### ISSUE TITLE
Support for node.js modules/globals

### ISSUE THREAD

**Issue by cem2ran** [wallabyjs/public#1]
Is node.js supported? Here I'm specifically thinking about how to deal with globals herein require('x_module') which throws a "ReferenceError: Can't find variable: require"

**Comment by ArtemGovorov** [comment]
Node.js/io.js test runner support is not there yet, but it is in plans.

**Comment by cem2ran** [comment]
Alrighty. Eagerly awaiting it!
This is the project I tried to run it with: https://github.com/Reactive-Extensions/RxJSKoans

**Comment by ArtemGovorov** [comment]
Thanks for the link. Node.js support is one the top priorities at the moment, I'll let you know once it's ready.

**Comment by TheCodeDestroyer** [comment]
:+1:

**Comment by ArtemGovorov** [comment]
Node.js and io.js are now supported - https://github.com/wallabyjs/public#environment-setting
