### ISSUE TITLE
Global variables do not work with latest

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1000]
### Issue description or question

I am not sure what is going on, but defining global variable in `setup` function does not propagate to the test. I downloaded your wallaby-jest-snapshots code, defined a global variable in the setup function but that variable was not available neither in file and in test.

```
setup: function () {
      global.aaa = "1";

      wallaby.testFramework.configure(require('./package.json').jest);
    }
```

and test

```
export class TestComponent extends React.Component<TestProps, {}> {
  render() {
    console.log(aaa) // aaa is not defined
     ...
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.ts*',
      'src/**/*.snap',
      'package.json',
      '!src/**/*.spec.ts*'
    ],
    tests: [
      'src/**/*.spec.ts*'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "commonjs", target: "es6", jsx: "react"})
    },

    testFramework: 'jest',

    setup: function () {
      global.aaa = "1";

      wallaby.testFramework.configure(require('./package.json').jest);
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.9

### OS name and version

OSX

**Comment by tomitrescak** [comment]
OK, seems to be Jest thing (was using mocha till now). This solves the problem:

```
const jconfig = require('./package.json').jest;
      jconfig.globals = {
        aaa: "1"
      }
```

**Comment by ArtemGovorov** [comment]
Yep, jest is [using an isolated vm](https://github.com/facebook/jest/blob/master/packages/jest-environment-node/src/index.js#L30) to run tests, so you need to [use the globals object](https://facebook.github.io/jest/docs/configuration.html#globals-object). 

```javascript
    setup: function () {
      var jestConfig = require('./package.json').jest;
      jestConfig.globals = {
        aaa: '1'
      };
      wallaby.testFramework.configure(jestConfig);
    }
```
