### ISSUE TITLE
Inline reporting for async tests?

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1001]
Hello,

Is it possible to refactor my async test, so that I can get the same inline reporting as the synchronous test?

Here's a screenshot of what I mean (`calculatorAsync` returns a Promise):

![screen shot 2017-02-08 at 15 22 17](https://cloud.githubusercontent.com/assets/1718128/22741277/e89510ce-ee12-11e6-98ca-57533a536015.png)

**Comment by bfulop** [comment]
This seems to work, but not very elegant:

![screen shot 2017-02-08 at 15 36 41](https://cloud.githubusercontent.com/assets/1718128/22741743/8bf08db0-ee14-11e6-8853-66b6c7dea5c1.png)

**Comment by bfulop** [comment]
A bit less lines of code:

![screen shot 2017-02-08 at 15 51 55](https://cloud.githubusercontent.com/assets/1718128/22742302/96d9332e-ee16-11e6-9f8a-9e0555ac462a.png)

If you have a better suggestion, I'm open to it! 🙂

**Comment by bfulop** [comment]
Finally I think I can live with this pattern:

![screen shot 2017-02-08 at 15 58 26](https://cloud.githubusercontent.com/assets/1718128/22742559/79848214-ee17-11e6-8dd7-06601fb5e304.png)

You can close this issue, unless this can be made even cleaner...

**Comment by ArtemGovorov** [comment]
Unfortunately it is a limitation of the `chai-as-promised` library. It's not wallaby.js specific - the library doesn't report the test line in the error stack, so neither plain mocha, nor wallaby can display the failing line:

![screen shot 2017-02-09 at 2 29 16 pm](https://cloud.githubusercontent.com/assets/979966/22769513/ea021200-eed4-11e6-9559-5378bb264f61.png)

unlike a simple sync test where both mocha and wallaby are able to report the line:

![screen shot 2017-02-09 at 2 29 50 pm](https://cloud.githubusercontent.com/assets/979966/22769568/41749468-eed5-11e6-8abe-1f5ca5b8ca33.png)

Unfortunately the `chai-as-promised` maintainer [decided not to accept the pull request](https://github.com/domenic/chai-as-promised/pull/155) that is addressing this exact issue. There are a few possible workarounds discussed in there and the one you are using is a good one.

If I take [the file from pull request](https://raw.githubusercontent.com/meeber/chai-as-promised/6d1cd1fd80c713e1688088ea3a21704b4849b2ff/lib/chai-as-promised.js) and replace the `node_modules/chai-as-promised/lib/chai-as-promised.js` file locally, it starts working:

![screen shot 2017-02-09 at 2 40 22 pm](https://cloud.githubusercontent.com/assets/979966/22769665/dd5ed88e-eed5-11e6-9171-3c29c80105e5.png)

So, as a possible alternative, you may consider forking the `chai-as-promised` repo and using the modification to make it work.
