### ISSUE TITLE
Jest snapshots tests errors on wrong line

### ISSUE THREAD

**Issue by yleflour** [wallabyjs/public#1002]
### Issue description or question
When I run my test on a React project, if a snapshot test is before another test, the error is displayed on the last test and not only on the snapshot test.

<img width="947" alt="screen shot 2017-02-09 at 00 02 17" src="https://cloud.githubusercontent.com/assets/1863461/22761507/527a6082-ee5b-11e6-97c6-50051892c8ea.png">

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      'package.json',
      'src/**/__snapshots__/*.snap',
      '!src/**/__tests__/*.js',
      '!src/**/*.test.js',
    ],

    tests: [
      'src/**/__tests__/*.js',
      'src/**/*.test.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: [
          'react-native',
          'react-native-stage-0/decorator-support',
        ],
        plugins: [
          'transform-flow-strip-types',
          'transform-object-rest-spread',
          'transform-async-to-generator',
        ],
      }),
    },

    setup: (wallaby) => {
      wallaby.testFramework.configure(require('./package.json').jest);
    },
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.9.0

### OS name and version
OSX 10.11.6

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue was caused by the `react-native` preset setting the `compact: true` flag for babel, which breaks source map generation. We're setting it to `false` by default in wallaby now, so [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) should work for you.
