### ISSUE TITLE
VS Code: if I log an array with strings such as `console.log(['1'])` nothing will show inline

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1003]
in VS Code if I log an array with strings such as `console.log(['1'])` nothing will show inline. Here's a screenshot of what I'm talking about: 

https://www.dropbox.com/s/no2ewkwiiv6gt6e/Screenshot%202017-02-08%2021.58.38.png?dl=0

Perhaps it's a VSC 1.9 issue. I don't remember seeing this issue before. 

### Code editor or IDE name and version
Visual Studio Code v1.9

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It is [the issue in VS Code](https://github.com/Microsoft/vscode/issues/19922) and the fix should hopefully be published soon in the recovery release.

However, we have published a fix in wallaby.js to address the issue. Do you have the latest version of wallaby.js extension installed? Should be working in v1.0.43

<img width="292" alt="screen shot 2017-02-09 at 4 05 14 pm" src="https://cloud.githubusercontent.com/assets/979966/22771298/966b52ca-eee1-11e6-897e-c5a273aca0d2.png">

**Comment by faceyspacey** [comment]
I do have 43:

https://www.dropbox.com/s/oqnomxwk9iokvqz/Screenshot%202017-02-08%2022.12.24.png?dl=0

**Comment by faceyspacey** [comment]
oh my bad, i needed to update. it's updated and it works.
