### ISSUE TITLE
Backslashes in line reports when using the VSCode Insiders Build 1.10.0

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1004]
### Issue description or question

In my inline test reports I'm seeing backslashes (in front of spaces). 

![screen shot 2017-02-09 at 10 33 04](https://cloud.githubusercontent.com/assets/1718128/22777346/31ed5bfa-eeb3-11e6-9ccf-9636630d477d.png)

I don't see these escape characters in your demos or screenshots. Do you know where they could be coming from?

### Wallaby.js configuration file

I'm using the [NodeJS calculator example](https://github.com/wallabyjs/wallaby-node-iojs-sample/)

### Code editor or IDE name and version

Visual Studio Code V1.10.0-Insider
Wallaby Extension 1.0.43,  Wallaby.js Core v1.0.374

### OS name and version

OSX

**Comment by bfulop** [comment]
I tested with the regular Visual Studio Code v1.9.1 and looks ok. 

So this has to do with the insiders version.

**Comment by ArtemGovorov** [comment]
Thanks for the report.
We have fixed it in the Visual Studio Code V1.10.0-Insider in the latest Wallaby Extension 1.0.43.
