### ISSUE TITLE
WallabyJs broken with VSCode 1.9.1

### ISSUE THREAD

**Issue by oshalygin** [wallabyjs/public#1006]
### Issue description or question
![image](https://cloud.githubusercontent.com/assets/7675942/22795268/ee7d5058-eeaa-11e6-99c1-3ce128c47a01.png)

### Wallaby.js configuration file

```javascript
/* eslint-disable */

module.exports = function (wallaby) {
  "use strict";
  return {
    files: [
      "client/**/*.js*",
      "client/**/*.css",
      "server/**/*.js",
      "!client/**/*.json",
      "!client/**/*.spec.js*",
      "!server/**/*.spec.js*",
      { pattern: "/**/*.png", load: "null" }
    ],

    tests: [
      "client/**/*.spec.js",
      "server/**/*.spec.js"
    ],
    env: {
      type: "node",
      runner: "node",
      params: {
        env: "NODE_ENV=test"
      }
    },
    compilers: {
      "**/*.js*": wallaby.compilers.babel({
        presets: ["react", "es2015"],
        plugins: ["transform-object-rest-spread"]
      })
    },
    // Toggle when you experience caching issues

    // workers: {
    //   recycle: true
    // },

    setup: function () {
      require("css-modules-require-hook")({
        generateScopedName: "[path]___[name]__[local]___[hash:base64:5]"
      });

      const noop = () => { };
      require.extensions[".ico"] = noop;
      require.extensions[".png"] = noop;
      require.extensions[".svg"] = noop;

      const jsdom = require("jsdom").jsdom;
      const exposedProperties = ["window", "navigator", "document"];

      global.document = jsdom("");
      global.window = document.defaultView;
      Object.keys(document.defaultView).forEach((property) => {
        if (typeof global[property] === "undefined") {
          exposedProperties.push(property);
          global[property] = document.defaultView[property];
        }
      });

      global.localStorage = {
        getItem: function () { },
        setItem: function () { }
      };

      global.navigator = {
        userAgent: "node.js"
      };

      documentRef = document; //eslint-disable-line no-undef
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.9.1

### OS name and version

OSX

I tried reinstalling the extension, no dice.  Everything was working pretty well up until they released the recovery patch of `1.9.1` on VSCode.  I may have to try to find a way to rollback to `1.9`, Wallaby is something I use on a regular basis.

**Comment by oshalygin** [comment]
Oh, lately I've been having issues with erroneous errors if I don't recycle the workers, so I just toggle my badboy up in the config.  If anyone has a good solution to this let me know 💃

**Comment by oshalygin** [comment]
Resolved with the latest wallaby update!! Thanks guys!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> Oh, lately I've been having issues with erroneous errors if I don't recycle the workers, so I just toggle my badboy up in the config. If anyone has a good solution to this let me know

Given that `workers: {recycle: true}` helps, it means that one of the node modules that you're using caches something on a process level. A [couple of techniques for dealing with are described in this docs section](https://wallabyjs.com/docs/integration/node.html#node-process-reuse). 

If there's an indication of what module is causing the issue, then you may just delete the cache for the module:
```javascript
module.exports = wallaby => {
  return {
    ...
    setup: function (w) {
      delete require.cache[require.resolve('module_with_state')];
    }
  };
};
```

If you suspect several modules, or would to delete cache for all user modules, you may do this:

```javascript
module.exports = wallaby => {
  return {
    ...
    setup: function (w) {
      Object.keys(require.cache)
              // you may try only resetting cache for specific modules
              // by filtering them by name
              .filter(function (k) { return ~k.indexOf(w.localProjectDir); }) // && ~k.indexOf('suspect_module_with_state')
              .forEach(function (k)  { delete require.cache[k]; });
    }
  };
};
```
By gradually including/or bisecting modules by name (and trying if it helps) you may find the offending module and exclude it. For example, I have heard that some react modules do some caching, so you may try this:

```javascript
module.exports = wallaby => {
  return {
    ...
    setup: function (w) {
      Object.keys(require.cache)
              .filter(function (k) { return ~k.indexOf(w.localProjectDir) && ~k.indexOf('react'); })
              .forEach(function (k)  { delete require.cache[k]; });
    }
  };
};
```
