### ISSUE TITLE
Jest Snapshot Testing with VS Code

### ISSUE THREAD

**Issue by Knaackee** [wallabyjs/public#1007]
Ive using VS Code with WallabyJS and my project uses Jest as the Unit Test Framework.

Ive read the [Jest snapshot testing on steroids with Wallaby.js](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0#.6ztmjrpg8) article.

1. If i run the jest command a "__snapshots__" directory gets created but not if i use wallabyjs. Why is that and how to fix it ?
2. If i change the assertion the test fails as expected. Then i try to update the snapshot using the "Run line tests" command but nothing happens. The test still fails. (no new information in the output window).

**Comment by ArtemGovorov** [comment]
Does it work for you on the sample project from the article https://github.com/wallabyjs/wallaby-jest-snapshots? If yes, then please share a sample project where it doesn't work for you.

**Comment by Knaackee** [comment]
Ive checked the test project and it is working as expected.
After i looked for differences in the wallaby.js file. 

I added 

    setup: function () {
      wallaby.testFramework.configure(require('./package.json').jest);
    }


to my wallaby.js file and now it is working.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by justafreak** [comment]
Why do we need to specify a config? In your example that config is empty? Isn't this step optional?

**Comment by ArtemGovorov** [comment]
@justafreak It's a good point, doesn't seem to work without specifying the config. I'll have a deeper look and let you know.

**Comment by ArtemGovorov** [comment]
@justafreak It turned out to be the an small timing issue in our code. The issue is foxed and will be released in the next core version, so that even if the config is not specified - it'll still work. Thanks for noticing and reporting it.
