### ISSUE TITLE
Visual Studio Code UI - Breakpoints and Wallaby Test Indicators

### ISSUE THREAD

**Issue by Knaackee** [wallabyjs/public#1008]
In Visual Studio code the wallaby.js icons are overlapping the breakpoints.
I am not able to see a breakpoint. 

Is there any solution to this problem?

**Comment by ArtemGovorov** [comment]
Unfortunately it's a current limitation of the VS Code UI. Here's the issue in the VS Code repo: https://github.com/Microsoft/vscode/issues/5923, feel free to subscribe and vote for it.
