### ISSUE TITLE
Support ...  Release note & feature idea 

### ISSUE THREAD

**Issue by yongoh** [wallabyjs/public#101]
How are you doing?   I'm a big fan of Wallaby, and think you made great job! 

1. I cannot find release not from your site.  Could you let me know where is it? 

2. It would be awesome if you could provide a inline object inspector which shows properties & values of selected object as WebStorm does.

**Comment by ArtemGovorov** [comment]
Thank you for your support!

Our changelog is here - https://github.com/wallabyjs/public/blob/master/CHANGELOG.md

We plan to support debugger like experience in wallaby, here is the feature request for it - https://github.com/wallabyjs/public/issues/74. Or do you mean some other user experience without breakpoints?

**Comment by ArtemGovorov** [comment]
Have also added a link to the changelog to wallaby website (to the roadmap section).

**Comment by yongoh** [comment]
Dear Artem, 

#2 : To make it clear, I'm longing for a debug screen like below screenshot which shows values from variables.
   http://blog.jetbrains.com/idea/files/2011/03/debugtoolwindow.png

Thanks!

**Comment by ArtemGovorov** [comment]
Thanks! Debugging experience like on the screenshot that you have attached will be a part of https://github.com/wallabyjs/public/issues/74 implementation.
