### ISSUE TITLE
Sublime package breaks duplicate line keyboard shortcut

### ISSUE THREAD

**Issue by bboyle** [wallabyjs/public#1010]
### Issue description or question

Wallaby grabs `ctrl+shift+d` for "debug_wallaby"

Sublime uses `ctrl+shift+d` for "duplicate_line"

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

Sublime Text v3

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the updated version is published (should be available within an hour).
