### ISSUE TITLE
Unexpeced token import occurs on future test runs, but not first test run.

### ISSUE THREAD

**Issue by BrianHanechak** [wallabyjs/public#1013]
### Issue description or question
I'm running into an issue where my tests fail to run with messages like this:

[Error] Runtime error: Uncaught SyntaxError: Unexpected token export​​
​​[Error] at http://localhost:51088/__modules/91.js?1487003566994:1​​
​​​​​[Info]​​​​​ Mon, 13 Feb 2017 16:34:27 GMT wallaby:workers Failed to map the stack to user code, entry message: Uncaught SyntaxError: Unexpected token export, stack: Uncaught SyntaxError: Unexpected token export
​​​​​[Info]​​​​​ at http://localhost:51088/__modules/91.js?1487003566994:1
​​​​​[Info]​​​​​ Mon, 13 Feb 2017 16:34:27 GMT wallaby:workers Sandbox (active) [xexr0] error: Uncaught SyntaxError: Unexpected token import
​​[Error] Runtime error: Uncaught SyntaxError: Unexpected token import​​
​​[Error] at http://localhost:51088/__modules/98.js?1487003567000:1​​
​​​​​[Info]​​​​​ Mon, 13 Feb 2017 16:34:27 GMT wallaby:workers Failed to map the stack to user code, entry message: Uncaught SyntaxError: Unexpected token import, stack: Uncaught SyntaxError: Unexpected token import

However, they don't happen the first time the tests run after wallaby is started. They only happen after tests are run and changes are detected, and this error doesn't occur reliably. It seems like stopping and starting wallaby causes the problem to resolve itself, but it comes back. This problem also didn't happen 1-2 weeks ago, but started happening more recently... it might be correlated with a change from phantomjs to electron, but I'm not sure.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'scripts/**/*.ts', load: false },
      { pattern: 'scripts/**/*-spec.ts', ignore: true },
      { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },      
    ],

    tests: [
      { pattern: 'scripts/**/*-spec.ts', load: false }
    ],

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    debug: true,

    preprocessors: {
      '**/*.js': file => require("babel-core").transform(file.content, {
        sourceMap: true,
        compact: false,
        presets: ["es2015"]
      })
    },
    
    setup: function () {
      window.__moduleBundler.loadTests();
    }    
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.9.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
It looks like original (not compiled/preprocessed) files are being loaded.
This may happen if some of your file are importing other files with the `.ts` extension, like `import a from './aModule.ts'`, but the error would show up during the first run as well. May be related to some other tricky imports.

When you see the error next time:

> [Error] Runtime error: Uncaught SyntaxError: Unexpected token export​​
> ​​[Error] at http://localhost:51088/__modules/91.js?1487003566994:1​​

could you please open the url `http://localhost:51088/__modules/91.js` (there'll be a different port there as it is dynamic), and paste the content here?

Also, please make sure you're using the latest version of the `wallaby-webpack` node module.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
