### ISSUE TITLE
Getting ENV variables from .envrc

### ISSUE THREAD

**Issue by jccpdev** [wallabyjs/public#1016]
### Issue description or question

I need Wallabyjs to run to get the ENV variables from a .envrc file.

Usually, those are set by using the `direnv allow ./` command before I run the project.

Any ideas on how to get the same result? 

### Wallaby.js configuration file

```javascript
{
    "files": [
        "src/**/*.js"
    ],
    "tests": [
        "tests/**/*Test.js"
    ],
    "env":{
        "type":"node"
    },
    "testFramework": "mocha"
}
```

### Code editor or IDE name and version

PHPStorm 2016.2.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
You may install the `dotenv` module
```
npm i dotenv --save-dev
```
then rename your wallaby to `.js` (if you are using wallaby.json at the moment), and use the installed module to load the environment variables:

```javascript
require('dotenv').config({path: '.envrc'});

module.exports = function () {
  return {
    "files": [
      "src/**/*.js"
    ],
    "tests": [
      "tests/**/*Test.js"
    ],
    "env": {
      "type": "node"
    },
    "testFramework": "mocha"
  }
};
```

**Comment by jccpdev** [comment]
That, unfortunately, did not work. We are using https://github.com/direnv/direnv so the .envrc looks like this 

```
export ENV_VARIABLE=VALUE
```
so the dotenv lib does not work. I can probably get around this be doing the same thing the dotenv lib is doing and read the .envrc files and parse the lines and sets them as env variables. 

However, I thought there might have been a more elegant solution.

If you have one I would love to hear it or if not it sounds like a good problem for you guys to solve. 
It would make the integration with different development environment easier.

By the way excellent product I love it.

**Comment by ArtemGovorov** [comment]
> I can probably get around this be doing the same thing the dotenv lib is doing and read the .envrc files and parse the lines and sets them as env variables.

That'd probably be the best option. I tried re-using the most of the `dotenv` module, while still removing the leading `export `, here's the quick solution I could come up with:

```javascript
var forEach = Array.prototype.forEach;
Array.prototype.forEach = function () {
  var cb = arguments[0];
  arguments[0] = function () {
    var str = arguments[0];
    if (str && ~str.indexOf('export ')) arguments[0] = str.substr(7);
    return cb.apply(this, arguments);
  }
  return forEach.apply(this, arguments);
}
require('dotenv').config({path: '.envrc'});
Array.prototype.forEach = forEach;

module.exports = function () {
  return {
    "files": [
      "src/**/*.js"
    ],
    "tests": [
      "tests/**/*Test.js"
    ],
    "env": {
      "type": "node"
    },
    "testFramework": "mocha"
  }
};
```

I'm not familiar with the `direnv` format and have never used it, but if it's just the same as `dotenv` but with teh leading `export ` then it should work.

> However, I thought there might have been a more elegant solution.

Wallaby config is a small node program where one can do pretty much anything, so if there's a node module that supports the `direnv` format, then it'd be a more elegant solution. But I couldn't find any node modules supporting `direnv`.

> By the way excellent product I love it.

Thanks.

**Comment by schickling** [comment]
Given the last response was from 4 years ago, is there by now a more "elegant" solution for this?

**Comment by smcenlly** [comment]
@schickling - we don't have any update on how to load `dotenv` or `direnv` files. Out of interest, which format are you using?

**Comment by schickling** [comment]
I'm using `direnv` (i.e. `.envrc` files).

I've ended up using [dotenvrc](https://github.com/reedom/dotenvrc) in my Jest setup files. Using it in the `wallaby.js` file as mentioned above also didn't work.
