### ISSUE TITLE
webpack 2  doesn't allow ts on config object

### ISSUE THREAD

**Issue by davidmoshal** [wallabyjs/public#1018]
### Issue description or question

Upgraded my project to Webpack 2, ran wallabyjs and got this error:
```
Postprocessor run failure: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'ts'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           ts: ...
         }
       })
     ]

```

### Wallaby.js configuration file

```javascript
const webpack = require('webpack');
const webpackConfig = require('./webpack.config');
const wallabyWebpack = require('wallaby-webpack');

module.exports = function (wallaby) {

  // had to comment this out because webpack.resolve is null
 // webpackConfig.resolve.extensions = ['', '.js', '.vue'];
  webpackConfig.ts = webpackConfig.ts || {}

  /*
   Previously we had this in webpack.config.js:
   ts: {
     logLevel: 'warn',
     appendTsSuffixTo: [/\.vue$/]
   },
   */
  webpackConfig.ts.compilerOptions = {
    baseUrl: wallaby.localProjectDir,
    paths: {'*': ['./node_modules/*']}
  };
  const wallabyPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {pattern: 'tsconfig.json', load: false},
      {pattern: 'src/**/*.*', load: false}
    ],

    env: {
      type: 'browser'
    },

    tests: [
      {pattern: 'test/**/*.spec.ts', load: false},
    ],

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    hints: {
      ignoreCoverage: /ignore coverage/
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm 2016.3.3
Build #WS-163.12024.17, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX Sierra 10.12.3 (16D32)

**Comment by davidmoshal** [comment]
yet this works fine:
```
module.exports = function (w) {

  return {
    files: [
      'src/**/*.ts'
    ],

    tests: [
      'test/**/*Spec.ts'
    ]
  };
};
```
do I need any of the previous config options??

**Comment by davidmoshal** [comment]
This seems to work as long as I don't use the bundled node. ie: changing to node 7.4 seems to let this work:

```es6
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./webpack.config');

module.exports = function (w) {

  const wallabyPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {pattern: 'tsconfig.json', load: false},
      {pattern: 'src/**/*.*', load: false}
    ],

    env: {
      type: 'browser'
    },

    tests: [
      //{pattern: 'src/**/*.spec.ts', load: false}, // interspersing tests in code
      {pattern: 'test/**/*.spec.ts', load: false},
    ],

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    hints: {
      ignoreCoverage: /ignore coverage/
    },

    debug: true
  };
};
```

Do I need use any of the previous options,  which I was using with Webpack 1 and Typescript and Vue? :

```js
  webpackConfig.resolve.extensions = ['', '.js', '.vue'];
  webpackConfig.ts = webpackConfig.ts || {}
   ts: {
     logLevel: 'warn',
     appendTsSuffixTo: [/\.vue$/]
   },
  webpackConfig.ts.compilerOptions = {
    baseUrl: wallaby.localProjectDir,
    paths: {'*': ['./node_modules/*']}
  };
```

Note: although I'm using Vue, I'm currently not using any `*.vue` files because they don't support Typescript (at least not in my IDE).

David

**Comment by ArtemGovorov** [comment]
> This seems to work as long as I don't use the bundled node

Webpack 2 is quite different from Webpack 1 in terms of configuration, and none of those settings that you've mentioned are wallaby specific, they are all Webpack or one of its loaders (vue-loader I think) specific.

> Do I need use any of the previous options, which I was using with Webpack 1 and Typescript 

If it's working for you without those settings with Webpack 2, then I'd just remove them. 

If something doesn't work, I'll need a specific sample to reproduce the error and try to see what's wrong. Please let me know if it's the case and also share the sample that I may use.

**Comment by davidmoshal** [comment]
Thanks, from above looks like the issue was 'ts' on the webpackConfig object.
So far everything is fine, but if I need to use `*.vue` files then there could be an issue.
Probably I should not update my vue-ts template that I sent you because most likely anybody else using Vue uses the `*.vue` file format.

**Comment by davidmoshal** [comment]
@ArtemGovorov still not working.

I created a sample repo:

https://github.com/davidmoshal/wallaby-webpack2-ts2-vue1

which uses: webpack2, typescript2 and vue1

It has a hot-reload dev server and build configuration which both work just fine.

However, the Wallaby.js test runner fails!

**Comment by davidmoshal** [comment]
@ArtemGovorov fixed a few things, only thing remaining is the path to included templates.
See the readme on the above project.

Dave

**Comment by ArtemGovorov** [comment]
@davidmoshal Have [sent you the PR](https://github.com/davidmoshal/wallaby-webpack2-ts2-vue1/pull/1). Wallaby needs [all (most of) source files that you're using to be specified in the `files` list](https://wallabyjs.com/docs/config/files.html).

**Comment by davidmoshal** [comment]
Thanks, that makes sense!

**Comment by davidmoshal** [comment]
Honestly: I can't believe how good WallabyJs is, never seen anything like it.
It is possible to debug a client written in VueJs, on the server, with realtime error checking.
@ArtemGovorov you have basically delivered on the promise Lighttable made for clojure programmers, not sure if you know that.

**Comment by ArtemGovorov** [comment]
Thanks @davidmoshal!
