### ISSUE TITLE
angular-cli; Can't find variable: Intl

### ISSUE THREAD

**Issue by nelisbijl** [wallabyjs/public#1019]
### Issue description or question

Testing code that uses the Javascript's standard build-in object Intl (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) will give the error **Can't find variable: Intl**

What do I need to configure to have the tests find the standard build-in object Intl?

### Wallaby.js configuration file

as in https://github.com/wallabyjs/ngCliWebpackSample

### Code editor or IDE name and version

WebStorm 2016.3.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Wallaby.js is using PhantomJs by default and PhantomJs doesn't support `Intl`. There are 2 options to make it work: 
- Option number 1 is to switch to [Chrome/Electron runner](https://wallabyjs.com/docs/integration/electron.html) in your wallaby.js config:
```javascript
module.exports = function () {
  return {
    ...
    env: {
      kind: 'electron'
    }
  };
};
```
plus 
```
npm install electron --save-dev
```
- Option number 2 is to install `Intl` polyfill and add it to the files list, in which case PhantomJs will still be able to run tests:
```javascript
module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'node_modules/intl/dist/Intl.js', instrument: false},
      ...
...
```
plus 
```
npm install intl --save-dev
```

**Comment by nelisbijl** [comment]
Thnx
