### ISSUE TITLE
cannot find 'require'  reference in library in node_modules

### ISSUE THREAD

**Issue by kimballjohnson** [wallabyjs/public#1021]
All your examples are designed for a WebStorm, VSCode, MS Website, or .NET Core type implementation. And I agree that is reasonable, since the MS integration of TypeScript with ASP.NET MVC 4/5 (the 'old' ASP.NET MVC, not the same as the deprecated ASP.NET 5.0 replaced by .NET Core)  is really designed as an Angular environment only, and therefore conceives itself as an environment designed to support the highly hybridized integration of Angular views in razor pages. So I forgive you for not attempting to solve this problem for the few of us stuck in this particular pocket of .NET migration/antiquation.

I am using your example, 'wallaby-chai-as-promised-master', the mocha version, for a Typescript project in an existing MS ASP.NET MVC 4 project in visual studio 2015 (not an angular project). That example gets me closest to a good compromise among the options of: node vs browser test runner, imported source for mocha, chai vs package.json and node_modules, and referencing JavaScript libraries (global or UMD modules) out of the node_modules folder (or maybe not).

First, without  an import of the ES6Promise folder in node_modules, the calculator.js raises a 'refrerence error indicator' about the ES6Promise namespace or Promise object/function unless an import of ES6Promise is created at the top of the file pointing to the /node_modules/ES6Promise folder. I've tried some versions of that import statement, and this one as described seems to work as well as any other.

But wallaby reports that the chai file in node_modules cannot find the 'require' function to perform its lookup of an internal reference. 

ReferenceError: Can't find variable: require
		at node_modules/chai-as-promised/lib/chai-as-promised.js:2

Therefore, I have concluded that I need to do a better job of referencing things in wallaby.js, and with the import statements, and the paths to the resources that those import statements use. That is the question I am asking: how do I get all the references in this hybrid situation working? 

Here's the progress I have made so far: 

1. add the project name and root slash to the paths in wallaby.js: /assistv2/node_modules, etc.
2. Adding the project name and root slash to paths in the tsconfig.json produces errors in the project build process stating that no outputs can be found (with '/assistv2/' added).
3. Adding the project name and root slash to the source and test file paths in wallaby.js prevents those files from being found. Adding a single slash before the Typescripts folder does not.
2. add an import statement for all missing libraries in the source files.

this gets me past the following issues:

Text content of Wallaby Failing Tests:
​​​​​"before each" hook for "should add numbers": Can't find variable: Calculator
		at Typescripts/tst/calculatorSpec.js:4
ReferenceError: Can't find variable: require
		at node_modules/chai-as-promised/lib/chai-as-promised.js:2
SyntaxError: Use of reserved word 'import'
		at Typescripts/src/calculator.js:1
ReferenceError: Can't find variable: require
		at node_modules/chai-as-promised/lib/chai-as-promised.js:2

At that point, I am stuck with the following:

'Show output from wallaby failing tests:'

​​​​​"before each" hook for "should add numbers": Can't find variable: calculator 
at Typescripts/tst/calculatorSpec.js:4
SyntaxError: Use of reserved word 'import'
		at Typescripts/src/calculator.js:1
ReferenceError: Can't find variable: chai
at http://localhost:3140/wallaby_sandbox0.html:10
ReferenceError: Can't find variable: chai

After that, commenting out the import statement for ES6Promise in the calculator.js causes a javascript missing reference for the namespace ES6Promise.

I am guessing that these errors are variations on the 'project path and root slash' issue that i fixed in the wallaby.js. But I don't know where in your infrastructure they occur, and I don't know where in your config system I need to make the changes. 

Finally, I hope to be able to use wallaby to test my Typescript files as well as any pure javascript files. with copies of your calculator javascript files, the calculatorSpec.ts shows more issues than the javascript version. 

Some Images:

[calculator.js and calculator.ts comparison](https://jfbldrs1-my.sharepoint.com/personal/kimball_johnson_engagile_com/_layouts/15/guestaccess.aspx?guestaccesstoken=C3S+pJUbc1R2aYQV1Tq/6c0M9W1YG5u8XNVY6hsKvSk=&docid=2_1b00007b793594b7b958ca8b6a3a73027&rev=1)

[calculatorSpec.js and calculatorSpec.ts comparision](https://jfbldrs1-my.sharepoint.com/personal/kimball_johnson_engagile_com/_layouts/15/guestaccess.aspx?guestaccesstoken=Red1tMMELYjmXmv5GxngJo/qjDP/hRVbkUJJ6QMIyjM=&docid=2_1a610342325454e6897156cb66dc94dda&rev=1)

[calculator.js image showing resharper test runner wanting to run in jasmine - also wallaby coverage and error reports](https://jfbldrs1-my.sharepoint.com/personal/kimball_johnson_engagile_com/_layouts/15/guestaccess.aspx?guestaccesstoken=3BIENOCeFKp21yzfDxCBl5fi88TeaTPbtoPegYdgthE=&docid=2_1de4f7dd345744b30b59b792b01e06473&rev=1)

[calculator uncovered regions image](https://jfbldrs1-my.sharepoint.com/personal/kimball_johnson_engagile_com/_layouts/15/guestaccess.aspx?guestaccesstoken=H2c1yNAJ93r09LCfShilR0Hs+WRnBdoBAk62yXFMnb0=&docid=2_18ff18f90818f485c9ab984bd3546842c&rev=1)

If you can give me some insight on those details, I will let you know of any further issues. Please stay with me until we can get this working as I am already 5 days into this research and I must get it all the way fixed.

Thanks,

Kimball Johnson

calculator.js: (this causes the ES6Promise namespace in .js or .ts to be recognized. it is not recognized without an import statement.
```
import * as ES6Promise from "node_modules/es6-promise";
var Calculator = function () {
    };
Calculator.prototype.add = function (a, b) {
  return ES6Promise.Promise.resolve(a + b);
};
```

So this is the wallaby.js that ships with that example. This is what I am using.

``` module.exports = function (wallaby) {
     return {
         files: [
           // PhantomJs Function.bind polyfill
           { pattern: '/assistv2/node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
           // ES6 promise polyfill
           { pattern: '/assistv2/node_modules/es6-promise/dist/es6-promise.js', instrument: false },

           { pattern: '/assistv2/node_modules/chai/chai.js', instrument: false },
           { pattern: '/assistv2/node_modules/chai-as-promised/lib/chai-as-promised.js', instrument: false },
           { pattern: 'Typescripts/src/**/*.ts' }
         ],

         tests: [
           { pattern: 'Typescripts/tst/**/*Spec.ts' }
         ],

         testFramework: "mocha",

         setup: function () {
             window.expect = chai.expect;
             var should = chai.should();
         }
     };
 };
```

```
tsconfig.json:
{
  "compilerOptions": {
    "target": "es6",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [ "node_modules/@types/" ],
    "outDir": "TypeScripts/Src/AcsDlg"
  },
  "compileOnSave": true,
  "include": [
    "TypeScripts/Src/AcsDlg/*.ts",
    "TypeScripts/Tst/AcsDlg/*.ts"
  ],
  "exclude": [
  ]
}
```

```
package.json
{
  "name": "ast-1226-accessibility",
  "version": "1.0.0",
  "description": "EFSecondLevelCache\r =======\r Entity Framework 6.x Second Level Caching Library.",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://engagilist@bitbucket.org/Governet/assistng.git"
  },
  "keywords": [],
  "author": "Kimball Johnson",
  "license": "ISC",
  "homepage": "https://bitbucket.org/Governet/assistng#readme",
  "dependencies": {
    "jquery": "^1.8.1"
  },
  "devDependencies": {
    "@types/chai": "^3.4.34",
    "@types/jquery": "^2.0.39",
    "@types/mocha": "^2.2.37",
    "@types/mocha-phantomjs": "^3.5.28",
    "@types/sinon-chai": "^2.7.27",
    "babel": "^6.23.0",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "es6-promise": "^4.0.5",
    "mocha": "^3.2.0",
    "mocha-phantomjs": "^4.1.0",
    "phantomjs": "^2.1.7",
    "phantomjs-polyfill": "0.0.2",
    "sinon": "^1.17.7",
    "sinon-chai": "^2.8.0"
  }
}
```

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
windows 10

**Comment by ArtemGovorov** [comment]
Could you please create a sample repo (including all config files and VS project files) where I could reproduce the issues? Happy to have a look to help with the config file.

**Comment by kimballjohnson** [comment]
hmm... the telerik escape: that's a matter of policy. I'm providing a great deal of information based on a great deal of research, work, testing and messing around (and a lot of pluralsight prep) because I think I have gotten it very close, and what's left seems to be focused on the wallaby/phantomjs implementation.
So I believe you will be able to recognize the issue if you read it. 

I'm a contractor on a commercial LOB project. I cannot give you a copy of the code. But if you will read and review my what I have provided, and nothing comes to your mind, I will be willing to do a generic asp.net4/mvc5 project and migrate my typescript integration to that and upload it for you.

How's that?

**Comment by ArtemGovorov** [comment]
> So I believe you will be able to recognize the issue if you read it.

I can see a few possible issues, however most of them are not wallaby.js related. In particular:
- you attempt to use `import *`, and you tsconfig.json targets ES6 so it emits import as is. However browsers don't support it yet, neither is PhantomJs which is used by wallaby as you know.
- `wallaby-chai-as-promised` sample is [using chai-as-promised v5.1](https://github.com/wallabyjs/wallaby-chai-as-promised/blob/master/package.json#L24). From the errors you've listed it doesn't seem like you're using the same version. Newer versions of are [using pure CommonJs](https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js), so can't be just included as scripts. Neither in wallaby, nor into a plain testing page or any other test runner. Webpack/Browserify bundlers (or node.js environment) can handle it no problem, but from the supplied configs it doesn't look like you're using Webpack or Browserify.
- you've mentioned that `I hope to be able to use wallaby to test my Typescript files as well as any pure javascript files`, however your `tsconfig.json` is simply missing the [`allowJs` option that allows to do so](https://www.typescriptlang.org/docs/handbook/compiler-options.html).

> I'm a contractor on a commercial LOB project. I cannot give you a copy of the code. But if you will read and review my what I have provided, and nothing comes to your mind, I will be willing to do a generic asp.net4/mvc5 project and migrate my typescript integration to that and upload it for you.

I understand it and I wasn't asking for a copy of a real project. There are a few possible issues (and I described some above) come to my mind after the review of your post. 

However, as I have mentioned, none of those I see are wallaby specific issues, so I need to understand how your project is supposed to work in production (even without wallaby) given that you're targeting ES6 without babel compilation, trying to use CommonJs without Webpack/Browserify, etc. To provide you any help that is out-of wallaby.js project scope, I need more information from you.

So yes, please create a generic sample with your configs and as many details from your real app as you can (like folder structure, real `tsconfig.json` and `package.json`). It doesn't need to contain real source files and tests, a coupe of dummy ones is ok (as long as they demonstrate teh issues you're encountering).

**Comment by kimballjohnson** [comment]
Artem,
I appreciate this very much. I will check out those items you mentioned and then I will create a new asp.net mvc project and migrate my settings and typescript project over and send it to you.
Thanks again,
Kimball Johnson

**Comment by kimballjohnson** [comment]
[Engagile.zip](https://github.com/wallabyjs/public/files/798806/Engagile.zip)

I have attached a new ASP.NET 4 MVC 5 project with the basic typescript infrastructure I am trying to configure.  I have spent some time with various consultants working through the very basic issues and here's a more defined description of my goal:

1. utilize Typescript 2.1.1 and ongoing versions.
2. target es5 javascript code generation.
3. use the npm @types infrastructure 
4. use es2016/typescript module referencing
5. do not use triple-slash library referencing, even for types
6. make all references to javascript libraries in tsconfig.json and wallaby.json consistent, identical and non-conflicting
7. do not reference or use javascript libraries directly in typescript source code and exclusively use d.ts files for external js libraries and let the typescript compiler generate the actual js library code
8. use absolute referencing for @types-referenced libraries and do not reference dependent libraries
9. always know or be able to determine which of the previous items is the basis for each referencing problem.

With regards to wallaby, its clear that your functionality could not be achieved without quite a lot of integration into the wallaby tool. However the overlap and interactions or interferences between the references in tsconfig, in the various files, in node_modules, and in wallaby.js are the ongoing source of not-knowing-ness, for which the on-line community is simply the noise of the coming tidal wave of new confusion.  I just need to find the 'one way of referencing' that will work for maybe a year. 

Thanks,
Kimball Johnson

**Comment by ArtemGovorov** [comment]
Thanks for the sample project. There are still a couple of things that are not clear to me, that are not wallaby related but I need to understand in order to suggest a working config.

> 2. target es5 javascript code generation.
> 4. use es2016/typescript module referencing

These 2 mean that you are going to be generating CommonJs ES5 code. 

This is how TypeScript compiles ES2016/TypeScript `import`-s:
```javascript
import Calculator from "../Src/Calculator";
```
becomes:
```javascript
var Calculator_1 = require("../Src/Calculator");
```
You may see it in the `Typescripts/Tst/calculatorSpec.js` compiled file that is included in your attached project. In its turn,
```javascript
export default Calculator;
```
becomes 
```javascript
exports.default = Calculator;
```
You may see it in the `Typescripts/Src/calculator.js` compiled file that is included in your attached project.

As you know, browsers don't support CommonJs, neither `require`, not `exports` is defined in a browser environment. And this is exactly what wallaby.js errors are telling you:
```
Runtime error: ReferenceError: Can't find variable: exports
Runtime error: ReferenceError: Can't find variable: require
```

My question is, how is your (CommonJs) application supposed to be built to run in browser in production (without wallaby)?

**Comment by kimballjohnson** [comment]
Ok, I understand. This is the problem I'm facing. I cannot find any content that gives all the considerations, contingencies, consequences, constraints, and their conclusions necessary to make an informed decision about an overall successful combination of settings. But when it comes to which settings will work within a set of procedures for referencing in files using d.ts referencing techniques, js library referencing techniques, and module referencing techniques. I can find all of those individually, or more accurately I can find fragments and commentary about fragments, but no where is there any comprehensive guidance.

So the fragment you are providing to me here is that the setting of target:es5 produces commonJs, which would be appropriate for server-side node.js. But what I will need for testing a Typescript library intended to be used in a browser-based app like asp.net mvc would have to be es6? or es2016?

Then, based on that change, we would need to ripple through all the other settings to establish compatibility among all the settings. And we would need to consider again the techniques for d.ts referencing, js library referencing, and module referencing to make sure that the transpiled result of those choices would be compatible with the transpilation process specified by es6, es2015, or es2016.

As an example of what i'm up against, consider the lack of usable information in this post: http://stackoverflow.com/questions/27573365/how-to-use-typescript-with-native-es6-promises

In general, it seems obvious that there should be some selection of typescript settings for node.js browser apps, others for node.js server apps, and others for html/asp.net browser apps, and js libraries written in typescript, which is what I am doing.

Why such likely combinations aren't described and well-known, but have to be intuited, guessed at, or (as I am doing) begged for, seems astounding.

I will see how far i can get with those three settings and get back to you.

Thanks,

**Comment by ArtemGovorov** [comment]
There're 2 separate aspects of configuring TypeScript (not wallaby) in/for your project:
- TypeScript types/type checking settings,
- TypeScript compilation target/module settings.

These 2 aspects are quite independent, ie. the way you compile your ES6 module imports (to ES5 with CommonJs or ES5 with AMD, or ES5 with System.js, etc.), should not affect your choice of how you handle TypeScript types (@types/triple slashes/typings module/.d.ts files). You may use any combination of those.

I'm going to skip the "TypeScript types/type checking settings" aspect, as wallaby.js is 100% agnostic of the way you handle TypeScript types. Wallaby.js doesn't use/need `.d.ts`, doesn't even care if there're some type related issues in the app. It is the job of the TypeScript compiler integrated into your IDE.

As for the "TypeScript compilation target/module settings", wallaby.js is just using whatever is configured in your `tsconfig.json`. 

> This is the problem I'm facing. I cannot find any content that gives all the considerations, contingencies, consequences, constraints, and their conclusions necessary to make an informed decision about an overall successful combination of settings.

I suggest to figure this out first and find out how your application is going to work in production, ie. to set up your build process first. Once you have it, it's relatively easy to just tell wallaby.js to do the same.

Given you'd like to use ES6/Typescript imports, and target ES5, here are your options:
- Use `"module": "CommonJs"/"UMD"` and bundle your app for browser using [Webpack](https://webpack.github.io/) or [Browserify](http://browserify.org/). These module bundlers understand CommonJs/UMD and are able to build a browser compatible bundle.
- Use `"module": "SystemJs"` with [System.js module loader](https://github.com/systemjs/systemjs).
- Use `"module": "AMD"/"UMD"` with [require.js module loader](http://requirejs.org/).

I've got to tell that using/learning these tools is not easy, and it may take you some time to select the stack that suits your app, and get up to speed. But, just in case if it's not obvious, I'd like to stress that all these challenges are not wallaby.js related and the tool supports all of the listed choices. So once you selected your stack and have your app building and working in browser, you may find the corresponding docs section for the selected tech under the "Supported technologies" title in [our docs](https://wallabyjs.com/docs/).

Hope this helps.

**Comment by kimballjohnson** [comment]
Artem, you have been both kind and generous with me and your time. I appreciate it very much. As you can tell, I'm serious about making this work. And I've been working hard on all these issues for three years already. This week I paid an open-source developer to walk me through his understanding in order to confirm my understanding of the transpilation and the output process.  Your explanations have also given me confidence through confirmations. I'm stuck with things that can be reasonably be expected to work in a previous-generation MS project. I am now able to switch the output between common.js and require.js loaders. So i'm going with require.js because I only need to produce a browser-loaded js library at present. In any case, I believe you have gotten me where I need to be. 
Thanks again,
And I wish you much success with Wallaby, its a masterful concept, and a pleasure to work with!
Kimball Johnson

**Comment by ArtemGovorov** [comment]
Thanks for the update Kimball. Let me know once you finish setting the build process up and get to configuring wallaby, and have some questions, happy to help.
