### ISSUE TITLE
angular2-webpack-starter tests dont run with wallabyjs from old fork

### ISSUE THREAD

**Issue by yaroslavya** [wallabyjs/public#1022]
### Issue description or question
I tried to get the angular-class project to have wallabyjs up and running with it. For that I took your fork of it: https://github.com/wallabyjs/angular2-webpack-starter and grabbed the wallabyjs config. When I run the tests I get the following errors in wallaby console:

Error: Module parse failed: .\src\app\about\about.component.spec.ts Unexpected token (17:26)
You may need an appropriate loader to handle this file type.
|         useValue: {
|           data: {
|             subscribe: (fn: (value: Data) => void) => fn({
|               yourData: 'yolo'
|             })
at http://localhost:34654/__modules/492.js?1487287624635:1

Link to my fork of angularclass: https://github.com/yaroslavya/angular2-webpack-starter
Let me know if anything else is needed.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm 2016 2.4

### OS name and version
Windows 8.2

**Comment by ArtemGovorov** [comment]
I have [updated the fork readme](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/README.md) with instructions on how to make it work.

In your case you'll need to:

- [Move](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/spec-bundle.js#L41) karma specific hack from the `config/spec-bundle.js` file to a [separate file](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/karma-require.js) called `karma-require.js`.
- Run `npm install angular2-template-loader null-loader --save-dev`.

Let me know if this works for you (I quickly tried on your repo and it works for me).

**Comment by yaroslavya** [comment]
Wow, that was fast! Did all that, still have some issues:
Module not found: Error: Can't resolve 'null' in 'C:\Programming\github\angular2-webpack-starter'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'null-loader' instead of 'null'.ModuleNotFoundError: Module not found: Error: Can't resolve 'null' in 'C:\Programming\github\angular2-webpack-starter'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'null-loader' instead of 'null'.
I checked that I have the null-loader in my node_modules. Do I need to use it anywhere?
Note that tests by `npm run test` are running successfully. Also I noticed that you have a `require("ts-helpers")` in your spec-bundle.js and tried with and without it - no changes.

So currently 7 tests are failing and 4 are passing. Heres one of the errors:
src/app/app.component.spec.ts App should log ngOnInit [419 ms]

	Failed: Uncaught (in promise): Failed to load app.component.css

	Error: This test module uses the component AppComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.
		at src/app/app.component.spec.ts:30

	TypeError: undefined is not an object (evaluating 'comp.ngOnInit')
		at src/app/app.component.spec.ts:55

Let me know if you need the full wallabyjs log or anything or the full log of all the failing tests.  Also made you a collaborator, so you should be able to push your changes into the repo.

**Comment by ArtemGovorov** [comment]
Went through the [readme](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/README.md) to do everything that is listed, and everything is working for me in your repo (I forgot to mention to update your wallaby config with the one from the repo). Have [pushed the changes](https://github.com/yaroslavya/angular2-webpack-starter/commit/b0845a1c467a118667400ff0a9c3550ab6e250e0).

**Comment by yaroslavya** [comment]
Thanks, Artem, works like a charm!
