### ISSUE TITLE
Cant get samples to run in VSCode

### ISSUE THREAD

**Issue by dotnetprofessional** [wallabyjs/public#1025]
### Issue description or question
VSCode does not work. Starting wallaby starts a status indicator in the bottom left corner of IDE which simply bounces back an forth forever.  I've tried the VSCode sample on the VSCode page as well as the wallaby-typescript-sample.git. Neither work and show the same issue.

### Wallaby.js configuration file
See samples

```javascript
// paste your config here
```
See samples

### Code editor or IDE name and version

Visual Studio Code v1.9.1

### OS name and version
Windows 10

TypeScript v2.1.6

Would really like to evaluate this for our team of 10+ developers... But can't get the basics working.

**Comment by ArtemGovorov** [comment]
Is there anything [displayed in the Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting)?

**Comment by dotnetprofessional** [comment]
Ok, so I did manage to get if half working. I selected the wallaby.js file initially as the config to use, and this provided the issue posted. However, if I do select the wallaby-node.js file, I do get it working for that test. Is there a dependency I'm supposed to have for that test? I notice its to do with a browser.

When it does fail to work I'm seeing this in the output window. Which doesn't seem very helpful.
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.379

**Comment by ArtemGovorov** [comment]
Did you set the `debug: true` flag as it is suggested in the docs section I referenced? If not, please do it and paste the full output from the output window.

**Comment by ArtemGovorov** [comment]
> Is there a dependency I'm supposed to have for that test?

Wallaby.js extension has the PhantomJs dependency for browser tests, however it is supposed to be installed automatically. Please try the following:
- check if PhantomJs executable is present in this folder: `c:\Users\UserName\.vscode\phantomjs_v2.1.1\`. If not, please try to re-install the extension.
- try using [Chrome/Electron runner](https://wallabyjs.com/docs/integration/electron.html) instead of PhantomJs.

**Comment by dotnetprofessional** [comment]
Thanks for the quick reply. I didn't notice the debug setting (might be a good thing to add by default for the samples). I checked and phantom is in the location you suggested. Here is the output:

`
[Info]​​​​​ Mon, 20 Feb 2017 19:41:46 GMT wallaby:project Wallaby config: d:\dev\git.public\spike\wallaby-typescript-sample\wallaby.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.380
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:46 GMT wallaby:fs File added: src/sayingsBrowser.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:46 GMT wallaby:fs File added: test/sayingsBrowserSpec.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:46 GMT wallaby:project File cache: C:\Users\GARRM\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.45\projects\924d607379144cce
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:47 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:47 GMT wallaby:project Config file change detected, invalidating local cache
​​​​​[Info]​​​​​ Wallaby App available at: http://wallabyjs.com/app/#/files
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:48 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:48 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:48 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:48 GMT wallaby:workers Web server is listening at 3327
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:48 GMT wallaby:project File cache requires some updates, waiting required files from IDE
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:phantomRunner Signal killed phantomjs #0: null, exit code: 3221225477
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:phantomRunner Signal killed phantomjs #1: null, exit code: 3221225477
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project File src/sayingsBrowser.ts changes are patches only: false
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project File test/sayingsBrowserSpec.ts changes are patches only: false
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project Preparing to process src/sayingsBrowser.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project Preparing to process test/sayingsBrowserSpec.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:49 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:processor No compilers found for src/sayingsBrowser.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project File src/sayingsBrowser.ts is not instrumented by core
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project No preprocessors configured for src/sayingsBrowser.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Writing to disk and caching processed file src/sayingsBrowser.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project File src/sayingsBrowser.ts changes saved, store ts: 1487387559192, change ts: 1487619709342
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:processor No compilers found for test/sayingsBrowserSpec.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project File test/sayingsBrowserSpec.ts is not instrumented by core
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project No preprocessors configured for test/sayingsBrowserSpec.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Writing to disk and caching processed file test/sayingsBrowserSpec.ts
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project File test/sayingsBrowserSpec.ts changes saved, store ts: 1487387559195, change ts: 1487619709345
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Preparing to process src/sayingsBrowser.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Preparing to process test/sayingsBrowserSpec.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Processing compiled src/sayingsBrowser.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Instrumenting src/sayingsBrowser.js, via process pool: false
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Processing compiled test/sayingsBrowserSpec.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Instrumenting test/sayingsBrowserSpec.js, via process pool: false
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project No preprocessors configured for src/sayingsBrowser.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project No preprocessors configured for test/sayingsBrowserSpec.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Writing to disk and caching processed file src/sayingsBrowser.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Writing to disk and caching processed file test/sayingsBrowserSpec.js
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Test run started; run priority: 3
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:project Running all tests
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:workers Starting test run, priority: 3
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:phantomRunner Starting sandbox [worker #0, session #pk6nu]
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:phantomRunner Preparing sandbox [worker #0, session #pk6nu]
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:browserRunner Total files to load in sandbox: 2
​​​​​[Info]​​​​​ Mon, 20 Feb 2017 19:41:50 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #pk6nu]: http://localhost:3327/wallaby_sandbox0.html
`
​​​​​

**Comment by dotnetprofessional** [comment]
I just tried with using Electron as you suggested and that does seem to be working.

**Comment by ArtemGovorov** [comment]
> `wallaby:phantomRunner Signal killed phantomjs #0: null, exit code: 3221225477`

Thanks for the log. Looks like PhantomJs 2 is not working on your system. Have you ever got it working for anything else (not wallaby related) on your system?

Chrome/Electron runner is a better choice anyway. However, if you'd like to sue PhantomJs, please try downloading different versions from https://bitbucket.org/ariya/phantomjs/downloads (like v2.0, 1.9.8) and running the downloaded executables directly to see if anything works. If something does work, you may [specify the path to the working PhantomJs exe in your config](https://wallabyjs.com/docs/integration/phantomjs2.html).

**Comment by dotnetprofessional** [comment]
I've never used PhantomJs, so I'm not too concerned. I did raise a new issue #1028 with one of the real projects I'm trialing wallaby on. I'll also be trying to get it working on our teams project this week.

**Comment by ArtemGovorov** [comment]
@dotnetprofessional Thanks for the update. I've just replied to the other issue: https://github.com/wallabyjs/public/issues/1028#issuecomment-281252290
