### ISSUE TITLE
​​​​​Test run failure: file bower_components/angular/angular.js has invalid syntax

### ISSUE THREAD

**Issue by maccurt** [wallabyjs/public#1026]
My test were running just fine. I now get this error:

​​​​​Test run failure: file bower_components/angular/angular.js has invalid syntax

I do not believe, I changed anything. I did not re-install angular with bower (I will double check). I went back to a previous commit and it still did not work.

I know you will ask for more info, I will provide. First I am going to double check I did not change anything, then I will provide more info. I only started this thread in case you know the issue right away

### Code editor or IDE name and version

Visual Studio 2015
Visual Studio 2013

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
We are not aware of the issue, and didn't change anything in the core for a few days (earlier changes should not affect parsing either).

Moreover, I have [created this sample](https://github.com/ArtemGovorov/wallaby-1026) using the latest angular from bower and its working fine.

So, yes, please share a repo where the issue can be reproduced.

**Comment by maccurt** [comment]
I rebooted the computer and it started to work again. so, I wish I had the why, but it is working..

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
