### ISSUE TITLE
Jest 19.0.0

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#1031]
### Issue description or question

Since updating to Jest 19.0.0 (with babel-jest also at 19.0.0), Wallaby.js has been failing to run any of my tests.

The simple test I'm trying to run is:

```javascript
test('Adds 1 + 2 to equal 3', () => {
  expect(1 + 2).toBe(3);
});
```

The error I'm getting in the Wallaby.js Tests output window is:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​TypeError: Cannot read property 'indexOf' of undefined​​
​​    at emitTwo (events.js:106:13)​​
​​    at WebSocket.emit (events.js:191:7)​​
​​    at afterWrite (_stream_writable.js:388:3)​​
​​    at onwrite (_stream_writable.js:379:7)​​
​​    at WritableState.onwrite (_stream_writable.js:90:5)​​
​​    at afterTransform (_stream_transform.js:79:3)​​
​​    at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​    at Zlib.callback (zlib.js:625:5)​​
```

Running `yarn test` (which in turn just runs `jest` in the root directory), gives me the following:

```
PS E:\Documents\Visual Studio Projects\EF Core\src\ElectricFreedom.Web.Scripts> yarn test
yarn test v0.20.3
$ jest
 PASS  scripts\admin\tests\bootstrap.spec.jsx
  √ Adds 1 + 2 to equal 3 (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.711s
Ran all test suites.
Done in 6.87s.
```

So it appears that my test should be working okay and I've set Jest up correctly. It was also working in Wallaby.js in the previous 18.x version.

### Wallaby.js configuration file

```javascript
module.exports = function wallabyConfig(wallaby) {
  return {
    files: [
      'scripts/**/*.js',
      'scripts/**/*.jsx',
      '!scripts/**/tests/*.js',
      '!scripts/**/tests/*.jsx',
    ],

    tests: [
      'scripts/**/tests/*.js',
      'scripts/**/tests/*.jsx',
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.jsx': wallaby.compilers.babel(),
    },

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.9.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Jest 19.0.0 support is added and just released in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). We've actually added it earlier for the pre-release Jest, but looks like there's been some last minute breaking changes.

**Comment by dylanparry** [comment]
Thanks for the quick response. All is now working well again.
