### ISSUE TITLE
Syntax error on arrow function

### ISSUE THREAD

**Issue by R0bson** [wallabyjs/public#1033]
### Issue description or question
Wallaby fails with syntax error '>' or ')', generally caused by arrow functions, flow annotations and object spread operator. All with applied babel stage-2 v6.22.0 (rest-spread operator is currently in stage-3) both by .babelrc and custom settings in wallaby compiler. 
The repo below represents small code portion I reduced while still keeping the error to show up. What is strange repos like https://github.com/wallabyjs/wallaby-babel-es7-sample works without any problem so it shouldn't be issue with OS/IDE but rather something about my code structure. For 5 hours I tried to make Wallaby to work but this strange issue I can't resolve...

### Wallaby.js configuration file
Repo: https://github.com/R0bson/wallaby-test

Repo should reproduce:
```
1 failing tests, 0 passing

src/client/data/utils.test.js example test should return state [1 ms]

	SyntaxError: Unexpected token '>'
	at http://localhost:41155/__modules/613.js?1487693043756:36
```

Caused by src/client/data/store.js:29
`const identity = f => f`

### Code editor or IDE name and version
WebStorm 2016.3.3
Build #WS-163.12024.17, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Node: ~/.WebStorm2016.3/system/wallaby/node_v4.2.2/node

### OS name and version
Linux: Ubuntu 16.04

Other issues this repo can reproduce:
Complains about spread operator in src/utils/toolbox.js:105
`export const addField = curry((field, mapper, list) => map(el => ({ ...el, [field]: mapper(el) }), list))`

Or complains about flow annotations in src/client/data/reducers.js:21 (currently commented out)
`export const injectReducer = (store: Object, name: string, reducer: Function) => {`

**Comment by ArtemGovorov** [comment]
I have sent you [the pull request](https://github.com/R0bson/wallaby-test/pull/1). You need to:
- remove `entry` setting,
- point your [resolve.modules to wallaby cache](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) (where wallaby had all instrumented files).
