### ISSUE TITLE
Typescript- how to use custom tsconfig.json

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1035]
### Issue description or question

Is it possible to use custom tsconfig.json?
In my root directory I have tsconfig.json which I use for my dev build in VS Code. 

I need to override values from this tsconig.json for wallaby build. 
I cannot find a way to do this. Anything I write as a custom parameter to the compiler is ignored and values from tsconfig are used.
Can I somehow point typescript to a different tsconfig file? Thanks!

### Code editor or IDE name and version

WebStorm v11
Visual Studio Code v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Passing the [TS compiler options](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) overrides those from the `tsconfig.json`. Just tried on a few examples, and it's working for me.

For example, if I modify [the config from this sample](https://github.com/wallabyjs/wallaby-typescript-sample/blob/master/wallaby.js) like this:
```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/*Browser.ts'
    ],

    tests: [
      'test/*BrowserSpec.ts'
    ],
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        target: 'es6' // it is set to 'es5' in tsconfig.json
      })
    }
  };
};
```
it stops running tests in the sample and starts complaining about unsupported ES6 constructs. So it correctly overrides the setting in the `tsconfig.json`.

Please share a small sample repo demonstrating the issue.

**Comment by tomitrescak** [comment]
It does not work for me. I am receiving following error:

```
./src/client/modules/user/components/tests/accounts_ui.test.js:2​​
​​import * as React from 'react';​​
​​^^^^^^​​
​​SyntaxError: Unexpected token import​​
​​    at Object.exports.runInThisContext (vm.js:78:16)​​
​​    at Module._compile (module.js:543:28)​​
​​    at Object.Module._extensions..js (module.js:580:10)​​
​​    at Module.load (module.js:488:32)​​
​​    at tryModuleLoad (module.js:447:12)​​
​​    at Function.Module._load (module.js:439:3)​​
​​    at Module.require (module.js:498:17)​​
​​    at require (internal/module.js:20:19)​​
​​    at Array.forEach (native)​​
​​    at emitTwo (events.js:106:13)​​
​​    at WebSocket.emit (events.js:191:7)​​
​​    at afterWrite (_stream_writable.js:386:3)​​
​​    at onwrite (_stream_writable.js:377:7)​​
​​    at afterTransform (_stream_transform.js:79:3)​​
​​    at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​    at Zlib.callback (zlib.js:625:5)​​
```

Here is a wallaby config:

```
const transform = require("jsx-controls-loader").loader;
module.exports = function (wallaby) {
  // var load = require;

  return {
    debug: true,
    files: [
      `./jest.startup.js`,
      './src/client/modules/_stories/luis/snapshot_handler.js',
      "src/client/**/*.ts*",
      "src/shared/**/*.ts*",
      'src/**/*.snap',
      'package.json',
      '!src/**/*.test.ts*',
    ],
    tests: [
      "!src/**/*.snap",
      "src/**/*.test.ts*"

    ],
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
      '**/*.tsx': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
    preprocessors: {
      "**/*.tsx": file => transform(file.content)
    },
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "mocha",
    setup: function (wallaby) {
      require('./jest.startup');
    
      // global.workerId = wallaby.workerId;
      // global.isWallaby = true;
      // // wallaby.testFramework.grep('@sut');

      // var Module = require('module');
      // var originalRequire = Module.prototype.require;

      // // spy on requiring canvas
      // // globally stub modules that we wish not to load
      // Module.prototype.require = function(){
      //   //do your thing here
      //   if (arguments[0] === 'canvas' || arguments[0] === 'kinetic') {
      //     return {};
      //   }
      //   return originalRequire.apply(this, arguments);
      //};

      // Extend expect
      const expect = require('expect');
      global.expect = expect;
      expect.extend({
        toMatchSnapshot() {
          return true;
        }
      });

      // Taken from https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md
      var jsdom = require('jsdom').jsdom;

      var exposedProperties = ['window', 'navigator', 'document'];

      global.document = jsdom('');
      global.window = document.defaultView;
      Object.keys(document.defaultView).forEach((property) => {
        if (typeof global[property] === 'undefined') {
          exposedProperties.push(property);
          global[property] = document.defaultView[property];
        }
      });

      global.navigator = {
        userAgent: 'node.js'
      };
    },
    teardown: function (wallaby) {
      console.log('Tearing down database ...');
      const connector = require('apollo-connector-mongodb');
      connector.disposeDb(true);
      connector.stopServer();
    }
  };
};
```

And here is tsconfig.json

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowSyntheticDefaultImports": true,
        "lib": [
            "dom",
            "es2015",
            "es2016"
        ],
        "noEmitHelpers": false,
        "emitDecoratorMetadata": true,
        "jsx": "react",
        "target": "es2016",
        "module": "es6",
        "moduleResolution": "node",
        "removeComments": true,
        "preserveConstEnums": true,
        "sourceMap": true,
        "strictNullChecks": false,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "skipLibCheck": true,
        "skipDefaultLibCheck": true,
        "experimentalDecorators": true,
        "outDir": "./build",
        "types": [
            "chai",
            "react",
            "jest"
        ],
        "typeRoots": [
            "src/typings/overrides",
            "node_modules/@types"
        ],
        "pretty": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by ArtemGovorov** [comment]
Looks like you're specifying 2 separate TypeScript compilers, and it's not supported. Could you try this:

```
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
```

**Comment by tomitrescak** [comment]
Weird bit happens, that even when I change modules to "commonjs" in my tsconfig.json and maintain

```
compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
      '**/*.tsx': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
```

I still receive `import` errors.

Only when I change config to following (and having module: 'commonjs' in tsconfig.json)

```
compilers: {
      '**/*.ts': wallaby.compilers.typeScript(),
      '**/*.tsx': wallaby.compilers.typeScript()
    },
```

It works.

Please note that I have several tsconfig.json in my folder (e.g. tsconfig.fuse.json, tsconfig.server.json ... and tsconfig.json)

**Comment by ArtemGovorov** [comment]
Try the solution with one specified TS compiler above.

**Comment by tomitrescak** [comment]
```
'**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
```

Did not help

I have to do:

```
'**/*.ts?(x)': wallaby.compilers.typeScript()
```

**Comment by ArtemGovorov** [comment]
I don't understand what's going on, but it's definitely related to your setup/environment, because I can't reproduce it. 

```
'**/*.ts?(x)': wallaby.compilers.typeScript()
```
This, even if helps, is supposed to not use your `tsconfig.json` at all, not sure if it's what you want.

Let me quickly create a repo with your setup to see if I can get anywhere.

**Comment by ArtemGovorov** [comment]
Here's the repo: https://github.com/ArtemGovorov/wallaby-1035, it contains your tsconfig, another tsconfig, your wallaby config with 
```
'**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
```
and everything is working.

**Comment by tomitrescak** [comment]
Artem, when I clone your repo and run wallaby within I receive 

```
./src/a.test.js:2​​
​​import * as React from 'react';​​
​​^^^^^^​​
​​SyntaxError: Unexpected token import​​
​​    at Object.exports.runInThisContext (vm.js:78:16)​​
​​    at Module._compile (module.js:543:28)​​
​​    at Object.Module._extensions..js (module.js:580:10)​​
​​    at Module.load (module.js:488:32)​​
​​    at tryModuleLoad (module.js:447:12)​​
​​    at Function.Module._load (module.js:439:3)​​
​​    at Module.require (module.js:498:17)​​
​​    at require (internal/module.js:20:19)​​
​​    at Array.forEach (native)​​
​​    at emitTwo (events.js:106:13)​​
​​    at WebSocket.emit (events.js:191:7)​​
​​    at afterWrite (_stream_writable.js:386:3)​​
​​    at onwrite (_stream_writable.js:377:7)​​
​​    at afterTransform (_stream_transform.js:79:3)​​
​​    at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​    at Zlib.callback (zlib.js:625:5)​​
```

**Comment by ArtemGovorov** [comment]
Interesting, I can't reproduce it, neither in VS Code, nor in WebStorm. The `tsc` version shouldn't matter, because the sample repo has TypeScript dependency that wallaby is using.

Does it still throw the error is you delete the [tsconfig.server.json file](https://github.com/ArtemGovorov/wallaby-1035/blob/master/tsconfig.server.json) from the project?

**Comment by ArtemGovorov** [comment]
Also, please try renaming the `./src/a.test.tsx` file to `.ts` (and remove the JSX from it), to see if it changes anything.

**Comment by ArtemGovorov** [comment]
Also, just in case, what is your node.js version?

**Comment by ArtemGovorov** [comment]
I've just published [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version with a new setting that should ultimately solve the issue for you (even though I still don't know the reason). You may now pass `tsconfig: false` to the options to suppress reading any tsconfig files, so the compiler will only use the provided options.

Please try this in the sample repo:
```
'**/*.ts?(x)': wallaby.compilers.typeScript({ tsconfig: false, module: 'commonjs' })
```

I have also added some logging, so if you have a chance, please also paste the wallaby console output (when running without the `tsconfig` option).

**Comment by tomitrescak** [comment]
Artem.
My node version is 7.4.0
Changing .tsx to .ts did not help.

Now:

Setting `'**/*.ts*': wallaby.compilers.typeScript({ tsconfig: false, jsx: 'react', module: 'commonjs' })`

Resolved the module problems, but it is still emitting jsx into final file

```
./src/a.test.js:6​​
​​    $_$w(2, 2), $_$tracer.log(<div>Hello</div>, '<div>Hello</div>', 2, 2);​​
​​                              ^​​
​​SyntaxError: Unexpected token <​​
​​    at Object.exports.runInThisContext (vm.js:78:16)​​
```

How can I view logs that you mentioned?

**Comment by tomitrescak** [comment]
This is what I have found in my logs:

```
​​​​​[Info]​​​​​ Wed, 22 Feb 2017 23:17:34 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): undefined
​​​​​[Info]​​​​​ Wed, 22 Feb 2017 23:17:34 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): undefined
```

**Comment by tomitrescak** [comment]
Artem, I've found out that the last typescript this works with is 2.1.1 ... anything beyond will smash the compiler. So, **it does not work with latest typescript 2.2.*.**

**Comment by tomitrescak** [comment]
Yes, I've played with it and with typescript 2.1.6 everything works as you have described. 2.2.* is a fail.

**Comment by ArtemGovorov** [comment]
Thanks for the update, I will investigate. Just to make it clear, [this sample](https://github.com/ArtemGovorov/wallaby-1035) that we've been trying yesterday, works if you just do `npm i`? It has TypeScript 2.1.6 as a dependency.

**Comment by tomitrescak** [comment]
I had globally installed different typescript that for some reason was interfereing with the locally installed typescript. Global was 2.2.x local 2.1.6. It still would not work. I had to remove the global installation.

**Comment by ArtemGovorov** [comment]
I was able to reproduce the issue with 2.2.x, the issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Thanks for your help!

**Comment by Artur-A** [comment]
For those who faces the same exception double check `tsconfig.json`:
```
{
    "compilerOptions": 
    {
        "noEmit": true, // should be false!
```

The setting `"noEmit": true` leads to the error, should be `"noEmit": false`,
