### ISSUE TITLE
Using Wallaby with Webpack built code and plain es5 in the same project.

### ISSUE THREAD

**Issue by grug** [wallabyjs/public#1037]
### Issue description or question

I have an Angular project where it is split into two sections:

 1. Our old code, which is 1.x which is built using Grunt. Tests for this live in `tests/**/*.spec.js`. The code lives in `src/**/*.js`.
 2. Our new code, which is Typescript and built/bundled using Webpack. Tests for this live in `ts/**/*.spec.ts`. The code lives in `ts/**/*.ts`.

I can get Wallaby to run perfectly fine for **just** the Typescript part of the project using the following config:

    var wallabyWebpack = require('wallaby-webpack');
    
    var webpackPostprocessor = wallabyWebpack({
      module: {
        loaders: [{
          test: /\.html$/,
          loader: 'raw'
        }]
      }
    });
    
    module.exports = function(wallaby) {
      return {
        files: [
          { pattern: 'lib/angular/angular.js', instrument: false },
          { pattern: 'lib/angular-mocks/angular-mocks.js', instrument: false },
          { pattern: 'ts/**/*.html', load: false },
          { pattern: 'ts/**/*.ts', load: false },
          { pattern: 'ts/**/*.spec.ts', ignore: true }
        ],
    
        tests: [
          { pattern: 'ts/**/*.spec.ts', load: false }
        ],
    
        testFramework: 'jasmine',
    
        postprocessor: webpackPostprocessor,
    
        setup: function () {
          window.__moduleBundler.loadTests();
        },
    
        debug: true
      };
    };

This is great. However, I also want the old Angular tests to also run. So I've added `'src/**/*.js'` to the `files` array and added `'tests/**/*.spec.js'` to the `tests` array.

It should be noted that if I just run the unit tests by themselves without Wallaby that they execute and pass just fine.

For some reason, when I run Wallaby with my updated config, that I get the following error any time I try to inject anything from my old code (`src/**/*.js`) into my tests:

    TypeError: undefined is not a constructor (evaluating 'e.fn.call(c.userContext)')
    Error: [$injector:unpr] Unknown provider: FOO_TYPESProvider <- FOO_TYPES
    http://errors.angularjs.org/1.3.15/$injector/unpr?p0=FOO_TYPESProvider%20%3C-%20FOO_TYPES

For reference, here is a test that would cause the above error that would execute just fine via Karma:

      describe("Test", function () {
        var _FOO_TYPES;
    
        beforeEach(angular.module('test'));
    
    beforeEach(inject(function (FOO_TYPES) {
          _FOO_TYPES = FOO_TYPES;
        }));
       
        it('should have FOO_TYPES constants', function () {
          expect(_FOO_TYPES.FOO).toBe('foo');
        });
    });

The `FOO_TYPES` constant is defined in `src/foo/foo.js` as

    angular.module('test')
        .constant('FOO_TYPES', {
          FOO: 'foo'
        });

Is it possible to have both my Webpack tests and my ES5 tests running with Wallaby at once, or can I only have one or the other?

Thanks!

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I haven't seen anyone doing it, but I think it should be possible.

Just created a test branch for [the angular sample](https://github.com/wallabyjs/ngCliWebpackSample/tree/es5Angular1Tests) with a few existing TypeScript + Webpack tests, [added an "old" module](https://github.com/wallabyjs/ngCliWebpackSample/blob/es5Angular1Tests/src/oldModule.js), a [test for it](https://github.com/wallabyjs/ngCliWebpackSample/blob/es5Angular1Tests/tests/a.spec.js), and specified the files in the wallaby config (with `load: true`):
- https://github.com/wallabyjs/ngCliWebpackSample/blob/es5Angular1Tests/wallaby.js#L31
 - https://github.com/wallabyjs/ngCliWebpackSample/blob/es5Angular1Tests/wallaby.js#L44

(note that I slightly changed the module definition and `beforeEach(angular.module('test'));` -> `beforeEach(module('test'));`).

Everything seems to be working ok (both new and old tests run). Try the sample and if the similar setup is not working for you, please create a sample repo demonstrating the issue.

**Comment by grug** [comment]
Thanks for getting back to me so quick.

If I switch to using `beforeEach(module('test'));` and replicate the config like you have it, I get the following error:

`Object is not a constructor (evaluating 'module('test')')`

Any ideas on what needs to be done here? Do I need to enable anything like ES6 for this to work?

Thanks!

**Comment by ArtemGovorov** [comment]
I'm not sure how karma works with `beforeEach(angular.module('test'));` in your case, because [with angular-mocks it either needs to be](https://docs.angularjs.org/api/ngMock/function/angular.mock.inject):

```
beforeEach(module('test'));
```
or
```
beforeEach(angular.mock.module('test'));
```
Try the second one.

> Do I need to enable anything like ES6 for this to work?

You shouldn't need to. Does [my sample](https://github.com/wallabyjs/ngCliWebpackSample/tree/es5Angular1Tests) work for you? Is yes, then there's something specific to your project that I'm missing, in which case please create a sample repo demonstrating the issue.

**Comment by grug** [comment]
I'll try get a sample repo going for you.

I think there are a couple of things at play here that I haven't fully been able to articulate.

Depending on what I change that `beforeEach` line to gives me a different error:

- beforeEach(module('test')); -> "`Object is not a constructor(evaluating 'module('test')')`"
- beforeEach(angular.module('test')); -> "`TypeError: undefined is not a constructor (evaluating 'e.fn.call(c.userContext)')
Error: [$injector:unpr] Unknown provider: FOO_TYPESProvider <- FOO_TYPES
http://errors.angularjs.org/1.3.15/$injector/unpr?p0=FOO_TYPESProvider%20%3C-%20FOO_TYPES`"
- beforeEach(angular.mock.module('test')); -> "`Error: [$injector:modulerr] Failed to instantiate module test due to:
[$injector:modulerr] Failed to instantiate module other.module due to:...`"

The third one is probably because if we mock our the `test` module, then other things that depend on the dependencies introduced by `other.module` won't be included which will obviously be a problem. Not only this, the constants provided to that module will also not be included - which is what we are testing.

The correct answer to this has to be using one of the first two things I've listed, but need to find out why it's not currently working.

I'll get together a test repo for you to take a look at when you get a chance.

Thanks!

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
