### ISSUE TITLE
Async setup promise not resolving

### ISSUE THREAD

**Issue by BraunreutherA** [wallabyjs/public#1038]
Hi, I have a bootstrap script which connects to a mongo db and opens an express server. It looks like this: 

```javascript
import * as server from '../src/server';

export const start = (cb) => {
  server.start()
    .then((api) => {
      global.api = api.app;
      cb();
    });
};
```

I also tested it without the callback and returned the promise but no effect.

This is the wallaby config:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.spec.js',
      'test/helpers.js',
      'test/bootstrap.js',
    ],

    tests: [
      'src/**/*.spec.js',
    ],

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'mocha',
    debug: true,
    workers: {
      recycle: true,
      initial: 1,
      regualr: 1
    },

    setup: function(wallaby) {
      wallaby.delayStart();
      require('./test/helpers');
      const bootstrap = require('./test/bootstrap');

      bootstrap.start(() => {
        wallaby.start();
      });
    },
  };
};
```

wallaby runs forever and won't start. I'm using it the same way in mocha from cmd and it works.

```javascript
import * as bootstrap from './bootstrap';

before((done) => {
  bootstrap.start(done);
});
```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It seems like there's only one possible explanation, this code never runs:
```javascript
global.api = api.app;
cb();
```
which means that `server.start()` promise is failing for some reason. Try handling the error to get more details:

```javascript
export const start = (cb) => {
  server.start()
    .then((api) => {
      global.api = api.app;
      cb();
    })
    .catch(e => {
      console.error(e);
    });
};
```

**Comment by BraunreutherA** [comment]
Thanks for the quick reply. I also checked this but there are no console statements in my wallaby panel. That's another thing I'm wondering. 

But i tried it like this aswell: 
```javascript
export const start = (cb) => {
  server.start()
    .then((api) => {
      global.api = api.app;
      cb();
    })
    .catch(e => {
      console.error(e);
      cb();
    });
};
```

and wallaby won't startup

**Comment by ArtemGovorov** [comment]
Does this make it start?:

```javascript
export const start = (cb) => {
  new Promise((y, n) => y({}))
    .then((api) => {
      global.api = api.app;
      cb();
    })
    .catch(e => {
      console.error(e);
      cb();
    });
};
```

**Comment by BraunreutherA** [comment]
Yes this starts it up, but would be the same as calling cb directly - I'm wondering why wether the then nor the catch block executes. And also with plain mocha everything works out.

**Comment by ArtemGovorov** [comment]
Clearly `server.start()` hangs for some reason, and apparently doesn't crash/error and neither is starting. I can not guess why, it depends on what is it exactly and what is it doing. Your plain mocha setup may be a bit different, or it may be something different in wallaby environment that makes the server not to start - it's hard to tell without having a sample.

Unless you can create and share a sample GitHub repo where I could reproduce it, the best and the only  way I can think of is perhaps to insert some console logging statements along the way to find out why it's hanging.

> there are no console statements in my wallaby panel.

This kind of logging is done to the [Atom Developer Tools Console](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting). Try adding some logging to your `setup` function, and you should be able to see the output there.

**Comment by ArtemGovorov** [comment]
> And also with plain mocha everything works out.

I'd also make sure the same ENV vars are set for wallaby, if you're setting anything for mocha (like maybe ENV vars for server/DB connection). Also double check that all files that are used in your tests (config files to connect to DB for exampe, etc. are listed in your `files` list).

**Comment by BraunreutherA** [comment]
Ah now I can see the logs thanks!

Now it's getting really strange..

```javascript
import * as server from '../src/server';

export const start = (cb) => {
  server.start()
    .then((api) => {
      console.log(api); // this executes and produces a correct log;
      // global.api = api.app; // can even be deleted
      cb(); // seams to not execute
    })
    .catch((error) => {
      console.log(error);
    });
};
```

**Comment by ArtemGovorov** [comment]
It's weird... What does this print?

```javascript
export const start = (cb) => {
  server.start()
    .then((api) => {
      console.log(cb.toString()); // <---

      cb(); // seams to not execute
    })
    .catch((error) => {
      console.log(error);
    });
};
```

**Comment by BraunreutherA** [comment]
Wallaby Console: console.log: function (){r._delayStart=!1,r.start()}

**Comment by ArtemGovorov** [comment]
Hmm, I'm a bit lost, how is it possible if you are doing
```
bootstrap.start(() => {
        wallaby.start();
});
```
so it's supposed to print the arrow function body.

**Comment by BraunreutherA** [comment]
So I came there, I inserted an console log in the setup function and now it gets printed out aswell but wallaby doesn't load up more.

```javascript
bootstrap.start(() => {
        console.log('bla');  // this logs 
        wallaby.start();
      });
```

**Comment by ArtemGovorov** [comment]
I also don't understand why this:
```javascript
export const start = (cb) => {
  new Promise((y, n) => y({}))
    .then((api) => {
      global.api = api.app;
      cb();
    })
    .catch(e => {
      console.error(e);
      cb();
    });
};
```
works. If the server doesn't hang, then it shouldn't matter that the callback is invoked for a dummy promise.

**Comment by BraunreutherA** [comment]
So maybe a test is hanging in between? but then there should be an error thrown right?

**Comment by BraunreutherA** [comment]
Also when I insert a dummy promise all tests pass instead of one which requires the global api. And an error gets thrown also wallaby gets loaded completly

**Comment by ArtemGovorov** [comment]
> So maybe a test is hanging in between?

If it was the case, then this:

```javascript
export const start = (cb) => {
  new Promise((y, n) => y({}))
    .then((api) => {
      global.api = api.app;
      cb();
    })
    .catch(e => {
      console.error(e);
      cb();
    });
};
```
wouldn't work, but it does.

What if you do this:
```javascript
export const start = (cb) => {
  server.start()
    .then((api) => {
      global.api = api.app;
      setTimeout(() => cb(), 100);
    })
    .catch(e => {
      console.error(e);
      cb();
    });
};
```

**Comment by BraunreutherA** [comment]
I found it! 
```javascript
workers: {
      recycle: true,
      initial: 1,
      regualr: 1 // typo
    },
```
I'm so sorry that I didn't see this error before :/

**Comment by ArtemGovorov** [comment]
Does fixing the type help?

**Comment by BraunreutherA** [comment]
Yes it helped
I also tried to do it like this: 

```javascript
workers: {
      recycle: true,
    },
```

but then wallaby doesn't load. Don't know why - shouldn't it simply throw errors if tests with multiple workers don't work?

**Comment by BraunreutherA** [comment]
But Anyhow it works now :) 
Thanks a lot Artem - you're doing the best support I ever received for ages!

**Comment by ArtemGovorov** [comment]
> Don't know why - shouldn't it simply throw errors if tests with multiple workers don't work?

It should, and if you try with a dummy promise - it will. It's something in the server affecting it, but I have no idea what. 

As long as you are happy with the solution, I'm going to close it. However if you could share the sample when it's hanging (I understand it may be not possible or very hard to share), I'd love to have a look and get to the bottom of the problem.

**Comment by BraunreutherA** [comment]
I created a private fork as there's not that much work done already. But as it's internal code I can't share public. I invited you as collaborator, so maybe it helps :)

**Comment by ArtemGovorov** [comment]
Thanks, I have had a look and from what I was able to discover, mongoose hangs while connecting to your DB when doing it from 2 or more workers at the same time. I'm not much familiar with the library, but perhaps there's a timeout setting available or an even to subscribe to/handle for such cases so that wallaby is able to act gracefully.
