### ISSUE TITLE
Thrown bug is displayed in the wrong line.

### ISSUE THREAD

**Issue by PerFuchs** [wallabyjs/public#104]
I found following bug: 

![bug](https://cloud.githubusercontent.com/assets/10382528/7587558/77213a00-f8b7-11e4-8976-37752ef3079a.PNG)

The used javascript is beneath:
```javascript
it('will show the thrown bug in the wrong line', function() {
    var spy = jasmine.createSpy('spy').and.throwError('Bug');

    expect(spy).toThrowError('Bug');
    //spy.and.stub(); // Uncomment this line and test will pass.

    expect(spy()).toEqual(undefined); // 'Error: Bug' should be displayed here not up there.
  });
```

Congratulations for writting and supporting such a great tool. Very happy to use it in our project.

Best regards,
Per Fuchs

**Comment by ArtemGovorov** [comment]
Thank you! Glad to hear you're enjoying the tool.

I have fixed the issue, wallaby.js will automatically update the core, so you should be able to see it fixed next time you restart wallaby.
