### ISSUE TITLE
Error: processor pool is not started

### ISSUE THREAD

**Issue by tinovyatkin** [wallabyjs/public#1040]
![screen shot 2017-02-22 at 15 41 21 pm](https://cloud.githubusercontent.com/assets/5350898/23229139/8b147dfa-f915-11e6-9ae8-8e0417e2e78b.png)

**Comment by tinovyatkin** [comment]
Stopping and restarting Wallaby after that solves the problem

**Comment by ArtemGovorov** [comment]
Ok, must be some transient issue, not sure of the reason. Please report if it happens frequently.
