### ISSUE TITLE
before() block is run even though all tests are excluded with grep

### ISSUE THREAD

**Issue by larsthorup** [wallabyjs/public#1041]
I use grep with mocha to exclude slow tests. However any before() block inside those excluded tests are still being run by Wallaby. When run directly with mocha these before()-blocks are not being run. Since the before() block is causing most of the slowness, this prevents me from using Wallaby with these tests.

Sample repo here: https://github.com/larsthorup/wallaby-mocha-grep-before

Output from mocha:
```
>mocha --grep @slow --invert

  @fast
    √ should be included

  1 passing (12ms)
```

Output from Wallaby (notice the green dot in line 11).
![image](https://cloud.githubusercontent.com/assets/1202959/23231525/7545a98a-f948-11e6-8eba-5baa2d9f878a.png)

WebStorm 2016.3.3
Windows 10
Wallaby core v1.0.385

Output from Wallaby console: https://gist.github.com/anonymous/a142b454ffaa4c1993917b1b888e0491

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo!
The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by larsthorup** [comment]
Awesome response time! And it works :) Thanks a bunch :)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
