### ISSUE TITLE
Getting "Unexpected token ILLEGAL​​" when more than five files in a test directory.

### ISSUE THREAD

**Issue by Jorriss** [wallabyjs/public#1042]
### Issue description or question
I'm receiving the error "Unexpected token ILLEGAL" error when more than file files are in a test directory. I was getting the error when running all the test directories in a project and was able to track down the error to the number of files. Five or less and the error doesn't appear. Six or more and the error is displayed. The tests under mocha run green.

​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.385
​​​​​[Info]​​​​​ Wallaby App available at: http://wallabyjs.com/app/#/files
​​[Error] Runtime error: SyntaxError: Unexpected token ILLEGAL​​
​​[Error]     at exports.runInThisContext (vm.js:53:16)​​
​​[Error]     at Module._compile (module.js:373:25)​​
​​[Error]     at Object.Module._extensions..js (module.js:416:10)​​
​​[Error]     at Module.load (module.js:343:32)​​
​​[Error]     at Function.Module._load (module.js:300:12)​​
​​[Error]     at Module.require (module.js:353:17)​​
​​[Error]     at require (internal/module.js:12:17)​​
​​[Error]     at Array.forEach (native)​​
​​[Error]     at emitTwo (events.js:87:13)​​
​​[Error]     at WebSocket.emit (events.js:172:7)​​
​​[Error]     at afterWrite (_stream_writable.js:354:3)​​
​​[Error]     at onwrite (_stream_writable.js:345:7)​​
​​[Error]     at WritableState.onwrite (_stream_writable.js:89:5)​​
​​[Error]     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]     at Zlib.callback (zlib.js:615:5)​​
​​​​​[Info]​​​​​ Finished executing 46 affected test(s)

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            '**/lib/*.js',
            'common/lib/*.js',
            '**/functions/*.js'
        ],

        tests: [
            'common/test/CloudCompute-test.js',
            'common/test/CloudQueue-test.js',
            'common/test/CloudStorage-test.js',
            'common/test/Dynamo-test.js',
            'common/test/FileLog-test.js',
            // 'common/test/Postgres-test.js',
            // 'common/test/ProcessHelper-test.js',
            'common/test/SqsPoller-test.js',
            '*/test/*.zip'
        ],

        setup: function (wallaby) {
            global.expect = require('chai').expect;
            var mocha = wallaby.testFramework;
            mocha.ui('tdd');
        },

        env: {
            type: 'node'
            // More options are described here
            // http://wallabyjs.com/docs/integration/node.html
        }
    };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.9.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
I think the root of the issue is not directly related to the number of test files. Wallaby runs your tests in parallel using your machine capacity, so it is probably related to the [number of test workers](https://wallabyjs.com/docs/config/workers.html) wallaby spins up to run test files in parallel.

Could you please try the following:
- get rid of the file patterns starting with `*` (replace them with patterns with some root, like `src/**/lib/*.js` or similar).
- replace this pattern: `'*/test/*.zip'` with `{pattern: '*/test/*.zip', instrument: false, binary: true}`

**Comment by Jorriss** [comment]
That did it. I moved the zip pattern to the files section where it actually belongs.
Thanks for the info and the fix.
