### ISSUE TITLE
Basic enzyme's shallow fails with Invariant Violation: ReactShallowRenderer

### ISSUE THREAD

**Issue by R0bson** [wallabyjs/public#1045]
### Issue description or question
Minimal enzyme setup works with mocha-webpack (prepared in `npm test` command), with Wallaby returns error in src/client/view/App.test.js:10:
`Invariant Violation: ReactShallowRenderer render(): Invalid component element.`

Returns error:
```
const wrapper = shallow(<App/>)
const wrapper = shallow(React.createElement(App))
```
Works:
`const wrapper = shallow(React.createElement("div", null, "Test"))`

### Wallaby.js configuration file
Repo: https://github.com/R0bson/wallaby-enzyme-ReactShallowRenderer

### Code editor or IDE name and version
WebStorm 2016.3.3
Build #WS-163.12024.17, built on January 31, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Node: ~/.WebStorm2016.3/system/wallaby/node_v4.2.2/node

### OS name and version
Ubuntu 16.04

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I have sent you [the pull request](https://github.com/R0bson/wallaby-enzyme-ReactShallowRenderer/pull/1), it looks like specifying the `react` external breaks it.

**Comment by R0bson** [comment]
Thanks again! Finally wallaby works with my project :1st_place_medal: 

Some tips:
1. Setting `process.env.NODE_ENV= 'test'` at the top (like mentioned [here](https://wallabyjs.com/docs/integration/es-next.html) of wallaby.js doesn't work if using webpack. `process.env` is empty during and solution for this is to use webpack's DefinePlugin
```
...
var webpackPostprocessor = wallabyWebpack({
      plugins: [
        new webpack.DefinePlugin({
          'process.env': {
            NODE_ENV: JSON.stringify('test'),
          },
        }),
      ],
   ....
```

It would be worth to mention it in [webpack's section](https://wallabyjs.com/docs/integration/webpack.html).



And some tips for people searching web for other errors in future :)

2. If you are using enzyme with webpack then set up externals (available in repo above): 
```
'react/addons': true,
'jsdom': 'window',
'cheerio': 'window',
'react/lib/ExecutionEnvironment': true,
'react/lib/ReactContext': 'window',
```

3. When using enzyme's mount (which requires setting up jsdom global in mocha environment) then wallaby fails with `Can't evaluate 'jsdom('')'. I don't know why, but simply remove it. By default wallaby works in browser environment and doesn't require setting up the jsdom, mount works without it.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update and for the tips!
