### ISSUE TITLE
No trial available for VS Code plugin

### ISSUE THREAD

**Issue by tony19** [wallabyjs/public#1048]
### Issue description or question
I just installed the the Wallaby plugin for VS Code, but I don't see an option for "Trial". Attempting to run it causes this banner:
![screen shot 2017-02-24 at 7 48 28 pm](https://cloud.githubusercontent.com/assets/26580/23326972/43d323d6-faca-11e6-8824-86e24f189e19.png)

How do I install a trial of the VS Code plugin?

### Wallaby.js configuration file
N/A

### Code editor or IDE name and version
Visual Studio Code v1.9.1

### OS name and version
macOS Sierra 10.12

**Comment by ArtemGovorov** [comment]
As the banner message says, the tool is starting in the trial mode, just close it and you're good to go.

**Comment by tony19** [comment]
Ah, right! Oops. I guess I'm not sure how to use this in VS Code. I was expecting the colored squares in the gutter as shown in the README for https://github.com/wallabyjs/wallaby-typescript-sample/. Since I saw the banner instead of the squares, I assumed it was a license/trial issue. How do I get the squares to appear?

**Comment by ArtemGovorov** [comment]
The sample repo has 2 config files and 2 sets for files, to demonstrate testing for browser and for node.

On your screenshot, you have the `greeterNodeSpec.ts` file opened, however (unless you've specifically selected `wallaby-node.js` config file as [described in the tutorial](https://wallabyjs.com/docs/intro/get-started-vscode.html#first-steps)) wallaby will run the `wallaby.js` config file, which targets [browser spec file](https://github.com/wallabyjs/wallaby-typescript-sample/blob/master/test/sayingsBrowserSpec.ts).

Try opening the `test/sayingsBrowserSpec.ts` file to see if the squares are there. If not, try [opening the Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) to see if there're any errors displayed there.

**Comment by tony19** [comment]
Ok, got it now. Thanks!
