### ISSUE TITLE
Change file after typescript compilation

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1049]
Hi, is there any way I can modify file after typescript compilation?
For my stubbing functionality I need to rewrite all `requires` to something different.

**Comment by ArtemGovorov** [comment]
You may add a preprocessor for `.js` files (because wallaby renames `.ts` files to `.js`) and change it. Here's an example how to [add a babel preprocessor](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel).
