### ISSUE TITLE
utf-8-validate compatibility issue breaks wallaby

### ISSUE THREAD

**Issue by marcello3d** [wallabyjs/public#1051]
### Issue description or question

Getting this stack trace when running with debug mode (no tests run):

```
Wed, 01 Mar 2017 00:47:49 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'isValidUTF8' of undefined, stack: TypeError: Cannot read property 'isValidUTF8' of undefined
    at /Users/marcello/Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/ws/lib/Receiver.js:532:28
    at /Users/marcello/Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/ws/lib/Receiver.js:368:7
    at /Users/marcello/Library/Caches/WebStorm2016.3/wallaby/wallaby/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:388:3)
    at onwrite (_stream_writable.js:379:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:639:5)
```

Did a little digging and it appears that ws/lib/Receiver.js is trying to `require('utf-8-validate')` which isn't installed in `WebStorm2016.3/wallaby/wallaby/node_modules` for some reason but _is_ installed in our project (we're using the 3.x branch, which is incompatible with the 1.2.x version ws wants). 

If I open up `WebStorm2016.3/wallaby/wallaby` and manually `npm install utf-8-validate@1.2`, it seems to fix the problem, but this is hardly ideal.

### Code editor or IDE name and version
WebStorm v11

### OS name and version
macOs

**Comment by ArtemGovorov** [comment]
Thanks for the report and for the investigation. The issue is is fixed, and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
