### ISSUE TITLE
Typescript compiler option orderFilesByReferenceComments stopped working as expected

### ISSUE THREAD

**Issue by fdeslandes-wk** [wallabyjs/public#1052]
### Issue description or question
Lately, the orderFilesByReferenceComments stopped working in our project, so we have errors because files are loaded in the wrong order even if they have reference comments.

Our temporary fix was changing the file names so they are loaded in the right order.

### Wallaby.js configuration file

[Small project to reproduce the bug, with wallaby.js configuration included](https://github.com/fdeslandes-wk/wallaby-bug-order-files-by-reference-comments)

### Code editor or IDE name and version

Visual Studio Code v1.9

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report and for the repo, the regression is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and teh fix is published.
