### ISSUE TITLE
[Error]: Failed to start wallaby UI service: undefined

### ISSUE THREAD

**Issue by ts3li0t** [wallabyjs/public#1054]
### Issue description or question
When starting Wallaby.js from Sublime Package Control, I get the follow error message:

[Info]: wallaby.js started
[Error]: Failed to start wallaby UI service: undefined
[Info]: Wallaby App available at: http://wallabyjs.com/app/#/files

Debug mode does not reveal any further information. When navigating to http://wallabyjs.com/app/#/files, both Firefox and Chrome show the following, respectively:

09:21:48.221 Firefox can't establish a connection to the server at ws://127.0.0.1:51235/.1 main.a591c000222afc2c7bc4.js:2:9976

WebSocket connection to 'ws://127.0.0.1:51235/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
value @ main.a591c00â¦.js:2
main.a591c00â¦.js:2

### Wallaby.js configuration file
/* eslint-disable no-var, no-shadow, dot-notation */

module.exports = function(wallaby) {
  return {
    files: [

      {pattern: 'jspm_packages/system.js', instrument: false},
      {pattern: 'config.js', instrument: false},

      {pattern: 'src/**/*.js', load: false},
      {pattern: 'test/unit/setup.js', load: false}

    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: [ 'es2015-loose', 'stage-1'],
        plugins: [
          'syntax-flow',
          'transform-decorators-legacy',
          'transform-flow-strip-types'
        ]
      })
    },

    middleware: (app, express) => {
      app.use('/jspm_packages', express.static(require('path').join(__dirname, 'jspm_packages')));
    },

    bootstrap: function(wallaby) {
      var promises = [];
      var i = 0;
      var len = wallaby.tests.length;

      wallaby.delayStart();

      System.config({
        paths: {
          '*': '*.js'
        }
      });
      for (; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }

      System.import('test/unit/setup')
        .then(function () {
          return Promise.all(promises);
        })
        .then(function() {
          wallaby.start();
        }).catch(function (e) { setTimeout(function (){ throw e; }, 0); });
    },

    debug: false
  };
};

```javascript
Aurelia skeleton-esnext @ https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext

### Code editor or IDE name and version
Sublime Text v3 - Stable Channel Build 3103

### OS name and version
CentOS Linux release 7.1.1503 (Core)

**Comment by ArtemGovorov** [comment]
I have improved the error reporting a bit, please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to see if the error message had changed.

Please also try doing this:
- create a test.js file with the following content:
```javascript
const checker = (host, port) => {
  const tester = require('net').createServer()
    .once('error', e => console.error(e))
    .once('listening', () => tester.once('close', () => console.log('ok: ' + host + ':' + port)).close())
    .listen(port, host);
};

checker('0.0.0.0', 51235);
checker('127.0.0.1', 51235);
checker('::1', 51235);
```
- stop all wallaby instances, and just in case run `killall node`,
- run `node test.js`, and paste the result here.

**Comment by ts3li0t** [comment]
I'm now running Wallaby Core v1.0.392. Error reporting seems to be updated:

[Error]: Failed to start wallaby app service: Can not find a free port

[ts3li0t@project]$ killall node
node: no process found
[ts3li0t@project]$ node test.js 
{ [Error: listen EADDRINUSE 127.0.0.1:51235]
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 51235 }
{ [Error: listen EADDRNOTAVAIL ::1:51235]
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '::1',
  port: 51235 }
ok: 0.0.0.0:51235

Thank you!

**Comment by ArtemGovorov** [comment]
Thanks for checking. Just published Wallaby Core v1.0.393, please try it and let me know how it goes.

**Comment by ts3li0t** [comment]
I'd read about how great support was for WallabyJS, but quite frankly I'm still astonished.

It works - both localhost and wallabyjs.com/app. Thank you very much! Very appreciated.

FWIW - The app loads successfully in Chrome and Firefox but then a slew of the following error still appears but eventually stop:

main.a591c00â¦.js:2 WebSocket connection to 'ws://127.0.0.1:52748/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Nonetheless, the UI loads and shows coverage by test, file, etc. All appears to be working as expected but wanted to pass along that error in case you couldn't reproduce and it would be of some value.

Thanks again!

**Comment by ArtemGovorov** [comment]
Great, thanks for checking!

> main.a591c00â�¦.js:2 WebSocket connection to 'ws://127.0.0.1:52748/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

This is expected. Wallaby App has a range of ports it tries to connect to that wallaby app server may be using (depending on what port from the range is free).

**Comment by ts3li0t** [comment]
Thought that may be the case. Appreciate it. Thanks again.
