### ISSUE TITLE
wallaby.outputContentSize

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1055]
Where do I set wallaby.outputContentSize ? Thanks.

Am getting: --- output truncated to 204800 bytes (use the "wallaby.outputContentSize" user setting to change the bytes limit) ---

Am running VS Code on Mac.

I tried in wallaby config, in setup function and in vscode user setting, none led to what I needed.

**Comment by ArtemGovorov** [comment]
> vscode user settings

It is set in VS Code user settings. Just checked and it is working for me:

![screen shot 2017-03-06 at 2 36 29 pm](https://cloud.githubusercontent.com/assets/979966/23596887/569ef960-027a-11e7-85b0-41ba8fece27a.png)

(I'm setting the limit to 400 bytes and it is respected)

> none led to what I needed.

So what happens in your case? Does the "output truncated" message change to reflect the setting in your user settings?
