### ISSUE TITLE
Feature Request: Support for skipped tests

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#1056]
Hi Artem,

I use skipped tests quite heavily to take note of future functionality I plan to build. They serve as reminders. At present, the only way I can get a consolidated list of these it to run my `npm test` process and get a spec report.

It would be quite nice, and I think useful to others if the tests were highlighted in the IDE margin with a unique color (cyan perhaps) so they stood out and also if these tests were listed an counted in Wallaby App.

Your thoughts?

regards,
Dave

**Comment by ArtemGovorov** [comment]
Thanks for the feature request and for the ideas. Please feel free to subscribe to theese two issues below to get notified once the feature is implemented:
https://github.com/wallabyjs/public/issues/972
https://github.com/wallabyjs/public/issues/334

**Comment by zpydee** [comment]
Will do, thanks.
