### ISSUE TITLE
Support importing files from outside the app root

### ISSUE THREAD

**Issue by HowlingEverett** [wallabyjs/public#1064]
### Issue description or question
This is a similar request to https://github.com/wallabyjs/public/issues/68, but my use case is a little different, so I figured for clarity I'd capture it into an new issue.

My application and tests are one package in a monorepo, that with a file structure that looks roughly like this:

```
- monorepo
  |- packages
    |- my-app
        - wallaby.config.js
        - source
    |- shared-fixtures-package
        |- fixtures
           - fixture-i-my-app-tests-reference.json
```

The issue is the monorepo has some shared fixtures that live in a package outside of my particular application. There are other apps in the monorepo that also reference these fixtures in tests and we update them in a common location, so I can't just copy them over to my app.

If I run wallaby by a config in `my-app` I get import failures because the relative imports for the json files in `shared-fixtures-package` aren't found (I assume they aren't copied over to Wallaby's cache since they would require the cache to have a totally different directory structure).

If I try to run the wallaby as a global config in `monorepo` but select files in my app package only, I get relative import errors for node_modules in the `my-app` tests.

Ideally, I'd be able to just specify the external paths in my `files` config in wallaby.config.js and have it work, but I'd also be happy for a workaround if it could get Wallaby going for my project.

**Comment by ArtemGovorov** [comment]
> I assume they aren't copied over to Wallaby's cache since they would require the cache to have a totally different directory structure

Yes, your assumption is correct.

> If I try to run the wallaby as a global config in monorepo but select files in my app package only, I get relative import errors for node_modules in the `my-app` tests.

I think giving node a [hint via NODE_PATH](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) should work for you. Given that `wallaby.config.js`in the `monorepo` folder

```javascript
module.exports = function (wallaby) {
  var path = require('path');
  process.env.NODE_PATH += path.delimiter 
    + path.join(wallaby.localProjectDir, 'packages/my-app/node_modules');
  return {
    files: [
      'packages/my-app/**/*.*', // <-- also test patterns need to be excluded 
      'packages/shared-fixtures-package/**/*.json'
    ],
    ...
  };
};
```

**Comment by HowlingEverett** [comment]
Thanks, that's got me further - package local node_modules are now available. Unfortunately, fixing that has got me back to the issue I was having with `mocha` and requiring `describe` and `it`: https://github.com/wallabyjs/public/issues/1059.

My current config looks like this:

```js
const path = require('path')

module.exports = wallaby => {
  process.env.NODE_PATH += path.delimiter +
    path.join(wallaby.localProjectDir, 'packages/my-app/node_modules')
  return {
    files: [
      'components/abby/source/**/*',
      'components/peter/docs/blueprints/*',
      '!components/abby/source/**/*-test.js'
    ],

    tests: [
      'components/abby/source/**/*-test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: {
      type: 'mocha',
      path: 'mocha'
    },

    setup: (wallaby) => {
      require('boiler-room-builder/scripts/test/setup')
      const extensions = require('boiler-room-builder/config/extensions')

      function noop () { return {} }
      [].concat(
        extensions['css'],
        extensions['sass'],
        extensions['audio'],
        extensions['fonts'],
        extensions['images'],
        extensions['video']
      ).forEach((ext) => {
        require.extensions[`.${ext}`] = noop
      })
    }
  }
}
```

which is giving me the same old output of...

```
​​[Error]: Runtime error: TypeError: (0 , _mocha.describe) is not a function​​
​​[Error]:     at Object.<anonymous> (./components/abby/source/routes/donate/components/Amount/__tests__/Amount-test.js:66:36)​​
​​[Error]:     at Module._compile (module.js:571:32)​​
​​[Error]:     at Object.Module._extensions..js (module.js:580:10)​​
​​[Error]:     at Module.load (module.js:488:32)​​
​​[Error]:     at tryModuleLoad (module.js:447:12)​​
​​[Error]:     at Function.Module._load (module.js:439:3)​​
​​[Error]:     at Module.require (module.js:498:17)​​
​​[Error]:     at require (internal/module.js:20:19)​​
​​[Error]:     at /Users/justin.marrington/code/zuul/node_modules/mocha/lib/mocha.js:222:27​​
​​[Error]:     at Array.forEach (native)​​
​​[Error]:     at Mocha.loadFiles (/Users/justin.marrington/code/zuul/node_modules/mocha/lib/mocha.js:219:14)​​
​​[Error]:     at Mocha.run (/Users/justin.marrington/code/zuul/node_modules/mocha/lib/mocha.js:487:10)​​
​​[Error]:     at emitTwo (events.js:106:13)​​
​​[Error]:     at WebSocket.emit (events.js:192:7)​​
​​[Error]:     at afterWrite (_stream_writable.js:383:3)​​
​​[Error]:     at onwrite (_stream_writable.js:374:7)​​
​​[Error]:     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]:     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]:     at Zlib.callback (zlib.js:625:5)​​
```

If I change the testFramework config to:

```js
testFramework: {
      type: 'mocha',
      path: 'components/abby/node_modules/.bin/mocha'
    },
```

... then I no longer get the runtime errors, but Wallaby just spins its wheels and never finishes initialising (no log output)

**Comment by ArtemGovorov** [comment]
With this in place:
```javascript
process.env.NODE_PATH += path.delimiter +
    path.join(wallaby.localProjectDir, 'components/abby/node_modules')
```
if `mocha` module is installed in the `components/abby/node_modules`, you may remove the 
```
testFramework: {
  type: 'mocha',
  path: 'components/abby/node_modules/.bin/mocha'
},
```
setting completely and it should work for you, because `mocha` is the default and wallaby will just try to `require('mocha')` that should resolve the mocha from the `components/abby/node_modules` because of the hint. Please check without the test it the `testFramework` setting.

**Comment by HowlingEverett** [comment]
No change after removing the testFramework setting, unfortunately.

(Pre-empting other mystery configs, the `boiler-room-builder/scripts/test/setup` require in setup is just pulling in and configuring JSDOM.)

**Comment by ArtemGovorov** [comment]
I have created this branch https://github.com/wallabyjs/wallaby-node-iojs-sample/tree/i1064 to simulate your environment, installed mocha into a subfolder, and it's working for me. Try cloning the repo, `cd lib`, `npm i` and run wallaby to see if it's working for you.

**Comment by HowlingEverett** [comment]
That example does work for me. It's not using Babel, but other than that is a pretty like for like reproduction.

Damn, there must be something weird about our monorepo's configuration, but I've exhausted the obvious candidates. It's a shame - the standard mocha execution works fine, but it's not that live Wallaby experience I'm used to in my personal projects :)

**Comment by HowlingEverett** [comment]
Anyway, thank you for the help. I'm a big fan of Wallaby when I can use it :D

**Comment by ArtemGovorov** [comment]
There may be something wrong with the paths.
If you do this in your wallaby config:
```javascript
module.exports = wallaby => {
  process.env.NODE_PATH += path.delimiter +
    path.join(wallaby.localProjectDir, 'components/abby/node_modules')

  console.log(require(path.join(wallaby.localProjectDir, 'components/abby/node_modules/mocha/package.json')).version)
...
```
what does it print on the Wallaby Console when it starts?

**Comment by HowlingEverett** [comment]
```
[Info]: wallaby.js started​​​​​
​​​​​[Info]: 3.2.0​​​​​
​​​​​[Info]: Wallaby App available at: http://wallabyjs.com/app/#/files​​​​​
​​​​​[Info]: 3.2.0​​​​​
​​​​​[Info]: 3.2.0​​​​​
​​​​​[Info]: 3.2.0​​​​​
​​​​​[Info]: 3.2.0​​​​​
​​[Error]: Runtime error: TypeError: (0 , _mocha.describe) is not a function​​
```

However, the exception stack trace suggests it's using the mocha dep that's in the parent repo. That version is also 3.2.0.

**Comment by ArtemGovorov** [comment]
> the exception stack trace suggests it's using the mocha dep that's in the parent repo. That version is also 3.2.0.

This is interesting, could you please share some more details on this? What does the stack trace look like and where is the parent repo located? Is it the `monorepo` root, do you have node modules there as well?

**Comment by HowlingEverett** [comment]
It's the `monorepo` root. Stacktrace below...

```
[Error]: Runtime error: TypeError: (0 , _mocha.describe) is not a function​​
​​[Error]:     at Object.<anonymous> (./components/abby/source/routes/donate/components/Amount/__tests__/Amount-test.js:66:36)​​
​​[Error]:     at Module._compile (module.js:571:32)​​
​​[Error]:     at Object.Module._extensions..js (module.js:580:10)​​
​​[Error]:     at Module.load (module.js:488:32)​​
​​[Error]:     at tryModuleLoad (module.js:447:12)​​
​​[Error]:     at Function.Module._load (module.js:439:3)​​
​​[Error]:     at Module.require (module.js:498:17)​​
​​[Error]:     at require (internal/module.js:20:19)​​
​​[Error]:     at /Users/justin.marrington/code/monorepo/node_modules/mocha/lib/mocha.js:222:27​​
​​[Error]:     at Array.forEach (native)​​
​​[Error]:     at Mocha.loadFiles (/Users/justin.marrington/code/monorepo/node_modules/mocha/lib/mocha.js:219:14)​​
​​[Error]:     at Mocha.run (/Users/justin.marrington/code/monorepo/node_modules/mocha/lib/mocha.js:487:10)​​
​​[Error]:     at emitTwo (events.js:106:13)​​
​​[Error]:     at WebSocket.emit (events.js:192:7)​​
​​[Error]:     at afterWrite (_stream_writable.js:383:3)​​
​​[Error]:     at onwrite (_stream_writable.js:374:7)​​
​​[Error]:     at afterTransform (_stream_transform.js:79:3)​​
​​[Error]:     at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​[Error]:     at Zlib.callback (zlib.js:625:5)​​
```

Half of the reason I closed the issue was because this is a weird project 😛.

The history is that the back-end devs before us set it up as a monorepo for their own purposes, but made the root application as a Rails app, which also included a React UI that they built in React and load via the `webpack-rails` gem. That gem mandates that it's package.json/node_modules, etc be located at the root of the repository. Since that app is also tested via mocha and has similar behaviour, it's got mocha, webpack, etc as deps in the root.

The next-gen version of the UI lives in that repo's `components` and is a self-contained isomorphic React app. That's the `abby` part I'm developing/testing on, and trying to get Wallaby to run tests against. It retrieves it's data from another sibling `components` package that serves the application's API, and in tests loads fixtures from a shared `components` package.

Ideally, our Monorepo would have no application sitting in the root of the repository, and this would be a non-issue. It's not an ideal setup to be sure, but it's what I've inherited for now.

**Comment by ArtemGovorov** [comment]
I tried to reproduce it in the sample repo by adding mocha to the root as well, but it's still working. I have a suspicion that a different instances of mocha are used to run your tests and imported into the test file when you `require`/`import` it. I'm not yet sure how it could happen because I can't reproduce it, but let's try something. Add this to your setup function:

```javascript
    setup: (wallaby) => {
      if (!global._requireReplaced) {
        var path = require('path');
        var Module = require('module').Module;
        var modulePrototype = Module.prototype;
        var originalRequire = modulePrototype.require;
        modulePrototype.require = function (filePath) {
          if (filePath === 'mocha') {
            return originalRequire.call(this, path.join(wallaby.localProjectDir, 'node_modules/mocha/index.js'));
          }
          return originalRequire.call(this, filePath);
        };
        global._requireReplace = true;
      }
      ... the rest of your setup function
    }
```
This redirects all mocha imports to one place and should make sure the same version of mocha is used.

**Comment by HowlingEverett** [comment]
You're a gentleman and a scholar, that was exactly it. Tests are running perfectly now, thank you 😄.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
