### ISSUE TITLE
WallabyJS with mocha and angular-cli

### ISSUE THREAD

**Issue by arranbartish** [wallabyjs/public#1065]
I've made awesome progress while using wallabyJS. Really awesome test runner! 

This is probably another newbie/pebkac (problem exists between keyboard and chair) issue, so I apologize in advance.  

### Question

I am trying to use Wallaby and Mocha+chai+sinon instead of the default Jasmine configured by angular-cli. 

So far I've:
1. ripped out all the Jasmine dependencies and added the mocha+chai+sinon ones.
2. updated wallabyTest.ts with the mocha-patch from zone.js
3. using the info in #821 has given me no joy
    1. Importing these dependencies globally I get sinon not defined from wallaby
    1. When I add imports per test I get `Uncaught Error: Cannot find module './sinon/util/core'` which led me to #821

- It would seem my error is that I am not in fact importing globally like I think I am, which would explain the change in behavior when I add the import to the test. 
- Ideally my preference would be to import globally but I think I am missing something totally fundamental.

I am focusing on `listing.component.spec.ts` so and will convert the other tests next. 

Any hints would be most appreciated at this point. 

### Wallaby.js configuration file

Link: https://github.com/arranbartish/angular-cli-seed/tree/feature/change-to-mocha

Repo: https://github.com/arranbartish/angular-cli-seed
Branch: feature/change-to-mocha

### Code editor or IDE name and version

WebStorm: 2016.3.4

### OS name and version

Windows: 10

Thanks in advance,
Arran

**Comment by ArtemGovorov** [comment]
I have [sent you the pull request](https://github.com/arranbartish/angular-cli-seed/pull/18). The order of the files was slightly incorrect (`sinon-chai` needs `chai`, so `chai` needs to be loaded first), also chai `expect` needs to be exposed via the window object (that's what I did in the `setup` function). Just because other tests still use jasmine API, I have included just the test file you've mentioned.

Everything else looks good. However, when you run the config, you'll still see the error:

```
Cannot read property 'return' of undefined
```
originating from
```
const mockedGetCars = sinon.stub().and.return(mockCarsResponse);
```
It makes sense, because the `sinon.stub()` execution result doesn't have the `and` property out-of-box (neither `sinon` nor `sinon-chai` seem to have it). Perhaps there's some other library that is missing?

**Comment by arranbartish** [comment]
Amazing as always. I'll merge the pull request and see if I can't get all the tests to run. I'll post the working link in this issue for anyone else who struggles. 

I didn't realize the order was important... literally days playing with commenting, uncommenting, and googling.

**Comment by arranbartish** [comment]
Absolutely awesome! thank you. 

I am going through the remaining tests and converting them to mocha + sinon. The repository link is already in this issue, however i'll post the link again after it's merged because i'll delete the branch

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by arranbartish** [comment]
Anyone finding this from the interweb, the conversion for unit tests to mocha using wallabyjs was a doddle, thanks/kudos to @ArtemGovorov for helping me get that newbie issue sorted. 

The change is stuck on the branch referenced above until I resolve issues around protractor described in issue arranbartish/angular-cli-seed#19. If only all runners worked as well as wallabyjs 👍 

If you want to see wallabyjs + mocha on angular-cli it's a perfectly valid example arranbartish/angular-cli-seed@e2bc13cd51a4a16911039b853084f5b884966bc9 

all ng targets work except for `ng e2e`

**Comment by arranbartish** [comment]
Last note on this. 

Fully plumbed example of wallabyjs + karma + protractor all using mocha for unit and e2e tests. 

Link to actual commit in case the code base moves on. 
https://github.com/arranbartish/angular-cli-seed/tree/d60046e1e8767bef1a42eea2a3ee91b7c7de6569
