### ISSUE TITLE
Wallaby Webpack with modulesDirectories

### ISSUE THREAD

**Issue by BrianHanechak** [wallabyjs/public#1067]
### Issue description or question

I have a project using wallaby, webpack, typescript, and npm. I currently need to override one of the npm packages I use with a different version, and I've done this for my main build by using the "resolve.modulesDirectories" option from WebPack 1. I've also gotten this to work with the "resolve.modules" option from WebPack 2.

I can't get this working with wallaby-webpack, though. If I use resolve.modulesDirectories, it tells me that this is an unrecognized option. If I use resolve.modules, it fails to find my updated version.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackPostprocessor = wallabyWebpack({ resolve: { modules: [ "module_patches", "node_modules" ] } });

module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'scripts/**/*.ts', load: false },
      { pattern: 'scripts/**/*-spec.ts', ignore: true },
      { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },      
    ],

    tests: [
      { pattern: 'scripts/**/*-spec.ts', load: false }
    ],

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    debug: true,

    preprocessors: {
      '**/*.js': file => require("babel-core").transform(file.content, {
        sourceMap: true,
        compact: false,
        presets: ["es2015"]
      })
    },
    
    setup: function () {
      window.__moduleBundler.loadTests();
    }    
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.x

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
You need to point wallaby-webpack to your local folder, as [described here in the docs](https://wallabyjs.com/docs/integration/webpack.html#module-resolution-issues).

```javascript
var webpackPostprocessor = wallabyWebpack({ resolve: { modules: [ require('path').join(__dirname, 'module_patches'), "node_modules" ] } });
```

Please let me know if this fixes the issue for you.

**Comment by BrianHanechak** [comment]
Yes! Thank you!

I misread that section of the documentation. I had somehow thought that it indicated that modules_directories is supported, but it's clearer upon re-reading it that it's not (and that this is the preferred solution.)

Should I drop "node_modules" from the list entirely, since it's not an absolute path in this case so it's probably not doing anything, and "node_modules" is included by default?

 - Brian

**Comment by ArtemGovorov** [comment]
I think you should be able to drop `node_modules`, it shouldn't change anything.
