### ISSUE TITLE
Cannot find alias path module for testing with typescript, webpack

### ISSUE THREAD

**Issue by maierson** [wallabyjs/public#1068]
### Issue description or question
I am experimenting with using aliases for paths in imports as follows:

tsconfig compiler options:

```javascript
 "compilerOptions": {
        "baseUrl": ".",
        "rootDir": "./",
        ...
       "paths": {
            "icons/*": [
                "app/base/assets/icons/*"
            ]
        }
    },
```

webpack.config
```javascript
   ...
   resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.json', '.css', '.scss'],
        modules: [
            PATHS.app,
            'node_modules'
        ],
        alias: {
             icons: path.resolve(__dirname, 'app/base/assets/icons/'),
        },
    },
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        debug: true,

        files: [
            'app/**/*.ts?(x)',
            'app/**/*.css',
            "!app/**/*spec.ts?(x)"
        ],

        tests: [
            'app/**/*spec.ts?(x)'
        ],

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs',// jscs:ignore
                jsx: 'react'
            })
        },

        testFramework: 'mocha',

        env: {
            type: 'node'
        },

        workers: {
            //initial: 1,
            regular: 1
        },

        setup: function () {
            var jsdom = require('jsdom');
            global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
            global.window = document.defaultView;
            global.navigator = global.window.navigator;
            global.HTMLElement = global.window.HTMLElement;
            global.HTMLAnchorElement = global.window.HTMLAnchorElement;
            // global.CustomEvent = global.window.CustomEvent;
            // get window props for stuff like getComputedStyle etc.
            let window = document.defaultView;
            for (let key in window) {
                if (!window.hasOwnProperty(key)) continue
                if (key in global) continue
                global[key] = window[key]
            }
            require.extensions[".css"] = () => { };
            require.extensions[".svg"] = () => { };
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version
MacOS Sierra

OSX

Now I can import Icon files as such:

```javascript
import { Icon } from 'icons/Icon'
```

When running webpack it fails with this error:

```javascript
Error: Cannot find module 'icons/Icon'​​
  at Object.<anonymous> ​app/book/view/edit/BookEditBarButton.tsx:2​
  at Object.<anonymous> ​app/book/view/edit/BookEditorBar.tsx:2​
  at Object.<anonymous> ​app/book/view/edit/BookEditorBarContainer.tsx:6​
```

Thank you.

**Comment by ArtemGovorov** [comment]
What is the extension of the `icons/Icon` file?

**Comment by ArtemGovorov** [comment]
If the extension is `.svg` (or anything else), then you just need to add the icons pattern to your `files` list, because [all of the files used in tests/app need to be there](https://wallabyjs.com/docs/config/files.html).

```javascript
module.exports = function (wallaby) {
    return {
        debug: true,

        files: [
            'app/**/*.ts?(x)',
            'app/**/*.css',
            'app/**/*.svg', // <---
            "!app/**/*spec.ts?(x)"
        ],
...
```

**Comment by maierson** [comment]
Hi Artem,

Thank you for the response. The Icon file is actually a .tsx file. It can have various paths (as in svg path) injected into it  via the children property.

```
export const Icon: React.SFC<any> = (props: IProps) => {

    const containerClass = iconCss.container + ' ' + props.containerClassName;

    return (
        <div
            id={props.id}
            className={containerClass}
            style={props.containerStyle}
            onClick={props.onClick}
            onMouseOver={props.onMouseOver}
            onMouseOut={props.onMouseOut}>
            <svg
                id={props.id && props.id + '_svg'}
                className={props.className}
                style={{ ...styles.inner, ...props.style }}
                width={props.width || 35}
                height={props.height || 35}
                viewBox={`0 0 ${props.boxWidth || 35} ${props.boxHeight || 35}`}
                strokeLinecap='round'
                strokeLinejoin='round'
            >
                {props.children}
            </svg>
        </div>
    )
}
```

And here is a path example:

```
export const BookCoverPath: React.SFC<any> = (props) => {
    return (
        <path
            d="M18 2H6c-1.1 0-2 .9-2 2v16c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zM6 4h5v8l-2.5-1.5L6 12V4z"
            {...props} />
    )
}
```

I don't have any .svg extension files. So I don't think that's the issue. I've read through some threads that use wallaby-webpack and there were some mentions about wallaby cache. But I haven't had the time to go in depth. It seems to me that wallaby cannot follow the alias to the module when launching.

**Comment by maierson** [comment]
Also if I use relative paths all works fine in testing.

**Comment by ArtemGovorov** [comment]
Oh, I see the issue now, thanks for the explanation, I should actually have realised what it was with from your first post, there was enough information in it, sorry about the delay.

So you're running tests in `node` environment, so just need to [give node.js a hint how to resolve the module-like non relative imports](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) like `icons/Icon`:

```javascript
module.exports = function (wallaby) {
  var path = require('path');
  process.env.NODE_PATH += path.delimiter + path.join(wallaby.localProjectDir, 'app/base/assets/icons');
    return {
        ...
...
```

Please let me know if this works for you.

**Comment by maierson** [comment]
Unfortunately it didn't work (same error message). Just to make sure this is the complete updated wallaby.js. Am I missing something? (thanks for the link btw)

```

module.exports = function (wallaby) {

    var path = require('path');
    process.env.NODE_PATH += path.delimiter + path.join(wallaby.localProjectDir, 'app/base/assets/icons')

    return {
        debug: true,

        files: [
            'app/**/*.ts?(x)',
            'app/**/*.css',
            'app/**/*.svg',
            "!app/**/*spec.ts?(x)"
        ],

        tests: [
            'app/**/*spec.ts?(x)'
        ],

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs',// jscs:ignore
                jsx: 'react'
            })
        },

        testFramework: 'mocha',

        env: {
            type: 'node',
        },

        workers: {
            //initial: 1,
            regular: 1
        },

        setup: function () {
            var jsdom = require('jsdom');
            global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
            global.window = document.defaultView;
            global.navigator = global.window.navigator;
            global.HTMLElement = global.window.HTMLElement;
            global.HTMLAnchorElement = global.window.HTMLAnchorElement;
            // global.CustomEvent = global.window.CustomEvent;
            // get window props for stuff like getComputedStyle etc.
            let window = document.defaultView;
            for (let key in window) {
                if (!window.hasOwnProperty(key)) continue
                if (key in global) continue
                global[key] = window[key]
            }
            require.extensions[".css"] = () => { };
            require.extensions[".svg"] = () => { };
        }
    };
};


```
I also tried with same result :
`
process.env.NODE_PATH += path.delimiter + path.join(wallaby.localProjectDir, 'icons', 'app/base/assets/icons')
`

**Comment by ArtemGovorov** [comment]
Try this:
```javascript
    var path = require('path');
    process.env.NODE_PATH += path.delimiter + path.join(wallaby.projectCacheDir, 'app/base/assets');
```

**Comment by maierson** [comment]
Good call. Wallaby actually manages to launch without error. So there is progress. 

But the actual test fails not finding the Icon component. Here is the error message depending on how I'm doing the Icon import in the test (relative vs module)


```
import { Icon } from 'icons/Icon'

// error in test
Enzyme::Selector expects a string, object or Component Constructor.

```

![screen shot 2017-03-16 at 10 59 40 am](https://cloud.githubusercontent.com/assets/16655922/24002729/e2434e66-0a37-11e7-8fac-db48115eafed.png)

Or with relative import:

```
import { Icon } from '../../assets/icons/Icon'

// error in test
expected 0 to equal 1
```
![screen shot 2017-03-16 at 11 07 05 am](https://cloud.githubusercontent.com/assets/16655922/24003067/cd6554f2-0a38-11e7-9254-4c78dc06a97a.png)

**Comment by ArtemGovorov** [comment]
Unfortunately I'm not much familiar with enzyme, so not sure what's going on here. Could you please share a small sample where I could reproduce the issue? I'm happy to have a look.

**Comment by maierson** [comment]
To simplify basically enzyme is saying that it needs either a string (for tagnames ie `'div'`), an actual instance of the component (ie `<Icon/>`) or a Component Constructor (ie` Icon`) in order to locate it inside the shallow representation of the tested component. So the error message means that it's not finding the code for the Icon component when located via `icons/Icon` alias. 

When locating it via the relative path `../../assets/icons/Icon` it can find it but it probably thinks it's a different component since the path is different from the one mounted inside the tested component  via the alias `icons/Icon`. Hence the 0 found error message.

I'll look into putting together a sample.

**Comment by ArtemGovorov** [comment]
I have created this [basic sample](https://github.com/ArtemGovorov/wallaby-1068) with your config and the `Icon.tsx` file and it's working for me. The test is not exactly like yours, but seems to be quite similar. Please have a look and if it's working for you, try adding things that break the sample like in your scenario.

**Comment by maierson** [comment]
Hi Artem,

Thank you for this. I really appreciate it.

I've tried up the project and indeed all works. First I thought that the Icon needs to be inside another component for it to fail but tried that and the test for it still works.

So I'm at a loss right now. I need to carve out some time and see what specifically could be causing this in my project. One thing I noticed is in the test where I import Icon from alias it is undefined hence enzyme complaining that it's missing the correct argument.

```
import { Icon } from 'icons/Icon'

console.log(Icon) // undefined -> should be [Function]

```
If anything else to try comes to mind please let me know otherwise I'll be in touch once I make some progress in figuring this.

Thanks again.
