### ISSUE TITLE
wallaby-webpack initial build performance

### ISSUE THREAD

**Issue by yaroslavya** [wallabyjs/public#1069]
### Issue description or question
Based on the previous issue (https://github.com/wallabyjs/public/issues/1057) i managed to configure wallaby and its running the tests. But in a real project the build is taking a long time to run. My karma build is using the hardsource plugin and webpack dll plugin, so the initial build time is very fast. Is there any way I can do the same with wallabyjs? As I provide the config to the wallabyjs, can I specify the dll reference plugin and the hardsource plugin to speed up the compile time? 

Also I noticed that tests are taking more time than you see if you open wallabyjs.com/app/#/tests
For me single test is taking, say 1 second. Im changing something inside the test, like adding a simple console.log and it takes about 3-5 seconds to actually see the changed results. I made these numbers, but the main point is that its taking significantly more time, than it shows on the web interface.

I observe both issues on a big codebase, with about 60 tests and 2mb of source. The setup is very similar to the one I published for initial configuration. If theres a general advice on how to speed tests up, that would be sufficient. Im, not able to publish the real code, but can give you any wallaby logs or anything to help to reproduce the problem.

Let me know if you need any other information.

**Comment by ArtemGovorov** [comment]
Please share your current wallaby config file and (perhaps as a separate gist) the full output from the Wallaby Console. Please capture 2 log samples: one for starting the tool from the scratch on your project, then clear the log output, change a test and capture the second log sample.

**Comment by ArtemGovorov** [comment]
Please also share your webpack config so I could have a look if the hardsource plugin and webpack dll plugin could be used in wallaby-webpack config as well.

**Comment by yaroslavya** [comment]
Heres the link to the [webpack config](https://github.com/yaroslavya/ng2-wallaby/blob/master/cfg/webpack.karma.js)
the list of assets I wrap into dll can be found [here](https://github.com/yaroslavya/ng2-wallaby/blob/master/cfg/webpack.dll.js)

Heres are the plugins I configure to speed up the initial compilation and the subsequent builds(extract from the above webpack config):

       config.plugins.push(new Webpack.DllReferencePlugin({
            context: ".",
            manifest: require("../dll/polyfill-manifest.json")
        }));

        config.plugins.push(new Webpack.DllReferencePlugin({
            context: ".",
            manifest: require("../dll/ng2vendor-manifest.json")
        }));

        config.plugins.push(
            new (require('hard-source-webpack-plugin'))({
                cacheDirectory: __dirname + '/tmp/hard-source/[confighash]',
                recordsPath: __dirname + '/tmp/hard-source/[confighash]/records.json',
                configHash: (require('node-object-hash'))().hash
            })
        );

Need some time to post the wallaby log here, will only make it tomorrow.

**Comment by yaroslavya** [comment]
Thanks for the help, Artem, but I did it already. The perf problem of 1 second per test(note, 1 second is reported by the wallaby reporter, the time to actually see the result is about 3 seconds) was there after I did it. It really improved the performance as before switching to electron it was something about 3-5 seconds per test(note, it was the time reported by wallabyjs, the time to see the changes was about 6-10 seconds), which was way too slow. Still speeding up the initial build and subsequent ones can do a lot. I will post the wallabyjs log later today.

**Comment by yaroslavya** [comment]
Sorry for the delay, just sent all the log files by email. Let me know if more info is needed.

**Comment by ArtemGovorov** [comment]
Thanks for sending the logs. 

I have had a look, and the regular test run seems to be ok: 
- webpack incremental compilation is taking some time, 
- your test bootstrapping (all angular related stuff loading) takes some time, 
- test execution itself takes some time.
Only the `test execution` is reported in wallaby app, it is what the testing framework (jasmine) reports back to wallaby. As you can see, the total time includes a couple more things that are not really wallaby specific.

Regarding the initial startup, I will look into the dll reference plugin and the hardsource plugin to see if they can be used with [wallaby-webpack](https://github.com/jeffling/wallaby-webpack) to speed things up. I have never used the plugins, so may take me some time. The good thing is that the wallaby-webpack project is OSS, so you may also look into to see if it's possible to make the plugins work there.

**Comment by yaroslavya** [comment]
Thanks for the quick reply, Artem. I`ll check if any of the plugins will work in wallaby and post the update here. I think if it will work and speed things up it may be helpful for other webpack users.

**Comment by yaroslavya** [comment]
Tried the DllReference plugin and have the following error messages:

Uncaught ReferenceError: polyfill is not defined
at http://localhost:64767/__modules/31.js?1489921933173:1

Uncaught ReferenceError: ng2vendor is not defined
at http://localhost:64767/__modules/8.js?1489921933189:1

Uncaught ReferenceError: polyfill is not defined
at http://localhost:64767/__modules/31.js?1489921933173:1

Uncaught TypeError: __webpack_require__(...) is not a function
at http://localhost:64767/__modules/40.js?1489921933704:1

Im not sure, but it looks like wallaby need the actual bundles included. I only changed the plugins, by adding the DllReference plugin like that:
plugins: [
        new DefinePlugin({
            'ENV': JSON.stringify(ENV)
        }),
        //NOTE: previously it was used to add the dll folder contents to webpack. Now it didnt work so I just added 2 references for polyfills and vendors below
        //new CopyWebpackPlugin([{ from: "dll" }]),
        new Webpack.DllReferencePlugin({
            context: ".",
            manifest: require("absolute/path/to/dll/folder/polyfill-manifest.json")
        }),
        new Webpack.DllReferencePlugin({
            context: ".",
            manifest: require("absolute/path/to/dll/folder/ng2vendor-manifest.json")
        })
    ]

Also added these ones as the first files:
files: [
            {pattern: 'dll/polyfill.js', load: false},
            {pattern: 'dll/ng2vendor.js', load: false},
            //the rest of the files below

I tried to both include and exclude the CopyWebpackPlugin, add polyfill and ng2vendor to files and comment them out. The result is always the same. It seems the compiled polyfills and vendors are not visible to webpack. Not sure how to configure them right. As far as I got it wallaby copies all the assets somewhere where its processing them. Maybe some paths are broken so the plugins cant kick in and polyfills and vendors are not found. 

Note, if I dont use the dll reference plugin the vendors are visible as I always include the reference to the files which list all the vendors. As far as I understand I should include them into entryPatterns to be visible. So I tried this as well and it add 2 more errors:
Specified entry pattern "dll/polyfill.js" does not match any file.

Specified entry pattern "dll/ng2vendor.js" does not match any file.

thats very strange as the files are there, in the dll folder which is at the same level as test and src folder. So not sure why wallabyjs doesnt find them. Let me know if you need any other details.

**Comment by ArtemGovorov** [comment]
Not sure what's going on, as I've never worked with these plugins. Seems like something somewhere needs `polyfill` and `ng2vendor` to be loaded globally, so you may try:
```javascript
{pattern: 'dll/polyfill.js', load: true},
{pattern: 'dll/ng2vendor.js', load: true},
```
and that'll just [load the files via script tags](https://wallabyjs.com/docs/config/files.html#file-object) into the sandbox.
