### ISSUE TITLE
False reporting of "Some long running code has been detected"

### ISSUE THREAD

**Issue by damonmaria** [wallabyjs/public#1071]
### Issue description or question

I'm suddenly getting the following reported 6 times when Wallaby first starts:
`Some long running code has been detected: one of your tests is taking more than 5000ms to execute.`

No tests are marked as failed, this is only visible in the console (so I don't know how long I've been getting it).  if I use the Wallaby web app then no tests take anywhere near 5000ms in the times it lists. 

If I run each of my spec files individually then only one file produces the same error (it also happens to be my largest test file), and it only generates one error, not 6. If I 'comment out' half the tests in that file then the error doesn't appear. If I then comment out the other half and run the originally commented out half by themselves then... no error either. So it isn't a specific test that's wrong. It's only when I remove a fair number of the tests from that file that the error goes away.

If I change `workers` (`regular` and `initial`) down to 1 the error still appears. 

My guess is that it's triggered only by a lot of tests being run. Any suggestions of how else I can track down what's going on? 

### Wallaby.js configuration file

I am using a config based off xolvio/qualityfaster, so it's large. Relevant parts here:

```javascript
{
    files: [
      'src/**/*.@(js|jsx)',
      'src/.specs/**/*.js',
      '!src/.specs/**/*.spec.js',
      '!src/**/*.spec.@(js|jsx)',
      '!src/**/*.story.@(js|jsx)',
      '!src/node_modules/**/*',
    ],
    tests: [
      'src/**/*.spec.@(js|jsx)',
      'src/.specs/**/*.spec.js',
      '!src/node_modules/**/*',
    ],
    compilers: {
      'src/**/*.@(js|jsx)': compiler,
      'src/.specs/**/*.js': compiler,
    },
    env: {
      type: 'node',
      runner: nodePath,
    },
    reportConsoleErrorAsError: true,
    testFramework: 'mocha',
    workers: {
      recycle: true,
    },
    debug: false,
    bootstrap: function () {
      ...long...
    }
}
```

### Code editor or IDE name and version

IntelliJ IDEA 2016.3

### OS name and version

MacOS 10.12.3

**Comment by ArtemGovorov** [comment]
> No tests are marked as failed, this is only visible in the console

Is my understanding correct and everything passes and is working ok, except that the error message is displayed?

Any chance I may get an access to the project to have a look?

> If I 'comment out' half the tests in that file then the error doesn't appear. If I then comment out the other half and run the originally commented out half by themselves then... no error either. So it isn't a specific test that's wrong.

It still may be a specific test or few tests that causing the issue. The reason why it may work when half of the tests are commented out is because perhaps the commented tests create some state that makes the subsequent tests to hang. And when there are commented out, everything is ok.

I may suggest trying to comment out smaller portions of tests to see if you can find the offender. I'd start by commenting out async tests (if any).

The issue may also be related to your `bootstrap` code. Could you please share the `bootstrap` function?

> If I change workers (regular and initial) down to 1 the error still appears.

Are you still getting 6 of these errors or just one (when you're running more than one test file)?

**Comment by damonmaria** [comment]
> Is my understanding correct and everything passes and is working ok, except that the error message is displayed?

Correct. I have counted the number of tests in code and it matches the number executed and passed.

> Any chance I may get an access to the project to have a look?

I can probably do that. I'm thinking read access to the Github repo would be all you'd need. I presume to the @ArtemGovorov user?

> I may suggest trying to comment out smaller portions of tests to see if you can find the offender. I'd start by commenting out async tests (if any).

I was trying that stratergy but wasn't having any success in pinning down a pattern to what was causing the error to show up. 

> The issue may also be related to your bootstrap code. Could you please share the bootstrap function?

The bootstrap is huge because it's a copy of Meteor's bootstrap code so I can run Meteor packages. Because there's so much to it and we use it across multiple projects I've created a (public) package for it: https://github.com/mindhivenz/wallaby-meteor-config. So you can see what I do in there. Sorry, it's pretty fugly.

> Are you still getting 6 of these errors or just one (when you're running more than one test file)?

I thought I had it so that removing that one (big) test caused all the errors to disappear but now when I remove it the number of errors drops from 6 to 5. So that makes more sense since that one file causes one error. What doesn't make sense is that if I run every other spec individually I don't get any errors. 

I will have more of a go at trying to isolate at pattern as to what causes the error to show up. And then pass it along to you if I remain stuck. 

Thanks again. You're always super response on here which makes the fee for Wallaby well worth it.

**Comment by ArtemGovorov** [comment]
> I can probably do that. I'm thinking read access to the Github repo would be all you'd need. I presume to the @ArtemGovorov user?

Thanks, the read access and some pointers where to start (the name of the test file that causes the issue) should be enough for me to get started. It is @ArtemGovorov user.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please provide the info requested above.

**Comment by damonmaria** [comment]
Just FYI. These tests were being run on Node 4 as it's a Meteor project. Meteor now runs on Node 8 and this issue (as well as other little niggles I was having with Wallaby) have disappeared. So I suspect Node version was the root cause.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
