### ISSUE TITLE
RangeError: RangeError: Maximum call stack size exceeded with Jest

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#1072]
### Issue description or question

Whilst editing a file, (seems to mostly be when there's syntax errors due to half-way-editing a line), I often get `RangeError: Maximum call stack size exceeded` in the wallaby failing tests window.

The callstack shows the following in the console
```
Runtime error: RangeError: Maximum call stack size exceeded
    at Runtime.l.requireModule (/Users/davebrotherstone/Library/Caches/WebStorm2016.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:12242)
    at Runtime.l.requireModule (/Users/davebrotherstone/Library/Caches/WebStorm2016.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:12242)
    at Runtime.l.requireModule (/Users/davebrotherstone/Library/Caches/WebStorm2016.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:12242)
```

This column position corresponds to this (around about the `c.apply(this,arguments)`:
```
var c=l.prototype.requireModule;l.prototype.requireModule=function(e,t,i){var n=c.apply(this,arguments);if(e&&~e.replace(/\\/g,"/").indexOf("jest-snapshot")&&"./utils"
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'package.json',
      'src/**/*.js',
      'src/**/*.ts',
      'src/**/*.tsx',
      '!src/**/__tests__/*.spec.ts',
      '!src/**/__tests__/*.spec.tsx',
      'src/**/*.unexpected-snap',
      'test-helpers/**/*.ts',
      'types/**/*.d.ts'
    ],
    tests: ['src/**/__tests__/*.spec.ts', 'src/**/__tests__/*.spec.tsx'],

    testFramework: 'jest',

    env: {
      type: 'node',
      runner: 'node'
    },
    debug: true,
    compilers: {
      'src/**/*.ts': wallaby.compilers.typeScript({}),
      'src/**/*.tsx': wallaby.compilers.typeScript({})
    },

    setup: function (wallaby) {
      var jestConfig = require('./package.json').jest;
      wallaby.testFramework.configure(jestConfig);
    }
  }
};
```

### Code editor or IDE name and version

WebStorm 2016.3.5
WebStorm 2016.3.5
Build #WS-163.15188.8, built on March 17, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version
OSX 10.11.6

If you need a repro case, I can try and put one together, but i've had this on multiple projects using Jest (with and without typescript)

**Comment by ArtemGovorov** [comment]
Thanks for the report! The bug is fixed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by bruderstein** [comment]
Awesome, as always! Thanks!
