### ISSUE TITLE
TypeError: Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by ssured** [wallabyjs/public#1073]
# TLDR

Overriding `create-react-app` with your own `jest` in `package.json` is not a good plan. Remove `jest` from your `package.json` and you should be good to go

### Issue description or question
Since the last update this error blocks wallaby in VSCode. Nothing changed in my codebas.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules are located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH = process.env.NODE_PATH || '';
  process.env.NODE_PATH += path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  // Babel needs this
  process.env.NODE_ENV = 'development';

  return {
    files: ['src/**/*.js', '!src/**/*.test.js'],

    tests: ['src/**/*.test.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    debug: true,

    setup: function(wallaby) {
      wallaby.testFramework.configure({
        // as in node_modules/react-scripts/utils/createJestConfig.js
        moduleNameMapper: {
          '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve(
            'react-scripts/config/jest/fileTransform.js'
          ),
          '^.+\\.css$': require.resolve(
            'react-scripts/config/jest/cssTransform.js'
          )
        }
      });
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

OSX Mavericks

### Wallaby logs:

```
​​​​​[Info]​​​​​ Mon, 20 Mar 2017 20:20:16 GMT wallaby:project Wallaby config: /Users/sjoerd/Documents/racido/wallaby.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.394
...
[Info]​​​​​ Mon, 20 Mar 2017 20:20:20 GMT wallaby:workers Running tests in sandbox [worker #4, session #x34gd]
​​​​​[Info]​​​​​ Mon, 20 Mar 2017 20:20:20 GMT wallaby:workers Running tests in sandbox [worker #5, session #7valg]
​​​​​[Info]​​​​​ Mon, 20 Mar 2017 20:20:21 GMT wallaby:workers Sandbox (active) [x34gd] error: TypeError: Cannot read property '_jasmineAdapter' of undefined
​​[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined​​
​​[Error]     at Runtime._execModule (/Users/sjoerd/Documents/racido/node_modules/jest-runtime/build/index.js:447:13)​​
​​[Error]     at Runtime.requireModule (/Users/sjoerd/Documents/racido/node_modules/jest-runtime/build/index.js:295:14)​​
​​[Error]     at jasmine2 (/Users/sjoerd/Documents/racido/node_modules/jest-jasmine2/build/index.js:80:13)​​
​​[Error]     at runTest (/Users/sjoerd/Documents/racido/node_modules/jest-cli/build/runTest.js:53:10)​​
​​[Error]     at promise.then (/Users/sjoerd/Documents/racido/node_modules/jest-cli/build/TestRunner.js:307:14)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:109:7)​​
​​​​​[Info]​​​​​ Mon, 20 Mar 2017 20:20:21 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property '_jasmineAdapter' of undefined, stack: TypeError: Cannot read property '_jasmineAdapter' of undefined
​​​​​[Info]​​​​​     at Object.<anonymous> (/Users/sjoerd/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2810)
​​​​​[Info]​​​​​     at Runtime._execModule (/Users/sjoerd/Documents/racido/node_modules/jest-runtime/build/index.js:447:13)
​​​​​[Info]​​​​​     at Runtime.requireModule (/Users/sjoerd/Documents/racido/node_modules/jest-runtime/build/index.js:295:14)
​​​​​[Info]​​​​​     at Runtime.l.requireModule (/Users/sjoerd/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.48/wallaby/runners/node/jest@0.4.3/initializer.js:14:12242)
​​​​​[Info]​​​​​     at jasmine2 (/Users/sjoerd/Documents/racido/node_modules/jest-jasmine2/build/index.js:80:13)
​​​​​[Info]​​​​​     at runTest (/Users/sjoerd/Documents/racido/node_modules/jest-cli/build/runTest.js:53:10)
​​​​​[Info]​​​​​     at promise.then (/Users/sjoerd/Documents/racido/node_modules/jest-cli/build/TestRunner.js:307:14)
​​​​​[Info]​​​​​     at process._tickCallback (internal/process/next_tick.js:109:7)
​​​​​[Info]​​​​​ Mon, 20 Mar 2017 20:20:21 GMT wallaby:workers Loaded unknown number of test(s)
​​​```

**Comment by ArtemGovorov** [comment]
We didn't change anything recently that could produce the error. 
I have generated [this sample](https://github.com/ArtemGovorov/wallaby-1073) with `create-react-app`, added your config and it's working for me.

Some other user have been reporting the issue before though (few months ago), in of the cases removing `node_modules` and re-running `npm install` helped, try it and let use know how it goes.

**Comment by ssured** [comment]
Weird. I can't get it to work. I checked out code from a week ago, I am sure that code was working. I removed node_modules and ran `yarn install`

Your repo is working for me

Any idea what could cause this? From my perspective this all happened on a restart of VSCode, which triggered an update of Wallaby. From that point in time I got the error in my repo. I don't know where to search and do not feel like moving code into a new project

**Comment by ArtemGovorov** [comment]
We didn't change anything related to the jest integration, so my guess is that the fact that it stopped working after wallaby update was just a coincidence and something must have changed in your environment. Also the fact that the clean `create-react-app` is working supports the theory.

Could you please share your `package.json` file? I'll try to install the modules you're using in the clean `create-react-app` to see if I can reproduce the issue.

**Comment by ssured** [comment]
```
{
  "name": "racido",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-preset-stage-1": "^6.22.0",
    "enzyme": "^2.7.1",
    "flow-bin": "^0.41.0",
    "jest": "^19.0.2",
    "jest-enzyme": "^2.1.2",
    "pouchdb-memory": "^6.0.0",
    "react-addons-test-utils": "^15.4.2",
    "react-scripts": "0.9.3"
  },
  "dependencies": {
    "jsonschema": "^1.1.1",
    "mobx": "^3.1.7",
    "mobx-utils": "^2.0.1",
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "shortid": "^2.2.6"
  },
  "scripts": {
    "flow": "flow",
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "description": "This project was bootstrapped with [Create React App](https://github.com/facebookincubator/create-react-app).",
  "main": "index.js",
  "author": "",
  "license": "SEE LICENSE IN LICENCE.md"
}
```

**Comment by ssured** [comment]
.babelrc:
```
{
  "presets": [
    "react-app",
    "es2015",
    "stage-1"
  ],
  "plugins": [
    "transform-decorators-legacy"
  ]
}
```

.eslintrc
```
{
  "ecmaFeatures": {
    "jsx": true,
    "modules": true
  },
  "env": {
    "browser": true,
    "node": true
  },
  "parser": "babel-eslint",
  "rules": {
    "quotes": [
      2,
      "single"
    ],
    "strict": [
      2,
      "never"
    ],
    "no-unused-vars": [
      2,
      {
        "vars": "local"
      }
    ],
    "react/jsx-uses-react": 2,
    "react/jsx-uses-vars": 2,
    "react/jsx-no-undef": 2,
    "react/react-in-jsx-scope": 2
  },
  "extends": [
    "plugin:flowtype/recommended"
  ],
  "plugins": [
    "react",
    "flowtype"
  ],
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  }
}
```

.jsconfig
```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "target": "ES6"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by ssured** [comment]
Maybe something with flow changed. I have a (private) clean project start based on create-react-app, added with my own preferences (like flow) which used to work but now when I clone this repo it does not work anymore. I'll share the repo with you, as it exposes the problem right when you checkout and yarn install.

**Comment by ssured** [comment]
I sent you an invite

**Comment by ArtemGovorov** [comment]
Thanks!
I have cloned the repo, ran `yarn`, start wallaby and everything was working for me. Then I updated my `yarn` and everything stopped working with the reported error. I'm looking into this, but just not to hold you off, you may delete node modules and run `npm install` instead of `yarn` and it should work for you.

**Comment by ssured** [comment]
Thanks, it's super cool you are diving into this. Nice to have a pointer into the problem. 

FWIW: for me there is no difference installing using NPM or yarn, both expose the problem. My versions are:
```
➜  create-react-app git:(master) npm -v
4.1.2
➜  create-react-app git:(master) yarn -V
0.21.3
```

**Comment by ArtemGovorov** [comment]
Hmm, interesting. Not sure why, but is working for me. Anyway, I think I found the reason. There are basically 2 different versions of jest are installed in the repo. `create-react-app` is shipped with v18 and you have `"jest": "^19.0.2",` as a dependency in the repo. As a result, mixed jest modules seem to confuse wallaby. While I'm looking into this you may try deleting node modules, deleting the v19 dependency, installing the dependencies, and trying to run.

**Comment by ssured** [comment]
I can confirm removing jest from package.json does solve the issue for me too. Cool, thanks for that!

Still it's weird this error started just yesterday. I was using this same jest configuration for quite some time

**Comment by ssured** [comment]
In my original repo the fix of removing `jest` from `package.json` works. I'll close this issue, but feel free to reopen if you need it for wallaby internal issue tracking. The cause of this issue is not solved AFAIK. Also I added a TLDR on the initial post to help others. Thanks for your help @ArtemGovorov!

**Comment by ArtemGovorov** [comment]
Thanks for summing it up for other. The issue is fixed and the fixed is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
