### ISSUE TITLE
Report Jest obsolete snapshots to the Failing Tests tab

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#1074]
### Issue description or question

```js
// trivial react example
describe("suite", () => {
  // change the test description and the snapshot will be updated
  it("test", () => {
    const tree = create(
      <Component/>,
    ).toJSON();

    expect(tree).toMatchSnapshot();
  });
});
```

There's an edge case where if you have the snapshot test implementation (below) and you change the test description, it'll generate extraneous snapshots that are no longer available. In order to get rid of them, you would have to run the test again. This can be replicated with any trivial test.

The desired outcome should be that only the relevant snapshot be added. Please let me know if there's any questions.

**Comment by ArtemGovorov** [comment]
This is how Jest works (even without wallaby):

![ws](https://cloud.githubusercontent.com/assets/979966/24132849/485719f2-0e44-11e7-986a-5b0edbbc1afb.gif)

Just like in Jest, you need an additional action to remove obsolete snapshots. Like [described in the article](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0#.xxt5kfpwz), in case of wallaby.js you may run the `Run file tests` action to update snapshots of the file (or the `Run project tests` action to update the snapshots in the whole project).

![ws](https://cloud.githubusercontent.com/assets/979966/24132951/fb4ad5a8-0e44-11e7-9bae-453a9ef28612.gif)


Hope it addresses your question.

**Comment by thomastnguyen91** [comment]
I totally forgot about that, but I guess it wasn't that noticeable because jest tells you when there are obsolete snapshots and it creates obsolete snapshots based on the number of snapshots that were updated. For wallaby tho, it updates the snapshot on every keystroke. So if I update the description of a test, it can create N snapshots for N keystrokes.

Is it possible for wallaby to notify the user if there are obsolete snapshots? Perhaps treat obsolete snapshots as an error?

**Comment by ArtemGovorov** [comment]
> Is it possible for wallaby to notify the user if there are obsolete snapshots?

Wallaby does redirect Jest output to the wallaby console, so it reports in a similar way that Jest  does.
![screen shot 2017-03-21 at 3 15 58 pm](https://cloud.githubusercontent.com/assets/979966/24133556/84011502-0e49-11e7-94d9-66013d09dced.png)

> Perhaps treat obsolete snapshots as an error?

Jest doesn't report it as a test run error, so I'm not sure why wallaby should?

**Comment by ArtemGovorov** [comment]
> and it creates obsolete snapshots based on the number of snapshots that were updated.

Jest actually creates snapshots just like wallaby, on every run (it's just as you've correctly mentioned - wallaby runs your tests more frequently). If you start Jest watch mode, edit the test name, hit save, edit the test name, hit save, etc., it'll create as many snapshots as many times you've hit save.

**Comment by thomastnguyen91** [comment]
You have a point there because Wallaby does log out all of Jest's output in its own console. 

The point I wanted to make though is that when Jest notifies that there are obsolete snapshots, you see it immediately along with the other information in its CLI. Jest, in its own way, "prompts" you to remove those snapshots to keep a healthy project. 

Wallaby does report the same information, but it reports it in a way that people don't really pay attention to (the Wallaby Console). For me, I would look at Failing Tests, gutter, and status icon to let me know if there's anything wrong with my tests. 

If I wanted to check if there are any obsolete snapshots, I would have to look at the snapshots directly, check the Wallaby Console, or run Jest in the CLI.

Do you think there's a possible enhancement that can be done regarding this?

**Comment by ArtemGovorov** [comment]
@thomastnguyen91 Thanks for your response. I see your point and agree that the information about obsolete snapshots would be convenient to have in the Failing Tests tab. Re-opening the issue as a feature request.

**Comment by ArtemGovorov** [comment]
@streamnsight Tests can be skipped for various reasons. Jest doesn't report them as failed, so doesn't Wallaby.

**Comment by ArtemGovorov** [comment]
@streamnsight Hmm, you are right, and something is wrong here. Wallaby should run the exact same number of tests as Jest, and it sounds like an issue that is different from the originally reported. There may be an issue with your wallaby config. Could you please create a sample repo where we could reproduce the issue and share it? We are happy to have a look.

**Comment by streamnsight** [comment]
@ArtemGovorov 

obsolete snapshots is one case where I've seen this discrepancy, but I see it even when this is not the case sometimes.
Still trying to figure out why.
Unfortunately I cannot share this private repo.
I will keep looking to see what could be the problem.
we do have long running tests, so maybe there is some timeout limit in Wallaby that is different from what Jest does?

**Comment by smcenlly** [comment]
Wallaby now provides details of obsolete snapshots in your test output window.
