### ISSUE TITLE
Does wallabyjs + kind:'electron' use the GPU?

### ISSUE THREAD

**Issue by arranbartish** [wallabyjs/public#1076]
### context 

I am using a debian VM on virtual box heavily. There are issues with the host display drivers and guest addition drivers that mean chome throws the following errors 

```
GL ERROR :GL_INVALID_VALUE : ScopedTextureBinder::dtor: <- error from previous GL command
```

This tends to crash the entire VM. I am also using **WebStorm + wallabyjs** heavily, however when I use wallabyjs + electron I get the same "chrome" error and my VM also crashes.

I've "fixed" chrome browser by changing the settings and unchecking "Use hardware acceleration when available". Unfortunately Wallabyjs+electron will still crash the VM 😭 so it doesn't seem to use the chrome settings. Is this understanding correct? 

```
ue, 21 Mar 2017 11:08:28 GMT wallaby:electronRunner Prepared sandbox [worker #0, session #50gvw]
Tue, 21 Mar 2017 11:08:28 GMT wallaby:electronRunner Prepared sandbox [worker #1, session #t6s5r]
Tue, 21 Mar 2017 11:08:28 GMT wallaby:workers Running tests in sandbox [worker #0, session #50gvw]
Tue, 21 Mar 2017 11:08:28 GMT wallaby:workers Running tests in sandbox [worker #1, session #t6s5r]
[6360:0321/070829:ERROR:buffer_manager.cc(438)] [.DisplayCompositor-0x3077ba4d2500]GL ERROR :GL_INVALID_ENUM : glBufferData: <- error from previous GL command
[6360:0321/070829:ERROR:texture_manager.cc(2971)] [.DisplayCompositor-0x3077ba4d1000]GL ERROR :GL_INVALID_ENUM : glTexImage2D: <- error from previous GL command
Tue, 21 Mar 2017 11:08:29 GMT wallaby:middleware Preparing to serve /home/arran/.WebStorm2017.1/system/wallaby/wallaby/tracer.js
Tue, 21 Mar 2017 11:08:29 GMT wallaby:middleware Serving /home/arran/.WebStorm2017.1/system/wallaby/wallaby/tracer.js from disk
Tue, 21 Mar 2017 11:08:29 GMT wallaby:middleware Preparing to serve /mocha@3.2.0/framework.js
```

### question

Is there a way to configure electron+chrome to use the cli parameter `--disable-gpu`? 

Ideally I would want to configure this just for my VM (or in the launcher) as people using a native windows box, mac, or with happily configured drivers should be able to take advantage of their GPU. 

Does this seem reasonable? Any other ideas?  

### Wallaby.js configuration file

https://github.com/arranbartish/angular-cli-seed/blob/3ec7055c4b67de77e2692374720e06d71b479e34/wallaby.js

### Code editor or IDE name and version

WebStorm 2017.1

### OS name and version

Linux Mint 18.1 (64-bit) on Oracle VirtualBox

**Comment by ArtemGovorov** [comment]
> Is there a way to configure electron+chrome to use the cli parameter --disable-gpu?

Yes, when wallaby starts the runner, you [may pass any required flags via the `env.params.runner` setting](https://wallabyjs.com/docs/config/runner.html).

```javascript
...
module.exports = function (wallaby) {

  return {
    ...
    env: {
      kind: 'electron',
      params: {
        runner: '--disable-gpu'
      }
    },
    ...
  };
};
```

**Comment by arranbartish** [comment]
Cool! Is there a way to use environment variables from the wallaby.js? 

It would be cool to make it configurable based on an environment parameter? From what I understand the section above would would turn off the gpu for anyone who runs it?

something like 
```
var electronParams = { runner: '--disable-gpu' };
...
module.exports = function (wallaby) {

  return {
    ...
    env: {
      kind: 'electron',
      params: (env.DISABLE_GPU)? electronParams : {}
    },
    ...
  };
};

```

Am I making sense?

**Comment by arranbartish** [comment]
By the way. The original answer completely stopped my VM from crashing. Amazing. Thank you!

**Comment by ArtemGovorov** [comment]
Sure, `wallaby.js` is just a node program, so you [may use process.env.DISABLE_GPU](https://nodejs.org/api/process.html#process_process_env) (the `DISABLE_GPU` environment var obviously has to be set somewhere).

**Comment by arranbartish** [comment]
Awesome. learning more and more. Thank you, 

For those that come after me. [This change set][commit] will pass parameters to electron conditionally if an environment variable is set. 

[commit]: https://github.com/arranbartish/angular-cli-seed/commit/6f9d69763708f8adf77deccf64b28bb3a6c03106 "Commit to turn off GPU"
