### ISSUE TITLE
Wallaby hangs when running jest tests with typescript

### ISSUE THREAD

**Issue by zubivan** [wallabyjs/public#1077]
### Issue description

Wallaby hangs after the first test run.

I'm using typescript with jest in my project and wallaby runs correctly for the first time, but as soon as you're starting to change your tests/code it almost immediately hangs. 

I created a sample project you guys can use to diagnose the issue => https://github.com/zubivan/wallaby-vscode-jest-issue

Steps to reproduce:
- `yarn` or `npm i`
- Open in VSCode
- Start wallaby
- Change tests in `/__test__/sample.spec.ts`, especially make it fail
- Wallaby hangs

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: './node_modules/**/*.*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.spec.ts*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.test.ts*', instrument: false, load: false, ignore: true },
            { pattern: './**/*.ts*', instrument: true, load: false, ignore: false },
            { pattern: './**/*.svg', instrument: true, load: false, ignore: false },
            { pattern: './**/*.scss', instrument: true, load: false, ignore: false },
            { pattern: './**/*.css', instrument: true, load: false, ignore: false },
            { pattern: './**/*.json', instrument: true, load: false, ignore: false },
            'package.json',
            'tsconfig.json'
        ],
        tests: [
            './**/*.spec.ts*',
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        setup: function () {
            const jestConfig = require("./package.json").jest;
            wallaby.testFramework.configure(jestConfig);
        },
        maxConsoleMessagesPerTest: 10000,
        slowTestThreshold: 10000,
        debug: true
    }
};
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 10 Pro (Build 14393.953)

### Wallaby logs

<details>
  <summary>Click to expand</summary>
​​​​​[Info]​​​​​ console.log:  PASS  ..\..\Users\izu\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.48\projects\ce02b3dcb0f0c072\instrumented\src\__test__\sample.spec.js
​​​​​[Info]​​​​​ console.log:   it should calculate
​​​​​[Info]​​​​​ console.log:     √ should calculate
​​​​​[Info]​​​​​ console.log:     √ should calculate 3
​​​​​[Info]​​​​​ console.log:     √ should calculate 2
​​​​​[Info]​​​​​ console.log: 
​​​​​[Info]​​​​​ console.log: Test Suites: 1 passed, 1 total
​​​​​[Info]​​​​​ Tests:       3 passed, 3 total
​​​​​[Info]​​​​​ Snapshots:   0 total
​​​​​[Info]​​​​​ Time:        0.116s
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:workers Run 3 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:workers Sandbox [ctcu4] is responsive, closing it
​​​​​[Info]​​​​​ Finished executing 3 affected test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:10 GMT wallaby:project Test run result processed and sent to IDE
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:fs File changed in editor: src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Returning previously cached file [4] from memory
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Preparing to process src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No compilers configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts changes saved, store ts: 1490109110576, change ts: 1490109553457
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Preparing to process src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processing compiled src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Instrumenting src/__test__/sample.spec.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Detected single test [should calculate 3] change
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #z039w]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #z039w]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #z039w]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Running tests in sandbox [worker #0, session #z039w]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:fs File changed in editor: src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Cancelling test run, cancel requester priority: 2, current run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run was cancelled
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Sandbox [z039w] is responsive, closing it
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run cancelled, re-queueing run data
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run data re-queued
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Returning previously cached file [4] from memory
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Preparing to process src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No compilers configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project File src/__test__/sample.spec.ts changes saved, store ts: 1490109110576, change ts: 1490109553676
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Preparing to process src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processing compiled src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Instrumenting src/__test__/sample.spec.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Detected single test [should calculate 3] change
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #l8bbj]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #l8bbj]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #l8bbj]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Running tests in sandbox [worker #0, session #l8bbj]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Loaded unknown number of test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Test executed: should calculate 3
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Run 1 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:workers Sandbox [l8bbj] is responsive, closing it
​​​​​[Info]​​​​​ Finished executing 1 affected test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:13 GMT wallaby:project Test run result processed and sent to IDE
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:fs File changed in editor: src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Returning previously cached file [4] from memory
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Preparing to process src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No compilers configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts changes saved, store ts: 1490109110576, change ts: 1490109554271
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Preparing to process src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Processing compiled src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Instrumenting src/__test__/sample.spec.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Detected single test [should calculate 3] change
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #ww7ka]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #ww7ka]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #ww7ka]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Running tests in sandbox [worker #0, session #ww7ka]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Loaded unknown number of test(s)
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:fs File changed in editor: src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Cancelling test run, cancel requester priority: 2, current run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run was cancelled
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Sandbox [ww7ka] is responsive, closing it
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run cancelled, re-queueing run data
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run data re-queued
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts changes are patches only: true
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Returning previously cached file [4] from memory
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Preparing to process src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No compilers configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts is not instrumented by core
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.ts
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project File src/__test__/sample.spec.ts changes saved, store ts: 1490109110576, change ts: 1490109554510
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Preparing to process src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Processing compiled src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Instrumenting src/__test__/sample.spec.js, via process pool: false
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Detected single test [should calculate 3] change
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project No preprocessors configured for src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Writing to disk and caching processed file src/__test__/sample.spec.js
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:project Test run started; run priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Starting test run, priority: 2
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #pewbm]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #pewbm]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #pewbm]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Running tests in sandbox [worker #0, session #pewbm]
​​​​​[Info]​​​​​ Tue, 21 Mar 2017 15:19:14 GMT wallaby:workers Loaded unknown number of test(s)
​​[Error] Some long running code has been detected: test "undefined" is taking more than 5000ms to execute.​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] Sandbox is responsive. The issue may have the asynchronous nature, like a missing callback.​​
</details>

**Comment by ArtemGovorov** [comment]
Thanks a lot for the repo. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by zubivan** [comment]
@ArtemGovorov That was fast, thanks, it seems to be fixing this issue! Tho I see quite a lot of different issues with running jest + typescript combination. Will report them separately. Cheers.

**Comment by ArtemGovorov** [comment]
@zubivan Awesome, thanks for checking. Sure, let us know about any other issues you hit, we do have a lot users running jest + typescript without any issues, so I'm confident we can make it work for you.
