### ISSUE TITLE
Fatal "out of memory" error

### ISSUE THREAD

**Issue by mhelvens** [wallabyjs/public#108]
I've been working on [my library](https://github.com/mhelvens/graph.js) with Wallaby running. I happen to be copying some unit tests (making changes in the copy), and Wallaby quits on me. The Wallaby Console says:

    FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

This is happening frequently, maybe when I'm changing lots of stuff in quick succession? Wallaby will be able to restart just fine, but can certainly crash again afterwards.

**Comment by ArtemGovorov** [comment]
So what's the best way to reproduce it? Should copying some test(s) and changing the copy multiple times in one spec file suffice?

**Comment by ArtemGovorov** [comment]
Also, did it start to happen recently, or you have been observing the issue for a while?

**Comment by mhelvens** [comment]
I've only noticed this today. But then, it's the first time I'm making systematic duplications of certain tests in quick succession, i.e., without having to pause and think.

Best way to reproduce... hard to say. It might involve all kinds of subtleties. But it's happened to me three times in the last two hours. I would propose that you prepare a version that dumps a lot of info to the console. I'd certainly be willing to run it, so I have something to give you the next time it happens.

**Comment by ArtemGovorov** [comment]
Ok, thanks, I'll try the same steps and if I can't reproduce it, we'll try some verbose logging.

**Comment by mhelvens** [comment]
Actually, I'm working slowly now, with about 405 tests passing and 4 tests failing, and it crashed again the same way. It's starting to look like a memory leak to me. Might be a recently introduced one, but it's also the first time I'm running it with over 400 tests.

**Comment by ArtemGovorov** [comment]
I think I have fixed the leak, try the latest version (core 1.0.44) and let me know if you see the error again.

**Comment by mhelvens** [comment]
Where can I download this version? WebStorm is not notifying me of a Wallaby update, and the version available from the website seems to be 1.0.15.

**Comment by ArtemGovorov** [comment]
Wallaby.js automatically updates its core, which is versioned separately from the plugin version. The core update (if available) is applied within 20 minutes after some wallaby.js restart or IDE restart, whichever happens first. You may see the current core version in the Wallaby Console when it starts.

**Comment by mhelvens** [comment]
Ah, I see. I'm running v1.0.45, and it hasn't crashed yet. So things are looking good!

PS: To be honest, I'm a bit worried about a plugin that silently updates itself. If test results change from one run to the next because you have fixed or introduced a bug, I would likely blame my own code and get lost in a fruitless search. I myself may now be prepared for something like that, but I'd much prefer the option to be notified of every update (or even to be asked).

Should I open up a separate issue?

**Comment by ArtemGovorov** [comment]
Fair enough. Yes, please go ahead and open up a separate issue.

**Comment by rusboy** [comment]
Hi, I'm observing same issue on core v1.0.76

**Comment by ArtemGovorov** [comment]
@rusboy Could you please share your wallaby config?

**Comment by IcodeNet** [comment]
if that helps I was getting the same issue after I added lowCoverageThreshold : 100
even though later I removed the setting wallaby was still using the cached folder 
I enabled the setting ==> debug:true
found the location of cache - deleted the folders restarted wallaby and it all worked.

**Comment by ArtemGovorov** [comment]
@IcodeNet Hmm, it shouldn't be related if you're getting the same issue. Could you please try adding the setting back and see if the issue starts to show up? Could you please also share your wallaby config file?

**Comment by dapullar** [comment]
Strangely enough this happens to me more often at the 400 test threshold as well, tried clearing cache but no help, my work machine seems to throw the OOM every few days and seems to persist until I restart. Any more insight on this issue?

v1.0.435
[wallaby config](https://gist.github.com/dapullar/e570ec34672c52b73ee0b4e218c702a2)

**Comment by ArtemGovorov** [comment]
@dapullar Thanks for sharing the config. Could you please also share your `package.json` file, node.js version and your editor/IDE version?

**Comment by ArtemGovorov** [comment]
@dapullar Also, could you please paste the exact error message that is displayed? 

One thing it's worth trying in your case is switching to [Electron/Chrome runner](https://wallabyjs.com/docs/integration/electron.html). Please try it to see if the issue disappears with the new runner.

**Comment by dapullar** [comment]
[package.json](https://gist.github.com/dapullar/6c59781ea110e6fd781b8f66d1fdc708)
+wallaby-webpack
+angular2-template-loader

node v7.6.0
vscode v1.13

Sure i'll test out the electron config and get back to you

**Comment by ArtemGovorov** [comment]
@dapullar Thanks! A quick question - how exactly does it crash? Is the error displayed in the Wallaby Console or VS Code is crashing?

**Comment by dapullar** [comment]
Woops, accidentally omitted, it's in the Wallaby Console, I'll let it run and edit this comment with the dump once its OOM.

**Comment by dapullar** [comment]
I just figured out the issue, it happens when I link projects together using `npm link`. This doesn't affect running jasmine directly though.

**Comment by ArtemGovorov** [comment]
@dapullar Could you please provide some more details about your setup: 

- How many other projects do you have linked?
- Do those projects have the similar link the project being tested?
- How did you find out that it is the issue (from what you said earlier it takes few days to get the OOM error), so perhaps there's an easy way we could reproduce it?

**Comment by dapullar** [comment]
- I may link up to 3 other projects
- Never linked circularly
- I recalled it had worked up until I had made the change

Due to versioning, I may also link a project that have version differences (testing future releases), as in the project may have a higher version of `rxjs` for example, which will show as warnings like `X class is not compatible with X class` but has never caused any real issues.

**Comment by ArtemGovorov** [comment]
@dapullar I can't yet reproduce the issue. Here's what I have tried:
- created 2 modules `module1` and `module2`, ran `npm link` in those modules' folders;
- ran `npm link module1` and `npm link module2` in the project's folder;
- started wallaby on the project (with your wallaby config) and had been changing a file with over 500 tests, the file also imports `module1` and `module2`.

While running wallaby on this test project I have been monitoring the memory usage (had also taken a few memory snapshots with forced GC runs), but everything seems to be working as expected (memory consumption doesn't grow).

Is there anything you can spot that I'm doing differently from your setup?

> I recalled it had worked up until I had made the change, once I unlinked, it worked like a charm

Just to make it clear - so after linking a module (a particular one?), and starting wallaby, the memory consumption immediately starts to quickly grow when you are changing tests/source code? And right after unlinking the module and starting wallaby it works as expected? Also, given that tests work for you without the link, what's the reason for linking the modules?

Would it be possible to create a sample repo demonstrating the issue? It doesn't have to be able to cause the error immediately, but if the memory consumption is quickly growing in the sample project, I'll be able to trace the leak.
