### ISSUE TITLE
Winston Loggin

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#1080]
### Issue description or question
I am a newbie to wallaby. i tried it about 1.5 years and could not get it to function so i am trying it out again. Seems to run MUCH better... but the logger.verbose statements that i have in my tests.... how do i get those to output either to the app site or to console?

aaron

**Comment by ArtemGovorov** [comment]
AFAIK, `winston` supports console transport, so you may just configure it to use the console for output in [the setup function](https://wallabyjs.com/docs/config/bootstrap.html) of you config and it should start showing the logs. If it doesn't, please create a small sample repo, happy to jump in and have a look.

**Comment by scriptsure** [comment]
@ArtemGovorov would mind showing me how to place that in the setup??

**Comment by ArtemGovorov** [comment]
@scriptsure Sure, I have created [this example branch for you](https://github.com/wallabyjs/wallaby-node-iojs-sample/blob/winston/wallaby.js#L14). With the logger configured like this, you should start seeing the logs in the line tests reports and in the wallaby app: 

![screen shot 2017-03-24 at 11 56 16 am](https://cloud.githubusercontent.com/assets/979966/24277538/6d0b532a-1089-11e7-9f00-70e513a476a4.png)

**Comment by scriptsure** [comment]
![image](https://cloud.githubusercontent.com/assets/798281/24312094/69a1689a-10ad-11e7-86bd-acd48627881e.png)

now i get that... i am including the logger in node side....

**Comment by ArtemGovorov** [comment]
Please create a small sample repo demonstrating the issue, happy to jump in and have a look.

**Comment by ArtemGovorov** [comment]
Or just fork and [update the sample](https://github.com/wallabyjs/wallaby-node-iojs-sample/blob/winston/wallaby.js#L14) I have created for you.

**Comment by scriptsure** [comment]
https://github.com/scriptsure/wallaby-node-iojs-sample/blob/master/lib/logger.js

so it looks like on  line 4 of the logger is the issue.. so if i have node running it takes the console... so it removes and re-adds winston...  if i delete the REMOVE then when i go to start up node and wallaby is running i get an error of course....  is there a way to have wallaby latch on to an already created instnce of winston?

**Comment by ArtemGovorov** [comment]
Sure, the `setup` function executes before any of your code, so you may just patch winston `add/remove` functions to not do anything (because the initialization is done in the `setup`). I have [sent you the pull request](https://github.com/scriptsure/wallaby-node-iojs-sample/pull/1).

**Comment by scriptsure** [comment]
works perfect... bought a new license... makes it a JOY to write tests...

**Comment by ArtemGovorov** [comment]
Awesome, thanks for your order!
