### ISSUE TITLE
Some long running code has been detected: test "undefined"

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#1083]
### Issue description or question

I'm getting the following error since Wallaby Core updated itself this morning:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.400
​​[Error] Some long running code has been detected: test "undefined" is taking more than 5000ms to execute.​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​
```

The only test I have at the moment is as follows:

```javascript
import React from 'react';
import { MemoryRouter } from 'react-router-dom';
import { shallow } from 'enzyme';

import Layout from '../layout';

const setup = () =>
{
  const wrapper = shallow((
    <MemoryRouter>
      <Layout />
    </MemoryRouter>
  ));

  return {
    wrapper: wrapper.dive().dive(), // Get the rendered layout
  };
};

describe('Layout', () =>
{
  test('render', () =>
  {
    const { wrapper } = setup();

    expect(wrapper).toMatchSnapshot();
  });
});
```

It's a relatively simple one, and was working fine until the update occurred.

Any ideas? Thanks.

### Wallaby.js configuration file

```javascript
module.exports = function wallabyConfig(wallaby)
{
  return {
    files: [
      'scripts/**/*.js',
      'scripts/**/*.jsx',
      '!scripts/**/__tests__/*.js',
      '!scripts/**/__tests__/*.jsx',
    ],

    tests: [
      'scripts/**/__tests__/*.js',
      'scripts/**/__tests__/*.jsx',
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.jsx': wallaby.compilers.babel(),
    },

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 10

**Comment by dylanparry** [comment]
It appears to be related to snapshots. If I replace the test with the even simpler:

```javascript
test('test', () => {
  expect(true).toBe(true);
});
```

Then the test passes and there's no report of tests taking too long.

**Comment by ArtemGovorov** [comment]
We didn't change anything in jest integration is the last couple of versions, so it sounds like a coincidence. 

I have [created this branch](https://github.com/wallabyjs/wallaby-jest-snapshots/tree/wallaby-1083) with [your test](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/wallaby-1083/scripts/__tests__/component.spec.js) and it's working for me. Could you please try the sample and if it's working try to find what's different between it and your environment?

**Comment by dylanparry** [comment]
Hi. I've tried running your samples here, but they're not working for me either. I get the same message about tests taking too long, but can still run them via CLI without any issues.

Is there a debug log or anything I can paste here to help us figure out what's happening?

**Comment by ArtemGovorov** [comment]
Is the [master branch](https://github.com/wallabyjs/wallaby-jest-snapshots) of the sample working for you?

**Comment by ArtemGovorov** [comment]
> Is there a debug log or anything I can paste here to help us figure out what's happening?

Yes, please [add the `debug: true` to you config and paste the output from the wallaby console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by dylanparry** [comment]
The master branch does appear to work. I then added the `debug: true` setting to the config, and bizarrely my code is now working fine again—I'd changed nothing else, so no idea why it's suddenly working again.

Thanks for your help. It would be great to figure out why this happened, but I suspect we'll never know.

**Comment by ArtemGovorov** [comment]
Weird indeed, perhaps just some jest/wallaby cache glitch. I have noticed one thing though, your config doesn't have `.snap` files in the `files` list, you need to put it there if you'd like 2-way sync with your repo snapshots ([like here](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js#L5), but `'scripts/**/*.snap'`).

**Comment by dylanparry** [comment]
Ah, thanks for that. Didn't realise I needed to include those files too.
