### ISSUE TITLE
Any way to clear Wallaby cache?

### ISSUE THREAD

**Issue by MicahZoltu** [wallabyjs/public#1086]
### Issue description or question
I'm using Wallaby with TypeScript and every now and then (fairly rare) Wallaby seems to end up with an old version of the compiled TypeScript output cached somewhere.  When this happens, my tests will fail and the only solution I have found is to go through all of my files and `touch` them each once until I find the file that is incorrectly cached (sometimes the error gives a hint as to where to start).  Restarting VSCode does not appear to resolve this issue, nor does starting/stopping Wallaby.  Re-compiling all of my code with `tsc` does not resolve the issue.  The way I usually narrow the problem down to this is by running the tests manually (usually to debug) via my test runner does not show the problem.

Is there a way I can tell Wallaby to wipe out its internal cache and recompile all of my TypeScript into JavaScript?  Unfortunately I don't know how to reproduce this, it has happened about 2 times in the last ~40 hours of work and it is unclear what triggers it.

### Wallaby.js configuration file

```javascript
{
  "files": [
    "source/**/*.ts",
    "tests/helpers.ts"
  ],
  "tests": [
    "tests/index.ts",
    "tests/es5.js"
  ],
  "env": {
    "type": "node"
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
To [reset the cache](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) you may touch the wallaby config file and restart it. 

Please also let us know if you manage to reproduce and isolate the issue somehow so we could have a look.

**Comment by smcenlly** [comment]
@kevinbeal - are you using Jest? If so, `npx jest --clearCache` will clear the cache. Are you having a specific issue?

**Comment by kevinbeal** [comment]
I’ll give that a shot. 

> @kevinbeal - Are you having a specific issue?

I get “undefined index 0” at seemingly random locations like imports on a regular basis.

**Comment by kevinbeal** [comment]
> @kevinbeal - are you using Jest? If so, `npx jest --clearCache` will clear the cache

It appears to work perfectly.

It seems like I bump into the "undefined index 0" issue when I use and then remove the `only` from `it.only`s, though not consistently.

**Comment by lprichar** [comment]
This seems to happen to me pretty frequently, maybe once a week, and it's been very frustrating.  VS Code's "Reset Wallaby Cache" never helps.  "npx jest --clearCache" followed by "Reset Wallaby Cache" did fix it.  I wish I could be more help in providing repro steps, but maybe as an inelegant but effective solution you could run "npx jest --clearCache" in the "Reset Wallaby Cache" command.

**Comment by smcenlly** [comment]
@lprichar - could you please [create a new issue](https://github.com/wallabyjs/public/issues/new) and share your diagnostics report (both when you don't have the problem, and when you do have them problem)?
