### ISSUE TITLE
Problems with Database Connections

### ISSUE THREAD

**Issue by Knaackee** [wallabyjs/public#1088]
I am using Wallaby with Jest and i love it but recently i have the following problem.

Iam using postgresql as my primary database and wrote some unit tests for some database operations such as seeding etc.

After getting the connection and performing all my tests i close the connection. But for some reason the connection is still open (i can see this in the database admin tool). So more and more connections are created and never closed which leads of course to a "too much connections" problem.

Ive tried to close the connection in the "afterEach" method as well as in a try finally block, with no luck.

If i run the same tests a dozen times using the jest cli and dont have this problem.

What is correct way to handle and debug this?

**Comment by Knaackee** [comment]
Thanks, first i tried to set `workers: { recycle: true }` which worked.
After that ive investigated why the connection are not closed and found the problem.

Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by Knaackee** [comment]
Another question related to this is...

Imagine i write a test and wallabyjs executes as soon as possible. So the test is often "red" until finished. The problem here was that i was not able to close the connection in case of a failure.
It seemed that "finally" or catch are not called. Is that right and how to handle this ?

**Comment by ArtemGovorov** [comment]
> It seemed that "finally" or catch are not called.

It's not possible under the normal circumstances (or continuously running tests). If wallaby has started executing some code block, it'll finish executing it. So if wallaby enters say a `try` block, it'll hit the `catch` block if there's an error and will always hit the `finally` block. 

> (release resources) ?

The best way is to use `afterEach`, alternatively you may use [`teardown` function](https://wallabyjs.com/docs/config/bootstrap.html#teardown-function).

**Comment by Knaackee** [comment]
Thanks!
