### ISSUE TITLE
The issue with bundling typescript by webpack from node_modules. 

### ISSUE THREAD

**Issue by risonipli** [wallabyjs/public#1090]
### Issue description or question
Hi,

we're building bunch of private npm packages. Some pure typescript, some mix of typescript & js. All these packages we're bundling with webpack in our projects.
And it is not clear for me how properly configure wallaby for such cases. It fails while bundling, I think:
```
​​Error: Cannot find module "./src/utils-user.module"​​
​​at http://localhost:58223/____wallaby-bundle.js?1490880679143&wallabyFileId=bundle:18​​
​​Error: Cannot find module "./src/utils-user.module"​​
  at ​src/my-module.spec.ts:2​
​​Module not found: Error: Can't resolve './src/utils-user.module'
```
 Please take a look at https://github.com/risonipli/wallaby-webpack-typescript-issue where I reproduced the issue. 'postinstall.sh' will copy dummy modules 'utils' & 'utils_user' to node_modules.
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'src/**/*.spec.js'
    ]
});

module.exports = function () {
    return {
        debug: true,
        files: [
            { pattern: 'src/**/*.js', load: false },
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'node_modules/utils/package.json', load: false },
            { pattern: 'node_modules/utils_user/package.json', load: false },
            { pattern: 'node_modules/utils/**/*.ts', load: false },
            { pattern: 'node_modules/utils_user/**/*.ts', load: false },

            { pattern: 'src/**/*.spec.ts', ignore: true }
        ],

        tests: [
            { pattern: 'src/**/*.spec.ts', load: false },
        ],

        testFramework: 'jasmine',
        preprocessors: {
            '**/*.json': function (file) {
                return file.content.replace('index.ts', 'index.js');
            }
        },
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};


```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

OSX 10.12.3

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

> All these packages we're bundling with webpack in our projects

Could you please share your webpack config?

**Comment by ArtemGovorov** [comment]
Actually, I just noticed the issue.

You're using wallaby to compile the node modules by including them into the `files` list, and wallaby copies all the `files` over to its cache. So you just need to let webpack know about this new `modules` location by adding it to `resolve.modules`. I have sent you [the pull request to make it work](https://github.com/risonipli/wallaby-webpack-typescript-issue/pull/2):

```javascript
    var webpackPostprocessor = wallabyWebpack({
        resolve: {
          modules: [path.join(wallaby.projectCacheDir, 'node_modules'), 'node_modules']
        }
    });
```
