### ISSUE TITLE
Help needed: Angular-Cli 1.0.0 / Ng4.0.1 - Multiple "Cannot find module" errors

### ISSUE THREAD

**Issue by OClement** [wallabyjs/public#1091]
### Issue description or question
Using Angular-Cli 1.0.0, Angular 4.0.1
Wallaby config copied from https://github.com/wallabyjs/ngCliWebpackSample (./wallaby.js, ./wallabyTest.js, package.json versions)

When running, it will sometimes be able to run a few tests (anywhere between 1 to 12, out of 100+), but reports a bunch of errors (Karma runs fine) : 
```
Uncaught Error: Cannot find module '497'
at http://localhost:52365/wallaby-webpack.js?1490908130945:1

Uncaught Error: Cannot find module "fs"
at http://localhost:52365/____wallaby-bundle.js?1490908131591&wallabyFileId=bundle:79395

Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/glob'ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/glob'

Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/jasmine-core/lib'ModuleNotFoundError: 
Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/jasmine-core/lib'

Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/fs.realpath'ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/fs.realpath'

```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

IntelliJ IDEA 2017.1 (had same  issue with 2016.x)

### OS name and version

OSX Sierra

Not sure where to look :/
Thanks for your help

**Comment by ArtemGovorov** [comment]
> `Module not found: Error: Can't resolve 'fs' in '~/Documents/projects/<redacted>/frontend/node_modules/glob'`

Something  in your app (or one of the the modules you're using) is trying to import/require `glob` module that is using node's `fs` module. Clearly this will not work in browser, hence the error.

> Karma runs fine

I suspect your webpack configuration may be different for wallaby and karma, perhaps webpack config that karma is using mocks `fs`? Could you please share your webpack config that karma is using?

**Comment by OClement** [comment]
Thanks for the reply
I tried digging a bit more and still couldn't find what could try to load the glob module

We are using @angular/cli config, so we did not modify the webpack config ourselves;
I 'ejected' the project nonetheless to get to the actual webpack config (did not specify any options)
Here's the content of `webpack.js` : https://pastebin.com/i6Mdg3Ax that's generated

If I try to run wallaby on the ejected project, I get the same result

Looking at the generated file that throws the error (served by wallaby), I can indeed see the glob / globSync / Minimatch modules in there, but can't quite figure out who tries to use them... :/

**Comment by OClement** [comment]
Note that when building the project (for prod for instance), I cannot find those modules referenced anywhere in the generated packages

**Comment by ArtemGovorov** [comment]
I don't know what exactly, but something in your project (or its modules) is definitely importing the `glob` module. You may try cloning and running wallaby on the https://github.com/wallabyjs/ngCliWebpackSample sample, there's no issue there.

Looking into your ejected webpack config, it actually mocks the node `fs` module. Try doing the same in your wallaby config:

```javascript
var webpackPostprocessor = wallabyWebpack({
  ...
  "node": {
    "fs": "empty",
    "global": true,
    "crypto": "empty",
    "tls": "empty",
    "net": "empty",
    "process": true,
    "module": false,
    "clearImmediate": false,
    "setImmediate": false
  }
});
```

**Comment by OClement** [comment]
Ok, so adding this config did "fix" the `fs` module issue (I'll see later why this is being loaded)

Now I still have a few of these `Cannot find module '<number>' at http://localhost:60878/wallaby-webpack.js?1490976463764:1` errors

---

And I do experience a very weird behaviour around this; Sorry in advance for the long post, it is going to be hard to make it comprehensive unfortunately:

On the first run, the output window gives me

4 mentions of `Uncaught Error: Cannot find module '497'
at http://localhost:61206/wallaby-webpack.js?1490976702244:1`

2 failing tests, 11 passing (out of 160 tests, all passing in Karma)

It then displays those two failing tests with the reasons for each  of them being the same uncaught error cannot find module 497

I then go to that failing spec file, xit or comment out and back the failing test, and then Wallaby tells me I have only 1 failing test and 12 passing. I can do the same with the remaining failing test and it will be "happy" saying "all 13 tests are passing"

Now, if I xit those two same test and restart Wallaby completely:

The output gives me 5 mentions of `Cannot find module...`
And 1 failing test, 10 passing
(the 1 failing test is a new one)

I can xit/comment it out and then back and then it will think all is good again

If I leave it xitted, and restart wallaby, same scenario occurs;
1 new failing test, 9 passing

and so on so forth, until I have xitted all "failing tests". When I restart wallaby at that point, I then get 6 mentions of `cannot find module 497`, but no reports about any passing or failing tests, since all loaded tests have been skipped.

Soooo.... help? I am really at a loss here :S
Again, million thanks for your support!

**Comment by ArtemGovorov** [comment]
It looks like there's some global error (`cannot find module 497`), it may be an issue bundling/loading one of the modules you're using (it may be also somehow related to the `fs` issue "fixed" by mocking the module).

We need to find out what module is causing the issue.
Does this sample work for you: https://github.com/wallabyjs/ngCliWebpackSample as is?
If so, try changing your `tests` pattern to only include the test file that is failing when you start wallaby. If it's still failing, please try to isolate the issue by creating a sample repo (removing stuff while restarting to make sure it is still broken). I suspect you'll be able to reproduce it and end up having a dummy test file importing a dummy source file importing few modules. Once you are able to share it, I'll jump in to bee what's going on. Alternatively, if you could share the repo where I could reproduce the issue, I'm also happy to have a look and to try to find the problematic module myself.

**Comment by OClement** [comment]
You're most probably right indeed

I already tried the ngCliWebpackSample, and it worked perfectly.

I'll use those guidelines to try and isolate the issue further on Monday, and will report back when I find more relevant informations.

Thanks for your help again
I feel like I'm repeating myself a lot but i can't see otherwise how I can make it up to that incredible support you're offering :P

**Comment by OClement** [comment]
At last, issue solved

So it looks like we had 2 files with pattern *.spec.ts that were not actually spec files
They were used as test utils (mocks and the like) and Wallaby didn't like them at all
Not sure how the actual error message relates to this, but this is definitely a lessen learned!

Cheers!

**Comment by ArtemGovorov** [comment]
Awesome! Thanks for the update. Yes, wallaby does have [this important requirement](https://wallabyjs.com/docs/config/files.html#tests), and it's hard to diagnose at times. Will have a look how we can improve the error reporting in cases like this one.
