### ISSUE TITLE
Better instructions on how to setup mocha options.

### ISSUE THREAD

**Issue by MicahZoltu** [wallabyjs/public#1092]
### Issue description or question
I am using Mocha and have a `mocha.opts` file.  It appears that wallaby doesn't read/use this file so I need to reproduce the configuration it contains in the wallaby.json.  However, I am unable to find any documentation on how to do this.

Please improve documentation around configuring test runners.

### Wallaby.json configuration file

```javascript
{
    "files": [
        "src/**/*.js",
        "src/**/*.json"
    ],
    "tests": [
        "test/**/*.js",
        "!test/sync-node-only.js"
    ],
    "testFramework": "mocha",
    "env": {
        "type": "node"
    },
    "workers": {
        "initial": 1,
        "regular": 1
    }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Some of the scenarios are covered in our docs: [--require hooks](https://wallabyjs.com/docs/integration/node.html#mocha---require-equivalent), [`testFramework` access](https://wallabyjs.com/docs/config/bootstrap.html) (mocha object) from the `setup` function to do anything that mocha API support.

If you share your mocha.opts file, I'm happy to provide more details to address specific options and how to configure them.

**Comment by MicahZoltu** [comment]
I read those pages, but all they say is
> wallaby.testFramework is jasmine/QUnit/mocha object

What exactly is a `mocha object`?  I looked at the mocha website and their tutorials all describe configuring mocha via CLI options or `mocha.opts` file.  Is there some other way of configuring mocha that mocha supports?  If so, a link (in the wallaby docs) to that would be very helpful since mocha doesn't seem to advertise this other method very well.  If the mocha object is some custom Wallaby object, then links to documentation on how to translate between mocha.opts or CLI parameters would be valuable.

My specific issue is needing to set the test timeout to be higher than the default, as a couple of my tests take ~2.5 seconds to complete and the default timeout is 2 seconds.  More generally, it would be nice if there was a way to get an answer to this class of question (how to configure test runner) without having to file an issue.  😄

**Comment by ArtemGovorov** [comment]
Mocha object is [this one](https://mochajs.org/#browser-configuration). It is only described for browser, but wallaby exposes it for node as well, so you can do the same, and set any of [these options](https://github.com/mochajs/mocha/blob/b4ebabd1b76c02cbadd544544fb4b171a84ea698/lib/mocha.js#L61) via the mocha object function calls.

> would be very helpful since mocha doesn't seem to advertise this other method very well

Fair enough, I [have added the docs section](https://wallabyjs.com/docs/integration/node.html#mochaopts), with your specific scenario as an example.

**Comment by MicahZoltu** [comment]
Thanks!  I didn't see it because I was ignoring "browser configuration" as I am running my tests in node.  The link in the docs should help future users find correct documentation.
