### ISSUE TITLE
Jest 19 doesn't work with wallaby

### ISSUE THREAD

**Issue by khoomeister** [wallabyjs/public#1093]
### Issue description or question

If you open VSCode in the web-dep folder for this [SHA](https://github.com/khoomeister/ts-templates/commit/0cdf1c563402a93c0df1e4969d77b50bda74ec14), tests don't execute.

![image](https://cloud.githubusercontent.com/assets/681288/24532274/20b7619a-1574-11e7-9de6-dd019a23a4e1.png)

On the [prior SHA](https://github.com/khoomeister/ts-templates/commit/d6747c4a17bb4f16cb997232751941c92172f731) (jest 18), they run fine.

![image](https://cloud.githubusercontent.com/assets/681288/24532305/53587cc4-1574-11e7-8379-ab89286b0481.png)

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      'lib/**/*.ts*'
    ],
    tests: [
      'test/**/*spec.ts*'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Looks like your `tests` pattern is too greedy - it includes your snapshot files as well. Wallaby requires [only files with actual tests to be in the `tests`](https://wallabyjs.com/docs/config/files.html#tests) list, so you need to adjust your `tests` pattern and move `.snap` files to the `files` list.

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      'lib/**/*.ts*',
      'test/**/*.snap'
    ],
    tests: [
      'test/**/*spec.ts?(x)'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest'
  }
}
```

**Comment by khoomeister** [comment]
@ArtemGovorov thx!

I googled wallaby.js wildcard, but couldn't find much on wallaby's wildcard patterns.  Is there any doco on it anywhere I can look?

**Comment by khoomeister** [comment]
Ah OK I see it now (glob module patterns)

**Comment by ArtemGovorov** [comment]
Yep, wallaby is using [minimatch](https://github.com/isaacs/minimatch) behind the scenes.

**Comment by mindjuice** [comment]
I'm wondering if I have a similar issue with Jest `19.2.2` (although I'm not using snapshots).  If my `wallaby.conf.js` file contains specific files, as show below, then the tests run and pass (green boxes):

```
module.exports = () => {
  return {
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },

    files: [
      'src/middleware/utils.ts',
    ],
    tests: [
      'src/middleware/__tests__/utils_tests.ts',
    ],
    debug: true,
  }
}
```

But if I switch to wildcards as shown below, I get the grey boxes instead of green as shown in the OP's image above.

```
module.exports = () => {
  return {
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },

    files: [
      'src/middleware/*.ts',
    ],
    tests: [
      'src/middleware/__tests__/*_tests.ts',
    ],
    debug: true,
  }
}
```

If I check wallaby app, I see that it does match all 5 source files in the `src/middleware/` folder, and all 4 test files in the `src/middleware/__tests__` folder, but somehow no tests are run from any of them (they do all have tests).

Any idea?

**Comment by ArtemGovorov** [comment]
@mindjuice Try this:

```javascript
module.exports = () => {
  return {
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },

    files: [
      'src/middleware/*.ts',
      '!src/middleware/__tests__/*_tests.ts'
    ],
    tests: [
      'src/middleware/__tests__/*_tests.ts',
    ],
    debug: true,
  }
}
```

**Comment by mindjuice** [comment]
It still has grey boxes in margin for all files and tests.

**Comment by mindjuice** [comment]
Actually it's a bit odd.  Even when listing out some out the files specifically, not all of the tests get run initially.  Some files still show grey boxes.  But if I go to one of these test files and make any change (e.g., type a space), then the tests run and populate in wallaby app.  I have to manually walk through all the test files that didn't run and run them by making a change.

**Comment by ArtemGovorov** [comment]
@mindjuice It's pretty odd indeed. Could you please share a sample project demonstrating the issue? More than happy to jump in and have a look into what's going on.

**Comment by mindjuice** [comment]
So oddly after trying to pare down my project to something that failed that I could send you, I found that it started working.  I did restart VSCode somewhere in the middle there so perhaps something was corrupt.  The file path globs are working as expected now too.

I found a slightly different minor issue though while working through this.  I'll submit a separate issue for it.
