### ISSUE TITLE
How do you run electron/jasmine tests on CI?

### ISSUE THREAD

**Issue by khoomeister** [wallabyjs/public#1094]
I'm trying to create a CI test runner for electron + jasmine as per [this example config file](https://github.com/wallabyjs/wallaby-webpack-electron/blob/feb7e6e4f11cb70b111722487b8b060b9a7f7732/wallaby.js).  Is this wallaby secret sauce or is there an open source test runner that does something similar?

I'm using karma to do CI atm but I'm very sure since both are quite different platforms, some subtle incompatibility bug is going to bite in the future and waste tons of time.  I might as well try to figure this out upfront and avoid the pain later!

**Comment by ArtemGovorov** [comment]
> How do you run electron/jasmine tests on CI?

Wallaby [doesn't yet support running on CI servers](https://github.com/wallabyjs/public/issues/72). 

> Is this wallaby secret sauce or is there an open source test runner that does something similar?

Not really, we just launch electron and use it pretty much like karma uses browsers.
Karma [has this launcher](https://www.npmjs.com/package/karma-electron-launcher), that is doing the similar job.

Hope it answers your question.

**Comment by khoomeister** [comment]
thx @ArtemGovorov!
