### ISSUE TITLE
Tunnelling the Wallaby App report page to be accessible from outside

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1095]
Hello,

I tried tunnelling http://localhost:51245 with [ngrok](https://ngrok.com) to give my client/colleague an overview of the progress I'm making (±500 tests passing out of 650).

The web socket is configured to connect to localhost so it didn't work...

Do you think, there's a way to hack together a solution so that my client can access the Wallaby reports page from the outside?

**Comment by ArtemGovorov** [comment]
Hello, 

The websocket needs to connect to localhost (locally running wallaby core spawned by your editor), so if ngrok doesn't work this way, then I don't think it is possible to make it work. At least it was never designed to be exposed anywhere outside the local machine.

**Comment by bfulop** [comment]
AFAIK ngrok will tunnel one local port to a public address, but if the page tries to access `localhost`, it won't be tunnelled. 

Maybe one day we could have a configurable variable where we could replace localhost with a custom address? Not a big priority, just "_nice to have_" feature...

**Comment by ArtemGovorov** [comment]
> if the page tries to access localhost, it won't be tunnelled
> Maybe one day we could have a configurable variable where we could replace localhost

Perhaps I misunderstand something, but I'm not quite sure how it's going to work. Wallaby core runs locally, how can one replace the local address with some custom address? Maybe you could build a prototype of a web app hosted on one port, connecting to a websocket server hosted in the same machine on a different port, and everything wired up with ngrok?

**Comment by bfulop** [comment]
> Maybe you could build a prototype of a web app hosted on one port, connecting to a websocket server hosted in the same machine on a different port, and everything wired up with grok?

Yes, this is the idea, so that instead of websockets connecting to `localhost` it would connect to an ngrok address on port `80`. 

I don't have enough experience with websockets to know that it's at all possible. I will try to create a test setup as you described and tell you how it went. For the time being I close this issue...
