### ISSUE TITLE
Activity indicator doesn't always spin, instead showing pre-change status

### ISSUE THREAD

**Issue by mhelvens** [wallabyjs/public#1096]
### Issue description or question

I've actually always experienced this problem with Wallaby, but somehow never thought to report it as a bug. When I make changes in a source-file in WebStorm, Wallaby starts to rerun the relevant tests. And if I make changes while Wallaby is still running, it (presumably) stops and reruns again. This would happen a lot if I'm in the process of typing code.

But now and then, unpredictably, Wallaby will _not_ 'stop-and-rerun' tests. I notice this most often when I make a change and immediately save the file (Ctrl+S is a reflex-action for me). Wallaby will just go back to displaying the previous status report. When it happens, I need to press the spacebar or something; anything to make a change that triggers Wallaby again.

Since this has always been the case for me, it doesn't seem useful to provide specific versions or configuration files. Let me first ask: Is this a known problem? If not, what extra information could I provide to help diagnose it?

### Code editor or IDE

WebStorm

### OS name

Linux

_**See comment below for update**_

**Comment by ArtemGovorov** [comment]
> Let me first ask: Is this a known problem?

No, we haven't seen it before, neither have got any reports about it.

> If not, what extra information could I provide to help diagnose it?

How frequently does it show up? 
Is it hard to reproduce? 
Are you running tests in browser environment or in node environment?
I have tried these steps a few times:
- make a change,
- immediately save the file,

but couldn't catch it yet. Is there anything else I'm missing? 
When wallaby works ok, approx how long does it take from the change to the updated result in IDE?

**Comment by mhelvens** [comment]
I tried to isolate the problem using a smaller set of tests, which made me realize what's going on. Wallaby does rerun the tests, but the activity indicator doesn't always spin, instead showing the last status before the change. With my normal test-suites that could mean showing the wrong status for minutes at a time.

Check out this screen-cast: https://youtu.be/G0Pa_mDwbiw

**Comment by ArtemGovorov** [comment]
Thanks for the video and for the update. Tye issue is fixed and the fix is published in plugin v1.0.86.
