### ISSUE TITLE
Takes a lot of CPU on VSCode on Mac

### ISSUE THREAD

**Issue by Knaackee** [wallabyjs/public#1097]
I am using wallabyjs on vscode on my macbook with typescript and jest.
Ive noticed that it takes a lot of cpu and drains the battery. The fan is running all the time.
Is there something i can try to fix this ? 

Here is my config. 

 ```
module.exports = function (wallaby) {
  process.env.NODE_ENV = 'testing';

 return {
    files: [
      '**/*.ts',
      '**/knexfile.js',
      '**/migrations/*.js',
      '**/seeds/*.js',
      '**/*.tsx',
      '**/*.json',
      '**/*.png',
      '**/**.handlebars',
      '**/*.ico',
      '!**/*spec.ts',
      '!**/*test.ts',
      '!**/*spec.tsx',
      '!**/*test.tsx',
      '!**/node_modules',
      '!**/bower_components'
    ],

    tests: [
      '**/*spec.ts',
      '**/*test.ts',
      '**/*spec.tsx',
      '**/*test.tsx',      
      '!node_modules/**/*.*',
      '!bower_components/**/*.*'
    ],

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'React'
      })
    },    

    testFramework: 'jest',

    debug: false,

    setup: function () {
      wallaby.testFramework.configure(require('./package.json').jest);
    }

  };
};
```

**Comment by ArtemGovorov** [comment]
Wallaby itself doesn't consume much CPU, it's pretty much just passing your files straight to jest, and it's where I suspect the most of the time is spent - in jest running your tests, and obviously we can't change it much from the wallaby side. 

Having said that, there are a couple of things I may suggest adjusting that may help:
- first, I'd get rid of these kind of patterns: `**/*.ts` and try to do `src/**/*.ts`. The reason for the suggested change is that it allows file watcher to watch a specific folder (`src`), rather that to watch your root folder and later on spend CPU on filtering events from excluded patterns.
- second, by default wallaby makes jest to run tests very frequently. There's the [`delays` setting](https://wallabyjs.com/docs/config/overview.html#delays-setting) that allows to control the frequency. You may try setting it to few seconds: `delays: {run: 3000}` to see how much it helps, and tune it after that.

**Comment by Knaackee** [comment]
I had something similar without wallaby before. What helps was to exclude the node_modules from vscode so that the file watcher does not check this big folder all the time.
Is it possible that at the moment wallaby observes the whole project folder and not only the folders specified in the "files" section in the wallaby.js config file?

**Comment by ArtemGovorov** [comment]
Wallaby is using the most popular watcher in node land [`chokidar`](https://github.com/paulmillr/chokidar) internally. AFAIR, VS Code is also using it (or maybe a fork of it). Wallaby is just passing the patterns to it, as well as the patterns to ignore. I don't know the internals of `chokidar`, but have a suspicion that if you pass: `**/*.ts` and `!**/node_modules`, then the watcher will not scan your `**` to find out all the nested `node_modules` satisfying your exclusion pattern to only watch non-excluded ones. I'd rather expect it to watch the root, and then later on to filter fs events based on your exclusion patterns. If you however explicitly specify `src/**/*.ts`, then the watcher has no reason to watch the root folder and can only watch the `src` folder. Does it make sense?

**Comment by Knaackee** [comment]
Yes it does. This helps a lot. Thx!
