### ISSUE TITLE
Setting NODE_PATH from wallaby.js config

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#110]
My application is written on ES6 and every file uses fully-qualified imports starting from the project root (e.g. `import Button from 'common/Button'` can be used from any file). To achieve that, you need to set NODE_PATH environment variable to the application root (`/app` in my case).

Since Wallaby.js uses IDE's cache folder to store the project, it's unclear how to refer to it from `env.params.env` configuration object to set NODE_PATH variable properly. Could you please explain how to do that?

**Comment by ArtemGovorov** [comment]
If I correctly understand what's required, you may use [`bootstrap` function](https://github.com/wallabyjs/public#bootstrap-setting) to set the variable to be wallaby cache folder:
```
bootstrap: function (wallaby) {
   process.env.NODE_PATH = wallaby.projectCacheDir;
}
```

Please let me know if it answers your question.

**Comment by endragor** [comment]
That doesn't work for me - I'm still getting `Cannot find module` errors. Most probably node reads contents of that variable on start, so runtime changes do not affect the behaviour of imports. Is there a way to set that variable before node is launched?

**Comment by ArtemGovorov** [comment]
Could you please share a sample repo with your wallaby config and a couple of files, I'll have a look what can be done?

**Comment by endragor** [comment]
Forked your Jest example and modified it to use absolute imports here: https://github.com/endragor/wallaby-jest-sample
You can see that `npm run test` works fine for the project, but Wallaby throws `Cannot find module 'sum' from ...` error.

**Comment by ArtemGovorov** [comment]
Thanks for the sample, it helped and I have fixed a bug (I was overwriting `NODE_PATH` in Jest initializer). Now `bootstrap` function like this should work for your structure:
```
    bootstrap: function (wallaby) {
      process.env.NODE_PATH = require('path').join(wallaby.projectCacheDir, 'app');
    }
```
Let me know if it helps.

**Comment by endragor** [comment]
Imports work good now. Thanks for the quick replies and fix!

**Comment by inyono** [comment]
On node v2.4.6, I needed the following to make it work:
```.js
bootstrap: function (wallaby) {
  process.env.NODE_PATH = wallaby.projectCacheDir
  require('module').Module._initPaths()
}
```
see also https://gist.github.com/branneman/8048520

**Comment by ArtemGovorov** [comment]
@inyono Cool, thanks for the note.

**Comment by ArtemGovorov** [comment]
Since Jest 0.9.2, the approach with setting the `NODE_PATH` needs to be changed because jest now executes and caches some stuff before the `bootstrap` function.

The recommended way now is:

```javascript
module.exports = function (wallaby) {
  return {
    ...
    env: {
      ...
      params: {
        env: 'NODE_PATH=' + wallaby. projectCacheDir // or whatever the folder is
      }
    }
    ...
  };
};
```

**Comment by kristojorg** [comment]
I am unable to make this work. I'm using the [automatic absolute imports](https://nextjs.org/blog/next-9-4#absolute-imports-and-aliases) provided by Next.js and I have tried configuring as you suggest above, but I am still seeing that it cannot resolve modules when the Next.js app can resolve them. Specifically I am trying to import `src/icons/...` as `icons/...`. Below is my wallaby.js file:
```js
const path = require('path');

module.exports = (wallaby) => {
  const NODE_PATH = process.env.NODE_PATH +
      path.join(wallaby.projectCacheDir, 'src');
  return {
    autoDetect: true,
    env: {
      params: {
        env: `NODE_PATH=${NODE_PATH}`
      }
    }
  }
}
```

**Comment by ArtemGovorov** [comment]
@kristojorg This setting shouldn't be required for automatic Jest config. Can you please create a new issue and provide the details listed in the new issue template?
