### ISSUE TITLE
Error: Cannot find module 'sinon' (continuing #821)

### ISSUE THREAD

**Issue by ProLoser** [wallabyjs/public#1100]
I'm having the same problem as #821  `Error: Cannot find module 'sinon'` with the following config:

```js
module.exports = function (wallaby) {
  return {
    env: {
      type: 'node'
    },
    files: [
      '../src/**/*.js'
    ],
    tests: [
      './**/*.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') })
    },
    debug: true,
    testFramework: 'mocha',
    workers: {
      recycle: true
    },
    setup: function(wallaby) {
      var mocha = wallaby.testFramework;

      // setup sinon hooks
      var sinon = require('sinon');
      mocha.suite.beforeEach('sinon before', function() {
        if (null == this.sinon) {
          this.sinon = sinon.sandbox.create();
        }
      });
      mocha.suite.afterEach('sinon after', function() {
        if (this.sinon && 'function' === typeof this.sinon.restore) {
          this.sinon.restore();
        }
      });
    }
  };
};
```

I could not understand your comments though about webpack. I don't like having all these additional package dependencies just for wallaby as I'm the only one on my team (currently) using wallaby.

> **Note:** Started a new issue so I wouldn't spam the previous user.

**Comment by ProLoser** [comment]
Hoisting the `require('sinon')` in this file yielded new issues:

```
"before each" hook: sinon before for "returns the toString value of an object": sinon is not defined
"before each" hook: sinon before for "exposes isNullOrEmpty": sinon is not defined
"before each" hook: sinon before for "should return false when given a null or empty item": sinon is not defined
"before each" hook: sinon before for "returns true on null": sinon is not defined
"before each" hook: sinon before for "returns true for any Date object that represents a valid date": sinon is not defined
"before each" hook: sinon before for "merges two simple objects with different fields": sinon is not defined
```

**Comment by ProLoser** [comment]
I'm wondering if #357 might be outdated? I now have this as a config which seemed to be working (finally):

```js
module.exports = function (wallaby) {
  return {
    env: {
      type: 'node'
    },
    files: [
      { pattern: 'test/helpers/*.js', instrument: false },
      'src/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    debug: true,
    testFramework: 'mocha',
    workers: {
      recycle: true
    },
    setup: function() {
      // Adds helpers for chai to use
      require('./test/helpers/chai-helpers');
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

[This issue](https://github.com/wallabyjs/public/issues/821) is not related, I'll have a look why https://github.com/wallabyjs/public/issues/357 didn't work.

Also, unrelated to the original issues, but your `tests` pattern looks too broad. Wallaby [requires only files with actual tests in them](https://wallabyjs.com/docs/config/files.html#tests) to be in the list, and the `./test/helpers/chai-helpers` is most likely not a file with tests, so it needs to be in the `files` list instead.

If you have some naming convention, like `.spec.js`, for your tests you may do:

```javascript
module.exports = function (wallaby) {
  return {
    env: {
      type: 'node'
    },
    files: [
      'src/**/*.js',
      'test/**/*.js'
      '!test/**/*.spec.js'
    ],
    tests: [
      'test/**/*.spec.js'
    ],
    ...
  };
};
```

**Comment by ArtemGovorov** [comment]
> I'm wondering if #357 might be outdated?

Just tried a quick sample and it's working for me. I have pushed [my sample to this branch](https://github.com/wallabyjs/wallaby-node-iojs-sample/blob/sinon/wallaby.js#L17), you may have a look to see if it's working for you if you have some time (and it's still relevant to you).
