### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ProLoser** [wallabyjs/public#1101]
### Issue description or question

I get the following error when I try to put my `setup` logic into a secondary file instead of directly in wallaby.js

```
TypeError: Cannot read property '0' of undefined
at Object.<anonymous> test/helpers/chai-helpers.js:1:0
```
This is fixed if I copy the contents of `chai-helpers` directly into the wallaby file instead of requiring it. Is this absolutely necessary? I wish to share this logic across build tools and don't like having to copy-paste it everywhere.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    env: {
      type: 'node'
    },
    files: [
      'src/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    testFramework: 'mocha',
    workers: {
      recycle: true
    },
    setup: function() {
      require('./test/helpers/chai-helpers');
      // ./test/helpers/chai-helpers.js:
      // let chai = require('chai');
      // chai.config.includeStack = true;
      // chai.use(require('sinon-chai'));
      // chai.use(require('chai-datetime'));
    }
  };
};
```

### Code editor or IDE name and version

Atom v1.15.0 64

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment]
The reason for the error may be that your tests pattern includes not tests. Try adjusting your `tests` pattern as I [suggested here](https://github.com/wallabyjs/public/issues/1100#issuecomment-291671258).

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please try the suggestion above.

**Comment by andrew-w-ross** [comment]
@ArtemGovorov  I recreated this issue [here](/andrew-w-ross/wallaby-issue). If you change one of the tests in any way you'll get the same error.

**Comment by ArtemGovorov** [comment]
@andrew-w-ross Thanks for the repo, I have [sent you the PR](https://github.com/andrew-w-ross/wallaby-issue/pull/1). 

The issue is [described here](https://github.com/wallabyjs/public/issues/1100#issuecomment-291671258). Wallaby [requires only files with actual tests in them](https://wallabyjs.com/docs/config/files.html#tests) to be in the `tests` list, and the `test/setupTest.js` is not a file with tests, so it needs to be in the `files` list instead. 

Alternatively, you may change the `test/setupTest.js` file name to not follow your tests name pattern, and include all the helpers to the `files` list:
```javascript
module.exports = function (wallaby) {
  return {
		files: [
			'src/**/*.js',
			'test/**/*.js',
			'!test/**/*Test.js'
		],

		tests: [
			'test/**/*Test.js'
		],
    ...
  };
};
```

**Comment by kevinbeal** [comment]
I'm constantly running into this with automatic configuration. It never starts with the error. It seems to be introduced maybe when I focus tests and when I refactor, but I can't be sure.

What are the defaults for `files` and `tests` when using automatic configuration? If I knew, maybe I could find any offending files. I tried adding [this](https://github.com/chgc/angular-nx-wallaby/blob/fd1968f3e05c28277eaf150a7e2a7e0b49937e7e/wallaby.js#L48) following to my package.json to override them, but it didn't run any of my tests at all.

**Comment by kevinbeal** [comment]
I ended up adding the following to my `package.json` and it seems to work well so far:

```
"wallaby": {
    "files": [
        "apps/**/*.{ts,tsx}",
        "libs/**/*.{ts,tsx}",
        "!**/**/*.spec.{ts,tsx}"
    ],
    "tests": [
        "libs/**/*.spec.{ts,tsx}",
        "apps/**/*.spec.{ts,tsx}",
        "!**/integration/*"
    ]
}
```

**Comment by kevinbeal** [comment]
Now instead of immediately giving me the error, it takes 10 minutes of work.

**Comment by smcenlly** [comment]
@kevinbeal - this issue is old and closed from 2017. Moved to a new issue: https://github.com/wallabyjs/public/issues/2758. Please see my reply and respond there.
