### ISSUE TITLE
Wallaby with React, Webpack and Mocha - cannot find module "fs"

### ISSUE THREAD

**Issue by PaulStovell** [wallabyjs/public#1102]
Hello!

I have a React app using TypeScript and Mocha:

https://github.com/PaulStovell/react-sandbox

Mocha runs from `npm test` using a `test/mocha.opts` file. The tests run fine from command line. However, I can't figure out how to set up the Wallaby options to make it run from Wallaby. When I start Wallaby, I get:

```
​​[Error] Runtime error: Error: Cannot find module "fs"​​
​​[Error] Runtime error: Error: Cannot find module "fs"​​
​​[Error] at http://localhost:64843/____wallaby-bundle.js?1491370076848&wallabyFileId=bundle:49832​​
​​[Error] Runtime error: Error: Cannot find module "fs"​​
​​[Error] Runtime error: Error: Cannot find module "fs"​​
​​[Error] at http://localhost:64843/____wallaby-bundle.js?1491370076848&wallabyFileId=bundle:49832​​
```

 - Wallaby.js configuration file: https://github.com/PaulStovell/react-sandbox/blob/master/wallaby.js
 - Visual Studio Code v1.10.2
 - Windows

**Comment by PaulStovell** [comment]
In my Wallaby.js setup I had this:

```
    setup: function () {
      window.__moduleBundler.loadTests();
    },
```

(Not sure where I got it from.)

When I remove that I get a bit further - now Wallaby starts, but when it runs tests it prints:

```
​​[Error] Runtime error: ReferenceError: Can't find variable: exports​​
​​[Error] Runtime error: ReferenceError: Can't find variable: exports​​
​​[Error] at http://localhost:65292/app/components/Directory.spec.js?1491370394343&wallabyFileId=1:3​​
```

**Comment by ArtemGovorov** [comment]
Hey Paul,

I have sent you [the pull request](https://github.com/PaulStovell/react-sandbox/pull/1). Since you run your tests in node with mocha anyway, I have just [made your wallaby config to use node environment](https://wallabyjs.com/docs/integration/node.html) and got rid of the webpack stuff. 

> `Runtime error: ReferenceError: Can't find variable: exports​​`

By default wallaby runs in browser environment, so CommonJs (that your TypeScript modules are compiled to) is not supported there, and you do need webpack in case if you'd like to run your tests in browser. 

Let me know if you're happy to run your tests in node (like you do with mocha), or would like me to help with the browser/webpack configuration.

**Comment by PaulStovell** [comment]
Thanks Artem, it was this that I was missing:

```
require('ignore-styles');
```

**Comment by ArtemGovorov** [comment]
Oh, cool, thanks for the update. Sorry I forgot to mention about it, you may load any required stuff (and configure mocha) in [the `setup` function](https://wallabyjs.com/docs/integration/node.html#mocha---require-equivalent).

**Comment by PaulStovell** [comment]
To help anyone who stumbles upon this via Google - I have a TypeScript file which imports a LESS CSS file (which Webpack requires):

```
import "./Directory.less";
```

When the tests ran under Mocha I'd get an error because it would try to load the module as JavaScript/TypeScript:

```
​​[Error] Runtime error: .\app\components\Directory.less:1​​
​​[Error] (function (exports, require, module, __filename, __dirname) { body {​​
​​[Error]                                                                    ^​​
​​[Error] SyntaxError: Unexpected token {​​
```

To make Mocha work from the command line, I used:

```
mocha ....... --require ignore-styles
```

But as Artem showed, I needed to do the same in Wallaby:

```
    setup: function () {
      require('ignore-styles');
    },
```
