### ISSUE TITLE
Cannot setup Wallabyjs to use nodejs installed in Linux Subsystem (Bash/Ubuntu on Windows)

### ISSUE THREAD

**Issue by swissarmykirpan** [wallabyjs/public#1104]
### Issue description or question
I have installed Visual Studio Code in Windows 10 and have setup the Linux Subsystem.
I would like to be able to use the nodejs installation in the Linux Subsystem to run Wallaby, but the `wallaby.node` property will only enable execution in Windows.

### Code editor or IDE name and version
Visual Studio Code v1.x

### OS name and version

Windows 10 + Linux Subsystem

**Comment by ArtemGovorov** [comment]
This is by design. Wallaby can only run locally installed node.js version.
