### ISSUE TITLE
code coverage

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#1105]
is there a way to ignore certain sections of code when determining code coverage?

For example, sometimes error branches are very difficult to write tests for... is there a way for the coverage report to ignore those sections of code?

aaron

**Comment by ArtemGovorov** [comment]
Yes, you may [use the special code comments](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) to ignore certain sections of code for code coverage purposes.

**Comment by scriptsure** [comment]
so it does work... but not sure why in this particular situation it doesnt... any idea???

![image](https://cloud.githubusercontent.com/assets/798281/24771815/004ae01c-1add-11e7-8f57-bdd8654edf3f.png)

![image](https://cloud.githubusercontent.com/assets/798281/24771827/0fbe9b9c-1add-11e7-9acb-cc9f8c170fcf.png)

**Comment by ArtemGovorov** [comment]
Hmm, strange, not sure what's wrong. 

Did you try to restart wallaby and wallaby app after adding the hint?

Could you please attach a screenshot of the same code region in your editor, your full wallaby.js config and the piece of code so that I could try it without having to re-type the whole thing from the screenshot?

**Comment by scriptsure** [comment]
yes actually i completely restart machine. :)

```
router.delete('/:id', function (req, res) {

    if (routeHelper.isInt(req.params.practiceId)) {
        AuditLog.destroy(
            {
                where: {practiceId: parseInt(req.params.practiceId, 10)}
            }
        ).then(function (result) {
            res.status(http_status.OK_200).send({affectedcount: result});
        }).catch(function (error) {
            /* ignore coverage */
            logger.error('Error clearing audit log', util.inspect(error), function (log) {
                res.status(http_status.INTERNAL_SERVER_ERROR_500).send({
                    id: log? log.id : 'audit logging error',
                    err: error
                });
            });
        });

    } else {
        routeHelper.handleErrorResponse(res, {error: 'Integer value expected.'});
    }
});
```

```
module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'config/**',instrument: false, load: true, ignore: false},
            {pattern: 'config/passport.js',instrument: false, load: true, ignore: false},
            {pattern: 'app.js', load: true, ignore: false},
            {pattern: 'server.js', instrument: false,load: false, ignore: false},
            {pattern: 'lib/**', load: true, ignore: false},
            {pattern: 'routes/**/**/**/**', load: true, ignore: false},
            {pattern: 'models/**/**', instrumented: false, load: true, ignore: false}
        ],

        tests: [
            'test/api/auditlog.spec.js'

        ],

        testFramework: 'jasmine@2.3.4',

        workers: {
        initial: 1,
            regular: 1,
            recycle: true
    },
        hints: {
            ignoreCoverage: /ignore coverage/
        },
        // delays: {
        //     edit: 500,
        //     run: 150
        // },
        setup: function () {
            var winston = require('winston');
            if (!winston.transports.ConsoleLogger) {
                var ConsoleLogger = winston.transports.ConsoleLogger = function (options) {
                    this.level = 'verbose';
                };
                require('util').inherits(ConsoleLogger, winston.Transport);
                ConsoleLogger.prototype.log = function (level, msg, meta, callback) {
                    console.log(msg);
                    callback(null, true);
                };
                winston.remove(winston.transports.Console);
                winston.add(winston.transports.ConsoleLogger);
                winston.add = winston.remove = function () {

                };
            }

        },
        debug: true,
          // TypeScript compiler is on by default with default the options,
        // you can configure the built-in compiler by passing options to it.
        // See interface CompilerOptions in
        // https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts
        // compilers: {
        //'**/*.ts': wallaby.compilers.typeScript({}),
        env: {
            // use 'node' type to use node.js
            type: 'node',
            runner: 'node'

        }
    };
};


```

**Comment by ArtemGovorov** [comment]
Thanks for the files.

I have created [this sample branch](https://github.com/wallabyjs/wallaby-node-iojs-sample/tree/wallaby-1105) with your test file and the source file, and the config, and everything is working as expected. I don't import the file, but it is instrumented correctly, no coverage indicators displayed for the ignored statement [in the file](https://github.com/wallabyjs/wallaby-node-iojs-sample/blob/wallaby-1105/lib/file.js):

<img width="654" alt="screen shot 2017-04-08 at 2 32 21 pm" src="https://cloud.githubusercontent.com/assets/979966/24825738/78047e88-1c68-11e7-9d8a-1326f7429c30.png">

Please clone the repo, run it to see if you're getting the same result, and if so, have a look and try adding the missing bits (like pasting the full content of the file - maybe just that bit is not enough to reproduce the issue).
