### ISSUE TITLE
Do not display coverage indicators in VSC diff views

### ISSUE THREAD

**Issue by medikoo** [wallabyjs/public#1108]
I'm running Visual Studio Code v1.11.1 on macOS 10.12.4.

I found that wallaby adds it's markers to git diff views, and I find it quite confusing, I wouldn't expect them there.

![screen shot 2017-04-07 at 17 27 01](https://cloud.githubusercontent.com/assets/122434/24807491/a8604ea0-1bb8-11e7-9ec2-12c16334158f.png)

**Comment by ArtemGovorov** [comment]
There's [currently no VS Code API](https://github.com/Microsoft/vscode/issues/15513) to determine whether the editor is used in a diff view or not. Once the API is added, we'll be able to remove the markers.

**Comment by medikoo** [comment]
Thanks @ArtemGovorov hope they'll sort it in reasonable time

**Comment by smcenlly** [comment]
This has been fixed.
