### ISSUE TITLE
Support ava@0.19.0

### ISSUE THREAD

**Issue by clebert** [wallabyjs/public#1109]
### Issue description or question

The use of `ava@0.19.0` results in the following error:
ava node module is not found or the version is not supported, missing `npm install ava --save-dev`?​​

The use of `ava@0.18.2` in the same setup works.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: ['src/**/*.ts', '!src/**/*.test.ts'],
    tests: ['src/**/*.test.ts'],
    env: {type: 'node', runner: 'node'},
    testFramework: 'ava'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.11.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
AVA 0.19.0 support has just landed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
