### ISSUE TITLE
Please support ava 0.19.0

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#1111]
Since update to ava 0.19.0 the support is broken.

**Comment by ArtemGovorov** [comment]
We have added the support a couple of days ago: https://github.com/wallabyjs/public/issues/1109, please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). If it's still not working for you after the update, please create a sample repo demonstrating the issue.
