### ISSUE TITLE
Babel in node_modules of a subfolder

### ISSUE THREAD

**Issue by KingHenne** [wallabyjs/public#1112]
### Issue description or question

Is the tipp [Node modules in subfolder](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) also valid for finding `babel` within `wallaby.compilers.babel()`? If I use the config below (i.e. `'**/*.js': wallaby.compilers.babel()`) I get this error:

> Failed to load configuration file:  Error: babel or babel-core must be installed locally or babel instance must be passed in opts.babel, for example `wallaby.compilers.babel({ babel: require('babel') })`​​

Using this config instead:

```js
'**/*.js': wallaby.compilers.babel({
  babel: require('./client/node_modules/babel-core')
})
```

I get this error:

```
Error: spawn /Users/hendrik/.nvm/versions/node/v6.10.2/bin/node EMFILE​​
  at exports._errnoException (util.js:1018:11)​​
  at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)​​
  at onErrorNT (internal/child_process.js:367:16)​​
  at _combinedTickCallback (internal/process/next_tick.js:80:11)​​
  at process._tickCallback (internal/process/next_tick.js:104:9)​​
```

### Wallaby.js configuration file

```javascript
'use strict';

const path = require('path');

module.exports = function (wallaby) {
  const nodeModulesPath = path.join(wallaby.localProjectDir, 'client', 'node_modules');
  if (process.env.NODE_PATH) {
    process.env.NODE_PATH += path.delimiter + nodeModulesPath;
  } else {
    process.env.NODE_PATH = nodeModulesPath;
  }

  return {
    env: {
      type: 'node'
    },
    files: [
      'client/**/*.js',
      '!client/spec/**/*.spec.js'
    ],
    testFramework: 'jest',
    tests: [
      'client/spec/**/*.spec.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    delays: {
      run: 500
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.11.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
This should work for you:

```javascript
'**/*.js': wallaby.compilers.babel({
  babel: require('./client/node_modules/babel-core')
})
```

> Error: spawn /Users/hendrik/.nvm/versions/node/v6.10.2/bin/node EMFILE​​

I suspect this may happen because there are quite a few node modules in the `./client/node_modules` folder and your `files` pattern includes them, so wallaby babel compiler tries to compile them all. Try excluding node_modules from your `files`:

```javascript
    files: [
      'client/**/*.js',
      '!client/node_modules/**',
      '!client/spec/**/*.spec.js'
    ],
```

Let me know if it resolves the issue for you.

**Comment by KingHenne** [comment]
This resolves it. Thanks, Artem!
