### ISSUE TITLE
Jest: starting WallabyJS shouldn't update snapshots

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#1115]
### Issue description or question
When WallabyJS starts, it implicitly updates the snapshots.

I realize that this is a side-effect of being able to update snapshots when you choose to "Run Project Tests", but it isn't something that is desired.

If you were to update a file that causes a snapshot comparison to fail, you have to explicitly run the test again to get the snapshot to update. Let's say that you didn't update the snapshot and you restart WallabyJS. The snapshot will then be updated even though you did not intend it to.

For comparison, Jest-CLI leaves the snapshots alone until you tell it to update them. I think WallabyJS should do this as well?

**Comment by ArtemGovorov** [comment]
Wallaby shouldn't update snapshots when it is starting, it is supposed to work like Jest-CLI does.

> Let's say that you didn't update the snapshot and you restart WallabyJS. The snapshot will then be updated even though you did not intend it to.

I'm using [this sample repo](https://github.com/wallabyjs/wallaby-jest-snapshots) and everything is working for me as expected:

![ws](https://cloud.githubusercontent.com/assets/979966/24987197/ea68ff9e-2041-11e7-9c58-8ff297a6f5a6.gif)

How can I reproduce the issue that you're observing?

**Comment by thomastnguyen91** [comment]
That's weird. I cannot seem to reproduce it today. Maybe it was just a fluke. I think that we can close this and I'll reopen it if I encounter it again. Thank you for the help.
