### ISSUE TITLE
Unable to use NVM node

### ISSUE THREAD

**Issue by kisenka** [wallabyjs/public#1116]
Hi! 
I'am trying to use 7.9.0 nodejs version installed via nvm but getting _"Failed to parse, SyntaxError: Unexpected token (26:59)"_ ([link to the test/plugin.test.js](https://github.com/kisenka/svg-sprite-loader/blob/2.0/test/plugin.test.js#L26)). I'am trying different ways to specify custom node location:
* [runner](https://github.com/kisenka/svg-sprite-loader/blob/2.0/wallaby.config.js#L17) option
* [pass WALLABY_NODE env](https://gist.github.com/kisenka/72de2b16411ca996a6a203e818c4dfaa)

**Environment**
* [wallaby.js config](https://github.com/kisenka/svg-sprite-loader/blob/2.0/wallaby.config.js)
* wallaby plugin 1.0.67
* wallaby core 1.0.253
* WebStorm 2017.1
* macOS Sierra 10.12.3

**How to reproduce**
- Install nvm, then `nvm install 7.9.0`
- `git clone https://github.com/kisenka/svg-sprite-loader -b 2.0`
- `npm install`
- Create wallaby run configuration & run it
- NVM's node working, to check it you can run run mocha tests via `npm test`

**Comment by ArtemGovorov** [comment]
I tried your config from https://github.com/kisenka/svg-sprite-loader/blob/2.0/wallaby.config.js and it's working (after replacing the home dir name), also this is working for me:

```javascript
module.exports = (wallaby) => {
  const config = {
    files: [
      { pattern: 'lib/*.js' },
      { pattern: 'lib/**/*.js' },
      { pattern: 'test/tests-*.js', instrument: false }
    ],

    tests: [
      { pattern: 'test/*.test.js' }
    ],

    testFramework: 'mocha',

    env: {
      type: 'node',
      runner: require('os').homedir() + '/.nvm/versions/node/v7.9.0/bin/node'
    },

    // eslint-disable-next-line no-shadow
    setup: (wallaby) => {
      const mocha = wallaby.testFramework;
      mocha.ui('bdd');
    }
  };

  return config;
};
```

My guess that it may not be working for you because you're using the old version of core (where the scenario was not supported). Try the trial version with the latest core to see it's working for you.

**Comment by rluvaton** [comment]
People who want to use the node version based on their local `.nvmrc` file can use this:

```js
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

const nvmrcPath = path.join(__dirname, '.nvmrc');

function getNodePathFromNvm() {
	let nvmrcVersion;
	try {
		nvmrcVersion = fs.readFileSync(nvmrcPath, 'utf8').toString();
	} catch (e) {
		console.error('Failed to read .nvmrc file', e);

		throw new Error('Failed to read .nvmrc file');
	}

	const loadNvmScriptPath = path.join(process.env.NVM_DIR, 'nvm.sh');

	// Will equal /Users/<user>/.nvm/versions/node/<version>/bin/node on Mac for example
	return execSync(`source ${loadNvmScriptPath} && nvm which ${nvmrcVersion}`).toString().trim();
}

function getNodeFromNvmrcOrNone() {
	// Meaning that no nvm exists
	if (!process.env.NVM_DIR) {
		return undefined;
	}

	if (!fs.existsSync(nvmrcPath)) {
		return undefined;
	}

	return getNodePathFromNvm();
}

module.exports = function () {
	return {
		autoDetect: true,
		smartStart: [{ startMode: 'edit' }],
		env: getNodeFromNvmrcOrNone()
	};
};

```
