### ISSUE TITLE
Babel compiler source code

### ISSUE THREAD

**Issue by damonmaria** [wallabyjs/public#1117]
I wish to use Meteor's wrapper of the Babel compiler (https://github.com/meteor/babel/blob/master/index.js) to compile my Meteor project for testing in Wallaby. Everything is there, even the AST. But I don't want to reinvent the wheel with converting Babel's AST into the ranges that Wallaby requires. 

Would it be possible to publish (in this repo) the source to Wallaby's Babel compiler? It would be instructive to others producing their own compilers for Wallaby as well. Thanks.

**Comment by damonmaria** [comment]
@ArtemGovorov I've gotten around the need for this, so am happy for you to close it unless it's thought worthwhile for others.

**Comment by seanpoulter** [comment]
You can close this one @ArtemGovorov.
