### ISSUE TITLE
Angular CLI - css import and "stylePreprocessorOptions"

### ISSUE THREAD

**Issue by zetsnotdead** [wallabyjs/public#1119]
### Issue description or question
Css import in component's stylesheet breaks the test. I'm importing without using the relative path, after setting the stylePreprocessorOptions in .angular-cli.json.

I've created a small [repo](https://github.com/zetsnotdead/wallaby-angular-cli-scss-imports) replicating the issue.

I'm pretty sure the solution is to somehow let the webpack's loader know about the new style paths, specified in .angular-cli.json under the "stylePreprocessorOptions", but I can't seem to figure it out.

### Wallaby.js configuration file
[ngCliWebpackSample config](https://github.com/wallabyjs/ngCliWebpackSample)

### Code editor or IDE name and version
Visual Studio Code Version 1.11.2

### OS name and version
Ubuntu 16.04 LTS

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

In cases like this one, you may use `ng eject` command for your project - it generates the webpack config that is supposed to work without Angular CLI, so you may take the corresponding loader configuration from there.

I did `ng eject` for your case and from the generate webpack config it looks like the `LoaderOptionsPlugin` can be used to pass the SASS options. I [have sent you the PR](https://github.com/zetsnotdead/wallaby-angular-cli-scss-imports/pull/1).

```javascript
var LoaderOptionsPlugin = require('webpack').LoaderOptionsPlugin;
...
module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    ...

    plugins: [new LoaderOptionsPlugin({
      options: {
        sassLoader: {
          includePaths: [
            "./src/some-styles"
          ]
        }
      }
    })]
  });

  return ...;
};

```

**Comment by zetsnotdead** [comment]
Thanks for the quick fix :+1:
