### ISSUE TITLE
Example for preprocessed templates that are already js source and enabled for code coverage.

### ISSUE THREAD

**Issue by whindes** [wallabyjs/public#1120]
### Issue description or question

I can successfully preprocess any *.ejs (or any extention) which is already a javascript code file.  All I need now is to show code coverage. I shouldn't need a compiler (it's already javascript, the extention is the only thing pre-processed).  Is there a different configuration or is this supported?  

### Wallaby.js configuration file
```javascript
module.exports = function () {
    return {
        files: [
            'managers/**/*.js',
            'services/**/*.js',
            { pattern: 'views/angularjs/*.ejs', instrument: true }
            
        ],     
        
        preprocessors: {
            'views/angularjs/*.ejs': function (file) {
                file.changeExt('js')
                 return file.content;
            }
        },

		tests: [
            'test/*.js'
        ],
		
        env: {
            type: 'node',
            runner: 'node'  // or full path to any node executable
        }
    };
};
```
### Code editor or IDE name and version

Visual Studio 2017

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
We have added the support for custom JavaScript extensions and published it in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

You may now do this:
```javascript
module.exports = function () {
    return {
        extensions: {
          javascript: ['ejs']
        },
        ...
    };
};
```
Also, in order to load the files from node.js you may either leave your preprocessor that changes the extension, or remove it and [let node know](https://nodejs.org/api/globals.html#globals_require_extensions) that your `.ejs` files need to be loaded the same way as it loads `.js` files:

```javascript
module.exports = function () {
    return {
        ...
        setup: function() {
          require.extensions['.ejs'] = require.extensions['.js'];
        }
    };
};
```

**Comment by whindes** [comment]
Only when I manually change the file extension on the source file to .js the green/grey blocks appear.  When leaving .ejs extension and using the configuration suggested (extensions, setup, NOT using preprocessor).  No success yet for wallaby source .ejs .  Mocha tests pass in both.

wallaby.js started
core v1.0.416
Wallaby App available at: http://wallabyjs.com/app/#/files
Finished executing 10 affected test(s)

**Comment by whindes** [comment]
Hope to get the .ejs to light up :)
