### ISSUE TITLE
Code coverage does not show grey/green boxes for custom JavaScript extensions.

### ISSUE THREAD

**Issue by whindes** [wallabyjs/public#1122]
### Issue description or question
We should be able to see code coverage lines in the configured .ejs extension.

Only when renaming the file in the view folder (views/angularjs/*.ejs) to .js extention it lights up the code coverage lines correctly.  Expecting the same behavior with .ejs configured in wallaby.js

Mocha is working for both .ejs and .js scenarios above.

Thanks in advance for enhancing this feature.

Cheers!

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {

        extensions: {
            javascript: ['.ejs']
        },

         setup: function () {
            require.extensions['.ejs'] = require.extensions['.js'];
        },

        files: [
            'managers/**/*.js',
            'services/**/*.js',
            { pattern: 'views/angularjs/*.ejs', instrument: true }
        ],
        
        tests: [
            'test/*.js'
        ],        

        env: {
            type: 'node',
            runner: 'node'  // or full path to any node executable
        }
       
    };
};
```

### Code editor or IDE name and version

Visual Studio 2017

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
First of all, you need to remove the dot from the extension, as [in the example here](https://github.com/wallabyjs/public/issues/1120#issuecomment-294325335).

```
        extensions: {
            javascript: ['ejs']
        },
```

It'll still not work unfortunately, because of some restrictions in Visual Studio extension model. We have found the solution and are working on it, I'll let you know as soon as the new extension version is available.

Could you please also clarify something for us - are you using any VS extension to get the syntax highlighting in `.ejs` files?

**Comment by whindes** [comment]
Good morning from Seattle!

Some of these may have been installed by a bundled VSIX

All of these below are from the same Creator: Mads Kristensen

Markdown Editor

Editor Enhancements
EditorConfig Language Service
HTML Snippet Pack
HTML Tools

At one time before using Visual Studio 2017 (using VS 2015), I had just used the Tools>Options>Text Editor>File Extension and added .ejs
Now, there is nothing configured there at this time.

**Comment by ArtemGovorov** [comment]
Ok, we have done some investigation, and it looks like we don't need to release any updates. It should work for you if you:
- remove the dot from your wallaby config extensions setting, so it becomes
```
        extensions: {
            javascript: ['ejs']
        },
```
- associate `.ejs` file with JavaScript editor in your VS settings:

![vs_text_editor_ejs](https://cloud.githubusercontent.com/assets/979966/25082719/f719adfe-2395-11e7-8c33-9877e70c9bd1.png)

Let us know if it works for you this way.

**Comment by whindes** [comment]
I tried this in both Visual Studio 2015 & Visual Studio 2017... no success.

**Comment by ArtemGovorov** [comment]
@whindes Sorry about it, I confirm - we have found the scenarios when it doesn't work, we are investigating it further.

**Comment by ArtemGovorov** [comment]
Ok, so we have released the new 1.0.33 version of the extension. Please restart your VS to get the update prompt (or install the latest form our website), and try it.

**Comment by whindes** [comment]
Updated to 1.0.32.... (says aleady updated) restarted vs 2017
wallaby.js started
core v1.0.416 (same core?)

No change.

**Comment by ArtemGovorov** [comment]
Could you please attach your current wallaby config and the full list of the extension that you have installed?

**Comment by ArtemGovorov** [comment]
Also, just in case if it is a caching issue, try changing your wallaby config (even a space anywhere in the file is enough) and restarting wallaby.

**Comment by ArtemGovorov** [comment]
One more thing, could you please also attach a screenshot of the `.ejs` file where it doesn't show the indicators and the screenshot of the installed wallaby extension page (from `Tools - Extensions...`)?

**Comment by whindes** [comment]
```
module.exports = function () {
    return {

        extensions: {
            javascript: ['ejs']
        },

         setup: function () {
            require.extensions['.ejs'] = require.extensions['.js'];
        },

        files: [
            'managers/**/*.js',
            'services/**/*.js',
            { pattern: 'views/angularjs/*.ejs', instrument: true }
        ],
        
        tests: [
            'test/*.js'
        ],        

        env: {
            type: 'node',
            runner: 'node'  // or full path to any node executable
        }
       
    };
};
```
Installed Visual Studio Extensions 
.ignore
Add New File
Azure Data Lake Tools for Visual Studio
Bootstrap Snippet Pack
Browser Reload on Save
Browser Sync
Bundler & Minifier
Css Tools
Developer Analytics Tools
Editor Enhancements
EditorConfig Language Service
Extensibility Tools
File Icons
File Nesting
HTML Snippet Pack
HTML Tools
Image Optimizer
Image Sprites
Javascript Regions
JavaScript Snippet Pack
JavaScript Transpiler
Markdown Editor
Microsoft Advertising SDK for Windows 8.1
Microsoft Advertising SDK for Phone
Microsoft ASP.NET and Web Tools
Microsoft Azure App Service Tools
Microsoft Office 365 API Tools
Microsoft Visual Studio Test Platform
Microsoft Visual Studio Tools for Containers
Microsoft VisualStudio Managed Publish
Microsoft.VisualStudio.UniversalLibrary.dll
MSTest V2 Create Unit Test Extension
MSTest V2 Templates
MSTest V2 Templates (Universal Windows)
Node.js Tools
Node.js Tools - Interactive Window
NPM Task Runner
Open Command Line
Package Installer
Package Security Alerts
PowerShell Tools for Visual Studio 2017
Project File Tools
Razor Language Services
ReSharper Ultimate
Rosyln Expression Evaluators
Roslyn Interactove Components
Roslyn Language Services
Roslyn Language Services for Visual Studio 15
Serice Fabric Tools
SQL Search
Syntax Highlighting Pack
TypeScript for Microsoft Visual Studio
Visual F# Tools
Visual Studio Extensibility Templates
Visual Studio Extension for TextMate Grammers
Visual Studio Extensions for Windows Library
VisualStudio Interactive WIndow
Vue.js Pack 2017
Wallaby.js for Visual Studio 2017
Web Accessibilty Checker
Web Compiler
Web Essensials 2017
ZenCoding

**Comment by ArtemGovorov** [comment]
Thanks, try [resetting wallaby cache](https://github.com/wallabyjs/public/issues/1122#issuecomment-295067347), I think it should help.

**Comment by whindes** [comment]
![wallabyextension](https://cloud.githubusercontent.com/assets/16513896/25162836/86a3b926-247a-11e7-9652-9aeb00bae06c.jpg)

**Comment by whindes** [comment]
Reset Cache (Change wallaby.js line)"   'views/angularjs/*.ejs',

![ejs_file](https://cloud.githubusercontent.com/assets/16513896/25163179/33ebfe16-247d-11e7-8df7-719ac95a6cfd.jpg)

**Comment by whindes** [comment]
Reset and VS 2017 no luck.  I even removed the <script> tags in the .ejs file (line 1 & 47)

**Comment by ArtemGovorov** [comment]
Thanks for providing the info.

> Reset Cache (Change wallaby.js line)

Just in case, could you try adding an empty line or two to the config?

Also, it looks like Web essentials is highlighting the file, not of the `.ejs` file association in the VS settings. Could you please check that the `.ejs` file is associated with JavaScript Editor, as [we have discussed](https://github.com/wallabyjs/public/issues/1122#issuecomment-294426624) here?

> Test.ejs

Could you please rename the file to `Test.js` (without wallaby config changes) to see if it'll showing indicators or not?

**Comment by whindes** [comment]
I did the rename one file .ejs to .js and the other .ejs files threw warnings pointing to the instrumented cache folder

FINALLY WORKS after manually going to:
C:\Users\whindes\AppData\Local\Temp\.wallaby\projects 
deleted the cached folder.

Hooray !!!

![ejs_file_update](https://cloud.githubusercontent.com/assets/16513896/25163522/d3d051c8-247f-11e7-860d-a147000559cb.jpg)

**Comment by ArtemGovorov** [comment]
Awesome!

I'm still puzzled as to why it didn't work though. 

> after manually going to: C:\Users\whindes\AppData\Local\Temp.wallaby\projects deleted the cached folder.

Wallaby config change is supposed to cause the cache folder cleaning, so it may not be the reason why it worked.

I suspect it may be related to the file association - see how on [your screenshot here](https://github.com/wallabyjs/public/issues/1122#issuecomment-295079637) the `// <script>` tag is highlighted and there's no function names below the file tabs? It seems like JavaScript editor association wouldn't do it, rather the HTML editor association would. 

Then on your [next screenshot here](https://github.com/wallabyjs/public/issues/1122#issuecomment-295085452) it is correctly highlighted as comment and function names appear below the file tabs (just as JavaScript editor association would do). 

Because wallaby doesn't interfere with the highlighting/editor association at all, it must have been one of your extensions/settings.

**Comment by whindes** [comment]
I just tried another scenario to change the .ejs extension back to HTML and it regressed.  However, I was able to get it back by tracking these steps.

1.  Change the Text Editor extension for .ejs back to Javascript (instead of HTML)
2.  Change the wallaby.js config that targets .ejs to .js
3.  Rename Test.ejs to .js
4.  Observe Error for cached ejs.
5.  Delete cache folder
6.  Stop Wallaby
7.  Revert step 2, wallaby.js config back to target .ejs 
8.  Restart Wallaby
9.  Shut down Visual Studio
10. Delete cache folder again.
11.  Start Visual Studio
12.  Start Wallaby .... Hooray, fix.

**Comment by ArtemGovorov** [comment]
@whindes Hmm, interesting! Thanks for describing the steps, will try to follow to see if we can get somewhere. 

Either way, it's not blocking you now with JavaScript editor extension, is it?

**Comment by whindes** [comment]
The .ejs file we are using in this scenario is for a partial view (and can be unit tested now) so it is not intrusive to the other layouts for HTML views in the API (not required for code coverage).  Not blocked at the moment.  But other team members may experience this difficulty and we tracked it here. So... we can close for now.   Thanks for all the help.   I'll report any other anomalies if it becomes intrusive only.  Cheers!
