### ISSUE TITLE
C:\Users\{UserNAME}\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.50\dist\wallaby.json: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dagmawim** [wallabyjs/public#1123]
### Issue description or question
Tried installing wallaby and the error "C:\Users\name\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.50\dist\wallaby.json: Unexpected token < in JSON at position 0" popped up the first time.

Opened up the files and it had the following in markup( HTML ), 

Access Denied (authentication_failed) 

Your credentials could not be authenticated: "The specified domain is not trusted.". You will not be permitted access until your credentials can be verified.
This is typically caused by an incorrect username and/or password, but could also be caused by network problems.

For assistance, contact your network support team.

### Wallaby.js configuration file
No config file yet.

### Code editor or IDE name and version
Visual Studio 2015 (v 1.11.2 )

### OS name and version
Windows 7 64-bit

### Other Extensions:

Angular TypeScript Snippets for VS Code
angular2-inline
Icon Fonts for Visual Studio Code
jscs-formatter
Quokka.js Visual Studio Code Extension
vscode-icons
Wallaby.js Visual Studio Code Extension
XML Formatting for VS Code
XML Tools for VS Code

**Comment by ArtemGovorov** [comment]
It looks like you are behind some corporate proxy. Try this:
- uninstall the extension,
- add these settings to VS Code settings.json:
```
{
  ...
  "http.proxy": "your corporate proxy address",
  "wallaby.useHttpForDownload": true
}
```
- install the extension.

**Comment by dagmawim** [comment]
Thanks this worked!

**Comment by Janatbek** [comment]
I changed the settings but got following error. 
Error while downloading wallaby.js version file: connect ECONNREFUSED 137.201.129.1:80

**Comment by ArtemGovorov** [comment]
@Janatbek Please double check if you've correctly specified your proxy settings. If the proxy settings are correct, unfortunately there's not much else I can suggest other than contacting your IT department and asking them to whitelist: `http://update.wallabyjs.com/`,  `https://update.wallabyjs.com/`, `http://s3.amazonaws.com/wallaby-downloads/`, `https://s3.amazonaws.com/wallaby-downloads/`.

**Comment by ArtemGovorov** [comment]
@Janatbek Try specifying not just `http.proxy`, but also `https.proxy`:

```
{
  ...
  "http.proxy": "your corporate proxy address",
  "https.proxy": "your corporate proxy address",
  "wallaby.useHttpForDownload": true
}
```
