### ISSUE TITLE
Wallaby.js with angular-seed-advanced

### ISSUE THREAD

**Issue by phamduongnhatnam** [wallabyjs/public#1128]
### Issue description or question
Hi, I just purchased the wallaby.js license and trying to make it works with [angular-seed-advanced](https://github.com/NathanWalker/angular-seed-advanced) repo. I checked the https://github.com/wallabyjs/ngCliWebpackSample repo for example but it look like the project structure is not well config for me. Please help me to make wallaby.js work with this starter.
### Wallaby.js configuration file
I don't know how to setup the tsconfig.spec.json file
```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
	require('./tsconfig.json').compilerOptions,
	require('./src/client/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

	var webpackPostprocessor = wallabyWebpack({
		entryPatterns: [
			'src/client/wallabyTest.js',
			'src/client/**/*spec.js'
		],

		module: {
			loaders: [
				{test: /\.css$/, loader: 'raw-loader'},
				{test: /\.html$/, loader: 'raw-loader'},
				{test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
				{test: /\.json$/, loader: 'json-loader'},
				{test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
				{test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
				{test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
				{test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
			]
		},

		resolve: {
			modules: [
				path.join(wallaby.projectCacheDir, 'src/client/app'),
				path.join(wallaby.projectCacheDir, 'src/client')
			]
		}
	});

	return {
		files: [
			{pattern: 'src/client/**/*.ts', load: false},
			{pattern: 'src/client/**/*.d.ts', ignore: true},
			{pattern: 'src/client/**/*.css', load: false},
			{pattern: 'src/client/**/*.less', load: false},
			{pattern: 'src/client/**/*.scss', load: false},
			{pattern: 'src/client/**/*.sass', load: false},
			{pattern: 'src/client/**/*.styl', load: false},
			{pattern: 'src/client/**/*.html', load: false},
			{pattern: 'src/client/**/*.json', load: false},
			{pattern: 'src/client/**/*spec.ts', ignore: true}
		],

		tests: [
			{pattern: 'src/client/**/*spec.ts', load: false}
		],

		testFramework: 'jasmine',

		compilers: {
			'**/*.ts': wallaby.compilers.typeScript(compilerOptions)
		},

		env: {
			kind: 'electron'
		},

		postprocessor: webpackPostprocessor,

		setup: function () {
			window.__moduleBundler.loadTests();
		},

		debug: true
	};
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I have created the working config for you based on the config you're trying to make work. You'll need to:
- [install some dependencies](https://gist.github.com/ArtemGovorov/40fe0cf6882dcafcb307645744fa4188#file-npm),
- add [`wallaby.js`](https://gist.github.com/ArtemGovorov/40fe0cf6882dcafcb307645744fa4188#file-wallaby-js)
- add [`src/client/wallabyTest.ts`](https://gist.github.com/ArtemGovorov/40fe0cf6882dcafcb307645744fa4188#file-wallabytest-ts) file.

With these changes you should get the working wallaby setup

![screen shot 2017-04-21 at 7 21 22 pm](https://cloud.githubusercontent.com/assets/979966/25271539/cbc50330-26c7-11e7-94d8-e9b97270c474.png)

I must say it's pretty strange seed repo, some of the things in there I haven't seen used anywhere else. I'd recommend looking into using much more popular [official Angular CLI tool](https://github.com/angular/angular-cli) (the original config you have referenced works with it).

**Comment by phamduongnhatnam** [comment]
Thanks you a lot, this is very strange repo because it has to support multiple platform. But it is great for me and the others.
