### ISSUE TITLE
feature: ability to put quokka style comments on new line

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1129]
e.g:

```
const css = stylesAsString(stylesheets, outputPath);
/*? css */
```

or, if you're commenting on the immediately following line you can use `$`:
```
const css = stylesAsString(stylesheets, outputPath);
/*? $ */
```

This is useful especially when you're using prettier which will format your code to be no more than a specified number of chars per line, such as 80.

**Comment by faceyspacey** [comment]
Also, along with this it would be nice if you could specify any in-scope variables and it logs. This goes back to a feature request about 2 months ago.

**Comment by ArtemGovorov** [comment]
As a workaround for now, you may use a dummy expression before the comment, like a number or a string literal. For example:

```javascript
const css = stylesAsString(stylesheets, outputPath);

''/*? css */
''/*? stylesheets */
```

**Comment by faceyspacey** [comment]
closing because there's lots of new options now to see values inline
