### ISSUE TITLE
Wallaby App has got mixed up over tests

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1130]
### Issue description or question

Wallaby has got itself confused with one of my tests. I have a test that it's marked as failed which I believe is incorrect, and has instead got itself confused with another test.

![image](https://cloud.githubusercontent.com/assets/1374775/25274809/df74f022-2689-11e7-8786-acdc10912763.png)

Looking at what the test is doing, and where it's failed I'm pretty sure that the yellow line points to the actual failure point. Here's the full stack from the error:

```
TypeError: Cannot set property 'state' of undefined
    at C:\source\mood\pinboards-api\node_modules\mocha\lib\runner.js:577:20
    at done (C:\source\mood\pinboards-api\node_modules\mocha\lib\runnable.js:295:5)
    at Test.<anonymous> (C:\source\mood\pinboards-api\node_modules\mocha\lib\runnable.js:383:7)
    at Test.assert (C:\source\mood\pinboards-api\node_modules\supertest\lib\test.js:179:6)
    at Server.assert (C:\source\mood\pinboards-api\node_modules\supertest\lib\test.js:131:12)
    at Server.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1555:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
    const options = {
        files: [
            "src/**/*.js",
            "package.json",
        ],
        tests: [
            "test/**/*.unit.js",
            "test/**/*.api.js"
        ],
        env: {
            type: "node",
            params: {
                env: "MONGO_URL=mongodb://localhost:27017/MooDEdgeTest",
            },
        },
        debug: true,
        testFramework: "mocha",
        workers: {
            regular: 1,
            initial: 1,
            recycle: true,
        },
        delays: {
            run: 500,
        },
    };

    return options;
};
```

### Code editor or IDE name and version

Sublime Text v3

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment]
Does wallaby app refresh/wallaby restart in Sublime Text help in this case?

**Comment by IPWright83** [comment]
@ArtemGovorov this is more than the Wallaby app - the test view in Sublime was also reporting the wrong test. I ran this a few times and got the same error.

I was trying to get some concrete proof that it was wrong to demonstrate without needing to share all the code. In doing so I've tried including test files one at a time and managed to include them all, reporting correctly, then gone back to a wildcard and it still seems to be behaving at present.

**Comment by IPWright83** [comment]
I have noticed however, that the tests have ran in a different order than the original screenshot, as I guess it's not deterministic even with 1 runner.

**Comment by IPWright83** [comment]
Now they're working, I'm going to struggle getting more information. You might want to close this (as I'm probably not going to get a reproduction for now), and just keep it on the back burner as a confirmation if anyone else see's odd behaviour.

**Comment by ArtemGovorov** [comment]
No worries, must have been some wallaby cache glitch. Thanks for the report anyway!

BTW, If you set [workers count to 1](https://wallabyjs.com/docs/config/workers.html), the tests will run deterministically (always in the same order), not in parallel anymore though.

**Comment by IPWright83** [comment]
@ArtemGovorov hmm, they don't seem to be doing so. This is the running order, with exactly the same setup as when I posted the original screenshot.

![image](https://cloud.githubusercontent.com/assets/1374775/25276214/f0d19224-2690-11e7-80c6-b0985a0cde2b.png)

**Comment by ArtemGovorov** [comment]
Sorry, I'm a bit lost - what's the issue with the order?

**Comment by IPWright83** [comment]
@ArtemGovorov I'm just pointing out, that the order that the tests have run, is not the same as the order the tests ran in my first screenshot, despite the fact my config has a single worker/runner. Unless I've missed something?

**Comment by ArtemGovorov** [comment]
Ah, got it. The order on the second screenshot looks correct to me. The order on the first screenshot must have been affected by the same glitch that had been causing the original issue.

**Comment by IPWright83** [comment]
@ArtemGovorov ok fair enough :)
