### ISSUE TITLE
VS Code Insiders Extension Fails to Install: EPROTO  SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by Barryrowe** [wallabyjs/public#1131]
### Issue description or question
A member of our team is attempting to install the WallabyJS extension, but it keeps failing with the following error after reloading VS Code:

Error while downloading wallaby.js version file: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:c:\jenkins\workspace\electron-win-ia32\vendor\node\deps\openssl\openssl\ssl\s23_clnt.c:794:

I'm on the same VS Code Insiders version, node (7.4.0) and npm (4.4.4) and installed extension v1.0.50 just fine. Other extensions install for them without issue. We have a proxy server, but it is configured correctly.

### Wallaby.js configuration file

NA

### Code editor or IDE name and version

Visual Studio Code Insiders v1.12.0
![image](https://cloud.githubusercontent.com/assets/1013426/25388628/5610deb6-299c-11e7-8fd9-e1326c1b7df2.png)

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Looks like [this VS Code issue related to proxy configuration](https://github.com/Microsoft/vscode/issues/14672). Try this:
- uninstall the extension,
- add these settings to VS Code settings.json:
```
{
  ...
  "http.proxy": "your corporate proxy address",
  "wallaby.useHttpForDownload": true
}
```
- install the extension.

**Comment by jhhoff02** [comment]
Thanks Artem! This worked in addition to changing proxy protocol from "https://" to "http://".

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
