### ISSUE TITLE
Tape, babel polyfill issue

### ISSUE THREAD

**Issue by mrotaru** [wallabyjs/public#1132]
### Issue description or question

I'm trying to run the unit tests in this repository with Wallaby: https://github.com/redux-saga/redux-saga-beginner-tutorial, and getting the following result:

```javascript
0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​ReferenceError: regeneratorRuntime is not defined​​
  at Object.<anonymous> ​sagas.js:4​
  at Object.<anonymous> ​sagas.spec.js:3:0​
```
Not sure what do do about this; I verified that the `babel-polyfill`, `babel-plugin-syntax-async-functions`, `babel-plugin-syntax-async-generators` modules are installed.

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => ({
  files: [
    {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
    'main.js',
    'reducers.js',
    'Counter.js',
    'sagas.js'
  ],
  tests: [ 'sagas.spec.js' ],
  compilers: {
    '*.js': wallaby.compilers.babel()
  },
  workers: { recycle: true },
  testFramework: 'tape',
  env: {
    type: 'node',
    runner: 'node'
  }
})
```

### Code editor or IDE name and version

Visual Studio Code v1.12.0-insider

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
For node.js environment, you need to use [the `setup` function](https://wallabyjs.com/docs/config/bootstrap.html) and just `require` the `babel-polyfill` module:
```javascript
module.exports = (wallaby) => ({
  files: [
    'main.js',
    'reducers.js',
    'Counter.js',
    'sagas.js'
  ],
  tests: [ 'sagas.spec.js' ],
  compilers: {
    '*.js': wallaby.compilers.babel()
  },
  workers: { recycle: true },
  testFramework: 'tape',
  env: {
    type: 'node',
    runner: 'node'
  },
  setup: function () {
   require('babel-polyfill'); // <--
  }
});
```
