### ISSUE TITLE
Unwanted: Line is covered outside tests

### ISSUE THREAD

**Issue by smeijer** [wallabyjs/public#1134]
### Issue description or question
Even uncovered lines are being displayed as covered, with the mention: 
> Line is covered outside tests.

What does this mean, and how can I stop this behavior? I'm 100% sure the affected line is not covered, as the method is beging unused.

![image](https://cloud.githubusercontent.com/assets/1196524/25531228/4bd10414-2c29-11e7-8a4b-6ff2fe66803f.png)

### Versions: 
WebStorm 2017.1
Windows 10
Wallaby v1.0.411 
testFramework: ava

### Wallaby config 

<details>
  <summary>Wallaby config</summary>

```js
const path = require('path');
const fs = require('fs');

process.env.BABEL_ENV = 'test';
process.env.NODE_ENV = 'production';

module.exports = function (wallaby) {
  process.env.NODE_PATH += path.delimiter +
    path.join(wallaby.localProjectDir, 'src', 'node_modules');

  const babelConfig = JSON.parse(fs.readFileSync('./src/.babelrc', 'utf8'));
  babelConfig.babel = require('./src/node_modules/babel-core');
  const babelCompiler = wallaby.compilers.babel(babelConfig);

  return {
    files: [
      'src/server/**/*.js',
      '!src/server/**/*.tests.js',
    ],
    tests: [
      'src/server/**/*.tests.js',
    ],
    compilers: {
      '**/*.js': babelCompiler,
    },
    env: {
      type: 'node',
      params: {
        env: [
          'DEBUG=*,-mocha:*',
          'NODE_ENV=production',
        ].join(';'),
      },
    },
    debug: false,
    testFramework: 'ava',

    setup: () => {
      console.debug = console.log;
      global.React = require('react');

      require('babel-polyfill');

      var debug = require('debug');
      debug.log = console.info.bind(console);
    },
  };
};
```
</details>

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby config?

**Comment by smeijer** [comment]
Sure, added to the OP

**Comment by ArtemGovorov** [comment]
Looks like the issue is specific to babel, w/o babel it's working as expected. Could you please sahre your `.babelrc` and `package.json` (or just that part of dependencies where babel and presets/plugins are listed).

**Comment by smeijer** [comment]
`.babelrc`:

```json
{
  "presets": ["react"],
  "plugins": [
    "react-require",
    "transform-class-properties",
    "transform-export-extensions"
  ],
  "env": {
    "test": {
      "presets": ["es2015", "stage-2", "power-assert"],
      "plugins": [
        ["babel-plugin-espower", {
          "embedAst": true,
          "patterns": [
            "t.truthy(value, [message])",
            "t.falsy(value, [message])",
            "t.true(value, [message])",
            "t.false(value, [message])",
            "t.is(value, expected, [message])",
            "t.not(value, expected, [message])",
            "t.deepEqual(value, expected, [message])",
            "t.notDeepEqual(value, expected, [message])",
            "t.regex(contents, regex, [message])",
            "t.notRegex(contents, regex, [message])"
          ]
        }]
      ]
    }
  }
}
```

`package.json`
```js
dependencies:
    "babel-core": "^6.17.0",
    "babel-eslint": "^6.1.2",
    "babel-plugin-module-resolver": "^2.2.0",
    "babel-plugin-react-require": "3.x.x",
    "babel-plugin-transform-class-properties": "^6.16.0",
    "babel-plugin-transform-export-extensions": "^6.8.0",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2015": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-preset-stage-2": "^6.17.0",

devDependencies:
    "ava": "^0.16.0",
    "babel-plugin-espower": "^2.3.1",
    "babel-preset-power-assert": "^1.0.0",
```

**Comment by smeijer** [comment]
I'm not sure if it is relevant, but ava has a config in package.json too:

```json
"ava": {
    "files": [
      "./imports/modules/**/tests/*.js",
      "./imports/lib/**/tests/*.js",
      "./server/**/*.tests.js"
    ],
    "require": [
      "babel-core/register",
      "babel-polyfill"
    ],
    "babel": "inherit"
  },
  "nyc": {
    "report-dir": "../coverage",
    "temp-directory": "../.nyc_output"
  },
```

**Comment by ArtemGovorov** [comment]
I still haven't got to the bottom of the problem, but it looks like for some reason moving the `es2015` preset up from the `env.test` fixes the issue:

```javascript
  const babelConfig = JSON.parse(fs.readFileSync('./src/.babelrc', 'utf8'));
  babelConfig.babel = require('./src/node_modules/babel-core');
  babelConfig.presets.push(babelConfig.env.test.presets.shift()); // <--
  const babelCompiler = wallaby.compilers.babel(babelConfig);
```

Given that the generated (and executed by wallaby) code is exactly the same in both of the cases, my suspicion is that there's an issue in babel source maps generation.

**Comment by smeijer** [comment]
Doesn't change a thing here. Can I remove compiled cache files from wallaby somewhere?

**Comment by ArtemGovorov** [comment]
The config change (even adding a space) is supposed to clear the cache, so it must be something else.

I have created [this sample repo](https://github.com/ArtemGovorov/wallaby-1134) with your configuration. Once I add the config line, it starts working as expected:

![ts](https://cloud.githubusercontent.com/assets/979966/25559510/ee5ee128-2d7e-11e7-86be-0e3528beea56.gif)

Please have look if the repo is working for you. If it does, please try to bring the missing bits to the repo to reproduce the issue.

**Comment by smeijer** [comment]
I've cloned the repo, did a `yarn install` and ended up with these results. Doesn't seem correct to me.

without the "shift":
![image](https://cloud.githubusercontent.com/assets/1196524/25576484/c2e3ef3e-2e5f-11e7-8042-1643b1cf0c05.png)


with the "shift"
![image](https://cloud.githubusercontent.com/assets/1196524/25576468/9e9436ca-2e5f-11e7-9d29-2a67401bb99a.png)

```js
const foo = bar => ({
  baz: bar
});

const bar = 'baz';

const a = () => {
  console.log('bar');
};

const b = x => {
  return x * x;
};

const c = x => ({
  y: z,
}) ;
```

**Comment by ArtemGovorov** [comment]
> Doesn't seem correct to me

Why? The version with the "shift" looks correct.

```
const foo = bar => ({
  baz: bar
});
const c = x => ({
  y: z,
}) ;
```
are orange because the line is partially covered. `const foo = ...` is an executed region but the `x => ({` part is not executed, so the line is orange (you may click on the square indicator to ss the uncovered regions of a line).

```javascript
const bar = 'baz';
```
is green because whatever can be executed on the line is executed.

```javascript
const b = x => {
  return x * x;
};
```

`const b = ...` is an executed region, so it's green, `return x * x;` is grey because it hasn't been executed.

**Comment by smeijer** [comment]
In that way; you're right. I saw it as the method is not tested. But indeed; than the "Line is covered outside tests" makes sense.

So I must agree. The "shift" fixes the problem.

**Comment by ArtemGovorov** [comment]
Ah, sorry, I didn't address the `Line is covered outside tests` message. The message means that it wasn't a particular test that had caused the line execution.

For example,

```javascript
var a = 0;
var b = () => {
  var c = 0;
};

it('a should be 0', () => {
  expect(a).toBe(0)
  b();
})

it('run b', () => {
  b();
})
```

the `var a = 0;` line will be green (because it is executed), but it is executed not from some tests, but before them, so it'll be `Line is covered outside tests`.

The ` var c = 0;` line on the other hand will be green (as it's also executed), but will also display the 2 tests that is had been executed from.

Hope it makes sense.

**Comment by smeijer** [comment]
Thanks for the explanation. After playing a little around, It seems to be something with the `es2015 preset` or with the `environment presets`. 

This `.babelrc` does not work:
```json
{
  "presets": [],
  "env": {
    "test": {
      "presets": ["es2015"]
    }
  }
}
```

This does:
```json
{
  "presets": ["es2015"]
}
```

**Comment by smeijer** [comment]
Although I now do understand the idea of the cover icon more. The line belowe should not be shown as covered in my opinion. I understand it's correct by the current feature description; but it shouldn't be. 

I think it's worth another github issue / future request, but it can be an idea to show the indirectly covered lines (outside tests) in another green color.

```js
import R from 'ramda';

export const parseFilter = R.converge( // « Line is covered outside tests
  R.pipe, [parseList, parseState, parseRules], // all functions
);
```

`R.converge` returns a new method composed by the given arguments. Although this line is executed, `parseFilter` is in no way tested here.  Perhaps make the icon dark green for "Line is covered outside tests" coverage? And of course not count it in the cover-percentages.

**Comment by ArtemGovorov** [comment]
@smeijer I don't think I understand what you mean.

```javascript
const parseFilter = R.converge(...
```
or generally 

```javascript
const a = b(...)
```
is covered when it is executed. For the code coverage purposes, it's not relevant what is returned from the `b` function.

The code coverage displayed in your example is absolutely correct - it's the way any code tool will display it. Code coverage can't guarantee if something is tested or not - it's just a metric to see what exactly had been executed and what's not.

**Comment by smeijer** [comment]
Or; to not include external libraries now: `a` and `b` should in my opinion not be shown as covered. Their behavior must be tested.

![image](https://cloud.githubusercontent.com/assets/1196524/25578668/42096ed6-2e71-11e7-9109-b1f06bc68792.png)

```js
const pipe = fns => x => fns.reduce((a, f) => f(a), x);
const inc = x => x + 1;
const double = x => x * 2;

const coverPipe = (() => {
  pipe([x => x * 1, x => x + 1])(0);
})();

const coverInc = (() => {
  inc(1);
})();

const coverDouble = (() => {
  double(1);
})();

const a = pipe([inc, double]); // » 18
// a(8); /* ? */

const b = pipe([double, inc]); // » 17
// b(8); /* ? */
```

**Comment by smeijer** [comment]
> Code coverage can't guarantee if something is tested or not - it's just a metric to see what exactly had been executed and what's not.

Aaah, okay. Valid point. Then It's just me misusing the thing to show if the parts has been tested. That's what I love about wallaby. If it's all green, than it's okay. A green light for the `const a` in my post above, is in no way okay though 😞

**Comment by ArtemGovorov** [comment]
> Or; to not include external libraries now: a and b should in my opinion not be shown as covered. Their behavior must be tested.

Code coverage can't possibly guarantee if something is tested or not. It's only about executing certain statements or expressions. Both `a` and `b` variable assignments were executed - it's absolutely correct and expected to see those lines as covered.

No tool can prove if something is (properly) tested or not.

Consider this:

```javascript
var a = (x, y) => {
  return x + y;
};
it('test a', () => {
  a(1, 3);
})
```
All lines will be green. But is it tested? Nope. We just executed all lines, but never asserted/checked anything. Green coverage everywhere can only guarantee you one thing - that everything that is green has been exercised from somewhere.

**Comment by ArtemGovorov** [comment]
> A green light for the const a in my post above, is in no way okay though

Another example:

```javascript
if (condition) {
  a = pipe([inc, double]);
} else {
  a = pipe([inc, double]);
}
```
if `a = ...` line wasn't green, how would one understand which branch of the `if` statement was called?

This is not a wallaby specific thing, it's juts the way code coverage works.

**Comment by smeijer** [comment]
You're totally right. The implementation of the tests cannot be guaranteed. But the fact if there is a test somewhere that makes a call to this function, is already known by Wallaby. As your giving either a message: 

> "Line is covered outside tests" 

or the sources like:

> src/server/a.tests.js  some test description [0 ms]
> src/server/a.tests.js  an other test description [0 ms]

So it would be awesome if the "outside tests" green light could be a little darker green than the "found related tests" green icon. Of course there is still no guarantee that the test is right. But it helps by quickly specifying tests covering the code.

**Comment by ArtemGovorov** [comment]
> So it would be awesome if the "outside tests" green light could be a little darker green than the "found related tests" green icon.

I suppose we could consider this feature. Red/orange indicators for the "outside tests" lines should probably also be darker following the same logic.

**Comment by ArtemGovorov** [comment]
The original issue turned out to be the known issue with babel plugin ordering (wallaby needs to insert its own plugin and its order can not be guaranteed):
https://github.com/babel/babel/issues/5623#issuecomment-293736355
https://github.com/babel/babel/issues/3793
https://github.com/babel/babel/issues/5275
https://github.com/babel/babel/issues/4539

We have fixed the issue in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). The feature request to differently highlight the "outside tests" covered regions was added to our internal list as well.
