### ISSUE TITLE
VS Code Breakpoints

### ISSUE THREAD

**Issue by sgtoj** [wallabyjs/public#1136]
### Issue

It is not possible to see breakpoints markers in VS Code when Wallaby's code coverage markers are enabled. Is it possible to find a solution that allows for the to markers show?

### Code Editor

Latest VS Code and VS Code Insiders

### OS 

Microsoft Windows v. 10.0.16179

**Comment by ArtemGovorov** [comment]
Unfortunately it's a current limitation of the VS Code UI. Here's the issue in the VS Code repo: https://github.com/Microsoft/vscode/issues/5923, feel free to subscribe and vote for it.

Also see https://github.com/wallabyjs/public/issues/279

**Comment by MikeYermolayev** [comment]
@ArtemGovorov Hi, I'm sorry for bringing this up but maybe you know any workarounds? Is it possible to just show/hide wallaby's gutter icons? Or start/stop is the only option here?

**Comment by smcenlly** [comment]
@MikeYermolayev - the best workaround for now is to use the keyboard when running Wallaby. The default keyboard shortcut to toggle breakpoints is `F9`. Does this help?

**Comment by AnasMostefaoui** [comment]
Thank you @smcenlly that saved the day 👍
