### ISSUE TITLE
Issues with wallaby webpack ES6 syntax [VSCode]

### ISSUE THREAD

**Issue by citypaul** [wallabyjs/public#1137]
### Issue description or question
I can't run Wallaby after updates. The ES6 syntax used in the `wallaby-webpack` package brings back errors now.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./test/webpack.test.config');
var babel = require('babel-core');

module.exports = function (wallaby) {
    var webpackPostprocessor = wallabyWebpack(webpackConfig);
    var babelCompiler = wallaby.compilers.babel({babel: babel, plugins: ['rewire'], presets: ['es2015', 'react']});

    return {
        files: [
            {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false, load: false},
            {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false, load: true},
            {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
            {pattern: 'node_modules/react-dom/dist/react-dom.js', instrument: false},
            {pattern: 'node_modules/requirejs/require.js', instrument: false},

            {pattern: 'test/view/lib/window-mocks/mocks.js', instrument: false, load: true},
            // not required if using PhantomJs2 - http://wallabyjs.com/docs/integration/phantomjs2.html
            {pattern: 'lib/**/*.jsx', load: false},
            {pattern: 'lib/model/*.js', load: false},
            {pattern: 'index.jsx', load: false}
        ],

        tests: [
            {pattern: 'test/view/**/*spec.js', load: false}
        ],

        compilers: {
            'index.jsx': babelCompiler,
            'lib/*.jsx': babelCompiler
        },

        postprocessor: webpackPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        },
        
        debug:true
    };
};

```

### Code editor or IDE name and version
Visual Studio Code 1.11.2

### OS name and version
OSX

I'm getting this error:

```
[Error] ​​/Users/paul/workspace/morph-modules/sport-media-collection/node_modules/wallaby-webpack/index.js:30​​
[Error] ​​class WebpackPostprocessor {​​
[Error] ​​^^^^^​​
[Error] ​​SyntaxError: Unexpected reserved word​​
[Error] ​​  at exports.runInThisContext (vm.js:73:16)​​
[Error] ​​  at Module.i._compile (/Users/paul/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.50/wallaby/server.js:15:13541)​​
[Error] ​​  at Module.s.require (/Users/paul/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.50/wallaby/server.js:19:15086)​​
[Error] ​​  at Object.<anonymous> (/Users/paul/workspace/morph-modules/sport-media-collection/wallaby.js:1:84)​​
```

**Comment by citypaul** [comment]
This was working until fairly recently, when I updated Wallaby in VSCode. I should note that I tried running it in IntelliJ (without updating Wallaby), and it's still running in IntelliJ.

**Comment by citypaul** [comment]
My colleague pulled the code down and tried to run it on her machine using Atom, and had the exact same issue. Any advice would be appreciated, thanks!

**Comment by ArtemGovorov** [comment]
The issue doesn't seem to be related to wallaby updates. The wallaby-webpack package had the `class` syntax from day one. 

The reason it's working in IntelliJ may be because it's using ts own version of node.js (that supports the ES6 syntax). 

The reason why it is not working for you is most likely an older version of node.js that you may have installed recently.

Try printing the node version in your config:

```javascript
console.log('Node version: ' + process.version);

var wallabyWebpack = require('wallaby-webpack');
...
```

If it is the issue with the old node version installed as default on your machine, please install a fresh version (you may do it side by side and specify the [node version for wallaby in your editor settings](https://wallabyjs.com/docs/intro/install.html#nodejs-3)).

**Comment by citypaul** [comment]
Thanks for your response. I'm actually on holiday for a week now, so won't get a chance to try this for at least a week, but just wanted to say thanks for the quick response. I'll come back to you when I do try it and let you know how it goes!

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
