### ISSUE TITLE
Support fuse-box

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1140]
@artemgovorov how difficult would it be to implement a custom test runner? Is there any API? I fell in love with fuse-box, which is blazing fast alternative of web pack for typescript lovers. It comes with its own test runner and I like its API a lot. Here is a bit info http://fuse-box.org:3333/page/test-runner

**Comment by ArtemGovorov** [comment]
There's no API at the moment, we add new testing frameworks support ourselves (once a testing framework is popular enough).

**Comment by tomitrescak** [comment]
I guess mapping on to mocha or jest is the only way now right?

**Comment by ArtemGovorov** [comment]
Yes, it is.
