### ISSUE TITLE
Example of how to use wallaby.js with phantomjs or electron?

### ISSUE THREAD

**Issue by hungsu** [wallabyjs/public#1144]
Can we get a very simple example of how to use wallaby to test using a headless browser, including the test?

Like a very simple test that goes to www.google.com and asserts that the image alt tag is "Google".

**Comment by ArtemGovorov** [comment]
I think there's a misunderstanding about the tool's scope. Wallaby is a tool for running your unit tests in a browser or node.js context. If you have some mocha/jasmine/qunit/jest/ava/tape tests - wallaby can run them. So if you have a test, that can be executed in a context of a web page or a node.js app, then wallaby can run it for you.

However, it looks like you're trying to use wallaby for something that has never been supported in the tool - browser automation or E2E type of testing, like Cucumber/Nightwatch/Selenium/Webdriver. Feel free to subscribe to the feature requests:
https://github.com/wallabyjs/public/issues/46
https://github.com/wallabyjs/public/issues/476

You may also be interested to take a look into this experiment of one of our users: https://twitter.com/fuli42/status/824977507153747969 (it's wallaby running in node and using `webdriverio` module).

**Comment by hungsu** [comment]
I still don't understand. When you say WallabyJs supports Electron and Phantom, what exactly can you do with them? https://wallabyjs.com/docs/integration/phantomjs2.html

**Comment by ArtemGovorov** [comment]
> When you say WallabyJs supports Electron and Phantom, what exactly can you do with them?

You can use them as test runners to run your unit tests in a browser environment. For example, if you have this simple jasmine test:

```javascript
it('should work', () => {
  expect(2+2).toBe(4);
});
```

and configured wallaby to run it with PhantomJs/Electron, then wallaby will run it in a context of a web page using PhantomJs/Electron (renderer process) as a browser (to run the page). So you have access to DOM/window/etc. - whatever you can access from your browser web app.

Hope it answers your question.
