### ISSUE TITLE
Extending Wallaby App compare

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1145]
### Issue description or question
Allow the use of the comparison window in the Wallaby App when using alternatives to jest.

We've been using Jest quite extensively, but I often find it's quite slow, and some tests are better just not using snapshots. However the snapshot comparison in the Wallaby app is brilliant. Could you extend it to support other comparisons (for example an equality check within a test?)

e.g.

````
expect({ myObj: "A", name: "Apple" }).toEqual({" myObj: "A", name: "Aardvark" });
````

**Comment by ArtemGovorov** [comment]
Wallaby App already supports it. 

For the test you've provided as an example, here's the output from Wallaby App:

![screen shot 2017-05-05 at 11 30 11 am](https://cloud.githubusercontent.com/assets/979966/25731084/7680e442-3186-11e7-8f10-262d18baadd1.png)

**Comment by IPWright83** [comment]
@ArtemGovorov sorry, I maybe wasn't explicit enough. I was specifically interested in the "Diff" view allowing a side by side comparison for slightly more complex objects. Oddly - it seems to be present in your screenshot, but not when I've just tried it using `Wallaby.js App v1.0.27, Core v1.0.419`:

![image](https://cloud.githubusercontent.com/assets/1374775/25738992/c3fc13f4-3177-11e7-8a2f-219745fa02f6.png)

**Comment by ArtemGovorov** [comment]
@IPWright83 The diff view should also be displayed. Not sure what's going on, it's working for me. Try this simple repo https://github.com/ArtemGovorov/wallaby-1145 I have put together, is the diff showing up for you there?

**Comment by IPWright83** [comment]
@ArtemGovorov yeah - works fine using that rep.

**Comment by ArtemGovorov** [comment]
@IPWright83 Try adding things from your project that the repo is missing. My only guess would be that the version of Jest is different, but it shouldn't matter (if snapshot diff are working for you, then normal objects diffs should work as well).

**Comment by IPWright83** [comment]
I think it's my wrapper causing the problem as I've just noticed it's not there for my other Jest snapshot tests either.

```
/**
     * Wraps the expect checks (for an async test) in a try/catch to work around
     * https://github.com/facebook/jest/issues/2059
     * @param  {Function}   expects     A function with a set of expects within it
     * @param  {Function}   done        The done function
     */
    static jestAsyncDone(expects, done) {
        try {
            expects();
            done();
        } catch (e) {
            done.fail(e);
        }
    }
```

**Comment by ArtemGovorov** [comment]
Have added your helper to the sample repo: https://github.com/ArtemGovorov/wallaby-1145/blob/master/test.js, everything is still working as expected (the diff is displayed).

**Comment by IPWright83** [comment]
Hmm, leave it with my. If I get a chance I'll try and investigate a bit more.
