### ISSUE TITLE
wallabyjs: ​​​​​ReferenceError: Can't find variable: Promise/System

### ISSUE THREAD

**Issue by mobiledeve** [wallabyjs/public#1146]
### Issue description or question
I was usinh Angular 2, it was working fine.
After upgrade my project to Angular 4, I got these errors when starting wallabyjs:
In output windows of Visual Studio 2015, "Show output from: Wallaby.js - Failing Tests"

​​​​​ReferenceError: Can't find variable: Promise
		at node_modules/systemjs/dist/system.js:5
ReferenceError: Can't find variable: System
		at systemjs.config.js:6
TypeError: undefined is not a constructor (evaluating 'System.config')
ReferenceError: Can't find variable: Promise
		at node_modules/systemjs/dist/system.js:5
ReferenceError: Can't find variable: System
		at systemjs.config.js:6
TypeError: undefined is not a constructor (evaluating 'System.config')
at http://localhost:3664/wallaby_sandbox0.html:12

### Wallaby.js configuration file
// Configuration for the Wallaby Visual Studio Code testing extension
// https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode
// Note: Wallaby is not open source and costs money

module.exports = function () {
  return {
    files: [
      // System.js for module loading
      {pattern: 'node_modules/systemjs/dist/system.js', instrument: false},
      {pattern: 'systemjs.config.js', instrument: false},
      {pattern: 'systemjs.config.extras.js', instrument: false},

      // Polyfills
      {pattern: 'node_modules/core-js/client/shim.min.js', instrument: false},
      {pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false},

      // zone.js
      {pattern: 'node_modules/zone.js/dist/zone.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/long-stack-trace-zone.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/proxy.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/sync-test.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/jasmine-patch.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/async-test.js', instrument: false},
      {pattern: 'node_modules/zone.js/dist/fake-async-test.js', instrument: false},

      // application (but not specs) loaded via module imports
      {pattern: 'app/**/*+(ts|html|css)', load: false},
      {pattern: 'app/**/*.spec.ts', ignore: true},

      {pattern: 'testing/**/*+(ts|html|css)', load: false},
    ],

    tests: [
      {pattern: 'app/**/*.spec.ts', load: false}
    ],

    middleware: function (app, express) {
      app.use('/node_modules', express.static(require('path').join(__dirname, 'node_modules')));
    },

    testFramework: 'jasmine',

    debug: true,

    bootstrap: bootstrap
  };
};

// Like karma-test-shim.js
function bootstrap (wallaby) {
  wallaby.delayStart();

  System.config({
    // Extend usual application package list with test folder
    packages: { 'testing': { main: 'index.js', defaultExtension: 'js' } },

    // Assume npm: is set in `paths` in systemjs.config
    // Map the angular testing umd bundles
    map: {
    	'@angular/core/testing': 'npm:@angular/core/bundles/core-testing.umd.js',
      '@angular/common/testing': 'npm:@angular/common/bundles/common-testing.umd.js',
      '@angular/compiler/testing': 'npm:@angular/compiler/bundles/compiler-testing.umd.js',
      '@angular/platform-browser/testing': 'npm:@angular/platform-browser/bundles/platform-browser-testing.umd.js',
      '@angular/platform-browser-dynamic/testing': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
      '@angular/http/testing': 'npm:@angular/http/bundles/http-testing.umd.js',
      '@angular/router/testing': 'npm:@angular/router/bundles/router-testing.umd.js',
      '@angular/forms/testing': 'npm:@angular/forms/bundles/forms-testing.umd.js',
      'angular2-moment/module': 'node_modules/moment/index.js',
    },
  });

  System.import('systemjs.config.js')
    .then(importSystemJsExtras)
    .then(initTestBed)
    .then(initTesting);

  /** Optional SystemJS configuration extras. Keep going w/o it */
  function importSystemJsExtras(){
    return System.import('systemjs.config.extras.js')
    .catch(function(reason) {
      console.log(
        'Warning: System.import could not load the optional "systemjs.config.extras.js". Did you omit it by accident? Continuing without it.'
      );
      console.log(reason);
    });
  }

  function initTestBed(){
    return Promise.all([
      System.import('@angular/core/testing'),
      System.import('@angular/platform-browser-dynamic/testing')
    ])

    .then(function (providers) {
      var coreTesting    = providers[0];
      var browserTesting = providers[1];

      coreTesting.TestBed.initTestEnvironment(
        browserTesting.BrowserDynamicTestingModule,
        browserTesting.platformBrowserDynamicTesting());
    })
  }

  // Load all spec files and start wallaby
  function initTesting () {
    return Promise.all(
      wallaby.tests.map(function (specFile) {
        return System.import(specFile);
      })
    )
    .then(function () {
      wallaby.start();
    })
    .catch(function (e) {
      setTimeout(function () {
        throw e;
      }, 0);
    });
  }
}

```javascript
tsconfig.json

{
  "compilerOptions": {
    "target": "es2015",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": [
      "./node_modules/@types/"
    ]
  },

  "exclude": [
    "node_modules/*"
  ]
}

================

systemjs.config.js: 

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api',
      'angular2-moment/module': 'node_modules/moment/moment.js',
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'angular-in-memory-web-api': {
        main: './index.js',
        defaultExtension: 'js'
      }
    }
  });
})(this);



==============
package.json:


{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "docker-build": "docker build -t ng2-quickstart .",
    "docker": "npm run docker-build && docker run -it --rm -p 3000:3000 -p 3001:3001 ng2-quickstart",
    "pree2e": "npm run webdriver:update",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "webdriver:update": "webdriver-manager update"
  },
  "keywords": [],
  "author": "",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/angular/angular.io/blob/master/LICENSE"
    }
  ],
  "dependencies": {
    "@angular/animations": "^4.1.1",
    "@angular/common": "^4.1.1",
    "@angular/compiler": "^4.1.1",
    "@angular/compiler-cli": "^4.1.1",
    "@angular/core": "^4.1.1",
    "@angular/forms": "^4.1.1",
    "@angular/http": "^4.1.1",
    "@angular/platform-browser": "^4.1.1",
    "@angular/platform-browser-dynamic": "^4.1.1",
    "@angular/platform-server": "^4.1.1",
    "@angular/router": "^4.1.1",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "@angular/upgrade": "^2.0.2",
    "@types/core-js": "^0.9.41",
    "angular-in-memory-web-api": "^0.1.17",
    "bootstrap": "^3.3.7",
    "canonical-path": "0.0.2",
    "concurrently": "^3.4.0",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "jasmine-core": "^2.5.2",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.1.1",
    "karma-cli": "^1.0.1",
    "karma-htmlfile-reporter": "^0.3.5",
    "karma-jasmine": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "lightbox2": "^2.9.0",
    "lite-server": "^2.3.0",
    "lodash": "^4.17.4",
    "ng2-file-upload": "^1.2.1",
    "phantomjs": "^2.1.7",
    "protractor": "^4.0.14",
    "reflect-metadata": "^0.1.10",
    "rimraf": "^2.6.1",
    "rxjs": "^5.3.1",
    "systemjs": "^0.20.12",
    "tslint": "^3.15.1",
    "typescript": "^2.3.2",
    "zone.js": "^0.8.10"
  },
  "repository": {}
}

```

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version

Windows 8.1

**Comment by ArtemGovorov** [comment]
Looks like system.js in its latest version is using native Promise. You may either add a polyfill for Promise into the `files` list (before system.js file), or, which is recommended, switch to Chrome/Electron runner [as described here in the docs](https://wallabyjs.com/docs/integration/electron.html).

**Comment by mobiledeve** [comment]
Thank you for the quick response! I'll try your suggestion.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
