### ISSUE TITLE
Files Recursive Glob not selecting all files

### ISSUE THREAD

**Issue by KeKs0r** [wallabyjs/public#1147]
### Issue description or question
I have a test case that calculates the size of a folder and its contents (recursively with several levels)

Since I don't want these files be manipulated by wallaby and just read from the file system I excluded them from instrumentation:
```
      { pattern: 'test/fixtures/**/*.*', instrument: false }
```
But it seems that it is not excluding all files, because my file folder sizes differ. And they only differ when running with wallaby. If I run my test cases without wallaby, they pass just fine.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      { pattern: 'test/testUtil.js', instrument: false },
      { pattern: 'test/fixtures/**/*.*', instrument: false }
    ],

    tests: [
      'test/*.spec.js',
      'test/**/*.spec.js'
    ],
    testFramework: 'ava',
    env: {
      type: 'node'
    },

    delays: {
      run: 500
    },
    debug: true
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.htm^l
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.x

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Try [opening Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) after starting wallaby, search for `File cache:`, opening the folder that you find + `instrumented/test/fixtures/`. This is the place wallaby copies the files over to. Try comparing it with your local folder to see what exactly is not copied over.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
