### ISSUE TITLE
screenshot always fails with electron but works ok with phantomjs ...? 

### ISSUE THREAD

**Issue by jkennerley** [wallabyjs/public#1149]
### Issue description or question
screenshot  + visual studio + electron  + es6 +  

### Wallaby.js configuration file
{

  "files": [
    "Mashid\\wwwroot\\app\\learnts\\*.js"
  ],

  "tests": [
    "-EXCLUDED-Mashid.UnitTest\\wwwroot\\app\\learnts\\*.UnitTest.Jasmine.js",
    "-EXCLUDED-Mashid.UnitTest\\wwwroot\\app\\es2015\\*.UnitTest.Jasmine.js",
    "Mashid.UnitTest\\wwwroot\\app\\**\\*.UnitTest.Jasmine.js"

  ],

  "commented-out-env": { "kind": "electron" },

  "env": { "kind": "electron" }

}

```javascript
// paste your config here

        // // works fine when with phantomejs "-XX-env": { "kind": "electron" }
        // it("screenshot-with-phantom-ok", function () {
        //     // with phantom ...
        //     var element = document.getElementsByTagName("body");
        //     element[0].style.background = '#500';
        // ALT-SHIFT-F10 never always yields coloured bgnd
        // });

        // does not work fine when with electron"env": { "kind": "electron" }
        it("screenshot-with-electron-not-ok", function () {
            let x = 1; // es2015(es6) will work with electron
            // with electron ...
            var element = document.getElementsByTagName("body");
            element[0].style.background = '#550';
            // ALT-SHIFT-F10 never yields coloured bgnd
        });

```

### Code editor or IDE name and version

Visual Studio 2017

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
It is expected. Screenshot capturing was never supported in the Electron runner, only in PhantomJs runner.

**Comment by jkennerley** [comment]
;-), ok thanks for the reply.
I thought the was  a way of making this work.
I swapped to running the tests in electron, rather than phantomjs because some es2015 language construct were causing exceptions when running tests ..

**Comment by Gosha** [comment]
How come the Electron runner doesn't support screenshots?

**Comment by ArtemGovorov** [comment]
@Gosha While experimenting with adding the feature for Electron we found that it was slowing down every test run, so we have put on hold implementing it for Electron.
