### ISSUE TITLE
Wallaby executes tests with Jest only from single folder matching the pattern

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#115]
If you try to run Wallaby on the same repo I provided yesterday (https://github.com/endragor/wallaby-jest-sample), you'll see that only tests under `app/mul/__tests__/` are executed, but tests under `app/sum/__tests__/` are not. The pattern looks correct to me.
![not_everything_executed](https://cloud.githubusercontent.com/assets/2417849/7701588/26cfdc24-fe42-11e4-8774-c715e9a41af3.png)

**Comment by ArtemGovorov** [comment]
Can't reproduce this one:
![screen shot 2015-05-19 at 9 24 12 pm](https://cloud.githubusercontent.com/assets/979966/7701743/76814eb2-fe6d-11e4-83ca-e85dc0f49c38.png)
Are you just starting wallaby and it happens?

**Comment by endragor** [comment]
Yes, I'm just starting it and it happens. These are node and npm versions that I use:
```
$ node -v
v0.10.38
$ npm -v
2.10.0
```
Is there anything else that may affect the behaviour?

**Comment by endragor** [comment]
Debug log: https://gist.github.com/endragor/72cc8bbcd0a1e27b0b7f

**Comment by ArtemGovorov** [comment]
Installed node v0.10.38, still no luck reproducing it. Could you please check that the issue didn't go away after resetting caches in https://github.com/wallabyjs/public/issues/112?

If it still doesn't work, could you please try removing `runner` and `params` from `env`, so that it looks like:
```
env: {
      type: 'node'
    }
```
and re-installing node modules. In this case wallaby will uses its own io.js to run Jest, would be interesting to see if it works or not.

**Comment by endragor** [comment]
I reported this issue already after performing actions from #112.

Shouldn't I reinstall node_modules with the same io.js as used in Wallaby? Anyway, I don't think Jest supports it well enough - it outputs warnings even if you use node different from 0.10.

When I tried the actions you described, I started getting `Error: Module did not self-register.` from within jest libs.

Also, when I reopened the project now to try this, errors from #112 have returned:
![errors_112](https://cloud.githubusercontent.com/assets/2417849/7704387/79384f54-fe57-11e4-9993-a5573fc711ac.png)

**Comment by ArtemGovorov** [comment]
Interesting. Ok, I'll keep trying to reproduce it. Jest seems to be using some cache, it may affect wallaby. Anyway, for now `workers: {recycle: true}` should help avoiding these issues all together.

**Comment by endragor** [comment]
`workers: {recycle: true}` helps avoid #112, but not this one. I have not found a workaround for this issue.

**Comment by ArtemGovorov** [comment]
@endragor Ah, ok. Will investigate the issue ASAP.

**Comment by ArtemGovorov** [comment]
Ok, thanks to your debug log gist I was able to reproduce the environment (you have been testing wallaby on 2 core machine or with modified workers.initial/regular setting, I have adjusted workers settings to use 2 core and the issue came out).

Please check if the issue is fixed now.

**Comment by endragor** [comment]
Cool, this issue is fixed now!

In my real project I have another bug - each test gets executed dozens of times, so I get `Finished executing 32386 affected test(s)` when I just have around a hundred tests at the moment. When I make a change to a test file that contains 2 tests, the log reads `Finished executing 864 affected test(s)`.
I'll file another issue when/if I can succeed in reproducing this on the sample project.

**Comment by ArtemGovorov** [comment]
Do you think it really executes those tests that many times or executes once and just reports the number incorrectly? I'm assuming 864 tests would take noticeably longer to execute.

**Comment by endragor** [comment]
According to the debug log, it really executes them. See #118 for details (still cannot reproduce in the sample project).
