### ISSUE TITLE
Support Storybook Storyshoots

### ISSUE THREAD

**Issue by alinvdumitru** [wallabyjs/public#1150]
### Issue description or question
We recently introduced storyshots in our project since we were using storybook for a while. Tests are passing just fine in npm jest CLI and I'm trying to get the same thing going in wallaby. However, this error is popping up:

```[Error] Test without test file id, most likely the test did not run, OR the test/test body is in the file that is not in the `tests` list in the configuration file { testFileIdCanNotBeDetermined: 'with required props',​​
​​[Error]   id: 100010,​​
​​[Error]   log: undefined,​​
​​[Error]   filesInvolved: ​​
​​[Error]    [ 'action.story.jsx',​​
​​[Error]      'action.jsx' ] }​​```

I'm wondering if storyshoots implementation is supported at all.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

return {
    files: [
        {pattern: 'src/app/**/*.jsx*', load: false},
        {pattern: 'src/app/**/*.js*', load: false},
        {pattern: 'src/app/core/excel/**/*', ignore: true},
        {pattern: 'src/**/__tests__/*.js', ignore: true },
        {pattern: 'src/**/__tests__/*.jsx', ignore: true },
        {pattern: '.storybook/config.js', load: false},
        {pattern: 'src/assets/css/main.styl', load: false}
    ],
    env: {
        type: 'node',
        runner: 'node',
        params: {
            runner: '--harmony'
        }
    },

    tests: [
        {pattern: 'src/**/__tests__/*.jsx'},
        {pattern: 'src/**/__tests__/*.js'}
    ],

    testFramework: 'jest',

    compilers: { 
      '**/*.js': wallaby.compilers.babel(),
      '**/*.jsx': wallaby.compilers.babel(),
      '.storybook/*.js': wallaby.compilers.babel()
    },

    debug: true
  };
};

```

### Code editor or IDE name and version
Visual Studio Code v1.x

### OS name and version
Linux

**Comment by ArtemGovorov** [comment]
I haven't heard about storyshots before, so wouldn't be surprised if it's not supported. Could you please share a sample GitHub repo with a simple test or two so I could have a look into why it's not working and what's required to make it work?

**Comment by ArtemGovorov** [comment]
Just looking into the error message, `action.story.jsx` is this your test file with tests? Where is the `with required props` test located?

**Comment by alinvdumitru** [comment]
```action.story.jsx``` is a storybook story. We use storybook to develop UI components in isolation, storyshots being the integration of Jest snapshot testing & storybook.

Sample story:
```javascript
import React from 'react';
import { storiesOf, action, linkTo } from '@kadira/storybook';
import {TestComponent} from './../src/component';

storiesOf('TestComponent', module)
    .add('TestComponent render', () => {
        return (
            <TestComponent />
        );
    });
```

Repository with reproducible example based on wallaby snapshot example can be found here
[Wallaby+Jest+Storyshots](https://github.com/alinvdumitru/wallaby-jest-storyshots-example)

**Comment by ArtemGovorov** [comment]
Thanks for the sample. There was a small issue with Jest integration which is fixed and published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Please update the core and try, the issue should disappear.
