### ISSUE TITLE
Does not start without AppData\Local\Temp\.wallaby

### ISSUE THREAD

**Issue by RussKie** [wallabyjs/public#1151]
### Issue description or question
I have an existing installation 1.0.26 which I haven't used for awhile. When tried to run it, it wouldn't run nor would give any error messages.
Whilst troubleshooting I saw that it unsuccessfully attempted to write a log `C:\Users\<username>\AppData\Local\Temp\.wallaby\wallaby-<timestamp>.log`. The folder ...\Temp\.wallaby wasn't there, so it failed.
Once I've manually created .wallaby folder it all went to normal and started working.

**Expected:**
Wallaby must create any missing folders itself or, at the very least, provide a clear error message what is wrong and how to remedy it.

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
The issue was fixed a while ago: https://github.com/wallabyjs/public/issues/884#issuecomment-263541968, please update to the latest version to get the fix.
