### ISSUE TITLE
Wallaby fails with assets

### ISSUE THREAD

**Issue by superkew** [wallabyjs/public#1157]
### Issue description or question
I've had wallaby working in the past, and now using the clicker example it works except my assets don't load. I'm sure it is a quick fix from your side, I assume the path needs to be altered somehow.

I tried using a file loader instead of a null loader but it still doesn't work.

See this repo (forked from your fork of clicker)
https://github.com/superkew/clicker

I added a simple asset and the loader isn't pulling them in.
`Module not found: Error: Can't resolve './assets/github.svg' in './src/pages/page2'ModuleNotFoundError: Module not found: Error: Can't resolve './assets/github.svg' ...`

### Wallaby.js configuration file

```javascript
same as repo
```

### Code editor or IDE name and version

NA

### OS name and version

OSX

**Comment by superkew** [comment]
I think I resolved the asset issue.

I added a node-noop plugin. Is this the best way to resolve this?

```
var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');
var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*.spec.js'
  ],

  module: {
    loaders: [
      {test: /\.html$/, loader: 'html-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/}
    ]
  },

  plugins: [
    new webpack.NormalModuleReplacementPlugin(/\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/, 'node-noop')
  ]
});
```

**Comment by ArtemGovorov** [comment]
> I added a node-noop plugin. Is this the best way to resolve this?

Yes, that's what we [recommend in the docs](https://wallabyjs.com/docs/integration/webpack.html#normalmodulereplacementplugin).

Alternatively, you could also add the `.svg` pattern to [the `files` list](https://github.com/superkew/clicker/blob/master/wallaby.js#L20), wallaby needs to [know about all files used in tests](https://wallabyjs.com/docs/config/files.html).

**Comment by gisu** [comment]
Sorry for reopening the issue. But I currently have similar problems with Nuxt. I bind SVGs to the elements using `require`. Jest runs fine, only Wallaby has his problems. I'm a bit lost because I don't know where to attach the `wallabyPostprocessor`.

```js
module.exports = (wallaby) => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({
    presets: [['@vue/app', { modules: 'commonjs' }]]
  });

  const wallabyWebpack = require('wallaby-webpack');
  const webpack = require('webpack');
  const wallabyPostprocessor = wallabyWebpack({
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/, 'node-noop')
    ]
  });

  return {
    files: ['client/**/*', 'jest.config.js', 'package.json', '!**/*.spec.js'],

    tests: ['client/**/*.spec.js', '!client/tests/e2e/'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      'client/**/*.js': compiler,
      'client/**/*.vue': require('wallaby-vue-compiler')(compiler)
    },

    preprocessors: {
      'client/**/*.vue': (file) => require('vue-jest').process(file.content, file.path)
    },

    setup: function(wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config');
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',

    debug: true
  };
};

```
