### ISSUE TITLE
Testing a Node server with Mocha, TypeScript, TypeScript paths and Webpack

### ISSUE THREAD

**Issue by RobertYoung** [wallabyjs/public#1158]
### Issue description or question
Hi,

I'm trying to get wallaby to work with my backend unit tests. I am using webpack to bundle the files and have started implementing TypeScript paths. This requires a change in the tsconfig and also adding the alias to the resolve.alias property in webpack.

The goal is to use the syntax @util/, which works fine when building and testing the project without wallaby. However, wallaby does not resolve this. I can half get it to work with just util/ by amending the NODE_PATH variable:

```javascript
process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir
```

But this requires to go up a directory, so it's myProject/util/ instead, due to a util npm module already installed in node_modules.

This would work okay if I can use the wallaby-webpack and test a node application, but I ran into the same issues as this issue #383. 

Is it possible to test a node application with webpack and wallaby?

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var wallabyPostprocessor = wallabyWebpack({
    resolve: {
      alias: {
        "@util": 'modules/util'
      }
    },
  }
);

module.exports = function (wallaby) {
  return {
    files: [
      // Source code
      { pattern: 'modules/**/server/js/**/*.ts', load: false }
    ],

    tests: [
      // Unit tests
      'modules/**/server/test/**/*.ts'
    ],

    testFramework: 'mocha',

    env: { type: 'node' },

    postprocessor: wallabyPostprocessor,

    debug: true
  };
};
```

### tsconfig
```json
{
  "compilerOptions": {
    "baseUrl": "",
    "target": "es5",
    "paths": {
      "@util/*": ["modules/util/*"],
    }
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.12.1

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
Wallaby doesn't support webpack in node environment, only in browser environment. The good news is that you don't really need webpack for what you're doing (it'll only slow things down anyway). You may configure wallaby like this by using [the setup function](https://wallabyjs.com/docs/config/bootstrap.html) and patching `require` to do any aliasing:

```javascript
module.exports = function (wallaby) {

  process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;

  return {
    files: [
      // Source code
      { pattern: 'modules/**/server/js/**/*.ts', load: false }
    ],

    tests: [
      // Unit tests
      'modules/**/server/test/**/*.ts'
    ],

    env: { type: 'node' },

    setup: function () {
      var Module = require('module').Module;
      var originalRequire = Module.prototype.require;
      if (!originalRequire._replaced) {
        Module.prototype.require = function (filePath) {
          // may add more mappings here
          filePath = filePath.replace('@util', 'modules/util');

          return originalRequire.call(this, filePath);
        };
        originalRequire._replaced = true;
      }
    },

    debug: true
  };
};
```

Let me know if it addresses your question.

**Comment by RobertYoung** [comment]
That's worked! Thank you so much for your time and help :)
