### ISSUE TITLE
Advanced logging in CoffeeScript

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#1159]
### Issue description or question

I'm trying to use the new advanced logging features but the syntax /*?.*/ doesn't work in CoffeeScript

![image](https://cloud.githubusercontent.com/assets/656739/26053722/cb5e27b2-3961-11e7-8de4-1f99f33cc5e9.png)

### Code editor or IDE name and version
WebStorm

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
The advanced logging feature works by parsing JavaScript comments. You're trying to add JavaScript comment into CoffeeScript code, If CoffeeScript supported preserving line comments in generated JavaScript, then using CoffeeScript comments like `#?.` would work. 

Unfortunately CoffeeScript doesn't preserve any inline comments in the generated JavaScript code:

https://github.com/jashkenas/coffeescript/issues/2365#issuecomment-23604937
https://github.com/jashkenas/coffeescript/issues/4189
http://stackoverflow.com/questions/20069232/coffeescript-comments-in-javascript-output

This blocks us from making it work in wallaby for CoffeeScript. At least until preserving line comments is implemented in CoffeeScript compiler:  https://github.com/jashkenas/coffeescript/issues/2365.
