### ISSUE TITLE
Add example of __mocks__ to Jest example

### ISSUE THREAD

**Issue by Sanjo** [wallabyjs/public#116]
It is helpful for new users to get started. The __mocks__ folder must be included under files to work without errors in my case.

```javascript
module.exports = function () {

  return {
    files: [
      'bin/*.js',
      'lib/**/*.js',
      '__mocks__/*.js'
    ],

    tests: [
      '__tests__/*.js'
    ],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: '--harmony'
      }
    },

    testFramework: 'jest@0.4.3'

    // Use bootstrap function
    //bootstrap: function (wallaby) {
    //  wallaby.testFramework.configure({
    //    // https://facebook.github.io/jest/docs/api.html#config-options
    //  });
    //}
  };
};
```

**Comment by ArtemGovorov** [comment]
Done. All of the files used in tests (except node modules) must be included to the `files` list as wallaby iso using its own cache.  Added this note to the https://github.com/wallabyjs/wallaby-jest-sample/blob/master/README.md#configure-wallabyjs section.
