### ISSUE TITLE
VSCode not updating when doing change that should break - file is changed however

### ISSUE THREAD

**Issue by einari** [wallabyjs/public#1164]
### Issue description or question

I have an issue with VSCode not reflecting the change of tests. The file is getting changed, you can see the console go and in a browser I can see the change happen. Its just the IDE not getting updated, even though it says in the console it sent it to the IDE.

I've made a [video](https://dolittle-my.sharepoint.com/personal/einar_dolittle_com/_layouts/15/guestaccess.aspx?docid=02b1008f4e4414564afaae5e04283701c&authkey=AW142CEFR1Up65_wvk33cXs).

You can also find the project [here](https://github.com/dolittle/javascript.core)

Also worth noting; not getting classmates - thought this was default added to babel configuration. I do have in the `.babel.rc`file the `sourceMap`property set to `inline`

### Wallaby.js configuration file

```javascript
"use strict";
var cachebust = require('express-cachebust');

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: "!**/jspm_packages", instrument: false },
            { pattern: "jspm_packages/system.js", instrument: false },
            { pattern: "node_modules/chai/chai.js", instrument: false },
            { pattern: "node_modules/chai-as-promised/chai-as-promised.js", instrument: false },
            { pattern: "node_modules/sinon/pkg/sinon.js", instrument: false },
            { pattern: "jspm.config.js", instrument: false },
            { pattern: "json.js", instrument: false, load: false },
            { pattern: "package.json", instrument: false, load: false },
            { pattern: "Specifications/**/given/*.js", load: false },
            { pattern: "!Source/**/jspm_packages/**/*.js", instrument: false },
            { pattern: "Source/**/*.js", load: false }
        ],
        tests: [
            { pattern: "!Specifications/**/given/*.js", load: false },
            { pattern: "Specifications/**/*.js", load: false }
        ],

        compilers: {
            "**/*.js": wallaby.compilers.babel({
                babelrc: true
            })
        },

        env: {
            kind: "electron"
        },

        middleware: (app, express) => {
            app.use(cachebust("/"));
            app.use("/jspm_packages", express.static(require("path").join(__dirname, "jspm_packages")));
        },

        setup: function (wallaby) {
            wallaby.delayStart();

            window.expect = chai.expect;
            var should = chai.should();

            System.import("./package.json!./json.js").then(function (pkg) {

                console.log("Package loaded");

                var systemConfig = {
                    transpiler: false,
                    packages: {
                        "/": {
                            defaultExtension: "js",
                            format: "cjs",
                            meta: {
                                "*": {
                                    
                                }
                            }
                        }
                    }
                };

                System.config(systemConfig);

                var promises = [];
                for (var i = 0, len = wallaby.tests.length; i < len; i++) {
                    console.log("Import : "+wallaby.tests[i]);
                    promises.push(System['import'](wallaby.tests[i]));
                }

                Promise.all(promises).then(function () {
                    wallaby.start();
                }).catch(function (e) {
                    setTimeout(function () {
                        throw e;
                    }, 0);
                });

            });
        },

        testFramework: "mocha",

        debug: true
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.12.2

### OS name and version

macOS Sierra 10.12.4

**Comment by ArtemGovorov** [comment]
Thanks for providing the details and the repo. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by einari** [comment]
Great. At least my tests are now being reported correctly - but it only seem to have fixed half of the story (Or my configuration is wrong). If you look at the [Video](https://dolittle-my.sharepoint.com/personal/einar_dolittle_com/_layouts/15/guestaccess.aspx?docid=02fc175a86f07447a9f81849bec818f85&authkey=AbbSL0uo60z2FoLwcQqm3W4) - you'll see that the unit under test does not reflect any of the change. Having to restart wallaby to get it. 

Is there something I'm doing with my setup that you'd consider bad practice?

**Comment by ArtemGovorov** [comment]
Thanks for the note and for the video. Indeed the issue (it's related to System.js integration) wasn't fully fixed. The issue is now fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
