### ISSUE TITLE
Jasmine DEFAULT_TIMEOUT_INTERVAL not respected

### ISSUE THREAD

**Issue by ericmhalvorsen** [wallabyjs/public#1166]
Hi Everyone,

First want to say this is by far the best and most functional JS test runner that I've used. So thank you for the work that you've done, I'm in the process of switching over to this solution in favor of Karma, etc.

That said, I am having an issue with overriding the official Jasmine settings for test timeout as described here: http://stackoverflow.com/questions/34665214/cant-set-timeout-for-jasmine

The official documentation also confirms that this is the correct way to override the setting, and even when I look using your `debug: true` setting, I can only see that the value I set matches the value I ask for in the test - 20000. See screenshot:

<img width="544" alt="screen shot 2017-05-21 at 7 13 39 pm" src="https://cloud.githubusercontent.com/assets/2429150/26288153/a5a0a76e-3e59-11e7-904e-85518233f5ce.png">

As you can see, the amount of time waited is still 5000ms regardless of the jasmine object telling me I have set it to 20000. As I can't see quite how this value is loaded by wallaby (or if there are conflicting packages on my system causing this) I was hoping you might be able to shed some light. I've tried a number of solutions at this point.

Thanks again for this product, if I can get this working I will most definitely be switching over.

Eric

**Comment by ericmhalvorsen** [comment]
A copy of my wallaby.conf.js - Also using Atom.

var angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');
```
module.exports = function (wallaby) {
  return {
    debug: true,
    files: [
      'node_modules/jquery/dist/jquery.js',
      'node_modules/underscore/underscore.js',
      'node_modules/angular/angular.js',
      'node_modules/angular-route/angular-route.js',
      'node_modules/angular-resource/angular-resource.js',
      'node_modules/angular-animate/angular-animate.js',
      'node_modules/angular-sanitize/angular-sanitize.js',
      'node_modules/angular-touch/angular-touch.js',
      'node_modules/chosen-js/chosen.jquery.js',
      'node_modules/angular-chosen-localytics/dist/angular-chosen.js',
      'node_modules/angularjs-rails-resource/angularjs-rails-resource.js',
      'vendor/assets/javascripts/*.js',
      'vendor/assets/javascripts/*.erb',
      'vendor/assets/javascripts/**/*.js',
      'spec/javascripts/support/mock_constants.js.coffee',
      'spec/javascripts/support/*.js',
      'app/assets/javascripts/*.js.coffee',
      'app/assets/javascripts/multiple_markers_bullet_model.js',
      'app/assets/javascripts/qdw/providers/*.js.coffee',
      'app/assets/javascripts/qdw/templates/*.html',
      'app/assets/javascripts/qdw/main.js.coffee',
      'app/assets/javascripts/qdw/routes.js.coffee',
      'app/assets/javascripts/qdw/filters/qdw_filters.js.coffee',
      'app/assets/javascripts/qdw/interceptors/qdw_interceptors.js.coffee',
      'app/assets/javascripts/qdw/**/*.js.coffee'
    ],
    tests: [
      'spec/javascripts/qdw/controllers/sections/reports*_spec.js.coffee'
    ],
    preprocessors: {
      'app/assets/javascripts/qdw/templates/*.html': function(file) {
        return angularTemplatePreprocessor.transform(file, {
          stripPrefix: 'app/assets/javascripts/qdw/templates/',
          moduleName: 'templates'
        })
      }
    },
    bootstrap: function(wallaby) {
      // Also Tried:
      // wallaby.testFramework.DEFAULT_TIMEOUT_INTERVAL = 20000
      jasmine.DEFAULT_TIMEOUT_INTERVAL = 20000
    }
  }
};
```

**Comment by ericmhalvorsen** [comment]
Also tried (in the test file itself) - ```
afterAll ->
  jasmine.DEFAULT_TIMEOUT_INTERVAL = 20000
```

**Comment by ArtemGovorov** [comment]
Hi @ericmhalvorsen,

The error message that you see from wallaby: `Some long running code has been detected ...` is not controlled by the `jasmine.DEFAULT_TIMEOUT_INTERVAL` setting. In fact the `jasmine.DEFAULT_TIMEOUT_INTERVAL` setting may be already working for you the way you set it, and you may safely ignore the message in the wallaby console (that is harmless by itself).

The reason we have the message is to notify you in certain cases where the other setting is useless. For example, the `jasmine.DEFAULT_TIMEOUT_INTERVAL` setting will cause the test run to stop is one of your async tests is taking more than the configured amount of time. However, if you for example introduce an infinite loop in your code, the `jasmine.DEFAULT_TIMEOUT_INTERVAL` setting will not help and the test runner will keep executing forever. It's for cases like this, wallaby notifies you that something may have gone wrong.

Hope it makes sense.
