### ISSUE TITLE
Sudden TypeScript Compilation Errors on Angular 2 / VSCode

### ISSUE THREAD

**Issue by uitgewis** [wallabyjs/public#1168]
### Issue description or question
I day ago I started having issues while attempting to start up wallabyjs within VSCode, with the output giving me errors such as:
```
​​​​​​​​​SyntaxError: Unexpected token 'const'​​
​​at http://localhost:59163/____wallaby-bundle.js?1495529197705&wallabyFileId=bundle:42746​​
​​Error: Cannot find module '1'​​
  at ​src/app/app.component.spec.ts:1​
​​Error: Cannot find module '1'​​
​​at http://localhost:59163/wallaby-webpack.js?1495529197393:1​​
​​Error: Cannot find module '370'​​
  at ​src/app/auth/auth.actions.spec.ts:1​
​​Error: Cannot find module '370'​​
​​at http://localhost:59163/wallaby-webpack.js?1495529197393:1​​
```
When running the test suite manually it passes without a hitch. 

My problem does not seem to be configuration related, as I haven't changed it and it works for colleagues also working on the same project.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: {runner: '--web-security=false'}
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.12.2 

### OS name and version
OSX 10.11.6 (El Capitan)

**Comment by ArtemGovorov** [comment]
Could you please share your `tsconfig.json` (specifically `compilerOptions`) and `package.json` (specifically `dependencies` and `devDependencies`) files?

**Comment by ArtemGovorov** [comment]
> When running the test suite manually it passes without a hitch.

Please also share your karma config file.

**Comment by ArtemGovorov** [comment]
Also, please open the reported URL from the `​​​​​​​​​SyntaxError: Unexpected token 'const'​​
​​at http://localhost:59163/____wallaby-bundle.js?1495529197705&wallabyFileId=bundle:42746​​` error (not that the port changes every time you restart wallaby), and paste here in the issue the code around the line number 42746 (please include a few lines before and a few lines after the line).

**Comment by uitgewis** [comment]
tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```


karma.conf.js
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-phantomjs-launcher'),
      require('karma-chrome-launcher'),
      require('karma-firefox-launcher'),
      require('karma-safari-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'coverage-istanbul']
              : ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome', 'Firefox'],
    singleRun: false
  });
};
```

`const` error: When looking at it, it seems that an `npm` module being `import`ed is using `const/let`, which I assume causes issues for PhantomJS. I manually patched the module to be ES5 and it seems to be working again now. Is this normal?

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

> When looking at it, it seems that an npm module being imported is using const/let, which I assume causes issues for PhantomJS. I manually patched the module to be ES5 and it seems to be working again now. Is this normal?

This is the most likely issue. You are running your tests in Chrome via Karma, that's why everything is working there.

While you may either try finding an ES5 version of the module, or configure wallaby to use babel and compile the module to ES5 (you'll need to install babel in the project just for that which is not perfect), I would recommend another approach. 

As you are using Chrome to run your tests via Karma, it makes sense to do the same with Wallaby and use the [Chrome/Electron runner](https://wallabyjs.com/docs/integration/electron.html). It's just one line config change, but will work (and actually faster than PhantomJs, also no need to load any ES6 polyfills). Our offical Angular sample [has the setting by default](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L67), we are alos planning to make the Chrome runner to be the default option.

Please try switching the runner to Chrome/Electron and let me know how it goes.

**Comment by uitgewis** [comment]
That seem to work beautifully, thanks a lot. 😃

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
