### ISSUE TITLE
Wallaby, TypeScript, and Electron | exports is not defined

### ISSUE THREAD

**Issue by brandonfeil** [wallabyjs/public#1171]
### Issue description or question

I'm absolutely sure that this issue is a result of me not understanding how the world works, but I come seeking sage wisdom.

I have a project using TypeScript that is ultimately going to be an electron app. I was doing some base level development and was using node as the environment type. I'm using `import { Thing } from './place/thing'` style syntax for importing and `export class Foo` style syntax for exporting things.

All of the testing runs fine so long as the `env.type: 'node'`, but if I remove that and use `env.kind: 'electron'`, i get `​​Uncaught ReferenceError: exports is not defined​​`.

Like I said, you'll have to forgive my unfamiliarity with all of this. I'm sure it is related to a misunderstanding of the differences between node and electron wrt module formats and such. 

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

  return {
    files: [
      'src/**/*.ts'
    ],

    tests: [
      'test/**/*Spec.ts'
    ],

    env: {
      //type: 'node',
      kind: 'electron'
    },
    testFramework: 'mocha'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.12.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Wallaby Electron integration is designed to run browser tests only (and node integration is off by default). However, since your tests already run in node, it looks like you only need the renderer process only, so [this setting may be enough](https://github.com/wallabyjs/public/issues/943#issuecomment-287695386).
