### ISSUE TITLE
Wallabyjs using mocha not working with wallaby example code

### ISSUE THREAD

**Issue by ee0jmt** [wallabyjs/public#1173]
I am using the tutorial code from the wallabyjs website. It works fine with Jasmine, but I can not get it to work with mocha.

When I select startwallabyjs from the wallaby-mocha-2.0.1.json file the console output is:

wallaby.js started
core v1.0.431
Runtime error: TypeError: undefined is not a constructor (evaluating 'this[t](e[t])')
Runtime error: TypeError: undefined is not a constructor (evaluating 'this[t](e[t])')
at http://localhost:55780/__wallaby__/mocha@2.0.1/framework.js:15
console.log: NaN
console.log: 5
console.log: 0
console.log: -0.6666666666666666
console.log: 290

Help would be very much appreciated!

### Code editor or IDE name and version
Visual Studio 2015 Pro

### OS name and version
Windows 10 Pro

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed ([mocha version has to be removed from the config](https://github.com/wallabyjs/public/blob/master/sample/visualstudio/wallaby-mocha.json#L12)). Please get the latest version and it should work for you.
