### ISSUE TITLE
wallabyjs for Angular 4 - using a mix of full and relative path for imports

### ISSUE THREAD

**Issue by terealcantara** [wallabyjs/public#1176]
### Issue description or question
wallabyjs for Angular 4 - using a mix of full and relative path for import statements

our developers use a mix of full and relative paths for imports. it looks like wallaby out of the box recognizes just relative paths. how do I make it recognize absolute paths as well?

for instance: 

doesn't work for:
import { Logger } from 'app/core/service/logger/logger.service';
works for:
import { Logger } from '../logger/logger.service';

### Wallaby.js configuration file

var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallaby-test.js',
    'src/**/*.spec.js'
  ],

  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
      { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
      { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
    ]
  }
});

let compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      // { pattern: 'src/wallaby-test.js', load: false },
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.less', load: false },
      { pattern: 'src/**/*.scss', load: false },
      { pattern: 'src/**/*.sass', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [{ pattern: 'src/**/*spec.ts', load: false }],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: { kind: 'electron' },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 7 Enterprise SP1

**Comment by ArtemGovorov** [comment]
You need to configure webpack to look up the paths correctly by using the [`resolve.modules` setting](https://webpack.js.org/configuration/resolve/#resolve-modules). You may pass the setting into the `wallaby-webpack`/`webpackPostprocessor` initialization function call. 

Our Angular 4 sample had been updated some time ago to include the setting, so you [may just copy it from there](https://github.com/wallabyjs/ngCliWebpackSample/blob/82e24dc009b02213320b18a21651e418d8193821/wallaby.js#L29) (note that you'll need to move the `webpackPostprocessor` initialization under the `module.exports = function (wallaby) {...` function).

Please let me know if the solution works for you.

**Comment by terealcantara** [comment]
thank you for the prompt response! it worked!
