### ISSUE TITLE
Quokka plugin support?

### ISSUE THREAD

**Issue by signetjs** [wallabyjs/public#1187]
### Issue description or question

Is it possible, or is it in the plans to support Quokka plugins in Wallaby? I'm building something right now for Quokka, but I would really like to be able to use it with Wallaby for broader use in project code exploration and testing.

Not a bug so much as a question. Ideally, this would work in any OS and IDE. If this is already supported, I must have overlooked it in the docs.

**Comment by ArtemGovorov** [comment]
Yes, it is possible to use Quokka plugins from Wallaby given that [Wallaby is configured to run in node environment](https://wallabyjs.com/docs/integration/node.html), like Quokka does.

Wallaby has [the setup function](https://wallabyjs.com/docs/config/bootstrap.html) that you may use to execute any code before your test run. So if you have a Quokka plugin called `quokka-my-plugin` installed in your project, you use it with Wallaby as follows:

```javascript
 module.exports = function () {
   return {
     ...
     setup: function () {
       const plugin = require('quokka-my-plugin');
       // may pass plugin options to before/beforeEach if required
       if (plugin.before) plugin.before();
       if (plugin.beforeEach) plugin.beforeEach();
       delete plugin.before;
     }
   };
 };
```

**Comment by cmstead** [comment]
Awesome, thanks for the info!
