### ISSUE TITLE
er

### ISSUE THREAD

**Issue by jagreehal** [wallabyjs/public#1188]
### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm v?
IntelliJ IDEA v?
Visual Studio v?
Atom v1.?
Visual Studio Code v1.?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by fvanwijk** [comment]
Awesome!

**Comment by ArtemGovorov** [comment]
Closing the issue, assuming it was created by mistake.
