### ISSUE TITLE
Add Chrome headless as a supported browser

### ISSUE THREAD

**Issue by wbuss** [wallabyjs/public#1190]
### Add Chrome headless as a supported browser
Now that Chrome headless is here (for Linux and Mac anyway) i was wondering if there are any plans to support it as a runner?

**Comment by ArtemGovorov** [comment]
We have a plan to add the support. While it's being added, you may use wallaby.js [Electron/Chrome runner](https://wallabyjs.com/docs/integration/electron.html) which is essentially (almost) the same thing (in the context of running browser tests).

**Comment by ArtemGovorov** [comment]
[Google Chrome test runner support](https://wallabyjs.com/docs/integration/chrome.html) has been added (including headless mode for supported browser versions).
