### ISSUE TITLE
Token must be defined!​​

### ISSUE THREAD

**Issue by sgruhier** [wallabyjs/public#1192]
### Issue description or question
Anyone had that kid of error `​​Error: Token must be defined!​​`

It's in a complex component, but `ng test` runs well. 
From my investigation, it's on this line `injector.get(AuthenticationService);` where AuthenticationService is an in house service. 

it's in providers list of `TestBed.configureTestingModule`

I know I don't give a lot of hints, but it will be hard to isolate that from our code.
Just curious if people already faced that.

Thanks
 

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.13.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
We have never seen anything  like this. Googling the error also didn't yield any hints.
Given that you've found the service causing the issue, perhaps isolating it is possible (my guess is that it's something simple in the service is causing the issue). If you manage to share a repro sample, I'm happy to have a look.

**Comment by sgruhier** [comment]
Thanks for the quick answer (as usual!)
First I need to simplify my code and may the error will disappear. I just asked to see if I was the only one with this kind of issue. 
I also tried to inject to service in the constructor, the error was different. I don't have that test anymore, but the error was something like 
cannot inject ([Object, Object], ?). It's like it has no info about my AuthenticationService at all.

I'm gonna close that issue for now
Thanks again

**Comment by ArtemGovorov** [comment]
@sgruhier We have seen some angular 2 injection issues (like `cannot inject ([Object, Object], ?)`) in past, they were related to the `.d.ts` files, so try adding the `{pattern: 'src/**/*.d.ts', ignore: true},` entry to your `files` list (if it's not there yet).

**Comment by sgruhier** [comment]
I already have that :(
