### ISSUE TITLE
Taking a long time to find and run new test.ts files

### ISSUE THREAD

**Issue by patroza** [wallabyjs/public#1194]
### Issue description or question

It takes a long time for new .test.ts files to be detected, up to a minute or so.
Anything I can do about that?

Jest's watchman works immediately.

### Wallaby.js configuration file

```javascript
module.exports = function(w) {
  return {
    files: [
      'tsconfig.json', // <--
      'jest_global.ts',
      'src/**/*.ts',
      '!src/**/*.test.ts'
    ],

    tests: [
      'src/**/*.test.ts'
    ],

    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: '--harmony'
      }
    },
    compilers: {
      '**/*.ts': w.compilers.typeScript()
    },
    preprocessors: {
      '**/*.js?(x)': file => require('babel-core')
        .transform(file.content, {
          babelrc: true,
          sourceMap: true,
          filename: file.path
        })
    },
  };
};
```

Typescript 2.3.4 tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "lib": [
      "es2017", "dom"
    ],
    "moduleResolution": "node",
    "noImplicitAny": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "allowJs": false,
    "allowSyntheticDefaultImports": true
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useCache": true,
    "useBabel": true
  },
  "exclude": ["bower_components", "node_modules", "test"]
}
```

.babelrc
```json
{
  "plugins": [
    "transform-decorators-legacy"
  ],
  "presets": [
    ["es2015", {
      "loose": true
    }],
    "stage-1"
  ]
}
```

### Code editor or IDE name and version

Visual Studio Code v1.13.1?

### OS name and version

Windows 10.0.15063 (1703 creators update)

**Comment by ArtemGovorov** [comment]
- Is this only happening for newly added TypeScript files, but is working fast for changing existing files?
- Does your project take about a minute to build from the scratch (when you cold start Jest), with or without wallaby?

**Comment by patroza** [comment]
@ArtemGovorov thanks for the quick response.

It is super fast once the file is recognized, e.g I make a change in either source or test file, and the changes come in rather quickly.

Running jest for the first time takes up to 10 seconds. Subsequent runs (no test or src changes), it goes down to 3 seconds. Doesn't win any hearts and minds, but is far from taking up to a minute with Wallaby.

**Comment by patroza** [comment]
@ArtemGovorov it looks like when I add a new test file, all existing ts files get recompiled inside `.vscode\extensions\WallabyJs.wallaby-vscode-1.0.50\projects\6136621f52959a0e\instrumented`

**Comment by ArtemGovorov** [comment]
> it looks like when I add a new test file, all existing ts files get recompiled inside `.vscode\extensions\WallabyJs.wallaby-vscode-1.0.50\projects\6136621f52959a0e\instrumented`

Yes, it is indeed the case. In fact it was designed like this (to address shortcomings of the earlier versions of TS compiler). Under certain conditions, adding files on the fly could break compilation (it's not wallaby specific, can break plain Jest as well), so as a guaranteed safeguard we restart the compiler if a test file is added. Given that new files adding is a relatively rare operation (comparing to editing files), it seemed to be a reasonable trade-off.

We'll run some tests to see if those issues are still present in the latest TS compiler version (what's your TypeScript compiler version BTW?) to see if we can drop the safeguard to increase the performance without affecting the stability.

**Comment by patroza** [comment]
@ArtemGovorov thanks! Latest, TS 2.3.4.
Could you point me to the source file where I could stop the behavior to test performance impact?

**Comment by ArtemGovorov** [comment]
@patroza It's not easy (a few changes are required). Let me put together a solution for you (maybe behind a flag), I'll let you know once it's published so you could try.

**Comment by ArtemGovorov** [comment]
@patroza I have made the required changes and published the new version. Try updating to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.440 and see how goes. No additional configuration is required.

**Comment by ArtemGovorov** [comment]
BTW, the cold start could be much faster for you if you didn't have the babel preprocessor. Is there any specific reason you have it? Unless you need it just for synthetic module imports, you could do:

```javascript
    compilers: {
      '**/*.ts': w.compilers.typeScript({target: 'es5', module: 'commonjs'})
    },
```
and remove the preprocessor from the config.

**Comment by patroza** [comment]
@ArtemGovorov thanks a lot, so far my VS Code does not update Wallaby to the new version.

Regarding the babel; I indeed use synthetic default imports right now :(

**Comment by ArtemGovorov** [comment]
@patroza You may force the update [as described here](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by patroza** [comment]
@ArtemGovorov thanks a lot, so far it seems to be working like a dream!

I've found that only one case I had a synthetic default import, I've worked around that and dropped the babel requirement for tests which speeds things up even more.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
