### ISSUE TITLE
Error: not opened on combinedTickCallback along with Runtime error: SecurityError

### ISSUE THREAD

**Issue by oshalygin** [wallabyjs/public#1197]
### Issue description or question
Starting to see this lately, and I suspect it largely has an issue to do with some of my dependencies.  If anyone has any clue as to what is going on I would love to solve this.

I only get certain tests to run otherwise things just bomb out.

```
[Error] Error: not opened​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:95:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:161:9)​​
```

I also see 
```
​​[Error] Some long running code has been detected: test "my test name here" is taking more than 5000ms to execute.​​
``` 

but when I run this with the command line I don't see any issues.

This one troubles me the most but I'm not sure how to solve it, I dont even have jsdom as a peer dependency:

```
​​[Error] Runtime error: SecurityError​​
​​[Error]     at HistoryImpl._sharedPushAndReplaceState (/Users/oshalygin/dev/Atom/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/window/History-impl.js:87:15)​​
​​[Error]     at HistoryImpl.pushState (/Users/oshalygin/dev/Atom/node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/living/window/History-impl.js:69:10)​​
​​[Error]     at History.pushState 
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  'use strict';
  return {
    files: [
      'client/**/*.js*',
      'client/**/*.css',
      'server/**/*.js',
      'utilities/**/*.js',
      'stormpath.yml',
      '!client/**/*.json',
      '!client/**/*.spec.js*',
      '!server/**/*.spec.js*',
      '!server/**/**.http',
      { pattern: '/**/*.png', load: 'null' },
      { pattern: '/**/*.svg', load: 'null' },
      { pattern: '/**/*.txt', load: 'null' }
    ],
    tests: [
      'client/**/*.spec.js',
      'server/**/*.spec.js'
    ],
    env: {
      type: 'node',
      params: {
        env: 'NODE_ENV=test'
      }
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
        presets: ['latest', 'react', 'stage-1'],
        plugins: ['transform-object-rest-spread', [
          'transform-runtime',
          {
            polyfill: false
          }
        ],
          [
            'react-css-modules',
            {
              generateScopedName: '[local]'
            }
          ]
        ]
      })
    }
    // Toggle when you experience caching issues

    , workers: {
      recycle: true
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.14?

### OS name and version

MacOS Sierra

**Comment by ArtemGovorov** [comment]
Looks like you are observing 2 separate issues, I'll address them here separately.

1.
> I only get certain tests to run otherwise things just bomb out.
```
[Error] Error: not opened​​
​​[Error]   at _combinedTickCallback (internal/process/next_tick.js:95:7)​​
​​[Error]   at process._tickCallback (internal/process/next_tick.js:161:9)​​
```

> I also see
```
[Error] Some long running code has been detected: test "my test name here" is taking more than 5000ms to execute.​​
```

The combo of this two makes me think that there's something in your tests (specifically `my test name here` or its dependencies) calls `process.exit(...)`. This nukes wallaby test runner process. You may find what exactly is calling `process.exit` calls, by doing this:

```javascript
module.exports = function (wallaby) {
  return {
    ...
    setup: function () {
      process.exit = function () {
        throw new Error('found you!');
      }
    }
  };
};
```

If you find out that is not something that you'd like to fix/prevent, then just stub out the call so that wallaby may still work:

```javascript
module.exports = function (wallaby) {
  return {
    ...
    setup: function () {
      process.exit = function (){};
    }
  };
};
```

2.
> This one troubles me the most but I'm not sure how to solve it, I dont even have jsdom as a peer dependency:
```
​​[Error] Runtime error: SecurityError​​
​​[Error]     at HistoryImpl._sharedPushAndReplaceState
```

Jest has `jsdom` as a dependency, and by default `jsdom` is initialised/used by Jest when running your tests. Looks like some of your tests/dependencies access `document.location`, and the most common reason for the error is that [Jest testURL is not set in your Jest config](https://github.com/tmpvar/jsdom/issues/1378#issuecomment-283606444).

**Comment by oshalygin** [comment]
@ArtemGovorov awesome thanks as always!!

Is there a convention in place by wallaby to look at `package.json` to pull the jest config out?  I tried to have a separate file `.jestrc` but it was quite the PITA to get things working at the command line and through my build process with Jest.

Thanks I'm going to take another stab at this and clean things up!!

**Comment by ArtemGovorov** [comment]
> Is there a convention in place by wallaby to look at `package.json` to pull the jest config out

Yes, it [happens by default](https://wallabyjs.com/docs/integration/jest.html#jest-configuration). If you'd like to load it from elsewhere, like `.jestrc`  (or override some settings), you may do it like [described in the docs](https://wallabyjs.com/docs/integration/jest.html#jest-configuration).

**Comment by oshalygin** [comment]
Just added it and added the setup stub.  

Perfect!  Back to smooth sailing thanks as always @ArtemGovorov !!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

Just to help others who may stumble upon the same issues, what dependency was calling the `process.exit`? You may see it in the console stack trace if throwing and error from the stub:

```javascript
    setup: function () {
      process.exit = function () {
        throw new Error('found you!');
      }
    }
```

**Comment by oshalygin** [comment]
It was `js-yaml`.

I honestly have way too many dependencies right now and I need to do a few sweeping cleanups.  I like that wallaby keeps me honest with terrible tests as well, because running some of this via the cli doesn't poop out any of the hidden errors that surface themselves as I'm running wallaby in debug mode.
