### ISSUE TITLE
VSCode execution time displayed instead of failing assertion output

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1198]
### Issue description or question

It used to be that Wallaby should the output of a failing assertion. Now, I only have the time it took to run the assertion displayed. 

### Wallaby.js configuration file

I haven't touched the configuration before the issue appeared

### Code editor or IDE name and version

Visual Studio Code v1.13.1

### OS name and version

OSX

![screen shot 2017-06-17 at 07 03 23](https://user-images.githubusercontent.com/1718128/27250296-c369b010-532b-11e7-8e43-7a1e498b386b.png)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in VS Code extension v1.0.51.
