### ISSUE TITLE
Disabling Atom keymap.

### ISSUE THREAD

**Issue by phyllisstein** [wallabyjs/public#1199]
### Issue description or question
👋 Hey Wallabies. I've been working on integrating Wallaby into my Atom workflow, and something that I've found a little frustrating is that I can't seem to disable its keymap. The reason for wanting to do so is that it steps on the "Reopen Tab" shortcut: once <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd> is defined with a second chorded keystroke, Atom waits around for that second stroke before falling back on the original command.

I can add my own definitions (I like <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>Y</kbd> myself), but I can't disable Wallaby's---the package is hidden from Settings, and neither adding `atom-wallaby` nor adding `wallaby` alone to `config.packagesWithKeymapsDisabled` seems to do the trick.

Do you have any suggestions for the best course of action here? I'd be very grateful for any thoughts you might have. Thanks in advance!

### Wallaby.js configuration file

```javascript
module.exports = () => ({
  env: {
    params: {
      runner: '--harmony',
    },
    type: 'node',
  },
  files: [
    'src/**/*.js',
  ],
  setup() {
    const chai = require('chai')
    const sinonChai = require('sinon-chai')

    chai.use(sinonChai)
    global.should = chai.should()
  },
  testFramework: 'mocha',
  tests: [
    'spec/**/*-spec.js',
  ],
})
```

### Code editor or IDE name and version
Atom v1.18.0

### OS name and version
macOS 10.12.5

**Comment by ArtemGovorov** [comment]
Hello,

there may be a more compact way to do it, but [according to the discussion](https://discuss.atom.io/t/disable-default-keybindings/1077/47) using the `unset!` value for the shortcut should do the trick.

So if I take [macOS shortcuts from atom wallaby package](https://github.com/wallabyjs/atom-wallaby/blob/master/keymaps/wallaby.cson), set the <kbd>⌘</kbd>+<kbd>Shift</kbd>+<kbd>Y</kbd> prefix and unset all `cmd-shift-t` starting shortcuts, it seems to works as you'd like it to:

### keymap.cson
```
'.platform-darwin atom-workspace':
  'cmd-shift-t t': 'unset!'
  'cmd-shift-t r': 'unset!'
  'cmd-shift-t s': 'unset!'
  'cmd-shift-t p': 'unset!'
  'cmd-shift-t h': 'unset!'

  'cmd-shift-y t': 'wallaby:toggle-panel'
  'cmd-shift-y r': 'wallaby:start'
  'cmd-shift-y s': 'wallaby:stop'
  'cmd-shift-y p': 'wallaby:run-project-tests'
  'cmd-shift-y h': 'wallaby:show-last-screenshot'

'.platform-darwin atom-text-editor':
  'cmd-shift-t c': 'unset!'
  'cmd-shift-t f': 'unset!'
  'cmd-shift-t o': 'unset!'
  'cmd-shift-t p': 'unset!'
  'cmd-shift-t u': 'unset!'
  'cmd-shift-t l': 'unset!'

  'cmd-shift-y c': 'wallaby:run-line-tests'
  'cmd-shift-y f': 'wallaby:run-file-tests'
  'cmd-shift-y o': 'wallaby:jump-to-failing-test'
  'cmd-shift-y p': 'wallaby:jump-to-error-source'
  'cmd-shift-y u': 'wallaby:toggle-uncovered-regions'
  'cmd-shift-y l': 'wallaby:show-line-tests'
```

**Comment by phyllisstein** [comment]
🤕 🌴  Ack, that turned out to be a bit of a LMGTFY, I apologize. But thanks so much for the tip, it worked beautifully!

**Comment by ArtemGovorov** [comment]
No worries at all, thanks for the update!
