### ISSUE TITLE
video is too low resolution

### ISSUE THREAD

**Issue by tomByrer** [wallabyjs/public#12]
Usually 480p is the minimal to read code, unless the capture zoom/screen resolution makes the fonts larger.
ref: https://www.youtube.com/watch?v=uUmF16R9JNs
cheers :)

**Comment by ArtemGovorov** [comment]
You can change the resolution in the settings:
![screen shot 2015-02-09 at 2 46 56 pm](https://cloud.githubusercontent.com/assets/979966/6101155/967e9db0-b06a-11e4-8987-dd8e6048e0f8.png)

**Comment by tomByrer** [comment]
Weird, I tried that, but only 360p was available, but now is.
Thanks for your time!

**Comment by ArtemGovorov** [comment]
Interesting, was it from a desktop?

**Comment by tomByrer** [comment]
Yes.
Not worried about it now, but thanks for your consern!
