### ISSUE TITLE
Feature Suggestion: Wallaby CLI Test Runner

### ISSUE THREAD

**Issue by AustinMatherne** [wallabyjs/public#1200]
I love how fast Wallaby is able to execute large test suites. It's great from a local dev experience, but all of the test runners I can use with Jenkins are single threaded and much slower. It would be awesome if I could run Wallaby on a deployment server as part of CI/CD.

**Comment by ArtemGovorov** [comment]
Thanks for the feature request. Please feel free to subscribe to it here: https://github.com/wallabyjs/public/issues/72
