### ISSUE TITLE
Local Modules / Typescript files referenced by a package.json

### ISSUE THREAD

**Issue by cecilemuller** [wallabyjs/public#1201]
### Issue description or question

I noticed that Wallaby's Typescript preprocessor isn't applied to TS files that are referenced by a `package.json`.

As background info, [Local Modules](https://github.com/substack/browserify-handbook#node_modules) are a convenient cross-platform way to reference other modules local to the project, (e.g. `components/MyComponent` instead of `../../../components/MyComponent/MyComponent.js`), and given they use the vanilla Node resolution system, they usually work out of the box without any config in tools (unlike something that would use Webpack "resolve.alias", or a hack like [cross-env to use the deprecated NODE_PATH](https://gist.github.com/branneman/8048520#gistcomment-1881177) variable), very handy 😃 

Here is an example: https://github.com/wildpeaks/issue-wallaby-typescript-local-modules

It has two modules (`hello` and `helloworld`):

	/src
	/src/node_modules

	/src/node_modules/examples/hello/package.json
	/src/node_modules/examples/hello/hello.ts
	/src/node_modules/examples/hello/hello.spec.ts

	/src/node_modules/examples/helloworld/package.json
	/src/node_modules/examples/helloworld/helloworld.ts
	/src/node_modules/examples/helloworld/helloworld.spec.ts

Typical package.json (it uses both `typings` and `main` because TS intellisense uses "typings" while ts-node and Webpack use "main", however the example doesn't use Webpack).

````json
{
  "main": "hello.ts",
  "typings": "hello.ts"
}
````

Module `helloworld` relies on module `hello`, so it does `import hello from 'examples/hello'`. This works in ts-node, but fails in Wallaby (because Node tries to run the TS file directly, hence shows `SyntaxError: Unexpected token export`in Wallaby Output panel in VSCode).

If on the other hand you bypass package.json by referencing the TS file directly (using either `../hello/hello` or `examples/hello/hello`), it works fine in both, hence proving the cause is not the file it's trying to import, just that it merely wasn't identified as a file that needs to be preprocessed.

### Wallaby.js configuration file

```javascript
module.exports = () => {
	return {
		debug: true,
		testFramework: 'jasmine',
		files: [
			'src/**/*.ts',
			{pattern: 'src/**/package.json', instrument: false, load: false},
			'!src/**/*.spec.ts'
		],
		tests: [
			'src/**/*.spec.ts'
		],
		env: {
			type: 'node',
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.13.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Wallaby.js works a bit differently from `ts-node`, it precompiles `.ts` files to `.js` (and saves them on disk) before running tests, so package.json referencing `.ts` files will work in compile time, but will not work for the runtime resolution (like you're trying to use them). BTW, I'm not sure how your production build works, but it may also not work there for you, unless you are using `ts-node` in production (that is not great).

To make it work with wallaby, you may add a simple [preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) to rename `.ts` files to `.js` in `package.json` files.

```javascript

module.exports = () => {
	return {
		debug: true,
		testFramework: 'jasmine',
		files: [
			'src/**/*.ts',
			{pattern: 'src/**/package.json', instrument: false, load: false},
			'!src/**/*.spec.ts'
		],
		tests: [
			'src/**/*.spec.ts'
		],
		env: {
			type: 'node',
		},
                preprocessors: {
                        '**/*.json': file => file.content.replace('.ts', '.js') // <--
                }
	};
};

```

I have also [sent you the PR](https://github.com/wildpeaks/issue-wallaby-typescript-local-modules/pull/1) to make it work for your example.

BTW, I haven't seen many users using Local Modules trick, much more users seem to use the `NODE_PATH` ([here's an example](https://github.com/wallabyjs/public/issues/1082#issuecomment-288929441))

**Comment by cecilemuller** [comment]
Thanks, although I don't need a change to 'make it work' as I can already avoid the problem by referencing the ts file directly, it's just not as clean.

**Comment by ArtemGovorov** [comment]
Yep, sorry, by  'make it work' I meant  'make it work with `import helloworld from '.';`-like imports'.
