### ISSUE TITLE
NFR: a handy way to update snapshot

### ISSUE THREAD

**Issue by cyberhck** [wallabyjs/public#1202]
### New Feature Request

Hi there,

 Thanks for an amazing tool. I use wallaby a lot and I'm absolutely loving it and it saves a lot of my time.

 There's one particular situation, where I'd love a time saving feature. Whenever I change something in my components, my snapshot testing fails. I could go to command line and update the snapshot, that'd mean it'll update all the snapshot and not just one. I'd like to have a handy shortcut to update the snapshot right out of the box. Say when I click on red markers, we could show a small link to update the current snapshot. In that way, I can see what changed, if it's intended, we update, else we fix our tests.

### Code editor or IDE name and version

WebStorm

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
This feature is [already supported](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0). You may use `Run line/file/project tests` actions to update test/test file/whole project snapshots respectively.

![Snapshot testing](https://cdn-images-1.medium.com/max/800/1*xnFo08AOBW8drLDPT5BB3w.gif)

**Comment by cyberhck** [comment]
for some reason I don't see the show assertion data diff in PhpStorm (Didn't try in WebStorm yet)
Is that also working in PhpStorm? since it's the same plugin, I was hoping it to work.

PS: I already updated wallaby plugin today.

**Comment by ArtemGovorov** [comment]
Just checked and it's working for me in PhpStorm as well. 

I'm using [this project](https://github.com/wallabyjs/wallaby-jest-snapshots), breaking the test, and the action shows up (*note that the focus/cursor has to be on the error line to display the action*):

![wst](https://user-images.githubusercontent.com/979966/27366393-38fc37b6-5689-11e7-8361-405f4f5c468d.gif)
