### ISSUE TITLE
Test Failures With Rejected Promises

### ISSUE THREAD

**Issue by pahund** [wallabyjs/public#1206]
### Issue description or question

Since today, running my tests with Wallaby.js in IntelliJ IDEA does not work correctly anymore, while the tests still run fine using Mocha on the console.

Tests that are supposed to make sure that a promise rejection happens as expected fail.

Contents of the “Failing Tests” panel of Wallaby.js on IntelliJ IDEA:

https://gist.github.com/pahund/b5269b470a7008180c6fecef2ca23062

“Wallaby Console” panel:

https://gist.github.com/pahund/e1563da7d6a0a4c9e095cfb5f4ef91de

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
    files: [
        'src/**/*.js',
        'src/**/*.scss'
    ],

    tests: [
        'test/**/*Test.js'
    ],

    env: {
        type: 'node',
        runner: '/usr/local/bin/node'
    },

    workers: {
        recycle: true
    },

    testFramework: 'mocha',

    compilers: {
        '**/*.js': wallaby.compilers.babel()
    },

    bootstrap: () => {
        const path = require('path');
        const setupPath = path.join(wallaby.localProjectDir, 'test/setup');
        require(setupPath);
    }
});
```

### Code editor or IDE name and version

IntelliJ IDEA v2017.1.4
Wallaby.js core v1.0.442 

### OS name and version

macOS Sierra v10.12.5
Node.js v6.9.5

**Comment by ArtemGovorov** [comment]
> Tests that are supposed to make sure that a promise rejection happens as expected fail.

Could you please provide a simplified example of a test that is failing? How exactly is the promise rejection handled?

We have recently introduced a setting to report unhandled promise rejections as errors, I have a suspicion it may be affecting your case. Try setting it to `false`:

```javascript
module.exports = wallaby => ({
    ...
    reportUnhandledPromises: false
});
```

Even if it works with the setting, please share a test example so we could see if we could do something better in wallaby for your scenario (with the new default value for the setting).

**Comment by pahund** [comment]
Hi Artem,

`reportUnhandledPromises: false` fixed the tests, thanks!

I don't have time to create a reproducible example right now, perhaps I'll get around to it this week.

Cheers,
Patrick

**Comment by ArtemGovorov** [comment]
@pahund 
Awesome, thanks for the update!

BTW, you may need to fix your tests at some point not to have unhandled promise rejections, because they're already deprecated and in future versions of node.js an unhandled promise rejection will terminate node process.

**Comment by pahund** [comment]
I've created an example repo for you: https://github.com/pahund/wallaby-problem-rejected-promise

**Comment by ArtemGovorov** [comment]
Thanks for the sample!
The `reportUnhandledPromises: false` is a correct way to make these tests pass for now. It'll just stop wallaby from reporting unhandled promise rejections.

**Comment by ArtemGovorov** [comment]
If however you'd like to fix your tests that they don't cause node process termination in future versions of node.js, you [may add an empty `catch` to the promise](https://github.com/pahund/wallaby-problem-rejected-promise/pull/1). It will not change anything now, but should save you some time in future. You may read more about the [reasoning for the solution here](https://stackoverflow.com/questions/40920179/should-i-refrain-from-handling-promise-rejection-asynchronously/40921505).

**Comment by pahund** [comment]
👍🏻 will do, thanks for pointing it out

**Comment by sizilium** [comment]
In my case it's the other way around. I had a faulty test which threw an unhandled exception but it was not reported by wallaby. Even with the `reportUnhandledPromises: true` config it did not report it.

This workaround worked for me:
```
    setup: function () {
        window.addEventListener("unhandledrejection", e => {
            throw new Error(e);
        });
```

Now, when a test throws an unhandled exception wallaby will fail the test and mark it as red, which is exactly what I want.
Even karma does not fail the test, it just marks it as green and logs an error to the console (at a random place due to the async behavior) which makes it hard to find those issues.
