### ISSUE TITLE
Mocking keymaster makes react mocked (Jest)

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#121]
1. Run `npm run test` on https://github.com/endragor/wallaby-jest-sample and observe the test passes.
2. Run Wallaby on the same project and observe the test fails on `require('react')` line with
```
Runtime error: TypeError: Object function CallbackQueue(){return mockConstructor.apply(this,arguments);} has no method 'getPooled'
```
That is an indication that `react` was mocked, even though it was not supposed to be mocked (there is `jest.autoMockOff()`).
Interesting thing is that changing `keymaster` to some other module makes the test work fine from Wallaby.

**Comment by ArtemGovorov** [comment]
Fixed in 1.0.50.
