### ISSUE TITLE
'Unexpected token import' with Wallaby, react-native and typescript 

### ISSUE THREAD

**Issue by cofdev0** [wallabyjs/public#1211]
### Issue description or question

I get

Runtime error: ./src/index.ios.spec.js:2
import 'react-native';
^^^^^^
SyntaxError: Unexpected token import

when starting Wallaby in IDEAv2017.1.4 in a project using Jest, React-native and Typescript.

Tests run successfully with Jest alone: 'yarn run test'
source: https://github.com/cofdev0/mobileapp.git

I have found similar issues in this forum but their solution did not help.

### Wallaby.js configuration file
```javascript
/*
 WallabyJS React Native Config
 Works well with Jest + Enzyme
 */

/* eslint-disable */
module.exports = function (wallaby) {
    return {
        files: [
            'tsconfig.json',
            'package.json',
            'src/**/*.ts*',
            '!src/**/*spec.ts*'
        ],

        tests: [
            'src/**/*spec.ts*'],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                presets: [
                    'react-native',
                    'react-native-stage-0/decorator-support',
                ],
                plugins: [
                    'transform-flow-strip-types',
                    'transform-object-rest-spread',
                    'transform-async-to-generator',
                ],
            }),
        },

        setup: (wallaby) => {
            wallaby.testFramework.configure(require('./package.json').jest);
        },

    };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2017.1.4
Build #IU-171.4694.23, built on June 6, 2017

### OS name and version
Mac OS X 10.12.4

**Comment by ArtemGovorov** [comment]
You are using both TypeScript and Babel compilation. The correct way to make it work is to [use Babel preprocessor](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) after default TypeScript compiler.

I have sent you [the PR with the change](https://github.com/cofdev0/mobileapp/pull/1):
```javascript
        ...
        preprocessors: {
            '**/*.js': file => require('babel-core').transform(file.content, {
                sourceMap: true, filename: file.path,
                presets: [
                    'react-native'
                ],
                plugins: [
                    'transform-es2015-modules-commonjs',
                ],
            }),
        },
```

**Comment by cofdev0** [comment]
yes, that did it! 

thank you very much!
