### ISSUE TITLE
Problem with Jest and enzyme.mount using IntelliJ Ultimate

### ISSUE THREAD

**Issue by roger-gl** [wallabyjs/public#1215]
```
import * as React from "react";
import AktivitaetenButtonLine from "../AktivitaetenButtonLine";
import {mount} from "enzyme";
import postal from "postal";

it('should render with one text', () => {
        expect(mount(<AktivitaetenButtonLine text1={"a Line"}/>)).toMatchSnapshot();
  });

```
the above tests fails with the message : type error: Canot convert undefined or null to object
 
The test runs fine if I start jest from the command line. BTW: It seems as if all tests using mount fail.

Any ideas how to solve that ?

**Comment by roger-gl** [comment]
My mistake. I forgot to configure the enzyme-to-json/serializer.

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
