### ISSUE TITLE
wallaby is not working with mongoose models

### ISSUE THREAD

**Issue by ssmlee04** [wallabyjs/public#1217]
### Issue description or question

I have a mongoose model that looks like this:

```
const mongoose = require('mongoose');
const Promise = require('bluebird');

const widgetSchema = mongoose.Schema({
  color: String
});

widgetSchema.statics.b = function() {
  // return Promise.resolve()
  return Promise.cast(this.findOne().exec())
  .then(function(){
    return 1
  })
}

module.exports = mongoose.model('Widget', widgetSchema);
```

and my test file looks like this:

```
const should = require('should');
const Promise = require('bluebird');
var Widget = require('../models/mod');

describe('widget', function() {
  it('can get b', done => {
    Widget.b().then(d => {
      d.should.equal(1);
      done();
    });
  });
});
```

Somehow wallaby is not able to check the test results inside the promise function. Is there a way to make this work?

![](https://i.stack.imgur.com/UwjPu.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: ['server/models/*.js'],
    tests: ['server/tests/*.js'],
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },
  };
};
```

### Code editor or IDE name and version
Sublime Text v3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
There's a red icon in the test, meaning that there's some error occurring in your code. You may inspect the error using the [Failing Tests](https://wallabyjs.com/docs/intro/get-started-sublime.html#failing-tests) output, and the [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting) output.

You may also get the error description by adding the catch block to your test:

```javascript
  it('can get b', done => {
    Widget.b().then(d => {
      d.should.equal(1);
      done();
    }).catch(e => {
      console.log(e) // <--
    });
  });
```

**Comment by ArtemGovorov** [comment]
We do have a few wallaby users testing mongoose models, so my guess is that perhaps there's some connection issue (maybe because some required files, like `json` files with connection details, are not in the `files` list of your wallaby config).

Check out what error is displayed as I described above, hopefully it should clear things out.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If it is still a valid issue for you, please provide the info requested above.
