### ISSUE TITLE
feature: keep diff modal in sync in realtime

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1221]
The diff modal doesn't stay up to date like the logs do, it would be nice if it did so you don't have to keep closing it and reopening it.

![screen shot 2017-07-11 at 6 42 53 pm](https://user-images.githubusercontent.com/154732/28098042-d25c73a0-6668-11e7-91f9-e57e8d724155.png)

**Comment by ArtemGovorov** [comment]
[Released](https://twitter.com/wallabyjs/status/887929932235497472) in Wallaby App v1.0.29.
