### ISSUE TITLE
Error updating wallaby components when multiple Atom windows open on launch

### ISSUE THREAD

**Issue by subblue** [wallabyjs/public#1223]
### Issue description or question
I usually have multiple Atom windows open which get automatically restored after relaunching Atom. However, when there is a wallaby.js update each Atom window will try to get the update and install it at the same time leading to the error

```
Error while unzipping wallaby.js core file:
ENOTEMPTY: directory not empty
```

This often leaves the plugin in a corrupt state and I have to uninstall it and then reinstall it before it will work properly again.

### Code editor or IDE name and version
Atom v1.18.0

### OS name and version
OSX 10.12.5

**Comment by ArtemGovorov** [comment]
The issue should be fixed in atom-wallaby 1.0.19.
