### ISSUE TITLE
How do you setup Node + Browser tests

### ISSUE THREAD

**Issue by ProLoser** [wallabyjs/public#1226]
### Issue description or question
All my files are written node-like and then browserified, but the package is going to be used on the browser. When I tried to use `XMLHttpRequest` I got an undefined error. How can I use node-like `require()` alongside browser globals in my tests?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    env: {
      type: 'node'
    },
    files: [
      'src/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    testFramework: 'mocha',
    workers: {
      recycle: true
    }
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.14.0

### OS name and version
OSX 10.12.3

**Comment by fvanwijk** [comment]
The env type should not be node because the test are running in the browser

**Comment by ProLoser** [comment]
If I change the environment to node, it doesn't understand the calls to `require()`

**Comment by ProLoser** [comment]
Hmm annoying, but I guess it can't be helped.

**Comment by ArtemGovorov** [comment]
You actually have 2 options that should both work for you:
- as suggested above, you may configure [browserify](https://wallabyjs.com/docs/integration/browserify.html)  (or [Webpack](https://wallabyjs.com/docs/integration/webpack.html)) and wallaby will browserify your tests/code and then run it in browser (so you can use CommonJs or ES6 imports).
- you may also keep running your tests in node environment, but emulate browser specific stuff like `XMLHttpRequest` by [using jsdom](https://github.com/tmpvar/jsdom) (which you can initialize in your `setup` function).

Hope it helps.

**Comment by ProLoser** [comment]
I ended up figuring out how to get `sinon` (which I was already using) to mock the object for me.
