### ISSUE TITLE
Wallaby.js stuck on start

### ISSUE THREAD

**Issue by danielepolencic** [wallabyjs/public#1228]
### Issue description or question
When I start wallaby the loader continues loading forever.
The console doesn't show any error. No error in dev tools.

Wallaby version: 1.0.54

![image](https://user-images.githubusercontent.com/1130499/28242652-2f234648-69a9-11e7-9dc6-d701d6204f1d.png)

This is happening since I installed the new updates for Wallaby & VS Code.

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    debug: true,
    files: [
      './**/*.ts',
      '!./**/*test.ts',
      '!./**/*integration.ts',
    ],

    tests: [
      './**/*test.ts',
      './**/*integration.ts',
    ],
    testFramework: 'tape',
    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: false,
    },
    delays: {
      run: 500
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code 1.14.1

### OS name and version

OSX 10.12.5

**Comment by ArtemGovorov** [comment]
Try:
- reinstalling the extension,
- running [this sample](https://github.com/wallabyjs/wallaby-node-iojs-sample) to see if it works for you,
- setting `debug: true` flag as [described in the docs](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) and paste the full Wallaby Console output here.

**Comment by danielepolencic** [comment]
- tried uninstalling and installing it already. after I installed it, the next time I reopen Wallaby, it upgrades itself.
- `debug: true` was already enabled in my repo. The output is empty
- The sample works

**Comment by danielepolencic** [comment]
Ok, found the error. 

- in the output section, `Wallaby.js console` wasn't selected
- The output suggested that a test took more than 5000ms to execute

I commented the test and wallaby started working again.
