### ISSUE TITLE
Aurelia - handle external modules in wallaby

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#1229]
### Issue description or question
I have an Aurelia app where a class is referencing a module outside of node_modules - for simplicity, say:  

```
import ExternalLib from 'externalLib';

@inject(ExternalLib)
export class App {
  constructor(externalLib) {
    this.externalLib = externalLib;
    console.log('externalLib', externalLib);
  }
}
```
The module source file is referenced in aurelia.json like this:
```
build: {
    bundles": [
      ...
      {
        "name": "vendor-bundle.js",
        "dependencies": [
            {
                "name": "externalLib",
                "path": "../stuff/dist",
                "main": "externalLib",
                "packageRoot": "../stuff"
            }
       ]
     }
    ...
```

The app works OK.  And the jasmine test works ok running on Karma.  But when I try to add Wallaby, then it complains about not finding the external module.  Presumably because I have not worked out how to include the module in the wallaby config.  I tried adding it to the "files" list - no luck (maybe I did it wrong).

```
Uncaught Error: Cannot find module "externalLib"
	at src/app.js:5
Module not found: Error: Can't resolve 'externalLib' in './src'ModuleNotFoundError: Module not found: Error: Can't resolve 'externalLib' in '/home/xxx/IntelliJIdea2017.2/system/wallaby/projects/a729eff22d9c2b32/instrumented/src'
```
Some hint here would be really helpful.  

### Wallaby.js configuration file

```javascript

const wallabyWebpack = require('wallaby-webpack');
const wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js']
});

module.exports = function(wallaby) {
  return {
    files: [
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'test/stubs/**/*.js', load: false},
      {pattern: 'test/unit/setup.js', load: false}
    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],

    env: {
      kind: 'electron'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        'presets': [
          'es2015',
          'stage-1'
        ],
        'plugins': [
          'transform-regenerator',
          'transform-async-generator-functions',
          'syntax-async-functions',
          'transform-decorators-legacy',
          'transform-class-properties'
        ]
      })
    },

    postprocessor: wallabyPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};
```
### Code editor or IDE name and version

IntelliJ IDEA v2017.2

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
Since you're using webpack in your config, you'll just need to let webpack know how to resolve the modules that are outside of the standard `node_modules` location. You may either use [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules) or [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) depending on your situation (looks like resolve.alias is a better choice based on the info you've provided). For example:

```javascript
const path = require('path');
const wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js'],
  resolve: {
    alias: {
      'externalLib': path.resolve(__dirname, 'stuff') // or 'stuff/dist' 
    }
  }
});
```

If the suggested solution doesn't work for you, please create a sample repo demonstrating the issue, I'm happy to have a look.

**Comment by stevies** [comment]
Thanks. This worked:
```
 resolve: {
    alias: {
      'externalLib': path.resolve(__dirname, 'stuff/dist/externalLib.js')
    }
  }
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by stevies** [comment]
Fast and helpful response as always!

**Comment by stevies** [comment]
Unfortunately, when I apply the above solution that works in my simple sample app to my more complex real app, I am now getting hit with errors for each module - eg
```
Runtime error: Uncaught ReferenceError: exports is not defined
at http://localhost:9096/src/configs/app-config.js?1500463003679&wallabyFileId=8:3

Runtime error: Uncaught ReferenceError: exports is not defined
at http://localhost:9096/src/configs/constants.js?1500371054750&wallabyFileId=7:3
```
I will try to puzzle this out, but if you can think of anything obvious, let me know.

**Comment by ArtemGovorov** [comment]
Looks like it's a different (unrelated) error. My guess is that the `src/configs/app-config.js` and `src/configs/constants.js` files (or a pattern that includes them) is specified without `load: false` flag, so files are loaded as scripts without being webpack-ed (as they would be with the `load: false` flag).

**Comment by stevies** [comment]
Thanks.  Suspected this might just be another unrelated error that is now appearing because I have fixed the previous one.  Trying to add wallaby to an existing project - much easier to do on a clean application.  I will try to work it out in small steps, adding one module / spec at a time.

**Comment by stevies** [comment]
OK to close this one now.

**Comment by stevies** [comment]
Update - yes, I had a pattern without `load: false`.  Got it working now (mostly).  Remaining problem is back to an issue with 
```
import {bootstrap} from 'aurelia-bootstrapper';
```
causing problems.  
```
Uncaught Error: Unhandled promise rejection: Cannot find module "aurelia-loader-webpack"
at http://localhost:22993/__wallaby__/tracer.js:14
```
```
Module not found: Error: Can't resolve 'aurelia-loader-webpack' in '/home/xxx/IdeaProjects/web, 
etc, etc...
```
I remember bumping into this before - can't remember if I ever solved it.  Problem is in aurelia I think.

Is there now a simple way to exclude some tests from Wallaby?

**Comment by ArtemGovorov** [comment]
Try installing the `aurelia-loader-webpack` module.

> Is there now a simple way to exclude some tests from Wallaby?

Yes, you may exclude any specific test files like this:

```
    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false},
      '!test/unit/**/abc.spec.js' // <-- some specific file or a pattern
    ],
```

**Comment by stevies** [comment]
Cool.  I will see if I can install the aurelia-loader-webpack module and see if that fixes it.  But the exclusion will be very helpful if I can't fix the one file that is now breaking me.
