### ISSUE TITLE
angularjs-template-loader doesn't seem to kick-in with WallabyJS

### ISSUE THREAD

**Issue by dietergeerts** [wallabyjs/public#1230]
### Issue description or question

When I run my tests without wallaby, they all succeed, when run with wallaby with the same webpack configuration, I got an error `Unexpected request: GET ./errors.component.html`, which seems that the template loader isn't executed for some reason. I thought that all webpack loaders would kick in. Maybe I need some more specified config for wallaby. I can't find a solution for this though....

### How I run my tests without Wallaby

Scripts used for a single test run:

```json
// package.json
{
  "scripts": {
    "test": "cross-env NODE_ENV=test BABEL_CACHE_PATH=babel-cache.json webpack",
    "mocha": "mocha-phantomjs dist-test/index.html --reporter min",
    "coverage": "istanbul report --dir test-results/unit/coverage cobertura html"
  }
}
```

Then my webpack configuration:

```javascript
// webpack.config.js
if (process.env.NODE_ENV === 'development') {

    module.exports = [
        require('./webpack/dev.config'),
        require('./webpack/test.config'),
    ];

} else if (process.env.NODE_ENV === 'test') {

    module.exports = require('./webpack/test.config');

} else {

    module.exports = require('./webpack/prod.config');

}
```

```javascript
// webpack/test.config.js
const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const replace = require('lodash/fp/replace');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WebpackShellPlugin = require('webpack-shell-plugin');
const baseConfig = require('./base.config');

const IN_DEVELOPMENT = process.env.NODE_ENV === 'development';

module.exports = merge(baseConfig, {
    watch: IN_DEVELOPMENT,
    entry: {
        test: './../test/unit/index.js',
    },
    output: {
        path: path.resolve(__dirname, './../dist-test/assets'),
    },
    module: {
        rules: [
            {
                test: /.js$/,
                include: [
                    path.resolve(__dirname, './../test'),
                    // See https://github.com/domenic/chai-as-promised#browsernode-compatibility
                    path.resolve(__dirname, './../node_modules/chai-as-promised'),
                    // Without the following, unit tests don't work in PhantomJS...
                    path.resolve(__dirname, './../node_modules/angularjs-toaster'),
                    path.resolve(__dirname, './../node_modules/angular-ui-bootstrap-4'),
                ],
                loader: 'babel-loader',
            },
        ],
    },
    plugins: [
        new webpack.NormalModuleReplacementPlugin(/.css$/, 'node-noop'),
        new HtmlWebpackPlugin({
            filename: '../index.html',
            template: '../test/unit/index.html',
            __BASE_URL__: replace(/\\/g, '/')(path.resolve(__dirname, './../')),
            __DIST_DIR__: 'dist-test',
            inject: false,
        }),
        new WebpackShellPlugin({
            onBuildExit: IN_DEVELOPMENT
                ? ['npm run --silent mocha || exit 0'] // Don't exit on error + see mocha output last
                : [
                    'npm run mocha -- --hooks ./phantom-hooks.js' + // Normal execution + save coverage.json
                    '&& npm run coverage',                          // Create coverage report
                ],
        }),
    ],
});
```

```javascript
// webpack/base.config.js
const path = require('path');
const webpack = require('webpack');
const appSettings = require('./../app.settings');

module.exports = {
    context: path.resolve(__dirname, './../src'),
    output: {
        filename: '[name].[hash].js',
        publicPath: 'assets',
    },
    resolve: {
        extensions: ['.js', '.html', '.css'],
    },
    module: {
        rules: [
            {
                test: /.js$/,
                include: [
                    path.resolve(__dirname, './../src'),
                    // TODO: Make sure that the toolkit package is already compiled, best-practice!
                    path.resolve(__dirname, './../node_modules/@barco/careconsultation-toolkit'),
                ],
                use: [
                    {loader: 'babel-loader'},
                    {loader: 'angularjs-template-loader'}, // Inlines templateUrl: ... to template: ...
                ],
            },
            {
                test: /.html$/,
                include: path.resolve(__dirname, './../src'),
                loader: 'raw-loader',
            },
        ],
    },
    plugins: [
        new webpack.DefinePlugin({
            // TODO: App settings should be split up, depending on their usage...
            __APP_SETTINGS__: JSON.stringify(appSettings),
        }),
    ],
};
```

So when I run it through the npm test command, it works, and saves coverage report.

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./webpack/test.config');

module.exports = (wallaby) => {
    return {
        files: [
            {pattern: 'src/**/*.js', load: false},
            {pattern: 'src/**/*.test.js', ignore: true},
            {pattern: 'test/**/*.js', load: false},
        ],
        tests: [
            {pattern: 'src/**/*.test.js', load: false},
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },
        testFramework: 'mocha',
        postprocessor: wallabyWebpack(webpackConfig),
        setup: () => window.__moduleBundler.loadTests(),
    };
};
```

And my actual unit test file, because it can be related to how I did it:

```javascript
import {expect} from 'chai';
import './../../../test/unit/test-setup';
import {appErrorsComponentModule} from './errors.component';

describe(appErrorsComponentModule, () => {

    const ng = {};

    beforeEach(() => {
        angular.mock.module(appErrorsComponentModule);
        angular.mock.inject((_$compile_, _$rootScope_) => {
            ng.$compile = _$compile_;
            ng.$rootScope = _$rootScope_;
        });
    });

    it('should be true', () => {
        // console.log(global);
        // console.log(global.window);
        // console.log(angular);
        // console.log(window);

        const element = ng.$compile('<app-errors data-errors="errors"></app-errors>')(ng.$rootScope);

        ng.$rootScope.errors = [];
        ng.$rootScope.$digest();  // >> Unexpected request: GET ./errors.component.html No more request expected
        // console.log(element.html());
        expect(element.html()).to.match(/^<!--.*?-->\n$/g);

        ng.$rootScope.errors = [{}];
        ng.$rootScope.$digest();
        // console.log(element.html());
        expect(element.html()).to.not.match(/^\n<!--.*?-->\n$/g);

        expect(true).to.be.true;
    });
});
```

### Code editor or IDE name and version

IntelliJ IDEA 2017.1.5

### OS name and version

Windows 8

**Comment by ArtemGovorov** [comment]
None of your webpack `module.rules` are applied by wallaby because as [described in docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder), wallaby runs webpack on its own file cache (with all instrumented files specified in your `files` list), and your module rules have explicit `include`-s pointing to your local project path.

The good news is that wallaby doesn't need the most of your module rules for `.js` files because you have [babel compilation configured](https://wallabyjs.com/docs/integration/webpack.html#loaders-vs-preprocessorscompilers) in your wallaby config, so no babel-loader is required. However, you still need to apply the `angularjs-template-loader` for your `.js` files and `raw-loader` for your `.html` files.

To do it, you may just override the `module.rules` to apply loaders with [wallaby cache](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) being the root folder, and [include `.html` files](https://wallabyjs.com/docs/integration/webpack.html#files-and-tests) into your `files` list:

```javascript
...
module.exports = (wallaby) => {
  const path = require('path');
  const rootFolder = wallaby.projectCacheDir;
  webpackConfig.module = {
        rules: [
            {
                test: /.js$/,
                include: [
                    path.join(rootFolder, 'src')
                ],
                use: [
                    {loader: 'angularjs-template-loader'}
                ],
            },
            {
                test: /.html$/,
                include: path.join(rootFolder, 'src'),
                loader: 'raw-loader',
            },
        ],
    };

    return {
        files: [
            {pattern: 'src/**/*.html', load: false}, // <--
        ],
        ...
};
```

If the solution suggested above doesn't work for you, please create a sample repo demonstrating the issue, I'm happy to jump in and have a look.

**Comment by dietergeerts** [comment]
Thx you. Though I did have spent some time in the documentation, that part I didn't read already.
I changed my configs, so that a function is exported and I can give it the rootDir, which is my project dir on normal testing and the wallabyCacheDir when I run through wallaby.

But now I get another error, which I also had before with the normal testing:
```
SyntaxError: Expected an identifier but found 'checkError' instead
```

That  was the reason I added the following in my include of the js rule:
```
// See https://github.com/domenic/chai-as-promised#browsernode-compatibility     
path.join(rootDir, 'node_modules/chai-as-promised'),
```

So If I understand it correctly, the node_modules aren't in the cache, or they aren't ran through the loader then?

**Comment by ArtemGovorov** [comment]
> So If I understand it correctly, the node_modules aren't in the cache, or they aren't ran through the loader then?

Correct, the node_modules aren't in the cache by default. It's be too much file copying to do without much need (no instrumentation/compilation is normally required for external modules).

> does that mean that I need to do something special to be able to also have some run through a loader?

Yes, you may add that specific module to the `files` list (everything in the `files`/`tests` list gets in the cache):

```javascript
...
module.exports = (wallaby) => {
    return {
        files: [
            {pattern: 'node_modules/chai-as-promised/**', load: false},
            ...
        ],
...
```

**Comment by ArtemGovorov** [comment]
My last note is about how to run the files though wallaby compiler, not webpack babel loader. If you'd like babel loader ti run instead, then for node modules you may leave:
```
path.resolve(__dirname, './../node_modules/chai-as-promised'),
```
instead of 
```
path.join(rootDir, 'node_modules/chai-as-promised'),
```

**Comment by dietergeerts** [comment]
Having

```
path.resolve(__dirname, './../node_modules/chai-as-promised'),
```
and those modules added to the files array in wallaby config works now, but why? Isn't the wallaby babel compiler picking up my `.babelrc` file? or is the babel-loader doing other things I don't know about?

**Comment by ArtemGovorov** [comment]
I don't think you need both, you may either add the `node_modules/chai-as-promised` to the files list (in which case wallaby babel compiler will compile it, using your `.babelrc`), or you may have
```
path.resolve(__dirname, './../node_modules/chai-as-promised'),
```
in your module.rules, in which case babel-loader should do the same.

**Comment by dietergeerts** [comment]
Ok, removing them from the wallaby files array, and tests are still working. But now I'm confused about how this integration with webpack really works. Does wallaby loads all files and tests first with the specified babel compiler from the config before webpack actually runs? And is this why my template-loader is also ran for my src files? So then that means that both the wallaby babel compiler and the babel-loader runs on those src files?

Oh, and keep up the great work on Wallaby! I love it, it makes writing tests and developing so much easier and faster.

**Comment by ArtemGovorov** [comment]
> Does wallaby loads all files and tests first with the specified babel compiler from the config before webpack actually runs?

Correct, wallaby compiles files (with instrumentation) via its [babel compiler](https://wallabyjs.com/docs/integration/es-next.html) that you have configured in your wallaby config.

> And is this why my template-loader is also ran for my src files?

Your `angularjs-template-loader` runs because it is specified in your module rules:

```javascript
    module: {
        rules: [
            {
                test: /.js$/,
                include: [
                    ...,
                ],
                use: [
                    {loader: 'babel-loader'},
                    {loader: 'angularjs-template-loader'}
                ],
            },
...
```

> So then that means that both the wallaby babel compiler and the babel-loader runs on those src files?

If the `include` array points to wallaby cache folder, then yes. It's not an issue, just a double work done. This is why I was suggesting to simply [override `module.rules`](https://github.com/wallabyjs/public/issues/1230#issuecomment-316624630) instead of trying to reuse them. Alternatively, you may remove babel-loader right in your wallaby config from your webpack config, something like:

```javascript
webpackConfig.module.rules.forEach(r => {
 if(r.use[0].loader === 'babel-loader') r.use.shift();
})
```

**Comment by dietergeerts** [comment]
Super thx! This gave me a better understanding of how this all works and will help me setup other projects as well.
