### ISSUE TITLE
Wallaby updating jest snapshots on start

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1232]
### Issue description or question
When Wallaby's config is updated / Wallaby's internal cache invalidated, all failing Jest snapshots will be updated on startup. As expected, tests are not updated if wallaby's config is unchanged.

Possibly the same issue as #1115.

```
jest --version
v20.0.4
```

Modified test to fail:
<img width="646" alt="screen shot 2017-07-20 at 4 58 00 am" src="https://user-images.githubusercontent.com/1595871/28416312-5c508cf4-6d08-11e7-99fa-7ed0cdb2778c.png">

Added a random space in wallaby.js and restarted wallaby:
<img width="524" alt="screen shot 2017-07-20 at 4 58 40 am" src="https://user-images.githubusercontent.com/1595871/28416314-5fb77fb0-6d08-11e7-9e74-b23cc80774c9.png">

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js',

            'jest.config.js',
            '.env',

            '!src/**/*.test.js',
            '!src/**/*.snap',
        ],
        tests: ['src/**/*.test.js'],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        // https://github.com/wallabyjs/public/issues/465
        workers: { initial: 1, regular: 1 },

        setup: w => {
            process.env.NODE_ENV = 'test';

            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2017.2
Build #WS-172.3317.70, built on July 13, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```
### OS name and version

``Mac OS X 10.12.5``

**Comment by ArtemGovorov** [comment]
I thinks it's because your `.snap` files are excluded, so when the wallaby cache is cleared, it re-created the files (because the original .snap files are not copied over to the cache). Try including the files, as [we do in our sample](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js#L5), it should help.

**Comment by chrisblossom** [comment]
Thank you! That solved the issue. Might be nice to add a warning / error of some sort discouraging this behavior.
