### ISSUE TITLE
Can Wallaby handle module imports from both a relative and root paths?

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#1233]
### Issue description or question

Can Wallaby handle jasmine spec files that import Aurelia modules from both a relative path and from a root path?

I have a legacy Aurelia projects that I am trying to add Wallaby to.  There are test specs that import the required modules like this:
```
import {Something} from 'site/mything/views/somepart/something';
```
and others like this:
``` 
import {Something} from '../../../../../../src/site/mything/views/somepart/something';
```

Running under Karma - via Aurelia CLI `au test --watch` - works OK with both of the above import styles in the codebase.  Wallaby complains about the 1st type - `site/mything/...`

I could go through all the files and swap to the `../../../../../` approach.  But this is annoying if there is a simple wallaby config option that I am missing.

I had seen some examples where config like this is being added:
```
webpackConfig.resolve.root = path.join(wallaby.projectCacheDir, 'app');
```
But when I try adding a resolve.root pointing to my 'src' dir, I get an error about invalida configuration
```
Webpack has been initialised using a configuration object that does not match the API schema
configuration.resolve has an unknown property 'root'
```

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

module.exports = function(wallaby) {
  const wallabyPostprocessor = wallabyWebpack({
    entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js'],
    resolve: {
      // root: path.resolve(__dirname, 'src'),
      alias: {
        'aurelia-loader-webpack': path.resolve(__dirname, 'node_modules/aurelia-loader-webpack/dist/amd/aurelia-loader-webpack.js')
      }
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'test/stubs/**/*.js', load: false},
      {pattern: 'test/unit/setup.js', load: false},
      {pattern: 'test/unit/helpers/*.js', load: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false}
    ],
    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],

    env: {
      kind: 'electron'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        'presets': [
          'es2015',
          'stage-1'
        ],
        'plugins': [
          'transform-regenerator',
          'transform-async-generator-functions',
          'syntax-async-functions',
          'transform-decorators-legacy',
          'transform-class-properties'
        ]
      })
    },

    postprocessor: wallabyPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version

IntelliJ IDEA v?

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
You've been digging in the right direction, it's just that `resolve.root` is Webpack 1.x setting, and you seem to be using Webpack 2. You need the [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules) setting, like described in [the docs section](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder). So in your case (if the `site/mything/views/somepart/something` is inside the `src` folder):

```javascript
...
const wallabyPostprocessor = wallabyWebpack({
    ...
    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src') // <--
      ],
      ...
    }
  });
```
