### ISSUE TITLE
Wallaby Updating Jest Snapshots

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1240]
### Issue description or question
Wallaby is still randomly updating Jest snapshots and I am unsure how to reproduce.

How can I figure out what is going on? Is there a way to make it impossible for Wallaby to update / create a snapshot?

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

module.exports = wallaby => {
    return {
        files: [
            {
                pattern: 'src/**/__sandbox__/**/*',
                instrument: false,
            },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            '.babelrc',
            '.babelrc.js',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        // https://github.com/wallabyjs/public/issues/465
        // workers: { initial: 1, regular: 1 },

        setup: w => {
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            jestConfig.transform = { '__sandbox__.+\\.jsx?$': 'babel-jest' };
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version
```
WebStorm 2017.2.1 EAP
Build #WS-172.3544.10, built on July 21, 2017
JRE: 1.8.0_152-release-915-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```
### OS name and version

``Mac OS X 10.12.5``

**Comment by ArtemGovorov** [comment]
> Wallaby is still randomly updating Jest snapshots and I am unsure how to reproduce.

Could you please provide more details about the issue? 

Wallaby.js does update local snapshots by design in certain cases, however not randomly, but exactly when Jest requests it. So it actually Jest's request to update / create a snapshot.

**Comment by ArtemGovorov** [comment]
@chrisblossom We have reviewed the snapshot updating code and have found a case when snapshots are incorrectly updated by Jest because wallaby passes the `-u` flag incorrectly in this case. We have fixed the issue in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Please try the latest version and let us know how it goes.

**Comment by chrisblossom** [comment]
@ArtemGovorov thank you for looking into this. I have been trying to figure out why this is happening/reproduce it but am unable to. It seems it might be a race condition with Webstorm's auto-save functionality and how quickly Wallaby tracks/updates files.

This is my best guess because I noticed this happening when I was making a lot of different changes quickly.

**Comment by ArtemGovorov** [comment]
>  because I noticed this happening when I was making a lot of different changes quickly.

Yep, this is exactly the case we have fixed it for in the latest core, so should hopefully be ok now.

**Comment by chrisblossom** [comment]
Great! Thank you again!

**Comment by mbaranovski** [comment]
Hi @ArtemGovorov, I noticed that the snapshots are being overwritten. I was able to reproduce it with these steps:
1. Clone repo: https://github.com/mbaranovski/wallaby-jest-sample
2. Run wallaby see the snapshot test passing.
3. Stop wallaby
4. Change sum.js to add let's say `value1 + value1`.
5. Edit wallaby config file (add extra line)
6. Start wallaby and observe that snapshot has been overwritten and tests are passing without any indication to the user that this happened.

**Comment by ArtemGovorov** [comment]
@mbaranovski Thanks for providing the sample repo. I have sent [the pull request](https://github.com/mbaranovski/wallaby-jest-sample/pull/1) with the config change to your repo. 

In order to sync snapshots correctly, Wallaby needs to have your `.snap` files in the `files` list (otherwise test run generated snap files are the source of truth). For example, in this issue config file there's the `'src/**/*.snap',` entry, as well as in [the sample repo](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js#L5) for [this article](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0) on Jest snapshot testing with Wallaby.

**Comment by mbaranovski** [comment]
Thank you @ArtemGovorov for such a fast response. I just tested it on my project and it works as you said, that's great. It's a great article, just found out about the `Run line test(s)` option to update only one snapshot... I used to do` jest -u` to update it before... :)

**Comment by massimonewsuk** [comment]
I have been having this problem too. Updating my wallaby config to include the `*.snap` files doesn't seem to have fixed the issue.

My wallaby config looks like this:
```js
module.exports = () => {
  process.env.NODE_ENV = "test";

  return {
    files: [
      "{src,__tests__}/**/*.{ts,json,graphql,snap}",
      "!__tests__/**/*.{functional,integration,shape,unit,provider-integration,e2e}.ts",
      "tsconfig.json" // For ts-jest
    ],
    tests: [
      "__tests__/**/*.{functional,integration,shape,unit,provider-integration,e2e}.ts"
      // "__tests__/**/*.functional.ts"
    ],

    preprocessors: {
      "**/*.js?(x)": file =>
        require("babel-core").transform(file.content, {
          sourceMap: true,
          filename: file.path,
          presets: ["babel-preset-jest"]
        })
    },

    env: {
      type: "node"
    },

    testFramework: "jest",
    workers: {
      restart: true
    }
  };
};
```

**Comment by massimonewsuk** [comment]
Actually my issue seems to be jest related and not just isolated to wallaby, because running it on the command line alters the snapshot file too.

**Comment by massimonewsuk** [comment]
Is it possible to pass this option by default? https://jestjs.io/docs/en/cli.html#ci

**Comment by ArtemGovorov** [comment]
@massimonewsuk Changing the default may not be desirable/expected for most of users. You may add the option to your Jest config (or [override the setting value in your Jest config in Wallaby config](https://wallabyjs.com/docs/integration/jest.html#jest-configuration)).

**Comment by massimonewsuk** [comment]
I've updated my wallaby config as follows:
```js
module.exports = () => {
  process.env.NODE_ENV = "test";
  process.env.CI = "true";

  return {
    files: [
      "{src,__tests__}/**/*.{ts,json,graphql,snap}",
      "!__tests__/**/*.{functional,integration,shape,unit,provider-integration,e2e}.ts",
      "tsconfig.json", // For ts-jest
      "package.json"
    ],
    tests: [
      "__tests__/**/*.{functional,integration,shape,unit,provider-integration,e2e}.ts"
      // "__tests__/**/*.functional.ts"
    ],

    preprocessors: {
      "**/*.js?(x)": file =>
        require("babel-core").transform(file.content, {
          sourceMap: true,
          filename: file.path,
          presets: ["babel-preset-jest"]
        })
    },

    env: {
      type: "node"
    },

    setup: function() {
      process.env.CI = "true";

      var jestConfig = require('./package.json').jest;
      jestConfig.ci = true;
      jestConfig.updateSnapshot = false;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest"
  };
};
```

But it is still updating the snapshots and therefore making wallaby completely unusable because all the tests which should be failing start passing

**Comment by ArtemGovorov** [comment]
@massimonewsuk Thanks for sharing the config. Apparently the `ci` setting is not a part of Jest config API, it is only a CLI flag, so `jestConfig.ci = true;` won't work.

> But it is still updating the snapshots and therefore making wallaby completely unusable because all the tests which should be failing start passing

This is the way Jest works by default. When a snapshot doesn't exist, it creates it, but then if the snapshot doesn't match after some code changes, it'll fail the test.

> `process.env.CI = "true";`

We went ahead and implemented checking the `process.env.CI` env variable to set `updateSnapshot` to `none`. If you get [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), your config should start working as you are expecting it to. Note that the `setup` section is not required anymore (as you are setting the env variable at the start of your config), so this change should be enough:

```diff
module.exports = () => {
     ...
+    process.env.CI = "true";

```
