### ISSUE TITLE
Support `ospec` test framework

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#1243]
How can I use it with typescript? 

Code is here: https://github.com/MithrilJS/mithril.js/tree/master/ospec

**Comment by ArtemGovorov** [comment]
@andr2 Wallaby needs to add special support for any new testing framework (normally via a reporter to the framework) to be able to integrate with it.

**Comment by andr2** [comment]
Could you implement the integration? I need a simple lightweight all-in-one framework

**Comment by ArtemGovorov** [comment]
We marked it as a feature request for future, but can't promise any specific timeframe.

**Comment by smcenlly** [comment]
Closing this feature request. We do not have an intention of implementing support for `ospec` at this time.
