### ISSUE TITLE
[feature requests] make associated snapshots visualization available in test runner, jump to test in wallaby app, jump to snapshot

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1244]
### Issue description or question
Thanks for the project!  Really enjoying Wallaby, excited to add it to my team.

I've got some feature request ideas around supporting more visualization options for jest snapshots, particularly for non-failing tests.

Thanks again!

Three feature requests:
- Would be convenient for the test reporter to grow an always present view of jest snapshots (rather than only having ability to show such a visualization for failing tests.)  Something like an extra tab next to the errors/logs viewer that showed snapshots associated with currently selected test even for non-failiing test)
- Would be convenient to have a way to navigate automatically from editor to a particular test report in the wallaby app.  
- Would be convenient to be able to jump editor directly to the correct jest snapshot associated with a particular expect().toMatchSnapshot() call.  (convenient especially for exploring the data-structure generated by non-failing tests.)

### Code editor or IDE name and version

Visual Studio v1.14.2

### OS name and version
OSX

**Comment by smcenlly** [comment]
Wallaby now allows you to navigate to and view snapshots from your tests.
