### ISSUE TITLE
Wallaby doesn't work with scss imports and latest version of angular-cli (1.2.6)

### ISSUE THREAD

**Issue by kiwio** [wallabyjs/public#1245]
I'm having an issue with Wallaby not recognizing custom scss paths when project is setup with angular-cli 1.2.6. When I try to run Wallaby configuration in WebStorm (plugin version 1.0.92) I'm getting the following error:
```
Error: Module build failed: 
@import 'base';

^
      File to import not found or unreadable: base.
Parent style sheet: stdin
      in C:\Users\kiwio\.WebStorm2017.2\system\wallaby\projects\b1fb19c2150dbd5b\instrumented\src\app\app.component.scss (line 1, column 1)
```

I have the following setup in my project:

- styles/_base.scss - shared scss module
- .angular-cli.json contains configuration to resolve custom style paths:
```
"stylePreprocessorOptions": {
    "includePaths": [
        "styles"
        ]
    }
```
- app.comonent.scss has a simple import:
`@import 'base';`
- wallaby.js is configured to support the custom file path:
```
plugins: [new LoaderOptionsPlugin({
    options: {
        sassLoader: {
            includePaths: [
            "./src/styles"
        ]
        }
    }
    })]
```
It's working fine when I downgrade to angular-cli 1.0.0 though. 

A sample project replicating the issue can be found here: https://github.com/kiwio/wallaby-angular-cli-test

### Code editor or IDE name and version

WebStorm v2017.2

### OS name and version

Windows Server 2008R2

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo!
According to the [LoaderOptionsPlugin docs](https://webpack.js.org/plugins/loader-options-plugin/), it's not really supposed to be used what you're trying to use it.

The easiest way to find out what webpack config is used by angular CLI is by doing `ng eject` for the project (and roll the action back afterwards) - it'll generate the full webpack config to take some things from.

In your case the generate webpack config passes the `includePaths` option directly to the loader, I tried the same and it's working for me:

```javascript
{
          test: /\.scss$|\.sass$/,
          loaders: [
            'raw-loader',
            {loader: 'sass-loader', options: {includePaths: ['./src/styles']}}
          ]
},
```
I have [sent you the pull request](https://github.com/kiwio/wallaby-angular-cli-test/pull/1) with the change.

Hope it helps.

**Comment by glendaviesnz** [comment]
Just for future reference - we tried the change from your pull request, and it worked in the sample project, but for some strange reason not on our live project, which as far as we can see has identical settings. Anyway, we did an eject and grabbed the following settings from the webpack config and added them to the wallaby config and everything is now working

```
                { test: /\.scss$|\.sass$/,
                    "use": [
                        "exports-loader?module.exports.toString()",
                        {
                            "loader": "css-loader",
                            "options": {
                                "sourceMap": false,
                                "importLoaders": 1
                            }
                        },
                        {
                            "loader": "sass-loader",
                            "options": {
                                "sourceMap": false,
                                "precision": 8,
                                "includePaths": [
                                    "./src/styles"
                                ]
                            }
                        }
                    ]
                },
```
