### ISSUE TITLE
Capturing unused application code

### ISSUE THREAD

**Issue by elgalu** [wallabyjs/public#1246]
Just a hint, perhaps Wallaby.js can re-use some of the code from: https://github.com/joelgriffith/navalia

Blog post:
https://codeburst.io/capturing-unused-application-code-2b7594a9fe06

**Comment by ArtemGovorov** [comment]
Regarding unused code, Wallaby can run your tests and produce [the live code coverage report](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#files). 

While wallaby is a unit test runner that has [headless Chrome support](https://wallabyjs.com/docs/integration/chrome.html), Navalia looks like a browser automation tool, so could you please elaborate what exactly this feature request is about?

**Comment by elgalu** [comment]
Thanks for the neat clarification! closing as unrelated.
