### ISSUE TITLE
Cannot find module errors

### ISSUE THREAD

**Issue by ramaghanta** [wallabyjs/public#1251]
Since yesterday, we're seeing the following errors when we run wallaby, in the "Failing Tests" window. There was absolutely no code changes on my side. Was there any update to wallaby in the last few days that could have caused this issue?

    Error ./src/index.ts (7,21): Cannot find module '@checkdigit/aws-nock'.

    Error ./src/index.ts (8,24): Cannot find module 'debug'.

    Error ./src/index.ts (9,23): Cannot find module 'http'.

    Error ./src/index.ts (10,24): Cannot find module 'nconf'.

    Error ./src/index.ts (20,19): Cannot find name 'Promise'.

    Error ./src/index.ts (23,46): Cannot find name 'Promise'.

    Error ./src/index.ts (52,16): Cannot find name 'parseInt'.

    Error ./src/index.ts (61,11): An async function or method must return a 'Promise'. Make sure you have a declaration for 'Promise' or include 'ES2015' in your `--lib` option.

    Error ./src/index.ts (63,17): Cannot find name 'Promise'.

    Error ./src/index.ts (63,26): Parameter 'resolve' implicitly has an 'any' type.

    Error ./src/index.ts (20,19): Property 'teardown' of exported interface has or is using private name 'Promise'.

    Error ./src/index.ts (23,46): Return type of exported function has or is using private name 'Promise'.

### Wallaby.js configuration file
    const typescript = require('typescript');
    const compilerOptions = Object.assign(
      { typescript: typescript },
      require('./tsconfig.json').compilerOptions
    );

    module.exports = function (wallaby) {
      return {
        bootstrap: function () {
          require('expectations');
        },

        files: [
          {pattern: 'src/**/*.ts'},
          {pattern: 'src/**/*.yml'},
          {pattern: 'src/**/*.json'},
          {pattern: 'src/**/*.spec.ts', ignore: true}
        ],

        tests: [
          {pattern: 'src/**/*.spec.ts'}
        ],

        compilers: {
          '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
        },

        env: {
          type: 'node',
          runner: 'node'
        },
      };
    };

### Code editor or IDE name and version

WebStorm 2017.1.4

### OS name and version

OSX Sierra

**Comment by ramaghanta** [comment]
As a work around for the time being I added `{pattern: 'src/index.ts', ignore: true},` to `files` section and the "Failing Tests" window shows the test results.

Whats weird about this is, I use `debug` and `nconf` in another .ts file at the same path as `index.ts` and wallaby doesn't complain about that file.

**Comment by carlansley** [comment]
I have also been seeing these problems the last several days, where for some reason modules (both local and within node_modules) cannot be found by code running within Wallaby.  Only impacts a couple of source files.

**Comment by ramaghanta** [comment]
Changing `declaration` from `true` to `false` in tsconfig.json fixed the issue for me. While that could be a workaround, I would like to know what's triggering this error. I haven't changed my tsconfig.json for a while now, but wallaby started reporting these errors.

**Comment by ArtemGovorov** [comment]
There was a change to some defaults of the wallaby TS compiler recently and the changes must have affected you. We have fixed the issue in the [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version. After the update it should work for you as it did before. Sorry for the inconvenience.

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
