### ISSUE TITLE
Aurelia - problem testing code that imports aurelia-bootstrap

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#1252]
### Issue description or question
When I try to write a test that uses Aurelia testing framework - eg:
```
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper';

describe('test', () => {
  it('x', () => {
    expect(true).toBeTrue();
  });
});
```
The actual tests are irrelevant - it is import from 'aurelia-bootstrapper' that seems to be the problem.
Wallaby complains with message:
```
Uncaught Error: Unhandled promise rejection: Unable to find module with ID: aurelia-pal-browser
at http://localhost:11706/__wallaby__/tracer.js:14
```
I am using basic wallaby-webpack config setup. I've tried adding an alias for 'aurelia-bootstrapper' and aurel-pal-browser, but that doesn't help.

Any ideas on where I am going wrong? 
### Wallaby.js configuration file

```javascript

const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

module.exports = function(wallaby) {
  const wallabyPostprocessor = wallabyWebpack({
    entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js', 'test/unit/**/*-spec.js'],
    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src')
      ],
      alias: {
        'aurelia-bootstrapper': path.resolve(__dirname, 'node_modules/aurelia-bootstrapper/dist/amd/aurelia-bootstrapper.js'),
        'aurelia-pal-browser': path.resolve(__dirname, 'node_modules/aurelia-pal-browser/dist/amd/aurelia-pal-browser.js')
      }
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'test/stubs/**/*.js', load: false},
      {pattern: 'test/unit/setup.js', load: false},
      {pattern: 'test/unit/helpers/*.js', load: false},
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false}
    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],

    env: {
      kind: 'electron'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        'presets': [
          'es2015',
          'stage-1'
        ],
        'plugins': [
          'transform-regenerator',
          'transform-async-generator-functions',
          'syntax-async-functions',
          'transform-decorators-legacy',
          'transform-class-properties'
        ]
      })
    },

    postprocessor: wallabyPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```
### Code editor or IDE name and version

IntelliJ IDEA 2017.2.1

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
Could you please create a repo where the issue could be reproduced?

**Comment by stevies** [comment]
OK.  I'll try to do that later today.  Thanks.

**Comment by stevies** [comment]
Have a look at:  https://github.com/stevies/aurelia-testing-sample 

A basic aurelia project created using aurelia-cli.  Then I added wallaby.  All works.

I then modified `/test/unit/app.spec.js` to add the imports needed to write code using aurlia test.
```
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper';
```
This breaks with error - 
```
Runtime error: Uncaught Error: Unhandled promise rejection: Cannot find module "aurelia-loader-webpack"
```
That reminded me that aurelia has a separate loader for webpack.  Maybe that is the problem since we are using webpack for wallaby, but not in the application itself.  My main project did not have that specific error - maybe I changed something else.  Will check that.

**Comment by stevies** [comment]
When I did an install - `npm install aurelia-loader-webpack --save-dev`

Then the aulrelia-loader-webpack error goes away - replaced by:
```
Runtime error: Uncaught Error: Unhandled promise rejection: Unable to find module with ID: aurelia-pal-browser
```

**Comment by ArtemGovorov** [comment]
Thanks for the repo. Looks like some things had changed in Aurelia since the last time we had checked, and we may need to extend https://github.com/jeffling/wallaby-webpack to support the way the latest Aurelia version does things. I'll post an update here once we have something to test ready.

**Comment by ArtemGovorov** [comment]
I have sent you [the pull request](https://github.com/stevies/aurelia-testing-sample/pull/1) with my attempt to make it work. You'll need to update the wallaby config file, update the `wallaby-webpack` (as I have added some Aurelia specific support to it) and install `aurelia-loader-webpack` & `aurelia-webpack-plugin` modules.

**Comment by stevies** [comment]
I have taken your changes.  When I run wallaby, in the wallaby runner, I get:
```
wallaby.js started
core v1.0.465
Failed to load configuration file:  SyntaxError: Unexpected token =
  at exports.runInThisContext (vm.js:53:16)
  at Module.i._compile (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:15:20195)
  at Module.r.require (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:19:26568)
  at Object.<anonymous> (/home/dev/IdeaProjects/web/aurelia-testing-sample/node_modules/aurelia-webpack-plugin/dist/index.js:6:10)
  at Module.i._compile (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:15:20195)
  at Module.r.require (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:19:26568)
  at Object.<anonymous> (/home/dev/IdeaProjects/web/aurelia-testing-sample/wallaby.js:3:23)
```
and in failing tests:
```
SyntaxError: Unexpected token =
  at exports.runInThisContext (vm.js:53:16)
  at Module.i._compile (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:15:20195)
  at Module.r.require (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:19:26568)
  at Object.<anonymous> (/home/dev/IdeaProjects/web/aurelia-testing-sample/node_modules/aurelia-webpack-plugin/dist/index.js:6:10)
  at Module.i._compile (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:15:20195)
  at Module.r.require (/home/dev/.IntelliJIdea2017.2/system/wallaby/wallaby/server.js:19:26568)
  at Object.<anonymous> (/home/dev/IdeaProjects/web/aurelia-testing-sample/wallaby.js:3:23)
```
Maybe I missed a build step. Will clean everything and try again.

**Comment by ArtemGovorov** [comment]
Ah, it must be `aurelia-webpack-plugin` using newer syntax that is not supported in the default version of node that wallaby runs the config with. Try [pointing wallaby Run Configuration to use your system's node version](https://wallabyjs.com/docs/intro/install.html#nodejs) in your IDE.

**Comment by stevies** [comment]
Yes, that seems to fix it.  Sample working now. 

I've made the same changes in my main project.  Now failing with problems relating to loading Aurelia validation module. 
```
	Error: Unhandled promise rejection: Unable to find module with ID: aurelia-validation
```
I had problems with testing validation before when using Webpack to build the project.  Eventually had to switch to using Aurelia CLI to get around that.  I'll do some more investigation and see if I can fix it.

Thanks again.

**Comment by ArtemGovorov** [comment]
Thanks for the update. 
Quick googling the error [suggests using `PLATFORM.moduleName`](https://github.com/aurelia/webpack-plugin/issues/99#issuecomment-290034760):

```javascript
...
.plugin(PLATFORM.moduleName('aurelia-validation'))
```

Did you try it?

**Comment by stevies** [comment]
Thanks.  That seems to fix that problem with validation - at least it is not the main error now.  Now getting problems loading the resource files.  Likely some path problem.  Tests work outside wallaby with paths that point outside tests back to relative to 'src' directory.  I'll see if I can fix it. 
```
component = StageComponent
      .withResources(['views/products/someview'])
      .inView('<my-component></my-component>')
      .boundTo({ changeIsDisabled: false });

    component.bootstrap(aurelia => {
      return aurelia.use
        .standardConfiguration()
        .plugin(PLATFORM.moduleName('aurelia-validation'))
        .feature('resources');
    });
```

**Comment by ArtemGovorov** [comment]
Your `files` list (at least in the config posted in the issue and in the sample repo) doesn't contain any other files but `.js` files. I'm not very familiar with aurelia resources, but I'm guessing it's not `.js` (but `.html`/`.css`?) and you'll to add the file patterns to the files list so that wallaby-webpack could find them.

**Comment by stevies** [comment]
The resources here are .js files - 'resources' is just a naming convention for the directory where you place components, value converters, etc.  I'll see if I can add a simple example to my repo later today.  Probably better to get a real example working there first.

**Comment by ArtemGovorov** [comment]
>  'resources' is just a naming convention for the directory

Ah, thanks for clarifying it. Then maybe adding it to the `resolve.modules` helps?

```diff
const wallabyPostprocessor = wallabyWebpack({
    ...
    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src'),
+       path.join(wallaby.projectCacheDir, 'src/resources') // or whatever the path is
      ],
      ...
    }
  });
```

If it doesn't help, then adding an example to your repo would be great.

**Comment by stevies** [comment]
Example component and test added to my repo.  Works in Karma runner.  Fails to load component in wallaby.  I've not had time to try to fix it - will look later today to see if I am missing something simple in wallaby.js.
```
1 failing tests, 1 passing

test/unit/my-component.spec.js MyComponent can render [36 ms]

	Error: Unhandled promise rejection: Unable to find module with ID: my-component

	Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
		at Object.<anonymous> test/unit/my-component.spec.js:15
```

**Comment by ArtemGovorov** [comment]
> Works in Karma runner.

Karma runner runs tests on pre-built bundles, it's a completely different story.

I'm not sure what's going now, will need to investigate. It must be something aurelia-webpack plugin/integration related, because my-component is not imported but just referenced as a string, so I'm guessing Aurelia webpack plugin needs to handle it correctly.

BTW, could you please try the config below for your sample/real project? It uses wallaby node runner with `aurelia-loader-nodejs`/`aurelia-pal-nodejs`. 

```
npm install jasmine aurelia-loader-nodejs aurelia-pal-nodejs
```

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.js',
      'src/**/*.html'
    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.js'}
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        'presets': [
          'es2015',
          'stage-1'
        ],
        'plugins': [
          'transform-regenerator',
          'transform-async-generator-functions',
          'syntax-async-functions',
          'transform-decorators-legacy',
          'transform-class-properties'
        ]
      })
    },

    testFramework: 'jasmine',

    setup: function (w) {
      require('aurelia-polyfills');
      require('aurelia-loader-nodejs').Options.relativeToDir = require('path').join(w.projectCacheDir, 'src');
      require('aurelia-loader-nodejs').ExtensionHandlers['.css'] = function () {
        return new Promise(function (resolve, reject) {
          return resolve('');
        });
      };
      require('aurelia-pal-nodejs').globalize();
    }
  };
};
```

**Comment by stevies** [comment]
That config appears to work OK with the sample. Can't quite get it running with the real app - seeing module loading still failing...
```
Runtime error: Error: Cannot find module 'resources/value-converters/text-filter'
```
and also:
```
```
Runtime error: ReferenceError: regeneratorRuntime is not defined
```
Also, I have some module alias stuff I don't know how to replicate.
```
const wallabyPostprocessor = wallabyWebpack({
    entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js', 'test/unit/**/*-spec.js'],
    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src')
      ],
      alias: {
        'my-alias': path.resolve(__dirname, 'node_modules/some-module.js')
      }
    }
  });
```
Not sure that is needed or not.

**Comment by ArtemGovorov** [comment]
Had sent you [the PR](https://github.com/stevies/aurelia-testing-sample/pull/2). After some digging, looks like Aurelia webpack integration really needs `PLATFORM.moduleName(...)` for all resources that you reference. 

As far as I understand, the call is harmless in other contexts as it just returns a passed string. But for webpack it is a meaningful compilation time token that tell it to resolve and package the referenced resource.

So I had to modify the test to basically tell webpack to load everything it needs. I couldn't find another way to make it work, looks like it's just the way Aurelia integration with webpack works.

It may be possible to avoid using `PLATFORM.moduleName(...)` and setup wallaby to use aurelia node integration, or requirejs integration (that karma config seems to be partially using), but I suspect that it may require solving the same set of challenges (pointing to `src` for modules, setting aliases and maybe a few more things).

**Comment by stevies** [comment]
Sorry to open this again.  I have one more question / problem.  I have checked in some changes to my repo.  The directory structure is more representative of my main aurelia project (follows convention of registering components under /resources/elements/...).

Now when I run my test for my-component it appears that I need to load all the other components or the test fails to work - can't find the 'another' component even though it is not being used by this test or the original code.
```
component = StageComponent
      .withResources(
        // PLATFORM.moduleName('resources/elements/another.html') &&
        // PLATFORM.moduleName('resources/elements/another') &&
        PLATFORM.moduleName('resources/elements/my-component.html') &&
        PLATFORM.moduleName('resources/elements/my-component')
      )
      .inView('<my-component name.bind="someProperty"></my-component>')
      .boundTo({ someProperty: 'Foo' });

```
If I remove the comments around 'another' component, it works.  But that will be painful to copy into my real project where I have many components.
```
1 failing tests, 1 passing

test/unit/resources/elements/my-component.spec.js MyComponent can render [39 ms]

	Error: Unhandled promise rejection: Unable to find module with ID: resources/elements/another

	Error: Cannot call ComponentTester.dispose() before ComponentTester.create()
		at Object.<anonymous> test/unit/resources/elements/my-component.spec.js:27
```
I am guessing that this has something to do with Aurelia's convention of looking in where 'feature' points to to register all the helper components.  Not sure how to wire that up.   This is the usual approach:
```
 component.bootstrap(aurelia => {
      return aurelia.use
        .standardConfiguration()
        .feature(PLATFORM.moduleName('resources/index'));
    });
```
where the index.js file has an array of all the feature components.  

Any ideas on how to get this to work with just referencing the component I want to test, and not all the other untested ones?

**Comment by stevies** [comment]
Appears to work OK if I simply remove the `aurelia.use.feature()`.  Repo updated in case this helps anyone else. 
```
  beforeEach(() => {
    component = StageComponent
      .withResources(
        // PLATFORM.moduleName('resources/elements/another.html') &&
        // PLATFORM.moduleName('resources/elements/another') &&
        PLATFORM.moduleName('resources/elements/my-component.html') &&
        PLATFORM.moduleName('resources/elements/my-component')
      )
      .inView('<my-component name.bind="someProperty"></my-component>')
      .boundTo({ someProperty: 'Foo' });

    component.bootstrap(aurelia => {
      return aurelia.use
        .standardConfiguration()
        .defaultResources();
        // .feature('resources');
    });
  });
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by stevies** [comment]
Sorry to drag this out again.  I have updated my repo to include a less / css include into the component.  Wallaby does not like that.  
```
Module not found: Error: Can't resolve './my-component.css' in './src/resources/elements'ModuleNotFoundError: Module not found: Error: Can't resolve './my-component.css' in '/home/dev/.IntelliJIdea2017.2/system/wallaby/projects/7efb3bed6b704d5e/instrumented/src/resources/elements'
  at factoryCallback (/home/dev/IdeaProjects/web/aurelia-testing-sample/node_modules/webpack/lib/Compilation.js:264:39)
```
I have added:
```
 module: {
      rules: [
        {test: /\.html$/i, loader: 'html-loader'},
        {test: /\.css$/, use: ['style-loader', 'css-loader']}
      ]
    },
```
and
```
   files: [
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'test/unit/setup.js', load: false}
    ],
```
in an attempt to get this to work.  But 
```
 component = StageComponent
      .withResources(
        PLATFORM.moduleName('resources/elements/my-component.css') &&
        PLATFORM.moduleName('resources/elements/my-component.html') &&
        PLATFORM.moduleName('resources/elements/my-component')
      )
```
causes 
```
wallaby.js started
core v1.0.466
TypeError: Cannot read property 'startsWith' of undefined
  at resolver.doResolve (/home/dev/IdeaProjects/web/aurelia-testing-sample/node_modules/aurelia-webpack-plugin/dist/SubFolderPlugin.js:30:41)
```
and commenting out the css line gives the first error. 
You may need to npm import again into my repo to get some of the css / less parts of the aurelia build.

**Comment by ArtemGovorov** [comment]
I [have sent the PR](https://github.com/stevies/aurelia-testing-sample/pull/3). Took a hint from the official aurelia webpack skeleton project's webpack config [that loads CSS differently for html files and not from html files](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-esnext-webpack/webpack.config.js#L52-L68).

I also renamed your `.less` file to `.css` because you've referenced it everywhere (in configs and from .html file) as `.css`. If you have `.less` files in real project, you'll need to adjust the file patterns in the config (and use less-loader for webpack instead of the css-loader).

**Comment by stevies** [comment]
OK - thanks again for the fast response.  Will have a look.  

Aurelia build presumably handles the conversion from less to css in the background when bundling.  I wouldn't normally have any raw css files in the project.

**Comment by ArtemGovorov** [comment]
> Aurelia build presumably handles the conversion from less to css in the background when bundling

In this case you may need to use [wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) to convert `.less` files to `.css` (and rename them on the fly as well) instead of the less-loader via webpack (because your html templates seem to reference `.css` that don't exist during the build, so webpack chokes).

**Comment by stevies** [comment]
Yes - that is correct.  I'll have a look at the prepreocessor and try to get it to generate the css on the fly.

**Comment by stevies** [comment]
I found your example preprocessor that uses node-sass to handle sass files. Looks good. 

https://github.com/wallabyjs/public/issues/709

```
 preprocessors: {
      '**/*.scss': file => require('node-sass').renderSync(
                                      {data: file.changeExt('css').content || ' '}
                                    ).css.toString()
    },
```
But I can't see anything similar to node-sass for handling less files on the fly.  I'll keep looking to see if I find anything suitable.

**Comment by ArtemGovorov** [comment]
It shouldn't be too hard to just `require('less')` and [call it programmatically](http://lesscss.org/usage/#programmatic-usage). [Wallaby preprocessor supports async mode with the `done` callback], so you may do something like:

```javascript
 preprocessors: {
      '**/*.less': (file, done) => 
        require('less').render(
          file.changeExt('css').content, 
          {}, 
          (err, output) => done(err || output))
    },
```

**Comment by stevies** [comment]
Thanks again.  Since I don't really care about the less to css conversion in wallaby - not part of anything I want to test - I can simply fake it and rename the .less files to .css in the preprocessor.

```
    preprocessors: {
      '**/*.less':  (file, done) => done(file.changeExt('css').content)
    },
```
That appears to work OK.  I have updated my repo.

I really appreciate the help you have provided here.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
