### ISSUE TITLE
Not working with latest IDEA

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#1253]
### Issue description or question

After a long time without usage I now trying to run wallaby in the IntellJ IDEA 2017.2 and it's not working. No errors no warnings.

### Wallaby.js configuration file

https://github.com/okonet/react-dropzone/blob/master/wallaby.config.js

### Code editor or IDE name and version

IntelliJ IDEA v2017.2

### OS name and version

OSX 10.12

**Comment by ArtemGovorov** [comment]
Wallaby was tested for IntelliJ IDEA v2017.2 and is supposed to work.

Could you please:
- Specify how the plugin is not working: does it not even display the tool window (allows to create a Run Configuration), or it starts but is not displaying anything in the Wallaby Console?
- Check if you have all wallaby notifications turned on:
<img width="454" alt="screen shot 2017-08-05 at 9 42 00 am" src="https://user-images.githubusercontent.com/979966/28990608-5f233d48-79c2-11e7-839b-40b170af9cef.png">

- Check if you have a valid license entered (`Help - Manage Wallaby.js License`),
- Attach the relevant part of your `idea.log` after you start wallaby (`Help - Show Log In finder`). You may also search to see if there's anything Wallaby related in it.

**Comment by okonet** [comment]
- it starts but is not displaying anything in the Wallaby Console
- I've re-enabled all notifications for Wallaby (you have suggested to disable them) and I don't see any when I start it. The license one appeared after I clicked on `Help - Manage Wallaby.js License`
- The license wasn't entered correctly. After I entered it, nothing has changed.

This is how it looked before I entered license:
![2017-08-05 at 07 29](https://user-images.githubusercontent.com/11071/28993159-ed274e76-79af-11e7-9e73-2f7581c9f2f4.png)

This is after:
![2017-08-05 at 07 33](https://user-images.githubusercontent.com/11071/28993182-7645c304-79b0-11e7-9179-8d7d671467a6.png)

Here is the log file: 
[idea.log.zip](https://github.com/wallabyjs/public/files/1202137/idea.log.zip)

**Comment by ArtemGovorov** [comment]
Thanks for describing the details.
After cloning your repo and [setting the `debug: true` as suggested in out troubleshooting guide](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information), I got this error on the Wallaby Console:

```
Error in worker: node: bad option: --harmony_proxies
```

Try setting the `debug: true` and see if you're getting the same error. If so, it mean your node version doesn't support the `--harmony_proxies` that you are passing in your config and if you remove it, it should work (it's working for me if I remove it).

Hope it helps. We'll also have a look to see if we can display an error like this not just with the debug flag, as it's clearly a show-stopper.

**Comment by okonet** [comment]
That solved it
