### ISSUE TITLE
Power-assert with angular-cli?

### ISSUE THREAD

**Issue by studds** [wallabyjs/public#1256]
### Issue description or question

I was using a setup based on https://github.com/wallabyjs/walllaby-typescript-powerassert but have now migrated to https://github.com/wallabyjs/ngCliWebpackSample. Is there a suggested way to use power-assert with the built in typescript compiler?

### Wallaby.js configuration file

per https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js

**Comment by ArtemGovorov** [comment]
The setup that you were using is also using the built-in typescript compiler, so if it was working for you, then [the same approach](https://github.com/wallabyjs/walllaby-typescript-powerassert/blob/master/wallaby.js#L19) adjusted for your `tests` glob pattern (only without the `setup` function change) should work for you.
