### ISSUE TITLE
Provide visual indication of which tests are running in Wallaby App

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1257]
### Issue description or question

Currently, the tests are green even before they've run and there is no visual indication that tests are running/which tests are running in wallabyjs app.

It'd would be awesome to provide visual feedback as tests are run/re-run.

It would also be pretty cool if the wallabyjs console output streamed into a pane visible within wallabyjs app -- I have some slow-running tests in my suite and its nice to have the console output visible to re-assure me that the test cases are running when expected - but its not ideal to always devote the bottom panel in vscode to this purpose.

### Code editor or IDE name and version

Visual Studio v 1.14.2

### OS name and version

OSX

**Comment by lgandecki** [comment]
Yup! Especially since wallaybjs gets stuck from time to time, with no indication about tests running, it's easy not to notice, and think that your refactoring keeps your code green (while it's not..)

**Comment by lgandecki** [comment]
So apparently there is a spinner in the bottom right part of the screen (at least in intellij/webstorm). Somehow I've missed it, until my recent discussion with Artem. 
It provides some assurance - as long as you see it spinning, you can't be sure that the test results are correct. For me that's ok, assuming we can get wallaby not get stuck while using jest :) And I'm sure that's doable, excited for those times. ;-)

**Comment by NikGovorov** [comment]
HI @breathe,

Thanks for the feedback. We implemented loading indicator in Wallaby.js App v1.0.53, Core v1.0.671.

Regarding to adding console in Wallaby.js App, please subscribe to #1410, it is under our consideration however we don't have any specific ETA yet.
