### ISSUE TITLE
Wallaby tests do no longer run anymore with latest wallabyjs v1.0.466 update.

### ISSUE THREAD

**Issue by jp7677** [wallabyjs/public#1259]
### Issue description or question
Since a recent update the wallaby tests do no longer run anymore. The spinner keeps running forever. The console shows nothing useful, even with debug enabled. Though when running the projects tests manually I'm seeing:

 ​​​​​[Info]​​​​​ Thu, 10 Aug 2017 07:45:00 GMT wallaby:project Wallaby config: /home/.../Develop/hellocoreclr/ui/wallaby.conf.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.466
​​​​​[Info]​​​​​ Thu, 10 Aug 2017 07:46:25 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Thu, 10 Aug 2017 07:46:25 GMT wallaby:project TypeError: Cannot read property 'testFilesInOrder' of undefined
​​​​​[Info]​​​​​   at EventEmitter._createPostProcessorArgument (/home/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:17:17031)
​​​​​[Info]​​​​​   at /home/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:17:11512
​​​​​[Info]​​​​​   at Timeout._onTimeout (/home/jpeters/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:17:11318)
​​​​​[Info]​​​​​   at ontimeout (timers.js:386:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:250:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:214:5)
​​​​​[Info]​​​​​ From previous event:
​​​​​[Info]​​​​​   at Timeout._onTimeout (/home/.../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/wallaby/server.js:17:11318)
​​​​​[Info]​​​​​   at ontimeout (timers.js:386:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:250:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:214:5)
​​​​​[Info]​​​​​ Thu, 10 Aug 2017 07:46:25 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Thu, 10 Aug 2017 07:46:25 GMT wallaby:project Test run data re-queued

### Wallaby.js configuration file
See https://github.com/jp7677/hellocoreclr/blob/master/ui/wallaby.conf.js
See https://github.com/jp7677/hellocoreclr/blob/master/ui/ for  a full reproduction project.
(Note, I don't have wallaby-webpack in my package.json, you'll also need to run 'npm install wallaby-webpack' within the ui folder

### Code editor or IDE name and version
Visual Studio Code v1.14.2

### OS name and version
Linux (Fedora 26)

**Comment by ArtemGovorov** [comment]
I don't think it's the update had broken your config, as wallaby never supported absolute paths in the `files`/`tests` lists. As [specified in our docs](https://wallabyjs.com/docs/config/files.html), the paths always have to be relative.

I have [sent you the pull request](https://github.com/jp7677/hellocoreclr/pull/34) to make the config work.

We'll also have a look into why no error was reported in this case.

**Comment by jp7677** [comment]
You are absolutely right, thanks a lot!

**Comment by ArtemGovorov** [comment]
Note that there's another change I have made that you didn't merge:
```diff
       resolve: {
          extensions: ['.js'],
-        modules: [src, nodeModules]
+        modules: [path.join(wallaby.projectCacheDir, 'src')]
        }
```
You seem to be using relative paths for your imports, so it doesn't matter, but the modules path has to be pointing to wallaby cache (where all instrumented files are).

**Comment by jp7677** [comment]
Thanks for the follow-up. I was a little bit in a hurry and missed that one due to the formatting changes and mostly because it just worked after party applying your patch. I guess you didn't wanted to go through a complete review process, hence I did a similar commit ;).
Anyway, I applied your suggestion, it still works.

Thanks a lot for creating wallabyjs, really a very cool project!
