### ISSUE TITLE
would like to use wallaby.js

### ISSUE THREAD

**Issue by firecentaur** [wallabyjs/public#126]
Hi there,

I have an angular.js app created, however, I just don't know where to start in using wallaby.js
Firstly, your trial period is way to short inorder to figure out how to get it working,

I wonder, if I could hire you for an hour to set up a screenshare with me to help me with 
getting one of my controllers hooked up with wallaby to help me get started?

**Comment by ArtemGovorov** [comment]
Hello, 
Thanks for your feedback, we are working on extending the trial period.

Please send me an email to wallabyjs@gmail.com, I'll arrange you a longer trial period and will help to get started.

**Comment by ArtemGovorov** [comment]
Alternatively, please share a link to the GitHub repository with your controller and your wallaby configuration that doesn't work, I'll have a look and configure it for you.

**Comment by firecentaur** [comment]
Hi there, here is a Gist to one of my controllers.  I am really excited to use Wallaby, however, uncertain how to get started with the unit tests.  I am using Node.js

Here is my gist: https://gist.github.com/anonymous/11de25d189febd5a5cd5
