### ISSUE TITLE
Feature request: support toggling between alternative snapshot-diff view's in wallaby app

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1260]
### Issue description or question

Sometimes the snapshot diff rendering style used in the jest console is superior to the one offered by Wallaby.

Say you have a large configuration object for example -- with a few lines that have changed.  The diff view offered by Wallaby app makes this really hard to see as its more focused on representing the state of the whole snapshot than just the differences ...  The rendering offered by the jest command line is better in this scenario. 

Both rendering styles are useful and would be nice if we could toggle between them in the wallaby app ...

**Comment by ArtemGovorov** [comment]
Could you please provide a screenshot of an example? 

Would it help it wallaby current diff view would be automatically scrolled to the (first) difference? 

Or would it help if wallaby diff view would automatically hide large irrelevant parts and would only show the diff parts (with some context), similar to how jest does it, but with nice coloured highlighting as opposed to the Jest's standard line based diff?

**Comment by breathe** [comment]
Hi sorry for the delay -- yes I'm thinking it would be helpful sometimes for wallaby to show the diff's plus context.

Here's an example.  I'm snapshot diffing a somewhat large configuration object associated with my deployment system to be able to quickly identify when there are unknown sources of variation in the deployment environment or new behaviors from code changes.

The diff's rendered by wallaby are hard to use on large objects like this.  Here's wallaby's view

![screen shot 2017-08-18 at 4 45 15 pm](https://user-images.githubusercontent.com/434034/29477102-e77bf744-8434-11e7-9d71-4f30e2cee0d9.png)

And here's the jest view which only shows the diff's plus context:

![screen shot 2017-08-18 at 4 46 38 pm](https://user-images.githubusercontent.com/434034/29477140-0ee03296-8435-11e7-9659-d6fe12fa4d48.png)

Sometimes the 'full object' view that wallaby renders is more useful.  Sometimes hiding the unchanged elements of the diff is more useful.  Maybe there's a good heuristic wallaby could use to pick which way to render the diff -- or maybe it would be possible for wallaby to just supply both viewing options and let you pick which one you want to see in the wallaby app?

**Comment by IPWright83** [comment]
I raised something a little similar (that got a little off topic I think https://github.com/wallabyjs/public/issues/1127) about pretty printing output which is in a similar area. I find a lot of my diff's end up printing on one line (unless I pretty print them) which adds a significant overhead to most tests.

**Comment by ArtemGovorov** [comment]
Compact diff just landed in Wallaby App. Now the displayed diff only shows changes (with some context), while it's still possible to view the whole side-by-side diff:

![wallabyapp](https://user-images.githubusercontent.com/979966/31371081-78738750-add2-11e7-929a-afc5cd743e9c.gif)
