### ISSUE TITLE
Stale Jest Snapshots not removed

### ISSUE THREAD

**Issue by KingHenne** [wallabyjs/public#1264]
### Issue description or question

Recently I noticed that Wallaby.js keeps stale snapshots (and also syncs them back to the project root).

In the past I could update the snapshots in a separate Jest watch task, then run the VSCode task "Run Project Tests" and wallaby would update the test results with regards to the externally updated snapshots. This does not work anymore. Instead wallaby keeps or re-creates the old snapshots resulting in failing tests. If the external watch task runs the tests again the snapshots are there as well. Updating the snapshots there and re-running the VSCode task can be done over and over again. Also, restarting VSCode does not help. Only manually removing the folder in `~/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.56/projects` seems to help. 😞 

I'm wondering whether this is related to the change you mentioned in #1240.

### Wallaby.js configuration file

```javascript
'use strict';

// eslint-disable-next-line import/no-internal-modules
const loaderConfig = require('./node_modules/hops-config/sections/module-rules/babel')
  .node;
const babelConfig = loaderConfig.use.options;
const presetEnvConfig = babelConfig.presets[0][1];
presetEnvConfig.modules = 'commonjs';

module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
    },
    files: [
      'src/**/*.{ts,tsx}',
      'typings/**/*.ts',
      'spec/**/*.{ts,tsx}',
      'package.json',
      '!spec/**/*.spec.{ts,tsx}',
    ],
    testFramework: 'jest',
    tests: ['spec/**/*.spec.{ts,tsx}'],
    delays: {
      run: 500,
    },
    preprocessors: {
      '**/*.js': file =>
        // eslint-disable-next-line xing/no-extraneous-import
        require('babel-core').transform(file.content, {
          presets: [...babelConfig.presets, 'babel-preset-jest'],
          plugins: babelConfig.plugins,
          babelrc: false,
          sourceMap: true,
        }),
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.15.0

### OS name and version

macOS 10.12.5

**Comment by KingHenne** [comment]
Oh wow, it seems to work flawlessly when adding the snapshot files to the `files` list as mentioned in [this comment](https://github.com/wallabyjs/public/issues/1242#issuecomment-318535202)! 👍

**Comment by ArtemGovorov** [comment]
> it seems to work flawlessly when adding the snapshot files to the `files`

Yep, was just going to suggest it :)
