### ISSUE TITLE
How best to configure wallaby.js for lerna.js monorepo?

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1265]
I've just changed a project to a mono-repo structure (https://lernajs.io).

The project structure ends up being like this:
my-lerna-repo/
  package.json
  packages/
    package-1/
      package.json
    package-2/
      package.json

With node_modules/ directory sibling next to the nested package.json

I'm a little confused about how to handle node_modules/ in the wallaby config -- should these be added to files array?

**Comment by breathe** [comment]
NVM -- found it in the docs.

https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

In your case you may need to use `wallaby.projectCacheDir` instead of `wallaby.localProjectDir` (if you expect wallaby to process/instrument modules as opposed to just be loading them from your local project as is). See this sample: https://github.com/thomastnguyen91/wallaby-issue-959/pull/1/commits/193e86adcee6f7c328bb1303569c91b0fd94a2d4

**Comment by vjpr** [comment]
@ArtemGovorov This is problematic if you are using scoped packages, but do not nest them in their `@scope` dir in the `packages` dir...which is [valid in lerna](https://github.com/lerna/lerna/issues/185#issuecomment-333592307).

E.g. `packages/foo-bar/package.json` = `{name: '@foo/bar'}`

The `NODE_PATH` modification won't work.

The only solution seems to be to symlink `instrumented/packages/foo-bar/node_modules/@foo/baz` to the correct module, or some kind of require-hack.

Maybe it is just easier to nest them...

**Comment by ArtemGovorov** [comment]
@vjpr Could you please create a sample repo with the issue(s)? I'm happy to have a look to see what's going on and what'd be the best way to configure it in wallaby.

**Comment by ArtemGovorov** [comment]
@vjpr Had some time to play with it, created [this repo with a solution](https://github.com/ArtemGovorov/wallaby-1265). Basically the idea is to [use module aliasing](https://github.com/ArtemGovorov/wallaby-1265/blob/master/wallaby.js#L26-L29). 

I think module aliasing is something that should ideally be built-in into node itself, to avoid using dirty tricks and hacks such as symlinks/require-hacks.

**Comment by vjpr** [comment]
I went for the `babel-plugin-module-resolver` as its easier to debug because you can check the require rewrite in the instrumented files.

```js
function moduleResolverPlugin(wallaby) {
  return [
    'module-resolver',
    {
      alias: {
        '^@foo/(.+)': wallaby.projectCacheDir + '/packages/\\1',
      },
    },
  ]
}
```

**Comment by ArtemGovorov** [comment]
@vjpr Nice, didn't think of the compile time solution, thanks for sharing!

**Comment by ArtemGovorov** [comment]
Also, if anyone is looking for a solution of how to configure Wallaby for lerna.js monorepo for Jest, here's another way to do it - https://github.com/wallabyjs/public/issues/1374#issuecomment-342017179. So if your scope name is `@private-package`, the solution looks like:

```javascript
const path = require("path");

module.exports = function(wallaby) {
  return {
    ...

    setup: w => {
      const jestConfig = require('./package.json').jest;
      jestConfig.moduleNameMapper = {
        '^@private-package/(.+)': w.projectCacheDir + '/packages/$1',
      };
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

**Comment by vjpr** [comment]
@ArtemGovorov Regarding the solution I proposed, I've found a slight issue.

When I delete the cache dir I see a bunch of these errors in the log:

```
Could not resolve "/Users/Vaughan/Library/Caches/IntelliJIdea2017.3/wallaby/projects/c682bc127da20367/instrumented/packages/db" in file /Users/Vaughan/dev-live/vwp/packages/rethink-import/index.js.
```

Seems that wallaby attempts to resolve requires when it compiles, before all the files have been transpiled.

**Comment by zpydee** [comment]
I am encountering an issue when using wallaby in my lerna project wherein the number of tests reported is incorrect.

If Package A has 10 tests,
and Package B has 20 tests,
then instead of correctly reporting 30 tests having been run, wallaby reports 40 tests:

- 10 tests for Package A
- 20 tests for Package B
- 10 tests for Package A imported by Package B

not sure if my config is the issue?

```
module.exports = function (w) {

  process.env.NODE_ENV = 'test';

  return {
    files: [
      { pattern: 'packages/**/src/**/*.ts', load: true },
      { pattern: 'packages/**/src/**/*.spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'packages/**/src/**/*.spec.ts', load: true }
    ],

    filesWithNoCoverageCalculated: [
      'packages/**/src/index.ts',
      'packages/**/src/spec-helpers/**/*.ts'
    ],

    env: {
      type: 'node'
    },

    testFramework: 'jasmine',

    // added for mongoose related errors
    workers: {
      recycle: true,
      initial: 1,
      regular: 1
    }

  };
};
```

**Comment by ArtemGovorov** [comment]
@zpydee You need to [exclude `node_modules` inside packages](https://github.com/thomastnguyen91/wallaby-issue-959/commit/193e86adcee6f7c328bb1303569c91b0fd94a2d4#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR13). Otherwise Wallaby runs 10 tests for `Package A` and 10 tests for `Package B/node_modules/Package A`.

```diff
module.exports = function (w) {

  ...

  return {
    files: [
      { pattern: 'packages/**/src/**/*.ts', load: true },
      { pattern: 'packages/**/src/**/*.spec.ts', ignore: true },
+     { pattern: 'packages/**/node_modules/**', ignore: true }
    ],

    ...

  };
};
```

**Comment by ArtemGovorov** [comment]
@zpydee Sorry, missed the exclusion for `tests`:

```diff
module.exports = function (w) {

  ...

  return {
    files: [
      { pattern: 'packages/**/src/**/*.ts', load: true },
      { pattern: 'packages/**/src/**/*.spec.ts', ignore: true },
+     { pattern: 'packages/**/node_modules/**', ignore: true }
    ],

    tests: [
      { pattern: 'packages/**/src/**/*.spec.ts', load: true },
+     { pattern: 'packages/**/node_modules/**', ignore: true }
    ],

    ...

  };
};
```

**Comment by zpydee** [comment]
thx, should have figured that out myself I guess :-)
