### ISSUE TITLE
Cannot install wallaby.js core behind http proxy in Sublime Text 3

### ISSUE THREAD

**Issue by smilingsun** [wallabyjs/public#1266]
### Issue description or question

Always installing when starting the wallaby.js, and no output in console although in debug mode.

![image](https://user-images.githubusercontent.com/4011348/29364695-efaef688-82c6-11e7-934f-0e2bcdde3b50.png)

![image](https://user-images.githubusercontent.com/4011348/29364867-7a3812a8-82c7-11e7-8308-22a47fd9726d.png)

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};
```

### Code editor or IDE name and version

Sublime Text v3 build 3126

### OS name and version

Windows 10 Version 1607

**Comment by ArtemGovorov** [comment]
Wallaby Sublime Text package is using the standard `urllib` to download the required dependencies. According to [this answer](https://stackoverflow.com/a/3168244/146850), proxy settings can be supplied by setting the `http_proxy` [environment variable](https://i.stack.imgur.com/ZeExG.png) on your machine. Apart from setting the `http_proxy`, also set the `https_proxy` environment variable.

If it doesn't help, please follow the steps of [the offline installation guide](https://wallabyjs.com/docs/intro/troubleshooting.html#sublime-text).
