### ISSUE TITLE
VSCode Clipboard with http://localhost/wallaby_sandbox0.html

### ISSUE THREAD

**Issue by leocaseiro** [wallabyjs/public#1267]
### Issue description or question
Hi, I would like to disable the action that keeps replacing my clipboard with some localhost for wallaby that not even works.
Eq: `http://localhost:50476/wallaby_sandbox1.html`

I'm not sure why and when it happens, but most of the time is when I hit Cmd+S to save.

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

const compilerOptions = Object.assign(
    require('./tsconfig.json').compilerOptions,
    require('./Source/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

    const webpackPostprocessor = wallabyWebpack({
        entryPatterns: [
            'Source/wallabyTest.js',
            'Source/**/*spec.js'
        ],

        module: {
            loaders: [
                { test: /\.css$/, loader: 'raw-loader' },
                { test: /\.html$/, loader: 'raw-loader' },
                { test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: { tsConfigPath: 'tsconfig.json' } },
                { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
                { test: /\.json$/, loader: 'json-loader' },
                { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
                { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
                { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
                { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
            ]
        },

        resolve: {
            extensions: ['.js', '.ts'],
            modules: [
                path.join(wallaby.projectCacheDir, 'Source')
            ]
        }
    });

    return {
        files: [
            { pattern: 'Source/**/*.ts', load: false },
            { pattern: 'Source/**/*.d.ts', ignore: true },
            { pattern: 'Source/**/*.css', load: false },
            { pattern: 'Source/**/*.less', load: false },
            { pattern: 'Source/**/*.scss', load: false },
            { pattern: 'Source/**/*.sass', load: false },
            { pattern: 'Source/**/*.styl', load: false },
            { pattern: 'Source/**/*.html', load: false },
            { pattern: 'Source/**/*.json', load: false },
            { pattern: 'Source/**/*spec.ts', ignore: true }
        ],

        tests: [
            { pattern: 'Source/**/*spec.ts', load: false }
        ],

        testFramework: 'jasmine',

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
        },

        middleware: function (app, express) {
            var path = require('path');
            app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
            app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
        },

        env: {
            kind: 'electron'
        },

        postprocessor: webpackPostprocessor,

        setup: function () {
            window.__moduleBundler.loadTests();
        },

        debug: true
    };
};

```

### Code editor or IDE name and version

Visual Studio Code: Version 1.15.1 (1.15.1)

### OS name and version

OSX: macOS Sierra: Version 10.12.5

**Comment by ArtemGovorov** [comment]
I can't reproduce it and it's the first time I hear about something like this. I'm not even sure if it is wallaby related - we don't even have any commands/actions that touch clipboard.

Just to make it clear what's going on:
- you `Cmd + C` something, 
- then you hit `Cmd + S` and your clipboard content gets replaced with something like `http://localhost:50476/wallaby_sandbox1.html`?

As we only pass the strings like `http://localhost:50476/wallaby_sandbox1.html` to display in the Wallaby Console output channel, try setting `debug: false` in your wallaby config to see if it helps.

Also, to check if the issue is not caused by some other extension, please try installing [VS Code insiders build](https://code.visualstudio.com/insiders) (without any extensions), install wallaby and try running the project to see if the error is reproduced. If not, it must be some other extension copying wallaby output to clipboard.

**Comment by ArtemGovorov** [comment]
More I think about it, more it looks like it is some other extension interferes with Wallaby Console and is copying links from it. So please try the steps described above and also share the full list of extensions you have installed, I can scan their source to see if they may be doing something with clipboard.

**Comment by leocaseiro** [comment]
Hi @ArtemGovorov, thanks for your reply.

Yeap, you understood correctly. That exactly what's going on.

I'll try disabling all other extensions, as well installing with insiders build, and disable the debug and I'll back to you with the news.

**Comment by leocaseiro** [comment]
You can see all my settings from my VSCode that are synced on my gist: https://gist.github.com/leocaseiro/3f3de784dc77afb1e8402956c56116bf

You can use [VISUAL STUDIO CODE SETTINGS SYNC](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) to import and test yourself.

PS: Unfortunately, it's intermittent. Which means sometimes happens and sometimes doesn't. Perhaps, it replaces my clipboard if a test is failing or not. I still not able to detect when it happens, though.

**Comment by leocaseiro** [comment]
In case you are used to the `code --list-extensions`

```
AndersEAndersen.html-class-suggestions
Angular.ng-template
CoenraadS.bracket-pair-colorizer
DavidAnson.vscode-markdownlint
DmitryDorofeev.empty-indent
EditorConfig.EditorConfig
GreatMinds.gitflow4code
HvyIndustries.crane
IBM.output-colorizer
MariusAlchimavicius.json-to-ts
RoscoP.ActiveFileInStatusBar
Shan.code-settings-sync
SimonTest.simontest
Sophisticode.php-formatter
Telerik.nativescript
Tyriar.sort-lines
WallabyJs.wallaby-vscode
abierbaum.vscode-file-peek
akamud.vscode-caniuse
alefragnani.Bookmarks
alefragnani.project-manager
bgse.relative-path-and-line
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
coderfee.open-html-in-browser
donjayamanne.githistory
donjayamanne.python
eamodio.gitlens
eg2.ts-tslint
eg2.tslint
eg2.vscode-npm-script
felixfbecker.php-intellisense
formulahendry.auto-rename-tag
hangxingliu.vscode-nginx-conf-hint
hoovercj.vscode-settings-cycler
hunter-dev.volt
ikappas.phpcs
infinity1207.angular2-switcher
ipatalas.vscode-postfix-ts
jacobkantzer.case-sensitive-add-next
jakethashi.vscode-angular2-emmet
jasonnutter.search-node-modules
joelday.docthis
johnpapa.Angular2
junstyle.php-cs-fixer
lafe.contextualduplicate
linyang95.php-symbols
lixquid.calculator
makao.phpcsfixer
miclo.sort-typescript-imports
minhthai.vscode-todo-parser
mrmlnc.vscode-scss
ms-vscode.typescript-javascript-grammar
msjsdiag.debugger-for-chrome
natewallace.angular2-inline
patrys.vscode-code-outline
peterjuras.sort-imports
pflannery.vscode-versionlens
pmneo.tsimporter
pprice.better-merge
pranaygp.vscode-css-peek
rbbit.typescript-hero
robertohuertasm.vscode-icons
sanderledegen.angular-follow-selector
sasa.vscode-sass-format
sashaweiss.bracket-jumper
shanoor.vscode-nginx
shardulm94.trailing-spaces
steoates.autoimport
vector-of-bool.gitflow
webstp.extension-manager
whtouche.vscode-js-console-utils
wmaurer.change-case
xabikos.JasmineSnippets
```

**Comment by ArtemGovorov** [comment]
Thanks, that's a lot of extension, may take me a while to find the offender.

But, as I have mentioned, there's a easy way to completely stop wallaby producing the strings like `http://localhost:50476/wallaby_sandbox1.html`, so whatever copies them, will have to stop doing or so (or start polluting the clipboard with something else):

```javascript
module.exports = function (wallaby) {

    return {
        ...
        debug: false
    };
};
```

**Comment by leocaseiro** [comment]
Hi @ArtemGovorov 
Yeap, I'm addicted by extensions LOL.

I'll have to give a try on Monday, but I hope that will do it.
I'll get back to you with news soon.

Many many thanks for the amazing extension and for the support as well.

**Comment by leocaseiro** [comment]
Hi @ArtemGovorov,

I've disabled the `debug` and it seems the problem is not occurring anymore.

I appreciate your help.

I'm closing this issue.
