### ISSUE TITLE
Isolate test files and mocha before() runs

### ISSUE THREAD

**Issue by Samenai** [wallabyjs/public#1269]
### Issue description or question

My integration and model spec files run mocha before() tasks to reset and then seed the database with data that the code needs to complete tests.  My normal testing process would isolate the files and run them one by one, but Wallaby is attempting to run them quicker than possible, either causing MySQL issues (cannot delete row or cannot update row) or causing tests to fail (entry doesn't exist or test fails due to entries existing)

Is it possible to have Wallaby run each file isolated to the rest?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'server/**/!(*.spec|*.integration).js',
      '!server/config/local.env.sample.js',
      '!server/config/localtest.env.js',
      '!server/config/local.env.js'
    ],
    tests: [
      'server/**/index.spec.js',
      'server/**/*.integration.js',
      'server/**/*.model.spec.js'
    ],
    testFramework: 'mocha',
    compilers: {
      'server/**/*.js': wallaby.compilers.babel()
    },
    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      regular: 1,
      initial: 1,
      recycle: true,
    },
    setup: function () {
      console.log('global wallaby setup');

      var chai = require('chai');
      global.expect = chai.expect;
      global.assert = chai.assert;
      global.should = chai.should();
      global.sinon = require('sinon');
      chai.use(require('sinon-chai'));
      chai.use(require('chai-as-promised'));
      chai.use(require('chai-things'));
    },
    teardown: function(){
      console.log('global wallaby teardown');
    },
  };
};
```

### Code editor or IDE name and version

WebStorm v2017.2.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> My normal testing process would isolate the files and run them one by one, but Wallaby is attempting to run them quicker than possible, either causing MySQL issues

With your current workers setting:

```javascript
    workers: {
      regular: 1,
      initial: 1,
      recycle: true,
    },
```

wallaby is supposed to work exactly like you have described: it should run your test files one by one in a single process. You may make sure that is is happening by adding the `process.pid` to your logged message:

```javascript
    setup: function () {
      console.log('global wallaby setup: ' + process.pid);
      ...
```
Now you should only see one process ID being logged, while if you remove the workers setting there'll be multiple process IDs logged.

Try this, and if you only see one process ID being logged, then wallaby does run your tests in one process and sequentially, so the issue must be something else than parallelisation.

- Does the first run always succeed and only when you start editing individual files it starts to fail, or it is failing right from the start?
- Where is your mocha `before` hook located? Are you sure it's being called by wallaby? Do you have any `after` hooks?
- When you say your "normal testing process would isolate the files and run them one by one", I understand the bit about running them one by one, but what do you mean by "isolate the files"?
- Could you please create a sample project demonstrating then issue? That'd be the fastest way for me to get it working for you.

**Comment by Samenai** [comment]
Looks like it's all good actually... In an attempt to grab some logs for you on my second development machine, it worked perfectly and successfully ran with all my tests.  So this is a local issue to my first development machine.  I'll compare the differences and figure out what's going on with it.

Thanks for helping.  I'll update this comment with the differences on Monday in case someone else runs into this issue.
