### ISSUE TITLE
i have a problem wallaby extantion for visualstudio 

### ISSUE THREAD

**Issue by samiozer** [wallabyjs/public#127]
viasfor extantion disable while trying wallaby but does not work when enable

**Comment by samiozer** [comment]
It does not work with vscommands

**Comment by ArtemGovorov** [comment]
Could you please provide more details on what exactly doesn't work, perhaps some screenshots? I have tried installing vscommands, everything works for me. What OS and VS version do you have, what other extensions do you have installed?

**Comment by ArtemGovorov** [comment]
We have fixed a few things addressing various compatibility issues with other extensions. Please try the latest version and let me know if the issue is still there for you.
