### ISSUE TITLE
Babel's regenerator applied unnecessary

### ISSUE THREAD

**Issue by speedboat** [wallabyjs/public#1272]
### Issue description or question
My config file does not have any plugins or presets for async/await transformation, but wallaby still applies it causing "regeneratorRuntime is not defined". Adding babel-polyfill everywhere is a workaround, but after Node 7.6 we have native async/await support.

### Wallaby.js configuration file

```javascript
compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: require("babel-core"),
                plugins: [
                    require("babel-plugin-transform-flow-strip-types")
                ]      
            }),         
}
```
### Code editor or IDE name and version
Visual Studio Code v1.15

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Wallaby doesn't (well shouldn't) apply any plugins or presets apart from those specified in your config.

I have created this simple repo with your compilers config: https://github.com/ArtemGovorov/wallaby-1272. It's working as expected and not causing "regeneratorRuntime is not defined" errors. 

I suspect it may be something else that is causing the issue. Could you try the repo to see if it's working for you and if yes, then please fork it and add the missing bits to reproduce the issue.

**Comment by ArtemGovorov** [comment]
I suspect the issue may have been fixed as a part of https://github.com/wallabyjs/public/issues/1289. If it is still a valid issue for you, please fork the above mentioned repo and add the missing bits to reproduce the issue
