### ISSUE TITLE
code --install-extension WallabyJs.wallaby-vscode doesn't work

### ISSUE THREAD

**Issue by clintmod** [wallabyjs/public#1274]
### Issue description or question
09:43 $ code --install-extension WallabyJs.wallaby-vscode
Found 'WallabyJs.wallaby-vscode' in the marketplace.
Installing...
(node:44871) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this._state.then is not a function
(node:44871) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
### Wallaby.js configuration file

```javascript
N/A
```

### Code editor or IDE name and version
Visual Studio Code - Version 1.15.1 (1.15.1)

### OS name and version
Mac OS Sierra 10.12.5 (16F73)

**Comment by ArtemGovorov** [comment]
This is not a wallaby.js specific issue, CLI installation for ANY extensions is currently broken in VS Code: https://github.com/Microsoft/vscode/issues/32381.
