### ISSUE TITLE
Code Coverage Comment failing in weird ways

### ISSUE THREAD

**Issue by alexandertrefz** [wallabyjs/public#1275]
### Issue description or question

The ignoreCoverage comment seems to not function consistently:
In VS Code:
<img width="685" alt="screenshot 2017-08-27 21 10 24" src="https://user-images.githubusercontent.com/231650/29753200-56dbd18e-8b6c-11e7-8734-d850b7d7212d.png">
In Wallabyjs App:
<img width="644" alt="screenshot 2017-08-27 21 10 01" src="https://user-images.githubusercontent.com/231650/29753204-5dc8bee4-8b6c-11e7-973c-0a5ae2cd9dae.png">

Here is the code itself for your Repro purposes: (I can paste this exact snipper into a new file and it reproduces the issue on my machine)
```typescript
export enum TokenType {
	LiteralTrue   = 'LiteralTrue',
	LiteralFalse  = 'LiteralFalse',

	KeywordType  = 'KeywordType',
	KeywordIf    = 'KeywordIf',
	KeywordElse  = 'KeywordElse',
}

const getBooleanType = (value: string) => {
	if (value === 'true') {
		return TokenType.LiteralTrue
	} else if (value === 'false') {
		return TokenType.LiteralFalse
	} else {
		/* ignore coverage */
		throw new Error(`${value} is not a valid value for BooleanLiterals`)
	}
}

const getKeywordType = (value: string) => {
	if (value === 'if') {
		return TokenType.KeywordIf
	} else if (value === 'else') {
		return TokenType.KeywordElse
	} else if (value === 'type') {
		return TokenType.KeywordType
	} else {
		/* ignore coverage */
		throw new Error(`${value} is not a valid value for Keywords`)
	}
}
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
	return {
		files: [
			'src/**/*.ts',
			'!src/tests/*.ts'
		],
		tests: [
			'src/tests/*.ts'
		],
		env: {
			type: 'node'
		},
		hints: {
			ignoreCoverage: /ignore coverage/
		},
		testFramework: 'jasmine'
	}
}
```

### Code editor or IDE name and version
Visual Studio Code Version 1.16.0-insider

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for providing the code to reproduce the issue!

It's fixed now and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
