### ISSUE TITLE
Wallaby kicks node into overdrive

### ISSUE THREAD

**Issue by maierson** [wallabyjs/public#1279]
### Issue description or question
As soon as I start wallaby test runner several node processes are spawn that overwhelm the CPU. Typing gets slower in the IDE. This is a snapshot of ActivityMonitor.
![screenshot 2017-08-29 09 02 52](https://user-images.githubusercontent.com/16655922/29822708-61db05bc-8c9a-11e7-8a28-6de26836f316.png)
As soon as I stop wallaby (verified several times):

![screenshot 2017-08-29 09 04 09](https://user-images.githubusercontent.com/16655922/29822715-693b1bc6-8c9a-11e7-8081-3b821797c05e.png)

This seems to have happened after the latest update this morning (0.474 I think).

### Wallaby.js configuration file

```javascript

module.exports = function w(wallaby) {
  const path = require("path"); //eslint-disable-line
  process.env.NODE_PATH += path.delimiter +
    path.join(wallaby.localProjectDir, "app/base/assets");

  return {
    debug: true,

    files: [
      "package.json",
      "app/**/*.json",
      "tsconfig.json",
      "app/**/*.ts?(x)",
      "app/**/*.css",
      "app/**/*.svg",
      "!app/**/*spec.ts?(x)",
    ],

    tests: ["app/**/*spec.ts?(x)"],
   
    compilers: {
      "**/*.ts?(x)": wallaby.compilers.typeScript({
        module: "commonjs", // jscs:ignore
        jsx: "react",
      }),
    },

    env: {
      type: "node",
      runner: "node",
    },

    testFramework: "jest",

  };
};


```

### Code editor or IDE name and version

Visual Studio Code v1.15.1?

### OS name and version
OSX Sierra

Thank you.

**Comment by ArtemGovorov** [comment]
After you start wallaby, does the high load drop after the initial test run finishes? Could you please start wallaby, wait for coverage indicators to show up in your editor for some file, wait a couple of seconds and them make a screenshot of node processes?

If the load drops after the initial run, then everything is working as expected. Wallaby had always been starting multiple processes to run tests in parallel, nothing had changed in that regard in the recent wallaby updates.

When you start wallaby, it runs all of your tests in parallel, using the number of processes (that is the number of your CPU cores).

The actual load depends on what your tests are doing. If they need 100% of a process CPU time, then they'll take it.

You may [control the number of processes used to run your tests](https://wallabyjs.com/docs/config/workers.html), for example try reducing it to 2 or even 1:

```javascript
module.exports = function w(wallaby) {
  ...

  return {
    ...
     workers: {
       initial: 2,
       regular: 2
     }
  };
};
```

**Comment by maierson** [comment]
Hi Artem,

Thank you for this. Indeed the processes drop back to 1.

![screenshot 2017-08-29 20 22 36](https://user-images.githubusercontent.com/16655922/29849962-1f35f574-8cf8-11e7-852d-eaf4d7361f4a.png)

But as soon as I make the smallest change (ie just typing a new line in a tested file) they cycle back up and wallaby execution lasts for quite a while. This is what's in the activity monitor after typing a new line in one of the action factory files.

![screenshot 2017-08-29 20 24 37](https://user-images.githubusercontent.com/16655922/29849994-5fa5c350-8cf8-11e7-9d36-6241fb3901f9.png)

I was under the impression that only the affected tests were being re-run. In this case there shouldn't be any since no code was changed. Is this a correct understanding?

I tried changing the workers to just 1 but in that case it all takes even longer. 
We currently have a little over 3,300 tests. Can this be an issue?

Lastly - is there a configuration in wallaby.js to provide node with more ram at startup? I've read about people having issues with node running on its default max 1.7GB.

**Comment by ArtemGovorov** [comment]
> Indeed the processes drop back to 1.

Looks like it is working as expected.

> But as soon as I make the smallest change (ie just typing a new line in a tested file) they cycle back up and wallaby execution lasts for quite a while

If the "tested" file is covered by many tests it is possible. Try changing a single test in a test file (in this case just that test file/test should be running) and see how it affects the load.

> I was under the impression that only the affected tests were being re-run. In this case there shouldn't be any since no code was changed. Is this a correct understanding?

Adding a line is a code change (which may actually result in a change of the code behaviour under certain circumstances).

> I tried changing the workers to just 1 but in that case it all takes even longer. We currently have a little over 3,300 tests. 

It makes sense, because with one worker tests will take longer to execute than with a few workers running them in parallel. It is a tradeoff between the execution speed and the load on your CPU. You may set the number of workers to 10 and it will be theoretically 10 times faster, but will have 10 times more impact on your CPU.

I'd suggest to experiment and to find the number of workers that don't slow down typing in the IDE. Obviously one worker shouldn't affect it much,  how about 2-3-4?

> Lastly - is there a configuration in wallaby.js to provide node with more ram at startup? I've read about people having issues with node running on its default max 1.7GB.

You may pass any flags to node via the [`env.params.runner` setting](https://wallabyjs.com/docs/config/runner.html). From [what I could find there's the `--max_old_space_size` flag](http://prestonparry.com/articles/IncreaseNodeJSMemorySize/) that you may try setting. However I'm not sure if RAM is an issue here (you may double check how much RAM the worker node processes consume in the Memory tab of the activity monitor).

**Comment by ArtemGovorov** [comment]
Also, wallaby runs Jest with your setup, so it also largely depends on how fats Jest is able to run your tests and what kind of CPU load does it produce when doing so. Could you run Jest from CLI (without wallaby) on your project to see how the CPU is affected?

One more thing, you've also mentioned that 

> This seems to have happened after the latest update this morning

Did it work differently earlier? Since there were no changes that I could think of that could affect the performance, perhaps there were some recent changes in your environment (such package update, jest settings update, node version update)?

**Comment by maierson** [comment]
Ok. I've run jest via the cli and it has the exact same behavior (it runs 7 workers out of the box and each maxes out to over 100% of CPU). 
Also running wallaby with 10 workers does seem to lessen the load on each individual worker (from 100%+ to about 79% CPU / worker). So everything seems to be working correctly. 

The only part where I could see an improvement is in re-running changed tests. Right now it seems to run all tests related to all code in a file on any change in the file. So if I have 10 actions in the factory file it seems to be running the tests related to all of them (I assume all reducer tests, components dispatching actions, middleware etc) when only one is changed. The activity monitor load spikes up again. Also wallaby seems to make a quick 3-5 seconds run (which is what I would expect) and then a second much longer run (~60s) - where I assume it's testing all other related code.

Not sure if it would be possible to cache the code that has already been "run" in order to re-test only the changed action related tests. It would be a big time saver. In the meanwhile I can always run wallaby on a smaller subset of tests to keep it snappy. It's hard to use anything else once you get used to it. It's really a fantastic tool.

Re the new version - that was a subjective perception and I'm pretty sure by now the issue is not from that but rather from the fact that our test coverage has increased.

I'll try a couple of other things (notably the node --max_old_space_size) and if I find anything else will post it here.

Thanks again.

**Comment by maierson** [comment]
@ArtemGovorov I've run into a couple of pages detailing modes of setting the max-old-space-size in a launch configuration for vscode:

https://code.visualstudio.com/docs/nodejs/nodejs-debugging
https://github.com/Microsoft/vscode/issues/10149

But I'm not quite sure what such a configuration for wallaby would look like since it's not currently running from the cli. Any suggestions?

**Comment by ArtemGovorov** [comment]
@maierson You may pass any flags to node via the [`env.params.runner` setting](https://wallabyjs.com/docs/config/runner.html). 


```javascript
module.exports = function () {
  return {
    ...

    env: {
      ...

      params: {
        runner: '--max_old_space_size=...'
      }
    }
  };
};
```

**Comment by maierson** [comment]
Yes. Tried that. Didn't seem to make a difference. Thank you anyways.

**Comment by rhysawilliams2010** [comment]
@maierson there was a typo in artem's comment. use "--max-old-space-size" (with dashes *not* underscores).

```
module.exports = function () {
  return {
    ...

    env: {
      ...

      params: {
        runner: '--max-old-space-size=...'
      }
    }
  };
};
```
