### ISSUE TITLE
does wallaby support jest's moduleNameMapper configuration?

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1281]
### Issue description or question

Not sure if its me or if wallaby doesn't support jest's moduleNameMapper configuration?  Is there a way to get wallaby to use the moduleNameMapper as from below:

```
  "jest": {
    "globals": {
      "ts-jest": {
        "skipBabel": true
      }
    },
    "testEnvironment": "node",
    "transform": {
      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "moduleNameMapper": {
      "^.*/Configuration/(.*)-shim.js$": "<rootDir>/src/Configuration/$1"
    }
}
```

I'm trying to test code which:
- parses and processes a yml file
- certain directives within the yml file cause javascript require("./path/to/Configuration/someModule-shim") statements to execute
- the yml directives ("./path/to/someModule-shim") in these files normally target compiled js artifacts, however in jest context I use moduleNameMapper to redirect these request's at 'require' time to the source typescript (which ts-jest will pre-process)  

Some way to achieve similar in wallaby context?

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      "./*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*",
      "serverless-services/*",
      "serverless-services/**/*.yml",
      "!src/**/*.test.ts"
      // "lib/**/*.js",
      // "!lib/**/*.test.js"
    ],

    tests: ["src/**/*.test.ts", "!src/service-tests/*.test.ts"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: false,
    testFramework: "jest"
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.15.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I'm pretty sure it is possible with wallaby, however it's hard to tell what is wrong without more information.

Try [adjusting your Jest config for wallaby](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) as follows:

```diff
 module.exports = function () {

   return {
     files: [
       ...
+       'package.json', // or jest.config.js depending on where your config is
       ],

       ...

+     setup: function (wallaby) {
+       var jestConfig = require('./package.json').jest;
+       jestConfig. moduleNameMapper = {
+           "^.*/Configuration/(.*)-shim.js$": wallaby.projectCacheDir + "/src/Configuration/$1" };
+       wallaby.testFramework.configure(jestConfig);
     }
   };
 };
```

If it doesn't help, please create a sample repo where I could reproduce the issue - I'll jump in and help configuring it.

**Comment by kimjuny** [comment]
Hi, I can confirm wallaby doesn't load and configure `jest.config.js` automatically as [document](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) says, even if I imported `jest.config.js` as file manually in wallaby configuration. I have to manually setup jest configuration as you did above. I'm using vscode.

**Comment by ArtemGovorov** [comment]
@kimjuny Hi, wallaby fully supports the scenario you've described. It automatically loads `jest.config.js` file (if it can find it). I have created this simple sample branch to demonstrate it -
 https://github.com/wallabyjs/wallaby-jest-sample/tree/jest-config. If you clone the sample repo, run `npm i` and run wallaby, it should run the test successfully. However, if you change the [`jest.config.js` file defined `automock` setting](https://github.com/wallabyjs/wallaby-jest-sample/blob/jest-config/jest.config.js#L2) to `false`, the test will start failing.

Perhaps wallaby can't find your `jest.config.js` because it is in a different folder? If it's un the same folder and still don't work for you, please create a sample repo demonstrating the issue (you may just fork the sample I have provided if you like).

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please provide the info requested above.

**Comment by thephw** [comment]
@ArtemGovorov This still seems to be an issue. More specifically when an entry in the setting for `moduleNameMapper` starts with `<rootDir>` wallaby is resolving `rootDir` to `~/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/7713c9f573b55d8c/instrumented`
