### ISSUE TITLE
[Error] ​​Postprocessor run failure: Debug Failure. ​​

### ISSUE THREAD

**Issue by urish** [wallabyjs/public#1282]
### Issue description or question

I am occasionally getting the above error message in VSCode's "Wallaby Tests" output window, and then wallaby shows an "X" symbol in the status bar and stops running the tests. Restarting wallaby fixes this, but then it returns after a while.

### Wallaby.js configuration file

```javascript
module.exports = function () {

	return {
		files: [
			'jest-setup-frontend.ts',
			'src/**/*.ts?(x)',
			'src/**/*.js',
			'src/**/*.snap',
			'!src/**/*.spec.ts?(x)'
		],

		tests: ['src/**/*.spec.ts?(x)'],

		env: {
			type: 'node',
			runner: 'node'
		},

		testFramework: 'jest'
	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.15.1

### OS name and version

Windows 10 Creators Update

**Comment by ArtemGovorov** [comment]
From the error message is looks like the error is raised from TypeScript (not from wallaby code). Could you please share your `tsconfig.json` file and version of TypeScript (from your `package.json`)?

**Comment by urish** [comment]
Sure Artem, here is my tsconfig.json:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "allowSyntheticDefaultImports": true,
    "lib": ["es2015", "dom"],
    "jsx": "react"
  }
}
```

and this is TypeScript 2.4.0

**Comment by ArtemGovorov** [comment]
Thanks! 
One more question - how frequently the error shows up? Once per hour/few hours/day? 

Also any special action(s) that you might have noticed preceding the error? Like adding/deleting files, adding/changing a specific code pattern?

**Comment by urish** [comment]
Hi Artem,

The error showed up every 15-20 minutes when I was actively working on that project, I am not very sure about the pattern - I was more focused on getting the work done that day, so I just quickly restarted wallaby whenever it happened. 

I will be spending the next week travelling to conferences, so it is not very likely that I will get an opportunity to work on the project again in the next few days. Next time when I work on it, I can set up screen recording so when this happens, I could go back and see which event preceded it. Are there any other suggestions that can help you figure it out?

**Comment by ArtemGovorov** [comment]
> Are there any other suggestions that can help you figure it out?

Yes, please add the `debug: true` flag to your wallaby config, 

```diff
module.exports = function () {

	return {
		...
+               debug: true
	};
};
```

and the next time the error shows up, please copy/paste the full error stack [from the Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by urish** [comment]
Thanks, I will!

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please provide the info requested above.
