### ISSUE TITLE
Support Qunit 2

### ISSUE THREAD

**Issue by dalner** [wallabyjs/public#1283]
### Issue description or question
I'm trying to use Qunit2 Framework and it appears that Wallaby is only bringing in v1.8. Is there a way to configure wallaby to bring in a newer qunit version? I've tried setting the testFramework: 'qunit@2.4.0' with no luck. Any suggestions would be appreciated.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
      return {
         files: [
               ...
         ],

         tests: [
                ...
         ],
         debug: true,
         slowTestThreshold: 5000, // 5000ms
         testFramework: 'qunit'
      }
}
```

### Code editor or IDE name and version

Visual Studio v1.15

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
At the moment, wallaby only supports Qunit 1.x. Qunit 2.x is not yet supported.

**Comment by dalner** [comment]
Is there an ETA on support for it?

**Comment by ArtemGovorov** [comment]
There's no ETA yet, when the status changes - I'll post an update here.

**Comment by ArtemGovorov** [comment]
The first beta version of QUnut 2 support is landed in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version 1.0.480. The `testFramework: 'qunit@2.4.0'` setting should be specified in order to use it.

```javascript
module.exports = function(wallaby) {
      return {
         ...
         testFramework: 'qunit@2.4.0'
      }
}
```
