### ISSUE TITLE
Web app coverage popup

### ISSUE THREAD

**Issue by stychu** [wallabyjs/public#1286]
Hello,
I'am currently trying test version of wallaby.js and so far I love it very much! The boost in performance, productivity and comfort when it comes with wallaby is amazing!.
I would like to suggest one thing that you may consider in adding. Its not something urgent or crucial but I think it somehow helps in overall look.

When you look at the  wallaby web app on the specific test coverage of file u see the popup with the code of file and lines that are covered or not. It would be amazing if you could add difference in seeing comments and comments with `TODO` like in IntelIJ Idea products. When there is Comment with TODO its in different color from regular comment. I think this would help in some cases.
Second thing I would reccomend is adding possibility to resize the popup window when u look at coverage file. Its anoying that i can't resize the popup and have to just select text to the right side to see whats there. It would be nice to have resize option or horizontal bar. If code is really nested its hard to see it on this popup.

Looking forward to buy the license once i get some funds.
Keep awesome WORK!

**Comment by ArtemGovorov** [comment]
Thanks for your feedback!

Regarding the popup size, Wallaby App has the [`Files`](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#files) tab, where you could select an individual file and get the resizable editor on the right hand side:

![f](https://user-images.githubusercontent.com/979966/30025247-ea707266-91ba-11e7-984e-b1ce0cc55727.gif)

Perhaps it may help.

**Comment by NikGovorov** [comment]
Hi @stychu,

We addressed the second issue by significantly increasing size of the window in the recent versions of Wallaby.js App. Regarding to the second issue, unfortunately currently we don't have any plans to implement `todo` highlighting, however if VS Code team will implement '[add highlighting of common keywords like TODO](https://github.com/Microsoft/vscode/issues/9899)' feature request then we will be able to enable it in our code viewer too.
