### ISSUE TITLE
WallabyJs, Aurelia and Kendo UI

### ISSUE THREAD

**Issue by Lloyc** [wallabyjs/public#1288]
### Issue description or question
I'm trying to use wallaby with aurelia/typescript and Kendo UI. I can't figure out how to load all the needed modules. I tried the configuration below but it cannot find the module Kendo UI.

### Wallaby.js configuration file
I tried this config. Not all my test are running
![image](https://user-images.githubusercontent.com/11031281/30060532-cc78c3d8-9211-11e7-97eb-b6cae5eab337.png)

```typescript
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "lib": ["es2015", "dom"],
    "allowJs": true
  },
  "exclude": [
    "node_modules",
    "scripts"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./custom_typings/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}

```

### Code editor or IDE name and version
Visual Studio Code v 1.15.1

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Please create a sample repo with your setup, where I could reproduce the config issue. Happy to have a look into.

**Comment by Lloyc** [comment]
@ArtemGovorov There is the sample Github. Thank you for the quick reply. https://github.com/Lloyc/AureliaKendoUISample

**Comment by ArtemGovorov** [comment]
@Lloyc Thanks for the repo! I'm not very familiar with Kendo UI, but when I run wallaby in it, it shows this error:

```
Uncaught Error: Cannot find module "kendo-ui/js/kendo.notification"
```

However, I neither see the `kendo-ui` module installed locally, nor it is present in the `package.json` dependencies. Karma config doesn't seem to start either.

Could you please update the repo to install missing modules and had a working karma configuration?

**Comment by Lloyc** [comment]
@ArtemGovorov Thank you. I updated the repo with working karma configuration. I use Kendo UI Pro for my project. It is installed under @progress folder and Dependencies in the package.json.
![image](https://user-images.githubusercontent.com/11031281/30075863-1f410746-9245-11e7-94e4-4998c9a7f3d2.png)

You'll probably need to be registered to be able to use it. In my output console, I have the same error as the one you mentioned above. That's the reason I open this issue.

**Comment by ArtemGovorov** [comment]
Thanks for updating  the repo. I have sent you the [pull request](https://github.com/Lloyc/AureliaKendoUISample/pull/1) with some change to make it work. Because `kendo-ui` module is not under `node_modules` directly but under the `@progress` folder, webpack needs to know how resolve it [via an alias](https://webpack.js.org/configuration/resolve/#resolve-alias).

**Comment by ArtemGovorov** [comment]
I have also noticed that you have the ~9mb TypeScript file https://github.com/Lloyc/AureliaKendoUISample/blob/master/src/models/dal.ts in your sample project. It slows things down in Aurelia/TypeScript compilation and doesn't seem to be used at all (so you can probably remove it).

**Comment by Lloyc** [comment]
Thank you @ArtemGovorov. It works!!
