### ISSUE TITLE
Safari automatically unzips the file when downloaded which can lead to user installing wrong jar

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#129]
Safari seems to automatically unzip archives when downloaded.

Inside the archive their is a lib folder and inside that there is a `wallaby.jar`. If the user mistakenly installs the `wallaby.jar` file it will install, but break with an uninformative error message because it can't find dependencies.

This is all they will see, and only if they open the Event Log!
```
10:39:31 PM InvocationTargetException: null
```

This will lead OSX Safari users to always receive a bad install. Please fix ASAP so more people can enjoy this awesome product :)

I only managed to install it when I used Chrome instead.

**Comment by ArtemGovorov** [comment]
Thanks for letting me know. I have changed the build process to only produce a single JAR file, so now even a user installs the unzipped JAR - it'll still work.

**Comment by vjpr** [comment]
Better, but not optimal. I suggest placing a `README` or `INSTALL` file in the root directory. Its confusing when the website instructions say install the `zip` when there appears to be no zip.

I had a look and could not figure out a way to force Safari to not extract zips on the client.

**Comment by ArtemGovorov** [comment]
Good idea. I have changed the website to say that unzipped JAR may also be installed and have also added a note in the installation instructions about automatically unzipped JAR file - https://github.com/wallabyjs/public#getting-started. Also, I you have suggested I have added the readme file to the archive root directory, it will be included starting from the next released version.
