### ISSUE TITLE
Jest 21 property _jasmineAdapter undefined

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1290]
### Issue description or question
After upgrading to Jest 21, if there are seven or more test files the following error is thrown: ``TypeError: Cannot read property '_jasmineAdapter' of undefined``.

https://github.com/chrisblossom/wallaby-issue-1290

### Wallaby.js configuration file

```javascript
'use strict';

/* eslint strict:off, global-require:off */

module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js',
            'jest.config.js',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],
        tests: [
            'src/**/*.test.js',
        ],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: w => {
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version
```
WebStorm 2017.2.4 EAP
Build #WS-172.4155.10, built on August 31, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

### OS name and version
``Mac OS X 10.12.6``

**Comment by ArtemGovorov** [comment]
Thanks for the repo! The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.479.
