### ISSUE TITLE
“Unexpected token export” when running tests that use ES6 modules in node_modules directory

### ISSUE THREAD

**Issue by pahund** [wallabyjs/public#1294]
### Issue description or question

In my project, I have npm dependencies to packages from two monorepos `@mt-advertising` and `@mt-ui`. The repositories are available in my company's internal npm registry. They contain ES6 modules. The web app that consumes the modules uses webpack to transpile them to regular JavaScript code.

The application works fine, as does running the Mocha test suites on the command line.

When I try to run the tests with Wallaby.js, I get an error that indicates that the modules are not transpiled through Babel:

```
/Users/pahund/git/polly/node_modules/@mt-advertising/containers/src/index.js:10
export { default as createAdPlacement } from './createAdPlacement';
^^^^^^

SyntaxError: Unexpected token export

	at Object.<anonymous> src/shared/components/App/App.js:5
	at Object.<anonymous> src/shared/components/App/index.js:5
	at Object.<anonymous> test/shared/components/AppTest.js:7
```

I've found this issue, which seems to be related: https://github.com/wallabyjs/public/issues/293

I added my ES6 modules to the files as suggested in the issue, but it doesn't change anything.

Here is the output I get on the Wallaby console when I run in debug mode:

https://gist.github.com/pahund/8b2d9a4e4631635d90238ec3af47d7f4

It does say in this log that Wallaby picks up the files from _@mt-advertising_ and _@mt-ui_, if I interpret it correctly (lines 293 ff.).

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test';

module.exports = wallaby => ({
    files: [
        'src/**/*.js',
        'src/**/*.css',
        'test/**/*.json',
        'node_modules/@mt-ui/**/*.js',
        'node_modules/@mt-ui/**/*.css',
        'node_modules/@mt-advertising/**/*.js'
    ],

    tests: [
        'test/**/*Test.js'
    ],

    env: {
        type: 'node',
        runner: '/usr/local/bin/node',
        params: {
            // this allows us to use absolute paths in import statements instead of ../../../../../bla.js
            env: `NODE_PATH=${wallaby.projectCacheDir};NODE_ENV=test`
        }
    },

    workers: {
        recycle: true
    },

    testFramework: 'mocha',

    compilers: {
        '**/*.js': wallaby.compilers.babel()
    },

    bootstrap: () => {
        const path = require('path');
        require(path.join(wallaby.localProjectDir, 'test/setup'));
    },

    reportUnhandledPromises: false
});
```
### Babel Configuration (.babelrc)

```json
{
  "presets": [
    [ "env", { "modules": false } ],
    "react"
  ],
  "plugins": [
    "transform-object-rest-spread"
  ],
  "env": {
    "development": {
      "plugins": [
        "react-hot-loader/babel",
        "transform-react-jsx-source"
      ]
    },
    "test": {
      "presets": [
        "env",
        "react"
      ]
    }
  }
}
```
### Code editor or IDE name and version

IntelliJ IDEA 2017.2.3 Ultimate
Wallaby core v1.0.481

### OS name and version

MacOS 10.12.6 Sierra

**Comment by ArtemGovorov** [comment]
You may use the solution described here: https://github.com/wallabyjs/public/issues/602#issuecomment-220504165 and let `babel-register` to do the job:

```javascript
...

module.exports = wallaby => ({
    ...
    bootstrap: () => {
        // will match @mt-ui and @mt-advertising, and @mt*
        require('babel-register')({ only: ['/node_modules/@mt'] });
        ...
    },

    ...
});
```

**Comment by pahund** [comment]
👍 **IT WORKS** – perfect, thanks!

**Comment by pahund** [comment]
Although… 🤔 it works, but it slows down the execution speed of Wallaby significantly. When I change code to intentionally break a test, it takes 5-7 seconds until Wallaby reports the test failure. I assume this is because the bootstrap function is invoked every time code changes. Is there a better way? Why doesn't it work to simply add _'node_modules/@mt-ui/**/*.js'_ and _'node_modules/@mt-advertising/**/*.js'_ to _files_?

**Comment by ArtemGovorov** [comment]
I doubt that babel-register slows things down, as babel should cache compiled files, but just in case you may try this:

```javascript
module.exports = wallaby => ({
    ...
    bootstrap: () => {
        if(!global._babelRegistered) {
          require('babel-register')({ only: ['/node_modules/@mt'] });
          global._babelRegistered
        }
        ...
    },

    ...
});
```


This should only register babel once per process.

**Comment by ArtemGovorov** [comment]
You may also turn on the `debug: true`:
```javascript
module.exports = wallaby => ({
    ...
    debug: true
});
```
and see where the time spent in the Wallaby Console.

**Comment by pahund** [comment]
Thanks, I've removed _workers: { recycle: true }_, now the speed is acceptable
