### ISSUE TITLE
Support testing a Cordova/Phonegap project

### ISSUE THREAD

**Issue by elijnzaad** [wallabyjs/public#1295]
### Can't figure out how to use Wallaby to test a Cordova project
I use cordova to create apps for iOS and Android devices. Code is written in Vanilla JS. I know Wallaby will not be able to execute code on a device, so for that purpose I've added the 'browser' platform to the project. By issuing 'cordova run browser' in the terminal, cordova starts a server providing access to the app by 'http://localhost:8000/index.html'.

So far so good. The app runs and the expected output is shown in the Javascript console.
However, I can't seem to get Wallaby running the tests. I suspect this is because Wallaby does not use the cordova-serve (https://www.npmjs.com/package/cordova-serve), but I can't figure out how to configure this.

I've added an archive containing a basic cordova example writing to and reading from the filesystem. You should be able to get it running by extracting the archive, open a terminal, cd into the WallabyTest directory and issue 'cordova run browser'.

When running the tests, you should get a message saying "Error: Unhandled promise rejection: LocalFileSystem is not defined​​". The LocalFileSystem is provided by cordova.

Disclaimer: the only purpose of this project is to illustrate the problem described. It is not intended to be a showpiece of excellent programming. 

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'platforms/browser/www/js/*.js'
    ],

    tests: [
      'tests/spec/*.js'
    ],

    testFramework: 'jasmine',
    env: {
      kind: 'chrome'
    },
    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.16.0

### OS name and version
MacOS 10.12.6

### Example project
[WallabyTest.zip](https://github.com/wallabyjs/public/files/1290871/WallabyTest.zip)

**Comment by ArtemGovorov** [comment]
I have tried your repo, and I'm also getting the `Error: Unhandled promise rejection: LocalFileSystem is not defined​​` error.

As the error message points out, the error is thrown on this line:
```javascript
window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function (fs) {...
```
because the code is trying to access the `LocalFileSystem` global variable that is not defined.

> The LocalFileSystem is provided by cordova.

I haven't used Cordova/PhoneGap at all, but I'm guessing that required cordova files have not been added to the `files` list in your wallaby config, so cordova and the `LocalFileSystem` global variable (and the rest) is not defined/loaded.

If you can create a simple html page that can run your single unit test without wallaby, then I can easily show how to configure wallaby for it.

**Comment by elijnzaad** [comment]
I must admit this is quite a challenge and I now understand it is not a problem related to Wallaby, but more in general to testing Cordova/Phonegap apps.

I haven't yet got the test running, the main challenge seems to be starting the tests after cordova has fired a 'device ready' event.

If you don't mind I'll update this issue as soon as I have a test running, as I suspect there might be more people struggling to test cordova apps.

Thanks again for your swift reply, you certainly got me going in the right direction.

**Comment by elijnzaad** [comment]
In case somebody needs to test a cordova iOS, Android or Windows app:

I am using Jasmine and Wallaby and I would like both SpecRunner.html and Wallaby to be able to test my app. 

You need to add platform 'browser' to your app:

```cordova platform add browser```

This will allow you to run tests on your code, as the javascript test tools are unable to access the physical devices.

Next, add a /merges/browser/tests directory to your project and place your tests and SpecRunner.html in there. By placing your tests in /merges/browser you won't pollute your iOS, Android or Windows project with test code.

### Jasmine SpecRunner.html
(you can skip this if you only use Wallaby)
Modify SpecRunner.html so that it loads cordova, for example:

```
  <script src="lib/jasmine-2.4.1/jasmine.js"></script>
  <script src="lib/jasmine-2.4.1/jasmine-html.js"></script>
  <script src="lib/jasmine-2.4.1/boot.js"></script>

  <!-- include source files here... -->
  <script src="../cordova.js"></script>
  <script src="../plugins/cordova-plugin-file/src/browser/FileProxy.js"></script>
  <script src="../plugins/cordova-plugin-file/www/DirectoryEntry.js"></script>
  <script src="../plugins/cordova-plugin-file/www/DirectoryReader.js"></script>
  <script src="../plugins/cordova-plugin-file/www/Entry.js"></script>
  <script src="../plugins/cordova-plugin-file/www/File.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileEntry.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileError.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileReader.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileSystem.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileUploadOptions.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileUploadResult.js"></script>
  <script src="../plugins/cordova-plugin-file/www/FileWriter.js"></script>
  <script src="../plugins/cordova-plugin-file/www/Flags.js"></script>
  <script src="../plugins/cordova-plugin-file/www/Metadata.js"></script>
  <script src="../plugins/cordova-plugin-file/www/ProgressEvent.js"></script>
  <script src="../plugins/cordova-plugin-file/www/fileSystems.js"></script>
  <script src="../js/index.js"></script>

  <!-- include spec files here... -->
  <script src="spec/index.js"></script>
```

Next build your project:

```cordova prepare browser```
(this will copy your tests to the browser platform only, not to iOS, Android or Windows)
```cordova run browser```

This should start a browser serving your project at http://localhost:8000. To run the Jasmine SpecRunner.html type:

```http://localhost:8000/tests/SpecRunner.html```

### Wallaby
Next configure Wallaby to use cordova, my config is:

```
module.exports = function () {
  return {
    files: [
      { pattern: 'platforms/browser/www/cordova.js', instrument: false, load: true, ignore: false },
      { pattern: 'platforms/browser/www/cordova_plugins.js', instrument: false, load: true, ignore: false },
      { pattern: 'platforms/browser/www/plugins/cordova-plugin-file/src/**/*.js', instrument: false, load: true, ignore: false },
      { pattern: 'platforms/browser/www/plugins/cordova-plugin-file/www/**/*.js', instrument: false, load: true, ignore: false },
      'platforms/browser/www/js/*.js'
    ],

    tests: [
      'platforms/browser/www/tests/spec/*.js'
    ],

    testFramework: 'jasmine',

    env: {
      kind: 'chrome'
    },

    debug: true
  };
};
```

Now both Jasmine SpecRunner and Wallaby should run the tests without complaining. In the examples above I only use cordova-plugin-file, so in a real project you could end up with quite a list of files to include.

If you are building iOS apps like me, remember to 
- Stop Wallaby
- cordova prepare browser
- Start Wallaby
to avoid errors due to caching.

**Comment by ArtemGovorov** [comment]
@elijnzaad Awesome, thank you very much for the update!
