### ISSUE TITLE
Wallaby gets out of sync with code in the editor

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1296]
### Issue description or question
I have the impression that after some time Wallaby does not update the test.

I created this video that shows the error:
https://www.dropbox.com/s/y8lybuw7flfahlf/sublime.mov?dl=0

In the end, when I finish typing ([line 31, functor_exercises.js](https://github.com/bfulop/wallabyquestion/blob/fe1753359ee60920de4d52a7b9a5ea38e3a402d8/exercises/functors/functor_exercises.js#L31)) ` _.map(safeProp('name'))` , the assertion error on the right should be `expected { Object (id, name) } to deeply equal Maybe(A)` . 

It looks like to me Wallaby loses track around `_.map(safeProp)` and does not update after. When I stop and restart it, it shows the correct assertion. 

This has happened to me several times in fact, but always thought that my code was too complex (too many nested callbacks or whatever), but I'm also seeing this on this simple repo (or is it because of ramda?). This has now bugged me for so long to warrant a bug report...

This is on Sublime Text, but also tried it on VSCode. At first, it seemed like VSCode was better so I set out to do the screen recording, but in fact both Sublime and VSCode behave the same way.

If I go over to the specs file and edit (e.g. adding just a blank line) the test is updated and Wallaby displays the correct assertion. 

### Wallaby.js configuration file

I've shared the core here:
https://github.com/bfulop/wallabyquestion

To reproduce, start typing `_.map(safeProp('name'))` on ([line 31 in functor_exercises.js](https://github.com/bfulop/wallabyquestion/blob/fe1753359ee60920de4d52a7b9a5ea38e3a402d8/exercises/functors/functor_exercises.js#L31))
### Code editor or IDE name and version

Visual Studio Code v1.16
Sublime Text v3 build 3142

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks a lot for the repo and the video recording! The issue is fixed and the fix is published  in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version 1.0.486.

**Comment by bfulop** [comment]
Excellent, thanks!
