### ISSUE TITLE
Coverage for jest + modulePaths option does not work

### ISSUE THREAD

**Issue by boccob** [wallabyjs/public#1297]
### Issue description or question
Wallaby does not show coverage properly when jest is used with `modulePaths` option.
I forked wallaby-jest-sample to show an issue: https://github.com/boccob/wallaby-jest-sample
When `require('../src/sum')` is used, coverage calculated correctly. But with `require('sum')` it does not.

### Wallaby.js configuration file

```javascript
module.exports = function () {

  return {
    files: ['src/sum.js'],

    tests: ['__tests__/*.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version
WebStorm 2017.2.4 EAP

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo! 
Wallaby runs tests from its own file cache (with instrumented files) and the `<rootDir>` is pointing back to the local project, so a slight [config adjustment is required](https://wallabyjs.com/docs/integration/jest.html#jest-configuration). Basically you may just point jest fir wallaby to the wallaby project cache: 

```javascript
module.exports = function () {

  return {
    ...

    setup: function (wallaby) {
      const jestConfig = require('./package.json').jest;
      jestConfig.modulePaths = jestConfig.modulePaths.map(p => p.replace('<rootDir>', wallaby.projectCacheDir));
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

I have also sent your [the pull request](https://github.com/boccob/wallaby-jest-sample/pull/1) with the change.

**Comment by ArtemGovorov** [comment]
Have also added [the docs section to describe the scenario](https://wallabyjs.com/docs/integration/jest.html#modulepaths).

**Comment by boccob** [comment]
Thanks a lot!
