### ISSUE TITLE
First test pink in each file

### ISSUE THREAD

**Issue by chrissie1** [wallabyjs/public#130]
concerns the Wallaby visual studio extension

using qunit 1.18.0

As you can see in the image bellow the first test in each file test is pink, but the other tests run just fine. 

![image](https://cloud.githubusercontent.com/assets/364177/7811471/3e9e0380-03ab-11e5-928a-6b9f0f78e3b9.png)

This is what I see in the failing tests screen. 

![image](https://cloud.githubusercontent.com/assets/364177/7811506/ab5a03ac-03ab-11e5-8183-167b93385dce.png)

And this is in the console. 

![image](https://cloud.githubusercontent.com/assets/364177/7811519/bd4ed092-03ab-11e5-9dfa-92da47e104e1.png)

I'll try and upload the zipfile with the solution somewhere, hold on.

**Comment by ArtemGovorov** [comment]
Not sure about the pink test, but from your log it seems like the order of files in your `files` array in the wallaby config is not correct or some files (such as jquery) are missing. Would be great to have the solution to see what's going on.

**Comment by chrissie1** [comment]
I will have to upload it later today since at work everything I can think of to upload it is blocked. Even making a project and adding it to github. 

The second test, which uses the same file runs just fine. 

Here is the conf file

``` json
{
    "files": [
     "Scripts/*.js"
    ],
    "tests": [
      "Tests/*Tests.js"
    ],
    "testFramework": "qunit@1.18.0"
}
```

But it should all be clearer in a few hours when I can upload the solution.

**Comment by ArtemGovorov** [comment]
I can see at least one problem:  `Scripts/*.js` will make wallaby load the scripts from the folder in alphabetical order. It's not working because the scripts depend on each other, so they have to be listed in the order like you are loading them on your test page or your on production pages.
Having `Tests/*Tests.js` is fine, because the order is not important (if your tests do not depend on each other).

**Comment by chrissie1** [comment]
And I guess it works for the second test because all the dependencies are already loaded for that one?

Ok, I will try that on thursday when I'm back at work. 

Anyway here is the test project https://github.com/chrissie1/wallabytest

**Comment by chrissie1** [comment]
You can close this issue and thanks very much for helping.

**Comment by ArtemGovorov** [comment]
Yep, it seems like that's the case.

Thanks for the project! I have managed to make it work with the config like this (that pretty much reflects your test page scripts order):
``` JSON
{
    "files": [
      "Css/*.css",
      { "pattern": "Scripts/jquery-2.1.3.js", "instrument": false },
      { "pattern": "Scripts/jsondiffpatch.min.js", "instrument": false },
      { "pattern": "Scripts/jsondiffpatch-full.min.js", "instrument": false },
      { "pattern": "Scripts/diff_match_patch_uncompressed.js", "instrument": false },
      { "pattern": "Scripts/bootstrap-maxlength.min.js", "instrument": false },
      "Scripts/truncate.js",
      "Scripts/search.js"
    ],
    "tests": [
      "Tests/*Tests.js"
    ],
    "testFramework": "qunit@1.18.0"
}
```

If you'd like to make it less verbose, you may use JavaScript fro the config file (as opposed to JSON) and set `wallaby.defaults.files.instrument = false;` like in [the sample code here](https://github.com/wallabyjs/public#file-object).
