### ISSUE TITLE
Wallaby on VSCode does not run any tests in a TypeScript+Jest project

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/public#1306]
### Issue description or question

After installing the extension and activating it, none of the tests are executed, and wallaby status shows 0 tests failing and 0 tests passing.

I'm using TypeScript and Jest.

The output panel contains this:

```
Error: {​​
​​    "messageText": "Cannot read file 'C:\\Users\\USERNAME\\.vscode\\extensions\\WallabyJs.wallaby-vscode-1.0.59\\projects\\HASH\\instrumented\\tsconfig.json': ENOENT: no such file or directory, open 'C:\\Users\\USERNAME\\.vscode\\extensions\\WallabyJs.wallaby-vscode-1.0.59\\projects\\hash\\instrumented\\tsconfig.json'.",​​
​​    "category": 1,​​
​​    "code": 5012​​
​​}​​
​​    at readCompilerOptions (path\to\node_modules\ts-jest\dist\utils.js:73:15)​​
​​    at Object.getTSConfig (path\to\node_modules\ts-jest\dist\utils.js:113:18)​​
​​    at Object.getCacheKey (path\to\node_modules\ts-jest\dist\preprocessor.js:48:28)​​
​​    at ScriptTransformer._getCacheKey (path\to\node_modules\jest-runtime\build\ScriptTransformer.js:69:26)​​
​​    at ScriptTransformer._getFileCachePath (path\to\node_modules\jest-runtime\build\ScriptTransformer.js:94:27)​​
​​    at ScriptTransformer.transformSource (path\to\node_modules\jest-runtime\build\ScriptTransformer.js:183:32)​​
​​    at ScriptTransformer._transformAndBuildScript (path\to\node_modules\jest-runtime\build\ScriptTransformer.js:276:40)​​
​​    at ScriptTransformer.transform (path\to\node_modules\jest-runtime\build\ScriptTransformer.js:317:21)​​
​​    at Runtime._execModule (path\to\node_modules\jest-runtime\build\index.js:500:53)​​
​​    at Runtime.requireModule (cpath\to\node_modules\jest-runtime\build\index.js:335:14)​​
​​    at new Runtime (path\to\node_modules\jest-runtime\build\index.js:176:14)​​
​​    at runTest (path\to\node_modules\jest-cli\build\runTest.js:79:19)​​
​​    at promise.then (path\to\node_modules\jest-cli\build\TestRunner.js:198:14)​​
```

I have a project with a similar setup which worked just fine, so not sure why wallaby fails on this project.

### Wallaby.js configuration file

```javascript
module.exports = () => ({
  files: [
    "src/**/*.ts",
    "!src/**/*.test.ts",
  ],
  tests: [
    "src/**/*.test.ts",
  ],
  env: {
    type: "node",
  },
  testFramework: "jest",
  debug: true,
});
```

### Code editor or IDE name and version

Visual Studio Code v1.16

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Try adding your `tsconfig.json` file to the `files` list:

```diff
module.exports = () => ({
  files: [
+   "tsconfig.json",
    "src/**/*.ts",
    "!src/**/*.test.ts",
  ],
  tests: [
    "src/**/*.test.ts",
  ],
  env: {
    type: "node",
  },
  testFramework: "jest",
  debug: true,
});
```

If it doesn't help (or you start seeing other issues), please share your jest config.

**Comment by foxbunny** [comment]
After adding that line, and a few more things I forgot to add, I have the following configuration:

```javascript
module.exports = () => ({
  files: [
    "tsconfig.json",
    "src/**/*.ts",
    "src/**/*.tsx",
    "!src/**/*.test.ts",
    "!src/**/*.test.tsx",
  ],
  tests: [
    "src/**/*.test.ts",
    "src/**/*.test.tsx",
  ],
  env: {
    type: "node",
  },
  testFramework: "jest",
  debug: true,
});
```

The jest config looks like this:

```json
  "jest": {
    "transform": {
      "\\.(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "\\.test\\.tsx?$",
    "modulePaths": [
      "<rootDir>/src/",
      "<rootDir>/node_modules/"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "moduleNameMapper": {
      "(\\.scss|\\.webfont\\.json)": "identity-obj-proxy",
      "(\\.handlebars)": "<rootDir>/src/__mocks__/hbs.js",
      "\\.(jpg|png|gif|ttf|woff|eot|svg|html)": "<rootDir>/src/__mocks__/file-mock.js"
    },
    "setupFiles": [
      "./src/__testing__/setup.ts"
    ],
    "mapCoverage": true
  }
```

Now the error in the output panel is this:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​TypeError: Object prototype may only be an Object or null: undefined​​
  at ​src/auth/ForgottenPassword.tsx:32​
  at Object.<anonymous> ​src/auth/ForgottenPassword.tsx:95​
  at Object.<anonymous> ​src/auth/ForgottenPassword.test.ts:6​
​​TypeError: Object prototype may only be an Object or null: undefined​​
  at ​src/auth/Login.tsx:38​
  at Object.<anonymous> ​src/auth/Login.tsx:128​
  at Object.<anonymous> ​src/auth/Login.test.ts:6​
```

The .tsx file in question is a Vue.js component, which uses [decorators](https://github.com/vuejs/vue-class-component#example). The tsconfig includes the `experimentalDecoratros` flag, and otherwise looks like this:

```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "isolatedModules": false,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "removeComments": true,
    "suppressImplicitAnyIndexErrors": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src",
    "jsx": "react",
    "jsxFactory": "h"
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by foxbunny** [comment]
A small update:

I remembered that some of the non-ts files are being used as modules, so I modified the wallaby configuration like so:

```patch
```patch
module.exports = () => ({
  files: [
    "tsconfig.json",
    "src/**/*.*",
-   "src/**/*.ts",
-   "src/**/*.tsx",
-   "!src/**/*.test.ts",
-   "!src/**/*.test.tsx",
  ],
  tests: [
    "src/**/*.test.ts",
    "src/**/*.test.tsx",
  ],
  env: {
    type: "node",
  },
  testFramework: "jest",
  debug: true,
});
```

After this change, there are no errors in the `Wallaby.js Tests` panel, but I still can't get any tests to run.

**Comment by ArtemGovorov** [comment]
Try pointing wallaby to its cache (modulePaths), instead of your local project folder, in your [wallaby config `setup` function](https://wallabyjs.com/docs/integration/jest.html#jest-configuration):

```javascript
module.exports = () => ({
  ...
  setup: function (wallaby) {
    var jestConfig = require('./package.json').jest;
    jestConfig.modulePaths[0] = jestConfig.modulePaths[0].replace('<rootDir>', wallaby.projectCacheDir);
    wallaby.testFramework.configure(jestConfig);
  }
});
```

If it doesn't help, please create a sample GitHub repo reproducing the issue, I'm happy to have a look.

**Comment by foxbunny** [comment]
I've tried to re(pro)duce the original setup as best I could, but it doesn't seem to be perfect. I've noted the differences in the README.

https://github.com/foxbunny/wallaby-case

**Comment by ArtemGovorov** [comment]
I have sent you 2 pull requests with 2 different solutions:
- https://github.com/foxbunny/wallaby-case/pull/1
- https://github.com/foxbunny/wallaby-case/pull/2

Strictly saying, the import `import Vue from "vue";` is not valid, because `vue` doesn't export default `Vue` symbol. As I [describe here (see for more details)](https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360) `ts-jest` applies Babel compilation on top of TypeScript compilation, so this is why it works. If you are happy with it, you may apply PR 1 to do the same. Note that for production build you'll need to do the same if you want it to work - not only compile with TypeScript, but also add Babel compilation on top.

If you'd like to be explicit and follow ES6 module standard, then you may fix your code like I have done in PR 2. This way you will jot need babel compilation on top of your TS compilation neither for testing, nor for production build. 

Hope it makes sense.

**Comment by fvanwijk** [comment]
`import Vue from "vue"` is totally valid when you are using the [esm or commonjs](https://vuejs.org/v2/guide/installation.html#Explanation-of-Different-Builds) build.

`Vue` is the default export.

**Comment by ArtemGovorov** [comment]
@fvanwijk `import Vue from "vue"` is only valid if there's a valid default export.

TypeScript import `import Vue from "vue"` (that is used for [the project in this issue](https://github.com/foxbunny/wallaby-case/blob/master/tsconfig.json#L8)) compiled to CommonJs looks something like:

```
var vue = require('vue').default;
```

Vue CommonJs build (`node_modules/vue/dist/vue.runtime.common.js`), used by current node.js version when you do `require('vue')`, doesn't have the default export (ie. `exports.default`). Babel [adds the `default` property](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBANQK4FM4DMoRHARAN1VzgCgBjCAOwGcIAbFAOjogHMAKZFASiA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=env&prettier=false&targets=Node-8&version=6.26.0), but CommonJs build doesn't export it, so technically the `import Vue from "vue"` import is not valid in this specific context.

**Comment by fvanwijk** [comment]
Ah thanks, yes I'm living in the Babel world for too long.

The CommonJS has `module.exports = Vue$3;` which isn't the default export. 👍

**Comment by ArtemGovorov** [comment]
@fvanwijk Yep, however you are also correct about ESM, which has the correct default export `export default Vue$3;`. 

So if this import `import Vue from "vue"` is handled from the context of webpack then the import is valid. Because the current version of webpack will use the `node_modules/vue/dist/vue.runtime.esm.js` ESM build of vue (because of the `module: ...` field the `vue` module `package.json` file). So whether the import is valid or not, really depends on the context (and whether ESM build is used or not).

**Comment by foxbunny** [comment]
@ArtemGovorov Thanks for the PRs.

> Vue CommonJs build (node_modules/vue/dist/vue.runtime.common.js), used by current node.js version when you do require('vue'), doesn't have the default export (ie. exports.default). Babel adds the default property, but CommonJs build doesn't export it, so technically the import Vue from "vue" import is not valid in this specific context.

In the production code, if I change the import to `import * as Vue from "vue";` most of the code actually breaks at runtime with lots of weird errors about missing properties on the component classes related to hooks and stuff.

If I use the solution from the first PR, I get from wallaby that 54 tests are failing, while Jest reports only 1.

I'll see what I can do to make the test- and runtime compilation more consistent, and report back.

**Comment by ArtemGovorov** [comment]
> In the production code, if I change the import to `import * as Vue from "vue";` most of the code actually breaks at runtime with lots of weird errors about missing properties on the component classes related to hooks and stuff.

Perhaps it's because you're using webpack (as I mentioned above it'll use ESM build), and looks like `vue` CommonJs build and `vue` ESM build are not really equivalent. In this case it makes sense to stay with the `import Vue from "vue"` import, and just configure wallaby to run babel on top of the TS built code (just like `ts-jest` is doing).

> If I use the solution from the first PR, I get from wallaby that 54 tests are failing, while Jest reports only 1.

Please update your repo with some example(s), Wallaby can definitely be configured to work like Jest, happy to have a look and help.

**Comment by foxbunny** [comment]
> Please update your repo with some example(s), Wallaby can definitely be configured to work like Jest, happy to have a look and help.

I'll poke at it a bit more and update the repo.

**Comment by foxbunny** [comment]
Incidentally, using the `allowSyntheticDefaultImports` flag seems to be the reason why `import Vue from "vue";` works.

**Comment by ArtemGovorov** [comment]
> Incidentally, using the allowSyntheticDefaultImports flag seems to be the reason why import Vue from "vue"; works.

The flag doesn't affect TypeScript compilation at all. It's just `ts-jest` is [checking for the flag](https://github.com/kulshekhar/ts-jest/blob/master/src/utils.ts#L205) and if it is set, `ts-jest` sets TS module to ES2015, so that TypeScript leaves `import Vue from "vue";` untouched and Babel applied by Jest later can generate the access to the default property even if it doesn't exists. See the [detailed explanation here](https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360).

**Comment by foxbunny** [comment]
Ah, thanks for the clarification.

**Comment by ArtemGovorov** [comment]
One more config setting (that'll make wallaby behave closer to how plain Jest builds it) that I may suggest (without see the actual issues) is this - try adding `babel-preset-jest` as well. I understand that it may not solve the configuration issues (that I'm happy to look into once shared), but still may be worth trying.

```diff
module.exports = (wallaby) => ({
  ...
  preprocessors: {
    '**/*.js?(x)': file => require('babel-core').transform(
      file.content,
      {
        sourceMap: true,
        plugins: ['transform-es2015-modules-commonjs'],
+       presets: 'babel-preset-jest'
      })
  },
  ...
});

```

**Comment by foxbunny** [comment]
I think I might be onto something. I've updated the repo to include a test that uses a mock module that is automatically mocked by Jest. It's one of the things I'm doing in the production code, and it appears most of the failed tests are related to these automocked modules.

**Comment by ArtemGovorov** [comment]
Thanks for updating the repo!
The issue is reproduced, fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version 1.0.491.

**Comment by foxbunny** [comment]
I confirm that it now works as expected. Hooray!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
