### ISSUE TITLE
Word document files copied incorrectly

### ISSUE THREAD

**Issue by Dviejopomata** [wallabyjs/public#1308]
### Issue description or question

Same problem as: #521 and #614  , but different extensions: .docx

If the extension is .docx it gets corrupted, though if i change the extension to .zip (since a word document is a zip) it works fine.

The docx has 20kb in origin and in the instrumented and original folder has 34kb.
The zip remains unchanged.

I have attached both files, the docx and the corrupted file i get.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'src/utils/*.ts', instrument: false },

            { pattern: 'samples/invoice.docx', instrument: false, load: false },
            { pattern: 'samples/invoice.zip', instrument: false, load: false },
            'src/**/*.ts',
            'config/*.json',
            'src/templates/**/*.hbs',
            'src/templates/**/*.scss',
            '!src/**/*.test.ts',
            '!src/frontend/**/*.ts'
        ],

        tests: [
            'src/**/*.test.ts',
            '!src/frontend/**/*.test.ts'
        ],

        testFramework: 'tape',

        env: {
            type: 'node',
            runner: 'node'
        },
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
                "module": "commonjs",
                "sourceMap": true,
                "target": "es6"
            })
        },
        workers: { recycle: true }
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.16.1

### OS name and version

Windows

[invoice.docx](https://github.com/wallabyjs/public/files/1309325/invoice.docx)
[invoice_corrupted.docx](https://github.com/wallabyjs/public/files/1309326/invoice_corrupted.docx)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
