### ISSUE TITLE
Node tests fail in Wallaby and pass in Mocha (Workers set to 1)

### ISSUE THREAD

**Issue by whydoidoit** [wallabyjs/public#1309]
### Issue description or question

Wallaby tests fail and Mocha pass.  Appears to be due to some kind of concurrency or beforeEach hook not working.  My memory mock DB isn't clear so tests fail.

Also code coverage shows that files in my src/node_modules folder are not executed (grey marker), even though they are (console.log shows in Wallaby output but not in the IDE).

https://github.com/whydoidoit/3r

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    process.env.NODE_PATH +=
        require('path').join(wallaby.localProjectDir, 'src', 'node_modules');
    return {
        files: [
            'src/**/*.js',
            {pattern: 'src/node_modules/**/*.js', ignore: false, load: true, instrument: true},
            {"pattern": "src/test/**/*.js", ignore: true}
        ],
        tests: [
            'src/test/**/*.js'
        ],
        env: {
            type: 'node'
        },
        workers: {
            initial: 1,
            regular: 1,
            recycle: true
        },
        testFramework: 'mocha'
    }
}

```

### Code editor or IDE name and version

IntelliJ IDEA v2017.2
### OS name and version

OSX

**Comment by whydoidoit** [comment]
Note that it does "sometimes" work.  Normally I get this error caused by another test having written to the database:
```
	expected 1505695865204 to equal 100
		at Context.it src/test/unlockables/create-unlockables.js:113

	From console:
		mike:1234:0 { last: 1505695865204,
		  codes: [ { d: 1505695865204, u: 0 }, { d: 100, u: 0 } ],
		  id: 0,
		  r: 1 } 
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The problem with both showing code coverage and with the failing test had the same reason. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

Please also change your wallaby config after the update as follows:
```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.js',
            {"pattern": "src/test/**/*.js", ignore: true}
        ],
        tests: [
            'src/test/**/*.js'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'mocha'
    }
}
```
(the important bit is to remove pointing the `NODE_PATH` to your local folder)

**Comment by whydoidoit** [comment]
Thanks Artem - that got it working for a while.  Will report another one that's happening as I write more tests!
