### ISSUE TITLE
Node.js and browser environment

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#131]
How can I run some tests in a Node environment and others in the browser environment?

**Comment by ArtemGovorov** [comment]
You'll need to create two config files, with corresponding lists of files/tests and [`env` setting](https://github.com/wallabyjs/public#environment-setting) for node (browser environment is the default value of the setting). Then you'll need to create a Run Configuration for each in your IDE and run it whenever you're writing tests/code for browser or node. 

Please note that currently running [more than one configuration at the same time is not supported](https://github.com/wallabyjs/public/issues/89).

**Comment by vjpr** [comment]
Thanks!
