### ISSUE TITLE
env.params.env parser doesn't strip spaces (or take env as an object)

### ISSUE THREAD

**Issue by just-another-jxliu** [wallabyjs/public#1312]
### Issue description or question

With the configuration snippet below, `process.env` looks like this when running a test in Wallaby:
```
  ...
  TZ: 'UTC',​​​​​
  ' HELLO': 'world' }​​​​​
```

Note the space before the key HELLO. I'd expect the space to not be preserved to mimic the behavior of setting those env vars inline on the command-line.

### Wallaby.js configuration file

```javascript
    env: {
      type: 'node',
      params: {
        env: 'TZ=UTC; HELLO=world'
      }
    },
```

### Code editor or IDE name and version

Visual Studio Code v1.15.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in the latest extension v1.0.60.
