### ISSUE TITLE
Select Configuration File is slow (possibly traversing node_modules?)

### ISSUE THREAD

**Issue by just-another-jxliu** [wallabyjs/public#1313]
### Issue description or question

We're running Wallaby in a large node monorepo with multiple Wallaby config files and a lot of installed npm packages.

It takes "Select Configuration File" 10-15 seconds to display our list of Wallaby config files. It feels like Wallaby is traversing all of the node_modules directories. Can this be turned off to speed up the command?

### Code editor or IDE name and version

Visual Studio Code v1.16.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in the latest extension v1.0.60.
