### ISSUE TITLE
Respect use Jest options automatically

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#1316]
### Issue description or question

Every time I'm trying to run wallaby on the OSS project I run into issues related to not synced configurations between Jest and wallaby. This is very frustrating and costs a lot of time to update.

It would be a much better DX if wallaby could use Jest's options when `testFramework: 'jest',` without the need to duplicate everything in 2 different formats.

Options like:

```
compilers: {
  'src/*.js': wallaby.compilers.babel()
},
```

and 

```
env: {
  type: 'node',   
  runner: 'node'
},
```

and 

```
setup: () => {
  wallaby.testFramework.configure(require('./package.json').jest) 
}
```

as well as `files` and `tests` arrays could be rather easily read out of Jest's config and applied under the hood by wallaby.

Ideally, I don't want to setup my test environment at all and Jest provides that. It would be an even better DX improvement if wallaby could recognize that I'm using Jest and don't require the `wallaby.config.js` at all.

IMO it's rather easy to read this configuration from it and this is what I would expect for the paid product.

### Wallaby.js configuration file

https://github.com/react-dropzone/react-dropzone/blob/master/wallaby.config.js

### Code editor or IDE name and version

IntelliJ IDEA v2017.2 but it doesn't matter, actually.

### OS name and version

OSX but it doesn't matter

**Comment by okonet** [comment]
See related PR: https://github.com/react-dropzone/react-dropzone/pull/505

**Comment by ArtemGovorov** [comment]
This 

```javascript
setup: () => {
  wallaby.testFramework.configure(require('./package.json').jest) 
}
```

is not required and is done automatically for quite some time. 

Agree about the rest, we will either make the core to auto-configure stuff for Jest or publish an OSS package to do it.

**Comment by smcenlly** [comment]
@okonet - today we released our experimental automatic configuration for jest v24+ that we hope will help you out in the future. [Check it out](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) and let us know how it goes with your projects (you don't even need to have a wallaby configuration file).
