### ISSUE TITLE
Perpetual use on VS code and Webstorm

### ISSUE THREAD

**Issue by glendaviesnz** [wallabyjs/public#1317]
### Issue description or question
VS Code and Webstorm automatically upgrade to latest version, so can't continue to use the last supported version after current license expires.

We would like to continue to use the last supported version in both VS Code and Webstorm while we negotiate to have the licenses renewed. The fact that it is advertised as a perpetual license seems to indicate that this is possible - can you please let us know how to downgrade to and stay on last supported version in both these IDEs?

Thanks
Glen

**Comment by ArtemGovorov** [comment]
> VS Code and Webstorm automatically upgrade to latest version

This is not how it works (supposed to work). There's no need to downgrade - wallaby normally automatically downloads only the latest supported version based on your entered license key, unless you do a fresh install of a not supported wallaby.js version and only then enter your expired license key.

If that's the case, then enter your license key (if not already), then:
- for WebStorm, please use our [latest covered version form](https://wallabyjs.com/license) to download and install the version covered by your license.
- for VS Code, [force wallaby core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If it doesn't help, please send us an email to hello@wallabyjs.com with your license key and some screenshots/error messages describing the problem.
