### ISSUE TITLE
Wallaby does not auto-refresh test result after TypeScript code change

### ISSUE THREAD

**Issue by mobiledeve** [wallabyjs/public#1323]
### Issue description or question
Wallaby does not auto-refresh test result after TypeScript code change.

In the sample project, the 1st.spec.ts can auto-refresh result. If I change 
```javascript
        expect(true).toBe(true);

```
to 
```javascript
        expect(true).toBe(false);

```
I can see the green dot change to red dot immediately.

But in test.spec.ts, if I add a white space to the file and save, all the dots will change to gray, I have to restart wallaby.js to see the dots change to red.

I created  https://github.com/mobiledeve/WallabyRefreshError, can you please have a look to see why this is happenning?

Thank you very much!

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version
Windows 8.1

**Comment by ArtemGovorov** [comment]
Wallaby requires [all files specified in the `tests` lists to be test files (files with tests in them)](https://wallabyjs.com/docs/config/files.html#tests). In your case however, there's the `src/TestHelper.spec.ts` file that follows your tests naming convention, however is not a file with test.

You may either rename the file, or exclude it from your test patterns, like I did in [this pull request](https://github.com/mobiledeve/WallabyRefreshError/pull/1).

**Comment by mobiledeve** [comment]
Thank you very much! It worked!

Just a little suggestion, can we have some kind of user message or dialog to notify user what happened, it will save you more time in the future if someone else get the same issue?

Have a great day!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> can we have some kind of user message or dialog to notify user what happened

Wallaby notifies about errors like this one via the Wallaby Console output channel:

![console](https://user-images.githubusercontent.com/979966/30805754-2bb60b38-a236-11e7-937d-b8810b9fd90e.png)
