### ISSUE TITLE
Use Atom's updater rather than updating independently

### ISSUE THREAD

**Issue by wldcordeiro** [wallabyjs/public#1324]
### Issue description or question

Wallaby shouldn't just be shutting down sockets by itself and getting into a broken state. The updates should be handled via the package updater in Atom.

### Code editor or IDE name and version

Atom v1.21

**Comment by ArtemGovorov** [comment]
> Wallaby shouldn't just be shutting down sockets by itself and getting into a broken state.

Could you please provide some more details about what exactly is broken, like error messages or screenshots? What do you mean by "shutting down sockets"?

**Comment by wldcordeiro** [comment]
<img width="1920" alt="screen shot 2017-09-27 at 8 30 22 pm" src="https://user-images.githubusercontent.com/580982/30992655-2accad60-a468-11e7-9cf6-68c2036a00a5.png">

I never did anything to close this socket but Wallaby just lost connection here and after I use the stop command Wallaby shows a dialog for its updates.

**Comment by ArtemGovorov** [comment]
Sorry, I'm a bit lost - could you please describe the steps how to reproduce the issue? When exactly does the socket error come up? 

Here is how it is supposed to work: when there's a new version available, wallaby downloads it behind the scenes and waits for you to stop your current running wallaby instance. When you stop it, wallaby attempts to renew the installed version with the downloaded one. Clearly in your environment something in these steps fail, so I'm trying to understand where and how to reproduce it.

**Comment by wldcordeiro** [comment]
Wallaby goes through the Atom package management system like any other package and lets me decide when to update. Having this weird backdoor update system that manages itself is cumbersome when I update all my other plugins together.

**Comment by ArtemGovorov** [comment]
Wallaby Atom integration consist of the Atom package and a separately versioned component called core. Wallaby Atom package updates go through the Atom package management system like any other package. The core is updated separately by the package itself when required. There are many other tools and plugins that are doing it for various reasons, to name a couple:
- Atom only allows publishing package from public Github repos, however many tools, for example wallaby are not open sourced.
- Wallaby checks your license and the core only updates to the latest version is covered by your license. It is not possible to accomplish via Atom package management system.

Could you please describe the steps how to reproduce the issue?
