### ISSUE TITLE
404 link (just a minor hiccup, but it should be an easy to fix nuisance)

### ISSUE THREAD

**Issue by metasean** [wallabyjs/public#1326]
I just saw a [mention](https://github.com/wallabyjs/public/issues/1286) of a Wallaby _APP_ and got all excited [0], so I started hunting down more info, and saw a link to this mythical app of awesomeness on [https://wallabyjs.com/docs/index.html](https://wallabyjs.com/docs/index.html), but when I followed the "`wallaby web app`" link it took me to [land of 404s](https://wallabyjs.com/docs/(/docs/intro/get-started-wallaby-app.html)) instead of [the pot of gold at the end of the rainbow](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html).

[0]: I actually remember seeing it when I first looked at Wallaby, but since I had "to have wallaby.js configured and running" in my editor, I ended up mesmerized in IDE land.  This was a nice reminder find 🙃

**Comment by ArtemGovorov** [comment]
Thanks for the report, the link is fixed.
