### ISSUE TITLE
Test first reported failing then passing on second run

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1327]
### Issue description or question
Best is to watch this screen recording:
https://www.dropbox.com/s/fxcm2j5xancmbwa/wallaby-bug.mp4?dl=0

I launch Wallaby, it reports an assertion as failing, then I just add a space in the code then the test passes. I had this for a long time (several months), so I thought why not report it... :)
I don't know if it's my test set up or some async issue. I tried adding the `done` callback but did not make a difference.
With `$ npm test` the test are passing.

Note, that I'm using the [testdouble](https://github.com/testdouble/testdouble.js) library to dynamically replace the imported modules. No idea if it has any importance.

### Wallaby.js configuration file

A good example of this behaviour is here:
https://github.com/bfulop/quivertolevel

Open the `processFolders.test.js` or `processNote.test.js` and launch Wallaby. 

### Code editor or IDE name and version

I have this with both my editors:

Visual Studio Code v1.6
Sublime Text v3 build 3144

### OS name and version

OSX 10.12 and 10.13

**Comment by ArtemGovorov** [comment]
Thanks for the repo, however I can't reproduce it on OSX nether in Sublime Text nor in VS Code. When I start wallaby on the project, all tests are passing on my machine (I have also tried another machine - same result).

Could you please change the test as follows:
```javascript
  describe('processing folders', function () {
    it('returns a Task containing a List', function () {
      try {
        subject.processFolders.fork(console.err, r => {
          expect(r.fold([])[0]).to.eql(_processedNoteBook)
        })
      }
      catch(e){
        console.log(e.stack);
        throw e;
      }
    })
  })
```
then restart Wallaby in VS Code/Sublime and paste the output from the Wallaby Tests output channel/console to see the full error stack (not from the Wallaby Console)?

Also, what is your node.js version? I'll try the same as your to check if it it matters.

**Comment by bfulop** [comment]
Thanks for the help !
My node version is : `v8.6.0` 
And here's the log from the console:

```
​​Path must be a string. Received undefined​​
      at Task [as fork] ​src/utils/fileUtils.js:18​
      at Context.<anonymous> ​src/processFolders.test.js:33:8​
    ​​​​​​​​​​
    ​​​​​From console:​​​​​
      ​​​​​​​​​​
      ​​​​​TypeError: Path must be a string. Received undefined​​​​​
      ​​​​​    at assertPath (path.js:28:11)​​​​​
      ​​​​​    at Object.resolve (path.js:1188:7)​​​​​
      ​​​​​    at Task [as fork] (/Users/bfulop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.62/projects/0b037ba80e9ed581/instrumented/src/utils/fileUtils.js:18:12)​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:117:19​​​​​
      ​​​​​    at Task.fork (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:58:12)​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:117:19​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:96:14​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:58:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:93:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:114:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:114:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:93:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:93:12​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:93:12​​​​​
      ​​​​​    at Task.fork (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/data.task/lib/task.js:114:12)​​​​​
      ​​​​​    at Context.<anonymous> (/Users/bfulop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.62/projects/0b037ba80e9ed581/instrumented/src/processFolders.test.js:31:54)​​​​​
      ​​​​​    at callFn (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runnable.js:348:21)​​​​​
      ​​​​​    at Test.Runnable.run (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runnable.js:340:7)​​​​​
      ​​​​​    at Runner.i.runTest (/Users/bfulop/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.62/wallaby/runners/node/mocha@2.1.0/initializer.js:14:567)​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runner.js:549:12​​​​​
      ​​​​​    at next (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runner.js:361:14)​​​​​
      ​​​​​    at /Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runner.js:371:7​​​​​
      ​​​​​    at next (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runner.js:295:14)​​​​​
      ​​​​​    at Immediate.<anonymous> (/Users/bfulop/Work/Abundancia/quivertolevel/node_modules/mocha/lib/runner.js:339:5)​​​​​
      ​​​​​    at runCallback (timers.js:781:20)​​​​​
      ​​​​​    at tryOnImmediate (timers.js:743:5)​​​​​
      ​​​​​    at processImmediate [as _immediateCallback] (timers.js:714:5)​​​​​
      at e.stack ​src/processFolders.test.js:38:8​
```

**Comment by bfulop** [comment]
I just tested it on another Mac and it behaves the same way (as described in the bug report).

This one is running node `v8.1.3`.

Both of the machines are "low-end" Macs (Core Duo and Macbook 2015), I don't know if it has anything to do with it.

Unfortunately there's no one else in the office at the moment whose computer I could use for testing.

**Comment by ArtemGovorov** [comment]
> Both of the machines are "low-end" Macs (Core Duo and Macbook 2015), I don't know if it has anything to do with it.

This note was actually very helpful - the issue is only reproduced if the number of parallel workers is less than the certain number. In this case wallaby starts executing 2 or more specs in one batch and that was the key to reproduce the issue. On my machines each spec was running in its own process (because the machines have enough CPUs).

Anyway, after some investigation, I have found out that the issue is related to how one of the modules used by the ` testdouble` library is working in wallaby environment. Everything required to do to make it work is to do a one-liner configuration in your `setup` function:
```diff
    setup: function (wallaby) {
      global.insp = f => (f && f.inspect ? f.inspect() : f)
      global.td = require('testdouble')
      global.expect = require('chai').expect
+     require('quibble').ignoreCallsFromThisFile(require.main.filename);
    }
```
I have sent you [the pull request](https://github.com/bfulop/quivertolevel/pull/1).

**Comment by bfulop** [comment]
Perfect, thanks! 👍 

Yes, it's the `quibble` library that's doing the module replacement. 

I use `testdouble` for all my tests, I wouldn't be able to do BDD without it. There are some other libraries that do it e.g. sandboxed-module but testdouble is the most focused one.
