### ISSUE TITLE
Node update doesn't allow working offline in JetBrains IDEs

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#1328]
### Issue description or question

During my flight I was planning to work on my project. When I started wallaby runner I encountered that it needs to download latest node version and I can't skip this step even using my system node. 

Also, when I finally got internet and agreed to download node, I could not hide the modal dialog with the progress bar even though it was completely irrelevant to my work. Very annoying user experience.

<img width="470" alt="2017-10-01 at 16 07" src="https://user-images.githubusercontent.com/11071/31055453-534fe3bc-a6c3-11e7-8e56-3784ef1941e4.png">

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

IntelliJ IDEA v2017.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wow, even though the node update only happens once in a while (and that unfortunately happened during you flight), what you've described is definitely an annoying user experience. Sorry about it, we will be looking into the ways to make it better.

**Comment by smcenlly** [comment]
Our plugins now no longer download `node.js` for their runtime. Instead, your system needs to have `node.js` installed (and set in PATH so you may run node from terminal/command line) to run wallaby.js for IntelliJ.
