### ISSUE TITLE
JsDom not getting setup right or something

### ISSUE THREAD

**Issue by TroySchmidt** [wallabyjs/public#1329]
### Issue description or question
Cannot seem to get WallabyJS configured with TypeScript properly.  I ejected my project and that helped.  At one point this was running, so I don't know if a WallabyJS core update has broken it or not.

TypeError: Cannot set property '_eventListeners' of undefined​​
​​    at Window.close (c:\Source\MSRAM-Web\Msram.Web\node_modules\jsdom\lib\jsdom\browser\Window.js:363:51)​​
​​    at JSDOMEnvironment.dispose (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-runner\node_modules\jest-environment-jsdom\build\index.js:44:19)​​
​​    at Promise.resolve.then (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-runner\build\run_test.js:116:17)​​
​​    at <anonymous>​​
​​TypeError: Cannot set property '_eventListeners' of undefined​​
​​    at Window.close (c:\Source\MSRAM-Web\Msram.Web\node_modules\jsdom\lib\jsdom\browser\Window.js:363:51)​​
​​    at JSDOMEnvironment.dispose (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-runner\node_modules\jest-environment-jsdom\build\index.js:44:19)​​
​​    at Promise.resolve.then (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-runner\build\run_test.js:116:17)​​
​​    at <anonymous>​​
​​    at process._tickCallback (internal/process/next_tick.js:188:7)​​

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    
      // Babel, jest-cli and some other modules are located under
      // react-scripts/node_modules, so need to let node.js know about it
      var path = require('path');
      process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(__dirname, 'node_modules/react-scripts-ts/node_modules');
      require('module').Module._initPaths();
    
      // Babel needs this
      process.env.NODE_ENV = 'test';
    
      return {
        files: [
          'src/**/*.js*',
          'src/**/*.ts*',
          'package.json',
          'tsconfig.json',
          'tsconfig.test.json',
          '!src/**/*.test.js*',
          '!src/**/*.test.ts*',
          '!src/registerServiceWorker.ts',
          '!src/react-split-pane/**/*.*'
        ],
    
        tests: ['src/**/*.test.js*','src/**/*.test.ts*'],
    
        env: {
          type: 'node',
          runner: 'node'
        },
    
        compilers: {
          '**/*.ts?(x)': wallaby.compilers.typeScript({ 
            module: "commonjs",
            jsx: "react",
            lib: ["es6", "dom"]
          })
        },
    
        setup: (wallaby) => {
          wallaby.testFramework.configure({
            // as in node_modules/react-scripts/utils/createJestConfig.js
            setupFiles: [
              require.resolve('raf/polyfill'),
              require.resolve('../config/setupAdapter.js')
            ],
            moduleNameMapper: {
              '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve('../config/jest/fileTransform.js'),
              '^.+\\.css$': require.resolve('../config/jest/cssTransform.js')
            }
          });
        },
    
        testFramework: 'jest',

        workers: {
          initial: 3,
          regular: 3
        },
    
        filesWithNoCoverageCalculated: ['src/modules/**/layout.js*', 'src/index.js', 'src/**/__mocks__/*'],
    
        hints: {
            ignoreCoverage: /ignore coverage/
        }
      };
    };
```

### Code editor or IDE name and version

vsCode 1.16.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
I have tried creating a new react app with `create-react-app my-app --scripts-version=react-scripts-ts` and it's working with your config (after slight modifications of paths in the `setup` function). It is also working for me with a simplified config like this:

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.+(ts*|js*|css|svg)',
      '!src/**/*.test.js*',
      '!src/**/*.test.ts*'
    ],

    tests: ['src/**/*.test.js*','src/**/*.test.ts*'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(require('./tsconfig.test.json').compilerOptions)
    },

    setup: (wallaby) => {
      const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts-ts/' + p));
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

It looks like there's an issue with an old/incompatible version of jsdom, try cleaning your node modules and re-installing them. 

If it doesn't help, please share a sample project where the issue can be reproduced. It should be easy to extract one from your project by just copying git and removing everything but `package.json`, `yarn.lock`, required jest configuration files and one test file with a dummy test.

**Comment by TroySchmidt** [comment]
Okay now I have ejected mine after I create it using the create-react-app.  But I think I get the gist of what this config is looking like.  I just don't have createJestConfig after the ejection so trying to map that over to what I need there.

**Comment by TroySchmidt** [comment]
https://github.com/TroySchmidt/TypescriptWallabyConfig

There is a repository that still has the problem.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. 

It looks like you are using `node` test environment (as opposed to `jsdom`) in Jest and then just manually loading jsdom in your tests. In this case you don't need to alter the `testEnvironment` in your wallaby config, because it will switch it to `jsdom` and this is what causing the issue. In fact, if you removed from the `testEnvironment` from your `package.json`, then Jest CLI will start showing the same error.

Have sent you the [pull request with the change](https://github.com/TroySchmidt/TypescriptWallabyConfig/pull/1).

Also, if you see the `Cannot read property '_jasmineAdapter' of undefined` error message after the change, please [force wallaby core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), as we have recently released some changed related to the Jest integration for `"testEnvironment": "node"`.

**Comment by TroySchmidt** [comment]
Thanks so much.  I think I saw that ```_jasmineAdapter``` error message when I was playing around with the configs to get it to work and didn't think I was on the right track.  But the forced update worked.  There is still a window is not defined for the leaflet package, but I don't think that is related to Wallaby config at this point.  Thanks again!
