### ISSUE TITLE
Wallaby not correctly using file patterns when symlinks are introduced

### ISSUE THREAD

**Issue by cwohlman** [wallabyjs/public#1331]
### Issue description or question

My wallaby tests recently quit working, and as far as I can tell the issue is incorrect use of path patterns. The error I get indicates that certain files were not included:

```
Runtime error: Error: Cannot find module './vendor/parse-xml/src'​​
```

However, those files clearly should be included (see the config below). 

The error only occurs with files included twice because of a symlink but where the symlink is in a directory who's contents are ignored, and when those files are at least 2 levels deep. (As far as I can tell.)

Note: a workaround is to not ignore the symlink's contents.

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  const path = require('path');
  return {
    debug: true,
    testFramework: 'mocha',
    files: [
      {pattern: 'modules/**/node_modules/**', ignore: true},
      {pattern: 'modules/**/imports/**', ignore: true},
      {pattern: 'modules/**/*-spec.js', ignore: true},
      'modules/**/*.js'
    ],
    tests: [
      {pattern: 'modules/**/node_modules/**', ignore: true},
      {pattern: 'modules/**/imports/**', ignore: true},
      'modules/**/*-spec.js',
    ],
    env: {type: 'node'},
    compilers: {'**/*.js': wallaby.compilers.babel()},
    setup: (wallaby) => {
      require("babel-polyfill");
    },
  }
};
```

### Reproduction

https://github.com/cwohlman/wallaby-symlink-bug-reproduction

### Code editor or IDE name and version
I've run into this problem on vscode and can also reproduce it in atom:

Atom v1.21.0
Visual Studio Code v1.6.1
Wallaby.js Core v1.0.498

### OS name and version

OSX 10.12.5

**Comment by ArtemGovorov** [comment]
Thanks for putting together the repo! The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version 1.0.499.
