### ISSUE TITLE
TypeError: Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by rogergl** [wallabyjs/public#1332]
### Issue description or question

TypeError: Cannot read property '_jasmineAdapter' of undefined

It worked  on Monday and now it doesn't anymore. 

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = wallaby => {
    return {
        files: [
            './app/**/*.js',
            '!/app/**/__tests__/*.js'
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        tests: [
            './app/**/__tests__/*.js'
        ],
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({babelrc: true, presets: [ "es2015",
                "react",
                "stage-0"]})
        },
        setup(wallaby) {
            wallaby.testFramework.configure(require('./package.json').jest)
        },
        debug: true

    };
};
```

### Code editor or IDE name and version

IntelliJ Ultimate IDEA latest release

### OS name and version

OSX and using Jest 19.0.2

**Comment by ArtemGovorov** [comment]
Thanks for the report! Looks like our recent changes for Jest 21 had affected Jest 19 support. The issues is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
