### ISSUE TITLE
when adding console.log to functions in node_modules, I get "console.log is not a function"

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1336]
Sometimes I like to do a quick test of something in node_modules, but I can't add logging to it without getting this error. That's very bizarre. It makes me wonder what would happen if it had logging of its own--would it not work?

Anyway, what's the prescribed remedy here?

**Comment by ArtemGovorov** [comment]
> That's very bizarre.

It is indeed. I have never seen an error like this, even though I occasionally add `console.log` to node modules. Could you please share a way to reproduce it?

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please share a sample repo demonstrating the issue - we are happy to have a look into it.
