### ISSUE TITLE
Uncaught ReferenceError: Zone is not defined, Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by spinachandkale** [wallabyjs/public#1337]
### Issue description or question
Unable to run wallaby due to below issues. Please help.

<img width="1091" alt="screen shot 2017-10-07 at 2 25 51 pm" src="https://user-images.githubusercontent.com/25850583/31311274-6669ce2c-ab6e-11e7-94c4-f052bda1e83f.png">

(i) Zone is not referenced in any place in my project
Tried adding/removing zone.js to package.json with below line, still getting same error.
    "zone.js": "^0.8.14"
(ii) For the second error, tried rebuilding node-sass with the given command, still seeing same error
'npm rebuild node-sass --force'

### Wallaby.js configuration file

Config is same as given in angular cli example. changed env to chrome, tsconfig to right path and commented out wallabyTest.js. 

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./src/tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      // 'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'src/test.ts', ignore:true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

WebStorm 2017.2.4

### OS name and version

macOS Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
> Zone is not referenced

This
> commented out wallabyTest.js

is exactly the issue.
In the Angular CLI sample config the [`src/wallabyTest.js` bootstraps testing environment and loads zone.js](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts). You need to create the file and paste the content from the sample repo into it.

> Node Sass could not find a binding for your current environment.

By default, when you create a new Run Configuration for wallaby in WebStorm, wallaby uses its own node.js version. Node Sass is using native bindings, so the used node.js version has to be the same as the one you've used to installed node-sass node module. To fix the issue you may just edit your wallaby Run Configuration and [change the used node.js version](https://wallabyjs.com/docs/intro/install.html#nodejs) to your system's default one (the one you've used to install `node_modules`).

**Comment by Janatbek** [comment]
@ArtemGovorov , I have wallabyTest.js in my wallaby.js file, but still getting 
```
Uncaught ReferenceError: Zone is not defined
at http://localhost:62691/____wallaby-bundle.js?1547837300420&wallabyFileId=bundle:3708
```

**Comment by ArtemGovorov** [comment]
@Janatbek I'm assuming the issue has been resolved for you by https://github.com/wallabyjs/ngCliWebpackSample/pull/41. If not, please create a sample repo demonstrating your issue and open a new issue in this repo.
