### ISSUE TITLE
Testing React 16

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1339]
### Issue description or question

Hi, is it somehow possible to make React dump also the line with error? Currently when error happens during render all I see in Wallaby log is:

```
An error was thrown inside one of your components, but React doesn't know what it was. This is likely due to browser flakiness. React does its best to preserve the "Pause on exceptions" behavior of the DevTools, which requires some DEV-mode only tricks. It's possible that these don't work in your browser. Try triggering the error in production mode, or switching to a modern browser. If you suspect that this is actually an issue with React, please file an issue.​​
    ​​​​​​​​​​
    ​​​​​From console:​​​​​
      ​​​​​​​​​​
      ​​​​​Error: Uncaught [TypeError: Cannot read property 'readonly' of undefined]​​​​​
      ​​​​​    at reportException (/Users/tomi/Github/packages/webpack2-typescript-2/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:63:24)​​​​​
      ​​​​​    at invokeEventListeners (/Users/tomi/Github/packages/webpack2-typescript-2/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:211:9)​​​​​
      ​​​​​    at HTMLUnknownElementImpl._dispatch (/Users/tomi/Github/packages/webpack2-typescript-2/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)​​​​​
...

​​​​​The above error occurred in the <TabbedEditorView> component:​​​​​
      ​​​​​    in TabbedEditorView​​​​​
      ​​​​​    in Provider​​​​​
      ​​​​​    in div (created by WrapperComponent)​​​​​
      ​​​​​    in WrapperComponent​​​​​
      ​​​​​​​​​​
      ​​​​​Consider adding an error boundary to your tree to customize error handling behavior.​​​​​
      ​​​​​You can learn more about error boundaries at https://fb.me/react-error-boundaries.​​​​​
```

So, I can see the error: `Cannot read property 'readonly' of undefined` But I cannot get to the line where it happens and I'm down to guessing.

### Code editor or IDE name and version

Visual Studio Code v1.17.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Is the issue Wallaby specific, or Jest CLI also doesn't report the line number?

Could you please share a sample repo where I could reproduce the issue?

**Comment by tomitrescak** [comment]
I'm using Mocha. The issue is that I receive the React error, where the first line does not have number. It is the same behaviour as in the browser, but browser outputs one more error with the exact line number.

Do you have by any chance a repo with React project so that I do not start from scratch? Thanks.

**Comment by ArtemGovorov** [comment]
> It is the same behaviour as in the browser, but browser outputs one more error with the exact line number.

I'm a bit confused. According to the stack traces that you have provided, you are running tests in node (not in browser), because I can see `jsdom` in the stack entries. Am I wrong? Can I see your current wallaby config? I'll create the sample repo based on it.

> I'm using Mocha

Does running mocha from CLI make it report the correct line number?

**Comment by tomitrescak** [comment]
I'm running tests in both. Node and Browser.
Following in my wallaby.js

```js
// const transform = require("fuse-test-runner").wallabyFuseTestLoader;
const path = require('path');
const jsxtransform = require('jsx-controls-loader').loader;

module.exports = function(wallaby) {
  return {
    files: [
      './src/shared/highlighter.js',
      './setup.js',
      'src/client/**/*.ts*',
      'src/server/**/*.ts*',
      'src/shared/**/*.ts*',
      'src/tests/**/*.ts*',
      '!**/luis.ts',
      '!src/**/*.test.tsx',
      '!src/**/*.test.ts',
      '!src/**/*.d.ts*'
    ],
    tests: [
      'src/tests/setup',
      'src/server/**/*.test.ts',
      'src/client/**/*.test.tsx', 'src/client.**/*.test.ts', 'src/**/snapshots/*.json'
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ jsx: 'react', module: 'commonjs' })
    },
    preprocessors: {
      '**/*.tsx': file => jsxtransform(file.content)
    },
    env: {
      type: 'node'
    },
    workers: {
      initial: 1,
      regular: 1
    },
    hints: {
      ignoreCoverage: /ignore coverage/ 
    },
    delays: {
      run: 200
    },
    testFramework: 'mocha',
    setup: function(wallaby) {
      require('wafl').setup({ wallaby });
    },
    teardown: function(wallaby) {
      require('apollo-connector-mongodb').stopDatabase();
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Thanks,

> I'm running tests in both. Node and Browser.

Does the issue show up when you run your client tests in node without wallaby with mocha from CLI? I have a feeling that the issue is not wallaby specific and may be specific to the difference between node/jsdom and browser environments. 

Anyway, I have created this sample repo https://github.com/ArtemGovorov/wallaby-1339, the error from the component render function seem to be reported as expected:

<img width="931" alt="screen shot 2017-10-11 at 12 07 38 pm" src="https://user-images.githubusercontent.com/979966/31419034-d089a4d8-ae7c-11e7-954f-1b21b2554069.png">

Please take a look to see if you can use the repo to reproduce the issue.

**Comment by tomitrescak** [comment]
Artem, thanks to your config I found out that the problem was in jsdom initialisation. I had:

```js
require('jsdom-global')();
```

while this is correct:

```js
if (!global.document) {
  require('jsdom-global')();
}
```

Thanks for your support.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
