### ISSUE TITLE
Support the SPFx Framework with a guide/tutorial/configuration example

### ISSUE THREAD

**Issue by michel-weber** [wallabyjs/public#1340]
### Suggestion
I'm having issues configuring wallabyjs for the SharePoint Framework (SPFx). Wallabyjs seems to be the only player in town to do continuous unit testing like NCrunch is doing for the .NET World (with code coverage, ...).
Wallabyjs could broaden it's user base even more if there was a tutorial/guide how to configure it for the SPFx Framework.

I think it would take me quite some time to figure it out. The SPFx Framework uses quite some tooling (TypeScript, Gulp, WebPack, Mocha & Chai) so this is not such an easy task.

**So this is a feature request to provide a guide/tutorial/configuration which can be used by people using the SPFx Framework.**

Some information on the SharePoint Framework (SPFx):
[Overview of the SharePoint Framework](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview)
[Tools and libraries](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tools-and-libraries)
[SharePoint Framework client-side web part samples & tutorial materials](https://github.com/SharePoint/sp-dev-fx-webparts)

### Code editor or IDE name and version
Visual Studio Code v1.16.1
SharePoint Framework 1.3.2

### Resources:
[Better JS Testing Experience with VS Code and Wallaby.js](http://www.andrewconnell.com/blog/better-js-testing-experience-with-vs-code-and-wallaby-js)

**Comment by ArtemGovorov** [comment]
I can see a lot of [samples for SPFx using different app frameworks](https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples), such as Angular, React, Vue. Any particular sample or app framework you're using and having issues configuring wallaby.js for?

**Comment by michel-weber** [comment]
Hi Artem,
thank you for extending a helping hand.

The SharePoint Framework (SPFx) is framework agnostic so you can use different app frameworks on top of it. But the SharePoint Framework already uses:
- TypeScript
- WebPack
- Mocha
- Chai

I'm trying to configure it for a HelloWorld-App as it is generated by the yeoman generator (`yo @microsoft/sharepoint`). Consequently I have to configure it for TypeScript, WebPack, Mocha, ...

I will upload a sample to GitHub asap.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the sample repo. I have created a [basic wallaby config](https://github.com/michel-weber/spfx-helloworld-wallabyjs/pull/1) based on the sample webpack config from [our Webpack integration docs](https://wallabyjs.com/docs/integration/webpack.html).

**Comment by michel-weber** [comment]
Thank you for your pull request :+1: .
 It is now working will test it more thoroughly and come back with questions or will close this issue.

Cheers!
