### ISSUE TITLE
Uncaught Error: Cannot find module '371'

### ISSUE THREAD

**Issue by spinachandkale** [wallabyjs/public#1342]
## Issue description or question

Some files are tested by Wallaby and successful, but some files were not considered saying, 'no test coverage' 

Error in Failing-tests.

![screen shot 2017-10-09 at 4 06 01 pm](https://user-images.githubusercontent.com/25850583/31358965-71ec82ee-ad0d-11e7-938e-1d37cc75b9d2.png)

Error in Wallaby-console. 

![screen shot 2017-10-09 at 4 22 41 pm](https://user-images.githubusercontent.com/25850583/31359094-1c57f65a-ad0e-11e7-861d-53668857ef97.png)

Yesterday during one run indicator showed green so thought all is well, but re-run today threw these errors.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm 2017.2.4

### OS name and version

macOS Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
What has changed in your project since yesterday?
Are there any other errors in the Wallaby Console or the Failing Tests Console?

**Comment by spinachandkale** [comment]
Nothing has changed since yesterday. Before that Wallaby threw some errors like 'BrowserAnimationsModule' or 'FormsModule' is missing, I fixed those errors. 

>> Are there any other errors in the Wallaby Console or the Failing Tests Console?

No, only the ones shown in above images

**Comment by ArtemGovorov** [comment]
Please attach (or send to hello@wallabyjs.com) your `____wallaby-bundle.js` file. You may get the file by opening the error URL in chrome and then replacing the `wallaby-webpack...` part with `____wallaby-bundle.js`. Note that the file is quite large so you may need to wait until it fully loads in chrome.

**Comment by spinachandkale** [comment]
It has source code belong to the company, I don't think I can give that file. Apologies. 
Please let me know what to look for in that file, I will see and let you know.

Is there any way to find what module it is missing, 371 doesn't look like a module name.

**Comment by ArtemGovorov** [comment]
> 371 doesn't look like a module name

It is webpack generated id (it assigns numeric ids to all modules internally).

Try searching the `____wallaby-bundle.js` file for `371`, see what you find.

**Comment by spinachandkale** [comment]
It has no reference of 371. 

Is it possible to give any config parameters to webpackPostprocessor in wallaby.js?

**Comment by ArtemGovorov** [comment]
> Is it possible to give any config parameters to webpackPostprocessor in wallaby.js that gives module numbering?

I'm not sure, it'd be some webpack setting, not wallaby one.

> It has no reference of 371.

It is interesting. 
- Maybe one of your specs is referencing other spec files?
- Try specifying your spec files one by one and running wallaby to find what spec file is causing the issue, ie.:

```javascript
   tests: [
      {pattern: 'src/**/1.spec.ts', load: false}, // then try 2.spec.ts, etc.
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],
```

**Comment by spinachandkale** [comment]
You are absolutely correct. One of the non-test file named as .spec.ts which caused bit of mix up. I removed the files that are causing this issue. Everything is working perfectly now. 

Thanks for the help. Super quick and accurate :-)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
