### ISSUE TITLE
[VSCode] Option to disable notifications about extension updates

### ISSUE THREAD

**Issue by ProLoser** [wallabyjs/public#1343]
I would like to have the option to silence all future update notifications for wallaby.js

It's nice that it auto-updates the extension, but many other extensions do the same, some even present changelogs and other such options. However the other options have a button to no longer notify me with notifications about extension updates. This isn't a big deal but since you push updates so frequently (which is great) I see this every time I open my IDE and it's just a few more mandatory clicks to dismiss the 3 generated notifications.

**Comment by ArtemGovorov** [comment]
The feature has just been published in Wallaby VS Code extension 1.0.64.

You may now silence update notifications for wallaby.js by adding the following setting to your VS Code settings:
```
...
"wallaby.showUpdateNotifications": false,
```
