### ISSUE TITLE
Angular NX config?

### ISSUE THREAD

**Issue by AustinMatherne** [wallabyjs/public#1347]
### Issue description or question
I'm looking at converting some of our Angular repos over to a mono repo using [Nrwl Extensions for Angular](https://nrwl.io/nx). I'm trying to tweak the Angular CLI wallaby config to work with the mono repo layout. I created a [simple example repo](https://github.com/AustinMatherne/angular-nx/pull/1/files) to test out, but I'm currently getting a few errors from wallaby.

```shell
​​Specified entry pattern "wallabyTest.js" does not match any file.​​
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/protractor/built'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/protractor/built'​​
...
​​​​Module not found: Error: Can't resolve 'repl' in '/Users/amather/repos/nx/node_modules/protractor/built'ModuleNotFoundError: Module not found: Error: Can't resolve 'repl' in '/Users/amather/repos/nx/node_modules/protractor/built'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/io'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/io'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/net'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/net'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/firefox'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/selenium-webdriver/firefox'​​
...
​​Module parse failed: /Users/amather/repos/nx/node_modules/blocking-proxy/built/lib/bin.js Unexpected character '#' (1:0)​​
​​You may need an appropriate loader to handle this file type.​​
​​| #!/usr/bin/env node​​
​​| "use strict";​​
​​| const blockingproxy_1 = require('./blockingproxy');ModuleParseError: Module parse failed: /Users/amather/repos/nx/node_modules/blocking-proxy/built/lib/bin.js Unexpected character '#' (1:0)​​
...
​​Module not found: Error: Can't resolve './lib-cov/SauceLabs' in '/Users/amather/repos/nx/node_modules/saucelabs'ModuleNotFoundError: Module not found: Error: Can't resolve './lib-cov/SauceLabs' in '/Users/amather/repos/nx/node_modules/saucelabs'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/io'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/io'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/net'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/net'​​
...
​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/firefox'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/webdriver-js-extender/node_modules/selenium-webdriver/firefox'​​
...
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'wallabyTest.js',
      'apps/**/*spec.js',
      'libs/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'apps/**/*.d.ts', ignore: true},
      {pattern: 'apps/**/*spec.ts', ignore: true},
      {pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'libs/**/*.d.ts', ignore: true},
      {pattern: 'libs/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'apps/**/*spec.ts', load: false},
      {pattern: 'libs/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.17.1

### OS name and version

macOS High Sierra v10.13

**Comment by ArtemGovorov** [comment]
> ​​Specified entry pattern "wallabyTest.js" does not match any file.​​

This is because the `wallabyTest` file wasn't included in the `files` list.

> ​​Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/protractor/built'ModuleNotFoundError: Module not found: Error: Can't resolve 'child_process' in '/Users/amather/repos/nx/node_modules/**protractor**/built'​​

This is because `e2e` pattern wasn't excluded from the `tests`. In the angular CLI sample this wasn't required because the `e2e` folder was not in the included `src` folder.

There's also [missing `polyfills` import](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts#L1) in your `wallabyTest` file.

I have sent you the [pull request with the changes to make it work](https://github.com/AustinMatherne/angular-nx/pull/2). Let me know if this works for you.

**Comment by AustinMatherne** [comment]
Worked like a charm. Thank you!

**Comment by zpydee** [comment]
@ArtemGovorov 

Hi Artem,

Hope you're well. Would you mind posting the required wallaby configuration as a gist as you have for other environments. I've tried to follow this and related threads but I'm still getting module import issues...


```bash
​​Module not found: Error: Can't resolve '@mystique/mystique-utils-http' in './libs/mystique-utils-validators/src/services'ModuleNotFoundError: Module not found: Error: Can't resolve '@mystique/mystique-utils-http' in '/Users/zpydee/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.67/projects/6c0b6ad6902ba7a6/instrumented/libs/mystique-utils-validators/src/services'​​
```

**Comment by zpydee** [comment]
sorry, forgot to mention - this would be for a nrwl/nx setup

**Comment by ArtemGovorov** [comment]
@zpydee The error message you've posted doesn't seem to be nrwl/nx related. 

> ​​Module not found: Error: Can't resolve '@mystique/mystique-utils-http'

means that webpack can not find the module, that means it is not in your `node_modules`. If your prod/test webpack is using `resolve.alias` for the module, then you need to configure the same alias in your `webpackPostprocessor`. 

It the suggest above doesn't work, please share a sample repo where the issue can be reproduced, happy to help with the config.

**Comment by zpydee** [comment]
hmmmm, thanks for that feedback. not exactly a webpack expert, i've gotten comfortable with just using ng-cli. i'll take a look thanks. unfortunately, my repo is private and already far to complex to try duplicate the error

**Comment by zpydee** [comment]
in such a case though, why would karma not experience the same issue?

**Comment by ArtemGovorov** [comment]
> my repo is private and already far to complex to try duplicate the error

The error shouldn't need much to reproduce. Any simplified file that imports `@mystique/mystique-utils-http`, like a stripped down version of the `libs/mystique-utils-validators/src/services`, plus your config files (wallaby, package.json, etc), plus a dummy test file that imports the file importing the `@mystique/mystique-utils-http` module, should be enough.

> in such a case though, why would karma not experience the same issue?

Karma is using a different webpack config, and not the one you have in your wallaby config. 

If you run `ng eject` for your project and share the generated webpack config, it may shed some light.

What is `@mystique/mystique-utils-http`? Is the module installed in your `node_modules`, ie. is there a `node_modules/@mystique/mystique-utils-http` folder? Do you have any special configuration (anywhere) for the `@mystique/mystique-utils-http` module (like a mapping or an alias)?

**Comment by zpydee** [comment]
all @mystique packages are nrwl/nx libs, not external.

**Comment by ArtemGovorov** [comment]
@zpydee Sorry, I'm not an expert in nrwl/nx (have never used it), so will need to more information to help with configuring wallaby for it. 

Could you please either create a sample where I could reproduce the issue (that'd be the fastest way for us to help you with the config file), or 

- run `ng eject` for your project and share the generated webpack config,
- check the `@mystique/mystique-utils-http` module is present in your `node_modules` or not.

**Comment by ArtemGovorov** [comment]
@zpydee I'm also not sure what do you mean by

> all @mystique packages are nrwl/nx libs, not external.

If I run `npm install --save @nrwl/nx`, and search in the installed node modules and all files in the `node_modules/@nrwl`, I can't find any `@mystique` packages or libs.

**Comment by zpydee** [comment]
i've ejected. the webpack config is probably a bit too big to post here. can I mail you?

**Comment by ArtemGovorov** [comment]
@zpydee Creating and sharing a gist would be perfect. Alternatively, please email it to hello@wallabyjs.com.

**Comment by zpydee** [comment]
have mailed you gist link

**Comment by ArtemGovorov** [comment]
@zpydee Thanks, I've had a look. It's still not clear from the webpack config though, how the `@mystique/mystique-utils-http` module is resolved. There're no special alias, so webpack is supposed to look it up in your `node_modules` (both for wallaby and karma).

Is the `@mystique/mystique-utils-http` module is present in your node_modules or not? How's webpack supposed to resolve it? 

Unfortunately, I'm running out of ideas. Creating a sample where I could reproduce the issue is the best way to proceed. As I have mentioned, it hopefully shouldn't take much time.

**Comment by zpydee** [comment]
so... thus interesting that karma resolves all modules. let me see if I can reproduce...
as always, thanks for your amazing attention to customer support!

**Comment by Epenance** [comment]
@zpydee Did you ever find a way to use the paths setup within the tsconfig? It seems to still be failing me to get them to work with Wallaby.

**Comment by ArtemGovorov** [comment]
@Epenance Take a look [here in our docs](https://wallabyjs.com/docs/integration/typescript.html#typescript-compileroptionspaths-setting) to see if it helps. If it doesn't, please create a sample repo demonstrating the issue - we are happy to have look and help with the config.

**Comment by zpydee** [comment]
I'm also still unable to use wallaby within my nx project...

**Comment by Epenance** [comment]
Actually got it working by adding this to my wallabyjs file:

```
alias: {
        '@impactdk': path.resolve(wallaby.projectCacheDir, 'libs')
      }
```

**Comment by zpydee** [comment]
@ArtemGovorov is there a final guide for configuring a nrwl/nx project yet?

**Comment by ArtemGovorov** [comment]
@zpydee There's no special guide planned, the config file from topic starter sample project is working. If there are any project specific issues, please create a sample repo demonstrating those, happy to have a look.

**Comment by zpydee** [comment]
@ArtemGovorov in the interests of completing this thread and to assist others in not having to hunt around for the correct configuration, would you mind pasting the suggested `wallaby.js` and wallabyTest.ts` configurations as a final post, or alternatively publish and link to a gist?

**Comment by ArtemGovorov** [comment]
@zpydee The original issue author had accepted my pull request, so there's even a [full sample](https://github.com/AustinMatherne/angular-nx) with all the configs and requested files in the right places.

`wallabyTest.ts`

```javascript
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import {getTestBed} from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);
```

`wallaby.js` (it is basically the same as [Angular CLI generated project one](https://github.com/wallabyjs/ngCliWebpackSample) with 2 roots (`apps` and `libs`) instead of just a single root).

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'wallabyTest.js',
      'apps/**/*spec.js',
      'libs/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'wallabyTest.ts', load: false},
      {pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'apps/**/*.d.ts', ignore: true},
      {pattern: 'apps/**/*spec.ts', ignore: true},
      {pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'libs/**/*.d.ts', ignore: true},
      {pattern: 'libs/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'apps/**/*spec.ts', load: false},
      {pattern: 'libs/**/*spec.ts', load: false},
      {pattern: 'apps/**/e2e/**', ignore: true},
      {pattern: 'libs/**/e2e/**', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },
  };
};
```

**Comment by zpydee** [comment]
@ArtemGovorov still getting errors. i have invited you to my repo. please check out `wallaby` branch

**Comment by ArtemGovorov** [comment]
@zpydee Thanks, made a commit to wallaby.js in your repo to fix it. The issue is that webpack alias wasn't added, a similar case is described at https://github.com/wallabyjs/ngCliWebpackSample/issues/30.

**Comment by zpydee** [comment]
@ArtemGovorov many thanks - its so good to have my wallaby installation working again!

**Comment by tomwhite007** [comment]
Hello @zpydee and any other Nrwl Nx users.

If you have any further problems configuring Wallaby with the latest version of Nrwl Nx 6.1.0, @ArtemGovorov helped me out last week, and we've now got a working demo repo:
https://github.com/TomWhiteOmni/angular-nx-wallaby

Cheers 
Tom
