### ISSUE TITLE
Issue importing TypeScript class with multiple parts separated by '.' into test file.

### ISSUE THREAD

**Issue by devonhumes** [wallabyjs/public#1348]
### Issue description or question

This is a really weird issue that I can reliably reproduce, but I really hope is not specific to my machine!

I am getting the error `TypeError: Cannot read property '0' of undefined` when I attempt to use a class imported from a file that ends in `*.fixture.ts`.

I have uploaded a reproducible (at least on my machine) test case to github at https://github.com/devonhumes/wallaby-issue-with-importing-class. Checkout / download the code and run `npm install` then run the steps below.

Steps to reproduce:
1. Start Wallaby process in Intellij IDEA (see version below)
2. Note that the test passes initially
3. Comment out `fixture = new ServiceOrchestratorFixture();` (line 9) in `service-orchestrator.spec.ts`
4. Test should pass
5. Uncomment the line from step 3
6. Test should fail with `TypeError: Cannot read property '0' of undefined`
7. Repeat 3-6

Now if you change the name of `service-orchestrator.fixture.ts` to `service-orchestrator.ts`, update `wallaby.js` and then run the previous steps it doesn't fail anymore. Is there some logic that is parsing the extension?

### Wallaby.js configuration file

See https://github.com/devonhumes/wallaby-issue-with-importing-class for the full reproducible project.

```javascript
module.exports = function () {
    return {
        files: [
            'lib/use-cases/service-orchestration/service-orchestrator.ts',
        ],

        tests: [
            'lib/use-cases/service-orchestration/service-orchestrator.spec.ts',
            'lib/use-cases/service-orchestration/service-orchestrator.fixture.ts'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'mocha'
    };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v2017.2.5

### OS name and version

OSX 10.13 - High Sierra

**Comment by ArtemGovorov** [comment]
Thanks for putting the repo together.

I have sent you the pull request - https://github.com/devonhumes/wallaby-issue-with-importing-class/pull/1 to make it work.

Wallaby [requires the `tests` list to only contain entry files with tests](https://wallabyjs.com/docs/config/files.html#tests) (that are not imported by other files), so the `service-orchestrator.fixture.ts` file needs to be in the `files` list.

Let me know if it addresses the issue.
