### ISSUE TITLE
Missing "Show last run screenshot" option when using create-react-app config

### ISSUE THREAD

**Issue by semeltheone** [wallabyjs/public#1349]
Hi,
we are using the create-react-app config from here: 
https://wallabyjs.com/docs/integration/react-jsx.html

As far as I understand, this code snippet should be sufficient to modify the dom and show the "Show last run screenshot" option:

```
describe('foo', () => {
    it.only('bar', () => {

        document.body.innerHTML="<p>test</p>";

    });
}) ;
```

We are using Webstorm and Wallaby v1.0.506.

Is there a way to make this feature work with the create-react-app config from above?

**Comment by ArtemGovorov** [comment]
The `Show last run screenshot` feature only works when running tests in browser (PhantomJs). Jest (used in `create-react-app`) runs in node (via `jsdom`), and real DOM is not rendered there, so unfortunately it's not possible to make a screenshot.

**Comment by semeltheone** [comment]
OK. Thank you for your fast response. Wallaby and Quokka are real game changers.
Keep up the good work!

**Comment by ArtemGovorov** [comment]
@semeltheone Thank you!
