### ISSUE TITLE
Wallaby with Typescript - 0% coverage on VS 2017, VS Code en http://wallabyjs.com/app/#/files

### ISSUE THREAD

**Issue by spapaseit** [wallabyjs/public#1352]
### Issue description or question
On a .NET Core, Aurelia en TypeScript app I have 62 passing tests. All specs display de green squares, which turn red when the tested file is changed.

The tested files, however, only show grey squares, both on VS Code and VS 2017. Navigating to `http://wallabyjs.com/app/#/files`  displays 0% coverage.

### Wallaby.js configuration file

```javascript
// https://github.com/wallabyjs/public/issues/863#issuecomment-259416922
var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
    if (filePath === 'source-map-support') {
        return { install: () => { } };
    }
    return originalRequire.call(this, filePath);
};

/* eslint-env node  */
const path = require('path');

const { AureliaPlugin } = require('aurelia-webpack-plugin');
var wallabyWebpack = require('wallaby-webpack');
const { TsConfigPathsPlugin, CheckerPlugin } = require('awesome-typescript-loader');

module.exports = function (wallaby) {
    process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;

    var wallabyPostprocessor = wallabyWebpack({
        resolve: {
            alias: {
                interact: path.resolve(__dirname, "node_modules", "interactjs", "dist", "interact.js")
            },
            extensions: ['.ts', '.js'],
            modules: [path.join(wallaby.projectCacheDir, 'src'), 'node_modules'],
            plugins: [
                new TsConfigPathsPlugin()
            ]
        },
        module: {
            rules: [
                { test: /\.ts$/i, loader: 'awesome-typescript-loader' }
            ]
        }
    });

    return {
        files: [
            { pattern: "node_modules/babel-polyfill/browser.js", instrument: false },
            { pattern: "node_modules/jquery/dist/jquery.js", instrument: false },
            { pattern: "src/**/*.ts", load: false },
            { pattern: "test/stubs/**/*.ts", load: false },
            { pattern: "test/fakes/**/*.ts", load: false },
            { pattern: "test/unit/setup.ts", load: false },
            { pattern: 'node_modules/interactjs/dist/interact.js', instrument: false },
        ],

        tests: [
            { pattern: "test/unit/**/*.spec.ts", load: false }
        ],

        env: {
            kind: "electron"
        },

        postprocessor: wallabyPostprocessor,

        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2
Visual Studio v2017

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
I have recently helped set up Aurelia + TypeScript + Webpack here https://github.com/wallabyjs/public/issues/1350#issuecomment-337484397 and it worked (you my find the full project in the linked issue). Try the config from there (may remove kendo-ui bits, those are irrelevant). If the config from the sample doesn't work for you, please set up a sample repo demonstrating the issue.

**Comment by spapaseit** [comment]
Hi @ArtemGovorov, just a quick heads-up; the referenced configuration did not work for us. I'll prepare a sample repo asap.

**Comment by spapaseit** [comment]
Sorry it took so long @ArtemGovorov, here you can find a repo demonstrating the issue:
https://github.com/codenamednl/wallaby-lights-issue

You can just `npm i` or `yarn` it; the app doesn't run as such, but it demonstrates the issue: red-green lights are displayed [on the test](https://github.com/codenamednl/wallaby-lights-issue/blob/master/test/unit/utils/array-operations.spec.ts), but not on [the source file](https://github.com/codenamednl/wallaby-lights-issue/blob/master/src/utils/array-operations.ts).

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

When using with Webpack, the default wallaby TypeScript compiler needs to be used (it doesn't require any config and is used by default). [Using TypeScript loader in addition to that, interferes with Wallaby instrumentation](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript), and is not required to run tests with Wallaby.

I have sent you [this PR to make the configuration work](https://github.com/codenamednl/wallaby-lights-issue/pull/1).

Note that is you still need to use TypeScript webpack loader for something that wallaby doesn't compile by default (like some of `node_modules` published in TypeScript), you may leave the code you had (that I deleted in the PR), but modify it as follows:

- change the `extensions` order to first have `.js` and then `.ts`: `extensions: ['.js', '.ts']`,
- restrict the scope of the `at-loader` rule to node_modules (or a specific node_modules): ` { test: /\.ts$/i, loader: 'awesome-typescript-loader', include: /node_modules/ }`
