### ISSUE TITLE
VSCode - wallaby.js support for multi-root workspaces

### ISSUE THREAD

**Issue by forestmaxime** [wallabyjs/public#1353]
Hi!

I was wondering if wallaby.js in the future version of VS Code 1.18 will support Multi-Root workspaces in any ways?

**Proposition:**
The VSCode extension could find each wallaby.js files inside the workspace and run each tests. 

**Nice to have but would be really useful:**
Run a specific project. The menu of CTRL+P Wallaby.js Start could also pop another menu when multiple wallaby.js found in the workspace and prompt us to choose between: All, Project 1 OR Project 2. The project name can come from the package.json file.

**Comment by ArtemGovorov** [comment]
Hi,

Wallaby already supports Multi-Root workspaces. You may use the `Wallaby.js: Select Configuration File` command from the editor Command Palette to select wallaby config file that you'd like to run. The provided list of suggested config files includes wallaby config files from all projects in the workspace.

Wallaby doesn't run multiple config files at the same time (neither in VS Code, nor in any other supported editors, there's a separate feature request for it: https://github.com/wallabyjs/public/issues/89).
