### ISSUE TITLE
VSCode - Show code coverage at the bottom right corner

### ISSUE THREAD

**Issue by forestmaxime** [wallabyjs/public#1354]
Hi!

One feature that would be really nice to have until the webapp support multiple projects is to have code coverage displayed in the bottom right corner of the VS Code extension.

**Proposition:**
Show code coverage at the bottom right by default
Add a setting that can disable code coverage.
If multi-root workspace is supported at the same time (see my other issue #1353) then we would need a way to see the % per projects. There is 2 ways I have in mind for showing that:
- Average of all projects with hover that show the drilldown (fastest one)
- The project % in the opened file, if nothing is selected then fallback to average of all projects with hover (nice to have)

**Nice to have:**
Thresholds per wallaby.js file to show the coverage indicator in VS Code in red (or an icon) if under the threshold.
In multiple projects it would react the same as in single project where the indicator shows red (or icon) if one of the project is under the threshold.

**Comment by forestmaxime** [comment]
I see you've implemented this feature!!! 👍 

You can close this issue

Thanks!

**Comment by ArtemGovorov** [comment]
Yep, the feature had been recently implemented and published :)
