### ISSUE TITLE
VS Code - add a setting for auto-running Wallaby.js

### ISSUE THREAD

**Issue by orta** [wallabyjs/public#1357]
### Issue description or question

Hello there! I've got Wallaby set up on a few of my projects and I expect it to be the main way that I interact with tests. I'd like to be able to indicate that Wallaby should [load by default](https://github.com/orta/vscode-jest/blob/master/package.json#L48-L52) inside my projects settings. E.g. in `.vscode/settings.json`:

```json
{
  "wallaby.js.startOnOpen": true
}
```

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

Visual Studio Code v1.x

**Comment by ArtemGovorov** [comment]
Hello! Glad to hear you like the tool!

You may use this awesome extension (made to run wallaby.js automatically when a project is opened, but can also run any other commands, even conditionally) to autostart wallaby.

Let me know if the suggested solution works for you.

**Comment by orta** [comment]
Clever, yep that works for me 👍
