### ISSUE TITLE
SyntaxError: Parse error when including unexpected-dom

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#136]
When unexpected-dom is required, wallaby.js reports simply
```
wallaby.js started
core v1.0.54
Runtime error: SyntaxError: Parse error
Finished executing 0 affected test(s)
```
and always reports that 0 tests were found.

I've pushed a demo repo with minimal code to reproduce the issue [bruderstein/wallabyunexpected](https://github.com/bruderstein/wallabyunexpected) 

Removing the require('unexpected-dom') fixes the issue.

Is there a more detailed log anywhere?

I've tried marking unexpected-dom and jsdom as instrument:false, but that causes wallaby to hang.
(jsdom isn't used by unexpected-dom, but is required if no DOM is found, so I assume wallaby expects it to be installed due to `require('jsdom')` being in the AST)

If there's something we can do to unexpected-dom to fix this, then that'd be great too.

Thanks for an awesome product :)

**Comment by ArtemGovorov** [comment]
I'm not yet 100% sure what's issue reason, but it seems like phantomjs fails when loading unexpected-dom browserified by wallaby.js. Unfortunately, `SyntaxError: Parse error` is the only message phantomjs provides in this case, so there's not much more information wallaby can provide you.

I have sent you the pull request to make everything work https://github.com/bruderstein/wallabyunexpected/pull/1 by loading unexpected and unexpected-dom right into the sandbox as opposed to loading them with browserify. It's not the fix of the issue, more like a work-around, but as a small bonus it works faster as browserify doesn't need to process something that is already available for loading.

When using node_modules with browserify, you don't normally need to list them in your `files` list. Wallaby.js automatically lets browserify know about your local node_modules folder when building everything. In my PR I'm adding browser-ready versions directly to the test page without `require`-ing them (just like you did with the `phantomPolyfill`).

More detailed log can be viewed in the Wallaby Console with `debug: true` set in your wallaby config (I have added a comment in the pull request). In this particular case though, I have said, `SyntaxError: Parse error` is the only message phantomjs provides, so more detailed log from wallaby wouldn't probably shed much more light.

PhantomJs may throw syntax error on [things you'd never think could cause the issue](https://github.com/wallabyjs/public/issues/33), so it's hard to say what exactly is causing the issue, but I'll try to find it out. Either way, hope the workaround helps.

**Comment by ArtemGovorov** [comment]
Also, I have just thought, since you've mentioned that you are using `jsdom`, is there a particular reason you'd like it work in browser environment and not in node.js environment?

Wallaby.js supports running tests in [node.js environment](https://github.com/wallabyjs/public#environment-setting), so the simple config like
``` JavaScript
module.exports = function () {
    return {
        files: [
            { pattern: 'src/**/*.js' }
        ],

        tests: [
            { pattern: 'tests/*.spec.js' }
        ],

        env: {
            type: 'node'
        }
    }
};
```
should just work for you.

**Comment by bruderstein** [comment]
Thanks for the super quick response.  I found the link to the other odd parse error from phantomjs after I sent the issue, and had checked if there was anything similar.  The workaround is fine.

I got stuck with `env: { type: 'node' }` as I couldn't get it to require the '.jsx' files - just simply "Cannot find module '../Login', when the file is called '../Login.jsx'.  

I've tried adding `require.extensions['jsx'] = require.extensions['js]` in bootstrap (not sure if that's early enough), and in a file that's loaded in the sandbox, and neither worked.  I guess renaming the .jsx to .js is an option, now that babel just does it all, but if there's a way to keep the .jsx that would be ideal.

Feel free to close this issue, even if there's no way to override the require. I see [wallaby-react-component](https://github.com/wallabyjs/wallaby-react-component) doesn't export the component, and just creates a variable. Works if you're not browserifying/webpacking everything.

**Comment by ArtemGovorov** [comment]
Have a look here - https://github.com/bruderstein/wallabyunexpected/commit/79beae8a9ca4488c054a47304e011e7637ee6135, I'm using babel preprocessors and `changeExt` function of the file to transparently change it from `jsx` -> `js` on the fly so you can keep your file name and let wallaby do the trick.

If you'd like to do it without `changeExt` call, you still can, using the way you have been trying. It probably didn't work because you're missing `.`s, it should work like this:
``` JavaScript
    bootstrap: function () {
      require.extensions['.jsx'] = require.extensions['.js'];
      global.React = require('react');
      global.expect = require('unexpected');
      global.expect.installPlugin(require('unexpected-dom'));
    }
```

**Comment by bruderstein** [comment]
Argh, thanks, sorry, I thought I'd checked that. Looks good to me. Thanks.
