### ISSUE TITLE
Wallaby fails to import 3rd party MomentModule, works with ng test

### ISSUE THREAD

**Issue by studds** [wallabyjs/public#1360]
### Issue description or question

I'm importing a third party module `MomentModule` in my test (https://github.com/urish/angular2-moment). The tests run fine with `ng test`, but fail in wallaby with the error "Unexpected value 'MomentModule' imported by the module 'DynamicTestModule'. Please add a @NgModule annotation.​​"

I've reproduced the issue in https://github.com/studds/ngCliWebpackSample. The only change from the base repo is installing angular2-moment and importing MomentModule in the test. (Obviously in my own code, I'm actually using the pipes provided by MomentModule: this makes no difference for reproducing the error.)

```typescript
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        MomentModule
      ]
    }).compileComponents();
  }));
```

I figure this is something to do with wallaby's webpack config, but having played around with it a bit, I'm no closer to working out where the problem lies.

Any help very much appreciated!

### Wallaby.js configuration file

See https://github.com/studds/ngCliWebpackSample (unmodified from  https://github.com/wallabyjs/ngCliWebpackSample)

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

OSX Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
I've just tried your repo https://github.com/studds/ngCliWebpackSample and it's working for me without any issues in Visual Studio Code v1.17.2 in OSX Sierra 10.12.6:

<img width="721" alt="screen shot 2017-10-24 at 9 37 18 am" src="https://user-images.githubusercontent.com/979966/31918228-fdd50190-b89e-11e7-8c07-d12c89af3a25.png">

Are you sure no pipes provided by the MomentModule required to reproduce the issue?

Could you please 
- start wallaby on the sample project https://github.com/studds/ngCliWebpackSample,
- open your Wallaby Console output channel in VS Code, 
- search for `File cache:`, 
- open the found folder, archive and attach the `instrumented` folder.

**Comment by studds** [comment]
Hmm, tried on a different computer and it worked. Looks like it's something environment specific... I'll look into it further, see if I can't nut out what's happening. Thanks @ArtemGovorov !

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please provide the info requested above - we are happy to have a look into it.
