### ISSUE TITLE
Any way to see the contents of the Wallaby cache?

### ISSUE THREAD

**Issue by BrianHanechak** [wallabyjs/public#1363]
### Issue description or question

I had something that was just working, and Wallaby updated and now it's not. In the debug log, I have:

[Info]​​​​​ Wed, 25 Oct 2017 05:52:47 GMT wallaby:project Error: Failed to parse shapeProcessor-spec.js, SyntaxError: Unexpected token (28:4)
​​​​​
I'm using TypeScript and I'm not manually compiling the -spec files... is there a way I can see the output of Wallaby's compile operations, in an effort to try to figure out what's gone wrong?

Also, is there a way to downgrade to the previous version where this was working?

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    debug: true,
    files: [
      '**/*.ts',
      { pattern: '**/*-spec.ts', ignore: true }
    ],

    tests: [
      '**/*-spec.ts'
    ],

    env: {
      type: 'node'
    },
    testFramework: 'jasmine'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> is there a way I can see the output of Wallaby's compile operations, in an effort to try to figure out what's gone wrong?

In may cases it is possible, but unfortunately not in this specific case.

Could you please paste the content of the `shapeProcessor-spec.ts` file and your `tsconfig.json` file?

> Also, is there a way to downgrade to the previous version where this was working?

Yes, you may manually download previous versions of Wallaby Core [as described here](https://wallabyjs.com/docs/intro/troubleshooting.html#vs-code). You may see your current version of wallaby core in the Wallaby Console when you start it.

**Comment by ArtemGovorov** [comment]
Had just been looking through the list of recent changes, and I can't see what could have possibly affected your scenario. Perhaps you've recently updated your TypeScript version or your `tsconfig.json`? So please share the `shapeProcessor-spec.ts` file (or try commenting things out in it to see what it causing the issue) and your `tsconfig.json` file?

**Comment by BrianHanechak** [comment]
My apologies... it was, in fact, a syntax error in my TypeScript code. Not sure why I thought it had been working before the update.

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
