### ISSUE TITLE
Not working with Enzyme (React 16)

### ISSUE THREAD

**Issue by Rob-Samalonis** [wallabyjs/public#1367]
### How to properly run setup/config code
The latest version of Enzyme requires an adapter to be set up in order for tests to pass. Wallaby does not seem like the following code in the config file under setup:
```javascript
const Enzyme = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');
Enzyme.configure({adapter: new Adapter()});
```
The code seems to run in the setup, but the tests do not recognize that anything happened, giving an error: 'Enzyme expects an adapter to be configured'. This error appears on any line that includes a react component.
(Wallaby recognizes the setup code by having it in each .test file, but I would much prefer to just have it in the setup file / called by the setup file).

### Code editor 

Visual Studio Code
React App

### OS
Windows 10

**Comment by ArtemGovorov** [comment]
> React App

If you are using `create-react-app` (with [our config from here](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app)), then you'll need to [include the setup file as described here](https://github.com/wallabyjs/public/issues/1351#issuecomment-337590485).

If you're not using `create-react-app`, please share your wallaby config and your Jest config (if you're using Jest).
