### ISSUE TITLE
How to know if my license is registered

### ISSUE THREAD

**Issue by kavumbi** [wallabyjs/public#1369]
### Issue description or question
I have downloaded and installed wallabyjs for vs2017. I notice that many times it closes itself and cannot restart it until I restart visual studio. This is an expected behavior with free version. However I have a license but I didn't get the prompt to register. I don't remember if I have registered it before and would like a way to check if the license is correctly registered.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v? 2017 Enterprise
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
After you install wallaby.js in Visual Studio, restart the IDE and open any project/solution, or any time you restart the IDE after wallaby.js was installed and open any project/solution, you [should get the license activation popup](https://wallabyjs.com/docs/intro/license.html#visual-studio) **within 10 seconds** after you Visual Studio starts. Open the license activation window from the popup, you may paste your license key in the input field and click the Activate button.

If the activation prompt doesn't show up, it means your license is registered. 

Also, if you have entered your license key, it should be saved in the `c:\\users\\USER\.wallaby\key.lic` file. If the activation prompt doesn't show up, you may edit/create the file and paste your license key into it.

Hope it answers your question.

**Comment by kavumbi** [comment]
That's the problem. I don't get the license activation popup no matter how many times I restart the IDE.

**Comment by kavumbi** [comment]
And there is no key lic in the .wallaby folder. In any case my main concern is to prevent wallabyjs to stop inadvertently.

**Comment by ArtemGovorov** [comment]
> I don't get the license activation popup no matter how many times I restart the IDE.

Note that you have to open some project/solution as well.

> And there is no key lic in the .wallaby folder. In any case my main concern is to prevent wallabyjs to stop inadvertently.

In this case you may create the `key.lic` file in the `.wallaby` folder and just paste you license key into it. Wallaby will be activated and will not stop anymore.

**Comment by kavumbi** [comment]
After manually creating the license file everything is fine now. I am still curious though why I didn't get the prompt. Also wallabyjs appears twice in Visual Studio 20017 extension online search. Just in case you want to look into that.

**Comment by ArtemGovorov** [comment]
>  I am still curious though why I didn't get the prompt.

It is indeed interesting, we haven't heard about such issue. The prompt doesn't show up when you open an empty IDE, however if you open an existing solution/project then it should show up. Could you please share the full version of your VS and your OS, we'll try to test it there.

> Also wallabyjs appears twice in Visual Studio 20017 extension online search. Just in case you want to look into that.

Thanks for the note, we'll look int it too.

**Comment by kavumbi** [comment]
I am using Visual Studio Enterprise version 15.4.1 under Windows 10 version 1607, OS Build: 14393.1770. My solution has 60 projects of which 1 is an MVC project whose tests are located in a separate project. If you need more information, let me know. Unfortunately I am not in position to share the wallaby file.
