### ISSUE TITLE
Phantomjs 2.0

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#137]
I just wanted to see what the plans are for this.  Phantomjs 2.0 is much more standards compliant, with respect to ES5 ([weird](https://github.com/wallabyjs/public/issues/33) [parsing](https://github.com/wallabyjs/public/issues/136) bugs and [other issues](https://github.com/wallabyjs/wallaby-react-component/blob/master/test/phantomPolyfill.js) are cleaned up).

As an experiment, I tried building phantomjs 2.0 (linux, debian), and simply replacing the binary under ~/.WebStorm10/system/wallaby/phantomjs_v1.9.8.  After updating the `phantom` module under ~/.WebStorm10/system/wallaby/wallaby/node_modules to 0.7.x, it worked. The only thing that didn't was the line numbers when something threw an exception (obviously had a secondary effect in that I only got a "light red" indicator for the test, and no "deep red" for the failing line).  

Appreciate it may be difficult to have this as a default until official binaries are available for all platforms, but as an option "for those willing to build it themselves/on mac or windows" it seems like a nice step forward. No idea obviously what causes the line number information to be lost, and whether that's something inherent in the upgrade, or just a tiny glitch that can be fixed.

Thanks again - this is changing how I'm working :+1:

**Comment by ArtemGovorov** [comment]
I have got some good news - just today we have started working on supporting PhantomJs 2. Will let you know once it's ready, shouldn't take too long.

**Comment by ArtemGovorov** [comment]
Done https://github.com/wallabyjs/public#phantomjs-2. 
Thanks for your hint about the line numbers! I would have missed it, as it works on OSX (but apparently not on Windows and Linux).

**Comment by bruderstein** [comment]
Thank you! Awesome, works with the line numbers now too. And it fixes the unexpected-dom parse error (even though I'm switching to env:type:node, still nice to know it works).

Amazing timing/work/both :)

**Comment by ArtemGovorov** [comment]
@bruderstein Awesome, thanks!
