### ISSUE TITLE
Less problems when webpacking in our tests

### ISSUE THREAD

**Issue by chris-heathwood-mood** [wallabyjs/public#1370]
Less problems when webpacking in our tests

### Issue description or question
When we add our less files to the configuration and they are then webpacked
it seems that the less loaders are ignored and we then get these errors:

`​​ModuleParseError: Module parse failed: C:\Users\chris.heathwood\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.64\projects\af2b91e284fa285c\instrumented\xxxxxx.less Unexpected character '@' (1:0)​​
​​You may need an appropriate loader to handle this file type.​​`

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require("wallaby-webpack");
const webpack = require("webpack");
const webpackConfig = require("./webpack.config.development");

const wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
    return {
        name: "integration",
        files: [
            { pattern: "packages/**/src/**/*.js", load: false },
            { pattern: "packages/**/src/**/*.less", instrument: false, load: false },
        ],
        tests: [
            { pattern: "tests/specs/**/*.tests.js", load: false },
        ],
        env: {
            kind: "chrome",
        },
        testFramework: "jasmine",
        compilers: {
            "**/*.js": wallaby.compilers.babel({ babel: require("babel-core") }),
        },
        postprocessor: wallabyPostprocessor,
        bootstrap: () => {
            window.__moduleBundler.loadTests();
        },
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

Windows

Any help much appreciated as I need our CSS to be there for our "integration" tests so nooping them is not an option.

**Comment by ArtemGovorov** [comment]
It does indeed look like your LESS loader is not applied for some reason. Could you please share your `./webpack.config.development` (and any other webpack files that it depends on)? I have a suspicion that the `./webpack.config.development` file is not (or conditionally) configuring LESS loader.

**Comment by ArtemGovorov** [comment]
I was going to set up an example repo, but have noticed you've put together [this repo](https://github.com/chris-heathwood-mood/wallaby-less), where everything is working as expected.

It means that this:

```javascript
const webpackConfig = require("./webpack.config.development");
```
most likely doesn't return a webpack config with less loaders.
Try logging it to see the output in the Wallaby Console output channel in VS Code:
```javascript
const webpackConfig = require("./webpack.config.development");
console.log('webpack config', webpackConfig);
console.log('webpack config rules', webpackConfig.module.rules);
```

**Comment by chris-heathwood-mood** [comment]
Yeah I was going to ping it across but indeed it works fine in the example repo I'll get some logging out of ours and see what I can find, thanks for the help!

**Comment by chris-heathwood-mood** [comment]
The less loader is in the webpack config rules when I add in the console logs:

```
[
  { test: /\.js$/, loader: [ 'babel-loader' ], exclude: /node_modules/ },
  { test: /\.less$/, use: [ [Object], [Object], [Object] ] }
  { test: /\.json$/, use: [ [Object] ] },
  { test: /\.css$/, use: [ [Object], [Object] ] },
  { test: /(\.webm|\.mp4|\.m4v|\.ogv)$/, use: [ [Object] ] },
  { test: /\.(jpe?g|png|gif|svg)$/, use: [ [Object], [Object] ] },
  { test: /\.(eot|svg|ttf|woff|woff2)$/, use: [ [Object] ] } ]
```

I've tried a few different things and running the config with:

```
        workers: {
            initial: 1,
            regular: 1,
            recycle: true,
        },
```

It works fine, I'll see if I can reproduce this on the test repo but have a feeling it could be the size of the code base making a difference.

**Comment by ArtemGovorov** [comment]
> I've tried a few different things and running the config with:

```
        workers: {
            initial: 1,
            regular: 1,
            recycle: true,
        },
```

Hm, I'm surprised. This is very strange. The originally reported error seems to be build stage specific (thrown by webpack during build). The `workers` setting only affects runtime stage (controls the number of parallel test worker instances for running your tests). So I'm a bit puzzled as to how using the setting may affect the build error.

Could you please share the full stack trace of the error, as well as the error .less file location (relatively to the project's root)?

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please try the steps listed above, or/and create a sample repo demonstrating the issue - we are happy to have a look into it.
