### ISSUE TITLE
VS Code extension crashes on git branch change

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1371]
### Issue description or question

Switching a branch on the command-line with `git checkout` crashes the Wallaby.js runner with the following error in Output > `Wallaby.js Tests`:

```
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Error: ENOENT: no such file or directory, open '.\package.json'​​
​​    at Object.fs.openSync (fs.js:648:18)​​
​​    at Object.fs.readFileSync (fs.js:553:33)​​
​​    at Object.Module._extensions..json (module.js:629:20)​​
​​    at Module.load (module.js:531:32)​​
​​    at tryModuleLoad (module.js:494:12)​​
​​    at Function.Module._load (module.js:486:3)​​
​​    at Module.require (module.js:556:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at emitTwo (events.js:125:13)​​
​​    at WebSocket.emit (events.js:213:7)​​
​​    at afterWrite (_stream_writable.js:454:3)​​
​​    at onwrite (_stream_writable.js:445:7)​​
​​    at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​    at Zlib.callback (zlib.js:515:5)​​
```

### Wallaby.js configuration file

```javascript
const path = require("path");

module.exports = (wallaby) => ({
	compilers: {
		"**/*.ts?(x)": wallaby.compilers.typeScript({
			compilerOptions: {
				target: "es3",
			},
		}),
	},

	env: {
		type: "node",
	},

	files: [
		"package.json",
		"src/**/*.ts",
		"!src/**/*.test.ts",
		"src/**/*.tsx",
		"!src/**/*.test.tsx",
	],

	preprocessors: {
		"**/*.css": () => ({}),
	},

	setup: () => {
		const jestConfig = require("./package.json").jest;
		const cssMockFile = require("path").join(wallaby.localProjectDir, "test/jestCssPreprocessor.js");

		jestConfig.moduleNameMapper[".*\.css$"] = cssMockFile;

		wallaby.testFramework.configure(jestConfig);
	},

	testFramework: "jest",

	tests: [
		"src/**/*.test.ts",
		"src/**/*.test.tsx",
	],
});
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

Windows 10 and Windows Server 2016

**Comment by ArtemGovorov** [comment]
I have created this repo trying to reproduce the issue: https://github.com/ArtemGovorov/wallaby-1371, but when I switch between the `master` and `test` branch, everything is working as expected. Could you please have a look if the repo is working for you?

Anyway, looks like the issue occurs when executing you `setup` function, perhaps because git didn't re-create the `package.json` file yet, however paused for longed enough for wallaby to trigger the test run.

There's a easy way to verify the assumption. Wallaby [supports async start](https://wallabyjs.com/docs/config/bootstrap.html) with the `delayStart`/`start` functions, so you may try re-trying to do start the test run right in your setup function, like this:

```javascript
  setup: wallaby => {
    const initializer = () => {
      const jestConfig = require("./package.json").jest;
      const cssMockFile = require("path").join(wallaby.localProjectDir, "test/jestCssPreprocessor.js");

      jestConfig.moduleNameMapper[".*\.css$"] = cssMockFile;

      wallaby.testFramework.configure(jestConfig);
    };

    try {
      initializer();
    }
    catch (e) {
      console.warn('Retrying test initialization');
      wallaby.delayStart();
      setTimeout(() => {
        initializer();
        wallaby.start();
      }, 500);
    }
  },
```

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please try the steps listed above, or/and create a sample repo demonstrating the issue - we are happy to have a look into it.
