### ISSUE TITLE
Can I use jest mock hoisting in TypeScript test cases?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#1373]
### Issue description or question
I could see babel configuraiton for babel-preset-jest in https://github.com/wallabyjs/public/issues/872, is there way to configure similar when test case is written in TypeScript and using TS compiler in wallaby configuration? For CLI jest runner I'm using ts-jest (https://github.com/kulshekhar/ts-jest) which does re-transpiles using babel once again to hoist mocks, not sure same approach could be applicable.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by kwonoj** [comment]
For current wallaby config, I came to realize I've shared several time already 😅 it's here: https://github.com/wallabyjs/public/issues/1366#issuecomment-339555316

**Comment by ArtemGovorov** [comment]
> I'm using ts-jest (https://github.com/kulshekhar/ts-jest) which does re-transpiles using babel once again to hoist mocks, not sure same approach could be applicable.

Yep, the same approach is used by Wallaby, you may [configure Babel preprocessor to process TS compilation results](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel):

```javascript
  module.exports = function (w) {

    return {
      files: [
        ...
      ],

      tests: [
        ...
      ],

      ...

      preprocessors: {
        '**/*.js?(x)': file => require('babel-core').transform(
          file.content,
          {sourceMap: true, filename: file.path, presets: ['babel-preset-jest']})
      }
    };
  };
```

**Comment by kwonoj** [comment]
Super appreciate as always, let me try it on my end!
