### ISSUE TITLE
[Atom] Move pane to sidebar

### ISSUE THREAD

**Issue by wldcordeiro** [wallabyjs/public#1377]
### Issue description or question
It'd be nice to see the Wallaby pane use the built-in panes for its tooling. I think the right sidebar in particular would be a good home (think if it were next to "Outline" in my screenshot below)

<img width="301" alt="screen shot 2017-11-07 at 1 02 01 pm" src="https://user-images.githubusercontent.com/580982/32515048-0975abbc-c3bc-11e7-82a7-9539b59c85eb.png">

### Code editor or IDE name and version

Atom v1.23.beta3

**Comment by smcenlly** [comment]
We no longer support Atom as it has reached end of life: https://github.blog/2022-06-08-sunsetting-atom/
