### ISSUE TITLE
Clean cache button

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1379]
Would be great to have a button to clear the cache. Sometimes you may get into a weird state if you are tweaking config, changing babel config, or something.

Currently you have to copy the dir from the log and `rm -rf`. A minor inconvenience.

**Comment by ArtemGovorov** [comment]
While I'm not opposed to the idea of having the button, ideally you should never need to clear the cache manually. We are cleaning it automatically based on certain triggers. For example, 

> tweaking config

and 

> changing babel config

(and a few other actions - like changing `package.json` file) are causing cache cleaning automatically.

Are there any other scenarios where you find that cleaning the cache is necessary?

**Comment by vjpr** [comment]
What if I have a nested 'package.json` file in a monorepo, or a `.babelrc` file which has a local `require` for a preset. I don't know how the cleaning logic works, but I think there are endless edge cases.

**Comment by ArtemGovorov** [comment]
In these cases we normally suggest to "touch" wallaby config (even adding space anywhere in it will do). Doing it plus restarting wallaby cleans the cache.

**Comment by vjpr** [comment]
This doesn't seem to work for me:

I always see this:

```
Sun, 10 Dec 2017 19:13:47 GMT wallaby:project File cache is up-to-date, starting full test run
```

Also, I store my wallaby config in `tools/wallaby/index.js` and require it like so: `module.exports = require('./tools/wallaby/index')`. Touching wouldn't work in this case...

**Comment by ArtemGovorov** [comment]
Root wallaby config file has to be touched. The one with `module.exports = require('./tools/wallaby/index')` code in your case.

**Comment by vjpr** [comment]
This is annoying. My config requires its config in another file deep in my project, and I find myself constantly having to open up the root file, press enter a few times, then press play.

**Comment by smcenlly** [comment]
If you include your nested config file in your wallaby configuration `files` list, does that fix your problem?

Besides the Wallaby configuration, are you having other issues that are forcing you to reset the cache? If you can provide us with details of the issue and steps to reproduce, we'd be happy to investigate further.

**Comment by kvernon** [comment]
I am at this point today. 

I have a nrwl/nx project, and I renamed a library (utils to utils-sdk). I went through all the path references (typescript / jest / nx / workspace), and I run all the tests with the cli. When I try to run wallabyjs auto config, it still thinks the folder is at the old location (prior to rename), and I can't shake it / refresh it. I've opened and closed webstorm. I even told webstorm to release the cache and restart. nothing.

This is what I get:

The project's path (references + naming) was updated to: `./libs/utils-sdk` and `utils-sdk` respectively.

```
Automatic Angular CLI configuration error: None of your projects are configured with `@angular-devkit/build-angular:karma`, `@angular-builders/jest:run`, or `@nrwl/jest:jest` builders as their test architect.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Failed to read Jest configuration from '.': Can't find a root directory while resolving a config file path.
Provided path to resolve: ./libs/utils
cwd: .


```

**Comment by andrew-knack** [comment]
@ArtemGovorov Any particular reason why you won't implement this? Currently I'm getting a `Some long running code has been detected` for a test that no longer exists so I'm assuming it's a caching issue. 

I'm using automatic configuration in a monorepo and touching the babelrc or jest config anywhere doesn't clear it. As @vjpr said there are endless edge cases and having to work out what to delete from the logs is just annoying.

**Comment by smcenlly** [comment]
@andrew-knack - The reason that we have not added this feature to date is that it **shouldn't** be necessary. If there is a caching issue, then from our perspective, it is a bug. Even if it's not caused by Wallaby (e.g. caused by Jest, etc.) then we want to detect this automatically and fix it.

Our concern has been that if we add a command to do this, it will lead to a decrease in Wallaby quality. Are you able to readily reproduce the problem? We would appreciate it if you could [create a new issue](https://github.com/wallabyjs/public/issues/new/choose) and provide us with your diagnostic report when you next see it.

> I'm using automatic configuration in a monorepo and touching the babelrc or jest config anywhere doesn't clear it.

If you are using automatic configuration, you will need to touch `package.json`.

---

Having said all that, we would be happy to add the feature for Wallaby for VS Code and JetBrains Editors; can you tell us which editor you're using? We'll prioritise adding for that one first.

**Comment by andrew-knack** [comment]
> If you are using automatic configuration, you will need to touch package.json.

Thanks for the tip, you might want to add it to the [troubleshooting section](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working). 

> Our concern has been that if we add a command to do this, it will lead to a decrease in Wallaby quality. Are you able to readily reproduce the problem? 

I can't reproduce the problem I had an infinite loop in one of my tests, stopped wallaby and commented out the test. Checked that it wasn't stuck in an infinite loop by running it in jest directly and then restarted wallaby. On starting wallaby again the core updated and that's what I think broke it. Manually deleting the cache and restarting wallaby got it working again.

I think it speaks to `vjpr` point overall that you're just not going to account for every edge case. I use VS Code but I wouldn't put a rush on it. In 2017 when I [started using wallaby](https://github.com/wallabyjs/public/issues/1101#issuecomment-332199122) it used to happen every other day. Now months go by without having to manually delete the cache so it's definitely much better.
