### ISSUE TITLE
Issue with latest beta of jest

### ISSUE THREAD

**Issue by asvetliakov** [wallabyjs/public#1381]
### Issue description or question
I'm running jest 21.3.0-beta.8. All is fine except when i'm trying to run wallaby i'm receiving failing snapshots similar to this:
![wallaby](https://user-images.githubusercontent.com/8881674/32575882-8de7ac64-c4d5-11e7-8673-2441ed9e234d.png)

Does the wallaby use different version of jest?

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = "test";

const babelConf = require("./.babelrc");
babelConf.plugins.push("jest-hoist");

module.exports = function (wallaby) {
    return {
        files: [
            "src/**/*.snap",
            "src/**/*.ts?(x)",
            "!src/**/*_Spec.ts?(x)",
            "!src/**/*.d.ts",
            "package.json",
            "tsconfig.json",
            "helpers/**.js",
            { pattern: 'src/**/*.css', load: false, instrument: false },
            { pattern: 'src/**/*.png', load: false, instrument: false },
            { pattern: 'src/**/*.jpg', load: false, instrument: false },
            { pattern: 'src/**/*.mp3', load: false, instrument: false },
            { pattern: 'src/**/*.ogg', load: false, instrument: false },
            { pattern: 'src/**/*.svg', load: false, instrument: false }
        ],
        tests: [
            "src/**/*_Spec.ts?(x)"
        ],
        env: {
            type: "node",
            runner: "node"
        },
        hints: {
            ignoreCoverage: /istanbul ignore.*/
        },
        reportConsoleErrorAsError: true,
        compilers: {
            "**/*.ts?(x)": wallaby.compilers.babel({
                ...babelConf,
                babel: require("@babel/core")
            })
        },
        testFramework: "jest",
        setup: function () {
            const jestConfig = require("./package.json").jest;
            jestConfig.transform = {
                "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|ogg)$": "<rootDir>/node_modules/@ramble/helpers/jest/assetsFileTransformer.js"
            };
            wallaby.testFramework.configure(jestConfig);
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.18-insiders

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
There may be some breaking changes in the latest Jest beta. However, when I run a simple snapshot test, everything is working as expected, so we'll need your help to reproduce it.

Could you please update your [repo from the previous issue](https://github.com/ArtemGovorov/wallaby-1379) with an example of this behaviour? I'll take a look as soon as possible.

**Comment by asvetliakov** [comment]
Sure, will try to get repro soon

**Comment by ArtemGovorov** [comment]
Just realised that I didn't answer your question:

> Does the wallaby use different version of jest?

Nope, wallaby is using the installed Jest version. From the error it looks like perhaps component functions had not been mocked, so perhaps the issue has something to do with mocking.

**Comment by ArtemGovorov** [comment]
Investigated a bit and it looks like `MockFunction` was introduced recently in `jest-snapshot` package. Try searching your `node_modules` to make sure you don't have any old (< v21.3.0-beta.8) versions of `jest-snapshot` installed anywhere in the tree.

**Comment by asvetliakov** [comment]
@ArtemGovorov Thanks! Looks like different version of jest-snapshots are causing this:

```
asvetl ~/work/applications/frontend/node_modules $ find . -name "jest-snapshot" -type d
./jest/node_modules/jest-snapshot
./jest-runner/node_modules/jest-snapshot
./jest-runtime/node_modules/jest-snapshot
./jest-snapshot
```
Also can't reproduce with simple repo from previous issue. Perhaps the native jest CLI uses top-level jest-snapshot package, but wallaby may be using ```jest-runtime``` package which includes own version of ```jest-snapshots``` (in my case) ?

I'll try to recreate my node_modules

**Comment by ArtemGovorov** [comment]
> Perhaps the native jest CLI uses top-level jest-snapshot package, but wallaby may be using jest-runtime package which includes own version of jest-snapshots (in my case) ?

It is possible. What versions do these package have:

```
./jest/node_modules/jest-snapshot
./jest-runner/node_modules/jest-snapshot
./jest-runtime/node_modules/jest-snapshot
./jest-snapshot
```

Looks like another Jest version (older one) is installed in your node_modules (or some packages from another Jest version).

> I'll try to recreate my node_modules

May work, try deleting your package-lock/yarn.lock file and re-installing modules.

**Comment by asvetliakov** [comment]
Exactly this was causing this. After deleting package-lock.json and re-installing node_modules it's working as should. Perhaps it was caused by some bad npm update/install. Thanks again for your help and guidance! 💯

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
