### ISSUE TITLE
Making a purchase order on the site defaults to German localization

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1382]
I'm in `en-us` personally.

![wallaby localization 2](https://user-images.githubusercontent.com/3335181/32632626-2d0e46f8-c559-11e7-84bf-aee2fcc1e0a4.PNG)
![wallaby localization](https://user-images.githubusercontent.com/3335181/32632627-2d1ef5c0-c559-11e7-8d6d-64c2595fdf76.PNG)

**Comment by ArtemGovorov** [comment]
Thanks for the report! The checkout form is hosted by our payment solution provider (Paddle), I'll raise the issue with them. Though everything is working for us as expected here (English is set by default).

One thing that happens sometimes - perhaps you've accidentally clicked the language selection button (bottom right corner of the screen during the checkout)? Easy way to check is open the https://wallabyjs.com/purchase/ page in a new Incognito Window (no cookies, etc) and check what happens.

**Comment by JoshuaKGoldberg** [comment]
Ehh, I tried again incognito and didn't click any unnecessary buttons.

Chrome 61.0.3163.100
Windows 10

**Comment by ArtemGovorov** [comment]
Wow, interesting. Thanks for checking! I'll pass the data to Paddle (we have no control over the checkout code where the issue seems to show up).

**Comment by ArtemGovorov** [comment]
@JoshuaKGoldberg Could you please check your language preferences in your Chrome settings (under the Advanced button):

![screen shot 2017-11-10 at 9 22 23 am](https://user-images.githubusercontent.com/979966/32634734-bd865d48-c5f8-11e7-94c4-574e176db997.png)

Any chance `German` is the first language in the list there?

**Comment by JoshuaKGoldberg** [comment]
It's second.

![image](https://user-images.githubusercontent.com/3335181/32635134-cf04e516-c563-11e7-85d0-6521ab96e8f0.png)

**Comment by ArtemGovorov** [comment]
Could you please try to move `English` to be above `English (United States)`?

**Comment by JoshuaKGoldberg** [comment]
`English` isn't selectable as the display language. But, when I move it to the top, it does fix the issue!

![image](https://user-images.githubusercontent.com/3335181/32635714-4d084f6e-c566-11e7-805f-9d4755e90cc6.png)
![image](https://user-images.githubusercontent.com/3335181/32635761-71c5680a-c566-11e7-95af-e72eefd91264.png)

**Comment by pt3bbs** [comment]
Hey Josh,
Sorry you're having issues  here. Could I ask you to please try opening the checkout in an incognito window now that you have English above English (US) in your Chrome preferences?
If that doesn't work then I need to ask one of our Engineers to look into it on Monday.
Best
Paul

**Comment by JoshuaKGoldberg** [comment]
That worka! It's in English again.

**Comment by pt3bbs** [comment]
Sweet! 🙌
