### ISSUE TITLE
feature request: show loading indicator in web panel

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1388]
## Use Case

Zen mode in VS Code. It would be nice to know the status of your test re-running in the web panel so you don't need to have the VS Code blue footer bar showing to tell you. 

It also might make for an opportunity to make a larger more easily noticeable loading indicator.

**Comment by ArtemGovorov** [comment]
Good point, thanks for providing the use case! Should be easy to add the indicator.

**Comment by NikGovorov** [comment]
HI @faceyspacey,

Thanks for the feedback. We implemented loading indicator in Wallaby.js App v1.0.53, Core v1.0.671.

**Comment by faceyspacey** [comment]
Awesome, great work!!!
