### ISSUE TITLE
Missing tracer start subscription

### ISSUE THREAD

**Issue by chastel** [wallabyjs/public#1391]
### Issue description or question

I am looking if wallaby.js is something for our team, but I can't get it work properly.

When I want to run the defined wallaby run-configuration in WebStorm, I get the error 
```
Runtime error: Error: Missing tracer start subscription at http://localhost:58625/__wallaby__/tracer.js:14
```

But when I just click on a specific test, wallaby can run it and gives me the results.

I installed wallaby according the "JetBrains IDEs tutorial".

**The part in the logs**
```
Tue, 14 Nov 2017 14:46:40 GMT wallaby:middleware Serving /test/list.test.js from cache
Runtime error: Error: Missing tracer start subscription
at http://localhost:58625/__wallaby__/tracer.js:14
Runtime error: Error: Missing tracer start subscription
Tue, 14 Nov 2017 14:46:40 GMT wallaby:workers Sandbox (active) [byu5b] error: Error: Missing tracer start subscription
Tue, 14 Nov 2017 14:46:40 GMT wallaby:workers Failed to map the stack to user code, entry message: Error: Missing tracer start subscription, stack: Error: Missing tracer start subscription
at http://localhost:58625/__wallaby__/tracer.js:14
Tue, 14 Nov 2017 14:46:40 GMT wallaby:workers Sandbox (active) [byu5b] error: Error: Missing tracer start subscription
Tue, 14 Nov 2017 14:46:40 GMT wallaby:workers Failed to map the stack to user code, entry message: Error: Missing tracer start subscription, stack: http://localhost:58625/__wallaby__/tracer.js:14
:1
:1
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.ts'
        ],

        tests: [
            'test/**/*.ts'
        ],
        testFramework: 'mocha',
        debug: true
    };
};
```

### Code editor or IDE name and version

WebStorm v2017.2.5

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
The config doesn't look complete.

Could you please share some more details about the code you're testing?

- if it it browser app and you are using TypeScript with ES modules (import/export), then you are probably using webpack and then need to look into [this docs section](https://wallabyjs.com/docs/integration/webpack.html).
- if if is node app, then you're missing [the `env: {type: 'node'}` setting](https://wallabyjs.com/docs/integration/node.html).

**Comment by bbugh** [comment]
I arrived here with the same issue (except with Jest), using this configuration: https://wallabyjs.com/docs/integration/typescript.html 

I'm using a really simple rollup + typescript setup (no babel, webpack, etc.).

I believe it has to do with my `tsconfig.json` using `"module": "es6"` instead of `commonjs`.  [This comment](https://github.com/wallabyjs/public/issues/1910#issuecomment-437136358) for a separate issue got me to the right answer: 

```javascript
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
```

I also had to specify the env type as @ArtemGovorov mentioned above:

```javascript
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
```

<details>
<summary>Details on the complete wallaby.config.js</summary>

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.ts',
    ],

    tests: [
      'test/**/*.test.ts'
    ],

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```
</details>
