### ISSUE TITLE
File has different size than original

### ISSUE THREAD

**Issue by Knaackee** [wallabyjs/public#1394]
I have included a binary file (a zip file with a different extension) to the files section of the wallaby.js config file.

For some reason, the file copied to the 
projects/../instrumented​​​​​ folder has a different size than the original file. 

I noticed that because the test failed with "node-zip" throwing an error saying the file is corrupt.

### Original
![screen shot 2017-11-16 at 16 23 16](https://user-images.githubusercontent.com/880759/32899493-6e010d84-caeb-11e7-9cdc-97eadb45539d.png)

### Copied
![screen shot 2017-11-16 at 16 22 36](https://user-images.githubusercontent.com/880759/32899508-7a1d33cc-caeb-11e7-9649-2f2358b4484c.png)

## Update 
I did a diff in terminal.

```
diff test.c*** ~/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.66/projects/22fb5c81164e2d7c/instrumented/src/backend/tests/test.c***
Binary files test.c*** and /Users/***/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.66/projects/22fb5c81164e2d7c/instrumented/src/backend/tests/test.c*** differ

```

### Code editor or IDE name and version

Visual Studio Code v1.19.0-insider  

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
You may add the `binary: true` flag to the file/pattern:

```javascript
  files: [
    ...
    {pattern: 'src/**/test.c*', instrument: false, binary: true}
  ]
```

If it is a well known binary extension, let us know the file extension name and we'll whitelist it (like we are doing for `.zip` and other known binary extensions), so that wallaby automatically adds the flag.

**Comment by Knaackee** [comment]
Awesome, thank you! I did not found the "binary" flag in the docs.

**Comment by ArtemGovorov** [comment]
@Knaackee Thanks for the note, [added the flag description to the docs](https://wallabyjs.com/docs/config/files.html#binary).
