### ISSUE TITLE
Feature request: Show currently selected configuration file path

### ISSUE THREAD

**Issue by fdeslandes-wk** [wallabyjs/public#1396]
### Issue description or question

Working with the new workspaces in VSCode, I often have to switch between wallaby configurations for the different projects in my workspace.  Often, I don't remember which was the last wallaby config I loaded, go to select configuration file and don't find the configuration I want, only to realise it must already be the current one.

I would like to be able to know which configuration file is currently selected by wallaby, either in the status bar, the wallaby menu or wherever you think should be the best place to read this information in the IDE.

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the feature request. It is implemented in v1.0.67. Now when you invoke the select configuration file command, currently selected configuration file is displayed in the selector placeholder:

![vsccs](https://user-images.githubusercontent.com/979966/33001621-bc547072-cdfa-11e7-8bb0-bf80f242adb0.gif)
