### ISSUE TITLE
Wallaby doesn't show tiles (green/red) next to line numbers in webstorm

### ISSUE THREAD

**Issue by einav7** [wallabyjs/public#1397]
### Issue description or question
Wallaby doesn't show tiles (green/red) next to line numbers in webstorm, 
the console shows tests have passed.
(I have upgraded typescript to 2.5.3 lately but not sure it's related)

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm 2017.1.4
Build #WS-171.4694.29, built on June 7, 2017
Licensed to WebStorm Evaluator
Expiration date: November 22, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
- Could you please attach a screenshot of a test file while Wallaby is running?
- Could you clone [this sample project](https://github.com/wallabyjs/calculator-sample), and run Wallaby to see if it displays coverage indicators when you run it on this project?
- Does Wallaby show inline messages (errors) for you?
- Did you recently update WebStorm or change any IDE settings?

**Comment by ArtemGovorov** [comment]
Also could you please 
- download the [latest version of Webstorm](https://www.jetbrains.com/webstorm/download/#section=mac), 
- install it it side-by-side with your existing version, 
- when prompted, select NOT to import your existing version settings,
- install Wallaby for the latest WS version and try to run it.

**Comment by einav7** [comment]
Thanks for the quick response!
I noticed that changes in the files doesn't trigger the tests to run if that helps to understand the issue.
in the sample project it's working!
I'd rather not paste screenshots of the code but I can say there's no indicators of wallaby on the file itself while the tests are running in the wallaby console.
No errors are showing at all
no recent IDE updates

**Comment by ArtemGovorov** [comment]
> I noticed that changes in the files doesn't trigger the tests to run if that helps to understand the issue.

> in the sample project it's working!

> there's no indicators of wallaby on the file itself while the tests are running in the wallaby console.

All these points mean that the issue is in your config. Most likely your tests are running code not from wallaby cache (with instrumented project files, but from your local project). Please share your wallaby config, and one of the file names where indicators are not displayed. Or send these details to hello@wallabyjs.com and we'll take it from there.

**Comment by einav7** [comment]
I will send the details,
Thank you!
