### ISSUE TITLE
VS Code ​​Failed to parse .babelrc

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1398]
### Issue description or question
When running Wallaby with ``.babelrc`` that points to ``.babelrc.js`` as a preset, the following error is thrown in VS Code (works as expected with Webstorm and untested with other editors):

```js
[Error] ​​Failed to parse .babelrc, SyntaxError: Unexpected token (2:13)​​
[Error] ​​  at emitTwo (events.js:126:13)​​
[Error] ​​  at process.emit (events.js:214:7)​​
[Error] ​​  at emit (internal/child_process.js:772:12)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:141:11)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
```

.babelrc:
```js
{
    "presets": ["./.babelrc.js"]
}
```

.babelrc.js:
```js
'use strict';

const babel = {
    presets: [
        [
            'env',
            {
                targets: {
                    node: 'current',
                },
            },
        ],
    ],
};

module.exports = babel;
```

Example: [chrisblossom/wallaby-issue-1398](https://github.com/chrisblossom/wallaby-issue-1398)

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            {
                pattern: 'src/**/__sandbox__/**/*',
                instrument: false,
            },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            '.babelrc',
            '.babelrc.js',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],
        tests: [
            'src/**/*.test.js',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: w => {
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            jestConfig.transform = { '__sandbox__.+\\.jsx?$': 'babel-jest' };
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version
``Visual Studio Code v1.18.1``

### OS name and version
``OSX 10.13.1``

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo!

The easiest solution is just to remove '.babelrc' and '.babelrc.js' file from the `files` list. Doesn't see like you need these files in your Wallaby cache anyway.

If you need the files in the list, then you may turn off the .babelrc file instrumentation:

```javascript
        files: [
            ...
            { pattern: '.babelrc', instrument: false },
            ...
        ],
```

**Comment by chrisblossom** [comment]
Webstorm's Wallaby runner failed after removing ``.babelrc`` and ``.babelrc.js``. They both seem to work with ``{ pattern: '.babelrc', instrument: false }, { pattern: '.babelrc.js', instrument: false }``. Is this a bad idea? Or is there a better option?

**Comment by ArtemGovorov** [comment]
It's not a bad idea, I don't see anything wrong with having:

```javascript
{ pattern: '.babelrc', instrument: false }, 
{ pattern: '.babelrc.js', instrument: false }
```
or even
```javascript
{ pattern: '.babelrc+(.js|)', instrument: false },
```

Though it's a bit strange that Webstorm's Wallaby runner failed after removing those. I have tried the sample project in WS without those files, and it's working.

**Comment by chrisblossom** [comment]
It is with a current private repo where I've been getting these new issues with when trying to load up wallaby with VS Code.
