### ISSUE TITLE
VS Code ignores .hidden dotfiles

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1399]
### Issue description or question
VS Code's file regex ignores hidden dotfiles with the following pattern: ``'src/**/__sandbox__/**/*'``. This works as expected in Webstorm and untested in other editors.

Example: [chrisblossom/wallaby-issue-1399](https://github.com/chrisblossom/wallaby-issue-1399)

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            {
                pattern: 'src/**/__sandbox__/**/*',
                instrument: false,
            },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: w => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            jestConfig.transform = { '__sandbox__.+\\.jsx?$': 'babel-jest' };
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

``Visual Studio Code v1.18.1``

### OS name and version

``OSX 10.13.1``

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo! As usually, it is very helpful.

It's a known issue with glob/minimatch, by default glob/minimatch `*` doesn't include dotfiles:

```javascript
require('minimatch')('src/__sandbox__/.test_file', 'src/**/__sandbox__/**/*') //? false
```

The easiest solution is to use the following pattern specifically for dotfiles:

```
pattern: 'src/**/__sandbox__/**/.*',
```

I have sent you [this pull request](https://github.com/chrisblossom/wallaby-issue-1399/pull/1/files) with the change.

Webstorm is using a different (Java) implementation of glob and looks `*` includes dotfiles in that implementation.

**Comment by chrisblossom** [comment]
Wouldn't it be better to set ``dot: true`` with glob/minimatch for the VS Code implementation? 

https://github.com/isaacs/minimatch#dot

**Comment by ArtemGovorov** [comment]
We have considered the option, but because it is not an option set by default, setting it now for everyone may be a breaking change for some configs.

**Comment by vjpr** [comment]
@ArtemGovorov I ran into a similar issue. Just to clarify: there is no way to set `dot: true`? 

What about something like:

```
{pattern: 'packages/**/*.js', globConfig: {dot: true}}
```

Without it I have to create multiple entries for every dir that may contain dots for `files` and `compilers`.

**Comment by ArtemGovorov** [comment]
@vjpr 
> there is no way to set `dot: true`

Correct, right now there's no way to do it. There may also be an issue with the Java `minimatch` port (used in JetBrains IDEs integration) that may not support the `dot` option at all. We'll investigate some options.
