### ISSUE TITLE
Postprocessor run failure: failed to parse file

### ISSUE THREAD

**Issue by Pompeoar** [wallabyjs/public#1400]
### Issue description or question
Loading wallaby back up for the first time in a while. I keep getting the same output error:
[Error] ​​Postprocessor run failure: Failed to parse src/environments/environment.azuredev.js, SyntaxError: Unexpected token (255:1)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:73:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:104:9)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:73:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:104:9)​​

I've commented out the environment file, and it works, but then I change a test and the whole thing fails again with the same error. Npm test works fine. 

### Wallaby.js configuration file

```
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine', 

    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript(compilerOptions)  
    },
    
    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron' 
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```
### Code editor or IDE name and version
Visual Studio Code v1.18.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
> Postprocessor run failure: Failed to parse src/environments/environment.azuredev.js, SyntaxError: Unexpected token (255:1)​​

Could you please share the file content? If you cannot share it, try commenting a half of it to see if the error is still showing up, etc. to find out what code is causing the issue and let us know.

Also, please share your `./tsconfig.json` and `./src/tsconfig.spec.json` files.

> I've commented out the environment file, and it works, but then I change a test and the whole thing fails again with the same error. 

With the same error for a different file? Could you please perform the steps suggested above for that file as well (either share the file or try to find out what code/statement/expression is causing the issue)?

**Comment by Pompeoar** [comment]
Commenting out the file completely lets it run. Once. Then I alter any test and it fails with the same error (for the same file). Uncommenting the file again lets it run. Once. Then alter any test and it again fails with the same error (for the same file). 

{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "../CompliancePortal.WebApi/wwwroot/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "types": [
      "hammerjs",
      "jasmine"
    ]
  }
}


{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}

**Comment by ArtemGovorov** [comment]
Thanks for providing more details. 

Any chance you could share the file with us? You may email it to use to hello@wallabyjs.com if you don't feel comfortable sharing it here.

Is the file imported from any other files of your app or required to run unit tests? If not, try excluding it in your `files` list:

```diff
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},
+     {pattern: 'src/environments/environment.azuredev.ts', ignore: true}
    ],
```

**Comment by Pompeoar** [comment]
That fixed it! I altered some tests and it's still working. Seems like a facepalm "why didn't I think of that" solution, but I'll take it - thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

We'd still love to find out the reason why wallaby had issues compiling that file, so if you have a chance, please send us the file.
