### ISSUE TITLE
Setting up Wallaby with Jasmine Testing and Sublime Text 3 Newb question

### ISSUE THREAD

**Issue by etcetera8** [wallabyjs/public#1401]
### Issue description or question
I'm simply trying to get the tests running as I want to present this in a lightening talk to the rest of my class. The only tiles I'm seeing are gray and its not console logging to the ide. I was reading through the docs and went through several tutorials online and followed along with someones yt video but it was for a different framework. I feel like I'm close but am missing just a simple part somewhere?  Thanks in advance and sorry for the newb question but this looks awesome and I'm pining to use it. 

### Wallaby.js configuration file

[link to repo](https://github.com/etcetera8/gigaSecondWallaby)

    function Gigasecond() {

    };

    module.exports = Gigasecond;

// paste your config here

    module.exports = function () {
      return {
    files: [
      'gigasecond.js'
    ],

    tests: [
      'gigasecond.spec.js'
    ],

    env: {
      type: 'node'
    },

    testFramework: 'jasmine'
     };
    };

### Code editor or IDE name and version

Sublime Text v3 3143

### OS name and version

OSX High Sierra
Version 10.13.1

**Comment by ArtemGovorov** [comment]
Wallaby displays information about what went wrong in the [Failing Tests Console](https://wallabyjs.com/docs/intro/get-started-sublime.html#failing-tests) and in [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting).

I think in your case it complains that Jasmine node module is not found. By default wallaby tries to look up Jasmine in your project's node modules, but your project doesn't even have `package.json` file, so it doesn't install Jasmine as a dependency.

You may create a `package.json` file (by running `npm init` in your project folder), and run `npm install jasmine --save-dev`. 

Or, if you have Jasmine installed globally (as I can see from your repo docs, you may have it globally installed), then you may specify the path (by running `npm root -g` to avoid hardcoding your system's global node modules path):

```diff
module.exports = function () {
  return {
    files: [
      'gigasecond.js'
    ],

    tests: [
      'gigasecond.spec.js'
    ],

    env: {
      type: 'node'
    },

-   testFramework: 'jasmine',
+   testFramework: {
+     type: 'jasmine',
+     path: require('path').join(require('child_process').execSync('npm root -g').toString().replace(/\r\n|\r|\n/g, ''), 'jasmine')
+    }
  };
};

```

Please note that we've introduced the feature recently so you most likely need to [update your Wallaby Core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to the latest version.

**Comment by etcetera8** [comment]
Thanks! Installed globally it was.
