### ISSUE TITLE
Lerna with hoisted modules

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1402]
### Issue description or question
Is it possible to use wallaby with Lerna's hoist option? It seems that wallaby might have the resolution algorithm implemented incorrectly? Also, this was working until a day or two ago, did something change? Works as expected without the hoist option, but causes other issues.

https://github.com/lerna/lerna/blob/master/doc/hoist.md
https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders

> [Error] ​​Error: babel, babel-core or @babel/core must be installed locally or babel instance must be passed in opts.babel, for example `wallaby.compilers.babel({ babel: require('babel') })`​​

Example: [chrisblossom/wallaby-issue-1402](https://github.com/chrisblossom/wallaby-issue-1402)

### Code editor or IDE name and version

``Visual Studio Code v1.18.1``
``WebStorm 2017.3 EAP Build #WS-173.3727.2, built on November 13, 2017``

### OS name and version

``OSX 10.13.1``

**Comment by ArtemGovorov** [comment]
It should be possible [with a `NODE_PATH` hint](https://github.com/chrisblossom/wallaby-issue-1402/pull/1).

> It seems that wallaby might have the resolution algorithm implemented incorrectly?

Wallaby resolves certain infrastructure modules (including babel) via absolute paths, so node resolution algorithm doesn't apply. This however is not related to how modules are resolved from your tests/code - node module resolution algorithm is used there.

**Comment by chrisblossom** [comment]
Thanks for looking into this. Is there an alternate solution? This is causing some tests to fail. I think it is breaking Jest's mocking.

**Comment by ArtemGovorov** [comment]
Could you please update the sample repo with an example of a failure? We'll take a look and depending on what's causing the issue we'll either fix it or come up with some suitable working alternative for you.

**Comment by chrisblossom** [comment]
Do you have a gitlab account? I have a private repo I can share there.

**Comment by ArtemGovorov** [comment]
@chrisblossom Thanks! My gitlab handle is @ArtemGovorov

**Comment by chrisblossom** [comment]
Invite sent

**Comment by ArtemGovorov** [comment]
Thanks, I'm not an experienced GitLab user, so may be missing something, but seems like I don't have an access to the source code - can't find a way to clone the repo.

**Comment by chrisblossom** [comment]
I'm not either. I just gave you the highest permission I could. Did that fix it?

**Comment by ArtemGovorov** [comment]
Yes, now I can see the source code, thanks!

**Comment by chrisblossom** [comment]
Also, you can see the [other issue](https://github.com/wallabyjs/public/issues/1398#issuecomment-345875505) I was having by removing ``{ pattern: '.babelrc+(.js|)', instrument: false }``.

**Comment by ArtemGovorov** [comment]
Thanks, looking into it now. Just to clarify, the mocking issue you've mentioned is in the `runs task` test?

**Comment by chrisblossom** [comment]
Yes that one and the other failing test. Sorry, not in front of a computer right now. If you disable lerna hoisting and remove the config fix from this thread you’ll see all tests pass in wallaby.

**Comment by ArtemGovorov** [comment]
There was an issue in Wallaby where `babel-jest` preset (required to hoist `jest.mock` calls) wasn't resolved, because Wallaby was trying to resolve it using an absolute path.

We have decided to switch from using absolute paths to standard node resolution for compilers/presets. The change is implemented in core v1.0.519. Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, and your current config should work for you. You may even revert `compilers` change in your config to be the way it was:

```javascript
         compilers: {
              '**/*.js': wallaby.compilers.babel(),
         },
```
after updating.

> Also, you can see the [other issue](https://github.com/wallabyjs/public/issues/1398#issuecomment-345875505) I was having by removing ``{ pattern: '.babelrc+(.js|)', instrument: false }``.

I checked this one as well, and looks like you do need the babelrc files in wallaby cache, because you are compiling code from `__sandbox__` folder with Jest transform. Removing the pattern doesn't only break WebStorm config, it breaks VS Code config for me as well.

**Comment by chrisblossom** [comment]
Thanks for getting that fixed so quickly!

To be clear, I still need the following code block:

```js
    process.env.NODE_PATH = require('path').join(
        wallaby.localProjectDir,
        '../../node_modules',
    );

```

**Comment by ArtemGovorov** [comment]
@chrisblossom Yes, that code block is still required.
