### ISSUE TITLE
Wallaby with Sinon Issues

### ISSUE THREAD

**Issue by jpreese** [wallabyjs/public#1403]
### Issue description or question
Spent a decent part of the day trying to get this to run.. but I'm running out of ideas. The problem is two fold.

1) I'm getting an error saying "Cannot read property 'createStubInstance' of undefined when calling
import sinon from 'sinon' however, var sinon = require('sinon') makes the error go away. Not really sure why.

![image](https://user-images.githubusercontent.com/6980197/33100789-b3fc05a4-cee3-11e7-8b68-e37df717424c.png)

2) The hardest one, everytime I try to actually use sinon, specificially createStubInstance from within Wallaby, I get the following error:

Runtime error: TypeError: Reflect.getMetadata is not a function​​

![image](https://user-images.githubusercontent.com/6980197/33100813-c927c51c-cee3-11e7-8c5a-083b18e28bb1.png)

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      { pattern: "client/node_modules/es7-reflect-metadata/*.ts", instrument: false },
      { pattern: 'client/node_modules/sinon/lib/sinon.js', instrument: false },

      "client/api/**",
      "client/config/**",
      "client/modules/**",
      "client/src/**",

      "server/**/*.js",
      "!server/node_modules/**",
      "!server/unit-tests/**",
      "!server/tests/**",
    ],
    tests: [
      "server/unit-tests/*.tests.js",
      "client/unit-tests/*.tests.js",
      "client/unit-tests/*.spec.ts"
    ],

    env: {
      type: "node"
    },

    testFramework: "mocha",

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.18

### OS name and version
Windows

Thanks in advanced for any advice on getting these resolved.

**Comment by ArtemGovorov** [comment]
> I'm getting an error saying "Cannot read property 'createStubInstance' of undefined when calling import sinon from 'sinon' however, var sinon = require('sinon') makes the error go away. Not really sure why.

Sinon doesn't have any `default` export, so the correct way to import it in TypeScript is

```javascript
import * as sinon from 'sinon'
```

> The hardest one, everytime I try to actually use sinon, specificially createStubInstance from within Wallaby, I get the following error:
> Runtime error: TypeError: Reflect.getMetadata is not a function​​

It doesn't look like the issue is wallaby specific. From your config file it looks like you are using `mocha` and node environment to run your client tests. Can you run mocha (without Wallaby) to see if it produces correct results?

**Comment by jpreese** [comment]
Thanks for the response @ArtemGovorov. I think I'm good now. It mostly boiled down to the code itself having trouble being tested, rather than Wallaby running it.
