### ISSUE TITLE
Can't get jest example to work

### ISSUE THREAD

**Issue by altano** [wallabyjs/public#1408]
### Issue description or question

The sample repo won't work for me. Steps to reproduce:

1. git clone https://github.com/wallabyjs/wallaby-jest-snapshots.git
1. Open Visual Studio Code for the cloned folder
1. Run `npm install`
1. In VS Code ctrl+shift+p and select the Wallaby Start command
1. Get the following error:

> ​​​​​[Info]​​​​​ Sat, 25 Nov 2017 01:22:09 GMT wallaby:workers Running tests in sandbox [worker #0, session #kv81s]
> ​​​​​[Info]​​​​​ Sat, 25 Nov 2017 01:22:09 GMT wallaby:workers Sandbox (active) [kv81s] error: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
> ​​​​​[Info]​​​​​ Error: Cannot find module 'jest/node_modules/jest-cli/build/TestRunner'
> ​​[Error] Runtime error: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?​​
> ​​[Error] Error: Cannot find module 'jest/node_modules/jest-cli/build/TestRunner'​​

1. Run `npm install jest-cli --save-dev`, stop Wallaby, start wallaby.
1. Same error as above...

This is the contents of the jest-cli build directory:

```
C:\src\wallaby-jest-snapshots [master ≡ +1 ~1 -0 !]> ls .\node_modules\jest\node_modules\jest-cli\build\


    Directory: C:\src\wallaby-jest-snapshots\node_modules\jest\node_modules\jest-cli\build


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       11/24/2017   5:21 PM                assets
d-----       11/24/2017   5:21 PM                cli
d-----       11/24/2017   5:21 PM                lib
d-----       11/24/2017   5:21 PM                reporters
-a----        9/27/2017   3:12 PM           1434 constants.js
-a----        9/27/2017   3:12 PM            843 coverage.template
-a----        9/27/2017   3:12 PM           1510 generate_empty_coverage.js
-a----        9/27/2017   3:12 PM            881 get_changed_files_promise.js
-a----        9/27/2017   3:12 PM           1299 get_no_test_found.js
-a----        9/27/2017   3:12 PM           1276 get_no_test_found_message.js
-a----        9/27/2017   3:12 PM            700 get_no_test_found_related_to_changed_files.js
-a----        9/27/2017   3:12 PM           2050 get_no_test_found_verbose.js
-a----        9/27/2017   3:12 PM           1510 jest.js
-a----        9/27/2017   3:12 PM           2155 pattern_prompt.js
-a----        9/27/2017   3:12 PM            203 pluralize.js
-a----        9/27/2017   3:12 PM           1091 pre_run_message.js
-a----        9/27/2017   3:12 PM           2654 reporter_dispatcher.js
-a----        9/27/2017   3:12 PM          11025 run_jest.js
-a----        9/27/2017   3:12 PM          10765 search_source.js
-a----        9/27/2017   3:12 PM           2379 test_name_pattern_prompt.js
-a----        9/27/2017   3:12 PM           2193 test_path_pattern_prompt.js
-a----        9/27/2017   3:12 PM           1110 test_path_pattern_to_regexp.js
-a----        9/27/2017   3:12 PM           3408 test_result_helpers.js
-a----        9/27/2017   3:12 PM          17123 test_scheduler.js
-a----        9/27/2017   3:12 PM           3713 test_sequencer.js
-a----        9/27/2017   3:12 PM           1198 test_watcher.js
-a----        9/27/2017   3:12 PM          30243 watch.js
```

### Wallaby.js configuration file

https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Looks like you are not using the latest core version, and using an older version that doesn't support the current version of Jest.

What is your core version (printed in Wallaby Console when you start wallaby)? If it is not the latest (> 1.0.520) and if you have recently updated your license, be sure to enter the new key and force core update as described at https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update

**Comment by altano** [comment]
Sorry I didn't realize the internals of the extension could be out of date while the extension was up to date, but I guess that makes sense. Everything works now. Cheers and thanks for the help.
