### ISSUE TITLE
VS Code: Add more links to localhost:51245

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1411]
After running tests with Wallaby for a while, there's no immediate link in either the Wallaby.js Console or Wallaby.js Tests output windows. You have to either know the URL or know to scroll _all_ the way up in the console. 
Maybe have the URL in the test window before or after test descriptors?

**Comment by ArtemGovorov** [comment]
Thanks for the feature request. We have added the `Open Wallaby App` command to the editor (`Cmd/Ctrl + Shift + P`) command palette and Wallaby command palette (`Cmd/Ctrl + Shift + =`). The feature is published in v1.0.68:

<img width="584" alt="screen shot 2017-11-29 at 10 10 06 am" src="https://user-images.githubusercontent.com/979966/33351067-c1f3d212-d4ed-11e7-98ed-d648e4c6b331.png">
