### ISSUE TITLE
Feature: add live comment snippet with keybinding

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#1412]
It would be great to have a keybinding for inserting `/*?*/` at the cursor position.
It is cumbersome to type `/*?*/` all the time instead of a simple shortcut.

**Comment by ArtemGovorov** [comment]
@KnisterPeter Pretty much all editors that we support allow to create (bindable) user snippets. So most likely you may create one for your editor and assign it to any key you like. What IDE/editor are you using?

**Comment by ArtemGovorov** [comment]
From other issues you've created, it looks like you are using VS Code. Here is the [relevant docs section on how to create the snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets) and assign it to any key combo that you like.

Hope it addresses the request.

**Comment by KnisterPeter** [comment]
Right, I'm using `vscode` and I've already have a custom snippet for me. I thought it might be useful for others as well and instead of creating an extension for just that it could be shipped with wallaby.

**Comment by ArtemGovorov** [comment]
Fair enough, reopening as a feature request. For now I have also [added some docs on how to create snippets](https://wallabyjs.com/docs/intro/advanced-logging.html#live-comment-snippet) for other IDEs if someone else is looking for it.

**Comment by vjpr** [comment]
IMHO this is better left out of Wallaby. It is the responsibility of the editor/ide.

- You may want to use `//?` or some variation.
- Maybe your editor supports surround templates so you can have it leave the cursor in the middle of the comment `/*? <cursor-here> */`.

**Comment by damionvega** [comment]
I have a snippet created in VS Code as well, but what I'd really appreciate is being able to add `/*?*/` at the end of the line by pressing a keybinding anywhere on the line, much like how commenting a line works (`ctrl/cmd` + `/`). Then @vjpr's idea of placing the cursor after would be the cherry on top.

This and only re-running upon save are the only things missing for me. Been loving it so far though!

**Comment by ArtemGovorov** [comment]
Since this issue was created, we have added the [`Show Value` command in Wallaby](https://wallabyjs.com/docs/intro/advanced-logging.html#live-value-display) that (with a simple keyboard shortcut) allows to achieve the exact same result as with live comment, but without changing the code.
