### ISSUE TITLE
Ubuntu - VScode - can't see some UI elements

### ISSUE THREAD

**Issue by jadczakd** [wallabyjs/public#1418]
### Issue description or question
 I can run Wallaby in VS Code, but don't see some of the UI elements for it (right click on file -> start/restart/stop). Tried reinstalling both the editor and the extension, no luck there.
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {

    files: [
      {"pattern": "src/lib/jquery-3.2.1.min.js", "instrument": false},
      {"pattern": "node_modules/chai/chai.js", "instrument": false},
      {"pattern": "node_modules/sinon/pkg/sinon.js", "instrument": false},
      'src/**/*.js'
    ],

    tests: [
      'test/**/*Tests.js'
    ],

    testFramework: "mocha"
  };
};

```

### Code editor or IDE name and version

Visual Studio Code 1.18.1

### OS name and version

Linux - Ubuntu 16.04 LTS

**Comment by ArtemGovorov** [comment]
Wallaby for VS Code doesn't have (and never had) the mentioned UI elements - `right click on file -> start/restart/stop`. Sounds like UI elements from Wallaby for Visual Studio. Wallaby for VS Code has all commands available in the editor command palette (`Ctrl + Shift + P`) or Wallaby command palette (`Ctrl + Shift + =`).

If I didn't understand the issue correctly or something else is missing, please provide some more details.

**Comment by jadczakd** [comment]
Thanks for the answer, my bad. Time to switch the editor, at least for the testing!
