### ISSUE TITLE
new Date() returns 1/1/1970

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1420]
### Issue description or question

Hi, I have something really strange going on. When I launch my tests, on initial run all `new Date()` return 1/1/1970. When I change into the test and make a small change, the correct date is returned. I am pretty sure I have not stubbed the constructor of Date object.

I cannot share the repo with you as it is a private project with 1Mil lines of code and 1K+ tests.

Have you ANY idea what can be messing with my date constructor?

Tests execute as expected with **mocha** in console.

Here is an example output:

```
    ​​​​​From console:​​​​​
      ​​​​​​​​​​
      ​​​​​Thu Jan 01 1970 10:00:00 GMT+1000 (AEST)​​​​​
      at new Date() ​src/client/helpers/helpers_client.tsx:168:6​
```

### Wallaby.js configuration file

```javascript
// const transform = require("fuse-test-runner").wallabyFuseTestLoader;
const path = require('path');
const jsxtransform = require('jsx-controls-loader').loader;

module.exports = function(wallaby) {
  // var load = require;

  return {
    files: [
      ...
    ],
    // debug: true,
    tests: [
      ...
    ],
    filesWithNoCoverageCalculated: [
      ...
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ jsx: 'react', module: 'commonjs' })
    },
    preprocessors: {
      '**/*.tsx': file => jsxtransform(file.content)
    },
    hints: {
      ignoreCoverage: /ignore coverage/ // or /istanbul ignore next/, or any RegExp
    },
    env: {
      type: 'node'
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    },
    testFramework: 'mocha',
    setup: function(wallaby) {
      var mocha = wallaby.testFramework;
      mocha.timeout(1000);

      const path = require('path');
      const snapshotDir = path.join(wallaby.localProjectDir, 'src', 'tests', 'snapshots');

      require('wafl').setup({
        wallaby,
        // if you want wallaby to save snapshots, you need to specify absolute path to their location
        snapshotDir,
        snapshotMode: 'test'
      });

      // setup server tests
      require('./src/tests/client_start');
      wallaby.testFramework.grep('@story|@viewModel');
    },

  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

OSX High Sierra 10.13.1

**Comment by ArtemGovorov** [comment]
It should be easy to quickly find if something is replacing Date constructor. In your test, before using Date, add
```javascript
console.log(Date.toString())
```
if something is replacing `Date`, then it should print something other than `function Date() { [native code] }`.

**Comment by tomitrescak** [comment]
Nope ;( I am getting. It seems that javascript is somehow failing.

```
function Date() { [native code] }
```
<img width="590" alt="screen shot 2017-12-04 at 5 47 08 pm" src="https://user-images.githubusercontent.com/2682705/33539565-2f18c8c6-d91b-11e7-9a8b-486dac10cad8.png">

When I make all my `matchSnapshot` matcher pass, all works well, the moment I only throw error in that matcher the whole system explodes ;(

**Comment by ArtemGovorov** [comment]
Could you please try the following, change you wallaby config `tests` file to:
```javascript
...
module.exports = function(wallaby) {
  
  return {
    ...
    tests: [
      'src/simpleTest.js'
    ],
    ...

  };
};
```

and create the `src/simpleTest.js`:

```javascript
console.log(new Date())
```
and run wallaby, what does it print?

**Comment by tomitrescak** [comment]
I'm getting correct date at this point. I guess I will follow this direction and start adding slowly my tests to see when the error will occur.

**Comment by ArtemGovorov** [comment]
> I'm getting correct date at this point (with your simpleTest.js).

It looks like one of the project files/dependencies may be causing the issue then.

> I guess I will follow this direction and start adding slowly my tests to see when the error will occur.

This sounds like the fastest way to find the reason of the issue. Maybe try adding your specs not one by one, but by a few at a time (or the other way around, bisect the initial list until the issue goes away).

> When I make all my matchSnapshot matcher pass, all works well, the moment I only throw error in that matcher the whole system explodes ;(

What if you try to throw an error for `matchSnapshot` in the `src/simpleTest.js` file? Perhaps the issue is in the `matchSnapshot` implementation?

**Comment by tomitrescak** [comment]
Hm. So the perpetrator was `sinon.useFakeTimers`.
I did not put `clock.restore()` into a `finally` and it snowballed in all tests.

Thanks for your support!
