### ISSUE TITLE
Links are not always resolved

### ISSUE THREAD

**Issue by silyevsk** [wallabyjs/public#1425]
### Issue description or question
Links are sometimes not resolved. An example is when the links are at the top level.
Example repo: [https://github.com/wix/wallabyjs-links-issue](https://github.com/wix/wallabyjs-links-issue)
If there's any pattern with a wildcard under tests, then for some reason the links are resolved (try uncommenting the comment in wallaby.js in the example repo)

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    files: [
      'a.js',
      'b.js'
    ],
    tests: [
      // '*.very_weird_workaround',
      'a.test.js'
    ]
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for creating and sharing the repo! The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version 1.0.529.
