### ISSUE TITLE
Cannot Stop Wallaby and restart if config file fails to load in Visual Studio

### ISSUE THREAD

**Issue by RobertTheGrey** [wallabyjs/public#143]
If I happen to have an invalid wallaby config file (js or json) - could be a syntax error or missing require or anything, then after right clicking the file and choosing "Start Wallaby" I get the expected error in the console: `Failed to load configuration file: ... `

The problem is, the I cannot right click the file and choose "Stop Wallaby" to try again. The workaround is the close to .sln and reopen, make the syntax fix and then the Start option is available again

**Comment by ArtemGovorov** [comment]
Fixed in 1.0.6 (wallaby.js will prompt to install the new version, once installed you may try it after Visual Studio restart).
