### ISSUE TITLE
Failed to execute start operation, Error: ENOTEMPTY: directory not empty, rmdir './packages/model-generator'

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1430]
After deleting the wallaby cache dir and re-running I see this message. No stack trace.

**Comment by ArtemGovorov** [comment]
Is there a `./packages/model-generator` folder in the wallaby cache after you deleted it? Can you try to delete the whole "projects" folder in the cache?
Looks like something in your system is still accessing the files in the cache folder, so Wallaby can't clean it. Try closing anything that can block Wallaby from cleaning the cache. 

If the suggestions above don't help, then the issue may be related to something else and not related to wallaby cache. In this case, please share a repro, we'll further investigate it.

**Comment by smcenlly** [comment]
Closing this old issue due to lack of activity. We will re-open the issue if more detail is provided.
