### ISSUE TITLE
Document wallaby.js for create-react-app-ts

### ISSUE THREAD

**Issue by acchou** [wallabyjs/public#1431]
### Issue description or question
Consider adding a sample `wallaby.js` configuration for `create-react-app-ts` generated projects, which combine React + JSX with Typescript.

### Wallaby.js configuration file
Here's an example that I adapted from the `create-react-app` example. It seems to work for me, but I'm not 100% sure I adapted it correctly:

```javascript
module.exports = function(wallaby) {
    // Babel, jest-cli and some other modules may be located under
    // react-scripts/node_modules, so need to let node.js know about it
    var path = require("path");
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, "node_modules") +
        path.delimiter +
        path.join(__dirname, "node_modules/react-scripts/node_modules");
    require("module").Module._initPaths();

    return {
        files: [
            "src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
            "!src/**/*.test.[jt]s?(x)"
        ],

        tests: ["src/**/*.test.[jt]s?(x)"],

        env: {
            type: "node",
            runner: "node"
        },

        compilers: {
            "**/*.js?(x)": wallaby.compilers.babel({
                babel: require("babel-core"),
                presets: ["react-app"]
            }),
            "**/*.ts?(x)": wallaby.compilers.typeScript({
                module: "commonjs",
                jsx: "React"
            })
        },

        setup: wallaby => {
            const jestConfig = require("react-scripts-ts/scripts/utils/createJestConfig")(
                p => require.resolve("react-scripts-ts/" + p)
            );
            delete jestConfig.transform["^.+\\.(js|jsx)$"];
            delete jestConfig.transform["^.+\\.(ts|tsx)$"];
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: "jest"
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.18

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Awesome, thanks for sharing! The config looks good to me, have added the link to it to [the relevant docs section](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app).

**Comment by yonatanmn** [comment]
wan't working till adding:

```js

    files: [
      'tsconfig.json', // <--
      'tsconfig.test.json', // <--
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.[jt]s?(x)'
    ],
```

**Comment by ArtemGovorov** [comment]
@yonatanmn Thanks for the note. What error was it throwing?

**Comment by yonatanmn** [comment]
```js
Error: {
    "messageText": "Cannot read file 'C:\\Users\\Yonatan\\.WebStorm2017.3\\system\\wallaby\\projects\\efc992132dd2be2f\\instrumented\\tsconfig.test.json': ENOENT: no such file or directory, open 'C:\\Users\\Yonatan\\.WebStorm2017.3\\system\\wallaby\\projects\\efc992132dd2be2f\\instrumented\\tsconfig.test.json'.",
    "category": 1,
    "code": 5012
}
    at readCompilerOptions (C:\projects\TopBar\node_modules\react-scripts-ts\node_modules\ts-jest\dist\utils.js:73:15)
    at Object.getTSConfig (C:\projects\TopBar\node_modules\react-scripts-ts\node_modules\ts-jest\dist\utils.js:122:18)
    at Object.getCacheKey (C:\projects\TopBar\node_modules\react-scripts-ts\node_modules\ts-jest\dist\preprocessor.js:43:28)
    at ScriptTransformer._getCacheKey (C:\projects\TopBar\node_modules\jest-runtime\build\script_transformer.js:76:19)
    at ScriptTransformer._getFileCachePath (C:\projects\TopBar\node_modules\jest-runtime\build\script_transformer.js:107:27)
    at ScriptTransformer.transformSource (C:\projects\TopBar\node_modules\jest-runtime\build\script_transformer.js:191:32)
    at ScriptTransformer._transformAndBuildScript (C:\projects\TopBar\node_modules\jest-runtime\build\script_transformer.js:291:40)
    at ScriptTransformer.transform (C:\projects\TopBar\node_modules\jest-runtime\build\script_transformer.js:332:21)
    at Runtime._execModule (C:\projects\TopBar\node_modules\jest-runtime\build\index.js:501:53)
    at Runtime.requireModule (C:\projects\TopBar\node_modules\jest-runtime\build\index.js:332:14)
    at C:\projects\TopBar\node_modules\jest-jasmine2\build\index.js:93:15
    at Generator.next (<anonymous>)
    at step (C:\projects\TopBar\node_modules\jest-jasmine2\build\index.js:106:583)
    at C:\projects\TopBar\node_modules\jest-jasmine2\build\index.js:106:813
    at new Promise (<anonymous>)
    at C:\projects\TopBar\node_modules\jest-jasmine2\build\index.js:106:494
    at jasmine2 (C:\projects\TopBar\node_modules\jest-jasmine2\build\index.js:106:68)
    at runTest (C:\projects\TopBar\node_modules\jest-runner\build\run_test.js:98:10)
    at C:\projects\TopBar\node_modules\jest-runner\build\index.js:71:68
    at Generator.next (<anonymous>)
    at step (C:\projects\TopBar\node_modules\jest-runner\build\index.js:23:376)
    at C:\projects\TopBar\node_modules\jest-runner\build\index.js:23:536
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by guylemon** [comment]
Hi @ArtemGovorov, not sure where to put this, but here is a working config for `create-react-app` and typescript using VSCode.  I was able to get it working without some of the additional options used above.  Hope this is helpful for anyone finding their way here!

```javascript
/**
 * Simple typescript config for an un-ejected create-react-app using typescript
 *
 * This config assumes the following:
 *
 * 1. Your tests are located in a file named tests.ts, or tests.tsx,
 * OR the index.ts(x) of a 'tests' dir within the `src` directory or
 * a subdirectory inside of `src`.
 *
 * 2. You are running a version of node that can handle template strings and `const`
 *
 * 3. Your basic dependencies look something like the package.json below
 */

module.exports = function(wallaby) {
  // change this expression to reflect your naming conventions
  const testPathExp = 'src/**/tests.ts?(x)';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      `!${testPathExp}`,
    ],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app'],
      }),
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'React',
      }),
    },

    testFramework: 'jest',
  };
};
```
The package.json file:
```json
/**
 * Package JSON
 */
{ 

  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts-ts": "2.8.0",
    "styled-components": "^2.4.0",
    "true-myth": "^1.1.1"
  },
  "scripts": {
    "cm": "git-cz",
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^21.1.8",
    "@types/node": "^8.0.53",
    "@types/react": "^16.0.25",
    "@types/react-dom": "^16.0.3",
    "commitizen": "^2.9.6",
    "cz-conventional-changelog": "^2.1.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
 }
```

**Comment by ArtemGovorov** [comment]
@guylemon Awesome, thanks for sharing! The issue is referenced from our docs, so your solution is helpful for Wallaby users.

**Comment by hellnation** [comment]
I've just started with the latest version of create-react-app-ts and the very first thing I did was added the wallaby.js as described above. The boilerplate that comes with create-react-app comes with a single test, being src/App.test.tsx. With the testPathExp above, this test isn't found and so everything appears fine. If I 'yarn test' it finds the test and it passes successfully. If I then change the testPathExp so that it finds this one test:

const testPathExp = 'src/**/*.test.ts?(x)';

and run Wallaby I get this error:

.\src\App.css:1​​
​​({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.App {​​
​​                                                                                         ^​​
​​​​
​​SyntaxError: Unexpected token .​​
  at ​src/App.css:1​
  at Object.<anonymous> ​src/App.tsx:4:0​
  at Object.<anonymous> ​src/App.test.tsx:5:0​

Does anyone know waht this means? It would be useful to fix it or provide a workaround here because I assume anyone who starts a new create-react-app-ts will have this experience.

**Comment by hellnation** [comment]
@ArtemGovorov the doco I mention above is https://wallabyjs.com/docs/integration/react-jsx.html in the create-react-app section, when referring to typescript

**Comment by ArtemGovorov** [comment]
@hellnation Thanks for sharing! Doesn't the very first config (for the issue starter) work for you? Just checked and it's working for me.

**Comment by tomitrescak** [comment]
Any love for create-react-app 2.0 ? I am getting 0/0 on tests ;(

**Comment by ArtemGovorov** [comment]
@tomitrescak Just tried 
- installing `create-react-app@next` (`2.0.0-next.66cc7a90`), 
- generating a new project with `create-react-app my-app --scripts-version=react-scripts-ts` 
- adding wallaby config exactly as in the first post in this issue,
- and everything is working for me:

<img width="735" alt="screen shot 2018-05-17 at 5 00 35 pm" src="https://user-images.githubusercontent.com/979966/40161346-df3bd8de-59f3-11e8-83cb-505a26e28520.png">

Please share a sample repo where the issue can be reproduced.

**Comment by tomitrescak** [comment]
Hi, thanks for a prompt response. I have a bit of special setup with babel7 compiling typescript,so no react-scripts-ts

Repo is here: https://github.com/tomitrescak/babel-ts

**Comment by ArtemGovorov** [comment]
@tomitrescak When you need to use babel after TypeScript, you may use [wallaby preprocessor](https://wallabyjs.com/docs/integration/typescript.html#using-with-babel). Note that you also need to leave module and JSX compilation for babel (because you're using [synthetic imports](https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360) and JSX control statements), so TypeScript need to emit ES6 modules and plain JSX. That's how your repo `npm test` command works anyway.

Had sent you [the pull request with the change](https://github.com/tomitrescak/babel-ts/pull/1).

**Comment by QuantumInformation** [comment]
Is there any repo with a working solution for create-react-app-ts apps?

We have our tests like so 

![image](https://user-images.githubusercontent.com/216566/45032600-21722f80-b04a-11e8-94cd-dbdfa63cba0f.png)

**Comment by QuantumInformation** [comment]
I tried what some of you guys posted but get

Failed to run compilers on src/index.tsx, Error: Couldn't find preset "@babel/react" relative to directory "src"

we have
```
  "dependencies": {
    "axios": "^0.17.1",
    "axios-mock-adapter": "^1.14.0",
    "bootstrap": "4.1.1",
    "enzyme": "^3.4.2",
    "enzyme-adapter-react-16": "^1.2.0",
    "font-awesome": "~4.7.0",
    "formik": "^0.11.11",
    "history": "^4.7.2",
    "jest": "^22.4.3",
    "jest-cli": "^23.1.0",
    "jest-junit": "^5.0.0",
    "loadash": "^1.0.0",
    "node-sass-chokidar": "^1.2.2",
    "prettier": "^1.12.1",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-redux": "^5.0.7",
    "react-router-dom": "^4.2.2",
    "react-scripts-ts": "2.15.1",
  }```


my setup

```module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  process.env.NODE_ENV = 'test';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel({
        sourceMap: true,
        compact: false,
        presets: ['@babel/react', '@babel/typescript']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts/' + p),
        '.',
        ['src']
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(ts|tsx|js|jsx)') && void delete jestConfig.transform[k]
      );
      console.log(jestConfig);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};```

**Comment by ArtemGovorov** [comment]
Looks like you are trying to run config for CRA 2 beta. Try the config from [this post above](https://github.com/wallabyjs/public/issues/1431#issuecomment-381056890), it is working for me on a freshly generated project `npx create-react-app my-app-ts--scripts-version=react-scripts-ts`.

**Comment by QuantumInformation** [comment]
I tried that config for my project as stands, but now get this.
`
Runtime error: TypeError: Cannot read property 'Component' of undefined
    at Object.<anonymous> (./src/component/shared/toolTip/ToolTipPopUp.js:54:19)
`
But my yarn test works perfectly

![image](https://user-images.githubusercontent.com/216566/45084900-496b9c80-b0f7-11e8-9b08-c2f6d5ae7676.png)

I'll try up date `CRA 2 ` and let you know what happens

**Comment by QuantumInformation** [comment]
Same error upgrading

![image](https://user-images.githubusercontent.com/216566/45088816-14b11280-b102-11e8-96ef-fe88a0b2d74a.png)

**Comment by QuantumInformation** [comment]
I tried with a brand new CRT and ran wallaby with the above config and get

![image](https://user-images.githubusercontent.com/216566/45091012-09151a00-b109-11e8-91da-137b8930f416.png)

**Comment by QuantumInformation** [comment]
Wallaby just doesn't like this

![image](https://user-images.githubusercontent.com/216566/45096009-6c0dad80-b117-11e8-8dd5-9b3831864bfa.png)

![image](https://user-images.githubusercontent.com/216566/45096022-70d26180-b117-11e8-9309-f411190c25eb.png)

**Comment by ArtemGovorov** [comment]
> Runtime error: TypeError: Cannot read property 'Component' of undefined at Object.

@QuantumInformation Thanks for sharing the additional details. Looks like you are using synthetic default imports and to support them `ts-jest` (used by CRA with TypeScript) compiles compiled TypeScript code with Babel as well, so you need a similar preprocessor in your Wallaby config. Adding this preprocessor should help: 

```diff
module.exports = function(wallaby) {
  ...
  return {
       ...
+    preprocessors: {
+      '**/*.js?(x)': file => require('babel-core').transform(
+        file.content,
+        {
+          sourceMap: true, compact: false, filename: file.path, presets: ['react-app']
+        })
+    }
  };
};
```

**Comment by QuantumInformation** [comment]
Thanks for all your help so far, I added that but still get the same error:

```js
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  return {
    files: ['tsconfig.json', 'tsconfig.test.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],

    tests: [testPathExp],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      }),
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'React'
      })
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: ['react-app']
        })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts-ts/' + p));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};

```
![image](https://user-images.githubusercontent.com/216566/45145683-2d303400-b1b9-11e8-8d38-876e8df1be07.png)

**Comment by ArtemGovorov** [comment]
@QuantumInformation Sorry, I forgot to mention that you need to remove the `compilers` section (at least for TypeScript). So this config should work:

```javascript
module.exports = function(wallaby) {
    const testPathExp = 'src/**/*.test.ts?(x)';

    return {
        files: ['tsconfig.json', 'tsconfig.test.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],

        tests: [testPathExp],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel({
                babel: require('babel-core'),
                presets: ['react-app']
            })
        },

        preprocessors: {
            '**/*.js?(x)': file =>
                require('babel-core').transform(file.content, {
                    sourceMap: true,
                    compact: false,
                    filename: file.path,
                    presets: ['react-app']
                })
        },

        setup: wallaby => {
            const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts-ts/' + p));
            Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: 'jest'
    };
};
```

**Comment by QuantumInformation** [comment]
Thx that fixed it!

**Comment by tomitrescak** [comment]
Just a question, why do you need both preprocessor and compiler? Can't you just use preprocessor in this case?

**Comment by ArtemGovorov** [comment]
@tomitrescak You are truly an expert in Wallaby configuration! Excellent point, the preprocessor should be enough.

**Comment by QuantumInformation** [comment]
My linter is complaining about this

![image](https://user-images.githubusercontent.com/216566/45220086-f9cad380-b2a4-11e8-8226-fb9dc0b3115d.png)

![image](https://user-images.githubusercontent.com/216566/45220091-fe8f8780-b2a4-11e8-9061-ab812041c5dd.png)

**Comment by QuantumInformation** [comment]
@tomitrescak so I can just delete the compilers part?

**Comment by QuantumInformation** [comment]
lol, now I have 

![image](https://user-images.githubusercontent.com/216566/45220630-a2c5fe00-b2a6-11e8-9460-ac3bf98fb96c.png)

**Comment by lucax88x** [comment]
Need some help there.

I've successfully used wallabyjs for months in angular applications, and this week I started a react + typescript app for some POCs.

I did the create-react-app with typescript and ejected it so I could put my wallaby configuration.

I literally tried with all the wallabyjs confs there, but nothing, it ALWAYS hang up on 

![image](https://user-images.githubusercontent.com/6294464/46872039-5fc1f200-ce33-11e8-8d5e-cdf14d33c1fc.png)

I even tried to put the debug: true in the conf, but nothing prints out as errors.. it's like something is stuck?

hint: normal tests using the yarn run test are working, but I noticed there's like an INTERACTIVE mode in the Jest framework like this:

![image](https://user-images.githubusercontent.com/6294464/46872090-86802880-ce33-11e8-83b9-880f753471d3.png)

it's possible that wallaby is stuck because of that?

**Comment by smcenlly** [comment]
Could you please create a [new issue](https://github.com/wallabyjs/public/issues/new) for this and provide us with a sample repo so that we can take a look at your package + wallaby configuration? We'd be happy to take a look at why this isn't working for you.

**Comment by liamdawson** [comment]
It seems that the sample Wallaby config does not load the dotenv support, so environment variables I expect in tests aren't set.

I fixed this by using the `react-scripts` env handling:

```diff
   process.env.NODE_ENV = 'test';
+  process.env = require('react-scripts/config/env')('http://example.com').raw;
   process.env.NODE_PATH +=
     path.delimiter +
     path.join(__dirname, 'node_modules') +
     path.delimiter +
     path.join(__dirname, 'node_modules/react-scripts/node_modules');
```

I haven't checked to see if this introduces other side effects, but it fixed my test that failed due to a missing environment variable. 🙂

**Comment by theutz** [comment]
> **Wallaby Config for CRA >=2.1 with TypeScript support generated app (not ejected)**:
> 
> ```js
> module.exports = function (wallaby) {
> 
>   var path = require('path');
>   process.env.NODE_ENV = 'test';
>   process.env.NODE_PATH +=
>     path.delimiter +
>     path.join(__dirname, 'node_modules') +
>     path.delimiter +
>     path.join(__dirname, 'node_modules/react-scripts/node_modules');
>   require('module').Module._initPaths();
> 
>   return {
>     files: [
>       {pattern: 'src/setupTests.ts', instrument: false},
>       'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
>       '!src/**/*.test.ts?(x)'
>     ],
> 
>     tests: ['src/**/*.test.ts?(x)'],
> 
>     env: {
>       type: 'node',
>       runner: 'node'
>     },
> 
>     preprocessors: {
>       '**/*.js?(x)': file =>
>         require('@babel/core').transform(file.content, {
>           sourceMap: true,
>           compact: false,
>           filename: file.path,
>           presets: ['react-app']
>         })
>     },
> 
>     setup: wallaby => {
>       const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
>       Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
>       delete jestConfig.testEnvironment;
>       wallaby.testFramework.configure(jestConfig);
>     },
> 
>     testFramework: 'jest'
>   };
> };
> ```
> 
> **Wallaby Config for `create-react-app-ts` generated app (not ejected)**:
> 
> ```js
> module.exports = function(wallaby) {
>     const testPathExp = 'src/**/*.test.ts?(x)';
> 
>     return {
>         files: ['tsconfig.json', 'tsconfig.test.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],
> 
>         tests: [testPathExp],
> 
>         env: {
>             type: 'node',
>             runner: 'node'
>         },
> 
>         compilers: {
>             '**/*.js?(x)': wallaby.compilers.babel({
>                 babel: require('babel-core'),
>                 presets: ['react-app']
>             })
>         },
> 
>         preprocessors: {
>             '**/*.js?(x)': file =>
>                 require('babel-core').transform(file.content, {
>                     sourceMap: true,
>                     compact: false,
>                     filename: file.path,
>                     presets: ['react-app']
>                 })
>         },
> 
>         setup: wallaby => {
>             const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts-ts/' + p));
>             Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
>             delete jestConfig.testEnvironment;
>             wallaby.testFramework.configure(jestConfig);
>         },
> 
>         testFramework: 'jest'
>     };
> };
> ```

Using this setup and the newest version of `create-react-app --typescript`, it seems that Wallaby is not processing manual mocks for user modules. Jest seems to understand what's going on, however. Any ideas?

**Comment by smcenlly** [comment]
@theutz - you need to change your preprocessor presets to get mocks working:

```diff
..
    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
-         presets: ['react-app']
+         presets: [require('babel-preset-jest'), 'react-app']
        })
    },
...
```

We will update our doco to reflect this requirement.

**Comment by smcenlly** [comment]
We've now added an [official sample project](https://github.com/wallabyjs/wallaby-create-react-app-ts) for `create-react-app --typescript` which we will use as the source of truth for create-react-app unejected config.

**Comment by theutz** [comment]
Awesome @smcenlly! Thanks for your quick reply and your always stellar support!
