### ISSUE TITLE
SyntaxError: Unexpected token import, Node 8

### ISSUE THREAD

**Issue by vespertilian** [wallabyjs/public#1433]
### Issue description or question

"SyntaxError: Unexpected token import"

Testing some super simple Node  scripts trying to use import with them. They work with require. 

import {promisify} from 'util';

Maybe an issue with import ? 

https://stackoverflow.com/questions/44985913/nodejs-8-import-module-require-or-import

Do I need to use Babel?

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            'src/**/*.js',
            'data-files/**'
        ],

        tests: [
            'test/**/*spec.js'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'jasmine',
    };
};
```

### Code editor or IDE name and version

WebStorm v?
 2017.3

### OS name and version

OSX
10.13.1

### Node version 

8.9.1

**Comment by ArtemGovorov** [comment]
Yes, you'll need to use Babel. 

Node doesn't support ES6 modules yet (only in experimental mode behind a flag, with special file extension, and [a few limitations](https://github.com/nodejs/node/blob/master/doc/api/esm.md#unsupported) that are making it not yet ready for proper integrations).
