### ISSUE TITLE
Wallaby doesn't work with jest's setupTestFrameworkScriptFile configuration

### ISSUE THREAD

**Issue by silyevsk** [wallabyjs/public#1434]
### Issue description or question
Please check the [demo repo](https://github.com/wix/wallabyjs-jest-setupTestFrameworkScriptFile-issue) - `yarn jest` passes but wallaby fails

### Code editor or IDE name and version

Visual Studio v1.18.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
The `setupTestFrameworkScriptFile` file is executed (if you add `console.log` into it, you may see that it prints the output in Wallaby Console). 

However, with the [path like this](https://github.com/wix/wallabyjs-jest-setupTestFrameworkScriptFile-issue/blob/master/wallaby.js#L21), the file is loaded from your local project folder (as opposed to be loading from Wallaby cache where all files are instrumented), so non-instrumented version is executed (this is why coverage indicators are displayed as grey). For the same reason, the loaded file ends up mocking an incorrect `./b` module.

I have sent you the [pull request to make it work](https://github.com/wix/wallabyjs-jest-setupTestFrameworkScriptFile-issue/pull/1).

**Comment by silyevsk** [comment]
It works, thanks!

Unfortunately though it makes using jest with wallaby less transparent (We can't just use `wallaby.testFramework.configure(require('./package.json').jest` but need to duplicate the `setupTestFrameworkScriptFile` setting). May be it would be better if this was done automatically by wallaby.

**Comment by ArtemGovorov** [comment]
@silyevsk Thanks for your feedback. We'll investigate how to do it automatically without breaking anything. Many of our users have their `setupTestFrameworkScriptFile` loaded from their local project (the file is executed, and don't even have to be included to the `files` list), but in your case it is not a option because you are setting up module mocks there.
