### ISSUE TITLE
Custom location for: tsconfig.json, wallaby.js

### ISSUE THREAD

**Issue by alexander-ossur** [wallabyjs/public#1438]
Hello,

I need one of those in order to separate client/server logic:
1. a support for a custom location of tsconfig.json. T.e. _/client/tsconfig.json_, _/server/tsconfig.json_
2. a support for a custom location of wallaby.js., so this would grab the tsconfig.json from the same directory. T.e. _/client/wallaby.js_, _/server/wallaby.js_

For number (1) I tried this, but did not work:
```javascript
compilers: {
	"src/client/src/**/*.ts?(x)": wallaby.compilers.typeScript ({ tsconfig: "src/client/tssconfig.json" })
},
```

Also it would be nice to know a full list of **wallaby.compilers.typeScript** options

Thank you in advance

**Comment by ArtemGovorov** [comment]
As [mentioned in our docs](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings), wallaby.compilers.typeScript options is your [TypeScript compiler options](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) (`compilerOptions` of your `tsconfig.json` file).

So you may just do this:

```
compilers: {
	"src/client/src/**/*.ts?(x)": wallaby.compilers.typeScript(require("./src/client/tssconfig.json").compilerOptions)
},
```

**Comment by alexander-ossur** [comment]
Thank you Artem,

Unfortunately this solution will not work in our case. Let me explain. We got two main parts of the project: client and server.

The folder structure look like this:
```
root
	src
		client
			src
				client.tsx	<- entry point
			tsconfig.json		<- TypeScript config for client. Based on /root/tsconfig.json
			...			<- more utility files to support builds and etc
		server
			src
				server.ts	<- entry point
			tsconfig.json		<- TypeScript config for server. Based on /root/tsconfig.json
			...			<- more utility files to support builds and etc
	wallaby-client.js
	wallaby-server.js
	tsconfig.json
	webpack-dev.js			<- Currently builds both Client and Server 
	webpack-prod.js			<- Not ready, but supposed to build both Client and Server 
	...				<- more utility files to support builds and etc
```

Let's have a closer look into client side settings.

/root/tsconfig.json
```javascript
{
	"compilerOptions": {
		"inlineSourceMap": true,
		"inlineSources": true,

		"target": "ES6",
		"allowSyntheticDefaultImports": true,

		"module": "commonjs",
		"moduleResolution": "node",
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"removeComments": false,

		"noImplicitAny": true,
		"strictNullChecks": true,

		"jsx": "react"
	}
}
```

/root/src/client/tsconfig.json
```javascript
{
	"extends": "./../../tsconfig",
	"compilerOptions": {
		"target": "es5",
		"module": "commonjs"
	},
	"include": [
		"./src/**/*"	<- This is very important, and will compile only ./src/client/src files
	]
}
```

As you can see we narrowed the set of files to be compiled by TypeScript (section "include"). But it seems like Wallaby allows only to change "compilerOptions" and not the rest of JSON file.

While while |ts-loader| in Webpack does not support it fully either, we can give a file location:
```javascript
	module: {
		rules: [{
			test: /\.tsx?$/,
			use: [{
				loader: "ts-loader",
				options: {
					configFile: "./src/client/tsconfig.json"    <- Magic
				}
			}]
		}]
	}
```

The reason of this...
```javascript
compilers: {
	"src/client/src/**/*.ts?(x)": wallaby.compilers.typeScript ({ tsconfig: "src/client/tssconfig.json" })
},
```
... is because I saw somewhere ...
```javascript
compilers: {
	"**/*.ts?(x)": wallaby.compilers.typeScript ({ tsconfig: false })
},
```
... which made me thinking that Wallaby may support this too.

**Comment by ArtemGovorov** [comment]
> But it seems like Wallaby allows only to change "compilerOptions" and not the rest of JSON file.

Wallaby doesn't need the rest of the file. Your `wallaby-client.js` contains the `files` list and wallaby TypeScript compiler is using those files. If your `files` list in the `wallaby-client.js` file looks like:

```
files: [
  'src/client/src/**/*.ts?(x)',
  ...
]
```
then it should be enough.

Regarding merging `/root/tsconfig.json` file and `/root/src/client/tsconfig.json`, you may use `Object.assign`, like in the [sample from here](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L4):

```javascript
var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

...
return {
    ...

    compilers: {
      'src/client/src/**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
    },
```

**Comment by alexander-ossur** [comment]
Oh I see now. Yes that will definitely work. Thank you.
