### ISSUE TITLE
`Show side-by-side diff` for Ava tests 

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1439]
### Issue description or question

I can't find `show side-by-side assertion` for Ava, e.g. `t.snapshot(actual)`.

As explained here: https://github.com/wallabyjs/public/issues/1437#issuecomment-352149440

**Comment by ArtemGovorov** [comment]
The command is supported for relevant Ava assertions:

![ava](https://user-images.githubusercontent.com/979966/34085244-3948b3f6-e3d9-11e7-8752-d12014b165be.gif)

but not for Ava snapshots. Will close this one and merge it into another opened issue: https://github.com/wallabyjs/public/issues/1440
