### ISSUE TITLE
Test Explorer

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#144]
Would like to see a view with time statistics per file/test. This will help to identify tests that are taking longer than I would expect.

**Comment by ArtemGovorov** [comment]
@endragor I'll steal the issue to extend the scope a bit if you don't mind.

It'd be nice to have a filterable and searchable tree of all tests, where apart from the execution time, other test data would be listed.

**Comment by usefulthink** [comment]
:+1:

**Comment by brettjacobson** [comment]
I was just curious if there is progress on the Test Explorer?

**Comment by ArtemGovorov** [comment]
@brettjacobson There's been some progress, but not very substantial yet. We do get a lot of requests for the feature though from IntelliJ users and Atom users as well. 

I have been thinking of perhaps providing a couple of reports (Test Explorer and Coverage) that could be opened from an IDE but in a browser. That would be the easiest and the fastest way for us to implement and release it, as opposed to doing 3 IDE specific implementations. 

Even though HTML report will not be as 'integrated' as the rest of wallaby features, these reports is not something that is used as frequently as other features, so perhaps a little context switching (from IDE to browser) is not a big deal here.

Your thoughts?

**Comment by endragor** [comment]
That works for me.

**Comment by fvanwijk** [comment]
I think it is a good start, since we are used to get a HTML coverage report with Karma/Istanbul as well (there is no good IDE integration yet). However, I really like to eventually have IDE integration for coverage etc. because lack of context switches makes Wallaby so powerful.

**Comment by brettjacobson** [comment]
I think an HTML coverage report would be useful, but it would only be useful every once in awhile.  A Test explorer window would be useful all the time I think, since it would serve many purposes.

**Comment by ArtemGovorov** [comment]
Thanks for your feedback guys.

@brettjacobson 
> A Test explorer window would be useful all the time I think, since it would serve many purposes.

How often would you use the window? I understand that sometimes one may need to use it for a few minutes or even more, but working with the window is already a context switching from writing code right? So my question is - would you need to keep the tests tree open all the time while you write code?

**Comment by brettjacobson** [comment]
With NCrunch I keep the ncrunch Tests window open on a secondary monitor. Perhaps NCrunchs' window is valuable to us because our C# unit test suite is much larger (and slower) than our JS test suite, so its advantageous to get progress reports on test runs (even when optimized to run only affected tests).

I definitely use the ncrunch test window as a test code navigation aid.  I think I would like to use a wallaby test window for the same purpose

Perhaps you can summarize what possible requirements for a Test Explorer that you've gathered/planned?

**Comment by ArtemGovorov** [comment]
> With NCrunch I keep the ncrunch Tests window open on a secondary monitor.

So you wouldn't mind if in wallaby case it was a browser window if it had the features you need?

Here is a summary of features for the Test Explorer that I had in mind (note that the Coverage Report is a separate view with its own set of requirements/features, though some of its data may end up in the Test Explorer):

##### Minimal set of features for v1:
- Displaying all tests in a tree (name + execution time).
- Displaying details of a selected test (execution time, errors if any, console.log output for test).
- Allowing to jump to the selected test code, its error stack lines and console.log positions.
- Allowing to run the selected test/suite or all project tests.

##### Advanced features to add later:
- Allowing to group/order/filter tests by file/test name, execution time, failed/passed state, etc.
- Displaying detailed test execution progress and what tests are currently running.

Your thoughts?

**Comment by brettjacobson** [comment]
I think that would be okay, if it was a browser window. Would a browser window in VS still be able to jump to the right place in the code windows??

Otherwise the features sound great!

**Comment by ArtemGovorov** [comment]
> Would a browser window in VS still be able to jump to the right place in the code windows??

Yes, any code links inside the browser window will work as if they were in IDE, so clicking on a line link will navigate to the line location in the opened IDE.

**Comment by brettjacobson** [comment]
That sounds like it would meet our needs.

**Comment by hellboy81** [comment]
I'm curious about it. Is there screenshots?

**Comment by ArtemGovorov** [comment]
@hellboy81 will share some as soon as I can

**Comment by brettjacobson** [comment]
any update on this item?

**Comment by hellboy81** [comment]
+ `infinity`

**Comment by ArtemGovorov** [comment]
We are working on it and have made some good progress. I'd say it's about 80% ready.

**Comment by hellboy81** [comment]
Test Explorer teaser trailer needed!

**Comment by ArtemGovorov** [comment]
*Disclaimer*: it's an early (but already working) prototype and things may (and most likely will) change, but thought I'd still share it with you guys:

<img width="1035" alt="screen shot 2016-03-11 at 9 23 20 pm" src="https://cloud.githubusercontent.com/assets/979966/13700935/cc69bc78-e7cf-11e5-88c9-125729241150.png">

**Comment by fvanwijk** [comment]
Super cool!
Also add number of ignored tests at the upper right corner?

**Comment by brettjacobson** [comment]
looks awesome! I agree, number of ignored tests would be valuable to see too

**Comment by soates** [comment]
Looks very good - exactly what we need.

**Comment by soates** [comment]
Any update on when this is due out?

**Comment by ArtemGovorov** [comment]
No exact date yet, but we are very close. We decided to experiment with a couple of features that have increased the work scope, here's a sneak peek:
![ui](https://cloud.githubusercontent.com/assets/979966/16289055/55cad040-3935-11e6-972e-34153e451f62.gif)

**Comment by brettjacobson** [comment]
Looking great!

**Comment by ArtemGovorov** [comment]
Forgot to add to the recording that everything in the test explorer gets updated in realtime as one's making changes in the code. Updated the GIF to demonstrate it.

**Comment by ArtemGovorov** [comment]
[Introducing Wallaby.js App](http://dm.gl/2016/07/19/wallaby-app/)): realtime bird's eye view of your project's tests connected to your editor.
