### ISSUE TITLE
Random test suite must contain test error and not all tests running.

### ISSUE THREAD

**Issue by TroySchmidt** [wallabyjs/public#1441]
### Issue description or question
Won't run all the tests.  But doesn't give a meaningful error other than the one listed below.  I can go to the specific test files and run the files manually and they will run fine.

### Wallaby.js configuration file
```module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.+(ts*|js*|css|svg|png|json)',
      '!src/**/*.test\.js*',
      '!src/**/*.test\.ts*',
      '!src/registerServiceWorker.ts'
    ],

    tests: ['src/**/*.test.js*','src/**/*.test.ts*'],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_PATH=src'
      }
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(require('./tsconfig.test.json').compilerOptions)
    },

    setup: (wallaby) => {
      const jestConfig = require('./package.json').jest;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',

    filesWithNoCoverageCalculated: ['src/store.ts', 'src/**/webClient.ts', 'src/modules/**/layout.js*', 'src/index.js', 'src/**/__mocks__/*', 'src/stories/**'],

    hints: {
        ignoreCoverage: /ignore coverage/
    },

    workers: {
      initial: 6,
      regular: 2,
    }
  };
};
```

```javascript
​​Error: Your test suite must contain at least one test.​​
​​    at c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-cli\build\test_scheduler.js:98:22​​
​​    at Generator.next (<anonymous>)​​
​​    at step (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-cli\build\test_scheduler.js:30:405)​​
​​    at c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-cli\build\test_scheduler.js:30:635​​
​​    at new Promise (<anonymous>)​​
​​    at c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-cli\build\test_scheduler.js:30:316​​
​​    at onResult (c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-cli\build\test_scheduler.js:122:59)​​
​​    at c:\Source\MSRAM-Web\Msram.Web\node_modules\jest-runner\build\index.js:81:46​​
​​    at <anonymous>​​
```

### Code editor or IDE name and version

Visual Studio Code v1.19.0

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
- What is your installed version of `jest`?
- Please run all of your tests, then open your [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) and search for `console.log: FAIL`, you should be able to find:

```
​​​​​[Info]​​​​​ console.log: FAIL <problem spec path>
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     Your test suite must contain at least one test.
```

Does the `<problem spec path>` contain any tests? Are they conditionally executed?

**Comment by TroySchmidt** [comment]
jest version 22.  Running the test and looking the Wallaby console only shows the message shown above.  Running them manually with npm run test (an ejected TypeScript app from create react app) runs all the tests fine with no error like that.

**Comment by ArtemGovorov** [comment]
> Running the test and looking the Wallaby console only shows the message shown above

You're probably looking to Wallaby Failing Tests output channel, however I was asking about [Wallaby.js Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) output channel (it's a separate output channel). Could you please open it and search for the failing spec name like I have described in the previous comment?

**Comment by TroySchmidt** [comment]
Duh.  I looked at that and finally figured out that it was attempting to run tests in the snapshot file.  So changed the wallaby config line to 
```
tests: ['src/**/*.test.js?(x)','src/**/*.test.ts?(x)'],
```
before it was a wildcard.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by ArtemGovorov** [comment]
You may also need to fix your `files` pattern to include `.snap` files, so that you may use [wallaby supported snapshot testing features](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0).
```
    files: [
      'src/**/*.+(ts|js|tsx|jsx|snap|css|svg|png|json)',
      '!src/**/*.test.+(ts|js)?(x)',
      '!src/registerServiceWorker.ts'
    ],

    tests: ['src/**/*.test.js?(x)','src/**/*.test.ts?(x)'],
```
