### ISSUE TITLE
status indicators is too small on hi-dpi in JetBrains IDEs

### ISSUE THREAD

**Issue by mhhegazy** [wallabyjs/public#1443]
### Issue description or question
status indicators is too small on hi-dpi 
**is there any settings can control size of indicators?**
![image](https://user-images.githubusercontent.com/198722/34371325-43cdff42-eadd-11e7-9ed6-c3aa056bb974.png)

### Wallaby.js configuration file
not applicable 

### Code editor or IDE name and version
WebStorm v2017.3

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Try updating your Wallaby IntelliJ plugin to the latest v1.0.104, let us know if status indicators are looking better now.
