### ISSUE TITLE
Another interesting case where wallaby fails but cli pass

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1452]
This test fails on Wallaby but pass on CLI:
https://github.com/unional/clibuilder/blob/master/src/loadPlugins.spec.ts#L5-L8

```ts
test('empty folder will still load global plugins', async t => {
  const plugins = await loadPlugins('clibuilder-plugin', { cwd: 'fixtures/no-plugin' })
  t.is(plugins.length, 1)
})
```

Its lookup strategy is this:
https://github.com/unional/clibuilder/blob/master/src/loadPlugins.ts#L28

```ts
  const globalFolder = getGlobalPackageFolder(__dirname)
  ...

function getGlobalPackageFolder(folder): string {
  const indexToFirstNodeModulesFolder = folder.indexOf('node_modules')
  const basePath = indexToFirstNodeModulesFolder === -1 ? folder : folder.slice(0, indexToFirstNodeModulesFolder)
  return path.resolve(findup.sync('node_modules', { cwd: basePath }), '..')
}
```
But seems like running in Wallaby this logic doesn't work.

**Comment by ArtemGovorov** [comment]
As I have [mentioned here](https://github.com/wallabyjs/public/issues/1446#issuecomment-354638602), wallaby runs tests from it's local cache (and it doesn't copy node modules there). While wallaby makes sure that standard node resolution works, your app is physically reading `node_modules` folder.

The easiest way to make it work for your case is to redirect wallaby to your local folder whenever `node_modules` are resolved in wallaby cache using [wallaby `setup` function](https://wallabyjs.com/docs/config/bootstrap.html). I have sent you [the pull request with the change](https://github.com/unional/clibuilder/pull/127).
