### ISSUE TITLE
Storyshots Classname Mismatch with Jest

### ISSUE THREAD

**Issue by TomPridham** [wallabyjs/public#1455]
### Issue description or question
We've got a few tests in our repo that reliably pass when run with `jest` but always fail in the wallaby console. The failures are always due to generated classnames being moved around in the snapshot. They're all there and contain the same things, they are just in different places, so it causes the snapshot to fail. 
<img width="406" alt="screen shot 2018-01-09 at 6 27 47 pm" src="https://user-images.githubusercontent.com/8271228/34751608-db9f49b0-f56a-11e7-9ccb-c860e1593a63.png">

It also reports the failure is in a file completely separate from the test that is failing.
<img width="645" alt="screen shot 2018-01-09 at 6 19 02 pm" src="https://user-images.githubusercontent.com/8271228/34751465-029cd1d2-f56a-11e7-9869-1db648aaf3e3.png">

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  const babelConfig = require('./config/babel')

  return {
    files: [
      'package.json',
      { pattern: 'src/**/*.css', load: false, instrument: false },
      { pattern: 'src/**/*.snap', load: false, instrument: false },
      '!src/legacy/**',
      '!src/integration-tests/**',
      '!src/**/*.test.js',
      'src/**/*.js',
      '.storybook/config.js'
    ],

    filesWithNoCoverageCalculated: ['src/**/*.queries.js', 'src/**/*.stories.js', 'src/**/*.test.js'],

    tests: [
      'src/**/*.test.js',
      'server/src/**/*.test.js',
      { pattern: 'src/integration-tests/**', ignore: true }
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelConfig)
    },

    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Rubymine 17.3.1, but it also reliably happens in a coworkers Atom IDE

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Hi,

we'll need a repro to investigate and resolve the issue (likely via some config change). Could you please setup and share a sample repo demonstrating the issue? Since it's reliably failing, it hopefully shouldn't be too hard to isolate an example.
