### ISSUE TITLE
do not show license reminder on every restart

### ISSUE THREAD

**Issue by pekeler** [wallabyjs/public#1460]
### Issue description or question

My license expires in two weeks. It's helpful to show a reminder of that. It's not helpful to do so on every restart.

My code base is complex, often requiring a manual restart of the tests (cmd-shift-R R). Now I need to confirm this stupid reminder panel every time which is super annoying.

### Code editor or IDE name and version

VSCode 1.19.2

### OS name and version

OSX 10.13.2

**Comment by pekeler** [comment]
<img width="1575" alt="license" src="https://user-images.githubusercontent.com/42363/34886712-27f7338c-f781-11e7-84f9-fca9bd10c166.png">

**Comment by ArtemGovorov** [comment]
Please update to Wallaby VS Code v1.0.72, and you may use this setting in your VS Code user settings (`Cmd + ,`):
```
{
    ...
    "wallaby.suppressExpirationNotifications": true
}
```

**Comment by pekeler** [comment]
Thank you - this works.
