### ISSUE TITLE
Doesn't work with yarn workspaces

### ISSUE THREAD

**Issue by blackxored** [wallabyjs/public#1465]
I think I've reported this before but I might be mistaken. When using yarn workspaces, wallaby's node-modules resolution seem to fail since it only takes into account the project root's `node_modules`. When using workspaces, yarn might chose to install a dependency under a nested `node_modules`. This is probably similar to lerna without `--hoist` as well.

**Comment by ArtemGovorov** [comment]
Wallaby should support the scenario - we know it's working for a few of our users. Having said that, your case may be somehow special, so could you please create a sample repo demonstrating the issue? We are happy to have a look.

**Comment by blackxored** [comment]
Unfortunately project is private. But blackxored/elasticdev-starter-kit
might have a similar (albeit outdated) setup.

-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by ArtemGovorov** [comment]
Just tried to clone and run tests in the mentioned repo, but tests seem to run the same way in CLI and in Wallaby. Could you please branch the `blackxored/elasticdev-starter-kit` repo and create reproducible sample?

**Comment by swernerx** [comment]
I am having the same issue.

**Comment by swernerx** [comment]
Project:
https://github.com/sebastian-software/edge/tree/master/packages/edge-webpack

package.json:
https://github.com/sebastian-software/edge/blob/master/packages/edge-webpack/package.json

wallaby config:
https://github.com/sebastian-software/edge/blob/master/packages/edge-webpack/wallaby.js

```
~/Workspace/open-source/edge master
❯ ls -l node_modules/.bin/jest
lrwxr-xr-x  1 swerner  staff  23 Jun 19 13:06 node_modules/.bin/jest -> ../jest-cli/bin/jest.js
```

**Comment by swernerx** [comment]
Executing jest via npm/yarn works fine.

**Comment by ArtemGovorov** [comment]
@swernerx 
> If I place the config file to the root of Yarn workspaces it fails again as it does not fine any file called "wallaby" then after trying to select it.

In this case you'll need to open the root of the project in your editor, and then it'll work.

Please try updating to [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and specify the path to your Jest module (relative to the path where your wallaby config is located):

```diff
module.exports = function config(wallaby) {
  ...
  return {
    ...
-   testFramework: "jest"
+   testFramework: {
+     type: 'jest',
+     path: require('path').resolve(__dirname + '/../node_modules/jest-cli')
+   }
```

**Comment by tomitrescak** [comment]
To me it does not work when requiring other packages in the same workspace. For example with this setup:

```
{
  "private": true,
  "workspaces": [
    "client",
    "server",
    "dynamic-form",
    "dynamic-form-semantic-ui",
    "toolbelt"
  ]
}
```

Whenever requiring any of the packages, e.g. 'dynamic-form' I get 'module not found' exception ;(

**Comment by ArtemGovorov** [comment]
@tomitrescak Please create a sample repo and open a separate issue with the link to it. We are happy to take a look.

**Comment by tomitrescak** [comment]
@ArtemGovorov here you go. Just run yarn in the top level folder and then run wallaby, selecting the wallaby.js from the app folder. It complains that the test1-package does not exists, while it clearly exists in the node_modules folder.

[Workspace.zip](https://github.com/wallabyjs/public/files/2814409/Workspace.zip)

**Comment by tomitrescak** [comment]
Here is another version simply using "marked" package. But still does not work ;(
[Archive.zip](https://github.com/wallabyjs/public/files/2814454/Archive.zip) [60kb]

**Comment by tomitrescak** [comment]
OK, it seems that I need to properly set up ALL node_module paths, so far I got it working on this small example. Will let know I will not get it working on my big repo. Thanks ;)
