### ISSUE TITLE
Invalid mapping when using Vue 2.5

### ISSUE THREAD

**Issue by asmadsen** [wallabyjs/public#1466]
### Issue description or question
I tried adding Wallaby.js to my vue project however I keep getting an `Invalid mapping` error thrown in `node_modules/vue-loader/node_modules/source-map/lib/source-map-generator.js` Here is the entire console output from wallaby
[wallaby.log](https://github.com/wallabyjs/public/files/1642196/wallaby.log)
I am debugging this on the [vue-wallaby-webpack-template](https://github.com/ChangJoo-Park/vue-wallaby-webpack-template) with the following [package.json](https://github.com/wallabyjs/public/files/1642207/package.json.txt)

### Wallaby.js configuration file

```javascript
const webpackConfig = require('./build/webpack.test.conf.js')
const wallabyWebpack = require('wallaby-webpack')

module.exports = function (wallaby) {
  webpackConfig.resolve.alias = {'@': require('path').join(wallaby.projectCacheDir, 'src')}
  webpackConfig.externals = {vue: 'Vue'}
  webpackConfig.module.rules.find(r => r.loader === 'vue-loader').options.loaders.js = ''

  const wallabyPostprocessor = wallabyWebpack(webpackConfig)

  return {
    files: [
      {pattern: 'node_modules/vue/dist/vue.js', instrument: false},
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'src/**/*.*', load: false}
    ],

    env: {
      type: 'browser'
    },

    tests: [
      {pattern: 'test/**/*.spec.js', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    setup: function () {
      // eslint-disable-next-line
      Vue.config.errorHandler = function (err) {
        throw err
      }
      window.__moduleBundler.loadTests()
    },

    hints: {
      ignoreCoverage: /ignore coverage/
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },
    debug: true
  }
}
```

### Code editor or IDE name and version

WebStorm 2017.3.3
Build #WS-173.4301.22, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

Mac OS X 10.13.2

**Comment by ArtemGovorov** [comment]
Looks like there's a bug in a newer version of `vue-loader`. Wallaby generates code that gets inserted on the same line as the `script` tag, but [the scenario is broken by this change](https://github.com/vuejs/vue-loader/commit/acaf6a648bd0e4bfc005852bd496c70ff7c9757f#commitcomment-26936408). It only happens when `vue-loader` generates source maps for `.vue` files (that are not required in case of wallaby), so you may easily fix it by adding the following line to your wallaby config:

```diff
...
module.exports = function (wallaby) {
  webpackConfig.resolve.alias = {'@': require('path').join(wallaby.projectCacheDir, 'src')}
  webpackConfig.externals = {vue: 'Vue'}
  webpackConfig.module.rules.find(r => r.loader === 'vue-loader').options.loaders.js = ''
+ webpackConfig.plugins.push(new (require('webpack').LoaderOptionsPlugin)({test: /\.vue$/, sourceMap: false}))
...
```
