### ISSUE TITLE
Wallaby.js local license issue

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1467]
### Issue description or question
I'm trying running two Wallaby instances (monorepo) within the same IDE and am running into a license issue telling me I'm running Wallaby on a different computer. I am unsure if this would happen if I was running VSCode and Webstorm at the same time as well.

<img width="1532" alt="screen shot 2018-01-18 at 6 07 51 am" src="https://user-images.githubusercontent.com/1595871/35101989-6a7752d4-fc16-11e7-9811-057ac34d7b14.png">

### Code editor or IDE name and version
```
WebStorm 2017.3.3
Build #WS-173.4301.22, built on January 15, 2018
JRE: 1.8.0_152-release-1024-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### OS name and version

``Mac OS X 10.13.2``

**Comment by ArtemGovorov** [comment]
It's likely that you have an orphaned process running wallaby core (maybe as a result of and IDE/editor crash). Please close all wallaby instances, kill all node process on your machine (or restart it) and try again.

Let me know if it helped.

**Comment by chrisblossom** [comment]
@ArtemGovorov I am trying to run Wallaby twice within the same editor. Although it does not seem to be working as expected. Maybe just stopped by the license server?

**Comment by ArtemGovorov** [comment]
> trying to run Wallaby twice within the same editor.

Oh, [this is actually not supported](https://github.com/wallabyjs/public/issues/89) (different instances of the same IDE or different editors - yes, but not running multiple running configurations in the same IDE window). However, it's not supported for other technical reasons, license checking should still work fine.
