### ISSUE TITLE
How to run @std/esm module loader.

### ISSUE THREAD

**Issue by jdalton** [wallabyjs/public#1468]
I've noticed there are examples for using `babel` and `babel-register` so I'm wondering if it's possible to support the [@std/esm](https://github.com/standard-things/esm) with existing wallaby hooks. It can be invoked in a couple of ways.

```js
// Provide options as a parameter or options file.
require = require("@std/esm")(module/*, options*/)
module.exports = require("./main.mjs").default
```
or
```js
node -r @std/esm main.mjs
```

**Comment by ArtemGovorov** [comment]
Thanks for pointing out the ways to start `@std/esm`. Wallaby [allows to pass node params (and ENV variables)](https://wallabyjs.com/docs/config/runner.html), so if your Wallaby config looks like:

```javascript
module.exports = function () {
  return {
    ...
    env: {
      type: 'node',
      params: {
        env: 'ESM_OPTIONS=cjs',
        runner: `-r ${require('path').join(__dirname, 'node_modules/@std/esm')}`
      }
    }
  }
};
```

then ` @std/esm` just works:

![esm](https://user-images.githubusercontent.com/979966/35138584-088c4ba8-fd3b-11e7-8a98-3320bf4f0cd5.gif)

I have created [this sample repo](https://github.com/wallabyjs/wallaby-std-esm) with the config above.

**Comment by ArtemGovorov** [comment]
Added the [`@std/esm` configuration notes](https://wallabyjs.com/docs/integration/node.html#es-modules) to wallaby docs.

**Comment by jdalton** [comment]
Wow thank you @ArtemGovorov!

Is there anything I could do to make things easier?

> require('path').join(__dirname, 'node_modules/@std/esm')

Could this be simplified to `require.resolve("@std/esm")`

**Comment by ArtemGovorov** [comment]
@jdalton 

> Could this be simplified to `require.resolve("@std/esm")`?

Good point, thanks! Updated my post, the docs and the sample repo.

> Is there anything I could do to make things easier?

Looks like everything just works with the one line wallaby config change (swapping babel setting with this one) for those willing to use it, probably as simple as it can be.

We're now looking into adding `@std/esm` to [Quokka](https://quokkajs.com/), maybe even as built-in default option if ES6 imports are used. There's one issue though, we are not using standard node require for the root/main file, so while `@std/esm` seems to be working with imported modules, the main entry file is not processed by `@std/esm`. I was wondering if there's an API (or one could be exposed) where I could pass the code and get back the transpiled code to run it?

**Comment by jdalton** [comment]
> I was wondering if there's an API (or one could be exposed) where I could pass the code and get back the transpiled code to run it?

There isn't but there could totally be one. So for the entry file you pass source text in... so you need like an exposed `Module#_compile` method which takes`(sourceCode, filePath)` params? Do you need a specific kind of return value?

**Comment by jdalton** [comment]
If you can describe your "perfect world" API I'll try to deliver it 😋

**Comment by ArtemGovorov** [comment]
Basically we are running the following code for the root/entry (which is not a physical file, it may be just an unsaved scratch file that doesn't exist on disk - so essentially we are dealing with a string):

```javascript

// file.content contains user code with ES imports
// file.path is just a virtual path (not a path to a real physical file)

const sourceCode = require('module').wrap(file.content); // wraps with node function
const runner = require('vm').runInThisContext(sourceCode, { filename: file.path });

runner(
          // exports
          {},
          // require
          ourSpecialRequire,
          // module
          {},
          // __filename
          file.path,
          // __dirname
          path.dirname(file.path)
)

// the runner will execute user's code
```

This code above runs in a node process started as `node -r @std/esm`, so `@std/esm` infrastructure is already loaded when the code executes. So if `@std/esm` could expose some API at this point, we could definitely use it.

So I cans see there are 2 things we need to do to integrate `@std/esm` in Quokka:

- before passing `file.content` to `const sourceCode = require('module').wrap(file.content);` we need to process it with `Module#_compile`. Passing a single `sourceCode` parameter is sufficient for our purposes, but if you need `filePath`, we can also pass it (but note that it will not be a real file).

- also note that we are passing `ourSpecialRequire` to the executed entry/root code. So any `require` in user's code of the entry module (but not any modules imported from the entry module) will use `ourSpecialRequire`. In the `ourSpecialRequire` implementation we are calling `require('module')._load(request, entryModule, false);` directly and doing other things required for Quokka to work. So if you are patching module loading on a higher level in `@std/esm`, then we'll need to somehow access the API as well.

I guess I should start looking into the `@std/esm` source code to better understand how you're patching node module loading pipeline, hopefully with the explanation above you could point me to the right places of `@std/esm` source to read.

Hope it makes sense.

**Comment by ArtemGovorov** [comment]
Have to say I'm very excited about the possibility of making it work and including in our Quokka plugin by default - eg. when a user starts typing/adding ES6 imports it would just work with zero config. That'd be very cool as right now Babel needs to be installed configured by many of our users (and we have 624k plugin downloads in 10 months in [VS Code plugin only](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode), so easily talking about thousands of people) only to use ES6 modules.

**Comment by jdalton** [comment]
If `@std/esm` is loaded with `node -r @std/esm` then when wallaby calls `require('module')` it should get the `'module'` of `@std/esm` and not the real Node one. Is it erroring out and not translating `import`/`export` syntax?

**Comment by ArtemGovorov** [comment]
Sorry if I wasn't clear. 

[Wallaby](https://wallabyjs.com/) (our test runner) is working great with `@std/esm` with just the config setting discussed earlier (and now [described in our docs](https://wallabyjs.com/docs/integration/node.html#es-modules)). 

Now I'm trying to make our other tool called [Quokka](https://quokkajs.com/) (live scratchpad/playground for JavaScript) to work with `@std/esm` (and use `@std/esm` by default with zero config from our users).

Right now with the way we process user's code:
```javascript
const sourceCode = require('module').wrap(userCode);
```
the returned `sourceCode` doesn't have `import/export` translated. Do you replace `require('module').wrap` function?

**Comment by jdalton** [comment]
> the returned `sourceCode` doesn't have `import/export` translated. Do you replace `require('module').wrap` function

Yes, but it just mimics what Node's is. Compilation and execution happens in the `Module.prototype._compile` method *(which should be ours too)*. Ahhh so we'd need to make `require('vm').runInThisContext` compile the code too. Okay!

Basically once `@std/esm` loads the entire load pipeline runs through it. So I can make it work 😋

**Comment by ArtemGovorov** [comment]
> Ahhh so we'd need to make `require('vm').runInThisContext` compile the code too. Okay!

That'd be awesome! No API would be required then.

**Comment by jdalton** [comment]
Thinking on this more we take the `module.exports` and perform a juggle on it. The initial value is used to store the runtime library and then it's replaced by another empty `exports` object.  Each module is executed through a `runtime.run(function(global [,other args]) { /* module code */ })` so while we can compile the code in `vm.runInContext` we couldn't be sure it would be invoked values. Can you point me to your 
```js
runner(
          // exports
          {},
          // require
          ourSpecialRequire,
          // module
          {},
          // __filename
          file.path,
          // __dirname
          path.dirname(file.path)
)
```
code.

**Comment by ArtemGovorov** [comment]
I have [created this repo](https://github.com/ArtemGovorov/std-esm-integration) with the runnable sample of what we are essentially doing. 

Run
```
npm i
npm run esm
```

and you should get the 
```
virtual.js:2
    import a from './someModule'
    ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)

```
error.

If you run
```
npm run commonjs
```
(exact same params but `require` instead of `import` in the executed code), then it works as expected.

Hope it helps. Here's the [full sample code](https://github.com/ArtemGovorov/std-esm-integration/blob/master/esm.js):
```javascript
const path = require('path');
const Module = require('module');
const vm = require('vm');

const file = {
  content: `
    import a from './someModule'
    console.log('hello');
  `,
  path: 'virtual.js'
};

const sourceCode = Module.wrap(file.content);
const runner = vm.runInThisContext(sourceCode, {filename: file.path});

const entryModule = new Module('.', null);
entryModule.filename = file.path;
entryModule.paths = Module._nodeModulePaths(path.dirname(entryModule.filename)).concat([]); // more module folders

const specialRequire = function (request) {
  const loadedModule = Module._load(request, entryModule, false);
  // some irrelevant logic using/checking loadedModule
  return loadedModule;
};

runner(
  // exports
  {},
  // require
  specialRequire,
  // module
  {},
  // __filename
  file.path,
  // __dirname
  path.dirname(file.path)
);

```

**Comment by ArtemGovorov** [comment]
Note that the `specialRequire` in the sample is only used for modules that are imported into the root one. So even though `someModule` is using ES6 export, it's working fine when `require`-ing it from  the root module with CommonJs (and it's great). So the only bit that seems to be missing is that the `vm.runInThisContext` doesn't compile `import/export`.

**Comment by jdalton** [comment]
Ah is this bit closed source? *(it's ok if it is)*.
I have an idea... The `entryModule._compile` method compiles and uses its `entryModule.require` inside the `require` that's passed to the compiled code. So if you wanted to create a custom `require` you could just overwrite the one on `entryModule.require`. Then you could use `entryModule._compile(sourceCode, file.path)`.

**Comment by ArtemGovorov** [comment]
> Ah is this bit closed source? *(it's ok if it is)*.

Yes, it is. Sorry, I should have mentioned it.

> Then you could use `entryModule._compile(sourceCode, file.path)` instead of `vm.runInThisContext`.

Yes, we could do it, but at the moment it still doesn't compile ES imports. Here's the code I'm trying (have also [added it to the sample repo](https://github.com/ArtemGovorov/std-esm-integration/blob/master/esm-compile.js) so it can be run with `npm run esm-compile`):

```javascript
const path = require('path');
const Module = require('module');
const vm = require('vm');

const file = {
  content: `
    import a from './someModule'
    console.log('hello');
  `,
  path: 'virtual.js'
};

const sourceCode = Module.wrap(file.content);
const runner = vm.runInThisContext(sourceCode, {filename: file.path});

const entryModule = new Module('.', null);
entryModule.filename = file.path;
entryModule.paths = Module._nodeModulePaths(path.dirname(entryModule.filename)).concat([]); // more module folders

entryModule.require = function (request) {
  const loadedModule = Module._load(request, entryModule, false);
  // some irrelevant logic using/checking loadedModule
  return loadedModule;
};

entryModule._compile(file.content, file.path);
```

Running the is resulting in 
```
virtual.js:2
    import a from './someModule'
    ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)

```

Am I missing something?

**Comment by jdalton** [comment]
> Am I missing something?

No you're not. I'll dig into it.

**Comment by jdalton** [comment]
Okay, I have it working locally. I'll clean it up and likely bump in a day or so!

**Comment by jdalton** [comment]
Will do. Just have to refactor some code for better reuse/sharing between `Module#_compile` and the `Module._extensions[".js"]` equivs.

**Comment by ArtemGovorov** [comment]
@jdalton Hey, we have run into an issue with patching `require` function in Wallaby when running with `@std/esm`. In our AVA integration, we need to monkey patch the `require` function as follows:

```javascript
  var Module = require('module').Module;
  var modulePrototype = Module.prototype;
  var originalRequire = modulePrototype.require;
  modulePrototype.require = function (filePath) {
    ...
    // calling the originalRequire at some point
  };
```

However the function is never invoked when running with `@std/esm`. Is there a way to hook into the pipeline and patch the `require` function replaced by esm?

**Comment by ArtemGovorov** [comment]
This also doesn't work
```javascript
  var Module = require('module').Module;
  var originalLoad = Module._load;
  Module._load = function (filePath) {
    ...
    // calling the originalLoad at some point
  }
```

**Comment by jdalton** [comment]
What does `console.log(Module + "")` produce?

**Comment by ArtemGovorov** [comment]
> What does `console.log(Module + "")` produce?

```
class O extends T{_compile(t,e){return b(this,t,e)}load(t){if(this.loaded)throw new h("Module already loaded: "+this.id);var e=O._extensions,i=E(s.extname)(t);""!==i&&"function"==typeof e[i]||(i=".js"),this.filename=t,this.paths=E(N.a)(E(s.dirname)(t)),e[i](this,t),this.loaded=!0}}
```

**Comment by jdalton** [comment]
Great, that means it's ours. Side note: The next release of AVA will use it for tests when using AVA `require` option with `@std/esm`.

**Comment by ArtemGovorov** [comment]
> Great, that means it's ours.

Yes, the module is replaced, it's just that currently overriding its functions like `Module.prototype.require` or `Module._load` doesn't result in the same behaviour as doing it with pure node for `node_modules` (but is working for built-ins). 

Here's a simple check, given `test.js`

```javascript
const Module = require('module').Module;
const modulePrototype = Module.prototype;
const originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
  console.log('intercepted ' + filePath);
  return originalRequire.apply(this, arguments);
};

require('http');
require('left-pad');
```

running plain node prints
```
> node test.js

intercepted http
intercepted left-pad
```
and running esm only prints
```
> ESM_OPTIONS=cjs node -r @std/esm test.js

intercepted http
```

**Comment by jdalton** [comment]
Cool. Will get that working too.

**Comment by jdalton** [comment]
Ok I've got it working in both test cases now. I'm going to cleanup and publish in a day or so.
This was a big help in refactoring the code to be more flexible. Things are in a much better place because of this request.

**Comment by ArtemGovorov** [comment]
@jdalton You rock! Looking forward to playing with the new version when it's published.

**Comment by jdalton** [comment]
Since you're using a special `modulePrototype.require` would you need the `import a from './someModule'` to process `'./someModule'` through `modulePrototype.require`?

**Comment by ArtemGovorov** [comment]
> Since you're using a special `modulePrototype.require` would you need the `import a from './someModule'` to process `'./someModule'` through `modulePrototype.require`?

For our purposes we only need to intercept `require` calls.

**Comment by jdalton** [comment]
Ah, okay. That means I can ship sooner. : )

**Comment by jdalton** [comment]
Sorry for the delay. After thinking on it more I really wanted `import` to be inspectable like `require` so now I've made it so that using  your custom require you can intercept static `import` and dynamic `import()`. Just adding a unit test and will bump in a few hours.

**Comment by jdalton** [comment]
[v0.20.0](https://github.com/standard-things/esm/releases/tag/0.20.0) is released 🎉

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! Will be looking into integrating it soon.

**Comment by jdalton** [comment]
Just checking in to see if you've run into any more issues I can tackle.

**Comment by ArtemGovorov** [comment]
@jdalton So far so good, thanks! Wallaby part is [now working great](https://github.com/wallabyjs/public/issues/1474#issuecomment-361240852) (we can intercept `require` calls) and for Quokka we need to do some more investigation on switching from

```javascript
vm.runInThisContext(sourceCode, ...
```

to 

```
entryModule._compile(sourceCode, file.path)
```
because those 2 are may not equivalent in terms of isolating globals, etc. So some things may break for some users, we need to understand the implications or find some workarounds.

**Comment by jdalton** [comment]
> So some things may break for some users, we need to understand the implications or find some workarounds.

Sure, let me know if there's a specific scenario to dig into.

**Comment by jdalton** [comment]
Which globals are you introducing. Since you're using `runInThisContext` it should be the same context as `entryModule._compile`.

**Comment by ArtemGovorov** [comment]
@jdalton Looks like you are correct and globals should not be an issue. Let me investigate other possible differences between 2 methods. Maybe you are you aware of any that I could test/check?

**Comment by jdalton** [comment]
The only different will be what you're passing it in terms of a custom wrapper or custom values. 
Under the hood `entryModule._compile` uses `vm.runInContext`.

**Comment by jdalton** [comment]
erm `vm.runInThisContext`

**Comment by ArtemGovorov** [comment]
So we have published the latest Quokka version with `entryModule._compile` instead of `vm.runInThisContext`. Will see how it goes for few days, and if nothing breaks for any of our users (and I don't see why anything would break), the plan is to enable `@std/esm` by default.

**Comment by jdalton** [comment]
Awesome news!

**Comment by ArtemGovorov** [comment]
[Quokka with `@std/esm` support is shipped](https://medium.com/@artem.govorov/es-modules-support-in-quokka-by-default-5a0b18256194)!

**Comment by jdalton** [comment]
So rad!!

**Comment by jdalton** [comment]
Curious if there was a perf improvement over Babel.

**Comment by ArtemGovorov** [comment]
> I'm curious. Was a perf improvement over Babel?

Babel is optional in Quokka, but there's definitely a performance improvement with `@std/esm` over babel with `env` preset (or with just ES modules transform).

Startup time of Quokka with `@std/esm` vs. with babel is more than times better, because:

<img width="396" alt="screen shot 2018-02-07 at 3 29 20 pm" src="https://user-images.githubusercontent.com/979966/35900073-be40534c-0c1b-11e8-9a17-7ea9fd06a534.png">

(though Quokka by default is reusing created node process with loaded modules for further incremental runs)

**Comment by lorengreenfield** [comment]
@jdalton @ArtemGovorov Thanks guys, I appreciate the work you've put into getting wallaby and @std/esm working together. I'm trying to get things setup and I seem to be getting an error when using import.meta.url - `SyntaxError: Unexpected token`. Everything works as expected when I avoid import.meta usage, including dynamic `import()`. Should I create another issue or is this something that just won't work?

**Comment by jdalton** [comment]
import.meta.url should work. A parse error means I missed a usage pattern for it. Can you post the snippet you used.

**Comment by lorengreenfield** [comment]
Here's how I'm using it currently (I've tried a few different ways though):
```
let server = new Hapi.Server({
connections: {
      routes: {
        files: {
          relativeTo: new URL('../client/dist', import.meta.url)
        }
    }
})
```
I've also tried using path.resolve with import.meta.url at the start
and even just doing a simple `console.log(import.meta.url)` results in the same error.

**Comment by lorengreenfield** [comment]
I realise I also need the .pathname on the new URL too, that results in a different error though

**Comment by jdalton** [comment]
the `import.meta.url` is not a url object it's a url string so you'll have to pass it to the URL constructor
```
import { URL } from "url"
```

> even just doing a simple `console.log(import.meta.url)` results in the same error.

That is odd. I noticed in quokka if I typed `import.meta.url` into a new JavaScript file I get a Syntax error too. On the `std/esm` the unambiguous parse seems to pick up on `import.meta.url` without issue (so not throwing there).

**Comment by lorengreenfield** [comment]
I've been using @std/esm@0.20.0, I'll give it a shot with 0.21.3 to see if there's any difference.

**Comment by lorengreenfield** [comment]
Yeah, no dice. Not that you were expecting it to work though...

**Comment by ArtemGovorov** [comment]
This wasn't an issue with `@std/esm`, it was an issue with Wallaby/Quokka core. We parse code in both Wallaby and Quokka (regardless of whether `std/esm` is used or not) to provide Wallaby/Quokka related features. Our parser didn't support `import.meta` (we also use `acorn` for parsing BTW).

Now the support has been added to [the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), as well as published in the latest Quokka extension version.

<img width="373" alt="screen shot 2018-02-11 at 11 19 13 am" src="https://user-images.githubusercontent.com/979966/36068285-7bdf0e94-0f1d-11e8-871f-8705ff354ec6.png">

**Comment by jdalton** [comment]
@ArtemGovorov Ah cool,`std/esm` uses acorn too!
If you want to compare plugin implementations [here is ours](https://github.com/standard-things/esm/blob/master/src/acorn-ext/dynamic-import.js).

**Comment by ArtemGovorov** [comment]
@jdalton Yep, we shamelessly took your implementation because the other one we found didn't have a suitable license.

**Comment by jdalton** [comment]
Dude, awesome! Anything you need, have at it. Ours has a better lookahead trick too 😋

**Comment by jdalton** [comment]
> but I'm guessing you may be using other properties of your lookahead version return result elsewhere.

Ah yes, ours is using the [flyweight pattern](https://en.wikipedia.org/wiki/Flyweight_pattern) so it reuses a single acorn parser instance to lookahead. This avoids corrupting the state of the primary parser.

**Comment by jdalton** [comment]
**Update:**

This [caught an issue](https://github.com/standard-things/esm/commit/c19ec313b161e0389782996e3b0487b5246f3f50) where we weren't detecting `import.meta` as ESM when in unambiguous mode.

RE `parser.input[parser.pos]`: 

Does that work with whitespace between the `import` the `.` and the `meta`?
See [these tests](https://github.com/standard-things/esm/commit/6a91a23961512536761c6a2ad49d12a7f3ed4123#diff-49e2b45b6868f87105497a585f8445b5).

**Update:**

Bumped `@std/esm` v0.21.4 :tada:

**Comment by ArtemGovorov** [comment]
> Does that work with whitespace between the `import` the `.` and the `meta`?

Good catch, `import .meta` will not work with our `lookahead` parser version. We'll need to use your version.

Wondering if the `import['meta']` should work as well (or generally `key = 'meta'; import[key]`)? Didn't find anything in the proposal that would indicate otherwise.

**Comment by lorengreenfield** [comment]
@jdalton @ArtemGovorov Gentlemen... Thank you. All fixed. I'm really impressed with both the Wallaby.js and @std/esm projects. Super nice to see open source and commercial projects working so well together.

**Comment by ArtemGovorov** [comment]
Though because of the proposed `MetaProperty` node type, the runtime `import['meta']` may not be intended to be supported.

**Comment by jdalton** [comment]
> Wondering if the `import['meta']` should work as well (or generally `key = 'meta'; import[key]`)? 
> Though because of the proposed `MetaProperty` node type, the runtime resolved `import['meta']`may not be intended to be supported.

Right, it's just like `new.target` is valid but not `new['target']`. These aren't real objects they're just fancy syntax. If ya dig you can test `import.meta.url` in Chrome 64 *(without experimental flags)*.
