### ISSUE TITLE
Wallaby shows obvious compilation errors in the test as passing

### ISSUE THREAD

**Issue by tonyxiao** [wallabyjs/public#1471]
### Issue description or question

So wallaby reports `false` to equal to `true`, not to mention that this file shouldn't even compile, yet wallaby reports it to be passing. 

![image](https://user-images.githubusercontent.com/696842/35159419-0a161ec8-fcef-11e7-974f-2da8eb4958f2.png)

I started with the wallaby (typescript sample project)[https://github.com/wallabyjs/wallaby-typescript-sample/] and essentially just messed around with the greeterNodeSpec.ts file. Here's the delta

![image](https://user-images.githubusercontent.com/696842/35159286-8c68ba30-fcee-11e7-9bc3-a66a782c2240.png)

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

  return {
    files: [
      'src/*Browser.ts'
    ],

    tests: [
      'test/*BrowserSpec.ts'
    ]
  };
};

```

### Code editor or IDE name and version

Visual Studio Code Version 1.19.2 (1.19.2)

### OS name and version

OSX 10.13.2 (17C88) (High Sierra)

**Comment by ArtemGovorov** [comment]
Thanks for the report. 

It looks like there's an issue with the latest Jasmine (that was released 2 days ago). If you get the [latest version of the sample project](https://github.com/wallabyjs/wallaby-typescript-sample/) now, and run `npm install`, it should work for you.

**Comment by ArtemGovorov** [comment]
Jasmine 2.9 support had been implemented in Wallaby Core as well now (there was a breaking change that landed in Jasmine a day ago). You may update (if it hasn't happened automatically yet) to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, and the cloned repo will work for you as is (with Jasmine 2.9 installed).

**Comment by tonyxiao** [comment]
Got it. on a slight tangent it's a bit confusing that a test itself can fail while the `it()` line shows up as green in the gutter.

**Comment by tonyxiao** [comment]
<img width="815" alt="cloudapp annotation 2018-01-20 at 09 19 13 png" src="https://user-images.githubusercontent.com/696842/35186063-03131fa2-fdc3-11e7-9ef0-ffbb13a2e5ea.png">
This is the case even on the sample video on homepage

**Comment by ArtemGovorov** [comment]
Yes, it's correct and is working as expected. These indicators are [code coverage indicators](https://wallabyjs.com/docs/intro/get-started-vscode.html#coverage-indicators) that also show error path/error source.

The statement `it('...', () => ...)` is executed successfully without an error, that is why it is green. If there's an error when executing the statement, then it becomes red.

![ind](https://user-images.githubusercontent.com/979966/35189316-a85e1b58-fe93-11e7-94cf-2dc9c2063200.gif)

**Comment by tonyxiao** [comment]
Got it, thanks super helpful, thanks!
