### ISSUE TITLE
[Storyshots] throwing "​​SyntaxError: Invalid or unexpected token​​"

### ISSUE THREAD

**Issue by thehig** [wallabyjs/public#1472]
### Issue description or question

I'm using create-react-app with material-ui and storyshots. My tests are passing when run from jest cli, however when I run the tests through wallaby I get the following error:

```
[truncated]\node_modules\typeface-roboto\index.css:2​​
​​@font-face {​​
​​^​​
​​​​
​​SyntaxError: Invalid or unexpected token​​
```

> Sidenote: I was getting a similar SyntaxError for the "import" keyword, but I solved this by extracting and applying the `babelCompiler` to the config file manually, as well as including `.storybook/**/*.js` in my files.

A few of the things I've tried/researched:

* [Wallaby Jest Storyshots Example](https://github.com/alinvdumitru/wallaby-jest-storyshots-example)
* [Wallaby Webpack CSS Imports](https://github.com/yanivefraim/wallaby-webpack-es6-react-css-imports/blob/master/wallaby.js)
* [Support Storybook Storyshots](https://github.com/wallabyjs/public/issues/1249)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  // Babel, jest-cli and some other modules are located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require("path");
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, "node_modules") +
    path.delimiter +
    path.join(__dirname, "node_modules/react-scripts/node_modules");
  require("module").Module._initPaths();

  // Babel needs this
  process.env.NODE_ENV = "development";

  var babelCompiler = wallaby.compilers.babel({
    babel: require("babel-core"),
    presets: ["react-app"]
  });

  return {
    files: [
      "src/**/*.js",
      "src/**/*.jsx",
      "src/**/*.snap",
      "!src/spec/**/*.spec.js",
      "src/**/*.stories.js",
      ".storybook/**/*.js"
    ],
    tests: [
      "src/spec/**/*.spec.js"
    ],
    env: { type: "node", runner: "node" },
    compilers: {
      "**/*.js": babelCompiler,
      ".storybook/**/*.js": babelCompiler
    },
    setup: wallaby => {
      wallaby.testFramework.configure({
        // as in node_modules/react-scripts/utils/createJestConfig.js
        moduleNameMapper: {
          "^.+\\.(jpg|jpeg|png|gif|svg)$": require.resolve(
            "react-scripts/config/jest/fileTransform.js"
          ),
          "^.+\\.css$": require.resolve(
            "react-scripts/config/jest/cssTransform.js"
          )
        }
      });
    },
    testFramework: "jest"
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.20.0-insider

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
It looks like the configured css transform doesn't get applied, and Jest is trying to load the `node_modules\typeface-roboto\index.css` as JavaScript without applying the `react-scripts/config/jest/cssTransform.js`.

Could you please share the code that imports/uses the `node_modules\typeface-roboto\index.css` module? Or better, if you could create a sample repo demonstrating the issue, I'm confident I could come up with a solution for your very fast in this case. The sample repo doesn't need to contain your real tests/app code, I think a dummy test importing the `typeface-roboto` the way you do it in your real app will suffice to reproduce the issue.

**Comment by thehig** [comment]
I've created a project [here](https://github.com/thehig/storyshots-css-wallaby) that demonstrates the problem in its minimal form

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo! 

Looks like in your wallaby config the `moduleNameMapper` setting is used instead of `transform`, that's why the required CSS transform is not applied. Not sure where it came from, maybe from earlier versions of Wallaby config for CRA (that had been updated since then). If you replace `moduleNameMapper` with `transform`, the error will disappear (there'll be another one because of the missing `.svg` pattern in `files`).

If you use the latest [wallaby config for CRA](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app), it should just work. I have sent you [the pull request](https://github.com/thehig/storyshots-css-wallaby/pull/1) to make it work.

**Comment by thehig** [comment]
Thank you very much for the assistance. I must have copied my wallaby config from an old project :hodor:
