### ISSUE TITLE
How to run @std/esm with ava?

### ISSUE THREAD

**Issue by Lichtjaeger** [wallabyjs/public#1474]
### Issue description or question
In reference to #1468 and standard-things/esm#240.
Thank you for your work and sorry that I steal your time again.
Wallaby is now running but it doesn't run any tests.

The only green marker is in the first line of the test: `import test from 'ava'`. All other markers are white.

I've uploaded a small [test repo](https://github.com/Lichtjaeger/test-wallaby-esm-ava).

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      '**/*.mjs',
    ],

    tests: [
      'test/**/*.test.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'ESM_OPTIONS=cjs',
        runner: `-r ${require.resolve("@std/esm")}`,
      },
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'ava',

    debug: true,
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.19.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Hey, looks like when running with `@std/esm` some of our AVA integration is broken. I have asked [here](https://github.com/wallabyjs/public/issues/1468#issuecomment-359390233) how we can fix it, as soon as we find the way, I'll publish an update.

**Comment by ArtemGovorov** [comment]
`@std/esm` v0.20.0 [has been published](https://github.com/wallabyjs/public/issues/1468#issuecomment-361019584), so now after updating the `@std/esm` in your project, wallaby should work without any changes to the config.

**Comment by Lichtjaeger** [comment]
I can confirm it works.
