### ISSUE TITLE
Allow Live Comments to show both evaluated result and performance 

### ISSUE THREAD

**Issue by bbugh** [wallabyjs/public#1475]
### Issue description or question
 
Wallaby is amazing, I wish it worked for all of the other platforms I use. The Live Comments are especially awesome for live testing and code writing, wow.

However I have one small feature request that would make them even better - show both the value and the result (or at least allow `/* ? */` and `/* ?. */` to be cumulative). Currently it just uses whichever one is first on the line.

This is especially helpful for doing performance testing between several methods, to ensure they're returning the same result *and* comparing performance.

<img width="415" alt="pasted_image_1_22_18__9_22_am" src="https://user-images.githubusercontent.com/438465/35228572-aabe1a42-ff56-11e7-8a94-69941f80c0be.png">

(This is in VSCode 1.19.2 (1.19.2) on MacOS Sierra)

**Comment by ArtemGovorov** [comment]
The feature is implemented in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

Now you may use the execution time reporting comment and add to it any expression that you may use in live comments to display both an expression execution time and execution result.

For example,
```
a() //?. $    result_from_a, 0.004ms
```
displays `a()` execution time and result.

**Comment by bbugh** [comment]
Amazing! What a turnaround time! Thank you so much, it works great.
