### ISSUE TITLE
regexp running error

### ISSUE THREAD

**Issue by ft1996** [wallabyjs/public#1476]
![jietu20180123-035515](https://user-images.githubusercontent.com/18325669/35241371-42040ade-fff1-11e7-9a57-90d41992eb12.jpg)

wallaby.js
`module.exports = () => {
  return {
    files: [
      'style/*.css',
      'png/*.png',
      '*.html',
      'code/*.js',
      'src/*.js'
    ],
    tests: [
      'test/*.js'
    ],
    debug: true,
    env:{
      kind:'chrome'
    }
  };
};`

**Comment by ArtemGovorov** [comment]
Hi, the result on the screenshot looks correct to me. Let me know if the issue is still valid for you, and in this case please describe what the error is and the expected behaviour.
