### ISSUE TITLE
Tests in Wallaby App not ordered

### ISSUE THREAD

**Issue by oliversalzburg** [wallabyjs/public#1479]
When I go to https://wallabyjs.com/app/#/tests to watch a live view of my tests, the order the files are in constantly changes. This is confusing.

Also, the tree nodes constantly collapse, requiring me to expand them again. This is incredibly frustrating.

**Comment by NikGovorov** [comment]
Hi @oliversalzburg,

Thanks for the report. We fixed the issues in v1.0.49.
