### ISSUE TITLE
[Jest] Big dependency list increases Wallaby response time to 20s for a tiny test

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#148]
Reproducible in https://github.com/endragor/wallaby-jest-sample

Make a change in `console.log` statement in `sum-test.js` and observe it takes about 20 seconds for Wallaby to show the updated output. The test itself takes 5ms, according to Wallaby.
Jest runs it for ~1.5s, including ramp up time.

Don't forget to run `npm install`. You'll get node_modules folder that is about 300 MB in size.

**Comment by endragor** [comment]
I think I wasn't able to reproduce this last week. Right now Wallaby is just unusable for me because of such huge run time - it's faster to run the test from command line.

Though last week I was getting "errno 23" errors from Wallaby pretty often when it tried to process the `node_modules` folder. That errno means reaching limit of open file handles. I had to relaunch Wallaby after that.

**Comment by ArtemGovorov** [comment]
Thanks for the sample. I'm looking into it.

**Comment by ArtemGovorov** [comment]
Ok, I think have found the issue and fixed it. Before I publish it could you please check something for me? It looks like fixing this issue brings back this one - https://github.com/wallabyjs/public/issues/121. But an interesting thing is that Jest CLI without also behaves exactly the same way for me: it also throws `Object function CallbackQueue(){return mockConstructor.apply(this,arguments);} has no method 'getPooled'` error. So I'm actually not sure if my 'fix' was even supposed to be there. Could you please have a look to make sure that running the sample from https://github.com/wallabyjs/public/issues/121 work in your Jest CLI without wallaby? If it does work, I'll keep looking how to fix it before publishing the performance issue fix.

**Comment by ArtemGovorov** [comment]
Here is what happens:
![w](https://cloud.githubusercontent.com/assets/979966/8028971/3de92f7e-0dfa-11e5-9a2f-1877fa28da87.gif)

**Comment by endragor** [comment]
Indeed, the error from #121 appears even if you directly run Jest right now. I'm sure though it didn't appear from Jest the time I filed #121.

Anyway, I think it's fine to apply the fix so that the error occurs from Wallaby, if it also occurs when running Jest directly.

**Comment by ArtemGovorov** [comment]
Published the fix, core 1.0.62. Should waaaay better now.

> #121

I have noticed that changing the order to
``` JavaScript
jest.autoMockOff();
require('react');
jest.mock('keymaster');
```
makes it work everywhere, so perhaps could be the solution if you hit the issue.

**Comment by endragor** [comment]
Thanks! I'm not getting the error in the real project.

**Comment by ArtemGovorov** [comment]
Is the performance better now?

**Comment by endragor** [comment]
Yes, it is.
