### ISSUE TITLE
​​Uncaught ReferenceError with Custom Types

### ISSUE THREAD

**Issue by AustinMatherne** [wallabyjs/public#1481]
I'm running into the following error when running wallaby on projects that reference custom TypeScript types. Karma (npm test) doesn't throw these exceptions.

```
Uncaught ReferenceError: users_types_1 is not defined​​ at apps/app/src/app/users/users.component.ts:9​
```

Here's a small example Angular repo with the exception:
https://github.com/AustinMatherne/wallaby-type-error

And a PR that changes the type to an interface (which resolves the exception thrown by wallaby):
https://github.com/AustinMatherne/wallaby-type-error/pull/1/files

### Code editor or IDE name and version

Visual Studio Code v1.19

### OS name and version

OSX 10.13

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo!
I have sent you the [pull request](https://github.com/AustinMatherne/wallaby-type-error/pull/2) to make it work. By default wallaby [changes some TS compiler settings](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) to make the compilation as fast as possible, but in your case you need standard defaults.
