### ISSUE TITLE
Treeview node expansion is cumbersome

### ISSUE THREAD

**Issue by oliversalzburg** [wallabyjs/public#1482]
In the Wallaby app, nodes in the treeview can only be expanded when clicking directly on the + icon. This is cumbersome, especially on large monitors and *especially* since the view collapses all nodes when it rebuilds itself.

Some `:hover` styling on those nodes would also go a long way in finding the icons that correlate to a given node. This is a long distance:
![image](https://user-images.githubusercontent.com/1658949/35339288-8020a34c-0120-11e8-8425-cd147d0bbcea.png)

**Comment by ArtemGovorov** [comment]
> In the Wallaby app, nodes in the treeview can only be expanded when clicking directly on the + icon. 

The tree is actually keyboard friendly and everything you can do with a mouse (and more) you can do with a keyboard as well. For example, on Windows you may press `right arrow` to expand a node level, `Ctrl + right arrow` to fully expand a node, or `Ctrl + Shift + right arrow` to fully expand the whole tree. Similar shortcuts with `left arrow` will collapse opened node(s).

Other node actions also have keyboard shortcuts. Please take a look [into the tutorial](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#tests) for all shortcuts.

Also the distance between the text and icons of the node can be reduced by resizing test tree panel (by dragging the grey border between the tree view and details view).

**Comment by oliversalzburg** [comment]
Given that adjustments to the layout don't persist, they are pointless.

Having great keyboard support is also pointless if I'm using the mouse. Which I have to do at least to resize the mentioned splitter. If anything, having to switch inputs methods is *more* frustrating than aiming for the tiny expand icon in the first place.

**Comment by ArtemGovorov** [comment]
Fair enough, reopening the issue.

Could you please share your vision of how the mentioned UX features would work best for you? Like what would be the ideal way for them to work in your opinion?

**Comment by fvanwijk** [comment]
@oliversalzburg
A lot of people use mouse and keyboard simultaneously, especially when they work on a laptop with trackpad. So stating that switching input methods *is* frustrating might be just *your* point of view.

Regarding the tiny interface elements in a high res screen such as the expand/collapse buttons, you could zoom in a little with `Ctrl` `Shift` `=`. This is how you would do it too in a web based editor such as VSCode or Atom.

Persisting the collapse state of the tree would be a good enhancement indeed.

Generally, in respect to some recent GH issues you opened, I think you should adjust you tone of voice a little. Words like 'frustrating', 'cumbersome', 'pointless' are not really stimulating the authors in making a great(er) product.

**Comment by oliversalzburg** [comment]
@fvanwijk I like my reports to be on point. When something is frustrating, I want to communicate that fact directly and clearly. I can understand if people don't respond well to that, but I have wasted a lot of time in my life writing "nice" issue reports that went nowhere. I rather save my time and let people know that their solution is not working for *me*.

Which brings me to your other point. Yes, I realize that I am complaining for my own benefit and not for that of the larger user community, but I don't care. I paid for this product so that it furthers my personal workflow, not that of the community.

It is my understanding that Wallaby is a tool that has the ability to have a huge impact on workflow when working with tests and initial trials have confirmed this. The biggest benefit, in my opinion, are the turnaround times. This results in a much higher trough- and output.
When I see apparently minor details that have a negative impact on the perceived speed at which I can work, then those "speed bumps" can become a major annoyance fairly quickly. Especially when you run into them dozens of times a day and when the apparent fix seems so obvious and easy to implement.

Here, I added a quick `.summary-table:hover : #444` rule:
![image](https://user-images.githubusercontent.com/1658949/35670026-6638c79e-0737-11e8-8034-71f3aad63158.png)

Say what you want, I find that very helpful when navigating a large tree and trying to find the icons that relate to a specific file name. An action that would otherwise require me to select the node by clicking. But clicking and selecting it also has additional behavior, which I might not even want at that point.

You don't have to bring up that people work on laptops or have an otherwise keyboard-centric workflow when we're talking about a change that literally takes seconds to implement and has no apparent negative impact.

Regarding the expand/collapse, why not tie the toggling behavior of the tree node to click events on the entire node? The difference is also incredibly minor and the only valid reason I am aware of is allowing text selection of the label on the node. But I don't see how that would be a more important use case here than toggling the collapse state of the node. Which is something you constantly have to do, as the tree collapses itself constantly.

Either my workflow is somehow conflicting with the intended use scenario thought out for Wallaby, but the constant collapsing of the tree should be an obvious issue to anyone who has worked with the product for a day.

Experiences like this have such a negative impact on the perceived quality of the product that it makes me question if purchasing it was even the right choice in the first place and it definitely makes me reconsider equipping more developers with a license. So, in that regard, I feel it is perfectly fine to make it clear how I feel about that experience.

Please don't see my rant as an invitation for a larger discourse. I would like to see my mentioned points addressed by changes in the software, but I have no interest in debating the validity of these points.

**Comment by ArtemGovorov** [comment]
@oliversalzburg Thanks for your feedback.

> Some `:hover` styling on those nodes would also go a long way in finding the icons that correlate to a given node.

This shouldn't be too hard to implement.

> why not tie the toggling behavior of the tree node to click events on the entire node? 

This doesn't sound like a good idea to me. Clicking already displays node details, so overloading it with an additional action may be confusing/undesirable.

I'd rather address this issue `constant collapsing of the tree`. At the moment, when a test file structure changes (ie. not a individual test changes, but certain actions may cause it), we do redraw the tree, and may definitely put some better heuristics in to re-open the previous state if it is possible. This shouldn't be too hard to implement too.

> Either my workflow is somehow conflicting with the intended use scenario thought out for Wallaby

From what we have seen our users doing, Wallaby App (as opposed to Wallaby plugin to your editor) is frequently used for reporting/analytics purposes, rather than something used at the same time with the plugin when actively coding. So I would say your workflow is not typical for the majority of our use cases, but it doesn't mean that we will not consider your feedback - it is always welcomed (we can't make any promises on ETA though).

> Experiences like this have such a negative impact on the perceived quality of the product that it makes me question if purchasing it was even the right choice in the first place and it definitely makes me reconsider equipping more developers with a license.

If the purchase was made less than 30 days ago and the tool is not meeting your expectations, we are happy to make a full refund and de-activate your license. Just send us a quick email to hello@wallabyjs.com and we'll arrange it for you.

**Comment by ArtemGovorov** [comment]
> Some `:hover` styling on those nodes would also go a long way in finding the icons that correlate to a given node.

Implemented in Wallaby.js App v1.0.35.

**Comment by NikGovorov** [comment]
Hi @oliversalzburg,

We addressed most of the issues discussed here in the recent releases of Wallaby.js App. Could you please try v1.0.49? 

I'm closing the issue for now, please feel free to create new issues if you'll find any other bugs.

Thanks.

**Comment by oliversalzburg** [comment]
Sorry, but I stopped using this product back then. I'm sure you'll understand that 1 year is a bit of a stretch to wait for a bugfix.

**Comment by ArtemGovorov** [comment]
@oliversalzburg No worries, sorry to see you go, we do nevertheless appreciate your original feedback on the issue.
