### ISSUE TITLE
Wallaby + jest + enzyme

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1483]
### Issue description or question

Hi, I cannot make wallaby work with jest + enzyme. It must have something to do with jest running a separate virual instance for each test. With the config below I still keep getting errors:

```
​​Error: ​​
    ​​      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To​​
    ​​      configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`​​
    ​​      before using any of Enzyme's top level APIs, where `Adapter` is the adapter​​
```

### Wallaby.js configuration file

```javascript
// const transform = require("fuse-test-runner").wallabyFuseTestLoader;
const path = require('path');

module.exports = function(wallaby) {
  // var load = require;

  return {
    files: [
      'tsconfig.json',
      'src/**/*.ts*',
      'src/**/*.snap',
      '!src/**/*.test.ts*'
    ],
    tests: [
      'src/**/*.test.ts*'
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ jsx: 'react', module: 'commonjs' })
    },
    env: {
      type: 'node'
    },
    testFramework: 'jest',
    setup: function(wallaby) {
      console.log("Configuring ...");

      if (!global.document) {
        require('jsdom-global')();
      }

      const Enzyme = require('enzyme');
      const Adapter = require('enzyme-adapter-react-16');

      Enzyme.configure({ adapter: new Adapter() });
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
> It must have something to do with jest running a separate virual instance for each test.

Yes, you are absolutely correct. Jest is running tests in its own context, and any global state you set in `setup` function doesn't apply there.

You may use [Jest `setupFiles`](https://facebook.github.io/jest/docs/en/configuration.html#setupfiles-array) for this purpose. Those should run in correct contexts, and don't require any additional configuration from wallaby side.

**Comment by ivanbaj** [comment]
Is there a working example for React 15, enzyme, jest? I keep getting this error:

 Runtime error: TypeError: Super expression must either be null or a function, not undefined​​
​​[Error]   ...node_modules/enzyme-adapter-react-15/build/ReactFifteenAdapter.js:51:113)​​

I am using this:

import Enzyme, { shallow, mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-15';
Enzyme.configure({ adapter: new Adapter() });

And my config file:

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.jsx',
      'src/**/*.js',
      '!src/**/__tests__/*.test.js?(x)'
    ],
    tests: [
      'src/**/__tests__/*test.js?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },

    testFramework: 'jest',

    debug: true
  };
};

**Comment by ArtemGovorov** [comment]
@ivanbaj Have you tried any hints from this thread https://github.com/airbnb/enzyme/issues/1172? If nothing from there helps, please create and share a sample repo where we can reproduce the issue, happy to have a look and help.
