### ISSUE TITLE
Jest/Typescript/VSC "Test framework [jest] is not supported​​"?

### ISSUE THREAD

**Issue by ivebencrazy** [wallabyjs/public#1484]
### Issue description or question
Hi! First time trying out wallaby.js (using trial mode).
When I try running Wallaby, I keep getting this message in the Wallaby.js Console:
`​​[Error] Failed to load configuration file:  Test framework [jest] is not supported​​`
Wondering if I'm doing something wrong? I'm running a Jest and Typescript repo in Visual Studio Code.
Thanks! :)

### Wallaby.js configuration file
```javascript
module.exports = function (wallaby) {
    return {
        files: [
            "tsconfig.json",
            "source/**/*.ts"
        ],
        tests: [
            "source/**/*.test.ts"
        ],
        testFramework: "jest",
    };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.19.2
Wallaby v1.0.75
Wallaby.js Core v1.0.544

### OS name and version
OSX 10.11.6

**Comment by ivebencrazy** [comment]
Ah! I didn't realize that I needed this:
```   
env: {
  type: 'node',
  runner: 'node'
},
```

Does just only run in a node env?

**Comment by ArtemGovorov** [comment]
> Does Jest only run in a node env?

Correct, Jest only runs in node (generally, not only when running from Wallaby).
