### ISSUE TITLE
REJECTED_REQUEST error

### ISSUE THREAD

**Issue by grimkor** [wallabyjs/public#1485]
### Issue description or question
Receiving the following error in the wallaby.js console:

```
​​[Error] Runtime error: REJECTED_REQUEST​​
​​[Error] Runtime error: REJECTED_REQUEST​​
​​[Error] Runtime error: Error: Your test suite must contain at least one test.​​
​​[Error]     at onResult (c:\node_projects\reddit-feed\node_modules\react-scripts\node_modules\jest\node_modules\jest-cli\build\TestRunner.js:110:20)​​
​​[Error]     at promise.then.then.result (c:\node_projects\reddit-feed\node_modules\react-scripts\node_modules\jest\node_modules\jest-cli\build\TestRunner.js:204:20)​​
​​[Error]     at <anonymous>​​
```

Using the create-react-app config file provided and only runs tests if you make an error in a test and revert it. It will then run all tests in the corresponding test file but not others.

Happens with this project on both my laptop and desktop, VSCode is the most recent release.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

	// Babel, jest-cli and some other modules may be located under
	// react-scripts/node_modules, so need to let node.js know about it
	var path = require('path');
	process.env.NODE_PATH +=
	  path.delimiter +
	  path.join(__dirname, 'node_modules') +
	  path.delimiter +
	  path.join(__dirname, 'node_modules/react-scripts/node_modules');
	require('module').Module._initPaths();
  
	return {
	  files: [
		'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
		'!src/**/*.test.js?(x)'
	  ],
  
	  tests: ['src/**/*.test.js?(x)'],
  
	  env: {
		type: 'node',
		runner: 'node'
	  },
  
	  compilers: {
		'**/*.js?(x)': wallaby.compilers.babel({
		  babel: require('babel-core'),
		  presets: ['react-app']
		})
	  },
  
	  setup: wallaby => {
		const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
		Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
		delete jestConfig.testEnvironment;
		wallaby.testFramework.configure(jestConfig);
	  },
  
	  testFramework: 'jest'
	};
  };
```

### Code editor or IDE name and version

Visual Studio v1.19.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> `Runtime error: REJECTED_REQUEST​​`

We have never see the issue like this before. If I create a new app with the latest `create-react-app`, paste your config and run wallaby, then everything is working for me.

There must be something your project specific that is causing the issue. Please try specifying less test paths by editing `tests: ['src/**/*.test.js?(x)'],` to find out what test file(s) is causing the issue. Once it the test file is found, please create a sample repo demonstrating the issue (I think imports of the test fie will be sufficient to reproduce the issue).

**Comment by grimkor** [comment]
Went through the tests and found the erronous code. I'll attach just the file as I think it's sufficient to repoduce. The error appears to be that wanting to a run a test against a rejected promise with `Promise.reject({message: 'REJECTED_REQUEST'})` (line 25)  is causing the error but only if the test is testing against the `Promise.resolve()` (line 17).

```javascript 
import * as actions from '../../actions/submission_actions';
import * as TYPES from '../../actions/types';
import moment from 'moment';
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';

describe('Submission Actions', () => {
	let mockApi;
	let token;
	let resolvedSubreddits;
	let rejectedRequest;
	let mockStore;
	let store;

	beforeEach(() => {
		mockApi = jest.fn();
		resolvedSubreddits = Promise.resolve({
			data: {
				data: {
					children: [{ data: { id: 'ID_1', display_name: 'DISPLAY_NAME_1' } }]
				}
			}
		});

		rejectedRequest = Promise.reject({ message: 'REJECTED_REQUEST' });

		token = {
			refresh_token: 'REFRESH_TOKEN',
			access_token: 'ACCESS_TOKEN',
			expires_at: moment().unix(),
			scope: 'read identity'
		};
		mockStore = configureMockStore([thunk]);
		store = mockStore({});
	});

	it('should request reddit submissions', done => {
		mockApi.mockReturnValue(resolvedSubreddits);

		token.expires_at = token.expires_at + 1000;
		store.dispatch(actions.getSubmissions(token, mockApi));
		process.nextTick(() => {
			expect(mockApi).toHaveBeenCalled();
			expect(true).toEqual(true);
			done();
		});
	});

	it('should dispatch an error on failed request', () => {
		mockApi.mockReturnValue(rejectedRequest);
		store.dispatch(actions.getSubmissions(token, mockApi));
		process.nextTick(() => {
			expect(store.getActions()[0]).toEqual(
				expect.objectContaining({
					type: TYPES.GET_SUBMISSIONS_ERROR,
					payload: expect.any(String)
				})
			);
		});
	});
});

```

**Comment by ArtemGovorov** [comment]
Thanks for the code sample. 

One thing I may suggest trying is turning off wallaby default behaviour of [treating unhandled promise rejections as errors](https://wallabyjs.com/docs/config/overview.html#unhandled-promise-rejections):

```diff
module.exports = function (wallaby) {
	return {
	  ...
+         reportUnhandledPromises: false
	};
  };
``` 

If it doesn't help, I may need some more context from you. I tried to reproduce it by removing/mocking some things like `../../actions/submission_actions` dependency:

```javascript
describe('Submission Actions', () => {
  let mockApi = {mockReturnValue: v => (store._v = v)};
  let rejectedRequest;
  let store = {dispatch: () => {store._v.then()}, getActions: () => [{type: '', payload: ''}]};

  beforeEach(() => {
    rejectedRequest = Promise.reject({ message: 'REJECTED_REQUEST' });
  });

  it('should dispatch an error on failed request', () => {
    mockApi.mockReturnValue(rejectedRequest);
    store.dispatch();
    process.nextTick(() => {
      expect(store.getActions()[0]).toEqual(
        expect.objectContaining({
          type: '',
          payload: expect.any(String)
        })
      );
    });
  });
});
```

However the sample works ok for me, so I must be missing something. Could you please create a sample without dependencies (or include sufficient dependencies)?

**Comment by grimkor** [comment]
Hey @ArtemGovorov ,

Apologies been away and not able to reply. I spent a quick time this morning creating a very simplified version of the problem and how to trigger it on/off.
```javascript
describe('Wallaby test', () => {
	let mockApi;
	let resolvedRequest;
	let rejectedRequest;

	beforeEach(() => {
		mockApi = jest.fn();
		resolvedRequest = Promise.resolve({ message: 'SUCCESSFUL_REQUEST' });
		rejectedRequest = Promise.reject({ message: 'REJECTED_REQUEST' });
	});

	it('should give an example', () => {});
});
```

Commenting out `rejectedRequest` removes the error in the next run it does and re-introducing the line will bring the error back into the next run of tests.

I have added `reportUnhandledPromises: false` to my configuration file and it works a treat. Thank you for that.

**Comment by ArtemGovorov** [comment]
> Commenting out `rejectedRequest` removes the error in the next run it does and re-introducing the line will bring the error back into the next run of tests.

Great, thanks for the update. 
It means that you have an unhandled promise rejection, and by default Wallaby does not tolerate them, because in [future versions of Node your test run may simply be terminated](http://thecodebarbarian.com/unhandled-promise-rejections-in-node.js.html). 
Jest may not be reporting it, and it may not be an issue for now, but may be an issue in future. 

For example, if you create a node program like
```javascript
var rejectedRequest = Promise.reject({ message: 'REJECTED_REQUEST' });
```
you'll, get this output:
```
(node:25423) UnhandledPromiseRejectionWarning: #<Object>
(node:25423) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25423) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The proper fix is very simple:

```diff
rejectedRequest = Promise.reject({ message: 'REJECTED_REQUEST' });
+rejectedRequest.catch(() => {});
```

This way you'll be ok in future versions of node and don't have to suppress unhandled promise rejections in wallaby with the `reportUnhandledPromises` (because there'll be no unhandled promise rejection as you are handling it).

Hope it makes sense.
