### ISSUE TITLE
Prompt for license key issue

### ISSUE THREAD

**Issue by RaviVaranasi** [wallabyjs/public#1488]
### Issue description or question

VS Code prompts for license key everytime

<img width="1203" alt="image001" src="https://user-images.githubusercontent.com/51507/35474916-c88dbcd2-035a-11e8-8bca-66f78f6a614b.png">

After entering the license key, see the confirmation, but it prompts for license key again after restart.

<img width="1190" alt="preferencebuttonnoimage_js_ _design-tools" src="https://user-images.githubusercontent.com/51507/35474922-e80c1fa4-035a-11e8-930b-888e9477355b.png">

### Code editor or IDE name and version

Visual Studio Code 1.19.3 (1.19.3)
Plugin Version: 1.0.75

### OS name and version

MacOSX Sierra

**Comment by ArtemGovorov** [comment]
This most likely means that you are not entering the full key. Please double check that you are entering the full key that had been sent to you. 

If after you checked the key, it still doesn't work, please send us the exact key you're trying to enter to hello@wallabyjs.com and we'll sort it out for you.
