### ISSUE TITLE
Can't find variable: module

### ISSUE THREAD

**Issue by Nembus** [wallabyjs/public#149]
I'm getting this error even though I am using babel compiler, am including the said module (node_module flux) in the file list, and am using webpack. What I want to do is use react + es6 + webpack with es6 syntax. I see example repos for all three but not all together.

**Comment by ArtemGovorov** [comment]
You don't need to include the module in the file list, wallaby.js uses your local node_modules.

I have created [the example of using react + es6 + webpack](https://github.com/wallabyjs/wallaby-webpack-es6-react) and I'm referencing flux module from the JSX component. 

Please let me know if it works for you.

**Comment by Nembus** [comment]
I'm using alt and when I do:
//in alt.js file
var Alt = require('alt'); Cannot find module "flux"
var alt = new Alt();

module.exports = alt;

It looks like wallabyjs cannot find the flux dependency in alt.

**Comment by ArtemGovorov** [comment]
Can't reproduce it, here is what I do:
![screen shot 2015-06-10 at 1 21 21 pm](https://cloud.githubusercontent.com/assets/979966/8074310/d19e0530-0f73-11e5-9f79-32368fc6cbe0.png)
Is it reproducible in the repository I have referenced above?

**Comment by Nembus** [comment]
No, not reproducible in your repo.

Here's my wallaby.js config file:

var wallabyWebpack = require('wallaby-webpack');
var babel = require('babel');
var webpack = require('webpack');
var path = require('path');

var wallabyPostprocessor = wallabyWebpack({
      plugins: [
          new webpack.DefinePlugin({
              _PRODUCTION_: true
          }),

          new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
          )
      ],

      resolve: {
          modulesDirectories: [path.join(__dirname, 'node_modules'), path.join(__dirname, 'bower_components')],
          extensions: ["", ".js", ".jsx"]
      }
  }
);

module.exports = function (wallaby) {
    'use strict';
    return {
        // set `load: false` to all of source files and tests processed by webpack
        // (except external files),
        // as they should not be loaded in browser,
        // their wrapped versions will be loaded instead
        files: [
            'src/styles/*.scss',
            {pattern: 'node_modules/react-tools/src/test/phantomjs-shims.js', instrument: false},
            {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
            {pattern: 'node_modules/chai/chai.js', instrument: false},
            {pattern: 'src/**/*.js*', load: false},
            {pattern: 'src/styles/*.css', load: false},
            {pattern: 'test/spec/**/*.*', ignore: true}
        ],

        tests: [
            {pattern: 'test/spec/**/*.*', load: false}
        ],

        compilers: {
            'src/**/*.js*': wallaby.compilers.babel({
                babel: babel,
                // other babel options
                stage: 0    // https://babeljs.io/docs/usage/experimental/
            }),

            'test/spec/**/*.js': wallaby.compilers.babel({
                babel: babel,
                // other babel options
                stage: 0    // https://babeljs.io/docs/usage/experimental/
            })
        },


        testFramework: "mocha@2.0.1",

        postprocessor: wallabyPostprocessor,

        debug: true,

        bootstrap: function (wallaby) {
            var mocha = wallaby.testFramework;
            mocha.ui('bdd');
            window.expect = chai.expect;
            var should = chai.should();
            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        }
    };
};

**Comment by ArtemGovorov** [comment]
Could you please also share your package.json?

**Comment by ArtemGovorov** [comment]
Ok, I think I have found the issue. In your config file, you'll need to add `node_modules` to the modules directory of webpack config:

```
modulesDirectories: [
  path.join(__dirname, 'node_modules'), 
  'node_modules', 
  path.join(__dirname, 'bower_components')
]
```

Please note that you probably don't need to override `modulesDirectories` at all if you're not using bower components. You also probably don't need a few other things. If I'm not mistaken, you've used the config example from one of wallaby.js sample repositories and that repo was created to address some specific issues with another user setup, so it contains lots of stuff you may not need.

**Comment by Nembus** [comment]
Yes! That did it! I will try to remove the modulesDirectories entry.

Thanks Artem.

**Comment by Nembus** [comment]
Hi Artem, for some reason I am getting 'Cannot find module "normalize.css"' in the same project. Should css modules in node_modules be treated any differently?

**Comment by ArtemGovorov** [comment]
@Nembus Not sure what's the reason, happy to have a look, how can I reproduce the issue?

**Comment by Nembus** [comment]
You can npm install normalize.css and then import/require it in Label.jsx (in your repo).

**Comment by ArtemGovorov** [comment]
Works for me (perhaps you're missing webpack css loader?):
![screen shot 2015-06-11 at 1 06 42 pm](https://cloud.githubusercontent.com/assets/979966/8099040/e3e22ea2-103a-11e5-8679-fa5bc59cb2e7.png)

**Comment by Nembus** [comment]
Ah. It was the 
module: {
      loaders: [{test: /\.css$/, loader: 'css-loader'}]
    }

I forgot to include that. It works. If you have a webpack based repo, it might be a good idea to add that, since webpack can require individual css modules for each js file.

Thanks again.

**Comment by ArtemGovorov** [comment]
Cool, thanks. Will add it to the sample.

**Comment by Nembus** [comment]
Artem, for completeness sake, can you check if you can require a css file that is not in the node_modules, i.e., in your styles directory. For some reason, wallaby cannot find the main.css (styles/main.css) even with the above loaders modification.

**Comment by ArtemGovorov** [comment]
Most likely the reason is that `main.css` is not in your `files` list. If the file is not in node_modules, it has to be in your `files` list so that wallaby copies it to its cache to serve its testing sandbox page from.
![screen shot 2015-06-11 at 2 19 09 pm](https://cloud.githubusercontent.com/assets/979966/8099735/ea829c42-1044-11e5-9536-698078449c98.png)

**Comment by Nembus** [comment]
I see. But what about preprocessed files like .scss? Do they need to be in the file list as well?

**Comment by ArtemGovorov** [comment]
Yes, they do. Pretty much anything that is used in your tests (except node_modules), has to be listed. 

Though I have a few users who prefer to avoid loading `.scss` files simply because the don't test anything that depends on the fact of loading it and it's more efficient not to include those. They use webpack [IgnorePlugin](http://webpack.github.io/docs/list-of-plugins.html#ignoreplugin) like [suggested here](https://github.com/jeffling/wallaby-webpack#webpack-options) or [NormalModuleReplacementPlugin](http://webpack.github.io/docs/list-of-plugins.html#normalmodulereplacementplugin) to create stubs for `.scss`, like `new webpack.NormalModuleReplacementPlugin(/\.scss$/, path.resolve('./', 'empty-module.js'))`

**Comment by ArtemGovorov** [comment]
Also, as far as I remember, one more reason to avoid loading `.scss` and using ignore plugin or replacement plugin was related to some node.js version conflicts in `sass-loader` and wallaby.

**Comment by Nembus** [comment]
Avoid loading .scss in wallaby or webpack? So if you're testing a React module that depends on the .scss file (which needs post-processing by webpack) are you suggesting to ignore them during the test? Could you please explain this, as I am curious to establish a workflow integrating many of these parts.

**Comment by ArtemGovorov** [comment]
You need to create a file that will be exporting an empty object, for example `empty-module.js` in your root project folder:
``` JavaScript
module.exports = {};
```
Then in wallaby.js configuration for webpack you'll need to add the plugin to redirect all `.scss` require requests to the module.

``` JavaScript
var path = require('path');
var webpack = require('webpack');
...
  var webpackPostprocessor = wallabyWebpack({
    // webpack options
    resolve: {
      extensions: ['', '.js', '.jsx']
    },
    module: {
      loaders: [
        {test: /\.css$/, loader: "css-loader"}
      ]
    },
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/\.scss$/, path.resolve('./', './empty-module.js'))
    ]
  });
```

**Comment by Nembus** [comment]
I see, meanwhile webpack will process .scss as usual and so the styles will show as usual, but for wallaby, it'll be a no-op.

**Comment by ArtemGovorov** [comment]
Yes, exactly.
