### ISSUE TITLE
Get the latest version of wallaby supported by my licence

### ISSUE THREAD

**Issue by rollymaduk** [wallabyjs/public#1491]
### Issue description or question
Hi please I was wondering if I can access the latest version of my wallaby license, which had expired a few months ago. thanks

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
You may download the [latest supported version as described here in the docs](https://wallabyjs.com/license/). Also [forcing wallaby core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) may be sometimes required (depending on the editor that you are using and the way you have installed your current wallaby version).
