### ISSUE TITLE
A large number of output characters are replaced by ...

### ISSUE THREAD

**Issue by ft1996** [wallabyjs/public#1493]
A large number of output characters are replaced by ...
![qq20180202-112241](https://user-images.githubusercontent.com/18325669/35715087-6968540a-080b-11e8-8bd7-5590b2c4d9f5.png)

wallaby.js
`module.exports = () => {
  return {
    files: [
      'style/*.css',
      'png/*.png',
      '*.html',
      'code/*.js',
      'src/*.js'
    ],
    tests: [
      'test/*.js'
    ],
    debug: true,
    env:{
      kind:'chrome'
    },
    maxConsoleMessagesPerTest: 10000
  };
};`

If I want to show all, what should I do?

**Comment by ArtemGovorov** [comment]
You may invoke `Show line test(s)` command from command palette and the output channel will show the full output.
