### ISSUE TITLE
Eventually stopped compiling (Unexpected token import)

### ISSUE THREAD

**Issue by alexander-ossur** [wallabyjs/public#1495]
### Issue description or question
Hello,

Somehow wallaby stopped working for me. What I did is just enabled internet access to Visual Studio, so I think wallaby did some updates (or whatever) which broke the whole process.
It has up to date license. v1.0.33 installed

### Wallaby.js configuration file

```javascript
let setup__ = require ("./src/setup-utils");

module.exports = function (wallaby) {
	return {
		"files": [
			{ pattern: "src/common/src/**/!(*.spec).ts?(x)", load: true },
			{ pattern: "src/server/src/**/!(*.spec).ts?(x)", load: true }
		],
		"tests": [
			{ pattern: "src/common/src/**/*.spec.ts?(x)", load: true },
			{ pattern: "src/server/src/**/*.spec.ts?(x)", load: true }
		],
		
		env: {
			// Server part is always running on Node.js
			type: "node",

			// NOTE: (Alexander)	Seems like Wallaby is using older version of NODE.
			//						So we are going to use ours
			runner: "F:/Program Files/nodejs/node.exe"  // or full path to any node executable
		},

		"testFramework": "mocha",

		debug: true,

		compilers: {
			"*.ts?(x)": wallaby.compilers.typeScript ({
 				 inlineSourceMap: true,
 				inlineSources: true,
 				target: 'ES6',
 				allowSyntheticDefaultImports: true,
 				module: 'commonjs',
 				moduleResolution: 'node',
 				emitDecoratorMetadata: true,
 				experimentalDecorators: true,
 				removeComments: false,
 				noImplicitAny: true,
 				strictNullChecks: true,
 				jsx: 'react' 
  			})
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio v2017

### OS name and version

Windows 8.1

### Cold start log

> wallaby.js started
core v1.0.544
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Wallaby config: C:\Workspace\itrader\wallaby-server.js
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File cache: I:\TEMP\.wallaby\projects\Sr7fvSoGl4Q8UHcupTT2I6s8eeU=\cache
Sat, 03 Feb 2018 22:23:45 GMT wallaby:uiService Listening port 51235
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Config file change detected, invalidating local cache
Wallaby App (realtime reports) is available at: http://localhost:51245
Sat, 03 Feb 2018 22:23:45 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
Sat, 03 Feb 2018 22:23:45 GMT wallaby:workers Starting run worker instance #0
Sat, 03 Feb 2018 22:23:45 GMT wallaby:workers Starting run worker instance #1
Sat, 03 Feb 2018 22:23:45 GMT wallaby:workers Web server is listening at 50741
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/test-suite/server.spec.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/logger.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/orderbook.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/orderbook-definition.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/server.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project File src/server/src/server-definition.ts changes are patches only: false
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/orderbook.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/orderbook-definition.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/server.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/server-definition.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/logger.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Preparing to process src/server/src/test-suite/server.spec.ts
Sat, 03 Feb 2018 22:23:45 GMT wallaby:project Starting processor pool (if not yet started)
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/orderbook.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/orderbook.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/orderbook.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/orderbook.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/logger.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/logger.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/logger.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/logger.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/test-suite/server.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/test-suite/server.spec.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/test-suite/server.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/test-suite/server.spec.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/test-suite/server.spec.ts changes saved, store ts: 636527441743638300, change ts: 1517696625930
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/orderbook.ts changes saved, store ts: 636532551555824400, change ts: 1517696625931
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/logger.ts changes saved, store ts: 636528401495912600, change ts: 1517696625930
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts changes saved, store ts: 636532564205244000, change ts: 1517696625929
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/orderbook-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/server.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/orderbook-definition.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/orderbook-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/orderbook-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/server.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/server.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/server.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/orderbook-definition.ts changes saved, store ts: 636529639609444100, change ts: 1517696625931
Sat, 03 Feb 2018 22:23:47 GMT wallaby:processor No compilers found for src/server/src/server-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/server.ts changes saved, store ts: 636532372174580000, change ts: 1517696625931
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/server-definition.ts is not instrumented by core
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project No preprocessors configured for src/server/src/server-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Writing to disk and caching processed file src/server/src/server-definition.ts
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project File src/server/src/server-definition.ts changes saved, store ts: 636528473683110400, change ts: 1517696625931
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Stopping process pool
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Running postprocessor
Sat, 03 Feb 2018 22:23:47 GMT wallaby:postprocessor New TypeScript language service is required
Sat, 03 Feb 2018 22:23:47 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 7 project files none were found by patterns: *.ts?(x)
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Postprocessor execution finished
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Postprocessor is removed as requested by itself
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Test run started; run priority: 3
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Running all tests
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Starting test run, priority: 3
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Distributing tests between 2 workers
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Running tests in parallel
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Merging parallel test run results
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Test run finished
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Processed console.log entries
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Processed loading sequences
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Processed executed tests
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Processed code coverage
Sat, 03 Feb 2018 22:23:47 GMT wallaby:project Test run result processed and sent to IDE
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Started run worker instance (delayed) #1
Sat, 03 Feb 2018 22:23:47 GMT wallaby:workers Started run worker instance (delayed) #0

### Restart log

> wallaby.js started
core v1.0.544
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Wallaby config: C:\Workspace\itrader\wallaby-server.js
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project File cache: I:\TEMP\.wallaby\projects\Sr7fvSoGl4Q8UHcupTT2I6s8eeU=\cache
Sat, 03 Feb 2018 22:39:29 GMT wallaby:uiService Listening port 51235
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Starting run worker instance #0
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Starting run worker instance #1
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Web server is listening at 50959
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Stopping process pool
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project File cache is up-to-date, starting full test run
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Running postprocessor
Sat, 03 Feb 2018 22:39:29 GMT wallaby:postprocessor New TypeScript language service is required
Sat, 03 Feb 2018 22:39:29 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 7 project files none were found by patterns: *.ts?(x)
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Postprocessor execution finished
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Postprocessor is removed as requested by itself
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Test run started; run priority: 3
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Running all tests
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Starting test run, priority: 3
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Distributing tests between 2 workers
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Running tests in parallel
Sat, 03 Feb 2018 22:39:29 GMT wallaby:workers Merging parallel test run results
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Test run finished
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Processed console.log entries
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Processed loading sequences
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Processed executed tests
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Processed code coverage
Sat, 03 Feb 2018 22:39:29 GMT wallaby:project Test run result processed and sent to IDE
Sat, 03 Feb 2018 22:39:30 GMT wallaby:workers Started run worker instance (delayed) #0
Sat, 03 Feb 2018 22:39:30 GMT wallaby:workers Started run worker instance (delayed) #1

### Made changes in orderbook.spec.ts

> Sat, 03 Feb 2018 22:40:11 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts changes are patches only: false
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Preparing to process src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:40:11 GMT wallaby:processor No compilers found for src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts is not instrumented by core
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project No preprocessors configured for src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Writing to disk and caching processed file src/server/src/test-suite/orderbook.spec.ts
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project File src/server/src/test-suite/orderbook.spec.ts changes saved, store ts: 636532944113570600, change ts: 1517697611363
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Test run started; run priority: 2
Sat, 03 Feb 2018 22:40:11 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Sat, 03 Feb 2018 22:40:11 GMT wallaby:workers Starting test run, priority: 2
Sat, 03 Feb 2018 22:40:11 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #r12in]
Sat, 03 Feb 2018 22:40:11 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #r12in]
Sat, 03 Feb 2018 22:40:11 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #r12in]
Sat, 03 Feb 2018 22:40:11 GMT wallaby:workers [worker #0, session #r12in] Running tests in sandbox
Sat, 03 Feb 2018 22:40:11 GMT wallaby:workers Sandbox (active) [r12in] error: I:\TEMP\.wallaby\projects\Sr7fvSoGl4Q8UHcupTT2I6s8eeU=\cache\instrumented\src\server\src\test-suite\orderbook.spec.ts:3
import * as chai from "chai";
^^^^^^

> SyntaxError: Unexpected token import
Runtime error: .\src\server\src\test-suite\orderbook.spec.ts:3
import * as chai from "chai";
^^^^^^

> SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at C:\Workspace\itrader\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Workspace\itrader\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Workspace\itrader\node_modules\mocha\lib\mocha.js:536:10)
    at WebSocket.emit (events.js:160:13)
    at afterWrite (_stream_writable.js:474:3)
    at onwrite (_stream_writable.js:465:7)
    at InflateRaw.afterTransform (_stream_transform.js:89:3)
    at Zlib.processCallback (zlib.js:588:8)
Sat, 03 Feb 2018 22:40:11 GMT wallaby:workers [r12in] Run 0 test(s), skipped 0 test(s)
Sat, 03 Feb 2018 22:40:11 GMT wallaby:workers [r12in] Sandbox is responsive, closing it
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Test run finished
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Processed console.log entries
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Processed loading sequences
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Processed executed tests
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Processed code coverage
Sat, 03 Feb 2018 22:40:11 GMT wallaby:project Test run result processed and sent to IDE

### Conclusion
I guess Wallaby does NOT compile Typescript into Javascript hence "Unexpected token import" error

**Comment by ArtemGovorov** [comment]
> I guess Wallaby does NOT compile Typescript into Javascript hence "Unexpected token import" error

Yes, it is correct.

The provided log contains the following entry:

```
TypeScript postprocessor will be removed because in 7 project files none were found by patterns: *.ts?(x)
```

It means that Wallaby is compiling any of your project TypeScript files, because none of them satisfies the `*.ts?(x)` pattern. And it makes sense, only some root level TypeScript file paths would satisfy this glob pattern.

In order to work, your pattern should include subfolders and look like:

```javascript
    compilers: {
      '**/*.ts?(x)': ...
    },
```

> Somehow wallaby stopped working for me. What I did is just enabled internet access to Visual Studio, so I think wallaby did some updates (or whatever) which broke the whole process.

This is surprising and sounds unlikely, I don't think any of previous Wallaby versions would work with the glob pattern.

**Comment by alexander-ossur** [comment]
Thank you Artem,

**/*.ts?(x) works like a charm. It's strange though "*.ts?(x)" worked before. 

Thank you again and have nice day
