### ISSUE TITLE
Enzyme expects an adaptor to be configured - Wallaby

### ISSUE THREAD

**Issue by michael4reynolds** [wallabyjs/public#1497]
### Issue description or question
While trying to get Wallaby to run with Enzyme in a Create-React-App I am receiving the error: 'Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none' even though the tests pass with the Jest test runner. I've tried to ignore while still loading the setupTests.js file to at least get some of the tests to run but now I cannot get any shallow rendering.

### Wallaby.js configuration file
```javascript
// wallaby.js
module.exports = function (wallaby) {
  var path = require('path')
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules')
  require('module').Module._initPaths()

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.js?(x)',
      {pattern: 'src/setupTests.js', load: true, ignore: true}
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p))
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k])
      delete jestConfig.testEnvironment
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest'
  }
}
```

```javascript
// setupTests.js
import { configure } from 'enzyme'
import Adapter from 'enzyme-adapter-react-16'

configure({ adapter: new Adapter() })
```

```javascript
// App.test.js
import React from 'react'
import { shallow } from 'enzyme'
import App from './App'

describe('App', () => {
  const app = shallow(<App />) // this line throw error: Enzyme expects an adapter to be configured, but found none

  it('renders properly', () => {
    expect(app).toMatchSnapshot()
  })
})
```

### Code editor or IDE name and version

Visual Studio Code v1.19.3
IntelliJ IDEA v2017.3

### OS name and version
OSX - 10.13.3

**Comment by ArtemGovorov** [comment]
There's no need to include anything in your [wallaby CRA config](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app), it should just work. 

This line

```javascript
{pattern: 'src/setupTests.js', load: true, ignore: true}
```

with the `ignore` flag excludes the file from those being considered by Jest when running from wallaby, that's why it doesn't work. If you remove the line, it should just work for you.

**Comment by michael4reynolds** [comment]
Thanks. I removed the line but I also had to convert 'setupTests.js' to ES5 syntax to get it to work with both Enzyme and Wallaby simultaneously.
