### ISSUE TITLE
Unexpected Token import Node

### ISSUE THREAD

**Issue by Awais512** [wallabyjs/public#1499]

**Comment by Awais512** [comment]
My server.js file

import { MongoStore } from '../AppData/Local/Microsoft/TypeScript/2.6/node_modules/@types/connect-mongo';

var express = require('express');
var morgan = require('morgan');
var app = express();
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
var ejs = require('ejs');
var engine = require('ejs-mate');
var session = require('express-session');
var cookieParser = require('cookie-parser');
var flash = require('express-flash');
var mongoStore = require('connect-mongo/es5')(session);
var passport = require('passport');

var secret = require('./config/secret');
var User = require('./models/user');

mongoose.connect(secret.database,function(err){
    if(err){
    console.log(err);}
    else{
        console.log("Connected with mongodb");
    }
});
//Middleware
app.use(express.static(__dirname + '/public'));
app.use(morgan('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
app.use(cookieParser());
app.use(session({
    resave:true,
    saveUninitialized: true,
    secret: secret.secretKey,
    store: new MongoStore({ url: secret.database, autoReconnect: true })
}));
app.use(flash());

app.engine('ejs', engine);
app.set('view engine', 'ejs');

var mainRoutes = require('./routes/main');
var userRoutes = require('./routes/user');
app.use(mainRoutes);
app.use(userRoutes);




app.listen(secret.port, function(err){
    if(err) throw err;
    console.log("Server is running on port " +secret.port);
});


My Passport.js file

var passport = require('passport');
var localStrategy = require('passport-local').Strategy;

//serialize and deserialize
passport.serializeUser(function(user, done){
done(null, user._id);
});

passport.deserializeUser(function(id, done){
User.findById(id, function(err, user){
done(err, user);
    });
});

//middleware

passport.use('local-login', new localStrategy({
    usernameField: 'email',
    passwordField: 'password',
    passReqToCallback: true
}, function(req, email, password, done){
    user.findOne({email: email}, function(err, user){
        if(err) return done(err);

        if(!user) {
            return done(null, false, req.flash('loginMessage', 'No user has been find'));
        }
        if(!user.comparePassword(password)) {
            return done(null, false, req.flash('loginMessage', 'Oops! Wrong password'));
        }
        return done(null, user);
    });
}));

//custom function

exports.isAuthenticated = function(req, res, next) {
    if(req.isAuthenticated()) {
        next();
    }
    res.redirect('/login');
}
My user.js file


var router = require('express').Router();
var User = require('../models/user');
var passport = require('passport');
var passportConf = require('../config/passport');

router.get('/login', function(req, res,){
if(req.user) return res.redirect('/');
res.render('accounts/login', {message: req.flash('loginMessage')});
});

router.post('/login', passport.authenticate('local-login', {
    successRedirect: '/profile',
    failureRedirect: '/login',
    failureFlash: true
}));

router.get('/signup', function(req, res){
    res.render('accounts/signup', {
        errors: req.flash('errors')
    });
});


router.post('/signup', function(req, res, next){
var user = new User();

user.profile.name = req.body.name;
user.email = req.body.email;
user.password = req.body.password;

User.findOne({email: req.body.email}, function(err, existingUser){
if(existingUser) {
    req.flash('errors', 'This email address already exists')
    return res.redirect('/signup'); 
}else{
    user.save(function(err, user){
        if(err) return next(err);
        return res.redirect('/');
     });
    }
  });

});
module.exports = router;


its not working it gives me the error "Unexpected token import" 
Help me to solve this issue any help would be appreciated

**Comment by ArtemGovorov** [comment]
Node.js doesn't support ES modules (`import/export`). 

- How's your app supposed to work in production with ES modules? 
- Are you using Babel to transpile your source code? 
- Can you share your wallaby config file?

**Comment by Awais512** [comment]
Thnx got it now. I just remove the import lines from the server.js and it works like a charm
