### ISSUE TITLE
Intellij Ultimate 14.0.1

### ISSUE THREAD

**Issue by ingoe** [wallabyjs/public#15]
Trying to install wallaby-intellij-v0.9.7.zip in IntelliJ Ultimate 14.0.1 on Windows 7 Enterprise returns the error:

plugin Wallaby is incompatible with current installation.

**Comment by cluebcke** [comment]
The "Supported Code Editors" section of the [README](https://github.com/wallabyjs/public/blob/master/README.md) specifically states
> IntelliJ IDEA Ultimate >= 14.0.2

**Comment by ArtemGovorov** [comment]
Yes, as @cluebcke has correctly mentioned only version 14.0.2 (and higher) is supported.
