### ISSUE TITLE
Change Phantom.js viewport width.

### ISSUE THREAD

**Issue by baldore** [wallabyjs/public#150]
Good morning. I have a small problem in this moment testing different viewport widths. Is there a way to change the viewport size in wallaby config file?

**Comment by ArtemGovorov** [comment]
Hello,

There is not way to do it at the moment, I'll add the configuration option today and let you know once it's ready.

**Comment by baldore** [comment]
Thanks Artem.

**Comment by ArtemGovorov** [comment]
Done (core 1.0.63, will update itself automatically or after IDE restart). You can now set the viewport size in the `env` setting in your config:
``` JavaScript
...
files: [...],
tests: [...],
env: {
  viewportSize: {width: 300, height: 300}
}
...
```
The default value is `{width: 800, height: 600}`.

**Comment by baldore** [comment]
Thanks for all ArtemGovorov. Wallaby rocks!!!
