### ISSUE TITLE
Error: Failed to lookup view "accounts/login" in views directory "C:\Users\Hp\ecommerce\views"

### ISSUE THREAD

**Issue by Awais512** [wallabyjs/public#1500]
When i try t send data via postman then it gives me that error "Error: Failed to lookup view "accounts/login in views directory C:\Users\Hp\ecommerce\views" help me to resolve this issue  any help would be appreciated thanx

**Comment by ArtemGovorov** [comment]
It's possible that you are missing some [files in your `files` list](https://wallabyjs.com/docs/config/files.html). Make sure that all files used by your tests are listed in the config `files` list, including your views (with whatever file extension they have).

If the suggestion above doesn't help, please create a sample repository demonstrating the issue, we are happy top have a look.
