### ISSUE TITLE
How to config wallaby to work with lerna, typescript and react?

### ISSUE THREAD

**Issue by nampdn** [wallabyjs/public#1503]
### Issue description or question
Hi, I tried to make wallabyjs work with [https://github.com/nampdn/lerna-wallaby-react-typescript](https://github.com/nampdn/lerna-wallaby-react-typescript),
But it throw error like this in the Test Console:
> Error: Cannot find module 'react' from 'App.test.js'​​
### Wallaby.js configuration file
https://github.com/nampdn/lerna-wallaby-react-typescript/blob/master/wallaby.js

```javascript
const path = require('path')

module.exports = wallaby => {
  process.env.NODE_PATH += path.delimiter + path.join(wallaby.projectCacheDir, 'packages')
  return {
    files: ['packages/**/*.ts*', '!packages/**/node_modules/**', '!packages/**/*.test.ts*'],
    tests: ['packages/**/*.test.ts*', '!packages/**/node_modules/**'],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs', jsx: 'React' }),
    },
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.19.3

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Some file patterns are missing and some jest initialisation mostly from [wallaby CRA docs](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app) (with some adjustments for `react-scripts-ts`).

I have sent you the [pull request with the working config](https://github.com/nampdn/lerna-wallaby-react-typescript/pull/1).

**Comment by nampdn** [comment]
Thank you for your quick support!

**Comment by nampdn** [comment]
Hi @ArtemGovorov,
I have pulled the merged code and run wallaby again, but it throw error like this in Wallaby Console:
>[Info]​​​​​ console.error: Error while trying to initialize jest: Cannot set property '_wallabySession' of undefined

And in the Wallaby.JS Tests:
>​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Failed to initialize wallaby jest.​​
​​Error: Cannot find Jest test runner​​
​​    at Module._compile (module.js:635:30)​​
​​    at Object.Module._extensions..js (module.js:646:10)​​
​​    at Module.load (module.js:554:32)​​
​​    at tryModuleLoad (module.js:497:12)​​
​​    at Function.Module._load (module.js:489:3)​​
​​    at Module.require (module.js:579:17)​​
​​    at require (internal/module.js:11:18)​​
​​    at Module._compile (module.js:635:30)​​
​​    at Object.Module._extensions..js (module.js:646:10)​​
​​    at Module.load (module.js:554:32)​​
​​    at tryModuleLoad (module.js:497:12)​​
​​    at Function.Module._load (module.js:489:3)​​
​​    at Function.Module.runMain (module.js:676:10)​​
​​    at startup (bootstrap_node.js:187:16)​​
​​    at bootstrap_node.js:608:3​​

**Comment by ArtemGovorov** [comment]
@nampdn This issue was fixed yesterday, please see https://github.com/wallabyjs/public/issues/1505#issuecomment-363973201

**Comment by nampdn** [comment]
Thanks @ArtemGovorov, I do the force update and it works now.
But please this is the last call for this issue.

It seem I couldn't load css file from compiled typescript file.
>Error: Cannot find module './App.css' from 'App.js'​​
  at Object.<anonymous> ​packages/cms-exercise/src/App.tsx:2​
  at Object.<anonymous> ​packages/cms-exercise/src/App.test.tsx:3​

**Comment by ArtemGovorov** [comment]
@nampdn Yep, I saw this one `Error: Cannot find module './App.css' from 'App.js'​​` when was creating the config for your project. There's no `App.css` file in the project, only `App.scss`, hence the error.

**Comment by nampdn** [comment]
Ah I got it, it is related to my project setup, not about Wallaby.
Thanks for your quick response again <3
