### ISSUE TITLE
Error while trying to initialize jest: Cannot set property '_wallabySession' of undefined

### ISSUE THREAD

**Issue by brekk** [wallabyjs/public#1505]
### Issue description or question

I'm a huge fan of wallaby and normally I am able to get it to run in new projects, but I am seeing an error I'm familiar with:

```
Wallaby Console: Error while trying to initialize jest: Cannot set property '_wallabySession' of undefined
```

I'm seeing that as the last message displayed in the Atom dev tools with `{debug: true}` in my wallaby config.

### Wallaby.js configuration file

```javascript
module.exports = function configureWallaby(wallaby) {
  const config = {
    debug: true,
    files: [
      'static/*.js',
      'static/**/*.js',
      '!static/tests/**/*.specs.js',
    ],

    tests: [
      'static/tests/*.specs.js',
      'static/tests/**/*.specs.js',
      // wallaby doesn't know about this yet
      // '!static/tests/js/routes/*.specs.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'jest',
  };
  return config;
};

```

### Code editor or IDE name and version

Atom v.1.23.3

### OS name and version

OSX High Sierra (10.13.3)

**Comment by ArtemGovorov** [comment]
This was a breaking change in Jest 22.2. However the support was published yesterday (shortly after the Jest version was published) in the latest wallaby core version 1.0.545. Please try forcing the update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), it should help.

**Comment by brekk** [comment]
👍 Great, worked perfectly after re-install. Thank you!

**Comment by jscanlon77** [comment]
Hi there.. This still doesn't work for me...
I'm using Wallaby.js Core v1.0.529. 
I've got a working version of Jest installed 23.1.0 and jest-preset-angular 5.2.2. This is all working fine in my project but I'd like to get them both working together.  My output window gives the following:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.529
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​​​​[Info]​​​​​ console.error: Error while trying to initialize jest: Cannot set property '_wallabySession' of undefined
```

And my config is 

```
module.exports = function () {

  return {
    files: [
      'src/**/*.js',
      'package.json', // <--
      '!src/**/*.spec.ts'
      ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup: function (wallaby) {
      var jestConfig = require('./package.json').jest;
      // for example:
      // jestConfig.globals = { "__DEV__": true };
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
@jscanlon77 The error is expected because

> I'm using Wallaby.js Core v1.0.529.
> Jest installed 23.1.0

You Wallaby Core version doesn't support Jest 23. The support was added in later versions. For example Jest 22.2.0 support was added in v1.0.545 (current Wallaby Core version is 1.0.604). You may either consider using earlier versions of Jest, or consider [updating your Wallaby license](https://wallabyjs.com/purchase/#upgrade) to get the latest version of Wallaby Core (and 12 more months of updates).
