### ISSUE TITLE
Wallaby JS with yarn workspaces

### ISSUE THREAD

**Issue by vespertilian** [wallabyjs/public#1506]
### Issue description or question

If possible I would like to get Wallaby working with yarn workspaces in a mono-repo configuration. I have a Javascript app consisting of an Angular frontend and Node backend and I like the idea installing all my dependencies with one command. 

### Wallaby.js configuration file

You can find a sample of the app setup here:
https://github.com/vespertilian/wallaby-angular-node-yarn-workspaces

If you want to see the existing setup work with wallaby you can just checkout an older commit and run `yarn` in the individual folders. 

The only thing that does not work for the mono repo is Wallaby.js

I have two wallaby config files: 

```
/api/wallaby.js 
/angular-app/wallaby.js 
```

Not sure if you support this yet but it would be great to be able to run wallaby for my frontend and backend code at the same time. 

### Code editor or IDE name and version

WebStorm v2017.3.4

### OS name and version

OSX 10.13.3

**Comment by vespertilian** [comment]
@ArtemGovorov you are super quick with the fix. Thanks you so much. 

Updated repository here for anyone viewing this issue:
https://github.com/vespertilian/wallaby-angular-node-yarn-workspaces

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
