### ISSUE TITLE
Uncaught Error: Cannot find module ng-cli setup

### ISSUE THREAD

**Issue by Conrad777** [wallabyjs/public#1507]
### Issue description or question

Hi, I am using the wallaby setup for [ng-cli](https://github.com/wallabyjs/ngCliWebpackSample).

I started getting this error only recently.

```
​​Uncaught Error: Cannot find module './src/wallabyTest.js'​​ ​​at http://localhost:49408/wallaby-webpack.js?1518096576794:1​​
​​Uncaught Error: Cannot find module '271'​​ ​​at http://localhost:49408/wallaby-webpack.js?1518096576794:1​​
```
Wallaby runs half of my tests fine so also getting `0 failing tests, 139 passing​​​​​`, but there are 250 tests.

So I am suspecting that it is probably a specific test, but the passing tests always varies.

What would be the quickest way to debug this?

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.20.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please try this:
- set [wallaby workers](https://wallabyjs.com/docs/config/workers.html) count to 1 (to make the issue causing spec finding easier)
```diff
module.exports = function (wallaby) {

  ...

  return {
    ...
+   workers: {initial: 1, regular: 1}
  };
};
```
- edit the `tests` setting and comment out all specs
```javascript
tests: [
      // {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],
```
- add one spec to the `tests` to see if the tests pass,
- keep adding spec files one by one, until you find the one causing the failure.

**Comment by Conrad777** [comment]
Thanks, will try this and get back to you

**Comment by Conrad777** [comment]
So I can confirm that it isn't just any one test. It happens in different spec files.

What does work though is when I add `workers: { initial: 1, regular: 1 }`. With this setting all the errors go away. Does that mean some of my tests rely on others?

**Comment by ArtemGovorov** [comment]
> Does that mean some of my tests rely on others?

Yes, it is likely the case. Because the `workers` setting makes your tests files run one after another in one sandbox (just like karma does). However the default parallelisation breaks them.

**Comment by Conrad777** [comment]
Okay, thanks for your help

**Comment by ArtemGovorov** [comment]
Have you found the test(s) that is causing the issue?

I may also suggest trying this:
- set `emitModulePaths` webpack config property, and when the `Cannot find module ...` error shows up, it should now display the module name instead of a number. Please share the module name.
```diff
var webpackPostprocessor = wallabyWebpack({
  ...
+ emitModulePaths: true
})
...
```

**Comment by Conrad777** [comment]
I've not yet had a change look into this a bit more. When I add emitModulePaths setting the module is: `​​Uncaught Error: Cannot find module '271' (.../node_modules/@angular/core/esm5/testing.js)​​`

**Comment by ArtemGovorov** [comment]
Could you please 

- specify your version of Chrome browser,
- share your `package.json`'s file dependencies and devDependencies sections,
- try switching to [Electron runner](https://wallabyjs.com/docs/integration/electron.html) (and removing the `workers: {initial: 1, regular: 1}` setting) to see if it helps.

**Comment by ArtemGovorov** [comment]
Thanks for the provided info. Merging the issue into https://github.com/wallabyjs/public/issues/1514#issuecomment-366115013, you may more info and a couple of workarounds there.
