### ISSUE TITLE
dynamic imports with @std/esm does not work with wallaby

### ISSUE THREAD

**Issue by git-jiby-me** [wallabyjs/public#1508]
### Issue description or question

When i try to add a dynamic import to @std/esm sample from https://github.com/wallabyjs/wallaby-std-esm it fails with error `SyntaxError: Unexpected token import`

### Wallaby.js configuration file

same as the one in sample project https://github.com/wallabyjs/wallaby-std-esm/blob/master/wallaby.js

### Code editor or IDE name and version

IntelliJ IDEA 2017.3

### OS name and version

OSX

**Comment by git-jiby-me** [comment]
static imports does work fine, so i believe this is specific to dynamic imports with @std/esm and wallaby

**Comment by ArtemGovorov** [comment]
Wallaby inserts instrumentation instructions producing sequence expressions and it seems to break `@std/esm`. I have created an issue here https://github.com/standard-things/esm/issues/273.

**Comment by ArtemGovorov** [comment]
Should work with with `@srd/esm@0.21.0+`, https://github.com/standard-things/esm/issues/273#issuecomment-364291978

**Comment by git-jiby-me** [comment]
@ArtemGovorov i can confirm it works, thanks for the fast response.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
