### ISSUE TITLE
'Cannot find module' with Jest, Webpack & React configuration

### ISSUE THREAD

**Issue by andrewflierman** [wallabyjs/public#1510]
### How to properly configure wallaby in project with Jest, Webpack and React
Taking the given configuration file I'm getting the following error when running tests:

```
Cannot find module '../../src/core/utils/logger' from 'file.test.js'​​
```

The actual code is: 

```
jest.mock('../../src/core/utils/logger', () => ({ error: jest.fn(), info: jest.fn() }));
```

When I simply run my tests with **yarn test** it all runs fine.

How do I go on from here? 

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  process.env.NODE_ENV = 'test';
  return {
    files: [
      { pattern: 'src/**/*.js?(x)', load: false },
      { pattern: 'test/fakeContexts.js', load: false }
    ],
    tests: [
      'test/**/*.test.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },
    testFramework: 'jest',
    debug: true
  };
};

```
### Jest Config (in package.json)
```
"jest": {
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "transform": {
      "^.+\\.js$": "babel-jest",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/test/fileTransformer.js"
    }
  }
```

### Code editor or IDE name and version

Visual Studio Code v1.20

### OS name and version

MacOS 10.13.3

**Comment by ArtemGovorov** [comment]
I have created [this sample repo](https://github.com/ArtemGovorov/wallaby-1510) with your config and your file structure, and it's working for me.

Perhaps you have some module mapping in your Jest config? Could you please share your Jest config?

Either way, please take a look into the repo and let me know about the missing bits to reproduce the issue (please feel free to fork the repo).

**Comment by andrewflierman** [comment]
Thnx, here is my Jest config

```
"jest": {
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "transform": {
      "^.+\\.js$": "babel-jest",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/test/fileTransformer.js"
    }
  },
```

**Comment by ArtemGovorov** [comment]
Juts added your Jest config as is, but the sample repo https://github.com/ArtemGovorov/wallaby-1510 is working for me without any issues.

Could you please clone the repo, run `npm i` and run wallaby in it? If it's working for you, please add the missing bits to reproduce the issue.

**Comment by andrewflierman** [comment]
I forked the repo and added the missing bits, result is the same error.

https://github.com/andrewflierman/wallaby-1510

**Comment by ArtemGovorov** [comment]
Thanks! The issue was that you are using `package.json` in the logger folder, but `*.json` files pattern wasn't specified, so when running from wallaby Jest was attempting to look up just by the `logger`/`logger/index.js` standard names.

I have sent your the [pull request](https://github.com/andrewflierman/wallaby-1510/pull/1) to make it work.

**Comment by andrewflierman** [comment]
Works perfect now, thank you!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
