### ISSUE TITLE
Cannot find module `@babel/plugin-transform-runtime`

### ISSUE THREAD

**Issue by kevva** [wallabyjs/public#1512]
### Issue description or question

When upgrading Babel to version `7.0.0@beta` and trying to run Wallaby I get `Cannot find module '@babel/plugin-transform-runtime' from '.'​​`. Running the tests from `jest` directly works fine so I suspect is has to do something with `wallaby`, or my configuration (which worked with `babel@6`).

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
  files: ['src/**/*.js*', '!src/**/__tests__/*.js*'],
  tests: ['src/**/__tests__/*.js*'],
  compilers: {
    'src/**/*.js*': wallaby.compilers.babel(),
  },
  env: {
    type: 'node',
    runner: 'node',
  },
  testFramework: 'jest',
});
```

### Relevant configuration and dependencies in `package.json`

```json
{
  "devDependencies": {
    "@babel/cli": "^7.0.0-beta.40",
    "@babel/core": "^7.0.0-beta.40",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.40",
    "@babel/preset-env": "^7.0.0-beta.40",
    "@babel/preset-react": "^7.0.0-beta.40",
    "babel-core": "^7.0.0-bridge.0",
    "babel-eslint": "^8.2.1",
    "babel-jest": "^22.2.2",
    "babel-loader": "^8.0.0-beta.0",
    "jest": "^22.2.2",
  },
  "babel": {
    "plugins": [
      "@babel/plugin-transform-runtime"
    ],
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  }
}
```

### Code editor or IDE name and version

Visual Studio Code 1.21.0-insider

### OS name and version

macOS 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for the report. We have been able to reproduce and fix the issue. Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), the issue should be fixed now.

**Comment by kevva** [comment]
@ArtemGovorov, thanks for the swift fix!
