### ISSUE TITLE
duplicate require/import errors

### ISSUE THREAD

**Issue by farzher** [wallabyjs/public#1516]
### Issue description or question

noob here.

not sure how this is possible? but it looks like require/import are running multiple times, causing weird errors.

![image](https://user-images.githubusercontent.com/1005136/36296188-11a8c7b8-12ba-11e8-9f93-600e547900e6.png)
this thing tries to use `Object.defineProperty`

![image](https://user-images.githubusercontent.com/1005136/36296191-133d1066-12ba-11e8-839b-d57836b96c5e.png)
this thing calls `expressapp.listen`

anything i include that would break if executed multiple times, breaks

running `mocha` works fine, it's just wallaby that's bugging out

i'm using typescript if that's relevant

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      '*.ts',
      'lib/**/*.ts',
      'lib/express-async-errors.js',
    ],

    tests: [
      'test/**/*.ts',
    ],

    env: {
      type: 'node',
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.21

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Wallaby, unlike mocha, by default reuses node processes and runs tests in parallel. It looks like both of the first error is related to the [process reuse](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) and the second one is related to [test runs parallelization](https://wallabyjs.com/docs/config/workers.html).

If you don't want to make your tests parallel runs friendly (by [not using a fixed port](https://stackoverflow.com/questions/30178023/avoiding-eaddrinuse-when-using-wallaby-js-with-an-express-project)), and find some way to reuse node the process, then you may make wallaby tor run your tests like plain mocha would:

```diff
module.exports = function () {
  return {
    files: [
      '*.ts',
      'lib/**/*.ts',
      'lib/express-async-errors.js',
    ],

    tests: [
      'test/**/*.ts',
    ],

+   workers: {regular: 1, initial: 1, restart: true},

    env: {
      type: 'node',
    }
  };
};
```

**Comment by farzher** [comment]
ty!

**Comment by farzher** [comment]
fancy stuff. i didn't know it was even possible to require the same thing twice

`require('./lib/express-async-errors')`
`require('./lib/express-async-errors')`

this only runs once.
are you doing something that clears the `require` cache and runs all the changed code again on the same process?

**Comment by ArtemGovorov** [comment]
> are you doing something that clears the `require` cache and runs all the changed code again on the same process?

Yes, we are clearing `require` cache. But a module can introduce some side effects for example by writing something to globals.

**Comment by farzher** [comment]
@ArtemGovorov can i take advantage of this to cache stuff?

my app downloads a lot of stuff from a DB once, then uses it from ram.
every time i type, it's triggering a new test and downloading the DB again!
is there a way to keep a variable persistent between tests?

**Comment by ArtemGovorov** [comment]
You may try, it does sound however that your tests are just not designed to run as frequently as wallaby normally runs tests.

If workers are reused (workers: {...,restart: false}), then whatever you save into the `global` will persist. For example,

```javascript
module.exports = function () {
  return {
    ...
    setup: () => {
      if (global.myVar) return;
      console.log('setting myVar');
      global.myVar = 1;
    }
  };
};
```

global.myVar will only be set once per worker.

**Comment by farzher** [comment]
I tried using global before asking, but it didn't work... seems to work fine now, thanks!
