### ISSUE TITLE
Jest Windows Issue

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1517]
### Issue description or question
When starting Wallaby on Windows I am getting the error below. This is happening on the private repo I've previously given you access to.

```js
TypeError: Cannot read property 'forEach' of undefined
    at default.readdir (C:\Users\chris\Documents\sanejs\packages\core\node_modules\jest-haste-map\build\crawlers\node.js:34:13)
    at FSReqWrap.oncomplete (fs.js:135:15)
```
### Wallaby.js configuration file

```javascript
'use strict';

module.exports = (wallaby) => {
    process.env.NODE_PATH = require('path').join(
        wallaby.localProjectDir,
        '../../node_modules',
    );

    return {
        files: [
            { pattern: 'src/**/__sandbox__/**/*', instrument: false },
            { pattern: 'src/**/__sandbox__/**/.*', instrument: false },
            { pattern: '.babelrc+(.js|)', instrument: false },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (w) => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            require('babel-polyfill');
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            jestConfig.transform = { '__sandbox__.+\\.jsx?$': 'babel-jest' };
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2018.1 EAP
Build #WS-181.3741.14, built on February 13, 2018
JRE: 1.8.0_152-release-1136-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
### OS name and version

``Windows 10 10.0``

**Comment by ArtemGovorov** [comment]
Does plain Jest CLI work on the project on Windows?

I have also noticed from the error stack that you've posted:
```
at default.readdir (C:\Users\chris\Documents\sanejs\packages\core\node_modules\jest-haste-map\build\crawlers\node.js:34:13)
```
that jest node_modules hadn't been hoisted to the root for some reason (as it used to work on macOS).  Is it expected on Windows?

**Comment by chrisblossom** [comment]
Jest CLI works as expected (tests fail as expected, but run)

The ``node_modules`` weren't hoisted for that run because I ``npm install`` directly in ``C:\Users\chris\Documents\sanejs\packages\core\``. Same issue hoisted or not.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details. Looks like on Windows different file crawler is used by Jest, and for some reason (maybe because of the multi-package repo), with the `rootDir` setting in your Jest config, when running from Wallaby Jest is trying to resolve `src/src/...` directory, instead of `src/...`. It is strange because the same setting is ok on macOS.

This config change should fix it:

```diff
setup: (w) => {
	...
	const jestConfig = require('./jest.config');
+	delete jestConfig.rootDir;
}
```

**Comment by ArtemGovorov** [comment]
I think Jest `rootDir` is an issue in this case maybe because you are running wallaby from your project's root (wallaby's working directory is always the project's root dir), while you are running Jest CLI from the context of your `core` package.

**Comment by chrisblossom** [comment]
@ArtemGovorov I created a minimal example [chrisblossom/wallaby-issue-1517](https://github.com/chrisblossom/wallaby-issue-1517) without a lerna repo. I think rootDir is a typical configuration setting. You sure this isn't a bug with wallaby?

**Comment by ArtemGovorov** [comment]
@chrisblossom Thanks for the repo, will check it out.

**Comment by ArtemGovorov** [comment]
@chrisblossom You were absolutely correct! The bug is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
