### ISSUE TITLE
Wallaby App on localhost does not display tests

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#1518]
When running the wallaby app from `localhost`, it does not show tests, even though it still shows the test count and coverage in the top bar. It works perfectly when I connect to the app via `https://wallabyjs.com/app/#/tests` however.

Here's a screenshot from `http://localhost:51245/`:
<img width="773" alt="screen shot 2018-02-19 at 21 41 18" src="https://user-images.githubusercontent.com/10428082/36396314-b462ddb2-15bd-11e8-8124-97fced81ebf4.png">

Here's a gist with the long list of errors in the Google Chrome console: https://gist.github.com/Floriferous/ce6573b15007653f0dbf8fffa4cf0661

I'm using macOS 10.13.3 and Chrome: Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by ArtemGovorov** [comment]
Looks like you have the `Block third-party cookies` on in chrome://settings/content/cookies. The error however shouldn't break the app, we have fixed it and released the fix in Wallaby App v1.0.36.
