### ISSUE TITLE
Cannot find module: any test using proxyquire.

### ISSUE THREAD

**Issue by kid-icarus** [wallabyjs/public#1519]
### Issue description or question

Running server-side mocha tests and I'm unable to proxyquire modules with wallaby. I looked at the proxyquireify plugin but I'm not using proxyquireify, just proxyquire.

### Wallaby.js configuration file

```javascript
const path = require('path');

module.exports = function(wallaby) {
  process.env.NODE_PATH += ':' + path.join(wallaby.localProjectDir, 'src', 'node_modules');
  return {
    files: [
      'src/**/*.js',
      'src/**/*.json',
      '!src/assets/**',
      '!src/test-func/**',
      '!src/**/test-node/*.js',
      '!src/**/test/**'
    ],
    tests: ['src/**/test-node/*.js'],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'mocha'
  };
};
```

### Code editor or IDE name and version

WebStorm v2017.3?

### OS name and version

OSX

**Comment by kid-icarus** [comment]
![image](https://user-images.githubusercontent.com/864752/36408318-8c7cde6e-15b9-11e8-923d-4abc95717336.png)

**Comment by kid-icarus** [comment]
Wallaby console doesn't show any errors.

```
wallaby.js started
core v1.0.551
Wallaby App (realtime reports) is available at: http://localhost:51245
console.error: WARNING: No configurations found in configuration directory:/Users/rkois/Library/Caches/WebStorm2017.3/wallaby/projects/3ec951c325e25c81/instrumented/config
console.error: WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
console.error: WARNING: No configurations found in configuration directory:/Users/rkois/Library/Caches/WebStorm2017.3/wallaby/projects/3ec951c325e25c81/instrumented/config
console.error: WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Execution progress: 50 tests
Execution progress: 100 tests
Finished executing 103 affected test(s)
```

**Comment by ArtemGovorov** [comment]
From the error message looks like `package.json` is [missing in wallaby cache](https://wallabyjs.com/docs/config/files.html).
Try adding it to the `files` list:

```diff
...
module.exports = function(wallaby) {
  ...
  return {
    files: [
+    'package.json,
      ...
    ],
    ...
  };
};
```

If the solution above doesn't help, please share a sample repo where we could reproduce the issue, we are happy to have a look and help.

> Wallaby console doesn't show any errors.

Looks like these are test errors, so Failing Tests tab should should show them.

**Comment by kid-icarus** [comment]
Thanks for the suggestion, but unfortunately it didn't work. I'll throw together a quick sample repo for reproduction.

**Comment by ArtemGovorov** [comment]
> I'll throw together a quick sample repo for reproduction.

Thanks. The sample from https://github.com/thlorenz/proxyquire#example works without any issues:

<img width="1158" alt="screen shot 2018-02-20 at 3 37 10 pm" src="https://user-images.githubusercontent.com/979966/36408902-023cce80-1654-11e8-946b-e47cb74c0377.png">

Also regarding this error from your Wallaby Console:

> `console.error: WARNING: No configurations found in configuration directory ...`

It's basically saying that your `config` folder is missing in your `files` list. Even though it is just a warning, but may be worth adding `config/**` pattern to your `files` list.

**Comment by kid-icarus** [comment]
Well, I feel foolish. Adding `config/**` did the trick. Thank you so much, your support is amazing!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
