### ISSUE TITLE
Unable to view test results in browser

### ISSUE THREAD

**Issue by Anupheaus** [wallabyjs/public#1520]
### Issue description or question
This morning there was an update link at the bottom of the Wallaby web app, which I clicked and since then I have been unable to view the test results in the browser at all.

### Wallaby.js configuration file
I created a quick repo with the files that pass the tests but I can't get the web app to work: https://github.com/Anupheaus/Test

### Code editor or IDE name and version

Visual Studio Code v1.20.1

### OS name and version

Windows 10

This is all I can see:
![image](https://user-images.githubusercontent.com/2872785/36420317-85f37fa8-162c-11e8-80d8-ae66dbc314e3.png)

Here is the network tab:
![image](https://user-images.githubusercontent.com/2872785/36420361-a773e6ea-162c-11e8-9d18-4d3e90f6d32c.png)

Any ideas please?

**Comment by Anupheaus** [comment]
Hmm, works in Edge and if I go into incognito mode....very strange

**Comment by Anupheaus** [comment]
Finally got it working by clearing all site data from within Chrome DevTools.  Feel free to delete if this post doesn't provide anything useful please.

**Comment by ArtemGovorov** [comment]
We have released 2 updates yesterday and the first one was broken, so perhaps you have got the broken update, and the correct one was installed after clearing the cache.
