### ISSUE TITLE
Compared values have no visual difference.

### ISSUE THREAD

**Issue by axelnormand** [wallabyjs/public#1526]
### Issue description or question

In my React + Saga + Jest project, one of my saga with snapshot tests passes on jest but fails on wallaby.
I can't figure out why the test would fail on wallaby. 
Other saga tests pass where i use snapshot.

Any clues much appreciated

Here is the output:

```
 { '@@redux-saga/IO': true,
      CALL: { context: null, fn: [λ: clear], args: [] } }
    ​​​​
    ​​Expected value to equal:​​
    ​​  {"@@redux-saga/IO": true, "CALL": {"args": [], "context": null, "fn": [Function clear]}}​​
    ​​Received:​​
    ​​  {"@@redux-saga/IO": true, "CALL": {"args": [], "context": null, "fn": [Function clear]}}​​
    ​​​​
    ​​Difference:​​
    ​​​​
    ​​Compared values have no visual difference.​​
      at Object.<anonymous> ​src/sagas/login.test.ts:138:2​
```

**Comment by ArtemGovorov** [comment]
Unfortunately it is impossible to tell why it may happen as the error is coming from Jest (when running it by Wallaby) without a sample repo. If you could share a sample repo, we are keen to have a look to sort it out. Hopefully it shouldn't be too hard to isolate the case.

**Comment by axelnormand** [comment]
Many thanks for the reply.
Just got back and this morning it started working again! 
So I'm closing this issue, sorry :)
