### ISSUE TITLE
Cannot set property '0' of undefined at __wallaby__/tracer.js:14

### ISSUE THREAD

**Issue by sylvain-hamel** [wallabyjs/public#1527]
### Issue description or question

I started getting this error when I start Wallaby from WebStorm

```
wallaby.js started
core v1.0.552
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught Error: Cannot find module '1'
at http://localhost:59986/wallaby-webpack.js?1519418024862:1
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught Error: Cannot find module '869'
at http://localhost:59986/wallaby-webpack.js?1519418024862:1
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Runtime error: Uncaught TypeError: Cannot set property '0' of undefined
at http://localhost:59986/__wallaby__/tracer.js:14
Finished executing 3 affected test(s)
```

In the Wallaby App I see that it only executed 3 tests out of 2280 tests. If I modify a file, Wallaby wakes up and runs the tests for that file. But I'm no longer able to get a full test run on start because of that error. As far as I can tell this started _suddenly_. I rebooted my PC and still have this issue.

### Code editor or IDE name and version

WebStorm 2017.3.4

### OS name and version

Windows 8.1

**Comment by ArtemGovorov** [comment]
This sound like a corrupted cache issue, please try [resetting wallaby cache](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) and restarting it. 

If it doesn't help, then it may be [this headless Chrome issue](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) (but I'm not sure as you haven't shared your wallaby config), in which case you may try [one of the workarounds listed here](https://github.com/wallabyjs/public/issues/1514#issuecomment-366115013).

Either way, please let me know if suggestions above helped.

**Comment by sylvain-hamel** [comment]
Yes, resetting the cache fixted it. Thanks
