### ISSUE TITLE
Using "special comment" in coffeescript

### ISSUE THREAD

**Issue by VasilySizov** [wallabyjs/public#1528]
### Issue description or question

How to use `/*?*/` when working with coffeescript? Obviously, comments syntax in coffeescript is different and interpreter fails when used. I suppose it should be something like `###*?*###`, but it doesn't work.

Thanks!

### Code editor or IDE name and version
Latest WebStorm

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Unfortunately the special comments feature is not supported in CoffeeScript.
