### ISSUE TITLE
Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by dkuida** [wallabyjs/public#1529]
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*'
        ],
        tests: [
            'test/**/*.test.js?(x)',
            'test/**/*.test.ts?(x)'
        ],

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel({}),

            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs'
            })
        },

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',
        debug: true
    };
};

```

### Code editor or IDE name and version

WebStorm v2017.3.4
### OS name and version

Windows

I have a set of tests, written in typescript- that are runing without any issue on the backend
but when I move them to frontend, where I have React setup
they are failing to run
more other - since the syntax is jasmine, when I set in wallaby - jasmine, the tests pass
if I set it to jest. - I receive the infamouse
**TypeError: Cannot read property '_jasmineAdapter' of undefined**

here is a sample test

```javascript
describe('lmp', () => {
            it('returns', () => {
                // arrange
                const sut = new Sut(lmp);
                expect(sut.lmp).toEqual(startOfDayLmp);
            }, TIMEOUT);
            xit('even if Date() return beginign of day', () => {
                // arrange

                const date = lmp.toDate();
                const sut = new Sut(date);
                expect(sut.lmp).toEqual(startOfDayLmp);
            }, TIMEOUT);
        });
```

I am on latest everything, jest, ts-jest etc

**update**
after pinpointing the problem to the installation of react scripts, I removed them and than wallaby switched to using jest-cli

in this scenarion at the moment it does not bother me - BUT - stilll how can I force wallabyjs to use jest-cli instead of react-scripts ?

**Comment by ArtemGovorov** [comment]
> in this scenarion at the moment it does not bother me

As it's working for you know, I'm going to close the issue. 

> stilll how can I force wallabyjs to use jest-cli instead of react-scripts ?

Could you please share a sample project (with package.json and package/yarn lock file and a dummy test) where we could reproduce the issue? After seeing what's causing it, we'll come up with an answer to your question.
