### ISSUE TITLE
Cannot read property 'DoStatement' of undefined

### ISSUE THREAD

**Issue by AndrewBailMYOB** [wallabyjs/public#1532]
### Issue description or question
When trying to launch wallaby it consistently fails, regardless of IDE.
Console output is 
```wallaby.js started
core v1.0.556
Failed to load configuration file:  Cannot read property 'DoStatement' of undefined
```
I cannot fund any information regarding 'DoStatement'. I have a feeling this has something to do with my system configuration but I do not know where to start to look to debug this. 

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};

```

### Code editor or IDE name and version
IntelliJ IDEA v2017.3
Atom v1.20.1

### OS name and version
OSX High Sierra

**Comment by ArtemGovorov** [comment]
We have reviewed our source code and had only found one place where the error could be raised from under very special conditions, we don't have any ideas how it's even possible. 

Nevertheless, we have just published [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) where the issue has been addressed (if it was the issue that you've been observing). Please try updating your wallaby core to 1.0.557 and let us know how it goes.

**Comment by AndrewBailMYOB** [comment]
That did the trick! Thanks for your prompt reply and action.
