### ISSUE TITLE
Dependency resolution issues on Windows

### ISSUE THREAD

**Issue by milang** [wallabyjs/public#1534]
### Issue description or question

Attached please find a demonstration project that illustrates the issue: [demo.zip](https://github.com/wallabyjs/public/files/1764539/demo.zip).

To build:

```sh
# unpack demo.zip
# cd unpack-directory
yarn
jest
code .
```

Expected behaviour:
- The test (`main/grid.tests.js`) passes when `jest` is run on command-line as well as when `jest` is run by Wallaby (in VSCode)

Actual behaviour:
- The test passes on command line but fails in Wallaby

---

The demo project uses `yarn` workspaces for two packages:
- `grid` => requires `jquery` 2.1.4 + (local copy of) `jquery-ui` that has side-effects (extra "stuff" is injected into jQuery as part of `require`)
- `main` => requires `jquery` 2.1.4 again as well as `grid`; it then defines a test that relies on side-effects that `grid` was supposed to inject into `jquery`

When running Jest on command line, test passes:

![Success on command line](https://user-images.githubusercontent.com/42297/36753403-47f22b9a-1bc3-11e8-9d72-037893c9177c.png)

However, Wallaby reports an error in VSCode (the side-effects are missing from `jQuery`):

![Wallaby failure](https://user-images.githubusercontent.com/42297/36753455-6da3f51c-1bc3-11e8-862a-57e10b2c21dc.png)

Please note that the demo project succeeds in terminal as well as VSCode + Wallaby on macOS 10.13. Because of this my working hypothesis is that Wallaby gets confused by "Windows symlinks" (junctions) created by `yarn` workspaces:

![image](https://user-images.githubusercontent.com/42297/36754033-2b4935b8-1bc5-11e8-8f13-bf5d05b65621.png)

It seems that when the test is running in Wallaby, it creates two copies of `jQuery` -- one in `grid` package, this copy is extended by `jquery-ui`; and another in `main` package that is not extended by `jquery-ui`, causing the test to fail.

### Wallaby.js configuration file

Included in demonstration project, see above.

### Code editor

Visual Studio Code v1.20.1 + Wallaby Core 1.0.558

### OS name and version

Windows 8.1, 10 (Wallaby does not work as expected)
macOS 10.13 (Wallaby works as expected)

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

It's actually not working on macOS either (well, not the way you'd expect it). Because packages other than the package with unit tests are not correctly loaded (they are loaded from your local project folder, as opposed to be loading from wallaby cache where everything is instrumented for code coverage). For example, if you run wallaby on macOS and open the  `packages/grid/index.js` file, you'll see it not covered, because when the `require("@acme/grid")` call is made, wiht your current config wallaby looks up into node modules that point back to you local folder (via a symlink, that also doesn't work on Windows for some reason).

The best way to [get yarn workspaces working in Wallaby is to use Jest `moduleNameMapper` in your wallaby config](https://github.com/wallabyjs/public/issues/1374#issuecomment-342017179). This way you don't depend on symlinks and code coverage works as expected in Wallaby. 

Here's the working config for your attached `demo` project:

```javascript
module.exports = {
    files: [
        "jest.config.js",
        "packages/grid/*.js",
        "packages/main/*.js",
        "!packages/main/*.tests.*",
        {pattern: 'packages/**/lib/*.js', instrument: false}
    ],
    tests: [
        "packages/main/*.tests.js",
    ],
    env: {
        type: "node",
        runner: "node",
        params: {
            env: "NODE_ENV=test"
        }
    },
    testFramework: "jest",
    setup: w => {
        const jestConfig = require('./jest.config');
        jestConfig.moduleNameMapper = {
            '^@acme/(.+)': w.projectCacheDir + '/packages/$1',
        };
        wallaby.testFramework.configure(jestConfig);
    },
};
```

**Comment by milang** [comment]
Thank you @ArtemGovorov , great advice.

Based on your configuration file, I tried tweaking the `jest.config.js` itself:

```js
module.exports = {
    moduleFileExtensions: ["js", "json"],
    testEnvironment: "node",
    moduleNameMapper: {
        "^@acme/(.+)": "<rootDir>/packages/$1"
    },
    testMatch: [
        "<rootDir>/packages/main/*.tests.js"
    ]
};
```

This allowed me to make the `setup` method more generic in `wallaby.js`:

```js
module.exports = {
    env: {
        type: "node",
        runner: "node",
        params: {
            env: "NODE_ENV=test"
        }
    },
    files: [
        "jest.config.js",
        "packages/**/*.js",
        "!packages/**/*.tests.js",
    ],
    testFramework: "jest",
    tests: [
        "packages/**/*.tests.js",
    ],
    setup: wallaby => {
        const jestConfig = require("./jest.config");
        for (const mapperKey in jestConfig.moduleNameMapper) {
            const mapperValue = jestConfig.moduleNameMapper[mapperKey];
            if (mapperValue.startsWith("<rootDir>")) {
                jestConfig.moduleNameMapper[mapperKey] = wallaby.projectCacheDir + mapperValue.substring(9);
            }
        }
        wallaby.testFramework.configure(jestConfig);
    }
};
```

With those changes, command-line `jest` still passes + it now also passes in Wallaby and correctly tracks code coverage in all files involved in the test.

What do you think about possibility for Wallaby to automatically perform this transformation, for example by adding a new opt-in configuration flag to enable it?

PS: For reference, I am including working demo project with the above changes: 
[demo.zip](https://github.com/wallabyjs/public/files/1765818/demo.zip)

**Comment by ArtemGovorov** [comment]
> What do you think about possibility for Wallaby to automatically perform this transformation, for example by adding a new opt-in configuration flag to enable it?

If you mean automatically replacing `<rootDir>` with `wallaby.projectCacheDir`, then I think it is a good idea. There are few cases when it's not desirable (when mapping node modules), but I think we could handle those by checking the mapped value.

**Comment by milang** [comment]
@ArtemGovorov 

> If you mean automatically replacing `<rootDir>` with `wallaby.projectCacheDir`...

Yes, that is exactly what I had in mind. Thank you for considering this idea.

PS: After applying _demo_ changes to our real project, Wallaby works as expected again (+ even better than before -- we get code coverage in places where we never had it). Thank you once again!

**Comment by ArtemGovorov** [comment]
@milang Implemented in the latest wallaby core v1.0.559. Now you should be able to completely drop the `setup` function in your wallaby config.

**Comment by milang** [comment]
@ArtemGovorov thank you! I can confirm that with the latest Wallaby Core v1.0.561 all tests pass in our real project even after removing the custom `setup` from `wallaby.js`.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
