### ISSUE TITLE
Unable to include files

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1535]
### Issue description or question

Want to include some files and folders into wallaby but it is not loaded.

Repro here: https://github.com/unional/fixture/tree/b6697484d6ac423f9780e9b56fc9af05c6794e97

Run the test in wallaby and you can see the error.

If I run `console.log(fs.readdirSync('src')`, the files are listed (as expected).

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      { pattern: 'fixtures/**/*', instrument: false },
      // also tried 'fixtures/**/*', 'fixtures', and 'fixtures/**'
      { pattern: 'tsconfig.*', instrument: false },
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],
    tests: [
      'src/**/*.spec.ts'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.20.1

### OS name and version

OSX 10.13.3

**Comment by ArtemGovorov** [comment]
This happens because you only have dot files in the folder and [minimatch doesn't match them by default](https://github.com/wallabyjs/public/issues/1399#issuecomment-345874209). This should help:

```diff
module.exports = () => {
  return {
    files: [
      { pattern: 'fixtures/**/*', instrument: false },
+     { pattern: 'fixtures/**/.*', instrument: false },
      { pattern: 'tsconfig.*', instrument: false },
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],
    tests: [
      'src/**/*.spec.ts'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest'
  }
}
```

**Comment by unional** [comment]
Thanks!
