### ISSUE TITLE
Having trouble running Quokka in create-react-app 

### ISSUE THREAD

**Issue by joha0033** [wallabyjs/public#1536]
### Issue description or question
So i've created a react app with the CLI, and have done nothing to it and Quokka.

I've tried to add Quokka to the config in the Quokka folder, no go.
I tried adding the Quokka babel: true in package.json, no go.
I tried reinstalling Quokka atom package, no go.
... a new app, nothing.
... npm install babel-core and loader, no go

any suggestions?

### Wallaby.js configuration file

```javascript
SyntaxError: src/App.js: Unexpected token (8:6)
   6 |   render() {
   7 |     return (
>  8 |       <div className="App">
     |       ^
   9 |         <header className="App-header">
  10 |           <img src={logo} className="App-logo" alt="logo" />
  11 |           <h1 className="App-title">Welcome to React</h1>
```

### Code editor or IDE name and version

Atom v1.15

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please follow the [suggestions in this thread](https://github.com/wallabyjs/quokka/issues/31#issuecomment-292053881).
