### ISSUE TITLE
Support for Dojo

### ISSUE THREAD

**Issue by dmitryfil** [wallabyjs/public#1539]
**Repurposed this issue to include overall support for Dojo as a UI framework, not just the Doh component.**

---

**Original issue description:**

> ### Question
> 
> Want to check if it's currently possible to set it up with Dojo's Doh framework, or how well it might work with it.
> 
> https://dojotoolkit.org/reference-guide/1.10/util/doh.html

**Comment by ArtemGovorov** [comment]
Wallaby supports [testing frameworks listed here](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks), Doh is not something that we support at the moment.

**Comment by dmitryfil** [comment]
@ArtemGovorov thank you, and in terms of adding support for it, would it be something that might be in a roadmap? 

I understand that Dojo is slightly outdated by today's standard, but there might be an array of legacy apps ( I would assume mostly enterprise ) where it might be still in use, and such tools might be especially useful.

Also want to check if / maybe there is a way to add support for it as a 3rd party extension ( or by means of some additional configuration? )

**Comment by ArtemGovorov** [comment]
>  would it be something that might be in a roadmap

Unfortunately not at the moment.

> Also want to check if / maybe there is a way to add support for it as a 3rd party extension

Unlike many other extendable parts of Wallaby, new testing framework support is unfortunately not something that be added by a third party.
