### ISSUE TITLE
Improve "Jump to Failing Test" behavior in VS Code in split screen

### ISSUE THREAD

**Issue by seanpoulter** [wallabyjs/public#1540]
### Issue description or question

Given:
* VS Code open
* Wallaby.js started
* Two editors viewed side by side:  module.js  |  module.test.js (active)
* A failing test in _module.test.js_ out of focus

When:
* I run the _Wallaby.js: Jump to Failing Test_ command

Then:
* I expect the failing test location to appear in the active document

Actual:
* The document is opened again on the first pane:  module.js, _module.test.js_  |  module.test.js

### Wallaby.js configuration file

Omitted for now to reduce the noise.

### Code editor or IDE name and version

Visual Studio Code v1.19.3

### OS name and version

OSX High Sierra v10.13.3 (17D102)

**Comment by ArtemGovorov** [comment]
Hi Sean,

Thanks for posting the request. We have implemented it and published in the latest Wallaby for VS Code 1.0.78.

**Comment by seanpoulter** [comment]
I'm impressed. Thanks for the wickedly fast fix @ArtemGovorov!
