### ISSUE TITLE
Support ava 1.0

### ISSUE THREAD

**Issue by smeijer** [wallabyjs/public#1542]
### Issue description or question

I've upgraded ava to the `1.0.0-beta` release because a `babel` update forced me to. (which was in turn forced by a meteor update).

Long story short; I cannot get WallabyJS to run with the new version of ava. It gives me the error, `Options have not yet been set`.

I have ava running, but Wallaby just won't start.

### Wallaby.js configuration file

Also have a repo here: https://github.com/smeijer/meteor-wallaby-ava

The fact that it is a meteor project, doesn't seem to be relevant. But that was the fasted way to get a repo.

```javascript
module.exports = function(wallaby) {
  const babelCompiler = wallaby.compilers.babel();

  return {
    files: [
      'client/**/*.js',
      'server/**/*.js',
      'imports/**/*.js',
      '!imports/tests.js'
    ],
    tests: [
      'imports/tests.js'
    ],
    compilers: {
      '**/*.js': babelCompiler,
    },
    env: {
      type: 'node',
      params: {
        env: ['NODE_ENV=production'].join(';'),
      },
    },
    debug: true,
    testFramework: 'ava',

    setup: () => {
      console.debug = console.log;
      global.React = require('react');
    },
  };
};

```

### Code editor or IDE name and version
WebStorm v2017.3.2

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Ava 1.0 beta has introduced a few breaking changes in their APIs that we have used in integration with Ava 0.x. We'll most likely need to implement Ava 1.0 support from the scratch.

**Comment by smeijer** [comment]
That's unfortunate to hear. Can you say anything about planning / priority?

Because you've added the `feature request` label. But as this change was pushed by Babel 7, I'm sure there will be a lot more environments that start breaking, as soon as Babel 7 will be released without beta label.

**Comment by ArtemGovorov** [comment]
>  But as this change was pushed by Babel 7, I'm sure there will be a lot more environments that start breaking, as soon as Babel 7 will be released without beta label.

Wallaby supports Babel 7 current beta, so if you use Babel 7 with mocha or other testing frameworks, it should work. 

The issue is not related to Babel. It's Ava's API have some breaking changes between Ava 0.x (that is supported by Wallaby) and Ava 1.x (which is still in beta BTW).

> Can you say anything about planning / priority?

We will be looking into it next week, but it depends on how many different things are changed between Ava 0.x and Ava 1.x.

**Comment by smeijer** [comment]
I understand. And I know Wallaby works fine with Babel 7. I said "pushed by Babel" because Babel 7 did also break a lot of things. Ava 0.25 wasn't compatible with Babel 7. That's why I needed to update Ava.

My Meteor update came with Babel 7, and Babel 7 broke Ava.  Updating Ava to 1.0 to be compatible with Babel again, broke wallaby. 

So all Ava users that will update to Babel 7, also needs to update Ava. 

We are on the same page here, and I'm still a happy wallaby user. That's why I extended my license yesterday. And will buy quokka next week. It's an awesome dev tool. I really miss using it at the moment. Coding without Wallaby just isn't the same. 

> We will be looking into it next week, but it depends on how many different things are changed between Ava 0.x and Ava 1.x.

Awesome. Would be great if you could keep me (/us) updated trough this issue.

**Comment by ArtemGovorov** [comment]
`ava@1.0.0-beta.3` support is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Note that the support is in beta (so there may be some cases that we didn't consider), as well as that the Ava 1.0 is still in beta (so there may be some issues in Ava itself). 

I will keep the issue opened until a few users try the support. Please try it and report any issues you hit here.

**Comment by smeijer** [comment]
Awesome. Can confirm it works 👍 🎉

**Comment by xanf** [comment]
@ArtemGovorov  Just FYI, it does not work with latest `ava@1.0.0-beta.5.1` with message `Chalk has not yet been configured​​` (it's because ava moved to own instance of chalk at https://github.com/avajs/ava/commit/2bd570edefc7cb5ab018eaf80191d81c6c25bf34

**Comment by ArtemGovorov** [comment]
@xanf Thanks for the report. Support for `ava@1.0.0-beta.5.1` has been added and published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.597.

**Comment by xanf** [comment]
@ArtemGovorov awesome. Sorry for annoying you, just making a note that ava now has a configuration options, which allows to configure ava in various ways - what I'm trying to do is to skip babel at all, and use esm for `mjs` modules:
```
{
	"ava": {
		"babel": false,
		"compileEnhancements": false,
		"extensions": [
			"js",
			"mjs"
		],
                "require": [ "esm" ]
	}
}
```

I can't get such setup working with wallaby, it seems these settings are completely ignored when spawning ava from wallaby. I understand the setup is a bit exotic (I prefer to call it next-gen), but it would be awesome if wallaby respects ava config in package.json

**Comment by ArtemGovorov** [comment]
@xanf Ava settings are indeed ignored by wallaby, because 99% of settings are configured differently in wallaby and are not required. To use `esm` instead of Babel in wallaby you may use [the `env.params.runner` setting](https://wallabyjs.com/docs/integration/node.html#es-modules).

**Comment by xanf** [comment]
@ArtemGovorov I know, sorry, will come with a demo repo to show issue

**Comment by xanf** [comment]
@ArtemGovorov https://github.com/xanf/wallaby-ava-esm-mjs-demo
Here we go (ignore that I didn't put run script to the repo). The main idea I can do `ava` and it will run test fine (import is handled by `esm` and other stuff is not compiled by babel). But with wallaby I have following in console:

```
​​​​​[Info]​​​​​ Thu, 14 Jun 2018 11:43:51 GMT wallaby:workers Sandbox (active) [c1skt] error: Must use import to load ES Module: file:///c:/Users/xanf/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/7bce06916b362d4b/instrumented/tests/demo.mjs
​​[Error] Runtime error: C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1​​
​​[Error] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: file:///c:/Users/xanf/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/7bce06916b362d4b/instrumented/tests/demo.mjs​​
​​[Error]     at Object.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Object.Gu (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Object.u (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Object.l (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Object.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Object.apply (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1​​
​​[Error]     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1​​
​​[Error]     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1​​
​​[Error]     at En (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Proxy.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Module.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at Module.t (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at require (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:112:11)​​
​​​​​[Info]​​​​​ Thu, 14 Jun 2018 11:43:51 GMT wallaby:workers Failed to map the stack to user code, entry message: Must use import to load ES Module: file:///c:/Users/xanf/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/7bce06916b362d4b/instrumented/tests/demo.mjs, stack: C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1
​​​​​[Info]​​​​​ Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: file:///c:/Users/xanf/.vscode-insiders/extensions/WallabyJs.wallaby-vscode-1.0.86/projects/7bce06916b362d4b/instrumented/tests/demo.mjs
​​​​​[Info]​​​​​     at Object.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at Object.Gu (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at Object.u (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at Object.l (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at Object.<anonymous> (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at Object.apply (C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1)
​​​​​[Info]​​​​​     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1
​​​​​[Info]​​​​​     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1
​​​​​[Info]​​​​​     at C:\Users\xanf\Desktop\node-jwt-demo\node_modules\esm\esm.js:1
​​​​​[Info]​​​​​     at En (C:\Users\xanf\Desktop\node-jwt-demo\node_mo
```
(same applies on linux)

I assume that wallaby is applying default babel config of ava, which compiles import to require, and require fails for mjs files obviously

**Comment by xanf** [comment]
Just fyi, if I rename mjs files to js in tests folder and update configs - it works :(

**Comment by ArtemGovorov** [comment]
@xanf Thanks for providing the repo! This should help https://github.com/wallabyjs/public/issues/1661#issuecomment-389411837.

**Comment by mesqueeb** [comment]
Is AVA already supported on Wallaby?
The wallaby docs say nothing about which AVA version we need to use.
I'm getting:
> Failed to load configuration file:  Test framework [ava] is not supported​​
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.605

I'm using `"ava": "1.0.0-beta.6",`

Which version do I need in order for Wallaby to work?

**Comment by ArtemGovorov** [comment]
@mesqueeb Yes, AVA is supported in Wallaby. Please take a look into this sample repo https://github.com/wallabyjs/ava-sample (it's now using `"ava": "1.0.0-beta.6"`), to see if it's working for you. If it does, please share a sample repo demonstrating the issue with no live feedback, we are happy to take a look and help with your config.

**Comment by mesqueeb** [comment]
@ArtemGovorov Thank you so much. Should I open a separate thread?
I had trouble with Ava on Beta 6 even without Wallaby, so now I reverted back to `v0.25.0`.
Ava currently runs without problem.

However, when starting Wallaby I'm currently having the problem that `preset-stage-4` probably doesn't include `object-rest-spread` support:
```js
//​​ Failed to run compilers on src/makeMutations.js, SyntaxError: src/makeMutations.js: Unexpected token (38:19)​​
 mutations = {...mutations, ...childrenMutations}​​
               ^​​
```
I'm using the `presets: ['@ava/babel-preset-stage-4']` as I copied the `wallaby.conf.js` from the repo you gave me. : )

This is my `.babelrc`
```JSON
{
  "presets": [
    ["env", {
      "modules": false
    }]
  ],
  "plugins": ["external-helpers", "babel-plugin-transform-object-rest-spread"]
}
```

**Comment by ArtemGovorov** [comment]
@mesqueeb Thanks for sharing the repo. Had sent you the PR to make it work https://github.com/mesqueeb/VuexEasyAccess/pull/6.
