### ISSUE TITLE
Uses wrong version of `babel-core`

### ISSUE THREAD

**Issue by kevva** [wallabyjs/public#1544]
### Issue description or question

When installing modules that has a newer version of Babel (`7.x.x`) as a dependency even though you're using an older one in your project it causes Wallaby to use Babel in `@babel/core`. I can fix this by setting the `babel` option in `wallaby.compilers.babel()` but ideally I'd expect it to use what the `package.json` in the project root has listed as dependency. Right now it seems like it's defaulting to `@babel/core` if the directory exists in `node_modules`.

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
	compilers: {
		'**/*.js*': wallaby.compilers.babel()
	}
});
```

### Code editor or IDE name and version

Visual Studio Code 1.21.0-insider

### OS name and version

macOS 10.12.6

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version. Now wallaby will use the version specified in your `package.json` `dependencies` or `devDependencies`.

**Comment by kevva** [comment]
Thank you! Does it take `babel-cli` into account? You don't need both `babel-core` and `babel-cli`.

**Comment by ArtemGovorov** [comment]
Good point, [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) includes `babel-cli` scenario.

**Comment by ProLoser** [comment]
Does this work for `babel-register` and `babel-loader`?

**Comment by ArtemGovorov** [comment]
@ProLoser `babel-register` and `babel-loader` and not loaded/used by `wallaby.compilers.babel()`.
