### ISSUE TITLE
Blank lines sometimes swallow click events

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1545]
### Issue description or question

If I click on a *blank line with a failing test*, such as 73 in the following photo, nothing happens: the cursor remains where it already was.
If I click on any other line, including non-blank lines with failing tests or blank lines with no or passing tests, the cursor is updated properly.

Two sub-bugs here:
* Why are line 73 and other blank lines marked as failing?
* Why are click events being swallowed?

![image](https://user-images.githubusercontent.com/3335181/37065578-295ef3fa-2156-11e8-9b9c-47b53493f40b.png)

### Wallaby.js configuration file

```javascript
// Simplified to remove some project-specific wildcards
module.exports = () => ({
	env: {
		type: "node",
	},

	files: [
		"tsconfig.test.json",
		"test/unit/jest.config.js",
		"test/unit/setup.js",
		"config/polyfills.js",
		"src/**/*.ts",
		"!src/**/*.test.ts",
		"src/**/*.tsx",
		"!src/**/*.test.tsx",
		"src/External/**/*.js",
	],

	filesWithNoCoverageCalculated: [
		"config/*",
		"src/Adapters/**",
		"src/External/**",
		"src/*.tsx",
		"src/*.ts",
	],

	hints: {
		ignoreCoverage: /istanbul ignore next/,
	},

	setup: (wallaby) => {
		wallaby.testFramework.configure(require("./test/unit/jest.config"));
	},

	testFramework: "jest",

	tests: [
		"src/**/*.test.ts",
		"src/**/*.test.tsx",
	],
});
```

### Code editor or IDE name and version

Visual Studio Code v1.20.1

### OS name and version

Windows 10 and Windows Server 2016

**Comment by ArtemGovorov** [comment]
> Why are line 73 and other blank lines marked as failing?

They shouldn't. It looks like an issue with source maps (most likely because jest transforms are applied redundantly). 

- does the issue show up immediately as you start wallaby and persists when you're editing the file?
- could you please share the `./test/unit/jest.config.js` file?

**Comment by JoshuaKGoldberg** [comment]
The issue is nondeterministic :( sometimes it shows up immediately, sometimes it doesn't.

`./test/unit/jest.config.js`:

```javascript
/*!
 * Copyright Microsoft Corporation. All rights reserved.
 */

const path = require("path");

module.exports = {
	collectCoverageFrom: [
		"src/*/**/*.ts*",
		"!src/*",
		"!src/Adapters/**",
		"!src/External/**",
		"!src/config/*",
		"!src/typings/**",
	],
	globals: {
		"ts-jest": {
			tsConfigFile: "./tsconfig.test.json",
		},
	},
	moduleFileExtensions: [
		"js",
		"ts",
		"tsx",
	],
	rootDir: path.join(__dirname, "../../"),
	setupFiles: [
		"<rootDir>/config/polyfills.js",
	],
	setupTestFrameworkScriptFile: "<rootDir>/test/unit/setup",
	testEnvironment: "jsdom",
	testMatch: [
		"<rootDir>/src/**/?(*.)test.ts?(x)",
	],
	testURL: "http://localhost",
	transform: {
		"^.+\\.tsx?$": "ts-jest",
	},
	transformIgnorePatterns: [
		"[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$",
	],
};
```

`tsconfig.test.json`:

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017"
  }
}
```

`tsconfig.json`:

```jsonc
{
  "compilerOptions": {
    "allowJs": true,
    "baseUrl": ".",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": [
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "outDir": "build/dist",
    "rootDir": "src",
    "strict": true,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "pretty": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
```

**Comment by ArtemGovorov** [comment]
Does it ever happen with a clear wallaby cache (after config file change, even adding a space anywhere in it and saving triggers clearing the cache)?

Try this in your wallaby config `setup`:
```javascript
setup: (wallaby) => {
                const config = require("./test/unit/jest.config");
                config.transform = {};
		wallaby.testFramework.configure(config);
	},
```

If this doesn't help, we'll need a sample repo to reproduce the issue. BTW, the issue may show up even if the code is not covered (grey indicators on empty lines), in which case it hopefully shouldn't be too hard to isolate an example.

**Comment by JoshuaKGoldberg** [comment]
I made that change but it didn't help.

Also, the buggy behavior is happening on passing blank lines too. Changed the title to reflect that.

![image](https://user-images.githubusercontent.com/3335181/37110996-63ba8008-21f3-11e8-98ba-7abdb0f703a4.png)

**Comment by JoshuaKGoldberg** [comment]
I can't reproduce the error anymore...!
