### ISSUE TITLE
Mocha-Snapshots

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1546]
### Issue description or question

this is more of a question then issue. I am using package "mocha-snapshots" which saves snapshots even for Mocha tests. This is obvious problem for wallaby, as wallaby runs from a wallaby temp project directory. therefore, when I update snapshots they update only in the temp directory and not in the main directory. Any idea how to solve this? Thanks!

### Code editor or IDE name and version

Visual Studio Code

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Depending on how exactly `mocha-snapshots` saves snapshots to disk, you may use wallaby `setup` function to monkey-patch/intercept the function it's using to save snapshots and save them to and if the file is saved to `wallaby.projectCacheDir` (tmp folder), and looks like a snapshot, then save it to the `wallaby.localProjectDir` (project folder) as well.

Pseudo code assuming `mocha-snapshots` is using `fs.writeFileSync`:

```javascript
setup: (wallaby) => {
  const fs = require('fs');
  if (fs.patched) return;

  const writeFile = fs.writeFileSync;
  fs.writeFileSync = function(file, content) {
    if (file looks like snapshot) { 
      writeFile(file.replace(wallaby.projectCacheDir, wallaby.localProjectDir), content);
    }
    return writeFile.apply(this, arguments);
  }
  fs.patched = true;
}
```

Hope it makes sense.

**Comment by tomitrescak** [comment]
@ArtemGovorov that is pure gold. Thanks a lot! Works like charm ;)
