### ISSUE TITLE
Runtime error: TypeError: 'undefined' is not an object (evaluating 'b.call')

### ISSUE THREAD

**Issue by taeyangoh** [wallabyjs/public#155]
Hi, 

If I require module "angular-local-storage", wallaby console throws below error message and stops test process.  

Runtime error: TypeError: 'undefined' is not an object (evaluating 'b.call')
Finished executing 0 affected test(s)

**Comment by ArtemGovorov** [comment]
Hello,

Could you please share your wallaby.js config file (or send it to artem.govorov@gmail.com)?

I'm trying to reproduce the issue, but can't do it yet. Here is what I do (using webpack):

![screen shot 2015-06-15 at 6 52 47 pm](https://cloud.githubusercontent.com/assets/979966/8156429/1b8a9d50-1390-11e5-8f82-4d72f1e3dc80.png)

**Comment by taeyangoh** [comment]
Sorry, I should narrow down the error condition.    
Thanks!

Taeyang.

**Comment by ArtemGovorov** [comment]
Oh, it looks like you've closed the issue while I was writing my answer. Is it still reproducible?
