### ISSUE TITLE
Global jasmine custom matchers not working

### ISSUE THREAD

**Issue by ivarvh** [wallabyjs/public#1550]
### Issue description or question

We have a beforeAll outside all describes that adds custom matchers to jasmine. This works when running with Karma, but with wallaby.js, our custom matchers are not loaded. When I console.log in the beforeAll, I see that it is executed (once). How do we configure this?

### Wallaby.js configuration file

```javascript
files: [
      {pattern: 'test-config/wallabyjs-spec-bundle.js', load: false},
      {pattern: 'test-config/karma-require.js', load: false},
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'src/**/globals.ts', ignore: false}, // <-- this one contains the beforeAll
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'src/**/*.d.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],
```

### Code editor or IDE name and version

IntelliJ IDEA 2017.3.4

### OS name and version

OSX High Sierra

**Comment by ArtemGovorov** [comment]
Try specifying the file in your [wallaby webpack config `entryPatterns`](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns):

```javascript
...
var wallabyPostprocessor = wallabyWebpack({
    entryPatterns: [
            'src/**/globals.js', // <--
            'src/**/*.spec.js',
            'test/**/*.spec.js'
            ]
});
...
```

If it doesn't work, please share a sample repo demonstrating the issue, we are happy to take a look and help with the config.

**Comment by ivarvh** [comment]
That works! Thank you!
