### ISSUE TITLE
npm package resolve with wallaby

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1552]
### Issue description or question
I'm using the [browserify/resolve](https://github.com/browserify/resolve) package to in-order to specify where to search for ``node_modules``. This is causing an issue with wallaby because ``process.cwd()`` is something like ``/Users/chris/Library/Caches/WebStorm2018.1/wallaby/projects/b84186d7a4408a81/instrumented``, which does not contain the ``node_modules`` folder. How can I get wallaby to work correctly with this use case.

I can provide an example if you provide me with your npm handle (private npm packages required).

### Wallaby.js configuration file

```javascript
'use strict';

const wallaby = (wallabyConfig) => {
    return {
        files: [
            { pattern: 'src/**/__sandbox__/**/*', instrument: false },
            { pattern: 'src/**/__sandbox__/**/.*', instrument: false },
            { pattern: '.babelrc+(.js|)', instrument: false },

            'src/**/*.js',
            'jest.config.js',
            '.env',
            'src/**/*.snap',
            '!src/**/*.test.js'
        ],

        tests: ['src/**/*.test.js'],

        compilers: {
            '**/*.js': wallabyConfig.compilers.babel()
        },

        hints: {
            ignoreCoverage: /ignore coverage/
        },

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',

        setup: (setupConfig) => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (setupConfig.projectCacheDir !== process.cwd()) {
                process.chdir(setupConfig.projectCacheDir);
            }

            require('babel-polyfill');
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            jestConfig.transform = {
                '__sandbox__.+\\.jsx?$': 'babel-jest'
            };
            setupConfig.testFramework.configure(jestConfig);
        }
    };
};

module.exports = wallaby;
```

### Code editor or IDE name and version
```
WebStorm 2018.1 EAP
Build #WS-181.4096.25, built on March 8, 2018
JRE: 1.8.0_152-release-1136-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### OS name and version

``macOS 10.13.3``

**Comment by ArtemGovorov** [comment]
> I can provide an example if you provide me with your npm handle (private npm packages required).

Thanks, here is [my npm account](https://www.npmjs.com/~artemgovorov).

**Comment by chrisblossom** [comment]
Here you go: [chrisblossom/wallaby-issue-1552](https://github.com/chrisblossom/wallaby-issue-1552)

If you need further information let me know.

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

> This is causing an issue with wallaby because ``process.cwd()`` is something like ``/Users/chris/Library/Caches/WebStorm2018.1/wallaby/projects/b84186d7a4408a81/instrumented``, which does not contain the ``node_modules`` folder. How can I get wallaby to work correctly with this use case.

You have correctly identified the problem - `browserify/resolve` package is using `process.cwd()`, but unfortunately doesn't respect `NODE_PATH` in its module resolution process, despite the fact that it states that it "implements the node require.resolve() algorithm" (and `require.resolve` does take the `NODE_PATH` value into account).

The easiest way to solve it is to give `browserify/resolve` what it wants:

```javascript
const wallaby = (wallabyConfig) => {
    ...

    return configManager({
        ...
        config: {
            ...

            setup: (setupConfig) => {
               
                ...
                process.chdir(setupConfig.localProjectDir); // <--
                const jestConfig = require('./jest.config');
                if (setupConfig.projectCacheDir !== process.cwd()) {
                    process.chdir(setupConfig.projectCacheDir);
                }
                ...
            },
        },
    });
};
```

**Comment by chrisblossom** [comment]
@ArtemGovorov could that break other things? Is it possible for me to change the wallaby cache file to a different location? For example, https://github.com/avajs/find-cache-dir ? ``NODE_PATH`` seems very fragile, and even the node docs say it shouldn't be needed any longer.

**Comment by ArtemGovorov** [comment]
It shouldn't break anything, because it's only used to `require('./jest.config')`. Unless jest config loading breaks when loaded in project dir, and I assume it doesn't because you use it outside wallaby context as well.

**Comment by chrisblossom** [comment]
Thanks for the help!

**Comment by chrisblossom** [comment]
@ArtemGovorov looks like the first thing I tried to to ended up with the same error. I've updated the repo as an example.

https://github.com/chrisblossom/wallaby-issue-1552

**Comment by ArtemGovorov** [comment]
Thanks for updating the repo. Looks like `process.chdir` is not enough to make `resolve` work from wallaby cache. We have made some changes in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to address the issue, and now it should work for you even with your original config (without the `process.chdir(setupConfig.localProjectDir)` call).

**Comment by chrisblossom** [comment]
Thank you! Looks like ``process.chdir`` can completely be removed from my config? Also, does this mean https://github.com/wallabyjs/public/issues/1402#issuecomment-346237702 isn't needed anymore as well?

**Comment by ArtemGovorov** [comment]
> Looks like ``process.chdir`` can completely be removed from my config?

If your tests are not calling `process.chdir`, then yes. AFAIR, the `process.chdir(setupConfig.projectCacheDir);` call was added because your tests were changing the process dir (and, if interrupted, were not restoring it back)? You may try removing to see how it goes.

> Also, does this mean https://github.com/wallabyjs/public/issues/1402#issuecomment-346237702 isn't needed anymore as well?

It depends, but may not be required, try removing it to see how it goes.

**Comment by chrisblossom** [comment]
> Looks like process.chdir can completely be removed from my config?

https://github.com/wallabyjs/public/issues/1268 was the original issue. I just tried it without the suggested ``chdir`` fix and it seems to work. I'm actually surprised by this. Is this expected?

> Also, does this mean #1402 (comment) isn't needed anymore as well?

Just tried it. Still needs the explicit NODE_PATH. Node algorithm is still acts differently than from the project root.

**Comment by ArtemGovorov** [comment]
> I just tried it without the suggested ``chdir`` fix and it seems to work. I'm actually surprised by this. Is this expected?

We have changed a few things (even before the last change) around `rootDir` handling in Jest integration, so it's possible that `chdir` call (the original one) wasn't required in a few latest wallaby versions.
