### ISSUE TITLE
PrettyFormatPluginError: Cannot read property 'inserted' of undefined

### ISSUE THREAD

**Issue by vhlongon** [wallabyjs/public#1554]
### Issue description or question
After updating Wallaby I am getting this error: `PrettyFormatPluginError: Cannot read property 'inserted' of undefined` for snapshot tests. I have a colleague running the same version for vs code and Wallaby and not having any issues. Running my tests directly on terminal don't output any error, issue either.

### Wallaby version
v1.0.78

### Wallaby.js configuration file
``` 
module.exports = wallaby => ({
  files: ['fileMock.js', 'src/**/*.js*', '!src/**/__tests__/*.js*'],
  tests: ['src/**/__tests__/*.js*'],
  compilers: {
    'src/**/*.js*': wallaby.compilers.babel(),
  },
  env: {
    type: 'node',
    runner: 'node',
  },
  testFramework: 'jest',
});

``` 

```javascript
//Sample test
import React from 'react';
import { shallow } from 'enzyme';
import toJson from 'enzyme-to-json';
import Component from '../Component';

it('renders a wrapper', () => {
    const component = shallow(<Component />);
    const wrapper = component.find('div');
    expect(toJson(wrapper.dive())).toMatchSnapshot();
  });
```

### Code editor or IDE name and version

Visual Studio Code v1.21.0

### OS name and version
OSX
10.13.3

**Comment by ArtemGovorov** [comment]
Could you please share
- the full error stack, you may copy the stack as reported by Jest from the [Wallaby Console output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) in VS Code.
- your Jest config,
- your package.json `dependencies` and `devDependencies` sections.

**Comment by vhlongon** [comment]
Jest Config ( on package.json):
```
"jest": {
    "setupFiles": [
      "./testSetup.js"
    ],
    "setupTestFrameworkScriptFile": "./testFrameworkSetup.js",
    "testEnvironment": "jsdom",
    "moduleNameMapper": {
      "\\.(jpeg|jpg|svg)$": "<rootDir>/fileMock.js"
    },
    "coverageReporters": [
      "lcov",
      "text"
    ],
    "collectCoverageFrom": [
      "src/**",
      "!src/**/index.js",
      "!src/**/__snapshots__/**"
    ]
  },
```
Dependencies:
``` 
"
[wallaby-console-output.txt](https://github.com/wallabyjs/public/files/1810154/wallaby-console-output.txt)
dependencies": {
    "array-find": "^1.0.0",
    "babel-runtime": "^6.26.0",
    "classnames": "^2.2.5",
    "eti-assets": "^2.5.0",
    "eti-js-utils": "^2.3.0",
    "eti-js-validation": "^1.4.0",
    "eti-react-components": "^6.2.1",
    "eti-react-form": "^1.1.2",
    "eti-react-texts-provider": "^3.0.1",
    "eti-styles": "^2.0.0",
    "prop-types": "^15.5.10",
    "react-modal": "^3.1.11",
    "recompose": "^0.26.0",
    "redux-form": "^7.3.0",
    "redux-modal": "^1.5.2"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-eslint": "^8.0.1",
    "babel-loader": "^7.1.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.1",
    "enzyme-redux": "^0.1.6",
    "enzyme-to-json": "^3.3.0",
    "eslint": "^4.4.1",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-config-prettier": "^2.6.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-prettier": "^2.3.1",
    "eslint-plugin-react": "^7.2.0",
    "eti-js-test-utils": "^2.0.1",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^3.0.5",
    "jest": "^22.2.1",
    "prettier": "^1.7.4",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6",
    "react-test-renderer": "^16.0.0",
    "redux": "^3.7.2",
    "redux-test-utils": "^0.2.1",
    "svgr": "^1.8.1",
    "webpack": "^4.1.0",
    "webpack-cli": "^2.0.10",
    "webpack-dev-server": "^3.1.0"
  },
  "peerDependencies": {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-redux": "^5.0.6"
  },
```

**Comment by ArtemGovorov** [comment]
Thanks. Even though I can't reproduce the issue locally (because I don't have an access to `eti-*` modules), I have a guess why it's happening. For some reason, one of your `eti-*` modules is using an older version of the `emotion` node module. Try this:

- remove and re-install your `node_modules`,
- if it doesn't help, then possibly you have some older (globally) installed version of one of the modules (so when running from wallaby Jest gets confused). Try checking these folders to see if any of them exist (and delete them if so):
```
/Users/your_username/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/projects/node_modules
/Users/your_username/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/node_modules
/Users/your_username/.vscode/extensions/node_modules
/Users/your_username/.vscode/node_modules
/Users/your_username/node_modules
/Users/node_modules
/node_modules
```

**Comment by vhlongon** [comment]
Hi, thanks for the reply!

I had indeed some eti*  packages installed globally. I have uninstall them. 
I have deleted the wallaby folder under `.vscode/extentions` and  force update.
I have also deleted my project `node_modules` folder, run `npm i `.

But even after these steps I am unable to get wallaby to work properly (still getting the same errors)

**Comment by ArtemGovorov** [comment]
Could you please create a test like this one in any of your test files:
```javascript
it('renders a wrapper', () => {
  console.log(require('emotion').caches);
  console.log(require.resolve('emotion'));
});
```
and let me know what it prints?

**Comment by nathanvale** [comment]
i am also getting a similar error

`H1 › should render
​​​​​[Info]​​​​​     TypeError: Cannot read property 'test' of undefined
​​​​​[Info]​​​​​ 
​​​​​[Info]​​​​​       15 |         $_$wf(15);
​​​​​[Info]​​​​​       16 |         var component = ($_$w(15, 12), createComponent());
​​​​​[Info]​​​​​     > 17 |         $_$w(15, 13), expect(component).toMatchSnapshot();
​​​​​[Info]​​​​​       18 |     });
​​​​​[Info]​​​​​       19 | });
​​​​​[Info]​​​​​       20 | $_$wpe(15);
​​​​​[Info]​​​​​       
​​​​​[Info]​​​​​       at findPlugin (../../node_modules/pretty-format/build/index.js:272:20)
​​​​​[Info]​​​​​       at prettyFormat (../../node_modules/pretty-format/build/index.js:429:22)
​​​​​[Info]​​​​​       at Object.throwingMatcher (node_modules/expect/build/index.js:214:24)
​​​​​[Info]​​​​​       at Object.<anonymous> `

**Comment by ArtemGovorov** [comment]
@nathanvale This looks like a different error. Quite possible something goes wrong when you call `expect.addSnapshotSerializer` and the added snapshot serialiser is corrupted (or undefined) for some reason. Try checking logging all of the `expect.addSnapshotSerializer` calls in your app to make sure correct values are passed (and not null or undefined). If it doesn't help, please share a sample repo where we could reproduce the issue, we are happy to have a look ASAP.

**Comment by vhlongon** [comment]
HI @ArtemGovorov. I found out what the problem was with the help a colleague. I had a node_modules installed on folder up where my projects are located. That was probably an old version of emotion installed there which confused Wallaby. Thanks again for the quick replies ;)

**Comment by vhlongon** [comment]
One thing though. Is there any change of making Wallaby looking preferably at packages installed on the project folder?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> Is there any change of making Wallaby looking preferably at packages installed on the project folder?

It's what supposed to happen. We'll investigate it.
