### ISSUE TITLE
Resolve issue when using typescript 'outDir' and want to access upper level files

### ISSUE THREAD

**Issue by JimiC** [wallabyjs/public#1557]
This issue has the purpose to show how to solve the case when using `wallaby.js` and you need to access files that are on upper levels than the source code.

The example uses a `typescript` project but the concept is applied on any other similar case.

Let's assume that you have a project structure like:
```
./
|-- src
|   `-- index.ts
|
|-- test
|   | -- fixtures
|   |    |-- some.json
|   |    `-- other.json
|   |
|   `-- index.spec.ts
|
|-- package.json
|-- tsconfig.json
`-- wallaby.js
```

Now let's assume that your `tsconfig.json` uses the `outDir` compiler option in order for the compiler to spit the `js` files to a specific folder. Let's name that folder `out`.

So your `tsconfig.json` may look like this:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "skipLibCheck": true,
    "target": "es6",
    "outDir": "out",
    "lib": [
      "es6"
    ],
    "sourceMap": true,
    "rootDir": "."
  },
  "include": [
    "src/**/*.ts",
    "test/**/*.ts"
  ]
}
```

Finally, let's assume that you're using `import` to import `json` in your `index.test.ts` code like:

```ts
import some from '../../test/fixtures/some.json'
import other from '../../test/fixtures/other.json'
import packageJson from '../../package.json'
```

by using the known typings trick:

```ts
declare module '*.json';
```

or

```ts
declare module "*.json" {
  const value: any;
  export default value;
}
```
whatever works for you.

Notice that in order to access the `json` files we are telling the importation to go two levels up by using `../../` and not `../` when our `root` folder is just one level up from our code.

Why is that?

When compilation gets performed our project structure will look like:
```
./
|-- out
|   |-- src
|   |   |-- index.js
|   |   `-- index.js.map
|   |
|   ` -- test
|        |-- index.spec.js
|        `-- index.spec.js.map
|
|-- src
|   `-- index.ts
|
|-- test
|   |-- fixtures
|   |   |-- some.json
|   |   `-- other.json
|   |
|   `-- index.spec.ts
|
|-- package.json
|-- tsconfig.json
`-- wallaby.js
```

and in order for `require` to load the `json` content, you have to tell it the relative path from the compiled folder, in our case `out`, which adds one additional level in our structure.

So from `./out/test/index.test.js` we need to go two levels up (`../../`) to meet the `root` folder and then navigate down to `test/fixtures/`.

So far so good, our code works and our tests also (assuming we use `mocha/jasmine/jest/ava` or other similar test frameworks).

Now it's time to wire `wallaby`.

Things are simple here. We create a `wallaby.js` file that looks like:
```js
module.exports = (wallaby) => ({
  files: [
    "src/**/*.ts",
    "test/fixtures/*.json",
    "package.json"
  ],
  tests: [
    "test/**/*.test.ts"
  ],
  hints: {
    ignoreCoverage: /\/* wallaby ignore next\/*/
  },
  testFramework: "mocha",
  env: {
    type: "node"
  },
  delays: {
    run: 500
  },
  debug: true,
  reportConsoleErrorAsError: true,
  setup: (wallaby) => wallaby.testFramework.ui('bdd')
});

```

We start `wallaby` and... test fails. WHY???

Here starts the debugging nightmare!

80% of solving an issue is to undestand the issue itself. Finding the solution is the rest 10% and applying it, is the remaining 10%.

So what's the 80%?

`wallaby` uses it's own project cache directory to store the compiled code exposed as `projectCacheDir`. And our project structure in it doesn't match the one our project has after the compilation.

Specifically, `wallaby` structure looks like:
```
./
|-- instrumented
|   |-- src
|   |   |-- index.js
|   |   `-- index.ts
|   |
|   |-- test
|   |   |-- fixtures
|   |   |   |-- some.json
|   |   |   `-- other.json
|   |   |
|   |   |-- index.spec.js
|   |   `-- index.spec.ts
|   |
|   `-- package.json
|
`-- original
    |-- src
    |   `-- index.ts
    |
    |-- test
    |   |-- fixtures
    |   |   |-- some.json
    |   |   `-- other.json
    |   |
    |   `-- index.spec.ts
    |
    `-- package.json
```
as you can notice it's missing that extra additional level our compiled structure looks like.

We have to move the `test/fixture` folder up one level. So how do we tell `wallaby` about it?

Can we use `projectCacheDir`?
- No, `projectCacheDir` is read-only.

Can we use `process.cwd` manipulation?
- No, that won't work either.

**Then what? Tell me!!!**

The solution is by using `preprocessors`.

Just by adding:
```js
  preprocessors: {
    '**/test/fixtures/*.json': (file, done) => {
      done(file.rename(`../${file.path}`).content)
    }
  },
```
in `wallaby.js`, we are telling it to rename/move our `json` files up one level.

Now `wallaby` structure looks like:
```
./
|-- instrumented
|   |-- src
|   |   |-- index.js
|   |   `-- index.ts
|   |
|   |-- test
|   |   |-- fixtures
|   |   |
|   |   |-- index.spec.js
|   |   `-- index.spec.ts
|   |
|   `-- package.json
|
|-- original
|   |-- src
|   |   `-- index.ts
|   |
|   |-- test
|   |   |-- fixtures
|   |   |   |-- some.json
|   |   |   `-- other.json
|   |   |
|   |   `-- index.spec.ts
|   |
|   `-- package.json
|
`-- test
    `-- fixtures
        |-- some.json
        `-- other.json
```
and `wallaby` is happy!!!

And so are you.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for sharing the solution!

Another option would be to intercept imports and, if a test fixture is being imported, then redirect the import to the `./test/fixtures`. Here is an [example from RxJs wallaby config](https://github.com/ReactiveX/rxjs/commit/acda6e8187ec1b82179309cc97bc7a2d2b3e5b79#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR37) when it was redirecting requests made to `dist/cjs` back to `src`.

I would however point out that the issue is tricky, and may cause other issues even without wallaby. You are running wallaby on your project's root, but expecting it to behave like it was running on the `./out` dir. Your code inside the root is making an assumption that it is already compiled and resides in `./out` dir, also your source code depends on the build setting, and it's not very good. For example if you change `"outDir": "out"` to "outDir": "dist/out" - your code is going to break even without wallaby because of the additional folder level. Also you are going to hit the same issue if you run Jest or Mocha on your root folder (as opposed to on your `./out` dir).

**Comment by JimiC** [comment]
@ArtemGovorov Some trade-offs are required when project structure changes but I believe this isn't something the author can't fix. The point of the OP was to provide the concept on how to configure `wallaby` to work in such scenarios. Thanks for the suggestions though and for a great product.
