### ISSUE TITLE
Wallaby not working with Typescript + Jest 22

### ISSUE THREAD

**Issue by borislit** [wallabyjs/public#1558]
### Issue description or question
Im getting the following error when trying to configure Wallaby with Typescript + Jest 22.
See the error below:

> ​​​​​[Info]​​​​​ Wed, 14 Mar 2018 14:48:28 GMT wallaby:workers Sandbox (active) [0jj9q] error: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
​​​​​[Info]​​​​​ TypeError: Cannot read property '_loadConfigDependencies' of undefined
​​[Error] Runtime error: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?​​
​​[Error] TypeError: Cannot read property '_loadConfigDependencies' of undefined​​
​​[Error]     at Module._compile (module.js:573:32)​​
​​[Error]     at Object.Module._extensions..js (module.js:582:10)​​
​​[Error]     at Module.load (module.js:490:32)​​
​​[Error]     at tryModuleLoad (module.js:449:12)​​
​​[Error]     at Function.Module._load (module.js:441:3)​​
​​[Error]     at Module.require (module.js:500:17)​​
​​[Error]     at require (internal/module.js:20:19)​​
​​[Error]     at Module._compile (module.js:573:32)​​
​​[Error]     at Object.Module._extensions..js (module.js:582:10)​​
​​[Error]     at Module.load (module.js:490:32)​​
​​[Error]     at tryModuleLoad (module.js:449:12)​​
​​[Error]     at Function.Module._load (module.js:441:3)​​
​​[Error]     at Module.runMain (module.js:607:10)​​
​​[Error]     at run (bootstrap_node.js:382:7)​​
​​[Error]     at startup (bootstrap_node.js:137:9)​​
​​[Error]     at bootstrap_node.js:497:3​​
​​​​​[Info]​​​​​ Wed, 14 Mar 2018 14:48:28 GMT wallaby:workers Failed to map the stack to user code, entry message: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
​​​​​[Info]​​​​​ TypeError: Cannot read property '_loadConfigDependencies' of undefined, stack: jest-cli node module is not found or the version is not supported, missing `npm install jest --save-dev` or `npm install jest-cli --save-dev`?
​​​​​[Info]​​​​​ TypeError: Cannot read property '_loadConfigDependencies' of undefined
​​​​​[Info]​​​​​     at Object.<anonymous> (/Users/borisl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/wallaby/runners/node/jest@0.4.3/initializer.js:28:69)
​​​​​[Info]​​​​​     at Module._compile (module.js:573:32)
​​​​​[Info]​​​​​     at Object.Module._extensions..js (module.js:582:10)
​​​​​[Info]​​​​​     at Module.load (module.js:490:32)
​​​​​[Info]​​​​​     at tryModuleLoad (module.js:449:12)
​​​​​[Info]​​​​​     at Function.Module._load (module.js:441:3)
​​​​​[Info]​​​​​     at Module.require (module.js:500:17)
​​​​​[Info]​​​​​     at Module.r.require (/Users/borisl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/wallaby/server.js:19:29641)
​​​​​[Info]​​​​​     at require (internal/module.js:20:19)
​​​​​[Info]​​​​​     at r (/Users/borisl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/wallaby/server.js:14:114)
​​​​​[Info]​​​​​     at /Users/borisl/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.78/wallaby/server.js:14:305
​​​​​[Info]​​​​​     at m 

> 

### Wallaby.js configuration file

```javascript
'use strict';

module.exports = function () {
  return {
    files: [
      {pattern: 'src/templates/**', instrument: false},
      // {pattern: 'test/**/*.spec.[j|t]s', ignore: true},
      // {pattern: 'test/**/*.spec.[j|t]sx', ignore: true},
      {pattern: 'test/**/*.e2e.[j|t]s', ignore: true},
      {pattern: 'app/**/*.spec.[j|t]s', ignore: true},
      {pattern: 'app/**/*.spec.[j|t]sx', ignore: true},
      {pattern: 'src/assets/**', instrument: false},
      {pattern: 'src/**', instrument: true},
      {pattern: 'target/**/*.json', instrument: false},
      {pattern: 'templates/**', instrument: false},
      {pattern: 'index.js', instrument: true},
      {pattern: 'package.json', instrument: false},
      {pattern: 'app/tsconfig.json', instrument: false},
      {pattern: 'pom.xml', instrument: false},
      'testkit/**/*.[j|t]s',
      'testkit/**/*.[j|t]s',
      'test/**/*.[j|t]s',
      'test/**/*.[j|t]sx',
      'src/**/*.scss'
    ],

    tests: [
      // {pattern: 'test/**/*.spec.[j|t]s'},
      // {pattern: 'test/**/*.spec.[j|t]sx'},
      {pattern: 'app/**/*.spec.[j|t]s'},
      {pattern: 'app/**/*.spec.[j|t]sx'},
    ],

    // compilers: {
    //   '**/*.js{,x}': wallaby.compilers.babel({
    //     babelrc: true,
    //     plugins: [
    //       require.resolve('babel-plugin-transform-es2015-modules-commonjs')
    //     ]
    //   })
    // },

    env: {
      type: 'node',
      runnner:'node'
    },
    debug: true,
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    },
    testFramework: 'jest',
    setup: () => {
      wallaby.testFramework.configure(require('./package.json').jest);
    }
  };
};

```
Package.json

```javascript
{
  "name": "@wix/scheduler-owner",
  "version": "0.0.0",
  "dependencies": {
    "@wix/bookings-customer-bookings-statics": "^1.0.107",
    "@wix/bookings-form-statics": "^1.0.1049",
    "@wix/wix-instance-parser-js": "^1.0.7",
    "global": "^4.3.1",
    "jquery": "~2.2.0",
    "moment": "^2.20.1",
    "moment-timezone": "^0.5.14",
    "react-module-container": "^1.0.1538"
  },
  "devDependencies": {
    "@types/angular": "^1.6.42",
    "@types/angular-mocks": "^1.5.8",
    "@types/angular-route": "^1.3.3",
    "@types/angular-translate": "^2.4.34",
    "@types/es6-shim": "^0.31.32",
    "@types/jasmine": "^2.8.6",
    "@types/jquery": "~2.0.37",
    "@wix/business-manager": "^1.0.2718",
    "@wix/business-manager-api": "^1.0.153",
    "@wix/business-manager-mini-home": "^1.0.261",
    "@wix/business-settings-api": "latest",
    "@wix/contacts-server": "^1.0.1219",
    "@wix/protractor-helpers": "^1.1.438",
    "@wix/wix-gruntfile-tslint-rules": "^1.0.0",
    "axios": "^0.17.1",
    "body-parser": "^1.18.2",
    "bower-art-resolver": "^2.0.9",
    "browserify": "^13.1.0",
    "chromedriver": "^2.34.1",
    "command-line-args": "^3.0.5",
    "duplicate-package-checker-webpack-plugin": "^2.1.0",
    "express": "^4.16.2",
    "express-session": "^1.15.6",
    "fetch-mock": "^5.13.1",
    "glob": "~6.0.4",
    "grunt-jscs": "^3.0.1",
    "grunt-run": "^0.8.0",
    "grunt-webpack": "^3.0.2",
    "html-loader": "^0.4.5",
    "jasmine-core": "~2.7.0",
    "jest": "~22.4.2",
    "jest-teamcity-reporter": "^0.9.0",
    "json-loader": "^0.5.7",
    "karma-chrome-launcher": "^2.2.0",
    "ng-annotate-loader": "^0.6.1",
    "ng-annotate-webpack-plugin": "^0.2.1-pre",
    "nock": "^9.1.6",
    "node-cmd": "^1.1.1",
    "node-http-proxy": "*",
    "raw-loader": "^0.5.1",
    "react-dom": "15.4.2",
    "ts-jest": "~22.4.0",
    "tslint": "~3.15.1",
    "tslint-config-wix": "^1.0.30",
    "typescript": "^2.7.1",
    "uglify-js": "2.8.29",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.10.0",
    "webpack-dev-server": "^2.11.0",
    "wix-gruntfile": "^0.1.899",
    "wix-statics-parent": "^1.0.606"
  },
  "scripts": {
    "release": "node_modules/wix-gruntfile/scripts/release.sh",
    "start": "grunt serve",
    "build": ":",
    "test": "node_modules/wix-gruntfile/scripts/test.sh && jest --maxWorkers=2 --silent",
    "test:jsdom": "jest --silent",
    "test:watchAll": "jest --watchAll --silent",
    "postinstall": "node_modules/wix-gruntfile/scripts/postinstall.sh"
  },
  "jest": {
    "testURL": "http://localhost:8880",
    "testResultsProcessor": "jest-teamcity-reporter",
    "globals": {
      "ts-jest": {
        "tsConfigFile": "app/tsconfig.json"
      }
    },
    "transform": {
      "^.+\\.tsx?$": "ts-jest"
    },
    "testMatch": [
      "**/app/**/*.spec.esm.ts",
      "**/app/**/*.html",
      "**/.tmp/**/*.html"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ],
    "setupTestFrameworkScriptFile": "./test-setup.js"
  },
  "private": true
}

```

### Code editor or IDE name and version

Visual Studio Code v1.21.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
From the error message it looks like you are using an old version of Wallaby Core (released prior to Nov 2017) and Jest 22 support was added after that date. Most likely your existing license free upgrades period had expired, so you need to contact support engineer to get a fresh license and [once the fresh license key is activated ](https://wallabyjs.com/docs/intro/license.html#visual-studio-code), you may [force the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and it should work for you.
