### ISSUE TITLE
Can't test child_process.fork()'d calls

### ISSUE THREAD

**Issue by leebenson** [wallabyjs/public#1559]
### Issue description or question

Wallaby throws the following error whenever it encounters .js files loaded by `child_process.fork()`:

> [Error] ReferenceError: $_$wp is not defined​​

Possibly related to #1553

For some context: I'm attempting to unit test some code that invokes an expensive Webpack API build via a forked process, to avoid blocking the main thread.

FWIW, I'm calling a plain .js file from within a Typescript script and using Jest.

The error can be replicated with the following Jest test:

```js
test("balks when forking", () => {
  require("child_process").fork(path.resolve(__dirname, "someFile.js"));
});
```

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
  return {
    files: [
      "src/**/*.ts?(x)",
      "src/**/*.js",
      "__tests__/components/*.ts?(x)",
      "__tests__/components/*.js",
      "*.json",
    ],

    tests: [
      '__tests__/*.test.ts'
    ],

    testFramework: 'jest',

    env: {
      type: 'node',
      runner: "node",
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
This is expected as wallaby doesn't support cross process coverage reporting. All you need to do is to set `instrument: false` for the `someFile.js` and it should work for you:

```diff
module.exports = function (w) {
  return {
    files: [
+     { pattern: "src/**/someFile.js", instrument: false },
      ...
    ],

    ...
  };
};
```
