### ISSUE TITLE
I get this error, which stops wallaby: `jest: failed to cache transform results in: `

### ISSUE THREAD

**Issue by samholder** [wallabyjs/public#1560]
### Issue description or question
Wallaby won't start my tests and seems to be because of this error in the logs:

`jest: failed to cache transform results in:`  and then some random file name

a bit of googling seems to point to a workaround by running jest with the `--runInBand` flag (though at a perf hit.)

the error message is:
```[Info]​​​​​ Thu, 15 Mar 2018 07:19:34 GMT wallaby:workers [8cl40] Loaded unknown number of test(s)
​​​​​[Info]​​​​​ Thu, 15 Mar 2018 07:19:35 GMT wallaby:workers Sandbox (active) [28s0i] error: Error: jest: failed to cache transform results in: \somepath\\AppData\Local\Temp\jest\jest-transform-cache-c--Src--UI-Assets-js-a7cc73bddb94bd83c0c211db85e3d556\ff\DriverSearchPopup_ffb389a1c78b7e354d0c14c0d9dd1aab
​​​​​[Info]​​​​​ Failure message: UNKNOWN: unknown error, open '\somepath\\AppData\Local\Temp\jest\jest-transform-cache-c--Src--UI-Assets-js-a7cc73bddb94bd83c0c211db85e3d556\ff\DriverSearchPopup_ffb389a1c78b7e354d0c14c0d9dd1aab'
​​[Error] Runtime error: Error: jest: failed to cache transform results in: \somepath\\AppData\Local\Temp\jest\jest-transform-cache-c--Src--UI-Assets-js-a7cc73bddb94bd83c0c211db85e3d556\ff\DriverSearchPopup_ffb389a1c78b7e354d0c14c0d9dd1aab​​
​​[Error] Failure message: UNKNOWN: unknown error, open '\somepath\\AppData\Local\Temp\jest\jest-transform-cache-c--Src--UI-Assets-js-a7cc73bddb94bd83c0c211db85e3d556\ff\DriverSearchPopup_ffb389a1c78b7e354d0c14c0d9dd1aab'​​
​​[Error]     at Object.fs.openSync (fs.js:652:18)​​
​​[Error]     at Object.fs.writeFileSync (fs.js:1299:33)​​
​​[Error]     at writeCacheFile (\some other path\js\node_modules\jest-runtime\build\transform.js:93:8)```

jest is at version:

`"jest": "^19.0.2"`

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
    files: [
        { pattern: 'jest/*.js', instrument: false, load: true },
        { pattern: 'package.json', instrument: false, load: true },
        'app/**/*.js',
        '!app/**/__tests__/*.js'
    ],
    tests: [
        'app/**/__tests__/*.js'
    ],
    env: {
        type: 'node',
        runner: 'node'
    },
    compilers: {
        'app/**/*.js': wallaby.compilers.babel()
    },
    workers: {
        initial: 10,
        regular: 5
    },
    testFramework: 'jest',
    bootstrap: () => {
        const config = require('./package.json').jest;
        wallaby.testFramework.configure(config);
    },
    debug: true
});
```

### Code editor or IDE name and version

Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:47:13.351Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

### OS name and version

Windows 7 Ent SP1

**Comment by ArtemGovorov** [comment]
Could you please share your `package.json` jest section?

**Comment by samholder** [comment]
Sure:

``` "jest": {
    "transform": {
      "^.+\\.js$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "/node_modules/(?!(spin.js))",
      "/node_modules/appliedsystems-web/node_modules/(?!(spin.js))"
    ]
  }```

**Comment by ArtemGovorov** [comment]
Thanks, try this:

```diff
    bootstrap: () => {
        const config = require('./package.json').jest;
+       config.transform = {};
        wallaby.testFramework.configure(config);
    },
```

**Comment by samholder** [comment]
This made a difference in that it tries to run the tests but I then get some claim of an error in one of the files in a package we are using. Usually this error was caused by some incompatibility in packages and removing the all the node_modules package and reinstalling it would fix the problem. When I run I get this error:

​​c:\Src\path\js\node_modules\spin.js\spin.js:114​​
​​export { Spinner };​​
​​^^^^^^​​

which seems related to the above jest config :)

**Comment by samholder** [comment]
it seems that adding this to my packages.json scripts config makes it happy again though

```
"scripts": {
    "test": "jest  --runInBand"
  },
```

**Comment by ArtemGovorov** [comment]
> it seems that adding this to my packages.json scripts config makes it happy again though

```
"scripts": {
    "test": "jest  --runInBand"
  },
```

Ah, it must have been some transient caching issue then, because wallaby doesn't depend/use `runInBand` setting nor package.json script test command.

You may revert your package.json change and it will still work for you.

**Comment by samholder** [comment]
Very strange as making this change consistently makes it work and removing it consistently makes it fail...

**Comment by ArtemGovorov** [comment]
It is strange indeed. I'm puzzled how it can affect wallaby. If you could put together a sample repo where we could reproduce the issue, we are happy to take a look and investigate.
