### ISSUE TITLE
Not working in VS Code 1.21.1

### ISSUE THREAD

**Issue by kavumbi** [wallabyjs/public#1561]
### Issue description or question
I just installed the extension in VS Code, registered the license and selected the configuration file. But the task bar does not show anything.  
### Wallaby.js configuration file

module.exports = function (w) {

    return {
      files: [
        'src/**/*.ts'
      ],
  
      tests: [
        'src/webparts/spPnPjsExample/tests/*.ts'
      ]
    };
  };
  

### Code editor or IDE name and version

Visual Studio Code 
Version 1.21.1
Commit 79b44aa704ce542d8ca4a3cc44cfca566e7720f1
Date 2018-03-14T14:46:47.128Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### OS name and version

Windows 10 home Fall Creator

**Comment by JRobber** [comment]
Open up the VSCode Output tab then select Wallaby.js Console from the dropdown. 

I'm also on 1.21.1 and it won't start for me.  I do see something in that console though.  I wonder if you're seeing the same.  If so I'll close my issue and piggy back on yours.

**Comment by ArtemGovorov** [comment]
@kavumbi Please check the [Wallaby Console output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) as suggested above. The first likely step to make it work is to exclude your `tests` from your `files` list like the error message in the output channel should suggest.

Also your config looks too simple for a real works apps (unless your app is not using ES modules). You may need to configure your [testing framework](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks), possibly configure [Webpack](https://wallabyjs.com/docs/integration/webpack.html) if you are using it, possibly [turn on Chrome runner](https://wallabyjs.com/docs/integration/chrome.html).

**Comment by kavumbi** [comment]
First, I don’t get the wallabyjs option in the VS Code Output window. 
About the test files being also included in the source files, I noticed it yesterday and changed but it didn’t work. 
When I open the same project in Visual Studio 2017, wallabyjs works without problem. 
As for my config, I know it is too simplistic but I wanted it to work first before making it more complex.

**Comment by ArtemGovorov** [comment]
> First, I don’t get the wallabyjs option in the VS Code Output window.

Hmm, it's interesting. Have you [started wallaby.js with the ""Start" command](https://wallabyjs.com/docs/intro/get-started-vscode.html#wallabyjs-command-palette)? Wallaby Console output channel should be displayed after you start it. 

If you have started wallaby with the start command, but the output channel doesn't show up, could you please:
- make and share a screenshot of your task bar panel (right side),
- open dev tools (`Help - Toggle Developer Tools`), open console and copy&paste any reported errors from there?

**Comment by kavumbi** [comment]
That did it. By using the “start” command, I am able to see the wallabyjs console in the output window. And the tests are run without problems. This issue can be closed. 
Thanks for the help. 
<img width="575" alt="vs code wallabyjs console" src="https://user-images.githubusercontent.com/4941100/37515737-130a5d0c-290c-11e8-86f2-334c6c0e73a3.PNG">
