### ISSUE TITLE
With new wallaby version shows errors in wrong lines (and even tests).

### ISSUE THREAD

**Issue by swayf** [wallabyjs/public#1562]
### Issue description or question
With new wallaby version shows errors in wrong lines (and even tests).
That's something new, that come with the last versions.

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

    return {
        files: [
            'tsconfig.json',
            'package.json',
            'app/*.ts',
            'app/src/**/*.ts',
            'app/src/**/*.json',
            '!app/src/**/__tests__/*.ts'
        ],

        tests: ['app/src/**/__tests__/*.ts'],

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',

        compilers: {
          '**/*.ts': w.compilers.typeScript({
              typescript: require('typescript'),
              noResolve: false
          })
        }
    };
};

```

### Code editor or IDE name and version
IntelliJ IDEA v18.1 RC and last stable version also

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
This is unlikely that is was caused by Wallaby changes. We haven't recently made any changes that might have affected line mappings.

Could you please provide a sample repo where we could reproduce the issue (one test with incorrectly mapped lines will be enough)? We're happy to look into in ASAP.

**Comment by swayf** [comment]
After upgrading outdated ts-jest, babel-jest and others works fine again..
sorry.. was not problem of wallaby =)
