### ISSUE TITLE
Hanging on "Downloading https://update.wallabyjs.com/wallaby.json?licensed=true"

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1566]
![screen shot 2018-03-19 at 4 08 02 pm](https://user-images.githubusercontent.com/281413/37603856-daa6567e-2b8f-11e8-9d06-540b9752a206.png)

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.4203.6, built on March 13, 2018
IntelliJ IDEA EAP User
Expiration date: April 12, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

**Comment by vjpr** [comment]
It has started working again after I restarted.

**Comment by ArtemGovorov** [comment]
Must have been some transient (possibly network) issue (wallaby works when fully offline though).

**Comment by vjpr** [comment]
Just encountered again first time running after an update.
