### ISSUE TITLE
VSCode: new WallabyJs.wallaby-vscode-1.0.78 update breaks scss 

### ISSUE THREAD

**Issue by garrettmac** [wallabyjs/public#1568]
### Issue description or question
Before vscode auto updated the wallaby vscode extension about a week ago wallaby would run as expected.
after it updated, it introduced an issue where Wallaby has an issue processes `scss` imports.

I have not made any changes in any seemingly related files like `jest.config.js`, `package.json`,`webpack.config.js`, `yarn.lock`, `wallaby.js`, node/npm version.  

Only thing that changes was the wallaby extension version.

From wallaby console. 
```jsx
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.568
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] Runtime error: Error: Cannot find module './item.scss' from 'item.js'​​
```
like this but for every file.

### Wallaby.js configuration file

```javascript
// https://wallabyjs.com/
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.js',
      { pattern: 'src/**/*.json', instrument: false },
      { pattern: 'config.json', instrument: false },
      '!src/**/*.test.js',
      'jest.config.js',
      '!src/**/__tests__/*.js',
      '!src/__mocks/**/*.js'
    ],
    tests: ['src/**/*.test.js', 'test/**/*.js', 'src/**/__tests__/*.js'],
    env: {
      type: 'node',
      runner: 'node',
      kind: 'chrome'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    setup: function(wallaby) {
      const jestConfig = require('./jest.config.js');
      wallaby.testFramework.configure(jestConfig);
    },
    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version /  OS name and version

**Node**: v6.10.0
**NPM**: 3.10.10
**Visual Studio Code**:  v1.21.1 (1.21.1)
**OSX macbook pro, 2017**, High sierra 10.13.3

How can I fix or revert to an earlier extension version in vscode?

**Comment by garrettmac** [comment]
looks like it's some issue related to polyfills. Wallaby doesnt like this line im by setup.
```
global.requestAnimationFrame = callback => setTimeout(callback, 0);
// says 0 is undefined.

// same thing if I have this in my jest.config.js
  setupFiles: [
    'raf/polyfill', // https://stackoverflow.com/a/46656658/4642530
```

**Comment by ArtemGovorov** [comment]
Try adding `src/**/*.scss` pattern to your `files` list, and if you have a `moduleNameMapper` for `scss` files that resides in your project (not a node modules), then make sure the mapper file is in the `files` list as well.

Let me know if this helps.
