### ISSUE TITLE
Getting "SyntaxError: Expected an identifier but found '{' instead" for valid syntax

### ISSUE THREAD

**Issue by moltar** [wallabyjs/public#1569]
### Issue description or question

An error is produced:

> SyntaxError: Expected an identifier but found '{' instead

The offending code snippet:

```js
const {
  test, trait, beforeEach, afterEach
} = use('Test/Suite')('providers/Entity/User')
```

### Wallaby.js configuration file

```javascript
module.exports = function wallaby () {
  return {
    files: [
      'app/**/*.js',
      'config/*.js',
      'providers/**/*.js',
      'start/**/*.js',
      'start/**/*.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ]
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.21.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
With your config wallaby runs tests in browser (PhantomJs by default, that doesn't support destructuring assignment). You are probably missing a setting to [tell wallaby to run your tests in node](https://wallabyjs.com/docs/integration/node.html).

```javascript
module.exports = function () {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    env: {
      type: 'node'
    }
  };
};
```
