### ISSUE TITLE
Error using proxyquire when running with wallaby.js on Node

### ISSUE THREAD

**Issue by alexmbrown** [wallabyjs/public#1570]
### Issue description or question

I'm receiving the following error when I attempt to require another file using proxyquire `TypeError: Cannot read property 'split' of undefined` from the line invoking the proxyquire method when running my tests. I do not receive this error when I use the jasmine test runner. Here is an example of when the error occurs

example.js:
```
const foo = require('../foo')

module.exports = function getFoo() {
  return 'hello ' + foo();
}
```

example.spec.js:
```
const proxyquire = require('proxyquire')

describe('Example', () => {
  let fooBar
  let foo

  beforeEach(() => {
    foo = {
      bar: 'mock bar'
    }

    fooBar = proxyquire('./example.js', {
      '../foo': () => 'world'
    })
  })
    
  it('should log "hello world"', () => {
    console.log(fooBar.getFoo())
  })
})
```

### Wallaby.js configuration file

```javascript
'use strict'

module.exports = function () {
  return {
    files: [
      'src/**/*.js',
      {pattern: 'src/**/*spec.js', ignore: true}
    ],
    tests: [
      'src/**/*spec.js'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jasmine'
  }
}

```

### Code editor or IDE name and version

WebStorm v2017.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Note that your test needs to be modified to pass (with or without wallaby), because a function is exported from the `example.js` module:

```diff
  it('should log "hello world"', () => {
-   console.log(fooBar.getFoo())
+   console.log(fooBar())
  })
```
