### ISSUE TITLE
[Wallaby app] Keep files three state the same between test runs 

### ISSUE THREAD

**Issue by ralzinov** [wallabyjs/public#1575]
### Issue description or question
I have a little usability suggestion for wallaby app. It always make folders in files three expanded, and it is not very comfortable to scroll to file i need to watch its coverage.

Current behavior:
1. collapse some folders in file three
2. make change in any file
3. All folders become expanded again

Expected behavior:
 1. Collapse some folders in file three
2. Make change in file
3. All folders are keeping their state

Also maybe it will be useful to have "collapse all" / "expand all" button

**Comment by ArtemGovorov** [comment]
> Also maybe it will be useful to have "collapse all" / "expand all" button

You can do it [via a keyboard shortcut](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#tests) - you may navigate the trees with the keyboard using arrow keys, plus `Cmd/Ctrl + arrow` to expand a node, or `Cmd/Ctrl +Shift + arrow` the whole tree.

**Comment by ralzinov** [comment]
Thank you, i did't notice it

**Comment by ralzinov** [comment]
It seems to this feature was implemented recently, because folders now keeping their state on file changes. That's cool, thank you very much!
Unfortunately folders still doesn't keep collapsed/expanded state when i'm adding a new file (seems to that whole tree just reloaded in that case), could you please also make such behavior when adding new file?

**Comment by NikGovorov** [comment]
Hi @ralzinov,

Thanks for the suggestion, tree state persistence is released with v1.0.49.
