### ISSUE TITLE
Offline installation: Cannot find module '../wallaby/client'

### ISSUE THREAD

**Issue by justin73** [wallabyjs/public#1578]
Hi. 

I am trying to do a demo to my team for promoting them to use Wallaby. I've used it in my previous project and it worked really well. But now my company does have this proxy issue, so I've tried the offline installation based on your instruction https://wallabyjs.com/docs/intro/troubleshooting.html

Extention version : 1.0.78 
![2018-03-23 14_50_01-extension_ wallaby js - vue-demo - visual studio code administrator](https://user-images.githubusercontent.com/3356603/37848177-8b14060c-2ea9-11e8-96b4-60fc52626d5e.png)

Here are some screenshots of my current file structure
 
![2018-03-23 14_40_02-extensions](https://user-images.githubusercontent.com/3356603/37848198-a998e25a-2ea9-11e8-8131-69cef9ea7064.png)
![2018-03-23 14_40_16-wallabyjs wallaby-vscode-1 0 78](https://user-images.githubusercontent.com/3356603/37848199-a9a4a996-2ea9-11e8-8582-0e12d76af7b4.png)
![2018-03-23 14_40_26-wallaby](https://user-images.githubusercontent.com/3356603/37848200-a9af7448-2ea9-11e8-999d-f3f821bbe9ac.png)

And the phantom js files
![2018_03_23_14_52_42_phantomjs_v2 1 1](https://user-images.githubusercontent.com/3356603/37848283-fbe96bf6-2ea9-11e8-9be8-982ba351e974.jpg)

Here is the error I have 
![2018-03-23 14_35_44-rootstore spec js - vue-demo - visual studio code administrator](https://user-images.githubusercontent.com/3356603/37848306-0ff9fcf0-2eaa-11e8-81a3-29900c009f37.png)

### Wallaby.js configuration file

```const webpackConfig = require('./build/webpack.test.conf.js')
const wallabyWebpack = require('wallaby-webpack')

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.*',
      '!src/**/*.test.js'
    ],

    tests: [
      'test/**/*.spec.js',
      'src/**/*.test.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

    testFramework: 'jest',

    setup: function (wallaby) {
      const jestConfig = require('./package.json').jest
      jestConfig.moduleNameMapper = {
        '^@/(.*)$': wallaby.projectCacheDir + '/src/$1'
      }
      wallaby.testFramework.configure(jestConfig)
    },

    debug: true
  }
}

```

### Code editor or IDE name and version
Visual Studio Code v1.21.1

### OS name and version
Windows 10

Thanks a lot!

**Comment by ArtemGovorov** [comment]
From this screenshot:
![2018-03-23 14_40_26-wallaby](https://user-images.githubusercontent.com/3356603/37848200-a9af7448-2ea9-11e8-999d-f3f821bbe9ac.png)
looks like a few files are missing. Please make sure you download the latest core version from our website [as described here](https://wallabyjs.com/docs/intro/troubleshooting.html#vs-code) and after unzipping, make sure you copy all files (there should be `client.js` file in there).

Also, make sure that `phantomjs.exe` file is located right in the `.vscode/phantomjs_v2.2.1` folder (copy it from the `bin` subfolder if required).
