### ISSUE TITLE
Typo https://wallabyjs.com/docs/intro/troubleshooting.html

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1580]
> Tests are running too slow or consume too much RAM

> Make sure that you have set instrument: false flag to all files that you don’t need the code coverage to be collected for, such as your project libraries. **No only this will make wallaby.js to consume** much less memory, it may also increase your test runs speed.

*"Not only will this make wallaby.js consume"

**Comment by ArtemGovorov** [comment]
Thanks, fixed!
