### ISSUE TITLE
Slow performance on relatively fast laptop

### ISSUE THREAD

**Issue by rpfister51** [wallabyjs/public#1584]
### Issue description or question

Even with a very simple repository it takes 50 to 60 seconds to see a change when the value expected changes.  I've seen instantaneous updates on other people's systems before, so wonder if there's something simple I'm doing that is causing the problem.

My laptop is Intel i7-4800MQ (4 core/8 threads/2.7 GHz), 32 GB memory, so I don't think it's a hardware problem.

See repository https://github.com/rpfister51/slowwallaby

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
      files: [
        'src/**/*.js'
      ],
  
      tests: [
        'tests/**/*Spec.js'
      ],

      env: {
          type: 'node',
          runner: 'node'
      },

      workers: {
        initial: 6,
        regular: 2,
        restart: true
      },

      testFramework: 'jest',
      debug: true
    };
  };
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

Windows 10 Enterprise, version 1703, OS Build 15063.909

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

The issue is likely that because of the `workers: {restart: true}` setting, wallaby is restarting node process on every change (and Jest is not cheap to start up, though 50-60 seconds is still strange as it only takes 3-4 on my machine with similar specs).

Removing the setting should help:

```javascript
module.exports = function (wallaby) {
    return {
      files: [
        'src/**/*.js'
      ],
  
      tests: [
        'tests/**/*Spec.js'
      ],

      env: {
          type: 'node',
          runner: 'node'
      },

      testFramework: 'jest',
      debug: true
    };
  };
```

**Comment by rpfister51** [comment]
Hi Artem,

Removing restart: true brings refresh of the IDE down to about 2 seconds.  I had an idea about the 50 seconds I was seeing; my employer is on a security kick here and is using a tool called Avecta.  I wonder if Avecta is doing something that is slowing down node restarts.  Do you have any experience with Avecta?

Thanks for your prompt response to my question, and your accurate resolution.

Bob

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> I wonder if Avecta is doing something that is slowing down node restarts. Do you have any experience with Avecta?

It is possible, but unfortunately we don't have any experience with the tool.
