### ISSUE TITLE
Feature Request: Run Only File/Line Tests

### ISSUE THREAD

**Issue by KingHenne** [wallabyjs/public#1586]
Sometimes I want to see the coverage/logs only in regards to the current test I'm working on and not all other tests. To accomplish that it would be convenient to have two additional commands:
- Run Only File Tests
- Run Only Line Tests

Note: Maybe this is only relevant to test frameworks that don't support `.only` across files, e.g. jest.

**Comment by KingHenne** [comment]
Duplicate of #1156, I guess.

**Comment by ArtemGovorov** [comment]
I have some good news for you, we are implementing the feature right now, and `.only` will be supported across multiple files as you'd expect it to. We are planning to release it soon, hopefully next week. Please subscribe to #1156 to get an update when it is ready.

**Comment by KingHenne** [comment]
That is awesome, looking forward to the release!
