### ISSUE TITLE
Can't get WallabyJs running with Ava

### ISSUE THREAD

**Issue by florianb** [wallabyjs/public#1587]
### Issue description or question

I tried several steps to make Wallaby run with Ava in my current project. Unfortunately it still keeps failing with the following complaint:

```
Unexpected token import
    at test/repo.js:1
```

It seems like the Babel-transpilation fails at one point. I have read through #1542 (Support Ava 1.0) and since it seems that the issue there was fixed by the answer being provided there i wonder if that issue applies to me, too?

And since i am pretty new to WallabyJs i hope i didn't mess the configuration up.

Might this be an issue related to the upcoming Major Babel (and pending Major Ava) release and should i just wait until stuff gets fixed or do i need to fix something?

Thank you very much in advance! 🍪

P.s.: The Ava-runner itself runs without any issues.

### Wallaby Versions

Atom plugin v1.0.39
Core v1.0.571

### Dependencies

    @babel/core: ^7.0.0-beta.42
    ava: ^1.0.0-beta.3

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
	return {
		files: [
			'src/**/*.js'
		],
		tests: [
			'test/**/*.js'
		],
		env: {
			type: 'node',
			runner: 'node'
		},
		compilers: {
			'**/*.js': wallaby.compilers.babel()
		},
		testFramework: 'ava',
		debug: false
	}
}
```

### Code editor or IDE name and version

Atom v1.24.1

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment]
Your wallaby config looks ok to me, so we'll need some more information to troubleshoot the issue. Could you please create a sample repo where the issue could be reproduced? We're happy to look into it and help.

**Comment by florianb** [comment]
Thank you very much for your fast response @ArtemGovorov,

i prepared the following repository: https://github.com/florianb/wlby-issue

Let me know if i can do anything else.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.
Your repo is missing any babel config, like `.babelrc`, so wallaby doesn't compile your ES imports. Ava is automagically using the required preset (however you may still need a valid babel config for your production build). You just need to let [wallaby babel compiler](https://wallabyjs.com/docs/integration/es-next.html) know about the preset.

I have sent you the PR with the working config - https://github.com/florianb/wlby-issue/pull/1.

**Comment by florianb** [comment]
@ArtemGovorov - thank you very much! I really appreciate you also fixed it in the PR! ❤️ 

Would you mind if i file a PR to this ava-example or to the docs?

**Comment by ArtemGovorov** [comment]
@florianb Thanks, the PR is appreciated!
