### ISSUE TITLE
license not compatiable with downloaded plugin

### ISSUE THREAD

**Issue by cyberhck** [wallabyjs/public#1588]
### Issue description or question
I've got a license, when I try to activate it, it says the current version isn't compatible, I can't find past releases anywhere.
### Code editor or IDE name and version

PhpStorm EAP

### OS name and version
OSX/Linux

**Comment by ArtemGovorov** [comment]
The activation popup should have a link to this page https://wallabyjs.com/license/, where you can download the past compatible release.
