### ISSUE TITLE
Wallaby fails after removing restart:true

### ISSUE THREAD

**Issue by rpfister51** [wallabyjs/public#1589]
### Issue description or question
After removing restart:true (and entire "workers" item) from wallaby.js (this resolved my problem as described in issue 1584) wallaby failed after switching to a different project.  After returning to the initial project ("slowwallaby", link in 1584) wallaby still failed.  By failed I mean the wallaby command palette could not be reached by Ctl + Shift + = (message was something like command palette not available, sorry, I didn't get screen prints) and the Wallaby commands showing in the main command palette with similar messages: something like "Wallaby command start not available" for instance.

I found issue 969 which suggested uninstalling wallaby extension, uninstalling VS Code, then re-installing.  I did this and Wallaby is now working again.

I'm writing this just so you're aware of the problem.

My configuration details are in issue 1584.

**Comment by ArtemGovorov** [comment]
It sounds like your wallaby installation was corrupted for some reason. Re-installing the extension helps in this case. Unfortunately we can't reproduce the issue locally, and have a suspicion that the issue may be not with wallaby extension, but with extension host in VS Code.
