### ISSUE TITLE
Wallaby cannot find jest mapped module relative to <rootDir> in monorepo

### ISSUE THREAD

**Issue by suchipi** [wallabyjs/public#1590]
### Issue description or question
I am using wallaby with the jest framework in a monorepo.
My wallaby config file and jest config (in my package.json) both reside in a path deeper than my editor's project root:

```
packages/
  my-package/
    wallaby.conf.js
    package.json (contains jest config)
```

I use `<rootDir>` in my Jest config to refer to `packages/my-package`, and I have my jest `moduleNameMapper`s referring to content in `<rootDir>/..`.

Jest resolves those properly, but wallaby does not. I suspect (but have not confirmed) that wallaby is using the project root as `<rootDir>` instead of the location of `packages/my-package`.

Here is the error I get from wallaby:
```
Configuration error:

Could not locate module react (mapped as ./../react-compat/index.js)

Please check:

"moduleNameMapper": {
  "/^react$/": "./../react-compat/index.js"
},
"resolver": undefined
```

I have also tried opening `my-package` directly in atom as the project root, but I get the same error.

### Wallaby.js configuration file

```javascript
const path = require("path");

module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js?(x)",
      "!src/**/*.test.js?(x)",
      "!src/**/*.stories.js?(x)",
    ],

    tests: [
      "src/**/*.test.js?(x)",
    ],

    env: {
      type: "node",
      runner: "node",
      params: {
        env: `NODE_PATH=${path.resolve(__dirname, "..", "..", "node_modules")}`,
      },
    },

    testFramework: "jest",

    compilers: {
      "src/**/*.js?(x)": wallaby.compilers.babel(),
    },
  };
};
```

### Jest config (in `package.json`)
```
"jest": {
    "setupTestFrameworkScriptFile": "<rootDir>/src/testHelpers/setup.js",
    "testPathIgnorePatterns": [
      "<rootDir>/node_modules/",
      "<rootDir>/build/"
    ],
    "moduleNameMapper": {
      "^react$": "<rootDir>/../react-compat/index.js",
      "^react/lib/(.*)$": "<rootDir>/../../node_modules/react-15/lib/$1"
    }
  }
```

### Code editor or IDE name and version

Atom v1.24.0
atom-wallaby 1.0.22

### OS name and version

macOS Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
Wallaby maps `<rootDir>` to its local cache (with instrumented files), unless the path is pointing to `node_modules`. However, files/folders that are above wallaby config file level are not copied to the wallaby cache, hence the issue. 

Try the config below, it should help:

```diff
const path = require("path");

module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js?(x)",
      "!src/**/*.test.js?(x)",
      "!src/**/*.stories.js?(x)",
    ],

    tests: [
      "src/**/*.test.js?(x)",
    ],

    env: {
      type: "node",
      runner: "node",
      params: {
        env: `NODE_PATH=${path.resolve(__dirname, "..", "..", "node_modules")}`,
      },
    },

    testFramework: "jest",

    compilers: {
      "src/**/*.js?(x)": wallaby.compilers.babel(),
    },
+   setup: function(wallaby) {
+     const config = require('./package.json').jest;
+     Object.keys(config.moduleNameMapper).forEach(k => (config.moduleNameMapper[k] = config.moduleNameMapper[k].replace('<rootDir>', wallaby.localProjectDir)))
+     wallaby.testFramework.configure(config);
+   }
  };
};
```

**Comment by suchipi** [comment]
This works, thank you!

**Comment by csi-lk** [comment]
Not to re-open but I just wanted to point out I had the same issue, may be related to a wallaby update?

(was working fine previously)

Cheers

**Comment by ArtemGovorov** [comment]
@csi-lk Yep, the issue is related to a recent update (that was few weeks ago). We'll investigate the ways to fix if (to work without the suggested `<rootDir>`) for this scenario (wallaby config residing deeper than project's root).
