### ISSUE TITLE
Wallaby can't find any command

### ISSUE THREAD

**Issue by beebase** [wallabyjs/public#1591]
### Issue description or question
All commands are failing in vscode
error:  command '....' not found

Didn't change any config file whatsoever.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: ['lib/**/*.js'],

    tests: ['test/**/*Spec.js'],

    env: {
      type: 'node'
    },

    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX  High Sierra 10.13.3 (17D102)

**Comment by ArtemGovorov** [comment]
Looks like your wallaby extension installation is corrupted.

Please share the output from the Dev Tools console (Help - Toggle Developer Tools) and re-install the extension in VS Code, it should help.

**Comment by beebase** [comment]
Got it working again with following steps.
1. uninstall wallaby ext.
2. restart vscode
3. install wallaby ext.

thanks.
