### ISSUE TITLE
0 failing tests, 0 passing​​​​​ - with jest, flow & Babel

### ISSUE THREAD

**Issue by MarkLyck** [wallabyjs/public#1592]
### When starting wallaby it doesn't run any tests with the trial license (first time trying it)

getting the output: `0 failing tests, 0 passing​​​​​`

### Wallaby.js configuration file

```javascript
{
      files: [
        'src/**/*.js?(x)',
      ],
  
      tests: [
        'src/test/**/*test.js?(x)'
      ],

      compilers: {
        'src/**/*.js?(x)': wallaby.compilers.babel()
      },

      env: {
        type: 'node',
        runner: 'node'
      },

      testFramework: 'jest',
      reportConsoleErrorAsError: true,
      debug: true,
    }
```

### jest config:
```
{
    verbose: true,
    setupFiles: ['./src/test/common/jest/jest.setup.js'],
    snapshotSerializers: ['enzyme-to-json/serializer'],
    moduleFileExtensions: ['js', 'jsx', 'json'],
    transform: {
        '^.+\\.jsx?$': 'babel-jest',
        '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
        '<rootDir>/src/test/common/jest/assetsTransformer.js',
    },
    moduleNameMapper: {
        '\\.(css|less|scss)$': 'identity-obj-proxy',
    },
    modulePathIgnorePatterns: [
        '<rootDir>/.yarn',
        '<rootDir>/.npm',
    ],
};
```

jest unit tests are in `src/test/unit/**/*.test.js`

### versions
Visual Studio Code: 1.21.1
MacOS Siera: 10.12.6
Wallaby-vscode: 1.0.79
Jest: 22.4.2

**Comment by ArtemGovorov** [comment]
It looks like your [`files` and `tests` patterns](https://wallabyjs.com/docs/config/files.html) intersect. Please check [Wallaby Console output](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting), it should tell what's wrong and how to fix it.

**Comment by MarkLyck** [comment]
changed it to:

```
files: [
        'src/main/**/*.js?(x)',
      ],
  
      tests: [
        'src/test/unit/**/*test.js?(x)'
      ],
```

which does show a bit more information now, I'm still getting 0 failed and 0 passed but with an error now:

```
​​[31m[1m[1m● [1mValidation Error[22m:[39m​​
​​[31m[39m​​
​​[31m  Module [1m./src/test/common/jest/assetsTransformer.js[22m in the [1mtransform[22m option was not found.[39m​​
​​[31m[39m​​
​​[31m  [1mConfiguration Documentation:[22m[39m​​
​​[31m  https://facebook.github.io/jest/docs/configuration.html[39m​​
​​[31m[39m​​
```

It doesn't seem to be able to parse the assetTransformer I use with Jest?

**Comment by ArtemGovorov** [comment]
All of your files used in your tests/source need to be included in the [`files` patterns](https://wallabyjs.com/docs/config/files.html). The error mentions
```
./src/test/common/jest/assetsTransformer.js
```

so

```diff
      files: [
        'src/main/**/*.js?(x)',
+       'src/test/common/**'
      ],
```

should help.

**Comment by MarkLyck** [comment]
That worked, thank you so much!
