### ISSUE TITLE
Won't run typescript tests on Windows

### ISSUE THREAD

**Issue by JRobber** [wallabyjs/public#1594]
### Issue description or question
I can't get typescript tests to run on my Windows computer.

Using this same basic repo on my mac works fine.  Wallaby mac version 1.0.561.  Windows version : 1.0.568.

Full repo here : https://gitlab.com/JRobber/simple-ts-tests

It appears to just turn on and run, and then never runs any tests.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
      files: [
        'logic/**/*.ts',
      ],
  
      tests: [
        'spec/**/*.spec.ts'
      ],
  
      debug: true
    };
  };
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

Windows 10 Home

No errors in the debug stream
[log.log](https://github.com/wallabyjs/public/files/1863473/log.log)

**Comment by ArtemGovorov** [comment]
I suspect the issue is with PhantomJs (currently used by default, but will soon be deprecated) on latest versions of Windows.

Please [use Chrome runner](https://wallabyjs.com/docs/integration/chrome.html) instead:

```js
module.exports = function (wallaby) {
    return {
      files: [
        'logic/**/*.ts',
      ],
  
      tests: [
        'spec/**/*.spec.ts'
      ],

      env: { kind: 'chrome' },
  
      debug: true
    };
  };
```
