### ISSUE TITLE
Configuration for Electron, Typescript, ESNEXT, Vue

### ISSUE THREAD

**Issue by JRobber** [wallabyjs/public#1595]
### Issue description or question
Sample repo here : https://gitlab.com/JRobber/sqlphile-gen

**1) Nothing ES6 works**
It works right now, but I have commented out almost all of `src/logic/logic.ts`

using `let` throws an `expected identifier` error.

using export kills the test run and throws a `Missing tracer start subscription error` (Super confusing as this overrides all other errors and the error message is not obvious).

No, arrow functions, backticks, or classes work either.

I've spent about 5 hours trying lots of different things and eventually broke it down to the basics because I've just been copying basics from other solutions you've given on the internet in.

**2) Nothing Electron/Vue works**

Right now the wallaby config is set up to only look at my basic javascript tests.  If I change it to include the unit test folder it breaks when trying to test a component.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
      files: [
        'src/logic/**/*.ts',
      ],
  
      tests: [
        'test/unit/**/*.spec.ts'
      ],
      // env: {
      //   kind: 'electron'
      // },

      debug: true
    };
  };
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX 10.12.6
AND on Windows 10 Home 
But mac is more important to me right now.

**Comment by ArtemGovorov** [comment]
It looks like you are using webpack and babel, but none of those is configured in your wallaby config. What happens with the config like yours, is that your scripts and tests are just included into the generated sandbox test page as is, so all the described failure are expected.

The first thing you need to do is to configure wallaby to use [babel](https://wallabyjs.com/docs/integration/es-next.html) and [webpack](https://wallabyjs.com/docs/integration/webpack.html), as they are used in your project (and by your karma config). Try that and let us know how it goes.

**Comment by JRobber** [comment]
Thanks for the direction.  I pivoted a little bit and made a smaller project that only has TS files so I could focus on getting that to work:  https://gitlab.com/JRobber/simple-ts-tests

I can't.  TS works out of the box, but then ES6 things don't.  If I add babel then the ES6 stuff works but TS doesn't.  This is way harder than it should be to get TS + arrow functions.

Please take this the right way, but I have a love/hate relationship with wallaby.  It's an amazing tool, really fantastic, but I do a lot of smaller projects and I'm always losing hours getting wallaby set up.  It's incredibly frustrating.  And I don't feel like I get better at it as I do it because most of my projects are pretty different.

You really should consider making a CLI tool to help generate config files or auto-detect webpack setups and the like.  A LOT of devs are using boilerplates and cli's to generate their projects and don't know the ins and outs of how some are set up.  I usually don't take the time because I need to get other things done.

The only reason I've pushed through on this one is because I renewed my license last night, went to set up wallaby, and I'm now at 6 hours and can't run a single test against a simple TS file that also uses some ES6.  It's silly really, and it's probably my fault, but it still feels like Wallaby is a few steps behind the rest of the JS build industry in terms of 'quick setup and help' that it provides.

**Comment by ArtemGovorov** [comment]
As I have mentioned in your previous issue, wallaby is using PhantomJs by default (but things will change soon). PhantomJs doesn't support ES6, so you need to transpile it, or use something that supports ES6.

If you use [Chrome](https://wallabyjs.com/docs/integration/chrome.html) or Electron (as the issue's title says, but your current config doesn't have it configured for some reason), then your sample just works:

```js
let path = require("path"),
  wallabyWebpack = require("wallaby-webpack");

module.exports = function(wallaby) {
  return {
    files: ["logic/**/*.ts"],

    tests: ["spec/**/*.spec.ts"],

    env: {
      kind: 'chrome'
    },

    debug: true
  };
};
```

Note that you don't need to use babel at all in this case with your current configs (your TS config compiles to ESNext supported by Chrome). If you still want to use babel with TypeScript, then you can use the configuration [described in the relevant docs section](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel).

Hope it helps.

**Comment by ArtemGovorov** [comment]
Once you start adding/using modules, you'll need to configure webpack for wallaby as I have mentioned here - https://github.com/wallabyjs/public/issues/1595#issuecomment-377655235. It actually is much simper than configuring webpack itself (without wallaby), but if you get stuck, please let me know and share an update repo demonstrating the issue, I'm happy to help with the config.

**Comment by JRobber** [comment]
I appreciate your patience and apologize for the rant earlier.  Using Wallaby is a dream.  Setting it up is a nightmare for me, and part of that is all of the little things like phantom not supporting ES6.

**Comment by ArtemGovorov** [comment]
Thanks for your feedback. We will be deprecating PhantomJs default soon.
