### ISSUE TITLE
Wallaby not working with jasmine callFake

### ISSUE THREAD

**Issue by joilson-cisne** [wallabyjs/public#1597]
### Issue description or question
Wallaby seems not to be working with jasmine `callFake`. The argument of the "fake" function is always `undefined`.

The test below passes when I run with jasmine directly, but it breaks when running with wallaby. Does anyone had this problem before?

```js
it('test callFake and wallaby', async () => {
      // Arrange
      const myObj = {
        myFunc: (a) => a + 1,
      };

      spyOn(myObj, 'myFunc')
        .and.callFake(arg => arg);
      
      // Act
      const result = myObj.myFunc(1);

      // Assert
      expect(result).toBe(1);
    });
```

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      'src/**/*.js',
      'migrations/*',
      'test/_helpers/*',
      'seeds/*',
      'config/*',
      { pattern: '.env', instrument: false },
    ],

    tests: [
      'test/**/*.spec.js',
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'jasmine',

    env: {
      type: 'node',

      params: {
        env: 'NODE_ENV=test;MONGODB_CONQUERY=mongodb://localhost:27017/athena-test',
      },
    },
    workers: {
      initial: 1,
      regular: 1,
      restart: true,
    },

    setup: (/* wallaby */) => {
      require('dotenv').load({ path: '.env' }); // eslint-disable-line
      require('./test/_helpers/dropDatabase'); // eslint-disable-line
    },

    teardown: (/* wallaby */) => {
    },
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX 10.13.3

**Comment by joilson-cisne** [comment]
https://stackoverflow.com/questions/49595096/wallaby-js-not-working-with-jasmine-callfake

**Comment by ArtemGovorov** [comment]
Thanks for the report. Apparently you are using Jasmine 2.9, because your code is working as expected in Jasmine 3.x. The bug in Jasmine 2.x support was introduced recently when adding Jasmine 3 support in wallaby. 

The regression is fixed and the fix had juts been published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) (or update your Jasmine version to 3.x).

**Comment by joilson-cisne** [comment]
Thanks for the quick response. @ArtemGovorov
