### ISSUE TITLE
Failed to initialize wallaby jest. Error: Cannot find Jest test runner

### ISSUE THREAD

**Issue by 09wattry** [wallabyjs/public#1598]
### Issue description or question
When running Wallaby.js with Jest testing framework I receive this error:

Failed to initialize wallaby jest.
Error: Cannot find Jest test runner
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

I had Jest and Wallaby working prior to a Windows and Wallaby core update. 

### Wallaby.js configuration file

```javascript
module.exports = function() {

  return {
    files: ['app/*.js', 'app/src/**/*.js', {
      pattern: '.env',
      instrument: false
    }],
    tests: ['test/*.js'],
    env: {
      type: 'node',
      runner: 'node'
    },
     testFramework: 'jest',
    debug: true
  };
};
```

### Code editor or IDE name and version
Atom v1.25

### OS name and version

Windows 10 build 1709
64 bit

**Comment by ArtemGovorov** [comment]
From the error message it looks like wallaby can't find Jest in your project's `node_modules`. Try re-installing the modules by deleting them and running `npm i` (or `yarn` if you're using it).

If it doesn't help, please 
- search for the `jest-cli` node module in your `node_modules` (it should either be under the `node_modules/jest-cli` or under `node_modules/jest/node_modules/jest-cli`).
- share your package.json and `package-lock.json`/`yarn.lock`.

**Comment by unional** [comment]
I also use jest, you can consider taking a look at my config. e.g: https://github.com/unional/komondor-plugin

The project is written in typescript, meaning it is probably even easier for you.

**Comment by 09wattry** [comment]
@ArtemGovorov I rearranged my project recently. I didn't realise that the node_modules folder needs to be in the root directory of the project for Wallaby to work. I moved it back to the project root and it started working.

**Comment by ArtemGovorov** [comment]
@09wattry Awesome, thanks for the update!

@unional Thanks!

**Comment by Ghirigoro** [comment]
I have the same issue and node_modules is in the project root. What caused my issue was moving my wallaby config files out of the root and into a config folder inside of root. Is it a requirement that the config files be in the root?

**Comment by ArtemGovorov** [comment]
> Is it a requirement that the config files be in the root?

Yes, it is.

**Comment by artemshapovalov** [comment]
I have the same problem using `yarn` `workspaces` I don't have `jest-cli` in the project `node_modules` there is only .bin/jest but I have it in the root `node_modules` 

@ArtemGovorov how can I solve it?

**Comment by ArtemGovorov** [comment]
@artemshapovalov Can you please create a separate issue and attach Wallaby diagnostics report (described in the new issue template)?

**Comment by artemshapovalov** [comment]
@ArtemGovorov here it is https://github.com/wallabyjs/public/issues/2731
