### ISSUE TITLE
Registering settings.json Defaults in VSCode

### ISSUE THREAD

**Issue by kjrocker** [wallabyjs/public#1603]
### Issue description or question

WallabyJS does not register any of its default configuration options in the default `settings.json` file. This makes it difficult to grep for the config options that are available outside of `wallaby.conf.js`.

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report, registered all available options in the latest published v1.0.80.
