### ISSUE TITLE
Karma tests that references file directly fails when run with wallaby

### ISSUE THREAD

**Issue by git-jiby-me** [wallabyjs/public#1607]
### Issue description or question

I have a karma - jasmine test, that involves workers. The code loads worker off a url, and to test with karma, the url is mocked to be `/base/${file}`, and karma delivers this file and test works.

However when test is run with wallaby the url `/base/${file}` returns 404, how can i configure wallaby so that a test file can be accessed at url `/base/${file}` ?

**Comment by git-jiby-me** [comment]
Okay, just found out that karma serves file on `/base` while as wallaby on `/`, is there any way to configure this ?

**Comment by ArtemGovorov** [comment]
You may use [express middleware to configure any routes](https://wallabyjs.com/docs/config/middleware.html) and make wallaby return either your original project files (you may use `__dirname` for that), or if you like to return instrumented files (to display code coverage for the served file), you may use [`wallaby. projectCacheDir`](https://wallabyjs.com/docs/config/overview.html) as a physical folder to map the route to.
