### ISSUE TITLE
Use TypeScript reference comments to order source files and load them in the correct order

### ISSUE THREAD

**Issue by defaude** [wallabyjs/public#161]
Wallaby.js compiles TypeScript just fine but does not add (the full) compiled code during spec execution.

See https://github.com/defaude/wallaby-typescript-modules for an example.

**Comment by ArtemGovorov** [comment]
Thanks for the sample repo. 

The issue in this case is that the file `Bar` is loaded to the sandbox before the file `Foo`, because in the config file source files are specified as a pattern and by default wallaby.js loads them in alphabetical order. The issue is not TypeScript specific, if you just use Bar.js and Foo.js, you'll get the same result.

In order to fix it, all you have to do is to specify your files in the correct order:

``` JavaScript
module.exports = function () {
    return {
        files: ['src/Foo.ts', 'src/Bar.ts'],
        tests: ['test/**/*.coffee']
    };
};
```

**Comment by defaude** [comment]
Hmmm. I see. Still, I think Wallaby could / should behave like:
1. Read the "files" patterns and look at the file system for all files that match
2. Inspect those files for language-specific features (e.g. TypeScript's reference comments, require-calls, etc.)
3. Construct a kind of dependency tree for all files
4. Insert the files into the sandbox in the order defined by the tree

For this simple sample thingy, it's no big deal to specify the files manually. But what do you do when you have a dozen .ts files in multiple directories? Or a hundred? :)

**Comment by ArtemGovorov** [comment]
For technologies that support some sort of enforced module dependency mechanism, wallaby.js supports it as well. For example for node.js apps and browsers apps using CommonJs with webpack/browserify, wallaby doesn't require to list files, you may just use patterns. So for require-calls it already does work. 

Regarding specifying files manually, if there's no other way to determine it, then the files order has to be specified somewhere, and yes, it can get quite long, have a look into a [part of karma config for angular.js](https://github.com/angular/angular.js/blob/master/angularFiles.js). It's the only way to do things in vanilla JS without some sort of enforced module dependency mechanism, such as CommonJs.

TypeScript reference comments case is a bit tricky. While something can be implemented in wallaby to try sorting your files, it's never going to be 100% reliable, as for example enforced CommonJs. First, reference comments are optional. Second, you may have a mixture of TS and other files, like JS or CS. For example, in your case, given your CS test file, there's no way to tell that it depends on Foo and Bar. So if it wasn't a test, but a source file, it'd be an issue.

I've renamed the issue and tagged it as an enhancement, will try to implement something fully utilize reference comments and implement automatic sorting for TS files.

**Comment by defaude** [comment]
You are my personal hero, Sir :+1:

**Comment by Burgov** [comment]
+1

**Comment by ArtemGovorov** [comment]
@Burgov Could you please share your karma config and wallaby config?

**Comment by Burgov** [comment]
@ArtemGovorov when I said karma runs fine that was actually a bit misleading: we're not using the karma typescript preprocessor. We're compiling the TS code and then running karma on that. The reason is (was?) that the karma typescript preprocessor is really crap...

If you still need anything, let me know, i'm happy to provide it to you.

**Comment by ArtemGovorov** [comment]
@Burgov Got it, thanks. So in your karma config you still have to list all compiled js file in the correct order to make it work, right?

**Comment by Burgov** [comment]
@ArtemGovorov yes. We have a gulp file which compiles all ts files into a `.tmp_test` folder. The output of the compile action then goes into a gulp task that injects all that into the karma config file.

```

gulp.task('create-karma-config', function() {
    var testFiles = merge2(
        src,
        helpers,
        tests
    ).pipe($.if('**/*.ts', typescriptChannel()));

    testFiles = testFiles.pipe(gulp.dest('.tmp_test'));

    var pipe = gulp.src('./test/config/karma.conf.js')
        .pipe($.inject(testFiles, {
            starttag: 'files: [',
            endtag: ']',
            transform: function (filepath, file, i, length) {
                return '  "' + filepath.substr(1) + '"' + (i + 1 < length ? ',' : '');
            }
        }));

    return pipe.pipe(gulp.dest('.'));
});
```

Not sure how it works, but the files in question are then entered into the karma config file in the correct order:

```
          [...]
          ".tmp_test/app/scripts/topsellers/topsellers.controller.js",
          ".tmp_test/app/scripts/topsellers/topsellers.service.js",
          ".tmp_test/app/scripts/topsellers/topsellerslist.directive.js",
          ".tmp_test/app/scripts/topsellers/app.js",
          [...]
```
(the app.js file references the other three)
even though in the glob, the app file is explicitly listed first:
```
var jsFiles = ['app/typings/tsd.d.ts', 'app/scripts/bootstrap.{js,ts}', 'app/scripts/app.{js,ts}', 'app/scripts/**/app.{js,ts}', 'app/scripts/**/*.{js,ts}'];
```

**Comment by wilgert** [comment]
+1 for building this enhancement!

**Comment by ArtemGovorov** [comment]
The feature is implemented in core 1.0.132. Here is the [doc section](http://wallabyjs.com/docs/integration/typescript.html#ordering-source-files-with-reference-comments) on how to turn it on.

**Comment by Burgov** [comment]
dude, awesome, thanks!

![image](https://cloud.githubusercontent.com/assets/417674/10535942/7e4c33b0-73e7-11e5-9d55-2cfd07c3ec3f.png)

**Comment by ArtemGovorov** [comment]
@Burgov Nice! Glad to see it's working for you.
