### ISSUE TITLE
Failed to parse packages

### ISSUE THREAD

**Issue by evgygor** [wallabyjs/public#1610]
### Issue description or question
Hi,
I'm working with monorepo, and the following error appears in console:

​​​​​[Info]​​​​​ Tue, 10 Apr 2018 14:31:03 GMT wallaby:project Error: Failed to parse packages/ui-components/src/components/atoms/Badge/Badge.js, SyntaxError: Unexpected token (34:16)
​​​​​[Info]​​​​​     at _combinedTickCallback (internal/process/next_tick.js:131:7)
​​​​​[Info]​​​​​     at process._tickCallback (internal/process/next_tick.js:180:9)
​​​​​[Info]​​​​​     at C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\server.js:18:9846
​​​​​[Info]​​​​​     at _rejected (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:864:24)
​​​​​[Info]​​​​​     at C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:890:30
​​​​​[Info]​​​​​     at Promise.when (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:1142:31)
​​​​​[Info]​​​​​     at Promise.promise.promiseDispatch (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:808:41)
​​​​​[Info]​​​​​     at C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:624:44
​​​​​[Info]​​​​​     at runSingle (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:137:13)
​​​​​[Info]​​​​​     at flush (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\q\q.js:125:13)
​​​​​[Info]​​​​​     at _combinedTickCallback (internal/process/next_tick.js:131:7)
​​​​​[Info]​​​​​     at process._tickCallback (internal/process/next_tick.js:180:9)

### Wallaby.js configuration file

```javascript
const path = require('path');

module.exports = function(wallaby) {
  process.env.NODE_PATH +=
    path.delimiter + path.join(wallaby.projectCacheDir, 'packages');

  return {
    files: [
      {
        pattern: 'packages/**/src/**/*.ts?(x)',
      },
      {
        pattern: 'packages/**/scripts/dashed-css-modules.js',
      },
      {
        pattern: 'packages/**/node_modules/**',
        ignore: true,
      },
      {
        pattern: 'packages/**/src/**/*.spec.ts?(x)',
        ignore: true,
      }
    ],

    tests: [
      {
        pattern: 'packages/**/src/**/*.spec.ts?(x)',
      },
      {
        pattern: "packages/**/node_modules/**",
        ignore: true
      }
    ],

    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript({ module: "es5"})
    },

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',
    debug: true,

    setup: function(wallaby) {
      var jestConfig = require('./package.json').jest;

      jestConfig.globals = { __DEV__: true };
      wallaby.testFramework.configure(jestConfig);
    },
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.22

### OS name and version

Windows 7 64bit

Thanks

**Comment by ArtemGovorov** [comment]
- Is there a root `tsconfig.json` in the project?
- Is there some JSX syntax in the `packages/ui-components/src/components/atoms/Badge/Badge` file?

**Comment by evgygor** [comment]
1. No tsconfig in root, each package have owns.
2. Yes, React + Typescript.

**Comment by ArtemGovorov** [comment]
Thanks,

this should help:

```js
    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript({ module: "es5", jsx: "React"})
    },
```

**Comment by evgygor** [comment]
It helped with the issue.
Thanks!

Noe the exception: 

[Info]​​​​​ Wed, 11 Apr 2018 08:11:52 GMT wallaby:workers [worker #1, session #fayho] Running tests in sandbox
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:52 GMT wallaby:workers Sandbox (active) [fayho] error: TypeError: Cannot set property 'globals' of undefined
​​[Error] Runtime error: TypeError: Cannot set property 'globals' of undefined​​
​​[Error]     at emitTwo (events.js:126:13)​​
​​[Error]     at WebSocket.emit (events.js:214:7)​​
​​[Error]     at afterWrite (_stream_writable.js:454:3)​​
​​[Error]     at onwrite (_stream_writable.js:445:7)​​
​​[Error]     at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​[Error]     at Zlib.callback (zlib.js:515:5)​​
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:52 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot set property 'globals' of undefined, stack: TypeError: Cannot set property 'globals' of undefined
​​​​​[Info]​​​​​     at eval (eval at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44), <anonymous>:4:26)
​​​​​[Info]​​​​​     at eval (eval at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44), <anonymous>:6:7)
​​​​​[Info]​​​​​     at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44)
​​​​​[Info]​​​​​     at b.in:run (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\server.js:16:23043)
​​​​​[Info]​​​​​     at WebSocket.<anonymous> (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\server.js:16:21835)
​​​​​[Info]​​​​​     at emitTwo (events.js:126:13)
​​​​​[Info]​​​​​     at WebSocket.emit (events.js:214:7)
​​​​​[Info]​​​​​     at Receiver.ontext (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\ws\lib\WebSocket.js:841:10)
​​​​​[Info]​​​​​     at C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-v
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:52 GMT wallaby:workers Sandbox (active) [61dk1] error: TypeError: Cannot set property 'globals' of undefined
​​[Error] Runtime error: TypeError: Cannot set property 'globals' of undefined​​
​​[Error]     at emitTwo (events.js:126:13)​​
​​[Error]     at WebSocket.emit (events.js:214:7)​​
​​[Error]     at afterWrite (_stream_writable.js:454:3)​​
​​[Error]     at onwrite (_stream_writable.js:445:7)​​
​​[Error]     at InflateRaw.afterTransform (_stream_transform.js:90:3)​​
​​[Error]     at Zlib.callback (zlib.js:515:5)​​
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:52 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot set property 'globals' of undefined, stack: TypeError: Cannot set property 'globals' of undefined
​​​​​[Info]​​​​​     at eval (eval at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44), <anonymous>:4:26)
​​​​​[Info]​​​​​     at eval (eval at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44), <anonymous>:6:7)
​​​​​[Info]​​​​​     at module.exports (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\runners\node\bootstrap.js:14:44)
​​​​​[Info]​​​​​     at b.in:run (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\server.js:16:23043)
​​​​​[Info]​​​​​     at WebSocket.<anonymous> (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\server.js:16:21835)
​​​​​[Info]​​​​​     at emitTwo (events.js:126:13)
​​​​​[Info]​​​​​     at WebSocket.emit (events.js:214:7)
​​​​​[Info]​​​​​     at Receiver.ontext (C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.81\wallaby\node_modules\ws\lib\WebSocket.js:841:10)
​​​​​[Info]​​​​​     at C:\Users\eg874k\.vscode\extensions\WallabyJs.wallaby-v
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:53 GMT wallaby:workers [fayho] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:53 GMT wallaby:workers [61dk1] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:53 GMT wallaby:workers [fayho] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:53 GMT wallaby:workers [61dk1] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Wed, 11 Apr 2018 08:11:53 GMT wallaby:workers Merging parallel test run results

**Comment by evgygor** [comment]
Thank you for support.
I verified, currently we doesn't need to see all packages on same report :)
Thanks
