### ISSUE TITLE
Exports is not defined continued..

### ISSUE THREAD

**Issue by kubal5003** [wallabyjs/public#1614]
### Issue description or question
Some time ago I already reported this issue, but with input from other people you traced it to some Chrome bug and tests started working again after fixes. Since IMO the thing was not fully understood and fixed (I'm still getting those messages, but tests are executing), so I'm raising this again, now with new findings.

In each execution of tests I'm getting the 'exports is not defined' error, that is usually not preventing the test that I'm working on from executing properly. I was guessing it was coming from some other test..

Second - not sure if related problem is that whenever I change a source file - tests are not executed, but if I touch the spec file tests execute fine. Each time I'm getting the 'exports is not defined' message.

Today is a special day, because for the very first time I got this error for the test that I'm working on, so I got a chance to debug this live :)

I found out that in even a simple test like this one:

```javascript
import { ComponentFixture } from '@angular/core/testing';

fdescribe('InstructionLayoutComponent', () => {
  it('should be able to render component', () => {
    console.log(this);
  });
});
```
is causing this error to appear - it's sufficient to have at least a single import statement in the whole file. If I remove all the imports - problem disappears. Please also note that it doesn't really matter which import is added - whether this is source file, angular dependency or whatever. Just the fact of having ANY import is already causing the line below to appear in the source and crash the tests:

```javascript
Object.defineProperty(exports, '__esModule', { value: true });
```
The problem seems to be consistent with what is described here: https://github.com/Microsoft/TypeScript/issues/15795

The part that I'm missing is how wallaby & webpack are playing a role in this and how this is supposed to actually work.

Since I know the problem already I was trying to find a workaround. Adding exports does not change a thing here - problem persists. Trying to assign something to module.exports (CommonJS way) also has no effect. Workaround that actually works:

```javascript
import { ComponentFixture } from '@angular/core/testing';

let exports = {};

fdescribe('InstructionLayoutComponent', () => {
  it('should be able to render component', () => {
    console.log(this);
  });
});
```

For reference the full compiled source for this test (without workaround):
```javascript
'use strict';
$_$wp(952);
var _this = ($_$w(952, 0), this);
$_$w(952, 1), Object.defineProperty(exports, '__esModule', { value: true });
var exports = ($_$w(952, 2), {});
$_$w(952, 3), fdescribe('InstructionLayoutComponent', function () {
    $_$wf(952);
    $_$w(952, 4), it('should be able to render component', function () {
        $_$wf(952);
        $_$w(952, 5), $_$tracer.log(_this, '_this', 952, 5);
    });
});
$_$wpe(952);
```
and same with workaround (clearly var hoisting is in effect here..):
```javascript
'use strict';
$_$wp(952);
var _this = ($_$w(952, 0), this);
$_$w(952, 1), Object.defineProperty(exports, '__esModule', { value: true });
var exports = ($_$w(952, 2), {});
$_$w(952, 3), fdescribe('InstructionLayoutComponent', function () {
    $_$wf(952);
    $_$w(952, 4), it('should be able to render component', function () {
        $_$wf(952);
        $_$w(952, 5), $_$tracer.log(_this, '_this', 952, 5);
    });
});
$_$wpe(952);
```

### Wallaby.js configuration file

```javascript
const webpack = require('webpack');
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

module.exports = function(wallaby) {
  const webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['test-config/spec-bundle-wallaby.js', 'src/app/**/*spec.js'],
    module: {
      loaders: [
        { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
        { test: /\.css$/, loaders: ['to-string-loader', 'css-loader'] },
        { test: /\.scss$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.html$/, loader: 'html-loader' }
      ]
    },
    resolve: {
      extensions: ['.js'],
      modules: [path.join(wallaby.projectCacheDir, 'src')]
    },
    plugins: [new webpack.NormalModuleReplacementPlugin(/\.(gif|png|jpg|svg|mp4|css)$/, 'node-noop')]
  });

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'test-config/matchers.ts', load: false, instrument: false },
      { pattern: 'test-config/spec-bundle-wallaby.js', load: false, instrument: false },
      { pattern: 'src/app/**/*.css', load: false },
      { pattern: 'src/app/**/*.scss', load: false },
      { pattern: 'src/app/**/*.html', load: false },
      { pattern: 'src/app/**/*.json', load: false },
      { pattern: 'src/app/**/*spec.ts', ignore: true },
      { pattern: 'src/app/**/*.d.ts', ignore: true }
    ],
    filesWithNoCoverageCalculated: ['src/test/**/*.ts'],
    tests: ['src/app/**/*spec.ts'],
    testFramework: 'jasmine',
    middleware: function(app, express) {
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },
    env: {
      kind: 'chrome'
    },
    postprocessor: webpackPostprocessor,
    setup: function() {
      window.__moduleBundler.loadTests();
    },
    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm 2018.1

### OS name and version
OSX HighSierra 10.13.3

**Comment by ArtemGovorov** [comment]
The compiled source that you've listed is not supposed to be executed. If you take a look into the wallaby cache (where you found the compiled source), you need to open files that end with `*spec.js.wbp.js`. You'll see that the file looks like:

```js
window.__moduleBundler.cache["..."] = [function(__webpack_require__, module, exports, __webpack_exports__) {
... // compiled content
}, window.__moduleBundler.deps];
```

so the `exports` is defined as a wrapping function parameter, so it is defined and should not cause any issues.

My suspicion is that somehow in your project the compiled and unwrapped content may be executed, but I'm not sure how it may happen, your config looks ok.

I can't reproduce the issue locally, trying on this project: https://github.com/wallabyjs/ngCliWebpackSample. Could you please try the repo to check if it's working for you ([this simple test imports things](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/app/app.component.spec.ts)). If it is working, then the issue may be your project specific. In this case, please create a sample repo demonstrating the issue, we're happy to take a look.

This issue also doesn't seem to be related to [the other issue](https://github.com/wallabyjs/public/issues/1514) you've been referring to.

**Comment by kubal5003** [comment]
I did verify that the file you mentioned does exist. However for some reason this is not the one that is being executed in the browser.

```javascript
window.__moduleBundler.cache["/Users/kubal5003/Library/Caches/WebStorm2018.1/wallaby/projects/ca33b875856602c7/instrumented/src/app/components/shared/instruction-layout/instruction-layout.component.spec.js"] = [function(__webpack_require__, module, exports, __webpack_exports__) {"use strict";
$_$wp(333);
var _this = ($_$w(333, 0), this);
$_$w(333, 1), Object.defineProperty(exports, '__esModule', { value: true });
$_$w(333, 2), fdescribe('InstructionLayoutComponent', function () {
    $_$wf(333);
    $_$w(333, 3), it('should be able to render component', function () {
        $_$wf(333);
        $_$w(333, 4), $_$tracer.log(_this, '_this', 333, 4);
    });
});
$_$wpe(333);
}, window.__moduleBundler.deps];
```

**Comment by ArtemGovorov** [comment]
Ah, it's me being stupid, I should have noticed it immediately. 

The issue is that your tests are loaded via script tags because they are defined as:
```js
tests: ['src/app/**/*spec.ts'],
```
in your config. However, as [the docs say](https://wallabyjs.com/docs/integration/webpack.html), when using webpack you need to add `load: false` to them (as well as to all files that you need to be webpack-ed):

```js
tests: [{ pattern: 'src/app/**/*spec.ts', load: false }],
```

Sorry that I didn't spot this earlier.
