### ISSUE TITLE
Wallaby js stopped working after ejecting create react app

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#1616]
### Issue description or question
Wallaby js stopped working after ejecting create react app

Link to my repository and branch:

https://github.com/smarigowda/react16Revision/tree/REAC-20-eject-to-get-control-on-webpack-config

### Wallaby.js configuration file

https://github.com/smarigowda/react16Revision/blob/REAC-20-eject-to-get-control-on-webpack-config/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

OSX Mac OS Sierra

Link to my repository and branch:

https://github.com/smarigowda/react16Revision/tree/REAC-20-eject-to-get-control-on-webpack-config

**Comment by ArtemGovorov** [comment]
The error message from Jest seems helpful: wallaby can't find your polyfills and other files under `config`, because those are missing in your `files` list. Had sen you the [PR to fix the config](https://github.com/smarigowda/react16Revision/pull/22).
