### ISSUE TITLE
Grammar typo: "1 failing tests, X passing"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1619]
### Issue description or question

Grammar nit: this should be "1 failing test" (singular).

![image](https://user-images.githubusercontent.com/3335181/38838279-4e279710-418a-11e8-8dc4-f5f825301400.png)

### Code editor or IDE name and version

Visual Studio Code v1.22.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks! Fixed and will be published in 1.0.82.
