### ISSUE TITLE
Issue with Yarn Workspaces and top-level wallaby.js

### ISSUE THREAD

**Issue by urish** [wallabyjs/public#1620]
### Issue description or question

When using Wallaby.js with [TypeWiz](https://github.com/urish/typewiz) some tests fail. They pass when running directly through jest (you can verify by running `yarn test`). The tests that fail can be found in [configuration-parser.spec.ts](https://github.com/urish/typewiz/blob/1e0b87ab2ab43b41186d55df9839358f50dbf4d1/packages/typewiz-core/src/configuration-parser.spec.ts). They fail due to wrong version of `ajv` being imported in [configuration-parser.ts](https://github.com/urish/typewiz/blob/1e0b87ab2ab43b41186d55df9839358f50dbf4d1/packages/typewiz-core/src/configuration-parser.ts#L1). When running under wallaby.js, it imports the package from the project's top-level `node_modules` instead of importing it from `node_modules` instead `packages/typewiz-core`, thus importing and older version (5.x instead of 6.x).

I'm not sure if it can even work with just one toplevel `wallaby.js` for all projects in the monorepo. I'd be delighted if it can, but creating a `wallaby.js` file per sub-project is also an acceptable solution.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            'packages/*/src/**/*.ts',
            'packages/*/src/**/*.json',
            { pattern: 'packages/*/fixtures/**/*', instrument: false },
            { pattern: 'packages/typewiz/dist/**.js', instrument: false },
            { pattern: 'packages/typewiz/package.json', instrument: false },
            { pattern: 'packages/*/src/**/*.spec.ts', ignore: true },
        ],

        tests: ['packages/*/src/**/*.spec.ts'],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: () => {
            if (!global._vmPatched) {
                const vm = require('vm');
                const createContext = vm.createContext;
                const runInNewContext = vm.Script.prototype.runInNewContext;
                const wallabyGlobals = { $_$wp, $_$wpe, $_$w, $_$wf, $_$wv, $_$tracer };
                vm.createContext = function() {
                    arguments[0] = Object.assign(arguments[0] || {}, wallabyGlobals);
                    return createContext.apply(this, arguments);
                };
                vm.Script.prototype.runInNewContext = function() {
                    arguments[0] = Object.assign(arguments[0] || {}, wallabyGlobals);
                    return runInNewContext.apply(this, arguments);
                };
                global._vmPatched = true;
            }
        },
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

Windows 10

**Comment by urish** [comment]
And I have to say thank again for creating Wallaby.js and improving it all the time! At some point, I have given up writing unit-tests, but then I was lucky enough to discover Wallaby and it was all joy again :-)

**Comment by ArtemGovorov** [comment]
> thank you for creating Wallaby.js and improving it all the time

Thanks for your feedback Uri!

> When running under wallaby.js, it imports the package from the project's top-level node_modules instead of importing it from node_modules instead packages/typewiz-core, thus importing and older version (5.x instead of 6.x).

This is a bug. We have just fixed it and published the fix in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Comment by urish** [comment]
Confirmed - fix working for me. You are amazing!
