### ISSUE TITLE
Having problems setting up

### ISSUE THREAD

**Issue by cavaloni** [wallabyjs/public#1621]
### Issue description or question
I am getting this error when trying to run:

```
​​​​​[Info]​​​​​ Tue, 17 Apr 2018 22:48:21 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Tue, 17 Apr 2018 22:48:21 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 132 project files none were found by patterns: **/*.ts?(x)
​​​​​[Info]​​​​​ Tue, 17 Apr 2018 22:48:21 GMT wallaby:project TypeScript postprocessor is removed as requested by itself
​​​​​[Info]​​​​​ Tue, 17 Apr 2018 22:48:21 GMT wallaby:postprocessor New compiler created
​​[Error] clean-webpack-plugin: /Users/chad.avalon/Documents/projects/ce/build_dev has been removed.​​
​​​​​[Info]​​​​​ Tue, 17 Apr 2018 22:48:21 GMT wallaby:postprocessor Webpack compilation started
​​[Error] TypeError: Data must be a string or a buffer​​
​​[Error]     at TypeError (native)​​
​​[Error]     at Hash.update (crypto.js:75:16)​​
​​[Error]     at Compilation.modifyHash (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/lib/Compilation.js:1149:8)​​
​​[Error]     at Compilation.<anonymous> (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/lib/HotModuleReplacementPlugin.js:81:9)​​
​​[Error]     at Compilation.applyPlugins0 (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/node_modules/tapable/lib/Tapable.js:68:14)​​
​​[Error]     at sealPart2 (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/lib/Compilation.js:615:9)​​
​​[Error]     at Compilation.applyPluginsAsyncSeries (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/node_modules/tapable/lib/Tapable.js:195:46)​​
​​[Error]     at Compilation.seal (/Users/chad.avalon/Documents/projects/ce/node_modules/webpack/lib/Compilation.js:579:8)​​
​​[Error]     at /Users/chad.avalon/Documents/projects/ce/node_modules/webpack/lib/Compiler.js:493:16​​
​​[Error]     at /Users/chad.avalon/Documents/projects/ce/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11​​
​​[Error]     at _combinedTickCallback (internal/process/next_tick.js:73:7)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:104:9)​​

```
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConf = require('./static/config/webpack.config.dev');
var wallabyPostprocessor = wallabyWebpack(webpackConf);

// eslint-disable-next-line
module.exports = function(wallaby) {
	process.env.NODE_ENV = 'development';

	return {
		files: [
			{ pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
			'build_dev/**/*.js?(x)',
			'!build_dev/**/*.spec.js?(x)',
		],
		tests: [
			{
				pattern: 'comp/**/*.spec.js?(x)',
				load: false,
			},
		],

		compilers: {
			'**/*.js?(x)': wallaby.compilers.babel(),
		},

		testFramework: 'jest',

		postprocessor: wallabyPostprocessor,

		debug: true,

		env: {
			type: 'node',
			runner: 'node',
		},

		setup(wallaby) {
			const jestConfig = {
				coverageDirectory: 'coverage-jest/',
				collectCoverage: true,
				coverageReporters: ['lcov'],
				globals: {
					__webpack_public_path__: true,
				},
				snapshotSerializers: ['enzyme-to-json/serializer'],
				setupFiles: ['./shim.js', './setupEnzyme.js'],
				testMatch: ['**/__tests__/**/?(*.)(spec|test).js?(x)'],
				testPathIgnorePatterns: [
					'<rootDir>/node_modules/',
					'<rootDir>/cv/static',
					'<rootDir>/test/unit/',
					'/fixtures/',
					'shim.js',
				],
				coveragePathIgnorePatterns: ['/fixtures/'],
				verbose: false,
				moduleNameMapper: {
					'\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
						'<rootDir>/__mocks__/fileMock.js',
				},
			};
			wallaby.testFramework.configure(jestConfig);
		},
	};
};

```

### Code editor or IDE name and version

Visual Studio Code v1.22

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Jest [doesn't support webpack](https://facebook.github.io/jest/docs/en/webpack.html) (or to put it better - it doesn't need webpack to run tests). So you need to remove these lines from the config:

```
var wallabyWebpack = require('wallaby-webpack');
var webpackConf = require('./static/config/webpack.config.dev');
var wallabyPostprocessor = wallabyWebpack(webpackConf);
...
postprocessor: wallabyPostprocessor,
```

Also may need to slightly adjust your `files` list:

```diff
		files: [
-			{ pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
+                        '__mocks__/fileMock.js',
			'build_dev/**/*.js?(x)',
			'!build_dev/**/*.spec.js?(x)',
		],
```

One last thing - if your jest config resides in your package.json or in `jest.config.js` file in the project's root, then you may delete the `setup` function as wallaby will use the config from those sources automatically.

Let us know if it helps.

**Comment by cavaloni** [comment]
Thanks for your help. I guess I don't have quite the grasp on webpack.jest as I thought. When I do the things you listed it now cannot find the modules/files. 

I have this set in jest:

> "globals": {
> 		"__webpack_public_path__": true
> 	},

I am assuming this means it is using the webpack build for the files to be loaded? Which is set to be build_dev. Otherwise, where should `files` be pointing to? The build, or the jsx itself? Or maybe I am missing something else? Heres the config now:

```
module.exports = function(wallaby) {
	process.env.NODE_ENV = 'development';

	return {
		files: [
			'__mocks__/fileMock.js',
			'build_dev/**/*.js?(x)',
			'!build_dev/**/*.spec.js?(x)',
		],
		tests: [
			{
				pattern: 'comp/**/*.spec.js?(x)',
				// load: false,
			},
		],
		compilers: {
			'**/*.js?(x)': wallaby.compilers.babel(),
		},
		testFramework: 'jest',

		debug: true,

		env: {
			type: 'node',
			runner: 'node',
		},
	};
};
```

And here is an example of one of the many failures I get:

`​​[Error] Runtime error: Error: Cannot find module '../../__tests__/fixtures/redux-store' from 'controls-info.spec.js'​​`

**Comment by cavaloni** [comment]
It loads the tests fine, but not the modules.

**Comment by ArtemGovorov** [comment]
[`files` should be pointing to your app original source code](https://wallabyjs.com/docs/config/files.html) (not any build result). If wallaby complains it can't find any modules, it's likely that the file is not in the `files`.

**Comment by cavaloni** [comment]
Ok I realized that the ones that were failing were because it was importing from a scope outside of the directory. So now including the whole project, it seems to load everything ok (though it fails loading images) but now all of the tests are a white box (instead of green or red), and it seems to be trying to run 'tests' in the jsx files too, even though they are ignored by the glob pattern. 

Heres how it looks now:

```
module.exports = function(wallaby) {
	process.env.NODE_ENV = 'development';

	return {
		files: [
			'__mocks__/fileMock.js',
			'/**/*.js?(x)',
			'!/**/*.spec.js?(x)',
			'!node_modules/**/*.*',
			'!bower_components/**/*.*',
			'!syndio_main/**/*.*',
		],
		tests: [
			'/**/*.spec.js?(x)',
			'!node_modules/**/*.*',
			'!bower_components/**/*.*',
			'!syndio_main/**/*.*',
		],

		compilers: {
			'**/*.js?(x)': wallaby.compilers.babel(),
		},
		testFramework: 'jest',

		debug: true,

		env: {
			type: 'node',
			runner: 'node',
		},
	};
};

```

Thanks again for all of your help!

**Comment by ArtemGovorov** [comment]
> though it fails loading images

That's because images are not included in your `files` list, only `*.js?(x)` files. Including images pattern(s) should help.

> but now all of the tests are a white box (instead of green or red)

Looks like you are including more than required.
Do you have a root folder inside your project? Like `src` so you could just do:
```
files: [
			'__mocks__/fileMock.js',
			'src/**/*.js?(x)',
			'!src/**/*.spec.js?(x)',
		],
```
and the same with `tests`?

**Comment by cavaloni** [comment]
I appreciate your patience with your assistance. So I tried to include the images, which is only png in this project, like so

```
{
				pattern: 'comp/**/*.png*',
				load: false,
			},
```
Not it changes the error from not being able to find it, to not being able to parse it. Usually we would use webpack to work with image files, but since jest doesn't work with webpack, I am not sure what to do at this point. 

Thanks again!

**Comment by cavaloni** [comment]
Also, it appears it is trying to run on my component files (white boxes on the left in component files and not in test files). So it seems backwards, but my config does not appear to be backwards so I'm a bit confused by that.

```
		files: [
			'__mocks__/fileMock.js',
			'comp/**/*.js?(x)',
			{
				pattern: 'comp/**/*.png*',
				load: false,
				binary: true,
			},
			{
				pattern: 'admin/**/*.png*',
				load: false,
				binary: true,
			},
			{
				pattern: 'static/**/*.png*',
				load: false,
				binary: true,
			},
			'admin/**/*.js?(x)',
			'static/**/*.js?(x)',
			'!/**/*.spec.js',
		],
		tests: [
			'!admin/**/*.js?(x)',
			'!static/**/*.js?(x)',
			'!comp/**/*.js?(x)',
			'admin/**/*.spec.js?(x)',
			'comp/**/*.spec.js?(x)',
			'static/**/*.spec.js?(x)',
		],
```

**Comment by cavaloni** [comment]
Note: the `binary: true` part was an experiment which seemed to alleviate the above mentioned errors of parsing image files.

**Comment by cavaloni** [comment]
Also: there are no errors in the debug console now.

**Comment by cavaloni** [comment]
Ah got it. Subtracted lines as you suggested and now my test files are included, but react component files are still getting hit. Also, still a white square, after I run wallaby, and then run on file. No errors in the console.

<img width="1806" alt="screen shot 2018-04-19 at 8 48 10 am" src="https://user-images.githubusercontent.com/22948520/39002941-914b4944-43ae-11e8-9728-cc120d2d4daa.png">

**Comment by ArtemGovorov** [comment]
Just to check, could you please clone, `npm i` and run wallaby it [this sample repo](https://github.com/wallabyjs/wallaby-jest-snapshots) to see if it's working for you?

If it is working for you, then we'll need a reproducible sample of your project - you may just copy/paste the whole project, remove most of the source but leave one empty (or basic) test, one empty/basic component and share it with us (by attaching an archive or creating a sample GH repo). We'll take a look and quickly sort out what's wrong.

**Comment by cavaloni** [comment]
That project does work on my machine.

However, some of my co-workers are very reluctant to add any packages at all, and we are also knee deep in a few security audits, so I'm having a hard time to convince them to fork anything from the project. Might there be any other way or something else we can check? Thanks again.

**Comment by ArtemGovorov** [comment]
Because the issue is specific to your setup (the sample project is working for you), we need a sample project where the same issue as your can be reproduced. I don't think you need anything more to share than you've already shared in this issue. A simple test (not a real one) importing a simple component, like `<div></div>` should suffice.

**Comment by cavaloni** [comment]
I have added you @ArtemGovorov  as a collaborator on the project stripped of everything but setup and some fake components and tests, with the results matching those I've mentioned.

**Comment by ArtemGovorov** [comment]
I have sent the pull request to make it work. Wallaby console actually is clearly saying what was wrong with the config (and how to fix it):

<img width="1199" alt="screen shot 2018-04-25 at 9 53 52 am" src="https://user-images.githubusercontent.com/979966/39219576-b55df9ca-486e-11e8-9bba-9f74c1b4d52a.png">

**Comment by cavaloni** [comment]
Thanks for taking a look and getting things to work @ArtemGovorov. I appreciate your time. There were a few things you change that the console was not clear about though. For instance the setup function, and the inclusion of jest config in the files list. I had also previously tried what the console was saying too, as you can see from above, though it seems I had my glob patterns messed up. But it works now! So thanks again.
