### ISSUE TITLE
Wallaby seems to stop after only 1 of my Jest test suites

### ISSUE THREAD

**Issue by wldcordeiro** [wallabyjs/public#1622]
### Issue description or question

I have a project with 200+ suites, but every time I run Wallaby it's only showing 1 suite run and there are no errors present anywhere.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
	process.env.BABEL_ENV = 'test'
	process.env.NODE_ENV = 'test'
	return {
		files: [
			{ pattern: 'jest-setup.js' },
			{ pattern: 'src/**/*.js', instrument: true, load: false },
			{ pattern: '**/*.snap', instrument: false },
			{ pattern: 'src/**/*.mock.js', instrument: false, load: false },
			{ pattern: 'data/*.mock.js', instrument: true, load: false },
			{ pattern: 'config/env.config.js', instrument: false, load: false },
			{ pattern: 'src/**/*.story.js', ignore: true },
			{ pattern: 'src/**/*.test.js', ignore: true },
		],
		tests: [{ pattern: 'src/**/*.test.js' }],
		env: {
			type: 'node',
			runner: 'node',
		},
		testFramework: 'jest',
		compilers: {
			'jest-setup.js': wallaby.compilers.babel(),
			'src/**/*.js': wallaby.compilers.babel(),
			'data/*.mock.js': wallaby.compilers.babel(),
		},
	}
}
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It's possible that wallaby found [its special comment if one of your suites](https://wallabyjs.com/docs/intro/selected-tests.html#additional-configuration) and is only running that suite. If it's the case, wallaby will says that it's only running one test suite in the [Failing Tests output header](https://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests): `No failing tests, N passing (only executed <...>.js)`.

Please check it, and if it is not the case, then please [add `debug: true` to your wallaby config and share the full output from the Wallaby Console output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by wldcordeiro** [comment]
I looked and it wasn't the case, however the test itself was using `describe.only` which may be what confused wallaby

**Comment by ArtemGovorov** [comment]
This is expected then - `describe.only` is automatically switching wallaby to the mode of only running this test suite. If it's the case, wallaby also says that it's only running one test suite in the [Failing Tests output header](https://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests): `No failing tests, N passing (only executed <...>.js)`.

if you don't like the behaviour, you [may turn it off](https://wallabyjs.com/docs/intro/selected-tests.html#additional-configuration) by using the `automaticTestFileSelection` setting:
```js
module.exports = function (wallaby) {
  return {
    ...
    automaticTestFileSelection: false
  };
};
```

**Comment by wldcordeiro** [comment]
Ah I see. Well it was an errant `describe.only` 😄 It's the only `describe` in the file so it's implicitly `.only` I'll keep that config value in mind.

**Comment by ArtemGovorov** [comment]
Yeah, [wallaby now supports `.only` across multiple files](https://twitter.com/wallabyjs/status/981420172765429761) (whether it's `describe.only` or `it.only`). It may be handy if you'd like to debug/see coverage from a specific test/suite and don't show coverage from other suites.
