### ISSUE TITLE
Test fails due to upstream pretty-format package

### ISSUE THREAD

**Issue by TrevorBurnham** [wallabyjs/public#1626]
### Issue description or question

This one was a puzzler for me. I hit the same error mentioned in [this comment](https://github.com/wallabyjs/public/issues/1554#issuecomment-373518205) by @nathanvale:

```
TypeError: Cannot read property 'test' of undefined
  
  at findPlugin (../../node_modules/pretty-format/build/index.js:272:20)
      at Array.map (<anonymous>)
  at Object.<anonymous> (../../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.83/projects/cc362621f18cef70/instrumented/src/Form/__tests__/Form.js:25:35)
  at Object.e.length.arguments.(anonymous function) (../../../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.83/projects/cc362621f18cef70/instrumented/config/jest/setupTests.js:28:1786)

```

I tried to replicate in a new project but couldn't. Then I tried simply copying and pasting the project to a new directory—and still couldn't! Then I found that if I deleted `node_modules/` in a parent directory, the error went away and all tests passed. I isolated the source of the problem to one particular dependency, `lint-staged@6.1.1`, which in turn brings in `pretty-format@21.2.1`.

I've created a complete [test repo](https://github.com/TrevorBurnham/wallaby-bug-report). Steps to reproduce the bug in that repo:

1. `yarn install`
1. `cd subproject && yarn install`
1. Open in VS Code and run Wallaby

Note that the bug occurs whether you have the whole repo or just the `subproject/` dir open in your editor.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    testFramework: 'jest',

    env: {
      type: 'node',
      runner: 'node',
    },

    files: [
      'subproject/src/**/*.js',
      'subproject/src/**/*.snap',
      'subproject/jest.config.js',
      'subproject/config/jest/setupTests.js',
      '!subproject/src/**/__tests__/*.js',
    ],

    tests: ['subproject/src/**/__tests__/*.js'],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    setup(wallaby) {
      const jestConfig = require(`./subproject/jest.config.js`);
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

macOS 10.13.4

**Comment by ArtemGovorov** [comment]
Thanks for sharing the sample repo. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
