### ISSUE TITLE
Cannot find Jest test runner (Yarn workspace)

### ISSUE THREAD

**Issue by kristiandupont** [wallabyjs/public#1627]
### Issue description or question
```
​​[Error] Runtime error: Failed to initialize wallaby jest.​​
​​[Error] Error: Cannot find Jest test runner​​
```

This project is a part of a Yarn workspace, so `jest` inside the `.bin` folder is a symbolic link to the root `node_modules` folder. Is that part of the problem? I can run `jest` just fine on the command line.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'package.json',
      'src/**/*.ts',
      { pattern: 'src/**/*.test.ts', ignore: true }
    ],
    tests: [
      'src/**/*.test.ts'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup(wallaby) {
      var jestConfig = require('./package.json').jest;
      // for example:
      // jestConfig.globals = { "__DEV__": true };
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

This is my package.json file:
```json
{
  "name": "helpers",
  "private": true,
  "version": "1.0.0",
  "main": "build/index.js",
  "types": "build/index.d.ts",
  "license": "MIT",
  "scripts": {
    "test": "jest",
    "build": "tsc"
  },
  "dependencies": {},
  "devDependencies": {
    "@types/jest": "^22.2.3",
    "jest": "^22.4.3",
    "ts-jest": "^22.4.4",
    "typescript": "^2.8.1"
  },
  "jest": {
    "moduleFileExtensions": [
      "js",
      "jsx",
      "json",
      "ts",
      "tsx"
    ],
    "transform": {
      "^.+\\.(ts)$": "../../node_modules/ts-jest/preprocessor.js"
    },
    "testMatch": [
      "<rootDir>/src/**/*.test.ts"
    ],
    "testEnvironment": "node"
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.22.2

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Wallaby config needs to be on the same level where Jest is installed in the `node_modules`.  So if you move your config up with changing the paths in it accordingly (or make yarn leave jest in the package's node_modules), it then should work.

**Comment by swernerx** [comment]
I have the same issue. If I place the config file to the root of Yarn workspaces it fails again as it does not fine any file called "wallaby" then after trying to select it.
