### ISSUE TITLE
AssertionError is truncated and not very helpful

### ISSUE THREAD

**Issue by sertae** [wallabyjs/public#163]
Hello, I have a problem with not that useful assertion error message:
`expected { Object (firstName, lastName, ...) } to have keys 'countryCode', 'stateCode', 'zipCode', 'city', 'firstName', 'lastName', 'email', 'phone', 'line1', 'line2', 'company', and 'vatNumber'`
It's a guessing game what's missing.

While Mocha runner does the same and hides the object, Webstorm (I guess) adds a link at the end "Click to see difference":
`AssertionError: expected { Object (firstName, lastName, ...) } to have keys 'countryCode', 'stateCode', 'zipCode', 'city', 'firstName', 'lastName', 'email', 'phone', and 'line1' <Click to see difference>`

which opens this window:
![wallaby_more_info_needed](https://cloud.githubusercontent.com/assets/4718998/8273007/ee0e61fc-185a-11e5-8c90-af97f72ff7c7.png)

Can Wallaby have the same window/link when I click red icon?

Assertion I use in Chai.js that gives the error above:
`expect(address).to.have.all.keys([
                'countryCode',
                'stateCode',
                'zipCode',
                'city',
                'firstName',
                'lastName',
                'email',
                'phone',
                'line1',
                'line2',
                'company',
                'vatNumber'
            ]);`

I can check every key separately as a workaround. But I think that comparison window is a great addition anyway.

**Comment by ArtemGovorov** [comment]
Done, available in 1.0.21.

![assert](https://cloud.githubusercontent.com/assets/979966/8278280/81b19d72-190d-11e5-82b9-69b7e43d0797.gif)

**Comment by ArtemGovorov** [comment]
Forgot to update node.js integration, now works for it as well as for browser.
