### ISSUE TITLE
Boilerplate request? Webpack 3, Babel 7, React, styled-components, Jest (regular js tests, snapshots, jest-styled-components), absolute & relative import paths?

### ISSUE THREAD

**Issue by reywright** [wallabyjs/public#1630]
I'm having a lot of troubles getting up and running. I feel like if there was a boilerplate with all the above, I could really get on board.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version
Visual Studio Code v1.22.1

### OS name and version
OSX 10.13.3

**Comment by ArtemGovorov** [comment]
This [sample repo config](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/wallaby.js) should be enough to get started with the above mentioned stack. This [Jest specific article in our docs](https://wallabyjs.com/docs/integration/jest.html) should also be helpful.
