### ISSUE TITLE
wallaby does not like https link inside package.json for dependencies?

### ISSUE THREAD

**Issue by reywright** [wallabyjs/public#1631]
### Issue description or question

So you can put stuff like this in your package.json: `"git+https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:x-oauth-basic@github.com/user/private-repo.git#xxxxxxx"`

I figured out that wallaby was having some problem with my package.json. Removing this one seemed to fix it (I've edited out my private repo information of course). This is using the jest sample setup.

### Code editor or IDE name and version

Visual Studio Code v122.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby doesn't install any dependencies, in fact it doesn't even use/read `package.json` `dependencies`/`devDependencies`. 

What kind or error was reported? Could you please share the full error message reported by wallaby?

**Comment by reywright** [comment]
I'll close for now until I run into this again, but I'm pretty sure it says somewhere in documentation that you read the jest config from the package.json? maybe the format of what is in the dependencies can mess that up.

https://github.com/wallabyjs/public/issues/1633

I posted a code example here. Once I can get these working, then I'll see if this works again.
