### ISSUE TITLE
Can't specify more simplified glob without tests not being picked up?

### ISSUE THREAD

**Issue by reywright** [wallabyjs/public#1635]
You recently helped me, thought I'd make a new separate issue.

I'd like to use a more simplified glob pattern but when I do, Wallaby does not pick up the files. Any ideas?

### Wallaby.js configuration file

https://github.com/reywright/wallaby-nowork

### Code editor or IDE name and version

Visual Studio Code v1.22.1

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Just pulled the latest version of your repo, and everything seems to be working for me:

<img width="1274" alt="screen shot 2018-04-26 at 1 49 40 pm" src="https://user-images.githubusercontent.com/979966/39284845-b182b83c-4958-11e8-9ed3-53c029876d16.png">

> Wallaby does not pick up the files

Could you please provide some more details? What files are not picked up and what errors are reported?

**Comment by reywright** [comment]
Sorry about the lack of details. I was just having trouble specifying a better glob pattern. Looking at one of the examples helped. This is what I have now:

```
    files: [
      "app/javascript/root/**/*.js?(x)",
      "!app/javascript/root/**/*.test.js?(x)",
      "config/jest/*.js"
    ]
```

I was able to bring the config into my private project, and now it all works! Thanks for all your help.
