### ISSUE TITLE
I can't get Wallaby to work with Zeit Next + Jest/Enzyme.

### ISSUE THREAD

**Issue by haluvibe** [wallabyjs/public#1636]
### Issue description or question

I can't get Wallaby to work with Zeit Next + Jest/Enzyme.

In particular I think it's an issue with -> babel-plugin-module-resolver

Wallaby does start, I can see Wallaby's boxes but they are all white.

One box is red however which gives me hope that's a simple fix away from working, it's saying Error cannot find module which is why I believe it's todo the that resolver module

### Wallaby.js configuration file

```javascript
/* eslint-disable */
module.exports = function(wallaby) {
  return {
    files: [
      'layouts/**/*.js?(x)',
      'components/**/*.js?(x)',
      'materials/**/*.js?(x)',
      'elements/**/*.js?(x)',
      'localization/**/*.js?(x)',
      'pages/**/*.js?(x)',
    ],

    tests: ['**/*.test.js?(x)', '!node_modules/**/*.test.js?(x)'],

    testFramework: 'jest',
    debug: true,

    env: {
      type: 'node',
      runner: 'node',
    },

    setup: function() {
      const jestConfig = require('./package.json').jest;
      // for example:
      // jestConfig.globals = { "__DEV__": true };
      wallaby.testFramework.configure(jestConfig);
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: [['env'], 'next/babel'],
        plugins: [
          [
            'module-resolver',
            {
              root: ['./'],
              alias: {
                utils: './utils',
                materials: './materials',
                elements: './elements',
                components: './components',
                layouts: './layouts',
                localization: './localization',
                pages: './pages',
              },
            },
          ],
        ],
      }),
    },
  };
};

```

### Code editor or IDE name and version
Atom v1.25.1

### OS name and version

OSX High Sierra

**Comment by ArtemGovorov** [comment]
We have some users using `babel-plugin-module-resolver` without any issues. I have also just tried to run a simple repo with the `babel-plugin-module-resolver` and it's working for me.

Check the errors [printed in Wallaby Console](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting), I think your `files` and `tests` patterns may overlap and wallaby should display an error about it.

If there's nothing reported, please create a sample repo demonstrating the issue, we are happy to have a look.

**Comment by haluvibe** [comment]
Yes please do take a look -> https://github.com/haluvibe/wallabytest

**Comment by haluvibe** [comment]
With the minimal repository I do get the error -> ```Error: Cannot find module './helpers.js' from 'helpers.test.js'
at Object.<anonymous> utils/helpers.test.js:3:0```

**Comment by haluvibe** [comment]
but the other files with tests don't give errors, just white boxes

**Comment by ArtemGovorov** [comment]
Thanks. I [have sent you the PR](https://github.com/haluvibe/wallabytest/pull/1).

> With the minimal repository I do get the error -> ```Error: Cannot find module './helpers.js' from 'helpers.test.js'
at Object.<anonymous> utils/helpers.test.js:3:0```

This is because `utils` folder was missing the the `files` patterns.

Next error ([printed in Wallaby Console](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) as I have been mentioning) is that the `files` and `tests` patterns overlap,  so have fixed it in the config as well (just like the console error message suggest).

After fixing those I see the following error:

> Cannot find module '../components/LanguageSelector/LanguageSelector' from 'DefaultLayout.jsx'

but it is expected because the `components` folder is missing in the sample repo.

**Comment by haluvibe** [comment]
Yes it all works perfect now, thx so much
