### ISSUE TITLE
coverage report suggestion

### ISSUE THREAD

**Issue by streamnsight** [wallabyjs/public#1638]
Suggestion:

to fix coverage issues, it is useful to know what files has the most lines not covered.
In the current version, the web UI gives the total line count and the count of covered lines, but not the count of NOT covered lines, which is the important one IMO. I'd rather have NOT covered count than covered count. 
That's what I look for to figure where to spend my time: tackle the files with the most missed lines first.

**Comment by ArtemGovorov** [comment]
Doesn't the first column (Coverage %) fit the purpose?

**Comment by ArtemGovorov** [comment]
Good point. We have implemented and released the change in Wallaby.js App v1.0.38.
