### ISSUE TITLE
wallabyJS does not run until manually saved

### ISSUE THREAD

**Issue by gxspin** [wallabyjs/public#1639]
### Issue description or question
After I start wallaby, all unit tests and code lines are gray. wallabyjs.com/app shows coverage is 0%.
When i go to a unit tests change something (for example: add a whitespace) and save, then wallaby runs this unit test, the lines in this unit test file and covered code becomes green, and the wallabyjs.com/app shows some code coverage related to this unit test file.

If i manually save another unit tests file, wallaby runs that file and add those related code to code coverage.

When starting wallaby, in "Wallaby.js - Console", it shows error:
......
Mon, 30 Apr 2018 10:27:13 GMT wallaby:middleware Serving /jasmine@2.1.3/starter.js from disk
Mon, 30 Apr 2018 10:27:13 GMT wallaby:middleware Preparing to serve /systemjs.config.extras.js
Mon, 30 Apr 2018 10:27:13 GMT wallaby:middleware Serving /systemjs.config.extras.js from disk
Mon, 30 Apr 2018 10:27:13 GMT wallaby:middleware ENOENT: no such file or directory, open 'C:\Users\a\AppData\Local\Temp\.wallaby\projects\Ot+zHxj0n9fb0Ic20kvilsFM9Y=\cache\instrumented\systemjs.config.extras.js'
console.log: Warning: System.import could not load the optional "systemjs.config.extras.js". Did you omit it by accident? Continuing without it.
console.log: { [Error: Fetch error: 404 Not Found
  Instantiating http://localhost:59246/systemjs.config.extras.js
  Loading systemjs.config.extras.js] originalErr: [Error: Fetch error: 404 Not Found] }
Mon, 30 Apr 2018 10:27:14 GMT wallaby:middleware Preparing to serve /src/1st.spec.js
Mon, 30 Apr 2018 10:27:14 GMT wallaby:middleware Serving /src/1st.spec.js from cache
......

......
Mon, 30 Apr 2018 10:27:14 GMT wallaby:workers Sandbox (active) [t1b75] error: [object ErrorEvent]
Runtime error: [object ErrorEvent]
at :
Mon, 30 Apr 2018 10:27:14 GMT wallaby:workers Failed to map the stack to user code, entry message: [object ErrorEvent], stack: [object ErrorEvent]
at :
......

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            // System.js for module loading
            { pattern: 'node_modules/systemjs/dist/system.js', instrument: false },
            { pattern: 'systemjs.config.js', instrument: false },
            { pattern: 'systemjs.config.extras.js', instrument: false },

            // Polyfills
            { pattern: 'node_modules/core-js/client/shim.min.js', instrument: false },
            { pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false },

            // zone.js
            { pattern: 'node_modules/zone.js/dist/zone.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/long-stack-trace-zone.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/proxy.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/sync-test.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/jasmine-patch.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/async-test.js', instrument: false },
            { pattern: 'node_modules/zone.js/dist/fake-async-test.js', instrument: false },

            // application (but not specs) loaded via module imports
            { pattern: 'src/**/*+(ts|html|css)', load: false },
            { pattern: 'src/**/*.spec.ts', ignore: true },

            { pattern: 'testing/**/*+(ts|html|css)', load: false }
        ],

        tests: [
            { pattern: 'src/**/*.spec.ts', load: false }
        ],

        env: {
            kind: 'electron'
        },

        middleware: function (app, express) {
            app.use('/node_modules', express.static(require('path').join(__dirname, 'node_modules')));
        },

        testFramework: 'jasmine',

        debug: true,

        bootstrap: bootstrap,
        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
        }
    };
};

// Like karma-test-shim.js
function bootstrap(wallaby) {
    wallaby.delayStart();

    System.config({
        // Extend usual application package list with test folder
        packages: { 'testing': { main: 'index.js', defaultExtension: 'js' } },

        // Assume npm: is set in `paths` in systemjs.config
        // Map the angular testing umd bundles
        map: {
            '@angular/core/testing': 'npm:@angular/core/bundles/core-testing.umd.js',
            '@angular/common/testing': 'npm:@angular/common/bundles/common-testing.umd.js',
            '@angular/compiler/testing': 'npm:@angular/compiler/bundles/compiler-testing.umd.js',
            '@angular/platform-browser/testing': 'npm:@angular/platform-browser/bundles/platform-browser-testing.umd.js',
            '@angular/platform-browser-dynamic/testing': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js',
            '@angular/http/testing': 'npm:@angular/http/bundles/http-testing.umd.js',
            '@angular/router/testing': 'npm:@angular/router/bundles/router-testing.umd.js',
            '@angular/forms/testing': 'npm:@angular/forms/bundles/forms-testing.umd.js',
            'angular2-moment/module': 'node_modules/moment/index.js',
            'ionic-angular': 'node_modules/ionic-angular/bundles/ionic.umd.js',
            'linqts': 'node_modules/linqts/dist/linq.umd.js'
        },
    });

    System.import('systemjs.config.js')
        .then(importSystemJsExtras)
        .then(initTestBed)
        .then(initTesting);

    /** Optional SystemJS configuration extras. Keep going w/o it */
    function importSystemJsExtras() {
        return System.import('systemjs.config.extras.js')
            .catch(function (reason) {
                console.log(
                    'Warning: System.import could not load the optional "systemjs.config.extras.js". Did you omit it by accident? Continuing without it.'
                );
                console.log(reason);
            });
    }

    function initTestBed() {
        return Promise.all([
            System.import('@angular/core/testing'),
            System.import('@angular/platform-browser-dynamic/testing')
        ])

            .then(function (providers) {
                var coreTesting = providers[0];
                var browserTesting = providers[1];

                coreTesting.TestBed.initTestEnvironment(
                    browserTesting.BrowserDynamicTestingModule,
                    browserTesting.platformBrowserDynamicTesting());
            })
    }

    // Load all spec files and start wallaby
    function initTesting() {
        return Promise.all(
            wallaby.tests.map(function (specFile) {
                return System.import(specFile);
            })
        )
            .then(function () {
                wallaby.start();
            })
            .catch(function (e) {
                setTimeout(function () {
                    throw e;
                }, 0);
            });
    }
}

```

### Code editor or IDE name and version
Visual Studio Professional 2017(version 15.6.4)

### OS name and version

Windows 10

**Comment by gxspin** [comment]
I appreciate it very much if you could point me to the right the direction. Thanks!

**Comment by ArtemGovorov** [comment]
> all unit tests and code lines are gray

Please create a sample repo demonstrating the issue. Add your configs, and one test file with an empty test like below (no real project source code is required).

```js
it('is gray', () => {
  console.log('only executed manually')
})
```

Once the repo is published, please let us, we are happy to have a look.

**Comment by gxspin** [comment]
I noticed one line in the 800 lines of output:
Tue, 01 May 2018 09:12:43 GMT wallaby:middleware ENOENT: no such file or directory, open 'C:\Users\a\AppData\Local\Temp\.wallaby\projects\Ot+zHxj0n9fb0Ic20kvilsFM9Y=\cache\instrumented\node_modules\linqts\dist\linq.umd.js'

Looked more carefully found that there is a typo in my wallaby.js file:
`
function bootstrap(wallaby) {
    wallaby.delayStart();

    System.config({
        packages: { 'testing': { main: 'index.js', defaultExtension: 'js' } },

        map: {
            'linqts': 'node_modules/linqts/dist/linq.umd.js'
        },
//...
`
"linq.umd.js" should be "linqts.umd.js"

This fixed the issue.

May I suggest that if this kind of error happens (file not found), it should be output as an error and more obvious to user, and it should not stop the whole project from running.

Thanks for your help!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

We do the opt-in [`env.report404AsError` setting](https://wallabyjs.com/docs/config/runner.html) that allows to report such errors in a better and more noticeable way (even without `debug: true` setting). It's off by default, because many users have request some missing resources from their tests (that don't affect those tests). You may set it the `env.report404AsError` value to `true` to get those as errors in the console.
