### ISSUE TITLE
InvalidCastException thrown when starting Wallaby

### ISSUE THREAD

**Issue by nevadascout** [wallabyjs/public#164]
I'm using the Visual Studio beta of Wallaby, and on launch I get a message telling me that an extension caused an exception.

When I try to start wallaby, it says that it failed to start and that I should look at the output or log file. The output pane contains nothing about wallaby, so this is a non-starter.

This is the second time this has happened to me. The time before this, I fixed it by uninstalling and re-installing the vsix extension.

I'm using Visual Studio 2013 Premium Update 4.

**Comment by cResults** [comment]
I’m new to Wallabyjs as well.  Are you aware that you can add ‘debug: true’ to the wallaby.js file to get more info?  If not, then you may benefit from reading the post on trouble-shooting<http://wallabyjs.com/docs/intro/troubleshooting.html>.

I hope this helps.

Respectfully,

cResults

**Comment by nevadascout** [comment]
I wasn't aware of this, thanks!

**Comment by ArtemGovorov** [comment]
@nevadascout Did you find the log file? It should be in `\Users\%username%\AppData\Local\Temp\.wallaby\`. Is there anything helpful in the log file?

**Comment by nevadascout** [comment]
I haven't had a chance to look yet, but I will when I get to work tomorrow morning. I'll let you know what I find!

**Comment by ArtemGovorov** [comment]
@nevadascout Thanks, this log file `c:\Users\%username%\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml` content may be useful as well.

**Comment by nevadascout** [comment]
Here's the stack trace from the wallaby log file:

```
2015-06-22 15:16:08Z [72] Error Wallaby.Runner 0: Failed to start Runner.
System.TypeInitializationException: The type initializer for 'System.Reactive.Linq.Observable' threw an exception. ---> System.InvalidCastException: Unable to cast object of type 'System.Reactive.PlatformServices.CurrentPlatformEnlightenmentProvider' to type 'System.Reactive.PlatformServices.IPlatformEnlightenmentProvider'.
   at System.Reactive.PlatformServices.PlatformEnlightenmentProvider.get_Current()
   at System.Reactive.Linq.QueryServices.Initialize()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at System.Reactive.Linq.QueryServices.GetQueryImpl[T](T defaultInstance)
   at System.Reactive.Linq.Observable..cctor()
   --- End of inner exception stack trace ---
   at System.Reactive.Linq.Observable.Buffer[TSource](IObservable`1 source, TimeSpan timeSpan, IScheduler scheduler)
   at ⁫‬‬‏‎‌‎⁫‬⁭⁪‫‫‏⁮‍‫‌⁯⁫‌‫‪‭⁬⁭⁬‍⁫‍‎⁬‫‬‬⁫‍‍⁫‮.;p_@ ~Y6lYjDhd~U5=nHfXx>.MoveNext()
```

**Comment by ArtemGovorov** [comment]
@nevadascout We have tried to fix the issue, please try the latest version (1.0.10) to see if it's gone.

**Comment by nevadascout** [comment]
Thanks! How can I get the latest version?

Normally wallaby updates itself automatically when I run it, but as I can't actually start it, how do I get hold of the update?

**Comment by ArtemGovorov** [comment]
@nevadascout You may uninstall it via "Extensions and Updates", get the latest [from our website](http://wallabyjs.com/#download) and install it.

**Comment by nevadascout** [comment]
Cool, thanks. Will let you know if this works or not...

**Comment by nevadascout** [comment]
That's fixed it, awesome! Thanks again :)

**Comment by ArtemGovorov** [comment]
@nevadascout Awesome, thanks!
