### ISSUE TITLE
Wallaby not finding wallabyTest.js

### ISSUE THREAD

**Issue by c-science1** [wallabyjs/public#1640]
### Issue description or question
Facing this weird issue that Wallaby is still complaining about not finding wallabyTest.js file even tough I have it saved as attached.

Unable to move ahead with Wallaby due to this. Also I can't seem to see the Wallaby toolbar I used to have in my previous company using phpStorm.

### Wallaby.js configuration file

![image](https://user-images.githubusercontent.com/19345360/39565103-adf07654-4eae-11e8-92ce-9893ff84183d.png)

### Code editor or IDE name and version

Visual Studio Code

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Check your `files` setting to make sure the file is there. My guess is that .ts (`wallabyTest.ts`) is there (if you copied your config from https://github.com/wallabyjs/ngCliWebpackSample), however yours is a .js file (`wallabyTest.js`). 

Regardless of the file extension used, `entryPatterns` should contain `wallabyTest.js` [even if the original file is TypeScript](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns) (it's correct as you have it now).

**Comment by ArtemGovorov** [comment]
> Also I can't seem to see the Wallaby toolbar I used to have in my previous company using phpStorm.

I'd recommend checking out [our VS Code tutorial](https://wallabyjs.com/docs/intro/get-started-vscode.html) to find out where wallaby UI elements that you got used to in PhpStorm are located in VS Code. Specifically Failing tests toolbar is located in the [corresponding output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests), same for Wallaby Console.

**Comment by c-science1** [comment]
Thanks, I got it working by changing it to .ts but somehow messed up the config file which I have put back to

https://github.com/wallabyjs/ngCliWebpackSample/blob/82d4f43d1a1e701de403a2cdb38986bfb4ddca0b/wallaby.js

but keep on getting the message below even after having reinstall node-modules 

![image](https://user-images.githubusercontent.com/19345360/39575479-93c7c75e-4ed2-11e8-8790-92948c4e8073.png)

I am on a angular2 CLI project, I have even trying to install fs module which installed successfully but didn't make any different.

Any suggesstions would be appreciated!
