### ISSUE TITLE
Runtime error: Uncaught Error: Cannot find module "fs"

### ISSUE THREAD

**Issue by c-science1** [wallabyjs/public#1641]
I got Wallaby running but  by change but somehow messed up the config file which I have put back to

https://github.com/wallabyjs/ngCliWebpackSample/blob/82d4f43d1a1e701de403a2cdb38986bfb4ddca0b/wallaby.js

but keep on getting the message below even after having reinstall node-modules 

![image](https://user-images.githubusercontent.com/19345360/39575479-93c7c75e-4ed2-11e8-8790-92948c4e8073.png)

I am on a angular2 CLI project, I have even trying to install fs module which installed successfully but didn't make any different.

Any suggesstions would be appreciated!
here is my wallaby.js

```js
var wallabyWebpack = require('wallaby-webpack');
var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;
var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

**Comment by c-science1** [comment]
Hi,


Thanks but don't think that the app is using fs module anywhere..also searched for any references to it and there aren't any.


Failed to start stop operation, Error: ENOENT: no such file or directory, unlink 'C:\Users\Humzah\.PhpStorm2018.1\system\wallaby\projects\86ab2f14430564ec\instrumented\src\app\app-routing.module.js'
Fri, 04 May 2018 05:59:47 GMT wallaby:project Stopping test runner
    at Object.fs.unlinkSync (fs.js:1015:3)



Error is Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'



Kind Regards,
Sarah Saad


________________________________

**Comment by c-science1** [comment]
I have also tried removing the e2e folder completely and didn't make any difference.


Kind Regards,
Sarah Saad


________________________________

**Comment by ArtemGovorov** [comment]
> Thanks but don't think that the app is using fs module anywhere

It may not be the app code directly, it may be one of the modules imported in your tests/code.

> Error is Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'

Ah, it looks like we are getting somewhere. This error indicates that some e2e tests are included in the `tests` pattern. Try excluding the e2e tests pattern from your `tests` list.

**Comment by ArtemGovorov** [comment]
> Error is Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '....\node_modules\selenium-webdriver\lib'

This error indicates that some of your tests are e2e tests. if you're not sure which one, try going through you spec files one by one as described here https://github.com/wallabyjs/public/issues/1641#issuecomment-386465252 to find the e2e test.

**Comment by c-science1** [comment]
Finally got Wallaby all working -

Had **import {HttpClient} from 'selenium-webdriver/http';**
instead of 

import {HttpClient} from '@angular/common/http';

Thanks for all your help and time! I am hoping to now demo and present a good case for it's use.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
