### ISSUE TITLE
VSCode Command to generate Wallaby.js config

### ISSUE THREAD

**Issue by urish** [wallabyjs/public#1647]
### Issue description or question

Please add a VSCode command that generates a wallaby.js. This will be super useful in setting up Wallaby for a new project - you could probably provide a few common templates to start with - Mocha, Karma, Jest, etc. 

If you need any additional input or help implementing this please ping me. Thank you!

**Comment by smcenlly** [comment]
Closing this issue. We are addressing this request with our [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) feature. 

Right now Jest framework (from v24) is supported to work without Wallaby configuration, and Angular CLI (Jasmine + Webpack) is available for BETA use. We also now have [tutorials in our docs](https://wallabyjs.com/docs/tutorial/overview.html) that include ready-to-use configuration examples.
