### ISSUE TITLE
Unexpected token causing failure to run Jest & Sublime Text

### ISSUE THREAD

**Issue by j2is** [wallabyjs/public#1648]
### Issue description or question
Wallaby has stopped processing my Jest tests. Unsure if this is an issue with jest-cli or my recent upgrade to the latest Sublime Text build. Opening the console after running Wallaby I get the following:

```
 SyntaxError: Unexpected token {​​​​​
​​​​​[Info]:       ​​​​​
​​​​​[Info]:       at Object.require.extensions..js (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:2043)​​​​​
​​​​​[Info]:       at Module.r.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:12484)​​​​​
​​​​​[Info]:       at Module.i.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:10723)​​​​​
​​​​​[Info]:       at Module.i.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:
```

### Wallaby.js configuration file
Please see public repo [https://github.com/j2is/wallaby](https://github.com/j2is/wallaby)
```
module.exports = () => {
  return {
    files: [
      'src/js/*.js'
    ],
    tests: [
      'tests/unit/*Spec.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    debug: true
  };
};
```

### Code editor or IDE name and version
Sublime Text v3 3170

### OS name and version
OSX

**Comment by j2is** [comment]
Thanks for the speedy reply!

`[Info]: wallaby.js started​​​​​
​​​​​[Info]: v4.4.4​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Wallaby config: /Users/Jai/Repos/wallaby/wallaby.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:fs File added: package.json​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:fs File added: tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:fs File added: src/js/calculator.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project File cache: /Users/Jai/Library/Application Support/Sublime Text 3/Packages/Wallaby/projects/087c9b21ea2ebf8c​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:uiService Listening port 51235​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #0​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #1​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #2​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #3​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #4​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Starting run worker instance #5​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:workers Web server is listening at 58947​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Re-instrumenting original file because its ID has changed​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Preparing to process tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Starting processor pool (if not yet started)​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Re-instrumenting original file because its ID has changed​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Preparing to process src/js/calculator.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:03 GMT wallaby:project Starting processor pool (if not yet started)​​​​​
​​​​​[Info]: v4.4.4​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #2​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #0​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #1​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #3​​​​​
​​​​​[Info]: v4.4.4​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #4​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Started run worker instance (delayed) #5​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:processor No compilers found for tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Instrumenting tests/unit/calculatorSpec.js, via process pool: true​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:processor No compilers found for src/js/calculator.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Instrumenting src/js/calculator.js, via process pool: true​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:processor No preprocessors found for tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Writing to disk and caching processed file tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Re-attaching document block comment​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:processor No preprocessors found for src/js/calculator.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Writing to disk and caching processed file src/js/calculator.js​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Stopping process pool​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project File cache is up-to-date, starting full test run​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Running postprocessor​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:postprocessor New TypeScript language service is required​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 3 project files none were found by patterns: **/*.ts?(x)​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Postprocessor execution finished​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Postprocessor is removed as requested by itself​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Test run started; run priority: 3​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:project Running all tests​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers Starting test run, priority: 3​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #vp9pa]​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #vp9pa]​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #vp9pa]​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:04 GMT wallaby:workers [worker #0, session #vp9pa] Running tests in sandbox​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:workers Sandbox (active) [vp9pa] error: SyntaxError: Unexpected token {​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:workers Failed to map the stack to user code, entry message: SyntaxError: Unexpected token {, stack: SyntaxError: Unexpected token {​​​​​
​​[Error]:     at exports.runInThisContext (vm.js:53:16)​​
​​​​​[Info]:     at exports.runInThisContext (vm.js:53:16)​​​​​
​​[Error]:     at Module._compile (module.js:373:25)​​
​​​​​[Info]:     at Module._compile (module.js:373:25)​​​​​
​​[Error]:     at Module._extensions..js (module.js:416:10)​​
​​​​​[Info]:     at Module._extensions..js (module.js:416:10)​​​​​
​​[Error]:     at Module.load (module.js:343:32)​​
​​​​​[Info]:     at Object.require.extensions..js (/Users/Jai/Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:2043)​​​​​
​​[Error]:     at Function.Module._load (module.js:300:12)​​
​​​​​[Info]:     at Module.load (module.js:343:32)​​​​​
​​​​​[Info]:     at Function.Module._load (module.js:300:12)​​​​​
​​[Error]:     at Module.require (module.js:353:17)​​
​​​​​[Info]:     at Module.require (module.js:353:17)​​​​​
​​[Error]:     at require (internal/module.js:12:17)​​
​​​​​[Info]:     at Module.r.require (/Users/Jai/Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:12484)​​​​​
​​[Error]:     at _load_jsdom (/Users/Jai/Repos/wallaby/node_modules/jest-environment-jsdom/build/index.js:18:19)​​
​​[Error]:     at new JSDOMEnvironment (/Users/Jai/Repos/wallaby/node_modules/jest-environment-jsdom/build/index.js:36:31)​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:58:25​​
​​​​​[Info]:     at require (internal/module.js:12:17)​​​​​
​​[Error]:     at next (native)​​
​​​​​[Info]:     at _load_jsdom (/Users/Jai/Repos/wallaby/node_modules/jest-environment-jsdom/build/index.js:18:19)​​​​​
​​[Error]:     at step (/Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:191)​​
​​​​​[Info]:     at new JSDOMEnvironment (/Users/Jai/Repos/​​​​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:437​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:99​​
​​[Error]:     at runTestInternal (/Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:103:17)​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:161:23​​
​​[Error]:     at next (native)​​
​​[Error]:     at step (/Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:191)​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:437​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:147:99​​
​​[Error]:     at runTest (/Users/Jai/Repos/wallaby/node_modules/jest-runner/build/run_test.js:174:18)​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/index.js:67:64​​
​​[Error]:     at next (native)​​
​​[Error]:     at step (/Users/Jai/Repos/wallaby/node_modules/jest-runner/build/index.js:29:191)​​
​​[Error]:     at /Users/Jai/Repos/wallaby/node_modules/jest-runner/build/index.js:29:361​​
​​[Error]:     at process._tickCallback (node.js:369:9)​​
​​​​​[Info]: console.log: FAIL tests/unit/calculatorSpec.js​​​​​
​​​​​[Info]: ​​​​​
​​​​​[Info]: console.log:   ● Test suite failed to run​​​​​
​​​​​[Info]: ​​​​​
​​​​​[Info]:     SyntaxError: Unexpected token {​​​​​
​​​​​[Info]:       ​​​​​
​​​​​[Info]:       at Object.require.extensions..js (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:2043)​​​​​
​​​​​[Info]:       at Module.r.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:12484)​​​​​
​​​​​[Info]:       at Module.i.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:10723)​​​​​
​​​​​[Info]:       at Module.i.require (../../Library/Application Support/Sublime Text 3/Packages/Wallaby/wallaby/server.js:20:10723)​​​​​
​​​​​[Info]: ​​​​​
​​​​​[Info]: ​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:workers [vp9pa] Run 0 test(s), skipped 0 test(s)​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:workers [vp9pa] Sandbox is responsive, closing it​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Test run finished​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Processed console.log entries​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Processed loading sequences​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Processed executed tests​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Processed code coverage​​​​​
​​​​​[Info]: Thu, 10 May 2018 08:49:05 GMT wallaby:project Test run result processed and sent to IDE​​​​​
`

**Comment by ArtemGovorov** [comment]
Thanks!

> [Info]: v4.4.4​​​​​

Looks like your system default node.js version (that `node` command gets resolved to) is too old for Jest. Try installing a newer version, if the 4.4.4 needs to be your default version, you may install a newer version somewhere else (possibly via `nvm`) and [configure wallaby to use it](https://wallabyjs.com/docs/intro/install.html#nodejs-4).

**Comment by j2is** [comment]
Ah thanks so much. Will do that.
