### ISSUE TITLE
Using lodash-es with esm in typescript jest tests

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#1651]
### Issue description or question
I tried to use `lodash-es` as dependency to jest-based test cases sources, and after trying to set runner with `esm` still getting module import failures, looks like esm is not applied to lodash-es. Is there missing configurations or did I misconfigured esm?

### Wallaby.js configuration file

Example repo PR at https://github.com/kwonoj/hunspell-asm/pull/120, in current wallaby.js config, added esm config.

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.? latest
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
The issue does not seem to be wallaby related, looks like it is related to the fact that [`esm` doesn't supports Jest just yet](https://github.com/facebook/jest/issues/4842#issuecomment-385571373).

For now you may use [Babel](https://facebook.github.io/jest/docs/en/getting-started.html#using-babel) + [let Jest know to compile `lodash-es` module with it](https://stackoverflow.com/questions/42260218/jest-setup-syntaxerror-unexpected-token-export).
