### ISSUE TITLE
wallabyjs unable to find config file in "VS Live Share" project

### ISSUE THREAD

**Issue by VRspace4** [wallabyjs/public#1653]
### Issue description or question

Wallaby.js is unable to find the config file in a [VS Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) project.

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
    return {
      files: [
        'tsconfig.json',
        'src/**/*.ts',
        '!src/**/*.spec.ts'
      ],
      tests: [
        'src/**/*.spec.ts'
      ],
      env: {
        type: 'node',
        runner: 'node'
      },
      testFramework: 'jest'
    };
  };
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
You've referenced Visual Studio VS Live Share extension, however also mentioned that you are using VS Code. So I'm wondering what editor/extension are you using?

Also, could you please share a sample repo (can just be an empty/close to empty one with the wallaby config) where we could reproduce the issue?

**Comment by ArtemGovorov** [comment]
Thanks, I have taken a look and the issue doesn't seem to be wallaby specific. 

We look up the wallaby config by calling VS Code API [`workspace.findFiles` method](https://code.visualstudio.com/docs/extensionAPI/vscode-api) and it doesn't seem to work on the VS Live share guest side. The host side is working as expected.

So it's an existing VS Live Share extension/VS Code API limitation (temporary or permanent). I have a suspicion that it may not be the only limitation of the extension/API. Wallaby (as any test runner) needs a physical access to your local files to run tests, including your node modules. It doesn't look like the guest session really has all those real files available on the disk.

**Comment by ArtemGovorov** [comment]
Just to elaborate a bit on the API I mentioned, if you run this simple code on the guest side:
```js
          workspace.findFiles('**/*.*', '**/node_modules/**').then(f => {
            console.log(f);
          })
```
it returns an empty array for a shared workspace (even if it contains some files).

**Comment by bj97301** [comment]
This sucks.
