### ISSUE TITLE
Add option run compilation on webpack resolve

### ISSUE THREAD

**Issue by jljorgenson18** [wallabyjs/public#1657]
We are trying to get Wallaby working on a new Webpack project and we ran into an issue with our current setup. The docs state that we do not need to add Javascript loaders in Webpack and that we should use the Wallaby compilers. However, the Wallaby compilers do not factor in the resolve values in Webpack. This means that if we resolve a module that needs compilation through one of our custom resolve directories, it will fail. Here is our current wallaby config.

```js
process.env.NODE_ENV = 'test';
process.env.BABEL_ENV = 'development';

const webpack = require('webpack');
const path = require('path');
const wallabyWebpack = require('wallaby-webpack');

const wallabyWebpackConfig = {
    context: path.join(__dirname, './'),
    externals: {
        // Use external version of React
        react: 'React'
    },
    module: {
        rules: [
            {
                test: /\.(scss|css|less|jpe?g|png|gif|svg)$/,
                use: 'null-loader'
            }
        ]
    },
    plugins: [new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('development'),
        DEVELOPMENT: JSON.stringify(true),
        TEST: JSON.stringify(true)
    })],
    resolve: {
        modules: ['node_modules', path.join(__dirname, 'prosemirror'), path.join(__dirname, 'src')]
    }
};

const wallabyPostprocessor = wallabyWebpack(wallabyWebpackConfig);

module.exports = function (wallaby) {
    return {
        files: [
            // We can use externals to speed up the process
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
            { pattern: 'src/**/*.js', load: false },
            { pattern: 'src/**/*.test.js', ignore: true },
            {
                pattern: './test-assets/**',
                instrument: false,
                load: false
            }
        ],
        tests: [
            { pattern: 'src/**/*.test.js', load: false }
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },
        postprocessor: wallabyPostprocessor,
        testFramework: 'mocha',
        env: {
            kind: 'chrome'
        },

        setup: function () {
            // required to trigger test loading
            window.__moduleBundler.loadTests();
        },

        workers: {
            initial: 8,
            regular: 4
        }
    };
};
```

When we resolve with the "src" directory, the compilation fails. We are discussing redoing our configs to use the babel-plugin-root-import plugin (https://github.com/entwicklerstube/babel-plugin-root-import) instead, but ideally, there would be an option as to what files should be compiled.

**Comment by jljorgenson18** [comment]
@ArtemGovorov That seems to have done the trick. I am now having separate issues with the prosemirror folder but I can open another ticket if there is an actual problem.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! The prosemirror folder may not need the change and shoukld hopefully work as `path.join(__dirname, 'prosemirror')`. If the change to `wallaby.projectCacheDir` is required for it as well, then you need to add the folder to the `files` patterns as well, otherwise it's not in the `wallaby.projectCacheDir`.

**Comment by jljorgenson18** [comment]
Right, I discovered that today. The prosemirror directory contains prosemirror modules as Git submodules and are just straight pulls from the origin repository. Because of that, the problems I had are due to compilation and problems with nested node_modules. I don't think there is much Wallaby can do right now until we figure out what the desired compilation is supposed to be.
