### ISSUE TITLE
Jasmine beforeEach() + functions returning promises

### ISSUE THREAD

**Issue by einari** [wallabyjs/public#166]
Hi,
I'm using Babel + JSPM and have run into a bit of a weird one. 

My system under test has a function that I call that returns a Promise. 
In my test I do the following:

```
beforeEach(() => {
    var query_coordinator = new QueryCoordinator(query_hub_mock);
    var promise = query_coordinator.execute(query, 1, 2);
    promise.then((result) => {
         query_result = result;
    });
});
```

The inner then() resolve callback is not getting called. If I drop the beforeEach() and pull the inner function outside, it works fine.

**Comment by ArtemGovorov** [comment]
@einari Are you using Mocha or Jasmine?
Either way, you're using sync version of `beforeEach`, so executes and promise then callback may never be invoked. Try the async version:
``` JavaScript
beforeEach(done => {
    var query_coordinator = new QueryCoordinator(query_hub_mock);
    var promise = query_coordinator.execute(query, 1, 2);
    promise.then((result) => {
         query_result = result;
         done();
    });
});
```

**Comment by einari** [comment]
Excellent @ArtemGovorov - Thanks!  I'm using Jasmine, that did the trick!  

Great support for a great tool, loving it, keep up the great work!

**Comment by ArtemGovorov** [comment]
@einari Awesome, thank you!
