### ISSUE TITLE
Can't load CSJ modules with esm

### ISSUE THREAD

**Issue by cwp** [wallabyjs/public#1661]
### Issue description or question
I'm trying to use ES 6 modules in node. They work great with --experimental-modules. I'm using `rollup` to bundle them for older node versions, and `esm` to run mocha tests. I've done pretty much what's described here: https://github.com/wallabyjs/wallaby-std-esm, but I can't seem to get it to work in Wallaby. It loads .mjs files fine, but it can't load CJS that are installed in node_modules with npm.

When I start wallaby I get this in the console:

```
[Error] Runtime error: file://./src/client.mjs:1​​
​​[Error] Error [ERR_MODULE_RESOLUTION_LEGACY]: pg not found by import in ./src. Legacy behavior in require() would have found it at /Users/colin/Better/dev/bluefin/node_modules/pg/lib/index.js​​
​​[Error]     at file://./src/client.mjs:1​​
​​[Error]     at Object.<anonymous> (file://./src/client.mjs:1)​​
​​[Error]     at Object.<anonymous> (file://./test/cluster.js:1)​​
​​[Error]     at Object.<anonymous> (file://./test/cluster.js:1)​​
​​[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)​​
```
### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
  process.env.NODE_PATH = require('path').join(wallaby.localProjectDir, 'node_modules')
  return {
    files: ['src/*.mjs'],
    tests: ['test/*.js'],
    debug: true,
    testFramework: 'mocha',
    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: `-r ${require.resolve('esm')} -r ${require.resolve('must')}`
      }
    }
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

macOS 10.12.6

**Comment by ArtemGovorov** [comment]
Could you please share a sample repo with a simple test where mocha can run tests with `esm` and wallaby can not? We are happy to have a look and sort it out.

**Comment by ArtemGovorov** [comment]
Actually we have managed to reproduce the issue.

Due to some current limitations of `.mjs` file loading/caching in node.js, wallaby can only work with `.mjs` files as if they were `.js` files. So until the native esm loader in node is fully implemented (and exposes some ways to specify module folders and manage its cache), you may use the following solution in your wallaby config:

```diff
module.exports = wallaby => {
  ...
  return {
    ...
    params: {
      runner: `-r ${require.resolve('esm')}`
    }
+   preprocessors: { '**/*.mjs': file => file.changeExt('js').content }
  }
}
```

**Comment by cwp** [comment]
Ok, this works, thanks!

Note to those who encounter a similar issue: make sure the preprocessors property in the root object and not the `env` object as presented above.

**Comment by ArtemGovorov** [comment]
> but it causes an error trying to resolve a module with a relative file path.

I think it is because your wallaby config only includes `*.mjs` files. This should help:

```diff
module.exports = wallaby => {
  ...
  return {
      files: [
        'src/*.mjs', 
+       'src/*.js'
      ],
    ...
  }
}
```

This + the preprocessor should get it working for you.

**Comment by cwp** [comment]
Now it works. Thanks!
