### ISSUE TITLE
using jest with angular and getting The string did not match the expected pattern.​​

### ISSUE THREAD

**Issue by bayterry** [wallabyjs/public#1662]
### Issue description or question
I started using jest with Angular v6. I created a test for the component and getting the error: "The string did not match the expected pattern.​​" on wallaby but not when I run the tests using pm. 

### Wallaby.js configuration file

```javascript
const compilerOptions = Object.assign(
  require('./src/tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  return {
    files: [
      'src/setupJest.ts',
      'src/jestGlobalMocks.ts',
      'jest.config.js',
      'src/**/*.+(ts|js|tsx|jsx|snap|css|svg|png|json)',
      '!src/**/*.test.+(ts|js)?(x)',
      '!src/registerServiceWorker.ts',
      'src/app/**/*.html',
      '!src/app/**/*.spec.ts',
      'src/**/*.json'
    ],

    tests: ['src/app/**/*.spec.ts'],

    testFramework: 'jest',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      type: 'node',
      params: 'node'
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX 10.13.4
Linux

**Comment by ArtemGovorov** [comment]
Could you please share a sample repo with a simple test demonstrating the issue? We are happy to take a look and help with the config.

**Comment by ArtemGovorov** [comment]
I have just hit the same issue while testing some other things and it looks like what's missing in your config is a preprocessor to transform template and style URL:

```js
const ngxWallabyJest = require('ngx-wallaby-jest');

module.exports = function (wallaby) {
    return {
        ...
        preprocessors: {
            // This translate templateUrl and styleUrls to the right implementation
            // For wallaby
            'src/**/*.component.ts': ngxWallabyJest,
        },
        ...
    };
};
```

You may take a look into this tutorial for an [example of a working configuration](https://blog.cloudboost.io/angular-jest-wallabyjs-why-it-is-the-ideal-combination-and-how-to-configure-b4cbe2eff4b3#a559).
