### ISSUE TITLE
node_modules outside of Wallaby root

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1663]
### Issue description or question
I am unsure how to correctly configure Wallaby for Jest snapshots that reference `node_modules`. Please advise.

Repo: [chrisblossom/backtrack-preset-preset/wallaby-issue](https://github.com/chrisblossom/backtrack-preset-preset/tree/wallaby-issue)

I think this is the same issue as #1565 and would be solved by #1571. 

### Wallaby.js configuration file

```javascript
'use strict';

const wallaby = (wallabyConfig) => {
    /**
     * Needed for monorepo
     */
    process.env.NODE_PATH = require('path').join(
        wallabyConfig.localProjectDir,
        '../../node_modules'
    );

    return {
        files: [
            { pattern: 'lib/files/*', instrument: false },
            { pattern: 'lib/files/.*', instrument: false },
            { pattern: '.*', instrument: false },
            { pattern: '*', instrument: false },
            { pattern: '.circleci/*', instrument: false },
            'lib/**/*.js',
            'jest.config.js',
            '.env',
            'lib/**/*.snap',
            '!lib/**/*.test.js',
        ],

        tests: ['lib/**/*.test.js'],

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (setupConfig) => {
            /**
             * Set to project local path so backtrack can correctly resolve modules
             * https://github.com/wallabyjs/public/issues/1552#issuecomment-372002860
             */
            process.chdir(setupConfig.localProjectDir);

            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            setupConfig.testFramework.configure(jestConfig);

            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             *
             * reset to expected wallaby process.cwd
             */
            process.chdir(setupConfig.projectCacheDir);
        },
    };
};

module.exports = wallaby;

```

### Code editor or IDE name and version

```
WebStorm 2018.1.3
Build #WS-181.4892.44, built on May 8, 2018
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### OS name and version

``macOS 10.13.3``

**Comment by ArtemGovorov** [comment]
It is indeed related to #1571, and we are still trying to find the best way to address it in wallaby core. However, we seem to have found a method that is working for now and is relatively easy to add to your config. The idea is to just symlink your project node modules from wallaby cache folder:

```diff
...

const wallaby = (wallabyConfig) => {
    ...

    return configManager({
        ...
        config: {
            ...

            setup: (setupConfig) => {
+                  const fs = require('fs');
+                  const path = require('path');
+                  const modulesLink = path.join(wallaby.projectCacheDir, 'node_modules');
+                  if (!fs.existsSync(modulesLink)) fs.symlinkSync(
+                    path.join(wallaby.localProjectDir, 'node_modules'),
+                    modulesLink,
+                    'dir');
                ...
            },
        },
    });
};

module.exports = wallaby;
```

This should get rid of the errors in the snapshot related to node_modules location.

However, I have noticed that there are still some differences in the snapshot in file hashes for wallaby file (that's probably expected because I changed it), and for 2 source files - again may be expected because the hash is calculated for instrumented copies that are running?

**Comment by chrisblossom** [comment]
@ArtemGovorov thank you! This will work until I use a lerna repo I think.

As for the hash mismatch, they are being instrumented. Not sure how to solve that, but (at the moment) it isn't a very big deal for that particular repo.

**Comment by ArtemGovorov** [comment]
Also `jest-serializer-path` is now using `process.cwd()`, as opposed to `__dirname`, so this issue is not related to https://github.com/wallabyjs/public/issues/1565#issuecomment-374427858 anymore. It's good to see they have fixed the module to be less dependent on where it's installed relatively to the project root.

**Comment by chrisblossom** [comment]
I actually put the [PR in to ``jest-serializer-path``](https://github.com/tribou/jest-serializer-path/commit/bfd59e5fc2e1d8b2b1a4f03fb166c2b4c44c85d0) fix the ``process.cwd()`` issue after you pointed that out.

> Because ./node_modules/@backtrack/core/dist/options-file/transform-config.js resolves file paths for some node modules and those node modules are located differently when running from Wallaby and when running from Jest (they would be no matter where Wallaby cache would reside).

Not sure this is would be the case because ``process.cwd()`` would be the same. But I definitely could be wrong here.

Thanks for the help!
