### ISSUE TITLE
TypeScript and RequireJS

### ISSUE THREAD

**Issue by BrianMcBrayer** [wallabyjs/public#167]
I'm testing wallabyjs for an internal project that uses TypeScript and RequireJS... specifically, we are using the `import bar = require('lib/bar');` functionality. I cannot find any example of wallabyjs supporting this kind of syntax, but I'm pretty sure it should work.

Normally I wouldn't ask for a demo, but I think that this is a common scenario that might help others.

It seems that, among other things, TypeScript will not output using 'amd' module format. However, even with that I am not sure it will just work.

Would it be possible to see a small working example of using TypeScript and RequireJS with wallabyjs?

Many thanks!

**Comment by ArtemGovorov** [comment]
@BrianMcBrayer Good point, thanks. I have added [the section in wallaby.js docs](http://wallabyjs.com/docs/integration/typescript.html#external-modules) describing how to configure TypeScript + AMD with Require.js. I have also created [this sample repository](https://github.com/wallabyjs/wallaby-typescript-requirejs/) with working configuration.

Please let me know if you hit any other issues when configuring wallaby.js for your project, I'm happy to help.

**Comment by BrianMcBrayer** [comment]
Wow--really fast response. Thank you so much! I think I should be able to get it working today!
