### ISSUE TITLE
Error while downloading wallaby.js version file

### ISSUE THREAD

**Issue by pjsvis** [wallabyjs/public#1670]
### Issue description or question
Error while downloading wallaby.js version file: getaddrinfo ENOTFOUND update.wallabyjs.com update.wallabyjs.com:80
NOTE: I am on enterprise network and npm install currently doesn't work for me.
I was able to licence quokka without any problems

### Wallaby.js configuration file
NONE

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

Windows 7 Version 6.1 Build 7601 Service Pack 1

**Comment by ArtemGovorov** [comment]
Quokka is shipped a bit differently. 
You'll need to get your support engineers to whitelist the URL the error is listing or [perform offline installation manually as described in our docs](https://wallabyjs.com/docs/intro/troubleshooting.html#offline-installation).
