### ISSUE TITLE
Feature Request: Add branch coverage

### ISSUE THREAD

**Issue by ThomasKlessen** [wallabyjs/public#1671]
If i use jest with `--coverage` i get for every file a branch coverage.
I think that this information is quite useful because it is possible to have 100% statement coverage but only 50% branch coverage.

It would be nice if i could see the branch coverage in the generated website as a new column after normal coverage.

![bildschirmfoto 2018-05-25 um 17 03 11](https://user-images.githubusercontent.com/25477157/40551913-89215248-603e-11e8-88ba-f6f77c9b2a3c.png)

 But even without this feature: Wallaby rocks! Really good work guys!

**Comment by ArtemGovorov** [comment]
Thanks for your feedback!

Wallaby is actually calculating statement+condition coverage (that is pretty much is branch coverage except for missing `else` cases). 

For example, wallaby will show the missing branches inside the following statements:

```js
var a = 1 || 1;

var b = 1 ? 1 : 1;

if(0 && 1) {
  //...
}
```

The only branch coverage case that is not supported by wallaby is the [missing `else` case](https://github.com/wallabyjs/public/issues/94), so if you don't mind I'll close this issue as a duplicate.

P.S. We find that statement+condition coverage is the most practical type of coverage to track/achieve, as it's not as loose as line/statement and yet not as demanding as full branch coverage. Having said that, we'd like to address the referenced feature request and add the full branch coverage support at some point, so please feel free to subscribe to the referenced issue.

**Comment by ThomasKlessen** [comment]
thx for the detailed feedback.
Of course it was the missing else case in my Example.
;o)

But i will subscribe and wait.

**Comment by congwenma** [comment]
Can wallaby display the actual missing branch in the file view?

**Comment by smcenlly** [comment]
@congwenma - in Wallaby app, uncovered branches are always highlighted in the file view (see screenshot below). In your editor, Wallaby has a command to toggle uncovered code regions. Please refer to [our tutorials](https://wallabyjs.com/docs/tutorial/overview.html) for your editor-specific instructions for displaying uncovered code regions.

![image](https://user-images.githubusercontent.com/2074089/80558453-c9a5ea80-8a1d-11ea-8470-7003f16af4f5.png)
