### ISSUE TITLE
Wallaby reports no failing tests, 0 passing. Can you confirm my wallaby.js file?

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#1672]
Hi,

I have been trying to get wallaby working with angular. I came upon a ngx-wallaby-jest package which is supposed to help.

One thing to note as that in webstorm i have a jest test runner setup and sure enough it reports around 4 tests passing and around 5 not.

But wallaby doesn't report any. Do you know what could be wrong with my wallaby file

Wallaby reports no failing tests, 0 passing. 

```
const ngxWallabyJest = require('ngx-wallaby-jest');

module.exports = function (wallaby) {
  return {
    files: [
      //Files used for testing
      {pattern: 'tsconfig.json', load: false},
      {pattern: 'jest.config.js', load: false},
      {pattern: 'src/setupJest.ts', load: false},
      {pattern: 'src/jestGlobalMocks.ts', load: false},
      {pattern: 'src/tsconfig.spec.json', load: false},
      {pattern: 'src/app/**/*.ts', load: false},
      {pattern: 'test/**/*.ts', load: false},
      {pattern: 'src/app/**/*.spec.ts', ignore: true},
      {pattern: 'src/app/**/*.d.ts', ignore: true},
    ],
    tests: ['src/app/**/*.spec.ts'],
    env: {
      //Jest tests runs on node, not on a browser!
      type: 'node',
      runner: 'node'
    },
    preprocessors: {
      // This translate templateUrl and styleUrls to the right implementation
      // For wallaby
      'src/**/*.component.ts': ngxWallabyJest,
    },
    testFramework: 'jest',
    bootstrap: function (wallaby) {
      //Use the configured jest file for testing
      const jestConfig = require('./jest.config.js');
      wallaby.testFramework.configure(jestConfig);
    },
    debug: true
  };
};

```

I have quite a large log file and i can see that there are tests failing there... and i also see this, so in the console there are tests failing just like inside the jest running in webstorm but something is weird.

, 27 May 2018 07:05:58 GMT wallaby:project Instrumenting src/app/layout/sidebar/sidebar.component.spec.js, via process pool: false
Sun, 27 May 2018 07:05:58 GMT wallaby:project Processing compiled src/app/login/login.component.spec.js
Sun, 27 May 2018 07:05:58 GMT wallaby:project Instrumenting src/app/login/login.component.spec.js, via process pool: false
Sun, 27 May 2018 07:05:59 GMT wallaby:processor No preprocessors found for src/setupJest.js
Sun, 27 May 2018 07:05:59 GMT wallaby:processor No preprocessors found for src/jestGlobalMocks.js
Sun, 27 May 2018 07:05:59 GMT wallaby:processor No preprocessors found for src/app/account/account.component.js
Sun, 27 May 2018 07:05:59 GMT wallaby:processor No preprocessors found for src/app/account/account.module.js
Sun, 27 May 2018 07:05:59 GMT wallaby:processor No preprocessors found for src/app/account/account.routing.js

**console.log: PASS src/app/account/account.component.spec.js

console.log: PASS src/app/layout/layout.module.spec.js

console.log: PASS src/app/login/login.component.spec.js

Sun, 27 May 2018 07:06:03 GMT wallaby:workers [l42jb] Run 0 test(s), skipped 0 test(s)
Sun, 27 May 2018 07:06:03 GMT wallaby:workers [l42jb] Sandbox is responsive, closing it**

console.log:   ● FooterComponent › should create

    Template parse errors:
    'mat-toolbar' is not a known element:
    1. If 'mat-toolbar' is an Angular component, then verify that it is part of this module.
    2. If 'mat-toolbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<mat-toolbar class="main-footer">
      <span>Some Company. Copyright @2018</span>
    </mat-toolbar>
    "): ng:///DynamicTestModule/FooterComponent.html@0:0

**Comment by ArtemGovorov** [comment]
We have just released a new version of [wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), that should address the issue. 

Please try the latest version and also the [config listed here](https://wallabyjs.com/docs/integration/angular.html#jest).

**Comment by appsolutegeek** [comment]
Nice! that worked... and no dependency ngx-wallaby-jest, I just got one question, 

Can you see my test below, the margin indicator is in a grey colour but its covered for the test so why is it not in green ?

![image](https://user-images.githubusercontent.com/2370364/40583714-400f1e08-6194-11e8-9eb9-42ebf4128b80.png)

**Comment by ArtemGovorov** [comment]
@appsolutegeek I don't see the full screen, but if you mean the `removeMeLater` method, then it doesn't look like it is covered. You are not calling the function, you are just checking that it exists on the `component` object.

**Comment by appsolutegeek** [comment]
Oops, yep, sorry, my bad. Thanks - all working now. Forgot the brackets.
