### ISSUE TITLE
Jest 23

### ISSUE THREAD

**Issue by jgoz** [wallabyjs/public#1675]
### Issue description or question

Jest v23 was [released recently](https://github.com/facebook/jest/blob/master/CHANGELOG.md#2300) (though an accompanying blog post has not been written, so maybe the release is not "official" yet). It appears that something changed in Jest's output that affects Wallaby. After upgrading to 23, Wallaby shows `0 failing tests, 0 passing`.

There are also new features that may affect Wallaby: [`describe.each`](https://facebook.github.io/jest/docs/en/api.html#describeeachtable-name-fn) and [`test.each`](https://facebook.github.io/jest/docs/en/api.html#testeachtable-name-fn). These allow specifying multiple test cases for a single test body.

### Wallaby.js configuration file

(not relevant)

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

OSX 10.13

**Comment by jgoz** [comment]
Actually, my wallaby core just updated (to v1.0.592) and it appears that everything now works with Jest 23. 🎉

**Comment by ArtemGovorov** [comment]
Yep, we have added Jest 23 support in 1.0.592 (released a couple of days before).
