### ISSUE TITLE
Basic declarations getting flagged as untested

### ISSUE THREAD

**Issue by bentedder** [wallabyjs/public#1676]
### Issue description or question

I have a basic const declaring an array that is showing up as untested in wallaby, and it's mostly just irritating me. Any ideas how I can make it pass the tests, or tweak some dials to make it ignore simple declarations?

```
export const COMPONENTS = [
  AppComponent,
];
```

**Comment by ArtemGovorov** [comment]
Could you please provide a bit more details:
- your wallaby config,
- what exactly do you mean by "is showing up as untested in wallaby"?

**Comment by bentedder** [comment]
Thanks for the response. My config seems pretty standard. What I mean is that I have a standard "route" array like this, that shows the white/grey box in VSCode and shows as a block of code that is not covered by tests. For now I've been adding `// ignore coverage` all over my app in areas where i have these types of array declarations. Can you think of another way to ignore them? Or do I have to write basic tests that somehow pull them in?
Thanks,


```
const routes: Routes = [
  {
    path: '',
    component: AnalyzeComponent,
  },
];

```

Here is my wallaby config:
```
files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'config/spec-bundle-wallaby.js', load: false, instrument: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/polyfills.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    hints: {
      ignoreCoverage: /ignore coverage/
    },

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      'src/**/*.ts*': wallaby.compilers.typeScript({
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
      })
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'phantomjs'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
```

**Comment by ArtemGovorov** [comment]
Ah, got it, thanks. So the file is not covered and you want to ignore it for code coverage reporting purposes? If that's the case, then the solution is simple - Wallaby config support [excluding certain files/patterns from code coverage reporting with the `filesWithNoCoverageCalculated` setting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file).
