### ISSUE TITLE
Wallaby app is hanging

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#1678]
### Issue description or question

Wallaby app is hanging. It was working perfect so far. Not sure how to debug, I need help. My repository is public: https://github.com/smarigowda/burger-builder-revision

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'config/**/*.js',
      '!src/**/*.test.js?(x)'
    ],

    tests: ['src/**/*.test.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({})
    },

    filesWithNoCoverageCalculated: [
      'src/registerServiceWorker.js',
      'src/index.js',
      'config/**/*.js'
    ],

    setup: function(wallaby) {
      const jestConfig = require('./package.json').jest;
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },
  
    hints: {
      ignoreCoverage: /ignore coverage/ // or /istanbul ignore next/, or any RegExp
    },
  
    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version
OSX, Mac OS Sierra 10.12.6

**Comment by smarigowda** [comment]
![image](https://user-images.githubusercontent.com/1831259/40700895-82958ba4-63d3-11e8-9abf-a36210b31783.png)

**Comment by ArtemGovorov** [comment]
Could you please try:
- opening the app in the Incognito window (to eliminate any caching issues),
- try opening the app via the local URL http://localhost:51245,
- share your browser version,
- open browser DevTools and share the Console output.

**Comment by smarigowda** [comment]
Thank you for the quick response. I figured out the issue. Charles proxy was running which was blocking the requests. It is working fine after closing the Charles proxy.
