### ISSUE TITLE
Angular CLI + jest + nrwl nx not working: zone is not defined

### ISSUE THREAD

**Issue by Silthus** [wallabyjs/public#1679]
### Issue description or question
I am trying to use wallaby with the Angular CLI and jest. I followed the setup, but I am getting an error `Zone is not defined`. I also tried using the webpack config for Angular CLI but then jest wont work since it needs to run in node.
### Wallaby.js configuration file

```javascript
const compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./tsconfig.spec.json').compilerOptions
);

module.exports = function (wallaby) {
  return {
    files: [
      'setupJest.ts',
      'jestGlobalMocks.ts',
      'jest.config.json',
      'apps/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'libs/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!apps/**/*.spec.ts',
      '!libs/**/*.spec.ts',
    ],

    tests: [
      'apps/**/*.spec.ts',
      'libs/**/*.spec.ts'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    preprocessors: {
      'apps/**/*.+(js|html)': file => require('jest-preset-angular/preprocessor').process(file.content, file.path, { globals: {} }),
      'libs/**/*.+(js|html)': file => require('jest-preset-angular/preprocessor').process(file.content, file.path, { globals: {} })
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

Windows 10 - 1803

**Comment by ArtemGovorov** [comment]
> getting an error `Zone is not defined`

This means that `jest-preset-angular` is not being imported/loaded.

Is your Jest config in the `jest.config.json` file? If it is the case, try [loading your Jest config explicitly](https://wallabyjs.com/docs/integration/jest.html#jest-configuration), it should help:

```diff
...

module.exports = function (wallaby) {
  return {
    ...
+    setup: function (wallaby) {
+      const jestConfig = require('./jest.config.json');
+      wallaby.testFramework.configure(jestConfig);
+    }
  };
};
```

**Comment by Silthus** [comment]
That worked!

Thanks for the quick answer.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

BTW, we have added the support for `jest.config.json` by default, so in the [next version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) it should work for without the `setup` function.
