### ISSUE TITLE
Tests created with factories are not recognised

### ISSUE THREAD

**Issue by aaronmcadam** [wallabyjs/public#1682]
### Issue description or question

Hi there, I'm using a couple of libraries that generate tests for me:

* https://github.com/Roilan/redux-jest
* https://github.com/facebook/jscodeshift

The tests pass when running Jest directly myself.

However, Wallaby returns these kind of errors:

```js
​​[Error] Test without test file id, most likely the test did not run, OR the test/test body is in the file that is not in the `tests` list in the configuration file { testFileIdCanNotBeDetermined: 'fetchProjects',​​
```

### Test Examples

```js
import { actionTest } from 'redux-jest';
import * as actions from './actions';

actionTest(
  'fetchProjects',
  actions.fetchProjects,
  {},
  { type: 'FETCH_PROJECTS', payload: {} }
);
```

```js
import { defineTest } from 'jscodeshift/dist/testUtils';

defineTest(
  __dirname,
  'add-organisation-to-package-name',
  null,
  'add-organisation-to-package-name/add-organisation-to-package-name'
);
```

### Wallaby.js configuration file

```javascript
module.exports = function ConfigureWallaby(wallaby) {
  return {
    files: [
      '__mocks__/fileMock.js',
      'fixtures/**',
      'package.json',
      'packages/**',
      '!packages/**/dist/**',
      '!packages/**/*.test.js',
      '!packages/**/node_modules/**',
    ],

    tests: [
      'packages/**/*.test.js',
      '!packages/**/dist/**',
      '!packages/**/node_modules/**',
    ],

    testFramework: 'jest',

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    reportConsoleErrorAsError: true,
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby needs to be able to instrument test bodies (ie. `it(..., () => {...})`) to report tests and work correctly. 

If test factories were inside the project, it would work. However, in this case tests are generated inside `node_modules` (that aren't instrumented by default).

The only way to try making it work that I can think of, is including node_modules that are generating tests to the `files` list, so that they get instrumented. Depending on where the module is installed, it may look like:

```diff
files: [
+    'node_modules/redux-jest/**'
      ...
    ],
```

**Comment by aaronmcadam** [comment]
Thanks so much @ArtemGovorov, that worked! ❤️ 🎉

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
