### ISSUE TITLE
vscode configuration that will allow all of my tests to run instead of just affected test

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#1683]
### Issue description or question
Is there a vscode configuration that will allow all of my tests to run instead of just affected test?
### Wallaby.js configuration file
na
```javascript
// paste your config here
```

### Code editor or IDE name and version
vscode latest

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Yes, there is the [`runAllTestsInAffectedTestFile `](https://wallabyjs.com/docs/config/overview.html#running-all-tests-in-changed-or-affected-test-files) that may help.

**Comment by bj97301** [comment]
what about running all test in my project not just the file?

**Comment by ArtemGovorov** [comment]
This is not something that is supported at the moment. 

Could you please share your scenario, why do you need to run all tests if they are not affected?

**Comment by bj97301** [comment]
My integration test are very fast at the moment so I would like to run them as part of my TDD workflow but they never get triggered in wallaby.

**Comment by ArtemGovorov** [comment]
Are your integration tests in the `tests` list?

If your integration tests cause some (wallaby instrumented) source code of your app to trigger/run, then they should run on the code changes as well.

**Comment by bj97301** [comment]
Good question.  They are.  However, I would like them to run every time any of my code changes at all as they are able to fail when this happens.

**Comment by ArtemGovorov** [comment]
They should run every time any affected code changes (ie. when any code they trigger changes). For example, if you touch a source code file `a` that is somehow executed during execution of an integration test `a.integration`, then the `a.integration` test should run. The changes in `a` file will not trigger an integration test `b.integration`, if `b.integration` execution doesn't affect/run any code in the `a` file.

**Comment by bj97301** [comment]
Understood.  The problem is that my integration test are calling api endpoints and are in no way logically connected to the src that is changing so they only run if I change the integration test itself.

**Comment by ArtemGovorov** [comment]
If your integration tests are calling api endpoints outside of your source code, then how can the source code changes break those tests? In other words, what is the point of running tests that can not be broken by your source code changes?

**Comment by bj97301** [comment]
Good question. I have a node api. The integration tests are calling my node
api. The same api that I am making changes to.

**Comment by ArtemGovorov** [comment]
If the code that the API is calling is in the `src`, then it should be instrumented, so your integration tests should be connected (by wallaby) to your source code and should run on your source code changes.

**Comment by bj97301** [comment]
When I get in the office tomorrow I’ll see if I can show you with some code
snippets or an animated gif.

**Comment by bj97301** [comment]
humm... I think now is the time where I eat my words and admit that your right :)

But, how does it know to run the test?  It is in no way related to the endpoint that I changed.  Does it make a map of test that have failed in the past when pieces of code are changed?

**Comment by ArtemGovorov** [comment]
> But, how does it know to run the test? It is in no way related to the endpoint that I changed. Does it make a map of test that have failed in the past when pieces of code are changed?

There are a few things that we do: from some smart heuristics (like the one that you've mentioned), to mapping each line of source code to a test that invokes it.

However (putting heuristics aside), if a test is in no way related to some piece of code, it shouldn't really need to run when the code changes, should it?

**Comment by bj97301** [comment]
Good to know.

Was a bad word choice. It’s connected but not from any logical code paths.
