### ISSUE TITLE
Testing Angular 6 Libraries

### ISSUE THREAD

**Issue by GordonCumming** [wallabyjs/public#1687]
### Issue description or question
I am trying to use Wallaby.js to unit test Angular 6 libraries

### Wallaby.js configuration file
```js
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "my-new-lib": [
        "dist/my-new-lib"
      ]
    }
  }
}
```
### Code editor or IDE name and version
VS Code v1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please share some more details about what/how exactly it is not working for you, ie. what errors are you getting?

**Comment by GordonCumming** [comment]
When I created the project with a library - my-new-lib as in 
https://medium.com/@brenden.niedermeyer/angular-cli-libraries-79b0a32a1443
The app.component.spec.ts file performs unit tests via ng test and also shows some Wallaby.js squares (although they appear white) -  but  the counter-button.component.spec.ts does not show any wallaby squares nor is it unit tested with my ng test

**Comment by ArtemGovorov** [comment]
@GordonCumming Could you please share a sample repo demonstrating the issue? Happy to take a loom and help with the config.

**Comment by GordonCumming** [comment]
Will try and do it soon

**Comment by DynamiteTom** [comment]
Here is the zipped code for the app'n[
[comp-libs-with-cli-03June.zip](https://github.com/wallabyjs/public/files/2074255/comp-libs-with-cli-03June.zip)
]

**Comment by DynamiteTom** [comment]
Sorry I forgot to add the Wallaby.js files I'll do that now

**Comment by DynamiteTom** [comment]
Here is the code for the wallaby encoded Library project 
You should see the white squares instead of greens and reds 
[Uploading wallaby-libs-with-cli-03June.zip…]()

**Comment by ArtemGovorov** [comment]
Could you please re-upload the project? Your last post link just references the issue, not the uploaded zipped code.

**Comment by GordonCumming** [comment]
Sorry I can’t as I’m at work in a secure project
But all I added to the 1st zip file was the Wallaby.js tutorial for Angular – regarding  Angular/cli  code for webpack

add  wallaby.js in root |  add in src file wallabyTest.ts file and then
3 devDependencies in package.json
npm install wallaby-webpack angular2-template-loader electron --save-dev

Gordon

**Comment by ArtemGovorov** [comment]
Thanks, I think I understand what the issue is now.

Please take a look here: https://github.com/wallabyjs/ngCliWebpackSample/issues/32. 
- For an example of Wallaby setup where both app and library are tested with a single wallaby config, please [take a look into this comment](https://github.com/wallabyjs/ngCliWebpackSample/issues/32#issuecomment-392612879). Note that you'll obviously need to replace all instances of `my-lib` with your lib name in the config.
- For an example of Wallaby setup where the library is unit tested separately, take a look into [the repo from this comment](https://github.com/wallabyjs/ngCliWebpackSample/issues/32#issuecomment-392028758), here is the [working wallaby config](https://github.com/NickClark/ngCliWebpackSample/blob/master/projects/test-lib/wallaby.js).
