### ISSUE TITLE
Error in wallaby runner

### ISSUE THREAD

**Issue by cwp** [wallabyjs/public#1689]
### Issue description or question

Running tests produces many errors in the Wallaby.js console, and many tests marked failed. I don't think this is a problem with my set up. It started suddenly, in many projects simultaneously, but the tests all pass when run in a terminal. 

```
​​​​​[Info]​​​​​ Tue, 05 Jun 2018 18:10:23 GMT wallaby:workers Sandbox (active) [n0qe0] error: TypeError: Cannot read property 'type' of undefined
​​​​​[Info]​​​​​ Tue, 05 Jun 2018 18:10:23 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'type' of undefined, stack: TypeError: Cannot read property 'type' of undefined
​​​​​[Info]​​​​​     at r (/Users/colin/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/runners/node/ava@0.3.0/initializer.js:14:4278)
​​​​​[Info]​​​​​     at onAfterTest (/Users/colin/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/runners/node/ava@0.3.0/initializer.js:14:4937)
​​​​​[Info]​​​​​     at /Users/colin/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.86/wallaby/runners/node/ava@0.3.0/initializer.js:14:3273
​​​​​[Info]​​​​​     at <anonymous>
```
### Wallaby.js configuration file

All my projects are configured more-or-less like this. I'm using ava 0.25.0, the latest stable version. 

```javascript
const pkg = require('./package.json')

module.exports = wallaby => {
  return {
    files: pkg.ava.source,
    tests: pkg.ava.files,
    debug: true,
    delays: {
      run: 500,
    },
    testFramework: 'ava',
    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: `TZ=UTC;NODE_ENV=test`,
      },
    },
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.23.1

### OS name and version

macOS

**Comment by ArtemGovorov** [comment]
Thanks for providing the details, looks like a regression from the recently added `ava@1.0.0-beta.5.1` support. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by cwp** [comment]
Yup. It works now. Thanks!
