### ISSUE TITLE
Wallaby does not register calls to console.log when mocked with jest

### ISSUE THREAD

**Issue by FlemmingBehrend** [wallabyjs/public#1692]
### Issue description or question
I have forked [the jest example](https://github.com/FlemmingBehrend/wallaby-jest-sample) and updated the code with two console.log statements. When I mock it with jest and run the test with Wallaby it does not register any calls to the mock.

![2018-06-07 09_47_14-wallaby-jest-sample d__own_wallaby-issues_wallaby-jest-sample - ___tests___](https://user-images.githubusercontent.com/1967934/41085919-a5caead6-6a38-11e8-9606-f94341b9386f.jpg)

It works if I just run it with jest (npm test)

### Wallaby.js configuration file

```javascript
module.exports = function () {

  return {
    files: ['sum.js'],

    tests: ['__tests__/*.js'],

    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: '--harmony'
      }
    },

    testFramework: 'jest'

    //setup: function (wallaby) {
    //  wallaby.testFramework.configure({
    //    // https://facebook.github.io/jest/docs/api.html#config-options
    //  });
    //}
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v2018.1.4 build UI-181.5087.20

### OS name and version

Windows 10 build 16299

**Comment by ArtemGovorov** [comment]
Thanks for the report and the repo. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
