### ISSUE TITLE
Wallaby crashes trying to import *.less files from node_modules

### ISSUE THREAD

**Issue by Timebutt** [wallabyjs/public#1693]
### Issue description or question

I'm currently adding Wallaby.js to an existing Angular 6 CLI project, and stumble upon a list of the following errors:

```
​​@import (reference) "node_modules/sp-uikit/less/button";​​
​​@import (reference) 'node_modules/sp-uikit/style/atom/a-size';​​
​​^​​
​​Can't resolve './node_modules/sp-uikit/style/atom/a-size.less' in './src/common/containers/edit-app-details-modal'​​
​​      in ./src/common/containers/edit-app-details-modal/edit-app-details-modal.container.less (line 5, column 0)​​
​​    at runLoaders (/Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/webpack/lib/NormalModule.js:252:20)​​
​​    at /Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/loader-runner/lib/LoaderRunner.js:364:11​​
​​    at /Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/loader-runner/lib/LoaderRunner.js:230:18​​
​​    at context.callback (/Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/loader-runner/lib/LoaderRunner.js:111:13)​​
​​    at <anonymous>​​
​​Module build failed: ​​
```

sp-uikit is an npm package we use to ship a lot of components and styles in our different repositories. What do I change to our Wallaby configuration to make this work? I started our configuration (see below) from the Angular 2+ example repository and made some tweaks to it, seems like I'm missing one though.

Thanks!

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
    require('./tsconfig.json').compilerOptions,
    require('./src/tsconfig.spec.json').compilerOptions);
compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

    var webpackPostprocessor = wallabyWebpack({
        entryPatterns: [
          'src/wallabyTest.js',
          'src/**/*spec.js'
        ],
    
        module: {
          rules: [
            {test: /\.css$/, loader: ['raw-loader']},
            {test: /\.html$/, loader: 'raw-loader'},
            {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
            {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
            {test: /\.json$/, loader: 'json-loader'},
            {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
            {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
            {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
            {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
          ]
        },
    
        resolve: {
          extensions: ['.js', '.ts'],
          modules: [
            path.join(wallaby.projectCacheDir, 'src/app'),
            path.join(wallaby.projectCacheDir, 'src'),
            'node_modules'
          ]
        },
        node: {
          fs: 'empty',
          net: 'empty',
          tls: 'empty',
          dns: 'empty'
        }
      });

    return {
        debug: true,
        filesWithNoCoverageCalculated: [
            'src/dealrooms/dealrooms.document-events.ts',
            'src/**/*.builder.ts',
            'src/*.ts',
            'src/**/index.ts',
            'src/**/routes.ts',
            'src/bootstrap/*.ts',
            'src/statemanagement/*.ts',
            'src/**/customTypes/*.ts',
            'src/**/*.factory.ts',
            'src/**/*.ngfactory.ts'
        ],
        files: [
            {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
            {pattern: 'src/**/*.d.ts', ignore: true},
            {pattern: 'src/**/*spec.ts', ignore: true}
        ],
        tests: [
            {pattern: 'src/**/*.spec.ts', load: false},
            {pattern: 'node_modules/**/*.js', load: false, ignore: true, instrument: false}
        ],
        testFramework: 'jasmine',
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
        },
        middleware: function (app, express) {
            var path = require('path');
            app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
            app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
        },
        postprocessor: webpackPostprocessor,
        env: {
            kind: 'chrome'
        },
        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
};

```

### Code editor or IDE name and version

Visual Studio Code 1.24.0
wallaby-webpack 3.9.9

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. We have changed our sample to make it work, please [this change](https://github.com/wallabyjs/ngCliWebpackSample/commit/d32ead20dcf0b2052f542c85ad702c4a4477a3e0) and it should work for you.

```diff
-        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
+        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
```

**Comment by ArtemGovorov** [comment]
This should do the trick: https://github.com/wallabyjs/ngCliWebpackSample/commit/59d4b27a8da1558c343575e21d042ec48f954aa2 (also updated the sample in our docs).

**Comment by Timebutt** [comment]
Nice! It did indeed. I got Wallaby up and running, but I still have two issues remaining somehow. 
The first one has something to do with `./data/packed/latest.json`, but I don't have a file like this in my project at all.

I've Googled for a while, and found out it probably has something to do with the `moment-timezone` dependency I have in my project (latest version of 0.5.17). Have you ever seen something of the likes?

```
​​​​​[Info]​​​​​ Fri, 08 Jun 2018 07:38:53 GMT wallaby:workers Sandbox (active) [k0mx3] error: Uncaught Error: Cannot find module "./data/packed/latest.json"
​​[Error] Runtime error: Uncaught Error: Cannot find module "./data/packed/latest.json"​​
​​[Error] at http://localhost:59708/____wallaby-bundle.js?1528443529385&wallabyFileId=bundle:158754​​
​​​​​[Info]​​​​​ Fri, 08 Jun 2018 07:38:53 GMT wallaby:workers Failed to map the stack to user code, entry message: Uncaught Error: Cannot find module "./data/packed/latest.json", stack: Uncaught Error: Cannot find module "./data/packed/latest.json"
​​​​​[Info]​​​​​ at http://localhost:59708/____wallaby-bundle.js?1528443529385&wallabyFileId=bundle:158754
```

More info: I import this module in 4 different spec files in this way:

```
import * as moment from 'moment-timezone';
```

Second issue is a png that can't be loaded by Wallaby, which poses no problem for the CLI build (meaning the path to the file is correct).

```
[Info]​​​​​ Fri, 08 Jun 2018 07:38:53 GMT wallaby:workers Sandbox (active) [kv55v] error: Uncaught Error: Cannot find module "../../../images/logo.png"
​​[Error] Runtime error: Uncaught Error: Cannot find module "../../../images/logo.png"​​
​​[Error] at http://localhost:59708/____wallaby-bundle.js?1528443529385&wallabyFileId=bundle:3182​​
```

Seems like something is off with the png loader. The path to the file is `src/images/logo.png`, so nothing exotic like my first issue I guess.

This is the offending line of code in my component:

```
const logoUrl = require('../../../images/logo.png');
```

Thanks for your very responsive and thorough support: this is the biggest project my team has to be moved to Wallaby, will be a great addition!

**Comment by Timebutt** [comment]
I got my first problem partially fixed by installing `json-loader` as a devDependency. 
I figured it wasn't required, since your demo project didn't have it listed in its `package.json`.

After adding it, the following appeared however :/

```
[Error] ​​Postprocessor run failure: /Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/json-loader/index.js!/Users/nils.tijtgat/Showpad/Code/local-development/web-app-v2/node_modules/moment-timezone/data/packed/latest.json​​
[Error] ​​Cannot read property 'replace' of undefined​​
```

**Comment by ArtemGovorov** [comment]
> Cannot find module "./data/packed/latest.json"​​

Looks like you've found another issue in our sample config. `json-loader` is not required with the latest versions of webpack, so [can be removed](https://github.com/wallabyjs/ngCliWebpackSample/commit/c556b9e4eee03acd130b83bf82af97e1d65a9bc9) (both from your wallaby config and from `package.json` dependencies & your node_modules).

> Cannot find module "../../../images/logo.png"​​

Where is the `images` folder located, in the project's root folder? If so, then adding the folder to the `files` list should help:

```diff
    files: [
      ...
+     {pattern: 'images/**/*.png', load: false},
    ],
```

**Comment by Timebutt** [comment]
Alright, one step closer. I removed the `json-loader` everywhere and got rid of the first error.
New ones pop up however. First one is comparable with the very first issue I had importing `.less` files from `node_modules`. I tried the same fix, but that didn't work ...

```
[Info]​​​​​ Fri, 08 Jun 2018 08:51:57 GMT wallaby:workers Sandbox (active) [1skhe] error: Uncaught Error: Cannot find module "../../../../node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css"
​​[Error] Runtime error: Uncaught Error: Cannot find module "../../../../node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css"​​
​​[Error] at http://localhost:61527/____wallaby-bundle.js?1528447914128&wallabyFileId=bundle:151245​​
```

Here's the fix I tried, to no avail:

```
{test: /\.css$/, loaders: [{loader: 'raw-loader', options: {paths: [__dirname]}}]},
```

Second one is more exotic, what's going on here?
I looked through all the existing issues in this repository, couldn't find anything that resembles this. 

```
[Info]​​​​​ Fri, 08 Jun 2018 08:51:57 GMT wallaby:workers Sandbox (active) [efqna] error: Cannot read property 'queueRunner' of undefined
​​[Error] Runtime error: TypeError: Cannot read property 'queueRunner' of undefined​​
​​[Error]     at http://localhost:61527/____wallaby-bundle.js?1528447914128&wallabyFileId=bundle:182612:55​​
​​[Error]     at t.s.it [as __zone_symbol__it] (http://localhost:61527/__wallaby__/jasmine@2.1.3/configurator.js:14:2748)​​
​​[Error]     at t.jasmineEnv.(anonymous function) [as it] (http://localhost:61527/____wallaby-bundle.js?1528447914128&wallabyFileId=bundle:182520:38)​​
​​[Error]     at n (http://localhost:61527/__wallaby__/jasmine@2.8.0/framework.js:14:8649)​​
​​[Error]     at t.describe (http://localhost:61527/__wallaby__/jasmine@2.8.0/framework.js:14:13300)​​
​​[Error]     at t.s.describe (http://localhost:61527/__wallaby__/jasmine@2.1.3/configurator.js:14:1931)​​
​​[Error]     at t.jasmineEnv.(anonymous function) [as describe] (http://localhost:61527/____wallaby-bundle.js?1528447914128&wallabyFileId=bundle:182512:38)​​
​​[Error]     at describe (http://localhost:61527/__wallaby__/jasmine@2.8.0/framework.js:15:18662)​​
​​[Error]     at t.<anonymous> (http://localhost:61527/src/common/components/node/node.component.spec.js.wbp.js?1528447911775&wallabyFileId=875:9:19)​​
​​[Error]     at ZoneDelegate.invoke (http://localhost:61527/____wallaby-bundle.js?1528447914128&wallabyFileId=bundle:153747:26)​​
```

Seems I'm not running an out of the box project here ;)

**Comment by ArtemGovorov** [comment]
> First one is comparable with the very first issue I had importing .less files from node_modules. 

Could you please share some more details on how the `node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css` file is imported and from what type of file?

> Second one is more exotic, what's going on here?

The good thing is that it is the `Runtime error` (as opposed to build errors), so we are getting closer to running tests.

I'm not sure what can be causing it though. From the stack trace it looks like it is something in the `src/common/components/node/node.component.spec.ts` spec file. Is there something that the file is doing differently from other files, perhaps extending Jasmine in some way?

**Comment by Timebutt** [comment]
This is how I import the `node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css` file. It's being imported as a `styleUrl` in an Angular component.

```
styleUrls: [
        '../../../../node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css',
        './asset-viewer-wrapper.less'
    ],
```

Regarding the second problem: I just went through the test file to see if Jasmine is being extended in any way there, and couldn't find anything. This is how it currently looks when Wallaby is up:

<img width="777" alt="screen shot 2018-06-08 at 11 40 30" src="https://user-images.githubusercontent.com/10674081/41151377-da1f8eee-6b10-11e8-9f80-8fea475331a1.png">

I have found that commenting out that specific `describe` block of test code fixed the issue, so I'll dive into this and try and see what's causing this issue exactly!

**Comment by ArtemGovorov** [comment]
>  It's being imported as a `styleUrl` in an Angular component.
```
styleUrls: [
        '../../../../node_modules/@showpad/pdfjs-dist/web/pdf_viewer.css',
        './asset-viewer-wrapper.less'
    ],
```

if you are reporting it in a relative manner like this, then you'll need to add the CSS files from the module to wallaby:

```diff
  files: [
  ...
+ 'node_modules/@showpad/**/*.css'
  ]
```

Alternatively, you may try importing the files using absolute path: 

```
styleUrls: [
        '@showpad/pdfjs-dist/web/pdf_viewer.css',
```
 and in this case you should not need to add the module CSS files to the `files` list.

> Regarding the second problem

Ah, got it. Unfortunately this is the obscure error that Jasmine + Zone.js reports when there's an exception thrown during test declaration (outside of an `it`/`beforeEach`, in your case within `describe`). Try moving the code into the `it`/`beforeEach` to see what the real error is.
