### ISSUE TITLE
Multiple snapshot updates is awkward

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#1694]
### Issue description or question
When I'm using the Wallaby web application if I've got a few snapshots to update, the interface is incredibly frustrating. For example:

![image](https://user-images.githubusercontent.com/1374775/41111150-1d44de0c-6a73-11e8-9e11-55bb5b306aed.png)

If I have the group selected and click the "update snapshot" button, the first test snapshot is updated, and then the test is selected with a `pass` result. I then have to select the group again to update the next snapshot.

Note that the same is true if you select the tests individually (e.g. `correctly renders selected planet`), if I hit update snapshot and select the next failing test `correctly renders locked planet` then the right hand side of the app will revert to the previous test as soon as it passes. 

This just makes it hard to update a number of snapshots quickly via the UI. Could this be improved (at least at the group level)?

**Comment by ArtemGovorov** [comment]
> If I have the group selected and click the "update snapshot" button, the first test snapshot is updated, 

When a group is selected, all errors from all test are displayed, so clicking the first error update snapshot icon updates the first test snapshot. And when a test runs, Wallaby app automatically focuses it in the tree.

While the behaviour is expected, I can see how it's getting on your way in your case. To address the scenario, we have added `Update snapshot(s)` action right into the test tree:

<img width="580" alt="screen shot 2018-06-08 at 12 43 52 pm" src="https://user-images.githubusercontent.com/979966/41136686-b57ea7b4-6b1a-11e8-949d-9a82ce950590.png">

Now you can update snapshots individually from tree node icons, or update all snapshot of a test file at once using the same icon on the file level. Unfortunately, updating on a group level (`describe` level) is not something that Jest supports.

Hope it addresses your issues with the UI. Please let us know if we can further improve it.

**Comment by IPWright83** [comment]
@ArtemGovorov Awesome, that works well enough for me. Thanks :) Great turnaround speed!
