### ISSUE TITLE
Having problem with jest

### ISSUE THREAD

**Issue by WangZishi** [wallabyjs/public#1696]
### Issue description or question
Can not find any test when using wallaby with nestjs and jest

![image](https://user-images.githubusercontent.com/8288105/41153026-1f8a112a-6b48-11e8-9c5e-4920ed6b9eab.png)

But I can run the test with `jest`

![image](https://user-images.githubusercontent.com/8288105/41153234-b840be8c-6b48-11e8-8fe0-4a136e81720a.png)

Here is repo https://github.com/WangZishi/wallaby-nestjs

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            'tsconfig.json',
            'package.json',
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*spec.ts', ignore: true }
        ],
        tests: [
            { pattern: 'src/**/*spec.ts', load: false },
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        setup: function (wallaby) {
            const jestConfig = require('./package.json').jest;
            console.log(jestConfig);
            wallaby.testFramework.configure(jestConfig);
        },
        debug: true
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.24.0

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Your `tests` pattern is set to `load: false`, that is why your tests had not been loaded (the config must have been copied from webpack, where the setting is required because tests are loaded in browser separately). I have sent you a pull request with [the working config](https://github.com/WangZishi/wallaby-nestjs/pull/1).

**Comment by WangZishi** [comment]
Thank you for your quick reply!
It is worked using this config file.
