### ISSUE TITLE
Wallaby.js does not find my TypeScript / Webpack tests

### ISSUE THREAD

**Issue by mduu** [wallabyjs/public#1697]
### Issue description or question

I can't get WallabyJs get running with my project and need help - trying since hours and don't know back and forward anymore. My project uses

- React 16.3
- Redux 4
- TypeScript 2.8
- Webpack 4

Tests are written with Mocha and Chai. Test-Environment at the - I guess - will be electron but for now I can go with anything executing my tests.

Currently I get a webpack error because of missing "entry" configuration:

```
[Error] ​​Postprocessor run failure: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.​​
[Error] ​​ - configuration.entry should be one of these:​​
[Error] ​​   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function​​
[Error] ​​   -> The entry point(s) of the compilation.​​
[Error] ​​   Details:​​
[Error] ​​    * configuration.entry should not be empty.​​
[Error] ​​      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.​​
[Error] ​​    * configuration.entry should be a string.​​
[Error] ​​      -> An entry point without name. The string is resolved to a module which is loaded upon startup.​​
[Error] ​​    * configuration.entry should be an array:​​
[Error] ​​      [non-empty string]​​
[Error] ​​    * configuration.entry should be an instance of function​​
[Error] ​​      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.​​
```

The WallabyJs Webpack tutorial says we don't need output and the sample shows no 'entry' as well. I have a src/tests.ts file which would build up the require() statements but not sure if I need this at all (maybe as the 'entry')? Are the 'entry' generated by 'wallaby-webpack'?

What do I miss here?

### Wallaby.js configuration file

```javascript
// Wallaby.js configuration

var path = require('path');
var webpack = require('webpack');
var wallabyWebpack = require('wallaby-webpack');

var wallabyPostprocessor = wallabyWebpack({
    devtool: "source-map",
    resolve: {
        extensions: [".js", ".jsx", ".json"]
    },

    module: {
        rules: [
            {
              test: /\.less$/,
              use: ExtractTextPlugin.extract({
                use: [{
                  loader: "css-loader",
                  options: {
                    localIdentName: '[local]--[hash:5]',
                    sourceMap: true
                  }

                }, {
                  loader: "less-loader",
                  options: {
                    sourceMap: true
                  }
                }],
                fallback: "style-loader",
                publicPath: "../"
              }),
              exclude: "/node_modules/"
            },
            {
              test: /\.html$/,
              use: 'raw-loader'
            },
            {
              test: /\.jpe?g$|\.gif$|\.png$/i,
              loader: "file-loader?name=assets/img/[name].[ext]"
            },
            {
              test: /\.woff2?$|\.ttf$|\.eot$|\.svg$/,
              use: "file-loader?name=assets/[name].[ext]"
            }
        ]
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('development')
            }
        }),
        new webpack.NamedModulesPlugin()
     ]
});

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'src/**/*.ts', load: false },
        ],

        tests: [
            { pattern: 'tests/**/*Spec.ts', load: false }
        ],

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                "experimentalDecorators": true,
                "emitDecoratorMetadata": true
            })
        },

        postprocessor: wallabyPostprocessor,

        setup: function () {
            // required to trigger test loading
            window.__moduleBundler.loadTests();
        }
    };
};
```

### tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom"],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "exclude": [
    "dist/**",
    "./*.js",
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts"
  ]
}
```

### tests.ts

```javascript
import 'reflect-metadata';

const requireFileFn = require.context('.', true, /Spec\.tsx?$/);
const testFileNames = requireFileFn.keys();
for (const testFile of testFileNames) {
  requireFileFn(testFile);
}
```

### Code editor or IDE name and version

Visual Studio Code vLatest

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Just created a sample repo with your configs at https://github.com/ArtemGovorov/wallaby-1697 and a simple test, and it is working for me (only had to add the `ExtractTextPlugin` import as it is missing in your wallaby config). Please try cloning the repo to see if it's working for you. If it is, try adding the bits I'm missing to reproduce the issue (I'd start with checking used versions of webpack/wallaby-webpack).

> I have a src/tests.ts file which would build up the require() statements but not sure if I need this at all 

Nope, you don't need it. Your `tests` will act as entry points, `wallaby-webpack` takes care of that. However, I have noticed you have the `import 'reflect-metadata';` import that isn not specific to Karma (like the rest of your `tests.ts` file), so you may need it for wallaby as well. You may either refactor the common bit into a file of its own, or create a similar `wallabyTests.ts` file for wallaby with just that `reflect-metadata` import (*the rest of the code with test loading is Karma specific and not required for Wallaby*), and [add an `entryPatterns` setting to your wallaby config](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns) with `wallabyTests.js` (note that .js extension should be used for `entryPatterns`, according to the docs).

Note that the `entryPatterns` configuration bit is a next step and not related to the current issue that you're observing.

**Comment by mduu** [comment]
Thanks a lot. Cloned it and it works on my machine too. So now I try to figure out what the differences are. I'll get back to you as soon as I can figure it out.

EntryPatterns: Thanks for the pointer - will check this too after I got it work in general.

**Comment by mduu** [comment]
Cleaned my ``wallaby.js`` and tried breaking yours - without success yet. What I see in mine in the "Wallaby.js Tests" log is:

```
[Error] ​​Postprocessor run failure: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.​​
[Error] ​​ - configuration.entry should be one of these:​​
[Error] ​​   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function​​
[Error] ​​   -> The entry point(s) of the compilation.​​
[Error] ​​   Details:​​
[Error] ​​    * configuration.entry should not be empty.​​
[Error] ​​      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.​​
[Error] ​​    * configuration.entry should be a string.​​
[Error] ​​      -> An entry point without name. The string is resolved to a module which is loaded upon startup.​​
[Error] ​​    * configuration.entry should be an array:​​
[Error] ​​      [non-empty string]​​
[Error] ​​    * configuration.entry should be an instance of function​​
[Error] ​​      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.​​
```
I thought I don't need entry points as wallaby will add them. Correct? Why then this error?

In "Wallaby.js Console" log I always get:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.603
​​[Error] No files with tests found, check your tests list patterns.​​
```

I guess this is because webpack failed according to the above error.

**Comment by ArtemGovorov** [comment]
> I thought I don't need entry points as wallaby will add them. 

Correct.

> Why then this error?

I have no idea yet. As you may see, it works on a simple sample repo using Webpack 4. The error that you are getting is not coming from Wallaby, it is coming from Webpack. My only guess would be that maybe you are using some old `wallaby-webpack` package version. What does running `npm ls wallaby-webpack` in your repo return?

**Comment by ArtemGovorov** [comment]
Also what is your Wallaby Core version (printed in the Wallaby.js Console when wallaby starts)?

**Comment by mduu** [comment]
I'm using yarn instead of NPM so there is no ``package.config.lock`` file but a ``yarn.lock`` file. May this be a problem for ``wallaby-webpack``?

Versions I use (I cleared my ``node_modules`` to ensure):
- wallaby-webpack@3.9.9
- webpack@4.12.0
- typescript@2.9.1
- Wallaby.js Core v1.0.603

I think these are all the latest stuff. Right?

**Comment by mduu** [comment]
Thinking: what could happen that ``wallaby-webpack`` would not generate or include webpacks ``entry`` configurations?

**Comment by mduu** [comment]
Oh, wait. I just figured that my tests where in ``src/tests`` and not ``./tests/``. Now Wallaby starts (but tests are failing). Anyway: I'm now one step further! Sorry about this one.

**Comment by mduu** [comment]
Me again. Now I can't get the ``import`` statements work in wallaby. Not only the one to my own code (which is to be tested by the test) but also not ``node_modules`` like "Chai" or *Ajv* etc.  I've sent you a [little pull request](https://github.com/ArtemGovorov/wallaby-1697/pull/1) for your sample which should show the problem I have.

I guess its a configuration thing. Not sure if this is the wallaby-entry-pattern- or a webpack-config issue?
