### ISSUE TITLE
Allow preprocessors to return a Readable stream or promise

### ISSUE THREAD

**Issue by jeffling** [wallabyjs/public#17]
If we can return some sort of object, we don't have to worry about our preprocessors being synchronous, and we could probably reuse a lot of gulp plugins with very little work. Maybe we can already, but I'm missing something obvious? :)

**Comment by ArtemGovorov** [comment]
Preprocessors can be async, the just have to take 2 arguments and the second argument is the callback to invoke when done.

```javascript
'**/*.js': (file, done) => done(file.content + '// modified')
```

**Comment by jeffling** [comment]
Awesome, that's all I need to get webpack working probably. Thanks.

**Comment by ArtemGovorov** [comment]
Cool, please let me know if you get webpack working - I'll put it in the documentation.
