### ISSUE TITLE
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

### ISSUE THREAD

**Issue by subblue** [wallabyjs/public#1700]
### Issue description or question
Recently I've started getting this error when running the tests in wallaby.js (used to work fine with wallaby and still all works when run directly with Mocha)

```
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
       at module.exports (/Users/xxx/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
       at HTMLCanvasElementImpl.getContext (/Users/xxx/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
       at HTMLCanvasElement.getContext (/Users/xxx/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:50:45)
```

Needless to say that `canvas` is installed as a dev dependency (also tried `canvas-prebuilt`)   
Also tried clean install of node modules, latest version of JSDOM (v11.11.0) and am using Node v10.1 etc.   
The main thing is that it all works fine from the command line with Mocha so it seems to be something specific to the wallaby config.

### Wallaby.js configuration file

Wallaby.js App v1.0.40, Core v1.0.603

```javascript
module.exports = function (wallaby) {
  return {
    files: ['src/**/*.js*', '!src/**/__tests__/*-test.js', '!src/images/*'],

    tests: ['src/**/__tests__/*-test.js'],

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

    env: {
      type: 'node',

      params: {
        env: 'LOCAL_PATH=' + process.cwd()
      }
    },

    testFramework: 'mocha',

    delays: {
      run: 1000
    },

    setup: function () {
      require.extensions['.jsx'] = require.extensions['.js']
      require('./src/__tests__/setup')
      require('./src/__tests__/helpers')
      require('babel-register')({
        ignore: /node_modules\/(?!@hypd|quill)/
      })
    }
  }
}

```

### Code editor or IDE name and version
Visual Studio Code v1.25

### OS name and version
OSX 10.13.5

**Comment by ArtemGovorov** [comment]
I'm trying to reproduce the issue, but need some more details. Could you please share:
- your `package.json` `dependencies`&`devDependencies` properties,
- `src/__tests__/setup.js` and `src/__tests__/helpers` code,
- an example of test/code that triggers the error,
- your current `test` command from your package.json (where mocha is configured).

**Comment by ArtemGovorov** [comment]
I have created this simple repo with your config https://github.com/ArtemGovorov/wallaby-1700, and the simple test is working. Could you please clone the repo, run `npm i` and run wallaby to see if it's working for you? If it is, please add the bits I'm missing to reproduce the issue.

Some things I'd start adding/checking would be:

- your `package.json` `dependencies`&`devDependencies` properties,
- `src/__tests__/setup.js` and `src/__tests__/helpers` code,
- an example of test/code that triggers the error,
- your current `test` command from your package.json (where mocha is configured).

**Comment by subblue** [comment]
Thanks for putting together the test repo - that actually worked fine for me too.

In the end I've managed to fix the issue by specifying the version of node wallaby should use via:

```
...
runner: require('os').homedir() + '/.nvm/versions/node/v10.1.0/bin/node'
...
```

Not the most elegant solution, but our team all has the same nvm config, so it works for now. 
It there a neater, more robust way of specifying the version of node it should use?

**Comment by ArtemGovorov** [comment]
You may specify node version in [VS Code settings](https://wallabyjs.com/docs/intro/install.html#nodejs-1), but it looks like you and your team are using a specific node version (that is not the same as your default `node` version), in which case your solution is the best I can think of. You could also use `NVM_DIR`:

```
// but I'm guessing 10.1.0 is not your current version, otherwise just `node` would be enough
runner: require('path').resolve(process.env.NVM_DIR + '/current/bin/node')
// 
runner: require('path').resolve(process.env.NVM_DIR + '/versions/node/v10.1.0/bin/node')
```

You mentioned that mocha is running fine, are your switching node version for it as well?

**Comment by subblue** [comment]
Ahh yes, that makes sense now.

Our default node is still v8.4 but for this project we recently switched to v10.1. However, we use a script to automatically change NVM node versions when entering the project folder in the terminal - hence the version mismatch.

Thanks for your help resolving this - your support for wallaby.js users continues to be great!
