### ISSUE TITLE
wallaby.js just stops with `Wallaby.js stopped`

### ISSUE THREAD

**Issue by macrozone** [wallabyjs/public#1701]
i am using Visual Studio Code and wallaby without a licence (yet).

after staging wallaby it eventuelly stops with `Wallaby.js stopped` and without any more detail.

**Comment by ArtemGovorov** [comment]
Stopping is expected in trial mode (without a license), it is the trial mode limitation - you need to restart your editor to get another trial session. There should be a notification from VS Code, warning that wallaby is about to stop.

If you'd like to arrange a trial period without prompts and restarts, please send us an email to hello@wallabyjs.com, and we'll arrange it for you.

**Comment by macrozone** [comment]
@ArtemGovorov I could not find any information, but that the trial period is 30 days (http://disq.us/p/175cdgm) 

So i would expect to be able to use wallaby within 30 days without any other limitations. I could not find any mention of any limitation of the trial version. Also the log in vscode does not mention that it is stopped because of the trial licence.

So I had the impression that wallaby does not work properly and therefor would not buy a licence. That is totally against the idea of a trial period. You would have lost me as a user...

I would advice to _at least_ notify in the log that it has been stopped because of the trial licence or put that limitation that prominent somewhere on the webpage. Even better: just let users use it for 30 days without more limitation. It doesn't make any sense to have both limitations in place.

**Comment by ArtemGovorov** [comment]
Thanks for your feedback.

Right in the same paragraph on the [download page](https://wallabyjs.com/download/) where it is stated about the 30 days trial, it mentions the other limitation of the trial: 

`
Note that in the trial mode wallaby will sometimes prompt you to restart your editor to get another trial session. Please contact us if you would like to arrange a trial period for yourself or your team without activation prompts and restarts.
`

> I would advice to at least notify in the log that it has been stopped because of the trial licence or put that limitation prominently somewhere on the webpage. 

We do exactly that. When Wallaby is about to stop, it notifies the user about it using VS Code notifications and/or Wallaby.js Tests output channel. Any chance you have the VS Code notifications muted somehow or maybe you haven't checked Wallaby.js Tests output channel? When Wallaby stops, what is displayed in your `Wallaby.js Tests` output channel? (`Wallaby.js stopped` is from Wallaby.js Console output channel).

> Even better: just let users use it for 30 days without more limitation. It doesn't make any sense to have both limitations in place.

We do it too by a simple email request. Please send us an email to hello@wallabyjs.com, and we'll arrange a trial license key that will work as you are expecting.

**Comment by beelio** [comment]
As it is right now i'ts a bit unclear that this limitation exists in the trial version.

I was almost considering to not buy a license as it made me feel that the extension was to unstable.

So you should probably try to make it more clear that auto stopping is a natural part of the trial version 👍
