### ISSUE TITLE
Angular 6: All Unit test passed with Wallaby but using npm test failed.

### ISSUE THREAD

**Issue by blopez2010** [wallabyjs/public#1702]
### Issue description or question
All my unit tests passed according to WallabyJs but if I run `npm test` some of them failed.

`"test": "./node_modules/.bin/ng test --browsers=ChromeHeadless --code-coverage=true --watch=false"`

![image](https://user-images.githubusercontent.com/15872584/41246743-3eaf0506-6d69-11e8-9b06-08dbfbaede2c.png)

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.24.0

### OS name and version

macOS High Sierra Version 10.13.4

**Comment by ArtemGovorov** [comment]
Are you expecting the test to fail or to pass?

**Comment by blopez2010** [comment]
According to the image, if the test is failing with `npm test` I would expect it fails with WallabyJs since the one we are using for CI for deployment validation is `npm test` otherwise I would think WallabyJs is cheating me.

**Comment by ArtemGovorov** [comment]
What I'm trying to say is that it may be an issue with Karma/CI setup, and not with Wallaby. It's not really clear what the error is from Karma output, so that's why I'm asking if the test is supposed to fail or not given it's current code/state?

**Comment by blopez2010** [comment]
I see what you meant, It's supposed to pass given the current state. What are your suggestions to check on Karma setup?

**Comment by blopez2010** [comment]
Actually looking at this unit test in the image, the code is supposed to pass and according to `npm test` it pass, but WallabyJs is throwing a weird error.

![image](https://user-images.githubusercontent.com/15872584/41264962-f6a806f6-6dac-11e8-8eb5-228dbb7615b9.png)

**Comment by ArtemGovorov** [comment]
Looks like you are getting the same error in Karma - `[object ErrorEvent]` for the originally reported test. Looks to me like the error is consistent between Karma and Wallaby, and it may be happening not during a test, but after a test, or something similar, that is why Karma and Wallaby are attributing the error to different tests.

Either way, the error doesn't look Wallaby specific, as the same happens in Karma. Having said that, we are happy to investigate what's going on, but will need a repro. Please set up a sam[le repo demonstrating the issue and we'll jump in to take a look.

**Comment by blopez2010** [comment]
I have tried to make a sample trying to demonstrate the issue but it is very specific with the project though 😞so I don't have any idea how to do it.

**Comment by ArtemGovorov** [comment]
I understand your frustration, but unfortunately we can't possibly guess what's going on. Especially given that the error is not wallaby specific/related, and the same happens in Karma.

If you'd like to start investigating yourself on what's going on with your Karma test run and fix it, then the error should disappear in Wallaby too.

If you'd like us to be able help, then a sample is required. I'd suggest by starting with adding the `//file.only` attribute to the test file. It'll make wallaby to only run this test file, and check if the error is still reproduced. If not, it may be an issue with interdependent tests.

If the error is still reproduced, then, I'd comment out all other tests from the file. If the error is not reproduced anymore, then it may be an issue with interdependent tests within this test file.

**Comment by blopez2010** [comment]
@ArtemGovorov thanks for the feedback and comments, what I noticed after some research is typescript change the way some of the unit tests are accepted or not, we have made an upgrade from Angular 5 to 6 version so that makes some unit tests stop working, after some research on coding I noticed some errors that I have made after coding (that's why unit tests are too :) ) that weren't accepted by wallaby, for example: Look at the image in the comment https://github.com/wallabyjs/public/issues/1702#issuecomment-396436598, I've been throwing an error, in line number 169 I'm checking if `res` is null, but it will never being called since it will be an error. Wallaby show it as an error but, `npm test` test passed. haha weird I think, some other examples where Wallaby passed the test and `npm test` doesn't applies same rule, type checking fixes everything, last one is the most worry thing I think since I thing Wallaby is cheating me...

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update, glad to hear it's sorted. 

>  type checking fixes everything

Out of interest, could you please share some more details about it? May be helpful to other users.
