### ISSUE TITLE
Very first time wallaby runs, `self` in tests is empty object `{}` instead of pointing to `window`

### ISSUE THREAD

**Issue by git-jiby-me** [wallabyjs/public#1704]
### Issue description or question

This only happens on the very first run, if some tests changes, and tests re-run then everything works and `self` points to `window`

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'plugins/Q_sessionrecorder/**/*.js', load: false },
            { pattern: 'plugins/D_sessionrecorderworker/**/*.js', load: false },
            { pattern: '!plugins/Q_sessionrecorder/_old/**/*.js', load: false },
            { pattern: '!**/*.spec.js', load: false }
        ],
        tests: [
            { pattern: 'plugins/Q_sessionrecorder/**/*.spec.js', load: false },
            { pattern: 'plugins/D_sessionrecorderworker/**/*.spec.js', load: false },
            { pattern: '!plugins/Q_sessionrecorder/_old/**/*.spec.js', load: false }
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                plugins: [
                    'add-module-exports',
                    'transform-es2015-modules-commonjs',
                    'transform-async-to-generator'
                ]
            })
        },
        postprocessor: require('wallabify-proxyquire-postprocessor')({
                debug: true,
                plugin: ['proxyquireify/plugin']
            },
            ['proxyquire']
        ),

        setup: function () {
            window.testFrameworkBasePath = '/';
            window.__moduleBundler.loadTests();
        },
        env: {
            kind: 'electron'
        },
        testFramework: 'jasmine'
    };
};

```

### Code editor or IDE name and version

IntelliJ IDEA v2018.1.4

### OS name and version

macOS High Sierra

**Comment by git-jiby-me** [comment]
Well correction, it's not always the very first start, it seems sometimes `self` points to `window` and sometimes to `{}`.

Does not happen when tests are directly run from `karma`

**Comment by git-jiby-me** [comment]
@ArtemGovorov okay `//file.only` makes it work, so i guess its as your assumption that some other test or modules modify `window.self`.This would also explain why it only fails on first run, as with test edit, only the modified tests run.

I will check the other tests, modules to try to find the root cause, thanks for the quick response.

**Comment by git-jiby-me** [comment]
@ArtemGovorov that was it, there was another test that was modifying `window.self`. Thanks for the help 👍 and btw very helpful tool, improves my workflow very much.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
