### ISSUE TITLE
Wallaby green coverage indicator not showing up

### ISSUE THREAD

**Issue by khuynh92** [wallabyjs/public#1705]
### Issue description or question
Currently my green coverage indicators are not appearing, in VS Code. the red, orange, and gray indicators still appear, but when tests are covered and pass, green will disappear.

### Wallaby.js configuration file
----------------------------------------
module.exports = function () {
  return {
    files: [
      'arrays/**/*.js',
      '!arrays/**/*.spec.js',
      'linked-lists/**/*.js',
      '!linked-lists/**/*.spec.js',
    ],

    tests: [
      'arrays/**/*.spec.js',
      'linked-lists/**/*.spec.js',  
    ],

    testFramework: 'jest',
    env: {
      type: 'node',
    },
  };
};
----------------------------------------

### Code editor or IDE name and version

Visual Studio Code 1.24.0

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
One of our users had the same issue recently. Looks like your Wallaby installation had been corrupted somehow, please follow the [steps described here](https://github.com/wallabyjs/public/issues/1690#issuecomment-394897705) to reinstall the extension, it should help.

**Comment by khuynh92** [comment]
Thank you! That fixed the issue
