### ISSUE TITLE
Unable to resolve own package within TypeScript Lerna Repo

### ISSUE THREAD

**Issue by Anupheaus** [wallabyjs/public#1708]
### Issue description or question
I am using Yarn with workspaces enabled, Lerna, TypeScript and React in this project.

I have looked at all the issues surrounding this topic in wallabyjs/public and I cannot find a solution that works.  I am using react but using enzyme for testing.  It is failing in my `setup.ts` on this line:
```TypeScript
import '@myapp/common';
```

Where Lerna has added `@myapp/packagename` to the node_modules folder at the root, so it should find it easily?

### Wallaby.js configuration file

```javascript
const path = require('path');

module.exports = function (wallaby) {
  process.env.NODE_PATH = (process.env.NODE_PATH || '') + path.delimiter + path.join(wallaby.projectCacheDir, 'packages');
  return {
    files: [
      { pattern: 'react', ignore: true },
      { pattern: 'react-dom', ignore: true },
      { pattern: 'packages/ui/src/**/*.tests.ts?(x)', ignore: true },
      { pattern: 'packages/ui/tests/environment.ts', load: false, instrument: false },
      { pattern: 'packages/ui/tests/setup.ts', load: false, instrument: false },
      { pattern: 'packages/*/src/**/*.ts?(x)', load: false },
    ],
    tests: [
      { pattern: './packages/ui/src/**/*.tests.ts?(x)' },
    ],
    testFramework: 'mocha',
    env: {
      type: 'node',
      runner: 'node',
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true,
    },
    setup() {
      require('./packages/ui/tests/setup');
    },
  };
}
```

### Code editor or IDE name and version

Visual Studio Code v1.24.0?

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.
You may find the solution here: https://github.com/wallabyjs/public/issues/1665#issuecomment-390366213. In your case it will look like:

```js
setup() {
  require('module-alias').addAliases({ '@myapp': w.projectCacheDir + '/packages' });
  ...
}
```

**Comment by Anupheaus** [comment]
This still doesn't exactly work, I have to change a file pattern to this:
```
{ pattern: 'packages/**/*.ts?(x)', load: false }
```
and add an `index.ts` file in the root of each package exporting everything from the `./src` folder to get this to work, or I would have to put the individual packages all explicitly in the `addAliases` method like so: `.addAliases({ '@myapp/common': w.projectCacheDir + '/packages/common/src' })`.

Any ideas on how to get the aliasing to work without having to explicitly set each alias or without having to add an index file in the package root folder please?

**Comment by ArtemGovorov** [comment]
This:

```js
setup() {
  require('module-alias').addAliases({ '@myapp': w.projectCacheDir + '/packages' });
  ...
}
```
should be enough. However, since you have `main` field pointing to `src` in your packages `package.json` files, you'll need to let Wallaby know about your `package.json` files (otherwise standard node resolution is used as if `package.json` was missing). So adding:

```js
{ pattern: 'packages/**/package.json', load: false },
```

should work for you.
