### ISSUE TITLE
Parallelism and MongoDB

### ISSUE THREAD

**Issue by arg20** [wallabyjs/public#171]
I'm using mongoose, and I have some tests aimed at making sure some of the middleware denormalizes documents properly or triggers certain actions and they are stored properly in mongodb. Because individual tests may affect the database, I run a `beforeEach` function that clears the collection (say `User.remove()`).

This works well when tests are run serially using mocha. Each test restores the collection to a given state before it begins, so tests don't affect each other. But when I use wallaby and tests run in parallel, a test could be restoring the collection while another test is expecting to see changes (and thus they fail).

I don't want to remove parallel behavior, but I'm uncertain as to how to tackle this problem. I was thinking that each process is given a uniq mongodb url on startup, so they work on different databases (maybe I could do this on the bootstrap function), but there is no destructor function to drop that database so I don't pollute mongodb. Any ideas?

**Comment by ArtemGovorov** [comment]
>  I was thinking that each process is given a uniq mongodb url on startup, so they work on different databases (maybe I could do this on the bootstrap function)

I suppose you could try it.

> but there is no destructor function to drop that database so I don't pollute mongodb.

You may use mocha built-in hooks to execute some code after all tests of a parallel worker has finished executing:

``` JavaScript
    bootstrap: function (wallaby) {
      var mocha = wallaby.testFramework;
      // DB setup code
      mocha.suite.afterAll(function () {
        console.log('afterAll', process.pid);
        // DB clean up code
      });
    }
```

> I don't want to remove parallel behavior

Are you experiencing significantly longer test execution time without the parallelism?
I'm assuming you've already found how to remove it, but just in case if you haven't - you may set [workers count to one](http://wallabyjs.com/docs/config/workers.html).
``` JavaScript
    workers: {
      initial: 1, regular: 1
    }
```

**Comment by ArtemGovorov** [comment]
Closing this for now, let me know if mocha built-in hooks worked for you.
