### ISSUE TITLE
Wallaby chrome app/page not loading

### ISSUE THREAD

**Issue by bentedder** [wallabyjs/public#1713]
### Issue description or question
When running the wallaby app from vscode (`Wallabyjs: Open Wallaby App`) to see test coverage in chrome, I get all kinds of 404s from what seems to be the wallabyjs.com website. I recently upgraded to angular 6, but changed nothing in my webpack or wallaby.js files.

![screenshot 2018-06-15 at 09 37 57 am](https://user-images.githubusercontent.com/1597375/41474008-78f2d73c-7080-11e8-884d-30a6464920ab.jpg)

Using chrome Version 67.0.3396.87 (Official Build) (64-bit)

Console is showing the follow error:
```
(index):1 GET http://wallabyjs.com/app/main.4b6e6b21ffc72ee011a4.css 404 (Not Found)
2(index):5 GET http://wallabyjs.com/app/main.4b6e6b21ffc72ee011a4.js 404 (Not Found)
vendor.31fadcd40eb6091fa9ce.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.31fadcd40eb6091fa9ce.js:1
(anonymous) @ vendor.31fadcd40eb6091fa9ce.js:1
assets.c41cbcf308633d0f0afb.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at assets.c41cbcf308633d0f0afb.js:1
(anonymous) @ assets.c41cbcf308633d0f0afb.js:1
(index):5 GET http://wallabyjs.com/app/main.4b6e6b21ffc72ee011a4.js 404 (Not Found)
```

### Code editor or IDE name and version
Visual Studio Code v1.24.1

### OS name and version
OSX High Sierra 10.13.5

wallaby config:
```
var webpack = require('webpack');
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');
var constants = require('./config/webpack.constants');
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;

module.exports = function (wallaby) {

  var baseUrl = constants.appPath + '/';
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'config/spec-bundle-wallaby.js',
      'src/**/*spec.js',
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: 'raw-loader'},
        {test: /\.html$/, loader: 'raw-loader'},
        {
          test: /\.ts$/,
          include: /node_modules/,
          use: [
            {
              loader: 'ts-loader',
              query: {
                sourceMap: false,
                inlineSourceMap: true,
                compilerOptions: {
                  removeComments: true
                }
              }
            },
            'angular2-template-loader'
          ]
        },
        {test: /\.js$/, loaders: ['babel-loader', 'angular2-template-loader'], exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'},
      ]
    },
    plugins: [
      new webpack.DefinePlugin({
        APP: {
          ENV: JSON.stringify(constants.ENV),
          AUTH_HEADER: JSON.stringify(constants.authHeader),
          BASE_URL: JSON.stringify(baseUrl)
        }
      }),

    ],

    resolve: {
      extensions: ['.js', '.ts', '.css', '.scss'],
      alias: {
        vars: path.resolve(__dirname, 'src/app/styles/vars.scss'),
        list: path.resolve(__dirname, 'src/app/styles/list.scss'),
      },
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'node_modules'),
        'node_modules'
      ]
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'config/spec-bundle-wallaby.js', load: false, instrument: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/polyfills.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],
    // filesWithNoCoverageCalculated: ['src/app/shared/charts/**/*.ts'],
    hints: {
      ignoreCoverage: /ignore coverage/
    },

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      'src/**/*.ts*': wallaby.compilers.typeScript({
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
      })
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'phantomjs'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
It looks like some browser caching issue. Please try to open wallaby app in an Chrome Incognito Window to see if it's working. If it is, try clearing the cache for the app, if not - let us know and we will take it from there.

**Comment by bentedder** [comment]
Just putting this here again. I used another browser (firefox) for a while and that worked great, but then all the sudden this morning that browser won't load the app. So now I'm in incognito mode, as that's the only way I can see the webapp. Hopefully incognito works from now on.

**Comment by ArtemGovorov** [comment]
@bentedder If it's working in incognito mode, it means that there's some issue with the main browser window caching of the page. Try clearing the cache for the page, it should help.

**Comment by bentedder** [comment]
Yeah I cleared cache, all local, session storage, cookies, everything in the browser that I could find to clear. No luck :/. No big deal though, incognito works well so far.

**Comment by ArtemGovorov** [comment]
@bentedder Could you please share the error that you are getting?

**Comment by bentedder** [comment]
I get 404s on the following files:
http://wallabyjs.com/app/main.4b6e6b21ffc72ee011a4.css
http://wallabyjs.com/app/manifest.b2fd2a9d1b86566441a1.js

I also get:
```
vendor.31fadcd40eb6091fa9ce.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at vendor.31fadcd40eb6091fa9ce.js:1
(anonymous) @ vendor.31fadcd40eb6091fa9ce.js:1
```
and

```
assets.c41cbcf308633d0f0afb.js:1 Uncaught ReferenceError: webpackJsonp is not defined
    at assets.c41cbcf308633d0f0afb.js:1
(anonymous) @ assets.c41cbcf308633d0f0afb.js:1
```

and finally (this one seems less important):
```
[Deprecation] Application Cache is deprecated in non-secure contexts, and will be restricted to secure contexts in M69, around September 2018. Please consider migrating your application to HTTPS, and eventually shifting over to Service Workers. See https://goo.gl/rStTGz for more details.
```

**Comment by Cerberus** [comment]
I got the same problem, It seem load some scripts from http://wallabyjs.com fail.
![app](https://user-images.githubusercontent.com/9087409/46917544-a9a50680-cff2-11e8-9418-28e246c78fd5.png)
Clear-cache did not help, but it works fine on incognito mode.
Browser: Chrome

**Comment by ArtemGovorov** [comment]
@bentedder @Cerberus Please try the following:

- open DevTools while on the Wallaby App Page,
- open Application tab,
- select `Application - Clear Storage` menu item on the left had side,
- click the `Clear Site` button,
- refresh the page.

<img width="593" alt="screen shot 2018-10-15 at 10 30 33 am" src="https://user-images.githubusercontent.com/979966/46924222-bf074880-d065-11e8-83d0-b6126bdec97d.png">

**Comment by Cerberus** [comment]
@ArtemGovorov Thx for your exhaustive steps.

I have tried this before and it did not work, but I've noticed clearing site data does not whole remove them at all.  (even check all checkbox, maybe Chrome bug)
However, I've solved by remove them on this url
chrome://settings/siteData
<img width="845" alt="ss" src="https://user-images.githubusercontent.com/9087409/46936611-123ec280-d089-11e8-8382-0343348908b1.png">
thx again : )

**Comment by bentedder** [comment]
yeah, that worked or me as well. Had to go into sitedata in firefox as well and clear it, and that seemed to work. Thanks for your help everybody. Weird that it caches it so hard.

**Comment by dainbrump** [comment]
Just an additional note. I had uBlock and Ghostery extensions running. Even though clearing the application cache worked and reloaded the page, I kept getting websocket errors. Disabling uBlock and Ghostery extensions for the site cleared all those.

**Comment by blopez2010** [comment]
I ran into the same issue today, yesterday was working as expected. I have removed the url from sites as @Cerberus described and it worked but, this is being logged in the console:

![image](https://user-images.githubusercontent.com/15872584/53426561-d0b21280-39ac-11e9-908e-5b6bec1121c3.png)

**Comment by smcenlly** [comment]
@blopez2010 - the error messages are expected. While Wallaby app is accessed via the internet, all of the test results are served from your local host (i.e. no data is ever transferred publicly). The errors that you see are Wallaby app attempting to connect to Wallaby on the list of ports that we use for transmitting to the Wallaby app. We'll investigate whether we can report these as info messages instead of errors.
