### ISSUE TITLE
Wallaby working with Aurelia, Typescript & RequireJS

### ISSUE THREAD

**Issue by vidaritos** [wallabyjs/public#1716]
### Issue description or question
Hi, I'm having difficulties getting Wallabyjs to work with an Aurelia-cli based project using Typescript & requireJS.

I have two test, both Karma and Wallaby will execute the first test just fine, but wallaby fails with the second test:
```javascript
import {App} from '../../src/app';
import {StageComponent} from 'aurelia-testing';
import {bootstrap} from 'aurelia-bootstrapper';

describe('the app', () => {
  it('says hello', () => {
    expect(new App().message).toBe('Hello World!');
  });
});

describe('MyComponent', () => {
  let component;

  beforeEach(() => {
    component = StageComponent
      .withResources('app')
      .inView('<app first-name.bind="firstName"></app>')
      .boundTo({ firstName: 'Bob' });
  });

  it('should render first name', (done) => {
    component.create(bootstrap).then(() => {
      
      const nameElement = document.querySelector('.firstName');
      console.log(nameElement);
      expect(nameElement.innerHTML).toBe('Bob');
      done();
    }).catch(e => { console.log(e.toString()) });
  });

  afterEach(() => {
    component.dispose();
  });
});
```
I have tried modifying the path argumentin the `withResources` function (relative path, absolute path, with and without leading slash) , but karma will not accept anytghing other than just `'app'`

<details> 
  <summary>Karma output:</summary>
<pre>
Starting 'karma'...
19 06 2018 15:12:49.269:INFO [karma]: Karma v2.0.3 server started at http://0.0.0.0:9876/
19 06 2018 15:12:49.270:INFO [launcher]: Launching browser Chrome with unlimited concurrency
19 06 2018 15:12:49.276:INFO [launcher]: Starting browser Chrome
19 06 2018 15:12:49.866:INFO [Chrome 67.0.3396 (Windows 10 0.0.0)]: Connected on socket fC45qWDRsgzjIdYEAAAA with id 9825390
LOG: <div class="firstName">Bob</div>
Chrome 67.0.3396 (Windows 10 0.0.0): Executed 2 of 2 SUCCESS (0.108 secs / 0.097 secs)
TOTAL: 2 SUCCESS
Finished 'karma'
</pre>
</details>

<details> 
  <summary>Wallaby.js Test output:</summary>
<pre>
1 failing test, 1 passing​​​​​
  ​​​​MyComponent should render first name​​​​ ​​​[5005 ms]​​​​
    ​​Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.​​
    ​​Error: Cannot call ComponentTester.dispose() before ComponentTester.create()​​
      at t.<anonymous> ​test/unit/app.spec.ts:33:4​
    ​​​​​From console:​​​​​
      ​​​​​{ [Error: Script error for "app"​​​​​
      ​​​​​http://requirejs.org/docs/errors.html#scripterror]​​​​​
      ​​​​​  requireType: 'scripterror',​​​​​
      ​​​​​  requireModules: [ 'app' ],​​​​​
      ​​​​​  originalError: Event { isTrusted: [Getter] } }​​​​​
      ​​​​​Error: Script error for "app"​​​​​
      ​​​​​http://requirejs.org/docs/errors.html#scripterror​​​​​
      at e.toString() ​test/unit/app.spec.ts:29:20​
</pre>
</details>

<details> 
  <summary>Wallaby.js Console output:</summary>
<pre>
[Error] Some long running code has been detected: test "should render label and slot" is taking more than 5000ms to execute.​​
​​[Error] The last recorded console.log: Error: Script error for "/src/resources/elements/category-box"​​
​​[Error] http://requirejs.org/docs/errors.html#scripterror​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] Sandbox is responsive. The issue may have the asynchronous nature, like a missing callback.​​
</pre>
</details>

Repo: https://github.com/vidaritos/aurelia-cli-ts-wllabyjs

### Wallaby.js configuration file

```javascript
/* eslint-env node  */
/* global requirejs */

module.exports = function () {


  var path = require('path');
  var aureliaJson = require('./aurelia_project/aurelia.json');

  return {

    debug: true,

    files: [
      { pattern: 'node_modules/bluebird/js/browser/bluebird.core.js', instrument: false },
      { pattern: 'node_modules/requirejs/require.js', instrument: false },
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'test/unit/setup.ts', load: false }
    ],

    tests: [
      { pattern: 'test/unit/**/*.spec.ts', load: false }
    ],

    env: {
      kind: 'electron'
    },

    middleware: function (app, express) {
      app.use('/node_modules',
        express.static(path.join(__dirname, 'node_modules')));
    },

    setup: (function (wallaby) {
      wallaby.delayStart();

      requirejs.config({
        packages: [
          // packages
        ]
      });

      require(['/test/unit/setup.js'].concat(wallaby.tests), function () {
        wallaby.start();
      });
    }).toString()
      .replace(
        '// packages',
        aureliaJson.build.bundles[1].dependencies.reduce(function (prev, curr) {
          var moduleName, modulePath, moduleMain;
          if (curr.path) {
            moduleName = moduleMain = curr.name;
            modulePath = path.relative(
              __dirname,
              path.resolve(__dirname, 'aurelia_project', curr.path))
              .split('\\').join('/');
            if (curr.main) {
              moduleMain = curr.main;
            }
          }
          else {
            moduleName = moduleMain = curr;
            modulePath = 'node_modules/' + moduleName + '/dist/amd';
          }
          return prev
            + '{ name: ' + JSON.stringify(moduleName)
            + ', location: ' + JSON.stringify(modulePath)
            + ', main: ' + JSON.stringify(moduleMain)
            + '},';
        }, ''))
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

Windows 10 64 Ent 1803

**Comment by ArtemGovorov** [comment]
> but karma will not accept anything other than just 'app'

Yes, and it is not looking great in tests, especially considering that it works with relative imports `import {App} from '../../src/app';` used in the same file. The `.withResources('app')` is accepted because Karma runs on a prebuilt bundle where `app` is defined in the root (`define('app', ...`). 

Anyway, you can let wallaby know to use `src` path when something is requested from the root via a [middleware function route](https://wallabyjs.com/docs/config/middleware.html).

I have sent you the [pull request with the working config](https://github.com/vidaritos/aurelia-cli-ts-wllabyjs/pull/1).

```js
/* eslint-env node  */
/* global requirejs */

module.exports = function (wallaby) {


  var path = require('path');
  var aureliaJson = require('./aurelia_project/aurelia.json');

  return {

    debug: true,

    files: [
      { pattern: 'node_modules/bluebird/js/browser/bluebird.core.js', instrument: false },
      { pattern: 'node_modules/requirejs/require.js', instrument: false },
      { pattern: 'src/**/*.+(ts|html)', load: false },
      { pattern: 'test/unit/setup.ts', load: false }
    ],

    tests: [
      { pattern: 'test/unit/**/*.spec.ts', load: false }
    ],

    env: {
      kind: 'electron'
    },

    middleware: function (app, express) {
      app.use('/node_modules', express.static(path.join(__dirname, 'node_modules')));
      app.use('/', express.static(path.join(wallaby.projectCacheDir, 'src')));
    },

    setup: (function (wallaby) {
      wallaby.delayStart();

      requirejs.config({
        packages: []
      });

      require(['/test/unit/setup.js'].concat(wallaby.tests), function () {
        wallaby.start();
      });
    }).toString()
      .replace(
        'packages: []',
        aureliaJson.build.bundles[1].dependencies.reduce(function (prev, curr) {
          var moduleName, modulePath, moduleMain;
          if (curr.path) {
            moduleName = moduleMain = curr.name;
            modulePath = path.relative(
              __dirname,
              path.resolve(__dirname, 'aurelia_project', curr.path))
              .split('\\').join('/');
            if (curr.main) {
              moduleMain = curr.main;
            }
          }
          else {
            moduleName = moduleMain = curr;
            var packageJson = require(moduleName + '/package.json');
            if (packageJson.jspm && packageJson.jspm.format === 'amd') {
              modulePath = 'node_modules/' + moduleName + '/' + packageJson.jspm.directories.dist;
            } else {
              modulePath = 'node_modules/' + moduleName;
              moduleMain = packageJson.main;
            }
          }
          return prev
            + '{ name: ' + JSON.stringify(moduleName)
            + ', location: ' + JSON.stringify(modulePath)
            + ', main: ' + JSON.stringify(moduleMain)
            + '},';
        }, 'packages: [') + ']')
  };
};
```

P.S. setting up Wallaby for Aurelia with require.js may get tricky. If you get stuck, I'd also recommend exploring [webpack powered wallaby config for Aurelia CLI](https://github.com/wallabyjs/public/issues/784#issuecomment-274394448) or even using Jest for testing Aurelia CLI apps (with or without wallaby).
