### ISSUE TITLE
Wallaby js config for create react app + eject

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#1717]
### Issue description or question

I am trying to configure wallaby for a create react app after ejecting. This is my repository. 

https://github.com/smarigowda/advanced-react-patterns-v2-with-wallaby

I am getting error when I run the wallaby. Could you please help.

​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.603
​​[Error] Runtime error: [31m[1m[1m● [1mValidation Error[22m:​​
​​[Error]   Module [1m./config/polyfills.js[22m in the [1msetupFiles[22m option was not found.​​
​​[Error]   [1mConfiguration Documentation:[22m​​
​​[Error]   https://facebook.github.io/jest/docs/configuration.html​​
​​[Error] [39m​​

### Wallaby.js configuration file

https://github.com/smarigowda/advanced-react-patterns-v2-with-wallaby/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
We have already helped you with a similar issue, you may find the solution here https://github.com/wallabyjs/public/issues/1616

**Comment by smarigowda** [comment]
Sorry, I should have looked at this before raising the request. Thank you very much for the help.
