### ISSUE TITLE
Wallaby VSCode Firewall

### ISSUE THREAD

**Issue by snehalp29** [wallabyjs/public#1718]
### Issue description or question
Trying to install Wallaby for VSCode behind firewall
### Wallaby.js configuration file
not sure whats the location of config file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.24.1
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows 7 Enterprise
OSX
Linux

**Comment by ArtemGovorov** [comment]
If you can't configure your firewall to let Wallaby install correctly, you may [use the offline installation procedure](https://wallabyjs.com/docs/intro/troubleshooting.html#offline-installation).

**Comment by snehalp29** [comment]
1)	Added "wallaby.noAutomaticInstall": true, to user settings
2)	install the latest VS Code extension WallabyJs.wallaby-vscode-1.0.86.vsix
3)	download the https://s3.amazonaws.com/wallaby-downloads/wallaby-v1.0.604.zip the first value [0] from latestServer in wallaby.json

4)	unzip the downloaded file to the C:\Users\UserName\\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby
5)	download the latest PhantomJs for your platform
6)	extract the downloaded archive and place the PhantomJs binary to the C:\Users\USERNAME\.vscode\phantomjs_v2.1.1 folder

Installing Core

7)	download trusted core version from the https://s3.amazonaws.com/wallaby-downloads/wallaby-v0.9.10.zip the second value [1] from latestServer in wallaby.json
8)	unzip the downloaded file to the C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby
9)	had some merge conflicts since both were extracted to same folder but replaced with core version

when I start the vs-code I see following error
With wallaby.noAutomaticInstall option set, you need to manually install wallaby core and dependencies when the extension is installed/updated.

![image](https://user-images.githubusercontent.com/11776039/41730114-f5605804-7548-11e8-960f-fb2a4b23d12d.png)

**Comment by ArtemGovorov** [comment]
> 7)	download trusted core version from the https://s3.amazonaws.com/wallaby-downloads/wallaby-v0.9.10.zip the second value [1] from latestServer in wallaby.json

The trusted version is value [0] from latestServer, nowhere is the docs it says to use  the second value [1] from latestServer. Also, the core is already installed with your previous steps, and those 7-9 steps are about updating then core in future (as the title in the docs for them says), so don't need to do it now.

So please delete `c:\Users\UserName\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby`, repeat steps 3 and 4 and try running it again. 

If it's still not working, then the issue may be related to the way that the dependencies are unzipped. If it's the case, please attach a screenshot of your file explorer with `C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby` and `C:\Users\USERNAME\.vscode\phantomjs_v2.1.1` folders expanded so we could check that downloaded archives are correctly extracted.

**Comment by snehalp29** [comment]
Phantom JS
![image](https://user-images.githubusercontent.com/11776039/41753713-14e13654-759d-11e8-8f22-2944526e4d97.png)

Wallaby

![image](https://user-images.githubusercontent.com/11776039/41753742-393b9b0c-759d-11e8-99bf-3696c887759f.png)

**Comment by ArtemGovorov** [comment]
Thanks.

The `C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST` is not supposed to be literally named, the `LATEST` part is means the latest installed extension version, so the folder should be `C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.86`. Try moving the `C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby` folder to the `C:\Users\USERNAME\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.86` folder.

**Comment by snehalp29** [comment]
Hi, 
Thank Artem I got it working. 

I would like to use wallaby with angular cli project 

may I know if we have any sample steps to follow or config that I can copy to get it up and running Quickly

btw its working fine when I run it on calculator project
but when cli project and 


var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [{
          test: /\.css$/,
          loader: ['raw-loader', 'css-loader']
        },
        {
          test: /\.html$/,
          loader: 'raw-loader'
        },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: {
            tsConfigPath: 'tsconfig.json'
          }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        {
          test: /\.json$/,
          loader: 'json-loader'
        },
        {
          test: /\.styl$/,
          loaders: ['raw-loader', 'stylus-loader']
        },
        {
          test: /\.less$/,
          loaders: ['raw-loader', 'less-loader']
        },
        {
          test: /\.scss$|\.sass$/,
          loaders: ['raw-loader', 'sass-loader']
        },
        {
          test: /\.(jpg|png)$/,
          loader: 'url-loader?limit=128000'
        }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [{
        pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      {
        pattern: 'src/**/*.d.ts',
        ignore: true
      },
      {
        pattern: 'src/**/*spec.ts',
        ignore: true
      }
    ],

    tests: [{
        pattern: 'src/**/*spec.ts',
        load: false
      },
      {
        pattern: 'src/**/*e2e-spec.ts',
        ignore: true
      }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

nothing happnes 

I dont see green dots on the side

**Comment by ArtemGovorov** [comment]
Please make sure you've followed all the steps [from this readme file for Angular CLI generated projects](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/README.md). You may also run `ng add ngcli-wallaby` to run those steps automatically.

If it still doesn't work after performing those steps, please take a look init Wallaby.js log displayed in the [Wallaby Console output channel in VS Code](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).
