### ISSUE TITLE
How to put together Vue + Webpack + AvA + Wallaby ?

### ISSUE THREAD

**Issue by numfin** [wallabyjs/public#1719]
### Issue description or question
I setted up AvA + Webpack + Vue. Its testing. Now when im trying to configure Wallaby.js - its just not load my Vue files. 

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({
    presets: [['@vue/app', { modules: 'commonjs' }]],
  });

  return {
    files: ['src/**/*', 'package.json', 'tsconfig.json'],
    tests: ['tests/**/*.spec.ts'],
    env: {
      type: 'node',
      runner: 'node',
    },
    preprocessors: {
      '**/*.js': file =>
        require('babel-core').transform(file.content, {
          sourceMaps: true,
          compact: false,
          filename: file.path,
          presets: ['env'],
        }),
      // '**/*.vue': file => require('vue-jest').process(file.content, file.path),
    },
    compilers: {
      '**/*.js': compiler,
      '**/*.ts': wallaby.compilers.typeScript(require('./tsconfig.json')),
      '**/*.vue': require('wallaby-vue-compiler')(compiler),
    },
    testFramework: 'ava',
    debug: true,
  };
};
```
### tests/HelloWorld.spec.ts
```javascript
import test from 'ava';
import { shallowMount } from '@vue/test-utils';
import HelloWorld from '../src/components/HelloWorld.vue';

test('works', (t) => {
  const wrapper = shallowMount(HelloWorld, { propsData: { msg: 'world' } });
  t.is(wrapper.vm.$el.innerHTML, 'Hello world!');
});
```

With this configuration it shows:
![image](https://user-images.githubusercontent.com/8134947/41691425-416e54da-7503-11e8-8d0f-0356fef242d8.png)

But if im adding this preprocessor as in tutorial ([here](https://wallabyjs.com/docs/integration/vue.html))...
```javascript
{
  '**/*.vue': file => require('vue-jest').process(file.content, file.path)
}
```

...its just crashing:
![image](https://user-images.githubusercontent.com/8134947/41691484-8b9df178-7503-11e8-9513-ad16d083b76c.png)

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

Windows 10 (1803)

**Comment by ArtemGovorov** [comment]
Could you please share a sample repo with your current setup (so that we have all the file with all the versions of frameworks that you're using)? We are happy to take a look and help with the configuration.

**Comment by numfin** [comment]
@ArtemGovorov https://github.com/numfin/wallaby-ts-vue-ava-issue

**Comment by numfin** [comment]
@ArtemGovorov forgot to say, npm run test works fine. Only wallaby cant launch

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. 

There are 2 ways you can make it work, with `vue-jest` and without `vue-jest`. Note that regardless of the solution used, wallaby [doesn't support displaying code coverage in TypeScript sections of .vue files](https://github.com/wallabyjs/public/issues/1469#issuecomment-358965998). However, it should be able to run tests and display results in them.

For both solutions, some Ava setup code, similar to what you have in the `tests/helpers/setup.js` file is required. With `vue-jest` solution, wallaby will also be able to track dependencies between your `.vue` files and re-run tests on their changes. In the solution without `vue-jest`, with just Ava hooks, you'll need to touch a test file before changing a `.vue` file so that wallaby can re-run tests for the `.vue` file changes.

I have sent you 2 pull requests with both solutions:
https://github.com/numfin/wallaby-ts-vue-ava-issue/pull/1
https://github.com/numfin/wallaby-ts-vue-ava-issue/pull/2

**Comment by numfin** [comment]
@ArtemGovorov to render my components i need to provide template string. Usually <template></template> in *.vue files. There is no way to import vue files from .ts files and render it. So i decided to use vue-template-compiler which provides ts decorator for this. Now im wondering how to make wallaby work with this.
p.s. I updated my repo so you can see how is this working. I just need to make wallaby see my htmls.

**Comment by numfin** [comment]
I surrender. Will wait for ```<script lang="ts"><script>``` wallaby support. For now its possible only for js with ava. https://github.com/numfin/wallaby-vue-ava-configuration

**Comment by ArtemGovorov** [comment]
Have got the latest version of https://github.com/numfin/wallaby-ts-vue-ava-issue, but plain Ava (`npm test`) is not working for me there either. Could you please make Ava (without wallaby) work and I'll take a look into how to do the same/similar for Wallaby.

**Comment by numfin** [comment]
@ArtemGovorov tried to reconfigure everything completely with my js configuration, but. @vue/test-utils are working strange.

**Comment by numfin** [comment]
@ArtemGovorov HORRRAAAY!!! I figure it out. The only thing is that not working right now is typings:
![image](https://user-images.githubusercontent.com/8134947/41786934-8800002c-764f-11e8-9edd-cd289c44f363.png)
![image](https://user-images.githubusercontent.com/8134947/41786943-9105f96a-764f-11e8-85be-a758bb4edd0d.png)

I uploaded new version. If you know how to fix it - please help.

p.s. dont try to test with ava, because its just not working with ts sections, i didnt found any require-extension-hook for that. 

omg im so happy its closer and closer! 🙌

**Comment by ArtemGovorov** [comment]
> The only thing is that not working right now is typings

I'm guessing it's because you are trying to compile TypeScript with Babel. And you should be able to do it with the [TypeScript preset](https://new.babeljs.io/docs/en/next/babel-preset-typescript.html). Try installing the preset and adding to your Wallaby config:

```js
const compiler = wallaby.compilers.babel({ "presets": ["@babel/preset-typescript"] });
```

**Comment by numfin** [comment]
@ArtemGovorov uh finally. everything works now. 
DUDE WE ROCK!!!! 
i uploaded instructions here https://github.com/numfin/wallaby-vue-ava-typescript-configuration

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! We have added the repo link to the collection of recommended [config recipes in the docs](https://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes).
