### ISSUE TITLE
require.extensions not used

### ISSUE THREAD

**Issue by cassus** [wallabyjs/public#172]
I'm using node + mocha to test my webpack app without webpack. I used require.extensions to work around webpack-style require-ing non-js files. It works with mocha runner but fails with wallaby.

I have
```js
bootstrap: function () {
    require.extensions['.sass'] = function(module) {
        module.exports = 'SASS-DUMMY'
    }
},
```

But I still get error
`
Error: Cannot find module './style.sass'
	at app/components/Application/index.jsx:4
`

**Comment by ArtemGovorov** [comment]
The most likely reason is that the file is not in the `files` list of your wallaby config. 

Wallaby.js [copies listed files to its local cache](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39) to instrument them and run tests, and looks like node.js still needs the required file to be present, even when it's actual loading is mocked with extensions function like your case.

Please let me know if it works if you add your styles pattern to the files list.

**Comment by cassus** [comment]
Thanks, including assets in `files` fixed it!
