### ISSUE TITLE
Visual Studio Code extension uses vulnerable Node.js module

### ISSUE THREAD

**Issue by valentiniliescu** [wallabyjs/public#1720]
### Issue description or question
The Visual Studio Code extension uses adm-zip version 0.4.8 which has a vulnerability, see [https://github.com/snyk/zip-slip-vulnerability#affected-libraries](https://github.com/snyk/zip-slip-vulnerability#affected-libraries)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The dependency had been updated in the latest version 1.0.87.
