### ISSUE TITLE
Wallaby errors out after recent changes in project

### ISSUE THREAD

**Issue by silentnoise86** [wallabyjs/public#1725]
### Issue description or question

Recently wallaby doesnt work across all project 
this is an agular project that is not built with angular cli 

### Wallaby.js configuration file

```js
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
  if (filePath === 'source-map-support') {
    return {install: () => {}};
  }
  return originalRequire.call(this, filePath);
};

var webpackConfig = require('./conf/webpack.conf');
modulePrototype.require = originalRequire;
module.exports = function (wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'conf/spec-bundle-wallaby.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: 'raw-loader'},
        {test: /\.html$/, loader: 'raw-loader'},
        {
          test: /\.ts$/,
          include: /node_modules/,
          use: [
            {
              loader: 'awesome-typescript-loader',
              query: {
                sourceMap: false,
                inlineSourceMap: true,
                compilerOptions: {
                  removeComments: true
                }
              }
            },
            'angular2-template-loader'
          ]
        },
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src')
      ]
    }
  });

  return {
    files: [
        {pattern: 'src/**/*.ts', load: false},
        {pattern: 'conf/spec-bundle-wallaby.js', load: false, instrument: false},
        {pattern: 'src/**/*.d.ts', load: false},
        {pattern: 'src/**/*.css', load: false},
        {pattern: 'src/**/*.less', load: false},
        {pattern: 'src/**/*.scss', load: false},
        {pattern: 'src/**/*.sass', load: false},
        {pattern: 'src/**/*.styl', load: false},
        {pattern: 'src/**/*.html', load: false},
        {pattern: 'src/**/*.json', load: false},
        {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
        // change to folder you working with
      // {pattern: 'src/**/platform/**/**/*spec.ts', load: false},
      {pattern: 'src/**/shared/dynamic-form/**/*spec.ts', load: false},
    ],

    testFramework: 'jasmine',

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
        kind: 'chrome',
        params: {
            runner: '--headless --disable-gpu'
        }
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true,
    delays: {
        run: 2000
      }
  };
};
```

```javascript
// paste your config here
not sure what files you need to see here but i paste here spec-bundle-wallaby.js from our conf dir :
Error.stackTraceLimit = Infinity;

require('core-js/es6');
require('core-js/es7/reflect');

require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/proxy'); // since zone.js 0.6.15
require('zone.js/dist/sync-test');
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');

/**
 * RxJS
 */
require('rxjs/Rx');

let testing = require('@angular/core/testing');
let browser = require('@angular/platform-browser-dynamic/testing');

testing.TestBed.initTestEnvironment(
  browser.BrowserDynamicTestingModule,
  browser.platformBrowserDynamicTesting()
);

```

### Code editor or IDE name and version
It doesnt work both in webstorm and in visual studio code 
Visual Studio Code v1.?
WebStorm v 2018.1 WS-181.4203.535
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows 10 Version 1607 Os Build 14393.2189
OSX
Linux

Error  message
Tue, 26 Jun 2018 07:10:35 GMT wallaby:project WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, defaultRules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp?, strictExportPresence?, strictThisContextOnImports? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at WebpackPostprocessor.webpack [as _webpack] (C:\Dev\Sources\swm\swm\SmaFrontend\node_modules\webpack\lib\webpack.js:24:9)
    at WebpackPostprocessor._createCompiler (C:\Dev\Sources\swm\swm\SmaFrontend\node_modules\wallaby-webpack\index.js:270:41)
    at wallaby (C:\Dev\Sources\swm\swm\SmaFrontend\node_modules\wallaby-webpack\index.js:112:31)
    at C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\server.js:17:6704
    at _fulfilled (C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:816:13)
    at C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:624:44
    at runSingle (C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:137:13)
    at flush (C:\Users\tkornis\.WebStorm2018.1\system\wallaby\wallaby\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ArtemGovorov** [comment]
You must have updated your Webpack to a newer version, and the error message precisely says what's wrong:

> configuration.module has an unknown property 'loaders'.

This is because in the newer Webpack version, `module.loaders` had been renamed to `module.rules`. All you need to do is to rename the setting in your Wallaby config:

```diff
...
module.exports = function (wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    ...

    module: {
-    loaders: [
+    rules: [
        {test: /\.css$/, loader: 'raw-loader'},
```
