### ISSUE TITLE
TypeScript, RequireJS, and extends

### ISSUE THREAD

**Issue by BrianMcBrayer** [wallabyjs/public#173]
Hello! I am |-| <-- this close to getting this to work (I think). However, I think I've hit an error with either WallabyJS or the TypeScript compiler. It happens when I use the `extends` keyword, and I get the error `Can't find variable` on the class that is extended. I cannot find any similar issues online. If this is not a WallayJS issue I apologize.

Repo with the error (forked from the excellent TypeScript/RequireJS demo) here. https://github.com/BrianMcBrayer/wallaby-typescript-requirejs/tree/master/wallabyMultiExtend

Thank you SO much.

**Comment by BrianMcBrayer** [comment]
Visual Studio outputs the following (working) code (for an internal prototype):
`
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
define(["require", "exports", 'Foos/extensions/Foo'], function (require, exports, Foo) {
    var FooExtended = (function (_super) {
        __extends(FooExtended, _super);
        function FooExtended() {
            _super.call(this);
        }
        return FooExtended;
    })(Foo);
    return FooExtended;
});
//# sourceMappingURL=FooExtended.js.map
`

The instrumented code outputted by WallabyJS follows:
`
$_$wp(53);
var __extends = ($_$w(53, 0), ($_$w(53, 1), this.__extends) || ($_$w(53, 2), function (d, b) {
    $_$wf(53);
    for (var p in b) {
        if ($_$w(53, 3), b.hasOwnProperty(p)) {
            $_$w(53, 4), d[p] = b[p];
        }
    }
    function __() {
        $_$wf(53);
        $_$w(53, 5), this.constructor = d;
    }
    $_$w(53, 6), __.prototype = b.prototype;
    $_$w(53, 7), d.prototype = new __();
}));
$_$w(53, 8), define([
    'require',
    'exports'
], function (require, exports) {
    $_$wf(53);
    var FooExtended = ($_$w(53, 9), function (_super) {
        $_$wf(53);
        $_$w(53, 10), __extends(FooExtended, _super);
        function FooExtended() {
            $_$wf(53);
            $_$w(53, 11), _super.call(this);
        }
        return $_$w(53, 12), FooExtended;
    }(Foo));
    return $_$w(53, 13), FooExtended;
});
`

I can easily see that the `define` call in the instrumented code does not include the extended classname in its requirements whereas Visual Studio does. Not sure which compiler is at fault--it may be a TypeScript thing, but I cannot find any helpful examples.

**Comment by ArtemGovorov** [comment]
Thanks for the sample, very helpful! It was a bug in wallaby integration with TypeScript compiler specific to AMD module output. The bug is fixed now (core v1.0.73, will update automatically next time you start wallaby/restart VS).

Please let me know if it works for you now. Note that tests in your sample solution will still fail, but for a valid reason: `sayHello` function is using `_el2` that is not set.

**Comment by BrianMcBrayer** [comment]
After I restarted Visual Studio... it worked!!! Thank you so much for your help and quick bug fix! I can't wait to start really working with this and see how fast it speeds me up!
