### ISSUE TITLE
Can't resolve TypeScript paths 

### ISSUE THREAD

**Issue by c-science1** [wallabyjs/public#1730]
### Issue description or question
When I try to run the whole suit of tests get the error related to the paths

Module not found: Error: Can't resolve 'shared/sidebar/sidebar.service' in '.\src\app'ModuleNotFoundError: Can't resolve 'shared/sidebar/sidebar.service' in '.\src\app'

### Wallaby.js configuration file
```js
var wallabyWebpack = require('wallaby-webpack');

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;
module.exports = function (wallaby) {
  var path = require('path');
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*.spec.js'
    ],

    resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
        // path.join(wallaby.projectCacheDir, 'src'),
        // path.join(wallaby.projectCacheDir, 'app/auth/'),
        // path.join(wallaby.projectCacheDir, 'app/core/'),
        // path.join(wallaby.projectCacheDir, 'app/shared/'),
        // path.join(wallaby.projectCacheDir, 'app/store')
      ]
    }

  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      // {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: false},
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],
    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,
  };
};

below is my tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "paths": {
      "app/*": ["app/*"],
      "auth/*": ["app/auth/*"],
      "core/*": ["app/core/*"],
      "environments/*": ["environments/*"],
      "features/*": ["app/features/*"],
      "shared/*": ["app/shared/*"],
      "store/*": ["app/store/*"]
    },
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

### Code editor or IDE name and version
WebStorm 2018.1.4
Build #WS-181.5087.27, built on May 21, 2018

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Looks like you are missing `module.resolve` path (similar to your tsconfig paths).

If the `shared` folder is `src /app/shared`, then it should work if you add this:

```diff
    resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
+       path.join(wallaby.projectCacheDir, 'src/app'),
        ...
      ]
    }
```

If it doesn't help, please let us know where is the `shared` folder located.

**Comment by c-science1** [comment]
here is my updated 
  resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'src/app')
      ]
    }

but I get No failing tests, 0 passing !

**Comment by c-science1** [comment]
I updated it to 

  resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'src/app')
      ]
    }

but getting 

![image](https://user-images.githubusercontent.com/19345360/42021453-83b53a0c-7ab2-11e8-8ca5-50d5a6123e49.png)

**Comment by ArtemGovorov** [comment]
Please take a look into the Wallaby Console tab to see if some errors are printed there.

**Comment by ArtemGovorov** [comment]
Ah, nevemind, I can see the issue. Your config is using [Webpack, but missing the required `setup` function](https://wallabyjs.com/docs/integration/webpack.html):

```js
module.exports = function (wallaby) {
  return {
    ...
    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

**Comment by c-science1** [comment]
Thanks, it works fine now. However, the tests are not automatically running on changing the code.
Do I need to enable this setting before it used to do it out of the box so I now having to re-run manually?
