### ISSUE TITLE
Tests failing with a compilation error!

### ISSUE THREAD

**Issue by c-science1** [wallabyjs/public#1732]
### Issue description or question
I am getting this error for half of the unit tests in the suite. 
Is there a setting that I am missing?

Error: This test module uses the component SidebarComponent which is using a "templateUrl" or "styleUrls", but they were never compiled. Please call "TestBed.compileComponents" before your test.

### Wallaby.js configuration file
```js
var wallabyWebpack = require('wallaby-webpack');

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;
module.exports = function (wallaby) {
  var path = require('path');
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*.spec.js'
    ],

    resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'src/app')
      ]
    }

  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      // {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: false},
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],
    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron',
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm 

### OS name and version

Windows

**Comment by c-science1** [comment]
![image](https://user-images.githubusercontent.com/19345360/42036866-b245dd32-7ade-11e8-9870-e092edfcea70.png)

**Comment by ArtemGovorov** [comment]
Looks like you are missing a loader for processing styles and templates in your wallaby webpack config.  Are you using Wallaby in Angular CLI generated project? If so, then try the [config from this sample repo](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js), it should help (for this issue specifically - [this loader should help](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L23)). Please also make sure to follow the readme steps to install all required dependencies.
