### ISSUE TITLE
Wallaby does not detect the covered files for suite of tests.

### ISSUE THREAD

**Issue by jeansebb** [wallabyjs/public#1733]
### Issue description or question
Wallaby does not seem to detect that a test that use proxyquire, test the imported file, so no covered files are detected. Coverage in Wallaby are 0%. NYC does it correctly.

I have a wrapper around node-postgres. I want to test a certain logic about the Pool query that is an event emitters. I want to proxyquire the pg lib to mock the pool and be able to simulate behavior.

Wallaby just doesnt pick up that I am testing my wrapper at all.

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    setup: wallaby => {
      require(wallaby.localProjectDir + '/test/setup')
    }
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

OSX High Sierra 10.13.5

**Comment by ArtemGovorov** [comment]
Could you please set up and share a sample repo demonstrating the issue? We are happy to take a look and help with the config.

**Comment by smcenlly** [comment]
Closing this issue as we need more information. We will re-open the issue if more detail is provided.
