### ISSUE TITLE
NG4 CLI Node module dependencies 

### ISSUE THREAD

**Issue by snehalp29** [wallabyjs/public#1734]
### Issue description or question
Cannot find module 
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [{
          test: /\.css$/,
          loader: ['raw-loader', 'css-loader']
        },
        {
          test: /\.html$/,
          loader: 'raw-loader'
        },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: {
            tsConfigPath: 'tsconfig.json'
          }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        {
          test: /\.json$/,
          loader: 'json-loader'
        },
        {
          test: /\.styl$/,
          loaders: ['raw-loader', 'stylus-loader']
        },
        {
          test: /\.less$/,
          loaders: ['raw-loader', 'less-loader']
        },
        {
          test: /\.scss$|\.sass$/,
          loaders: ['raw-loader', 'sass-loader']
        },
        {
          test: /\.(jpg|png)$/,
          loader: 'url-loader?limit=128000'
        }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [{
        pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      {
        pattern: 'src/app/helper/modernizr.js',
        instrument: false
      },
      {
        pattern: '​src/mocks/user-roles/service/indv.js',
        instrument: false
      },
      {
        pattern: '​src/mocks/helper.js',
        instrument: false
      },
      {
        pattern: '​global-navigation/**/*.+(ts|js)',
        instrument: false
      },
      {
        pattern: 'src/**/*.d.ts',
        ignore: true
      },
      {
        pattern: 'src/**/*spec.ts',
        ignore: true
      }
    ],

    tests: [{
        pattern: 'src/**/*spec.ts',
        load: false
      },
      {
        pattern: 'src/**/*e2e-spec.ts',
        ignore: true
      }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version
Visual Studio Code v1.24.1

### OS name and version
Windows

==================================

​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/core/services/ajax-loader/ajax-loader.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/core/services/byc-nav-update/byc-nav-update.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/core/services/byc-nav-update/byc-nav-update.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/core/services/contract-summary/contract-summary.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/core/services/contract-summary/contract-summary.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/core/services/pru-urls/pru-urls.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/core/services/pru-urls/pru-urls.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/document-center/doc-center-content.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/document-center/doc-center-content.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/document-center/document-center.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/document-center/document-center.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/document-landing/doc-table/doc-table.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/document-landing/doc-table/doc-table.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/document-landing/document-landing.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/document-landing/document-landing.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/faq/faq-left-nav/faq-left-nav.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/faq/faq-left-nav/faq-left-nav.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/faq/faq.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/faq/faq.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/footer/services/footer.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/footer/services/footer.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/home/home.service.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/home/home.service.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/components/breadcrumb/breadcrumb.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/components/breadcrumb/breadcrumb.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/components/date-picker/components/date-picker.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/components/date-picker/components/date-picker.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/components/pru-id/pru-id.component.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/components/pru-id/pru-id.component.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/pipes/mask-string/mask-string.pipe.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/pipes/mask-string/mask-string.pipe.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/pipes/remove-duplicates-from-array/remove-duplicates-from-array.pipe.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/pipes/remove-duplicates-from-array/remove-duplicates-from-array.pipe.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Preparing to serve /src/app/shared/pipes/space-to-hyphen/space-to-hyphen.pipe.spec.js.wbp.js
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:25 GMT wallaby:middleware Serving /src/app/shared/pipes/space-to-hyphen/space-to-hyphen.pipe.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:26 GMT wallaby:workers Sandbox (active) [a4lvh] error: Uncaught Error: Cannot find module "mocks/helpers"
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:26 GMT wallaby:workers [a4lvh] Loaded 0 test(s)
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers [a4lvh] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers [a4lvh] Sandbox is responsive, closing it
​​[Error] Runtime error: Uncaught Error: Cannot find module "mocks/helpers"​​
​​[Error] at http://localhost:62128/src/app/alerts/alerts-content.service.spec.js.wbp.js?1530295162331&wallabyFileId=65:186​​
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers Sandbox (active) [tlbx2] error: **Uncaught Error: Cannot find module "global-navigation/src/app/services/alerts.service"**
​​[Error] Runtime error: Uncaught Error: Cannot find module "global-navigation/src/app/services/alerts.service"​​
​​[Error] at http://localhost:62128/____wallaby-bundle.js?1530295163922&wallabyFileId=bundle:466​​
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers [tlbx2] Loaded 0 test(s)
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers [tlbx2] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers [tlbx2] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:workers Merging parallel test run results
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Processed console.log entries
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Processed loading sequences
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Processed executed tests
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Processed code coverage
​​​​​[Info]​​​​​ Fri, 29 Jun 2018 17:59:27 GMT wallaby:project Test run result processed and sent to IDE

**Comment by ArtemGovorov** [comment]
> Cannot find module "mocks/helpers"​​
> Cannot find module "global-navigation/src/app/services/alerts.service"

- Where are these modules located relatively to the wallaby config file? 
- Is `global-navigation` your project root folder name?
- How is the "global-navigation/src/app/services/alerts.service" module imported in your tests/source?

**Comment by ArtemGovorov** [comment]
Could you please attach a screenshot of the expanded `node_modules/global-navigation/src/app/services/` folder (and all nested subfolder of the folder) in your File Explorer?

**Comment by snehalp29** [comment]
Global Nav node modules
[image: image.png]


App Structure

[image: image.png]

**Comment by ArtemGovorov** [comment]
@snehalp29 It doesn't look like the images have been attached correctly. Could you please re-upload them?

**Comment by snehalp29** [comment]
![image](https://user-images.githubusercontent.com/11776039/42332907-45d335f0-8047-11e8-8147-44c417813f4d.png)


![image](https://user-images.githubusercontent.com/11776039/42333012-91d1a342-8047-11e8-8f15-918123ec62b2.png)

**Comment by ArtemGovorov** [comment]
Thanks, try this:

```diff
-      {
-        pattern: '​global-navigation/**/*.+(ts|js)',
-        instrument: false
-      },
+      {
+        pattern: 'node_modules/​global-navigation/**/*.+(ts|js)',
+      },
```

**Comment by snehalp29** [comment]
Hi Artem,

thanks your suggestions worked but still all the issues are not yet resolved.
I am still getting a new error.

​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:37:56 GMT wallaby:middleware Serving /src/app/shared/pipes/safe-html/safe-html.pipe.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:37:59 GMT wallaby:workers Sandbox (active) [qssmr] error: Uncaught Error: Cannot find module "mocks/helpers.js"
​​[Error] Runtime error: Uncaught Error: **Cannot find module "mocks/helpers.js"​​**
​​[Error] at http://localhost:58121/src/app/alerts/alerts-store.service.spec.js.wbp.js?1532097463402&wallabyFileId=70:8​​
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:37:59 GMT wallaby:workers [qssmr] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:37:59 GMT wallaby:workers [qssmr] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:38:00 GMT wallaby:workers Sandbox (active) [ner2g] error: Uncaught Error: Cannot find module "mocks/helpers"
​​[Error] Runtime error: Uncaught Error: Cannot find module "mocks/helpers"​​
​​[Error] at http://localhost:58121/src/app/alerts/alerts-content.service.spec.js.wbp.js?1532097463379&wallabyFileId=68:186​​
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:38:00 GMT wallaby:workers [ner2g] Run 0 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Fri, 20 Jul 2018 14:38:00 GMT wallaby:workers [ner2g] Sandbox is responsive, closing it


I have following configuration in webpack 

```
module.exports = {
  resolve: {
    extensions: ['.ts', '.js'],
    modules: [path.join(__dirname, 'node_modules')],
    alias: {
      mocks: path.resolve(__dirname, 'src/mocks/')
    }
  },
  resolveLoader: {
    modules: ['./node_modules', './node_modules']
  },
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the additional details. This should help:

```diff
module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    ...

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
+     alias: {
+       mocks:  path.join(wallaby.projectCacheDir, 'src/mocks/')
+     }
    },
```

**Comment by snehalp29** [comment]
Hi Artem,

the above code was not resolving the issue so I replaced it with what I have in webpack

```
alias: {
      mocks: path.resolve(__dirname, 'src/mocks/')
    }
```
and it worked but still getting few issues

]​​​​​ Tue, 24 Jul 2018 02:47:31 GMT wallaby:middleware Serving /src/app/shared/pipes/space-to-hyphen/space-to-hyphen.pipe.spec.js.wbp.js from cache
​​​​​[Info]​​​​​ Tue, 24 Jul 2018 02:47:32 GMT wallaby:workers Sandbox (active) [edz5v] error: Uncaught Error: Cannot find module "app/core/services/timeoutModal.js"
​​[Error] Runtime error: Uncaught Error: Cannot find module "app/core/services/timeoutModal.js"​​
​​[Error] at http://localhost:61233/____wallaby-bundle.js?1532400448631&wallabyFileId=bundle:1015​​
​​​​​[Info]​​​​​ Tue, 24 Jul 2018 02:47:32 GMT wallaby:workers [edz5v] Loaded 1 test(s)
​​​​​[Info]​​​​​ Tue

this timeoutModal.js is old legacy file not es6 module file how can I fix this error
also my webpack has some sass loader settings

```
{
        exclude: [path.join(process.cwd(), 'src/styles/styles.scss')],
        test: /\.scss$|\.sass$/,
        use: [
          'exports-loader?module.exports.toString()',
          {
            loader: 'css-loader',
            options: {
              sourceMap: false,
              importLoaders: 1
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              ident: 'postcss',
              plugins: postcssPlugins
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: false,
              precision: 8,
              includePaths: [
                'node_modules/pru-strap/dist/sass',
                'node_modules/bootstrap-sass/assets/stylesheets/bootstrap',
                'node_modules/font-awesome/scss',
                'node_modules/bootstrap-datepicker',
                'node_modules/global-navigation/src/styles/styles.scss'
              ]
            }
          }
        ]
      },
```

how to copy these seeting to wallaby ?
can we use the same webpack config file and share with wallaby ?

**Comment by ArtemGovorov** [comment]
> Cannot find module "app/core/services/timeoutModal.js"

Looks like your Wallaby config `files` list doesn't have `.js` extension, this should help:

```diff
{
-       pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
+       pattern: 'src/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
        load: false
},
```

> also my webpack has some sass loader settings
> how to copy these seeting to wallaby ?

The argument that you are passing to `wallabyWebpack({...})` is Webpack configuration. So you may replace the existing `sass` rule with your in the `module.rules` list. Eg. this one:

```js
        {
          test: /\.scss$|\.sass$/,
          loaders: ['raw-loader', 'sass-loader']
        },
```
with yours.

**Comment by snehalp29** [comment]
so I replaced above scss rule with below

```
{
          exclude: [path.join(process.cwd(), 'src/styles/styles.scss'), path.join(process.cwd(), 'src/assets/**/*.*')],
          test: /\.scss$|\.sass$/,
          use: [
            'exports-loader?module.exports.toString()',
            {
              loader: 'css-loader',
              options: {
                sourceMap: false,
                importLoaders: 1
              }
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: false,
                precision: 8,
                includePaths: [
                  'node_modules/pru-strap/dist/sass',
                  'node_modules/bootstrap-sass/assets/stylesheets/bootstrap',
                  'node_modules/font-awesome/scss',
                  'node_modules/bootstrap-datepicker',
                  'node_modules/global-navigation/src/styles/styles.scss'
                ]
              }
            }
          ]
        }, {
          include: [path.join(process.cwd(), 'src/styles/styles.scss'), path.join(process.cwd(), 'src/assets/**/*.*')],
          test: /\.scss$|\.sass$/,
          use: [
            'exports-loader?module.exports.toString()',
            {
              loader: 'css-loader',
              options: {
                sourceMap: false,
                importLoaders: 1
              }
            },
            {
              loader: 'sass-loader',
              options: {
                sourceMap: false,
                precision: 8,
                includePaths: [
                  'node_modules/pru-strap/dist/sass',
                  'node_modules/bootstrap-sass/assets/stylesheets/bootstrap',
                  'node_modules/font-awesome/scss',
                  'node_modules/bootstrap-datepicker',
                  'node_modules/global-navigation/src/styles/styles.scss'
                ]
              }
            }
          ]
        }
```

can we make it shorter ??
also how to include jquery with wallaby?

we are using angular-cli scripts tag to import jquery

**Comment by ArtemGovorov** [comment]
> can we make it shorter ??

Yes, you may `require` your existing webpack config into Wallaby config file and reuse some bits from it (such as adding this rule to the list of rules passed to `wallabyWebpack({ module: { rules: [...]}})`)

> also how to include jquery with wallaby?

Given jquery is installed as a node module, you may simply add it [to your `files` list with `load: true` (which is the default value)](https://wallabyjs.com/docs/config/files.html) (this will add it as a script):

```diff
files: [{
        pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      {
        pattern: 'src/app/helper/modernizr.js',
        instrument: false
      },
+     {
+       pattern: 'node_modules/jquery/dist/jquery.js',
+       instrument: false
+     },
```

**Comment by snehalp29** [comment]
Thanks, Artem now all the issues are resolved !!!! Thanks a lot

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
