### ISSUE TITLE
Object.values is not a function

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#1736]
### Issue description or question
I just started seeing this error, which I haven't ever seen previously:

`Runtime error: TypeError: Object.values is not a function​​`.

From what I can find online it might be related to using the wrong node version, but I added `runner: 'node'`, and I'm using `nvm` to set node at version 8.11.2, which should make wallaby use that version right?

Not sure what I can try.

### Wallaby.js configuration file
(Not passing anything in the overrides)

```javascript
// Use old-school javascript in this file to make it work nicely
const merge = require('lodash/merge');

function setWallabyConfig(name, overrides = {}) {
  return function setupWallaby(wallaby) {
    return merge(
      {},
      {
        name,
        testFramework: 'mocha',
        files: [
          'imports/**/**.js*',
          '!imports/core/node_modules/**',
          '!imports/core/assets/**',
          '!imports/**/*.spec.js*',
          'lang/*.json',
        ],
        tests: ['imports/**/*.spec.js*', '!imports/core/node_modules/**'],
        compilers: {
          '**/*.js?(x)': wallaby.compilers.babel({
            presets: ['meteor', '@babel/preset-react', '@babel/preset-flow'],
            plugins: [
              '@babel/plugin-transform-modules-commonjs',
              '@babel/plugin-proposal-class-properties',
              'meteor-babel/plugins/dynamic-import',
              [
                'module-resolver',
                {
                  root: ['.'],
                  alias: {
                    core: './imports/core',
                    meteor: './imports/core/utils/testHelpers/meteorStubs',
                  },
                },
              ],
            ],
          }),
        },
        env: { type: 'node', runner: 'node' },
        setup() {
          global.IS_WALLABY = true;
          global.fetch = require('node-fetch');
          global.window = { navigator: { userAgent: 'node.js' } };
        },
      },
      overrides
    );
  };
}

module.exports = setWallabyConfig;
```

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The `runner` setting allows you to specify the CLI command to run to resolve node. So whatever node version is resolved when running `node`, is used by Wallaby to run your tests.

You may easily check what version of node is used right in your tests by writing:
```js
console.log(process.version)
```

If the default version of `node` version is not resolved to what you need in your system, then you may specify any version path in the `runner` setting: https://github.com/wallabyjs/public/issues/1700#issuecomment-396530832.
