### ISSUE TITLE
How to use modern javascript in wallaby config file?

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#1737]
It's not clear to me how I could use modern javascript (es6, or even the one defined by my babel setup) in the wallaby config file.

Is it possible to run wallaby itself with `babel-cli`, or a more modern version of node so that I don't have to use old javascript (meaning I have to disable my code formatters whenever I edit the file..)?

**Comment by ArtemGovorov** [comment]
Wallaby config file runs in node. So whatever modern JavaScript features are supported by your node version, can be used in the config. The version on node to run the config is your system default `node` (whatever version you have set in PATH). 

You may easily check what version of node is used to run your config by adding:

```js
console.log(process.version)
```
right into your config and then checking the output from [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by ArtemGovorov** [comment]
Forgot to mention, you may also change the [version of node that runs Wallaby (and the config file)](https://wallabyjs.com/docs/intro/install.html#nodejs-1). Note that after the change this specified version of node will be used to run your tests as well, unless you have `env.runner` setting specified, in which case the setting's value will be used as the node version to run your tests.

**Comment by Floriferous** [comment]
When I try to set the node version in my workspace settings (not user settings), like this: `    "wallaby.node": "~/.nvm/versions/node/v8.11.2/bin/node"`

I get the following error:

`Can not start node.js process (~/.nvm/versions/node/v8.11.2/bin/node), make sure your system has node.js installed.`

Can I not use a relative path? How can I then share this setting with my collaborators?
