### ISSUE TITLE
Angular @Input types are not found when running Wallaby

### ISSUE THREAD

**Issue by KwintenP** [wallabyjs/public#1739]
### Issue description or question
In an Angular project powered by Nx from Nrwl with angular 6 and jest-preset-angular, I'm having problems with type definitions at `@Input` decorators. 

The following type definition is not working when running wallaby:

`@Input() test: Test;`

The following error is produced:

`ReferenceError: test_type_1 is not defined`

When I look inside the cache from WallabyJS and the transpiled version of that file, I can see the error is caused as Angular leverages this type in the `@Input` decorator: 

`   $_$w(10, 41), __decorate([
        core_1.Input(),
        __metadata('design:type', ($_$w(10, 42), ($_$w(10, 44), typeof (_a = ($_$w(10, 46), typeof test_type_1.Test !== 'undefined') && ($_$w(10, 47), test_type_1.Test)) === 'function') && ($_$w(10, 45), _a)) || ($_$w(10, 43), Object))
    ], InputErrorWallabyComponent.prototype, 'test', void 0);`

But the import that is providing this type is removed as it only has a type definition.

Repro of the issue can be found here: https://github.com/KwintenP/angular-cli-jest-nx-wallaby 
Yarn install and starting wallaby should show the error.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  const path = require('path');
  const ts = require(path.join(wallaby.localProjectDir, 'node_modules/typescript'));
  const jestconfig = require('./package.json').jest;

  var compilerOptions = Object.assign(
    require('./tsconfig.json').compilerOptions,
    require('./tsconfig.spec.json').compilerOptions);

  return {
    files: jestconfig.collectCoverageFrom,
    tests: ['apps/**/*spec.ts', '!apps/**/*e2e-spec.ts', 'libs/**/*spec.ts', '!libs/**/*e2e-spec.ts'],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },
    testFramework: 'jest',
    debug: true,
    hints: {
      ignoreCoverage: /ignore coverage/
    },
    setup: function (wallaby) {
      var jestConfig = require(wallaby.localProjectDir + '/package.json').jest;
      const pattern = '@myworkspacename/test-lib';
      jestConfig.moduleNameMapper[pattern] = jestConfig.moduleNameMapper[pattern].replace('<rootDir>', wallaby.projectCacheDir);
      console.log('jestCo', jestConfig);
      delete jestConfig.transform; // <--
      wallaby.testFramework.configure(jestConfig);
    }
  };
};

```

### Code editor or IDE name and version

WebStorm 2018.1?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. The issue is not related to `@Input`, if you remove the decorator, the issue remains.

> But the import that is providing this type is removed as it only has a type definition.

Yes, it is exactly what happens because by default Wallaby is trying to make TS compilation faster and overrides `noResolve`/`declaration` settings. Unfortunately, while working in most of cases, the optimisation it causes issues for file with definitions only compilation.

The solution is to tell Wallaby to fully honour your tsconfig.json settings by [using the `useStandardDefaults` TS compiler setting](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings):

```diff
  var compilerOptions = Object.assign(
    require('./tsconfig.json').compilerOptions,
    require('./tsconfig.spec.json').compilerOptions);
+ compilerOptions.useStandardDefaults = true;

```

**Comment by KwintenP** [comment]
Works like a charm! 

Thanks Artem, for the swift and correct response!
