### ISSUE TITLE
an angular service create test failing with [object ErrorEvent]

### ISSUE THREAD

**Issue by c-science1** [wallabyjs/public#1741]
A unit test to check if a service is created is failing with this error [object ErrorEvent]
Am I missing anything from the configuration?

This test doesn't fail when run using Karma.

### Wallaby.js configuration file
var wallabyWebpack = require('wallaby-webpack');

var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;
module.exports = function (wallaby) {
  var path = require('path');
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*.spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      modules: [
        // These are to aid with the relative paths in tsconfig
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'src/app')
      ]
    }

  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.scss', load: true},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: true},
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],
    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'chrome',
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      // required to trigger test loading
      jasmine.DEFAULT_TIMEOUT_INTERVAL = 50000;
      window.__moduleBundler.loadTests();
    }
  };
};

```javascript
import './polyfills';

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

```

**Comment by c-science1** [comment]
Found more details in Karma debug dev tools but why does Wallaby not give this information in it's console?

**Comment by ArtemGovorov** [comment]
Could you please share a reproducible sample repo (perhaps forking this sample is the easiest way to go - https://github.com/wallabyjs/ngCliWebpackSample)? We are happy to take a look.

**Comment by aikrez** [comment]
Today I had the same error [object ErrorEvent] en Karma showed

> HeadlessChrome 0.0.0 (Windows 10 0.0.0) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught TypeError: Cannot read property 'name' of undefined thrown",
    "str": "An error was thrown in afterAll\nUncaught TypeError: Cannot read property 'name' of undefined thrown"
  }
This was the test inside an Observable subscription
` expect(res[0].name.startsWith(term));`

The array was empty so obviosly the first item did not have a name property

Wallaybjs 1.0.115
Angular CLI 608
RxJS 6.2.1

**Comment by vespertilian** [comment]
I was getting a similar error. Seemed to be working in Karma, sometimes though it would fail in Karma to. So it was just very flaky overall hard to pin down. 

The cause of my issue was I was 

#### Wrong

```
    typeSelectEl.click();
    fixture.detectChanges();
```

#### Right (inside fakeAsync)

```
    typeSelectEl.click();
    fixture.detectChanges();
    flush();
```

I ended up using xit to narrow down the spec that was the culprit. The spec in question was not the spec that was reporting the failure (Yay ☹️). Hopefully this helps someone.
