### ISSUE TITLE
Question: VSCode Test Markers

### ISSUE THREAD

**Issue by TylorS** [wallabyjs/public#1743]
Hello, I'm working on a vscode extension, and I was wondering what API is used to add the passing/failing test markers next to the line numbers? 
Thank you so much in advance!

**Comment by ArtemGovorov** [comment]
Hello, we are using [`window.createTextEditorDecorationType` and `TextEditorDecorationType`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextEditorDecorationType) to display the markers.

**Comment by TylorS** [comment]
Thank you @ArtemGovorov !!
