### ISSUE TITLE
can't get Wallaby.js to run Jest tests from TypeScript files using the "import" syntax

### ISSUE THREAD

**Issue by marcelh-gh** [wallabyjs/public#1748]
### Issue description or question
In general, Wallaby.js is running. As long as I don't use any imports, I can get tests to run, I get feedback in VS Code and the Wallaby.js web app also runs fine.

Using the "imports" syntax to import modules though causes Wallaby.js to stop working at all with error messages like
`[Info]​​​​​     import { useSomeHelp } from '../useSomeHelp';
​​​​​[Info]​​​​​            ^
​​​​​[Info]​​​​​     SyntaxError: Unexpected token {`

I'd really appreciate some help with this. I am already a very happy user of Quokka.js and now I want to use Wallaby.js for a large project but I can't even get it to run properly in an empty test project.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.ts',
            "!src/**/*test.ts"
        ],
        tests: [
            'src/**/*test.ts'
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        debug: true,
    };
}
```

I have tried to add
```javascript
        compilers: {
            'src/**/*.ts': wallaby.compilers.typeScript({
            })
        }
```
without any effect.

### jest.config.js

```javascript
module.exports = {
    transform: {
        "^.+\\.tsx?$": "ts-jest"
    },
    testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
    moduleFileExtensions: [
        "tsx",
        "ts",
        "js",
        "jsx",
        "json",
        "node"
    ],
    testPathIgnorePatterns: [
        "<rootDir>/inject/*",
        "<rootDir>/node_modules/",
        "<rootDir>/compiledJS/"
    ],
    moduleDirectories: [
        "node_modules"
    ],
    moduleNameMapper: {
        "@HELPERS/(.*)": "<rootDir>/src/helpers/$1",
    },
    automock: false,
    verbose: true
};
```

### Environment

Jest 23.2
ts-jest 23.0
TypeScript 2.9.2
Visual Studio Code 1.24.1
Node.js 10.5
Windows 10 1709

**Comment by marcelh-gh** [comment]
I should have mentioned that running the test just via `npm run jest` works perfectly fine.

**Comment by marcelh-gh** [comment]
ok, it seems I already found the problem. My `tsconfig.json` is configured for ES2015 modules.
ts-jest does not seem to mind and just works. Wallaby.js seems to compile everything based on the tsconfig.json setting and therefore gets modules it can't handle.

**How can I specify in the `Wallaby.js` that I want to use a different `tsconfig.json` ?**

**Comment by ArtemGovorov** [comment]
> **How can I specify in the `Wallaby.js` that I want to use a different `tsconfig.json` ?**

You may [override any of TS compiler settings using the `compilers` setting](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings). 

```js
module.exports = function (wallaby) {
  return {
    ...

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs'
      })
    },

    ...
  };
};
```

> ts-jest does not seem to mind and just works.

`ts-jest` [runs Babel compilation on top of TypeScript compilation](https://github.com/wallabyjs/public/issues/1373#issuecomment-341279927). If you'd like to do the same, you may just add the Babel [preprocessor to run after TS compilation](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) as follows, like described at https://github.com/wallabyjs/public/issues/1375#issuecomment-342464261).

Note that in this case you don't need to override TS compiler settings, because Babel will take care of ES modules.

```diff
module.exports = function (wallaby) {
    return {
        ...
+       preprocessors: {
+         '**/*.js?(x)': file => require('babel-core').transform(
+           file.content,
+           {sourceMap: true, filename: file.path, compact: false, 
+            babelrc: true, presets: ['babel-preset-jest']})
+       }
    };
};
```

**Comment by marcelh-gh** [comment]
@ArtemGovorov Thank you very much for the super quick help! the variant overwriting the tsc config works. The other option using babel as preprocessor (which I'd prefer) does not work though.

**Comment by marcelh-gh** [comment]
no `.babel.rc` file in project...

**Comment by ArtemGovorov** [comment]
@marcelh-gh Then one of the preprocessors suggested above should help.

**Comment by marcelh-gh** [comment]
second one does not work..

**Comment by marcelh-gh** [comment]
@ArtemGovorov Thanks a lot! The first one works. :-) The second one does not..

**Comment by LStAmour** [comment]
Similar to all of the above solutions, I had a unique configuration where, in a subdirectory, my Babel config was doing all my typescript compilation -- and outputting es6 modules intentionally.

So I loaded my babelConfig and added a few plugins... this is probably the harder way to do it, but at least I knew exactly which babel config it was using! ;-)

```javascript
var babelConfig = require("./src/babel.config.js")();
if (!babelConfig.plugins.includes("jest-hoist")) {
  babelConfig.plugins.push("@babel/plugin-transform-modules-commonjs");
  babelConfig.plugins.push("jest-hoist");
}

module.exports = function(wallaby) {
  return {
    files: [
      { pattern: "src/**/*.test.js*", ignore: true },
      { pattern: "src/**/*.test.ts*", ignore: true },
      { pattern: "node_modules/babel-polyfill/dist/polyfill.js", instrument: false },
      "src/**/*.js",
      "src/**/*.ts",
      "src/**/*.jsx",
      "src/**/*.tsx",
      "tsconfig.json",
      "package.json"
    ],
    tests: ["src/**/*.test.jsx", "src/**/*.test.tsx", "src/**/*.test.js", "src/**/*.test.ts"],
    compilers: {
      "src/**/*.js": wallaby.compilers.babel(babelConfig),
      "src/**/*.ts": wallaby.compilers.babel(babelConfig),
      "src/**/*.jsx": wallaby.compilers.babel(babelConfig),
      "src/**/*.tsx": wallaby.compilers.babel(babelConfig)
    },
    testFramework: "jest",
    env: { type: "node" }
  };
};
```

**Comment by Alexanderurijs523** [comment]
> [@ArtemGovorov](https://github.com/ArtemGovorov) Thanks a lot! The first one works. :-) The second one does not..





https://lnkr.fun/6db3c92
