### ISSUE TITLE
Cannot find module "./browser/algorithms.json"​​

### ISSUE THREAD

**Issue by TomWhiteOmni** [wallabyjs/public#1749]
### Issue description or question
Hi (Wallaby is great! by the way)
I'm trying to configure Wallaby to work with my Angular 6 & Nrwl Nx project, and got the error below. It's successfully passing 4 tests and then giving this message. I had this error on another project, but it was standard Angular 6 but doing something quirky with Node Crypto - so I didn't report it. But this time, I think my request is valid.
I used [https://github.com/chgc/angular-nx-wallaby](https://github.com/chgc/angular-nx-wallaby) as reference although it's for an earlier version.

### Wallaby.js Tests Output:

Uncaught Error: Cannot find module "./browser/algorithms.json"​​
​​at http://localhost:64276/____wallaby-bundle.js?1530785357161&wallabyFileId=bundle:137842​​
​​Module parse failed: Unexpected character '#' (1:0)​​
​​You may need an appropriate loader to handle this file type.​​
​​| #!/usr/bin/env node​​
​​| "use strict";​​
​​| Object.defineProperty(exports, "__esModule", { value: true });ModuleParseError: Module parse failed: Unexpected character '#' (1:0)​​
​​You may need an appropriate loader to handle this file type.​​
​​| #!/usr/bin/env node​​
​​| "use strict";​​
​​| Object.defineProperty(exports, "__esModule", { value: true });​​

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./apps/supply-x-angular2/tsconfig.spec.json').compilerOptions,
  require('./libs/reporting/tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['wallabyTest.js', 'apps/**/*spec.js', 'libs/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader', 'css-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'wallabyTest.ts', load: false },
      {
        pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'apps/**/*.d.ts', ignore: true },
      { pattern: 'apps/**/*spec.ts', ignore: true },
      {
        pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'libs/**/*.d.ts', ignore: true },
      { pattern: 'libs/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'apps/**/*spec.ts', load: false },
      { pattern: 'libs/**/*spec.ts', load: false },
      { pattern: 'apps/**/e2e/**', ignore: true },
      { pattern: 'libs/**/e2e/**', ignore: true }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> Uncaught Error: Cannot find module "./browser/algorithms.json"​​

Looks like the file/folder is missing in the `files` patterns, try adding it there, it should help:

```
...
{ pattern: 'browser/*.json', load: false },
...
```

> ​​Module parse failed: Unexpected character '#' (1:0)​​
> ​​You may need an appropriate loader to handle this file type.​​
> ​​| #!/usr/bin/env node​​

Looks like one of your source files (or node modules that you're using) contains shebang, so you may need a loader to take care of it. If it's one of node modules, then addign this should help:

```diff
module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['wallabyTest.js', 'apps/**/*spec.js', 'libs/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader', 'css-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
+       { test: /\.js$/, loader: 'shebang-loader', include: /node_modules/ },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
      ]
    },
```

plus

```
npm install shebang-loader --save-dev
```

**Comment by TomWhiteOmni** [comment]
Excellent response time. Much appreciated.
Still have a problem, but the output has changed:

​​Uncaught Error: Cannot find module "./browser/algorithms.json"​​
​​at http://localhost:65529/____wallaby-bundle.js?1530790211865&wallabyFileId=bundle:135161​​
​​Module not found: Error: Can't resolve './lib-cov/SauceLabs' in 'xxxxxxxomittedxxxxxxxxx\node_modules\saucelabs'ModuleNotFoundError: Module not found: Error: Can't resolve './lib-cov/SauceLabs' in 'xxxxxxxomittedxxxxxxxxx\node_modules\saucelabs'​​
...etc...

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./apps/supply-x-angular2/tsconfig.spec.json').compilerOptions,
  require('./libs/reporting/tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['wallabyTest.js', 'apps/**/*spec.js', 'libs/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader', 'css-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        { test: /\.js$/, loader: 'shebang-loader', include: /node_modules/ },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'wallabyTest.ts', load: false },
      {
        pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'apps/**/*.d.ts', ignore: true },
      { pattern: 'apps/**/*spec.ts', ignore: true },
      {
        pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'libs/**/*.d.ts', ignore: true },
      { pattern: 'libs/**/*spec.ts', ignore: true },
      { pattern: 'browser/*.json', load: false }
    ],

    tests: [
      { pattern: 'apps/**/*spec.ts', load: false },
      { pattern: 'libs/**/*spec.ts', load: false },
      { pattern: 'apps/**/e2e/**', ignore: true },
      { pattern: 'libs/**/e2e/**', ignore: true }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```

**Comment by ArtemGovorov** [comment]
> Uncaught Error: Cannot find module "./browser/algorithms.json"​​

Does the file (`<project_dir>/browser/algorithms.json`) exist? Could you please search your codebase (and `node_modules`) to see where it it imported form?

> Module not found: Error: Can't resolve './lib-cov/SauceLabs' in 'xxxxxxxomittedxxxxxxxxx\node_modules\saucelabs'

Looks like something in your source code/tests imports `saucelabs`, maybe some e2e tests? In this case you'll need to exclude them from your `tests` list.

**Comment by TomWhiteOmni** [comment]
Hi @ArtemGovorov 

Really appreciate your help.

> Does the file (<project_dir>/browser/algorithms.json) exist? Could you please search your codebase (and node_modules) to see where it it imported form?

node_modules\browserify-sign\browser\     ...contains file...    algorithms.json   ...I suspect it's a dependency of a dependency, because it's not in package.json

> Looks like something in your source code/tests imports saucelabs, maybe some e2e tests? In this case you'll need to exclude them from your tests list.

Both the above dependency issues are automatically created when [Nwrl Nx](https://nrwl.io/nx/guide-nx-workspace) creates/scaffolds a workspace + app, so they're really outside my field - as an end user. I have noted that the app CLI generator creates a same-named e2e test app that may be creating part of the problem for Wallaby.

To help both of us from sniping questions, I've created a repo - using the most basic Nwrl Nx setup to prove the point. I'd really appreciate you taking a look:

[TomWhiteOmni / angular-nx-wallaby](https://github.com/TomWhiteOmni/angular-nx-wallaby)

If you could spin up Wallaby against it, you'll see that there is a list of other errors that follow on from these (that I'm hoping will clear up once the root cause is fixed).

Feel free to submit an update / pull request; it'd be great for the other Nwrl Nx 6.1.0 users to have an up to date repo with a working Wallaby config

Thanks a lot

Kind regards

Tom

**Comment by ArtemGovorov** [comment]
Hi @TomWhiteOmni , thank for sharing the repo! It's the fastest way to get things going. I have sent you the pull request with the config changes to make it work https://github.com/TomWhiteOmni/angular-nx-wallaby/pull/1.

As I was suspecting, e2e tests were included and were causing the issue, because webpack was (trying to) building them into the bundle. I have adjusted ignored `files`/`tests` patterns to reflect the project's structure and now it's working.

**Comment by TomWhiteOmni** [comment]
Thanks @ArtemGovorov !
All working now - both in the demo repo, and in my original project.
Really appreciate your rapid response.
What's your Twitter handle? I'd like to spread the word to other Nrwl Nx users. Mine's [@Angular2bes](https://twitter.com/Angular2bes)
Feel free to close this thread
Kind regards
Tom

**Comment by ArtemGovorov** [comment]
Thanks for the update @TomWhiteOmni, our Twitter handle is https://twitter.com/wallabyjs
