### ISSUE TITLE
wallaby-qunit-1.16.0.json in a folder rather than at the root for Visual Studio

### ISSUE THREAD

**Issue by saifmd4u** [wallabyjs/public#175]
I have moved wallaby-qunit-1.16.0.json in a folder such as "\wallaby\module1\wallaby-qunit-1.16.0.json" rather than at the root.

Wallaby is not able to identify the paths if i provide such as 

{
    "files": [
        "../../Scripts/require.js",
        "../../Scripts/jquery-1.11.0.js",
}

May be I might be missing something here.

**Comment by ArtemGovorov** [comment]
At the moment wallaby.js doesn't support relative paths in config, here is [the feature request](https://github.com/wallabyjs/public/issues/68). If you have multiple projects you may consider using [solution Items](https://github.com/wallabyjs/public/issues/153) for now.
