### ISSUE TITLE
Clicking on "Update Snapshot" in the output view does not update snapshot in VSCODE

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1752]
### Issue description or question

✅ When I click on "Update Snapshot" in hover -> Works
✅ When I click on "Show side-by-side-diff" in output -> Works
❗️When I click on  "Update snapshot" in output view -> Nothing Happens

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'tsconfig.json',
      'transformer.js',
      'jest.setup.js',
      'jest.config.js',
      //'jest.*',
      'test/*.js',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      '!src/**/tests/*.+(ts|tsx)',
      '!src/luis_app',
      '!src/**/index.ts'
    ],
    tests: ['!src/**/tests/index.ts', 'src/**/tests/*.+(ts|tsx)'],
    env: {
      type: 'node',
      runner: 'node'
    },
    preprocessors: {
      'src/**/*.tsx': file => require('jsx-controls-loader').loader(file.content)
    },
    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.25

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue unfortunately. Here's what I'm trying (in this sample repo https://github.com/wallabyjs/wallaby-jest-snapshots):

![jest](https://user-images.githubusercontent.com/979966/42415576-bccfae94-8296-11e8-96b8-28fbaef25b70.gif)

Could you please try the sample repo to see if the result is different for you?

**Comment by tomitrescak** [comment]
Ha! I tried insiders and it worked. Then I compared what is different and found out that the "snapshots extensions" package from asvetliakov was interfering. Upon uninstall of that package all works as expected.
