### ISSUE TITLE
Listen to snapshot being created in wallaby

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1753]
Hi, this is a kind feature request.

Do you think it would be possible to listen to snapshots being rendered by wallaby when working with jest?

I have a VSCODE extension that renders the contents of jest snapshots into custom view when snapshot is saved to disk (https://marketplace.visualstudio.com/items?itemName=Tomas.luis-snapshot-preview)

I would love to render also the last processed snapshot by wallaby. This would allow me to work on the component and dynamically render its current state. You are displaying the side-by-side diff, so it is laying somewhere in the memory I just do not know how to access it.

Would you consider giving out the possibility to access it?

Thanks!

**Comment by tomitrescak** [comment]
Nevermind ... I hacked into serialiser and made it work. Thanks.

**Comment by tomitrescak** [comment]
@ArtemGovorov not sure if you are interested, but I created a nice little companion for Wallaby, that allows to live preview your snapshots as you type. This can be really nicely used when developing new components.

Here is a preview. You can see that "snapshots" are being updated live as you type. By snapshots I mean the current state that is compared to the snapshots stored on drive.

![luis-live](https://user-images.githubusercontent.com/2682705/42417411-0ce16f40-82cd-11e8-90e5-cc601e34149f.gif)

Very easy to start:

1. Install [following extension in vscode](https://marketplace.visualstudio.com/items?itemName=Tomas.luis-snapshot-preview) - Please ignore the documentation for now as it needs to be updated.
2. In your project `yarn add jest-spy-serialiser`
3. In your jest startup file, e.g. `jest.config.js` just insert following `require('jest-spy-serialiser').registerSpy();`
4. In VSCode run "Luis: View Live snapshots"
5. Profit

The extension also renders stored snapshots via: "Luis: View Stored Snapshots" and if they are in HTML, it renders them nicely in your view

![luis-offline](https://user-images.githubusercontent.com/2682705/42417444-ccc77f98-82cd-11e8-9423-c62b01bf8e4e.gif)

This config works REALLY well with:

- Snapshots stored as HTML (e.g. via React and `react-test-renderer`)
- Works only when using `expect` package and `toMatchSnapshot`

For now, I manually insert `semantic-ui` as css there but this may all be configurable if community will show interest.

**Comment by ArtemGovorov** [comment]
@tomitrescak This looks great, thanks for sharing! We have retweeted it in our Twitter account. Do you have plans to maybe write a blog post about the extension?

**Comment by tomitrescak** [comment]
@ArtemGovorov thanks for the tweet ;) I probably will write blog post some time soon, but first I will battle test this extension on my current project.
