### ISSUE TITLE
[feature request] Add gitter chat

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#176]
Very helpful to provide help both in English  and Russian

**Comment by ArtemGovorov** [comment]
How about Slack?

**Comment by hellboy81** [comment]
OK

**Comment by hellboy81** [comment]
Вы для русскоговорящих делаете скидки? Или для Open-Source проектов? А то наше сеньор сказал, что 160 долларов - это довольно много. Хоть и фирма западная.

**Comment by ArtemGovorov** [comment]
We don't currently have any special program for OSS projects. Anyway, send me an email to wallabyjs@gmail.com with some more details about how many licenses your company needs, etc., will se what we can do.

**Comment by boneskull** [comment]
may want to create two separate channels

**Comment by szarouski** [comment]
:+1:

**Comment by hellboy81** [comment]
we, customers, are still waiting for live payed support in native language ;-)

**Comment by smcenlly** [comment]
We provide online chat via our [discord channel](https://wallabyjs.com/chat/).
