### ISSUE TITLE
Should non-instrumented files get compiled?

### ISSUE THREAD

**Issue by smozely** [wallabyjs/public#1760]
### Issue description or question
I'm just wondering if files that get marked as `instrument: false` should still be getting compiled by the specified compiler? ... Because they seem to not be, and I'm just trying to exclude some test library code from coverage reports, and wondering if this is the expected behaviour.

I can work around this with `filesWithNoCoverageCalculated` but I just end up having to specify a bunch of files twice.

**Comment by ArtemGovorov** [comment]
Non-instrumented files are not compiled by design.
