### ISSUE TITLE
Have the javascript examples ever worked?

### ISSUE THREAD

**Issue by msgirlperl** [wallabyjs/public#1761]
### Issue description or question
I am trying to run the javascript examples and it seems that all the src files are in ES6 module syntax and the examples are running in node and expect CommonJS. I started to make local changes to fix this but I'm realizing you may not want them because you it's code under the src directory and not the examples directory.  Is there an easy way to run the examples?  Have they ever worked?

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Atom v1.28.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Could you please specify what examples do you mean (that "are in ES6 module syntax and the examples are running in node and expect CommonJS")?

**Comment by msgirlperl** [comment]
The Javascript examples -

Modules are being imported with 'import' instead of 'require', and exported with the keyword export before each function instead of using module.exports.

Attempting to run the examples as specified in the README generates exceptions.

**Comment by ArtemGovorov** [comment]
Could you please share a link to a specific example repo that you are trying to run?

**Comment by msgirlperl** [comment]
https://github.com/dropbox/dropbox-sdk-js/tree/master/examples/javascript

**Comment by ArtemGovorov** [comment]
I'm a bit confused - the repo doesn't have any relation to Wallaby.js, also the examples folder doesn't have any tests (and Wallaby.js is a test runner).

**Comment by msgirlperl** [comment]
What in the world?  How did this end up here?  I'm not even familiar with Wallaby, sorry!
