### ISSUE TITLE
[Docs] Here's a sample config for Meteor apps

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#1764]
Together with @ArtemGovorov we were able to put together a simple wallaby config file for Meteor apps. 

You can find it here: https://gist.github.com/Floriferous/982f64b897fc114422464217abbce713

To do:
* Figure out how to make things work with meteor server-side tests that depend on a running instance of Meteor and its related `meteor/` packages.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for sharing! Have added the link to [the docs](https://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes).
