### ISSUE TITLE
Vue Cli 3 + mocha + typescript

### ISSUE THREAD

**Issue by phil-scott-78** [wallabyjs/public#1765]
### Issue description or question

When creating a new project using vue-cli (v3 rc5) with a Mocha + Chai project with Typescript Wallaby errors with 
`error: Error: Cannot find module '@/components/HelloWorld.vue'`

Regular tests work fine, it's just the parsing of the vue modules that is failing. Running `npx vue-cli-service test:unit` also succeeds. 

### Wallaby.js configuration file

Copied the config more or less from https://wallabyjs.com/docs/integration/vue.html but removed the part about configuring Jest

```javascript
module.exports = wallaby => {
    process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;
  
    return {
      files: ['src/**/*', 'package.json', 'tsconfig.json'],
  
      tests: ['tests/**/*.spec.ts'],
  
      env: {
        type: 'node',
        runner: 'node',
      },
  
      preprocessors: {
        '**/*.js?(x)': file => require('@babel/core').transform(
          file.content,
          {sourceMap: true, compact: false, filename: file.path})
      },
   
      testFramework: 'mocha',
  
      debug: true
    }
  }
```

I pushed the full project for reproduction to https://github.com/phil-scott-78/wallaby-mocha-typescript

### Code editor or IDE name and version

Visual Studio Code v1.25.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo.
I have sent you the [pull request with the working config](https://github.com/phil-scott-78/wallaby-mocha-typescript/pull/1). Basically the idea is to use `tsconfig-paths` module to map Vue modules to `@/**` and `vue-jest` module to compile Vue files.

**Comment by phil-scott-78** [comment]
wonderful, that worked. Using `vue-jest` threw me off there. Might be nice to add this example to the docs. Until then I'll leave me repo up and hopefully others with the same issue as me can discover it.

thanks again for the super quick turnaround and explanation of the fix.
