### ISSUE TITLE
Display which tests call a particular code statement

### ISSUE THREAD

**Issue by acorretti** [wallabyjs/public#1766]
### Feature Request description

It'd be fantastic for Wallaby to show which tests are calling a particular code statement.

For example, when hovering and staying on top of a coverage indicator in VSCode gutter, if a tooltip showed the first line (usually containing the test name) of tests running that line.

Thank you!

**Comment by ArtemGovorov** [comment]
The feature does exist (unfortunately not as a tooltip, because VS Code API doesn't support it). You may use [`Show line test(s)` command](https://wallabyjs.com/docs/intro/get-started-vscode.html#commands) to display all tests covering any particular line of code.

**Comment by bj97301** [comment]
This isn't as user-friendly as it could be IMO.  What if when clicking on the green/red gutter thing it rand the show line test(s) command?

**Comment by ArtemGovorov** [comment]
@bj97301 Agreed, it'd be cool, and indeed in JetBrains IDEs and Atom Wallaby doing exactly that on the gutter icons clicks - showing the related tests. Unfortunately VS Code API doesn't expose a way to handle on click events for the gutter.

**Comment by ArtemGovorov** [comment]
> Right click?

Not possible either unfortunately.

> maybe right click in the editor.

This is possible. We've just added the command as editor context action and released the feature in v1.0.101.
