### ISSUE TITLE
Speed issue with semantic-is-react

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1767]
### Issue description or question

Hi, i am getting the complaint that my test are taking over 5seconds to execute with jest. I found the culprit being the import of semantic-ui-react Library. Now almost every time I re-run my test I have to wait 15+ seconds for test to run. Mocking the Library brings down the test startup to pleasant 2 seconds. Mocking is not possible though as it would mess up my snapshots. Is there any way I can speed it up? Is it maybe somehow instrumented? sUI is a chunky 600kb basterd.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Please create a sample repo so we could run it and investigate the issue.

**Comment by tomitrescak** [comment]
@ArtemGovorov this is our project repo https://github.com/tomitrescak/corporator I made it public for now. It's very early work. Jest was quite swift up until recent when we discovered a major drop in performance. We attribute it to semantic-ui-react.

**Comment by ArtemGovorov** [comment]
Thanks for the repo link. Unfortunately I'm not able to even start a test run. The `wallaby.js`/`wallaby.server.js` config doesn't run any tests (because there are no tests in the server folder), `wallaby.data.js` throws config error, `wallaby.client.js` throws `connect ECONNREFUSED` error from `corporator/node_modules/jest-spy-serialiser`.

**Comment by tomitrescak** [comment]
Please just comment out the line // require('jest-spy-serialiser').registerSpy();
in jest.config.js ... this is something internal.

**Comment by ArtemGovorov** [comment]
Thanks, got it running now. What test takes a long time to run? I have tried editing a couple of test files (`src/client/modules/email/views/tests/email_view.test.js`, `src/client/modules/form/models/tests/form_model.test.js`), and the feedback is almost instant.

**Comment by tomitrescak** [comment]
So, when I only do slight changes feedback is almost instant. But every few seconds, when I type something more complex than it seems that it starts from scratch and then it takes 10-15 seconds to execute test. So if I'm lucky I have a stream of 1-2 minutes with instant feedback, when I'm not lucky, almost after every change I have to wait 10-15 seconds. I know that this is the worlds worst problem description so I'll try to create something reproducible.

**Comment by smcenlly** [comment]
Closing this issue for now as we don't have a sample to replicate the problem. We will re-open the issue if more detail is provided.
