### ISSUE TITLE
Zone is needed for the async() test helper

### ISSUE THREAD

**Issue by dudewad** [wallabyjs/public#1768]
### Issue description or question
This is an Angular 6.x project, testing via Karma/Jasmine

I'm not sure if this is an issue with Wallaby or not, but my tests work when running them outside of Wallaby so I think this may be a config issue...?

Anyways, when running my tests, I get the following error in any tests attempting to use `async`:
```
Failed: Zone is needed for the async() test helper but could not be found.
Please make sure that your environment includes zone.js/dist/zone.js
```

I have searched for hours but not found a solution. I feel like Zone needs to be included globally via Wallaby settings somehow because the tests run fine when I run the Angular standard test runner.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions);

// compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/**/*.spec.js',
      'libs/**/*.spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ],
      alias: {
        'atlas-lib': path.resolve(wallaby.projectCacheDir, 'libs/atlas-lib/src/public_api'),
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.spec.ts', ignore: true },
      { pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'libs/**/*.d.ts', ignore: true },
      { pattern: 'libs/**/*.spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.spec.ts', load: false },
      { pattern: 'libs/**/*.spec.ts', load: false },
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

IntelliJ IDEA Ultimate 2018.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Looks like there's a helper file (that loads zone.js and bootstraps angular testing) is missing in the `entryPatterns`.

This should help:
- create an `src/wallabyTest.ts` file, like in [this sample repo](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) that was generated from Angular CLI. If you have the `src/polyfills.ts` file in your project (that `src/wallabyTest.ts` imports), then it is sufficient. If you don't have the file, then you may include zone.js import right in your `src/wallabyTest.ts` file ([this import](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/polyfills.ts#L74) and maybe [this as well](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/polyfills.ts#L46))
- add it to your `entryPatterns` like [done here](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L14) (note it needs to be included as `.js`, even though the file itself is `.ts`).

**Comment by dudewad** [comment]
@ArtemGovorov Thanks this saves me. It's interesting though, that putting `wallabyTest.js` in the root (above `src`) with correct path references still breaks. Putting it in `src` fixes it. Do you know why that is?

**Comment by dudewad** [comment]
Excellent thanks. Webpack configs have always eluded me!!

**Comment by ThatSpaceGuy** [comment]
Hello I am experiencing the same `Zone is needed for the async() test helper but could not be found.
Please make sure that your environment includes zone.js/dist/zone.js` error - however, I am attempting to run Wallaby.js without webpack.  How can I make sure `zone` is included in the environment?

**Comment by smcenlly** [comment]
@ThatSpaceGuy can you please confirm whether you tried [these steps mentioned above](https://github.com/wallabyjs/public/issues/1768#issuecomment-408644132)? If so, can you please provide us with your wallaby.js config file?

**Comment by ThatSpaceGuy** [comment]
Pardon my lack of experience, but where would I include the `entryPatterns` property if I am not using webpack?  Here is my current wallaby.js config file:

`const compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  return {
    files: [
      'tsconfig.json',
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)'},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts'},
      {pattern: 'src/**/*e2e-spec.ts'}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      type: 'node',
      kind: 'chrome'
    },

    setup: function (wallaby) {
      if (global._tsconfigPathsRegistered) return;
      const tsConfigPaths = require('tsconfig-paths');
      const tsconfig = require('./tsconfig.json');
      tsConfigPaths.register({
        baseUrl: tsconfig.compilerOptions.baseUrl,
        paths: tsconfig.compilerOptions.paths
      });
      global._tsconfigPathsRegistered = true;
    },

    debug: true
  };
};
`

**Comment by ArtemGovorov** [comment]
@ThatSpaceGuy If you are not using Webpack, you may specify/require any files that you need to run prior to your tests in your `setup` config function. So just like you currently have `require('tsconfig-paths')` it the setup function, you may add `require('./src/wallabyTest')` (just make sure the `wallabyTest` file is there).

However, I think there are some other issues with your config that you'll need to fix:
- you seem to be running your tests in node, but had also specified `chrome`, and it either has to be  node or browser/chrome. Where/how are you running your tests without wallaby?

**Comment by ThatSpaceGuy** [comment]
Thanks very much, @ArtemGovorov - adding the `require` statement worked to solve the error that this thread is named for.  

I realize that we are now leaving the scope of this post moving beyond this error thread, please let me know if you prefer we move this discussion to a different thread.  

To answer your last question:  We had been running our tests in Karma/Jasmine using Chrome Headless.  Our team recently implemented Wallaby.js using electron and webpack.  The problem came when certain tests raised `alert`s which needed to be manually dismissed by clicking okay.  I was attempting to switch over to a Chrome Headless implementation of wallaby to keep from having to refactor older code, and maybe even keep from importing electron into the project (but that's a lesser goal).  Admittedly, I've been piecing together my `wallaby.js` as I've run into error after error.

**Comment by ThatSpaceGuy** [comment]
Update:  I am pushing forward with `kind: 'chrome'`, but I keep running into errors like this:

```[Info]​​​​​ Tue, 04 Sep 2018 19:12:52 GMT wallaby:workers Sandbox (active) [oi25u] error: Uncaught ReferenceError: exports is not defined
​​[Error] Runtime error: Uncaught ReferenceError: exports is not defined​​
​​[Error] at http://localhost:61674/src/app/app.module.js?1536088353195&wallabyFileId=16:17​​
```

Any tips?

**Comment by ThatSpaceGuy** [comment]
Ah - thank you for explaining that, @ArtemGovorov.  Is it possible to use Chrome Headless with Webpack?

**Comment by ArtemGovorov** [comment]
> Is it possible to use Chrome Headless with Webpack?

@ThatSpaceGuy Yes it is, the [readme file explains how](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/README.md).

**Comment by ThatSpaceGuy** [comment]
Thank you @ArtemGovorow, I could have sworn I tried that at first and after researching found I needed to choose between Chrome Headless and Webpack.  I must have done something wrong initially, as it seems to be working now.  Thank you for your product and your patience with me!
