### ISSUE TITLE
Showing errors in Angular HTML templates

### ISSUE THREAD

**Issue by sgronblo** [wallabyjs/public#1769]
### Issue description or question

This is kind of a support request. I couldn't find anything about whether this is even possible in the docs.

I was able to set up wallaby with a newly created Angular 6 project to show me test failures inside my spec files. However the most error prone part in Angular is usually the templates so I was wondering if Wallaby has any support for showing the red squares inside the HTML template files' expressions.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Wallaby only instruments JavaScript/TypeScript files. Having said that, it may be possible to [create a custom compiler](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler) (by anyone, maybe as an OSS project) that will display code coverage inside expressions for HTML files.
