### ISSUE TITLE
run test for angular with ava in node context without karma (jsdom)

### ISSUE THREAD

**Issue by andrewvmail** [wallabyjs/public#1770]
I have gotten Ava working with backend code with Wallaby and its awesome, right now I'm experimenting trying to get Ava working with angular on the frontend. I know its a little bit of a stretch doing it this way but what the heck maybe it works. If it does this would be awesome, faster test. 

I think it's almost there.

I cloned your repo and made some changes so it would run with ava. I brought in window with ```require('browser-env')(); //jsdom```

But having some issue with angular testing framework.

```
 TestBed.configureTestingModule({
    declarations: [AppComponent]
  }).compileComponents();
// DomException here
```
https://github.com/andrewvmail/ngCliWebpackSample/blob/master/src/app/app.component.spec.ts

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo.

Is Ava CLI (without Wallaby) working, or the issue is not Wallaby specific? 

I think it should be possible, because Angular apps can be tested with Jest (that runs in node and is using jsdom). Here is how they do it https://github.com/thymikee/jest-preset-angular/blob/master/setupJest.js.

**Comment by andrewvmail** [comment]
@ArtemGovorov, issue seems to be not wallaby specific. And thanks for the direction now i'm closer to the finish line! Just one more hurdle now. https://github.com/thymikee/jest-preset-angular/blob/master/preprocessor.js i need to turn this preprocessor into the wallaby version. 

I checked out the docs on preprocessing https://wallabyjs.com/docs/config/preprocessors.html im not sure how to take the content of the html and inject it to the js. 

so far i have this to start with.
```
 '**/*.html': (file, done) => {
  file.content = file.content.replace(ESCAPE_TEMPLATE_REGEX, '\\$1');
  
  // take html and inject it into js

  //file.content = file.content
    //.replace(TEMPLATE_URL_REGEX, 'template: require($1./$3$4)')
    //.replace(STYLE_URLS_REGEX, 'styles: []');
  
  done(file.content + '// modified')
  //return process(src, path, config, transformOptions);
}
```

**Comment by andrewvmail** [comment]
Thank you Artem. Everything i needed was in setupJest.js link you pointed me to. But i had to trace the last piece here https://github.com/kulshekhar/ts-jest/blob/master/src/preprocessor.ts#L31-L33

My final config for anyone who is interested doing the same thing.

```
var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

const TEMPLATE_URL_REGEX = /templateUrl\s*:\s*('|")(\.\/){0,}(.*)('|")/g;
const STYLE_URLS_REGEX = /styleUrls\s*:\s*\[[^\]]*\]/g;
const ESCAPE_TEMPLATE_REGEX = /(\${|\`)/g;

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.html',
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: true},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [{ pattern: "src/**/*.spec.ts", load: true }],

    env: { type: "node", runner: "node" }, testFramework: "ava", debug: true,

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions),
    },
    preprocessors: {
      '**/*.ts': (file, done) => {
        // from https://github.com/thymikee/jest-preset-angular/blob/master/setupJest.js
        file.content = file.content
          .replace(TEMPLATE_URL_REGEX, 'template: require($1./$3$4)')
          .replace(STYLE_URLS_REGEX, 'styles: []');
        done(file.content + '//modified')
      },
      '**/*.html': (file, done) => {
        if(file.path.endsWith('index.html')) {
          return done(file.content)
        }
        file.content = file.content.replace(ESCAPE_TEMPLATE_REGEX, '\\$1');
        file.content = 'module.exports=`' + file.content  + '`;'
        done(file.content + '//modified')
      },
    },
    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! and for sharing the config!
