### ISSUE TITLE
Wallaby throws Error: Cannot find Jest test runner

### ISSUE THREAD

**Issue by felixmosh** [wallabyjs/public#1771]
### Issue description or question
Wallaby throws `Error: Cannot find Jest test runner` with the latest **Jest@23.4.2**.
Downgrading jest to version 23.4.1 solves.
### Wallaby.js configuration file

```javascript
module.exports = function () {

  return {
    files: [
      'tsconfig.json', // <--
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version

WebStorm 2018.2

### OS name and version

OSX

```
Failed to initialize wallaby jest.
Error: Cannot find Jest test runner
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by cjanietz** [comment]
It did not work for me using only jest 23.4.1 either. Not exactly sure why, but adding jest-cli 23.4.1 to my dependencies solved it.

**Comment by felixmosh** [comment]
@cjanietz, yeah you are right I needed to downgrade both, jest-cli & jest.

**Comment by ArtemGovorov** [comment]
Support for Jest 23.4.2 has been added and published in the [latest Wallaby core version v1.0.609](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by dicarlo2** [comment]
@ArtemGovorov I'm still seeing this issue with `Wallaby.js App v1.0.40, Core v1.0.609` on vscode.

**Comment by thehig** [comment]
I also have this issue with the latest Wallaby & vscode.

`yarn add jest-cli@23.4.1 jest@23.4.1 --dev` Fixed it for me (didn't work without jest-cli)

**Comment by ArtemGovorov** [comment]
Could you please share your package.json `devDependencies` and package-lock.json/yarn.lock file?

**Comment by ArtemGovorov** [comment]
Please also try [core v1.0.610](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
