### ISSUE TITLE
XML file gets corrupted when copying

### ISSUE THREAD

**Issue by sgronblo** [wallabyjs/public#1774]
### Issue description or question

I have an xml file defined like this in wallaby.js

`{ pattern: 'spec/assets/school-sample.xml', binary: true }`

If I make any change to the file I seem to end up with a corrupted file in the wallaby plugin cache directory. I noticed there is already many other issues about this for other file types. Is this really a problem you want to fix one by one for each file format?

Could you go into more detail about what this means too?

> The binary boolean property (false by default) tells wallaby whether the file is binary (this affects how the file get copied to wallaby cache).

More specifically, how is the copying different for the two?

Also, am I supposed to have to restart wallaby every time I change the config file?

After the file gets corrupted I have to restart Wallaby to get the updated file contents to be available.

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
> I have an xml file defined like this in wallaby.js

Please remove the `binary` flag, XML files are text files so the flag is not required.

> Also, am I supposed to have to restart wallaby every time I change the config file?

Yes.

**Comment by sgronblo** [comment]
If I remove the binary flag, the encoding of the file gets corrupted.

**Comment by ArtemGovorov** [comment]
> If I make any change to the file I seem to end up with a corrupted file in the wallaby plugin cache directory.

And in what way does it get corrupted with the `binary` flag?

Could you please share an example of a file and your IDE/editor version? We'll try to reproduce the issue locally.
