### ISSUE TITLE
The extension manifest is invalid

### ISSUE THREAD

**Issue by gxomin** [wallabyjs/public#1777]
### Issue description or question
Trying to install wallaby-vs-2017-v1.0.33.vsix, got error dialog:
The extension manifest is invalid

### Code editor or IDE name and version

Visual Studio Professional 2017
Versionm 15.6.4

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
It is most likely an issue with your VS.

Please try the following:

- Try installing [any other VS extension](https://marketplace.visualstudio.com/search?target=VS&category=Tools&vsVersion=&subCategory=All&sortBy=Downloads) to see if it gets installed.
- Try running the `wallaby-vs-2017-v1.0.33.vsix` installer as Administrator.
- Try to `Repair` your VS instance (Program and Features - VS2017 - Change context menu).

![screenclip](https://cloud.githubusercontent.com/assets/979966/9372779/f56ee472-4725-11e5-817e-59b83e093f7b.png)

Let us know how it goes.

**Comment by ArtemGovorov** [comment]
If the solution suggested above doesn't help, please try the following:

- Open `c:\Users\%user%\AppData\Local\Temp\`.
- Delete all files looking like `VSIXInstaller_someGUID.log`.
- Close all Visual Studio instances, run `wallaby-vs-2017-v1.0.33.vsix`.
- Now there should be the only `VSIXInstaller_someGUID.log` in `c:\Users\%user%\AppData\Local\Temp\`, paste its full content here.
