### ISSUE TITLE
Issue running typescript via wallaby but works via jest

### ISSUE THREAD

**Issue by bbugh** [wallabyjs/public#1783]
### Issue description or question

Hi again, we're adding typescript to our project, and have everything working except I'm having trouble getting wallaby working. Jest is working fine run from the command line.

I'm having the same problem as [the last issue I created](https://github.com/wallabyjs/public/issues/1757) which you helped fix before, and I'm confused why it's reappeared!

My files are all still the same as [the last issue here](https://github.com/wallabyjs/public/issues/1757) except jest has the loader lines for typescript:

```diff
@@ -87,11 +92,13 @@
     "moduleFileExtensions": [
       "js",
       "json",
+      "ts",
       "vue"
     ],
     "testRegex": "(/test/.*|\\.(test|spec))\\.(ts|tsx|js)$",
     "transform": {
       "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
+      "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor",
       ".*\\.(vue)$": "<rootDir>/node_modules/vue-jest"
     },
```

Jest error when wallaby runs:
```
Details:​​
​​​​
​​/Users/bbugh/XXXXXXXX/XXXXXX/XXXXXXXXXXXXXX/node_modules/lodash-es/startCase.js:1​​
​​({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import createCompounder from './_createCompounder.js';​​
​​                                                                                         ^^^^^^​​
​​​​
​​SyntaxError: Unexpected token import​​
  at Object.<anonymous> ​app/javascript/config/filters.js:4​
  at Object.<anonymous> ​app/javascript/spec/unit/config/filters.spec.js:1​
```

Where it's failing:

```javascript
/** @module filters */

import Vue from 'vue'
import startCase from 'lodash-es/startCase'
import toLower from 'lodash-es/toLower'
```

### Wallaby.js configuration file

```javascript
// this is the same as the example typescript config except for "files" and "tests"
module.exports = wallaby => {
  return {
    files: [
      'app/javascript/**/*',
      '!app/javascript/**/*.spec.js',
      '!app/javascript/**/*.spec.ts',
      'package.json',
      'tsconfig.json'
    ],

    tests: ['app/javascript/**/*.spec.js', 'app/javascript/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          plugins: ['transform-es2015-modules-commonjs']
        })
    },

    setup (wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config')
      delete jestConfig.transform['^.+\\.tsx?$']
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',

    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code 1.25.1 (1.25.1)

### OS name and version

OSX 10.12.6 (16G1408)

**Comment by ArtemGovorov** [comment]
Wallaby Babel compiler for JavaScript automatically sets `BABEL_ENV` to `test`, however because you've switched to TypeScript and removed the compiler from the config, babel specific `BABEL_ENV` is not set anymore, and with your `.babelrc` the `transform-es2015-modules-commonjs` is applied only under `test`.

All you need to do is to let Wallaby know what environment Babel (when ran by Jest) should be using:

```diff
+process.env.BABEL_ENV = 'test';
module.exports = wallaby => {
  return {
    ...
```

After adding the environment setting, you should also be able to simplify your preprocessor:

```diff
    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
-         plugins: ['transform-es2015-modules-commonjs']
+         babelrc: true
        })
    },
```

Hope it makes sense.

**Comment by bbugh** [comment]
Ah ha, thank you for the explanation, that makes sense. I think it clarifies some of the past confusion I had as well.

Your solution works perfectly as always! Thanks @ArtemGovorov!
