### ISSUE TITLE
Issues with lodash while running wallaby

### ISSUE THREAD

**Issue by jbprat** [wallabyjs/public#1785]
### Issue description or question
I am trying to run Wallaby with Visual Studio on my project with a project that uses lodash. 
It was running fine a couple weeks ago, and suddenly, when I run it I keep having issues related to lodash with test failing with this single issue: `Failed: lodash_1.set is not a function​​`.

I am using nvm, so I had to add a specific settings in my vs code setting: `"wallaby.node": "/Users/jean-baptiste/.nvm/versions/node/v10.2.1/bin/node"`

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/main/webapp/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/main/webapp/wallabyTest.js',
      'src/main/webapp/app/**/*spec.js'
    ],

    module: {
      rules: [
        { test: /\.css$/, use: [{ loader: 'raw-loader' }] },
        { test: /\.html$/, use: [{ loader: 'raw-loader' }] },
        { test: /\.js$/, use: [{ loader: 'angular2-template-loader'}], exclude: /node_modules/  },
        { test: /\.json$/, use: [{ loader: 'json-loader' }] },
        { test: /\.styl$/, use: [{ loader: 'raw-loader' }, { loader: 'stylus-loader' }] },
        { test: /\.less$/, use: [{ loader: 'raw-loader' }, { loader: 'less-loader' }] },
        { test: /\.scss$|\.sass$/, use: [{ loader: 'raw-loader' }, { loader: 'sass-loader' }] },
        { test: /\.(jpg|png)$/, use: [{ loader: 'url-loader?limit=128000' }]  }
      ]
    },

    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src/main/webapp/app'),
        path.join(wallaby.projectCacheDir, 'src')
      ],
      alias: {
        '@angular-redux/store/testing': path.resolve(__dirname, 'node_modules/@angular-redux/store/lib/testing/index.js')
      }
    }
  });


  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/main/webapp/main.ts', ignore: true },
      { pattern: 'src/main/webapp/test.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.less', load: false },
      { pattern: 'src/**/*.scss', load: false },
      { pattern: 'src/**/*.sass', load: false },
      { pattern: 'src/**/*.styl', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*.json', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.spec.ts', load: false },
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron',
      runner: require('electron') // <-- will set the correct path
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.25.1

### OS name and version
OSX 10.13.6

**Comment by ArtemGovorov** [comment]
It is possible that there's some older version of lodash installed somewhere on the webpack module resolution paths. 

Please try: 
- clone [this sample project](https://github.com/wallabyjs/ngCliWebpackSample), `npm i`, `npm i lodash`, then import lodash to the [sample test](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/app/app.component.spec.ts) to see if the error shows up (for example by adding `require('lodash').set//?` to any of the tests).
- check the following folders and remove any `node_modules` in them:
  - `/Users/jean-baptiste/.vscode/extensions`
  - `/Users/jean-baptiste/.vscode`
  - `/Users/jean-baptiste`
  - `/Users`
  - `/`

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by ArtemGovorov** [comment]
Though, `/Users/jean-baptiste/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.92/node_modules/` shouldn't have any `lodash` module version in it, so I'm wondering how this could possibly help.

**Comment by jbprat** [comment]
Actually, I removed one node_modules at my Users/Jean-Baptiste level, but the test weren't running. Maybe that did the trick too after I restarted my editor.

-------- Message d'origine --------

**Comment by ArtemGovorov** [comment]
> Maybe that did the trick too after I restarted my editor.

Ah, makes sense then.
