### ISSUE TITLE
"Show assertion data diff" missing

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#179]
The context menu does not show the "Show assertion data diff" in IntelliJ.
<img width="422" alt="context_menu" src="https://cloud.githubusercontent.com/assets/963136/8507753/c54029ea-2250-11e5-802f-827b9a7b53d5.png">

Does it matter from what line or file I request the context menu?
Core version is 1.0.73, plugin version is 1.0.24.

NB: The "Run project tests" action is not described in the [docs](http://wallabyjs.com/docs/intro/get-started-jetbrains.html).

**Comment by ArtemGovorov** [comment]
For Jasmine framework, the action is displayed only for `toEqual` matcher. It's also not displayed for boolean or numbers (because the difference is obvious without diff window).

> The "Run project tests" action is not described in the docs.

Thanks, added the description.
