### ISSUE TITLE
Seperate Wallaby config for every lib in Nx monorepo

### ISSUE THREAD

**Issue by Timebutt** [wallabyjs/public#1790]
### Issue description or question
I'm currently trying to add per-library Wallaby configurations in our huge monorepo. We have a global `wallaby.js` file that runs all the tests, and does so very well, but because of the size of the application we want to have a `wallaby.js` configuration per library, and per application. It makes no sense to run the entire suite if you're working on one part of the monorepo.

This is the structure of our Nx monorepo:

```
main folder
  node_modules
  apps
    application-1
      wallaby.js (for application-1 only)
    application-2
      wallaby.js
  libs
    library-1
      wallaby.js (for library-1 only)
    library-2
      wallaby.js 
  wallaby.js (main config file)
```

This is the error output I get when starting Wallaby with the `apps/*specific_app*/wallaby.js` configuration:

```
[Info]​​​​​ Started Wallaby.js Core v1.0.610
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] Runtime error: Failed to initialize wallaby jest.​​
​​[Error] Error: Cannot find Jest test runner​​
​​[Error]     at Module._compile (module.js:635:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:646:10)​​
​​[Error]     at Module.load (module.js:554:32)​​
​​[Error]     at tryModuleLoad (module.js:497:12)​​
​​[Error]     at Function.Module._load (module.js:489:3)​​
​​[Error]     at Module.require (module.js:579:17)​​
​​[Error]     at require (internal/module.js:11:18)​​
​​[Error]     at Module._compile (module.js:635:30)​​
​​[Error]     at Object.Module._extensions..js (module.js:646:10)​​
​​[Error]     at Module.load (module.js:554:32)​​
​​[Error]     at tryModuleLoad (module.js:497:12)​​
​​[Error]     at Function.Module._load (module.js:489:3)​​
​​[Error]     at Function.Module.runMain (module.js:676:10)​​
​​[Error]     at startup (bootstrap_node.js:187:16)​​
​​[Error]     at bootstrap_node.js:608:3​​
```

I think this is because `Wallaby` is looking for `Jest` in the `node_modules` folder, but because the relation of `wallaby.js` to `node_modules` is different here (normally they are on the same level) the runner won't start!
Is there a way of specifying in the `wallaby.js` config where the `node_modules` are located?

Also weird: I had to use `wallaby.localProjectDir` to correctly `require` the `jest.config.js` file we use. Just using `require('../../config.js')` generates a `module not found` error. Is this the correct syntax to use in our situation?

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*.d.ts', ignore: true },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.less', load: false },
            { pattern: 'src/**/*.html', load: false },
            { pattern: 'src/**/*.spec.ts', ignore: true }
        ],
        filesWithNoCoverageCalculated: ['src/environments/**/*.ts', '../../jest/**/*.ts'],
        tests: ['src/**/*spec.ts'],
        env: {
            type: 'node',
            runner: 'node'
        },
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' })
        },
        testFramework: 'jest',
        setup: function(wallaby) {
            const jestConfig = require(wallaby.localProjectDir + '../../jest.config.js');
            wallaby.testFramework.configure(jestConfig);
        },
        debug: false
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.25.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
There are 2 options:

- Moving your lib specific configs to the project's root (with adjusting the paths inside them), like `wallaby-app-1.js`, etc.
- Specifying Jest module path in your nested Wallaby configs:

```diff
module.exports = function config(wallaby) {
  ...
  return {
    ...
-   testFramework: "jest"
+   testFramework: {
+     type: 'jest',
+     path: require('path').resolve(__dirname + '/../../node_modules/jest')
+   }
```

> Also weird: I had to use `wallaby.localProjectDir` to correctly `require` the `jest.config.js` file we use. Just using `require('../../config.js')` generates a `module not found` error. Is this the correct syntax to use in our situation?

With the nested Wallaby configs it is the correct way (because the file is outside the Wallaby cache).

**Comment by Timebutt** [comment]
Hi @ArtemGovorov, I've only just found time to get back to this as other more important stuff got in the way. Thanks for you reply, but configuring it using your second method only brings me to the next error thrown at Wallaby start-up time:

```
[Error] Error: Cannot find module 'jest-util/build/install_common_globals
```

For completeness: `jest-cli` is installed in my repo top level `node_modules`, and the `install_common_globals.js` it is requesting is available at the same path relative to the `jest-cli` folder.

How can I overcome this issue?

**Comment by ArtemGovorov** [comment]
Hi @Timebutt, thanks for the report. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.

**Comment by Timebutt** [comment]
As always: I'm amazed at the quality and timeliness of your replies @ArtemGovorov. Makes me very happy for using Wallaby.js, thank you! ;)

**Comment by nathanvale** [comment]
I am also trying to achieve the second method however I am getting this error when targetting jest 24.8.0

[Error] Failed to load configuration file: Test framework [jest@0.4.3] is not supported 

```
  testFramework: {
     type: 'jest',
    path: require('path').resolve(__dirname + '/../../node_modules/jest')
  }
```

**Comment by ArtemGovorov** [comment]
@nathanvale You are likely missing `env` setting:

```diff
+ env: {
+   type: 'node'
+ },

  testFramework: {
     type: 'jest',
    path: require('path').resolve(__dirname + '/../../node_modules/jest')
  }
```
