### ISSUE TITLE
Cannot find module when no extension is specified

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#1795]
I'm getting the error:
```
​​Error: Cannot find module '../app/src/api' from 'api.test.js'​​
```

If I add the extension to the `import` statement like this `'../app/src/api.js'` the error disappears and it happens for every other file.

I've been looking for an option to add in order to support this kind of importing syntax because is important for my team in terms of consistency but I can't find any related docs.

### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
    const path = require('path');

    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(
            __dirname,
            'node_modules/<path>'
        );
    require('module').Module._initPaths();

    return {
        files: [
            'app/**/.+(js|jsx|json|snap|scss|jpg|jpeg|gif|png|svg)',
            'test/mocks/**/*.js',
            '!test/**/*.test.js?(x)',
        ],
        tests: ['test/**/*.test.js?(x)'],
        env: { type: 'node', runner: 'node' },

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel({
                babel: require('babel-core'),
                presets: ['react-app'],
            }),
        },
        setup: wallabyTest => {
            const jestConfig = require('<path>')(
                p => require.resolve(`<path>/${p}`)
            );
            Object.keys(jestConfig.transform || {}).forEach(
                k =>
                    ~k.indexOf('^.+\\.(js|jsx') &&
                    void delete jestConfig.transform[k]
            );
            delete jestConfig.testEnvironment;
            wallabyTest.testFramework.configure(jestConfig);
        },
        testFramework: 'jest',
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.26.0

### OS name and version

macOS

**Comment by ArtemGovorov** [comment]
The only issue I can see is that your `files` pattern is incomplete (`*` is missing):

```diff
-'app/**/.+(js|jsx|json|snap|scss|jpg|jpeg|gif|png|svg)',
+'app/**/*.+(js|jsx|json|snap|scss|jpg|jpeg|gif|png|svg)',
```

I have created this sample repo: https://github.com/ArtemGovorov/wallaby-1795 with your config (and my fix for the pattern), and it is working for me. Try the fix and if it doesn't help, please add the bits I'm missing to reproduce the issue in the sample repo.

**Comment by davegomez** [comment]
Thank you for your response Artem, this indeed fixed the issue with the files so you should consider fixed the example where I got the code from because it doesn't have the `*` either.

As a follow up question now I'm getting an Enzyme error when I run the tests. I already checked my Jest setupFiles config as you suggest in the issue #1483 and I'm importing the `./test/spec_helper.js` where I have the Enzyme adapter configuration.

```js
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

I know this works because my tests run correctly from the command line and I have the dependencies on the last version available.

The error I'm getting for every test using Enzyme is this:

```bash
  ​​​​formatter formatterFunction should format the value​​​​ ​​​[11 ms]​​​​
    ​​​​
    ​​Error: ​​
    ​​      Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.​​
    ​​      To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`​​
    ​​      before using any of Enzyme's top level APIs, where `Adapter` is the adapter​​
    ​​      corresponding to the library currently being tested. For example:​​
    ​​​​
    ​​      import Adapter from 'enzyme-adapter-react-15';​​
    ​​​​
    ​​      To find out more about this, see http://airbnb.io/enzyme/docs/installation/index.html​​
    ​​    ​​
      at Object.it ​test/utils/formatter.test.js:32:12​
```

**Comment by ArtemGovorov** [comment]
> Thank you for your response Artem, this indeed fixed the issue with the files so you should consider fixed the example where I got the code from because it doesn't have the `*` either.

Where have you copied the example from? AFAIK, we only have the CRA config example in one place in our docs: https://wallabyjs.com/docs/integration/react-jsx.html, and it had always had the `*` in the path.

**Comment by davegomez** [comment]
You are right, I must removed it when I was customizing the path.
