### ISSUE TITLE
При изменении тестируемого файла приходится перезагружать Wallaby, иначе он не видит изменений

### ISSUE THREAD

**Issue by YadrovSergey** [wallabyjs/public#18]
Проблема показана на картике

![2015-02-23_21-07-06](https://cloud.githubusercontent.com/assets/4640119/6333740/9f17601a-bba0-11e4-8752-171dd47611e6.png)

**Comment by RubaXa** [comment]
Наблюдал эту проблему при одновременно двух запущенных wallaby: http://recordit.co/PNz9AYaGwh

**Comment by ArtemGovorov** [comment]
@YadrovSergey на скриншоте номер 2 правится тест для функции sum, а на скриншоте номер 3 правится функция sum2, которая видимо не покрывается этим тестом. Работает ли если править функцию sum в app.js? Или проблема не в этом?

**Comment by ArtemGovorov** [comment]
@RubaXa да, действительно - при двух запущенных проектах с wallaby проблема воспроизводится в том, который был запущен вторым - будем лечить.

@YadrovSergey Может у вас тоже запущено 2 проекта с wallaby? Или проблема воспроизводится на чем-то другом?

**Comment by ArtemGovorov** [comment]
@RubaXa @YadrovSergey проблема при двух запущенных проектах пофиксена. Если она будет воспроизводиться при этих или других условиях - дайте знать пожалуйста.

**Comment by ArtemGovorov** [comment]
Reproduced and fixed the issue, was reported by another user as well. Turned out to be a combination of require.js caching and Windows paths.
