### ISSUE TITLE
Support for Jest 0.5

### ISSUE THREAD

**Issue by endragor** [wallabyjs/public#180]
Jest 0.5 is going to finally drop node 0.10 dependency and work only on io.js. It's scheduled to be released on August 1st. For the time being it's available in their `0.5.x` branch.

**Comment by ArtemGovorov** [comment]
Added Jest 0.5 support (for the current state of `0.5.x` branch), core 1.0.74.

If you'd like to use it now, you may install the latest jest-cli (`npm install facebook/jest#0.5.x`) and in you wallaby config use `testFramework: 'jest'` without the version (though should also work if you leave the 0.4.3 version).

If something breaks after the official release (shouldn't really, but just in case) please let me know.
