### ISSUE TITLE
Can't get Wallaby to run with NodeJS mix of ts and js "Unexpected token import"

### ISSUE THREAD

**Issue by jessedobbelaere** [wallabyjs/public#1800]
### Issue description or question
I have a **NodeJS 10.8.0** project with **Mocha & Chai** tests, where I used to run Wallabyjs succesfully in the past. But ever since we started migrating the js files to typescript, I had issues getting Wallaby to run. Right now 50% of the code is migrated to Typescript, so some files and tests are in typescript and have dependencies to js files and vice-versa. Some .js files use `import` statements to Typescript files.  

In command line I run the tests by doing:

```
"scripts": {
	"build-with-source-inline": "tsc -p tsconfig.json --inlineSourceMap --inlineSources",
	"pretest": "rm -r dist/; npm -q run build-with-source-inline",
	"test": "export TZ=utc; mocha --require source-map-support/register --colors --recursive 'dist/test/unit/**/*.js'",
}
```

or with `ts-node`: 

```
npx mocha --require source-map-support/register --require ts-node/register test/**/*
```

In Webstorm's UI I run a test using ts-node like mentioned above with the require statements.

My `tsconfig.json` looks like this with es2017 target, commonjs and `allowJS` being used in my project:

<details>

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "lib": [
      "es2015",
      "es2016",
      "es2017"
    ],
    "allowJs": true,
    "outDir": "dist",
    "removeComments": true,
    "strict": true,
    "checkJs": false,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "moduleResolution": "node",
    "baseUrl": "."
  },
  "include": [
    "app.ts",
    "src/**/*.*",
    "test/**/*.*"
  ],
  "exclude": [
    "node_modules",
    "dist"
  ]
}
```

</details>

However, I already spent hours trying to make a working wallaby.js config file for my project. Seems like Wallaby compiles Typescript by default, so added .js files too to the pattern and pointed it to use my `tsconfig.json` which *should* be able to compile and run tests as this works in CLI and Webstorm. 

When I run Wallaby it fails with:

```
./src/commands/xxx-xxx-xxx.js:13
import { Converter } from "../common/converter";
^^^^^^

SyntaxError: Unexpected token import

	at src/commands/xxx-xxx-xxx.js:13
	at Object.<anonymous> test/unit/commands/xxx-xxx-xxx-test.js:10

./src/models/es_repositories/xxx.js:9
import * as trends from "./queries/content/trends";
^^^^^^

SyntaxError: Unexpected token import

	at src/models/es_repositories/xxx.js:9
	at Object.<anonymous> src/models/transformers/xxx-transformer.js:10
	at Object.<anonymous> test/unit/commands/xxx-xxx-test.js:8

./src/models/transformers/xxx-transformer.js:1
(function (exports, require, module, __filename, __dirname) { import { XXXEvent } from "./xxx-event";
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

My tsconfig is able to compile and run the code without errors using `tsc` or `ts-node` but seems to fail when used in my Wallaby config. Can't seem to pinpoint what is wrong here. Do I really need the Babel transpiling or ESM? 

I tried using ts-node (`require("ts-node").register();`) too in my wallaby config but Wallaby first compiles the typescript (by default I believe?) and fails on that same error, before it uses ts-node to run Mocha I believe?

Already looked at similar issues for the `"Unexpected token import"` but can't find a solution in my project.
Help is much appreciated, want to get Wallaby running again :-) 

### Wallaby.js configuration file

```javascript
const compilerOptions = require("./tsconfig.json");

module.exports = function (wallaby) {
    process.env.WALLABY = "true";
    return {
        files: [
            "tsconfig.json",
            "config/*.json",
            "resources/*",
            "package.json",
            "src/**/*.js",
            "src/**/*.ts",
        ],
        tests: [
            "test/unit/**/*.*"
        ],
        compilers: {
            "**/*.+(t|j)s?(x)": wallaby.compilers.typeScript(compilerOptions)
        },
        setup: function () {
            global.expect = require("chai").expect;
        },
        debug: true,
        testFramework: "mocha",
        env: {
            type: "node",
            params: {
                env: "TZ=utc"
            }
        }
    };
};

```

### Code editor or IDE name and version

WebStorm v2018.2.1

### OS name and version

macOS High Sierra

**Comment by smcenlly** [comment]
We've provided an updated wallaby.js configuration file (see below) that works for projects that use the TypeScript compiler on .js files. Please note, the `const compilerOptions` assignment had an issue and was not extracting the compilerOptions section. The configuration that we added was:

```
        preprocessors: {
            '**/*.jsts': file => file.changeExt('js').content
        },
```

## Working Wallaby.js Configuration

```javascript
const compilerOptions = require("./tsconfig.json").compilerOptions;

module.exports = function (wallaby) {
    process.env.WALLABY = "true";
    return {
        files: [
            "tsconfig.json",
            "config/*.json",
            "resources/*",
            "package.json",
            "src/**/*.js",
            "src/**/*.ts",
        ],
        tests: [
            "test/unit/**/*.*"
        ],
        compilers: {
            "**/*.+(t|j)s?(x)": wallaby.compilers.typeScript(compilerOptions)
        },

        preprocessors: {
            '**/*.jsts': file => file.changeExt('js').content
        },

        setup: function () {
            global.expect = require("chai").expect;
        },
        debug: true,
        testFramework: "mocha",
        env: {
            type: "node",
            params: {
                env: "TZ=utc"
            }
        }
    };
};```

**Comment by jessedobbelaere** [comment]
Works perfectly like that! Thank you so much!
