### ISSUE TITLE
`Update File Snapshots` is not working correctly

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#1804]
### Issue description or question
Update snapshots is working only when I click in terminal and not when I use the command `Update File Snapshots`. 
I am already dissatisfied paid customer and my dissatisfaction grows with each passing day, as I don't see any of `VSCode` bugs fixed.

[https://twitter.com/self_refactor/status/1032250726561529857](https://twitter.com/self_refactor/status/1032250726561529857)

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'jest.init.js', load: false, instrument: false },
      { pattern: 'package.json', load: false, instrument: false },
      { pattern: 'app/components/**/*.snap', load: false, instrument: false },
      'app/**/*.js?(x)',
      '!app/components/**/*.spec.jsx'
    ],
    tests: [
      'app/components/**/*.spec.jsx',
      '!app/components/ShipmentCardNew/AdminShipmentCardNew.spec.jsx',
      '!app/components/NavSidebar/NavSidebar.spec.jsx'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },
    testFramework: 'jest',
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    delays: {
      run: 1000
    },
    ignoreFileLoadingDependencyTracking: true,
    slowTestThreshold: 1000,
    maxConsoleMessagesPerTest: 5,
    debug: true
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.25.1
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux: 18.04

**Comment by ArtemGovorov** [comment]
Sorry to hear you're unhappy and that wallaby hasn't worked out for you. Please email us if you'd like a refund, we'll issue the refund and revoke your license.

If you'd like us to investigate the issue, please share the following info:
- try cloning this sample repo https://github.com/wallabyjs/wallaby-jest-snapshots, change [one of the tests snapshots code](https://github.com/wallabyjs/wallaby-jest-snapshots/blob/master/src/__tests__/component.spec.js#L12), and after the tests fail, try running the `Update File Snapshots` to see if it's working for you.

**Comment by selfrefactor** [comment]
That you are open to refund changes things for me in principle. It shows that you do realize the shortcomings of your code.

My main issue is the overall shaky and unreliable behavior. I see also other bugs, that I didn't bother to report.

If that was my code and it has so many bugs, then I won't feel so comfortable to charge a price for a perfect software.

My licence was a gift, so I don't win much with refund, but if these were my money, then I would definitely would use the refund suggestion.

Feel free to close the issue and feel free to fix VSCode extension, so other people think of me as a simple hater,  rather than a trustworthy source.

**Comment by ArtemGovorov** [comment]
If you continue to use the product, and would like to submit more details about the issue you're encountering (such as we have [requested above](https://github.com/wallabyjs/public/issues/1804#issuecomment-415224310)), we are happy to investigate and fix them.
