### ISSUE TITLE
Praise.....

### ISSUE THREAD

**Issue by jimdeane** [wallabyjs/public#181]
Absolutely great tool. I've been using. nCrunch for C# development for a while and this provides the exact same power for my JS development..

Thanks for creating wallaby! 

About to experiment with jasmine.given using  coffeescript as this fits in with our SpecLog, SpecFlow BDD approach.

Jim Deane

**Comment by ArtemGovorov** [comment]
@jimdeane Thanks! Glad to hear the tool helps. Let me know if you have any issues jasmine.given + coffeescript, I quickly tried it and simple samples seem to work:

![csjg](https://cloud.githubusercontent.com/assets/979966/8560851/195926be-2560-11e5-8ddf-848d20a458d5.gif)

**Comment by jimdeane** [comment]
Thanks.

I have Wallaby running with "Jasmine.Given" beautifully after I figured out how to get the dependencies sorted..

I'll let you have any feedback :)



On 08 Jul 2015, at 02:58, Artem Govorov <notifications@github.com<mailto:notifications@github.com>> wrote:


@jimdeane<https://github.com/jimdeane> Thanks! Glad to hear the tool helps. Let me know if you have any issues jasmine.given + coffeescript, I quickly tried it and simple samples seem to work:

[csjg]<https://cloud.githubusercontent.com/assets/979966/8560851/195926be-2560-11e5-8ddf-848d20a458d5.gif>

-

**Comment by ArtemGovorov** [comment]
Thanks Jim. Let me know how it goes. BTW, are you using Visual Studio or WebStorm/IntelliJ?

**Comment by jimdeane** [comment]
Visual studio.

We are a .NET development organisation we write insurance administration systems. We've taken the step to move entirely into BDD and are using all the tooling we can including TFS, SpecLog, SpecFlow and the C#.NET stack, reSharper, nCrunch  etc in the server and are now building a better UI using Angular (hence the interest in Wallaby..

I've seen a few oddities that are easily worked round and I'll post those to you when I've had a chance to recreate and capture the details

Jim



On 09 Jul 2015, at 12:00, Artem Govorov <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks Jim. Let me know how it goes. BTW, are you using Visual Studio or WebStorm/IntelliJ?

-
