### ISSUE TITLE
Using Different Node Versions in WebStorm

### ISSUE THREAD

**Issue by lance-p** [wallabyjs/public#1810]
### Issue description or question
I need to change the Node version I want to use for testing. 

I'm using Webstorm 2018.2.2 and in the Run/Debug Configuration it gives the option to set the path for the Node.js executable. My path is currently set to: /Users/lance.p/Library/Caches/WebStorm2018.2/wallaby/node_v8.5.0/node

<img width="851" alt="screen shot 2018-08-28 at 9 34 24 am" src="https://user-images.githubusercontent.com/14359565/44726363-93280780-aaa5-11e8-88c1-fe774871c042.png">

When I check the wallaby folder /Users/lance.p/Library/Caches/WebStorm2018.2/wallaby/ the only Node folder I see is the node_v8.5.0 folder. 

<img width="418" alt="screen shot 2018-08-28 at 9 15 43 am" src="https://user-images.githubusercontent.com/14359565/44725324-01b79600-aaa3-11e8-9870-3ad450559d60.png">

This must have been setup when Wallaby was installed, and I don't see any option to add other Node versions via the Run/Debug Configuration. The only option I see is to change the Node.js path, but there is a note to not change the path unless necessary. Is this how I should change the Node.js version to run my Wallaby tests against? (I'm using nvm and have a 10.4.1 executable at /Users/lance.p/.nvm/versions/node/v10.4.1/bin/node)

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version
WebStorm v2018.2.2

### OS name and version

OSX

**Comment by smcenlly** [comment]
The node version specified in the Run/Debug configurations is the version of node that is used to run wallaby itself, and not your tests. 

Based on your config, your tests are running in electron.

You may need to change the wallaby node version if, for example, you your sass-loader requires a specific version of node. In this case, it is OK to change the node.js path in Run/Debug configurations to point to the version of node that your project is using.
