### ISSUE TITLE
Wallaby keeps "saving" the snapshot when running Jest test

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1819]
### Issue description or question

I am not sure why, but when running jest tests wallaby keeps saving the snapshot to the disk in the project folder. Weird is that it is the original snapshot. It is as if it would load it  and then save it back again. It is NOT the new snapshot.

It's just mildly annoying because it messes up with my bundler that keeps constantly rebuilding the app.

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function(wallaby) {
  return {
    files: [
      'tsconfig.json',
      'transformer.js',
      'jest.setup.js',
      'jest.config.js',
      'test/*.js',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      '!src/luis_app',
      '!src/**/*.test.+(ts|tsx)'
    ],

    tests: [
      'src/data/**/*.test.+(ts|tsx)',
      'src/client/**/*.test.+(ts|tsx)',
      'src/shared/**/*.test.+(ts|tsx)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      initial: 1,
      regular: 1
    },
    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.Latest

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I may be misunderstanding the issue, but Jest (when Wallaby is running it) is supposed to keep saving snapshots? If you run Jest (without Wallaby) in watch mode, doesn't it do the same?

**Comment by tomitrescak** [comment]
@ArtemGovorov no, I just tested it. I ran jest in watch mode and it does not update snapshots unless you specifically tell it to. Only when I run wallaby, those snapshots are saved. I mean, it is a minor nuisance, nothing blocking ...

**Comment by ArtemGovorov** [comment]
@tomitrescak Interesting, then Wallaby is not supposed to update snapshots either (Wallaby does what Jets tells it to with snapshots). I also can't seem to reproduce the issue locally.

Could you please clone this repo https://github.com/wallabyjs/wallaby-jest-snapshots, start wallaby and edit some tests (without breaking snapshots)? Are snapshots being updated? I can't see them being updated on my machine (the files' update date stays the same).

**Comment by foxbunny** [comment]
@tomitrescak When you say "run tests", do you mean using "Run file tests" or something along those lines?

**Comment by tomitrescak** [comment]
No, it happens during the test run. It's quite annoying as FuseBox keeps rebundling the app almost every second. It is on my TODO list to find out what is causing this. I'm pretty sure must be some configuration / extension issue. The fact is, that all affected snapshots are overwritten on each Wallaby run. I'll keep this open and close it as soon as I will find the cause and report back so others can possibly avoid doing the same silly thing.

**Comment by smcenlly** [comment]
We recently found and fixed an issue with snapshots updating in certain cases when using [Live Comments](https://wallabyjs.com/docs/intro/advanced-logging.html#live-comments). This may have caused your problem. I'll close the issue for now, let us know if you're still have problems after updating to use the latest version of Wallaby plugin for your editor with the latest Wallaby core.
