### ISSUE TITLE
No tests are run after the initial run

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#182]
Since the last update (core 1.0.74), tests are run properly for the first time after I clear the cache from `c:\Users\sflint\.WebStorm10\system\wallaby\projects\`, but then, when I edit my code, Wallaby no longer identifies my tests, and the Wallaby Console writes `Finished executing 0 affected test(s)`.

**Comment by ArtemGovorov** [comment]
Fixed in core 1.0.75. Restart wallaby.js to get the core updated (if it doesn't update, restart WebStorm and start wallaby).

**Comment by ArtemGovorov** [comment]
The issue was introduced very recently when fixing some other TypeScript compiler scenario and is specific to TypeScript. Thanks for finding it so quickly and sorry about any inconvenience it caused.

**Comment by splintor** [comment]
Great - Wallaby is now back to its amazing behavior. Thanks for such a quick fix!
