### ISSUE TITLE
Not able to start up WallabyJS plugin in IntelliJ

### ISSUE THREAD

**Issue by edudojevic** [wallabyjs/public#1822]
### Issue description or question
I'm not able to start up the plugin anymore in IntelliJ. Getting: "Process finished with exit code 0". Tried deleting the plugin and reinstalling, but same result. Any idea what is going on?

### Code editor or IDE name and version
IntelliJ IDEA 2018.2

### OS name and version
OSX 10.13.6

**Comment by smcenlly** [comment]
Can you please tell us what version of the WallabyJS plugin you are using? Is it the latest version? 

Can you also please provide us with your IntelliJ logs, you can find these from the IntelliJ menu: `Help->Show Log in Explorer`

**Comment by edudojevic** [comment]
WallabyJS version: 1.0.118

The logs are quite big. But the only warning from wallaby that I could find was this:
2018-09-04 06:33:02,196 [514261954]   WARN -                        Wallaby - Failed to copy wallaby.js dependencies, /private/var/folders/xd/_7chxw7s6mx17rmlw89s1_tr0000gn/T/unzip-dir-/bin/node (No such file or directory) 
2018-09-04 06:33:04,779 [514264537]   WARN -                        Wallaby - Failed to copy wallaby.js dependencies, /private/var/folders/xd/_7chxw7s6mx17rmlw89s1_tr0000gn/T/unzip-dir-/bin/node (No such file or directory) 

And this was a while ago.

**Comment by smcenlly** [comment]
Can you please confirm how you're launching Wallaby? Under the `Run` menu in IntelliJ, if you select `Edit Configurations...`, you should have a `Wallaby.js` configuration that points to your project configuration file. By default, the wallaby node path should be set to `....wallaby\node_v8.5.0\node.exe`. If you're not launching using a wallaby configuration, you can read more about how to set up in our [docs](https://wallabyjs.com/docs/intro/get-started-jetbrains.html#run-configuration).

When you run your wallaby configuration, you should have two tabs display, one that says `Failing Tests` and one that says `Wallaby Console`. Is the `Wallaby Console` where you're getting the message `Process finished with exit code 0`?

**Comment by edudojevic** [comment]
Yes I do have a configuration, which is set as follows:
- Configuration file: `..../wallaby.conf.js`
- Node.js: `..../wallaby/node_v8.5.0/node`

When I run this configuration I do get a Wallaby Console which only outputs the following:
`Process finished with exit code 0`

**Comment by ArtemGovorov** [comment]
Please try changing node location in your Run Configuration to your system's node binary path to see if it helps.

**Comment by edudojevic** [comment]
Setting the node path to `/usr/local/bin/node` instead of the previous one solves the problem. Thanks!

**Comment by ArtemGovorov** [comment]
Thanks for checking. Looks like you Wallaby node have not been downloaded/extracted correctly. Copying `/usr/local/bin/node` to `..../wallaby/node_v8.5.0/` folder should fix the issue for future run configurations.
