### ISSUE TITLE
Run tests one after another and not in parallel

### ISSUE THREAD

**Issue by afresquet** [wallabyjs/public#1827]
### Issue description or question

I have a few test suites that interact with a database, I need to not run them in parallel so that conflicts don't happen.

I achieve this by adding the flag `--runInBand` to the `jest` command.

I haven't been able to find how to do this with Wallaby. Is it possible?

### Wallaby.js configuration file

[Create React App configuration from Wallaby website](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app)

### Code editor or IDE name and version

Visual Studio Code v1.28.0-insider 

### OS name and version

OSX v10.13.6

**Comment by ArtemGovorov** [comment]
Yes, it is possible. [Setting `workers`](https://wallabyjs.com/docs/config/workers.html) count to `1` should help: 

```js
workers: {
       initial: 1,
       regular: 1
     }
```

**Comment by afresquet** [comment]
Thank you very much!
