### ISSUE TITLE
Missing setTimeout[util.promisify.custom] property

### ISSUE THREAD

**Issue by zapthedingbat** [wallabyjs/public#1835]
### Issue description or question

When running tests in wallaby the setTimeout[util.promisify.custom] property is missing, which causes `util.promisify` to fail.

Example reproduction available here
https://gist.github.com/zapthedingbat/2cd66e7506c4670fc0b7e36042cd9f46

The native nodejs `util.promisify` method expects to find an alternative implementation for use with promises defined on the setTimeout[util.promisify.custom] property. This property is in tact when run with the command line, but is missing when wallaby runs the tests.

The correct behaviour can be restored by defining an equivalent implementation on setTimeout[util.promisify.custom] in the wallaby `setup` method.

#### References
* https://nodejs.org/api/util.html#util_custom_promisified_functions
* https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [ '!test.js' ],
    tests: [ 'test.js' ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'mocha',
    debug: true,
    setup: function () {
      // Add the custom promisify implementation back to setTimeout to make wallaby work
      /*
      const util = require('util');
      
      if (typeof util.promisify.custom !== 'undefined' && typeof setTimeout[util.promisify.custom] === 'undefined') {
        setTimeout[util.promisify.custom] = (after, value) => new Promise(resolve => setTimeout(() => resolve(value), after));
      }
      */
    }
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the detailed report! The issue is fixed and the fix is published in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
