### ISSUE TITLE
Can you install WallabyJS into Visual Code manually?

### ISSUE THREAD

**Issue by maccurt** [wallabyjs/public#1837]
My office has some new Network software that is preventing me from upgrading WallabyJS in Visual Code. We know that it is the network software because they turned it off on my machine and every thing worked. They currently are not unblocking whatever website the extension is coming from they do tell me they are working on it. They tell me there must be a way I can manually download it and install the upgrade. Is that possible?

**Comment by smcenlly** [comment]
We do support offline installation. There are a few manual steps you'll need to take. Offline installation is described in our [docs](https://wallabyjs.com/docs/intro/troubleshooting.html#offline-installation).

**Comment by maccurt** [comment]
Ok, the instructions are slightly confusing. I was able to download  wallaby-v1.0.617.zip. On my computer I currently see  C:\Users\MYNAME\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.96. In your instructions I see you say unzip to ~/.vscode/extensions/WallabyJs.wallaby-vscode-LATEST/wallaby.  am I supposed to change LATEST to something? There is no folder named Wallaby under my ..\wallabyjs.wallaby-vscode-1.0.96. Should I add that there and zip into that?

**Comment by maccurt** [comment]
Ok, I think I got it working in this folder:  C:\Users\MYNAME.vscode\extensions\wallabyjs.wallaby-vscode-1.0.96  I added a folder named wallaby(or is was there already and I missed it) and unzipped into there, I see then opened a folder/project that had some wallaby test and they ran and it did not say anything about upgrading core.. So it looks like it worked

**Comment by smcenlly** [comment]
Yep - what you did was correct.
