### ISSUE TITLE
"Unexpected token import" when importing es2015 module with Jest, works with jest-cli

### ISSUE THREAD

**Issue by miguelbermudez** [wallabyjs/public#1844]
### Issue description or question
I'm using babel@7, typescript (using @babel/preset-typescript) with jest and i'm getting the "Unexpected token import" error for a library I'm using that is only packaging es2015 modules: `date-fns@2`.

Jest works fine when running:
`./node_modules/.bin/jest`.

Babel works fine when running:
`babel src --out-dir lib --extensions \".ts,.tsx\" --source-maps inline"`

TS works fine when running:
`tsc --noEmit`

Interestingly enough, I just finished fixing the same issue with jest once I added the library. I forgot to add its location to `transformIgnorePatterns`. 
After I did that, jest worked. 
Now wallaby is giving me the same error even in the same file.

I'm wallaby overriding some of the jest config?
 
### Wallaby.js configuration file

```javascript
var babelConf = require('./babel.config.js');

module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.ts?(x)',
    ],

    tests: [
      'tests/**/*test.ts?(x)'
    ],

    debug: true,

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.babel(babelConf)
    },
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup: function(wallaby) {
      var jestConfig = require('./package.json')
        .jest;
      wallaby.testFramework.configure(jestConfig);
    }

  };
};

```

### babel.conf.js 

```javascript
module.exports = {
  presets: [
    ["@babel/preset-env", {
      targets: {
        esmodules: true
      },
      loose: true
    }],
    "@babel/preset-typescript",
    "@babel/preset-react"
  ],
  plugins: [
    ["@babel/plugin-proposal-class-properties", {
      "loose": true
    }],
    "@babel/proposal-object-rest-spread"
  ]
}


```

### Relavent jest config from package.json
```json
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}"
    ],
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
    },
    "testMatch": [
      "<rootDir>/tests/**/?(*.)(spec|test).ts?(x)"
    ],
    "transformIgnorePatterns": [
      "/node_modules/(?!date-fns).+\\.js$"
    ],
    "moduleDirectories": [
      "./node_modules",
      "./src"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
```

### Code editor or IDE name and version
Visual Studio Code v1.? 1.27.2 

### OS name and version
OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Try adding your babel config to your `files` list (so it gets copied to the Wallaby cache folder where Wallaby is running Jest from), it should help.

```diff
    files: [
      'src/**/*.ts?(x)',
+     {pattern: 'babel.conf.js', instrument: false}
    ],
```

**Comment by ArtemGovorov** [comment]
Also you may need to add your tsconfig.json too:

```diff
    files: [
      'src/**/*.ts?(x)',
+     'tsconfig.json',
+     {pattern: 'babel.conf.js', instrument: false}
    ],
```
