### ISSUE TITLE
Option to display the contents of nested objects

### ISSUE THREAD

**Issue by nachocab** [wallabyjs/public#1845]
In mocha I can see my stringified objects, but in the wallaby console it only goes down a few levels:

```
[
  [ { something: 0, tokens: [ [Object], [Object] ] },‌⁠...
]
```

Can this be changed with a setting?

**Comment by ArtemGovorov** [comment]
> In mocha I can see my stringified objects

How exactly are you logging your objects in mocha? Could you please provide an example of when mocha displays something that Wallaby doesn't?

**Comment by nachocab** [comment]
Thanks for the answer! It's okay, I just didn't realize that if I scrolled in the console there is the option to `Show side-by-side diff​`

**Comment by nachocab** [comment]
Oops, never mind. Even with the side-by-side. It still shows up as `[Object]`. Here is a reproducible example:

```
it('should show nested properties', function() {
    const obj1 = [
      [
        {
          chunks: [
            {
              tokens: [{ value: 'a' }],
            },
          ],
        },
      ],
    ];
    const obj2 = [
      [
        {
          chunks: [
            {
              tokens: [{ value: 'b' }],
            },
          ],
        },
      ],
    ];
    expect(obj1).to.eql(obj2);
  });
```
![image](https://user-images.githubusercontent.com/27538/46256759-42923880-c4af-11e8-99b4-86241f37e923.png)

![image](https://user-images.githubusercontent.com/27538/46256765-589ff900-c4af-11e8-8496-a03994323d51.png)

Side by side diff
![image](https://user-images.githubusercontent.com/27538/46256768-6f465000-c4af-11e8-8e3f-c91ea42fe05f.png)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by nachocab** [comment]
Great, thanks a lot for the quick response 👍
