### ISSUE TITLE
TypeError: trustedSubscriber._addParentTeardownLogic is not a function

### ISSUE THREAD

**Issue by TomWhiteOmni** [wallabyjs/public#1848]
### Issue description or question
I've got a weird situation where Wallaby fails my Angular Observables tests with... 
> TypeError: trustedSubscriber._addParentTeardownLogic is not a function

...When subscribing to a simple RxJS observable on my development machine, but on another PC running a trial of Wallaby passes all tests.

I've put my entire Angular project on GitHub so you can see it:
[ObservablesUnitTests1](https://github.com/tomwhite007/ObservablesUnitTests1)

On my Dev machine it fails with the above error message in src\app\shared\services\intermediate.service.spec.ts , line 51

I've tried uninstalling and reinstalling the Wallaby Plugin, but no luck.

I had this problem in another project and thought  I was going mad, but then it repeated in this simple demo.

Any ideas?

Kind regards 

Tom

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions
);

compilerOptions.module = 'CommonJs';

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['src/wallabyTest.js', 'src/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {
        pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false },
      { pattern: 'src/**/*e2e-spec.ts', ignore: true }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use(
        '/favicon.ico',
        express.static(path.join(__dirname, 'src/favicon.ico'))
      );
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.? 1.27.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo, however it's working fine in my environment.

> When subscribing to a simple RxJS observable on my development machine, but on another PC running a trial of Wallaby passes all tests.

It looks like you have an older version of Angular/Rx installed on the path of node module resolution algorithm from Webpack. Try checking the following folders and remove any `node_modules` subfolder in them:

- `c:\Users\USERNAME\.vscode\extensions\`
- `c:\Users\USERNAME\.vscode\`
- `c:\Users\USERNAME\`
- `c:\Users\`
- `c:\`

and this should help.

**Comment by TomWhiteOmni** [comment]
You're a star Artem! Thanks.

Deleting the folder, c:\Users\USERNAME\node_modules
and then opening VS Code and running Tests in Wallaby solved it.

Excellent support. Really appreciate it.

Regards

Tom
