### ISSUE TITLE
wallaby setup with ts-jest typescript doMock doesn't work

### ISSUE THREAD

**Issue by jcyh0120** [wallabyjs/public#1852]
### Issue description or question
When using wallaby with ts-jest, I cannot set to doMock function right.
I had found some discuss with mock hoisting issue of ts-jest and babel, but I couldn't get more clue to make my sample project work.

I create a repo to write sample tests here. 
https://github.com/jcyh0120/wallaby-typescript-ts-jest
The one which doesn't work is 
https://github.com/jcyh0120/wallaby-typescript-ts-jest/blob/master/src/do-mock.spec.ts

### Wallaby.js configuration file

```javascript
module.exports = function(w) {
  return {
    files: ["src/**/*.ts", "!src/**/*.spec.ts"],

    tests: ["src/**/*.spec.ts"],

    env: {
      type: "node",
      NODE_ENV: "test"
    },

    // or any other supported testing framework:
    // https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks
    testFramework: "jest"
  };
};

```

### jest.config.js
```javascript

module.exports = {
  "transform": {
    "^.+\\.tsx?$": "ts-jest"
  },
  "testRegex": "(/__tests__/.*|(\\.|/)(test|spec))\\.(jsx?|tsx?)$",
  "testPathIgnorePatterns": [
    "<rootDir>/build/",
    "<rootDir>/node_modules/"
  ],
  "modulePaths": [
    "<rootDir>"
  ],
  "moduleFileExtensions": [
    "ts",
    "tsx",
    "js",
    "jsx",
    "json",
    "node"
  ],
  "testEnvironment": 'node',
  "verbose": true,
  "coverageDirectory": "coverage",
  "collectCoverage": true,
  "coveragePathIgnorePatterns": [
    "<rootDir>/build/",
    "<rootDir>/node_modules/",
    "<rootDir>/test/"
  ],
  "coverageReporters": [
    "lcov"
  ],
  "globals": {
    "ts-jest": {
    }
  },
  "reporters": ["jest-silent-reporter"]
}
```

### tsconfig.json

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "target": "es2017",
    "strict": true,
    "strictPropertyInitialization": false,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "outDir": "./build",
    "rootDirs": ["./src"],
    "typeRoots": ["node_modules/@types"]
  },
  "compileOnSave": false,
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}

```

### Code editor or IDE name and version

Visual Studio Code v1.27.2
### OS name and version
OSX 10.13.5

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample. 

What error are you getting? I'm getting this one:

```
Expected: 5566
Received: 555
```

but I'm getting the exact same error when running Jest without wallaby with `npm test` in your example repo.

**Comment by jcyh0120** [comment]
Yes, I am getting the same error.

I expect the doMock would replace the mock at the beginning. But it didn't happened.
Should any configuration be done in wallaby or ts-jest to make it work?

Also, I would like to know if I am asking question at the right place. 
Don't know if I should post this to ts-jest.

```javascript
// doMock hoist doesn't work

// put mock files into __mocks__ folder

const mockData = {
  userId: 1,
  id: 555,
  title: "i am replace mock",
  completed: false
};

jest.mock("axios", () => {
  return {
    default: {
      get: jest.fn(() => Promise.resolve({ data: mockData }))
    }
  };
});

import apiCall from "./api-play";

describe("test manual mock api play", async () => {
  beforeEach(() => {
    jest.resetModules();
  });

  it("call weather api", async () => {
    jest.doMock("axios", () => {
      return {
        default: {
          get: jest.fn(() =>
            Promise.resolve({ data: { id: 5566 } })
          )
        }
      };
    });

    let id = 123;
    let res = await apiCall(id);

    expect(res.id).not.toBe(id);
    expect(res.id).toBe(5566);
    expect(res.title).toBe("i am replace mock");
  });
});
```

**Comment by smcenlly** [comment]
Your question should really be directed as a jest issue/forum. From reviewing the jest documentation, it appears that this behavior is by design.

[From their documentation:](https://jestjs.io/docs/en/jest-object.html#jestmockmodulename-factory-options)

**jest.mock(moduleName, factory, options)**
> Modules that are mocked with jest.mock are mocked only for the file that calls jest.mock. Another file that imports the module will get the original implementation even if it runs after the test file that mocks the module.

**jest.doMock(moduleName, factory, options)**

> this is useful is when you want to mock a module differently within the same file
