### ISSUE TITLE
Jest transformIgnorePatterns option not being considered by wallaby.js

### ISSUE THREAD

**Issue by subblue** [wallabyjs/public#1853]
### Issue description or question

Wallaby.js using Jest is failing on files that import es6 components from our own private @kpvlab NPM modules. However everything is working fine via the Jest CLI.

```
SyntaxError: Unexpected token export​​
  at Object.<anonymous> ​src/components/ui/__tests__/Panel-test.js:7:0​
​​Jest encountered an unexpected token​​
​​​​
​​This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.​​
```

The trick is usually to specify the `transformIgnorePatterns` option in the Jest config (see below) but the possible complication in our case is that we have a mono repo with yarn workspaces and this is happening in one of the sub-packages: `packages/client/`. The files that are causing problems are actually stored in packages within `../../node_modules/@kpvlab/` relative to the client folder I'm running wallaby from.

Jest CLI doesn't have a problem with this, which is why I think it must be something specific to Wallaby and not Jest.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  process.env.NODE_PATH = require('path').join(__dirname, '../../node_modules')
  return {
    files: [
      'src/**/*.js*',
      { pattern: 'src/**/*.css', instrument: false },
      { pattern: 'src/fonts/*.*', instrument: false },
      { pattern: 'src/lib/*', instrument: false },
      '!src/**/__tests__/*-test.js',
      '!src/images/*',
    ],

    tests: ['src/**/__tests__/*-test.js'],

    filesWithNoCoverageCalculated: ['src/index.js', 'src/__tests__/*.js'],

    hints: {
      ignoreCoverage: /ignore coverage/,
    },

    compilers: {
      '**/*.js':  wallaby.compilers.babel(),
      '**/*.jsx': wallaby.compilers.babel(),
    },

    env: {
      type:   'node',
      runner: require('path').resolve(process.env.NVM_DIR + '/versions/node/v10.2.1/bin/node'),

      params: {
        env: 'LOCAL_PATH=' + process.cwd(),
      },
    },

    testFramework: 'jest',

    delays: {
      run: 1000,
    },
  }
}

```

### Jest config part of package.json

We are using the `transformIgnorePatterns` option in Jest to make sure our own @kpvlab modules still get transpiled - which works fine on the CLI.

```
"jest": {
    "setupFiles": [
      "<rootDir>/src/__tests__/setup.js"
    ],
    "transform": {
      "\\.(gql|graphql)$": "jest-transform-graphql",
      "^.+\\.jsx?$": "babel-jest"
    },
    "testRegex": "src/.*/__tests__/.*?-test.js$",
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|frag|vert)$": "<rootDir>/src/__tests__/file-mock.js",
      "\\.css$": "identity-obj-proxy"
    },
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}"
    ],
    "transformIgnorePatterns": [
      "node_modules/(?!@kpvlab)"
    ],
    "reporters": [
      "jest-spec-reporter",
      "jest-junit"
    ],
    "globals": {
      "API_PORT": "9009",
      "__DEV__": true
    },
    "testURL": "http://localhost:3009"
  },
```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

OSX

Being forced to run the tests on the CLI makes you realise how much you miss Wallaby when things aren't working, so I hope there is a configuration tweak we can make to get our workflow back :)

**Comment by ArtemGovorov** [comment]
I have tried to reproduce the issue with the info you've provided, but unfortunately everything seems to be working fine for me. I have created this simple repo with your configs https://github.com/ArtemGovorov/wallaby-1853 and file structure. Could you please have a look and add the bits I've missed to reproduce the issue?

**Comment by subblue** [comment]
Thanks for the test repo - I've forked it and made some changes to more closely match our set up and now I can replicate the error again. Make sure you use yarn to install the modules just in case it makes a difference:

https://github.com/subblue/wallaby-1853/commit/066f675b098a738e585a83306fc4e6c47909cdfb

Hopefully you will also be able to see the error too.

**Comment by subblue** [comment]
I've simplified the repo to remove the yarn workspace setup:
https://github.com/subblue/wallaby-1853

running `yarn test` works as expected, but running wallaby still triggers the issue above.

**Comment by smcenlly** [comment]
Thanks for the sample repo. You were very close to having this working. You were missing the babel configuration from your list of wallaby source files. I've created a [pull request](https://github.com/subblue/wallaby-1853/pull/2) for you and have also highlighted the changes (see below)

```diff
module.exports = function(wallaby) {
  process.env.NODE_PATH = require('path').join(__dirname, './node_modules')
  return {
    files: [
      'src/**/*.js*',
+     { pattern: 'babel.config.js', instrument: false },
      '!src/**/__tests__/*-test.js'
    ],

    tests: [
      'src/**/__tests__/*-test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',

      params: {
        env: 'LOCAL_PATH=' + process.cwd()
      }
    },

    testFramework: 'jest',

    delays: {
      run: 1000
    }
  }
}
```

**Comment by subblue** [comment]
Fantastic!

I added the `{ pattern: 'babel.config.js', instrument: false },` line to our actual project and it is all working as expected again :)

Thanks for your help, the Jest error proved to be a really misleading direction!
