### ISSUE TITLE
Duplicate snapshots for Typescript files being generated

### ISSUE THREAD

**Issue by UberMouse** [wallabyjs/public#1855]
### Issue description or question

I've noticed that randomly Wallabyjs will generate .js.snap snapshot files from our .tsx spec files, duplicates of the existing .tsx.snap files. This does not happen every time but it has resulted in almost all our snapshot files being duplicated.

Edit: I just ran `git clean -f` and they reappeared after restarting Wallabyjs but they have not appeared every time I've restarted it in the past fews I've been using it, so I'm not sure what is happening. I haven't made any changes to the Wallabyjs config or changed any dependencies

 ```
-> ls
-> messages.spec.js.snap  messages.spec.tsx.snap
```

Spec file name `messages.spec.tsx`

### Wallaby.js configuration file

```javascript
var compilerOptions = require('./tsconfig.json');
compilerOptions.module = 'CommonJs';


module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'tsconfig.json', load: false },
      { pattern: 'Scripts/react/**/*.ts', load: false },
      { pattern: 'Scripts/react/**/*.tsx', load: false },
      { pattern: 'Scripts/react/**/*.js', load: false },
      { pattern: 'Scripts/react/**/*.spec.tsx', ignore: true },
      { pattern: 'Scripts/react/**/*.spec.ts', ignore: true },
      { pattern: 'Scripts/react/**/*.stories.tsx', ignore: true },
      { pattern: 'Scripts/react/**/*.snap', ignore: true },
    ],
    tests: [
      'Scripts/react/**/*.spec.ts',
      'Scripts/react/**/*.spec.tsx',
      '!Scripts/react/sections/apm/modules/onboarding/tourtip.spec.tsx'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    compilers: {
      '**/*.ts?x': wallaby.compilers.typeScript(compilerOptions)
    },
    setup: function (wallaby) {
      var jestConfig = require(wallaby.localProjectDir + '/jestconfig.json');

      wallaby.testFramework.configure(jestConfig);
    }
  }
};
```

### Code editor or IDE name and version
WebStorm 2018.2

### OS name and version
macOS High Sierra 10.13.6

**Comment by ArtemGovorov** [comment]
Thanks for adding the details. Unfortunately I wasn't able to reproduce the issue in your fork (tried starting/restarting/changing code/changing snapshots/breaking & updating snapshots).

I have noticed a couple of things though that may not be related to the issue, but it's hard to tell at this point:

- your Jest config transform pattern `".(ts|tsx)": ...` looks like a glob pattern, while it is supposed to be a RegExp. It's still a valid RegExp, but will match anything with `ts` or `tsx` in its path. Try changing it to see if it affects anything:

```diff
    "transform": {
-     ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
+     "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
```

- your Wallaby config ignores `.snap` files. Not sure why the setting is in place, but try removing this line:

```diff
- { pattern: 'Scripts/react/**/*.snap', ignore: true },
```
