### ISSUE TITLE
Jest Multi Project Config Fails

### ISSUE THREAD

**Issue by matt-sanders** [wallabyjs/public#1856]
### Issue description or question
Hi guys
I'm having an issue with a multi project jest setup. The setup works fine when running `npm test` or `jest` but when running through wallaby I get an error when importing a `.vue` file: `[Info]​​​​​ Fri, 05 Oct 2018 02:51:00 GMT wallaby:workers Sandbox (active) [d4crr] error: Error: Cannot find module './file1' from 'file1.spec.js'`

https://github.com/matt-sanders/wallaby-config  contains config file and all the files to reproduce the error. `npm install` or `yarn` and then `jest` to see the tests passing. 

In the `jest.config.js` file you'll see I've commented out a single project config which does work in Wallaby. It's only when I switch to the multi project setup that it fails.

Hopefully it's something trival...

Open in VS Code and start wallaby and you'll get the following error:
```
[Info]​​​​​ Fri, 05 Oct 2018 02:51:00 GMT wallaby:workers Sandbox (active) [d4crr] error: Error: Cannot find module './file1' from 'file1.spec.js'
​​[Error] Runtime error: Error: Cannot find module './file1' from 'file1.spec.js'​​
​​[Error]     at Resolver.resolveModule (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-resolve/build/index.js:221:17)​​
​​[Error]     at Resolver._getVirtualMockPath (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-resolve/build/index.js:338:16)​​
​​[Error]     at Resolver._getAbsolutePath (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-resolve/build/index.js:324:14)​​
​​[Error]     at Resolver.getModuleID (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-resolve/build/index.js:301:31)​​
​​[Error]     at Runtime._shouldMock (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-runtime/build/index.js:766:37)​​
​​[Error]     at Runtime.requireModuleOrMock (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-runtime/build/index.js:460:14)​​
​​[Error]     at Object.<anonymous> (./proj1/file1.spec.js:3:26)​​
​​[Error]     at Runtime._execModule (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-runtime/build/index.js:694:13)​​
​​[Error]     at Runtime.requireModule (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-runtime/build/index.js:376:14)​​
​​[Error]     at /Users/mattsanders/Downloads/wallabytest/node_modules/jest-jasmine2/build/index.js:129:13​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-jasmine2/build/index.js:170:30)​​
​​[Error]     at /Users/mattsanders/Downloads/wallabytest/node_modules/jest-jasmine2/build/index.js:189:14​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at /Users/mattsanders/Downloads/wallabytest/node_modules/jest-jasmine2/build/index.js:167:12​​
​​[Error]     at jasmine2 (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-jasmine2/build/index.js:138:17)​​
​​[Error]     at /Users/mattsanders/Downloads/wallabytest/node_modules/jest-runner/build/run_test.js:187:24​​
​​[Error]     at Generator.next (<anonymous>)​​
​​[Error]     at step (/Users/mattsanders/Downloads/wallabytest/node_modules/jest-runner/build/run_test.js:315:30)​​
​​[Error]     at /Users/mattsanders/Downloads/wallabytest/node_modules/jest-runner/build/run_test.js:326:15​​
​​[Error]     at <anonymous>​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:188:7)​​
​​​​​[Info]​​​​​ console.log: FAIL proj1/file1.spec.js
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     Cannot find module './file1' from 'file1.spec.js'
​​​​​[Info]​​​​​       at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
​​​​​[Info]​​​​​       at Object.<anonymous> (../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.96/projects/871a9c3401ad6e3c/instrumented/proj1/file1.spec.js:3:26)
​​​​​[Info]​​​​​       at Runtime.d._wallabyReplaced.c.requireModule (../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.96/wallaby/runners/node/jest@0.4.3/initializer.js:14:22399)
```

### Wallaby.js configuration file
https://github.com/matt-sanders/wallaby-config 

### Code editor or IDE name and version
Visual Studio Code v1.27.2 w/ Wallaby 1.0.96

### OS name and version
macOS High Sierra 10.13.6

**Comment by matt-sanders** [comment]
Also, thanks for the awesome product. Wallaby is great :)

**Comment by ArtemGovorov** [comment]
Thanks for sharing the config! This change should make it work for you:

```diff
    setup: function (wallaby) {
-     const jestConfig = require('./jest.config.js');
+     const jestConfig = require('./jest.config.js').projects[0];
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig)
    },
```

**Comment by matt-sanders** [comment]
hmm, am I right in assuming that this would then still only load the first config? I would like to be able to run all the project tests, just as I do with `jest`.

**Comment by ArtemGovorov** [comment]
While we don't support multi-project Jest configs, this wallaby config should still run all tests in all projects.

**Comment by ArtemGovorov** [comment]
We'll be looking into supporting it properly, however we haven't yet seen cases where it wouldn't work just with the config above. Have you tried the config in your project to see if it's working for you?

**Comment by matt-sanders** [comment]
Yea I have, it mostly works but the real issue we're having ( which I didn't include in the example repo for brevity ) is that we have something like:
```
core/
   - index.js
clients/
    - client1/
       - index.js
       - someImport.js
       - client1Component.vue
       - client1Component.spec.js
    - client2/
       - index.js
       - somethingElse.js
       - client2Component.vue
       - client2Component.spec.js
```
Core has some shared functionality and inside client1Component.vue we reference core files with `@@` and client specific files with `@`.
So we might have something like this:
```js
// client1Component.vue
import core from '@@'
import someImport from '@/someImport'
```
```js
// client2Component.vue
import core from '@@'
import somethignElse from '@/somethingElse'
```

So then when the tests in `client1spec.js` run `@` references `/clients/client1/` and when `client2spec.js` runs `@` references `clients/client2/`. When we build it builds out each client separately, so it doesn't conflict then either. We can make this work with jest projects by doing something like:
```js
projects: [
   {
     displayName: 'Client 1',
      moduleNameMapper: {
          "^@/(.*)$": "<rootDir>/clients/client1/$1"
       }
   },
   {
     displayName: 'Client 2',
      moduleNameMapper: {
          "^@/(.*)$": "<rootDir>/clients/client2/$1"
       }
   }
]
```
Of course I can always just run `jest --watch` in the terminal, but would be nice to be able to use Wallaby in this instance.

Because `moduleNameMapper` applies to all files in the test, we can only apply one map for `@` which means in the tests, client2 would be importing files from client1, which obviously doesn't work.

Anyway, if there's another way around it I'd be happy to give it a shot, but that's the issue I'm running into at the moment. I can update the repo to match that if it's helpful.

**Comment by ArtemGovorov** [comment]
>  I can update the repo to match that if it's helpful.

Yes, could you please update the repo? Happy to investigate how we can make it work for your scenario.

**Comment by matt-sanders** [comment]
Ok, I've updated the repo with a very contrived example.

If you run `jest` or `npm test` you will see all the tests passing. Digging into the directory structure you'll see we have:
```
core/
   - components/
      - welcome.vue
      - welcome.spec.js
proj1/
   - deeply/
      - nested/
         - component.vue
         - component.spec.js
   - file1.vue
   - file1.spec.js
   - msg.js
proj2/
   - another/
      - nested/
         - component.vue
         - component.spec.js
   - file1.vue
   - file1.spec.js
   - msg.js
```
In `proj1/file1.vue` and `proj2/file1.vue` they both `import Welcome from '@@/components/welcome'`. In this case it's just one component, but in our project there are many different components, helpers etc being imported from core. They each then import a `msg.js` file and a component from within their directories by using `@/`. I guess we could instead import via `./` or `../../` but it's nicer to be able to use `@`.

In this example it's relatively basic as there are only a couple of files, but in our project each client has many different components and logic etc. I've also added a dummy `npm run build-proj1` script to demonstrate how we are using this. The reason we have this setup is because we have multiple clients, and each client uses the same build process, the same core files but have their own unique files. We've tried a few different approaches:
- having each client in their own repo with their own build setup
- having `core` as a git sub-module in each client repo
- having `core` as an npm package in each client repo

but in the end we've decided to come back to just one repo for everything as it was getting chaotic. If each client has the same build process we had to update every different webpack config, every test config, etc for each client when we made a change. Then you update core and you have to go into each repo and pull the new branch, write tests, make PRs for all different clients and re-build. There were PRs going everywhere and many different branches etc and it was becoming impractical. With this approach we share one build config, one test config, one common codebase. We can update core and test right from here that it hasn't broken any client specific code. We don't have to go through and update many different webpack configs every time we make a change ( which isn't often, but it does happen sometimes ).

Hope this makes sense and helps give some background as to what we're trying to achieve. Thanks for your help!
