### ISSUE TITLE
Your test suite must contain at least one test

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1857]
### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by kaminskypavel** [comment]
that was driving me crazy! thanks for reporting :)
