### ISSUE TITLE
[discussion] [question] [feature request] Support assertion data diff view for sinon-chai

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#186]
Is there possible to compare visually parameters in `sinon-chai` assertions:

``` js
.. .should.have.been.calledWith(....)
```

Is there possible in release `1.0.24` display chai.js assertion errors (demo from twitter)?

**Comment by ArtemGovorov** [comment]
We are using chai convention where AssertionError is raised with `showDiff` flag for those assertions that it makes sense to show the diff for. So it's up to the assertion library to set the flag and if I'm not mistaken, sinon-chai doesn't set the flag for its assertions.

I'll se what we can do about it.

**Comment by boneskull** [comment]
I'm going to be taking a look at Wallaby, but `sinon-chai` and `chai-as-expected` support is going to be crucial for me.

**Comment by ArtemGovorov** [comment]
@boneskull wallaby supports both `sinon-chai` and `chai-as-expected`, this issue is about [this feature support](https://twitter.com/wallabyjs/status/612902770526388224) for `sinon-chai` assertion errors

**Comment by hellboy81** [comment]
[Discussion updated](https://github.com/domenic/sinon-chai/issues/67#issuecomment-123293787)

**Comment by ArtemGovorov** [comment]
@hellboy81 Thanks, so as soon Sinon-chai is fixed to pass `expected`, `actual` and `showDiff` for certain assertions, wallaby.js 'Show Diff' feature will just work.
