### ISSUE TITLE
orange warning but no feedback

### ISSUE THREAD

**Issue by mesqueeb** [wallabyjs/public#1860]
### Issue description or question
I have an orange warning, but no feedback is given in VSCode.
I'm not sure why or what's wrong.

Screenshot:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/3253920/46566728-46b2d000-c95f-11e8-8304-c9d54e1ee9f7.png">

Repo: https://github.com/mesqueeb/is-what

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.ts',
      'dist/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.+(js|ts)': wallaby.compilers.typeScript({allowJs: true, outDir: './bin'})
    },
    preprocessors: {
      '**/*.jsts': file => file.changeExt('js').content
    },
    testFramework: 'jest',
    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code 1.27.2 (1.27.2)

### OS name and version

macOS

**Comment by ArtemGovorov** [comment]
> I have an orange warning,

This is not a warning. Wallaby gutter icons are [coverage indicators](https://wallabyjs.com/docs/intro/get-started-vscode.html#coverage-indicators). 

In your particular case it means that the line contains some code that is not covered (never executed). You may use the [`Toggle uncovered regions` command](https://wallabyjs.com/docs/intro/get-started-vscode.html#commands) to see what part or the code line is not covered. 

For your particular case - the `toDate: function () { return new Date() }` is never called, so Wallaby coverage indicator tells you about it.

**Comment by mesqueeb** [comment]
@ArtemGovorov I see! Sorry and thanks!!

**Comment by mesqueeb** [comment]
@ArtemGovorov that guide you linked me said nothing about orange indicators!

only Gray, Green, Yellow, Red and Pink 🦁

**Comment by ArtemGovorov** [comment]
"Yellow" is the same "Orange" in this context in your colour theme (meaning missing coverage).
