### ISSUE TITLE
Angular project: TypeError: Cannot read property 'run' of null​​

### ISSUE THREAD

**Issue by joonaspi** [wallabyjs/public#1863]
### Issue description or question
I'm using Wallaby with VS Code in my projects and today the WallabyJS plugin started to fail with all the tests in all projects. I did clone the angular-starter project which fails also so it can be used as a example repo. Same issue seems to happen with latest WallabyJS plugin for Atom.

In my own projects I'm still able to run all tests successfully with Karma and Chrome in headless mode.

Steps:

1. Clone repo: https://github.com/wallabyjs/angular-starter/
2. Install depedencies and follow repo's instructions
3. Vscode / Atom is installed with latest WallabyJS extension
4. Start wallaby
5. All tests will fail. See output below:
`
10 failing tests, 0 passing​​​​​
  ​​​​x-large directive should sent font-size to x-large​​​​ ​​​[3 ms]​​​​
    ​​TypeError: Cannot read property 'run' of null​​
    ​​TypeError: Cannot read property 'run' of null​ ​​​​
    ​​TypeError: Cannot read property 'run' of null​​
  ​​​​Title should get data from the server​​​​ ​​​[6 ms]​​​​
    ​​TypeError: Cannot read property 'run' of null​​

..... and so on with every test ....
`

WallabyJS console in Code prints following:
`
​​​​​[Info]​​​​​ Tue, 09 Oct 2018 09:10:59 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'run' of null, stack: TypeError: Cannot read property 'run' of null
​​​​​[Info]​​​​​     at t.<anonymous> (http://localhost:53243/____wallaby-bundle.js?1539076259108&wallabyFileId=bundle:33339:33)
​​​​​[Info]​​​​​     at t.e.length.arguments.(anonymous function) (http://localhost:53243/__wallaby__/jasmine@2.1.3/configurator.js:14:2941)
​​​​​[Info]​​​​​     at ZoneQueueRunner.i.attempt (http://localhost:53243/__wallaby__/jasmine@3.2.1/framework.js:15:26174)
​​​​​[Info]​​​​​     at ZoneQueueRunner.i.run (http://localhost:53243/__wallaby__/jasmine@3.2.1/framework.js:15:26449)
​​​​​[Info]​​​​​     at r (http://localhost:53243/__wallaby__/jasmine@3.2.1/framework.js:15:25598)
​​​​​[Info]​​​​​     at http://localhost:53243/__wallaby__/jasmine@3.2.1/framework.js:15:25687
​​​​​[Info]​​​​​     at http://localhost:53243/__wallaby__/jasmine@3.2.1/framework.js:15:24032
​​​​​[Info]​​​​​     at ZoneDelegate.invokeTask (http://localhost:53243/____wallaby-bundle.js?1539076259108&wallabyFileId=bundle:30601:31)
​​​​​[Info]​​​​​     at Zone.runTask (http://localhost:53243/____wallaby-bundle.js?1539076259108&wallabyFileId=bundle:30368:47)
​​​​​[Info]​​​​​     at drainMicroTaskQueue (http://localhost:53243/____wallaby-
[Info]​​​​​ Tue, 09 Oct 2018 09:10:59 GMT wallaby:workers [e30tz] Sandbox is responsive, closing it
​​​​​[Info]​​​​​ Tue, 09 Oct 2018 09:10:59 GMT wallaby:workers [94v3d] Run 3 test(s), skipped 0 test(s)
​​​​​[Info]​​​​​ Tue, 09 Oct 2018 09:10:59 GMT wallaby:workers [1flge] Run 2 test(s), skipped 0 test(s)
`

### Wallaby.js configuration file
The one from the angular-starter repo. No changes.

### Code editor or IDE name and version
Visual Studio Code Version 1.28.0 (1.28.0)
- WallabyJs.wallaby-vscode@1.0.96

Atom 1.22.1
-atom-wallaby: 1.0.24

### OS name and version
macOS High Sierra

**Comment by joonaspi** [comment]
Is there a way to use earlier version of the WallabyJS plugin with Code or Atom?

**Comment by ArtemGovorov** [comment]
We have made Jasmine 3 the default version, and it looks like your project(s) may not be compatible with it. We'll investigate the sample repo, but you may add/change your `testFramework` setting in your Wallaby config to `jasmine@2.8.0` to get it working:

```diff
- testFramework: 'jasmine',
+ testFramework: 'jasmine@2.8.0',
```

**Comment by joonaspi** [comment]
That does the trick. Thanks for the fast response! For me this issue can be closed.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by ArtemGovorov** [comment]
I'll keep the issue opened for a few days so it's easier discoverable by those who're using older versions on Angular.

**Comment by blopez2010** [comment]
You guys are AWESOME!! @ArtemGovorov I almost started to cry!! haha, thanks and great work!

**Comment by sjetha-pason** [comment]
@ArtemGovorov What steps need to be taken to make this work with Jasmine 3, rather than downgrading to Jasmine 2?

**Comment by smcenlly** [comment]
From a wallaby perspective, you simply need to specify your `testFramework` as `jasmine` in your `wallaby.js` configuration.

To upgrade from Jasmine 2.x to 3.x, please refer to the [Jasmine repo's](https://github.com/jasmine/jasmine) 3.0 [release notes](https://github.com/jasmine/jasmine/blob/v3.0.0/release_notes/3.0.md) for a list of what's new, including breaking changes.
