### ISSUE TITLE
Restart wallaby if configuration file is changed

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#1864]
I think it'd be helpful if wallaby would simply restart if you set the configuration file. 

I have multiple wallaby configs in my repo, between which I switch frequently. Wallaby basically always runs, so when I want to change the config, I have to first `Wallaby.js: Select Configuration File` and then `Wallaby.js: Start`. 

Is there a case where you want to change the configuration file, but keep using the old/currently-cached configuration file?

Editor: VSCode
OS: mac OS

**Comment by ArtemGovorov** [comment]
Thanks for the feature request. We have implemented and published it in the latest v1.0.97.
