### ISSUE TITLE
Wallaby 1.0.97 broken in VSCode: Cannot find module 'readable-stream/duplex'

### ISSUE THREAD

**Issue by narkowicz** [wallabyjs/public#1867]
### Issue description or question

All wallaby commands are failing, i.e. when attempting to start:

```
command 'wallaby.start' not found

Cannot find module 'readable-stream/duplex'
Source: Wallaby.js (Extension)
```

Reproducible across multiple projects using **`wallaby-vscode-1.0.97`**. Have rolled back to **`wallaby-vscode-1.0.96`** and have no problems. Subsequent auto-update restored broken `1.0.97` but am able to use after disabling auto-updates.

### Code editor or IDE name and version

Visual Studio Code v1.28.0 **`wallaby-vscode-1.0.97`**

### OS name and version

macOS High Sierra 10.13.6

**Comment by ArtemGovorov** [comment]
Thanks for the report. There was a corrupted version (v1.0.97) that we have published. Please update to 1.0.98 and the issue should be fixed for you.
