### ISSUE TITLE
Wallaby not workin with dotenv-safe library

### ISSUE THREAD

**Issue by cleitonper** [wallabyjs/public#1871]
### Issue description or question

Wallaby is displaying an error when used with [dotenv-safe](https://github.com/rolodato/dotenv-safe) library. The error is `​​MissingEnvVarsError` and occours when some variables are declared in `.env.example` file and not defined in `.env` file, but my environment variables are in both files.

When I start Wallaby, its creates a copy of all files in my project inside `$HOME/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.98/projects/ff9b2e2ad7bf3316/instrumented` directory. In this folder, the copy of my `.env` file is wrong.

The original `.env` file is: 
```
PORT=8000
JWT_SECRET='supersecret'
JWT_TTL='5m'
DB_CONN='mongodb://127.0.0.1/database'
```

The copied file is:
```
$_$wp(1);
$_$w(1, 0), PORT = 8000;
$_$w(1, 1), JWT_SECRET = 'supersecret';
$_$w(1, 2), JWT_TTL = '5m';
$_$w(1, 3), DB_CONN = 'mongodb://127.0.0.1/database';
$_$wpe(1);
```

Wallaby introduces theses strangers characters (`$_$wp(1)`, `$_$w(1, 0)`, `$_$w(1, 0)`...). When I replace the copied `.env` file with the original the error `MissingEnvVarsError` is no longer displayed.

Someone can help me with this?

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'lib/**/*.js',
      'src/**/*.js',
      'tests/teardown.js',
      '.env',
      '.env.example',
    ],

    filesWithNoCoverageCalculated: [
      'lib/**/*.js',
      'src/app.js',
      'src/database.js',
      'src/server.js',
      'tests/teardown.js',
    ],

    tests: [
      'tests/**/*.spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

Ubuntu 18.04.1 LTS

**Comment by ArtemGovorov** [comment]
By default, Wallaby is trying to [instrument your files](https://wallabyjs.com/docs/config/files.html#instrument). You may add the `instrument: false` flag to stop it:

```diff
    files: [
      'lib/**/*.js',
      'src/**/*.js',
      'tests/teardown.js',
-     '.env',
-     '.env.example',
+     {pattern: '.env', instrument: false},
+     {pattern: '.env.example', instrument: false},
    ],
```

**Comment by cleitonper** [comment]
Solved. Thanks.
