### ISSUE TITLE
with a new create-react-app with typescript always stuck with any wallaby conf

### ISSUE THREAD

**Issue by lucax88x** [wallabyjs/public#1874]
### Issue description or question

Need some help there.

I've successfully used wallabyjs for months in angular applications, and this week I started a react + typescript app for some POCs.

I did the create-react-app with typescript and ejected it so I could put my wallaby configuration.

I literally tried with all the wallabyjs confs there, but nothing, it ALWAYS hang up on

![image](https://user-images.githubusercontent.com/6294464/46904392-a40ccb00-cee3-11e8-9009-4d027ed401a7.png)

I even tried to put the debug: true in the conf, but nothing prints out as errors.. it's like something is stuck?

hint: normal tests using the yarn run test are working, but I noticed there's like an INTERACTIVE mode in the Jest framework like this:

![image](https://user-images.githubusercontent.com/6294464/46904396-aa02ac00-cee3-11e8-9390-d85c56aff612.png)

it's possible that wallaby is stuck because of that?

You can find a repo [here](https://github.com/lucax88x/react-playground):

ps: always worked with angular projects

### Wallaby.js configuration file

```javascript
// tslint:disable

module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      runner: 'node',
      type: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },
    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          compact: false,
          filename: file.path,
          presets: ['react-app'],
          sourceMap: true
        })
    },

    setup: () => {
      const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(
        p => require.resolve('react-scripts-ts/' + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. The reason it didn't work for you is because Wallaby config file at the moment has a requirement to be placed in the project's root.

Another issue with your config is that your project is ejected, so there's no `react-scripts-ts`, so I have adjusted the config to consider it.

I have sent you the [PR with the working config](https://github.com/lucax88x/react-playground/pull/1) (make sure to use Wallaby Select Config command to select the new config).

**Comment by ArtemGovorov** [comment]
We'll take a look into it. I'm surprised that it didn't show any messages at all.

**Comment by lucax88x** [comment]
keep up the good work on this amazing product please.

I'm trying to spread this as much as I can..
