### ISSUE TITLE
Can not start node.js process (node), make sure your system has node.js installed.

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#1876]
### Issue description or question
Node is installed with NVM. I browse to other similar issues and try to apply `wallaby.node` to no success.
I restarted my OS with no difference.

### Wallaby.js configuration file

```javascript
// paste your config here
// https://github.com/selfrefactor/rambdax/blob/master/wallaby.js
module.exports = function (wallaby){
  return {
    files: [
      'rambdax.js',
      'package.json',
      'src/**/*.js',
      '!src/**/*.spec.js'
    ],
    tests: [
      'src/**/*.spec.js'
    ],
    env: {
      type: 'node',
      kind:'chrome',
      runner: 'node'
    },
    projectCacheDir: 'node_modules',
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    delays: {
      run: 1000
    },
    testFramework: 'jest',
    debug:true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code latest
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux Ubuntu 18.04

**Comment by ArtemGovorov** [comment]
The [`wallaby.node` setting](https://wallabyjs.com/docs/intro/install.html#nodejs-1) in VS Code settings should help.

Please make sure you are specifying a correct absolute path to the installed node executable in the setting.

**Comment by selfrefactor** [comment]
it does but the message is unclear whether to set up this option in wallaby file or in VSCode itself. So the issue is actually the message as I manage to resolve it.
