### ISSUE TITLE
Mention in Mocha docs

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#188]
Hey Artem, Wallaby is awesome! I think it deserves a mention in Mocha docs alongside with default JetBrains runner. In fact, I've already asked them about it: https://github.com/mochajs/mocha/issues/1795. Is there anything else I can do to get Wallaby mentioned in their docs?

**Comment by ArtemGovorov** [comment]
@DenisGorbachev Thanks for your support Denis! It'd be awesome if wallaby.js gets mentioned in mocha docs.

**Comment by ArtemGovorov** [comment]
Created [the pull request](https://github.com/mochajs/mochajs.github.io/pull/11) to mocha docs with a note about wallaby.js.
