### ISSUE TITLE
Can't force Wallaby Core upgrade on IntelliJ

### ISSUE THREAD

**Issue by ryandegruyter** [wallabyjs/public#1881]
### Issue description or question
Old license was expired, I purchased and activated a new license.

In plugins the version is: 1.0.118

When I launch wallabyjs it states:

wallaby.js started
core v1.0.497

How do I force to latest core? Tryed restart.

### Wallaby.js configuration file

IntelliJ IDEA v 2018.2.2

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Editor restart after entering your new license key should be enough.

If it doesn't help, try this:
- close the editor,
- delete `~/Library/Caches/IntelliJIdea2018.2/wallaby/wallaby` folder, and start the IDE.

**Comment by ryandegruyter** [comment]
Thanks for the quick response.

delete ~/Library/Caches/IntelliJIdea2018.2/wallaby/wallaby did the trick :)
