### ISSUE TITLE
Error with jest + mobx

### ISSUE THREAD

**Issue by dandevs** [wallabyjs/public#1885]
### Issue description or question
Using `jest@23.6.0` and `mobx@5.5.2` there seems to be issue running this test in wallaby but not jest itself

related: https://github.com/facebook/jest/pull/6391

Error:
![image](https://user-images.githubusercontent.com/2289147/47405440-80d1ef00-d71f-11e8-851d-d9a394901425.png)

Expected:
![image](https://user-images.githubusercontent.com/2289147/47405454-8e877480-d71f-11e8-8040-02b64658a9b9.png)

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => ({
    tests: ["_test/**/*.js"],
    files: ["src/**/*.js"],

    env: {
        type: "node",
        runner: "node"
    },

    testFramework: "jest"
})
```

### Code editor or IDE name and version
Visual Studio Code v1.28.2

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in  [the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
