### ISSUE TITLE
 requestAnimationFrame is not defined​​

### ISSUE THREAD

**Issue by Shermayster** [wallabyjs/public#1889]
### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  return {
    files: ['tsconfig.json', 'tsconfig.test.json', 'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', `!${testPathExp}`],

    tests: [testPathExp],

    env: {
      runner: 'node',
      type: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },
    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          compact: false,
          filename: file.path,
          presets: ['react-app'],
          sourceMap: true
        })
    },

    setup: () => {
      const jestConfig = require('react-scripts-ts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts-ts/' + p));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```
### Code editor or IDE name and version

Visual Studio Code v1.28

### OS name and version

OSX Mojave - 10.14

I'm using react-create-app with reach/router and typescript 
I receive: 
​ReferenceError: requestAnimationFrame is not defined​​
    ​​    at /Users/pavelshermayster/eva-web/node_modules/@reach/router/index.js:126:9​​

Tests are pass in jest

**Comment by smcenlly** [comment]
We've been unable to duplicate your issue using the latest version of `react-create-app` with TypeScript and @reach/router.

The `requestAnimationFrame` function was added to the `jsdom` package in October 2017. Prior to that, the `requestAnimationFrame` function was added by jest as polyfill. If you're not using the latest packages, could you please try updating them?

You could also try to fix this on your environment by adding `process.env.NODE_ENV = 'test';` as the first line of your wallaby configuration.

```javascript
module.exports = function(wallaby) {
  process.env.NODE_ENV = 'test';
  ...
  {Existing Wallaby.js Config}
}
```

If you are still having this issue after updating your packages, or after updating your `wallaby.js` configuration file, please provide us with a sample repo so we can see the problem first hand.

**Comment by Shermayster** [comment]
adding process.env.NODE_ENV = 'test'; 
fixed my problem

Thank you
