### ISSUE TITLE
Redundant validation message?

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#189]
![double-validation](https://cloud.githubusercontent.com/assets/829578/8633500/a6a8d67e-27d4-11e5-93c4-ba12c0a5f479.png)

**Comment by ArtemGovorov** [comment]
Thanks! It's my reseller engine (I don't own the code, just CSS styles), so I don't think I can do much about fixing it. Will raise the issue in their issue tracker.
