### ISSUE TITLE
Wallaby take forever to start in vscode

### ISSUE THREAD

**Issue by klauszhang** [wallabyjs/public#1890]
### Issue description or question
I run jest and wallaby at the same time, I could finish jest test in console in less than 5 min, but wallaby just hangs.
And I cannot stop it. Even I saw the message says
```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.630
​​[Error] No files with tests found, check your tests list patterns.​​
​​​​​[Info]​​​​​ Wallaby.js stopped
```
It still runs in the status bar. And I'm pretty sure it worked before.

This happens when I start a wallaby, then hit start again. Restarting OS doesn't help.

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test'
process.env.BABEL_ENV = 'test'

module.exports = function wallabyConfig(wallaby) {
  return {
    files: [
      'src/**/*.svg',
      'src/**/*.gql',
      { pattern: '.env*', instrument: false },
      { pattern: 'src/**/*.js*', load: true },
      '!src/**/__tests__/*.js',
      { pattern: 'webpack/jest/*', instrument: true }
    ],

    tests: ['src/**/__tests__/*.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',
    compilers: {
      'src/**/*.{jsx,js}': wallaby.compilers.babel(),
      'webpack/jest/*.{jsx,js}': wallaby.compilers.babel()
    },
    setup() {
      const jestConfig = require('./package.json').jest
      wallaby.testFramework.configure(jestConfig)
    }
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v 1.28.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The error:

> ​​[Error] No files with tests found, check your tests list patterns.​​

is reporting what happened.

It means that Wallaby can't find anything in the `'src/**/__tests__/*.js` folder that is relative to your Wallaby config.

Please check that 
- Wallaby config file is in your project's root, 
- and it is correctly selected in VS Code (run `Select Configuration File` command in VS Code).

If it doesn't help, please add the following line to your Wallaby config:

```diff
+console.log(__dirname);
process.env.NODE_ENV = 'test'
process.env.BABEL_ENV = 'test'
```

and share the output from Wallaby console.

**Comment by klauszhang** [comment]
@ArtemGovorov it start previously and the folder doesn't change.

**Comment by ArtemGovorov** [comment]
Can you please:
- provide a screenshot of running the `Select Configuration File` in the project,
- provide an output of when running Wallaby with the config change as suggested above:

```diff
+console.log(__dirname);
process.env.NODE_ENV = 'test'
process.env.BABEL_ENV = 'test' 
```

**Comment by klauszhang** [comment]
@ArtemGovorov Thanks
it seems to pick up the folder when I call `console.log(__dirname)`.
And the error `​​[Error] No files with tests found, check your tests list patterns.​​` disappeared.

But if I remove that `console.log(__dirname)` and restart vscode, it comes back again.

BTW, the loading indicator in status bar doesn't disappear when wallaby stops. It is a bit confusing for this.

**Comment by ArtemGovorov** [comment]
Could you please share the screenshot and the output that I have requested https://github.com/wallabyjs/public/issues/1890#issuecomment-433763184?

**Comment by klauszhang** [comment]
@ArtemGovorov 
I cannot reproduce the error now, I followed https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working
And clear the cache and reinstall it. 

I can provide the screenshot of the folder structure. Error message is
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.630
​​[Error] No files with tests found, check your tests list patterns.​​
​​​​​[Info]​​​​​ Wallaby.js stopped

![screen shot 2018-10-29 at 2 50 13 pm](https://user-images.githubusercontent.com/9569789/47625501-7170fc80-db8a-11e8-9991-68402b4885ab.png)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update. Glad to hear the issue is sorted out for you.

**Comment by klauszhang** [comment]
@ArtemGovorov Thanks for your help, really appreciate the prompt assist.
