### ISSUE TITLE
Wallaby not accepting license key for older version in VS Code

### ISSUE THREAD

**Issue by tony19** [wallabyjs/public#1891]
### Issue description or question

According to the [License Management page](https://wallabyjs.com/license/#notUpgrade), VS Code should automatically use the covered Wallaby version based on my license key. However, after entering my license key whose free upgrades expired this year, Wallaby continues to prompt me for my license and does not run any tests. Isn't it possible to continue using an older version of Wallaby?

### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  return {
    files: [
      'src/**/*',
      '!src/**/*.spec.ts',
      'jest.config.js',
      'package.json',
      'tsconfig.json',
    ],

    tests: ['tests/**/*.spec.ts', 'src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node',
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
        }),
    },

    setup(wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config');
      delete jestConfig.transform['^.+\\.tsx?$'];
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',

    debug: true,
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

macOS Mojave v10.14

**Comment by ArtemGovorov** [comment]
It should be possible to continue using old version of Wallaby (given that your **current version of Jest, Babel, TypeScript, editor API and possibly Vue integration was supported in that old version**).

Try entering your existing key and then [forcing Wallaby core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), it should install the correct version of Wallaby core after the editor restart.

Please note that you may still be getting obsolete version notifications (that you may either ignore or disable as described at https://github.com/wallabyjs/public/issues/1460#issuecomment-357396080).

**Comment by tony19** [comment]
Thanks, that worked! I recommend updating that support page to indicate the forced update is needed for VS Code.

**Comment by airtonix** [comment]
doesn't work anymore.

**Comment by ArtemGovorov** [comment]
@airtonix Please send us an email to hello@wallabyjs.com with your license key (or your order number), your editor version and some details about the issue (what exactly and how it doesn't work), we are happy to help.
