### ISSUE TITLE
Help a newbie configure Wallaby for Testem/Jasmine2?

### ISSUE THREAD

**Issue by smlarkin** [wallabyjs/public#1895]
### Issue description or question
I'm very new to configuring my environment, package.json, TDD, etc.  So I've been toying with Wallaby and simply can't get it to work.  After trying to import / the configuration file in VS Code and making sure the plugin was installed, I can't get it to work the way Quokka does for me.  I am just starting at a code school that exclusively uses Testem (which uses Jasmine 2) for all spec.js sheets.  Can I get someone to walk me through the correct configuration file and installation?
### Wallaby.js configuration file ... (That's what I need to get help on as using the default does not work).  I have tried placing this in the root and importing it in my .js files and tweaked it with various paths and such, but can't get it to work:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*Spec.js'
    ]
    ...
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};
```

FYI: in any of our projects repos there is this testem.json file in that repos root:
```javascript
{
"framework": "jasmine2",
"src_files": [
"src/*.js",
"test/*.js"
]
}
```
And often times (but not always) are is usually a test directory a single level deeper from the root directory that has both the xxx.spec.js (test spec) and this other testem.json file:

```javascript
{
"framework": "jasmine2"
}
```
If the above directory / spec is not there, usually there is only a spec folder with various xxx.spec.js files in it and no testem.json file.

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

OSX 10.14.1

**Comment by smcenlly** [comment]
I recommend checking out our [VS Code tutorial](https://wallabyjs.com/docs/intro/get-started-vscode.html), it's a great way to get started. We also have a [set of public samples](https://github.com/wallabyjs/public/tree/master/sample) that you can refer to. While not explicitly for VS Code, they will work for VS Code as well. You will see the [Visual Studio sample](https://github.com/wallabyjs/public/blob/master/sample/visualstudio/wallaby-jasmine-2.js) uses Jasmine 2.

If you can't get Wallaby working with your project, please provide us with a sample repo with tests working outside of Wallaby and we'll take a look for you.
