### ISSUE TITLE
Wallaby working in mocks

### ISSUE THREAD

**Issue by FlemmingBehrend** [wallabyjs/public#1897]
### Issue description or question
I can follow execution in test and src but not i jest mocks. 

Is it possible to get wallaby to work inside jest mocks that is placed in `__mocks__`

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: ['src/**/*.js', { pattern: 'src/**/*.spec.js', ignore: true }, 'src/**/__mocks__/*.js'],
        tests: ['src/**/*.spec.js'],
        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony'
            }
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js*': wallaby.compilers.babel({ babelrc: true, presets: ['babel-preset-jest'] })
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please create a sample repo demonstrating your request? We're happy to take a look and see what we can do.

**Comment by FlemmingBehrend** [comment]
Hi Artem

I have put an example [here](https://github.com/FlemmingBehrend/wallaby-jest-mock-sample)

To be more specific, when I run wallyby I get IDE green dots in source file and test file but not i mock file.

![image](https://user-images.githubusercontent.com/1967934/47814019-eab84d00-dd4c-11e8-9b38-2ad19efa38e8.png)

![image](https://user-images.githubusercontent.com/1967934/47814041-f86dd280-dd4c-11e8-8adc-b2b9f3157c8a.png)

![image](https://user-images.githubusercontent.com/1967934/47814078-0b80a280-dd4d-11e8-9e59-660d609aec37.png)

I can not follow execution flow in jest mocks nor can I expect variables and other nice wallaby stuff. Is there something I forgot to set up?

BTW thanks for a very cool product 👍

**Comment by FlemmingBehrend** [comment]
ahh, I forgot to include the `__mocks__` package in the config file. Closing this issue.
