### ISSUE TITLE
QUnit: Runtime error: Error: Called start() outside of a test context while already started

### ISSUE THREAD

**Issue by RubaXa** [wallabyjs/public#19]
Не получилось пока вычленить код приводящий к этой ошибке.

**UPD**: Пока пытался воспроизвести ошибка пропала :dizzy_face:

**Comment by RubaXa** [comment]
@ArtemGovorov Ошибка всё равно переодически выползает, бывает всё работает нормально достаточно долго, а вот сейчас более менее стабильно: http://recordit.co/492LjxCwdE

Притом ещё это не самый плохой вариант, сейчас хотя бы отображается результат тестов, но частно бывает, что кроме «_Runtime error: Error: Called start() outside of a test context while already started_» ничего не происходит.

У меня очень много асинхронных тестов и чем больше я их подключаю, тем чаще повторяется проблема. Помимо этого вместо `asyncTest` + `start` использую вспомогательные функции:

```js
// qunit-ext.js  — расширение для QUnit
QUnit.promiseTest = function (name, callback) {
	QUnit.asyncTest(name, function () {
		callback().then(function () {
			start();
		}, function (err) {
			equal(err.toString() + '\n' + err.stack, null, 'Тест «' + name + '» — fail');
			start();
		});
	});
};

// где-то в реальном тесте
promiseTest("Проверка результат от сервера", function () {
    return $.get("path/to").done(function (result) {
         equal(result, "...");
    });
});
```

Это никак не может влиять на ошибку?

P.S. Локализовать код пока не удается, ошибка выползает достаточно на большом объеме, и как видите, сильно «плавает».

**Comment by ArtemGovorov** [comment]
Ok, спасибо за дополнительные симптомы и код, буду пытаться воспроизводить.

**Comment by ArtemGovorov** [comment]
Пока не могу воспроизвести, можно попросить добавить `debug: true` в wallaby config (это включает подробный output):
```javascript
module.exports = function () {
  return {
    files: [
      'src/*.js'
    ],

    tests: [
      'test/*Spec.js'
    ],

    debug: true
  };
};
```
и вставить консольный вывод при возникновении ошибки (там более подробный стэк должен быть)?

**Comment by RubaXa** [comment]
Ошибка стабильно начинает появляется после повторного запуска `wallaby`

```
Wed, 25 Feb 2015 05:45:13 GMT project Serving /utils/extension/extension.test.js from cache
Wed, 25 Feb 2015 05:45:13 GMT project Sandbox (active) [cq9f7] error: Error: Called start() outside of a test context while already started
Runtime error: Error: Called start() outside of a test context while already started
Wed, 25 Feb 2015 05:45:13 GMT project Failed to map the stack to user code, entry message: Error: Called start() outside of a test context while already started, stack: http://localhost:59720/__wallaby__/qunit@1.16.0/framework.js:8
http://localhost:59720/__wallaby__/qunit@1.16.0/starter.js:8
http://localhost:59720/__wallaby__/tracer.js:8
phantomjs://webpage.evaluate():1
phantomjs://webpage.evaluate():1
phantomjs://webpage.evaluate():1
```

**Comment by ArtemGovorov** [comment]
Такой вопрос, где-нибудь в используемых файлах случайно не вызывается `QUnit.start()`?

**Comment by RubaXa** [comment]
Конечно вызывается, я же говорю, у меня много ассинхроных тестов, а это значит использование `QUnit.asyncTest` и `QUnit.start`.

**Comment by ArtemGovorov** [comment]
А, да, сорри, я почему-то думал что `QUnit.start` и то, что он экспортирует в `window.start` это разные вещи.

**Comment by ArtemGovorov** [comment]
Симптомы указывают на то, что что-то вызывает  `QUnit.start()` ДО wallaby.js. Что происходит: в sandbox загружается QUnit, затем все файлы (files), затем все тесты (tests), и затем wallaby стартует QUnit вызовом `QUnit.start`. Похоже, что какой-то из файлов или файлов с тестами вызывает `QUnit.start`(не сами асинхронные тесты, а процесс их загрузки). Нет ли чего-то такого?

**Comment by RubaXa** [comment]
Нет такого кода, да и ошибка происходит не в момент запуска, а при изменений тестов и то не всегда.

**Comment by RubaXa** [comment]
Попробовал посмотреть откуда вызывается `start`, все места указывают на wallaby и вот какая картина получилась:

```
Wed, 25 Feb 2015 06:38:09 GMT project Serving /utils/extension/extension.test.js from cache
console.log: Start again:     at http://localhost:61403/__wallaby__/qunit@1.16.0/starter.js:8
    at http://localhost:61403/__wallaby__/tracer.js:8
console.log: Start again:     at http://localhost:61403/__wallaby__/qunit@1.16.0/starter.js:8
    at http://localhost:61403/__wallaby__/tracer.js:8
Wed, 25 Feb 2015 06:38:09 GMT project Sandbox (active) [djboz] error: Error: Called start() outside of a test context while already started
Runtime error: Error: Called start() outside of a test context while already started
```

Т.е. при одном изменении два вызова `start`.

**Comment by ArtemGovorov** [comment]
Это интересно. А можно посмотреть на test-main.js (там где `requirejs.config` для тестов делается)?

**Comment by RubaXa** [comment]
Можно, вот он:

```js
(function (factory) {
	'use strict';

	if (window.wallaby) {
		wallaby.delayStart();
		factory('./', require, wallaby);
	}
	else if (typeof define === 'function' && define.amd) {
		define('jssdk', function () {
			return factory(require.toUrl('jssdk').split('/').slice(0, -1).join('/'), require);
		});
	} else {
		var cfg = factory(__dirname, { config: function () {} });

		delete cfg.tests;
		delete cfg.bench;
		delete cfg.modules;

		module.exports = {
			cfg: cfg,

			extend: function (cfg) {
				Object.keys(this.cfg).forEach(function (key) {
					var value = cfg[key],
						extValue = this[key];

					if (cfg[key]) {
						if (value instanceof Array) {
							cfg[key] = value.concat(extValue);
						} else {
							Object.keys(extValue).forEach(function (key) {
								value[key] = extValue[key];
							});
						}
					} else {
						cfg[key] = extValue;
					}
				}, this.cfg);

				return cfg;
			}
		};
	}
})(function (rootPath, require, wallaby) {
	'use strict';

	// Описание бута
	var cfg = {},
		_cfg;

	if (!Array.prototype.forEach) {
		// Array.prototype.forEach
		Array.prototype.forEach = function forEach(callback, scope) {
			for (var array = this, index = 0, length = array.length; index < length; ++index) {
				callback.call(scope || window, array[index], index, array);
			}
		};

	}

	if (typeof Object !== "undefined" && !Object.keys) {
		// Object.keys
		Object.keys = function keys(object) {
			var buffer = [], key;

			for (key in object) {
				if (Object.prototype.hasOwnProperty.call(object, key)) {
					buffer.push(key);
				}
			}

			return buffer;
		};
	}

	// Конфигурация JSSDK
	require.config(_cfg = {
		deps: ['autopolyfiller'].concat(wallaby ? wallaby.tests : []),
		callback: wallaby && function () {
			console.log('require.callback, QUnit.config.current:' + QUnit.config.current);
			wallaby.start();
		},

		shim: {
			'jquery.mockjax': { deps: ['jquery'] }
		},

		paths: (function (cfg) {
			cfg.tests = [];
			cfg.bench = [];
			cfg.paths = {};


			// Модули системы
			cfg.modules = [
				'config',
				'Emitter',
				'Promise',
				'request',
				'RPC',
				'RPC/statuses/sdc',
				'RPC/statuses/token',
				'Storage',
				'Model',
				'Model.List',
				'RPCModel',
				'utils/util',
				'utils/extension'
				/* module */
			];


			// Собираем реальные пути до модулей
			cfg.modules.forEach(function (name) {
				var fullname = name.split('/');

				fullname.push(fullname.slice().pop());
				fullname = fullname.join('/');

				cfg.tests.push(name + '.test');
				cfg.bench.push(name + '.bench');

				cfg.paths[name + '.test'] = fullname + '.test';
				cfg.paths[name + '.bench'] = fullname + '.bench';

				cfg.paths[name] = fullname;
			});


			// Поставщики разных полезностей
			var vendors = {
				'filter': 'vendor/filter',
				'jquery': 'vendor/jquery',
				'jquery.mockjax': 'vendor/jquery.mockjax',
				'benchmark': 'vendor/benchmark',
				'canjs': '//cdnjs.cloudflare.com/ajax/libs/can.js/1.1.7/can.jquery.min',
				'exojs': 'https://dl.dropboxusercontent.com/s/9mw2uyevis1ue2d/exoskeleton.js?dl=0',
				'backbone': '//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min',
				'underscore': '//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min',
				'inherit': 'vendor/inherit',
				'performance': 'vendor/performance',
				'autopolyfiller': 'vendor/autopolyfiller',
				'apidoc': 'tests/apidoc'
			};


			// Добавляем путь до jssdk
			function _paths() {
				var paths = cfg.paths;

				[].forEach.call(arguments, function (arg) {
					Object.keys(arg).forEach(function (name, value) {
						value = arg[name];
						paths[name] = (/^(\/\/|http)/.test(value) ? '' : rootPath + '/') + value;
					});
				});

				return paths;
			}

			return _paths(cfg.paths, vendors);
		})(typeof cfg === 'undefined' ? {} : cfg)
	});


	Object.keys(_cfg).forEach(function (key) {
		cfg[key] = _cfg[key];
	});

	// Export
	return cfg;
});
```

Он только выглядит сложно, а так  обычный конфиг.

**Comment by ArtemGovorov** [comment]
Да, все правильно вроде. Попробуем кое-что - я залил новую версию, обновится автоматом при перезапуске wallaby.js не позднее чем через 20 минут (или немедленно при перезапуске WebStorm) - посмотри пожалуйста не вылечилась ли проблема на новой версии.

**Comment by RubaXa** [comment]
Ну ок, пойду я пока на работу ;] Через час отпишусь.

**Comment by RubaXa** [comment]
Добрался, скачал и поставил последнию версию, проблемы пока не обнаружил.

**Comment by RubaXa** [comment]
@ArtemGovorov  не знаю заводить новую задачу или нет, может проблема в моей криворукости, но теперь столкнулся с другой проблемой, начал добавлять оставшиеся тесты и: `Test run failure: SyntaxError: Parse error`

```
Wed, 25 Feb 2015 09:40:16 GMT project Sandbox (active) [ape2u] error: SyntaxError: Parse error
Runtime error: SyntaxError: Parse error
Wed, 25 Feb 2015 09:40:16 GMT project Sandbox [ape2u] is responsive, closing it
```

**Comment by ArtemGovorov** [comment]
```Parse error``` - появляется стабильно? Удалось локализовать код/изменения при которых это происходит?

**Comment by RubaXa** [comment]
Стабильно при инициализация, добавляю три модуля и получаю ошибку, мне бы хоть понять, что именно это значит, «Parse» чего? JS файла или тест?

**Comment by ArtemGovorov** [comment]
Это ошибка, которую в таком виде выдает PhantomJs, больше деталей он не дает - это может быть любой код в JS файлах/тестах.

**Comment by RubaXa** [comment]
Странно, у меня теже самые тесты гоняются через тот же PhantomJS (grunt-qunit-istanbul) и с ним проблем нет, но я понял вас, постараюсь как-то локализовать проблему.

**Comment by ArtemGovorov** [comment]
Есть один важный момент - эта ошибка происходит где-то вне файлов, в которых показывается покрытие - иначе бы показывалась другая ошибка `Failed to parse`. То есть ошибка может быть в тех файлах, которые `instrument: false`

**Comment by RubaXa** [comment]
@ArtemGovorov С ошибкой разобрался, проблема была «у меня» из-за автогенерации кода через Function. wallaby же меняет структуру кода, добавляя свои конструкции и регулярки начали нерпавильно работать, собственно в этом и была проблема, точнее проблема в моем безумном коде.

В целом всё заработало, странно, но заработало. Вот пример странности: http://recordit.co/CKq5nYRSzM

При первом запуске нет никакой индикации, тольк при изменении появляется.
Запуска как debug режиме, так и без него, однажды получилось добиться двойной индикации, т.е. прям две колонки квадратиков появились.

P.S. Ещё не очень понятен прогресс исполнения, в логе вижу:
```
wallaby.js started
Execution progress: 50 tests
Execution progress: 100 tests
```
Но сколько это? Долго ли ждать? Прогресс бар был бы идеален :]

P.S.S. Ещё раз спасибо вам, надеюсь не утомил ;]

**Comment by ArtemGovorov** [comment]
Спасибо вам за ценный фидбек!

1) Да, wallaby меняет код для сбора coverage и это к сожалению может сломать определенные сценарии, читающие и использующие текст исходного кода. К слову, такие сценарии также может поломать минификация кода, поэтому если вы делаете минификацию - проверьте не ломает ли она ваш код подобным образом.

2) Я видимо туплю, но посмотрев два раза видео на которое вы ссылаетесь - не могу заметить странности, в чем она заключается? Если вы о том, что failed expectation показывается на нескольких строках - то это ожидаемо, так как wallaby показывает ошибки на каждой строке стека ошибки, что в данном случае несколько строк в рамках одного теста.

3) Насчет - при первом запуске нет индикации - то есть вообще нет квадратиков и появляются только при последующей правке? Это было всегда или только какие-то конкретные тесты на это влияют? Было бы супер если бы был код/тесты где я бы мог это воcпроизвести. 

4) Двойные квадратики я ловил один раз, но к сожалению не смог воспроизвести. 

5) Прогресс бар планируется. Когда тестов более 50, в данный момент выводится информация когда выполняются каждые 50, просто чтобы дать понять пользователю, что ничего не зависло и процесс идет. Такой прогресс как правило выводится один раз, при запуске, далее wallaby выполняет только затронутые изменением тесты, их как правило меньше 50.
Если прогресс обрывается на круглой цифре и больше ничего не выводит:
```
Execution progress: 50 tests
Execution progress: 100 tests
```
то что-то видимо зависло. В таком случае можно попробовать включить `debug: true` - там выводится имя каждого выполненного теста. и можно понять на каком тесте все зависло.

**Comment by ArtemGovorov** [comment]
Как дела с wallaby? Полет нормальный или есть новые issues? Эту пока закрываю.
