### ISSUE TITLE
make plugin installable from within JetBrains IDEs

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#190]
![screenshot](http://content.screencast.com/users/chiller/folders/Jing/media/0f8c36b4-ca4c-41e4-9db6-4e75d07b806b/00000203.png)

Is there a custom repository to add or something?

**Comment by DenisGorbachev** [comment]
@boneskull you might find http://wallabyjs.com/docs/intro/install.html helpful. But yeah, a custom repository with automatic updates would be great.

**Comment by ArtemGovorov** [comment]
@boneskull You may download and install the plugin like this.

![96efa948-1117-11e5-978b-d46661a0aa44](https://cloud.githubusercontent.com/assets/979966/8635763/dd489958-2879-11e5-8fb4-fe5dc0c9c8cd.png)

@DenisGorbachev Once installed, wallaby.js updates itself automatically, so you won't have to worry about missing new versions.

**Comment by boneskull** [comment]
@ArtemGororov Out of curiosity, why not use JetBrains' system?

**Comment by boneskull** [comment]
@ArtemGovorov ^

**Comment by ArtemGovorov** [comment]
@boneskull A few reasons, mostly it's about additional flexibility like custom update availability checking, option to automatically downgrade to previous version if/when required with almost zero effort, consistency in publishing the plugin itself and [separately versioned and updatable core](http://wallabyjs.com/docs/intro/how-it-works.html#plugin-and-core).
