### ISSUE TITLE
Babel config isn't loaded correctly

### ISSUE THREAD

**Issue by kevva** [wallabyjs/public#1901]
### Issue description or question

When running Wallaby and using `babel.config.js` for the Babel config, it isn't loaded correctly. It should be loaded project wide, and for stuff in `node_modules` too, but when trying to use a module in `node_modules` with dynamic imports in it, Wallaby errors out, even though I've explicitly added it to `files`.

You can reproduce this issue in this example repo https://github.com/kevva/wallaby-dynamic-import and read more about `babel.config.js` in https://babeljs.io/docs/en/configuration.

### Wallaby.js configuration file

```js
module.exports = async wallaby => ({
	files: ['index.js', '!test.js', 'node_modules/dynamic-import-module/*.js'],
	tests: ['test.js'],
	compilers: {
		'**/*.js': wallaby.compilers.babel()
	},
	env: {
		type: 'node',
		runner: 'node'
	},
	testFramework: 'jest'
});
```

### Code editor or IDE name and version

Visual Studio Code v1.29.0-insider

### OS name and version

macOS 10.14

**Comment by ArtemGovorov** [comment]
Because wallaby runs Jest tests from its own cache, and Jest is expected to compile the module, you need to add `babel.config.js` to the `files` list, not the module itself.

I have sent you [the PR with the change](https://github.com/kevva/wallaby-dynamic-import/pull/1).
