### ISSUE TITLE
`Could not compare snapshot` doesn't show enough info

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1903]
Wallaby only shows the first line. But when I run ava I see this:

```
  Could not compare snapshot

  The snapshot file is v1, but only v2 is supported.

  File path: xxx/index.test.js.snap

  Please run AVA again with the --update-snapshots flag to upgrade.
```

This is the key line I was missing: `The snapshot file is v1, but only v2 is supported.`

**Comment by ArtemGovorov** [comment]
@vjpr Thanks for the report. The latest Ava version support has been added to [Wallaby Core 1.0.632](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
