### ISSUE TITLE
Upgrade VS Code extension to use VS Code's webview API 

### ISSUE THREAD

**Issue by mjbvz** [wallabyjs/public#1905]
Hi, I'm on the VS Code team. I noticed that your extension uses the `vscode.previewHtml` command which is deprecated and which we are actively working to remove: https://github.com/Microsoft/vscode/issues/62630

We've developed a [webview API][docs] that provides a much better developer experience and offers a number of important security and compatibility benefits over `previewHtml`. We cannot fix `previewHtml` without breaking backwards compatibility, and have instead opted to remove it. 

To ensure that your extension continues to work properly in VS Code, please try upgrading to use the new Webview API. You can find documentation on the API usage [here][docs]. Let me know if you have any questions or concerns about this migration

[docs]: https://code.visualstudio.com/docs/extensions/webview

**Comment by smcenlly** [comment]
Thanks for letting us know. Do you have a timeline when the `vscode.previewHtml` will be removed?

**Comment by mjbvz** [comment]
Aggressive plan: removal of the command entirely in the March or April VS Code updates. But as a developer you will start seeing alerts about this command in the November update

**Comment by smcenlly** [comment]
We've updated our integration to use the new webview API. This will be released within the next week in the next version of wallaby.
