### ISSUE TITLE
wallaby.compilers.babel() ignores .babelrc file

### ISSUE THREAD

**Issue by maksimr** [wallabyjs/public#1906]
### Issue description or question
Wallaby ignore [.babelrc](https://github.com/JetBrains/ring-ui/blob/c68c2a7080bdd50c17616cef72e6490712745ffc/.babelrc) file inside [the project](https://github.com/JetBrains/ring-ui/tree/c68c2a7080bdd50c17616cef72e6490712745ffc)

### Wallaby.js configuration file

https://github.com/JetBrains/ring-ui/blob/c68c2a7080bdd50c17616cef72e6490712745ffc/wallaby.config.js
```javascript
const path = require('path');

const wallabyWebpack = require('wallaby-webpack');

const webpackConfig = require('./webpack.config');
const webpackTestConfig = require('./webpack-test.config');

module.exports = wallaby => {
  webpackConfig.componentsPath.
    push(path.join(wallaby.projectCacheDir, 'components'));
  webpackTestConfig.entryPatterns = [
    'test-helpers/mocha-globals.js',
    'test-helpers/enzyme-configuration.js',
    'components/**/*.test.js'
  ];

  return {
    files: [
      {pattern: 'components/**/*.*', load: false},
      {pattern: 'test-helpers/**/*.js', load: false},
      {pattern: 'postcss.config.js', instrument: false, load: false},
      {pattern: 'components/**/*.test.js', ignore: true}
    ],

    tests: [
      {pattern: 'components/**/*.test.js', load: false}
    ],

    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    postprocessor: wallabyWebpack(webpackTestConfig),

    /* global window */
    bootstrap: function bootstrap() {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    },

    env: {
      kind: 'electron'
    },

    reportConsoleErrorAsError: true
  };
};
```

### Code editor or IDE name and version
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.4139.22, built on October 31, 2018
IntelliJ IDEA EAP User
Expiration date: November 30, 2018
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14

Wallaby Plugin v1.0.118

### OS name and version
OSX

### Workaround
Now I'm using [this workaround](https://github.com/JetBrains/ring-ui/blob/master/wallaby.config.js#L33)

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

The issue is not Wallaby specific, this is the way [Babel 7 works](https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading) (it was different in Babel 6).

Because you have nested `package.json` files, ie.:

```
.babelrc
packages/
  mod1/
    package.json
    src/index.js
  mod2/
    package.json
    src/index.js
```

Babel 7 simply ignores `.babelrc` when compiling files inside those folders with `package.json` files. 

Apart from the workaround in Wallaby config, there are other ways to fix it as described in the referenced Babel docs:
- you may either "` .babelrc` to be a project-wide 'babel.config.js'",
- or "create a .babelrc in each sub-package that uses "extends" as `{ "extends": "../../.babelrc" }`".

**Comment by maksimr** [comment]
@ArtemGovorov thanks!

**Comment by ArtemGovorov** [comment]
@huston007 Babel doesn't care about folder names, `packages` name is just an example from their docs.

You have folders like `ring-ui/components/icon/` with `package.json` files in it. It makes babel to ignore your root `.babelrc` when compiling files inside `ring-ui/components/icon/` folder(s). The behaviour is [explained in Babel 7 docs](https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading).

**Comment by huston007** [comment]
Oh I see. I forgot that we have one more package.json in "icons" component
