### ISSUE TITLE
Transforming a Vue component node package

### ISSUE THREAD

**Issue by MechJosh0** [wallabyjs/public#1907]
### Issue description or question
I'm trying to get Wallaby to work with VueJS, TypeScript, and Jest. I'm running into an issue where I need a `node_module` package to be transpiled but isn't not listening to `jest.config.js:transformIgnorePatterns`. I tried adding a `jestConfig.transform` option into the wallaby configuration for the node package and it now produces a json error (note that I'm not using Webpack).

```js
SyntaxError: Unexpected token m in JSON at position 0
	at src/components/HelloWorld.vue:12
	at Object.<anonymous> src/components/HelloWorld.vue:14
	at Object.<anonymous> tests/unit/example.spec.js:2
```

If I instead have the wallaby configuration to be `jestConfig.transform = {}` I receive this error:
```js
node_modules\vue-spinner\src\ClipLoader.vue:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<template>
                                                                                         ^

SyntaxError: Unexpected token <

	at src/components/HelloWorld.vue:12
	at Object.<anonymous> src/components/HelloWorld.vue:14
	at Object.<anonymous> tests/unit/example.spec.js:2
```

### Wallaby.js test repo
https://github.com/MechJosh0/wallaby-vuejs

### Code editor or IDE name and version
PhpStorm: 2018.1.2

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo. I have sent you the [pull request](https://github.com/MechJosh0/wallaby-vuejs/pull/1) to make it work. All you need to do is to include the module with `.vue` source files to your `files` list. This way the module ends up in Wallaby cache and gets processed correctly.
