### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#191]
On startup, Wallaby fails to load some tests. If I edit any file, Wallaby picks up those tests.

Reproduction steps:
1. `git clone https://github.com/fixin-platform/backend-freshdesk.git`
2. `git checkout 52868dd06319083c98bc334fe7af5c4fb6531046`
3. `npm install`
3. Download [wallaby.local.js](https://www.dropbox.com/s/0t0iqo46fdkrze1/wallaby.local.js?dl=1)
4. Put `wallaby.local.js` in project root directory
5. Run Wallaby.

```
Sat, 11 Jul 2015 21:16:03 GMT wallaby:workers Loaded 2 test(s)
Sat, 11 Jul 2015 21:16:03 GMT wallaby:workers Sandbox (active) [lx11o] error: Maximum call stack size exceeded
Runtime error: Maximum call stack size exceeded
Sat, 11 Jul 2015 21:16:03 GMT wallaby:workers Failed to map the stack to user code, entry message: Maximum call stack size exceeded, stack: Maximum call stack size exceeded
Sat, 11 Jul 2015 21:16:03 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Sat, 11 Jul 2015 21:16:03 GMT wallaby:workers Sandbox [lx11o] is responsive, closing it
```

Environment:
1. Wallaby 1.0.24 (happy 2^10!)
2. WebStorm 9.0.3
3. Ubuntu 14.04

**Comment by ArtemGovorov** [comment]
The issue is that wallaby treats `test/Binding/responses/getUsers.json` as a test, because it is in the `tests` list and not excluded. If you change the patterns like this:

``` JavaScript
files: [
    "core/**/*.coffee",
    "lib/**/*.coffee",
    "test/mocha.coffee",
    "test/**/*.json"   // including all json files
  ],
  tests: [
    "test/**/*.coffee",  // only coffee files inside the folder are tests
    "!test/mocha.coffee", // except mocha.coffee :)
  ]
```

it should work. You may also consider using adding a suffix of `Spec` or `Test` to your test files and using a single pattern `test/**/*Spec.coffee` to make the convention more stable and avoid any issues if you add any non-test coffee files to the test folder.

**Comment by DenisGorbachev** [comment]
@ArtemGovorov yes, it fixes the issue. Thanks!

Frankly, I couldn't fully figure out the difference between `files` and `tests`. I thought that everything that belongs to tests, including fixtures, should be listed under `tests`.
