### ISSUE TITLE
TypeScript + Jest config + VSCode - not recognizing "import"

### ISSUE THREAD

**Issue by andrewconnell** [wallabyjs/public#1910]
### Issue description or question

I'm trying to get my TypeScript + Jest project working in Wallaby but can't get the config figured out. Running `jest --config ./jest.config.json` works just fine, so it's just a wallaby config issue.

Using the debug mode & console logs, I've been able to fix some of the special things in my Jest config and examine the instrumentation folder wallaby is using to make sure everything is there, including rewriting the `jest.setupFiles` to point to the correct location for some setup scripts.

However, from the debug console, jest isn't preprocessing the TypeScript before running it. I'm using ts_jest in my Jest config... I see both JS & TS files in the instrumentation folder... 

![image](https://user-images.githubusercontent.com/2068657/48221858-25c80b00-e361-11e8-8f97-06dc1ddd1f40.png)

...but I see jest errors with the generated JS not understanding the "import" keyword:

```
​​[Error] Runtime error: Jest encountered an unexpected token​​
​​[Error] This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.​​
​​[Error] By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".​​
​​[Error] Here's what you can do:​​
​​[Error]  • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.​​
​​[Error]  • If you need a custom transformation specify a "transform" option in your config.​​
​​[Error]  • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.​​
​​[Error] You'll find more details and examples of these config options in the docs:​​
​​[Error] https://jestjs.io/docs/en/configuration.html​​
​​[Error] Details:​​
​​[Error] ./scripts/rightmessage-tracking/RightMessage-Tracking_RightBar.spec.js:2​​
​​[Error] import 'jest';​​
​​[Error] ^^^^^^​​
​​[Error] SyntaxError: Unexpected token import​​
```

I thought it was due to an outdated version of Node, but in the setup I console.log it, confirming 8.11.2, so it should understand "import".

Ideas on what to look at? I've been scouring the docs and the sample projects in github you reference, but can't get this sorted. :(

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'tsconfig.json',
      'jest.config.json',
      'scripts/config/disableAppInsights.js',
      'scripts/rightmessage-tracking/*.ts', 
      '!scripts/rightmessage-tracking/*.spec.ts'
    ],

    tests: [
      'scripts/rightmessage-tracking/*.spec.ts'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',
    setup: function (wallaby) {
      console.log('Node.js', process.version);
      console.log('wallaby.projectCacheDir:', wallaby.projectCacheDir);
      const jestConfig = require('./jest.config.json');
      jestConfig.setupFiles = [wallaby.projectCacheDir + '/scripts/config/disableAppInsights.js'];
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.28.1
Wallaby Core v1.0.633

### OS name and version

OSX v10.14.1

### Jest config

```
{
  "moduleFileExtensions": [
    "ts", "js", "json"
  ],
  "rootDir": "./scripts",
  "setupFiles": [
    "<rootDir>/config/disableAppInsights.js"
  ],
  "testMatch": [
    "**/*.spec.ts"
  ],
  "testURL": "http://www.something.com/test.html",
  "transform": {
    "^.+\\.(ts|tsx)$": "ts-jest"
  },
  "verbose": true
}
```

**Comment by andrewconnell** [comment]
Resolved... #1748 helped a lot. Ends up I needed to specify the compiler in the config.

```
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
```

**Comment by joaogoya** [comment]
in which file?

**Comment by smcenlly** [comment]
@joaogoya - the file referenced in the last comment was the wallaby configuration file. If you are using automatic configuration and/or have a different problem, please create a [new issue](https://github.com/wallabyjs/public/issues/new) for us, we're happy to help.
