### ISSUE TITLE
Correct way to locate to node_modules

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#1911]
### Issue description or question

What's the correct way to locate `node_modules` from wallaby? I have a module that uses the typescript compiler API so I need to pass in some directories, including the `node_modules/@types` directory. Currently I'm doing that relative to the current module, but that breaks in wallaby due to node_modules not being relative to the module under wallaby.

I've read issue #1446, and adding the `node_modules/@types` to the config works.

My question is: Is there a way to find the project root location (possibly by doing something in `setup` in the wallaby config, then passing in that path. Adding node_modules to wallaby seems like a bad solution to this (however, if that's the way, then fair enough)

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version
OSX High Sierra

**Comment by smcenlly** [comment]
In node.js environments:

- `localProjectDir` string property returns the project local folder.
- `projectCacheDir` string property returns the project cache folder. Note that wallaby.js uses files from this folder to run tests. It copies the files specified in files and tests lists from `localProjectDir` to `projectCacheDir`.

These properties (and other details) are described in [our documentation](https://wallabyjs.com/docs/config/bootstrap.html#setup-function) for `setup` and `teardown`.

By default, wallaby will find your `require` / `imports` from your node_modules directory. If you (or one of your modules) are referencing node_modules outside of `require` or `import`, you may need to include your node_modules in your wallaby config `files` section (see example below). If you are doing this, we recommend only specifying the minimum set of node_modules you need as they will be copied to the `projectCacheDir` when wallaby starts.

```javascript
files: [
...
      { pattern:'node_modules/**/*', instrument: false },
...
]
```

You can also read how to configure node module hints in our [documentation for configuring node](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder).
