### ISSUE TITLE
Can Wallaby be configured to wrap live comment display values in the editor?

### ISSUE THREAD

**Issue by johnhamm** [wallabyjs/public#1916]
### Issue description or question
Can Wallaby be configured to wrap live comment display values in the editor?  Perhaps cosmetically temporarily covering up the lines below, or increasing the bottom margin of the original line to accomodate the wrapped text?  The use case would be for long JSON objects.

### Code editor or IDE name and version

Visual Studio Code v1.29.0

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Unfortunately that is not something that VS Code editor extension API supports.
Having said that, there are a few ways to view larger objects:
- if you hover over the line with the live comment (or use VS Code shortcut to show the hover), the logged value is displayed in the tooltip.
- if you call `Show line test(s)` command on the line with the long output, it will be displayed in the Wallaby Output.
- for even larger objects, you may use the recently introduced [Value Explorer feature](https://wallabyjs.com/docs/intro/value-explorer.html) to expand/inspect/copy objects of any depth.
