### ISSUE TITLE
Feature Request: Limit the output 

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1918]
Hi. Thanks for the amazing plugin, 4 years happy user now ;)

Currently, in VSCode wallaby puts all errors into output view top to bottom.
To find the first issue, I have to scroll up. I am doing a lot snapshot testing, and often such output is huge and I waste a LOT of time scrolling. Truth be told, I do not even care for what the output says, I am immediately clicking on "show side-by-side" and "update-snapshot".

1. Is there a possibility to remove the error output, or limit it to certain ammout of characters? Or,
2. Is there a possibility to output the errors so that I see the last errors on top, where my cursor would be? Or
3. Is there a possibility to have a dedicated view with the list of easily clickable errors? The ts-vscode plugin puts these in the list of errors and works quite well,

**Comment by smcenlly** [comment]
Have you tried using the output window's scroll lock?

![wallabytestscrolllock](https://user-images.githubusercontent.com/2074089/48679860-d5627000-ebe0-11e8-9dbc-0cc4c270cc0a.png)

**Comment by tomitrescak** [comment]
It still would be nice to have the possibility to limit output per item (currently it is only possible globally).

But the scroll lock will do for now ;)
