### ISSUE TITLE
jest.mock does not work in wallaby but it works in jest

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1920]
### Issue description or question

Hi, when running tests in wallaby, mocks are only correctly processed in jest.setup.js file. Any mocks that I do in test files are ignored. It is a Create React App 2.1 running with Typescript.

I can send a sample repo if need be. But before I'd like to ask if you have encountered this problem and if it has a solution.

for example, following

```js
import { HeaderAuthorised } from '../header_authorised';

jest.mock('../header_authorised', () => ({
  HeaderAuthorised: () => <div>ewewe</div> // this will only work when running tests with jest, in wallaby is ignored.
}));
```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  var path = require('path');
  process.env.NODE_ENV = 'test';
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: [
      { pattern: 'src/setupTests.ts', instrument: false },
      'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.ts?(x)'
    ],

    tests: ['src/**/*.test.ts?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: ['react-app']
        })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p =>
        require.resolve('react-scripts/' + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.29.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Can you try this change:

```diff
    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
-         presets: ['react-app']
+         presets: ['react-app', 'babel-preset-jest']
        })
    },
```

**Comment by tomitrescak** [comment]
Hi, thanks for the swift reply. Getting a cryptic message: `​​Postprocessor run failure: Failed to run preprocessors on src/setupTests.js, Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/tomi/Github/apps/corporator/client/node_modules/babel-preset-jest/index.js​​`

Trying to find out what it means.

**Comment by tomitrescak** [comment]
I think it does not work with a new Babel 7

**Comment by ArtemGovorov** [comment]
Right, what if you do:

```diff
    preprocessors: {
      '**/*.js?(x)': file =>
-       require('@babel/core').transform(file.content, {
+       require('babel-core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
-         presets: ['react-app']
+         presets: ['react-app', 'babel-preset-jest']
        })
    },
```

**Comment by ArtemGovorov** [comment]
If the above doesn't help too, could you please share a sample repo? I'll take a look and sort it out for you.

**Comment by ArtemGovorov** [comment]
Hmm, I'll definitely need a repo to see what's going on. I'd guess that the error is referring to some wallaby instrumentation instructions, but you have the `instrument: false` flag for that file, so it's not that.

**Comment by ArtemGovorov** [comment]
Maybe it's referring to the `withRouter` variable?

**Comment by tomitrescak** [comment]
Ah, that one could be ignored. I'll prepare the repo.

**Comment by tomitrescak** [comment]
Here it is: 
[Archive.zip](https://github.com/wallabyjs/public/files/2593506/Archive.zip)

**Comment by tomitrescak** [comment]
I'm trying to find a `src/setupTests.js` but it is not created, even when I turn the instrumentation on. Weird.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. Try this preprocessor:

```js
    preprocessors: {
      '**/*.js?(x)': file =>
      require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: file.path === 'src/setupTests.js' ? ['react-app'] : ['babel-preset-jest', 'react-app']
        })
    },
```

**Comment by tomitrescak** [comment]
@ArtemGovorov it's the object spread on this line `const { to, children, ...rest } = this.props;` if you change it to `const { to, children } = this.props;` and remove the use of `rest`. All works as normal. It must be some instrumentation / jest magic issue

**Comment by tomitrescak** [comment]
Yes, it has problems with all object spreads. Must be some unfortunate combination of babel trasnsforms.

**Comment by ArtemGovorov** [comment]
> I'm trying to find a src/setupTests.js but it is not created, even when I turn the instrumentation on. Weird.

It's because it fails to get created because of the error.

Wallaby VS Code output actually tells what variable is causing the issue:

`
​​Postprocessor run failure: Failed to run preprocessors on src/setupTests.js, Error: babel-plugin-jest-hoist: The module factory of `jest.mock()` is not allowed to reference any out-of-scope variables.​​
`
`
[Error] ​​Invalid variable access: __extends​​
`
`
[Error] ​​Invalid variable access: __rest
`

It is a result of TypeScript compilation of ES6 and ES next to ES5 (as configured in the `tsconfig.json`), and it is not happening when using `ts-jest` (used for normal Jest CLI run), because `ts-jest` must be configuring TypeScript compilation to use `esnext` as `target`.

If that's the case, then Wallaby can be configured similarly:

```js
module.exports = function(wallaby) {
  ...

  return {
    ...

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({target: 'esnext'})
    },

    preprocessors: {
      '**/*.js?(x)': file =>
      require('@babel/core').transform(file.content, {
          ...
          presets: ['babel-preset-jest', 'react-app']
        })
    },

    ...
  };
};
```

This way, Wallaby TypeScript compilation will be doing the same as `ts-jest` (not touching `extends`, object rest/spread, etc.), and leaving it to Babel to compile.

Here is the full working config for your sample repo:

```js
module.exports = function(wallaby) {
  var path = require('path');
  process.env.NODE_ENV = 'test';
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: [
      { pattern: 'src/setupTests.ts', instrument: false },
      'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.ts?(x)'
    ],

    tests: ['src/**/*.test.ts?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({target: 'esnext'})
    },

    preprocessors: {
      '**/*.js?(x)': file =>
      require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: ['babel-preset-jest', 'react-app']
        })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p =>
        require.resolve('react-scripts/' + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};

```

**Comment by NuclleaR** [comment]
@ArtemGovorov I faced with issue. Could you help me pls?

```
jest.mock('./EntityDetailsSection', () => ({
    EntityDetailsSection: jest.fn(() => <div />),
}));
```

```
[Error] Invalid variable access: _jsx 
[Error]  
[Error]   14 |         EntityDetailsSection: jest.fn(() => { 
[Error]   15 |             var $_$c = $_$wf(565); 
[Error] > 16 |             return $_$w(565, 2, $_$c), _jsx('div', {}, void 0); 
[Error]      |                                        ^^^^ 
[Error]   17 |         }) 
[Error]   18 |     }; 
[Error]   19 | });
```

**Comment by smcenlly** [comment]
@NuclleaR - if you are using a fairly recent version of React and Jest, then we recommend starting Wallaby with [Automatic Configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) instead of a configuration file. Unless you are using a very old version of react/Jest, then it should work for you if your tests are also working from the CLI.

If you are still having problems, could you please[ create a new issue ](https://github.com/wallabyjs/public/issues/new)and use automatic configuration and provide your Wallaby Diagnostics report (instructions for generating this are provided in the new issue template).
