### ISSUE TITLE
Help needed configuring wallaby to test a monorepo with aurelia and hoisted node_modules

### ISSUE THREAD

**Issue by kevinbeaudoin** [wallabyjs/public#1921]
### Issue description or question
We are having a hard time configuring wallaby to run our tests when our node_modules are hoisted using lerna.

Running our test using karma works perfectly but in order to be able to use wallaby, we must install all dependencies locally (npm install within packages\syncfusion-bridge folder).

Once we install locally our test runs without any issues.

We tried out several things but each time we are facing issues with aurelia.

### Wallaby.js configuration file
Please have a look at a sample repo that reproduce our issue.
https://github.com/kevinbeaudoin/aurelia-syncfusion-monorepo

### Code editor or IDE name and version

Visual Studio Code v1.29.1

### OS name and version

Windows 8.1

Thanks

**Comment by smcenlly** [comment]
Thanks for providing us with the repo, was extremely helpful for us to see your exact issue.

You were very close to having this working, you just needed to add another webpack module resolver for `path.join(__dirname, '../../node_modules')`.

I've created a [pull request](https://github.com/kevinbeaudoin/aurelia-syncfusion-monorepo/pull/1) for you with the updated wallaby configuration.

**Comment by kevinbeaudoin** [comment]
Awesome thanks a lot!

**Comment by kevinbeaudoin** [comment]
Leaving a note here just in case it would help other googling the same issue we had.  In our production code we had a package that was relying on Aurelia-Framework 1.2.0.  And this was causing us issues with WalalbyJS in a monorepo environment.  Turns out updating to 1.3.0 and adding fix proposed above fixed all issues.
