### ISSUE TITLE
Support PNPM

### ISSUE THREAD

**Issue by andrewconnell** [wallabyjs/public#1924]
### Issue description or question

Wallaby is working just fine for me when I use NPM or Yarn as my package manager, but PNPM is failing. 

After installing dependencies (`pnp install --shamefully-flatten`), when I run Wallaby, it fails with the **[Error] Runtime error: TypeError: Cannot read property '_jasmineAdapter' of undefined​​** error (*in the Wallaby console*).

After removing the **node_modules** folder and running either `yarn` or `npm installl`, wallaby correctly as expecting, finding tests and executing them.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      { pattern: './tsconfig.json', instrument: false},
      { pattern: './config/jest.config.json', instrument: false},

      'src/**/*.ts',
      
      '!src/**/*.spec.ts',
      '!src/**/*.scss.ts'
    ],
    tests: [
      'src/**/*.spec.ts'
    ],
    hints: {
      ignoreCoverageForFile: /istanbul ignore next/
    },
    env: {
      type: 'node'
    },
    testFramework: 'jest',
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs' })
    },
    setup: function (wallaby) {
      const jestConfig = require('./config/jest.config.json');
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.29.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
We have used PNPM, neither tested Wallaby with it, so I'll mark it as a feature request and we will investigate what is required to properly integrate with it.

**Comment by andrewconnell** [comment]
In the projects I'm using, you have to use the `--shamefully-flatten` flag due to some incorrectly referenced dependencies (by upstream dependencies). Ideally, the feature request would test for both conditions: one with & without this flag.

PNPM is > Yarn & NPM as it uses symbolic links to a central NPM cache on the user's machine, dramatically speeding up package acquisition & shrinking the project disk footprint. Maybe the fact it's not supported is how the internals of Wallaby's core is following paths / symbolic links. 

Not sure... just a tip when someone looks into implementing the feature. Awesome product... big fan :)

**Comment by ArtemGovorov** [comment]
I have just tried [our sample Jest repo](https://github.com/wallabyjs/wallaby-jest-snapshots), ran `pnpm install --shamefully-flatten`, and Wallaby is working as expected for me. 

Could you please share a sample repo where I could reproduce the mentioned issue?

**Comment by andrewconnell** [comment]
Even though I could repo this multiple times the other day, in trying to repo the issue for you, I can't get it to fail so nevermind... *closing*. #MyBad

**Comment by ArtemGovorov** [comment]
No worries at all, glad to heat it's working for you now.
