### ISSUE TITLE
Using Types in Describe block errors with: "... appropriate loader to handle this file type.​."

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#1925]
### Issue description or question
The Karma tests pass no problems.
Wallaby tests pass but at the end I see this:
​​Uncaught Error: Module parse failed: Unexpected token (13:12)​​
​​You may need an appropriate loader to handle this file type.​​
​​| describe("Landing", () => {​​
​​| ​​
​​> 	let sandbox: sinon.SinonSandbox;​​
​​| 	let authStub: sinon.SinonStubbedInstance<AuthorizationService>;​​
​​| ​​
​​at http://localhost:53410/__modules/1.js?1543004046596:1​​

In my beginning of the describe I'm using sinon types:
describe("Landing", () => {

	let sandbox: sinon.SinonSandbox;
	let authStub: sinon.SinonStubbedInstance<AuthorizationService>;

	let comp: Landing; 

Wallaby is having an issue with Types at this point. I have not have this problem in any other project I used Wallaby.

### Wallaby.js configuration file
I'm using this config file:
https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.29.0

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
- What is the original extension of the test file? Is it `.ts` or `.js`?
- Is the test file being imported from other files?

**Comment by whyld4900** [comment]
@ArtemGovorov sorry, I found the issue. Somehow I had:
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);

from https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/test.ts

in https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts

That was messing Wallaby up. But removed that and all good now.
Ty!
