### ISSUE TITLE
Error running 'wallaby-mocha.js': within webstorm 2018.3

### ISSUE THREAD

**Issue by kvernon** [wallabyjs/public#1928]
### Issue description or question
Recently I've updated webstorm to 2018.3. After doing so wallabjs fails to run. Unfortunately, the only thing I am able to capture is this from the event log window: **8:52 PM	Error running 'wallaby-mocha.js': com.intellij.util.ui.EmptyIcon.create(I)Ljavax/swing/Icon;**

### Wallaby.js configuration file (which is called wallaby-mocha.js)

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
      {pattern: 'node_modules/babel-polyfill/browser.js', instrument: false},
      {pattern: 'test/helpers/*.j*', instrument: false},
      'src/**/*.js*', '!build/**'
    ],
    testFramework: 'mocha',
    env: {
      type: 'node'
    },
    tests: [
      'test/unit/**/*tests.j*'
    ],
    compilers: {
      '**/*.j*': wallaby.compilers.babel()
    },
    delay: {
      run: 50
    },
    debug: true
  };
};

```

### Code editor or IDE name and version
WebStorm v2018.3 (note: wallabyjs works 2018.2.6, which is the previous version)

### OS name and version
Windows 1809

**Comment by ArtemGovorov** [comment]
This IntelliJ breaking change issue was fixed a couple of months ago - https://github.com/wallabyjs/public/issues/1817. Try downloading and installing [Wallaby plugin from our website](https://wallabyjs.com/download/) (the error may be blocking automatic update).
