### ISSUE TITLE
Cannot find module server.js

### ISSUE THREAD

**Issue by JoshWhite** [wallabyjs/public#1934]
Hey,

I loaded vscode this morning and Wallaby is hanging.

It gives the following output:

```
[Error] module.js:549​​
​​[Error]     throw err;​​
​​[Error]     ^​​
​​[Error] Error: Cannot find module '/Users/myUser/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.100/wallaby/server.js'​​
​​[Error]     at Function.Module._resolveFilename (module.js:547:15)​​
​​[Error]     at Function.Module._load (module.js:474:25)​​
​​[Error]     at Function.Module.runMain (module.js:693:10)​​
​​[Error]     at startup (bootstrap_node.js:191:16)​​
​​[Error]     at bootstrap_node.js:612:3​​
```

I've done the usual, stopped/started Wallaby, disabled/enabled, uninstalled/installed - basically turned it off and on again ;)

Issue looks similar to [this issue](https://github.com/wallabyjs/public/issues/699), but with VSCode. If it helps, I bought a licence in May, so shouldn't have expired. 

### Wallaby.js configuration file
NA - hasn't changed since last time

### Code editor or IDE name and version

Visual Studio Code v1.29.1.

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Looks like your Wallaby extension installation get corrupted somehow. This should help:
- close VS Code,
- open the `~/.vscode/extensions/` folder,
- delete all `wallabyjs.*` folders in there,
- start VS Code and install Wallaby extension.

**Comment by JoshWhite** [comment]
Yes, this worked. Thanks 👍

**Comment by JoshWhite** [comment]
For my future reference, on a Windows machine (mine at least), the path is as follows:
`C:\Users\{user}\.vscode\extensions `
