### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1940]
### Issue description or question

Hi, I'm using pnpm and I am getting the following error:

```​​Failed to initialize wallaby jest.​​
​​Error: Can not find install_common_globals path​​
​​    at Module._compile (internal/modules/cjs/loader.js:689:30)​​
​​    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)​​
​​    at Module.load (internal/modules/cjs/loader.js:599:32)​​
​​    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)​​
​​    at Function.Module._load (internal/modules/cjs/loader.js:530:3)​​
​​    at Module.require (internal/modules/cjs/loader.js:637:17)​​
​​    at require (internal/modules/cjs/helpers.js:20:18)​​
​​    at Module._compile (internal/modules/cjs/loader.js:689:30)​​
​​    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)​​
​​    at Module.load (internal/modules/cjs/loader.js:599:32)​​
​​    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)​​
​​    at Function.Module._load (internal/modules/cjs/loader.js:530:3)​​
​​    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)​​
​​    at startup (internal/bootstrap/node.js:266:19)​​
​​    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)​​
```

When running "npm test" .. with executing jest in the console all works as usual

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'package.json',
      'tsconfig.json',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg|graphql)',
      '!src/**/*.test.+(ts|tsx)'
    ],
    filesWithNoCoverageCalculated: [],
    tests: [
      'src/**/*.test.+(ts|tsx)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      initial: 1,
      regular: 1
    },
    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.29.1

### OS name and version

OSX Mojave

**Comment by tomitrescak** [comment]
Forgot to say, that when I flatten modules (similar to yarn) then all work fine.

**Comment by smcenlly** [comment]
Could you please provide us with a sample repo so we can duplicate the problem?

**Comment by ArtemGovorov** [comment]
> use pnpm instead of yarn or npm.

Sorry, I missed the bit that you are using `pnpm` from your original message.
Unfortunately the way `pnpm` installs modules by default is not supported by Wallaby. Having said that, the following command should install modules in a way that is supported:

`pnpm install --shamefully-flatten`

**Comment by tomitrescak** [comment]
Fair enough ;)

**Comment by dietergeerts** [comment]
Any way Wallaby can support this in the future? The reason to not flatten is to avoid phantom dependencies: https://rushjs.io/pages/advanced/phantom_deps/

**Comment by smcenlly** [comment]
@dietergeerts - what are you using as your testing framework? If you're using jest v24+, you should be able to use `pnpm` with our relatively new [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) feature. Please note that with `pnpm` your project must specify the dependencies needed by Wallaby to run automatic configuration:

```bash
pnpm install --save-dev jest jest-cli jest-runtime
```

**Comment by dietergeerts** [comment]
Karma for FE and plain mocha for BE. Though we got it working in the end.
