### ISSUE TITLE
Better support Sublime Text distraction free mode inline logging

### ISSUE THREAD

**Issue by lamartire** [wallabyjs/public#1944]
### Ugly logging into Sublime Text distraction free mode

![image](https://user-images.githubusercontent.com/13414205/50309299-64e49280-04af-11e9-9069-f7fb26cfb03a.png)

Hello! It is very different than logging into "common" mode. Does it possible to make it similar?
Thank you! ✨

### Wallaby.js configuration file

Configuration independent.

### Code editor or IDE name and version

Sublime Text v3 3176

### OS name and version

OSX 10.14.2

**Comment by ArtemGovorov** [comment]
We'll investigate why it is displayed differently. 
In a meantime, if the output is too distracting, you may turn it off completely by using the `inlineMessages` setting in the `Wallaby.sublime-settings` config:

```json
{
  ...
  "inlineMessages": false
}
```

**Comment by ArtemGovorov** [comment]
We have done some investigation and it looks like it's an issue/limitation in Sublime. We have raised the question at https://forum.sublimetext.com/t/phantom-is-not-centered-with-code-in-distraction-free-mode/41020. 

The best way to make it work for now is either to turn off inline comments are I have suggested above, or to change the [Distraction Free setting](https://www.sublimetext.com/docs/3/distraction_free.html) to avoid placing the code in the center of the screen:

```
"draw_centered": false,
```

**Comment by lamartire** [comment]
Thank you. I really want to have correct inline messages in distraction free mode, but in the "classic" view, I guess :)

**Comment by smcenlly** [comment]
Looks like Sublime fixed this 11 days ago. We'll take a look and see whether the Sublime Wallaby extension needs to be changed to support this fix.

https://github.com/SublimeTextIssues/Core/issues/2416

**Comment by smcenlly** [comment]
After the Sublime fix, this is working without any changes to Wallaby.

![image](https://user-images.githubusercontent.com/2074089/64088865-c5d6a100-cd86-11e9-8d06-1b4b0b49814b.png)
