### ISSUE TITLE
Copy Data in Wallaby panel in VSCode only seems to work on expanded nodes.

### ISSUE THREAD

**Issue by nerdo** [wallabyjs/public#1948]
### Issue description or question
`Copy Data` option in Wallaby panel in VSCode only works on expanded nodes. It's a little difficult to explain, but I did a screen recording here: https://d.pr/free/i/m3Hf9I

Basically, when data is console.log'd, there is an option to `Copy Data` from the wallaby panel, but it only seems to resolve nodes that are expanded in the view. As I expand nodes and re-run the Copy Data command, it will have the expanded bits of data.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: ['src/**/*.js', '!src/**/*.test.js'],

    tests: ['src/**/*.test.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    }
  }
}

```

### Code editor or IDE name and version

Wallaby.js 1.0.101
Visual Studio Code v1.30.1

### OS name and version

OSX 10.14

**Comment by smcenlly** [comment]
This behavior is actually by design to avoid circular dependency issues, but we'll consider how we can improve the copy experience, especially for `console.log` vs. Wallaby's `Live Comments` feature.

**Comment by nerdo** [comment]
Understood. I can totally understand needing to avoid cycles in an object, but when one tried to copy the data, it is misleading that only what had been visibly expanded gets resolved. It seems like the original object should just be used for the copy op?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ArtemGovorov** [comment]
> the original object

Could you please provide some more detail on what do you mean by "the original object" in the context of this issue?

**Comment by nerdo** [comment]
It just seems like the copy object operation is iterating over the object instead of just stringifying the original object that was console logged.

**Comment by ArtemGovorov** [comment]
@nerdo Yes, it is exactly how it's working and was designed to: 
- not every object that can be inspected can be stringify-ed,
- sometimes you may need to control what properties you'd like to copy (and you may now do it by expanding/collapsing certain nodes).

I suppose we can add a feature that allows to copy stringify-ed object via a separate menu option.

**Comment by ArtemGovorov** [comment]
We have introduced the [new feature to auto-expand object trees](https://medium.com/@wallabyjs/value-explorer-for-jetbrains-ides-wallaby-quokka-bundle-and-more-cdbbea7791e0#3ab1) with a special comment.
