### ISSUE TITLE
Error source highlighting

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#195]
Ситуация: в тестируемой функции два вложенных друг в друга callback-вызова.

И сообщение об ошибке отображается сразу в 2-х местах вызова. Довольно трудно сразу понять, где произошла ошибка.

Это  должна быть выделено, например красным фоном.

![пример](https://cdn.pbrd.co/images/1VyNsMDd.png)

**Comment by fvanwijk** [comment]
Please file issues in English so that everyone can reply to it and learn from it.

**Comment by ArtemGovorov** [comment]
The provided (screenshot?) link gives me `Not found` page.

**Comment by ArtemGovorov** [comment]
`Attempted to wrap ... which is already wrapped` error is fixed in https://github.com/wallabyjs/public/issues/194
