### ISSUE TITLE
Const enum import from a dependent project does not work

### ISSUE THREAD

**Issue by greyepoxy** [wallabyjs/public#1950]
### Issue description or question

When importing a const enum from a dependent project, running wallaby results in an error.

Looking at existing issues this seems to be the exact problem discussed here https://github.com/wallabyjs/public/issues/1541. I tried the work around described and that did not seem to work to resolve the problem.

I created a repository with a reproduction of the issue here https://github.com/greyepoxy/wallaby-import-const-enum-bug

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
      files: ['src/**/*.ts'],
      tests: ['test/foo.test.ts'],
  
      env: {
        type: 'node',
        runner: 'node',
      },
  
      testFramework: 'jasmine',

      compilers: {
        '**/*.ts': wallaby.compilers.typeScript({
          noResolve: false 
        })
      }
    };
  };
  
```

### Code editor or IDE name and version

Visual Studio Code v1.30.1

### OS name and version

Windows 10.0.15063 Build 15063

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. I have cloned it, however Wallaby works without any issues for me in the repo:

<img width="827" alt="screen shot 2018-12-29 at 10 01 48 am" src="https://user-images.githubusercontent.com/979966/50531123-e9d74800-0b50-11e9-86eb-d390254d3654.png">

I do get an error if I comment out `noResolve: false` however.

Could you please paste the reported error message?

**Comment by greyepoxy** [comment]
Thanks for taking a look!

hmm very weird... This is what I get with or without `noResolve: false`

![image](https://user-images.githubusercontent.com/11470527/50531173-90243e80-0aba-11e9-8b5e-a3bae2c43097.png)


This is the Console Output
```unix
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.637
​​​​​[Info]​​​​​ Finished executing 2 affected test(s)
```

And this is the Test Output
```unix
​​​​​1 failing test, 1 passing​​​​​
  
  ​​​​ does a thing​​​​ ​​​[4 ms]​​​​
    ​​​​
    ​​TypeError: Cannot read property 'VALUE' of undefined​​
      at Object.doAThing ​src/foo.ts:5:4​
      at UserContext.it ​test/foo.test.ts:5:8​
```

**Comment by greyepoxy** [comment]
Is there more information that I can provide to help figure this out?

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details, we'll investigate it further.

**Comment by ArtemGovorov** [comment]
We have found and fixed a bug related to path normalisation on Windows that was affecting your scenario. Please update to [the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and the issue should be resolved for you.

**Comment by greyepoxy** [comment]
I gave it a try today and it worked, thank you!
