### ISSUE TITLE
Support darcula theme in webstorm

### ISSUE THREAD

**Issue by martinsson** [wallabyjs/public#1953]
### Issue description 
It is virtually impossible to use the darcula theme in webstorm due to the fact that wallaby.js uses the same colors as in Light theme

<img width="553" alt="screenshot 2019-01-03 at 13 24 54" src="https://user-images.githubusercontent.com/182208/50637678-3a88df80-0f5b-11e9-948c-312bcbe67bb2.png">

### Wallaby.js configuration file
N/A

### Code editor or IDE name and version

WebStorm v2018.3.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please restart your IDE after changing the theme and Wallaby should apply correct colors.

**Comment by martinsson** [comment]
Oh that explains it, it seemed to me that it had worked before. Lately I've been switching a lot for presenting on retro-projectors and that's why I got the wrong colors and I didn't make the link.

Cheers for a great product!
