### ISSUE TITLE
Console.log "%c" meta-character confuses wallaby

### ISSUE THREAD

**Issue by msorens** [wallabyjs/public#1954]
### Issue description or question

I find wallaby's capabilities to reveal values both in-editor and in the output-console quite useful. But I encountered this small unsupported bit. The `console.log` command supports CSS formatting when those lines are output in the browser. But wallaby does not interpret it correctly.  It effectively ignores the "%c" formatter and thus shifts the remaining arguments out of place.
![image](https://user-images.githubusercontent.com/6817500/50739622-0a7a5000-1198-11e9-8909-08b729e0ab7a.png)

If I remove the "%c" and its corresponding argument, then Wallaby renders accurately like this:
![image](https://user-images.githubusercontent.com/6817500/50739628-149c4e80-1198-11e9-9603-d365507dc2f1.png)

Same issue occurs in the output-console:
![image](https://user-images.githubusercontent.com/6817500/50739633-1d8d2000-1198-11e9-895f-887269d0b7c4.png)

Would be nice if Wallaby would just ignore the "%c" *and* its corresponding argument.

### Wallaby.js configuration file

NA

### Code editor or IDE name and version

Visual Studio Code v1.30.1

### OS name and version

OSX High Sierra 10.13.6

**Comment by smcenlly** [comment]
Thanks for reporting this issue. We've updated our `console.log` handling to ignore `%c` parameters. This will be available in the next wallaby update, which will be released later today.
