### ISSUE TITLE
Using Wallaby with ndenv?

### ISSUE THREAD

**Issue by philipmw** [wallabyjs/public#1957]
### Issue description or question

I am trying to configure Wallaby on macOS. I use `ndenv`. Running `node` in a directory not explicitly configured for Node gives the following response:

    % node
    ndenv: node: command not found

    The `node' command exists in these Node versions:
      v10.15.0

I see this error in Wallaby's console:

    wallaby:nodeRunner Error in worker: ndenv: node: command not found

I understand I can probably fix this by enabling a global version of node, but I'd prefer to have better control over what software uses what version of node.

Changing the path to Node in IntelliJ's Configurations has no effect.

So I have a two-fold question:

1. Is it possible to give a path to a specific Node to Wallaby's workers? (As I said, configuring the path to Node in IntelliJ has no effect on this problem.)
2. Can you print the present working directory (pwd) of Wallaby in the debug log so I can configure a specific local version of Node in that directory?

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'src/**/*(\.test){0}.tsx'
    ],
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },
    tests: [
      'src/**/*.test.tsx'
    ],
    debug: "true"
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2018.3.2 (Ultimate Edition)

### OS name and version

macOS 10.13.6

**Comment by smcenlly** [comment]
**RE: 1**: it is possible to specify the path for Wallaby's workers to use. You will want to update your `env.runner` property of your wallaby.js configuration to point to the full path of your node executable.

**RE: 2**: we don't recommend this, as we create/delete directories as part of our instrumentation and internal shadow-copy process before running your files.

You can read more about configuring node in [our docs](https://wallabyjs.com/docs/integration/node.html).
