### ISSUE TITLE
some tests inexplicably skipped

### ISSUE THREAD

**Issue by msorens** [wallabyjs/public#1958]
### Issue description or question

I have seen a handful of other issues on this topic being reported but did not come across anything to shed a light on my particular issue.

When I start up wallaby in VSCode (Cmd + Shift + R, R), I shortly get a test result, e.g. 
![image](https://user-images.githubusercontent.com/6817500/50798256-97063a80-128c-11e9-894c-cf4ce61ca979.png)

I have noticed that the total number of tests in that status line can vary by a good 10 or 20% as I am working. I have not kept track of when it happens or what causes it to change so this might not be a very good issue report, but I found something I could report now to see if you might offer any suggestions. I had not really used the wallaby web app much, but fired that up today (running locally) and noticed several of the files reported zero time taken.
![image](https://user-images.githubusercontent.com/6817500/50798420-29a6d980-128d-11e9-9ff4-75f8d1055529.png)
Quantitatively, it looks like there are 25 files showing zero milliseconds (out of roughly a couple hundred files). At first glance, I thought there were no tests in those files. And in fact, attempting to expand the node in the browser resulted in no content.
![image](https://user-images.githubusercontent.com/6817500/50798597-c36e8680-128d-11e9-8706-edee2ac8daf2.png)
But I jumped to that file in my IDE and it definitely had tests. And the lines of code in the tests had white markers (indicating not run for some reason??). 

So I then ran those file tests (Cmd + Shift + R, F) and that did two things: bumped up the count in the VSCode status bar by the number of tests in that file... 
![image](https://user-images.githubusercontent.com/6817500/50798795-7212c700-128e-11e9-97a1-b49039a3289c.png)
... and revealed those test results in the web app as well with **no** action (refresh, button clicking) on my part.
![image](https://user-images.githubusercontent.com/6817500/50798708-22cc9680-128e-11e9-8635-684c3b5a64d6.png)

Just for completeness, here is the wallaby.js console output (once I turned off debug). There is one unrelated warning near the top, and the last 3 lines are the result of my doing the above manual test runs (Cmd + Shift + R, F) on 3 separate files.

```
[Info]​​​​​ Started Wallaby.js Core v1.0.641
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] DEPRECATION WARNING on line 4, column 10 of stdin:​​
​​[Error] Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.​​
​​[Error] Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.​​
​​[Error] Runtime error: Uncaught Error: Cannot find module '2521'​​
​​[Error] at http://localhost:63949/wallaby-webpack.js?1546901495656:1​​
​​​​​[Info]​​​​​ Execution progress: 50 tests
​​​​​[Info]​​​​​ Execution progress: 100 tests
​​​​​[Info]​​​​​ Execution progress: 150 tests
​​​​​[Info]​​​​​ Execution progress: 200 tests
​​​​​[Info]​​​​​ Execution progress: 250 tests
​​​​​[Info]​​​​​ Execution progress: 300 tests
​​​​​[Info]​​​​​ Execution progress: 350 tests
​​​​​[Info]​​​​​ Execution progress: 400 tests
​​​​​[Info]​​​​​ Execution progress: 450 tests
​​​​​[Info]​​​​​ Execution progress: 500 tests
​​​​​[Info]​​​​​ Execution progress: 550 tests
​​​​​[Info]​​​​​ Execution progress: 600 tests
​​​​​[Info]​​​​​ Execution progress: 650 tests
​​​​​[Info]​​​​​ Execution progress: 700 tests
​​​​​[Info]​​​​​ Execution progress: 750 tests
​​​​​[Info]​​​​​ Finished executing 761 affected test(s)
​​​​​[Info]​​​​​ Finished executing 1 affected test(s)
​​​​​[Info]​​​​​ Finished executing 6 affected test(s)
​​​​​[Info]​​​​​ Finished executing 26 affected test(s)
```
Any thoughts on why these tests are not being run initially?

### Wallaby.js configuration file

```javascript
/// This "config" file comes from https://github.com/wallabyjs/ngCliWebpackSample/ .
// There are only a couple tweaks needed for Automate-UI, noted inline.

var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      // 2017.09.30 Automate-UI: Added json-tree item to this list
      {pattern: 'src/app/page-components/json-tree/vendor/**/*.*', load: false, instrument: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      // 2017.09.30 Automate-UI: Set the test-runner to use chrome headless runner
      // instead of the default electron, since "ng test" also uses chrome headless.
      // Note that it is specified as just "chrome" here unlike in karma.conf.js,
      // and that wallaby passes in a --headless flag by itself.
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    // 2019.01.07 Automate-UI: only show important stuff in the console
    debug: false
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.30.1

### OS name and version

OSX High Sierra 10.13.6

**Comment by foxbunny** [comment]
I have noticed this as well. My assumption was that wallaby has its own way of figuring out what tests to run based on code coverage of the modified code. I'm not exactly sure how it does this and what tests it considers are candidates, but for me it always runs *at least* the tests for the code/tests I'm working on.

**Comment by ArtemGovorov** [comment]
Wallaby runs tests in parallel in a few workers. During the initial run, all specs are divided into `N` groups, where `N` is the [number of workers](https://wallabyjs.com/docs/config/workers.html). Each worker executes its group of specs. If during the execution of a group of specs some global error occurs (not inside a test), then if a testing framework can't continue executing the rest - the execution of the test group finishes. In case of an error, some of the specs may not be executed, hence the reported empty spec files and incomplete number of tests (because testing framework didn't even get to count those).

> the result of my doing the above manual test runs (Cmd + Shift + R, F) on 3 separate files.

When you later run specs individually, that bad spec that had caused the group of them to fail initially is not affecting them any more, so the pass and report correct numbers.

I'd recommend taking a look into that failing test (the one being reported as failing), as it seems that it stops Jasmine  (testing framework you're using), to keep executing any further tests. Might be some global error.

>  `Runtime error: Uncaught Error: Cannot find module '2521'​​`

This error reported in your Wallaby console may mean that one of your spec file imports another spec file.

Hope it explains things a bit and helps to find/fix the error affecting your tests.

**Comment by msorens** [comment]
Ah, had not considered that. The one error was actually about the jasmine clock. So I fixed that and that exposed another similar to what you mentioned, but could you tell me what this `2520` code means?
```
Uncaught Error: Cannot find module '2520'​​
```

**Comment by ArtemGovorov** [comment]
> but could you tell me what this 2520 code means?

It is an id that Webpack generates for modules. It's likely that that one of your spec file imports another spec file. You may add the `emitModulePaths` setting to make wallaby webpack emit module names instead of ids:

```diff
...
var webpackPostprocessor = wallabyWebpack({
+  emitModulePaths: true,
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],
   ...
```

**Comment by msorens** [comment]
Alas, that did not help very much:
```
​​Uncaught Error: Cannot find module '2520' (undefined)​​
```
I also searched for any import statements ending in "spec" to check for one importing another, per your suggestion, but that turned up nothing.
A web search also indicated that `require` calls are syntactically finicky and could cause webpack issue, but I have no `require` calls in my code base.
Other suggestions?
