### ISSUE TITLE
Generic wallaby.js

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#196]
```
module.exports = {
  files: [
    "**/*",
    "!*",
    "!.*/**/*",
    "!node_modules/**/*",
    "!**/*Spec.coffee"
  ],
  tests: [
    "test/**/*Spec.coffee"
  ]
}
```

This config works on a simple project, and it's fairly generic. Is there anything wrong with it? Should it be added to examples in http://wallabyjs.com/docs/config/files.html?

**Comment by ArtemGovorov** [comment]
Looks fairly generic with 2 notes though: 
- for CoffeeScript tests projects
- that is using node.js.

For browser test configs, there're potentially more root folders to exclude, such as `bower_components`, jspm modules, etc. Besides, browser configs are usually tech specific, so webpack configs have some webpack specific settings, etc. Also, unless using CommonJs, browser config often lists all libs/files in a certain order and using patterns only for tests.

However, from personal experience, I'd avoid including root `**/*` even for node projects, as I tend to have other folders and files that I don't want wallaby to know about (and watch/copy/instrument). For example various tmp folders like `bin` or `dist`, build system config files, like `gruntfile` or `gulpfile`, etc. 

So as a generic and language agnostic config for node.js, I'd rather suggest:

``` JavaScript
module.exports = {
  files: [
    "lib/**/*", // or "src/**/*"
  ],
  tests: [
    "test/**/*Spec.*"
  ]
}
```
If there're some more root files that need to be included, I think it's safer to include them manually in the files list.

Anyway, I don't think there's an ultimate generic config that will suite everyone, even `files/tests` lists section. One likes `test/**/*.Spec.*` convention, another one may use `spec/**/*.Test.*` one.

**Comment by fvanwijk** [comment]
You should put a Wallaby config generater on your website, which generates a config based on some parameters :)

**Comment by ArtemGovorov** [comment]
Heh, yeah I was thinking of providing some templates for typical environments. Someone has already started to create [yeoman generators for certain stacks of technologies](https://www.npmjs.com/package/generator-wallaby-webpack-react).

**Comment by DenisGorbachev** [comment]
Yes, you're right about root-level includes, I'll fix my config. Thanks for comments!
