### ISSUE TITLE
Ionic 4 / Angular 7 configuration

### ISSUE THREAD

**Issue by shuppert** [wallabyjs/public#1960]
### Issue description or question
I am unable to get a newly created Ionic 4/Angular 7 project working with WallabyJS.  I took the configuration from here: https://github.com/wallabyjs/ngCliWebpackSample#wallabyjs.  

I'm getting this error:
​​Uncaught Error: Cannot find module './ios-add-circle-outline.svg'​​
​​Module not found: Error: Can't resolve 'url-loader' in 'S:\AssistNG'ModuleNotFoundError: Module not found: Error: Can't resolve 'url-loader' in 'S:\AssistNG'​​
​​    at factory.create (S:\AssistNG\node_modules\webpack\lib\Compilation.js:797:10)​​
​​    at factory (S:\AssistNG\node_modules\webpack\lib\NormalModuleFactory.js:397:22)​​
​​    at resolver (S:\AssistNG\node_modules\webpack\lib\NormalModuleFactory.js:130:21)​​
​​    at asyncLib.parallel (S:\AssistNG\node_modules\webpack\lib\NormalModuleFactory.js:337:24)​​
​​    at S:\AssistNG\node_modules\neo-async\async.js:2825:7​​
​​    at S:\AssistNG\node_modules\neo-async\async.js:6886:13​​
​​    at S:\AssistNG\node_modules\neo-async\async.js:2825:7​​
​​    at done (S:\AssistNG\node_modules\neo-async\async.js:2922:13)​​
​​    at resolver.resolve (S:\AssistNG\node_modules\webpack\lib\NormalModuleFactory.js:447:23)​​
​​    at doResolve (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:184:12)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn0 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at resolver.doResolve (S:\AssistNG\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:5)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn0 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn0 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)​​
​​    at resolver.doResolve (S:\AssistNG\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:42:38)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn0 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:12:1)​​
​​    at resolver.doResolve (S:\AssistNG\node_modules\enhanced-resolve\lib\ModuleKindPlugin.js:23:37)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn0 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:15:1)​​
​​    at hook.callAsync (S:\AssistNG\node_modules\enhanced-resolve\lib\Resolver.js:238:5)​​
​​    at _fn2 (eval at create (S:\AssistNG\node_modules\tapable\lib\HookCodeFactory.js:32:10), <anonymous>:33:1)​​
​​    at args (S:\AssistNG\node_modules\enhanced-resolve\lib\forEachBail.js:30:14)​​
​​    at fs.stat (S:\AssistNG\node_modules\enhanced-resolve\lib\ModulesInHierachicDirectoriesPlugin.js:39:13)​​
​​    at S:\AssistNG\node_modules\graceful-fs\polyfills.js:282:31​​
​​    at FSReqWrap.oncomplete (fs.js:154:21)​​

### Wallaby.js configuration file

var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```javascript
import './polyfills';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone-testing';

import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

### Code editor or IDE name and version
Visual Studio Code v1.30.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
From the error message 

> ​​Module not found: Error: Can't resolve 'url-loader'

it looks like [url-loader](https://www.npmjs.com/package/url-loader) module is missing. Try installing the module, it should help, with the issue.

**Comment by shuppert** [comment]
That works.  Interesting that Ionic needs the extra package.  Thanks!

**Comment by ArtemGovorov** [comment]
> Interesting that Ionic needs the extra package.

Thanks for the note. Actually looks like Wallaby webpack config doesn't need it either. I have updated [our sample](https://github.com/wallabyjs/ngCliWebpackSample/commit/ff5379d5691b836a1f8191d87b75c527c575ae78#diff-4e87b2c6dcfa10beeaf6797eaa6c66ec) to use `raw-loader` instead. You may do the same and remove `url-loader` from your `package.json` dependencies.

**Comment by shuppert** [comment]
Excellent!  You rock @ArtemGovorov!
