### ISSUE TITLE
Cannot find module '../myCustomModule' using wallaby and quokka

### ISSUE THREAD

**Issue by kivi** [wallabyjs/public#1963]
### Issue description or question
I have Quokka and Wallaby running. And see the message Cannot find module ... in my mocha test.
The **test** file is in test directory. 
A index.js exists in the **models** directory.
If I run mocha, the test passes. Wallaby fails by requiring an existing module.

![image](https://user-images.githubusercontent.com/366163/51088480-69bffd80-1760-11e9-973a-cf4007367c67.png)

as code:
```javascript
const expect = require('chai').expect;
const db = require('../models');
const optinManager = require('../optinManager');
const Op = db.Sequelize.Op;

describe('optinManager tests', () => {
  // tests, which pass when I run mocha from cli
}
```

### Wallaby.js configuration file

```javascript
module.exports = function(w) {
    return {
        files: [ '*.js' ],
        tests: [ 'test/*.js' ],
        // tests: {pattern: ['test/**/*.ts'], load: false},
        // testFramework: 'mocha'

        env: {
            type: 'node'
        },
        testFramework: 'mocha'
    }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version
Windows 10

**Comment by smcenlly** [comment]
Your current configuration is only selecting `.js` files from your project's root directory (`files: [ '*.js' ]`). Your configuration needs to be updated to match sub-directories. 

Please find an updated wallaby configuration below. I've updated your config to specify that your application files are all `.js` files in your project *except* for those that live under the `test` directory in the your project root. I've also updated your config to specify that any `.js` file in the test directory or any directory underneath is a test file.

A handy tool to test your `files` and `tests` configuration patterns is [http://www.globtester.com/](http://www.globtester.com/).

You can also read more about the files and tests configuration in our [docs](https://wallabyjs.com/docs/config/files.html).

```javascript
module.exports = function(w) {
    return {
        files: [ 
            '**/*.js' 
            '!test/**/*.js' 
        ],
        tests: [ 
            'test/**/*.js' 
        ],

        env: {
            type: 'node'
        },
        testFramework: 'mocha'
    }
}
```

**Comment by kivi** [comment]
That makes sense, as the file to be testet also includes models, I assumed incorrectly, that Wallaby would parse that models/index.js as well.

That leads me to change the file structure. I have moved 'files' now in a directory called app. 'tests' remain where they are. Otherwise Wallaby would take too long to start. Maybe it is going through node_modules? It is definitely checking also on wallaby.js and other files in the root directory

Thank you

**Comment by ArtemGovorov** [comment]
> Maybe it is going through node_modules?

Yes, it was. You may exclude it like this:

```js
files: [ 
            '**/*.js', 
            '!test/**/*.js',
            '!node_modules/**' 
        ],
```
but specifying a dedicated source folder is a better solution anyway.

**Comment by kivi** [comment]
I have fixed the settings, now sometimes, when I create or change tests, they obviously fail. But when I fix them the box sometimes turn white... and a few minutes later or after restarting VS Code all boxes are white.

**Comment by smcenlly** [comment]
Please check for errors printed in the Wallaby Console output window; there may be an indication of what's going wrong there.

You may also try setting your configuration file [workers property](https://wallabyjs.com/docs/config/workers.html) to:

```javascript
...
     workers: {
       initial: 1,
       regular: 1,
       restart: true
     }
...
```
