### ISSUE TITLE
Using package.json to indicate module location 

### ISSUE THREAD

**Issue by traviswatsonws** [wallabyjs/public#1964]
### Issue description or question

I found this issue: https://github.com/wallabyjs/public/issues/660 that shows how to enable babel processing for modules through NODE_PATH specification.

There's another way to do this (load modules in your application as if they were in node_modules) by placing a `package.json` file in that folder with only a name, such as `{"name":"utilities"}`.  This allows you to reference stuff in that folder like `import { format } from 'utilities/date'` rather than `import { format } from '../../../utilities/date'`

Is there a way to configure wallaby to enable Babel for modules loaded like this?  This is only an issue with Wallaby, webpack and jest have no issues with this normally.

Here's a similar issue from a while back, but that workaround doesn't work in this situation; https://github.com/wallabyjs/public/issues/1201

### Wallaby.js configuration file

Standard for create-react-app: https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for the report. 
The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version.
