### ISSUE TITLE
include an otherwise ignored file pattern inside a specific folder

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1966]
### Issue description or question
Unable to include an otherwise ignored file pattern inside a specific folder.

https://wallabyjs.com/docs/config/files.html#pattern

> The pattern string property represents the file name or pattern. Each file is checked against patterns from the top of the list to the bottom. If a file satisfies multiple patterns, the **first file configuration (from the top of the list) with a matching pattern will be used for the file**. The rule applies to all file configuration properties, except the ignore property - **if a file pattern is marked as ignored, it will be ignored regardless of its position in the files/tests list**.

What is the reason ignore patterns ignore position? ~~I must be missing a use case here, but this seems like a big oversight / additional complexity.~~ (edit: I think this would cause the opposite issue I'm having)

Example: [chrisblossom/wallaby-issue-1966](https://github.com/chrisblossom/wallaby-issue-1966)

### Wallaby.js configuration file

```javascript
'use strict';

const ignore = [
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/build/**',
    '!**/coverage/**',
    '!**/.git/**',
    '!**/.idea/**',
    '!**/.vscode/**',
    '!**/.cache/**',
    '!**/.DS_Store/**',
    '!**/flow-typed/**',
];

const wallaby = (wallabyInitial) => {
    /**
     * Needed for monorepo
     */
    process.env.NODE_PATH = require('path').join(
        wallabyInitial.localProjectDir,
        '../../node_modules',
    );

    return {
        files: [
            ...ignore,
            { pattern: '*', instrument: false },
            { pattern: '.*', instrument: false },
            { pattern: '**/__sandbox__/**/*', instrument: false },
            { pattern: '**/__sandbox__/**/.*', instrument: false },
            '**/*.+(js|jsx|ts|tsx)',
            '!**/*.test.+(js|ts)',
            { pattern: '**/.*', instrument: false },
            { pattern: '**/*', instrument: false },
        ],

        tests: [...ignore, '!**/__sandbox__/**', '**/*.test.+(js|ts)'],

        compilers: {
            'src/**/*.+(js|jsx)': wallabyInitial.compilers.babel(),
            '**/*.+(ts|tsx)': wallabyInitial.compilers.babel(),
        },

        hints: {
            ignoreCoverage: /ignore coverage/,
        },

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: (wallabySetup) => {
            /**
             * link node_modules inside wallaby's temp dir
             *
             * https://github.com/wallabyjs/public/issues/1663#issuecomment-389717074
             */
            const fs = require('fs');
            const path = require('path');
            const realModules = path.join(
                wallabySetup.localProjectDir,
                'node_modules'
            );
            const linkedModules = path.join(
                wallabySetup.projectCacheDir,
                'node_modules'
            );

            try {
                fs.symlinkSync(realModules, linkedModules, 'dir');
            } catch (error) {
                if (error.code !== 'EEXIST') {
                    throw error;
                }
            }

            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             *
             * reset to expected wallaby process.cwd
             */
            process.chdir(wallabySetup.projectCacheDir);

            try {
                require('@babel/polyfill');
                // eslint-disable-next-line no-empty
            } catch (error) {}
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            wallabySetup.testFramework.configure(jestConfig);

            try {
                /**
                 * Run custom wallaby setup script
                 */
                require('./wallaby.setup.js')(wallabySetup);
                // eslint-disable-next-line no-empty
            } catch (error) {}
        },
    };
};

module.exports = wallaby;
```

### Code editor or IDE name and version

```
WebStorm 2018.3.3
Build #WS-183.5153.33, built on January 8, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

### OS name and version

``macOS 10.14.2``

**Comment by ArtemGovorov** [comment]
> What is the reason ignore patterns ignore position?

Generally speaking, it's common in many libraries for applications for ignore or excludes to take precedence (including karma and jest). For example, any patterns in the `testPathIgnorePatterns` Jest setting will override patterns in the `testMatch` setting. It's just in Wallaby those two settings can be specified combined in the `files`/`tests` list, otherwise it's the same behaviour as in Jest/Karma.

Unfortunately we cannot change the default behavior as we would almost certainly break wallaby configuration for existing users.

For your specific case, if what you are trying to achieve is to exclude the `lib/__sandbox__/sandbox.test.js` file from tests (because you don't want to run it as a test), but still want to include it as a file, the solution would is:

```js
        files: [
            ...ignore,
            { pattern: '*', instrument: false },
            { pattern: '.*', instrument: false },
            { pattern: '**/__sandbox__/**/*', instrument: false },
            { pattern: '**/__sandbox__/**/.*', instrument: false },
            '**/*.+(js|jsx|ts|tsx)',
            '!**/!(__sandbox__)/*.test.+(js|ts)', // <---
            { pattern: '**/.*', instrument: false },
            { pattern: '**/*', instrument: false },
        ],

        tests: [...ignore, '**/!(__sandbox__)/*.test.+(js|ts)'], // <---
```

I have also sent you the [pull request with the change](https://github.com/chrisblossom/wallaby-issue-1966/pull/1).

**Comment by chrisblossom** [comment]
Thanks @ArtemGovorov! I agree it shouldn't change, just trying to figure out how to work around it.

The PR doesn't seem to 100% work.

See: https://github.com/chrisblossom/wallaby-issue-1966/commit/6ce42913f0956606aee319458aba63ccde0baeae

**Comment by ArtemGovorov** [comment]
Sent another PR https://github.com/chrisblossom/wallaby-issue-1966/pull/2. A slightly more mind-twisting solution would be to extend the `!**/!(__sandbox__)/*.test.+(js|ts)` pattern to include subfolders, but I can only think of the solution that includes glob brace expansion, and unfortunately Java minimatch version doesn't support them (so it won't work in WS).

**Comment by ArtemGovorov** [comment]
After some more thinking, I have come up with another solution https://github.com/chrisblossom/wallaby-issue-1966/pull/3 (that doesn't need `read-dir-deep`):

```js
        files: [
            ...ignore,
            { pattern: '*', instrument: false },
            { pattern: '.*', instrument: false },
            { pattern: '**/__sandbox__/**/*', instrument: false },
            { pattern: '**/__sandbox__/**/.*', instrument: false },
            '**/!(*.test).+(js|jsx|ts|tsx)',
            { pattern: '**/.*', instrument: false },
            { pattern: '**/!(*.test).*', instrument: false },
        ],

        tests: [...ignore, '**/*.test.+(js|ts)', '!**/__sandbox__/**/*'],
```

**Comment by chrisblossom** [comment]
That looks to have worked. Thank you!
