### ISSUE TITLE
​​​​​0 failing tests, 0 passing​​​​​

### ISSUE THREAD

**Issue by SeanSobey** [wallabyjs/public#1971]
### Issue description or question

My same configuration and setup has been working for a while, and works in an earlier version (v1.0.638), since upgrading none of my tests are being discovered.

The Wallaby Console seems to indicate the tests are still being executed (`Finished executing 1895 affected test(s)`). 

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test';

//https://wallabyjs.com/docs/config/overview.html
module.exports = function (wallaby) {
	return {
		files: [
			{ pattern: 'tests/helpers/**/*.js', instrument: false },
			{ pattern: 'locale/**/*', instrument: false },
			{ pattern: 'images/**/*', instrument: false, binary: true },
			{ pattern: 'src/**/*.{css,html,svg,handlebars,json}', instrument: false },
			{ pattern: '/config/**/*', instrument: false },
			"!**/*.wip.ts",
			'!src/**/*.spec.ts',
			'src/**/*.{ts,js}',
		],
		tests: [
			"!**/*.wip.spec.ts",
			'!src/**/*.e2e.spec.ts',
			'src/**/*.spec.ts'
		],
		env: {
			type: 'node',
			runner: 'node',
			params: {
				//env: 'NODE_ENV=test;'
			}
		},
		testFramework: 'jasmine',
		setup: (wallaby) => {
			console.log('Node Version:', process.version);
			console.log('Jasmine Version:', wallaby.testFramework.coreVersion());
			console.log('NODE_ENV:', process.env.NODE_ENV);

			require('./src/ModuleExtensions');	// Load custom node Module Extensions

			//require('./tests/helpers/error');	// Wallaby JS has built in error handling
			require('./tests/helpers/moment-range');
			require('./tests/helpers/numeral');
			require('./tests/helpers/sourceMapSupport');

			require('./src/Moment/locale');	// Load custom moment langs
			require('./src/Numeral/locale');	// Load custom numeral langs
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Thanks for reporting the issue. Did you try version v1.0.639? Knowing exactly what version stops working would help us to isolate the problem.

We'll take a look at what's changed between versions. If you're able to send us a sample repo that has the same problem, we'd also appreciate that.

**Comment by smcenlly** [comment]
Could you also provide us with a copy of your `Wallaby.js Console` output channel for the broken version?

**Comment by SeanSobey** [comment]
Yes, from `v1.0.639` was broken. I say was because I just downloaded the latest version `v1.0.647` (I was using `wallaby.noAutomaticInstall`) and the problem looks to have gone away!

Switching back to `v1.0.639` replicates the issue but the latest version works. So I will resume using the latest wallaby verisons and reopen this issue if it returns.
