### ISSUE TITLE
Wallaby icon no longer appearing on bottom right hand corner of WebStorm

### ISSUE THREAD

**Issue by andrewryan1906** [wallabyjs/public#1972]
### Issue description or question
When I first installed Wallaby, there was an icon on the bottom right hand corner of my WebStorm window that was green if all tests were passing, and red if they weren't. This icon no longer appears.

Without it, I don't know if my tests are all passing without switching to the Wallaby explorer window, which makes Wallaby less efficient for TDD development.

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            'config.js',
            'src/**/*.js',
            'tests/json/**/*',
        ],

        tests: [
            'tests/unit/**/*spec.js'
        ],
        testFramework: 'mocha',
        setup: function () {
            global.expect = require('chai').expect;
        },
        env: {
            type: 'node',
            runner: 'node'
        }
    };

};
```

### Code editor or IDE name and version

WebStorm 2018.3.3

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Can you check whether you have the status bar enabled? In WebStorm, View->Status Bar should be checked.

![image](https://user-images.githubusercontent.com/2074089/51354654-00ddda00-1b00-11e9-918e-9b25fd318c76.png)
