### ISSUE TITLE
TypeError: Cannot read property 'getComponentFromError' of null

### ISSUE THREAD

**Issue by Janatbek** [wallabyjs/public#1976]
### Issue description or question
Getting this error:
TypeError: Cannot read property 'getComponentFromError' of null

### Wallaby.js configuration file
[same as this](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js)

### Code editor or IDE name and version
WebStorm 2018.2.5

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I'm assuming the issue is resolved by https://github.com/wallabyjs/ngCliWebpackSample/pull/41.
