### ISSUE TITLE
Loading .graphql and .gql files by a pattern doesn't work

### ISSUE THREAD

**Issue by lgandecki** [wallabyjs/public#1979]
### Issue description or question

I'm trying to use .gql or .graphql files in my tests but it doesn't work through wallabyjs (works through jest)
the problem is, the pattern seems to ignore files different than .ts and .js, I have to manually add every single graphql/gql file:

https://github.com/TheBrainFamily/test-driven-and-typed-graphql-server/blob/differentSchema/wallaby.js#L10

      'src/generatedQueries/mutations/itemAdd.gql',

this will end up the only file visible in the original and instrumented folder.

all those patterns get ignored:

      { pattern: "src/generatedQueries/mutations/*.qql"},
      "src/generatedQueries/queries/**.qql",
      "src/generatedQueries/queries/*.qraphql",
      {pattern: "src/generatedQueries/**/*.qraphql" },

Please help. :-)

### Wallaby.js configuration file

https://github.com/TheBrainFamily/test-driven-and-typed-graphql-server/tree/differentSchema

### Code editor or IDE name and version

WebStorm v?

### OS name and version

OSX

**Comment by smcenlly** [comment]
It seems like your `test-driven-and-typed-graphql-server` is a private repo, and we don't have access. 

Can you please copy/paste your `wallaby.js` configuration for us to take a look?

**Comment by lgandecki** [comment]
sorry not sure why it was private. I made it public now @smcenlly
