### ISSUE TITLE
Problem with default imports: xxxxx_1.default is not a function (AngularCLI/lodash)

### ISSUE THREAD

**Issue by fergusg** [wallabyjs/public#1980]
### Issue description or question

Using a clean install of `ngCliWebpackSample`

```bash
$ git clone https://github.com/wallabyjs/ngCliWebpackSample.git
$ cd ngCliWebpackSample
$ yarn
$ yarn add lodash
```

Importing a  "default" module as

```javascript
import invert from 'lodash/fp/invert';
[...]
constructor() {
    invert({});
}
```

This fails in WallabyJS with

```
TypeError: invert_1.default is not a function
      at new AppComponent  src/app/app.component.ts:14:4
```

This works fine with vanilla `ng-cli` (test, build, etc).

Workaround is to change the above to:

```javascript
import {invert} from 'lodash/fp';
```

Apart from the inconvenience of changing my code, I have a working assumption that the first import is significantly better for tree-shaking (which may be wrong!)

### Wallaby.js configuration file

Unchanged from `ngCliWebpackSample`

### Code editor or IDE name and version

Visual Studio Code 
```
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.13.16-100.fc25.x86_64
```

### OS name and version

Linux (Fedora)

**Comment by ArtemGovorov** [comment]
This [Wallaby config change](https://github.com/wallabyjs/public/issues/1973#issuecomment-455391493) should help:

```diff
var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

-compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) { 
```
