### ISSUE TITLE
Wallaby path resolve in tests files

### ISSUE THREAD

**Issue by baartko** [wallabyjs/public#1984]
### Issue description or question
It's more question not REAL wallabyjs issue.
I am running custom CRA version, that's why problem exists.
So I just paste wallaby.js configuration for CRA from documentation.
Also I have tested with original CRA app, and there's no issue at all.

### What's the issue
Wallaby cannot correctly resolve paths.

__App.spec.js__
`import mock from './mock`
`import sth from './components/something/test'`

So probably it points somewhere else ('./')

### Note
Was trying to solve it on my own based on already submitted issues, but with no success.

### The question is
What's the possible solutions, what mechanism should I use to make it work?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

    // Babel, jest-cli and some other modules may be located under
    // react-scripts/node_modules, so need to let node.js know about it
    var path = require('path');
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(__dirname, 'node_modules/react-scripts/node_modules');
    require('module').Module._initPaths();

    return {
        files: [
            'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
            '!src/**/*.test.js?(x)'
        ],

        tests: ['src/**/*.test.js?(x)'],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel({
                presets: ['react-app']
            })
        },

        setup: wallaby => {
            const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
            Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: 'jest'
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.25.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> I am running custom CRA version, that's why problem exists.

Please share a sample repo demonstrating the issue, we are happy to take a look.

**Comment by baartko** [comment]
I have created a base app using that custom CRA, and there's no issue, so it must be something project related.
Anyway, I will submit an update here when it'll be resolved, maybe it will be useful to the others.

**Comment by smcenlly** [comment]
We'll close this issue for now, happy to reopen it if you decide to post a sample repo with an issue.
