### ISSUE TITLE
Feature Request: support Jest's todo

### ISSUE THREAD

**Issue by borislit** [wallabyjs/public#1985]
I would be totally cool for wallaby to take Jest new "todo" tests into the account and show them distinctively both inline and in the console.
 https://jestjs.io/blog/2019/01/25/jest-24-refreshing-polished-typescript-friendly#testtodo
![image](https://user-images.githubusercontent.com/1139234/51852553-007ae580-232f-11e9-9d68-d32012f6fe21.png)

**Comment by smcenlly** [comment]
We're currently working on a large project to improve our jest integration. Thanks for the feedback, we'll consider this request at the same time.

**Comment by NikGovorov** [comment]
Hi All,

The feature was implemented and released in the latest version of the editor extensions, core and wallaby app.

![vsc_jb_app_skipped_todo](https://user-images.githubusercontent.com/129254/83219550-fc293b80-a1b3-11ea-8f07-9b63e50fb88e.gif)
