### ISSUE TITLE
​​[Error] Failed to set up project file system

### ISSUE THREAD

**Issue by KingHenne** [wallabyjs/public#1988]
### Issue description or question

Since today wallaby fails to start for [sinnerschrader/feature-hub](https://github.com/sinnerschrader/feature-hub) with errors like this (on varying files):

```
​​[Error] Failed to set up project file system: Error: Failed to parse packages/demos/src/watch-demo.ts, SyntaxError: Unexpected token (24:10)​​
​​[Error]     at process.emit (events.js:182:13)​​
​​[Error]     at emit (internal/child_process.js:812:12)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:63:19)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:61:11)​​
```

We didn't do any changes to the wallaby config, jest or babel (with a lock file), and it worked just fine until yesterday.

### Wallaby.js configuration file

```javascript
// @ts-check

function setup({projectCacheDir, testFramework}) {
  const jestConfig = require('./jest.config');

  delete jestConfig.globalSetup;
  delete jestConfig.globalTeardown;

  jestConfig.moduleNameMapper = {
    '^@feature-hub/([^/]+)$': projectCacheDir + '/packages/$1/src'
  };

  testFramework.configure(jestConfig);
}

module.exports = wallaby => ({
  files: [
    'jest.config.js',
    'scripts/setup-test-framework.js',
    'packages/*/src/**/*.{ts,tsx,snap}',
    '!packages/*/src/**/*.test.{ts,tsx}'
  ],
  tests: [
    'packages/*/src/**/*.test.{ts,tsx}',
    '!packages/demos/src/**/*.test.{ts,tsx}'
  ],
  env: {type: 'node', runner: 'node'},
  setup,
  testFramework: 'jest',
  compilers: {
    '**/*.ts?(x)': wallaby.compilers.babel()
  }
});
```

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version

macOS 10.14.2 (18C54)

**Comment by ArtemGovorov** [comment]
We can't reproduce the issue with the same editor and OS version. Just cloned the repo, ran `yarn`, started Wallaby and here is the result I'm getting:

```
​​​​​0 failing tests, 187 passing​​​​​
```

<img width="615" alt="screen shot 2019-01-31 at 7 33 25 pm" src="https://user-images.githubusercontent.com/979966/52045015-40400800-258f-11e9-9afb-f48eb44d73f3.png">

Also we haven't changed Wallaby core for about 3 days, the latest extension release was targeting a very small Windows specific change.
 
Maybe it's some caching issue - try touching your Wallaby config (adding a line break will do), saving it, and restarting Wallaby to see if it helps.

**Comment by KingHenne** [comment]
Thanks for the quick check! Your guess was probably right, since restarting VSCode fixed the issue. Before, I only tried the "Reload Window" command, which did not have an effect.

**Comment by KingHenne** [comment]
The issue re-appeared and now restarting VSCode does not fix it anymore. Do you have a hint, what cache files I would need to delete manually?

**Comment by smcenlly** [comment]
If you have deleted the extension directory, you will have deleted Wallaby's cache. The problem may be that you are using `jest` and the jest cache is corrupted. From your project directory, try running `jest --showConfig`. The config will include an entry, `cacheDirectory`. Once you have identified the `cacheDirectory`, delete all files/folders in that directory and restart Wallaby.

**Comment by KingHenne** [comment]
Unfortunately that didn't fix the issue. Any other ideas? (For what it's worth, wallaby still works on my colleague's machine in the same repo.)

**Comment by ArtemGovorov** [comment]
Try touching your Wallaby config (adding a line break will do), saving it, and restarting Wallaby to see if it helps.

**Comment by KingHenne** [comment]
That did not help.

**Comment by ArtemGovorov** [comment]
Just tried the latest version of the repo, and I can't reproduce the issue unfortunately, 200 tests are passing.

Please do the following:
- stop Wallaby,
- delete the `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.109/projects` folder,
- start Wallaby,
- share the full output from the Wallaby Console output channel when after you start Wallaby,
- zip the `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.109/projects` folder and attach the archive.

**Comment by KingHenne** [comment]
**Wallaby.js Console**:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.651
​​​​​[Info]​​​​​ Wallaby App (realtime reports) is available at: http://localhost:51245
```

**Wallaby.js Tests**:

```
[Error] ​​Failed to parse packages/demos/src/watch-demo.ts, SyntaxError: Unexpected token (24:10)​​
[Error] ​​    at process.emit (events.js:182:13)​​
[Error] ​​    at emit (internal/child_process.js:812:12)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:63:19)​​
```

[projects.zip](https://github.com/wallabyjs/public/files/2831550/projects.zip)

**Comment by KingHenne** [comment]
If I restart wallaby (after initial start), the **Wallaby.js Console** has this output:

```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.651
​​[Error] Failed to set up project file system: Error: Failed to parse packages/demos/src/watch-demo.ts, SyntaxError: Unexpected token (24:10)​​
​​[Error]     at process.emit (events.js:182:13)​​
​​[Error]     at emit (internal/child_process.js:812:12)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:63:19)​​
​​[Error]     at process._tickCallback (internal/process/next_tick.js:61:11)​​
```

**Comment by ArtemGovorov** [comment]
Thanks. Try checking if any of the following folders exist:

- `~/.vscode/extensions/node_modules`
- `~/.vscode/node_modules`
- `~/node_modules`

and if it does, try deleting it, touching Wallaby config and restarting it.

Also try modifying your Wallaby config as follows:

```diff
  files: [
    'jest.config.js',
    'scripts/setup-test-framework.js',
    'packages/*/src/**/*.{ts,tsx,snap}',
    '!packages/*/src/**/*.test.{ts,tsx}',
+   {pattern: 'packages/demos/src/**/*.{ts,tsx}', instrument: false}
  ],
```

and if the error changes after it, please share the new error.

**Comment by ArtemGovorov** [comment]
Also 
- have you changed/upgraded your node version recently? 
- what does running `node -v` in your terminal print?
- do you have [`wallaby.node` setting overridden in your VS Code settings](https://wallabyjs.com/docs/intro/install.html#nodejs-1)?

**Comment by ArtemGovorov** [comment]
EDIT (had it wrong in my previous comment): 

Also try modifying your Wallaby config as follows:

```diff
  files: [
+   {pattern: 'packages/demos/src/**/*.{ts,tsx}', instrument: false},
    'jest.config.js',
    'scripts/setup-test-framework.js',
    'packages/*/src/**/*.{ts,tsx,snap}',
    '!packages/*/src/**/*.test.{ts,tsx}'
  ],
```

and if the error changes after it, please share the new error.

**Comment by KingHenne** [comment]
- The three `node_modules` folders do not exist.
- Changing the Wallaby config as suggested in https://github.com/wallabyjs/public/issues/1988#issuecomment-460581233 leads to a similar error on another file:

    ```
    [Error] ​​Failed to parse packages/core/src/__tests__/feature-app-manager.test.ts, SyntaxError: Unexpected token (147:16)​​
    [Error] ​​    at process.emit (events.js:182:13)​​
    [Error] ​​    at emit (internal/child_process.js:812:12)​​
    [Error] ​​    at process._tickCallback (internal/process/next_tick.js:63:19)​​
    ```
- I sometimes switch between Node 8 and 10 using `nvm`. Currently I use `v10.14.1` (not changed in the last few days!).
- `wallaby.node` is not set in my settings.

**Comment by KingHenne** [comment]
I just noticed, if I remove the `compilers` config, wallaby can start successfully, and only the tests fail that rely on the `jest.mock` hoisting.

**Comment by ArtemGovorov** [comment]
Could you please try 
- specifying Node 8 path in your [`wallaby.node` setting in VS Code settings](https://wallabyjs.com/docs/intro/install.html#nodejs-1), 
- delete the `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.109/projects` folder,
- run Wallaby.

**Comment by ArtemGovorov** [comment]
The issue is that `try {} catch {}` ([optional catch binding](https://github.com/tc39/proposal-optional-catch-binding)) is supported since node 10, and Wallaby parser doesn't yet support it. So when you are using node 10 to run Wallaby (and compile TS code with `['@babel/preset-env', {targets: {node: 'current'}}]`), it fails to parse `try {} catch {}`. 

We'll be looking into adding the support shortly. In meantime you may:
- keep having node 8 in your VS Code settings,
- or replace all `try {} catch {}` blocks (you only have 3 of them), with `try {} catch (e) {}`.

**Comment by KingHenne** [comment]
Thanks a lot for investigating this and explaining the cause of the issue!
