### ISSUE TITLE
Feature Request: Copy and navigate to line

### ISSUE THREAD

**Issue by johan-vd-merwe** [wallabyjs/public#1989]
### Two small enhancements to the Wallaby App
- In the Wallaby App, the right click context menu has copy disabled - would be nice to copy code
- You can already navigate to the file (Webstorm) using the treeview - would be nice if you could do the same in the code window but additionally also to the correct line number (for instance clicking on the line number in code window gutter)

**Comment by NikGovorov** [comment]
Hi @johan-vd-merwe,

Thanks for the suggestions, we implemented and released them as part of 1.0.48 release:

- `Ctrl+C` (Windows/Linux) and `Cmd+C` (Mac) for copying;
- `Shift+Alt+G` (Windows/Linux) and `Ctrl+Shift+G` (Mac) for synchronizing opened file and cursor position from Wallaby App's code viewer to IDE editor.
