### ISSUE TITLE
Lerna, Typescript, RCA example

### ISSUE THREAD

**Issue by rhysawilliams2010** [wallabyjs/public#1993]
### Issue description or question
Hi @ArtemGovorov,

I am trying to get wallabyjs working on a lerna repo using RCA and typescript. I've tried a combination of the various examples on your site, but I can't get it working.

I notice that you may have resolved a very similar problem [here](https://github.com/wallabyjs/public/issues/1503) but I can't see your code. 

Please can you share an example lerna, RCA, typescript wallaby.js

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version
IntelliJ IDEA v2018.3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Here's the source code with my change for the mentioned repo - https://github.com/ArtemGovorov/lerna-wallaby-react-typescript/tree/patch-1. If the config doesn't help, please create a sample repo with Wallaby config that is not working for you, we are happy to jump in and help.
