### ISSUE TITLE
Inconsistant behavior between mocha and wallabyjs regarding before/after global hooks

### ISSUE THREAD

**Issue by stf8** [wallabyjs/public#1994]
### Issue description or question

I use a global hook file which contains before/after hooks. While mocha only executes those hooks once even though they are required in every tests, it seems wallabyjs executes global hooks for each test. This is my understanding as in my use case it leads to duplicate keys in the database and the db setup failing.

I suspect I could make use of setup / teardown , but that would mean maintaining 2 configurations as mochas tests are already running in CI.

Is there a better way to have both running smoothly ? 

### Typical configuration

The hook file looks like this :
```javascript

const app = require('app.js') ; // is a promise, not the actual express app
const context = { };  // will be filled later on

before((done) => {
  app.then(({ a, b } => { // only one then here, but could be more, ie : auth, so context will be populated by JWT
    context.a = a;
   done();
 });
});

after((done) => {
  // close of handles
  done();
});

module.exports = context;
```
And a test like that :
```
const context = require('hook.js');
describe('test case 1', () => {
  it('test 1', (done) => {
    // context is usable and filled.
  });
});
```
### Code editor or IDE name and version

Visual Studio Code 

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
> it seems wallabyjs executes global hooks for each test.

Wallaby should execute global hooks once per worker process. However, by default Wallaby runs your tests in several worker processes, and it may be causing duplicate keys in the database. If that is the case, then making Wallaby run like plain mocha in one process by [setting `workers` to 1 in your Wallaby config](https://wallabyjs.com/docs/config/workers.html) should do the trick:

```diff
 module.exports = function () {
   return {
     ...

+    workers: { initial: 1, regular: 1}
   };
 };
```

Please try the solution and let us know if it helps.

**Comment by stf8** [comment]
Thanks a lot Artem,  I totally missed the worker aspect.

It work as expected now :)
