### ISSUE TITLE
How to pass information from setup function to tests in Node?

### ISSUE THREAD

**Issue by Ghirigoro** [wallabyjs/public#1995]
### Issue description or question
The documentation states that  if you want to pass any context to your tests from the setup function you should:
>use the `global` object in case of node.js tests (or the require modules you need).

I've tried setting values on the global object but :
```
// In wallaby.js
env: {
    type: "node",
    runner: "node" // or full path to any node executable
},
setup: function(wallaby) {
    global.TEST = 42;
}

// In a test
console.log(global.TEST); // undefined
```

What is the proper way to pass context (e.g. a database instance) to tests from the setup function?

### Code editor or IDE name and version

Visual Studio Code v1.30.2

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It depends on your testing framework. If you are using Mocha/Jasmine, then 

```js
setup: function(wallaby) {
    global.TEST = 42;
}
```

should work. 

If you are using Jest, then it requires to pass globals differently. You may add the [globals to Jest config](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) like this (given that your jest config is in your `package.json` file):

```js
 module.exports = function () {

   return {
     ...

     setup: function (wallaby) {
       var jestConfig = require('./package.json').jest;
       jestConfig.globals = { "TEST": 42 };
       wallaby.testFramework.configure(jestConfig);
     }
   };
 };
```

Having said that, if you are running your Jest CLI tests too, then you should already have your globals in your Jest config (or some [other Jest setup files](https://jestjs.io/docs/en/configuration#setupfiles-array)), in which case no additional Wallaby config is required.
