### ISSUE TITLE
support for Quasar V1 almost working

### ISSUE THREAD

**Issue by paulvanbladel** [wallabyjs/public#1998]
### Issue description or question
Quasar reached V1 status. Quasar is a vueJs based spa framework.
I have a sample of a quasar project containing JEST unit tests which are working fine.
See: https://github.com/paulvanbladel/quasar-jest-unit-testing-sample

I'm quite close to get WallabyJs working, but the thing missing is probably beyond the scope of my knowledge.
Your help would be greatly appreciated. Quasar is getting quite some traction, I would be very glad to promote usage of wallaby in the vueJs/quasar community.
Thanks a lot !
### Wallaby.js configuration file
https://github.com/paulvanbladel/quasar-jest-unit-testing-sample
```error
​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​Configuration error:​​
​​​​
​​Could not locate module ~/test/jest/utils mapped as:​​
​​./test/jest/utils.​​
​​​​
​​Please check your configuration for these entries:​​
​​{​​
​​  "moduleNameMapper": {​​
​​    "/^~\/(.*)$/": "./$1"​​
​​  },​​
​​  "resolver": null​​
​​}​​
  at Object.<anonymous> ​test/jest/__tests__/App.spec.js:7​
```

### Code editor or IDE name and version

Visual Studio Code v1.?
### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Created the [PR with the working config](https://github.com/paulvanbladel/quasar-jest-unit-testing-sample/pull/1). Basically all that was missing is the `./test/jest/utils` in the `files` list.

I have also had to delete some code from `test/jest/utils/index` as it was breaking Wallaby, but doesn't seem to make any difference if deleted. If you need it for CLI, may just put it in `try-catch` block.

**Comment by paulvanbladel** [comment]
@ArtemGovorov Many thanks Artem. Very much appreciated.
