### ISSUE TITLE
Test without test file id, most likely test did not run

### ISSUE THREAD

**Issue by jeffling** [wallabyjs/public#20]
```
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'should export properly',
  id: 100001,
  log: [ { message: 'undefined is not a function', stack: [] } ],
  filesInvolved: [] }
``` 

What does it mean? Where do I look for the undefined function?

**Comment by ArtemGovorov** [comment]
It normally means that some test failed to start. For example:
```javascript
it('test', someFunc(function() {
  // test body
});
```
if `someFunc` for whatever reason fails, the message like this will appear. Have a look into your 'should export properly' test.

**Comment by ArtemGovorov** [comment]
Or more precisely, it means that the test have started to execute, but failed before the execution has actually reached the test file (the test body or any before/beforeEach hooks).

**Comment by jeffling** [comment]
:( has to do with my webpack attempts.
