### ISSUE TITLE
Error is shown when running a very simple demo setup with Jest

### ISSUE THREAD

**Issue by i0natan** [wallabyjs/public#2002]
### Issue description or question
When I run the project's test, different errors are shown randomly (never succeeded), the last one is:
"​Failed to parse node_modules/browser-resolve/node_modules/resolve/test/precedence/bbb.js, SyntaxError: Unexpected token (1:15)​​
[Error] ​​    at process.emit (events.js:182:13)​​
[Error] ​​    at emit (internal/child_process.js:812:12)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:63:19)​​"

One another :
"Failed to parse node_modules/cssom/lib/Parser.js, SyntaxError: Unexpected token (362:11)​​
[Error] ​​    at process.emit (events.js:182:13)​​
[Error] ​​    at emit (internal/child_process.js:812:12)​​
[Error] ​​    at process._tickCallback (internal/process/next_tick.js:63:19)​​"

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [{ pattern: '/**/*.js', ignore: false }, { pattern: 'tests/**/*.test.js', ignore: true }],

    tests: [{ pattern: 'tests/**/*.test.js', ignore: false }],

    debug:true,

    env: {
      type: 'node',
      runner: 'node',
    },
    setup: function (wallaby) {
      var jestConfig = require('./jest.config');
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

OSX

**Comment by smcenlly** [comment]
@i0natan - can you please provide us with a sample repo and steps to reproduce?

**Comment by smcenlly** [comment]
I also noticed that your configuration is including *all* `.js` files from your project root. This means that wallaby is going to find any `.js` artifacts that exist under you project's root directory (e.g. may include your build directory). This pattern will also include all javascript from `node_modules`, which Wallaby will try and instrument. If any node modules include `.js` files that include newer language syntax that Wallaby isn't configured for (e.g. ESNEXT) then Wallaby will return syntax errors when parsing.

Please try making your files pattern more specific, for example:

```javascript
return {
    files: [{ pattern: 'src/**/*.js', ignore: false }, { pattern: 'tests/**/*.test.js', ignore: true }],
..
}
```

If *all* `.js` files under your project root are source files (except for `tests/**/*.test.js`) then you can keep your existing pattern, change your files to:

```javascript
return {
    files: [
        { pattern: '**/*.js', ignore: false }, 
        { pattern: 'node_modules/**', ignore: true }, 
        { pattern: 'tests/**/*.test.js', ignore: true }
    ]
,..
}
```

Also, please note that you can shorten your `files` and `tests` sections using our more compact syntax ((documented here)[https://wallabyjs.com/docs/config/files.html])

```javascript
return {
    files: [
        { '**/*.js' }, 
        { '!node_modules/**' }, 
        { '!tests/**/*.test.js'  }
    ],

    tests: [ 'tests/**/*.test.js' ],
,..
}
```
