### ISSUE TITLE
setting problem, cache is not found

### ISSUE THREAD

**Issue by jiaming0708** [wallabyjs/public#2004]
### Issue description or question

My project is building by `webpack`+`react`+`jest`, and I got the error running `wallaby.js`

```
0 failing tests, 0 passing (only executed app/containers/NotFound/NotFound.test.js)

TypeError: Cannot read property 'cache' of undefined
  at Object.<anonymous> app/containers/NotFound/NotFound.test.js:1
Module parse failed: Unexpected token (95:24)
You may need an appropriate loader to handle this file type.
|                     $_$wf(77);
|                     return $_$w(77, 16), {
|                         ...route,
|                         path: PREPEND_PATTERN,
|                         component: 'LocaleHandler'ModuleParseError: Module parse failed: Unexpected token (95:24)
You may need an appropriate loader to handle this file type.
|                     $_$wf(77);
|                     return $_$w(77, 16), {
|                         ...route,
|                         path: PREPEND_PATTERN,
|                         component: 'LocaleHandler'
    at doBuild (/Users/jimmy/Documents/3_Snapask/Work/Blueberry/node_modules/webpack/lib/NormalModule.js:303:19)

// ... the log is too long, if you need more , I can post full log
```

`NotFound.test.js`, all is white point, the test should not run(?)
![screen shot 2019-02-20 at 10 41 06](https://user-images.githubusercontent.com/8855285/53062581-39f0dc00-34fc-11e9-9905-f7ebc5b61e21.png)

```
import React from 'react';
import toJson from 'enzyme-to-json';
import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import { MemoryRouter } from 'react-router-dom';

import NotFound from './NotFound';

// Enzyme.configure({ adapter: new Adapter() });
describe('Component: NotFound', () => {
  it.only('should match its empty snapshot', () => {
    expect(1).toBe(1);
    // // @issue adding initial entries to react router.
    // // https:// stackoverflow.com/questions/44441852/testing-react-router-v4-with-jest-and-enzyme
    // const component = Enzyme.shallow(
    //   <MemoryRouter initialEntries={[
    //     {
    //       pathname: '/',
    //       key: 'testKey',
    //       state: '',
    //     },
    //   ]}
    //   >
    //     <NotFound t={(key, options) => (key)} />
    //   </MemoryRouter>
    // );

    // expect(toJson(component)).toMatchSnapshot();
  });
});
```

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./webpack.config');

module.exports = function (wallaby) {
  process.env.BABEL_ENV = 'test';
  process.env.NODE_ENV = 'local';

  const wallabyPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {
        pattern: 'app/**/*.js*',
        load: false,
      },
      {
        pattern: 'app/**/*.test.js',
        ignore: true,
      },
    ],
    tests: [
      {
        pattern: 'app/**/*.test.js',
        load: false,
      },
    ],
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      'app/**/*.jsx': wallaby.compilers.babel(),
    },
    postprocessor: wallabyPostprocessor,
    testFramework: 'jest',
    debug: true,
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.13.1

### OS name and version

OSX 10.14.3

**Comment by ArtemGovorov** [comment]
Jest doesn't use webpack config, so this should work for you:

```diff
```js
-const wallabyWebpack = require('wallaby-webpack');
-const webpackConfig = require('./webpack.config');

module.exports = function (wallaby) {
  process.env.BABEL_ENV = 'test';
  process.env.NODE_ENV = 'local';

- const wallabyPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {
        pattern: 'app/**/*.js*',
        load: false,
      },
      {
        pattern: 'app/**/*.test.js',
        ignore: true,
      },
    ],
    tests: [
      {
        pattern: 'app/**/*.test.js',
-       load: false,
      },
    ],
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      'app/**/*.jsx': wallaby.compilers.babel(),
    },
-   postprocessor: wallabyPostprocessor,
    testFramework: 'jest',
    debug: true,
  };
};
```
```

**Comment by jiaming0708** [comment]
but I got this error, when I refine the script
```
0 failing tests, 0 passing (only executed app/containers/NotFound/NotFound.test.js)

./app/containers/NotFound/NotFound.test.js:2
import React from 'react';
^^^^^^

SyntaxError: Unexpected token import
  at app/containers/NotFound/NotFound.test.js:1
```

**Comment by ArtemGovorov** [comment]
Your `.js` files are not being compiled, because your `compilers` pattern only includes `.jsx` files. This should help:

```diff
    compilers: {
-    'app/**/*.jsx': wallaby.compilers.babel(),
+    'app/**/*.js?(x)': wallaby.compilers.babel(),
    },
```

**Comment by jiaming0708** [comment]
nice, it works now
but I have another questions

* there are some files for saga, but not include in the test list
![screen shot 2019-02-20 at 12 44 34](https://user-images.githubusercontent.com/8855285/53067014-4b8eaf80-350d-11e9-8756-238bf42b838f.png)

* **module alias** setting in webpack, how to resolve the alias problem without include `wallaby-webpack`

**Comment by ArtemGovorov** [comment]
> there are some files for saga, but not include in the test list

Ok, what's the question?

> **module alias** setting in webpack, how to resolve the alias problem without include `wallaby-webpack`

You are using Jest, and Jest doesn't use webpack at all. The question is not Wallaby specific though, as you need to configure your Jest CLI the same way. The [`moduleNameMapper ` setting](https://jest-bot.github.io/jest/docs/configuration.html#modulenamemapper-object-string-string) may help.

**Comment by jiaming0708** [comment]
> there are some files for saga, but not include in the test list
>> Ok, what's the question?

folder `sagas` not include in the testing list, but when I change the folder not include component test, the testing will run, how should I set?

```
    tests: [
      'app/sagas/*.test.js',
    ],
```

folder
![folder](https://user-images.githubusercontent.com/8855285/53067014-4b8eaf80-350d-11e9-8756-238bf42b838f.png)

> **module alias** setting in webpack, how to resolve the alias problem without include `wallaby-webpack`
>> You are using Jest, and Jest doesn't use webpack at all. The question is not Wallaby specific though, as you need to configure your Jest CLI the same way. The [`moduleNameMapper ` setting](https://jest-bot.github.io/jest/docs/configuration.html#modulenamemapper-object-string-string) may help.

got it!! I will check it first

**Comment by ArtemGovorov** [comment]
> folder `sagas` not include in the testing list, but when I change the folder not include component test, the testing will run, how should I set?

Sorry, I still don't quite understand what is the issue with the `sagas` folder.

With your current config:

```
    tests: [
      {
        pattern: 'app/**/*.test.js',
      },
    ],
```

all files like `*.test.js` are included and executed as tests, including those in `sagas` folder (if it is in under `app`, ie. `app/sagas`).

if you want to exclude the folder, you may use [the ignore flag](https://wallabyjs.com/docs/config/files.html#file-object) for a certain pattern.

If it doesn't address your question, please describe what you are trying to do in more detail step by step with a concrete file names example.

**Comment by jiaming0708** [comment]
sorry, my bad...

with this config only 1 file test, but total test files have 7 in project (1 in component, 6 in sagas)
```
    tests: [
        'app/**/*.test.js',
    ],
```
> 0 failing tests, 1 passing (only executed app/containers/NotFound/NotFound.test.js)

try to change the config to this, 6 files test
```
    tests: [
      'app/sagas/*.test.js',
    ],
```
> 0 failing tests, 6 passing

all test files are under `app/*` folder, my expect should have 7 files when I use first config
is it any setting wrong in `wallaby` or `jest`?

**Comment by smcenlly** [comment]
If all of your test files are under `app`, then with the pattern, `app/**/*.test.js`, Wallaby should be running all of them, regardless of whether they are: `app/sagas/error.test.js` or `app/containers/notfound/notfound.test.js`.

You could try specifying both paths in your `tests` section (comma separated) but you should not have to do that. 

Could you please send us a cut-down sample repo that has the same problem so we can investigate further for you?

**Comment by jiaming0708** [comment]
If set specifying paths, also only run `appcontainers/notfound/notfound.test.js`.
I will try to reproduce a sample repo, and send it to you.

very thanks for your help!!

**Comment by ArtemGovorov** [comment]
@jiaming0708 Please check one more thing, I have a suspicion that the `app/containers/notfound/notfound.test.js` may contain `it.only` or `//file.only` comment. If it is the case, then it is expected - Wallaby [runs only the spec with `it.only`/`//file.only`](https://wallabyjs.com/docs/intro/selected-tests.html).

**Comment by jiaming0708** [comment]
@ArtemGovorov you are right!! we write `it.only` in the file.

all problems are resolved, thank you all guys!!
