### ISSUE TITLE
inject() must be called from an injection context

### ISSUE THREAD

**Issue by maccurt** [wallabyjs/public#2007]
### Issue description or question

I get an error: inject() must be called from an injection context
my test pass fine using ng test. I had my repo on another laptop and all the test pass. The difference is I upgraded one to Angular 7, the one working on the laptop is Angular 6. I am at my wits ends and will continue to try to find a fix. If need be I will create a brand new project with Angular 7 to see if I can reproduce the problem in a small project. My first though is Angular Material has something to do with this...

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*.spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),        
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/environments/*.ts', ignore: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},      
      {pattern: 'src/main.ts', ignore: true},      
      {pattern: 'src/test.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code 1.31.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
The issue doesn't seem to be related purely to Angular 7, because our sample here https://github.com/wallabyjs/ngCliWebpackSample is using Angular 7 and it is working. Could you please try running Wallaby on the sample project to see if Wallaby is working for you there? If yes, then please create a small sample repo demonstrating the issue, we are happy to take a look.

**Comment by maccurt** [comment]
Yes, I will be able to do this. I created a small project with the minimal amount of code. I did include Angular Material.. I have a service that is injecting MatDialog into the service and if I remove the MatDialog wallaby will work fine, the application also work either way. I will have a repo for you in a minute on GitHub..

**Comment by maccurt** [comment]
Here is my repo: https://github.com/maccurt/WallabyFix.git

Do you need anything else?

**Comment by maccurt** [comment]
My version of the code was working before, and then I had the bright idea of upgrading my machine to the newest angular cli and 7

**Comment by maccurt** [comment]
Angular CLI: 7.3.3
Node: 8.11.2
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cdk                      7.3.3
@angular/cli                      7.3.3
@angular/material                 7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by ArtemGovorov** [comment]
Just cloned your repo and wallaby is working as expected for me:

<img width="485" alt="screen shot 2019-02-24 at 12 01 30 am" src="https://user-images.githubusercontent.com/979966/53287398-55dbd280-37c7-11e9-8d84-98f078de5a18.png">

Is there anything I'm supposed to change/uncomment in the repo to reproduce the issue?

Please also check if you have any of the following folders on disk:
```
C:\Users\USERNAME\.vscode\extensions\node_modules
C:\Users\USERNAME\.vscode\node_modules
C:\Users\USERNAME\node_modules
C:\Users\node_modules
C:\node_modules
```

and if you do, try deleting them and restarting Wallaby.

**Comment by maccurt** [comment]
Interesting.. can I assume you are using the same version of the CLI as I am? must be. Let me pull it down on another machine and see what is going on. Thanks for trying..

**Comment by ArtemGovorov** [comment]
> can I assume you are using the same version of the CLI as I am?

I don't think it matters because I've been trying your https://github.com/maccurt/WallabyFix.git repo that contains all dependencies, package-lock file, and doesn't need any Angular CLI version (because it is already generated).

Have you tried checking the folder I have listed at https://github.com/wallabyjs/public/issues/2007#issuecomment-466653361?

**Comment by maccurt** [comment]
Son of a biscuit! I did delete the folders you suggested, started it back up and everything worked. Thank you. I would have never thought to do that. I must love walllaby to much because I knew my build was good, but it was driving me crazy I had all those test not passing (though they worked with ng test).. I thank you sir and you will continue to get my money..
