### ISSUE TITLE
Some long running code has been detected

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/public#2009]
### Issue description or question

After adding a few tests that use mock modules, I started getting the following error:

```
Some long running code has been detected: test "storage persistent storage uses localStorage" is taking more than 5000ms to execute.
Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,
and restarting wallaby to make sure that it is this test/file causing the issue and not something else.
Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.
Pinging test runner sandbox...
The sandbox is not responsive. Check for possibly recently introduced infinite loops.
Runtime error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

The repository that reproduces this issue can be found [here](https://github.com/foxbunny/wallaby-inifinite-loop). The test referenced in the error message is located in `src/services/storage.test.ts`. The tests pass when run using Jest directly (`npm test`).

Any idea why this is happening?

### Wallaby.js configuration file

```javascript
const path = require('path')

module.exports = wallaby => {
  // Set up the environment
  process.env.BABEL_ENV = process.env.NODE_ENV = 'test'

  // Add react scripts dependencies to NODE_PATH
  process.env.NODE_PATH += (
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts/node_modules')
  )

  // Reinit paths
  require('module').Module._initPaths()

  // Final wallaby config
  return {
    files: [
      'src/**/*.+(ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*.test.ts?(x)'
    ],
    tests: [
      'src/**/*.test.ts?(x)'
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        jsx: 'preserve'
      })
    },
    testFramework: 'jest',
    env: { type: 'node' },
    preprocessors: {
      '**/*.js': file => {
        return require('@babel/core').transform(
          file.content,
          {
            sourceMap: true,
            compact: false,
            filename: file.path,
            presets: ['babel-preset-react-app']
          }
        )
      }
    },

    setup (wallaby) {
      const createConfig = require(
        'react-scripts/scripts/utils/createJestConfig')
      const jestConfig = createConfig(
        p => require.resolve('react-scripts/' + p))
      Object.keys(jestConfig.transform || {}).forEach(k => {
        if (k.endsWith('.(ts|tsx)')) {
          void delete jestConfig.transform[k]
        }
      })
      delete jestConfig.testEnvironment
      wallaby.testFramework.configure(jestConfig)
    }
  }
}
```

### Code editor or IDE name and version

IntelliJ IDEA v2018.3.4

### OS name and version

Windows 10

**Comment by foxbunny** [comment]
FYI: Updated to IntelliJ v2018.3.5, and the issue persists.

**Comment by smcenlly** [comment]
The configuration is mostly correct. I can see that there's a problem with your presets (they aren't what they should be). Having said that, we need to do a bit more investigation to identify why they're failing with such a severe error.

Your can fix your config, by changing your `preprocessors` `presets` to: `presets: [require('babel-preset-jest'), 'react-app']`.

Having said that, it looks like your app was created using `create-react-app --typescript`. Our recommendation is to replace your existing configuration with the configuration in our `create-react-app --typescript` sample: https://github.com/wallabyjs/wallaby-create-react-app-ts/blob/master/wallaby.js

**Comment by foxbunny** [comment]
@smcenlly Thanks for that. Adding `require('babel-preset-jest')` definitely fixes the issue as does using the config from the sample.

**Comment by smcenlly** [comment]
Without `require('babel-preset-jest')`, your mocks were not being hoisted to the top of your files. This resulted in your `storage.test.ts` files running your production code instead of your mocks. If you comment out the `jest.mock` in the storage.test.ts, you get the same out of memory error when testing using the cli (i.e. `npm test`).
