### ISSUE TITLE
Webstorm plugin: License does not persist

### ISSUE THREAD

**Issue by prabinv** [wallabyjs/public#201]
I use the wallabyjs plugin with Webstorm 9 (9.0.3), and every time I restart Webstorm, WallabyJS asks for  the license key to be entered. This is a bit annoying. Is this intentional, or is there some step I missed while activating wallabyjs plugin?

**Comment by ArtemGovorov** [comment]
What OS are you using?

Wallaby stores the license key in WebStorm cache folder. Perhaps there's something that clears the cache?

Try following:

Open your WebStorm, activate wallaby.js with your license key, then add [`debug: true`](http://wallabyjs.com/docs/config/overview.html#debug-setting) to your wallaby config, start wallaby configuration and open the Wallaby Console tab. One of the very first lines it outputs should be something like `File cache: .../wallaby/projects/...`. Open the folder, and go 2 levels up to the `wallaby` folder. You should be able to see `key.lic` file, it's your license key that wallaby plugin reads when it starts. Now try closing your WebStorm and see if the file is still there.

Please also attach your `idea.log` file, the part of it after the initial WebStorm start, wallaby activation and WebStorm restart. The log can be found by using menu `Help - Show Log ...`.

**Comment by prabinv** [comment]
Thanks for the reply.
I'm using OSX. 
I guess the fact that it stores in the Webstorm cache would explain why it gets reset. I have a disk clean utility which runs occassionally, and deletes the Webstorm cache. Is there a way to change this? Otherwise, I will remove the Webstorm cache from the clean tool.

**Comment by ArtemGovorov** [comment]
Please configure the disk clean utility to keep at least the `key.lic` file, however I'd recommend to avoid cleaning the whole WebStorm cache, as the IDE itself and all of its plugins store some data there and cleaning the folder may affect the performance of the IDE and its plugins. For example, wallaby.js in particular caches some data that allows it to start and run tests faster after the very first start.
