### ISSUE TITLE
VSCode decorations (gutter indicators) seem completely off

### ISSUE THREAD

**Issue by simerlec** [wallabyjs/public#2013]
### Issue description or question
Hello!

The decorations inside VSCode seem completely off, which makes gathering testing feedback inside the testing file basically impossible. The below screenshot should illustrate what I'm talking about. The decorations (green markings in the gutter) are not where they should be.

![screenshot 2019-03-01 09 16 02](https://user-images.githubusercontent.com/5793380/53625449-6fd04780-3c03-11e9-87ee-a947409908bb.png)

They are offset somehow which can be seen later in the file (they almost seem to just stop due to the offset)

![screenshot 2019-03-01 09 26 31](https://user-images.githubusercontent.com/5793380/53625705-1d435b00-3c04-11e9-8e81-9ac8ee7da9d8.png)

Has this been experienced before?

Thanks for your time!

### Wallaby.js configuration file

```
var compilerOptions = require('./src/tsconfig.spec.json').compilerOptions;

module.exports = function(wallaby) {
  const jestTransform = file =>
    require('jest-preset-angular/preprocessor').process(
      file.content,
      file.path,
      { globals: { __TRANSFORM_HTML__: true }, rootDir: __dirname },
    );

  return {
    files: [
      'tsconfig.json',
      'package.json',
      './src/tsconfig.spec.json',
      'src/**/*.ts',
      '!src/**/*.d.ts',
      'src/**/*.css',
      'src/**/*.less',
      'src/**/*.scss',
      'src/**/*.sass',
      'src/**/*.html',
      '*.snap',
      '!src/**/*spec.ts',
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'babel.config.js', instrument: false },
    ],
    tests: ['src/**/*spec.ts'],
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions),
    },
    testFramework: 'jest',
    slowTestThreshold: 100,
    preprocessors: {
      'src/**/*.ts': [
        jestTransform,
        file =>
          require('@babel/core').transform(file.content, {
            sourceMap: true,
            filename: file.path,
            presets: ['babel-preset-jest'],
          }),
      ],
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code Version 1.31.1 (1.31.1)

### OS name and version
OSX: macOS Mojave 10.14.3 (18D109)

**Comment by ArtemGovorov** [comment]
Please share your Jest config. Looks like some of your Jest transforms is applied after Wallaby, and it is breaking source map.

**Comment by ArtemGovorov** [comment]
Also your config is slightly incorrect:

```diff
...
preprocessors: {
-     'src/**/*.ts': [
+     'src/**/*.js': [
        jestTransform,
        file =>
          require('@babel/core').transform(file.content, {
            sourceMap: true,
            filename: file.path,
            presets: ['babel-preset-jest'],
          }),
      ],
    },
```

Or better try using the config from our docs at https://wallabyjs.com/docs/integration/angular.html#jest.

**Comment by simerlec** [comment]
ah yes, the preprocessors change from `ts` to `js` already did the trick. I must admit a spent way too little time to understand everything that happens with wallaby and jest 😓here's the jest config just for sake of completeness

```
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['./src/setup.jest.ts'],

  globals: {
    __TRANSFORM_HTML__: true,
  },
  transform: {
    '^.+\\.(ts|html)$': './node_modules/jest-preset-angular/preprocessor.js',
    '^.+\\.js$': 'babel-jest',
    '.+\\.(css|styl|less|sass|scss)$': 'jest-transform-css',
  },
  transformIgnorePatterns: ['node_modules/(?!@ngrx|ngx-bootstrap)'],
  moduleNameMapper: {
    'monaco-editor': '<rootDir>/__mocks__/monaco-editor.js',
  },
};
```

thank you very much, @ArtemGovorov 👍

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
