### ISSUE TITLE
Feature Request: choose a wallaby.js that is not in the project root

### ISSUE THREAD

**Issue by cellog** [wallabyjs/public#2016]
### Issue description or question
I would like to use wallaby.js for debugging, but the project I'm using it on will not add it to the repo. I don't want to add it to .gitignore because I am constantly switching branches and it tends to disappear. 

Is there any way to select a wallaby.js file that is outside the project root in VS Code? This way I could keep it in my ~ and nobody need be the wiser.

### Code editor or IDE name and version

Visual Studio Code v1.31.1

### OS name and version

OSX

**Comment by foxbunny** [comment]
It sounds like you'd be better served by [Quokka](https://quokkajs.com/) if you're not actually running tests.

**Comment by cellog** [comment]
I am running tests

**Comment by foxbunny** [comment]
In that case, your request makes more sense. Meanwhile, try adding `wallaby.js` to `.git/info/exclude`. That works like a local `.gitignore` that is not part of the repo.

**Comment by smcenlly** [comment]
Thanks for the feature request. I'm going to close this, as it is a duplicate, referenced in two other open issues: #1422 and #68.
