### ISSUE TITLE
Can't make jest work with a monorepo.

### ISSUE THREAD

**Issue by stijnvanderlaan** [wallabyjs/public#2018]
### Issue description or question
I keep getting the error: "Runtime error: Jest encountered an unexpected token" on files imported using lerna / yarn workspaces.

### Wallaby.js configuration file

```javascript

module.exports = function (wallaby) {

  return {
    files: [
      'apps/**/*.js',
      '!apps/**/node_modules/**',
      'jest.config.js',
      '!apps/*/src/**/__tests__/*.js',
    ],

    tests: [
      'apps/*/src/**/__tests__/*.js',
      // 'packages/**/__tests__/*.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      // 'packages/**/*.js': wallaby.compilers.babel(),
    },

    setup: function (w) {
      var jestConfig = require('./jest.config.js');
      // for example:
      // jestConfig.globals = { "__DEV__": true };
      wallaby.testFramework.configure({
        moduleNameMapper: {
          "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|swf)$": "identity-obj-proxy",
          "\\.(css|less)$": "identity-obj-proxy"
        },
      });
    },

    // debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v 1.31.1

### OS name and version
OSX 10.14.3

**Comment by ArtemGovorov** [comment]
Please provide a sample repo demonstrating the issue, we are happy to take a look and help with the config. A lot of our users successfully using Wallaby for testing monorepos via yarn workspaces/lerna, so I'm confident we can help you once we have more details.

**Comment by smcenlly** [comment]
Closing this issue as we require more information. If you provide a sample, we will re-open this issue.
