### ISSUE TITLE
Require files out of project

### ISSUE THREAD

**Issue by nikolaymatrosov** [wallabyjs/public#202]
In one project I have server and client code in sibling folders. Server code has json schema files. In my client code I want to use that schema to generate fake data for tests. In plain Mocha tests it works perfectly. But Wallaby fails to find that flie. I don't want to copy json schema, to be sure that I use for test the same schema as the server does.

Folders:
```
|-client
| |-src
|   |-data
|     |-Api.spec.js
|-server
  |-SOME_PROJECT
    |-JsonSchemas
      |-Api.json
```

Example from `Api.spec.js`:
```js
var schema = require('../../../server/SOME_PROJECT/JsonSchemas/Api.json'));
```
Is there any workaround?

**Comment by fvanwijk** [comment]
Possible duplicate of https://github.com/wallabyjs/public/issues/68

**Comment by ArtemGovorov** [comment]
Did you include the JSON file in your `files` list? If so, and it still doesn't work, could you please share your wallaby config?

**Comment by ArtemGovorov** [comment]
@nikolaymatrosov Is this still a valid issue or I may close it?

**Comment by ArtemGovorov** [comment]
I'll close it for now, please let me know if it's still an issue.
