### ISSUE TITLE
File has invalid syntax

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2021]
### Issue description or question

What causes the `File has invalid syntax:` error?

The file is being instrumented fine as seen below.

Is this a runtime or compile time error?

```
Mon, 11 Mar 2019 01:05:41 GMT wallaby:processor Finished running one processor for packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js
Mon, 11 Mar 2019 01:05:41 GMT wallaby:project Processing compiled packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js
Mon, 11 Mar 2019 01:05:41 GMT wallaby:project Instrumenting packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js, via process pool: false
Mon, 11 Mar 2019 01:05:41 GMT wallaby:project No preprocessors configured for packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js
Mon, 11 Mar 2019 01:05:41 GMT wallaby:project Writing to disk and caching processed file packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js
Mon, 11 Mar 2019 01:05:41 GMT wallaby:project File packages/public-symlink/framework/cli/src/modules/runners/util/get-shell-env-vars.js changes saved, store ts: 1552266316796, change ts: 1552266341425
Mon, 11 Mar 2019 01:05:42 GMT wallaby:project Test run started; run priority: 2
Mon, 11 Mar 2019 01:05:42 GMT wallaby:testTask Test files from affected: 7, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Mon, 11 Mar 2019 01:05:42 GMT wallaby:project Test run finished
Mon, 11 Mar 2019 01:05:42 GMT wallaby:project File has invalid syntax: packages/public-symlink/framework/cli/lib/modules/runners/util/get-shell-env-vars.js
Mon, 11 Mar 2019 01:05:42 GMT wallaby:project Test run data re-queued
```

**Comment by ArtemGovorov** [comment]
This is a compile time error. There should be some more information (starting with `Failed to parse ...`)  about the file in the output. If you can't find the information in the output, please create a sample repo demonstrating the issue, we are happy to take a look and investigate.

**Comment by vjpr** [comment]
I think there is a need to expose more debugging information to the user as I mention here: https://github.com/wallabyjs/public/issues/2020#issuecomment-472017035

Without a stack trace this is impossible to debug. There is literally nothing the user can do to try and solve it.

---

For this particular error, I have a babel plugin that is throwing an error, but this doesn't show up in `Failing tests` logs. Making it even harder to debug.

**Comment by smcenlly** [comment]
> For this particular error, I have a babel plugin that is throwing an error, but this doesn't show up in Failing tests logs. Making it even harder to debug.

Could you please provide us with a sample of your code/config so we can see the babel plugin error?
