### ISSUE TITLE
CRA --typescript and Lerna

### ISSUE THREAD

**Issue by bhishp** [wallabyjs/public#2024]
### Issue description or question

I am having an issue setting up Wallaby with CRA typescript in a lerna repo. Currently the project has two sub-packaged: vessel and shared.

I have followed the example here: https://github.com/wallabyjs/wallaby-create-react-app-ts/blob/master/wallaby.js for CRA ts.

And integrated changes from here for lerna: https://github.com/ArtemGovorov/lerna-wallaby-react-typescript/blob/patch-1/wallaby.js.

The error given is as follows:

```
Postprocessor run failure: Failed to instrument packages/shared/src/components/ErrorList/ErrorList.js
   9 |     return (<div>
  10 |       {errors.map(function (error) {
> 11 |         return error.message && (<error_1["default"] key={error.message} message={error.message}/>);
     |                                          ^ SyntaxError: Unexpected token (11:41)
  12 |     })}
  13 |     </div>);
  14 | };
```

I have noticed that if I change the files glob to scope to src then the error is slightly different. `'packages/**/*` to `'packages/**/src/*`.

Error scoped to src:

```
Postprocessor run failure: Failed to instrument packages/vessel/src/app.js
  100 |         var _a = this.state, loading = _a.loading, error = _a.error, showInstallButton = _a.showInstallButton;
  101 |         if (loading) {
> 102 |             return <splash_1["default"] />;
      |                             ^ SyntaxError: Unexpected token (102:28)
  103 |         }
  104 |         if (error) {
  105 |             return <base_layout_1["default"]>Error!</base_layout_1["default"]>;
```

Looks like maybe it just processes files in a different order, not sure...

Thanks for your help.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  var path = require('path');
  const vesselPath = path.join(wallaby.localProjectDir, 'packages', 'vessel');
  const nodeModulesPath = path.join(vesselPath, 'node_modules');
  const reactScriptsPath = path.join(nodeModulesPath, 'react-scripts');
  const reactScriptsNodeModulesPath = path.join(reactScriptsPath, 'node_modules');

  // const setupTestsPath = path.join(vesselPath, 'src', 'setupTests');
  // const jestConfigPath = path.join(reactScriptsPath, 'scripts', 'utils', 'createJestConfig');

  process.env.BABEL_ENV = 'test';
  process.env.NODE_ENV = 'test';
  // process.env.NODE_PATH += path.delimiter + path.join(__dirname, 'node_modules') + path.delimiter + path.join(__dirname, 'node_modules/react-scripts/node_modules');
  process.env.NODE_PATH += path.delimiter + nodeModulesPath + path.delimiter + reactScriptsNodeModulesPath;
  require('module').Module._initPaths();

  return {
    files: [
      // { pattern: 'src/setupTests.ts', instrument: false },
      'packages/**/*.+(ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!packages/**/node_modules/**',
      '!packages/**/*.test.ts*'
    ],
    tests: [
      'packages/**/*.test.ts*',
      '!packages/**/node_modules/**'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    debug: true,

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require('babel-preset-jest'), 'react-app']
        })
    },

    testFramework: {
      type: 'jest',
      path: path.join(nodeModulesPath, 'jest', 'node_modules', 'jest-cli')
    },

    // postprocessor: null,

    setup: wallaby => {
      const path = require('path');
      const vesselPath = path.join(wallaby.localProjectDir, 'packages', 'vessel');
      // const setupTestsPath = path.join(vesselPath, 'src', 'setupTests');
      const nodeModulesPath = path.join(vesselPath, 'node_modules');
      const reactScriptsPath = path.join(nodeModulesPath, 'react-scripts');
      const jestConfigPath = path.join(reactScriptsPath, 'scripts', 'utils', 'createJestConfig');

      // 'react-scripts/scripts/utils/createJestConfig'

      const jestConfig = require(jestConfigPath)(p => require.resolve(path.join(reactScriptsPath, p)));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

  };
};
```

### Code editor or IDE name and version

WebStorm 2018.3.5
Build #WS-183.5912.23, built on February 26, 2019
macOS 10.14.3

### OS name and version

OSX

**Comment by smcenlly** [comment]
Thanks for the all the detail you provided. Unfortunately, we're going to need a bit more information to be able to identify exactly what's wrong. 

**Could you please send us a sample repo of what you've set up?** The root `package.json` and `tsconfig.json` may also have configuration that is relevant to identifying what's not working.

---

If you'd like to try and get it working without sending us a sample repo:

What might also help you is turning on the wallaby `debug` [configuration option](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information). This will output more detail to the Wallaby console which may point you in the right direction.

As a first step, you should get wallaby working with CRA for your `vessel` sub-project by itself. We did the same (you can see our wallaby.js configuration below). Please note that we needed to include TypeScript in our root package, as well as a valid `tsconfig.json` file.

If you can't get it working, as per my comment above, please send a sample repo, we'd be happy to take a look.

```javascript
module.exports = function(wallaby) {
  var path = require('path');
  process.env.BABEL_ENV = 'test';
  process.env.NODE_ENV = 'test';
  process.env.NODE_PATH += path.delimiter + 
      path.join(__dirname, 'packages', 'vessel', 'node_modules') + 
      path.delimiter + 
      path.join(__dirname, 'packages', 'vessel', 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
    files: 
    [
      { pattern: 'packages/vessel/src/setupTests.ts', instrument: false }, 
      'packages/vessel/src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', 
      '!packages/vessel/src/**/*.test.ts?(x)'
    ],

    tests: [
      'packages/vessel/src/**/*.test.ts?(x)'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require('babel-preset-jest'), 'react-app']
        })
    },

    setup: wallaby => {
      const jestConfig = require('react-scripts/scripts/utils/createJestConfig')(p => require.resolve('react-scripts/' + p));
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

**Comment by ArtemGovorov** [comment]
Looks like the issue is TypeScript compilation related. For some reason, Wallaby TypeScript compiler emits incorrect code (my guess is because it can't find your `tsconfig.json`). 

Please try @smcenlly suggestions above, and also try modifying your Wallaby config as follows:

```diff
module.exports = function(wallaby) {
  ...

  return {
    ...

+   compilers: {
+     '**/*.ts?(x)': wallaby.compilers.typeScript({
+       module: 'esnext',
+       jsx: 'React'
+     })
+   },
  };
};
```

**Comment by bhishp** [comment]
Thanks for speedy reply both.

I added the compiler section as you suggested @ArtemGovorov and then started getting an error about postprocessor

```
Postprocessor run failure: Failed to run preprocessors on packages/shared/src/index.js, Error: Cannot find module 'babel-preset-react-app' from '/Users/bhish/code/shell/sailmetrix/sailmetrix-fe'
```

I then changed the babel loader setting to be fullpath for the sub-package:

```
preprocessors: {
      '**/*.js?(x)': file =>
        require(path.join(nodeModulesPath, '@babel/core')).transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [
            require(path.join(nodeModulesPath, 'babel-preset-jest')),
            require(path.join(nodeModulesPath, 'babel-preset-react-app')),
            // 'react-app'
          ]
        })
    },
```

This gave me a new error about install_common_globals path:

```
Sat, 16 Mar 2019 10:06:23 GMT wallaby:workers Sandbox (active) [obzm0] error: Failed to initialize wallaby jest.
Error: Can not find install_common_globals path
Sat, 16 Mar 2019 10:06:23 GMT wallaby:workers Failed to map the stack to user code, entry message: Failed to initialize wallaby jest.
Error: Can not find install_common_globals path, stack: Failed to initialize wallaby jest.
Error: Can not find install_common_globals path
    at Object.<anonymous> (/Users/bhish/Library/Caches/WebStorm2018.3/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:14:11970)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at Module.i.require (/Users/bhish/Library/Caches/WebStorm2018.3/wallaby/wallaby/server.js:21:20945)
    at require (internal/modules/cjs/helpers.js:22:18)
    at i (/Users/bhish/Library/Caches/WebStorm2018.3/wallaby/wallaby/server.js:14:114)
    at /Users/bhish/Library/Caches/WebStorm2018.3/wallaby/wallaby/server.js:14:305
    at /Users/bhish/Library/Caches/WebStorm2018.3/wallaby/wallaby/server.js:16:27545
```

Does this error look familiar?

My tsconfig is as follows:

```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "allowJs": true
  },
  "include": ["src"]
}
```

I'm afraid I can't share the entire project because it is closed source. I will try setup wallaby in a sub-package as  suggested by @smcenlly now.

**Comment by ArtemGovorov** [comment]
It looks like Wallaby can't find your Jest components now. Unfortunately it's hard to tell why without a sample project.

> I'm afraid I can't share the entire project because it is closed source.

We don't need the entire project. You may copy/paste you entire project to a new folder, remove all real source file and tests, just leave a dummy test file importing and testing a dummy `<div>`-like react component, and various configs where they are. Make sure Jest CLI is working ok on the sample project, and Wallaby is showing the above mentioned issues. Once ready, please upload the repo and share the link - we'll jump in and help you with the config.

**Comment by bhishp** [comment]
I have created the repo here: https://github.com/bhishp/bhishp-wallaby

`npx jest` from the room of the vessel package does **not** work (i assume because it is a CRA projecT). But the CRA test script **does**.

In the real project there is only just a single test file too (app.test.tx in the root of source) as we are only just starting out with writing unit tests. We would build tests alongside components such as

```
/Button
  Button.tsx
  Button.test.tsx
```

We would want the tests to be runnable in shared as well as the vessel package.

Thanks

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo, we can clearly see the issue now.

The problem is that you are trying to run Jest tests in both projects while using Jest installed in one of them (and its config, and its tsconfig, etc). 

There are 2 ways to make it work. 

- If you are OK to run tests for projects separately, then the best choice is to create 2 separate Wallaby configs. One for the `vessel` project would live in the `packages/vessel` folder and be [our docs config](https://github.com/wallabyjs/wallaby-create-react-app-ts/blob/master/wallaby.js) and I think without any changes to it. For the `shared` project - it depends on how are you planning to test it. It doesn't seem to be CRA bootstrapped, doesn't have any testing dependencies installed, so its Wallaby config depends on how you end up setting Jest (without Wallaby) for the project.

- If you want Wallaby (and potentially Jest without Wallaby) to run tests in both projects, then you will need to install Jest at the project's root. Because you are using CRA for the `vessel` project, and CRA ship with embedded Jest version, then installing `react-scripts` in the project's root may be a better choice. In this case Wallaby config to run both projects is a simple config for one CRA project, with `packages/**` in the `files` and required path for compilers to point to tsconfig and babel dependencies.  I have created [the pull request](https://github.com/bhishp/bhishp-wallaby/pull/1) to make your sample repo work.
  - as an alternative to installing anything in the project's root, you may [configure lerna to hoist dependencies](https://github.com/lerna/lerna/blob/master/doc/hoist.md), in which case `react-scripts` (or plain Jest modules) will end being in the project's root node modules without an explicit dependency. In this case, Babel dependencies resolution in the Wallaby config can also be reverted to the original config (because they'll be located in the project's root node modules too).

**Comment by bhishp** [comment]
@ArtemGovorov this makes perfect sense now, thanks for your help. For some reason I thought I had to run wallaby at top-level with lerna but obviously it could just be configured per package... I'm going with option 1 as I'm not sure all the packages we'll have yet, but they are not all likely to be CRA ones.

Thanks again.

**Comment by bhishp** [comment]
I have setup wallaby in two sub-packages but can only seem to run one instance of wallaby at a time. I have a package called `vessel` and a package called `shared`. Whichever wallaby config gets ran first works, whilst the other one reports 0 tests.

This is not an urgent problem but is it expected behaviour that two configs can be run simultaneously?

E.g. Running shared first then vessel. Vessel doesn't work, shared does.

`shared wallaby and test`
![image](https://user-images.githubusercontent.com/12024258/54624310-0bb3dd00-4a65-11e9-9a3c-e33806db1d2a.png)

`vessel wallaby and test`
![image](https://user-images.githubusercontent.com/12024258/54624246-e921c400-4a64-11e9-91b0-c980aa3043e2.png)

**Comment by smcenlly** [comment]
Unfortunately Wallaby doesn't support 2 configurations running at the same time. If you have compatible dependencies, you can set up a single wallaby configuration file that runs all of the tests in all sub-projects. If not, you will only be able to have the tests running in 1 project at a time.
