### ISSUE TITLE
Cannot set property 'adapter' of undefined

### ISSUE THREAD

**Issue by schoenbergeringo** [wallabyjs/public#2025]
I have @google-cloud/monitoring in my project. Files which try to access this shows this Error in wallaby console : [Error] Runtime error: TypeError: Cannot set property 'adapter' of undefined at Object.<anonymous> (/Users/MY_ACCOUNT/Desktop/MY_PROJECT/node_modules/google-auto-auth/node_modules/google-auth-library/src/transporters.ts:49:23) 

### Wallaby.js configuration file

```javascript

module.exports = function (wallaby) {
  const testPathExpTSX = 'src/**/*.test.tsx'
  const testPathExpTS = 'src/**/*.test.ts'
  const testPathExp = 'src/**/*.test.js'
  const babelConfig = JSON.parse(require('fs').readFileSync('./.babelrc'))

  return {

    files: [
      'src/**/*.ts',
      'src/**/*.tsx',
      'src/**/*.js',
      'src/setupTests.js',
      'package.json',
      'scripts/**/*.ts',
      'public/**/*.json',
      'src/**/*.json',
      'babel.config.js',
      `!${testPathExpTS}`,
      `!${testPathExpTSX}`,
      `!${testPathExp}`,
    ],

    tests: [
      testPathExpTS, 
      testPathExpTSX, 
      testPathExp,
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      'src/**/*.js': wallaby.compilers.babel(babelConfig),
      'src/**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        jsx: 'React',
      }),
    },

    setup: (wallaby) => {
      var jestConfig = require('./package.json').jest
      jestConfig.setupFiles = ['<rootDir>/src/setupTests.js']
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest',
  }
}


```

### Code editor or IDE name and version
Visual Studio Code v1.32.3

### OS name and version
OSX
Linux

**Comment by ArtemGovorov** [comment]
Unfortunately we can't reproduce the issue. We have created [this sample repo](https://github.com/ArtemGovorov/wallaby-2025) with your config. It contains a single test with the [content from `@google-cloud/monitoring` docs](https://www.npmjs.com/package/@google-cloud/monitoring#using-the-client-library), and everything seems to be working.

Could you please clone the sample repo and see if it is working for you? If so, please add the details we are missing to reproduce the issue and push your changes - we are happy to take a look and help. My first guess is that you are using some specific version of the library (not the latest), and maybe somehow differently from the sample.

**Comment by schoenbergeringo** [comment]
Thanks for your support. The sample repo works fine for me. After updating my dependency of google-cloud, I receive a different error now...but something completely different. Thanks !!
