### ISSUE TITLE
Wallaby erroring on <rootDir> and mock files

### ISSUE THREAD

**Issue by zarrellab** [wallabyjs/public#2026]
### Issue description or question
I'm having 2 issues with wallaby erroring on running tests, while jest runs fine.

1. Mock files will not run through babel. They produce this error when used:
```
Jest encountered an unexpected token 
 
This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript. 
 
By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules". 
 
Here's what you can do: 
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config. 
 • If you need a custom transformation specify a "transform" option in your config. 
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option. 
 
You'll find more details and examples of these config options in the docs: 
https://jestjs.io/docs/en/configuration.html 
 
Details: 
 
SyntaxError: /Volumes/XT/brandonz/Coding/boilerplate/wallaby-issue/__mocks__/@fortawesome/react-fontawesome.jsx: Unexpected token (3:37) 
 
  1 | import React from 'react' 
  2 |  
> 3 | export const FontAwesomeIcon = () => <i id='MockFontAwesomeIcon' />
    |                                      ^ 
  4 | // SyntaxError: /Volumes/XT/brandonz/Coding/boilerplate/wallaby-issue/__mocks__/@fortawesome/react-fontawesome.jsx: Unexpected token (3:37) 
  5 | // export const FontAwesomeIcon = () => <i id='MockFontAwesomeIcon' /> 
  6 |  
  at Object.require ​src/components/icon.jsx:3​
me._execModule (/Volumes/XT/brandonz/Coding/boilerplate/wallaby-issue/node_modules/jest-runtime/build/index.js:763:13) 
  at Object.require ​src/components/icon.test.jsx:4​
```

2. `<rootDir>` does not get picked up correctly in `jest.config.js`
Adding `'<rootDir>/wallaby-issue/jest.setup.js'` to `setupFilesAfterEnv` produces this error:
```
- Validation Error: 
 
  Module ./wallaby-issue/jest.setup.js in the setupFilesAfterEnv option was not found. 
         <rootDir> is: /Volumes/XT/brandonz/Coding/boilerplate/wallaby-issue 
```
However, adding `'/Volumes/XT/brandonz/Coding/boilerplate/wallaby-issue/jest.setup.js'` does work.

*I made a sample repo* [here](https://github.com/zarrellab/wallaby-issue)
Just search for `FIXME` to get to the issues.

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
  files: [
    '__mocks__/**/*.js?(x)',
    'src/**/*.js?(x)',
    '!src/**/*.test.js?(x)',
  ],
  tests: ['src/**/*.test.js?(x)'],
  filesWithNoCoverageCalculated: [
    '__mocks__/**/*.js?(x)',
    'src/index.jsx',
  ],
  env: {
    type: 'node',
    runner: 'node',
  },
  compilers: {
    '**/*.js?(x)': wallaby.compilers.babel(),
  },
  testFramework: 'jest',
  debug: true,
})
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.
We have created this [pull request to make the config work](https://github.com/zarrellab/wallaby-issue/pull/1).

> <rootDir> does not get picked up correctly in jest.config.js

It is because you've been setting it to `<rootDir>/wallaby-issue/jest.setup.js`, but it's supposed to be `<rootDir>/jest.setup.js`.

> Mock files will not run through babel.

After analysing this one it turned out that recent Jest updates had some breaking changes that we needed to address. We have released the fix in [the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), so after the update it should work for you.

**Comment by zarrellab** [comment]
Thanks so much for this!

> It is because you've been setting it to `<rootDir>/wallaby-issue/jest.setup.js`, but it's supposed to be `<rootDir>/jest.setup.js`.

Whoops! This was a mistake I made creating the demo repo. The error was the same as when I originally found it. The actual fix was providing the `jest.setup.js` file to the wallaby config. So thanks for adding that in the PR.

Also, the core update is working great.
