### ISSUE TITLE
Test suite failed to run [Info]      EACCES: permission denied, write

### ISSUE THREAD

**Issue by nklayman** [wallabyjs/public#2027]
### Issue description or question

When running wallaby on any project (logs from `wallaby-jest-sample`), the tests fail with `Test suite failed to run
[Info]      EACCES: permission denied, write`. Extension is installed to `~/.vscode/extensions/...`, have full permissions to folder.
[full log](https://github.com/wallabyjs/public/files/2980886/log.txt)

### Wallaby.js configuration file

```javascript
module.exports = function () {

  return {
    files: ['sum.js'],

    tests: ['__tests__/*.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',
    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

Ubuntu Linux 18.10

**Comment by NikGovorov** [comment]
Hi @nklayman,

Did you change default [AppArmor ](https://wiki.ubuntu.com/AppArmor) settings on your machine?

Could you please execute `ls -al /etc/apparmor.d/` and paste the content here?

**Comment by nklayman** [comment]
```
total 120
drwxr-xr-x   8 root root  4096 Mar 17 21:13 .
drwxr-xr-x 133 root root 12288 Mar 17 21:13 ..
drwxr-xr-x   4 root root  4096 Nov 13 21:33 abstractions
drwxr-xr-x   2 root root  4096 Mar 17 21:13 cache
drwxr-xr-x   2 root root  4096 Oct 17 15:25 disable
drwxr-xr-x   2 root root  4096 Jul  3  2018 force-complain
drwxr-xr-x   2 root root  4096 Oct 18 11:30 local
-rw-r--r--   1 root root  3215 Jul 30  2018 sbin.dhclient
drwxr-xr-x   5 root root  4096 Oct 17 15:28 tunables
-rw-r--r--   1 root root 10127 Oct 31 12:26 usr.bin.evince
-rw-r--r--   1 root root  8477 Oct 23 13:29 usr.bin.firefox
-rw-r--r--   1 root root  2885 Jul 30  2018 usr.bin.man
-rw-r--r--   1 root root 23187 Feb 27 10:53 usr.lib.snapd.snap-confine.real
-rw-r--r--   1 root root   540 Oct  5 06:34 usr.sbin.cups-browsed
-rw-r--r--   1 root root  5552 Aug 19  2018 usr.sbin.cupsd
-rw-r--r--   1 root root   643 Jul 19  2018 usr.sbin.ippusbxd
-rw-r--r--   1 root root  1550 Apr 24  2018 usr.sbin.rsyslogd
-rw-r--r--   1 root root  1353 Mar 31  2018 usr.sbin.tcpdump
```

**Comment by smcenlly** [comment]
@nklayman - a couple of questions:

1) Did you change the default AppArmor settings on your machine?
2) Is this a fresh standard ubuntu install?

**Comment by nklayman** [comment]
1. Not that I know of, is it possible an app I installed changed it?
2. No. This error doesn't show up on my desktop (which runs Ubuntu 18.10 as well), only my laptop. Chances are I changed something accidentally that is screwing it up. Here is the `apparmor.d` on my desktop:
```
total 128
drwxr-xr-x   8 root root  4096 Mar 17 11:58 .
drwxr-xr-x 142 root root 12288 Mar 18 20:20 ..
drwxr-xr-x   4 root root  4096 Nov 13 12:45 abstractions
drwxr-xr-x   2 root root  4096 Mar 17 11:58 cache
drwxr-xr-x   2 root root  4096 Jul 24  2018 disable
-rw-r--r--   1 root root  1167 Oct 30 21:08 docker
drwxr-xr-x   2 root root  4096 Apr 24  2018 force-complain
-rw-r--r--   1 root root   802 Mar 21  2018 lightdm-guest-session
drwxr-xr-x   2 root root  4096 Oct 18 13:39 local
-rw-r--r--   1 root root  3215 Jul 30  2018 sbin.dhclient
drwxr-xr-x   5 root root  4096 Oct 18 13:39 tunables
-rw-r--r--   1 root root 10127 Oct 31 12:26 usr.bin.evince
-rw-r--r--   1 root root  8477 Oct 23 13:29 usr.bin.firefox
-rw-r--r--   1 root root  2885 Jul 30  2018 usr.bin.man
-rw-r--r--   1 root root 23187 Feb 27 10:53 usr.lib.snapd.snap-confine.real
-rw-r--r--   1 root root   540 Feb 25  2018 usr.sbin.cups-browsed
-rw-r--r--   1 root root  5552 Jun 22  2018 usr.sbin.cupsd
-rw-r--r--   1 root root   643 Jan 16  2018 usr.sbin.ippusbxd
-rw-r--r--   1 root root  1550 Apr 24  2018 usr.sbin.rsyslogd
-rw-r--r--   1 root root  1353 Mar 31  2018 usr.sbin.tcpdump
```

**Comment by smcenlly** [comment]
Unfortunately we can't reproduce the issue. 

As we have not seen this before and can't reproduce the issue, we strongly suspect that your issue is environmental and is not related to Wallaby.js.

Wallaby is getting the `EACCES: permission denied` when attempting to write to `stdout` from a spawned process. You should be able to duplicate this outside of wallaby by spawning a new process from `nodejs` to run this code:

```javascript 
   var reportViaStdOut = process.stdout.write.bind(process.stdout);
   reportViaStdOut("Write to STDOUT");
```

The only suggestion we have is to try updating your `wallaby.js` configuration and remove the `runner` parameter from your `env` settings. Your config should then look like this:

```javascript
module.exports = function () {

  return {
    files: ['sum.js'],

    tests: ['__tests__/*.js'],

    env: {
      type: 'node'
    },

    testFramework: 'jest',
    debug: true
  };
};
```

We recommend comparing your two environments (Desktop and Laptop) to see what's different in your configuration. You may find your laptop's system log helpful in diagnosing/fixing the problem (you can read more about how to query it here: https://coreos.com/os/docs/latest/reading-the-system-log.html).

If you can provide us with a method to duplicate, we'd be happy to help you further.

**Comment by nklayman** [comment]
Thanks for your help, I really appreciate it. I figured it was something with my environment as nobody else reported the issue, and it works on my desktop. I'll look into the logs and see if I can figure it out.
