### ISSUE TITLE
Can't start wallaby in VS Code

### ISSUE THREAD

**Issue by eyaleizenberg** [wallabyjs/public#2028]
### Issue description or question
Can't start wallaby in VSCode. Getting the following:
```
[Error] module.js:557 
[Error]     throw err; 
[Error]     ^ 
[Error] Error: Cannot find module '/Users/eyale/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.119/wallaby/server.js' 
[Error]     at Function.Module._resolveFilename (module.js:555:15) 
[Error]     at Function.Module._load (module.js:482:25) 
[Error]     at Function.Module.runMain (module.js:701:10) 
[Error]     at startup (bootstrap_node.js:193:16) 
[Error]     at bootstrap_node.js:617:3 
```

### Wallaby.js configuration file
```
module.exports = function(wallaby) {
  return Object.assign({}, require('yoshi/config/wallaby-jest')(wallaby), {
    // set to undefined to let Wallaby decide the number of processes based on the system's capacity
    workers: undefined,
  });
};

```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

OSX 10.14

**Comment by ArtemGovorov** [comment]
Looks like your Wallaby extension installation somehow got corrupted. Please do the following:
- close VS Code,
- open `/Users/eyale/.vscode/extensions/` folder,
- delete all `wallabyjs.wallaby-vscode-*` subfolders,
- start VS Code and install Wallaby extension.

Please let us know if it helped.

**Comment by eyaleizenberg** [comment]
yup that solved it. thanks.
