### ISSUE TITLE
Can't find Jetbrains scheme color setting

### ISSUE THREAD

**Issue by kevinbeal** [wallabyjs/public#2029]
### Issue description or question

My custom Jetbrains theme has somehow chosen an extremely low contrast color for the hint text to the right of any statements ending in `/*?*/`.

I saw the color options for the little squares in the gutter, but I can't for the life of me locate the color setting that text that shows up in the background.

What setting is that under?

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

WebStorm v?2018.3.5

### OS name and version

OSX 10.13.4

**Comment by smcenlly** [comment]
The color that we use for `console.log` and `Live Comments` is the Console -> System output -> Foreground color. After changing the color, you will need to restart your WebStorm for the change to take effect.

![image](https://user-images.githubusercontent.com/2074089/54724766-424e3c80-4bb8-11e9-90df-94aa588c2a6a.png)
