### ISSUE TITLE
Tests report running and passing but VS Code does not show all lines executed

### ISSUE THREAD

**Issue by seebees** [wallabyjs/public#2030]
### Issue description or question

I've been playing with this all day :( so I finally came to ask.  In the Wallaby.js Console, I can see tests are running.  But when I open the test files, no coverage is reported (the green boxes).  Additional, only some source files show the green boxes that indicate test coverage.
This is doubly strange, because tests that exercise these files are reported as running and passing.

Finally in the Wallaby.js Tests console I have a lot of strange errors that I can't find out where they are coming from e.g.

Error ./modules/some-module/src/errors.ts (16,32): Cannot find name 'Error'. 
Error ./modules/some-module/src/errors.ts (19,5): Cannot find name 'Object'.

The above correspond to the lines:
```javascript
export class CustomError extends Error {
  constructor (message?: string) {
    super(message)
    Object.setPrototypeOf(this, CustomError.prototype)
  }
}
```

I had things working in the past, but I'm chasing my tail at this point, and I'm not sure how to set up a test repo as there are so many moving parts...

Any help would be appreciated.

### Wallaby.js configuration file

```javascript
'use strict'

module.exports = function (wallaby) {
  return {
    files: [
      'modules/**/src/**/*.ts',
      'modules/**/fixtures.ts',
      '!modules/**/test/**/*.test.ts',
      '!modules/**/node_modules/**',
      '!modules/**/build/**',
    ],
    tests: [
      'modules/**/test/**/*test.ts',
      '!modules/**/node_modules/**',
      '!modules/**/build/**',
    ],
    filesWithNoCoverageCalculated: [
      'modules/**/src/index.ts'
    ],
    testFramework: 'mocha',
    env: { type: 'node' },
    setup: w => {
      const {projectCacheDir} = w
      const path = require('path')
      const {Module} = require('module')
      if (!Module._originalRequire) {
        const modulePrototype = Module.prototype
        Module._originalRequire = modulePrototype.require
        modulePrototype.require = function (filePath) {
          if (!filePath.startsWith('@npm-namespace')) {
            return Module._originalRequire.call(this, filePath)
          }
          const [, _module] = filePath.split('/')
          const _filePath = path.join(projectCacheDir, 'modules', _module, 'src', 'index.js')
          return Module._originalRequire.call(this, _filePath)
        }
      }
    },
    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> Error ./modules/some-module/src/errors.ts (16,32): Cannot find name 'Error'. 
> Error ./modules/some-module/src/errors.ts (19,5): Cannot find name 'Object'.

These errors likely mean that there's an issue with TypeScript compilation of your source files by Wallaby.

Could you please share your `tsconfig.json` file?

Regarding other issue

> But when I open the test files, no coverage is reported (the green boxes). 

This should be pretty straightforward to isolate by
- copy/pasting your project, 
- removing all source file except for configs and one of those test files where coverage is not reported,
- simplifying the test file to only have a dummy test, 
- and sharing the resulting project with us.

Once we have the sample project, we are happy to take a loom and help with it.

**Comment by seebees** [comment]
I agree, that it would seem like an issue with TypeScript compilation... but the file in the cache look good... and the tests pass...

Here is a project that seems to do the bad things:

https://github.com/seebees/wallaby-issue-1665

The compilation errors are not... every time.  I sometimes have to start/stop wallaby a few times or change the test.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. We have identified an issue - it's the `composite: true` setting in your tsconfig file. Wallaby needs to set it to false by default (as it doesn't need it), or you may set it to false right in your Wallaby config. To avoid changing your config just update to [the latest Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and the issue should be fixed for you.

**Comment by seebees** [comment]
All is once again right with the world!  Thanks so much, I can now return to being productive :)
