### ISSUE TITLE
Runtime error: Uncaught SyntaxError: Unexpected token ! 

### ISSUE THREAD

**Issue by DonkeyKongJr** [wallabyjs/public#2031]
### Issue description or question

When starting wallaby inside our Angular 7 project we receive the following error:

> [Info]  Thu, 21 Mar 2019 09:40:41 GMT wallaby:middleware Serving /jasmine@2.1.3/starter.js from cache
> [Info]  Thu, 21 Mar 2019 09:40:41 GMT wallaby:workers Sandbox (active) [31zv4] error: Uncaught SyntaxError: Unexpected token !
> [Error] Runtime error: Uncaught SyntaxError: Unexpected token ! 
> [Error] at http://localhost:53207/____wallaby-bundle.js?1553161240995&wallabyFileId=bundle:66 
> [Info]  Thu, 21 Mar 2019 09:40:42 GMT wallaby:workers Sandbox (active) [31zv4] error: Uncaught Error: Cannot find module 'C:\Users\pschadler\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.119\projects\348fa303574dfcc4\instrumented\src\wallabyTest.js'
> [Error] Runtime error: Uncaught Error: Cannot find module '.\src\wallabyTest.js'

However, the karma test runner succeeds and has no problems.

I tried to run testfile by testfile, but the error remains, but the project just started and to this point there are only 2 test files.

<img src="https://i.postimg.cc/Bb2TwGDb/angular-project.png">

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['src/wallabyTest.js', 'src/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    workers: { initial: 1, regular: 1 },
    files: [
      { pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/tenant-details.component.spec.ts', load: false },
      { pattern: 'src/**/*e2e-spec.ts', ignore: true }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

Windows 10.0.17134.648

**Comment by ArtemGovorov** [comment]
Please try the following:

- Start Wallaby in your project, then open the `C:\Users\pschadler.vscode\extensions\wallabyjs.wallaby-vscode-1.0.119\projects\348fa303574dfcc4\instrumented\src\` folder, and check if the `wallabyTest.js` exists in the folder.
- Start Wallaby, open the `C:\Users\pschadler.vscode\extensions\wallabyjs.wallaby-vscode-1.0.119\projects\348fa303574dfcc4\instrumented` folder, zip and attach (or send us to hello@wallabyjs.com) the `____wallaby-bundle.js` file. Alternatively, check line 66 in the file (the line is reported in the error URL - for example from the error message that you have provided: `http://localhost:.../____wallaby-bundle.js?1553161240995&wallabyFileId=bundle:66`), and share the code on the line (and few lines before and after it).
- Is this sample repo working for you https://github.com/wallabyjs/ngCliWebpackSample if you clone it, run `npm i` and run Wallaby?

**Comment by DonkeyKongJr** [comment]
Thank you for your reply, with your help we figured out what went wrong.

The wallabyTest.js file was in that folder, but however the **automatic import** within VS Code messed things up.
Instead of using the relative path it used the absolute. 
Therefore no imported classes couldn't be found when running Wallaby.
