### ISSUE TITLE
jetbrains plugin doesn't work on pycharm version 2018.3

### ISSUE THREAD

**Issue by shaicantor** [wallabyjs/public#2033]
### Issue description or question
jetbrains plugin version v1.0.114 doesn't work on pycharm 2018.3

Ubuntu 16.04

![image](https://user-images.githubusercontent.com/2952388/54878260-dd524b00-4e32-11e9-8ce1-25283c96d893.png)

**Comment by ArtemGovorov** [comment]
PyCharm 2018.3 API had introduced a few breaking changes that we have fixed and addressed in plugin v1.0.118 (and greater). 

If you would like to use Wallaby with 2018.3, you may renew your license and install the latest version. 

If you don't want to renew your Wallaby license, you may download previous version(s) of PyCharm and use plugin v1.0.114.
