### ISSUE TITLE
Test VS Code Extension - cannot find module vscode

### ISSUE THREAD

**Issue by testpossessed** [wallabyjs/public#2035]
### Issue description or question
I am working on a VS Code Extension and want to test it with Wallaby.js as I work on some refactoring.  With the configuration below all tests work fine until I add an import for vscode into any file.  At that point I get a "Cannot find module 'vscode'" error.

There is no file in the vscode package that can be loaded as I have done with reflect-metadata.

The project is in a public repo at https://github.com/testpossessed/auto-barrel.  I would be very grateful if you could help me get wallabyjs up and running for this project.

### Wallaby.js configuration file
module.exports = (wallaby) => {

    return {
        files: [
            { pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false },
            'src/*.ts',
            'src/abstractions/*.ts'
        ],
        tests: [
            'src/test/unit/*.test.ts'
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        compilers: {
            'src/**/*.ts': wallaby.compilers.typeScript()
        },
        testFramework: 'jasmine',
        debug: true
    };

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

Windows 10 Pro build 17763

**Comment by ArtemGovorov** [comment]
Unfortunately Wallaby doesn't support the scenario at the moment. Please subscribe to [this feature request](https://github.com/wallabyjs/public/issues/1548) to receive updates on the issue.

**Comment by testpossessed** [comment]
Thanks Artem.  I have subscribed, but I think my scenario is not quite the same.  I don't want Wallaby to run integration tests and integrate with the host, that for me is not appropriate for continuous build and test as it would have the debug instance constantly starting up, not what I want as part of a TDD process.

I narrowed the issue down and it is at the point I try to spy on any part of the VS Code API that I get the error.  So for me the solution is to create an adapter that I can mock for unit tests.

**Comment by ArtemGovorov** [comment]
Thanks for the update Mike.

> I narrowed the issue down and it is at the point I try to spy on any part of the VS Code API that I get the error. So for me the solution is to create an adapter that I can mock for unit tests.

Sounds like you need to mock VS Code API somehow, and the issue is not specific to Wallaby (running Jasmine from CLI should produce the same results too). I have seen how [it's done in Jest](https://jestjs.io/docs/en/es6-class-mocks), I remember I have seen some third party libs to do similar with Jasmine, but unfortunately can't remember anything specific.
