### ISSUE TITLE
No tests run and markers lost on save

### ISSUE THREAD

**Issue by ericselin** [wallabyjs/public#2038]
### Issue description or question

I've stumbled across an annoying bug or possibly a configuration issue. Wallaby runs fine when starting up, and when modifying files. However, when I save a file (for instance a test file), all markers are lost. Also, if I save both the test file and source file, I need to slightly edit both to get the markers back.

When I look at the instrumented code, on startup and file modification everything seems fine, but when I save the file, all tests are gone from the instrumented file. Maybe by design, maybe not. But let's take the source file as an example:

```js
// Working instrumented source file
'use strict';
$_$wp(1);
$_$w(1, 0), Object.defineProperty(exports, '__esModule', { value: true });
$_$w(1, 1), exports.default = void 0;
const $_$wvd3 = $_$w(1, 2), fn = () => {
        $_$wf(1);
        return $_$w(1, 3), true;
    };
var _default = ($_$w(1, 4), fn);
$_$w(1, 5), exports.default = _default;
$_$wpe(1);
```

```js
// Instrumented source file after saving
'use strict';
$_$wp(1);
$_$wpe(1);
```

This doesn't happen _always_. On my own test repo it happens pretty much on every save, but on the sample AVA repo it happens more seldom (I think). But even on the sample repo, I managed to reproduce.

It _seems_ this problem occurs when wallaby does this: `wallaby:extended-core New document or complex document change`. But I really don't know.

### Sample repo and config file

https://github.com/ericselin/wallaby-test

```js
// wallaby.js for convenience
module.exports = (wallaby) => ({
  files: [
    'index.js',
  ],
  tests: [
    'index.test.js',
  ],
  env: {
    type: 'node',
    runner: 'node',
  },
  compilers: {
    '**/*.js': wallaby.compilers.babel({
      presets: ['@ava/babel-preset-stage-4'],
    }),
  },
  testFramework: 'ava',
  debug: true,
});
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3
Node 10.2.0
Wallaby.js Core v1.0.671

### OS name and version

Windows 10

**Comment by ericselin** [comment]
Possibly related to #2037

**Comment by dericgw** [comment]
@ericselin Glad I am not the only one experiencing this issue.

**Comment by smcenlly** [comment]
Thanks for providing the sample and great level of detail in your issue report. This was a big help in isolating the cause of this issue. The cause of the problem was a combination of Windows file system changed events and the way that VS Code flushes content to disk after write. Wallaby was receiving 0 bytes from the file system for the changed files, which is why your files were empty.

This has now been fixed. Please download the latest version of Wallaby for VS Code, v1.0.121. This will also download the latest version of Wallaby core, which is also necessary.
