### ISSUE TITLE
Jest, NextJS With Typescript & Babel 7

### ISSUE THREAD

**Issue by DmacLoyaltyOne** [wallabyjs/public#2044]
### Issue description or question
Having a really tough time trying to get wallaby setup with Jest / Babel7 / NextJS / Typescript

I can't seem to get all these to play nicely together

### Wallaby.js configuration file

Here is a sample repo
https://github.com/DmacLoyaltyOne/Wallaby-NextJS-Typescript

```
wallaby-nextjs-demo/src/setupTests.tsx:1 
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from 'react' 
```

```
module.exports = (wallaby) => ({
  files: [
    'src/**/*.json',
    { pattern: 'test/**/*.test.ts', ignore: true },
    { pattern: 'src/**/*.test.tsx', ignore: true },
    { pattern: 'src/**/*.test.ts', ignore: true },
    { pattern: 'src/.next/*.*', ignore: true },
    { pattern: 'src/next.config.js', ignore: true },
    { pattern: 'next.config.js', ignore: true },
    { pattern: 'src/setupTests.tsx', ignore: false },
    { pattern: 'jest/globals.js', ignore: true },
    'src/**/*.js*',
    'src/**/*.ts*',
    'src/**/*.tsx*',
    'src/**/*.png',
    'src/**/*.webp',
    'src/**/*.svg',
    'src/**/*.css',
    'src/**/*.scss',
  ],

  filesWithNoCoverageCalculated: [],

  hints: {
    ignoreCoverage: /istanbul ignore next/,
  },

  tests: [
    { pattern: 'node_modules/*', ignore: true, instrument: false },
    'src/**/*.test.ts*',
    'src/**/*.test.tsx*',
  ],

  compilers: {
    '**/*.js': wallaby.compilers.babel(),
    '**/*.jsx': wallaby.compilers.babel(),
    "**/*.ts?(x)": wallaby.compilers.typeScript({
      module: "commonjs",
      jsx: "React"
    })
  },

  preprocessors: {
    '**/*.png': (file, done) => {
      done('');
    },
    '**/*.svg': (file, done) => {
      done('');
    }
  },


  setup: function (wallaby) {



    const config = require('./package.json').jest
    // The paths to modules that run some code to configure or set up the testing environment before each test
    //config.setupFiles = [wallaby.localProjectDir + "/jest/globals.js"]

    // The path to a module that runs some code to configure or set up the testing framework before each test
    config.setupTestFrameworkScriptFile = wallaby.localProjectDir + "/src/setupTests.tsx"
    Object.keys(config.moduleNameMapper).forEach(k => (config.moduleNameMapper[k] = config.moduleNameMapper[k].replace('<rootDir>', wallaby.localProjectDir)))
    //Object.keys(config.setupFiles).forEach(k => (config.setupFiles[k] = config.setupFiles[k].replace('<rootDir>', wallaby.localProjectDir)))
    //setupTestFrameworkScriptFile.replace('<rootDir>', wallaby.localProjectDir)
    wallaby.testFramework.configure(config)
  },

  env: {
    type: 'node',
    runner: "node"
  },

  workers: {
    initial: 1,
    regular: 1,
    recycle: true,
  },

  testFramework: 'jest',
});

```

### Code editor or IDE name and version

Visual Studio Code v1.32.3

### OS name and version

OSX - 10.14.3

**Comment by smcenlly** [comment]
It seems I can't access your sample repo. If there's nothing private in there, can you please grant me access? In the meantime, I'll take a look through your config.

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo. I have pushed working Wallaby config to it (also simplified it a bit).

**Comment by DmacLoyaltyOne** [comment]
Hey @ArtemGovorov 
Thanks so much for the quick response.
After simplifying the repo, I ended up taking out another source of error that I'm having.
I added in a component that imports an .scss file

Currently I'm getting the following error:

```
Configuration error: 
 
Could not locate module ./LabeledIcon.scss mapped as: 
./__mocks__/styleMock.js. 
 
Please check your configuration for these entries: 
{ 
  "moduleNameMapper": { 
    "/\.(css|scss|less)$/": "./__mocks__/styleMock.js" 
  }, 
  "resolver": null 
} 
```

I pushed the latest update to the same repo to demonstrate

**Comment by ArtemGovorov** [comment]
> Nevermind, I fixed this issue. Running into a few other issues though, i'll see if I can push them up to the repo...

Thanks for the update. Sure, let us know if you have more issue tat we can take a look at in the repo, we're happy to help.

**Comment by DmacLoyaltyOne** [comment]
@ArtemGovorov 
Much appreciated. I just purchased the Quokka + Wallaby Combo yesterday 👏 

I have run into another issue.
jest.mock calls do not seem to be working.
The first symptom I ran into was the following:

```axios.get.mockResolvedValue('test') //TypeError: axios_1.default.get.mockResolvedValue is not a function  ```

I noticed that none of the jest mocks seemed to be working.
When I searched the documentation, I see I need to add something like

```
preprocessors: {
    '**/*.ts?(x)': file => require('@babel/core').transform(
      file.content,
      { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest'), require('react-app')] }),
    '**/*.js?(x)': file => require('@babel/core').transform(
      file.content,
      { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest'), require('react-app')] })
  },
```
my setupTests.tsx is a typescript file, so I would imagine I need to add the ts?(x) block as well.

But I get the following errors:


[Error] Postprocessor run failure: ENOENT: no such file or directory, open './src/client/components/Atoms/AMCard/AMCard.tsx'

**Comment by smcenlly** [comment]
Wallaby's preprocessors run as the last step before executing your code (after the TypeScript compiler). Therefore, the TypeScript files are already `js` which means that you don't need a `**/*.ts?(x)` preprocessor. Is your repo up-to-date in this state (i.e. not working, getting the ENOENT error)? If so, can you please grant me access so I can take a look for you?

**Comment by ArtemGovorov** [comment]
@DmacLoyaltyOne Thanks for your order!
You definitely don't need `ts?(x)` preprocessor, just the `js?(x)` one:

```diff
preprocessors: {
-   '**/*.ts?(x)': file => require('@babel/core').transform(
-     file.content,
-     { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest'), require('react-app')] -}),
    '**/*.js?(x)': file => require('@babel/core').transform(
      file.content,
      { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest'), require('react-app')] })
  },
```

If the solution above doesn't work, please upload a repro to your sample repo and provide @smcenlly with access to the repo.

**Comment by DmacLoyaltyOne** [comment]
Great, I found the issue!

```
diff
preprocessors: {
    -   '**/*.ts?(x)': file => require('@babel/core').transform(
-     file.content,
-     { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest'), require('react-app')] -}),
    '**/*.js?(x)': file => require('@babel/core').transform(
      file.content,
      { sourceMap: true, filename: file.path, presets: [require('babel-preset-jest')] })
  },

  compilers: {
    -  '**/*.js?(x)': wallaby.compilers.babel({ babelrc: true, presets: ['babel-preset-jest'] })
    +  '**/*.js?(x)': wallaby.compilers.babel(),
    '**/*.ts?(x)': wallaby.compilers.typeScript({ module: 'commonjs', jsx: 'React', target: 'esnext' })
  },
```

jest mocks are now working inline, but not through setupTests.tsx file.

@smcenlly I will add you to the repo, thanks!

Maybe this repo would be a good candidate for an example in the docs.
I can clean it up afterwards and we could add it.

**Comment by smcenlly** [comment]
@DmacLoyaltyOne, thanks for sharing your repo with me. 

I took a look and found a few problems with both your wallaby config and with jest generally. I've sent you a pull request with changes to get everything working. Most of the changes were `jest` related as the tests weren't working in jest either. When we're debugging what appears to be wallaby issues, we first test outside of wallaby as quite often the problems are actually there and once you solve them wallaby is OK and then the changes you need to get everything working are pretty minor.

I'll close the issue for now. If you have more problems with the same repo, feel free to post back here, we can re-open and take a look for you.

**Comment by DmacLoyaltyOne** [comment]
Yeah perfect, it works now. 
Huge thanks to you both.

Cheers

**Comment by smcenlly** [comment]
Thanks - let us know when you're happy with the state of the repo and we can add it to our examples.
