### ISSUE TITLE
Some tests show as not covered when they are, coverage is incorrect and changes with every run

### ISSUE THREAD

**Issue by seaBubble** [wallabyjs/public#2045]
### Issue description or question

In the Wallaby web app, the coverage of the project changes every time I run Wallaby.
For example, I see 5.77% and only 65 tests detected, then I run Wallaby again and I see only 56 tests detected. Karma detects 798 tests.
In the files section I can see how some files show 0% coverage, they appear as not covered in Webstorm too (gray squares) but the tests are there and run correctly by Karma.

I am using Wallaby Webstorm plugin v1.0.125

On the failing tests tab of Webstorm I see this error multiple times:
Uncaught TypeError: __webpack_require__.t is not a function
at http://localhost:58201/____wallaby-bundle.js?1554173659739&wallabyFileId=bundle:145787

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions
);

compilerOptions.module = 'CommonJs';

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['src/wallabyTest.js', 'src/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' },
        },
        { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000' },
      ],
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules',
      ],
      alias: {
        '@app': path.join(wallaby.projectCacheDir, 'src/app/'),
        '@shared': path.join(wallaby.projectCacheDir, 'src/app/shared'),
        '@env': path.join(wallaby.projectCacheDir, 'src/environments/'),
      },
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty',
    },
  });

  return {
    files: [
      { pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*spec.ts', ignore: true },
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false },
      { pattern: 'src/**/*e2e-spec.ts', ignore: true },
    ],

    hints: {
      ignoreCoverage: /ignore coverage/, // or /istanbul ignore next/, or any RegExp
    },

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions),
    },

    middleware: function(app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome',
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    debug: true,
  };
};

```

### Code editor or IDE name and version

Webstorm 2018.3

### OS name and version

OSX10.10.5

**Comment by ArtemGovorov** [comment]
The issue is that some of your tests don't run because of the error:

> Uncaught TypeError: webpack_require.t is not a function

The error happens because you are using an older version of the [`wallaby-webpack` package](https://www.npmjs.com/package/wallaby-webpack). Please update the package to the latest version 3.9.14.

**Comment by seaBubble** [comment]
Thanks @ArtemGovorov , I have done what you suggested and the error is gone, the coverage now seems stable but I still see some files that show as not covered (both in the web app and the IDE). The spec files were not initially there, I added them and run Wallaby again and the web app shows the files, but the covered file still appears as n/a. Any idea why this could be happening?

Thanks,

**Comment by ArtemGovorov** [comment]
Have you tried restarting Wallaby & refreshing Wallaby App? Also try stopping Wallaby, killing all node processes on your machine and starting it again. 

If you have tried the steps suggested above, but it didn't help, you please provide a specific example of the issue with some screenshots?

**Comment by seaBubble** [comment]
@ArtemGovorov I have noticed this is only happening if the classes I am testing (Angular components) have only a constructor and some inputs. The tests cover the component is created and the template rendered correctly, but I guess technically there is nothing in the class to test so Wallaby shows n/a. If I add a method to the class and add a test for it, the coverage becomes 100%. So I guess this is not really an issue, as long as these files are considered as 100% when calculating the overall percentage. Sorry about the confusion and thanks for your help.
