### ISSUE TITLE
Wallaby for Visual Studio 2019

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2047]
Will there be support for Visual Studio 2019?

### Code editor or IDE name and version
Visual Studio 2019

### OS name and version
Windows

**Comment by smcenlly** [comment]
We're currently working on a new plugin to support Visual Studio 2019. Unfortunately their API changed a little so it's not a trivial re-build on the latest set of .NET assemblies.

We don't have a firm release date that we can share at this stage, but expect it to be available in late April/early May 2019.

**Comment by ryandegruyter** [comment]
What about IntelliJ 2019?

**Comment by ArtemGovorov** [comment]
@ryandegruyter It is fully supported.

**Comment by spapaseit** [comment]
Hi guys, do you have a status update on VS 2019 support?

**Comment by smcenlly** [comment]
Hi @spapaseit - we've been working on a ground up rewrite to support Visual Studio 2019. We have a final test run to perform tomorrow and plan to release when that's finished. If you'd like to try out our release candidate, you can grab it from here: https://s3.amazonaws.com/wallaby-downloads/wallaby-vs-2019-v1.0.37.vsix

The new version has a much lower memory footprint and for larger projects we saw a reduction in test execution time by around 40%.

If you want to wait until the official release, we completely understand. If you do use this version and have any feedback for us or find problems, please let us know.

**Comment by spapaseit** [comment]
Hi @smcenlly, that's awesome news.

I'm more than happy to try the RC, thanks! :)

**Comment by Tchami** [comment]
I just ran the RC on a solution with ~600 tests. Only thing I noticed is that node.js is required for VS 2019. The VS 2017 vs VS 2019 execution time is roughly similar.

**Comment by smcenlly** [comment]
@Tchami - thanks for letting us know. We tested with the rxjs project, which had ~2500 tests.

**Comment by smcenlly** [comment]
We've now published this to the Visual Studio marketplace. You can download the [Visual Studio 2019 extension here](https://marketplace.visualstudio.com/items?itemName=vs-publisher-999439.WallabyjsforVisualStudio2017).
