### ISSUE TITLE
can wallaby kill my ssd?

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#2048]
### Issue description or question
I am worried that constantly running tests in the temp directory makes a lot of reads and writes to my ssd.  Have you benchmarked this and do you have the same concerns?  If so, is there a setting to let wallaby use an in memory disk or be able to configure wallaby to use an in memory disk that I have created? 
### Wallaby.js configuration file
na
### Code editor or IDE name and version
Visual Studio Code v1.32.3

### OS name and version

OSX 10.14.4

**Comment by smcenlly** [comment]
The short answer is that this is not a concern. I've answered your question below with some calculations to show why it's not a concern. If you're interested in knowing how SSDs work, I recommend checking out:

1) https://en.wikipedia.org/wiki/Solid-state_drive
2) https://www.ontrack.com/blog/2018/02/07/how-long-do-ssds-really-last/

> Device age, measured by days in use, is the main factor in SSD reliability, and not amount of data read or written, which are measured by TBW or DWPD. ([wikipedia](https://en.wikipedia.org/wiki/Solid-state_drive))

> SSDs have a built-in “time of death.” To keep it simple: An electric effect results in the fact that data can only be written on a storage cell inside the chips between approximately 3,000 and 100,000 times during its lifetime. After that, the cells “forget” new data. Because of this fact – and to prevent certain cells from getting used all the time while others aren’t – manufacturers use wear-leveling algorithms to distribute data evenly over all cells by the controller. ([ontrack article](https://www.ontrack.com/blog/2018/02/07/how-long-do-ssds-really-last/))

> Usually, manufacturers give an estimate with the so-called terabyte(s) written (TBW)– especially when it comes to enterprise SSDs, but also for consumer versions. Because of the fact that by using Wear-Leveling the data will be distributed evenly over all cells, this figure is supposed to tell how much data can be really written in total on all cells inside the storage chips and over the whole life span. ([ontrack article](https://www.ontrack.com/blog/2018/02/07/how-long-do-ssds-really-last/))

Let's use the [Samsung 860 EVO SSDs](https://www.samsung.com/semiconductor/minisite/ssd/product/consumer/860evo/) in an example, which have a warrantied TBW of: 150 TBW for 250 GB model, 300 TBW for 500 GB model, 600 TBW for 1 TB model, 1,200 TBW for 2 TB model and 2,400 TBW for 4 TB model. 

Most of the time, Wallaby is only updating your changed files. It can do a little more at startup and if you change your Wallaby configuration, but those are really edge cases that won't change much in our calculations. 

Let's say that you only have large files that you're changing (100K would be a reasonably large code file), and you change it every second of your working day (8 hours a day). If you do that every day of the year, that works out to be:

**Number of file changes in a year**
```
60 seconds x 60 minutes x 8 hours x 365 days = 1,0512,000 file changes
```

**Total bytes written**
```
100 KB x 1,0512,000 changes = 1,051,200,000 Kb = 0.97 TB
--
```

I think you'll agree that's a pretty extreme example. Given the smallest SSD, it would take ~150 years for Wallaby to be the cause of HDD failure. For the largest disk, it would take ~2400 years. Having said that, remember, that device age is the leading cause of failure, not number of writes, so they'll die well before then.

**Comment by foxbunny** [comment]
> it would take ~150 years for Wallaby to be the cause of HDD failure

That's good because I was planning to let my kids have my SSD when I die. :D
