### ISSUE TITLE
Aurelia support

### ISSUE THREAD

**Issue by RainerAtSpirit** [wallabyjs/public#205]
JFI: Feel free to add to the Configuration file section. 

https://github.com/RainerAtSpirit/skeleton-navigation/blob/master/wallaby.js

```javascript
var babel = require('babel');

module.exports = function(wallaby) {

    return {
        files: [

            {pattern: 'jspm_packages/system.js', instrument: false},
            {pattern: 'config.js', instrument: false},

            {pattern: 'src/**/*.js', load: false}

        ],

        tests: [
            {pattern: 'test/unit/**/*.spec.js', load: false}
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel,
                sourceMap: 'inline',
                modules: 'system',
                moduleIds: false,
                optional: [
                    "es7.decorators",
                    "es7.classProperties"
                ]
            })
        },

        middleware: ( app, express ) => {
            app.use('/jspm_packages', express.static(require('path').join(__dirname, 'jspm_packages')));
        },

        bootstrap: function( wallaby ) {
            wallaby.delayStart();

            var promises = [];
            for ( var i = 0, len = wallaby.tests.length; i < len; i++ ) {
                promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
            }

            Promise.all(promises).then(function() {
                wallaby.start();
            });
        },

        debug: false
    };
};
```

**Comment by ArtemGovorov** [comment]
@RainerAtSpirit Awesome, thanks! Added the repo link to the [supported integrations](http://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallaby-js-config).

**Comment by zewa666** [comment]
@RainerAtSpirit seems we're having issues with the latest jspm@beta release. One thing for sure needed is redefining the new System.paths inside bootstrap:

```
System.config({
        paths: {
          '*': '*.js'
        }
      });
```

otherwhise JSPM is unable to find the test files and errors out with few 404s. But now we get the error:

`TypeError: Invalid anonymous System.register module load. If loading a single module, ensure anonymous System.register is loaded via System.import. If loading a bundle, ensure all the System.register calls are named.`

I'm on it trying to fix it, just wanted to drop the information here for reference, in case someone else already has found a solution

**Comment by RainerAtSpirit** [comment]
@zewa666 Thanks for the information. Might have to wait till jspm@beta is released. At the moment this looks like a moving target to me :).

**Comment by ArtemGovorov** [comment]
Made it work with the latest version, here is the pull request with the configuration - https://github.com/aurelia/skeleton-navigation/pull/174
Here is the updated config file: https://github.com/wallabyjs/skeleton-navigation/blob/e6678c60e18f5794e91549ef5db115f929156fad/wallaby.js

**Comment by zewa666** [comment]
@ArtemGovorov thanks, seems that something changed with JSPM in the meanwhile because I cannot see any obvious difference between your config and mine, nor does my diff tool besides some whitespaces :)

Anyways thanks for the help and +1 for Atom support, works like a charm

**Comment by ArtemGovorov** [comment]
@zewa666 As you have been suggesting, I have added 
```
System.config({
        paths: {
          '*': '*.js'
        }
      });
```
and also removed `modules: 'system',` related stuff from babel compiler settings.
