### ISSUE TITLE
Configuring WallabyJS to work with Ember in WebStorm

### ISSUE THREAD

**Issue by djodonnell** [wallabyjs/public#2051]
I'm trying to setup Wallaby in WebStorm for use in an Ember JS project.  Ember uses QUnit by default for unit tests, integration tests and acceptance tests.  Ember's test runner is Testem which is great, but unsupported by WebStorm, and there is no way to interactively debug tests...which is what attracted me to Wallaby.

Would you please be able to assist me in getting this working? ...or of course if anyone else has successfully gone down the same path and got it working.

In terms of the steps that I have taken:

Step 1:

Installed WallabyJS as a plugin to WebStorm (manually)

Step 2:

Created a Wallaby configuration file called wallaby.js (as follows)

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'app/**/*.js'
    ],

    tests: [
      'tests/**/*.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    debug: true
  };
};
```

Step 3:

Created a project configuration based on the Wallaby template and pointed to the wallaby.js configuration file

Step 4:

Run the project configuration

In terms of output I'm receiving in the "Wallaby Console" I receive a lot of status messages and then...

```javascript
Runtime error: ./tests/integration/helpers/capitalise-test.js:2
import {
       ^

SyntaxError: Unexpected token {
``` 
I receive a similar error for every unit, integration and acceptance test file.  I presume this is something to do with ES6.

The other thing I noticed is that Wallaby is not looking through all of the subfolders in the "tests" folder, so I'm not sure what I need to do in the configuration file to make it recurse through the subfolders because Ember creates folders that match the route hierarchy, so I don't want to have to manually add folders to the Wallaby configuration file as I create them; hopefully there is a better way.

### Code editor or IDE name and version

WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
Licensed to Datashow Pty Ltd / David O'Donnell
Subscription is active until January 16, 2020
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4 

Thank you so much for your help as Wallaby looks very good and I'm keen to make it part of my workflow.

**Comment by ArtemGovorov** [comment]
Unfortunately we are not very familiar with Ember and its ecosystem, so not sure if it's possible to make Wallaby work with it. This [response](https://github.com/wallabyjs/public/issues/13#issuecomment-217046185) may shed some light on the direction to proceed though. 

The errors that you are currently getting are expected because your current config is trying to run tests in node (using mocha), and node doesn't support ES modules, so you will need to configure [Babel](https://wallabyjs.com/docs/integration/es-next.html) with proper presets to compile ES modules to CommonJs.

**Comment by djodonnell** [comment]
Thanks for the quick response.  I've followed your ES6/ES7 Wallaby configuration file example:

```javascript
module.exports = function () {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      'app/**/*.js'
    ],

    tests: [
      'tests/**/*.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    debug: true
  };
};
```

I now receive an error

```javascript
ReferenceError: wallaby is not defined
```

**Comment by ArtemGovorov** [comment]
`wallaby` is supposed to be a name of the `module.exports = function () {` parameter:

```diff
-module.exports = function () {
+module.exports = function (wallaby) {
```

I don't expect the config to work yet though. ES modules will be compiled to CommonJs but since you've switched your config from node to browser environment, there need to be some module bundler to actually bundle the code prior to running tests. I don't know how it works in Ember, but you may have a look into our [Webpack integration docs](https://wallabyjs.com/docs/integration/webpack.html) to see if you can use it.

**Comment by djodonnell** [comment]
Ok - now I just see...

```javascript
Error: Missing tracer start subscription
at http://localhost:50147/__wallaby__/tracer.js:14
```
(many times)

I've started looking into the module bundling.  I'm way out of my depth here as I don't really understand what the build pipeline is or what needs to be fed to what, but so far I have learnt that:

Ember uses rollup.js to do its bundling, so presumably I can use it for this purpose before Wallaby parses the bundle.

**ember-auto-import** seems to be the way to do this, although I'm not exactly sure how/where I'm supposed to use it, although the dynamic option looks like it's probably the answer.  There are other options like **ember-rollup** which are recommended for building addons.

https://github.com/ef4/ember-auto-import

**Comment by smcenlly** [comment]
@djodonnell, to get this working, you're going to need a `rollup.js` post-processor for wallaby. You could use the `wallaby-webpack` post-processor as a starting point (https://github.com/jeffling/wallaby-webpack). You can find more information about writing a post-processor in [our docs](https://wallabyjs.com/docs/config/postprocessor.html).

I think the ideal scenario for you would be to somehow configure `jest` to run your ember tests. If you had your project working in `jest`, you could quickly/easily get these working in wallaby. I took a quick look and couldn't see that anyone has done this.

I'm going to close this issue as at this point in time, we don't support `rollup.js`, which is a requirement for `ember`. You may up-vote our [rollup support feature request](https://github.com/wallabyjs/public/issues/736). If you feel like contributing an open-source rollup postprocessor, we'd appreciate your help.
