### ISSUE TITLE
Module not found: Error: Can't resolve '@s3-angular/sch-svc' in '.\src\environments'

### ISSUE THREAD

**Issue by chauey** [wallabyjs/public#2054]
### Issue description or question
Given the paths setting, the ts file it points to, and the wallaby.js modules and alias settings I have, can you please help me find out what is wrong? There is source code for lib project in "./projects/sch-svc". THANKS!

**ts.config** 
...
   "paths": {
     "@s3-angular/sch-svc": [
            "projects/sch-svc/src/public_api"
         ],
...

**projects\sch-svc\src\public_api.ts**
has import and exports

### Wallaby.js configuration file

```javascript
...
modules: [
        path.join(wallaby.projectCacheDir, 'projects'),
...
 alias: {
        '@s3-angular/sch-svc': 
        path.join(wallaby.projectCacheDir, 'projects/sch-svc/src/public_api')
      }
```

### Code editor or IDE name and version

Visual Studio Code v1.?

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Could you please share your full Wallaby config?

**Comment by chauey** [comment]
Thanks. Also, I see some files import modules like this, is it problematic vs. relative paths?

import { ObjectUtils } from 'src/app/shared/utils/object.utils';

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader'}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'raw-loader'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'projects'),
        // path.join(wallaby.projectCacheDir, 'projects/sch-services/src'),
        // path.join(wallaby.projectCacheDir, 'projects/sch-services/src/lib'),
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
        '@s3-angular/sch-services': 
        path.join(wallaby.projectCacheDir, 'projects/sch-services/src/public_api')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},
      // {pattern: 'projects/**/*.d.ts', ignore: true},
      {pattern: 'projects/**/*.*', instrument: false, load: false }
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

Unfortunately we can't reproduce the issue with your config. We have created this [sample repo branch](https://github.com/wallabyjs/ngCliWebpackSample/tree/wallaby-2054), with your config file, adde a simple [`projects/sch-svc/src/public_api.ts`](https://github.com/wallabyjs/ngCliWebpackSample/blob/wallaby-2054/projects/sch-svc/src/public_api.ts), importing it from a [sample test](https://github.com/wallabyjs/ngCliWebpackSample/blob/wallaby-2054/src/app/app.component.spec.ts#L3-L5) and everything is working ok. Could you please take a look into the sample repo branch to see if it's working for you and what is different from your project?



> Also, I see some files import modules like this, is it problematic vs. relative paths?

Yes, this should help:

```diff
      modules: [
+       path.join(wallaby.projectCacheDir, 'projects'),
        path.join(wallaby.projectCacheDir, 'projects'),
        // path.join(wallaby.projectCacheDir, 'projects/sch-svc/src'),
        // path.join(wallaby.projectCacheDir, 'projects/sch-svc/src/lib'),
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
```

**Comment by chauey** [comment]
​​​​​​​​​​Thanks, I currently have this error:

​​Uncaught TypeError: Cannot read property 'Error' of undefined​​
  at ​src/environments/environment.ts:44:0​

There is a line with this:
      logLevel: LogLevelEnum.Error,

On top imports the enum:
import { LogLevelEnum } from '@s3-angular/core';

That package is listed package.json and installed in node_modules.

Any tips what to look at? Thanks!

**Comment by ArtemGovorov** [comment]
I think this could be related to [Wallaby overriding some TS compiler settings](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings), this config change should help:

```diff
var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);
+compilerOptions.useStandardDefaults = true;
```

**Comment by chauey** [comment]
It got me further, thank you!
