### ISSUE TITLE
Is there support for BigInt?

### ISSUE THREAD

**Issue by NikkiJ19** [wallabyjs/public#2056]
### Issue description or question
I get a "Failed to instrument" error message.

![image](https://user-images.githubusercontent.com/31554476/56175579-9debca00-5fac-11e9-9334-159e0cd0937f.png)

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version
WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

### OS name and version

![image](https://user-images.githubusercontent.com/31554476/56175424-04bcb380-5fac-11e9-951e-08c3dc2e24e6.png)

**Comment by smcenlly** [comment]
We've actually been working on this feature and are planning to release it today. We'll let you know when it's ready.

**Comment by smcenlly** [comment]
We have added support for `bigint` in the latest version, Wallaby core v1.0.677. Please note that if you are using other tools that transform your code (e.g. `jest` or `webpack`), you may need to also modify their configuration in the event that they don't support `bigint`.

![image](https://user-images.githubusercontent.com/2074089/56181791-73ece300-6052-11e9-9262-18f71b7d78d7.png)
