### ISSUE TITLE
setup not working

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#2057]
### Issue description or question
Chai and should are not set on `global` when referencing them in my tests. 
### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'wallaby'
let prefix = './src/**/'
module.exports = function(wallaby) {
    return {
        setup: function() {
            global.chai = require('chai')
            global.should = global.chai.should()
            // require(`./src/test/beforeAllTests.js`)
            wallaby.testFramework.configure(require('./package.json').jest)
        },
        files: [
            `${prefix}*.js`,
            `${prefix}*.png`,
            `!${prefix}*Tests.js`,
            // `${prefix}test/beforeAllTests.js`,
        ],
        tests: [
            `${prefix}*Tests.js`,
            // `!${prefix}test/beforeAllTests.js`,
        ],
        env: {
            type: 'node',
            runner: 'node',
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: require('@babel/core'),
                presets: ['module:metro-react-native-babel-preset', ],
            }),
        },
    }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.33.1

### OS name and version

OSX 10.14.4

**Comment by ArtemGovorov** [comment]
Jest creates its won global scopes for executing tests, so setting globals in the `setup` function won't help.

In order to make it work, you don't actually need to change Wallaby config, you need to configure Jest (and Wallaby will just work once Jest in correctly configured). To do it, you may use Jest [`setupFiles` setting](https://jestjs.io/docs/en/configuration#setupfiles-array) in your Jest config and specify a file that sets the globals.

**Comment by bj97301** [comment]
Good suggestion.  I tried that before but kept getting an error from wallaby:
```bash
0 failing tests, 0 passing 
 
● Validation Error: 
 
  Module ./src/test/beforeAllTests.js in the setupFiles option was not found. 
         <rootDir> is: /Users/Bryan/code/nativeApp 
 
  Configuration Documentation: 
  https://jestjs.io/docs/configuration.html 
 
```

But running my tests from the terminal was successful:
```bash
  console.log src/test/beforeAllTests.js:1
    setting up

 PASS  src/appTests.js
  app
    ✓ renders without errors (11ms)
    ✓ has an image (102ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.37s
Ran all test suites.

Watch Usage: Press w to show more.
```

**Comment by ArtemGovorov** [comment]
Looks like it happens because the `src/test/beforeAllTests.js` is excluded from your `files` via the specified patterns.

Try this config:

```js
process.env.NODE_ENV = 'wallaby'
let prefix = 'src/**/'
module.exports = function(wallaby) {
    return {
        files: [
            `${prefix}*.js`,
            `${prefix}*.png`,
             `!${prefix}!(beforeAll)Tests.js`,
        ],
        tests: [
            `${prefix}*Tests.js`,
            `!${prefix}test/beforeAllTests.js`,
        ],
        env: {
            type: 'node',
            runner: 'node',
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: require('@babel/core'),
                presets: ['module:metro-react-native-babel-preset', ],
            }),
        },
    }
}
```

If it doesn't help, please share a sample repo demonstrating the issue, we are happy to take a look.

**Comment by bj97301** [comment]
That was it.  Thank you.  

Combining the logic like that isnt very intuitive for me.  Any idea why this doesnt work:
```js
`!${prefix}*Tests.js`,
`${prefix}test/beforeAllTests.js`,
```

**Comment by smcenlly** [comment]
@bj97301 - this is by design, as per [our docs](https://wallabyjs.com/docs/config/files.html#pattern):

> if a file pattern is marked as ignored, it will be ignored regardless of its position in the files/tests list.

Unfortunately we can't change this behavior as people rely on the configuration working this way.
