### ISSUE TITLE
ES6 modules and folder import issue

### ISSUE THREAD

**Issue by onexdata** [wallabyjs/public#2066]
### Issue description or question
Trying to use GSAP and anime.js in tests, which use ES6, but get 'unexpected token "import"' from Jest inside the GSAP/anime.js packages when running Wallaby unless I add 'node_modules/animejs/**' and 'node_modules/gsap/**' respectively to files in wallaby.js config file, however, this adds the folders to test coverage and messes up the coverage numbers.

Also, can't seem to import anything from the 'test/jest/__mocks__' folder or 'test/utils' folders, which just include test helpers. Wallaby says it can't find the includes unless I add the folders to the files list, but again adding them to the files list adds them to the coverage report which is not wanted.

### Wallaby.js configuration file
```javascript
module.exports = (wallaby) => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;
  const compiler = wallaby.compilers.babel();
  return {
    files: [
      'jest.config.js',
      'package.json',
      'src/**/*.js?(x)',
      'src/**/*.vue',
      'test/utils/**', // Can't import from here unless I include it in files list ?
      'test/jest/__mocks__/**', // Can't import from here unless I include it in files list ?
      '/node_modules/animejs/**', // Jest can't see ES6 unless I include it in files list ?
      '/node_modules/gsap/**', // Jest can't see ES6 unless I include it in files list ?
      '!src/**/*.spec.js?(x)'
    ],

    tests: ['test/**/*spec.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler)
    },

    preprocessors: {
      '**/*.vue': file => require('vue-jest').process(file.content, file.path)
    },

    setup (wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config');
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.31.1

### OS name and version
OSX 10.14.2

**Comment by ArtemGovorov** [comment]
It is ok to include required files in the `files` list, to exclude the files from code coverage calculation you may [use this setting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file).
