### ISSUE TITLE
setupFilesAfterEnv not extending expect

### ISSUE THREAD

**Issue by nathanvale** [wallabyjs/public#2067]
### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test'
process.env.NODE_ENV = 'test'

const jestConfig = {
  collectCoverageFrom: ['src/**/*.+(js|jsx|ts|tsx)'],
  testMatch: ['**/__tests__/**/*.+(js|jsx|ts|tsx)'],
}

const files = [
  './src/**/*.json',
  ...jestConfig.collectCoverageFrom,
  ...jestConfig.testMatch.map(file => `!${file}`),
  '!dist',
  '!node_modules',
]

const tests = [...jestConfig.testMatch, '!node_modules', '!dist']
// eslint-disable-next-line func-names
module.exports = function(wallaby) {
  const config = {
    debug: true,
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
    files,
    tests,
    compilers: {
      '**/*.{js,ts,tsx}': wallaby.compilers.babel({
        babelrc: true,
      }),
    },
  }
  return config
}

```

### Code editor or IDE name and version

Visual Studio Code v1.33.1

### OS name and version

OSX 10.14.4

Hi there,

I am having an issue with getting wallabyjs to extend expect with my setupfiles in my jest config in my package.json

   "setupFilesAfterEnv": [
      "jest-axe/extend-expect",
      "jest-dom/extend-expect",
      "react-testing-library/cleanup-after-each"
    ],

Jest  is able to do this, Is anyone able to suggest a way around this?

![Screen Shot 2019-05-07 at 3 32 28 pm](https://user-images.githubusercontent.com/6100206/57274080-5e149000-70dd-11e9-8b36-55a0f87d6969.png)
![Screen Shot 2019-05-07 at 3 32 18 pm](https://user-images.githubusercontent.com/6100206/57274081-5ead2680-70dd-11e9-8afc-f715a8eacb7c.png)

I have a branch showing the behaviour here.

https://github.com/nathanvale/okmotels/tree/write-tests-for-login

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. You have 2 different versions of Jest installed in your project (one that comes with `react-scripts`, and one that comes with `easy-scripts`). Wallaby was using an older version that doesn't support `setupFilesAfterEnv` setting. The issue is fixed and the fix is available in [the latest Wallaby core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
