### ISSUE TITLE
Cannot convert undefined or null to object with Nrwl + Angular + Jest

### ISSUE THREAD

**Issue by Steven-Harris** [wallabyjs/public#2072]
### Issue
I am trying to get wallaby to run my jest tests in my nrwl-angular projects and I can't get anything to work. I keep getting 
>wallaby:workers Failed to map the stack to user code, entry message: Cannot convert undefined or null to object, stack: TypeError: Cannot convert undefined or null to object

### Sample Repo
https://github.com/Steven-Harris/nrwl-jest-wallaby

### Logs
[console.log](https://github.com/wallabyjs/public/files/3169325/console.log)

### Versions 
>MacOs: 10.14.4
VsCode: 1.33.1
Nrwl: 7.4.3
Angular: ^7.0.0
Jest: 24.1.0

**Comment by ArtemGovorov** [comment]
From the log it looks like the error is coming from your config `setup` function. After a quick look I can see what can be the issue - you are reading Jest config from your `package.json` in your `setup` function, however the config is located in the `jest.config.js`. Also `jest-preset-angular/jest-preset` doesn't seem to be used in your `jest.config.js`, so you may delete it from your Wallaby config `setup` too:

```diff
module.exports = function(wallaby) {
  return {
    files: [
      'apps/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
+     'jest.config.js'
      '!apps/**/*.spec.ts'
    ],

    ...

    setup: function(wallaby) {
-     let jestConfig = require('./package.json').jest;
+     let jestConfig = require('./jest.config');
-      delete jestConfig.preset;
-      jestConfig = Object.assign(
-        require('jest-preset-angular/jest-preset'),
-        jestConfig
-      );
      jestConfig.transformIgnorePatterns.push('instrumented.*.(jsx?|html)$');
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```
