### ISSUE TITLE
​​Uncaught Error: Cannot find module 'core-js/es6/reflect'​​   at ​wallabyTest.ts:1​ ...

### ISSUE THREAD

**Issue by chauey** [wallabyjs/public#2073]
### Issue description or question
Any tips on what to try for this error with Angular Nx project. Thanks!

​​Uncaught Error: Cannot find module 'core-js/es6/reflect'​​
  at ​wallabyTest.ts:1​
​​Uncaught Error: Cannot find module '@angular/core/testing'​​
  at ​apps/aspnetzero69/src/app/app.component.spec.ts:3​
​​Uncaught Error: Cannot find module '@angular/core/testing'​​
  at ​apps/dna-components-demo/src/app/app.component.spec.ts:1​
​​Module not found: Error: Can't resolve 'css-loader' in 'C:\dna-ws'ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in 'C:\dna-ws'​​

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./apps/genhub/tsconfig.spec.json').compilerOptions,
  require('./libs/ncg/tsconfig.spec.json').compilerOptions
);

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: ['wallabyTest.js', 'apps/**/*spec.js', 'libs/**/*spec.js'],

    module: {
      rules: [
        { test: /\.css$/, loader: ['raw-loader', 'css-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        {
          test: /\.ts$/,
          loader: '@ngtools/webpack',
          include: /node_modules/,
          query: { tsConfigPath: 'tsconfig.json' }
        },
        {
          test: /\.js$/,
          loader: 'angular2-template-loader',
          exclude: /node_modules/
        },
        { test: /\.js$/, loader: 'shebang-loader', include: /node_modules/ },
        { test: /\.json$/, loader: 'json-loader' },
        { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
        { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
        { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
        { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules'
      ],
      alias: {
        '@myworkspacename/mylib': path.join(
          wallaby.projectCacheDir,
          'libs/mylib/src/index.ts'
        )
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      { pattern: 'wallabyTest.ts', load: false },
      {
        pattern: 'apps/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'apps/**/*.d.ts', ignore: true },
      { pattern: 'apps/**/*spec.ts', ignore: true },
      {
        pattern: 'libs/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)',
        load: false
      },
      { pattern: 'libs/**/*.d.ts', ignore: true },
      { pattern: 'libs/**/*spec.ts', ignore: true },
      { pattern: 'apps/**/*-e2e/**', ignore: true },
      { pattern: 'libs/**/*-e2e/**', ignore: true }
    ],

    tests: [
      { pattern: 'apps/**/*spec.ts', load: false },
      { pattern: 'libs/**/*spec.ts', load: false },
      { pattern: 'apps/**/*-e2e/**', ignore: true },
      { pattern: 'libs/**/*-e2e/**', ignore: true }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    env: {
      kind: 'electron'
      // kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function() {
      window.__moduleBundler.loadTests();
    },

    // workers: {initial: 1, regular: 1}
  };
};
```

### Code editor or IDE name and version

Visual Studio Code

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> ​​Uncaught Error: Cannot find module 'core-js/es6/reflect'​​
at ​wallabyTest.ts:1​
> ​​Uncaught Error: Cannot find module '@angular/core/testing'​​
at ​apps/aspnetzero69/src/app/app.component.spec.ts:3​
> ​​Uncaught Error: Cannot find module '@angular/core/testing'​​
at ​apps/dna-components-demo/src/app/app.component.spec.ts:1​

Looks like wallabyTest.ts file is in your project's root, does your `node_modules` root folder have `@angular/core/testing`/`core-js/es6/reflect'` modules? If not, you either need to
-  move the file to where they are (and change its paths in your Wallaby config).
- or add the `node_modules` location to the list:

```diff
modules: [
        path.join(wallaby.projectCacheDir, 'apps'),
        path.join(wallaby.projectCacheDir, 'libs'),
        'node_modules',
+       path.join(wallaby.localProjectDir, 'relative_path_to_node_modules'), // <--
      ],
```

> ​​Module not found: Error: Can't resolve 'css-loader' in 'C:\dna-ws'ModuleNotFoundError: Module not found: Error: Can't resolve 'css-loader' in 'C:\dna-ws'​​

This should help (as in our [current sample config for Angular CLI repos](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js)):

```diff
    module: {
      rules: [
-        { test: /\.css$/, loader: ['raw-loader', 'css-loader'] },
+        { test: /\.css$/, loader: ['raw-loader'] },
```

**Comment by chauey** [comment]
Would you be so kind as to help me get past it here: https://github.com/chauey/nx-wallaby-test

The modules seems to be there in node_modules;
I can't figure it out, I thought it might be the core-js version.

Thanks.

**Comment by smcenlly** [comment]
Thanks for sending through the sample. After cloning and installing your npm packages, we received this error:

```
Uncaught Error: Cannot find module 'core-js/es6/reflect' 
  at ​wallabyTest.ts:1​
Uncaught Error: Cannot find module '@angular/core/testing' 
  at ​libs/my-lib/src/lib/my-lib.module.spec.ts:1​
Module not found: Error: Can't resolve 'shebang-loader' in 'C:\temp\nx-wallaby-test'ModuleNotFoundError: Module not found: Error: Can't resolve 'shebang-1loader' in 'C:\temp\nx-wallaby-test' 
    at factory.create (C:\temp\nx-wallaby-test\node_modules\webpack\lib\Compilation.js:797:10) 
    at factory (C:\temp\nx-wallaby-test\node_modules\webpack\lib\NormalModuleFactory.js:397:22) 
    at resolver (C:\temp\nx-wallaby-test\node_modules\webpack\lib\NormalModuleFactory.js:130:21
```

After installing the shebang-loader npm package `npm install shebang-loader --save-dev`, the problem went away and wallaby started working. Because your sample didn't include any of your apps files, we had to modify the entryPatterns to work for us, removing ` //'apps/**/*spec.js',`.

If you're still having problems after installing the missing module, please send through a more complete sample, we'd be happy to take a look.
