### ISSUE TITLE
Is it possible to use Wallaby while developing vscode extensions?

### ISSUE THREAD

**Issue by parithon** [wallabyjs/public#2075]
I'm not sure it is even possible because vscode is a highly customized electron app, but I ask in case somebody has some insights that I might have missed.

**Comment by ArtemGovorov** [comment]
Unfortunately Wallaby doesn't support the scenario at the moment. Please subscribe to [this feature request](https://github.com/wallabyjs/public/issues/1548) to receive updates on the issue.

**Comment by parithon** [comment]
It appears my search foo isn't up to snuff. Thanks for pointing me to the previous request.
