### ISSUE TITLE
describe() content missing in Wallaby App when HTML-like string

### ISSUE THREAD

**Issue by cadichris** [wallabyjs/public#2076]
### Issue description or question
I'm working on a **React** app created through `create-react-app`.  
My tests are executed by **Jest**.
When the `describe("")` of a test suite contains HTML-like string, it's not rendered in the Wallaby App.

On the screenshot below, we see that the `describe("<Echeances />"` results in an empty block in Wallaby App.
**Expected behavior** : **`<Echeances />`** string is displayed in Wallaby App.

![image](https://user-images.githubusercontent.com/24898521/57715996-49ee0700-7678-11e9-8a79-2d0a1449ed1c.png)

Where my `describe()` contains regular text, I have no problem.

### Wallaby.js configuration file
It's identical to https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app

### Code editor or IDE name and version
IntelliJ IDEA Ultimate v2019.1

### OS name and version
MacOS Mojave 10.14.4

**Comment by smcenlly** [comment]
Thanks for reporting the issue. If you refresh your wallaby app, this should now be fixed.

**Comment by cadichris** [comment]
I can confirm it's now working ✅ . Thanks !
