### ISSUE TITLE
Integration problems with Vue+Quasar

### ISSUE THREAD

**Issue by MechJosh0** [wallabyjs/public#2078]
### Issue description
I'm trying to integrate Wallaby into a Vue project with Quasar but I'm getting this error:
```bash
.\node_modules\quasar\src\components\btn\QBtn.js:1 
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from 'vue' 

SyntaxError: Unexpected identifier 
```

If we remove `QBtn` from the project we then get an error with the file type `.styl` using `@import`.

```bash
.\src\styles\quasar.styl:1 
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){@import './quasar.variables.styl' 

SyntaxError: Invalid or unexpected token
```

### Wallaby.js configuration file
https://github.com/MechJosh0/wallabyjs-issue-project/blob/master/wallaby.js

### Wallaby.js example project
https://github.com/MechJosh0/wallabyjs-issue-project

### Code editor or IDE name and version
Visual Studio Code v1.33.1

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. The issue was that required Jest transforms had been removed (by overwriting the transforms setting). We have sent your the [pull request with the working config](https://github.com/MechJosh0/wallabyjs-issue-project/pull/1).
