### ISSUE TITLE
Add support for .babelrc

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#208]
Babel supports configuration via `.babelrc` or `package.json` files which can be used globally: https://babeljs.io/docs/usage/babelrc/

But it seems wallaby still does not support it since I'm getting `file ... has invalid syntax` after removing options from `wallaby.conf.js` and moving it to `.babelrc`

**Comment by ArtemGovorov** [comment]
Wallaby doesn't read the file, but this should work for now if you'd like to use the `.babelrc` file:

``` JavaScript
var babel = require('babel');

var babelConfig = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, '.babelrc')));
babelConfig.babel = babel;

module.exports = function (wallaby) {
  return {
    files: [...],
    tests: [...],
    compilers: {
      '**/*.js': wallaby.compilers.babel(babelConfig)
    }
  };
};

```

**Comment by okonet** [comment]
Sure this work around will work but it would be cool if wallaby could read this file.

**Comment by ArtemGovorov** [comment]
Agree, we can implement that for both `.babelrc` and `package.json`.

**Comment by epsitec** [comment]
I agree with @okonet that automatically picking up defaults from `.babelrc` would be a step forward.

**Comment by yaroslavya** [comment]
What do I need to switch to babel6?
 just add `var babel = require('babel-core');`, instead of `var babel = require('babel');` ?
I have a babelrc settings that are working fine. Do I need to change anything else?

**Comment by ArtemGovorov** [comment]
@yaroslavya Yes, you need just the babel-core change:
``` JavaScript
var babel = require('babel-core');

var babelConfig = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, '.babelrc')));
babelConfig.babel = babel;
```

**Comment by okonet** [comment]
@ArtemGovorov this one is an old one and I feel it doesn't get enough attention. My main concern is still bootstrapping and configuring wallaby for the first time. As it was released I've spent _a lot_ of time to get it working. I think you should invest into a zero config setup (i.e. use existing configs from mocha, jasmin, jest etc.). 

PS I know it's an offtopic and should be a separate issue I guess.

**Comment by ArtemGovorov** [comment]
@okonet It's really true and I have been planning it for while. I'm planing to create an open source node package that will make it easier to bootstrap typical scenarios and would allow to reduce the boilerplate code. Still thinking about the API, your input is welcome, perhaps something like:

``` JavaScript
var config = require('wallaby-enhanced-config')
// will load babelrc, add webpack postprocessor, etc.
module.exports = wallaby => config.babel().webpack({...})({
  files: [...],
  tests: [...]
});
```

The change can be totally separated from the core and live in a separate OSS module. Your thoughts?

**Comment by okonet** [comment]
Should we move this discussion to a separate issue?

**Comment by ArtemGovorov** [comment]
@okonet  Done https://github.com/wallabyjs/public/issues/408

**Comment by ArtemGovorov** [comment]
In the latest core v1.0.17 `.babelrc` file is automatically loaded (and a few versions back we have implemented automatic local version lookup), so now, if you have a `.babelrc` file, your compilers section may look like:

```
```

**Comment by ArtemGovorov** [comment]
So no need to `var babel = require('babel');` anywhere in your wallaby config file (unless you're using it elsewhere).

**Comment by okonet** [comment]
Doesn't look like it's working with babel@5.x

```
Failed to run compilers on js/utils/__tests__/hashCode.spec.js, ReferenceError: [BABEL] js/utils/__tests__/hashCode.spec.js: Unknown option: /Users/okonet/Projects/adverity/web-app/.babelrc.stage
```

**Comment by ArtemGovorov** [comment]
@okonet Works for me with babel@5.8.35 (have also tested a few versions back), here is the simplest repo https://github.com/wallabyjs/babel5-babelrc.

Maybe you have babel-core@6.x installed in your project as well? It looks like an error message from babel-core 6. Wallaby resolves babel version to use like this: first checks if there's `babel-core` module (if there is, tires to use it), then checks if there's `babel` module. If that's the case, you may still need to pass babel 5 instance (`.babelrc` should still be loaded automatically):
```
compilers: {
      '**/*.js': wallaby.compilers.babel({ babel: require(...whereever your babel 5 is..) }),
    }
```
