### ISSUE TITLE
wallaby testing react + styled-components

### ISSUE THREAD

**Issue by matchatype** [wallabyjs/public#2082]
### Issue description or question
Wallaby is configured and running just fine, but it seems to have issues with styled component props. Have this simple React component below and it returns the following error: `TypeError: Cannot read property 'lg' of undefined`. Same for all other styled-components props. Clearly the component renders just fine. Only Wallaby tests won't pass.

```js
import * as PropTypes from "prop-types"
import React from "react"
import styled from "styled-components"

const Styled = styled.div`
  display: flex;
  flex-direction: column;
  max-width: ${({ theme }) => theme.breakpoints.lg};
  margin-left: auto;
  margin-right: auto;
  padding: ${({ theme }) => theme.fontSizes.small};
`

const Footer = ({ siteTitle }) => (
    <Styled>
      {siteTitle} &ndash; © {new Date().getFullYear()}. All Rights Reserved.
    </Styled>
)

Footer.propTypes = {
  siteTitle: PropTypes.string,
}

Footer.defaultProps = {
  siteTitle: ``,
}

export default Footer

```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ["src/**/*.js?(x)", "!src/**/*.spec.js?(x)"],

    tests: ["src/**/*.spec.js?(x)"],

    env: {
      type: "node",
      runner: "node",
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel(),
    },

    testFramework: "jest",

    debug: true,
  }
}
```

### Code editor or IDE name and version

WebStorm 2019.1.2

### OS name and version

OSX

**Comment by matchatype** [comment]
I guess the issue is that styled-component's theme object is not ready right away. So far I found two possibilities to make tests pass: async/await or an elvis operator:

```js
import * as PropTypes from "prop-types"
import React from "react"
import styled from "styled-components"

const Container = styled.div`
  display: flex;
  flex-direction: column;
  max-width: ${({ theme }) => theme?.breakpoints?.lg};
  margin-left: auto;
  margin-right: auto;
  padding: ${async ({ theme }) => await theme.fontSizes.small};
`

const Footer = ({ siteTitle }) => (
  <footer>
    <Container>
      {siteTitle} &ndash; © {new Date().getFullYear()}. All Rights Reserved.
    </Container>
  </footer>
)

Footer.propTypes = {
  siteTitle: PropTypes.string,
}

Footer.defaultProps = {
  siteTitle: `Little Robot Friends`,
}

export default Footer
```

However, I wish I could avoid tweaking code just to make tests pass. Is there a way to address the issue through wallaby config itself?

**Comment by smcenlly** [comment]
Unfortunately we're not familiar with `styled-components` but if you can provide us with a sample repo that uses it, we'd be happy to take a look for you and let you know the best way to configure wallaby or how to restructure your tests.

Can you confirm that your tests are working when you use `jest` from the command line? If not, please get your tests passing in jest first and you may find that wallaby will then work.

**Comment by matchatype** [comment]
Many thanks @smcenlly Here is a demo: https://github.com/matchatype/wallaby-styled-component

It's a simple create-react-app starter with the only addition of styled-components to it. I did set up everything using WebStorm and I added my .idea folder to git. You should be able to find the exact configurations for jest (working) and wallaby (exhibiting the issue). Wallaby configuration is copied from the documentation.

Here is the Footer component in which I reproduced the issue:

```js
import React from "react";
import styled from "styled-components";

const StyledFooter = styled.footer`
  display: flex;
  flex-direction: column;
  max-width: ${({ theme }) =>
    console.log(theme.breakpoints.lg) || theme.breakpoints.lg};
  margin-left: auto;
  margin-right: auto;
  padding: ${({ theme }) => theme.fontSizes.small};
`;

const Footer = ({ siteTitle }) => (
  <StyledFooter>
    {siteTitle} &ndash; © {new Date().getFullYear()}. All Rights Reserved.
  </StyledFooter>
);

export default Footer;
```

According to [styled-components' documentation](https://www.styled-components.com/docs/basics#adapting-based-on-props) it should be cool to pull the theme object from within the styled component as I did (check the max-width CSS rule for example). And work it does: if you run npm start you'll see in the console the computed value displays correctly.

However, wallaby is not ok with that, unless you make it return a promise, like this:

```
 max-width: ${async ({ theme }) => theme.breakpoints.lg};
```

Then it will work (of course you have to the same for padding).

**Comment by smcenlly** [comment]
Thanks for the demo. On my machine I get the same error when I use the `jest` run configuration. I also get the same error when using `npm run test`. Could you please try cloning to a new directory and confirming everything is working for you?

In the meantime, I'll keep digging around for a little while longer to try get it working in jest.

![image](https://user-images.githubusercontent.com/2074089/58219406-12edb480-7d4e-11e9-9f94-8f5baf5531f6.png)

![image](https://user-images.githubusercontent.com/2074089/58219419-1f720d00-7d4e-11e9-8603-a6589e85f28e.png)

**Comment by matchatype** [comment]
Unfortunately, I think you are correct, I'm sorry.

I was looking at the following and thought everything was alright
<img width="1315" alt="CleanShot 2019-05-22 at 21 35 24@2x" src="https://user-images.githubusercontent.com/28128/58219647-aa64f000-7cd9-11e9-9f49-6bb40a37966a.png">

However, by taking a better look I can see the same
<img width="1328" alt="CleanShot 2019-05-22 at 21 35 31@2x" src="https://user-images.githubusercontent.com/28128/58219753-0465b580-7cda-11e9-8fc4-c6463c5e9a65.png">

Not that I could figure out why though...

**Comment by smcenlly** [comment]
I've figured out what you need to do. Your footer tests are running fine but your app tests are failing.

I have updated your `test` file (`App.test.js`) and everything is now working. This is what I did:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import theme from './theme';
import { ThemeProvider } from "styled-components";

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<ThemeProvider theme={theme}><App /></ThemeProvider>, div);
  ReactDOM.unmountComponentAtNode(div);
});
```
