### ISSUE TITLE
Tests are not run

### ISSUE THREAD

**Issue by olaven** [wallabyjs/public#2086]
### Issue description or question
I have configured wallaby in a project. My tests are written in Typescript.
I initially configured jest with [ts-jest](https://github.com/kulshekhar/ts-jest). 
The config is detected, but the test-console says: `0 failing tests, 0 passing`. 

The test-files are found, ad this is logged in debug-console and the "indicators" are visible in the sidebar. They are just always white(not run).

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'src/**/*.ts', load: false}, 
            "tsconfig.json"
        ],

        tests: [
            {pattern: 'test/**/*.test.ts', load: false}
        ], 

        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        debug: true,
    };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.34

### OS name and version
OSX Mojave

Thank you for this amazing product! I have used it in the past and I cannot wait to get it working! 😄 👏 

Olav

**Comment by smcenlly** [comment]
Is `jest` configured in your `package.json`? If so, please try the configuration below. I've added `package.json` to your files list and added a `setup` function to remove the `jest` `transform` section of your configuration. 

If that doesn't work for you, please provide us with a sample repo of your project, we'd be happy to take a look (it doesn't need to have any of your code, just a simple code/test file).

```
module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'src/**/*.ts', load: false}, 
            "tsconfig.json",
            'package.json'
        ],

        tests: [
            {pattern: 'test/**/*.test.ts', load: false}
        ], 

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',

        debug: true,

        setup: function (wallaby) {
           var jestConfig = require('./package.json').jest;
           delete jestConfig.transform;
           wallaby.testFramework.configure(jestConfig);
        }
    };
};
```

If your jest configuration

**Comment by ArtemGovorov** [comment]
This should help:
```diff
     tests: [
-            {pattern: 'test/**/*.test.ts', load: false}
+            {pattern: 'test/**/*.test.ts'}
        ], 
```

**Comment by olaven** [comment]
Thank you! This, along with some extra project-specific config, fixed the issue for me 😄 🌤
