### ISSUE TITLE
dynamic imports with next.js and jest not working

### ISSUE THREAD

**Issue by mattruby** [wallabyjs/public#2088]
### Issue description or question
Next.js next/babel is not working with Wallaby.  dynamic imports are failing in wallaby, but working well in Jest.  

Here's a small demo repo: https://github.com/mattruby/wallaby_next_demo

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ["**/*.js", "!**/*.test.js", "!/node_modules/*"],

    tests: ["**/*.test.js","!/node_modules/*"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },

    testFramework: "jest",

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.34

### OS name and version
OSX Mojave 10.14.5

**Comment by smcenlly** [comment]
Thanks for the sample repo. I took a look at what the `.babelrc` `next/babel` preset was doing and followed through to `node_modules\next\dist\build\babel\preset.js`. I saw that it has different logic based on the process.env.NODE_ENV setting.

I got everything working in your sample repo by adding `process.env.NODE_ENV = 'test';` to the top of your `wallaby.js` configuration file:

```diff
module.exports = function(wallaby) {
+ process.env.NODE_ENV = 'test';

  return {
    files: [
      "**/*.js",
      "!**/*.test.js",
      "!/node_modules/*"
    ],

    tests: ["**/*.test.js","!/node_modules/*"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },
    testFramework: "jest",

    debug: true
  };
};
```

**Comment by mattruby** [comment]
Thanks!
