### ISSUE TITLE
Exclude code from inline indicators in webstorm ?

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#2094]
### Issue description or question

Inside my code, wallaby is highlighting a utility method, I was wondering if i can disable it with a comment or something like ts-ignore does for tslint :-)

This probably explains it

![image](https://user-images.githubusercontent.com/2370364/58759826-75099f00-8530-11e9-96f1-669f3a804dea.png)

createTestingModule is an internal method that will be called a number of times, to keep me DRY inside tests.

### Code editor or IDE name and version

WebStorm v2019.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Yes, there's a setting for it. You may use a [special comment](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) configured in your Wallaby config file to suppress code coverage:

```js
module.exports = function () {

    return {
      ...
      hints: {
        allowIgnoringCoverageInTests: true,
        ignoreCoverage: /ignore coverage/
      },
    };
  };
``` 

Then in your file you may add the `// ignore coverage` comment above or inside the function.

**Comment by appsolutegeek** [comment]
@ArtemGovorov Nice! - works great!
