### ISSUE TITLE
Wallaby - Hoisting jest.mock not working (ts-jest, typescript) ?

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#2095]
### Issue description or question
Hi,

I found this https://github.com/wallabyjs/public/issues/2039

I am trying to get jest working with hosting the jest.mock automatically because right now i need to place them at the very top of each file.

If i place the mock at the top of the file it passes but if i place it at the bottom near my test, it fails.

```
jest.mock("../../src/lib/logger")
```

I npm installed 2 additional components as per the config below

```
@babel/core
babel-preset-jest
```

Its probably me, but I don't know what I am doing wrong.

If I can provide additional info then please let me know.

### Wallaby.js configuration file

```javascript
const { lstatSync, readdirSync, existsSync } = require("fs")
const { join, delimiter } = require("path")

module.exports = function(wallaby) {
  /*** Start for processing multiple node_modules (mono repo) ***/
  const isDirectory = source => lstatSync(source).isDirectory()

  const getDirectories = source =>
    readdirSync(source)
      .map(name => join(source, name))
      .filter(isDirectory)
      .filter(source => existsSync(join(source, "node_modules")))

  const nodeModuleDirs = [...getDirectories(join(__dirname, "apps")), ...getDirectories(join(__dirname, "libs"))]

  for (const dir of nodeModuleDirs) {
    process.env.NODE_PATH += delimiter + join(dir, "node_modules")
  }
  /*** End for processing multiple node_modules (mono repo) ***/

  return {
    files: [
      "jest.config.js",
      "libs/**/src/**/*.ts",
      { pattern: "libs/**/test/__test/**/*.ts", instrument: false, load: true, ignore: false },
      "!libs/**/src/**/*.spec.ts",
      "!**/node_modules/**/*",
      "!**/dist/**/*"
    ],

    tests: ["libs/**/test/**/*.spec.ts", "libs/**/src/**/*.spec.ts", "!**/node_modules/**/*", "!**/dist/**/*"],

    compilers: {
      "**/*.ts?(x)": wallaby.compilers.typeScript({ isolatedModules: true })
    },

    setup: function(wallaby) {
      const jestConfig = require("./jest.config")
      delete jestConfig.transform
      wallaby.testFramework.configure(jestConfig)
    },

    preprocessors: {
      "**/*.js?(x)": file =>
        require("@babel/core").transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require("babel-preset-jest")]
        })
    },

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest",

    debug: false
  }
}

```

### Code editor or IDE name and version

WebStorm v2019.1

### OS name and version

OSX

**Comment by smcenlly** [comment]
We have identified the cause of your problem, which is a slight difference in behavior when using the TypeScript `Isolated Modules` compiler setting.

Preprocessor file patterns behave differently when using the Isolated Modules compiler setting. Any preprocessor file patterns must match on the .ts or .tsx file extension (this is in contrast to using .js or .jsx when not using Isolated Modules). We've updated our docs to reflect this note.

This means that to hoist your jest mocks, your config file will look like this:

```diff
const { lstatSync, readdirSync, existsSync } = require("fs")
const { join, delimiter } = require("path")

module.exports = function(wallaby) {
  /*** Start for processing multiple node_modules (mono repo) ***/
  const isDirectory = source => lstatSync(source).isDirectory()

  const getDirectories = source =>
    readdirSync(source)
      .map(name => join(source, name))
      .filter(isDirectory)
      .filter(source => existsSync(join(source, "node_modules")))

  const nodeModuleDirs = [...getDirectories(join(__dirname, "apps")), ...getDirectories(join(__dirname, "libs"))]

  for (const dir of nodeModuleDirs) {
    process.env.NODE_PATH += delimiter + join(dir, "node_modules")
  }
  /*** End for processing multiple node_modules (mono repo) ***/

  return {
    files: [
      "jest.config.js",
      "libs/**/src/**/*.ts",
      { pattern: "libs/**/test/__test/**/*.ts", instrument: false, load: true, ignore: false },
      "!libs/**/src/**/*.spec.ts",
      "!**/node_modules/**/*",
      "!**/dist/**/*"
    ],

    tests: ["libs/**/test/**/*.spec.ts", "libs/**/src/**/*.spec.ts", "!**/node_modules/**/*", "!**/dist/**/*"],

    compilers: {
      "**/*.ts?(x)": wallaby.compilers.typeScript({ isolatedModules: true })
    },

    setup: function(wallaby) {
      const jestConfig = require("./jest.config")
      delete jestConfig.transform
      wallaby.testFramework.configure(jestConfig)
    },

    preprocessors: {
-     "**/*.js?(x)": file =>
+     "**/*.ts?(x)": file =>
        require("@babel/core").transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require("babel-preset-jest")]
        })
    },

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest",

    debug: false
  }
}
```

**Comment by appsolutegeek** [comment]
@smcenlly Thanks, i am almost there :-) There is an error now about experimental decorators.. I can confirm that i have them enabled in my tsconfig.

```
Failed to run preprocessors on libs/nest-correlation/test/__test/app.controller.ts, SyntaxError: /Users/ian/Development/Work/fortris/vault-projects/nest-common/libs/nest-correlation/test/__test/app.controller.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (5:1):

  3 | import { Request } from "express"
  4 | 
> 5 | @Controller()
    | ^
```

I presume that wallaby looks for the tsconfig in the root where it is. My code works, its just the tests do not .. here is the tsconfig

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "strict": true,
    "declaration": false,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2018",
    "module": "commonjs",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
    }
  },
  "exclude": ["node_modules", "tmp"]
}

```

**Comment by appsolutegeek** [comment]
These are the standard decorators available in typescript, that are enabled by setting..

```
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
```

**Comment by smcenlly** [comment]
We can see that the problem is caused by your files configuration. In your files configuration, you're excluding `libs/nest-correlation/test/__test/app.controller.ts` from being instrumented (compiled and preprocessed) because of this line in your `files` configuration:

```
      { pattern: "libs/**/test/__test/**/*.ts", instrument: false, load: true, ignore: false },
```

I'm not sure why you've excluded this pattern? If it's because you don't want the file to be included in your instrumentation but the file needs to be compiled, then you can use the `filesWithNoCoverageCalculated` setting (see more in our [docs](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file)).

Without a sample repo, we can't determine the exact `files` and `tests` patterns to provide, but something like what I've provided below should work for you:

```
...
    files: [
      "jest.config.js",
      "libs/**/*.ts",
      "!libs/**/*.spec.ts",
      "!**/node_modules/**/*",
      "!**/dist/**/*"
    ],

    tests: ["libs/**/*.spec.ts", "!**/node_modules/**/*", "!**/dist/**/*"],
...
```

This will compile and process all `.ts` file but only run the tests for files ending in `.spec.ts`.'

If you're still having problems, please share a sample repo with us, we'd be happy to take a look at it for you.

**Comment by appsolutegeek** [comment]
Thanks ! that seems to work now ... but I don't think the jest.mock is getting hoisted still..., i get the error

```
	Matcher error: received value must be a mock or spy function
	
	Received has type:  function
	Received has value: [Function Logger]
```

```
       // placing this in the "it" method
       jest.mock("../../src/lib/logger")

       // Act
      const logger = service.getLogger({ category })

      // Assert
      expect(Logger).toBeCalledWith(category)
```

placing the 

```
jest.mock("../../src/lib/logger")
```


at the top of the file, works again...

So leaving it in the "it" of the "describe" causes the above error but placing it as the first line before the import statements then all is well with my test.

**Comment by appsolutegeek** [comment]
The above error is erroring on this line

```
     // Assert
      expect(Logger).toBeCalledWith(category)
```

It doesn't recognize the Logger as a mock but placing it as the first statement above imporrts - then it does..

**Comment by ArtemGovorov** [comment]
>   // placing this in the "it" method
>   jest.mock("../../src/lib/logger")

> but I don't think the jest.mock is getting hoisted still

It looks like the result you are getting is expected, because it is [how Jest works](https://github.com/facebook/jest/issues/2582#issuecomment-284452585) - it hoists `jest.mock` within the current block scope. 

So if you have `jest.mock` call anywhere in the program scope of the file, the statement will be hoisted to be the first statement of the scope; if you have `jest.mock` call anywhere in a function, the statement will be hoisted to be the first statement of the function. Check out the referenced Jest issue for some ideas how to make Jest work for your case.
