### ISSUE TITLE
Update snapshot from WallabyApp does not work

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#2096]
Issue Type: <b>Bug</b>

Clicking the update snapshot button in the WallabyApp is having no effect ...

wallaby.js looks like this -- 
```
module.exports = function() {
  return {
    files: ["**/*", "!src/**/*.test.ts", "!lib/**/*", "!node_modules/**/*"],

    tests: ["src/**/*.test.ts"],

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest"
  };
};
```

My project uses dynamically generated test cases by iterating over a list of sample data and producing one test for each element in array -- not sure if that is part of the issue ...?

Extension version: 1.0.128
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:22.738Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.34GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by NikGovorov** [comment]
Hi @breathe,

I think the only way to reproduce the issue is to have non-unique tests names, that in your scenario probably is the case.

Could you please check that your code that generates tests assigns unique test names? If it does not you should add something like this:

```javascript
describe('component', () => {
  for (let i = 0; i < 100; i++) {
    it(`should be rendered correctly for ${i}`, () => {
    }); 
  }
});
```

Thanks.
