### ISSUE TITLE
Babel transpile issue using amd to commonjs plugin

### ISSUE THREAD

**Issue by devghost** [wallabyjs/public#2098]
### Issue description or question
I have setup testing for our app using Jest. It work nicely. I am now trying to setup Wallaby to run these tests. There are mainly two categories of tests, new and legacy. The new ones run perfectly fine in Wallaby but the legacy one does not. The legacy tests test an older part of the system using RequireJS and are written in Mocha.

We're using a babel plugin called "transform-amd-to-commonjs" to convert the RequireJS portion of the code to CommonJS. Works flawlessly in Jest but Wallaby has troubles with this and I keep getting the error "define is not defined" located in an external Javascript file (Durandal). Which to me seem to indicate that Babel does not transpile the code properly in the Wallaby project cache. But I am not able to find out what is wrong with my config.

```
ReferenceError: define is not defined 
  at Object.define ​src/assets/durandal/events.js:15​
```

Folder structure
```
src
  app
  assets    <-- Durandal is in here
  core
tests
```

### Wallaby.js configuration file

```javascript
const environment = "test";

process.env.BABEL_ENV = environment;
process.env.NODE_ENV = environment;

module.exports = function (wallaby) {
    return {
        files: [
            // Vendor files..
            {pattern: "src/assets/**/*.json", instrument: false, load: false},
            {pattern: "src/assets/**/*.json", instrument: false, load: false},
            {pattern: "src/assets/**/*.js", instrument: false, load: true},

            // APP...
            {pattern: "src/core/**/*.js", load: false},
            {pattern: "src/app/**/*.js", load: false},

            // Test/Helper stuff...
            {pattern: "__mocks__/*.*", load: false},
            {pattern: "tests/all.js", load: false},
            {pattern: "tests/customQAlwaysUsesSetTimeout.js", load: false},
            {pattern: "tests/helpers/**/*.js", load: false},
            {pattern: "tests/config/setup-jest.js", load: false},
            {pattern: "tests/config/react-testing-library.setup.js", load: false},
            {pattern: "tests/config/htmlLoader.js", load: false},
            {pattern: "jest.config.js", load: false}
        ],

        tests: [
            "tests/unit/**/*.jest.test.js",
            "tests/unit/**/*.spec.js", // <== TODO These won't work in Wallaby
            "!tests/unit/widgets/visualizationLineVsTime/viewModel.spec.js",
            "!tests/unit/core/components/expressions/timeseriesUtils.spec.js",
            "!tests/unit/core/services/unitOfWork.spec.js"
        ],

        env: {
            type: "node",
            runner: "node",
            params: {
                env: `NODE_ENV=${environment}`
            }
        },

        compilers: {
            "**/*.js*": wallaby.compilers.babel({
                presets: ["@babel/preset-env","@babel/preset-react"],
                plugins: [
                    "@babel/plugin-proposal-object-rest-spread",
                    ["transform-amd-to-commonjs", { restrictToTopLevelDefine: true }],
                    "@babel/plugin-proposal-class-properties",
                    "@babel/plugin-syntax-dynamic-import",
                ],
                ignore: [
                    "./src/assets/cldr"
                ]
            })
        },

        bootstrap: function () {
            const conf = require("./jest.config.js");
            Object.keys(conf.moduleNameMapper).forEach(function (key) {
                conf.moduleNameMapper[key] = conf.moduleNameMapper[key].replace("<rootDir>", wallaby.projectCacheDir);
            });

            wallaby.testFramework.configure(conf);
        },

        debug: true,
        testFramework: "jest"
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.34.0

### OS name and version

Windows_NT x64 10.0.17134

**Comment by smcenlly** [comment]
We're going to need a little more information to be able to help. We need to see your jest configuration, package configuration and a sample of one of the tests that is failing. **Could you please send us a sample repo?**

**Comment by ArtemGovorov** [comment]
We can see that the problem is caused by your files configuration. In your files configuration, you're excluding `src/assets/**/*.js` from being instrumented (compiled and preprocessed) because of this line in your `files` configuration:

```
{pattern: "src/assets/**/*.js", instrument: false, load: true},
```

I'm not sure why you've excluded this pattern? If it's because you don't want the file to be included in your instrumentation but the file needs to be compiled, then you can use the `filesWithNoCoverageCalculated` setting (see more in our [docs](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file)).
