### ISSUE TITLE
Wallaby errors while starting

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#2099]
### Issue description or question
I am unable to get wallaby to start. Different errors are thrown randomly and am unsure why.

Examples (there are more):
- `Failed to run preprocessors on package.json, TypeError: Cannot read property 'length' of undefined`
- `Failed to run preprocessors on .prettierrc.js, TypeError: Cannot read property 'length' of undefined`
- `Failed to run preprocessors on .backtrack-stats.json, TypeError: Cannot read property 'length' of undefined`
-  `Cannot read property 'sections' of undefined`

Sometimes it throws something about "sections".

Example repo: https://github.com/chrisblossom/issues/tree/wallaby-issue-2099

### Code editor or IDE name and version

```
WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
```

### OS name and version

`macOS 10.14.5`

**Comment by smcenlly** [comment]
Can you please explain what these lines do in your configuration file?

```
const { Backtrack } = require('@backtrack/core');

// uncommenting this line removes errors
const { configManager } = new Backtrack();
```

It seems that they are unnecessary, and removing them fixes the problem.

Within these files are you replacing "require" or some other core node.js functions (e.g. `path`, `fs`)?

It looks like this library is messing with some core nodejs runtime elements which then results in some very strange wallaby.js behavior. For example, if I look at the instrumented project directory (i.e. `~/Library/Caches/<PRODUCT><VERSION>/wallaby/projects/<FOLDER WITH MOST RECENT MODIFIED DATE>`), the content of all of my files is simply `undefined`.

We will keep investigating the issue, but would appreciate a bit more context into what's going on in this library and why it's required.

**Comment by chrisblossom** [comment]
> Within these files are you replacing "require" or some other core node.js functions (e.g. path, fs)?

No.

> We will keep investigating the issue, but would appreciate a bit more context into what's going on in this library and why it's required.

[@backtrack/core](https://github.com/chrisblossom/backtrack) is an extendable task runner / file manager / configuration manager I wrote. I can't imagine any node internals being modified (unless `@babel/preset-env` is changing them via `core-js@3`).

With the configuration I provided it is not necessary, but it is for the rest of my projects. When I open an issue here I try and provide a bare minimal repository to minimize your debug time.

**Comment by ArtemGovorov** [comment]
We have identified the issue. The `nodemon` module is being loaded as a dependency of the `@backtrack/core`, and the module is interrupting Wallaby processor pool work.

If possible, I'd add a setting not to load the module from `@backtrack/core` when in Wallaby context (can't see why you'd need it in Wallaby context), otherwise this should help:

```diff
...
+require('nodemon/lib/utils/bus').emit = () => {};

const { Backtrack } = require('@backtrack/core');

// uncommenting this line removes errors
const { configManager } = new Backtrack();
```

**Comment by chrisblossom** [comment]
Sorry, I had no idea requiring nodemon started the nodemon process. This was very unexpected and seems to me like a terrible API design. Thanks for tracking that down (although I have no idea how you did)! I appreciate it! 

https://github.com/chrisblossom/backtrack-preset-node/commit/e378d484ffd78fc8fb15d9e50825860471b48544
