### ISSUE TITLE
Support jasmine for node.js/io.js

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#21]

**Comment by dsibiski** [comment]
+1

I have a project that is pure Javascript (Node/IO) which doesn't load in the browser, I'm getting "expect is not defined" when trying to run Wallaby. I'm hoping that this will resolve that problem.

Thanks for such an amazing tool, this just blew my mind when I learned about it. :)

**Comment by ArtemGovorov** [comment]
@dsibiski wallaby.js by default is using mocha for node.js, you may for now install and use https://github.com/Automattic/expect.js or http://chaijs.com/ with expect style. Have a look into this sample - https://github.com/wallabyjs/wallaby-node-iojs-sample/

**Comment by Sanjo** [comment]
:+1: For Jasmine node.js support. http://jasmine.github.io/2.3/node.html

**Comment by daw451-duplicate** [comment]
+1

**Comment by mutantcornholio** [comment]
+1

**Comment by psyduckinattack** [comment]
:+1: I will be so happy!

**Comment by ArtemGovorov** [comment]
Shipped in core v1.0.139.

  ```javascript
  module.exports = function (wallaby) {
    return {
      files: [
        ...
      ],

      tests: [
        ...
      ],

      env: {
        type: 'node'
      },

      ...

      testFramework: 'jasmine'
    };
  };
  ```

**Comment by psyduckinattack** [comment]
@ArtemGovorov, when it will be possible to download and try this feature in Intellij Idea package?

**Comment by ArtemGovorov** [comment]
It's been supported in IntelliJ (as well as other editors that we support) since the issue was closed. If you don't have it installed, you may download the latest plugin for IntelliJ IDEA [from our website](http://wallabyjs.com/#download).

**Comment by psyduckinattack** [comment]
I downloaded the latest version (`wallaby-intellij-v1.0.46`) from website, but wallaby console shows me an error:
```
wallaby.js started
core v1.0.138
Failed to load configuration file:  Test framework [jasmine] is not supported
```
As I see, it is not the version that is expected (1.0.139).

**Comment by ArtemGovorov** [comment]
The latest IntelliJ plugin version is 1.0.46, however the latest wallaby core version is 1.0.157, it looks like your wallaby.js core hasn't been updated for a while. When was the last time you used wallaby.js? Try closing all instances of your IDE, starting it back and starting wallaby.js, it should update the core automatically. If the update doesn't happen, please attach the latest entries from your idea.log file (menu Help - Show Log).

**Comment by ArtemGovorov** [comment]
@psyduckinattack Also, do you have a valid license? If don't and your trial period has expired, wallaby.js stops the updates until you purchase a license.

**Comment by psyduckinattack** [comment]
> Also, do you have a valid license? If don't and your trial period has expired, wallaby.js stops the updates until you purchase a license.

No, i have only a trial license to try to work with jasmine and now it explains a lot :smile:

**Comment by ArtemGovorov** [comment]
@psyduckinattack Send me an email to wallabyjs@gmail.com and I'll extend your trial license so you could try the feature before considering purchasing a license.
