### ISSUE TITLE
node_modules in subdirectory?

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#210]
Reproduction steps:

* https://github.com/fixin-platform/backend-swf/commit/a5e2d2a2955cbf04537fd056512e291150fd63f8
* `git submodule update --remote --init --recursive`
* Put https://gist.github.com/DenisGorbachev/ca8cc97b1abd093a67e4 in `settings/dev.json`
* Run tests.

Results:

* mocha works
* Wallaby doesn't work (`Error: Cannot find module 'object-path'`)

That's because Wallaby only uses the top-level node_modules, while ignoring all node_modules (both top-level and inside `core/`).

In theory, I could install "core" as npm package itself. However, I'd like to keep it as git submodule, because I develop core along with the main package.

Is it possible to utilize all node_modules, not just top-level ones?

**Comment by ArtemGovorov** [comment]
It is possible, you may just give wallaby a hint where to look for node modules:

``` JavaScript
module.exports = function(wallaby) {
  process.env.NODE_PATH = 
    require('path').join(wallaby.localProjectDir, 'core', 'node_modules');
  ...
}
```

I understand it's not perfect and it'd be better if it would just work as in mocha (actually mocha with code coverage solution should fail for the same reason, as it also has its own cache of instrumented files where it will not copy nested node modules, unless instructed to do so). So as opposed to mocha that is using a local folder, wallaby is using its own cache and doesn't copy node modules there, so needs a hint where to find node modules. Top level modules are automatically handled, but modules in subfolders may need scanning to find them, which will be a bit less performant than the proposed solution with `NODE_PATH`.

P.S You may consider adding `!core/node_modules/**` to your files list, right now all coffee script files from the node modules are copied to the wallaby cache.

**Comment by DenisGorbachev** [comment]
Thanks for the tips, it works!

Here's my final wallaby.js: https://gist.github.com/DenisGorbachev/c370efdee4acec46b83e

**Comment by DenisGorbachev** [comment]
By the way, maybe it would be better to update the docs with these instructions?

Plus, a micro-pull-request:
```
- process.env.NODE_PATH = require('path').join(wallaby.localProjectDir, 'core', 'node_modules');
+ process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'core', 'node_modules');
```

**Comment by ArtemGovorov** [comment]
@DenisGorbachev Thanks, added [the doco section](http://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder).

**Comment by DinisCruz** [comment]
that worked really well, I'm still in early stages of integrating wallaby on my project so my wallaby.js is still quite simple:

```
module.exports = function (wallaby) {
  process.env.NODE_PATH = require('path').join(wallaby.localProjectDir, 'TM_Website', 'node_modules');

  //console.dir(wallaby)

  return {
    files: [
      "TM_Website/src/**/*.coffee",
      "TM_Jade/**/*.jade"
    ],

    tests: [
      "TM_Website/test/**/*.coffee"
    ],

    env: {
      type: 'node',
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
@DenisGorbachev quick note on using `':' + require('path').join...`, I have corrected the example in docs to make it cross-platform:
``` JavaScript
process.env.NODE_PATH += path.delimiter 
  + path.join(wallaby.localProjectDir, 'core', 'node_modules');
```

**Comment by DenisGorbachev** [comment]
Ah, totally forgot about Windows :) Thanks!

**Comment by szarouski** [comment]
Probably silly question, but how `wallaby` should be defined?

**Comment by ArtemGovorov** [comment]
@szarouski `wallaby` in context of this issue is a parameter passed to the main configuration function of your wallaby config:
```
module.exports = function(wallaby) { ...
```
Does it answer your question? If not, could you please clarify a bit what do you mean by defined?

**Comment by szarouski** [comment]
Yes, that is it. Thanks Artem.
