### ISSUE TITLE
Live comment outputs (/*?*/) not showing in WallabyjsApp when test case fails

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#2100]
### Issue description or question
I have some testcases that run some shared code with different arguments and then make some assertions which fail.  

Prior to making the assertions I invoke code on the shared path and that path includes some live comment output.

For the test cases which succeed (pass assertions) I see the live comments in WallabyjsApp -- for those that fail I do not.  

How can I see the live comment values associated with the failing test case path in WallabyApp?

Thanks!!

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: ["**/*", "!src/**/*.test.ts", "!lib/**/*", "!node_modules/**/*"],

    tests: ["src/**/*.test.ts"],

    env: {
      type: "node",
      runner: "node"
    },

    testFramework: "jest"
  };
};
```

### Code editor or IDE name and version
Visual Studio Code Version 1.34.0 (1.34.0)

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Could you please provide some (pseudo)code and screenshots to demonstrate the issue?

**Comment by smcenlly** [comment]
Closing this issue as it's been over a month since we requested some additional info. Let us know if you're still experiencing the problem and we'll re-open the issue.
