### ISSUE TITLE
Wallaby won't run on a fresh install

### ISSUE THREAD

**Issue by syntax-error** [wallabyjs/public#2102]
I've just been given a new MacBook at work and been in the process of setting up my environments again. 

I typically use PHPStorm, and I'm used to WallabyJS being essentially being plug-and-play. However, when I start wallaby, I get the error `Cannot find module 'chrome-launcher'`.

I have tried installing said module locally and globally. I have tried using wallaby in VSCode. I have tried making the most minimal standalone project. I still get the same error.

I'm at a loss as to what is causing this issue, and how to solve it.

### Full error

```
Failed to set up project file system: Error: Cannot find module 'chrome-launcher'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            'src/**/*.js'
        ],

        tests: [
            'test/**/*.spec.js'
        ],

        env: {
            kind: 'chrome'
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.35.0
PHPStorm v2019.1.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. There's been an issue with our build process causing one the required build artefacts go missing. The issue is fixed and the fix is published in [the latest Wallaby core v1.0.695](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
