### ISSUE TITLE
Using Headless Chrome Driver

### ISSUE THREAD

**Issue by petermierau** [wallabyjs/public#2105]
### Issue description or question
I want to intereact with the headless Chrome instance and I'm not sure how.
Actions:
   Resetting the DOM after each test
   Verifying CSS properties
   Simulating User clicks

I'm using Mocha as the testing framework and Chrome as the driver.

### Wallaby.js configuration file
```
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
    mode: 'development',
    entry: './src/index.js',
    output: {
        filename: 'main.js',
    },
    devtool: 'source-map'
    }
);

module.exports = function (wallaby) {
    return {
        // set `load: false` to all source files and tests processed by webpack
        // (except external files),
        // as they should not be loaded in browser,
        // their wrapped versions will be loaded instead
        files: [
            // {pattern: 'lib/jquery.js', instrument: false},
            {pattern: 'src/**/*.js', load: false}
        ],

        tests: [
            {pattern: 'test/**/*Spec.js', load: false}
        ],

        testFramework: 'mocha',
        env: {
            kind: 'chrome'
        },

        postprocessor: wallabyPostprocessor,ac

        setup: function () {
            // required to trigger test loading
            window.__moduleBundler.loadTests();
        },
        hints: {
            ignoreCoverageForFile: /ignore file coverage/,
            ignoreCoverage : /ignore coverage/
        },
    };
};
```

### Code editor or IDE name and version
WebStorm v2019.1.1

### OS name and version
Linux Fedora 30

**Comment by smcenlly** [comment]
Check out our [`calculator-sample`](https://github.com/wallabyjs/calculator-sample) to see how we are interacting with the `dom` (loading, clicking, etc.) using `jasmine` and headless-chrome. 

During test execution, we interact with the `dom` using `jquery`; you should be able to do the same.

If this doesn't answer your question, can you please tell us about the technologies you're using (e.g. frameworks, etc.) and how you're performing your browser-based tests outside of wallaby? If you can provide us with a sample repo with your browser-based tests working outside of wallaby, we'd be happy to help you with your configuration.
