### ISSUE TITLE
Covered lines are not showing any color at all.

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#2111]
### Issue description or question
Covered lines are not showing any colors
### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            "src/*",
            { pattern: 'babel.config.js', instrument: false },
        ],

        tests: ["tests/*"],

        compilers: {
            "**/*.js": wallaby.compilers.babel()
        },
        env: {
            type: "node",
            runner: "node"
        },
        testFramework: "jest"
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.35.1

### OS name and version
OSX Mac OS Mojave 10.14.5

**Comment by smarigowda** [comment]
<img width="1655" alt="no_color_for_covered_lines" src="https://user-images.githubusercontent.com/1831259/59482323-4b217800-8e60-11e9-9936-01e70505b543.png">

**Comment by smarigowda** [comment]
I was working fine. I see this behaviour since yesterday.

**Comment by ArtemGovorov** [comment]
Please try:
- re-installing Wallaby Extension,
- if it doesn't help, once Wallaby is started (with no covered lines showing), open VS Code Dev Tools and share output from the DevTools Console.

**Comment by smarigowda** [comment]
Uninstalled and re-installed Wallaby js. Same behaviour. See dev tools console logs in attached screenshot. I do not see any errors.

<img width="1615" alt="vs-code-dev-tools-console-log" src="https://user-images.githubusercontent.com/1831259/59484386-7066b400-8e69-11e9-8c18-e60661e38d2f.png">

**Comment by smarigowda** [comment]
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3313 [Extension Host] debugger listening on port 40586
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host]  Quokka.js Live Share integration disabled, VSLS not found.
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4357 Overwriting grammar scope name to file mapping for scope wallaby.output.
Old grammar file: file:///Users/santosh/.vscode/extensions/wallabyjs.quokka-vscode-1.0.227/quokka-output.tmLanguage.json.
New grammar file: file:///Users/santosh/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/wallaby-output.tmLanguage.json
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:4357
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] (node:5214) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
t.log @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] [Wallaby Console] VS Code extension v1.0.128
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] [Wallaby Console] Core v1.0.697

**Comment by ArtemGovorov** [comment]
Can you please 
- open the `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128/images/` and attach the `covered.svg` file content?
- with VS Code DevTool use Select Element and explore the content of the place in the gutter where covered icon is expected:

![trigtests](https://user-images.githubusercontent.com/979966/59484633-e98bf880-8eb5-11e9-87be-1039726c3791.gif)

**Comment by smarigowda** [comment]
![image](https://user-images.githubusercontent.com/1831259/59484986-ef5cec00-8e6b-11e9-8bc6-e795ffaff43d.png)

**Comment by smarigowda** [comment]
covered.svg has 0 bytes (see above screenshot). I will inspect the element and provide the input in a moment.

**Comment by michael-letcher** [comment]
I'm getting no decorations at all.

I've reinstalled with no avail. The only decorations I see are when there is an error in the spec file and it shows Red box, once fixed they all disappear.

![image](https://user-images.githubusercontent.com/4531036/59485124-da0daf00-8eb7-11e9-98a9-63a0a02d04f1.png)
0 bytes

**Comment by ArtemGovorov** [comment]
It looks like the extension installation is corrupted. 

Try this:

- close VS Code,
- delete `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.128` folder, and all `~/.vscode/extensions/wallabyjs.wallaby-vscode-*` folders too.
- open VS Code and install Wallaby extension.

**Comment by smarigowda** [comment]
![image](https://user-images.githubusercontent.com/1831259/59485192-a8bbc180-8e6c-11e9-970c-377b5ad99e7b.png)

**Comment by smarigowda** [comment]
See above screenshot for dev tools inspection.

**Comment by ArtemGovorov** [comment]
@smarigowda Thanks, please try these steps: https://github.com/wallabyjs/public/issues/2111#issuecomment-501971822

**Comment by michael-letcher** [comment]
@ArtemGovorov Worked thanks!

**Comment by smarigowda** [comment]
Worked. Thank you for the support.
