### ISSUE TITLE
Riteway jest support

### ISSUE THREAD

**Issue by allforabit** [wallabyjs/public#2112]
### Issue description or question
https://github.com/janhesters/riteway-jest gives a way to use Eric Elliott's riteway testing technique with jest. Is it possible to configure wallaby to pick up on this or would it need explicit support? I've tried to add the setup module to wallaby's setup function. More info on Eric Eliot's riteway technique can be found here: https://medium.com/javascript-scene/tdd-the-rite-way-53c9b46f45e3

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js?(x)",
      "!src/**/__tests__/*.js?(x)"
    ],
    tests: ["src/**/__tests__/*.js?(x)"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },
    setup: () => {
      require("riteway-jest/assert");
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.?

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby `setup` function doesn't execute in Jest context (Jest creates its own execution contexts). Have you tried [configuring Jest](https://github.com/janhesters/riteway-jest#installation) to use the library as described in their docs?

**Comment by allforabit** [comment]
Yes I did that that. It works when I run it directly from the commandline with the `jest` command. I actually got it closer to working with wallaby by adding this to the test file `import 'riteway-jest/assert';` This gets rid of the warning about `assert` being undefined and everything shows up as working (all green). The only thing that doesn't work is it's not registered as a test so wallaby shows `0 of 0 tests passing`. I am assuming this is because it's not expecting jest to use the `assert` function to run a test.

**Comment by smcenlly** [comment]
Because the riteway-jest library is calling the jest library functions, you need to instruct wallaby to instrument its files the same way that it instruments your app files.

You can do this by adding them to your files pattern (see the updated config below):

```diff
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js?(x)",
      "!src/**/__tests__/*.js?(x)",
+     "node_modules/riteway-jest/**/*.js"
    ],
    tests: ["src/**/__tests__/*.js?(x)"],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },
    setup: () => {
      require("riteway-jest/assert");
    }
  };
};
```

**Comment by allforabit** [comment]
Ah brilliant works a treat thanks, @smcenlly. I'm just wondering though, I still have to add this to each test `import 'riteway-jest/assert';`. Is there a reason that the `require("riteway-jest/assert");` doesn't seem to do much? This import is meant to add `assert` globally. Not critical obviously, more out of curiosity!

**Comment by smcenlly** [comment]
I'm not sure why you have to add the import to each test file. I created a sample application and configured jest's `setupFilesAfterEnv` setting to call a new file setup file that I created, `setup-riteway.js` with the contents:

```javascript
require('riteway-jest/assert');
```

After adding this setup file, I don't need to include it in any test files, and wallaby is working correctly.

If you want to send us a sample that has the problem, we'd be happy to take a look, for you.

**Comment by smcenlly** [comment]
I couldn't see any tests configured in the project, maybe you forgot to commit/push them?

I added tests and configured `riteway-jest` by adding `setupFilesAfterEnv` as per my comment above and everything appears to be working. I've created a [pull request](https://github.com/allforabit/test-site-wallaby/pull/1) for your repo that has everything working/configured. Let me know if I've missed something or if you need further assistance.

**Comment by allforabit** [comment]
Yes I forgot to commit some changes I made but yes that is working much better. I'll just use the config you setup, thanks for that.

One last tiny thing... Even though it shows the correct test count for tests that are failing/passing it doesn't mark a failing test with a red dot and it stays green. It's showing the red mark instead in `riteway-jest.js` (found by clicking through from the console). I know this may be due to a shortcoming of riteway-jest and it's integration with jest.

**Comment by smcenlly** [comment]
`jest` behaves the same way when using `riteway-jest` as we're using it in your project. Because the assert wraps `it` (see `riteway-jest` code below), when the `expect` fails, there's no error propagated up from the failed `assert()` function. In both `jest` and `wallaby` this means that your test is never reported in the stack trace for the failed assertion. For `wallaby`, that means we can't show indicators because that information is never passed back.

```javascript
const assert = ({
  given = undefined,
  should = '',
  actual = undefined,
  expected = undefined,
} = {}) => {
  it(`given ${given}: should ${should}`, () => {
    expect(actual).toEqual(expected);
  });
};
```

When testing with `jest` from the command line, my failed test reports as:

```
sum() › given zero: should return the correct sum

    expect(received).toEqual(expected) // deep equality

    Expected: 1
    Received: 2

      at Object.<anonymous> (node_modules/riteway-jest/src/riteway-jest.js:8:20)
```

If you use [wallaby app](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html), you will see the failed tests, but unfortunately there's no way for wallaby to display the error indicator without the correct stack trace being provided.

**Comment by allforabit** [comment]
OK thanks for all the info on that and working through all the config with me.
