### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by rosshulford** [wallabyjs/public#2113]
I have a couple of top level folders (mixins) and (store) in my vuejs config. 

When I run jest from the command line these don't give me any issues. In the wallaby console I typically get 

```Error: Cannot find module '../store/index.js' from 'Nav.spec.js' ```

My wallaby config is as follows

```
module.exports = wallaby => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({
    presets: [["@babel/preset-env", { modules: "commonjs" }]]
  });

  return {
    files: ["./components/**/*", "jest.config.js", "package.json"],

    tests: ["unit/**/*.spec.js"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js": compiler,
      "**/*.vue": require("wallaby-vue-compiler")(compiler)
    },

    preprocessors: {
      "**/*.vue": file => require("vue-jest").process(file.content, file.path)
    },

    setup: function(wallaby) {
      const jestConfig = require("./package").jest || require("./jest.config");
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest",

    debug: true
  };
};
```

Any help would be appreciated.

**Comment by smcenlly** [comment]
If I understand your project structure correctly, your `Nav.spec.js` lives under your `unit` directory, and you also have a folder named `store` with `index.js` in it under the project root?

```
<ProjectRoot>/store/index.js
<ProjectRoot>/unit/Nav.spec.js
```

If this is correct, you will need to include your `store` folder in the files section of your wallaby configuration. From [our docs](https://wallabyjs.com/docs/config/files.html#files):

>  Make sure that all files used by your tests are listed in the config files list. Wallaby.js uses its own cache to process/instrument files and run tests, so it has to copy used files there. For example, if you are loading some .json files from your source code or tests (dynamically from browser tests or require('...') in node.js), they have to be included in the files list.

Your configuration file should then look like this:

```diff
module.exports = wallaby => {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({
    presets: [["@babel/preset-env", { modules: "commonjs" }]]
  });

  return {
    files: [
      "./components/**/*", 
+    "./store/**/*",
      "jest.config.js", 
      "package.json"
    ],

    tests: ["unit/**/*.spec.js"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js": compiler,
      "**/*.vue": require("wallaby-vue-compiler")(compiler)
    },

    preprocessors: {
      "**/*.vue": file => require("vue-jest").process(file.content, file.path)
    },

    setup: function(wallaby) {
      const jestConfig = require("./package").jest || require("./jest.config");
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest",

    debug: true
  };
};
```

You will also want to add any other folders/files (e.g. your mixins) if they are needed by your tests or by source files that are run by your tests.

If I've misunderstood your project structure and this doesn't help, could you please create a simple sample repo that demonstrates the problem?

**Comment by rosshulford** [comment]
Thanks Simon that was it. I did edit that config but thought it was the path to my jest config that was wrong.
