### ISSUE TITLE
Feature request: support yarn workspaces

### ISSUE THREAD

**Issue by allforabit** [wallabyjs/public#2117]
### Issue description or question
From browsing through the older issues it seems that yarn workspaces aren't supported. Is this correct? The workarounds given such as adding `jest` to `noHoist` or alternatively moving the wallaby.js file to the root of the project are brittle and difficult to get to work. Jest works fine OK when configured in one of the sub projects and run from the cli. Ideally wallaby should work similarly and allow for the creation of a wallaby config file alongside the jest file in the sub project. 

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = "test";
module.exports = function(wallaby) {
  return {
    files: [
      "!src/**/__tests__/*.js?(x)",
      "src/**/*.js?(x)",
      "jest-preprocess.js",
      "loadershim.js"
    ],
    tests: [
      "src/**/__tests__/*.js?(x)"
    ],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel({
        presets: ["react-app"]
      })
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.
### OS name and version

OSX

**Comment by allforabit** [comment]
Actually I can see why it doesn't work, it's because of how wallaby copies the js files to a folder in the .vscode directory. My very crude workaround is to symlink my root yarn workspaces `node_modules` to my home directory. That way the node.js module resolution algorithm can find the modules by jumping up a few times through parent directories and finding the node_modules. Obviously only works for a single monorepo. Maybe something could be implemented like that with wallaby where it creates a symlink to the root workspace node_modules in the parent of the duplicated project files. Works a charm then...

**Comment by smcenlly** [comment]
> My very crude workaround is to symlink my root yarn workspaces node_modules to my home directory.

This may work for you now, but you might find that it causes some strange problems in the future with package version conflicts if you have any code that's running under your home directory.

If you haven't already seen in [our docs](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder), there's a method to set/extend the node_modules folders that are used by node to resolve modules. From our docs:

>If you have some node modules in a subfolder of your main project folder, you may need to give wallaby.js a hint about how to load them, as wallaby.js is using its own file cache to run your tests and you probably don’t want to copy the node modules there.
>
>For example, if you have a core subfolder with its own node modules, you may add:

```javascript
var path = require('path');
process.env.NODE_PATH += path.delimiter + 
                         path.join(wallaby.localProjectDir, 'core', 'node_modules');
```

Our [create react application configuration](https://wallabyjs.com/docs/integration/react-jsx.html#configure-wallabyjs) includes an example of enhancing the node_module resolution:

```javascript
module.exports = function (wallaby) {

  // Babel, jest-cli and some other modules may be located under
  // react-scripts/node_modules, so need to let node.js know about it
  var path = require('path');
  process.env.NODE_PATH +=
      path.delimiter +
      path.join(__dirname, 'node_modules') +
      path.delimiter +
      path.join(__dirname, 'node_modules/react-scripts/node_modules');
  require('module').Module._initPaths();

  return {
      files: [
          'jsconfig.json',
          'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
          '!src/**/*.test.js?(x)'
      ],

      tests: ['src/**/*.test.js?(x)'],

      env: {
          type: 'node',
          runner: 'node'
      },

      compilers: {
          '**/*.js?(x)': wallaby.compilers.babel({
              presets: ['react-app']
          })
      },

      setup: wallaby => {
          const createJestConfigUtil = require('react-scripts/scripts/utils/createJestConfig');
          const jestConfig = createJestConfigUtil(p => require.resolve('react-scripts/' + p));
          Object.keys(jestConfig.transform || {})
            .forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
          delete jestConfig.testEnvironment;
          wallaby.testFramework.configure(jestConfig);
      },

      testFramework: 'jest'
  };
};
```

**Comment by allforabit** [comment]
OK thanks for that I think that will work much better.
