### ISSUE TITLE
Wallaby not able to resolve dependencies in runtime with TS and Lerna

### ISSUE THREAD

**Issue by jmgomez** [wallabyjs/public#2120]
### Wallaby not able to resolve dependencies in runtime with TS and Lerna

Im using Typescript, Lerna and Jest. With the default configuration I got the test working and I can see the boxes in green/red on everything that is in the project-test structure. However everything remains grey in project-a. 

When I transform the module name mapper from the setup function,  I can see the red boxes in project-a but wallaby is not able to run the tests. They fail because the dependencies are not loaded (i.e.  TypeError: moment_1.default is not a function ) 

The project has the following structure: 
/
  code/project-a
    ...
  code/project-n
  code/project-tests
  ..
  wallaby.js

 
### Wallaby.js configuration file
```
    module.exports = wallaby => {
 

  return {
    files: [
        'code/tsconfig.json', 
        'code/project-a/src/**/*.+(ts|tsx|json)',
        '!code/project-a/src/**/*.+(d.ts)',
        '!code/project-tests/src/test-unit/**/*Specs.ts*'],

    tests: [
      'code/project-tests/src/test-unit/**/*Specs.ts*',
  ],
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ useStandardDefaults: true, isolatedModules: true , module:"commonjs"}),
    },
   
    env: {
      type: 'node',
      runner: 'node',
    },
    workers: {
      restart:true
    },
    // debug:true,
    testFramework: 'jest',
    setup: wallaby => {
      let jestConfig = {};
      jestConfig.moduleNameMapper = {
        '^project-a/lib/(.*)$': './code/project-a/src/$1',        
      };
      
     
      wallaby.testFramework.configure(jestConfig)  
      },
  }
}

```

**Comment by ArtemGovorov** [comment]
> They fail because the dependencies are not loaded (i.e. TypeError: moment_1.default is not a function )

Could you please share:
- your `package.json` file (dependencies and devDependencies sections is enough),
- your `code/tsconfig.json` and `code/project-a/tsconfig.json`,
- your existing Jest config,
- snippet of code that imports `moment` dependency.

**Comment by jmgomez** [comment]
Thank you for the quick reply. The issue seems to be related of how I'm importing them. I'm using: 

> import moment from 'moment'

However, if I change it to

> import moment = require('moment')

It just works. Is there a way to change them in runtime or any configuration flag that I am missing?

Thanks!

**Comment by smcenlly** [comment]
Could you please provide the other information that we requested? It's important for us to be able to diagnose what's going on.

Could you please share:
- your `package.json` file (dependencies and devDependencies sections is enough),
- your `code/tsconfig.json` and `code/project-a/tsconfig.json`,
- your existing Jest config.

**Comment by jmgomez** [comment]
Can I send you that information privately? Im not allowed to share even those settings publicly. 

Thanks

**Comment by smcenlly** [comment]
In terms of providing us with your configuration files, we recommend setting up a separate sample project with the minimum packages/configuration to duplicate your problem. This way, you're not sending us any proprietary code. If this isn't an option, you may send an email to hello@wallabyjs.com with your configuration instead.

**Comment by smcenlly** [comment]
@jmgomez - I hope my reply to you over email helped. I'm going to close the issue here. Please respond via email if you need further assistance.
