### ISSUE TITLE
Wallaby app should show pass/fail summary data on test group headers

### ISSUE THREAD

**Issue by DarrenPaulWright** [wallabyjs/public#2121]
I often have more tests than fit on the screen at one time, and I also often have multiple nested describes, and both issues can make it difficult to summarizing results in my head.

Just like the '# failed, # passed, # total' summary in the app header, having the same summary data on test group headers would be very helpful.

**Comment by NikGovorov** [comment]
Hi @DarrenPaulWright,

Thanks for the suggestion. We've implemented and released the improvement in version 1.0.59.

**Comment by DarrenPaulWright** [comment]
It looks great, thank you!
