### ISSUE TITLE
Wallaby got errors in Angular7

### ISSUE THREAD

**Issue by junimohano** [wallabyjs/public#2125]
### Issue description or question
```
[Info]  Fri, 28 Jun 2019 19:02:13 GMT wallaby:middleware Serving /src/app/modules/requests/request-list/request-list-filters/store/request-list-filters.state.spec.js.wbp.js from cache
[Info]  Fri, 28 Jun 2019 19:02:14 GMT wallaby:workers Sandbox (active) [9j6j4] error: Uncaught SyntaxError: Unexpected token !
[Error] Runtime error: Uncaught SyntaxError: Unexpected token ! 
[Error] at http://localhost:8609/____wallaby-bundle.js?1561748532417&wallabyFileId=bundle:42338 
[Info]  Fri, 28 Jun 2019 19:02:14 GMT wallaby:workers Sandbox (active) [9j6j4] error: Uncaught Error: Cannot find module 'C:\Users\jun.an\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.130\projects\caddd1c48201c4a2\instrumented\src\wallabyTest.js'
[Error] Runtime error: Uncaught Error: Cannot find module '.\src\wallabyTest.js' 
[Error] at http://localhost:8609/wallaby-webpack.js?1561748532278:1 
[Info]  Fri, 28 Jun 2019 19:02:14 GMT wallaby:workers Failed to map the stack to user code, entry message: Uncaught Error: Cannot find module 'C:\Users\jun.an\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.130\projects\caddd1c48201c4a2\instrumented\src\wallabyTest.js', stack: Uncaught Error: Cannot find module 'C:\Users\jun.an\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.130\projects\caddd1c48201c4a2\instrumented\src\wallabyTest.js'
```

I got this error when I executed Wallaby
I am using Angular 7 and used same config as https://github.com/wallabyjs/ngCliWebpackSample

also followed 
```
// if you are using Angular < 8, then use `import 'core-js/es7/reflect'` instead;
```
in wallabyTest.ts

any ideas????

### Wallaby.js configuration file

used same config as https://github.com/wallabyjs/ngCliWebpackSample

### Code editor or IDE name and version

Visual Studio Code 

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please double check that the `src\wallabyTest.ts` file exists in your project?

If it does, then the issue is likely related to one of the node modules you're importing in your tests. Please create a sample repo demonstrating the issue, we are happy to take a look and investigate.

**Comment by ArtemGovorov** [comment]
The module in question in likely to be imported from your `/src/app/modules/requests/request-list/request-list-filters/store/request-list-filters.state.spec.ts` file (or one of the source files that it imports)

**Comment by smcenlly** [comment]
I'm going to close this issue assuming that everything's working since we haven't heard back. If you're still experiencing problems, let us know and we'll re-open the issue.
