### ISSUE TITLE
/* ignore coverage */ not working on some files

### ISSUE THREAD

**Issue by blogwebpl** [wallabyjs/public#2126]
### Issue description or question

/* ignore coverage */ not working on some files

for example:
in src/functions/getColumns.js - works ok
```
		try {
			return JSON.parse((JSON.stringify(columns)));
		} catch (err) {
			/* ignore coverage */
		 	return []; // < - this line is ignore
		}
```

in src/functions/getCollection.js - not working

```
	try {
		const columns = getColumns(user, collectionName);
		const select = columns.map((column) => (column.key)).join(' ');
		const populate = getPopulate(user, collectionName);
		const data = await getModel(collectionName).find().select(select).populate(populate).lean();
		return data;
	} catch (err) {
		/* ignore coverage */
		return []; // < - this line is not ignore
	}
```
Full source:
https://github.com/blogwebpl/gps_server

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test';

module.exports = function(wallaby) {
	return {
		hints: {
			ignoreCoverage: /ignore coverage/
		},
		files: [
			'src/*.js', 'src/**/*.js', '!src/**/*.test.js'
		],
		tests: [
			'src/**/*.test.js'
		],
		compilers: {
			'src/**/*.js': wallaby.compilers.babel()
		},
		env: {
			type: 'node'
		},
		testFramework: 'mocha',
		setup: (wallaby) => {
			const runningMocha = wallaby.testFramework;
			runningMocha.timeout(15000);
		},
		debug: true,
		workers: {
			recycle: true,
			initial: 1,
			regular: 1
		}
	};
};

```

### Code editor or IDE name and version

Visual Studio Code v1.35

### OS name and version

OSX

**Comment by smcenlly** [comment]
The reason that the hints are not working is because babel is removing these comments when it transforms your file. When wallaby receives the babel output, there are no longer comments for it to process.

You can see this for yourself by running:

```
npx babel ./src/functions/getCollection.js
```

We can't easily determine which babel transform is causing the problem, but this information should allow you to investigate further.
