### ISSUE TITLE
Wallaby with react jest and Flow - setup issue

### ISSUE THREAD

**Issue by natan-mobileheartbeat** [wallabyjs/public#2129]
### Issue description or question
I am trying to setup the wallaby to work with @Flow inside a project of 'react-redux' 
I created a very simple test that calls a function from a "code" file
This is error I am getting:
```javascript
Failed to run compilers on core/try.js, SyntaxError: /Users/Shared/git/mhcure-webapp/src/core/try.js: Unexpected token, expected "," (2:30)

  1 | // @Flow
> 2 | export const pleaseAdd = ( num: number ) => {
    |                               ^
  3 |    return num+1;
  4 | };
    at Object.raise (/Users/Shared/git/mhcure-webapp/src/node_modules/@babel/parser/lib/index.js:6344:17)
```
Please let me know how to setup my project so I can start using Wallaby.js with all my tests.
We just purchased 3 licenses and my team is eager to start using Wallaby.
Thanks
Natan
### Wallaby.js configuration file
```javascript
process.env.NODE_ENV = 'test';

// eslint-disable-next-line func-names
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
        "./core/try.js",
     { pattern: "test/*.js", instrument: false }      ],

        tests: [
            "./core/try.test.js"
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({

            })
        },

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony',
            },
        },

        testFramework: 'jest',

        setup: (w) => {
            w.testFramework.configure({
                moduleFileExtensions: ['js'],
                moduleNameMapper: {
                    '^.+\\.(css|scss|sass)$': '<rootDir>/test/styleMock.js',
                    '^.+\\.(gif|ttf|eot|svg)$': '<rootDir>/test/fileMock.js',
                },
            });
        },
    };
};
```

### Code editor or IDE name and version
WebStorm v?2018.3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
What version of Jest are you using? 

- If you are using v24 (or are happy to migrate to Jest v24), please try our new [automatic Wallaby configuration feature](https://wallabyjs.com/docs/intro/config.html#jetbrains-ides).
- If you are using Jest v23 (or less), please check the following:
  - is running `npx jest` from your project's root in command line working?
  - where is your Babel configuration (that includes flow plugin or other presets) located?

**Comment by natan-mobileheartbeat** [comment]
runnig npx jest returns the following errors for all my tests
```javascript
'Plugin/Preset files are not allowed to export objects, only functions. In ....../node_modules/babel-preset-stage-0/lib/index.js'
```

regarding the second question, it is located inside the .bablerc - here is the file content
```javaScript
{
  "presets": [
    ["./electron_build/node_modules/babel-preset-env", {
      "targets": { "node": 10 },
      "useBuiltIns": true
    }],
    "./electron_build/node_modules/babel-preset-stage-0",
    "./electron_build/node_modules/babel-preset-react"
  ],
  "plugins": ["./electron_build/node_modules/babel-plugin-add-module-exports"],
  "env": {
    "production": {
      "presets": ["./electron_build/node_modules/babel-preset-react-optimize"],
      "plugins": ["./electron_build/node_modules/babel-plugin-dev-expression"]
    },
    "development": {
      "plugins": [
        "./electron_build/node_modules/babel-plugin-transform-class-properties",
        "./electron_build/node_modules/babel-plugin-transform-es2015-classes",
        ["./electron_build/node_modules/babel-plugin-flow-runtime", {
          "assert": true,
          "annotate": true
        }]
      ]
    }
  }
}
```

**Comment by natan-mobileheartbeat** [comment]
Also all my functions are in the form of
```javascript
const doSomeWork = (arg) => {

};
```
and of course for public function I am adding 'export' before that

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. Looks like your flow plugins sits under `development` environment, your Wallaby config however sets it to `test`. Try this:

```diff
+process.env.BABEL_ENV = 'development';
+process.env.NODE_ENV = 'development';
-process.env.NODE_ENV = 'test';

// eslint-disable-next-line func-names
module.exports = function (wallaby) {
  ...
```

Also, if `npx jest` is not working for you, how are you running your tests without Wallaby?

**Comment by natan-mobileheartbeat** [comment]
we are running the test using "yarn" to start a script
The script (inside package.json) is:
```javascript
react-scripts test --env=jsdom
```

**Comment by natan-mobileheartbeat** [comment]
Can I change the "wallaby.js" to ES6 instead of using module.exports?
Can you provide a sample file please?

**Comment by natan-mobileheartbeat** [comment]
Thanks for the response for our "process.env" I will change it tomorrow morning and see if this can take me to the next level.

**Comment by ArtemGovorov** [comment]
> Can I change the "wallaby.js" to ES6 instead of using module.exports?

This is not possible at the moment.

> react-scripts test --env=jsdom

Is your app `create-react-app` generated? If so, then this config should be a good start - https://wallabyjs.com/docs/integration/react-jsx.html#configure-wallabyjs.

**Comment by natan-mobileheartbeat** [comment]
Hello again, Thanks for the latest update, it is starting to look much better.
Many tests are still failing over "Enzyme"
The error I am getting is below.
I saw that it mentioned "Adapters" but I could not find in the docs how and where to add the adapter.
Do you add it inside the wallaby.js? can you provide an example.
Thanks again
```javascript
Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none.
	      To configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
	      before using any of Enzyme's top level APIs, where `Adapter` is the adapter
	      corresponding to the library currently being tested. For example:
	
	      import Adapter from 'enzyme-adapter-react-15';
```

**Comment by natan-mobileheartbeat** [comment]
Also I have few hundreds of tests, Wallaby finds only a single test.
Here is my Wallaby.js
```javascript
//const Enzyme = require('enzyme');
//const Adapter = require('enzyme-adapter-react-16');
import {configure} from "enzyme";
import Adapter from "enzyme-adapter-react-16";

module.exports = function (wallaby) {

    // Babel, jest-cli and some other modules may be located under
    // react-scripts/node_modules, so need to let node.js know about it
    var path = require('path');
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(__dirname, 'node_modules/react-scripts/node_modules');
    require('module').Module._initPaths();

    return {
        files: [
            //'jsconfig.json',
            './setupTests.js',
            //'./core/try.js'
            './**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
            '!./**/*.test.js?(x)',
            '!./node_modules/**/*.js',
            '!./electron_build/**/*'
        ],

        tests: [
            './**/*.test.js',
            './core/**/*.test.js'
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel({
                presets: ['react-app']
            })
        },

        setup: wallaby => {
            // const Enzyme = require('enzyme');// import { configure } from 'enzyme';
            // const Adapter = require('enzyme-adapter-react-16');
            // Enzyme.configure({ adapter: new Adapter() });
            const createJestConfigUtil = require('react-scripts/scripts/utils/createJestConfig');
            const jestConfig = createJestConfigUtil(p => require.resolve('react-scripts/' + p));
            Object.keys(jestConfig.transform || {})
                .forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
            delete jestConfig.testEnvironment;
            wallaby.testFramework.configure(jestConfig);
        },

        testFramework: 'jest'
    };
};
```
I added on the top of the test file these 2 lines so the test passes.
```javascript
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
```
I need to be able to add it in a central place so all the tests are getting the 'enzyme' configuration.
Inside the wallaby.js I tried to add these lines, didn't work. I left these line commented

**Comment by ArtemGovorov** [comment]
> fetch is not defined - I am using fetch.resetMocks() and fetch.once() but wallaby can't find those.

Where do you define fetch for Jest (without Wallaby)?

> Do you add it inside the wallaby.js? can you provide an example.

> import { configure } from 'enzyme';
> import Adapter from 'enzyme-adapter-react-16';

Do you have a Jest setup file somewhere that has the 2 lines above? If so, then adding the file to [Jest setup files](https://jestjs.io/docs/en/configuration#setupfiles-array) in Wallaby config should be enough. 


If you set up a sample repo demonstrating the issues, we are happy to take a look and create a pull request with working wallaby config for you.

P.S. It's highly not recommended to add `./**/...` like patterns to your `files` and `tests`:

>         '!./**/*.test.js?(x)',
>            '!./node_modules/**/*.js',
>            '!./electron_build/**/*'
>        ],
>
>        tests: [
>            './**/*.test.js',

as it may affect file watcher performance. I'd suggest to to add more specific patterns like:

```
src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)'
...
src/**/*.test.js
```
or, at least fully exclude node_modules (not just .js files) from both `files` and `tests` lists:

```
files: [
  ...
  '!node_modules/**'
],

tests: [
  ..
  '!node_modules/**'
]
```

**Comment by natan-mobileheartbeat** [comment]
I have the file "setupTests.js"
```javascript
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

global.fetch = require('jest-fetch-mock');
```
Not sure where to add a reference to this file for the Wallaby config.
Please advise,

**Comment by ArtemGovorov** [comment]
@natan-mobileheartbeat Thanks for providing the repo. I have pushed the config changes to make it work. Now all tests in your repo are passing with Wallaby. If you face any more config issues, please feel free to update the repo, and we'll take a look.

**Comment by natan-mobileheartbeat** [comment]
Perfect. Thank you so much. It works like a charm.
Great support.

**Comment by natan-mobileheartbeat** [comment]
Hi Artem,
Wallaby was working great in recent weeks. As of yesterday we can't get it to work. This is the error that we get for every single test:
Jest encountered an unexpected token

This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/en/configuration.html

Details:

./setupTests.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from 'enzyme';
                                                                                                ^

SyntaxError: Unexpected token {

	at setupTests.js:1


Please advise,
Natan

**Comment by smcenlly** [comment]
Hi Natan,

Are you able to update your [sample repo](https://github.com/natan-mobileheartbeat/wallaby-setup) so that it has the same problem?

**Comment by natan-mobileheartbeat** [comment]
Hi Simon,
Thanks for the follow up.
I took the following steps

  1.  Restart my MacBook
  2.  Switch to the master branch
  3.  Switch back to my working branch
After these steps (like a magic) the Wallaby started working again.
Not sure what cause it to begin with but I am very happy to have it back and running.

FYI,
Natan
