### ISSUE TITLE
Regretting not open sourcing?

### ISSUE THREAD

**Issue by youssefsharief** [wallabyjs/public#2131]
First, thank you for the awesome products.

If you went back on time, would you rather open source the project? Or are you happy with your choice? I also think that you might have made more money open sourcing it. I think you might have gained financially via capitalizing on the popularity of the project through services, etc. 
I am not sure if I am right, but I would like to get your perspective on this.
No plans to open source your project in the future?

**Comment by smcenlly** [comment]
Thanks for your interest in our products.

> If you went back on time, would you rather open source the project? Or are you happy with your choice? 

When we first commercialized our offering, it wasn't economically viable for us to make our products open-source. Where we are now in our commercialization phase, it doesn't make sense to change our model. We have a number of developers who work full-time on our products. We reinvest the revenue we receive into adding support for new editors, improving our products, keeping them up-to-date with the latest Javascript language features and testing frameworks.

We love the open source community and sponsor a number of open source projects (a few examples include: Mocha, VSCode-Icons, Quasar Framework).

> I also think that you might have made more money open sourcing it. I think you might have gained financially via capitalizing on the popularity of the project through services, etc. I am not sure if I am right, but I would like to get your perspective on this.

You may be right, but beyond initial configuration, we don’t see a lot of need for services in our space. We want to make the initial configuration completely turn-key (no configuration required), which also means no services required. If you’re interested in what we’re doing in this space, check out our [automatic configuration for jest v24+](https://wallabyjs.com/docs/integration/jest.html) (released last week). 

> No plans to open source your project in the future?

We don’t have an immediate plans to open-source our current product offerings in the future but will definitely consider for future products that we may develop.

**Comment by youssefsharief** [comment]
Thank you so much for your response.
