### ISSUE TITLE
.env Issues

### ISSUE THREAD

**Issue by moonthug** [wallabyjs/public#2132]
### Issue description or question
Just updated wallaby to `v1.0.705` and I'm now getting errors with `.env` files.

My folder structure looks like this:
```
├── src
│   └── lib
|       └── dotenv.js
|   └── app.js
├── .env
└── wallaby.js

```
The file `src/lib/dotenv.js` is loaded on the first line of app js which uses the `dotenv` module to load the `.env` in the root of the project.

Without adding the `.env` to the files, its not copied, however now I cant seem to stop it being instrumented/parsed.

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      'src/**/*.js',
      'package.json',
      '.env',
      'test/integration/**/*.js',
      { pattern: '.env', instrument: false },
      { pattern: 'src/**/*.spec.js', ignore: true },
      { pattern: 'test/integration/api/**/*.js', ignore: true }
    ],
    tests: [
      'src/**/*.spec.js',
      'test/integration/api/**/*.js'
    ],
    env: {
      type: 'node'
    }
  };
};
```

Error:
```
wallaby.js started
core v1.0.705
Failed to set up project file system: Error: Failed to instrument .env
> 1 | #######################################
    | ^ SyntaxError: Unexpected character '#' (1:0)
  2 | #
  3 | # PROJECT
  4 | 
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

### Code editor or IDE name and version
IDEA 2019.1.3

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
> Just updated wallaby to v1.0.705 and I'm now getting errors with .env files.

I don't think the issue is specific to the version update, [Wallaby always required all files used in your tests to be in the `files` list](https://wallabyjs.com/docs/config/files.html).

> Without adding the .env to the files, its not copied, however now I cant seem to stop it being instrumented/parsed.

This is because first entry found in the `files` list dictates file properties (including whether or not the file is instrumented, that is `true` by default). All you need to do is to get rid of the duplicate that causes the file to be instrumented:

```diff
    files: [
      'src/**/*.js',
      'package.json',
-     '.env',
      'test/integration/**/*.js',
      { pattern: '.env', instrument: false },
      { pattern: 'src/**/*.spec.js', ignore: true },
      { pattern: 'test/integration/api/**/*.js', ignore: true }
    ],
```
