### ISSUE TITLE
'na' coverage on a file where as jest coverage shows 100

### ISSUE THREAD

**Issue by harshanooka** [wallabyjs/public#2135]
### Issue description or question
When checking for coverage on wallaby app for a file, it shows as 'na' whereas jest coverage report shows 100%. The total coverage on jest reporting is 83.75% whereas on Wallaby is 71.54%

### Wallaby.js configuration file
```javascript

const ngxWallabyJest = require("ngx-wallaby-jest");

module.exports = function(wallaby) {
  return {
    files: [
      //Files used for testing
      { pattern: "tsconfig.json", load: false },
      { pattern: "src/tsconfig.spec.json", load: false },
      { pattern: "jest.config.js", load: false },
      { pattern: "setupJest.ts", load: false },
      { pattern: "jestGlobalMocks.ts", load: false },
      { pattern: "src/environments/*.ts" },
      { pattern: "src/app/**/*.ts", load: false },
      { pattern: "__tests__/**/*.ts", load: false },
      { pattern: "test/**/*.ts", load: false },
      { pattern: "src/app/**/*.spec.ts", ignore: true },
      { pattern: "src/app/**/*.test.ts", ignore: true },
      { pattern: "src/app/**/*.d.ts", ignore: true }
    ],
    compilers: {
      "**/*.ts?(x)": wallaby.compilers.typeScript({
        module: "commonjs"
      })
    },
    tests: ["src/app/**/*.spec.ts"],
    env: {
      //Jest tests runs on node, not on a browser!
      type: "node",
      runner: "node"
    },
    preprocessors: {
      // This translate templateUrl and styleUrls to the right implementation
      // For wallaby
      "src/**/*.component.ts": ngxWallabyJest
    },
    testFramework: "jest",
    bootstrap: function(wallaby) {
      //Use the configured jest file for testing
      const jestConfig = require("./jest.config.js");
      wallaby.testFramework.configure(jestConfig);
    },
    debug: true
  };
};
```
### jest configuration file

```javascript
module.exports = {
  "testMatch": [
    "<rootDir>/src/**/*.spec.ts",
    "<rootDir>/src/**/__tests__/**/*.ts"
  ],
  "preset": "jest-preset-angular",
  "setupTestFrameworkScriptFile": "<rootDir>/setupJest.ts",
  "coverageDirectory": "./coverage/",
  "collectCoverage": true,
  "collectCoverageFrom": [
    "**/src/**/*.ts"
  ],
  "coveragePathIgnorePatterns": [
    "<rootDir>/jestGlobalMocks.ts",
    "<rootDir>/node_modules/",
    "<rootDir>/src/environments/",
    "<rootDir>/src/main.ts",
    "<rootDir>/src/polyfills.ts",
    "<rootDir>/src/test.ts",
    ".*\\.d\\.ts",
    ".*.routes.ts",
    ".*.module.ts",
    ".*.mock.ts"
  ],
  "moduleNameMapper": {
    "^store/(.*)$": "<rootDir>/src/app/store/$1",
    "^config/(.*)$": "<rootDir>/src/app/config/$1",
    "^app/(.*)$": "<rootDir>/src/app/$1"
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.36.0

### OS name and version

OSX
Mojave 10.14

<img width="1678" alt="Screen Shot 2019-07-11 at 11 02 51 PM" src="https://user-images.githubusercontent.com/12086853/61105875-1806e000-a430-11e9-85f0-808200e4096f.png">
<img width="1680" alt="Screen Shot 2019-07-11 at 11 03 03 PM" src="https://user-images.githubusercontent.com/12086853/61105876-189f7680-a430-11e9-8136-8d74d10a6b0d.png">

**Comment by ArtemGovorov** [comment]
The result is expected.

> The total coverage on jest reporting is 83.75% whereas on Wallaby is 71.54%
> it shows as 'na' whereas jest coverage report shows 100%. 

Wallaby is measuring code coverage a bit differently from Jest.

Re: your `auth.component.ts` file, there are no coverable regions in the file that may/may not execute, so there's nothing to report. If you add a method to the class with some lines in it (even console.log), then the code coverage will start showing up.

Re: your `auth.component.unit.spec.ts` file `n/a` is expected because it is a test file and coverage is not measure for test files (same as in Jest and other testing frameworks).

**Comment by harshanooka** [comment]
thanks for answering my questions. Just wanted to show that tests are being run in the corresponding spec file. Any thoughts on getting the coverages on empty components like these where I only care about if they are instantiating properly in the unit test?

**Comment by ArtemGovorov** [comment]
> Any thoughts on getting the coverages on empty components like these where I only care about if they are instantiating properly in the unit test?

There's no code coverage available for this files in Wallaby, and it is expected. Wallaby calculates code coverage based on how many coverable code regions are covered/uncovered in the file. In your empty components, there are no coverable code regions, hence calculating code coverage metric is not possible. If your component does nothing that can be executed or not executed, then reporting any coverage for it is misleading.
