### ISSUE TITLE
Wallaby App not working with VS Code Remote SSH

### ISSUE THREAD

**Issue by rfermann** [wallabyjs/public#2136]
### Issue description or question
I'm running Wallaby.js (Wallaby.js Core v1.0.708) on a remote machine using VS Code Remote SSH extension. Wallaby.js itself is working fine with that setup. All tests are running as expected, coverage indicators are working as well. 

The only thing not fully working is the Wallaby App. I am able to access it as soon as Wallaby.js is running, but the loading indicator shows up forever, not outputting any information:
![Bildschirmfoto 2019-07-12 um 10 52 52](https://user-images.githubusercontent.com/18217019/61115682-4669d700-a493-11e9-91d0-fdebb9799e45.png)

This is a screenshot from the browser console:
![Image](https://user-images.githubusercontent.com/18217019/61115450-c8a5cb80-a492-11e9-871f-eb2ec03ea202.png)

Is there some setting I as a user need to configure in order to use the Wallaby App in conjunction with the Remote SSH extension? I haven't found anything regarding this in the docs so far.

### Wallaby.js configuration file
automatic configuration is used

### Code editor or IDE name and version

Visual Studio Code v1.36.1

### OS name and version
Ubuntu 18.04.2 LTS

**Comment by rfermann** [comment]
...the issue seems to be pretty obvious, I don't know why I haven't recognized it before. The app is trying to connect to the localhost of the browser, which is apparently not working, as Wallaby.js is running on the remote computer. 

Is there any option to configure the address the Wallaby App is connecting to?

**Comment by smcenlly** [comment]
Right now wallaby app is hardcoded to use localhost (`127.0.0.1`). We'll investigate how to address this scenario over the coming week.

**Comment by rfermann** [comment]
Thanks for the update.
Meanwhile I did a short test using ssh port forwarding. I redirected the requests on 127.0.0.1:51235 to the same port on my remote machine with `ssh -L 127.0.0.1:51235:remote-ip:51235 -N 127.0.0.1`. After activating port forwarding the Wallaby App started working as it would work when running locally. 

I will use this workaround for now, but it would be great if you can make this configurable or even auto-detectable.

**Comment by rfermann** [comment]
@smcenlly do you have any news on this topic?

**Comment by NikGovorov** [comment]
Hi @rfermann,

We are going to address the issue tomorrow by adding `server` query string parameter that will be persisted in local storage and displayed near `project name`.  Also we will consider to improve UX in the case by adding proper UI later, but I don't have ETA yet.

**Comment by NikGovorov** [comment]
The feature is implemented in 1.0.61. 

To set/persist `server` setting, please open `http://wallabyjs.com/app?server={IP address or hostname}`, for example `http://wallabyjs.com/app?server=128.0.0.1`. 

If the setting is set then App's status bar will display the server (IP address or hostname) it is connected to and the button to reset the setting.

![ScreenClip](https://user-images.githubusercontent.com/129254/62194395-2015c800-b3bd-11e9-9cb9-6fba566ca2f6.png)

**Comment by rfermann** [comment]
It's working fine now. Thanks for addressing this topic.

**Comment by jfpaccini** [comment]
Hello @NikGovorov 

As I am doing remote development over ssh (with vscode), I used the /app?server=... trick, which worked fine.

However, this seems to be broken since a few days. Did anything change ?

Thanks !

**Comment by smcenlly** [comment]
@jfpaccini - we haven't changed anything on our end. Right now, Wallaby uses a fixed port number (`51245`) for hosting Wallaby app. In the past, we have seen other programs use the same port with a different protocol (not HTTP) which has caused problems. You may like to check which ports are in use on your SSH host or else restart the host and Wallaby to see if that fixes your problem.

**Comment by jfpaccini** [comment]
@smcenlly thank you for your answer. The 51245 tcp port is correctly used by the wallaby app and I can connect to it from my local host successfully. 

when I launch a new instance with:
http://wallabyjs.com/app?server=63.xx.xx.xx, (63.xx.xx.xx being my development box), here is what I get in the console:
![image](https://user-images.githubusercontent.com/48450834/93114086-6e1d8600-f6ba-11ea-81a0-f68b2eac537d.png)

notice that there a no connection attempted to 63.xx.xx.xx , only then a bunch of websocket connections to 127.0.0.1:....

I tried to flush any localstorage, cookie, etc... no luck. private mode, no luck.

however, I had saved my previous setup as a chrome app, and here is what happens when I launch it (server name is dev-jf.xxxx):

![image](https://user-images.githubusercontent.com/48450834/93114647-1fbcb700-f6bb-11ea-83ac-d268cdefb51a.png)
And in that case, I can see a connection being established on my dev box.

¯\_(ツ)_/¯

any idea ? should I open an issue to document this ?

thanks

**Comment by smcenlly** [comment]
@jfpaccini - we have identified the cause of this problem and fixed it. Please try accessing your server again with:

`http://wallabyjs.com/app/?server=63.xx.xx.xx` (after update IP address)

Everything should now work for you. If it does not, please clear your browser cache.

**Comment by jfpaccini** [comment]
@smcenlly works flawlessly now !! thanks 🍻

PS: I am not sure this /?server=xxx option appears in your main documentation website, I could only find it in this thread. That may help other folks.

PS2: wallabyjs rocks !

**Comment by smcenlly** [comment]
Thanks - [we've updated our docs](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#how-do-i-access-wallaby-app-if-developing-remotely).
