### ISSUE TITLE
Purchased pro - Error starting Wallaby: "Cannot find module 'underscore.string'"

### ISSUE THREAD

**Issue by onexdata** [wallabyjs/public#2137]
### Issue description or question
I purchased a pro license. Cannot install Wallaby.js anymore. Used to work fine approximately 1 month ago, now no commands work. Tried uninstalling and reinstalling and I get "Cannot find module 'underscore.string'" during install, however, Wallaby.js appears to be installed and commands have been added to the palette, just none of them work.

### Wallaby.js configuration file
I cannot seem to finish installing it, so no commands work. i.e. I also get: ```command 'wallaby.selectConfigFile' not found```

### Code editor or IDE name and version
Visual Studio Code v1.36.1 (system setup)

### OS name and version
Windows 10 Pro

**Comment by ArtemGovorov** [comment]
Looks like your Wallaby installation in VS Code somehow got corrupted. This should help:

- Close VS Code, 
- Open `~/.vscode/` folder (where `~` is your home directory),
- Delete all `wallabyjs.wallaby-vscode-*` subfolders, delete `.obsolete` file if present in the folder.
- Start VS Code,
- Install Wallaby.js extension, and wait until message saying that core has been successfully installed.
