### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by sertae** [wallabyjs/public#214]
Solution: set `env.runner`

Something for troubleshooting area in docs:

If `env.type` is set to `node` but `env.runner` is not set most of the time everything will work as expected with Wallaby fallback to io.js version. Until you try to install npm package that is build during installation for your node version. Then you get 'Module did not self-register' error or some 'Method not supported' variation. It's not clear why `npm install` breaks Wallaby and took me some time to figure this out.

Please add this to troubleshooting docs. And/or add more logic to Wallaby to try to figure out which node version application will use.

**Comment by ArtemGovorov** [comment]
Added the [documentation section](http://wallabyjs.com/docs/intro/troubleshooting.html#39-module-did-not-self-register-39).
