### ISSUE TITLE
dynamic imports are broken Next.js 9.0.2 (again)

### ISSUE THREAD

**Issue by mattruby** [wallabyjs/public#2140]
### Issue description or question
Next.js 9.0.2 next/babel is not working with Wallaby. dynamic imports are failing in wallaby, but working well in Jest.

This seems to be the same issue as: https://github.com/wallabyjs/public/issues/2088
That was resolved by adding `process.env.NODE_ENV = "test";`.  That fix is no longer holding.

Here's a small demo repo: https://github.com/mattruby/wallaby_next_demo (same as before, but upgraded to next 9.0.2)

### Wallaby.js configuration file

```
module.exports = function(wallaby) {
process.env.NODE_ENV = "test";
  return {
    files: ["**/*.js", "!**/*.test.js", "!/node_modules/*"],

    tests: ["**/*.test.js","!/node_modules/*"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },

    testFramework: "jest",

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.36.1

### OS name and version
OSX Mojave 10.14.5

**Comment by smcenlly** [comment]
For some reason the `jest` tests aren't working for me from the cli. After installing packages with `yarn`, I get an error when I run `npm test`:

```
  ● fancy method

    Not supported

      1 | export const simpleMethod = data => data;
      2 | 
    > 3 | export const fancyMethod = async data => {
        |                            ^
      4 |   const otherMethod = await import("./otherMethod").then(
      5 |     module => module.otherMethod
      6 |   );
```

Regardless, there's a quick fix to get this working, which should fix this type of problem permanently. We recently released a new feature that allows you to use Wallaby without any configuration for Jest v24+. You can read about how to use it in [our docs](https://wallabyjs.com/docs/intro/config.html#automatic-configuration), but it's pretty simple:

> To start Wallaby without configuration in VS Code you may run Select Configuration command and then select Automatic Configuration option once. After that you may keep using Wallaby Start command as usual and it will start Wallaby with automatic configuration.
>
> ![image](https://wallabyjs.com/assets/img/vsc_select_config.gif)

If you switch to automatic configuration using Jest, you can delete your configuration file. If you still want to use a configuration file (e.g. your customizing `debug` setting, or `delay` setting), you may continue to do so, also mentioned in [our docs](https://wallabyjs.com/docs/intro/config.html#configuration-file).

**Comment by ArtemGovorov** [comment]
If you would like to keep using your config file (we recommend switching to the new automatic config like @smcenlly had described above), here's the change you need to make it work:

```diff
module.exports = function(wallaby) {
process.env.NODE_ENV = "test";
  return {
-   files: ["**/*.js", "!**/*.test.js", "!/node_modules/*"],
+   files: ["**/*.js", "!**/*.test.js", {pattern: '.babelrc', instrument: false}, "!/node_modules/*"],

    tests: ["**/*.test.js","!/node_modules/*"],

    env: {
      type: "node",
      runner: "node"
    },

    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel()
    },

    testFramework: "jest",

    debug: true
  };
};
```

**Comment by mattruby** [comment]
Thank you!  `{ pattern: '.babelrc', instrument: false },` was the missing link!  We'll look at the automatic config next time this crops up.  
Thanks again!
