### ISSUE TITLE
Wallaby fails silently

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#2145]
### Issue description or question

1. `git clone https://github.com/DenisGorbachev/talloc talloc-test`
1. `cd talloc-test`
1. `yarn`
1. Create Wallaby Run configuration:
![image](https://user-images.githubusercontent.com/829578/61538036-3dec4000-aa41-11e9-9929-aa7b9e690145.png)
1. Click `Run`

**Expected**: Wallaby runs tests.
**Actual**: Wallaby fails silently:
![image](https://user-images.githubusercontent.com/829578/61538178-89065300-aa41-11e9-8871-302252f26bef.png)

I believe it happens because of `@shelf/jest-mongodb`. To reproduce:

1. Open `jest.config.js`
2. Remove `jest_mongodb_preset` (`jest_coffeescript_preset, jest_mongodb_preset` -> `jest_coffeescript_preset`)
3. Re-run Wallaby.

It prints errors, but only because MongoDB URI is not supplied in tests due to removal of `jest_mongodb_preset`. At least it runs.

FYI: `jest-mongodb-config.local.js` is currently _commented out_ in `jest-mongodb-config.js`

### Wallaby.js configuration file

```javascript
const _ = require('lodash');
const fs = require('fs');
const babelConfig = require('./babel.config');

ifExists = function (filename) {
  return fs.existsSync(filename) && filename;
};

module.exports = function (wallaby) {
  console.log('__dirname', __dirname);
  return {
    debug: true,

    files: _.compact([
      'lib/**/*.coffee',
      'babel.config.js',
      'jest.config.js',
      'jest-mongodb-config.js',
      ifExists('jest-mongodb-config.local.js')
    ]),

    tests: [
      'test/**/*.test.coffee'
    ],

    testFramework: 'jest',

    env: {
      type: 'node'
    },

    setup: function (wallaby) {
      var jestConfig = require('./jest.config');
      wallaby.testFramework.configure(jestConfig);
    },

    compilers: {
      '**/*.coffee': wallaby.compilers.coffeeScript({
        transpile: babelConfig
      }),
      // '**/*.js': wallaby.compilers.babel()
    }
  };
};
```

### Code editor or IDE name and version

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic

### OS name and version

starfall@nx:/tmp/talloc-test$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"

**Comment by smcenlly** [comment]
Thanks for the sample repo!

We recently released [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) for jest v24+. Could you please enable this for your project? You will need the latest version of Wallaby for IntelliJ.

> To start Wallaby without a configuration file in JetBrains IDEs, you may edit (or create a new) wallaby.js Run Configuration by selecting Edit configurations from the drop-down menu in the top right-hand corner of the navigation bar, or from the Run menu. In the run configuration editor set Configuration Type filed value to Automatic.
> ![](https://wallabyjs.com/assets/img/jb_select_config.gif)

I tried this on your repo and everything works for me. Initially tests were failing to connect to the mongodb memory provider, but then everything magically started working and I couldn't reproduce my initial mongodb problems.

**Comment by DenisGorbachev** [comment]
Confirmed: automatic configuration works. Thanks for the tip, Simon!
