### ISSUE TITLE
Wallaby fails sometimes while Jest succeeds everytime

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#2147]
### Issue description or question

1. `git clone https://github.com/DenisGorbachev/talloc talloc-test`
1. `cd talloc-test`
1. `yarn`
1. Create Wallaby Run configuration (automatic):
![image](https://user-images.githubusercontent.com/829578/61723966-af93f900-ad75-11e9-8ee9-ec1825aa8258.png)
1. Click `Run`

**Expected:** Wallaby succeeds everytime.
**Actual:** Wallaby succeeds sometimes, but other times it fails with `MongoNetworkError: failed to connect to server [127.0.0.1:42531] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:42531]` (port is random)

FYI: `for run in {1..10}; do jest test/PerformAirdrop.test.coffee; done` succeeds everytime.

### Wallaby.js configuration file

```javascript
const _ = require('lodash');
const fs = require('fs');
const babelConfig = require('./babel.config');

ifExists = function (filename) {
  return fs.existsSync(filename) && filename;
};

module.exports = function (wallaby) {
  console.log('__dirname', __dirname);
  return {
    debug: true,

    files: _.compact([
      'lib/**/*.coffee',
      'babel.config.js',
      'jest.config.js',
      'jest-mongodb-config.js',
      ifExists('jest-mongodb-config.local.js')
    ]),

    tests: [
      'test/**/*.test.coffee'
    ],

    testFramework: 'jest',

    env: {
      type: 'node'
    },

    setup: function (wallaby) {
      var jestConfig = require('./jest.config');
      wallaby.testFramework.configure(jestConfig);
    },

    compilers: {
      '**/*.coffee': wallaby.compilers.coffeeScript({
        transpile: babelConfig
      }),
      // '**/*.js': wallaby.compilers.babel()
    }
  };
};
```

### Code editor or IDE name and version

WebStorm 2019.1.3
Build #WS-191.7479.14, built on May 27, 2019
JRE: 1.8.0_202-release-1483-b53 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-20-generic

### OS name and version

starfall@nx:/tmp/talloc-test$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.1
DISTRIB_CODENAME=tessa
DISTRIB_DESCRIPTION="Linux Mint 19.1 Tessa"

**Comment by ArtemGovorov** [comment]
Please update your [Wallaby Core to the latest version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), change your Wallaby config as follows, and change your run configuration type to `Configuration File` (with the config file selected):

```js
module.exports = function () {
  return {

    autoDetect: true,

    workers: {initial: 1, regular: 1}
  };
};
```

**Comment by DenisGorbachev** [comment]
Confirmed: it fixed the issue.

Does `workers: {initial: 1, regular: 1}` mean that tests don't run in parallel, or are they still parallellized by Jest?

**Comment by DenisGorbachev** [comment]
Also, your support is amazing. Keep it up!

**Comment by smcenlly** [comment]
> Also, your support is amazing. Keep it up!

Thanks :)

> Does workers: {initial: 1, regular: 1} mean that tests don't run in parallel, or are they still parallellized by Jest?

The `workers` object property specifies the degree of parallelism that **wallaby** uses to run your tests and controls the way wallaby.js re-uses workers. Under the covers, we start jest with `runInBand` for each worker and merge results at the end.

Once your tests run after start, wallaby only runs the tests that have changed (can even be one test). If you're experiencing slower performance with wallaby vs. jest cli after this change, let us know and we'll investigate further.
