### ISSUE TITLE
Mocha with Enzyme and Webpack

### ISSUE THREAD

**Issue by steveHornseyDeveloper** [wallabyjs/public#2150]
### Issue description or question
I am having troubles getting my test suite working with wallaby.js.
I have tried using both webpack and not using webpack. I got further with using webpack (couldn't solve some file resolutions without webpack). I have left some commented code in to show some other things I've tried.
In my with Webpack config I think i just need to run the Enzyme adapter configuration.

```
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

However, I cannot work out how  to run it whilst running with webpack and whilst:
`env: { kind: 'chrome' },`
As require is undefined (i guess because it is running in a browser environment rather than node).

I have a mocha.opts file which normally defines some set up files which Wallaby seems to ignore.

### Wallaby.js configuration file
```
const webpackConfig = require('./webpack.config');
const wallabyWebpack = require('wallaby-webpack');
const webpack = require('webpack');

const { configure } = require('enzyme');
const Adapter = require('enzyme-adapter-react-16');

webpackConfig.entry = () => ['./index.js', 'test/setup.js'];

// eslint-disable-next-line max-len
webpackConfig.plugins.push(new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css)$/, 'node-noop'));

const wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = wallaby => ({
  files: [
    { pattern: ('test/setup.js'), load: false },
    { pattern: 'app/**/*.js*', load: false },
    { pattern: 'app/**/*.ts*', load: false },
    { pattern: 'app/**/*.spec.js*', ignore: true },
    { pattern: 'app/**/*.spec.ts*', ignore: true },
    { pattern: 'test/unit/**/*', load: false },
    // { pattern: ('test/unit/setup.js') },
    // { pattern: ('test/unit/_helpers/setup.js') },
  ],

  tests: [
    { pattern: 'app/**/*.spec.js*', load: false }
  ],

  compilers: {
    '**/*.js*': wallaby.compilers.babel(),
    '**/*.ts*': wallaby.compilers.typeScript(),
  },

  testFramework: 'mocha',
  debug: false,

  bootstrap() {
    // the files from my mocha.opts
    // require('babel-register');
    // require('ignore-styles');
    // console.log(window.__moduleBundler);
    // require('./test/unit/setup.js');
    // require('./test/unit/_helpers/setup.js');
    // require('tsconfig-paths/register');

    // required to trigger test loading
    window.__moduleBundler.loadTests();
  },

  postprocessor: wallabyPostprocessor,

  // env: { type: 'node', runner: 'node' },
  env: { kind: 'chrome' },
});
```

// Mocha.opts:

```
--require babel-register

--require ignore-styles

--require ./test/setup.js

--require ./test/unit/_helpers/setup.js

--require test/unit/setup.js

--compilers ts:ts-node/register

--require tsconfig-paths/register
```

### Code editor or IDE name and version

Visual Studio Code v1.35.1

### OS name and version

OSX

Any advice would  be greatly appreciated

**Comment by ArtemGovorov** [comment]
> I have tried using both webpack and not using webpack. 

The right way for you will be to run mocha with Wallaby in node without Webpack, because that is how you run mocha without Wallaby.

Based on your mocha.opts, this config should be close to working:

```js
module.exports = wallaby => ({
  files: [
    'tsconfig.json',
    'test/setup.js',
    'app/**/*.js*',
    'app/**/*.ts*',
    { pattern: 'app/**/*.spec.js*', ignore: true },
    { pattern: 'app/**/*.spec.ts*', ignore: true },
    'test/unit/**/*'
  ],

  tests: [
    'app/**/*.spec.js*'
  ],

  compilers: {
    '**/*.js*': wallaby.compilers.babel(),
    '**/*.ts*': wallaby.compilers.typeScript(),
  },

  testFramework: 'mocha',

  debug: true,

  setup() {
    // the files from my mocha.opts
    require('ignore-styles');
    require('./test/unit/_helpers/setup.js');
    require('./test/unit/setup.js');
    require('tsconfig-paths/register');
  },

  env: { type: 'node' },
});
```

Can you try the config and let us know what errors/issues are you getting with it?

**Comment by steveHornseyDeveloper** [comment]
Done, I had to comment out tsconfig.json as it was erroring with `Failed to run compilers on tsconfig.json`, am I right in thinking tsconfig.json is the default and will be picked up by wallaby without referencing it?

I now get errors for: 
`Cannot find module '../../../../../style/colors.scss'` 
`Cannot find module '~/components/_shared/icon/icon'`

All other resolutions seem to be working, I believe these do not work because they both use ~ as part of the file path. The source code colors.scss import statement is 
`import colors from '~/../style/colors.scss';`

**Comment by ArtemGovorov** [comment]
> I had to comment out tsconfig.json as it was erroring with Failed to run compilers on tsconfig.json

Looks like your compiler pattern is a bit too greedy, and tries to compile `.json` files. Please leave the `tsconfig.json` file, and change the compiler pattern to:

```diff
  compilers: {
-    '**/*.js*': wallaby.compilers.babel(),
+    '**/*.js?(x)': wallaby.compilers.babel(),
```


> I now get errors for:
> Cannot find module '../../../../../style/colors.scss'
> Cannot find module '~/components/_shared/icon/icon'

Looks like your files with styles are not in your Wallaby config `files` list. Try adding the file patterns in the list to see if it helps.

**Comment by steveHornseyDeveloper** [comment]
Progress!

I still get:
`Cannot find module '../../../../../style/colors.scss' 
  at Object.<anonymous> ​app/components/_shared/table-header/filters/filter-name.jsx:5​
  at Object.<anonymous> ​app/components/_shared/table-header/filters/filters.jsx:9​
  at Object.<anonymous> ​app/components/_shared/table-header/popup.jsx:8​
  at Object.<anonymous> ​app/components/_shared/table-header/heading.jsx:8​
`

These are surely all covered by ` 'app/**/*.js?(x)',` in:
`
  files: [
    'tsconfig.json',
    'test/setup.js',
    'app/**/*.js?(x)',
    'app/**/*.ts?(x)',
    { pattern: 'app/**/*.spec.js*', ignore: true },
    { pattern: 'app/**/*.spec.ts*', ignore: true },
    'test/unit/**/*'
  ],
`

One thing to note is the path used in the import statement is:
`import colors from '~/../style/colors.scss';`
which relates to `app/style/colors.scss` is the `~/../` part of the problem?

**Comment by ArtemGovorov** [comment]
> These are surely all covered by 'app/**/*.js?(x)', in:

They are actually not. The `app/**/*.js?(x)` pattern covers `.js`/`.jsx` files, but not `.scss`, hence the error. As [specified in our docs](https://wallabyjs.com/docs/config/files.html), all files used in your app/tests need to be in the `files`

```diff
  files: [
    'tsconfig.json',
    'test/setup.js',
    'app/**/*.js*',
    'app/**/*.ts*',
+   'app/**/*.scss',
    { pattern: 'app/**/*.spec.js*', ignore: true },
    { pattern: 'app/**/*.spec.ts*', ignore: true },
    'test/unit/**/*'
  ],
```

**Comment by steveHornseyDeveloper** [comment]
IT WORKS!!!

Many thanks for your help, I've spent a long time looking at this and probably should have asked sooner!

**Comment by steveHornseyDeveloper** [comment]
For anyone looking at this, final config was:
```

module.exports = wallaby => ({
  files: [
    'style/*.scss',
    'tsconfig.json',
    'test/setup.js',
    'app/**/*.js?(x)',
    'app/**/*.ts?(x)',
    { pattern: 'app/**/*.spec.js*', ignore: true },
    'test/unit/**/*',
  ],

  tests: [
    'app/**/*.spec.js?(x)'
  ],

  compilers: {
    '**/*.js?(x)': wallaby.compilers.babel(),
    '**/*.ts*': wallaby.compilers.typeScript(),
  },

  testFramework: 'mocha',

  debug: true,

  setup() {
    // the files from my mocha.opts
    require('ignore-styles');
    require('./test/setup.js');
    require('./test/unit/_helpers/setup.js');
    require('./test/unit/setup.js');
    require('tsconfig-paths/register');
  },

  env: { type: 'node' },
});
```
