### ISSUE TITLE
Feature Request: Allow config to set `workers` and rely on auto config for the rest

### ISSUE THREAD

**Issue by ha404** [wallabyjs/public#2152]
### Issue description or question

I was hoping to only use the `workers` config in conjunction with the auto config so that I can limit the resources Wallaby uses:
```
workers: {
  initial: 2,
  regular: 2,
  restart: true,
},
```

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test';

module.exports = (wallaby) => {
  return {
    files: [
      'testing/**/*.js',
      'src/**/*.js',
      '__mocks__/**/*.js',
      '!src/**/__tests__/*.js',
      'src/**/*.gql',
    ],
    tests: ['src/**/__tests__/*.js'],
    workers: {
      initial: 2,
      regular: 2,
      restart: true,
    },
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js*': wallaby.compilers.babel(),
    },
    debug: true,
  };
};

```

### Code editor or IDE name and version

Visual Studio Code Version 1.36.1 (1.36.1)
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

OSX 10.14.5

**Comment by smcenlly** [comment]
This is possible today ([described in our docs](https://wallabyjs.com/docs/intro/config.html#overriding-automatic-defaults)):

> In order to override any defaults, you may use Wallaby Configuration file or wallaby section in your package.json file, specify the autoDetect: true setting and then any Wallaby settings that you want to add/override.

In your case, your configuration file would look like:

```javascript
module.exports = () => ({
  autoDetect: true,
  workers: {
    initial: 2,
    regular: 2,
    restart: true,
  },
});
```

I would also be careful setting `restart` to `true` unless you know that you need it. Setting `restart` to true is great if you need it, but you may find that you don't need it anymore with automatic configuration.
