### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by ovidubya** [wallabyjs/public#2156]
### Issue description or question

getting this error:
`Uncaught ReferenceError: exports is not defined 
at http://localhost:56442/src/SomethingBrowser.js?1564173049078&wallabyFileId=3:3`

I have a repo here: https://github.com/ovidubya/wallaby-javascript-with-typescript
with JS and TS files and im trying to get the tests to work. 

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

  return {
    files: [
      'src/*Browser.ts',
      'src/*Browser.js'
    ],

    tests: [
      'test/*BrowserSpec.ts',
      'test/*BrowserSpec.js'
    ]
  };
};

```

### Code editor or IDE name and version

Version 1.36.1 (1.36.1)

### OS name and version
OSX Mojave

**Comment by ArtemGovorov** [comment]
Looks like you are trying to use ES modules, and in the repo TypeScript is set to compile to `CommonJs` modules, hence the error. To make it work, you may extend your repo to use Webpack with [this Wallaby config](https://wallabyjs.com/docs/integration/webpack.html) (need to set your paths in that config), or switch from using browser environment to [node](https://wallabyjs.com/docs/integration/node.html), or use [Wallaby with Jest](https://wallabyjs.com/docs/integration/jest.html).

**Comment by dht** [comment]
Installing ts-jest also helped in my case:

```
yarn add --dev jest typescript
yarn add --dev ts-jest @types/jest
yarn ts-jest config:init
yarn jest (to verify)
```

And then start `wallaby` with an autoDetect configuration:
```
module.exports = function (wallaby) {
    return {
        autoDetect: true,
    };
};
```
