### ISSUE TITLE
Run  angular directive tests when their html template file changes

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#216]
We use [wallaby-ng-html2js-preprocessor](https://github.com/sheltonial/wallaby-ng-html2js-preprocessor) to test our directives that use HTML templates, and it works great.

However, I discovered that changes in the template file doesn't cause the directive tests to run, probably because it is not source code file, so Wallaby doesn't mark it as affecting the directive test.

Can you make wallaby detect changes to html template used by a directive, and run tests that uses that directive?

**Comment by ArtemGovorov** [comment]
There're some heuristics that can make it work to some extent. Please have a [look here for more details](https://github.com/wallabyjs/public/issues/183#issuecomment-119778325).

We are also planning to implement an option to automatically run all tests if wallaby can't figure out what tests to run.

**Comment by splintor** [comment]
OK, thanks.
