### ISSUE TITLE
Failed to load configuration file: Incompatible Jest version: Module jest-cli is not found in D:\Repos\Mapr

### ISSUE THREAD

**Issue by KiransHub** [wallabyjs/public#2160]
### Issue description or question
Using the new automatic configuration I get the error: 

Failed to load configuration file: Incompatible Jest version: Module jest-cli is not found in D:\Repos\Mapr

With a new angular 8 project. 

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.36
### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Right now only Jest testing framework (from v24) is supported to work without Wallaby configuration.

By default, Angular ships with karma as its test runner, unless you've changed the project to use jest.

From the error, and from your description, `new angular 8 project`, this behavior is expected.

If you haven't already done so, please refer to our [docs for Angular 8 Wallaby.js configuration](https://wallabyjs.com/docs/integration/angular.html#angular-cli).
