### ISSUE TITLE
Wallaby and Nestjs

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#2161]
@### Issue description or question
Will wallby work with typescript and nestjs nodejs backend?

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Please provide a sample repo demonstrating the issue, we are happy to take a look and help with the config.

**Comment by scriptsure** [comment]
Artem sorry I was just researching new tools for a new project. I know if I code nodejs using typescript it will work. But was also wondering about nestjs?

**Comment by smcenlly** [comment]
@scriptsure - took a look at nestjs, it's using Jest 24+ so testing should be fully supported.
