### ISSUE TITLE
jest setupFiles not extending expect in v1.0.712

### ISSUE THREAD

**Issue by JM-Mendez** [wallabyjs/public#2163]
### Issue description or question

wallaby isn't extending the jest object found in my jest config under `setupFilesAfterEnv`. I saw https://github.com/wallabyjs/public/issues/2067, but since that was from May 2019 and the issue was resolved with a previous version, I created a new issue.

It works normally when run from the terminal, and I have tried deleting the cache and reinstalling wallaby to no avail.

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
   const config = {
      files: [
         'src/**',
         '!src/**/*.spec.{ts,tsx}',
         'jest/**/*{ts,js}',
         '!src/**/*.stories.{ts,tsx}',
         './tsconfig.json'
      ],
      tests: ['src/**/*.spec.{ts,tsx}', '!src/**/performance.spec.{ts,tsx}'],
      filesWithNoCoverageCalculated: [
         'jest/**/*',
         'src/**/stubs/*',
      ],
      compilers: {
         '**/*{js,jsx,ts,tsx}': wallaby.compilers.babel()
      },
      slowTestThreshold: 300,
      testFramework: 'jest',
      debug: false,
      hints: {
         ignoreCoverageForFile: 'wallaby ignore file',
         ignoreCoverage: 'wallaby ignore next'
      },
      env: {
         type: 'node',
         runner: require('electron'),
         params: {
            env: 'ELECTRON_RUN_AS_NODE=true'
         }
      },
      setup: () => {
         require('./jest/jest.config')
      }
   }
}
```

### Code editor or IDE name and version

Visual Studio Code  v1.36.1

### OS name and version

OSX 10.14.5

**Comment by smcenlly** [comment]
Am I correct in assuming that your `jest.config` file is not in your project root? (looks like it's in your `jest` directory). If this is the case, it's possible that Wallaby isn't finding/using your jest configuration, in which case, you might have to explicitly pass it to wallaby in your setup function like this:

```
...
  setup: function (wallaby) {
    const jestConfig = require('./jest/jest.config');
    wallaby.testFramework.configure(jestConfig);
  }
...
```

**If you are using Jest v24+**, you may also like to try our new [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) feature, which will allow you to run your jest tests without any wallaby configuration.

--

If this doesn't help, can you please provide us with your `package.json`, and `jest` configuration files?

**Comment by JM-Mendez** [comment]
> you might have to explicitly pass it to wallaby in your setup function 

Thank you. This was exactly the issue. Since I use typescript I also had to modify the extensions in `setupFiles` and `setupFilesAfterEnv` since `wallaby` couldn't find them after instrumentation. 

This is my working setup function:

```js
setup: () => {
   const toJsExt = (file) => file.replace('.ts', '.js')
   const jestConfig = require('./jest/jest.config')

   jestConfig.setupFiles = jestConfig.setupFiles.map(toJsExt)
   jestConfig.setupFilesAfterEnv = jestConfig.setupFilesAfterEnv.map(toJsExt)

   wallaby.testFramework.configure(jestConfig)
}
```
