### ISSUE TITLE
Wallaby does not apply mock, but jest does

### ISSUE THREAD

**Issue by mralj** [wallabyjs/public#2164]
### Issue description or question
I have this piece of code:

```
import { View as mockForValuePicker } from "react-native";

jest.mock("src/components/exerciseValuePicker/ExerciseValueEditorPicker", () => ({
  ExerciseValueEditorPicker: () => <mockForValuePicker />
}));

describe("ExerciseValueEditorPicker tests", () => {
  let reduxStore: Store<IReduxState, AnyAction>;

  it("should render correctly and match snapshot", () => {
    const { toJSON } = renderWithRedux(
      <Exercise  />,
      reduxStore
    );

    expect(toJSON()).toMatchSnapshot();
  });
....
});
```

The problem is that Wallaby isn't applying mock, meaning that whole component `ExerciseValueEditorPicker` gets rendered and saved in snapshot. 

Snapshot generated through Jest CLI, works as expected, instead of `ExerciseValueEditorPicker` component, `mockForValuePicker` gets rendered.

If I put `mock` code  in file defined in Jest config:

```
 "setupFilesAfterEnv": [
      "<rootDir>/src/__test__/testsSetup.js"
    ]
```
(ie. `testsSetup.js` file)

Then Wallaby works same way as Jest.

 ### Wallaby.js configuration file

```
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js",
      "src/**/*.ts",
      "src/**/*.tsx",
      "src/**/*.png",
      "src/**/*.jpg",
      "src/**/*.mp4",
      "!src/**/*.test.tsx",
      "!src/**/*.test.ts",
      "!src/**/*.test.js",
      "!src/**/__tests__/*.ts",
      "babel.config.js"
    ],

    tests: ["src/**/*.test.ts", "src/**/*.test.js", "src/**/*.test.tsx"],

    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
    lowCoverageThreshold: 70
  };
};

```

### Jest config

```
 "jest": {
    "preset": "react-native",
    "modulePaths": [
      "<rootDir>"
    ],
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "testPathIgnorePatterns": [
      "\\.snap$",
      "<rootDir>/node_modules/",
      "<rootDir>/__tests__/",
      "<rootDir>/.history/"
    ],
    "transformIgnorePatterns": [
      "node_modules/?!(react-native|native-base)"
    ],
    "cacheDirectory": ".jest/cache",
    "globals": {
      "__TEST__": true
    },
    "setupFilesAfterEnv": [
      "<rootDir>/src/__test__/testsSetup.js"
    ]
  }
```

### Code editor or IDE name and version

Visual Studio Code v1.36.1

### OS name and version

OSX 10.14.5

**Comment by smcenlly** [comment]
When `jest` runs, it automatically transpiles your code with `babel`, which is where your jest mocks are hoisted. You will need to update your wallaby configuration so that babel runs as a compiler. There's an example of this in our  [react docs](https://wallabyjs.com/docs/integration/react-jsx.html), for example:

```javascript
...
      compilers: {
          '**/*.js?(x)': wallaby.compilers.babel({
              presets: ['react-app']
          })
      },
...
```

**If you are using Jest v24+** you may switch to use our [Automatic Configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration), which will allow you to delete your wallaby.js file, and will correctly apply your mocks without you having to do anything.
