### ISSUE TITLE
Wallaby applies file filters to realpaths not logical paths anymore

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2166]
### Issue description or question

None of my tests are being found. They were before some change to Wallaby.

I think this message is the culprit:

```
wallaby:fs File system scan has finished by timeout
```

Is the timeout configurable?

Maybe its related to my use of symlinks.

I noticed this line in the logs too:

```
Possible symlink: foo
```

What is the purpose of this?

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
**IntelliJ IDEA v?**
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
**OSX**
Linux

**Comment by vjpr** [comment]
I have a symlink like so: `/xxx/packages/public -> /xxx/packages/public-symlink`

## No files detected

```
module.exports = {
  debug: true,
  files: ['packages/public-symlink/**/*.js'],
  tests: ['packages/public-symlink/**/*.test.js'],
}
```

```
wallaby:fs Possible symlink: /xxx/packages/public -> /xxx/packages/public-symlink
```

## Works

```
module.exports = {
  debug: true,
  files: ['packages/public/**/*.js'],
  tests: ['packages/public/**/*.test.js'],
}
```

**Comment by vjpr** [comment]
Also, when using an `OR` glob like `(public|foo)`:

```
files: ['packages/(public|foo)/**/*.js']
```

I am getting:

```
Possible symlink: /root -> /root
```

**Comment by ArtemGovorov** [comment]
> So it looks like you are resolving symlinks to real paths now before applying filter patterns.

Yes, it was the case in our new implementation (for symlinks to something inside the wallaby root). We have pushed the change to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), so it should now work for you.

**Comment by vjpr** [comment]
I'm using core v1.0.713 and I see no difference.

**Comment by ArtemGovorov** [comment]
To test the solution, I have created a simple project with the following config

```js
module.exports = {
  debug: true,
  files: ['packages/public-symlink/**/*.js', '!packages/public-symlink/**/*.test.js'],
  tests: ['packages/public-symlink/**/*.test.js'],
}
```
with a symlink `packages/public -> packages/public-symlink` and a simple test `packages/public/a.test.js`. When I run the config, it finds and runs the `packages/public/a.test.js` test as expected.

**Comment by vjpr** [comment]
Okay that seems to work.

However when using `'packages/**/*.js'` and excluding `public`, the `public` dir is not excluded, and files in both `public-symlink` and `public` are added.

```
module.exports = {
  debug: true,
  files: ['packages/**/*.js', '!packages/public/**'],
  tests: ['packages/public-symlink/**/*.test.js'],
}
```

**Comment by vjpr** [comment]
Also just to clarify...the symlink I have is `packages/public-symlink (the symlink / target_file) -> packages/public (source_file)`.

**Comment by ArtemGovorov** [comment]
> Also just to clarify...the symlink I have is `packages/public-symlink (the symlink / target_file) -> packages/public (source_file)`.

Yep, I have the same in my sample, fixed my comment. 

> the `public` dir is not excluded, and files in both `public-symlink` and `public` are added.

The files are added to Wallaby cache as a part of the symlink resolution, and while we may change it in future, ideally it should not affect your test runs - are you experiencing any issues with actual test runs?

**Comment by ArtemGovorov** [comment]
There's one potential issue I can see (tests from `public` may run), but the solution in this case is:

```js
module.exports = {
  debug: true,
  files: [
    'packages/**/*.js', 
    '!packages/public/**', 
    '!packages/**/*.test.js'
  ],
  tests: ['packages/public-symlink/**/*.test.js', '!packages/public/**'],
}
```

**Comment by vjpr** [comment]
> The files are added to Wallaby cache as a part of the symlink resolution

This has a big speed impact for me because it will end up copying the same files 3 times (public, public-symlink, public-local).

**Comment by vjpr** [comment]
Why doesn't this pattern work:

Works
`packages/(public-symlink|org-symlink)/**/*.js`

Not working
`packages/public-symlink/**/*.js`

**Comment by vjpr** [comment]
> The files are added to Wallaby cache as a part of the symlink resolution

Do you mean that when it says `wallaby:fs File added:`, this does not mean that it actually matched a `file` or `test` pattern...but rather it is so that it can resolve symlinks?

**Comment by ArtemGovorov** [comment]
> Is it that you have code to detect symlinks?

Pretty much, but we are planning to change it. However, the implementation detail should not affect user experience much. While there's some excessive copying is involved, actual copying only happens once, then results are cached (and when you restart Wallaby or switch symlinks - no more copying happens).

**Comment by vjpr** [comment]
1. What is the reason for symlink detection?

2. I managed to workaround it. My patterns must begin with symlinked dirs to avoid the excessive copying. I end up tweaking my wallaby config often, which invalidates the cache, so I would feel the excessive copying often.

**Comment by ArtemGovorov** [comment]
> What is the reason for symlink detection?

Limitation of the file watcher library version that we are using.
