### ISSUE TITLE
`TypeError [ERR_MISSING_ARGS]: The "message" argument must be specified`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2167]
### Issue description or question

```
(node:31111) UnhandledPromiseRejectionWarning: TypeError [ERR_MISSING_ARGS]: The "message" argument must be specified
    at process.target._send (internal/child_process.js:691:13)
    at process.target.send (internal/child_process.js:676:19)
    at /Users/Vaughan/Library/Caches/IntelliJIdea2019.2/wallaby/wallaby/server.js:23:14400
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
**IntelliJ IDEA v?**
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
**OSX**
Linux

**Comment by ArtemGovorov** [comment]
- Is the issue reproduced if you restart Wallaby/IDE?
- Can you share your Wallaby config?
- Could you please try running this sample repo https://github.com/wallabyjs/wallaby-jest-snapshots to see if the issue is reproduced in it?

**Comment by ArtemGovorov** [comment]
The issue is likely related to one of your Wallaby config compilers/preprocessors incorrectly returning results for some reason.

**Comment by ArtemGovorov** [comment]
Also, what is displayed in the Wallaby Failing Tests tab when the error occurs?

**Comment by vjpr** [comment]
I cannot seem to reproduce anymore. There should be a friendlier error message shown. Will update issue if I see it again.

**Comment by ArtemGovorov** [comment]
>  There should be a friendlier error message shown. 

I think a friendlier message was displayed, but in Wallaby Failing Tests tab (not in the console tab) - have you checked Wallaby Failing Tests tab? Let us know if you hit the issue again.

**Comment by GladunovDenis** [comment]
I had similar error message using paralleljs: 
```js
internal/child_process.js:691
      throw new ERR_MISSING_ARGS('message');
      ^

TypeError [ERR_MISSING_ARGS]: The "message" argument must be specified
    at process.target._send (internal/child_process.js:691:13)
    at process.target.send (internal/child_process.js:676:19)
    at process.eval (eval at <anonymous> (C:\Users\username\node_modules\paralleljs\lib\eval.js:7:5), <anonymous>:12:71)
    at process.emit (events.js:223:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ERR_MISSING_ARGS'
}
```

After debugging for a while i found out that the error appears only if i return nothing in .spawn callback.
```js
// THIS THROWS AN ERROR
new Parallel(1000).spawn(function (data){
    const something = data;
}).then(console.log);

// THIS WORKS OK
new Parallel(1000).spawn(function (data){
    const something = data;
    return something;    
}).then(console.log);
```

**Comment by smcenlly** [comment]
@GladunovDenis - What error do you get when running the same code outside of Wallaby?

**Comment by GladunovDenis** [comment]
> I had similar error message using paralleljs:
> 
> ```
> internal/child_process.js:691
>       throw new ERR_MISSING_ARGS('message');
>       ^
> 
> TypeError [ERR_MISSING_ARGS]: The "message" argument must be specified
>     at process.target._send (internal/child_process.js:691:13)
>     at process.target.send (internal/child_process.js:676:19)
>     at process.eval (eval at <anonymous> (C:\Users\username\node_modules\paralleljs\lib\eval.js:7:5), <anonymous>:12:71)
>     at process.emit (events.js:223:5)
>     at emit (internal/child_process.js:876:12)
>     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
>   code: 'ERR_MISSING_ARGS'
> }
> ```
> 
> After debugging for a while i found out that the error appears only if i return nothing in .spawn callback.
> 
> ```js
> // THIS THROWS AN ERROR
> new Parallel(1000).spawn(function (data){
>     const something = data;
> }).then(console.log);
> 
> // THIS WORKS OK
> new Parallel(1000).spawn(function (data){
>     const something = data;
>     return something;    
> }).then(console.log);
> ```

Excuse me. This happened outside Wallaby.
