### ISSUE TITLE
Wallaby config evaled many times

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2168]
### Issue description or question

I want to print the files/tests patterns only once when Wallaby starts in the IDE.

However, when I add a log to the config, I'm seeing it run once, then a lot of `File added`, and then its logging like 16 times.

Is this normal?

How would I log something only once during a Wallaby run?

```
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #5
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #1
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #2
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #0
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #3
Fri, 02 Aug 2019 21:29:20 GMT wallaby:workers Started run worker instance (delayed) #4
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
WALLABY CONFIG RAN!
```

---

I'm thinking I can do something like:

```js
fs.writeFileSync(join(wallaby.projectCacheDir, '__wallaby'), +new Date, 'utf8')

process.on('exit', () => {
    console.log('Wallaby main process exiting.')
    // Remove temp file...
  })
```

But this is brittle - say if process 'exit' never runs because of IDE crash.
And it also runs many times after the files are added and tests start running.

Is there any unique identifier for an IDE session?

**Comment by ArtemGovorov** [comment]
> Is this normal?

Yes, Wallaby config is loaded from parallel worker processes that will be compiling files with Babel/TypeScript/preprocessors in parallel, to read Babel/TypeScript/preprocessors settings.

> How would I log something only once during a Wallaby run?

```js
(process.argv[2] !== 'worker') && console.log('Should be logged once');
```

> I'm thinking I can do something like:

If possible in your case, a better place to do it is [the `setup` function](https://wallabyjs.com/docs/config/bootstrap.html). There are some identifiers you may use there (test run id, test worker id), and to make sure your code executes once per worker process you may use some `global.myVar` variables to set/check.

> But this is brittle - say if process 'exit' never runs because of IDE crash.

Correct, but unfortunately there's not much we can do about it (neither can other testing frameworks where a test run can be interrupted by a starting host/CLI). The best way is to ensure that the file is in the right state prior to running your tests (regardless of whether or not it had been deleted afterwards).
