### ISSUE TITLE
Wallaby sometimes complains about license issues when multiple windows are open on same machine

### ISSUE THREAD

**Issue by fr0** [wallabyjs/public#2169]
### Issue description or question

<img width="378" alt="Screen Shot 2019-08-05 at 10 13 43 AM copy" src="https://user-images.githubusercontent.com/435418/62471165-10560500-b76a-11e9-95de-879d676ee29a.png">

The machine name and IP address are the local machine.

This happens about once per day.

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

OSX 10.13.6

**Comment by smcenlly** [comment]
Is it possible that your network adapters are changing throuhgout the day? e.g. you connect/disconnect from a wireless network, or from a wired network?

Could you please send an email with your license key to hello@wallabyjs.com? We should be able to provide you with a fix.
