### ISSUE TITLE
Link in README.txt in wallaby-intellij downloaded zip is incorrect

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#217]
When you download wallaby from the link http://download.wallabyjs.com/intellij, the downloaded zip contians wallaby-intellij\lib\wallaby-intellij.jar and README.txt.
The readme file says you need to follow the instructions at https://github.com/wallabyjs/public#getting-started - but there are no installation instructions in that page.
It should point to http://wallabyjs.com/docs/intro/install.html

**Comment by ArtemGovorov** [comment]
Good find, thanks. Fixed the link, should be correct starting from the next version.
