### ISSUE TITLE
Error: One of your tests is trying to unload window object.

### ISSUE THREAD

**Issue by fr0** [wallabyjs/public#2170]
### Issue description or question

I'm trying to test how my app response to the `beforeunload` event, so I have this line:

```
window.dispatchEvent(new Event('beforeunload'));
```

Unfortunately wallaby throws an error here. It works fine in Karma.

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

OSX 10.13.6

**Comment by smcenlly** [comment]
Wallaby runs your tests in parallel and only executes tests that are impacted by your current code changes. This means that some tests may not execute, or they will run in a different order from time to time. 

Wallaby subscribes to the window `beforeunload` event and throws the above mentioned error. Unloading the window with the parallel executions and non-deterministic order of tests may cause tests to not execute and you won't know about it (hence why we report the error).

If you're able to give us a sample, and tell us a little more about your use case, we'd be happy to investigate further and provide advice on whether this is possible in wallaby. Without knowing more detail, it's possible that this will also cause problems for `Karma` (e.g. subsequent tests), but we can't say for sure.

**Comment by fr0** [comment]
The short version: map app saves data to `localStorage`, but has a debounce timer so that changes in quick succession will wait until there is a certain amount of time elapsed with no changes before doing the save. This is for performance purposes to avoid constant calls to `JSON.stringify` and `localStorage.setItem`.

It short-circuits this debounce when the `beforeunload` event happens. If there are pending changes during `beforeunload`, they're written immediately.

```javascript
window.addEventListener('beforeunload', () => {
  if (this.pendingChanges) {
    this.save();
  }
});
```

I'm trying to write unit tests for this behavior. My first thought was to use...

```javascript
// <code here that makes changes>
window.dispatchEvent(new Event('beforeunload'));
// <code here that checks localStorage>
```

...in my unit test, and was surprised when the error was thrown by wallaby, since the tests pass in Karma.

**Comment by ArtemGovorov** [comment]
By default, Karma is [also throwing the error](https://github.com/karma-runner/karma/blob/master/client/karma.js#L105). Not sure why in your case Karma doesn't do it, maybe because some of the code that you are using deliberately or accidentally is using [this workaround](https://github.com/karma-runner/karma/issues/1062#issuecomment-42421624).

To support the scenario, we have introduced a new setting in [the latest Wallaby Core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), that you may use to stop Wallaby reporting the error:

```diff
module.exports = function (wallaby) {
  ...
  return {
    ...
+   throwOnBeforeUnload: false
  };
};
```
