### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#2172]
### Issue description or question

Feature Request;

The live test filtering in jest is pretty awesome (apart from being the slowest pain in my a$$).

Would you consider to include live test filtering inwallaby? Filter by test name or by file name would be great.

I know how to do it with wallaby Config, but live would be too good ;))

**Comment by smcenlly** [comment]
@tomitrescak - are you able to provide some additional details?

* What do you mean by "live test filtering"? Are you using `jest` with the `--runTestsByPath` option?
* If "filtering" by test name, what would you expect to happen? To see or be taken to the associated test?

I am guessing that you are already aware of [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html) and that the filtering/behavior provided by Wallaby App is different to what you're looking for?

As an aside, if you're using jest, and have v24+, you may benefit from the [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) feature we recently released. This allows you to use wallaby with jest without a wallaby.js configuration file.

**Comment by ArtemGovorov** [comment]
Also, have you see our [test selection feature](https://wallabyjs.com/docs/intro/selected-tests.html)?

**Comment by smcenlly** [comment]
@tomitrescak - I hope our responses gave you what you were looking for. Since we haven't heard back, I'm going to close this ticket, but feel free to reply and we will re-open it.

**Comment by tomitrescak** [comment]
Simon, sorry for the lack of reply. I’ll have time to check your kind advice tomorrow. If there will be anything I miss I will reopen the ticket. Have a lovely day.

**Comment by tomitrescak** [comment]
I just read Artem’s response and it is EXACTLY what I wanted. Great job as usual ;)
