### ISSUE TITLE
Max 99 tests in free trial?

### ISSUE THREAD

**Issue by YousefED** [wallabyjs/public#2174]
### Issue description or question
Could it be Wallaby runs a maximum of 99 tests in the free trial?

![image](https://user-images.githubusercontent.com/368857/62826586-72759680-bbbe-11e9-97d7-1af8d6714ecf.png)

But I'm missing a lot of other tests

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    process.env.NODE_ENV = "test";

    return {
        files: [
            "src/**/*.ts",
            "@client/**/*.ts",
            "@shared/**/*.ts",
            "!@client/node_modules/**/*.ts",
            "test/data/**/*",
            "test/__snapshots__/**/*",
            "test/__mocksnapshots__/**/*",
            "bin/**/*"
        ],

        tests: ["test/**/*.ts"],
        testFramework: "jest",
        env: {
            type: "node"
        },

        compilers: {
            "**/*.ts?(x)": wallaby.compilers.typeScript({ module: "commonjs" })
        },
        debug: false,
        maxLogEntrySize: 1000
    };
};

```

### Code editor or IDE name and version

Visual Studio Code 

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
There's no such limitation in our trial version. However, Wallaby runs tests in parallel groups and when some tests/test files in one of the groups fail (like dependency load or other global kind of errors), it may stop other tests in the group from running and being reported. I'd suggest investigating why other tests are failing, and fixing the reason may get Wallaby to report/run the rest of your tests.

Also, if you are using Jest v24 or higher, we recommend you try [our config-less feature](https://wallabyjs.com/docs/intro/config.html#automatic-configuration).

**Comment by YousefED** [comment]
Thanks @ArtemGovorov . Figured it out after making all the tests working.

This was a bit confusing though. It would be extremely helpful if the UI would always show all tests (not just those that passed or failed). E.g.:

- show which tests are pending (running)
- show which tests have been skipped (for example by it.skip, or dropped because of the reason above)

This would also be more inline with other unit test tooling and with my expectations as a user.
