### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by elmizan** [wallabyjs/public#2176]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.138`
- OS Version: `Linux x64 5.0.0-23-generic`
- VSCode version: `1.37.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/codingnt/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by smcenlly** [comment]
@elmizan - could you please attach the cpuprofile referenced in the issue?

> /home/codingnt/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt

**Comment by smcenlly** [comment]
Closing this issue. We require more information and have not been able to duplicate.
