### ISSUE TITLE
Multiple markers in left margin in IntelliJ

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#218]
When I set the `Libraries in Scope` - click the Yeoman-like icon at the right bottom of the window - while Wallaby is running, there are markers added to the editor, resulting in two columns of markers. The added markers are grey (no coverage).
Everytime I repeat this step, there are new markers added.

**Comment by ArtemGovorov** [comment]
@fvanwijk I have tried reproducing it on WS 9.0.3, 10.0.4, 11 EAP, no luck yet. Here is what I do:

![f](https://cloud.githubusercontent.com/assets/979966/8921974/2ed34810-3520-11e5-87f8-6789c68364ca.gif)

It just re-runs test(s) and re-draws the markers for me. Am I missing some actions or are you doing it somehow differently? What's your IDE build version?

**Comment by fvanwijk** [comment]
IntelliJ IDEA 14.1.4 Build #IU-141.1532

What I did was about the same as what you are showing. I clicked 'Manage scopes', added `jasmine-DefinitelyTyped` to the 'test/spec' dir. Press OK twice. Al column of markers is added to all instrumented files, even after closing and opening them.

Then repeat the steps, remove `jasmine-DefinitelyTyped` from the 'test/spec' dir. Another column of markers is added.

However... I'm just repeating your steps: When I just click 'Node.js' and 'ECMAScript 6', this also happens :)

**Comment by ArtemGovorov** [comment]
Tried the 141.1532 build, still no luck. I'm trying on OSX, please remind what's your OS?

**Comment by fvanwijk** [comment]
OSX Yosemite 10.10.4 (14E46)

**Comment by ArtemGovorov** [comment]
Could you please paste the content of the idea.log file (Help - Show Log...) for the time when you reproduce the issue?

**Comment by fvanwijk** [comment]
2015-07-29 08:26:42,409 [582329134]   INFO - indexing.UnindexedFilesUpdater - Indexable files iterated in 72 ms 
2015-07-29 08:26:42,409 [582329134]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update started: 1 files to update 
2015-07-29 08:26:42,419 [582329144]   INFO - indexing.UnindexedFilesUpdater - Unindexed files update done in 10 ms 
2015-07-29 08:26:43,177 [582329902]   INFO - hint.version.JSHintVersionUtil - JSHint 2.7.0 is loaded from classpath 
2015-07-29 08:26:43,259 [582329984]   INFO - ter.rhino.RhinoFunctionManager - [ApplicationImpl pooled thread 676] JSHINT 2.7.0 script rhino compilation took 77.16 ms

**Comment by ArtemGovorov** [comment]
When you open About IDEA dialog, what JRE version does it display in there?

**Comment by fvanwijk** [comment]
1.6.0_65 (64bit).
I have 1.7 and 1.8 also installed, I takes an old version. I will try to see how these newer versions behave.

**Comment by nikolaymatrosov** [comment]
Got similar bug. Windows + WebStorm 11 EAP.
Tried to search in files (ctrl+shift+f)
![2015-08-07_1327](https://cloud.githubusercontent.com/assets/1625055/9130951/d555461c-3d08-11e5-8841-a109352ec9bf.png)
In search results double clicked on file. And got double markers.
![wallaby](https://cloud.githubusercontent.com/assets/1625055/9130970/fc5a3a1a-3d08-11e5-83c6-943a8aa4f73f.png)
Closed file. Clicked in search again. Got triple markers. Maximum I can get 5 in row.
![2015-08-07_1329](https://cloud.githubusercontent.com/assets/1625055/9130949/d10b656e-3d08-11e5-8276-9e13e67b3098.png)

**Comment by ArtemGovorov** [comment]
The issue is fixed in IntelliJ plugin v1.0.26.
