### ISSUE TITLE
Add file name related to "Error: Your test suite must contain at least one test."

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2180]
### Issue description or question

The error message in `Failint Tests` tab "Error: Your test suite must contain at least one test." is related to a specific file, but the file name without tests is not in the message. To get the file name it need to switch to `Wallaby Console` tab that can already be flooded with other messages

So it would be nice to see the file name(s) this error relates to in `Failing Tests` tab inside of error message or near it

### Wallaby.js configuration file

Autoconfig for Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

**Comment by smcenlly** [comment]
Thanks for your issue. I've marked as a feature request.

**Comment by smcenlly** [comment]
We've updated our error reporting to prefix the filename associated with global errors when available. This is available in Wallaby Core v1.0.722 and works for the error `Your test suite must contain at least one test.`

Wallaby should update automatically the next time you restart. If it doesn't update automatically, you may [force an update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
