### ISSUE TITLE
Wrong Wallaby version number in Webstorm Settings

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2182]
### Issue description or question

I have installed a plugin by downloading a `wallaby-intellij-v1.0.136.zip` from the official site. On the first run, it was updated to the last version. But if I open Settings -> Plugins and search in installed for Wallaby it shows me the same 1.0.136

### Wallaby.js configuration file

Autoconfig with Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

**Comment by ArtemGovorov** [comment]
Current Webstorm Wallaby plugin version is 1.0.136. Probably what was updated was [Wallaby Core](https://wallabyjs.com/docs/intro/how-it-works.html#plugin-and-core), that is versioned and updated separately from the plugin. Current Wallaby Core version (printed in Wallaby Console when it starts) is v1.0.721.

**Comment by Alexsey** [comment]
Got it, thank you for a fast reply!
