### ISSUE TITLE
In WebStorm, Wallaby doesn't respect it's Notification settings

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2184]
### Issue description or question

Even though `Wallaby Expiring License` Notification is disabled, it's pop-up on every Wallaby start (see screenshot)

It's annoying

### Wallaby.js configuration file

Autoconfig with Jest 24.9

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows Pro 10
![notifications](https://user-images.githubusercontent.com/6392013/63362066-ea3f8000-c379-11e9-80ea-4180f6d6beff.png)

**Comment by smcenlly** [comment]
I tested this using the same version of WebStorm and the latest version of Wallaby and everything is working for me. If your notification settings match your screenshot, then you haven't actually disabled the notification.

WebStorm logs notifications to the `Event Log` and optionally via a popup. In your case, you've disabled the `Event Log` but **not** the popup. You can fix this a couple of ways:

1) Expand the Wallaby License message popup message, scroll down, and select `Mute Notification`.
2) Open your WebStorm notification settings, for the `Wallaby Expiring License` notification, select the dropdown beside `Sticky balloon` and change it to `None`.

**Comment by Alexsey** [comment]
You are correct - it was my mistake. Thank you for pointing this out
