### ISSUE TITLE
/deep/ Expected selector

### ISSUE THREAD

**Issue by chrisj-skinner** [wallabyjs/public#2185]
Hi,

I'm get the following error when running wallaby.

![Screen Shot 2019-08-20 at 14 56 12](https://user-images.githubusercontent.com/5794048/63353500-bef96880-c35a-11e9-979f-3317780daf83.png)

Appears to be associated with `/deep/`

Running on a CLI build of Angular 8
I am not able to share this via a repo.

I have commented out all instances of `/deep/` and I have wallaby working correctly. What do I need to do to get it working with the use of `/deep/`

Thanks

**Comment by smcenlly** [comment]
I added [`deep`](https://www.npmjs.com/package/deep) as a dependency of our [ngCliWebpackSample](https://github.com/wallabyjs/ngCliWebpackSample), imported and used it in a test and everything is working.

Can you please provide an example of how you're using it? Would you be able to try cloning our [ngCliWebpackSample](https://github.com/wallabyjs/ngCliWebpackSample) and adding a sample that breaks in the same way?

**Comment by NikGovorov** [comment]
Hi @chrisj-skinner,

`deep` is not supported by [sass](https://github.com/sass/dart-sass/issues/154#issuecomment-307240458).

If you want to keep using the selector then you need to switch to legacy `node-sass` by changing line 129 in [wallaby.js](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L129) file to:

```javascript
loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('node-sass') } }]
```

**Comment by NikGovorov** [comment]
More on deprecation of `deep` in Angular docs: https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep.

**Comment by chrisj-skinner** [comment]
Thanks - @NikGovorov
