### ISSUE TITLE
Edit of jest config doesn't trigger tests re-run

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2186]
### Issue description or question

Edit of `jest.config.js` or Jest config in `package.json` doesn't trigger tests re-run

1. Start Wallaby with some tests
2. Create `./test/setup.js` with code
```
throw Error('test')
```
3. Create `./jest.config.js` with code
```
module.exports = {
  setupFilesAfterEnv: ['./test/setup.js'],
}
```

ER: Tests should crash with error `'test'`
CR: Tests are not even triggered

The same problem if Jest config is added to `package.json`

### Wallaby.js configuration file

Autoconfig for Jest 24.8

### Code editor or IDE name and version

WebStorm v2019.2

### OS name and version

Windows 10 Pro

**Comment by ArtemGovorov** [comment]
This is expected behavior because Jest requires restart when its config is changed, `npx jest --watch` without Wallaby works the same way.
