### ISSUE TITLE
Cannot get Jest mocks or snapshots working with Typescript, React-Native, and Jest

### ISSUE THREAD

**Issue by jljorgenson18** [wallabyjs/public#2188]
### Issue description or question

So this is really two issues and I am happy to split this up if they are unrelated. I'm attempting to get a jest + react-native + Typescript project set up with Wallaby. I can get many of the tests running, but the tests that require certain mocks are failing and certain `jest.mock` calls seem to be bypassed.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'tsconfig.json',
      'src/**/*.ts?(x)',
      'src/**/__snapshots__/**',
      { pattern: 'assets/**', instrument: false, binary: true },
      '!assets/ce/**',
      '!src/**/__tests__/*.ts?(x)',
    ],

    tests: ['src/**/__tests__/*.ts?(x)'],

    env: {
      type: 'node',
    },

    testFramework: 'jest',

    debug: true,

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require('babel-preset-jest')],
        }),
    },
  };
};

```

### Jest Configuration File

```javascript
module.exports = {
  verbose: true,
  preset: 'react-native',
  transform: {
    '^.+\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js',
  },
  testRegex: '(/__tests__/.*|(\\.|/)(test|spec))\\.[j]sx?$',
};
```

The error logs show us trying to hit "react-native-localize" even though it should been mocked.

```
[Info]  console.log: FAIL src/notebook-list/__tests__/NotebookListShortRow-test.js
[Info]  console.log:   ● Test suite failed to run
[Info]      TypeError: Cannot read property 'initialConstants' of undefined
[Info]        at Object.<anonymous> (node_modules/react-native-localize/index.js:24:28)
[Info]        at Runtime.u._wallabyReplaced.c.requireModule (../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.141/wallaby/runners/node/jest@0.4.3/initializer.js:14:25888)
[Info]        at Object.<anonymous> (src/base/neutron-i18n/translate.ts:5:1)
[Info]  2019-08-21T21:23:19.119Z wallaby:workers Sandbox (inactive) [o3qte] error: TypeError: Cannot read property 'initialConstants' of undefined
[Error] Runtime error: TypeError: Cannot read property 'initialConstants' of undefined 
[Error]     at Object.<anonymous> (./node_modules/react-native-localize/index.js:24:28) 
[Error]     at Runtime._execModule (./node_modules/jest-runtime/build/index.js:888:13) 
[Error]     at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:577:12) 
[Error]     at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:433:10) 
```

In digging into this, I'm almost certain the problem is related to module resolution. The tsconfig has

```
    "moduleResolution": "node" /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */,
    "baseUrl": "." /* Base directory to resolve non-absolute module names. */,
    "paths": {
      "*": ["node_modules/*", "src/*", "src/base/*"]
    } /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */,
    "rootDirs": [
      "./src",
      "./stories"
    ] /* List of root folders whose combined content represents the structure of the project at runtime. */,
```

And it looks like if jest.mock was called as a result of requiring something that was in `src/base/`, the mock doesn't actually work. I can also see in the instrumented code that the paths are not rewritten. So if I do

`import myModule from 'myModule';`

and `myModule` was located at `src/base/myModule.tsx`, then the jest.mock calls executed in `myModule` seem to end up failing.

### Snapshot issue

The snapshots are listed in the file globs and being loaded, but Wallaby is writing to a "tsx" extension and not the "js" extension. For example, the normal jest snapshots look like `src/notelist/__tests__/__snapshots__/NoteCard-test.js.snap` while the Wallaby snapshots look like `src/notelist/__tests__/__snapshots__/NoteCard-test.tsx.snap`. I don't know if this is related to the original issue or if it is something else.

**Comment by jljorgenson18** [comment]
Also, I did try the automatic configuration. It ran all of the tests but failed to do any in-editor code coverage or visual feedback.

**Comment by smcenlly** [comment]
Thanks for all of the detail that you provided. We're going to need a little bit more information about your project to help resolve your issue.

Am I right in saying that when you test outside of Wallaby, you have to compile your TypeScript code before you run your tests?

Could you please provide the following files:
* package.json
* tsconfig.json
* any babel configuration you may have for your project

We will use those files to set up a small sample project to duplicate your problem. As an alternative, if possible could you please share your project, or a cut down version of your project that has the problem?

**Comment by jljorgenson18** [comment]
Here is the tsconfig.json with comments removed

```json
{
  "compilerOptions": {
    "watch": true,
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es2015.promise",
      "es2015.core",
      "es5",
      "esnext.array"
    ],
    "jsx": "react",
    "sourceMap": true,
    "strict": true ,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {
      "*": ["node_modules/*", "src/*", "src/base/*"]
    },
    "rootDirs": [
      "./src",
      "./stories"
    ],
    "typeRoots": [
      "./typescript-definitions",
      "./node_modules/@types"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "exclude": [
    ".vscode-test",
    "node_modules",
    "node_modules/@types",
    "node_modules/@types*",
    "/node_modules",
    "../node_modules",
    "*node_modules*",
    "/node_modules*",
    "SampleApplication/",
    "SampleApplication/node_modules",
    "SampleApplication/.vscode",
    "ReactTypings",
    "tools/",
    "test/resources/sampleReactNative022Project/"
  ]
}
```



I would rather note share the entire package.json just because there are private package names and what not. In double checking the files, I realize now that the Jest command had Typescript being compiled ahead of time. Here are some of the package.json scripts.

```
    "build": "tsc",
    "build:nowatch": "tsc --watch false",
    (...a few more scripts)
    "clean": "react-native-clean-project && rm -rf dist",
    "clean:typescript": "find src | grep -E '.js$|.js.map$' | xargs rm",
    (...a few more scripts)
    "test": "yarn build:nowatch && jest --forceExit",
    "test:nobuild": "jest --forceExit",
    "test:update": "yarn clean:typescript && yarn build:nowatch && jest -u",
```

Maybe I was just missing the compilation for Typescript somehow?

Also, there is no babel configuration. This is a pure typescript + react-native project.

**Comment by jljorgenson18** [comment]
Also apparently, they had update the vscode settings to exclude all of the .js and .js.map files from showing up in the directory. That could also be explaining the discrepancy as I've been doubly importing the files. That is probably the source of the problem so I can try to resolve that. Not sure how well that would play with Wallaby though because the tests are being run on the pure js files.

**Comment by smcenlly** [comment]
Thanks for your replies. 

The reason that your snapshots are not working is because `jest` is configured to run on the compiled JavaScript files. This means that the snapshot file extension is `.js`. Wallaby is configured to run on your TypeScript files, which have an extension of `.tsx`. In this case, Wallaby is doing the right thing, as is Jest. To get snapshots working, you will need to update your Jest configuration to run on the TypeScript files instead of the compiled JavaScript.

The reason you weren't getting any coverage indicators when using Automatic Configuration is because the source files are mapped to the `.js` files which are hidden from your editor. If you were to show those, you would see the coverage appearing in those files (which obviously is still not correct).

Our recommendation is to update your jest configuration to run on TypeScript and then use Wallaby's Automatic Configuration. For example, something like this (maybe replace the preset with your current preset):

```javascript
// From react-native sample: 
//     https://github.com/amaurymartiny/shoot-i-smoke/blob/master/jest.config.js

module.exports = {
  preset: 'jest-expo',
  moduleFileExtensions: ['js', 'ts', 'tsx'],
  testMatch: ['**/?(*.)+(spec|test).ts?(x)'],
  transform: {
    '^.+\\.tsx?$': 'ts-jest',
    '^.+\\.js$': '<rootDir>/node_modules/react-native/jest/preprocessor.js' // https://github.com/facebook/react-native/issues/21075#issuecomment-441332894
  }
};
```

If you make this change, at the very least, I would expect your snapshot filenames to change, so you would need to fix that.

---

I don't believe that the mock problem has anything to do with the fact that `.js` file exist along side your project files as Wallaby isn't using these. I think that there's a conflict/issue with jest mocks being hoisted by babel (perhaps due to the react-native jest preprocessor). This may also be resolved by changing jest to run on TypeScript. If you don't want to update Jest to run on your TypeScript files, please provide us with a cut down sample repo (excluding any private packages, etc.) that has the mock problem.

**Comment by jljorgenson18** [comment]
Yep, just confirmed the issue had to do with Typescript misconfiguration in the project itself. If anything, Wallaby was the only thing running correctly. Thank you for taking a look at this regardless!
