### ISSUE TITLE
File called $$ and _$$ are not loaded

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#219]
I just hit on an issue where if a file is named using $$ or _$$ then it wouldn't be picked up by the source scripts loader

![image](https://cloud.githubusercontent.com/assets/656739/8955877/7cd70880-35e8-11e5-9110-d46fca370e65.png)

In the screenshot above the issue happens when the file is called $$.coffee

Note that this same code is passing ok with Karma (using PhantomJS)

![image](https://cloud.githubusercontent.com/assets/656739/8955894/a6608e1a-35e8-11e5-88af-1f305a08ea36.png)

My short term fix is to call the file _$_$  which seems to work ok

![image](https://cloud.githubusercontent.com/assets/656739/8955934/21c0fd06-35e9-11e5-9f6e-300f593a86f8.png)

**Comment by ArtemGovorov** [comment]
The issue is fixed in core v1.0.84. Will be updated automatically next time you restart wallaby.js (the current core version is displayed in Wallaby Console when you start it).

**Comment by DinisCruz** [comment]
great thx
