### ISSUE TITLE
 using jQuery in advanced logging expressions?

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#2198]
###  question
In the past, I remember using jQuery in advanced logging expressions (as opposed to pure javascript)... does that work out of the box? Or is there some config needed?

### Wallaby.js configuration file
from here = https://wallabyjs.com/docs/integration/angular.html#angular-cli
for Angular CLI

### Code editor or IDE name and version
Visual Studio Code v1.38.0

### OS name and version
Windows 10

**Comment by smcenlly** [comment]
Advanced logging provides a special variable `$`, which is the object being logged (NOT JQuery).

If you use JQuery in your application/tests if your angular project is configured to use it (e.g. https://medium.com/better-programming/how-to-include-and-use-jquery-in-angular-cli-project-592e0fe63176) and the object being logged is a JQuery object, then in your Advanced Logging expression, you will have access to JQuery methods on the object. For example:

```typescript
import { Component } from '@angular/core';
import * as jquery from 'jquery';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'Wallaby Angular CLI Project';

  public ngOnInit() {
    jquery(document).ready(function() {
      const div = jquery('div');
      div //? $.text()
    })
  }
}
```
