### ISSUE TITLE
Wallaby reports false positive on jest test - > shallow(<Component/>)

### ISSUE THREAD

**Issue by jostendorf** [wallabyjs/public#2199]
### Issue description or question
Wallaby is passing this test when it should fail.  The test explorer is showing the file as "n/a" when it should show coverage.  Within the IDE, the test is green.  The scenario is I added a props property to a react component that previously did not have one.  Tests were passing prior, and are still passing after the change when this typescript error occurs:

Property 'history' is missing in type '{}' but required in type 'Props'.ts(2741)
index.tsx(8, 3): 'history' is declared here.

### Wallaby.js configuration file
Auto-configuration

```javascript
// before code change
export const Component = () => {
  // do stuff
};

// after code change
export const Component = (props: Props) => {
const { history } = props;
 // do stuff
};


// test
beforeEach(() => {
    wrapper = mount(<Component />);
    ....
});
```

### Code editor or IDE name and version
Visual Studio Code v1.38

### OS name and version
OSX

**Comment by smcenlly** [comment]
By default, Wallaby also [sets few default compiler settings](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) that are not replaced by `tsconfig.json` compiler settings (to perform TypeScript compilation faster).

```javascript
        noLib: true,
        noResolve: true,
        declaration: false,
        noEmitOnError: false,
        composite: false
```

If you want wallaby to stop overriding them, then you may to do so in your wallaby.js config by adding the `useStandardDefaults: true` setting.

However, we **do not recommend** running Wallaby with type checking in place. Doing so will likely duplicate what your editor is already doing, and create a lot of noise for you when you're using Wallaby and will result in coverage indicators breaking when type errors are detected (often). This will also slow down the feedback loop between writing code and running tests, which somewhat reduces the benefit of Wallaby.

Instead, we suggest relying on your editor for these errors which will give you the best user experience in terms of editor feedback + fast wallaby tests. You should of course rely on your build processes, etc. to fail hard on these errors.
