### ISSUE TITLE
Support mocha TDD interface

### ISSUE THREAD

**Issue by Saulis** [wallabyjs/public#22]

**Comment by ArtemGovorov** [comment]
Do you mean for node.js/io.js tests or for browser tests? 

For browser tests, you can already configure mocha by calling

```javascript
mocha.ui('tdd');
```
somewhere before your tests, the best place I guess would be a separate file, say `mochaConfig.js`. So the config file would look like:
```
module.exports = function () {
  return {
    files: [
      'src/*.js',
      'helpers/mochaConfig.js' // or anywhere that suits you
    ],

    tests: [
      'test/*Spec.js'
    ]
  };
};
```
and mochaConfig.js would contain the line of code I have pasted earlier (or some more mocha configuration).

**Comment by Saulis** [comment]
Thanks for your reply, I'm running node.js. "mocha" seems to be undefined for me.

**Comment by ArtemGovorov** [comment]
@Saulis Yes, in node.js there's not way yet to access it. I will expose it and let you know when the version with the change is out.

**Comment by Saulis** [comment]
OK, thanks alot!

**Comment by ArtemGovorov** [comment]
Now you can configure your testing framework via the `bootstrap` function configuration setting - https://github.com/wallabyjs/public#bootstrap-setting.

**Comment by Saulis** [comment]
Works like a charm!

**Comment by ArtemGovorov** [comment]
Awesome, glad to hear that!

**Comment by kodeninja** [comment]
@ArtemGovorov I've just started playing around with wallaby, and I'm trying to integrate some mocha-specific options that I normally use when running my tests.

Is this the correct syntax?:

*wallaby.js*:
```javascript
...
        "bootstrap": function (wallaby) {
            wallaby.testFramework.options = {
                "timeout": 6000,
                "check-leaks": false,
                "ui": "bdd",
                "reporter": "spec",
                "env": { "NODE_ENV": "test", "inTest": true, "logConsole": false },
                "globals": ["elt"]
            };
...
```

**Comment by ArtemGovorov** [comment]
From mocha source code (I'm assuming you are running node.js tests), it looks like there are separate functions to set these options.
```
/**
 * Setup mocha with `options`.
 *
 * Options:
 *
 *   - `ui` name "bdd", "tdd", "exports" etc
 *   - `reporter` reporter instance, defaults to `mocha.reporters.spec`
 *   - `globals` array of accepted globals
 *   - `timeout` timeout in milliseconds
 *   - `bail` bail on the first test failure
 *   - `slow` milliseconds to wait before considering a test slow
 *   - `ignoreLeaks` ignore global leaks
 *   - `grep` string or regexp to filter tests with
 *
 * @param {Object} options
 * @api public
 */
```
So it would look like:
```javascript
        "bootstrap": function (wallaby) {
            var mocha = wallaby.testFramework;
            mocha.globals(['elt']);
            mocha.ui('bdd');
            // etc
        };
```
Regarding `"env": { "NODE_ENV": "test", "inTest": true, "logConsole": false }`, you can pass env object specifying those values from configuration:
```javascript
module.exports = function () {
  return {
    files: [
      'lib/*.js'
    ],

    tests: [
      'test/*Spec.js'
    ],

    env: {
      type: 'node',

      params: {
        //runner: '--harmony --harmony_arrow_functions',
        env: 'NODE_ENV=test;inTest=true;logConsole=false'
      }
    }
  };
};
```

**Comment by kodeninja** [comment]
Thanks a lot, @ArtemGovorov! That worked! And yes, I _am_ running these tests server-side, in a node.js environment.

**Comment by ArtemGovorov** [comment]
Great. Looking further into mocha source code, your initial version of just setting `wallaby.testFramework.options = {...}` should also work (except env, it has to be passed from config).

**Comment by kodeninja** [comment]
@ArtemGovorov one more question. If I need to pass the `NODE_DEBUG` flag as well, would that also be via `env.params.env`? So, something like:

```javascript
            "params": {
                "env": "NODE_DEBUG=fs,path;NODE_ENV=test;inTest=true;logConsole=false"
            }
```

I'm actually seeing an `Arguments to path.resolve must be strings` error in a lot of my tests when run via `wallaby`. I don't see these errors when running them the usual way, via `npm test`. I've tracked down all explicit uses of `path.resolve()` in my code and don't see an issue. So, I was wondering if enabling `NODE_DEBUG` might give some clues.

Thanks again for you help!

**Comment by ArtemGovorov** [comment]
@kodeninja yes, all env vars (including NODE_DEBUG) are passed via `env.params.env`.
You may also try setting `debug: true` in wallaby config and have a look into wallaby console tab inside wallaby tool window, it may also shed some light.
```javascript
module.exports = function () {
  return {
    debug: true,
    ...
  };
};
```
Does the error occur after the initial run or later on when you are editing your code and tests? If it starts to show up later, try setting `recycle: true` setting in `workers` setting - https://github.com/wallabyjs/public#node-process-reuse.

If nothing helps, please provide a small sample project if it's not too much trouble for you, where the error can be reproduced. Best if you create a repository on GitHub and give me a link to the repo. I will have a look, fix wallaby.js issue or the setup issue and send you a pull request, like in this case - https://github.com/Gregoor/wallaby-test/pull/1.

**Comment by ArtemGovorov** [comment]
@kodeninja Did you manage to find the reason for `Arguments to path.resolve must be strings` issue?

**Comment by kodeninja** [comment]
@ArtemGovorov thank so much for looking into this. Sorry I could not reply earlier.

I am running wallaby with `debug: true` every time. I'm running these tests via the wallaby & Intellij IDEA14 integration. What I see is that on the very first run, although the `Wallaby Console` does not report errors, the `Failing Tests` console shows a couple of tests marked as failed, with the `Arguments to path.resolve must be strings` error.

This is a proprietary app, so I can't post the source, unfortunately. However, I will try to create a minimal app that, hopefully, reproduces the error.

I tried adding the `NODE_DEBUG` flag as mentioned, but could not see any additional logging. Not sure what's missing.

In any case, I'll probably have more details later.
