### ISSUE TITLE
Update favicon color (green/red) depending of global status

### ISSUE THREAD

**Issue by tomsquest** [wallabyjs/public#2202]
### Feature request

Currently, in any case, the wallaby icon in the wallaby webapp is always red, even if 100% of the tests succeeded.

This icon could reflect the global status of the tests.

**Comment by ArtemGovorov** [comment]
Could you please share your browser and OS versions?

**Comment by tomsquest** [comment]
- Firefox 69.0 64bits
- Ubuntu 19.04

**Comment by tomsquest** [comment]
Closing: disabling http://localhost:51245/ in **ublock origin** fixes the problem.
