### ISSUE TITLE
Crash in WebStorm 

### ISSUE THREAD

**Issue by olegdovger** [wallabyjs/public#2205]
### Issue description or question

I updated WebStorm to version 2019.2.2

WebStorm version info:
```WebStorm 2019.2.2
Build #WS-192.6603.19, built on September 3, 2019
Licensed to Oleg Dovger
Subscription is active until January 10, 2020
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1406M
Cores: 4
Registry: js.debugger.webconsole=false
Non-Bundled Plugins: Key Promoter X, com.alayouni.ansiHighlight, com.intellij.ideolog, com.khmelyuk.multirun, com.thvardhan.gradianto, net.seesharpsoft.intellij.plugins.csv, BashSupport, de.escalon.idea.plugin.svelte, quokka.js, ru.adelf.idea.dotenv, wallaby.js
```

And I have got this message
Anyway, wallabyjs plugin works well

I just noticed such strange behaviour

### Wallaby diagnostics report

![w error](https://user-images.githubusercontent.com/964292/64845873-ebc83500-d613-11e9-9539-cdad1f84df09.png)

**Comment by NikGovorov** [comment]
Hi @olegdovger,

Thanks for reporting the issue, it's fixed in [1.0.138](https://download.wallabyjs.com/intellij) of IntelliJ plugin.
