### ISSUE TITLE
setupFilesAfterEnv not found

### ISSUE THREAD

**Issue by BrendaEgeland** [wallabyjs/public#2207]
### Issue description or question

I had Wallaby working fine with Jest and Enzyme until I tried to incorporate a jestSetup file. Jest continues to run the tests with no errors, but Wallaby says it cannot find the setup file. I have tried many of the variations I have found when others have reported similar problems, but to no avail.

I have changed angle-bracket-rootDir-angle-bracket to [rootDir] below so it appears correctly below.

Thank you for your help.

package.json:

> {
>   "name": "wallaby-debug",
>   "private": true,
>   "scripts": {
>     "test": "jest"
>   },
>   "jest": {
>     "testMatch": [
>       "[rootDir]/app/javascript/tests/**/*.test.js"
>     ],
>     "transformIgnorePatterns": [
>       "/node_modules/(?!React).+\\.js$"
>     ],
>     "setupFilesAfterEnv": [
>       "[rootDir]/jestSetup.js"
>     ]
>   },
>   "dependencies": {
>     "core-js": "^3.2.1",
>     "prop-types": "^15.6.0",
>     "react": "^16.9.0",
>     "react-bootstrap": "^0.32.4",
>     "react-dom": "^16.2.0"
>   },
>   "license": "UNLICENSED",
>   "engines": {
>     "node": "11.14.0",
>     "yarn": "YARN NO LONGER USED - use npm instead."
>   },
>   "devDependencies": {
>     "@babel/core": "^7.6.0",
>     "@babel/plugin-proposal-class-properties": "^7.5.5",
>     "@babel/plugin-syntax-dynamic-import": "^7.2.0",
>     "@babel/plugin-transform-react-jsx-source": "^7.5.0",
>     "@babel/plugin-transform-runtime": "^7.6.0",
>     "@babel/preset-env": "^7.6.0",
>     "@babel/preset-react": "^7.0.0",
>     "babel-core": "^7.0.0-bridge.0",
>     "babel-eslint": "^10.0.3",
>     "babel-jest": "^24.9.0",
>     "babel-loader": "^8.0.6",
>     "babel-plugin-module-resolver": "^3.2.0",
>     "compression-webpack-plugin": "^1.1.12",
>     "enzyme": "^3.8.0",
>     "enzyme-adapter-react-16": "^1.7.1",
>     "eslint": "^6.3.0",
>     "eslint-plugin-jest": "^22.17.0",
>     "eslint-plugin-react": "^7.14.3",
>     "jest": "^24.9.0",
>     "prettier-eslint-cli": "^5.0.0"
>   }
> }

wallaby.js:
> module.exports = function(wallaby) {
>   return {
>    testFramework: 'jest',
>    env: {
>       type: 'node',
>     },
>     tests: ['app/javascript/tests/**/*.test.js'],
>     files: ['app/javascript/**/*.js', 'app/javascript/**/*.jsx', '!node_modules/**/*.*', '!app/javascript/tests/**/*.js', '!**/.*'],
>     compilers: {
>       '**/*.js': wallaby.compilers.babel(),
>       '**/*.jsx': wallaby.compilers.babel(),
>     },
>   }
> }

jsetSetup.js (currently in root, but I've tried it elsewhere):
> import { configure } from 'enzyme'
> import Adapter from 'enzyme-adapter-react-16'
> configure({ adapter: new Adapter() })

Messages in Wallaby Console:
> [Info]  Started Wallaby.js Core v1.0.740
> [Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
> [Error] Runtime error: ● Validation Error: 
> [Error]   Module ./jestSetup.js in the setupFilesAfterEnv option was not found. 
> [Error]          [rootDir] is: . 
> [Error]   Configuration Documentation: 
> [Error]   https://jestjs.io/docs/configuration.html 
> [Error] Runtime error: ● Validation Error: 
> [Error]   Module ./jestSetup.js in the setupFilesAfterEnv option was not found. 
> [Error]          [rootDir] is: . 
> [Error]   Configuration Documentation: 
> [Error]   https://jestjs.io/docs/configuration.html 
> ...

### Wallaby diagnostics report

```
{ editorVersion: '1.38.1',
  pluginVersion: '1.0.143',
  editorType: 'VSCode',
  osVersion: 'darwin 18.6.0',
  nodeVersion: 'v11.14.0',
  coreVersion: '1.0.740',
  config:
   { testFramework:
      { version: 'jest@0.4.3',
        configurator: 'jest@0.4.3',
        reporter: 'jest@0.4.3',
        starter: 'jest@0.4.3' },
     env:
      { type: 'node',
        params: {},
        runner: '<homeDir>/.nvm/versions/node/v11.14.0/bin/node',
        viewportSize: { width: 800, height: 600 },
        options: { width: 800, height: 600 },
        bundle: true },
     tests:
      [ { pattern: 'app/javascript/tests/**/*.test.js',
          ignore: false,
          trigger: true,
          load: true,
          test: true,
          order: 5 } ],
     files:
      [ { pattern: 'app/javascript/**/*.js',
          ignore: false,
          trigger: true,
          load: true,
          instrument: true,
          order: 1 },
        { pattern: 'app/javascript/**/*.jsx',
          ignore: false,
          trigger: true,
          load: true,
          instrument: true,
          order: 2 },
        { pattern: 'node_modules/**/*.*',
          ignore: true,
          trigger: true,
          load: true,
          instrument: true },
        { pattern: 'app/javascript/tests/**/*.js',
          ignore: true,
          trigger: true,
          load: true,
          instrument: true },
        { pattern: '**/.*',
          ignore: true,
          trigger: true,
          load: true,
          instrument: true },
        { pattern: 'app/javascript/tests/**/*.test.js.snap',
          ignore: false,
          instrument: false,
          trigger: true,
          load: true,
          order: 3 },
        { pattern: 'package.json',
          ignore: false,
          instrument: false,
          trigger: true,
          load: true,
          order: 4 } ],
     compilers:
      { '**/*.js': [Function],
        '**/*.jsx': [Function],
        '**/*.?(lit)coffee?(.md)': [Function] },
     filesWithNoCoverageCalculated: [],
     runAllTestsInAffectedTestFile: false,
     preprocessors: { 'package.json': [Function] },
     maxConsoleMessagesPerTest: 100,
     autoConsoleLog: true,
     delays: { run: 0, edit: 100, update: 0 },
     workers: { initial: 0, regular: 0, recycle: false },
     teardown: undefined,
     hints:
      { ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
        ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
        commentAutoLog: '?',
        testFileSelection:
         { include: '__REGEXP /file\\.only/',
           exclude: '__REGEXP /file\\.skip/' } },
     automaticTestFileSelection: true,
     runSelectedTestsOnly: false,
     extensions: {},
     reportUnhandledPromises: true,
     slowTestThreshold: 75,
     lowCoverageThreshold: 80,
     loose: true,
     configCode:
      "module.exports = function(wallaby) {\n  return {\n   testFramework: 'jest',\n   env: {\n      type: 'node',\n    },\n    tests: ['app/javascript/tests/**/*.test.js'],\n    files: ['app/javascript/**/*.js', 'app/javascript/**/*.jsx', '!node_modules/**/*.*', '!app/javascript/tests/**/*.js', '!**/.*'],\n    compilers: {\n      '**/*.js': wallaby.compilers.babel(),\n      '**/*.jsx': wallaby.compilers.babel(),\n    },\n  }\n}\n" },
  packageJSON:
   { dependencies:
      { 'core-js': '^3.2.1',
        'prop-types': '^15.6.0',
        react: '^16.9.0',
        'react-bootstrap': '^0.32.4',
        'react-dom': '^16.2.0' },
     devDependencies:
      { '@babel/core': '^7.6.0',
        '@babel/plugin-proposal-class-properties': '^7.5.5',
        '@babel/plugin-syntax-dynamic-import': '^7.2.0',
        '@babel/plugin-transform-react-jsx-source': '^7.5.0',
        '@babel/plugin-transform-runtime': '^7.6.0',
        '@babel/preset-env': '^7.6.0',
        '@babel/preset-react': '^7.0.0',
        'babel-core': '^7.0.0-bridge.0',
        'babel-eslint': '^10.0.3',
        'babel-jest': '^24.9.0',
        'babel-loader': '^8.0.6',
        'babel-plugin-module-resolver': '^3.2.0',
        'compression-webpack-plugin': '^1.1.12',
        enzyme: '^3.8.0',
        'enzyme-adapter-react-16': '^1.7.1',
        eslint: '^6.3.0',
        'eslint-plugin-jest': '^22.17.0',
        'eslint-plugin-react': '^7.14.3',
        jest: '^24.9.0',
        'prettier-eslint-cli': '^5.0.0' } },
  fs: { numberOfFiles: 6 },
  debug: [] }
```

**Comment by BrendaEgeland** [comment]
Sigh ... as soon as you post, you find an answer, right?

I added 'jestSetup.js' to the files: array in wallaby.js, and now it works.

But ... if I move the jestSetup.js file to app/javascript/test/jestSetup.js, and change it in files as well, it goes back to not working:

    files: ['app/javascript/tests/jestSetup.js', 'app/javascript/**/*.js', 'app/javascript/**/*.jsx', '!node_modules/**/*.*', '!app/javascript/tests/**/*.js', '!**/.*'],

**Comment by BrendaEgeland** [comment]
Sigh again.. finally found my problem. On the files line, although I'm including it at the front, I'm excluding it later on in the list. I changed that and now all is fine.

**Comment by smcenlly** [comment]
Glad to hear that you got this working. I see that you had a Wallaby.js configuration file. If you didn't already know, Wallaby now supports running without a configuration file for Jest v24+. You may like to check out [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) and use it for your project.
