### ISSUE TITLE
Automatic Angular CLI configuration error: rules is not defined after updating WebStorm plugin

### ISSUE THREAD

**Issue by wilgert** [wallabyjs/public#2208]
### Issue description or question

After updating the Wallaby WebStorm plugin my tests don't run anymore. Previously tests where running with Automatic Configuration.

We are using Angular 8.2.

### Wallaby diagnostics report

```
wallaby.js started
core v1.0.744
Failed to load configuration file: Automatic Angular CLI configuration error: rules is not defined

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '/Users/***/Projects/****'.

```

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by wilgert** [comment]
Thanks for the fast response and fix!
