### ISSUE TITLE
When live logging HTML, how can you pretty print/format the HTML?

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#2210]
### Issue question
When live logging HTML, how can you pretty print/format the HTML?
Please see screenshot, the popup with the rendered HTML is one line.
How could you have it look like the source (in screenshot the top code block)?
![bbb](https://user-images.githubusercontent.com/6947701/64991172-fba37b80-d896-11e9-9858-62b27cf1869c.PNG)

**Comment by ArtemGovorov** [comment]
Live logging prints out the content as is (it is not formatted in the `nodeList[0].outerHTML` property).

You can use one of the formatters, for example https://www.npmjs.com/package/pretty, and do:
```
npm i pretty --save-dev
```

and then

```js
require('pretty')(nodeList[0].outerHTML) //?
```
