### ISSUE TITLE
No support for baseurl

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#2211]
Hi

How would you modify this config to support `"baseUrl": "src"`.
Currently it explodes.

All works with automatically generated config, but with custom one no ;(

**Comment by ArtemGovorov** [comment]
Thanks for your feedback. We have re-implemented Jest `collectCoverageFrom` support for auto-configuration. Please 
update to [the latest core version 1.0.748](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), refresh your Wallaby App and the experience should be much better now.

**Comment by tomitrescak** [comment]
@ArtemGovorov nothing short of amazing! Thank you! I love how I travel with Wallaby between companies ... in my newest one I had them buy immediately few company licenses and the LOVE it ;)

Yet, while the files are now shown correctly, the coverage is not calculated coerrectly. Files correctly show 0% coverage, but the running total is not taking it into account, still thinking they are n/a. Check out the screen below:

![image](https://user-images.githubusercontent.com/2682705/65130463-c49baa00-d9fd-11e9-9962-acfd1526d732.png)

When a test "touches" the file, the calculation start to adjust correctly.

**Comment by tomitrescak** [comment]
A bit more info, the issue lies with that the line count is not detected:

![image](https://user-images.githubusercontent.com/2682705/65130660-307e1280-d9fe-11e9-82c3-e19553aea0d8.png)

This is the "loading_modal.tsx" file

```ts
import React from 'react';
import { modalStore } from '../modal';
import { LoadingAnimation } from 'components/loading/loading_overlay';
import { LoadingContainer, LoadingMessage } from './loading_modal.styles';

type Props = {
  message?: string;
};

export function showLoadingModal(message = 'Loading ...') {
  modalStore.show({
    closeOnClick: false,
    closeOnEscape: false,
    content: (
      <LoadingContainer>
        <LoadingAnimation />
        <LoadingMessage>{message}</LoadingMessage>
      </LoadingContainer>
    )
  });
}
```

This is what jest reports

```
src/components/loading      |       70 |        0 |    66.67 |       70 |                   |
  index.tsx                  |        0 |        0 |        0 |        0 |                   |
  loading_modal.styles.ts    |        0 |      100 |      100 |        0 |               3,8 |
  loading_modal.tsx          |        0 |        0 |        0 |        0 |                11 |
```

**Comment by ArtemGovorov** [comment]
Thanks a lot for your report! Please 
update to [the latest core version 1.0.750](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), refresh your Wallaby App and the issue with coverage calculation should be fixed now.

**Comment by tomitrescak** [comment]
Fabulous!! Thanks!
