### ISSUE TITLE
Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#2215]
First apologies in advance if this is a repeat question. I've searched through the issues and alhough I can see similar issues listed, none of the solutions offered seem to help me.

I've just added wallaby to my angular cli project. I'm using
- a `nrwl/nx` workspace
- angular cli > `8.2.0`
- jest > `24.0.0`

I have therefore opted to use your suggested automatic configuration.

however, on running my tests, I still get the `zone.js` error.

specific error:

```shell
 Error: Failed: "Zone is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/zone.js" 
      at Suite.Object.<anonymous>.describe ​apps/<my-app-name>/app/src/app/app.component.spec.ts:6:2​
      at Object.<anonymous> ​apps/<my-app-name>/app/src/app/app.component.spec.ts:5:0​
```

i'm assuming I need to use 

```javascript
module.exports = () => ({
   autoDetect: true,
   ...
});
```

and add some additional configuraiton, but not sure what. Any guidance would be muchc appreciated...

**Comment by zpydee** [comment]
And now I'm also getting

```bash
TypeError: Cannot set property '0' of undefined 
  at Object.<anonymous> ​apps/papillio/app/src/app/app.component.ts:3​
  at Object.<anonymous> ​apps/papillio/app/src/app/app.component.spec.ts:3:0​Ï
```

**Comment by zpydee** [comment]
and

```bash
Error: Cannot find module '@<my-namespace>/apps/core-app' from 'app.component.spec.ts' 
  at Object.<anonymous> ​apps/<my-app-name>/app/src/app/app.component.spec.ts:6:0​
```

**Comment by zpydee** [comment]
seems to be firing random messages at me.

Is it possible that the auto configuration is not suitable for `nrwl/nx` projects and if so, what config should I use for my project

**Comment by NikGovorov** [comment]
Hi @zpydee,

At the moment for `nrwl/nx` workspaces auto configuration works only for one [specific application or library](https://wallabyjs.com/docs/integration/nrwl.html). 

To run tests for the entire workspace you'll have to create `wallaby.js` configuration file, please find the example [here](https://github.com/wallabyjs/wallaby-2190).
