### ISSUE TITLE
Configuring WallabyJS for StoryBook + Create React App Typscript + Jest

### ISSUE THREAD

**Issue by TanKucukhas** [wallabyjs/public#2220]
### Issue description or question

Trying to setup wallaby for a storybook project. I made some progress got stuck in the end running it. The things is used on the project are Create React App Typescript ( Not the new create-react-app that already has typescript support), Storybook, Jest.

### Wallaby diagnostics report
```
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
console.error: Error while trying to initialize jest: Cannot read property 'rootDir' of undefined
```

**wallaby.js**
 ```javascript
module.exports = function (wallaby) {

    return {
        files: [
            'src/**/*.ts?(x)',
            'src/**/*.snap',
            '!src/**/*.test.ts?(x)',
            '.storybook/config.js',
            'src/**/*.d.ts'
        ],
        tests: [
            'src/**/*.test.ts?(x)',
        ],
        env: {
            type: 'node',
            runner: 'node',
        },

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript(Object.assign(
                require('./tsconfig.json').compilerOptions,
                require('./tsconfig.test.json').compilerOptions)),
            '.storybook/*.js': wallaby.compilers.babel()
        },

        preprocessors: {
            '.storybook/config.js': f => f.content.replace('.tsx$', '.js$')
        },

        setup: wallaby => {
            const jestConfig = require("react-scripts-ts/scripts/utils/createJestConfig")(
                p => require.resolve("react-scripts-ts/" + p)
            );
            delete jestConfig.transform["^.+\\.(js|jsx)$"];
            delete jestConfig.transform["^.+\\.(ts|tsx)$"];
            delete jestConfig.testEnvironment;
            Object.keys(jestConfig.moduleNameMapper).forEach(k => (jestConfig.moduleNameMapper[k] = jestConfig.moduleNameMapper[k].replace('<rootDir>', wallaby.localProjectDir)))
            wallaby.testFramework.configure(jestConfig);
        },

        debug: true,
        testFramework: 'jest',
    };
};

```

**package.json jset config**
 ```
"jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less|scss)$": "identity-obj-proxy"
    },
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}",
      "!src/**/*.{d.ts}",
      "!src/**/*.stories.tsx",
      "!src/__template__/*.*",
      "!src/Common/{fonts,js,styles,Types}/*.*"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 50,
        "functions": 70,
        "lines": 70,
        "statements": 70
      }
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  },
```

**IDE**
```
IntelliJ Ultimate 2019.2 with latest wallaby plugin
```

**OS**
```
OSX
```

**Comment by smcenlly** [comment]
We identified an edge case in our jest integration that can lead to the issue that you're seeing. Please update to the latest version of Wallaby core (v1.0.754) and see if that fixes your problem. If wallaby doesn't automatically update for you, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If you are using Jest v24+, we recommend changing your project to use our new [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration), which will allow you to run Wallaby without configuration.

If you're still having the problem, can you please provide us with your Wallaby Diagnostics report. The diagnostics report is a simple JSON text report that contains some basic information
about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To get the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
Since we haven't heard back, we're going to assume that either our update or one of the suggestions we provided fixed your problem. If not, let us know and we will reopen this issue.
