### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ifuseandprint** [wallabyjs/public#2225]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.144`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\PC\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ArtemGovorov** [comment]
Please attach the file mentioned in the issue description to the issue.

**Comment by smcenlly** [comment]
@ifuseandprint - since we have not heard back from you, we are closing this issue. If you are able to provide us with the CPU profile requested we will reopen the issue.
