### ISSUE TITLE
Same behaviour for errors as Quokka

### ISSUE THREAD

**Issue by mjunker** [wallabyjs/public#2227]
### Issue description or question

This is a feature request. When using RxJS I noticed that there's a difference of how Quokka and Wallaby display errors.
When using Quokka an error which is thrown inside an observable is always displayed next to where it's thrown. This would be also really useful in Wallaby.

![Screenshot 2019-10-02 at 11 20 57](https://user-images.githubusercontent.com/528457/66034267-3b11cf00-e509-11e9-8792-3d643e458db9.png)

When I handle the error it's not displayed anymore:
![Screenshot 2019-10-02 at 11 41 36](https://user-images.githubusercontent.com/528457/66034544-b4a9bd00-e509-11e9-8ca5-506dc1ea4410.png)

If I put the same code in a test and run it with wallaby the error is not displayed:
![Screenshot 2019-10-02 at 11 21 39](https://user-images.githubusercontent.com/528457/66034330-58df3400-e509-11e9-8171-6f6dbb610b5f.png)

**Comment by smcenlly** [comment]
@mjunker - We're assuming that you raised this issue by mistake and simply closed it. If not, please let us know.

**Comment by mjunker** [comment]
Yes thanks for asking. I realized the behaviour is actually the same, I just had to add a "done" in the test and it behaves the same as in Quokka.
