### ISSUE TITLE
wallaby with nx lib does not start testing (karma/jasmine) with automatic configuration

### ISSUE THREAD

**Issue by pzurowski** [wallabyjs/public#2232]
### When I try to run tests for the library, I get the following error:

```
Automatic Angular CLI configuration error: Cannot read property 'options' of undefined
```

When I run tests for the application in the same monorepo - everything works (but only with one instance of wallaby, but this is not a part of this issue). Tested with other app (works), and other libs (doesn't work). I would like start wallaby with debug enabled, but how can I do it without configuration file? :)

### Wallaby diagnostics report

Automatic Angular CLI configuration error: Cannot read property 'options' of undefined

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.'.

**Comment by smcenlly** [comment]
Could you please share your Wallaby diagnostics report? To share the report:

* start Wallaby in your project;
* wait until it reports the error;
* run Copy Diagnostics Report command:
  * in VS Code, Atom, or Sublime editor execute Wallaby Copy Diagnostics Report command;
  * in JetBrains IDEs or VS use Wallaby Help | Wallaby.js | Copy Diagnostics Report menu item;
* paste generated report from your clipboard to a newly created issue (feel free to review and edit the report if required).

If you do not have the diagnostics report available, could you please provide us with your editor/editor version, Wallaby extension version, and the output of your Wallaby console log.

**Comment by smcenlly** [comment]
To run Wallaby with debug/trace information without a configuration file, you may create a Wallaby.js configuration file as shown below:

```javascript
module.exports = () => ({
   autoDetect: true,
   trace: true
});
```

You may also specify the trace setting in a wallaby section within your `package.json`, for example:

```javascript
{
  "name": "...",
  ...
  
  "dependencies": {
    ...
  },
  
  "devDependencies": {
    ...
  },
  
  ...
  
  "wallaby": {
    "trace": true
  }
}
```

Having said that, the diagnostic report should provide us with some debug/trace information to assist in resolving your problem.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
