### ISSUE TITLE
Object diff shouldn't highlight reordered properties

### ISSUE THREAD

**Issue by bgoscinski** [wallabyjs/public#2237]
### Issue description or question
Wallaby side-by-side diff highlights properties that were only reordered (their values were the same).

```ts
it('should highlight only diff property addition', () => {
  const original = {
    aProperty: 123,
    bProperty: 456,
    cProperty: 789,
    dProperty: 987,
    eProperty: 765,
    fProperty: 432,
  };

  const { aProperty, ...rest } = original;
  const reordered = { ...rest, aProperty };

  expect({ ...reordered, diff: true }).toEqual(original);
});
```
results in 
![image](https://user-images.githubusercontent.com/5730169/66772997-46c4a480-eebe-11e9-9816-441312f6c146.png)

This diff would be much more helpful if it would only highlight `diff` property addition by diffing objects with properties sorted alphabetically

**Comment by smcenlly** [comment]
We've updated Wallaby to order properties in objects which addresses this request. If you restart your editor, Wallaby should automatically download the latest version of core (v1.0.767) that includes this fix. If Wallaby does not update automatically, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
