### ISSUE TITLE
Wallaby failing to connect to some external site

### ISSUE THREAD

**Issue by azaeng04** [wallabyjs/public#2239]
### Issue description or question
Currently getting a connection refused when downloading wallaby from the VSCode extensions

This is the error I get:
![2019-10-15_16h46_21](https://user-images.githubusercontent.com/13921692/66842409-7da4c400-ef6b-11e9-97c4-8da7b2318492.png)

I navigate to that folder location specified on the error prompt and open up the wallaby.json file

![2019-10-15_16h48_17](https://user-images.githubusercontent.com/13921692/66842462-990fcf00-ef6b-11e9-956b-7d6673f3b8ed.png)

### Wallaby diagnostics report

I cannot start wallaby so I can't get this information

**Comment by azaeng04** [comment]
I never use to get this information before

**Comment by smcenlly** [comment]
Thanks for reporting the problem, it appears that something was corrupted when Wallaby attempted to update itself. Can you please perform the following steps:

1) Close all instances of VS Code
2) Delete the `wallaby.json` file mentioned in the error, `/home/dev/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.147/dist/wallaby.json`
3) Restart VS Code

**Comment by smcenlly** [comment]
We've completed a more detailed investigation and the error stemmed from our automatic update feature not downloading the latest version information correctly. We have released a new version of Wallaby for VS Code (v1.0.148) that has improved error handling for failed downloads. If you haven't already tried the steps above, please update your Wallaby VS Code extension before doing so.
