### ISSUE TITLE
EACCESS permission denied when running VSCode Remote SSH

### ISSUE THREAD

**Issue by kimbui13** [wallabyjs/public#2241]
### Issue description or question

I get and EACCES error when running wallaby in VSCode with Remote SSH extension:

Output:

[Info]  Started Wallaby.js Core v1.0.767
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  console.log: FAIL __tests__/index.test.js
[Info]  console.log:   ● Test suite failed to run
[Info]      EACCES: permission denied, write
[Info]        at Object.send (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:18:24235)
[Info]        at s._sendWithHighPriority (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:23:15975)
[Info]        at ../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:24:4043
[Info]        at s._doWhenReceiverIsReady (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:23:12588)
[Info]        at s._reportProgramScope (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:24:4007)
[Info]        at e.$_$wp (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:24:3757)
[Info]        at Object.<anonymous> (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/projects/41a27e7a1332f38e/instrumented/__tests__/index.test.js:2:1)
[Info]        at Runtime.p._wallabyReplaced.c.requireModule (../../.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/runners/node/jest@0.4.3/initializer.js:14:25888)
[Info]  console.error: Error: EACCES: permission denied, write
[Info]      at writeSync (fs.js:573:3)
[Info]      at SyncWriteStream._write (internal/fs/sync_write_stream.js:22:3)
[Info]      at doWrite (_stream_writable.js:415:12)
[Info]      at writeOrBuffer (_stream_writable.js:399:5)
[Info]      at SyncWriteStream.Writable.write (_stream_writable.js:299:11)
[Info]      at s.u [as reportGlobalError] (/home/kibu/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/server.js:18:24165)
[Info]      at WallabyReporter.onTestResult (/home/kibu/.vscode-server/extensions/wallabyjs.wallaby-vscode-1.0.151/wallaby/runners/node/jest@0.4.3/initializer.js:14:20792)
[Info]      at /home/kibu/dev/wallaby/node_modules/@jest/core/build/ReporterDispatcher.js:93:29
[Info]      at Generator.next (<anonymous>)
[Info]      at asyncGeneratorStep (/home/kibu/dev/wallaby/node_modules/@jest/core/build/ReporterDispatcher.js:10:24)
[Info]      at _next (/home/kibu/dev/wallaby/node_modules/@jest/core/build/ReporterDispatcher.js:30:9)
[Info]      at process._tickCallback (internal/process/next_tick.js:68:7)

Test file:

import { add } from '../index'

describe('wallaby', () => {
    it('should add', () => {
        expect(add(2,3)).toEqual(5)
    })
})

wallaby.js

/* eslint-disable */
process.env.BABEL_ENV = 'test';
process.env.NODE_ENV = 'test';

// tslint:disable

module.exports = function(wallaby) {
  process.env.NODE_PATH = require('path').join(wallaby.localProjectDir, '../../node_modules');

  return {
    files: [

      { pattern: '**/*.ts', load: true },
      { pattern: '**/*.test.ts', ignore: true },
      { pattern: '**/node_modules/**', ignore: true },
    ],

    tests: [
      { pattern: '**/__tests__/**/*.test.ts', load: true },

      // Ignore node_modules
      { pattern: '**/node_modules/**', ignore: true },
      { pattern: 'node_modules/**', ignore: true },
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ useStandardDefaults: true }),
    },

    testFramework: {
      type: 'jest',
    },
  };
};

**Comment by smcenlly** [comment]
We'd previously tested VS Code with Remote SSH and everything was working for us. To make sure nothing has changed, we just installed and set up on a new Ubuntu installation (Ubuntu 18.04.2 LTS), connecting from a Windows host and everything is working for us when running our [calculator-sample](https://github.com/wallabyjs/calculator-sample). _Note that we also had to install chromium-browser._

From the error that you reported, it appears that this error is not related to Wallaby as Wallaby does not have permissions to use `process.stdout` (a requirement for Wallaby to work). The `EACCES: permission denied, write` failure that you reported is when Wallaby is trying to run: `process.stdout.write`. 

Some questions to help diagnose/fix:

* Is it possible that there is a permissions issue with your user on the remote server? 
* Can you connect in VS Code using the terminal? 
* If you run the following from the VS Code terminal, do you get the same error:
  * `node` <ENTER>
  * Once node loads `process.stdout.write('test')` <ENTER>
  * `.exit` <ENTER>

--

We had a [previous issue](https://github.com/wallabyjs/public/issues/2027) with the same problem that includes some additional information that may assist diagnosing/fixing the issue.

Could you also try testing on a different remote server? If Wallaby works on a different server, you will be able to try diffing the two environments to see what's causing the problem.

**Comment by kimbui13** [comment]
Hi Simon, thanks for the fast reply.

Did the test you mentioned: no error.

kibu@kibu-dev:~/dev/wallaby$ node
> process.stdout.write('test')
testtrue
> .exit

Unfortunately, I don't have another remote server at the moment.

Note that actually Wallyby works on the remote servers. But I need to do
ctrl-S for the green markers to appear.

Le ven. 18 oct. 2019 à 19:37, Simon McEnlly <notifications@github.com> a
écrit :

**Comment by smcenlly** [comment]
What is the operating system of your remote server? Is it a standard build that we could try for ourselves?

**Comment by smcenlly** [comment]
Thanks - that is the same operating system we were using for testing. I assume it's just the standard build? Have you been able to test on another ubuntu environment?

**Comment by smcenlly** [comment]
I'm going to close this issue as we haven't heard back. If you worked out what was wrong with your environment, please let us know so we can help others in the future.
