### ISSUE TITLE
Switching to automatic configuration makes some tests fail

### ISSUE THREAD

**Issue by vipirain** [wallabyjs/public#2248]
### Issue description or question

I just switched to automatic configuration and I love it, it's easier and faster.
Before using Wallaby we used jasmine + karma.
We have 3350 unit tests.
After switching to automatic configuration some of them (10) fail and it's always the same problem:

```
    it('correct dateStart should be valid', () => {
      const inputDateStart = debugElement.query(By.css('[formControlName=dateStart]')).nativeElement;
      inputDateStart.value = '1.1.1999';
      inputDateStart.dispatchEvent(new Event('input'));
      inputDateStart.dispatchEvent(new Event('change'));
      fixture.detectChanges();
      expect(inputDateStart.classList.contains('ng-invalid')).toBeFalsy('dateStart should be valid');
    });
```

As you can see, it's a DOM UnitTest.
Fails with this message: Expected true to be falsy 'dateStart should be valid'
When using Karma, the field is valid.

I sent you the diagnostic report via email, since I don't want to share that, sorry.

**Comment by NikGovorov** [comment]
Hi @vipirain,

Thanks for providing us with diagnostic report, unfortunately we could not reproduce the issue. We created an isolated [repo ](https://github.com/wallabyjs/wallaby-2248) with the similar test which passes for us. Could you please fork/clone the [repo ](https://github.com/wallabyjs/wallaby-2248) and change the code in the way that it is closer to your real code and fails the test?

**Comment by NikGovorov** [comment]
I also noticed that you use `test.wallaby.ts` file, from what I can see from the diagnostics report the file is redundant and can be removed.

**Comment by vipirain** [comment]
Hi Nikita,

I made a pull request on my own repository:
https://github.com/vipirain/wallaby-2248/pull/1/commits
Sadly the diff is not showing correctly, don't know why.
Anyway, the angular material directive [matDatepicker] brakes the test.
When removing that directive from the input field "dateStart", the test is
passing.
It's always passing with Karma, regardless of the directive.

Txs
Vito

**Comment by NikGovorov** [comment]
Could you please share your `app.component.ts`? It's not the repository.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by vipirain** [comment]
Thank you very much!
Just one lust thing:
I didn't get the core update when starting wallaby with "automatic"
configuration.
I had to start wallaby using the old "configuration file way" to get the
core update.

**Comment by NikGovorov** [comment]
To [force ](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)Core update from IntelliJ, you need to restart all running instances of the IDE and start Wallaby.js again.

**Comment by vipirain** [comment]
I did restart ... I also received the quokka plugin update, but not the
core update :-(

**Comment by smcenlly** [comment]
Please note that the Wallaby core update is separate from the IntelliJ Wallaby extension. The only reason the core won't update for you is if your license has expired. If your license is valid and it's still not updating for you, please email us a copy of your license (hello@wallabyjs.com).

**Comment by vipirain** [comment]
I'll try to be more explicit and clearer:
My license is fine, I have free upgrades until the 5th of June 2020.
The core did update, now my core is on v1.0.772 as I can see from the
Wallaby Console.
I'm using IntelliJ's run configurations to start Wallaby.
I did restart IntelliJ several times.
When I started Wallaby using the run configuration with configuration type
"Automatic" the core would "not" update.
As soon as I started Wallaby using a run configuration with configuration
type "Configuration File" the core finally did update.

**Comment by smcenlly** [comment]
Closing and restarting IntelliJ should have worked for you. Can you confirm that you closed all opened IntelliJ editors?

**Comment by vipirain** [comment]
Hi Simon,

I hit "Quit IntelliJ IDEA" from the IntelliJ IDEA main menu several times.
I didn't check the running process in the activity monitor. So I'm not 100%
sure.
I will open a new issue if it happens again, next time you release a new
core update.
For now on, again, thank you very very much for solving my problem that
fast.
