### ISSUE TITLE
Autoconfig with NX project, Can't find imports (in tsconfig), info inside.

### ISSUE THREAD

**Issue by iangregsondev** [wallabyjs/public#2249]
### Issue description or question

I setup a previous project using NEST on NRWL NX and all is OK.

Currently on angular, using a AUTOCONFIG.

So i have no wallabyjs file, testing is working as a simple test checking for expect(true).toBeTruthy() works as expected

```
core v1.0.769
console.log: Jest: PASS apps/vault-ui/src/app/app.component.spec.ts

Runtime error: Error: Cannot find module '@vault-ws/core' from 'remote-logger.interceptor.spec.ts'
    at Resolver.resolveModule (./node_modules/jest-resolve/build/index.js:259:17)
    at Resolver._getVirtualMockPath (./node_modules/jest-resolve/build/index.js:390:14)
    at Resolver._getAbsolutePath (./node_modules/jest-resolve/build/index.js:376:14)
    at Resolver.getModuleID (./node_modules/jest-resolve/build/index.js:348:31)
    at Runtime._shouldMock (./node_modules/jest-runtime/build/index.js:942:37)
    at Runtime.requireModuleOrMock (./node_modules/jest-runtime/build/index.js:595:16)
    at Object.<anonymous> (./libs/core/src/lib/interceptors/remote-logger.interceptor.spec.ts:9:31)
    at Runtime._execModule (./node_modules/jest-runtime/build/index.js:867:68)
    at Runtime._loadModule (./node_modules/jest-runtime/build/index.js:577:12)
    at Runtime.requireModule (./node_modules/jest-runtime/build/index.js:433:10)
    at ./node_modules/jest-jasmine2/build/index.js:202:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (./node_modules/jest-jasmine2/build/index.js:27:24)
    at _next (./node_modules/jest-jasmine2/build/index.js:47:9)
    at ./node_modules/jest-jasmine2/build/index.js:52:7
    at new Promise (<anonymous>)
    at ./node_modules/jest-jasmine2/build/index.js:44:12
    at _jasmine (./node_modules/jest-jasmine2/build/index.js:207:19)
    at jasmine2 (./node_modules/jest-jasmine2/build/index.js:60:19)
    at ./node_modules/jest-runner/build/runTest.js:385:24
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (./node_modules/jest-runner/build/runTest.js:161:24)
    at _next (./node_modules/jest-runner/build/runTest.js:181:9)
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/app/a-projects/vault-ui/tsconfig.spec.json
console.log: Jest: FAIL libs/core/src/lib/interceptors/remote-logger.interceptor.spec.ts

console.log: Jest:   ● Test suite failed to run

    Cannot find module '@vault-ws/core' from 'remote-logger.interceptor.spec.ts'
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (libs/core/src/lib/interceptors/remote-logger.interceptor.spec.ts:9:31)


Finished executing 1 affected test(s) in 9.52 second(s)

```

The thing that is concerning is this message

```
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/app/a-projects/vault-ui/tsconfig.spec.json
```

It should not look for the tsconfig.spec.json in the root.... Its in the core directory.

I have a tsconfig       

```
"@vault-ws/core": **["libs/core/src/index.ts"],

```

and in angular.json, I have checked and there isn't anything pointing to a tsconfig.spec.json in the root.

In fact here is the portion of the angular.json

```
       "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/core/jest.config.js",
            "tsConfig": "libs/core/tsconfig.spec.json",
            "setupFile": "libs/core/src/test-setup.ts"
          }
        }
      },
```

These files exist.

when i run wallaby inside of webstorm i get

![image](https://user-images.githubusercontent.com/2370364/67477585-a9eecd80-f65a-11e9-8ced-7c5cb66dd7a2.png)

but this location exists.

### Wallaby diagnostics report

I can give more details, if you let me know what i need to do.

**Comment by iangregsondev** [comment]
ermmm my other project that does work ... also reports missing spec file.... NX doesn't come with this out of the box

```
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/test/nest-common/tsconfig.spec.json
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/test/nest-common/tsconfig.spec.json
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/test/nest-common/tsconfig.spec.json
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/test/nest-common/tsconfig.spec.json
console.error: Cannot locate a tsconfig.spec.json. Please create one at /Users/ian/Development/Work/test/nest-common/tsconfig.spec.json
console.log: Jest: PASS libs/nest-correlation/src/lib/correlation.service.spec.ts (20.761s)
```

So maybe there is no issue as this project also complains but the tests pass..

It seems the first project, that it can't find dependencies 

NX projects are stored under 

/apps

and 

/libs


maybe i can offer better logs or something?

**Comment by iangregsondev** [comment]
Updated the title, as looking over the issue now, it seems those error messages about missing tsconfig.spec.ts file is not right, so the main issue is that wallaby can't find the files to import.

**Comment by smcenlly** [comment]
The only way that we were able to reproduce your problem was when running automatic configuration on the workspace root. Unfortunately this is not supported. From [our Nx/Nrwl docs](https://wallabyjs.com/docs/integration/nrwl.html):

> You may use Wallaby’s automatic configuration within your monorepo, with **an important caveat**. Without changes to your jest configuration files, **Wallaby can only run for one application or library at a time**. When you select your automatic configuration directory, you **must select an application/library directory**, and **not the monorepo root directory**.

If you want to run Wallaby on all Applications, APIs and Libraries at the same time, then you will need to configure jest so that it can run on your project root using `npx jest`. We have [some instructions](https://wallabyjs.com/docs/integration/nrwl.html#how-to-run-wallaby-on-the-entire-monorepo) for how to do this on our website. Depending on customizations you have made to your project, you may need to make further changes. We recommend first getting everything working using jest from the CLI with `npx jest` and then Wallaby will just work.

--

If you are getting an error when running automatic config on a specific application/library, could you please let us know and provide a sample repo that has the problem and we will re-open this issue.

**Comment by iangregsondev** [comment]
@smcenlly Thanks, I think I have it working now, although something was a little unclear even after reading the document.

Adding the global is to each jest.config.js in ever directory ? 

I didn't do this, but it seems to work.

What I did was I created a tsconfig.spec.json in the ROOT and added the global to the ROOT jest.config.js file.

Did I mess up ?

Did i need to create a tsconfig.spec.json in the root ?

And should I have actually added the global to every jest.config.js in every lib / app directory ?

Can you confirm, I am just looking for confirmation 

Thanks!

**Comment by smcenlly** [comment]
> Adding the global is to each jest.config.js in ever directory ?

Yes - our instructions were to do this for every directory. 

What you did in the root is OK and will work if you run Wallaby with automatic configuration for your entire mono-repo. If you want to run only one project within your mono-repo by specifying automatic configuration to run on a sub-folder then you will need to add the configuration to the projectgs as well.

**Comment by iangregsondev** [comment]
@smcenlly Thanks.. Yes I took the root of running wallaby on the complete mono-repo otherwise i would need to create run configurations for each app and lib - there are quite a lot.

What i did notice is that i can run unit tests (without wallaby) in my ide and debug them - this did require the change to the jest.config in each directory.

So I ending it with adding them to all directories and the root and adding the tsconfig.spec.json to the root...

so now I have wallaby running on the complete mono-repo and i am able to debug individual tests in webstorm.

I think the only downfall with running wallaby on the complete mono-repo is that it only takes into consideration the jest.config.js and tsconfig.spec.json in the root... and ignores that items in the libs and apps..

But having to create a run config for each directory seems kind of overkill for me :-(

**Comment by smcenlly** [comment]
> I think the only downfall with running wallaby on the complete mono-repo is that it only takes into consideration the jest.config.js and tsconfig.spec.json in the root... and ignores that items in the libs and apps..

Yes, but normally those files are the same. Is that the same in your case?

If everything is working in Wallaby then you don't need to do anything further.

**Comment by iangregsondev** [comment]
@smcenlly Exactly, these files for me are the same - so nothing further is needed.
