### ISSUE TITLE
How does wallaby IDE plugin communicates with the running tests? (i.e. receives data)

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#225]
I have not looked very deep but it seems that there is a server.js file somewhere that receives data from a running test?

I'm thinking of a solution for the protractor (and others) required (see https://github.com/wallabyjs/public/issues/125)

**Comment by ArtemGovorov** [comment]
Simplified process looks like this: [wallaby.js core](http://wallabyjs.com/docs/intro/how-it-works.html) instruments (source and test) code and generates a sandbox for a specific test runner (phantomjs/node). When instrumented code executes, it sends the data back to the core. The data is processed and sent to the IDE.

Solution for Protractor/Webdriver will need a few things: most likely creation of a new test runner capable of handling incoming data from both browser executed code context and protractor tests node context and connecting those 2 to track dependencies, integration with the testing framework protractor is using (the one built on top of jasmine), and a few more bits and pieces.

**Comment by peter-watters** [comment]
+1
