### ISSUE TITLE
Automatic Jest configuration error: Module jest-cli is not found in '.'.

### ISSUE THREAD

**Issue by sergey-kudriavtsev** [wallabyjs/public#2254]
Hi all!
I can not understand the reason
I am using mocha
my wallaby.conf.js
```js
module.exports = function (wallaby) {
  return {
    files: [
      'Services/Commons/core/*.js'
    ],

    tests: [
      'Services/Commons/test/**/*spec.js'
    ],
    testFramework: 'mocha',
    debug: true
  };
};
```
but at startup I get an answer
**Module jest-cli is not found in '/work/projects/prod**
```
Wallaby Console: Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '/work/projects/prod
(anonymous)	@/home/dev/.atom/pack…ex.js:formatted:677
arrayEach	@/home/dev/.atom/pack…odash/index.js:1286
forEach	        @/home/dev/.atom/pack…odash/index.js:5700
(anonymous)	@/home/dev/.atom/pack…ex.js:formatted:676
emit	        @events.js:182
(anonymous)	@/home/dev/.atom/pack…nt.js:formatted:112
(anonymous)	@/home/dev/.atom/pack…nt.js:formatted:311
emit	        @events.js:182
addChunk	@_stream_readable.js:279
readableAddChunk@_stream_readable.js:260
Readable.push   @_stream_readable.js:219
onread	        @net.js:636
```
Atom: 1.40.1
Electron: 3.1.10
Chrome:66.0.3359.181
Node:v10.2.0
Wallaby Console: Started Wallaby.js Core v1.0.766

**Comment by smcenlly** [comment]
The error indicates that Wallaby is not using your configuration file and is instead using "automatic configuration". To run a configuration file, please select it in your editor. Steps to select a configuration file are described in our docs:

* [VS Code](https://wallabyjs.com/docs/intro/get-started-vscode.html)
* [JetBrains](https://wallabyjs.com/docs/intro/get-started-jetbrains.html)
* [Visual Studio](https://wallabyjs.com/docs/intro/get-started-vs.html)
* [Atom](https://wallabyjs.com/docs/intro/get-started-atom.html)
* [Sublime Text](https://wallabyjs.com/docs/intro/get-started-sublime.html)

**Comment by sergey-kudriavtsev** [comment]
I understand why there was an error, I have a question why the configuration file is in the project, but the plugin does not raise it, but uses its own by default.

[See doc desdriptions](https://wallabyjs.com/docs/intro/get-started-atom.html#selecting-wallabyjs-config-file)

Wallaby.js for Atom needs to know what configuration file to use to run your tests. If you only have one file named wallaby.js/wallaby.conf.js in your project root, **wallaby will automatically select it.**

**Comment by smcenlly** [comment]
It looks like there's an edge case when you add a new wallaby configuration file to your project. Currently Wallaby is only looking for a configuration file when Atom first loads your project. We will update this behavior in the next release of Wallaby Atom. 

Does that explain why the default behavior didn't work for you?

**Comment by sergey-kudriavtsev** [comment]
I think no.
I tried to open the project (atom [/ my_path / ..]), it started right away from the project, the result is the same, only it manually sets.
I assume that you are in the right direction, after installation, the start event for wallaby is not set, and wallaby does not respond.

**Comment by ludwighogstrom** [comment]
Hi! I had the same error with WebStorm / Jest and Automatic configuration type `Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in...`. 

When I updated the default nvm version (previous 8.x.x) to 12.x.x it started to work (`nvm alias default 12.18.4`).

**Comment by maccurt** [comment]
My issue was I was in a visual studio solution (in visual studio code) (c#) and I was not at the root of the Angular Project, if I opened visual studio code at the folder where my angular project was this error went away. Can I change some config to make this not happen?

**Comment by smcenlly** [comment]
@maccurt - you may try using the `Wallaby.js: Select Configuration` command and the `Automatic Configuration <custom directory>...` option. You will be prompted for your project location, select the folder that has your angular project.

**Comment by maccurt** [comment]
Thanks, that worked for me.

**Comment by dht** [comment]
From my experience using the "select configuration..." in a VSCode workspace fails to find the node_modules

**Comment by smcenlly** [comment]
@dht - if you are having problems, please [create a new issue](https://github.com/wallabyjs/public/issues/new/choose) and provide your diagnostic report when you have the problem. Please also detail your project structure, it should help us identify why it's not working for you (and fix it, if it is a problem with Wallaby).

**Comment by dht** [comment]
The same issue as here. When I open a "workspace in VSCode" (same term, not related to Yarn/Npm workspaces) and I choose "Wallaby.js: Select Configuration" and I select a "wallaby.js" file which is not in the root of the workspace (again VSCode workspace, not Yarn/Npm) I get: 
```
‌[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```
If I open a new VSCode window with the same folder which consists of the "wallaby.js" and run follow the same steps, everything works as expected. So I think it is important to have this here as some people who will experience the error specified in the issue's title are probably trying to run Wallaby in a VSCode Workspace setup.

**Comment by smcenlly** [comment]
If you are using a `wallaby.js` configuration file, the file must be in your project root for Wallaby to work.

**Comment by dht** [comment]
oh, Interesting to know...
I've successfully used it differently for quite some time now.
In a large mono-repo setup I create a `wallaby.js` for each package.
It saves me the time of filtering the tests I want to run.

**Comment by alecmce** [comment]
I've just started seeing this issue again. I'm seeing a "Automatic Jest configuration error: Module jest-cli is not found in '.'" error when trying to run wallaby over a vitest project that has been working without problems until a recent update. (Yes, I will raise a new issue, just leaving this here as this is the first result on a Google search)

**Comment by bj97301** [comment]
restarted vs code seemed to fix it for me.  maybe some strange package ref somewhere with a node version... dunno
