### ISSUE TITLE
Run multiple test configurations (reactjs and Apollo)

### ISSUE THREAD

**Issue by saltzmanjoelh** [wallabyjs/public#2255]
I have 2 projects in typescript. A reactjs project and an Apollo project. Both are using the automatic configuration in separate VSCode projects.

However, I like all the source in a single project with a structure similar to this:
/project_name (root of Apollo project)
  /client (reactjs project)
  /src (Apollo project code)
package.json (for Apollo)
...etc

Wallaby runs the Apollo tests just fine. Is there a way to get wallaby to also run the tests for the reactjs project that are started via the `npm test` or `react-scripts test` from the client dir? The reactjs project has different compiler requirements and package dependencies otherwise I would think just make the Apollo tests include the react tests would be an option.

**Comment by smcenlly** [comment]
When Wallaby is configured to run on a given folder, there is some special case handling to support running with react-scripts and nx/nrwl mono repos. When you run on a folder that isn't a react project, Wallaby uses jest to find all of the sub-folder configurations, which does not work for react projects. 

To get this working, you will need to make sure that `npx jest` runs for your react application from your mono-repo root. 

If you were to temporarily eject your react application (and then undo the changes), it should create the jest configuration you need in your package.json and a few other files that are required by jest. You can use these details to work out how to configure jest to run using `npx jest`.

**Comment by saltzmanjoelh** [comment]
@smcenlly npx jest will run the server tests from the root of the monorepo. It will also run from the client directory. Do I need to do anything special to get wallaby to execute both test configurations? It's only running the server tests at the root.

[Diagnostics.txt](https://github.com/wallabyjs/public/files/3800243/Diagnostics.txt)

**Comment by saltzmanjoelh** [comment]
For anyone curious, I was able to get this working with a few steps.

React Goal: Get the config for jest in react project
At the bottom of node_modules/react-scripts/scripts/test.js I replaced the last line `jest.run(argv);` with `console.log(argv);`
Then ran npm test. This prints the react configuration as a json string.
I copied that to a jest.config.js file
Now when I ran `npx jest` I received some errors out formatting like moduleNameMapper was an array instead of object. I fixed the few errors that came out until `npx jest` ran without any errors.

Apollo Goal: Run both Apollo and react tests
With `npx jest` working, I needed to additionally be able to run the react tests. However, I couldn't just include the react tests in the Apollo project because each one has different dependencies and compiler settings.
The format for the jest config that I was used to working in was like this:

`module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  ...
}`

Jest supports multiple runners. You just have to move the project configuration into an array of configurations under the projects key:

`module.exports = {
  projects: {[
    {
      displayName: "apollo",
      preset: 'ts-jest',
      testEnvironment: 'node'
      ...
    }
  ]}
}`

That is a single runner that will execute the Apollo tests. The trick to get the react tests running now is to simply provide a path to the jest.config.js that we created above. You don't need to duplicate the configuration .

`module.exports = {
  projects: {[
    {
      displayName: "apollo",
      preset: 'ts-jest',
      testEnvironment: 'node'
      ...
    },
    'client/jest.config.js' //react runner
  ]}
}`

**Comment by saltzmanjoelh** [comment]
Actually, I'm able to get `npx jest` to run at the root of my project but wallaby is only running the server tests. It's skipping the client tests for some reason...

**Comment by smcenlly** [comment]
@saltzmanjoelh - is it possible to send us a sample repo with the same structure and jest configuration that you are using? We won't need any application files, just a dummy test in each project.

**Comment by saltzmanjoelh** [comment]
@smcenlly https://github.com/saltzmanjoelh/wallabyjs-2255

Let me know if you need anything else.

**Comment by saltzmanjoelh** [comment]
@smcenlly Not sure if it helps or not but `npx jest --watch` only seems to watch one project..

**Comment by smcenlly** [comment]
Thanks for letting us know - we're taking a look at why both projects are not running and will update this ticket when we completed our investigation.

**Comment by smcenlly** [comment]
Thanks for reporting the problem and for your sample repo. We needed to make a few changes to support your configuration in our jest integration. This is fixed and available in the latest version of Wallaby core, v1.0.781. Wallaby should update automatically with the latest version that fixes the problem. If Wallaby does not update automatically, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by saltzmanjoelh** [comment]
@smcenlly Awesome! It worked, thank you so much for the quick work. I will buy a license for sure.
