### ISSUE TITLE
Invalid links are created

### ISSUE THREAD

**Issue by dnicolson** [wallabyjs/public#2256]
### Issue description or question

Depending on surrounding code, links can be arbitrarily created.

![Screen Shot 2019-11-01 at 13 04 54](https://user-images.githubusercontent.com/2276355/68023962-11cf9480-fca9-11e9-9c1c-16f0cc0fa567.png)
![Screen Shot 2019-11-01 at 13 07 35](https://user-images.githubusercontent.com/2276355/68023965-11cf9480-fca9-11e9-86f1-4fff51f42b0b.png)
![Screen Shot 2019-11-01 at 13 05 20](https://user-images.githubusercontent.com/2276355/68023964-11cf9480-fca9-11e9-9550-e975bed1646e.png)

### Wallaby diagnostics report

The `Copy Diagnostics Report` was run but I couldn't find any report.

Visual Studio Code v1.39.2
Wallaby.js v1.0.153

**Comment by smcenlly** [comment]
> Depending on surrounding code, links can be arbitrarily created.

Are these links in your code file, or in your Wallaby output window? The look like they are in your code file. If this is the case, they are not generated by Wallaby. The only hover provider that Wallaby adds is for displaying diffs.

![image](https://wallabyjs.com/assets/img/vsc_diff.gif)

---

Are you running Wallaby through a remote ssh, remote docker, or wsl? The `Copy Diagnostics Report` copies the report to your clipboard. If you're connected to a remote environment, this may explain why the report did not work for you.

**Comment by dnicolson** [comment]
The issue occurs in a code window, disabling the extensions resolves the issue:

![out2](https://user-images.githubusercontent.com/2276355/68061883-5853dc00-fd07-11e9-8f3c-c2012f21ba06.gif)

**Comment by ArtemGovorov** [comment]
- Can you try clicking the link to see what happens?
- Can you try disabling all other extensions and the enabling Wallaby extension only to see if you can reproduce the issue?

**Comment by smcenlly** [comment]
Could you also please run `code --list-extensions` from the command line and provide us with the output? This will let us install the same extensions as you have to identify if there is some sort of conflict.

**Comment by dnicolson** [comment]
Clicking the link results in this:
![Screen Shot 2019-11-06 at 11 22 10](https://user-images.githubusercontent.com/2276355/68292884-1a4f1300-008d-11ea-8207-34c3c29e60c9.png)

I can reproduce it with the following extensions enabled:
dnicolson.binary-plist
WallabyJs.wallaby-vscode
eamodio.gitlens

Strangely the issue persists after disabling the Wallaby extension, but the problem is not reproducible without first enabling Wallaby.

**Comment by NikGovorov** [comment]
Hi @dimitropoulos,

I can reproduce the issue with only dnicolson.binary-plist and eamodio.gitlens installed.

![gitlens-binary-plist](https://user-images.githubusercontent.com/129254/68352192-65caf500-0151-11ea-878b-7fe05364bfe0.gif)

I'm closing the issue as it is not Wallaby.js specific problem.
