### ISSUE TITLE
Feature request - specify mocha version in configuration

### ISSUE THREAD

**Issue by jlweston** [wallabyjs/public#2258]
### Feature request - specify mocha version in configuration

I work on several projects that are still using old dev dependencies - among these is mocha v2. We have a large number of tests that fail on newer versions of mocha due to being overspecified (https://github.com/mochajs/mocha/issues/2407), which results in these tests not being run by wallaby and code coverage being reported incorrectly.

I can see that wallaby's configuration allows us to specify the test framework but does not allow us to tie this to a particular version. I would love to see the ability to specify the version of mocha and use wallaby with these projects.

**Comment by smcenlly** [comment]
By default, if your wallaby `testFramework` setting is `mocha` then Wallaby will try and our integration with the most recent version. You may also tell Wallaby to use a specific version of our integration with mocha. 

Please try updating your wallaby `testFramework` setting to `mocha@2.2.4` or `mocha@2.0.1`.

If neither of those settings work for you, please provide us with a sample repo so we can see your project dependencies and the test that is failing.

**Comment by jlweston** [comment]
After updating my config as suggested, I'm getting the following error when wallaby starts:

`{"message":"Cannot find module 'node_modules/mocha'","stack":...}`

In what format does wallaby expect the path? Should it be relative or absolute, and should the path be to the root of the module or to the mocha binary itself?

**Comment by smcenlly** [comment]
There was a bug in Wallaby which was forcing mocha to always use version 5.2.0. This has been fixed in the latest version of Wallaby core, v1.0.776. Wallaby should update automatically for you at which point, you can remove the `path` setting from your configuration file and everything should work for you. If Wallaby does not update automatically, you may [force the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by jlweston** [comment]
Looks like that's done the trick. I'm still working through some config issues to get legacy projects working but at least it's using the local version of mocha now!

Appreciate the quick turnaround on this. Between the great app itself and the outstanding support, I'm pretty likely to be upgrading my trial license shortly!
