### ISSUE TITLE
weird angular.module not found, solved by clearing projectCacheDir

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#226]
Just in case others see the same thing, I just had a really weird error where if I added an new controller on a new file I would get the error

```Error: [$injector:nomod] Module '{module name}' is not available! You either misspelled the module name or forgot to load it```

but If added the same code in a file that already existed, it would work ok

After multiple attempts at figuring out the prob (for example by reducing the number of files loaded), I was able to 'fix it' by deleting all files from ```~/Library/Caches/WebStorm10/wallaby/projects```

It feels like somehow that file was not loaded into the same session than the other files

Note that I'm also able to run the exact same tests using Karma, which was able to run the tests successfully

The tests I was running are the ones from the the Dev branch of https://github.com/TeamMentor/TM_Angular (namely at this commit https://github.com/TeamMentor/TM_Angular/tree/c9bdf38b1e0a60b3e55198756cf352c59e34325c )

**Comment by ArtemGovorov** [comment]
Considering that deleting files from `~/Library/Caches/WebStorm10/wallaby/projects` helped, it's most likely [the caching issue](https://github.com/wallabyjs/public/issues/81).

A quick hint if happens again - perhaps a slightly easier way to clear wallaby cache is to [make any change to the project config file](http://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working).

**Comment by DinisCruz** [comment]
> A quick hint if happens again - perhaps a slightly easier way to clear wallaby cache is to make any change to the project config file.

that wouldn't had helped since I was having the issue while making changes to the project config file :)
