### ISSUE TITLE
Jest: Automatic configuration support for webpack plugins (importing of graphql files fail)?

### ISSUE THREAD

**Issue by iangregsondev** [wallabyjs/public#2260]
Hi,

I moved over to automatic configuration in my API (using nestjs etc) and works great.

I also moved over to automatic configuration in my angular project, and it appeared to work great but

I am getting errors,

```
SyntaxError: Unexpected identifier

	at apps/ui/src/app/core/graphql/update-user-profile.mutation.graphql:1
	at Object.<anonymous> apps/ui/test/app/modules/account/pages/account-detail/account-detail.component.spec.ts:24:1
```

and I think it might be related to the webpackconfig, you see i have an additional plugin that allows me to import .graphql files, it is configured like so

```
  config.module.rules.push({
    test: /\.(graphql|gql)$/,
    use: [
      {
        loader: "graphql-tag/loader"
      }
    ]
  })
```

This allows me to do in code the following

```
import updateUserProfileMutation from "../graphql/update-user-profile.mutation.graphql"
```

I think it maybe related to wallaby not picking up the webpackconfig etc..

even running npx jest, hightlights the issue

```
    SyntaxError: Unexpected identifier

      26 | 
      27 | import { ErrorService } from "@app/core/services/error.service"
    > 28 | import updateUserProfileMutation from "../graphql/update-user-profile.mutation.graphql"

```

I really hope I don't have to go back to non automatic configuration :-(

Can anyone help me ?

If i did have to go back to NON automatic configuration, is it possible to get automatic configuration to output the config file that it is using internally - so  i have a starting point..

Looking forward to any insight anyone can offer

Thanks

**Comment by ArtemGovorov** [comment]
> even running npx jest, hightlights the issue

The issue is not Wallaby specific then because plain Jest shows the exact same error. Jest doesn't support webpack plugins and you may need to install and specify a transform for this type of files. I have done a quick search and it looks like you may need something like [this transform](https://github.com/remind101/jest-transform-graphql) to be installed and added to your Jest config.

**Comment by iangregsondev** [comment]
Thanks, I think i got the following working

```
  transform: {
    "\\.(gql|graphql)$": "jest-transform-graphql",
    "^.+\\.(ts|js|html)$": "ts-jest"
  },
```

```
  moduleFileExtensions: ["ts", "js", "html", "graphql"],
```

well, it certainly has stopped complaining about it :-)
