### ISSUE TITLE
[Error] c:\Users\{Username}\.vscode-insiders\extensions\wallabyjs.wallaby-vscode-1.0.156\wallaby\node_modules\chokidar\index.js:151 -  [Error]   async remove(item) { 

### ISSUE THREAD

**Issue by agarwalprashant** [wallabyjs/public#2264]
[Error] c:\Users\{Username}\.vscode-insiders\extensions\wallabyjs.wallaby-vscode-1.0.156\wallaby\node_modules\chokidar\index.js:151 
[Error]   async remove(item) { 
[Error]         ^^^^^^ 
[Error] SyntaxError: Unexpected identifier 
[Error]     at Object.exports.runInThisContext (vm.js:76:16) 
[Error]     at Module._compile (module.js:542:28) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at require (internal/module.js:20:19) 
[Error]     at Module._compile (module.js:570:32) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at Module.runMain (module.js:604:10) 
[Error]     at run (bootstrap_node.js:394:7) 
[Error]     at startup (bootstrap_node.js:149:9) 
[Error]     at bootstrap_node.js:509:3

**Comment by ArtemGovorov** [comment]
We have recently updated some of our dependencies and it looks like your version of node is too old (older than 7.6?) to be used with it. You may renew your node version to get it working. If you don't want to renew your system node version, you may install another newer version side by side (via `nvm` or somehow else) just for Wallaby and [specify the path in your VS Code settings](https://wallabyjs.com/docs/intro/install.html#nodejs-1).
