### ISSUE TITLE
Module version mismatch. Expected 43, got 14 when using level package

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#227]
This looks like the same problem with https://github.com/sgentle/phantomjs-node/issues/279

Here the error I get

![image](https://cloud.githubusercontent.com/assets/656739/9155045/69224468-3ea2-11e5-843f-2e7b653c3a8d.png)

Does this mean that I need to compile my node_modules with io.js? I was trying to avoid that since I wanted (for now) to keep the main code base on node.js

**Comment by ArtemGovorov** [comment]
You [can configure node.js version](http://wallabyjs.com/docs/integration/node.html) you'd like to use to run your tests. 

``` JavaScript
module.exports = function () {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    env: {
      type: 'node',

      // if runner property is not set, then wallaby.js embedded node/io.js version is used
      // you can specifically set the node version by specifying 'node' (or any other command)
      // that resolves your default node version or just specify the path
      // your node installation, like

      // runner: 'node'
      // or
      // runner: 'path to the desired node version'
    }
  };
};
```

Please let me know if it doesn't work for you.

**Comment by DinisCruz** [comment]
ok that seems to have done the trick
