### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#2274]
### Issue description or question

Hi, I'm geeting following error on ALL my projects. Tried reinstalling wallaby to no avail:

```
[Error] TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type number 
[Error]     at Function.from (buffer.js:219:9) 
[Error]     at Server.emit (events.js:203:13) 
[Error]     at onParserExecuteCommon (_http_server.js:605:14) 
[Error]     at onParserExecute (_http_server.js:544:3) 
```

### Wallaby diagnostics report

Diagnostic report does not work as wallaby never starts  and is hanging on loading.

**Comment by tomitrescak** [comment]
Tried downgrading visual studio to 1.39 to no avail.

**Comment by smcenlly** [comment]
Could you please try forcing a core update? Are you using VS Code, if so please open the editor and launch the Command Pallete using Ctrl/Cmd + Shift + P, then run the command Wallaby.js: Force Core Update.

If you're using a different editor, please follow the instructions from [our docs](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If the command doesn't work, could you also please send us your `%HOMEDIR%/.vscode/extensions/wallabyjs.wallaby-vscode-XXXXX/wallaby/package.json` file? Can you also please tell us what your license expiry date is?

**Comment by tomitrescak** [comment]
@smcenlly thanks guys for a rapid response! I deleted the extension from the homedir and re-registered the license. All works now. Must have been some botched update.
