### ISSUE TITLE
Testing an angular app with librairies.

### ISSUE THREAD

**Issue by bokzor** [wallabyjs/public#2283]
Hi,
I have an angular app with some libraries using the  automatic configuration.

It seems that tests from librairies are not executed. 
Ss there a way to run them with the automatic configuration ?
Regards

**Comment by NikGovorov** [comment]
Hi  @bokzor,

Wallaby should run your libraries' tests by default if you choose to run Wallaby for the whole workspace

![ScreenClip](https://user-images.githubusercontent.com/129254/70006724-f1ea0400-15b9-11ea-9177-1a850315c643.png)

If it does not run the tests for some reason, could you please share Wallaby Diagnostics Report?

### Wallaby diagnostics report

Wallaby Diagnostics Report is a simple JSON text report that contains some basic information
about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
@bokzor - did you get Wallaby working? If not, please let us know and provide the diagnostics report requested by @NikGovorov and we will re-open this issue.
