### ISSUE TITLE
Wallaby JS never starts

### ISSUE THREAD

**Issue by adriandavidbrand** [wallabyjs/public#2285]
In VS Code I get this icon

![image](https://user-images.githubusercontent.com/39876791/70196586-f26ad200-1754-11ea-8001-ef327700a357.png)

Where the equals signs is moving back and forward but never stops. Is this an issue with our corporate firewall? Does Wallaby JS download it's dependencies through the proxy settings?

**Comment by smcenlly** [comment]
Was Wallaby ever working for you on this computer? Or is this a new installation?

You may like to check out the Wallaby Console (VS Code Output Window) as it may have additional information.

If you are running behind or corporate firewall then you may try setting the Wallaby VS Code setting, `Wallaby: Use Http For Download` to `true`. You may also refer to our [Offline Installation](https://wallabyjs.com/docs/intro/offline.html) instructions to install without any network connection.

**Comment by adriandavidbrand** [comment]
Turning off Strict SSL seemed to fix it for me
