### ISSUE TITLE
"Debug Test" doesn't find the test I'm in

### ISSUE THREAD

**Issue by oliversturm** [wallabyjs/public#2296]
### Issue description or question

I have a test that begins with the following code. I have highlighted four positions in the code using markers like `<<<< X >>>>`.

```js
describe('manual start', () => {
  test('concurrency 1', () => { <<<< A >>>>
    jest.clearAllMocks(); <<<< B >>>>
    resolveRecorder.reset();
    rejectRecorder.reset();

    const q = makeQueue
      (1)
      (false) <<<< D >>>>
      (createFuture)
      (resolve)
      (reject);

    q.add <<<< C >>>>
      ({ success: true, val: 42, after: 50 });
    q.add
      ({ success: true, val: 43, after: 50 });

    let start;

  ...
```

When I use the *Debug Test* command in positions A, B or C, the debugger is started correctly and stops at the location. However, for position D Wallaby executes all tests in my project instead. My guess is that something goes wrong with the algorithm used to detect the block I'm in - perhaps this even has to do with formatting?

I checked the diagnostic log, but unfortunately I can only see in there that tests were executed - there is no indication at all about the process of finding the correct context when running *Debug Test*.

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core version 1.0.800](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
