### ISSUE TITLE
Alt+W shortcut conflict with opening Window menu in Visual Studio

### ISSUE THREAD

**Issue by joaroyen** [wallabyjs/public#230]
I use Alt+W to access the Window menu, and the default WallabyJS key bindings override the expected behavior.

Workaround: Re-bind Wallaby.* keyboard bindings in the options dialog. Ctrl+Shift+Alt+W is available on my machine, but not sure if that is the best combination to use.

**Comment by ArtemGovorov** [comment]
Another solution would be to use [Alt, W] (Alt and the W after a short delay) to access the Window menu.

**Comment by joaroyen** [comment]
I ended up adding 'Alt+W, L' keyboard binding to Close All Documents, which is the way I'm used to.

This is not a big issue yet, but if you introduce more default keyboard shortcuts, you should think about doing something similar to ReSharper by asking the user if the shortcut should be modified.

**Comment by ArtemGovorov** [comment]
@joaroyen ReSharper way sounds good, we should do something similar, thanks for the idea.
