### ISSUE TITLE
Failed to load configuration file: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2302]
I have started a Wallaby with this Config File

```
module.exports = function () {
  return {
    env: {
      type: 'node',
    },
    ignoreFileLoadingDependencyTracking: true,
  }
}
```

and it failed.

At the same time, autoconfiguration works well

### Failing Tests
```
Cannot read property 'type' of undefined
```

### Wallaby Console
```
wallaby.js started
core v1.0.806
Failed to load configuration file: Cannot read property 'type' of undefined
```
### Wallaby diagnostics report

Unfortunately, the diagnostics report failed to be generated. Probably because the crash occurred on too early stage

### Expected result

If there is really something wrong with the config, the error should not be confusing and explain what I, as a user, have done wrong and how can I fix it

**Comment by smcenlly** [comment]
Thanks for reporting the error - this was a bug in our logic that parsed your configuration file. There is indeed something wrong with your configuration. If you update to the latest version of Wallaby.js core (v1.0.807) you will now get a message that says: "Files property must be non-empty array of files/file patterns". 

If you need assistance configuring Wallaby, [our docs](https://wallabyjs.com/docs/intro/config.html) should help. We also have a [page with examples](https://wallabyjs.com/docs/intro/examples.html) that you may find useful. If you are stuck or have a sample you can provide, we're happy to take a look at the configuration for you.
