### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by buisonthai1310** [wallabyjs/public#2306]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.162`
- OS Version: `Windows_NT ia32 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\KIM ANH\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smcenlly** [comment]
@buisonthai1310 - could you please provide the attachment referenced in your issue description: `C:\Users\KIM ANH\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`?

**Comment by smcenlly** [comment]
I'm going to close this issue as we haven't heard back. If you are able to provide the requested attachment, we will re-open the issue.
