### ISSUE TITLE
Wallaby "compile" in VsCode prevents autohotkey shortcut (CapsLock mapped to Ctrl)

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2310]
### Issue description or question

I use AutoHotKey and have mapped CapsLock to Ctrl key. Whenever I hit CapsLock+S to save a file when WallabyJs is compiling, it prevents save and writes and "s". After WallayJs has compiled CapsLock+S works as expected again. Standard Ctrl+S works fine.

See below when typing ```oioi<save>, oioi<save>```... (miscTsSpec.ts is saved after Wallaby error is shown, before it writes "s" in editor instead of saving)
![wallaby](https://user-images.githubusercontent.com/31244330/72145554-0e3c4600-339b-11ea-9388-df03c2f48fb2.gif)

### Wallaby diagnostics report

```
{
  editorVersion: '1.41.1',
  pluginVersion: '1.0.163',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.18362',
  nodeVersion: 'v13.5.0',
  coreVersion: '1.0.815',
  config: {
    files: [
      { pattern: 'lib/jquery.js', instrument: false, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 }
    ],
    tests: [ { pattern: 'test/**/*Spec.ts', ignore: false, trigger: true, load: true, test: true, order: 3 } ],
    env: { kind: 'chrome', type: 'browser', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    debug: true,
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.4.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: 'module.exports = () => {\r\n' +
      '  return {\r\n' +
      '    files: [\r\n' +
      "      {pattern: 'lib/jquery.js', instrument: false},\r\n" +
      "      'src/**/*.ts',\r\n" +
      '    ],\r\n' +
      '    tests: [\r\n' +
      "      'test/**/*Spec.ts'\r\n" +
      '    ],\r\n' +
      '    env: {\r\n' +
      "      kind: 'chrome'\r\n" +
      '    },\r\n' +
      '    debug: true\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  fs: { numberOfFiles: 4 },
  debug: [
```

**Comment by smcenlly** [comment]
Do you get the same behavior without using the autohotkey extension?

Can you please provide us with the complete list of your VS Code extensions by running this command from your terminal: `code --list-extensions`.

We have seen a similar issue with other extensions in the past that has been caused problems with Wallaby because of extensions using `vscode.window.activeTextEditor` to get the active text editor instead of the getting the editor from the relevant VS Code event that is being processed. The way VS Code works is that when your console output windows are updated (like they are when Wallaby runs) the active text editor changes (to the console) which can cause problems if using `activeTextEditor`. 

Once we hear back from you and have your list of all your plugins, we'll attempt to duplicate and then identify the root cause.

**Comment by greenmooseSE** [comment]
I can no longer reproduce this any longer for whatever reason (AutoHotKey crashed and after I restarted today I can no longer reproduce it). Closing the issue.

Thanks.

PS:
> Do you get the same behavior without using the autohotkey extension?

[AutoHotKey](https://www.autohotkey.com/) is not a VSCode extension, it is a keyboard remapper for Windows.
