### ISSUE TITLE
Tooltip when hovering squares

### ISSUE THREAD

**Issue by ekaradon** [wallabyjs/public#2311]
### Feature request: add information when hovering squares

As a newcomer, I would just like to have at least basic information about square colors when hovering these. For example, when hovering a yellow square, I would like to be reminded that yellow stand for:
`Yellow square means that the source line is only partially covered by some of your tests.`
Furthermore, this explanation is really hard to find in your documentation. I find myself always [googling](http://dm.gl/2015/11/26/wallaby-for-visual-studio-code/) it instead of searching this in your documentation as I have no idea where to find this. 
This feature could be nicely enhanced after that by providing detailed information, for example, which parts are not covered.

**Comment by smcenlly** [comment]
@ekaradon - Thanks for the feedback. We'll be updating our docs today with a new "Code Coverage" section to make this easier to find.

Out of interest, which editor are you using? We are limited at times with what we can display in the editor based on the editor extension API capabilities.

**Comment by ekaradon** [comment]
VSCode

**Comment by smcenlly** [comment]
We thought that might be the case. Unfortunately we can't do anything in VS Code to improve the editor experience. We have added a new [code coverage](https://wallabyjs.com/docs/intro/coverage.html) page that should make this more discoverable in the future.

**Comment by ekaradon** [comment]
Yes, thanks. It is now really much easier to find it. :)
