### ISSUE TITLE
Feature request: time travel back to field assignment

### ISSUE THREAD

**Issue by JonathanMEdwards** [wallabyjs/public#2318]
### Issue description or question

The essential killer feature of time-travel debugging is the ability to go back to the previous statement that assigned a field. Please consider that.

**Comment by smcenlly** [comment]
@JonathanMEdwards - thanks for the suggestion. This was something that we had also considered but there are currently some JavaScript runtime limitations that we haven't figured out how to solve that are preventing us from providing this as a feature. 

Earlier this week we released a new Live Value Display feature, **Object Proxy** that helps address your feature request (but not quite the same thing). 

The feature allows you to wrap any selected object value with [JavaScript Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to quickly see where the wrapped object properties are being accessed from and what values are returned/set, and also where the wrapped object functions are called from and what values are returned from the object functions.

Inserting the special comment //?? (or /*??*/) **after any expression will wrap the runtime value of the expression with recursive proxy** (if the value of the expression is an object). The results of intercepting the object’s properties and functions can then be viewed in Wallaby's Value Explorer.

**Comment by JonathanMEdwards** [comment]
Thanks, I'll give it a try
