### ISSUE TITLE
How I can use wallaby on node js

### ISSUE THREAD

**Issue by Alexzanderk** [wallabyjs/public#2319]
I have an issue, my project on the root folder where is node_modules folder! 
this is my wallaby.js
```js
module.exports = function () {
    return {
        files: [
            '/**/*.js'
        ],
        tests: [
            'test/**/*spec.js'
        ],
        setup: function () {
            global.expect = require('chai').expect;
        },
        trace: true,
        env: {
            type: 'node',
            runner: 'node'
        }
    };
};
```
here I have error

![image](https://user-images.githubusercontent.com/16296369/73691332-d34bda80-46da-11ea-9a5d-2b11e3a6eb7e.png)

If I exclude node_modules,
```js
module.exports = function () {
    return {
        files: [
            '/**/*.js',
            '!node_modules/**/*.js'
        ],
        tests: [
            'test/**/*spec.js'
        ],
        setup: function () {
            global.expect = require('chai').expect;
        },
        trace: true,
        env: {
            type: 'node',
            runner: 'node'
        }
    };
};
```

 I got this
![image](https://user-images.githubusercontent.com/16296369/73691141-73553400-46da-11ea-894a-6326a0db6566.png)

**Comment by smcenlly** [comment]
I can see an immediate problem in your Wallaby configuration. Your tests and files patterns need to be mutually exclusive. Right now, your test files pattern will be matched by your files pattern, which means Wallaby won't detect or run any of your tests. We have provided an updated Wallaby.js configuration below that:

1. Excludes your test files
2. Excludes wallaby.js in the project root
3. Excludes node modules

**Wallaby.js Configuration**
```javascript
module.exports = function () {
  return {
      files: [
          '**/*.js',
          '!wallaby.js',
          '!test/**/*.spec.js',
          '!node_modules/**/*'
      ],
      tests: [
          'test/**/*spec.js'
      ],
      setup: function () {
          global.expect = require('chai').expect;
      },
      env: {
          type: 'node',
          runner: 'node'
      }
  };
};
```

If the configuration above doesn't work for you and you are still getting problems, could you please provide us with your Wallaby diagnostic report. The Wallaby Diagnostics Report is a simple JSON text report that contains some basic information about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard in your response (feel free to review and edit the report if required).

If you are **not receiving** any output in your Wallaby diagnostics report, could you please provide us with the output of your `Wallaby.js Console` output window.

**Comment by Alexzanderk** [comment]
@smcenlly everything is fine, thanks!
