### ISSUE TITLE
Purchased 4 licenses - no email

### ISSUE THREAD

**Issue by coachrob** [wallabyjs/public#232]
Hi,

I purchased 4 licenses for Wallaby about 2 hours ago, but haven't received any information on what to do next.

Can anyone help or tell me what "next steps" I'm missing?

**Comment by ArtemGovorov** [comment]
@coachrob Hi Rob, according to our system the email was sent. If you still haven't received it, please send me an email to wallabyjs@gmail.com, we will sort it out.

**Comment by ArtemGovorov** [comment]
I have tried to send you a test email to the address you've specified for the purchase and the delivery has failed. Here is what it tells me:

```
Undeliverable:

Delivery has failed to these recipients or groups:

...your email...
Your message couldn't be delivered because the group you're sending to needs to know who you are before it will accept your message.

To fix this problem, ask the email admin for the group to configure the group to accept messages from you.
```
