### ISSUE TITLE
question: specify config file for automatic config?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#2324]
### Issue description or question

sorry for spamming q, but thought this is bit different q than below issue.

When jest's config file is not default one, like npm script invokes test runner like `jest --config=./some/config/path/specific.jest.config.json`, what would be way to let wallaby picks up those config to use in automatic config?

**Comment by ArtemGovorov** [comment]
Unfortunately this is not supported at the moment (there is a plan to support it, so marking it as a feature request). The easiest workaround to run Wallaby in this case is to create `jest.config.js` in your project's root with the following content:

```js
module.exports = require('./some/config/path/specific.jest.config');
```

**Comment by smcenlly** [comment]
We have enhanced Wallaby's automatic configuration to allow you to specify the configuration file location. Please [refer to our Jest docs](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration) for details.
