### ISSUE TITLE
Can not start node.js process (node)... (because of folder rename)

### ISSUE THREAD

**Issue by gadicc** [wallabyjs/public#2325]
Hi, I've solved this but I thought this might help others.

I started getting the "Can not start node.js process (node), make sure your system has node.js installed." message, in Atom.

I'm using the Automatic Configuration and had previously selected a specific folder (a subfolder of my project root) for this.  Presumably because I renamed that folder, I started getting this error.

To be clear, node *is* in my PATH.  In fact, I got the same error even with setting `process.env.WALLABY_NODE` to the exact path & file.  In fact, I got the same error even when setting this to an executable shell script, which, if run, would write the date to a temporary file.  So, even though it would say, e.g. `Can not start node.js process (/tmp/test)`, that file was never actually being executed.

I couldn't set `trace: true` to see what's really going on because I'm using the automatic config.  Once I had an actual config file and had to select it, I no longer had this error (or when selecting automatic config again on the original folder again).

**Reproduction**

1. Create a new project, select a folder for Automatic Configuration, everything works.
2. Rename that folder (via mv or atom) and try start Wallaby, the above error is received.

Hope this helps.  Hoping for a clearer error in this case :) <3

**Comment by smcenlly** [comment]
Thanks for reporting this issue. We've added an additional check before starting Wallaby to confirm that your project folder still exists which displays a more meaningful error message: `Can not start Wallaby as the directory "{DIRECTORY_NAME}" does not exist.`

**Comment by smcenlly** [comment]
Sorry - one more item to note: setting `trace` to `true` would not have helped you in this case, but if you need to enable trace with automatic configuration in the future, you can do so a couple of ways:

**package.json**
```javascript
{
  "name": "...",
  ...
  "wallaby": {
    "autoDetect": true,
    "trace": true
  }
}
```

**Wallaby Configuration File (wallaby.js)**
```javascript
module.exports = () => ({
   autoDetect: true,
   trace: true
});
```

**Comment by gadicc** [comment]
Wow, super quick fix!  Thanks!  And for also for taking the time to explain about `trace` with automatic configuration, greatly appreciated too.

Can I suggest that these examples be added to https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information?  Of course now that I've seen them it's pretty obvious, but for someone less familiar with Wallaby, my first inclination on reading the instructions was to create a configuration file, which I thought was mutually exclusive to the automatic configuration.

Thanks again, Wallaby is a godsend! :D

**Comment by ArtemGovorov** [comment]
Thanks for your suggestion! We have aded the samples to the https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information docs section.

**Comment by gadicc** [comment]
So fast!  You guys are a real inspiration :grin:
