### ISSUE TITLE
Setting up wallaby for VS2015 + Karma

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#233]
Sorry for bit ambiguous question. Can I get some basic steps to configure wallaby for environment using VS2015 and karma as runner? While I try to follow http://dm.gl/2015/05/18/wallaby-for-visual-studio/ , I'm seeing sample project https://github.com/wallabyjs/public does not contains Karma configurations in repo.

**Comment by ArtemGovorov** [comment]
Wallaby doesn't need Karma configuration, it uses its own config. 

To run the sample, after you have cloned the repository (or downloaded it as a zip file), as the [tutorial suggests](http://dm.gl/2015/05/18/wallaby-for-visual-studio/), please open [sample/visualstudio/Wallaby-Sample.sln](https://github.com/wallabyjs/public/tree/master/sample/visualstudio) in Visual Studio. It contains few wallaby config files. Right click on any of them from Solution Explorer and it'll start wallaby.js.

Please let me know if it helps.

**Comment by kwonoj** [comment]
Thanks, understood concept. Will try on my code by following samples.
