### ISSUE TITLE
Wallaby Debugger takes significantly longer to display selected value than to execute the test itself

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#2332]
@ArtemGovorov 

> For example, if you simply type element at the end of the test (without the debugger started), is it also taking a while before it gets evaluated?

Yup, It takes a long time to execute the test itself. We have  ~4500 tests
`Finished executing 11 affected test(s) in 1.32 second(s)`

> Also, could you please go to Wallaby Console tab, clear it, select a variable, wait until it gets evaluated, open and share your Wallaby Console output?

`Finished executing 1 affected test(s) in 1.2 second(s)`
![image](https://user-images.githubusercontent.com/616193/74143261-8fd9fa80-4c0b-11ea-8e61-89c56ae1adfe.png)

_Originally posted by @maksimr in https://github.com/wallabyjs/public/issues/74#issuecomment-584062201_

**Comment by ArtemGovorov** [comment]
@maksimr Interesting, looks like the test is re-executed in 1.2 second, however on your animated GIF the time between the value selection and when it appeared in the Value Explorer (and inline) was like 5-6 seconds. Can you confirm that it is the case, or you have been using different tests for GIF/screenshot?

**Comment by maksimr** [comment]
@ArtemGovorov gif from my home laptop which slower than the laptop from work (from which I have post execution time).

**Comment by smcenlly** [comment]
I've done some testing to confirm that the time to display the selected value is approximately the same as the time to execute the test. The display timings are approximately the same for both VS Code and IntelliJ (within <500ms; cannot tell visual difference). As an aside, I also analyzed the general breakdown of timings for a test that takes 1000ms to execute, Wallaby adds approximately 100ms to the overall execution time (running internal logic, starting new worker process, etc.). We would expect the overhead ~100ms to remain the same regardless of test execution time.

Given the comment above:

> @ArtemGovorov gif from my **home laptop** which slower than the laptop from **work** (from which I have posted execution time).

I'm going to assume that this is not an issue.

@maksimr - if you are seeing that it's taking longer to display the value vs. test execution time on the same machine, please let us know. We understand your original comment/feedback remains the same regarding selection feedback.

**Comment by maksimr** [comment]
@smcenlly 1 second is **too long** to get the value of **one** expression when you debugging.

The test itself took 11ms
![image](https://user-images.githubusercontent.com/616193/74191651-1242d880-4c65-11ea-8079-95b75ad9078b.png)

Get value in this test took 2 seconds on an average developer laptop
![image](https://user-images.githubusercontent.com/616193/74191784-44ecd100-4c65-11ea-9612-e17d00d15909.png)

In embedded IDEA's debugger, I get a value instantly.

**Comment by ArtemGovorov** [comment]
>  1 second is too long to get the value of one expression when you debugging.
> In embedded IDEA's debugger, I get a value instantly.

Wallaby debugger works significantly differently from classical debugger. When values are evaluated, Wallaby (as if you were typing) has to re-execute the test and capture the value. Classical debugger simply stops the program execution and evaluates expressions in place. 

I understand that 1 second seems slow to evaluate an expression, but unfortunately it is the price of being able to provide time travel experience and fast and reliable edit-and-continue (even for complex changes) features.

Having said that, we'll keep improving our debugger experience to make it as fast as possible.

**Comment by maksimr** [comment]
> Wallaby debugger works significantly differently from classical debugger.

Sure guys, I understand :)

It was just a note that usually the user doesn't care about how things work inside.
I still can use it together with a usual debugger so this is not so critical. 

Thanks!
