### ISSUE TITLE
Wallaby NOT working with JEST in angular monorepo (nrwl nx)

### ISSUE THREAD

**Issue by paulvanj** [wallabyjs/public#2335]
You may also take a look into this repo https://github.com/Steven-Harris/nrwl-jest-wallaby/blob/master/wallaby.js (where we have been helping one of our users to get his similar stack config working).

_Originally posted by @ArtemGovorov in https://github.com/wallabyjs/public/issues/2084#issuecomment-496322648_

hi,
I purchased wallaby a short while back and I am not too familiar with it as yet. 
I got JEST working and running in a mono repo (nrwl nx). I have been battling getting wallaby to work and tried to work through all the errors and posts and got it to a point where everything was green except it was not running the 'expect' lines of the test.

![2020-02-11 16_03_20-Window](https://user-images.githubusercontent.com/13675068/74243341-414e5e00-4ce8-11ea-886a-e074605b9d06.png)

I then stumbled onto the thread mentioned above and tried to run the repo as mentioned by ArtemGovorov and got the same issues. repo https://github.com/Steven-Harris/nrwl-jest-wallaby/blob/master/wallaby.js

![2020-02-11 16_05_20-Window](https://user-images.githubusercontent.com/13675068/74243400-5d51ff80-4ce8-11ea-8246-5059fce755cb.png)

I feel like I am running in circles and not clued up exactly what to do next. Some help would be greatly appreciated. :-)  thank you.

Perhaps there is a repo that is currently working with the latest versions I could look at?

EDIT: ok my bad it does seem to be working with the adjustments I made. It seems to exclude any code which is in an inline/anonymous/lambda/closure function within a subscribe to an observable. perhaps I need to set up something else?
![2020-02-11 16_24_40-Window](https://user-images.githubusercontent.com/13675068/74245255-61335100-4ceb-11ea-9489-790ae7e1d023.png)

**Comment by ArtemGovorov** [comment]
> It seems to exclude any code which is in an inline/anonymous/lambda/closure function within a subscribe to an observable. perhaps I need to set up something else?

In this example 

![2020-02-11 16_03_20-Window](https://user-images.githubusercontent.com/13675068/74243341-414e5e00-4ce8-11ea-886a-e074605b9d06.png)

it looks the test is synchronous, so it simply returns and is marked as passed before async subscribe callback (with `expect` calls) is invoked. This looks correct to me, and should work the same way in Jest without Wallaby.

Could you please set up a repo demonstrating the issue(s) where Jest CLI is working and Wallaby doesn't, we are happy to jump in and see what's wrong.

**Comment by smcenlly** [comment]
@paulvanj - I hope @ArtemGovorov's reply helped you. Since we haven't heard back, I'm going to close this issue. If you need further assistance and reply, we will re-open.
