### ISSUE TITLE
Support for Polymer Web Components

### ISSUE THREAD

**Issue by 311chaos** [wallabyjs/public#234]
Hi there.

I am curious if there is any support for Wallaby along side Polymer Web Components? https://www.polymer-project.org/1.0/

-Aaron

**Comment by ArtemGovorov** [comment]
I haven't tried it myself yet, but [according to this](https://github.com/Polymer/polymer/issues/724#issuecomment-53507084) PhantomJs 1 and 2 don't support Polymer (wallaby.js is using PhantomJs to run tests), so Polymer support may be enabled when [this feature](https://github.com/wallabyjs/public/issues/29) is implemented or PhantomJs 3 comes out, whatever happens first.

**Comment by 311chaos** [comment]
Thanks for the response @ArtemGovorov. I will watch that other issue.

**Comment by ArtemGovorov** [comment]
@311chaos I have spent some time playing with Polymer and it looks like it actually works in PhantomJs 2. Wallaby.js [supports PhantomJs 2](http://wallabyjs.com/docs/integration/phantomjs2.html), so I have created [this sample](https://github.com/wallabyjs/wallaby-polymer-sample) with wallaby configuration for a simple Polymer component.

![p](https://cloud.githubusercontent.com/assets/979966/9269832/5e378880-42b0-11e5-98d6-5c14509699b0.gif)


Please have a look to see if you could use a similar configuration for testing your components.

**Comment by ArtemGovorov** [comment]
Closing as implemented. Polymer sample support - https://github.com/wallabyjs/wallaby-polymer-sample
