### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vovnet** [wallabyjs/public#2342]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.173`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Anonimous\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ArtemGovorov** [comment]
Please attach the following file from your home-directory:
⚠️C:\Users\Anonimous\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt

**Comment by vovnet** [comment]
> Please attach the following file from your home-directory:
> C:\Users\Anonimous\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt

[file](https://easyupload.io/bdhq79)

**Comment by smcenlly** [comment]
Thanks for providing the CPU profile. The CPU profile shows that the majority of the time is spent in file copy operations when Wallaby is updating itself. In the past we have attributed this to a virus scanner checking the application files when they are being extracted onto disk.

Can you please see if you can duplicate the problem by running the VS Code command, `Wallaby.js: Force Core Update`. If you can, can you please try disabling the virus scanner and then attempting to reproduce again? If it is related to your virus scanner then you may disable the virus scanner on our extension directory or else ignore this error if it only occurs during Wallaby updates.

**Comment by smcenlly** [comment]
Closing this issue. Will re-open if we hear back with problems outside of updating Wallaby.
