### ISSUE TITLE
Reproduction in private repo?

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#235]
@ArtemGovorov I have a private repository with a reproduction of a Wallaby bug (at least, what appears to be a Wallaby bug :) ). How can I share it with you? Should I just give you access to that (the repo's on GitHub), or send an archive?

**Comment by ArtemGovorov** [comment]
@DenisGorbachev Whatever works better for you. Perhaps sending an archive to wallabyjs@gmail.com is easier, as I'll have to get it locally anyway and you will not have to bother with the access. Let me know  if I need to sign some NDA before looking into the code.
