### ISSUE TITLE
Custom matchers in Automatic configuration

### ISSUE THREAD

**Issue by ryandegruyter** [wallabyjs/public#2352]
### Issue description or question

We have a huge codebase and tests are starting to run really slow. I just read about automatic configuration and it helps a lot. Tests run very fast again but I don't know how to override the automatic configuration to import custom jasmine matchers.

### Wallaby diagnostics report

No menu item in Help.

Environment:
core v1.0.769
Angular CLI
Angular 8.2+
1200 tests +-

How we configured custom matchers in manual config:

```
var wallabyWebpack = require('wallaby-webpack');
module.exports = function (wallaby) {
 ....
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/test/helpers/globals.js',
    ],
  });

  return {
....
    postprocessor: webpackPostprocessor,
  };
};
```

**Comment by ivarvh** [comment]
I have the same problem.

**Comment by smcenlly** [comment]
@ryandegruyter, @ivarvh - are your projects configured to run your tests outside of Wallaby (e.g. with `ng test`)? If so, are custom jasmine matchers working for you when you do that?

Could you please provide:
1) [Your Wallaby Diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report).
2) Your project's `angular.json` file
3) Your project's `karma.conf.js` file
4) Your project's `tests.ts` file (for a single project workspace, it should be located at `src/test.ts`)

**Comment by smcenlly** [comment]
RE: No diagnostics report and your current problem, we just noticed that you are using an older version of Wallaby core (v1.0.769 from October 2019), while the latest version is now v1.0.856 (released February 26, 2020).

Besides new features in the latest version, we have made a number of fixes to automatic configuration that may address your problem (as well as adding the diagnostics report functionality).

Could you please try using the latest version to see if that fixes your problem? If your license has expired, you may request a trial from [our website](https://wallabyjs.com/download/) or else contact us at hello@wallabyjs.com.

**Comment by ryandegruyter** [comment]
@smcenlly 

Ok for you that I send you the diagnostics etc. via email? Don't want to make it public.

I do get this error message:

Angular CLI automatic configuration: Wallaby.js cannot use /Users/ivar/Development/appyourservice/frontend/laq-webyourservice/src/test.ts file

**Comment by ArtemGovorov** [comment]
> Ok for you that I send you the diagnostics etc. via email?

Yes, please send it to hello@wallabyjs.com

**Comment by ryandegruyter** [comment]
Email sent.

**Comment by NikGovorov** [comment]
Hi @ryandegruyter,

Does `ng test` work for the project?

**Comment by NikGovorov** [comment]
I think the following steps should fix the issue with automatic configuration on your project:

1. Delete `wallaby.js` and `wallabyTest.ts` files;
2. Create the following section in your `package.json` file, if you need `--disable-web-security` parameter, if not skip the step:

```json
{
...
"wallaby": {
    "env": {
        "kind": "chrome",
        "params": {
            "runner": "--headless --disable-gpu --disable-web-security --deterministic-fetch"
        }
    }
}
...
}
```

3. Create `test.wallaby.ts` file side by side with `test.ts`:

```typescript

import 'zone.js/dist/zone-testing';
import {getTestBed} from '@angular/core/testing';
import {BrowserDynamicTestingModule, platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

import './test/helpers/globals';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

```

4. Start wallaby in [auto config mode](https://wallabyjs.com/docs/tutorial/angular-cli.html#start-wallabyjs).

Please find more explanation on why you need to create `test.wallaby.ts` file [in your docs](https://wallabyjs.com/docs/integration/angular.html#automatic-configuration-project-overrides).

**Comment by ryandegruyter** [comment]
Perfect, it works. Thanks for all the help guys.

**Comment by NikGovorov** [comment]
@ivarvh, Could you please follow the steps above too and see if it fixes the issue with custom matchers on your project?

**Comment by ivarvh** [comment]
Yes, we're actually on the same project

**Comment by ivarvh** [comment]
Yes, we're actually on the same project

**Comment by NikGovorov** [comment]
Cool, thanks. Closing the issue then.
