### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by NeilTruick** [wallabyjs/public#2356]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.178`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.42.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\ntrui\WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt](https://github.com/wallabyjs/public/files/4272915/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt)

**Comment by ArtemGovorov** [comment]
Thanks for the report. Please update to Wallaby v1.0.179, we have made some changes to the way we unzip Wallaby core that should help.
