### ISSUE TITLE
VS Code: Show errors on test files which has a failed test

### ISSUE THREAD

**Issue by SachinShekhar** [wallabyjs/public#2357]
Wallaby.js is awesome in every way, but I also have to keep `Jest` extension (VS Code) around because it embeds errors on failed tests. The result: VS Code's file explorer sidebar shows errors on files and folders (highlighted with red) which contains at least one failed test. It allows me to easily jump to the files which I or my team mistakenly broke.

This is a simple, but powerful feature to have. Please, add this and also allow this to be toggled.

**Comment by smcenlly** [comment]
Thanks for your suggestion! We've updated Wallaby for VS Code to now display failing tests in the VS Code Problems View (available in v1.0.180). This new feature is enabled by default but can be turned off by changing your VS Code setting, `wallaby.reportFailuresAsProblems`.
