### ISSUE TITLE
Cannot find module error when VS Code starts

### ISSUE THREAD

**Issue by devmao** [wallabyjs/public#2365]
### Issue description or question

The wallaby extension is not loaded. Error message:
```
Cannot find module '/home/mao/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.181/wallaby/node_modules/q/q.js'. Please verify that the package.json has a valid "main" entry
```

### Wallaby diagnostics report

None

**Comment by NikGovorov** [comment]
Could you please try to uninstall the extension, close all vs code instances, delete `/home/mao/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.181` folder and install the extension  again?

**Comment by devmao** [comment]
works. thanks.
