### ISSUE TITLE
Keep showing notification on start even if "wallaby.showUpdateNotifications": false

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#2369]
I have set `"wallaby.showUpdateNotifications": false` but something seems wrong as this notification keeps bugging me:

```
Your Wallaby.js license free upgrades period has expired. 

If you would like to work with the latest version of Wallaby.js and future versions released within the next 12 months, please visit our website to upgrade your license. 

If you have already purchased the new license, please activate it.
```

It prompts me to enter licence, but if I simply close the notification, Wallaby works as expected. So this is the issue - that every time I have to close this notification.

If you need any log, please let me know.

It happens to Insiders and stable VSCodes.

**Comment by smcenlly** [comment]
The setting that you are using is for being prompted to update when updates are available. To suppress expiry notifications, you need to use the setting, `wallaby.suppressExpirationNotifications` with its value set to true (or you can do this using the preferences UI in VS Code).

![image](https://user-images.githubusercontent.com/2074089/76907903-28425980-68f3-11ea-9088-18b8182bac91.png)
