### ISSUE TITLE
Wallaby context actions are not working with the clipboard using Webstorm

### ISSUE THREAD

**Issue by njmaeff** [wallabyjs/public#2370]
### Issue description or question
The copy value context action does not copy the value of the highlighted variable to the clipboard.

### Wallaby diagnostics report

The diagnostics report won't show up on my clipboard when I use the action "Copy Diagnostic Report". The "copy value" context action also doesn't work for me in the test runner.

Here is my IntelliJ info.

WebStorm 2019.3.4
Build #WS-193.6911.28, built on March 18, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 16
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, com.chrisrm.idea.MaterialThemeUI, com.deadlock.scsyntax, com.intellij.lang.jsgraphql, quokka.js, ru.adelf.idea.dotenv, wallaby.js

**Comment by smcenlly** [comment]
From your WebStorm diagnostics report, it looks like you are using Linux. Can you check and see if `xclip` is installed? Our copy module uses that command line utility to gain access to the system's clipboard.
