### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ronniery** [wallabyjs/public#2374]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.185`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.1`

[WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt](https://github.com/wallabyjs/public/files/4377446/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

VSCode told me to create that...

**Comment by maplion** [comment]
After updating to 1.43.2, I also got the same as @ronniery, but it also told me that wallabyjs prevented other extensions from loading.

**Comment by smcenlly** [comment]
@ronniery AND @maplion - could you each please attach the cpu-profile file mentioned in the issue description. We need the profile before we can investigate.

**Comment by ronniery** [comment]
Yeah i did it @smcenlly is here -> https://github.com/wallabyjs/public/files/4377446/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt

**Comment by smcenlly** [comment]
Thanks - the link was malformed in the issue description and I missed it.

The CPU profile shows that the majority of the time is spent in file copy operations when Wallaby is updating itself. In the past we have attributed this to a virus scanner checking the application files when they are being extracted onto disk. Can you please see if you can duplicate the problem by running the VS Code command, Wallaby.js: Force Core Update. If you can, can you please try disabling the virus scanner and then attempting to reproduce again? If it is related to your virus scanner then you may disable the virus scanner on our extension directory or else ignore this error if it only occurs during Wallaby updates.

**Comment by maplion** [comment]
@smcenlly I tried a Wallaby.js: Force Core Update and it successfully updated and I was not able to reproduce the error.

**Comment by smcenlly** [comment]
@maplion - I'm going to assume that your CPU profile is the same as the one attached in the issue. If you provide your CPU profile and we see it is a different problem, we will reopen the issue.

To summarize: this is not a performance problem that you should be concerned with and is likely related to your file system/virus scanner/etc.
