### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by LPCmedia** [wallabyjs/public#2377]
### Issue description or question

/Users/pboudreau/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.185/wallaby/package.json: Unexpected end of JSON input

**Comment by smcenlly** [comment]
We have seen this problem before when using Wallaby for VS Code and a VS Code upgrade occurs. Sometimes the wallaby files may be corrupted after the upgrade.

Could you please:

1. Uninstall Wallaby for VS Code from your VS Code Extensions.
2. Close all instances of VS Code
3. Delete the `/Users/pboudreau/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.185` folder (if it still exists)
4. Start VS Code
5. Reinstall the Wallaby extension.

At this point Wallaby should start for you.

**Comment by LPCmedia** [comment]
thanks
