### ISSUE TITLE
Wallaby Latest VS Code Stopped Working

### ISSUE THREAD

**Issue by mieraup** [wallabyjs/public#2379]
### Issue description or question
command 'wallaby.start' not found

I removed all the folder and installed the extension and restarted vs code.
I downgraded down to the 185 version and everything is working now.
PLEASE NOTE: If you are using If you are using Jest >= v24 or Angular CLI >= v8.2 and using a
wallaby configuration file, switching to use automatic configuration may resolve your problem.

https://wallabyjs.com/docs/intro/config.html#automatic-configuration

**Comment by ArtemGovorov** [comment]
Apologies for delaying to reply to this issue, looks like GitHub notifications failed to notify anyone in our team.

The issue had been fix on the [same day when it had been reported](https://github.com/wallabyjs/public/issues/2380). You probably have already updated to the fixed version, if not, you may update your Wallaby extension to the latest version.
