### ISSUE TITLE
Can't install Wallaby Visual Studio 2015

### ISSUE THREAD

**Issue by AStoker** [wallabyjs/public#238]
I had Wallaby installed in VS 2015 when last week I was prompted to install a wallaby update. When I clicked update, VS crashed. Now, wallaby does not show up as installed, and when I try to run the installer, the installer never opens up. I wish I could provide more details, but I'm not sure what kind of details you need, or where to look. I'm running this in Windows 10 by the way, and Visual Studio Enterprise 2015

**Comment by ArtemGovorov** [comment]
I'm assuming you've tried to restart VS. Can you please try installing any other extensions from the Visual Studio Gallery or it's just the wallaby extension that can't be installed? If any other extension installation works, could you try restarting Visual Studio and trying to install wallaby again after that successful installation? Also If you open Extensions and Updates, are you sure wallaby is not there (it may be the case that it is disabled, so that's why can't be installed)?

**Comment by ArtemGovorov** [comment]
There's also something else we may need. Please open this folder `c:\Users\%user%\AppData\Local\Temp\`, run wallaby VSIX, there should be a new file created in the folder with the name like `VSIXInstaller_c6c07e8a-756d-4a0f-b330-d91b2945686d.log` (the GUID will be different). You may sort the files by date to find the newly created one. Please paste the contents of the file here.

**Comment by AStoker** [comment]
I've tried restarting VS, and Windows (I've had the problem for about a week). At this point it does seem that no other extensions can be run (V8 moment, should have tried that first). I'm sure that wallaby is not in the extensions window. When searching in the extension window online, I saw Wallaby, and it gave the download button (which only takes me to your site). Wallaby was working previously, and only stopped working when it tried to update (and crashed everything now apparently). 
 
The contents of the file are:
```
7/27/2015 10:51:19 AM - Microsoft VSIX Installer
7/27/2015 10:51:19 AM - -------------------------------------------
7/27/2015 10:51:19 AM - Initializing Uninstall...
7/27/2015 10:51:31 AM - VSIXInstaller.NoApplicableSKUsException: The extension with ID '517DE5F3-FA5B-45E4-84D5-5E896D5A18C1' is not installed to any currently installed products.
   at VSIXInstaller.App.InitializeUninstall()
   at VSIXInstaller.App.OnStartup(StartupEventArgs e)
```

**Comment by ArtemGovorov** [comment]
I'm not sure the issue is wallaby related, it may be just a coincidence that it stopped working after the update crash. What do other extension installation logs look like?

Anyway, just to double check - are you installing Wallaby VSIX for VS2015? From the log it looks like you may be trying to install the VSIX for VS2013. You may download the VSIX for VS 2015 from the link that may receive to your email from our website.

**Comment by ArtemGovorov** [comment]
You may also try manually removing wallaby, by doing following:

On your file system, open: `c:\Users\%user%\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\` and find a folder that name should be in: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\EnabledExtensions\EnabledExtensions`, delete that folder.

Now few registry keys (make sure to do a backup of `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\` - by right click and Export).

In:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\EnabledExtensions`
delete
`91ed0b3e-dedc-435f-99a2-8b496951f582,1.0.14` (may not be 1.0.14, but the GUID should be as listed).

In:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\ExtensionAutoUpdateEnrollment`
delete 
`91ed0b3e-dedc-435f-99a2-8b496951f582,1.0.14` (may not be 1.0.14, but the GUID should be as listed).

In:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\ExtensionTypes`
delete 
`91ed0b3e-dedc-435f-99a2-8b496951f582,1.0.14` (may not be 1.0.14, but the GUID should be as listed).

In:
`HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\PendingDeletions`
delete
`91ed0b3e-dedc-435f-99a2-8b496951f582,1.0.14` (may not be 1.0.14, but the GUID should be as listed).

**Comment by AStoker** [comment]
That was the only file inside the folder that had the VSIXInstall prefix. It could be coincidence that it just happens to not work now. I can confirm that I've downloaded the wallaby-vs-2015-v1.0.13 installer.

Regarding this registry stuff, I want to clarify some steps (since registry land is a dangerous place to be in). I'm looking inside ```HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\EnabledExtensions\EnabledExtensions``` to find a matching folder in ```c:\Users\%user%\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\```? The contents of the folder inside the user directory are a few cache files, a compatibility list, and a folder. 
![screen shot 2015-08-19 at 10 50 41 am](https://cloud.githubusercontent.com/assets/2907279/9359668/46dd3e92-4660-11e5-8529-8dfa145b9a5c.png)  

In the regex path, I don't have an EnabledExtensions folder nested inside another EnabledExtensions folder.  
![screen shot 2015-08-19 at 10 51 42 am](https://cloud.githubusercontent.com/assets/2907279/9359702/6f5c4ec6-4660-11e5-8e1f-47bc7f6adeb2.png)

So before I try that other stuff, I would like to clarify what needs to happen here.

**Comment by ArtemGovorov** [comment]
I have just noticed that the VSIX log file you have posted is from July based on the dates inside it, so definitely not the one we are after. Let's try again:
- Download the latest wallaby.js for VS2015 (it's 1.0.14, VSIX file should be `wallaby-vs-2015-v1.0.14.vsix`).
- Open `c:\Users\%user%\AppData\Local\Temp\`.
- Delete all files looking like `VSIXInstaller_someGUID.log`.
- Close all Visual Studio instances, run wallaby `wallaby-vs-2015-v1.0.14.vsix`.
- Now there should be the only `VSIXInstaller_someGUID.log` in `c:\Users\%user%\AppData\Local\Temp\`, paste its full content here.
- If there's no log file in the folder, may be double click didn't run it, try running the `"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe" wallaby-vs-2015-v1.0.14.vsix` from command prompt *as administrator*. Without the admin rights it may silently do nothing, you may double check `Event Viewer -> Windows Logs -> Application` after running the VSIX for `Application: VSIXInstaller.exe` errors.

Now with the registry - from your screenshots it looks like wallaby is not installed (or partially (un)installed). Let's find it out: 
- Right click on the `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0\ExtensionManager\` in the tree.
- Export it to a text file. 
- Paste the contents of the file here.

You may also try running Repair on your VS2015 (Program and Features - VS2015 - Change context menu).

![screenclip](https://cloud.githubusercontent.com/assets/979966/9372779/f56ee472-4725-11e5-817e-59b83e093f7b.png)

**Comment by AStoker** [comment]
Okay, looks like it was definitely more of a VS problem. Got to the step of running the command as administrator, and the installer finally kicked in and was successful (I still can't get any installer to run by clicking on it). 
So my guess is that my instance of VS is hosed, and I need to run that repair. I'll go ahead and close this issue, and I really appreciate you helping me out, even though this ended up not being an issue with Wallaby itself.

**Comment by ArtemGovorov** [comment]
@AStoker No worries. [From I've found](https://connect.microsoft.com/VisualStudio/feedback/details/1576068) (see the issue comments) it looks like it's an issue with the UAC in Windows 10 and the VSIXInstaller executable (VSIXInstaller.exe) of Visual Studio 2015 and Microsoft is working to fix the issue.
