### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#2386]
### Issue description or question
Hi, I have receive this error in IntellJ Idea : 
![image](https://user-images.githubusercontent.com/1046806/78665667-776a2180-78d6-11ea-8011-531f212141a2.png)

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7B59CECF5 
 2: 00007FF7B59A81A6 
 3: 00007FF7B59A8BB0 
 4: 00007FF7B5C39AAE 
 5: 00007FF7B5C399DF 
 6: 00007FF7B6177724 
 7: 00007FF7B616DE87 
 8: 00007FF7B616C3FC 
 9: 00007FF7B6175377 
10: 00007FF7B61753F6 
11: 00007FF7B5D184B7 
12: 00007FF7B5DB019A 
13: 000001DEEC3DC5C1 

Process finished with exit code 134

Maybe need to increase Javascript heap memory, but do you know how to do this ? 

### Wallaby diagnostics report

I would like to give you the diagnostics report, but when I try to copy it, It was empty. Is there any other ways to get it ?

**Comment by smcenlly** [comment]
By default, Node.js (up to 11.x) uses a maximum heap size of 700MB and 1400MB on 32-bit and 64-bit platforms, respectively. This may be what is causing your problem. You may like to try updating your node.js version to one of the [latest versions](https://nodejs.org/en/) (either LTS or Current) and see if that fixes your problem?

You may also try setting your system's [`NODE_OPTIONS` environment variable](https://nodejs.org/api/cli.html#cli_node_options_options) to `--max_old_space_size=8192` to force node to allow up to 8GB for all node processes on your system. Once you have set the environment variable you will need to restart all instances of IntelliJ Idea.

[To set it on macOS](https://stackoverflow.com/a/3756686)  you may use the following command `launchctl setenv NODE_OPTIONS --max_old_space_size=8192`.

To set it on Windows you may use the `setx` command: `setx NODE_OPTIONS "--max_old_space_size=8192"`
