### ISSUE TITLE
Solution for java.lang.NoSuchMethodError: 'com.intellij.ide.plugins.IdeaPluginDescriptorImpl com.intellij.openapi.updateSettings.impl.PluginDownloader.loadDescriptionFromJar(java.io.File)'

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#2387]
If you're seeing the following error: 

```
java.lang.NoSuchMethodError: 'com.intellij.ide.plugins.IdeaPluginDescriptorImpl 
com.intellij.openapi.updateSettings.impl.PluginDownloader.loadDescriptionFromJar(java.io.File)'
``` 

**when trying to update your Wallaby plugin after updating to the latest version of WebStorm 2020 or IntelliJ IDEA**, it is because of a breaking change in the latest IntelliJ APIs Wallaby, the plugin can not update itself successfully.

To update to the latest Wallaby plugin version in this case:
- [download](https://download.wallabyjs.com/intellij) the latest version of the plugin;
- [install](https://wallabyjs.com/docs/intro/install.html?editor=jb#jetbrains-ides) it from disk.

After that, the plugin should be able to keep updating itself without any issues.

**Comment by felikf** [comment]
![image](https://user-images.githubusercontent.com/13978154/80699103-bbb69f00-8adb-11ea-8025-9bd5ec119b7f.png)
