### ISSUE TITLE
Issue with mongoose models

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#239]
After changing test  I get error message 

```
Cannot overwrite model once compiled. 
```

Runner should be restarted

See also [stackoverflow question](http://stackoverflow.com/q/14644742/444079)

**Comment by ArtemGovorov** [comment]
Does setting [workers `recycle: true`](http://wallabyjs.com/docs/config/workers.html) help?
``` JavaScript
module.exports = function () {
   return {
     files: [
       ...
     ],

     tests: [
       ...
     ],

     workers: {
       recycle: true
     }
   };
 };
```

**Comment by hellboy81** [comment]
It helps

**Comment by hellboy81** [comment]
Nope. I am still having problem:

```js
module.exports = mongoose.model('MyMongooseModel', MyMongooseModelSchema)
```

**Comment by ArtemGovorov** [comment]
Could you please create a small sample GitHub repository where I could reproduce the issue so I could fix it?

**Comment by hellboy81** [comment]
Yes, of course. But it seems to be problem with `mocha`.

**Comment by hellboy81** [comment]
Problem can be solved  [by modifying model file](http://stackoverflow.com/a/26142477/444079)

**Comment by ArtemGovorov** [comment]
Nice, thanks for the update!

**Comment by hellboy81** [comment]
Issue can be closed

**Comment by johannesjo** [comment]
@hellboy81 why can it be closed? I think the issue still persists, at least for me. The fix you linked works, but is really ugly and might hide errors, when you actually want them to throw.

**Comment by hellboy81** [comment]
@johannesjo implementing "singleton" pattern is the only suitable solution I found with my seniour dev ;-)

**Comment by hellboy81** [comment]
@johannesjo implementing "singleton" pattern is the only suitable solution I found with my seniour dev ;-)

**Comment by hellboy81** [comment]
@johannesjo implementing "singleton" pattern is the only suitable solution I found with my seniour dev ;-)

**Comment by johannesjo** [comment]
@hellboy81 hehe ok. I just think given that jasmine-node doesn't suffer from this issue they should fix it :)

**Comment by johannesjo** [comment]
Setting workers to recycle works now if you also set initial and regular to 1. See https://github.com/wallabyjs/public/issues/323
