### ISSUE TITLE
feature request: approve snapshots for only single test when using `runAllTestsInAffectedTestFile`

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2397]
Currently, when using `runAllTestsInAffectedTestFile`, if you approve a jest snapshot, *all tests* in the given file get approved. 

Ideally, **only the single test** for which the snapshot was approved gets approved. That way you can work on one test at a time, approve its snapshots, and then move to the next without prematurely approving it.

**Comment by ArtemGovorov** [comment]
The `runAllTestsInAffectedTestFile` setting was added for tests that depend on each other, to run all tests if any of them is affected, otherwise the tests will just fail. 

And, to update a snapshot, Jest needs to run a test. 

So with the `runAllTestsInAffectedTestFile` setting, Wallaby will need to run all tests in the test file when you update one snapshot and when Wallaby runs those tests, Jest will update all snapshots for all of them. 

If you want to be able to run individual tests (so that Jest can only update snapshots for those tests), you will need to remove the `runAllTestsInAffectedTestFile` setting. If your individual tests cannot run without the setting, then Jest will not be able to run an individual test to update its snapshot.

Hope it makes sense.

**Comment by faceyspacey** [comment]
Gothu. I just remembered, we examined this 3 years ago lol:

https://github.com/wallabyjs/public/issues/939

...I've been thinking about this again and here's what I have in mind:

You can only approve the snapshot for the first test that fails, *and Wallaby only runs the tests up until that test:*

![Screen Shot 2020-04-17 at 1 00 08 PM](https://user-images.githubusercontent.com/154732/79609342-6f1a9f00-80ab-11ea-930e-dd8fe236217b.png)

That would allow you to work *one by one* on each failed test sequentially, ***without prematurely approving failed tests you're not prepared to approve.*** Having to approve a long chain of tests all at once is error prone. 

I remember what you shared with me several years ago about isolated tests, and I agree *in theory.* In practice however, Wallaby presents a great UI to examine sequences of actions, and to do so, I'm treating an entire test suite file as a single test:

```js
import { setup } from 'test-manager'

const actions = [
  {
    "type": "BROWSE",
    snipes: {
      done: [
        {
          props: { children: 'Offer Name 0' },
          propsMatch: { children: 'Offer Name 0' },
        }
      ]
    }
  },
  {
    "type": "HOME",
    snipes: {
      initial: [
        root => {
          const el = root.find(instance => instance.props.className === 'lds-ellipsis')
          expect(el.props.className).toEqual('lds-ellipsis')
        }
      ],
    }
  },
  {
    type: 'LOGIN'
  }
]


let store, snap, renderer

beforeAll(async () => {
  ({ store, snap, renderer } = await setup(actions))
})

test('BROWSE', async () => {
  await snap(actions[0])
})

test('HOME', async () => {
  await snap(actions[1])
})

test('LOGIN', async () => {
  await snap(actions[2])
})
```

> In other words, my entire test suite is an isolated test. And I use the Wallaby app UI for deep insight into what and where things are going wrong.

So here if the `HOME` action fails, the Wallaby app provides an extremely useful indicator of exactly where in the sequence of tests things wen't wrong. You want to be able to fix that failed test *alone* without having to concern yourself with all the upcoming work related to the effects on subsequent tests.

To give an idea of the limitations I'm overcoming, check this:

![Screen Shot 2020-04-17 at 1 15 49 PM](https://user-images.githubusercontent.com/154732/79610553-9a9e8900-80ad-11ea-94e6-8639f60adb06.png)

So, each test action above snapshots actions, state, and components (as well as snipes).  I've made a bunch of very small test helper functions like `snapInitialState` as shown in the above screenshot, so I know exactly *what* wen't wrong. The tests/actions themselves indicate *where* things went wrong. 

In short, I've designed a very nice testing system that makes use of the Wallaby UI to intuitively display the matrix of *where* and *what* went wrong.

To be sure, it's a workaround to stretch the capabilities of the Wallaby app interface in this way. But it provides immense insight into what's going on with a single test. I've experimented with several ways in the past 3 years since you added the `runAllTestsInAffectedTestFile` feature. There's still a few other options, but none so nice as this. 

Approving snapshots for all tests is extremely unideal in this setup, and I can't really imagine where it ever would make sense with `runAllTestsInAffectedTestFile`. I get that it's challenging based on how Jest works, but can we simply not run the tests after the test whose snapshots were approved? Is there anything that can be done?

**Comment by faceyspacey** [comment]
Did my suggestion here of *running only the first segment of tests up until the approved test* end up making sense on your end? Just wondering, because I noticed this issue was still closed. Having this solved would do wonders for my setup.

ps. thanks for the other fixes, and pointing out my outdated Jest. I can't change it on my current client project, but I look forward to my snapshot names showing in Wallaby on the next!

**Comment by ArtemGovorov** [comment]
Sorry, I marked it as a feature request, but forgot to re-open it.

**Comment by ArtemGovorov** [comment]
> Did my suggestion here of running only the first segment of tests up until the approved test end up making sense on your end?

Yes, it makes sense to me in context of your workflow.

Overloading the semantics of the `runAllTestsInAffectedTestFile` to update one snapshot at a time doesn't seem like a safe backwards compatible idea though.

So we have added the new `updateNoMoreThanOneSnapshotPerTestFileRun` setting, that should do what you've been requesting (independently of the `runAllTestsInAffectedTestFile` setting value).

Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and add:

```diff
...
{
  ...
+ updateNoMoreThanOneSnapshotPerTestFileRun: true
}
```

to your Wallaby config.

**Comment by faceyspacey** [comment]
incredible! Thanks again!!
