### ISSUE TITLE
feature request: don't show redundant snapshot diffs in wallaby app

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2399]
If you look at the below diff, you will see that both the Jest log of the diff and a better Wallaby-produced version of the diff is displayed:

![Screen Shot 2020-04-19 at 7 02 12 PM](https://user-images.githubusercontent.com/154732/79811239-186ec880-832a-11ea-9c92-a144dd02254c.png)

It would be better if there was only the Wallaby-produced version. Less clutter. And being that the Jest one is all red, it's basically unusable in comparison to the Wallaby-produced diff that has proper green+red diffing.

**Comment by ArtemGovorov** [comment]
Done, implemented and published in Wallaby App v1.0.66.
