### ISSUE TITLE
Support Atom

### ISSUE THREAD

**Issue by DarrylD** [wallabyjs/public#24]
Has any been made?

**Comment by ArtemGovorov** [comment]
Yes, not very substantial though. It's on the roadmap and we are occasionally working on it, but it's not under an active development yet.

**Comment by chyld** [comment]
I'm a javascript full stack instructor and my class uses the Atom editor. We'll definitely be using wallaby.js once Atom is supported.

**Comment by MarkHerhold** [comment]
+1 This would be amazing.

**Comment by martinjackson** [comment]
I am a developer wishing to help with the walaby plugin for atom

**Comment by redeemed2011** [comment]
+1. Trying to push for WallabyJS to my boss and team for careful consideration, but we do not use IntelliJ products or Visual Studio (we're on linux).

**Comment by seanmay** [comment]
I hate to say something like +1...

What I will say is that I'm working with at least two teams of people who would relegate their IntelliJ (community) IDEs to Scala development, and pick up Atom + Wallaby (or if needs be, Sublime 3 beta / VSC), for the love of unit testing.

While I'm the only one I know of right now, in those teams with a Sublime license (my day-to-day is Atom) and a Wallaby Freedom license (yes, I'm using WS/VS2013 expressly because of Wallaby right now), I'm certain we can find funding for this wonderful tool when it lands in other editors.

**Comment by ArtemGovorov** [comment]
@seanmay Thanks for your support! Lightweight code editors support is definitely on our roadmap and is something that we're planing to start developing actively pretty soon.

**Comment by yamsellem** [comment]
+1

**Comment by poeschko** [comment]
+1

**Comment by memark** [comment]
+1 for Visual Studio Code (which builds on Atom).

**Comment by halfdan** [comment]
@ArtemGovorov I'm considering to buy a Wallaby license (to use with IntelliJ) but would ultimately want it for Atom. Since the license is valid for up to 12 months I'm wondering whether the Atom support will come within that time or whether I'd have to re-license. Do you have a have ETA on Atom support?

On a similar note: Do you plan to have special licenses for Open Source projects or Education? (Similar to OS Licenses that Jetbrains offers)

**Comment by ArtemGovorov** [comment]
@halfdan There's no ETA yet and I can't make any promises. 

If you're not really planning to use it much for IntelliJ, then I'd recommend to just wait for Atom support, when you'll be able to get a license for Atom. 

If you're planning to use it for IntelliJ, then it should start paying for itself anyway. And even if Atom support is not released within the initial license period, the license update after it expires is 50% of the normal price, so it'll still be less expensive to keep using 'Freedom' license than buying an IntelliJ license now and another one for Atom later.

**Comment by ArtemGovorov** [comment]
> Do you plan to have special licenses for Open Source projects or Education? (Similar to OS Licenses that Jetbrains offers)

Quite possibly, but not in the near future. It's just hard to manage for a small business like wallaby.js at this stage.

**Comment by ArtemGovorov** [comment]
Happy to officially announce that we are starting [active development of wallaby.js plugin for Atom](http://eepurl.com/bswqOz), stay tuned.

**Comment by halfdan** [comment]
Any first screenshots (if there's anything to see yet)? Happily jumping around like a little kid right now - this is exciting!

**Comment by ArtemGovorov** [comment]
@halfdan There's nothing to show yet (we have started with some non UI work and my UI prototypes are very basic so far). I'll post some screenshots here once there's something to show.

**Comment by martinjackson** [comment]
Awesome News!!  

Please direct me on how to help.

**Comment by jmarbutt** [comment]
Very Awesome!

**Comment by ArtemGovorov** [comment]
Early preview of some UI work:

![a](https://cloud.githubusercontent.com/assets/979966/8793955/02a8a528-2fc1-11e5-82c6-8e510561ea28.gif)

**Comment by MarkHerhold** [comment]
:100:

**Comment by mastilver** [comment]
This is awesome, great work!
Can wait to try it!!!

**Comment by nikolaymatrosov** [comment]
Is this pluggin going to support VS Code?

**Comment by ArtemGovorov** [comment]
@nikolaymatrosov there's a plan to to support VS Code. We are looking forward to VS Code plugin system being released to see how much work is required.

**Comment by bestan** [comment]
@ArtemGovorov any updates? Really excited to use it with Atom!

**Comment by ArtemGovorov** [comment]
Will make an announcement about the ETA next week in the [wallaby newsletter](http://wallabyjs.com/#subscribe).

**Comment by ArtemGovorov** [comment]
[Great news everyone](http://eepurl.com/bw73pD)!

**Comment by hellboy81** [comment]
Is there license? Freeware or commercial?

**Comment by ArtemGovorov** [comment]
@hellboy81 As with all other wallaby.js integrations, it's a commercial tool, but free while it is in beta. The price is planned to be the same as for [all other wallaby integrations](http://wallabyjs.com/#pricing).

**Comment by MarkHerhold** [comment]
Yay! Can't wait to try it out!

**Comment by ArtemGovorov** [comment]
[Step-by-step tutorial for wallaby.js in Atom](http://dm.gl/2015/08/31/wallaby-for-atom/).
