### ISSUE TITLE
feature request: display snapshot names in Wallaby app

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2400]
Currently I'm naming snapping functions so I know what a given snapshot relates to:

![Screen Shot 2020-04-20 at 5 11 09 PM](https://user-images.githubusercontent.com/154732/79811321-5ff55480-832a-11ea-8fe8-8b13322726bc.png)

Jest lets you name your snapshots. So if the Wallaby app could just display the name of the snapshot that would be better. It would also make the stack trace shorter--as you can see above, 3 of the 6 lines in the trace are related to naming the snapshot, eg: `snapInitialTestIDs` and `snapinitialTestId`.

----

The real inspiration for this feature request, however, is dynamic snapshot names (one's that can't be solved by named wrapper functions):

```js
expect(xyz).toMatchSnapshot(varA + '_' + varB)
```

Then you would know exactly what's wrong in the Wallaby UI if you have many of these in a single test.

**Comment by ArtemGovorov** [comment]
Jest has added snapshot name in the error message [a while ago](https://github.com/facebook/jest/issues/6003), here's how it looks for me:

```
  it('renders without crashing', => {
    expect({a: 111}).toMatchSnapshot('My AWESOME Snapshot');
```

<img width="529" alt="Screen Shot 2020-04-21 at 11 54 47 am" src="https://user-images.githubusercontent.com/979966/79816808-70a7d800-83c7-11ea-99c9-0a73a860acac.png">

Maybe you are using some old version of Jest?
