### ISSUE TITLE
feature request: approve obsolete snapshots in Wallaby app

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2401]
Add a camera icon next to the file name when there are obsolete snapshots, but the tests are passing:

![Screen Shot 2020-04-21 at 1 45 17 AM](https://user-images.githubusercontent.com/154732/79845372-cc477680-8371-11ea-96a2-d15fb6365574.png)

**Comment by ArtemGovorov** [comment]
Good find! Implemented and released in Wallaby v1.0.67 and [Wallaby Core 1.0.884](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
