### ISSUE TITLE
feature request (wallaby app): to support exclusive runs, add "focus" icon with identical UX to "filter" icon

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2402]
### Wishlist

- add "focus" icon to left of filter icon in each test row
- add "focus" icon to toolbar to toggle them all off
- add "focused" switch to left of "failed" and "logged" switches to toggle test row visibility
- remember previous selection on re-boot, so large test suites can boot up quicker

### Background

Usually, you know the main culprits you need to get to pass, even if you have lots of failing tests, and, in one way or another, you can just "focus" those, and get the perf boost.

Wallaby always feels like magic when you edit the tests config array to have a small number of files. Being able to quickly maneuver the toggling of focused tests would enormously enhance the "perceived" performance of Wallaby.

### Alternative

Maybe the "filter" icon be changed to this functionality instead. Is there any value of still running tests when you show no trace of them in your IDE?? That's what I originally thought the "filter" icon would do, and I suppose many others thought the same. If there is, a 3rd alternative is to use the "filter" icon for both, but then have a switch (in the top toolbar) to toggle its purpose: coverage ***or*** focused exclusive runs.

### Note

This is a continuation of this closed issue: https://github.com/wallabyjs/public/issues/2323

**Comment by ArtemGovorov** [comment]
> Maybe the "filter" icon be changed to this functionality instead. Is there any value of still running tests when you show no trace of them in your IDE??

If you are using "filter" icon, and then are editing the filtered test file, then only that test file will executed. If you however change any code that is covered by some other test files, Wallaby will run those tests to stay up-to-date for when you remove the filter, so that other results can be displayed *instantly* for you. If we were not running other (non-filtered) affected tests, we would need to run ALL tests after you remove the filter.

Exclusive test runs will simply never run other (non-included) tests, even if you change those tests. So to get the full picture (coverage for the whole project), you will need to wait until the full test run finishes when you decide to switch from the Exclusive test run mode to the normal (full) mode.

**Comment by faceyspacey** [comment]
Gotchu. And there's often tons of code that triggers other tests. 

I love the "instant" changes by toggling the filter switch. That's the trade-off with the way it currently works vs any way that allows us to toggle off tests. The latter will require running tests and be slow when you toggle focus/filtering, *but until then can be very fast while you keep a small number of tests focused.*

**Comment by ArtemGovorov** [comment]
Also given that

> Exclusive test runs will simply never run other (non-included) tests

whenever an exclusive test run is started, Wallaby only "knows" about the test file(s) that ran as a part of the exclusive test run. It means that the test tree in Wallaby App will simply not have any other test files to display requested icons for. 

> Wallaby always feels like magic when you edit the tests config array to have a small number of files.

Currently exclusive test run can be started from editor file explorer, and (often preferable/faster way) by running `Start/Add to Exclusive Test Run` command while having any desired opened test file in your editor. 

Given that Wallaby doesn't know about any test files before it starts (or other test files not selected for an exclusive test run when it is started in the exclusive test run mode), we need file/folder context to let user make the selection, and Wallaby App is not a suitable place for it.

**Comment by faceyspacey** [comment]
I get that startup is the issue--you gotta run all the tests at least once to know about them, right?

It's still very cumbersome to go back to your IDE filetree and find more than one test that you want to keep running. The real problem comes after you add the first test, the Wallaby app hides all the other tests, and you can't see the other ones you would have selected. 

I get that you are wanting to rely more on the IDE filetree, and I love the color-coding. It's beginning to function more and more like the Wallaby app itself! Here are some ideas for your consideration:

- add a "remove from exclusive test run" to the file context menu + command palette

- add a visual indicator to the files that it's in a exclusive test run group. Ideally, it's some icon on the far right. However, I'm noticing you don't color filename rows green when they pass. So another option is to color both red *and green*. Rows not in the group have the standard color, so that's how you can tell the difference.

Nitpick: from the command pallet, it's not clear that "start exclusive test run" will remove all existing tests. At first the language "start" and "add" seemed redundant to me. Maybe if you have one running, the language can be changed to "Start NEW ...".
