### ISSUE TITLE
is there a way to trigger a Wallaby VSCode command via CLI?

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2404]
I have built an in-app system to bring up my sequential action-based tests in the browser, and replay them step by step. It allows a developer to go to exact locations in their tests without having to manually reproduce the given interactions.

Basically, the tests I previously sent you are re-used with a devtools similar--but quite different--to the Redux devtools.

There's also a GUI to browse tests, and select them. I'd like to essentially trigger an exclusive run simultaneously while the browser app goes to the first action in the test replay. VSCode doesn't seem to allow you to run command palette commands from the terminal. Is there something built-in to Wallaby I can call to trigger a given test file as an exclusive test run?

Here are some screenshots of how it works:

![Screen Shot 2020-04-24 at 2 58 43 AM](https://user-images.githubusercontent.com/154732/80200537-9efc0200-85d7-11ea-9571-983a10ffbb97.png)
![Screen Shot 2020-04-24 at 2 58 58 AM](https://user-images.githubusercontent.com/154732/80200543-a02d2f00-85d7-11ea-9af9-730ddb1094da.png)
![Screen Shot 2020-04-24 at 2 59 07 AM](https://user-images.githubusercontent.com/154732/80200544-a02d2f00-85d7-11ea-8687-bdf96db54f95.png)

One thing to note is that these aren't actions like in the Redux devtools. These are only *user-triggered* actions. And when re-played all the side-fx re-run too, including additional actions that were triggered within the side-fx. So for example, you see 4 actions above, but the Redux devtools might show 8+. 

To facilitate all this, the DB is reset each replay. So it's not *just* state changes like in the Redux devtools, which if run in the future don't reflect how your whole app is working. It's the real deal, including async data requests to the server. And now I'm trying to give it deep integration to Wallaby.

**Comment by ArtemGovorov** [comment]
To get a better understanding of what you're trying to do:
- you have VS Code running, 
- Wallaby stopped (not yet running),
- at some point you want to start new exclusive run on a given test file.

Is it correct?

**Comment by faceyspacey** [comment]
Yea. From a Node script that executes a command, or even a browser script that maybe opens a vscode link: 'vscode://file...'. I have an standard full stack javascript app that I'd like to trigger Wallaby commands in VSCode.

**Comment by ArtemGovorov** [comment]
Got it. 

Here's the easiest solution I can think of:
- VS Code extensions can run any VS Code commands programmatically, including other installed extension command. For example, [this extension](https://github.com/GabiGrin/vscode-auto-run-command) automatically starts Wallaby (or runs any other command).
- You may create your own extension, that has some sort of communication channel with your GUI (via a WebSocket, HTTP polling, or file writing/reading, or somehow else), and that will dispatch GUI commands to Wallaby (start run) and generally to VS Code (open file, etc).

**Comment by faceyspacey** [comment]
thank you Artem.
