### ISSUE TITLE
Automatic configuration with wallaby-specific jest config?

### ISSUE THREAD

**Issue by studds** [wallabyjs/public#2407]
### Issue description or question

I'm loving the automatic configuration with Nrwl/nx. Two things:

Firstly, the docs seem outdated, and the AST transformers have changed:

```
astTransformers: [
    'jest-preset-angular/build/InlineFilesTransformer',
    'jest-preset-angular/build/StripStylesTransformer'
]
```

See: https://github.com/thymikee/jest-preset-angular

Secondly, a question: is it possible to use the automatic configuration with a wallaby-specific jest config eg `jest.config.walllaby.js`. I'd like to leave the nx-generated `jest.config.js` as is.

**Comment by ArtemGovorov** [comment]
> Firstly, the docs seem outdated, and the AST transformers have changed:

Nice find, thanks for pointing this out, docs updated!

> Secondly, a question: is it possible to use the automatic configuration with a wallaby-specific jest config eg jest.config.walllaby.js. I'd like to leave the nx-generated jest.config.js as is.

Yes, you can [specify custom Jest config path](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration).

**Comment by studds** [comment]
Thanks!
