### ISSUE TITLE
approving a test suite's obsolete snapshots approves ALL the project snapshots

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2409]
For example, if I click any of the camera icons in the test suite rows here:

![Screen Shot 2020-04-29 at 5 11 39 AM](https://user-images.githubusercontent.com/154732/80594562-18c92c80-89d8-11ea-92d0-5934b32e5968.png)

it will approve the obsolete snapshots for all the other test suites, when I'm expecting to only approve the obsoletes of the clicked test suite.

I have these options set:

```js
runAllTestsInAffectedTestFile: true,
updateNoMoreThanOneSnapshotPerTestFileRun: true,
```

I'm using jest 22.4.3

**Comment by ArtemGovorov** [comment]
Thanks for the report, the issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
