### ISSUE TITLE
Allow to update obsolete snapshots separately from failing snapshots

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#2412]
expected: The obsolete snapshots should not be approved until the new camera button is clicked on the test suite row.

Jest Config:
```js
runAllTestsInAffectedTestFile: true,
updateNoMoreThanOneSnapshotPerTestFileRun: true,
```

**Comment by ArtemGovorov** [comment]
Jest currently updates all snapshots when it's told to update any. Not sure if it's easy/possible to only tell it to update obsolete/other snapshots.

**Comment by faceyspacey** [comment]
How did you do `updateNoMoreThanOneSnapshotPerTestFileRun`? You seemed to make it better than what I initially imagined by guaranteeing it *only does one.*

Can we not extend that to never doing more than one obsolete--at least then it wouldn't be all of them lol?? Because right now it will approve one snapshot at a time, but if you have obsoletes that you plan to deal with separately, it will both approve the individual snapshot AND approve all the obsoletes.

Here's why I need this by the way:

![Screen Shot 2020-05-08 at 10 42 47 PM](https://user-images.githubusercontent.com/154732/81465224-4a32bc80-917d-11ea-8b51-162bc26e9d54.png)

![Screen Shot 2020-05-08 at 10 42 55 PM](https://user-images.githubusercontent.com/154732/81465227-5159ca80-917d-11ea-8656-c04dbad0f590.png)

I have a very productive strategy where I enable/disable certain snapshots, as I expect them to fail. For example you can make state changes, disable them via the switch (making the associated snapshots come up as obsolete in Jest/Wallaby), but know you're tests are still passing because the components still render.

**Comment by ArtemGovorov** [comment]
Wow, thanks for providing so much context! Do you have any blog posts to read (or planning to write some) about Respond Framework that I could share with my team? We'd like to better understand it.

> How did you do `updateNoMoreThanOneSnapshotPerTestFileRun`? 

We had to hack into Jest and dynamically replace some of its source code on loading to make it work. 

After some investigation, we have found a way to do the same and not update obsolete snapshots if at least one failed snapshot have been updated. If you update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), it now doesn't update any obsolete snapshots if at least one failed snapshot had been updated when using the `updateNoMoreThanOneSnapshotPerTestFileRun` setting.

**Comment by faceyspacey** [comment]
Wow, thanks so much brother!!! I really appreciate that. It was a glaring hole that was going to diminish the practical usage of my testing system.

Here are the docs for Respond Framework:

https://github.com/faceyspacey/respond-framework

The version on NPM is quite a bit behind this. This is serving as "documentation-driven development" for me. I still gotta fulfill some of its promises, but if you're interested in the big picture, it's there...Well almost, because a lot new has come into view with regards to the amazing things we can now do when it comes to testing :)

The end goal is a **real** command center/ui to build apps with (like Wallaby app!). Not these run-of-the-mill drag-n-drop editors which have been appearing for decades, but never take off because they produce bad + highly limited code. 3D modelers and game developers have long since had expansive tool sets for various things that must be done. The focus on drag-n-dropping view components unhelpfully skips a step and misses a world of practical observability-oriented tools that solve today's problems.

There's a lot of features that can be built on top of the foundation/constraints of truly pure event-driven rendering. No reactive frameworks--not even Elm--achieve this, and therefore haven't even begun to think of all the UIs that we'll be able to build to assist us. Lots of the *Bret Victor observability into our code* stuff becomes possible. 

I'm just working furiously to get the underlying framework done so I can get to that point. I got lucky and found some time to build in some of the higher UI-centric testing tools which I sent you screenshots to. But that's just scratching the surface. Rest assured, when it becomes time you'll be hearing from me. As you know, I'm one of Wallaby's biggest advocates, and have have been pondering the power of this stuff and the overall vision for what's possible for some time now.

**Comment by faceyspacey** [comment]
Here's a 2 year old version that one of the RFR contributors forks and maintains:

https://github.com/respond-framework/rudy

If anyone wanted to use it, that's what they should use. Mine is in flux, and in use in production by a few of my clients.


ps. I've been working on this stuff for 4 years now.
