### ISSUE TITLE
wallaby never stars

### ISSUE THREAD

**Issue by wiber** [wallabyjs/public#2416]
### Issue description or question

The license expired January. On start it justs spins. Should it not still work? Both atom and vscode has this behavior.

https://wallabyjs.com/docs/intro/config.html#automatic-configuration

[Error] /Users/eliaswilliammoosman/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.199/wallaby/node_modules/chokidar/index.js:151 
[Error]   async remove(item) { 
[Error]         ^^^^^^ 
[Error] SyntaxError: Unexpected identifier 
[Error]     at Object.exports.runInThisContext (vm.js:76:16) 
[Error]     at Module._compile (module.js:542:28) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at require (internal/module.js:20:19) 
[Error]     at Module._compile (module.js:570:32) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at Module.runMain (module.js:604:10) 
[Error]     at run (bootstrap_node.js:394:7) 
[Error]     at startup (bootstrap_node.js:149:9) 
[Error]     at bootstrap_node.js:509:3 

### Wallaby diagnostics report

Returns nothing as the it just spins.. never arrives.

**Comment by ArtemGovorov** [comment]
This should help https://github.com/wallabyjs/public/issues/2264#issuecomment-551507594.
