### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '!'   ,  Module not found: Error: Can't resolve

### ISSUE THREAD

**Issue by RADUL01** [wallabyjs/public#2418]
Getting following errors: 
1. Uncaught SyntaxError: Unexpected token '!' 
2. Uncaught Error: Cannot find module '269' 
3. Uncaught Error: Cannot find module '1080' 
4. Module not found: Error: Can't resolve '@appServices/dfd" in "dfdfd : Module not found: Error: Can't resolve
[report.txt](https://github.com/wallabyjs/public/files/4640449/report.txt)

**Comment by smcenlly** [comment]
We tried to duplicate your problem but were not successful. We used angular cli v7.3.8 (specified in your package.json) with your project dependencies but everything is working for us, with one exception. It looks like you had made one small change to our recommended configuration that is breaking Wallaby (for us).

Please try modifying your postprocessor configuration section to:

```diff
      postprocessor: wallabyWebpack({
 
        entryPatterns: [
          ...applications
-           .map(project => project.sourceRoot + '/polyfills.ts')
+           .map(project => project.sourceRoot + '/polyfills.js')
            .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
          path.basename(__filename),
          ...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
        ],
```

We don't think that this will solve your problem though. Is it possible that you are importing javascript/typescript files that start with `#!/usr/bin/env node`?

In order for us to diagnose further, can you please provide us with your `tsconfig.json` and `angular.json` files? We may request some additional information after we've had a change to review these. Another approach to speed up turnaround is for you to provide us with a cut-down repo that has the problem (without your actual application code); this will allow us to debug/diagnose the issue without requesting additional information from you.

**Comment by smcenlly** [comment]
@RADUL01 - were you able to solve your problem?

I'm going to close this ticket as we haven't heard back. If you still need assistance, please reply and we will re-open it.
