### ISSUE TITLE
Logs from the console in VSCode not appearing properly

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#2420]
I'm using `@testing-library/react` in some of my tests, and their `debug` function is really helpful to see the DOM tree before you make any assertions to it. However, in the `Output` of VSCode, in `Wallaby.js Tests`, this output is shown with a lot of extra characters:

<img width="478" alt="Screenshot 2020-05-19 at 10 41 03" src="https://user-images.githubusercontent.com/10428082/82304915-3f69fa00-99bd-11ea-9967-b860ac90f5f2.png">

Could these be color tags from bash that VSCode is not picking up properly?

**Comment by ArtemGovorov** [comment]
Can you please share 
- an example of a test that produces the output like on your screenshot,
- Wallaby Diagnostics report (to understand what versions of what libraries are used).

To get Wallaby Diagnostics report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- execute Wallaby `Copy Diagnostics Report` command from your editor command palette;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by ArtemGovorov** [comment]
We have fixed the output and also made it possible to print the `debug` function output inline as follows:

<img width="584" alt="Screen Shot 2020-05-19 at 7 51 00 pm" src="https://user-images.githubusercontent.com/979966/82312218-1ae83f00-9a0a-11ea-9d5a-dca01880401f.png">

(will print to `Wallaby.js Tests` too).

Please update to [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to get the changes.

**Comment by Floriferous** [comment]
Awesome guys, this has made writing tests with `@testing-library/react` amazing!
