### ISSUE TITLE
Webstorm actions don't work, except Exclusive Test Run

### ISSUE THREAD

**Issue by lucastraba** [wallabyjs/public#2421]
### Issue description or question

I recently switched to Webstorm, and I found that Wallaby works a lot better here and is a lot more robust than in VS Code. Great job, you guys!

Anyways, my problem is that I see a lot of options when searching for actions, such as Run File Tests, Run Project Tests. These are not working. If I run Wallaby from the services tab, it will run all tests. If I choose Start Exclusive Test Run, it will also work. Update Snapshots also works when I'm running an exclusive test run, but the rest of the options just do nothing. Am I doing something wrong here? I read the documentation, and I should be able to use those actions. My config is fine, as Wallaby is, indeed, working, just not through the actions.

**Comment by ArtemGovorov** [comment]
Could you please provide a detailed example of a non-working action? `Run File Tests, Run Project Tests` actions are supposed to work as context actions after Wallaby is started.

**Comment by lucastraba** [comment]
Okay, now I feel like a dummy. I misunderstood the workflow, even after reading the documentation. I was used to Wallaby being fired on actions like in VS Code. Here I have to run it and then perform the actions, correct? It's just that the fact that "Start Exclusive Test Run" actually starts Wallaby, while the rest don't made me think they were not working. Also, the lack of a general Run Wallaby action made me confused.

Sorry for wasting your time, and thanks for the fast response! Keep up the great work!
