### ISSUE TITLE
Wallaby does not run tests with Automatic config

### ISSUE THREAD

**Issue by sh33dafi** [wallabyjs/public#2424]
### Issue description or question

We have a project using nrwl nx 
Relevant versions:
- jest: 24.9.0
- jest-preset-angular: 7.1.0
- wallaby-webpack: 3.9.13
- @angular-builders/jest: 8.2.0,
- @angular-devkit/build-angular: ^0.803.13
- @angular/cli: 8.3.13
- @nrwl/angular: 8.10.1
- @nrwl/cypress: 8.10.1
- @nrwl/jest: 8.10.1
- @nrwl/workspace: 8.10.1

using automatic config to run wallaby tests on libraries

When starting wallaby we get the following error
`Automatic Angular CLI configuration error: The project common is not configured with @angular-devkit/build-angular:karma builder for test architect.`

The library is configured in the angular.json:
`"common": {
      "root": "libs/common",
      "sourceRoot": "libs/common/src",
      "projectType": "library",
      "prefix": "trendminer",
      "architect": {
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/common/jest.config.js",
            "tsConfig": "libs/common/tsconfig.spec.json",
            "setupFile": "libs/common/src/test-setup.ts"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": ["libs/common/tsconfig.lib.json", "libs/common/tsconfig.spec.json"],
            "exclude": ["**/node_modules/**", "!libs/common/**"]
          }
        }
      }
    },`

My run configuration
<img width="1084" alt="Screenshot 2020-05-26 at 12 13 51" src="https://user-images.githubusercontent.com/6681036/82889386-f67ced00-9f4a-11ea-8298-eeb5b89a1ce3.png">

### Wallaby diagnostics report

n/a

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by sh33dafi** [comment]
Thanks for the quick fix! The wallaby js team is doing a great job

**Comment by smcenlly** [comment]
As of today we have added experimental support to Wallaby's automatic configuration for nx workspaces (both `angular.json` and `workspace.json`) that use jest (the nx default) as their test runner. Both Angular and React project types are supported. Please note that your `@nrwl/workspace` version must be >= 8.0.0.

You can try this by switching Wallaby project to use [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration). If you encounter problems using automatic configuration, please [let us know](https://github.com/wallabyjs/public/issues/new).
