### ISSUE TITLE
domGlobals.window.matchMedia is not a function

### ISSUE THREAD

**Issue by jim-pickering** [wallabyjs/public#2427]
### Issue description or question

I am using Create-React-App Typescript with React-App-Rewired. 
**Jest v24.9.0** - We don't have the terminal configured to use 'jest' commands, but rather 'npm run test'
**react-scripts - 3.4.1**
**react-app-rewired - 2.1.5**

I am getting this error in the Wallaby console:
**[Info]  console.log: Jest: FAIL src/app/components/dual-pane-selector/dual-pane-selector.component.spec.tsx
[Info]  console.log: Jest:   ● Test suite failed to run**
[Info]      TypeError: domGlobals.window.matchMedia is not a function
[Info]        at mediaMatch (node_modules/tinymce/tinymce.js:827:32)
[Info]        at DeviceType (node_modules/tinymce/tinymce.js:633:33)
[Info]        at Object.detect$2 [as detect] (node_modules/tinymce/tinymce.js:817:24)
[Info]        at node_modules/tinymce/tinymce.js:829:43
[Info]        at Object.<anonymous> (node_modules/tinymce/tinymce.js:28251:2)
...
[Info]  2020-05-28T20:32:42.743Z workers Sandbox (active) [o6zxa] error: domGlobals.window.matchMedia is not a function
**[Error] Runtime error: TypeError: domGlobals.window.matchMedia is not a function** 

In jest.setup.js on the root of the project I have:
if (global.document)
  document.createRange = () => ({
    setStart: () => {
      /* fix linting issue */
    },
    setEnd: () => {
      /* fix linting issue */
    },
    commonAncestorContainer: {
      nodeName: 'BODY',
      ownerDocument: document
    }
  });

// eslint-disable-next-line
window.matchMedia = jest.fn().mockImplementation(query => {
  return {
    matches: false,
    media: query,
    onchange: null,
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn()
  };
});

The 'window.matchMedia' is from the jest docs. Wallaby displays white squares, but this seems to be blocking it's ability to function completely.

In *dual-pane-selector.component.spec.tsx* there is an import in the code, and Wallaby off to the side of it is displaying in red: domGlobals.window.matchMedia is not a function.

What can I do to resolve this?

### Wallaby diagnostics report

I'm using VS Code Insiders v1.46.0 with an SSH connection to an Ubuntu 18.04 Server VM. I cannot get a Diagnostics Report, says: [Error] Failed to copy to clipboard. write EPIPE. Here my wallaby.js config file:
module.exports = () => ({
  autoDetect: true,
  trace: true
});

**Comment by smcenlly** [comment]
We've tried the latest `create-react-app` (react-scripts v3.4.1) outside of `react-app-rewired` and everything is working for us:

1. `npx create-react-app myapp --template=typescript`
2. Add matchMedia in `src/setupTests.ts` to window as per [jest docs](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom):

```
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});
```

We also tried your `jest.setup.js` code and everything worked for us.

---

Could you please confirm that this is working outside of Wallaby when you run `npm test`? If `npm test` is not working for you, please fix that first before confirming that wallaby is working.

If `npm test` is working for you, can you please provide us with:
1. `package.json`
2. Your react-app-rewired config overrides (`config-overrides.js`)
3. Your jest configuration overrides (e.g. it looks like you have a custom `/jest.config.js` file vs. the default of `/src/setupTests.ts`)

**Comment by jim-pickering** [comment]
Yes, npm run test works for me. 

*package.json:*
{
  "name": "@jimsapp",
  "version": "0.1.0",
  "homepage": ".",
  "files": [
    "*"
  ],
  "scripts": {
    "start": "react-app-rewired --max_old_space_size=4096 start",
    "build": "react-app-rewired --max_old_space_size=4096 build && node ./scripts/optimize-build.js",
    "postbuild": "node scripts/post-build.js",
    "test": "react-app-rewired --max_old_space_size=4096 test --setupFilesAfterEnv='./jest.setup.js' --coverageDirectory='./coverage' --reporters default --reporters jest-junit",
    "test-local": "react-app-rewired --max_old_space_size=4096 test --setupFilesAfterEnv='./jest.setup.js' --coverageDirectory='./coverage'",
    "eject": "react-scripts eject",
    "lint": "eslint \"src/**/*.{js,jsx,ts,tsx}\" --max-warnings 0",
    "format": "prettier \"src/**/*.{js,jsx,ts,tsx}\" --write",
    "format:check": "prettier \"src/**/*.{js,jsx,ts,tsx}\" --check",
    "coverage": "npm test -- --watchAll=false --collect-coverage",
    "licensing": "node scripts/license-file-generator.js",
    "licensing:summary": "license-checker --production --summary --out ./build/licenses-summary.txt",
    "licensing:publish": "npm run licensing && npm run licensing:summary",
    "licensing:diff": "node scripts/license-version-differ-tool",
    "publish:branch": "node scripts/publish.js"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "jest": {
    "moduleNameMapper": {
      "\\.(css|less|scss|sass)$": "identity-obj-proxy",
      "tinymce/themes/silver/theme.min.js": "<rootDir>/src/app/components/richtext-editor/__mocks__/theme.mock.ts"
    },
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}",
      "!**/*.spec.{ts,tsx}",
      "!**/*.interface.{ts,tsx}",
      "!**/*.stories.{ts,tsx}",
      "!**/index.{ts,tsx}",
      "!**/*.d.ts",
      "!**/optimizeBuild.js",
      "!**/polyfills.ts",
      "!**/serviceWorker.ts",
      "!**/setupProxy.js",
      "!**/history.tsx",
      "!**/polyfills.ts",
      "!**/initSagas.ts",
      "!**/*type.ts",
      "!src/app/store/reducers/state.ts",
      "!src/app/testing/**/*.{ts,tsx}",
      "!src/**/*.demo.{tsx}"
    ],
    "coveragePathIgnorePatterns": [
      "<rootDir>/node_modules/"
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  },
  "jest-junit": {
    "outputDirectory": "coverage"
  },
  "eslintConfig": {
    "parser": "@typescript-eslint/parser",
    "extends": [
      "airbnb",
      "react-app",
      "plugin:react/recommended",
      "plugin:@typescript-eslint/recommended",
      "plugin:prettier/recommended",
      "prettier/@typescript-eslint",
      "plugin:jest/recommended"
    ],
    "parserOptions": {
      "ecmaVersion": 2018,
      "sourceType": "module",
      "ecmaFeatures": {
        "jsx": true
      }
    },
    "settings": {
      "react": {
        "version": "detect"
      },
      "import/resolver": {
        "node": {
          "paths": [
            "./",
            "src"
          ],
          "extensions": [
            ".js",
            ".jsx",
            ".ts",
            ".tsx"
          ]
        }
      }
    },
    "rules": {
      "react/jsx-filename-extension": [
        "error",
        {
          "extensions": [
            ".jsx",
            ".tsx"
          ]
        }
      ],
      "import/extensions": [
        "error",
        "always",
        {
          "ts": "never",
          "tsx": "never",
          "js": "never",
          "jsx": "never"
        }
      ],
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/ban-ts-ignore": "off",
      "@typescript-eslint/prefer-namespace-keyword": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/explicit-member-accessibility": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/interface-name-prefix": "off",
      "@typescript-eslint/no-namespace": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "import/export": "off",
      "react/prop-types": "off",
      "react/display-name": "off",
      "import/prefer-default-export": "off",
      "react/jsx-one-expression-per-line": "off",
      "react/sort-comp": 0,
      "no-console": "off",
      "spaced-comment": [
        "error",
        "always",
        {
          "markers": [
            "/"
          ]
        }
      ]
    }
  },
  "prettier": {
    "singleQuote": true,
    "printWidth": 150
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "dependencies": {
    "@material-ui/core": "^4.5.2",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/styles": "^4.5.2",
    "@tinymce/tinymce-react": "^3.4.0",
    "@types/tinymce": "^4.5.23",
    "connected-react-router": "^6.5.2",
    "core-js": "^3.2.1",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "history": "^4.9.0",
    "identity-obj-proxy": "^3.0.0",
    "lodash": "^4.17.15",
    "odata-query": "^5.7.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-hot-loader": "^4.12.11",
    "react-redux": "^7.1.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-freeze": "^0.1.7",
    "redux-saga": "^1.0.5",
    "tinymce": "5.1.5",
    "tinymce-i18n": "^19.9.17",
    "ts-polyfill": "^3.5.3",
    "typeface-lato": "0.0.54",
    "typescript": "^3.7.5",
    "webpack": "4.42.0",
    "whatwg-fetch": "^3.0.0"
  },
  "devDependencies": {
    "@testing-library/react-hooks": "^3.2.1",
    "@types/enzyme": "^3.10.3",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "^24.0.17",
    "@types/lodash": "^4.14.137",
    "@types/node": "^11.13.19",
    "@types/react": "^16.9.2",
    "@types/react-dom": "^16.8.5",
    "@types/react-redux": "^7.1.2",
    "@types/react-router": "^5.0.3",
    "@types/react-router-dom": "^4.3.4",
    "@types/redux-saga": "^0.10.5",
    "@typescript-eslint/eslint-plugin": "^2.17.0",
    "@typescript-eslint/parser": "^2.17.0",
    "axe-core": "^3.4.0",
    "axe-testcafe": "^3.0.0",
    "cheerio": "^1.0.0-rc.3",
    "concat": "^1.0.3",
    "enzyme-to-json": "^3.4.0",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-jest": "^22.15.1",
    "eslint-plugin-node": "^10.0.0",
    "eslint-plugin-prettier": "^3.1.0",
    "eslint-plugin-react": "^7.14.3",
    "eslint-plugin-testcafe": "^0.2.1",
    "gh-pages": "^2.1.1",
    "http-proxy-middleware": "^0.19.1",
    "http-server": "^0.12.3",
    "husky": "^1.3.1",
    "jest-junit": "^6.4.0",
    "jflint": "^0.3.2",
    "license-checker": "^25.0.1",
    "lint-staged": "^8.2.1",
    "node-cmd": "^3.0.0",
    "npm": "^6.14.4",
    "prettier": "^1.19.1",
    "pretty-quick": "^1.11.1",
    "react-app-rewired": "^2.1.5",
    "react-scripts": "3.4.1",
    "request": "^2.88.0",
    "tar": "^6.0.1",
    "testcafe": "^1.7.1",
    "testcafe-react-selectors": "^4.0.0"
  }
}

*config-overrides.js:*
/* config-overrides.js */
const path = require('path');

module.exports = function override(config, env) {
  const isEnvDevelopment = env === 'development';
  const isEnvProduction = env === 'production';

  let forkTsCheckerWebpackPlugin = config.plugins.find(plugin => {
    return plugin.constructor.name === 'ForkTsCheckerWebpackPlugin';
  });
  forkTsCheckerWebpackPlugin.memoryLimit = 4096;

  if (isEnvDevelopment) {
    config.devtool = 'source-map';
    config.output.filename = 'static/js/bundle.js';
    config.output.chunkFilename = 'static/js/[name].chunk.js';
  }

  if (isEnvProduction) {
    // Adjust for proper bundling for app usage.
    config.output.filename = 'jims-app/static/js/[name].js';
    config.output.chunkFilename = 'jims-app/static/js/[name].chunk.js';

    // Allowing classnames and fnames to stay during minification... This allows the ReactSelectors in TestCafe to continue working in production mode.
    let TerserPlugin = config.optimization.minimizer.find(plugin => {
      return plugin.constructor.name === 'TerserPlugin';
    });
    TerserPlugin.options.terserOptions.keep_classnames = true;
    TerserPlugin.options.terserOptions.keep_fnames = true;
  }

  // Hooks and NPM linking is not working properly.  Need to adjust the aliases per: https://github.com/facebook/react/issues/13991
  config.resolve.alias = Object.assign(config.resolve.alias, {
    react: path.resolve('./node_modules/react')
  });

  return config;
};

*jest.config.js* - on the root (not in src)
if (global.document)
  document.createRange = () => ({
    setStart: () => {
      /* fix linting issue */
    },
    setEnd: () => {
      /* fix linting issue */
    },
    commonAncestorContainer: {
      nodeName: 'BODY',
      ownerDocument: document
    }
  });

// eslint-disable-next-line
window.matchMedia = jest.fn().mockImplementation(query => {
  return {
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn()
  };
});

Here is tsconfig.json too:
{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "es5",
      "es2015.core",
      "es2015.promise",
      "es2016.array.include",
      "es2017.string",
      "es2017.object",
      "es2018.promise",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve"
  },
  "include": [
    "src", "jest.setup.js"
  ],
  "exclude": [
    "src/setupProxy.js",
    "src/optimizeBuild.js",
    "src/app/components/richtext-editor/__mocks__/theme.mock.ts"
  ]
}

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

When running your tests with `npm run test`, you are 
passing the `--setupFilesAfterEnv='./jest.setup.js'` flag that overrides standard CRA `setupFilesAfterEnv` location. All you need to do to make it work is to provide the same override to Wallaby by modifying your wallaby.js config as follows:

**wallaby.js**
```diff
module.exports = () => ({
    autoDetect: true,
    trace: true,
+   setup: wallaby => wallaby.testFramework.configure({setupFilesAfterEnv: ['./jest.setup.js']})
});

**Comment by jim-pickering** [comment]
I am getting a syntax error now:
```
[Info]  2020-05-29T13:59:42.792Z uiService Listening port 51235
[Info]  2020-05-29T13:59:42.840Z workers Parallelism for initial run: 2, for regular run: 2
[Info]  2020-05-29T13:59:42.840Z workers Starting run worker instance #0
[Info]  2020-05-29T13:59:42.840Z workers Starting run worker instance #1
[Info]  2020-05-29T13:59:42.857Z workers Web server is listening at 38831
[Info]  2020-05-29T13:59:42.911Z project Stopping process pool
[Info]  2020-05-29T13:59:42.911Z project File cache is up-to-date, starting full test run
[Info]  2020-05-29T13:59:42.916Z project Test run started; run priority: 3
[Info]  2020-05-29T13:59:42.921Z project Running all tests
[Info]  2020-05-29T13:59:42.941Z workers Starting test run, priority: 3
[Info]  2020-05-29T13:59:42.942Z workers Distributing tests between 2 workers
[Info]  2020-05-29T13:59:42.945Z workers Running tests in parallel
[Info]  2020-05-29T13:59:42.946Z nodeRunner Starting sandbox [worker #0, session #y772r]
[Info]  2020-05-29T13:59:42.946Z nodeRunner Starting sandbox [worker #1, session #um7z3]
[Info]  2020-05-29T13:59:42.947Z nodeRunner Preparing sandbox [worker #0, session #y772r]
[Info]  2020-05-29T13:59:42.947Z nodeRunner Preparing sandbox [worker #1, session #um7z3]
[Info]  2020-05-29T13:59:43.020Z workers Started run worker instance (delayed) #0
[Info]  2020-05-29T13:59:43.020Z nodeRunner Prepared sandbox [worker #0, session #y772r]
[Info]  2020-05-29T13:59:43.021Z workers [worker #0, session #y772r] Running tests in sandbox
[Info]  2020-05-29T13:59:43.041Z workers Sandbox (active) [y772r] error: Unexpected token '{'
[Error] Runtime error: SyntaxError: Unexpected token '{' 
[Error]     at WebSocket.emit (events.js:310:20) 
[Error]     at afterWrite (_stream_writable.js:490:5) 
[Error]     at onwrite (_stream_writable.js:470:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:98:3) 
[Error]     at Zlib.processCallback (zlib.js:578:8) 
[Info]  2020-05-29T13:59:43.044Z workers Started run worker instance (delayed) #1
[Info]  2020-05-29T13:59:43.045Z nodeRunner Prepared sandbox [worker #1, session #um7z3]
[Info]  2020-05-29T13:59:43.045Z workers [worker #1, session #um7z3] Running tests in sandbox
[Info]  2020-05-29T13:59:43.053Z workers Sandbox (active) [um7z3] error: Unexpected token '{'
[Error] Runtime error: SyntaxError: Unexpected token '{' 
[Error]     at WebSocket.emit (events.js:310:20) 
[Error]     at afterWrite (_stream_writable.js:490:5) 
[Error]     at onwrite (_stream_writable.js:470:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:98:3) 
[Error]     at Zlib.processCallback (zlib.js:578:8) 
[Info]  2020-05-29T13:59:43.143Z workers [y772r] Run 0 test(s), skipped 0 test(s)
[Info]  2020-05-29T13:59:43.146Z workers [y772r] Sandbox is responsive, closing it
[Info]  2020-05-29T13:59:43.147Z workers Failed to map the stack to user code, entry message: Unexpected token '{', stack: SyntaxError: Unexpected token '{'
[Info]      at module.exports (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/runners/node/bootstrap.js:14:1679)
[Info]      at x.in:run (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/server.js:19:17442)
[Info]      at WebSocket.<anonymous> (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/server.js:19:15039)
[Info]      at WebSocket.emit (events.js:310:20)
[Info]      at Receiver.ontext (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/WebSocket.js:841:10)
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/Receiver.js:536:18
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/Receiver.js:368:7
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_module
[Info]  2020-05-29T13:59:43.154Z workers [um7z3] Run 0 test(s), skipped 0 test(s)
[Info]  2020-05-29T13:59:43.157Z workers [um7z3] Sandbox is responsive, closing it
[Info]  2020-05-29T13:59:43.157Z workers Failed to map the stack to user code, entry message: Unexpected token '{', stack: SyntaxError: Unexpected token '{'
[Info]      at module.exports (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/runners/node/bootstrap.js:14:1679)
[Info]      at x.in:run (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/server.js:19:17442)
[Info]      at WebSocket.<anonymous> (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/server.js:19:15039)
[Info]      at WebSocket.emit (events.js:310:20)
[Info]      at Receiver.ontext (/home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/WebSocket.js:841:10)
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/Receiver.js:536:18
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_modules/ws/lib/Receiver.js:368:7
[Info]      at /home/develop/.vscode-server-insiders/extensions/wallabyjs.wallaby-vscode-1.0.204/wallaby/node_module
[Info]  2020-05-29T13:59:43.158Z workers Merging parallel test run results
[Info]  2020-05-29T13:59:43.159Z project Test run finished
[Info]  2020-05-29T13:59:43.159Z project Processed console.log entries
[Info]  2020-05-29T13:59:43.160Z project Processed loading sequences
[Info]  2020-05-29T13:59:43.160Z project Processed executed tests
[Info]  2020-05-29T13:59:43.161Z project Processed code coverage
[Info]  2020-05-29T13:59:43.165Z project Test run result processed and sent to IDE
```
