### ISSUE TITLE
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. Angular 9 project with Jest & auto config

### ISSUE THREAD

**Issue by chrisj-skinner** [wallabyjs/public#2428]
### Issue description or question

I have a cli angular v9 build and using [Jest builder](https://github.com/just-jeb/angular-builders/tree/master/packages/jest) to implement jest with a standard configuration.

Getting the following error when running the auto config setup https://wallabyjs.com/docs/intro/config.html#automatic-configuration 
```
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.
```

### Wallaby diagnostics report

```
{ editorVersion: '1.45.1', pluginVersion: '1.0.203', editorType: 'VSCode', osVersion: 'darwin 17.7.0', nodeVersion: 'v10.15.1', coreVersion: '1.0.900', config: {}, fs: { numberOfFiles: 0 }, debug: [] }
```

### package.json

```
{
  "name": "project-name",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test --coverage",
    "test:watch": "ng test --watch",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "docs:json": "compodoc -p ./tsconfig.json -e json -d .",
    "storybook": "npm run docs:json && start-storybook -p 6006 -s src/assets",
    "build-storybook": "build-storybook"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.3",
    "@angular/common": "~9.0.3",
    "@angular/compiler": "~9.0.3",
    "@angular/core": "~9.0.3",
    "@angular/forms": "~9.0.3",
    "@angular/platform-browser": "~9.0.3",
    "@angular/platform-browser-dynamic": "~9.0.3",
    "@angular/router": "~9.0.3",
    "@storybook/addon-knobs": "^5.3.19",
    "node-sass": "^4.14.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/jest": "^9.0.1",
    "@angular-devkit/build-angular": "~0.900.4",
    "@angular/cli": "~9.0.4",
    "@angular/compiler-cli": "~9.0.3",
    "@angular/language-service": "~9.0.3",
    "@babel/core": "^7.9.6",
    "@compodoc/compodoc": "^1.1.11",
    "@storybook/addon-a11y": "^6.0.0-beta.16",
    "@storybook/addon-actions": "^6.0.0-beta.16",
    "@storybook/addon-docs": "^6.0.0-beta.16",
    "@storybook/addon-links": "^6.0.0-beta.16",
    "@storybook/addon-storyshots": "^6.0.0-beta.16",
    "@storybook/addon-viewport": "^6.0.0-beta.16",
    "@storybook/addons": "^6.0.0-beta.16",
    "@storybook/angular": "^6.0.0-beta.16",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^25.2.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^26.0.1",
    "jest-cli": "^26.0.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5",
    "wallaby-webpack": "^3.9.15"
  }
}
```

**Comment by smcenlly** [comment]
Right now, Wallaby does not support Angular CLI projects that use the Angular jest builder. We are working on adding support for this and expect for support to be available in the next day or two.

In the meantime, to get this working you will need to ensure that `npx jest` works from your project's root. To do this, you will need to create a `jest.config.js` file in the project root. This excerpt from a [previous issue](https://github.com/wallabyjs/public/issues/2406#issuecomment-622610180) describes how to do that:

**jest.config.js**
```
module.exports = {
  globals: {
    "ts-jest": {
      stringifyContentPathRegex: "\\.html$",
      astTransformers: [
        "jest-preset-angular/build/InlineFilesTransformer",
        "jest-preset-angular/build/StripStylesTransformer",
      ],
    },
  },
  preset: "jest-preset-angular",
  testURL: "https://github.com/@angular-cli-builders",
  setupFilesAfterEnv: [
    "<rootDir>/node_modules/@angular-builders/jest/dist/jest-config/setup.js",
  ],
  moduleNameMapper: {
    "\\.(jpg|jpeg|png)$":
      "<rootDir>/node_modules/@angular-builders/jest/dist/jest-config/mock-module.js",
  },
  testMatch: ["<rootDir>/**/*(*.)@(spec|test).[tj]s?(x)"],
};
```

---

The error that you're receiving also indicates that Wallaby cannot find `jest-cli` in your `node_modules`. It's possible that this is because of dependency conflicts between some of your package versions. Unfortunately we couldn't replicate your problem. Can you please try deleting your `node_modules` and reinstalling?

If you're still receiving the error: 

```
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.
```

Could you please tell us:
1. The location of all `jest-cli` folders in your `node_modules` directory.
2. What you're using as your package manager (e.g. yarn, npm).

Could you also please confirm that the folder that you have open in VS Code is your angular project root, i.e. the folder that has your `angular.json` file.

**Comment by chrisj-skinner** [comment]
1. The location of all jest-cli folders in your node_modules directory. `node_modules/jest-cli
![image](https://user-images.githubusercontent.com/5794048/83220454-3ea93480-a130-11ea-9913-fea8a3da55e9.png)

2. What you're using as your package manager (e.g. yarn, npm). **NPM**

After updating the `jest.config.js` file `npx jest` works and all tests pass in both of the below Scenarios.

**Scenario 1:**
I opened my `dev` folder (which contains all of my projects, including the one in question) in VSCODE (dev/project-name) - then navigated to my project root folder and selected it / open it.
I then run wallaby auto config and it failed and I got the same error again `[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.`

**Scenario 2:**
I opened just the folder containing my project root in VSCODE (project-name/). I then run wallaby auto config and it works. Strange.. 🤔

**Comment by smcenlly** [comment]
In **Scenario 1**, did you have the `dev` folder open as your project root in VS Code? If so, it is expected that Wallaby will not load properly as it uses the project root to resolve dependencies (e.g. you likely have no `node_modules` folder in `dev`). If I've misunderstood what you're saying, could you please provide detailed step-by-step instructions for how you're opening projects, perhaps with some screenshots?

I'm going to assume that we've solved your problem and close this issue. If not, please reply to this issue and we will re-open it.

**Comment by chrisj-skinner** [comment]
@smcenlly You are correct in that there is no `node_modules` folder in `dev`. I got around this issue by selection `<custom directory>` under auto config and then selecting my project folder and wallaby starts and runs fine 👍 

![image](https://user-images.githubusercontent.com/5794048/83317594-1599aa00-a1eb-11ea-8e01-b67ea76c5b3a.png)

Yes, problem solved. Many thanks.

**Comment by chrisj-skinner** [comment]
@smcenlly Hi, I just noticed today that I'm getting a 'NOTHING FOUND' message appearing when on the 'TESTS` tab in the wallaby test suite. And a warning `(node:19165) ExperimentalWarning: The fs.promises API is experimental` in the top right hand box.

My tests all run ok and when clicking on the `FILES` tab I can see the files. Just seams there's an issue with the 'TESTS` tab.

Could this be related to the fix above?

**TESTS TAB**
![image](https://user-images.githubusercontent.com/5794048/83373212-cdae8a80-a384-11ea-84b4-e905925cdede.png)

**FILES TAB**
![image](https://user-images.githubusercontent.com/5794048/83373232-db641000-a384-11ea-9a27-356061e7f30c.png)

**Comment by smcenlly** [comment]
Your screenshot indicates that you have all filters enabled in the **Tests** tab, which is why you're not seeing anything. Please toggle all of your filters and you should see the tests display. 

We'll investigate how to make this more obvious for others in the future.

**Comment by chrisj-skinner** [comment]
@smcenlly Thanks
