### ISSUE TITLE
Copy to Clipboard (diagnostics, copy value) doesn't work with VS Code remote sessions

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2431]
The copy to clipboard feature for the Wallaby Diagnostics Report and Copy Value can fail for VS Code remote sessions for two reasons:

1) `xclip` is not installed for ubuntu systems
2) No interactive session with a GUI exists for the clipboard to be available.

**Comment by ArtemGovorov** [comment]
Released in v1.0.902.
