### ISSUE TITLE
Wallaby report does not match with jest report 

### ISSUE THREAD

**Issue by SMH110** [wallabyjs/public#2432]
I am having different report when running tests using jest.
Some of the snapshots tests are passing in wallaby but not in jest.
![image](https://user-images.githubusercontent.com/16171515/83402249-469df880-a3fe-11ea-9f2b-5ea00246cc68.png)
I get the correct report result if I run the tests again using `Ctrl+Shift+R  R`
![image](https://user-images.githubusercontent.com/16171515/83402522-d3e14d00-a3fe-11ea-9baa-47482b1571d7.png)

![image](https://user-images.githubusercontent.com/16171515/83402566-ece9fe00-a3fe-11ea-9d8e-51e727138c3c.png)

This is my wallabyjs configuration 
```js
module.exports = function (wallaby) {
  var path = require("path");
  process.env.BABEL_ENV = "test";
  process.env.NODE_ENV = "test";
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, "node_modules") +
    path.delimiter +
    path.join(__dirname, "node_modules/react-scripts/node_modules");
  require("module").Module._initPaths();

  return {
    // debug:true,
    files: [
      { pattern: "src/setupTests.ts", instrument: true },
      "src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
      "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
      "!src/**/*.test.ts?(x)",
      "!src/**/*.test.js?(x)",
    ],

    tests: ["src/**/*.test.ts?(x)", "src/**/*.test.js?(x)"],

    env: {
      type: "node",
    },

    preprocessors: {
     
      "**/*.js?(x)": (file) =>
        require("@babel/core").transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require("babel-preset-jest"), "react-app"],
        }),
    },
  
    setup: (wallaby) => {
      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(
        (p) => require.resolve("react-scripts/" + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        (k) =>
          ~k.indexOf("^.+\\.(js|jsx|tsx") && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest",
  };
};

```

<details>
<summary>Show Diagnostics Report</summary>
<p>

{
  editorVersion: '1.46.0-insider',
  pluginVersion: '1.0.201',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.17763',
  nodeVersion: 'v12.16.1',
  coreVersion: '1.0.901',
  config: {
    files: [
      { pattern: 'src/setupTests.ts', instrument: true, ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'node_modules/@fortawesome/fontawesome-free/css/all.min.css', ignore: false, trigger: true, load: true, instrument: true, order: 3 },
      { pattern: 'src/**/*.test.ts?(x)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/**/*.test.js?(x)', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/**/*.test.ts?(x).snap', ignore: false, instrument: false, trigger: true, load: true, order: 4 },
      { pattern: 'src/**/*.test.js?(x).snap', ignore: false, instrument: false, trigger: true, load: true, order: 5 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 6 }
    ],
    tests: [
      { pattern: 'src/**/*.test.ts?(x)', ignore: false, trigger: true, load: true, test: true, order: 7 },
      { pattern: 'src/**/*.test.js?(x)', ignore: false, trigger: true, load: true, test: true, order: 8 }
    ],
    env: { type: 'node', params: {}, runner: 'C:\\Program Files\\nodejs\\node.exe', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    preprocessors: { '**/*.js?(x)': [Function: **/*.js?(x)], 'package.json': [Function] },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'module.exports = function (wallaby) {\r\n' +
      '  var path = require("path");\r\n' +
      '  process.env.BABEL_ENV = "test";\r\n' +
      '  process.env.NODE_ENV = "test";\r\n' +
      '  process.env.NODE_PATH +=\r\n' +
      '    path.delimiter +\r\n' +
      '    path.join(__dirname, "node_modules") +\r\n' +
      '    path.delimiter +\r\n' +
      '    path.join(__dirname, "node_modules/react-scripts/node_modules");\r\n' +
      '  require("module").Module._initPaths();\r\n' +
      '\r\n' +
      '  return {\r\n' +
      '    // debug:true,\r\n' +
      '    files: [\r\n' +
      '      { pattern: "src/setupTests.ts", instrument: true },\r\n' +
      '      "src/**/*.+(ts|js|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",\r\n' +
      '      "node_modules/@fortawesome/fontawesome-free/css/all.min.css",\r\n' +
      '      "!src/**/*.test.ts?(x)",\r\n' +
      '      "!src/**/*.test.js?(x)",\r\n' +
      '    ],\r\n' +
      '\r\n' +
      '    tests: ["src/**/*.test.ts?(x)", "src/**/*.test.js?(x)"],\r\n' +
      '\r\n' +
      '    env: {\r\n' +
      '      type: "node",\r\n' +
      '    },\r\n' +
      '\r\n' +
      '    preprocessors: {\r\n' +
      '     \r\n' +
      '      "**/*.js?(x)": (file) =>\r\n' +
      '        require("@babel/core").transform(file.content, {\r\n' +
      '          sourceMap: true,\r\n' +
      '          compact: false,\r\n' +
      '          filename: file.path,\r\n' +
      '          presets: [require("babel-preset-jest"), "react-app"],\r\n' +
      '        }),\r\n' +
      '    },\r\n' +
      '  \r\n' +
      '    setup: (wallaby) => {\r\n' +
      '      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(\r\n' +
      '        (p) => require.resolve("react-scripts/" + p)\r\n' +
      '      );\r\n' +
      '      Object.keys(jestConfig.transform || {}).forEach(\r\n' +
      '        (k) =>\r\n' +
      '          ~k.indexOf("^.+\\\\.(js|jsx|tsx") && void delete jestConfig.transform[k]\r\n' +
      '      );\r\n' +
      '      delete jestConfig.testEnvironment;\r\n' +
      '      wallaby.testFramework.configure(jestConfig);\r\n' +
      '    },\r\n' +
      '\r\n' +
      '    testFramework: "jest",\r\n' +
      '  };\r\n' +
      '};\r\n'
  },
  packageJSON: {
    dependencies: {
      '@fortawesome/fontawesome-free': '^5.13.0',
      '@material-ui/core': '^4.9.14',
      axios: '^0.19.2',
      devextreme: '19.2-stable',
      'devextreme-react': '19.2-stable',
      'devextreme-themebuilder': '19.2-stable',
      lodash: '^4.17.15',
      'prop-types': 'latest',
      react: '^16.13.1',
      'react-app-polyfill': '^1.0.6',
      'react-dom': '^16.13.1',
      'react-router-dom': '^5.1.2',
      'react-scripts': '^3.4.1',
      uuidv4: '6.0.8'
    },
    devDependencies: {
      '@babel/cli': '^7.8.4',
      '@babel/core': '^7.8.6',
      '@babel/plugin-transform-react-jsx': '^7.8.3',
      '@babel/plugin-transform-typescript': '^7.8.7',
      '@babel/polyfill': '^7.8.3',
      '@babel/preset-env': '^7.8.6',
      '@babel/preset-react': '^7.8.3',
      '@testing-library/jest-dom': '^4.2.4',
      '@testing-library/react': '^9.5.0',
      '@testing-library/user-event': '^7.1.2',
      '@types/jest': '^25.2.1',
      '@types/lodash': '^4.14.152',
      'jest-junit': '^10.0.0',
      'react-test-renderer': '^16.13.0',
      typescript: '^3.8.3'
    }
  },
  fs: { numberOfFiles: 77 },
  debug: [
    '2020-06-01T10:54:39.026Z project Wallaby Node version: v12.16.1\n',
    '2020-06-01T10:54:39.026Z project Wallaby config: C:\\repos\\SchedulingAssistantWeb\\ScheduleAssistant\\ScheduleAssistant\\ClientApp\\wallaby.js\n',
    '2020-06-01T10:54:39.866Z project File cache: C:\\Users\\mhasan\\.vscode-insiders\\extensions\\wallabyjs.wallaby-vscode-1.0.201\\projects\\696aa05548fe31be\n',
    '2020-06-01T10:54:39.949Z uiService Listening port 51235\n',
    '2020-06-01T10:54:39.988Z workers Parallelism for initial run: 30, for regular run: 15\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #0\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #1\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #2\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #3\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #4\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #5\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #6\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #7\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #8\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #9\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #10\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #11\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #12\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #13\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #14\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #15\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #16\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #17\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #18\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #19\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #20\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #21\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #22\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #23\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #24\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #25\n',
    '2020-06-01T10:54:39.988Z workers Starting run worker instance #26\n',
    '2020-06-01T10:54:39.989Z workers Starting run worker instance #27\n',
    '2020-06-01T10:54:39.989Z workers Starting run worker instance #28\n',
    '2020-06-01T10:54:39.989Z workers Starting run worker instance #29\n',
    '2020-06-01T10:54:39.992Z workers Web server is listening at 56632\n',
    '2020-06-01T10:54:40.154Z project File cache requires some updates, waiting required files from IDE\n',
    '2020-06-01T10:54:40.180Z extended-core New document or complex document change\n',
    '2020-06-01T10:54:41.044Z workers Started run worker instance (delayed) #6\n',
    '2020-06-01T10:54:41.071Z workers Started run worker instance (delayed) #0\n',
    '2020-06-01T10:54:41.077Z workers Started run worker instance (delayed) #3\n',
    '2020-06-01T10:54:41.101Z workers Started run worker instance (delayed) #2\n',
    '2020-06-01T10:54:41.108Z workers Started run worker instance (delayed) #1\n',
    '2020-06-01T10:54:41.119Z workers Started run worker instance (delayed) #8\n',
    '2020-06-01T10:54:41.140Z workers Started run worker instance (delayed) #14\n',
    '2020-06-01T10:54:41.149Z workers Started run worker instance (delayed) #16\n',
    '2020-06-01T10:54:41.161Z workers Started run worker instance (delayed) #15\n',
    '2020-06-01T10:54:41.162Z workers Started run worker instance (delayed) #4\n',
    '2020-06-01T10:54:41.176Z workers Started run worker instance (delayed) #18\n',
    '2020-06-01T10:54:41.179Z workers Started run worker instance (delayed) #7\n',
    '2020-06-01T10:54:41.184Z workers Started run worker instance (delayed) #17\n',
    '2020-06-01T10:54:41.185Z workers Started run worker instance (delayed) #13\n',
    '2020-06-01T10:54:41.206Z workers Started run worker instance (delayed) #29\n',
    '2020-06-01T10:54:41.229Z workers Started run worker instance (delayed) #11\n',
    '2020-06-01T10:54:41.231Z workers Started run worker instance (delayed) #10\n',
    '2020-06-01T10:54:41.246Z workers Started run worker instance (delayed) #23\n',
    '2020-06-01T10:54:41.273Z workers Started run worker instance (delayed) #19\n',
    '2020-06-01T10:54:41.276Z workers Started run worker instance (delayed) #21\n',
    '2020-06-01T10:54:41.284Z workers Started run worker instance (delayed) #5\n',
    '2020-06-01T10:54:41.290Z workers Started run worker instance (delayed) #9\n',
    '2020-06-01T10:54:41.294Z workers Started run worker instance (delayed) #20\n',
    '2020-06-01T10:54:41.297Z workers Started run worker instance (delayed) #22\n',
    '2020-06-01T10:54:41.298Z workers Started run worker instance (delayed) #25\n',
    '2020-06-01T10:54:41.299Z workers Started run worker instance (delayed) #27\n',
    '2020-06-01T10:54:41.314Z workers Started run worker instance (delayed) #24\n',
    '2020-06-01T10:54:41.316Z workers Started run worker instance (delayed) #12\n',
    '2020-06-01T10:54:41.341Z workers Started run worker instance (delayed) #26\n',
    '2020-06-01T10:54:41.355Z workers Started run worker instance (delayed) #28\n',
    '2020-06-01T10:54:41.734Z project Stopping process pool\n',
    '2020-06-01T10:54:41.737Z project Running postprocessor\n',
    '2020-06-01T10:54:41.743Z postprocessor New TypeScript language service is required\n',
    '2020-06-01T10:54:47.979Z project Postprocessor execution finished\n',
    '2020-06-01T10:54:47.979Z project Test run started; run priority: 3\n',
    '2020-06-01T10:54:47.980Z project Running all tests\n',
    '2020-06-01T10:54:47.982Z workers Starting test run, priority: 3\n',
    '2020-06-01T10:54:47.982Z workers Distributing tests between 30 workers\n',
    '2020-06-01T10:54:47.983Z workers Running tests in parallel\n',
    '2020-06-01T10:54:47.983Z nodeRunner Starting sandbox [worker #0, session #4e35n]\n',
    '2020-06-01T10:54:47.983Z nodeRunner Starting sandbox [worker #1, session #cenwp]\n',
    '2020-06-01T10:54:47.983Z nodeRunner Starting sandbox [worker #2, session #ig6ds]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #3, session #ipx9k]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #4, session #25ahd]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #5, session #bvwju]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #6, session #gcnqa]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #7, session #7de0c]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Starting sandbox [worker #8, session #oxijp]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #0, session #4e35n]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #1, session #cenwp]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #2, session #ig6ds]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #3, session #ipx9k]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #4, session #25ahd]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #5, session #bvwju]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #6, session #gcnqa]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #7, session #7de0c]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Preparing sandbox [worker #8, session #oxijp]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #0, session #4e35n]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #1, session #cenwp]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #2, session #ig6ds]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #3, session #ipx9k]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #4, session #25ahd]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #5, session #bvwju]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #6, session #gcnqa]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #7, session #7de0c]\n',
    '2020-06-01T10:54:47.984Z nodeRunner Prepared sandbox [worker #8, session #oxijp]\n',
    '2020-06-01T10:54:47.984Z workers [worker #0, session #4e35n] Running tests in sandbox\n',
    '2020-06-01T10:54:47.985Z workers [worker #1, session #cenwp] Running tests in sandbox\n',
    '2020-06-01T10:54:47.986Z workers [worker #2, session #ig6ds] Running tests in sandbox\n',
    '2020-06-01T10:54:47.986Z workers [worker #3, session #ipx9k] Running tests in sandbox\n',
    '2020-06-01T10:54:47.986Z workers [worker #4, session #25ahd] Running tests in sandbox\n',
    '2020-06-01T10:54:47.986Z workers [worker #5, session #bvwju] Running tests in sandbox\n',
    '2020-06-01T10:54:47.987Z workers [worker #6, session #gcnqa] Running tests in sandbox\n',
    '2020-06-01T10:54:47.987Z workers [worker #7, session #7de0c] Running tests in sandbox\n',
    '2020-06-01T10:54:47.987Z workers [worker #8, session #oxijp] Running tests in sandbox\n',
    '2020-06-01T10:54:53.184Z workers [ipx9k] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.185Z workers [ipx9k] Test executed: Update the setting value as expected\n',
    '2020-06-01T10:54:53.186Z workers [ipx9k] Test executed: Save settings values to local storage\n',
    '2020-06-01T10:54:53.187Z workers [ipx9k] Test executed: Get Updated settings values from local storage\n',
    '2020-06-01T10:54:53.211Z workers [25ahd] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.213Z workers [ipx9k] Run 3 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.213Z workers [25ahd] Test executed: Should return false for invalid value - negatives numbers\n',
    '2020-06-01T10:54:53.214Z workers [25ahd] Test executed: Should return false for invalid value - NaN\n',
    '2020-06-01T10:54:53.215Z workers [25ahd] Test executed: Should return false for invalid value - greater than defined max value\n',
    '2020-06-01T10:54:53.216Z workers [ipx9k] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:53.216Z workers [25ahd] Test executed: Should return true for valid values\n',
    '2020-06-01T10:54:53.218Z workers [25ahd] Test executed: Should return false for invalid value - negatives numbers\n',
    '2020-06-01T10:54:53.219Z workers [25ahd] Test executed: Should return false for invalid value - NaN\n',
    '2020-06-01T10:54:53.219Z workers [25ahd] Test executed: Should return true for valid values\n',
    '2020-06-01T10:54:53.242Z workers [25ahd] Run 7 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.244Z workers [25ahd] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:53.332Z workers [bvwju] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.333Z workers [bvwju] Test executed: No LocalStorage data exists on startup\n',
    '2020-06-01T10:54:53.333Z workers [bvwju] Test executed: LocalStorage data exists on startup\n',
    '2020-06-01T10:54:53.334Z workers [bvwju] Test executed: No LocalStorage data exists when storing, new prices set\n',
    '2020-06-01T10:54:53.334Z workers [bvwju] Test executed: LocalStorage data exists when storing, new prices set\n',
    '2020-06-01T10:54:53.360Z workers [bvwju] Run 4 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.361Z workers [bvwju] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:53.528Z workers [4e35n] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.529Z workers [4e35n] Test executed: ActivitiesService.LoadAllAsync A-01) returns data\n',
    '2020-06-01T10:54:53.553Z workers [4e35n] Test executed: ActivitiesService.LoadAllAsync A-02) Promise rejected\n',
    '2020-06-01T10:54:53.554Z workers [4e35n] Test executed: ActivitiesService.UpdateAllAsync B-01) returns data \n',
    '2020-06-01T10:54:53.573Z workers [oxijp] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.578Z workers [4e35n] Test executed: ActivitiesService.UpdateAllAsync B-02) Promise rejected\n',
    '2020-06-01T10:54:53.585Z workers [oxijp] Test executed: A-01) getAPIData(Activities) - HTTP Status 200\n',
    '2020-06-01T10:54:53.586Z workers [oxijp] Test executed: A-02) getAPIData(Global Locks) - HTTP Status 200\n',
    '2020-06-01T10:54:53.587Z workers [oxijp] Test executed: A-03) getAPIData(Activities) - HTTP Status 400\n',
    '2020-06-01T10:54:53.589Z workers [oxijp] Test executed: A-04) getAPIData(Global Locks) - HTTP Status 500\n',
    '2020-06-01T10:54:53.589Z workers [oxijp] Test executed: B-01) updateActivities() - HTTP Status 200\n',
    '2020-06-01T10:54:53.591Z workers [oxijp] Test executed: B-02) serialiseActivitiesAsync() - HTTP Status 400\n',
    '2020-06-01T10:54:53.593Z workers [oxijp] Test executed: B-03) serialiseActivitiesAsync() - HTTP Status 500\n',
    '2020-06-01T10:54:53.594Z workers [oxijp] Test executed: B-04) serialiseGlobalLocksAsync() - HTTP Status 200\n',
    '2020-06-01T10:54:53.596Z workers [oxijp] Test executed: B-05) updateGlobalLocks() - HTTP Status 400\n',
    '2020-06-01T10:54:53.597Z workers [oxijp] Test executed: B-06) updateGlobalLocks() - HTTP Status 500\n',
    '2020-06-01T10:54:53.598Z workers [oxijp] Test executed: C-01) serialise(Activities) - HTTP Status 200\n',
    '2020-06-01T10:54:53.598Z workers [oxijp] Test executed: C-02) serialise(GlobalLocks) - HTTP Status 200\n',
    '2020-06-01T10:54:53.606Z workers [4e35n] Run 4 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.608Z workers [4e35n] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:53.619Z workers [oxijp] Run 12 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.621Z workers [oxijp] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:53.645Z workers [gcnqa] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:53.646Z workers [gcnqa] Test executed: Update current action as expected and return false  - Sales prices update failure\n',
    '2020-06-01T10:54:53.651Z workers [gcnqa] Test executed: Update current action as expected and return false  - blend settings update failure\n',
    '2020-06-01T10:54:53.658Z workers [gcnqa] Test executed: Update current action as expected and return false  - optimise case failure\n',
    '2020-06-01T10:54:53.671Z workers [gcnqa] Test executed: Update current action as expected and return false  - accept optimise result failure\n',
    '2020-06-01T10:54:53.679Z workers [gcnqa] Test executed: Returns the expected object and Current action is optimizing sales\n',
    '2020-06-01T10:54:53.697Z workers [gcnqa] Test executed: Calls process step callback with the expected message\n',
    '2020-06-01T10:54:53.718Z workers [gcnqa] Run 6 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:53.719Z workers [gcnqa] Sandbox is responsive, closing it\n',
    '2020-06-01T10:54:55.251Z workers [ig6ds] Loaded unknown number of test(s)\n',
    '2020-06-01T10:54:55.353Z workers [ig6ds] Test executed: Should render without error\n',
    '2020-06-01T10:54:55.433Z workers [ig6ds] Test executed: Should display settings items as expected\n',
    '2020-06-01T10:54:55.434Z workers [ig6ds] Test executed: Display updated settings from local storage\n',
    '2020-06-01T10:54:55.434Z workers [ig6ds] Test executed: Display the provided value for the setting\n',
    '2020-06-01T10:54:55.434Z workers [ig6ds] Test executed: Update the setting value and save it in the local storage\n',
    '2020-06-01T10:54:55.435Z workers [ig6ds] Test executed: Show error message and does not save the invalid value in the local storage\n',
    '2020-06-01T10:54:55.435Z workers [ig6ds] Test executed: Show error message and does not save the invalid value in the local storage\n',
    '2020-06-01T10:54:55.436Z workers [ig6ds] Test executed: Reset the setting field and update local storage\n',
    '2020-06-01T10:54:55.455Z workers [ig6ds] Run 8 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:54:55.457Z workers [ig6ds] Sandbox is responsive, closing it\n',
    '2020-06-01T10:55:04.343Z workers [cenwp] Loaded unknown number of test(s)\n',
    '2020-06-01T10:55:04.344Z workers [cenwp] Test executed: renders without crashing\n',
    '2020-06-01T10:55:04.359Z workers [cenwp] Run 1 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:55:04.361Z workers [cenwp] Sandbox is responsive, closing it\n',
    '2020-06-01T10:55:05.670Z workers [7de0c] Loaded unknown number of test(s)\n',
    '2020-06-01T10:55:05.936Z workers [7de0c] Test executed: Should display the Feed settings component\n',
    '2020-06-01T10:55:06.219Z workers [7de0c] Test executed: Should display the requestId when Optimise button clicked\n',
    '2020-06-01T10:55:06.575Z workers [7de0c] Test executed: Should patch update the case settings\n',
    '2020-06-01T10:55:06.832Z workers [7de0c] Test executed: Should patch update the case settings using the default value - null\n',
    "2020-06-01T10:55:07.084Z workers [7de0c] Test executed: Show 'Applying Result...' message\n",
    '2020-06-01T10:55:07.288Z workers [7de0c] Test executed: Hide loading dialog\n',
    '2020-06-01T10:55:07.335Z workers [7de0c] Test executed: Hide Optimise button\n',
    '2020-06-01T10:55:07.358Z workers [7de0c] Run 7 test(s), skipped 0 test(s)\n',
    '2020-06-01T10:55:07.359Z workers [7de0c] Sandbox is responsive, closing it\n',
    '2020-06-01T10:55:07.360Z workers Merging parallel test run results\n',
    '2020-06-01T10:55:07.374Z project Test run finished\n',
    '2020-06-01T10:55:07.375Z project Processed console.log entries\n',
    '2020-06-01T10:55:07.375Z project Processed loading sequences\n',
    '2020-06-01T10:55:07.376Z project Processed executed tests\n',
    '2020-06-01T10:55:07.393Z project Processed code coverage\n',
    '2020-06-01T10:55:07.447Z project Test run result processed and sent to IDE\n',
    '2020-06-01T11:11:42.500Z fs File changed in editor: src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:42.515Z project Running postprocessor\n',
    '2020-06-01T11:11:42.516Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-01T11:11:42.722Z project Postprocessor execution finished\n',
    '2020-06-01T11:11:42.722Z project Test run started; run priority: 2\n',
    '2020-06-01T11:11:42.723Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-01T11:11:42.725Z project Test run finished\n',
    '2020-06-01T11:11:42.725Z project Test run data re-queued\n',
    '2020-06-01T11:11:42.903Z fs File changed: src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:42.932Z fs No changes detected for src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:42.932Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-01T11:11:44.888Z fs File changed in editor: src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:44.895Z project Running postprocessor\n',
    '2020-06-01T11:11:44.895Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-01T11:11:45.009Z project Postprocessor execution finished\n',
    '2020-06-01T11:11:45.009Z project Test run started; run priority: 2\n',
    '2020-06-01T11:11:45.010Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-01T11:11:45.013Z project Test run finished\n',
    '2020-06-01T11:11:45.013Z project Test run data re-queued\n',
    '2020-06-01T11:11:45.144Z fs File changed: src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:45.167Z fs No changes detected for src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:45.167Z extended-core File was not changed, but file markers may need to be synced\n',
    '2020-06-01T11:11:49.914Z fs File changed: src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:49.935Z fs No changes detected for src/Resources/Strings/BlendSettingsConstants.ts\n',
    '2020-06-01T11:11:49.935Z extended-core File was not changed, but file markers may need to be synced\n'
  ]
}

</p>
</details>

**Comment by ArtemGovorov** [comment]
Can you please share your Wallaby Diagnostics report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by SMH110** [comment]
Using the automatic configuration fixed the issue.
Thanks
