### ISSUE TITLE
Is there a way to check if wallaby is running my code?

### ISSUE THREAD

**Issue by ioanb7** [wallabyjs/public#2435]
It might be bad practice, but I'd like to know "if wallaby" is running my code.

I know [if jest does it](https://stackoverflow.com/questions/50940640/how-to-determine-if-jest-is-running-the-code-or-not), but I'm more interested if wallaby does it. More specifically I want the application I am testing not to show console error logs, unless "debugging" it with wallaby.

**Comment by smcenlly** [comment]
If you are running your tests in node, you can check if Wallaby is running your code by looking for `process.env.WALLABY_ENV` variable. The value will be a string with a value of `true`. 

If you are running your tests in the browser, you can check whether a window variable is set, "window.$_$session".
