### ISSUE TITLE
Make wallaby and quokka available in the open vsx registry https://open-vsx.org/

### ISSUE THREAD

**Issue by nerdo** [wallabyjs/public#2436]
This is a feature request to make wallaby and quokka available in the open vsx registry (https://open-vsx.org/).

Microsoft apparently has clear language stating that extensions in their marketplace may only be used with VSCode family of products, but it would be great to be able to use wallaby and quokka with other editors (I have my eye on onivim2 https://onivim.io/)

**Comment by maksimr** [comment]
+1 Wold love to use it in the theia editor.

**Comment by mutech** [comment]
Is it just a question of publishing it there or is it not working in Theia?

**Comment by maksimr** [comment]
@mutech it’s just a question of publishing.

**Comment by mutech** [comment]
Then it's really sad that this issue gets so little attention.

**Comment by smcenlly** [comment]
Unfortunately we cannot publish to the open vsx repository as publishing to the open vsx repository is only available for open-source projects ([see agreement here](https://www.eclipse.org/legal/ECA.php)).

To use Wallaby and Quokka in other editors you will need to download the extension from the Microsoft marketplace and then install from VSIX. For example, this is described in the [VS Codium docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace).

- [Marketplace for Wallaby](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode)
- [Marketplace for Quokka](https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode)

**Comment by spoenemann** [comment]
@smcenlly the Eclipse Contributor Agreement (ECA) is for contributing code to open-source projects hosted by the Eclipse Foundation. The Publisher Agreement for publishing to open-vsx.org is this one:
https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf

It requires every extension to have a license, but it is not restricted to open source licenses. Please consider reopening this issue.

**Comment by smcenlly** [comment]
We recently reviewed the Open VSX marketplace agreement and it appears that it is not compatible with our licensing model:

> No Compensation​. You expressly acknowledge that neither Eclipse nor any licensee or end-user of any of your Offerings published on the Registry shall be required to provide you with any compensation for the distribution or use of your Offering as made available on the Registry.

---

We do not have any plans to publish Quokka to the Open VSX marketplace, but you are fully able to use our products with VSCodium today (a number of options exist). 

Please refer to [VSCodium docs](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) for information on how to do this.

**Comment by joeyfigaro** [comment]
For those still looking, installing the vsix manually it [no longer seems to work](https://joeysharesthings.com/yjYCppgs) in vscodium `1.75.1  (23040)`

Looks like there's an issue with rendering the extension settings view.

**Comment by smcenlly** [comment]
@joeyfigaro - I'm not sure that this is true... we have had similar issues in the past and they are generally environmental (e.g. corrupt VS Code installation, using Ubuntu `snap` to install VS Code / Node) and other similar problems.

As per our email response:

> Hi Joey,
> 
> Are you getting an error when you attempt to load the view? Can you describe a little more about what is happening? Is it loading and nothing is displaying or does it not load at all?
> 
> Can you also please run the VS Code command, `Developer: Toggle Developer Tools` and provide us with your Console output. It may have some errors and log messages that are helpful in understanding why it's not working for you.
> 
> Regards, Simon

Please be assured that we will work with you to get this working. We are not aware of anything in VS Codium that would cause a compatibility issue with Wallaby / Quokka.

**Comment by RayyanNafees** [comment]
Any progress after a year ?

**Comment by smcenlly** [comment]
Please refer to [our comment above](https://github.com/wallabyjs/public/issues/2436#issuecomment-1188391768):

We have reviewed the Open VSX marketplace agreement and it is not compatible with our licensing model:

> No Compensation​. You expressly acknowledge that neither Eclipse nor any licensee or end-user of any of your Offerings published on the Registry shall be required to provide you with any compensation for the distribution or use of your Offering as made available on the Registry.

We do not have plans to publish Quokka to the Open VSX marketplace, but you are fully able to use our products with VSCodium today.
