### ISSUE TITLE
Add a way to stop line wrapping and remove log entry locations from Wallaby App output

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#2438]
See https://discordapp.com/channels/694023081168994355/694035930541064293/718698398760435712. Maybe a couple of buttons (with saving their state).

**Comment by mighdoll** [comment]
Thanks for considering this. I like being able to see a lot of logged info while debugging.

**Comment by NikGovorov** [comment]
We've just released Wallaby.js App v1.0.73 with compact view mode for test details section.

![ScreenClip](https://user-images.githubusercontent.com/129254/85259597-abec8300-b4ac-11ea-9af4-3e3e164439a8.png)


![ScreenClip](https://user-images.githubusercontent.com/129254/85259509-895a6a00-b4ac-11ea-8713-9827b4b39946.png)
