### ISSUE TITLE
Tests not running on latest upgrade in Visual Studio

### ISSUE THREAD

**Issue by jmwnoble** [wallabyjs/public#244]
Wallaby upgraded today from the beta version.  A few issues have occurred with no file changes:
First: The failing test window said: A compliance.spec.compiled.js file had incorrectly terminated regex expression.  The typescript was compiling properly and no changed had been made since the tests last ran.
On closing and re-opening VS, I got an error in wallaby console saying app-config has syntax error but providing no further information.  The sandbox would not open.
Then on re-opening again the console said it could not load enums.map.js, which was not included in the wallaby config and that it had never looked for before.  I explicitly included that file to see if I could get past that error, then it had EONENT looking for favicon.ico, now I get no error but no action on my tests and the message: 
wallaby:project Test run is not cancelled because cancel requester does not have enough priority to cancel the run
and in the SandBox console it says 
Uncaught Error: One of your tests is trying to unload window object.(anonymous function) @ tracer.js:8

Any ideas?

I'm continuing to try to isolate the issue.  I've got it to work with minimal tests so will build up from there and let you know what I find...

**Comment by jmwnoble** [comment]
I think these errors were all side-effects of a method buried in code that was being tested that caused an infinite loop.  A developer had written for(i=1, i=maxval...... instead of i==maxval.  Not sure why it threw the errors it did but once this was fixed things were back to normal

**Comment by ArtemGovorov** [comment]
@jmwnoble Awesome, thanks for the update. Infinite loops did cause various other issues for me as well a few times, but normally I'd see `... possible infinite loop` message. From the symptoms you've described, the infinite loop was probably in some code that gets invoked not by tests, but resides in the program scope (and gets invoked before tests), which makes it harder to diagnose.
