### ISSUE TITLE
Support pnpm and jest

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2441]
### Issue description or question

Wallaby is searching the following paths for a test runner but none is available when using pnpm.

_~/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:64:1421)_

```
if (findModule('react-scripts/node_modules/jest-cli', '/build/TestRunner', foundTestRunner)
 findModule('react-scripts/node_modules/jest-cli', '/build/test_scheduler', foundTestRunner)
 findModule('react-scripts/node_modules/jest-cli', '/build/TestScheduler', foundTestRunner)
 findModule('react-scripts/node_modules/jest/node_modules/jest-cli', '/build/TestRunner', foundTestRunner)
 findModule('react-scripts/node_modules/jest/node_modules/jest-cli', '/build/test_scheduler', foundTestRunner)
 findModule('react-scripts/node_modules/jest/node_modules/jest-cli', '/build/TestScheduler', foundTestRunner)
 findModule('jest-cli/node_modules/@jest/core', '/build/TestScheduler', foundTestRunner)
 findModule('jest/node_modules/jest-cli/node_modules/@jest/core', '/build/TestScheduler', foundTestRunner)
 findModule('@jest/core', '/build/TestScheduler', foundTestRunner)
 findModule('jest-cli', '/build/TestRunner', foundTestRunner)
 findModule('jest-cli', '/build/TestScheduler', foundTestRunner)
 findModule('jest-cli', '/build/test_scheduler', foundTestRunner)
 findModule('jest-cli', '/src/TestRunner', foundTestRunner)
 findModule('jest/node_modules/jest-cli', '/build/TestRunner', foundTestRunner)
 findModule('jest/node_modules/jest-cli', '/build/test_scheduler', foundTestRunner)
 findModule('jest/node_modules/jest-cli', '/build/TestScheduler', foundTestRunner), !TestRunner) 
   throw new Error('Cannot find Jest test runner')
```

**Comment by vjpr** [comment]
Actually, it looks like for `jest@0.26`, you will need `@jest/core` installed in your root.

**Comment by vjpr** [comment]
console.error: Error while trying to initialize jest: a is not a function
console.log: { contexts: Set { undefined } }
console.error: TypeError: Cannot destructure property 'config' of 'undefined' as it is undefined.
    at /Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/registry.npmjs.org/@jest/core/26.0.1/node_modules/@jest/core/build/TestScheduler.js:246:24
    at Set.forEach (<anonymous>)
    at TestScheduler.scheduleTests (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/registry.npmjs.org/@jest/core/26.0.1/node_modules/@jest/core/build/TestScheduler.js:246:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by smcenlly** [comment]
Wallaby supports the latest version of Jest, `v26.0.1`.

Could you please provide your [Wallaby Diagnostics Report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)? 

I'd also like to understand if you are using Automatic Configuration or a Wallaby config file (the diagnostics report will tell us this). The file that you referenced in your issue description is not used with Wallaby's Automatic Configuration but there may be other similar problems. If your project is not using Automatic Configuration, could you please try updating your project to use [automatic config](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) as this may fix your problem?

Can you also provide us with details on how your project is structured (or else instructions to set up a replica environment) so that we can understand how your packages are structured when you're using `pnpm` (I'm assuming you have a mono-repo)?

**Comment by vjpr** [comment]
I have created a bare-bones reproduction here -> https://github.com/vjpr/wallaby-pnpm-jest-issue

I am getting a different issue now...

```
Error in worker: {"message":"Cannot set property 'runContentWithLocalBindings' of undefined","stack":"TypeError: Cannot set property 'runContentWithLocalBindings' of undefined\n    at Object.<anonymous> (/Users/Vaughan/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/wallaby/runners/node/jest@0.4.3/initializer.js:206:41)
```

**Comment by vjpr** [comment]
```
{
  editorVersion: 'IntelliJ IDEA 2020.2 EAP',
  pluginVersion: '1.0.177',
  editorType: 'IntelliJ',
  osVersion: 'darwin 19.3.0',
  nodeVersion: 'v14.2.0',
  coreVersion: '1.0.906',
  config: {
    files: [
      { pattern: 'jest.config.js', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: '**/src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: '**/src/**/*.test.ts', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '**/src/*.test.ts.snap', ignore: false, instrument: false, trigger: true, load: true, order: 3 },
      { pattern: '**/src/**/*.test.ts.snap', ignore: false, instrument: false, trigger: true, load: true, order: 4 },
      { pattern: 'package.json', ignore: false, instrument: false, trigger: true, load: true, order: 5 }
    ],
    tests: [
      { pattern: '**/src/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 6 },
      { pattern: '**/src/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 7 }
    ],
    env: { type: 'node', params: {}, runner: '<homeDir>/nvm/versions/node/v14.2.0/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    testFramework: { version: 'jest@0.4.3', configurator: 'jest@0.4.3', reporter: 'jest@0.4.3', starter: 'jest@0.4.3' },
    debug: true,
    runMode: 'onsave',
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    preprocessors: { 'package.json': [Function (anonymous)] },
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: "module.exports = require('./config/tools/wallaby/wallaby.jest.default')\n"
  },
  packageJSON: {
    dependencies: { '@babel/core': '^7.10.2', '@live/tsconfig': 'workspace:^0.1.0', 'jest-config': '^26.0.1' },
    devDependencies: {
      '@ava/babel': '^1.0.1',
      '@babel/preset-env': '^7.10.2',
      '@commitlint/prompt-cli': '^8.3.5',
      '@jest/core': '^26.0.1',
      '@types/jest': '^25.2.3',
      ava: '^3.8.2',
      'babel-jest': '^26.0.1',
      eslint: '^7.1.0',
      husky: '^4.2.5',
      jest: '^26.0.1',
      'jest-util': '^26.0.1',
      'lint-staged': '^10.2.9',
      'markdownlint-cli': '^0.23.1',
      prettier: '^2.0.5',
      'regenerator-runtime': '^0.13.5',
      'ts-node': '^8.10.2',
      typescript: '^3.9.3'
    }
  },
  fs: { numberOfFiles: 10 },
  debug: [
    '2020-06-08T21:45:03.043Z project Wallaby Node version: v14.2.0\n',
    '2020-06-08T21:45:03.043Z project Wallaby config: <homeDir>/dev-mono/thirtyfive/wallaby.jest.js\n',
    '2020-06-08T21:45:05.150Z fs File system scan has finished by timeout\n',
    '2020-06-08T21:45:05.216Z project File cache: <homeDir>/Library/Application Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/2f831b667358b84c\n',
    '2020-06-08T21:45:05.224Z uiService Listening port 51235\n',
    '2020-06-08T21:45:05.593Z workers Parallelism for initial run: 14, for regular run: 7\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #0\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #1\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #2\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #3\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #4\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #5\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #6\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #7\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #8\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #9\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #10\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #11\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #12\n',
    '2020-06-08T21:45:05.594Z workers Starting run worker instance #13\n',
    '2020-06-08T21:45:05.595Z workers Web server is listening at 57450\n',
    '2020-06-08T21:45:05.827Z project Stopping process pool\n',
    '2020-06-08T21:45:05.828Z project File cache is up-to-date, starting full test run\n',
    '2020-06-08T21:45:05.931Z project Running postprocessor\n',
    '2020-06-08T21:45:05.934Z postprocessor New TypeScript language service is required\n',
    "2020-06-08T21:45:05.934Z postprocessor TypeScript postprocessor will be removed because in 2 project files none were found by patterns: [ '**/*.ts?(x)' ]\n",
    '2020-06-08T21:45:05.937Z project Postprocessor execution finished\n',
    '2020-06-08T21:45:05.937Z project Postprocessor is removed as requested by itself\n',
    '2020-06-08T21:45:05.937Z project Test run started; run priority: 3\n',
    '2020-06-08T21:45:05.941Z project Running all tests\n',
    '2020-06-08T21:45:05.943Z project Test run finished\n',
    '2020-06-08T21:45:05.943Z project Test run data re-queued\n',
    '2020-06-08T21:45:10.940Z workers Started run worker instance (delayed) #5\n',
    '2020-06-08T21:45:10.941Z workers Started run worker instance (delayed) #6\n',
    '2020-06-08T21:45:10.941Z workers Started run worker instance (delayed) #7\n',
    '2020-06-08T21:45:10.941Z workers Started run worker instance (delayed) #0\n',
    '2020-06-08T21:45:10.942Z workers Started run worker instance (delayed) #1\n',
    '2020-06-08T21:45:10.942Z workers Started run worker instance (delayed) #4\n',
    '2020-06-08T21:45:10.942Z workers Started run worker instance (delayed) #2\n',
    '2020-06-08T21:45:10.942Z workers Started run worker instance (delayed) #3\n',
    '2020-06-08T21:45:10.978Z workers Started run worker instance (delayed) #8\n',
    '2020-06-08T21:45:10.978Z workers Started run worker instance (delayed) #9\n',
    '2020-06-08T21:45:10.979Z workers Started run worker instance (delayed) #11\n',
    '2020-06-08T21:45:10.979Z workers Started run worker instance (delayed) #10\n',
    '2020-06-08T21:45:10.979Z workers Started run worker instance (delayed) #12\n',
    '2020-06-08T21:45:10.979Z workers Started run worker instance (delayed) #13\n',
    '2020-06-08T21:45:11.406Z project Test run started; run priority: 3\n',
    '2020-06-08T21:45:11.406Z project Running all tests\n',
    '2020-06-08T21:45:11.407Z workers Starting test run, priority: 3\n',
    '2020-06-08T21:45:11.408Z nodeRunner Starting sandbox [worker #0, session #o5zhr]\n',
    '2020-06-08T21:45:11.408Z nodeRunner Preparing sandbox [worker #0, session #o5zhr]\n',
    '2020-06-08T21:45:11.408Z nodeRunner Prepared sandbox [worker #0, session #o5zhr]\n',
    '2020-06-08T21:45:11.408Z workers [worker #0, session #o5zhr] Running tests in sandbox\n',
    '2020-06-08T21:45:13.566Z project Test run is not cancelled because cancel requester does not have enough priority to cancel the run\n',
    '2020-06-08T21:45:21.815Z workers [o5zhr] Run 0 test(s), skipped 0 test(s)\n',
    '2020-06-08T21:45:22.164Z workers [o5zhr] Sandbox is responsive, closing it\n',
    '2020-06-08T21:45:22.164Z project Test run finished\n',
    '2020-06-08T21:45:22.165Z project Processed console.log entries\n',
    '2020-06-08T21:45:22.165Z project Processed loading sequences\n',
    '2020-06-08T21:45:22.165Z project Processed executed tests\n',
    '2020-06-08T21:45:22.165Z project Processed code coverage\n',
    '2020-06-08T21:45:22.167Z project Test run result processed and sent to IDE\n',
    '2020-06-08T21:45:32.622Z project TypeScript file has been added, re-activating TypeScript postprocessor\n',
    '2020-06-08T21:45:32.622Z project Running postprocessor\n',
    '2020-06-08T21:45:32.622Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-08T21:45:32.622Z postprocessor New TypeScript language service is required\n',
    '2020-06-08T21:45:33.155Z project Postprocessor execution finished\n',
    '2020-06-08T21:45:33.155Z project Test run started; run priority: 2\n',
    '2020-06-08T21:45:33.156Z testTask Test files from affected: 0, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-08T21:45:33.156Z project Test run finished\n',
    '2020-06-08T21:45:33.157Z project Test run data re-queued\n',
    '2020-06-08T21:45:38.891Z project Running postprocessor\n',
    '2020-06-08T21:45:38.891Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-08T21:45:39.019Z project Postprocessor execution finished\n',
    '2020-06-08T21:45:39.019Z project Test run started; run priority: 2\n',
    '2020-06-08T21:45:39.019Z testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0\n',
    '2020-06-08T21:45:39.019Z workers Starting test run, priority: 2\n',
    '2020-06-08T21:45:39.019Z nodeRunner Starting sandbox [worker #0, session #09u3r]\n',
    '2020-06-08T21:45:39.019Z nodeRunner Preparing sandbox [worker #0, session #09u3r]\n',
    '2020-06-08T21:45:39.019Z nodeRunner Prepared sandbox [worker #0, session #09u3r]\n',
    '2020-06-08T21:45:39.019Z workers [worker #0, session #09u3r] Running tests in sandbox\n',
    '2020-06-08T21:45:41.288Z workers [09u3r] Run 0 test(s), skipped 0 test(s)\n',
    '2020-06-08T21:45:41.749Z workers [09u3r] Sandbox is responsive, closing it\n',
    '2020-06-08T21:45:41.749Z project Test run finished\n',
    '2020-06-08T21:45:41.749Z project Processed console.log entries\n',
    '2020-06-08T21:45:41.749Z project Processed loading sequences\n',
    '2020-06-08T21:45:41.749Z project Processed executed tests\n',
    '2020-06-08T21:45:41.750Z project Processed code coverage\n',
    '2020-06-08T21:45:41.751Z project Test run result processed and sent to IDE\n'
  ]
}
```

**Comment by smcenlly** [comment]
Thanks for sending the sample repo. 

After setting up your project, we ran your project using `npx jest` to confirm that everything was working from the command line but there was an error in your test. A callback, `t`, is defined but is never called. 

Your current code:

```javascript
  test('foo', async t => {
    const a = 1
    expect(a).toBe(1)
  });
```

Should be either:

```diff
  test('foo', async t => {
    const a = 1
    expect(a).toBe(1)
+   t()
  })
```

or should be:

```diff
- test('foo', async t => {
+ test('foo', async () => {
    const a = 1
    expect(a).toBe(1)
  })
```

---

After fixing the test, we created a Wallaby run configuration in WebStorm with its `Configuration type` set to `Automatic`. For jest v24+, this is our recommended approach for configuring jest. Please update your configuration type to automatic as that should fix the problem for you. If it does not, please let us know.

![image](https://user-images.githubusercontent.com/2074089/84091264-45d91800-aa37-11ea-9578-648305d517d7.png)

**Comment by vjpr** [comment]
Does automatic configuration allow configuration with a `wallaby.js` file?

And I have multiple wallaby configs that I need to use.

**Comment by smcenlly** [comment]
> Does automatic configuration allow configuration with a wallaby.js file?

Yes it does, but usually this is not necessary. You can specify this in your WebStorm Run Configuration (i.e. have multiple run configurations). Using automatic configuration, you may also change the root path (e.g. if you want to run only for one package) - this is also saved with your Run Configuration. Setting it up is described in [our docs](https://wallabyjs.com/docs/intro/config.html).

If you want to keep a config file and switch the content, you can use:

**Wallaby.js Automatic Configuration file.**
```javascript
module.exports = () => ({
   autoDetect: true,
});
```

You can also add other options such as `runMode`: `onsave` using the Wallaby.js file with the `autoDetect`: `true` setting. You may also set Wallaby options using automatic configuration by editing your `package.json` (this is also described in our config docs).

> Can confirm that Automatic config seems to make it work...but why is this?

To better support Jest and to allow automatic configuration, we completely re-wrote our Jest integration. We still support jest using a manual configuration file, but it's a very different implementation and very different runtime environment. 

Wallaby provides its own runtime environment for different browsers and within node.js. If you're using automatic configuration, Wallaby's is actually using jest's runtime environment and most of its execution pipeline. This makes using automatic configuration much much closer to what you get when you run `npx jest` vs. having a Wallaby configuration file. We previously had issues where tests would work in jest but not Wallaby, and vice-versa. With automatic configuration, those problems are extremely rare/unlikely and would indicate an issue with our jest automatic configuration integration.

If you are using a manual configuration file, then you are using Wallaby's execution pipeline, not jest's. You therefore need to tell Wallaby how to resolve runtime dependencies, how to find your files, how to find your tests, how to compile your code, override jest configuration options, etc. to allow your jest tests to run in Wallaby's runtime environment. If you already have jest configured and working outside of Wallaby, setting up Wallaby manually is duplicated and unnecessary effort.

> Is there an example of a manual config that works?

We took a look at your configuration file and the error is stemming from your files/tests paths. Your patterns are a little aggressive and are telling Wallaby to copy and instrument all of the files that exist in your `node_modules` folder. The configuration below fixes this in your sample repo. While Wallaby **can** instrument your `node_modules` (and sometimes it's required, e.g. if your packages ship as TypeScript), generally you don't want to do this.

**Manual Configuration**
```diff
module.exports = (w) => {
  return {
    files: [
+     '!node_modules',
      'jest.config.js', 
      '**/src/**/*.js', 
      '!**/src/**/*.test.js'
    ],

    tests: [
+     '!node_modules',
      '**/src/*.test.js',
      '**/src/**/*.test.js',
    ],

    env: {
      type: 'node',
    },

    compilers: {
      '**/*.ts?(x)': w.compilers.typeScript({
        module: 'commonjs',
      }),
    },

    testFramework: 'jest',

    debug: true,

    runMode: 'onsave',

    setup: (w) => {
      const {join} = require('path')
      //w._testFrameworkPath
      const jestConfigPath = join(w.localProjectDir, './jest.config.js')
      console.log({jestConfigPath})
      const jestConfig = require(jestConfigPath)
      w.testFramework.configure(jestConfig)
    },

  }
}
```

**Comment by vjpr** [comment]
I didn't realize that `automatic` was a different pipeline to manual. I just assumed that it was just generating a `wallaby.js` config from an automatically detected jest config.

It has usually be a pain synchronizing cli test config with wallaby config, so now that I understand this feature, I am gladly welcome it!

Is automatic configuration only for jest? I also have some Ava tests too...

**Comment by smcenlly** [comment]
We currently support Automatic Configuration for jest v24+ and for Angular CLI v8.2.0+ that use karma as their test running. We're currently working on adding automatic configuration support for Angular CLI projects that use jest builder, and also for nx/nrwl workspaces.

We don't have any plans at this stage to add automatic configuration for Ava.

**Comment by vjpr** [comment]
If I wanted to keep two wallaby.js files with automatic config...it is not possible right? It would always use `wallaby.js`? There seems to be no way to have multiple wallaby runners. Say I want to run browser tests and node tests separately...how is this possible?

Why is there no configuration file setting to an automatic run configuration - seems like it would have been easy to add.

**Comment by smcenlly** [comment]
> If I wanted to keep two wallaby.js files with automatic config...it is not possible right? It would always use wallaby.js?

It is possible - you can have two files with automatic configuration. Automatic configuration does not use `wallaby.js` at all unless you've explicitly defined a configuration file, in which case, it will use the configuration file specified in your Run Configuration. 

For example, you can have two configuration files:

**Wallaby_Default.js**
```
module.exports = () => ({
   autoDetect: true,
});
```

**Wallaby_RunOnSave.js**
```
module.exports = () => ({
   autoDetect: true,
   runMode: 'onsave'
});
```

> There seems to be no way to have multiple wallaby runners.

If you are using Automatic Configuration, Wallaby will detect the test framework/runner you are using. Right now I'm struggling to think of a scenario where you would want to do this with automatic configuration. The best I can come up with is to have a project that uses both `jest` and Angular CLI that uses `karma` and also have `jest` tests for the Angular CLI project that I want to run at different times. We've not seen projects set up like this, but certainly that would be possible and we'd need to add some additional options to support.

> Say I want to run browser tests and node tests separately...how is this possible?

Can you be specific in what runners you are using? Both runners would need to allow Wallaby's automatic configuration. If you were using `jest` for both, you could have something like:

**Wallaby_1.js**
```
module.exports = () => ({
   autoDetect: true,
   configFile: './jest.config.wallaby_1.js'
});
```

**Wallaby_2.js**
```
module.exports = () => ({
   autoDetect: true,
   configFile: './jest.config.wallaby_2.js'
});
```

> Why is there no configuration file setting to an automatic run configuration - seems like it would have been easy to add.

Unless I'm misunderstanding you, there is, the `autoDetect`: `true` flag.

You may also **override** automatic configuration if you require/desire. (see our [Jest docs](https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration) and [Angular CLI docs](https://wallabyjs.com/docs/integration/angular.html#automatic-configuration-workspace-overrides) for how to do this).

**Comment by vjpr** [comment]
![Screen Shot 2020-06-09 at 11 54 53 am](https://user-images.githubusercontent.com/281413/84133953-24ccf300-aa48-11ea-9a13-e5dbb1b334b0.png)

How does wallaby detect the config file to use? Does it search for a file in the root dir with `wallaby` in its name?

> Recommended name is wallaby.js or wallaby.conf.js.
> https://wallabyjs.com/docs/intro/config.html#configuration-file

---

My use case is within a monorepo. I need to run my tests from the root - running from a sub-root would not work.

It looks something like this:

```
- common
  - foo / package.json
  - bar / package.json
- app1
- app2
```

1. There are peer dependencies (singletons) that are only available in the root package (this is pnpm-specific behavior). E.g. `@babel/core`, `react`.

2. When testing `app1` (but not `app2`), I want to also run tests for `common`.

**Comment by ArtemGovorov** [comment]
> Automatic config file dialog has not config file option in IntelliJ

To use automatic config with config file, you can select `Configuration File` option of the `Configuration type` and point the Run Configuration to the right Wallaby config file with `autoDetect` in it.

> and the jest config would specify which files to run tests on.

Yes, your `autoDetect` wallaby config files can point to different Jest config files, as @smcenlly desribed:

**Wallaby_1.js**
```
module.exports = () => ({
   autoDetect: true,
   testFramework: {
     configFile: './jest.config.wallaby_1.js'
   }
});
```
**Wallaby_2.js**

```
module.exports = () => ({
   autoDetect: true,
   testFramework: {
     configFile: './jest.config.wallaby_2.js'
   }
});
```
> In the docs is says to use testFramework.config. Are both methods possible?

No, @smcenlly pasted an incorrect example, I have fixed it in his response.

**Comment by vjpr** [comment]
Thanks, I just figured out what was meant (made an edit above) and it works perfectly.

I think the terminology is a little confusing.

Configuration type can be "automatic" or "configuration file", but then you can also use "automatic" config with a "configuration file" by adding "autoDetect: true".

Maybe in the run config: `Automatic` should be changed to `Autodetect`...

**Comment by vjpr** [comment]
Also, can `setup` config option be used in `autoDetect` config? What settings are available in "automatic" config file?

**Comment by ArtemGovorov** [comment]
> Also, can `setup` config option be used in `autoDetect` config?

Yes. Here is an example https://github.com/wallabyjs/public/issues/2427#issuecomment-635746516.

> What settings are available in "automatic" config file?

Most of settings that manual config supported. Some settings (such as `compilers`) may be ignored if they don't make sense in the execution pipeline that automatic config mode enables for a specific testing framework. If you have a question/concern regarding a specific setting, let us know.
