### ISSUE TITLE
Add support for node-qunit test runner

### ISSUE THREAD

**Issue by agarwalprashant** [wallabyjs/public#2442]
### Issue description 

Objective - The primary Objective is to study the momentjs source code using wallaby.js.

Tried running wallabyjs on momentjs Library source code to get a better insight of the source code which resulted in following error - 
**`[Error] Test framework [qunit] is not supported `**
**`[Error] Failed to load configuration file: Test framework [qunit] is not supported 
[Info]  Started Wallaby.js Core v1.0.906`**

Following is my wallaby.js file  - 

`module.exports = function () {
    return {
      files: [
        '*.js',
        { pattern: 'node_modules/**/*.js', instrument: false },
        'test/*.js',
        '!test/*.test.js',
        '!wallaby.js'
      ],
  
      tests: ['src/test/*.test.js'],
      testFramework: 'qunit',
  
      env: {
        type: 'node',
        
      },
  
    
    };
  };`

My node version is  - 10.19.0

It would be really helpful if somebody can guide me through the correct wallaby.js configuration file.Thanks in advance

**Comment by smcenlly** [comment]
Unfortunately the test runner used by momentjs, [`node-qunit`](https://github.com/qunitjs/node-qunit) is not currently supported by Wallaby.

We do not have any immediate plans to add support for `node-qunit` but have renamed this issue and added as a feature request.

If you wanted to study the momentjs source code with Wallaby, an alternative available to you today would be to update the momentjs tests to run in one of [our supported testing frameworks](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks).

**Comment by smcenlly** [comment]
Closing this feature request. With an average of ~400 downloads per week in [npm](https://www.npmtrends.com/node-qunit), we have no intention of supporting `node-qunit` as a test runner.
