### ISSUE TITLE
Webstorm error colour foreground

### ISSUE THREAD

**Issue by quantuminformation** [wallabyjs/public#2444]
Anyone know what colour setting I need to change to get this red changed?

![image](https://user-images.githubusercontent.com/216566/84365822-4c4fc700-abd2-11ea-83f7-f416335f5151.png)

**Comment by ArtemGovorov** [comment]
You nay change the colour via Wallaby Settings:

<img width="961" alt="Screen Shot 2020-06-11 at 6 59 02 pm" src="https://user-images.githubusercontent.com/979966/84366064-af168200-ac15-11ea-981d-d23fb9dad030.png">

Note that you have to restart WebStorm after the change.

**Comment by quantuminformation** [comment]
awesome thx

![image](https://user-images.githubusercontent.com/216566/84368532-f41ac400-abd5-11ea-9eb1-659f25bd9ce5.png)
