### ISSUE TITLE
VS Code in Windows 10 unable to rename extension folder

### ISSUE THREAD

**Issue by chris-fleming** [wallabyjs/public#2446]
### Issue description or question

Hi, I have a windows 10 work SOE and I'm using VS Code 1.46.0. When the wallaby extension updates itself I get an error changing the extension directory from wallaby_new to wallaby.

Has anyone experienced this before? I tried starting vs code as administrator but still had the issue. If i manually go to directory and rename, it works but means i need to restart vs.

Error message sample is:  
Error: EPERM: operation not permitted, rename 'c:\Users\abcde\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.207\wallaby_new' -> 'c:\Users\abcde\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.207\wallaby'

**Comment by ArtemGovorov** [comment]
Yes, we have seen the rename issue before.

In all cases it was an issue with virus scanner (in some cases Zone Alarm specifically), blocking Wallaby extension from renaming downloaded folder. 

If you have any antivirus software installed, please make sure it’s not blocking Wallaby IO operations on its own folder.

**Comment by chris-fleming** [comment]
Thanks for the info and fast response. Unfortunately as its a work machine can't change the virus scanning setting so will keep with the manual renames or set to be manual updates. Cheers

**Comment by ArtemGovorov** [comment]
We will be looking into improving the update mechanism next week, will update the issue when we make any changes.

**Comment by ArtemGovorov** [comment]
We have improved our update mechanism, please let us know if you have any issues with updating to new Wallaby extension versions in future.

**Comment by chris-fleming** [comment]
Thanks very much.. it updated yesterday afternoon without issue.. cheers
