### ISSUE TITLE
issue running test cases in wallabyjs

### ISSUE THREAD

**Issue by agarwalprashant** [wallabyjs/public#2453]
**Issue description**
Objective - The primary Objective is to study the momentjs source code using wallaby.js.

As discussed before, the testing framework used by moment is node-qunit which is currently not supported by wallaby.So I tried writing new test cases in mocha which is giving me grey/white boxes when wallaby runs and none of the test runs.

My project is hosted at following URL - [project link](https://github.com/agarwalprashant/quickMocha
)
Following is my wallaby.js file -

`module.exports = function () {
    return {
      files: [
        'src/ ** /*.js',
        { pattern: 'node_modules/**/*.js', instrument: false },
     
      ],
  
      tests: ['test/test.js'],
      testFramework: 'mocha',

    
    };
  };`

My node version is - 10.19.0

It would be really helpful if somebody can guide me through the correct wallaby.js configuration file.Thanks in advance

**Comment by ArtemGovorov** [comment]
@agarwalprashant Sure, please send us an email to hello@wallabyjs.com with your diagnostics report (the steps to get the report described in the new issue template) and we'll take it from there.
