### ISSUE TITLE
bug: `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`

### ISSUE THREAD

**Issue by tomsquest** [wallabyjs/public#2456]
### Issue description or question

Wallaby is not running anymore since last update.

Given the last update (self update as of 2020.06.22) 
When run
Then Wallabys.js console shows this message in its console:

```
wallaby.js started
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at WebSocketServer.emit (events.js:198:13)
    at Server.emit (events.js:198:13)
    at onParserExecuteCommon (_http_server.js:567:14)
    at onParserExecute (_http_server.js:513:3)
```

Wallaby spinner last forever. On click on the Stop button, this notification is displayed:

![image](https://user-images.githubusercontent.com/365778/85260932-c2261f00-b46b-11ea-8de7-e337e4224871.png)

### Wallaby diagnostics report

No report, Wallaby does not start.

### Version

Latest as of 2020.06.22, Wallaby updated itself.

### Configuration

Wallaby version (from the plugins section): 1.0.177

Intellij version Ultimate 2020.1.2 

Using Wallaby Automatic configuration:

![image](https://user-images.githubusercontent.com/365778/85260583-344a3400-b46b-11ea-84f6-ffe891550a47.png)

Using node 10.21.0

```bash
$ which node                                                                 
/home/tom/.asdf/installs/nodejs/10.21.0/bin/node
```

**Comment by FlemmingBehrend** [comment]
Same issue, but in vscode

**Comment by ArtemGovorov** [comment]
Thanks for letting us know. The was an issue with one of the changes. The issue is fixed and the fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Apologies for the inconvenience.

**Comment by tomsquest** [comment]
@ArtemGovorov that was fast ! :sparkles: 
Thanks a lot!
