### ISSUE TITLE
When files/folders are moved via Atom's file tree, tests don't run properly until wallaby is restarted

### ISSUE THREAD

**Issue by danmartinez101** [wallabyjs/public#246]

**Comment by ArtemGovorov** [comment]
I have reproduced something, but not sure it's the same issue. Just to confirm that I'm reproducing the issue correctly, could you check something form me please? When you hit the issue after some file/folder manipulation, then close all files in editor, and then re-open some file/test and edit it, does the issue go away or persists until you restart wallaby.js? If closing files doesn't make it go away until wallaby restart, then it may be a different issue that I'm reproducing and in this case could you please share some steps how to reproduce the one you're experiencing, for example on the [calculator sample](https://github.com/wallabyjs/calculator-sample)?

**Comment by ArtemGovorov** [comment]
The issue I have been able to reproduce is fixed now (Atom plugin v1.0.3, Core v1.0.95). Please let me know if you still able to reproduce the issue that you've been experiencing after the update.
