### ISSUE TITLE
Jest-circus runner not working with automatic jest config

### ISSUE THREAD

**Issue by azaeng04** [wallabyjs/public#2462]
### Issue description or question

Jest-circus runner doesn't seem to be recognized by Wallaby.

 These are the packages installed:

```
"devDependencies": {
    "@agct/common-testing-helpers": "^2.0.10",
    "@agct/eslint-config-agct": "5.0.0",
    "@agct/test-data": "^16.3.4",
    "@agct/test-utilities": "^1.11.1",
    "babel-jest": "26.0.1",
    "chance": "1.1.4",
    "eslint-plugin-jest": "23.9.0",
    "jest": "^26.0.1",
    "mockserver-client": "5.10.0"
  }
```

Wallaby error on console:
`‍[Info]  Started Wallaby.js Core v1.0.920
[Error] Failed to load configuration file: Automatic Jest configuration error: Failed to read Jest configuration from '.': ● Validation Error: 
[Error]   Module jest-circus/runner in the testRunner option was not found. 
[Error]          <rootDir> is: . `

### Wallaby Setup

```
process.env.TEST_ENV = 'dev';
process.env.TEST_DATA_ENV = 'dev';
process.env.NODE_DEBUG = 'log';

module.exports = () => ({
  autoDetect: true,
  tests: ['./ci/**/*.test.js', './verification/**/*.test.js'],
});

```

### Wallaby diagnostics report

Unable to retrieve

**Comment by smcenlly** [comment]
Is jest working for you from the CLI? From the package dependencies that you provided, it doesn't look like `jest-circus` is installed. We set up a new project and it is working for us (package dependencies/jest config below):

**jest.config.js**
```
module.exports = {
  testRunner: "jest-circus/runner"
};
```

**package.json dependencies**
```
  "devDependencies": {
    "babel-jest": "26.0.1",
    "chance": "1.1.4",
    "eslint-plugin-jest": "23.9.0",
    "jest": "^26.0.1",
    "jest-circus": "^26.1.0",
    "mockserver-client": "5.10.0"
  }
```

Could you please install as a direct dependency of your project to see if that helps:

```
yarn add --dev jest-circus
```

or 

```
npm install --save-dev jest-circus
```

If you are still having problems, could you please provide:

* Your **jest.config.js**
* Code for custom testEnvironment (if you are not using `node` or `jsdom`)
* A sample test (if you get to the point that tests are failing in Wallaby but not from the command line).

**Comment by smcenlly** [comment]
We're going to assume that our suggestion above fixed the problem for you. If not, please let us know and we'll re-open this issue.

**Comment by azaeng04** [comment]
Yes @smcenlly it has been resolved. I just needed to install jest-circus as a dependency.
