### ISSUE TITLE
Allow running wallaby with an empty files array

### ISSUE THREAD

**Issue by Floriferous** [wallabyjs/public#2476]
I noticed that you're not allowed to run wallaby if your `files` array in the config file is empty. I'm not sure if this has been done to help new people and make sure they know that they should use it. In my case, when extracting a reproduction, it adds one small pointless step to it, as I may just want to have a single file in my `tests` array.

I wonder if the behavior could instead be to allow an empty (or non-existent) `files` key, but show a warning in the console, something like this: `files is empty in your wallaby config file, please make sure this is not a mistake LINK_TO_WALLABY_DOCS`.

**Comment by smcenlly** [comment]
We're improved handling of this error and now provide a link to docs.
