### ISSUE TITLE
How to configure Wallaby to run with lerna packages, each with their own `jest.config.js`

### ISSUE THREAD

**Issue by ryall** [wallabyjs/public#2478]
My project is currently configured using multiple Lerna packages, each with their own `jest.config.js` setup. 

If I copy and paste the `wallaby.js` config to each package root directory and select the configuration every time I change packages, everything works well. 

```
<root>/
    packages/
        lib-one/
            jest.config.js
            wallaby.js
        lib-two/
            jest.config.js
            wallaby.js
        lib-three/
            jest.config.js
            wallaby.js
    package.json
```

However, this becomes **very tiresome** with the more packages I add to the project. 

Instead I'd prefer to have a single master `wallaby.js` configuration in the project root and load all the configured packages (including their independent `jest.config.js` files) at once, so that I don't have to keep switching configurations.

```
<root>/
    packages/
        lib-one/
            jest.config.js
        lib-two/
            jest.config.js
        lib-three/
            jest.config.js
    package.json
    wallaby.js
```

Experimenting with the config, I was unable to achieve this.

**Comment by smcenlly** [comment]
To get Wallaby working, Jest must be installed in the mono-repo root. You must also configure jest to run from your mono-repo root (i.e. from the CLI with `npx jest`). To do this:

1. Install `jest` in your `<root>` directory.
2. Configure `jest` to run for your entire mono-repo using `npx jest` from the CLI at the mono-repo root. For example:

```javascript
// <root>/jest.config.js

module.exports = { 
  projects: [
    '<rootDir>/packages/lib-one/jest.config.js', 
    '<rootDir>/packages/lib-two/jest.config.js',
    '<rootDir>/packages/lib-three/jest.config.js',
  ] 
};
```

**Comment by ryall** [comment]
Took a while because of the Babel CWD issue (https://github.com/facebook/jest/issues/7359) but managed to get it working. Thanks!
