### ISSUE TITLE
istanbul ignore support

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#248]
[istanbul ignore coverage hint in comment](https://github.com/gotwarlost/istanbul/blob/c87ada03cb485e4f9110224899b68d8dc27e4bf3/ignoring-code-for-coverage.md) should be supported

**Comment by hieudt** [comment]
+1

**Comment by ArtemGovorov** [comment]
The [feature support](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) is landed in the core v1.0.321. Note that wallaby config change is required to enable it (specifying the hint). You may either wait for the automatic core update or [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
