### ISSUE TITLE
Automatic angular configuration fails with pnpm

### ISSUE THREAD

**Issue by KrystianMazur** [wallabyjs/public#2480]
### Issue description or question

When I use npm everything works fine. Automatic configuration doesn't work after switching to pnpm package manager.
Angular 9
Jasmine 3.5
Wallaby 1.0.184
pnpm 5.2.3
node 10.20.1

Wallaby console:
```
wallaby.js started
core v1.0.926
Failed to load configuration file: Automatic Angular CLI configuration error: Unable to load webpack module.
```

### Files:

wallaby.js
```
module.exports = () => ({
  autoDetect: true,
  testFramework: 'jasmine',
});
```

test.wallaby.ts
```
import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';

declare const require: {
  context(
    path: string,
    deep?: boolean,
    filter?: RegExp,
  ): {
    keys(): string[];
    <T>(id: string): T;
  };
};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
);
```

### Wallaby diagnostics report

When this error occurs there is no report.

**Comment by smcenlly** [comment]
Unfortunately the way pnpm installs modules by default is not supported by Wallaby. Having said that, the following command will install modules in a way that is supported:

`pnpm install --shamefully-flatten`

---

We were also able to solve your problem another way, by installing `webpack` as a `devDependency` for the Angular project. While this works for a simple project, there's no guarantee that this will work in your situation depending on your project setup/dependencies, etc. We recommend using `pnpm install --shamefully-flatten`.
