### ISSUE TITLE
Angular 10: Error if tsconfig json file contains comments

### ISSUE THREAD

**Issue by prabh-62** [wallabyjs/public#2482]
### System Info
OS: `Mac OS 10.15.6`
Node: `14.5.0`
Yarn: `1.22.4`
VS Code: `1.47.2`
Angular CLI: `10.0.3`
Wallaby Core: `1.0.844`

### Steps to reproduce
- `npx @angular/cli new apps --strict --create-application=false`
- `cd apps`
- `yarn ng generate application admin-console --defaults true`
- `yarn ng generate application support-portal --defaults true`
- `code .`
- Open Command Pallete using <kbd>Cmd + Shft + P</kbd> and type `Wallaby.js: Start`
- Navigate to `Output` window and switch to `Wallaby.js Console`
```‍log
[Info]  Started Wallaby.js Core v1.0.844
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: /Users/<user>/dev/temp/apps/tsconfig.json: Unexpected token / in JSON at position 0 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '/Users/<user>/dev/temp/apps'.
```

<img width="1422" alt="wallaby_comments_json" src="https://user-images.githubusercontent.com/13006107/87864661-0278a000-c939-11ea-877f-8d2d5c3500c4.png">

### Workaround
Delete all comments in 
- `tsconfig.json`
- `projects/admin-console/tsconfig.spec.json`
- `projects/support-portal/tsconfig.spec.json`

**Comment by smcenlly** [comment]
This has been fixed and is available in the latest version of Wallaby core, v1.0.930. Wallaby should update automatically for you to fix this problem. If it does not, you may force a core update in VS Code by using the command `Wallaby.js: Force Core Update`.
