### ISSUE TITLE
Angular 10: Global styles are not used when running projects in a workspace

### ISSUE THREAD

**Issue by prabh-62** [wallabyjs/public#2484]
### System Info
OS: `Mac OS 10.15.6`
Node: `14.5.0`
Yarn: `1.22.4`
VS Code: `1.47.2`
Angular CLI: `10.0.4`
Wallaby Core: `1.0.931`

### Steps to reproduce
- `npx @angular/cli new apps --strict --create-application=false`
- `cd apps`
- `yarn ng generate application admin-console --defaults true`
- `yarn ng generate application support-portal --defaults true`
- `code .`
- Replace code in `projects/support-portal/src/app/app.component.html` with
```html
<button class="btn">World</button>
```
- Replace code in `projects/support-portal/src/styles.css` with 
```css
.btn {
  text-transform: uppercase;
}
```
- Replace code in `projects/support-portal/src/app/app.component.spec.ts` with
```typescript
import { TestBed, async } from '@angular/core/testing';
import { By } from '@angular/platform-browser';
import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
    }).compileComponents();
  }));

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const button = fixture.debugElement.query(By.css('.btn'));
    const buttonElement = button.nativeElement as HTMLButtonElement;
    expect(buttonElement.innerText).toEqual('WORLD');
  });
});
```
- Run unit test with angular cli: `yarn test --project support-portal`. Test passes
<img width="1148" alt="test_ng_cli" src="https://user-images.githubusercontent.com/13006107/87999930-4c44c000-caca-11ea-8dd1-a85f69448975.png">

- Open Command Pallete using <kbd>Cmd + Shft + P</kbd> and type `Wallaby.js: Start`
- Test fails in wallaby mode
<img width="732" alt="test_wallaby" src="https://user-images.githubusercontent.com/13006107/87999702-abee9b80-cac9-11ea-9d69-fc72c966c11c.png">

### Workaround
- Replace code in `projects/admin-console/src/styles.css` with
```css
.btn {
  text-transform: uppercase;
}
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem and providing the steps to reproduce.

The reason for this behavior is that when Wallaby is running multiple projects for your workspace, it is running them the same way Angular CLI does. Unlike the Angular CLI, Wallaby allows you to run multiple apps at the same time but there are some edge cases that are not supported. 

Specifically, you may encounter these edge cases if you have different global styles, conflicting assets (same name, different content) or conflicting polyfills code,

There are a few ways you can work around these problems:

1. Only start Wallaby on the application that you're currently working on. In VS Code, use the `Wallaby.js: Select Configuration` command and select `Automatic Configuration <custom directory>...` and select your application root. Our [docs](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) describe how to do this for other editors.

2. Minimize conflicts by making global styles/assets consistent across different applications. For example, make `styles.css` the same in all applications (please note that changes to global styles require Wallaby restart to take effect).

3. Scope your styles:
  a. Using nested css selectors (e.g. create class name in root level div `support-portal` and have all selectors use `support-portal` in their selector: `.support portal .btn`)
  b. Using component styles (i.e. putting code in `app.component.css`)
