### ISSUE TITLE
Downloading Wallaby.js core behind proxy is stuck

### ISSUE THREAD

**Issue by aykutkilic** [wallabyjs/public#2491]
### Issue description or question

When I try to download Wallaby.js core by "Force core update" the download is stuck.
![image](https://user-images.githubusercontent.com/1406590/89759315-89f99f00-daf2-11ea-8d05-7dd4566b3ba4.png)
No progress or error msg is shown.

I've tried w. v1.0.225

**Comment by ArtemGovorov** [comment]
Please configure Wallaby for VS Code as described at https://github.com/wallabyjs/public/issues/1123#issuecomment-294623732.
