### ISSUE TITLE
switch to stop munging absolute paths?

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#2492]
### Issue description or question

I'm doing some work with absolute paths, and in Wallaby's test output (e.g., in the browser), it appears absolute paths are automatically replaced by relative ones.  I understand that Wallaby runs in _some weird directory_ which would potentially confuse people if it was displayed verbatim.  I think this is the correct behavior 98% of the time.

However, my problem is that diffs in failing assertions become nonsensical, e.g.:

![image](https://user-images.githubusercontent.com/924465/89957262-cc52d700-dbeb-11ea-97c3-9d41c51231da.png)

In the above case, my _expected value_ is a relative path, but the _actual value_ is an absolute path--but the actual value is munged.  So this caused some confusion/misdirection until I realized what Wallaby was doing.

Is there a flag to disable this behavior?

**Comment by smcenlly** [comment]
@boneskull - are you able to provide us with some additional details on exactly what you're doing (perhaps a simple sample test) with the paths, as well as your Wallaby.js configuration file so we can understand what's going on?

**Comment by boneskull** [comment]
```js
// this-file.js
const assert = require('assert')
const path = require('path')

assert.strictEqual(__filename, 'this-file.js');
```

untested, but that's the gist of it. the assertion will fail like it should, but the absolute path (`__filename`) will be converted to a relative one in wallaby's display

**Comment by smcenlly** [comment]
Thanks - we'll look into it right now

**Comment by smcenlly** [comment]
We've added a new setting to not replace the instrumented file paths with the relative path in any messages reported by Wallaby. The new setting, `preservePaths` is available in Wallaby core `v1.0.943`.

Example configuration below:

```diff
module.exports = function () {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    env: {
      type: 'node'
    },

+   preservePaths: true
  };
};
```

**Comment by boneskull** [comment]
thanks!!

**Comment by boneskull** [comment]
works as expected
