### ISSUE TITLE
Wallaby fails on vue cli project with jest v24+.

### ISSUE THREAD

**Issue by blowsie** [wallabyjs/public#2493]
### Issue description or question

Wallaby fails on vue cli project with jest v24+.
I followed [this guide](https://wallabyjs.com/docs/tutorial/vue.html?editor=jb), where possible (i was using an existing project)

Might be worth noting im using yarn workspaces.

Please let me know if i can provide anymore information somehow. 
 

```
λ vue --version
@vue/cli 4.5.2
```

```
λ vue info

Environment Info:

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.17763.831.0)
  npmPackages:
    vue-loader: ^15.9.3 => 15.9.3

```

```
λ yarn why jest
yarn why v1.22.4
[1/4] Why do we have the module "jest"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "jest@24.9.0"
```

### Wallaby diagnostics report

wallaby.js started
wallaby.js stopped

Process finished with exit code 0

**Comment by blowsie** [comment]
Perhaps its because im liscensed on an older version? 
Is it possible to renew a trial period? I used wallaby some years ago but havent used it for some time

**Comment by ArtemGovorov** [comment]
> Perhaps its because im liscensed on an older version?
> Is it possible to renew a trial period? 

Quite possibly, please try downloading the latest version and trial license at https://wallabyjs.com/download/, let us know if it works for you.

**Comment by blowsie** [comment]
Didnt realise I could get a another free trial form there, thanks! Working as expected
