### ISSUE TITLE
Having trouble getting Wallaby VS Code extension to start

### ISSUE THREAD

**Issue by jackwkinsey** [wallabyjs/public#2495]
### Issue description or question

Whenever I try to start the Wallaby VS Code extension (CMD + Shift + R R) I see the following error in the Wallaby.js console output:

>‍[Error] dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.64.dylib 
[Error]   Referenced from: /usr/local/opt/node@8/bin/node 
[Error]   Reason: image not found

I haven't really found much help through Googling on this. The consensus seems to be that Node needs re-installed (which I have done and I'm using `n` to manage node versions on my system).

`/usr/local/opt/icu4c/lib/` doesn't contain `libicui18n.64.dylib` but it does have `libicui18n.67.dylib`

It seems like this may be more of a VS Code issue, but Wallaby and Quokka seem to be the only extensions I've noticed this affecting. Has anyone else run into this issue or know of a way to resolve it?

**Comment by jackwkinsey** [comment]
Found a solution so I'll close this!

If anyone else runs into this issue make sure your Wallaby.js Node setting is set to the correct path to your Node executable.

Run `which node` in your console to find the path to `node`: for me this was `/usr/local/bin/node`

And update the Wallaby.js Node setting in VS Code settings with that path value and re-start Wallaby.

That solved my issue and is now working!

**Comment by marcellkiss** [comment]
Thanks, saved my day 🎉
