### ISSUE TITLE
Getting cannot use import statement outside a module when testing a visual studio code extension project

### ISSUE THREAD

**Issue by adimoraret** [wallabyjs/public#2499]
### Issue description or question

Getting **SyntaxError: Cannot use import statement outside a module** when testing a visual studio code extension project. 

### Wallaby diagnostics report

[Info]  2020-08-19T00:43:51.751Z project Wallaby Node version: v12.18.2
[Info]  2020-08-19T00:43:51.751Z project Wallaby config: /home/adi/Workspace/playground/hello-world/wallaby.js
[Info]  Started Wallaby.js Core v1.0.944
[Info]  2020-08-19T00:43:51.784Z fs File added: test/mytest.test.js
[Info]  2020-08-19T00:43:52.339Z project File cache: /home/adi/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.230/projects/1c7a324aa041de65
[Info]  2020-08-19T00:43:52.348Z uiService Listening port 51235
[Info]  2020-08-19T00:43:52.351Z project Config file change detected, invalidating local cache
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Info]  2020-08-19T00:43:52.374Z workers Parallelism for initial run: 2, for regular run: 2
[Info]  2020-08-19T00:43:52.375Z workers Starting run worker instance #0
[Info]  2020-08-19T00:43:52.375Z workers Starting run worker instance #1
[Info]  2020-08-19T00:43:52.376Z workers Web server is listening at 44689
[Info]  2020-08-19T00:43:52.376Z project File cache requires some updates, waiting required files from IDE
[Info]  2020-08-19T00:43:52.398Z project File test/mytest.test.js changes are patches only: false
[Info]  2020-08-19T00:43:52.400Z project Preparing to process test/mytest.test.js
[Info]  2020-08-19T00:43:52.401Z project Starting processor pool (if not yet started)
[Info]  2020-08-19T00:43:52.575Z workers Started run worker instance (delayed) #0
[Info]  2020-08-19T00:43:52.631Z workers Started run worker instance (delayed) #1
[Info]  2020-08-19T00:43:52.900Z processor Running 1 processor(s) for test/mytest.test.js
[Info]  2020-08-19T00:43:53.090Z processor Finished running one processor for test/mytest.test.js
[Info]  2020-08-19T00:43:53.093Z project Processing compiled test/mytest.test.js
[Info]  2020-08-19T00:43:53.094Z project Instrumenting test/mytest.test.js, via process pool: true
[Info]  2020-08-19T00:43:53.112Z project No preprocessors configured for test/mytest.test.js
[Info]  2020-08-19T00:43:53.112Z project Writing to disk and caching processed file test/mytest.test.js
[Info]  2020-08-19T00:43:53.113Z project File test/mytest.test.js changes saved, store ts: 1597797524340, change ts: 1597797832398
[Info]  2020-08-19T00:43:53.114Z project Stopping process pool
[Info]  2020-08-19T00:43:53.116Z project Running postprocessor
[Info]  2020-08-19T00:43:53.119Z postprocessor New TypeScript language service is required
[Info]  2020-08-19T00:43:53.119Z postprocessor TypeScript postprocessor will be removed because in 1 project files none were found by patterns: [ '**/*.ts?(x)' ]
[Info]  2020-08-19T00:43:53.121Z project Postprocessor execution finished
[Info]  2020-08-19T00:43:53.121Z project Postprocessor is removed as requested by itself
[Info]  2020-08-19T00:43:53.122Z project Test run started; run priority: 3
[Info]  2020-08-19T00:43:53.122Z project Running all tests
[Info]  2020-08-19T00:43:53.123Z workers Starting test run, priority: 3
[Info]  2020-08-19T00:43:53.123Z nodeRunner Starting sandbox [worker #0, session #5ulzi]
[Info]  2020-08-19T00:43:53.124Z nodeRunner Preparing sandbox [worker #0, session #5ulzi]
[Info]  2020-08-19T00:43:53.124Z nodeRunner Prepared sandbox [worker #0, session #5ulzi]
[Info]  2020-08-19T00:43:53.124Z workers [worker #0, session #5ulzi] Running tests in sandbox
[Info]  2020-08-19T00:43:53.135Z workers Sandbox (active) [5ulzi] error: Cannot use import statement outside a module
[Error] Runtime error: ./test/mytest.test.js:2 
[Error] import assert from 'assert'; 
[Error] ^^^^^^ 
[Error] SyntaxError: Cannot use import statement outside a module 
[Error]     at wrapSafe (internal/modules/cjs/loader.js:1054:16) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1102:27) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:986:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:879:14) 
[Error]     at Module.require (internal/modules/cjs/loader.js:1026:19) 
[Error]     at require (internal/modules/cjs/helpers.js:72:18) 
[Error]     at Object.exports.requireOrImport (./node_modules/mocha/lib/esm-utils.js:20:12) 
[Error]     at Object.exports.loadFilesAsync (./node_modules/mocha/lib/esm-utils.js:33:34) 
[Error]     at Mocha.loadFilesAsync (./node_modules/mocha/lib/mocha.js:427:19) 
[Error]     at new Promise (<anonymous>) 
[Error]     at WebSocket.emit (events.js:315:20) 
[Error]     at afterWrite (_stream_writable.js:490:5) 
[Error]     at onwrite (_stream_writable.js:470:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:98:3) 
[Error]     at Zlib.processCallback (zlib.js:578:8) 
[Info]  2020-08-19T00:43:53.236Z workers [5ulzi] Run 0 test(s), skipped 0 test(s)
[Info]  2020-08-19T00:43:53.239Z workers [5ulzi] Sandbox is responsive, closing it
[Info]  2020-08-19T00:43:53.240Z project Test run finished
[Info]  2020-08-19T00:43:53.240Z project Processed console.log entries
[Info]  2020-08-19T00:43:53.240Z project Processed loading sequences
[Info]  2020-08-19T00:43:53.240Z project Processed executed tests
[Info]  2020-08-19T00:43:53.241Z project Processed code coverage
[Info]  2020-08-19T00:43:53.246Z project Test run result processed and sent to IDE

wallaby js file is
```
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
    ],
    tests: [
      'test/*.test.js',
    ],
    debug:true,
    trace: true,
    env: {
      type: 'node',
      runner: 'node',
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel({}),
    }    
  };
};
```

my sample test file is this:
```
import assert from 'assert';
describe("my tests", () => {
  it('should pass', () => {
    assert.equal(true, true);
  })
});
```

Whole sample project is [here](https://github.com/adimoraret/vsc-hello-world)

**Comment by ArtemGovorov** [comment]
While you can make your current simple test file work (just need to install `@babel/preset-env` and add it to `.babelrc` file), Wallaby doesn't support testing VS Code extensions at the moment https://github.com/wallabyjs/public/issues/1548 (it would need to run VS Extension Host environment, not simple node).
