### ISSUE TITLE
Frameworks like in karma.

### ISSUE THREAD

**Issue by davit-yavryan** [wallabyjs/public#25]
module.exports = function () {
    return {
        files: [...],
        tests: [...],
        env: {...}
        frameworks: ['mocha', 'sinon', 'expect'],
    };
};

**Comment by ArtemGovorov** [comment]
While we may add the setting, for now only preprocessors, bootstrap and the config file itself are places where wallaby functionality can be extended, so I am not sure how adding the framework setting would help right now.

Could you please tell a bit more how would you like for example `sinon` and `expect` frameworks to work in wallaby if specified like you have suggested? If you mean just including them into each test run sandbox - then you can already do it via the `files` list.

**Comment by ArtemGovorov** [comment]
Please let me know some more details about the feature request and I'll re-open the issue.
