### ISSUE TITLE
Toggle debug breakpoint via mouse/clicking with WallabyJS enabled

### ISSUE THREAD

**Issue by xtbe** [wallabyjs/public#2500]
I'm new using Wallabyjs but I ran the following:

Previously I used to put a breakpoint in my code by clicking in the left-margin of the editor. This still works if there's no square visible for Wallaby.js. In the attached screenshot you can see this on line 43. However when clicking on any line between 39-42 this doens't work.

![image](https://user-images.githubusercontent.com/909796/91013756-71a47c80-e5e8-11ea-9bb5-e29aeb3017f4.png)

Toggling a breakpoint with the keyboard shortcut works.

Is there any way to enable mouse support of toggling breakpoints? If not, is this document otherwise would be good to add you need to use the keyboard shortcut to toggle and that mouse-clicking is not supported.

Thank you for the feedback

**Comment by ArtemGovorov** [comment]
Unfortunately it's a current limitation of the VS Code UI. Here's the issue in the VS Code repo: https://github.com/Microsoft/vscode/issues/5923, feel free to subscribe and vote for it.
