### ISSUE TITLE
Unable to detect test file in angular project

### ISSUE THREAD

**Issue by samirsahoo** [wallabyjs/public#2502]
Hi Team,

We are using wallaby js in the our Angular Project.

Our project Structure is like

-components
        |- node_modules
        |- component1
               -component1.html
               -component1.ts
               -component1.spec.ts
       |- component2
               -component2.html
               -component2.ts
               -component3.spec.ts
      |-wallaby.js
      |-angular.json
      |-tsconfig.spec.json
      |-package.json
      |-karma.conf.js
      |-test.ts
      ..........

1. Used the same wallaby.js provided for Angular Project

```javascript
  module.exports = function(wallaby) {
  const wallabyWebpack = require('wallaby-webpack');
  const path = require('path');
  const fs = require('fs');

  const specPattern = '/**/*spec.ts';
  const angularConfig = require('./angular.json');

  const projects = Object.keys(angularConfig.projects).map(key => {
    return { name: key, ...angularConfig.projects[key] };
  }).filter(project => project.sourceRoot)
    .filter(project => project.projectType !== 'application' || 
                       (project.architect &&
                        project.architect.test &&
                        project.architect.test.builder === '@angular-devkit/build-angular:karma'));

  const applications = projects.filter(project => project.projectType === 'application');
  const libraries = projects.filter(project => project.projectType === 'library');

  const tsConfigFile = projects
    .map(project => path.join(__dirname, project.root, 'tsconfig.spec.json'))
    .find(tsConfig => fs.existsSync(tsConfig));

  const tsConfigSpec = tsConfigFile ? JSON.parse(fs.readFileSync(tsConfigFile)) : {};

  const compilerOptions = Object.assign(require('./tsconfig.json').compilerOptions, tsConfigSpec.compilerOptions);
  compilerOptions.emitDecoratorMetadata = true;

  return {
    files: [
      { pattern: path.basename(__filename), load: false, instrument: false },
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.+(ts|js|css|less|scss|sass|styl|html|json|svg)',
        load: false
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + specPattern,
        ignore: true
      })),
      ...projects.map(project => ({
        pattern: project.sourceRoot + '/**/*.d.ts',
        ignore: true
      }))
    ],

    tests: [
      ...projects.map(project => ({
        pattern: project.sourceRoot + specPattern,
        load: false
      }))
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        ...compilerOptions,
        getCustomTransformers: program => {
          return {
            before: [
              require('@ngtools/webpack/src/transformers/replace_resources').replaceResources(
                path => true,
                () => program.getTypeChecker(),
                false
              )
            ]
          };
        }
      })
    },

    preprocessors: {
      /* Initialize Test Environment for Wallaby */
      [path.basename(__filename)]: file => `
 import '@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills';
 import 'zone.js/dist/zone-testing';
 import { getTestBed } from '@angular/core/testing';
 import { BrowserDynamicTestingModule,  platformBrowserDynamicTesting} from '@angular/platform-browser-dynamic/testing';

 getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());`
    },

    middleware: function(app, express) {
      const path = require('path');

      applications.forEach(application => {
        if (
          !application.architect ||
          !application.architect.test ||
          !application.architect.test.options ||
          !application.architect.test.options.assets
        ) {
          return;
        }

        application.architect.test.options.assets.forEach(asset => {
          if (asset && !asset.glob) {
            // Only works for file assets (not globs)
            // (https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets)
            app.use(asset.slice(application.sourceRoot.length), express.static(path.join(__dirname, asset)));
          }
        });
      });
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyWebpack({
      entryPatterns: [
        ...applications
          .map(project => project.sourceRoot + '/polyfills.js')
          .filter(polyfills => fs.existsSync(path.join(__dirname, polyfills.replace(/js$/, 'ts')))),
        path.basename(__filename),
        ...projects.map(project => project.sourceRoot + specPattern.replace(/ts$/, 'js'))
      ],

      module: {
        rules: [
          { test: /\.css$/, loader: ['raw-loader'] },
          { test: /\.html$/, loader: 'raw-loader' },
          {
            test: /\.ts$/,
            loader: '@ngtools/webpack',
            include: /node_modules/,
            query: { tsConfigPath: 'tsconfig.json' }
          },
          { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
          { test: /\.less$/, loaders: ['raw-loader', { loader: 'less-loader' }] },
          {
            test: /\.scss$|\.sass$/,
            loaders: [{ loader: 'raw-loader' }, { loader: 'sass-loader', options: { implementation: require('sass') } }]
          },
          { test: /\.(jpg|png|svg)$/, loader: 'raw-loader' }
        ]
      },

      resolve: {
        extensions: ['.js', '.ts'],
        modules: [
          wallaby.projectCacheDir,
          ...(projects.length ? projects.filter(project => project.root)
            .map(project => path.join(wallaby.projectCacheDir, project.root)) : []),
          ...(projects.length ? projects.filter(project => project.sourceRoot)
            .map(project => path.join(wallaby.projectCacheDir,project.sourceRoot)) : []),
          'node_modules'
        ],
        alias: libraries.reduce((result, project) => {
          const alias =  project.name.replace(/([a-zA-Z])(?=[A-Z])/g, '$1-').toLowerCase();
          result[alias] = path.join(wallaby.projectCacheDir, project.sourceRoot, 'public-api');
          return result;
        }, {})
      }
    }),

    setup: function() {
      window.__moduleBundler.loadTests();
    }
  };
};
```

2. In the angular.json

```javascript
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "components": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "architect": {
        "build": {
...............
...........
```

In our project no src folder hence the "sourceRoot":""
Wallaby JS is configured successfully but when I start "Wallaby.js:Start", it is unable to find the test files and I am getting below error in the Wallaby.js Console

```
[Info] Started Wallaby.js Core v1.0.944
[Error] No files with testes found, check your tests list patterns.
[Info] Can't determine tests to run for the change
```

In the second scenario,
I have created one new angular project generated by angular cli and placed my test file in the root level like

      -MyTestAngularProject
        |- node_modules
        |- mytestcomponent
               -mytestcomponent.html
               -mytestcomponent.ts
               -mytestcomponent.spec.ts
       |- src
               -app
                   -app.component.html
                   -app.component.ts
                   -app.component.spec.ts
                    ........
      |-wallaby.js
      |-angular.json
      |-tsconfig.spec.json
      |-package.json
      |-karma.conf.js
      |-test.ts
 In the angular.json

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "components": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "architect": {
        "build": {
...............
...........
```

Even I specify my test file name in the "tests" list, my test files are not detected.

Please let me know if I missed some configuration to fix this issue

Regards,
Samir

**Comment by smcenlly** [comment]
Could you please provide us with a bit more information/responses to the questions below:

1. Do your tests run outside of Wallaby? If so, how are you running them? `ng test`?

2. Could you please try running Wallaby:
  a. Using [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) (no configuration file required) 
  b. If that does not work for you, please restart Wallaby and [explicitly select your configuration file to be used](https://wallabyjs.com/docs/intro/config.html#configuration-file)

3. Your Wallaby Diagnostics Report, **_for both (a) and (b)_**. To share the report:

- after starting Wallaby for your project;
- wait until it reports some results (in your case, `No files with testes found`);
- run the `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste the generated reports in your issue response (feel free to review and edit the report if required).

4. The full content of your `angular.json` file.

**Comment by samirsahoo** [comment]
Hi Simon,

Thanks for your response.

1. Yes, our test runs outside Wallaby and we run it by "ng test" command
2.  a) In automatic configuration, It shows same error "[Error] No files with testes found, check your tests list patterns."
     b) Same issue as in case a
3. I don't find  Wallaby "Copy Diagnostics Report" from VS Code. 
   But I enabled trace to get more debugging info

4. angular.json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "components": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "prefix": "",
      "schematics": {
          "@schematics/angular:component": {
                "style": "scss"
          }   
       },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/coponents",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
              "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot":true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "components:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "components:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "components:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "test.ts",
            "polyfills": "polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js"
             }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "components-e2e": {
       "root": "e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "components:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "components:serve:production"
            }
          }
        },
      "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
             "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }},
  "defaultProject": "components"
}

**Comment by ArtemGovorov** [comment]
> I don't find Wallaby "Copy Diagnostics Report" from VS Code.

Can you please wait until the `No files with testes found` message is displayed and then press `Cmd/Ctrl Shift +` (it should open a list on Wallaby commands only), and the `Copy Diagnostics Report` command should show up in the list.

**Comment by NikGovorov** [comment]
Hi @samirsahoo,

To get wallaby working on such custom Angular CLI project structure I would recommend to use the following configuration file:

```javascript
const folders = ['component1', 'component2']; // all custom folders...

const files = folders.flatMap((x) => [
  { pattern: `${x}/**/*.spec.ts`, ignore: true },
  { pattern: `${x}/**/*.+(ts|js)`, load: false },
  {
    pattern: `${x}/**/*.+(css|less|scss|sass|styl|html|json|svg)`,
    load: false,
    instrument: false
  },
]);

const tests = folders.map((x) => ({
  pattern: `${x}/**/*.spec.ts`,
  load: false
}));

module.exports = () => ({
  autoDetect: true,
  files: { override: (x) => x.concat(files) },
  tests: { override: (x) => x.concat(tests) }
});

```


Please let us know if it works for you.

**Comment by samirsahoo** [comment]
Hi @NikGovorov 

thanks for a quick solution.
I have tried it, but unfortunately it did not work. I am getting the same error.
Even, I tried with naming the specific test file, but it was unable to find.

Regards,
Samir

**Comment by smcenlly** [comment]
@samirsahoo - looking at your file structure, you may need to adjust the configuration suggested by @NikGovorov a little:

**wallaby.js**
```javascript
const folders = ['component1', 'component2']; // all custom folders...

const files = folders.flatMap((x) => [
  { pattern: `components/${x}/**/*.spec.ts`, ignore: true },
  { pattern: `components/${x}/**/*.+(ts|js)`, load: false },
  {
    pattern: `components/${x}/**/*.+(css|less|scss|sass|styl|html|json|svg)`,
    load: false,
    instrument: false
  }
]);

const tests = folders.map((x) => ({
  pattern: `components/${x}/**/*.spec.ts`,
  load: false
}));

module.exports = () => ({
  autoDetect: true,
  files: { override: (x) => x.concat(files) },
  tests: { override: (x) => x.concat(tests) }
});
```

After creating the `wallaby.js file`, you will need to [select this as your configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file), instead of using automatic configuration.

If you're still having problems after trying this, can you please provide us with a sample repo? It's a little difficult for us to fully understand what's going on without that.

**Comment by smcenlly** [comment]
@samirsahoo - just in case you didn't already try @NikGovorov config, please [try that first](https://github.com/wallabyjs/public/issues/2502#issuecomment-680787600) and [select the configuration as a configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file), instead of using automatic configuration before you try my suggestion.

**Comment by samirsahoo** [comment]
@smcenlly ,
thanks and I have selected configuration wallaby.js instead of automatic configuration and tried with different combinations with @NikGovorov config, but it did not work.
I am trying to create sample similar repo and share with you.

**Comment by samirsahoo** [comment]
Hi @smcenlly 
Attached the sample repository as attachment "components.zip".

Steps to reproduce the issue.

1. Unzip components.zip
2. npm install
3. ng test (to confirm test is working)
4. Select configuration as wallaby.js
5. ‍Wallaby.js : Start command shows below error in the console
    [Info]  Started Wallaby.js Core v1.0.946
    [Error] No files with tests found, check your tests list patterns. 
    [Info]  Can't determine tests to run for the change.
6. Attached Diagnostics Report. 
[DiagnosticsReport.txt](https://github.com/wallabyjs/public/files/5137158/DiagnosticsReport.txt)

[components.zip](https://github.com/wallabyjs/public/files/5137078/components.zip)

**Comment by smcenlly** [comment]
The configuration that @NikGovorov suggested is working for us. Can you please try changing your Wallaby configuration as shown below? Please make sure that you select the wallaby.js configuration file using the VS Code command `Wallaby.js: Select Configuration`.

**wallaby.js**
```javascript
const folders = ['component1']; // all custom folders...

const files = folders.flatMap((x) => [
  { pattern: `${x}/**/*.spec.ts`, ignore: true },
  { pattern: `${x}/**/*.+(ts|js)`, load: false },
  {
    pattern: `${x}/**/*.+(css|less|scss|sass|styl|html|json|svg)`,
    load: false,
    instrument: false
  }
]);

const tests = folders.map((x) => ({
  pattern: `${x}/**/*.spec.ts`,
  load: false
}));

module.exports = () => ({
  autoDetect: true,
  files: { override: (x) => x.concat(files) },
  tests: { override: (x) => x.concat(tests) }
});
```

![2502](https://user-images.githubusercontent.com/2074089/91500831-99a52000-e907-11ea-9346-9764377adfb2.gif)

**Comment by samirsahoo** [comment]
Hi Simon,

With the given wallaby.js configuration, it is working fine  :)
So, I have to remove the "components" from the pattern.

Many thanks for the support to resolve my issue.

Regards,
Samir
