### ISSUE TITLE
Angular Ivy not being used when running Wallaby after Angular 9 upgrade

### ISSUE THREAD

**Issue by vandammeb** [wallabyjs/public#2504]
### Issue description or question

Since we upgrade to angular 9 with ivy, we've been experiencing issues that seem related to Ivy not being used when wallaby is running. (Error: No component factory found for DatePickerComponent. Did you add it to @NgModule.entryComponents?)
We're using a configuration file, since autoconfiguration does not seem to work). Are there any specific changes needed to our configuration file to get this to work?

### Wallaby diagnostics report

[wallabydiagnostics.txt](https://github.com/wallabyjs/public/files/5129741/wallabydiagnostics.txt)

**Comment by ArtemGovorov** [comment]
> since autoconfiguration does not seem to work

Can you please attach your Wallaby diagnostics report for autoconfig run?

**Comment by vandammeb** [comment]
Sure, this is the one after updating to the latest wallaby version. Sometimes it fails on asset resolution and sometimes the process crashes when running out of memory.
[wallabydiagnostics.txt](https://github.com/wallabyjs/public/files/5134694/wallabydiagnostics.txt)

**Comment by ArtemGovorov** [comment]
@vandammeb Looks like the report you've attached in your second post is not from the latest Wallaby version (looks like your license had expired, so Angular 9 may be not supported in your expired version), and also the report is not for autoconfiguration (it is for your config file). 

Can you please do the following:
- update to the latest Wallaby version by getting the trial license at https://wallabyjs.com/download/, apply the license (`Help - Wallaby.js - Manage Licence`) and restart your IDE,
- start Wallaby using autoconfiguration:

![](https://wallabyjs.com/assets/img/jb_select_config.gif)

- run Copy Diagnostics Report command (`Help - Wallaby.js - Copy Diagnostics Report`).

**Comment by vandammeb** [comment]
@ArtemGovorov that's weird, I'm using the latest wallaby version though 

![image](https://user-images.githubusercontent.com/1032765/91411607-dbbb5c80-e848-11ea-91d3-bea536b2b9f4.png)

I'm running wallaby with autoconfig as well: 
![image](https://user-images.githubusercontent.com/1032765/91411717-03122980-e849-11ea-9891-3bf3dcdb85f6.png)

and my license is valid till april 2021... 

I'll remove and reinstall the plugin to see if that helps

**Comment by vandammeb** [comment]
@ArtemGovorov reinstalled plugin, doublechecked license and re-exported the diagnostics report:

[diagnostics.txt](https://github.com/wallabyjs/public/files/5134831/diagnostics.txt)

**Comment by NikGovorov** [comment]
Hi @vandammeb,

Does `ng test` work for the project?

From the diagnostics report that you attached I can see that `src/theme/vdw.scss:3787:17` references a path that does not exist:

```css
.mat-select-arrow-wrapper::after {
  content: url("../../assets/icons/navigation/arrowdown.svg");
}
```

If the icon is supposed to be in `assets` then the path should be:

```css
.mat-select-arrow-wrapper::after {
  content: url("../assets/icons/navigation/arrowdown.svg");
}
```

**Comment by vandammeb** [comment]
Hey @NikGovorov,

Yes, running the tests with Karma as a testrunner works fine, I fixed those paths and re-ran wallaby to run into the JS heap running out memory (was unable to export the diagnostics report in this case)

`wallaby.js started
core v1.0.946
Angular CLI automatic configuration: Wallaby.js cannot use /Users/bert/Projects/vdw-texconnect-webapp/src/test.unit.ts file, the standard test bed initialization code will be used instead. Please let us know if this is an issue for you at https:/github.com/wallabyjs/public/issues.

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
<--- Last few GCs --->

[67054:0x102808000]   153804 ms: Scavenge 1285.5 (1422.6) -> 1284.9 (1423.6) MB, 3.1 / 0.0 ms  (average mu = 0.379, current mu = 0.390) allocation failure 
[67054:0x102808000]   153809 ms: Scavenge 1285.6 (1423.6) -> 1285.1 (1424.1) MB, 3.8 / 0.0 ms  (average mu = 0.379, current mu = 0.390) allocation failure 
[67054:0x102808000]   153814 ms: Scavenge 1285.9 (1424.1) -> 1285.4 (1424.6) MB, 3.7 / 0.0 ms  (average mu = 0.379, current mu = 0.390) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x29905b95be3d]
Security context: 0x1d2dad91e6e9 <JSObject>
    1: DoJoin(aka DoJoin) [0x1d2dad905e91] [native array.js:~87] [pc=0x29905dec21c9](this=0x1d2d2ad826f1 <undefined>,l=0x1d2dc583c491 <JSArray[14]>,m=14,A=0x1d2d2ad828c9 <true>,w=0x1d2d411b2a81 <String[1]: />,v=0x1d2d2ad829a1 <false>)
    2: Join(aka Join) [0x1d2dad905ee1] [native array.js:~112] [pc=0x29905bd7e178](this=0x1d2d2ad826f1 <undefined>,l=0x1d2dc58...

 1: 0x10003cf99 node::Abort() [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 2: 0x10003d1a3 node::OnFatalError(char const*, char const*) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 3: 0x1001b7835 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 4: 0x100585682 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 5: 0x100588155 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 6: 0x100583fff v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 7: 0x1005821d4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 8: 0x10058ea6c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
 9: 0x10058eaef v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
10: 0x100560974 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
11: 0x10083a40d v8::internal::Runtime_StringBuilderJoin(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/bert/.nvm/versions/node/v10.16.0/bin/node]
12: 0x29905b95be3d 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

**Comment by NikGovorov** [comment]
Could you please add the following section to your package.json, start wallaby and share the content of `Wallaby Console`?

``` json
"wallaby: {
  "trace": true
}
```

**Comment by vandammeb** [comment]
@NikGovorov here you go (had to concat the output of 2 runs though)

[wallabyconsoleoutput.txt](https://github.com/wallabyjs/public/files/5142484/wallabyconsoleoutput.txt)

**Comment by NikGovorov** [comment]
@vandammeb thanks!

Could you please set `NODE_OPTIONS=--max_old_space_size=8192` global environment variable, restart Webstorm, start auto configuration and see if it fixes the issue with auto config?

`NODE_OPTIONS` is an environment variable that defines default arguments for all node processes on your system. To set it on macOS you may use the following command `launchctl setenv NODE_OPTIONS --max_old_space_size=8192`, then restart all instances of Webstorm and run Wallaby.js Run Configuration again.

**Comment by vandammeb** [comment]
@NikGovorov increasing the max_old_space_size does the trick for autoconfiguration 👍 . I need to excluded certain files from being picked up by wallaby though (our contract and ui tests). Is there a way to do that?

Manual config file extract:

`const specPattern = '/**/*spec.ts';
  const pactPattern = '/**/*pact.spec.ts';
  const e2ePattern = '/**/*e2e-spec.ts';`

...

`     tests: [
      ...projects.map((project) => ({
        pattern: project.sourceRoot + specPattern,
        load: false
      })),
      ...projects.map((project) => ({
        pattern: project.sourceRoot + e2ePattern,
        ignore: true
      })),
      ...projects.map((project) => ({
        pattern: project.sourceRoot + pactPattern,
        ignore: true
      }))
    ],`

**Comment by vandammeb** [comment]
@NikGovorov never mind the above, as I was reading the docs I noticed autoconfig stuff can be overridden :-) 👍 

Adding the same patterns to the wallaby section in package.json did the trick

`"wallaby": {
    "autoDetect": true,
    "trace": true,
    "tests": [
      {
        "pattern": "src/**/*spec.ts",
        "load": false
      },
      {
        "pattern": "src/**/*pact.spec.ts",
        "ignore": true
      },
      {
        "pattern": "src/**/*e2e.spec.ts",
        "ignore": true
      }
    ]
  }`

Thanks for your help!

**Comment by vandammeb** [comment]
@NikGovorov I've only just noticed that although tests run fine with Wallaby now, they are broken when running with Karma due to the change of paths references to those assets in the scss. Any ideas?

**Comment by NikGovorov** [comment]
@vandammeb, could you please provide us with your `karma.conf.js` file  content?

**Comment by vandammeb** [comment]
@NikGovorov sure:

`// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

const path = require('path');

const puppeteer = require('puppeteer');
process.env.CHROME_BIN = puppeteer.executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['parallel', 'jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-mocha-reporter'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('karma-sonarqube-unit-reporter'),
      require('karma-spec-reporter'),
      require('karma-parallel'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    files: [
      {pattern: './src/test.unit.ts', watched: false},
      {pattern: './node_modules/@angular/material/prebuilt-themes/indigo-pink.css', included: true, watched: true},
      'node_modules/cookieconsent/build/cookieconsent.min.js',
      'node_modules/cookieconsent/build/cookieconsent.min.css'
    ],
    coverageIstanbulReporter: {
      dir: path.join(__dirname, 'reports/coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    sonarQubeUnitReporter: {
      sonarQubeVersion: 'LATEST',
      outputFile: 'reports/ut_report.xml',
      overrideTestDescription: true,
      testFilePattern: '.spec.ts',
      useBrowserName: false
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['mocha', 'coverage-istanbul', 'sonarqubeUnit', 'spec'],
    mochaReporter: {
      ignoreSkipped: true
    },
    parallelOptions: {
      executors: 2,
      aggregatedReporterTest: '/coverage|istanbul/'
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['ChromeHeadlessNoSandboxNoSecurity'],
    singleRun: true,
    restartOnFileChange: true,
    customLaunchers: {
      ChromeHeadlessNoSandboxNoSecurity: {
        base: 'ChromeHeadless',
        flags: [
          '--headless',
          '--no-sandbox',
          '--disable-web-security',
          '--disable-gpu',
          '--disable-translate',
          '--disable-extensions',
          '--js-flags=--max-old-space-size=4096',
          '--remote-debugging-port=9222'
        ]
      }
    }
  });
};
`

**Comment by vandammeb** [comment]
Hey @NikGovorov this is the error on ng test in the original project when wallaby tests run without a problem:
[karmatestrun.txt](https://github.com/wallabyjs/public/files/5173710/karmatestrun.txt)

In your sample project the same error occurs when running tests with wallaby and karma.

There is a difference is how the relative path is resolved in the original though, since there are several imports being used.
vdw.scss imports an index file which contains imports for cards and forms (2 the files where the relative paths are in)

![image](https://user-images.githubusercontent.com/1032765/92221416-bb6d4c80-ee9d-11ea-82ce-228cc75749e7.png)

Could the issue be related to that?

**Comment by vandammeb** [comment]
@NikGovorov works like a charm! Thanks for fixing this 👍
