### ISSUE TITLE
console.log redirection

### ISSUE THREAD

**Issue by deeperx** [wallabyjs/public#251]
Is there a way to get the console.log events for the running tests (logs from the non-test files)?

**Comment by ArtemGovorov** [comment]
If you'd like to see everything what's `console.log`-ed as a result or running some particular test (logged from this tests and *all* code that it invokes), you may invoke `Show line tests` command from that test:
![lr](https://cloud.githubusercontent.com/assets/979966/9711332/28802ef2-5586-11e5-8fa8-69c5412314bc.gif).

If you'd like to see everything from everywhere in one place, [it's not yet supported](https://github.com/wallabyjs/public/issues/79).

**Comment by deeperx** [comment]
Great, it would be great if it could write logs into wallaby panel too. Because, some logs are too long to view in the modal box. Also, it would be great to get everything get logged too.

**Comment by ArtemGovorov** [comment]
@deeperx Hmm, thanks, I haven't tried too long ones. Will have a look.

**Comment by ArtemGovorov** [comment]
BTW, as a workaround for now: wallaby does display all console logs for failing tests inside wallaby panel, so one way to quickly view logs for a test there is to break the test temporarily.
