### ISSUE TITLE
Coverage appears to differ by if you destructure a nullable React prop or not.

### ISSUE THREAD

**Issue by tobysmith568** [wallabyjs/public#2513]
Coverage appears to differ by if you destructure a nullable React prop or not.

Lines 15 and 16 show different coverage indicators even though they're using the same data in the same way. The only difference is that one of them is using a destructured prop and one is not.

I believe the coverage should be yellow/orange for both because there is only one test and it does not pass in a falsy value.

<img src="https://raw.githubusercontent.com/tobysmith568/Wallaby.JS-Repro/main/readme/wallaby-run.png">

Repro repo: [https://github.com/tobysmith568/Wallaby.JS-Repro](https://github.com/tobysmith568/Wallaby.JS-Repro)

Diagnostics Report: [https://github.com/tobysmith568/Wallaby.JS-Repro/blob/main/diagnostics-report.txt](https://github.com/tobysmith568/Wallaby.JS-Repro/blob/main/diagnostics-report.txt)

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue and sharing the sample repo. The issue is fixed and the fix is published in [the latest core version 1.0.956](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
