### ISSUE TITLE
Automatic configuration from subfolder gives and error 'can not find jest-cli'

### ISSUE THREAD

**Issue by rudavko** [wallabyjs/public#2524]
### Issue description or question
The following error is being thrown when you try to start Wallaby in automatic configuration mode, where node_modules are not in the root folder:
`‌[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. `

Here is the repo that reproduces the bug:
https://github.com/rudavko/wallaby-autoconfig-bug-reproduce

If you start Wallaby from the root it fails, but, if you launch VScode with the 'functions' folder as root via:
`code functions`
and then launch Wallaby, it works perfectly well.

Thanks.

**Comment by ArtemGovorov** [comment]
The behaviour is expected. Wallaby automatic configuration expects to be started in the folder where your `package.json` file is located. To start Wallaby for your repo's root,  you may run `Select Configuration` command and then select `Automatic Configuration <custom directory>`. Wallaby will remember the selection and will start Jest in that folder.

![vsc](https://user-images.githubusercontent.com/979966/94343957-3f5ec280-005f-11eb-817c-4c871e573137.gif)

**Comment by rudavko** [comment]
Huh, did not want to work for me when I selected the custom directory prior...

Thanks
