### ISSUE TITLE
 LICENSE ISSUE?: Automatic Angular CLI configuration error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by maccurt** [wallabyjs/public#2526]
I have a license that is expired for updates *** THIS MAY BE THE ISSUE ****

I got a brand new machine, installed angular 10 and created a new application. With Visual Studio Code I installed the extension for wallaby.  I pasted in my license, I get the message that my license free upgrade is expired

 I get the following errors

‌[Error] Automatic Angular CLI configuration error: Cannot convert undefined or null to object 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Cannot find compatible jest-cli module. 

jest-cli": "^26.4.2",
Wallaby.js - v1.0.784

I should have the latest of everything

**Comment by smcenlly** [comment]
We had some compatibility issues that prevented Wallaby running with Angular v10 in the last 6 months, so it is possible that the version supported by your license does not work with Angular v10.

You may [request a trial license](https://wallabyjs.com/download/#try-it-free) from our website to see if this works for you when using the latest version of Wallaby.

If you still have problems when using the latest version of Wallaby, could you please provide us with your Wallaby diagnostics report. The Wallaby Diagnostics Report is a simple JSON text report that contains some basic information about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

* start Wallaby in your project;
* wait until it reports some results (finishes running tests);
* run Copy Diagnostics Report command:
  * in VS Code, Atom, or Sublime editor execute Wallaby Copy Diagnostics Report command;
  * in JetBrains IDEs or VS use Wallaby Help | Wallaby.js | Copy Diagnostics Report menu item;
* paste generated report from your clipboard to a newly created issue (feel free to review and edit the report if required).

**Comment by maccurt** [comment]
I did get the trial license and that indeed did fix the issue, so I will upgrade my current license.
