### ISSUE TITLE
Wallaby doesn't start with the latest version of WebStorm 2020.3 EAP

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2527]
Error running 'Wallaby': 'void com.intellij.platform.templates.github.ZipUtil.unzipWithProgressSynchronously(com.intellij.openapi.project.Project, java.lang.String, java.io.File, java.io.File, boolean)'

**Comment by smcenlly** [comment]
This has been fixed. The fix is available in the latest version of Wallaby for IntelliJ, v1.0.198.

**Comment by Vetalb8** [comment]
the same for webstorm 
![Uploading image.png…]()

**Comment by ArtemGovorov** [comment]
@Vetalb8 Please uninstall the Wallaby extension from your editor and then download and install the latest version from [our website](https://download.wallabyjs.com/intellij).
