### ISSUE TITLE
JetBrains usage. Now what?

### ISSUE THREAD

**Issue by tinjaw** [wallabyjs/public#2528]
From my support case with JetBrains:

Chaim Krause Sep 25, 2020, 16:34 GMT+2 I have looked at the documentation for React apps, and Electron apps, but I cannot get my breakpoint to work with my project based on this template. https://github.com/electron-react-boilerplate/electron-react-boilerplate

Oksana Chumak (IntelliJ) Sep 29, 2020, 11:42 GMT+2 Hello, The general steps are the following: Start from package.json scripts start-renderer-dev, then start-main-debug. Create a Attach to Node.js/Chrome run configuration with the port number 9223. Then start it with debugging. Regards, Oksana WebStorm team

My question about is Wallaby.js is how I properly use Wallaby now that I have gotten my program running/debugging based on JetBrains help?

Best,
Chaim

**Comment by ArtemGovorov** [comment]
> My question about is Wallaby.js is how I properly use Wallaby

Please check out [this tutorial](https://wallabyjs.com/docs/intro/get-started-jetbrains.html) on how to use Wallaby in JetBrains IDEs. 

>  https://github.com/electron-react-boilerplate/electron-react-boilerplate

I'm not familiar with the template, but from briefly checking it - it looks like it is using Jest, so you may try starting [Wallaby automatic configuration](https://wallabyjs.com/docs/intro/config.html?editor=jb#jetbrains-ides) on the project to see if it works for you.

Let us know if you get stuck, we are happy to help.
