### ISSUE TITLE
OSS Project not working with OSS license

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#2529]
Hi, I've applied successfully for the OSS license.
Now wallaby fails to start with "Wallaby.js has been stopped because your project is not associated with a valid GitHub project.".
My project is https://github.com/KnisterPeter/tsdi

Any hint what I can do?

**Comment by smcenlly** [comment]
I tried your project and besides an error in your wallaby configuration, it seems to be working for me.

Can you please:
1. Update your Wallaby configuration to include the `trace` setting with a value of `true`.
2. Start Wallaby again
3. After receiving the message "Wallaby.js has been stopped because your project is not associated with a valid GitHub project.", please go to your Wallaby console and copy the contents and paste it into a reply to this issue.

**Comment by KnisterPeter** [comment]
@smcenlly Sure

Config:
```js
module.exports = function (wallaby) {
  return {
    trace: true,
    files: [
      'lib/**/*.ts',
      'tests/**/*.ts',
      '!tests/**/*-test.ts'
    ],
    tests: [
      'tests/**/*-test.ts'
    ],
    testFramework: 'mocha',
    env: {
      type: 'node'
    },
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        typescript: require('typescript'),
        module: 1, // commonjs
        emitDecoratorMetadata: true
      })
    }
  };
};
```
Log:

```
‍[Info]  2020-10-03T10:10:57.148Z extended-core Validating Open Source License
[Info]  2020-10-03T10:10:57.149Z extended-core Remotes:  [ 'https://github.com/KnisterPeter/tsdi/' ]
[Info]  2020-10-03T10:10:57.341Z project Wallaby Node version: v12.18.4
[Info]  2020-10-03T10:10:57.342Z project Wallaby config: /home/markusw/source/tsdi/wallaby.js
[Info]  Started Wallaby.js Core v1.0.969
[Info]  2020-10-03T10:10:57.371Z fs File added: lib/component.ts
[Info]  2020-10-03T10:10:57.372Z fs File added: lib/debug.ts
[Info]  2020-10-03T10:10:57.373Z fs File added: lib/destroy.ts
[Info]  2020-10-03T10:10:57.373Z fs File added: lib/external.ts
[Info]  2020-10-03T10:10:57.374Z fs File added: lib/factory.ts
[Info]  2020-10-03T10:10:57.374Z fs File added: lib/global-state.ts
[Info]  2020-10-03T10:10:57.374Z fs File added: lib/helper.ts
[Info]  2020-10-03T10:10:57.375Z fs File added: lib/index.ts
[Info]  2020-10-03T10:10:57.375Z fs File added: lib/initialize.ts
[Info]  2020-10-03T10:10:57.376Z fs File added: lib/inject.ts
[Info]  2020-10-03T10:10:57.376Z fs File added: lib/tsdi.ts
[Info]  2020-10-03T10:10:57.376Z fs File added: tests/cyclic1.ts
[Info]  2020-10-03T10:10:57.377Z fs File added: tests/cyclic2.ts
[Info]  2020-10-03T10:10:57.377Z fs File added: tests/dependency.ts
[Info]  2020-10-03T10:10:57.378Z fs File added: tests/eager1.ts
[Info]  2020-10-03T10:10:57.378Z fs File added: tests/eager2.ts
[Info]  2020-10-03T10:10:57.378Z fs File added: tests/index-test.ts
[Info]  2020-10-03T10:10:57.379Z fs File added: tests/mock-test.ts
[Info]  2020-10-03T10:10:57.380Z fs File added: tests/user.ts
[Info]  2020-10-03T10:10:57.384Z fs File added: tests/integration/cypress.ts
[Info]  2020-10-03T10:10:57.384Z fs File added: tests/integration/index.spec.ts
[Info]  2020-10-03T10:10:57.384Z fs File added: tests/integration/umd.ts
[Info]  2020-10-03T10:10:57.392Z extended-core Wallaby.js has been stopped because your project is not associated with a valid GitHub project (err:1014).
[Info]  2020-10-03T10:10:57.394Z project Stopping wallaby.js
[Info]  2020-10-03T10:10:57.394Z project Killing 0 spawned process(es)
[Info]  2020-10-03T10:10:57.394Z project Stopping test runner
[Info]  Wallaby.js stopped
```

**Comment by smcenlly** [comment]
Your error indicates that you have a nested git submodule or nested git repository. Currently the OSS license does not support this project structure but we have an open issue tracking this as a feature request: https://github.com/wallabyjs/public/issues/2521.

**Comment by KnisterPeter** [comment]
@smcenlly But I don't. It is a simple JavaScript project checked out directly.
I'll retest with a new clone later. And report back.

**Comment by KnisterPeter** [comment]
@smcenlly Indeed a fresh clone does work. I'll double checked that I have no `.git` folder outside of the failing instance, so I guess this is not the same as #2521. This migth be some other bug.

**Comment by KnisterPeter** [comment]
The question for me here is, if I should keep my 'old' check around that you can debug & inspect what is wrong or if its okay for you if I just throw it away.

**Comment by ArtemGovorov** [comment]
@KnisterPeter any chance you could delete `node_modules`, archive and attach your previously failing folder?

**Comment by KnisterPeter** [comment]
Sure :smiley:

**Comment by KnisterPeter** [comment]
@ArtemGovorov Its around 150MB (including the `.git` folder). Do you have place where I can upload? Github tells me that its too big

**Comment by ArtemGovorov** [comment]
@KnisterPeter 150MB without any node modules? Can you please double check that:
- `node_modules` have been deleted from the `./website` folder,
- `node_modules` have been deleted from the root repo folder,
and try archiving it again? If it's still too much, can you please check what folders/files are contributing to such a large archive size? When I clone the repo and archive it, it takes less than 1Mb for me.

Also, can you please check if you have a `.git` inside the `./website` folder in that "old" folder?

**Comment by KnisterPeter** [comment]
Whops, it was the `node_modules` inside `./website`. Now its fine.

[wallaby-failure-no-node_modules.tar.gz](https://github.com/wallabyjs/public/files/5326616/wallaby-failure-no-node_modules.tar.gz)

**Comment by ArtemGovorov** [comment]
Thanks. The issue is indeed related to https://github.com/wallabyjs/public/issues/2521, because there's a nested git repo located in `./website/build/tsdi-gh-pages/`.

**Comment by KnisterPeter** [comment]
I see. Thanks for the info. Therefore a new clone does work.
