### ISSUE TITLE
Show value in Webstorm doesn't work: Reopen #2530

### ISSUE THREAD

**Issue by i-have-no-name** [wallabyjs/public#2531]
### Issue description or question

Sorry, I reopen an issue. I remove all overrided props, but it doesn't help.
Trial version has the same opportunities as paid ?

**Comment by smcenlly** [comment]
Yes - the trial version works the same as a paid license.

Could you please provide your diagnostics report and a screenshot of your code where `Show Value` is not working?

**Comment by smcenlly** [comment]
Sorry - I had missed your previous issue. I will close this issue and reopen the previous issue where you replied.
