### ISSUE TITLE
"Bubble up" console.log calls to show up in UI from a custom logger?

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2536]
### Issue description or question

Hi.
In typescript, I have a custom logger type similar to 
```ts
export class Logger {
  private _useLogging = true;
  //Callback to not evaluate the string unless logging, but that maybe is a bit of overkill...
  public static logIt(msgCb: () => string) : void {
     if (this._useLogging) {
        console.log(msgCb());
    }
  }
}
```
In code I then, instead of console.log, use this logger:
```ts
something() : void {
  Logger.logIt(() => "Foo"); 
}
```
Is there a way for wallaby to "intercept" this console.log and, maybe via some annotation, know that when I use ```Logger.logIt(..)```, I want the console output to be written on the same line as I've would used console.log directly in method ```something()```?

Thanks.

**Comment by smcenlly** [comment]
We do not currently have a way of extending Wallaby to allow other functions to directly output inline messages like `console.log` does. We have an existing feature request that you may subscribe to for updates (https://github.com/wallabyjs/public/issues/165) but we do not have any immediate plans to support this use case.

We have a number of our own projects that have a similar logger class to what you have described and in our experience, which may be different to yours, we know that if you have a decent amount of logging in your application then the logger messages become extremely noisy and as a result make Wallaby output very difficult to comprehend and process. For that reason, in our tests, we mock our own logger calls with a no-op (e.g. `_useLogging` is always false when Wallaby is running) and use inline `console.log` when we really want to view/monitor a value. You're probably already aware that there are other ways to log runtime values (e.g. `Show Value` command, live comments, etc.); if not, you may like to check out the [advanced logging](https://wallabyjs.com/docs/intro/advanced-logging.html) section of our docs.
