### ISSUE TITLE
Unnecessarily hard to debug errors. Errors are truncated, impossible to see full message. No line numbers.

### ISSUE THREAD

**Issue by samdesota** [wallabyjs/public#2541]
### Issue description or question

Wallaby test runner in VSCode has changed my dev workflow for the better on nodejs tools, but it's very confusing to me why it's so hard to debug errors, it's far easier to find out where an error is coming from when just running with `jest`

First off, when an error occurs, there's no stack trace, no line numbers, just a truncated error message. The only way to find out where it's coming from quickly is to use `go to definition` repeatedly until you find the source of the bug, but why can't I just see the full error message instead of the truncated one? I recently was debugging a library with very long error messages, and every time an error occurred, just to see the full error message (not even the stack trace) I had to write:

```
try {
 myOperation
} catch (e) {
  e //?
}
```

Then I could hover over `//?` to see the full error message. Love this tool, but hiding the error message like this must be a bug. Ideally, when an error occurs, there could be a link that let's me go to the deepest location in my source code where the error occurred, instead of hiding this information..

**Comment by ArtemGovorov** [comment]
Wallaby displays rich and interactive details for errors in the [Wallaby.js Tests output channel in VS Code](https://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests).
