### ISSUE TITLE
Lerna + CRA + Ts. My setupTest.ts is not being readed.

### ISSUE THREAD

**Issue by DarioG** [wallabyjs/public#2542]
### When trying to configure Wallaby in VSCode with my ts + CRA app, the setupTest.ts file is not being read, therefore my libraries are not initialized.

I have a [repo](https://github.com/DarioG/lerna-typescript-CRA-enzyme) where I use Typescript + CRA + jest as setup. I managed to run wallaby on it, with this [configuration file](https://github.com/DarioG/lerna-typescript-CRA-enzyme/blob/master/wallaby.js). 
```
module.exports = function (wallaby) {
  var path = require("path");
  process.env.BABEL_ENV = "test";
  process.env.NODE_ENV = "test";
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, "node_modules") +
    path.delimiter +
    path.join(__dirname, "node_modules/react-scripts/node_modules");
  require("module").Module._initPaths();

  const vesselPath = path.join(
    wallaby.localProjectDir,
    "packages",
    "my-project"
  );
  const vesselTsconfig = require(path.join(vesselPath, "tsconfig"))
    .compilerOptions;
  delete vesselTsconfig.isolatedModules;
  delete vesselTsconfig.noEmit;

  return {
    files: [
      "packages/**/src/*.+(ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)",
      "!packages/**/node_modules/**",
      "!packages/**/*.test.ts*",
    ],
    tests: ["packages/**/*.test.ts*", "!packages/**/node_modules/**"],
    env: {
      type: "node",
      runner: "node",
    },

    compilers: {
      "**/*.ts?(x)": wallaby.compilers.typeScript(vesselTsconfig),
    },

    preprocessors: {
      "**/*.js?(x)": (file) =>
        require("@babel/core").transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [
            require("babel-preset-jest"),
            require("babel-preset-react-app"),
          ],
        }),
    },

    setup: (wallaby) => {
      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(
        (p) => require.resolve("react-scripts/" + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        (k) =>
          ~k.indexOf("^.+\\.(js|jsx") && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: "jest",
  };
};
```
However, I tried to add Enzyme, and when I enable it with my [setupTest.ts](https://github.com/DarioG/lerna-typescript-CRA-enzyme/blob/master/packages/my-project/src/setupTests.ts), 

```
// jest-dom adds custom jest matchers for asserting on DOM nodes.
// allows you to do things like:
// expect(element).toHaveTextContent(/react/i)
// learn more: https://github.com/testing-library/jest-dom
import '@testing-library/jest-dom/extend-expect';


/* eslint-disable import/no-extraneous-dependencies */
import Enzyme from 'enzyme';
import ReactSixteenAdapter from 'enzyme-adapter-react-16';
Enzyme.configure({ adapter: new ReactSixteenAdapter() });

```
I get the following error:

![image](https://user-images.githubusercontent.com/1649042/96416225-06de7e80-11f0-11eb-9f85-2f3655e70d8e.png)

What am I doing wrong?

Thank you in advance :)

**Comment by ArtemGovorov** [comment]
You don't need a configuration file for your project and may use [automatic Jest config](https://wallabyjs.com/docs/intro/config.html#automatic-configuration):

![vsc](https://user-images.githubusercontent.com/979966/96418642-70817b80-1236-11eb-84ad-176d3ce745e2.gif)

If you would like to keep your config file, here's the change you need to make:

```diff
    setup: (wallaby) => {
      const jestConfig = require("react-scripts/scripts/utils/createJestConfig")(
        (p) => require.resolve("react-scripts/" + p)
      );
      Object.keys(jestConfig.transform || {}).forEach(
        (k) =>
          ~k.indexOf("^.+\\.(js|jsx") && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
+     jestConfig.setupFilesAfterEnv.push('<rootDir>/packages/my-project/src/setupTests.js');
      wallaby.testFramework.configure(jestConfig);
    },
```

**Comment by DarioG** [comment]
Hi,

Thank you for the quick response. In case I keep my config file, what would happen when i have 2 or more packages? maybe those packages have different `setupTest.ts` files, right? how should that be handled?

Thank you!

**Comment by ArtemGovorov** [comment]
If you have 2 or more packages, then your config may already be broken (because other packages may not use `react-scripts` for example, as your config implies).

The solution is not Wallaby specific and is the same for how you are planning to run your tests outside of Wallaby.

Option 1: If you are planning to run Jest tests on each package at a time (with or without Wallaby), then you may create multiple Wallaby configs, one for each project, and run them separately. The same way as you would run tests separately for each project without Wallaby with Jest CLI, or with Wallaby autoconfig for a selected package folder.

Option 2: If you are planning to run Jest tests in all packages on the monorepo atbthe same time, then you need to make the `npx jest` command to work in your monorepo's root. Once you have configured Jest to run all of your tests from your repo's root (ie. `npx jest` from your repo's root is working correctly), then Wallaby autoconfig for the monorepo's root should just work without any additional configs.

Hope it makes sense.
