### ISSUE TITLE
Sequelize Log

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#2546]
### Issue description or question
How can i get the logs of sql statements being generated by sequelize in the wallaby logs?

**Comment by smcenlly** [comment]
Wallaby displays console.log statements from 3rd party libraries in the `Wallaby.js console` window:

![image](https://user-images.githubusercontent.com/2074089/96939970-d2313680-1511-11eb-92ed-806ead990303.png)

If you wanted to display these inline using Wallaby's live value display then you would have to replace Sequelize's logging mechanism with your own. For example, something like this:

![image](https://user-images.githubusercontent.com/2074089/96940174-58e61380-1512-11eb-965f-ea20cd250202.png)
