### ISSUE TITLE
Wallaby/vscode failing to start

### ISSUE THREAD

**Issue by shufton** [wallabyjs/public#2547]
### Wallaby/vscode failing to start

vscode version 1.50.1 user setup.
Wallabyjs extension version 1.0.248

Whenever I start Vscode, and try to start wallaby, I get the notification

"Wallaby.js is updating and will be started automatically when the update is complete."

All wallaby commands cause the same notification.

Even after a while, this is all I get when I try to start.  I have uninstalled the extension and re-installed, but is still the same. The target project is typescript, not sure what else you need, let me know if you require other logs etc.

**Comment by ArtemGovorov** [comment]
Try this:
- uninstall Wallaby extension,
-close VS Code,
- delete all  `~/.vscode/extensions/wallabyjs.wallaby-vscode-*` folders,
- install the extension and start Wallaby.


if it doesn't help, please
- send your license details to hello@wallabyjs.com,
- send/attach console tab logs from VS Code dev tools console (`Toggle Developer Tools` command in VS Code) when you Wallaby is failing to start.

**Comment by shufton** [comment]
Info sent, assuming it gets through corp boundary, let me know if you can't find and I will try another way.

**Comment by shufton** [comment]
I had a chance to look at the log myself over lunch, and I think some corporate firewall MITM certificate interception stuff is causing the problem, when I set NODE_TLS_REJECT_UNAUTHORIZED=0 and start vscode in that session, I am able to download the updated package. The issue is technically fixed for me, please close if you think it should be.
