### ISSUE TITLE
comparison failure in `unexpected-sinon`

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#255]
I am using `unexpected` with `unexpected-sinon` plugin

This assertion fails:

```
expect(my.args, 'to satisfy', [[...],[..]]
```

Show assertion data diff:
contents are identical
Both `Expected` and `Actual` are empty

**Comment by ArtemGovorov** [comment]
Could you please paste some code that fails so I could reproduce the issue? I have tried the example from [the plugin page](http://unexpected.js.org/unexpected-sinon/) and it works for me.

**Comment by ArtemGovorov** [comment]
Let me know if you have some sample to reproduce the issue, happy to re-open it.
