### ISSUE TITLE
Treeview node expansion is not kept when using test text filter

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2552]
### Issue description or question
1. Ensure a node is expanded in the wallaby app without any text filter.
1. Change a test name within the expanded node and notice it is updated while kept expanded.
1. Filter the view to only show the node and ensure it is expanded.
1. Change a test name again and notice the expanded node is now collapsed.

**Expected Behavior**
On step 4, node to be kept expanded like in step 2.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. The fix is released with Wallaby App v1.0.76.
