### ISSUE TITLE
Node Version Mismatch when using Webpack

### ISSUE THREAD

**Issue by jljorgenson18** [wallabyjs/public#2557]
### Issue description or question

We are currently using Node v12 in our project and using Wallaby with a webpack post processor. We have node-sass as a dependency and the underlying binding ends up being installed with Node v12 in mind. However, Wallaby seems to use Node v14 when starting up and we get this error

```
[Error] ./src/apps/peso/components/menus/menus.scss?module (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-0-1!./node_modules/postcss-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js??ref--9-oneOf-0-3!wallaby-pre-loader!./src/apps/peso/components/menus/menus.scss?module) 
[Error] Module build failed (from ./node_modules/sass-loader/dist/cjs.js): 
[Error] Error: Missing binding ./node_modules/node-sass/vendor/darwin-x64-83/binding.node 
[Error] Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 14.x 
[Error]  
[Error] Found bindings for the following environments: 
[Error]   - OS X 64-bit with Node.js 12.x 
[Error]  
[Error] This usually happens because your environment has changed since running `npm install`. 
[Error] Run `npm rebuild node-sass` to download the binding for your current environment. 
[Error]     at module.exports (./node_modules/node-sass/lib/binding.js:15:13) 
[Error]     at Object.<anonymous> (./node_modules/node-sass/lib/index.js:14:35) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1085:30) 
```

Is there any way to have Wallaby attempt to hook into what is in the nvmrc file or allow us to specify the Node version?

**Comment by ArtemGovorov** [comment]
Wallaby is using your system default node version by default, but yes, you may specify any desired node version as [described in our docs](https://wallabyjs.com/docs/intro/install.html?editor=vsc):

If you have multiple versions of node.js installed or don’t have node path in your PATH, and you would like wallaby.js to run with a specific version (for example if you are using nvm), you may use wallaby.node setting in your settings.json file to specify the full path to node.js executable file, for example:

```
// Place your settings in this file to overwrite the default settings
{
    ...
    "wallaby.node": "/Users/user/.nvm/versions/node/v4.1.1/bin/node"
}
```

**Comment by jljorgenson18** [comment]
Got it, thank you! I was looking at the wrong spot in the docs
