### ISSUE TITLE
Feature Request: VSC set configuration dir via context menu

### ISSUE THREAD

**Issue by gkTim** [wallabyjs/public#2563]
### Issue description or question

It would be awesome when we can set the configuration dir via the context menu auf the VSC Sidebar (like "Add to exclusive test run").

Currently it is only possible via quick actions which opens then a file picker.
The other way would be much quicker.

I do it very ofter in nrwl workspaces to run test for specific libs and not the whole monorepo.

**Comment by smcenlly** [comment]
Thanks for the feature request, nice idea. This has been implemented and is available in the latest version of Wallaby for VS Code, `v1.0.249`.

To select a different sub-folder within your project for automatic configuration you may now select the folder in the **Explorer** tree and use the `Wallaby.js: Configure and Start` context menu item.
