### ISSUE TITLE
Angular 11 automatic configuration fails

### ISSUE THREAD

**Issue by milanosie** [wallabyjs/public#2566]
### Issue description or question

Hi, after updating to Angular 11 I can't seem to get the automatic configuration to work. 
It's looking for a module that (no longer?) exists.

Automatic Angular CLI configuration error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs'
Require stack:
- ./node_modules/@angular/cli/commands/test-impl.js/wallaby.js

**Comment by laurent67100** [comment]
I have the same issue with angular 11

**Comment by smcenlly** [comment]
Thanks for reporting the problem. The latest version of Wallaby, `v1.0.989` now supports Angular v11 with automatic configuration.
