### ISSUE TITLE
IntelliJ dialogue popup show blank when using wallaby plugin in Ubuntu (15.04)

### ISSUE THREAD

**Issue by TJNK** [wallabyjs/public#257]
When the plugin is enabled intelliJ dialogue popups show blank (as seen in screenshot). when disabling the plugin the dialogue popup's work properly again. Checked with IDEA and they said no other related issues are known.

![rendering_blank](https://cloud.githubusercontent.com/assets/13555258/9810654/8eed3fba-5872-11e5-86a0-9e56ac97b4e3.png)

**Comment by ArtemGovorov** [comment]
What IDEA version are you using?

**Comment by ArtemGovorov** [comment]
Can't reproduce on Ubuntu 15.04 and IDEA 141.x, 142.x.

**Comment by TJNK** [comment]
IntelliJ 14.1.4; had issues for a while; but with core 105 the rendering is better (somehow; less hickups)

**Comment by ArtemGovorov** [comment]
Ok, thanks, good to know. Overall, it doesn't look like wallaby.js issue, I'm not sure how it can affect it. Anyway, let me know if it gets worse and the only thing that fixes it is wallaby.js uninstalling.
