### ISSUE TITLE
Aggressive license check over same network

### ISSUE THREAD

**Issue by veksen** [wallabyjs/public#2570]
### Issue description or question

I'm using Wallaby on 2 computers, at my desk using a desktop computer, and will sometimes sit on the couch on my laptop to continue the same work. This causes wallaby to prompt me that the license is already used on the network. I understand the implications from your part and wanting to avoid shared licenses, but not sure how to proceed with the license on multiple computers that I own.

**Comment by veksen** [comment]
It seems to go away once the test runner is stopped, am I correct?

**Comment by ArtemGovorov** [comment]
> It seems to go away once the test runner is stopped, am I correct?

Yes, you are correct.

Please send us an email to hello@wallabyjs.com referencing this issue and we'll sort it out for you.
