### ISSUE TITLE
Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

### ISSUE THREAD

**Issue by ProgrammerSM** [wallabyjs/public#2573]
Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

I have been using wallaby for quite a number of months, but as of today I keep getting the error listed above. I am currently on v1.0.991. I have not needed to use a wallaby config up to this point, so I'm not sure if there was a recent change that requires one or not.

I have tried deleting my modules and package-lock file and reinstalling - did not work
I tried updating - did not work

Any help would be appreciated

‍[Info]  Started Wallaby.js Core v1.0.991
[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.

**Comment by ArtemGovorov** [comment]
@ProgrammerSM I'm assuming you've figured out what was causing the issue because you've closed the ticket. Mind sharing what was the problem?
