### ISSUE TITLE
No valid wallaby.js license found

### ISSUE THREAD

**Issue by jasonkuhrt** [wallabyjs/public#2574]
### Issue description or question

I signed up for the oss license (thanks!) but when I enter my email (jasonkuhrt@me.com) it is not being recognized.

> No valid Wallaby.js license found, starting in limited-trial mode. If you would like to try Wallaby without any limitations, please request an extended trial license. If you have already purchased the license, please activate it. If you would like to purchase a license, please visit our website.

I had previously purchased the Quokka personal license, not sure that could/should affect anything here.

### Wallaby diagnostics report

(I didn't do this yet)

**Comment by ArtemGovorov** [comment]
Can you please try this:
- close your editor,
- delete `~/.wallaby` folder,
- start your editor,
- start Wallaby and enter your email when asked for your license key.

This should help.
