### ISSUE TITLE
Wallaby fails to show update notifications in IntelliJ

### ISSUE THREAD

**Issue by TJNK** [wallabyjs/public#258]
Wallaby fails to show up in the Notification Settings page in IntelliJ; only after reinstalling the licence and updates appear in the list.

**Comment by ArtemGovorov** [comment]
So it works now after the re-install? What version of wallaby did you have and what's your IDE version?

**Comment by TJNK** [comment]
yes works after reinstall; IntelliJ 14.1.4; wallaby version 95(?)

**Comment by ArtemGovorov** [comment]
Cool, not sure what exactly corrupted the previous installation though. Let me know if happens again.
