### ISSUE TITLE
Error when running wallaby

### ISSUE THREAD

**Issue by LoreVdl** [wallabyjs/public#2583]
I am trying to run Wallabyjs in IntelliJ, but am getting a fatal error.

Wallaby console output:
`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
` 1: 0x10096dd2e node::Abort() (.cold.1) [/usr/local/opt/node@10/bin/node]
 2: 0x10003b906 node_module_register [/usr/local/opt/node@10/bin/node]
 3: 0x10003bac7 node::OnFatalError(char const*, char const*) [/usr/local/opt/node@10/bin/node]
 4: 0x100178fd3 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/opt/node@10/bin/node]
 5: 0x100178f75 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/opt/node@10/bin/node]
 6: 0x10042d4e8 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/opt/node@10/bin/node]
 7: 0x100433ca4 v8::internal::Heap::SetUp() [/usr/local/opt/node@10/bin/node]
 8: 0x10041429b v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/local/opt/node@10/bin/node]
 9: 0x100415dba v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/opt/node@10/bin/node]
10: 0x1004ef51a v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/opt/node@10/bin/node]
11: 0x10018d68e v8::String::Utf8Length() const [/usr/local/opt/node@10/bin/node]
12: 0x10004c5de node::Buffer::(anonymous namespace)::ByteLengthUtf8(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/opt/node@10/bin/node]
13: 0x1001dd409 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/opt/node@10/bin/node]
14: 0x1001dca0d v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/opt/node@10/bin/node]
15: 0x1001dc1c9 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/opt/node@10/bin/node]
16: 0x38ab57e5be3d`

**Comment by ArtemGovorov** [comment]
Can you please:
- share your Wallaby config,
- set `NODE_OPTIONS=--max_old_space_size=8192` global environment variable, restart your IDE, start Wallaby and see if it fixes the issue with auto config?

`NODE_OPTIONS` is an environment variable that defines default arguments for all node processes on your system. To set it on macOS you may use the following command `launchctl setenv NODE_OPTIONS --max_old_space_size=8192`, then restart all instances of IntelliJ and run Wallaby.js Run Configuration again.

**Comment by LoreVdl** [comment]
Setting the NODE_OPTIONS=--max_old_space_size=8192 worked. Thank you for the quick solution!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
