### ISSUE TITLE
Does not pick up jest setting for coveragePathIgnorePatterns from package.json ?

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2585]
### Issue description or question

I use CRA with typescript and want to exclude interface TS files (e.g. `IFoo.ts`) to not be included in coverage since they always show up as uncovered.
When I run `npm test -- --coverage --watchAll=false` it works as expected with below setting in `package.json`, but Wallaby seems to ignore it (it displays 0% coverage for ts interface files).
From *package.json*:
```
  "jest": {
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/src/.*/I.*\\.ts"
    ]
  },

```
From *wallaby.js*:
```
module.exports = () => ({
    autoDetect: true,
    tests: ['src/__tests__/**/*.test.ts?(x)'],

    reportConsoleErrorAsError: true,
});
```

According to [docs](https://wallabyjs.com/docs/integration/jest.html) wallaby should pick up the jest config from package.json automatically, right?

Thanks.

**Comment by smcenlly** [comment]
Thanks for reporting your problem. Wallaby was considering the [`collectCoverageFrom`](https://jestjs.io/docs/en/configuration.html#collectcoveragefrom-array) setting but not the [`coveragePathIgnorePatterns`](https://jestjs.io/docs/en/configuration.html#coveragepathignorepatterns-arraystring) setting.

Wallaby now uses both settings. Once you update to the latest version of Wallaby core, `v1.0.996`.
