### ISSUE TITLE
File has invalid syntax (static delete =)

### ISSUE THREAD

**Issue by amercier** [wallabyjs/public#2586]
### Issue description or question

Considering this code (I'm unfortunately unable to provide actual code as it's private):

`src/myclass.js`
```js
class MyClass {
  static delete = 'foo'
}
```

`wallaby.js`
```js
const babelConfig = require('./babel.config.js')

module.exports = (wallaby) => ({
  // ...
  compilers: {
    '**/*.js': wallaby.compilers.babel({ ...babelConfig.env.test }),
  }
})
```

`babel.config.js`
```
module.exports = {
  env: {
    test: {
      plugins: ['babel-plugin-dynamic-import-node'],
      presets: [
        [
          '@babel/preset-env',
          {
            targets: {
              node: 'current',
            },
          },
        ],
        '@vue/babel-preset-jsx',
      ],
    },
  },
}
```

### Expected behavior

Wallaby should run fine.

### Actual behavior

```
‌[Error] Test run failure: file src/myclass.js has invalid syntax 
```

### Workaround

`src/myclass.js`
```js
class MyClass {
  // ...
}

MyClass['delete'] = 'foo'
```

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest Wallaby Core v1.0.997](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
