### ISSUE TITLE
Where is wallaby-app located? (following offline routine for upgrade with IntelliJ)

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2588]
### Issue description or question
I am trying to upgrade my wallabyJS (behind corp firewall, IntelliiJ is blocked from network access) and am following guide at https://wallabyjs.com/docs/intro/offline.html#jetbrains-ides trying to script to automate the upgrade process.

The first time I installed wallaby was on a different network, so I am now trying to upgrade but have some issues
1) I have located plugin dir at`<userDir>\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\wallaby-intellij`, is there a way I can tell which version this is and if I should replace it with a new  version from `https://download.wallabyjs.com/intellij` ? (is it enough to simply replace content in the `wallaby-intellij` folder?)
2) I have the wallaby core dir at `<userdir>\AppData\Local\JetBrains\IntelliJIdea2020.2\wallaby`, here I can tell version via `package.json` and compare with [wallaby.json](https://update.wallabyjs.com/wallaby.json) and if its newer I simply replace all content in `wallaby\wallaby` dir with `wallaby-v1.2.3` from amazonaws.com.
3) At step 6 in offline install however, it says I should have a dir `wallaby\wallaby-app`, which I don't but my local "wallaby app" in browser is working anyhow. Isn't this wallaby-app required?

Thanks.

**Comment by smcenlly** [comment]
> 1. I have located plugin dir at<userDir>\AppData\Roaming\JetBrains\IntelliJIdea2020.2\plugins\wallaby-intellij, is there a way I can tell which version this is and if I should replace it with a new version from https://download.wallabyjs.com/intellij ? (is it enough to simply replace content in the wallaby-intellij folder?)

There's no easily accessible client-side version number that we can refer you to check. The best method for checking whether there is a new version is to see if our server-side response to `https://download.wallabyjs.com/intellij` is the same as the last request. This call will actually redirect you to the download location for the latest version, so you may make a light-weight `HEAD` call to check whether the redirect location matches the version you already have. For example:

```javascript
const fetch = require('node-fetch');

(async () => {
  const result = await fetch('https://download.wallabyjs.com/intellij', { method: 'HEAD', redirect: 'manual '});
  const latestVersionLocation = result.headers.get('location');

  // TODO: check if latest version location is different from last time, and if so, download/extract it
  // TODO: update local manifest to remember what last installed version was
})();
```

> 2. I have the wallaby core dir at <userdir>\AppData\Local\JetBrains\IntelliJIdea2020.2\wallaby, here I can tell version via package.json and compare with wallaby.json and if its newer I simply replace all content in wallaby\wallaby dir with wallaby-v1.2.3 from amazonaws.com.

You can compare the `package.json` version against the `latestServer` attribute reported at this endpoint: `https://update.wallabyjs.com/wallaby.json` for your matching `major.minor` version number. An example `wallaby.json` is shown below. In your case, you should be looking for `1.0.998`. 

```json
{"latestServer":["1.0.998","0.9.10"],"latestIntelliJPlugin":"1.0.203","latestVisualStudioPlugin-12":"1.0.36","latestVisualStudioPlugin-14":"1.0.36","latestVisualStudioPlugin-15":"1.0.58","latestVisualStudioPlugin-16":"1.0.58","latestAtomPlugin":"1.0.61"}
```

> 3. At step 6 in offline install however, it says I should have a dir wallaby\wallaby-app, which I don't but my local "wallaby app" in browser is working anyhow. Isn't this wallaby-app required?

You will need to create the `wallaby-app` directory as a part of step 6, then extract the downloaded zip file from step 5. Most of the time, we find that Wallaby App works behind a corporate firewall but there are some cases (e.g. air-gapped networks) where Wallaby App **must** be installed to work in an offline environment. If Wallaby App works for you without following Step 5 or Step 6 then you may skip these steps.
