### ISSUE TITLE
Wallaby fails to start. DevTools contain SSL error

### ISSUE THREAD

**Issue by stevegreatrex** [wallabyjs/public#2589]
### Issue description or question

When I try to start Wallaby in VSCode I have started seeing the standard "Wallaby is updating and will be started automatically..." message, but Wallaby never starts.

This has worked on this setup (same machine, IDE, etc.) before, but my company have recently introduced SSL introspection which I suspect is causing the problem.

It sounds very similar to #2285 but 1) I don't see the status bar update; and 2) the suggested changes to non-strict SSL and to use HTTP in the settings have no effect.  In fact, if I force a core update for Wallaby I can still see an SSL error in the VSCode dev tool console.

### Wallaby diagnostics report
I do not have the requested command available and I see no longs in the wallaby console or test output

**Comment by smcenlly** [comment]
It does sound like the SSL introspection is causing a problem.

Our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html) should work for you in this case.

If your network configuration relies on a proxy server, you may also [configure VS Code to use your proxy server](https://code.visualstudio.com/docs/setup/network#_proxy-server-support), which may fix your problem.

**Comment by ArtemGovorov** [comment]
>  I can still see an SSL error in the VSCode dev tool console.

Can you please also share the error message/stack?

**Comment by stevegreatrex** [comment]
*Error Message*
This error is shown in the console

```
ERR 2460230792:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 0
: Error: 2460230792:error:100003e8:SSL routines:OPENSSL_internal:SSLV3_ALERT_CLOSE_NOTIFY:../../third_party/boringssl/src/ssl/tls_record.cc:592:SSL alert number 0
```
![image](https://user-images.githubusercontent.com/854480/102864689-7b21e200-442c-11eb-9f86-a3853781f8b8.png)

I can't get VSCode to break on the error but a breakpoint on the logging gives me this:
![image](https://user-images.githubusercontent.com/854480/102864928-e23f9680-442c-11eb-8c50-f3cc1c71c258.png)

*Offline Installation*
I followed the instructions provided but when I try to start Wallaby I still see the following
![image](https://user-images.githubusercontent.com/854480/102865792-2f703800-442e-11eb-931f-7b7caba916f3.png)

**Comment by ArtemGovorov** [comment]
> Offline Installation
> I followed the instructions provided but when I try to start Wallaby I still see the following

Can you please 
- verify that there's only one `c:\\Users\\op_stepheng\\.vscode\\extensions\\WallabyJs.wallaby-vscode-VERSION` folder in your ` c:\\Users\\op_stepheng\\.vscode\\extensions\\` folder.
- archive and attach your `c:\\Users\\op_stepheng\\.vscode\\extensions\\WallabyJs.wallaby-vscode-VERSION` folder.

**Comment by smcenlly** [comment]
@stevegreatrex - can you also please try to uninstall the Wallaby extension, delete the extension files from disk (i.e. `c:\Users\op_stepheng\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.254`) and then follow the offline installation instructions again?

The error in your console indicates that either your installation is corrupt or the Wallaby core version has not been extracted beneath your `c:\Users\op_stepheng\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.254` directory. That is to say, you are missing: `c:\Users\op_stepheng\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.254\wallaby`.

**Comment by ArtemGovorov** [comment]
@stevegreatrex Another thing (I know you've mentioned you've tried it already, but it needs VS Code restart), is that `wallaby.useHttpForDownload: true` may help. Can you please try this:
- Set `wallaby.noAutomaticInstall": false` (that you may have set to `true` as a part of offline installation procedure),
- Set `wallaby.useHttpForDownload: true`
- Restart VS Code,
- Run force core update command.

<img width="673" alt="Screen Shot 2020-12-23 at 3 39 41 pm" src="https://user-images.githubusercontent.com/979966/102963727-975d7600-4535-11eb-83f6-d02e3831e4d5.png">

**Comment by stevegreatrex** [comment]
I've set `useHttpForDownload`, restarted and forced an update but I still see the same error
![image](https://user-images.githubusercontent.com/854480/102974913-30b96780-44f7-11eb-8601-db0f4b76c011.png).  Neither this nor the Strict SSL setting seemed to have any effect on the behaviour, even after a restart.

The extension folder is here:
[wallabyjs.wallaby-vscode-1.0.254.zip](https://github.com/wallabyjs/public/files/5733991/wallabyjs.wallaby-vscode-1.0.254.zip).  There is only one such folder present (i.e. no other versions)

Interestingly it seems like I _am_ missing the `wallaby` and `wallaby-app` folders, despite creating them during the offline process.  Is it possible that it would have been automatically deleted by the extension, e.g. when I tried to force a core update?

Good news though: uninstalling the extension, deleting the `WallabyJs.wallaby-vscode-VERSION`, reinstalling the extension and then following the offline install steps has worked 🎉 

I'd still like to see if there's a way to fix automatic updates though.  Let me know what I can do to help debug

**Comment by smcenlly** [comment]
@stevegreatrex - glad to hear that you got it working. Our auto-update mechanism had not changed for a long time and we were using a now deprecated package for managing our http requests. We've updated to use a new package which may fix your problem. Please try the latest version of Wallaby for VS Code (v1.0.257) and try removing your `wallaby.noAutomaticInstall` setting.

If it does not work for you at first, please also try with `wallaby.strictSSL` set to `false.

In the worst case scenario it won't work for you and you'll have to follow the offline installation instructions again but ideally we'd like to get automatic updates working for you again.

**Comment by stevegreatrex** [comment]
![image](https://user-images.githubusercontent.com/854480/103073113-edc2c700-45be-11eb-89b0-8a9a063e9e4d.png)

👏 working perfectly!  Thanks for all the help guys, and thanks for the fantastic product.

Merry Christmas!
