### ISSUE TITLE
How I can resolve jest-runtime deps?

### ISSUE THREAD

**Issue by semeleven** [wallabyjs/public#2593]
### Issue description or question
I use pnpm workspace and when I start `npx jest` in packages then all tests running well. But wallaby has `Cannot find module 'jest-runtime'` error. I know about `--shamefully-hoist` (this not good for me, because pnpm hoist some packages incorrect), also when I install `jest-runtime` like deps, wallaby start work. But I work on a big project and only one use wallaby) Because I don't want to install `jest-runtime` like deps. Maybe has some way to alias this module manual? I tried to install `jest-runtime` like global deps, but it is not working. Of cause, I am use automatic settings

I can't attach `Diagnostic report`, because inside could be NDA info.

**Comment by smcenlly** [comment]
I'm assuming that you also cannot use `pnpm install --shamefully-flatten` (I'm not sure if it's different to `--shamefully-hoist`)?

You may also try to specify a configuration file with automatic configuration to explicitly provide the path to locate jest (relative to your project root):

```javascript
module.exports = () => {
  return {
    // tell wallaby to use automatic configuration
    autoDetect: true,

    testFramework: {
      // the path to locate jest
      // (relative to project root)
      path: './subfolder/node_modules'
    }
  }
};
```

**Comment by semeleven** [comment]
Yep, `shamefully-hoist` was rename to `shamefully-flatten`. Jest resolved without path setting in my case, like you suggest. I have problem with `jest-runtime`
```
‍[Info]  Started Wallaby.js Core v1.0.999
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Error] Runtime error: Failed to initialize wallaby jest. 
[Error] Cannot find module 'jest-runtime' 
[Error] Require stack: 
[Error] - /projects/some/node_modules/.pnpm/jest-config@26.4.2/node_modules/jest-config/build/index.js/wallaby.js 
[Error] Runtime error: Failed to initialize wallaby jest.
```
How can I tell Wallaby where `jest-runtime` is located?

**Comment by semeleven** [comment]
I'm finded solution - in my case enought add `public-hoist-pattern[] = "jest-runtime"` to `.npmrc` in project root
