### ISSUE TITLE
Mute upgrade period expiration on VSCode

### ISSUE THREAD

**Issue by dht** [wallabyjs/public#2596]
### Issue description or question

When running Wallaby.js on VSCode this message keeps appearing:
[
![wallaby-update-notification](https://user-images.githubusercontent.com/137832/103167840-4f8d6600-4837-11eb-927a-c6c6408ae0fe.png)
](url)
Could there be a way to mute it?

**Comment by ArtemGovorov** [comment]
Yes, you may mute the notification in Wallaby VS Code settings:

<img width="416" alt="Screen Shot 2020-12-27 at 8 14 08 pm" src="https://user-images.githubusercontent.com/979966/103168577-19280900-4880-11eb-92ff-47847d6f8434.png">
