### ISSUE TITLE
Any workaround when using __dirname, __filename, process.cwd()

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#2597]
### Issue description or question

I have hard time in figuring out how to bypass this Wallaby limitation. 

I mean when I have in my code any of `__dirname __filename process.cwd()`, I cannot rely on the outcome as Wallaby is copying the files to its out directory. 

Can I force Wallaby to somehow skip this optimization step?

**Comment by ArtemGovorov** [comment]
> Can I force Wallaby to somehow skip this optimization step?

If you are using Wallaby with Mocha, there's no way to not copy the files over to Wallaby cache directory. If you use Wallaby with Jest, it is possible (and is done by default).

> I cannot rely on the outcome as Wallaby is copying the files to its out directory.

Can you please describe the exact scenario when it is a problem for you that `__dirname, __filename, process.cwd()` are pointing to the folder where tests are running from? We may be able to suggest some solution.

**Comment by selfrefactor** [comment]
I only use Jest.

This is the file in question: https://github.com/selfrefactor/code-signal/blob/b814432de97fcd341c945f8472850c6c1352fa27/katas/refactor-to-require.spec.js#L26

As you can see, I was forced to use the absolute path, otherwise I couldn't see the output. Thank you for the fast reply.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo.

In order to run Wallaby with Jest in the project's folder, you need to [use Wallaby in auto-config mode](https://wallabyjs.com/docs/integration/jest.html) (instead of specifying `files` and `tests`).

This Wallaby config should work for as you expect:


```js
module.exports = function () {
  return {
    name: 'CodeSignal',
    filesWithNoCoverageCalculated: ['src/**/*.js'],
    runMode: 'onsave',
    autoDetect: true,
    env: {
      params: {
        env: 'WALLABY=ON'
      }
    }
  }
}
```

**Comment by selfrefactor** [comment]
Thanks for the help, but for me the issue is not resolved.

While it indeed fixed the issue with __dirname, it didn't properly skipped the files inside `src` folder. Feel fee to try it, but it doesn't work.

**Comment by ArtemGovorov** [comment]
In auto-config mode Wallaby is running the same way that Jest without Wallaby would, so running `npx jest` in your repo works the same way. If you want to ignore `src` folder, you may simply add it to your [Jest's config `watchPathIgnorePatterns `](https://jestjs.io/docs/en/configuration#watchpathignorepatterns-arraystring), by adding a separate [`jest.config.js` file](https://jestjs.io/docs/en/configuration) with the setting, or simply adding this to your `package.json`:

```diff
+  "jest": {
+    "watchPathIgnorePatterns": ["/src/"]
+  }
```

**Comment by selfrefactor** [comment]
Thank you, it worked.

**Comment by vjpr** [comment]
Just making a note for when using a config file. I was reading some `.html` files using:

```
import {fileURLToPath} from 'url'
const __dirname = dirname(fileURLToPath(import.meta.url))
const cliReferencePath = join(__dirname, 'clang-cli-ref.html')
const html = fs.readFileSync(cliReferencePath, {encoding: 'utf8'})
```

I had to add a `preprocessor` to move the files to the `lib` dir where my `ts` files were being compiled to. This is similar behavior to babel's `--copy-files` flag.

```
    preprocessors: {
      // Like babel's --copy-files. We have to copy files from src to lib that our code relies on.
      '**/*.html': file => {
        file.rename(file.path.replace('src', 'lib'))
        return file.content
      }
    },
```
