### ISSUE TITLE
IntelliJ IDEA Utlimate - PhantomJS Download error

### ISSUE THREAD

**Issue by TheCodeDestroyer** [wallabyjs/public#26]
I get this error, when running the wallaby.js configuration:

````
Can not download from
https://s3.amazonaws.com/wallaby-downloads/phantom/phantomjs-1.9.8-linux-x86_64.tar.bz2. 
````

I tried that URL in the browser and access is denied, while this one actually works:
`https://s3.amazonaws.com/wallaby-downloads/phantom/phantomjs-1.9.8-linux-x86_64.tar`

**Comment by ArtemGovorov** [comment]
Fixed, should be downloading fine now.
