### ISSUE TITLE
Hide the helper links ("Debug | View story | Focus") above the tests in the editor?

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#2600]
Howdy!
I use VScode with Mocha and the links "Debug | View story | Focus" above every test is kinda in my way, can I turn that off or hide it?
Thanks!

![image](https://user-images.githubusercontent.com/6947701/103392699-cdc26480-4ae4-11eb-91cc-d85a50861d6e.png)

**Comment by ArtemGovorov** [comment]
You may disable code lens from Wallaby with this VS Code setting:

<img width="477" alt="Screen Shot 2020-12-31 at 1 26 39 pm" src="https://user-images.githubusercontent.com/979966/103392939-e0cc4780-4b6b-11eb-8bb3-d6fdf47b06ba.png">
