### ISSUE TITLE
Failed to load configuration file:  Error: Cannot find module '/Users/tony/src/tmp/wallaby-vue-app/auto.detect'

### ISSUE THREAD

**Issue by tony19** [wallabyjs/public#2601]
### Issue description or question

An error occurs when starting Wallaby from Vue project, following the steps in https://wallabyjs.com/docs/tutorial/vue.html:

```
‍[Error] Failed to load configuration file:  Error: Cannot find module '/Users/tony/src/tmp/wallaby-vue-app/auto.detect' 
[Error] Require stack: 
[Error] - /Users/tony/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.257/wallaby2f83af/server.js 
[Error]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15) 
[Info]  Started Wallaby.js Core v1.0.614
```

### Steps to reproduce

 1. From command line, run `npx @vue/cli create wallaby-vue-app --default`
 2. In project root directory, run `npx @vue/cli add @vue/unit-jest` (and accept prompt to overwrite uncommitted changes from initial project generation)
 3. Open project in VS Code (1.52.1).
 4. From VS Code Command Palette, run `>Wallaby.js: Select Configuration`, then `Automatic Configuration: project directory`.
 5. Observe the error message in VS Code's *Wallaby.js Console*.

### Environment

 * macOS Big Sur `11.1`
 * Node `14.9.0`
 * VS Code `1.52.1`
 * Wallaby VS Code Extension `1.0.257`
 * Wallaby Core `1.0.614`
 * Vue CLI `5.0.0-alpha.0` and Vue CLI `4.5.9`

### Wallaby diagnostics report

*[No such diagnostics command available from the VSCode Command Palette]*

**Comment by tony19** [comment]
Adding `<projectRoot>/auto.detect` with the following contents (based on the [tutorial's Manual Config](https://wallabyjs.com/docs/tutorial/vue.html#configure-wallabyjs)) seems to mute the initial loading error, but still results in an error below:

```js
module.exports = (wallaby) => {

  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel({presets: [['@vue/app', {modules: 'commonjs'}]]})

  return {
    autoDetect: true,
    files: ['src/**/*', 'jest.config.js', 'package.json'],

    tests: ['tests/**/*.spec.js'],

    env: {
      type: 'node'
    },

    compilers: {
      '**/*.js': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler)
    },

    preprocessors: {
      '**/*.vue': file => require('vue-jest').process(file.content, file.path, require('./package').jest || require('./jest.config'))
    },

    setup: function (wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config')
      jestConfig.transform = {}
      wallaby.testFramework.configure(jestConfig)
    },

    testFramework: 'jest'
  }
}
```

*Wallaby.js Console*:

```
[Info]  Started Wallaby.js Core v1.0.614
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Error] Runtime error: Failed to initialize wallaby jest. 
[Error] Error: Cannot find Jest test runner 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1075:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:940:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:781:14) 
[Error]     at Module.require (internal/modules/cjs/loader.js:964:19) 
[Error]     at require (internal/modules/cjs/helpers.js:88:18) 
[Error]     at Module._compile (internal/modules/cjs/loader.js:1075:30) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:940:32) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:781:14) 
[Error]     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) 
[Error]     at internal/main/run_main_module.js:17:47 
```

**Comment by smcenlly** [comment]
Thanks for reporting your problem. It looks like our Vue tutorial is now out of date as `vue` has changed their jest setup instructions.

If you follow their setup instructions from [here](https://vue-test-utils.vuejs.org/guides/#setting-up-jest), it should work for you.

We will update our tutorial now to reflect their current set of instructions. If you have trouble following their guide, refresh our website after the next hour or so and you should be able to follow the tutorial again with the correct set of steps.

**Comment by tony19** [comment]
@smcenlly Thanks for the response!

The Jest setup you mention is automatically done via Vue CLI's Jest plugin (via `vue add @vue/unit-jest`), so that guidance doesn't help unfortunately. Any other suggestions?

**Comment by smcenlly** [comment]
@tony19 - the instructions from the website mostly worked for us (there were a few other dependencies that were missing). Our [vue tutorial](https://wallabyjs.com/docs/tutorial/vue.html) has been updated with correct instructions to setup on a default project type.

At a basic level, if you find instructions to get `jest` working outside of Wallaby (using `npx jest`) then Wallaby will also work for you.

**Comment by tony19** [comment]
@smcenlly The updated instructions fail with a different error upon installing `vue-jest`, yet this error is not observed with the Vue CLI Jest plugin. However, if I stick with the original Wallaby instructions of using the Vue CLI Jest plugin, I can run passing tests with `npx jest`, but Wallaby still fails with the original error. Can you link to a sample GitHub repo that actually works for you?

**Comment by ArtemGovorov** [comment]
@tony19 It looks like your installed Wallaby Core version is very old, probably because your Wallaby license had expired in Sep 2018:

> Started Wallaby.js Core v1.0.614

Latest Vue CLI support, as well as automatic configuration support had been added to Wallaby after that date. Please try the following:

- Get Wallaby trial license at https://wallabyjs.com/download/,
- Apply trial license in VS Code by running `Wallaby: Manage License Key` command,
- Wait until it installs the latest Wallaby Core version (1.0.1001),
- Start Wallaby automatic config (the way that you have described in the initial post of this issue), and it should work for you.

If it's working with the latest version, you may consider [renewing your Wallaby license](https://wallabyjs.com/purchase/#select-wallaby).

**Comment by tony19** [comment]
@ArtemGovorov Thanks, that fixed it!

While the trial key works, I'd like to get an OSS key, but I get this error:

> Our records indicate that you already have Wallaby license. You may use your existing license for your OSS projects too.

**Comment by tony19** [comment]
@smcenlly Also, please consider reverting the Vue tutorial steps to use the Vue CLI Jest plugin, as that actually works without error and is simpler than the proposed manual setup. Thanks!

**Comment by ArtemGovorov** [comment]
> While the trial key works, I'd like to get an OSS key, but I get this error:
> Our records indicate that you already have Wallaby license. You may use your existing license for your OSS projects too.

You may use a different email address to get your OSS key, but please note that our OSS license only works for publicly available OSS projects, and you will not be able to use your old Wallaby license and OSS license at the same time (even on different projects).

**Comment by smcenlly** [comment]
> @smcenlly Please consider reverting the Vue tutorial steps to use the Vue CLI Jest plugin, as that actually works without error and is simpler than the proposed manual setup. Thanks!

I actually had problems when I followed the previous tutorial: `npx jest` failed from the command-line, which is when we noticed the setup instructions had changed. We're going to stick with updated instructions for now.

**Comment by tony19** [comment]
@smcenlly That's odd. The updated instructions don't work however, as the NPM installation fails (commented [above](https://github.com/wallabyjs/public/issues/2601#issuecomment-753407595)). I'll create a new issue to track that.
