### ISSUE TITLE
Wallaby's Vue tutorial steps fail

### ISSUE THREAD

**Issue by tony19** [wallabyjs/public#2603]
### Issue description or question

The [official tutorial for setting up Wallaby in Vue CLI projects](https://wallabyjs.com/docs/tutorial/vue.html) was recently changed (as a side effect of https://github.com/wallabyjs/public/issues/2601#issuecomment-753405209), and no longer works.

#### `npx vue` command

The tutorial [suggests](https://wallabyjs.com/docs/tutorial/vue.html#create-a-new-vuejs-application) using:

```
npx vue create wallaby-vuejs-app --default
```

...but if you don't already have the `@vue/cli` package globally installed, `npx vue` fails with:

```
$ npx vue create wallaby-vuejs-app --default
npx: installed 1 in 1.639s
command not found: vue
```

The `@vue/cli` package name should be passed to `npx` instead:

```
npx @vue/cli create wallaby-vuejs-app --default
```

#### Jest setup

The tutorial also [suggests](https://wallabyjs.com/docs/tutorial/vue.html#add-unit-tests-to-your-project) using:

```
npm install --save-dev jest @vue/test-utils vue-jest babel-core@bridge
```

...but the `vue-jest` package installation is failing with:

```
$ npm install --save-dev jest @vue/test-utils vue-jest babel-core@bridge
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/vue-loader-v15 - Not found
npm ERR! 404 
npm ERR! 404  'vue-loader-v15@15.9.6' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@vue/cli-service'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tony/.npm/_logs/2021-01-05T02_51_15_100Z-debug.log
```

The previous Vue tutorial had a simpler Jest setup, as it only required adding the [Vue CLI Jest plugin](https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-jest) (i.e., run `vue add unit-jest` from the root of your Vue CLI generated project), which automatically selects the correct versions of the required dependencies and generates the proper Jest config for your Vue CLI generated project. More importantly, it works without error.

Can the original Jest setup be restored in the tutorial? Or added as alternate instructions?

### Wallaby diagnostics report

*No relevant diagnostic report, as the issue pertains to the website*

**Comment by smcenlly** [comment]
Thanks for creating the issue.

We've reverted our tutorial to the previous version and updated it to use `npx @vue/cli` instead of using globally installed `vue` package. When we tested the previous tutorial I had a conflict in our global vue dependencies that caused the tutorial to fail but it works after upgrading to the latest and with `npx @vue/cli`.

The updated tutorial should also have worked for you and was working for us on a fresh node installation on both Windows and Linux. We didn't get the `https://registry.npmjs.org/vue-loader-v15 - Not found` error.

Regardless, the previous tutorial has been reverted, is simpler and is now working correctly so we will close this issue.
