### ISSUE TITLE
Console warnings from jest seem to get buried

### ISSUE THREAD

**Issue by nerdo** [wallabyjs/public#2604]
### Issue description or question

I noticed that some important warnings from jest are getting buried by wallabyjs.

In particular, I am seeing instances where if I run jest directly OR dig into the wallaby.js console, I see warning messages in my React project relating to not calling act(). I only noticed this at the end of the project when I was getting ready to publish it and that runs jest directly. I never look at the wallabyjs console unless there's a good reason to.

Unfortunately, this is a work project and I can't share the repository, but it should be fairly easy to reproduce by either setting up an act() example like [https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning] or finding some other way for jest to produce warnings.

Ideally any of these kinds of warnings would appear in the UI, similar to how the code coverage indicators work, or get surfaced in some other way so that they can be addressed immediately.

Here is a screenshot of the warnings in my console from running jest directly, but also in the wallabyjs console.

![wallabyjs-jest-warnings](https://user-images.githubusercontent.com/1031502/103925311-52187700-50e5-11eb-8183-194969879103.png)

### Wallaby diagnostics report

The diagnostic report seems to be too long to paste. Please let me know if you need it and I will try to attach it to the issue in some other way.

**Comment by smcenlly** [comment]
Unlike jest, Wallaby has the ability to [fail a test on `console.error` messages](https://wallabyjs.com/docs/config/overview.html#report-consoleerror-as-test-run-error). In your case, if you want Wallaby to fail when this error occurs, you may create a wallaby.js configuration file with `reportConsoleErrorAsError` set to `true` or else add a `wallaby` section to your `package.json` to do the same:

**package.json example**
```javascript
{
...
  "wallaby": {
    "reportConsoleErrorAsError": true
  }
}
```

---

We have also updated Wallaby to output external dependency `console.*` messages ('log', 'warn', 'error', 'dir', 'debug', 'info') to Wallaby's log when using jest. Previously these messages were not displayed as you mentioned. These messages will now be automatically displayed in the Wallaby output for all failing tests. You may also see these messages in your Wallaby App console and when you use the `Wallaby.js: Show Line Tests` command. You will need to update your Wallaby core version to v1.0.1002+ for Wallaby to report all console messages when using jest. 

If you are using an older version of Wallaby and don't want to update to the latest version for some reason, you may still use the `reportConsoleAsError` option mentioned above.
