### ISSUE TITLE
Wallaby not starting in VS Code

### ISSUE THREAD

**Issue by epegzz** [wallabyjs/public#2605]
### Issue description or question

I get the message `Wallaby.js is updating, [...]`. 

Re-installing and restarting VS Code does not help.

I also followed resolution steps in similar issues I found here on GitHub, but without luck.

I'm not using any HTTP proxy.

I am running VS Code on a MacMini M1 with a Remote-SSH workspace on a remote Linux machine.

On both machines a `~/.wallaby` folder gets created.

On the MacMini it contains one file: `~/.wallaby/downloads/wallaby.zip`, on the remote linux machine it only contains an empty `~/.wallaby/downloads` folder.

Not sure how I could further debug 🤔

**Comment by smcenlly** [comment]
Do you get any errors reported in your VS Code developer tools console? To check, run the VS Code command: `Developer: Toggle Developer Tools` and see if there are any `Console` messages.

We'd like to get work out why the update mechanism is not working for you but in the meantime, you should also be able to follow our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html).

Could you also please provide us with the contents of `~/.wallaby/downloads/wallaby.zip` from your MacMini? If you cannot attach to the issue, please email it to us (hello@wallabyjs.com).

**Comment by epegzz** [comment]
So, waking up this morning all is working 🤔 
So maybe it really took a very long time to download? Not sure.
At least now the `~/.wallaby/downloads/wallaby.zip` exists on both machines.

Maybe because I was using a VPN on MacMini but not on the remote Linux machine. Without VPN downloads from GitHub are stalling unfortunately which is why I started using VPN. Apparently GitHub has throttled the IP range of my internet provider.

But AFAIK the `wallaby.zip` is downloaded from AWS, not Github?

But anyways, thanks a lot for your support!
