### ISSUE TITLE
Cant Override Headless Mode for Chrome

### ISSUE THREAD

**Issue by pixelshaded** [wallabyjs/public#2610]
Wallaby has been amazing. The one thing I have trouble with right now is debugging DOM issues. Looking at outerHTML/innerHTML strings is painful, especially because they get truncated by wallaby. What I want to be able to do is view the test as it is running in the browser and explore the DOM through that. I would guess that using chrome without the headless flag would work, but because I am on a modern version, that flag is passed by default.

Env:
- Angular CLI 8.3.25
- Chrome 88.0.4234.96
- IntelliJ Ultimate 2020.3.1
- MacOS Catalina 10.15.7
- Wallaby 4.6.2

In IntelliJ, I am using automatic configuration along with a wallaby.js file with overrides as described here:
https://wallabyjs.com/docs/intro/config.html#overriding-automatic-defaults

```javascript
module.exports = (wallaby) => ({
  autoDetect: true,
  env: {
    kind: 'chrome',
    params: {
      runner: '',
    },
  },
});
```

Note that in IntelliJ, there is are two types of run config, one for automatic and one for manual. The automatic one runs fine but seems to completely ignore any changes I make to the wallaby.js file. If a use the manual config, it doesn't find any of my tests, so it seems like autoDetect: true doesn't work the same as the automatic run config.

Am I missing something?

**Comment by smcenlly** [comment]
The configuration below should work for you.

**wallaby.js configuration file**
```javascript
module.exports = (wallaby) => ({
  // Tell Wallaby to auto-detect/configure your project
  autoDetect: true,

  // Limit Wallaby execution to a single process (otherwise you will get many tabs opened)
  workers: {
    initial: 1,
    regular: 1,
  },

  // Override Wallaby's environment settings to keep tabs opened and not open in headless mode
  env: {
    keepTabsOpened: true,
    kind: "chrome",
    params: {
      runner:
        "--disable-gpu --disable-translate --disable-extensions --disable-background-networking --safebrowsing-disable-auto-update --disable-sync --metrics-recording-only --disable-default-apps --no-first-run",
    },
  },
});
```

**Comment by pixelshaded** [comment]
Thank you.
