### ISSUE TITLE
Test hanging with exclusive test run + autoconfig

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#2612]
### Issue description or question

Our work repo is quite large and due to those reason I was using exclusive test run for specific files. Recently I do not getting test result indicator in editor, would like to request some help to diagnose problem.

I have full trace + diagnostics report in hand, but hope to share in private way to not reveal some of paths includes PII / work related. Please let me know if there's way to upload those other than public issue.

**Comment by ArtemGovorov** [comment]
@kwonoj Please send the trace + diagnostics report to hello@wallabyjs.com.

**Comment by kwonoj** [comment]
Thanks, submitted. Please let me know if there are other things I need to provide.

**Comment by kwonoj** [comment]
Closing as latest core update helped to resolve issue. Appreciate for the help.
