### ISSUE TITLE
How to utilize .env.test[.local] files with Jest (create-react-app) ?

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2613]
### Issue description or question

How should I configure Wallaby to utilize the `.env.test` files ([react doc](https://create-react-app.dev/docs/adding-custom-environment-variables/)) ?
(it works fine when I run via `npm test`)

My current `wallaby.js` file is:
```js
module.exports = () => ({
    autoDetect: true,
    tests: ['src/__tests__/**/*.test.ts?(x)'],

    reportConsoleErrorAsError: true,
});
```

Thanks.

**Comment by smcenlly** [comment]
The following will work for you:


```diff
+ require('dotenv').config({ path: '.env.test' });
module.exports = () => ({
    autoDetect: true,
    tests: ['src/__tests__/**/*.test.ts?(x)'],

    reportConsoleErrorAsError: true,
});
```

By default, Create React App has the `dotenv` module installed as a dependency but if for some reason your version does not, you might have to install as a devDependency using `npm install dotenv --save-dev`.

**Comment by greenmooseSE** [comment]
> The following will work for you:
> ```+ require('dotenv').config({ path: '.env.test' });```

This only reads `.env.test` files but does pick up overridden values from `.env.test.local`, any hints of how to fix that as well?
(`npm install dotenv --save-dev` did not make any difference).

Thanks.

**Comment by smcenlly** [comment]
If you have a `.local` file. you may read that as well. I'm assuming any `.local` overrides take precedence, in which case you should load it first. You can read more about how to use `dotenv` in their [docs](https://www.npmjs.com/package/dotenv). Also, you should note that `dotenv` does not override existing values that may be set. A more complex example from their docs:

> ```javascript
> const fs = require('fs')
> const dotenv = require('dotenv')
> const envConfig = dotenv.parse(fs.readFileSync('.env.override'))
> for (const k in envConfig) {
>   process.env[k] = envConfig[k]
> }
> ```

So you could do something like:

```javascript
const fs = require('fs')
const dotenv = require('dotenv')
const envConfig = { ...dotenv.parse(fs.readFileSync('.env.test')), ...dotenv.parse(fs.readFileSync('.env.test.local')) }
for (const k in envConfig) {
  process.env[k] = envConfig[k]
}
```

Of course, if your `.env` files differ on different machines and you are using a shared Wallaby file, you can also make the wallaby configuration tolerant of that.
