### ISSUE TITLE
highlight filters on coverage explorer (failed/logged/skipped/todo)

### ISSUE THREAD

**Issue by pixsrv** [wallabyjs/public#2614]
### highlight filters on coverage explorer (failed/logged/skipped/todo)

it could be nice to have them highlighted a bit more
it's hardly visible which switch is switched
it's especially misleading when user re-runs wallaby and the app shows new set of tests

**Comment by smcenlly** [comment]
We've updated Wallaby app to use checkboxes instead of toggle switches to make filter selection more obvious (see TODO example in screenshot below):

![image](https://user-images.githubusercontent.com/2074089/110427413-713a8180-80f3-11eb-86e1-b18393316ac9.png)

**Comment by pixsrv** [comment]
could not be better
thanx @smcenlly
