### ISSUE TITLE
setting a breakpoint using the mouse is doesn't work due to wallaby gutter icons

### ISSUE THREAD

**Issue by gabimor** [wallabyjs/public#2622]
### Issue description or question

VS code 1.53.0

Issue: Usually clicking on the gutter in VS code sets a break point. this doesn't when clicking on Wallaby gutter marks and am forced to use F9 to set the break point.

Expected result: clicking on a wallaby gutter mark will set a breakpoint, same as F9 if the cursor in located on that line.

**Comment by ArtemGovorov** [comment]
Unfortunately it's a current limitation of the VS Code UI. Here's the issue in the VS Code repo: https://github.com/Microsoft/vscode/issues/5923, feel free to subscribe and vote for it.

Also see https://github.com/wallabyjs/public/issues/279
