### ISSUE TITLE
React: HTMLOptionElement.label not null in wallaby, but null with npm test

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2631]
### Issue description or question
(CRA app)
Code below passes with wallaby (`.label` has same value as `.textContent`), but fails with npm test (`.label` is null but `.textContent` is not). I suspect wallaby uses a different rendering engine than npm test? How can I ensure they both produce consistent result?

### Code example

```tsx
import React from 'react';
import {render, screen} from '@testing-library/react';
import {act} from 'react-dom/test-utils';

describe("Troubleshooting tests", () => {
    it.only("it can render as expected", () => {
        let dropdownLabel = "label for the dropdown";
        act(() => {
            render(<>
                <label htmlFor="dropdown01">
                    {dropdownLabel}
                </label>
                <select id="dropdown01">
                    <option id="dropDownOption-1-0" value="">
                        Option 01
                    </option>
                    <option id="dropDownOption-1-1" value="foo">
                        Option 02
                    </option>
                </select>
            </>)
        });

        let select = screen.getByLabelText(dropdownLabel) as HTMLSelectElement;
        expect(select).toBeTruthy();
        expect(select.item(0)?.textContent).toBe("Option 01");
        let selectOption = select.item(0) as HTMLOptionElement;
        expect(selectOption).toBeTruthy();
        expect(selectOption.label).toBe("Option 01");
    });
});
```
### NPM test output
```
    expect(received).toBe(expected) // Object.is equality

    Expected: "Option 01"
    Received: null

      27 |         let selectOption = select.item(0) as HTMLOptionElement;
      28 |         expect(selectOption).toBeTruthy();
    > 29 |         expect(selectOption.label).toBe("Option 01");
         |                                    ^
      30 |     });
      31 | });
      32 |

      at Object.it.only (src/__tests__/viewTests/renderTest.test.tsx:29:36)
```
</details>

### Wallaby config file:
```
module.exports = () => ({
    autoDetect: true,
    files: [
        'src/**/*.ts?(x)',
        {pattern: 'src/__tests__/**/*.test.ts?(x)', ignore: true}
    ],
    tests: ['src/__tests__/**/*.test.ts?(x)'],
    reportConsoleErrorAsError: true,
});
```

Thanks!

**Comment by smcenlly** [comment]
>  I suspect wallaby uses a different rendering engine than npm test?

Wallaby uses the same rendering engine as when you run your tests with jest.

> Code below passes with wallaby (.label has same value as .textContent), but fails with npm test (.label is null but .textContent is not). I suspect wallaby uses a different rendering engine than npm test? How can I ensure they both produce consistent result?

We tried the same code in a freshly created CRA project and everything works for us in both Wallaby and npm. Could you please [clone our repo](https://github.com/wallabyjs/wallaby-2631) to confirm everything is working for you? There may be something else wrong with your project. I would also try clearing your jest cache `npx jest --clearCache` from the command-line as that may fix your tests not working using `npm test`.

**Comment by greenmooseSE** [comment]
> I would also try clearing your jest cache npx jest --clearCache

That did not help

> Could you please clone our repo to confirm everything is working for you? 

Yes that does indeed work. I think need to compare these 2 project's dependencies to find the root cause of this.  I don't have time to do this now though (in the middle of a sprint) but I might be able to squeeze it in during upcoming week or 2 weeks.
You can close this issue for now if you want, and I can get back to it if I find the cause of it.
Thanks.

(I will use `.textContent` as a workaround for now to be able to complete the story I'm working on)
