### ISSUE TITLE
Auto-configuration fails with jest-runner-tsc

### ISSUE THREAD

**Issue by TrevorBurnham** [wallabyjs/public#2633]
### Issue description or question

I have a Typescript project that uses [jest-runner-tsc](https://github.com/azz/jest-runner-tsc). The project has a `jest.config.js` in its root that looks like this:

```js
module.exports = {
  moduleFileExtensions: ['js', 'ts', 'tsx'],
  testMatch: ['<rootDir>/**/*.ts'],
  runner: 'jest-runner-tsc',
};
```

That broad `testMatch` is intentional: jest-runner-tsc requires `testMatch` to include all TypeScript files, not just tests.  Running `pnpx jest` from the project root works fine. But automatic configuration in Wallaby fails.

### Wallaby diagnostics report

None, the only output in the Wallaby.js Console is:

```
‍[Info]  Started Wallaby.js Core v1.0.1031
[Error] Failed to load configuration file: Automatic Jest configuration error: Can not find any Jest runner configurations in '.'. 
```

**Comment by smcenlly** [comment]
> Running pnpx jest from the project root works fine.

It sounds like you are using `pnpm` to manage your project's dependencies

Unfortunately the way pnpm installs modules by default is not supported by Wallaby. Having said that, the following command will install modules in a way that is supported:

```
pnpm install --shamefully-flatten
```

We had a similar issue reported in the past (#2593), depending on your project, perhaps the same steps will help in your case:

> in my case it was enough to add public-hoist-pattern[] = "jest-runtime" to .npmrc in project root

**Comment by TrevorBurnham** [comment]
I don't think `pnpm` was the issue in this case; I've had no trouble running Wallaby against other pnpm projects.

Good news, though: It turns out that I didn't really want the functionality of jest-runner-tsc anyway. 😅  I switched my project over to [ts-jest](https://github.com/kulshekhar/ts-jest) and everything—including Wallaby—works much better!

**Comment by smcenlly** [comment]
> Good news, though: It turns out that I didn't really want the functionality of jest-runner-tsc anyway. 😅 I switched my project over to ts-jest and everything—including Wallaby—works much better!

In case you are interested, we used to use `ts-jest` for our project's tests but then switched to using the `babel` TypeScript preset and found it to be much faster. We didn't want/need type checking when running our tests and didn't need any other `ts-jest` benefits (you can read about differences [here](https://kulshekhar.github.io/ts-jest/docs/babel7-or-ts/)).
