### ISSUE TITLE
[Feature Request] Provide ability to exclude certain files from test story view

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2638]
From our discord channel:

> It would be nice to be able to exclude certain files from the 'test story' view.  For example, I have a call to a logger class that adds a lot of noise to the story output:
> 
> ![image](https://user-images.githubusercontent.com/2074089/108919113-301b8980-767e-11eb-8e8f-78a9e6a2ffed.png)

Note: it is possible to change your file coverage settings to exclude noisy infrastructure files (e.g. logger). Having said that, we can imagine sometimes you would only want to do this in the context of viewing a test story.

**Comment by ArtemGovorov** [comment]
[The feature has been implemented](https://wallabyjs.com/docs/intro/test-stories.html#hiding-repeated-executed-code-fragments) and released in [the latest Wallaby core 1.0.1039](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
