### ISSUE TITLE
Workers overlap tests

### ISSUE THREAD

**Issue by bestan** [wallabyjs/public#264]
My backend has **851** tests. I'm using `atom-wallaby` plugin and 5 workers.

```
Wallaby Console: Mon, 14 Sep 2015 07:10:57 GMT wallaby:workers Loaded 164 test(s)
Wallaby Console: Mon, 14 Sep 2015 07:10:57 GMT wallaby:workers Loaded 148 test(s)
Wallaby Console: Mon, 14 Sep 2015 07:10:57 GMT wallaby:workers Loaded 177 test(s)
Wallaby Console: Mon, 14 Sep 2015 07:10:57 GMT wallaby:workers Loaded 623 test(s)
Wallaby Console: Mon, 14 Sep 2015 07:10:57 GMT wallaby:workers Loaded 851 test(s)
```

At the end of the initial run I'm seeing "**1963** passing tests". These numbers are quite consistent - if I restart the plugin, they're exactly the same.

`tests` in `wallaby.js` looks like this:

```javascript
    tests: [
      'test/**/*.js',
      '!test/helpers/**/*.js',
    ],
```

To me, having multiple workers is about finishing initial test run as quickly as possible. I would expect wallaby to run exactly 851 tests to achieve that.

**Comment by ArtemGovorov** [comment]
Is anything satisfying `test/**/*.js` (except the helpers folder) not a simple file with tests? Are there any files in your test files `test/**/*.js` that load other tests, perhaps some files that `require` all/some of your specs?

**Comment by bestan** [comment]
Yes - `test/test.js` loads all specs. However, I couldn't make wallaby work by including just that single file. It's likely I don't exactly understand how I should be loading test files correctly, but configuration I posted initially works perfectly with 1 worker.

**Comment by ArtemGovorov** [comment]
Wallaby needs separate test files to be in the files list. It'll feed each of those files to mocha as an entry point. Including a single file doesn't let wallaby to run files in parallel and not supported for a few other reasons (wallaby needs to know exactly what your test roots are to properly instrument and report results).

So `test/test.js` has to be excluded from the tests list:
```
tests: [
      'test/**/*.js',
      '!test/test.js',
      '!test/helpers/**/*.js',
    ],
```
Let me know if excluding the file makes the numbers right.

**Comment by ArtemGovorov** [comment]
So `test/**/*.js` pattern should only contain your actual files with tests (where you have `describe/it`) and nothing else. Perhaps there's some convention you follow to name those files, some add `test` or `Spec` suffix, so the pattern may look like `test/**/*Spec.js` and there'll be much less chance to include anything else by mistake.

**Comment by bestan** [comment]
@ArtemGovorov it's working fine now. Thanks!
