### ISSUE TITLE
OSS License not working

### ISSUE THREAD

**Issue by ali-master** [wallabyjs/public#2640]
### Issue description or question
I got a wallaby OSS license for about 4 months ago for my Repository in Github. That days, Wallaby worked great before 1.5 month ago, but now, it's not working(I activated the Wallaby via my Email address.)

Repo:
[Persian-Tools Repository](https://github.com/persian-tools/persian-tools)

### Wallaby diagnostics report

12:13 PM	Wallaby Notification: Wallaby.js activation check is being performed. Wallaby.js will be started until after a successful check.

12:13 PM	Wallaby Notification: Wallaby.js has been successfully activated.

12:13 PM	Wallaby Notification
					Currently installed version of Wallaby.js is not covered by your license. Please visit our website to upgrade your license.
					If you have purchased a renewal license, please activate it.

**Comment by ArtemGovorov** [comment]
Please update to [the latest Wallaby Core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and it should work for you.

**Comment by ali-master** [comment]
I'm using the latest version.

**Comment by ArtemGovorov** [comment]
When you start Wallaby, what version of core does it print to to Wallaby Console?

**Comment by ali-master** [comment]
v1.0.1036

**Comment by ali-master** [comment]
I'm developing the next version of my Repository and priority of improving the Test is higher than before. Can you help me to fix my Wallaby's problem?

IDE: WebstormWebStorm 2020.3.2, Build #WS-203.7148.54, built on January 25, 2021
Wallaby Core version: v1.0.1036
Wallaby Plugin version: v1.0.211

**Comment by smcenlly** [comment]
We found a bug that mean that if you had not used Wallaby for a long time then your OSS license would not refresh itself; this is fixed in the latest version of Wallaby, `v1.0.1037`. 

If Wallaby does not update for you with that version, or you're still having problems, please delete your `.wallaby` directory in your user home directory and then enter your email address again as your license key. At this point, you will receive an email to confirm your open source license activation and everything should work for you again.

**Comment by ali-master** [comment]
Woow thanks for the new update and I've updated my Wallaby plugin but I got this error:
```
Wallaby.js has been stopped because the open source status of your project could not be verified.
```

**Comment by smcenlly** [comment]
> If Wallaby does not update for you with that version, or you're still having problems, please delete your .wallaby directory in your user home directory and then enter your email address again as your license key. At this point, you will receive an email to confirm your open source license activation and everything should work for you again.

Our logs show that you did not delete your `.wallaby` directory. Could you please confirm that you have done that and try again?

**Comment by ali-master** [comment]
Sorry for the delay to response, I deleted `.wallaby` directory and It worked. Thanks a lot for supporting the Open source projects. I appreciate your attention and help.
