### ISSUE TITLE
Cannot copy live outputs

### ISSUE THREAD

**Issue by felipedrumond** [wallabyjs/public#2642]
I'd recommend allowing us to copy live outputs. That can improve a little bit out coding performance.

![image](https://user-images.githubusercontent.com/17038136/109437697-55433a00-7a7a-11eb-8da5-e2e1a07f1e48.png)

**Comment by smcenlly** [comment]
The ability to copy live outputs is limited by editor support. For VS Code, you may use the existing [`Copy Value`](https://wallabyjs.com/docs/intro/advanced-logging.html#show-value--copy-value) feature; select your variable that you wish to copy (e.g. `disclaimer`) and then run the `Wallaby.js: Copy Value` command.
