### ISSUE TITLE
Wallaby auto update check crashes VSCode Extension host

### ISSUE THREAD

**Issue by patroza** [wallabyjs/public#2646]
### Issue description or question

When no or poor internet connection, Wallaby auto update check crashes VSCode Extension host

**Comment by smcenlly** [comment]
We have done some testing and Wallaby appears to be working for us when we completely disconnect from the internet. The behavior being completely disconnected vs. poor internet connection should be the same.

What we tried:

**Scenario 1**
1. Fresh install of VS Code (no other extension installed to make sure problem is Wallaby)
2. Install Wallaby extension offline (from VSIX)
3. Wallaby start page appears but Wallaby core doesn't update (no internet); NO CRASH

**Scenario 2**
1. Fresh install of VS Code
2. Install Wallaby extension while connected to the internet
3. Wallaby start page appears and Wallaby core is updated; NO CRASH (Wallaby can start successfully)
4. Run Wallaby `Wallaby.js: Force Core Update` to perform immediate auto-update check; NO CRASH

---

Could you please provide a bit more detail on your problem:

* Please provide a screenshot or copy/paste text-based error details
* Describe your environment (e.g. operating system, are you using one of the VS Code Remove Development Environments)?
* If possible, steps that you take to reproduce the error; can you reproduce on a fresh installation?
* Are you running behind a corporate firewall or proxy server?

**Comment by smcenlly** [comment]
I'm going to close this issue since we haven't heard back. If you reply with more information, we'll re-open it.
