### ISSUE TITLE
Add flexibility to "files" config

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2647]
### Issue description or question

I have started to work on a project where tests are located not in a single top-level folder, but in many *tests* folders near the code they are testing. Also, each *tests* folder may include *support* or *factories* folders with tests utils files that don't include any tests (and so, must be specified in *files* config and excluded from *tests* config) And it appeared that with the current way how "files" config is getting resolved, writing the correct pattern is just not possible :( Consider requirements:
 * include all files in */src/*
 * exclude all files in */src/**/tests/*
 * include all files in */src/**/tests/support/*
 * include all files in */src/**/tests/factories/*
There are many ways to achieve this: allow to add negation that would respect its position in *files* array (right now all negations are applied after non-negations), allow to suppress error if the same file is specified in both *files* and *tests*, allow to use regexps as patterns, probably more things can be thought out... anything that would allow to "include subfolders of excluded folder" would work

Thank you!

**Comment by smcenlly** [comment]
In your example, the following should work for you:

**wallaby.js**
```javascript
module.exports = function () {
  return {
    files: [
      'src/**/*.js', //Pattern 1
      '!src/**/tests/*.js' //Pattern 2
    ],

    tests: [
      'src/**/tests/*.js',
    ],

    env: {
      type: 'node'
    }
  };
};
```

> * include all files in */src/*

Matched by `Pattern 1`
Not Matched by `Pattern 2`

> * exclude all files in */src/**/tests/*

Matched by `Pattern 1`
Matched by `Pattern 2` (files directly under tests folder are excluded for `files`, included for `tests`)

> * include all files in */src/**/tests/support/*
> * include all files in */src/**/tests/factories/*

Matched by `Pattern 1`
Not Matched by `Pattern 2` (there is a nested folder under tests and no `**` part of the pattern so these files are not part of tests but are part of files)

---

There can be some limitations to how you need to express your `files` and `tests` patterns but your example seems to be fairly standard. If you have a more complex use case, please provide us with your file/folder structure (or sample) and we can help you out with a pattern.

In the worst case scenario, you may read files/directories from disk in your `wallaby.js` file as you construct the configuration but needing to do this is fairly rare. For example:

```javascript
const fs = require('fs');

const files = [];
const tests = [];

// Use `fs` to read (potentially recursively) folders and generate
// files/tests patterns...
//
// files.push(resultOfCustomLogic)
// tests.push(resultOfCustomLogic)

module.exports = function () {
  return {
    files,
    tests,

    env: {
      type: 'node'
    }
  };
};
```

**Comment by Alexsey** [comment]
Thank you for the response

Unfortunately, sometimes `/tests/` may have subfolders with tests. Right now there is a limited number of subfolders, so I have specified them manually in `files` below `/tests/*.js`, but it could break at any moment and if it's possible to have a non-hacky solution - it's always better to use it

I was also thinking about collecting files and tests manually in the config, but it seems to be very slow to scan hundreds of files on each tests re-run. Is there a way to go over this performance problem without me building a local cache of file system tree? :)

**Comment by smcenlly** [comment]
> it seems to be very slow to scan hundreds of files on each tests re-run

In terms of file scan, this is something that Wallaby does a bit of under the covers as you can probably imagine. I assume that you're running on an SSD? If you are scanning < 2000 files, it shouldn't take more than 250-500ms and will only happen once on start up.

In this case, I would imagine that you would build a pattern of directories to include and would only scan/find directories under the nested `tests` folder that are not `support` or `factories`. For something that specific, I would imagine it would be much faster than 250-500ms.

If you have a sample wallaby config with such code and it's slow for you, please let us know and we'll take a look for you.

**Comment by Alexsey** [comment]
Thank you. If it would only execute the config once on wallaby start then it's not going to be an issue
