### ISSUE TITLE
multiple instances (nodejs)

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#265]
I have a project I'm working on which is a collection of (Git) submodules.  Each submodule has its own tests.  I was attempting to have a Wallaby config in each submodule, and multiple run configurations for each.  That worked ok--as long as I ran them one at a time.

If I attempted to have two instances of Wallaby going, it gets confused about what's what, and I get test failures in one tab which were actually supposed to run in a different tab.  And if Wallaby gets confused, I get confused.  If you need steps to reproduce, I can try.  It *may* have something to do with the use of `npm link`.

Mind you, having multiple instances running may be a rare use-case.

As a workaround, I decided on running with *one* Wallaby config file, which is in the project root.  This has the added bonus of ensuring I don't break my other submodules, since some depend on others.  The main drawback is since you end up lumping the contents of `node_modules` together, you're not necessarily guaranteed the tests will run against the dependency local to your submodule.  To mitigate the risk of false positives and hard-to-track-down failures, you'd need to:

- keep your dependency versions tightly in sync
- use a pre-commit hook which runs `npm test` (see package [pre-commit](https://www.npmjs.com/package/pre-commit))
- use CI

I'm fortunate I was doing these things before I tried to work around this issue.

For the curious, the resulting config `.js` looks like this:

```js
'use strict';

const path = require('path');
const dirpaths = [
  'digs',
  'digs-data',
  'digs-common',
  'digs-dev'
];

function joinDirpath() {
  const args = Array.prototype.slice.call(arguments);
  return dirpaths.map(function(dirpath) {
    return path.join.apply(null, [dirpath].concat(args));
  });
}

module.exports = function wallabyConfig() {
  const absoluteDirpaths = dirpaths.map(function(dirpath) {
    return path.resolve(__dirname, dirpath);
  });

  return {
    files: joinDirpath('lib', '**', '*.js')
      .concat(joinDirpath('test', '**', 'suites', '**', '*.js'))
      .concat(joinDirpath('test', '**', 'mocks', '**', '*.js')),
    tests: joinDirpath('test', '**', '*.spec.js'),
    env: {
      type: 'node',
      params: {
        env: 'NODE_PATH=' + absoluteDirpaths.map(function(dirpath) {
          return path.join(dirpath, 'node_modules');
        }).join(':')
      },
      runner: 'node'
    },
    testFramework: 'mocha',
    bootstrap: function bootstrap(wallaby) {
      require(require('path').join(wallaby.localProjectDir,
        'digs-dev',
        'test',
        'fixture'));
    }
  };
};
```

I was surprised I got this to work.  In the meantime, if anyone else is having a similar issue, try the setup above.  The key takeaway is the `NODE_PATH` environment variable (don't forget the colon delimiters).  Wallaby will attempt to look for `node_modules` in the root project directory, which is the parent directory of all the submodules.  In my case, this directory does not exist.  Instead, every submodule (defined by `dirpaths` above) has its own `node_modules` folder.  We have to add all those `node_modules` paths into the `NODE_PATH` env var, so `node` knows where to look.  Furthermore, it seems these *must* be absolute paths.  

It's also worth noting: the paths as defined in the `files` and `tests` properties look like they need to be relative to the project root.

- latest Wallaby (as of this writing)
- latest PyCharm (as of this writing)

**Comment by ArtemGovorov** [comment]
@boneskull It's a very nice solution you ended up with, I like it.

> multiple instances

It's not yet supported https://github.com/wallabyjs/public/issues/89

> `NODE_PATH`

Wallaby.js instruments source files to collect the code coverage, and because it's too expensive to copy over all `node_modules` to the folder with all these instrumented files, it looks for `node_modules` in the original root project directory.

`NODE_PATH` is a nice way to point wallaby (and any node app really) to some additional places for `node_modules`. It's described in [the docs as well](http://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder). Note that as an alternative to passing the `NODE_PATH` via the `params.env`, you may set the `process.env.NODE_PATH` right in the context of the config file (if it's easier).

> the paths as defined in the `files` and `tests` properties look like they need to be relative to the project root

More precisely, to the location of the config file where they are defined. But in the config itself going up with `..` is not yet supported - https://github.com/wallabyjs/public/issues/68

**Comment by boneskull** [comment]
Another weird thing I'm doing is putting suites in their own files.  The use case is that I have "abstract" factory functions (or "interfaces").  They are not used directly, but are rather used to compose other factory functions.  So, I want to run a common suite against any factory function which implements the interface in order to assert it does so correctly.  This means I need to re-use suites.

So for example, below is `suites/adapter.js`.  `digsLoggerSuite` is a suite function (this is the second parameter to Mocha's `describe()`) which asserts a function parameter (contained in `opts.func`) implements the `DigsLogger` factory interface.  It also passes `opts` through by returning it.  Then, I use LoDash's `_.flow()` to compose the `digsLoggerSuite` and the `digsAdapterSuite`.  In the test file itself (further below), I use `_.partial()` to "bind" the options to the composed function. 

```js
'use strict';

const digsLoggerSuite = require('digs-common/test/defines/suites/logger');
const _ = require('digs-common').utils;

function defaultAdapterSuite(opts) {
  opts = opts || {};
  let sandbox;
  const DefaultAdapter = opts.func;

  beforeEach(function() {
    sandbox = sinon.sandbox.create('DefaultAdapter');
  });

  afterEach(function() {
    sandbox.restore();
  });

  describe('initialization', function() {
    it('should be a function', function() {
      expect(DefaultAdapter).to.be.a('function');
    });
  });

  return opts;
}

module.exports = _.flow(digsLoggerSuite, defaultAdapterSuite);
```

and this is `adapter.spec.js`:

```js
'use strict';

const defaultAdapterSuite = require('./suites/adapter');
const DefaultAdapter = require('../lib/adapter');
const _ = require('digs-common').utils;

describe('DefaultAdapterSuite',
  _.partial(defaultAdapterSuite, {
    func: DefaultAdapter
  }));

```

* * *
But the problem is this:

It appears Wallaby wants something to be either a "file" or a "test".  `suites/adapter.js` is sort of both.  I can't add it to both lists, and if I omit it from "files" then I get this weird error out of `require()`:

```
Runtime error: TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (./digs-auth-device/test/suites/adapter.js:3:26)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/boneskull/Library/Caches/PyCharm40/wallaby/projects/23ce18a1e2d84780/instrumented/digs-auth-device/test/adapter.spec.js:3:43)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Array.forEach (native)
```

But if I remove it from tests, then I get a bunch of warnings about the test having no ID, and modifying the 
"suite" file does not cause Wallaby to re-run any tests.

**Comment by ArtemGovorov** [comment]
It's another known limitation - https://github.com/wallabyjs/public/issues/124. Wallaby requires test files to be entry points. In other words, everything with `describe/it` has to be listed in the `tests` property.

**Comment by boneskull** [comment]
I'm going to close this because it looks like it contains no less than three (3) dupes.
