### ISSUE TITLE
Run once on start

### ISSUE THREAD

**Issue by cmidgley** [wallabyjs/public#2653]
Is it possible to have Wallaby execute a function only once, when Wallaby is first started?  I do not want it to run when individual tests are run, just when Wallaby starts up (or is restarted).  I need this because I have a code and schema generator (Nexus/Prisma) that is very slow to run, and rarely needs to be used ... but it must be done once before any tests can be executed.  If I change the schema (nexus/graphql or prisma) I am hoping I could just restart Wallaby cause it to run.

I am using a custom configuration (not automatic) and a wallaby.js file.  I attempted to use startup() in wallaby.js, but that runs on every test execution.  I also attempted to use a static flag to track if the startup has already been run, but that doesn't work because the workers operate across multiple processes (and therefore the flag is not shared).  Using an external database or web service also doesn't work, as nothing would reset the flag upon Wallaby restarting.  Compilers and preprocessors have similar limitations - they run on every test, not just when Wallaby starts up.

Any hook I can use, or perhaps recommendations on how I might approach this?  My environment is Node / Typescript.

**Comment by smcenlly** [comment]
Yes - it is possible to only process your logic once. The code below shows one way of doing this:

**wallaby.js example**
```javascript
const process = require('process');

if (process.env.DO_ONCE) {
  process.env.DO_ONCE = true;
  // Logic to only process once...
}

module.exports = ({
  files: [
    'src/**/*.js',
    '!src/**/*.spec.js',
  ],

  tests: [
    'src/**/*.spec.js',
  ],

  env: {
    type: 'node'
  }
});
```
