### ISSUE TITLE
Automatic configuration ignoring files containing `[...` (e.g. Next.js catch-all routes)

### ISSUE THREAD

**Issue by tyom** [wallabyjs/public#2655]
c### Issue description or question

The default configuration is ignoring Next.js [dynamic catch-all routes](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes), e.g. `[...slug].js` for both test files and source files. When I rename the file to `[slug]` it works but I'd like the test file names to match 
the source file names.

Also, the source files are ignored from coverage even when the test files are renamed to something else.

I tried giving explicit node rules with custom globs, even with the full file name in the list of files and it still gets ignored.

### Wallaby diagnostics report

<details>
  <summary>See the diagnostic report</summary>
<pre>
{
  editorVersion: 'WebStorm 2021.1 EAP',
  pluginVersion: '1.0.213',
  editorType: 'IntelliJ',
  osVersion: 'darwin 20.3.0',
  nodeVersion: 'v12.20.1',
  coreVersion: '1.0.1043',
  checksum: 'NDRkMjlkMTQzN2YwZGYyN2YwOGYyYjgyYmNjNGRhZDcsMTYzMzU2NDgwMDAwMCww',
  config: {
    diagnostics: {
      jest: {
        config: {
          configs: [
            {
              automock: false,
              cache: true,
              cacheDirectory: '/private/var/folders/xg/5mh6_vg51fdc1p0h0c71ntw40000gn/T/jest_dx',
              clearMocks: false,
              coveragePathIgnorePatterns: [ '/node_modules/' ],
              cwd: '<homeDir>/Work/(REDUCTED)',
              dependencyExtractor: undefined,
              detectLeaks: undefined,
              detectOpenHandles: undefined,
              displayName: { color: 'white', name: 'Unit' },
              errorOnDeprecated: false,
              extraGlobals: [],
              filter: undefined,
              forceCoverageMatch: [],
              globalSetup: undefined,
              globalTeardown: undefined,
              globals: {},
              haste: { computeSha1: false, throwOnModuleCollision: false },
              injectGlobals: true,
              moduleDirectories: [ 'node_modules' ],
              moduleFileExtensions: [ 'js', 'json', 'jsx', 'ts', 'tsx', 'node' ],
              moduleLoader: undefined,
              moduleNameMapper: [
                [ '\\.(css)$', 'identity-obj-proxy' ],
                [ 'ip.json', '<homeDir>/Work/(REDUCTED)/src/__mocks__/ip.json' ],
                [ '\\.svg$', '<homeDir>/Work/(REDUCTED)/src/__mocks__/svg.json' ],
                [ 'alias/content-platform', '<homeDir>/Work/(REDUCTED)/src/content-platform/server.js' ],
                [ 'alias/article-gifting', '<homeDir>/Work/(REDUCTED)/src/lib/gifting/server.js' ],
                [ '^@/(.*)$', '<homeDir>/Work/(REDUCTED)/src/$1' ],
                [ '^@test/(.*)$', '<homeDir>/Work/(REDUCTED)/test/$1' ]
              ],
              modulePathIgnorePatterns: [],
              modulePaths: undefined,
              name: '09ce04e2562150d49cad9cddfb03a0fd',
              prettierPath: 'prettier',
              resetMocks: false,
              resetModules: false,
              resolver: undefined,
              restoreMocks: false,
              rootDir: '<homeDir>/Work/(REDUCTED)',
              roots: [ '<homeDir>/Work/(REDUCTED)' ],
              runner: 'jest-runner',
              setupFiles: [ '<homeDir>/Work/(REDUCTED)/node_modules/jest-date-mock/lib/index.js' ],
              setupFilesAfterEnv: [ '<homeDir>/Work/(REDUCTED)/test/jest.setup.js' ],
              skipFilter: false,
              skipNodeResolution: undefined,
              slowTestThreshold: 5,
              snapshotResolver: undefined,
              snapshotSerializers: [ '<homeDir>/Work/(REDUCTED)/node_modules/enzyme-to-json/serializer.js' ],
              testEnvironment: '<homeDir>/Work/(REDUCTED)/node_modules/jest-environment-jsdom/build/index.js',
              testEnvironmentOptions: {},
              testLocationInResults: false,
              testMatch: [ '<homeDir>/Work/(REDUCTED)/src/**/*.test.js' ],
              testPathIgnorePatterns: [ '/node_modules/' ],
              testRegex: [],
              testRunner: '<homeDir>/Work/(REDUCTED)/node_modules/jest-jasmine2/build/index.js',
              testURL: 'http://localhost',
              timers: 'real',
              transform: [
                [ '\\.js?$', '<homeDir>/Work/(REDUCTED)/node_modules/babel-jest/build/index.js', {} ],
                [ '\\.html$', '<homeDir>/Work/(REDUCTED)/node_modules/jest-raw-loader/index.js', {} ],
                [ '\\.gql$', '<homeDir>/Work/(REDUCTED)/node_modules/jest-raw-loader/index.js', {} ]
              ],
              transformIgnorePatterns: [ '/node_modules/(?!@(REDUCTED)).+\\.js$' ],
              unmockedModulePathPatterns: undefined,
              watchPathIgnorePatterns: []
            }
          ],
          globalConfig: {
            bail: 1,
            changedFilesWithAncestor: false,
            changedSince: undefined,
            collectCoverage: false,
            collectCoverageFrom: [
              'src/**/*.js',
              '!src/logger.js',
              '!src/server.js',
              '!src/server-local.js',
              '!src/request-handler.js',
              '!src/logger.js',
              '!src/pages/_app.js',
              '!src/__fixtures__/**',
              '!src/__mocks__/**',
              '!.next/',
              '!src/components-third-party/NewRelicScript.js',
              '!**/*.stories.js',
              '!src/lib/graphql-tag.js',
              '!src/assets.js',
              '!**/styles.js'
            ],
            collectCoverageOnlyFrom: undefined,
            coverageDirectory: '<homeDir>/Work/(REDUCTED)/coverage',
            coverageProvider: 'babel',
            coverageReporters: [ 'json', 'text', 'lcov', 'clover' ],
            coverageThreshold: { global: { branches: 100, functions: 100, lines: 100, statements: 100 } },
            detectLeaks: undefined,
            detectOpenHandles: undefined,
            enabledTestsMap: undefined,
            errorOnDeprecated: false,
            expand: false,
            filter: undefined,
            findRelatedTests: false,
            forceExit: false,
            globalSetup: undefined,
            globalTeardown: undefined,
            json: false,
            lastCommit: false,
            listTests: undefined,
            logHeapUsage: false,
            maxConcurrency: 5,
            maxWorkers: 7,
            noSCM: undefined,
            noStackTrace: false,
            nonFlagArgs: undefined,
            notify: false,
            notifyMode: 'failure-change',
            onlyChanged: false,
            onlyFailures: false,
            outputFile: undefined,
            passWithNoTests: undefined,
            projects: [],
            replname: undefined,
            reporters: [ [ 'default', {} ] ],
            rootDir: '<homeDir>/Work/(REDUCTED)',
            runTestsByPath: false,
            silent: undefined,
            skipFilter: false,
            testFailureExitCode: 1,
            testNamePattern: undefined,
            testPathPattern: '',
            testResultsProcessor: undefined,
            testSequencer: '<homeDir>/Work/(REDUCTED)/node_modules/@jest/test-sequencer/build/index.js',
            testTimeout: undefined,
            updateSnapshot: 'new',
            useStderr: false,
            verbose: undefined,
            watch: false,
            watchAll: false,
            watchPlugins: undefined,
            watchman: true
          },
          hasDeprecationWarnings: false,
          wallaby: {
            roots: [],
            watchPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testPathIgnorePatterns: [ '/node_modules/', '\\./dist/|\\./build/|\\./coverage/|/\\..+/' ],
            testMatch: [ 'src/**/*.test.js' ],
            testRegex: []
          }
        }
      }
    },
    testFramework: { version: 'jest@24.8.0', configurator: 'jest@24.8.0', reporter: 'jest@24.8.0', starter: 'jest@24.8.0', autoDetected: true },
    filesWithCoverageCalculated: [
      'src/**/*.js',
      '!src/logger.js',
      '!src/server.js',
      '!src/server-local.js',
      '!src/request-handler.js',
      '!src/logger.js',
      '!src/pages/_app.js',
      '!src/__fixtures__/**',
      '!src/__mocks__/**',
      '!.next/',
      '!src/components-third-party/NewRelicScript.js',
      '!**/*.stories.js',
      '!src/lib/graphql-tag.js',
      '!src/assets.js',
      '!**/styles.js'
    ],
    filesWithNoCoverageCalculated: [],
    globalSetup: false,
    micromatch: true,
    files: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true },
      { pattern: '**/**', ignore: false, trigger: true, load: true, order: 1 },
      { pattern: 'src/**/*.test.js', ignore: true, trigger: true, load: true }
    ],
    tests: [
      { pattern: '/node_modules/', regexp: /\/node_modules\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: '\\./dist/|\\./build/|\\./coverage/|/\\..+/', regexp: /\.\/dist\/|\.\/build\/|\.\/coverage\/|\/\..+\//, ignore: true, trigger: true, load: true, test: true },
      { pattern: 'src/**/*.test.js', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: {},
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    extensions: {},
    env: { type: 'node', params: {}, runner: '/usr/local/bin/node', viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: true,
    configCode: 'auto.detect#154281597'
  },
  packageJSON: {
    // REDUCTED
  },
  fs: { numberOfFiles: 3742 },
  debug: [
    '2021-03-10T16:10:21.300Z angular/cli config Angular CLI not found.\n',
    '2021-03-10T16:10:21.383Z jest/config Detected Jest.\n',
    '2021-03-10T16:10:21.383Z jest/config Configured Jest.\n',
    '2021-03-10T16:10:21.384Z project Wallaby Node version: v12.20.1\n',
    '2021-03-10T16:10:21.384Z project Wallaby config: <homeDir>/Work/(REDUCTED)/auto.detect\n',
    '2021-03-10T16:10:22.750Z project File cache: <homeDir>/Library/Caches/JetBrains/WebStorm2021.1/wallaby/projects/67e8fa6b1c049c85\n',
    '2021-03-10T16:10:23.462Z uiService Listening port 51235\n',
    '2021-03-10T16:10:23.651Z workers Parallelism for initial run: 6, for regular run: 3\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #0\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #1\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #2\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #3\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #4\n',
    '2021-03-10T16:10:23.651Z workers Starting run worker instance #5\n',
    '2021-03-10T16:10:23.656Z workers Web server is listening at 56351\n',
    '2021-03-10T16:10:23.811Z project Stopping process pool\n',
    '2021-03-10T16:10:23.811Z project File cache is up-to-date, starting full test run\n',
    '2021-03-10T16:10:23.830Z project Test run started; run priority: 3\n',
    '2021-03-10T16:10:23.848Z project Running all tests\n',
    '2021-03-10T16:10:23.914Z workers Starting test run, priority: 3\n',
    '2021-03-10T16:10:23.914Z nodeRunner Starting sandbox [worker #0, session #tea47]\n',
    '2021-03-10T16:10:23.914Z nodeRunner Preparing sandbox [worker #0, session #tea47]\n',
    '2021-03-10T16:10:23.928Z workers Started run worker instance (delayed) #0\n',
    '2021-03-10T16:10:23.929Z nodeRunner Prepared sandbox [worker #0, session #tea47]\n',
    '2021-03-10T16:10:23.929Z workers [worker #0, session #tea47] Running tests in sandbox\n',
    '2021-03-10T16:10:23.940Z workers Started run worker instance (delayed) #1\n',
    '2021-03-10T16:10:23.940Z workers Started run worker instance (delayed) #2\n',
    '2021-03-10T16:10:23.948Z workers Started run worker instance (delayed) #4\n',
    '2021-03-10T16:10:23.949Z workers Started run worker instance (delayed) #3\n',
    '2021-03-10T16:10:23.966Z workers Started run worker instance (delayed) #5\n',
    '2021-03-10T16:10:25.904Z workers Scheduling Jest Test Run: 2021-03-10T16:10:24.214Z\n',
    '2021-03-10T16:10:25.904Z workers [tea47] Loaded unknown number of test(s)\n',
    '2021-03-10T16:10:25.904Z workers [tea47] Test executed: placeholder\n',
    '2021-03-10T16:10:25.965Z workers [tea47] Run 1 test(s), skipped 0 test(s)\n',
    '2021-03-10T16:10:25.966Z workers Jest Test Run Complete: 2021-03-10T16:10:25.903Z\n',
    '2021-03-10T16:10:25.967Z workers [tea47] Sandbox is responsive, closing it\n',
    '2021-03-10T16:10:25.968Z project Test run finished\n',
    '2021-03-10T16:10:25.968Z project Processed console.log entries\n',
    '2021-03-10T16:10:25.968Z project Processed loading sequences\n',
    '2021-03-10T16:10:25.968Z project Processed executed tests\n',
    '2021-03-10T16:10:26.001Z project Processed code coverage\n',
    '2021-03-10T16:10:26.129Z project Test run result processed and sent to IDE\n'
  ]
}
</pre>
</details>

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, `v1.0.1044`.

Wallaby should automatically update for you but if it does not or you want to update immediately, please close all instances of your editor and re-open and Wallaby will update for you.
