### ISSUE TITLE
Jest globalSetup not working per-process

### ISSUE THREAD

**Issue by cmidgley** [wallabyjs/public#2660]
### Issue description or question

Jest has a feature called `globalSetup` that is supposed to run a default exported function from a file, once (and only once) per process.  This works as expected when running outside Wallaby (including with watcher).  

When executing inside Wallaby, upon startup only one process (the first one) has `globalSetup` called.  Further, on later runs (such as after a file is modified) `globalSetup` is executed again, even though the process has executed it previously.

This is should be easily reproduced, such as this TypeScript async example (I did async because that what I must do in my use case, just in case that matters)

`global-setup.ts`:
```
export default async function globalSetupTest(): Promise<void> {
  console.log(`Inside global setup, in process ${process.pid}`);
}
```

`jest.config.js`:
```
...
globalSetup: './global-setup.ts',
...
```

The result, at least as I see it, is just one console.log when multiple processes are executed.  And when a Wallaby action is given which causes a test to execute, the code will run again using the same process ID as before.

Expected behavior would have been to see the console message once per process started, and then upon future Wallaby actions no more console logs (unless a new process is started).

**Comment by cmidgley** [comment]
See #2663 - these issues seem very related.  I'm starting to see that a process can be reused, yet the JS engine has a different memory space, so perhaps ignore the process comments but the globalSetup not executing as expected still remains.

**Comment by smcenlly** [comment]
> Jest has a feature called globalSetup that is supposed to run a default exported function from a file, once (and only once) per process. This works as expected when running outside Wallaby (including with watcher).

The [jest docs](https://jestjs.io/docs/configuration#globalsetup-string) do not describe any per-process behavior for `globalSetup` or `globalTeardown`. What they do say:

> [Global setup] is triggered once before all test suites.
> A global setup module configured in a project [...] will be triggered only when you run at least one test from this project.

and

> [Global teardown] is triggered once after all test suites.
> A global teardown module configured in a project [...] will be triggered only when you run at least one test from this project.

When you change your code or manually start a test run, Wallaby starts a new test run (even though it reuses processes). For each test run, global setup will be executed before running your tests and global teardown will be executed after running your tests. Please note as per #2663 that global teardown is not guaranteed; nor is global teardown execution guaranteed by jest. 

Unless there is other jest documentation that we're not aware of describing per-process behavior, there is no mention of how `globalSetup` / `globalTeardown` are expected to behave when processes are reused or where multiple processes are used to run your tests (as Wallaby is doing).

As mentioned in #2663 - you may use Wallaby's [worker settings](https://wallabyjs.com/docs/config/workers.html) restart flag to make Wallaby start a new process each time, but we recommend updating your setup/teardown logic to be tolerant of the process being reused.

**Comment by cmidgley** [comment]
Similar to my other comment on #2663, I basically disagree.  There is an assumption in Jest that you run in a process, you get the `globalSetup`, and if you don't get a `globalTeardown`, it's also because your process is dead.  In Jest, I receive a `globalSetup` just once for each process executing.  In Wallaby, I receive only one `globalSetup` across all the processes, and then I receive it again, in process that has already received a `globalSetup` anytime another test runs.  This is a very different behavior.

I do agree that their documentation is lacking, but the behavior is the point.  For Wallaby to be able to execute tests that jest does natively, it needs to mirror the process that Jest executes.  

Now ... having said that, I see where Wallaby has a serious problem with `globalTeardown`!  There is no "end of test" and therefore, no point in time that it makes sense to call it.  In this case, my perspective is that `globalStartup` should be called once, as any new process is started, and `globalTeardown` like just ignored (kill the process when done). 

Now for me, I've worked around this issue (this one was easy, I just have beforeAll use a singleton pattern to initialize), so this isn't a big deal.  But I wanted to reinforce this point wrt #2663 where the best case is one where Wallaby mirror the **behavior** of Jest, and not just the (poor/incomplete) documentation.

Thanks again for your awesome support.

**Comment by smcenlly** [comment]
> Similar to my other comment on #2663, I basically disagree.

I think we'll have to agree to disagree. Unfortunately we have many customers who rely on the current behavior now so it's definitely not something we can change. We did a lot of thinking on the behavior prior to implementing support for jest's `globalSetup` and `globalTeardown` and the implementation also was non-trivial. Basically, we opted for the case where Wallaby can run as fast as possible for those who don't rely on some global state being bound to a process, BUT we still have options for people who do need process-specific behavior (which I'll get to in terms of how you may implement your configuration). We would rather Wallaby run in ~200ms for most users with setup/teardown and not recycle processes vs. always recycle the process and have large over head for each test run. i.e. make Wallaby as fast as possible for the largest number of people, yet still support those cases where something more is required.

> There is no "end of test" [for Wallaby]

From Wallaby perspective (our perspective insofar as what we consider a test run), a test run finishes when Wallaby reports results back to your editor. It is at this point that Wallaby's own [teardown](https://wallabyjs.com/docs/config/bootstrap.html#teardown-function) method gets called, and the same was replicated when we added support for jest (calling jest globalTeardown). Our concept of a when a test starts/finishes has always been the same.

--

I definitely think we could beef up our own documentation to describe various use cases for jest global setup and what to do (I'll add to our backlog).

--

If you truly want something to be alive for the entire time that Wallaby is running then I recommend using the example below as a starting point. You may need to update your jest globalSetup / globalTearDown to be aware of Wallaby context:

**wallaby.js configuration file**
```javascript
if (!process.env.WALLABY_GLOBAL) {
  process.env.WALLABY_GLOBAL = true;
  // setup database, etc. - note that there is no "teardown" equivalent of doing this
  // but if your code is happy to survive sudden process terminations, there is no problem
}

module.exports = ({
  autoDetect: true
});
```

**jest globalSetup / globalTeardown files**
```javascript
if (process.env.WALLABY_GLOBAL) {
  // do not do any processing that would be done in the Wallaby configuration
}
```

**Comment by ArtemGovorov** [comment]
@cmidgley 

I can't seem to reproduce the behaviour that you are describing:

> Jest has a feature called globalSetup that is supposed to run a default exported function from a file, once (and only once) per process.
> In Jest, I receive a globalSetup just once for each process executing.

in Jest CLI. I have a simple app with `globalSetup` file and 2 tests. I run Jest in watch mode and from what I see, Jest does run `globalSetup` function in the same one process multiple times:

![jp](https://user-images.githubusercontent.com/979966/111248639-08548b80-8656-11eb-955b-f62b48e97341.gif)

As you may see in the video, I save the test file and `globalSetup` is executing multiple times in the same process because the process id is the same and the date changes.

**Comment by cmidgley** [comment]
Thanks - and clearly I was wrong / you are correct here.  I've added more comments (and a new question) on this at #2663 but the issue for me I believe has been a misunderstanding on how process space is used by JS VM's.  Even if that is wrong, we can complete the discussion over on #2663.  

I am so impressed with the time and effort you and the team at Wallaby spend on supporting your customers.  Thank you!
