### ISSUE TITLE
Feature Request: Additional code lens features

### ISSUE THREAD

**Issue by cmidgley** [wallabyjs/public#2664]
### Feature Request

I constantly run up again having to click the space bar or do unnecessary change to the test to cause it to run.  While Wallaby does a great job of figuring out when to run a test when I'm editing tests, it doesn't know about external events - which in my case is an external database and a web service.  When I change something in those external services, I wish I could easily click a "run test" code lens.   It seems natural to me that the code lens could offer Run in additional to Debug, View Story, Profile and Focus.

It would also be nice to be able to launch the test using the real VS Code debugger, rather than the Wallaby one.  I'm finding the Wallaby "debugger" doesn't meet my needs, and frequently have to stop Wallaby, start the debugger, start up my test, and then debug it.  I used to use an add-in for VS Code that offered these two features, and there were great - it would be wonderful if Wallaby could offer similar functionality.  Personally, I find calling the Time Travel Debugger "debug" confusing - as it really isn't debugging the code, it's an entirely unique concept.  

So I'd love to see: "Run | Debug | Time Travel | View Story | Profile | Focus"

**Comment by smcenlly** [comment]
> I constantly run up again having to click the space bar or do unnecessary change to the test to cause it to run. While Wallaby does a great job of figuring out when to run a test when I'm editing tests, it doesn't know about external events - which in my case is an external database and a web service. When I change something in those external services, I wish I could easily click a "run test" code lens. It seems natural to me that the code lens could offer Run in additional to Debug, View Story, Profile and Focus.

Wallaby already has a command that allows you to do this: `Wallaby.js: Run Line Tests` (keyboard shortcut: `ctrl+shift+r c`).

You may use this command from within a test file or within your application code on any line that has a code coverage indicator and Wallaby will run the test(s) associated with that line of code. The only caveat with this command is that any tests that are run will also update their snapshots if you use snapshot testing. At this point in time, we do not want to add this as a code-lens option as the normal behavior for most people is to not need this command (although it does have a shortcut). We are mindful of not providing too many options in the editor that would act as a distraction.

> It would also be nice to be able to launch the test using the real VS Code debugger, rather than the Wallaby one. I'm finding the Wallaby "debugger" doesn't meet my needs, and frequently have to stop Wallaby, start the debugger, start up my test, and then debug it. I used to use an add-in for VS Code that offered these two features, and there were great - it would be wonderful if Wallaby could offer similar functionality. Personally, I find calling the Time Travel Debugger "debug" confusing - as it really isn't debugging the code, it's an entirely unique concept.

Unfortunately this isn't something that we can easily provide and we're not sure where exactly this would be able to fit in terms of our upcoming roadmap for 2021.

**Comment by cmidgley** [comment]
Understood.  Thanks for the consideration and time responding.

**Comment by cmidgley** [comment]
I feel bad reopening this as I understand it's an issue of balancing usability with features, and you guys have done a fantastic job walking that tightrope.  However after a bunch of dedicated time using Wallaby, I think there remains a strong argument for a code lens for "Run" to trigger a run single line operation and I don't think I did a decent job explaining it before.  It certainly does depend on your use case, as simple, responsive uses don't need it.  But I think there are many that cause it to be frequently used - way more than the other code lens options offered today.  

Here are a few cases for why you might need to use :
- When you set `runMode` to `onsave`, yet want to run a test without persisting it to disk (very cool!)
- Any test that consumes an external service (web service, etc) often needs multiple by-hand test runs
- Any test that has dynamically changing content, like time-of-day, random numbers, UUID, etc.
- Any test that consumes information that Wallaby doesn't detect as trigging change, like i18n resource files or config files
- Any time you are trying to debug something with inconsistent behaviors
- Any time you use `runAllTestsInAffectedFiles` set to false
- When Wallaby doesn't correctly detect the changed files

In my case, I actually have every single one of those issues above, and I find I run single line tests constantly and very rarely use the other code lens options (profile and focus being the most used, rarely debug or view story).  

So why not just use Run Line Tests, perhaps mapping it to a single shortcut key?  
- If you have the wrong window in context, say the output window, Wallaby runs all tests
- If you have the wrong cursor location, Wallaby runs file or all tests

Now these last points about run line test might not be an issue if your test suite was fast and small.  But in my case, it runs over 100 tests (growing rapidly to many hundreds) that both take a long time to run (15 seconds for all vs. 1.5 seconds for a single test), and hammer all 16 cores on my laptop and my battery life drops to under an hour when lots of tests are running.  Due to these issues, I rarely use `runMode` of `automatic` (except when working on very specific test cases) so I'd really love the quick-and-easy "run" code lens!  

Of note, I see in config you can disable code lenses.  A possible solution is to expand that to let us select which code lenses we want (or don't want) and default to whatever set makes the best sense for the Wallaby default install.

Thanks for your consideration again.  I understand if it still doesn't fit your vision, but I at least wanted to make a more informed argument for why I think it's important!

**Comment by cmidgley** [comment]
And one more ... this is likely a bug but I find there where my cursor is within my test code changes if the entire file is run or just my test.  For example, if I'm on the word "catch" in try/catch block, the entire file runs.  But if my cursor is on an individual code line, it runs just the test (this is true even with Focus on).  

I'd like the Run code lens to run this one test, and only this one test, and not attempt to analyze any other possible tests to run.

**Comment by smcenlly** [comment]
We've added a new `Run` code action above test declaration line for VS Code:

![image](https://user-images.githubusercontent.com/2074089/112237320-29d4f900-8c8e-11eb-8f67-610dacb68bc6.png)

We have also updated Wallaby's code lens settings to be more granular (they are now specified per code lens action). You can access these from VS Code settings or via Wallaby's start view:

![image](https://user-images.githubusercontent.com/2074089/112237452-6d2f6780-8c8e-11eb-971e-52519f5240ab.png)

**Comment by cmidgley** [comment]
You guys totally rock!
