### ISSUE TITLE
runMode configuration with Value Explorer and Test Stories

### ISSUE THREAD

**Issue by gitrojones** [wallabyjs/public#2670]
### Issue description or question
With runMode set to automatic, value explorer and test stories work as documented. However, with runMode set to onsave, these features behave in a non-intuitive way that isn't documented anywhere. The problem is more obvious in test stories where the requirement to save before a value can be explored makes value exploring within test stories impossible.

Once you realize the reason for these features not working is due to the save cycle it isn't such a mystery; however, I've been using Wallaby for over a year now and had no idea why the value explorer never seemed to function properly. I chalked it up to being a second-class feature for IntelliJ and never thought more of it until Test Stories were introduced and that too seemed to be non-functional (this time as an announced feature).

Ideally, wallaby would behave like runMode set to automatic for Value Explorer operations. Alternatively, Test Stories should behave like runMode is set to automatic or expose a context option to view a selected value as the current behavior greatly reduces it's utility. At a minimum, this behavior should be documented on the FAQ/Troubleshooting section. I'm sure i'm not the only one who has experienced this problem.

Perhaps there's an opportunity to expand the runMode options to be a bit more flexible?

### Wallaby diagnostics report

The diagnostics report doesn't get saved to my clipboard. Is there an alternate way to generate this?

Running the latest version of Wallaby (1.0.213).

IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.15-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 8019M
Cores: 16
Registry: undo.documentUndoLimit=10000, undo.globalUndoLimit=100
Current Desktop: i3

**Comment by smcenlly** [comment]
Thanks for reporting your problem. This sounds like something that we may need to fix. We'll do some investigation and get back to you.

**Comment by ArtemGovorov** [comment]
The issue has been fixed and the fix is published in [the latest core v1.0.1051](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
