### ISSUE TITLE
Jasmine spy error when run from wallaby

### ISSUE THREAD

**Issue by crfrolik** [wallabyjs/public#2673]
### Wallaby diagnostics report

Using Jasmine `spyOn(...).and.rejectWith(...)` throws an error when run from wallaby.
```
TypeError: spy.and.rejectWith is not a function
```

When run outside of wallaby, this does not happen.

Here is my `wallaby.js`:

```
module.exports = function (w) {
  return {
    files: [
      'src/**/*.ts',
      { pattern: 'src/**/*.spec.ts', ignore: true }
    ],

    tests: [
      'src/**/*.spec.ts'
    ],

    env: {
      type: 'node'
    },

    testFramework: 'jasmine'
  };
};
```

"Copy Diagnostic Report" does not put anything on the clipboard; please help.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in Wallaby core `v1.0.1053`.

If Wallaby does not automatically update for you with the latest version, you may [perform a force core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
