### ISSUE TITLE
wallabyjs Changelog

### ISSUE THREAD

**Issue by Faq** [wallabyjs/public#2682]
Hello, 
Just want to know where would be possible to see actual change log?

[This one is outdated](https://github.com/wallabyjs/public/blob/master/CHANGELOG.md) as there is last VS Code 1.0.262, but as we see [here](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode) yesterday was released 1.0.282, so linked change log is a bit outdated.

Is there some any other place to check?

**Comment by ArtemGovorov** [comment]
Hello,

Our changelog at https://github.com/wallabyjs/public/blob/master/CHANGELOG.md is updated every few months, while we release new versions of wallaby.js a few times a week (sometimes a few times a day), so the formal changelog is always behind a bit.

For more frequent significant changes updates between the detailed changelog updates, you may:
- check out our ~weekly updated `What's New` section on [the website](https://wallabyjs.com/whatsnew/) or in [the docs](https://wallabyjs.com/docs/intro/whatsnew.html).
- [follow us on Twitter](https://twitter.com/wallabyjs) where we also post about significant changes.

If you have any other/specific questions, please feel free to ask them here or send us an email to hello@wallabyjs.com, we are happy to help.
