### ISSUE TITLE
Can't get Wallaby to use Node without explicit reference

### ISSUE THREAD

**Issue by andrewryan1906** [wallabyjs/public#2683]
### Issue description or question

I cant’ get Wallaby to use Node 14. I’ve use nvm use and nvm alias default to set the default node. My WebStorm is set to use Node 14. But I can’t get Wallaby to use unless I have this wallaby.js file:

```
module.exports = function () {
    return {
        files: [
            'config.js',
            'src/**/*.js',
            'tests/json/**/*',
        ],

        tests: [
            'tests/unit/**/*spec.js'
        ],
        testFramework: 'mocha',
        setup: function () {
            global.expect = require('chai').expect;
        },
        env: {
            type: 'node',
            runner: require('os').homedir() + '/.nvm/versions/node/v14.16.0/bin/node'
        }
    };

};
```

**Comment by smcenlly** [comment]
You should be able to configure which version of `node` to use in your Wallaby Run Configuration. Did you try that (see screenshot below). Please note that the `{SYSTEM DEFAULT}` setting will use the version of node found by your system's path resolution, **not** the version of node specified in your WebStorm `Node.js and NPM` settings.

![image](https://user-images.githubusercontent.com/2074089/114324384-fab6f680-9b6c-11eb-8850-242ec6017f85.png)
