### ISSUE TITLE
Angular Workspaces with Jest not working.

### ISSUE THREAD

**Issue by Makepool** [wallabyjs/public#2686]
### Issue description or question

I'm using Angular 11 with Jest 26 and Wallaby doesn't run, instead it just give the error message shown below. We're using Angular workspaces, I'm not sure if that has something to do with this.

### Wallaby diagnostics report

‍[Info]  Started Wallaby.js Core v1.0.1060
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: ENOENT: no such file or directory, open '.\projects\ng-sova\src\test.ts'
 
[Error] 
 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks
 
[Error] Automatic Jest configuration error: Failed to read Jest configuration from '.': ● Validation Error: 
[Error]   Preset jest-preset-angular not found. 
[Error]   Configuration Documentation: 
[Error]   https://jestjs.io/docs/configuration.html

**Comment by Makepool** [comment]
‍[Info]  2021-04-14T12:18:30.626Z angular/cli config Detecting Angular CLI.
[Info]  2021-04-14T12:18:30.628Z angular/cli config Detected Angular CLI.
[Info]  Started Wallaby.js Core v1.0.1060
[Info]  2021-04-14T12:18:30.631Z angular/cli jest project config Configuring.
[Info]  2021-04-14T12:18:30.700Z angular/cli config Error: Failed to read Jest configuration from 'C:\Dev\frontend': ● Validation Error:
[Info]    Preset jest-preset-angular not found.
[Info]    Configuration Documentation:
[Info]    https://jestjs.io/docs/configuration.html
[Info]      at Object.<anonymous> (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:29:8839)
[Info]      at n (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:25337)
[Info]      at Object.throw (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24632)
[Info]      at a (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24445)
[Info]  2021-04-14T12:18:30.701Z angular/cli config Angular.json: 
[Info]   {
[Info]    '$schema': './node_modules/@angular/cli/lib/config/schema.json',
[Info]    version: 1,
[Info]    newProjectRoot: 'projects',
[Info]    projects: {
[Info]      assessor: {
[Info]        projectType: 'application',
[Info]        schematics: { '@schematics/angular:component': { style: 'scss' } },
[Info]        root: 'projects/assessor',
[Info]        sourceRoot: 'projects/assessor/src',
[Info]        prefix: 'app',
[Info]        architect: {
[Info]          build: {
[Info]            builder: '@angular-devkit/build-angular:browser',
[Info]            options: {
[Info]              outputPath: 'dist/assessor',
[Info]              index: 'projects/assessor/src/index.html',
[Info]              main: 'projects/assessor/src/main.ts',
[Info]              polyfills: 'projects/assessor/src/polyfills.ts',
[Info]              tsConfig: 'projects/assessor/tsconfig.app.json',
[Info]              aot: true,
[Info]              assets: [ 'projects/assessor/src/assets' ],
[Info]              styles: [ 'projects/assessor/src/styles.scss' ],
[Info]              stylePreprocessorOptions: { includePaths: [ 'projects/ng-sova/components/theme' ] },
[Info]              scripts: [],
[Info]              allowedCommonJsDependencies: [ 'qrcode' ]
[Info]            },
[Info]            configurations: {
[Info]              production: {
[Info]                fileReplacements: [ { replace: 'projects/assessor/src/environments/environment.ts', with: 'projects/assessor/src/environments/environment.prod.ts' } ],
[Info]                optimization: true,
[Info]                outputHashing: 'all',
[Info]                sourceMap: false,
[Info]                namedChunks: false,
[Info]                extractLicenses: true,
[Info]                vendorChunk: false,
[Info]                buildOptimizer: true,
[Info]                budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
[Info]              },
[Info]              staging: { fileReplacements: [ { replace: 'projects/assessor/src/environments/environment.ts', with: 'projects/assessor/src/environments/environment.staging.ts' } ] }
[Info]            }
[Info]          },
[Info]          serve: {
[Info]            builder: '@angular-devkit/build-angular:dev-server',
[Info]            options: { browserTarget: 'assessor:build' },
[Info]            configurations: { production: { browserTarget: 'assessor:build:production' }, staging: { browserTarget: 'assessor:build:staging' } }
[Info]          },
[Info]          'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'assessor:build' } },
[Info]          lint: {
[Info]            builder: '@angular-devkit/build-angular:tslint',
[Info]            options: { tsConfig: [ 'projects/assessor/tsconfig.app.json', 'projects/assessor/tsconfig.spec.json', 'projects/assessor/e2e/tsconfig.json' ], exclude: [ '**/node_modules/**' ] }
[Info]          }
[Info]        }
[Info]      },
[Info]      portal: {
[Info]        projectType: 'application',
[Info]        schematics: { '@schematics/angular:component': { style: 'scss' } },
[Info]        root: 'projects/portal',
[Info]        sourceRoot: 'projects/portal/src',
[Info]        prefix: 'app',
[Info]        architect: {
[Info]          build: {
[Info]            builder: '@angular-devkit/build-angular:browser',
[Info]            options: {
[Info]              outputPath: 'dist/portal',
[Info]              index: 'projects/portal/src/index.html',
[Info]              main: 'projects/portal/src/main.ts',
[Info]              polyfills: 'projects/portal/src/polyfills.ts',
[Info]              tsConfig: 'projects/portal/tsconfig.app.json',
[Info]              aot: true,
[Info]              assets: [ 'projects/portal/src/assets' ],
[Info]              styles: [ 'projects/portal/src/assets/styles/styles.scss', './node_modules/quill/dist/quill.core.css', './node_modules/quill/dist/quill.snow.css' ],
[Info]              stylePreprocessorOptions: { includePaths: [ 'projects/ng-sova/components/theme' ] },
[Info]              scripts: [ './node_modules/quill/dist/quill.min.js' ],
[Info]              allowedCommonJsDependencies: [ 'zone.js', 'moment-timezone', 'qrcode' ]
[Info]            },
[Info]            configurations: {
[Info]              production: {
[Info]                fileReplacements: [ { replace: 'projects/portal/src/environments/environment.ts', with: 'projects/portal/src/environments/environment.prod.ts' } ],
[Info]                optimization: true,
[Info]                outputHashing: 'all',
[Info]                sourceMap: false,
[Info]                namedChunks: false,
[Info]                extractLicenses: true,
[Info]                vendorChunk: false,
[Info]                buildOptimizer: true,
[Info]                budgets: [ { type: 'initial', maximumWarning: '2mb', maximumError: '5mb' }, { type: 'anyComponentStyle', maximumWarning: '6kb', maximumError: '10kb' } ]
[Info]              },
[Info]              staging: { fileReplacements: [ { replace: 'projects/portal/src/environments/environment.ts', with: 'projects/portal/src/environments/environment.staging.ts' } ] }
[Info]            }
[Info]          },
[Info]          serve: {
[Info]            builder: '@angular-devkit/build-angular:dev-server',
[Info]            options: { browserTarget: 'portal:build', port: 4500 },
[Info]            configurations: { production: { browserTarget: 'portal:build:production' }, staging: { browserTarget: 'portal:build:staging' } }
[Info]          },
[Info]          'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'portal:build' } },
[Info]          lint: {
[Info]            builder: '@angular-devkit/build-angular:tslint',
[Info]            options: { tsConfig: [ 'projects/portal/tsconfig.app.json', 'projects/portal/tsconfig.spec.json', 'projects/portal/e2e/tsconfig.json' ], exclude: [ '**/node_modules/**' ] }
[Info]          }
[Info]        }
[Info]      },
[Info]      'ng-sova': {
[Info]        projectType: 'library',
[Info]        root: 'projects/ng-sova',
[Info]        sourceRoot: 'projects/ng-sova',
[Info]        prefix: 'sova',
[Info]        architect: {
[Info]          build: {
[Info]            builder: '@angular-devkit/build-angular:ng-packagr',
[Info]            options: { tsConfig: 'projects/ng-sova/tsconfig.lib.json', project: 'projects/ng-sova/ng-package.json' },
[Info]            configurations: { production: { tsConfig: 'projects/ng-sova/tsconfig.lib.prod.json' } }
[Info]          },
[Info]          test: { builder: '@angular-builders/jest:run' },
[Info]          lint: {
[Info]            builder: '@angular-devkit/build-angular:tslint',
[Info]            options: { tsConfig: [ 'projects/ng-sova/tsconfig.lib.json', 'projects/ng-sova/tsconfig.spec.json' ], exclude: [ '**/node_modules/**' ] }
[Info]          }
[Info]        }
[Info]      }
[Info]    },
[Info]    defaultProject: 'ng-sova'
[Info]  }
[Info]  2021-04-14T12:18:30.701Z angular/cli config Error: Failed to read Jest configuration from 'C:\Dev\frontend': ● Validation Error:
[Info]    Preset jest-preset-angular not found.
[Info]    Configuration Documentation:
[Info]    https://jestjs.io/docs/configuration.html
[Info]      at Object.<anonymous> (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:29:8839)
[Info]      at n (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:25337)
[Info]      at Object.throw (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24632)
[Info]      at a (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24445)
[Info]  2021-04-14T12:18:30.702Z jest/config Detecting Jest.
[Info]  2021-04-14T12:18:30.703Z jest/config Error: Failed to read Jest configuration from 'C:\Dev\frontend': ● Validation Error:
[Info]    Preset jest-preset-angular not found.
[Info]    Configuration Documentation:
[Info]    https://jestjs.io/docs/configuration.html
[Info]      at Object.<anonymous> (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:29:8839)
[Info]      at n (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:25337)
[Info]      at Object.throw (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24632)
[Info]      at a (c:\Users\makep\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.284\wallabyc80619\server.js:28:24445)
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Failed to read Jest configuration from '.': ● Validation Error: 
[Error]   Preset jest-preset-angular not found. 
[Error]   Configuration Documentation: 
[Error]   https://jestjs.io/docs/configuration.html 
[Error] 
 
[Error] 
 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks
 
[Error] Automatic Jest configuration error: Failed to read Jest configuration from '.': ● Validation Error: 
[Error]   Preset jest-preset-angular not found. 
[Error]   Configuration Documentation: 
[Error]   https://jestjs.io/docs/configuration.html 
[Info]  2021-04-14T12:18:30.708Z extended-core Setting preferences

**Comment by ArtemGovorov** [comment]
Can you please share your Wallaby Diagnostics Report? To share the report:

- start Wallaby in your project;
- wait until it reports some results/errors;
- execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
- paste generated report as a response in this issue.

**Comment by smcenlly** [comment]
Please also note that Wallaby automatic configuration for any project using Jest (including Angular projects) requires jest to be able to run from your project root using `npx jest`. Could you please confirm that `npx jest` from your project root is working for you?

**Comment by smcenlly** [comment]
I'm going to close this issue since we haven't heard back. We're assuming that you got this working. If not, please let us know and provide us with the additional detail suggested and we'll re-open this issue.
