### ISSUE TITLE
Feature request: Add a 'Restart' option to the Wallaby commands in VS Code

### ISSUE THREAD

**Issue by 8enSmith** [wallabyjs/public#2690]
### Issue description or question

I often find myself using the "Wallaby.js: Stop" and "Wallaby.js: Start" commands if I encounter odd Wallaby behaviour (e.g. if I rename a TypeScript variable in VS Code I find that Wallaby doesn't handle the change and I need to restart - probably worth raising in another ticket!).

Hence instead of having to use two commands to restart Wallaby I'd like to have one 'Restart' command i.e. "Wallaby.js: Restart"

**Comment by ArtemGovorov** [comment]
"Wallaby.js: Start" command should do the trick for you - if Wallaby is running, the command restarts it.

> (e.g. if I rename a TypeScript variable in VS Code I find that Wallaby doesn't handle the change and I need to restart - probably worth raising in another ticket!).

Yes, please create a new issue for it, it is not something that we have seen before.
