### ISSUE TITLE
Wallaby ignores babel plugins with react-app-rewired

### ISSUE THREAD

**Issue by Esya** [wallabyjs/public#2692]
### Issue description or question

I was using the automatic configuration until now in my react project, and had to add [react-app-rewired](https://github.com/timarney/react-app-rewired) to add a new babel plugin that I need for certain mocks.

You can [see the repository here](https://github.com/Esya/oasis-wallet/tree/feat/genesis-on-network-selector) as it is public (if you try running the tests, the issue is only on this branch for now)

I tried writing a manual configuration, but could never get it to work - the plugin that I'm trying to add is never found when running wallaby : 

```  
    Error: Did you forget to use @userlike/babel-plugin-joke? 
      at Object.<anonymous> ​src/app/components/Toolbar/Features/NetworkSelector/__tests__/index.test.tsx:25:4​
 ```

I tried adding the plugin in `.babelrc`, in `package.json` and it's never picked up (the documentation mentions it should), but it works fine when running `yarn test`

Some help would be much appreciated, thanks !

**Comment by smcenlly** [comment]
Thanks for reporting the problem and for the sample repo. Previously, our `react-app-rewired` integration did not support [`cra-customize`](https://github.com/arackaf/customize-cra) (which your project was using). We've updated our integration to now support using this package.

Please update Wallaby core to `v1.0.1066`+ and it will work for you. Wallaby should update automatically for you but if it does not, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
