### ISSUE TITLE
Does Wallaby support `ngx-build-plus:karma`?

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2693]
I am also using `ngx-build-plus:karma`. Since I'm using Angular 11 I believe I have to use automatic configuration. How can I go about replacing `@angular-devkit/build-angular:karma` with `ngx-build-plus:karma` if I don't have a `wallaby.js` file?

_Originally posted by @tjrobinson in https://github.com/wallabyjs/public/issues/2326#issuecomment-831929896_

**Comment by smcenlly** [comment]
Wallaby does not currently support `ngx-build-plus:karma`. At this point in time, we don't have any immediate plans to add support for it.

When you run `ng add ngx-build-plus` for your Angular project, your `angular.json` test builder automatically changes from `@angular-devkit/build-angular:karma` to `ngx-build-plus:karma`. If you are not using any `ngx-build-plus` overrides that apply to your tests, we recommend changing this back to `@angular-devkit/build-angular:karma` and both Wallaby automatic configuration and `ng test` will work for you.

If you require `ngx-build-plus:karma` overrides for running your tests, at this point in time, your only option is to create a Wallaby configuration file. Unfortunately our legacy manual configuration settings for Angular CLI are not compatible for the latest version of Angular or for `ngx-build-plus:karma` and there is no way of migrating them. To create a manual configuration, you will need to determine the webpack configuration for your project and use Wallaby's [built-in webpack integration](https://wallabyjs.com/docs/integration/webpack-built-in.html).

If you get stuck, please provide us with a working sample repo with tests working outside of Wallaby and we can take a look for you.

**Comment by tjrobinson** [comment]
Thanks, that's working for me. Fortunately I don't need anything provided by `ngx-build-plus` in my tests.

For background, I am working with a hybrid Angular/AngularJS app and am using `ngx-build-plus` to allow for the following manual adjustments to the Angular CLI default `webpack` configuration, to allow the AngularJS code to work properly:

```javascript
const webpack = require('webpack');

module.exports = {
    module: {
        rules: [
            {
                test: /\.ts$/,
                use: [
                    {
                        loader: "ng-annotate-loader",
                        options: {
                            ngAnnotate: "ng-annotate-patched"
                        }
                    }
                ],
                enforce: "post"
            },
            {
                test: /\.html$/,
                use: [{ loader: "raw-loader" }]
            }
        ]
    },
  plugins: [
    new webpack.ProvidePlugin({
      $: "jquery",
      jQuery: "jquery",
      moment: "moment",
      "window.jQuery": "jquery"
    }),
  ]
};
```
