### ISSUE TITLE
Wallaby startup slow for large number of projects

### ISSUE THREAD

**Issue by michael-golden** [wallabyjs/public#2696]
### Issue description or question
I'm running wallaby in a NX monorepo with 93 projects.  It takes wallaby a few minutes to initialize and run, even with Exclusive Test Run.   What should I look at to speed this up?

package|version
--|--
jest|26.6.3
jest-extended|0.11.5
jest-mock-extended|1.0.13
ts-jest|26.5.3
ts-loader|8.0.18
ts-node|9.1.1
node|v15.11.0
@nrwl/jest|11.5.1

### Wallaby diagnostics report

Full diagnostic report e-mailed to wallaby support.

**Comment by smcenlly** [comment]
Could you please update your NX workspace root `package.json` and add:

```javascript
...
  "wallaby": {
    "debug": true,
    "trace": true
  }
...
```

and then send us your updated diagnostics report?

**Comment by michael-golden** [comment]
Here is the new diagnostic report.

Thanks!
________________________________

**Comment by ArtemGovorov** [comment]
We have replied with the solution via email.

**Comment by tamascsaba** [comment]
What was the solution? Thank you for the information :)

**Comment by smcenlly** [comment]
In this case, there were 80+ projects that were part of the mono-repo with tests and so Wallaby was taking a long time to start as it was running tests in all projects. Similarly, jest would have also taken a long time to run all tests.

Our advice was to start Wallaby using automatic configuration but selecting a **custom directory** to only run Wallaby for one project at a time. Or else try using the [exclusive test run](https://wallabyjs.com/docs/intro/selected-tests.html#exclusive-test-run) feature.

If you're having performance problems, please create a new issue and we'll be able to assist.
