### ISSUE TITLE
Visual Studio Dark theme and output window

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#270]
When using a dark theme in Visual Studio 2015, the text coloring in the "Wallaby.js - Failing Tests" output window pane is very difficult to read.  The background of this pane is a dark grey, which makes reading the light blueish and reddish text very difficult to read.

In addition, is there any way to get a dedicated tool window to Wallaby instead of using the Output window?

**Comment by ArtemGovorov** [comment]
These colors are supposed to be configurable from `Settings - Environment - Fonts and Colors - Wallaby.js Results...` display items. However, there seems to be a bug because it only works for the Covering Tests window, but not for the Output. We're looking into the issue.

> is there any way to get a dedicated tool window to Wallaby instead of using the Output window

At the moment, there's no dedicated wallaby tool window. If we create one, what would you expect to be there? Are there any issues with the existing Output window that you're encountering?

**Comment by brettjacobson** [comment]
I'll think about my wishes for a wallaby tool window and create a separate issue for it. Thanks!

**Comment by ArtemGovorov** [comment]
@brettjacobson The issue with color configuration is fixed in v1.0.16. 
You may now tune the colors by changing `Wallaby.js Results ...` display items. 
![fonts_and_colors](https://cloud.githubusercontent.com/assets/979966/10060996/96eb0a28-6298-11e5-8888-709afd6e34ed.png)

**Comment by brettjacobson** [comment]
Great, thanks!

**Comment by brettjacobson** [comment]
I don't think this is working correctly.  I've changed the text color on several of these items, and it doesn't seem to be having any effect on the coloring in the "Wallaby.js - Failing Tests" pane.

![image](https://cloud.githubusercontent.com/assets/8862834/10827083/fe88a8f8-7e3a-11e5-833b-ef560b2eff12.png)

As you can see, thats very difficult to read.

In my Options panel under Text Editor, i don't actually see any of the wallaby.js items having the blue or the light red colors selected for Item foreground.  I've changed most of them to lime green just to test it!  So I don't think the colors options are actually being used.

**Comment by ArtemGovorov** [comment]
Did you try to change those that start with `Wallaby.js Results ...`? Here is how it works for me:

![rec](https://cloud.githubusercontent.com/assets/979966/10835994/2ed18ae8-7ef4-11e5-9390-59a6f8d3932b.gif)

If the same thing doesn't work for you, could you try backing up your settings

![screenclip 1](https://cloud.githubusercontent.com/assets/979966/10836114/a708ef5a-7ef5-11e5-822e-1f309bef3571.png)

and then resetting your theme (with `Use Defaults`):
![skitch](https://cloud.githubusercontent.com/assets/979966/10836068/409d3474-7ef5-11e5-8af1-bf9548909808.png)

then restarting your Visual Studio, trying to change wallaby colours again and see if it works?

If it still doesn't work, could you please list your other installed extensions, possibly there's something conflicting.

**Comment by brettjacobson** [comment]
@ArtemGovorov thank you for the very detailed screenshots.  Unfortunately, no, resetting to defaults did not help.

I'm using Visual Studio 2015, and here are my installed extension (that I installed, not part of base VS install):
* Angular Productivity Tools
* Diff All Files for VS2015
* Microsoft ASP.NET and Web Tools
* NCrunch for Visual Studio
* PowerShell Tools for Visual Studio 2015
* Productivity Power Tools 2015
* Resharper
* Team Foundation Server Power Tools 2015
* TFS Productivity Pack (Visual Studio 2015)
* Web Analyzer
* Web Essentials 2015
* WhereAmI 2015

**Comment by brettjacobson** [comment]
So its working now;  the key point I missed in your post was restarting Visual Studio! I assumed they would take effect immediately, and I was just coming back to post that things were now magically working after I'd rebooted my machine, and noticed you'd said to restart Visual Studio.

Thank you very much!
