### ISSUE TITLE
Debug mode can't advance - additional logs?

### ISSUE THREAD

**Issue by alexanderlamb** [wallabyjs/public#2702]
### Debugger won't advance.  Line is highlighted in red but I can't find other info.

I've been running into situations when I'm stepping forward through my code and run into an 'Unable to Navigate' state as indicated in the docs.

When running the tests normally, everything is passing.  I was stuck in this state once when my function contained a loop that was comparing hundreds of objects to hundreds of other objects.  I simplified that comparison loop and I was able to navigate beyond that point using the debugger.

I can't however,  understand what is causing this error in some circumstances.  An example is as follows:
![image](https://user-images.githubusercontent.com/5480111/118198797-732c0400-b406-11eb-9d78-ee05e30da043.png)

I can't advance beyond this point and there isn't anything to step into.  It's a standard object property assignment.

My first though was that maybe I'm hitting a limit on what the debugger can handle?  Memory, call stack etc?

I've been unable to find any kind of log or output that would indicate what the problem is.  Where should I look to resolve issues like this?

I'm using VSCode connected to a docker container on Windows 10

**Comment by smcenlly** [comment]
Could you please tell us which exact method of stepping forward in your code that you are using? E.g. are you using F5 (Run to Active Line), Step Into, Step Out, etc.?

We do have an internal limit of `999999` debugger steps. Can you tell us how many steps you see in the Wallaby Tools section of VS Code. In the example below, you can see we have `6888` steps total.

![image](https://user-images.githubusercontent.com/2074089/118201299-796bc000-b49a-11eb-8ee7-cecc63de97f1.png)

**Comment by alexanderlamb** [comment]
That may be the problem :)

![image](https://user-images.githubusercontent.com/5480111/118205059-6b735c00-b414-11eb-91e0-c316836354d0.png)

Any suggestions?  My tests depend on each other, but I may be able to break them up into separate files.

**Comment by smcenlly** [comment]
We have added a new setting ([`maxTraceSteps`](https://wallabyjs.com/docs/config/overview.html#maximum-trace-steps)) to allow you to increase the maximum number of trace steps which should resolve your problem. We did some performance testing before we decided on our current default max number of steps: `999,999` steps. I have a vague recollection that `999,999` steps resulted in a memory increase of about ~10-20MB so you should have some headroom to change this setting.

While I'm not familiar with your project, I think generally that having tests that depend on each other is less than ideal for a number of reason (code isolation, performance, etc.) and would recommend to separate these if possible but it shouldn't affect your Wallaby usage, only Wallaby (and CLI) performance.

**Comment by alexanderlamb** [comment]
Thanks @smcenlly!
