### ISSUE TITLE
Automatic Jest configuration error: Module jest-cli is not found in '.'.

### ISSUE THREAD

**Issue by OnurUenal** [wallabyjs/public#2704]
Automatic Jest configuration error: Module jest-cli is not found in '.'.

**Comment by smcenlly** [comment]
Can you please provide your [Wallaby Diagnostics Report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)?

If your project is not using Jest >= v24, Angular CLI >= v8.2, Vue CLI >= v4, Create-React-App >= v3, or NX Workspaces >= v8 then you will need to create a Wallaby [configuration file](https://wallabyjs.com/docs/config/overview.html) to tell Wallaby how to run your project's tests.

**Comment by OnurUenal** [comment]
thank you for helping me.

> Can you please provide your Wallaby Diagnostics Report?

i try it but it´s not possible because i can not run wallaby. maybe i need a dist folder before in my angular project? but if i try to generate the dist folder there comes another error message:

```bash
An unhandled exception occurred: EROFS: read-only file system, mkdir '/dist'
```

**Comment by ArtemGovorov** [comment]
Can you please share your `package.json` file and `angular.json` file?

**Comment by smcenlly** [comment]
Closing this issue as we have not heard back. If you are able to share your `package.json` and `angular.json` file we can re-open the issue and take a look for you.
