### ISSUE TITLE
Wallaby not starting in shared library project updated to Angular 12

### ISSUE THREAD

**Issue by hamfastgamgee** [wallabyjs/public#2708]
### Issue description or question

I have tried updating a shared library project to Angular 12 (went final last week, and all my dependencies have released compatibility patches), and I'm getting failures trying to start up wallaby.  I'm not getting far enough in the process to send a formal diagnostics report, but I will paste what I have in trace mode.

### Wallaby diagnostics report

[Info]  2021-05-19T15:07:29.743Z angular/cli config Detecting Angular CLI.
[Info]  2021-05-19T15:07:29.748Z angular/cli config Detected Angular CLI.
[Info]  Started Wallaby.js Core v1.0.1075
[Info]  2021-05-19T15:07:29.756Z angular/cli karma project config Configuring.
[Info]  2021-05-19T15:07:40.086Z angular/cli karma project config Calling test command for bfy-ui-shared.
[Info]  2021-05-19T15:07:48.772Z angular/cli config TypeError: w is not a function
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:16:20534
[Info]      at generateWebpackConfig (C:\git\CMRS_BPFS\BFY\Src\BFY.UI.Shared\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:40:49)
[Info]      at async generateBrowserWebpackConfigFromContext (C:\git\CMRS_BPFS\BFY\Src\BFY.UI.Shared\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:20)
[Info]  2021-05-19T15:07:48.774Z angular/cli config Angular.json: 
[Info]   {
[Info]    '$schema': './node_modules/@angular/cli/lib/config/schema.json',
[Info]    version: 1,
[Info]    newProjectRoot: 'projects',
[Info]    projects: {
[Info]      'bfy-ui-shared': {
[Info]        projectType: 'library',
[Info]        root: 'projects/bfy-ui-shared',
[Info]        sourceRoot: 'projects/bfy-ui-shared/src',
[Info]        prefix: 'bfy',
[Info]        architect: {
[Info]          build: {
[Info]            builder: '@angular-devkit/build-angular:ng-packagr',
[Info]            options: { tsConfig: 'projects/bfy-ui-shared/tsconfig.lib.json', project: 'projects/bfy-ui-shared/ng-package.json' },
[Info]            allowedCommonJsDependencies: [ 'file-saver' ],
[Info]            configurations: { production: { tsConfig: 'projects/bfy-ui-shared/tsconfig.lib.prod.json' } }
[Info]          },
[Info]          test: {
[Info]            builder: '@angular-devkit/build-angular:karma',
[Info]            options: {
[Info]              main: 'projects/bfy-ui-shared/src/test.ts',
[Info]              tsConfig: 'projects/bfy-ui-shared/tsconfig.spec.json',
[Info]              karmaConfig: 'projects/bfy-ui-shared/karma.conf.js',
[Info]              codeCoverageExclude: [ 'projects/bfy-ui-shared/src/test-helpers/**/*.*' ]
[Info]            }
[Info]          },
[Info]          lint: { builder: '@angular-eslint/builder:lint', options: { lintFilePatterns: [ 'projects/bfy-ui-shared/**/*.ts', 'projects/bfy-ui-shared/**/*.html' ] } }
[Info]        }
[Info]      }
[Info]    },
[Info]    defaultProject: 'bfy-ui-shared',
[Info]    cli: { analytics: false }
[Info]  }
[Info]  2021-05-19T15:07:48.774Z angular/cli config TypeError: w is not a function
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:16:20534
[Info]      at generateWebpackConfig (C:\git\CMRS_BPFS\BFY\Src\BFY.UI.Shared\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:40:49)
[Info]      at async generateBrowserWebpackConfigFromContext (C:\git\CMRS_BPFS\BFY\Src\BFY.UI.Shared\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:97:20)
[Info]  2021-05-19T15:07:48.776Z jest/config Detecting Jest.
[Info]  2021-05-19T15:07:48.782Z jest/config Error: Module jest-cli is not found in 'C:\git\CMRS_BPFS\BFY\Src\BFY.UI.Shared'.
[Info]      at Object.<anonymous> (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:29:12904)
[Info]      at n (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:28:29245)
[Info]      at Object.next (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:28:28540)
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:28:28449
[Info]      at new Promise (<anonymous>)
[Info]      at r (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:28:28243)
[Info]      at Object.loadJest (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:29:10576)
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:14822
[Info]      at n (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:19322)
[Info]      at Object.next (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18617)
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18526
[Info]      at new Promise (<anonymous>)
[Info]      at s (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18320)
[Info]      at n (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:14510)
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:17997
[Info]      at n (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:19322)
[Info]      at Object.next (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18617)
[Info]      at c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18526
[Info]      at new Promise (<anonymous>)
[Info]      at s (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:18320)
[Info]      at r (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:18:17878)
[Info]      at Config.<anonymous> (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:15:25702)
[Info]      at n (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:15:19089)
[Info]      at Object.next (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:15:18384)
[Info]      at o (c:\Users\maw8414\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.292\wallabyf2b616\server.js:15:18133)
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: w is not a function
 
[Error] 
 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks
 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Info]  2021-05-19T15:07:48.805Z extended-core Setting preferences

**Comment by hamfastgamgee** [comment]
Angular.json is:

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "bfy-ui-shared": {
      "projectType": "library",
      "root": "projects/bfy-ui-shared",
      "sourceRoot": "projects/bfy-ui-shared/src",
      "prefix": "bfy",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "tsConfig": "projects/bfy-ui-shared/tsconfig.lib.json",
            "project": "projects/bfy-ui-shared/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/bfy-ui-shared/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/bfy-ui-shared/src/test.ts",
            "tsConfig": "projects/bfy-ui-shared/tsconfig.spec.json",
            "karmaConfig": "projects/bfy-ui-shared/karma.conf.js",
            "codeCoverageExclude": [
              "projects/bfy-ui-shared/src/test-helpers/**/*.*"
            ]
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "projects/bfy-ui-shared/**/*.ts",
              "projects/bfy-ui-shared/**/*.html"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "bfy-ui-shared",
  "cli": {
    "analytics": false
  }
}

**Comment by hamfastgamgee** [comment]
And package.json:

{
  "name": "@bfy/bfy-ui-shared",
  "version": "12.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:prod": "ng build --prod",
    "deploy": "npm ci && npm run build:prod",
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points --tsconfig \"./projects/bfy-ui-shared/tsconfig.lib.json\"",
    "test": "ng test",
    "test:gate": "ng test --watch=false --code-coverage",
    "gate": "npm ci && npm-run-all --print-label --parallel build:prod test:gate lint",
    "lint": "ng lint && npm run lint:styles",
    "lint:styles": "stylelint \"projects/bfy-ui-shared/**/*.s?(a|c)ss\"",
    "e2e": "ng e2e",
    "update:packages": "node wipe-dependencies.js && rm -rf node_modules && npm update --save-dev && npm update --save",
    "build:test-participant": "ng build && xcopy \"./dist\" \"../BFY.UI.Participant/node_modules/@bfy\" /s /F /y",
    "build:test-admin": "ng build && xcopy \"./dist\" \"../BFY.Admin.Web/node_modules/@bfy\" /s /F /y",
    "clean:dist": "rimraf dist && mkdir dist",
    "cleanInstall": "npm run clean:dist && npm install",
    "clean:node": "rimraf node_modules"
  },
  "private": true,
  "dependencies": {
    "@angular/forms": "~12.0.1",
    "@angular/material": "~12.0.1",
    "@angular/material-moment-adapter": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "error-stack-parser": "^2.0.6",
    "moment-timezone": "^0.5.33",
    "ngx-toastr": "^14.0.0",
    "rxjs": "^6.6.7",
    "stacktrace-gps": "^3.0.4",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.0",
    "@angular-eslint/builder": "^12.0.0",
    "@angular-eslint/eslint-plugin": "^12.0.0",
    "@angular-eslint/eslint-plugin-template": "^12.0.0",
    "@angular-eslint/schematics": "^12.0.0",
    "@angular-eslint/template-parser": "^12.0.0",
    "@angular/animations": "~12.0.1",
    "@angular/cdk": "~12.0.1",
    "@angular/cli": "~12.0.0",
    "@angular/common": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/compiler-cli": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~3.6.9",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^12.19.12",
    "@typescript-eslint/eslint-plugin": "4.24.0",
    "@typescript-eslint/parser": "4.24.0",
    "eslint": "^7.26.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "32.3.1",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "file-saver": "^2.0.5",
    "jasmine-core": "~3.7.1",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "moment": "2.29.1",
    "ng-packagr": "^12.0.0",
    "npm-run-all": "4.1.5",
    "postcss": "^8.2.15",
    "protractor": "~7.0.0",
    "stylelint": "^13.12.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.2.4"
  },
  "wallaby": {
    "autoDetect": true,
    "trace": true
  }
}

**Comment by smcenlly** [comment]
Thanks - we've duplicated the problem.

There's been some restructuring of files in the latest version of Angular that has broken our integration. We've started working on a fix but don't have any ETA we can provide yet. We hope to have a fix in the next day or so, if not, we'll let you know.

**Comment by hamfastgamgee** [comment]
A day or so sounds great.  A month or so and I'd have to postpone upgrading to Angular 12. :)

**Comment by NikGovorov** [comment]
Hi @hamfastgamgee,

We investigated the issue, it will takes us several days to implement and test Angular 12 support.

**Comment by hamfastgamgee** [comment]
Thanks folks, I truly appreciate the effort.

**Comment by NikGovorov** [comment]
Hi @hamfastgamgee,

We added support of Agular CLI 12 for single projects(apps or libs) in [v1.0.1079](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) which should work in your particular case. 

We still work on supporting running tests for multi projects workspaces, I'll close the issue once it's done.

**Comment by NikGovorov** [comment]
Multi-project workspaces support has been added in v1.0.1085.
