### ISSUE TITLE
Follow Offline install Doc, still get "Wallaby.js is updating and will be started automatically when the update is complete" Message

### ISSUE THREAD

**Issue by chgc** [wallabyjs/public#2727]
### Install WallabyJs Offline still get "Wallaby.js is updating..." Message

My working environment is in Corp Network, therefore I follow [Offline Install Document](https://wallabyjs.com/docs/intro/offline.html) to install wallaby.

When vscode open, it shows following notification
"With wallaby.noAutomaticInstall option set, you need to manually install wallaby core and dependencies when the extension is installed/updated"

When I start wallaby. it shows "Wallaby.js is updating and will be started automatically when the update is complete" notify message. 

How can I fix this problem? Thanks.

(sorry due to company secure policy, I can't upload any screenshot.)

VS Code version is 1.56.2
Wallaby-vscode extension: 1.0.294
Wallaby version: 1.0.1095

**Comment by ArtemGovorov** [comment]
This message

> With wallaby.noAutomaticInstall option set, you need to manually install wallaby core and dependencies when the extension is installed/updated

indicates that Wallaby Core has not been found in your extension folder. The [Offline Installation Document](https://wallabyjs.com/docs/intro/offline.html) contains the following steps:

```
- download the https://wallaby-downloads.s3.amazonaws.com/wallaby-vNNN.zip file, where NNN is latestServer[0] value in the downloaded wallaby.json file,
- unzip the downloaded file to the ~/.vscode/extensions/WallabyJs.wallaby-vscode-LATEST/wallaby folder,
```

Can you please verify that you've completed the steps and that your `~/.vscode/extensions/WallabyJs.wallaby-vscode-LATEST/wallaby` folder exists, is not empty, and contains `package.json` file inside it?

**Comment by chgc** [comment]
Yes, I am confirmed  `package.json` file is in  `%USERPROFILE%\.vscode\extensions\WallabyJs.wallaby-vscode-LATEST\wallaby` folder

**Comment by smcenlly** [comment]
From the error that you're getting, it sounds like you may have installed the extension **_before_** updating the VS Code `settings.json` file to include the ` "wallaby.noAutomaticInstall": true` setting.

We have just tried the offline installation instructions on a fresh VS Code installation that has never had Wallaby and everything is working for us.

Please try the following:

1. Uninstall the Wallaby VS Code extension
2. Close all instances of VS Code
3. In your VS Code extensions folder (`~/.vscode/extensions`), delete any `wallabyjs.wallaby-vscode-*` folders.
4. Delete Wallaby's application folder (`~/.wallaby`).
5. Open VS Code and update VS Code's `settings.json` to include `"wallaby.noAutomaticInstall": true` (or confirm it is still there)
6. Download the [latest version of the Wallaby Extensions](https://marketplace.visualstudio.com/items?itemName=WallabyJs.wallaby-vscode) from VS Code Marketplace.
7. Install the downloaded extension using the `Extensions: Install from VSIX...` command
8. Download the latest version of Wallaby core from here: [https://wallaby-downloads.s3.amazonaws.com/wallaby-v1.0.1095.zip](https://wallaby-downloads.s3.amazonaws.com/wallaby-v1.0.1095.zip)
9. Extract it to `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.297/wallaby` (or similar name based on extension version).
10. Download the latest Wallaby App files from [https://wallaby-downloads.s3.amazonaws.com/wallaby-app.zip](https://wallaby-downloads.s3.amazonaws.com/wallaby-app.zip)
11. Unzip the Wallaby App Zip file to the `~/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.297/wallaby-app` folder (or similar name based on extension version).
12. Open VS Code and start Wallaby.js.

**Comment by chgc** [comment]
Thanks for really detail steps, I found where my problem was.
in step 9. I put wallaby and wallaby-app folder in `wallabyjs.wallaby-vscode-LATEST` folder, I misunderstood what LATEST meant.  
After move wallaby and wallaby-app to wallabyjs.wallaby-vscode-1.0.297 folder. (LATEST mean last version of wallabyjs extension), everything is working now.

Thanks for the help.

**Comment by jardicc** [comment]
Note for others. In my case, I did not notice that there are 3 parts instead of 2
1) extension
2) `/wallaby` folder
3) `/wallaby-app` folder

**Comment by smcenlly** [comment]
@jardicc - the steps are also listed in [our docs](https://wallabyjs.com/docs/intro/offline.html).

**Comment by jardicc** [comment]
Yes, I saw it. But I just did not expect it to have that many parts :-D So I didn't see it :-D
