### ISSUE TITLE
Enhance Wallaby App to auto-detect hyperlinks in wallaby logs so that they can be navigated to

### ISSUE THREAD

**Issue by hakubo** [wallabyjs/public#2728]
### Issue description or question

screen.logTestingPlaygroundURL() is great for writing tests and quickly getting selectors for elements. However when used in wallaby link are not clickable: 
![image](https://user-images.githubusercontent.com/1018759/121490523-65ea4100-c9d5-11eb-93e5-b34d71421577.png)

It would be beneficial if these could be links.

Or better yet - if wallaby could detect it and open it automatically. Maybe even auto update it when test changes.

Thanks!

**Comment by smcenlly** [comment]
Can you please tell us which editor/operating system you are using?

**Comment by hakubo** [comment]
vscode + macos

**Comment by smcenlly** [comment]
You should be able to `Cmd + Click` in the `Wallaby Test` and `Wallaby Console` output windows to launch links. By default VS Code does not allow you to click, but `Ctrl/Cmd + Click` should open the link for you (see demo below). If it's not working for you, can you please try disabling all extension except for Wallaby and try again? If that's also not working, it's possible that you have a modified VS Code setting that is causing the `Cmd + Click` to not work; please try restoring the default settings (back up your existing settings first) to confirm that it's working.

![testingplayground](https://user-images.githubusercontent.com/2074089/122129311-43df3b80-ce79-11eb-80bd-fafb21f4c9aa.gif)

**Comment by smcenlly** [comment]
I'm going to assume that our suggestion solved your problem. If not, please let us know and we can re-open this issue.

**Comment by hakubo** [comment]
It does work in console.

but it does not work in Coverage and Test explorer

**Comment by smcenlly** [comment]
We have updated Wallaby App to detect URLs in console log messages and to provide those URLs as hyperlinks:

![image](https://user-images.githubusercontent.com/2074089/122858097-0721b180-d35d-11eb-86ad-87bf66ca68e3.png)
