### ISSUE TITLE
persistent directory

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#273]
I periodically remove all files and folders from `~/Library/Caches` directory. For instance, I am using `CleanMyMac` for that.

It would be nice if  `wallaby` doesn't store `key.lic` and related files to `~/Library/Caches/WebStorm10/wallaby` and uses more persistent directory.

It would be nice to have one directory to store all `wallaby` licence and related files. Is it possible?

**Comment by ArtemGovorov** [comment]
Wallaby uses WebStorm cache folder and while it's definitely possible to implement storing the file somewhere else, I would recommend excluding the folder from cleaning (if the cleaner software supports it), because cleaning the folder may significantly affect WS and its plugins performance.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks for the response. I have added `WebStorm` cache folder to the exclude list.
