### ISSUE TITLE
Wallaby does not pick up on tests in Angular 9 app with multiple projects/modules

### ISSUE THREAD

**Issue by KevinC4T** [wallabyjs/public#2732]
Setup: vscode with Angular 9 application; the application is partitioned in 10+ modules; jest is used

1. Using the getting started guide with automatic configuration: did not work (wallaby was just doing something / spinning in the status bar and after 10s  stopped without much. I had at least to select a specific project folder in the app. Is this correct?

2. after selecting the project folder, wallaby seems to be ready and configured (= I see '0 X 0 V' in the status bar bottom right), but does not pick up any test. no green boxes or anything in the code. If I command start and request to run the test file open in vscode nothing happens.

if you would like me to share something please ask me, because I really want to give it a go.

**Comment by ArtemGovorov** [comment]
> Using the getting started guide with automatic configuration: did not work (wallaby was just doing something / spinning in the status bar and after 10s stopped without much.

Can you please:

- start Wallaby in your project (for the root of your repo);
- wait until it reports some results (finishes running tests) - in your case stops spinning after 10s;
- run `Copy Diagnostics Report` command in VS Code from your editor command palette; 
- paste generated report from your clipboard below.

**Comment by KevinC4T** [comment]
sure, is this a private message. because I do not want to paste any possibly confidential information

**Comment by ArtemGovorov** [comment]
You can send the diagnostics report to hello@wallabyjs.com (please also add the issue link to the email subject).

**Comment by KevinC4T** [comment]
done

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. It looks like Jest when running by Wallaby is not reading your Jest config. 

Here’s the solution:

- create this simple Wallaby config file in your repo's root:

**wallaby.js**
```js
module.exports = () => {
    return {
      // tell wallaby to use automatic configuration
      autoDetect: true,
  
      testFramework: {
        // the jest configuration file path
        // (relative to project root)
        configFile: './jest.config.json'
      }
    }
  };
```
- In VS Code run “Select Configuration” Wallaby command and select the file instead of automatic configuration.

**Comment by KevinC4T** [comment]
thanks for the quick response

I have done what you proposed, but no success; maybe due to the particular structure of our repo?

- there is only one jest config file, not one per project. Could this be the issue?
- the repo is structured as follows:

      - repo folder
        - projects
          - angular project 1 (api)
             - ... 
          - angular project 2 (front)
             - src
                - app 
                   - angular module 1
                   - angular module 2  
                   - ...
          - ... (angular project n)
             - ... 
        - jest.config.json
        - wallaby.js

**Comment by ArtemGovorov** [comment]
Can you please email us the diagnostics report captured after applying the proposed Wallaby config?

**Comment by smcenlly** [comment]
Reviewing logs over email, we identified that `@angular-builders/jest` is for version `7.4.1` while Angular version is `v9.x`. Suggested fix is to upgrade to the correct version of `@angular-builders/jest` for the version of Angular (`@angular-builders/jest@9.0.1`). We expect this will fix the problem.

Closing this issue. If you have further problems, please reply to the issue and we can re-open it, or else, email us.
