### ISSUE TITLE
Feature request: Provide option to interpret `it.only` in the same way as Jest

### ISSUE THREAD

**Issue by schickling** [wallabyjs/public#2736]
It would be great if there was a configuration option that forces Wallaby to interpret `it.only` the same way as Jest does i.e. still execute all tests/test files across a project and apply the `it.only` only to the given test file.

Context from Discord:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1567498/122738738-8d1cfa00-d282-11eb-98ee-4711774716d4.png">

**Comment by smcenlly** [comment]
A configuration option already exists to make Wallaby behave the same way as Jest:

1. Run all tests without `.only`
2. Only runs `.only` tests or sections within a file with `.only`.

From [our docs](https://wallabyjs.com/docs/intro/selected-tests.html#additional-configuration):

> If you encounter a scenario when using the automatic test focusing is not desirable, you may turn the feature off in your wallaby config:
> 
> ```javascript
> module.exports = function (wallaby) {
>   return {
>     ...
>     automaticTestFileSelection: false
>   };
> };
> ```

In your case, you would have a configuration file that looks like:

**Wallaby.js**
```javascript
module.exports = function (wallaby) {
  return {
    autoDetect: true,
    automaticTestFileSelection: false
  };
};
```

Alternatively, you may add the configuration to your `package.json`:

**package.json**
```javascript
{
  ...
  "wallaby": {
    "automaticTestFileSelection": false
  }
}
```
