### ISSUE TITLE
angular v12 - can not start wallaby

### ISSUE THREAD

**Issue by OnurUenal** [wallabyjs/public#2739]
### Issue description or question

i can not start wallaby.js. if i want to start there comes a error message. i tried also the automatic configure but there comes a error message too. 

### Wallaby diagnostics report

wallaby.js started
core v1.0.1098
Failed to load configuration file: Unsupported webpack version. The 'wallaby-webpack' package does not support your project's version of webpack (5.39.1). Use Wallaby's built-in webpack integration instead: https://wallabyjs.com/docs/integration/webpack-built-in.html
    at module.exports (./wallaby.js:106:20)

### Wallaby diagnostics report (automatic configuration)

wallaby.js started
core v1.0.1098
Failed to load configuration file: Unsupported webpack version. The 'wallaby-webpack' package does not support your project's version of webpack (5.39.1). Use Wallaby's built-in webpack integration instead: https://wallabyjs.com/docs/integration/webpack-built-in.html
    at module.exports (./wallaby.js:106:20)

**Comment by NikGovorov** [comment]
Angular CLI 12 projects support only automatic configuration, could you please provide us with [Diagnostics Report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report) for automatic configuration? 

Both reports that you shared are for the manual configuration which uses `wallaby-webpack`.

**Comment by OnurUenal** [comment]
### screen record
https://youtu.be/963NHtfph8o

### report
wallaby.js started
core v1.0.1098
Failed to load configuration file: Automatic Angular CLI configuration error: Could not load Webpack configuration

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.'.

**Comment by OnurUenal** [comment]
### it work´s now 

#1 ```bash
ng new <PROJECT_NAME>
```

#2 ```bash
npm i jest-cli
```

**Comment by smcenlly** [comment]
Glad to hear that you got it working. Closing this issue.

**Comment by NikGovorov** [comment]
@OnurUenal do you use `jest` to run your tests?

**Comment by NikGovorov** [comment]
Could you please repro the issue on your video again and try this https://github.com/wallabyjs/public/issues/2737#issuecomment-865810863?

**Comment by OnurUenal** [comment]
@NikGovorov https://www.youtube.com/watch?v=TV0zC6qHr8E
