### ISSUE TITLE
Test status indicator in status bar of Visual Studio

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#274]
I would like it if there was an always visible status indicator of JavaScript tests that was visible in the status bar in Visual Studio, similar to NCrunch.  This indicator could be green if all tests are passing, and red if any test is failing.  If tests are failing, perhaps the number of failing tests could be shown inside the red indicator.

**Comment by ArtemGovorov** [comment]
Wallaby does have the indicator in the status bar (bottom right corner) that does almost everything that you've described:

![main](https://cloud.githubusercontent.com/assets/979966/10061521/e1b5873c-629c-11e5-8e8f-0448d1edaaba.png)

Or am I missing something?

**Comment by ArtemGovorov** [comment]
if you don't see the indicator, could you please list your installed VS extensions? There may by some conflicts resulting in the indicator go missing.

**Comment by brettjacobson** [comment]
Nope, its there, awesome!  I just didn't know what it was :)  It was right next to my NCrunch indicator and R# solution indicators, so I just assumed it was something related to those that I did not recognize.  I'd tried hovering with my mouse over it to see if there was a tooltip, but because it is on the far right, the windows 8 charms pane just always popped up.

When there are failing tests, does it give any indication to the number of failing tests??

**Comment by ArtemGovorov** [comment]
Cool, thanks for the update.

> When there are failing tests, does it give any indication to the number of failing tests

It doesn't, you need to open Wallaby Failing tests output window to get these details. You'll need to do it anyway to navigate to those tests (if you're not already in the file with 'red' indicators, in which case the easier way would be to [use smart actions](http://wallabyjs.com/docs/intro/get-started-vs.html#smart-actions) to jump to failing tests).
