### ISSUE TITLE
0% Test Coverage

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [wallabyjs/public#2743]
Issue Type: <b>Bug</b>

Wallaby seems to be stuck at import statements in vue script tag. Also reports 0% coverage, although jest is reporting 100%

![image](https://user-images.githubusercontent.com/86342787/123804395-795e3d00-d8ed-11eb-905a-fe813542e0a3.png)

Extension version: 1.0.297
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.87GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510
vsccppwt:30329788

```

</details>

**Comment by smcenlly** [comment]
To investigate we will need some additional information. Could you please start by providing us with your Wallaby Diagnostics report?

The Wallaby Diagnostics Report is a simple JSON text report that contains some basic information about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

If you are concerned about sharing the information in the diagnostics report on github, you may email it to hello@wallabyjs.com instead.

**Comment by sschneider-ihre-pvs** [comment]
ok done.

**Comment by smcenlly** [comment]
> Also reports 0% coverage, although jest is reporting 100%

Do your `jest` tests run and report coverage correctly using the command below when run from the CLI of folder you have opened in VS Code?

```
npx jest --collectCoverage
``` 

If that is working for you and Wallaby is not, please provide us with a cut-down (non production code) reproduceable sample that has the same jest, typescript, and vue, etc. configuration as your project.

If that is **not** working for you, can you please describe how you are running your tests from the CLI?

**Comment by sschneider-ihre-pvs** [comment]
I either run `npx jest` or `npm run test:unit` which then runs `vue-cli-service test:unit` and both are working with coverage.
Currently Wallaby does not show any coverage at all.

**Comment by smcenlly** [comment]
Could you please provide us with a cut-down (non production code) reproduceable sample that has the same jest, typescript, and vue, etc. configuration as your project?

**Comment by sschneider-ihre-pvs** [comment]
I cannot provide any code, sorry

**Comment by smcenlly** [comment]
We have created a [sample repo](https://github.com/wallabyjs/wallaby-2743) that has the same `package.json` dependencies that you listed in your diagnostics report. 

Could you please try it and confirm that everything is working for you?

1. Clone repo: `git clone https://github.com/wallabyjs/wallaby-2743`
2. Install dependencies: `yarn` 
3. Start Wallaby
4. Check that `src/components/HelloWorld.vue` shows import:

![image](https://user-images.githubusercontent.com/2074089/124339553-9e56f680-dbf2-11eb-8059-20cc3c298b2a.png)

If it is working for you, can you please try to update it with similar code to your project and break it with whatever we are missing.

**Comment by sschneider-ihre-pvs** [comment]
The minimal example works but for adding alternate code I lack the time.

**Comment by smcenlly** [comment]
> And the trial ended.

We have emailed you another trial license.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If/when you reply, we will re-open.
