### ISSUE TITLE
Automatic Angular CLI configuration error: A project for '.' directory cannot be detected.

### ISSUE THREAD

**Issue by ArtemeeSenin** [wallabyjs/public#2744]
### Issue description or question

Angular CLI 11.2.4 and  automatic configuration may resolve your problem.

[This repository]( https://github.com/ArtemeeSenin/tiny-tasks) is a monorepo with angular.json on top and all the rest is in src/main/webapp

But wallaby automatically does not catch and I see the error below (I use wallaby with Intellij Idea)

```
Automatic Angular CLI configuration error: A project for '.' directory cannot be detected.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.'.
```
### Wallaby diagnostics report

Does not copy, leaves my clipboard buffer the same

**Comment by NikGovorov** [comment]
I've cloned your repo and wallaby works fine there, however I had to change [line 16](https://github.com/ArtemeeSenin/tiny-tasks/blob/master/angular.json#L16) of `angular.json`, rename `targets` to `architect`(https://angular.io/guide/workspace-config#configuring-builder-targets). 

![ScreenClip](https://user-images.githubusercontent.com/129254/124096467-f29c9200-da9d-11eb-856e-ce8f7a7c3b0e.png)

**Comment by ArtemeeSenin** [comment]
@NikGovorov thank you a lot for you time and help!
