### ISSUE TITLE
Sublime Text 3/4 – Test markers doesn't show with any light theme

### ISSUE THREAD

**Issue by r3nya** [wallabyjs/public#2746]
### Issue description or question

Unfortunately test markers doesn't work with light theme. (I don't have GitGutter plugin)

Just to make sure I've checked it on example project from https://wallabyjs.com/docs/intro/get-started-sublime.html page 

<details>
  <summary>Screenshots</summary>
  
##### GitHub Light
<img width="1072" alt="Screenshot 2021-07-05 at 00 09 12" src="https://user-images.githubusercontent.com/209313/124399748-2db0f680-dd26-11eb-9e96-b67a6535e6c7.png">

##### Gruvbox Light
<img width="1072" alt="Screenshot 2021-07-05 at 00 22 53" src="https://user-images.githubusercontent.com/209313/124399886-381fc000-dd27-11eb-93ef-424bb143dd2b.png">

##### GitHub Dark
<img width="1072" alt="Screenshot 2021-07-05 at 00 09 38" src="https://user-images.githubusercontent.com/209313/124399754-39042200-dd26-11eb-845c-df977c389405.png">

</details>

### Wallaby diagnostics report

Wallaby v1.0.65

PS: Strange but command "Copy Diagnostics Report" couldn't copy anything 🤔

**Comment by smcenlly** [comment]
Sublime Text automatically tints gutter icons to match your background color settings. Unfortunately this can cause Wallaby's indicators to vary from slightly inaccurate to completely black.  Wallaby used to automatically correct this for you, but it has been broken with the release of Sublime Text 4. 

We're investigating how to update Wallaby to fix this for you automatically, but in the meantime, you may fix yourself by customizing your current color scheme to set the foreground to white only for the `wallaby` scope. This will not have any effect other other than to correct the color of Wallaby icons.

To modify your theme, perform the following steps:

1. Select `Preferences` menu -> `Customize Color Scheme`
2. Sublime Text will open a split-view with your theme override on the right-hand side of the screen.
3. Under the `rules` section of theme override, add the following new rule:

```
  { "scope": "wallaby", "foreground": "#fff" }
```

4. Save the override
5. Restart Wallaby

**Comment by smcenlly** [comment]
We have updated both Wallaby and Quokka to automatically override theme settings so that gutter indicators work correctly for both Sublime Text 3 and Sublime Text 4.

This behavior is available in Wallaby for Sublime `v1.0.66+`, and Quokka for Sublime `v1.0.111+`.

**Comment by r3nya** [comment]
Thank you! Everything works well!
