### ISSUE TITLE
Test tool window in Visual Studio

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#275]
I would like a dedicated tool window in Visual Studio for test results.  This would allow quick navigation to JS test results, because often the Output window has different panes selected whenever I visit there looking for test result information.

Perhaps this dedicated tool window could support listing all tests in a treeview format, with the status of each test shown.  Clicking the test would navigate directly to it in the source.

This feature would be similar to the NCrunch Tests window.

**Comment by ArtemGovorov** [comment]
Thanks. We have the feature request https://github.com/wallabyjs/public/issues/144 that pretty much describes what you're asking for (if not, please feel free to add your comments in that issue), so I'll close this one as a duplicate.
