### ISSUE TITLE
Runtime error: TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by marcoSven** [wallabyjs/public#2752]
### Issue description or question

For an unknown reason, I started to get the following error from Wallaby `Cannot set property '0' of undefined`.

On initial startup, first test run, there is no issue but after making any change to the test suite, the error immediately pops up again. 

Solved the issue by deleting the project folder as suggested by @ArtemGovorov here #2466 

I emailed my diagnostics report etc to support, but none of the suggestions mentioned the above "fix". I think I have encountered this issue in the past and for some reason, it fixed itself.  

Feel free to close this issue simply hoping there is a permanent fix.

**Comment by smcenlly** [comment]
We've made a number of enhancements to how Jest cache mismatches are handled as well as error reporting for this specific case. Error will not report what steps need to be taken. We're still not quite sure how your issue exhibited in the first place and were not expecting that clearing the Wallaby project cache to fix your problem.

The improvements will be published in the next version of Wallaby core, `v1.0.1110`. If you have a similar problem again in the future after this version, please let us know.
