### ISSUE TITLE
Angular CLI: Wallaby looks in wrong path for webpack configs

### ISSUE THREAD

**Issue by pauleustice** [wallabyjs/public#2753]
### Issue description or question

I have an Angular monorepo using ng 11. When trying to run Wallaby using an automatic configuration in Webstorm, I see this error:

```
Failed to load configuration file: Automatic Angular CLI configuration error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs'
```

This seems to be the incorrect path for Angular 11; my Webpack configs are located at `@angular-devkit/build-angular/src/webpack/configs`.

<img width="457" alt="Screenshot 2021-07-16 at 09 33 17" src="https://user-images.githubusercontent.com/1677737/125918457-53de58f7-442e-4ba3-9960-8bec7d94252b.png">

<img width="580" alt="Screenshot 2021-07-16 at 09 33 38" src="https://user-images.githubusercontent.com/1677737/125918470-914f1ec2-ec48-4177-81e9-1e1e1c2704cf.png">

### Wallaby diagnostics report

Nothing present when attempting to copy.

**Comment by NikGovorov** [comment]
Hi @pauleustice,

Could you please check if/when your [license](https://wallabyjs.com/docs/intro/license.html?editor=jb) expired? I suspect that your version of core does not support Angular CLI 11.

**Comment by pauleustice** [comment]
> Hi @pauleustice,
> 
> Could you please check if/when your [license](https://wallabyjs.com/docs/intro/license.html?editor=jb) expired? I suspect that your version of Core does not support Angular CLI 11.

@NikGovorov Sorry for the delay in getting back to you. It expired in 2019, so I guess that's it; I hadn't realised that licence was actually active within Webstorm. How can I go about removing it to test with a trial licence?

**Comment by smcenlly** [comment]
@pauleustice - you may request a trial license from [our website](https://wallabyjs.com/download/) and simply replace your license key with the trial key that is emailed to you. If you wish to revert to your old license, change the key back to your old license key.

Instructions for changing your license key are described in [our docs](https://wallabyjs.com/docs/intro/license.html?editor=jb#jetbrains-ides).

**Comment by pauleustice** [comment]
Thanks! 👍
