### ISSUE TITLE
Debugging preprocessor

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#276]
I'm currently working on a wallaby preprocessor, which is quite hard to debug.
Wallaby is not supporting debug mode (see #74), so I have to do it with `console.log`. When I have a `console.log` statement in the config file, output is sent to the Wallaby Console window, but when I log something in the preprocessor function, nothing is visible.

How can I debug my preprocessor?

**Comment by fvanwijk** [comment]
Argh... the function was not triggered because my file pattern did not match the file. Thanks to #68.
However, the question still stands: do you have suggestions how to make debugging easier?

**Comment by ArtemGovorov** [comment]
#74 wouldn't help in this case, as it's about debugging your app/tests code. Config code is executed by wallaby core in node.js context.

If your preprocessor is quite complex and you want to debug its code, then I'd suggest to debug it in isolation from wallaby.js engine, for example by creating a simple app.js file that requires wallaby.js and mocks required stuff. You can debug the app in your IDE just like other node.js apps.

If you'd like to debug with real wallaby.js engine, the you may use `console.log` anywhere in your config file and missing output means that the piece of code where you've placed it is not executed, that includes preprocessors. It's really the same if you would be able to place a breakpoint that was never hit.

Another thing that may make debugging easier is to turn on [`debug: true` flag](http://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) in your config and to inspect the Wallaby Console output. It's very verbose, so to save time, one needs to know what to look for. In this particular case, you may look for a file name that was supposed to be processed by the preprocessor and you'll find some log entries saying something like `no processors found` for the file, and that pretty much points out the issue.
