### ISSUE TITLE
Updating an inline snapshot writes to file but not to open editor

### ISSUE THREAD

**Issue by ncirkel** [wallabyjs/public#2761]
### Issue description or question

I tend to have many unsaved files open when working with unit tests in VSCode. This is made possible by Wallaby detecting and running unsaved changes.

One thing I keep running into is having to save a file before updating inline snapshots. The update is written to the file on disk, but the open editor is unchanged. Wallaby reports all green on the outdated code and when trying to save, VSCode complains that the content of the file on disk is newer.

This also happens when typing `expect([...]).toMatchInlineSnapshot()`, which triggers inserting the initial snapshot. I have to remember to quickly save the file before it updates.

I could certainly live with Wallaby saving the file before updating snapshots, if that's the easy solution to this.

### Wallaby diagnostics report

(The relevant bit)

```
{
  editorVersion: '1.58.2',
  pluginVersion: '1.0.301',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.22000',
  nodeVersion: 'v14.17.1',
  coreVersion: '1.0.1118',
  checksum: 'N2RiOWMyYjdlOGYyMTQ1MDE4NmY1NWU3ZTY1MDU3NWUsMTY0NDcxMDQwMDAwMCww',
}
```

**Comment by smcenlly** [comment]
Currently, Wallaby does not work properly with inline snapshots in some editors when not using auto-save. We are working on improving this behaviour and expect to have an updated version that correctly works when not using auto-save by the end of this week. We will reply to this issue when the updated version is available.

**Comment by ncirkel** [comment]
That's fantastic, looking forward!

**Comment by smcenlly** [comment]
We have updated Wallaby to better handle updating inline snapshots in unsaved files. Please update to the latest version of Wallaby and it will work without the problem that you identified.

**Comment by ncirkel** [comment]
I had time to try this now and, unfortunately, something goes wrong on my end. Updating an inline snapshot in an unsaved file results in a test run failure. This is from the log:

```
[Info]  console.log: Jest: FAIL packages/ui/src/editor/state/array/array.test.tsx
[Info]  console.log: Jest:   ● Test suite failed to run
[Info]      Jest: Couldn't locate all inline snapshots.
[Info]        at Object.parse (node_modules/jest-snapshot/build/InlineSnapshots.js:267:11)
[Info]        at Object.parse (node_modules/prettier/index.js:13625:19)
[Info]        at coreFormat (node_modules/prettier/index.js:14899:14)
[Info]        at format (node_modules/prettier/index.js:15131:14)
[Info]        at node_modules/prettier/index.js:57542:12
[Info]        at Object.format (node_modules/prettier/index.js:57562:12)
[Error] Runtime error: undefined 
```

Diagnostics report:

```
{
  editorVersion: '1.59.0',
  pluginVersion: '1.0.302',
  editorType: 'VSCode',
  osVersion: 'win32 10.0.19043',
  nodeVersion: 'v12.22.1',
  coreVersion: '1.0.1125',
  checksum: 'N2RiOWMyYjdlOGYyMTQ1MDE4NmY1NWU3ZTY1MDU3NWUsMTY0NDcxMDQwMDAwMCww',
}
```

**Comment by smcenlly** [comment]
@ncirkel - this doesn't sound related to our change; the change that we made is actually downstream of this call and should be completely unrelated. 

Are you able to create a simple sample repo and step-by-step instructions so that we can replicate the issue?
