### ISSUE TITLE
Incorrect incrementCondition executing in for loop when debugging

### ISSUE THREAD

**Issue by benthomasknight** [wallabyjs/public#2767]
Wallaby is returning the incorrect date object when evaluating a for loop. The following piece of code shows two different results when debugging versus not debugging. It seems to only be returning the final result of the object rather than its state at each iteration.

```
const dayStart = moment("2021-07-01");
const leaveRequestEnd = moment("2021-07-03");
for (; dayStart.isBefore(leaveRequestEnd); dayStart.add(1, 'days')) {
    console.log(dayStart);
}
```

dayStart when outside debugger: 2021-07-01, 2021-07-02

dayStart when looping (selecting the object when in each loop): 2021-07-02, 2021-07-02

Iterating the loop can be seen here.

https://user-images.githubusercontent.com/20388953/128276782-248f23ad-3156-497f-8652-a1944867374a.mov

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. The bug is fixed and the fix is published in [the latest core v1.0.1125](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
