### ISSUE TITLE
Supported versions of Jasmine

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#277]
I tried modifying my wallabyjs.json file to say
 "testFramework": "jasmine@2.2.0" from  "testFramework": "jasmine@2.1.3", and i get 
Failed to load configuration file:  Test framework [jasmine@2.2.0] is not supported

2.2.0 is what we're using without wallaby, does this mean we cannot use wallaby with newer versions of jasmine?  How do we see the list of supported jasmine versions?

**Comment by ArtemGovorov** [comment]
Have a look [here to see the list of versions](http://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). Basically if some higher version is there (2.2.1 in your case), then lower one should just work as well, so you may configure: `"testFramework": "jasmine@2.2.1"` and it'll work for you. But, as the docs say, I'd recommend to just use `"testFramework": "jasmine"` without any version. These versions are more for our reference, we add them if there're some breaking in changes in the way we integrate with those frameworks internally.

**Comment by brettjacobson** [comment]
Good news, thank you!
