### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by PavelA85** [wallabyjs/public#2772]
Visual Studio 2022 Preview was released on June 17, 2021, https://visualstudio.microsoft.com/vs/preview/ 

Can you please provide the Wallaby.js extension for VS2022?

**Comment by smcenlly** [comment]
Adding as a feature request. Don't have an ETA that we can share at this time but this was already on our radar outside of being a feature request and should be something that we can address in the next month or two.

**Comment by NikGovorov** [comment]
Hi @PavelA85,

We've released [Wallaby.js for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=vs-publisher-999439.WallabyjsforVisualStudio2022). Could you please try it and let us know if it works for you?
