### ISSUE TITLE
Test file line markers are out of sync with code

### ISSUE THREAD

**Issue by MarkKahn** [wallabyjs/public#2783]
### Issue description or question

Trying to get wallaby running and line markers on all our tests are inaccurate and seem to be seeing entirely different content from the actual test file.

See video:

https://user-images.githubusercontent.com/320562/131135088-785ab252-4ebe-40d4-8a9a-8ced73296fa6.mov

My wild guess is that wallaby might be seeing the tests after Jest has re-writen the test files internally, but as I said that's just a guess.  Happy to provide whatever info to help debug.

### Wallaby diagnostics report

Too long to paste in issue.  https://gist.githubusercontent.com/MarkKahn/024e7923c21b2163e7db01bd9498938e/raw/4b1345d3035d10cf51c2a13769225e832b5d6270/wallaby-diagnostics.json

**Comment by smcenlly** [comment]
Thanks for providing your diagnostics report.

It looks like you are using `esbuild-jest` to transform your files. We can reproduce your problem if `esbuild-jest` is not configured to emit source maps. Wallaby needs the source maps to correctly identify how the transformed file maps back to the original file. Please update your `jest` configuration to fix the problem:

**jest.config.js**
```diff
module.exports = {
  "transform": {
    "^.+\\.tsx?$": [ 
      "esbuild-jest", 
      { 
+       sourcemap: true
      } 
    ]
  }
}
```

**Comment by MarkKahn** [comment]
thanks for the quick response!

**Comment by DHFW** [comment]
I still have this issue with NodeJS 16.13.0, esbuild-jest 0.5.0, and Jest 25.5.4. Also tried Jest 27.3.2 (latest). Setting the `sourcemap: true` or `sourcemap: 'inline' does not help. Resetted the WallabyJS cache after every change in config. Used in VS code current version. 
![image](https://user-images.githubusercontent.com/8356670/141701653-3511bdec-68da-4663-98c4-ee9652536fc5.png)

I have to revert back to `ts-jest` for this to work properly. Background: I'm using ES build during development time for now. This is a NodeJS api project.

**Comment by smcenlly** [comment]
@DHFW - this is most likely due to esbuild source maps being incorrect. Are you able to provide a sample repo with the problem? If so, we can analyse the source maps and help you report the issue to the esbuild team.
