### ISSUE TITLE
"Some long running code has been detected" error in wallaby console when using faker

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2787]
### Issue description or question
`core v1.0.1136` / `IntelliJ 2020.3`
When using [faker](https://www.npmjs.com/package/faker) running wallaby results in console output error (I guess since it is red) below
```
        Some long running code has been detected: one of your files is taking more than 5000ms to execute.
        Execution of the following files has started but has not finished:
            - test/faker.jest.test.ts
        Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,
        and restarting wallaby to make sure that it is this test/file causing the issue and not something else.
        Pinging test runner sandbox...
        The sandbox is not responsive. Check for possibly recently introduced infinite loops.
```
* using e.g. `jest.setTimeout(20000) ` does not seem to help (where does this 5000ms come from?)
* runing it via `npm test` works fine.
* Rerunning test by modifying code does not output the error, but restarting wallabyJS does.
* Test passes after 9s: `console.log: Jest: PASS test/faker.jest.test.ts (9.139 s)`

Repro: See [faker.jest.test.ts](https://github.com/greenmooseSE/wallaby_example/blob/try-wjUsingFakerResultsInUnresponsiveSandbox/test/faker.jest.test.ts)

**Comment by smcenlly** [comment]
Thanks for the sample repo. Unfortunately we cannot reproduce the same issue with your repo/branch.

The messages that you are seeing are warnings only. That is to say, Wallaby does not do any special processing after displaying the messages, it's simply telling you that there's been a problem.

Wallaby has an internal timeout that it uses to detect long running code outside of your test executing (e.g. imports, etc.). This can be changed in your Wallaby.js configuration file, but it's only a warning (`longExecutingWarningTimeout` default of `5000` ms).

After that warning occurs, Wallaby attempts to get a response from its worker process. This is a very fast operation and usually responds in < `1 ms`. Wallaby waits up to `200ms` for a response (e.g. in case the process had hung or some synchronous code was being executed). If no response is given, Wallaby provides the warning that `The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​`. Again, Wallaby is not doing anything at this point except for waiting for your code to finish executing. If nothing happens after this point then it means that you're code has hung `node.js` / `jest` somehow (e.g. may be an infinite loop). In your case, we're not sure why you're getting the message.

You may get this message intentionally by changing your test as shown below:

```javascript
import faker from "faker";

const keepGoingUntil = new Date().getTime() + 5500;
while (new Date().getTime() < keepGoingUntil) {
}

describe("faker tests", () => {
    jest.setTimeout(20000); //(has no effect)
    
    it("it can use faker", () => {
        let adjective = faker.commerce.productAdjective().toLowerCase();
        console.log(adjective);
    });
});
```

In our case, with the code above, Wallaby will always return a result (see `Wallaby Console` below):

```
‍​[Info]​ Started Wallaby.js Core v1.0.1136

--- INITIAL RUN ---

​​[Error] Some long running code has been detected: one of your files is taking more than 5000ms to execute.​​
​​[Error] Execution of the following files has started but has not finished:​​
​​[Error] - test/faker.jest.test.ts​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​
​[Info]​ console.log: Jest: PASS test/faker.jest.test.ts (7.248 s)
​[Info]​ console.log: Jest:   ● Console
​[Info]​     console.log
​[Info]​       handcrafted
​[Info]​       at console.t.<computed> (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.311/wallabyed00a4/runners/node/jest@24.8.0/initializer.js:14:18517)
​[Info]​ Finished executing 1 affected test(s) in 7.7 second(s)

--- EDIT TEST ---

​​[Error] Some long running code has been detected: one of your files is taking more than 5000ms to execute.​​
​​[Error] Execution of the following files has started but has not finished:​​
​​[Error] - test/faker.jest.test.ts​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​
​[Info]​ console.log: Jest: PASS test/faker.jest.test.ts (7.2 s)
​[Info]​ console.log: Jest:   ● Console
​[Info]​     console.log
​[Info]​       tasty
​[Info]​       at console.t.<computed> (../../../.vscode/extensions/wallabyjs.wallaby-vscode-1.0.311/wallabyed00a4/runners/node/jest@24.8.0/initializer.js:14:18517)
​[Info]​ Finished executing 1 affected test(s) in 7.62 second(s)
```

In order for us to diagnose further, we need you to provide us with your Wallaby Diagnostics report after you get the warning message. We're expecting that this will have a bit more information. To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by greenmooseSE** [comment]
Thanks. Increasing `longExecutingWarningTimeout` is good enough solution for me. I spent quite a few hours troubleshooting this because I thought it was an error. To help your users in future for this scenario maybe it is a good idea would be to

1. Prefix the message with a 'warning' so one know it is not an error (red to me means error).
2. Provide additional help in the text related to setting, e.g. `To increase the timeout you can use the setting longExecutingWarningTimeout ` or similar.

Attaching diagnostics below.

**Comment by smcenlly** [comment]
Generally speaking, we don't expect people to read (or use) the Wallaby Console unless you're debugging a problem that's not immediately exposed by Wallaby as an error (e.g. in your tests, test output window, etc).

We'll consider updating the message so it's not confusing to others in future.
