### ISSUE TITLE
Local typescript module import

### ISSUE THREAD

**Issue by JANDA-Developers** [wallabyjs/public#2789]
I made a local module with typescript and tried to use it in another project by creating an npm link from (uncompiled).

But I got an error saying it couldn't compile. 
I wonder if this is a part supported by the create react app environment or not.

message...
`Module parse failed: The keyword 'interface' is reserved (10:0`

**Comment by smcenlly** [comment]
> I made a local module with typescript and tried to use it in another project by creating an npm link from (uncompiled).

Does this work for you outside of Quokka?

> I wonder if this is a part supported by the create react app environment or not.

Not quite sure what you mean?

---

Would you be able to provide us with specific example code so we can understand how you have structured your code? Perhaps attach a sample repo that does the same thing with some instructions to run it **outside** of Quokka?

**Comment by JANDA-Developers** [comment]
Sorry I went to wrong repository ㅠㅠ
