### ISSUE TITLE
Wallaby fails when loading a project from Windows mapped drive D

### ISSUE THREAD

**Issue by bhalperin** [wallabyjs/public#2790]
Loading a project in VSCode from a Windows mapped drive D (using `subst`), Wallaby fails to run the tests, showing these message in its console:
```
[Error] No files with tests found, check your tests list patterns.​​
​[Info]​ Can't determine tests to run for the change.
```
Loading the same project from drive C Wallaby is doing fine.

What can I do to make it work if I load the project from a mapped drive?

**Comment by smcenlly** [comment]
Is your project running from the root of the `D` drive or under a folder within that drive?

Could you also please provide us with your Wallaby Diagnostics report? The Wallaby Diagnostics Report is a simple JSON text report that contains some basic information about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
We've been able to reproduce your problem. The problem seems specific to the use of `subst` and everything appears to work when located on a different physical drive. We're investigating the issue.

**Comment by smcenlly** [comment]
The problem appears to be isolated to using `jest` and we believe the root cause is related to jest itself. From the CLI if you run `npx jest --showConfig` you will see that the paths are reported as `C:` instead of `D:`. This is what is causing Wallaby to not load your files/run your tests.

**Comment by smcenlly** [comment]
We've updated Wallaby to support use of `subst` in jest projects in Wallaby core `v1.0.1138`.

**Comment by bhalperin** [comment]
👍 thanks!!!
