### ISSUE TITLE
Coverage & Test Explorer of a project loaded from a mapped drive is not connecting

### ISSUE THREAD

**Issue by bhalperin** [wallabyjs/public#2791]
Side effect of the fix of https://github.com/wallabyjs/public/issues/2790.
The URL of the test explorer in this case is http://localhost:51245/?port=51236, and it fails to connect

**Comment by smcenlly** [comment]
I don't think this is related as it is working for me using the latest production build of Wallaby and the `subst` mapped drive.

Sometimes in Windows environments (especially if you have Hyper-V and/or Docker), the ports can get locked and may no longer work. Can you please try closing all VS Code instances, opening again, starting Wallaby and see if Wallaby App loads for you? If that does not work, please try rebooting.

If it's still not working for you, please provide a screenshot of what you're seeing in the browser as well as your Wallaby Diagnostics report.

**Comment by bhalperin** [comment]
After closing and relaunching VS Code **it's working** again. Now with http://localhost:51245/ (`/?port=51236` no longer appended).
Strange, as I'm not using Docker or anything like it.
Will keep on monitoring. Anyway many thanks for the prompt and effective response! 🥇
