### ISSUE TITLE
Feature request: Stop showing value after enabling "show value"

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2796]
### Issue description or question

When I use show value, it will continue showing the value with every run, and there seems no way to disable it. I see them appear in the Value Explorer, but there does not seem to be a way to remove them.

### Wallaby diagnostics report

IntelliJ

**Comment by smcenlly** [comment]
Wallaby includes a couple of context actions that allow you to stop showing a value after enabling show value:

> **Clear value**: clears Live Values on a line that were displayed by using Show Value action (press Esc to execute the action).
> 
> **Clear file values**: clears all Live Values in a file that were displayed by using Show Value action (press Esc Esc to execute the action).
>
> **Clear all values**: clears all Live Values in all files that were displayed by using Show Value action.
