### ISSUE TITLE
Allow Copy Value to work without selecting the text

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2797]
When binding a mouse shortcut to `Copy Value`, it's more more convenient for it to copy the value from the element under the cursor. Also more convenient for keyboard shortcut too.

If there is a selection though, it should use this.

**Comment by smcenlly** [comment]
Currently `Copy Value` uses the cursor position to determine which value to copy, you do not need any selection. If you have a value selected, it will use the selection as the cursor position. Unless I am mistaken, it already behaves as you have described.

Am I missing something in your request? If so, would you mind explaining the current behavior vs. what you would prefer to happen?

**Comment by vjpr** [comment]
> Currently Copy Value uses the cursor position to determine which value to copy

Does not work for me.

I bound a keyboard shortcut, and also tried via the `Find actions` window. 

NOTE: I am pressing the keyboard shortcut which you can't see...

https://user-images.githubusercontent.com/281413/132772731-0e992454-1e02-4f53-aff8-2ace8fa29a05.mov

**Comment by vjpr** [comment]
```
  editorVersion: 'IntelliJ IDEA 2021.2',
  pluginVersion: '1.0.222',
  editorType: 'IntelliJ',
  osVersion: 'darwin 20.3.0',
  nodeVersion: 'v16.7.0',
  coreVersion: '1.0.1143',
  checksum: 'NzNiMjNlMjY5OGE1ODI4ZTkwOTZlNWQ1ZDM0YmViNmQsMTY1MzM1MDQwMDAwMCww',
```

**Comment by smcenlly** [comment]
Thanks for the screen recording and editor information. Wallaby for JetBrains editors was ignoring `Show Value` if a selection was not made (other editors did not). The latest version of Wallaby for JetBrains editors now behaves consistently with other editors and will use your Caret position if a selection has not been made.

Please update your Wallaby plugin version to `v1.0.224`+ to fix this behavior.
