### ISSUE TITLE
Bug: Wallaby & Quokka extensions causing the status bar to crash in VSCode Insiders

### ISSUE THREAD

**Issue by stephenlaughton** [wallabyjs/public#2798]
### Issue description or question

See https://github.com/microsoft/vscode/issues/133317

### Wallaby diagnostics report

There is no output from VSCode startup in wallaby's console

**Comment by smcenlly** [comment]
Thanks for letting us know. Something changed in the latest insiders that broke Wallaby and Quokka. We'll reply in the Microsoft issue with the details. Please update to the latest Wallaby (`v1.0.313`) and Quokka (`v1.0.401`) VS Code extension versions to fix the problem.
