### ISSUE TITLE
Phantom JS function.prototype.bind issues

### ISSUE THREAD

**Issue by asos-massimo** [wallabyjs/public#280]
On my initial test run, our specs which use function.prototype.bind work fine. But on subsequent ones  when only those tests are run they fail (because of function.prototype.bind being undefined). I presume this is because some of our other specs import knockout, which patches function.prototype.bind. It seems PhantomJS does not support function.prototype.bind. I've solved this for now by including a polyfill JS file in our main wallaby config.

What do you think we should do about this going forwards?

**Comment by ArtemGovorov** [comment]
Yep, for PhantomJs 1.x doesn't support Function.prototype.bind and the polyfill is required. You may either put it in a separate file like you have done or [is done in this sample](https://github.com/wallabyjs/wallaby-react-todomvc-sample/blob/master/wallaby-babel.js#L5). Another option would be to just place the polyfill code into [the bootstrap function](http://wallabyjs.com/docs/config/bootstrap.html) which gets executed before any tests (if nothing before tests requires it), so something like that:

```JavaScript
module.exports = function () {
   return {
     files: [
       ...
     ],

     tests: [
       ...
     ],

     bootstrap: function (w) {
       if (!Function.prototype.bind) {
        Function.prototype.bind = function(oThis) {
          if (typeof this !== 'function') {
            // closest thing possible to the ECMAScript 5
            // internal IsCallable function
            throw new TypeError('Function.prototype.bind - what is trying to be bound is not callable');
          }

          var aArgs   = Array.prototype.slice.call(arguments, 1),
            fToBind = this,
            fNOP    = function() {},
            fBound  = function() {
              return fToBind.apply(this instanceof fNOP && oThis
                  ? this
                  : oThis,
                aArgs.concat(Array.prototype.slice.call(arguments)));
            };

          // test this.prototype in case of native functions binding:
          if (this.prototype)
            fNOP.prototype = this.prototype;
          fBound.prototype = new fNOP();

          return fBound;
        };
      }
     }
   };
 };
```

Once you decide to migrate to PhantomJs 2, which is [supported by wallaby.js](http://wallabyjs.com/docs/integration/phantomjs2.html), the polyfill will not be required any more.

**Comment by ArtemGovorov** [comment]
Hi Massimo, 
closing this one as answered, 
please let me know if I can add more details to the answer.
