### ISSUE TITLE
Seems Wallaby ignores Jest's projects configuration settings

### ISSUE THREAD

**Issue by hiredgunhouse** [wallabyjs/public#2804]
I have a monorepo with jest.config.js file at the root of the repository and in that Jest config file I specify paths to my projects using this setting https://jestjs.io/docs/26.x/configuration#projects-arraystring--projectconfig but it seems that Wallaby ignores that.
I could not find information about this in Wallaby docs, is that true or am I doing something wrong?

**Comment by smcenlly** [comment]
If you are using [`automatic configuration`](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) **and** the root folder opened in your editor is the mono-repo root, **and** you have `jest.config.js` in your mono-repo root, then Wallaby will use it (and the projects configuration) to run your jest tests.

By default, Wallaby should behave exactly the same as if you run `npx jest` from your mono-repo root. Can you please check that is the case? If it is behaving the same, please first fix jest outside of Wallaby and then Wallaby will work for you.

If Wallaby is still not working for you, can you please provide your Wallaby Diagnostics report? To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by hiredgunhouse** [comment]
What I have is `jest.config.js` at the root of my monorepo. The `jest.config.js` at the root has `'projects'` section which lists several paths to specific sub-projects in the monorepo and each of those projects has its custom `jest.config.js` (i.e. some sub-projects are React and require JSX support, some are not and don't require certain setup, etc.).
That setup works when I run Jest CLI but Wallaby seems to completely ignore the per-project `jest.config.js` files and only relies on the root `jest.config.js`.

My wallaby.js at the root of the repo is very simple:
```javascript
  return {
    autodetect: true,

    files: [
       //...
    ],
    tests: [
      //...
    ],
    // needed cause otherwise Wallaby will try to run tests in browser
    testFramework: 'jest',
    env: {
      type: 'node',
    },
    debug: true,
    trace: true,
  }
}
```

**Comment by hiredgunhouse** [comment]
btw. automatic configuration does not work at all, it does not find any tests.

**Comment by hiredgunhouse** [comment]
I also tried to create a Jest configuration specific to Wallaby, but this does not seem to work at all (I have created a separate issue #2815 for this):
```
    testFramework: {
      configFile: './jest.config.wallaby.js'
    },
```

**Comment by hiredgunhouse** [comment]
I'm wondering if you have an example of a working Lerna monorepo with a real-world type of project (i.e. two React apps and some library package, etc.). I saw some very simple example somewhere provided by your team but it's far from real-world. I would suggest that you try to run Wallaby in a few of the more popular projects listed on Lerna's website.

**Comment by smcenlly** [comment]
Could you please confirm that `jest` is installed in the `node_modules` of your mono-repo root? If not, you will need to install it.

As [requested above](https://github.com/wallabyjs/public/issues/2804#issuecomment-926229529), could you also please provide your Wallaby Diagnostics report, it contains a few details that we need to start troubleshooting most issues. If you are not comfortable publishing the details publicly please email it to hello@wallabyjs.com.

**Comment by smcenlly** [comment]
I'm going to assume that our suggestion helped you. Closing this issue. Please feel free to reply and we will re-open if you're still having problems.
