### ISSUE TITLE
`Failed to load configuration file` CJS/ESM confusing error

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2806]
### Issue description or question

Using IntelliJ.

My project has `type: 'module'`, and I get both these messages printed. I am using an ESM module.

I am guessing it tries to parse the file as CJS, and if that fails, then it tries ESM.

The problem is that anyone who runs it sees the CJS error message and tries to fix that (and I sometimes make this mistake myself).

1. The issue that is important is actually `SyntaxError: Unexpected string` but it is hidden at the bottom. 

2. Also, there is no stack trace which makes it very hard to debug.

    In this case, the `unexpected string` happens because my ESM module imports a CJS module with `.js` extension. But its still hard to track down.

3. Can we load config async?

```
Failed to load configuration file: 
-----------------------------
CommonJs config loading error
-----------------------------
Error [ERR_REQUIRE_ESM]: require() of ES Module ./wallaby.ava.js from [wallaby core]/server.js not supported.
wallaby.ava.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename wallaby.ava.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in ./package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

------------------------------
ES module config loading error
------------------------------
SyntaxError: Unexpected string
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html

```

### Wallaby diagnostics report

...

**Comment by ArtemGovorov** [comment]
Thanks for the report. 

> I am guessing it tries to parse the file as CJS, and if that fails, then it tries ESM.

Yes, it's exactly the way it works.

> The issue that is important is actually SyntaxError: Unexpected string but it is hidden at the bottom.

We have changed the error message to be more clear about what's going on.

> Also, there is no stack trace which makes it very hard to debug.

This one we can't reproduce unfortunately. It's possible that the error in your case doesn't contain stack trace entries that point to Wallaby config file (only node internals).

> Can we load config async?

Yes, please see the other issue for the update: https://github.com/wallabyjs/public/issues/2808.
