### ISSUE TITLE
Async config file execution

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2808]
### Issue description or question

Can the wallaby config function be a promise? I have an async operation I need to run to generate the `files` config setting. I think top-level await in ESM would allow me to do some async stuff, but it cannot use `wallaby` parameter.

This is what I want to do:

_wallaby.js (pjson#type=module)_

```js
export default async function (wallaby) => {
  const files = await getFiles(wallaby)
  return {files}
}
```

**Comment by ArtemGovorov** [comment]
While it was always possible to have an async config via a callback (ie. `module.exports = (wallaby, done) => done(config)`), promise wasn't supported, but we have now added the support for promise to, so after you update to Wallaby Core v1.0.1151, returning a promise should also work.
