### ISSUE TITLE
Wallby js is not running tests for all the apps in NX repo

### ISSUE THREAD

**Issue by smarigowda** [wallabyjs/public#2809]
Wallby js is not running tests for all the apps in NX repo, see image below. I can not provide the details in public because it will capture project details. Can I get some help ?

![image](https://user-images.githubusercontent.com/1831259/134794535-ec524ad4-af82-4c8a-ace1-6dca8b09dde5.png)

**Comment by ArtemGovorov** [comment]
From the screenshot (see the `only executed ...` label after the number fo tests) it looks like Wallaby is only executing a single test file. It mean that you are either 
- launching an exclusive test run (via [a special command](https://wallabyjs.com/docs/intro/selected-tests.html#exclusive-test-run)) on the `tabs.spec.tsx` file (if that is the case, please start Wallaby via `Start` command and it should run all of your tests), 
- or the the `tabs.spec.tsx` file has [some focussed specs/tests](https://wallabyjs.com/docs/intro/selected-tests.html#automatic-test-focusing), so Wallaby is only running the spec file. It can be a `fit`/`.only` marked test, or a special // file.only comment in the file. Please search the file for `only` string, and if you find it, but believe it's a false positive, please send us an example of the `only` string occurrence in your code to hello@wallabyjs.com for investigation. 

If neither of the suggestions above help, please send us the content of the `tabs.spec.tsx` file to hello@wallabyjs.com for investigation.

**Comment by smarigowda** [comment]
The spec had `.only` in it, that was the issue as you suggested. I am closing this ticket. Thanks for speedy response. Thank you very much for the help.
![image](https://user-images.githubusercontent.com/1831259/134804367-76bf08ab-6d44-49ea-8099-38068cd2110a.png)
