### ISSUE TITLE
Loading a source file from external URL

### ISSUE THREAD

**Issue by chinchiheather** [wallabyjs/public#281]
I am attempting to try out wallaby on my Angular project in WebStorm. I am trying to load the angular auth0 library using a URL ("https://cdn.auth0.com/w2/auth0-angular-4.0.1.min.js") in the files section of my wallaby config, but something seems to be going wrong. It is failing to find the auth0 module, and erroring in my tests due to this. Either it is not loading it from the URL, or it is not waiting for it to be loaded before running my tests... Is there anything I can do to fix this? Thanks!

**Comment by ArtemGovorov** [comment]
Wallaby.js doesn't support URLs in the `files` or `tests` list. I'd recommend just downloading the library and referencing it locally, as it's just faster than downloading it for your tests.

If it's not an option to download and reference it locally, you may create a file that downloads the library it and reference the file. You may have a look [how it's done in the sample](https://github.com/wallabyjs/wallaby-external-script). [This file](https://github.com/wallabyjs/wallaby-external-script/blob/master/googleMapsApi.js) downloads the remote lib and is referenced from `files` list. Please note that you need to specify [a flag for phantomjs in your wallaby config](https://github.com/wallabyjs/wallaby-external-script/blob/master/wallaby.js#L12) in this case.

Please let me know if it addresses your issue and answers your question.

**Comment by chinchiheather** [comment]
Thank you, that's solved it for me :)
