### ISSUE TITLE
Specifying custom config file name does not work

### ISSUE THREAD

**Issue by hiredgunhouse** [wallabyjs/public#2815]
This example from the docs (https://wallabyjs.com/docs/integration/jest.html#overriding-automatic-configuration) does not work:
```javascript
module.exports = () => {
  return {
    // tell wallaby to use automatic configuration
    autoDetect: true,

    testFramework: {
      // the jest configuration file path
      // (relative to project root)
      configFile: './jest.config.wallaby.js'
    }
  }
};
```
even though I have jest.config.wallaby.js file in my project root I get this error 
```
Failed to load configuration file: TypeError: Cannot read property 'indexOf' of undefined
Please refer to our docs: https://wallabyjs.com/docs/config/overview.html
```

**Comment by smcenlly** [comment]
It is working for us with the Wallaby.js configuration that you provided. Could you please try this sample repo that we have created (clone, install and select to use the `wallaby.js` configuration)?

https://github.com/wallabyjs/wallaby-2815

Is it possible that you are using an older version of Wallaby with an expired license? If so, this feature may not be available which may explain why you are getting the error.

If Wallaby is still not working for you, can you please provide your Wallaby Diagnostics report? To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
Closing this issue as we're assuming it is working for you or you are using an expired license where this is not supported. If you need a trial license to use the latest version you may request a trial from our website or else email us hello@wallabyjs.com.
