### ISSUE TITLE
Wallaby value explorer is appearing in the incorrect activity bar menu

### ISSUE THREAD

**Issue by benthomasknight** [wallabyjs/public#2817]
### Wallaby value explorer is appearing in the incorrect activity bar menu

The wallaby activity menu has gone and the value explorer and coverage tool are appearing in the git menu. As you can see in the screenshot below I am in the git menu and the value explorer and coverage tools are at the bottom of the list.

![Screen Shot 2021-09-28 at 5 06 54 pm](https://user-images.githubusercontent.com/20388953/135040084-462652d4-7d97-4ede-a59a-d41cf312ef7f.png)

**Comment by ArtemGovorov** [comment]
By default, Wallaby creates a dedicated sidebar item for the Wallaby Tools (Value Explorer, Test File Coverage and Debugger). It is however possible to drag&drop VS Code sidebar views into other sidebars. Perhaps you have accidentally dragged and dropped Wallaby tools into the Source Control side view? Either way, it should be easy to fix, you may just drag Wallaby Views back to the sidebar. Here's a short video of me dragging the views to the Source Control and back:


![w2817](https://user-images.githubusercontent.com/979966/135050376-712c2df1-6720-4cb0-83a5-d88d0b3ab159.gif)

If the issue persist after fragging the views back to the sidebar, please let us know and we'll further investigate it.

**Comment by smcenlly** [comment]
Note: you may also use the VS Code command, `View: Reset View Locations` to reset view locations and put the Wallaby Tools back to their original position (applies to all views, not just Wallaby).
