### ISSUE TITLE
Checkout Fastspring - Enter coupon code

### ISSUE THREAD

**Issue by sectore** [wallabyjs/public#282]
I got a coupon code and wanted to use it to buy wallaby today. It seems that the [checkout process of Fastspring ('Freedom' Named User License)](https://sites.fastspring.com/wallabyjs/instant/freedom-personal) does not support a field to enter this code. Or miss I something?

**Comment by ArtemGovorov** [comment]
Just add `?coupon=your_coupon_code` at the end of the URL and refresh the page. Send me an email to wallabyjs@gmail.com if doesn't work for you.
