### ISSUE TITLE
Async compiler

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2822]
### Issue description or question

> a compiler function can be sync or async.

https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler

Does this mean promise or just callback?

I'm having some odd problems trying to use async.

```
async file => return await compile(...)
```

Error is:

```
2021-09-30T23:20:14.994Z project Error: Failed to run compilers on repos/vjpr/packages/obs/cli/src/server/index.ts, Processor must pass a string, an object with code property or an error to done function.
```

Works:

```
  return (file, cb) => {
    compile({file, config, shouldLog})
      .then(res => cb(res))
      .catch(e => cb(e))
  }
```

**Comment by smcenlly** [comment]
Only callback is supported through the compiler API.
