### ISSUE TITLE
SWC support

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2823]
Just going to leave this here as a reference for options for using SWC.

## Summary of options for SWC support

Just thought I would leave a summary of SWC support options here too.

### Use JS visitor API (`@swc/core/Visitor`)

Apparently API is being removed. Code available above in this thread.

### Use `swc#parse`

SWC has a `parse` method that returns a JSON AST.

~API is also being removed.~ They are keeping it! https://github.com/swc-project/swc/issues/2123#issuecomment-903445282

Also, currently it is slow. https://github.com/swc-project/swc/issues/2175 - Speed up parse()

The AST is non-standard too. There are issues discussing compatibility here:

https://github.com/swc-project/swc/issues/2123 - Babel compatible AST
https://github.com/swc-project/swc/issues/1392 - ESTree compatible AST
https://github.com/swc-project/swc/issues/246 - Using SWC AST for eslint

### Use SWC for transform, and Babel for parsing

Probably negates the speed benefits.

### Use ESbuild for Wallaby code parsing/compilation

~This might have better standard AST support than Babel.~

~Just need a way to go from AST -> Wallaby ranges.~

ESBuild does not expose the AST. https://github.com/evanw/esbuild/issues/201

It is very locked down regarding plugins/AST as part of its philosophy.

### Just use Babel / TS

Slower than what is theoretically possible natively, but guaranteed to work, and supported natively by Wallaby.

### Wrap `@swc/core`

> kdy1: I think a new node binding built on top of swc will be the best.

https://github.com/swc-project/swc/pull/2320#issuecomment-931260222

There is [`next-swc`](https://github.com/vercel/next.js/tree/canary/packages/next/build/swc), which implements a new binding wrapping `@swc/core`. The Rust Cargo package systems makes it quite easy to extend SWC as necessary.

The advantage of this approach is that converting the AST's to JSON is a bottleneck, so a wrapper can extract just the ranges during the parsing process causing zero overhead.

**Comment by smcenlly** [comment]
**Please read: https://github.com/wallabyjs/public/issues/2818#issuecomment-931807152** for additional context re: this issue.

**Comment by vjpr** [comment]
Managed to get it working using a simple Rust wrapper: https://github.com/vjpr/swc-wallaby

Now on the user-side, you only need SWC.

**Comment by patroza** [comment]
So how does one now use SWC with wallaby?

**Comment by smcenlly** [comment]
@patroza - what are you using as your testing framework?

**Comment by patroza** [comment]
> @patroza - what are you using as your testing framework?

Jest with swc

**Comment by ArtemGovorov** [comment]
@patroza If swc is configured and working for your with Jest CLI (ie. you can run `npx jest` from your repo's root and it works), then there's no special Wallaby config is required, you may [simply start Wallaby on the project](https://wallabyjs.com/docs/integration/jest.html#starting-wallaby-on-a-project-with-configured-jest) and ti should work.
