### ISSUE TITLE
AVA with ESM requires `worker.restart = true`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2824]
### Issue description or question

Before I set `restart = true`, changes in files outside of the test file would not update. They would just show old values.

Is there are way to get it working such that I don't need to restart workers?

Is there a cache I need to clear somewhere?

**Comment by vjpr** [comment]
I noticed you added `?update=xxxx` to the test import. Is this attempting to cache-bust?

```
file:///Users/Vaughan/Library/Application%20Support/JetBrains/IntelliJIdeaVaughan/system/wallaby/projects/3947423c19a8649a/instrumented/repos/vjpr/packages/obs/cli/lib/index.test.ava.js?update=1633059515473&wallaby=true:14:26
```

**Comment by smcenlly** [comment]
> I noticed you added ?update=xxxx to the test import. Is this attempting to cache-bust?

Yes

> ~UPDATE: So I have added `?update=${+new Date()}` in my `--experimental-loader` `resolve(specifier, context, defaultResolve)` hook, and it works!~
> 
> Wasn't actually working...

It's working for us. It seems to work in the `issue-wallaby-ava` project that you previous shared with us. I wonder if it's related to node version? Does `issue-wallaby-ava` show new values on files outside the test file for you?

**Comment by vjpr** [comment]
I think it might have been related to one of the other issues I posted that was resolved recently.
