### ISSUE TITLE
Teardown doesn't execute when `workers: restart`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2828]
### Issue description or question

This was unexpected.

I would prefer to be able to run something after all my tests regardless of whether `workers.restart = true`.

Maybe a separate function called `after`. My present use case is timing the execution of workers, to see if any are slow. I might also want to close database connections and things like that.

Whatever the case, it should be mentioned in the docs.

Potentially throw an error if a `teardown` is set, but `workers.restart = true`.

**Comment by smcenlly** [comment]
We actually think that the `teardown` should execute when `workers.restart` is set to `true`. Previously we had tried to terminate processes/restart as fast as possible, but if you have a `teardown` function configured, there's no reason to not execute it with `restart` set to `true`. 

Wallaby core `v1.0.1160` will now run `teardown` even when `workers.restart` is `true`. If someone doesn't want that behavior, then our advice is to not configure a `teardown` function.
