### ISSUE TITLE
Cannot find files/folders inside of any directory outside of src

### ISSUE THREAD

**Issue by YizYah** [wallabyjs/public#2836]
**NOTE** per your request on your [Troubleshooting page](https://wallabyjs.com/docs/intro/troubleshooting.html),  please refer to the minimized problematic repo at [minimalWallabyWannabe](https://github.com/YizYah/minimalWallabyWannabe).

### Issue description or question
I cannot import a file within the test directory into a test file.

The `test/sample.test.ts` file is passing when run directly.  But for some reason, the Wallaby.js Tests OUTPUT shows
```
Cannot find module './data' 
  ​​​​​at Object.<anonymous> ​​​​​​test/sample.test.ts:2​
```

In your documentation at [Troubleshooting](https://wallabyjs.com/docs/intro/troubleshooting.html), you specify that 

>   If you are running tests in node.js and getting a Cannot find module error or other ‘file not found’ type of issues, please make sure that files that you are trying to load are listed in the files list. Wallaby.js uses its own cache, so it has to copy used files there. Note that this does not apply to the node_modules folder, as wallaby.js doesn’t cache it and uses your local version of it. So, no need to list node modules in the files list for your node tests (but it may be required for browser tests if you are using node modules as libs).

But you can see that I added a reference to the file directly in the files list of the `wallaby.js` document:
```
    files: [
      'src/**/*.ts',
      'test/data.ts',
    ],

```
I have found that in fact I cannot get the `data.ts` file to be seen anywhere but in the `src` directory.

### Wallaby diagnostics report
Too long to be submitted directly as text.  Added here as a file.
[WallabyDiagnosticsReport.txt](https://github.com/wallabyjs/public/files/7337675/WallabyDiagnosticsReport.txt)

**Comment by ArtemGovorov** [comment]
Thanks for sharing the sample repo. We've tried it and it is working for us as is:

<img width="807" alt="Screen Shot 2021-10-13 at 9 43 54 pm" src="https://user-images.githubusercontent.com/979966/137126376-69d40df2-9aef-46f0-ae76-821fc5fb5562.png">

Your diagnostics report however indicates that you have a slightly different config, specifically:

```
    files: [
      'src/**/*.ts',
      'test/data/**.*.ts', //<----- 
    ],
```

The pattern is not including the `test/data.ts` file, so the `Cannot find module './data'` result is expected. If you fix the `files` patterns, for example like this:

```
    files: [
      'src/**/*.ts',
      'test/**/*.ts',
      '!test/**/*.test.ts'
    ],
```

then it should work for you.
