### ISSUE TITLE
retrieve license

### ISSUE THREAD

**Issue by db** [wallabyjs/public#284]
How do I retrieve my license key?

**Comment by ArtemGovorov** [comment]
You may find your license key in the `key.lic` file located at
- on Windows: `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.WebStorm10\system\wallaby\`
- on OSX: `~/Library/Caches/WebStorm10/wallaby/`
- on Linux: `~/.WebStorm10/wallaby/`

(assuming you are using WebStorm 10, if not just replace it in the path with your IDE version).

If you have lost the key and the email with the key that we have sent you when you purchased the license, please send us an email at wallabyjs@gmail.com and we will sort it out.
