### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by josepa333** [wallabyjs/public#2846]
### Issue description or question

Hi! I'm trying to get Wallaby to run on my Angular Project(11.2.14), I installed the library and when I run the Select Configuration => Project Directory or Custom Directory it starts running and then I get the following message:

[Error] FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
​​
​​[Error]  1: 00007FF637DC89AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
​​
​​[Error]  2: 00007FF637DA34E6 node::MakeCallback+4534
​​
​​[Error]  3: 00007FF637DA3E60 node_module_register+2032
​​
​​[Error]  4: 00007FF6380C2F4E v8::internal::FatalProcessOutOfMemory+846
​​
​​[Error]  5: 00007FF6380C2E7F v8::internal::FatalProcessOutOfMemory+639
​​
​​[Error]  6: 00007FF6382A9674 v8::internal::Heap::MaxHeapGrowingFactor+9620
​​
​​[Error]  7: 00007FF6382A0656 v8::internal::ScavengeJob::operator=+24550
​​
​​[Error]  8: 00007FF63829ECAC v8::internal::ScavengeJob::operator=+17980
​​
​​[Error]  9: 00007FF6382A79F7 v8::internal::Heap::MaxHeapGrowingFactor+2327
​​
​​[Error] 10: 00007FF6382A7A76 v8::internal::Heap::MaxHeapGrowingFactor+2454
​​
​​[Error] 11: 00007FF6383D1D17 v8::internal::Factory::NewFillerObject+55
​​
​​[Error] 12: 00007FF63844EF06 v8::internal::operator<<+73494
​​
​​[Error] 13: 0000023D4065C6C1 
​​

I tried increasing the size of the setx NODE_OPTIONS "--max_old_space_size=8192" but no luck.

**Comment by smcenlly** [comment]
Do you get the same problem with you run your tests outside of Wallaby (i.e. using the CLI)?

I'm assuming that Wallaby crashes and you are unable to [generate a diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)?

If possible, could you also please try on a different PC to see if there is something environmental going wrong?

**Comment by josepa333** [comment]
I don't get the same error outside of Wallaby.
Yeah, it crashes before it allows me to generate the report, I checked on the sample project and everything works fine.
I did, I tried on a teammate's PC and he got the same stuff, it definitely is enviromental related, the project might be a little to big for the extension.

**Comment by smcenlly** [comment]
There are a few similar previous issues that you should refer to first:

**increase memory size globally (sounds like you have already tried this)**
* https://github.com/wallabyjs/public/issues/2619
* https://github.com/wallabyjs/public/issues/2583 - 

**Change tsconfig target from es5 to es2015**
* https://github.com/wallabyjs/public/issues/2711

---

Please also confirm that the memory size changes has taken effect by running the following from the CLI:

```
> node
> require('v8').getHeapStatistics().heap_size_limit / (1024 * 1024)
```

**Comment by smcenlly** [comment]
Since we haven't heard back, assuming that you solved your problem with the suggestion above. Closing the issue.
