### ISSUE TITLE
Wallaby.js Automatic configuration stops working in project after upgrade to Webpack 5

### ISSUE THREAD

**Issue by snorkpete** [wallabyjs/public#2847]
### Issue description or question

I was successfully using Wallaby.js using Automatic Configuration with an internal Typescript-based project without any issues, until the project was updated to Webpack 5. Unfortunately, I am not part of the team that performed that upgrade so I don't have a lot of insight into what was changed beyond switching to Webpack 5, but after the upgrade, Wallaby no longer runs. I get the error below:

`Automatic Jest configuration error: Failed to read Jest configuration from '.': Cannot read properties of undefined (reading 'includes')
`

I tried to get the diagnostics report to attach it here, but it seems that because Wallaby doesn't actually load up, the report is not available at all.  Of course, I have verified that the unit tests can run with Jest from the command line.

I know that this issue currently does not give any actionable issue, so I assume that I will need to provide more information to help troubleshoot the issue.  It's an internal project that I can't share fully, and it's a monorepo that which adds to the complexity, but I can try to provide info as needed (jest configuration files, package.json etc).  I'm not sure what might be needed, so just let me know, and I'll try to share it asap.

**Comment by ArtemGovorov** [comment]
Since you are using Jest for your tests, Webpack specific changes should not affect running Wallaby/Jest. It's more likely there's been some Jest config/version changes that may have caused the issue. 

Can you please update your Wallaby Core [to the latest version 1.0.1173](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), we have added some more detailed error reporting to figure out from what part of Jest the error is coming from. After updating can you please reproduce the issue and share:
- the new error message (should include the error stack),
- project's Jest config,
- `package.json` file.

**Comment by ArtemGovorov** [comment]
The error is coming from Jest internals, and is likely to be related to some Jest config/version changes. Can you please 
[the latest Wallaby core v1.0.1173](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) where we have added some more error details, run Wallaby and share:
- the new error message (should now include error stack),
- jest configuration file,
- package.json file.

**Comment by snorkpete** [comment]
The Stack Trace of the Error:

Automatic Jest configuration error: Failed to read Jest configuration from '.': TypeError: Cannot read properties of undefined (reading 'includes')
    at Object.<anonymous> (/Users/<USERNAME>/workspace/micro-frontends/jest.config.js:7:34)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (./jest.config.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at readConfigFileAndSetRootDir (/Users/<USERNAME>/workspace/micro-frontends/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:119:22)
    at readConfig (/Users/<USERNAME>/workspace/micro-frontends/node_modules/jest-config/build/index.js:217:65)
    at Object.readConfigs (/Users/<USERNAME>/workspace/micro-frontends/node_modules/jest-config/build/index.js:406:32)
    at new Promise (<anonymous>)
    at new Promise (<anonymous>)
    at new Promise (<anonymous>)



The Jest Config
As mentioned, my project is part of a mono-repo, so will have to share multiple configs. Some of our build system is also developed internally as wrappers around webpack (and, quite frankly,  seems like black magic to me). I unfortunately can't include those libraries. but hopefully, the info below is helpful without those.

Please, of course, let me know if you need more info.  We might have to resort to email depending on what it is, but don't hesitate to ask if you need more.


-----------------------------
<MYPROJECT>/jest.config.js
-----------------------------

const parentJestConfig = require('../jest.config.js');

/* eslint-disable max-len, no-undef */
module.exports = {
  // extend parent jest configuration
  ...parentJestConfig,

  // Indicates whether the coverage information should be collected while executing the test
  collectCoverage: true,

  // An array of glob patterns indicating a set of files for which coverage information should be collected
  collectCoverageFrom: ['<MYPROJECT>/patterns/**/*.{js,jsx,ts,tsx}'],

  // The directory where Jest should output its coverage files
  coverageDirectory: 'coverage',

  // An array of regexp pattern strings used to skip coverage collection
  coveragePathIgnorePatterns: [
    '<MYPROJECT>/scripts',
    'd.ts',
    'types.ts',
    'index.ts',
    'index.js'
  ],

  // An object that configures minimum threshold enforcement for coverage results
  coverageThreshold: {
    '**/*.{js,jsx,ts,tsx}': {
      lines: 1
    }
  },

  // The root directory that Jest should scan for tests and modules within
  rootDir: '../',

  preset: 'ts-jest'
};


The Root Jest Configs (sorry, it's again multiple files). I'm including the integration config just for completeness, but  i'm only running the unit tests

------------
jest.config.js
-------------

const all = require('./jest.all.config');
const unit = require('./jest.unit.config');
const integration = require('./jest.integration.config');

const npmLifeCycleEvent = process.env.npm_lifecycle_event;

const isUnit = npmLifeCycleEvent.includes('unit');
const isIntegration = npmLifeCycleEvent.includes('integration');
const isAll = npmLifeCycleEvent.includes('all') || (!isUnit && !isIntegration);

module.exports = {
  ...(isAll ? all : {}),
  ...(isUnit ? unit : {}),
  ...(isIntegration ? integration : {})
};


--------------
jest.unit.config
---------------

const allConfig = require('./jest.all.config');

module.exports = {
  ...allConfig,

  testPathIgnorePatterns: ['/node_modules/', '/.<OTHER_PROJECTS_BUILD_OUTPUT_DIR>/'],

  testPathIgnorePatterns: [
    '/node_modules/',
    '/<OTHER_PROJECTS_BUILD_OUTPUT_DIR>/',
    '/tests\\/integration/',
    '.+\\.(?:integration.test|integration.spec)\\.(jsx?|tsx?)$'
  ]
};


-------------
jest.all.config
--------------
/* eslint-disable max-len, no-undef */
module.exports = {
  // when this config is extended, set the rootDir to the same level as this file
  rootDir: __dirname,
  
  // Automatically clear mock calls and instances between every test
  clearMocks: true,

  // Indicates whether the coverage information should be collected while executing the test
  collectCoverage: true,

  // An array of glob patterns indicating a set of files for which coverage information should be collected
  collectCoverageFrom: [
    '{mfes,MYPROJECT/patterns}/**/*.{js,jsx,ts,tsx}',
    '!{mfes,MYPROJECT/patterns}/**/*{spec,test,foundry}.{js,jsx,ts,tsx}',
    '!**/*.d.ts',
    '!**/*.config.js'
  ],

  // The directory where Jest should output its coverage files
  coverageDirectory: 'coverage',

  // An array of regexp pattern strings used to skip coverage collection
  coveragePathIgnorePatterns: ['/node_modules/', '/<OTHER_PROJECTS_BUILD_OUTPUT_DIR>/', '/coverage/'],

  coverageReporters: ['text', 'cobertura', 'html', 'lcov'],

  // A set of global variables that need to be available in all test environments
  // when using ts-jest, pick the local typescript configuration
  globals: {
    'ts-jest': {
      tsconfig: './tsconfig.json'
    }
  },

  // An array of file extensions your modules use
  moduleFileExtensions: ['js', 'json', 'jsx', 'ts', 'tsx'],

  // A list of paths to directories that Jest should use to search for files in
  roots: [process.cwd()],

  // The test environment that will be used for testing
  testEnvironment: 'jsdom',

  // An array of regexp pattern strings that are matched against all test paths, matched tests are skipped
  testPathIgnorePatterns: ['/node_modules/', '/<OTHER_PROJECTS_BUILD_OUTPUT_DIR>/'],

  // The regexp pattern Jest uses to detect test files
  testRegex: '.+\\.(?:test|spec)\\.(jsx?|tsx?)$',

  // This option sets the URL for the jsdom environment. It is reflected in properties such as location.href
  testURL: 'http://localhost',


  // An array of regexp pattern strings that are matched against all source file paths, matched files will skip transformation
  transformIgnorePatterns: [
    '<rootDir>/node_modules/(?!<OUR_CUSTOM_LIBRARY_OF_MOCKS>)'
  ],

  // Indicates whether each individual test should be reported during the run
  verbose: true,

  setupFiles: ['<rootDir>/jest.setup.js'],

  // A map from regular expressions to paths to transformers
  transform: {
    '\\.jsx?$': ['babel-jest', { rootMode: 'upward' }],
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)':
      '<rootDir>/<MYPROJECT>/utils/fileTransformer.js'
  },

  // A map from regular expressions to module names that allow to stub out resources with a single module
  moduleNameMapper: {
    '\\.css$': 'identity-obj-proxy',
    '\\.svg(\\?external)?$':
      'OUR_CUSTOM_LIBRARY_OF_MOCKS/dist/svgrMock.modern.js',
    '^@testing-library/react$': '<rootDir>/<MYPROJECT>/utils/test-utils.js',
    '^uuid$': '<rootDir>/<MYPROJECT>/utils/uuid-test-mock.js',
    '<OUR_CUSTOM_LIBRARY>/react-error-reporter':
      '<OUR_CUSTOM_LIBRARY_OF_MOCKS>/dist/reactErrorReporterMock.js'
  }
};


------------------------
jest.integration.config.js
-------------------------
const allConfig = require('./jest.all.config');

delete allConfig.testRegex;

module.exports = {
  ...allConfig,

  coverageDirectory: 'coverage/integration',

  testPathIgnorePatterns: ['/node_modules/', '/<OTHER_PROJECTS_BUILD_OUTPUT_DIR>/'],

  testMatch: [
    '**/integration/**/?(*.)+(spec|test).[jt]s?(x)',
    '**/?(*.)+(integration.spec|integration.test).[jt]s?(x)'
  ]
};




------------
jest.setup.js
-------------
import MutationObserver from '@sheerun/mutationobserver-shim';

// We're reusing same jest.config.js for different environments.
// In node environment (which Playwright uses), there is no window.
if (typeof window !== 'undefined') {
  window.MutationObserver = MutationObserver;
}


-----------------------------
<MYPROJECT>/package.json
-----------------------------

{
  "name": "MYPROJECT",
  "version": "0.2.0",
  "license": "UNLICENSED",
  "files": [
    "patterns/**/*.js",
    "!patterns/**/*.foundry.js",
    "patterns/**/*.css"
  ],
  "scripts": {
     ......
    "test": "jest --maxWorkers=3",
    
  },
  "devDependencies": {
    "@babel/preset-typescript": "7.15.0",
      ....... (3 internal company packages for managing icons and translations etc)
     "@loadable/webpack-plugin": "5.15.1",
    "@teamsupercell/typings-for-css-modules-loader": "2.4.0",
    "change-case": "4.1.1",
    "plop": "2.7.4",
    "style-loader": "3.2.1",
    "ts-loader": "9.2.5"
  },
  "dependencies": {
    ...... (only 2 internal company packages)
    "react-copy-to-clipboard": "5.0.2"
  },
  "sonarqube": {
    "source": [
      "./**"
    ],
    "coverageExclusions": [],
    "exclusions": [
      ".foundry",
      ".plop",
      "dist",
      "**/*.foundry.tsx",
      "**/*.test.tsx",
      "**/*.test.ts",
      "**/*.foundry.jsx",
      "**/*.test.jsx",
      "**/*.test.js",
      "**/*.config.js"
    ],
    "testInclusions": [
      "**/*.test.tsx",
      "**/*.test.ts",
      "**/*.test.js",
      "**/*.test.jsx",
      "**/*.spec.tsx",
      "**/*.spec.ts",
      "**/*.spec.js",
      "**/*.spec.jsx"
    ],
    "coverageResults": [
      "../coverage/lcov.info"
    ],
    "eslintResults": "eslint.json"
  }
}


-----------------------
<ROOT>/package.json
-----------------------
{
  "name": "MONOREPO-NAME",
  "private": true,
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "workspaces": {
    "packages": [
      "mfes/*",
      "MYPROJECT"
    ]
  },
  "scripts": {
    ........
  },
  "dependencies": {
    "@apollo/client": "3.3.17",
    ..... (a bunch of internal packages)
    "@types/classnames": "2.2.10",
    "@types/lodash": "4.14.161",
    "@types/prop-types": "15.7.3",
    "@types/react": "16.9.37",
    "@types/react-dom": "16.9.9",
    "@types/react-helmet": "6.0.0",
    "@types/react-router": "5.1.8",
    "@types/react-router-dom": "5.1.8",
    "@types/uuid": "8.3.0",
    "classnames": "2.2.6",
    "formik": "2.2.9",
    "graphql": "15.6.1",
    "lodash": "4.17.15",
    "pm2": "4.5.5",
    "postcss": "8.3.6",
    "prop-types": "15.7.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-helmet": "5.2.1",
    "react-intersection-observer": "8.26.2",
    "react-router": "5.2.0",
    "react-router-dom": "5.2.0",
    "typescript": "4.4.2",
    "uuid": "8.3.2"
  },
  "devDependencies": {
    "@babel/core": "7.15.8",
     .... some more internal packages
    "@graphql-eslint/eslint-plugin": "2.2.0",
    "@svgr/webpack": "^4.3.3",
    "@testing-library/jest-dom": "5.3.0",
    "@testing-library/react": "10.0.2",
    "@testing-library/react-hooks": "5.0.3",
    "@testing-library/user-event": "12.6.0",
    "@types/jest": "26.0.0",
    "@types/node": "14.14.31",
    "@types/testing-library__react": "10.0.1",
    "@types/uuid": "8.3.0",
    "@typescript-eslint/eslint-plugin": "4.21.0",
    "@typescript-eslint/parser": "4.21.0",
    "apollo": "2.33.6",
    "babel-jest": "^24.8.0",
    "babel-preset-razzle": "^3.0.0",
    "concurrently": "6.0.2",
    "eslint": "7.9.0",
    "eslint-config-prettier": "8.1.0",
    "eslint-import-resolver-typescript": "2.5.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "24.3.4",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-prettier": "3.3.1",
    "eslint-plugin-react": "7.23.1",
    "eslint-plugin-react-hooks": "4.2.0",
    "husky": "^3.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "26.0.1",
    "jest-mock-extended": "2.0.4",
    "jest-transform-css": "2.0.0",
    "js-yaml": "4.0.0",
    "precinct": "8.1.0",
    "prettier": "1.19.1",
    "pretty-quick": "1.11.1",
    "semver": "7.3.2",
    "stylelint": "^11.0.0",
    "ts-jest": "26.4.3",
    "ts-node": "10.2.1"
  },
  "resolutions": {
    "netmask": "2.0.1",
    "pac-resolver": "5.0.0",
    "ts-invariant": "0.7.3"
  },
  "prettier": {
    "singleQuote": true
  },
  "engines": {
    "node": ">= 16.10.0 < 17.0.0",
    "yarn": ">= 1.22.0 < 2.0.0"
  },
  "engineStrict": true
}

**Comment by ArtemGovorov** [comment]
Thanks for sharing the additional details. As the error stack indicates, the error is coming from you **ROOT/jest.config.js** file. When running your tests outside of npm test/run, the environment variable `process.env.npm_lifecycle_event` is not set, so the `npmLifeCycleEvent.includes` throws the error.

Depending on what types of test you want to run when the environment variable is not set, you may either fix it like this:

```diff
...
-const npmLifeCycleEvent = process.env.npm_lifecycle_event;
+const npmLifeCycleEvent = process.env.npm_lifecycle_event || '';
...
```

or like this:

```diff
...
-const npmLifeCycleEvent = process.env.npm_lifecycle_event;
+const npmLifeCycleEvent = process.env.npm_lifecycle_event || 'unit';
...
```

**Comment by snorkpete** [comment]
Yes, Artem,  that worked perfectly!

Thank you very much for your quick support!


You guys have made such an awesome product that i can't work without it anymore.... keep up the great work!
