### ISSUE TITLE
Time travel debugger not available when using a nx v12 and v13 workspace on WebStorm

### ISSUE THREAD

**Issue by nicolashzmor** [wallabyjs/public#2849]
### Issue description or question

I'm trying to use Time Travel with a nx workspace and although the tests are running fine, the Time Travel icon remains disabled. Same thing inside the debugger window.

![image](https://user-images.githubusercontent.com/66749276/141180326-b247fa8b-655c-46ce-9be0-5817086595b4.png)

![image](https://user-images.githubusercontent.com/66749276/141180441-31462e6d-1447-491c-be03-ea89be941038.png)

The project is a fresh new nx workspace.

### Wallaby diagnostics report

There is no diagnostic, because there is no evident "error" as so. The Time Travel is simply not available.

**Comment by smcenlly** [comment]
To start the time travel debugger, you need to first place your cursor on a line of code that has a Wallaby coverage indicator. At that point, the feature will become enabled.

We tried a fresh `nx workspace` and it works for us, so assume that this was your problem.
