### ISSUE TITLE
Typo in VSCode Output Inspector Settings

### ISSUE THREAD

**Issue by meanspa** [wallabyjs/public#2850]
In the VSCode settings for Output Inspector: 

```
Wallaby › Output Inspector Feature: Automatic Display Debugger Override
Specifies when Output Inspector is automatically displayed in context of Time Trave Debugger
```

There appears to be a missing L in "Time Travel Debugger"

**Comment by smcenlly** [comment]
Thanks for reporting the problem. It has been fixed and will be available in the next version of the Wallaby for VS Code extension.
