### ISSUE TITLE
EACCES issue when trying to run wallaby

### ISSUE THREAD

**Issue by azaeng04** [wallabyjs/public#2851]
### Issue description or question

I am getting the following error in my IDE when trying to run wallaby. Even after executing `sudo chmod 777 -R $HOME/.nvm`. I still get the following error:

```
‍​​[Error] Error: spawn /home/azariah/.nvm/versions/node/v14.18.1/bin EACCES​​
​​[Error] 	at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)​​
​​[Error] 	at onErrorNT (internal/child_process.js:465:16)​​
​​[Error] 	at processTicksAndRejections (internal/process/task_queues.js:80:21)​​
```

![Screenshot 2021-11-16 at 17 26 01](https://user-images.githubusercontent.com/13921692/142014785-ed3d9a77-cb88-444c-ae7e-5d2c6ae384f4.png)

### Wallaby diagnostics report

I could not get this as wallaby wasn't even running because of above issue. Unless there is another way I can get this?

**Comment by ArtemGovorov** [comment]
- Are you using `"wallaby.node"` setting in VS Code to specify your node path?
- Can you run `ls -l /home/azariah/.nvm/versions/node/v14.18.1/bin` command in terminal and share the output?

**Comment by azaeng04** [comment]
Output:
![Screenshot 2021-11-17 at 01 55 54](https://user-images.githubusercontent.com/13921692/142084751-17cd9ea3-3df7-45a9-9f5f-b1c87f55c4bd.png)

**Comment by ArtemGovorov** [comment]
> Are you using "wallaby.node" setting in VS Code to specify your node path?

**Comment by azaeng04** [comment]
Yes @ArtemGovorov not sure why I have to set it because I have $NODE_HOME set in my ~/.zshrc

**Comment by ArtemGovorov** [comment]
What is the exact value of the `wallaby.node` VS Code setting in your case?

**Comment by azaeng04** [comment]
Under User:
![Screenshot 2021-11-17 at 02 18 22](https://user-images.githubusercontent.com/13921692/142086607-e5019ee0-1c9f-43ec-90b7-919f55d98433.png)

Under Remote:
![Screenshot 2021-11-17 at 02 18 40](https://user-images.githubusercontent.com/13921692/142086635-cac315c6-c06f-44a3-8089-6880900e1934.png)
)

Under Workspace:

![Screenshot 2021-11-17 at 02 19 07](https://user-images.githubusercontent.com/13921692/142086724-697108f4-c013-4774-a5d9-a537f045ad3c.png)

**Comment by azaeng04** [comment]
$NODE_HOME is set to:
![Screenshot 2021-11-17 at 02 21 15](https://user-images.githubusercontent.com/13921692/142086882-677a43fb-0897-4785-99c4-d7362747627e.png)

**Comment by ArtemGovorov** [comment]
Thanks. As specified in [our docs](https://wallabyjs.com/docs/intro/install.html#visual-studio-code), when `wallaby.node` is used, it has to point to the node executable, so try changing the setting value to: `/home/azariah/.nvm/versions/node/v14.18.1/bin/node`.

**Comment by azaeng04** [comment]
Awesome thanks that worked! Thank you!
