### ISSUE TITLE
wallaby with mocha/chai test framework and rushjs monorepo framwork containing typescript+esm modules

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/public#2853]
### Issue description or question

I am evaluating wallaby for my project which uses `mocha` as a test framework and `rushjs` to manage monorepo.

All my packages are esm modules using typescript. For front-end I use svelte and use `cypress` for component testing and `playwright` for e2e testing. I am using `intellij 2021.3 ultimate` where my packages are setup as separate modules. 

I was evaluating wallaby with mocha and was able to make it work for individual `mocha` based library project. I figured that I can run only one instance of wallaby runner at a time. So I cannot run two wallaby instance running two separate package respectively. In any case I would have preferred one wallaby runner for my entire repo. I could not make it work for the entire repo. 

Here's a sample [repo](https://github.com/bhvngt/wallaby-mocha-rushjs) that I have created to evaluate wallabyjs.

Can you help me with setting up wallaby for my project.

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2021.3 RC',
  pluginVersion: '1.0.227',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.1.0',
  nodeVersion: 'v16.11.1',
  coreVersion: '1.0.1179',
  checksum: 'OGQ2Njg4ODI2M2E5YmU2YTI5NmFmYzAyYTYzMjUwOGMsMTYzOTAwODAwMDAwMCwx',
  config: {
    files: [
      { pattern: 'package.json', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: '**/src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: '.env', instrument: false, ignore: false, trigger: true, load: true, order: 3 }
    ],
    tests: [
      { pattern: '**/tests/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 4 },
      { pattern: '**/{web,api,ui,jsonschema-definer}/**', ignore: true, trigger: true, load: true, test: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true }
    ],
    testFramework: { version: 'mocha@2.1.0', configurator: 'mocha@2.1.0', reporter: 'mocha@2.1.0', starter: 'mocha@2.1.0' },
    filesWithNoCoverageCalculated: [ '**/node_modules/**' ],
    env: {
      type: 'node',
      params: { runner: '--experimental-specifier-resolution=node' },
      runner: '<homeDir>/Library/pnpm/nodejs/16.11.1/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    workers: { restart: true, initial: 0, regular: 0, recycle: true },
    debug: true,
    reportConsoleErrorAsError: true,
    diagnostics: {},
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    addModifiedTestFileToExclusiveTestRun: true,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: undefined,
    configCode: "const path = require('path');\n" +
      '\n' +
      'module.exports = function (wallaby) {\n' +
      "\tconst rushjsPath = path.delimiter + path.join(wallaby.localProjectDir, 'common', 'temp', 'node_modules');\n" +
      '\tprocess.env.NODE_PATH += rushjsPath;\n' +
      '\n' +
      '\treturn {\n' +
      '\t\tfiles: [\n' +
      '\t\t\t"package.json",\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: "**/src/**/*.ts"\n' +
      '\t\t\t},\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: "**/node_modules/**",\n' +
      '\t\t\t\tignore: true\n' +
      '\t\t\t},\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: ".env",\n' +
      '\t\t\t\tinstrument: false\n' +
      '\t\t\t}\n' +
      '\t\t],\n' +
      '\n' +
      '\t\ttests: [\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: "**/tests/**/*.test.ts"\n' +
      '\t\t\t},\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: "**/{web,api,ui,jsonschema-definer}/**",\n' +
      '\t\t\t\tignore: true\n' +
      '\t\t\t},\n' +
      '\t\t\t{\n' +
      '\t\t\t\tpattern: "**/node_modules/**",\n' +
      '\t\t\t\tignore: true\n' +
      '\t\t\t}\n' +
      '\t\t],\n' +
      '\t\ttestFramework: "mocha",\n' +
      '\t\tfilesWithNoCoverageCalculated: ["**/node_modules/**"],\n' +
      '\n' +
      '\t\tenv: {\n' +
      '\t\t\ttype: "node",\n' +
      '\t\t\tparams: {\n' +
      '\t\t\t\trunner: "--experimental-specifier-resolution=node"\n' +
      '\t\t\t}\n' +
      '\t\t},\n' +
      '\t\tworkers: { restart: true },\n' +
      '\t\tdebug: true,\n' +
      '\t\treportConsoleErrorAsError: true,\n' +
      '\t\tsetup: () => {}\n' +
      '\t};\n' +
      '}\n'
  },
  fs: { numberOfFiles: 4 },
  debug: [
    '2021-11-25T16:11:05.592Z project Wallaby Node version: v16.11.1\n',
    '2021-11-25T16:11:05.593Z project Wallaby config: <homeDir>/Projects/temp/wallaby-mocha-rushjs/wallaby.cjs\n',
    '2021-11-25T16:11:06.391Z project File cache: <homeDir>/Library/Caches/JetBrains/IntelliJIdea2021.3/wallaby/projects/7fb73c2a0f3955e2\n',
    '2021-11-25T16:11:06.399Z uiService Listening port 51236\n',
    '2021-11-25T16:11:06.410Z workers Parallelism for initial run: 2, for regular run: 2\n',
    '2021-11-25T16:11:06.410Z workers Starting run worker instance #0\n',
    '2021-11-25T16:11:06.411Z workers Starting run worker instance #1\n',
    '2021-11-25T16:11:06.412Z workers Web server is listening at 63039\n',
    '2021-11-25T16:11:06.476Z project Stopping process pool\n',
    '2021-11-25T16:11:06.478Z project File cache is up-to-date, starting full test run\n',
    '2021-11-25T16:11:06.491Z project Running postprocessor\n',
    '2021-11-25T16:11:06.515Z postprocessor New TypeScript language service is required\n',
    '2021-11-25T16:11:06.515Z postprocessor Error parsing tsconfig file <homeDir>/Projects/temp/wallaby-mocha-rushjs/tsconfig.json\n' +
      "(ENOENT: no such file or directory, open '<homeDir>/Projects/temp/wallaby-mocha-rushjs/tsconfig.json')\n",
    '2021-11-25T16:11:06.516Z postprocessor Error reading tsconfig file from <homeDir>/Projects/temp/wallaby-mocha-rushjs/tsconfig.json\n' +
      "(Cannot find module '<homeDir>/Projects/temp/wallaby-mocha-rushjs/tsconfig.json'\n" +
      'Require stack:\n' +
      '- <homeDir>/Library/Caches/JetBrains/IntelliJIdea2021.3/wallaby/wallaby/server.js)\n',
    '2021-11-25T16:11:06.942Z project Postprocessor execution finished\n',
    '2021-11-25T16:11:06.942Z project Test run started; run priority: 3\n',
    '2021-11-25T16:11:06.942Z project Running all tests\n',
    '2021-11-25T16:11:06.944Z workers Starting test run, priority: 3\n',
    '2021-11-25T16:11:06.944Z workers Distributing tests between 2 workers\n',
    '2021-11-25T16:11:06.944Z workers Running tests in parallel\n',
    '2021-11-25T16:11:06.945Z nodeRunner Starting sandbox [worker #0, session #9ifxt]\n',
    '2021-11-25T16:11:06.945Z nodeRunner Starting sandbox [worker #1, session #ohcdp]\n',
    '2021-11-25T16:11:06.945Z nodeRunner Preparing sandbox [worker #0, session #9ifxt]\n',
    '2021-11-25T16:11:06.945Z nodeRunner Preparing sandbox [worker #1, session #ohcdp]\n',
    '2021-11-25T16:11:06.946Z workers Started run worker instance (delayed) #0\n',
    '2021-11-25T16:11:06.947Z nodeRunner Prepared sandbox [worker #0, session #9ifxt]\n',
    '2021-11-25T16:11:06.947Z workers [worker #0, session #9ifxt] Running tests in sandbox\n',
    '2021-11-25T16:11:06.948Z workers Started run worker instance (delayed) #1\n',
    '2021-11-25T16:11:06.949Z nodeRunner Prepared sandbox [worker #1, session #ohcdp]\n',
    '2021-11-25T16:11:06.949Z workers [worker #1, session #ohcdp] Running tests in sandbox\n',
    "2021-11-25T16:11:07.048Z workers Sandbox (active) [ohcdp] error: Cannot read properties of undefined (reading 'should')\n",
    "2021-11-25T16:11:07.051Z workers Sandbox (active) [9ifxt] error: Cannot read properties of undefined (reading 'should')\n",
    '2021-11-25T16:11:07.150Z workers [ohcdp] Run 0 test(s), skipped 0 test(s)\n',
    '2021-11-25T16:11:07.152Z workers [9ifxt] Run 0 test(s), skipped 0 test(s)\n',
    '2021-11-25T16:11:07.156Z workers [ohcdp] Sandbox is responsive, closing it\n',
    '2021-11-25T16:11:07.156Z workers Starting run worker instance #1\n',
    '2021-11-25T16:11:07.156Z workers [9ifxt] Sandbox is responsive, closing it\n',
    '2021-11-25T16:11:07.157Z workers Starting run worker instance #0\n',
    '2021-11-25T16:11:07.157Z workers Merging parallel test run results\n',
    '2021-11-25T16:11:07.157Z project Test run finished\n',
    '2021-11-25T16:11:07.157Z project Processed console.log entries\n',
    '2021-11-25T16:11:07.158Z project Processed loading sequences\n',
    '2021-11-25T16:11:07.158Z project Processed executed tests\n',
    '2021-11-25T16:11:07.158Z project Processed code coverage\n',
    '2021-11-25T16:11:07.177Z project Test run result processed and sent to IDE\n',
    '2021-11-25T16:11:07.541Z workers Started run worker instance (delayed) #0\n',
    '2021-11-25T16:11:07.551Z workers Started run worker instance (delayed) #1\n'
  ]
}
```

**Comment by smcenlly** [comment]
I can see why it's not working for you but I'm not exactly sure as to what the best way of configuring Wallaby is for you with a rush project (as we are not especially familiar with rush). First, let me explain a few problems:

1. Nested `project.json` files are configured to be copied (only for the project root - which doesn't actually exist). This means that nested libs are not treated an `type: module`.

2. When Wallaby runs in a mono-repo, everything has to be homogenous; that is to say that your `tsconfig.json`, testing framework, etc. all have to be compatible so that all of your project tests can run at the same time. Wallaby picks ups the TypeScript configuration from your project root, which for your mono-repo does not exist. When there's no `<root>/tsconfig.json`, Wallaby will use TypeScript defaults (which isn't going to work for your project).

3. When using `esm` (which your projects are doing), `NODE_PATH` is not part of resolving import specifiers.  (see [node docs](https://nodejs.org/api/esm.html)). They recommend:
> Please use symlinks if this behavior is desired.
I guess this means, create `node_modules` symlink in your mono-repo root.

---

Having said all that, we were able to get Wallaby working by performing the following steps:

1. Copy `tsconfig.json` to mono-repo root (could instead [configure TypeScript compiler settings](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) in Wallaby config).
2. Copy `package.json` to mono-repo root from one of the libs, change `name` and run `npm install`. With this file, we don't need to worry about not copying the `lib` `package.json` files (but you could still do this if you wanted).

At this point, everything works for us but I'm aware that this is probably not how you want to do things with a `rush` project. Hopefully this gives you enough information to play around and work out the best way of achieving the result.

---

I'll mark the issue as resolved as I think this gives you enough to solve your problem, but if you're still having problems then please reply and we can re-open it for you.

**Comment by bhvngt** [comment]
Thank you @smcenlly for your response and suggestions. After couple of trials and errors, I could make my monorepo work with wallaby with following setup. So far loving the wallaby experience and quiet excited to use it.

1. All my packages extend from a common `tsconfig.json`, hence I made a symlink to `tsconfig.json` in my root folder.
2. I created a simple `package.json` with `type:module` entry.
3. `rush` keeps all the modules under `common/temp/node_modules`.  So, I created a sym link by the name of `node_module` in the root folder with the target as `common/temp/node_modules`. 
4. I was using `pnpm workspace` but realised that it keeps all of the modules under `.pnpm` sub-folder under the `common\temp\node_modules` folder. Hence, my node modules were not getting picked up by wallaby. I removed `pnpm workspace` (this is the default option in rush). This flattened all the modules under `node_modules`.
5. Last one was little tricky. Rush sym links inter-project dependencies within node_modules of respective projects. I created a root level category folders under node_modules and then sym linked project folders within them. This also ensures that when `common/temp` is deleted, nothing from the project folder gets deleted. For this, It was important to create symlinks under category folders. I kept the creation of these folder and `symlink` under `wallabyjs` setup function.

## Question

- I do have 1-2 projects which uses `jest`. Is it possible for wallaby to process such projects while continue to process rest of the projects using `mocha`?
- Let me know if you see any red flags in terms of best practices.

##
Here's my `wallaby.cjs`

```javascript
module.exports = function (wallaby) {
	return {
		files: [
			"package.json",
			"**/{src,tests,types}/**/!(*.+(test|spec)).ts",
			"!**/node_modules/**",
			{
				pattern: ".env",
				instrument: false
			}
		],

		tests: [
			"**/tests/**/*.+(test|spec).ts",
			"!**/node_modules/**"
		],

		testFramework: "mocha",
		filesWithNoCoverageCalculated: ["**/node_modules/**"],

		env: {
			type: "node",
			params: {
				runner: "--experimental-specifier-resolution=node"
			}
		},
		workers: {restart: true},
		debug: true,
		reportConsoleErrorAsError: true,
		setup: (wallaby) => {
			const dotenv = require("dotenv");
			dotenv.config();
			const fs = require("fs");
			const json5 = require("json5");
			const rushJson = json5.parse(fs.readFileSync(`${wallaby.localProjectDir}/rush.json`, "utf-8"));
			rushJson.projects.map(async (project) => {
				const [packageCategory, packageName] = project.packageName.split("/");
				const categoryDir = `./node_modules/${packageCategory}`
				if (!fs.existsSync(categoryDir)) fs.mkdirSync(categoryDir);
				if (!fs.existsSync(`${categoryDir}/${packageName}`)) {
					console.log("Sym linking", project.packageName);
					const sourcePath = `${wallaby.localProjectDir}/${project.projectFolder}`;
					const targetPath = `${categoryDir}/${packageName}`;
					console.log(`Sym linking ${sourcePath} with ${targetPath}`);
					fs.symlinkSync(sourcePath, targetPath)
				}
			})
		}
	};
}
```

**Comment by ArtemGovorov** [comment]
@bhvngt Awesome, thanks a lot for sharing your solution as it may helps other too!

> Let me know if you see any red flags in terms of best practices.

Your config file looks good to me.

> I do have 1-2 projects which uses jest. Is it possible for wallaby to process such projects while continue to process rest of the projects using mocha?

Unfortunately Wallaby can only run one testing framework at a time. To run Jest tests (separately from your Mocha tests), you may create a separate Run configuration with [running in auto-config mode](https://wallabyjs.com/docs/intro/config.html?editor=jb) that will work if you have Jest configuration in your project's root and `npx jest` works from your repo's root. Alternatively, the Wallaby Jest run configuration may point to a specific subproject with Jest tests (and will only run tests in that subproject).
