### ISSUE TITLE
Help with config file for lit-element-starter-ts repo?

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2859]
### Issue description or question

I don't know how to create a wallaby config file for the repo https://github.com/lit/lit-element-starter-ts in order to make wallbyJS run tests for it.
Do you have an idea of of the content of a `wallaby.js` config file for it?

Thanks!

**Comment by smcenlly** [comment]
We've just taken a look at the starter kit (and `lit`). By default it is using [Web Test Runner](https://modern-web.dev/docs/test-runner/overview/) to bundle the project and to run the tests for the project. Web Test Runner is using [`rollup`](https://rollupjs.org/guide/en/) as its bundler.

Wallaby doesn't integrate with either `rollup` or `web test runner` which means that you're going to need to write some configuration files for Wallaby to run the tests in this project.

We're not exactly sure of the configuration you'll require but recommend to start by first configuring the project to use webpack (quick google search showed [an example](https://github.com/JeremyBernier/lit-element-webpack-hello-world) - not sure if it works).

Once you have webpack configured, you should then be able to configure Wallaby to run your tests with a configuration file that uses webpack ([see our docs](https://wallabyjs.com/docs/integration/webpack-built-in.html)). I _think_ it shouldn't be too hard at this point.

If you have webpack working and can't get Wallaby to work, please share your repo as we should be able to help at that point.

Also, if you create a configuration for the starter, please reply to this issue so it can help others in the future.
