### ISSUE TITLE
Having trouble with babel/polyfill

### ISSUE THREAD

**Issue by forestmarie** [wallabyjs/public#286]
Using wallaby to demo a bunch of ES6 features.  Currently my wallaby configuration is: 

var babel = require('babel');

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: '**/src/*.js', load: true }
        ],

        tests: [
            { pattern: '**/spec/*.js', load: true }
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel,
                // https://babeljs.io/docs/usage/experimental/
                stage: 0
            })
        }
    };
};

The features I'm struggling with are sets, maps, iterables and some of the new array methods such as find, findIndex, etc.  I've read that you need babel/polyfill for sets and maps at least.  

Is there a sample wallaby config bringing in polyfill?

Thanks.

**Comment by ArtemGovorov** [comment]
Sure, you just need one more line in your config, here is the sample - https://github.com/wallabyjs/wallaby-babel-es7-sample/blob/master/wallaby.js#L6

**Comment by forestmarie** [comment]
Worked for me - excellent and thanks for the fast response!  Only delta was my polyfill was at much shorter location: 'node_modules/babel-core/browser-polyfill.js' but I got all the tests green now so thanks again Artem!

**Comment by ruswerner** [comment]
I'm still having this problem even with that config line included.

```
Mon, 23 Nov 2015 23:43:25 GMT wallaby:workers Sandbox (active) [bekaq] error: ReferenceError: Symbol is not defined
Runtime error: ReferenceError: Symbol is not defined
    at Object.<anonymous> (./client/scripts/lib/node-helper.js:34:27)
    at Module._compile (module.js:456:26)
```

```
var babel = require('babel');

module.exports = function(wallaby) {
  return {
    debug: true,
    files: [
      {pattern: 'node_modules/babel/node_modules/babel-core/browser-polyfill.js', instrument: false},
      'client/scripts/**/*.js',
      'client/scripts/**/*.coffee',
      'client/scripts/**/*.jsx'
    ],
    tests: [
      'client/tests/unit/lib/node-helper-spec.js'
    ],
    testFramework: 'mocha',
    delays: {
      edit: 500,
      run: 150
    },
    env: {
      type: 'node',
      runner: '/Users/rus/.nvm/v0.10.40/bin/node'
      //env: 'NODE_ENV=test'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: babel,
        stage: 0
      }),
      '**/*.jsx': wallaby.compilers.babel({
        babel: babel,
        stage: 0
      }),
      '**/*.coffee': wallaby.compilers.coffeeScript({
        // CoffeeScript compiler specific options
      })
    },
    bootstrap: function(wallaby) {
      var mocha = wallaby.testFramework;
      mocha.timeout = 2000;
      mocha.ui = 'bdd';
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
@ruswerner Check if the file `node_modules/babel/node_modules/babel-core/browser-polyfill.js` exists. If you are using npm 3.x, you may need to change it to `node_modules/babel-core/browser-polyfill.js`.

**Comment by ruswerner** [comment]
I'm using npm 2.7.4 and the file exists. Any other suggestions?

```
💻  ~/Development/reactor $ ls -l node_modules/babel/node_modules/babel-core/browser-polyfill.js
-rw-r--r--  1 rus  staff  132331 27 Jun 11:16 node_modules/babel/node_modules/babel-core/browser-polyfill.js
💻  ~/Development/reactor $ npm -v
2.7.4
```

**Comment by ArtemGovorov** [comment]
@ruswerner Oh, sorry, I didn't spot that you are using node environment.
You need to [`require` the polyfill before executing](https://babeljs.io/docs/usage/polyfill/) your tests in node (may either install the module as described in docs, or just require polyfill from babel-core as described below). You may do it in the [bootstrap function](http://wallabyjs.com/docs/config/bootstrap.html):
```
    ...
    compilers: ...
    bootstrap: function () {
      require('babel/node_modules/babel-core/polyfill');
    }
```

**Comment by ruswerner** [comment]
@ArtemGovorov I included it in the bootstrap function and that sorted it. Thanks for the quick help!

**Comment by zivni** [comment]
Suddenly, after upgrading babel version, i Started getting and error about babel polyfill.
This is my wallaby.conf.js file:
```javascript
var webpack = require('webpack');
var babel = require('babel-core');
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');
const webpackPostprocessor = (w) => {
    const PATHS = {
        app: path.join(w.projectCacheDir, 'app'),
    };
    return wallabyWebpack({
        resolve: {
            root: PATHS.app,
        },
        externals: {
            // Use external versions
            "react": "React",
            "lodash": "lodash",
        },
        plugins: [
            new webpack.NormalModuleReplacementPlugin(/\.(gif|png||jpg|less|css|ttf|eot|svg|woff(2)?)$/, 'node-noop'),
            new webpack.ProvidePlugin({
                'R': 'ramda',
            })
        ],
    });
}
module.exports = function(w) {
    return {
        testFramework: 'jasmine@2.4.1',
        "files": [
            { pattern: 'node_modules/babel-polyfill/browser.js', instrument: false },
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
            { pattern: 'node_modules/lodash/lodash.js', instrument: false },
            { pattern: "app/**/*.ts", load: false },
            { pattern: "app/**/*.tsx", load: false },
            { pattern: "app/**/*.spec.ts", ignore: true }
        ],

        "tests": [
            { pattern: "app/**/*.spec.ts", load: false },
            { pattern: 'node_modules/**/*.*', ignore: true }
        ],
        preprocessors: {
            '**/*.js': file => babel.transform(file.content, { sourceMap: true, presets: ['es2015'], plugins:['transform-runtime'] })
        },
        postprocessor: webpackPostprocessor(w),

        bootstrap: function() {
            window.__moduleBundler.loadTests();
        }
    };
};
```
With the help of @ArtemGovorov this is how to fix the problem: just changing the preprocessors section to:
```javascript
      preprocessors: {
            'app/**/*.js': file => babel.transform(file.content, { sourceMap: true, presets: ['es2015'], plugins:['transform-runtime'] })
        }
```
The reason is that is babel transformed also the node modules, so it transformed  it self too. In the old version it was not a problem but with the new version it is.
