### ISSUE TITLE
Wallaby spamming its console with console.error messages

### ISSUE THREAD

**Issue by JohanHeyvaert** [wallabyjs/public#2863]
### Issue description or question

When running the tests Wallaby outputs a massive amount of log messages like this:

console.error: Summary of all failing tests
console.error: F
console.error: A
console.error: I
console.error: L
console.error: 
console.error: .
console.error: .
console.error: /
console.error: .
console.error: .
....
console.error: .
console.error: O
console.error: b
console.error: j
console.error: e
console.error: c
console.error: t
console.error: .
console.error: <
console.error: a
console.error: n
console.error: o
console.error: n
console.error: y
console.error: m
console.error: o
console.error: u
console.error: s
console.error: >
console.error: .
console.error: T
console.error: e
console.error: s
console.error: t
console.error: B
console.error: e
console.error: d
console.error: V
console.error: i
console.error: e
console.error: w
console.error: E
console.error: n
console.error: g
console.error: i
console.error: n
console.error: e
console.error: .
console.error: i
console.error: n
console.error: j
console.error: e
console.error: c
console.error: t
console.error: 
...
(thousands of lines)

For confidentiality reasons I'd rather not publicly share the diagnostics report. If you need it I can email it to you.

**Comment by ArtemGovorov** [comment]
> For confidentiality reasons I'd rather not publicly share the diagnostics report. If you need it I can email it to you.

**Comment by ArtemGovorov** [comment]
> For confidentiality reasons I'd rather not publicly share the diagnostics report. If you need it I can email it to you.

Yes, please send it to hello@wallabyjs.com and we will take it from there.

**Comment by ArtemGovorov** [comment]
Thanks for sending the report to us. The issue has been fixed and the fix is published in [the latest core v1.0.1184](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by JohanHeyvaert** [comment]
Seems solved. Thanks a lot!
