### ISSUE TITLE
WSL/Docker/Node getting "[Error]: Test run failure: not opened"

### ISSUE THREAD

**Issue by cmidgley** [wallabyjs/public#2869]
### Issue description or question

When running Wallaby on Windows Subsystem for Linux (WSL2, on Windows 10), using a dev container (Docker, Ubuntu, with NodeJS), the tests run fine but after a bunch of live editing/runs, Wallaby eventually reports "[Error]: Test run failure: not opened" (usually within 15-30 minutes of use).  

There are some moderate duration async tests async (<500ms typical, but sometimes stalls out into a few seconds) so some may occasionally hit the Wallaby 5 second limit, though the only time I've seen that reported in the UI is on initial container startup (and not common).  

### Wallaby diagnostics report

See here for the [Wallaby Diagnostic](https://gist.github.com/cmidgley/4dcb012272d797b1c4fc3846e172271c) (too large for issues)

**Comment by smcenlly** [comment]
Your diagnostic report doesn't have the same stack trace that you shared on discord yesterday (shown below) but I imagine that you're still getting the same output in your Wallaby console?

```
[Info]​ console.log: Jest: PASS tests/WorkspaceManager.test.ts
​[Info]​ console.log: Jest: PASS tests/SlotManager.test.ts
​[Info]​ console.log: Server listening on port 8002
​[Info]​ console.log: Jest: PASS tests/WorkspaceManager.test.ts
​[Info]​ console.log: Jest: PASS tests/SlotManager.test.ts
​​[Error] Runtime error: process.exit called with 1​​
​​[Error]     at process.emit.sharedData.processEmitHook.installedValue [as emit] (./node_modules/@cspotcode/source-map-support/source-map-support.js:618:17)​​
​​[Error]     at process._fatalException (node:internal/process/execution:170:25)​​
​​[Error]     at processPromiseRejections (node:internal/process/promises:246:11)​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:97:32)​​
​[Info]​ console.log: Jest: PASS tests/WorkspaceManager.test.ts
​[Info]​ console.log: Jest: PASS tests/SlotManager.test.ts
​​[Error] Runtime error: process.exit called with 1​​
​​[Error]     at process.emit.sharedData.processEmitHook.installedValue [as emit] (./node_modules/@cspotcode/source-map-support/source-map-support.js:618:17)​​
​​[Error]     at process._fatalException (node:internal/process/execution:170:25)​​
​​[Error]     at processPromiseRejections (node:internal/process/promises:246:11)​​
​​[Error]     at processTicksAndRejections (node:internal/process/task_queues:97:32)​​
```

Is your `jest` configuration a TypeScript file? If so, could you please try to change the file type to JavaScript and see if the problem goes away?

Looking at your dependencies and the stack trace, it seems that the only way to get the error is from `ts-node` and I **_think_** the only way this would happen is if your jest configuration is a TypeScript file. We'll keep investigating while you get back to us.

**Comment by smcenlly** [comment]
Could you also please share your jest configuration?

**Comment by smcenlly** [comment]
One final question, when you get the error, what does it look like to you? We can see some errors in the Wallaby log file but it appears that Wallaby recovers from this and continues to work. Are you getting problems / errors / failures or are you only seeing the error details in the Wallaby Console?

It is expected that from time to time, the worker processes that Wallaby runs your tests may fail in unexpected ways (e.g. your code/test runner doing something that causes a crash), and Wallaby is designed to recover from such failures. If this is the case for you, then I think you can safely ignore the errors when they occur in the Wallaby Console.

**Comment by cmidgley** [comment]
The Jest config is currently TypeScript (`jest.config.ts`).  The `ts-node` is currently barely in use, though I have been planning on moving everything to it.  What is recommended?  Switch jest to a `jest.config.js` file?  Should I skip switching to `ts-node` (it's not critical)?

The error is the same as reported earlier on Discord: `[Error]: Test run failure` and I see in the task bar (lower right) just "X" instead of the running test indicator / summary of success/failed tests.  I seem to recall once it did restart after this failure, though it's not quick (>10 minutes) if it does.   

One change I did make is to test for Wallaby in one of my long running async test suites, and mock out some forking (`exec`) that I do (it's executing TypeScript and a firmware compiler from a web service).  This way the test is a true unit test (and fast) when in Wallaby, and more of an integration test when operated outside (I'll be changing this later, but it was a quick way to eliminate those delays).  I've had no further failures with that enabled (though my usage time has been limited as I'm working on CI/CD configuration).  The test I did for you had that disabled as I knew that would quickly recreate the failure.  Not sure if that provides any hints, though it did make me wonder if I had some failures with managing async calls / promises (not handling an exception or something) that perhaps is the source of this issue?

Let me know what thoughts / recommendations you have for me to try and/or what testing I should focus on (such as looking for restart after failure, changing `jest.config.ts`, eliminating `ts-node`, etc) and I'll do that and get back to you.

### Supporting Information

Here is the current `jest.config.ts`.  Note that I also use the NPM module `tsconfig-paths` and map `@xxx` paths to my modules, so here in the config I include those mappings:

#### `jest.config.ts`
```ts
import type { Config } from "@jest/types";

const config: Config.InitialOptions = {
	preset: "ts-jest",
	testEnvironment: "node",
	moduleNameMapper: {
		"^@compiler/(.*)$": [
			"<rootDir>/src/noddable/$1",
			"<rootDir>/src/ModBuilder/$1",
			"<rootDir>/src/SlotManager/$1",
			"<rootDir>/src/WebApp/$1",
			"<rootDir>/src/WorkspaceManager/$1",
		],
	},
};

const globals = {
	"ts-jest": {
		tsconfig: {
			rootDir: ".",
		},
	},
};

export { config as default, globals };
```

Here are the `tsconfig.json` files as well, in case that's interesting.  I use two files as I have some cross-platform dependencies, so the first file (`tsconfig-node.json`) is the one used when using Wallaby, and it includes the second one.

#### `tsconfig.json`
```ts
{
	"extends": "./tsconfig.json",
	"exclude": ["src/**/*.test.ts", "src/esp32/**/*", "src/typings/esp32/**/*"]
}
```

#### `tsconfig-node.json`
```ts
{
	"include": ["src/**/*.ts"],
	"exclude": [],
	"compilerOptions": {
		"target": "es2015",
		"module": "commonjs",
		"rootDir": ".",
		"paths": {
			"@compiler/*": [
				"./src/ModBuilder/*",
				"./src/SlotManager/*",
				"./src/WebApp/*",
				"./src/WorkspaceManager/*"
			]
		},
		"sourceMap": true,
		"outDir": "./dist",
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"strict": true,
		"skipLibCheck": true
	},
	"ts-node": {
		"transpileOnly": true,
		"files": true,
		"compilerOptions": {
			"rootDir": "."
		}
	}
}
```

**Comment by smcenlly** [comment]
From what we can tell, this is what's happening:

1. Because you are using a TypeScript file for your jest configuration, jest is using `ts-node` to run your jest configuration.
2. When `ts-node` runs, it automatically loads `@cspotcode/source-map-support` to generate correct stack traces.
3. `@cspotcode/source-map-support` hooks into `process.emit` and looks for `uncaughtException` and then [exits the process](https://github.com/cspotcode/node-source-map-support/blob/817f84b2820e7395a274379cf80e79930e15d3b2/source-map-support.js#L618).

> though it did make me wonder if I had some failures with managing async calls / promises (not handling an exception or something) that perhaps is the source of this issue?

This is quite likely. The suggest to try `jest.config.js` as a JavaScript file instead of a TypeScript file was to see if we get some better error reporting (i.e. the source of the issue). The error may persist regardless of using TypeScript.

Wallaby has special logic to prevent unwanted process exiting and to handle uncaught exceptions but it's possible that this is being interfered with by `@cspotcode/source-map-support` or may be problematic regardless.

---

In terms of next steps, let's start by changing your jest configuration from TypeScript to JavaScript. Hopefully at that point you have better error without `@cspotcode/source-map-support` overrides in place.

**Comment by cmidgley** [comment]
Sorry for delay, but I didn't want to bother you again until I had more research done.  I have been able to reproduce a similar failure outside of Wallaby.  Something is leaking in my docker/linux setup and consuming all memory, and then all swap (even though all my processes are terminated).  Thanks for the help.  I'll reopen this issue if I still have problems after (hopefully) figuring out my OS memory / swap issue.
