### ISSUE TITLE
Split panes for showing wallaby console next to failing tests

### ISSUE THREAD

**Issue by chrisns** [wallabyjs/public#287]
Hey,
This may be more of an intellij support query, so forgive me if you can't control it.
Would it be possible to split the wallaby window in intellij so that I can see the 'Failing Tests' and 'Wallaby Console' at the same time?
Thanks

**Comment by ArtemGovorov** [comment]
Hey, 
If I'm not mistaken it should be possible to implement, I'll have a look.

**Comment by chrisns** [comment]
Great news, ideally, if it could look like the below it'd be amazing.
<img width="1255" alt="screen shot 2015-10-08 at 08 39 02" src="https://cloud.githubusercontent.com/assets/715120/10360414/6b8c8b3a-6d98-11e5-90ae-3718593b8771.png">

At the minute I'm getting by running wallaby in the background and mocha in the foreground.

(Performance stats are always helpful to know how long tests are taking too, though that should probably be a separate issue)

**Comment by ArtemGovorov** [comment]
BTW, performance stats are planned as a part on the test explorer feature #144

**Comment by chrisns** [comment]
FTW!
