### ISSUE TITLE
Wallaby won't start. moving to Angular13 with wallaby intellij 1.0.225

### ISSUE THREAD

**Issue by Beauceron** [wallabyjs/public#2870]
I run in automatic configs and i have this error in the console:

```
wallaby.js started
core v1.0.1176
Failed to load configuration file: Automatic Angular CLI configuration error: Package subpath './src/ngtsc/file_system' is not defined by "exports" in .\node_modules\@angular\compiler-cli\package.json

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Jest configuration error: Module jest-cli is not found in '.' .
```

I have this installed : 
Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.0
Angular: 13.0.2
**wallaby intellij 1.0.225**

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@angular/cdk                    12.2.11
@angular/cli                    13.0.3
@schematics/angular             12.2.11
rxjs                            6.6.7
typescript                      4.4.4
webpack                         5.38.1

**Comment by smcenlly** [comment]
The latest version of Angular v13 introduced a breaking change that was fixed in Wallaby core v1.0.1183+. Please update to the latest version of Wallaby, it should fix your problem. 

In JetBrains editors you can restart all instances of your editor and then start Wallaby to force the core to update.
