### ISSUE TITLE
Webstorm : Required plugin wallaby.js is disabled

### ISSUE THREAD

**Issue by martinsson** [wallabyjs/public#2871]
### Issue description or question

The plugin is seen as disabled when starting wallaby

<img width="1083" alt="wallabyjs disabled" src="https://user-images.githubusercontent.com/182208/145288401-67d29592-c000-4654-be8e-82069ab05fe6.png">

It works fine in intellij though

### Wallaby diagnostics report
[idea.log](https://github.com/wallabyjs/public/files/7679070/idea.log)

{
  "appInfo" : {
    "build" : "213.5744.224",
    "buildDate" : "2021-11-27T10:34:47.013Z[UTC]",
    "productCode" : "WS",
    "generated" : "2021-12-08T21:32:00.399922Z",
    "os" : "macOS 11.6",
    "runtime" : "JetBrains s.r.o. 11.0.13 11.0.13+7-b1751.19"
  },
  "runtimeInfo" : {
    "maxMemory" : 2147483648,
    "numberOfProcessors" : 12,
    "maxNumberOfIndexingThreads" : 4,
    "maxSizeOfFileForIntelliSense" : 2560000,
    "maxSizeOfFileForContentLoading" : 20971520
  },
  "projectIndexingHistory" : {
    "projectName" : "ui",
    "times" : {
      "indexingReason" : "On project open",
      "totalUpdatingTime" : 3741373027,
      "indexingTime" : 0,
      "contentLoadingTime" : 0,
      "scanFilesTime" : 3695513000,
      "pushPropertiesTime" : 60000,
      "indexExtensionsTime" : 0,
      "updatingStart" : "2021-12-08T21:31:56.656344Z",
      "updatingEnd" : "2021-12-08T21:32:00.397737Z",
      "totalSuspendedTime" : 0,
      "wasInterrupted" : false
    },
    "fileCount" : {
      "numberOfFileProviders" : 17,
      "numberOfScannedFiles" : 12903,
      "numberOfFilesIndexedByInfrastructureExtensionsDuringScan" : 0,
      "numberOfFilesScheduledForIndexingAfterScan" : 0,
      "numberOfFilesIndexedByInfrastructureExtensionsDuringIndexingStage" : 0,
      "numberOfFilesIndexedWithLoadingContent" : 0
    },
    "totalStatsPerFileType" : [ ],
    "totalStatsPerIndexer" : [ ],
    "scanningStatistics" : [ {
      "providerName" : "com.intellij.openapi.roots.ImmutableSyntheticLibrary@27a23691",
      "numberOfScannedFiles" : 11571,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 2378489743,
      "timeProcessingUpToDateFiles" : 212807993,
      "timeUpdatingContentLessIndexes" : 17012014,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Module 'ui' (ui)",
      "numberOfScannedFiles" : 938,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 554703809,
      "timeProcessingUpToDateFiles" : 38437565,
      "timeUpdatingContentLessIndexes" : 2926454,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.javaee.ExternalResourcesRootsProvider@3dc27dd8' (non-project)",
      "numberOfScannedFiles" : 217,
      "numberOfSkippedFiles" : 4,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 208503903,
      "timeProcessingUpToDateFiles" : 21619179,
      "timeUpdatingContentLessIndexes" : 1224663,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'TypeScript bundled libraries' (project)",
      "numberOfScannedFiles" : 35,
      "numberOfSkippedFiles" : 26,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 128094063,
      "timeProcessingUpToDateFiles" : 59532701,
      "timeUpdatingContentLessIndexes" : 398800,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'JS required libraries' (project)",
      "numberOfScannedFiles" : 36,
      "numberOfSkippedFiles" : 34,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 124710507,
      "timeProcessingUpToDateFiles" : 62569911,
      "timeUpdatingContentLessIndexes" : 441555,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "com.intellij.openapi.roots.ImmutableSyntheticLibrary@78962e73",
      "numberOfScannedFiles" : 54,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 110680062,
      "timeProcessingUpToDateFiles" : 24101842,
      "timeUpdatingContentLessIndexes" : 446632,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'Scratches & Consoles' (non-project)",
      "numberOfScannedFiles" : 26,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 109936403,
      "timeProcessingUpToDateFiles" : 13144393,
      "timeUpdatingContentLessIndexes" : 275792,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'org.jetbrains.plugins.scss.index.SassScssIndexedRootProvider@139c32dc' (non-project)",
      "numberOfScannedFiles" : 8,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 71725407,
      "timeProcessingUpToDateFiles" : 4881940,
      "timeUpdatingContentLessIndexes" : 104969,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'JS required libraries' (non-project)",
      "numberOfScannedFiles" : 9,
      "numberOfSkippedFiles" : 4,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 67736557,
      "timeProcessingUpToDateFiles" : 32953249,
      "timeUpdatingContentLessIndexes" : 115432,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.httpClient.http.request.HttpRequestCollectionProvider@20f5024e' (non-project)",
      "numberOfScannedFiles" : 8,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 47976660,
      "timeProcessingUpToDateFiles" : 993674,
      "timeUpdatingContentLessIndexes" : 64759,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.httpClient.http.request.run.HttpClientDynamicVariablesStubController@290f47e7' (non-project)",
      "numberOfScannedFiles" : 1,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 19951879,
      "timeProcessingUpToDateFiles" : 203935,
      "timeUpdatingContentLessIndexes" : 16806,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'org.jetbrains.plugins.scss.index.SassScssIndexedRootProvider@139c32dc' (project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.httpClient.http.request.run.HttpClientDynamicVariablesStubController@290f47e7' (project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.httpClient.http.request.HttpRequestCollectionProvider@20f5024e' (project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'Scratches & Consoles' (project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'com.intellij.javaee.ExternalResourcesRootsProvider@3dc27dd8' (project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    }, {
      "providerName" : "Indexable set contributor 'TypeScript bundled libraries' (non-project)",
      "numberOfScannedFiles" : 0,
      "numberOfSkippedFiles" : 0,
      "numberOfFilesForIndexing" : 0,
      "numberOfFilesFullyIndexedByInfrastructureExtensions" : 0,
      "scanningTime" : 0,
      "timeProcessingUpToDateFiles" : 0,
      "timeUpdatingContentLessIndexes" : 0,
      "timeIndexingWithoutContent" : 0
    } ],
    "fileProviderStatistics" : [ ]
  }
}

I attach files showing what the ui looks like

**Comment by smcenlly** [comment]
Back in April, we had inadvertently made a change to Wallaby for IntelliJ that had broken some older run configuration settings. 

In order to fix your issue, you will need to recreate your Wallaby Run configuration (delete the old configuration and create it again). Alternatively, you may repair your old run configuration by editing the associated settings `xml` file and changing the `factoryName` property from `Wallaby.js` to `wallaby`.

**Comment by martinsson** [comment]
I confirm this worked. Thanks
