### ISSUE TITLE
Cannot verify OSS project.

### ISSUE THREAD

**Issue by Rawnly** [wallabyjs/public#2872]
### Issue description or question
Cannot verify OSS project.

`Wallaby.js has been stopped because the open source status of your project could not be verified. Please note: an internet connection is required for validation`

### Wallaby diagnostics report
Can't get a diagnostic report. But opening dev-tools reveals an error.

`this._session.requestTestRunSummary is not a function`

**Comment by ArtemGovorov** [comment]
Can you please send us an email from the email address that you have used for your OSS license activation to hello@wallabyjs.com and we'll sort it out for you.
