### ISSUE TITLE
Cannot start Wallaby on WSL 2 with NVM

### ISSUE THREAD

**Issue by mmeier** [wallabyjs/public#2876]
I have a project in WSL 2 that I can run from Webstorm manually. Added the Wallaby Plugin and it errors that it cannot find node.

The event log from Webstorm:
```
2:39 AM	Wallaby Notification: Can not start node.js process (node), make sure your system has node.js installed.

2:41 AM	Wallaby Notification: Can not start node.js process (//wsl$/Ubuntu/home/marcus/.nvm/versions/node/v16.13.0/bin/node), make sure your system has node.js installed.

2:41 AM	Wallaby Notification: Can not start node.js process (node), make sure your system has node.js installed.

2:46 AM	Wallaby Notification: Can not start node.js process (//wsl$/Ubuntu/home/marcus/.nvm/versions/node/v14.17.6/bin/node), make sure your system has node.js installed.
```

The `Can not start node.js process (node)` happens when I have the run configuration set to `{SYSTEM DEFAULT}`
The other errors are when I pointed Wallaby directly to node versions installed by NVM.

WSL Info
```
> wsl --list -v
  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Running         2
```

NVM Info
```
╰─ nvm list                                                                                                          ─╯
       v14.17.6
->     v16.13.0
default -> node (-> v16.13.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v16.13.0) (default)
stable -> 16.13 (-> v16.13.0) (default)
```

I suspect however Wallaby is launching it doesn't have node in the PATH, but I'm not sure which terminal it's using, so I don't know if I have to update one of my profile files within WSL. Is there someplace I can drop a `nvm use node` script?

**Comment by smcenlly** [comment]
Please explicitly set the path to node in the Node.js setting of your Wallaby Run Configuration. When using WSL, the path should reflect the path on your WSL environment, not your Windows environment. 

You should be able to determine the path using `node which` in your WSL instance.
