### ISSUE TITLE
Trying to set up wallaby with babel

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#288]
I cannot figure out how to make wallaby work with [this project](https://github.com/epsitec-sa/electrum).

Here is my `wallaby.conf.js` file:

```js
'use strict';

var babel = require ('babel');

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'modules/*.js', load: false}
    ],
    tests: [
      {pattern: 'test/*.js', load: false}
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel ({
        babel: babel,
        // other babel options
        stage: 0    // https://babeljs.io/docs/usage/experimental/
      })
    },
    debug: true
  };
};
```

If I don't set `{pattern: ... load: false}` then I get errors such as `ReferenceError: Can't find variable: require`, which makes sense.

If, on the other hand, I set `load: false`, then there isn't any error and wallaby seems to be happy, but all lines get a gray badge (i.e. `Line is not covered or covered not by tests`).

Running a simple `npm test` from the command line works, though.

**Comment by ArtemGovorov** [comment]
It looks like a node.js project, not a browser app, so you need to [set env property](http://wallabyjs.com/docs/intro/troubleshooting.html#39-can-39-t-find-variable-require-39-or-39-can-39-t-find-variable-module-39) to use node, otherwise it's using phantomjs by default and `require` is not defined in browser, hence the error.

Here is the config that should work for you:

``` JavaScript
'use strict';

var babel = require ('babel');

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'modules/**/*.js'},
      {pattern: 'index.js'}
    ],
    tests: [
      {pattern: 'test/*.js'}
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel ({
        babel: babel,
        // other babel options
        stage: 0    // https://babeljs.io/docs/usage/experimental/
      })
    },
    debug: true,
    env: {
      type: 'node'
    }
  };
};
```

**Comment by epsitec** [comment]
Thank you very much. It works, indeed.

**Comment by ArtemGovorov** [comment]
Awesome! Thanks for the update. Please let me know if you hit any other issues with wallaby, happy to help.
