### ISSUE TITLE
Auto-detect WSL use

### ISSUE THREAD

**Issue by mmeier** [wallabyjs/public#2882]
# Feature Request

Auto-detect WSL use.

# Explanation

I ran into configuration trouble which was solved here: https://github.com/wallabyjs/public/issues/2876

I've been using JetBrains IDE's with WSL for a while, and the integration has been pretty seamless. I found the "Use WSL" odd. But I located the node binary file with the provided browse button, and it filled the textbox with the standard `\\wsl$\<Version>` prefix. 

The rest of JetBrains appears to use this prefix to determine if it is running against WSL or not. The fact that I have to check a "Use WSL" option, and also modify the path pre-filled by the browse button in the UI is unintuitive and I found it frustrating. Once the issue was pointed out it was clear in hindsight, but it's inconsistent with how the rest of the IDE seems to integrate with WSL.

In the example pointed out in the linked issue I would expect a node path of `//wsl$/Ubuntu/home/marcus/.nvm/versions/node/v16.13.0/bin/node` to be equivalent to `/home/marcus/.nvm/versions/node/v16.13.0/bin/node` with WSL set to `yes`.

**Comment by smcenlly** [comment]
Wallaby for IntelliJ `v1.0.241`+ now automatically sets WSL to true if the node path contains `wsl$`.

**Comment by VildanJS** [comment]
Hi,
WSL auto seted on, but WebStorm does't find Node by path that includs //wsl$/Ubuntu
Works only /home/{profile}/.nvm/versions/node/v16.13.0/bin/node

**Comment by smcenlly** [comment]
Sorry - we had misunderstood your original request. Wallaby will now change:

```
//wsl$/Ubuntu/home/marcus/.nvm/versions/node/v16.13.0/bin/node
```

to 

```
/home/marcus/.nvm/versions/node/v16.13.0/bin/node
```

when it runs your code.
