### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by Rofer11607** [wallabyjs/public#2883]
Will there ever be neovim support? There is another thread that seems to have no response from the team. 

Neovim now has the virtual text to support this and quokka.

Im just wondering as I have gone to vim full time and am wondering if I should keep the membership

**Comment by smcenlly** [comment]
We don't have any immediate plans to add editor support for Neovim. You can [follow this issue](https://github.com/wallabyjs/public/issues/14) to be notified of any updates.

**Comment by ArtemGovorov** [comment]
Wallaby 2 is live 🚀 https://wallabyjs.com/blog/wallaby-2.html, and it can now be used with [any editors, including Neovim](https://wallabyjs.com/docs/intro/standalone/).
