### ISSUE TITLE
Error when running WallabyJS on Angular 12 project with Jest & auto config

### ISSUE THREAD

**Issue by pbrianmackey** [wallabyjs/public#2885]
This project was upgraded recently from Angular 8 to 12.  I also just migrated from Karma/Jasmine to Jest.  This is a fairly large project with about 1,000 tests.

Jest v27.4.5
‍​[Info]​ Started Wallaby.js Core v1.0.1196  (Just ran the update wallaby.js Force Core Update cmd in VS Code.)
Ran:  Wallaby.js: Reset Wallaby Cache

```
​​[Error] Runtime error: ReferenceError: window is not defined​​
​​[Error]     at WebSocket.emit (events.js:400:28)​​
​​[Error]     at afterWrite (internal/streams/writable.js:466:5)​​
​​[Error]     at onwrite (internal/streams/writable.js:446:7)​​
​​[Error]     at InflateRaw.afterTransform (internal/streams/transform.js:103:3)​​
​​[Error]     at Zlib.processCallback (zlib.js:607:8)​​
```

jest.config.js

```
require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  watchPathIgnorePatterns: ['<rootDir>/src/environments/environment.test.ts'],
  testPathIgnorePatterns: ['<rootDir>/src/environments/environment.test.ts'],
};
```

Already ran `.\node_modules\.bin\jest --clearCache`

`.\node_modules\.bin\jest` AND `npx jest` both run to completion with passing tests.

**Comment by pbrianmackey** [comment]
I noticed something very strange.  When I have my angular.json file in it's original form:

```
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": ["src/favicon.ico", "src/assets", "src/web.config"],
            "styles": ["src/sass/styles.scss"],
            "scripts": [],
            "codeCoverageExclude": [
            ]
          }
        },
```

Then I see this error:  `​​[Error] Runtime error: ReferenceError: window is not defined​​`

I am NOT using Karma anymore.  So if I delete the test section from angular.json:

```
‍​[Info]​ Started Wallaby.js Core v1.0.1199
​[Info]​ ngcc-jest-processor: running ngcc
​​[Error] Runtime error: Another process, with id 8904, is currently running ngcc.​​
```

Why would this happen?

**Comment by pbrianmackey** [comment]
If I delete change the angular.json test section as follows:

```
        "test": {
          "builder": "@angular-builders/jest:run"
        },
```

Then I get a completely different error.  

```
‍​[Info]​ Started Wallaby.js Core v1.0.1199
​[Info]​ ngcc-jest-processor: running ngcc
​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] Runtime error: Another process, with id 15816, is currently running ngcc.​​
​​[Error] Waiting up to 250s for it to finish.​​
​​[Error] (If you are sure no ngcc process is running then you should delete the lock-file at C:/Git/DW/UI/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)​​
```

```
        "test": {
          "builder": "@angular-builders/jest:run"
        },
```

If I change angular.json back to it's original setting it goes back to the original error again.

```
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": ["src/favicon.ico", "src/assets", "src/web.config"],
            "styles": ["src/sass/styles.scss"],
            "scripts": [],
            "codeCoverageExclude": [
              "my/path"
            ]
          }
        },
```

I'm not using Karma anymore, so I don't need this setting like this.  Why would changing angular.json do this to Wallaby?

**Comment by pbrianmackey** [comment]
Despite the many ngcc errors, the tests did complete after about 10 minutes.  Which is significantly slower than Jest at the command line.  Why am I getting lots of ngcc errors?  This happens like 30 times before the tests start executing when I Wallaby: Start:

```
‍​[Info]​ Started Wallaby.js Core v1.0.1199
​[Info]​ ngcc-jest-processor: running ngcc
​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] Runtime error: Another process, with id 12956, is currently running ngcc.​​
​​[Error] Waiting up to 250s for it to finish.​​
​​[Error] (If you are sure no ngcc process is running then you should delete the lock-file at C:/Git/DW/UI/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)​​
​​[Error] Runtime error: Another process, with id 12956, is currently running ngcc.​​
​​[Error] Waiting up to 250s for it to finish.​​
​​[Error] (If you are sure no ngcc process is running then you should delete the lock-file at C:/Git/DW/UI/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)​​
​​[Error] Runtime error: Another process, with id 12956, is currently running ngcc.​​
​​[Error] Waiting up to 250s for it to finish.​​
```

**Comment by pbrianmackey** [comment]
The errors went away when I used the following config:

```
  "wallaby": {
    "autoDetect": false,
    "trace": false,
    "debug": true,
    "configFile": "./jest.config.js",
    "slowTestThreshold": 200,
    "testFramework": "jest",
    "env": {
      "type": "node"
    },
    "workers": {
       "initial": 1,
       "regular": 1
     }
  }
```

I think it's setting the workers that did the trick.

**Comment by smcenlly** [comment]
> Why would changing angular.json do this to Wallaby?

Wallaby detects that you are using Angular and loads your test configuration from your `angular.json` file. As per angular-builders/jest docs, you should change your `angular.json` for when you run from the CLI (https://www.npmjs.com/package/@angular-builders/jest). Your CLI configuration is what Wallaby uses to determine how to run your tests.

---

From the Angular docs

> To make sure that Jest uses the Angular Ivy, you must run ngcc before running tests. ngcc will transform all Angular-format packages to be compatible with Ivy compiler.
> 
> jest-preset-angular also provides util script to help you to run ngcc with Jest but this script only works via the JavaScript version of Jest config
> 
> // jest.config.js
> require('jest-preset-angular/ngcc-jest-processor');

From their description of what it does (transforming all Angular format packages to be compatible with Ivy compiler), it seems that this is a one time operation.

Wallaby is also running your project's tests in parallel and I was able to find some previous issues ([example](https://github.com/angular/angular/issues/35000)) about ngcc not working when run in parallel.

After Wallaby starts, can you remove the ` require('jest-preset-angular/ngcc-jest-processor');` statement and the workers section override? If so, does it work for you? If this is working for you, we should be able to help you create a Wallaby/Jest configuration that does this just once on Wallaby startup.

**Comment by pbrianmackey** [comment]
I removed `require('jest-preset-angular/ngcc-jest-processor');` from jest.config.js.

Then I removed all 3 settings from the workers in package.json:

```
    "workers": {
     }
```

Jest stops running:

```
​​[Error] Runtime error: Failed to initialize wallaby jest.​​
​​[Error] Module jest-cli is not found in '.'.​​
​​[Error] Error: Module jest-cli is not found in '.'.​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at new Promise (<anonymous>)​​
​​[Error]     at WebSocket.emit (events.js:400:28)​​
​​[Error]     at afterWrite (internal/streams/writable.js:466:5)​​
​​[Error]     at onwrite (internal/streams/writable.js:446:7)​​
​​[Error]     at InflateRaw.afterTransform (internal/streams/transform.js:103:3)​​
​​[Error]     at Zlib.processCallback (zlib.js:607:8)
```

**Comment by smcenlly** [comment]
Can you please share your Wallaby diagnostics report? From our issue template:

Wallaby Diagnostics Report is a simple JSON text report that contains some basic information
about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

start Wallaby in your project;
wait until it reports some results (finishes running tests);
run Copy Diagnostics Report command:
in VS Code, Atom, or Sublime editor execute Wallaby Copy Diagnostics Report command from your editor command palette;
in JetBrains IDEs or VS use Wallaby Help | Wallaby.js | Copy Diagnostics Report menu item;
paste generated report from your clipboard below (feel free to review and edit the report if required).
--

If the diagnostics report is not generating, can you please share your Wallaby Console output as well as your package.json?

**Comment by pbrianmackey** [comment]
Oddly enough I tried the same thing again this morning and Wallaby did NOT break.  I can't explain what happened last night, but looks like it's working now.

**Comment by smcenlly** [comment]
Can you stop/restart a few times to make sure that you don't have a problem?

---

In terms of the configuration, it's probably best to explain a little about how Wallaby uses your configuration file so what we're doing makes sense to you:

Wallaby uses multiple processes to run your tests. It has a main process which is alive for the entire time that Wallaby is running and then spawns "worker" processes to run your tests. The worker processes are intentionally separate and speed up test execution as well as ensure that Wallaby recovers gracefully if a worker process gets into a bad state.

When Wallaby loads your configuration file, it first loads it in its main process before loading in each of the worker processes as/when required.

What we need to do is configure Wallaby to only run `require('jest-preset-angular/ngcc-jest-processor');` once (in the main process).

The configuration below should work for you (assuming that `require('jest-preset-angular/ngcc-jest-processor');` is synchronous). Please note that you will need to have a configuration file and not use `package.json`:

**wallaby.js**
```javascript
if (!process.env.WALLABY_NGCC_INITIALIZED) {
    require('jest-preset-angular/ngcc-jest-processor');

    // All worker processes will now have environment 
    // variable set and will not run the code again.
    process.env.WALLABY_NGCC_INITIALIZED = true;
}

module.exports = () => ({
  autoDetect: true,
});

```

You will also need to update your `jest.config.js`:

**jest.config.js**
```javascript
if (!process.env.WALLABY_ENV) {
  require('jest-preset-angular/ngcc-jest-processor');
}
```

---

If you run into problems or get stuck, please let us know.

**Comment by pbrianmackey** [comment]
The ngcc error comes back when I run "Wallaby Reset Cache" and try the steps that you originally gave me again.  But that file you gave me fixes it.  Question though.  Is it normal for Wallaby to take like 10-15 minutes to start the first run?  Once it starts all the tests report running in like 1ms - 300ms max between 100s of tests.  But on startup I get errors saying tests are taking 30s?  ONLY on startup does this error showup in the Wallaby.js console.
```
​​[Error] Some long running code has been detected: one of your files is taking more than 5000ms to execute.​​
​​[Error] Execution of the following files has started but has not finished:​​
```
There are lots of these on start.
