### ISSUE TITLE
Wallaby with vite-jest

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#2889]
Was going to add this to #2778 but that issue is asking about a specific project.

My project is vue + typescript, using vite to build and jest for testing. I have add to add a bunch of babel dependencies to get jest working, which is a shame becuase vite doesn't need them, but vite and jest don't get on.

I've been keeping an eye on [vite-jest](https://github.com/sodatea/vite-jest) to solve this problem, and I've now got it working on the command line, but not with Wallaby.

The Wallaby docs suggest to make sure running `jest` in the project works, which in this case it does *not*. You have to run `vite-jest`.

The errors reported by Wallaby are the same you get when running `jest`. e.g. "Cannot use import statement outside a module"

**Comment by ArtemGovorov** [comment]
> The Wallaby docs suggest to make sure running jest in the project works, which in this case it does not. You have to run vite-jest.

`vite-jest` command [doesn't seem to do much](https://github.com/sodatea/vite-jest/blob/main/packages/vite-jest/bin/vite-jest.js) except for passing node's `--experimental-vm-modules` argument required by Jest to support native ES modules. 

So after you pass the required flag, then should hopefully work for you (both with [plain `jest` command with the flag](https://jestjs.io/docs/ecmascript-modules) and Wallaby [with config for Jest ESM](https://wallabyjs.com/docs/integration/esm.html#jest)).

**Comment by tslocke** [comment]
Thanks - this worked, sort of.

I was able to get both command-line jest and Wallaby working, but jest was spitting out tons of warnings and Wallaby didn't seem very happy - responses to my edits were sometimes extremely slow and sometimes not happening at all.

I'm going to assume this is all a bit too close to the bleeding edge and stick with babel for now.

Thanks or the advice anyway - I'll probably revisit this in a few months.
