### ISSUE TITLE
Real bad performance when using Atom in Linux Ubuntu

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#289]
This is with a minimal node test, which runs at normal 'wallaby speed' on other OS (windows and OSx)

The same code runs ok in a VirtualBox Windows running on the same Ubuntu host

Any ideas why?

**Comment by ArtemGovorov** [comment]
Maybe something instance specific, just tried on Ubuntu 15.04, works pretty good:
![u](https://cloud.githubusercontent.com/assets/979966/10393330/667d75c4-6ed2-11e5-9755-63a259b83754.gif)
Also know it's been working good for quiet a few users on Ubuntu.

Try opening Developer Tools in Atom (`Ctrl + Shift + I`), add [`debug: true`](http://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) to wallaby config and have a look what's exactly taking long time.

**Comment by ArtemGovorov** [comment]
Let me know if have a chance to run with `debug: true` and paste the output, happy to re-open the issue.
