### ISSUE TITLE
Option to toggle the path in the Output Inspector

### ISSUE THREAD

**Issue by neldeles** [wallabyjs/public#2894]
### Issue description or question

Option to toggle the path in the Output Inspector. Ideally I'd like the filename only to be displayed by default with a toggle to display the whole path when needed. Or even some better styling ala how Jest does it:
![CleanShot-2021-12-30-at-14 01 18](https://user-images.githubusercontent.com/14298160/147725906-16e583f2-8966-4faf-8f56-af643f0b14b6.png)

It can be difficult to identify the included test files when starting a exclusive test run.

Here's a screenshot for your reference:

![CleanShot-2021-12-29-at-13 08 43@2x](https://user-images.githubusercontent.com/14298160/147725527-216b955b-68c0-4e76-bd78-ebad2128ff60.png)

Artem has recommended using the Wallaby App for now and this is what I'm currently doing. I'd like to reduce context switching though, so implementing this option would be a nice-to-have.

Thanks for the amazing product and support guys. :)

**Comment by smcenlly** [comment]
We have made some improvements to how exclusive test files are output in the Wallaby Output window.

1. Where possible, we now shorten the path to only the filename (provided there are no duplicates).
2. If the total length of the path is more than 120 characters, then we only output the number of test locations, we do not explicitly list them.

This behavior is not controlled by a setting.

Wallaby core `v1.0.1287` and later include this change.
