### ISSUE TITLE
Open source status check fail

### ISSUE THREAD

**Issue by lixcode-rep** [wallabyjs/public#2896]
### Issue description or question

The WebStorm plugin cannot check the open souce status of project.
Project: https://gitlab.com/vasille-js/vasille-js

### Wallaby diagnostics report

The command "Copy Diagnostics Report" does nothing, obsolutelly nothing.

Notification log:
12:28	Wallaby Notification: Wallaby.js will be started after the open-source status of your project has been validated.

12:28	Wallaby Notification: Wallaby.js has been stopped because the open source status of your project could not be verified.

**Comment by ArtemGovorov** [comment]
Your project is hosted on Gitlab and Wallaby OSS program [only supports projects hosted on Github](https://wallabyjs.com/oss/).
