### ISSUE TITLE
Debugger Question/Assistance

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2904]
currently 2022... Has this been looked at yet? Doesn't seem to be working for me?

_Originally posted by @FacePalmDev in https://github.com/wallabyjs/public/issues/74#issuecomment-1012075531_

**Comment by smcenlly** [comment]
@FacePalmDev - can you please describe what's not working for you with the debugger so we understand what's going on?

**Comment by FacePalmDev** [comment]
Hey sorry I've had to switch tasks for the moment but I'll take a look at this again next week.
