### ISSUE TITLE
Error output about ES6 Modules `import` statement

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#291]
Hello, I just bought Wallaby for the IntelliJ IDEA platform and I'm having some issues trying to make it work with my tests.

I'm gonna show you my setup and at the end of the report you can find the Wallaby current output.

**My Setup:**

    Webstorm 11 EAP Build WS-143.88
    Wallaby v1.0.38
    NodeJS v4.1.2
    Webpack v1.12.2
    Babel v5.8.23
    Karma v0.13.10
    Mocha v2.3.3
    Chai v3.3.0
    PhantomJS v1.9.18

**My Karma Config File:**

    module.exports = function(config) {
      config.set({
        frameworks: ['mocha'],
        files: [
          './node_modules/phantomjs-polyfill/bind-polyfill.js',
          './node_modules/babel-core/browser-polyfill.js',
          'tests/**/*.spec.js'
        ],
        plugins: ['karma-webpack', 'karma-mocha', 'karma-phantomjs-launcher', 'karma-coverage', 'karma-spec-reporter'],
        browsers: ['PhantomJS'],
        preprocessors: {
          'tests/**/*.spec.js': ['webpack'],
          'src/**/*.js': ['webpack']
        },
        reporters: ['spec', 'coverage'],
        coverageReporter: {
          dir: 'reports/coverage',
          reporters: [
            { type: 'html', subdir: 'report-html' },
            { type: 'lcov', subdir: 'report-lcov' },
            { type: 'cobertura', subdir: '.', file: 'cobertura.txt' }
          ]
        },
        webpack: {
          module: {
            loaders: [
              {
                test: /\.js$/, exclude: /(bower_components|node_modules)/,
                loader: 'babel-loader'
              },
              {
                test: /sinon.*\.js$/,
                loader: 'imports?define=>false'
              }
            ],
            postLoaders: [{
              test: /\.js$/, exclude: /(node_modules|bower_components|tests)/,
              loader: 'istanbul-instrumenter'
            }]
          }
        },
        webpackMiddleware: { noInfo: true }
      });
    };

**My Wallaby Config File:**

    var babel = require('babel');
    var wallabyWebpack = require('wallaby-webpack');
    
    var webpackPostprocessor = wallabyWebpack({
      module: {
        loaders: [
          {
            test: /sinon.*\.js$/,
            loader: "imports?define=>false"
          }
        ]
      }
    });
    
    module.exports = function () {
      return {
        files: [
          { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
          { pattern: 'node_modules/babel-core/browser-polyfill.js', instrument: false },
          { pattern: 'src/**/*.js', load: false }
        ],
    
        tests: [
          { pattern: 'tests/**/*.spec.js', load: false }
        ],
    
        preprocessors: {
          'src/**/*.js': file => babel.transform(file.content, { sourceMap: true })
        },
    
        postprocessor: webpackPostprocessor,
    
        bootstrap: function () {
          window.__moduleBundler.loadTests();
        }
      };
    };

**An Example Spec File:**

    import { expect } from 'chai';
    import * as is from '../../src/helpers/is';
    import { list } from '../fixtures';
    
    describe('is helpers', () => {
      const div = document.createElement('div');
      div.innerHTML = list;
      document.body.appendChild(div);
    
      let fn;
      let node;
      let num;
      let obj;
      let srt;
    
      beforeEach(() => {
        fn = x => x;
        node = document.querySelectorAll('li');
        num = 24.6;
        obj = {};
        srt = 'foo';
      });
    
      it('should return true if is function', () => {
        expect(is.isFunction(fn)).isTrue;
        expect(is.isNode(fn)).isFalse;
        expect(is.isNumber(fn)).isFalse;
        expect(is.isObject(fn)).isFalse;
        expect(is.isString(fn)).isFalse;
      });

    ...
    });

**Failing Tests Output:**

    Error: No source available
        at tests/helpers/is.spec.js:1
    
    Error: No source available
        at tests/modules/to-array.spec.js:1
    
    ModuleParseError: Module parse failed: ./tests/helpers/is.spec.js Line 2: Unexpected token
    You may need an appropriate loader to handle this file type.
    | $_$wp(12);
    | import { expect } from 'chai';
    | import * as is from '../../src/helpers/is';
    | import { list } from '../fixtures';
      at DependenciesBlock.<anonymous> (/Users/dave/Development/personal/dominus/node_modules/webpack/lib/NormalModule.js:113:20)
      at DependenciesBlock.onModuleBuild (/Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
      at nextLoader (/Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
      at /Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
      at /Users/dave/Development/personal/dominus/node_modules/wallaby-webpack/lib/WallabyInputFileSystem.js:30:11
      at process._tickCallback (node.js:340:13)
    
    
    ModuleParseError: Module parse failed: ./tests/modules/to-array.spec.js Line 2: Unexpected token
    You may need an appropriate loader to handle this file type.
    | $_$wp(13);
    | import {
    |     assert,
    |     expect
      at DependenciesBlock.<anonymous> (/Users/dave/Development/personal/dominus/node_modules/webpack/lib/NormalModule.js:113:20)
      at DependenciesBlock.onModuleBuild (/Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
      at nextLoader (/Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
      at /Users/dave/Development/personal/dominus/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
      at /Users/dave/Development/personal/dominus/node_modules/wallaby-webpack/lib/WallabyInputFileSystem.js:30:11
      at process._tickCallback (node.js:340:13)

**Wallaby Console Output:**

    wallaby.js started
    core v1.0.127
    Runtime error: Error: No source available
    Runtime error: Error: No source available

I hope you can help me with this...

**Comment by ArtemGovorov** [comment]
@davegomez  Thanks for your support.

Looks like babel is not processing your specs, the reason is that your preprocessors pattern only includes your source files, not specs. Try changing the pattern like this:

``` JavaScript
preprocessors: {
      '**/*.js': file => babel.transform(file.content, { sourceMap: true })
    },
```

**Comment by ArtemGovorov** [comment]
One other thing I have just noticed (not related to the issue) - you are using mocha in your karma config, however wallaby is using `jasmine` by default. It should work fine for you as well if you are not using any `mocha` specific API calls. However, I'd recommend to set your testing framework to `mocha`, here is  [an example](https://github.com/wallabyjs/wallaby-webpack-es7/blob/master/wallaby.js#L50) how to do it.

**Comment by davegomez** [comment]
It worked, thanks!
