### ISSUE TITLE
Automatic configuraion not working for new nx workspaces with angular

### ISSUE THREAD

**Issue by whernebrink** [wallabyjs/public#2912]
Hi,

At work we are utilizing an nx workspace for our Angular applicaion and libraries. This has worked fine with Wallaby, and the automatic configuration has worked fine too. However, now when trying to migrate to latest Nx workspace, the `angular.json`is just referencing the different projects, so the automatic configuration does not work (since it seems to be expecting the `@angular-devkit/build-angular:karma` in there, which is now moved by nx.

This is the error I get when trying a automatic configuration:
```
‌[Error] Automatic Angular CLI configuration error: None of your projects are configured with `@angular-devkit/build-angular:karma`, `@angular-builders/custom-webpack:karma`, `@angular-builders/jest:run`, or `@nrwl/jest:jest` builders as their test architect. 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```

It seems like it should be a simple fix, since under `projects` in the angular.json, the projects are just pointing to the project's location for all the configuration files, one of which would be the `project.json` which is where the build/test etc previously stored in the angular.json lives.

[Here is a clean repository](https://github.com/whernebrink/wallabyjs-nx-workspace) with one application and one library, both of which uses Karma as the test runner (since that is what we are stuck with).

### Wallaby diagnostics report
I was unable to get one, I assume it was due to the fact the configuration was not successful?

Best regards,

**Comment by smcenlly** [comment]
Thanks for reporting the problem. It looks like there have been some breaking changes to `nx` test configuration that Wallaby will need to support.

Could you please describe the steps to create the clean repository? Did you use the nx CLI tools, or were there custom modifications that you made to the configuration files?

**Comment by smcenlly** [comment]
We were able to reproduce the problem. There's been some breaking changes in the most recent version of NX configuration file format. Previously it was compatible with Angular but that is no longer the case.

We are actively working on fixing this issue but it may take another few days to fix.

**Comment by smcenlly** [comment]
We have added support for the latest version of NX workspaces (including the new workspace configuration file format).

Please update to Wallaby core `v1.0.1213` and everything should work for you.

**Comment by whernebrink** [comment]
@smcenlly Thanks for addressing so fast. Wallaby is now able to find the specs, but I'm also getting the `Cannot read properties of undefined (reading 'match').` which is mentioned in this [2913](https://github.com/wallabyjs/public/issues/2913#issuecomment-1020971502 ) that was created after my issue here.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by whernebrink** [comment]
@NikGovorov @smcenlly Huge thansk for this quick fix, really impressive! I'm so happy my managers listened to my suggesten and approved my request for having Wallaby.js for our project devs. Best descision ever! :) Thanks again!
