### ISSUE TITLE
Feature Request: Add VS Code command to select Automatic Configuration based on current current

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#2914]
From discord:

> I'm using Wallaby w/Rush in a Monorepo.  It's working great.  I have a usability question... I am constantly having to stop/restart Wallaby as I work on different scoped libraries in my monorepo.  Each time I have to select the directory I'm currently working in.  Is there any way to locate the nearest project.json based on the currently active / open file?

I assume that you're using VS Code? We don't have a way to locate the nearest project.json but I think we could add a Automatic Configuration <current project>  option that could use the currently opened editor (and maybe some other heuristics) to find the closest project in a mono repo. Would that give you what you want? If so, I'll create a feature request for you in our github issues (or else you may do the same)

> Auto config from open file (and then looking up directory stack to find nearest project.json) would be perfect.  That bound to a hotkey would make it much easier.

---

The command should be available from `Select Configuration` command and also as a separate key bindable command. After running the command, Wallaby should automatically start.

**Comment by cmidgley** [comment]
Thanks Simon for adding this request.  Having a command that locates the `package.json` automatically, starting at the directory represented by the file in the active tab and scanning upwards until found and then configuring/starting would be perfect.  Assuming this would have a command ID similar to `wallaby.selectConfigFile`, I can then also map it onto a button on my Elgato Stream Deck (where I have a page of Wallaby commands - a really nice way to interact with Wallaby).

**Comment by smcenlly** [comment]
We've added a new command, `wallaby.startOnClosestMonoRepoProject` (Start on closest project in mono-repo). The option is also available when you use the `Wallaby.js: Select Configuration` command.

The option will use the currently opened text editor as context and find the nearest project based on the root of your project containing `package.json` or `jest.config.js`.

**Comment by cmidgley** [comment]
Works great, and such a cleaner workflow for me!    Thank you so much.
