### ISSUE TITLE
Support Jasmine 2.3

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#292]
The newest supported Jasmine is 2.2.1, however 2.3.4 is currently the newest version.
What is your strategy on supporting multiple framework versions?
I can imagine that you don't want to support all future versions, which will make the Wallaby distribution too large. Can't you do some automatich downloading using npm instead of packing the frameworking into Wallaby?

**Comment by ArtemGovorov** [comment]
Out of interest, is there anything in particular missing in 2.3.4 that you are missing in 2.2.1?

The strategy for future is to allow using locally installed framework versions. We already do it for `jest`, will migrate to the same model for `jasmine` as well.

**Comment by fvanwijk** [comment]
No, just wondering why 2.2 is supported and not 2.3. I'm setting up a new project which depends on the newest Jasmine version. Supporting locally installed frameworks is even better than fetching dependencies via Wallaby :).

**Comment by ArtemGovorov** [comment]
For the new project you may just use `testFramework: 'jasmine'` without specifying the version, so whenever 2.3 is supported wallaby will automatically start using it, in a meantime it'll use 2.2, but everything should still work (unless you start using some 2.3 features missing in 2.2).

**Comment by ArtemGovorov** [comment]
v2.3.4 is now supported (and default when no testing framework or version is specified) in core v1.0.129.
