### ISSUE TITLE
Multiple frameworks

### ISSUE THREAD

**Issue by umerkk** [wallabyjs/public#2920]
Hi

I was wondering if wallaby can support a project that has two testing framework being used (Jest & Mocha). 

We have an electron app in which the renderer is based on React + Jest and the main process is on Typescript + Mocha. 
The auto project selection just detects Jest and provide feedback on those test while neglecting the Mocha test files. 

Just wondering if there are some configs that can help or is this not supported at all?

By the way, renderer and main and separated by their own folder hierarchy (if that helps)

**Comment by smcenlly** [comment]
Right now, Wallaby only supports one testing framework at a time.

We have some long-term plans to support multiple frameworks at the same time, but don't have a timeline we can share for this.

We have some other customers who also run heterogenous testing frameworks within the same project and usually what they will do is switch between different testing frameworks based on their current task. To do this, you may create multiple Wallaby configuration files (e.g. one for Jest, and one for Mocha) and switch between them as you need.

**Comment by Rivera-Emmanuel** [comment]
Pretty cool. I hope this is still being considered.
