### ISSUE TITLE
Cannot start test in VS Code with a testing licence

### ISSUE THREAD

**Issue by jbprat** [wallabyjs/public#2925]
### Cannot start test in VS Code with a testing licence
I started a Create React App project in VSCode and I want to test Wallaby testing solution, but I get this error:
![image](https://user-images.githubusercontent.com/7212417/152563134-38464fb3-eed3-48fb-bc57-8b8a429a375c.png)

Even though my licence is supposed to be valid:
![image](https://user-images.githubusercontent.com/7212417/152563208-bd58cdc2-4f05-4e12-a925-8244ff57cc33.png)

### Wallaby diagnostics report

I can't find the report command.

**Comment by smcenlly** [comment]
You will get this issue if you have you are using a trial license from our website for a second time. Please send an email to hello@wallabyjs.com and reference this issue and we will provide you with a different trial license key to use.
