### ISSUE TITLE
pre-tests and post-tests scripts

### ISSUE THREAD

**Issue by Niryo** [wallabyjs/public#2928]
### Issue description or question
I need to run some pretests and posttests scripts, that patches some thing in the node_modules folder. I can't use jest global setup file because it runs too late, I need my patch to be the first thing that runs.
without wallaby, I am jest running:
```
node ./preTests.js; jest; node ./postTests
```
`postTests` just reverts the patch, in order to leave a clean environment. 
how can I do the same thing with latest wallaby?

**Comment by smcenlly** [comment]
I also assume that you are using Wallaby with no configuration file. Is that correct? 

Can you be a little more specific about what you are patching in `node_modules`? Are you able to share your `preTests.js` and `postTests.js` files as well as any other related files so we can understand what you're doing?

**Comment by Niryo** [comment]
I am actually using a configuration file: 
```javascript
module.exports = () => {
  return {
    autoDetect: true,
    testFramework: {
      configFile: './node_modules/@wix/shono/src/jestConfig/jest-config.js',
    },
    env: {params: {env: 'RNTL_SKIP_AUTO_CLEANUP=true;NODE_OPTIONS="--max_old_space_size=20480"'}},
  };
};
```
in my pretest file I am applying the following patches:
```
  {
    /**
    * Workaround for fixing: https://github.com/facebook/react-native/issues/32727
    */
    fileName: 'node_modules/react-native/jest/setup.js',
    target: `global.Promise = jest.requireActual('promise');`,
    replace: '',
  },
  {
    /**
    * Workaround for fixing: https://github.com/callstack/react-native-testing-library/issues/886
    */
    fileName: 'node_modules/@testing-library/react-native/build/helpers/timers.js',
    target: `const fakeTimersType = getJestFakeTimersType()`,
    replace: `const fakeTimersType = undefined`,
  },
  {
    /**
    * Fix swallowed error by ErrorBoundaries:
    */
    fileName: 'node_modules/react-test-renderer/cjs/react-test-renderer.development.js',
    target: `console['error'](combinedMessage);`,
    replace: `console['error'](error)`,
  },
```

**Comment by smcenlly** [comment]
Thanks for providing the additional detail. Our recommendation is to perform what you're doing with Jest configuration instead of a custom script. Besides working with Wallaby, this has the advantage of being more robust (e.g. if `postTests` fails to run for some reason).

You can do what you want to do using `jest` with a custom transformer.

For example, if I am using `lodash` and I want to patch it, my jest configuration might look like this:

**jest.config.js**
```javascript
module.exports = {
  collectCoverage: true,
  coverageDirectory: "coverage",
  coverageProvider: "v8",
  transformIgnorePatterns: [
    // don't transform any node modules EXCEPT for lodash (we want to transform that)
    "node_modules/(?!lodash+)"
  ],
  transform: {
    // Specifically process the `lodash.js` file in the `lodash` node modules
    "node_modules/lodash/lodash\\.js": "<rootDir>/customTransformer.js",

    // TODO: make sure the transform patterns do not conflict with other transforms 
  }
};
```

Your custom transformer would look like this:

**customTransformer.js**
```javascript
const path = require('path');

module.exports = {
  process(src, filename, config, options) {
    // TODO: Perform any replacements in `src`
    return src;
  },
};
```

**Comment by Niryo** [comment]
Looks good, I'll do it. But what about patching jest itself? I used to have few patches for jest too, that  I recently removed. So it's not an issue now but maybe in the future I'll need to add them back again. How can i handle such patches with wallaby?

**Comment by ArtemGovorov** [comment]
Maybe [`npm postinstall` script](https://docs.npmjs.com/cli/v8/using-npm/scripts) is a good place to call the scripts from (especially if you need the patched node modules outside of Wallaby context too). Another (Wallaby specific) place to run the scripts would be Wallaby config:

```
// run scripts here

module.exports = () => { ...
```

**Comment by Niryo** [comment]
Ok, I found few concerns for using jest transformer- apart from being massy, it makes things very hard to debug in case the patch break something, and there is a cache so I fear it will be tricky to update the patch (Everyone will need to clear the cache on every update). 
I ended up putting it inside jest config file directly, and I gave up on trying to clean the patch.
