### ISSUE TITLE
Error when testing ES6 code that imports ES6 named modules

### ISSUE THREAD

**Issue by ludydoo** [wallabyjs/public#293]
Hi,

I wrote multiple ES6 modules and published them with npm.

if module2 depends on module 1 : 

In module2, i do 
```
npm install module1 --save
```

```
// module1.js
import {A} from './a/index.js'
import {B} from './b/index.js'
import {C} from './c/index.js'
export {A, B, C}
---------------

// module2.js
import * as Module1 from 'module1'
```
When running mocha with : 
```
node options : --harmony
mocha options : --compilers js:babel/register
```
It works fine.

When running wallaby with 

```
var babel = require('babel');
module.exports = function (wallaby) {
    return {
        files: [
            'lib/**/*.js'
        ],

        tests: [
            'test/**/*.js'
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel
            })
        },
        env: {
            type: 'node',
            params: {
                runner: '--harmony --harmony_arrow_functions'
            }
        }
    };
};
```

I get

```
Runtime error: /Users/ludydoo/Projects/module1/module1.js:1
(function (exports, require, module, __filename, __dirname) { import {A
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
```

Seems like **installed** modules (npm install module1) are not compiled to ES6

Because if I put the module1 directory inside the module2 directory like so 

```
~/Projects/module1/module2
````

And import the module1 like so

````
import * as Module1 from './module1/module1.js';
```

Wallaby does not throw any error.

**Comment by ArtemGovorov** [comment]
@ludydoo be default wallaby doesn't compile node modules, but tries to use them as is. To make wallaby compile the modules, all you have to do is to put them the your `files` list:

``` JavaScript
var babel = require('babel');
module.exports = function (wallaby) {
    return {
        files: [
            'lib/**/*.js',
            'node_modules/module1/**'
        ],

        tests: [
            'test/**/*.js'
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel
            })
        },
        env: {
            type: 'node',
            params: {
                runner: '--harmony --harmony_arrow_functions'
            }
        }
    };
};
```

Please note that it's better to avoid using a broader pattern like `node_modules/**`, but rather add specific modules, otherwise wallaby will compile all of your installed node_modules, that is probably not desirable.

Please let me know if the solution works for you.

**Comment by ludydoo** [comment]
Hi, 

Your solution works perfectly. 

Though, I fear that it might be problem when requiring modules that themselves require other modules, etc... When using 'node_modules/module1/**/*', it means it includes 'node_modules/module1/node_modules....'. If this module requires phantomjs or any other large library, that's going to be a problem like you said, that wallaby will have to compile it all.

**Comment by ArtemGovorov** [comment]
It's true, though I suspect it's already an issue for mocha even without wallaby. Wallaby also caches compiled files (the cache persists between re-runs), so if your node modules are not changing they are going to be compiled only the first time.

Anyway, one solution to avoid the nested modules compilation would be to set `instrument: false`:
``` JavaScript
    files: [
      'lib/**/*.js',
      {pattern: 'node_modules/module1/**/node_modules/**', instrument: false},
      'node_modules/module1/**'
    ],
```

Another solution would be to publish compiled code to npm as opposed to ES6 modules that are not supported by npm anyway (meaning that your published modules can only be consumed by others with babel).

**Comment by ArtemGovorov** [comment]
@ludydoo So what did you end up doing for the ES6 modules? Did the solution with `instrument: false` work for you (for excluding nested node modules) or you have decided to switch to publishing compiled code?

**Comment by ludydoo** [comment]
Hi Artem,

The instrument : false worked, but I in the end put all my modules back into a single one as it was more complicated to run external tools that don’t understand ES6 yet.

Thank you for your quick support. Wallaby is great!

**Comment by ArtemGovorov** [comment]
@ludydoo Awesome, thanks!
