### ISSUE TITLE
wallaby.js detects invalid test targets in my NX workspace (with builder @nx-dotnet/core:test)

### ISSUE THREAD

**Issue by marleypowell** [wallabyjs/public#2934]
### Issue description or question

wallaby.js detects invalid test targets in my NX workspace.

Expected test target has the `@angular-devkit/build-angular:karma` executor or other supported executors:
```json
{
  "root": "",
  "projectType": "application",
  "sourceRoot": "",
  "targets": {
    "test": {
      "executor": "@angular-devkit/build-angular:karma"
    }
  }
}
```

Recieved test target has the `@nx-dotnet/core:test` executor which is not supported:
```json
{
  "root": "",
  "projectType": "application",
  "sourceRoot": "",
  "targets": {
    "test": {
      "executor": "@nx-dotnet/core:test"
    }
  }
}
```

#### Expected behaviour:
wallaby.js should skip test targets with invalid executors instead of throwing an error.

### Wallaby diagnostics report

```
‌[Error] Automatic Angular CLI configuration error: Cannot find builder "@nx-dotnet/core:test". 
```

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
