### ISSUE TITLE
Feature Request: Html syntax highlight for failing tests

### ISSUE THREAD

**Issue by srosato** [wallabyjs/public#2936]
### Issue description or question

- I am using Webstorm and testing with React Testing library. When a test fails, it prints out the HTML in the console.
- Without Wallaby, when I run a single test, I have syntax highlight within the console.

Example:

![image](https://user-images.githubusercontent.com/650192/155371555-dd30cee6-d54b-4d76-b097-6d1ca3e5d63d.png)

However, I prefer to use Wallaby for all its feature, but when a test fails, I only get a red output for the HTML like this:

![image](https://user-images.githubusercontent.com/650192/155371718-3c107347-e5d0-4039-8109-e0323f0ecbef.png)

Am I missing some sort of configuration? I use automatic configuration.

The red syntax highlighting over strings as shown below is pretty helpful, because I can quickly find strings in the html.

![image](https://user-images.githubusercontent.com/650192/155371985-0585464c-31bb-4844-b886-11a9c38bce22.png)

To make it even more robust, it would be great if Wallaby could understand what could be of value when using react testing library and be smart in its syntax highlighting, for example, any aria attributes, text, or elements with roles (buttons, combobox etc.)

Thanks!

**Comment by srosato** [comment]
This could also be handy within the HTML Coverage/Test Explorer

![image](https://user-images.githubusercontent.com/650192/155457429-e6034a04-f3a3-457e-a64b-06858bfbc0cc.png)

**Comment by ArtemGovorov** [comment]
We have added HTML highlighting in Wallaby output Inspector for both errors and logs in the latest plugin version:

![jb-fm](https://user-images.githubusercontent.com/979966/157381045-71eb1e69-49f7-4840-8939-8b8247c6ed70.gif)

You may use `Alt+Enter` + `Show Value/Error` to display an error or `screen.debug(...)` result in the inspector.
