### ISSUE TITLE
Feature Request: Support passing license to VS Code Remote Container Instances

### ISSUE THREAD

**Issue by Noriller** [wallabyjs/public#2937]
I've tried using devcontainers on vscode and saw that it needs to run in the container so you need to either add the license or do like the tutorial: https://wallabyjs.com/docs/intro/get-started-vscode.html#remote-containers

since there are extensions that run in the "main" vscode and others that run remote, and I don't know if it would work, wouldn't an extension that "prefers" to work on the main vscode be able to fix having to change the containers?

Could also add to that some easy place to change some options and config (both wallaby and quokka)

**Comment by smcenlly** [comment]
> Since there are extensions that run in the "main" vscode and others that run remote, and I don't know if it would work, wouldn't an extension that "prefers" to work on the main vscode be able to fix having to change the containers?

Unfortunately Wallaby/Quokka need to run in the container

---

I'll update the issue title as a feature request to support passing license to remote-container instances (we're not sure if this is technically possible).

**Comment by Noriller** [comment]
My suggestion is about they needing to run in the container.
If the license part were in another extension that didn't need to run in
the container... wouldn't that help?

**Comment by smcenlly** [comment]
> My suggestion is about they needing to run in the container. If the license part were in another extension that didn't need to run in the container... wouldn't that help?

I don't fully understand your comment, but our licensing mechanism needs to run where ever Wallaby is running. If you are using a container, that's where it needs to run.

**Comment by Noriller** [comment]
basically this:
![image](https://user-images.githubusercontent.com/54413263/155585930-6e37482c-1434-4944-883d-028352e3cfc0.png)

**Comment by smcenlly** [comment]
Wallaby will now automatically pass your license to remote container instances. Please update to the latest version of Wallaby for VS Code (`v1.0.334`) and after restarting VS Code, Wallaby should start to automatically apply your license when your remote container is launched.
