### ISSUE TITLE
Create link to Wallaby/Karma test runner config in docs

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#294]
LOL Artem, you're faster than I am, mentioning my own projects -> vjpr/gulp-babel-tasks#1

Could you place a link to this project on the *Files and tests* config docs?
[Test Runner Config](www.github.com/fvanwijk/test-runner-config)

I created this project yesterday, so still under development, but it already saves me a lot of headaches when managing Karma/Wallaby config file lists. I hope it will help other developers as well.

**Comment by ArtemGovorov** [comment]
It is a good idea indeed, thanks for creating it. [Added the section to the docs](http://wallabyjs.com/docs/config/files.html#re-using-file-lists-between-karma-mocha-wallaby).
