### ISSUE TITLE
Detect HTML in output inspector and format with HTML colors/highlighting

### ISSUE THREAD

**Issue by aubrey-ford-nutrien** [wallabyjs/public#2941]
### Issue description or question

Hi, I was just wondering if it is possible to customize the colors in the Output Inspector.  I'm using Webstorm.  This HTML is kinda hard to read:

![image](https://user-images.githubusercontent.com/88005527/156972145-23ab8ba0-e402-4d27-9f9e-f5a3495a0d57.png)

**Comment by smcenlly** [comment]
I'm assuming that Output Inspector is logging text? And I am assuming you would want to format text that looks like HTML with your existing HTML colors that are defined in WebStorm?

**Comment by aubrey-ford-nutrien** [comment]
Ah you're right it's text so my question doesn't make sense at all.  The actual issue is that the output doesn't seem to be logging colors correctly.  At least it's not consistent with Webstorm's Jest test runner and Terminal which are both outputting this:

![image](https://user-images.githubusercontent.com/88005527/157116446-ec6bbb45-8ee5-4d2e-90d1-99a7bad3feea.png)
![image](https://user-images.githubusercontent.com/88005527/157116468-bca40fd7-7274-4437-b083-25ca1602bce0.png)


This is what the original string looks like (I'm not familiar with this format):
"\u001b[36m<body>\u001b[39m\n  \u001b[36m<div>\u001b[39m\n    \u001b[36m<div\u001b[39m\n      \u001b[33mclass\u001b[39m=\u001b[32m\"NmuiBox-root-41 NmuiBox-root-42\"\u001b[39m\n      \u001b[33mdata-testid\u001b[39m=\u001b[32m\"farm-tree\"\u001.........(ect, ect, ect)"

**Comment by smcenlly** [comment]
Wallaby for JetBrains was incorrectly trying to format your large string as code, which is why highlighting was being applied. We've updated the Wallaby JetBrains extension so that highlight is no longer incorrectly applied.

I'm going to repurpose this ticket now as a feature request to detect whether your output is HTML and if so, format using HTML colors.

**Comment by aubrey-ford-nutrien** [comment]
Awesome.  Thank you!

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core and extension version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
