### ISSUE TITLE
Is there a way to have console cleared for every run?

### ISSUE THREAD

**Issue by aubrey-ford-nutrien** [wallabyjs/public#2943]
### Issue description or question

Any time I want to look at Wallaby Console output, I have to manually clear it and then trigger a re-run.  Otherwise it is difficult to tell what output pertains to my last test run.  This is tedious, is there a way to have it automatically clear before each test run?  I'm using Webstorm.

**Comment by ArtemGovorov** [comment]
Wallaby Console output was not designed for continuous inspections, it exists to share the output with us for troubleshooting in certain cases and not meant to be used at all during normal development workflow (incremental test runs). 

Can you please share what output data are you using from the output? Highly likely that there are some other Wallaby features that let you access the same data but in a more ergonomic and suitable way.

**Comment by aubrey-ford-nutrien** [comment]
I ran into a number of situations recently where I wanted to see what the console was saying for each wallaby run even thought nothing was throwing an actual error.  I can't remember most of them, but I do find myself manually clearing the console a lot.  Here are two examples I recently ran into, I'll add more when I remember them.

I'm getting attribute warnings like this and I want to know when I've got it fixed, so I have to clear the console and then trigger another run to make sure the bug is still there:
![image](https://user-images.githubusercontent.com/88005527/157536560-d286cfdb-c908-4d37-9301-1ece2222ed6f.png)

I keep getting this warning and I'm trying things to see how to make it go away:
![image](https://user-images.githubusercontent.com/88005527/157536656-1e92f07b-0bb3-4009-96da-5f34c4b7393c.png)

**Comment by ArtemGovorov** [comment]
> Wallaby's long running code warning:

Those types of warnings are just for information and may not always be an indication of something going wrong. Some of your tests may take longer (than Wallaby reporting timeout) to run, sometimes the issue may be a result of running tests in a middle of your change, etc.

If you want to monitor the performance of your tests, and continuously see what tests are taking more than N milliseconds/seconds to execute, filter/sort by test execution time, and check any selected test dependencies, it's recommended to use [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html):

![wallabyapp_test_filtering](https://user-images.githubusercontent.com/979966/157563801-28bd35c4-c8c1-4466-91b9-d420b9695160.gif)



> Missing key error:
> Attribute warnings:
> Formik error that needs to be fixed even though it doesn't throw:

For these cases it's recommended to to use the [`reportConsoleErrorAsError`](https://wallabyjs.com/docs/config/overview.html#report-consoleerror-as-test-run-error) setting. This way you will not miss the issues as they will be reported as test errors.

Here's Wallaby config that you need to create and then change your Webstorm Wallaby Run Configuration to use the config:

```
module.exports = () => {
  return {
    autoDetect: true,

    reportConsoleErrorAsError: true
  }
};
```

**Comment by aubrey-ford-nutrien** [comment]
Oh thanks, that is good info.
