### ISSUE TITLE
Configure object inspector to call getters?

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#2947]
I've recently switched to SolidJS as a frontend framework.

The store uses getters for everything, so when I debug, e.g. with `//?` I often see stuff like `[ [Getter], [Getter] ]`

Is there anyway to have the inspector call those getters and display the result instead?

Thanks

**Comment by ArtemGovorov** [comment]
By default, Wallaby doesn't resolve getters as they may produce side effects. However, we have an extended version of the `//?` comment that has the following syntax `//?+` and is supposed to do [a bit more than the standard live comment](https://wallabyjs.com/docs/intro/advanced-logging.html#value-explorer-integration). We have just added getter expanding feature to the extended comment. So now if you do

```js
        var a = {
          get b(){
            return 1;
          }
        };

        a; //?+
```
the output inspector will show `{ b: 1 }`.

Please update to use [the latest core v1.0.1241](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and it it should work for you.

**Comment by tslocke** [comment]
That was good timing : ) Works great, thanks.

Sometimes I might not want the sub-objects expanded, but I would still like to see the values of getters. It's really rare to have side-effecting getters, and possibly a criminal offence, so maybe you could consider making this a setting (to always call them).

**Comment by ArtemGovorov** [comment]
Thanks for your feedback. We have added the [new `resolveGetters` setting](https://wallabyjs.com/docs/config/overview.html#resolve-getters-in-output-and-value-explorer) that is now available in the 
[the latest core v1.0.1242](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update):

```js
module.exports = function () {
    return {
      ...
      resolveGetters: true
    };
};
```

With the config above, in case of
```js
var a = {
  get b() {
    return 1;
  }
};
a; //?
```
the output will be `{ b: 1 }`.
