### ISSUE TITLE
Error saving license key: EISDIR: Illegal operation on directory, open ...

### ISSUE THREAD

**Issue by FMGordillo** [wallabyjs/public#2948]

**Comment by FMGordillo** [comment]
And if I use my mail it says "An error occurred attempting to active. You must be connected to the internet in order to activate your license. (Error: self signed certificate in certificate chain)

**Comment by FMGordillo** [comment]
it's a laptop from work using a VPN

**Comment by smcenlly** [comment]
Assuming that you closed the issue because you got everything working. If you need help, let us know, or else email us: hello@wallabyjs.com.
