### ISSUE TITLE
SyntaxError when try to process files with Facebook's flow arrow functions' type annotations

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#295]
Hi @ArtemGovorov I'm having another issue (I think) related with the babel transpilation issue for the files to be tested.

I'm using facebook flow and I'm getting an error when I try to add type annotations to arrow functions like this:

    const fn = (): Array<Object> => ['foo'];

The error looks like this:

    Failed to parse src/modules/to-array.js, SyntaxError: Unexpected token (1:14)
      at emitTwo (events.js:87:13)
      at process.emit (events.js:169:7)
      at handleMessage (child_process.js:306:10)
      at Pipe.channel.onread (child_process.js:334:11)

As you know [I'm using the latest Babel versión](https://github.com/wallabyjs/public/issues/291) and this issues seems to be [already addressed](https://github.com/babel/babel/issues/1991) by the flow and Babel teams.

**Comment by ArtemGovorov** [comment]
Hi @davegomez, wallaby parser doesn't support flow yet, so you can't yet use it with a `preprocessor`. But you should be able to use [babel `compiler`](http://wallabyjs.com/docs/integration/es-next.html) just fine.

So in your wallaby config replace this:
``` JavaScript
preprocessors: {
      '**/*.js': file => babel.transform(file.content, { sourceMap: true })
    }
```
with 
``` JavaScript
compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: babel,
        // https://babeljs.io/docs/usage/experimental/
        stage: 0
      })
    }
```

(note that you need to add `wallaby` param to your config exporting function and add babel variable [like in this sample](http://wallabyjs.com/docs/integration/es-next.html))

**Comment by ArtemGovorov** [comment]
Just doubled checked and can confirm that it does work with compiler like I described above.

<img width="354" alt="screen shot 2015-10-14 at 2 49 47 pm" src="https://cloud.githubusercontent.com/assets/979966/10475107/dc6d8bc6-7282-11e5-8619-b81517565d36.png">

Let me know if works for you.

**Comment by davegomez** [comment]
It worked!

Thanks again.
