### ISSUE TITLE
Test explorer and coverage is not working

### ISSUE THREAD

**Issue by piotrwalczak1** [wallabyjs/public#2959]
### Issue description or question
Version:  VSCode v1.0.333

It is even reproducible using wallaby sample project.

My tests are working, but when I try to 'launch coverage & test explorer' I get :

```
http://localhost:51245/?port=51235
This site can't be reached
```

It worked before, I have not changed anything in the configuration. My config:

```
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.ts',
            "config/**/*",
            { pattern: 'src/**/*.spec.ts', ignore: true }
        ],

        tests: [
            'src/**/*.spec.ts'
        ],

        env: {
            type: "node",
            runner: "node"
        },
        debug: true,

        testFramework: "jest",

        compilers: {
            "**/*.ts?(x)": wallaby.compilers.typeScript({ target: "commonjs" })
        },

        preprocessors: {
            "**/*.js?(x)": (file) =>
                require("@babel/core").transform(file.content, {
                    sourceMap: true,
                    filename: file.path,
                    compact: false,
                    babelrc: true,
                    presets: ["babel-preset-jest"],
                }),
        }
    };
}
```

**Comment by smcenlly** [comment]
A couple of things to try:

**1. Use Wallaby App Vanity URL**
Please try launching Wallaby App using our vanity URL (all communication is still through localhost and not exposed to the internet), [https://wallabyjs.com/app/](https://wallabyjs.com/app/).

**2. Try a different browser**
We've previously had some problems with Safari on MacOS (specifically) not always working but the same URL will work if you copy/paste to a different browser. Perhaps a recent auto-update to an ad-blocker/browser extension has also caused Wallaby to stop connecting? If you have Chrome and are not already using it, please try launching in Chrome. If you are already using Chrome, please try launching in FireFox.

**3. Try rebooting**
For Windows with Hyper-V and Docker, we have previously seen Hyper-V/Docker not releasing network ports after they are automatically acquired as part of their internal communication channels. Just in-case there is something mistakenly holding on to that port in your operating system, can you please try a reboot.

---

If you're still having problems after trying all of the suggestions above, please let us know. Please also provide us with your Wallaby Diagnostics Report at this time.

> Wallaby Diagnostics Report is a simple JSON text report that contains some basic information
> about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.
> 
> To share the report:
> 
> - start Wallaby in your project;
> - wait until it reports some results (finishes running tests);
> - run `Copy Diagnostics Report` command:
>   - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
>   - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
> - paste generated report from your clipboard below (feel free to review and edit the report if required).
