### ISSUE TITLE
Problem with license activation

### ISSUE THREAD

**Issue by raphaelmesquita** [wallabyjs/public#296]
Hi,

I purchased Wallaby and activated on my workplace machine just fine.
But when I try to activate it at home, when I paste the license key I get to see my name at "Registered to" field, but when I hit "Activate" I get that my license was successfully activated but it is registered to 'unkown'.

And then, next time I restart Visual Studio I get the "No valid license" again.
My e-mail is rmesquita@gmail.com and my name is Raphael Lima.

Find attached some screenshot (in chronological order).

Regards,
Raphael Lima

![2 - message](https://cloud.githubusercontent.com/assets/12098986/10502777/d0bafca8-72c5-11e5-8565-c5644894e171.png)
![3 - after_restart](https://cloud.githubusercontent.com/assets/12098986/10502779/d0bf7bc0-72c5-11e5-89b0-1d53a3fc4d31.png)

**Comment by ArtemGovorov** [comment]
Since you've closed the issue, I'm assuming you have found the reason? Out of curiosity, what was the reason?

**Comment by tdd-coder** [comment]
I'm having the same issue.  Using VS 2015 Professional with Resharper and NCrunch installed.

Is it possible to re-open this issue?

**Comment by tdd-coder** [comment]
Also, it's Visual Studio 2015 Pro with Update 1, with version 1.0.20, on Win 10 desktop.

I'll try on my laptop later (also Win 10).

**Comment by ArtemGovorov** [comment]
@tdd-coder we'll have a look into it. The original issue author got it working by just restarting wallaby/VS. Try restarting VS, starting wallaby, wait till runs, and pasting the key again. If it doesn't help, try opening `C:\Users\(user-name)\.wallaby` and creating a text `key.lic` file in there with your license key pasted in the file.

**Comment by tdd-coder** [comment]
I see -- the ".wallaby" folder doesn't appear to be created until wallaby is run for the first time (and downloads its dependencies).  I used the second option, and manually created the .wallaby folder first (and the license file).  

Thanks for the help, I'm up and running! :+1:

**Comment by ArtemGovorov** [comment]
@tdd-coder Thanks for the update! We'll make sure to support the scenario when the license is entered before wallaby downloads its dependencies.

**Comment by ArtemGovorov** [comment]
The issue should be resolved now in the latest VS extension.
