### ISSUE TITLE
Feature Request: Slow Mode / Compatibility Mode

### ISSUE THREAD

**Issue by tharrison4815** [wallabyjs/public#2964]
Could we have a slow mode that can be enabled which runs tests normally, as in runs tests in the same as if you just ran `npx jest` etc. So it will guarantee running the test hooks such as `afterAll`, using a single thread, in the right order etc.

Why would this be useful? For tests which are not compatible with Wallaby, for example they run mock services which require teardown before the tests can be ran again it will allow these to work while still getting the benefits of Wallaby's UI (traffic light indicators on lines, inline debugging etc).

**Comment by smcenlly** [comment]
There are a few settings that can help achieve what you want.

First, the [workers](https://wallabyjs.com/docs/config/workers.html) setting can be used to limit parallelization and force process restart for each test run (in the case where `afterAll` didn't have a chance to execute).

**wallaby.js** (configuration file)
```javascript
 module.exports = function () {
   return {
     workers: {
       // Only run tests with 1 process on start
       initial: 1,

       // Only run tests with 1 process on incremental runs
       regular: 1,

        // Restart the process on each test run
        restart: true,
     }
   };
 };
```

By default, if you are editing a test file, Wallaby will only run the one test that you are executing. If you want Wallaby to execute all tests in your file (the same way that `jest` will), then you can use the [`runAllTestsInAffectedTestFile`](https://wallabyjs.com/docs/config/overview.html#running-all-tests-in-changed-or-affected-test-files) setting.

**wallaby.js** (configuration file)
```javascript
module.exports = function () {
    return {
      ...
      runAllTestsInAffectedTestFile: true
    };
  };
```

---

> So it will guarantee running the test hooks such as afterAll, using a single thread, in the right order etc.

Please note that neither `jest` or Wallaby provide this guarantee. You may run into issues more often in Wallaby but jest doesn't guarantee that `afterAll` will always run. You will need to ensure that your setup/beforeAll/afterAll logic is tolerant of an unexpected process termination. If it isn't the case, then you will need to address it or else you may continue to have some problems with Wallaby.

I should also note that by using the settings above to achieve isolation, you're tests are going to run slower. Obviously if you need that then there's not much you can do about it, but ideally I would try and structure my tests to not rely on each other for execution order, and ideally to be tolerant of afterAll not running. If you're able to make these changes, you'll benefit more from Wallaby incremental test execution speeds.
