### ISSUE TITLE
Monorepo configuration help requested

### ISSUE THREAD

**Issue by cmidgley** [wallabyjs/public#2966]
### Issue description or question

I have pulled together a root project in my monorepo using Jest projects.  When I run it outside of Wallaby, it runs cleanly with all tests passing in about 20 seconds.  In Wallaby, it is slow starting (3-5 minutes), but more importantly it is failing in odd ways.  The browser tool says some tests failed yet shows no failed tests in the list (checking the "failed" option for example).  In the run that I copied the diagnostic report from (below) the browser doesn't even show any tests (though it claims 256 tests passed), yet it does show the files and several have zero coverage (which is not the case, I have 90+% coverage, many at 100%). 

When I open the Wallaby console, I see content like this, though it does vary run to run which modules complain about `export`:

```
‌0 failing tests, 256 passing  ​Launch Coverage & Test Explorer​ | ​Search Tests​

Unexpected token 'export' 
  ​​​​​at ​​​​​​libraries/crypto/src/aesjs.js:1106:1​
  ​​​​​at Object.<anonymous> ​​​​​​libraries/crypto/src/AES.ts:16:1​
  ​​​​​at ​​​​​​libraries/crypto/src/tests/AES.test.ts:4​

Unexpected token 'export' 
  ​​​​​at Object.<anonymous> ​​​​​​libraries/messenger/src/tests/WebSocket.test-node.ts:14:1​

Unexpected token 'export' 
  ​​​​​at Object.<anonymous> ​​​​​​libraries/host-sleep/src/tests/HostSleep-esp32.test.ts:11:1​
```
Each project has it's own `package.json`, `jest.config.ts`, etc, and the root configuration uses Jest's projects option to reference the child projects.  All packages run individualy just fine in Wallaby.  I am using automatic configuration `<project directory>` to start Wallaby.  

Any idea what I might try to debug this?

### Monorepo `jest.config.ts`:

```ts
import type { Config } from "@jest/types";
import { defaultsESM as tsjPreset } from "ts-jest/presets";

const config: Config.InitialOptions = {
	projects: ["<rootDir>/libraries/*"],
	transform: {
		...tsjPreset.transform,
	},
	collectCoverage: true,
	coverageReporters: ["text-summary", "lcov"],
	modulePathIgnorePatterns: ["/common"],
	testEnvironment: "node",
	testPathIgnorePatterns: ["/node_modules/", "/dist/", "/compiled/"],
	resolver: "jest-ts-webcompat-resolver",
	extensionsToTreatAsEsm: [".ts"],
	watchPathIgnorePatterns: [
		"<rootDir>/node_modules/",
		"<rootDir>/dist/",
		"<rootDir>/compiled/",
		"<rootDir>/docs/",
		"<rootDir>/.rush/",
		"<rootDir>/.vscode/",
		"<rootDir>/\\.coverage/",
	],
	globals: {
		"ts-jest": {
			compiler: "ttypescript",
			useESM: true,
		},
	},
};

export { config as default };
```

### Monorepo `package.json`

```json
{
	"name": "amorphous-monorepo",
	"version": "0.1.0",
	"description": "For running tests across all Node projects in the Monorepo",
	"scripts": {
		"test": "NODE_OPTIONS=--experimental-vm-modules jest"
	},
	"type": "module",
	"workspaces": [
		"libraries/*"
	],
	"devDependencies": {
		"@types/jest": "^27.0.3",
		"@types/node": "^16.11.9",
		"@typescript-eslint/eslint-plugin": "^5.6.0",
		"@typescript-eslint/parser": "^5.6.0",
		"eslint": "^8.4.1",
		"eslint-plugin-tsdoc": "^0.2.14",
		"jest": "^27.3.1",
		"ts-jest": "^27.0.7",
		"ts-node": "^10.4.0",
		"tsconfig-paths": "^3.12.0",
		"typescript": "^4.5.3",
		"typedoc": "^0.22.10",
		"typedoc-plugin-missing-exports": "~0.22.6",
		"@jest/types": "~27.4.2",
		"tslib": "~2.3.1",
		"jest-ts-webcompat-resolver": "~1.0.0",
		"jest-resolve": "~27.4.5",
		"@jest/globals": "~27.4.6",
		"ttypescript": "~1.5.13",
		"@cmidgley/di": "https://github.com/cmidgley/di"
	}
}
```

### Wallaby diagnostics report

Due to the size of the diagnostic, I put it in [this gist](https://gist.github.com/cmidgley/787e9369522cea3bb118565686a0a77d)

**Comment by smcenlly** [comment]
> In Wallaby, it is slow starting (3-5 minutes)

I can't help but think this is somehow related to the same issues we saw previously (https://github.com/wallabyjs/public/issues/2955). Your diagnostic report shows that Wallaby is watching `23789` files within your project. This sounds like a lot... do you really have that many source/project files in the mono repo?

> Any idea what I might try to debug this?

I would clone your mono-repo to a fresh directory and then start excluding projects until you have a minimal reproducible example. For instance, you have an error:

```
expected token 'export' 
  ​​​​​at ​​​​​​libraries/crypto/src/aesjs.js:1106:1​
  ​​​​​at Object.<anonymous> ​​​​​​libraries/crypto/src/AES.ts:16:1​
  ​​​​​at ​​​​​​libraries/crypto/src/tests/AES.test.ts:4​
```

If you remove all libraries except for crypto, do you have the same issue?

I think if you can isolate to a minimal reproducible, if you still can't work out what's going on, you should then be able to share an example with us that doesn't have any of your production source code.

---

I didn't see anything obvious in your diagnostics report but I will ask the rest of the team to review when they come online.

---

If you want to share an example of your issue with us and are not comfortable sharing anything publicly, please email us (hello@wallabyjs.com).

**Comment by smcenlly** [comment]
For now, you could consider overriding the files/tests patterns in a Wallaby configuration (or replacing them entirely).

You can read how to do that [here](https://wallabyjs.com/docs/config/files.html#overriding-automatic-configuration).

**Comment by cmidgley** [comment]
I've removed all but one sub-project (and I've tried multiple single projects).  Each project runs fine individually, but with the monorepo base project it's 20K+ files and nothing I do seems to change it (aside from reducing total projects, but that has only a minor impact on total file count).

If I add a `wallaby` section to my root monorepo, such as:

```json
  "wallaby": {
    "tests": [
      {
        "pattern": "node_modules",
        "ignore": true
      },
    ]
}
```

then Wallaby never starts - it just shows the crawling ants forever (well, I've waited two hours ... perhaps it eventually ends).

Two pieces of insight from you may help at least focus my efforts:

1) Where does the Wallaby configuration below?  In my root monorepo, in each sub-project, or both?  If in the root monorepo `package.json`, any ideas why Wallaby fails to ever start (or how to debug it, as I can't get a log)?

2) Where are settings for file watcher used - root project, sub-projects or both?  I can't seem to find anyway to reduce file count when I use a root project.

I have not attempted to override files/test patterns, partially because I don't know where to put it (in the sub-project files it won't help as that number is tiny, in the parent project files then I have the failure of Wallaby ever starting).

Thanks!

**Comment by smcenlly** [comment]
> Where does the Wallaby configuration below go? In my root monorepo, in each sub-project, or both?

If you are using Wallaby without a configuration file, Wallaby will look for the configuration in the root mono-repo `package.json`.

> any ideas why Wallaby fails to ever start?

The configuration that you now have is replacing your jest tests configuration entirely and telling it only to ignore `node_modules`. You have not provided any patterns for identifying tests to run. Besides fixing that, I'd also try to specify the files patterns to minimise the number of files being watched. For example:

**package.json (mono-repo root)**
```javascript
...
  "wallaby": {
    "files": [
      "!**/node_modules",
      "!**/*.spec.js",
      "**/*.js"
    ],
    "tests": [
      "!**/node_modules",
      "**/*.spec.js"
    ]
  }
...
```

> Where are settings for file watcher used - root project, sub-projects or both? I can't seem to find anyway to reduce file count when I use a root project.

Please note the change above to the `node_modules` pattern. Your previous pattern `node_modules` would only exclude the `node_modules` in the mono-repo root. The updated pattern `!**/node_modules` will ignore the root and all nested node_modules. This was probably why the file count was not being reduced.

**Comment by smcenlly** [comment]
I'm assuming our previous advice re: `node_modules` pattern helped fix your problem. If you're still having issues, please let us know.

**Comment by cmidgley** [comment]
Hi - just to close out this issue, I finally got back to working on it today.  It is now working - the big thing I didn't understand was that I could have project-specific settings in each sub-project for Jest, have Wallaby-specific overrides on any elements I need Wallaby to work differently than base Jest.  This, along with then fixing all the include/exclude patterns to be much cleaner across all projects, has solved the problem and is now working across my entire monorepo (and my external code coverage and CI/CD tests are also working, which need a slightly different configuration than Wallaby uses).

Thanks again for all your help.  It's such a awesome tool!

**Comment by smcenlly** [comment]
🥳 awesome - so glad it's all working well for you now!
