### ISSUE TITLE
Configure depth of output inspector?

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#2971]
Hi, is there a way to have the output inspector (and the similar mouse-over popup) show JSON to a greater depth before it bottoms out with `[Object]`?

If not, can I request it?

I realise I can do this with the value explorer with //?+, but I find the value explorer extremely difficult to parse visually and I never use it.

Thanks

**Comment by smcenlly** [comment]
Adding as a feature request

**Comment by smcenlly** [comment]
Closing as a duplicate of https://github.com/wallabyjs/public/issues/2108.
