### ISSUE TITLE
Smart Start not working with config file/run config combo?

### ISSUE THREAD

**Issue by aubrey-ford-nutrien** [wallabyjs/public#2972]
### Issue description or question

Here's my config file and run configuration.  Wallaby still runs all tests that match tests: ['src/**/*.spec.js*'].  I was under the impression it should only run the test files I'm working on.  Does selecting Smart Start from the run config only work for automatic config?

**Comment by smcenlly** [comment]
Could you please provide your Wallaby diagnostics report?

Wallaby Diagnostics Report is a simple JSON text report that contains some basic information
about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you reply with your diagnostics report, we will re-open and investigate further.
