### ISSUE TITLE
Can't start Wallaby: You may use the "wallaby.node" setting to configure the location of node.

### ISSUE THREAD

**Issue by eos-zz** [wallabyjs/public#2973]
I have tried to start wallaby in a number of different angular projects (new and existing) using both Angular 12 and 13, I consistently get the same error: You may use the "wallaby.node" setting to configure the location of node.

My current setting for this in the wallaby settings is %SYSTEM_DEFAULT%

My installed node version is: 
Welcome to Node.js v16.14.2.

Node is in my path at:
C:\Program Files\nodejs
 the Node.exe file is located there.

I can't start wallaby so I don't think I can get a diagnostics report.

I have tried uninstalling the wallaby extension in vscode and reinstalling it, reinstalling node, even deleting all the settings under the user/.vscode/extensions folder for wallaby and still no luck.

I'm trying to get a new project setup with wallaby before moving forward on other development on it so quick assistance with this would be greatly appreciated. 

Thank you!
Jeff Daniels

**Comment by ArtemGovorov** [comment]
Please specify the path to your node.exe file in your VS Code settings as [described here](https://wallabyjs.com/docs/intro/install.html), it should help.

```
{
    ...
    "wallaby.node": "C:\\Program Files\\nodejs\\node.exe"
}
```
