### ISSUE TITLE
Class constructor EventTarget cannot be invoked without 'new'

### ISSUE THREAD

**Issue by damusix** [wallabyjs/public#2981]
<img width="830" alt="Screen Shot 2022-04-29 at 1 00 07 AM" src="https://user-images.githubusercontent.com/4218587/165887534-0da2a88a-b73b-478c-a09f-5280db831d49.png">
<img width="982" alt="Screen Shot 2022-04-29 at 1 00 00 AM" src="https://user-images.githubusercontent.com/4218587/165887536-6410c04e-e131-4049-b500-b11f763cac90.png">

Any idea why it's giving me this error?

**Comment by smcenlly** [comment]
Could you please provide us with a reproducible sample so that we can try and run your code?

Can you please confirm that the same code works when you run your tests outside of Wallaby?

**Comment by smcenlly** [comment]
Closing this issue as we have not heard back. If you can provide us with a sample of your code working outside of Wallaby we will re-open the issue and investigate further.
