### ISSUE TITLE
Configuring env.params.env with comma-separated does not work

### ISSUE THREAD

**Issue by pahund** [wallabyjs/public#299]
I need to provide environment parameters to my tests.
In the [documentation](http://wallabyjs.com/docs/config/runner.html) it says: "env.params.env allows you to set comma-separated spawned runner process environment variables"
When I set a single environment var, all is well. If I try to specify multiple environment variables, comma-separated, all the environment variables are ignored.
See this Gist for a configuration example: https://gist.github.com/pahund/7d335da917e68a16b2c6

**Comment by ArtemGovorov** [comment]
It's an error in the documentation, the separator for env vars is `;` (semicolon), the example in the [mentioned doc section](http://wallabyjs.com/docs/config/runner.html#node-js) has correct sample code demonstrating how to use env params.

I have fixed the documentation to reflect the reality, thanks for finding it.

**Comment by pahund** [comment]
Ah, I see! I tried almost everything, but not the semicolon 😀
