### ISSUE TITLE
Wallaby working with yarn pnp without node_modules on vscode on a monorepo?

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [wallabyjs/public#2990]
### Issue description or question

Is there any approach to get wallaby to work with yarn's pnp without node_modules, on a yarn monorepo?
I've tried all the yarn3 related approaches like adding yarnrc dependencies, creating a wallaby.conf.js file and configuring the node path on the vscode settings.

Ultimately I get wallaby to "start" and say " no tests found", after that I add the wallaby.conf.js file to kind of hardcode the test files I want it to run, but the runner fails because it doesn't find the dependencies that are not "physically" available in node_modules, like react, or react-dom.

### Wallaby diagnostics report

```

```

{
  editorVersion: '1.67.1',
  pluginVersion: '1.0.337',
  editorType: 'VSCode',
  osVersion: 'darwin 21.5.0',
  nodeVersion: 'v17.8.0',
  coreVersion: '1.0.1268',
  checksum: 'YWU5Zjg3NWQ3ODJmMjdlOTY3YzE4YWU0NzBiMjMxYjIsMTY4MDEzNDQwMDAwMCww',
  config: {
    files: [
      { pattern: 'src/**/*.ts', ignore: false, trigger: true, load: true, instrument: true, order: 1 },
      { pattern: 'src/**/*.tsx', ignore: false, trigger: true, load: true, instrument: true, order: 2 },
      { pattern: 'src/**/*.test.ts', ignore: true, trigger: true, load: true, instrument: true },
      { pattern: 'src/**/*.test.tsx', ignore: true, trigger: true, load: true, instrument: true }
    ],
    tests: [
      { pattern: 'src/**/*.test.ts', ignore: false, trigger: true, load: true, test: true, order: 3 },
      { pattern: 'src/**/*.test.tsx', ignore: false, trigger: true, load: true, test: true, order: 4 }
    ],
    diagnostics: {},
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: { '**/*.?(lit)coffee?(.md)': [Function (anonymous)] },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    workers: { initial: 0, regular: 0, recycle: false },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: { type: 'browser', kind: 'chrome', params: {}, viewportSize: { width: 800, height: 600 }, options: { width: 800, height: 600 }, bundle: true },
    reportUnhandledPromises: false,
    throwOnBeforeUnload: true,
    testFramework: { version: 'jasmine@3.10.0', configurator: 'jasmine@2.1.3', reporter: 'jasmine@2.1.3', starter: 'jasmine@2.1.3' },
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    configCode: "module.exports = () => ({\n  files: [\n    'src/**/*.ts',\n    'src/**/*.tsx',\n    '!src/**/*.test.ts',\n    '!src/**/*.test.tsx',\n  ],\n\n  tests: ['src/**/*.test.ts', 'src/**/*.test.tsx'],\n})\n"
  },
  packageJSON: {
    dependencies: { clsx: '^1.1.1', react: '18.0.0', 'react-dom': '18.0.0', tslib: '^2.4.0' },
    devDependencies: {
      '@babel/cli': '^7.17.6',
      '@babel/core': '^7.17.9',
      '@babel/plugin-transform-typescript': '^7.16.8',
      '@babel/preset-env': '^7.16.11',
      '@babel/preset-react': '^7.16.7',
      '@babel/preset-typescript': '^7.16.7',
      '@goe/graphql': '@goe/graphql:*',
      '@goe/utils': '@goe/utils:*',
      '@mui/material': '^5.6.2',
      '@mui/types': '^7.1.3',
      '@testing-library/jest-dom': '~5.16.2',
      '@testing-library/react': '^13.1.1',
      '@testing-library/user-event': '~13.5.0',
      '@types/babel__core': '^7.1.19',
      '@types/babel__preset-env': '^7.9.2',
      '@types/jest': '^27.4.1',
      '@types/node': '^17.0.31',
      '@types/react': '^18.0.5',
      '@types/react-dom': '^18.0.0',
      '@types/react-router-dom': '^5.3.3',
      '@types/testing-library__jest-dom': '^5.14.3',
      'babel-plugin-inline-import-data-uri': '^1.0.1',
      'react-router-dom': '^6.3.0'
    }
  },
  fs: { numberOfFiles: 31 },
  debug: [
    '2022-05-17T09:39:44.221Z project Wallaby Node version: v17.8.0\n',
    '2022-05-17T09:39:44.221Z project Wallaby config: <homeDir>/work/goeng-goe-tools/packages/frontend/ui/wallaby.conf.js\n',
    '2022-05-17T09:39:44.250Z project File cache: <homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.337/projects/6dc95e54e3ad24fe\n',
    '2022-05-17T09:39:44.301Z uiService Listening port 51235\n',
    '2022-05-17T09:39:44.304Z project package.json file change detected, invalidating local cache\n',
    '2022-05-17T09:39:44.402Z workers Parallelism for initial run: 8, for regular run: 4\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #0\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #1\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #2\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #3\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #4\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #5\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #6\n',
    '2022-05-17T09:39:44.402Z workers Starting run worker instance #7\n',
    '2022-05-17T09:39:44.403Z workers Web server is listening at 52679\n',
    '2022-05-17T09:39:44.407Z project File cache requires some updates, waiting required files from IDE\n',
    '2022-05-17T09:39:44.856Z project Stopping process pool\n',
    '2022-05-17T09:39:44.859Z project Running postprocessor\n',
    '2022-05-17T09:39:44.865Z postprocessor New TypeScript language service is required\n',
    '2022-05-17T09:39:45.058Z project Postprocessor execution finished\n',
    '2022-05-17T09:39:45.058Z project Test run started; run priority: 3\n',
    '2022-05-17T09:39:45.058Z project Running all tests\n',
    '2022-05-17T09:39:45.059Z workers Starting test run, priority: 3\n',
    '2022-05-17T09:39:45.059Z workers Distributing tests between 8 workers\n',
    '2022-05-17T09:39:45.059Z workers Running tests in parallel\n',
    '2022-05-17T09:39:45.059Z chromeRunner Starting sandbox [worker #0, session #nxc4k]\n',
    '2022-05-17T09:39:45.059Z chromeRunner Starting sandbox [worker #1, session #c29gx]\n',
    '2022-05-17T09:39:45.059Z chromeRunner Starting sandbox [worker #2, session #5q9xv]\n',
    '2022-05-17T09:39:45.059Z chromeRunner Starting sandbox [worker #3, session #aaglr]\n',
    '2022-05-17T09:39:45.060Z chromeRunner Starting sandbox [worker #4, session #g7us9]\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #0\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #1\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #2\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #3\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #4\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #5\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #6\n',
    '2022-05-17T09:39:45.062Z workers Started run worker instance (immediate) #7\n',
    '2022-05-17T09:39:45.062Z chromeRunner Preparing sandbox [worker #0, session #nxc4k]\n',
    '2022-05-17T09:39:45.062Z browserRunner Total files to load in sandbox: 27\n',
    '2022-05-17T09:39:45.063Z browserRunner Sandbox is generated [worker #0, session #nxc4k]: http://localhost:52679/wallaby_sandbox0.html\n',
    '2022-05-17T09:39:45.063Z chromeRunner Preparing sandbox [worker #1, session #c29gx]\n',
    '2022-05-17T09:39:45.063Z browserRunner Total files to load in sandbox: 27\n',
    '2022-05-17T09:39:45.063Z browserRunner Sandbox is generated [worker #1, session #c29gx]: http://localhost:52679/wallaby_sandbox1.html\n',
    '2022-05-17T09:39:45.063Z chromeRunner Preparing sandbox [worker #2, session #5q9xv]\n',
    '2022-05-17T09:39:45.063Z browserRunner Total files to load in sandbox: 27\n',
    '2022-05-17T09:39:45.063Z browserRunner Sandbox is generated [worker #2, session #5q9xv]: http://localhost:52679/wallaby_sandbox2.html\n',
    '2022-05-17T09:39:45.063Z chromeRunner Preparing sandbox [worker #3, session #aaglr]\n',
    '2022-05-17T09:39:45.063Z browserRunner Total files to load in sandbox: 27\n',
    '2022-05-17T09:39:45.063Z browserRunner Sandbox is generated [worker #3, session #aaglr]: http://localhost:52679/wallaby_sandbox3.html\n',
    '2022-05-17T09:39:45.063Z chromeRunner Preparing sandbox [worker #4, session #g7us9]\n',
    '2022-05-17T09:39:45.063Z browserRunner Total files to load in sandbox: 27\n',
    '2022-05-17T09:39:45.063Z browserRunner Sandbox is generated [worker #4, session #g7us9]: http://localhost:52679/wallaby_sandbox4.html\n',
    '2022-05-17T09:39:45.063Z chromeRunner Prepared sandbox [worker #0, session #nxc4k]\n',
    '2022-05-17T09:39:45.063Z chromeRunner Prepared sandbox [worker #1, session #c29gx]\n',
    '2022-05-17T09:39:45.063Z chromeRunner Prepared sandbox [worker #2, session #5q9xv]\n',
    '2022-05-17T09:39:45.063Z chromeRunner Prepared sandbox [worker #3, session #aaglr]\n',
    '2022-05-17T09:39:45.063Z chromeRunner Prepared sandbox [worker #4, session #g7us9]\n',
    '2022-05-17T09:39:45.063Z workers [worker #0, session #nxc4k] Running tests in sandbox\n',
    '2022-05-17T09:39:45.063Z workers [worker #1, session #c29gx] Running tests in sandbox\n',
    '2022-05-17T09:39:45.063Z workers [worker #2, session #5q9xv] Running tests in sandbox\n',
    '2022-05-17T09:39:45.063Z workers [worker #3, session #aaglr] Running tests in sandbox\n',
    '2022-05-17T09:39:45.063Z workers [worker #4, session #g7us9] Running tests in sandbox\n',
    '2022-05-17T09:39:45.200Z workers [nxc4k] Loaded 0 test(s)\n',
    '2022-05-17T09:39:45.203Z workers [nxc4k] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-17T09:39:45.204Z workers [nxc4k] Sandbox is responsive, closing it\n',
    '2022-05-17T09:39:45.212Z workers [c29gx] Loaded 0 test(s)\n',
    '2022-05-17T09:39:45.215Z workers [c29gx] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-17T09:39:45.216Z workers [c29gx] Sandbox is responsive, closing it\n',
    '2022-05-17T09:39:45.226Z workers [5q9xv] Loaded 0 test(s)\n',
    '2022-05-17T09:39:45.227Z workers [5q9xv] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-17T09:39:45.228Z workers [5q9xv] Sandbox is responsive, closing it\n',
    '2022-05-17T09:39:45.245Z workers [aaglr] Loaded 0 test(s)\n',
    '2022-05-17T09:39:45.248Z workers [aaglr] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-17T09:39:45.249Z workers [aaglr] Sandbox is responsive, closing it\n',
    '2022-05-17T09:39:45.257Z workers [g7us9] Loaded 0 test(s)\n',
    '2022-05-17T09:39:45.260Z workers [g7us9] Run 0 test(s), skipped 0 test(s)\n',
    '2022-05-17T09:39:45.260Z workers [g7us9] Sandbox is responsive, closing it\n',
    '2022-05-17T09:39:45.261Z workers Merging parallel test run results\n',
    '2022-05-17T09:39:45.261Z project Test run finished\n',
    '2022-05-17T09:39:45.261Z project Processed console.log entries\n',
    '2022-05-17T09:39:45.261Z project Processed loading sequences\n',
    '2022-05-17T09:39:45.261Z project Processed executed tests\n',
    '2022-05-17T09:39:45.261Z project Processed code coverage\n',
    '2022-05-17T09:39:45.264Z project Test run result processed and sent to IDE\n'
  ]
}

**Comment by smcenlly** [comment]
How are you running your tests outside of Wallaby? Are you using `jest`? Can you confirm that your tests are working when you're not using Wallaby? e.g. when running them from the command line? If you are using `jest`, you should be able to use [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) (without a configuration file).

From your configuration, it looks like you will need to add `jest` as a `devDependency` to your project. Once you have `jest` working from the command-line, you should be able to follow the instructions in the [Yarn 2](https://wallabyjs.com/docs/integration/yarn2.html) section of our docs. If it's still not working for you, please provide us with a sample repo and instructions for running tests outside of Wallaby and we can take a look for you.

**Comment by jbaccarelli-equinix** [comment]
> How are you running your tests outside of Wallaby? Are you using `jest`? Can you confirm that your tests are working when you're not using Wallaby? e.g. when running them from the command line? If you are using `jest`, you should be able to use [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) (without a configuration file).
> 
> From your configuration, it looks like you will need to add `jest` as a `devDependency` to your project. Once you have `jest` working from the command-line, you should be able to follow the instructions in the [Yarn 2](https://wallabyjs.com/docs/integration/yarn2.html) section of our docs. If it's still not working for you, please provide us with a sample repo and instructions for running tests outside of Wallaby and we can take a look for you.

Sorry for missing that detail, yeah im using Jest and it does work just fine from the command line.
And it does seem to work on this repo too when i "eject" the modules from pnp into regular node_modules.

Creating a reproduction repo is gonna be tough because i would have create a monorepo with a nested folder where i have the tests and usese yarn pnp.

I haven't found any references to specifically "yarn with pnp" on any tutorials or documentation related to yarn3, could you confirm that the default solution should work with pnp too?

Thanks

**Comment by jbaccarelli-equinix** [comment]
Ok so the closest to a solution i found is to do `npm install` on the root of the repo so i have phisicaly node_modules available, but im afraid that every time i do `yarn install` the modules will be gone again xD.
My only guess to make this work "better" would be to somehow use a global (not scoped to the project) installation of jest to run wallaby anywhere, but no idea how to achieve that

**Comment by jbaccarelli-equinix** [comment]
ok so my "solution" makes the yarn repo not work for normal commands after that, like starting the different sub-apps in it because the node_modules conflict with the pnp settings and installation :/ 
Still hoping for a magical solution

**Comment by smcenlly** [comment]
> I haven't found any references to specifically "yarn with pnp" on any tutorials or documentation related to yarn3, could you confirm that the default solution should work with pnp too?

Yes, it should work with pnp if you followed the [Yarn 2](https://wallabyjs.com/docs/integration/yarn2.html) docs (the same docs apply for `Yarn 3`).

---

Without your project structure, it's a little hard to say what you need to do, but I think it should work if you add `jest` as a root dependency in your mono-repo root, and configure `jest` to run all projects within your repo. For example:

**jest.config.js**
```javascript
module.exports = {
	projects: [
		'<rootDir>/app-1/jest.config.js',
		'<rootDir>/app-2/jest.config.js',
		'<rootDir>/app-3/jest.config.js',
	],
}
```

---

> Creating a reproduction repo is gonna be tough

If you're still having problems, perhaps you could do this more easily by taking a copy of your current project and then removing all of your project source files and just leave the configuration files (e.g. `package.json`, `.yarnrc`, `jest.config.js`, etc.). If you're concerned about sharing publicly, you can also email us: hello@wallabyjs.com.

**Comment by jbaccarelli-equinix** [comment]
Wow i think that the problem was. that i had two jest.config.js files under the same workspace, now it's working :)
Thanks for the help!
