### ISSUE TITLE
Feature Request: Option in VSCode to specify a default action when clicking on a failed test.

### ISSUE THREAD

**Issue by bmcbarron** [wallabyjs/public#2993]
In the VSCode Test Explorer there are several useful actions available on-hover and in the context menu of a failed test. As the [documentation](https://wallabyjs.com/docs/intro/get-started-vscode.html) says:

> Common actions are available when you hover over the test name in the Test Explorer view, and additional less-common commands are exposed via the context menu.

However, 95% of the time, I use the same action, "Go to Test". For other users the most common action may be different. It would be nice if we could configure wallabyjs such that selecting a failed test triggers the action of our choice. I find the time to hover over the correct action and click it slows me down. The click target is small, and it is as far away from the test name as possible, so making sure I'm clicking on the right one takes a moment. If I could just click on the failed test name and jump to that test, that'd be a big help!

![image](https://user-images.githubusercontent.com/1638768/169170488-1b70ba31-a9e6-4ff0-b9a3-39a6778de0ce.png)

I have not included a diagnostics report, since this isn't a bug report. If it'd be helpful, let me know.

**Comment by smcenlly** [comment]
When we originally integrated with the Test Explorer, we had reported errors using their API along with the error position (which allows the clickithrough to function) but we didn't like the user experience so we disabled the click-through behaviour with an undocumented setting.

To allow the click-through, please run the VS Code command, `Preferences: Open Settings (JSON)` and then add `"wallaby.testExplorerFeature.showErrorLocation": true`.

```javascript
{
...
  "wallaby.testExplorerFeature.showErrorLocation": true,
...
}
