### ISSUE TITLE
Run multiple instance of WallabyJs in the same project/repositories.

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#2994]
### Feature

Hello,

Following this ticket #2992 , to manage hybrid tests, with Karma and Jest.
I can now run Karma tests on one side, and Jest tests on the other. However, it is not possible to run both commands at the same time. Because there is a restriction on the License. This is normal. But I think there should be an exception when both wallaby commands are run on the same directory/project, so that we can run all tests at the same time.

Thank you.

**Comment by smcenlly** [comment]
Right now, Wallaby does not support running multiple instances on the same project/editor at the same time. We have some long-term plans to support this, but don't have a timeline we can share for this.

Unfortunately the limitation isn't arbitrary, it's an architectural one. From an implementation perspective, a lot of our code is editor-centric which means that we assume that there is a 1:1 mapping between a single code file and a wallaby instance. This means that there are various areas of complexity that aren't simple for us to solve - for example, if code is run by both instances, Wallaby wouldn't be able to correctly calculate code coverage, associated tests, etc.

If you want to track progress and be notified when this feature is available, please subscribe to notifications on [this issue](https://github.com/wallabyjs/public/issues/89).
