### ISSUE TITLE
wallaby claims it cannot find tests but runs them all according to patterns

### ISSUE THREAD

**Issue by pixsrv** [wallabyjs/public#2995]
wallaby.js started
core v1.0.1270
No files with tests found, check your tests list patterns.
Can't determine tests to run for the change.

**Comment by ArtemGovorov** [comment]
It's sometimes possible that the initial quick file scan finishes without finding any tests, but slightly later the tests are discovered (and executed). If it is the case, then you may ignore the temporary log messages that you are observing (unless there are some other issues).

**Comment by pixsrv** [comment]
no other issues but it's always like that
it never start withiut such msg
