### ISSUE TITLE
Logging long strings

### ISSUE THREAD

**Issue by sheltonial** [wallabyjs/public#30]
When using `console.log` and the result is outputted inline with code, an ellipsis is added and there's no way to view the entire output. Perhaps if there was a function available to log the entire output out into the Wallaby console window using say `wallaby.log(...)`?

**Comment by ArtemGovorov** [comment]
Wallaby.js does truncate the inline output, but you can use the context action to quickly view the whole output and even search in it with Ctrl/Cmd + F

https://twitter.com/wallabyjs/status/572716637129854976

Does it solve the issue or I'm missing something?

**Comment by sheltonial** [comment]
You're one step ahead of me... perfect! Problem solved. Thanks.
