### ISSUE TITLE
Provide direct access to the license activation window (to view/change the license)

### ISSUE THREAD

**Issue by szarouski** [wallabyjs/public#300]
Hi, I used personal license at work for WebStorm and now I got company seat license. Unfortunately I can't find a way to change license to company seat. Is it currently possible?

**Comment by ArtemGovorov** [comment]
Hi Sergey, we don't have a UI for that yet. The way to change the license for now would be to delete your current license key (you can find it as [described in this issue](https://github.com/wallabyjs/public/issues/284#issuecomment-145351934)) and then after your IDE restarts, you may use the license activation popup to paste your new license.

**Comment by ArtemGovorov** [comment]
It's now implemented via `Help - Manage Wallaby.js License` menu.
