### ISSUE TITLE
Add support for node v18+ experimental Test runner

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#3000]
Just a quick question if you plan to support the new Node.js test runner. Thanks

https://nodejs.org/api/test.html

**Comment by smcenlly** [comment]
We don't have any immediate plans to add support for it but it is on our radar. We're waiting to see what community adoption is like.

Are you using it? Or planning on using it? If so, what are the features that make you prefer it over other JavaScript/TypeScript test runners? The reason I ask is we had thought at this point in time it was possibly a little too basic in features/functionality (we expect that to change).

**Comment by tomitrescak** [comment]
Hello. Yes, I have been using it quite extensively since they announced it. The benefit is no need for any external library for assertions and execution and the speed that comes with it. Maybe my testing habits do not include too advanced scenarios but at this point I do not have any reason (apart from the missing Wallaby support) to use Mocha or painfully slow Jest. Our codebases are > 500k loc. I still do use "expect" library from time to time as I like their API.

**Comment by muratkeremozcan** [comment]
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/34237651/219389607-6952cc5d-bc74-421b-80df-23e08297382d.png">

TL, DR;
The speed is great
Try node --test on smaller new projects
Do not port existing tests yet
Re-evaluate in 6 months

**Comment by tomitrescak** [comment]
I went Vitest all the way. TS support and speed is really good. Thanks for your breakdown!

**Comment by smcenlly** [comment]
Going to reopen this as it is still a valid feature request.

**Comment by carlansley** [comment]
FYI for those using it, code coverage support for `node:test` has been back-ported to Node 18.15.0.

**Comment by carlansley** [comment]
Another bump for this feature request, with Node 20 (released today) the test runner is now marked as stable.

https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#20.0.0

**Comment by daKmoR** [comment]
I'm definitely interested in this as well - not needing any dependencies for testing is awesome.

less hassle and it just works 👍

**Comment by boneskull** [comment]
I'm starting to use this test runner as well.

**Comment by bacebu4** [comment]
Also Astro ported their tests to node:test, can't wait for the support from you :)

**Comment by azat-io** [comment]
+1 for node:test

**Comment by bacebu4** [comment]
For anyone wanting to run node:test inside VSCode here's cool extension!
https://github.com/connor4312/nodejs-testing

**Comment by smcenlly** [comment]
As of today we have released EXPERIMENTAL support for `node:test` from `node@22.3.x+`. 

As a new testing framework to Wallaby, we've marked this as an experimental feature while we get user feedback and try this with real-world projects. We need to target a specific version of node because prior to `node@22.3.0` there were missing features that we required to integrate with `node:test`.

We'd appreciate your feedback, please let us know if you have any issues. You can either [create a new issue](https://github.com/wallabyjs/public/issues/new), or contact us via email: hello@wallabyjs.com.
