### ISSUE TITLE
add current filename above the preview panel

### ISSUE THREAD

**Issue by pixsrv** [wallabyjs/public#3002]
there is a lister on the left with 2 tabs
then to the right there is a preview panel
and above it there is a lot of empty space (on the level of tabs)
so why not to add a filename (with a path probably)

it would anchor the name in a static place
so scrolling the lister would not "hide" current filename

additionally when dark mode is on
then the selection on the lister is not the best highlighted thing in the universe ;)

**Comment by ArtemGovorov** [comment]
Can you please attach a screenshot describing the current/desired behaviour?

**Comment by pixsrv** [comment]
here you are
![image](https://user-images.githubusercontent.com/10224591/171013611-42cc1680-a170-43aa-99ea-22d9fdeb40b3.png)

**Comment by smcenlly** [comment]
The file name now appears above the file content viewer on this screen. Please refresh Wallaby App and you will see this (from `Wallaby App v1.0.83`+).
