### ISSUE TITLE
Testing React Native

### ISSUE THREAD

**Issue by Tiagojdferreira** [wallabyjs/public#301]
Hey everyone!
I would like to know if it is possible to integrate wallabyjs in a react native project. I have seen that wallaby works with react and jsx, so it should be possible to at least test some components, but I am not sure if will work for the components that use react native components. How should I go about setting my wallaby.js file ?

**Comment by ArtemGovorov** [comment]
Wallaby.js can run your test in browser (using PhantomJs) and node environment, so as long as yo can run your tests in browser or node, wallaby can run them for you. I have heard that some people are testing [react native components with Jest](https://github.com/facebook/react-native/issues/700) and wallaby supports Jest](http://wallabyjs.com/docs/integration/jest.html), so you mat try it.
