### ISSUE TITLE
Wallaby reports wrong line number as a error source

### ISSUE THREAD

**Issue by Dionis-mgn** [wallabyjs/public#3011]
### Issue description or question
This bug is reproducable in Wallaby Tutorial (section 4: Error Reporting).

See gif.

![WallabyBug](https://user-images.githubusercontent.com/5119640/173409851-eb054bc0-0671-45aa-be84-19293f6f2454.gif)

### Wallaby diagnostics report
[wallaby_report.txt](https://github.com/wallabyjs/public/files/8893226/wallaby_report.txt)

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby core, `v1.0.1283`. Wallaby should automatically update for you but if it does not, you can update immediately by using the VS Code command, `Wallaby.js: Force Core Update`.
