### ISSUE TITLE
Import aliases not working for TS + Babel workspace on monorepo with yarn2 

### ISSUE THREAD

**Issue by jbaccarelli-equinix** [wallabyjs/public#3016]
I have this monorepo where most of the workspaces use plain JS, and i have a single workspace that uses TS and compiles with babel.

Before introducing import aliases in my tsconfig and babel.config files wallaby was working just fine by using "automatic config"

but now i get errors about the aliased imports, like 

`import { ... } from '@/testUtils`

which gives an error like this: `Cannot find module '../../../../../../src/testUtils' from ...`

I believe wallaby is trying to resolve the alias going to the root of the project instead of from the workspace root.

I have configured the aliases this way in tsconfig and babel

tsconfig:

```
...
"baseUrl": ".",
"paths": {
      "@/*": ["src/*"],
      "@/config": ["src/config.ts"],
      "@/components/*": ["src/components/*"],
      "@/assets/*": ["src/assets/*"]
    }
...
```

babel.config:

```
...
plugins: [
    'inline-import-data-uri',
    [
      'module-resolver',
      {
        alias: {
          '@': './src',
          '@/config': ['./src/config.ts'],
          '@/components': ['./src/components/*'],
        },
      },
    ],
  ],
```

As i mentioned, everything was working fine for wallaby before adding these aliases (which i would like to keep) and it still works fine for running jest on the console

I tried using a wallaby.config.js file with the preprocessor option, but i get errors about babel-core not being found even if i install it at all levels of the project and globally, and if that error doesn't pop up first, i get other errors about symbols being wrong like `<` or imports

Any ideas?

### Wallaby diagnostics report

[Pastebin link to Diagnostic report which seems to be too long to post here :/](https://pastebin.pl/view/722ded3f)

**Comment by jbaccarelli-equinix** [comment]
> The preprocessor option is not compatible with automatic configuration; if you're using Jest transforms you shouldn't need this anyway.

I've tried the other things you mentioned to no avail, all of them. But could you suggest how to use jest transforms to handle import aliases? I can't seem to find info on that

**Comment by smcenlly** [comment]
Could you please create a sample repo for us that has the problem? Then we will be able to recommend how to fix it. Without seeing your setup it's a little hard to provide specific advice.

**Comment by jbaccarelli-equinix** [comment]
> Could you please create a sample repo for us that has the problem? Then we will be able to recommend how to fix it. Without seeing your setup it's a little hard to provide specific advice.

Ok i created an example repo for this, https://github.com/jbaccarelli-equinix/wallaby-test 

Running both `craco start` and `craco test` work just fine, but wallaby throws an error when i start it

<img width="1219" alt="Screenshot 2022-06-24 at 12 58 40" src="https://user-images.githubusercontent.com/102799139/175521499-6aeebcab-678f-43de-b839-d01de8dba617.png">

**Comment by smcenlly** [comment]
Thanks for your sample project. The reason that it's not working for you is because you are using `craco` to run your tests.

Wallaby does not integrate with `craco` but you can get Wallaby working for your project with a couple of simple changes.

When you run your tests, Wallaby is effectively doing the same as when you run `npx jest` from the command line. For your project, this is the result from the CLI:

```javascript
> npx jest
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    SyntaxError: /Users/smcenlly/repos/temp/wallaby-test/src/App.test.tsx: Support for the experimental syntax 'jsx' isn't currently enabled (6:10):

      4 |
      5 | test('renders learn react link', () => {
    > 6 |   render(<App />);
        |          ^
      7 |   const linkElement = screen.getByText(/learn react/i);
      8 |   expect(linkElement).toBeInTheDocument();
      9 | });

    Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
    If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-jsx) to the 'plugins' section to enable parsing.

      at instantiate (node_modules/@babel/parser/src/parse-error/credentials.js:61:22)
      at toParseError (node_modules/@babel/parser/src/parse-error.js:58:12)
      at Parser.raise (node_modules/@babel/parser/src/tokenizer/index.js:1736:19)
      at Parser.expectOnePlugin (node_modules/@babel/parser/src/tokenizer/index.js:1800:18)
      at Parser.parseExprAtom (node_modules/@babel/parser/src/parser/expression.js:1239:16)
      at Parser.parseExprSubscripts (node_modules/@babel/parser/src/parser/expression.js:684:23)
      at Parser.parseUpdate (node_modules/@babel/parser/src/parser/expression.js:663:21)
      at Parser.parseMaybeUnary (node_modules/@babel/parser/src/parser/expression.js:632:23)
      at Parser.parseMaybeUnaryOrPrivate (node_modules/@babel/parser/src/parser/expression.js:384:14)
      at Parser.parseExprOps (node_modules/@babel/parser/src/parser/expression.js:394:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.264 s, estimated 1 s
Ran all test suites.
```

As per the [`craco` docs](https://github.com/gsoft-inc/craco/blob/master/packages/craco/README.md#jest-api), to run jest from the CLI, you need to have a valid jest configuration:

**jest.config.js**
```javascript
/* jest.config.js */

const { createJestConfig } = require("@craco/craco");

const cracoConfig = require("./craco.config.js");
const jestConfig = createJestConfig(cracoConfig);

module.exports = jestConfig;
```

After updating your `jest.config.js`, the CLI will now pass:

```
> npx jest
 PASS  src/App.test.tsx
  ✓ renders learn react link (17 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.501 s
Ran all test suites.
```

---

There's one last problem that needs to be resolved for your project. Because your project is a `create-react-app` project, Wallaby tries to run your projects with the default jest configuration from `react-scripts`, which will fail.

```
> npx react-scripts test
 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Cannot find module '@testing/TestComponent' from 'src/App.tsx'

    Require stack:
      src/App.tsx
      src/App.test.tsx

      2 | import logo from "./logo.svg";
      3 | import "./App.css";
    > 4 | import { TestComponent } from "@testing/TestComponent";
        | ^
      5 |
      6 | function App() {
      7 |   return (

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/App.tsx:4:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.377 s
Ran all test suites.
```

We need to force Wallaby to use the `jest.config.js` configuration file instead of the react-scripts. You can do this by adding a simple Wallaby configuration file and explicitly setting the path to the jest configuration:

**wallaby.js**
```javascript
module.exports = ({
  testFramework: {
    configFile: './jest.config.js'
  }
});
```

**Comment by jbaccarelli-equinix** [comment]
@smcenlly how would this reflect on a monorepo using only tsconfig and babel to configure aliases on the workspace where i want to run the tests?
I can't find a similar jest config fix for babel

**Comment by jbaccarelli-equinix** [comment]
@smcenlly  I'm not sure if i should continue to post here, or open another issue?
I have uploaded another example, this time i extracted some parts of my existing repo with problems, here im using yarn/berry with a workspace that has some test files, https://github.com/jbaccarelli-equinix/wallaby-test-repo

you should only need to clone it and maybe run `yarn install` but the dependencies are cached and committed already. 
Then if you run `yarn ui test` or `yarn ui coverage` (this runs the tests on the workspace) you will see that the tests are passing just fine, but when i start wallaby with an automatic config it fails to resolve the aliases, this time the workspace is not using craco, just tsconfig for the paths and babel is configured for the build.

Also, if you go the the only test and replace `@/testUtils` for `../../testUtils` wallaby passes without errors, but it won't work for the alias, any ideas?

**Comment by smcenlly** [comment]
In order for Wallaby to run your tests for your entire mono-repo, you need to configure jest to also be able to run from the mono repo using `yarn jest`.

When I run `yarn jest` from the mono-repo root, I get the error:

```
> yarn jest
 FAIL   @goe/ui  packages/frontend/ui/src/components/EqxButton/EqxButton.test.tsx
  ● Test suite failed to run

    Cannot find module '../../../../../../src/testUtils' from '/Users/smcenlly/repos/temp/wallaby-test-monorepo/packages/frontend/ui/src/components/EqxButton'

      at resolveSync (../../../.yarn/cache/resolve-patch-46f9469d0d-5656f4d0be.zip/node_modules/resolve/lib/sync.js:111:15)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.709 s
Ran all test suites.
```

This is the same error I get when trying to use Wallaby.

Please fix the error in `jest` outside of Wallaby. Once you've done that, Wallaby should work for you.
