### ISSUE TITLE
bare import not working

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#3018]
### Issue description or question

Typescript path mapping workaround as described [here](https://github.com/wallabyjs/public/issues/1082), does not work.
Use-case seems to be different:

Rather than  `import { Dictionary } from '/dictionary.js'` I would like to do `import { Dictionary } from 'dictionary'`: a bare import 

Although the testing does not work,  
I am able to build the module and use it chrome browser.

To build the module with bare imports requires two pieces:

1. Typescript Compiler Paths
```json
{
"paths": {
            "dictionary": ["../node_modules/@browser-modules/typescript.dictionary/lib/dictionary.js"]
        }
}
```

2. Importmap in `index.html`
```html
<script type="importmap">
    {
        "imports": {
            "dictionary": "../node_modules/@browser-modules/typescript.dictionary/lib/dictionary.js",
            "events": "../lib/events.js"
        }
    }
</script>
```
To make the testing work I have to provide a relative path:

`import { Dictionary } from "../node_modules/@browser-modules/typescript.dictionary/lib/dictionary.js"` in events.ts file.

A small demonstratable project can be downloaded from GitHub [here](https://github.com/FlippieCoetser/typescript.events)

The HTML script type importmap works great with the chrome browser, is there a way to insert the importmap into the HTML file used by wallaby? or is there a different approach?

**Comment by smcenlly** [comment]
I think ideally your Wallaby and Karma solution should be the same. You need something to process the module imports and re-write your aliases for you so they can resolved by the browser.

For what you're looking to do, I myself would be setting up webpack for Karma with [resolve aliases](https://webpack.js.org/configuration/resolve/). Wallaby also [supports webpack](https://wallabyjs.com/docs/integration/webpack.html#article) and the same webpack configuration that works with Karma should work with webpack.

**Comment by FlippieCoetser** [comment]
@smcenlly, I got my unit tests working via Karma without rewriting any alias. But not yet Wallaby.

What I did was configure Karma to use a custom HTML context.
To do so, I added the below configuration option in my `karma.conf.js`:

```js
customContextFile: "custom.context.html"
```
my custom HTML file is a copy of what Karma uses by default.
The only change I made was to add the importmap: 

```html
<script type="importmap">
    {
        "imports": {
            "dictionary": "/base/node_modules/@browser-modules/typescript.dictionary/lib/dictionary.js"
        }
    }
</script>
```

Help me out with Wallaby, please! I would really like to avoid implementing any bundler.

Question:
**Is there a way to tell Wallaby to also use the same custom HTML context as Karma?**

> I pushed the changes I made to the git repo, so you can just do a pull and execute `npm test` to see successful unit testing via Karma

**Comment by FlippieCoetser** [comment]
@smcenlly I updated the path to the test [repo](https://github.com/FlippieCoetser/Events)

**Comment by NikGovorov** [comment]
@FlippieCoetser, To make Wallaby working in your repo you need to create the following file `aliases.js`:
```javascript
const importMap = {
    imports: {
      "@browser-modules/dictionary":
        "/node_modules/@browser-modules/dictionary/lib/dictionary.js",
    },
  };

  const element = document.createElement("script");
  element.type = "importmap";
  element.textContent = JSON.stringify(importMap);
  document.currentScript.after(element);
```
https://github.com/WICG/import-maps#dynamic-import-map-example

and add the file path as the first entry to `files` collection in `wallaby.js`:

```diff
// typescript paths is an example of how to map an npm module name directly to a file path.

module.exports = function (wallaby) {
  return {
    files: [
+++   "aliases.js",
      "src/**/*.ts",
      "node_modules/@browser-modules/dictionary/lib/dictionary.js",
    ],
    tests: ["test/*.ts"],
    trace: true,
    compilers: {
      "**/*.ts": wallaby.compilers.typeScript({
        module: "es2020",
        target: "es2020",
        sourceMap: true,
        inlineSources: true,
      }),
    }
  };
};

```

You may consider using the same file for Karma to have only one source of truth for path aliases in your project.

**Comment by FlippieCoetser** [comment]
@NikGovorov works like a charm! as per your suggestion I also simplified Karma using `aliases.js`. Can't believe the solution is so simple. In the end pure Typescript, Wallaby, and Typedoc, that is It. I can publish and consume ES6 Modules via NPM, using NO BUNDLER! Absolutely Perfect! Thank you!
