### ISSUE TITLE
snapshot button isn't working on test rows

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#3023]
A follow up to this issue:

https://github.com/wallabyjs/public/issues/3004

<img width="686" alt="image" src="https://user-images.githubusercontent.com/154732/175576657-07fb83c8-20d0-4b31-8058-a96bb23a6151.png">

The snapshot camera buttons on the test rows in the left column don't work.

**Comment by ArtemGovorov** [comment]
https://github.com/wallabyjs/public/issues/3004#issuecomment-1166724048
