### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by JohanHeyvaert** [wallabyjs/public#3024]
After upgrading our monorepository's packages (Nx 14.3.6, Angular 14.0.3, Jest 28.1.3, ts-jest 28.0.5, jest-preset-angular 12.1.0, TS 4.7.4) WallabyJS always crashes shortly after starting with an out of memory error.
We had this error before but then we've remediated it via the node option max_old_space_size. We now tried to increase that maximum size setting to 18192 (seems the maximum for my computer) but to no avail.
The problem occurs with Node v16.15.1 and v18.4.0 (x64 / windows).

After the package updates I had to change a few things to get our application and tests up and running again:
- use type-only imports (cf. https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html - I don't really why but after the updates Angular always gave runtime errors if we didn't use "import type" for type imports)
- in jest.config.ts files: set isolatedModules to false (previously we set this to true in order to improve the test performance but in that case the unit tests fail when testing a class that uses type-only imports)
- in tsconfig.spec.json files: set include to ["**/*.ts"]  (previously we had ["**/*.spec.ts", "**/*.test.ts", "**/*.d.ts", "jest.config.ts"] but this also caused the same problem with type-only imports)
I don't know if these changes matter to Wallaby as it was already crashing before these extra changes.

Outside Wallaby the tests are running correctly. Everything is slow (with just 1 worker) but it works.
Update: VERY SLOW..  ☹

The feature "copy diagnostics report" doesn't seem to work, probably due to the crash.
Below the output of the Wallaby Console and the Wallaby settings. Please let me know if you need more info.

Thanks for your help!

**Wallaby config in package.json**
  "wallaby": {
    "autoDetect": true,
    "noEmitOnError": true,
    "trace": false,
    "runMode": "automatic",
    "delays": {
      "run": 2000
    },
    "workers": {
      "restart": true
    }
  }

**Console output**
wallaby.js started
core v1.0.1296

<--- Last few GCs --->

[2036:000002200B9335F0]   377440 ms: Scavenge (reduce) 18174.7 (18218.6) -> 18174.7 (18219.8) MB, 3.0 / 0.0 ms  (average mu = 0.844, current mu = 0.630) allocation failure 
[2036:000002200B9335F0]   377613 ms: Mark-sweep (reduce) 18175.9 (18219.8) -> 18175.8 (18220.6) MB, 11.3 / 0.0 ms  (+ 328.4 ms in 33 steps since start of marking, biggest step 44.3 ms, walltime since start of marking 350 ms) (average mu = 0.737, current m

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF635E379CF v8::internal::CodeObjectRegistry::~CodeObjectRegistry+114207
 2: 00007FF635DC6096 DSA_meth_get_flags+65542
 3: 00007FF635DC6F4D node::OnFatalError+301
 4: 00007FF6366FB1EE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF6366E57CD v8::SharedArrayBuffer::Externalize+781
 6: 00007FF636588B9C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1468
 7: 00007FF636585CB4 v8::internal::Heap::CollectGarbage+4244
 8: 00007FF636583630 v8::internal::Heap::AllocateExternalBackingStore+2000
 9: 00007FF6365A1340 v8::internal::FreeListManyCached::Reset+1408
10: 00007FF6365A19F5 v8::internal::Factory::AllocateRaw+37
11: 00007FF6365B70CB v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString+75
12: 00007FF63629379C v8::internal::StringStream::ClearMentionedObjectCache+9132
13: 00007FF6364B3C4E v8::sampler::Sampler::Stop+1134
14: 00007FF6364B778A v8::sampler::Sampler::Stop+16298
15: 00007FF6364B6BCA v8::sampler::Sampler::Stop+13290
16: 00007FF6364BB8D5 v8::base::TimeDelta::operator!=+12661
17: 00007FF6364B7CAE v8::sampler::Sampler::Stop+17614
18: 00007FF6364BA466 v8::base::TimeDelta::operator!=+7430
19: 00007FF6366950CF v8::internal::Builtins::code_handle+38911
20: 00007FF636788FE1 v8::internal::SetupIsolateDelegate::SetupHeap+494673
21: 000002200D954064 

Process finished with exit code 134

**Comment by smcenlly** [comment]
> Outside Wallaby the tests are running correctly. Everything is slow (with just 1 worker) but it works.

Do you mean to say that the tests are running very slowly with just 1 worker outside of Wallaby? Or is Wallaby working and running slowly with just 1 worker?

---

If you haven't tried Wallaby with 1 worker process, you may also try that:

**Wallaby config in package.json**
```javascript
{ 
...
  "wallaby": {
    "autoDetect": true,
    "noEmitOnError": true,
    "trace": false,
    "runMode": "automatic",
    "delays": {
      "run": 2000
    },
    "workers": {
      "initial": 1,
      "regular": 1,
      "restart": true
    }
  }
}
```

---

If Wallaby does work with 1 worker process, how does its initial test execution time compare to running `ng test` from the CLI? Once Wallaby starts, is it still slow?

---

The change of setting `isolatedModules` to `false` can make a very big difference to performance (both startup times and memory usage). We have a [blog post](https://wallabyjs.com/blog/optimizing-typescript.html) that I think is worth you reading on TypeScript compilation times.

When `ts-jest` runs your code, it starts a new TypeScript compiler instance in each worker process and will with `isolatedModules` set to `false`, it will be compiling your project in every worker process, which can be very expensive.

We recently discovered that `ts-jest` is [moving to `esbuild/swc` as their default compiler](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets#the-presets) and the TypeScript compiler will be their legacy option.

> Starting from v28.0.0, ts-jest will gradually opt in adoption of `esbuild/swc` more to improve the performance.

We ourselves have been using `jest` with `swc` for a while now on some of our internal projects and it runs well. Are you able to try this for your project. We ourselves are not familiar with how to do this for `nx` workspaces, but we know from other Wallaby users that you can configure `nx` to use `swc` instead of TypeScript ([see here](https://nx.dev/packages/js/executors/swc)). This has appeared to work well for people. This example is for react so may not work for Angular, but you can see their ultimate configuration mentioned [here](https://github.com/wallabyjs/public/issues/3013#issuecomment-1162197751).

---

I assume that you're unable to provide us with access to your project. Are you able to provide us with a sample repo of the same publicly available dependencies and configuration with sample code that doesn't work with `isolatedModules` set to `true`?

**Comment by JohanHeyvaert** [comment]
Wow, thanks for your long reply!

> Do you mean to say that the tests are running very slowly with just 1 worker outside of Wallaby? Or is Wallaby working and running slowly with just 1 worker?

With Wallaby it just doesn't work, neither with just 1 initial/regular worker. It always throws an out of memory exception.

------
> The change of setting isolatedModules to false can make a very big difference to performance (both startup times and memory usage). 

The problem is that I can't get the application to run anymore with isolatedModules: true. This seems to be required by the move to type-only imports. I created a Stackoverflow post and answer with my (current) solution here: https://stackoverflow.com/a/72788471.
The crashing started before I've changed this configuration though.

------
> We recently discovered that ts-jest is [moving to esbuild/swc as their default compiler](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets#the-presets) and the TypeScript compiler will be their legacy option.

I'll try if I can get swc up and running. Thanks for that great suggestion!

------
> I assume that you're unable to provide us with access to your project. Are you able to provide us with a sample repo of the same publicly available dependencies and configuration with sample code that doesn't work with isolatedModules set to true?

Indeed, it's a private project. I'll try to create a sample project if I fail to get swc running or if the problem persists.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. Feel free to reply and we will re-open.

**Comment by JohanHeyvaert** [comment]
Okay, here is where we're at:
- we tried to use swc, but not succeeded in getting it running (the documentation of swc and Nx is not clear at all, so I don't really understand how to configure it)
- we modified our TS setting **emitDecoratorMetadata** to **false** --> this no longer forced us to use type imports (or, alternatively, namespace imports)
- we reverted jest setting **isolatedModules** to **true** 
- we reverted TS setting **include** in our tsconfig.spec.json files to **["/.spec.ts", "**/.test.ts", "**/*.d.ts", "jest.config.ts"]**

But wallaby is still failing with an out of memory exception.

```
core v1.0.1306

<--- Last few GCs --->

[23444:000002881F4AC130]   145755 ms: Mark-sweep (reduce) 8182.6 (8217.5) -> 8182.5 (8218.5) MB, 435.8 / 0.0 ms  (average mu = 0.652, current mu = 0.014) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF71DC395DF node_api_throw_syntax_error+175103
 2: 00007FF71DBC7926 v8::internal::wasm::WasmCode::safepoint_table_offset+67350
 3: 00007FF71DBC87FD node::OnFatalError+301
 4: 00007FF71E659C5E v8::Isolate::ReportExternalAllocationLimitReached+94
...
```

**Comment by smcenlly** [comment]
Sorry to hear you're still having problems. Are you able to provide us with a sample project that has the same problem? Perhaps start with your current project and cut out production code to see if you still have the same problem, that way you're not sharing anything proprietary with us?

**Comment by JohanHeyvaert** [comment]
Sorry, but that's almost impossible. The project is big and full with proprietary logic.

**Comment by smcenlly** [comment]
Could you please add `debug` and `trace` settings to your configuration and then send us the output of your Wallaby Console? After adding these settings, it should include some additional information that may help us diagnose what's going on.

```diff
{ 
...
  "wallaby": {
    "autoDetect": true,
    "noEmitOnError": true,
    "trace": false,
    "runMode": "automatic",
    "delays": {
      "run": 2000
    },
    "workers": {
      "initial": 1,
      "regular": 1,
      "restart": true
    },
+   debug: true,
+   trace: true,
  }
}
```

**Comment by smcenlly** [comment]
I have another couple of suggestions from our team:

---

We noticed that previously you said that you tried to fix the issue setting your `max_old_space_size` to 18192

```
[2036:000002200B9335F0] 377440 ms: Scavenge (reduce) 18174.7 (18218.6) -> 18174.7 (18219.8) MB, 3.0 / 0.0 ms (average mu = 0.844, current mu = 0.630) allocation failure
```

but in your comment from 3 days ago, your logs show:

```
[23444:000002881F4AC130]   145755 ms: Mark-sweep (reduce) 8182.6 (8217.5) -> 8182.5 (8218.5) MB, 435.8 / 0.0 ms  (average mu = 0.652, current mu = 0.014) allocation failure; scavenge might not succeed
```

It looks like the available memory has decreased. Is this expected? It may be contributing to your problem.

---

You may also try to bisect your project files (e.g. exclude half of your tests, and then half again, etc.) to try and isolate the problem. Perhaps your issue is with a specific file (or set of files) and you may exclude those files from being tested with Wallaby.

For example, in the past we had an issue where a very large array (100,000+ elements) was expressed on a single line of code. This caused Wallaby to use a lot of memory while it was attempting to determine source maps after compilation. That particular problem has been fixed, but it's possible that there's something else specific to your project file(s) that may be causing a problem.

**Comment by JohanHeyvaert** [comment]
> Could you please add debug and trace settings to your configuration and then send us the output of your Wallaby Console? After adding these settings, it should include some additional information that may help us diagnose what's going on.

The trace / debug options don't seem to add a lot of info. Probably the problem starts early in the process?
Here is the full output:

```
wallaby.js started
2022-08-01T07:22:16.632Z angular/cli config Detecting Angular CLI.
core v1.0.1307
2022-08-01T07:22:16.771Z angular/cli config Detected Angular CLI.
2022-08-01T07:22:16.774Z angular/cli config Angular currentDirPath: "C:\Dev\buza-ui", workspaceDirPath: "C:\Dev\buza-ui"
2022-08-01T07:22:16.775Z angular/cli nrwl-jest workspace config Configuring.

<--- Last few GCs --->

[6780:00000261108217A0]   152327 ms: Scavenge (reduce) 8176.4 (8217.6) -> 8176.4 (8218.6) MB, 3.4 / 0.0 ms  (average mu = 0.798, current mu = 0.586) allocation failure; 
[6780:00000261108217A0]   152863 ms: Mark-sweep (reduce) 8177.4 (8218.6) -> 8177.2 (8219.6) MB, 533.4 / 0.0 ms  (average mu = 0.613, current mu = 0.084) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF70BAE1C0F node_api_throw_syntax_error+182911
 2: 00007FF70BA6F2F6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+67078
 3: 00007FF70BA7043D node::OnFatalError+301
 4: 00007FF70C5021CE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF70C4ED552 v8::Isolate::Exit+674
 6: 00007FF70C36F5AC v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF70C36C7CB v8::internal::Heap::CollectGarbage+3963
 8: 00007FF70C382A03 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
 9: 00007FF70C3832AD v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
10: 00007FF70C38BBFA v8::internal::Factory::AllocateRaw+810
11: 00007FF70C39EE79 v8::internal::FactoryBase<v8::internal::Factory>::NewHeapNumber<0>+233
12: 00007FF70C3A3388 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString+72
13: 00007FF70C03AC0C v8::internal::StringStream::ClearMentionedObjectCache+9276
14: 00007FF70C28AF82 v8::sampler::Sampler::Stop+1138
15: 00007FF70C28E3E7 v8::sampler::Sampler::Stop+14551
16: 00007FF70C28D994 v8::sampler::Sampler::Stop+11908
17: 00007FF70C292A29 v8::base::TimeDelta::operator!=+13817
18: 00007FF70C28EA7B v8::sampler::Sampler::Stop+16235
19: 00007FF70C291476 v8::base::TimeDelta::operator!=+8262
20: 00007FF70C49690F v8::internal::Builtins::code+99375
21: 00007FF70C59F971 v8::internal::SetupIsolateDelegate::SetupHeap+558449
22: 00007FF68CABE23F 

Process finished with exit code 134
```

**Comment by JohanHeyvaert** [comment]
> We noticed that previously you said that you tried to fix the issue setting your `max_old_space_size` to 18192
> (...)
> It looks like the available memory has decreased. Is this expected? It may be contributing to your problem.

This is as expected: I resetted the variable to `--max_old_space_size=8192` as the higher value didn't help.


> You may also try to bisect your project files (e.g. exclude half of your tests, and then half again, etc.) to try and isolate the problem. Perhaps your issue is with a specific file (or set of files) and you may exclude those files from being tested with Wallaby.

I'll give that a try, thanks for the suggestion.

**Comment by JohanHeyvaert** [comment]
> You may also try to bisect your project files (e.g. exclude half of your tests, and then half again, etc.) to try and isolate the problem. Perhaps your issue is with a specific file (or set of files) and you may exclude those files from being tested with Wallaby.

Okay, so I've tried this and after removing some project files Wallaby starts working. But I am unable to pinpoint the problem to a specific test. 
Also, if I "remove" tests by changing the file names from *.spec.ts to a dummy name (e.g. *.speczzz.ts) then the error continues to occur. 
So the problem seems not caused by the tests themselves but by the amount or the structure of the source code?

FYI, we haven't recently added or modified code. The problem started after updating the dependencies (as described in the first post of this issue).

I've also tried with the latest nodejs version (18.7) but same problem.

**Comment by smcenlly** [comment]
Thanks for the diagnostics report. As you say, it looks like the crash is happening fairly early in processing your project.

The current version that you have been using tries to load/process all project configurations concurrently. We've updated Wallaby to process only one configuration at a time in case this is causing your out of memory error.

Can you please update to Wallaby Core `v1.0.1308` and see if it works for you?

**Comment by smcenlly** [comment]
One other interesting thing to try that we have discovered today while trying to optimise for your project is that your startup time may be impacted for large mono repos that have a lot of different file match patterns. This is because at startup Wallaby needs to check every pattern for include/exclude match for each file.

For a large mono-repo with a large number of distinct patterns and a lot of files, this can slow startup times quite significantly. This may be contirbuting to your problem.

You may attempt to fix this issue by explicitly setting the files and tests patterns to the minimal set required to run your tests. For example:

module.exports = (wallaby) => ({
  autoDetect: true,
  files: [
    'libs/**/**',
    'apps/**/**',
    '!libs/**/+(*.)+(spec|test).+(ts|js)?(x)',
    '!apps/**/+(*.)+(spec|test).+(ts|js)?(x)'
  ],
  tests: [
    'libs/**/+(*.)+(spec|test).+(ts|js)?(x)',
    'apps/**/+(*.)+(spec|test).+(ts|js)?(x)',
    '!/apps/app-e2e/**',
  ]
});

**Comment by JohanHeyvaert** [comment]
Thanks a lot for your help. The newest Wallaby version (now v1.0.1309) seems to solve the memory problem at startup.

However, during the tests itself again a memory error occured:

```
<--- Last few GCs --->

Runtime error: 
[6016:0000022AA493FE80]   491529 ms: Mark-sweep (reduce) 3677.4 (4601.0) -> 3670.7 (4535.0) MB, 838.7 / 0.0 ms  (average mu = 0.045, current mu = 0.045) last resort; GC in old space requested
[6016:0000022AA493FE80]   492509 ms: Mark-sweep (reduce) 3670.7 (4535.0) -> 3670.7 (4508.0) MB, 980.0 / 0.0 ms  (average mu = 0.021, current mu = 0.000) last resort; GC in old space requested

<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

Runtime error:  1: 00007FF70BAE1C0F node_api_
Runtime error: throw_syntax_error+182911
 2: 00007FF70BA6F2F6 v8::internal::MicrotaskQueue::GetMicrotasksScopeDepth+67078
 3: 00007FF70BA7043D node::OnFatalError+301
 4: 00007FF70C5021CE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF70C4ED552 v8::Isolate::Exit+674
 6: 00007FF70C38420E v8
Runtime error: ::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+4030
 7: 00007FF70C38B6DA v8::internal::Factory::CodeBuilder::AllocateCode+106
 8: 00007FF70C38C3B1 v8::
Runtime error: internal::Factory::CodeBuilder::BuildInternal+641
 9: 00007FF70C38C016 v8::internal::Factory::CodeBuilder::Build+22
10: 00007FF70BDDE007 v8::internal::RegExpMacroAssemblerX64::GetCode+4215
11: 00007FF70C0AA9CE v8::internal::RegExpErrorString+9390
1
Runtime error: 2: 00007FF70C094C21 v8::PropertyDescriptor::value+6081
13: 00007FF70C09513C v8::internal::RegExp::CompileForTesting+764
14: 00007FF70C095728 v8::internal::RegExp::DotPrint
Runtime error: ForTesting+248
15: 00007FF70C0967AB v8::internal::RegExp::ExperimentalOneshotExec+2795
16: 00007FF70C093C
Runtime error: 6C v8::PropertyDescriptor::value+2060
17: 00007FF70C06F445 v8::internal::DeclarationScope::was_lazily
Runtime error: _parsed+4885
18: 00007FF70C073D60 v8::internal::DeclarationScope::was_lazily_parsed+23600
19: 00007FF70C59F871 v8::internal::SetupIsolateDelegate::SetupHeap+558193
20: 00007FF70C5FEB96 v8::internal::SetupIsolateDelegate::SetupHeap+948118
21: 00007FF70C58FD
Runtime error: 2B v8::internal::SetupIsolateDelegate::SetupHeap+493867
22: 000
Runtime error: 07FF70C523284 v8::internal::SetupIsolateDelegate::SetupHeap+48772
23: 00007FF70C523284 v8::internal::SetupIsolateDelegate::SetupHeap+48772

Runtime error: 24: 00007FF70C523284 v8::internal::SetupIsolateDelegate::SetupHeap+48772
25: 00007FF70C523284 v8::internal::SetupIsolateDelegate::SetupH
Runtime error: eap+48772
26: 00007FF70C5C1960 v8::internal::SetupIsolateDelegate::SetupHeap+697696
27: 00007FF70C523284 v8::internal::SetupIsolateDelegate::SetupHeap+48772
28: 00007FF70C523284 v8::internal::SetupIsolateDelegate::SetupHeap+48772

Runtime error: 29: 00007FF691315BD4 

Finished executing 57 affected test(s) in 8.28 minute(s)
```

I think I was able to fix this problem by excluding all barrel files from the files configuration. Thanks for that last hint by the way; I was unaware Wallaby allowed this config.

Our Wallaby config is now:

```
"wallaby": {
    "autoDetect": true,
    "noEmitOnError": true,
    "debug": false,
    "trace": false,
    "runMode": "automatic",
    "delays": {
      "run": 2000
    },
    "workers": {
      "restart": true
    },
    "files": [
      "libs/**/**",
      "apps/**/**",
      "!apps/**-e2e/**/**",
      "!**/*.(png|jpg|gif|svg|graphql|scss|spec.ts|test.ts)",
      "!**/i18n/*.json",
      "!**/**/index.ts"
    ],
    "tests": [
      "(apps|libs)/**/*.(spec|test).(ts|js)",
      "!apps/**-e2e/**/**"
    ]
}
```

I'll let you know in case the problem returns. (fingers crossed ;-)

**Comment by JohanHeyvaert** [comment]
It seems that parallel runs cause locking issues. I sometimes get this error:

```
EPERM: operation not permitted, rename 'C:\Users\..\AppData\Local\Temp\jest\jest-transform-cache-996c106453fa6932a74f35427a152f57-2697e17f6738341b1cdada512ba46f39\3e\environmentdefaults_3e9ef3010d6460367b903351c065f893.wallaby.1646618509' -> 'C:\Users\DEVJohanHeyvaert\AppData\Local\Temp\jest\jest-transform-cache-996c106453fa6932a74f35427a152f57-2697e17f6738341b1cdada512ba46f39\3e\environmentdefaults_3e9ef3010d6460367b903351c065f893.wallaby'
    at Object.<anonymous> libs/shared/i18n/src/lib/transloco-root-module/transloco-root.module.ts:2:1
    at Object.<anonymous> libs/shared/forms/src/lib/form-field-clear-button/i18n/translation-scope.ts:1:1
    at Object.<anonymous> libs/shared/forms/src/lib/form-field-clear-button/form-field-clear-button.component.ts:7:1
    at Object.<anonymous> libs/belpas/lazy/domain/src/lib/citizen/search/search-citizen-form.ts:2:1

EPERM: operation not permitted, rename 'C:/Users/.../AppData/Local/Temp/jest/jest-transform-cache-87802d3cca636e4f960600183668c8fe-2697e17f6738341b1cdada512ba46f39/1c/versioninfo_1cbdd4cfe65dfdafdabe9fef9ce4b0d1.wallaby.2959049924' -> 'C:/Users/DEVJohanHeyvaert/AppData/Local/Temp/jest/jest-transform-cache-87802d3cca636e4f960600183668c8fe-2697e17f6738341b1cdada512ba46f39/1c/versioninfo_1cbdd4cfe65dfdafdabe9fef9ce4b0d1.wallaby'
    at Object.<anonymous> libs/bureau/data-access/src/lib/bureau.query.ts:2:1
    at Object.<anonymous> libs/auth/data-access/src/lib/auth.service.spec.ts:6:1

EPERM: operation not permitted, rename 'C:/Users/.../AppData/Local/Temp/jest/jest-transform-cache-fe82a1fc4ceb1ecc678ece21a71f3eb5-2697e17f6738341b1cdada512ba46f39/ec/environmentinfo_ec0dd58886654af3b327577beaad67e4.wallaby.986756266' -> 'C:/Users/DEVJohanHeyvaert/AppData/Local/Temp/jest/jest-transform-cache-fe82a1fc4ceb1ecc678ece21a71f3eb5-2697e17f6738341b1cdada512ba46f39/ec/environmentinfo_ec0dd58886654af3b327577beaad67e4.wallaby'
    at Object.<anonymous> libs/masterdata/data-access/src/lib/codes.query.ts:3:1
    at Object.<anonymous> libs/auth/data-access/src/lib/auth.query.ts:3:1
    at Object.<anonymous> libs/auth/feature/src/lib/sign-in/sign-in.component.spec.ts:3:1

```

So I re-configured workers to initial 1 and regular 1. That seems to work for now.

**Comment by smcenlly** [comment]
Glad to hear that you got it working. Your project / tests sound interesting. I'm keen to understand why the locking is occurring but if you're happy with it, we can leave with the workers setting as is. We really would need to better understand your project structure and what your tests are doing to diagnose this.

Can we now close this issue?

**Comment by JohanHeyvaert** [comment]
Yes, you can close this issue. Thanks again for your help!
