### ISSUE TITLE
`import.meta.resolve` in config file

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#3027]
### Issue description or question

I am using `import.meta.resolve` in my config file. 

This requires `--experimental-import-meta-resolve` to be used by the Node process that reads the config file. Can this be set?

**Comment by ArtemGovorov** [comment]
There's no plugin UI for that, but you may create an `.sh` wrapper file (here's an [example for an obsolete issue](https://github.com/wallabyjs/public/issues/2351#issuecomment-723930744)) that adds the `--experimental-import-meta-resolve` flag to node, and specify the path to the file as a path to node executable in your Run Configuration.

`nodeWithImportMeta.sh`
```
#!/bin/bash
node --experimental-import-meta-resolve "$@"
```
