### ISSUE TITLE
Using `act` with a user event

### ISSUE THREAD

**Issue by Rafael805** [wallabyjs/public#3029]
### Using `act` with a user event

Why is it that I have to wrap the user event in an `act`? Should I always be using an `act` with a user event? It seems to run a lot faster when I wrap it with `act`.

Also, is it still best practice to return `user` from your custom render function and should we be awaiting those events?

For example `await user.click(...)` 

or should we be doing `await act(() => user.click(...))`

![image](https://user-images.githubusercontent.com/19719207/178129990-35caae5b-3489-4115-8103-f4e9dc4c889c.png)

![image](https://user-images.githubusercontent.com/19719207/178130057-1c3f864a-736f-4bfd-91f4-7b8f97fddcaa.png)

**Comment by smcenlly** [comment]
The use of `act` is not actually a part of Wallaby but is related to your testing framework / use of react testing library. You can read more about `act` [here](https://reactjs.org/docs/testing-recipes.html#act). For questions related to its use, we recommend asking the react community or another forum like [stackoverflow](https://stackoverflow.com/questions/60113292/when-to-use-act-in-jest-unit-tests-with-react-dom).
