### ISSUE TITLE
Cannot find Jest test runner​​

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#3037]
I use custom Wallaby configuration in https://github.com/selfrefactor/rambda repo.

I haven't used for a while and now that I tried to run Wallaby, it fails with `Cannot find Jest test runner​​`.

Using automatic configuration doesn't suits me, but it also doesn't work. 

I did try to follow advice from https://stackoverflow.com/questions/71684223/cant-run-wallaby-js-with-jest-in-vscode but the error then is changed to `Cannot find module 'esm'​​`.

This is my custom configuration:

```
const options = { targets : { node : 'current' } }

module.exports = function (wallaby){
  return {
    name: 'Rambda',
    filesWithNoCoverageCalculated: ['src/**/*.js'],
    runMode: 'onsave',
    files: [
      { pattern: 'rambda.js', load: false },
      { pattern: 'package.json', load: false },
      { pattern: 'source/*.js', load: false },
      { pattern: 'source/_internals/*.js', load: false },
      { pattern: '!scripts/**/*.js', load: false, instrument:false },
      { pattern: 'src/*.js', load: false },
      { pattern: 'src/_internals/*.js', load: false },
      { pattern: '!source/**/*.spec.js', load: false },
    ],
    tests: [
      'source/**/*.spec.js'
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets : [ ['@babel/preset-env', options] ],
      })
    },
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    env: {
      type: 'node',
      params: {
        env: 'WALLABY=ON'
      }
    },
    testFramework: 'jest',
    debug: false,
  }
}
```

**Comment by smcenlly** [comment]
It looks like you are using a very recent version of Jest (`28.1.3`) and also Wallaby's legacy `jest` framework setting, which [as per our docs](https://wallabyjs.com/docs/integration/jest-legacy.html) we only recommend for Jest v23 and below.

Automatic configuration can also be used with a configuration file if there are some specific overrides that you need to apply (which seems to be your case). This is recommended for your project and should work for you. To use automatic configuration with a configuration file, simply remove the `testFramework`, `tests` and `files` configuration settings (Wallaby will work those out for you).

The following configuration worked for us with your project:

```javascript
module.exports = function (wallaby) {
  return {
    name: 'Rambda',
    runMode: 'onsave',
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    env: {
      type: 'node',
      params: {
        env: 'WALLABY=ON'
      }
    },
    debug: false,
  }
}
```

If you have other problems with automatic configuration with your project, please let us know, we can help with those.

**Comment by selfrefactor** [comment]
not ideal I have to say. Working with so old version of Jest is a bad price to pay.

**Comment by ArtemGovorov** [comment]
> not ideal I have to say. Working with so old version of Jest is a bad price to pay.

There's no need to use neither old version of Jest, nor to use legacy Wallaby config (with `jest` framework setting). Automatic configuration (with [any manual overrides](https://wallabyjs.com/docs/integration/jest.html?editor=vsc#overriding-automatic-configuration) if required) should work for you.

**Comment by selfrefactor** [comment]
it should work but it doesn't.

I tried last time with this and still no change:

```
const options = { targets : { node : 'current' } }

module.exports = function (wallaby){
  return {
    autoDetect: true,
    name    : 'Rambda',
    runMode : 'onsave',
    workers : {
      reload  : true,
      initial : 4,
      regular : 2,
    },
    env : {
      type   : 'node',
      params : { env : 'WALLABY=ON' },
    },
    debug                         : false,
    filesWithNoCoverageCalculated : [ 'src/**/*.js' ],
    files                         : [
      {
        pattern : 'rambda.js',
        load    : false,
      },
      {
        pattern : 'package.json',
        load    : false,
      },
      {
        pattern : 'source/*.js',
        load    : false,
      },
      {
        pattern : 'source/_internals/*.js',
        load    : false,
      },
      {
        pattern    : '!scripts/**/*.js',
        load       : false,
        instrument : false,
      },
      {
        pattern : 'src/*.js',
        load    : false,
      },
      {
        pattern : 'src/_internals/*.js',
        load    : false,
      },
      {
        pattern : '!source/**/*.spec.js',
        load    : false,
      },
    ],
    testFramework : 'jest',
    tests         : [ 'source/**/*.spec.js' ],
    compilers     : { '**/*.js' : wallaby.compilers.babel({ presets : [ [ '@babel/preset-env', options ] ] }) },
  }
}

```

**Comment by smcenlly** [comment]
Could you please share your Wallaby Diagnostics report when using Automatic Configuration?

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

---

I am guessing that your report will show that your license has expired. There were breaking changes in Jest v28 that are not supported in older versions of Wallaby.

If this is the case, you will need to renew your license to use the latest version of Jest.

You may confirm this by [requesting a trial license](https://wallabyjs.com/download/#try-it-free) from our website.
