### ISSUE TITLE
Unable to start Wallyby.js server when files on WSL2 FS - Cannot invoke "String.indexIf(int)" because "" is null

### ISSUE THREAD

**Issue by sventore** [wallabyjs/public#3042]
### Issue description or question

Node 17.4
WebStorm 2022.2
Project files on WSL2 Ubuntu 20.04
Node 17.4 (on WSL)

Webstorm run-config:
Configuration type: Automatic
Root path: \\wsl$\Ubunti-20.04\home\username\projectname
Node.js: /home/username/.nvm/versions/node/17.4.0/bin/node
Use WSL: Yes

When trying to start Wallaby the webstorm UI shows 2 errors.
Bottom right notification:
```
Wallaby Notification
Error starting wallaby.js server, Cannot invoke
"String.indexOf(int)" because "" is null
```

The "run" tab- also shows a message:
`Error running 'Wallaby': Cannot invoke "com.intellij.execution.process.ProcessHandler.putUserData(com.intellij.openapi.util.Key, Object)" because "this.p" is null`

Wallaby Console shows:
```
Error: ENOENT: no such file or directory, scandir 'WSL$\'
    at Object.readdirSync (node:fs:1392:3)
    at Array.reduce (<anonymous>)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Process finished with exit code 0
```

Since the code is places at the WSL file-system, I guess the root path should be /home/username/projectname - however the wallaby settings dialog will not let me save that configuration even though use WSL is set to yes.
Node.JS path is valid if use WSL is Yes, but it seems like Root-path validation does not take WSL into account in the "Run/Debug Configurations dialog". I've also tried replacing the path directly in .idea/workspace.xml, but wallaby config seems to run validation on WebStorm startup, and forces a config update before starting

**Comment by smcenlly** [comment]
The path should be your Windows file system path. Wallaby will convert it to WSL format when it starts. I've provided an example below (from our docs):

![](https://wallabyjs.com/assets/img/jb-wsl.png)

If you're still having problems, please reply with a screenshot of your run configuration.

**Comment by smcenlly** [comment]
Assuming that our response helped you fix your problem and closing the issue. If you're still having issues, please reply to the issue and we'll re-open it.
