### ISSUE TITLE
`screen.debug()` logs undefined in Output Inspector

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#3051]
Not sure if this is a bug report or a feature request. I remember it worked as expected long time ago, but I can't remember exactly.
(update: could be related to [#165](https://github.com/wallabyjs/public/issues/165))

I'm trying to show the result of Testing Library's [`screen.debug()`](https://testing-library.com/docs/queries/about/#screendebug) in the Output inspector.

`screen.debug()` returns `undefined`, so it makes sense that `undefined` is logged. However console.log is called internally so I still expect this to be in the Output explorer.

If I call `console.log(prettyDOM())`, it works as expected.

Maybe this happens because console.log calls are filtered by the files/tests lists? Is there a way to show console.logs for any file, just like when you run the tests from the terminal?

<img width="573" alt="image" src="https://user-images.githubusercontent.com/963136/184707416-8873c2ec-e4f3-4243-8a7e-7128d905dee9.png">

A second minor issue is that output is hard to read because of the logged color stops. Is it possible to apply those in the output?
![image](https://user-images.githubusercontent.com/963136/184707029-c103a9a2-653a-4ab4-93a1-bce4416cd84f.png)

Expected:
<img width="179" alt="image" src="https://user-images.githubusercontent.com/963136/184707294-fe320013-1c2c-4e75-9618-f97cb2f09f4f.png">

**Comment by smcenlly** [comment]
>  I remember it worked as expected long time ago, but I can't remember exactly.

Wallaby does some patching of `testing-library` at runtime to remove color highlighting, and to allow you to use `Show Value` and live comments after `screen.debug();`.

For some reason it looks like this isn't working for your project. It could be related to your testing framework, project dependencies, or perhaps something else.

Can you please provide your [Wallaby Diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)? It contains the information that we need to investigate further.

**Comment by smcenlly** [comment]
Bumping this issue in case you missed our reply.

**Comment by aweiss-dev** [comment]
I have the same problem while logging ```screen.debug()```.

My Diagnostics report can be found here:
https://jsfiddle.net/drmshx9w/

**Comment by smcenlly** [comment]
Thanks for your diagnostics report. We have found/fixed the issue. Please update to Wallaby core `v1.0.1335`, it should work for you.

**Comment by fvanwijk** [comment]
@smcenlly I actually did not receive any GH notifications except for when you closed the issue :)

I have force updated the core to 1.0.1335 and I still get `undefined` as output when logging testing library using `prettyDOM()` or `screen.debug()`.
![image](https://user-images.githubusercontent.com/963136/196360292-20e1b7e3-d2a3-43ed-bd9c-d2528f4680a4.png)

This is the diag report for a [test repo](https://github.com/fvanwijk/vite-vitest-stubs) that I created for a different issue.
https://jsfiddle.net/8tych3ur/

**Comment by smcenlly** [comment]
Your sample repo appears to be working for us when using the same version of VS Code, MacOS, node, and Wallaby.

<img width="1491" alt="image" src="https://user-images.githubusercontent.com/2074089/196553641-453efbcd-5be3-4324-a0df-c0623048fc5e.png">

We're wondering if there's some cached transform in vite / vitest for the previous version of Wallaby.

Could you please try cloning to a fresh directory to see if it works for you?

If it does work for you, please try using the `Wallaby.js: Reset Wallaby Cache` on your existing directory.

If you're still having problems, can you please let us know how you are installing your dependencies? We used `npm install`.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you're still having issues, please let us know and we will re-open the issue.

**Comment by fvanwijk** [comment]
There is definitely somethong wrong with GH email notifications because I didn't get any email from this thread again, despite the settings:
![image](https://user-images.githubusercontent.com/963136/218077087-b680009b-441f-443e-9fcd-2b9a21426ee8.png)

---

Anyway, the point is not that `//?` doesn't work with `screen.debug()` from Testing Library. When I try to log line 15 in Wallaby, I get the same output.

The issue is that I cannot log `screen.debug()` in the output inspector because it is *calling* console.log instead of *returning* it.

Here is another use case to illustrate what I mean:
<img width="305" alt="image" src="https://user-images.githubusercontent.com/963136/218078044-219f9fad-aff7-499b-8245-6ae5b5db1470.png">
I'd like to `logHello(); //?` output `hello` and not `undefined`

**Comment by fvanwijk** [comment]
In hindsight I see that a duplicate was opened 2 weeks later:
https://github.com/wallabyjs/public/issues/2510

I have core version v1.0.1379, so I would expect to see the component being logged
<img width="622" alt="image" src="https://user-images.githubusercontent.com/963136/218079493-2f98d60a-1703-475c-8dba-7735da4af513.png">

**Comment by smcenlly** [comment]
> Anyway, the point is not that `//?` doesn't work with `screen.debug()` from Testing Library. When I try to log line 15 in Wallaby, I get the same output.

We have applied a fix for this that should address your issue, available in Wallaby core, `v1.0.1380+`. We apply a number of patches to testing-library so that `screen.debug()` will output inline, but this was not working when using `vitest`.

> The issue is that I cannot log `screen.debug()` in the output inspector because it is *calling* console.log instead of *returning* it.

This is intentional. Do not expect Wallaby to output console.log inline for functions that return undefined; it may be intentional to log a function return value and we can't automatically patch all functions in this case. Our patch for `screen.debug()` does not have side-effects so it's safe for us to change the behavior.

> In hindsight I see that a duplicate was opened 2 weeks later:
> https://github.com/wallabyjs/public/issues/2510

This issue was from **2020**, almost 2 years before your issue was raised and was when we originally added support for `screen.debug()` to display inline.
