### ISSUE TITLE
Vitest: startVitest is not a function (VSCODE)

### ISSUE THREAD

**Issue by ryanhyslop** [wallabyjs/public#3053]
### Issue description or question

I've only recently starting using Vitest on a project and this could very much just be a configuration issue at my end but I'm struggling to find any matches for the issue I'm seeing reported.

Essentially wallaby never starts my vitest test run and outputs the following message in the vscode Output for 'Wallaby.js Console':

‍​[Info]​ Started Wallaby.js Core v1.0.1318
​​[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Vitest configuration error: (node:75988) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time​​
​​[Error] (Use `node --trace-warnings ...` to show where the warning was created)​​
​​[Error] startVitest is not a function​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html​​

I can't include a diagnositics report as the tests never actually run. Thing I've tried:
- reseting wallaby cache.
- `npx vitest` runs my tests fine
- adding 'trace: true` to a wallaby section in my package.json (didn't give me any further information).

Versions:
- Wallaby.js Core v1.0.1318
- "vitest": "0.19.1"

Anyone seen this before?

**Comment by smcenlly** [comment]
Can you please try:

1. Deleting `node_modules`
2. Delete `package-lock.json` or `yarn.lock` file(s) if they exist
3. Reinstall node modules

If you still have a problem at this point, please provide us with your `package.json` file and please let us know how you were installing your modules (e.g. `npm`, `yarn`, etc.).

**Comment by ryanhyslop** [comment]
Thanks @smcenlly .... unfortunately deleting node_modules and package-lock.json didn't seem to have an effect.

Here is my package.json file and we're installing packages via npm.

`node --version `
v16.10.0

`npm --version`
7.24.0

```
{
    "private": true,
    "sideEffects": false,
    "scripts": {
        "build": "run-s build:*",
        "build:remix": "remix build",
        "dev": "remix build && run-p \"dev:*\"",
        "dev:remix": "remix watch",
        "dev:arc": "cross-env NODE_ENV=development arc sandbox --host 0.0.0.0",
        "start": "cross-env NODE_ENV=production arc sandbox",
        "test": "vitest run",
        "test:watch": "vitest",
        "test:e2e:dev": "cross-env PORT=3334 start-server-and-test dev http://localhost:3334 \"npx cypress open\"",
        "test:e2e:run": "cross-env PORT=8811 start-server-and-test dev http://localhost:8811 \"npx cypress run\""
    },
    "dependencies": {
        "@remix-run/architect": "^1.6.5",
        "@remix-run/node": "^1.6.5",
        "@remix-run/react": "^1.6.5",
        "@splidejs/react-splide": "^0.7.8",
        "cross-env": "^7.0.3",
        "date-fns": "^2.29.1",
        "framer-motion": "^7.2.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "remix-auth": "^3.2.2",
        "remix-auth-form": "^1.1.2",
        "styled-components": "^5.3.5",
        "tiny-invariant": "^1.2.0"
    },
    "devDependencies": {
        "@architect/architect": "^10.3.4",
        "@badeball/cypress-cucumber-preprocessor": "^12.0.0",
        "@cypress/webpack-preprocessor": "^5.12.0",
        "@remix-run/dev": "^1.6.5",
        "@remix-run/eslint-config": "^1.6.5",
        "@testing-library/cypress": "^8.0.3",
        "@testing-library/jest-dom": "^5.16.5",
        "@testing-library/react": "^13.3.0",
        "@types/react": "^17.0.47",
        "@types/react-dom": "^17.0.17",
        "@types/styled-components": "^5.1.25",
        "@vitejs/plugin-react": "^2.0.0",
        "cypress": "^10.3.1",
        "eslint": "^8.20.0",
        "happy-dom": "^6.0.4",
        "msw": "^0.44.2",
        "npm-run-all": "^4.1.5",
        "start-server-and-test": "^1.14.0",
        "ts-loader": "^9.3.1",
        "typescript": "^4.7.4",
        "vite-tsconfig-paths": "^3.5.0",
        "vitest": "^0.19.1"
    },
    "engines": {
        "node": ">=14"
    },
    "cypress-cucumber-preprocessor": {
        "nonGlobalStepDefinitions": true
    }
}
```

**Comment by ryanhyslop** [comment]
also as a very minor point off the back of this issue the links to the docs return a 404 :)

​​[Error] Please refer to our docs: [https://wallabyjs.com/docs/config/overview.html​​]

**Comment by smcenlly** [comment]
Could you please try upgrading your `vitest` version to the latest (`v0.22.0`)? 

---

> also as a very minor point off the back of this issue the links to the docs return a 404 :)

Does this happen from within VS Code? Or only when you copy/paste text into this issue?

**Comment by ryanhyslop** [comment]
Thanks for getting back to me @smcenlly appreciate your help. Unfortunately upgrading to 0.22.1 hasn't seemed to have made any changes. Starting to wonder if it something to do with my VSCode or node environment 🤔 .
![image](https://user-images.githubusercontent.com/323687/185575772-b9802bcb-7ba2-470f-9704-5869fde93cfa.png)

Running npm test works fine however:

```
npm test
vitest run
 RUN  v0.22.1 /Users/...

 ✓ app/models/...
 ✓ app/models/...
 ✓ app/components/...
 ✓ app/components/...
 ✓ app/components/...
Test Files  5 passed (5)
Tests  15 passed (15)
Start at  09:15:03
Duration  2.69s (transform 2.50s, setup 1.94s, collect 2.94s, tests 418ms)
```

The link to the docs 404's from clicking in VSCode (sorry I didn't want to conflate two issues here so we can ignore this going forward)
![2022-08-19 09 11 38](https://user-images.githubusercontent.com/323687/185575975-1b4ba759-152f-49cd-9612-0cb55ce78625.gif)

**Comment by smcenlly** [comment]
Are you able to provide us with a sample repo that has your problem along with instructions on how to install your repo dependencies?

We are thinking that there may be some issue related to how your project is set up and your dependencies are managed and that should help us isolate the problem.

**Comment by smcenlly** [comment]
Are you still having problems? Are you able to provide us with a sample repo with instructions to install your dependencies?

**Comment by ryanhyslop** [comment]
Hi @smcenlly, sorry for the delayed reply.

I created a small repo this morning to reproduce and Wallaby was working fine, being quite puzzled I went back to the main repo and tried restarting the Smart server and it started working. 🤷‍♂️. Only real difference is the Wallaby Core has been updated to ​Wallaby.js Core v1.0.1326 whilst I was getting this issue initially on v1.0.1318. Not sure if anything changed there or just something really funky with my set up. If I learn anything useful or if it happens again I'll let you know. Doesn't seem like anyone else is reporting this so tempted to think something at my end. 

Thanks for your help on the issue!

**Comment by benthomasknight** [comment]
I also had this issue. It is a problem when I have `env.type` as `node`. Once I removed that it worked just fine.

**Comment by smcenlly** [comment]
@benthomasknight - were you using the latest version of Wallaby or did you have this problem in the past? It appears to be working for us. Can you try [this sample repository](https://github.com/smcenlly/vitest-mocks) to see if you have the same problem?

We had previously discovered that this issue was caused when using node 14. Wallaby only supports Vitest from node v16.12.0+.
