### ISSUE TITLE
Vitest: wallaby fails to start when running it with globalSetup

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/public#3054]
### Issue description or question

When trying to run wallaby with vitest on simple project, it fails to start when vite is configured to run [globalSetup](https://vitest.dev/config/#globalsetup) file.

Here's the simple [repo](https://github.com/bhvngt/wallabyjs-vitest) that reproduces this error.

You can use following steps to reproduce the error

1. git clone https://github.com/bhvngt/wallabyjs-vitest
2. cd wallabyjs-vitest
3. pnpm install
4. running `vitest` from cli should successfully run the test
5. Wallaby fails to start when running the same setup.

### Wallaby diagnostics report

I could not generate wallaby diagnostric report, since wallaby failed to start with following error message

```
Automatic Jest configuration error: Module jest-cli is not found in '.'.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: Unexpected token S in JSON at position 0
```

I am running wallaby on 

```
IntelliJ IDEA 2022.2.1 RC (Ultimate Edition)
Build #IU-222.3739.40, built on August 10, 2022
Runtime version: 17.0.3+7-b469.37 aarch64
macOS 12.5
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. There were a couple of issues related to globalSetup files.

Initially your `console.log` statement was breaking our Vitest configuration parsing:

```javascript
export function setup(){
    console.log("Setting up test")
}
```

After fixing that, we found one more problem. Wallaby was previously attempting to instrument `globalSetup` files, but this is incorrect. Wallaby now no longer attempts to instrument `globalSetup` files. This means that you won't see coverage or reporting on these files and is necessary because of when/how `globalSetup` gets called in the execution pipeline.

Please update to Wallaby `v1.0.1319` to fix your problem.

**Comment by bhvngt** [comment]
Thanks @smcenlly. I am using intellij as my code editor. Has the [Wallabyjs](https://plugins.jetbrains.com/plugin/15742-wallaby/versions) plugin been updated for this editor?

**Comment by smcenlly** [comment]
Wallaby has two parts:

1. Editor Plugin
2. Core Runtime

For this issue, only the core runtime was affected. This is updated automatically by your editor plugin. If Wallaby hasn't updated the Wallaby core version, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). 

For JetBrains Editors, close all instances of your editor and then restart your editor, and start Wallaby. At this point, Wallaby should start updating. Once it has updated to the latest version, try re-starting again, it should work for you.

**Comment by bhvngt** [comment]
While the simple `globalSetup.ts` worked, when I am importing one of the setup file, wallaby breaks. Here's the wallaby diagnostic report. I have also updated my repo with the reproducible [code](https://github.com/bhvngt/wallabyjs-vitest). It works fine on the command line.

I was also trying to setup wallaby using wallaby's configuration file with `vitest`. For this, what should be the value of [testFramework](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). It does not seem to be accepting `vitest` and instead keeps complaining about `mocha`. Is there any other specific consideration I need to keep in mind for wallaby's configuration file while working with `vitest`?

```
{
  editorVersion: 'IntelliJ IDEA 2022.2.1 RC',
  pluginVersion: '1.0.251',
  editorType: 'IntelliJ',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.7.0',
  coreVersion: '1.0.1321',
  checksum: 'MmUxNzQ4YTIxNGUwZjZhODg5YWRhNzc5Y2E0OWY3MzgsMTY2OTU5MzYwMDAwMCww',
  config: {
    diagnostics: {
      vitest: {
        file: {
          config: "import { defineConfig } from 'vitest/config'\n" +
            '\n' +
            'export default defineConfig({\n' +
            '    test: {\n' +
            '        setupFiles: ["./test/setupTest.ts"],\n' +
            '        globalSetup: ["./test/globalSetup.ts"]\n' +
            '    }\n' +
            '})\n'
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: false,
          environment: 'node',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}' ],
          exclude: [ '**/node_modules/**', '**/dist/**', '**/cypress/**', '**/.{idea,git,cache,output,temp}/**' ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 1000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/vitest.config.*/**', '**/vite.config.*/**' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [ {} ] },
          coverage: {
            enabled: false,
            clean: true,
            cleanOnRerun: false,
            reportsDirectory: '<homeDir>/Projects/lab/wallabyjs-vitest/coverage',
            excludeNodeModules: true,
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test{,s}/**',
              '**/*.d.ts',
              'cypress/**',
              'test{,s}/**',
              'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.{js,cjs,mjs,ts}',
              '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}'
            ],
            reporter: [ 'text', 'html', 'clover' ],
            allowExternal: false,
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ],
            tempDirectory: '<homeDir>/Projects/lab/wallabyjs-vitest/coverage/tmp'
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          setupFiles: [ '<homeDir>/Projects/lab/wallabyjs-vitest/test/setupTest.ts' ],
          globalSetup: [ './test/globalSetup.ts' ],
          defines: {},
          root: '<homeDir>/Projects/lab/wallabyjs-vitest',
          deps: { inline: [ {}, {}, {}, {}, {}, {}, '@nuxt/test-utils' ], registerNodeLoader: false },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          cache: { dir: '<homeDir>/Projects/lab/wallabyjs-vitest/node_modules/.vitest' },
          sequence: {},
          package: {
            version: '0.21.1',
            urls: { hooks: 'file://<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.2/wallaby/wallaby/runners/node/hooks.mjs' },
            paths: {
              root: '<homeDir>/Projects/lab/wallabyjs-vitest/node_modules/.pnpm/vitest@0.21.1/node_modules/vitest',
              dist: '<homeDir>/Projects/lab/wallabyjs-vitest/node_modules/.pnpm/vitest@0.21.1/node_modules/vitest/dist'
            }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true, test: true },
      { pattern: 'test/globalSetup.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    tests: [
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: 'test/globalSetup.ts', ignore: true, trigger: true, load: true, test: true, file: false },
      { pattern: '**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}', ignore: false, trigger: true, load: true, test: true, order: 2 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    maxConsoleMessagesPerTest: 100,
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/Library/Caches/JetBrains/IntelliJIdea2022.2/wallaby/wallaby/runners/node/hooks.mjs' },
      runner: '<homeDir>/Library/Application Support/fnm/node-versions/v18.7.0/installation/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: undefined,
    configCode: 'auto.detect#1225208177'
  },
  packageJSON: {
    dependencies: undefined,
    devDependencies: { ajv: '^8.11.0', 'ajv-keywords': '^5.1.0', 'ajv-formats': '^2.1.1', 'ajv-errors': '^3.0.0', vitest: '^0.21.1', vite: '^3.0.7', typescript: '^4.7.4' }
  },
  fs: { numberOfFiles: 8 },
  debug: []
}
```

**Comment by smcenlly** [comment]
> While the simple `globalSetup.ts` worked, when I am importing one of the setup file, wallaby breaks. Here's the wallaby diagnostic report. I have also updated my repo with the reproducible [code](https://github.com/bhvngt/wallabyjs-vitest). It works fine on the command line.

Thanks - we were able to reproduce the problem. The problem that you're having is similar to what you first reported. While Wallaby now detects `globalSetup` files and excludes them from being included in your coverage and reporting, unfortunately we cannot detect this in your `globalSetup` imports.

What you will need to do is explicitly exclude `initAjv.ts` from being instrumented by Wallaby for code coverage and reporting. We needed to update Wallaby to allow `files` and `tests` to be overridden with using `vitest`. To get this working for your project, please:

1. Update to Wallaby Core `v1.0.1322`
2. Create a Wallaby configuration that explicitly ignores `initAjv.ts` (see below): 

**Wallaby.js**
```javascript
module.exports = (wallaby) => ({
  files: {
    override: (filePatterns) => {
      return [...filePatterns, '!test/initAjv.ts'];
    }
  },
});
```

3. Update your Run Configuration to use the newly created **Wallaby.js** configuration file.

---
> I was also trying to setup wallaby using wallaby's configuration file with `vitest`. For this, what should be the value of [testFramework](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). It does not seem to be accepting `vitest` and instead keeps complaining about `mocha`. Is there any other specific consideration I need to keep in mind for wallaby's configuration file while working with `vitest`?

Wallaby should automatically detect vitest in **most** cases. Wallaby will not automatically detect vitest if:

1. You have `autoDetect: false` in your configuration file
2. You declare `files: []` setting to be an array (object is ok)
3. You declare `tests: []` setting to be an array (object is ok)
4. You set autoDetect to an array missing the `vitest` string value.

If for example, you have multiple testing frameworks installed (jest, vitest, angular), and you explicitly want to use vitest with `tests` and `files` array, your configuration may look like:

**wallaby.js** (explicit vitest example)
```javascript
module.exports = (wallaby) => ({
  autoDetect: ['vitest'],
  files: [
    'src/**/*.ts',
  ],
  tests: [
    'test/**/*.spec.ts',
  ]
});
```

**Comment by bhvngt** [comment]
Thanks @smcenlly. With your suggestion I was able to make wallaby work. Unfortunately, in my project, I am setting up database which ends up traversing quite a few source files. excluding them from the coverage and reporting will kind of defeat the purpose. For the time being, I have moved that logic to [beforeAll](https://vitest.dev/api/#beforeall). It's not ideal as it may be running it for each suite. So I have added some heuristics to make it run only once. 

Would you have any alternate suggestions?

> Wallaby should automatically detect vitest in most cases. Wallaby will not automatically detect vitest if:
> 
> You have autoDetect: false in your configuration file
> You declare files: [] setting to be an array (object is ok)
> You declare tests: [] setting to be an array (object is ok)
> You set autoDetect to an array missing the vitest string value.
> If for example, you have multiple testing frameworks installed (jest, vitest, angular), and you explicitly want to use vitest with tests and files array, your configuration may look like:

This worked fine. Thank you for your example.

**Comment by smcenlly** [comment]
> Would you have any alternate suggestions?

It's the end of our day here. Tomorrow I'll investigate whether it is possible to add some special logic/processing for all globalSetup imports so that we can process them without instrumentation within globalSetup context and with instrumentation outside of a globalSetup context.

For now, I've re-opened the issue.

**Comment by smcenlly** [comment]
We've updated Wallaby (`v1.0.1324`+) so that it no longer instruments any files or captures logs, etc. when running your globalSetup. You should not need to have a custom configuration file anymore with this change.

**Comment by bhvngt** [comment]
Thanks @smcenlly. While these works on the sample project, on my workspace project, wallaby is only running one single test. I tried resetting the cache, but still getting the same result. Before this update it was running my entire test suite across sub modules (without globalSetup). I might be missing something here. Trying to reproduce this issue on a sample project.

Meanwhile would you have suggestions on things to try?

**Comment by bhvngt** [comment]
My bas I was running test suite with `it.only`. Sorry about that.

**Comment by bhvngt** [comment]
I would like to exclude a particular module from the wallaby test run. I believe, for this I will have to use wallaby's configuration file. I am using following code in the `wallaby.js`. It is not excluding that module.

```
export default (wallaby) => ({
    files: {
        override: (filePatterns) => {
            return [...filePatterns, "!apps/web/**/*"];
        }
    },
    setup: async (wallaby) => {
        process.env.localProjectDir = 'file://' + wallaby.localProjectDir;
    }
});
```

**Comment by smcenlly** [comment]
To exclude files from being tested, you'll need to add them to the `tests` override.

There's an example in [our docs](https://wallabyjs.com/docs/config/files.html#modify-automatic-configuration-files-andor-tests).

**Example Wallaby.js Configuration**
```javascript
module.exports = () => ({
  // modify `files` automatic configuration settings
  files: {
    override: (filePatterns) => {
      // TODO: modify `filePatterns` array as required
      return filePatterns;
    }
  },

  // modify `tests` automatic configuration settings
  tests: {
    override: (testPatterns) => {
      // TODO: modify `testPatterns` array as required
      return testPatterns;
    }
  }
});
```

For your file, something like this should work:

```javascript
export default (wallaby) => ({
    files: {
        override: (filePatterns) => {
            return [...filePatterns, "!apps/web/**/*"];
        }
    },
    tests: {
        override: (filePatterns) => {
            return [...filePatterns, "!apps/web/**/*"];
        }
    },
    setup: async (wallaby) => {
        process.env.localProjectDir = 'file://' + wallaby.localProjectDir;
    }
});
```

**Comment by bhvngt** [comment]
Excellent.. Everything is working great. You guys as always rock. 🚀
