### ISSUE TITLE
Wallaby.js Toggle Output Inspector Focus not working

### ISSUE THREAD

**Issue by etiennejcharles** [wallabyjs/public#3062]
### Issue description or question
Is it me, or I'm not understanding how this is supposed to work ? 

**Expected**: Wallaby.js Output Tests to be Focused. 
**Got**: Nothing happens, as if no commands was passed. 

Here's an example. 
![stuff](https://user-images.githubusercontent.com/2872476/187440882-a2b5652a-ffec-4b71-a258-ab5f3558be12.gif)

WallabyJs: v1.0.347
VsCode: Version: 1.71.0-insider (Universal)

**Comment by smcenlly** [comment]
`Output Inspector` is a readonly code editor instance that has all basic built-in editor features such as syntax highlighting, copying, search etc. that can be launched next to your code editor when the inline value you have logged is too big. See example below. If you do not have a value displayed on your current line when you use the command, then nothing will happen.

![outputinspector](https://user-images.githubusercontent.com/2074089/187551973-d5d22804-3380-49cb-96d7-e49ddc6914c7.gif)

You can read more about output inspector in [our docs](https://wallabyjs.com/docs/intro/output-inspector.html?editor=vsc).

**Comment by etiennejcharles** [comment]
Thanks !
