### ISSUE TITLE
Wallaby not starting in Webstorm / NX : Error starting wallaby.js server, Cannot run program "node" (in directory "/Users/XXXXXX/Documents/Sandpit/wallaby-test"): error=2, No such file or directory"

### ISSUE THREAD

**Issue by baggsie** [wallabyjs/public#3063]
Hi,

Wallaby is not launching and I'm getting the following error in Webstorm (Build #WS-222.3739.57, built on August 16, 2022)  with an Nx project ( Angular & NestJS)

In a notification popup (bottom right) :  
"Error starting wallaby.js server, Cannot run program "node" (in directory "/Users/XXXXXX/Documents/Sandpit/wallaby-test"): error=2, No such file or directory"

Popup from the 'run' panel :
<img width="856" alt="Screenshot 2022-08-30 at 22 19 47" src="https://user-images.githubusercontent.com/13902975/187535290-aaad41c2-eca7-4f3a-aa43-e2338df57f0f.png">

I'm unable to generate a diagnostics report

I've created a sample repo : https://github.com/baggsie/wallaby-pb

Cheers, 

Baggsie

**Comment by smcenlly** [comment]
We tried your project on the same version of WebStorm and everything is working for us.

From the error, it appears the directory `/Users/XXXXXX/Documents/Sandpit/wallaby-test` does not exist. I assume you redacted the `XXXXXX` part. 

Can you please confirm that the directory referenced exists? It looks like there may be a problem with your run configuration.

Our run configuration looks like this:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/2074089/187553348-170559f6-c815-4b07-b91f-af91c6f4589b.png">

**Wallaby.run.xml**
```xml
<component name="ProjectRunConfigurationManager">
  <configuration default="false" name="Wallaby" type="wallaby" factoryName="wallaby" configType="Automatic" configFolder="$PROJECT_DIR$" wsl="No" SmartStart="No">
    <method v="2" />
  </configuration>
</component>
```

**Comment by baggsie** [comment]
Thanks for your reply,

Yes the XXXX is a redaction. 

I can confirm the directory exists. 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/13902975/187643735-b96dd37b-30c3-456e-8da8-2aa902ff27fb.png">

I've tested the same project in VSCode and Wallaby is working correctly.

**Comment by baggsie** [comment]
I've just reinstalled the plugin and it's working now.  

I'll keep you informed if it happens again.

Thanks for your help.
