### ISSUE TITLE
when wallaby starts it always shows misleading info

### ISSUE THREAD

**Issue by pixsrv** [wallabyjs/public#3064]
**No files with tests found, check your tests list patterns.**

and "of course" it finds both files and tests and runs them properly

here is my package.json part
```
  "wallaby": {
    "trace": false,
    "debug": false,
    "slowTestThreshold": 200,
    "files": [
      "src/components/ResponsiveUI/**/*.[jt]s?(x)",
      "!src/**/__tests__/**/*.[jt]s?(x)",
      "!src/**/?(*.)+(spec|test).[jt]s?(x)"
    ],
    "tests": [
      "src/components/ResponsiveUI/**/__tests__/**/*.[jt]s?(x)",
      "src/components/ResponsiveUI/**/?(*.)+(spec|test).[jt]s?(x)",
    ]
  }

```

**Comment by ArtemGovorov** [comment]
When Wallaby starts, it uses a library to scan for files and tests patterns. Looks like in your case the library exits (possibly by timeout) before the file system scan is finished, causing the misleading message to appear, and when the scan correctly finishes - to disappear. Can you please share your full Wallaby diagnostics report (the steps to get the report are listed in a new issue template) so we could confirm if it is the fs scan issue (in which case it's pretty harmless), or something else?

**Comment by smcenlly** [comment]
Closing this issue as we didn't hear back.
