### ISSUE TITLE
Typescript abstract classes

### ISSUE THREAD

**Issue by ludydoo** [wallabyjs/public#307]
Hi,

When declaring abstract classes in typescript and running tests with wallaby, it seems the compiler complains about "Reference error abstract not defined"

https://github.com/ludydoo/wallaby-abstract-err

**Comment by ArtemGovorov** [comment]
If I'm not mistaken, abstract classes is TS 1.6 feature and wallaby compiler by default uses 1.5.3. If you would like it to use 1.6, you may just [reference your locally installed version](http://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-version) in the compiler settings. Let me know if it helps.

**Comment by ludydoo** [comment]
Indeed! That did it. Thanks again for amazing support.
