### ISSUE TITLE
Can't figure out how to get wallaby to read my config file

### ISSUE THREAD

**Issue by anicolao** [wallabyjs/public#3071]
I can't seem to figure out how to point Wallaby.js at my desired config file, which is named `Wallaby.cjs` and contains:
```
module.exports = function (wallaby) {
    return {
      files: [
        'src/**/*.ts'
      ],

      tests: [
        'src/**/*.unit.ts'
      ],

      testFramework: 'mocha'
    };
  };
```

### Wallaby diagnostics report

I cannot provide a diagnostics report because Wallaby will not start. It seems intent on using auto configuration which I had briefly tried out of desperation but now cannot seem to get out of.
```
‍​[Info]​ Started Wallaby.js Core v1.0.1328
​​[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Vitest configuration error: Vitest dependency not found.​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
```
When I choose the `Select Configuration` command from the command palette, no matter what I type in the input field, I can't seem to get it to accept my input. I have tried `Wallaby.cjs`, `Wallaby.js` and `./Wallaby.js`.

**Comment by anicolao** [comment]
FWIW it works trivially with vitest.

**Comment by smcenlly** [comment]
> I can't seem to figure out how to point Wallaby.js at my desired config file, which is named Wallaby.cjs and contains:

Your Wallaby configuration file must be in the root directory of your opened folder, then you should see it listed after you run the `Wallaby.js: Select Configuration` command.

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/2074089/189235269-fc8b63e7-ad40-4e5e-bd54-61ef0ec306b1.png">

If you're still having problems, can you please take a screenshot (or share details) of your opened folder and where the Wallaby configuration file is located?

> FWIW it works trivially with vitest.

Not sure how this is related? I assume this is on a separate project that doesn't require a configuration file?

**Comment by anicolao** [comment]
The actual bug was that my configuration file was named `Wallaby.cjs` instead of `wallaby.cjs` because I didn't realize that the case wasn't arbitrary (on MacOS the filesystem is normally case-insensitive).

After modifying the config like this it was almost working:
```
module.exports = function (wallaby) {
    return {
      files: [
        'src/**/*.ts',
        { pattern: 'src/**/*.unit.ts', ignore: true }
      ],

      tests: [
        'src/**/*.unit.ts'
      ],

      testFramework: 'mocha'
    };
  };
```

but I was hitting some strange error after that.

The `vitest` comment is a non-sequiter from the point of view of this bug, because I think Wallaby.js should look for both wallaby.cjs and Wallaby.cjs even on case-sensitive file systems, and definitely should find it on case-insensitive filesystems, so perhaps that needs fixing.

However for my specific case rather than fight with the tooling (because `@reduxjs/toolkit` doesn't import in the setup with `wallaby.cjs` but does in the auto-configured case, presumably because I don't have the correct ecmascript configuration in `wallaby.cjs`) I have just switched from mocha to vitest and am personally unblocked. Thanks for the prompt response on the issue.
