### ISSUE TITLE
Wallaby throwing errors for "before" and "beforeEach" hooks in Mocha test

### ISSUE THREAD

**Issue by charcharln** [wallabyjs/public#3072]
### "before is not defined"

Trying to run a simple mocha test inside VSCode with the Automatic Configuration (project directory). However, when reaching the "before" hooks, Wallaby throws out an error: "before is not defined"

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/78950093/189439387-6286afa6-64c2-4ce4-8550-84c03ecdc363.png">

Kind of related error when reaching the "beforeEach" hook: "Invalid first argument. It must be a callback function."

<img width="1138" alt="image" src="https://user-images.githubusercontent.com/78950093/189439664-ace9cf65-5bc5-4c98-a969-c493a56f0b16.png">

Running `npm test` will execute the test successfully.

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/78950093/189440408-026f01ff-66f1-4793-8bb0-aa9e1b6beb98.png">

Would appreciate any feedback if there's some configuration missing.

**Comment by smcenlly** [comment]
Wallaby does not support automatic configuration for `mocha` projects. You will need to create a configuration file.

In your case, if tests are running with automatic configuration then you must have `jest`, `angular`, or `vitest` available within your project, and Wallaby is running your project tests with one of those configurations.

If you provide us with your Wallaby Diagnostics report (details for generating are in the [new issue template](https://github.com/wallabyjs/public/issues/new/choose)), we can confirm for you.

If you are using mocha, you will need to create and use a configuration file. Here is a [sample mocha configuration](https://github.com/wallabyjs/wallaby-mocha-sinon-chai-nodejs/blob/master/wallaby.js) that uses `sinon`, `chai` and runs in `node`.

**Comment by charcharln** [comment]
Got it, and yes `jest` was running in that project.

Cloned the linked repo, and now it's working great, thanks for your help.

<img width="1998" alt="image" src="https://user-images.githubusercontent.com/78950093/189472116-5c747410-25eb-4643-872c-cc7f01022e32.png">
