### ISSUE TITLE
Can't figure out how to dump the automatic configuration

### ISSUE THREAD

**Issue by anicolao** [wallabyjs/public#3074]
### Issue description or question

I want to set some options on Wallaby, but haven't been able to write a valid config file. Auto configuration works fine with my `vitest` setup, and I imagined there would be a way to also add some options to it, but I can't figure out how to do it.

Ideally there would be some way to dump the configuration that the auto config makes, and then I could edit from there. Alternately, a configuration example that should work with vitest would be great.

**Comment by ArtemGovorov** [comment]
There's no need to dump auto-config values, you may just add/override the options you need with a simple config file (that will work in conjunction with auto-config): https://wallabyjs.com/docs/intro/config.html#overriding-automatic-defaults:

```
module.exports = () => ({
   autoDetect: true,
   ... // any of your options here
});
```

If the solution suggested above doesn't work for you, please share your Wallaby config file that doesn't work for you and we'll take it from there.

**Comment by anicolao** [comment]
The terrible thing is just before posting that issue I read and re-read that section of the docs, but didn't see the `autoDetect: true` key in the snippet (I actually missed that there was a snippet for wallaby.cjs at all, because it is under the much longer package.json snippet that I wasn't trying to use). Sorry about that, this does work for me.
