### ISSUE TITLE
Cannot use Vitest in Webstorm

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#3078]
### Issue description or question
Cannot use Vitest in Webstorm
Webstorm 2022.2.2
Wallaby core v1.0.1330
I get this message
```
We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: (node:471460) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Error extracting vitest configuration
Please contact Wallaby support and provide the contents of this file './node_modules/vitest/dist/chunk-vite-node-externalize.8d8032d0.mjs'
startVitest is not a function
```
### Wallaby diagnostics report
Report entry is grayed out in the menu.

Requested file content :
https://gist.github.com/vjau/743beacfd04bd76e0d59ff303059365d

**Comment by smcenlly** [comment]
Could you please let us know what version of `node` you are using?

**Comment by vjau** [comment]
Sure, it's node v14.20.0

**Comment by smcenlly** [comment]
To integrate with `vitest`, Wallaby needs to use `node` experimental ESM hooks. There was a breaking change introduced in node `16.12.0` that was not backported to node `14.x` which means that you will not be able to use Wallaby with vitest with your current version of node.

You will need to update your node version to fix your problem. We will also update Wallaby to check for the node version when running `vitest` for better error messages.

As an aside, node v14 active support finished on **19 Oct 2021** and security updates will no longer be applied after 30 Apr 2023.

**Comment by vjau** [comment]
I'm using Meteor, which doesn't support node 16 ATM.
IMHO, your documentation should mention that Node v14 is not supported.

**Comment by ArtemGovorov** [comment]
@vjau Thanks for your note, we have added the node version restriction to the docs: https://wallabyjs.com/docs/integration/vitest.html#article.
