### ISSUE TITLE
Can't seem to set limits high enough to debug

### ISSUE THREAD

**Issue by anicolao** [wallabyjs/public#3079]
### Issue description or question

In the debugger, I often hit cases where I want to advance into a test and the text of some source line in the past turns red and I am unable to. Though I couldn't find any documentation on the meaning of that highlight, it seems to be that the trace size has been exceeded.

However, if I set `maxTraceSteps: 8000000,` in my `wallaby.cjs` file, the console log for Wallaby shows:

```
​[Error] Error: invalid compressed data​​
​​[Error]     at InflateRaw.emit (node:events:513:28)​​
​​[Error]     at addChunk (node:internal/streams/readable:324:12)​​
​​[Error]     at readableAddChunk (node:internal/streams/readable:297:9)​​
​​[Error]     at Readable.push (node:internal/streams/readable:234:10)​​
​​[Error]     at Zlib.processCallback (node:zlib:566:10)​​
​​[Error] Some long running code has been detected: one of your tests is taking more than 5000ms to execute.​​
​​[Error] The last recorded console.log: Number of states = 441, pruned = 325​​
```

### Wallaby diagnostics report

```
{
  editorVersion: '1.71.2',
  pluginVersion: '1.0.347',
  editorType: 'VSCode',
  osVersion: 'darwin 21.6.0',
  nodeVersion: 'v18.7.0',
  coreVersion: '1.0.1331',
  checksum: 'MTYyNmVmYzk1ODJmMTFlNjRhZDcwNTBkYWU3NzMzODUsMTY2NDE1MDQwMDAwMCww',
  config: {
    maxConsoleMessagesPerTest: 100000,
    maxTraceSteps: 8000000,
    tests: [
      { pattern: 'tests/**/*.unit.ts', ignore: false, trigger: true, load: true, test: true, order: 2 },
      { pattern: 'tests/**/Solver.unit.ts', instrument: false, load: false, ignore: true, trigger: true, test: true, file: false },
      { pattern: 'tests/**/Pruner.unit.ts', instrument: false, load: false, ignore: true, trigger: true, test: true, file: false }
    ],
    diagnostics: {
      vitest: {
        file: {
          config: "import { sveltekit } from '@sveltejs/kit/vite';\n" +
            '\n' +
            "/** @type {import('vite').UserConfig} */\n" +
            'const config = {\n' +
            '\tplugins: [sveltekit()],\n' +
            "\tbuild: { target: 'es2020' },\n" +
            "\ttest: { include: ['tests/**/*.unit.ts'] }\n" +
            '};\n' +
            '\n' +
            'export default config;\n'
        },
        config: {
          allowOnly: true,
          watch: true,
          globals: false,
          environment: 'node',
          threads: true,
          clearMocks: false,
          restoreMocks: false,
          mockReset: false,
          include: [ 'tests/**/*.unit.ts' ],
          exclude: [ '**/node_modules/**', '**/dist/**', '**/cypress/**', '**/.{idea,git,cache,output,temp}/**' ],
          testTimeout: 5000,
          hookTimeout: 10000,
          teardownTimeout: 1000,
          isolate: true,
          watchExclude: [ '**/node_modules/**', '**/dist/**' ],
          forceRerunTriggers: [ '**/package.json/**', '**/vitest.config.*/**', '**/vite.config.*/**' ],
          update: false,
          reporters: [ 'default' ],
          silent: false,
          ui: false,
          uiBase: '/__vitest__/',
          open: true,
          css: { include: [], modules: { classNameStrategy: 'stable' } },
          coverage: {
            provider: 'c8',
            enabled: false,
            clean: true,
            cleanOnRerun: false,
            reportsDirectory: './coverage',
            excludeNodeModules: true,
            exclude: [
              'coverage/**',
              'dist/**',
              'packages/*/test{,s}/**',
              '**/*.d.ts',
              'cypress/**',
              'test{,s}/**',
              'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
              '**/*{.,-}spec.{js,cjs,mjs,ts,tsx,jsx}',
              '**/__tests__/**',
              '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress}.config.{js,cjs,mjs,ts}',
              '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}'
            ],
            reporter: [ 'text', 'html', 'clover', 'json' ],
            allowExternal: false,
            extension: [
              '.js',  '.cjs',
              '.mjs', '.ts',
              '.tsx', '.jsx',
              '.vue', '.svelte'
            ]
          },
          fakeTimers: { loopLimit: 10000, shouldClearNativeTimers: true, toFake: [ 'setTimeout', 'clearTimeout', 'setInterval', 'clearInterval', 'setImmediate', 'clearImmediate', 'Date' ] },
          maxConcurrency: 5,
          dangerouslyIgnoreUnhandledErrors: false,
          defines: {},
          root: '<homeDir>/projects/rubik/blueroux',
          mode: [],
          deps: {
            inline: [
              {},                  {},
              {},                  {},
              {},                  {},
              '@nuxt/test-utils',  'svelte',
              {},                  '@smui/drawer',
              '@smui/common',      'svelte2tsx',
              '@smui/icon-button', '@smui/ripple',
              '@smui/list',        '@smui/top-app-bar',
              '@smui/button',      '@smui/card'
            ],
            registerNodeLoader: false
          },
          snapshotOptions: { snapshotFormat: {}, updateSnapshot: 'new' },
          setupFiles: [],
          cache: { dir: '<homeDir>/projects/rubik/blueroux/node_modules/.vitest' },
          sequence: {},
          package: {
            version: '0.23.1',
            urls: { hooks: 'file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.347/wallabyb2727f/runners/node/hooks.mjs' },
            paths: { root: '<homeDir>/projects/rubik/blueroux/node_modules/vitest', dist: '<homeDir>/projects/rubik/blueroux/node_modules/vitest/dist' }
          }
        }
      }
    },
    testFramework: { version: 'vitest@0.14.0', configurator: 'vitest@0.14.0', reporter: 'vitest@0.14.0', starter: 'vitest@0.14.0', autoDetected: true },
    preserveComments: false,
    extractComments: true,
    files: [
      { pattern: 'tests/**/*.unit.ts', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/node_modules/**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/dist/**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/cypress/**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/.{idea,git,cache,output,temp}/**', ignore: true, trigger: true, load: true, file: true },
      { pattern: '**/*.*', ignore: false, trigger: true, load: true, order: 1 }
    ],
    workers: { initial: 1, regular: 1, recycle: false },
    filesWithNoCoverageCalculated: [],
    runAllTestsInAffectedTestFile: false,
    updateNoMoreThanOneSnapshotPerTestFileRun: false,
    compilers: {},
    logLimits: { inline: { depth: 5, elements: 5000 }, values: { default: { stringLength: 200 }, autoExpand: { elements: 5000, stringLength: 8192, depth: 10 } } },
    preprocessors: {},
    autoConsoleLog: true,
    delays: { run: 0, edit: 100, update: 0 },
    teardown: undefined,
    hints: {
      ignoreCoverage: '__REGEXP /ignore coverage|istanbul ignore/',
      ignoreCoverageForFile: '__REGEXP /ignore file coverage/',
      commentAutoLog: '?',
      testFileSelection: { include: '__REGEXP /file\\.only/', exclude: '__REGEXP /file\\.skip/' }
    },
    automaticTestFileSelection: true,
    runSelectedTestsOnly: false,
    mapConsoleMessagesStackTrace: false,
    extensions: {},
    env: {
      type: 'node',
      params: { runner: '--experimental-loader=file://<homeDir>/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.347/wallabyb2727f/runners/node/hooks.mjs' },
      runner: '/opt/homebrew/Cellar/node/18.7.0/bin/node',
      viewportSize: { width: 800, height: 600 },
      options: { width: 800, height: 600 },
      bundle: true
    },
    reportUnhandledPromises: true,
    slowTestThreshold: 75,
    lowCoverageThreshold: 80,
    loose: undefined,
    symlinkNodeModules: true,
    configCode: 'module.exports = function (wallaby) {\n' +
      '\treturn {\n' +
      '\t\tautoDetect: true,\n' +
      '\t\tmaxConsoleMessagesPerTest: 100000,\n' +
      '\t\tmaxTraceSteps: 8000000,\n' +
      '\t\ttests: [\n' +
      "\t\t\t'tests/**/*.unit.ts',\n" +
      "\t\t\t{ pattern: 'tests/**/Solver.unit.ts', instrument: false, load: false, ignore: true },\n" +
      "\t\t\t{ pattern: 'tests/**/Pruner.unit.ts', instrument: false, load: false, ignore: true }\n" +
      '\t\t]\n' +
      '\t};\n' +
      '};\n'
  },
  packageJSON: {
    dependencies: {
      '@reduxjs/toolkit': '^1.8.5',
      '@smui/drawer': '^6.1.0',
      '@smui/icon-button': '^6.1.0',
      '@smui/list': '^6.1.0',
      '@smui/top-app-bar': '^6.1.0',
      '@web/test-runner-playwright': '^0.8.10',
      cubing: '^0.29.1',
      'd3-scale': '^4.0.2',
      firebase: '^9.9.3',
      three: '^0.144.0'
    },
    devDependencies: {
      '@esm-bundle/chai': '^4.3.4-fix.0',
      '@playwright/test': '^1.25.0',
      '@smui/button': '^6.1.0',
      '@smui/card': '^6.1.0',
      '@sveltejs/adapter-auto': 'next',
      '@sveltejs/adapter-static': '^1.0.0-next.39',
      '@sveltejs/kit': 'next',
      '@types/chai': '^4.3.3',
      '@types/d3-scale': '^4.0.2',
      '@types/mocha': '^9.1.1',
      '@typescript-eslint/eslint-plugin': '^5.27.0',
      '@typescript-eslint/parser': '^5.27.0',
      '@vitest/coverage-c8': '^0.23.1',
      '@web/dev-server-esbuild': '^0.3.2',
      autoprefixer: '^10.4.7',
      chai: '^4.3.6',
      eslint: '^8.16.0',
      'eslint-config-prettier': '^8.3.0',
      'eslint-plugin-svelte3': '^4.0.0',
      postcss: '^8.4.14',
      'postcss-load-config': '^4.0.1',
      prettier: '^2.6.2',
      'prettier-plugin-svelte': '^2.7.0',
      'smui-theme': '^6.1.3',
      svelte: '^3.44.0',
      'svelte-check': '^2.7.1',
      'svelte-preprocess': '^4.10.7',
      'ts-node': '^10.9.1',
      tslib: '^2.3.1',
      typescript: '^4.7.4',
      vite: '^3.0.4',
      vitest: '^0.23.1'
    }
  },
  fs: { numberOfFiles: 146 },
  debug: []
}
```

**Comment by smcenlly** [comment]
Sometimes you may select a navigation option that is unavailable (e.g. a Step Into/out of request when on the last execution step). When unable to navgiate, the code selected by the debugger will change to a red color.

Depending on how your code is structured, you may especially see this with asynchronous code when there is no clear return to a previous function.

In order to tell you whether this is expected behavior or not, we'd need to see your code (or a sample of code that has the same problem). Are you able to provide that to us? We would need to see all the different parts of it's end-to-end execution to understand how it's called and what is happening at runtime. Perhaps creating a sample repo with the same issue would be best?

**Comment by anicolao** [comment]
If it's not too much work for you, it'd be easiest for me to have you repro on the full repository for this test. 
```
git clone git@github.com:anicolao/blueroux.git
git checkout -b bluetooth
npm install
```
Then open `optimizer.unit.ts` and try to debug and step through any test. I believe all of these tests fail to step. For example, the test `it('can find shorter first block', () => {` fails on line 20, which reads `   const optimized = makeOptimizedData(scramble, solutionArray);` and requires only 5 step over actions to see the failure.

**Comment by anicolao** [comment]
<img width="848" alt="Screen Shot 2022-09-22 at 9 27 40 PM" src="https://user-images.githubusercontent.com/1145048/191877217-3068a5aa-4a5b-4e3b-a6e4-b2c2ccbf2fac.png">

Above is a screenshot of what this example looks like for me when it fails. It's a bit different than other cases I've seen, in that this only highlights the first character of each line as you step unlike normal where it highlights blocks within the line, and then fails with just a single character highlighted in red. In other cases, entire lines are highlighted red.

**Comment by anicolao** [comment]
Shortly after reproducing that, I got a JS heap OOM:
```
​[Error] <--- Last few GCs --->​​
​​[Error] [30118:0x150028000] 39135711 ms: Scavenge (reduce) 4078.4 (4142.9) -> 4078.5 (4143.9) MB, 8.9 / 0.0 ms  (average mu = 0.818, current mu = 0.017) allocation failure; ​​
​​[Error] [30118:0x150028000] 39138725 ms: Mark-sweep (reduce) 4079.4 (4143.9) -> 4079.2 (4144.7) MB, 3012.3 / 0.0 ms  (average mu = 0.666, current mu = 0.004) allocation failure; scavenge might not succeed​​
​​[Error] <--- JS stacktrace --->​​
​​[Error] FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory​​
​​[Error]  1: 0x101016dd4 node::Abort() [/opt/homebrew/Cellar/node/18.7.0/bin/node]​​
​​[Error]  2: 0x101017e34 node::OnFatalError(char const*, char const*) [/opt/homebrew/Cellar/node/18.7.0/bin/node]
```
Is there some easy way to give node more RAM? Perhaps that would help/is related.

**Comment by anicolao** [comment]
As near as I can tell, I need to pass something like `--max-old-space-size=SIZE` to `node` where SIZE > 4 gigabytes in order to increase the heap from what v8 is currently using. However I don't know who starts Wallaby's instance of node and can't find any wallaby option to pass through args to node. It does look like I could use the 'path to node' option to tell Wallaby that node is a script instead of the real thing, and then write a trivial bash script to set the RAM size. Will that work as I expect it to?

**Comment by anicolao** [comment]
I verified that pointing Wallaby at the script does use it and respect the `--max-old-space-size` parameter by setting it small (128M) and seeing wallaby run out of RAM in the console. Setting it large (8G) does not fix the problem I'm having stepping through this file's tests.

Also, the single red highlight as opposed to the highlight of the right piece of the line being executed seems to be related to an error mapping the source:
```
​​[Error] Failed to calculate original ranges for tests/optimizer.unit.ts: Unexpected token (8:12)​​
```
which in the case of my repository points at a line that is just a normal type import:
```
import type { AnalyzerState, SolutionDesc } from '$lib/third_party/onionhoney/Analyzer';
```
the 12th character of which is the `{`.

**Comment by anicolao** [comment]
Turning on `trace` did not provide any helpful clues
```
]
​[Info]​ 2022-09-23T04:44:15.737Z nodeRunner Prepared sandbox [worker #0, session #xm2qx]
​[Info]​ 2022-09-23T04:44:15.737Z workers [worker #0, session #xm2qx] Running tests in sandbox
​[Info]​ 2022-09-23T04:44:15.741Z workers Scheduling Vitest Run (xm2qx): 2022-09-23T04:44:15.740Z
​[Info]​ 2022-09-23T04:44:15.953Z workers [xm2qx.1] Loaded unknown number of test(s)
​[Info]​ 2022-09-23T04:44:22.038Z workers [xm2qx.1] Test executed: can find shorter first block
​[Info]​ 2022-09-23T04:44:22.784Z fs File changed: node_modules/.vitest/results.json
​[Info]​ 2022-09-23T04:44:22.784Z fs No metadata for changed file found: node_modules/.vitest/results.json
​[Info]​ 2022-09-23T04:44:24.312Z workers Vitest Run Complete (xm2qx): 2022-09-23T04:44:22.242Z
​[Info]​ 2022-09-23T04:44:24.313Z workers [xm2qx] Run 1 test(s), skipped 0 test(s)
​[Info]​ 2022-09-23T04:44:24.314Z workers [xm2qx] Sandbox is responsive, closing it
​[Info]​ Finished executing 1 affected test(s) in 8.58 second(s)
​[Info]​ 2022-09-23T04:44:24.315Z project Test run finished
​[Info]​ 2022-09-23T04:44:24.315Z project Processed console.log entries
​[Info]​ 2022-09-23T04:44:24.315Z project Processed loading sequences
​[Info]​ 2022-09-23T04:44:24.315Z project Processed executed tests
​[Info]​ 2022-09-23T04:44:24.317Z project Processed code coverage
​[Info]​ 2022-09-23T04:44:24.643Z project Processed code trace
​​[Error] Failed to calculate original ranges for tests/optimizer.unit.ts: Unexpected token (8:12)​​
​[Info]​ 2022-09-23T04:44:24.704Z project Test run result processed and sent to ID
```

It looks to me like `Processed code trace` implies that the trace from clicking debug was successful and I should be able to navigate using the time travel debugger to debug.

**Comment by anicolao** [comment]
I'm going to give up trying to use the debugger for now. Some clues on how to troubleshoot would be greatly appreciated.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo to reproduce the issues.

> this only highlights the first character of each line as you step unlike normal where it highlights blocks within the line

The issue has been fixed and the fix is published in [the latest core v1.0.1332](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)

> Then open optimizer.unit.ts and try to debug and step through any test. I believe all of these tests fail to step. 

We have tried and some of your code is definitely making >4M steps (when you hit a red indicator, you can `Step Into` to find out what code is it). You can also see the current step (and the total number or recorded steps) in the Wallaby Debugger side panel (you'll need to also update your Wallaby VS Code extension to latest if the panel doesn't show up when you click on Wallaby indicator in the side VS Code toolbar):

![dbg](https://user-images.githubusercontent.com/979966/192191736-0cc313cf-dcdd-4d56-a42c-a05d3584e709.gif)


As you can see from the GIF, in the `Pruner.ts` loop `for (let i = 0; i < max_depth; i++)` (likely deeper in its dependencies) the max number of recorded steps is exceeded. So the red indicator is expected.

> As near as I can tell, I need to pass something like --max-old-space-size=SIZE to node where SIZE > 4 gigabytes in order to increase the heap from what v8 is currently using.

You can pass it via adding the following setting in your VS Code wallaby settings: https://github.com/wallabyjs/public/issues/2619#issue-800819387. Having said that, even after increasing the number of steps that your code is making may be too large for node/wallaby to record and node process may still run out of memory. 

A better option may be to reduce the number of recorded steps by excluding tight loops that produce thousands of repetitive recorded steps (that are likely useless for the debugging purposes anyway). To do it, you may exclude certain code blocks, functions or even files from code coverage calculation as described here: https://wallabyjs.com/docs/config/coverage.html. 

For example, after adding `/* ignore file coverage */` code comment to the `src/lib/third_party/onionhoney/Pruner.ts` and `src/lib/third_party/onionhoney/CubeLib.ts` files to exclude them from the coverage/steps recording, debugger for optimiser tests starts recording only about 0.5M of steps (and seems much faster to start):

![dbg1](https://user-images.githubusercontent.com/979966/192191450-e2ba3f4d-19fc-4076-99f1-a301d0fa422f.gif)

I'd suggest excluding even more files/functions as even 0.5M of steps seems impossible to fully navigate, so may be wasteful to record for the debugging purposes. If excluding whole files from the coverage calculation is not desirable, you may exclude certain functions, or even code blocks in tight loops via `/* ignore coverage */` code comment to make the number of recorded steps manageable.

**Comment by anicolao** [comment]
I'll play with cutting down the number of steps and that'll most likely resolve the specific situations I am trying to debug at the moment.

Suppose however that I actually wanted to record a large trace, say 12 million or 40 million steps: is there an intrinsic limit beyond space and time, or should it be possible to set the limits up and have it work? I have not been able to find any way to get the system to work with limits greater than 4M, even with node heap size increased.

**Comment by smcenlly** [comment]
There's no intrinsic limit. When we released the debugger, we did some performance testing and for 1M steps, the memory usage was ~100MB. This may vary based on your project.

As @ArtemGovorov suggested, trying to debug a session with even 1/2 million steps may not productive.

**Comment by anicolao** [comment]
When I try to disable coverage on `Solver.ts`, I get the rather confusing message:

```
TypeError: Cannot create property 'CONTINUE' on number '1'
 
at​ src/lib/third_party/onionhoney/Solver.ts:59 ​
 
	enum SState {
		CONTINUE,
		STOP
```

I'm not even sure what to start looking at to fix it -- suggestions?

**Comment by smcenlly** [comment]
We're using the latest version of the `bluetooth` branch and it includes the `ignore file coverage` comment at the top of the file and everything is working for us. 

<img width="623" alt="image" src="https://user-images.githubusercontent.com/2074089/193482739-606d0868-c962-417d-a567-8046262bced3.png">

Did you get this working or are you still having problems? If it's not working for you, can you please try cloning to a fresh directory and see if it works there?

**Comment by anicolao** [comment]
I applied a workaround where I moved the enum containing CONTINUE and STOP to global scope and that made it "work". However it seems certain that this is really a but in wallaby or one of its dependencies. If you git blame the file you can see the edit and undo it to reproduce the issue.

**Comment by smcenlly** [comment]
Thanks - we have found and fixed the problem in Wallaby. Please update to Wallaby core `v1.0.1333`, it will fix your problem.
