### ISSUE TITLE
Windows 11: Error while unzipping wallaby.js core file: could not verify core version

### ISSUE THREAD

**Issue by zstundys** [wallabyjs/public#3085]
### Issue description or question

Did a clean Windows 11 install -- installed Node 18 -- installed a stable VS Code version 1.71.2 -- installed wallaby. Getting the following error on "Force core update" command:

```
[2022-09-28 22:35:19.886] [renderer1] [error] [Extension Host] Error: Error while unzipping wallaby.js core file: could not verify core version
	at m.<anonymous> (c:\Users\zstun\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\dist\index.js:15:13188)
	at Generator.throw (<anonymous>)
	at r (c:\Users\zstun\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\dist\index.js:15:647)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I only can assume this affects Windows 11, because I haven't got this error on any other machines I'm using (Ubuntu/MacOS). Closest related issue I've found is https://github.com/wallabyjs/public/issues/2773 -- but I'm not behind any proxy.
  
### Wallaby diagnostics report

Cannot attach any since the core files can't be installed due to this bug

**Comment by smcenlly** [comment]
> Closest related issue I've found is https://github.com/wallabyjs/public/issues/2773 -- but I'm not behind any proxy.

Your issue is almost certainly related to either:
1. Network traffic being filtered somewhere in transmission (e.g. external router / firewall rules), or
2. Your virus scanner intercepting/changing the content of Wallaby.

Can you please try disabling your Virus Scanner to see if that fixes your problem?

If possible, please also try connecting to another network (e.g. hotspot on your phone) as that may also fix the problem.

---

If you're still having problems after trying that, you may follow our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html) instead of using our automated update mechanism.

**Comment by smcenlly** [comment]
Did you follow the offline installation instructions? Did that work for you?

Can you also please check whether there is any error logged to your VS Code Developer tools console after receiving the error:

1. Run the VS Code `Developer: Toggle Developer Tools`
2. Select the `Console` tab and look any errors/messages

**Comment by zstundys** [comment]
I tried the offline installation -- no luck. This is as far as I've got (deadlocks with "Wallaby.js is updating and will be started automatically when the update is complete." notification)

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/40335772/193407392-ca7018e1-5090-4f7b-9ddb-306215f62acd.png">
<img width="858" alt="image" src="https://user-images.githubusercontent.com/40335772/193407419-006a4d03-9249-452c-912a-f7993b99717f.png">
<img width="870" alt="image" src="https://user-images.githubusercontent.com/40335772/193407430-5482e4c5-792e-461a-a35c-f713c32579fc.png">

**Comment by zstundys** [comment]
I got a feeling that the [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html) are outdated. At the time of writing the latest vscode version is 1.0.348 -- but the https://update.wallabyjs.com/wallaby.json returns 1.0.1332.

Somethings off

**Comment by smcenlly** [comment]
The offline installation instructions are not out of date. If you follow them exactly, it should work for you.

Wallaby has two separated versioned components:

1. Extension version (for VS Code, this is `1.0.348`), and
2. Server version (this is Wallaby's core runtime), which is referred to in the docs as latestServer, currently version `1.0.1332`.

The `LATEST` part of the folder name should be replaced with your VS Code extension version. So what you need to do is copy the `wallaby` and `wallaby-app` folders into the `wallabyjs.wallaby-vscode-1.0.348` folder and it should work for you.

**Comment by smcenlly** [comment]
Assuming that our latest comment has helped you fix the problem. If you're still having issues, please let us know.
