### ISSUE TITLE
Having trouble getting wallaby to accept another OSS Project

### ISSUE THREAD

**Issue by anicolao** [wallabyjs/public#3087]
Similar to last time, my project at 
```
$ git remote -v
origin  git@github.com:anicolao/words.git (fetch)
origin  git@github.com:anicolao/words.git (push)
```
isn't recognized as OSS by Wallaby.js. When we solved it last time, it was because the repository pointed at a private TODO repository. In this example, the repository has never pointed at a non-OSS repository (it pointed at blueroux briefly) so I am not sure how to get a more informative error out of wallaby than the message 'the open source status of your project could not be verified'.

Thanks

**Comment by smcenlly** [comment]
Wallaby performs various checks as a part of ensuring that your project is a valid, public, open source repository.

Unfortunately we cannot provide the specific reasons for checks failing without providing a means of bypassing part of our licensing mechanism.

In your case, it would appear that your `package.json` is sufficiently different from your repo and that is why your repo is not being recognised. Could you please provide us with your `package.json` and we will be able to check it for you against your public repo?

**Comment by anicolao** [comment]
I rewrote the history on the new project and got it working, thanks!
