### ISSUE TITLE
Morgan / Wallaby

### ISSUE THREAD

**Issue by scriptsure** [wallabyjs/public#3088]
Using morgan and was looking to have the output of morgan hit the testing console / tests output. Is that possible?

Do i have to setup a winston console transport in my wallaby config to get this to work?

**Comment by smcenlly** [comment]
Wallaby will capture any `console.log` statements that occur when executing your code. So if you can have `morgan` / `winston` use `console.log`, then you should see those `console.log` statements with Wallaby output.

By default, Wallaby will not show `console.log` statements in the test output window unless the test is failing. You can always see `console.log` statements in Wallaby App (at any time) and you can view the `console.log` statements for your any covered line in the editor using the `Show Line Tests` command.
