### ISSUE TITLE
vitest 024.0

### ISSUE THREAD

**Issue by matchatype** [wallabyjs/public#3089]
### Issue description or question

Wallaby worked well with vitest up to v0.23.4, but doesn't work with v0.24.0, which introduces a breaking change: *Drop support for Vite 2*.

### From Wallaby console error:

```
Automatic Jest configuration error: Module jest-cli is not found in '.'.

We've also tried to automatically configure Wallaby.js for other frameworks
Automatic Vitest configuration error: (node:29857) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
File '/chunk-vite-node-externalize\..*\.mjs/' is not found in './node_modules/vitest/dist'
```

**Comment by smcenlly** [comment]
Wallaby now supports the latest version of `vitest`. Please update to Wallaby core `v1.0.1334` to fix the problem.

The breaking change to our integration was that the vitest file extensions changed from `.mjs` to `.js`.
