### ISSUE TITLE
Display issue with webstorm line height > 1

### ISSUE THREAD

**Issue by ludydoo** [wallabyjs/public#309]
Hi, 

Please see attached image.

This is a minor issue, but it would be easier to read if the wallaby icons would be aligned to the bottom of the line

![sans titre](https://cloud.githubusercontent.com/assets/38968/10758055/3f390864-7c85-11e5-9df4-174a14b9576b.jpg)

**Comment by smcenlly** [comment]
This is no longer a problem with the latest version of Wallaby and the latest version of WebStorm.
