### ISSUE TITLE
Mocking while using Quokka

### ISSUE THREAD

**Issue by tnek213** [wallabyjs/public#3095]
Hi!

I've bought both Quokka and Wallaby, but I haven't really gotten started with Wallaby yet.

Is there a nice way to mock imports when using Quokka on a TypeScript project which will run in Node?

I like the playfulness and REPL-like experience of using Quokka and would like to use it while developing some "real" projects. And for real projects (and not just a scratchpad) the files will have imports. Maybe not always, but sometimes I'd like to mock the imports.

What would be the best way to do that? (Maybe I shouldn't use Quokka, but go for Wallaby?)

**Comment by smcenlly** [comment]
Quokka doesn't provide a first class ability to mock imports, that is certainly a feature provided by many testing frameworks, and depending on how you define your mocks, sometimes additional code transformation mechanisms are required to "hoist" your mock definition to the top of the code before any imports run.

If you are using Quokka, you really have two options available to you:

1. Copy/paste the code you want Quokka to run and define variable(s) in place of the imports you want to mock with dummy behavior.
2. Edit your codde file to do the same - define variable(s) in place of the imports you want to mock with dummy behaviour.

If you are using Wallaby with a testing framework that supports mocking imports, you don't need to do anything special, but your code will be running in the context of a test in this case.
