### ISSUE TITLE
Sandbox load failed, status: failed: Chrome is not running

### ISSUE THREAD

**Issue by NaoRojas** [wallabyjs/public#3098]

**Comment by smcenlly** [comment]
Your issue may be related to a previous issue we encountered where Wallaby won't launch Chrome properly if Chrome is not launched already. https://github.com/wallabyjs/public/issues/2148

Can you please try rebooting your machine, and immediately after reboot, launch Chrome.

After you've done that, please open VS Code and start Wallaby.

If you're still having a problem after trying that, please let us know.

**Comment by smcenlly** [comment]
Assuming our suggestion fixed your problem and closing this issue. If you're still experiencing problems, please comment/reply and we will re-open.
