### ISSUE TITLE
Automatic Angular CLI configuration error: Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by HimanshuGoel** [wallabyjs/public#3115]
### Issue description or question

After upgrading the project from Angular 14 to Angular 15, Wallaby started giving an error as below. The same error is also happening even if we create a brand new Angular 15 project from Angular CLI.

```shell
‌[Error] Automatic Angular CLI configuration error: Cannot read properties of undefined (reading 'version') 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
```

I tried to enable the `trace` option as `true`, but it looks like it is trying to access the `version` property on this line -

```typescript
//File path -  \node_modules\@angular\cli\src\analytics
const packageManagerVersion = context.packageManager.version;
```

Once I try to fix the above line by putting `?` before `version` property, it breaks on the below line for `name` property -

```typescript
//File path -  \node_modules\@angular\cli\src\analytics
[analytics_parameters_1.UserCustomDimension.PackageManager]: context.packageManager.name,
```

### Wallaby diagnostics report

‍​[Info]​ 2022-12-01T07:00:44.306Z config Attempting automatic configuration for angular
​[Info]​ 2022-12-01T07:00:44.308Z angular/cli config Detecting Angular CLI.
​[Info]​ Started Wallaby.js Core v1.0.1349
​[Info]​ 2022-12-01T07:00:44.315Z angular/cli config Detected Angular CLI.
​[Info]​ 2022-12-01T07:00:44.321Z angular/cli config Angular currentDirPath: "C:\Users\username\personal\code\templates\angular15-seed", workspaceDirPath: "C:\Users\username\personal\code\templates\angular15-seed"
​[Info]​ 2022-12-01T07:00:44.345Z angular/cli karma project config Configuring.
​[Info]​ 2022-12-01T07:00:48.942Z extended-core Setting preferences
​[Info]​ 2022-12-01T07:00:48.960Z angular/cli karma project config Calling test command for angular15-seed.
​[Info]​ 2022-12-01T07:00:49.488Z angular/cli config TypeError: Cannot read properties of undefined (reading 'version')
​[Info]​     at new AnalyticsCollector (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\analytics\analytics-collector.js:65:62)
​[Info]​     at TestCommandModule.getAnalytics (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\command-module.js:140:25)
​[Info]​     at async TestCommandModule.runSingleTarget (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js:44:15)
​[Info]​     at async TestCommandModule.run (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\architect-command-module.js:73:20)
​[Info]​ 2022-12-01T07:00:49.505Z angular/cli config Angular.json: 
​[Info]​  {
​[Info]​   '$schema': './node_modules/@angular/cli/lib/config/schema.json',
​[Info]​   version: 1,
​[Info]​   newProjectRoot: 'projects',
​[Info]​   projects: {
​[Info]​     'angular15-seed': {
​[Info]​       projectType: 'application',
​[Info]​       schematics: { '@schematics/angular:component': { style: 'scss' } },
​[Info]​       root: '',
​[Info]​       sourceRoot: 'src',
​[Info]​       prefix: 'app',
​[Info]​       architect: {
​[Info]​         build: {
​[Info]​           builder: '@angular-devkit/build-angular:browser',
​[Info]​           options: {
​[Info]​             outputPath: 'dist/angular15-seed',
​[Info]​             index: 'src/index.html',
​[Info]​             main: 'src/main.ts',
​[Info]​             polyfills: [ 'zone.js' ],
​[Info]​             tsConfig: 'tsconfig.app.json',
​[Info]​             inlineStyleLanguage: 'scss',
​[Info]​             assets: [ 'src/favicon.ico', 'src/assets' ],
​[Info]​             styles: [ 'src/styles.scss' ],
​[Info]​             scripts: []
​[Info]​           },
​[Info]​           configurations: {
​[Info]​             production: { budgets: [ { type: 'initial', maximumWarning: '500kb', maximumError: '1mb' }, { type: 'anyComponentStyle', maximumWarning: '2kb', maximumError: '4kb' } ], outputHashing: 'all' },
​[Info]​             development: { buildOptimizer: false, optimization: false, vendorChunk: true, extractLicenses: false, sourceMap: true, namedChunks: true }
​[Info]​           },
​[Info]​           defaultConfiguration: 'production'
​[Info]​         },
​[Info]​         serve: {
​[Info]​           builder: '@angular-devkit/build-angular:dev-server',
​[Info]​           configurations: { production: { browserTarget: 'angular15-seed:build:production' }, development: { browserTarget: 'angular15-seed:build:development' } },
​[Info]​           defaultConfiguration: 'development'
​[Info]​         },
​[Info]​         'extract-i18n': { builder: '@angular-devkit/build-angular:extract-i18n', options: { browserTarget: 'angular15-seed:build' } },
​[Info]​         test: {
​[Info]​           builder: '@angular-devkit/build-angular:karma',
​[Info]​           options: {
​[Info]​             main: 'src/test.ts',
​[Info]​             polyfills: [ 'zone.js', 'zone.js/testing' ],
​[Info]​             tsConfig: 'tsconfig.spec.json',
​[Info]​             inlineStyleLanguage: 'scss',
​[Info]​             assets: [ 'src/favicon.ico', 'src/assets' ],
​[Info]​             styles: [ 'src/styles.scss' ],
​[Info]​             scripts: []
​[Info]​           }
​[Info]​         }
​[Info]​       }
​[Info]​     }
​[Info]​   }
​[Info]​ }
​[Info]​ 2022-12-01T07:00:49.506Z angular/cli config TypeError: Cannot read properties of undefined (reading 'version')
​[Info]​     at new AnalyticsCollector (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\analytics\analytics-collector.js:65:62)
​[Info]​     at TestCommandModule.getAnalytics (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\command-module.js:140:25)
​[Info]​     at async TestCommandModule.runSingleTarget (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\architect-base-command-module.js:44:15)
​[Info]​     at async TestCommandModule.run (C:\Users\username\personal\code\templates\angular15-seed\node_modules\@angular\cli\src\command-builder\architect-command-module.js:73:20)
​[Info]​ 2022-12-01T07:00:49.506Z config Finished attempting automatic configuration for angular (5200ms)
​[Info]​ 2022-12-01T07:00:49.507Z config Attempting automatic configuration for jest
​[Info]​ 2022-12-01T07:00:49.513Z jest/config Detecting Jest.
​[Info]​ 2022-12-01T07:00:49.528Z jest/config Error: Module jest-cli is not found in 'C:\Users\username\personal\code\templates\angular15-seed'.
​[Info]​     at Object.<anonymous> (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:24913)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:8061)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:7356)
​[Info]​     at c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:7265
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at s (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:7059)
​[Info]​     at Object.loadJest (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:31:22511)
​[Info]​     at c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:22306
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:27039)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26334)
​[Info]​     at c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26243
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at s (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26037)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:21994)
​[Info]​     at Object.<anonymous> (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:25714)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:27039)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26334)
​[Info]​     at c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26243
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at s (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:26037)
​[Info]​     at Object.n [as configure] (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:25595)
​[Info]​     at Config.<anonymous> (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:20840)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:12061)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:11356)
​[Info]​     at o (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:11105)
​[Info]​ 2022-12-01T07:00:49.529Z config Finished attempting automatic configuration for jest (22ms)
​[Info]​ 2022-12-01T07:00:49.529Z config Attempting automatic configuration for vitest
​[Info]​ 2022-12-01T07:00:49.532Z vitest/config Detecting Vitest.
​[Info]​ 2022-12-01T07:00:49.537Z vitest/config Error: Vitest dependency not found.
​[Info]​     at Object.<anonymous> (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:28946)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:20:167)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:31487)
​[Info]​     at c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:31396
​[Info]​     at new Promise (<anonymous>)
​[Info]​     at n (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:31190)
​[Info]​     at Object.r [as configure] (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:19:28330)
​[Info]​     at Config.<anonymous> (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:20840)
​[Info]​     at r (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:12061)
​[Info]​     at Object.next (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:11356)
​[Info]​     at o (c:\Users\username\.vscode\extensions\wallabyjs.wallaby-vscode-1.0.348\wallaby41f09c\server.js:15:11105)
​[Info]​ 2022-12-01T07:00:49.538Z config Finished attempting automatic configuration for vitest (9ms)
​​[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Cannot read properties of undefined (reading 'version')
​​
​​[Error] 
​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks
​​
​​[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.
​​
​​[Error] Automatic Vitest configuration error: Vitest dependency not found.​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
​[Info]​ - Generating browser application bundles (phase: setup)...

**Comment by NikGovorov** [comment]
Does `ng test` work on the project?

**Comment by NikGovorov** [comment]
As a temporary fix you may execute the following command in your Angular CLI workspace:

`ng analytics disable`

which should fix the issue.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
