### ISSUE TITLE
atom-wallaby: Proxy settings

### ISSUE THREAD

**Issue by kutyel** [wallabyjs/public#312]
The complete error is:

```
Error while downloading wallaby.js version file:
connect ETIMEDOUT 104.44.128.13:80
```

As shown in the image:

![image](https://cloud.githubusercontent.com/assets/5127501/10815978/c149255e-7e2f-11e5-88bc-367d81dc98f1.png)

This causes wallaby to fail and doesn't allow you to do anything with the plugin, even the *keybindings* for the package do not appear.

I'm almost sure it's caused by our **corporate proxy**, any fix on this?

**Comment by ArtemGovorov** [comment]
I can't think of any workaround for this unfortunately. Wallaby needs quite a few things to download when it installs, then periodic updates. I suspect many other Atom plugins that need something from outside (including Atom updates itself) are suffering the same issue within your company network.

**Comment by ArtemGovorov** [comment]
Actually, there's one thing you could try. 

Wallaby uses `request` module to download stuff and [its docs says it respects proxy settings in environment variables](https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables).

So you may change your Atom Init Script (`Atom - Open Your Init Script`) and add
```CoffeeScript
process.env.http_proxy = 'http://yourproxy.com'
process.env.https_proxy = 'http://yourproxy.com'
```

**Comment by kutyel** [comment]
Apparently it worked, but now this message appears:

![image](https://cloud.githubusercontent.com/assets/5127501/10817570/147ef734-7e3b-11e5-85cd-616068db3f69.png)

And when I close it, it does nothing, you have to force it to use the trial license? I don't have any license yet :sob:

**Comment by ArtemGovorov** [comment]
You may find the [extended trial license key in this newsletter](http://us10.campaign-archive2.com/?u=9f4d1fcb266805fa22aec0b1f&id=1920f12ffb).

**Comment by Janatbek** [comment]
My IT department granted temporary access to that ip. but now I cannot install either. where I have to setup proxy in visual studio code?
