### ISSUE TITLE
Wallaby incompatible with vitest >= 0.25.5

### ISSUE THREAD

**Issue by matchatype** [wallabyjs/public#3122]
Wallaby seems to be broken (IntelliJ version) with vitest starting from v0.25.5.

```
Failed to initialize wallaby vitest.
Could not find vitest utils.
Error: Could not find vitest utils.
```

**Comment by smcenlly** [comment]
The latest version of `vitest` had some breaking changes. This is fixed in Wallaby core `v1.0.1356`.
