### ISSUE TITLE
Wallaby incompatible with @vitejs/plugin-react v3.0.0

### ISSUE THREAD

**Issue by matchatype** [wallabyjs/public#3123]
Upgrading @vitejs/plugin-react from v2.2.0 to v3.0.0 apparently breaks Wallaby:

```
Failed to initialize wallaby vitest.
e.replace is not a function
TypeError: e.replace is not a function
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. The latest version of Wallaby core, `v1.0.1357` now supports v3.0.0 of `@vitejs/plugin-react`.
