### ISSUE TITLE
Please support concurrent tests in Jest

### ISSUE THREAD

**Issue by zaripych** [wallabyjs/public#3126]
### Issue description or question

Jest concurrent tests are not detected. Ie if I declare a test using:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/396623/207490446-7502d42c-a87b-46b8-9833-0d48cd43e4ea.png">

The test would not be detected unless `.concurrent` is removed - then I can see actions above the test:
<img width="581" alt="image" src="https://user-images.githubusercontent.com/396623/207490519-b43b17c7-3177-4858-a4a1-1a535097e1b9.png">

The total number of tests is reported incorrectly.

Also this message is printed in the console:
```
Some of the failing tests can not be reported, check the wallaby console for more details 
```

I understand that `.concurrent` is considered an experimental feature https://jestjs.io/docs/api#testconcurrentname-fn-timeout

### Wallaby diagnostics report

```
{
  editorVersion: '1.74.0',
  pluginVersion: '1.0.348',
  editorType: 'VSCode',
  osVersion: 'darwin 22.1.0',
  nodeVersion: 'v16.15.1',
  coreVersion: '1.0.1357',
}
```

Cannot provide full report for security reasons.

**Comment by smcenlly** [comment]
We do not have plans to add first class support for `.concurrent` until it moves out of experimental status. Wallaby has a number of mechanisms (unrelated to `jest`) for running your tests in parallel which right now conflict with the `jest` feature and so we need it to be finalized before we add support.

Having said that, we have updated Wallaby to ignore the `concurrent` status of your tests when you use Wallaby. This means that Wallaby will execute your tests as if they did not have use `.concurrent`.

Please update to the latest version of Wallaby core, `v1.0.1359`, it should work for you.

**Comment by zaripych** [comment]
Thank you for making it do that. Appreciate it. 👍
