### ISSUE TITLE
typescript compiler for .js files

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3129]
### Issue description or question

I'm heavily using TS-types-in-JavaScript.  My sources and tests are written in plain JavaScript using (non-Node.js-native) ESM.  I'm using `tsc` to do type checking, emission of declaration files, and compilation down to CJS.

But I can't seem to force Wallaby to compile JS files (Node.js).

I'm trying this config:

```js
    compilers: {
      '**/*.js': wallaby.compilers.typeScript({
        allowJs: true,
        module: 'commonjs',
      }),
    },
```

...but I still get all of these errors about using import outside of a module.

The project is a [sizable monorepo](/appium/appium) using a composite strategy.  Outside of Wallaby, we use Mocha and `ts-node` to execute tests--but the tests themselves are not explicitly included within any `tsconfig.json` due to not publishing the tests.

The workaround would be to just use Wallaby's Babel compiler--but that means I'd need to add Babel (`@babel/core` and `@babel/preset-env` I think) as a dev dep.  I don't have any other use for Babel _besides_ Wallaby, so I'd like to avoid it.

Can you help?  

Thanks for the great work on Wallaby!

### Wallaby diagnostics report

(attached, because too big)

[wallaby.log](https://github.com/wallabyjs/public/files/10248571/wallaby.log)

**Comment by smcenlly** [comment]
Thanks for your diagnostics report and the sample repo.

I updated the TypeScript configuration to align with your TypeScript compiler settings to create a configuration that should work for you

* `module: 'commonjs',` isn't specified in your `tsconfig.json` but is the default so you don't need this
* Added `allowSyntheticDefaultImports` and `resolveJsonModule`
* Did not add `noEmit` as it will cause Wallaby to fail
* Added `isolatedModules: true` to align with `ts-node.transpileOnly`

```diff
'use strict';

module.exports = (wallaby) => {
  return {
    compilers: {
      '**/*.js': wallaby.compilers.typeScript({
        allowJs: true,
-       module: 'commonjs',
+       allowSyntheticDefaultImports: true,
+       resolveJsonModule: true,
+       isolatedModules: true,
      }),
    },
    debug: true,
    env: {
      type: 'node',
    },
    files: [
      './packages/**/*.js',
      './packages/**/*.json',
      '!./packages/**/build/**',
      '!./packages/**/test/**/*-specs.js',
      '!./packages/**/test/**/*.spec.js',
      '!./packages/*/node_modules/**',
      '!./packages/*/gulpfile.js',
      '!./packages/*/scripts/**',
      './packages/*/test/**/fixtures/**/*',
      './babel.config.json',
      // below this are fixtures
      {
        binary: true,
        pattern: './packages/support/test/unit/assets/sample_binary.plist',
      },
      {
        instrument: false,
        pattern: './packages/support/test/unit/assets/sample_text.plist',
      },
      {
        instrument: false,
        pattern: './packages/base-driver/static/**/*',
      },
      '!**/local_appium_home/**',
    ],
    testFramework: 'mocha',
    tests: ['./packages/*/test/unit/**/*.spec.js', '!**/local_appium_home/**'],
    workers: {
      restart: true,
    },
    setup() {
      // This copied out of `./test/setup.js`, which uses `@babel/register`.
      // Wallaby doesn't need `@babel/register` (and it probably makes Wallaby slow),
      // but we need the other stuff, so here it is.

      const chai = require('chai');
      const chaiAsPromised = require('chai-as-promised');
      const sinonChai = require('sinon-chai');

      // The `chai` global is set if a test needs something special.
      // Most tests won't need this.
      global.chai = chai.use(chaiAsPromised).use(sinonChai);

      // `should()` is only necessary when working with some `null` or `undefined` values.
      global.should = chai.should();
    },
    runMode: 'onsave'
  };
};
```

**Comment by boneskull** [comment]
Works! Thank you.
