### ISSUE TITLE
 not a valid Win32 application

### ISSUE THREAD

**Issue by daw451-duplicate** [wallabyjs/public#313]
getting the following error:

Error: %1 is not a valid Win32 application.
......\trunk\node_modules\bcrypt\build\Release\bcrypt_lib.node

we use the module for encryption of passwords... in node.

any ideas?

**Comment by ArtemGovorov** [comment]
Wallaby.js is using its own [node.js version to run tests by default](http://wallabyjs.com/docs/integration/node.html#node-version). Try setting `env.runner` to `node` to make it use your local version.

``` JavaScript
module.exports = function () {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    env: {
      type: 'node',

      // if runner property is not set, then wallaby.js embedded node.js version is used
      // you can specifically set the node version by specifying 'node' (or any other command)
      // that resolves your default node version, or just specify the path
      // to your node installation, like

      runner: 'node'
    }
  };
};
```
