### ISSUE TITLE
Wallaby incompatible with vitest 0.25.8

### ISSUE THREAD

**Issue by bad4iz** [wallabyjs/public#3130]
Wallaby seems to be broken (IntelliJ version) with vilest v0.25.8.

```
Failed to initialize wallaby vitest.
Could not find vitest utils.
Error: Could not find vitest utils.
```

it works on v0.25.0.

[there was a problem with version v0.25.5](https://github.com/wallabyjs/public/issues/3122)
![image](https://user-images.githubusercontent.com/16918043/208299317-80ba6ca6-8147-4800-9a45-2b1008a22d01.png)
![image](https://user-images.githubusercontent.com/16918043/208299255-adff560d-c43d-47df-8690-0b03d43738d3.png)

**Comment by smcenlly** [comment]
The latest version appears to work for us. Could you please try this [sample repo](https://github.com/wallabyjs/vitesse) that we have created and see if it works for you?

Could you also please provide us with your diagnostics report (instructions for generating it are in the new issue template).

**Comment by bad4iz** [comment]
![image](https://user-images.githubusercontent.com/16918043/208353979-d5863564-a462-4b54-b85e-3c36a5b54524.png)


![image](https://user-images.githubusercontent.com/16918043/208354149-7ebf7e46-c3a0-4add-ab9f-1bcbaaf9c41a.png)

**Comment by bad4iz** [comment]
![image](https://user-images.githubusercontent.com/16918043/208354260-4851e429-515f-4776-9fd9-94007e3ca02c.png)
I can't run the "Copy Diagnostics Report" yet. I press but nothing happens
```
wallaby.js started
core v1.0.1355
Wallaby App (realtime reports) is available at: http://localhost:51245
Runtime error: Failed to initialize wallaby vitest.
Could not find vitest utils.
Error: Could not find vitest utils.
    at new Promise (<anonymous>)
    at new Promise (<anonymous>)
    at WebSocket.emit (node:events:513:28)
    at afterWrite (node:internal/streams/writable:500:5)
    at onwrite (node:internal/streams/writable:480:7)
    at Zlib.cb (node:internal/streams/transform:190:7)
    at Zlib.processCallback (node:zlib:613:8)
Diagnostics report has been successfully copied to clipboard.
May have failed to copy to clipboard. spawn clip ENOENT
Diagnostics report has been successfully copied to clipboard.
May have failed to copy to clipboard. spawn clip ENOENT
```
I'll try reinstalling wallaby

**Comment by smcenlly** [comment]
It looks like you are using an older version of Wallaby that doesn't support the latest version of `vitest`. This is because there was recently a breaking change to `vitest` 

This may be because your license has expired. You can confirm this by requesting a trial license from [our website](https://wallabyjs.com/download/#try-it-free).

Please update to use the latest version, it should work for you.

**Comment by bad4iz** [comment]
I can't pay for a new license. I'm from Russia.
my wallaby.js v1.0.256
my upgrade license expired on December 10th.

**Comment by bad4iz** [comment]
I can't run it in vscode either to check. I'm doing
![image](https://user-images.githubusercontent.com/16918043/208357683-cd0b7104-bd6a-4b73-b5fa-b47758f302a3.png)
receive
![image](https://user-images.githubusercontent.com/16918043/208357548-ae00641d-b3f6-46f5-bbc7-c160983c7610.png)
and nothing works
