### ISSUE TITLE
IntelliJ `Show in output inspector` does nothing

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#3134]
### Issue description or question

I am using ava and configuration file config. I cannot see the output inspector.

### Wallaby diagnostics report

```
{
  editorVersion: 'IntelliJ IDEA 2022.3',
  pluginVersion: '1.0.253',
  editorType: 'IntelliJ',
  osVersion: 'darwin 22.2.0',
  nodeVersion: 'v18.12.1',
  coreVersion: '1.0.1363',
  checksum: 'MmMxY2MyYzI2N2IyNTcxMjIxYjAxYWE3NjVhZTQ2MTksMTcxNjQyMjQwMDAwMCww',
```

The log prints the following when I try this action:

```
2022-12-21T10:59:34.911Z extended-core Adding inspections
```

**Comment by vjpr** [comment]
I changed `Tools > Wallaby.js > View mode` to `Split view` and it now shows up...

**Comment by smcenlly** [comment]
It was working for me by default, are you able to provide steps to reproduce the problem? I'm not quite sure how to get my views into a state where it doesn't work.

**Comment by smcenlly** [comment]
Closing this issue since we haven't heard back. If you can provide us with steps to reproduce the problem, we'll re-open the issue.
