### ISSUE TITLE
how to make vitest work in cra ?

### ISSUE THREAD

**Issue by bad4iz** [wallabyjs/public#3138]
### how to make vitest work in cra ?
there is a project on cra I want to launch vitest in it . Wallaby always runs jest. I could only launch Vitest in wallaby only when I removed react-script from package.json . But this is not the way out))

**Comment by smcenlly** [comment]
By default, Wallaby detects `react-script` and determines that your test runner for your project is `jest`.

If you don't want Wallaby to automatically use `jest` you may make Wallaby run only detect `vitest` by adding the following code to your package.json:

```diff
...
+  "wallaby": {
+    "autoDetect": [
+      "vitest"
+    ]
+  }
```

Alternatively, you can do the same by creating a [Wallaby configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file):

**wallaby.js**
```javascript
module.exports = () => ({
   autoDetect: ['vitest']
});
```

**Comment by bad4iz** [comment]
Thanks for the reply. It works well.
You've helped a lot. Happy New Year !!!! 🎄🎄🎄 🎅🤶
