### ISSUE TITLE
Testing with full browser environment

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3147]
I've been on vitest, but I've just hit an issue where I need IndexedDB to be available in the test environment.

Can you advise what the best Wallaby setup is for this?

The docs (https://wallabyjs.com/docs/integration/chrome.html) say

> By default, wallaby.js uses Google Chrome (headless) as its test runner"

But then on the same page

> You will need to specify kind: 'chrome' in your env setting in wallaby config

So it's not clear if that's a default or not.

The other thing that is not clear is that you recommend getting the tests running outside of Wallaby first, before troubleshooting any Wallaby issues - but if I want the tests to run in headless chrome, what's the best way to get that working?

**Comment by tslocke** [comment]
I'll add to this, what is a good runner that works well with Wallaby and ES modules? I am not attached to Jest at this point. In fact having a tough time getting it to work.

And advice on the best testing framework for Wallaby + chrome headless + typescript + ESM ?

**Comment by smcenlly** [comment]
> The docs (https://wallabyjs.com/docs/integration/chrome.html) say
> 
> > By default, wallaby.js uses Google Chrome (headless) as its test runner"
> 
> But then on the same page
> 
> > You will need to specify kind: 'chrome' in your env setting in wallaby config
> 
> So it's not clear if that's a default or not.

Google chrome (headless) is the default test runner **unless** you are using automatic configuration. If you are using automatic configuration, then the test runner will be selected based on your testing framework / configuration. For example, in the case of `jest`, tests are run in `node.js` and the browser is emulated with `jsdom` if required.

> The other thing that is not clear is that you recommend getting the tests running outside of Wallaby first, before troubleshooting any Wallaby issues - but if I want the tests to run in headless chrome, what's the best way to get that working?

Are your tests running in headless chrome outside of Wallaby? If so, what testing framework / setup are you using? Generally speaking, the same advice applies, make sure that your tests are running outside of Wallaby before trying to run them with Wallaby. Obviously you will need to make sure that your testing framework is supported by Wallaby if you then want to run tests using Wallaby.

---

> I've been on vitest, but I've just hit an issue where I need IndexedDB to be available in the test environment.

Did you consider something like https://www.npmjs.com/package/fake-indexeddb? I'm not super familiar with `IndexedDB` but I'd consider start with something like that for mocking in the context of running tests.

---

> I'll add to this, what is a good runner that works well with Wallaby and ES modules? I am not attached to Jest at this point. In fact having a tough time getting it to work.
> 
> And advice on the best testing framework for Wallaby + chrome headless + typescript + ESM ?

If you're using `jest` or `vitest`, then you're not going to be running in chrome headless (instead you're going to be emulating the DOM with something like `jsdom` or `happy-dom`). If chrome headless is a hard requirement, then I'd consider using `mocha` or `jasmine`. Having said that, in my experience, `node`-based unit tests are generally faster, so I'd probably try and run in something like `jest` or `vitest` unless I absolutely needed the browser.

---

It's a little hard to provide advice / guidance without understanding your project / code, etc. Is you project open-source or can you share it with us? It's a little outside the scope of Wallaby product support, but happy to take a look for you to see if we can easily help.

**Comment by tslocke** [comment]
Thanks very much for the advice - fake-indexeddb is working well for me 👍
