### ISSUE TITLE
Proposal: Make activity bar icon match VS Code style guide

### ISSUE THREAD

**Issue by azat-io** [wallabyjs/public#3153]
There is official VS Code icon library - codincons:
https://microsoft.github.io/vscode-codicons/dist/codicon.html

The current icon stands out from the rest:

<img width="389" alt="Screenshot 2023-01-23 at 7 32 40 PM" src="https://user-images.githubusercontent.com/5698350/214097291-b2e99625-4106-488d-a7cc-2fec51632252.png">

It would be nice to make outline activity bar icon.  Maybe like this:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/5698350/214097815-f30c04c4-fec8-49e0-bff0-657ad56a8288.png">

Here is svg icon:

![wallaby](https://user-images.githubusercontent.com/5698350/214095851-04a7c0a5-7712-46e7-a0e0-9b446d526b24.svg)

**Comment by ArtemGovorov** [comment]
Thanks for submitting the proposal. We have updated the logo to look like VS Code built-in icons.
<img width="62" alt="Screen Shot 2023-01-27 at 11 40 59 am" src="https://user-images.githubusercontent.com/979966/214995204-2c83c1ca-5a12-4def-8ef9-39a280a20f6a.png">

**Comment by azat-io** [comment]
<img width="69" alt="image" src="https://user-images.githubusercontent.com/5698350/215169802-ec772703-315c-4b71-833b-3e9fcb6497ed.png">


It looks like the new icon is thinner than the other VS Code icons. Isn't it?

**Comment by azat-io** [comment]
![wallaby](https://user-images.githubusercontent.com/5698350/215238788-6e461d2c-0396-4a4d-8a5e-79f38c355685.svg)

Could you try using this one?

**Comment by azat-io** [comment]
![wallaby](https://user-images.githubusercontent.com/5698350/215238874-322b42b1-a6f9-4ec8-9187-59686edbd7ef.svg)

@ArtemGovorov Could you try using this one?

```svg
<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_329_25)">
<g clip-path="url(#clip1_329_25)" filter="url(#filter0_d_329_25)">
<g filter="url(#filter1_d_329_25)">
<path fill-rule="evenodd" clip-rule="evenodd" d="M31 19.75V2.875L29.125 1H18.875L17 2.875V17.5625H2.875L1 19.4375L1 29.125L2.875 31H29.125L31 29.125V19.75ZM29.125 2.875V17.875V29.125H2.875V19.4375H17L18.875 17.5625V2.875H29.125Z" fill="white"/>
<path d="M17 18.0625H17.5V17.5625V3.08211L19.0821 1.5H28.9179L30.5 3.08211V19.75V28.9179L28.9179 30.5H3.08211L1.5 28.9179V19.6446L3.08211 18.0625H17ZM29.625 2.875V2.375H29.125H18.875H18.375V2.875V17.3554L16.7929 18.9375H2.875H2.375V19.4375V29.125V29.625H2.875H29.125H29.625V29.125V17.875V2.875Z" stroke="white"/>
</g>
</g>
</g>
<defs>
<filter id="filter0_d_329_25" x="-3" y="1" width="38" height="38" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="4"/>
<feGaussianBlur stdDeviation="2"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_329_25"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_329_25" result="shape"/>
</filter>
<filter id="filter1_d_329_25" x="-3" y="1" width="38" height="38" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
<feFlood flood-opacity="0" result="BackgroundImageFix"/>
<feColorMatrix in="SourceAlpha" type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0" result="hardAlpha"/>
<feOffset dy="4"/>
<feGaussianBlur stdDeviation="2"/>
<feComposite in2="hardAlpha" operator="out"/>
<feColorMatrix type="matrix" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/>
<feBlend mode="normal" in2="BackgroundImageFix" result="effect1_dropShadow_329_25"/>
<feBlend mode="normal" in="SourceGraphic" in2="effect1_dropShadow_329_25" result="shape"/>
</filter>
<clipPath id="clip0_329_25">
<rect width="32" height="32" fill="white"/>
</clipPath>
<clipPath id="clip1_329_25">
<rect width="30" height="30" fill="white" transform="translate(1 1)"/>
</clipPath>
</defs>
</svg>
```

**Comment by azat-io** [comment]
This icon based on "Extensions" icon

**Comment by smcenlly** [comment]
Thanks for taking the time to provide the icon for us.

We are happy with the icon change we had made. On most resolutions it aligns with the other VS Code icons (which are also not consistent in width with each other). The icon represents our logo as we like and we are happy with the change.

Thanks again for reporting to us and for suggesting the change.

**Comment by azat-io** [comment]
Unfortunately, it's very noticeable now. The new icon is thinner

**Comment by azat-io** [comment]
Current icon:

<img width="1091" alt="Screenshot 2023-01-29 at 11 14 56 PM" src="https://user-images.githubusercontent.com/5698350/215354684-f3542cc0-8f45-4ef3-9dba-4cd13ed25e14.png">


Suggested icon:

<img width="1091" alt="Screenshot 2023-01-29 at 11 38 23 PM" src="https://user-images.githubusercontent.com/5698350/215354693-8801269f-4316-46c2-a984-a89c412aee2e.png">

**Comment by smcenlly** [comment]
Thanks again for taking the time to report the issue.

We are happy with the updated icon change we made and don't have any plans to change it again.
