### ISSUE TITLE
Wallaby doesn't work with pnpm when JS API is used

### ISSUE THREAD

**Issue by gzaripov** [wallabyjs/public#3157]
We use pnpm JS api for working with monorepo, i.e. to get list of all packages.

Unfortunately, pnpm uses [npm_package_version](https://github.com/pnpm/pnpm/blob/4ca53b0b50220da5e1aa8345817d04f09cda0c7b/cli/cli-meta/src/index.ts#L10) variable, that is set when script was executed by npm or pnpm cli. And wallaby doesn't set it.

And I see this error when I start wallaby:

```
Error: Unsupported engine for <package-path>: wanted: {"pnpm":"7.13.1"} (current: {"node":"v16.19.0","pnpm":"0.0.0"}) 
```

If I run tests by `pnpm run test` it will work just fine. Because then `npm_package_version` is set.

I see several solutions here:
1. Set these variables automatically in wallaby
2. Add possibility to set these variables globally in vscode settings, because we have a lot of packages that uses `pnpm` features.

**Comment by smcenlly** [comment]
We've been using `pnpm` with Wallaby for a while now and haven't run into this problem.

**Could you please provide us with steps for reproducing the error?**

---

From your report, it's not clear where your error is occurring. It may be possible to fix your problem by [using a Wallaby configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file) where you explicitly set `process.env.npm_package_version` for example:

**wallaby.js**
```javascript
// TODO - update the version number required for your project
process.env.npm_package_version = '7.13.1';

module.exports = ({
  autoDetect: true
})
```

**Comment by smcenlly** [comment]
@gzaripov - Could you please provide us with steps for reproducing the error?

**Comment by smcenlly** [comment]
I'm closing this issue as we haven't heard back. Assuming it's working for you.

If you can provide us with steps to reproduce the problem, we'll re-open and investigate further.
