### ISSUE TITLE
views not in instrumented directory

### ISSUE THREAD

**Issue by mwehlou** [wallabyjs/public#316]
I'm having problems getting the render of views to work. When I run under Wallaby, __dirname refers to an "instrumented" folder under WebStorm10/wallaby... and I find routes and test there, but the views folder isn't there, so it doesn't work. All I see is the following:

drwxr-xr-x  6 mw  staff   204 Oct 31 13:32 .
drwxr-xr-x  5 mw  staff   170 Oct 31 13:32 ..
-rw-r--r--  1 mw  staff  2061 Oct 31 14:12 app.js
drwxr-xr-x  5 mw  staff   170 Oct 31 13:46 routes
drwxr-xr-x  4 mw  staff   136 Oct 31 13:32 test
-rw-r--r--  1 mw  staff   424 Oct 31 13:32 wallaby.js

If I run without wallaby, __dirname refers to the actual project dir and the views are found. The views folder is in the wallaby.js file under "files".

Check out the value at line 16 in app.js, where I put in a console.log
You can pick up the project here:

https://db.tt/quOOOo43

**Comment by ArtemGovorov** [comment]
Your config file pattern for views is `'views/*.js'` but needs to be `'views/*.jade'`.

**Comment by mwehlou** [comment]
> On 31 Oct 2015, at 14:22, Artem Govorov <notifications@github.com> wrote:
> 
> Your config file pattern for views is 'views/*.js' but needs to be 'views/*.jade'.
> 
> 

Darn. I’m really bad at attention to detail, it seems. Thx again!

**Comment by ArtemGovorov** [comment]
No worries, it does take some time to get used to a new tool.
