### ISSUE TITLE
Wallaby config for a standard vue 3 project with typescript

### ISSUE THREAD

**Issue by Suiken** [wallabyjs/public#3160]
### Issue description or question
I tried to use Wallaby with a Vue 3 project generated by `npm init vue@latest` but it didn't work.

Here is the error :
```
src/components/__tests__/HelloWorld.spec.ts HelloWorld renders properly [3 ms]

	ReferenceError: document is not defined
		at src/components/__tests__/HelloWorld.spec.ts:8😘

```

To make it work with vitest, the command is `vitest --environment jsdom`

So the question is: Is it possible to make wallaby use vitest by setting an environment for it ?

Thank you !

**Comment by smcenlly** [comment]
If `vitest` works from the CLI with `npx vitest`, then Wallaby should also work.

In the case of the `create-vue` template, there is a pull request to fix this issue **and** another issue involving `e2e` tests being run incorrectly when using the `vitest` CLI.

For now, we suggest applying the same configuration changes as suggested in the [pull request](https://github.com/vuejs/create-vue/pull/227/commits/897ac762a2ee7c515fd1d05392d90469eb794f23). If the explicit `vitest.config.js` file is added as per the pull request then this issue should no longer affect anyone. If for some reason the pull request is rejected, we'll find another way for Wallaby to automatically detect the correct configuration but for now, our suggestion to you should fix your problem.
