### ISSUE TITLE
Keep writing to package.json even after uninstall of VSCode extension

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#3168]
Whatever this extension does, it is beyond my understanding of good practice.

1. Install `wallaby`
2. Use the recommended feature for automatic configuration
3. `wallaby` property keep popping up in `package.json`. I let it go as I thought that it is its way of keeping some cache.
4. Get fed up with removing changes in `package.json` before doing commit.
5. Get furious when after removing the extension, the issue persist.
6. Talking to myself when this happens even after removing VSCode cache data.

Can you share where you write this data, so that I can remove it? My OS is Manjaro.

**Comment by ArtemGovorov** [comment]
Wallaby extension doesn't write into `package.json` file. The issue is probably related to some other extension. Please try disabling other extension one by one, or bisecting them to find the extension that is causing the issue.

**Comment by selfrefactor** [comment]
It does write and it write in such manner that I cannot stop it. It doesn't matter - you are closing the issue without waiting for my reply.

I am simply not using it any more and I hope this issue is warning to potential users of this extension.
