### ISSUE TITLE
WebStorm, run exclusive test from different places

### ISSUE THREAD

**Issue by webuniverseio** [wallabyjs/public#3176]
Hello, I have a feature request. Very often I need to run an exclusive test for a specific file. The problem is that with WebStorm the only way to do that is through project view, context menu. What I want is to be able to do that via other context menus, not just from project menu. For example via file context within file, quokka is already doing that. Another good place is from 'Jump to Navigation bar' action, then right click on file (or use shortcut to open context), then it would be good to have run exclusive test there.

I believe I tried to set a shortcut to start exclusive test wallaby action, but I think it is not aware of currently open file, so I'm not confident that it is working the same way as from projects menu. I might be wrong as I only tried that from a large work project, so something might be a bit off about it.

**Comment by ArtemGovorov** [comment]
Hi, thanks for the feature request.

We do have a feature called [Smart Start](https://wallabyjs.com/docs/intro/smart-start.html?editor=jb) that makes Wallaby triggers exclusive test runs automatically on selected actions (such as a test file open, or a test file edit). Perhaps using the feature is even a better solution for your case?

**Comment by webuniverseio** [comment]
Hi Artem, this is a good one, I didn't know this can be related even when wallaby is not running (I thought smart start is for auto starting tests when you open them after you already started wallaby for something else). I'll give that a try. One thing I'm not 100% sure is auto start on open by default. I'm already used to it after wallaby is started, so maybe I'll be fine with that. I'll give that a try and I'm good to close this for now.

Thanks Artem!

**Comment by ArtemGovorov** [comment]
> I thought smart start is for auto starting tests when you open them after you already started wallaby for something else

This is correct, you have to start Wallaby Run Configuration first, but with Smart Start the launch is fast as it will not execute any tests to start with, and will only start executing them if you open/edit test files (depending on your preference).
