### ISSUE TITLE
Babel 6.0.0

### ISSUE THREAD

**Issue by TylorS** [wallabyjs/public#318]
I'm quite new to Wallaby.js and I'm very excited. I was previously able to get a project up and running with Webpack and Babel 5.x.x. Now I have a new library I need to work on with Browserify and I'd like to use Babel 6 if possible. My library and tests don't rely on the browser at all so I don't think I need to use browserify in my testing, but maybe I'm wrong? Is this currently possible?

My current configuration is this:

```js
var babel = require('babel-core');

module.exports = function (wallaby) {
  return {
    files: [
      'src/*.js'
    ],

    tests: [
      'test/*.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: babel
      })
    }
  };
};
```

But I get this error

```
Failed to run compilers on src/index.js, TypeError: n is not a function
  at Array.forEach (native)
  at emitTwo (events.js:87:13)
  at process.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:685:10)
  at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by ArtemGovorov** [comment]
Added babel 6 support in core v1.0.142. Please note [babel 6 comes without any default transforms](http://babeljs.io/blog/2015/10/31/setting-up-babel-6/), so you will have to add [presets and plugins](http://babeljs.io/docs/plugins) to the compiler options.

Also note that babel 6 is still very new, so [some things may not work as expected](https://github.com/babel/babel/issues). For example, if you hit **performance issues**, you may [need to do `npm dedupe`](https://github.com/babel/babel/issues/2706).

> My library and tests don't rely on the browser at all so I don't think I need to use browserify in my testing, but maybe I'm wrong? Is this currently possible?

Yes, you may try testing your library in [node environment](http://wallabyjs.com/docs/integration/node.html) that is supported by wallaby. If you don't use window object and DOM, it should work.

**Comment by peeter-tomberg** [comment]
@ArtemGovorov How do I define presets? I can't seem to get it to work with the following setup:

```
var babel = require('babel-core');
var webpack = require('webpack');
var path = require('path');
var wallabyWebpack = require('wallaby-webpack');
var config = require('./webpack.config');

var wallabyPostprocessor = wallabyWebpack(config);

module.exports = function (wallaby) {
    return {

        files: [
            { pattern: 'node_modules/react-tools/src/test/phantomjs-shims.js', instrument: false},

            // to avoid loading react into each test manually
            { pattern: 'node_modules/es5-shim/es5-shim.js', instrument: false},
            { pattern: 'node_modules/es5-shim/es5-sham.js', instrument: false},

            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
            { pattern: 'node_modules/chai/chai.js', instrument: false},

            { pattern: 'src/**/*.js?', load: false },
            { pattern: 'src/**/*Spec.js', ignore: true }
        ],

        tests: [
            { pattern: 'src/**/*Spec.js', load: false }
        ],

        //preprocessors: {
        //    '**/*.js?': file => require('babel').transform(file.content, {
        //        sourceMap: true,
        //        presets:[
        //            'react',
        //            'es2015',
        //            'stage-0'
        //        ]
        //    })
        //},

        compilers: {
            'src/**/*.js?': wallaby.compilers.babel({
                babel: babel,
                presets:[
                    'react',
                    'es2015',
                    'stage-0'
                ]
            })
        },

        testFramework: "mocha",

        postprocessor: wallabyPostprocessor,

        debug: true,

        bootstrap: function () {
            var mocha = wallaby.testFramework;
            mocha.ui('bdd');
            window.expect = chai.expect;
            var should = chai.should();

            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        }
    };
};
```

**Comment by fvanwijk** [comment]
Why `load: false` in your tests list?

**Comment by ArtemGovorov** [comment]
@peeter-tomberg Presets seems to be defined correctly. The issue is in your pattern: `src/**/*.js?` - it only matches files with 3 chars extensions, as `?` means exactly one character, so just `.js` files don't match. Should work for you if you replace it with: `src/**/*.js*` (both in your compiler patterns and in the `files` list).

@fvanwijk webpack integration is used, so the tests are loaded in the bootstrap function: `window.__moduleBundler.loadTests();`

**Comment by ArtemGovorov** [comment]
Have added [Babel 6 notes to the docs](http://wallabyjs.com/docs/integration/es-next.html#babel-6).
