### ISSUE TITLE
Ability to suppress "console.log" capture

### ISSUE THREAD

**Issue by milang** [wallabyjs/public#3189]
### Issue description or question

I really like the Wallaby `console.log` output capture feature during development. However, sometimes my tests explicitly capture `console` output using `jest.spyOn` and include it in my assertions. Wallaby will correctly stop capturing mocked `console.error` and `console.warn` calls, however `console.log` calls are still captured regardless of whether the function is mocked or not.

To demonstrate, I used the following simple program (Jest + automatic mode Wallaby in VSCode):

```js
function hijackConsole(log) {
  const spyError = jest.spyOn(console, "error");
  spyError.mockImplementation((...args) => log.push(`console.error:${args.join(" ")}`));
  const spyWarn = jest.spyOn(console, "warn");
  spyWarn.mockImplementation((...args) => log.push(`console.warn:${args.join(" ")}`));
  const spyLog = jest.spyOn(console, "log");
  spyLog.mockImplementation((...args) => log.push(`console.log:${args.join(" ")}`));

  return function restore() {
    spyLog.mockRestore();
    spyWarn.mockRestore();
    spyError.mockRestore();
  };
}

describe("console", () => {
  it("captures log messages", () => {
    const log = [];
    const restoreConsole = hijackConsole(log);
    console.error("Test error");
    console.warn("Test warning");
    console.log("Test message");
    expect(log).toEqual([
      "console.error:Test error",
      "console.warn:Test warning",
      "console.log:Test message"
    ]);
    restoreConsole();
  });
});
```

When the `hijackConsole` and related code is commented out, Wallaby correctly captures all three console calls:

<img width="715" alt="TestOutputNoSpy" src="https://user-images.githubusercontent.com/42297/227743997-aef204d2-d6e0-459e-a7e6-3e30c543f345.png">

However, when `hijackConsole` and related code is active, Wallaby does not capture `console.error` and `console.warn` output (as expected), but still captures `console.log` (not expected, inconsistent):

<img width="715" alt="TestOutputSpy" src="https://user-images.githubusercontent.com/42297/227744092-0b78bcca-618c-4bd5-ae35-78454e221817.png">

The log message also shows up in the editor:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/42297/227744272-b4371c74-3de2-420b-9b4d-8e878a9f6ec5.png">

I tried looking for either a configuration setting or a comment that would tell Wallaby _"do not capture console.log output in this test, please and thank you"_, however I didn't find anything. Is this possible?

Even better (IMO) would be if Wallaby made `console.log` behaviour consistent with `console.error` and `console.warn`: when not mocked, capture the output; when mocked, stop capturing the output.

### Wallaby diagnostics report

Not including because Wallaby test execution is working correctly.

**Comment by smcenlly** [comment]
Logging `console.log` in your scenario is inteded behavior and is a part of Wallaby's **Advanced Logging** functionality. We have added a new configuration setting that we believe will address your scenario. The setting disables `console.log` output for your entire project.

Please remember that Wallaby contains a number of other ways to log values, including:

- Identifier expressions
- Live values comments `//?`
- Show Value command 

From our docs:

> By default, Wallaby will capture and display any `console.log` values that are executed by your code and tests. This behavior can be changed with the `captureConsoleLog` setting:
> 
> **Wallaby.js Configuration file**
> ```javascript
> module.exports = function () {
>   return {
>     ...
>     captureConsoleLog: false
>   };
> };
> ```

Please update to Wallaby core `v1.0.1402` and create a a configuration file with the setting above and the `console.log` statements will behave the same as `console.error` and `console.warn`.
