### ISSUE TITLE
Feature Request: Output Inspector - Add facility to copy received data/object 

### ISSUE THREAD

**Issue by 8enSmith** [wallabyjs/public#3201]
### Issue description or question

In the 'Output Inspector' it would be great if there was a facility (e.g. copy to clipboard) feature to allow me to copy the 'Received' data/object.

Whilst the diff showing what is expected versus what was received works fine (i.e. the '+' and '-' syntax), if I want to quickly update my test, having to copy the text in the Output Inspector and then delete the mark-up is a chore.

**Comment by smcenlly** [comment]
Out of interest, what editor are you using?

**Comment by 8enSmith** [comment]
@smcenlly doh! I should have mentioned that in the description. I am using Visual Studio Code 1.77.3.

**Comment by ArtemGovorov** [comment]
@8enSmith We have implemented code lens to Copy Actual or Expected Value in Output Inspector in v1.0.354+.
<img width="679" alt="Screen Shot 2023-05-18 at 11 58 34 am" src="https://github.com/wallabyjs/public/assets/979966/a3347371-bbce-486b-867f-b03c75f9faf1">

**Comment by 8enSmith** [comment]
@ArtemGovorov Excellent! This will be really useful. Thank you Wallaby team.
