### ISSUE TITLE
wallaby can't find my dependencies?

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3202]
### Issue description or question

This is a weird one.  Running Wallaby today, all of my deps seem to be replaced with `undefined`.  e.g.:

```js
const _ = require('lodash');

const foo = _.partial(someFunc, someArg); // can't read partial because _ is undefined
```

My sources and tests are `.js` files compiled via `tsc`, and I've been using the config you graciously provided some months ago. 

I've tried resetting the Wallaby cache, force-updating, blasting my `~/.npm` folder and reinstalling everything, but nothing seems to help.  Other projects do not exhibit this behavior.  My tests all pass with `mocha` + `ts-node`.  Might be worth mentioning that I'm using `typescript@v5.0.4`.

### Wallaby diagnostics report

Attached.

[wallaby.md](https://github.com/wallabyjs/public/files/11277981/wallaby.md)

and [here's a gist of the source file](https://gist.github.com/boneskull/91fc62e97501967f1eb70776afacbdfb) throwing the exception

**Comment by smcenlly** [comment]
Haven't started to look at your issue yet, but wanted to try catch you while you're still online. Is this for a public repo? If so, mind sharing your project / branch so we can try for ourselves?

**Comment by smcenlly** [comment]
We've reproduced the issue and are investigating.

**Comment by smcenlly** [comment]
Based on your error and what we did to reproduce your problem, it looks like `esModuleInterop` is required as a TypeScript setting but it's not being provided. Perhaps this changed recently in your `tsconfig.json`?

The following should fix your problem for your `.js` files:

```diff
'use strict';

module.exports = (wallaby) => {
  return {
    compilers: {
      '**/*.js': wallaby.compilers.typeScript({
        allowJs: true,
        allowSyntheticDefaultImports: true,
        resolveJsonModule: true,
        isolatedModules: true,
+       esModuleInterop: true,
      }),
      '**/*.ts?(x)': wallaby.compilers.typeScript(),
    },
...
};
```

**Comment by boneskull** [comment]
@smcenlly Thanks.  The repo is [headspinio/appium-tizen-tv-driver](/headspinio/appium-tizen-tv-driver).  Still having some weird stuff happen here, but I'll follow up tomorrow.

**Comment by boneskull** [comment]
OK, I see what's going on.

This is a monorepo, so each package has its own `tsconfig.json`.  The config of that package _has_  `esModuleInterop: true`, but the _root_ `tsconfig.json` did not.  It appears this is significant (at least to Wallaby), so updating the root `tsconfig.json` fixes the issue w/o needing to modify the Wallaby config.
