### ISSUE TITLE
Open source license not working

### ISSUE THREAD

**Issue by niktek** [wallabyjs/public#3204]
### Issue description or question
Hi!

In https://account.wallabyjs.com/manage/ it shows that I have an Open Source Personal license, but when I try to enter my e-mail into the license section in VSCode, I get the following:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/52020637/235076548-42709b8b-65b8-4bb5-8eed-755cc18cd8af.png">

Unfortunately there is no actual key on my account page, so I can't try that as an alternative.

Any help appreciated!

**Comment by smcenlly** [comment]
Quokka does not have any sort of open source license model, that is only available for Wallaby. Instead, for Quokka, you may use the Community Edition if you do not have a license.

Please activate using your email via Wallaby's start page, instead of Quokka, it should work for you.
