### ISSUE TITLE
debug console

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#3205]
After clicking the debug button above a test, is there a way to access a debug console to execute some js code on the currently scoped vars like the vs code debug console?

**Comment by smcenlly** [comment]
Wallaby's Time Travel Debugger does not provide a debug console like the one in Visual Studio Code where you can execute arbitrary JavaScript code in the current scope. Instead, it provides various features for inspecting the state of your code at different points in time.

The primary way to inspect variables in the current scope in Wallaby's Time Travel Debugger is by selecting the variable, object, object property, parameter, or expression you want to inspect. Wallaby will then display the value of the selected item. Please note that the selection must be either on the current step or a previous step for the value to be displayed.

The Edit-and-Continue feature of Wallaby's Time Travel Debugger can also be quite valuable for inspecting runtime values. This functionality allows you to modify your code (i.e. add more logging) in the middle of a debugging session, and then continue debugging with the changes in place.

**Comment by bj97301** [comment]
Oh interesting I wasn’t aware of the edit and continue feature. That should work for most situations. Thank you.
