### ISSUE TITLE
Wallaby.js configuration error with Vitest 0.30

### ISSUE THREAD

**Issue by AlexandreGerault** [wallabyjs/public#3206]
### Issue description or question

I just bought and installed Wallaby.js on my Visual Studio Code editor. It is a vite react project with Typescript and vitest as test framework. When I run the tests via vitest, it works well. However, when I try to start Wallaby.js with the automatic configuration (current directory) I got this error message:
```
‌[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Vitest configuration error: Vitest dependency not found. 
```
I also tried to downgrade vitest as said in doc to 0.29 and 0.28 (with all fix patches, like 0.29.1, 0.29.2 etc). None seemed to work.

### Wallaby diagnostics report

Unfortunately it doesn't seem to be any report as Wallaby.js can't even start. Tell me if I'm wrong

**Comment by smcenlly** [comment]
Is it possible you're running a mono-repo? That may explain why it's not working for you if Wallaby can't find `vitest` in your mono-repo root `package.json`.

Could you please explain your project structure (i.e. mono-repo and if so how you're managing it), your `package.json`, and how you are installing your dependencies?

**Comment by smcenlly** [comment]
Can you also please tell us what version of `node.js` you are using? If you are using `v20.0.0`, please try downgrading to the latest LTS version (`v18.16.0`).

**Comment by AlexandreGerault** [comment]
Hey
I'm already using node v18.16.0 👍

**Comment by AlexandreGerault** [comment]
I'm not using a monorepo either, you can find the project here: https://github.com/AlexandreGerault/dixit-client-react-vite, at the initial commit

**Comment by smcenlly** [comment]
Thanks for the sample project. Your project has some `yarn2` artifacts, but no `yarn2` configuration.

At startup, Wallaby sees the `yarn2` files and is tries to load them but then cannot find any dependencies because they're not installed.

To fix the problem, please delete:
* `node_modules` (folder)
* `.pnp.cjs` (file)
* `.pnp.loader.mjs` (file)
* `package-lock.json` (file)

Reinstall your dependencies, e.g. with `npm install`.

Wallaby should then work for you.

I had a few errors when installing dependencies:

```
 WARN  Issues with peer dependencies found
.
├─┬ @redux-devtools/core 3.13.1
│ ├── ✕ missing peer redux@"^3.5.2 || ^4.0.0"
│ └─┬ @redux-devtools/instrument 2.1.0
│   └── ✕ missing peer redux@"^3.4.0 || ^4.0.0"
├─┬ @redux-devtools/extension 3.2.5
│ └── ✕ missing peer redux@"^3.1.0 || ^4.0.0"
├─┬ react-redux 8.0.5
│ └── ✕ missing peer redux@^4
├─┬ redux-thunk 2.4.2
│ └── ✕ missing peer redux@^4
└─┬ eslint-config-react-app 7.0.1
  └─┬ eslint-plugin-flowtype 8.0.3
    ├── ✕ missing peer @babel/plugin-syntax-flow@^7.14.5
    └── ✕ missing peer @babel/plugin-transform-react-jsx@^7.14.9
Peer dependencies that should be installed:
  @babel/plugin-syntax-flow@^7.14.5          @babel/plugin-transform-react-jsx@^7.14.9  redux@">=4.0.0 <5.0.0"                     
```

The test also failed, I assume because of the missing dependencies.

**Comment by AlexandreGerault** [comment]
Thanks for your answer, I did what you suggested and the error message is now gone. I could start wallaby normally. But as I downgraded Vitest, my test aren't working well, so I updated to Vitest 0.30.1 and now Wallaby.js is stuck at loading:
```
‍​[Info]​ Started Wallaby.js Core v1.0.1408
```
But I have the loading icon staying in the bottom right corner as you can see on the screen 
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/3494871/235848080-1e116692-4e6f-4151-b6e7-28f354ee321c.png">

**Comment by smcenlly** [comment]
I believe your problem is a duplicate of https://github.com/wallabyjs/public/issues/3207.

Please update to the latest version of Wallaby core, `v1.0.1409`. It should fix your problem.

**Comment by AlexandreGerault** [comment]
Yes, the latest update fixed the problem. Thanks
