### ISSUE TITLE
Wallaby perpetually keeps looking for tests without throwing any error.

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/public#3207]
### Issue description or question

While I was using wallaby without any issue. After few of my code changes, when I had to restart Wallaby, I find that it perpetually keeps looking out for test.

![image](https://user-images.githubusercontent.com/79074469/235978577-d1afb08b-a8e6-48b5-9c2f-a69a96de3bfb.png)

Wallaby Console shows following message. All other Wallaby tabs such `Failing tests` etc. are blank.

```
wallaby.js started
core v1.0.1408
```

I have since done following steps

- Reset Wallaby cache
- Created a simple project - https://github.com/bhvngt/wallabyjs-vitest
- Invalidated Intellij cache
- Reinstalled Wallabyjs plugin

None of this has worked.

Even `Copy Wallaby  diagnostics report" menu is grayed out.

![image](https://user-images.githubusercontent.com/79074469/235979389-78309285-25eb-4da6-8cf1-e1b07436c511.png)

Project is using vitest and vitest runs successfully on the terminal.

Not sure What I need to do to get it back to working.

My configurations are

IntelliJ IDEA 2023.1.1 (Ultimate Edition)
Build #IU-231.8770.65
macOS 13.3.1
Apple M1 Pro
Wallabyjs 1.0.267

### Wallaby diagnostics report

`Copy Diagnostic Report` Menu item is grayed out.

**Comment by andrew-w-ross** [comment]
@bhvngt I can confirm it's not just you mine was working yesterday and is hanging today. 

Pretty much the same setup, vitest and macos m1 pro. Only difference is I'm on vscode.

**Comment by vritant24** [comment]
Likewise, facing the same issue

**Comment by anicolao** [comment]
This also started failing for me today when Wallaby.js updated from core version 1.0.1402 to 1.0.1408 on both my M1 Macbook Pro. I was trying it there because it wasn't working on a friend's linux machine.

Normally the next message tells the user the URL for the web interface, but that message never appears.

**Comment by meanspa** [comment]
I also appear to be getting this behavior. 

Wallaby v1.0.1408
VSCode
MacOS 13.3.1
2019 Macbook Pro (Pentium)
Vite 4.3.4

**Comment by smcenlly** [comment]
@bhvngt - thanks for reporting the problem. Yesterday we added support for `node.js` `v20.0.0` and for some reason the updated approach to ES Module support in node v20 broke our integration for earlier versions of node. For some reason our spawned processes don't exit in earlier versions of node, but they do in the latest version of node.

A new release is available to fix the problem. Please update to Wallaby core `v1.0.1409`, it should fix the issue.
