### ISSUE TITLE
Report warnings emitted by React

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#321]
React emits warnings, such as:

```
Warning: Failed propType: Invalid prop `x` of type `string` supplied to `Foo`, expected `number`.
```

It would be nice to see them pop up inside atom editor, just like `console.log` output.

If the text cannot be made to appear inline with the source, then display it in the wallaby.js panel.

**Comment by ArtemGovorov** [comment]
Could you please share a sample where I could get the warning?

**Comment by epsitec** [comment]
See epsitec-sa/react-usage@ce5cea9c15c7c4cc1f4848b29f8c64a7bc5b49bc

Running `npm test` from the console outputs two warnings:

![react-usage](https://cloud.githubusercontent.com/assets/3872435/10964443/771dc1ce-83a7-11e5-9adf-21a27a105d42.png)

See file `test\React.Component-usage.spec.js` at line 94-106.

**Comment by epsitec** [comment]
When running the test from wallaby.js I see that `console.error` does not get called, which is a surprise to me. Could there be an issue with how the tools get different configuration options when run from the console, and that React behaves in a different way, accordingly?

**Comment by ArtemGovorov** [comment]
Actually wallaby does capture the warnings, it just doesn't display all console output in one place (just like it doesn't display a list of all tests - just failing ones). There's the feature request - https://github.com/wallabyjs/public/issues/79 that may address it.

For now you may see the warnings if your test is failing:
![screen shot 2015-11-05 at 7 38 56 pm](https://cloud.githubusercontent.com/assets/979966/10964924/87054578-83f5-11e5-817a-92800df858bd.png)

Or you may inspect the output for any test (including passing) like this:
![n](https://cloud.githubusercontent.com/assets/979966/10965041/16bc8f14-83f6-11e5-9b8e-78a465f8d041.gif)

Does it address the raised issue (considering the future plan to somehow output [all console output in one place](https://github.com/wallabyjs/public/issues/79))?

**Comment by ArtemGovorov** [comment]
There's also a plan to add Test Explorer https://github.com/wallabyjs/public/issues/144 that will display the list of all tests, we may include the output from all tests (in one place) there as well so it'd look like in mocha report.

**Comment by epsitec** [comment]
Yes, I think issue #79 would be a step forward.

However, I don't seem to be getting the same results as you do in your screen shots.

In my case, I see that running the unmodified tests (expecting `2` calls to `console.error()`) fails, `console.error` being called zero times:

![wallaby-1](https://cloud.githubusercontent.com/assets/3872435/10965382/df0a8588-83ac-11e5-9085-208e2c40efe2.png)

I am running on atom, on a Windows x64 machine.

**Comment by ArtemGovorov** [comment]
I think it's react caching issue. By default wallaby tries to re-use node processes, but react seems to cache something that causes subsequent test runs to fail.
You may have a [look here for more details](http://wallabyjs.com/docs/integration/node.html#node-process-reuse).
Try adding `recycle: true` to see if it helps.
``` JavaScript
module.exports = function () {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],
    ...
    workers: {
      recycle: true
    }
  };
};
```

This way wallaby will be re-creating node processes (just like mocha and other runners). 

As an alternative, you may try finding out what package is causing issues and removing it from the cache in bootstrap function. For example, try removing `react` from the cache and see if the issue persists. If you find the module that causes the caching issues, removing it from the cache will be faster then using `recycle: true`.

``` JavaScript
module.exports = wallaby => {
  return {
    ...
    bootstrap: function (w) {
      Object.keys(require.cache)
              // you may try only resetting cache for specific modules
              // by filtering them by name
              .filter(function (k) { return ~k.indexOf('react'); })
              .forEach(function (k)  { delete require.cache[k]; });
      ...
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
After a bit of playing, this seem to fix the issue while still allow to re-use node processes
``` JavaScript
    bootstrap: function () {
      // See http://wallabyjs.com/docs/config/bootstrap.html
      console.log ('Setup wallaby');
      Object.keys(require.cache)
        .filter(function (k) { return ~k.indexOf('react/'); })
        .forEach(function (k)  { delete require.cache[k]; });

      require ('./test/test_helper');
    },
```

**Comment by ArtemGovorov** [comment]
BTW, maybe there's some other cleaner way to actually clear/reset react DOM in `afterEach`, but I'm not an expert in that area.

**Comment by epsitec** [comment]
Indeed, `recycle: true` worked for me, but the testing feed-back loop got moch slower.

Then I tried your suggestion to delete entries in the `require.cache`. It works for me and is only somewhat slower as the one which keeps react in the cache. But as I need to support both Windows and Mac, I have to accept both `/` and `\` as file separators:

```js
    bootstrap: function () {
      // See http://wallabyjs.com/docs/config/bootstrap.html
      console.log ('Setup wallaby');

      Object.keys (require.cache)
        .forEach (function (k) {
          if ((k.indexOf ('\\react\\') > -1) || (k.indexOf ('/react/') > -1)) {
            delete require.cache[k];
          }
        });
      require ('./test/test_helper');
    },
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update Pierre.
`recycle: true` provides the best isolation, but, yes, comes with the cost of restarting node process.

I'll close this issue as it'll be addressed by other referenced issues.

**Comment by ArtemGovorov** [comment]
Oh, BTW, you may also use [`require('path').sep`](https://nodejs.org/api/path.html#path_path_sep):
``` JavaScript
if ((k.indexOf (require('path').sep + 'react' + require('path').sep) > -1)) {
            delete require.cache[k];
          }
```

**Comment by szarouski** [comment]
I didn't run into original issue, but thought that it might be a good idea to use this code to prevent future issues, but I did run into a different issue instead: https://github.com/facebook/react/issues/5538.
So for now I just removed this code. Hope I'll never run into original issue :)

**Comment by ArtemGovorov** [comment]
@szarouski Interesting, thanks for the note!

BTW, regarding the original issue, wallaby.js now has the [`reportConsoleErrorAsError` setting](https://wallabyjs.com/docs/config/overview.html#report-consoleerror-as-test-run-error). When set to `true`, it'll report tests as failed if the test itself or any code that the test covers does `console.error(...)`, even if there're not other failed assertions. It's useful for React emitted warnings if you'd like to see tests that are causing the as failing.
