### ISSUE TITLE
Support ignore comments

### ISSUE THREAD

**Issue by azat-io** [wallabyjs/public#3213]
Hi there!

I'm using Vitest with [c8](https://github.com/bcoe/c8) tool for counting code coverage.

In c8 you can use comments to ignore uncovered code lines:
https://github.com/bcoe/c8/blob/main/README.md#ignoring-uncovered-lines-functions-and-blocks

Could you add c8 comments support to Wallaby?
It doesn't look good at the moment and frankly is even a little distracting.

<img width="805" alt="image" src="https://github.com/wallabyjs/public/assets/5698350/e47875ee-8b51-47ef-8a08-29bd96b0fd44">

Thank you for your awesome project!

**Comment by ArtemGovorov** [comment]
Hello,

There are a couple of options you may choose from:
- Wallaby supports [`/* ignore coverage */`](https://wallabyjs.com/docs/config/coverage.html) comment by default that you may use next to c8 comment to separately control ignoring coverage from c8 and wallaby.
- It's also possible to [configure Wallaby to respect any coverage ignore comments of your choice](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file). 

So to ignore coverage in both c8 and wallaby at the same time with a single comment, you may [override default automatic config](https://wallabyjs.com/docs/integration/vitest.html#overriding-automatic-configuration) and add the following wallaby config file:

```js
module.exports = () => ({
  autoDetect: true,
  hints: {
    ignoreCoverageForFile: /c8 ignore/
  },
});
```

**Comment by ArtemGovorov** [comment]
Also, we have added the `c8 ignore` hint to be a part of Wallaby default hints, so after updating your Wallaby Core 
[to the latest version 1.0.1420](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), no config changes is required and it should just work for you.
