### ISSUE TITLE
Loading Jasmine helpers via files or test fails

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#3219]
I have set up a project for node testing using Jasmine and Wallaby.

When I execute `npm test`, all tests passed as expected.
However, not all tests pass in Wallaby, as it seems the custom matcher does not get loaded.

Here is a copy of my Jasmine configuration file: `jasmine.json`. 

```json
{
  "spec_dir": "test",
  "spec_files": ["**/*[tT]est.?(m)js"],
  "helpers": ["helpers/**/*.?(m)js"],
  "env": {
    "stopSpecOnExpectationFailure": false,
    "random": true
  }
}
```

Here is a copy of the `helper.js` file:

```javascript
beforeEach(function () {
  jasmine.addMatchers({
    toBePlaying: function () {
      return {
        compare: function (actual, expected) {
          const player = actual;

          return {
            pass: player.currentlyPlayingSong === expected && player.isPlaying
          };
        }
      };
    }
  });
});
```
Here you can see all test pass when running `npm test`:

![image](https://github.com/wallabyjs/public/assets/3672126/d79bcb82-c646-44f4-bd61-d98e101ccf62)

Here is also a copy of my wallaby configuration: `wallaby.js`:

```javascript
module.exports = function (wallaby) {
  return {
    files: ["src/**/*.mjs", "test/helpers/helper.js"],
    tests: ["test/**/*.mjs"],
    testFramework: "jasmine",
    env: {
      type: "node",
      runner: "node",
    },
  };
};
```

And here you can see a screenshot of the tests not passing in Wallaby:

![image](https://github.com/wallabyjs/public/assets/3672126/295109fe-782a-4162-9a16-7383d6d909d6)
**Note:** I have tried adding the path to the `helper.js` file in both the `files` and the `tests` section with no success

I am using a Windows machine with VS Code.

Also, both my source and test files have the extension `.mjs` while the helper only has the extension `.js`

What am I missing here? Please help!

**Comment by smcenlly** [comment]
When Wallaby runs your Jasmine tests, it uses its own configuration file and does not know about your `jasmine.json` configuration. To add your custom matcher, you will need to configure Jasmine in Wallaby's setup function. 

The setup function in Wallaby allows you to configure your testing framework before your test run starts​. Here's an example of how to use it:

```javascript
module.exports = function (wallaby) {
  return {
    // Note: we've removed `helper.js` from here as it doesn't need to 
    // be processed or instrumented by Wallaby.
    files: ["src/**/*.mjs"],

    tests: ["test/**/*.mjs"],
    testFramework: "jasmine",
    env: {
      type: "node",
      runner: "node",
    },

    // Added `setup` function to configure jasmine
    setup(wallaby) {
      const jasmine = wallaby.testFramework;
      const path = require('path');

      // configure jasmine with helper and other settings from `jasmine.json`
      const helperFile = path.join(wallaby.localProjectDir, 'tests', 'helpers', 'helper.js');
      jasmine.loadConfig({
        random: true,
        stopSpecOnExpectationFailure: true,
        helpers: [
          helperFile
        ]
      });
    }
  };
};
```

In the setup function we access `jasmine` testing framework from the `wallaby` object and then use the `jasmine.loadConfig` method provided by Jasmine to specify your configuration.

For more information, you can refer to the [Wallaby's setup function documentation](https://wallabyjs.com/docs/config/bootstrap.html) and [Jasmine's loadConfig documentation](https://jasmine.github.io/setup/nodejs.html).

This should fix your issue; if you have any other problems, let us know.

**Comment by FlippieCoetser** [comment]
Problem resolved! Everything is working as expected!
