### ISSUE TITLE
Upgrading from Webstorm to Freedom license

### ISSUE THREAD

**Issue by prabinv** [wallabyjs/public#322]
Hi, We have company seat licenses for Wallaby.js for Webstorm. Since some of the developers are using Atom as their primary editor of late, we wanted to see if we can move to a freedom license. Is there an upgrade path for the license, or do we have to buy new freedom licenses?

**Comment by ArtemGovorov** [comment]
Hello,
please send me an email to wallabyjs@gmail.com with a number of developers using Atom and we'll take it from there.
