### ISSUE TITLE
Fail to load .json via fetch

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#3223]
The following code snippet is a copy of what is defined in `index.js`:  

```javascript
import { JSONLoader } from "../JSONLoader.js";

let json = await JSONLoader.load("../test.json");
console.log(json);
```  

The `index.js` is referenced in a script tag in `index.html` and is used to load `test.json`.  
  
The `JSONLoader.js` contains the following code:  

```javascript
export class JSONLoader {
  static async load(jsonPath) {
    try {
      const response = await fetch(jsonPath);
      const json = await response.json();

      return json;
    } catch (error) {
      console.warn("Error fetching external JSON:", error);
    }
  }
}
```
**All of this works as expected in the browser**: I can see the `test.json` file contents directly in the console.  

However, when I add the `JSONLoader.js` and the `index.js` file in the files section of `wallaby.js`, wallaby fails.
I am unsure if I specify the correct path, given that Wallaby runs in a sandbox.

As part of my investigation, I also noticed in the Wallaby [documentation ](https://wallabyjs.com/docs/config/files.html#files)   that it is also possible to directly specify a `.json` file. However, I cannot find any working examples.

I need help with this:
1. Support to solve the problem explained above using the provided code snippets
2. A working example of using Wallaby's ability to directly import `.json` files as mentioned in the documentation can be used.

**Comment by smcenlly** [comment]
We have created a [sample project](https://github.com/wallabyjs/wallaby-3223) that you may refer to that shows how to load a JSON file with Wallaby when your tests are running in the browser with ES Modules.

Unfortunately without a complete sample of your application, and without knowing how your tests are running outside of Wallaby, we can't provide more specific advice.

If you would like to create and share a complete sample that's not working for you, we'd be happy to take a look for you. Please be sure to describe how you are running your tests outside of Wallaby.

I'm going to close this issue for now as I believe our sample will help you solve your problem. If you're still having issues, feel free to reply and we'll re-open the issue.

**Comment by FlippieCoetser** [comment]
@smcenlly thank you for the example project. I have tried to use the exact mechanism for my project, but I failed.
In VS Code, the Wallaby test results do not show up:  

![image](https://github.com/wallabyjs/public/assets/3672126/d84c897d-c2da-4a2f-b602-156dfd6415fe)  

Here is a link to the project that I use: [Project](https://github.com/FlippieCoetser/test)

In the last commit, I remove the `JSONLoader.js` and `test.json` from the `files` section in `wallaby.js`.
In VS Code, the Wallaby test results do show up:

**Comment by smcenlly** [comment]
Thanks for the sample repo. I got this working by changing your `wallaby.js` configuration to:

```diff
module.exports = function (wallaby) {
  return {
    files: [
      "importmap.js",
+     "JSONLoader.js",
+     "test.json",
      "src/**/*.ts",
      "node_modules/@browser-modules/browser.template/lib/*.js",
    ],
    tests: ["test/*.ts"],
    trace: true,
    compilers: {
      "**/*.ts": wallaby.compilers.typeScript({
        module: "es2020",
        target: "es2020",
        sourceMap: true,
        inlineSources: true,
      }),
    },
  };
};
```

To include it in your tests, I changed `./test/Index.test.ts` to similar code that you had in `demo/index.js`:

```diff
import { Calculator } from "../src/Index.js";
+ import { JSONLoader } from "../JSONLoader.js";

describe("Given Calculator imported", () => {
  it("Then Calculator should exist", async () => {
    expect(Calculator).toBeDefined();    
+   let json = await JSONLoader.load("../test.json");
+   console.log(json);
  });
...
});
```

---

If you're still having problems, can you please update the repo so I can see it failing when Wallaby runs your tests. Please make sure that in this case, `npm run test` is also working; if not, please get that working first.

**Comment by FlippieCoetser** [comment]
@smcenlly I managed to get everything working. Thank You for the help!  

After experimenting, I noticed the file order made a difference.  

**This works**
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      "importmap.js",
      "JSONLoader.js",
      "test.json",
      "src/**/*.ts",
      "node_modules/@browser-modules/browser.template/lib/*.js",
    ],
    tests: ["test/*.ts"],
    trace: true,
    compilers: {
      "**/*.ts": wallaby.compilers.typeScript({
        module: "es2020",
        target: "es2020",
        sourceMap: true,
        inlineSources: true,
      }),
    },
  };
};
```

**This does not work**
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      "JSONLoader.js",
      "test.json",
      "importmap.js",
      "src/**/*.ts",
      "node_modules/@browser-modules/browser.template/lib/*.js",
    ],
    tests: ["test/*.ts"],
    trace: true,
    compilers: {
      "**/*.ts": wallaby.compilers.typeScript({
        module: "es2020",
        target: "es2020",
        sourceMap: true,
        inlineSources: true,
      }),
    },
  };
};
```

Looking at the contents of the files, the `importmap.js` is a plain javascript file with no `import` or `export` statements. However, the `JSONLoader.js` do use an `export` statement. This makes me believe the two files are loaded differently into the sandbox. This is why the order of the files listed in `wallaby.js` is essential. Can you confirm if my understanding is correct?

Once again, thanks for the help. You may also close the issues.

**Comment by smcenlly** [comment]
You will find that when you change the order of your imports in `karma.conf.js`, you get the same problem.

Based on your project code, this appears to be expected. You are importing `importmap.js` as your first import (in `karma` and Wallaby), which adds an [`importmap`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) to the head of your document. The import map, will resolve `@browser-modules/browser.template` as `./node_modules/@browser-modules/browser.template/lib/Calculator.js`.

This import is used in `src/Index.ts`:

```typescript
export { Calculator } from "@browser-modules/browser.template";
```

If the import map hasn't been added, then the resolution of `@browser-modules/browser.template` fails because this is simply an alias that hasn't yet been defined.
