### ISSUE TITLE
Project is not associated with a valid GitHub project.

### ISSUE THREAD

**Issue by smcenlly** [wallabyjs/public#3228]
When I select that, I got:

```
Wallaby.js has been stopped because your project is not associated with a valid GitHub project.
```

_Originally posted by @unional in https://github.com/wallabyjs/public/issues/2970#issuecomment-1571474597_

**Comment by smcenlly** [comment]
@unional - if you are getting this error, you must be using our open source license.

Can you please provide us with your GitHub repo for your project and describe the steps you are taking to reproduce your error?

**Comment by unional** [comment]
It's https://github.com/unional/type-plus

**Comment by unional** [comment]
It's https://github.com/unional/type-plus

I recently convert it to a monorepo.
What I did is just select the open from the UI

**Comment by smcenlly** [comment]
I'm guessing that you opened the `type-plus` sub-folder within your repo and tried to start Wallaby there?

For open source projects, Wallaby needs to run from the root of your repo.

It also looks like you are using the latest version of `jest` but you are configuring Wallaby explicitly with a configuration file using our [legacy jest integration](https://wallabyjs.com/docs/integration/jest-legacy.html).

The best way to proceed with your project is to get `npx jest` working from the root of your mono repo. Once you have that working, Wallaby should work for you too, and the GitHub project validation will no longer be a problem.

**Comment by unional** [comment]
> I'm guessing that you opened the type-plus sub-folder within your repo and tried to start Wallaby there?

Not really. I'm opening the git repo itself, not a sub-folder.

> The best way to proceed with your project is to get npx jest working from the root of your mono repo.

yes, `npx jest` doesn't work at the root because I don't run jest at the root. It's a per package thing.

For example, repository like this: https://github.com/justland/just-web-react

using `vitest` or `jest` depends on the package.

That the root, I use `turborepo` and run `turbo run test` instead.

**Comment by smcenlly** [comment]
If you are using our Open Source license, you are limited to starting Wallaby on the root of your project only.

There is a feature request to add support for nested projects: https://github.com/wallabyjs/public/issues/2521, but this is not on our short term roadmap.

**Comment by unional** [comment]
I see. thx
