### ISSUE TITLE
How to run jasmine-node tests

### ISSUE THREAD

**Issue by johannesjo** [wallabyjs/public#323]
When I try to run tests written with jasmine-node, all of jasmins core functions are not defind like spyOn or even expect.
```
"before each" hook: spyOn is not defined
	at api/auth/authC-spec.js:48

1 failing tests, 0 passing

api/auth/authC-spec.js authC should have the following methods available [1 ms]

	expect is not defined
		at api/auth/authC-spec.js:35
```

Here is the config:
```
module.exports = function ()
{
    return {
        files: [
            'api/**/*.js',
            '!api/**/*spec.js'
        ],
        tests: [
            'api/**/*spec.js'
        ],
        env: {
            type: 'node',
            runner: 'node',
            env: 'NODE_ENV=test'
        }
    }
};

```

**Comment by johannesjo** [comment]
Ok I was able to resolve the issue by using test-framework: jasmine and using jasmine-node@2.0.0. See also: https://github.com/mhevery/jasmine-node/issues/282

Still though jasmine and jasmine-node are not the same and I might run into issues later on.

**Comment by johannesjo** [comment]
I also run into this issue with mongoose models once the tests are run a second time:
```
OverwriteModelError: Cannot overwrite `User` model once compiled
```

That doesn't happen with jasmine-node --autotest

**Comment by ArtemGovorov** [comment]
> Still though jasmine and jasmine-node are not the same and I might run into issues later on.

Yep, I have only tested it with `jasmine` (for node), not `jasmine-node`, so you may find something interesting. Please let me know if you do, I don't yet see any reasons why it shouldn't work and will try to fix it if it doesn't.

> I also run into this issue with mongoose models once the tests are run a second time

Try setting `workers: {recycle: true}` - https://github.com/wallabyjs/public/issues/239

**Comment by johannesjo** [comment]
Thanks for getting back to me so quickly. `workers: {recycle:true}` doesn't do anything for me.

**Comment by ArtemGovorov** [comment]
Interesting, could you please try `workers: {recycle:true, initial: 1, regular: 1}`?
If the suggestion above doesn't help, would it be possible to create a small sample github repo where it works with `jasmine-node --autotest` but doesn't work with wallaby? I definitely would like to find out what is going on.

**Comment by johannesjo** [comment]
That did the trick! Thank you very much. Are these options documented somewhere?

You still need the repo?

**Comment by ArtemGovorov** [comment]
Ok, cool. Yes here is the documentation - http://wallabyjs.com/docs/config/workers.html. The issue is that by default wallaby tries to run your tests in parallel mongoose doesn't seem to like it.

**Comment by ArtemGovorov** [comment]
One possible solution to still allow running your tests in parallel is perhaps using different DBs per worker. You may consider using [wallaby.js bootstrap function](http://wallabyjs.com/docs/config/bootstrap.html) to [set up a DB for worker](https://github.com/wallabyjs/public/issues/256#issue-105951655).

**Comment by johannesjo** [comment]
Good suggestion and good documentation. Was not able to find earlier somehow. 

I might try that at a later point. So far the tests are still running very fast in my current project.

**Comment by ArtemGovorov** [comment]
Awesome, then you probably don't need to bother trying to speed it up right now, but leave the option for later. 
BTW, does it work without `recycle:true`, just with workers set to 1: `workers: {initial: 1, regular: 1}`?

**Comment by johannesjo** [comment]
No it doesn't.

**Comment by ArtemGovorov** [comment]
Cool, good to know, thanks for checking!
