### ISSUE TITLE
Diff file not loading on intellij

### ISSUE THREAD

**Issue by foch01** [wallabyjs/public#3236]
Diff file not loading on intellij v2023.1.3. Version jest : 27.5.1

<img width="1243" alt="2023-06-22_15-08-22" src="https://github.com/wallabyjs/public/assets/19187357/738f2c29-de97-4ec4-b86b-2d0e105225cd">

Do you have the same issue ?

**Comment by smcenlly** [comment]
Thanks for reporting the issue. We've confirmed that is working in older versions of IntelliJ but not the latest.

We're investigating the problem and will provide an update when we have a fix.

**Comment by smcenlly** [comment]
We have identified and fixed the issue with diffs not loading properly. Please update to the latest version of the Wallaby plugin for JetBrains Editors, `v1.0.269` and it should work for you.

**Comment by foch01** [comment]
Thank you for your speed !
