### ISSUE TITLE
[Documentation] Keyboard Shortcut for "Run Back to Breakpoint"

### ISSUE THREAD

**Issue by cfigueiroa** [wallabyjs/public#3241]
Description:
I have identified a small error in the Wallaby.js documentation regarding the keyboard shortcut for the "Run back to breakpoint" feature. According to the documentation page at [time-travel-debugger](https://wallabyjs.com/docs/intro/time-travel-debugger.html#run-back-to-breakpoint-f8), it states that the shortcut is `F8`. 

However, the correct shortcut should be `CTRL + F8`.

![Screenshot](https://github.com/wallabyjs/public/assets/109833612/04f2903a-a932-4e7a-8dee-e0b6daf94f94)

Additionally, I would like to provide constructive feedback regarding this part of the documentation. As a non-native English speaker, I initially found it challenging to understand the functionality of each button at first glance. The presence of numerous buttons can be overwhelming.

I have created a document on [Notion](https://muddy-plain-5c5.notion.site/Wallaby-79b427b5a4624de99ad47903d68ccefb?pvs=4) where I reorganized the buttons for better comprehension. This reorganization aims to make the documentation clearer and more accessible.

**Comment by smcenlly** [comment]
Thanks for letting us know about the error in the default shortcut key in docs. This has been fixed.

Thank you also for your constructive feedback. We'll consider/adjust based on your other feedback when we next rework/revise the page.
