### ISSUE TITLE
Unable to install Wallaby.js in offline mode behind corporate proxy

### ISSUE THREAD

**Issue by FlavienR** [wallabyjs/public#3252]
### Issue description or question
I am currently working behind a corporate proxy and I'm unable to install Wallaby.js in my work environment. I followed the offline installation instructions provided on the Wallaby.js site to perform the installation (https://wallabyjs.com/docs/intro/offline.html), with latestServer version 1.0.1451 and vs code extension version 1.0.364.

When I start VS Code I get the following error: "Error: With wallaby.noAutomaticInstall option set, you need to manually install wallaby core and dependencies when the extension is installed/updated.", which I guess is normal. But when I try to start Wallaby, I get the message: "Wallaby.js is updating and will be starting automatically when the update is complete".
![image](https://github.com/wallabyjs/public/assets/5755585/a998dcdd-ba41-4067-b27e-a3142c389b54)

When I try to activate my license, I'm getting a similar error message.
![image](https://github.com/wallabyjs/public/assets/5755585/778fa674-2fe1-4346-b99d-58cc4c035c4a)

But given that I have set "wallaby.noAutomaticInstall" to true, I don't understand why it's attempting to update. I waited for a while and restarted VS Code but there was no change.

I'm not sure what could be causing these issues and would appreciate any guidance or assistance you could provide.

### Wallaby diagnostics report

Unfortunately, I cannot generate a Wallaby diagnostics report as I am unable to start Wallaby in my project.

Thank you in advance for your help and time. I am looking forward to your response.

**Comment by mburnell** [comment]
Thanks for reporting the issue. I've followed the steps in the instructions and confirmed it works for me, but did come across something I thought could easily trip someone up.

The `LATEST` in `~/.vscode/extensions/WallabyJs.wallaby-vscode-LATEST/wallaby` is not meant to be literal, but rather to refer to the the folder placed there when the plugin was installed (currently `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364`). The previous step involving a version replacement is explicit; I will update the docs so this step is as well. I confirmed "misplacing" the `wallaby` folder will produce the behaviour you reported.

Hopefully this is all that it is. If not, and you've confirmed that your `wallaby` and `wallaby-app` folders are correctly located, please let us know and we'll provide some additional steps to clear your environment and try again.

**Comment by FlavienR** [comment]
Thank you for your response. I actually thought `LATEST` was referring to the latestServer version in the `wallaby.json` file. So I had two folders. But now I put `wallaby `and `wallaby-app` in `~/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.364` and it works great 🎉
Thanks again, have a good day.
