### ISSUE TITLE
question: possible to de-instrument code?

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3257]
I have a situation in which I'm generating taking some code in a test file, stringifying it, then running it via Node.js' `vm` module.  The problem is, of course, that the Wallaby globals aren't present within the execution context, and stuff like `$_$wf` is undefined.

For example

```js
// test.js
function foo() {
  return true;
}

// yes, this does nothing; just an example
vm.runInContext(foo.toString(), someContext);
```

Ideally the source would live in its own file so I could avoid instrumentation, but that's not what I have at the moment.  Could I use [this feature](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) to do it?  Can it ignore an entire object or multiple lines at once?

Failing that, is there a regex I could run across the stringified source to strip the instrumentation out?

**Comment by smcenlly** [comment]
> Could I use [this feature](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) to do it?  Can it ignore an entire object or multiple lines at once?

Yes, this feature will work for you. The coverage hint will ignore all the branches underneath, which means if you have something like:

```javascript
/* ignore coverage */
function foo() {
  return true;
}
```

Then `console.log(foo.toString());` will return the function without any Wallaby instrumentation being applied.

**Important note:** by default Wallaby only applies coverage ignore hints to your application files, and **not** test files. You will need to add `hints.allowIgnoreCoverageInTests` with a value of `true` to use the ignore coverage hint in a test. 

**example.spec.js**
```javascript
/* ignore coverage */
function foo() {
  return true;
}

it("should not instrument code", function () {
  foo();
  // will return 'function foo() {\n  return true;\n}
  console.log(foo.toString());
});
```

> Failing that, is there a regex I could run across the stringified source to strip the instrumentation out?

Unfortunately this is not an option as we've modified the AST at this point and there's no simple way to strip out our instrumentation. If you get stuck, one possible option would be mock the functions that we call out to, but this would be brittle and is not something we can support / guarantee will work in the future.

**Comment by boneskull** [comment]
Thanks, I was wondering why it wasn't ignoring coverage in test files :D

**Comment by boneskull** [comment]
(maybe ignoring coverage in test files should be allowed by default, because it's rather surprising behavior...)

**Comment by smcenlly** [comment]
Yes, I don't disagree. Will talk it over with the team and consider changing the default.

**Comment by smcenlly** [comment]
Sorry, also there was a typo in the name I gave you: `allowIgnoringCoverageInTests` is the hint setting.

**Comment by smcenlly** [comment]
The reason this setting exists is because ignoring coverage in test files can wipe out most if not all Wallaby features, and may come as a surprise for a user with some existing comments from Istanbul for example.

In the future, we may consider detecting ignore coverage comments and warning with the suggested setting to use.
