### ISSUE TITLE
"Connection refused: connect" error when trying to use Wallaby.js on Win11+WSL2+Ubuntu inside Webstorm

### ISSUE THREAD

**Issue by denizoguz** [wallabyjs/public#3259]
### Issue description or question

I have migrated my development environment from Mac to Windows+WLS2. The only missing part is Wallaby.js, it is not working. I can run the tests using Jest. I have already setup Wallaby.js as outlined here, https://wallabyjs.com/docs/intro/get-started-jetbrains.html . I have "Use WSL" active and I have selected a node.js executable manually. {SYSTEM_DEFAULT} doesn't detect the nodejs. I'm using nodejs through nvm by the way. I'm attaching the configuration screenshot too.

I have run the specified firewall rule. Here is the output of Get-NetFirewallRule -DisplayName 'WSL'. I have actually 3 of them. 

```
Name                          : {257a00a3-eb23-40f4-908c-aea1680b58a8}
DisplayName                   : WSL
Description                   :
DisplayGroup                  :
Group                         :
Enabled                       : True
Profile                       : Any
Platform                      : {}
Direction                     : Inbound
Action                        : Allow
EdgeTraversalPolicy           : Block
LooseSourceMapping            : False
LocalOnlyMapping              : False
Owner                         :
PrimaryStatus                 : OK
Status                        : The rule was parsed successfully from the store. (65536)
EnforcementStatus             : NotApplicable
PolicyStoreSource             : PersistentStore
PolicyStoreSourceType         : Local
RemoteDynamicKeywordAddresses : {}
PolicyAppId                   :
```
![image](https://github.com/wallabyjs/public/assets/1111203/b6961ebb-bd35-49c6-8128-ac0dd7afc0b9)

### Wallaby diagnostics report
Wallaby.js is in running state. Stop button is active, below error is displayed in Jetbrain's notification popup. But "Copy Diagnostics Report" is grayed out. 

```
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:473)
	at com.wallaby.javascript.extendedCore.Client.q(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by smcenlly** [comment]
Can you please try temporarily disabling your Firewall to see if it is the cause of your problem? if so, refer to your firewall docs to see how to identify blocked traffic and how to configure it to allow Console Ninja.

If you are using a VPN, can you also try disconnecting from it in case that is causing a problem?

**Comment by denizoguz** [comment]
Hi,
I had forgotten to mention this detail. I had already tried that. But I have just checked it again, Firewall turned off. Still the same.

![image](https://github.com/wallabyjs/public/assets/1111203/76144001-a397-4130-9e8b-f9d69ace25b6)

I have noticed that something strange about how Wallaby.js expects path of the WSL Node.js. If I select it using "..." menu, the path has "\\wsl$\Ubuntu\" prefix. But, in this case, I get "Can not start node.js" process notification. If I remove "\\wsl$\Ubuntu" prefix, it starts. Wallaby console shows "wallaby.js started" message. But then, connection error notification pops up and tests are not executed.

**Comment by smcenlly** [comment]
We set up a new Windows machine instance with WSL. This is our configuration, and everything is working for us:

<img width="1557" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/d59cb53c-7881-4cfe-9d35-5e7f44744b79">

Our firewall settings are:

<img width="1123" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/b93e8bce-c564-4b74-959a-781a9c1ed9f1">

(Note: we ran the PowerShell command, `New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow` as per our docs)

---

**The `node.js` path is using Windows path, which I think is going to cause problems. Can you please change the backslash to forward slash? It may fix the problem.**

If you're still having problems after trying that, please let us know.

**Comment by denizoguz** [comment]
Hi, 
Unfortunately it didn’t work. It automatically reverts to back slashes on save (ok). I’m not sure this behavior is normal. If you provide me a debug build, I can install it. Obviously, something is wrong in my environment. But, there could be other users having the same issue in the future. If you want we can also make a screen sharing session.

**Comment by smcenlly** [comment]
That's strange, we don't have the same behavior. It may do this if `Use WSL` is `No`, but it shouldn't do this if `Use WSL` is `Yes`.

Can you please try editing your Run Configuration file directly instead? It should be in a folder in your project root similar to `.run/WallabyTimesheel.run.xml`. The contents should look something like:

```xml
<component name="ProjectRunConfigurationManager">
  <configuration 
    default="false" 
    name="Wallaby" 
    type="wallaby" 
    factoryName="wallaby" 
    configType="Automatic" 
    configFolder="$PROJECT_DIR$" 
    node="/home/user/.nvm/versions/node/v18.16.0/bin/node" 
    wsl="Yes" 
    SmartStart="No">
    <method v="2" />
  </configuration>
</component>
``` 

Please update the `node` property with the correct slashes, and ensure that `wsl` is set to `Yes` (**not** `No`).

**Comment by denizoguz** [comment]
Here is my configuration. It writes "wallaby.js started" on the "Wallaby console" and Webstrom's error notification pop's up.
Here all the versions on my computer:

```
<component name="ProjectRunConfigurationManager">
  <configuration
    default="false"
    name="Wallaby Forge"
    type="wallaby"
    factoryName="wallaby"
    configType="Automatic"
    configFolder="$PROJECT_DIR$"
    node="/home/denizoguz/.nvm/versions/node/v16.13.1/bin/node"
    wsl="Yes"
    SmartStart="No">
    <method v="2" />
  </configuration>
</component>
```

```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134
```

```
Docker version 24.0.5, build ced0996
```
```
WebStorm 2023.2
Build #WS-232.8660.143, built on July 21, 2023
Licensed to Deniz Oguz
You have a perpetual fallback license for this version.
Subscription is active until September 27, 2024.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    wallaby.js (1.0.270)
    com.github.copilot (1.2.18.2908)
    quokka.js (1.0.391)
    Key Promoter X (2023.2.0)
    ru.adelf.idea.dotenv (2023.2)
```

**Comment by smcenlly** [comment]
Thanks for providing the version information. We were still using `WebStorm 2023.1`.

It looks like something has broken Wallaby's integration with WSL in the latest version of WebStorm. We're not sure what the issue is at this point in time or how we can fix it.

While we're investigating, if you downgrade to `WebStorm 2023.1`, it should work for you.

**Comment by smcenlly** [comment]
It seems that the latest version of WebStorm has introduced a delay in the automated port mapping between your WSL instance and your Windows machine. This causes Wallaby to fail to connect to your WSL instance to run your tests. We're not sure the reason for this change, but we have updated the latest version of Wallaby to fix the problem.

Please update your [Wallaby editor plugin](https://plugins.jetbrains.com/plugin/15742-wallaby) to `v1.0.274+`, it should fix your problem.
