### ISSUE TITLE
Add copy support for console.log output

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#326]
In Webstorm in popup wallaby.js menu (with bulb) new dynamic menu item: copy console output:

```
console.log(uuid.v4())   afe9a2b8-df71-4f0c-8598-219103be6b0f  <-- This output should be copied in buffer
```

Optional features: 
- copy output with code line content
- copy selected code with console output
- if code line with `console.log` has been runned twice or more times - it should be outputted/copied  messages from all calls. Also wallaby should  visually group output from console by (`file name`, `line number`)

**Comment by ArtemGovorov** [comment]
Good idea, I have been missing something like this as well.

**Comment by hellboy81** [comment]
As I mentioned in some cases copy as markdown/plain text is much more better as copy as picture ;-)

**Comment by hellboy81** [comment]
Hm... Why `console.log` output is not piped to `Wallaby Console` in error case?

I should still run `mocha` console runner to copy it.

**Comment by ArtemGovorov** [comment]
`console.log` is not normally piped to `Wallaby Console`. It's only piped to `Wallaby Console` if it's outside any tests so there's nowhere else to pipe it. You may use `Failing tests` or `Show line test(s)` action to display `console.log` for any selected test.

**Comment by smcenlly** [comment]
Wallaby's [`Copy Value` feature](https://wallabyjs.com/docs/intro/advanced-logging.html#show-value--copy-value) addresses this feature request.
