### ISSUE TITLE
Test Output formatting is wrong in VSCode

### ISSUE THREAD

**Issue by OClement** [wallabyjs/public#3260]
### Issue description or question

Formatting of errors seems incorrect/mangled with escape/control characters:
eg:
> ‌[Error] Test run failure: [96mfeatures/main/src/lib/manage/map/map.service.spec.ts[0m:[93m32[0m:[93m51[0m - [91merror[0m[90m TS2345: [0mArgument of type '(status: LoadingStatus) => void' is not assignable to parameter of type '(value: unknown) => void | PromiseLike<void>'. 

Where ` ` appears as `esc escape ctrl-[` when pasting it into [unicodelookup.com](https://unicodelookup.com/#%1B/1)

I've had this issue on multiple fresh installs of VSCode / Wallaby
Using MacOS 13.4

### Wallaby diagnostics report
No Relevant / cannot paste due to it including private informations

**Comment by smcenlly** [comment]
I understand you don't want to share your Wallaby Diagnostics for privacy reasons, however, it contains some important information that will allow us to diagnose your problem, including your Wallaby version, your project dependencies, and project configuration.

If you're not comfortable sharing it publicly, could you please email it to us: hello@wallabyjs.com?

If there are any personal details in the report (e.g. in your log entries, or path names), please feel free to redact them.

Alternatively, you may provide us with a new sample repo without any private project details that has the same problem.

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. If you email us or reply with the details requested, we will re-open the issue.
