### ISSUE TITLE
No Tests or Inconsistent Tests Found in NPM Workspace Mono

### ISSUE THREAD

**Issue by jessejamesrich** [wallabyjs/public#3268]
### Issue description or question

I'm using Wallaby for the first time with the explicit purpose of getting test reports working in VSCode. I had initial success, but as I continued on Wallaby became increasingly sporadic in its reporting and eventually I just ended up with "No tests have been found in this workspace." Forgive me, I'm new to a lot of this, so I'm unclear if this is indicating an issue with Wallaby, VC Code, or me (it's probably me), but I can confirm from the console that my tests are running without issue there. 

```
[log]  Test Files  55 passed (55)
[log]       Tests  55 passed (55)
[log]    Start at  10:26:30
[log]    Duration  6.42s (transform 1.27s, setup 0ms, collect 5.79s, tests 132ms)
[log]
[log] 
 PASS  Waiting for file changes...
[log]        press h to show help, press q to quit
```

Here's what I'm working on.

Vite 4.4.9
Vitest 0.28.5
VsCode: 1.82.0

vite.config.js

```...
 test: {
      globals: true,
      environment: "jsdom", // browser
      // name: "...",
      include: ["**/.tests/index.jsx", "**/.tests/index.js"],
      exclude: ["node_modules"],
      threads: false,
    },
    ...
```

I've attempted to use a wallaby.js file:

```
/** @format */

export default () => ({
  autoDetect: true,
  trace: true,
  include: ["**/.tests/index.jsx", "**/.tests/index.js"],
});
```

I've attempted in the same breath to use my package.json file to do this work, but no luck. 

Of note, this is a workspace, so tests are deeply nested under the packages folder and as you can see they are and will likely continue to be rather simple single test for single file located always under ./tests/index.jsx. 

VS Code doesn't seem to dig Wallaby at all as time goes on, so I can't even seem to generate diagnostics report, or I'm too dumb to figure out where it is. 

I think of interest here is that on initial install (and re-install) I end up with 55 tests (which work sporatically), but time seems to be the enemy of my installation. 55, then 11, then "No tests have been found." 

I've done my best not to bother y'all, but I'm at pulling out my hair stage. I feel I've followed the install and tutorials properly and tried every setting that I think my nudge this into working order, but alas, no luck. Any guidance would be much appreciated. I see the promise in Wallaby. 👍  Happy to attach more info if the immediate cause doesn't stick out from my setup. Thanks in advance.

**Comment by smcenlly** [comment]
Vitest added workspace support in `vitest@0.30.0` ([vitest docs here](https://vitest.dev/guide/workspace.html)). Wallaby does not support running vitest in a mono-repo project structure **before** this version. There have been a number of improvements and fixes to vitest workspace support since `vitest@0.30.0`.

To run Wallaby on your workspace mono-repo, please upgrade to the latest version of `vitest`, `v0.34.4`. You will need to also define a vitest workspace as [described in their docs](https://vitest.dev/guide/workspace.html#defining-a-workspace).

Please also update to the latest version of Wallaby core, `v1.0.1468` as this version includes a number of improvements to our `vitest` workspace integration.

We think that everything will work for you once you have configured the latest version of `vitest` to run as a workspace, and you are using the latest version of Wallaby.

**Comment by jessejamesrich** [comment]
Thank you so much for the quick reply. And thank you for pointing out the version mismatch I was overlooking. As per, I've updated both the core and vitest. After some arm-wrestingly to get vitest back into fighting shape with its own proper config, and assuring the tests were running from the cli (getting the previously mentioned 55 test passing), I continue to have a problem with Wallaby recognizing these as valid tests. 

```
‌0 failing tests, 0 passing  ​Launch Coverage & Test Explorer​ | ​Search Tests
```

vs cli:

```
[log]  Test Files  55 passed (55)
[log]       Tests  55 passed (55)
[log]    Start at  09:30:55
```

I've done a couple things to attempt to address this by working with all combinations of my vitest.workspace.js file:

```
/** @format */
import pluginReact from "@vitejs/plugin-react";
import { defineWorkspace } from "vitest/config";

export default defineWorkspace([
  "packages/*",
  {
    extends: "./vite.config.js",
    plugins: [
      pluginReact({
        babel: {
          // allows import assertions for json
          plugins: ["@babel/plugin-syntax-import-assertions"],
        },
      }),
    ],
    test: {
      globals: true,
      environment: "happy-dom",
      name: "🥳",
      include: ["packages/**/.tests/index.jsx", "packages/**/.tests/index.js"],
      exclude: ["node_modules"],
      threads: false,
    },
  },
]);
```

I would imagine packages/ is superfluous, but attempted that an all others. I eventually started playing with wallaby.js as a config just to see how much headway I could make there. I'm 100% aware, it's not a solution, but it has acted as proof-of-life. 

```
/** @format */

module.exports = function (wallaby) {
  return {
    debug: true,
    trace: true,
    files: [
      "packages/**/src/**/*.js",
      "packages/**/src/**/*.jsx",
      "!packages/**/.tests/index.js",
      "!packages/**/.tests/index.jsx",
    ],
    tests: ["packages/**/.tests/index.js", "packages/**/.tests/index.jsx"],
    exclude: ["node_modules"],
    workers: {
      initial: 6,
      regular: 2,
    },
    compilers: {
      "**/*.js?(x)": wallaby.compilers.babel({
        babel: require("@babel/core"),
        presets: ["@babel/preset-react", "@babel/preset-env"],
      }),
    },
  };
};
```

Using this config does then show the tests in vscode as expected. It's unteanable in that all the vite logic is gonzo, but again - proof of life. At the moment, Wallaby appears unhappy with vitest. I'll take any further advice :) And to confirm, I have assured the versions you've recommended are the ones that have been installed now. 

Thanks again for the quick reply. Very much appreciated. I understand a lot of this is in beta and appreciate the assistance.

**Comment by smcenlly** [comment]
For vitest, you don't need a Wallaby configuration. In fact, your current configuration is specifying to use `jasmine` and to run your tests in `chrome`.

For vitest, you should be able to delete your configuration file and use [Wallaby's Automatic Configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration).

Some specific items to note if for some reason you *do* want a configuration file:
* If specifying `files` and `tests` as an array, you will need to also specify `autoDetect: true` to tell Wallaby to also configure `vitest`. You can read more in [our docs](https://wallabyjs.com/docs/config/files.html#overriding-automatic-configuration). When using automatic configuration, Wallaby will use your `vitest` configuration to find the files and tests.
* The workers setting is not relevant for `vitest`, instead the vitest configuration setting will be used.
* The compilers setting is not relevant for `vitest`, instead the vitest transformation pipeline will be used.

---

If you're still having problem when using automatic configuration, can you please provide a sample project that's not working for you?

**Comment by jessejamesrich** [comment]
Thanks again for the timely response. To clarify, I have no intentions of using a manually configured project using wallaby.js. I was more-or-less implementing it to see if any further insights could be garnered. 

So what I've done today is create a minimal testable project with only one test. I've removed the wallaby.js file and pared down config files all around. It can be found here: https://github.com/jessejamesrich/cv

packages/web is really where the focus is as it's the only test in the system. 

Again, this runs without issue from the cli, but fails to even display in VS Code. 

```
 ✓ |🥳| packages/web/src/components/Home/.tests/index.jsx (1)
   ✓ web/home (1)
     ✓ renders without crashing

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  13:54:23
   Duration  172ms
```

It's difficult for me to speculate where in the entire setup this is hiccuping, but I think this minimal testable is basic enough to show there's something unforeseen happening. 

Thanks again for all the help.

**Comment by smcenlly** [comment]
Thank you for the sample repo. It allowed us to understand why Wallaby wasn't working for you.

There were two issues when running your tests in Wallaby, both issues have been resolved:

1. By default, Wallaby completely ignores files and folders starting with `.`, while `vitest` does not. For `vitest` projects, we have updated Wallaby to have the same behavior.
2. Wallaby was not using the `include`/`exclude` patterns provided for your projects. In your case, this meant that Wallaby was not using the `include`/`exclude` files defined in your `vitest.workspace.js` file.

---

Please update to the latest version of Wallaby core, `v1.0.1469`. After updating, please run the VS Code command,  `Wallaby.js: Reset Wallaby Cache`, then start Wallaby on your project without a configuration file.

_**Note:**_ we couldn't actually get your sample project running as there were some missing files, but if you have further issues, please update the same project for us so it fails on a fresh clone/install and we'd be happy to take a look.

**Comment by jessejamesrich** [comment]
Awesome. I should have mentally noted that a .tests directory by virtue of its name might preset problems. My apologies. 

Indeed, now the tests are showing. I'm going to guess Wallaby is **skipping the environment setting as well**. "ReferenceError: Window is undefined" seems to indicate a browser environment isn't being run. I'm going to hack away at that on my side and will report back if I find there's a workaround on my, but if you see that on your end or have notes regarding environment and Wallaby please let me know. I will push a complete repo of the cv project which will include what I imagine are missing configs breaking the install if that helps. 
 
 Again, a sincere thanks for all your help!

**Comment by smcenlly** [comment]
Thank you for updating the sample repo. With your project configuration, internally vitest has a number of different configuration options/objects that are not homogenous. Some project configurations are specified to run in `node`, and some run in `happy-dom`. Wallaby was matching the configuration for your file based on your project path and configuration path, but this is not quite what `vitest` does internally.

We have updated Wallaby to use `vitest`'s algorithm for finding the correct configuration for your file.

Please update to Wallaby `v1.0.1470`, it should work for you.

**Comment by jessejamesrich** [comment]
Amazing. It's working as expected. Thank you sincerely for your diligent attention and shipping those adjustments.
