### ISSUE TITLE
Map covered line back to test

### ISSUE THREAD

**Issue by vritant24** [wallabyjs/public#3271]
### Issue description or question

I would like to be able to see which test(s) are covering a given line of code.

We have a plethora of tests in our large codbase that can be hard to map to. Having an ability to check which tests are failing on or covering a line of code would be very useful, similar to NCrunch or LiveUnitTesting in VS.
It would also act as a good indication of "add more tests in this file" when working on another teammate's code file.

**Comment by smcenlly** [comment]
Have you seen the `Show Line Tests` command? It sounds like this is what you are after. This will show you all tests covering the line of code.

Our Test filtering feature may also be useful. From [our docs](https://wallabyjs.com/docs/intro/selected-tests.html#test-filtering):

> Wallaby’s Test Filtering feature allows you to limit the display of inline code coverage indicators and inline run-time values to only the test that you are working on instead of all tests in your project.
> 
> Test Filtering allows you to switch focus between individual tests and their execution results instantly. Editor-specific commands are referenced on each editor’s tutorial page ([VS Code](https://wallabyjs.com/docs/intro/get-started-vscode.html#test-focusing), [JetBrains IDEs](https://wallabyjs.com/docs/intro/get-started-jetbrains.html#test-focusing), [Visual Studio](https://wallabyjs.com/docs/intro/get-started-vs.html#quick-actions), [Sublime](https://wallabyjs.com/docs/intro/get-started-sublime.html#test-focusing)). Filter selection can also be toggled within [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html).

Finally, if you haven't seen it, [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html) provides details your project's failing tests, and code coverage.

---

If none of these features help, can you please give us additional information on your exact scenario, what you're doing and what information you want to see?

**Comment by smcenlly** [comment]
Assuming that my reply addressed your issue. If not, please reply and let us know your exact scenario, what you're doing and what information you want to see.

**Comment by vritant24** [comment]
Sorry for the delayed response, missed the notification.

`Show Line Tests` does what I was looking for, thank you!

As a feature request, I would love it if I would be able to see it in the editor without popping out another window. Some suggestions are:
1. a hover window on the coverage glyph in the gutter.
2. an expanded in-editor window similar to the one like in the image below:
    ![image](https://github.com/wallabyjs/public/assets/13074644/89a538f7-07b5-4721-a584-a2a6beb54a51)

**Comment by smcenlly** [comment]
Glad to hear that `Show Line Tests` gave you what you were looking for.

In terms of your suggestion, we're a little constrained in what we can display (based on VS Code API / capability).

For now, we've just added `Show Lines Tests` as a right-click action on the gutter indicator (available in extension version `v1.0.370+`). Of course, now that you know about the command, you can simply run the command, or use the shortcut (default: `Shift+Command+R L`).

In the longer term, we're considering how we may be able to provide additional context-specific information (including tests for a line of code) in an enhanced output window. This is still in the planning stage but I would expect it to address your feature request.
