### ISSUE TITLE
Unable to use Wallaby with expired license

### ISSUE THREAD

**Issue by philipmw** [wallabyjs/public#3275]
(There is no diagnostics report; that menu option is grayed out for me.)

### problem

I have an outdated / expired license of Wallaby. However, I would like to use it somewhat longer before renewing.

I recently set up a fresh laptop, and I installed the Wallaby plugin following the official instructions. This gave me plugin version 1.0.274.

When I try to run it, I get a *Wallaby Notification*:

> Currently installed version of Wallaby.js is not covered by your license. Please visit our website to upgrade your license.

I tried to downgrade Wallaby by downloading the last plugin version within my license time window. My license expired in December 2022, so I downloaded plugin version 1.0.253, dated September 2022.

When I try to run this older version, I get an *Error running*:

> 'com.intellij.execution.ui.layout.LayoutViewOptions com.intellij.execution.ui.layout.LayoutViewOptions.setTopToolbar(com.intellij.openapi.actionSystem.ActionGroup, java.lang.String)'

Now I am out of ideas for how I can set up Wallaby compatible with my expired license. Please advise.

### IDE

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
Licensed to {{redacted}}
Expiration date: October 1, 2023
Runtime version: 17.0.8+7-b1000.22 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    wallaby.js (1.0.274)
    {{redacted}}
    IdeaVIM (2.5.1)
    {{redacted}}

Kotlin: 232-1.9.0-IJ9921.47

**Comment by philipmw** [comment]
I believe I have it working now -- the missing last step was to let IntelliJ update plugins. Somehow, upgrading from 1.0.253 back to 1.0.274 (which earlier gave me an error) solved the problem.

Now Wallaby runs as expected, telling me that my free upgrades period has expired.

I am leaving this issue open in case you want to make any UX improvements in this area, but I consider my problem solved.

**Comment by ArtemGovorov** [comment]
Hi,

> I tried to downgrade Wallaby by downloading the last plugin version within my license time window.

Wallaby plugin itself is evergreen, so there's no need to install older versions for licensing purposes. Wallaby Core component (that is versioned separately from the plugin) is automatically updated to the version that your license covers. This should have happened when you applied your license details in the freshly installed version of Wallaby on your new laptop for the first time. We will investigate why it didn't download the correct version for you.
