### ISSUE TITLE
subpath imports: how should they work?

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3289]
### Issue description or question

I have a Node.js + TS project using Node.js' subpath imports.  e.g. `package.json`:

```json
{
  "imports": {
    "#internal": "./dist/internal.js"
  }
}
```

TypeScript is able to understand this--it figures out that `./dist/internal.js` was compiled from `./src/internal.ts`.

However, Wallaby _doesn't_ make this connection automatically; it complains about e.g., `dist/internal.js` not found (because it's not in my `files` list).  To get this to work, I added this to my Wallaby config:

```js
module.exports = {
  files: [
    'src/*.ts',
    {pattern: 'dist/internal.js', instrument: false} // <---
  ],
  tests: [
    'test/*.spec.ts'
  ],
  env: {
    type: 'node'
  },
  testFramework: 'mocha'
}
```

With the above, Wallaby can now execute the test which references `#internal`.  _However_, it does _not_ generate any coverage for the `src/internal.ts` source file which generates `dist/internal.js`, even though it's in my list of files.  Is there anything to be done about this?

[Here's the before/after diagnostics reports](https://gist.github.com/boneskull/be6715dcc5c85a8c27e0d8a1e805a104)

**Comment by smcenlly** [comment]
Based on your diagnostics report, I assume that [this is the project](https://github.com/boneskull/midnight-smoker) where you have are having issues?

> TypeScript is able to understand this--it figures out that ./dist/internal.js was compiled from ./src/internal.ts.

Technically, it's `ts-node` doing this (e.g. [see here](https://github.com/TypeStrong/ts-node/blob/c06cbe7d83b5585bb24f9963c42ce13eadd2202f/dist-raw/node-internal-modules-cjs-loader.js#L478)).

With your configuration, when Wallaby runs your tests, it first compiles all of your project code to JavaScript using the TypeScript compiler, and then it runs your tests using `node`. In contrast, when your code is running from the command-line, it's running in `ts-node` at runtime, which inspects your `package.json` `imports` directive and re-writes the module resolution dynamically at runtime with its custom ESM loader.

> However, it does not generate any coverage for the src/internal.ts source file which generates dist/internal.js, even though it's in my list of files. Is there anything to be done about this?

This is expected. To have Wallaby run the file from your source directory (and not your `dist` folder), you will need to implement a [custom loader](https://nodejs.org/docs/latest-v18.x/api/esm.html#loaders) that resolves `/dist/*` to the appropriate source location. You then need to tell Wallaby to use your customer loader in your configuration file:

```javascript
...
    env: {
      // Tell Wallaby to run your tests with your loader loader
      params: {
        // This needs to be the fully-qualified path
        runner: "--experimental-loader " + path.join(__dirname, 'custom-loader.mjs')
      }
    },
...
```

**Comment by smcenlly** [comment]
I'm going to close this issue as I believe this addresses your question. If you have any other questions or problems, feel free to reply and we'll re-open if necessary.

**Comment by boneskull** [comment]
@smcenlly Maybe a custom loader implementation that handles this would make a good "example".  I can imagine my situation becoming more common as projects adopt subpath imports.

**Comment by smcenlly** [comment]
I have created a [small repo](https://github.com/wallabyjs/wallaby-3289) for you that you will be able to use as an example for how to show coverage on your files.

Firstly, yesterday I saw `createEsmNotFoundErr` and mistakenly thought you needed an ES Module loader. For your project, you actually need to modify CommonJS module loading logic. 

You can modify CommonJS module loading logic by replacing `Module._resolveFilename`. As you are probably aware, this is what tools like `ts-node`, `tsconfig-paths` (and Wallaby) are doing to redirect your imports. You can see how to do this in the **wallaby.js** configuration file in the project root.

ES modules has a completely different mechanism. This mechanism is not consistent between node modules and were experimental up until node 20. I've include an example for `node@v18.x` in the same sample repo. You can see how to do this in the **custom-loader.mjs** file in the project root. Please note, I also included the **wallaby.js** configuration file changes to support using this.

---

> I can imagine my situation becoming more common as projects adopt subpath imports.

With many developers now using `esbuild`, `swc`, etc. for compiling their TypeScript (especially at dev time), I also wonder how they solve this problem when not using `ts-node`.

We'll key an eye on how this progresses and will add first class support if we see this being adopted more widely.

**Comment by boneskull** [comment]
Thanks!

Yes, I am using subpath exports and subpath imports but am _not_ using ESM.  I suppose that's a little unusual.

**Comment by boneskull** [comment]
I finally got around to testing this, and it only works for the simple case.  It doesn't work if you have wildcards in your imports. so we need a little help from `minimatch`:

```js
// ... wallaby config ...

  setup(wallaby) {
      const minimatch = require('minimatch');
      const path = require('path');
      const Module = require('module');
      const pkgJsonPath = path.join(
        wallaby.projectCacheDir,
        'packages',
        'midnight-smoker',
        'package.json',
      );
      const pkgJson = require(pkgJsonPath);
      const mappedImports = Object.fromEntries(
        Object.entries(pkgJson.imports).map(([key, value]) => [
          key,
          value.replace('dist', 'src'),
        ]),
      );

      const originalResolveFilename = Module._resolveFilename;

      Module._resolveFilename = function (request, _parent) {
        if (request in mappedImports) {
          const newRequest = path.join(
            wallaby.projectCacheDir,
            'packages',
            'my-project',
            mappedImports[request],
          );
          return originalResolveFilename.call(this, newRequest, _parent);
        } else if (request.startsWith('#')) {
          // minimatch does not like a leading #
          const trimmedRequest = request.slice(1);
          const key = Object.keys(mappedImports).find((key) => {
            return minimatch(trimmedRequest, key.slice(1));
          });
          if (key) {
            const pattern = mappedImports[key];
            // zap leading #
            const trimmedKey = key.slice(1);
            // where is the magic?
            const magicIndex = trimmedKey.indexOf('*');
            // strip everything that matches _before_ the magic
            const wildname = trimmedRequest.slice(magicIndex);
            const newValue = pattern.replace('*', wildname);
            // given a request of `#foo/bar` matching `#foo/*`, this will be `bar`,
            // which is injected into the value matching `#foo/*` (e.g., `./src/foo/*.js`)
            // replace the magic with the rest of the request
            const newRequest = path.join(
              wallaby.projectCacheDir,
              'packages',
              'midnight-smoker',
              newValue,
            );
            return originalResolveFilename.call(this, newRequest, _parent);
          }
          // if we get here, it's probably gonna fail
        }

        return originalResolveFilename.call(this, request, _parent);
      };
    }
```
