### ISSUE TITLE
Ability to recognize source line with exception

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#329]
It should be able to recognize in which code line error has been thrown (**1** - yellow background) 
![8dbvrv5](https://cloud.githubusercontent.com/assets/341600/11092639/26b401ca-8885-11e5-8c57-02705fe2ce12.png)

**Comment by ArtemGovorov** [comment]
Could you please provide a sample repo where I could reproduce the behaviour to see what I can do?

**Comment by ArtemGovorov** [comment]
Let me know if there's a sample I could have look into to reproduce it.
