### ISSUE TITLE
Zuul Support

### ISSUE THREAD

**Issue by TylorS** [wallabyjs/public#330]
Hello, I was hoping to setup on of my new projects with wallaby, but I'm currently using zuul to startup a mock express server to test HTTP requests against. Is there any way to continue to use zuul or is there an option to start up a script before running tests? 

Thank you for your time!

**Comment by ArtemGovorov** [comment]
I don't have any experience with zuul, but you may try using [`bootstrap` function](http://wallabyjs.com/docs/config/bootstrap.html) to run anything before starting tests.

**Comment by TylorS** [comment]
I could start an express server from bootstrap?

**Comment by ArtemGovorov** [comment]
Yes, `bootstrap` is executed before each test run. In the function you may check if it's already started and if not - start it. You many also need to call `wallaby.delayStart()` in the bootstrap function (see the doc page for more details) if you are invoking async functions and then call `wallaby.start()` whenever you are ready to start the tests.

**Comment by TylorS** [comment]
Awesome thank you! I'll let you know if I run into any trouble

**Comment by ArtemGovorov** [comment]
Here is an example of using wallaby.js bootstrap function to [start sails.js server](https://github.com/wallabyjs/sailsjs-mocha-testing-barrels-fixtures-example/blob/master/wallaby.js#L12), not exactly your case, but may still be helpful.
