### ISSUE TITLE
Start exclusive test run broken on new version of Webstorm

### ISSUE THREAD

**Issue by aubrey-ford-nutrien** [wallabyjs/public#3305]
### Issue description or question

Just downloaded new version of Webstorm and Wallaby not starting when choosing "Start exclusive test run" for a file.  Works on prior version.  Giving this error:

(truncated, total length: 49767)
console.error: 'Test Suites: 1 failed, 1 total
Tests:       2 failed, 2 passed, 4 total
Snapshots:   0 total
Time:        18.549 s
Ran all test suites.'
Finished executing 4 affected test(s) in 19.13 second(s)
Failed to process test run results Cannot read properties of undefined (reading 'push')
Diagnostics report has been successfully copied to clipboard.

**Comment by smcenlly** [comment]
We tried exclusive test run and it's working for us. Assuming that you got everything working and don't have any further issues.
