### ISSUE TITLE
Typescript project with ESM and mocha/chai not working

### ISSUE THREAD

**Issue by thunderkid** [wallabyjs/public#3312]
### Issue description or question
I'm trying to get wallaby working with es modules and typescript under mocha/chai. I'm not sure from the wallaby docs whether this is even possible yet. Is there a sample that I missed? If not, here is my attempt:

My sample project has this package.json:
```
{
    "name": "typescript-mocha-testing-lab",
    "type": "module",
    "description": "Running mocha/chai tests in typescript with esm.",
    "version": "0.1.0",
    "license": "MIT",
    "devDependencies": {
        "@types/chai": "^4.3.11",
        "@types/mocha": "^10.0.6",
        "@types/node": "^20.10.5",
        "chai": "^4.3.10",
        "mocha": "^10.2.0",
        "ts-node": "^10.9.2",
        "tsconfig-paths": "^4.2.0",
        "typescript": "^5.3.3"
    },
    "browserslist": [
        "defaults"
    ],
    "scripts": {
        "test": "mocha --node-option loader=ts-node/esm --node-option experimental-specifier-resolution=node tests/**/*.spec.ts"
    },
    "engines": {
        "node": ">=8.9.0"
    }
}
```
and this tsconfig.json:
```
{
    "compilerOptions": {
        "module": "esnext",
        "target": "es2021",
        "incremental": true,
        "sourceMap": true,
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "jsx": "react",
        "moduleResolution": "node",
        "noImplicitReturns": false,
        "noImplicitThis": true,
        "noImplicitAny": false,
        "noImplicitOverride": true,
        "strictNullChecks": true,
        "strictPropertyInitialization": true,
        "noUnusedLocals": false,
        "experimentalDecorators": true,
        "useDefineForClassFields": true
    },
    "include": [
        "./src/**/*.ts",
        "tests/**/*.ts",
    ],
}
```
Running tests manually using `npm run test` works fine (though apparently needing the experimental options).
To try to get the tests working under wallaby, I use the following for wallaby.conf.js:
```
   import path from 'path';

    export default function (wallaby)
    {
        process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir + path.delimiter + 'src';

        return {

            debug: false,

            files: [
                'src/**/*.ts',
                'package.json', // ****** remove for commonjs
                // Exclude test files
                { pattern: '**/*.spec.ts', ignore: true }

            ],

            tests: [
                'tests/**/*.spec.ts'
            ],

            env: {
                type: 'node',
                runner: 'node'
            },

            testFramework: 'mocha',

            compilers: {
                '**/*.ts?(x)': wallaby.compilers.typeScript({
                    module: 'esnext',     // ***** works with commonjs but not with esnext,
                    target: 'es2021',
                    baseUrl: './src'
                })
            },
        };
    };
```
Starting wallaby gives the error
```
Runtime error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module './src/calculator' imported from ./tests/calculator.spec.js
```
However, wallaby works OK with commonjs: If I change the module type to `commonjs` and remove the `package.json` (in the locations marked with // *****), it runs fine.

So is it possible to get wallaby working properly with typescript and esnext? Relying on commonjs seems a hack that wouldn't necessarily work for more complex projects.

**Comment by smcenlly** [comment]
By default, ESM requires extensions for **relative imports** (e.g. `import "./foo.js"`).

Your `package.json` run script solves this problem with the legacy `--experimental-specifier-resolution=node` option (note: this doesn't work in the latest version of node), you should do the same for Wallaby.

You should be able to get Wallaby working with the following configuration file:

**wallaby.js**
```javascript
// import path from 'path';

export default function (wallaby)
{
    // NOTE: This is not required; does not apply to ES Module resolution
    // process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir + path.delimiter + 'src';

    return {

        debug: false,

        files: [
            'src/**/*.ts',
            'package.json', // ****** remove for commonjs
            // Exclude test files
            { pattern: '**/*.spec.ts', ignore: true }

        ],

        tests: [
            'tests/**/*.spec.ts'
        ],

        env: {
            type: 'node',
            runner: 'node',
            params: {
              // NOTE: Tell Wallaby to use the experimental specifier resolution
              runner: "--experimental-specifier-resolution=node"
            }
        },

        testFramework: 'mocha',

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'esnext',     // ***** works with commonjs but not with esnext,
                target: 'es2021',
                baseUrl: './src'
            })
        },

        // NOTE: This is required as mocha doesn't support resetting modules on file changes
        // https://wallabyjs.com/docs/integration/esm.html#mocha
        workers: {
          restart: true,
        }
    };
};
```

---

If you update to the latest version of node, we recommend first getting your tests to run using the CLI. Once you have identified your mocha configuration, you should be able to apply the same to Wallaby (or contact us, we're happy to help).

**Comment by thunderkid** [comment]
This solution worked fine under node 18.04. But after upgrading to node 20.10.0, it gives the same error as before:

```Runtime error: Error [ERR_MODULE_NOT_FOUND]: Cannot find module './src/calculator' imported from ./tests/calculator.spec.js​​```

But running manually with `npm run test` still works under node 20.10.0.

Is there something additional that wallaby requires for node 20.10?

**Comment by smcenlly** [comment]
The `ts-node/esm` loader that you're using automatically appends file extensions so that your CLI works with the latest version of node. You need something similar when Wallaby is running your code (described below).

The node.js team announced in their `node@v19` release notes that the `--experimental-specifier-resolution` flag has been removed and that its functionality should now be achieved using custom loaders. They provide an [example of how to do this](https://github.com/nodejs/loaders-test/tree/main/commonjs-extension-resolution-loader).

To get this working in your project:

1. Install [`resolve`](https://www.npmjs.com/package/resolve) as a devDependency (used by the node.js loader and is required to mimic the commonjs node module resolution behavior); `npm install resolve --save-dev`.
2. Update your Wallaby.js configuration to use a custom loader instead of the old `--experimental-specifier-resolution`:

**wallaby.js**
```javascript
import * as path from 'path';
import { fileURLToPath } from 'node:url';

export default function (wallaby)
{
    return {

        debug: false,

        files: [
            'src/**/*.ts',
            'package.json', // ****** remove for commonjs
            // Exclude test files
            { pattern: '**/*.spec.ts', ignore: true }

        ],

        tests: [
            'tests/**/*.spec.ts'
        ],

        env: {
            type: 'node',
            runner: 'node',
            params: {
              runner: "--loader=" + path.join(path.dirname(fileURLToPath(import.meta.url)), 'loader.js')
            }
        },

        testFramework: 'mocha',

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'esnext',     // ***** works with commonjs but not with esnext,
                target: 'es2021',
                baseUrl: './src'
            })
        },

        workers: {
          restart: true,
        }
    };
};
```

3. Create `loader.js` in your project root with the [contents from the `node.js` loader](https://raw.githubusercontent.com/nodejs/loaders-test/main/commonjs-extension-resolution-loader/loader.js).
