### ISSUE TITLE
vitest 1.2 support

### ISSUE THREAD

**Issue by inverted-capital** [wallabyjs/public#3319]
After upgrading to vitest 1.2 wallaby fails to detect vitest testing framework.

### Wallaby diagnostics report

I'm sorry but the `Copy Diagnostics Report` command is not longer available - I have tried to force a core update and reloaded config and reset wallaby cache - still nothing.  The wallaby console error is:

```
‍​[Info]​ Started Wallaby.js Core v1.0.1517
​​[Error] Failed to load configuration file: Automatic Jest configuration error: Module jest-cli is not found in '.'.​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks​​
​​[Error] Automatic Vitest configuration error: The "path" argument must be of type string. Received undefined​​
​​[Error]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​
```

**Comment by smcenlly** [comment]
Thanks for creating the issue, it was also reported [here](https://github.com/wallabyjs/public/issues/3318#issuecomment-1890181894).

There were a number of breaking changes in `vitest@1.2.0` (released over the weekend) that required updates to our integration. The latest version of Wallaby now supports `vitest@1.2.0`; please update to Wallaby core v1.0.1518, it should work for you.

**Comment by inverted-capital** [comment]
Thank you !!  confirmed working now :)

Really appreciate the rapid responses you guys give to issues that weren't actually anything to do with you.  It is exemplary.
