### ISSUE TITLE
Wallaby with Jest is really slow

### ISSUE THREAD

**Issue by GabrielAPineiro** [wallabyjs/public#3321]
### Issue description or question

We've changed from jasmine to jest and we can run each project individually, but when we try to run wallaby for the whole project it takes a massive long time to finish, while showing different errors and issues for example
![image](https://github.com/wallabyjs/public/assets/104081429/5b53c753-855c-474b-bcae-10f2e8a73f34)
I tried to run yarn nx run-many --all --target=test and it finished in 23 min, but wallaby took nearly 90 min.
![nx tests](https://github.com/wallabyjs/public/assets/104081429/c8ae1e30-a97a-4526-a69f-53520e206d05)
![wallaby whole project](https://github.com/wallabyjs/public/assets/104081429/394785e6-a750-4927-a17e-e354964dfde7)

### Wallaby diagnostics report

The file is very big and may contain sensitive information, can I get an email to send over the log, please.

**Comment by smcenlly** [comment]
You may email us at: hello@wallabyjs.com.

---

Could you please check how long the tests take to run with:

```
nx run-many --all --target=test --skip-nx-cache
```

Currently, when Wallaby starts on your project, by default it will try and run all of the tests for your project, so I imagine that even a 23 minute startup time is going to be too slow for you. We recommend checking out our [Smart Start](https://wallabyjs.com/docs/intro/smart-start.html) feature, which we designed for working with long projects and many/slow tests.

Regarding the errors / issues. Wallaby has an internal timeout that it uses to detect long running code outside of your test executing (e.g. imports, etc.). This can be changed in your Wallaby.js configuration file, but it's only a warning (`longExecutingWarningTimeout` default of `5000` ms). Are there other errors, or is it only the long running code issue?

**Comment by GabrielAPineiro** [comment]
I tried to run nx run-many --all --target=test --skip-nx-cache and got this
![image](https://github.com/wallabyjs/public/assets/104081429/fb857928-1094-402a-a9a4-c43323f69719)

**Comment by GabrielAPineiro** [comment]
Just to put a note here, this time also includes backend tests.
I tried to run wallaby with this config file and got this time
![image](https://github.com/wallabyjs/public/assets/104081429/92df3319-cbf4-400b-bcb9-4049adc5fcab)
​[Info]​ Finished executing 1515 affected test(s) in 6.31 minute(s)

**Comment by smcenlly** [comment]
> ​[Info]​ Finished executing 1515 affected test(s) in 13.47 minute(s)
> and also
> ​[Info]​ Finished executing 1515 affected test(s) in 6.31 minute(s)

I assume that the first time was from the first start, and the second time was from the second start? 

If so, this makes sense, as `jest` caches your file transformations. This is different from using the `--skip-nx-cache` option. To test like-for-like, you will need to compare your `nx` CLI after running `npx jest --clearCache` (for the first startup) to subsequent starts (without `npx jest --clearCache`).

> Just to put a note here, this time also includes backend tests.
Based on your file pattern and diagnostic report, it looks Wallaby would have been running on 86 projects, the same as reported in your previous comment (`Successfully ran target test for 86 projects (8m)`).

---

Assuming that the `6.31 minute(s)` is the start time for your non-initial test run, Wallaby is now running approximately 2 minutes faster than the equivalent using the `nx` CLI.

**Comment by GabrielAPineiro** [comment]
So after executing the clearCache I got this times:
Automatic Config
​[Info]​ Finished executing 4221 affected test(s) in 16.73 minute(s)
Wallaby.js file
​[Info]​ Finished executing 3296 affected test(s) in 69.75 minute(s)

Then, I tried again
​[Info]​ Finished executing 4221 affected test(s) in 12.98 minute(s)
and
​[Info]​ Finished executing 4221 affected test(s) in 11.49 minute(s)

To be honest I had a lot of trouble trying to get these values. Running wallaby made my computer really slow sometimes
***@***.***

I feel there is still an issue here, because the tests are really unstable.

Best regards,

***@***.***<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fwww.exclaimer.com%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=5c7e21a4227fee1189276045bdcfbff1&excomponentid=dMIpEPiSgs08i9F2UChFySJrEWRX3Obh0itCRuAVbe0&signature=crRogc9HW94jsVqNWbxQr3N22Xa_1qYDZZ59W0ac8spRaErdKq0RY-lNACznFlyqFzxEQ1yUaQOHbmKYKODE73IYRz_bH4ZjsUlkm-5e7_AyUmrAW1Pe4Ys7FqKlXR9LUFtVpRj1bR8KBdhox_0tyJfvqRwozTt7uHDoWepXmCg-MnzMZ91sbhhmcjxEABg4DreHhX4evik5_i1UW_rKvLn4nvjlqqHP_1qord_DMF3Y8sAUJsxTUugEtIyPFSVyFUTu8iPNAY5mY4F752ddc0l2sahm8EqiEVPfq_Cz3oSvRalSHPC0khI43obJsUIuI12nIT6Xq7ol_0-FayNlyA&v=1>
Gabriel Pineiro
Engineer
T:
+44 (0) 1252 531422<tel:+44%20(0)%201252%20531422>
(Office)
E:
***@***.******@***.***>
[Book an online demonstration of Exclaimer]<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fexclaimer.com%2Fproduct%2Fonline-demonstrations%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=c59925e64bb1ee11bea06045bdd19417&excomponentid=KrXVXyf5BYHpgAhFoDkTeGHJRNiVU1L1kvqp6TY4g1w&signature=T8UZvlRqzEzwbJ0FtwOoJcExFG4koWs4gKS1DvqCxhZ5qti9AJvAiEoxsagK_WK_7xRdWugrL14qaz5PCmoF8mnzOniWlZ4Hu8lSfwzFThTv60i2YUkuFfumjG4L5N07PMOYVRDo7WRQMfLU3wftpcfKdAzoYfFndxUo0EIRIqypMFp83DWwHryveFfbyhZz4D_9wBOPdcAYnW3d_ZRn7v9di17FT-su2dMRpXNaC6rjxJit2w8kirBPt8r6U7F2QWgLUMJTsXEjSdrPS7Qu3Q4q93czfS89jgZxH6Q4c74R2tkh2o8Fsk9B_BwyzC93ZIdzmQ0oGb5k_zCP_wdUzA&v=1>
Exclaimer Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Registered in England and Wales (number 04938619).​​​​

**Comment by GabrielAPineiro** [comment]
And I’m not sure is related to the performance issues.
If I close my VSCode and try to open again, after I used the Smart Start, I’m getting these errors as soon as I open my VSCode
Attached.

Best regards,

***@***.***<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fwww.exclaimer.com%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=5c7e21a4227fee1189276045bdcfbff1&excomponentid=dMIpEPiSgs08i9F2UChFySJrEWRX3Obh0itCRuAVbe0&signature=crRogc9HW94jsVqNWbxQr3N22Xa_1qYDZZ59W0ac8spRaErdKq0RY-lNACznFlyqFzxEQ1yUaQOHbmKYKODE73IYRz_bH4ZjsUlkm-5e7_AyUmrAW1Pe4Ys7FqKlXR9LUFtVpRj1bR8KBdhox_0tyJfvqRwozTt7uHDoWepXmCg-MnzMZ91sbhhmcjxEABg4DreHhX4evik5_i1UW_rKvLn4nvjlqqHP_1qord_DMF3Y8sAUJsxTUugEtIyPFSVyFUTu8iPNAY5mY4F752ddc0l2sahm8EqiEVPfq_Cz3oSvRalSHPC0khI43obJsUIuI12nIT6Xq7ol_0-FayNlyA&v=1>
Gabriel Pineiro
Engineer
T:
+44 (0) 1252 531422<tel:+44%20(0)%201252%20531422>
(Office)
E:
***@***.******@***.***>
[Download our whitepaper to learn more]<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fexclaimer.com%2Fwhite-papers-ebooks%2Frethinking-email-signatures%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=c59925e64bb1ee11bea06045bdd19417&excomponentid=XqZEJGugHWVN_bv1T4AGQDva9xVk2OytYEFdCKv6XTg&signature=yrnyD-R-AE5NmeRzZGP8Jk9fgKzJfHFTUygiPUjsjpMDLMjcUufQ018caHNa2Pj4J4yol5OejgYSkmAjvCxADoQo4x4sSt66HedT-a3paXmkwZXsYQOGmNc5-55XqSbyaHPUer4OFlx6thmDvPkYlA0QdioTUNKFwPuw-mmO_rNCqzJyZFmXn7X6ezvbIOrH9mqHV7h0WVUr3QOTtSX5hf2ORj94IWXd3vcwB04U_tQpbUe5Na9wCYvdmFsPMD27Pg2iiU3wJxHv8pLYTVv-Cg18_qIlyGt9pnnsI4ha-zSacn7nn4VBZyZEvZWVpNxHJxiiyQi3zSz4zInlDtJg_A&v=1>
Exclaimer Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Registered in England and Wales (number 04938619).​​​​

**Comment by smcenlly** [comment]
@GabrielAPineiro - it looks like you tried to send a few attachments in your email reply. Unfortunately those are not uploaded to GitHub. You will need to log into GitHub to attach the images.

Is there any way for us to access your project for ourselves to try and test the performance and identify what's going on/wrong?

**Comment by GabrielAPineiro** [comment]
This is the image from my last comment
![image](https://github.com/wallabyjs/public/assets/104081429/18a1106e-7389-4959-b4a3-fd2469155e33)

**Comment by GabrielAPineiro** [comment]
Hi Simon, good morning.
I’ve attached the image in the github thread.
About the access, I’ve talked with my manager. We can’t give you access to the code, but we can screenshare through a call, if that’s okay.

Best regards,

***@***.***<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fwww.exclaimer.com%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=5c7e21a4227fee1189276045bdcfbff1&excomponentid=dMIpEPiSgs08i9F2UChFySJrEWRX3Obh0itCRuAVbe0&signature=crRogc9HW94jsVqNWbxQr3N22Xa_1qYDZZ59W0ac8spRaErdKq0RY-lNACznFlyqFzxEQ1yUaQOHbmKYKODE73IYRz_bH4ZjsUlkm-5e7_AyUmrAW1Pe4Ys7FqKlXR9LUFtVpRj1bR8KBdhox_0tyJfvqRwozTt7uHDoWepXmCg-MnzMZ91sbhhmcjxEABg4DreHhX4evik5_i1UW_rKvLn4nvjlqqHP_1qord_DMF3Y8sAUJsxTUugEtIyPFSVyFUTu8iPNAY5mY4F752ddc0l2sahm8EqiEVPfq_Cz3oSvRalSHPC0khI43obJsUIuI12nIT6Xq7ol_0-FayNlyA&v=1>
Gabriel Pineiro
Engineer
T:
+44 (0) 1252 531422<tel:+44%20(0)%201252%20531422>
(Office)
E:
***@***.******@***.***>
[Book an online demonstration of Exclaimer]<https://uk.content.exclaimer.net/?url=https%3A%2F%2Fexclaimer.com%2Fproduct%2Fonline-demonstrations%2F&tenantid=bm88-84zEem80AAD_wDvFQ&templateid=c59925e64bb1ee11bea06045bdd19417&excomponentid=KrXVXyf5BYHpgAhFoDkTeGHJRNiVU1L1kvqp6TY4g1w&signature=T8UZvlRqzEzwbJ0FtwOoJcExFG4koWs4gKS1DvqCxhZ5qti9AJvAiEoxsagK_WK_7xRdWugrL14qaz5PCmoF8mnzOniWlZ4Hu8lSfwzFThTv60i2YUkuFfumjG4L5N07PMOYVRDo7WRQMfLU3wftpcfKdAzoYfFndxUo0EIRIqypMFp83DWwHryveFfbyhZz4D_9wBOPdcAYnW3d_ZRn7v9di17FT-su2dMRpXNaC6rjxJit2w8kirBPt8r6U7F2QWgLUMJTsXEjSdrPS7Qu3Q4q93czfS89jgZxH6Q4c74R2tkh2o8Fsk9B_BwyzC93ZIdzmQ0oGb5k_zCP_wdUzA&v=1>
Exclaimer Ltd accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Registered in England and Wales (number 04938619).​​​​

**Comment by marleypowell** [comment]
Also as another question, is wallaby expected to be very aggressive with the amount of workers that it uses for initial runs by default?

![image](https://github.com/wallabyjs/public/assets/55280588/2139233e-16bf-43d4-ae0a-811fcdf39665)

**Comment by smcenlly** [comment]
@marleypowell - thanks for the updates. 

If I understand you correctly, besides the aggressive CPU, Wallaby is running tests in a similar time to the CLI?

You may configure the number of worker threads that Wallaby uses with the [workers setting](https://wallabyjs.com/docs/config/workers.html). By default the `initial` setting is the `number of CPUs on your PC - 2` and the `regular` is half that.

**Comment by marleypowell** [comment]
@smcenlly yeah Wallaby seems to be doing a good job and back to working like before. The remaining long running time is down to our scale and performance of tests, we should probably start using smart start!

Jest was running them all in ~15 minutes (unsure if there was caching) and Wallaby ran them in ~10 minutes (without caching) 😄.

Thanks for clarifying how the workers are calculated, this might be something we will configure if it becomes a problem!

This problem only appeared when switching from Karma to Jest (both using NX), I can only assume there's a difference in how the automatic configuration works with them. Does the Jest auto config need to include `**/**` in it's files as from what I can tell it has the NX root paths for each project it needs to run tests for?

**Comment by smcenlly** [comment]
Great to hear that everything is now working well for you. 😀

You can try removing the `**/**` from the file patterns. If it works for you, there's nothing wrong with doing this. Because of how we integrate with `jest`, along with some targeted excludes (e.g. `node_modules`) this is the only way we can guarantee that we will correctly watch all files that may be related to your tests.

I'm going to close the issue now as it seems we've now addressed the problem.
