### ISSUE TITLE
How to supply Wallaby with env vars?

### ISSUE THREAD

**Issue by RapidOwl** [wallabyjs/public#3330]
We're using Jest `29.7.0` and Wallably is configured automatically. Other than Wallaby being generally flaky (not starting up, failing to find all tests and failing to display code lens), we have one blocking problem.

One of our tests depends on a function that pulls in an environment variable. I assumed "automatic mode" might do this for me, but it seems not. I've tried reading the docs on config files, but they're pretty confusing and I can't find any examples.

I _think_ I need a setup function so I've created a `wallably.js` in my root folder with the following:
```
module.exports = () => ({
  autoDetect: true,
  setup: function () {
    console.log("Setting up global variables for tests");

    process.env.THING = "stuff";
  },
});
```

This doesn't appear to work. I can't see that line being logged in the Wallably.js Console and the environment variable isn't being populated (I assume since the tests still fail).

Can anyone give me a clear example of how you do this?

**Comment by RapidOwl** [comment]
Confusingly, the answer is to explicitly supply them to Jest via Jest's config file. Jest didn't need this in order to run the tests, but Wallaby does.

**Comment by ArtemGovorov** [comment]
Hi,

> Jest didn't need this in order to run the tests, but Wallaby does.

If your tests depend on some env variables, you need to pass them to Jest too one way or another. Maybe they are passed via your `package.json` script args?

> Other than Wallaby being generally flaky (not starting up, failing to find all tests and failing to display code lens),

We are keen to look into these issues and fix them. Mind creating separate issue(s) with attached Wallaby diagnostics report?

**Comment by RapidOwl** [comment]
@ArtemGovorov The flakiness I was experiencing has now gone away again so I can't give you anything useful. If it comes back, I'll report it properly :).

We've got a weird mixed setup where we've got a JavaScript file (called in `jest.config.js` to set environment variables as well as `.env.test`. Jest seems to pick up the values from `.env.test` automatically, but when running inside Wallably it doesn't. I can't find anywhere where we're running code to import the values from `.env.test`.

**Comment by ArtemGovorov** [comment]
Hey @RapidOwl, thanks for sharing the details!

> Jest seems to pick up the values from .env.test automatically, but when running inside Wallably it doesn't

Hmm, this is a strange thing that we'd definitely want to fix if it is an issue with Wallaby. 

Can you please confirm:
- `.env.test` is a separate file that Jest is able to use without `jest.config.js` modifications to load it, but Wallaby only works with those modifications (to load the same values)?
- do you have `dotenv/config` package installed, and used by Jest somehow anywhere in your project? Like via this Jest setting somewhere for example: `"setupFilesAfterEnv": ["dotenv/config"]`, or being passed to load elsewhere?
- what script is used to run Jest, just `npx jest`, or some dedicated `test` script in your package.json, and if so, what does the script look like?
