### ISSUE TITLE
Wallaby doesn't seem to work with vitest "vmThreads" pool mode

### ISSUE THREAD

**Issue by kainosnoema** [wallabyjs/public#3335]
### Issue description or question

We've recently switched from jest to vitest for more reliable tests and faster test runs while watching in particular. We need to use the [vitest "vmThreads" pool mode](https://vitest.dev/config/#vmthreads) for full test runs, which is significantly faster than the default threads mode, but I can't get Wallaby to start and run with it enabled.

If I run in the threads pool mode everything seems to work as expected, but when started using using `vmThreads` mode I get an odd `TypeError: Cannot read properties of undefined (reading 'adjustFileTasks')​​` error (see diagnostics report).

### Wallaby diagnostics report

**Attached (too long for issue body):** [wallaby-diagnostics-vitest-vmthreads.txt](https://github.com/wallabyjs/public/files/14393074/wallaby-diagnostics-vitest-vmthreads.txt)

**Comment by mburnell** [comment]
Thanks for reporting the issue. We've identified and fixed an issue where globals were lost when running with jsdom and vmThreads. Please update to [the latest core v1.0.1531](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to fix this issue.
