### ISSUE TITLE
Inline values suddenly abbreviated

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3344]
This morning I've suddenly started seeing very abbreviated inline values

![image](https://github.com/wallabyjs/public/assets/360/921de6e8-e3ff-47ac-a6d1-ca90a76b6299)

Did something change? (I would previously see the full contents of that array, not ...)

This is my wallaby.js

```js
module.exports = function () {
  return {
    resolveGetters: true,

    logLimits: {
      inline: {
        depth: 12,
      },
      values: {
        default: {
          stringLength: 200,
        },
        autoExpand: {
          stringLength: 8192,
          elements: 5000,
          depth: 10,
        }
      },
    },
    
    runMode: "onSave",
  } 
}
```

**Comment by tslocke** [comment]
It seems as I expand things in the value explorer (which is very slow) the ellipses also expand. Is this a new feature?

This is unusable for me. Restoring to `//? JSON.stringify($, null, 2)` for now

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue. There's indeed been a recent change to how values are logged. Inline output for live comments (but not `console.log`) has been affected by the change and accidentally had a too small `depth` override. We have fixed the default setting in [the latest core v1.0.1537](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), please try updating and restarting Wallaby to see if it helps.

> It seems as I expand things in the value explorer (which is very slow) the ellipses also expand. Is this a new feature?

Expanding inline output when value explorer is used is a new feature, but it wasn't planned to be used to expand shallow inline output, but rather be able to expand deeper inline output even further if required.

> the value explorer (which is very slow)

I assume it has been slow for you prior to the above mentioned changes? We haven't made any changes to the way Value Explorer works. Value Explorer performance largely depends on how much time your tests (that need to run to get expanded values) take to execute.

**Comment by tslocke** [comment]
Awesome - thanks for fixing this so quickly. 

> but rather be able to expand deeper inline output even further if required.

That sounds like a great feature. I just tried it - a couple of bits of feedback

 - In a big json structure there is a lot of very fiddly expanding before you get to the [...] that you want to expand. It would be amazing if I could do this directly in the output inspector or inline view.
 - When I did expand something, the output inspector scroll position jumped back to the top

> I assume it has been slow for you prior to the above mentioned changes?

Yes. I guess I was wondering why the value explorer needs to keep re-evaluating to get to nested objects. How come it doesn't have access to the entire object from the first eval?

Thanks again for the quick fix!

**Comment by smcenlly** [comment]
> I just tried it - a couple of bits of feedback

Thanks for your feedback! 

> In a big json structure there is a lot of very fiddly expanding before you get to the [...] that you want to expand. It would be amazing if I could do this directly in the output inspector or inline view.

From what you said above, it sounds like you're already logging with Live Comments? You may like to try logging the value with the [Live Comment Auto-Expand](https://wallabyjs.com/docs/intro/value-explorer.html#live-comment-to-auto-expand) (`//?+`), it may give you what you're after in the Output Inspector.

> When I did expand something, the output inspector scroll position jumped back to the top

The scroll position changing sounds like a bug; we will investigate.

>  I guess I was wondering why the value explorer needs to keep re-evaluating to get to nested objects.

Both Wallaby and Quokka re-evaluate at times to get nested values (and also as a part of certain operations using Time Travel Debugger). Inspecting and capturing values can sometimes take a lot of CPU/memory (especially if there are lots of logged values), so we limit processing for performance reasons. In the context of Wallaby / Quokka, re-executing your code **should** return repeatable values, so it's safe for us to do so in this context.

**Comment by smcenlly** [comment]
@tslocke - we were unable to reproduce the changing scroll position issue that you had. Could you please raise a separate issue and provide a short video / animated gif demonstration for us to see?

**Comment by tslocke** [comment]
I only saw it the once and now I can't replicate either. If I see it again I'll try to reproduce.
