### ISSUE TITLE
Latest Visual Studio Plugin (1.0.18) fails with Microsoft Visual Studio 2015 Update 1 RC

### ISSUE THREAD

**Issue by timReynolds** [wallabyjs/public#335]
I've just been promoted to update to the latest version of the Visual Studio plugin via the notification. On doing so and restarting Wallaby was no longer installed in VS, trying to install from the download on the website results in the following log file;

13/11/2015 09:44:22 - Microsoft VSIX Installer
13/11/2015 09:44:22 - -------------------------------------------
13/11/2015 09:44:22 - Initializing Install...
13/11/2015 09:44:22 - Extension Details...
13/11/2015 09:44:22 - 	Identifier         : 91ed0b3e-dedc-435f-99a2-8b496951f582
13/11/2015 09:44:22 - 	Name               : Wallaby.js for Visual Studio 2015
13/11/2015 09:44:22 - 	Author             : Wallaby.js
13/11/2015 09:44:22 - 	Version            : 1.0.18
13/11/2015 09:44:22 - 	Description        : Wallaby.js is an intelligent test runner for JavaScript that continuously runs your tests. It reports code coverage and other results to your code editor immediately as you change your code. Wallaby.js uses various tricks to run your tests as fast as possible, such as runtime analysis to only execute tests affected by code changes and parallel test execution.
13/11/2015 09:44:22 - 	Locale             : en-US
13/11/2015 09:44:22 - 	MoreInfoURL        : http://wallabyjs.com/
13/11/2015 09:44:22 - 	InstalledByMSI     : False
13/11/2015 09:44:22 - 	SupportedFrameworkVersionRange : [4.5,)
13/11/2015 09:44:22 - 
13/11/2015 09:44:22 - 	SignatureState     : Unsigned
13/11/2015 09:44:22 - 	Supported Products : 
13/11/2015 09:44:22 - 		Microsoft.VisualStudio.Community
13/11/2015 09:44:22 - 			Version : [14.0.23107]
13/11/2015 09:44:22 - 
13/11/2015 09:44:22 - 	References         : 
13/11/2015 09:44:22 - Signature Details...
13/11/2015 09:44:22 - 	Extension is not signed.
13/11/2015 09:44:22 - 
13/11/2015 09:44:22 - Searching for applicable products...
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio Premium 2013 
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio Professional 2013
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio Enterprise 2015 RC
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio Professional 2015 RC
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio Community 2015 RC
13/11/2015 09:44:24 - Found installed product - Microsoft Visual Studio 2015 RC Shell (Integrated)
13/11/2015 09:44:24 - Found installed product - Global Location
13/11/2015 09:44:24 - Found installed product - ssms
13/11/2015 09:44:24 - Found installed product - ssms
13/11/2015 09:44:24 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ArtemGovorov** [comment]
Do you have VS2015 **Update 1** RC installed? We are looking into it, will most likely publish a new version soon, but you will have to download and install it from our website. Sorry for the inconvenience.

**Comment by timReynolds** [comment]
Sorry it is indeed update 1

**Comment by ArtemGovorov** [comment]
Please update the latest (v1.0.19) from our website. It should install fine now. Please note though that we didn't yet test much Update 1 RC so don't 'officially' support it yet, let us know if you hit any issues with it.

**Comment by timReynolds** [comment]
Thanks for being so responsive. I'll report any Update 1 issues I spot.

**Comment by timReynolds** [comment]
Just to let you know I've been running this with VS Update 1 RC since Friday on a large 400+ test suite and haven't spotted any issues. Seems solid, thanks again.

**Comment by ArtemGovorov** [comment]
@timReynolds Awesome, thanks for the update!
