### ISSUE TITLE
MutationObserver / Aurelia support

### ISSUE THREAD

**Issue by forestmarie** [wallabyjs/public#336]
Does Wallaby have a config option for mutation observer  ?  Running unit tests with the latest version of Aurelia (the pre-beta) and get errors with mutation observer. 

The error from Wallaby can be found here: https://gist.github.com/forestmarie/4311a803d99a94fc6c0b at the bottom. 

Thanks. 

Edit: using visual studio version of wallaby

**Comment by ArtemGovorov** [comment]
Wallaby.js by default is using PhantomJs 1.9.8 for browser tests and it [doesn't support MutationObserver API](https://github.com/ariya/phantomjs/issues/10715#issuecomment-26633219). The solution is to [configure wallaby to use PhantomJs 2](http://wallabyjs.com/docs/integration/phantomjs2.html), which does support it.
