### ISSUE TITLE
Consider support for Zed

### ISSUE THREAD

**Issue by michaelwestphal** [wallabyjs/public#3367]
### Issue description or question

Please consider adding Wallaby support for the Zed editor (https://zed.dev/) as their [support for extensions](https://github.com/zed-industries/extensions/blob/main/AUTHORING_EXTENSIONS.md) matures.

**Comment by smcenlly** [comment]
Zed currently only supports language and theme extensions which is not enough to provide Wallaby's functionality. Consequently, we do not have plans to integrate with Zed at this time. If/when their extension API changes, we will re-evaluate.

We have some loose plans to allow Wallaby to run without in-editor support, but there's nothing concrete we can share on that at this time.

**Comment by michaelwestphal** [comment]
Thank you!

**Comment by ArtemGovorov** [comment]
Wallaby 2 is live 🚀 https://wallabyjs.com/blog/wallaby-2.html, and it can now be used with [any editors, including Zed](https://wallabyjs.com/docs/intro/standalone/).

**Comment by ekaradon** [comment]
@ArtemGovorov Hello,
I know that we now have the ability to launch wallaby separately but for me it's not as powerful as having instant feedback in my IDE. It's still a point of friction for me when I try to leave behind VS Code. Do you still think about supporting Zed within the IDE in the future?

**Comment by ArtemGovorov** [comment]
@ekaradon Hi, right now, Zed doesn’t support extensions for deep integration in the editor - [only languages, themes, icons, and AI extensions](https://zed.dev/docs/extensions/developing-extensions). Once Zed provides the necessary APIs, we’d be happy to revisit our plans for full Wallaby support.
