### ISSUE TITLE
Support for vitest 1.6.0

### ISSUE THREAD

**Issue by dnicolson** [wallabyjs/public#3369]
### Issue description or question

Updating from vitest 1.5.3 to 1.6.0 results in the following messages:
```
‍​[Info]​ Started Wallaby.js Core v1.0.1560
​[Info]​ Wallaby App (realtime reports) is available at: http://localhost:51245
​​[Error] Runtime error: Failed to initialize wallaby vitest.​​
​​[Error] Initialization: Wallaby is not compatible with current version of Vitest.​​
​​[Error] Could not find fetchModule in entry point for file file://./node_modules/vitest/dist/vendor/cli-api.E07AF1Yq.js.​​
​​[Error] Error: Initialization: Wallaby is not compatible with current version of Vitest.​​
​​[Error] Could not find fetchModule in entry point for file file://./node_modules/vitest/dist/vendor/cli-api.E07AF1Yq.js.​​
​​[Error]     at file://./node_modules/vitest/dist/vendor/cli-api.E07AF1Yq.js:1:7​​
​​[Error]     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)​​
​​[Error]     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)​​
```

**Comment by smcenlly** [comment]
We plan on adding support for Vitest 1.6.x within the next week. Will post a reply when it becomes available.

In the meantime, if you don't require Vitest 1.6.x features, you may downgrade to Vitest 1.5.3 until we release support for 1.6.x.

**Comment by smcenlly** [comment]
We have added support for Vitest 1.6.x in Wallaby core `v1.0.1561`. Please update to the latest version, it should work for you.

**Comment by P0TER** [comment]
Hi @smcenlly, I have the same problem, but I can't figure out how I can update the main version for Wallaby because my plugin version is the latest in WebStorm.

```
{
  editorVersion: 'WebStorm 2024.1.2',
  pluginVersion: '1.0.288',
  editorType: 'IntelliJ',
  osVersion: 'win32 10.0.22631',
  nodeVersion: 'v20.11.0',
  coreVersion: '1.0.1559',
 // ...
}
```

**Comment by smcenlly** [comment]
@P0TER - If you close and re-open all instances of WebStorm, Wallaby should automatically download the latest version the next time it starts. After that, you will need to restart once more for the latest version for Wallaby to start using that version.

The only caveat to this is if your license has expired. In this case, you will be version-locked to the last version of Wallaby supported by your license.

**Comment by P0TER** [comment]
@smcenlly Thanks for the reply, but it doesn't work for me. I have a license valid for several years in advance. Would you be able to advise on how I can check my license and update the key if needed since I didn't receive any notifications?

**Comment by smcenlly** [comment]
@P0TER - you should be able to access your most recent license key via your [Wallaby Account](https://account.wallabyjs.com). Then you can [follow these instructions](https://wallabyjs.com/docs/intro/license.html?editor=jb) for applying your license key.

If it's still not updating for you and you're using a VPN, please try temporarily disabling it to allow the update.

Finally, if that does not work, you may try following our [offline installation instructions](https://wallabyjs.com/docs/intro/offline.html).

**Comment by P0TER** [comment]
@smcenlly Following the instructions, I found a magic core update button, this is what I needed. Now everything works fine, thanks.
![image](https://github.com/wallabyjs/public/assets/24668788/6171c25a-942c-4f76-a5b1-d10124364abf)
