### ISSUE TITLE
Can't start wallaby in PHPStorm

### ISSUE THREAD

**Issue by zach2825** [wallabyjs/public#3371]
### Issue description or question

![image](https://github.com/wallabyjs/public/assets/4049321/1ff9d678-23c8-4d08-818a-5f2736ce478e)

I have:
* vue3 project
* vitest@0.31.4
* typescript

this has been an issue for a few months. But, when I try to start wallaby in my project I get this error

```
We have tried both CommonJs require and ESM import to load the config, you may find errors for each attempt below.
-----------------------------
CommonJs config loading error
-----------------------------
<rootDir>/vite.config.js:1
import { defineConfig } from 'vite'
^^^^^^

SyntaxError: Cannot use import statement outside a module
------------------------------
ES module config loading error
------------------------------
<rootDir>/vite.config.js:1
import { defineConfig } from 'vite'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

### Wallaby diagnostics report

I can't copy the report
![2024-05-09_16-42_1](https://github.com/wallabyjs/public/assets/4049321/49a15fb9-8688-46d5-9c43-c8204d01fb67)

there was another kind of related issue. I tried the same fixes on that issue but that issue seemed to be different.

**Comment by smcenlly** [comment]
Based on your screenshot, your `Run Configuration` is not setup correctly for `vitest`. From [our docs](https://wallabyjs.com/docs/integration/vitest.html?editor=jb):

> To start Wallaby in JetBrains IDEs, you may edit (or create a new) wallaby.js Run Configuration by selecting Edit configurations from the drop-down menu in the top right-hand corner of the navigation bar, or from the Run menu. In the run configuration editor set `Configuration Type` filed value to `Automatic`.

Once you change the `Configuration Type` to `Automatic`, it should work for you.

**Comment by zach2825** [comment]
I tried that before, but it didn't work; all is good now. Thank you @smcenlly
