### ISSUE TITLE
Menu items "Start Exclusive Test Run" and "Add to Exclusive Test Run" disappeared from PhpStorm 2024.1

### ISSUE THREAD

**Issue by DontRepeatYourself** [wallabyjs/public#3372]
### Issue description or question

Menu items "Start Exclusive Test Run" and "Add to Exclusive Test Run" disappeared from PhpStorm 2024.1 context menu for test files.

Right clicking on a test file in project window shows a list of available actions.
I'm missing the former menu items for "Start Exclusive Test Run" and "Add to Exclusive Test Run".

![phpstorm-wallaby-right-click-menu](https://github.com/wallabyjs/public/assets/147685467/46e0c913-5820-4dad-90b7-4adacdc4f636)

Is this a wallaby or Intellij related bug or is there a way to bring back these menu items in PhpStorm settings?

PhpStorm 2024.1.1, wallaby plugin 1.0.287

**Comment by smcenlly** [comment]
Thanks for reporting the problem.

We've fixed this in Wallaby for IntelliJ `v1.0.288`. Please update, it should fix the problem for you.
