### ISSUE TITLE
wallaby's compiler seems to barf on stage 3 decorators

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#3374]
### Issue description or question

If a [stage 3 decorator](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#decorators) is used, Wallaby's internal compiler generates code that throws a `SyntaxError`.  In my case, the exception emitted from the test runner looks like

```
"before each" hook for "should reject": Unexpected token ','
  ​​​​​at ​​​​​​packages/midnight-smoker/src/util/filemanager.ts:35​
  ​​​​​at Object.<anonymous> ​​​​​​packages/midnight-smoker/src/pkg-manager/pkg-manager-spec.ts:10​
  ​​​​​at Object.<anonymous> ​​​​​​packages/midnight-smoker/src/pkg-manager/pkg-manager-loader.ts:12​
  ​​​​​at ​​​​​​packages/midnight-smoker/test/unit/component/pkg-manager/pkg-manager-loader.spec.ts:76:19​
  ​​​​​at Context.<anonymous> ​​​​​​packages/midnight-smoker/test/unit/component/pkg-manager/pkg-manager-loader.spec.ts:75:11​
```

Navigating to the line in question, it's a class in `filemanager.ts`:

```ts
export class FileManager {
```

The only thing special about this class is that I'm using some class method decorators, e.g.:

```ts
  @memoize()
  public async readSmokerPkgJson(): Promise<PackageJson> {
    const result = await this.findPkgUp(__dirname, {strict: true});
    return result.packageJson;
  }
```

The `memoize` decorator is defined as:

```ts
/**
 * Memoization decorator
 *
 * @param resolver Function to return the cache key
 * @returns The decorator
 */
export function memoize<
  TThis extends object,
  TArgs extends any[] = unknown[],
  TReturn = unknown,
>(resolver?: (this: TThis, ...args: TArgs) => any) {
  return function (
    target: (this: TThis, ...args: TArgs) => TReturn,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    context: ClassMethodDecoratorContext<
      TThis,
      (this: TThis, ...args: TArgs) => TReturn
    >,
  ) {
    context.addInitializer(function (this: TThis) {
      const func = context.access.get(this);
      // @ts-expect-error blah
      this[context.name] = _memoize(func, resolver);
    });
  };
}
```

Of note, it uses `addInitializer()` to perform method decoration.  The Wallaby console surfaces the actual error location; it is in the compiled `filemanager.js`.  The line containing the `SyntaxError` appears alongside public field declarations, just before the `constructor`, and throws:

```
​[Info]​ 2024-05-29T19:48:49.381Z workers Sandbox (active) [18ej3] error: <rootDir>/packages/midnight-smoker/src/util/filemanager.js:183
​[Info]​         fs = (__runInitializers(this, _instanceExtraInitializers)), void 0;
​[Info]​                                                                   ^
​[Info]​ SyntaxError: Unexpected token ','
```

Evidently the comma before the `void 0` is giving it fits.  FWIW, it appears if the last parentheses is in the wrong place. Compiling with `tsc` yields:

```js
        fs = (__runInitializers(this, _instanceExtraInitializers), void 0);
```

Which is valid syntax.

I attempted to switch to my local TypeScript version, but this made no difference.

### Wallaby diagnostics report

Here's [a gist](https://gist.github.com/boneskull/074f4c41aa88b8010b78e22b43fcbf97) containing the diagnostic report, `filemanager.ts` and Wallaby's `filemanager.js`.

**Comment by smcenlly** [comment]
We can't seem to reproduce your problem.

We tried using [midnight-smoker](https://github.com/boneskull/midnight-smoker) with the `plugin-support-xstate` branch, and we replaced `filemanager.ts` content and everything is working for us.

I'm wondering if perhaps the memoization decorator was broken at some point (i.e. generating incorrect code) and as a result, something has been cached incorrectly. Could you please try clearing your Wallaby cache with `Wallaby.js: Reset Wallaby Cache` to see if that fixes your problem?

If you think the steps we've taken are correct, can you please try cloning to a fresh directory and let us know if that works for you?

Finally, if you're still having problems, could you please provide us with a branch to use and any special instructions to set up (we were just using `npm install`).

**Comment by boneskull** [comment]
@smcenlly The branch is `plugin-support-xstate`

**Comment by boneskull** [comment]
OK, I've tried with a fresh clone.

1. clone repo
2. checkout `plugin-support-xstate` branch
3. `npm ci`
4. open dir in VS code
5. run wallaby

same result 😦 

I tried disabling a bunch of extensions, but this didn't seem to make a difference.

latest diagnostics: https://gist.github.com/boneskull/1177544eccb5ed960ce25e4889c42a15

**Comment by smcenlly** [comment]
Thanks - I can readily reproduce the problem now. It seems that this is failing on our production build and not our internal development time version that I was using yesterday because of some weird TypeScript behavior.

We should have a fix for you before too long.

**Comment by smcenlly** [comment]
This has been fixed in Wallaby core `v1.0.1567`. Please update to this version, it will fix your problem.

Apologies for the inconvenience with not finding the issue sooner. It's very rare our production build fails while our dev build does not.

**Comment by boneskull** [comment]
No need to apologize! Always grateful for the assistance.

**Comment by boneskull** [comment]
Confirmed fixed
