### ISSUE TITLE
Wallaby fails to start global.$_$wallabyVitest.wrapFetchedModule is not a function​​

### ISSUE THREAD

**Issue by deshiknaves** [wallabyjs/public#3375]
### Issue description or question

Wallaby will not start:

```shell
‍​[Info]​ Started Wallaby.js Core v1.0.1569
​​[Error] TypeError: global.$_$wallabyVitest.wrapFetchedModule is not a function​​
​[Info]​ console.error: 'TypeError: Cannot read properties of undefined (reading \'initializeGlobalSetup\')
```

The project will run using vitest directly. The same project was working correctly yesterday. There was an update to VSCode last night.

**Comment by smcenlly** [comment]
We're investigating your issue but so far have not been able to reproduce it.

Can you please provide your [Wallaby Diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)?

If that doesn't work for you, can you please provide your:

* `package.json` dependencies (`devDependencies` and `dependencies`)
* node version
* vitest configuration file

**Comment by smcenlly** [comment]
You may disregard my previous message; we've been able to reproduce the problem using vitest workspaces.

**Comment by smcenlly** [comment]
This has been fixed in the latest version of Wallaby core, `v1.0.1570`. Please update to this version, it will fix your problem.
