### ISSUE TITLE
Plugin gone after upgrading IntelliJ on OSX

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#338]
I updated IntelliJ to v15 and now the Wallaby plugin is gone. I have to install I manually to get it back. I need to re-enter the license code as well.
Is there any way that IntelliJ remembers that Wallaby is installed?

**Comment by ArtemGovorov** [comment]
It's expected. Different major versions of IntelliJ have different cache folders, etc. I'll have a look if a custom plugin can be preserved, but I doubt it.

**Comment by fvanwijk** [comment]
Grrr, I see that all my other custom plugins are gone too. Seems to be a Jetbrain "feature", has nothing to do with Wallaby.
