### ISSUE TITLE
No coverage in WebStorm

### ISSUE THREAD

**Issue by marekkalnik** [wallabyjs/public#339]
Hi,

thanks for Wallaby, it looks very promising. I'm trying it out at this moment but I can't get it to show the coverage in WebStorm. Could you tell me if I am doing anything wrong?

Here is the test:
![paymentservicetest](https://cloud.githubusercontent.com/assets/548629/11214616/9eb82b58-8d42-11e5-9b7a-6d1a39c5e90c.png)

And the tested code:
![paymentservice](https://cloud.githubusercontent.com/assets/548629/11214618/a0028a12-8d42-11e5-8591-cadc1d72a7b1.png)

My configuration is the following:
```json
{
  "files": [
    "api/**/*.js",
    {"pattern": "test/**/*.json", "instrument": false}
  ],
  "tests": [
    "test/unit/**/*.js"
  ],
  "testFramework": "mocha",
  "env": {
    "type": "node",
    "params": {
      "env": "PROJECT_ROOT=/Users/marek/project/backend"
    }
  }
}
```

Thanks in advance!

**Comment by marekkalnik** [comment]
I have downloaded the sample node.js project and ran wallaby - it works ok, so it has to be related to my project.

**Comment by ArtemGovorov** [comment]
> sample node.js project

I was going to suggest it.
Your config looks good, there's nothing wrong I can see.
Considering tests are passing and there's no coverage, I can only assume that it loads source files directly from your local project, not from wallaby cache where they're instrumented.
How do you load source files from your tests, via standard `require` or using some mocking module? Is there anything else you're doing that is different from the sample project? Perhaps you could create a sample repo where I could reproduce the issue?

**Comment by marekkalnik** [comment]
Ah, that is a good catch. I was loading source files with an absolute file path instead of a relative one (it's the env PROJECT_ROOT parameter in config). I replaced it by projectCacheDir and it works. I don't know if this is a common user case, but some kind of alert would be useful :) Thanks for help!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
