### ISSUE TITLE
Is there a Wallaby Server or Daemon I can communicate with programmatically from my local machine to check test status? 

### ISSUE THREAD

**Issue by technoplato** [wallabyjs/public#3392]
### Issue description or question

This is perhaps a little bit esoteric, but what I’m thinking is I would like to build in a test checking run to my large language model enabled code editor. I would like to let the large language model make changes to my code and then query after a brief second For the new status of the tests from Wallaby. I don’t expect this functionality to be there but I was just curious so figured I would ask. Thanks!

**Comment by smcenlly** [comment]
Currently, we don't expose any API to interact with Wallaby programmatically. That said, while I can't share details right now, our mid-long term roadmap includes some items that may help in this space.

What editor are you using, and what are you using for your LLM to make your code changes? Keen to understand your setup, if it's popular / common-place, maybe there's something we can do in the short-term to support a more direct integration.

**Comment by technoplato** [comment]
> Currently, we don't expose any API to interact with Wallaby programmatically. That said, while I can't share details right now, our mid-long term roadmap includes some items that may help in this space.
> 
> What editor are you using, and what are you using for your LLM to make your code changes? Keen to understand your setup, if it's popular / common-place, maybe there's something we can do in the short-term to support a more direct integration.

Hey thanks so much for the response. I personally use WebStorm and have found Claude to be the best code editor. I generally use the [aider](https://github.com/paul-gauthier/aider) tool but am working on building my own, just communicating with their LLMs via standard APIs (most likely litellm)

The key functionality I would want from Wallaby is to do something like observe a stream of test events. So I could apply code changes from llm, ensure unit tests pass, then commit, rinse and repeat. Does that make sense?

Can I provide any more useful info here?

**Comment by smcenlly** [comment]
Makes sense, thanks for sharing the additional detail. 🙏

**Comment by technoplato** [comment]
> Makes sense, thanks for sharing the additional detail. 🙏

Let me know if you have any follow up questions and thanks as always for an amazing tool!
