### ISSUE TITLE
Cursor IDE support

### ISSUE THREAD

**Issue by randspy** [wallabyjs/public#3398]
### Issue description or question

Hi, first of all, great job on the tool. It saves a lot of time. 

For the last few days, I have been testing Cursor IDE. And I have noticed that the diff is missing colorization in the terminal. No errors in the console.

in Cursor:
<img width="817" alt="image" src="https://github.com/user-attachments/assets/ac2ecba0-ba01-4bf7-a2f2-3aba454efb5a">

in VSC:
<img width="818" alt="image" src="https://github.com/user-attachments/assets/3c7864bb-dc61-4d9a-9d93-3560ae6e83be">

BTW. It is the only difference I have noticed.

BR

**Comment by ArtemGovorov** [comment]
Hey, thanks for being our user!

It's possible that the issue is theme related, because the diff colorization is working as expected in Cursor for us in Dark Modern and Dark+ themes.

Can you please share the name of the theme that you are using in Cursor?

**Comment by randspy** [comment]
Hi, 

Thanks for the fast replay. Changing the theme fixed the problem. I used Anysphere Dark. It was a default one when I installed Cursor.

BR
