### ISSUE TITLE
Suggestion. Add config inspector

### ISSUE THREAD

**Issue by VSymonenko** [wallabyjs/public#3399]
Hello!
I stuck with the observability problem.
I have 2 same Vitest projects:
- generated from the same CLI
- used the same Vitest config
- used the same Wallaby config `Automatic Configuration <project directory>`
- only source dependencies would be different

but in the first project wallaby work fine and in the second project wallaby does not see test files (run without any errors)

I would like to inspect the 'real' configuration that Wallaby used

**Comment by smcenlly** [comment]
There isn't a "real" configuration per se. That's not quite how our automatic configuration works.

Having said that, you can use your [Wallaby Diagnostic report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report) to compare the relevant configuration differences between your two projects.

If you're having problems with a specific project, please provide your Wallaby Diagnostic report and let us know where your test files are (that Wallaby is not detecting).

**Comment by VSymonenko** [comment]
thanks, this is helpful.
I found that bug with the newest Vitest version, and create a [repository to reproduce](https://github.com/VSymonenko/wallaby-vitest-bug)
Also I create [bug report](https://github.com/VSymonenko/wallaby-vitest-bug?tab=readme-ov-file#description)

**Comment by ArtemGovorov** [comment]
@VSymonenko Thanks for sharing the repo! The issue is fixed and the fix is published in [the latest core v1.0.1604](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
