### ISSUE TITLE
jasmine object not recognized

### ISSUE THREAD

**Issue by marcalj** [wallabyjs/public#34]
```TypeError: 'undefined' is not a function (evaluating 'jasmine.stringMatching(/^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/)')```

Using this test:

```js
expect(block).toEqual({
            'id': jasmine.stringMatching(/^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$/)
});
```

Is it my problem to not load protractor on files config section?

**Comment by ArtemGovorov** [comment]
`stringMatching` is a new jasmine 2.2 function, wallaby.js doesn't support it yet, we will be adding the support soon.

**Comment by marcalj** [comment]
Sorry, I just realized now. Thanks for the quick response.

**Comment by ArtemGovorov** [comment]
Jasmine 2.2.1 is now supported. Set `testFramework: 'jasmine@2.2.1'` in your config if you'd like to use it.

**Comment by marcalj** [comment]
Perfect! It's working :)
