### ISSUE TITLE
Wallaby.js auto-start

### ISSUE THREAD

**Issue by brettjacobson** [wallabyjs/public#340]
Is there an option to have WallabyJS auto-start if there is a wallaby.json file present when a solution is opened in Visual Studio?

**Comment by ArtemGovorov** [comment]
There's no such options at the moment. There's `Wallaby.StartRunner` command, so you may open your solution with this command (or create a shortcut for it): 
```
devenv "your\solution\file\path.sln" /command Wallaby.StartRunner
```
It should open your solution and start wallaby.js.

**Comment by IPWright83** [comment]
It'd be really nice to have this built into Visual Studio (and other IDE's if not present). But thanks for the workaround in the meantime

**Comment by mdebruijne** [comment]
@ArtemGovorov 

I want wallaby.js to start automatically in VS Code. Do you want a new issue for VS Code or do you want to make this a "generic autostart in all editors/IDE's issue"?

Any change this functionality will be added to wallaby.js?

**Comment by ArtemGovorov** [comment]
@mdebruijne It's ok, I have renamed the issue.

**Comment by GabiGrin** [comment]
@mdebruijne I've stumbled into the same issue today and made a VSCode extension for this:
https://github.com/GabiGrin/vscode-auto-run-command
Make sure to add this to your settings for to actually run wallaby:
`
"auto-run-command.rules": [
		{
			"condition": "hasFile: wallaby.js",
			"command": "wallaby.start",
			"message": "Running wallaby!"
		}
	]
`

Cheers!

**Comment by mdebruijne** [comment]
@GabiGrin 

Nice, thanks!

**Comment by ArtemGovorov** [comment]
@GabiGrin Awesome, thanks for sharing! The extension looks very useful.

**Comment by wojciechczerniak** [comment]
It's also possible to auto start Wallaby in Webstorm. Just add Wallaby run configuration to `Settings > Tools > Startup Tasks`.

**Comment by smcenlly** [comment]
For VS Code, Wallaby will now re-start a folder/workspace automatically if it was last running when the window was closed. You can read more about the feature [here](https://wallabyjs.com/docs/intro/get-started-vscode.html#changing-wallabys-start-mode). The option is on by default and can be disabled via a user/workspace setting.

Given that it's now possible automatically start Wallaby for VS Code and IntelliJ (via Startup Tasks), we will close this feature request.
