### ISSUE TITLE
WallabyJS and QuokkaJS stopped working in latest VSCode

### ISSUE THREAD

**Issue by cHaLkdusT** [wallabyjs/public#3400]
### Issue description or question

Wallaby and Quokko stopped working in latest VSCode (Version: 1.94.0 (Universal))

**Comment by ArtemGovorov** [comment]
Both tools are working as expected for us in VS Code 1.94.0. Can you please share some more details about any errors that you are seeing? If no errors are reported, please:
- share output from Wallaby and Quokka output channels in VS Code, after starting each tool on the project/file.
- share Console output of VS Code dev tools (available via `Developer: Toggle Developer Tools`), after starting each tool on the project/file.
- share Wallaby Diagnostics report (execute Wallaby `Copy Diagnostics Report` command from your editor command palette after Wallaby is started).

**Comment by cHaLkdusT** [comment]
Hi @ArtemGovorov,

Downgraded to previous VSCode, I can confirm both Wallaby and Quokka are working again.

Quokka.js `v1.0.514`
Wallaby.js `v1.0.348`

These versions are not working in the latest VSCode 1.94.0

**Comment by cHaLkdusT** [comment]
![image](https://github.com/user-attachments/assets/27c68fca-ec8c-4c21-925f-91deee9e5b93)

**Comment by ArtemGovorov** [comment]
There was a breaking change in a recent version of VS Code. This was fixed in our tools ~3 weeks ago, you can fix the problem by using latest version of Wallaby (1.0.382) and Quokka (1.0.653).
