### ISSUE TITLE
Wallaby website v2 announcement blog link links to localhost:4000

### ISSUE THREAD

**Issue by DHFW** [wallabyjs/public#3405]
The `[Read more in our blog](http://localhost:4000/blog/wallaby-2.html)` links to
http://localhost:4000/blog/wallaby-2.html

<img width="575" alt="image" src="https://github.com/user-attachments/assets/03eb2d6c-09a7-43ac-8635-ca3a9bd4e684">

BTW, seems like a really cool release! Major indeed :)

**Comment by ArtemGovorov** [comment]
Thanks for reporting the issue and for your kind words! The link is now fixed.
