### ISSUE TITLE
Add a way of copying multiple lines of log content

### ISSUE THREAD

**Issue by bobwieler** [wallabyjs/public#3409]
### Issue description or question

Maybe I'm missing something with the massive UI update but with prior version of Wallaby, the results of console.log statements would be printed out and could easily be copied and pasted elsewhere. Now with Wallaby 2.0, you can copy a single line statement but not multiple lines at the same time without copying the line number along with it.

<img width="847" alt="Screenshot 2024-10-23 at 14 46 27" src="https://github.com/user-attachments/assets/52768d93-cda9-4f11-b7c2-bea5f2005226">

Trying to copy what is selected in the image will result in:

8%3A18.000Z'
249:5
'2024-10-23T18%3A38%3A18.000Z'
250:5
{ arqcValidationResult: 'VALID' }
251:5
'2024-10-23T18%3A38

All of those line numbers are added in and there is no way of removing them except manually. This is something that I do all of the time so it would be great to have that functionality back.

**Comment by bobwieler** [comment]
Thank you for the quick response. We're using Webstorm and the previous logs would be something along the lines of:

	From console:
		'2024-10-24T14:11:32.919Z' at createdOn src/api/v1/interchange.spec.ts:105:5
		'2024-10-24T14:11:32.919Z' at createdOn src/api/v1/interchange.spec.ts:106:7
		
With the version that I raised the issue on we are getting logs that look like:

'2024-10-24T14:11:32.919Z'
105:5
'2024-10-24T14:11:32.919Z'
106:7

It's true that both of them have additional information for each line. The big difference is that it's easy to separate out the data from the actual console.log statements from the data added by Wallaby. We also lose the file that is associated with each line number.

I spend a lot of time using wallaby to debug production issues by creating a test that reproduces the issue. The log statements those tests produce are often copied into Github issues or shared with others in Slack as part of the debugging processing.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the details. 

With the yesterday's fix you may now copy the output without line numbers at all. Also, if you do need to copy with the same format of output as in Wallaby 1 (ie. with context and file plus line/column), you may get it by opening any test/code line details and copy it from there (by clicking on a gutter indicator of a test or using `Show line test(s)` action):
![lc](https://github.com/user-attachments/assets/35c6ae1e-face-4526-bf51-b3f8f6c4a1dc)

To better address your specific scenario (being able to quickly copy logs of a test), we have been thinking of the following possible solution. As you have already noticed, in the new UI individual log entries can be quickly copied by using copy icon or pressing `C`/`Ctrl/Cmd + C` when a log entry is selected. As it's visible on your screenshot, log list also has a test header that are also selectable in the list (`validate arqc / Valid ARQC`). We can add a feature to copy all logs of the selected test on pressing `C`/`Ctrl/Cmd + C` when the test item is selected in the list. This way you won't have to manually manage the selection and can quickly copy/paste the whole test log into Github issues or shared with others in Slack. Is this something that would work for you?

**Comment by bobwieler** [comment]
I think that sounds good. Right now copying the test header doesn't do anything so having it instead copy all of the logs for a test would be helpful. Thank you for your quick turn around on things.

**Comment by ArtemGovorov** [comment]
Thanks for your feedback. We have added the new feature as discussed in [the latest core v1.0.1620](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). After you update, pressing `C`/`Ctrl/Cmd + C` when a test header is selected in the list, should copy all of its logs with file and line numbers as in Wallaby 1 output.
