### ISSUE TITLE
Support VS code?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#341]
Maybe I'm too early to start asking this since VS code just announced beta version support extension ;) (https://code.visualstudio.com/updates)

Curious if there's plan to support it.

**Comment by ArtemGovorov** [comment]
https://twitter.com/wallabyjs/status/667125411986325504 :)

**Comment by kwonoj** [comment]
:+1:

**Comment by ArtemGovorov** [comment]
http://dm.gl/2015/11/26/wallaby-for-visual-studio-code/
