### ISSUE TITLE
Log statements outside of the project's code are not displayed in the logs

### ISSUE THREAD

**Issue by bobwieler** [wallabyjs/public#3410]
### Issue description or question

We often need to debug issues that are in libraries that we import. Any console.log statements that are in our project's code is being displayed however any console.log that we add to an imported library are not. This is something that used to work prior to Wallaby 2.0 and is incredibly important for debugging.

As an example, the following is the log output when running the tests:

<img width="903" alt="Screenshot 2024-10-23 at 15 31 36" src="https://github.com/user-attachments/assets/8e8acc1f-8b66-4372-a6eb-8879fa314f15">

What gets displayed in Wallaby's logs is:

<img width="830" alt="Screenshot 2024-10-23 at 15 31 46" src="https://github.com/user-attachments/assets/83cde2c1-795b-46f4-87a9-4fa6e2679627">

The console.log statement with "I am inside of a library" is no longer being displayed.

**Comment by ArtemGovorov** [comment]
Thanks for raising the issue. 
We had indeed displayed console.log-s from node modules code before, though without any location where they have been logged from.
We have just added in to Wallaby 2, and are also now capturing and displaying the location as well:
![l](https://github.com/user-attachments/assets/c5e478cf-c647-497e-9bf8-a0f558251ccd)

Please update to [the latest core v1.0.1614](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to get the change.
