### ISSUE TITLE
wallaby v2 runs slowly or becomes unresponsive while executing setup code while running vitest inside intellij 2024.2

### ISSUE THREAD

**Issue by bhvngt** [wallabyjs/public#3412]
### Issue description or question

I have just upgraded wallaby in jetbrains 2024.2. While running wallaby, I am receiving following crash dump

wallaby detects vitest as my framework and runs all my tests. However, when I try to change any code, it runs very slow in reporting the changes (it takes . It warns for long running on my setup file. I have some code executing during my setup but it has never timed out when run from cli. When I use vitest on cli, no timeout occurs and everything works fine and responsive. My test for a given file completes in 1-2 sec.. 

### Wallaby diagnostics report

https://gist.github.com/bhvngt/98799b74fdadf472aca9e7e9925b3cb3

**Comment by smcenlly** [comment]
Thanks for providing your diagnostics report!

Based on your report, we don't think that this is related to anything new in the updated Wallaby, or your setup code.

What we saw from your Wallaby Diagnostics report was that Wallaby is getting stuck in executing the same test over and over again as a result of changes to `test/__recordings__/TestContext_2156154716/should-trace-spanned-calls_1880847033/recording.har`.

Wallaby determines and tracks the files/tests for your project based on your Vitest test patterns. In contrast, Vitest does this a little differently, by looking at the imports/exports of your files. While both methods work differently, they achieve the same result, but have some different trade offs. In the case of Vitest, you can get into a state where your tests won't re-run automatically (that's their trade off). Conversely, in the case of Wallaby, you can get into a state where tests are re-run too aggressively, which is what's happening in your case.

We're not sure that the `recording.har` file is for, or how it's being generated, but we do have a fix for you:

Please update your vitest configuration and provide an exclude pattern for this file (and others also if relevant). You can do this with the [`exclude` configuration option](https://vitest.dev/config/#exclude). Once you make that change, Wallaby should no longer try and execute tests after your `.har` file changes.

**Comment by bhvngt** [comment]
Thanks @smcenlly. That a miss from my end. I am using [PollyJs](https://netflix.github.io/pollyjs/#/) for mocking fetch calls. It records fetch calls and keep it as `har` files under `__recordings__` folder. This should have been ignored while running vitest. After excluding these files, wallaby is running fine. Thank you for your support and solution.
