### ISSUE TITLE
Feature Request: Errors panel search bar

### ISSUE THREAD

**Issue by kalkson** [wallabyjs/public#3417]
### Issue description or question

Hi!

Thank you for the wonderful v2 major update - I love it! However, after it was released, I discovered that the search bar is no longer accessible via the cmd + F shortcut inside the Error panel, which has impacted my Wallaby workflow and daily testing process.

I typically debug tests by looking for components/phrases inside the rendered HTML that displays in the Wallaby Error panel. I would love to have the ability to easily search for these by typing a phrase, rather than being forced to scroll through the panel as I currently have to do.

Is there any chance we will get the search bar back inside the panel, or is there some obstacle that prevents it from being implemented again?

**Comment by ArtemGovorov** [comment]
Thanks for posting the feature request and for your kind words. We do have a plan to add search for errors panel.

**Comment by DHFW** [comment]
Similarly like searching in the Errors panel, I would like to be able to search inside the Logs panel.

**Comment by ArtemGovorov** [comment]
Until a better solution is available, if you're using VS Code, you can open Logs or Errors in the Side Panel, which has a find widget accessible via `Ctrl/Cmd + F`:

![lc](https://github.com/user-attachments/assets/0a8a680d-31de-4116-ad80-2d0d9b40ee74)

**Comment by kalkson** [comment]
> Until a better solution is available, if you're using VS Code, you can open Logs or Errors in the Side Panel, which has a find widget accessible via `Ctrl/Cmd + F`:

@ArtemGovorov
Does not work in my VSCode at the moment. Any tips with that?

**Comment by smcenlly** [comment]
@kalkson - it does not work if you use the Overview panel at the bottom of the screenshot above (currently [not supported by VS Code](https://github.com/microsoft/vscode/issues/173643)).

The find will **only work right now** in the Side View (when opened beside your code). If you have changed the `wallaby.sideView.mode` setting to `In View`, it also won't work for you right now.

Our team is prioritizing the development of Find functionality within the new UI.

It seems you may not have opened the side view before pressing Ctrl+F, or perhaps you've customized the `wallaby.sideView.mode` setting in VS Code. If neither of these cases apply, could you please share a short animated gif to help us understand your workflow?

**Comment by smcenlly** [comment]
Closing this issue, as search is now available in the Errors panel (both Overview and Side View)
