### ISSUE TITLE
Not updated error window after compilation error fixed

### ISSUE THREAD

**Issue by randspy** [wallabyjs/public#3422]
### Issue description or question

Hi, when I get a typescript compilation error I can see it in the error window. When I fix it the error persists in the error window. Tests are still executed and I can see the result in the editor. It happens only when a test is selected in Failing tests. When 'All logs and errors' are selected then it goes back to normal after typescript error fix.

<img width="1606" alt="image" src="https://github.com/user-attachments/assets/35c6eee4-3fed-4fa3-9b23-89419ead269d">

Link to my repo:
https://github.com/randspy/fitness-dashboard

Env: MacOS 15.1, Cursor: 0.42.4
### Wallaby diagnostics report

[report.txt](https://github.com/user-attachments/files/17745851/report.txt)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in [the latest core v1.0.1637](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
