### ISSUE TITLE
Bad diff in Failings test

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#343]
Mocha Console Output:

![2015-11-19 unexpected js compare bug for github mocha console output](https://cloud.githubusercontent.com/assets/341600/11267659/da68d5ce-8eac-11e5-9b1e-9984a19df4df.png)

In Wallaby:

![2015-11-19 unexpected js compare bug for github](https://cloud.githubusercontent.com/assets/341600/11267583/6eeccb3e-8eac-11e5-9c7c-96205744019e.png)

**Comment by hellboy81** [comment]
In walalby.js output  background should be white instead of black

**Comment by ArtemGovorov** [comment]
Is it from unexpected.js? If that's the case, wallaby.js just renders whatever it sends.

**Comment by ArtemGovorov** [comment]
Anyway, could you please provide some code where I could reproduce it to have a look?

**Comment by hellboy81** [comment]
>Is it from unexpected.js? 
Yes

>If that's the case, wallaby.js just renders whatever it sends.
IMHO you console output wrong.  Why background BEFORE is whit and AFTER is black?

**Comment by ArtemGovorov** [comment]
> console output wrong. Why background BEFORE is whit and AFTER is black?

I don't create the output, don't change it and don't control rendering. I get ANSI coloured output from unexpected.js and render it with a standard IntelliJ platform ANSI renderer. There must be a bug in one of them, if you can provide an example, that I can run, I could have a look and see where the problem is and how to fix it.

**Comment by hellboy81** [comment]
May be Webstorm bug?

**Comment by ArtemGovorov** [comment]
Maybe, it uses IntelliJ platform ANSI renderer. I can find out if you provide some code to reproduce.

**Comment by ArtemGovorov** [comment]
Let me know if have a chance to reproduce it, happy to re-open the issue.
