### ISSUE TITLE
Wallaby sometimes failing to restart

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3434]
This is an old issue that you've helped me with before but it didn't quite go away, and it's taken me ages to get around to producing a minimal repro.

Here's a slightly changed copy of a repo you set up for the previous issue I was having:
https://github.com/tslocke/wallaby-3433-tweaked

I made a small change to the vite config, and added a tsconfig and some stub tests. With Wallaby running, if I type ".only" next to `test(...)`, Wallaby will sometimes get stuck on `.onl` is not a function, as you see here:

![image](https://github.com/user-attachments/assets/1aa0e6bf-6aa4-4b5c-83ce-d10ae343676b)

The tricky part is the "sometimes". After getting lucky with an early reproduction, I messed around and found it to be very rare to see the problem in this little repo. My main repo has the problem very consistently. I spent some time trying to isolate what it is in my main repo that leads to this, and ended up adding some extra bits from my project to this mini repo. It seems to be showing the problem more consistently now and I was able to grab a diagnostic report. Hopefully this will be enough for you to see the problem.

It's obviously a race hazard as you need to experiment with different speeds of typing '.only' to see the problem. (I guess there's nothing special about .only -- it's more that you introduce an error and then remove it again quickly -- but that's how I typically see the issue)

https://gist.github.com/tslocke/126166eee741baaac842ad4b387f8bd1

**Comment by smcenlly** [comment]
Thanks for letting us know about the problem. We were able to reproduce the issue but also had issues getting it to occur (certainly couldn't make it happen reliably, but over time, we seemed to always make it happen).

We believe we have found and fixed the problem. There was an issue with the abort signaling mechanism that we provide to vitest. We're not sure why this was happening, as the problem also occurs when no abort signal is provided (which seems to be the default behavior when vitest runs from the CLI).

Please update to Wallaby core `v1.0.1660` (you can use the VS Code command, `Wallaby.js: Force Core Update`). If you see the problem again, please let us know.

**Comment by tslocke** [comment]
Thanks for looking into this. Unfortunately it doesn't seem to be fixed in 1.0.1660. The error is still happening quite reliably in my project. I don't know if it will help but if you're able to add a lot of source code and tests from some other project, that might make it easier to reproduce the problem. I did a bunch of experiments with long running tests yesterday (with both timeouts and big computation loops) but I wasn't able to get the small repo to exhibit the bug as consistently as my real project.

**Comment by tslocke** [comment]
No idea if this will be useful info but I thought I'd mention it - I've noticed a change in the pattern since 1.0.1660.

The bug used to typically show up as I was typing '.only'. It now seems to show up mostly when deleting '.only'.

So a different pattern in terms switching from/to a full test run vs a short one. Might just be a coincidence but I've noticed that pretty consistently.

**Comment by tslocke** [comment]
Another FYI - I had a stuck node process at 100% cpu today. I used to get these a lot with Wallaby but you fixed that. That's the first time I've seen one in a long time.

**Comment by tslocke** [comment]
Also fyi, the failing-to-restart issue is definitely much more rare now 👍

**Comment by ArtemGovorov** [comment]
We couldn't reproduce the problem yet, but we've made some changes that we think may help / fix the problem that we'd like for you to try.

Could you please update to Wallaby core `v1.0.1663` and let us know if it fixes things for you?

**Comment by tslocke** [comment]
Looking good : ) I haven't seen the issue for a while. Thanks for working on this. I recently took on a client project in Ruby and am reminded what coding without Wallaby is like. The pain!
