### ISSUE TITLE
Inline display lost ability to detect circular references?

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3435]
This is an old feature request from me: https://github.com/wallabyjs/public/issues/3044

I'd still really like that, but short of that the issue seems to have got a lot worse because the circular reference detection whic you can see in that screenshot (`[Circular]`) doesn't seem to work any more. If I inspect an object which is a SolidJS proxy, it now looks like this:

![image](https://github.com/user-attachments/assets/ae9bcd82-ed0d-484f-8b70-16464489668d)

Wallaby seems to give up on the loop after about 15 iterations. It's very difficult to inspect the data of course.

Thanks

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue with circular ref reporting is now fixed and the fix is published in [the latest core v1.0.1661](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
