### ISSUE TITLE
on startup of wallaby "window is not defined"

### ISSUE THREAD

**Issue by dmitryya-tr** [wallabyjs/public#3441]
### Issue description or question

tried to run wallaby against one of the project in nx angular monorepo got  " window is not defined" error in errors window. no tests are found in the list but nothing is runned 
 no suctome config was used, only node version was defined in wallaby.node 

tests are standard jasmine angular tests, except coverage-threshold is managed in separate js file 
### Wallaby diagnostics report 
[wallaby-report.txt](https://github.com/user-attachments/files/18108819/wallaby-report.txt)

**Comment by dmitryya-tr** [comment]
@NikGovorov  here is package.json`{
  "name": "@*-hidden-*/auth",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^16.2.0",
    "@angular/core": "^16.2.0",
    "karma-jasmine": "~4.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-jasmine-html-reporter": "^1.7.0",
    "karma-verbose-reporter": "0.0.6",
    "karma-spec-reporter": "0.0.32",
    "karma-sabarivka-reporter": "^3.3.1",
    "karma-coverage": "^2.2.0",
    "@angular-devkit/build-angular": "~16.2.0",
    "rxjs": "7.5.6",
    "@*-hidden-*/infra-services": "*",
    "@*-hidden-*/infra-ui": "*",
    "@angular/forms": "^16.2.12",
    "@angular/cdk": "^16.2.11",
    "typescript": "~5.1.3",
    "@*-hidden-*/ui-kit": "0.1.0-rc",
    "@ionic-enterprise/identity-vault-5.14.4": "file:libs/ionic-enterprise-identity-vault-5.14.4.tgz",
    "@angular/platform-browser": "^16.2.12",
    "*-hidden-*-upgrade": "*",
    "@angular/animations": "^16.2.12",
    "lodash-es": "^4.17.21"
  },
  "dependencies": {},
  "sideEffects": false,
  "build-metadata": "package-build.metadata.json",
  "publishConfig":{"registry":"https://*-hidden-*.jfrog.io/artifactory/api/npm/"}
}`

in usual case test would be: " run as nx run auth:test "  from top most folder

it is part of nx monorepo

**Comment by smcenlly** [comment]
Does `npm test auth` run tests in CLI for `auth` project?

Your angular test builder configuration for this project is missing an `options` section. When we try and do this and run from the CLI, we get an error. This is also what is causing Wallaby to fail. Can you please try fixing this project's test configuration, we think it will solve your problem.

**Comment by dmitryya-tr** [comment]
as i mentioned before we are not running test thru 

`npm test auth`
we are running them thru
`nx run auth:test `
There is an options object in the root nx.json.  when I'm trying to autoconfig from root it throws the same error.
options in nx.json looks like that: 
`"options": {
        "main": "{projectRoot}/src/test.ts",
        "tsConfig": "{projectRoot}/tsconfig.spec.json",
        "karmaConfig": "{projectRoot}/karma.conf.js",
        "styles": [],
        "scripts": [],
        "stylePreprocessorOptions": {
          "includePaths": [
            "libs/styles",
            "libs/infra-ui/src/lib",
            "libs/*-mask-*/src/lib/form-button",
            "node_modules"
          ]
        },
        "codeCoverage": true,
        "progress": false,
        "watch": false,
        "browsers": "ChromeHeadless"
      }`

inside libs folder there is a target object that contains ` "test": {
      "executor": "@angular-devkit/build-angular:karma"
    }`

**Comment by smcenlly** [comment]
> as i mentioned before we are not running test thru 
> 
> `npm test auth`
> we are running them thru
> `nx run auth:test `

Sorry, I understood that. I wanted to confirm that they actually execute successfully. I wasn't sure based on your previous response.

---

We think we understand what's going wrong, but we're not quite sure why it's not working and require some additional information. It appears that the `nx` targetDefaults aren't being merged into the final configuration for some reason, and that's what Wallaby is not happy about.

Can you please:
* Provide us with your diagnostic report after starting Wallaby on the root of your project? It should be a little different to starting on one of the nested projects, and the content of the report should help us work out what's going on.
* Provide us with the `dependencies` and `devDependencies` from your root `package.json`. They should be provided in the diagnostic report, but just incase they're missing, please also provide them in your reply.

**Comment by dmitryya-tr** [comment]
ok no problem, created new report from root, added copypaste of dependencies and devdependencies from root package json   
[wallaby-report.txt](https://github.com/user-attachments/files/18161990/wallaby-report.txt)

**Comment by smcenlly** [comment]
Thanks for the diagnostics report. We've been able to reproduce your problem. Will let you know when we have a fix.

**Comment by smcenlly** [comment]
We believe we have fixed your problem (it's now working for us).

Can you please update to Wallaby core `v1.0.1671`, it should work for you. If Wallaby doesn't automatically update, you can use the `Wallaby.js: Force Core Update` VS Code command.

**Comment by smcenlly** [comment]
No problem. If you’re having other issues, we’d love to help.
