### ISSUE TITLE
Issue with babel macros (@linguist/macro) on a project using vitest and pnpm

### ISSUE THREAD

**Issue by jayzz55** [wallabyjs/public#3443]
### Issue description or question

I'm testing running WallabyJS in VS Code on my project that is using vitest and pnpm.

When starting WallabyJS, I run into `The macro you imported from "@lingui/macro" is being executed outside the context of compilation with babel-plugin-macros.` error which is thrown js-lingui in the source code [here](https://github.com/lingui/js-lingui/blob/e45a2af5dfc1c88131fa8196d596e0f0f25678ea/packages/babel-plugin-lingui-macro/src/macro.ts#L46).

![image](https://github.com/user-attachments/assets/aef51af5-d81f-4963-90ec-4406b7eddce6)

I am able to run the test on my CLI (using `npx vitest`) but not wallabyJS, this led me to believe that WallabyJS is not able to load babel macros correctly.

### Wallaby diagnostics report

[report.txt](https://github.com/user-attachments/files/18222104/report.txt)

**Comment by smcenlly** [comment]
Thanks for providing your diagnostics report.

We tried to reproduce your problem but I think we may need your babel config (or else we're missing some other pieces of your project configuration).

We created a [sample repo](https://github.com/wallabyjs/wallaby-3443) with your dependencies and base configuration. Can you please try updating the sample repo to break in the same way as your project? Please start with adding your babel configuration.

Alternatively, if you're able to provide us with your project, or another sample, we can look at that instead?

**Comment by jayzz55** [comment]
@smcenlly 

Here is the sample repo where i'm able to reproduce the bug: https://github.com/jayzz55/wallaby-3443

screenshot:

![image](https://github.com/user-attachments/assets/171eb9df-b345-46bc-a28b-98d64e8b6c10)

the `.babelrc` config is:
```
{
  "plugins": ["graphql-tag", "macros"]
}
```

**Comment by smcenlly** [comment]
Thanks for updating the sample repo. We were able to reproduce the problem and have updated Wallaby to fix the issue.

The issue stems from a bug in the [vite-plugin-babel-macros](https://github.com/itsMapleLeaf/vite-plugin-babel-macros) plugin. Its `transform` function, `async transform(source: string, filename: string)`, receives a `filename` that can end in a querystring (e.g. `filename?timestamp=1234567`). However, the plugin's [regexes](https://github.com/itsMapleLeaf/vite-plugin-babel-macros/blob/7bf11fa60502147dbffa491aaad91b558fecf765/src/plugin.ts#L7-L8), which determine which files to process, doesn't account for filenames with query strings:

```typescript
const sourceRegex = /\.(j|t)sx?$/
const tsxRegex = /\.(j|t)sx$/ // all files are being interpreted as TS, so we'll treat JSX as TSX
```

We've updated Wallaby to patch this module when it's loaded to fix the bug.

Please update to Wallaby core `v1.0.1673`, it will fix your problem.
