### ISSUE TITLE
Clarify - Can the license be transferred between tools?

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#346]
I tend to use two IDE's - Visual Studio 2015 (but often it gets really slow on me) so if I'm just doing pure JavaScript I'll switch to Sublime Text.

Are your licenses transferable between different application plugins?

**Comment by IPWright83** [comment]
Hadn't seen the "Freedom" license before

**Comment by ArtemGovorov** [comment]
Yep, 'Freedom' license should work for you in this case. Please note however that we don't support Sublime Text yet.
