### ISSUE TITLE
Wallaby not finding src sub directory file in cache

### ISSUE THREAD

**Issue by infinetcloud** [wallabyjs/public#349]
Hi,
I have setup a very basic project to test out using wallaby with requirejs in Webstorm 11.0.1. I am getting the error Error: Script Error and after turning on debug I can see that wallaby is returning this error:

wallaby:middleware ENOENT: no such file or directory,  WebStorm11/wallaby/projects/467d2ab988276e85/instrumented/src/app/N/mock/Record.js

In trying to find a resolution, I moved the file Record.js into the app directory and the tests ran successfully. So it looks like if a file is in src/app/ its found but if its in a child folder src/app/N its not.

I suspect this is a problem in the wallaby.json configuration, pasted below are the three key files wallaby.json, test-main.js and the very basic Test Spec.

wallaby.json
```
{
  "files": [
    {"pattern": "lib/require.js", "instrument": false},
    {"pattern": "src/**/*.js", "load": false},
    {"pattern": "test/test-main.js", "instrument": false}
],

  "tests": [
    {"pattern": "test/**/*Spec.js", "load": false}
  ],
  "testFramework" : "jasmine",
  "debug" : true
}
```

test-main.js
```
// delaying wallaby automatic start
wallaby.delayStart();

requirejs.config({
  baseUrl: '/src',
  deps: wallaby.tests,
  callback: wallaby.start
});
```
test-spec.js
```
define(['app/core-uk','app/N/mock/Record'],function(core,Record){
    "use strict";

    var mockRec = new Record({
        type: 'employee'
    });


    describe("testModule",function()
    {
        it("should be true", function () {
            expect(core.PeriodNo(new Date())).toBe(1);
            expect(core.convertPeriod(new Date())).toBe(false);
            expect(mockRec.id).toBe(undefined);
            expect(mockRec.getFields().length).toBe(0);
        });
    });
});
```

**Comment by ArtemGovorov** [comment]
Hi,

I have created [this repo](https://github.com/ArtemGovorov/wallaby-349) reproducing the full structure and using the files you've listed. It works for me (on OSX and Windows in WS 11). Could you please try running it to check if it works for you, and if it does, could try finding the difference between it and your sample?

**Comment by infinetcloud** [comment]
Thanks Artem, I will give it a go and update you shortly.

**Comment by infinetcloud** [comment]
Hi Artem,

Okay looks like its just a path issue my directory structure was actually /N/mock/Record not /app/N/mock/Record .... PEBKAC case closed.

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
