### ISSUE TITLE
Warn if use test files included in files config section

### ISSUE THREAD

**Issue by marcalj** [wallabyjs/public#35]
I had a hard bug when running Wallaby with a config like this:

```js
'use strict';

module.exports = function () {
    return {
        files: [
...
            'app/scripts/**/*.js',
            'test/mock/**/*.js',
            //'test/spec/**/*.js',
        ],
        tests: [
            'test/spec/*/*.js'
        ],
        testFramework: 'jasmine@2.1.3'
    };
};

```

I've just copy the karma.conf files section into wallaby's files config section, and I realized afterwards I was adding spec files in both files and tests config sections.

Maybe a warning or something would be fine to detect this errors.

PD: It was working fine, but the IDE shows spec files as source code, no tests warnings.

**Comment by ArtemGovorov** [comment]
Good point, three different people had the same issue, I will have a look what can be done about it.
