### ISSUE TITLE
Tests fail in wallaby.js but run fine in Jasmine

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#350]
I've got some Jasmine tests that run without issue in Jasmine, but don't seem to run when I'm using wallaby. I've tried restricting the worker count like suggested but this makes no difference - I believe each test should be independent.

I've managed to put together a small project illustrating this, but being commercial code I'm not at liberty to post this in a public forum. I'd be happy to email over however if you're interested in looking into the issue.

**Comment by fvanwijk** [comment]
Could you create a repo with sample code that demonstrates the same issue?
I think you mean "Karma" where you wrote "Jasmine".

**Comment by IPWright83** [comment]
@fvanwijk I definitely mean Jasmine, I can run the tests fine using the SpecRunner.html but if I try to run them through the Visual Studio extension with wallaby the my expectations fail.

I can't put my source in a public repository unfortunately, the best I've managed to get permission to do so far is to send an email with the project in.

**Comment by ArtemGovorov** [comment]
@IPWright83 Please email the sample to wallabyjs@gmail.com and I'll have a look.

**Comment by ArtemGovorov** [comment]
@IPWright83 I have sent you an email with some config fixes and the explanation, should work now. Let me know if it doesn't fix the issue for you.
