### ISSUE TITLE
Improve reporting for shared expectation code

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#352]
I'm using Jasmine to declare all my tests, and in my case I've got lots of duplicate code - so I've moved into a helper function like this:

````
function verifyResult(actual, expected) {
   expect(actual.value).toBe(expected.value);
   expected(actual.myArray).toEqual(expected.myArray);
   ...
}

it("test1", function() {
   verifyResult({ value: 3, myArray: [ ] }, { value: 3, myArray: [ 1 ] });
});

it("test2", function() {
   verifyResult({ value: 3, myArray: [ 1 ] }, { value: 4, myArray: [ 1 ] });
});
````

The difficultly here is that Wallaby can obviously only show the results for 1 test inline e.g. It'd be nice to improve this somehow (I'm not exactly sure how) - possibly returning all the failed Expectations up slightly in the stack somehow to the actual spec that failed.

**Comment by ArtemGovorov** [comment]
Your example actually works as you are expecting, it displays inline results for both tests:

![assert](https://cloud.githubusercontent.com/assets/979966/11413610/810fdc72-9436-11e5-9f44-0b1d5d729a74.png)

From the code you've sent me recently I think the issue you're are having is different. In your case you are doing something like:

``` JavaScript
function verifyResultAsync(actual, expected, done) {
  setTimeout(function () {
    expect(actual.value).toBe(expected.value);
    expect(actual.myArray).toEqual(expected.myArray);
    done();
  }, 100)
}

it("test1", function(done) {
  verifyResultAsync({ value: 3, myArray: [ ] }, { value: 3, myArray: [ 1 ] }, done);
});

it("test2", function(done) {
  verifyResultAsync({ value: 3, myArray: [ 1 ] }, { value: 4, myArray: [ 1 ] }, done);
});
```

In this case the exception is raised within the `setTimeout` callback, so the error stack doesn't contain anything related to the original test. 

It's not wallaby specific issue, if you run the same tests in Jasmine, you will also not find any lines from the originating test in the error stack. There's no easy way to support it.

You may however restructure your test code a bit to make reporting in both plain Jasmine and Wallaby better:

![untitled](https://cloud.githubusercontent.com/assets/979966/11413825/5cd8a200-9439-11e5-9a6c-2dc663b5333b.png)

Let me know if it helps.

**Comment by IPWright83** [comment]
Thanks Artem,

I've not had an issue with Jasmine's reporting, or at least not through the browser (was going to upload an image but Github seems to be having issues with them at the moment).

I'm definitely going to take a look at that pattern and see how that improves things - it's worth it for the better error reporting.

Thanks
