### ISSUE TITLE
Test spec without require in node.js

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/public#353]
Is it possible to test files with `env: node` without `require`?

For example, we want to test calculator without specifying `require("../calculator.ts")` in the header of testSpec file. We want all files to be implicitly included to any test files.

**Comment by ArtemGovorov** [comment]
I don't think I understand the question. In node.js you export things from your modules and `require("../calculator.ts")` gives you the access to the exported things. Unless your modules add things to `global` objects, there's just no other way to access them.

If you could provide some more detailed sample, like a repository with code, I may be able to better address the question.

**Comment by ArtemGovorov** [comment]
Let me know if my response didn't address your question, happy to provide a more detailed answer.
