### ISSUE TITLE
Require assert lib only once

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/public#354]
Can I require assert lib in wallaby.js and pass it to test-spec file?

**Comment by ArtemGovorov** [comment]
You may use [the `bootstrap` function](http://wallabyjs.com/docs/config/bootstrap.html), `require` some libs, set them to global objects and then access them from your specs, if that's what you're asking.

``` JavaScript
bootstrap: function (wallaby) {
  global.expect = require('chai').expect;
}
```

then in your spec you may use `expect` global variable.
