### ISSUE TITLE
Specify file order in files section

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/public#356]
How can I explicitly specify the file order in the wallaby.js `files` section?
If I transpile code by typescript in my gulpfile then order is correct, but wallaby transpiles them in wrong order.

**Comment by ArtemGovorov** [comment]
You may specify files one by one, wallaby.js will just use the order your files are listed. If the order is correct, it should work.
However, if you are using reference comments in your `.ts` files, wallaby can automatically order them for you. Have a look into [the docs section how to do this](http://wallabyjs.com/docs/integration/typescript.html#ordering-source-files-with-reference-comments).

If suggestions above don't help, please provide your `gulpfile` and wallaby.js config so I could have a look.
