### ISSUE TITLE
Wallaby.js in Atom seems stuck in an infinite loop

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#358]
A few minutes ago, I got a notification in my Atom editor:

> Wallaby.js has been successfully updated  
> Atom plugin v1.0.17, Core v1.0.148

Since, then clicking on the `Start` button starts the spinning wheel in the notification area
of atom, but that's all. It is as if Wallaby.js got stuck in an infinite loop. I quit atom and relaunched
it without success. Wallaby.js won't work anymore.

Could there be an issue with the latest update?

**Comment by ArtemGovorov** [comment]
Could you please try opening Developer Tools in Atom (`Cmd/Ctrl + Alt + I`) and see if there's something logged there when you start wallaby?

**Comment by epsitec** [comment]
![wallaby-stack](https://cloud.githubusercontent.com/assets/3872435/11415186/02ee620e-9400-11e5-9490-0b8ae7c637f1.png)

**Comment by ArtemGovorov** [comment]
You may actually be right, there may be an issue with the latest update that has been rolled out recently.
Please close Atom, go to `c:\Users\Arnaud\.atom\packages\atom-wallaby` and delete `wallaby` folder there. Restart Atom, wallaby should update to the working version. Please let me know if it worked for you.

**Comment by epsitec** [comment]
Yes, it solved my issue. Thank you very much.

**Comment by ArtemGovorov** [comment]
Sorry for the inconvenience and thanks for reporting the issue.
