### ISSUE TITLE
how could I integrate wallaby with my own IDE (i.e. one I'm building)?

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#360]
I know you charge for your product. I just wonder if there's a way for 3rd party developers to do the work of making more editors, for whose usage, you can charge for? something like that.

**Comment by ArtemGovorov** [comment]
@faceyspacey There are some options that we may consider and are considering with some IDE vendors.  Please send me an email to wallabyjs@gmail.com and we may discuss the options.
