### ISSUE TITLE
Browserify, Babel, Mocha, Node - "window is not defined"

### ISSUE THREAD

**Issue by jrsearles** [wallabyjs/public#362]
I have a repo the uses Browserify and Babel with mocha node tests. I've been trying to get Wallaby going using Visual Studio Code on windows but am hitting roadblocks. Here is my config:

```js
module.exports = function (wallaby) {
	return {
		files: [{
			pattern: "src/**/*.js",
			load: false
		},
		{
			pattern: "index.js",
			load: false
		}],
		
		tests: [{
			pattern: "test/**/*.js",
			load: false		
		}],
		
		compilers: {
			"**/*.js": wallaby.compilers.babel({
				babel: babel
			})
		},
		
		testFramework: "mocha",
		
		postprocessor: wallabify({entries: ["./index.js"], ignoreMissing: true}),
		
		bootstrap: function () {
			window.__moduleBundler.loadTests();
		},
		
		debug: true,
		
		env: {
			type: "node"
		}
	};
};
```

The error i get is:

​ReferenceError: window is not defined
​    at emitTwo (events.js:87:13)
​    at WebSocket.emit (events.js:172:7)

Which makes sense, however changing the bootstrap function to use `global` doesn't work.

**Comment by ArtemGovorov** [comment]
@jrsearles Wallabify doesn't (yet?) support node environment. No one really asked for this before. Does it work for you without browserify?
``` JavaScript
module.exports = function (wallaby) {
    return {
        files: ["src/**/*.js", "index.js"],

        tests: ["test/**/*.js"],

        compilers: {
            "**/*.js": wallaby.compilers.babel({
                babel: babel // may need to configure presets: ['...'] if using babel 6
            })
        },

        debug: true,

        env: {
            type: "node"
        }
    };
};
```

**Comment by jrsearles** [comment]
Thanks! That seems to get me closer. I now get an error about `describe` not being defined:

​TypeError: (0 , _mocha.describe) is not a function
​ d:\github\sandboxr\test\api.tests.js:6:0
​TypeError: (0 , _mocha.describe) is not a function
​ d:\github\sandboxr\test\assignment-expressions.tests.js:4:0

I get this whether or not a set `testFramework` to "mocha". I am importing as seen below. These tests work from gulp-mocha or the command line (with babel compiler option)

```js
import {describe, it} from "mocha";
```

**Comment by ArtemGovorov** [comment]
Wallaby loads mocha before tests (to register reporter, hook up its handlers, etc.), so maybe the issue is related.

Try adding this to your wallaby bootstrap function:

``` JavaScript
module.exports = function (wallaby) {
    return {
        ...
    bootstrap: function () {
      var modulePrototype = require('module').Module.prototype;
      var originalRequire = modulePrototype.require;
      modulePrototype.require = function (filePath) {
        var exports = originalRequire.call(this, filePath);
        if (filePath === 'mocha') {
          exports.describe = global.describe;
          exports.it = global.it;
        }
        return exports;
      };
    }
    };
};
```

BTW, mocha exports globals, so just commenting out the line:

``` JavaScript
import {describe, it} from "mocha";
```
should also work (in wallaby/gulp-mocha/command line).

**Comment by jrsearles** [comment]
Thanks - this got me going.

**Comment by ArtemGovorov** [comment]
Just realised that `require` function will patched every time your tests run, but should really be patched just once:
``` JavaScript
module.exports = function (wallaby) {
    return {
      ...
      bootstrap: function () {
        var modulePrototype = require('module').Module.prototype;
        if(!modulePrototype._originalRequire) {
          modulePrototype._originalRequire = modulePrototype.require;
          modulePrototype.require = function (filePath) {
            var exports = modulePrototype._originalRequire.call(this, filePath);
            if (filePath === 'mocha') {
              exports.describe = global.describe;
              exports.it = global.it;
            }
            return exports;
          };
        }
      }
};
```
