### ISSUE TITLE
Restart wallabyjs when saving updated wallaby.json

### ISSUE THREAD

**Issue by KenVanGilbergen** [wallabyjs/public#363]
It seems that whenever I update my wallaby.json file, I need to click the restart Wallaby option in visual studio solution explorer.

Seems that the default should be restart on change with an option to disable it if people have a good reason for this?

**Comment by ArtemGovorov** [comment]
Sounds good.

**Comment by brettjacobson** [comment]
:+1:

**Comment by smcenlly** [comment]
We don't have any plans of changing this behavior. Having said that, the latest version of Wallaby now supports `Automatic Configuration` and no configured file is required at all for most projects.
