### ISSUE TITLE
Question - How to debug tests (e.g. in Chrome?)

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#364]
Hi, thanks for this fantastic software. Am in the process of discovering all the wonderful features and one of the things I could not discover was, how to debug my tests? Currently, I have solved the issue by running Karma on side and debug tests in Chrome, but would be nice just to use one solution. Is this possible? Thanks!

**Comment by fvanwijk** [comment]
See #74

**Comment by tomitrescak** [comment]
Ha! I promise I searched for word "Debug" between issues. Yup, it's duplicate.
