### ISSUE TITLE
Code Coverage Metrics

### ISSUE THREAD

**Issue by lprichar** [wallabyjs/public#368]
I got the impression from the website that we could see code coverage metrics with Wallaby (e.g. your code is 80% covered).  I'm not seeing those numbers in Visual Studio.  Am I missing something?

**Comment by ArtemGovorov** [comment]
Code coverage report is mentioned in our [plans to implement on the website](http://wallabyjs.com/#plans). Here is the feature request - https://github.com/wallabyjs/public/issues/38, please feel free to join the discussion about how you'd like to see it.
