### ISSUE TITLE
[discussion] [support neded] The best way to detect line with missing stubs

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#371]
In exception message 
```
"before each" hook: timeout of 2000ms exceeded
```

there is no info available about line where stub function has been called, but w/o callback 

In 99.9999%  this is missing stub declaration.

I should manually check all the code under test, to detect this issue (green/gray).

Is there possible to automate this process?

**Comment by ArtemGovorov** [comment]
The callback in an async hook may be not invoked for many reasons:

``` JavaScript
beforeEach(done => {
   // do anything and not invoke the `done callback`
});
```

I doubt that I could do anything about it. There's no error I could report, no line I could highlight. 

If you have some specific idea how to make it better, please let me know.
