### ISSUE TITLE
Marketing idea

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#372]
I think it would be great marketing for you guys to submit pull requests to popular open source projects / boilerplates that would add a functioning wallaby.js config file to the project.

I'll throw out https://github.com/erikras/react-redux-universal-hot-example as an example of where I think it would be great to have.

**Comment by ArtemGovorov** [comment]
Thanks for the suggestion, [have created the pull request](https://github.com/erikras/react-redux-universal-hot-example/pull/679) with wallaby config.

**Comment by ArtemGovorov** [comment]
@chrisblossom your feedback in the related PR is welcome
