### ISSUE TITLE
SyntaxError when including foundation-apps

### ISSUE THREAD

**Issue by HenryZouInterSystems** [wallabyjs/public#373]
I am getting an error when including foundation javascript file. It complains about SyntaxError. This error is only happening when using wallabyjs; normal karma gulp task runs without any error.

Foundation-apps github: https://github.com/zurb/foundation-apps

Foundation-apps bower dependency:     "foundation-apps": "1.1.0"

Wallabyjs Config: 

module.exports                  = function(){
  return {
    basePath : '..', // Ignored through gulp-karma
    "files"        : [
      "src/common/bower_components/foundation-apps/dist/js/foundation-apps.js"
    ],
    "tests"        : [
      "test/unit/common/**/*ests.js"
    ],
    "testFramework": "jasmine"
  };
};

Error:
Failed to parse src/common/bower_components/foundation-apps/dist/js/foundation-apps.js, SyntaxError: Unexpected token (6:1228)
  at emitTwo (events.js:87:13)
  at process.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:686:10)
  at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by ArtemGovorov** [comment]
In your `files` list, set [`instrument: false`](http://wallabyjs.com/docs/config/files.html#file-object) flag to the library (it also makes sense to do for all other libraries that you may use in future).
```
{pattern: "src/common/bower_components/foundation-apps/dist/js/foundation-apps.js", instrument: false}
```

Let me know if it helps.

**Comment by HenryZouInterSystems** [comment]
That worked. Thanks!
