### ISSUE TITLE
Mocha & Node

### ISSUE THREAD

**Issue by jenius** [wallabyjs/public#374]
I'm sure there's a way to do this, but I am unable to get it working. Spent a bunch of time with the docs, but I'm just getting no feedback from the console, and it's saying zero tests run, showing white boxes next to each line in the test file.

Could someone give me a push in the right direction? Here's the repo I'm using it with, fairly simple stuff: https://github.com/jenius/stockfighter-node -- config is in the `test` folder (I'm using Atom, I did select it specifically as the config)

**Comment by ArtemGovorov** [comment]
The config has to be in the root folder, the rest looks ok. Try moving the config to the root and let me know if it helps.

**Comment by jenius** [comment]
I right clicked it and selected it as the config in Atom. Does that not do the trick?

**Comment by ArtemGovorov** [comment]
Selecting it is just a way to tell wallaby.js which config to use if you have a few of them. The config itself has to be in the root folder.

**Comment by jenius** [comment]
Ah that's too bad. Would be nice if it could be in the test folder, makes things a lot cleaner. Ok well I moved it and it's now throwing an error at least. Looks like I need to register babel, `mocha.opts` including it as a compiler won't do the trick. I think this is enough to get me there, thanks!

**Comment by ArtemGovorov** [comment]
@jenius Agreed, we need to implement the support, here the issue for that - https://github.com/wallabyjs/public/issues/68

Re: babel, yes, you need to register a babel compiler, it's [pretty straightforward](http://wallabyjs.com/docs/integration/es-next.html)

**Comment by jenius** [comment]
Ok well, closer but still having issues. I configured babel to work and now it is trying to parse the file, but more or less failing miserably. It is unable to correctly import files. Not exactly sure how to handle this -- I pushed an update to the same repo as above. In order to replicate the issue, you need to copy `test/config.sample.js` to `test/config.js` then you will see it.

First issue is that it can't require the root. If you change `import API from '..'` to `import API from '../lib'` this line will pass fine, confusingly. Then it is unable to import `./config`, even though it is there and runs fine with a manual `mocha` run. I went a step further and just copy/pasted the contents of `config.js` into the file and removed the import, then it started having problems with chai's `should` assertions.

I feel like I'm still missing something big here, any ideas? And by the way, thanks so much for the quick and accurate support!

**Comment by ArtemGovorov** [comment]
@jenius When you `import * from '..'` node uses `package.json` to find out what `.js` file to load in `'..'`. With wallaby.js you [need to list all files that are used in your tests](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39), so adding `package.json` to your `file` list should do the trick:
```
...
files: ['index.js', 'package.json', 'lib/*'],
```

**Comment by ArtemGovorov** [comment]
The same applies to your `config.js` file - you need to add it to your files list as well:
```
...
files: ['index.js', 'package.json', 'test/config.js', 'lib/*'],
```

**Comment by jenius** [comment]
Awesome, that is very helpful, thanks! Almost there. In `mocha.opts` I require a test support file, and wallaby isn't loading this. Is there a way for me to pass in mocha options to wallaby to have it load this support file as well?

**Comment by ArtemGovorov** [comment]
Yes, there's the [bootstrap function](http://wallabyjs.com/docs/integration/node.html#mocha-require-equivalent) that you may use (don't forget to include your helper to the `files` list):
``` JavaScript
  return {
    files: ['index.js', 'package.json', 'test/config.js', 'test/support/helpers.js', 'lib/*'],
    tests: ['test/index.js'],
    env: {type: 'node', runner: 'node'},
    testFramework: 'mocha@2.1.0',
    debug: true,
    compilers: {
      '**/*.js': wallaby.compilers.babel(config)
    },

    bootstrap: function () {
      require('./test/support/helpers');
    }
  }
```

**Comment by jenius** [comment]
Excellent. For further customizing mocha options in here, I understand that this is possible through `wallaby.testFramework`. Is there any way I can log out this object so I can see what it is and be able to figure out how to add options myself?

**Comment by ArtemGovorov** [comment]
Sure, add `console.log`
``` JavaScript
    bootstrap: function (w) {
      console.log(w.testFramework);
      require('./test/support/helpers');
    }
```

and have a look into wallaby [console output in Dev Tools](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting). It's an [instance of this object](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L74).

**Comment by jenius** [comment]
Perfect, thanks so much. Just got everything working. You're the man @ArtemGovorov :+1:

**Comment by ArtemGovorov** [comment]
Cool, thanks for the update. Let me know if you hit any bumps, happy to help.
