### ISSUE TITLE
Visual Studio: Scrollbars don't allow viewing of full message

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#375]
I'm currently writing a test, and I want to see the expected output - unfortunately because I've got quite a long line I can't see the output that wallaby logs, and the scrollbar, even far right chops the message in half...

The only way I can view the message is to start resizing the code editor which is a bit annoying. Any chance of being able to include this is the scrollable area somehow?

![image](https://cloud.githubusercontent.com/assets/1374775/11811257/6c503fc0-a32c-11e5-97ae-810a82de6f20.png)

**Comment by ArtemGovorov** [comment]
@IPWright83 The message is not a content of the file (there'd be lot of issues it we'd make it to be a part of the file content). So unfortunately it's not selectable, doesn't participate in the layout calculations, doesn't affect scrollbars, etc. On the other hand, it doesn't cause scroll bars to change size/flicker when the message is changing (and generally speaking the message can be huge, so we can't always display it there).

Having said that, there're a few ways to make it work for you.

One way would be to display `Wallaby Failing Tests` output (`Ctrl + Alt + O`) to see the full message:

![2](https://cloud.githubusercontent.com/assets/979966/11829769/c55c1a26-a3ea-11e5-8ba8-e0b7c0701626.png)

Another way is to press `Alt + Shift + F10` while on the line and select `Show line tests` (or bind `Wallaby.ShowLineTests` command to any shortcut and use it):

![2](https://cloud.githubusercontent.com/assets/979966/11829763/b8edc0c8-a3ea-11e5-8920-dade0642b23c.png)

One more way (which I personally prefer) would be to add a line break somewhere to make the first line shorter:

![1](https://cloud.githubusercontent.com/assets/979966/11829751/a0ec0e62-a3ea-11e5-8639-9242dbc7b8d6.png)

You may remove the line break after you see the message or leave it if you find that your code is more readable with the line break (which I sometimes do).
