### ISSUE TITLE
Incorrect display of console.log or error messages (atom)

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#376]
If I insert a comment into my ES6 code, the `console.log()` output and errror messages get out of sync with the _real lines_. Note also that the green dots in the margin don't show up properly for the second call to `console.log()` in following example:

![wallaby-4](https://cloud.githubusercontent.com/assets/3872435/11845504/88b6ba02-a414-11e5-9ab8-05f33a0d7a3d.png)

This can be reproduced with the current atom editor in the `electrum` repository (https://github.com/epsitec-sa/electrum). The tests are in the `./src/test/` folder.

**Comment by ArtemGovorov** [comment]
It looks like the issue in babel 6 source maps generation. Works fine with babel 5. Have reported the issue - https://phabricator.babeljs.io/T6842. 

For now I have added a workaround in wallaby core v1.0.153, once your core gets updated (automatically) the issue should be fixed.

**Comment by epsitec** [comment]
Thank you very much for your quick response. Your quick fix works for me.
