### ISSUE TITLE
Debugger support for wallaby

### ISSUE THREAD

**Issue by sairamkunche** [wallabyjs/public#378]
We are planing to use wallaby in our project, Can you please let me know in which release we will found debugger support for wallaby?

**Comment by ArtemGovorov** [comment]
@sairamkunche You may monitor this issue for the feature - https://github.com/wallabyjs/public/issues/74. As for the time estimates, I can't give any promises yet.

**Comment by ArtemGovorov** [comment]
What IDE/editor are you using by the way?

**Comment by sairamkunche** [comment]
We are using visual studio code.. thank you :)
