### ISSUE TITLE
Test coverage report

### ISSUE THREAD

**Issue by aleksandrenko** [wallabyjs/public#38]
Add a test coverage progress indicator to push developers to write more unit tests (Gamification)

**Comment by ArtemGovorov** [comment]
Good idea, thanks. We are planning to add something like this along with coverage reports at some stage.

**Comment by Tineler** [comment]
Like i wrote on Twitter: I would love to see that! I think you could display the coverage for a single file somewhere in the upper right corner of the editor (if this is somehow possible). And the overall coverage in the run-console.

**Comment by browniefed** [comment]
:+1:

**Comment by endragor** [comment]
+1 to a view showing aggregated coverage info for the whole project (not sure if this is what the original poster meant)

**Comment by DinisCruz** [comment]
+1 this is really important

While we wait for official support, where is this data stored?

**Comment by ArtemGovorov** [comment]
@DinisCruz It is stored in memory, wallaby doesn't save any files if that's what you're asking about

**Comment by DinisCruz** [comment]
is there a way to access that data?

**Comment by ArtemGovorov** [comment]
@DinisCruz Not at the moment.

**Comment by hellboy81** [comment]
I mean also to track "writing progress".

Is there some metrics to answer the following questions:

- [How much additional time does unit testing take?](http://stackoverflow.com/q/3756796/444079)

- [Estimating of testing effort as a percentage of development time](http://stackoverflow.com/q/1595346/444079)

- [How do you estimate the time needed to write unit tests?](http://qr.ae/RoFuEP)

**Comment by hellboy81** [comment]
This metrics can be also reasonable:

- Estimate  time to write unit tests for existing code (with code coverage at least `N` %)

**Comment by fvanwijk** [comment]
@hellboy81 Hmm I think that calculating the estimates is no issue that Wallaby should solve. It's more like a Sonar thing (time to solve tech debt and tech debt percentage).

**Comment by hellboy81** [comment]
@fvanwijk  Can you provide more information about it?

**Comment by fvanwijk** [comment]
See http://www.sonarqube.org/evaluate-your-technical-debt-with-sonar/
Wallaby is just a test runner.
I suggest that you use tools like Sonar to do more in dept code quality/coverage analysis and let Wallaby only show the simple metrics that are already available, since it is measuring coverage through the instrumented code.

**Comment by hellboy81** [comment]
@fvanwijk KISS, use Excel, Luke!

**Comment by QuantumInformation** [comment]
Is there coverage build into the Idea version for wallaybyjs?

**Comment by ArtemGovorov** [comment]
@QuantumInformation  Only real-time coverage indicators, no reports yet.

**Comment by QuantumInformation** [comment]
Ok cool, well I'm very happy with it, I'm going to recommend it to my clients!

**Comment by tomitrescak** [comment]
Any progress on this? Would be great to see the overall statistics of the test coverage.

**Comment by DinisCruz** [comment]
Any updates, this is quite an important metric

**Comment by ArtemGovorov** [comment]
@tomitrescak @DinisCruz I'll post the news in this issue when there are some.

**Comment by ArtemGovorov** [comment]
We are working on the file-centric Coverage View in [Wallaby App](http://dm.gl/2016/07/19/wallaby-app/), in a meantime the already implemented Tests View can also be used to to inspect the coverage.

**Comment by DinisCruz** [comment]
@ArtemGovorov that App view is great

Question: how are you authenticating that the only that app is talking to wallaby engine (i.e. can the same functionality be invoked from other sites? (namely direct interaction with Webstorm)

**Comment by ArtemGovorov** [comment]
@DinisCruz Thanks! We're also working on file-centric view for the code coverage, which should better address this particular issue.
In the engine we are checking the `origin` header that contains the hostname of the server that served the HTML with the JS that opened the WebSocket connection, so other websites can not connect to the engine.

**Comment by ArtemGovorov** [comment]
Coming soon (this week): https://twitter.com/wallabyjs/status/765798386314412033

**Comment by dsifford** [comment]
Amazing @ArtemGovorov !

Question for ya: Is there any way currently, or any plans for the near future, to open up the app view inside atom editor? I'd imagine adding that feature would be relatively straightforward, being that it's essentially just a feature-packed, electron application.

Thanks again for your work on this!

**Comment by ArtemGovorov** [comment]
@dsifford There're no near future plans, but you may try using [atom-web-view](https://atom.io/packages/web-view) to open http://wallabyjs.com/app. It seems to work, but I haven't tested it much and I'd at least expect a few usability issues, like it may not look great in a different colour theme and there may be some keyboard shortcuts conflicts.

![ui](https://cloud.githubusercontent.com/assets/979966/17758788/a50cbafc-6535-11e6-833b-bc44aa04f4c8.gif)

**Comment by dsifford** [comment]
@ArtemGovorov I'm aware of the web-view package. I mainly was asking this because the thought of putting together a simple package for this crossed my mind and I wanted to be sure that A) you weren't already planning one (which would likely be better) and B) it was alright if I did so, being that wallaby is a trademarked, non-open-source product.

**Comment by ArtemGovorov** [comment]
@dsifford If the the web-view package is not enough for now, we don't mind if you create the package that does a better job of embedding the app.

**Comment by ArtemGovorov** [comment]
Released in Wallaby.js App v1.0.4.

**Comment by DinisCruz** [comment]
Hi @ArtemGovorov what was released on App v1.0.4?

**Comment by ArtemGovorov** [comment]
Hi @DinisCruz, the [Files tab with coverage reports](https://twitter.com/wallabyjs/status/766207361648168960), the blog post/tutorial about it is coming soon (hopefully this week).
