### ISSUE TITLE
New WallabyJS User - Best way to run externally?

### ISSUE THREAD

**Issue by ghost** [wallabyjs/public#380]
I'm currently a new user to Wallaby, and preparing to make a proposal to management to purchase a handful of VS licenses.

My question is not so much about Wallaby itself, but how people are using it along with their CI environments.

For instance, I can configure Wallaby in a JSON file to import files and tests, but how can I run those tests in a CI environment, without having to recreate some other file that mimics the JSON file?  We have a few (4 :) ) Jasmine tests written using the "///reference" syntax to import the files under test, but we are finding that does not work for tests running via Wallaby.

How are people doing this now?  I obviously want to TDD my JS, but I also want the backend CI server to validate future changes. HALP.

**Comment by fvanwijk** [comment]
Wallaby has strong IDE integrations but not command line (CI) support. See #72
In the meanwhile I suggest you to use [SkippyJS](https://github.com/AlbertBrand/skippyjs).

**Comment by CalvinAllen** [comment]
@fvanwijk That means maintaining two configuration files - one for Wallaby and one for Skippy, correct?

**Comment by fvanwijk** [comment]
Any test runner will have its own config. If you want to run in debug mode, which is also not (yet) supported by Wallaby, you have to use Karma.
Note that you could use Karma for CI as well, but it has no parallel test runner support, which Skippy has (it is as fast as Wallaby for a single run).

I created a node module to share file configs between Wallaby and Karma. It saves you some duplicate config code. See [Re-using file lists between Karma/Mocha/Wallaby](http://wallabyjs.com/docs/config/files.html).
I will add support for SkippyJS soon.

**Comment by CalvinAllen** [comment]
That may be exactly what I'm looking for then.

As of now, we have _3_ Jasmine tests, so parallel test support isn't necessary for us - yet, so I think I will take a look at Karma for now with the future possibility of switching to Skippy.

Thanks for your help, much appreciated!

**Comment by ArtemGovorov** [comment]
@CalvinAllen As Frank mentioned, the [testRunnerConfig](https://github.com/fvanwijk/testRunnerConfig) module is a good way to re-use your file/test lists. It allows you to have a single file with all of your files and runner specific config file importing it.
