### ISSUE TITLE
File must be included in project for wallaby too see it to import it

### ISSUE THREAD

**Issue by ShawnCholeva** [wallabyjs/public#381]
Hey,  we have ran into this issue where we noticed that an import statement isn't finding a file that is not included in our visual studio project.  We had to remove the file because of permissions with our build server that led us to discover this issue.  As background we are using Aurelia, which is es 2015.

This is the import in our js.

![image](https://cloud.githubusercontent.com/assets/13332685/11942278/155ff452-a7fb-11e5-9758-9e008b2e960c.png)

This is the error we are receiving once we exclude the file from our project.  This error fires when we run Start on wallaby.js.

![image](https://cloud.githubusercontent.com/assets/13332685/11942267/0a5527f8-a7fb-11e5-8f88-9835d6187ca4.png)

Any advice or are there any fixes for this problem of wallaby discovering a file that is not included in the project?

**Comment by ArtemGovorov** [comment]
Hey, 
if the file is not included in your VS project, you may just list it explicitly in the `files` list in your wallaby config:

``` JavaScript
    files: [
      ...
      {pattern: 'src/config/config.build.js', load: false}
    ],
```
With broader patterns wallaby.js is only using projects included files, but when a file path is specified, we also look for it on the disk even if it's not included in the VS project.

**Comment by ArtemGovorov** [comment]
Please let me know if it addresses the issue.
