### ISSUE TITLE
Wallaby stops working, because "license is being used elsewhere on the network" 

### ISSUE THREAD

**Issue by kaipahl** [wallabyjs/public#382]
I'm working in my office and at home. For coding at home, I'm using my laptop. For coding in the office, I'm using my desktop computer. In the office my laptop is running in the same local network as my desktop computer (for mails etc…), but IntelliJ 15/Laptop is not used in the office.

This morning I opened IntelliJ on my desktop computer and when starting Wallaby, I received the alert that Wallaby.js is stopped because the license is being used elsewhere and the IP adress is referencing to my laptop. There is nor IntelliJ nor Wallaby running on my laptop (and as I'm using a personal license from intellJ, IntelliJ would also complain about using the same license on two computers in the same LAN).

This happens with IntelliJ 15.0.1 and 15.0.3EAP. Desktop computer and laptop are Macs (OS X 10.11). Yesterday I upgraded my Jetbrains license to the toolbox subscription. Wallaby.js is at v1.0.154

**Comment by fvanwijk** [comment]
See #204 
I usually restart Wallaby and/or IntelliJ.

**Comment by kaipahl** [comment]
- There is no Restart-Option for Wallaby, as Wallaby stops with exit code 0 after being started
- I my case IntellJ was not running today on the laptop when changing from home to office
- I tried to restart IntelliJ on the desktop computer and tried also two different IntelliJ versions (15.0.1 and 15.0.3EAP)
- IntelliJ on the Laptop is not running. 
- To be sure that there is no hidden wallaby process running, I started IntelliJ on the Laptop, started Wallaby (it worked), stopped Wallaby and closed IntelliJ. Didn't change anything for the desktop computer. When I started IntelliJ and Wallaby on the desktop computer, I still got the License-Alert.

I got Wallaby since… hmm… 4 months or so and got since then, the same use scenario (home/laptop, office/desktop), but this is the first time the issue comes up.

**Comment by ArtemGovorov** [comment]
@kaipahl From the symptoms that you're describing, it looks like wallaby process is still running on your laptop. Could you please try rebooting your laptop (and desktop just in case) to see if the issue persists?

**Comment by ArtemGovorov** [comment]
> To be sure that there is no hidden wallaby process running, I started IntelliJ on the Laptop, started Wallaby (it worked), stopped Wallaby and closed IntelliJ

It may still be there in case if IntelliJ plugin for some reason didn't stop wallaby core (for example if IntelliJ itself crashed and the plugin didn't have a chance to kill wallaby core process).

**Comment by kaipahl** [comment]
Yep, reboot of the laptop did it. Wallaby works now on the desktop machine. Thanks for the advice.

Do you know which process? It would be easier to kill the process via activity monitor or shell instead of rebooting the whole computer. I did look for processes with the string "intellij" or "wallaby" but didn't find anything in the activity monitor.

**Comment by ArtemGovorov** [comment]
@kaipahl It's `node` process. I didn't suggest killing it in the first place because you may have some other `node` processes doing something else. If you're ok about killing all node processes, then if the issue happens next time - just run `killall node`.
