### ISSUE TITLE
ReferenceError: window is not defined when import a library

### ISSUE THREAD

**Issue by Ridermansb** [wallabyjs/public#383]
We try to use wallaby with Webpack and Babel in a OpenSource project.

https://github.com/takenet/messaginghub-client-js

But, when run.. the follow error is displayed

```bash
ReferenceError: window is not defined
	at test/MessagingHubClientTest.js:1
```

In this file we have:

```javascript
import sinon from 'sinon';
import MessagingHubClient from '../src/MessagingHubClient';
....
```

Here our [webpack.config](https://github.com/takenet/messaginghub-client-js/blob/develop/webpack.config.js) and [wallaby.conf.js](https://github.com/takenet/messaginghub-client-js/blob/develop/wallaby.conf.js)

We use [wallaby-webpack postprocessor](https://github.com/jeffling/wallaby-webpack) as recommended [here](http://wallabyjs.com/docs/integration/webpack.html)

**Comment by Ridermansb** [comment]
After same attempts ... a new error..

```bash
ReferenceError: Can't find variable: require
	at test/MessagingHubClientTest.js:3
```

**Comment by ArtemGovorov** [comment]
Perhaps I misunderstand something, but this is a node.js project, isn't it? Your mocha tests run in node, but for some reason you're trying to configure wallaby to use webpack. How do you expect webpack to provide `net` implementation that you're using?

Here is the working config equivalent to your current `npm run test` command:

``` JavaScript
/*eslint-env node, browser */
var babel = require('babel-core');
var fs = require('fs');
var path = require('path');

var babelConfig = JSON.parse(fs.readFileSync(path.join(__dirname, '.babelrc')));
babelConfig.babel = babel;

module.exports = function (wallaby) {
    return {
        files: [
            'test/helpers/*.js',
            'src/**/*.js'
        ],

        tests: [
            'test/**/*Test.js'
        ],

        env: {type: 'node'},

        debug: true,

        testFramework: 'mocha',

        compilers: {
            '**/*.js': wallaby.compilers.babel(babelConfig)
        }
    };
};
```

Let me know if it works for you. If you'd like webpack for some reason, please explain how are you expecting it to work so I can suggest how to configure wallaby.
