### ISSUE TITLE
Decorator doesn't get propertyDescriptor argument

### ISSUE THREAD

**Issue by Burgov** [wallabyjs/public#385]
I've created a decorator which allows me to mark methods as non-enumerable:

```
function enumerable(value: boolean) {
    return function (target: any, propertyKey: string, descriptor: PropertyDescriptor) {
        descriptor.enumerable = value;
    };
}
```

used as such:

```
    export class Price extends AbstractPrice {
        discounted:DiscountPrice;

        @enumerable(false)
        get final() {
            return this.discounted || this;
        }

        @enumerable(false)
        get discount() {
            return this.discounted ? 1 - this.discounted.price[0] / this.price[0] : 0;
        }
    }
```

While it compiles fine and the karma tests work as expected, the error wallaby gives me is that the `descriptor` argument is undefined.

Not sure if related, but a manual says: "NOTE: The Property Descriptor will be undefined if your script target is less than ES5." However, when I try to change the target in the config, wallaby fails on something completely unrelated (`Postprocessor run failure: Failed to parse app/scripts/objectmanager/producthooks/app.ts.compiled.js, SyntaxError: Unexpected token (2:55)`)

**Comment by Burgov** [comment]
Ok, it does seem related (although I'm surprised all the other tests never failed...)

But my first attempt to set the target to ES5 failed, because I tried to define it as `target: 'ES5'`, rather than `target: 1`. Are these enums documented anywhere?

**Comment by ArtemGovorov** [comment]
@Burgov Thanks for the update. Yes, as [the docs say](http://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings), enums expected in [TS `CompilerOptions`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2374) have to be used. For example target is [`ScriptTarget`](https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2460).
