### ISSUE TITLE
Need help to set up project

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#386]
Hello @ArtemGovorov,

I would like to ask you to help me to setup `wallabyjs` for my project [mdreizin/webpack-glob](https://github.com/mdreizin/webpack-glob).

It uses [rvagg/node-worker-farm](https://github.com/rvagg/node-worker-farm) to compile webpack configs in separate `process`.

For now `wallabyjs` fails with:

```
Runtime error: ./lib/runWorker.js:2
$_$wp(7);
^

ReferenceError: $_$wp is not defined
```

I read #359, but any suggestions didn't help me.

**PS**: `istanbul` + `jasmine` are working fine in this case.

**Comment by ArtemGovorov** [comment]
I cloned your repo, none of your tests run because you have `xdescribe` in the root of your `compilerAdapter.spec.js` test file. If I make it `describe`, I get this error:

``` JavaScript
1 failing tests, 0 passing

test/compilerAdapter.spec.js CompilerAdapter #run() dummy [4 ms]

	TypeError: WebpackConfig.environment.getAll is not a function
		at lib/runAdapter.js:56
		at lib/compilerAdapter.js:61
		at lib/compilerAdapter.js:73
		at test/compilerAdapter.spec.js:19
```

**Comment by mdreizin** [comment]
@ArtemGovorov I'm sorry for that. I have newer version of `webpack-config` locally and I have not published it yet. Give me a couple of minutes and I publish it.

**Comment by mdreizin** [comment]
@ArtemGovorov Could you please update the repo?

**Comment by ArtemGovorov** [comment]
@mdreizin Thanks, I can see the issue now. 

As mentioned in the issue that you have referenced, wallaby doesn't yet support multiprocess coverage. Even though we plan to support it at some point, I recommend to run tests in a single process anyway, to test things that can be simply `require`-ed (to achieve better test performance, have better isolation, etc.). Having said that, I don't know your project specifics and not sure how you can (or even willing to) do it in your case, so an easier way I can suggest is to mock the `worker-farm` to avoid any multiprocess in tests:

``` JavaScript
'use strict';
module.exports = function (wallaby) {
    return {
        ...
        bootstrap: function () {
            require('worker-farm');
            var farmMock = function (opts, workerFile) { return require(workerFile); };
            farmMock.end = function () {};
            require.cache[require.resolve('worker-farm')].exports = farmMock;
        }
    };
};
```

It'll just make `worker-farm` to work in the same process.

**Comment by mdreizin** [comment]
Huge thanks @ArtemGovorov, now it works fine :+1:

`jasmine` has ability to create `mock` via `spyOn`, `createSpy` and `createSpyObj` and 
it is reasonable to use `mock` objects.

I'm using mostly functional approach for now and I'm will refactor it soon.
