### ISSUE TITLE
Feature request; add AVA to supported frameworks

### ISSUE THREAD

**Issue by mdebruijne** [wallabyjs/public#389]
https://github.com/sindresorhus/ava

almost ready? ; https://github.com/sindresorhus/ava/issues/141

**Comment by hoichi** [comment]
Should we upvote this? AVA support would be very welcome, even though, AFAIK, it's not that easy to support due to it spawning multiple Node processes.

**Comment by ArtemGovorov** [comment]
AVA support is on its way. There're no technical issues with supporting it (one way or another) and we have a working prototype.

**Comment by hoichi** [comment]
Well, sweet!

**Comment by kennethlynne** [comment]
+1

**Comment by luisherranz** [comment]
Any news?

**Comment by ArtemGovorov** [comment]
@luisherranz Not yet, will post any updates here.

**Comment by luisherranz** [comment]
@ArtemGovorov thanks man! May I ask what's left? Can we test that working prototype to give you feedback?

**Comment by ArtemGovorov** [comment]
@luisherranz Not yet, because the prototype is slightly broken - since it was built, some AVA API and internals that wallaby depends on had been changed, so at this stage I'm just waiting while AVA core is stable enough to fix whatever is broken and add an official support for it.

**Comment by ArtemGovorov** [comment]
@luisherranz BTW, we have a plan in future to expose wallaby core API, so that anyone can build support for any testing frameworks.

**Comment by luisherranz** [comment]
Ok, so I guess this depends more on AVA internals than on Wallaby. I wonder if @sindresorhus could give us an idea about when the AVA core is going to be stable enough.

**Comment by ArtemGovorov** [comment]
@luisherranz @sindresorhus what we basically need is a more or less stable API [of few events from `Runner`](https://github.com/sindresorhus/ava/issues/141#issuecomment-154366307) or a more advanced reporter, like mocha runner events or Jasmine reporter. I know AVA has reporters, but they don't currently provide enough events. For example we need one before a test starts (and be able to change its metadata) and after it's finished. I was going to do a PR but never had a chance to.

**Comment by luisherranz** [comment]
Cool. Let's see if @sindresorhus can chime in and give us his insights about it. Both tools (AVA and Wallaby) are really cool and would make a dreaming testing suite together.

**Comment by ArtemGovorov** [comment]
Wallaby.js [adds AVA support](http://dm.gl/2016/04/26/wallaby-sublime-electron-ava/#ava-support).
