### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by marcalj** [wallabyjs/public#39]
Can you provide in this repo or somewhere else a public changelog?

Thanks!

**Comment by ArtemGovorov** [comment]
Agreed, will start one right in this repo.

**Comment by ArtemGovorov** [comment]
https://github.com/wallabyjs/public/blob/master/CHANGELOG.md

**Comment by marcalj** [comment]
:+1:  thanks!

**Comment by dsifford** [comment]
@ArtemGovorov I was notified of an update today in Atom, but it's not clear in the current changelog what exactly happened.

The latest update in the changelog was from Atom version 1.0.22, however, my version number in Atom is 1.0.7. Is there any finer-detailed changelog I can follow somewhere?

**Comment by dsifford** [comment]
Update on my last --- it only says version 1.0.7 in the settings view. In the notification the version is listed as 1.0.24

**Comment by ArtemGovorov** [comment]
@dsifford We release quite frequently (up to a few times a day, especially the [core component](https://wallabyjs.com/docs/intro/how-it-works.html#plugin-and-core)), but only update the changelog every couple of months.

The Atom package is [just a loader/updater of wallaby.js Plugin and Core](https://wallabyjs.com/docs/intro/install.html#atom), it gets updated quite infrequently and does it the same way as all other Atom packages that you may have installed.

Wallaby.js Plugin for Atom and wallaby.js Core on the other hand are updated more frequently, the update is performed automatically behind the scenes and the notification is displayed when the update is finished. So your wallaby Atom package version is 1.0.7, Wallaby.js Plugin for Atom version is 1.0.24.

Hope it makes sense and clarifies things.

**Comment by dsifford** [comment]
@ArtemGovorov Gotcha. Thanks for the clarification.

What do you recommend as the best way to stay on top of the major updates? I fear that I'll miss out on something awesome if I don't stay on top of it.

**Comment by ArtemGovorov** [comment]
> What do you recommend as the best way to stay on top of the major updates?

Almost all of the components (plugin, core) are updated automatically when we publish new versions, so you don't have to worry about missing a new version.

**Comment by dsifford** [comment]
The worry would be I'd miss some feature change and, by not knowing about it, not use it. I'm a bit anal-retentive when it comes to knowing about software updates.
