### ISSUE TITLE
two-headed setup

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#390]
Hi,

I have two sets of tests I wish to run; e2e tests and unit tests.  

The **unit** tests should be compiled by Babel and then Browserified via `wallabify`.

The **e2e** tests are written in ES5 and intended to be run using the global (`window`) context; they do not leverage `require()`.  This means all 3p deps must be placed into `<script>` tags or otherwise into the global context.

This is my current (working) setup, which does *not* run e2e tests:

```js
'use strict';

module.exports = function(wallaby) {
  return {
    files: [
      {
        pattern: 'src/**/*.js',
        load: false
      },
      {
        pattern: 'test/unit/**/*.spec.js',
        ignore: true
      },
      {
        pattern: 'test/unit/fixture.js',
        load: false
      }
    ],
    tests: [
      {
        pattern: 'test/unit/**/*.spec.js',
        load: false
      }
    ],
    // this bit compiles everything with babel
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['es2015'],
        sourceMap: true
      })
    },
    // this browserifies
    postprocessor: require('wallabify')({
      entryPatterns: [
        'test/unit/fixture.js',
        'test/unit/**/*.spec.js'
      ]
    }, function(b) {
      return b.transform(require('browserify-ngannotate'));
    }),
    // tell it to use mocha
    testFramework: 'mocha',
    // required if using wallabify
    bootstrap: function bootstrap() {
      window.__moduleBundler.loadTests();
    }
  };
};
```

If I wished to load tests under `test/e2e/**/*.spec.js` and their dependencies (currently this is `angular`, `angular-mocks`, `chai`, and my bundled library), ensuring nothing is compiled by Babel nor Browserified, how would I accomplish this?  Is it possible?

(`test/unit/fixture.js` currently throws some stuff into the global context, which I could avoid if necessary)

**Comment by ArtemGovorov** [comment]
It's a first time I see a setup like this, but I think it may work:
- include your e2e tests dependencies into your `files` list with `load: true` (which is the default).
- include your e2e tests pattern into you `tests` list with `load: true`.
- change your compiler pattern to exclude e2e tests (and other dependencies that you've mentioned like  `angular`, `chai`, etc.). Not sure where your other dependencies are, but the pattern for compilers that just excludes your e2e tests may look like: `'**/!(e2e)/**/*.js`

**Comment by boneskull** [comment]
I tried something like this, but angular was having spasms because it was loaded twice (once via `<script>`, and once via Browserify).  I'll give it another shot and let you know.

**Comment by ArtemGovorov** [comment]
Perhaps then you may try placing angular in your your `files` list and in your `fixture.js` just `require` it (and assign its globals to `window` if required). Or the other way around, configure browserify to expect globally loaded angular.

**Comment by boneskull** [comment]
I'm going to close this, but I'll comment here if/when I follow up on it.
