### ISSUE TITLE
Visual Studio Code not working

### ISSUE THREAD

**Issue by DomiR** [wallabyjs/public#391]
Visual Studio Code shows error: 
`No handler found for the command: "wallaby.selectConfigFile". Ensure there is an activation event defined, if you are an extension.`

Visual Studio Code Version 0.10.6

**Comment by ArtemGovorov** [comment]
@DomiR Does VS Code restart help?

**Comment by ArtemGovorov** [comment]
Also, please update your wallaby.js extension to 1.0.6 (if you haven't already).

**Comment by DomiR** [comment]
I just installed the extension. At some point three messages popped up, saying that wallaby-core was installed, the initialization process just took a while.

Thanks

**Comment by ArtemGovorov** [comment]
@DomiR  Cool, thanks for the update. If it happens again, try updating to 1.0.6 (which I also just published a few seconds ago).
