### ISSUE TITLE
VSCode - Starts, and just hangs...index.js vs server.js

### ISSUE THREAD

**Issue by shanselman** [wallabyjs/public#395]
I have a fresh install of VSCode, a fresh Wallaby installed as an extension, I cloned the simple calculator example and started Wallaby, and it just hangs with the ... in the status bar. Has something changed? I'm not sure where to start to debug.

**Comment by shanselman** [comment]
Well, here's the issue. The extension is looking for server.js but the name is now index.js?

![image](https://cloud.githubusercontent.com/assets/2892/12245018/3b04be98-b85b-11e5-98e1-bd8e41dbcb69.png)

**Comment by shanselman** [comment]
Weird. Deleted and reinstalled and it worked. Sorry.

**Comment by ArtemGovorov** [comment]
Thanks for the update. The `server.js` file is in the `wallaby` subfolder. It gets downloaded separately when wallaby.js starts for the first time (`...` indicator and notification should be displayed during the download). I can't yet reproduce the issue, but will keep trying.
