### ISSUE TITLE
getBBox is undefined

### ISSUE THREAD

**Issue by atpyatt** [wallabyjs/public#399]
I am running tests with phantomJs specified as the runner. Everything is working as expected except when I try and test code that uses the SVG function "getBBox()" to calculated the bounding box of an SVG element. Could anyone shed any light on this as I understood that this function should be available in phantomJs so I'm wondering what else is going on?

**Comment by ArtemGovorov** [comment]
@atpyatt Could you please share a bit more context, like some code that fails and what error are you getting?

**Comment by ArtemGovorov** [comment]
@atpyatt I haven't worked with SVG much, but maybe you may try [PhantomJs2](http://wallabyjs.com/docs/integration/phantomjs2.html) to see if it works there?

**Comment by atpyatt** [comment]
Hi,

This is what my code looks like:

```javascript
///textElement is an SVG element
textBox = d3.select(cfg.textElement.node().lastChild);
...
//we attempt to use the getBBox function
if (textBox.node().getBBox().width > width) {...
```
Gives the following error when ran with PhantomJs:

```javascript
TypeError: 'undefined' is not a function (evaluating 'textBox.node().getBBox()')
```

```javascript
console.log(textBox.node().getBBox === undefined) // evaluates to true
console.log(textBox.node()) // { x: { baseVal: { numberOfItems: 1 }, animVal: { numberOfItems: 1 } }...		  
```

I thought to try and use PhantomJs2, however when I tried it, the process hangs when loading test files that cover  code using the getBBox function. The console shows "One of your tests is taking too long to execute, check for possibly recently introduced infinite loops." when using PhantomJs2 and the getBBox function.

**Comment by ArtemGovorov** [comment]
Thanks, I'll try to reproduce it, but from the symptoms it looks like it's not wallaby.js specific issue, but PhantomsJs issue. Do you have other test runners set up where you could verify that there's the same issues (or there's no issue)? Or perhaps you could try running your code in PhantomJs without wallaby to see if it works there?

**Comment by ArtemGovorov** [comment]
So I have created [this very simple repo](https://github.com/wallabyjs/getBBoxTest) with one test and it looks like `getBBox` does work for me on this sample, so may be something specific to your project code. 

<img width="768" alt="screen shot 2016-01-16 at 4 34 08 pm" src="https://cloud.githubusercontent.com/assets/979966/12370941/7a70cde8-bc6f-11e5-9555-ce6cf4795e8a.png">

Could you please try to run the sample to see if it works for you?

**Comment by atpyatt** [comment]
The sample works for me as well, I also tried running my tests in PhantomJs through Karma and they also failed there so it's nothing to do with Wallaby. I think the problem is specifically linked to the D3 library and PhantomJs rather than SVG generally. Thanks very much for your help in narrowing this down.

**Comment by ArtemGovorov** [comment]
Thanks for the update. Please let me know if you find the reason, I'm interested to know why was it happening. In a mean time you may consider muting the problematic test if it's being run by PhantomJs, something like:

``` JavaScript
  // perhaps there's a better way to check if it's phantom environment
  !window.callPhantom && it('the test', function() {
  ...
  })
```
