### ISSUE TITLE
Issue configuring jspm/typescript/angular2 project

### ISSUE THREAD

**Issue by areel** [wallabyjs/public#401]
Hi

Trying to setup Wallabyjs for evaluation.

I have an existing typescript/angular2.beta.2 / jspm,  Atom based project, windows 10 OS.

I have taken your sample angular2-jspm as my starting point.

```
return {
           files: [
              { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
              { pattern: 'node_modules/es6-shim/es6-shim.js', instrument: false },
              { pattern: 'jspm_packages/system.js', instrument: false },
              { pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false },
              { pattern: 'jspm.config.js', instrument: false },
              { pattern: 'app/**/*.ts', load: false },
              { pattern: 'app/**/*.html', load: false },
              { pattern: 'app/**/*.spec.ts', ignore: true }
           ],
.......
```
I have treble checked the location and existence of the files referenced above.

When i start wallably I get the following error displayed in the console:
```
ReferenceError: Can't find variable: System
at jspm.config.js:1
ReferenceError: Can't find variable: System
```

which I am assuming means the jspm_packages/system.js has not been loaded. 
I have added the debug: true to the wallably.config.js file but havent seen any extra information logged.

Regards

Aidan

**Comment by ArtemGovorov** [comment]
Yes, it seems like `jspm_packages/system.js` has not been loaded.

Could you please share your full wallaby.js config file?

> I have added the debug: true to the wallably.config.js file but havent seen any extra information logged.

After you add `debug: true` to your config, [there's should be a lot of additional info in Atom Dev Tools](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting), perhaps you've been checking in the wrong place? 

In the log, you should be able to find messages starting with `Serving ...`, try to find the one where it's serving `jspm_packages/system.js` and see if there're not errors nearby.

Also, search for the `File cache: ...` log message in the file, open the folder and check if there's `instrumented/jspm_packages/system.js` file there.

**Comment by areel** [comment]
appreciate the quick response.

yes, you were correct, I was looking in the wrong place, I misread (didn't completely read) the doc and assumed the extra logging would appear in the wallaby console.

Looking in the correct place showed me that Wallably was attempting to load but not finding system-polyfills.js

so adding 

```
{ pattern: 'jspm_packages/system-polyfills.js', instrument: false },
```
before
```
{ pattern: 'jspm_packages/system.js', instrument: false },
```
in the files property array resolved the issue. So I will close this issue.

While investigating this I have noticed some other issues which I will open separately..
