### ISSUE TITLE
missing import statement prevents wallaby from completing startup

### ISSUE THREAD

**Issue by areel** [wallabyjs/public#403]
atom 1.4.0, wallaby 1.0.158, jspm,angular2,typescript 

Have one test file
```
import {AppComponent} from './app';

describe('greeting', () => {

    it('should greet', () => {
        expect('Hello, John').toBe('Hello, John');
    });
});
```

Everything works as expected, wallaby starts up, test is executed, IDE displays wallaby visuals.
if I comment out the import statement:
```
// import {AppComponent} from './app';

describe('greeting', () => {

    it('should greet', () => {
        expect('Hello, John').toBe('Hello, John');
    });
});
```

wallaby will not finish startup, the wallaby icon continues to be the spinning waiting wheel, wallably console does not display any feedback text.
In the logs I see the following entry
```
Wallaby Console: console.error: Potentially unhandled rejection [4] Error: http://localhost:58616/app/tests/first.spec.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
```

Reinstating the import corrects issue.

Expectation would be for wallaby to successfully start and display an error message in the wallaby console.

**Comment by ArtemGovorov** [comment]
Hmm, it looks like it has something to do with system.js, precisely looks like a side effect of adding
``` JavaScript
      System.config({
        meta: {
          'app/*': {
            scriptLoad: true,
            format: 'register'
          }
        }
      });
```
to the `bootstrap` function in your config. If you remove it, the issue should go away. Without it inline error messages will not be displayed though. I'll have a look how to configure system.js to have both.

**Comment by ArtemGovorov** [comment]
Ok, so the issue is that the error doesn't get reported because it's not handled in the promise.
In your config `bootstrap` function where you load tests, add `catch` to your promise and re-throw the error:

``` JavaScript
      ...
      var promises = [];
      for (var i = 0, len = wallaby.tests.length; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }
      Promise.all(promises)
        .then(function () {
          wallaby.start();
        })
        .catch(function (e) { setTimeout(function (){ throw e; }, 0); });
```

Let me know if it works for you this way, I'll then update wallaby SystemJs sample repos.

**Comment by areel** [comment]
I can confirm the proposed change works.

With import present wallaby starts, executes tests, wallaby visuals as expected.
With import missing wallaby starts, displays 0 failing tests, 0 passing, displays error message relating to missing import in wallaby console, wallaby icon is red, wallaby visuals as expected.
