### ISSUE TITLE
Node 4.x yield is unexpected token?

### ISSUE THREAD

**Issue by th-ko** [wallabyjs/public#404]
Hi,
tried to test some node code (typescript) using the mongo driver 2.x and the co library. However it seems that the yield keyword is causing issues: 
[Error] Postprocessor run failure: Failed to parse api/customer-handler.js, SyntaxError: Unexpected token (10:19)

Any ideas?
Thanks in advance
Thomas

**Comment by ArtemGovorov** [comment]
Could you please share your config? Also, what version of the [TypeScript compiler are you using](http://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-version)? Perhaps you don't have one installed in the project so it uses 1.5.3 by default where `yield` is not supported?

**Comment by th-ko** [comment]
Hi,
thanks for the quick answer. This is my config:

module.exports = function (w) {
  return {
    files: [
      'bin/*.ts',
      'api/*.ts',
      'app.ts'
    ],
    tests: [
      'test/*.spec.ts'
    ],
    env: {
      type: 'node'
    },
    compilers: {
      '**/*.ts': w.compilers.typeScript({
        module: 1,
        typescript: require('typescript')
      })
    }
  };
};

**Comment by th-ko** [comment]
My globally install typescript version is 1.7.5

**Comment by ArtemGovorov** [comment]
Thanks, I think I know what the issue is. In TypeScript generators are only available when targeting ECMAScript 6 or higher. so your TypeScript compiler has to target ES6 to correctly support them:

``` JavaScript
compilers: {
      // target: 2 for ES6
      // https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts#L2469
      '**/*.ts': w.compilers.typeScript({module: 1, target: 2})
    }
```

Otherwise, by default it compiles to ES5, and the code:
``` TypeScript
function *main() {
    yield ping();
}
```
gets compiled to syntactically invalid: 

``` JavaScript
function main() {
    yield ping();
}
```
hence the error.

**Comment by th-ko** [comment]
Perfect. Works like a charm! Thanks a lot!
Is there actually a nice way to read those settings directly from the tsconfig.json?

**Comment by ArtemGovorov** [comment]
> Is there actually a nice way to read those settings directly from the tsconfig.json?

Not at the moment, because some of the settings have to be converted from strings to integers, but we will address it as a part of this: https://github.com/wallabyjs/public/issues/408

**Comment by ArtemGovorov** [comment]
@th-ko Actually, more or less clean way to do it for now is like this:
``` JavaScript
module.exports = function (w) {
  var ts = require('typescript');
  return {
    ...
    compilers: {
      '**/*.ts': w.compilers.typeScript(
        ts.parseJsonConfigFileContent(
          require('./tsconfig.json'), 
          ts.sys, 
          ts.getDirectoryPath('./tsconfig.json'))
       .options)
    }
  };
};
```

**Comment by th-ko** [comment]
Awesome, thanks a lot!

**Comment by ArtemGovorov** [comment]
As of the latest core v1.0.175, wallaby.js automatically uses `tsconfig.json`, so the whole `compilers` section may be omitted now (unless you need to override some of the `tsconfig.json` file settings).
