### ISSUE TITLE
Activating wallaby in VS code

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#407]
Now Wallaby.js for VS code starts running in trial mode, asking to activate license to use it continuously. To enter license click 'activate' in message toast, it simply dismissed without asking any dialog to enter it actually. Is there any specific way to enter license code in VS code?

**Comment by ArtemGovorov** [comment]
What version of wallaby.js extension do you have? There's an embedded beta license and if you update wallaby.js extension to latest (1.0.7), then you should see `Your current wallaby.js license free upgrades period will expire soon on 31/01/2016.` But wallaby should still start normally (not in a trial mode). We are planning to release an update soon that will remove the  embedded beta license and allow to activate your valid license (with that `Activate License` button that currently does nothing).

**Comment by kwonoj** [comment]
Yes, it's my fault and found extension is outdated. Curious why it wasn't automatically updated though.. Thanks, I'm closing this issue on my end.

**Comment by ArtemGovorov** [comment]
> Curious why it wasn't automatically updated though.

VS code extensions can't update themselves. You may want to monitory [this issue in the VS Code repo](https://github.com/Microsoft/vscode/issues/268).

**Comment by ArtemGovorov** [comment]
@kwonoj Just letting you know that we have added the license activation mechanism in the latest wallaby extension version. Please upgrade your wallaby.js extension to 1.0.8, start wallaby and once it asks for the license activation, use the `Activate License` button and enter your license.

**Comment by kwonoj** [comment]
Yes I did yesterday. Appreciate for help!
