### ISSUE TITLE
Support Lab and Code frameworks

### ISSUE THREAD

**Issue by jmandzik** [wallabyjs/public#41]
[Lab](https://github.com/hapijs/lab) and [Code](https://github.com/hapijs/code) are two popular frameworks in the HapiJS community.  Seeing support for these two would be great.  They are similar to Mocha/Chai, so hopefully support wont be breaking new ground.

**Comment by KeKs0r** [comment]
Since I was about to create an own issue for this. here goes my +1

**Comment by jmandzik** [comment]
Any idea if there are plans to support Lab?  I'd love to use and recommend Wallaby to my team but our codebase is written with Lab & Code.

**Comment by ArtemGovorov** [comment]
@jmandzik There're plans, but I can't promise when we'll get there.

**Comment by sguimont** [comment]
+1

**Comment by camfraser** [comment]
+1

**Comment by StarpTech** [comment]
+1

**Comment by jccpdev** [comment]
+1

**Comment by timcosta** [comment]
@ArtemGovorov hate to push, but would love to see this soon. Testing `hapi` without `Lab` just isnt the same.

**Comment by jccpdev** [comment]
@timcosta I am new to hapi, can you tell me what the advantage is of using lab over mocha? when working on a hapi project? The only thing I have found is some people saying that the server inject does not work in mocha. But it's working for my team. Anything else? By the way, I'm not trying to not have them implement lab support I'm just trying to figure out what I loose if I use mocha until they do implement lab support.

**Comment by timcosta** [comment]
@jccpdev a large amount of what we deal with is that all of the hapi tests "time out" with mocha, so you have to scroll up wot see the real error. With lab the test failures are tracked as failures.

**Comment by jccpdev** [comment]
@timcosta i'm not sure if I understand what you mean by that, I also don't want to drag this conversation on here since it's not related to wallabyjs. if possible can we continue this via email?

**Comment by camfraser** [comment]
I can't speak for anyone else, but I certainly won't be renewing Wallaby without `lab` support.

**Comment by olalonde59** [comment]
A must!!! +1

**Comment by gilles-bertrand** [comment]
Really need this +10

**Comment by FaeezBorman** [comment]
Just watched the Fun Fun Function coverage of wallaby.js on youtube. 

Super excited to try it on our apps. Only to be stopped because we using hapi and have tons of test already written in Code and Lab

Is this on the roadmap for wallaby?

+1

**Comment by rpfister51** [comment]
+20 (for team of 20)

**Comment by damusix** [comment]
Why was this closed? No plans on supporting?

**Comment by smcenlly** [comment]
This issue wasn't closed by the Wallaby team, it was closed by the original creator of the issue.

We do not have any plans to support [Lab](https://github.com/hapijs/lab) or [Code](https://github.com/hapijs/code) at this point in time as it does not have enough adoption to warrant ongoing support/maintenance effort. We will continue to monitor them and if that changes, we will definitely reconsider.

You may like to consider another more popular testing framework for your `hapi` application. For example, `hapi` is mentioned on the [jest website](https://jestjs.io/docs/testing-frameworks#hapijs).
