### ISSUE TITLE
Testing a Meteor (Mantra) application.

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#410]
Hi, I am trying to run tests on a new architecture for Meteor applications called [Mantra](https://github.com/kadirahq/mantra). The repo for this application can be found here [https://github.com/mantrajs/mantra-sample-blog-app](https://github.com/mantrajs/mantra-sample-blog-app). 

The architecture is using ES2015 and babel-6 and react components. To start with, I tried to only test parts of the app, but wallaby is failing with error: `ReferenceError: Can't find variable: exports
at client/containers/newpost.js:2`

This is my config (what did I miss?):

```javascript
var babel = require('babel-core');

module.exports = function (wallaby) {
  return {
    files: [
      'client/containers/*.js'
    ],

    tests: [
      'client/containers/tests/*.js'
    ],

    // compilers: {
    //   '**/*.js': wallaby.compilers.babel({
    //     babel: babel,
    //     presets: ['es2015', 'react']
    //     // babel options
    //     // like `stage: n` for Babel 5.x or `presets: [...]` for Babel 6
    //   })
    // },

    preprocessors: {
      // NOTE: If you're using Babel 6, you should also add `presets: ['es2015']`.
      // You will also need to
      // npm install babel-core (and require it instead of babel)
      // and
      // npm install babel-preset-es2015
      // See http://babeljs.io/docs/plugins/preset-es2015/
      '**/*.js': file => require('babel-core').transform(file.content, {sourceMap: true, presets: ['es2015'] })
    },

    testFramework: 'mocha'
  };
};
```

**Comment by ArtemGovorov** [comment]
@tomitrescak What your current wallaby config does is simply transforming your ES6 code to ES5 (ES6 modules to CommonJs). Then it tries to load the code in PhantomJs, but browser environment has no idea about those generated `exports` and `require`, hence the error.

I'm not very familiar with Meteor/Mantra testing approaches, but if your tests run in node.js environment as opposed to PhantomJs, then you [need to specify](http://wallabyjs.com/docs/integration/node.html):
```
env: {
  type: 'node'
}
```
in your config.
if your tests can not be executed in node, then you're missing some step to make your code browser friendly. Wallaby supports webpack and browserify that can compile CommonJs, but not sure how it applies to Meteor.

**Comment by tomitrescak** [comment]
Thanks, that helped. Below is the final working configuration in case anyone will be interested:

```javascript
var babel = require('babel-core');

module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'client/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.js', ignore: true },
      'client/**/*.jsx',
      'client/**/*.js',
      'server/**/*.jsx',
      'server/**/*.js'
    ],
    tests: [
      'client/**/tests/*.js',
      'server/**/tests/*.js'
    ],
    preprocessors: {
      '**/*.js': file => require('babel-core').transform(file.content, {sourceMap: true, presets: ['es2015', 'stage-2', 'react'] }),
      '**/*.jsx': file => require('babel-core').transform(file.content, {sourceMap: true, presets: ['es2015', 'stage-2', 'react'] })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha'
  };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update. Compilers (instead of preprocessors) should also work for you (and is the recommended approach):

``` JavaScript
 compilers: {
       '**/*.js*': wallaby.compilers.babel({
         babel: require('babel-core'),
         presets: ['es2015', 'stage-2', 'react']
       })
     },
```

**Comment by tomitrescak** [comment]
Thanks @ArtemGovorov ! Already updated the response ;) Keep up the great work!

**Comment by firrae** [comment]
Sorry for dragging this up again @tomitrescak, but did you get this error and if so how did you solve it?

`client/modules/items/components/tests/ItemList.js items.components.itemList should display the text 3 ms
React is not defined
at client/modules/items/components/tests/ItemList.js:9:8`

**Comment by firrae** [comment]
Nevermind, I found the solution here where you brought it up to @arunoda: https://github.com/kadirahq/mantra/issues/28#issuecomment-185096801

That seems to work, too bad it has to be that way, but oh well.

**Comment by ArtemGovorov** [comment]
@firrae You may use the [`setup` function](http://wallabyjs.com/docs/config/bootstrap.html) to execute any code before your tests, including initialising any globals, such as `React`.

```javascript
module.exports = function (wallaby) {

  ...
  return {
    ...
    setup: function() {
      global.React = require('react');
    };
  };
};
```

**Comment by firrae** [comment]
@ArtemGovorov Perfect! Thanks a bunch!

**Comment by arunoda** [comment]
@firrae could you send a PR to the Mantra sample repo, setting up this.

**Comment by firrae** [comment]
@arunoda done, seems to work nicely in the sample app as it did in mine.
