### ISSUE TITLE
How to cleanup error stack trace?

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/public#411]
```
_core/tests/unit/sample.ts  should be failed [3 ms]

	AssertionError: expected false to be truthy
		at _core/_res/dynamic/test/chai.js:210
		at _core/_res/dynamic/test/chai.js:542
		at _core/_res/dynamic/test/chai.js:3992
```
I tried to use https://github.com/rstacruz/mocha-clean by requiring it in wallaby config top level and in bootstrap function, but it doesn't work.

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby.js config file (with the way you tried to use mocha-clean)?

**Comment by xlaywan** [comment]
```
module.exports = (wallaby) => {
	var fs = require('fs')
	var path = require('path')

	var files = [
		{ pattern: "**/_res/**/*.js", instrument: false },
		{ pattern: "_core/_res/dynamic/test/*", instrument: false },
		'!**/tests/**/*',
		'!**/_res/dynamic/*',
		'config.js',
	]
	function getDirectories(srcpath) {
		return fs.readdirSync(srcpath).filter(function(file) {
			return fs.statSync(path.join(srcpath, file)).isDirectory()
		})
	}
	getDirectories(__dirname)
		.sort((a, b) => a == '_core' ? -1 : b == '_core' ? 1 : 0)
		.forEach(p => {
			files.push(
				p + '/before.ts',
				p + '/*.ts',
				p + '/**/helpers/*.ts',
				p + '/**/before.ts',
				p + '/**/*.ts'
			)
		})
	require('mocha-clean')
	return {
		files: files,
		tests: [
			"**/tests/unit/**/*.ts"
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript({ module: 1, typescript: require('typescript') })
		},
		bootstrap: function() {
			require('mocha-clean')
		},
		// debug: true
	}
}
```

**Comment by ArtemGovorov** [comment]
You're running browser tests, so you need to use the way [described in the mocha-clean readme](https://github.com/rstacruz/mocha-clean#usage-browser):
- get the latest version from the URL that they have specified, save it somewhere locally in your project,
- add the file to your files list,
- in your bootstrap function add:
``` JavaScript
bootstrap: function(w) {
            var mocha = w.testFramework;
            mocha.traceIgnores = ['mocha.js', 'chai.js'];
        },
```

**Comment by xlaywan** [comment]
```
TypeError: 'undefined' is not an object (evaluating 'Mocha.Runner')
at _core/_res/dynamic/test/mocha-clean.js:19
```
It is finds global defined Mocha
```
  Mocha  = this.Mocha;
  Runner = Mocha.Runner;
```
It seems global Mocha variable must be defined. As I understand `w.testFramework` is instance of Mocha?
`window.Mocha = w.testFramework` in bootstrap function didn't help.

**Comment by ArtemGovorov** [comment]
global `Mocha` is actually defined, no need to set it. It seems like an issue in `mocha-clean.js`. Try changing the line 18:
```
Mocha  = this.Mocha;
```
to
```
Mocha  = window.Mocha;
```

**Comment by xlaywan** [comment]
Still erroring. ` throw window.Mocha` and `throw window.mocha` with `window.mocha = w.testFramework` in bootstrap func throws `undefined`

**Comment by ArtemGovorov** [comment]
Oh, just noticed, you've actually not configured it to use `mocha`, it uses `jasmine` by default for browser. To use mocha you need to [add `testFramework: 'mocha'`](http://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks) to your config.

**Comment by ArtemGovorov** [comment]
I have just published a new version of core, with it you may drop using `mocha-clean` altogether, and can just add this to your config:

``` JavaScript
    testFramework: 'mocha',

    bootstrap: function () {
      var fail = Mocha.Runner.prototype.fail;
      Mocha.Runner.prototype.fail = function (test, err) {

        if (err.stack) {
          var newStack = [];
          var stackEntries = err.stack.split('\n');
          for (var i = 0, len = stackEntries.length; i < len; i++) {
            var stackEntry = stackEntries[i];
            if (!~stackEntry.indexOf('chai.js')) {
              newStack.push(stackEntry);
            }
          }
          err.stack = newStack.join('\n');
        }
        return fail.apply(this, [test, err]);
      };
    }
```

The core version where it should work is 1.0.162. Depending on your IDE/editor, you may need to wait few minutes before it automatically updates the core. Please let me know if it resolves the issue.

**Comment by xlaywan** [comment]
Yeah, it totally resolves the issue! Thank you!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update.
