### ISSUE TITLE
Is PhantomJS api available?

### ISSUE THREAD

**Issue by adaskos** [wallabyjs/public#412]
I'm using the 'browser' environment (PhantomJs) and 'mocha' for framework. 
I want to add some functional tests and I'd like to use PhantomJS api for that (e.g. webpage.sendEvent).

How can I access the PhantomJS webpage? Or is it just not possible?

**Comment by ArtemGovorov** [comment]
Wallaby.js only supports running browser tests with PhantomJs, but not using PhantomJs node API, for 'browser' environment we generate a sandbox HTML page including all scripts/tests and run it in PhantomJs webpage. So what you're asking is not possible in wallaby.js, sorry.
