### ISSUE TITLE
WallabyWebpack not working with configuration that works with KarmaWebpack

### ISSUE THREAD

**Issue by ccoffey** [wallabyjs/public#414]
I [forked wallaby-webpack-sample](https://github.com/ccoffey/wallaby-webpack-sample/commit/87f4283ca859aa03b9d591dbc76c4ad7a0a4855e) to create a minimum not working example.

Running ```karma start``` results in ```PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.008 secs / 0.001 secs)```

Running ```wallaby``` results in ```Error: Cannot find module "../images/icon-is-typing.gif"
at src/styles/style.scss:6
at src/styles/style.scss:6
at src/Person.js:1:0
at test/personSpec.js:3:0
ModuleBuildError: Module build failed: Error: gifsicle:<stdin>:#0: read error: unknown block type 85 at file offset -2
gifsicle:<stdin>: file not in GIF format```

Any help would be appreciated.

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I have fixed the issue in core 1.0.163 (it's published, should be updated automatically, and you know how to force the update). Let me know if it works for you.

Even though it should work now, I'd recommend not loading images and styles for tests if you can, unless you need them and verify certain things about them in your tests (though I have no idea what can be unit-tested about an image except its presence or absence). We [recommend](http://wallabyjs.com/docs/integration/webpack.html#webpack-options) only doing things that are really necessary for your tests in order for them to stay fast. Your wallaby.js config doesn't have to replicate your production (or even your CI) config, its goal is to run your tests fast, not to build a production app every time.

**Comment by ccoffey** [comment]
Artem, thanks for fixing the bug. With regards to your comment, I tried not loading images and styles in this example repo and Wallaby failed. Am I missing something?

```
files: [
      //{ pattern: 'src/images/*.gif', load: false },
      //{ pattern: 'src/styles/*.scss', load: false },
      { pattern: 'src/*.js', load: false }
    ],
```

```
Error: Cannot find module "./styles/style.scss"
at src/Person.js:1:0
at src/Person.js:1:0
at test/personSpec.js:3:0
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./styles/style.scss in ./src
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/webpack/lib/Compilation.js:229:38
  at onDoneResolving (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/webpack/lib/NormalModuleFactory.js:85:20
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:726:13
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:52:16
  at done (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:241:17)
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:44:16
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:723:17
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/async/lib/async.js:167:37
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
  at onResolved (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/Resolver.js:127:10
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
  at loggingCallbackWrapper (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
  at Storage.finished (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at ReadFileContext.callback (/Users/cathalcoffey/github/fork/wallaby-webpack-sample/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:76:16)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update.

Re: not loading styles/images, with the way how webpack works and because you `require` them from your code, not including them in `files` will not work. As described in the [docs section that I referenced earlier](http://wallabyjs.com/docs/integration/webpack.html#webpack-options), you'll need to use a `null loader` or `IgnorePlugin`.

**Comment by ccoffey** [comment]
This is a really great idea, you mean something like the following.

```npm install null-loader```

```
var webpackPostprocessor = wallabyWebpack({
  module: {
    loaders: [{
      test: /\.gif$/,
      loader: 'null'
    }, {
      test: /\.scss$/,
      loader: 'null'
    }]
  }
});
```

**Comment by ccoffey** [comment]
Artem you mention [here](http://wallabyjs.com/docs/integration/webpack.html) that we should favor Wallaby's compilers/preprocessors over Webpack loaders. After taking the advise you mentioned above, my webpack loader section now looks as follows.  Would it be faster if Wallaby provided a first class null compiler/preprocessors?

``` javascript
var loaders = [ {
    test: /\.html$/,
    loader: 'null'
  }, {
    test: /\.json$/,
    loader: 'null'
  }, {
    test: /\.png$|\.gif$|\.svg$|\.jpe?g$/,
    loaders: 'null'
  }, {
    test: /\.mp3$/,
    loader: 'null'
  }, {
    test: /\.scss$/,
    loader: 'null'
  }];
```

```Unless you must to, consider not using webpack loaders in wallaby configuration, specifically those that require devtool and source maps, and use wallaby.js compilers or preprocessors instead as described below, because wallaby.js babel compilers/preprocessors are faster.```

**Comment by ArtemGovorov** [comment]
> This is a really great idea, you mean something like the following.
> `npm install null-loader`

Yes, that's what I meant. If that works for you, that may save a lot of time otherwise spent by webpack doing the work unnecessary for tests.

>  Would it be faster if Wallaby provided a first class null compiler/preprocessors?

It probably wouldn't. Babel compilation is faster with wallaby compiler because unlike babel-loader for webpack we generate highly optimised source map and are able to avoid a few FS trips.
