### ISSUE TITLE
errors with wallabyji ext for vscode

### ISSUE THREAD

**Issue by SofianHn** [wallabyjs/public#418]
I am lots of these errors coming from this extension:

Error: No handler found for the command: 'wallaby.showLicense'. Ensure there is an activation event defined, if you are an extension.

**Comment by ArtemGovorov** [comment]
What version of the extension do you have installed? 
Does VS Code restart help?

**Comment by SofianHn** [comment]
not really sure. I am seeing this data in the vscode error telemetry logs. I thought I would drop a line for you guys to investigate.

**Comment by ArtemGovorov** [comment]
@SofianHn Thanks, we have had a button that didn't have a handler, but in the latest version we have added the handler, so should be fine now.
