### ISSUE TITLE
Getting Wallaby working with Angular 2's 5 minute quickstart tutorial

### ISSUE THREAD

**Issue by robinbristoluk** [wallabyjs/public#419]
Hi, I have been struggling all weekend trying to get wallaby working with Angular 2.  I have been going through your documentation/ samples and trying everything I can think of to try and get this sorted.  

To try and keep things as simple as possible I have scrapped my attempts at getting it working with my own project , and am instead now trying to get it working with the 5 minute quick start project, from the angular.io site.  I have this in a [Sample Repository](https://robinbristoluk@bitbucket.org/robinbristoluk/wallabysetupangular2.git ) .

 As this is probably going to be most peoples first exposure to Angular 2 it would be fantastic to have a working sample of this setup with wallaby, in order to get people off on the right foot.

My current issue is I am getting the following when I try starting up wallaby (through webstorm): 

ReferenceError: Can't find variable: System
	at app/app.component.ts:1

ReferenceError: Can't find variable: System
	at app/boot.ts:1

ReferenceError: Can't find variable: System

ReferenceError: Can't find variable: System
	at app/app.component.ts:1

ReferenceError: Can't find variable: System
	at app/boot.ts:1

ReferenceError: Can't find variable: System
at http://localhost:55878/wallaby_sandbox0.html:12

I really hope you can help me getting this sorted, as otherwise I don't know what I can try next, and really want to get this fantastic tool working for my needs. 

Thanks

**Comment by ArtemGovorov** [comment]
The issue with creating a working sample is that there many of ways to setup angular2 app: with systemjs or webpack, with jspm or without it.

In your case the working config looks like:

```JavaScript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
            { pattern: 'node_modules/es6-shim/es6-shim.js', instrument: false },
            { pattern: 'node_modules/systemjs/dist/system-polyfills.js', instrument: false },
            { pattern: 'node_modules/systemjs/dist/system.js', instrument: false },
            { pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false },
            { pattern: 'app/**.ts', load: false },
            { pattern: 'app/specs/*.spec.ts', ignore: true }
        ],
        tests: [
            { pattern: 'app/specs/*.spec.ts', load: false }
        ],
        compilers: {
            'app/**/*.ts': wallaby.compilers.typeScript({
                "module": 4, // <--- 2 for AMD, or 4 for System.js
                "emitDecoratorMetadata": true,
                "experimentalDecorators": true,
                "noImplicitAny": false
            })
        },
        middleware: function (app, express) {
            app.use('/node_modules',
              express.static(
                require('path').join(__dirname, 'node_modules')));
        },
        bootstrap: function (wallaby) {
            wallaby.delayStart();

            System.config({
                defaultJSExtensions: true,
                packages: {
                  app: {

                    }
                  }
                },
                paths: {
                  "npm:*": "node_modules/*"
                },
                map: {
                  "angular2": "npm:angular2",
                  "rxjs": "npm:rxjs"
                }
            });

            var promises = [];
            for (var i = 0, len = wallaby.tests.length; i < len; i++) {
                promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
            }

            Promise.all(promises).then(function () {
                wallaby.start();
            });
        }
    };
};
```

Please note that I have added SystemJS configuration right in wallaby config, normally you should have a separate SystemJS config file in your app, and you'll just need to add it to your wallaby `files` list instead of duplicating its content in wallaby.js config. I didn't find any SystemJS configuration in your project, so had to add some minimal required configuration. It's not actually required to run your current test, but as soon as you start importing things, like:
```
import {AppComponent} from '../app.component';

describe('Unit under test', function () {
    it('Should be', function () {
        console.log(AppComponent);
        expect(true).toBe(false);
    });
});
```
then you'll need to tell SystemJS where to get angular2, rxjs, etc. from. You'll get [there](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md) eventually when starting put a real-world app together.

Also note that you may add `meta.scriptLoad`:
```
            System.config({
                defaultJSExtensions: true,
                packages: {
                  app: {
                    // for inline errors
                    meta: {
                      '*': {
                        scriptLoad: true
                      }
                    }
                  }
                },
```

 to make SystemJs load files via script tags, which will make it possible for wallaby to display inline error messages (inline console.log should work either way):

<img width="462" alt="screen shot 2016-01-26 at 8 32 14 pm" src="https://cloud.githubusercontent.com/assets/979966/12578329/e927ce54-c46b-11e5-8771-56a1ff3ce458.png">

but to do this, your test files need to be recognised as System.js modules for SystemJS, otherwise you'll get some errors like `TypeError: 'undefined' is not an object (evaluating 'e.split')` from SystemJS. But it's quite simple for them to be recognised as System.js modules - you'll need to have `import`s in them, which you'll have in real tests anyway, to import helpers from `angular2/testing`, your SUT modules, etc.

Hope it all makes sense. Please let me know if I can further help or answer any of your questions.

**Comment by robinbristoluk** [comment]
Wow, awesome support.    I have just got everything working thanks to you, and am extremely grateful.  
Were currently in the process of convincing our manager of the need for licenses for our developers, and getting this up and running will be a huge help. 
Many thanks again, 
Rob 

    On Tuesday, 26 January 2016, 10:36, Artem Govorov <notifications@github.com> wrote:
 

 The issue with creating a working sample is that there many of ways to setup angular2 app: with systemjs or webpack, with jspm or without it.In your case the working config looks like:module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
            { pattern: 'node_modules/es6-shim/es6-shim.js', instrument: false },
            { pattern: 'node_modules/systemjs/dist/system-polyfills.js', instrument: false },
            { pattern: 'node_modules/systemjs/dist/system.js', instrument: false },
            { pattern: 'node_modules/reflect-metadata/Reflect.js', instrument: false },
            { pattern: 'app/**.ts', load: false },
            { pattern: 'app/specs/*.spec.ts', ignore: true }
        ],
        tests: [
            { pattern: 'app/specs/*.spec.ts', load: false }
        ],
        compilers: {
            'app/**/*.ts': wallaby.compilers.typeScript({
                "module": 4, // <--- 2 for AMD, or 4 for System.js
                "emitDecoratorMetadata": true,
                "experimentalDecorators": true,
                "noImplicitAny": false
            })
        },
        middleware: function (app, express) {
            app.use('/node_modules',
              express.static(
                require('path').join(__dirname, 'node_modules')));
        },
        bootstrap: function (wallaby) {
            wallaby.delayStart();

            System.config({
                defaultJSExtensions: true,
                packages: {
                  app: {

                    }
                  }
                },
                paths: {
                  "npm:*": "node_modules/*"
                },
                map: {
                  "angular2": "npm:angular2",
                  "rxjs": "npm:rxjs"
                }
            });

            var promises = [];
            for (var i = 0, len = wallaby.tests.length; i < len; i++) {
                promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
            }

            Promise.all(promises).then(function () {
                wallaby.start();
            });
        }
    };
};Please note that I have added SystemJS configuration right in wallaby config, normally you should have a separate SystemJS config file in your app, and you'll just need to add it to your wallaby files list instead of duplicating its content in wallaby.js config. I didn't find any SystemJS configuration in your project, so had to add some minimal required configuration. It's not actually required to run your current test, but as soon as you start importing things, like:import {AppComponent} from '../app.component';

describe('Unit under test', function () {
    it('Should be', function () {
        console.log(AppComponent);
        expect(true).toBe(false);
    });
});
then you'll need to tell SystemJS where to get angular2, rxjs, etc. from. You'll get there eventually when starting put a real-world app together.Also note that you may add meta.scriptLoad:            System.config({
                defaultJSExtensions: true,
                packages: {
                  app: {
                    // for inline errors
                    meta: {
                      '*': {
                        scriptLoad: true
                      }
                    }
                  }
                },
to make SystemJs load files via script tags, which will make it possible for wallaby to display inline error messages (inline console.log should work either way):but to do this, your test files need to be recognised as System.js modules for SystemJS, otherwise you'll get some errors like TypeError: 'undefined' is not an object (evaluating 'e.split') from SystemJS. But it's quite simple for them to be recognised as System.js modules - you'll need to have imports in them, which you'll have in real tests anyway, to import helpers from angular2/testing, your SUT modules, etc.Hope it all makes sense. Please let me know if I can further help or answer any of your questions.—

**Comment by ArtemGovorov** [comment]
@robinbristoluk Awesome, thanks for the update

Please note that you may improve error reporting a bit for some cases, if make this change to your config: https://github.com/duncanhunter/angular2-jspm/pull/2/files
