### ISSUE TITLE
Global variables with env.type: node

### ISSUE THREAD

**Issue by xlaywan** [wallabyjs/public#420]
When I use in my files `global.name = ... ` and in wallby config `env.type: node` I get errors like `App is not defined` in my tests.
If I remove the line `type: node` it works fine.

My config
```
module.exports = (wallaby) => {
	var fs = require('fs')
	var path = require('path')

	var files = [
		{ pattern: "**/_res/**/*.js", instrument: false },
		{ pattern: "_core/_res/dynamic/test/*", instrument: false },
		'!**/tests/**/*',
		'!**/_res/dynamic/*',
		'config.js',
	]
	function getDirectories(srcpath) {
		return fs.readdirSync(srcpath).filter(function(file) {
			return fs.statSync(path.join(srcpath, file)).isDirectory()
		})
	}
	getDirectories(__dirname)
		.sort((a, b) => a == '_core' ? -1 : b == '_core' ? 1 : 0)
		.forEach(p => {
			files.push(
				p + '/before.ts',
				p + '/*.ts',
				p + '/**/helpers/*.ts',
				p + '/**/before.ts',
				p + '/**/*.ts'
			)
		})
	return {
		files: files,
		tests: [
			"**/tests/unit/**/*.ts"
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript({ typescript: require('typescript') })
		},
		testFramework: 'mocha',
		env: {
			type: 'node'
		}
		// debug: true
	}
}
```

I also tried to make all top-level vars global by:
```
		preprocessors: {
			'**/*.ts': (file) => {
				var regexpSource = '^(function|var) ([\\w$]+)'
				var globalRegexp = new RegExp(regexpSource, 'gm')
				var regexp = new RegExp(regexpSource)

				var data = file.content.toString()
				var m = data.match(globalRegexp)
				if (!m)
					return data
				var globals = m
					.map(x => x.match(regexp)[2])
					.map(name => `global.${name} = ${name};`)
					.join('\n')
				return data + globals
			}
		},
```

**Comment by ArtemGovorov** [comment]
@xlaywan Sorry I don't think I fully understand the question. So you get `App is not defined` in your test when trying to access `App`, where is `global.App` assigned? In node.js you have to `require` files in order for them to be loaded and executed. Do you `require` files where your globals are assigned before your tests? Depending on where you're assigning your globals, you may `require` them in a [`bootstrap` function](http://wallabyjs.com/docs/config/bootstrap.html) that gets executed before tests. For example, if your globals were defined in your `config.js`, you could do:

```JavaScript
 module.exports = function () {
   return {
     ...
     bootstrap: function (wallaby) {
        require('./config')
     }
   };
 };
```

**Comment by xlaywan** [comment]
Globals is defined in my source files and I want to access them in test files without `require`. Does wallaby require files defined in `files` property before test them?

**Comment by ArtemGovorov** [comment]
> Does wallaby require files defined in files property before test them?

No, in node.js environment (`env.type: node`) wallaby doesn't `require` anything. Neither does it for webpack/browserify integration. It generally doesn't make sense in node to execute potentially time-consuming code before each test file automatically without anything `require`-ing it. You may however do as I suggested and `require` files that you need in the `bootstrap` function.
