### ISSUE TITLE
Problem loading mock js class from wallaby

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#422]
I have a Jasmine test that attempts to import a fake helper class - eg: 

import {FakeHttpClient} from 'test/unit/helpers/fake-http-client';

My javacript source files are in 'app/src'.

My tests are in 'app/test/unit/'

I have placed a mock class in 'app/test/unit/helpers'

Tests run and pass OK from Karma. 

When starting wallaby, I get this error: 
>
wallaby.js started
core v1.0.165
console.error: Potentially unhandled rejection [4] Error: XHR error loading http://localhost:44251/app/test/unit/helpers/unit/helpers/fake-http-client.js
	Error loading http://localhost:44251/app/test/unit/helpers/unit/helpers/fake-http-client.js as "test/unit/helpers/fake-http-client" from http://localhost:44251/app/test/unit/services/sal-service.spec.js
    at http://localhost:44251/app/jspm_packages/system.js?1453819612263&wallabyFileId=5:4
    at tryCatchReject (http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:1257)
    at runContinuation1 (http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:1216)
    at http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:1037
    at http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:895
    at http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:171
    at http://localhost:44251/app/jspm_packages/system-polyfills.src.js?1453819612270&wallabyFileId=7:136

Presumably I have forgotten to include some mapping in my wallaby.js file - I've tried adding the "test" directory in a few places, not nothing I have tried fixes this. 

Or maybe I need to move the mock class away from the spec files. 

My wallaby file is like: 
    var babel = require('babel');

    module.exports = function (wallaby) {

    return {
    files: [
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
      {pattern: 'app/jspm_packages/system.js', instrument: false},
      {pattern: 'app/jspm_packages/system-*.js', instrument: false},
      {
        pattern: 'node_modules/karma-jasmine-matchers/node_modules/jasmine-expect/dist/jasmine-matchers.js',
        instrument: false
      },
      {
        pattern: 'node_modules/jasmine-promises/dist/jasmine-promises.js',
        instrument: false
      },
      {pattern: 'app/config.js', instrument: false},
      {pattern: 'app/src/**/*.js', load: false}
    ],

    tests: [
      {
        pattern: 'app/test/unit/**/*.spec.js', load: false
      },
      '!app/test/unit/**/home.spec.js' // waiting on bug fix - see https://github.com/aurelia/task-queue/issues/10
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babel: babel,
        optional: [
          'es7.decorators',
          'es7.classProperties'
        ]
      })
    },

    middleware: (app, express) => {
      app.use('/jspm_packages', express.static(require('path').join(__dirname, 'app/jspm_packages')));
    },

    bootstrap: function (wallaby) {
      wallaby.delayStart();

      System.config({
        paths: {
          'src/*': 'app/src/*.js'
        }
      });

      var promises = [];
      for (var i = 0, len = wallaby.tests.length; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }

      Promise.all(promises).then(function () {
        wallaby.start();
      });
    },

    debug: false
    };
    };

**Comment by ArtemGovorov** [comment]
Hi, 
First, I have updated JSPM sample config to include a better error reporting for those `Potentially unhandled rejection ...`. Please modify your bootstrap function [as in the sample](http://wallabyjs.com/docs/integration/jspm.html), the only change is to replace this:

``` JavaScript
Promise.all(promises).then(function () {
    wallaby.start();
  });
```
with this:
``` JavaScript
Promise.all(promises).then(function () {
        wallaby.start();
      }).catch(function (e) { setTimeout(function (){ throw e; }, 0); });
```

and you should get a cleaner error reporting in the Failing Tests view.

Regarding the error itself, the helper file you are loading is missing in your `files` list. Try adding 
``` JavaScript
{pattern: 'app/test/unit/helpers/**/*.js', load: false}
```
to your `files` list. You may also need to extend your SystemJS config in the `bootstrap` function to point it to the location of your tests (if you are not doing it anywhere else yet).
``` JavaScript
  System.config({
    paths: {
      'src/*': 'app/src/*.js',
      'test/*': 'app/test/*.js'
    }
  });
```

The location where it currently tries to load the file is strange `http://localhost:44251/app/test/unit/helpers/unit/helpers/fake-http-client.js`, double `unit/helpers` in particular, maybe some issues with paths/map for SystemJS. If the suggested solution doesn't work for you, please share your `config.js` and working karma config.

**Comment by stevies** [comment]
Thanks. I had not noticed the double path entry:

    .../unit/helpers/unit/helpers/...

I'll see if I can fix that with your suggested changes (I had tried some of these earlier, but maybe not all together, or in the correct order).

**Comment by stevies** [comment]
All working now.  Many thanks for the fast response.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
