### ISSUE TITLE
Wallaby's format for failing test output makes it harder to debug them

### ISSUE THREAD

**Issue by ccoffey** [wallabyjs/public#423]
A typical failing test in my codebase looks as follows when run by Karma.

```
PhantomJS 1.9.8 (Mac OS X 0.0.0) app/components/heading-block rendering a heading-block FAILED
	Expected: {
	  "$$typeof": {
	    "_k": "Symbol(react.element)_o.sv04ehmf2jpuv7vi"
	  },
	  "_owner": null,
	  "_store": {},
	  "key": null,
	  "props": {
	    "children": {
	      "$$typeof": {
	        "_k": "Symbol(react.element)_o.sv04ehmf2jpuv7vi"
	      },
	      "_owner": null,
	      "_store": {},
	      "key": null,
	      "props": {
	        "emoji": "auto",
	        "text": "block.text",
	        "truncate": false
	      },
	      "ref": null,
	      "type": function Text( ){
	        [code]
	      }
	    }
	  },
	  "ref": null,
	  "type": "h1"
	}
	Actual: {
	  "$$typeof": {
	    "_k": "Symbol(react.element)_o.sv04ehmf2jpuv7vi"
	  },
	  "_owner": null,
	  "_store": {},
	  "key": null,
	  "props": {
	    "children": {
	      "$$typeof": {
	        "_k": "Symbol(react.element)_o.sv04ehmf2jpuv7vi"
	      },
	      "_owner": null,
	      "_store": {},
	      "key": null,
	      "props": {
	        "emoji": "auto",
	        "text": "Hello world",
	        "truncate": false
	      },
	      "ref": null,
	      "type": function Text( ){
	        [code]
	      }
	    }
	  },
	  "ref": null,
	  "type": "h1"
	}
```

The same failing test in Wallaby looks as follows.

```
 Expected: '{ \'$$typeof\': { _k: \'Symbol(react.element)_i.fqj4f10txfqx5hfr\' },\n  type: \'h1\',\n  key: null,\n  ref: null,\n  props: \n   { children: \n      { \'$$typeof\': { _k: \'Symbol(react.element)_i.fqj4f10txfqx5hfr\' },\n        type: \n         { [Function: Text]\n           defaultProps: { truncate: false, emoji: \'auto\' },\n           propTypes: \n            { text: [Function],\n              truncate: { [Function] isRequired: [Function] },\n              emoji: { [Function] isRequired: [Function] } } },\n        key: null,\n        ref: null,\n        props: { text: \'block.text\', truncate: false, emoji: \'auto\' },\n        _owner: null,\n        _store: {} } },\n  _owner: null,\n  _store: {} }' Actual: '{ \'$$typeof\': { _k: \'Symbol(react.element)_i.fqj4f10txfqx5hfr\' },\n  type: \'h1\',\n  key: null,\n  ref: null,\n  props: \n   { children: \n      { \'$$typeof\': { _k: \'Symbol(react.element)_i.fqj4f10txfqx5hfr\' },\n        type: \n         { [Function: Text]\n           defaultProps: { truncate: false, emoji: \'auto\' },\n           propTypes: \n            { text: [Function],\n              truncate: { [Function] isRequired: [Function] },\n              emoji: { [Function] isRequired: [Function] } } },\n        key: null,\n        ref: null,\n        props: { text: \'Hello world\', truncate: false, emoji: \'auto\' },\n        _owner: null,\n        _store: {} } },\n  _owner: null,\n  _store: {} }'
```

The Karma output is much easier to debug because I can paste it into a diff tool such as BeyondCompare.

<img width="1236" alt="screen shot 2016-01-26 at 6 54 36 pm" src="https://cloud.githubusercontent.com/assets/456400/12591569/531df5ce-c460-11e5-9af2-48c790bb01f0.png">

The Wallaby output is harder to debug because its all on one line and whitespace is not printed.

<img width="1251" alt="screen shot 2016-01-26 at 6 57 36 pm" src="https://cloud.githubusercontent.com/assets/456400/12591579/6621fe18-c460-11e5-9c6d-020fd427a7de.png">

### Suggestions for improvement

1. Print Expected and Actual on separate lines
2. Print whitespace instead of '\n', '\t', '\r'

### Discussion

Actually I think this issue highlights a bigger problem. One reason I love Wallaby is that it keeps me in my editor where my code lives. I no longer have to context switch back and forth to a console to run my tests. However, I still have to context switch to a diff tool to debug my failing tests. It would be really amazing if Wallaby provided a view that displayed the diff between Actual and Expected for failing tests.

**Comment by ArtemGovorov** [comment]
Done in the latest core v1.0.166 (should be updated automatically, but you know how to force the update if something). Note that Atom restart is required after the update. Here is how your example looks now (Actual and Expected are still printed below the diff):

<img width="565" alt="screen shot 2016-01-27 at 4 14 32 pm" src="https://cloud.githubusercontent.com/assets/979966/12605499/56ce6968-c511-11e5-9c87-ed9950aa1739.png">
