### ISSUE TITLE
problem with Babel6 and ES2015 preset 

### ISSUE THREAD

**Issue by giraud** [wallabyjs/public#424]
Hi

I'm evaluating the library with babel 6 and found a problem when testing a code that uses a for..of loop.

my wallaby conf is using this:
```
var babelCompiler = wallaby.compilers.babel({
    babel  : require('babel-core'),
    presets: ['es2015', 'react', 'stage-3']
});
```
and 'es2015' preset should include the 'transform-es2015-for-of' transformation.

If I test this code, it doesn't work:
```
for (const user of payload.users) { ... }
```

But this one is working:
```
for (let i = 0; i < payload.users.length; i++) {
    const user = payload.users[i];
```

I don't know why presets are not working.
I already had to add the 'transform-object-assign' plugins so the code using 'Object.assign ' could work. 
If I explicitly add the 'transform-es2015-for-of' plugin to the wallaby.js config it still doesn't work.

What is missing in my config ? Or is wallaby not yet fully working with babel-6 ?

Thanks

**Comment by ArtemGovorov** [comment]
Wallaby.js fully supports Babel 6.

I can't reproduce the issue, the code
```
it('for of', () => {
  for (const user of [1, 2, 3]) {
    console.log(user);
  }
 });
```
works fine for me with this `compilers` section in wallaby config:
```
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
        presets: ['es2015'], 
        babel: require('babel-core')
      })
    }
```

Could you please share your full wallaby config file?

**Comment by ArtemGovorov** [comment]
Also, what error are you getting?

**Comment by giraud** [comment]
Glad to know it should work well with babel-6.

I copied/pasted one of your sample configuration:
```
        var babelCompiler = wallaby.compilers.babel({
            babel  : require('babel-core'),
            presets: ['es2015', 'react', 'stage-3'],
            plugins: [
                'transform-object-assign' // needed or else I can't use Object.assign(...)
            ]
        });

        var webpackPostprocessor = wallabyWebpack({
            resolve: {
                extensions: ['', '.js', '.jsx']
            }
        });

        return {
            files: [
                {
                    pattern   : 'node_modules/react-tools/src/test/phantomjs-shims.js',
                    instrument: false
                },

                {
                    pattern: path.join('helium', bundleName, '/src/**/*.js'),
                    load   : false
                }, {
                    pattern: path.join('helium', bundleName, 'src/**/__tests__/*.js'),
                    ignore : true
                },
            ],

            tests: [
                {
                    pattern: path.join('helium', bundleName, 'src/**/__tests__/*-spec.js'),
                    load   : false
                }
            ],

            compilers: {
                '**/*.js': babelCompiler
            },

            postprocessor: webpackPostprocessor,

            bootstrap: function() {
                window.__moduleBundler.loadTests();
            }
        };
```

I should have said that I'm using idea UE (15) with the plugin.
I get the following error:
```
ReferenceError: Can't find variable: Symbol
```
and it points to the line with for..of

**Comment by ArtemGovorov** [comment]
Thanks.
I think the error is not because of the loop, but because of the missing babel runtime (that's where polyfills are defined, including the one for ES6 `Symbol`).
Try [installing it](https://babeljs.io/docs/usage/polyfill/) with `npm install babel-polyfill` and adding to the `files` list:
```
{
                    pattern   : 'node_modules/babel-polyfill/dist/polyfill.js',
                    instrument: false
                },
```

**Comment by giraud** [comment]
Yes, that did the trick.
Thank you.
I must say that I'm very impressed by your quick answers !

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
