### ISSUE TITLE
Wallaby 1.0.8 fails to finish updating behind proxy

### ISSUE THREAD

**Issue by Barryrowe** [wallabyjs/public#426]
I just upaded to 1.0.8, the VS code extension install seemed to go well, but then it looks like Wallaby might go out and pull some data on its own that isn't delivered with the updated plugin?  I was getting a  timeout error after VS Code restarted. I was unable to start wallaby getting a message saying that the plugin doesn't have an activate function defined.

I dropped off my corporate network and restarted VS Code and got the message that I need to validate my license and it all worked.

I had the VSCode proxy setting set to point to our corporate proxy.  This VS Code issue may help with this issue as well: [VSCODE Issue # 69](https://github.com/Microsoft/vscode/issues/69)

**Comment by ArtemGovorov** [comment]
Thanks for the link!

> then it looks like Wallaby might go out and pull some data on its own that isn't delivered with the updated plugin

Correct, wallaby.js also downloads its core (and need to update it periodically when a new version comes out). I have updated the extension to read proxy settings from `settings.json` and use them to update core, it should hopefully work now (you need to update the extension to v1.0.9).
