### ISSUE TITLE
Cannot load wallaby.js in Sublime: Unexpected token )

### ISSUE THREAD

**Issue by lolomet** [wallabyjs/public#429]
When I try to load the wallaby.js config file I get this response:

```
[Info]: wallaby.js started​​​​​
​​[Error]: ​​
​​[Error]: /Users/lolomet/Documents/calculator-sample/wallaby.js:1​​
​​[Error]: n (exports, require, module, __filename, __dirname) { module.exports = () => {​​
​​[Error]:                                                                         ^​​
​​[Error]: Failed to load configuration file:  Unexpected token )​​
```

Am I missing a package or similar? I've installed from the package manager.

**Comment by lolomet** [comment]
The fix is obvs to change the offending line (line 1) to this:

`module.exports = function() {`

But I don't know if the package should ship with the offending line.

**Comment by ArtemGovorov** [comment]
The config file is using ES6 syntax that is not supported by your version of node.js (if you install node >=4, it should work for you). The fix you've made makes it a valid ES5 code, so it works.
