### ISSUE TITLE
VS Code - can't activate (basically can't try the product)

### ISSUE THREAD

**Issue by alvipeo** [wallabyjs/public#430]
Installed for vs code, added wallaby.js, Shift+Ctrl+=, Start => shows me 'Purchase/Activate license' => Activate, Enter => Info: Extended trial, blah-blah. No changes in the code, no additional UI. So I go to Shift+Ctrl+=, Start => showing the same thing. So going circles and it doesn't start working.

Tried to restart Code, same thing.

So, how do I try it?

(Windows 10)

**Comment by ArtemGovorov** [comment]
> So I go to Shift+Ctrl+=, Start => showing the same thing

Are you sure it's showing the same thing? The message should be changed from `Trial mode... blah` to `Your current wallaby.js license free upgrades period will expire soon on 11/02/2016...` with the same buttons, but, which you may close and keep working with wallaby normally.

If it doesn't work, there may be an issue with your config, check [Wallaby Console Output Channel](http://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

**Comment by ArtemGovorov** [comment]
It basically just shows a reminder that the trial license is going to expire soon every time you restart wallaby. Just hit Esc or ignore it, wallaby should still work for you normally. If it doesn't, please see my previous response.

**Comment by alvipeo** [comment]
The problem is I don't see Wallaby console output. Here's what I have:
![image]
(https://inus.azureedge.net/pub/wallaby%20output.png)

**Comment by ArtemGovorov** [comment]
Could you please have a look what in in the VS code dev tools console (`Toggle Developer Tools` command)?

**Comment by ArtemGovorov** [comment]
I mean the dev tools console output after you restart your editor and then trying to start wallaby.js.

**Comment by alvipeo** [comment]
Did a clean install on laptop. Here's what I see in the console:

>[Info] Started Wallaby.js Core v1.0.166
[Error] Failed to load configuration file:  Error: Cannot find module 'wallaby-webpack'
[Error]   at Module.s.require (C:\Users\...\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.8\wallaby\server.js:18:10626)
[Error]   at require (internal/module.js:16:19)
[Error]   at Object.<anonymous> (c:\Users\...\Documents\Visual Studio 2015\Projects\MyCode\wallaby.js:1:84)
[Info] Wallaby.js stopped

**Comment by ArtemGovorov** [comment]
> Error: Cannot find module 'wallaby-webpack'

It means that you `require` the module in your config file, but didn't install it. 
```
npm install wallaby-webpack --save-dev
```
should help.

**Comment by alvipeo** [comment]
ok, thanks! Reinstalled it, restarted code couple of times, now see the tests running! Cool.

But trial expires 31/01... 3 days?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update.
We have [announced the extended trial](http://dm.gl/2016/01/27/wallaby-vscode-sublime/) availability, you may use [this key](https://gist.github.com/ArtemGovorov/a20a4faa68f584e3ae04) to extend your trial for ~2 weeks.

**Comment by alvipeo** [comment]
Thanks! 2 weeks should be enough.

The thing is I'm not really sure yet even for the VS Code. Have been using VS2015 for years but with all these #ng2 multiple pieces of config/code vs2015 doesn't really work yet.

**Comment by ArtemGovorov** [comment]
Send me an email to wallabyjs@gmail.com if you decide to try wallaby.js in VS 2015, happy to issue an extended trial license for the IDE as well.

**Comment by GuyHarwood** [comment]
I get a similar experience - can't even trial wallaby.

This is what comes up every time i press cmd + shift + '=' keys...

[https://www.dropbox.com/s/mxx20m6ntq9fgof/Screenshot%202016-02-25%2008.24.57.png?dl=0](url)

**Comment by ArtemGovorov** [comment]
@GuyHarwood It's just a warning about trial mode on the screenshot that you have shared. You may close it and keep working with wallaby.

**Comment by GuyHarwood** [comment]
so the real issue was that wallabify hadn't been added via npm.

`npm install wallabify --save-dev`

After adding that, and starting wallaby i could run other wallaby commands and it shows up as expected.

Maybe perform a config sanity check in the background when executing start to help newcomers?

**Comment by ArtemGovorov** [comment]
@GuyHarwood The config is checked and all errors are displayed in the [Wallaby Console output channel](http://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) (run VS Code `Toggle Output` command via its menu or command palette and select `Wallaby Console`).
