### ISSUE TITLE
Jest with Jasmine 2 test runner

### ISSUE THREAD

**Issue by Sanjo** [wallabyjs/public#431]
Reproduce: https://github.com/Sanjo/wallaby-jest-sample/tree/jest-with-jasmine2

Expected: `No failing tests, 1 passing`

Actual: `No failing tests, 0 passing`

**Comment by ArtemGovorov** [comment]
Yes, jasmine 2 for Jest is not yet supported by wallaby. I'll be looking into it shortly, it shouldn't be too hard (I have just been waiting for someone to actually request it before add ing the implementation).

**Comment by ArtemGovorov** [comment]
Added the support for Jasmine 2 in the latest core (v1.0.167).

**Comment by Sanjo** [comment]
@ArtemGovorov Thanks for the fast implementation. __There is still a problem__ with the results of failing tests.

Reproduce: https://github.com/Sanjo/wallaby-jest-sample/tree/jest-with-jasmine2 (latest commit).

Expected after initial run: `1 failing tests, 2 passing`

Actual after initial run: `No failing tests, 2 passing`

When I change the y-failing-test.js, the report is correct. Also when I remove the z-passing-test.js, the initial report is correct.

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue, got the latest, started wallaby (in WebStorm) and I'm getting this after the initial run:

<img width="394" alt="screen shot 2016-01-29 at 1 20 53 pm" src="https://cloud.githubusercontent.com/assets/979966/12666316/3a472188-c68b-11e5-9db9-dc8db3635356.png">

Does it display any indicators in the `y-failing-test.js` file at all after the initial run?
Could you please add `debug: true` to the config and paste the output from the `Wallaby Console`?

**Comment by ArtemGovorov** [comment]
Ah, never mind, reproduced it by reducing the number of initial`workers` in my config.

**Comment by ArtemGovorov** [comment]
Fixed in core v1.0.168.
