### ISSUE TITLE
In Visual Studio Code it does not refresh correctly

### ISSUE THREAD

**Issue by tamasfoldi** [wallabyjs/public#438]
Hi!

With you help I have started to use this tool with VSCode. I have realized that if I edit my typescript it reports false result, and I have to restart with e.g. Ctrl+Shift+R+R then the report will be correct again. 

Here are some pictures to see what I'm talking about:
Start with the correct test:
![screenshot_1](https://cloud.githubusercontent.com/assets/11571461/12703589/3a5abb40-c847-11e5-82e5-1eebde64e5da.png)

Then modify it to be wrong:
![screenshot_2](https://cloud.githubusercontent.com/assets/11571461/12703592/47e63226-c847-11e5-873c-73da13b0e067.png)

Then restart wallaby:
![screenshot_3](https://cloud.githubusercontent.com/assets/11571461/12703595/512690e2-c847-11e5-8742-0fd5bb133b3f.png)

Then correct it again:
![screenshot_4](https://cloud.githubusercontent.com/assets/11571461/12703599/58f0d6c0-c847-11e5-9f04-f3e7114b9fd5.png)

Then restart again:
![screenshot_5](https://cloud.githubusercontent.com/assets/11571461/12703600/611d02ce-c847-11e5-9cff-159de5214bda.png)

Do you experiencing the same or something is wrong in my config file? Please tell me if there is something you need to reproduce this issue.

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue, the exact same sample code works for me:

![vsc](https://cloud.githubusercontent.com/assets/979966/12706198/4637c816-c8cb-11e5-824c-318d7b0b07d9.gif)

Could you please create a sample repository with your sample code, wallaby config, etc., and so I could have a look what's wrong?

**Comment by tamasfoldi** [comment]
Hi! Here it is:
https://github.com/tamasfoldi/wallaby_test_repo

**Comment by ArtemGovorov** [comment]
I cloned your repo as is, and can't reproduce the issue (tried on Windows and Mac OS). Here is what I do:
 
![vsc](https://cloud.githubusercontent.com/assets/979966/12717457/c5e21842-c933-11e5-8214-69d40cee3162.gif)

Am I doing it correctly?
Is there anything interesting in the Wallaby Console output channel when it happens?

**Comment by tamasfoldi** [comment]
Yes. That is the same what I'm doing. Interesting. Could it be because I'm using VSCode task runner to compile ts files?
Nothing special in the log:
```
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:workers Loaded 4 test(s)
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:workers Test executed: should have one h1
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:workers Run 1 test(s), skipped 3 test(s)
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:workers Sandbox [xn2xg] is responsive, closing it
[Info] Finished executing 1 affected test(s)
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Test run finished
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Processed console.log entries
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Processed loading sequences
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Processed executed tests
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Processed code coverage
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:extended-core Getting executed tests
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:extended-core Getting console.log output
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:extended-core Processing code coverage
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:extended-core Processing global test errors
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:extended-core Updating affected files
[Info] Mon, 01 Feb 2016 13:02:00 GMT wallaby:project Test run result processed and sent to IDE
```

Here is what I do and see:
![vscode](https://cloud.githubusercontent.com/assets/11571461/12718112/8e9e7336-c8ec-11e5-8d83-8fac92698dd8.gif)

**Comment by tamasfoldi** [comment]
If I modify my test in the header.spec.ts it is working correctly, but if in the main.spec.ts it is not.

**Comment by ArtemGovorov** [comment]
I'm not sure what's going on and why, but if I change the test to invoke `done` callback instead of returning promise, it starts working:

``` JavaScript
    it("should have one h1", done => {
        tcb.createAsync(MainComponent)
            .then(fixture => {

                fixture.detectChanges();

                let element = fixture.nativeElement;
                expect(element.querySelectorAll("h1").length).toEqual(1);
                done();
            });
    });
```

**Comment by tamasfoldi** [comment]
Perfect! Working for me too. Then this will be the solution. Thanks for the help again! 

Do you think, this issue should be closed, or you want it here as a reminder if you don't have anything to do you can go deeper to the root cause of the issee?

For me it is ok if you close it, because my problem is solved. So it is on you

**Comment by ArtemGovorov** [comment]
Thanks, I'll investigate it a bit to see if I can find out the root cause.

**Comment by ArtemGovorov** [comment]
@tamasfoldi It seems to be the issue with angular2 - see https://github.com/angular/angular/issues/5662.  You main component is using external html template, if I make it to use an inline html `template` instead of the external resource with `templateUrl`, then it starts working.

**Comment by tamasfoldi** [comment]
Thanks a lot for the investigation. Hope they'll fix it :)

**Comment by ArtemGovorov** [comment]
Just updated to angular `2.0.0-beta.2` (your repo is on `2.0.0-beta.0`) and it works.

But angular2 keeps introducing [breaking changes](https://github.com/angular/angular/blob/master/CHANGELOG.md#breaking-changes) and tests are now required to use something else instead of the `BrowserDomAdapter.makeCurrent`. So when you'll be migrating to the latest version, you'll need to change the fragment of your `bootstrap` function from:

``` JavaScript
System.import('angular2/src/platform/browser/browser_adapter').then(function(domAdapter) {
          domAdapter.BrowserDomAdapter.makeCurrent();
          for (var i = 0, len = wallaby.tests.length; i < len; i++) {
            promises.push(System["import"](wallaby.tests[i].replace(/\.js$/, "")));
          }
        })
...
```
to
``` JavaScript
      Promise.all([System.import('angular2/testing'), System.import('angular2/platform/testing/browser')])
        .then(function (results) {
          var testing = results[0];
          var browser = results[1];
          testing.setBaseTestProviders(browser.TEST_BROWSER_PLATFORM_PROVIDERS, browser.TEST_BROWSER_APPLICATION_PROVIDERS);
          
          for (var i = 0, len = wallaby.tests.length; i < len; i++) {
            promises.push(System["import"](wallaby.tests[i].replace(/\.js$/, "")));
          }
        })
...
```

**Comment by tamasfoldi** [comment]
Thanks for the information. After the update it is working for me too.

I'm just curious, after the angular update VSCode reports me that `Property toEqual does not exists on type NgMatchers` do you have the same?

If you have deleted the repo just ignore the question, thanks for all the helps :)

**Comment by ArtemGovorov** [comment]
Yes, I get the same. I think `jasmine.d.ts` needs to be installed (via `tsd` or manually), but I'm not 100% sure as it's not wallaby related.

**Comment by tamasfoldi** [comment]
Yes the installation solved it, but I don't know why it wasn't needed before the update. And no it is not wallaby related. Sorry for this, and thanks again!
