### ISSUE TITLE
Sublime Text and NVM

### ISSUE THREAD

**Issue by Kl0tl** [wallabyjs/public#439]
Hi,

Thanks a lot for the Sublime Text plugin, I had been looking forward to it for a long time !

Unfortunately it doesn’t work without a `node` binary available in the current `$PATH`, which I don’t have, using `nvm` to manage my node versions per project. I would need a way to use

```bash
$NVM_DIR/nvm-exec node
```

 instead of `node` right ? Is there another way to interop with `nvm` and its dynamic configuration through `.nvmrc` ?

Would be useful to configure the binary to use (and its params) through `Wallaby.sublime-settings`.

In the same vein, would it be necessary to set `env.runner` to `"$NVM_DIR/nvm-exec"` and `env.params.runner` to `"node"` in the `wallaby.js` configuration file or can Wallaby reuse the same node as it’s IDE plugin ?

**Comment by ArtemGovorov** [comment]
Hello,

In the latest version of the plugin (v1.0.11, just published so will be available in a hour or so) we have added the `node_path` setting so you may add your node path to the `User/Wallaby.sublime-settings`:

```
{
	"node_path": "/Users/user/.nvm/v0.10.38/bin/node"
}
```

> would it be necessary to set env.runner to "$NVM_DIR/nvm-exec" and env.params.runner to "node" in the wallaby.js configuration file or can Wallaby reuse the same node as it’s IDE plugin 

Wallaby will just reuse the same node by default, but you may override it if you need to.

**Comment by ArtemGovorov** [comment]
Added the note to [the package installation doc section](http://wallabyjs.com/docs/intro/install.html#sublime-text).

**Comment by Kl0tl** [comment]
Wow thanks a lot for your reactivity !
