### ISSUE TITLE
How can I run Wallaby.js in atom with multiple project folders?

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#441]
I've loaded multiple project folders in atom (_File_ > _Add Project Folder..._) but when I start Wallaby.js, I see it only in the first project.

Is it possible to use Wallaby.js in other project folders?

**Comment by ArtemGovorov** [comment]
In all editors/IDEs that we support it's only possible to run one wallaby.js configuration per project/folder. 

You should be able to right click on the wallaby config in the second project file tree and choose `Select as Wallaby.js Config` to run wallaby.js on your second project. Please note that it'll only be running tests for the second project. If you'd like to run both config at the same time you need to open these projects in different windows.

**Comment by TimMikeladze** [comment]
Is there any intention to implement this in the future? I often work across multiple project folders at once and having to manually start wallaby each time I jump from project is a buzz kill.

**Comment by ArtemGovorov** [comment]
Yes, we're planning to implement it in future at some point (though no ETA yet). This will be closely related to this feature https://github.com/wallabyjs/public/issues/89 implementation, so feel free to subscribe to that as well.
