### ISSUE TITLE
Sublime Text 3: Wallaby causes file picker to freeze up

### ISSUE THREAD

**Issue by leonid-shevtsov** [wallabyjs/public#442]
STR:

* install Wallaby.js package in Sublime Text 3 (on Mac)
* open mid-sized project (about 3k files) - the project is not Wallaby-related in any way
* open file picker (Cmd+P) and start typing

Every 3 or 4 typed chars the file picker freezes for several seconds, then proceeds to work normally.

The issue goes away after disabling the Wallaby.js package.

Again, the project itself does not have a Wallaby.js config, it is not a Javascript project at all, and no Wallaby.js runner is active at that time in the system.

**Comment by ArtemGovorov** [comment]
I've tried opening a folder with a few different repositories in it (and each repo folder having quite a few files) more than 23k files in total, but I have no problem using `Cmd + P` file picker.

If you enable the Wallaby package back, is the issue coming back?

**Comment by ArtemGovorov** [comment]
Either way, we have just pushed a new version (1.0.12, should be available in a hour or so), where we have fixed the only place where wallaby could potentially affect anything else while not running, so the issue should be fixed. Please try it (in an hour) and let me know if it didn't fix the case.
