### ISSUE TITLE
Wallaby.js configuration for Require.js project

### ISSUE THREAD

**Issue by daddyschmack** [wallabyjs/public#443]
Hi,
I"m new at this jasmine testing stuff, and also at require.js and the module format of writing javascripts.. All things we are using.  

The error returned by Wallaby  is "can't find variable: define"  Our test run fine on the server in our VM, but I would like to run the test locally for convenience sake.

![image](https://cloud.githubusercontent.com/assets/2753635/12784873/4fe7e94c-ca4f-11e5-8545-9a3524eb5845.png)
If I try the "module.exports" format of the wallaby.json, It return syntax errors:
![image](https://cloud.githubusercontent.com/assets/2753635/12784937/9c3b8bc8-ca4f-11e5-8a8e-b3c0d930b2e7.png)

**Comment by ArtemGovorov** [comment]
If you are using `module.exports` you need to rename your file from `json` to `js`. Please [read this docs section](http://wallabyjs.com/docs/integration/requirejs.html) on how to configure wallaby with require.js.

**Comment by daddyschmack** [comment]
Hi Artem, I actually tried that. I uploaded the wrong gif, sorry.    It didn't seem to make a difference..  It still couldn't find the define variable.. I didn't restart jetbrains, I just hit the reload button after making the changes

**Comment by ArtemGovorov** [comment]
> It didn't seem to make a difference

You mean making it a JS file or configuring like [described in the require.js with wallaby.js tutorial](http://wallabyjs.com/docs/integration/requirejs.html)?

Perhaps you should start with [cloning our sample repo](https://github.com/wallabyjs/wallaby-requirejs-sample/) for require.js, running it and then trying to apply the same configuration pattern to your project.

**Comment by daddyschmack** [comment]
Hey aArtem,
I did see there was a large difference between my simplifies wallaby.js
file and the example.  Our project is very complex in the various file
locations. I will get with someone more familiar than I and work on this
and get back to you.

Thanks

**Comment by ArtemGovorov** [comment]
@daddyschmack No worries, let me know if I can be of any help.

**Comment by daddyschmack** [comment]
Artem,

Hi, we are still running into issues.. Here is my screen, can you lend any
guidance?

Thanks!

[image: Inline image 1]

and here is the path to our equivalent of the test-js file
[image: Inline image 2]

**Comment by ArtemGovorov** [comment]
@daddyschmack Looks like your screenshots haven't been attached. 

Either way, the best way would be if you could create a small GitHub repo with some minimal code demonstrating your configuration issues. This way I would be able to help more efficiently.
