### ISSUE TITLE
Sublime Text - Multiple Cursor Bug

### ISSUE THREAD

**Issue by KyleKing** [wallabyjs/public#444]
Hi, I just started Wallaby and am excited to use it more, but I found that the package blocks the ability to create multiple cursors using cmd+click. Wallaby fires a "click_to_link" event whenever a command a click event occur. The bug occurs only when Wallaby is installed and dissapears when the Wallaby package is removed. I'm using Sublime version 3101 on Mac 10.11.2

**Comment by ArtemGovorov** [comment]
Hi, thanks for the report. I have changed our mouse mapping to Cmd + double click for navigating tests panel links to avoid clashing with the multiple cursors creation command. The new version is published, should be available within an hour or so.

In a meantime, the workaround is to open your `Packages/Wallaby/Default (OSX).sublime-mousemap` file and change `"count": 1,` to `"count": 2,` in there.

**Comment by KyleKing** [comment]
Great! Thank you for the quick fix!

**Comment by floriancargoet** [comment]
I always use Ctrl + double click to add a work to the multiple selection so this workaround is not enough for me. I changed to "button2" in the mousemap file.
