### ISSUE TITLE
Test run failure: o[s.type] is not a function

### ISSUE THREAD

**Issue by karlnp** [wallabyjs/public#448]
That's from the test run window; the wallaby.js output is
`Failed to process message preTest from worker, o[s.type] is not a function`
just after loading tests. It happens 1x for each worker.

My tests run when I open the sandbox, so it doesn't seem to be a config problem. Or maybe it is?? In either case, my config is the same as it was in #402 . My server updated this morning, but I think I was running fine on Friday.

**Comment by ArtemGovorov** [comment]
It seems like a caching issue. Try changing your config file (even a space anywhere will do) and restating wallaby. Let me know if the issue goes away or not.

**Comment by karlnp** [comment]
Yep! Updating the file/cache busting worked and I'm back in business. Thank you. :)
