### ISSUE TITLE
Cannot use require-self with Wallaby.js

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#449]
I opened an issue on `require-self` (https://github.com/yortus/require-self/pull/4) which might in fact be related to how Wallaby.js resolves `require()`.

`require-self` allows the developer to reference her own code by doing `require('foo')` from inside of module `foo`. This is possible thanks to a `./node_modules/foo.js` file which gets automatically generated by an NPM `prepublish` step which runs `require-self`.

The file `./node_modules/foo.js` contains this:

```
module.exports = require('..');
```

and I updated the configuration file like so:

```
    files: [
      ...
      {pattern: 'src/*.js'},
      {pattern: 'node_modules/foo.js'}
    ]
```

I am getting this error message:

> Cannot find module '..'

An example of a project which shows this behavior can be found here:
https://github.com/epsitec-sa/electrum-starter-3/commit/7cc5697bc476a3a551933b6b9b39663de1e3d75f

Did I miss something with the configuration of Wallaby.js?

**Comment by ArtemGovorov** [comment]
Wallaby.js is using its own file cache, so you've correctly added `{pattern: 'node_modules/foo.js'}` to your `files` list, so the file gets copied to the cache. And as you've mentioned in the related issue, you are pointing to the main entry point by way of the "main" definition in `package.json`. So the only missing bit is to add the `package.json` file to the `files` list as well.

```
    files: [
      ...
      {pattern: 'node_modules/electrum-starter-3.js'},
      {pattern: 'package.json', instrument: false}
    ],
```

and it should work for you. Let me know if it doesn't.

**Comment by epsitec** [comment]
Thank you for your explanation. Now everything works fine.
