### ISSUE TITLE
Support SublimeText 3 =)

### ISSUE THREAD

**Issue by douglas** [wallabyjs/public#45]
I have been a long user of SublimeText and it would be awesome to use it with Wallaby - I can help with testing if needed.

Also, its author has been pretty active these days and I am sure he would help if needed.

Congrats, this is amazing =)

**Comment by darend** [comment]
+1

**Comment by elgalu** [comment]
+1
Sorry for the +1 but this is due to Github missing feature: a VoteUp button

**Comment by Hyzual** [comment]
+1

**Comment by rexxars** [comment]
+1

**Comment by eigenmannmartin** [comment]
+1

**Comment by enjoylife** [comment]
+1

**Comment by redeemed2011** [comment]
+1. Trying to push for WallabyJS to my boss and team for careful consideration, but we do not use IntelliJ products or Visual Studio (we're on linux).

**Comment by pedromcunha** [comment]
+1

**Comment by darrennolan** [comment]
+1

**Comment by loopmode** [comment]
+1

**Comment by tehdb** [comment]
+1

**Comment by andreacab** [comment]
+1

**Comment by Kikobeats** [comment]
Totally +1

**Comment by scottdixon** [comment]
+1

**Comment by MattiSG** [comment]
+1

**Comment by IPWright83** [comment]
+1

**Comment by ArtemGovorov** [comment]
[ETA announcement](http://dm.gl/2015/12/11/wallaby-plans/#sublime-text-integration-eta)

**Comment by ArtemGovorov** [comment]
[Teaser #1](https://twitter.com/wallabyjs/status/686781197528088580)

**Comment by ArtemGovorov** [comment]
Big day! http://dm.gl/2016/01/27/wallaby-vscode-sublime/#sublime-text-integration-beta

**Comment by ArtemGovorov** [comment]
Great news, [we've found a way to make inline messages work in Sublime Text 3](https://twitter.com/wallabyjs/status/808975647737401345): 
![sb](https://cloud.githubusercontent.com/assets/979966/21177871/c0dd452a-c238-11e6-92d8-5c1dc9728c3e.gif)
