### ISSUE TITLE
How to use Wallaby.js with require-self and ES2015?

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#453]
NPM module `require-self` allows me to write `import 'foo'` from inside the source code of module `foo`.
However, if my module contains ES2015 code which is transpiled with Babel, then I don't really know
how to set up the `package.json` so that it works both with `npm` and with Wallaby.js.

My first idea define a `prepublish` step to compile `./src` and store the output in `./lib`. With this, I need
to point `npm` to the main entry point in the transpiled code:
```
  "main": "lib/index.js",
```
But with that, Wallaby.js won't pick up my source modifications as I edit module `foo`.

Changing `main` in the configuration to point to `./src` makes Wallaby.js happy:
```
  "main": "src/index.js",
```
But then, I can't publish my module.

Any idea of how I could get both tools happy?

**Comment by ArtemGovorov** [comment]
Try this:

- Configure your `package.json` so you can publish your module.
- Remove `require-self` specific files from wallaby config (the ones you've added recently):
```
files: [
      ...
      {pattern: 'node_modules/electrum-starter-3.js'},
      {pattern: 'package.json', instrument: false}
    ],
```

- Patch `require` function to get your module from compiled `src` folder.
```javascript
    bootstrap: function (wallaby) {
      ...
      var path = require('path');
      var modulePrototype = require('module').Module.prototype;
      if (!modulePrototype._originalRequire) {
        modulePrototype._originalRequire = modulePrototype.require;
        modulePrototype.require = function (filePath) {
          if (filePath === 'electrum-starter-3') {
            return modulePrototype._originalRequire.call(this, path.join(wallaby.projectCacheDir, 'src'));
          }
          return modulePrototype._originalRequire.call(this, filePath);
        };
      }
      ...
    }
```

The idea is that wallaby will not be using `require-self` at all, but when you `require('electrum-starter-3')` from your code, it will just load it from wherever we tell it to.

**Comment by epsitec** [comment]
The idea works great. Thanks a lot @ArtemGovorov!

I've modified the bootstrap code a little bit, so that I don't have to hard-code the module name
for the file path matching:

```javascript
    bootstrap: function (wallaby) {
      ...
      var packagePath = path.join (wallaby.localProjectDir, 'package.json');
      var packageConfig = JSON.parse (fs.readFileSync (packagePath));
      var packageName = packageConfig.name;
      var modulePrototype = require ('module').Module.prototype;
      if (!modulePrototype._originalRequire) {
        modulePrototype._originalRequire = modulePrototype.require;
        modulePrototype.require = function (filePath) {
          if (filePath === packageName) {
            return modulePrototype._originalRequire.call (this, path.join (wallaby.projectCacheDir, 'src'));
          } else {
            return modulePrototype._originalRequire.call (this, filePath);
          }
        };
      }
      ...
    }
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for posting the final version.
BTW, I believe you may just do 
```
var packageConfig = require(path.join(wallaby.localProjectDir, 'package.json'));
```
to get the JSON file object. Node should be able to correctly load `json` files when you `require` them.

**Comment by epsitec** [comment]
Indeed!

I decided to summarize all this in a [blog post](http://code.fitness/post/2016/02/npm-require-self-with-wallaby.html) for future reference. Thank you again for your help.

**Comment by ArtemGovorov** [comment]
Great, thanks for sharing! Have added your blog post link to [the list of wallaby.js recipes](http://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes) in the docs.
