### ISSUE TITLE
Conflict with Colorcoder (and other Color Scheme modifiying plugins)

### ISSUE THREAD

**Issue by Hyzual** [wallabyjs/public#454]
Hi,
I'm using (and very much liking) the [Colorcoder plugin](https://github.com/vprimachenko/Sublime-Colorcoder) for SublimeText.
It also modifies my current Color Scheme to color variables according to their names.
When I install Wallaby AND Colorcoder at the same time, it causes an infinite loop and `plugin_host` takes 100% CPU (thankfully you can still kill it :) )

Just so others encountering this issue know, it's possible to have them both but it's a bit tricky.

- First choose a color scheme
- Install Colorcoder first, have it modify the color scheme.
- Edit colorcoder.sublime-settings and set this option: `"auto_apply_on_scheme_change": false`
- Then install Wallaby and run Wallaby - Start

I don't think it's possible to fix this issue on your side alone (the [same kind of issue exists in Colorcoder](https://github.com/Monnoroch/ColorHighlighter/issues/218), a better color scheme modification API is probably needed in SublimeText core. That said, I think you should maybe provide a configuration option just like Colorcoder to disable auto-modifying the color scheme.
What do you think about it ?

**Comment by ArtemGovorov** [comment]
Hello,
we'll certainly add a similar option, we'll also have a look if we could co-exist better.

**Comment by ArtemGovorov** [comment]
In the latest v1.0.14 (published and should be available in a hour), we have added the support for `auto_apply_on_scheme_change` setting in `Wallaby.sublime-settings`, We have also added a check if Colorcoder scheme fix is in use, and if it is, we are just using its scheme as opposed to creating a new one.
