### ISSUE TITLE
Relative path support?

### ISSUE THREAD

**Issue by JoshSchreuder** [wallabyjs/public#459]
Hi,

I have a folder structure where the tests sit outside the main application code.

I've put up an example repo here:
https://github.com/JoshSchreuder/WallabyTest

Basically:
```js
  - app
    - lib
    - some app code
  - test
     - some specs
```

It seems like Wallaby doesn't support this scenario, as it won't load my relative paths from the config. In debug mode I get:

```js
[Info]: Fri, 12 Feb 2016 01:40:39 GMT wallaby:fs Symlink resolution for: C:\Users\me\Documents\Personal\WallabyTest\App\lib\angular.js​​​​​
​​​​​[Info]: Fri, 12 Feb 2016 01:40:39 GMT wallaby:fs File added: lib/angular-mocks.js​​​​​
​​​​​[Info]: Fri, 12 Feb 2016 01:40:39 GMT wallaby:fs Symlink resolution for: C:\Users\me\Documents\Personal\WallabyTest\App\calc.js​​​​​
​​​​​[Info]: Fri, 12 Feb 2016 01:40:39 GMT wallaby:fs File added: test/calc-spec.js​​​​​
```

But loading `angular-mocks.js` fails, as it doesn't seem to be actually loading `angular.js`
```js
[Error]: Runtime error: TypeError: 'undefined' is not an object (evaluating 'angular.mock = {}')​​
```

The issue here seems to be that Wallaby won't actually load any files with a relative path, eg.
```js
files: [
    // These aren't loaded
    '../App/lib/angular.js',
    '../App/calc.js',

    // This is loaded
    'lib/angular-mocks.js'
]
```

This is in the Sublime Text runner and my example above is just something I hacked up quickly to demonstrate, my actual project is much larger, but follows a similar structure where the test directory is not in the directory structure below the Wallaby config file.

It would be great if this scenario could be supported!

Thanks.

**Comment by ArtemGovorov** [comment]
Thanks for the example. This scenario is not yet supported (wallaby config has to be on the same level or upper with the files it needs to load).

You may subscribe to this issue https://github.com/wallabyjs/public/issues/68 for updates.

**Comment by JoshSchreuder** [comment]
Thanks @ArtemGovorov, didn't see that issue. Hope it gets resolved soon!

**Comment by ArtemGovorov** [comment]
@JoshSchreuder Unfortunately there's no plan to resolve it soon (it's pretty tricky to implement considering how wallaby file cache works), so I'd suggest moving wallaby config upper for now as a workaround.

**Comment by JoshSchreuder** [comment]
@ArtemGovorov oh right, so if I put the wallaby config in a higher directory again it should work? Awesome, will give that a try, thanks!

**Comment by ArtemGovorov** [comment]
Yes, as long as the config paths don't go up, it should be fine.

**Comment by JoshSchreuder** [comment]
Thanks, that worked to get the tests running. Only problem I have now is that I don't get the nice line coverage dots, and jump to error / jump to failing test doesn't work correctly. I assume they are related.

My jump to failing test for example, goes to:
`testdir/testdir/test-spec.js`. 

This just shows as an empty file as it doesn't exist on disk. I do however, get the line coverage dot on the first line.

Any ideas?

**Comment by ArtemGovorov** [comment]
@JoshSchreuder Could you please share your current folder structure and your wallaby config? Can I reproduce the issue in the [repo you have shared earlier](https://github.com/JoshSchreuder/WallabyTest)?

**Comment by JoshSchreuder** [comment]
> @JoshSchreuder Could you please share your current folder structure and your wallaby config? Can I reproduce the issue in the repo you have shared earlier?

No, strangely enough I can't, it seems to work fine with a very simple case. 

I'll try to reproduce it without putting my work code up.

**Comment by ArtemGovorov** [comment]
If you could share your wallaby config (perhaps after replacing sensitive file path parts), I may be able to have a look if there's anything wrong with it.

**Comment by JoshSchreuder** [comment]
Here's my config. Sorry it's pretty long, but we have a pretty large project:

```js
var angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');

module.exports = () => {
  'use strict';

  return {
    files: [
        // App Dependencies
        { "pattern": 'WebProj/Scripts/es5-shim.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/jquery-2.0.3.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/jquery-ui-1.11.4.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/attrchange.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular-route.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular-resource.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular-sanitize.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular-animate.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/angular-aria.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/grid/ng-grid.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/angular-file-upload.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/lib/angular/ui-bootstrap/ui-bootstrap-tpls-0.14.3.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/bootstrap-3.2.0/bootstrap.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/moment.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/underscore.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/big.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/jquery.inputmask/jquery.inputmask-3.0.2.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/select2/ui-select2.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/select2/select2.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/bootstrap-datepicker/js/bootstrap-datepicker.min.js', "instrument": false },
        { "pattern": 'WebProj/Scripts/ui-sortable-0.13.4.min.js', "instrument": false },

        // App Code
        'WebProj/Areas/**/Scripts/**/*app.js',
        'WebProj/Areas/**/Scripts/**/*.js',
        'WebProj/Scripts/MyCompany/**/*.js',
        { "pattern": 'WebProj/**/Templates/**/*.html', "instrument": false },
        'WebProj/Scripts/Report/*.js',

        // Test Dependencies
        { "pattern": 'WebProj/Scripts/lib/angular/angular-mocks.js', "instrument": false },
        { "pattern": 'TestProj/Scripts/jasmine-jquery.js', "instrument": false },

        // Test Fixtures
        { "pattern": 'TestProj/Mocks/*.js', "instrument": false },
        { "pattern": 'TestProj/Areas/**/*.mock.js', "instrument": false },
        { "pattern": 'TestProj/Mocks/**/*.html', "instrument": false, "load": true },
        { "pattern": 'TestProj/Mocks/**/*.json', "instrument": false, "load": false }
    ],

    tests: [
      'TestProj/Areas/**/*-spec.js',
      'TestProj/Scripts/**/*-spec.js'
    ],

    preprocessors: {
        'WebProj/**/Templates/**/*.html': (file) => {
            return angularTemplatePreprocessor.transform(file, {
                stripPrefix: '.+WebProj',
                moduleName: 'templates'
            });
        }
    },

    debug: false
  };
};
```

**Comment by ArtemGovorov** [comment]
The config looks good, can't see anything wrong with it. 

There's one thing I'd check - Sublime integration is case sensitive with Windows paths, so please check that the case in the file path (where you don't see the coverage) on your file system is the same as in your config. So in your specific case make sure the path is `TestProj/Areas/**/*-spec.js` and not `TestProj/Areas/**/*-Spec.js` or `TestProj/areas/**/*-spec.js`, etc.

If it's not the case, please try to isolate the issue and publish it in the sample repo.
