### ISSUE TITLE
Sublime Text Editor locking while tests are running

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#460]
I've not actually been using Wallaby that much yet in Sublime, but I've turned it on today and I'm finding that Sublime locks up during the test running. What I'm seeing:

1. I make a change to some code and hit save
2. I see the status update to show Wallaby is running some tests
3. I try to click on a line (Sublime doesn't respond)
4. I notice that the Wallaby progress "bouncer" has stopped bouncing.
5. Sublime suddenly becomes responsive again, right when the Wallaby status updates to show the # passing/failing tests.

I've included an animated gif to illustrate (although it seems to play quite fast) you can see the IDE is not selecting lines as I'm clicking + Wallaby status is frozen.

![wallaby](https://cloud.githubusercontent.com/assets/1374775/13003068/3092db2e-d16b-11e5-9462-cc08cb86b1c6.gif)

**Comment by ArtemGovorov** [comment]
> I make a change to some code and hit save

Is the same issue showing up if you don't hit save?

**Comment by IPWright83** [comment]
Sorry - yes it does also occur if I don't press save.

**Comment by ArtemGovorov** [comment]
Cool, thanks for the GIF BTW, it is helpful! Seems like we may be doing more work on the UI thread than we really should, we'll be looking into it.

**Comment by IPWright83** [comment]
Thanks Artem. You're incredibly helpful and responsive to issues - so it's only fair that I try and do the same when raising them!

**Comment by ArtemGovorov** [comment]
We've just applied some fixes and published the new 1.0.15 version of the package (should be available fro an update within an hour or so). Please try and let us know how it goes.

**Comment by ArtemGovorov** [comment]
We have made some more fixes in v1.0.16, the issue should be fixed now. Please try and let me now how it goes.

**Comment by JoshSchreuder** [comment]
@ArtemGovorov seems to be much better, I had a little bit of lag typing / deleting code and it's smooth as butter now. Nice work :+1:

**Comment by ArtemGovorov** [comment]
@JoshSchreuder Awesome, thanks for the update!
