### ISSUE TITLE
Default Phantom version in documentation

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#462]
The Configuration documentation says:
> By default, wallaby.js is using PhantomJs to run tests.

To run in PhantomJS 2, you have to specify the runner:
```
env: {
  runner: require('phantomjs2-ext').path
}
```

So I recommend to put in the documentation that wallaby is using PhantomJS **1.9.8** to run test.
* intro/config.html
* config/overview.html

Why don't you put the documentation source files on Github so that people can make PRs?

**Comment by ArtemGovorov** [comment]
Thanks, added the note to the docs. 
Yes, it's a good idea and we are planning to put the documentation source files on Github at some stage.
