### ISSUE TITLE
ES6 support in Wallaby config file

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#463]
How is the wallaby config file compiled before loading?

When I'm using destructuring in the config file, it complains:
> Failed to load configuration file:  Unexpected token [

Using destructuring in my src/spec files is ok, when using babel for compiling with the 'es2015' preset.

It looks like ES6 syntax is possible, so there must be some Babel compiling. Or is it running in a new version of Node that does not support destructuring? If so, is it possible to compile the wallaby config file on load, for example by setting a flag in the IDE plugin run config?

**Comment by ArtemGovorov** [comment]
Babel is not used for the config. For IntelliJ platform, wallaby.js config is loaded by the node version that wallaby plugin ships with (currently it is v4.2.2), so whatever the node version supports by default is supported in the config.

**Comment by fvanwijk** [comment]
Thanks for explaining.

Idea: show versions in the Walllaby Console

> wallaby.js started
> core v1.0.181 - plug-in 1.0.46 - node 4.2.2

**Comment by ArtemGovorov** [comment]
Sure, can add it. In a meantime it's possible to just do `console.log(process.version)` in wallaby config to print the node version.
