### ISSUE TITLE
No test run count at end of execution

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#471]
I've just tried turning `Wallaby.js` back on after making some big changes to our project. I've noticed that I'm not getting the test run count anymore - and I've got lots of white blocks (instead of green or red) in my Specs. My guess is that the process is failing somewhere and silently failing but I'm not sure. Here's some debug output:

[Wallaby.txt](https://github.com/wallabyjs/public/files/140993/Wallaby.txt)

and the failing test output:
```
​​​​​TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3

```

**Comment by ArtemGovorov** [comment]
I suspect the global error is preventing your tests from properly executing (even loading), so you have to fix it first.

The error itself is that PhantomJs doesn't support `Function.prototype.bind`, so you just need to include a polyfill for it. You may do:
```
npm install phantomjs-polyfill --save-dev
```
and then add it to the `files`, list like described [here](http://wallabyjs.com/docs/integration/angular.html#angular-15) or [here](http://wallabyjs.com/docs/integration/react-jsx.html#phantomjs-shim)
