### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by remojansen** [wallabyjs/public#479]
### Issue description or question
```
[Info] Thu, 25 Feb 2016 18:49:39 GMT wallaby:workers 
Failed to map the stack to user code, entry message: 
Error: Cannot find module '/Users/remojansen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.11/projects/7b2316d837346b6c/instrumented/test/utils/stubs.js', 
stack: Error: Cannot find module '/Users/remojansen/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.11/projects/7b2316d837346b6c/instrumented/test/utils/stubs.js'
[Info] at http://localhost:62791/wallabify.js?1456426172695:1
```
I visited the directory listed above and the `stubs.js` file seems to be there, but there are duplicates and `.ts` file. I'm not sure if they should not be there?

![screen shot 2016-02-25 at 21 08 50 2](https://cloud.githubusercontent.com/assets/10656223/13334651/fe93f00a-dc04-11e5-9ff1-72355e3ed8db.png)
### Wallaby.js configuration file

```
var wallabify = require("wallabify");

module.exports = function (wallaby) {
    
    var wallabyPostprocessor = wallabify({
        entryPatterns: [
            "test/**/*.js"
        ]
    });
    
    return {
        files : [
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*.tsx', load: false },
            { pattern: 'typings/browser.d.ts', load: false },
            { pattern: 'node_modules/reflect-metadata/reflect-metadata.d.ts', load: false }
        ],
        tests: [
            { pattern: 'test/**/*.ts', load: false }
        ],
        debug: true,
        testFramework: 'mocha',
        postprocessor: wallabyPostprocessor,
        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.0.11

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It looks like some of the files in your `tests` list pattern are not tests. `tests` list should only contain [files with tests](http://wallabyjs.com/docs/config/files.html) (with `describe`/`it` in them).

Also, wallaby.js is not using typings files, so you may remove
```
```
You also don't need to specify `entryPatterns` if only your tests are entries, so you may remove:
```
entryPatterns: [
            "test/**/*.js"
        ]
```

**Comment by ArtemGovorov** [comment]
It looks like some of the files in your `tests` list pattern are not tests. `tests` list should only contain [files with tests](http://wallabyjs.com/docs/config/files.html) (with `describe`/`it` in them). You need to do something like this:
```
        files : [
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*.tsx', load: false },
            { pattern: 'test/**/*.ts', load: false },
            { pattern: 'test/**/*.test.ts', ignore: true },
        ],
        tests: [
            { pattern: 'test/**/*.test.ts', load: false }
        ],
```

Also, wallaby.js is not using typings files, so you may remove these from your `files` list:
```
{ pattern: 'typings/browser.d.ts', load: false },
{ pattern: 'node_modules/reflect-metadata/reflect-metadata.d.ts', load: false }
```
You also don't need to specify `entryPatterns` if only your tests are entries, so you may remove:
```
entryPatterns: [
            "test/**/*.js"
        ]
```

**Comment by remojansen** [comment]
@ArtemGovorov thanks a lot for explaining the problem :) everything is working fine for me now.
