### ISSUE TITLE
IntelliJ IDEA 14.0.3 - Plugin "Wallaby" was not loaded: required plugin "JavaScript" not installed.

### ISSUE THREAD

**Issue by elgalu** [wallabyjs/public#48]
I get this error after installing Wallaby plugin on IntelliJ IDEA 14.0.3 community edition, Ubuntu 14.04 64bits, java-7-oracle.

>
> 8:24:51 PM Plugin Error
>           Problems found loading plugins:
>
>           Plugin "Wallaby" was not loaded: required plugin "JavaScript" not installed.
>           Disable Wallaby
>           Open plugin manager

I can't find that *JavaScript* plugin dependency.
Tried to install *NodeJS* plugin but that fails too.

**Comment by elgalu** [comment]
Fixed after I switched from IntelliJ IDEA community edition to the commercial edition as explained here http://stackoverflow.com/a/13625724/511069

**Comment by ArtemGovorov** [comment]
If you are only doing JavaScript and not Java - WebStorm would be a better option (it's way cheaper than IntelliJ IDEA Ultimate Edition).
