### ISSUE TITLE
Can't find module when using loader queries in require call

### ISSUE THREAD

**Issue by miguelbermudez** [wallabyjs/public#481]
### Issue description or question

How does Wallaby handle module loader queries in the the require call? For example, 
I am using [worker-loader](https://github.com/webpack/worker-loader) in one of my files and I use it like this: 

```javascript
const SearchWorker = require('worker!../actions/searchWorker.js');
```

This works when  processed by webpack. However, I get  
`Error: Cannot find module 'worker!../actions/searchWorker.js'` when wallaby runs. 

I can either try to make this work but since the web-workers aren't being tested I wouldn't mind if I could _ignore_ this module altogether.

I tried doing this: 
```javascript
new webpack.NormalModuleReplacementPlugin(/worker\!.*Worker\.js/, path.resolve('./', './empty-module.js')) //no-op for webworkers
```
after reading #149 but I get the same error. 

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var DefinePlugin = require('webpack').DefinePlugin;
var babel = require('babel-core');

module.exports = function (wallaby) {

  var babelCompiler = wallaby.compilers.babel({
    babel: babel,
  });

  var webpackPostprocessor = wallabyWebpack({
    externals: {
      "react": "React"
    },
    resolve: {
      modulesDirectories: ['./node_modules', './', './src', '../build'],
      extensions: ['', '.js', '.jsx']
    },
    entryPatterns: [
      'test/test_helper.js',
    ],
    plugins: [new DefinePlugin({
     //left out for brevity 
    })
    ]
  });

  return {
    files: [
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},

      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},

      {pattern: 'src/**/*.js', load: false},

      'test/test_helper.js',

      {pattern: 'test/fixtures/*.js', load: false}
    ],

    tests: [
      'test/*Spec.js'
    ],

    compilers: {
      '**/*.js*': babelCompiler
    },

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      require('./test/test_helper'); 
    },

    env: {
      type: 'node'
    },

    testFramework: 'mocha'
  };
};
```

### Code editor or IDE name and version

PyCharm v5.0.2

### OS name and version

OSX 10.10.5

**Comment by ArtemGovorov** [comment]
I have tried both using a file via worker loader
```javascript
var MyWorker = require('worker!../actions/searchWorker.js');
```
and just ignoring it, like [described in the docs](http://wallabyjs.com/docs/integration/webpack.html#normalmodulereplacementplugin) (similar to what you've been trying):

```javascript
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/worker\!.* Worker\.js/, 'node-noop')
    ]
```

and both worked for me.

I think the issue is that you're using both `webpack` and running tests in `node` environment. The scenario is not supported in wallaby.

Try removing these:
```javascript
bootstrap: function () {
      require('./test/test_helper'); 
    },

    env: {
      type: 'node'
    },
```
from your config. You also need to [add your test patterns to your `entryPatterns` if you have specified entry patterns](http://wallabyjs.com/docs/integration/webpack.html#entry-patterns):

```javascript
entryPatterns: [
      'test/test_helper.js',
      'test/*Spec.js'
    ],
```

**Comment by miguelbermudez** [comment]
Thank you Artem for the quick reply. I tried your suggestions but if I remove the lines you indicated I receive multiple 

 `ReferenceError: Can't find variable: require` errors 

and 

`TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)')
at node_modules/react/dist/react-with-addons.js:3215`


Also I need `test_helper.js` since I'm using immutable and chai (see #310)

```javascript
import chai from 'chai';
import chaiImmutable from 'chai-immutable';

chai.use(chaiImmutable);
```

I have a workaround since my tests with Wallaby have been working swimmingly before adding the web worker support: 

* define a `__WALLABY__` define in wallaby's webpack config
* wrap the problematic _require_ in an `if (!__WALALBY__)` 

All the tests run. Not very clean but for now I'm not blocked. 
Thanks again.

**Comment by ArtemGovorov** [comment]
@miguelbermudez 
> `ReferenceError: Can't find variable: require errors`

I think it's because [tests should have `load: false` set](http://wallabyjs.com/docs/integration/webpack.html). You also need to load them from your `bootstrap` function.

> `TypeError: 'undefined' is not a function (evaluating 'RegExp.prototype.test.bind(/^(data|aria)-[a-z_][a-z\d_.\-]*$/)') at node_modules/react/dist/react-with-addons.js:3215`

You need [PhantomJs polyfill](http://wallabyjs.com/docs/integration/react-jsx.html#phantomjs-shim) for `Function.bind` (or you may use PhantomJs2 that doesn't need the polyfill). So juts do 
```
npm install phantomjs-polyfill --save-dev
```
and include the polyfill in your `files` list.

> Also I need test_helper.js since I'm using immutable and chai 

As I have answered you in the [referenced issue](https://github.com/wallabyjs/public/issues/310#issuecomment-152367737), you just need to include the file to `entryPatterns`.

So, with all of these changes, you config may look like:
```javascript
var wallabyWebpack = require('wallaby-webpack');
var DefinePlugin = require('webpack').DefinePlugin;
var babel = require('babel-core');

module.exports = function (wallaby) {

  var babelCompiler = wallaby.compilers.babel({
    babel: babel,
  });

  var webpackPostprocessor = wallabyWebpack({
    externals: {
      "react": "React"
    },
    resolve: {
      modulesDirectories: ['./node_modules', './', './src', '../build'],
      extensions: ['', '.js', '.jsx']
    },
    entryPatterns: [
      'test/test_helper.js',
      'test/*Spec.js'
    ],
    plugins: [new DefinePlugin({
     //left out for brevity 
    })
    ]
  });

  return {
    files: [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},

      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},

      {pattern: 'src/**/*.js', load: false},

      {pattern: 'test/test_helper.js', load: false},

      {pattern: 'test/fixtures/*.js', load: false}
    ],

    tests: [
      {pattern: 'test/*Spec.js', load: false}
    ],

    compilers: {
      '**/*.js*': babelCompiler
    },

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    },

    testFramework: 'mocha'
  };
};
```
