### ISSUE TITLE
Does not copies empty directories

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#483]
### Issue description or question

Empty dir `src` in `test/fixtures/src` will not be copies resulting in following error:

```
ENOENT: no such file or directory, scandir '/Users/okonet/Library/Caches/IntelliJIdea15/wallaby/projects/78b114204440ef22/instrumented/test/fixtures/basic/src'
```

Adding an empty file to it fixes the issue.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        debug: true,
        files: [
            'src/**/*.js',
            'test/**/*',
            { pattern: 'test/**/*.js', ignore: true }
        ],

        tests: [
            'test/**/*.js'
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },

        env: {
            type: 'node'
        }
    }
}
```

### Code editor or IDE name and version

IntelliJ IDEA v15

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It's by design (only files are copied over to the cache, with a minimum required folder structure created for them).

The easiest way I can suggest is this one liner (it wouldn't be much shorter if we supported it in any other way):

```javascript
module.exports = function (wallaby) {
    require('fs-extra').ensureDirSync(wallaby.projectCacheDir + '/test/fixtures/src');

    return {
        ...
    }
}
```
+
```
npm install fs-extra --save-dev
```
