### ISSUE TITLE
Wallaby in VS 2015 requires files to be "included" in project

### ISSUE THREAD

**Issue by ShadowSoftware** [wallabyjs/public#486]
I am using Wallaby in a VS 2015 + Webstorm Angular2 Webpack Typescript environment which uses a symlinked "shared" code folder that is available across multiple projects. It took me a minute to realize that no matter the files: [] configuration, Wallaby will not include those files in its build output unless the files are included in the actual VS project. Is there a config option for this where Wallaby will traverse the file system for the files without relying on the VS project to provide them? The concern here is that these projects are accessed by some using Webstorm, and others using VS. If a Webstorm user adds a new shared component to the symlinked path, it will require the VS user to locate those new files and include them in the project and check in those project file changes independently of any other changes they are making.

**Comment by ShadowSoftware** [comment]
Excellent, that worked great, thank you =)

Yes, they can (only a couple would be using VS) edit those. Using the "Show All Files" option from the Solution Explorer allows you to get at those without including them. It's still aware of them even though they are not included directly...

**Comment by ArtemGovorov** [comment]
@ShadowSoftware Got it, thanks for the update!
