### ISSUE TITLE
Coffeescript!

### ISSUE THREAD

**Issue by marclar** [wallabyjs/public#49]
:coffee: :+1: 

Thanks!

**Comment by defaude** [comment]
Especially sexy: Support for jasmine specs written in coffeescript. I really like my jasmine with coffee :)

**Comment by ArtemGovorov** [comment]
Done - https://github.com/wallabyjs/public#compilers-setting

**Comment by ArtemGovorov** [comment]
http://dm.gl/2015/04/13/wallaby-expanding/

**Comment by marclar** [comment]
Very nice!
