### ISSUE TITLE
Adobe Brackets support requested.

### ISSUE THREAD

**Issue by abhiesa-tolexo** [wallabyjs/public#490]
Enhancement Request: Adobe Brackets support requested.
### Wallaby.js configuration file

N/A
### Code editor or IDE name and version

Adobe Brackets 1.6+
### OS name and version

Windows
OSX

**Comment by smcenlly** [comment]
On September 1, 2021, Adobe will end support for Brackets and users are being encouraged to use VS Code. We have no intention of adding support for Adobe Brackets.
