### ISSUE TITLE
Add unexpected-express support

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#492]
### Add [unexpected-express](https://github.com/unexpectedjs/unexpected-express) support

In assertion 

``` js
expect(express(), 'to yield exchange', {
   request: {
       method: 'POST',
       ...
   },
   response: {
      body: {
         bodyField: 'unexpectedbodyFieldValue',
      }
   }
 })
```
- assertion diff should have colorized output
- if environment variable `UNEXPECTED_FULL_TRACE=true`
  - clickable stack trace should be available
### Wallaby.js configuration file

``` js
env: {
   params: {
       env: 'UNEXPECTED_FULL_TRACE=true'
   }
}
```
### Code editor or IDE name and version

WebStorm v11
IntelliJ IDEA v15
Visual Studio 2015
Visual Studio 2013
Atom v1.x
Visual Studio Code v0.10.x
Sublime Text v3
### OS name and version

Windows
OSX
Linux

**Comment by smcenlly** [comment]
We have no intention of adding support for unexpected-express. Closing this issue.
