### ISSUE TITLE
Code coverage broken in WebStorm 12 EAP

### ISSUE THREAD

**Issue by carlansley** [wallabyjs/public#493]
### Issue description or question

WallabyJS's code coverage is broken in WebStorm 12 EAP, and has been since the first couple of builds.

Project in WebStorm 11:
<img width="355" alt="screen shot 2016-03-03 at 11 15 06 am" src="https://cloud.githubusercontent.com/assets/698612/13500629/5b266a60-e131-11e5-863c-e82b900c7c14.png">

Same project in WebStorm 12:
<img width="367" alt="screen shot 2016-03-03 at 11 15 16 am" src="https://cloud.githubusercontent.com/assets/698612/13500627/5828619c-e131-11e5-95d6-0a690ce93142.png">

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  //noinspection JSUnusedGlobalSymbols,JSUnresolvedFunction
  return {
    bootstrap: function () {
      require('expectations');
    },

    files: [
      {pattern: 'src/**/*.ts'},
      {pattern: 'src/**/*.spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*.spec.ts'}
    ],

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({module: 1, target: 2})
    },

    env: {
      type: 'node',
      runner: 'node',
      params: {
        runner: '--harmony --harmony_default_parameters --harmony_destructuring'
      }
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v12 EAP

### OS name and version

OSX 10.11.3

**Comment by carlansley** [comment]
I should add that I'm not expecting support for a pre-release version of WebStorm, but wanted to highlight it regardless since it is a pain point.  WebStorm 12 EAP supports the latest versions of the stuff we use (TypeScript, Angular) better than WebStorm 11 does.

**Comment by ArtemGovorov** [comment]
@carlansley It is EAP introduced issue https://github.com/wallabyjs/public/issues/474, here is the issue in [WebStorm issue tracker](https://youtrack.jetbrains.com/issue/IDEA-151485). Try changing your line spacing/font size settings for now, it should help.

**Comment by ArtemGovorov** [comment]
*Update*: I have implemented an internal workaround for the issue in the latest wallaby plugin v1.0.49, so icons should be ok in EAP builds as well now.

**Comment by carlansley** [comment]
Thanks, worked like a charm!
