### ISSUE TITLE
Increase Maximum Console Messages

### ISSUE THREAD

**Issue by johnvnguyen** [wallabyjs/public#494]
Excuse me for any improper postings.  I am working on a project that already uses tons of console.logs to use for debugging, so I cannot delete them out. I easily max out 100 console messages by simply adding 3 in my tests. 

`Number of console messages per test exceeded maximum allowed value (100), current test console messages recording stopped`

Is there anyway to increase this amount, and why is the maximum set at 100?

**Comment by ArtemGovorov** [comment]
I have increased the limit to 10000 per test and have published the core v1.0.193 with change (should be updated automatically). Please let me know if it works for you now.

**Comment by johnvnguyen** [comment]
@ArtemGovorov I tried waiting for an update on my Wallaby plugin and 20 mins has gone by. You said you updated the core v1.0.193. How would I go about updating Wallaby?

**Comment by ArtemGovorov** [comment]
@johnvnguyen What IDE/editor are you using?

**Comment by johnvnguyen** [comment]
@ArtemGovorov Intellij IDEA

**Comment by ArtemGovorov** [comment]
Try restarting your IDE and starting wallaby, it should update the core.

**Comment by johnvnguyen** [comment]
Hey, it works now. I restarted at least 3 times before you told me to, and nothing happened then. Thanks @ArtemGovorov

**Comment by ArtemGovorov** [comment]
Great, thanks for the update!

**Comment by ArtemGovorov** [comment]
In the core v1.0.196, I have put the default limit back, but [made it configurable](http://wallabyjs.com/docs/config/overview.html#maximum-console-messages-logged-per-test).

**Comment by johnvnguyen** [comment]
@ArtemGovorov Even better! Feature is very appreciated.
