### ISSUE TITLE
Wallaby.js cache is corrupted, please restart wallaby.js

### ISSUE THREAD

**Issue by spapaseit** [wallabyjs/public#495]
I have a Visual Studio 2015  project based on the Aurelia Navigation Skeleton for ASP.NET 5.
Wallaby.js is configured and starts-up fine; the tests run an the tests results are correct... Until you make a change, however small, to any of the files.

Then wallaby crashes with the following message:  **​​​​​Test run failure: Wallaby.js cache is corrupted, please restart wallaby.js**

This means that wallaby.js is unusable for me the the moment

### Wallaby.js configuration file

```javascript
/* eslint-disable no-var, no-shadow, dot-notation */
 
var babel = require("babel");

module.exports = function(wallaby) {
    return {
        files: [
            { pattern: "wwwroot/jspm_packages/system.js", instrument: false },
            { pattern: "wwwroot/config.js", instrument: false },
            { pattern: "wwwroot/lib/jquery/dist/jquery.js", instrument: false },
            { pattern: "src/**/*.js", load: false },
            { pattern: "test/stubs/**/*.js", load: false }
        ],

        tests: [
            { pattern: "test/unit/**/*.js", load: false }
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel,
                optional: [
                    "es7.decorators",
                    "es7.classProperties"
                ]
            })
        },

        middleware: (app, express) => {
            app.use("/wwwroot/jspm_packages", express.static(require("path").join(__dirname, "wwwroot", "jspm_packages")));
            app.use("/jspm_packages", express.static(require("path").join(__dirname, "wwwroot", "jspm_packages")));
        },

        bootstrap: function(wallaby) {
            var promises = [];
            var i = 0;
            var len = wallaby.tests.length;
            wallaby.delayStart();

            System.config({
                paths: {
                    '*': "*"
                }
            });
            for (; i < len; i++) {
                promises.push(System["import"](wallaby.tests[i].replace(/\.js$/, "")));
            }

            Promise.all(promises).then(function() {
                wallaby.start();
            }).catch(function (e) { setTimeout(function (){ throw e; }, 0); });
        },

        debug: false
    };
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Try changing your wallaby config file (even a space somewhere will do), and restarting it.

**Comment by spapaseit** [comment]
Hi @ArtemGovorov , I tried that already, but to no avail. I've tried uninstalling and reinstalling Wallaby as well.

Setting debug: true did not provide any extra information.

**Comment by ArtemGovorov** [comment]
Ok, I'll try the skeleton app now. Is it this one - https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs?

**Comment by ArtemGovorov** [comment]
I'm trying the one I have referenced (after doing `npm install` + `jspm install -y`) and it works for me in Visual Studio. Perhaps the issue is your project specific. Could you try if the fresh skeleton app works for you?

**Comment by ArtemGovorov** [comment]
Also, when you start wallaby.js with `debug: true` options, one the very first lines in prints into the Wallaby Console should be something like: 
```
wallaby:project File cache: somefolder
```
Try deleting the `somefolder` manually and restarting wallaby.js.

**Comment by spapaseit** [comment]
That's the correct skeleton indeed, but I cannot start wallaby from that skeleton:

`Error loading http://localhost:56789/test/unit/setup.js as "./setup" from http://localhost:56789/test/unit/app.spec.js`

I had to make a change to my wallaby configuration to get that to run in the first place. Could you start Wallaby with the configuration as is?

**Comment by spapaseit** [comment]
Deleting the cache folder didn't help either

**Comment by ArtemGovorov** [comment]
Looks like I was using an older version (it worked for me without any config chnages), trying the latest now. So you can reproduce the issue in the latest version in that skeleton without your project specific files?

**Comment by spapaseit** [comment]
To make the aurelia skeleton work with Wallaby I changed the following line:

    tests: [
      {pattern: 'test/unit/**/*.js', load: false}
    ],

to

   tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],

After doing that I can start Wallaby, but I have the same problem on the skeleton project

**Comment by ArtemGovorov** [comment]
@spapaseit Do you mean the other way around? It's [already `{pattern: 'test/unit/**/*.spec.js', load: false}
 ` in the skeleton](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-es2016-asp.net5/src/skeleton-navigation-es2016-vs/wallaby.js#L17).

**Comment by spapaseit** [comment]
Yes, sorry. I updated my comment.

**Comment by ArtemGovorov** [comment]
Ok, thanks. I think I can see the problem now. As [stated in the docs](http://wallabyjs.com/docs/config/files.html), wallaby `tests` should only contain actual test files (with `describe`/`it` in them). The `setup.js` should not be in the `tests` list, but in the `files` list:
```javascript
    files: [
      ...
      {pattern: 'test/unit/setup.js', load: false}
    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],
```

**Comment by spapaseit** [comment]
Works like charm, thank you!

I already expected it would have something to do with the new `setup.js` file, but I had totally missed that bit in the docs, sorry about that.

Can I suggest you do another PR on Aurelia to make sure people can keep using Wallaby with the current version?

**Comment by ArtemGovorov** [comment]
Great, thanks for the update. Will do create the pull request now.

**Comment by ArtemGovorov** [comment]
Done - https://github.com/aurelia/skeleton-navigation/pull/321

**Comment by spapaseit** [comment]
Cool, thanks again!

--
Kind regards,
*Sergi Papaseit Valls*
mobile: 06 52 091 662 <callto:+31622425298>
web: www.codenamed.nl <http://www.codenamed.nl>
twitter: @codenamednl <http://twitter.com/codenamednl>


Artem Govorov wrote:
