### ISSUE TITLE
Can Wallaby run without a test framework?

### ISSUE THREAD

**Issue by togakangaroo** [wallabyjs/public#496]
Is it possible to run wallaby without a test framework? I am playing with some libraries in a plain node js file and enjoy the workflow of wallaby and how it will show output inline.

If my file is simply 

```
doSomething(function() {
   console.log(arguments)
})

```

can I get wallaby to run this?

**Comment by ArtemGovorov** [comment]
You can write any sync code without a testing framework in any of your test files:
```javascript
console.log(doSomething());
console.log(doSomethingElse());
```
with a config like this:
```javascript
module.exports = function () {
  return {
    files: [
      'doesNotMatter/**/*.js'
    ],

    tests: [
      'sandbox.js'
    ],

    env: {
      type: 'node'
    }
  };
};
```

For async code, you'll need to let wallaby know that it needs to wait for some code to finish executing. The easiest way to do it is this (you don't need `describe`, just the `it`):

```javascript
it('async', function (done) {

  doSomething(function() {
   console.log(arguments);
   done();
  })

});
```
