### ISSUE TITLE
preferred way to pull environment variables from a file for wallaby?

### ISSUE THREAD

**Issue by Ashtonian** [wallabyjs/public#498]
### Issue description or question
I'm trying to setup wallaby to pull environment variables from a file rather then being specified as strings in the wallaby.js config file.  The motivation is that I'd like the environment variables file to not be contributed to source but I would like the wallaby config file to be in source. 

I attempted very quickly to use node dotenv and run the config function in the test setup function and it didn't work. 

SIDE NOTE: 
I'm not sure what the standard way to do this is, as I'm new to the node ecosystem. I'm using the .env file as per advice from heroku (I think) so if there is another config lib or standard for me to follow, i'd be glad to do so. 

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      '.env',
      // other stuff
      'app.js',
    ],
    tests: [
      'tests/**/**.js', {
        pattern: '../tests/wallaby.js',
        instrument: true,
        load: false,
        ignore: true
      }
    ],
    debug: true,
    testFramework: 'mocha',
    reportConsoleErrorAsError: true,
    env: {
      type: 'node'
    },
    setup: function(wallaby) {
      console.log('Setup');
      console.log('Current worker id: ' + wallaby.workerId);
      console.log('Current session id: ' + wallaby.sessionId);
      var should = require('chai').should();
      var dotenv = require('dotenv').config();  // does not seam to work 
    },

    teardown: function(wallaby) {
      console.log('Teardown');
      console.log('Current worker id: ' + wallaby.workerId);
      console.log('Current session id: ' + wallaby.sessionId);
    }
  };
};

```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
There's only one thing in your config that looks incorrect, this entry in your `tests` list should be removed:
```javascript
{
        pattern: '../tests/wallaby.js',
        instrument: true,
        load: false,
        ignore: true
      }
```

Other than that, everything seems to be ok and should work. I have never used the `dotenv` module before, but just tried using it just the same way as you are with a setup function like this:
```javascript
    setup: function() {
      ...
      require('dotenv').config();
      console.log(process.env.MY_SETTING);
    },
```
and `.env` file like 
```
MY_SETTING=Test
```
and I can see the `console.log: Test` value being printed in the [Atom Dev Tools console](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting), so it seems to work.

What are the specific symptoms of it not working in your case? Perhaps it's something else.

**Comment by Ashtonian** [comment]
Thanks for the quick response. 

something must be wrong with mine then, I removed the pattern above as you suggested, would you be able to maybe post your test? I tried to simplify the .env file and it didn't seem to work, I still get undefined in the console. Its finding a .env file as if I remove the .env file from files or set the path wrong it logs a warning that it can't find one in the console. which is expected. 

I really appreciate it! It is probably something stupid on my side - learning a lot of new tooling. 

also you mentioned not using dotenv before - is there a better/more standard way to do this?

**Comment by ArtemGovorov** [comment]
Have been putting a sample repo together and I think I found the issue. In my local sample I was trying with
```javascript
{pattern: '.env', instrument: false},
```
in my `files` list, but when I try just `'.env'` like in your config, it also doesn't work for me. 

What happens is wallaby instruments files by default (to collect code coverage), and we don't want this to happen to the `.env` file (because it's not even JavaScript), so just [add `instrument: false` flag to the entry](http://wallabyjs.com/docs/config/files.html#file-object).

> also you mentioned not using dotenv before - is there a better/more standard way to do this?

Different people prefer to do it differently, it also depends on whether you really need your settings to end up in `process.env`. I personally don't use ENV variables much (only for modules that require me using it) and prefer to store my settings in some `config.json` (or sometimes even right in `package.json`), so that I can just do
```javascript
var settings = require('./config');
console.log(settings.mySetting);
```

**Comment by Ashtonian** [comment]
that worked! thanks, also thanks for the notes about config variables, i'll keep that in mind.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by citypaul** [comment]
Two years after this post and it saved the day for me. Thanks!
