### ISSUE TITLE
Incorrect error message if "tests" missing in config

### ISSUE THREAD

**Issue by bruderstein** [wallabyjs/public#5]
If the "tests" property is missing in the config, the error message is "Configuration should have a "files" property".

**Comment by ArtemGovorov** [comment]
Thanks, fixed.

**Comment by ArtemGovorov** [comment]
p.s. the plugin will be updated automatically next time you start it.

**Comment by szarouski** [comment]
Hi Artem, FYI plugin didn't update automatically.

**Comment by ArtemGovorov** [comment]
Thanks I have fixed it a couple of hours ago - was the server file with versions issue. Still doesn't work?

**Comment by szarouski** [comment]
I'm sorry, I'm not reading carefully. It updated after I ran wallaby (I was thinking about WS).
