### ISSUE TITLE
TypeError: Cannot read property 'cache' of undefined -- trying to use jsdom instead of phantomjs

### ISSUE THREAD

**Issue by hrmoller** [wallabyjs/public#501]
### Issue description or question
We're trying to replace PhantomJS with jsdom. The reason for that is that we're using jsdom with Karma in our CI environment and due to minor differences between the two (jsdom/PhantomJS) when it comes to parsing of the DOM, we want to use jsdom in WallabyJS as well.

When running our tests with WallabyJS the following is thrown: `TypeError: Cannot read property 'cache' of undefined` and not really able to track down where it's thrown or whether it's WallabyJS or Webpack that throws it.

### Wallaby.js configuration file
This is the current state of our `wallaby.config.js` which also [can be found here](https://github.com/DBCDK/biblo/tree/dev/mmj) along with the rest of the project:
```javascript
'use strict';
let wallabyWebpack = require('wallaby-webpack');
let webpackConfig = require('./webpack.test.config');
let babel = require('babel-core');
let path = require('path');
let jsdom = require('jsdom');

const babelConfig = (() => {
  const file = __dirname + '/.babelrc';

  try {
    fs.accessSync(file, fs.R_OK);
  } catch (error) {
    return {babel};
  }

  try {
    const config = JSON.parse(fs.readFileSync(file));
    config.babel = babel;
    return config;
  } catch (error) {
    throw error;
  }
})();

module.exports = function(wallaby) {
  webpackConfig.resolve = {
    root: [
      path.join(wallaby.projectCacheDir, 'src/client/components'),
      path.join(wallaby.projectCacheDir, 'node_modules')
    ],
    extensions: ['', '.js', '.svg', '.scss']
  };

  let webpackPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [
      {pattern: 'src/client/**/*.js', load: false},
      {pattern: 'src/client/**/*.scss', load: false},
      {pattern: 'src/client/**/*.svg', load: false},
      {pattern: 'src/client/**/__tests__/*.test.js', ignore: true}
    ],

    tests: [
      {pattern: 'src/client/**/__tests__/*.test.js', load: false}
    ],

    postprocessor: webpackPostprocessor,

    bootstrap: function() {
      require('jsdom-global')();
    },

    testFramework: 'mocha',

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelConfig)
    },

    debug: false,

    setup: function() {
      // require('jsdom-global')();
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version
IntelliJ IDEA v15

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It looks like you are trying to do something that is not supported in wallaby - run webpack-ed app in node environment. At the moment wallaby only supports webpack in browser (PhantomJs) environment.

I have seen quite a few people using `jsdom` with wallaby, but they do it without webpack, allowing node to resolve all CommonJs `require`. But in your case you are using webpack loaders for `.scss` and `.svg`, not sure how easy it's be to import those without webpack.

**Comment by hrmoller** [comment]
Alright, that makes sense, I might experiment with an alternative solution without webpack.

Thank you for your answer and great tool.

**Comment by ArtemGovorov** [comment]
Ok, thanks for the update. Sorry that my answer wasn't really helpful in this case. Let me know if I can help with the node + non-webpack solution. Perhaps [this project may be helpful](https://github.com/epsitec-sa/electrum-starter-3/blob/master/wallaby.conf.js), they use `jsdom` + `react` + node with mocha/wallaby and `webpack` for prod build.

**Comment by hrmoller** [comment]
No worries, the information about webpack and running wallaby in node-env was enough to push it further. The project you reference looks very interesting so I'll have a look at it.
Thanks again🙏
