### ISSUE TITLE
Start up automatically in Visual Studio 2015

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#505]
Hi,

I've had a look at the documentation, but can't find an answer to my question. I was wondering if it’s possible to get Wallaby.js to start automatically when I open a project that has a configuration file in it? Reason being that I’m hopeless at remembering such things :) and will no doubt forget to do it manually.

It’s otherwise working perfectly for my TypeScript project, and I bought it pretty much straight away—thanks!

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Hi Dylan, thanks for your support!

There's nothing built-in yet to auto-start it, but [this solution](https://github.com/wallabyjs/public/issues/340#issuecomment-157570219) has been working good for a few users who'd like to automatically start wallaby.

**Comment by ArtemGovorov** [comment]
You may also check out the solution in [this SO question update](http://stackoverflow.com/questions/35718201/start-wallaby-js-automatically-after-visual-studio-solution-got-loaded).
