### ISSUE TITLE
ReferenceError on Atom

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#509]
### Issue description or question
Can't run Wallaby on Atom but every other editor works just fine. Is complaining about all the Babel plugins.

I'm getting this error:

```
ReferenceError: Unknown plugin "transform-class-properties" specified in "base" at 1, attempted to resolve relative to "tests/actions"
```
### Wallaby.js configuration file

```javascript
// jscs:disable
/* eslint-disable*/

const babel = require('babel-core');
const webpack = require('webpack');
const wallabyWebpack = require('wallaby-webpack');
const path = require('path');

const webpackPostprocessor = wallabyWebpack({
  resolve: {
    root: path.resolve(__dirname),
    alias: {
      'sinon': 'sinon/pkg/sinon',
      joi: 'app/vendor/joi'
    }
  },
  externals: {
    'jsdom': 'window',
    'cheerio': 'window',
    'react/lib/ExecutionEnvironment': true
  },
  node: {
    net: 'empty',
    tls: 'empty',
    dns: 'empty'
  },
  module: {
    noParse: [/node_modules\/sinon\//],
    loaders: [
      { test: /\.scss$/, loader: 'null' },
      { test: /\.json$/, loader: 'json' }
    ]
  },
  plugins: [
    new webpack.IgnorePlugin(/ReactContext/),
    new webpack.DefinePlugin({
      ENV: JSON.stringify('TEST')
    })
  ]
});

module.exports = function(wallaby) {
  const babelCompiler = wallaby.compilers.babel({
    babel: babel,
    presets: ['es2015', 'react', 'stage-2'],
    plugins: ['syntax-class-properties', 'transform-class-properties']
  });

  return {
    files: [
      { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
      { pattern: 'node_modules/babel-polyfill/dist/polyfill.min.js', instrument: false },
      { pattern: 'app/**/*.js', load: false },
      { pattern: 'app/**/*.spec.js', ignore: true },
      'app/**/*.scss'
    ],

    tests: [
      { pattern: 'tests/**/*.spec.js', load: false },
      { pattern: 'app/**/*.spec.js', load: false }
    ],

    compilers: {
      'app/**/*.js': babelCompiler,
      'tests/**/*.js': babelCompiler
    },

    postprocessor: webpackPostprocessor,

    bootstrap: function() {
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version
Atom v1.5.4

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
> every other editor works just fine

What other editors did you try?

Could you please check what core version do you have installed in your Atom plugin? It's printed in the the Atom Developer Tools Console (`Cmd + Alt + I`).

**Comment by ArtemGovorov** [comment]
If your core version in Atom plugin is not `1.0.196`, either wait a few minutes when it updates after you start wallaby.js or [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486), and try again.

If it still doesn't work, try [cloning the sample](https://github.com/ArtemGovorov/wallaby-webpack-es6-react), run `npm i` and try it in Atom. I have tried to make it as close to your setup as possible. If it works for you, try adding your project specific changes to break it.

**Comment by davegomez** [comment]
Sorry I could not attend this issue before, but I just got to work yesterday, update the plugins and everything works fine now in Atom.

BTW, there's an issue I notice and happened to me several times now.

Sometime, I have to make changes in the config file, save them, and run Wallaby again to make it work. Yesterday, after I pulled the changes from the repo, I ran Wallaby and 4 testing files was failing, so I added line breaks to each of them and Wallaby could ran again the tests and pass them, but that was the only way.

**Comment by ArtemGovorov** [comment]
Thanks for the update.

> there's an issue I notice and happened to me several times now.

If you manage find a way to reproduce it, please share a sample where I could have look into it in a separate issue.

**Comment by dijs** [comment]
I have this exact same error when trying to use the "transform-class-properties" plugin.

**Comment by ArtemGovorov** [comment]
@dijs Try updating wallaby.js core [like described here](https://github.com/wallabyjs/public/issues/633#issuecomment-224458545).
