### ISSUE TITLE
Test framework [mocha@2.0.1] is not supported

### ISSUE THREAD

**Issue by kruczy** [wallabyjs/public#51]
Hi I'm getting an error that mocha is not supported:
```
wallaby.js started
Failed to load configuration file:  Test framework [mocha@2.0.1] is not supported
```

my `wallaby.js` file:
```
var babel = require('babel');

var es6ToEs5Preprocessor = function(file) {
    return babel.transform(file.content, {sourceMap: true});
};

module.exports = {
    files: [
        "src/**/*.js"
    ],
    tests: [
        "test/**/*.test.js"
    ],
    preprocessors: {
        '**/*.js': es6ToEs5Preprocessor
    },
    env: {
        type: 'node',
        runner: 'node'
    },
    testFramework: 'mocha@2.0.1',
    debug: true
};
```

I have tried running without setting the framework though just getting a different error, mocha ins installed both locally and globally in the correct version

Thanks for any help

**Comment by kruczy** [comment]
Wasn't reading the doc properly, the version for node should be `2.1.0` after installing the correct one and changing the config all seems to work fine

**Comment by ArtemGovorov** [comment]
Please also note that you don't have to install it locally if you don't need it. Wallaby.js ships with one.
