### ISSUE TITLE
Wallabify + coffeescript

### ISSUE THREAD

**Issue by teddyhwang** [wallabyjs/public#511]
### Issue description or question

I'm having trouble setting up wallaby in a browserify + coffeescript project. All source files and tests are written in Coffeescript with Browserify. We also have some private node_module packages that use browserify settings that are defined in the module's package.json file like so:

```json
  "browserify": {
    "transform": [
      "coffeeify",
      "browserify-ng-html2js"
    ]
  }
```

When running wallaby, I get the following error: `Postprocessor run failure: Unexpected token`

Any suggestions on how to move forward?

### Wallaby.js configuration file
```javascript
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
  entryPatterns: [
    'src/scripts/**/*.js',
    'tests/client/**/*.js',
    'tests/selectors/**/*.js',
    'tests/defaultFormValues.js'
  ]
});

module.exports = function() {
  return {
    files: [
      {pattern: 'node_modules/@points/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.js', load: false},
      {pattern: 'src/scripts/**/*.html', load: false}
    ],
    tests: [
      {pattern: 'node_modules/@points/**/*.coffee', load: false},
      {pattern: 'node_modules/@points/**/*.json', load: false},
      {pattern: 'tests/client/**/*.coffee', load: false},
      {pattern: 'tests/selectors/**/*.coffee', load: false},
      {pattern: 'tests/defaultFormValues.coffee', load: false},
      {pattern: 'tests/generators.coffee', load: false}
    ],
    testFramework: 'mocha',
    postprocessor: wallabyPostprocessor,
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

Atom v1.5.4

### OS name and version

OSX

**Comment by teddyhwang** [comment]
Some other interesting observations: when I remove `'src/scripts/**/*.js'` from the `entryPatterns` array

I get the following error:
```javascript
Postprocessor run failure: Cannot find module 'coffeeify' from './node_modules/@points/pts-fixtures'
```

**Comment by ArtemGovorov** [comment]
There are a few potential issues in your config that may or may not be related to the issue, but need to be fixed to prevent other issues.

[Entry patterns](http://wallabyjs.com/docs/integration/browserify.html#entry-patterns) are normally used for files that you'd like to get loaded as entry points (tests and some test helpers that you need to execute before tests). Do you really need to have the `'src/scripts/**/*.js',` pattern in the entry pattern list?

`Tests` list should only [contain patterns for files with tests](http://wallabyjs.com/docs/config/files.html#tests), the files with specs/tests (`describe`/`it` in them). In your case it contains quite a few patterns that do not look like tests.

Regarding the issue itself, try inspecting the [Dev Tools console output](http://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) that should hopefully provide some more details about what/where is wrong.

> `Postprocessor run failure: Cannot find module 'coffeeify' from './node_modules/@points/pts-fixtures'`

Try removing the `node_modules/@points/**/*.coffee` pattern from your `files`/`tests`, any reason you need it to be there?

If after fixing your config and inspecting the debug output you don't find what the issue is, please create a sample repo where I could reproduce it, I'll jump in to reproduce and help. Alternatively, you may email me the sample to wallabyjs@gmail.com if it's easier for you.

**Comment by teddyhwang** [comment]
The test files do refer to certain coffeescript files in private modules in the node_modules folder (`node_modules/@points/`). When I remove them I get the error: `Postprocessor run failure: Cannot find module '../lpConfigurations/ft/globalrewards.json' from './node_modules/@points/pts-fixtures/storefront/ngInitialize'` which makes sense.

If I add `{pattern: 'node_modules/@points/**/*.json', load: false},` back into the files/tests array it works and my solution for getting around the `coffeeify` error was to add a postFilter into the wallabify options.

I'm now running into an issue where the project is having trouble adding a browserify transform into the HTML files. My wallabify config now looks like this:

```javascript
var wallabify = require('wallabify');
var _ = require('lodash');
var ngHtml2Js = require('browserify-ng-html2js');

var wallabyPostprocessor = wallabify({
  entryPatterns: [
    'tests/client/**/*.js'
  ],
  postFilter: function(id, file, pkg) {
    if (pkg && pkg.browserify && pkg.browserify.transform) {
      _.pull(pkg.browserify.transform, 'coffeeify');
    }
    return true;
  },
  function(b) { console.log(b.transform); b.transform({global: true}, ngHtml2Js) }
});

module.exports = function() {
  return {
    files: [
      {pattern: 'node_modules/@points/pts-fixtures/storefront/**/*.json', load: false},
      {pattern: 'node_modules/@points/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.js', load: false},
      {pattern: 'src/scripts/**/*.html', load: false},
      {pattern: 'tests/selectors/**/*.coffee', load: false},
      {pattern: 'tests/defaultFormValues.coffee', load: false},
      {pattern: 'tests/generators.coffee', load: false}
    ],
    tests: [
      {pattern: 'tests/client/**/*.coffee', load: false}
    ],
    testFramework: 'mocha',
    postprocessor: wallabyPostprocessor,
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    },
    debug: true
  };
};
```

I would much rather send you over a repository or a sample but this project setup is quite complex with a bunch of internal module references that I couldn't readily share.

Am I not correctly applying the `ng-html2js` transform into wallabify here?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update. It looks like we are getting somewhere.

> I would much rather send you over a repository or a sample but this project setup is quite complex with a bunch of internal module references that I couldn't readily share.

We could try to copy the project just remove everything sensitive, leaving only the issue related stuff. But hopefully we won't need to do this.

> Am I not correctly applying the ng-html2js transform into wallabify here?

It does look so.
You need to pass the `function(b) { console.log(b.transform); b.transform({global: true}, ngHtml2Js) }` as a second argument to `wallabify` function, but right now you have the function right in first argument object (which makes it a valid ES6 method definition shorthand).

So instead of
```javascript
var wallabyPostprocessor = wallabify({
  entryPatterns: [
    'tests/client/**/*.js'
  ],
  postFilter: function(id, file, pkg) {
    if (pkg && pkg.browserify && pkg.browserify.transform) {
      _.pull(pkg.browserify.transform, 'coffeeify');
    }
    return true;
  },
  function(b) { console.log(b.transform); b.transform({global: true}, ngHtml2Js) }
});
```
you need:
```javascript
  var wallabyPostprocessor = wallabify({
      entryPatterns: [
        'tests/client/**/*.js'
      ],
      postFilter: function (id, file, pkg) {
        if (pkg && pkg.browserify && pkg.browserify.transform) {
          _.pull(pkg.browserify.transform, 'coffeeify');
        }
        return true;
      }
    },
    function (b) { console.log(b.transform); b.transform({global: true}, ngHtml2Js)}
  );
```

**Comment by teddyhwang** [comment]
Thanks for pointing it out. Having updated the config, it still doesn't seem like the browserify transform is working as I'm still getting errors related to the HTML file not being converted into an angular template. I've also tried using the nghtml2js wallaby preprocessor with no luck. Here's my updated config file:

```javascript
var wallabify = require('wallabify');
var _ = require('lodash');
var ngHtml2Js = require('browserify-ng-html2js');
var angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');

var wallabyPostprocessor = wallabify({
    entryPatterns: [
      'tests/client/**/*.js'
    ],
    postFilter: function(id, file, pkg) {
      if (pkg && pkg.browserify && pkg.browserify.transform) {
        _.pull(pkg.browserify.transform, 'coffeeify');
      }
      return true;
    }
  },
  function(b) {
    b.transform(ngHtml2Js, {ext: '.html', global: true});
  }
);

var ngPreProcesss = function(file) {
  return angularTemplatePreprocessor.transform(file, {
    cacheIdFromPath: function(filepath) {
      paths = filepath.split('/');
      return paths.pop();
    }
  });
};

module.exports = function() {
  return {
    files: [
      {pattern: 'node_modules/@points/pts-fixtures/storefront/**/*.json', load: false, instrumented: false},
      {pattern: 'node_modules/@points/**/*.coffee', load: false, instrumented: false},
      {pattern: 'node_modules/@points/**/*.html', load: false, instrumented: false},
      {pattern: 'src/scripts/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.js', load: false, instrumented: false},
      {pattern: 'src/scripts/**/*.html', load: false},
      {pattern: 'tests/selectors/**/*.coffee', load: false},
      {pattern: 'tests/defaultFormValues.coffee', load: false},
      {pattern: 'tests/generators.coffee', load: false}
    ],
    tests: [
      {pattern: 'tests/client/**/*.coffee', load: false}
    ],
    testFramework: 'mocha',
    postprocessor: wallabyPostprocessor,
    preprocessors: {
      'src/scripts/**/*.html': ngPreProcesss,
      'node_modules/@points/**/*.html': ngPreProcesss
    },
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

The specific error I'm getting:

> `Postprocessor run failure: Unexpected token (2:28) while parsing /Users/teddyhwang/Sites/Points/apollo/storefront/storefront-ng-core/node_modules/@points/pts-ng-translations/src/pts.translations.coffee while parsing file: /Users/teddyhwang/Sites/Points/apollo/storefront/storefront-ng-core/node_modules/@points/pts-ng-translations/src/pts.translations.coffee`

Line 2 of that file is: `require './pts.select-language.html'`

Thanks @ArtemGovorov for the continued support.

**Comment by ArtemGovorov** [comment]
I have created [this sample repo](https://github.com/wallabyjs/wallaby-511) with the config exactly like yours (I just removed `preprocessors` because the transform should be enough) and the file structure assembled from your config and the error message.

It works for me. Well, it throws `Can't find variable: angular` because I'm not loading angular anywhere, but it successfully compiles the HTML file. I can also see the compiled file in [the wallaby cache](http://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page).

Please have a look into the sample, see if it works for you and if so, try adding your project specific things I that have missed to try and break it.

**Comment by teddyhwang** [comment]
Thanks for setting up the repo! After going through your example, I realized I was looking in the wrong area and the error was not a transform issue but browserify thinking the coffeescript file in the node_modules folder being a JS file. I've updated the config that allows wallaby to get past the postprocessor phase:

```javascript
var wallabify = require('wallabify');
var _ = require('lodash');
var ngHtml2Js = require('browserify-ng-html2js');

var wallabyPostprocessor = wallabify({
    entryPatterns: [
      'tests/client/**/*.js'
    ],
    extensions: ['.coffee']
  },
  function(b) {
    b.transform(ngHtml2Js, {ext: '.html', global: true});
  }
);

module.exports = function() {
  return {
    files: [
      {pattern: 'src/scripts/**/*.coffee', load: false},
      {pattern: 'src/scripts/**/*.js', load: false, instrumented: false},
      {pattern: 'src/scripts/**/*.html', load: false},
      {pattern: 'node_modules/@points/pts-fixtures/storefront/**/*.json', load: false, instrumented: false},
      {pattern: 'tests/selectors/**/*.coffee', load: false},
      {pattern: 'tests/defaultFormValues.coffee', load: false},
      {pattern: 'tests/generators.coffee', load: false}
    ],
    tests: [
      {pattern: 'tests/client/**/*.coffee', load: false}
    ],
    testFramework: 'mocha',
    postprocessor: wallabyPostprocessor,
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    },
    debug: true
  };
};
```

However, I'm not seeing an interesting issue with the tests not able to find modules that it references:

> ```
> Error: Cannot find module '/Users/teddyhwang/Dropbox/dotfiles/.atom/packages/atom-wallaby/projects/736cc9ca299fdfb3/instrumented/tests/client/StorefrontModule.js'
> at tests/client/integration/buy.coffee:2:0
> at tests/client/integration/buy.coffee:1:0
> ```

In `buy.coffee`:

```coffeescript
lodash = require 'lodash'
StorefrontModule = require '../StorefrontModule'
```

Similar errors appear in other test files. In StorefrontModule itself, it can't seem to find a file in the same folder:

> ```
> Error: Cannot find module '/Users/teddyhwang/Dropbox/dotfiles/.atom/packages/atom-wallaby/projects/736cc9ca299fdfb3/instrumented/tests/client/fixtures.js'
> at tests/client/StorefrontModule.coffee:11:0
> at tests/client/StorefrontModule.coffee:457
> at tests/client/StorefrontModule.coffee:459
> ```

Line 11 in `StorefrontModule.coffee`

```coffeescript
Module = require './Module'
```

When I open the folder that contains the instrumented files, I do see a StorefrontModule.js file that seems correctly instrumented.

I think we're very close now! Any clues on why it might not be able to find those particular modules?

**Comment by ArtemGovorov** [comment]
As I have mentioned before, `tests` list [should only contain patterns for files with tests](http://wallabyjs.com/docs/config/files.html#tests), the files with specs/tests (describe/it in them). 

In your case, are `buy.coffee`, `StorefrontModule.coffee`, `tests/client/fixtures.js`, etc. files with tests? If not, they should be listed in the `files` list. Normally test names have certain pattern, like `*-spec.coffee` or something like that, so you may use whatever your test file name pattern is in your `tests` list and specify the rest in the files list by excluding the `tests` pattern:

```
files: [
      ...
      {pattern: 'tests/client/**/*.coffee', load: false},
      {pattern: 'tests/client/**/*-spec.coffee', ignore: true},
    ],
    tests: [
      {pattern: 'tests/client/**/*-spec.coffee', load: false}
    ],
```

**Comment by teddyhwang** [comment]
That did it! Everything seems to be working now. Thank you very much for the detailed support.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
