### ISSUE TITLE
Correct setup for wallaby + ES6 + angular/angular-mocks + webpack?

### ISSUE THREAD

**Issue by Busata** [wallabyjs/public#513]
### Cannot find a way to get wallaby to work with my angular / ES6 / webpack setup

With the configuration files below, and the test I'm trying to run, I keep getting errors that angular could not be found. Since I need angular as well in the tests, I tried loading it in the tests files, which results in read only errors, since angular-mocks requires angular to be loaded on the window object, so I added that too, but then I just receive errors that angular.mock.module('app') cannot find that module, making me think that it has not "loaded" the angular application. I've got the feeling I'm not "getting" how wallaby loads it files & ties it together, but for now it seems that it's not finding my application/nor importing the correct files. 

For my setup, I'm using a single index.js in which all functions/variables are imported and in that same index.js, I created the angular module & bind everything that was imported to it. So that file does not seem to get loaded.

``` javascript
import {Card} from '../src/shared/entities/Card';

describe('Component: CardPractice', () => {
    let $compile, $rootScope;
    beforeEach(angular.mock.module('app'));
    beforeEach(angular.mock.inject(function(_$compile_, _$rootScope_) {
        $compile = _$compile_;
        $rootScope = _$rootScope_;
    }));
    beforeEach(() => {
        $rootScope.cards = [new Card('Speed of a swallow?','Unladen?'), new Card('Answer to everything?', '42')];
        let element = angular.element('<card-practice cards="cards"></card-practice>')
        $compile(element)($rootScope.$new());
    });


    it('should show a card from the list', ()=> {

    })
});
```

### Wallaby.js configuration file
``` javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config.js');
var babel = require('babel-core');

webpackConfig.module.loaders = webpackConfig.module.loaders.filter(function(l){
    return l.loader !== 'babel-loader';
});

module.exports = function(wallaby) {
    return {
        debug: true,
        files: [
            {pattern: 'src/**/*.js', load: false}
        ],
        tests: [
            {pattern: 'tests/**/*.js', load: false}
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel,
                presets:['es2015']
            })
        },
        postprocessor: wallabyWebpack(webpackConfig),
        env: {
            type: 'browser',
            runner: 'node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs.exe',
            params: { runner: '--web-security=false' }
        },
        testFramework: 'jasmine',
        bootstrap: function() {
          window.__moduleBundler.loadTests();
        }
    }
}
```

### Webpack configuration file
``` javascript
var path = require('path');

module.exports = {
    entry: './src/index.js',
    output: {
        path: path.resolve(__dirname, 'build'),
        publicPath: "/assets/",
        filename: 'bundle.js'
    },
    resolve: {
        modulesDirectories: ['src', 'tests', 'node_modules'],
        extensions: ['', '.webpack.js','.js']
    },
    module: {
        loaders: [
            {
                test: /\.js?$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel',
                query: {
                    presets: ['es2015']
                }
            },
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            },
            {
                test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: "url-loader?limit=10000&minetype=application/font-woff"
            },
            {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader"}
        ]
    }
};
```

### Code editor or IDE name and version
IntelliJ IDEA v15

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
>  I tried loading it in the tests files, which results in read only errors

`Tests` list should only contain patterns for [actual test files](http://wallabyjs.com/docs/config/files.html#tests) and nothing else

> I've got the feeling I'm not "getting" how wallaby loads it files & ties it together, but for now it seems that it's not finding my application/nor importing the correct files.

I think you've almost got it working. In case of webpack, wallaby mostly just uses it to compile everything and then is using tests as *entry points* to start/load everything. In your case however it looks like you need something to be loaded **before** tests, specifically your `src/index.js` file.

To do it, you'll need to specify your index file (where you load everything) in the [`entryPatterns` list](http://wallabyjs.com/docs/integration/webpack.html#entry-patterns) so it gets loaded before tests.

```javascript
var webpackConfig = require('./webpack.config.js');
...
webpackConfig.entryPatterns = ['src/index.js', 'tests/**/*.js'];
```


P.S. Unrelated to the issue, but if you get some `ModuleNotFound` errors (you may not not get them, but just in case), you may need adjust paths like described in [this](http://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) section of the docs.

**Comment by Busata** [comment]
Thanks in advance for your response, but I'm still a bit confused about the entryPatterns, if I specify it like you did, it does seem to find the angular global, so I think it has loaded src/index.js correctly, but I cannot find a way to load angular-mocks.js for every test. Does wallaby treat globals in a different way? angular-mocks.js requires the angular global, but it cannot seem to find it. I tried adding it after the src/index in the entryPatterns, but that doesn't seem to work, nor does require'ing that specific file in my test files.

**Comment by ArtemGovorov** [comment]
> it does seem to find the angular global

From your webpack config file (because you don't have `angular` loaded via externals or anything like that) I assumed that you do something like `window.angular = require('angular')` in your `src/index.js`.

It looks like it's not the case. I'm not sure how angular gets loaded in your prod app or tests outside wallaby, but if you don't load it anywhere else, you may just load `angular` and `angular-mocks` without webpack [in global scope via script tags](http://wallabyjs.com/docs/config/files.html#file-object), like:

```javascript
module.exports = function(wallaby) {
    return {
        debug: true,
        files: [
            {pattern: 'node_modules/angular/angular.js', load: true, instrument: false}
            {pattern: 'node_modules/angular-mocks/angular-mocks.js', load: true, instrument: false}
            {pattern: 'src/**/*.js', load: false}
        ],
...
```
(here I'm assuming you have `angular` and `angular-mocks` installed as node modules).

**Comment by Busata** [comment]
I do require angular in my src/index.js (import angular from 'angular'), so it gets that from the node_modules. Angular-mocks is only needed for tests, so I tried loading them in the files/entryPatterns as you mentioned, but I keep getting errors. I'll try for a bit longer with your input & see if I can fix it.

**Comment by ArtemGovorov** [comment]
Got it. Then perhaps you may create `src/index-tests.js` (you may have the file in `tests/` folder, but because it's not a test, it has to be excluded from the `tests` patterns and included in the `files` list), add it to the entry patterns as well, and inside it you may do
```
require('angular-mocks');
```

**Comment by Busata** [comment]
If I do that, with beforeEachTest.js having the require('angular-mocks'), it does not seem to pick up that file, wallaby does not indicate that it has run through that file (no green indicator). But it still seems to give the same errors, it can find angular, but angular-mocks has not added itself to it. In console I see no particular errors for that file.

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config.js');
var babel = require('babel-core');

webpackConfig.entry = {};
webpackConfig.entryPatterns = ['src/index.js', 'tests/beforeEachTest.js', 'tests/**/*.spec.js'];

module.exports = function (wallaby) {
    return {
        debug: true,
        files: [
            {pattern: 'tests/beforeEachTest.js', load: true},
            {pattern: 'src/**/*.js', load: false}
        ],
        tests: [
            {pattern: 'tests/**/*.spec.js', load: false}
        ],
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babel: babel,
                presets: ['es2015']
            })
        },
        postprocessor: wallabyWebpack(webpackConfig),
        env: {
            type: 'browser',
            runner: 'node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs.exe',
            params: {runner: '--web-security=false'}
        },
        testFramework: 'jasmine',
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    }
}
```

**Comment by ArtemGovorov** [comment]
Try setting `load: false` to the pattern (you're loading it via webpack entry patterns, so no need to load the file via script tag):
```
{pattern: 'tests/beforeEachTest.js', load: false},
```

**Comment by Busata** [comment]
woops, wrong edit, I did it with webpack, because the load:true gives errors when encountering the require keyword.

**Comment by Busata** [comment]
if I put console.log's in the beforeEachTest.js, they don't seem to trigger either, so I presume this means wallaby doesn't pick it up before running the test for some reason?

**Comment by ArtemGovorov** [comment]
Correct, but I'm not sure why. The config looks correct, unless there's some small typo somewhere that I don't see. Just as a sanity check, let's try something. In your `src/index.js`, try adding 
```
require('../tests/beforeEachTest');
```

**Comment by ArtemGovorov** [comment]
I think I'm able to reproduce the issue. Not yet sure, but I think it's the `wallaby-webpack` package related one. Looking into it now.

**Comment by Busata** [comment]
I could not require the beforeEachTest because module not found errors, so I assume that is related to the caching that you mentioned before. If I require('angular-mocks') directly in the index.js, the test runs fine, but that's not a solution ofc, I'll await your investigation, thanks!

**Comment by ArtemGovorov** [comment]
Ok, as I have been suspecting, it was a bug in `wallaby-webpack`. I [have fixed](https://github.com/jeffling/wallaby-webpack/commit/53c8a5b8c4f37bf01fd5a617bade3a96d0c488f9) it and published the new version. Try updating `wallaby-webpack` module to 0.0.18 and try running your tests now with:
```javascript
...
webpackConfig.entryPatterns = ['src/index.js', 'tests/beforeEachTest.js', 'tests/**/*.spec.js'];

module.exports = function (wallaby) {
    return {
        ...
        files: [
            {pattern: 'tests/beforeEachTest.js', load: true},
            {pattern: 'src/**/*.js', load: false}
        ],
...
```

**Comment by Busata** [comment]
Super, that fixed it, file is loaded now. Thanks for the fast & great support :)

**Comment by ArtemGovorov** [comment]
Great, thanks for the update and for helping to find the bug.

**Comment by Busata** [comment]
https://github.com/Busata/angular-1.5-es6-webpack-wallaby-karma I've created a small repository with this setup, if it's to any use in the docs.

**Comment by ArtemGovorov** [comment]
@Busata Wow, awesome, thanks for putting it together and for sharing! I have added the sample to the [collection of our recepies](http://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes) and to [the Angular doc page as well](http://wallabyjs.com/docs/integration/angular.html)
