### ISSUE TITLE
Cannot find module 'acorn-babel'

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#516]
### Issue description or question

Hi,

I’m getting the following error when attempting to use Wallaby with TypeScript via WebPack:

```
Error: Cannot find module 'acorn-babel'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at s (C:\Users\Dylan\.wallaby\core\server.js:14:114)
    at C:\Users\Dylan\.wallaby\core\server.js:14:305
    at Object.o.10.acorn-babel (C:\Users\Dylan\.wallaby\core\server.js:15:8146)
    at s (C:\Users\Dylan\.wallaby\core\server.js:14:254)
    at C:\Users\Dylan\.wallaby\core\server.js:14:305
    at Object.o.17../config (C:\Users\Dylan\.wallaby\core\server.js:16:2478)
wallaby.js stopped
```

I’m a little confused by the error as I’m not using Babel at all in my project as I’m getting TypeScript to compile all my source to ES5.

I was previously running Wallaby without WebPack and running my tests in a node environment, however I now require tests to run in a browser environment so am trying to set up WebPack in order to handle all the `require(…)` statements.

I followed the examples on the website. Any idea what I’m doing wrong?

Thanks

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack')
var wallabyPostprocessor = wallabyWebpack({})

module.exports = function (wallaby) {
	return {
		files: [
		  'scripts/**/*.ts*',
		  { pattern: 'scripts/**/*-spec.ts', ignore: true }
		],

		tests: [
		  'scripts/**/*-spec.ts'
		],

		compilers: {
			'**/*.ts*': wallaby.compilers.typeScript({
				module: 'commonjs',
				target: 'es5',
				jsx: 'react'
			})
		},

		testFramework: 'mocha',

		postprocessor: wallabyPostprocessor,

		setup: function () {
			window.__moduleBundler.loadTests()
		}
	}
}
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
We have had an issue with the latest wallaby core update. 

Please try restarting your IDE and starting wallaby, it should update the core version and the issue should be fixed.

Sorry about the issue.

**Comment by dylanparry** [comment]
Thanks, that got rid of that error! I’m getting another error now, but I’ll open a new issue for that.
