### ISSUE TITLE
`testFileIdCanNotBeDetermined` thrown when using co-mocha

### ISSUE THREAD

**Issue by TerenceZ** [wallabyjs/public#52]
```js
'use strict';

const should = require('should');
require('co-mocha');

describe('test', function () {
    it('should pass', function *() {
        yield function (next) {
            setTimeout(next, 1000);
        };
    });
});
```

When I test the above case, it will throw the following error:

```error
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'should pass test',
  id: 100001,
  log: undefined,
  filesInvolved: [] }
```

**Comment by ArtemGovorov** [comment]
The issue is that co-mocha monkey patches mocha instances and when it does so, it looks for them by mocha file name. The file name is not the same in case of normal mocha install and in case of wallaby.js used mocha instance. To fix the issue, you can use the following [`bootstrap` function](https://github.com/wallabyjs/public#bootstrap-setting) in your wallaby.js config file (I have taken the rest of your config from your previous issue).
```javascript
module.exports = function () {
  return {
    "files": [
      "config/index.js"
    ],
    "tests": [
      "test/config.test.js"
    ],
    "workers": {
      "recycle": true
    },
    "env": {
      "type": "node",
      "params": {
        "runner": "--harmony"
      }
    },
    bootstrap: function() {
      var path = require('path');
      require('co-mocha')(require(path.join(path.dirname(process.argv[1]), 'runners/node/mocha@2.1.0/framework/')));
    }
  };
};
```

Let me know if it works for you.

**Comment by ArtemGovorov** [comment]
Forgot to mention, with the `bootstrap` function like this one, you also don't need to call `require('co-mocha');` in your test files, as calling it once from the `bootstrap` function is enough. You may leave it if you want, but the call is not necessary anymore.

**Comment by TerenceZ** [comment]
Thanks, this solution works for me! But I think it is better to get these paths (e.g., 'runners/node/mocha@2.1.0...') in the argument `wallaby` supplied by `bootstrap` function.

**Comment by ArtemGovorov** [comment]
Agreed, will add these paths to the `wallaby` argument.

**Comment by justmoon** [comment]
@ArtemGovorov @TerenceZ 

Big thanks for that solution. That would have taken me forever to figure out on my own.

Btw. to avoid the path issue, I came up with this option:

```js
    bootstrap: function (wallaby) {
      require('co-mocha')(wallaby.testFramework.constructor)
    }
```

Full example:

``` js
module.exports = function () {
  return {
    files: [
      // ...
    ],

    tests: [
      'test/*Spec.js'
    ],

    testFramework: 'mocha',

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_ENV=unit'
      }
    },

    bootstrap: function (wallaby) {
      require('co-mocha')(wallaby.testFramework.constructor)
    }
  }
}
```

**Comment by ArtemGovorov** [comment]
@justmoon :+1:  nice! Very clean solution.
