### ISSUE TITLE
Angular 2 inline styles no-op

### ISSUE THREAD

**Issue by ShadowSoftware** [wallabyjs/public#520]
Hey Artem,

Using Angular 2 with a component decorator like this breaks the component when using the no-op method because it is returning a function and Angular throws attempting to string replace on it. Is there a way it can be no-op'd to an empty string, preferably without modifying the require?

Thanks

@Component({
    styles: [require('!raw!less!../some.less')]
})

Wallaby config:
var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'spec-bundle.js',
      'app/**/*.spec.js',
      //'app/**/*.steps.js',
    ],

    plugins: [
        new webpack.NormalModuleReplacementPlugin(/\.(gif|jpg|png|scss|css|less)$/, 'node-noop')
    ],

    module: {
        loaders: [
          { test: /\.css$/, loader: 'raw-loader' },
          { test: /\.html$/, loader: 'raw-loader' },
          { test: /\.less$/, loader: "raw-loader" },
        ]
    }
});

**Comment by ArtemGovorov** [comment]
Hello,

It doesn't look like wallaby.js related issue, seems like a webpack config issue.

AFAIK, `no-op` returns an empty object, and as you have said, Angular 2 component decorator expects an array of strings for the `styles` property.

The easiest way to fix it would be to to remove `less` pattern from the `NormalModuleReplacementPlugin` condition and use [webpack `null` loader](https://github.com/webpack/null-loader), which according to its source code [returns a string](https://github.com/webpack/null-loader/blob/master/index.js#L7).
```javascript
var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'spec-bundle.js',
      'app/**/*.spec.js',
      //'app/**/*.steps.js',
    ],

    plugins: [
        new webpack.NormalModuleReplacementPlugin(
          /\.(gif|jpg|png|scss|css)$/, 
          'node-noop')
    ],

    module: {
        loaders: [
          { test: /\.css$/, loader: 'raw-loader' },
          { test: /\.html$/, loader: 'raw-loader' },
          { test: /\.less$/, loader: "null" },
        ]
    }
});
```

Another way would be to to create an empty `app/noop.less` file (may need to add it to your `files` list) and do:
```javascript
plugins: [
    new webpack.NormalModuleReplacementPlugin(
      /\.(less)$/, 
      require('path').resolve('./', './app/noop.less'))
],
```
Perhaps there are some other webpack plugins that no-op to an empty string. [Looking into the `node-noop` plugin source](https://github.com/euank/node-noop/blob/master/index.js), I'd also imagine it wouldn't be to hard to create one.

Let me know if it helps.

**Comment by ZachHardin** [comment]
Ah thank you! I feel bad for asking you now I should have figured that out already LOL. As usual, great answer. We appreciate that =)

**Comment by ArtemGovorov** [comment]
No worries at all, I just assumed that was something broken in wallaby when I saw the issue, so started with trying to find an issue in our code :)
