### ISSUE TITLE
Using babel with typescript

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#523]
Im in a bit of a pickle. I code in typescript, but i use babel in my webpack to load the compiled typescript. The problem is, that i use jsx-control-statements plugin that allows me to use For, If statements in react. These are maintained by typescript compiler, yet they are translated by babel plugin to core react code. I use enzyme to test my components, but it is obviously failing after typescript compilation as it does not recognise For, If statement. Is it possible to setup a pipeline in which the compiled code would pass by Typescript AND then babel? If not, i can just compile typescript to temp directory and use the compiled code with babel loader. But, if it wouldnbe possible ... More awesome;)

**Comment by ArtemGovorov** [comment]
It is possible, you need to add a [preprocessor](http://wallabyjs.com/docs/config/preprocessors.html) for babel transformation:
```javascript
module.exports = function (wallaby) {
    return {
        files: [
            ...
        ],
        tests: [
            ...
        ],
        preprocessors: {
            '**/*.js': file => require("babel-core")
                .transform(file.content,
                {
                    sourceMap: true,
                    // you may add the jsx-control-statements plugin instead
                    presets: ["es2015"]
                })
        }
...
};
```

Wallaby.js TypeScript compiler + Babel preprocessor + Webpack postprocessor combo works like this:
- TypeScript compiler runs and compiles your `.ts` files to `.js` files.
- Babel preprocessor runs and compiles your `.js` files.
- Webpack postprocessor runs does the rest.

**Comment by ArtemGovorov** [comment]
Let me know if the solution works for you.

**Comment by tomitrescak** [comment]
Amazing support, as ever .. unfortunately this does not work as "jsx-control-statements" is a plugin not a preset. How can I load a plugin? Thanks

**Comment by tomitrescak** [comment]
I even created .babelrc with following:

```
{
  "plugins": ["jsx-control-statements"]
}
```

But I'm getting still `For is not defined`

**Comment by ArtemGovorov** [comment]
I haven't used this one, but AFAIR: `plugins: ["jsx-control-statements"]`?

**Comment by tomitrescak** [comment]
This is what I have now:

```
preprocessors: {
      "**/*.js*": file => require("babel-core").transform(file.content, {
        sourceMap: true,
        // you may add the jsx-control-statements plugin instead
        presets: [ "es2015" ],
        plugins: [ "jsx-control-statements" ]
      })
    },
```

**Comment by ArtemGovorov** [comment]
May I see your full config please?

**Comment by tomitrescak** [comment]
OK, for error is gone .. I had a compiler AND preprocessor active at te same time. Now I'm getting "Unexpected token". This is my config:

```javascript
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  var load = require;

  return {
    files: [
      "src/client/modules/**/components/*.tsx",
      "src/client/modules/**/actions/*.ts",
      "src/client/modules/**/containers/*.ts",
      "src/client/modules/**/libs/*.ts"
    ],
    tests: [
      "src/client/**/tests/*.js", "src/client/**/tests/*.ts", "src/client/**/tests/*.tsx"
    ],
    // compilers: {
    //   "**/*.js*": wallaby.compilers.babel({
    //     babel: load("babel-core"),
    //     presets: [ "es2015", "stage-2", "react" ]
    //   }),
    //   "**/*.ts*": wallaby.compilers.typeScript({module: "commonjs", jsx: "react"})
    // },
    preprocessors: {
      "**/*.js*": file => require("babel-core").transform(file.content, {
        sourceMap: true,
        // you may add the jsx-control-statements plugin instead
        presets: [ "es2015", "stage-2", "react" ],
        plugins: [ "jsx-control-statements" ]
      })
    },
    env: {
      type: "node"
    },
    testFramework: "mocha",
    setup: function() {
      global.React = require("react");
    }
  };
};
```

**Comment by tomitrescak** [comment]
@ArtemGovorov got it back to "For is not defined" with this config. Looks like the preprocessor is not kicking in. If I run it over the compiled JS files in temporary folder it runs ok.

```javascript
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  //var load = require;

  return {
    files: [
      "src/client/modules/**/components/*.tsx",
      "src/client/modules/**/actions/*.ts",
      "src/client/modules/**/containers/*.ts",
      "src/client/modules/**/libs/*.ts",
      "src/typings/**/*.d.ts"
    ],
    tests: [
      "src/client/**/tests/*.js",
      "src/client/**/tests/*.ts",
      "src/client/**/tests/*.tsx"
    ],
    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "commonjs", jsx: "react"})
    },
    preprocessors: {
      "**/*.js*": file => require("babel-core").transform(file.content, {
        sourceMap: true,
        // you may add the jsx-control-statements plugin instead
        presets: [ "es2015", "stage-2", "react" ],
        plugins: [ "jsx-control-statements" ]
      })
    },
    env: {
      type: "node"
    },
    testFramework: "mocha",
    setup: function() {
      global.React = require("react");
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Is there a sample repo I could clone and have a look?

**Comment by tomitrescak** [comment]
Artem, I solved it partially. I had to be compiling with react preserved in order for "For" not to be handled by typescript compiler.

`"**/*.ts*": wallaby.compilers.typeScript({module: "es6", jsx: "preserve"})`

BUT: my test code HAS TO be stored in the tsx files when I'm testing components, but "jsx" and "tsx" are ignored by Wallaby tests (see my config). Wallaby picks up unly tests stored in "js" and "ts" files. Can this be solved?

**Comment by ArtemGovorov** [comment]
>  I had to be compiling with react preserved in order for "For" not to be handled by typescript compiler.

Ah, it makes sense, because otherwise TypeScript complies the JSX to valid JS with `React.createElement('For',...)` so it's too late the `jsx-control-statements` to do anything.

> my test code HAS TO be stored in the tsx files when I'm testing components, but "jsx" and "tsx" are ignored by Wallaby tests (see my config). Wallaby picks up unly tests stored in "js" and "ts" files. 

Sorry, I'm not sure if I'm understanding correctly what is going on. Are your tests in `.tsx` files or in `.js` files? You should leave one pattern and remove the other, otherwise compiled tsx file may (or may not) overwrite the js files with the same names.

Anyway, I have a small local sample with your config and its working for me. Let me know if you can share your sample or would like me to publish mine.

**Comment by tomitrescak** [comment]
Yes, my tests are defined in TSX files and wallaby is not picking them up,this is my current config. If you could share your repo with tests stored in TSX files I would be really greatfull. Thanks:

```javascript
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  //var load = require;

  return {
    files: [
      "src/client/modules/**/components/*.jsx",
      "src/client/modules/**/actions/*.js",
      "src/client/modules/**/containers/*.js",
      "src/client/modules/**/libs/*.ts",
      "src/typings/**/*.d.ts"
    ],
    tests: [
      "src/client/**/tests/*.ts",
      "src/client/**/tests/*.tsx"
    ],
    compilers: {
      // "**/*.js*": wallaby.compilers.babel({
      //   babel: require("babel-core"),
      //   presets: [ "es2015", "stage-2", "react" ]
      // }),
      "**/*.ts*": wallaby.compilers.typeScript({module: "es6", jsx: "preserve"})
    },
    preprocessors: {
      "**/*.js*": file => require("babel-core").transform(file.content, {
        sourceMap: true,
        // you may add the jsx-control-statements plugin instead
        presets: [ "es2015", "stage-2", "react" ],
        plugins: [ "jsx-control-statements" ]
      })
    },
    env: {
      type: "node"
    },
    testFramework: "mocha",
    setup: function() {
      global.React = require("react");
    }
  };
};
```

**Comment by tomitrescak** [comment]
A small repo with one react component with enzyme would be great ;)))) It seems that there are some issues with react as well.

**Comment by tomitrescak** [comment]
[EDIT] There are even more issues as node does not resolve "jsx" files as these need to be specified explicityly as so `import "./component.jsx"` while Typescript preserves the extension "tsx". This is some messed up scenario I have: Typescript + React .. uff ;/

**Comment by ArtemGovorov** [comment]
@tomitrescak I'm putting a sample together. 

You don't need to specify the JSX extension in the `import`, just need to let node about how to load it:
```javascript
setup: function() {
      global.React = require("react");
      require.extensions['.jsx'] = require.extensions['.js'];
}
```

**Comment by ArtemGovorov** [comment]
What are you using `react` in node with, `jsdom`?

**Comment by tomitrescak** [comment]
@ArtemGovorov solution with compiling everything into temporary directory WORKS. So, if files and tests are run from Javascript files .. life is good.

Problem is that tests do not run from Typescript TSX files. Is there any way I can convince Wallaby to run tests from TSX? But, in any case, we have a working solution for now.

**Comment by ArtemGovorov** [comment]
> Problem is that tests do not run from Typescript TSX files.

Ok I think I have found something. Try NOT specifying the `jsx` value at all:
```javascript
    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "commonjs"})
    },
```

**Comment by tomitrescak** [comment]
Nope ;( Am getting `Postprocessor run failure: Failed to parse ..., SyntaxError: Unexpected token ...`

**Comment by ArtemGovorov** [comment]
Ok, thanks for checking, let me finish the sample and we will go from there.

**Comment by ArtemGovorov** [comment]
Ok, so here is the sample: https://github.com/wallabyjs/typescript-tsx-jsx

As you requested, it uses `enzyme`, so it's using a bit more code in the `setup` function, as suggested by [the `enzyme` docs](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md). Other than that, it's exactly your config + NOT specifying the `jsx` value at all like I've suggested.

Please try it and let me know how it goes.

**Comment by tomitrescak** [comment]
Hm. If I work only with compiler and get rid of the preprocessor with the babel plugin, all works just fine. It's the preprocessor that seems to break stuff.

**Comment by tomitrescak** [comment]
OK. let me check that repo.

**Comment by ArtemGovorov** [comment]
Actually I forgot to include some, just added the `If` tag statement: https://github.com/wallabyjs/typescript-tsx-jsx/commit/04a33606ec281f3c86c6d8d9bc4fc719103f0e10

**Comment by tomitrescak** [comment]
Artem ... loos good. But there is an error. The moment you define components in separate files, you will receive an error `Postprocessor run failure: Failed to parse src/client/modules/components/mycomponent/tests/test.js, SyntaxError: Unexpected token (7:47)`

```
import { shallow } from 'enzyme';
import { expect } from 'chai';
import MyComponent from "../mcomp";
import MyComponent2 from "../mcomp2"

describe('<MyComponent />', () => {

    it('renders children when passed in', () => {
        const wrapper = shallow(
            <MyComponent>
                <div className="unique" />
            </MyComponent>
        );
        expect(wrapper.contains(<div className="unique" />)).to.equal(true);
    });
});
```

MyComponent and MyComponent2 are the same file with a different name:

```
const MyComponent = React.createClass({
    propTypes: {
        children: React.PropTypes.element.isRequired
    },

    render: function() {
        return (
            <div>
                {this.props.children}
                <If condition={this.props.children.length}>
                    <span>IfBlock</span>
                </If>
            </div>
        );
    }

});

export default MyComponent;
```

**Comment by tomitrescak** [comment]
Here is a sample repo:

[Wallaby.zip](https://github.com/wallabyjs/public/files/181792/Wallaby.zip)

**Comment by ArtemGovorov** [comment]
Have updated the sample repo to demonstrate separate component files: https://github.com/wallabyjs/typescript-tsx-jsx. You need to add `target: "es6"` in this case, because otherwise TypeScript compiler doesn't produce a valid JSX code.

**Comment by ArtemGovorov** [comment]
Or just: 
```javascript
compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "es6"})
},
```

Your repo in the attached archive works if you uncomment the `preprocessors` and edit the `compilers` to be like I have mentioned above.

```javascript
    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "es6"})
    },
    preprocessors: {
      "**/*.js*": file => require("babel-core").transform(file.content, {
        sourceMap: true,
        // you may add the jsx-control-statements plugin instead
        presets: [ "es2015", "stage-2", "react" ],
        plugins: [ "jsx-control-statements" ]
      })
    },
```

**Comment by ArtemGovorov** [comment]
Regarding my "NOT specifying the `jsx` value at all" note: I found the bug in the core but it only shows up if some value is present. I have fixed it in the latest core v1.0.206. The core will be updated automatically in a few minutes after your next wallaby.js restart, to get the update ASAP, you may [force the core update](https://github.com/wallabyjs/public/issues/413#issuecomment-173174486).

Now with this fix and the fact that you have a working `tsconfig.json`, in the repo that you've attached in thearchive, you may do:
```javascript
    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript(
        require('./src/tsconfig').compilerOptions)
    },
    preprocessors: {...}
```
or, if you move the `tsconfig.json` file to your project root (where the `wallaby.js` file is), then wallaby.js will automatically find it, so you may remove the `compilers` section all together because wallaby.js will [automatically use the compiler with your `tsconfig.json` settings](http://wallabyjs.com/docs/integration/typescript.html):
```javascript
    preprocessors: {...}
```

**Comment by tomitrescak** [comment]
@ArtemGovorov just so know I am not a total idiot (but almost there) I had the preprocessors uncommented. Don't know why it was showing up in Atom as saved.

Anyways, everything works now. AMAZING! Thanks a lot, I really, really appreciate your help. I hope that the example that you put together will help others as well. Have a fantastic day!

**Comment by ArtemGovorov** [comment]
@tomitrescak Awesome, thanks for the update! I'll clean up the example and add it to our samples list in the docs.

**Comment by tomitrescak** [comment]
@ArtemGovorov one modification you need to do is to set the target to ES6, otherwise there is quite a mess when TS outputs to ES3 and babel is trying to use ES6 modules:

```
compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({target: "es6", module: "es6"})
    },
```

**Comment by tomitrescak** [comment]
@ArtemGovorov there is still something fishy with the configuration that we came up together. The imports for some reason do not work properly;(

Try this

```
// file A.ts
export default class A { }

// file B.ts
import A from "A.ts"
class B extends A { 
    constructor() {
         super();
    }
}

// test file
const {describe, it} = global;
import {expect} from "chai";
import B from "B.ts";

describe("something", () => {
  it ("detects correct user name", () => {
    let a = new A();
  });
});
```

you will get `_super.call is not a function error` ;(

if I define both classes in the same file all is good.

**Comment by tomitrescak** [comment]
Nevermind ... I got caugt on the erro of not putting "target:es6". It all works now.

**Comment by vjau** [comment]
Hi, 
i have been trying to do the same thing.
Like instructed, i have removed my babel compiler in wallaby.js and replaced it with a babel preprocessor, copying and pasting your provided code.
However, now my js code (not typescript) seems to not be babel converted by wallaby.
I get object.spread (stage 2) related error "unexpected token" when i run wallaby.

My wallay.js is like this :

```js
  return {
    files: [
      { pattern: 'client/**/tests/*.js', ignore: true },
      { pattern: 'server/**/tests/*.js', ignore: true },
      { pattern: 'imports/**/tests/*.js', ignore: true },
      'client/imports/modules/**/components/*.js',
      'client/imports/modules/**/composers/*.js',
      'client/imports/modules/**/actions/*.js',
      'client/imports/modules/**/containers/*.js',
      'client/imports/modules/**/libs/*.js',
      'client/imports/modules/**/processors/*.js',
      'client/imports/**/*.js',
      'client/imports/**/*.jsx',
      'imports/**/*.js',
      'client/imports/**/*.ts',
      'client/imports/**/*.tsx'
    ],
    tests: [
      'client/**/tests/*.js',
      'imports/**/tests/*.js'
    ],
    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript()
    },
    preprocessors: {
      '**/*.js': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, presets: ["es2015", "stage-2","react"]})
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    }
  };
```

Thank you in advance.

**Comment by vjau** [comment]
Also i'm using a tsconfig.json with jsx:preserve and target:es6

**Comment by ArtemGovorov** [comment]
@vjau looks like your preprocessor file pattern (`'**/*.js'`) is missing jsx files, try:
```javascript
preprocessors: {
      '**/*.js*': file => ...,
```

**Comment by vjau** [comment]
@ArtemGovorov  I don't think this is the problem, this is plain js files that do cause a problem.
I have done a PR demonstrating the problem on you example repo: 
https://github.com/wallabyjs/typescript-tsx-jsx/pull/1

**Comment by ArtemGovorov** [comment]
Thanks for the repo, sorry I didn't fully realise what was used in your scenario. For this case you also need to add [wallaby babel compiler for your `js*` files](https://github.com/wallabyjs/typescript-tsx-jsx/blob/master/wallaby.js#L19) (if you have a `.babelrc`, then you don't need to pass any options like I did in my commit).

**Comment by vjau** [comment]
Ok, does it mean that only files processed by the compiler goes through the preprocessing step ?

**Comment by ArtemGovorov** [comment]
@vjau Compiler runs first, then goes the preprocessing step. However, you may define some preprocessors for files that were not compiled by a compiler (for example for `*.html` files). In this specific case, it should actually work without a compiler, but wallaby parser (that works after a compiler, but before a preprocessor, doesn't yet support `stage-2` stuff, so a compiler comes to rescue). Hope it makes sense.

**Comment by vjau** [comment]
No sorry, i didn't get it.
If i don't use a compiler for plain js file, but a preprocessor with stage-2 presets, should'nt it work ?

**Comment by ArtemGovorov** [comment]
> If i don't use a compiler for plain js file, but a preprocessor with stage-2 presets, should'nt it work?

Yes, as I said, it should actually work without a compiler, but wallaby parser doesn't yet support stage-2 stuff. 

Wallaby parser participates in the code instrumentation. It needs to be able to parse your code to insert code coverage collecting instructions. The parser fully supports ES6/ES2015 *standard*, however [stage-2 is a *draft* stage](http://www.2ality.com/2015/11/tc39-process.html) of the feature proposal, and not yet supported by the parser.

When you're using a compiler, the parser is doing its work on the compiled code (ES5), so has no problem instrumenting it. If you use a preprocessor (without a compiler), then only *standard* ES2015 can be compiled.

Does it answer your question?
