### ISSUE TITLE
Cannot find node modules from jest

### ISSUE THREAD

**Issue by legofneb** [wallabyjs/public#524]
I've upgraded my current project to use jest version 0.9.2 and the test when run from jest work perfectly. However, when I use wallaby to run the tests I get errors from the HasteModuleLoader. Maybe an implementation in the HasteModuleLoader changed since the jest upgrade includes those changes. Here is the error message I get from wallaby's console: 

    Runtime error: Error: Cannot find module 'react-addons-test-utils' from 'TestUtils.js'
    at Loader._resolveNodeModule (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:431:11)
    at Loader._resolveModuleName (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:403:33)
    at Loader._getNormalizedModuleID (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:470:29)
    at Loader.requireModule (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:89:27)
    at Object.<anonymous> (.\Scripts\src\TestUtils\TestUtils.js:4:44)

and I get the same error for the 'flux' package. I am trying to use the unmocked versions of the packages. I'll try to reproduce this in another repo if I can this weekend.

### Wallaby.js configuration file

```javascript
var babel = require('babel-core');

process.env.BABEL_ENV = 'test';

module.exports = function (w) {

  return {
    files: [
      'Scripts/src/**/*.ts*',
      'Scripts/typings/**/*.ts',
      { pattern: '**/__tests__/*.ts*', ignore: true },
      '**/__mocks__/**',
      'jestGlobals.js',
    ],

    tests: [
      'Scripts/src/**/__tests__/*.ts', 'Scripts/src/**/__tests__/*.tsx'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    compilers: {
      'Scripts/src/**/*.ts*': w.compilers.typeScript({ typescript: require('typescript'), jsx: 2, module: 1 })
    },
    preprocessors: {
        'Scripts/src/**/*.js': file => babel.transform(
                                 file.content, 
                                 {sourceMap: true, presets: ['es2015', 'react'], plugins: ['jest-hoist', 'jest-unmock']})
    },

    bootstrap: function(wallaby) {
        wallaby.testFramework.configure({
            "unmockedModulePathPatterns": [
                "/node_modules/",
                "/flux/",
                "react-addons-test-utils",
                "react",
                "node_modules",
                  //"<rootDir>/node_modules/*",
                  //"react",
                  //"fbjs",
                  //"react-dom",
                  //"react-addons-test-utils",
                  //"babel",
                  //"core-js",
                  //"sinon",
                  "/TestUtils/",
                  //"<rootDir>/Scripts/src/TestUtils/*"
                ],
                "modulePathIgnorePatterns": [
                ],
                "setupTestFrameworkScriptFile": "<rootDir>/jestGlobals.js"
        });
    },

    debug: true

  };
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I have been able to reproduce a similar error (not exactly the same though) and have fixed it in the latest core v1.0.203 (will be updated automatically). Please try it and let me know how it goes.

**Comment by legofneb** [comment]
Thanks for the quick update! I tried running on 1.0.203 and am now receiving another error in wallabyjs:

    ​​​​​TypeError: t.test is not a function
    at Array.some (native)
    at Loader._execModule (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:277:25)
    at Loader.requireModule (C:\dev\node_modules\jest-cli\src\HasteModuleLoader\HasteModuleLoader.js:153:14)
    at Test.run (C:\dev\node_modules\jest-cli\src\Test.js:37:22)
    at C:\dev\node_modules\jest-cli\src\TestRunner.js:377:68

**Comment by ArtemGovorov** [comment]
@legofneb Thanks for checking. Can't reproduce `​​​​​TypeError: t.test is not a function` in any of my jest repos, may need a sample for this one.

**Comment by ArtemGovorov** [comment]
I also can't find any `t.test` usages in the `jest-cli` source code, so it may be your source code specific?

**Comment by ArtemGovorov** [comment]
Ok, I think I found something and fixed it in core v1.0.204, please try the new version and let me know how it goes.

BTW, are you using `scriptPreprocessor`? It seems like the error would only happen if you are. If so, what does your `scriptPreprocessor` do? I'm asking just in case to make sure it's not duplicating what's already done with wallaby `compilers` and `preprocessors` that you have configured.

**Comment by legofneb** [comment]
I'm using script preprocessor only when running the jest CLI, and I don't include it for wallaby. So I have the strangest problem now. When I copy and paste the files into a fresh project, it works perfectly! I just can't get it working in my working project for some reason. I keep encountering the same error as before, even when clearing my directory and checking it out from source control.

So I think it's probably a configuration problem I'm running into or something. It looks like wallaby is running correctly. I'll comment again if I can isolate the problem. Thanks!

**Comment by ArtemGovorov** [comment]
If it's wallaby related, then it sounds like some cache problem. Try changing your wallaby config (even a space will do), it should force wallaby cache to be cleaned.

**Comment by legofneb** [comment]
@ArtemGovorov, I was able to recreate the problem. It looks like it has something to do with the the packages I use in the project. Here is the [Jest Repo](https://github.com/legofneb/jest-0.9.2-repo). 

I run into the error when I use the wallaby-jest file to startup wallabyjs.

**Comment by ArtemGovorov** [comment]
@legofneb Thanks a lot for the repo! Fixed the issue in the latest core v1.0.205.

**Comment by creaux** [comment]
Hi, I just updated everything (downloaded latest version from your website) and following error occurs. Using version `1.0.53` for WebStorm.

```
jest-cli node module is not found, missing `npm install jest-cli --save-dev`?
```

Configuration is following:

```javascript
module.exports = function() {
    return {
        "files": ['source.js'],

        "tests": ["test.js"],

        env: {
            type: 'node',
            runner: 'node'
        },

        "testFramework": "jest",

    }
};
```

Any idea?

**Comment by ArtemGovorov** [comment]
@creaux Try installing jest@0.9, jest 0.10.x is not yet supported.

**Comment by ArtemGovorov** [comment]
@creaux I have added jest-cli@0.10 experimental support to wallaby core v1.0.211. You may restart your IDE and start wallaby to get the core updated. Once updated, it should work with the latest jest-cli.

**Comment by dsifford** [comment]
A similar issue just started happening for me within the last 3 hours.. Earlier this morning everything was working fine. 

I made no changes, so I can only assume this is the result of an update?

**Comment by ArtemGovorov** [comment]
> A similar issue just started happening for me within the last 3 hours

There're a couple of different issues discussed here, what issue/error message are you getting and what version of the `jest-cli` do you have installed?

**Comment by dsifford** [comment]
Whoops, sorry!

I have `moment` and `sinon` installed and I'm importing it like so...

```ts
// DashboardUtils-test.ts
jest.unmock('../DashboardUtils');
jest.unmock('moment');

import * as utils from '../DashboardUtils';
import * as sinon from 'sinon';
import * as Moment from 'moment';

// ..... tests
```

And both sinon and moment are not being found.

Message: `Error: cannot find module 'moment' from 'DashboardUtils-test.js`

While typing the message out, I just realized that the extension it's using a `.js` when it's actually a TypeScript file. Odd.

> what version of the jest-cli do you have installed?

```sh
$ jest --version
v12.1.1
```
