### ISSUE TITLE
Could not find module error

### ISSUE THREAD

**Issue by cheslip** [wallabyjs/public#529]
### Issue description or question

I keep getting a `Cannot find module` error every time I try and run wallaby. I'm using typescript with webpack and have posted the config file below. I've noticed that when the ts files get compiled in the cache directory, the compiled files look like `<filename>.ts.compiled.js` and the compiled test files are still trying to `require('../<filename>');`.

Is the `.compiled.js` suffix interfering with webpack module loading?

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({});

module.exports = function () {

  return {
    files: [
      { pattern: 'src/*.ts', load: false }
    ],

    tests: [
      { pattern: 'test/*.spec.ts', load: false }
    ],

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> Is the `.compiled.js` suffix interfering with webpack module loading

Thanks for the checking compiled files, it is indeed interfering with webpack compilation.
What happens here is that by default wallaby.js tries to find the `tsconfig.json` file (in the same folder where the wallaby.js config file is) and if it can can't find it, or if it can but no `module` option is specified in the file `compilerOptions`, then it adds the `.compiled.js` suffix.

When webpack is used, your code is expected to be compiled in CommonJs, so you need to specify `"module": "commonjs",` in your `tsconfig.json` file if you have one. If you don't, then you may add [compilers section](http://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) to your wallaby config to be able to pass any compiler settings (they'll override `tsconfig.json`):

```javascript
...
module.exports = function (wallaby) {
  return {
    files: [...],

    tests: [...],
    ...
    postprocessor: ...,
    bootstrap: ...,

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        module: 'commonjs'
      })
    }
  };
};
```

**Comment by cheslip** [comment]
Thanks for the great explanation, that works!
