### ISSUE TITLE
Longer, windowed, or export console.log

### ISSUE THREAD

**Issue by johnvnguyen** [wallabyjs/public#531]
Sorry I don't know how to add an enhancement tag. It is also a question.
I like how console log shows the variables of a class. For example, if I console.log(console),
I get '{ log: [Function], warn: [Function]...'

There are times when the object is declared as an <Any> type and so I cannot have auto completion to assist me, and so I rely on console.log and Wallaby. However, sometimes I cannot find help because the line is too short to show everything. Sometimes, if it is a string type, I can throw the string and look at the console for an answer. I use that method when I wan't to the the rendered HTML.

I  am hoping for a way to display than just that short view strings. I realize I can go to Wallaby's console, but there are thousands of lines of output.

What would you recommend me do, or can you do anything to help please?

Visual Studio 2015
Windows 10

**Comment by ArtemGovorov** [comment]
Good question.

I'd recommend using [`Show line tests` smart action](http://wallabyjs.com/docs/intro/get-started-vs.html#smart-actions) for the line with `console.log` to quickly see the full logged output.

You may either invoke the action for the line where you have `console.log` by clicking a coverage indicator (coloured square next to the line in the editor gutter) or by using `Alt + Shift + F10` + the smart action selection (or you may assign any keyboard shortcut to the action in your Keyboard settings).

The action displayed all the data related to the executed code line, including the full console output, that you may even search with `Ctrl + F`.

![peek_view 1](https://cloud.githubusercontent.com/assets/979966/14056964/2db9a072-f33f-11e5-85f1-3acfe936b611.png)

Hope it answers your question.
