### ISSUE TITLE
Support tape and karma-tap

### ISSUE THREAD

**Issue by wpannell** [wallabyjs/public#532]
[tape](https://github.com/substack/tape) and
[karma-tap](https://github.com/tmcw-up-for-adoption/karma-tap)

This is a feature request.  Arrived here by your [request](http://wallabyjs.com/docs/intro/get-started-jetbrains.html).

**Comment by ArtemGovorov** [comment]
Thanks for the request. Please subscribe to this one: https://github.com/wallabyjs/public/issues/2
