### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by Robert923** [wallabyjs/public#535]
### Issue description or question

[Git repo with issue reproduced.](https://github.com/Robert923/WallabyReadPropertyBug)

Everything works fine when Wallaby is first started and all the unit tests pass.

However, if you make **_any_** change to domainLogicTests.ts
(say, press space on an empty line) then the unit test will instantly fail
with the following error:

	Cannot read property '1' of undefined
		at test/mockInterfaceImpl.ts:14
		at lib/domainLogic.ts:29
		at test/domainLogicTests.ts:38

The unit tests work just fine in Mocha from the command line, even with 'mocha --watch'.

### Wallaby.js configuration file

    // See: http://wallabyjs.com/docs/config/overview.html
    // See: http://wallabyjs.com/docs/intro/config.html
    // and  http://wallabyjs.com/docs/config/files.html
    module.exports = function (wallaby) {
        return {
            'files': [
                'lib/**/*.ts'
            ],

            'tests': [
                'test/*.ts',
                'test/**/*.ts'
            ],

            'testFramework': 'mocha',

            // http://wallabyjs.com/docs/integration/typescript.html
            compilers: {
                '**/*.ts': wallaby.compilers.typeScript({
                    module: 5,  // 1 for CommonJs, 5 for ES6
                    target: 2,  // ES6
                    typescript: require('typescript')   // use Node typescript version
                })
            },

            // Allow TypeScript to ES6, and then Babel to ES5:
            // From https://github.com/wallabyjs/public/issues/355#issuecomment-159764077
            preprocessors: {
                '**/*.js':
                    (file) =>
                        require('babel-core').transform(file.content, { sourceMap: true, presets: ['es2015'] } )
            },

            env: {
                type : 'node',
                runner: 'node'
            },
            
            // I added this after reading through your troubleshooting guide - made no difference
            workers: {
                initial: 1,
                regular: 1,
                recycle: true
            }
        };
    };

### Code editor or IDE name and version
WebStorm 2016 or 2016.1  
  or  
Visual Studio Code v0.10.11

### OS name and version
Windows 10 - Version 1511 - OS Build 10586.164
(two different computers - but both with similar configuration)

**Comment by ArtemGovorov** [comment]
Thanks for repo!
Have sent you the pull request https://github.com/Robert923/WallabyReadPropertyBug/pull/1.
[Only test files](http://wallabyjs.com/docs/config/files.html#tests) should be in the `tests` list, so I have the pattern `'test/**/*Tests.ts'` in your `tests` list and included the rest (`mockInterfaceImpl` in your case) to the `files` list by adding `'test/*.ts',` and excluding the used tests pattern: `'!test/**/*Tests.ts'` (I have used an exclamation mark, but you may use [the full file pattern object](http://wallabyjs.com/docs/config/files.html#file-object) if you like).

**Comment by ArtemGovorov** [comment]
P.S. you may also remove the `workers` section, as node caching or tests order is definitely not the issue in this case.

**Comment by ArtemGovorov** [comment]
Also, because you have a `tsconfig.json` [that wallaby.js may use by default to configure your TypeScript compiler](http://wallabyjs.com/docs/integration/typescript.html), you may remove the `compilers` section. And (for node.js environment) `mocha` is the default testing framework value, so if you like you may remove `'testFramework': 'mocha',` as well.

**Comment by Robert923** [comment]
Wow!  That's fantastic!  Thanks for the fast turn around Artem!  :-)
