### ISSUE TITLE
Debugging test with vscode

### ISSUE THREAD

**Issue by mtrivolli** [wallabyjs/public#537]
### Debugging in vs code
I wonder if there is a recommended way to debug tests using wallaby and vs code. I'm finding myself using wallaby to rapidly launch tests but then using karma plus chrome debugging capabilities to debug failed tests. 

Thanks in advance

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
@mtrivolli There's currently no debugger support in wallaby.js, you may subscribed to the feature request to get notified about the progress - https://github.com/wallabyjs/public/issues/74.
I understand that what I'm about to suggest is not really a replacement of a full debugger, but in many simple cases, when wallaby is running I use `console.log(...)` + the realtime feedback wallaby provides for it to quickly see what some values are right in the editor.
