### ISSUE TITLE
Visual Studio 2015, display of console.log to the right in the editor

### ISSUE THREAD

**Issue by jkennerley** [wallabyjs/public#538]
### Issue description or question
Display of console.log can be very laggy. 
In the example below, the console.log did not appear for several minutes and lots of attempts at adding/deleting spaces. 

I am not complaining, probably this fails 1 in a 1000.
Or perhaps it is due to the variable 'p' not being declared 'var p' ...

### Wallaby.js configuration file
module.exports = function (wallaby) {

var cfg = {
    files: [
        {
            "pattern": "Jsts/wwwroot/lib/chai/chai.js",
            "instrument": false
        },
        {
            "pattern": "Jsts/wwwroot/js/*.js"
        }
    ],
    tests: [
        'Jsts.UnitTest/**/*TestMocha.js',
        'Jsts.UnitTest/**/*TestMocha.ts'
    ],
    "debug": false,
    "testFramework": "mocha"
    };

return cfg;

};

```javascript
       it("console.log", function () {
        //// when a var is not initialised, then will be set to undefined
        //p = "DISPLAYS IN EDITOR";
        //console.log(p);
        // when a var is not initialised, then will be set to undefined
        //p = "DOES NOT DISPLAY IN EDITOR";
        //console.log(p);

        // when a var is not initialised, then will be set to undefined
        p = "DOES NOT DISPLAY IN EDITOR";
        console.log(p);
    });

```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version
Windows 10

![walloby_issue](https://cloud.githubusercontent.com/assets/5923377/14174545/fa2224b2-f73c-11e5-8b3d-e387bdb60ff4.PNG)

and then several minutes and several small chnages later ...

![walloby_issue_no_you_see_it](https://cloud.githubusercontent.com/assets/5923377/14174617/70efa696-f73d-11e5-913c-456e4b1f02c4.PNG)

**Comment by ArtemGovorov** [comment]
Is the variable `p` also set from somewhere else? Like other tests/code? Does it always work with `var p = ''` for you? Did I understand it correctly that it normally works and only fails to display vary rarely?

**Comment by ArtemGovorov** [comment]
We have just checked the sample and it works for me in VS 2015: http://recordit.co/saVyFE2Ibl, is there anything I should do differently to reproduce it?

**Comment by jkennerley** [comment]
Not sure, I could not always reproduce it either.  I rebooted my machine and the lagginess of the display of the grey console text went away i.e. it quickly displayed the grey text. Before the reboot, persistently stop/starting walloby still had the effect of  extreme lagginess of display of the grey console text.  To be honest, I have the feeling you will find it almost impossible to repeat because right this second I cannot repeat it either. I hate to say switch-it-on-and-off-again solves the issue since there must be a reason for it.  It may well caused by something in the guts of VS rather than walloby, but there may may well be some optimisations for walloby. I thought perhaps it was the non declaration of the pa var, but obviously it is not.

**Comment by jkennerley** [comment]
I can see you screen cast working.  Currently I cannot reproduce it either. Perhaps you should close this issue I am sure you may be reviewing walloby perf.

**Comment by jkennerley** [comment]
Thank you for your extremely quick response on the issue. I think perhaps you may close it.

**Comment by ArtemGovorov** [comment]
Thanks for the update. Hopefully it was just a performance of VS itself. Let me know if it shows up again.

**Comment by jkennerley** [comment]
Can you reopen this, managed to demo the lagginess on my machine.

http://recordit.co/e7Ql3v4aG9

You can see  toggling of the value of x to 0 or 1.

I set x to 0, and TRUTHY is still displayed !
Then I restart walloby and TRUTHY is not displayed, TICK
Setting x back to 1, causes TRUTHY to be displayed, TICK. 
Setting x to 0 and TRUTHY is still displayed, !.
Restarting Walloby, causes TRUTHY to be undissplayed, TICK.




    it("comparisons", function () {
        var T = "TRUTHY";
        //var x = 1;// should show TRUTHY
        var x = 0;// should not be truthy
        if (x == 1) { console.log(T) };
    });

**Comment by ArtemGovorov** [comment]
Thanks for the video. It is not lagginess, it's just displaying the latest captured `console.log` value. It has always been like this and it's by design. Note that it correctly updates coverage indicator notifying that the `console.log` statement wasn't invoked.
To prove that it is not lagginess: if you I set x to 0, and `TRUTHY` is still displayed, then no matter how long you wait, the `TRUTHY` will be displayed. If you keep editing code however, then some code editing actions may remove it though (for example commenting/uncommenting the line and few other actions affecting the region).

**Comment by jkennerley** [comment]
OK, got it, it was displaying last console.log() and I was not forcing the change that console.log(), I needed an else for that.
I understand the tool and its behaviour a little better.
