### ISSUE TITLE
Runtime error: ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by joeycozza** [wallabyjs/public#54]
Runtime error: ReferenceError: Can't find variable: require

I'm quite sure this is just a configuration problem, but Wallaby is complaining about not knowing what "require" and "module" from all of my  ```var foo = require('bar')``` and  ```module.exports = {};``` statements.

Is there a particular setting I need to check in IntelliJ to expose those global node variables for wallaby?

Through IntelliJ I can command-click into the global variable ```require```and ```module``` and it takes me to a file located in JodeJS.jar/com/jetbrains/nodejs/library/node-globals-stub.js

I can't find any help with this issue through the documentation, so any guidance would really be appreciated. Thanks.

**Comment by ArtemGovorov** [comment]
Assuming that you are running node.js tests, maybe you are missing [`env` setting](https://github.com/wallabyjs/public#environment-setting)?

**Comment by joeycozza** [comment]
Dang, I can't believe I missed that part of the docs. Thanks for pointing it out to me. That seems to be working fine now.
