### ISSUE TITLE
TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')

### ISSUE THREAD

**Issue by mwq27** [wallabyjs/public#542]
### Issue description or question
I get this `TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')` error when I start up wallaby.
Full error:
```
TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')
at http://localhost:58857/__modules/38.js?1459558607590:38


TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')
	at src/client/app.spec.ts:6
```
### Wallaby.js configuration file

```javascript
'use strict';
var wallabyWebpack = require('wallaby-webpack');
var webpackPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {

	return {
		files: [
			{ pattern: 'src/**/!(*.spec|*.e2e).ts', load: false }
		],

		tests: [
			{ pattern: 'src/**/*.spec.ts', load: false }
		],

		postprocessor: webpackPostprocessor,

		bootstrap: function () {
			window.__moduleBundler.loadTests();
		}
	};
};

```

### Code editor or IDE name and version

WebStorm v11 2016.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
PhantomJs (that wallaby is using by default), doesn't support ES6 `Map`, so a polyfill needs to be included. 
```
npm install babel-polyfill --save-dev
```
+
```javascript
module.exports = function (wallaby) {

    return {
        files: [
            { pattern: 'node_modules/babel-polyfill/browser.js', instrument: false},
            { pattern: 'src/**/!(*.spec|*.e2e).ts', load: false }
        ],
```
Alternatively, you may switch to [Electron as your test runner](http://wallabyjs.com/docs/integration/electron.html), wallaby supports it and Electron does support `Map` without a polyfill.

Let me know if it helps.

**Comment by mwq27** [comment]
Yep that fixed it, thank you :)

Only thing now is in my src code where the test is failing/passing, I don't see the little block in the gutter.  Is there another setting I need for that?

**Comment by ArtemGovorov** [comment]
> I don't see the little block in the gutter. Is there another setting I need for that?

There's not special setting, everything from your `files` and `tests` patterns should have some indicators when a test run is finished (at least grey ones). If by the end of a test run your tests and source files don't have the indicators, most likely they didn't match the patterns. 

To make sure that it's the project/config specific issue (and not something else), could you please try running wallaby in this sample project - https://github.com/wallabyjs/calculator-sample to see if the indicators are displayed for you there?

**Comment by mwq27** [comment]
In the calculator-sample, I do see all of the blocks in the gutter.  In my own app, the only block I see in my source code is a grey block, I guess I was hoping to see more green blocks.  Maybe the tests just aren't covering enough though.

**Comment by ArtemGovorov** [comment]
You should see lots of green block in your test files. Could you please check if there are lots of green block in your test files?

**Comment by ArtemGovorov** [comment]
There may be some other issue why you only see grey blocks in your source code. Wallaby.js using its own file cache to execute your tests/code, where it has all the instrumented files. However, sometimes webpack may be configured to point to your local project, so the local project files are used instead of the instrumented ones, so no coverage is collected.

See [this docs section](http://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) for more details, and if there are some places in your webpack config that may point to your local project, try pointing them to the wallaby cache like described in the docs.

**Comment by ArtemGovorov** [comment]
I close this one as the original issue is resolved, but please feel free to create a new one for the missing coverage if you find it to be an issue. Please also attach your webpack config to the new issue (if it turns out to be one).

**Comment by Feytality** [comment]
I just want to thank you @ArtemGovorov ! This problem was driving me crazy! :smile:
