### ISSUE TITLE
Wallaby.js docker support

### ISSUE THREAD

**Issue by jmartin84** [wallabyjs/public#543]
Hi, I'm wondering if wallaby.js has any support for applications running in docker containers?  Thank you for your time.

**Comment by ArtemGovorov** [comment]
At this stage wallaby.js starts its node.js core locally right from an IDE/editor, so there's not support for docker container. Having said that, wallaby.js may run your tests on pretty much any platform where you code editor can run, so an alternative for now may be to just run your tests locally (if possible).

**Comment by jasdf2351** [comment]
I know +1 comments are frowned upon, but this ticket is a bit old so thought I'd give it a bump.
@ArtemGovorov is this support likely to be on the roadmap anytime soon-ish?

**Comment by smcenlly** [comment]
If you're using VS Code, then [VS Code Remote Containers](https://code.visualstudio.com/docs/remote/containers) may help. We tested when it was initially released and it worked. The only caveat was that you must install your wallaby license for each container that you use.

**Comment by miking-the-viking** [comment]
Thanks @smcenlly ! That's what I used to get up and running... Me slice'n'dicing wasn't quite bang on apparently. The use of the `node` user was key to making it work for me. Thanks for making that sample! It was a lifesaver!

**Comment by smcenlly** [comment]
I believe we can close this issue. Wallaby can be run in containers provided the editor supports them. For example: https://code.visualstudio.com/docs/remote/containers.
