### ISSUE TITLE
Webpack + TypeScript and Aurelia

### ISSUE THREAD

**Issue by Vheissu** [wallabyjs/public#544]
### Issue description or question
I am trying to get Wallaby working with Webpack + TypeScript using the Aurelia Javascript framework. 

The current console output I am seeing is:

``` shell
ts-loader: Using typescript@1.8.9 and C:\Sites\myApp\Client\Client.Application\Reporting\tsconfig.json
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Runtime error: ReferenceError: Can't find variable: Map
at http://localhost:39354/__modules/4.js?1459732962524:51
Runtime error: ReferenceError: Can't find variable: Map
Finished executing 1 affected test(s)
```

I have tried using the examples from the official documentation and other working examples of Webpack usage to no avail.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');

var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'test/unit/setup.ts', load: false}
        ],
        tests: [
            {pattern: 'test/unit/**/*.spec.ts', load: false}
        ],

        postprocessor: wallabyPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

### Code editor or IDE name and version

WebStorm 2016.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the log and the config!

So there are 3 issues I can see in the setup
1) `Runtime error: ReferenceError: Can't find variable: Map`. Can be fixed as described here: https://github.com/wallabyjs/public/issues/542#issuecomment-204622357
2) `ts-loader: Using typescript@1.8.9...`. Looks like webpack is configured to use `ts-loader` and [wallaby.js needs it to be removed](http://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript) because it uses its own TypeScript compiler. Depending on how your `webpack.config` looks like, it may be possible to just do:
```javascript
 var webpackConfig = require('./webpack.config');
 ...
  webpackConfig.module.loaders = webpackConfig.module.loaders.filter(function(l){
    return l.loader !== '...';
  });
```
in the wallaby config.
3) If I understand correctly, `test/unit/setup.ts` contains some setup logic has to be executed before any tests. If that's the case, then you'll need to specify the file as one of the [entry patterns](http://wallabyjs.com/docs/integration/webpack.html#entry-patterns) (note that it'll be compiled, so you'll need to use `.js` extension for the entry patterns).
```javascript
 var webpackConfig = require('./webpack.config');
 ...
  webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/unit/**/*.spec.js'];
```

Try fixing these and let me know how it goes.

**Comment by Vheissu** [comment]
@ArtemGovorov Thank you for the awesome and amazing support. Getting that Wallaby licence was one of the best things I have done so far this year. This fixes the issues you mentioned.

For anyone else who comes across this issue, this is my Wallaby file:

``` javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');

var wallabyPostprocessor = wallabyWebpack({});

webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/unit/**/*.spec.js'];

module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'node_modules/babel-polyfill/browser.js', instrument: false},
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'test/unit/setup.ts', load: false}
        ],
        tests: [
            {pattern: 'test/unit/**/*.spec.ts', load: false}
        ],

        postprocessor: wallabyPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
@Vheissu Awesome, thanks for the update!

**Comment by Vheissu** [comment]
@ArtemGovorov Further note. Also looks like the line ``webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/unit/**/*.spec.js'];`` is not needed either. It works without that. Thanks again, you're great.

**Comment by ArtemGovorov** [comment]
> Also looks like the line `webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/unit/**/*.spec.js'];` is not needed either

Hmm, then perhaps I was wrong saying that "`test/unit/setup.ts` contains some setup logic has to be executed before any tests". Or maybe you `import` the file from all of your tests files?
