### ISSUE TITLE
Wallaby task not running after upgrading to Idea 2016.1

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#545]
### Issue description or question

After upgrading to 2016.1 I see following message when trying to run my configuration in Idea:

![2016-04-04 at 15 33](https://cloud.githubusercontent.com/assets/11071/14249609/da00f03c-fa7a-11e5-8158-3674cbf27a1c.png)

### Code editor or IDE name and version

IntelliJ IDEA v2016.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
There is no node file in that location, is there?
Will try to reproduce it. In a meantime, you may just point it to any node executable installed in your system.

**Comment by okonet** [comment]
Right. I pointed to my node location but was wondering if the migration should be handled more smoothly  on your or JetBrains side. Feel free to close if it's out of scope.

**Comment by ArtemGovorov** [comment]
Thanks for reporting it. The issue was in wallaby and is fixed in the latest IntelliJ plugin (v1.0.55).
