### ISSUE TITLE
Wallaby not recognising files from the parent directory

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#548]
In my setup I need to keep wallaby config along with development modules in the separate directory. Yet wallaby s not detecting files from the parent directory. E.g:

```
tests: [
      "../test/*.ts",
    ],
```

This will not find tests in the parent directory. Is this a feature?

**Comment by ArtemGovorov** [comment]
This is not supported in wallaby, see the feature request: https://github.com/wallabyjs/public/issues/68
