### ISSUE TITLE
ES6 import syntax not working when using `export default`

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#55]
When using `export default` in the source file, wallaby does not import the module.

Example:

```
export default class Person {
  constructor(name) {
    this.name = name;
  }
}
```

Test:

```
import Person from '../src/Person';

var chai = require('chai');
var expect = chai.expect;

describe('Person', () => {
  it('should report name', () => {
    expect(new Person('John').name).to.equal('John');
  });
});
```

`Person` will be `undefined`. It works when `default` is removed from source.

Initially reported here: https://github.com/jeffling/wallaby-webpack/issues/7

**Comment by ArtemGovorov** [comment]
I'm not sure that it is a wallaby issue.

Babel transforms 
`export default class Person`
to
`module.exports = Person;`
and 
`import Person from '../src/Person';`
to
`var Person = require("../src/Person").Person;`
and as require("../src/Person") already is a Person function, accessing Person property of it returns undefined.

BTW, changing `import Person from '../src/Person';` to `import { default as Person } from '../src/Person';` works.

**Comment by ArtemGovorov** [comment]
Actually, it may be a wallaby issue, I will investigate more.

**Comment by ArtemGovorov** [comment]
Yep, confirmed, it is a wallaby issue. Wallaby for some reason incorrectly transforms `import Person from '../src/Person';` to `import { Person } from '../src/Person';` when instrumenting the code, then babel transforms it to `var Person = require("../src/Person").Person;`.

**Comment by okonet** [comment]
Yes, exactly. I was wondering why it is doing so with debug mode recently...

**Comment by ArtemGovorov** [comment]
If it still shows 'Person undefined', it may be a caching issue. To clear the cache just change your wallaby config (even add a space to it somewhere) and re-run wallaby.

**Comment by mrasoahaingo** [comment]
Oh I got the same issue, event though wallaby plugin is disabled, I still have 2 files that was included inside the wallaby.js before wich cannot find the default export when importing...
```javascript
import chai from 'chai'
```
this code is marked as error on my IDE but is syntactically correct

**Comment by ArtemGovorov** [comment]
> wallaby plugin is disabled

Do I understand correctly that it's not wallaby.js issue but the IDE issue?

> It says on chai variable: "Default export is not declated on imported module"

Is this message from wallaby or from IDE syntax analyzer? Could you please attach a screenshot?

**Comment by mrasoahaingo** [comment]
@ArtemGovorov 
It's just the IDE syntax analyzer :/

<img width="564" alt="screen shot 2016-01-29 at 00 16 41" src="https://cloud.githubusercontent.com/assets/12088397/12662014/bc05609a-c61d-11e5-9668-14f6f22af7a4.png">

**Comment by ArtemGovorov** [comment]
@mrasoahaingo Ok, thanks for the update, you may raise the issue at https://youtrack.jetbrains.com/issues
