### ISSUE TITLE
coverage report in file/directory?

### ISSUE THREAD

**Issue by Kosta-Github** [wallabyjs/public#551]
### Issue description or question
Maybe I just missed that, but is it possible to dump out the coverage report into a file or folder (similar to `istanbul` or `isparta`)?

I would like to integrate code coverage into a CI environment, but `istanbul` and `isparta` don't produce useful results for the more advanced features of `ES6` and `ES7`; maybe `wallabyjs` could be used instead?

**Comment by ArtemGovorov** [comment]
Wallaby collects the coverage for ES6/ES7 (you may use coverage indicators), but we don't yet support an overall report with coverage metrics. Feel free to subscribe to the feature request - https://github.com/wallabyjs/public/issues/38
