### ISSUE TITLE
Runtime error: ReferenceError: $_$wp is not defined

### ISSUE THREAD

**Issue by timReynolds** [wallabyjs/public#553]
### Issue description or question

I've just updated the packages my project depends on and am now getting the following warning;
![image](https://cloud.githubusercontent.com/assets/168870/14487483/b1a8d8ca-015a-11e6-9df8-2985498b40c3.png) 

Not taking the latest version of babel is due to issues in Jest with mocking es6 modules when using the built in support of babel-jest.

This seems to be caused by the following code which is used in the setupEnvScriptFile file hook for Jest;
![image](https://cloud.githubusercontent.com/assets/168870/14487516/e58b8a5c-015a-11e6-9d64-806325992b80.png)

However removing the code from this file still gives me the same error. Running the test via jest (npm run test) passes. 

### Wallaby.js configuration file

```javascript
var babel = require('babel');

module.exports = function (wallaby) {
    var wallabyBabelCompiler = wallaby.compilers.babel({
        babel: babel,
        stage: 0
    });

    return {
        debug: true,
        files: [
            'jest-setupEnvScriptFile.js',
            'jest-setupTestFrameworkScriptFile.js',
            'package.json',
            'src/**/*.js',
            '!src/**/__tests__/*.js'
        ],
        tests: [
            '__tests__/**/*.js',
            'src/**/__tests__/*.js'
        ],
        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony'
            }
        },
        compilers: {
            'src/**/*.js*': wallabyBabelCompiler
        },
        workers: {
            initial: 10,
            regular: 5
        },
        testFramework: 'jest',
        bootstrap: function (wallaby) {
            var config = require('./package.json').jest;
            wallaby.testFramework.configure(config);
        }
    };
};
```

### Jest configuration 
```
"jest": {
    "setupEnvScriptFile": "jest-setupEnvScriptFile.js",
    "scriptPreprocessor": "jest-scriptPreprocessor.js",
    "testRunner": "jasmine2",
    "testFileExtensions": [
      "js"
    ],
    "moduleFileExtensions": [
      "js",
      "json"
    ],
    "unmockedModulePathPatterns": [
      "/node_modules/react",
      "/node_modules/fbjs",
      "/node_modules/fbjs/lib/keyMirror",
      "/node_modules/react-dom",
      "/node_modules/react-addons-test-utils",
      "/node_modules/lodash",
      "/node_modules/ramda",
      "/node_modules/object-assign",
      "/node_modules/moment",
      "/node_modules/validate.js",
      "/node_modules/enzyme",
      "/node_modules/cheerio",
      "/node_modules/htmlparser2",
      "/node_modules/underscore",
      "/node_modules/domhandler",
      "/node_modules/object.assign",
      "/node_modules/define-properties",
      "/node_modules/function-bind",
      "/node_modules/object-keys",
      "/node_modules/object.values",
      "/node_modules/es-abstract",
      "/node_modules/dom-helpers"
    ]
  }
```

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
Windows

### Wallaby Core Version
wallaby.js core v1.0.213

### Example 
I've managed to replicate this in a small example project;
[WallabyTestSetup](https://github.com/timReynolds/WallabyTestSetupPF)

**Comment by ArtemGovorov** [comment]
Assuming that you probably don't need to track code coverage for setup files, try setting the [`instrument: false` flag](https://wallabyjs.com/docs/config/files.html#file-object) for them by changing your files like this:
```javascript
files: [
            {pattern: 'jest-setupEnvScriptFile.js', instrument: false},
            {pattern: 'jest-setupTestFrameworkScriptFile.js', instrument: false},
            ...
```

**Comment by timReynolds** [comment]
You're right I'm not interested in code coverage for those files and changing the instrument setting gets round the issue. 

However I'm now seeing the following issue with Jest;
```
TypeError: Cannot read property '_jasmineAdapter' of undefined
    at Runtime._execModule (C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-cli\src\Runtime\Runtime.js:305:17)
    at Runtime.requireModule (C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-cli\src\Runtime\Runtime.js:152:14)
    at C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-jasmine2\src\index.js:43:20
    at FakeTimers.runWithRealTimers (C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-util\lib\FakeTimers.js:262:7)
    at jasmine2 (C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-jasmine2\src\index.js:30:26)
    at Test.run (C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-cli\src\Test.js:42:12)
    at C:\Source\PremiumFinance\Dev\PF\PF.Presentation.Ui\js\node_modules\jest-cli\src\TestRunner.js:383:68
```

I know jest has made a lot of changes in the last few versions and now has packages for each running e.g. `jest-jasmine2`; 
![image](https://cloud.githubusercontent.com/assets/168870/14489205/c3612d3e-0163-11e6-809f-e5a4c2165c0d.png)

**Comment by ArtemGovorov** [comment]
Thanks for the note. I'm trying to track their changes, but sometimes they move too much stuff around and I have to add the new version specific changes.

This time it was a small breaking change between Jest v.0.10.x and Jest 11.0.0. The support for Jest 11.0.0 (at least this issue fix) is added the core v1.0.214 (restart your IDE and start wallaby to get the update immediately). Let me know how it goes.

**Comment by ArtemGovorov** [comment]
BTW, the originally reported issue and the new one (after setting `instrument: false`) are essentially the same issue related to the Jest 11 breaking changes.

**Comment by timReynolds** [comment]
Have confirmed the latest version fixes both of the above issues.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
