### ISSUE TITLE
systemjs and jspm support

### ISSUE THREAD

**Issue by Frizi** [wallabyjs/public#56]
Hello,
I'm trying to test my es6 modules with wallaby. I'm using [jspm](http://jspm.io/) for es6 modules loading in the browser.  Unfortunately, simple babel preprocessing (as in docs) is not enough for wallaby.js. I'm getting a lot of missing module errors.

I want to test my "View" module, so I put the import in the view.spec.js like this
```javascript
import {View} from 'view/View';
```

Which basically generates error.
I'm aware that i can use requirejs for that, but then the whole environment of jspm modules is lost, which prevents loading of external libraries like lodash.

I found a way to do this with Karma runner via [karma-jspm](https://github.com/Workiva/karma-jspm), but i have no idea how to implement something like this for wallaby. Any ideas?

**Comment by ArtemGovorov** [comment]
Hi,
I have added jspm support, have a look into this sample - https://github.com/wallabyjs/wallaby-jspm-sample

**Comment by Frizi** [comment]
Hey, Thank You! Will test it later today.
