### ISSUE TITLE
Code coverage not works with babel.js paths option

### ISSUE THREAD

**Issue by subuta** [wallabyjs/public#560]
### Issue description or question
i'm trying to use wallaby.js with browserify & babel.js based on [example.](https://github.com/subuta/wallaby-browserify-sample)

example runs fine, but when I use custom NODE_PATH(via babel.js paths option)
for requiring module, code coverage not works correctly(colored as gray, even corresponding test case shows okay(green color)). 
how can i get this working correctly?

[forked repository]
https://github.com/subuta/wallaby-browserify-sample

### Wallaby.js configuration file

```javascript
var wallabyPostprocessor = wallabify({ paths: ['src'] });
```

### In spec file.
```javascript
// good(from original wallaby-browserify-sample)
var Person = require('../src/Person');

// bad(test runs fine, but no coverage shown ...)
var Person = require('Person');
```

### Code editor or IDE name and version
WebStorm 2016.1.1

### OS name and version
OSX Yosemite 10.10.5

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

Wallaby.js is using its own cache to run tests (it keeps instrumented source files there). When just a relative `src` path is specified, browserify uses files from your local project folder. They are not instrumented, so no coverage is reported and everything is grey. 

We juts need to point browserify to the wallaby cache folder for the project. We may use [`wallaby.projectCacheFolder`](https://wallabyjs.com/docs/config/overview.html) value for it. I have submitted [the pull request](https://github.com/subuta/wallaby-browserify-sample/pull/1) that should make it work.

Let me know if this works for you.

**Comment by subuta** [comment]
@ArtemGovorov thanks for quick reply and PR :)

your advice works like a charm!
i will close this issue. Thank you very much for your time!

**Comment by ArtemGovorov** [comment]
@subuta Awesome, thanks for the update!
