### ISSUE TITLE
Can't run wallaby.js with ES6 constructs

### ISSUE THREAD

**Issue by altano** [wallabyjs/public#561]
### Issue description or question

I'm running the wallaby.js trial with some very simple mocha tests which pass just fine, but I can't get wallaby.js to run the project tests.  On the "module.exports = ..." line for all 3 source files in the project, I get errors:

```
​0 failing tests, 0 passing
​
​SyntaxError: Parse error
​ c:\src\experiments\cdner\src\CDNTransformer.js:13:0
​SyntaxError: Parse error
​ c:\src\experiments\cdner\src\HtmlTransformer.js:8:0
​SyntaxError: Parse error
​ c:\src\experiments\cdner\src\urlConverter.js:13:0
```

Note that the exports are ES6 constructs such as classes and arrow functions, e.g. CDNTransformer.js:13:0:

```module.exports = class CDNTransformer extends HtmlTransformer {```

These are all supported natively in Node.js, I'm *not* using --harmony* flags, and a vanilla call to `mocha .\tests\*.js" passes just fine.

If I simplify the export to just be a string, I then get an error on the require call:

```
​ReferenceError: Can't find variable: require
​ c:\src\experiments\cdner\src\CDNTransformer.js:3:0
```

Clearly wallaby.js is not liking commonjs and ES6, but I can't see why.  Help?

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      "src/**/*.js"
    ],

    tests: [
      "test/**/*.spec.js"
    ],

    testFramework: "mocha"
  };
};
```

### Code editor or IDE name and version

Visual Studio Code
Version 1.0.0
Commit fa6d0f03813dfb9df4589c30121e9fcffa8a8ec8
Date 2016-04-13T14:08:36.599Z
Shell 0.35.6
Renderer 45.0.2454.85
Node 4.1.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
By default wallaby.js is set to run browser tests (in PhantomJs), in your case it looks like you are running node.js tests, so you need to [set `env: {type: 'node'}`](https://wallabyjs.com/docs/integration/node.html).
Let me know if this helps.

**Comment by altano** [comment]
Oh that worked perfectly.  I was looking at the VSCode installation setup and didn't look at the node integration page so I never saw that.

Oh man, wallaby is amazing.  Took me a bit to figure out how to get the TS support working but it was worth the effort.

Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> Took me a bit to figure out how to get the TS support working

Is there anything we could better document to make it easier to configure TS in wallaby?

**Comment by altano** [comment]
Nope, all of the issues I hit were just related to writing and running TypeScript tests.  TypeScript is wonderful but makes setting up your testing framework and initial tests much more annoying.

I initially tried to leave my tests as JS tests but I couldn't get wallaby.js to work with that setup.  If that *is* possible, you might want to document how.

Thanks again.
