### ISSUE TITLE
webpack + babel + jest

### ISSUE THREAD

**Issue by andrew-w-ross** [wallabyjs/public#563]
### Works until async await

Error is `ReferenceError: regeneratorRuntime is not defined`
I assume it's because babel-polyfill is not applying itself correctly.

### Wallaby.js configuration file

```javascript
var babelCore = require("babel-core");

module.exports = function (wallaby) {

	return {
		files: [
			'src/**/*.ts',
			'!src/**/*.spec.ts'
		],
		tests: [
			'src/**/*.spec.ts'
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript()			
		},
		testFramework: 'jest',
		preprocessors: {
			'**/*.js': function (file) {
				return babelCore.transform(file.content, {
					sourceMap: true,
					compact: false,
					presets: ["es2015", "stage-2", "jest"]
				});
			}
		},
		env: {
			type: 'node',
			runner: 'node'
		},
		reportConsoleErrorAsError: true,
		setup: function (wallaby) {
			require("babel-polyfill");
			wallaby.testFramework.configure({
				automock: false
			});
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.0.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Jest creates isolated context for tests with its own set of globals. Once you call `require("babel-polyfill");` it creates the `regeneratorRuntime` global variable, so all you need to do is to pass it to jest created isolated contexts. There're a few ways to do it, the easiest is to just use jest [`globals` configuration option](http://facebook.github.io/jest/docs/api.html#globals-object):
```javascript
setup: function (wallaby) {
            require("babel-polyfill");
            wallaby.testFramework.configure({
                automock: false,
                globals: {
                  regeneratorRuntime: global.regeneratorRuntime
                }
            });
        }
```
Let me know if it works for you.

**Comment by andrew-w-ross** [comment]
@ArtemGovorov excellent that worked perfectly, thanks.

**Comment by aledoroshenko** [comment]
Guys, i'm playing with Wallaby in existing project, and have that `regeneratorRuntime` issue with async/await. But when i try to do `require("babel-polyfill")` in `setup` method, i have error `Uncaught ReferenceError: require is not defined`.

I have this for now:

```
const wallabyWebpack = require('wallaby-webpack');
const wallabyPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'node_modules/chai/chai.js', instrument: false },
      { pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false },
      { pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', instrument: false },
      { pattern: 'app/**/*.js', load: false },
      { pattern: 'app/**/*.spec.js', ignore: true, load: false },
    ],

    tests: [
      { pattern: 'app/test/*.spec.js', load: false }
    ],

    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      kind: 'electron'
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      require("babel-polyfill");
      window.assert = chai.assert;
      window.sinon = sinon;
      window.__moduleBundler.loadTests();
    }
  };
};
```

Where should i look at? Some env issue? Modules resolving issue?

**Comment by ArtemGovorov** [comment]
@aledoroshenko The easiest way would be to include the module globally via `script` tag, jsut like you are doing it for `chai` and `sinon`:

```
...
{ pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
...
```

If you like, you may also `require` it, but it can not be done inside the `setup` function. The setup function runs as is in browser before your tests (it's not processed by webpack), so it fails with the `require is not defined` error. The place to use `require` or `import` the polyfill would be a file to bootstrap your tests, that you'd need to specify as an [entry pattern for wallaby-webpack](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns).

**Comment by aledoroshenko** [comment]
Thanks @ArtemGovorov, worked perfectly.

**Comment by aledoroshenko** [comment]
One more question. Docs for entry pattern shows this:

> So, for example, if you have a fixture.js file that requires other files of your app and you would like it to be compiled by Webpack and loaded into the sandbox, then your wallaby config may look like

```
entryPatterns: [
    'fixture.js',
    'src/**/*.spec.js'
]
```

We need `src/**/*.spec.js` line because those files might be used in `fixture.js`, correct? We can't just use `entryPatterns: ['fixture.js']`, because files that might be used inside `fixture.js` would not be compiled?

**Comment by ArtemGovorov** [comment]
> We need src/**/*.spec.js line because those files might be used in fixture.js, correct?

Not really. It's just the `entryPatterns` setting default value is all of your specs by default (whatever is in your `tests` list). When you override the setting, you may specify any entry points, so not only add some bootstrap fixtures, but also adjust your webpack-ed tests.

For example, consider a hybrid app, where some of your app/tests are webpack-ed, and some are not. You may override entry points and only include those of your tests that you want to be bundled with webpack, and still have some other tests in your `tests` list that will have `load: true` and run outside of the webpack bundle.

**Comment by aledoroshenko** [comment]
Oh, now i get it, thanks for explanation!
