### ISSUE TITLE
Support for multi module projects in idea

### ISSUE THREAD

**Issue by benediktarnold** [wallabyjs/public#564]
### Issue description or question
I have an idea project with multiple modules (maven multi module project). Only one of the modules contains frontend code written in typescript and therefore the package.json and node_modules are in this directory. When I run wallaby from idea, it always tries to resolve node_modules from the root folder and I think this is because the working directory for the wallaby run is the project root folder. Is there any way to configure the working directory?

My folder layout looks like this
```
.
├── backend-module
└── frontend-module
    ├── node_modules
    ├── package.json
    └── wallaby.js
```
When I run wallaby, it creates a node_modules in the project root, but all dependencies are in frontend-module/node_modules
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({});

module.exports = function () {
   return {
      files: [
         { pattern: 'src/main/frontend/**/*.ts', load: false },
         { pattern: 'src/main/frontend/**/*.spec.ts', ignore: true }
      ],

      tests: [
         { pattern: 'src/main/frontend/**/*.spec.ts', load: false }
      ],

      postprocessor: webpackPostprocessor,

      bootstrap: function () {
         window.__moduleBundler.loadTests();
      }
   };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2016.1.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I have just tried a simple multi-module project with the structure like yours and it works fine for me. Wallaby.js working directory is the directory of the wallaby.js file itself. All paths in the wallaby.js `files` and `tests` lists should be relative to the wallaby.js file.
In your case, is the `src/main/frontend`a subfolder of the `frontend-module`?

**Comment by ArtemGovorov** [comment]
I'll close the issue for now. Please let me know if it's still not working for you.
