### ISSUE TITLE
Support Opal-RSpec

### ISSUE THREAD

**Issue by wied03** [wallabyjs/public#565]
Probably a big leap for a small user base but thought I'd put it out here anyways.

Opal has a webpack loader and
https://github.com/wied03/karma-opal-rspec/tree/webpack_refactor includes an RSpec reporter that funnels into Karma.

It looks like you're pretty into the guts of compilation though, so the opal webpack loader probably wouldn't be the preferred route here.

I'm gathering from other issues you do not work with 3rd party developers right now?

**Comment by ArtemGovorov** [comment]
> I'm gathering from other issues you do not work with 3rd party developers right now?
It looks like in this particular case it may be possible to implement the support as a [custom compiler](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler). Custom compiler is just a function that given Opal-RSpec should return an object with a source map, generated JS and a coverable ranges array (that will be used to display coverage in the original Opal-RSpec file).

**Comment by ArtemGovorov** [comment]
So it may be just a matter of taking the exiting modules that compile Opal-RSpec to JS (used in the webpack loader), adding coverable ranges, and wrapping it as a custom compiler function in your wallaby config (or a separate npm package).

**Comment by wied03** [comment]
Thanks for the quick response. What about dependencies? Am I right from looking at the docs that Wallaby just loads everything specified by `files` into the browser and lets the browser deal with requiring, irrespective of what the tests actually require/depend on?

**Comment by ArtemGovorov** [comment]
@wied03 Wallaby supports [webpack](https://wallabyjs.com/docs/integration/webpack.html) and [browserify](https://wallabyjs.com/docs/integration/browserify.html). When using those, one needs to set `load: false` to the files and they will not be loaded (via `script` tags), but bundled by the module bundler first. Before it happens, wallaby will run any configured compilers on the files.

For example, this is how CoffeeScript/TypeScript work with wallaby.js and webpack: wallaby compiles `.cs`/`.ts` files, then webpack compiles everything. If Opal-RSpec can be compiled to CommonJs JavaScript files (that does `require` whatever they need), then wallaby webpack will compile everything and run tests correctly reporting the coverage to all executed files, including Opal-RSpec files.

**Comment by wied03** [comment]
Sorry if these are dumb questions, but why not just omit the `files` setting and rely on the tests to `require` what they need?

**Comment by ArtemGovorov** [comment]
It is a reasonable question. There are a couple of reasons:
- wallaby not only supports CommonJs, but also other scenarios where file loading is required. Even with webpack, some people prefer to list an assertion lib or a mocking lib to be loaded in browser as a global, rather than to `require` it from all tests or to configure webpack externals.
- just like any solution with code coverage, wallaby uses its own cache of instrumented (to collect code coverage) files to run your tests, so it needs to know what to copy to that cache from your local project. And it needs to know it before any kind of compilation.

Note that in case of using wallaby with webpack, you don't have to list your files one by one, may just use a pattern like `src/**.js`, it should be enough.

**Comment by wied03** [comment]
That makes sense. On another note, yes I think the custom compiler part would cover the Opal to JS piece. The remaining part would be reporting the RSpec results in similar to the Karma framework I wrote. That would require Wallaby developers to do that, right?

**Comment by ArtemGovorov** [comment]
> The remaining part would be reporting the RSpec results in similar to the Karma framework I wrote. That would require Wallaby developers to do that, right?

Yes, sorry, I completely forgot about this bit. We have to support whatever testing framework is used and the framework has to be able to provide some information that we subscribe to (like test/suite started, test/suite finished, etc.). Similar to how we support mocha, jasmine, qunit, etc. It would require Wallaby developers to do it.

Unless of course you can compile Opal-RSpec to mocha/jasmine compliant JavaScript (`describe`/`it`/`beforeEach` etc.), in which case you may just configure wallaby to use mocha or jasmine to run the resulting JS and it should just work.

**Comment by wied03** [comment]
OK. Well wallaby looks like an interesting product. If I run across non Opal situations, I may look into it further. In the meantime, if a type of partner developer setup ever happens that makes it easier to write the testing framework piece, do let me know.
