### ISSUE TITLE
Node 6.0 support for browser tests

### ISSUE THREAD

**Issue by mvestergaard** [wallabyjs/public#568]
There seems to be compatibility issues with node 6.0.
In atom, the spinner in the bottom right corner just keeps going.
In VSCode its the same thing, but i managed to get this error message from the console
`[Error] node: bad option: --harmony_arrow_functions`

Switching back to < 6.0 makes it work again.

**Comment by ArtemGovorov** [comment]
We have discovered and fixed this issue with node 6 support a day ago, shortly after the node release. The core should be updated automatically, if it did, try just restarting your editor. If the update didn't happen yet, try [forcing the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to get the latest core version in Atom and VS Code. Let me know if the latest core version fixes the issue for you.

BTW, Atom also reports the same error in the [Developer Tools Console (`Ctrl/Cmd + Alt + I`)](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) (that's where Wallaby Console output in Atom happens).

**Comment by ArtemGovorov** [comment]
Seems like there's another issue in some projects (with browser tests) and node.js 6 in Atom, VS Code and Sublime Text. 
If your test run hangs (and there are some warnings like `phantom stdout: Incompatibile SockJS` in wallaby console), please [configure your editor to use some previous node version](https://wallabyjs.com/docs/intro/install.html) for now, while we are investigating the issue.

**Comment by ArtemGovorov** [comment]
Node 6 `crypto` module [breaking changes](https://github.com/nodejs/node/pull/5522) had broken 2 different web socket libraries (`ws` and `faye-websocket`) hixie-76 websockets implementation (that PhantomJs 1.9.8 is using). I have patched these and it should be ok now in core v1.0.221.

**Comment by mdreizin** [comment]
@ArtemGovorov I did everything described above and now `wallaby` doesn't work under all `node.js` versions. I always get:

```
bad option: --harmony_arrow_functions
```

**Comment by ArtemGovorov** [comment]
@mdreizin If I remember correctly, you are using WebStorm? Check you wallaby.js plugin version (in Settings - Plugins) to make sure it is >= 1.0.59. If it is < 1.0.59, you need to update wallaby.js plugin to the latest. It should be prompting you to update when you restart your IDE, unless you have turned off wallaby.js notifications in your IDE. Alternatively, you may just download the latest from our website and install it.
If you are experiencing the issue in Atom or VS Code, check what is you core version (printed in dev tools/wallaby console), and if it is < 1.0.221, then try [forcing the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by mdreizin** [comment]
@ArtemGovorov Yes, you are right. I'm using WebStorm and I did everything that you described. It didn't update automatically and that is why I updated it via direct download. Now it works. Thanks.
