### ISSUE TITLE
Programmatically Sort Test Files

### ISSUE THREAD

**Issue by ryanwischkaemper** [wallabyjs/public#574]
I'm working on an application that has a lot of Angular 1.x in it; and, because of that, my Angular source files need to be loaded in a specific order (due to Angular dependencies between them). Right now I user Karma with the [karma-angular-filesort plugin](https://github.com/wilsonjackson/karma-angular-filesort) and it works great.

The problem I'm running into with Wallaby is that (as far as I can tell) if I want to control the order in which the files are loaded, then I need to specify each file individually. In my case, though, this would be way too unwieldy as there are a very large amount of files. I need to be able to specify my files with a glob pattern.

What is the best way to achieve this?

I started on a [Wallaby postprocessor](https://wallabyjs.com/docs/config/postprocessor.html) with the intention of sorting my angular files and spitting them back out in the correct order. I've made some progress on that - I'm able to verify that I am sorting the files correctly in memory in the postprocessor, but I don't know how to properly write them back out to the Wallaby sandbox in the new sort order. Is a postprocessor the correct choice here? If so, any guidance on how to re-order the files?

**Comment by ArtemGovorov** [comment]
It is an interesting question.

Postprocessor approach may work for you, but I think it may be an overkill. Here are a couple of examples on how you write files back from our [webpack postprocessor](https://github.com/jeffling/wallaby-webpack/blob/master/index.js#L157) and [browserify postprocessor](https://github.com/wallabyjs/wallabify/blob/master/index.js#L182). You need to change the file name (for example add `ordered` suffix) to avoid overwriting existing files in the cache.

However, given that you already written the code that does the sorting, perhaps an easier way is to just do the sorting when creating the `files` array. For example, some of our user use `wiredep` plugin to get a list of bower components and [just add it to the `files` list](https://github.com/ArtemGovorov/gulp-patterns/blob/patch-1/wallaby.js#L16). From what I can see in the [karma-angular-filesort plugin](https://github.com/wilsonjackson/karma-angular-filesort/blob/master/lib/sort.js#L30), you'll need to read files content first (with `fs.readFileSync`) to do the sort, but it's only going to happen once on start and I don't think it should affect the startup time much (unless you have several thousands large files).

Either way, let me know how it goes. If you create a sample with a few angular files and your current implementation, I'm happy to jump in and have a look.

**Comment by ArtemGovorov** [comment]
Another possible solution, that doesn't need any wallaby config, but possibly requires some file renaming (so may not be an option for you) is to use `.module` naming convention for module definitions and load them first by specifying their pattern. The [project I have referenced before](https://github.com/ArtemGovorov/gulp-patterns/blob/patch-1/wallaby.js#L24) is Angular 1.x project that follows the convention, so it's possible to just list 2 patterns: `*.module` and the rest.

**Comment by ryanwischkaemper** [comment]
@ArtemGovorov Using the `*.module` pattern first still would not work in my case as some files have Angular module dependencies between them.

I'm going to try renaming the files with an `ordered` suffix within the postprocessor like you suggested and see where I get with that. I've been reading the source for the webpack and browserify postprocessors, but the debugging/development iteration experience is slow and cumbersome (I have to debug almost exclusively via the `logger` writing out to the Wallaby console).

Yes, in order to sort the Angular files properly their contents do need to be read. If the postprocessor doesn't work out for me soon, then I'll try your other route of doing the sorting before creating the `files` array.

One question, though - which of those two approaches do you think would be the fastest in terms of startup and ongoing testing when files are changed?

**Comment by ArtemGovorov** [comment]
> the fastest in terms of startup and ongoing testing when files are changed
In terms of startup - the postprocessor is faster, because wallaby will read all files any way and it'll pass files content, so no need to read it separately.
In terms of ongoing testing, creating the `files` array upfront is faster, because you do it once on startup and then don't do any work (in the postprocessor)

I think sorting files upfront should be easier to implement, while postprocessor approach is more harder to implement. One more thing to note, with the postprocessor you will be able to add/delete new files to your project without having to restart wallaby. In the case of the upfront created `files` list, you will have to restart wallaby if you add/remove a file.

**Comment by ryanwischkaemper** [comment]
@ArtemGovorov I put out a [very early version of the postprocessor](https://github.com/ryanwischkaemper/wallaby-angular-filesort). It works on small demo apps, but I'm testing it now on a fairly large one (~1000 `.js` source files and accompanying tests and html files) and I'm running into some issues - mainly with performance. I have never used Wallaby on this app (or any that large), so I'm not sure if the performance issues are because of my postprocessor or not. But those issues might be because I'm not yet doing any kind of caching of my own in the postprocessor.

Both of the [webpack postprocessor](https://github.com/jeffling/wallaby-webpack/blob/master/index.js#L157) and the [browserify posptprocessor](https://github.com/wallabyjs/wallabify/blob/master/index.js#L182) implement their own caching strategies to prevent unnecessary restarts/reloads of webpack or browserify. Would implementing a caching strategy in my postprocessor be necessary?

My `wallaby.js` config looks like this:

```javascript
var processor = require('wallaby-angular-filesort');
var wallabyPostprocessor = processor ({
  whitelist: ['spa/**/*.js']
});

module.exports = function () {
    // set `load: false` to all Angular source files since their ordered clones will be loaded instead
    files: [
      {pattern: 'src/**/*.js', load: false}
    ],
    tests: [
      'test/**/*Spec.js'
    ],
    postprocessor: wallabyPostprocessor
}
```

The postprocessor only takes action on Angular files from the provided whitelist. In a lot of apps, that'd be fine. In this big one, though, if one Angular file is changed, then the postprocessor has to reorder *all* of them again. I guess I could implement some caching based off the Angular module names and their dependencies. It wouldn't be that bad if, when one Angular file is changed, that only its directly related files would need to be reprocessed. 

But that leads me to another question about how I am ordering the new files. Once they are sorted in the postprocessor and ready to be written to disk, I'm adding the files index from the new sorted array to its original `file.order` from wallaby. I needed to do this to preserve the sorted array's order when wallaby writes the new files to disk. I assume there is no limit to that numeric value (`file.order`)?

```javascript
_.forEach(finalSortedFiles, (file, index) => {
            createFilePromises.push(wallaby.createFile({
              order: file.order + index,
     }));
});
```

Sorry for so many questions about this, but any tips or guidance you could provide to get me on the right track would be greatly appreciated. I recently convinced my company to purchase Wallaby for our department, and now I need to get this working.

Loading all the sorted files upfront will be my fallback, but the postprocessor would be better since it wouldn't require restarting wallaby whenever files are added or removed.

**Comment by ArtemGovorov** [comment]
Thanks for sharing! Looks good. Let's do some performance profiling on your real project and take it from there.

> In Webstorm 2016.1.1 it's taking 30-40 seconds to load before any test results are shown.

So wallaby has a cold start with an empty cache (the cache is cleaned when you make changes to wallaby config file and restart wallaby). During the start it copies all files to its cache, instruments them, runs postprocessor (also compliers and preprocessors) and then runs your tests. This make take some time for ~1000 files.

Then there's a normal start when wallaby just syncs its cache with your local project. This run normally happens when you start/restart wallaby.js without changing your config. During the run wallaby just runs postprocessor and then runs your tests.

Finally there's an incremental run, when wallaby just re-instruments a changed file, runs postprocessor and then runs your tests. Wallaby passes `wallaby.affectedFiles` to the postprocessor so it has a chance to work incrementally.

To find out what's taking so much time it makes sense to configure wallaby to output more details by adding the `debug: true`:
```javascript
...
module.exports = function () {
    return {
      ...
      debug: true
    };
}
```
starting wallaby, then clearing Wallaby Console tab (right click in it, then `Clear`), then changing one of your tests and inspecting the output. If you paste the mentioned output here, I'll be able to tell where does wallaby spend its time and where's the bottleneck.

> Would implementing a caching strategy in my postprocessor be necessary?

Let's first see where the time is spent. If it's not in your `sorter` (which we'll see because you are [logging when its job is over](https://github.com/ryanwischkaemper/wallaby-angular-filesort/blob/master/src/processor.js#L61)), but still in the postprocessor, then the issue most likely is that we're writing these 1000 files on disk every file change.

If that's the issue (and I suspect it may be), then implementing a caching strategy (anything that reduces a number of `wallaby.createFile` for incremental runs) would certainly help. 

Having said that, as I can see, unlike webpack and browserify postprocessor, you are not changing files content, just the order, so it doesn't even make much sense to write files on disk. It should be enough to change existing files order. So I'm thinking I could just add a new API method `wallaby.setOrder(...)` and you'd call it instead.

If we add the method and your sorter is not a bottleneck, then no caching strategy may be required. You may still be able to sort all files on every change, but because you'll not be asking wallaby to write those on disk, but only change existing files order, it may be fast enough.

**Comment by ArtemGovorov** [comment]
So I went ahead and added the `wallaby.setFileOrder({ file: ..., order: ... })` method to the API in core v1.0.222 (you may restart your WS and start wallaby to force the update). As the `createFile` this method return a promise, the `file` property should be set to the original file (the one you set to the `original` property in the [`createFile` calls](https://github.com/ryanwischkaemper/wallaby-angular-filesort/blob/master/src/processor.js#L57)) and the `order` is your integer order.

So just try updating the core and [replacing this line](https://github.com/ryanwischkaemper/wallaby-angular-filesort/blob/master/src/processor.js#L53) with:
```javascript
createFilePromises.push(wallaby.setFileOrder({ file: file, order: file.order+index }));
```
(perhaps also makes sense to refactor the `createFilePromises` name to `updatedFilePromises`)

**Comment by ryanwischkaemper** [comment]
I did some testing, and yes, it is writing those 1000 files to disk on every file change. No good. The `wallaby.setOrder(...)` method sounds really great. Is that something that is feasible in the relatively near future? Forgive me - I know you're busy, and, believe me, I really like and appreciate your work and am not trying to rush this. I just want to get a rough idea (weeks? months?) so that I can decide whether or not to start on the caching for it. Because even if the caching was highly optimized for Angular dependencies between the files, it still wouldn't be nearly as fast as not having to cache or write new files in the first place.

I have been working with Wallaby with `debug=true` for the past few days (it's the fastest/best/only? way for me to debug the postprocessor), and I've been reviewing the logs. I know for sure that each time a file is changed that my postprocessor is writing all of the Angular files again. I don't feel comfortable pasting the whole thing here - it's only file names and their structures, but it's a project at my day job. Is there anything else I should be looking for besides the files being all rewritten? No errors were being logged.


As I'm typing this I just saw your reply - that was fast! I'll get the change made and test it out. And yes, I'll probably rename that method. Probably some others too, I threw that together a little too quickly.

**Comment by ArtemGovorov** [comment]
@ryanwischkaemper Cool, let me know how it goes. One note, I ended up naming it `wallaby.setFileOrder` not the `wallaby.setOrder` as I have originally suggested,

**Comment by ArtemGovorov** [comment]
Oh, forgot to mention, now you also need to remove the `load: false` flag from your files pattern.

**Comment by ryanwischkaemper** [comment]
@ArtemGovorov Will do. We have other non-Angular files being loaded along with all of our Angular files. A good portion of them rely on objects being on the global scope (yes, this is horrible legacy code), so the order in which they are loaded *does* matter. We handle that file ordering manually in the wallaby config, though.  Does `wallaby.setFileOrder` have the potential to disrupt the ordering of the files that I am ignoring in this postprocessor?

**Comment by ArtemGovorov** [comment]
@ryanwischkaemper Wallaby assigns the `order` property (starting from 1) to all files in the `files` list based on their order in the list, and for patterns based on the alphabetical order of the files satisfying the pattern. You then get all files passed to the postprocessor (and their `order` too), and you can change the `order` of some files. The order of the files that you don't call `wallaby.setFileOrder` will not be changed.

For example, if you have 
```
files: [
  'a.js',
  'b.js',
  'src/**/*.js'
]
```
and in your postprocessor you call `wallaby.setFileOrder` only for files in `src/**/*.js`, then `a.js` and `b.js` are still guaranteed to be loaded in that order. Now when the files from `src/**/*.js` will be loaded, is up to you. You may give them `order` that starts from -1000. Then they'll be loaded before `a.js` and `b.js`. You may start their order from 1, then the loading order may look like:
`a.js`, `src/someFileWithOrder1.js`, `b.js`, `src/someFileWithOrder2.js`, `src/someFileWithOrder3.js`, etc. (so they'll be mixed with non changed files, but the order of the non-changed files will be preserved). 

Does it answer your question?

**Comment by ryanwischkaemper** [comment]
It does, thank you. I've got those changes made, will be testing them on the big app soon, and will let you know how it went.

**Comment by ryanwischkaemper** [comment]
@ArtemGovorov With that change in place it is significantly faster when I edit a file. Based on the wallaby console logs, from the time a made a change to the time it finished processing was 4 seconds and 2 of those seconds were spent in my postprocessor. I can share the logs in that time period if you think it will help. But this is very good - I can get quick test feedback. And I'll clean up the postprocessor and see if I can speed it up.

I still get the 30-40 second load time for a cold start, but once the cache was populated it started up in about 20-25 seconds. I just ran the same test suite in karma, and it took 22 seconds. So I don't think that's a problem for a project this size.

Thanks a lot for the help! I'm gonna roll this out to our devs tomorrow.

**Comment by ArtemGovorov** [comment]
Great, thanks for the update.

> was 4 seconds and 2 of those seconds were spent in my postprocessor.

Perhaps it is the `sorter` and you may add some caching and other checks to make it faster. One easy check that comes to mind is to inspect `wallaby.affectedFiles` and if all of the affected files are tests (have `test: true` property), then don't do the sort. This way if you are editing a test, not a source file, you'll not be spending time in the postprocessor.

> the same test suite in karma, and it took 22 seconds

Do you have a code coverage configured for karma? Wallaby always runs with it out-of-box, and it adds a bit of an overhead vs a run without the code coverage collected (like in karma).

**Comment by ArtemGovorov** [comment]
Hm, I think I was wrong about test files optimisation, because you already have the `findEntryFiles` in place.

**Comment by ArtemGovorov** [comment]
Or actually I wasn't wrong :) You are processing all files on every change in the postprocessor, but if the affected file is a test file, you may not do it.

**Comment by ryanwischkaemper** [comment]
Ok, I'll make that change. And yes, Karma was using a junit coverage reporter

**Comment by ryanwischkaemper** [comment]
@ArtemGovorov The [wallaby-angular-filesort postprocessor](https://github.com/ryanwischkaemper/wallaby-angular-filesort) is working and ready to be used. Is there any place where you list community plugins/addons/etc? 

For older Angular apps that don't use Browserify, Webpack, SystemJS, or some other module loader, ordering of the Angular files is necessary for testing. I think it could help out people who are using things like [gulp-angular-filesort](https://github.com/klei/gulp-angular-filesort), [karma-angular-filesort](https://github.com/wilsonjackson/karma-angular-filesort), etc want to use Wallaby.

Plus any additional source code examples of wallaby postprocessors would be helpful to developers.

**Comment by ArtemGovorov** [comment]
@ryanwischkaemper Thanks for the update and for your work on the postprocessor! I'm sure it'll be helpful for developers, both as a tool for those who use Angular 1.x and as an example of a postprocessor implementation for others.

I have added the link to the [list of wallaby.js recipes](https://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes), a note to the [Angular docs page](https://wallabyjs.com/docs/integration/angular.html#angularjs-1x-files-sorting) and a link to the repo as an example of a postprocessor to the [postprocessor docs](https://wallabyjs.com/docs/config/postprocessor.html) (at the bottom of the page).
