### ISSUE TITLE
Wallaby.js Can't work for me

### ISSUE THREAD

**Issue by sliuqin** [wallabyjs/public#575]
### Issue description or question
1. wallaby can't work on my own project which is using babel. 
2. wallaby can't work on `https://github.com/wallabyjs/wallaby-babel-es7-sample`
3. wallaby can work on `https://github.com/wallabyjs/wallaby-node-iojs-sample`

### Code editor or IDE name and version

WebStorm 2016.1.1
Build #WS-145.597, built on March 30, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version
OSX 10.11.4 (15E65)

![untitled-2](https://cloud.githubusercontent.com/assets/590735/14933547/d7fa2732-0ec4-11e6-9adc-3c83e9a95d44.png)

**Comment by ArtemGovorov** [comment]
I'm trying in your WS version on OSX and everything works for me.
What's your npm version (why your npm modules look like symlinks, perhaps it's an issue)? Try using npm 3 to install your node modules to se how it goes.

**Comment by ArtemGovorov** [comment]
It looks like you are using some different package manager to install your NPM packages and it may be causing the issue. Try clearing your `node_modules` folder, running `npm install` and starting wallaby.

**Comment by sliuqin** [comment]
@ArtemGovorov working now, thank you

**Comment by sliuqin** [comment]
just update npm from 2 to 3

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update. I think it should work with npm 2, but in your case it looks like packages were installed with this https://github.com/cnpm/npminstall and it looks like it creates some recursive symlinked structure (that not only causing wallaby to hang, but also hangs my WebStorm right after the installation).
