### ISSUE TITLE
Can't find 'require' for Typescript files

### ISSUE THREAD

**Issue by tsawan** [wallabyjs/public#578]
### Issue description or question
I have a very simple Typescript project. In my test spec, I tried to import the source file to test but it's giving Can't find 'require'. I've included the typescript compiler in my config. please check.

### Wallaby.js configuration file

```
module.exports = function (wallaby) {
    return {
        "files": [
            "src/**/*.ts"
        ],

        "tests": [
            "test/**/*Spec.ts"
        ],
        "compilers": {
            "**/*.ts": wallaby.compilers.typeScript({})
        }
    }
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
By default wallaby.js uses PhantomJs to run your tests. Your TypeScript files `import`s are compiled to CommonJs `require`s. Browser environment doesn't support CommonJs, hence the error. 

If it is a node.js app that you are testing, then you need to [specify the runner type](https://wallabyjs.com/docs/integration/node.html), so your tests will run in node.

If it is a browser app that you are testing, then it depends on the technology your app itself is using. You may configure wallaby.js to use a module bundler, like [Webpack](https://wallabyjs.com/docs/integration/webpack.html) or [Browserify](https://wallabyjs.com/docs/integration/browserify.html), or [System.js](https://wallabyjs.com/docs/integration/systemjs.html).

Let me know if it addresses your issue.

**Comment by tsawan** [comment]
it's a browser app. and I'm using webpack.
so how will it work with webpack/wallaby? I change the code, save the file, bundler will run and then the tests will run?

**Comment by ArtemGovorov** [comment]
Wallaby supports [webpack as a postprocessor](https://wallabyjs.com/docs/integration/webpack.html) and it's fully integrated, so will work just as with other technologies that wallaby supports: no need to save the file, just write your code/tests, wallaby will take care of the rest. Have a look into the referenced docs section how to configure it, you may also clone and run [this sample to quickly see how it works](https://github.com/wallabyjs/wallaby-webpack-sample).

**Comment by tsawan** [comment]
that worked like a charm. Never expected it to be this easy. Many thanks.
