### ISSUE TITLE
'undefined' is not a function (evaluating Object.assign)

### ISSUE THREAD

**Issue by tsawan** [wallabyjs/public#579]
### Issue description or question
I've a test failing where source file is using Object.assign with error message 
"TypeError: 'undefined' is not a function (evaluating Object.assign())"

I am using webpack

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        "files": [
            "src/**/*.ts"
        ],

        "tests": [
            "test/**/*Spec.ts"
        ],
        "compilers": {
            "**/*.ts": wallaby.compilers.typeScript({})
        },
    postprocessor: webpackPostprocessor,

    bootstrap: function() {
       window.__moduleBundler.loadTests();
    }

    }
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
`Object.assign` is a part of ES2015 and wallaby.js by default is using PhantomJs that doesn't support ES2015 (actually no browser fully supports it yet). You'll need to install and include a polyfill, for example babel-polyfill, as [described here](https://github.com/wallabyjs/public/issues/542#issuecomment-204622357). 
Note that you'll need to do something similar in your production app if you intend to support browsers/devices without ES2015 support.

**Comment by tsawan** [comment]
for people using Angular2, u can add
{ pattern: 'node_modules/es6-shim/es6-shim.js', instrument: false }
in your wallaby configuration file to fix this issue.
