### ISSUE TITLE
Test framework [ava] is not supported - Atom 1.7.3 & atom-wallaby 1.0.7

### ISSUE THREAD

**Issue by firrae** [wallabyjs/public#582]
### Issue description or question
Hi there,

I've been setting up a new project to use the Ava test framework and was really pleased to see you had support for it inside wallaby. Sadly though I'm not quite sure what is going on for me to get the following error: `Test framework [ava] is not supported`. It looks like the atom plugin hasn't been updated since 2015, but I remember reading that almost all the plugins were shells that simply downloaded the same core somewhere at some point.

Any help is greatly appreciated!

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
  files: ['src/**/*.js'],
  tests: ['src/**/*.test.js'],

  testFramework: 'ava',

  compilers: {
    '**/*.js': wallaby.compilers.babel({
      presets: ['es2015', 'react'],
      plugins: [
        require('babel-plugin-espower/create')(
         require('babel-core'), {
          patterns:require('ava/lib/enhance-assert').PATTERNS
         })
      ]
    })
  }
});

```

### Code editor or IDE name and version

Atom v1.7.3 with atom-wallaby 1.0.7 plugin

### OS name and version

Windows
OSX

**Comment by jiku** [comment]
I have it working with a very similar config on Atom 1.8.0b3 in OS X. Adding env: 'node' like in the [sample](https://github.com/wallabyjs/ava-sample/blob/master/wallaby.js) might help. Removing that throws the same error here.

**Comment by firrae** [comment]
@jiku that worked, I must have missed that at some point last night. Thanks!

**Comment by firrae** [comment]
Well that has solved it in WebStorm perfectly, sadly though on Atom there are still errors. It's complaining about `TypeError: Cannot read property 'bind' of undefined` when it imports the ava test library.

**Comment by jiku** [comment]
Never had that. If all the devDependencies are installed I have no idea.

**Comment by firrae** [comment]
So Wallaby just updated in Atom, not quite sure if I did something or what, but now it works. I'll close this again, as it all seems good now.

**Comment by ArtemGovorov** [comment]
Wallaby core in Atom gets updated automatically, but a bit differently from WebStorm. If you ever ht the issue with the core update and would like to force the update to make sure you are in the latest version, [here is how to do it](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by firrae** [comment]
@ArtemGovorov good to know, I don't really know what happened, but my best bet was after it was open for a while it realized it was behind and updated itself.

**Comment by ArtemGovorov** [comment]
@firrae Your guess is correct. Here is how it works: to prevent any work distractions, wallaby schedules an update when you start it. After a few minutes after you start it, it downloads the update (if there's any) and waits for your next wallaby (re)start to install it.

**Comment by firrae** [comment]
@ArtemGovorov Awesome, well at least it all got sorted in the end, but that's good to know going forward :smile: Keep up the good work!
