### ISSUE TITLE
can't find require() resources

### ISSUE THREAD

**Issue by tsawan** [wallabyjs/public#586]
### Issue description or question
While testing a Angular 2 component, wallaby is giving error that it can't find css file and html file that is required. e.g., require('./home.css') or require('./home.html'). 
If I change the code to use styleUrl and templateUrl without require, it works fine.
since I am using webpack so I use require for all css and html files.

### Code editor or IDE name and version

IntelliJ IDEA v15

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby config?

**Comment by tsawan** [comment]
module.exports = function (wallaby) {
    return {
        "files": [
            "src/**/*.ts",
           { pattern: 'node_modules/es6-shim/es6-shim.js', instrument: false}
        ],

        "tests": [
            "test/**/*Spec.ts"
        ],
        "compilers": {
            "**/*.ts": wallaby.compilers.typeScript({})
        },
    postprocessor: webpackPostprocessor,

    bootstrap: function() {
       window.__moduleBundler.loadTests();
    }

    }
};

**Comment by ArtemGovorov** [comment]
You need to include patterns for your `css` and `html` files [to your files list](https://wallabyjs.com/docs/config/files.html). I don't see how your `webpackPostprocessor` is defined since you skipped that part, but you may also need to add css and html webpack loaders in its config.

**Comment by tsawan** [comment]
I didn't skip any config part. is there a way to configure webpackPostProcessor to include css files?

in my webpack.config, I am using css-loader and styles-loader.

**Comment by tsawan** [comment]
just to clarify further, I've just listed 'webpackPostprocessor' as suggested in some other thread. I have not written it anywhere and the above config is the complete wallaby.js file I am using.

**Comment by ArtemGovorov** [comment]
> I didn't skip any config part

Then where is in the config you have pasted the `webpackPostprocessor` is defined? If you start the config you pasted you'll get an error because of the undefined variable.

> is there a way to configure webpackPostProcessor to include css files?

You don't need to do it. You need to include `css` and `html` files to your files list, just like describe in the docs I have referenced.

**Comment by ArtemGovorov** [comment]
Depending on how your `webpackPostProcessor` is defined, you may to also add css and html webpack loaders, the same way you do in your webpack config. For example, [this config](https://github.com/wallabyjs/wallaby-webpack-es6-react/blob/master/wallaby.js#L5) adds some webpack specific config options, like `externals` and `resolve`. The same way you may add your loaders. You may find more example and generally webpack integration notes in [this docs section](https://wallabyjs.com/docs/integration/webpack.html).

**Comment by tsawan** [comment]
sorry, I missed to include webpackPostprocessor in config above. that was just a function call with no config options.

I've copied the loaders from main webpack.config.js and pasted in webpackPostprocessor block. It's still giving "Cannot find module "./home.css".

I've also tried to add the file pattern as pattern: 'src/**/*.css' but getting same error. I think adding files pattern won't work since I am using require to bundle the css files. Not sure why the loaders are not working since my webpack bundle is working fine otherwise.

Any more idea(s)?

**Comment by ArtemGovorov** [comment]
Both loaders that you have pasted in the `webpackPostprocessor` block, and patterns for `css` (and `html`) in the `files` list are required. CSS files are required in the list, so that wallaby.js knows it needs to copy them to its cache (that it runs webpack build on).

The `Cannot find module` means that webpack can't find the `home.css` file for some reason. Please double check the pattern and if it is correct, try checking if your css files end up in wallaby cache. You may find the cache location for your project like [described here](https://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page).

If your css file are in the `instrumented` folder in the cache, then I'm out of ideas. In this case, please create a sample GitHub repo demonstrating your issue and I'l have a look.

**Comment by ArtemGovorov** [comment]
Forgot to mention - to get that debugging info with the project cache to wallaby console you'll also need to set [the `debug: true` flag](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) in your wallaby config.

**Comment by tsawan** [comment]
css files are in the cache but the debug log shows the following
No compilers found for src/app/home/home.css
file src/app/home/home.css is not instrumented by core

in webpackPostprocessor I have the following.
loaders: [
    { test: /\.css$/, loaders: ['style', 'css'] },
    { test: /\.html$/,  loader: 'raw' }
]

my css is referred in component like
  styles: [ require('./home.css').toString() ]

toString() was added because of a bug (solution found from SO).

**Comment by ArtemGovorov** [comment]
> css files are in the cache but the debug log shows the following
No compilers found for src/app/home/home.css
file src/app/home/home.css is not instrumented by core

This is ok. `toString()` should also not be an issue.
I'm out if ideas. Please create a simple repository with your config and that `home` file and I'll have a look into what is going on.

**Comment by tsawan** [comment]
got it working. the loaders in webpackPostprocessor had to be in module block. Thanks for help.

**Comment by ArtemGovorov** [comment]
Ok, thanks for the update. Yes, when constructing the `wallabyPostprocessor`, webpack options has to be in the exact same format like in your webpack config.
