### ISSUE TITLE
Support for Visual Studio 15 Preview

### ISSUE THREAD

**Issue by timReynolds** [wallabyjs/public#590]
### Issue description or question

Are you planning on support the Visual Studio 15 preview? Or will you wait until the final release?

**Comment by ArtemGovorov** [comment]
We'll certainly start supporting some versions before the final release, for example when CTP or RC comes out.
As for the preview, I can't make any promises yet, but we'll be looking into it in the next few days to see how much work is required to support it, and will be trying estimate how stable the API we'd need use is. If we make a decision to support it, I'll let you know.

**Comment by grantbowering** [comment]
RC is out now.  (and they've gone back to calling it "2017" instead of "15", thankfully! 😄)

**Comment by ArtemGovorov** [comment]
We are working on the integration. Most the things are already working, so shouldn't take too long.

**Comment by ArtemGovorov** [comment]
The extension for VS 2017 is published https://twitter.com/wallabyjs/status/822039658603298816
