### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by spapaseit** [wallabyjs/public#591]
### Issue description or question
This issue is a continuation of the [issue I filed in the aurelia-skeleton-navigation repository](https://github.com/aurelia/skeleton-navigation/issues/422).

I'm starting to doubt again that the issue is in my code. I've configured **Karma** on my solution and the tests run as expected while wallaby throws a `RangeError: Maximum call stack size exceeded`.

I've included a zip file with the VS2015 project I'm using. It's based on the ASP.NET 5-ES2016 Aurelia Navigation Skeleton so, in order to reproduce the issue:

    npm install
    jspm install -y

Afterwards just open with Visual Studio 2015 and try to start Walllaby up. It should fail with several `RangeError: Maximum call stack size exceeded` errors.

Running `karma start` from de console should run the only 2 (one and a half, actually) tests in de solution successfully.

### Wallaby.js configuration file

```javascript
/* eslint-disable no-var, no-shadow, dot-notation */

module.exports = function(wallaby) {
    return {
        files: [
            { pattern: "wwwroot/jspm_packages/system.js", instrument: false },
            { pattern: "wwwroot/config.js", instrument: false },
            //{ pattern: "wwwroot/lib/jquery/dist/jquery.js", instrument: false },
            { pattern: "src/**/*.js", load: false },
            { pattern: "test/stubs/**/*.js", load: false },
            { pattern: "test/unit/setup.js", load: false }
        ],

        tests: [
            { pattern: "test/unit/**/*.spec.js", load: false }
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel({
                presets: ["es2015-loose", "stage-1"],
                plugins: [
                  "syntax-flow",
                  "transform-decorators-legacy",
                  "transform-flow-strip-types"
                ]
            })
        },

        middleware: (app, express) => {
            app.use("/wwwroot/jspm_packages",
                express.static(require("path").join(__dirname, "wwwroot", "jspm_packages")));
            app.use("/jspm_packages", express.static(require("path").join(__dirname, "wwwroot", "jspm_packages")));
        },

        bootstrap: function(wallaby) {
            var promises = [];
            var i = 0;
            var len = wallaby.tests.length;

            wallaby.delayStart();

            System.config({
                paths: {
                    '*': "*"
                }
            });
            for (; i < len; i++) {
                promises.push(System["import"](wallaby.tests[i].replace(/\.js$/, "")));
            }

            System.import("test/unit/setup")
                .then(function() {
                    return Promise.all(promises);
                })
                .then(function() {
                    wallaby.start();
                })
                .catch(function(e) { setTimeout(function() { throw e; }, 0); });
        },

        debug: false
    };
};
```

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version

Windows 10

[Maximum call stack size exceeded - Code.zip](https://github.com/wallabyjs/public/files/254952/Maximum.call.stack.size.exceeded.-.Code.zip)

**Comment by ArtemGovorov** [comment]
> I've configured Karma on my solution and the tests run as expected while wallaby throws a `RangeError: Maximum call stack size exceeded`

You have configured Karma to use Chrome, while wallaby.js is using PhantomJs by default. If you change your Karma config to use PhantomJs:
```
```

**Comment by ArtemGovorov** [comment]
> I've configured Karma on my solution and the tests run as expected while wallaby throws a `RangeError: Maximum call stack size exceeded`

You have configured Karma to use Chrome, while wallaby.js is using PhantomJs by default. If you change your Karma config to use PhantomJs:
```javascript
browsers: ["PhantomJS"],
```
+
```
npm i karma-phantomjs-launcher phantomjs-prebuilt --save-dev
```
and run karma, you will get the same error.

**Comment by ArtemGovorov** [comment]
So the issue seems to be that PhantomJs can't run your projects tests for some reason.

Given that Chrome works, you may use [Electron test runner](https://wallabyjs.com/docs/integration/electron.html) with wallaby and it will also work for you. All you have to do is to install the module:
```
npm install electron-prebuilt --save-dev
```
and configure wallaby to use electron instead of PhantomJs:
```javascript 
module.exports = function () {
  return {
    ...
    env: {
      kind: 'electron'
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Was digging a bit more and looks like it's the issue caused by `core-js` loading after `aurelia-polyfills` in PhantomsJs.

`aurelia-polyfills` adds polyfills for `Map` (and a few other collections). Later on in the code `aurelia-framework` gets imported and it depends on `core-js` which is trying to add its own polyfill for `Map` and it causes the `RangeError: Maximum call stack size exceeded` in PhantomJs (both in karma and wallaby).

If you'd like to keep using PhantomJs, the workaround is to make core-js add its polyfills before `aurelia-polyfills`. You may do it add by importing `aurelia-framework` (that imports `core-js`), before `aurelia-polyfills` in your `setup.js` file:

```javascript
import "aurelia-framework";
import "aurelia-polyfills";
...
```

**Comment by ArtemGovorov** [comment]
Another solution to load `core-js` before `aurelia-polyfills` is to install the latest (that has proper browser bundles):
```
npm i core-js@2.4.0 --save-dev
```
and add it your `files` list:
```javascript
files: [
            { pattern: "wwwroot/jspm_packages/system.js", instrument: false },
            { pattern: "wwwroot/config.js", instrument: false },
            { pattern: "node_modules/core-js/client/core.js", instrument: false },
            ...
        ],
```

**Comment by spapaseit** [comment]
I should've paid more attention on the Wallaby/PhantomJs and Karma/Chrome combinations, so sorry for an unfair claim.
Thank you very much for delivering yet again amazing support; works like a charm
