### ISSUE TITLE
VScode is it possible to get a test failure to be reported as an error or warning to the ide

### ISSUE THREAD

**Issue by andrew-w-ross** [wallabyjs/public#596]
Just an idea as currently pressing `cmd + shift + M` is pretty natural when typescript or linting issues occur.

**Comment by ArtemGovorov** [comment]
I think it's a good idea. Wallaby has the `Jump to error/test` commands that navigate to the error and of course the `Wallaby Tests` output channel with the details, but I like the idea of displaying the list of error details with navigation like `cmd + shift + M` does.

**Comment by monagames** [comment]
That would be fantastic. The problems pane has been improved a lot in the latest release of VS Code

**Comment by smcenlly** [comment]
Wallaby for VS Code now reports errors to the problems view.
