### ISSUE TITLE
Issue with browserify and require html file

### ISSUE THREAD

**Issue by Autushka** [wallabyjs/public#598]
### Issue description or question
Having issue while trying to make wallaby working for a browserify js project in webstorm.

I'm getting an error when I require a html file:

Postprocessor run failure: Unexpected token (2:0) while parsing .\app\app.html while parsing file: C:\Users\aautushk\.WebStorm2016.1\system\wallaby\projects\e91e7db9a266ddb6\instrumented\app\app.html

To test out the problem I  used project https://github.com/wallabyjs/public. I have just switched from ts to js, added file app.html and added var template = require('./app.html') to spec.setup.js;

### Wallaby.js configuration file

```javascript
module.exports = function () {
  var wallabify = require('wallabify');

  var wallabyPostprocessor = wallabify({
      entryPatterns: [
        'app/spec.setup.js',
        'app/src/**/*.spec.js'
      ]
    }
  );

  return {
    files: [
      {pattern: 'app/spec.setup.js', load: false, instrument: false},
      {pattern: 'app/**/*.html', load: false, instrument: false},
      {pattern: 'app/src/**/*.js', load: false},

      {pattern: 'app/src/**/*.spec.js', ignore: true}
    ],

    tests: [
      {pattern: 'app/src/**/*.spec.js', load: false}
    ],

    testFramework: 'mocha',

    postprocessor: wallabyPostprocessor,

    bootstrap: function (w) {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm 2016.1.1

### OS name and version

Windows7

**Comment by ArtemGovorov** [comment]
If I'm not mistaken browserify needs some transform to be able to `require` HTML files, doesn't it? For example, if you expect your template to be loaded as a string, you may use [`stringify`](https://www.npmjs.com/package/stringify):

```javascript
var wallabyPostprocessor = wallabify({
      entryPatterns: [
        'app/spec.setup.js',
        'app/src/**/*.spec.js'
      ]
    },
    b => b.transform(require('stringify'), {appliesTo: {includeExtensions: ['.html']}}) 
  );
```
Depending on how it works in your app, you may need a different transform.

**Comment by Autushka** [comment]
Works fine now, thanks. Final wallaby.js:
`var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({ entryPatterns: ['src/app/app.js'] },
    function (obj) {
        return obj.transform(require('stringify'), { appliesTo: { includeExtensions: ['.html'] } });
    }
);

module.exports = function () {
    return {
        files: [
            { pattern: 'build/assets/js/lib.js' },
            { pattern: 'node_modules/angular-mocks/angular-mocks.js' },
            { pattern: 'src/**/*.html', instrument: false },
            { pattern: 'src/**/*.js', load: false },

            { pattern: 'src/**/*.spec.js', ignore: true }

        ],

        tests: [
            { pattern: 'src/**/*.spec.js' }
        ],
        
        postprocessor: wallabyPostprocessor,

        setup: function () {
            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        }
    };
};

`
