### ISSUE TITLE
Unable to register Wallaby on Webstorm 2016.2 EAP

### ISSUE THREAD

**Issue by vjau** [wallabyjs/public#600]
### Issue description or question
Today, Jetbrains released Webstorm 2016.2 EAP.
However, the wallaby plugin complains that i have no valid license.
Copying and pasting my license in the appropriate dialog doesn't seems to work.

Thank you.

**Comment by ArtemGovorov** [comment]
Just tried your license key in the latest WebStorm EAP (Build #WS-162.74.17, built on May 13, 2016) and it works for me. Please double check that you are pasting the full key, yours should start with `V` and end with `=`.

**Comment by ArtemGovorov** [comment]
If it doesn't help, please send me the key you are trying to enter to hello@wallabyjs.com.

**Comment by vjau** [comment]
Ok, i got a wallaby update, and now it works, thanks.
