### ISSUE TITLE
Issues with Wallaby in Atom VS Webstorm (NVM installed)

### ISSUE THREAD

**Issue by benstoltz** [wallabyjs/public#601]
### Issue description or question
Greetings! I'm running into a bit of an issue with wallaby. Let's take the [Calculator sample ](https://github.com/wallabyjs/calculator-sample). When I run wallaby in Webstorm, yay, everything works. However when I run that same file in Atom it endlessly processes with an error that `Wallaby Console: phantomsjs-node: You don't have 'phantoms' installed.`

Alright, so it's not picking up Node due to NVM and web storm comes bundled with a node env. So I add an env section to the wallaby.js which then causes wallaby to spit out that Calculator and $ is not defined. And at that point I'm somewhat at a loss. Any advice?

Thanks!

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true,
    env: {
      type: 'node',
      params: {
        env: '/Users/un/.nvm/versions/node/v4.0.0/bin/node'
      }
    }
  };
};

```

### Code editor or IDE name and version

WebStorm v11
Atom v1.7.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The error looks a bit strange, is it the exact error copy/pasted from the console?

Anyway, if it's the node issue, then you may configure node version that will run wallaby.js itself in Atom init script, [like described here](https://wallabyjs.com/docs/intro/install.html#nodejs-1). You need to remove the `env` section:
```
env: {
      type: 'node',
      params: {
        env: '/Users/un/.nvm/versions/node/v4.0.0/bin/node'
      }
    }
```
from your config. This is where you specify settings if you'd like wallaby.js to run your node.js tests.

Let me know if it addresses your question/issue.

**Comment by benstoltz** [comment]
Hey @ArtemGovorov Yeah, that's the exact error. Actually I still get the Phantom error even when I specify `process.env.WALLABY_NODE = /path/to/node`

Any thoughts?

![screen shot 2016-05-19 at 10 13 59 am](https://cloud.githubusercontent.com/assets/7872951/15396553/a4cb5670-1daa-11e6-8fe6-a190bb4310b2.png)

**Comment by ArtemGovorov** [comment]
It looks like some issue with phantomjs that gets installed as a part of wallaby.js package for Atom. Try opening `/Users/ben7664/.atom/packages/atom-wallaby/node_modules/phantomjs/lib` to check if there's an executable of PhantomJs in the folder. If there's not, try [downloading it from here](https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip) and extracting into the folder.

Either way, could you please try re-installing wallaby.js package for Atom?
If nothing from above works, try installing PhantomJs manually and configuring [like described here](https://wallabyjs.com/docs/integration/phantomjs2.html).

**Comment by benstoltz** [comment]
I've actually had this issue occur on two separate machines one with NVM and one without. And it persisted through a re-install of wallaby.js package for Atom. It does appear that there's an executable for PhantomJs in atom-wallaby, but it's not properly recognizing it. 

npm installing phantomjs2-ext and setting it yields a success:
```javascript
    env: {
      runner: require('phantomjs2-ext').path,
      params: { runner: '--web-security=false' }
    },
```

Could there be an issue with the atom-wallaby package / conflict with Atom? My only reason for asking this is this did persist through several installs and on multiple machines.

**Comment by ArtemGovorov** [comment]
Ok, cool, we've got somewhere. Please try specifying the path to the executable for PhantomJs in atom-wallaby in the `env.runner` (where you have a path to phantomjs2-ext now).

> Could there be an issue with the atom-wallaby package / conflict with Atom? 

Not sure. It works for me in the same environment (Atom version + OSX).

**Comment by benstoltz** [comment]
Swapping the path to the executable for PhantomJs in atom-wallaby in the env.runner worked as well.

**Comment by ArtemGovorov** [comment]
Interesting... Could you please try opening Atom, displaying wallaby panel (with `Ctrl + 1`), opening Atom Dev Tools, go to Console tab and execute `global.wallaby`. The displayed object should have the `phantomPath` property:
<img width="337" alt="screen shot 2016-05-20 at 12 51 09 pm" src="https://cloud.githubusercontent.com/assets/979966/15415967/f03ec04e-1e89-11e6-99a1-91a9b2bddad6.png">

Does the property contain the exact path to the executable for PhantomJs in atom-wallaby?
