### ISSUE TITLE
Setting up wallaby with react-native + enzyme + react-native-mock

### ISSUE THREAD

**Issue by sattaman** [wallabyjs/public#602]
### Issue description or question

Setting up wallaby with react-native + enzyme + react-native-mock

I am currently running my tests through node using the following command: 

scripts": {
    ...
    "test": "mocha --require react-native-mock/mock test/init.js --recursive test/**/*.js"
  },

where init.js is as follows

```
require("babel-register")({
    only: [
        "/app/**/*",
        "/test/**/*",
        "/node_modules/react-native-router-flux/**",
        "/node_modules/react-native-router-flux/src/**",
        "/node_modules/react-native-tabs/**",
        "/node_modules/react-native-button/**/*",
    ]
});
```
Is it possible to recreate this in wallaby? 

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It should be possible. Just need to list [files and tests](https://wallabyjs.com/docs/config/files.html) separately, specify [babel compiler](https://wallabyjs.com/docs/integration/es-next.html), [node.js environment](https://wallabyjs.com/docs/integration/node.html) and a [setup function](https://wallabyjs.com/docs/config/bootstrap.html) to do what `mocha --require` does.

So the config something like this shoild work for you:
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'app/**/*',
      "node_modules/react-native-router-flux/**",
      "node_modules/react-native-router-flux/src/**",
      "node_modules/react-native-tabs/**",
      "node_modules/react-native-button/**/*"
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    tests: [
      'test/**/*Spec.js' // or whatever the pattern for tests you have
    ],

    env: {
      type: 'node'
    },

    setup: function() {
      require('react-native-mock/mock');
    }
  };
};
```

Note that the `init.js` is not required and `tests` pattern should only include files with actual tests. The config also assumes you have a `.babelrc` file.

Let me know how it goes, and if you hit other configuration issues, please create a sample repo reproducing the issue. I'm happy to have a look and try to help.

**Comment by sattaman** [comment]
I get the following error. 

```
Failed to parse node_modules/react-native-button/LICENSE, SyntaxError: Unexpected token (1:4)
  at emitTwo (events.js:87:13)
  at process.emit (events.js:172:7)
  at handleMessage (internal/child_process.js:686:10)
  at Pipe.channel.onread (internal/child_process.js:440:11)
```

The original code I was running was transpiling these node_modules since they are es6 and not es5. I don't want to run tests on these folders.

**Comment by ArtemGovorov** [comment]
> The original code I was running was transpiling these node_modules since they are es6 and not es5. I don't want to run tests on these folders. Is it possible to configure babel in this way?

I understand, and yes, it should be possible. Try this:

```javascript
files: [
      'app/**/*',
      "node_modules/react-native-router-flux/**/*.js",
      "node_modules/react-native-router-flux/src/**/*.js",
      "node_modules/react-native-tabs/**/*.js",
      "node_modules/react-native-button/**/*.js"
    ],
```

**Comment by sattaman** [comment]
It still doesn't seem to be transpiling, it errors at the import 

import Button from 'react-native-button';  - Syntax error: unexpected token { 

I also tried "node_modules/react-native-button/*.js" since the file is at root level in that folder

**Comment by sattaman** [comment]
I think it may be an issue with that particular module not specifiying a .babelrc file .. Although works direct from node which is strange. 

The others seem to work :) Cheers

**Comment by ArtemGovorov** [comment]
It looks like the mode includes some `jsx`. Wallaby.js uses your project `.babelrc` to compile those files. Does your `.babelrc` contain `react` preset? If not and you don't like to chnage it, you may just pass the options right to wallaby babel compiler:
```javascript
    ...
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: ['es2015', 'react']
      })
    },
    ...
```

**Comment by ArtemGovorov** [comment]
Ok, I have created a sample to try and run it, here is what what missing: because `package.json` wasn't included in the pattern, wallaby was falling back to original modules as opposed to using compiled ones. Here's the config that should work:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'app/**/*',
      'node_modules/react-native-router-flux/**/*.js*',
      'node_modules/react-native-tabs/**/*.js*',
      'node_modules/react-native-button/**/*.js*'
    ],

    tests: [
      'test/**/*Spec.js' // or whatever the pattern for tests you have
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    setup: function() {
      require('react-native-mock/mock');
    }
  };
};
```

**Comment by ArtemGovorov** [comment]
Here's an alternative config that is closer to what you had with mocha CLI:
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'app/**/*'
    ],

    tests: [
      'test/**/*Spec.js' // or whatever the pattern for tests you have
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    setup: function() {
      require('react-native-mock/mock');
      require("babel-register")({
        only: [
          '/node_modules/react-native-router-flux',
          '/node_modules/react-native-tabs',
          '/node_modules/react-native-button'
        ]
      });
    }
  };
};
```
it will dynamically compile specify node modules via babel hook, as opposed to compiling everything upfront like in the previous config.

**Comment by sattaman** [comment]
Hi, one further question. I was wondering whether something like 

```
module.exports = function (wallaby) {
  return {
    files: [
      'app/**/*'
    ],

    tests: [
      'test/**/*Spec.js' // or whatever the pattern for tests you have
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node'
    },

    setup: function() {
      require('react-native-mock/mock');
      require('./test/init');
    }
  };
};
```

would work? It doesn't seem to, but it would be really nice if I could configure all my tests in one place.

**Comment by ArtemGovorov** [comment]
@sattaman Yes, it should work, just need to add the init file to the files list:
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'app/**/*',
      'test/init.js' // <---
    ],

    ...
    setup: function() {
      ...
      require('./test/init');
    }
  };
};
```
