### ISSUE TITLE
Configure colors for color blindness

### ISSUE THREAD

**Issue by jesperstarkar** [wallabyjs/public#603]
I'm slightly color blind and have a hard time separating single yellows from a sea of greens. Would you consider doing the colors configurable, or apply a highcontrast mode?

Visual Studio Code
OSX

**Comment by ArtemGovorov** [comment]
Done. Please update your wallaby VS Code extension to v1.0.13. Icon colors may now be changed from `settings.json` (`Preferences - User settings`). You may find the example with the default colors below. 

```
{
	...

	"wallaby.colors": {
		"covered": "#62b455",
		"errorPath": "#ffa0a0",
		"errorSource": "#fe536a",
		"notCovered": "#cccccc",
		"partiallyCovered": "#d2a032"
	}
}
```
