### ISSUE TITLE
Wallaby + jspm + wwwroot folder

### ISSUE THREAD

**Issue by jkennerley** [wallabyjs/public#604]
### Issue description or question
I am using jspm + vscode and basing my example on the https://github.com/wallabyjs/wallaby-jspm-sample. 
The change I have is trying to use wwwroot folder rather than of the root of the project folder.
I have left my example here https://github.com/jkennerley/en2

The issue is trying to get a wallaby js that will run tests. 
On running wallaby in the console window it shows ...

0 failing tests, 0 passing

​
```
​ReferenceError: Can't find variable: System
​ReferenceError: Can't find variable: System
​at http://localhost:8550/wallaby_sandbox0.html:14


```

Please see, https://github.com/jkennerley/en2 for whole example.

### Wallaby.js configuration file

module.exports = function () {

  //var babelPreprocessor = file => require('babel').transform(file.content, {sourceMap: true});
  var babelPreprocessor = file => require('babel-core').transform(file.content, {sourceMap: true});

  return {
    files: [
      {pattern: 'jspm_packages/system.js', instrument: false},
      {pattern: 'config.js', instrument: false},
      {pattern: 'wwwroot/src/**/*.js', load: false}
    ],
    tests: [
      {pattern: 'test/src/**/*Spec.js', load: false}
    ],

    preprocessors: {
      'test/*.js': babelPreprocessor,
      'src/*.js': babelPreprocessor
    },

    middleware: (app, express) => {
      app.use('/jspm_packages', express.static(require('path').join(__dirname, 'jspm_packages')));
    },

    setup: function (wallaby) {
      wallaby.delayStart();

      var promises = [];
      for (var i = 0, len = wallaby.tests.length; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }

      Promise.all(promises).then(function () {
        wallaby.start();
      }).catch(function (e) { setTimeout(function (){ throw e; }, 0); });
    }
  };
};

```javascript
Please see, https://github.com/jkennerley/en2 and the file test/src/WaSpec.js.




//import { Wa } from 'Wa'

describe("Wa" , function(){
    it("", function(){
        console.log("t1") ; 
        expect(1).toBe(1) ; 
    }) ; 
} ) ; 

/*
describe('Wa', function () {
  it('foo shuold return expected', function () {
    let wa = new Wa(); 
    expect(wa.foo()).toBe("wa.foo");
  });

});
*/



```

### Code editor or IDE name and version
Visual Studio Code v1.1.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Have sent you the pull request https://github.com/jkennerley/en2/pull/1.
The only required change to make it work is to remove `/` before paths in your `files`. The rest of my changes are really optional (we recommend to use compilers instead of preprocessors).

**Comment by jkennerley** [comment]
Than you, for the merge request and change.
The simplistic starter tests are still not running, because of another issue.

I merged your change and pushed back to my repo at https://github.com/jkennerley/en2.

The next issue is a xhr loading issue with wallaby issue with WaSpec.js & {import _ from "lodash" ; import {Wa} from "Wa"} -> xhr error.

XHR error loading http://localhost:9439/jspm_packages/npm/babel-core@5.8.38.js

**Comment by ArtemGovorov** [comment]
Replied here https://github.com/wallabyjs/public/issues/606#issuecomment-220864671
