### ISSUE TITLE
wallaby + jspm + babel + import statement in Spec.js file yields xhr issue/question

### ISSUE THREAD

**Issue by jkennerley** [wallabyjs/public#606]
### Issue description or question
xhr issue when running tests with statements
For full example, see https://github.com/jkennerley/en2 

### Wallaby.js configuration file
see https://github.com/jkennerley/en2 

### Code editor or IDE name and version
Visual Studio Code v1.1.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
As you may see from the error:
```
XHR error loading http://localhost:9439/jspm_packages/...
```
your app (or modules of your app) is trying to load modules from `jspm_packages` directly (not from `www/jspm_packages`), so you need one more mapping in your [`middleware` function](https://wallabyjs.com/docs/config/middleware.html) to make it work:
```javascript
    middleware: (app, express) => {
      app.use('/wwwroot/jspm_packages', express.static(require('path').join(__dirname, '/wwwroot/jspm_packages')));
      app.use('/jspm_packages', express.static(require('path').join(__dirname, '/wwwroot/jspm_packages')));
    },
```
This will route any `/jspm_packages` requests to the `/wwwroot/jspm_packages` folder.
Have sent you [the pull request](https://github.com/jkennerley/en2/pull/2).

**Comment by jkennerley** [comment]
OK, thank you.  I read your link at https://wallabyjs.com/docs/config/middleware.html.
