### ISSUE TITLE
Wallaby now hangs with jest

### ISSUE THREAD

**Issue by andrew-w-ross** [wallabyjs/public#608]
Example repo [here](https://github.com/andrew-w-ross/jest_check)

If you run wallaby it hange if you run jest directly by calling `npm test` it passes.

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

OSX
node 6.2.0

**Comment by ArtemGovorov** [comment]
Added Jest 12.1 support in wallaby core v1.0.235. You may wait a few minutes until it updates automatically during your next wallaby restart or [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by andrew-w-ross** [comment]
Holy hell that was fast, just got the update now and it works thanks.

**Comment by ArtemGovorov** [comment]
Thank you for the provided repo :)
