### ISSUE TITLE
VSCode Last Screenshot

### ISSUE THREAD

**Issue by newtack** [wallabyjs/public#609]
When do you expect to support the last screenshot feature in VSCode if at all? What are your dependencies to accomplish this?
(We are in the process of deciding between VSCode and WebStorm and would like to use VSCode)

**Comment by ArtemGovorov** [comment]
There's some missing VS Code API to open non-text files: https://github.com/Microsoft/vscode/issues/566. So wallaby.js takes the screenshot and there's a PNG file that it can display, but there's no API to open the file in VS Code. If you like, I can share a way how to find the file for your project and so you may open it manually in VS Code for now.

**Comment by ArtemGovorov** [comment]
I may actually investigate and try some other ways to display the image, will let you know if I find a way to do it.

**Comment by thomas-jeepe** [comment]
Is there an API to hook into the PNG files?

If so, I could easily display the screenshots in the browser with a gallery of all tests or just one screenshot.

**Comment by ArtemGovorov** [comment]
I have found the way to display the screenshot by essentially wrapping it into an HTML page and displaying the HTML document with the `vscode.previewHtml` command.

![vsc](https://cloud.githubusercontent.com/assets/979966/15530755/9ca76c7e-2299-11e6-810b-605beaad59dd.gif)

Available in wallaby extension v1.0.15.

**Comment by thomas-jeepe** [comment]
Thanks :)
