### ISSUE TITLE
angular cli support

### ISSUE THREAD

**Issue by nerumo** [wallabyjs/public#613]
since angular 2 is focusing on the angular cli, I won't use webpack for my project and use angular cli instead. 
How can I make it work to have ng tooling working together with wallaby? The plain angular 2 example project isn't  working because it does not compile sass. And when I think of other features to come (offline template compilation etc.), it would be nice to use the ng commands to support all those features

**Comment by ArtemGovorov** [comment]
I haven't yet spent much time looking into ng-cli as it's still at alpha stage, but I don't think it should be too hard to configure wallaby or extend it via a custom postprocessor like wallaby-webpack to support it. 

> The plain angular 2 example project isn't working because it does not compile sass. And when I think of other features to come (offline template compilation etc.),

Could you please share a sample ng2 project with wallaby config that you have issues with?

**Comment by ArtemGovorov** [comment]
BTW, here is [the config sample](https://gist.github.com/ArtemGovorov/2d5a6535316afa7ff12e0295d2c2f7d5) that should work for an ng-cli generated project. It doesn't use Webpack, it uses SystemJs.

**Comment by nerumo** [comment]
Here's the project. The problem with the tests are that in the angular components I have to reference the css files and ng cli is compiling the sass for me. It will only fail with tests that resolve the css (component builder tests), JS only code works properly.
I my project I already used your (btw great) example configuration.

[TimeShepherd.Client.zip](https://github.com/wallabyjs/public/files/284676/TimeShepherd.Client.zip)

**Comment by ArtemGovorov** [comment]
This one can be easily supported by adding the one line [wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) for your `scss` files:

```javascript
    preprocessors: {
      ...
      'src/app/**/*.scss': file => require('node-sass').renderSync({data: file.changeExt('css').content || ' '}).css.toString()
    },
```
+
```
npm i node-sass --save-dev
```
I'm doing a couple of things: 
- renaming the file from `scss` to `css` by calling `file.changeExt('css')` (that just returns the file so I can chain `.content` call); 
- passing a space to the `renderSync` `data` because some of your `scss` files are empty and `node-sass` throws an error if an empty string is passed.

If you have any special options you need to pass to the sass compiler, you may just pass them into the [`renderSync` function](https://github.com/sass/node-sass#usage) used in the preprocessor.

**Comment by ArtemGovorov** [comment]
Also note that if you'd like to have a better performance and nicer stack traces/error reporting, you may use [Electron runner](https://wallabyjs.com/docs/integration/electron.html) instead of the default PhantomJs one.

**Comment by nerumo** [comment]
tried it, get an exception:

wallaby.js started
core v1.0.236
Fri, 27 May 2016 05:59:56 GMT wallaby:project File cache: C:\Users\mb\AppData\Local\Temp\.wallaby\projects\hNW6qlDFtHNvaQOctpHjEfK7RE=\cache
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #0
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #1
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #2
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #3
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #4
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Starting run worker instance #5
Fri, 27 May 2016 05:59:56 GMT wallaby:workers Web server is listening at 9118
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/+dev/dev.component.scss, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/+dev/dev.component.scss
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/+dev/testform/testform.component.scss, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/+dev/testform/testform.component.scss
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/+start/start.component.scss, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/+start/start.component.scss
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/index.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/index.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/model/models.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/model/models.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/model/Container.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/model/Container.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/model/SecondContainer.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/model/SecondContainer.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/index.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/index.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/index.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/index.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/notification.component.spec.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/notification.component.spec.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/notification.component.css, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/notification.component.css
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/notification.component.html, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/notification.component.html
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/notification.service.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/notification.service.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/proxy-configurator.service.spec.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/proxy-configurator.service.spec.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/notification.component.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/notification.component.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/notification/shared/index.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/notification/shared/index.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/proxy-configurator.service.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/proxy-configurator.service.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/testutil/fakerespond.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/testutil/fakerespond.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/proxy-request-options.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/proxy-request-options.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/testutil/index.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/testutil/index.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/testutil/providers.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/testutil/providers.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/shared/validators/number.validator.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/shared/validators/number.validator.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/timeshephard.component.scss, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/timeshephard.component.scss
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/timeshepherd.component.html, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/timeshepherd.component.html
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/timeshepherd.component.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/timeshepherd.component.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/app/timeshepherd.component.spec.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/app/timeshepherd.component.spec.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file src/system-config.ts, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process src/system-config.ts
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File src/system-config.ts is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/systemjs/dist/system-polyfills.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/systemjs/dist/system-polyfills.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/systemjs/dist/system-polyfills.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/reflect-metadata/Reflect.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/reflect-metadata/Reflect.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/reflect-metadata/Reflect.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/systemjs/dist/system.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/systemjs/dist/system.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/systemjs/dist/system.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/zone.js/dist/async-test.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/zone.js/dist/async-test.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/zone.js/dist/async-test.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/zone.js/dist/zone.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/zone.js/dist/zone.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/zone.js/dist/zone.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/es6-shim/es6-shim.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/es6-shim/es6-shim.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/es6-shim/es6-shim.js is not instrumented by core
Fri, 27 May 2016 05:59:56 GMT wallaby:project No instrumented file node_modules/rxjs/bundles/Rx.js, re-instrumenting original file
Fri, 27 May 2016 05:59:56 GMT wallaby:project Preparing to process node_modules/rxjs/bundles/Rx.js
Fri, 27 May 2016 05:59:56 GMT wallaby:project Starting processor pool (if not yet started)
Fri, 27 May 2016 05:59:56 GMT wallaby:project File node_modules/rxjs/bundles/Rx.js is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #0
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #1
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #2
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #3
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #4
Fri, 27 May 2016 05:59:57 GMT wallaby:workers Started run worker instance (immediate) #5
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Running 1 processor(s) for src/app/+dev/dev.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Finished running one processor for src/app/+dev/dev.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set ranges for file [src/app/+dev/dev.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set source map for file [src/app/+dev/dev.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Processing compiled src/app/+dev/dev.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:project Stopping process pool
Failed to execute start operation, TypeError: Cannot read property 'sections' of undefined
From previous event:
  at EventEmitter._.extend.start (C:\Users\mb\.wallaby\core\server.js:16:12226)
  at Object.i.receive (C:\Users\mb\.wallaby\core\server.js:14:1179)
  at WebSocket.<anonymous> (C:\Users\mb\.wallaby\core\server.js:18:26118)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.self._receiver.ontext (C:\Users\mb\.wallaby\core\node_modules\ws\lib\WebSocket.js:682:10)
  at Receiver.opcodes.1.finish (C:\Users\mb\.wallaby\core\node_modules\ws\lib\Receiver.js:391:14)
  at Receiver.expectHandler (C:\Users\mb\.wallaby\core\node_modules\ws\lib\Receiver.js:372:33)
  at Receiver.add (C:\Users\mb\.wallaby\core\node_modules\ws\lib\Receiver.js:87:24)
  at Socket.firstHandler (C:\Users\mb\.wallaby\core\node_modules\ws\lib\WebSocket.js:663:22)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:523:20)
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/shared/notification/index.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/shared/notification/index.ts is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Running 1 processor(s) for src/app/+start/start.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Finished running one processor for src/app/+start/start.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set ranges for file [src/app/+start/start.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set source map for file [src/app/+start/start.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Processing compiled src/app/+start/start.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Running 1 processor(s) for src/app/+dev/testform/testform.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:processor Finished running one processor for src/app/+dev/testform/testform.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set ranges for file [src/app/+dev/testform/testform.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Compiler did not set source map for file [src/app/+dev/testform/testform.component.scss]
Fri, 27 May 2016 05:59:57 GMT wallaby:project Processing compiled src/app/+dev/testform/testform.component.scss
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/index.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/index.ts is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/model/models.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/model/models.ts is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/model/SecondContainer.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/model/SecondContainer.ts is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/model/Container.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/model/Container.ts is not instrumented by core
Fri, 27 May 2016 05:59:57 GMT wallaby:processor No compilers found for src/app/shared/index.ts
Fri, 27 May 2016 05:59:57 GMT wallaby:project File src/app/shared/index.ts is not instrumented by core

Tell me if you need more information to it (wallaby version is the latest for VS2015)

**Comment by nerumo** [comment]
tnx, worked perfectly
