### ISSUE TITLE
Other binary fixture copied incorrectly

### ISSUE THREAD

**Issue by jeromu** [wallabyjs/public#614]
### Issue description or question
Same problem as: #521 , but different extensions:  irx  and apk

### Code editor or IDE name and version

Visual Studio Code (latest)

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Fixed in core v1.0.236. The core is updated automatically within a few minutes during between your wallaby.js restarts, to force the update follow [the instructions in the docs](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by jeromu** [comment]
Running v1.0.237.  I now see the files are copied correctly into the 'original' folder, but the 'instrumented' folder show the files, but are < 1K in size.  I was expecting the files to be the same in both the instrumented and the original folders.

Here's what I'm trying to do: test the file upload functionality of an API, and for that, I need access to a file that I will upload.

 request
      .post('/api/upload')
      .attach('fileToUpload', join(__dirname, '../../../src/test/apis/resources/somefile.apk'))
      .expect('Content-Type', /json/)
      .expect(201)
      .end((err, res) => {
        done(err);
      });

Btw, I'm running on windows, if that makes a difference (are you using some sort of symbolic link?)

**Comment by jeromu** [comment]
Never mind... somehow it is fine now, the 'instrumented' contains the right files.
