### ISSUE TITLE
[Bug]: Atom -- When coverage sidebar decoration clicked, highlight color deepens rather than toggles.

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#617]
#### What happens
When I click a coverage indicator in the sidebar, the highlight color for the missing lines turns a deeper shade of red until it turns completely red, rather than toggle highlight on and off.

#### How to reproduce
1. Start wallaby.
2. Go to a file that has coverage reports.
3. Click the coverage indicator in the sidebar.

#### Example

**0 Clicks**
![image](https://cloud.githubusercontent.com/assets/5240018/15629928/389d1676-24f5-11e6-96cf-9ac870640683.png)

**1 Click**
![image](https://cloud.githubusercontent.com/assets/5240018/15629932/4b9eccd8-24f5-11e6-8091-941d73a90cad.png)

**2 Clicks**
![image](https://cloud.githubusercontent.com/assets/5240018/15629934/57683b44-24f5-11e6-97d3-8f3a4390cfd1.png)

**3 Clicks**
![image](https://cloud.githubusercontent.com/assets/5240018/15629940/64310fe0-24f5-11e6-8090-aa4795f04242.png)

I disabled all my stylesheets and it's still persisting.

Possibly useful information: The theme is Seti-UI

### Wallaby.js configuration file

Irrelevant

### Code editor or IDE name and version

Atom Latest

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment]
Thanks for the detailed report. The issue is fixed and the update is published (should be updated automatically within a few minutes between wallaby restarts).

**Comment by dsifford** [comment]
Thanks!

Just purchased the pro version. Such a slick addition to my workflow. Kudos to you for being awesome! Only thing I need is integration with istanbul (or something I can push out to coveralls) and I'll be set!

**Comment by ArtemGovorov** [comment]
Thanks! 

>  Only thing I need is integration with istanbul (or something I can push out to coveralls)

We are planning to add some coverage reports, so you may want to subscribe to the feature request https://github.com/wallabyjs/public/issues/38 to get an update when it's ready.

**Comment by dsifford** [comment]
Excellent!

Thanks so much.
