### ISSUE TITLE
[atom] license prompt not responding

### ISSUE THREAD

**Issue by GabiGrin** [wallabyjs/public#618]
### Issue description or question
Entering license in atom doesn't do anything, no errors, no confirmation. I'm entering the correct part of the license (company seat).

Tried re-installing the atom plugin and nothing, neither activating from the yellow popup, or from the `command palette -> wallaby js` license doesn't work

Any ideas?
This recreates on another computer with a different license, also on Atom, thus the public issue.

### Code editor or IDE name and version
Atom v1.7.4

### OS name and version
OSX 10.11.3

**Comment by ArtemGovorov** [comment]
Just tested and license activation works for me on OSX in Atom 1.7.4. 

Please send me (to hello@wallabyjs.com) the company seat key that doesn't work for you (the part `Key #xxxxx:` is sufficient if you have it, or the full key you are trying to enter if you don't have the `Key #xxxxx:` part) and I'll sort it out for you. The most likely reason is that the key you are trying to enter is not a valid 'Freedom' or Atom key, but for example an IntelliJ platform one.
