### ISSUE TITLE
wallaby.json should support exclusion path

### ISSUE THREAD

**Issue by pgdesjardins** [wallabyjs/public#62]
I'm testing wallaby with cg-angular generator.
cg-angular generates spec files in the same folder as the related object.
it would be nice if wallaby.json allowed for path exclusion in the files array.
It think node golb already has this kind on notation.

ex:

"files": [
        "**/*.js",
        "!**/*-spec.js"
    ],

    "tests": [
        "tests/**/*-spec.js"
    ]

**Comment by ArtemGovorov** [comment]
Agreed, will be nice to have.
As you probably already know, for now you can exclude files by specifying [file objects](https://github.com/wallabyjs/public#file-object) instead of strings and using `ignore: true` flag: `{ "pattern": "src/**/*-spec.js", "ignore": true }`

**Comment by pgdesjardins** [comment]
RTFM is often the answer. Right?
Thanks for that.

Thank you for this great product.
I'll have more than a few tester for you when the visual studio version is
out.

On Sun, Apr 5, 2015 at 8:32 PM, Artem Govorov <notifications@github.com>
wrote:

> Agreed, will be nice to have.
> As you probably already know, for now you can exclude files by specifying file
> objects <https://github.com/wallabyjs/public#file-object> instead of
> strings and using ignore: true flag: { "pattern": "src/**/*-spec.js",
> "ignore": true }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wallabyjs/public/issues/62#issuecomment-89873804>.
>



-- 
Gabriel Desjardins
desjardins.gabriel@gmail.com

**Comment by ArtemGovorov** [comment]
@pgdesjardins thanks! Visual Studio version will be out in few weeks.

**Comment by ArtemGovorov** [comment]
Added the way to invert `ignore` flag by using `!` as you have been suggesting. The feature description is in file object [`ignore` property section](https://github.com/wallabyjs/public#file-object).

**Comment by LPCmedia** [comment]
does this apply to spec files that are processed with webpack ?

**Comment by ArtemGovorov** [comment]
@LPCmedia This applies to everything listed in the `files`/`tests` lists.
