### ISSUE TITLE
Passing environment variables in atom-wallaby

### ISSUE THREAD

**Issue by rainydio** [wallabyjs/public#622]
I wonder why environment variables available to atom are not passed to wallaby server. For example when working with `aws-sdk` it is trying to locate `$HOME/.aws/credentials`, but is unable to do so. As far as I can see it's a simple change in `atom-wallaby/wallby/client.js` when forking server.js:

```diff
- env: _.extend({
+ env: _.extend({ }, process.env, {
    PATH: (i ? i + s.delimiter : "") + (a ? "" : "/usr/local/bin")
- }, {}),
+ }),
```

Then `aws-sdk` can simply pick my credentials from environment.

----

```js
"use strict";

module.exports = function (wallaby) {
	const specs = "test/**/*.spec.js";

	return {
		debug: false,

		files: [
			{ pattern: "node_modules/**/*", ignore: true },
			{ pattern: "wallaby.js", ignore: true },
			{ pattern: specs, ignore: true },
			{ pattern: "**/*.js", instrument: true },
			{ pattern: "**/*", instrument: false },
		],
		tests: [
			{ pattern: specs },
		],
		compilers: {
			[specs]: wallaby.compilers.babel(),
		},
		testFramework: "ava",
		env: {
			type: "node",
			runner: "env",
			params: { runner: "node" },
		},
	};
};
```

Atom 1.7.4, Ubuntu 16.04, Node 6.2.0

**Comment by ArtemGovorov** [comment]
The reason why we don't pass Atom's `env` to wallaby server is because the plan was to encourage users to set up the `env` right in the wallaby config, so it's more explicit for all members of your team and the same config works the same way across all editors that we support (and a CI server in future).

In your wallaby config you may just do
```javascript
"use strict";

module.exports = function (wallaby) { 
  process.env['param'] = 'value';
  ...
}
```

Would that be enough?

**Comment by ArtemGovorov** [comment]
Having said that, I can see how passing the editor `env` be helpful in your case and many other cases. And it something in the `env` needs to be changed, then it can be done as I have indicated. So I've changed the default implementation as you've suggested. The update will be installed automatically with core v1.0.239 within a few minutes between your wallaby restarts, you may also force the update [like described here](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by rainydio** [comment]
Thanks a lot... You caught me in the middle of writing wall of text.

**Comment by ArtemGovorov** [comment]
> You caught me in the middle of writing wall of text.

Thanks and sorry about that, I should have mentioned that we were going to consider your example and the suggestion.
