### ISSUE TITLE
[Jest] - Tests fail in atom wallaby, but not through the CLI or with TravisCI

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#623]
### Issue description or question

Starting within the last few hours, a bunch of tests are being reported as failing, when they aren't actually failing.

Here's a small test that is failing for example:

```ts
// Pagination.ts
export default function paginate(rows: Array<any>, visibleRows: number, currentPage: number) {
    return rows.filter((uid, i: number) =>
        (visibleRows * currentPage) <= i && i < (visibleRows * currentPage + visibleRows)
    );
}
```

```
// Pagination-test.ts
jest.unmock('../Pagination.ts');

import paginate from '../Pagination';

const rows = Array.from(Array(100).keys());

describe('Paginate Function', () => {
    it('should paginate correctly', () => {
        expect(paginate(rows, 10, 5)).toEqual([50, 51, 52, 53, 54, 55, 56, 57, 58, 59]);
        expect(paginate(rows, 3, 2)).toEqual([6, 7, 8]);
        expect(paginate(rows, 1, 39)).toEqual([39]);
        expect(paginate(rows, 100, 4)).toEqual([]);
        expect(paginate(rows, 0, 10)).toEqual([]);
    });
});
```

Message (for every expect line): `Expected undefined to equal` [my assertion]

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'wp-content/**/*.tsx',
            'wp-content/**/*.ts',
            'typings/**/*.d.ts',
            '!wp-content/**/__tests__/*',
        ],
        tests: [
            'wp-content/**/__tests__/*-test.tsx',
            'wp-content/**/__tests__/*-test.ts',
        ],
        env: {
            type: 'node',
            runner: 'node',
        },
        testFramework: 'jest',
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure({
                'scriptPreprocessor': 'jestPreprocessor.js',
                'testFileExtensions': [
                  'ts',
                  'tsx',
                  'js',
                ],
                'moduleFileExtensions': [
                  'js',
                  'ts',
                  'tsx',
                  'json',
                ],
                'unmockedModulePathPatterns': [
                  'react',
                  'react-dom',
                  'react-addons-test-utils',
                  'enzyme',
                  'sinon',
                ],
            });
        }
    };
};

```

### Code editor or IDE name and version

Atom latest

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment]
What is your `jest-cli` version?

**Comment by dsifford** [comment]
```sh
$ jest --version
v12.1.1
```

**Comment by ArtemGovorov** [comment]
> While typing the message out, I just realized that the extension it's using a .js when it's actually a TypeScript file. Odd.

This is normal. Wallaby compiles `.ts` files and renames them by default.

The only wallaby change that could affect your tests is that we [now are passing Atom `env` to wallaby](https://github.com/wallabyjs/public/issues/622) so it may be something in your Atom `env` that breaks the tests.

I'll create your sample locally now to see if I can reproduce it and what's going on.

**Comment by dsifford** [comment]
Sounds great. Happy to help troubleshoot if you need me to.

**Comment by ArtemGovorov** [comment]
Please try doing this in your config:
```javascript
module.exports = function (wallaby) {
  process.env = {PATH: process.env.PATH};
  ...
}
```
This should get rid of everything but PATH `env` variable passed from your editor, so we could test the assumption that passing the editor `env` has broken the tests.

**Comment by dsifford** [comment]
No dice. 

Tried removing all jest's cache and restarting atom as well and still no luck there either.

**Comment by ArtemGovorov** [comment]
Ok, thanks for checking.
Could you please share your `tsconfig.json` file and `jestPreprocessor.js` file?

**Comment by ArtemGovorov** [comment]
And also `package.json` file.

**Comment by ArtemGovorov** [comment]
Perhaps it's be easier if you could attach a project with that one source file and one test that is failing, so I could try it faster than trying to create it it from the scratch.

**Comment by dsifford** [comment]
The project is open source. Here's a link: https://github.com/AcademicLifeInEM/ALiEMU

**Comment by ArtemGovorov** [comment]
Great, thanks for sharing, trying it now.

**Comment by dsifford** [comment]
Here's another project that is also failing: https://github.com/dsifford/academic-bloggers-toolkit

**Comment by dsifford** [comment]
The failure messages from the other project:

![image](https://cloud.githubusercontent.com/assets/5240018/15697186/cddd3648-2785-11e6-9dae-621a1a80fff1.png)

**Comment by ArtemGovorov** [comment]
Ok, let's do one step at a time.
For this project: https://github.com/AcademicLifeInEM/ALiEMU, changing the `Pagination-test.ts` as follows (removing `.ts` extension from the `jest.unmock` argument) makes it work:
```
jest.unmock('../Pagination');
...
```
I'm not sure how/if it was working before, I checked a few wallaby versions back and they all fail for the same reason. Wallaby renames (and always renamed) `.ts` files to `.js` when compiling, so it makes sense. Omitting the extension also works fine with plain `jest-cli`.

Checking the other project https://github.com/dsifford/academic-bloggers-toolkit now.

**Comment by ArtemGovorov** [comment]
For the other project https://github.com/dsifford/academic-bloggers-toolkit, I was able to reproduce the issue, but my previous suggestion fixes it for me:
```javascript
module.exports = function (wallaby) {
  process.env = {PATH: process.env.PATH};
  ...
}
```

I'll be looking into why exactly does it happen, in a meantime, could you please try my suggestion for this project to see if it works for you for this project?

**Comment by dsifford** [comment]
Confirmed that setting `process.env = { PATH: process.env.PATH }` works for me too!

I feel a bit silly Re: the pagination file issue.. The sinon issue in the same project was due to the PATH thing.

Thanks for the help!

**Comment by ArtemGovorov** [comment]
Thanks for the update. 
I have found out what the issue with importing modules was:
- with our recent changes, wallaby started to pass Atom `env` to node test runner,
- one the `env` variables that Atom is passing is `NODE_PATH` pointing to the Atom folder, and Jest specifically didn't like it.

I have fixed the issue and published the update. It'll be installed automatically within a few minutes between your wallaby.js restarts. You may also [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). Please note that after this specific update is installed either way, you'll need to restart Atom. After the update you may remove the `process.env = { PATH: process.env.PATH }` from your config.

**Comment by dsifford** [comment]
Sounds great! Thanks so much for the help.
