### ISSUE TITLE
How do ge the path to the json or yaml file (resource?)

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#626]
Hello, I store my test cases in the YAML file. How can I get the path to the file if I need to load it via YAML.load(**path**)? I have included yaml files in my wallaby config as

```
tests: [
      { pattern: 'client/**/*.yaml', instrument: true, load: false, ignore: false },
      "client/src/tests/*.ts"
    ],
```

**Comment by tomitrescak** [comment]
Moreover, how can make that test re-rerun when I change that file> When loaded as absolute path, the changes do not trigger re-run.

**Comment by ArtemGovorov** [comment]
> YAML.load(path)

What module is this? Does it only accept absolute paths?

> how can make that test re-rerun when I change that file

Currently there's no way to always automatically do it, you may use the `Run project tests` command (from the Palette or via the `Cmd+Shift+T P` shortcut).

**Comment by tomitrescak** [comment]
@ArtemGovorov thatnks for your answer. Yes, looks like YAML only accepts only absolute paths, so would be great if I could somehow automatically create that path.

**Comment by ArtemGovorov** [comment]
> Yes, looks like YAML only accepts only absolute paths

Then I guess the question is not wallaby specific, it's more a question how you'd like to load the file in any test runner, for example plain mocha.

Perhaps you may just use:
```javascript
YAML.load(require('path').join(__dirname, 'path to .yaml file relative to the dir with this file'))
```
? It should work in all test runners.

**Comment by tomitrescak** [comment]
That worked. I asked since I did not know if Wallaby has anything extra needed in the bucket. Thanks for your help!
