### ISSUE TITLE
ReferenceError: Can't find variable: Symbol

### ISSUE THREAD

**Issue by jhhoff02** [wallabyjs/public#627]
### Issue description or question
Hello Artem! Your dedication to Wallaby support is always appreciated. 
I have a similar issue as described in [this] (https://github.com/wallabyjs/public/issues/424#issuecomment-175602978) comment/post, except I am not using Babel 6. I'm using AngularJS 2.0 with TypeScript 1.8.2 and ES6. When I startup Wallaby, all my tests pass. When I change 
`expect(foo).toEqual("foo");` to `expect(foo).toEqual("fo");` the test fails (as it should). But the "ReferenceError: Can't find variable: Symbol" error appears. 
When I change it back to `expect(foo).toEqual("foo");` the "Expected 'foo' to equal 'fo' " error goes away, but the Reference Errors remain and my tests are no longer passing like they do when I restart Wallaby. 
I'm assuming this is not an issue with Wallaby, but probably a similar polyfill issue like in the link above. Any ideas?
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'spec-bundle.js',
        'src/**/*spec.js'
    ]
});

module.exports = function (w) {

    return {
        files: [
            {pattern: 'spec-bundle.js', load: false},
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'src/**/*spec.ts', ignore: true}
        ],

        tests: [
            { pattern: 'src/**/*spec.ts', load: false }
        ],

        testFramework: "jasmine",

        compilers: {
            '**/*.ts': w.compilers.typeScript({
                emitDecoratorMetadata: true,
                experimentalDecorators: true
            })
        },

        postprocessor: webpackPostprocessor,

        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio 2015
Visual Studio Code v0.10.x

### OS name and version

Windows 7

**Comment by jhhoff02** [comment]
I have figured out the issue, in my spec-bundle.js file, 
`var testing = require('angular2/testing'); 
var browser = require('angular2/platform/testing/browser');`
should have been:
`var testing = require('@angular/core/testing'); 
var browser = require('@angular/platform-browser/testing/browser_static');`
with the new Angular2 update. Just posting in case anyone has similar issues :)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
