### ISSUE TITLE
Retrieving purchased license

### ISSUE THREAD

**Issue by lupesko** [wallabyjs/public#629]
Hello!

I have purchased a Wallaby.js license for WebStorm in Feb 2016 - and it all worked great!
I have just upgraded WS to 2016.1, but can't find the license key... I could not find a way to retrieve it in your web site.

Can you please help out?

Details: account email should be lupesko at gmail dot com or lupesko at amazon dot com

### Code editor or IDE name and version

WebStorm 2016.1

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Hello, 
I did a quick search by the email, but couldn't find anything.
Please send us an email to hello@wallabyjs.com with as many details as possible (email, name, country of purchase, payment type) and we'll sort it out for you.

**Comment by ArtemGovorov** [comment]
You may also try finding your license key by opening `~/Library/Caches/`, then `WebStormX` subfolder there, where `X` is your previous version where you had wallaby.js working, the `wallaby` subfolder and there should be `key.lic` file containing your license key in there.

**Comment by lupesko** [comment]
Thanks! that worked...
