### ISSUE TITLE
Support emacs

### ISSUE THREAD

**Issue by map7** [wallabyjs/public#63]

**Comment by jazen** [comment]
:+1:

**Comment by Trevoke** [comment]
Also, 👍 and such, since.. I dunno.. I should, Github doesn't do voting yet, and all.

**Comment by BelfordZ** [comment]
👍

**Comment by reywright** [comment]
make some kickstarter / bountysource for adding support for this and I'll contribute.

**Comment by nikna** [comment]
:+1:

**Comment by miwaniak** [comment]
+1

**Comment by i-have-no-name** [comment]
Hey. I'am a fan of wallaby, but recently I switched to emacs and as I know there were no plans to support emacs.
I wrote small [package](https://github.com/i-have-no-name/jest-interactive-mode), for now it's only support immediate results in window. I am planning to make more other stuff.
Maybe for someone it could be usefull

**Comment by ArtemGovorov** [comment]
Wallaby 2 is live 🚀 https://wallabyjs.com/blog/wallaby-2.html, and it can now be used with [any editors, including Emacs](https://wallabyjs.com/docs/intro/standalone/).
