### ISSUE TITLE
Inline errors and logs in Visual Studio Code

### ISSUE THREAD

**Issue by Merott** [wallabyjs/public#630]
### Issue description or question

I've noticed there are no inline errors or logs in Visual Studio Code. Are there editor limitations that prevent this feature?

### Code editor or IDE name and version

Visual Studio Code v1.1.1

### OS name and version

OS X

**Comment by ArtemGovorov** [comment]
Correct, there's the VS Code limitation that blocks the feature: https://github.com/wallabyjs/public/issues/437. Feel free to subscribe and vote for the feature in the VS Code repository.
