### ISSUE TITLE
Different screen management options in Atom

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#634]
Hi, I love using wallaby in Atom. It's as good as it gets.
I have one small suggestion though. In current screen configuration, wallaby is positioned in the bottom panel in the separate pane. On wide monitors, this tends to take a lot of space.

What would be great is to have an option to put it next to the Linter if it is detected. 
By modifying the DOM of Atom IO managed to do exactly as I needed it and now I have all the info close to everything and compact as can be.

It would be great to simply add it to the right and add a resized so that we can set the width of both. Another option it to stack it in tabs.

![screen shot 2016-06-08 at 1 58 38 pm](https://cloud.githubusercontent.com/assets/2682705/15882398/812b784e-2d81-11e6-8e6a-e11556dcec6e.png)

**Comment by ArtemGovorov** [comment]
It's a good idea, but I don't think it's possible via [Atom extensions API](https://atom.io/docs/api/v1.8.0/Workspace#instance-addBottomPanel), only a panel position and stacking order can really be controlled. 

While the hack with finding if there're some other panels and placing the wallaby panel into an existing panel to the right (or an existing panel to the wallaby panel to the left) is possible, I'm not sure if it's a good idea to implement it this way for a couple of reasons.

First, it may be ok with the linter panel, but other plugins' panels may not look that great when taking their space, so it needs to be optional. Second, as a hack using some internals, it may break when Atom changes their implementation details.

Considering this, I'd suggest for now coding the DOM modification that you have mentioned and placing it into [your Atom init script](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/). It's be awesome if you could share the script so it could be useful for others as well.

**Comment by tomitrescak** [comment]
I got couple now:
First one replaces new line symbols with new lines
Second positions wallaby to the right pane

```coffee script
atom.commands.add 'atom-text-editor', 'wallaby:replace-new-lines', ->
  p = document.querySelector('section.error section.header');
  if p
    p.innerText = p.innerText.replace(/\\n/g, '\n')

atom.commands.add 'atom-text-editor', 'wallaby:move-right', ->
  p = document.querySelector('div.wallaby-panel-view');
  if p


    container = document.querySelector('atom-panel-container.right');
    resizer = document.createElement 'div'
    resizer.className = 'resizer';
    resizer.style.width = '5px';
    resizer.style.cursor = 'ew-resize';

    container.insertBefore resizer, container.childNodes[0]


    c = p.parentNode.removeChild p
    right = document.querySelector('atom-panel.right');
    right.style.display = 'inherit';
    right.style.width = '250px';

    content = document.querySelector('atom-panel.right');
    content.appendChild(p)

    # resizer
    xPosition = 0;
    initialWidth = 0;

    resizeTreeView = (e) ->
      diff = (e.clientX - xPosition) * -1;
      diff = initialWidth + diff;
      if diff < 50
        diff = 50
      if diff > 800
        diff = 800
      right.style.width = diff + 'px';
      #nada

    resizeStarted = (e) ->
      xPosition = e.clientX;
      initialWidth = parseInt(right.style.width.substring(0, right.style.width.length - 2));
      document.addEventListener('mousemove', resizeTreeView)
      document.addEventListener('mouseup', resizeStopped)

    resizeStopped = (e) ->
      document.removeEventListener('mousemove', resizeTreeView)
      document.removeEventListener('mouseup', resizeStopped)

    resizer.onmousedown = resizeStarted;
```

**Comment by tomitrescak** [comment]
Problem there is that I can't make wallaby stretch to the whole page.
