### ISSUE TITLE
Error in Atom tutorial: Test run failure: Failed to create worker instance  

### ISSUE THREAD

**Issue by rbrtrbrt** [wallabyjs/public#635]
### Issue description or question
Just installed Wallaby in Atom 1.8. Cloned the 'calculator'-repo for the tutorial, and opened it in Atom.
When starting Wallaby from the Panel, 
* first only a spinner was shown in the status-bar, and nothing seems to happen.
* looking in the dev-console in Atom, I see several errors saying "phantomjs-node: you don't have phantomjs installed"
  - i did have phantomjs installed: both the globally installed version and the one that comes with wallaby are 1.9.8, and both run fine when started from the command line.
* followed the instructions for updating the Wallaby core (removing `wallaby` directory from ~/.atom/packages/atom-wallaby).
* restarted atom, update of core succeeded.
* now, when starting wallaby from the panel in the calculator project of the tutorial, there are no more errors about phantomjs not being installed. **But I get the error**: `Test run failure: Failed to create worker instance` in the panel, and the following output 6 times (for workers 0-5:
```
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Object._createPhantomInstance (/Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:15:28602)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Object.wrapper [as create] (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/lodash/index.js:2914:56)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at /Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:17:22633
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Function.promise (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:635:9)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Object.getWorker (/Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:17:22352)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Object.f (/Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:17:10481)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Object.o (/Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:15:27709)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at /Users/robert/.atom/packages/atom-wallaby/wallaby/server.js:16:12064
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at _fulfilled (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:787:54)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at self.promiseDispatch.done (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:816:30)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at Promise.promise.promiseDispatch (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:749:13)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at /Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:509:49
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at flush (/Users/robert/.atom/packages/atom-wallaby/wallaby/node_modules/q/q.js:108:17)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at _combinedTickCallback (internal/process/next_tick.js:67:7)
/Users/robert/.atom/packages/atom-wallaby/wallaby-atom/index.js:14 Wallaby Console:   at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Wallaby.js configuration file
straight from the tutorial repo:
```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};

```

### Code editor or IDE name and version

Atom v1.8

### OS name and version

OSX 10.11.5

**Comment by ArtemGovorov** [comment]
It looks like [this issue](https://github.com/wallabyjs/public/issues/601). 

Could you please 
- check if there's a `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/lib/phantom/bin/phantomjs` file,
- check if the [value of the `global.wallaby. phantomPath`](https://github.com/wallabyjs/public/issues/601#issuecomment-220505311) is the same as the path above.

If you have phantomjs installed globally (or locally), the workaround would be to tell wallaby.js in its config:
```javascript
module.exports = () => {
  return {
    ...
    env: {
      runner: 'phantomjs', // or a path to installed phantomjs
    }
  };
};
```

**Comment by rbrtrbrt** [comment]
Thank you for you quick response!

- `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/lib/phantom/bin/phantomjs` does not exist. The closest I get is `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/lib`, which only contains `location.js` and `phantomjs.js`. (There *is* a `phantomjs` executable in `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/bin`, which is symlinked to by `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/.bin/phantomjs`) 
- The value of `global.wallaby.phantomPath` is `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/lib/phantom/bin/phantomjs` (i.e. same as the path you asked for, but different from where my wallaby package has it's copy of the phantomjs executable)
- adding the path to an installed phantomjs to the `wallaby.js` file does not prevent the error `Test run failure: Failed to create worker instance`.

Could it be that finding phantomjs is no longer part of the problem, i.e. the failure to create a worker instance is a different problem?

**Comment by ArtemGovorov** [comment]
Thanks for checking! 

> The value of global.wallaby.phantomPath is `/Users/robert/.atom/packages/atom-wallaby/node_modules/phantomjs/lib/phantom/bin/phantomjs` (i.e. same as the path you asked for, but different from where my wallaby package has it's copy of the phantomjs executable)

This is definitely an issue. If you add `debug: true` to your config:
```javascript
module.exports = () => {
  return {
    ...
    debug: true
  };
};
```
then you should be able to see more details about the error in the Dev Tools console, and it may still be that `phantomjs-node: you don't have phantomjs installed` error.

> adding the path to an installed phantomjs to the wallaby.js file does not prevent the error `Test run failure: Failed to create worker instance`

This is strange, try [installing and configuring phantomjs 2 like described here](https://wallabyjs.com/docs/integration/phantomjs2.html) to see if it helps.

**Comment by ArtemGovorov** [comment]
BTW, I have rectified the phantomjs path resolution a bit (the paths mismatch) and published the new version that may actually fix the issue. Could you please update your wallaby.js package for atom (not the core, but the full package via Atom package updates)?

**Comment by rbrtrbrt** [comment]
Yes, that worked.
I reinstalled the entire Wallaby package, and restarted Atom. 
Wallaby is now starting just fine, and showing nice green squares.

I did not need to install phantomjs2. But if I encounter new problems that seem related, I will.
Thank you.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update and for your help!
