### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by ashishpreeti** [wallabyjs/public#636]
### Issue description or question
I am trying to use wallaby with angular 1.4.4. I get error "ReferenceError: Can't find variable: require" and when I include node in the wallaby configuration, I am gettting "TypeError: module is not a function"
### Wallaby.js configuration file
```javascript
{
  "files": [
    { "pattern": "lib/angular/angular.min.js" , "instrument": false },
    { "pattern": "lib/angular/angular-resource.min.js", "instrument": false },
    { "pattern": "lib/angular/angular-mocks.js","instrument": false },
    { "pattern": "lib/angular/angular-route.min.js","instrument": false },
    { "pattern": "lib/bootstrap/ui-bootstrap-tpls.min.js","instrument": false },
    "src/**/*.js"
  ],
  "tests": [
    "spec/**/*.js"
  ]
}
```
```javascript
require('../movie-app/app');
angular.module('movieCore', ['ngResource'])
	.factory('PopularMovies', function($resource) {
		var token = 'teddybear'; // TBC
		return $resource('popular/:movieId', { movieId: '@id' }, {
			update: {
				method: 'PUT',
				headers: { 'authToken': token }
			}
		});
	});

```

### Code editor or IDE name and version
IntelliJ Idea 2016.1.3
### OS name and version
OSX - Yosemite 10.10.5

**Comment by ashishpreeti** [comment]
Code at https://github.com/ashishpreeti/movie-app.git

**Comment by ArtemGovorov** [comment]
> `ReferenceError: Can't find variable: require`
So when you do:
```javascript
require('../movie-app/app');
```
how do you expect it to work in your real app? Your repo doesn't seem to include any Webpack/Browserify configuration, neither your karma config file.

**Comment by ArtemGovorov** [comment]
And your app is clearly a browser angular app, so using node environment to test it is not an option.

**Comment by ashishpreeti** [comment]
I was trying to make wallaby work in our larger application which uses browserify. That application uses require in lots of places including the main.js which bootstraps the application. I was trying to do the same here in a smaller application to prove that I can make require work.

**Comment by ashishpreeti** [comment]
BTW - Thank you for the prompt reply. Wallaby is great product and I am only a step away from buying it! :-)

**Comment by ArtemGovorov** [comment]
> larger application which uses browserify. That application uses require in lots of places including the main.js which bootstraps the application.

You may then configure wallaby to [use browserify like described here](https://wallabyjs.com/docs/integration/browserify.html). There's a also a sample referenced in the docs article. As for the `main.js` file, you may configure it to be an entry like [described in the docs](https://wallabyjs.com/docs/integration/browserify.html#entry-patterns). Try configuring wallaby for your repo as described in the docs, commit your changes and let me know if you hit any issues, I'll try to help.

**Comment by ashishpreeti** [comment]
Hi Artem,
 I have created another project in github https://github.com/ashishpreeti/sampleapp.git
This works fine with karma in intellij. But, I cannot still get wallaby to work. I still get problems with "ReferenceError: Can't find variable: require" 
I tried reading the links you have provided but, still couldn't get this working. Can you help?

**Comment by ArtemGovorov** [comment]
Thanks for the repo. As [specified in the docs](https://wallabyjs.com/docs/integration/browserify.html), you need to set `load: false` flag to your files and tests, because otherwise they are loaded via `script` tags before browserify has a chance to build them. You also don't need to specify all of your files as `entryPatterns`, as [the docs say](https://wallabyjs.com/docs/integration/browserify.html#entry-patterns): only your tests and files you'd like to load before any of your test.

So the config like this should work for you:

```javascript
var wallabify = require("wallabify");

var wallabyPostprocessor = wallabify({});
module.exports = function () {
  return {
    "files": [
      {pattern: 'app/src/**/*.js', load: false}
    ],
    "tests": [
      {pattern: 'app/tests/*.js', load: false}
    ],
    postprocessor: wallabyPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  }
};
```

**Comment by ashishpreeti** [comment]
Hi Artem, Thanks that work. But, now I was trying to apply the same in an angular app at https://github.com/ashishpreeti/movie-app.git
and I am getting following error. I tried a few things but, I couldn't make it work

TypeError: '[object Object]' is not a function (evaluating 'module('movieApp')')
	at spec/movie-app/results.controller.spec.js:33

**Comment by ArtemGovorov** [comment]
Hi, thanks for the update. As I have mentioned:
> you need to set `load: false` flag to your files and tests, because otherwise they are loaded via script tags

but in your angular app, you are not `require(...)`-ing angular (and perhaps some other libs), but relying on them being loaded globally. For such libs, you actually want them to be loaded via script tags into the sandbox, so need to remove `load: false` for:
```
          {pattern: "lib/angular/angular.min.js", load : false},
          {pattern: "lib/angular/angular-resource.min.js", load : false},
          {pattern: "lib/angular/angular-mocks.js", load : false},
          {pattern: "lib/angular/angular-route.min.js", load : false},
          {pattern: "lib/bootstrap/ui-bootstrap-tpls.min.js", load : false},
```

**Comment by ashishpreeti** [comment]
Hi tried few things for angular and other dependencies as below
1. {pattern: 'node_modules/angular/angular.js', load : true},

2. {pattern: 'node_modules/angular/angular.js'},

3. 'node_modules/angular/angular.js', 

I got rid of lib folder and used npm. But, I still get error 
"TypeError: '[object Object]' is not a function (evaluating 'module('movieApp')')
	at spec/movie-app/results.controller.spec.js:33"

I also tried,
beforeEach(function () {
	angular.mock.module('movieApp');
});
 instead of
beforeEach(module('movieApp'));
but, then I get the below error,

 Error: [$injector:modulerr] Failed to instantiate module movieApp due to:
	Error: [$injector:nomod] Module 'movieApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I have pushed the recent changes at https://github.com/ashishpreeti/movie-app.git

**Comment by ArtemGovorov** [comment]
The error `TypeError: '[object Object]' is not a function (evaluating 'module('movieApp')')` makes sense, because `module` in this context is the current module variable from browserify CommonJs.

Rewriting it to `angular.mock.module('movieApp');` causes the `Failed to instantiate module movieApp` because your app files are not loaded yet (they have `load:false`) and nothing in your tests `require` them, so browserify doesn't include them in a bundle either.

Perhaps I'm misunderstanding something, but your example app is not using CommonJs at all, neither your karma config in the app, so to make your tests run you don't need to configure wallaby to use browserify, and this config should work for you:

```javascript
module.exports = function () {
  return {
      "files": [
          {pattern: 'node_modules/angular/angular.js', instrument: false},
          {pattern: 'node_modules/angular-resource/angular-resource.js', instrument: false},
          {pattern: 'node_modules/angular-route/angular-route.js', instrument: false},
          {pattern: 'node_modules/angular-mocks/angular-mocks.js', instrument: false},
          {pattern: 'node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js', instrument: false},
          {pattern: "src/**/*.js", load : true}
      ],
      "tests": [
          {pattern: "spec/**/*.js", load : true}
      ]
  }
};
```

If you'd like to use browserify for your app/tests, then the app itself should be written in a way that allows browserify to build the bundle. Perhaps it's easier if you first create a working browserify build for your app and/or karma config using browserify, and then let me know if you have issues configuring it, given the knowledge you already possess from the [previous sample app](https://github.com/ashishpreeti/sampleapp.git).

**Comment by ashishpreeti** [comment]
Thanks. That works. I will create a browserify build karma config in our production code and try to make it work.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
