### ISSUE TITLE
Unknown plugin "syntax-async-generators" specified in "base"  - VSCode setup

### ISSUE THREAD

**Issue by nathfy** [wallabyjs/public#643]
### Issue description or question
Trying to setup wallby.js on VSCode with mocha based tests, seems to not be able to find the babel plugins. Folders are like this:
![image](https://cloud.githubusercontent.com/assets/1806224/15962643/78b40576-2f04-11e6-924e-524546374af9.png)

Modules for babel are in node_modules folder...
![image](https://cloud.githubusercontent.com/assets/1806224/15962740/1e3b6d36-2f05-11e6-8122-83acf06f95ea.png)

Getting this:
```
[Info] Fri, 10 Jun 2016 10:58:56 GMT wallaby:project Error: Failed to run compilers on src/app.js, ReferenceError: Unknown plugin "syntax-async-generators" specified in "base" at 1, attempted to resolve relative to "src"
[Info]   at f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:220:17
[Info]   at Array.map (native)
[Info]   at Function.normalisePlugins (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:196:20)
[Info]   at OptionManager.mergeOptions (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:317:36)
[Info]   at OptionManager.init (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\options\option-manager.js:506:10)
[Info]   at File.initOptions (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\index.js:243:89)
[Info]   at new File (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\file\index.js:159:72)
[Info]   at Pipeline.transform (f:\websites\lookedaftercall\beta\react\node_modules\babel-core\lib\transformation\pipeline.js:49:16)
[Info]   at Array.forEach (native)
[Info]   at emitTwo (events.js:100:13)
[Info]   at process.emit (events.js:185:7)
[Info]   at handleMessage (internal/child_process.js:718:10)
[Info]   at Pipe.channel.onread (internal/child_process.js:444:11)
[Info]   at C:\Users\nathan\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.15\wallaby\server.js:17:1948
```

Any idea how I can resolve/what I'm doing wrong in the config

### Wallaby.js configuration file
```javascript
module.exports = (wallaby) => {
  return {
    files: [
      //{pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      'src/**/*.js'
    ],

    tests: [
      'test/**/*spec.js'
    ],

    debug: true,

    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babelrc: false,
        presets: ['es2015', 'react', 'stage-2'],
        plugins: ['syntax-async-generators', 'add-module-exports', 'transform-class-properties']
      })
    },

    setup: function() {
          require('./test/.setup.js');
    }
  };
};
```
### Code editor or IDE name and version

Visual Studio Code v1.2.0
### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
This was a folder structure related bug that is not fixed (and published) in core v1.0.245. You may force the core update as [described here](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and, for this specific update you'll need to restart your editor as well after the core update.

Please note that even after the fix your config may still not work (for a different reason though). You are using `require('./test/.setup.js');` in your `setup` function, but the `test/.setup.js` is not specified in your `files` list. Also, your config is for browser environment (not for [node.js environment](https://wallabyjs.com/docs/integration/node.html)), so `require` will not work anyway. If you're using  browser environment for testing (as I can guess because you have karma config), then you probably are using Webpack or Browserify. You may have a look how to configure them in the corresponding docs section ([Webpack](https://wallabyjs.com/docs/integration/webpack.html), [Browserify](https://wallabyjs.com/docs/integration/browserify.html)), apart from the rest, you'll need to configure `entryPatterns`.

**Comment by nathfy** [comment]
Hi @ArtemGovorov - many thanks for the help and pointers, it's working now so in the interests of others looking configs here is mine:
```javascript
module.exports = (wallaby) => {
  return {
    files: [
      //{pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      './test/.setup.js',
      'src/**/*.js',
      'src/**/*.json'
    ],

    tests: [
      'test/**/*spec.js'
    ],

    env: {
      type: 'node',
      runner: 'node'  // or full path to any node executable
    },

    debug: true,

    testFramework: 'mocha',

    compilers: {
      'src/**/*.js': wallaby.compilers.babel({
        babelrc: false,
        presets: ['es2015', 'react', 'stage-2'],
        plugins: ['syntax-async-generators', 'add-module-exports', 'transform-class-properties']
      }),
      'test/**/*.js': wallaby.compilers.babel({
        babelrc: false,
        presets: ['es2015', 'react', 'stage-2'],
        plugins: ['syntax-async-generators', 'add-module-exports', 'transform-class-properties']
      })
    },

    setup: function() {
          require('./test/.setup.js');
    }
  };
};```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! 
You can make your compilers section a bit smaller, wallaby will only compile patterns from your `files`/`tests` lists anyway, so you can do:
```javascript
compilers: {
      '**/*.js': wallaby.compilers.babel({
        babelrc: false,
        presets: ['es2015', 'react', 'stage-2'],
        plugins: ['syntax-async-generators', 'add-module-exports', 'transform-class-properties']
      })
    },
```

**Comment by nathfy** [comment]
@ArtemGovorov cheers! you have a new customer.

**Comment by ArtemGovorov** [comment]
Great, thanks for becoming our customer :)!
