### ISSUE TITLE
VSCode lockup, probably due to too many 'Expected ...' logs

### ISSUE THREAD

**Issue by danzel** [wallabyjs/public#644]
### Issue description or question

I have some integration tests that do a lot of `expect(...).toBe(...);`
When I do a big change, they will all fail and log a lot of error messages.
Sometimes VS Code will lock up, otherwise `Wallaby.js Tests` log will be full heaps of lines like:

```
​  Expected false to be true.
​   c:\Users\dave\Code\mmomatch3\test\integration\sync\syncDetectorsSpec.ts:261
```

Is there a way to limit these like the console message limit?
Thanks!

Haven't ran this, but probably a reproduction:
```js
describe('VSCode', () => {
	it('doesnt die', () => {
		for (var i = 0; i < 10000; i++) {
			expect(true).toBe(false);
		}
	}
});
```

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

	return {
		files: [
			'app/**/*.ts',
			'test/util/*.ts'
		],

		tests: [
			'test/**/*Spec.ts'
		],
		
		testFramework: 'jasmine',

		// TypeScript compiler is on by default with default options,
		// you can configure built-in compiler by passing options to it
		// See interface CompilerOptions in
		// https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts
		compilers: {
		  '**/*.ts': w.compilers.typeScript({
			  module: 1 //commonjs
		  })
		},
		
		env: {
			type: 'node'
		}

	};
};
```

### Code editor or IDE name and version

Visual Studio Code v1.2.0

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I can add a setting to set the limit for the number of the displayed failing tests, but VS Code is already automatically doing it.

Your example doesn't display much, because it's a single test. I have tried to rewrite it a bit to make 10k tests, could you please try to see if this one locks your VS Code up:

```javascript
describe('VSCode', () => {
  for (var i = 0; i < 10000; i++) {
    it('doesnt die' + i, () => {
        expect(true).toBe(false);  
    });
  }
});
```
On machine it doesn't affect the editor at all.

**Comment by danzel** [comment]
Tested it, that doesn't lock up my VS Code. Not sure where the lockup came from then.

I am running in to a rare occasional lockup somewhere, but I'm not sure where. Will reopen if I find any way to reproduce it.
Thanks anyway :)

**Comment by ArtemGovorov** [comment]
Thanks for checking.
Any chance you remember how large is the file you were editing when VS Code locked up (large/small/files of different sizes)?
Please let me know if you find the way to reproduce it.

**Comment by ArtemGovorov** [comment]
Also, the next time it locks up, could you please check if there's anything interesting in the Dev Tools console (`Ctrl+Alt+I`).

**Comment by ArtemGovorov** [comment]
Have made a couple of optimisations that should eliminate the issue.
