### ISSUE TITLE
Can't run 2 wallaby configs at the same time (client and server)

### ISSUE THREAD

**Issue by ianjohnspain** [wallabyjs/public#649]
### Issue description or question

I have 2 wallaby js files, 1 for client using browser and the other for backend using node.

Running each one separately gives success but running them at the same time, 1 of them always fails.

Any ideas what I am doing wrong or its not supported?

I didn't paste my config files here as they are standard files one using node and other using browser but if you require them I can certainly attach them.

### Code editor or IDE name and version

WebStorm 2016.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
This scenario is not supported yet, feel free to subscribe to the feature request: https://github.com/wallabyjs/public/issues/89

**Comment by ianjohnspain** [comment]
Ok. Thanks for the info.
