### ISSUE TITLE
Support jasmine-node (specific lib, jasmine for node is supported)

### ISSUE THREAD

**Issue by dkuida** [wallabyjs/public#652]
### Issue description or question
support for 'jasmine-node'

since the current configuration just conflict with the run of the tool in webstorm

```javscript
module.exports = function () {
    return {
        files: [
            'config/**',
            'service_route.js'
        ],

        tests: [
            'integ/*[sS]pec.js'
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        debug: true,
        testFramework: 'jasmine'
    };
};
```

the above will just not recognise the tests written witht eh 'jasmine-node'
that invokes them with

jasmineWrapper.execute();

so the asynchronouse tests just do not run wiht wallaby

**Comment by ArtemGovorov** [comment]
Just to make it clear, your feature request is [for this library](https://github.com/mhevery/jasmine-node.git)?

**Comment by dkuida** [comment]
YEs, this library - it is a wraper around jasmine.
this is the only show stoper for me to buy wallaby

**Comment by dkuida** [comment]
Hi
I managed to get it all working ( seem like )
currently I use the regular node, without the require.
In general I use http://jasmine.github.io/2.4/node.html wrapper
Now since I am still wrapping here things up , and between several projects
( microservices you know)
any chance to get a trial license for couple of weeks ?
I want to see the flow working between projects and the code other
developers do, if it is all good, I will buy a license for myself and will
suggest it for the other developers also( currently one more backend , and
we try to force our frontend also).

Dan

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Re license: sure, please send us an email to hello@wallabyjs.com and we'll sort it out.

**Comment by dkuida** [comment]
Also one more thing - cannot figure out which jasmine version wallaby uses
? since I cannot use createSpyObj

**Comment by ArtemGovorov** [comment]
For node environment, wallaby.js is using the `jasmine` node module you have installed in your project.

**Comment by dkuida** [comment]
I just :heart: wallaby !
