### ISSUE TITLE
Support for visionmedia/debug ?

### ISSUE THREAD

**Issue by smeijer** [wallabyjs/public#654]
[visionmedia/debug](https://github.com/visionmedia/debug) is a common used debug module for node scripts. Support for this library would be great.

Currently wallaby prints `console.log` statements in the IDE being used (or at least in the case of webstorm). Although the debug package does write "error" messages to the "run pane", it would be awesome if the debug package would print to the IDE directly as well (just like common console.log statements).

**Comment by ArtemGovorov** [comment]
Thanks for the suggestion. There's this more generic feature request: https://github.com/wallabyjs/public/issues/165, `debug` should be covered once that one is implemented.
