### ISSUE TITLE
webstorm default node version (4.2) seems to cause parse errors in ECMAScript 6

### ISSUE THREAD

**Issue by luck02** [wallabyjs/public#655]
### webstorm default node version (4.2) can't parse ECMAScript6

wallaby console shows:
```
Thu, 16 Jun 2016 16:36:08 GMT wallaby:workers Sandbox (active) [yd54m] error: SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/linkLayer.spec.js:4:32)
    at Module._compile (module.js:435:26)
```

This is linkLayer.spec.js line 4
```javascript
const linkLayer = require('../lib/linkLayer')
```

The problem is the file being required, I'm not sure what token is specificall the issue.

However when I change the wallaby run configuration 
FROM:
~/Library/Caches/WebStorm2016.1/wallaby/node_v4.2.2/node

TO:
~/.nenv/versions/v6.2.1/bin/node

The issue goes away.

I'm primarily posting this to help anyone else who runs into this, not so much for support myself.  

### Wallaby.js configuration file

```javascript
{
  "files": [
    "./lib/**/*.js"
  ],

  "tests": [
    "./test/**/*.js"
  ],
  "testFramework": "mocha",
  "reportConsoleErrorAsError": true,
  "debug": true,
  "env": {
    "type": "node"
  }
}
```

### Code editor or IDE name and version

WebStorm 2016.1.3
Build #WS-145.1616, built on May 27, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for sharing.
The node path in run configuration is the node that wallaby is using to run itself. By default in WebStorm it's also using this node version to run your tests. The recommended way to configure the [node version for your tests is by using the `env.runner` setting](https://wallabyjs.com/docs/integration/node.html#node-version). For example, if you just set it to `node`:
```
"env": {
    "type": "node",
    "runner": "node"
  }
```
it'll use your system default node.
