### ISSUE TITLE
wallaby.js got error >> SyntaxError: Unexpected token u

### ISSUE THREAD

**Issue by piggyman007** [wallabyjs/public#657]
I found error, please help.

More information http://stackoverflow.com/questions/37826648/wallaby-js-got-error-syntaxerror-unexpected-token-u

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue with your config in my local example, for example in [this repo](https://github.com/wallabyjs/wallaby-node-babel) if I change it to use your code.

As I have requested in the referenced StackOverflow, please create a sample Github repo (or just attach the sample project zip to this issue) reproducing the issue.

**Comment by piggyman007** [comment]
hi all,

i have tried to create a small project with simple test cases and wallaby.js work fine.

I am not sure what the cause is but it should be my big code not wallaby.js.

Thanks so much.

**Comment by ArtemGovorov** [comment]
No worries, let me know if you find a way to reproduce the issue.
