### ISSUE TITLE
using .only in mocha makes wallaby stop working, need restart

### ISSUE THREAD

**Issue by cellog** [wallabyjs/public#658]
### Issue description or question
If you use .only (as in it.only(...) or describe.only(...)) in mocha wallaby needs to be restarted every time

### Wallaby.js configuration file
```javascript
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  const load = require;

  return {
    files: [
      { pattern: 'test/*', ignore: true },
      'src/**/*.js*',
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false }
    ],
    tests: [
      'test/*.js*'
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
        babel: load('babel-core'),
        presets: ['es2015', 'stage-0', 'react']
      })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      // this fools meteor into ignoring the require statement.
      // otherwise, it will try to load jsdom into the web version build and server build.
      const fool = require
      const jsdom = fool('jsdom').jsdom
      const sinon = fool('sinon')
      const expect = fool('chai').expect

// from mocha-jsdom https://github.com/rstacruz/mocha-jsdom/blob/master/index.js#L80
      const propagateToGlobal = (window) => {
        for (var key in window) {
          if (!window.hasOwnProperty(key)) continue
          if (key in global) continue

          global[key] = window[key]
        }
      }

// setup the simplest document possible
      const doc = jsdom('')
      const win = doc.defaultView
      global.document = doc
      global.window = win
      global.sinon = sinon
      global.expect = expect

      propagateToGlobal(win)
      global.window.____isjsdom = true
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX 10.10.5

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue on my projects, perhaps it's meteor/project specific. Could you please share a sample project where I could reproduce it?

**Comment by cellog** [comment]
Https://github.com/cellog/react-selection

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.43&pv=5.1.1&source=email_footer_2] On Sun, Jun 19, 2016 at 3:33 AM, Artem Govorov < notifications@github.com [notifications@github.com] > wrote:
Can't reproduce the issue on my projects, perhaps it's meteor/project specific. Could you please share a sample project where I could reproduce it?

**Comment by ArtemGovorov** [comment]
Thanks for the repo. Here is what I'm doing:
![ws](https://cloud.githubusercontent.com/assets/979966/16180911/8a4eb0d2-36d5-11e6-8b3b-3c821c21ecf7.gif)
and everything is working as expected. Is there a specific file/test I should be editing to reproduce the issue?

One thing, that may or may not be related to the issue, is that in your config some files included in your `tests` list are not files with actual tests [as wallaby.js requires](https://wallabyjs.com/docs/config/files.html#tests). This may be causing some issues (probably the one you've been observing). Here is how to fix the config in your case:
```javascript
    files: [
      { pattern: 'test/*.test.js*', ignore: true },
      'test/**/*.js*',
      'src/**/*.js*',
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false }
    ],
    tests: [
      'test/*.test.js*'
    ],
```

**Comment by cellog** [comment]
Thank you, that probably is the issue.

I will try and report back

via CloudMagic Email 
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.43&pv=5.1.1&source=email_footer_2]

**Comment by cellog** [comment]
I modified wallaby.js, and immediately had improvement.  Here is the new relevant section:

    files: [
      { pattern: 'test/*.test.js', ignore: true },
      'test/**/*.js',
      'src/**/*.js*',
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false }
    ],
    tests: [
      { pattern: 'test/index.js', ignore: true, instrument: false },
      'test/*.test.js*'
    ],

It's early, but I'd like to say this is working.  Your choice whether to close it or leave it open for a day if I was wrong.  I can always re-open it if it's still not working, but I think this is a case of user error.  Thanks!  Very helpful debugging!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
BTW, I don't think the
```javascript
{ pattern: 'test/index.js', ignore: true, instrument: false },
```
in the `tests` is required, because the pattern that follows it
```javascript
'test/*.test.js*'
```
doesn't include it the `index.js` file anyway.
Please feel free to re-open the issue if we didn't address it.

**Comment by cellog** [comment]
I didn't either, but wallaby explicitly gave me a parse error in test/index.js until I did that, so I didn't question it.  If I have more wonkiness (all working smoothly as I remember now, I'm salivating at the response time), I'll try to change that before re-opening

**Comment by onetom** [comment]
I would expect putting `.only` on a top-level `describe in a test script would only limit wallaby to running that test, just as `mocha` does. Yet it runs all my other test files too.

**Comment by ArtemGovorov** [comment]
@onetom By default wallaby runs test in parallel (in parallel mocha instances). To make `.only` work like in plain mocha, you need to run your tests in a single process like mocha does. You may do in wallaby by [setting the workers](https://wallabyjs.com/docs/config/workers.html) count to 1.

```diff
 module.exports = function () {
   return {
     ...

+    workers: { initial: 1, regular: 1 }
   };
 };
```

In future, we are planning to add the feature of running a single spec if it's marked with `.only` even with multiple parallel workers.
