### ISSUE TITLE
working with node and web together

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#659]
### Issue description or question
I have a setup where I have with a fullstack application (node and web) opened together:

```
├── app/
│   ├── app-client/ 
│   │   ├── wallaby.js
│   ├── app-server/
│   │   ├── wallaby.js
```

Each project has completely different settings (on has webpack + react/angular and the second is using node).

I want to be able to open both from IDE and work with them together. Is it possible? (currently I see that only one `wallaby.js` is allowed). Can I have main wallaby.js file which will somehow be used for both sub wallaby.js files?

**Comment by ArtemGovorov** [comment]
You may have multiple config files and run one or another, but at the moment running only one wallaby configuration at a time is supported (not both at the same time, unless you open them in 2 IDE instances). Feel free to subscribe to the [feature request](https://github.com/wallabyjs/public/issues/89).
