### ISSUE TITLE
Babel compiler not working for files from NODE_PATH

### ISSUE THREAD

**Issue by rochdev** [wallabyjs/public#660]
### Issue description or question

When adding the `src` folder in the `NODE_PATH` environment variable so its content can be used without relative paths, the babel compiler fails to compile and starts throwing ES2015 related errors. The problem disappears when switching to relative paths (i.e. `require('./a')` instead of `require('a')`) even though in both cases the file is located in `src`.

See https://github.com/rochdev/wallaby-babel-node-path-issue

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  var path = require('path');
  
  return {
    files: [
      {pattern: 'src/**/*.js'}
    ],

    tests: [
      {pattern: 'test/**/*.spec.js'}
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      params: {
        env: 'NODE_ENV=test;NODE_PATH=' + path.join(wallaby.localProjectDir, 'src')
      }
    }
  };
};
```

### Code editor or IDE name and version

Atom v1.8.0

### OS name and version

OSX 10.11.5

**Comment by yleflour** [comment]
I have the exact same problem. I use react native and got relative paths to work using the following config:

**wallaby.js**
```javascript
var path = require('path');
var globalModule = path.resolve(__dirname, '..');

module.exports = (wallaby) => ({
  files: [
    'src/**/*.js',
    '!src/**/*.spec.js',
  ],
  tests: [
    'src/**/*.spec.js',
  ],
  debug: true,
  compilers: {
    '**/*.js': wallaby.compilers.babel({
      babelrc: true,
      ignore: false,
      resolveModuleSource: require('babel-resolver')(globalModule),
    }),
  },
  env: {
    type: 'node',
  },
  setup: () => {
    require('react-native-mock/mock.js');
  },
});
```

**.babelrc**
```json
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "presets": ["react-native"],
  "plugins": "transform-object-rest-spread",
  "sourceMaps": true,
  "ignore": false
}
```

But imports such as `import MyComponent from 'myproject/src/components/MyComponent'` fail as the modules imported this way don't compile. I also tried using NODE_PATH as stated above which held the same results.

OS: Mac OSX 10.11.4
Editor: VSCode 1.2.1
Wallaby: 1.0.15

**Comment by ArtemGovorov** [comment]
It looks like the issue is that you're pointing the `NODE_PATH` to your local project dir (where your original not compiled files are stored). Try using the [`projectCacheDir`](https://wallabyjs.com/docs/config/overview.html) instead, to point it to the cache with compiled  and instrumented files:
```javascript
env: {
      type: 'node',
      params: {
        env: 'NODE_ENV=test;NODE_PATH=' + path.join(wallaby.projectCacheDir, 'src')
      }
    }
```

**Comment by ArtemGovorov** [comment]
Created the [pull request](https://github.com/rochdev/wallaby-babel-node-path-issue/pull/1).

**Comment by rochdev** [comment]
Works perfectly thank you and sorry about that :)
