### ISSUE TITLE
React Native + NODE_PATH imports

### ISSUE THREAD

**Issue by yleflour** [wallabyjs/public#661]
Our project uses React Native which by default allows resolved imports using the following:
If your project is named `myProject` you can do the following `import MyComponent from 'myProject/src/components/MyComponent'` meaning that we have those throughout the project.

Now when using relative imports everything works fine. But resolved imports are another matter. 
The only way I found to do it is to use the following config which necessitates that I manually link `instrumented/..` to `instrumented/links/myProject` at each wallabyjs launch.

**wallaby.js**
```javascript
var path = require('path');

module.exports = (wallaby) => ({
  files: [
    'src/**/*.js',
    '!src/**/*.spec.js',
  ],
  tests: [
    'src/**/*.spec.js',
  ],
  debug: true,
  compilers: {
    '**/*.js': wallaby.compilers.babel(),
  },
  env: {
    type: 'node',
    params: {
      env: 'NODE_PATH=' + path.join(wallaby.projectCacheDir, 'links'),
    },
  },
  setup: () => {
    require('react-native-mock/mock.js');
  },
});

```

**.babelrc**
```json
{
  "retainLines": true,
  "compact": true,
  "comments": false,
  "presets": ["react-native"],
  "plugins": "transform-object-rest-spread",
  "sourceMaps": true,
  "ignore": false
}
```

So I was wondering if there was a smarter way to do this which wouldn't necessitate me going into the wallaby cache everytime I launch it.

OS: Mac OSX 10.11.4
Editor: VSCode 1.2.1
Wallaby: 1.0.15

**Comment by ArtemGovorov** [comment]
Perhaps there's some more elegant solution, but you may just patch node `require` in wallaby config to do what you need. We use this idea in [RxJs for example](https://github.com/ReactiveX/rxjs/blob/master/wallaby.js#L35). In your case it may look like below (finding out if the required/imported path starts with `myProject`, and if so `require`-ing it from the `projectCacheDir` without the project name).
```javascript
setup: wallaby => {
      require('react-native-mock/mock.js');

      var path = require('path');
      var modulePrototype = require('module').Module.prototype;
      if (!modulePrototype._originalRequire) {
        modulePrototype._originalRequire = modulePrototype.require;
        modulePrototype.require = filePath => {
          var pathParts = filePath.split('/');
          if (pathParts.shift() === 'myProject') { // <-- your project name
            return modulePrototype._originalRequire.call(
              this, 
              path.join(wallaby.projectCacheDir, pathParts.join('/')));
          }
          return modulePrototype._originalRequire.call(this, filePath);
        };
      }
    }
```

**Comment by ArtemGovorov** [comment]
Did you have a chance to try the solution to see if it works for you?

**Comment by yleflour** [comment]
@ArtemGovorov Thanks fo the help,

I tried your solution and fiddled a bit with it. It does find the dependencies but now I can't find node_modules `React` and `chai`. It also throws errors such as `Cannot find module './runners/node/teardown'`.

Am I missing something?

**Comment by ArtemGovorov** [comment]
Did you try to remove the 
```
env: 'NODE_PATH=' + path.join(wallaby.projectCacheDir, 'links')
``` 
line?
Either way, it works for me on a simple local project, so could you please create a sample repo similar to your project setup demonstrating the issue?

**Comment by yleflour** [comment]
Got it working, I'll be maintaining a gist from now on [WallabyJS + React Native](https://gist.github.com/yleflour/dec8eb3a771277f7d8c410a5173b7c5f). You can use it if you get other people asking about wallabyjs + react native.

Now I have two other issues:

1: **.babelrc is mandatory**, putting my babel config in the wallaby config like this doesn't work.

```
compilers: {
    '**/*.js': wallaby.compilers.babel({
      babelrc: false,
      retainLines: true,
      compact: true,
      comments: false,
      presets: ['react-native'],
      plugins: 'transform-object-rest-spread',
      sourceMaps: true
    }),
  },
```

I get a `Failed to run compilers on src/actions/actionTypes.js, TypeError: this._opts.plugins.unshift is not a function` error

2: **One of my node_modules imports is es2015** as well and needs to be compiled with the rest so this doesn't work right now: `import Icon from 'react-native-vector-icons/FontAwesome';`. I'm thinking about adding it to the files (with `instrument: false`) and overriding the require as done for the global import. I'm open to any better idea.

**Comment by ArtemGovorov** [comment]
@yleflour Thanks for sharing! I have added the link to the gist to [our supported techs list](https://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes).

1. It should work if you change `plugins: 'transform-object-rest-spread'` to `plugins: ['transform-object-rest-spread']`. I have also just added the support for the plugins passed as a string to wallaby core v1.0.252, so once your core gets updated, you may keep passing it as a string.

2. If you add the module with `instrument: false`, wallaby will not be compiling it, however, you may configure [wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) for the module (it should work regardless the `instrument` setting). I would however recommend to use a different approach. Since you don't need the coverage for the module, you may just [use babel hook](https://babeljs.io/docs/usage/require/) to compile the module on the fly. So in your setup function ypu'll need to add:
```javascript
module.exports = (wallaby) => ({
  ...
  setup: () => {
   // you may need to look up the docs at 
   // https://babeljs.io/docs/usage/require/#specifying-options
   // to see if it's enough
   require("babel-register")({ only: /react-native-vector-icons/ });
   ...
  },
});
```

Let me know if the mentioned solutions work for you.

**Comment by yleflour** [comment]
All working and I've updated my [Gist](https://gist.github.com/yleflour/dec8eb3a771277f7d8c410a5173b7c5f)

Everything works great and all the tests run as expected.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
