### ISSUE TITLE
nodejs: cannot fork a child process using wallaby

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#662]
### Issue description or question
I am forking a child process in my code using `child_process`. This is working when running tests manually, but when running using Wallabyjs it is throwing an error:

`Error: Cannot find module..`

I created a simple example for it:

```js
var cp = require('child_process');
const join = require('path').join;

var child = cp.fork(join(__dirname,'./server'));
```

server.js is a simple http server:

```js
const http = require('http');

const server = http.createServer();
server.on('request', function(req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});

  res.write('Hello World!');
  res.end();
});

server.listen(4000);

module.exports = server;
```

My test is:

```js
const expect = require('chai').expect;
const fetch = require('node-fetch');
const aServer = require('../index2');

describe('bla', () => {
  it('should be ok', function(done) {
    this.timeout(10000);
    setTimeout(() => { //workaround for this sample
      fetch('http://localhost:4000').then(res => {
        console.log('123');
        expect(res.status).to.equal(200);
        done();
      });
    }, 5000);
  });
});

```
### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'index.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    env: {
      type: 'node'
    }
  };
};

```

### Code editor or IDE name and version
Atom v1.8

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Wallaby needs all files that you load (except node modules) to be [listed in the `files` list](https://wallabyjs.com/docs/intro/troubleshooting.html#cannot-find-module-or-file-not-found). 
Note that wallaby doesn't support cross process code coverage, so you'll need to set the [`instrument: false` flag](https://wallabyjs.com/docs/config/files.html#file-object) for the `server`:

```javascript
files: [
      'index.js',
      {pattern: 'server.js', instrument: false}
    ],
```
