### ISSUE TITLE
Browserify: Problem with module not being found via angular.

### ISSUE THREAD

**Issue by ianjohnspain** [wallabyjs/public#664]
### Issue description or question
 Getting the following here when running wallaby client. application JS use browserify,  tests currently do not. Before implementing browserify in the client, all tests were passing. I also have a karma.conf setup and this run tests OK so I think I am missing some config details ? I will place my karma.conf below, in case it is helpful is diagnosing the issue.

```javascript
"before each" hook: '[object Object]' is not a function (evaluating 'module(function ($provide) {
            $_$wf(6);
            $_$w(6, 13), $provide.value('$document', $document);
        })')

	at src/test/javascript/unit/services/miscServiceTest.js:28

"before each" hook: workFn: [$injector:modulerr] Failed to instantiate module misc due to:
Error: [$injector:nomod] Module 'misc' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=misc
```

Not too sure if its 100% corrrect, the line that is highlighted with wallaby with a red square in webstorm is this

```javascript
        module(function ($provide) {
            $provide.value('$document', $document);
        });
```

### Wallaby.js configuration file

```javascript
var nodeModulesPath = 'node_modules/';
var applicationPath = 'src/main/javascript/';

var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({});

module.exports = function (wallaby) {
  return {
    files: [
      {
        pattern: nodeModulesPath + 'chai/chai.js',
        instrument: false
      },
      nodeModulesPath + 'angular/angular.js',
      nodeModulesPath + 'angular-mocks/angular-mocks.js',
      {
        pattern: applicationPath + '**/*.js',
        load: false
      }
    ],

    tests: [
      '!src/test/javascript/karma.conf.js',
      'src/test/javascript/**/*.js'
    ],

    postprocessor: wallabyPostprocessor,

    testFramework: 'mocha',

    env: {
      type: 'browser'
    },

    setup: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

### Karma.Conf - currently runs tests ok

```javascript
// Karma configuration
// Generated on Mon Jun 13 2016 14:11:39 GMT+0800 (PHT)

var nodeModulesPath = '../../../node_modules/';
var applicationPath = '../../../src/main/javascript/';

module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',


        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['browserify', 'mocha', 'chai'],


        // list of files / patterns to load in the browser
        files: [
            nodeModulesPath + 'angular/angular.js',
            nodeModulesPath + 'angular-mocks/angular-mocks.js',
            applicationPath + '**/*.js',
            '**/*.js'
        ],


        // list of files to exclude
        exclude: [],


        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            '../../../src/main/javascript/**/*.js': [
                'browserify',
                'coverage'
            ]
        },


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['mocha', 'coverage', 'bamboo'],

        mochaReporter: {
            output: 'autowatch'
        },
        bambooReporter: {
            filename: 'mocha.frontend.json'
        },

        coverageReporter: {
            type : 'lcov',
            subdir: '.',
            dir : '../../../../coverage/frontend-unit'
        },

        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,


        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['PhantomJS'],


        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false,

        // Concurrency level
        // how many browser should be started simultaneous
        concurrency: Infinity,

    })
}

```

**Comment by ArtemGovorov** [comment]
In context of browserify (CommonJs), `module` is a reserved variable of the file scope (to do `module.exports`, etc.)
Try:
```javascript
angular.module(function ($provide) {
            $provide.value('$document', $document);
        });
```

**Comment by ianjohnspain** [comment]
Thanks!, Yes I missed that. actually I believe it is angular.mock.module, I have updated it and  checked karma and its still working but when wallaby runs it still failing. Do you think my config file is ok, I see no reference to browserify

        angular.mock.module(function ($provide) {
            $provide.value('$document', $document);
        });

The failure is a little better :-)

```
"before each" hook: workFn: [$injector:modulerr] Failed to instantiate module misc due to:
Error: [$injector:nomod] Module 'misc' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=misc
```

I have tried simply using console.log(..) at certain places so see where it seems to fail. It seems to fail on the beforeEach
```

    beforeEach(angular.mock.inject(function (_MiscService_) {
        console.log('444') // THIS NEVER ARRIVES
        MiscService = _MiscService_;
    }));
```

Maybe some files are not getting loaded so it can't inject.

I am still using a glob for the js files and set it to load: false, is this ok ?

THanks again for all your help.

**Comment by ianjohnspain** [comment]
I just put a console.log inside my angular service to see if its being loaded, and I get no output so it appears maybe its not loading

**Comment by ianjohnspain** [comment]
And the path appears to be correct, relative to where the wallaby.js file is .. i.e. I have 

var applicationPath = 'src/main/javascript/';

and the index.js is at src/main/javascript/index.js

**Comment by ArtemGovorov** [comment]
Looking into your config once again, I have noticed that you are not setting `load: false` for your `tests` as [the docs say](https://wallabyjs.com/docs/integration/browserify.html).
```javascript
tests: [
      '!src/test/javascript/karma.conf.js',
      {pattern: 'src/test/javascript/**/*.js', load: false}
    ],
```
This may be the issue. 
Here is how it works:
- [Files/tests with `load: true`](https://wallabyjs.com/docs/config/files.html#file-object) are loaded into the sandbox page via `script` tags. For browserify however, `load` needs to be set to `false` because original files have to be `browserified` first and the loaded via your `setup` function where you call:
```
setup: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    }
```
As currently your `tests` have `load: true` (the default), they get loaded before your source files, hence the error.

Also, please make sure that your `tests` pattern [only includes files with actual tests inside them](https://wallabyjs.com/docs/config/files.html#tests). So if there're some tests helpers in the `src/test/javascript/**/*.js` pattern, you may need to add them to the `files` list and make the `tests` pattern stronger (for example if you use some convention to name your test files, it may look like: `src/test/javascript/**/*.spec.js`).

Other than that, your config looks good to me, so if making the suggested change doesn't help, please create a small repo where I could reproduce the issue.

**Comment by ianjohnspain** [comment]
Thanks Artem for your continued support. I still wasn't able to get it working so I have created a small project to demonstrate it as recommended by yourself.

https://github.com/ianjohnspain/wallabysample

If you run the karma, you will notice the test passes..  

But wallaby fails to inject the dependencies from angular.

Karma uses a preprocessor to because of browserify

wallaby, setup, as part instructions, I think :-)

**Comment by ArtemGovorov** [comment]
Thanks for the repo, I have sent your [the pull request](https://github.com/ianjohnspain/wallabysample/pull/1).
Your tests are not `require`-ing any of your modules (like they ideally should if you do full CommonJs), they are relying on the fact that something has loaded them into the sandbox. And you can't just set `load: true` because they have to be browserify-ed first. To support this scenario, wallaby.js [has `entryPatterns` support](https://wallabyjs.com/docs/integration/browserify.html#entry-patterns) for browserify, where you may specify what files will be used as entry points for your app (other than your tests).

**Comment by ianjohnspain** [comment]
Thanks Artem!

Great support by the way.

Yes I am understanding things better now and with your pull request, i have managed to fix everything.

Thanks again

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
