### ISSUE TITLE
use files from file-sysytem instead of cache

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#665]
### Issue description or question
I have a  (node) project which generates a config file in runtime. I have this config file in `files` array, but wallaby does not copy it (probably because when it copies files this file is not there, yet). So when my test is looking for this file (in cache folder) it is not found.

I have two options: 

1. Wait for files to be written and only then tell wallaby to copy them (have no idea how to do that)

2. Tell wallaby to take this config file (which is located in `target` folder) from local file system (like we do with node_modules). The question is - how do I tell Wallaby to take files from local filesystem, similar to this thing: 

`process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');`

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');
  return {
    files: [
      'app/**/*.ts',
      {pattern: 'index.js', instrument: false},
      {pattern: 'test/environment.[j|t]s', instrument: false},
      {pattern: 'package.json', instrument: false},
      {pattern: 'dist/**/*.*', instrument: false}//,
      {pattern: 'target/configs/*.*', instrument: false},
    ],
    tests: [
      'test/**/*.spec.[j|t]s'
    ],
    testFramework: 'jasmine',
    env: {
      type: 'node'
    },
    workers: {recycle: false}
  };
};

```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by yanivefraim** [comment]
So fixed it in a hackey way, using an env variable to pass `localProjectDir` (process.cwd()) from wallaby.js:

```js
env: {
      type: 'node',
      params: {
        env: 'LOCAL_PATH=' + process.cwd()
      }
    },
```

Then, in my code, I access my configs using:

`APP_CONF_DIR: join(process.env.LOCAL_PATH, '/target/configs'),`  

I will love to hear what do you have to say about it and about my solution. Thanks!

**Comment by ArtemGovorov** [comment]
> I have a (node) project which generates a config file in runtime. I have this config file in files array, but wallaby does not copy it (probably because when it copies files this file is not there, yet).

Correct, it may be too late if the file is generated in runtime.

Depending on how you create those files in runtime, you may not need the hack with the path. The question is, how come that your code, that runs in the wallaby cache folder (when run by wallaby), in runtime creates files in your local project folder? Are you not using relative paths and hardcoding absolute paths somewhere?

For example, if in my app/tests I call `fs.writeFile('/tmp/test', ...)`, the file will be created in the wallaby cache folder, as expected.

**Comment by yanivefraim** [comment]
Thanks for the answer. 

The problem is that the code which does the `fs.writeFile('/tmp/test', ...)` is running inside a `node_module`, which runs on filesystem (and not on cache). This is because I defined:

`process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');` 

on my `wallaby.js`

**Comment by ArtemGovorov** [comment]
Could you please provide an example? I still don't understand what exactly is going on. 

> the code which does the fs.writeFile('/tmp/test', ...) is running inside a node_module

Where does your node module get the path to write the `/target/configs` files from? Are you passing it from your code? Is the path absolute/relative?

**Comment by yanivefraim** [comment]
Yes, the code gets the path from my code (from my test code, to be more precise). The code doing this fs.writeFile... My solution (which worked, BTW) was passing absolute path, for local file system.

**Comment by ArtemGovorov** [comment]
Sorry, I still don't quite understand why it doesn't work without using an absolute path with `process.env.LOCAL_PATH`. 

Let's say you have a node module `writer` (loaded from `process.env.NODE_PATH`, so from your local project folder), and it does something like:
```javascript
module.exports = function (path) { fs.writeFile(path); }
```

and you have a test that does:
```
it('should work', function() {
  require('writer')(__dirname + '/target/configs/someFile.txt')
});
```
then, if you run the test with wallaby, it will write the `someFile` to the `target/configs/` subfolder of your test folder in **wallaby cache**, not in your local project folder. So the file will be available for the rest of your code.

Your solution with the absolute path looks good as well, I'm just trying to understand if you could get away without having to specify the `LOCAL_PATH` env variable. I'll close the issue since you have it working, however please feel free to let me know more details about your scenario if you'd like to try getting it working without the `LOCAL_PATH`.

**Comment by yanivefraim** [comment]
I was able to finally solve it using `__dirname`, as you suggested. The problem was related to the way our application is built (too complicated to explain and not relevant...) 
Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
