### ISSUE TITLE
Delay Teardown

### ISSUE THREAD

**Issue by arg20** [wallabyjs/public#667]
### Please implement async teardown

I use wallaby to run database (not mocked) tests. I'm using bookshelf and knex, which need to destroy the pool of connections at the end of the tests or I get an error saying too many connections are being created. Is there any way to delay the teardown so it doesn't stop half way through my cleanup process? I don't want to destroy the process and recreate it.

**Comment by ArtemGovorov** [comment]
Async teardown is not supported, but async [`setup`](https://wallabyjs.com/docs/config/bootstrap.html) is supported. You may access everything that you can access from the `teardown` function, check if what you want to clean up exists, do the cleanup and start tests after the cleanup.
```javascript
setup: wallaby => {
  wallaby.delayStart();
  yourAsyncCleanUp(() => {
    wallaby.start();
  });
}
```
