### ISSUE TITLE
Running wallaby in webstorm

### ISSUE THREAD

**Issue by miganga** [wallabyjs/public#668]
### Issue description or question

Trying to make the wallaby.js run in webstorm, but always getting a spinner and no status in the console.

### Wallaby.js configuration file
```javascript
module.exports = function () {
  return {
    "files": [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
      {pattern: 'node_modules/angular/angular.js', instrument: false},
      {pattern: 'node_modules/angular-route/angular-route.js', instrument: false},
      {pattern: 'node_modules/angular-mocks/angular-mocks.js', instrument: false},
      'js/**/*.js'
    ],
    "tests": [
      'test/unit/**/*.js'
    ]
  };
};
```
### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Please try the following steps:
- Add the `debug: true` flag to the config, start wallaby.js and attach the Wallaby Console output.
```javascript
module.exports = function () {
  return {
    ...
    debug: true
  };
};
```
- Start wallaby.js again, and attach the `idea.log` file, the location is available from the “Help - Show Log” menu of your code editor.

**Comment by miganga** [comment]
Here you go.
[idea.log.zip](https://github.com/wallabyjs/public/files/331379/idea.log.zip)

**Comment by ArtemGovorov** [comment]
Thanks. 
Wallaby.js spins up a node.js process and communicates with it from the IDE via websocket (the connection is made to `ws://localhost:port`). From the log file it looks like like wallaby.js can not connect to its core on your system, maybe a firewall issue?

**Comment by miganga** [comment]
Hmm.  Disabled the firewall.  Still kind of same.  It was able to activate, download the files etc.  with the first installation though.

**Comment by ArtemGovorov** [comment]
> It was able to activate, download the files etc. with the first installation though.

Those are downloads from external http resources. However the current issue is with connecting from the IDE to the node server running locally by websocket.

Please try this:
- Open your activity monitor, make sure no `node` processes are running, start wallaby and check if one `node` process was created.
- Could you try installing wallaby.js for [Atom, VS Code or Sublime Text](https://wallabyjs.com/docs/intro/install.html#atom) to see if if works for you there?

**Comment by miganga** [comment]
Yes a node process is created when started.  Will try it on atom in a few.

**Comment by miganga** [comment]
Atom works actually.  So what would you suggest for webstorm?  Thanks.

**Comment by ArtemGovorov** [comment]
Hmm, interesting. May be something specific to Java version. Could you please download the [latest version of WebStorm 2016.1.3](https://www.jetbrains.com/webstorm/download/) and try there?

**Comment by miganga** [comment]
Was trying on that.  Also tried some eap versions. No luck.

**Comment by ArtemGovorov** [comment]
What's your OSX version?

**Comment by miganga** [comment]
10.10.5

**Comment by ArtemGovorov** [comment]
I'm on the exact same version of the OS and it works for me in all WebStorm versions since v9.

Just for the record, here is the error that is raised.
```
java.net.ConnectException: Operation timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.Socket.connect(Socket.java:589)
```
- What's your `java -version`?
- Does you WebStorm have any proxy settings (`Settings | Appearance & Behavior | System Settings | HTTP Proxy`)?
- Does your system have any proxy settings?
- How does your `/etc/hosts` file look like?
- Try installing this version [wallaby-intellij-v1.0.67.zip](https://github.com/wallabyjs/public/files/331554/wallaby-intellij-v1.0.67.zip) (`Settings | Plugins | Install plugin from disk`) and running it (I have replaced `localhost` with `127.0.0.1` in it to see if it helps).

**Comment by miganga** [comment]
java version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

installed the latest wallaby
proxy looks ok
so does /etc/hosts

Everything seems ok.  Will take a break for now. :)

**Comment by ArtemGovorov** [comment]
> installed the latest wallaby
> Everything seems ok.

You mean the attached version works?

**Comment by ArtemGovorov** [comment]
Sorry I didn't understand if it's working for you now or not :), will close the issue for now. If it doesn't work, please attach your `/etc/hosts` file, and clarify a bit when you say `proxy looks ok` - do you mean you have the proxy configured or not?

**Comment by miganga** [comment]
No it wasn't working.  
Found out this line in hosts
192.168.99.100 localhost  (for my docker setup)
was causing the issue.
It works now, thanks for the big support.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update and for your patience!
