### ISSUE TITLE
Wallaby + tsx: "before each" hook: document is not defined

### ISSUE THREAD

**Issue by maierson** [wallabyjs/public#670]
### I'm exploring using wallaby for testing. 

All works ok until I try to access the dom in any way (via document or through React's TestUtils.renderIntoDocument). I get a document is not defined error and no tests are running.

The basic setup project:

https://github.com/maierson/wallb

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        debug: true,

        files: [
            { pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
            'app/**/*.tsx'
        ],

        tests: ['test/**/*spec.tsx'],

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs',// jscs:ignore
                jsx: 'React'
            })
        },

        testFramework: 'mocha',

        env: {
            type: 'node'
        }
    };
};
```

### Code editor or IDE name and version

WebStorm v11
Visual Studio Code v0.10.x
(in visual studio code I don't get the inline errors - is this on purpose or am I missing a setting

### OS name and version
OSX 10.11.2

Thank you

![screen shot 2016-06-23 at 9 52 05 pm](https://cloud.githubusercontent.com/assets/16655922/16325524/dd8cfcae-398c-11e6-96af-2f14c61c37e3.png)

**Comment by ArtemGovorov** [comment]
Thanks for the project link. 
You are using node.js to run your tests:
```javascript
env: {
            type: 'node'
        }
```
and there's no DOM there, hence the error. You may [use `jsdom`](https://github.com/jesstelford/react-testing-mocha-jsdom#jsdom), so
```
npm i jsdom --save-dev
```
+

add the [`setup` function](https://wallabyjs.com/docs/config/bootstrap.html) in your wallaby config:
```javascript
module.exports = function (wallaby) {
    return {
        debug: true,

        files: [
            'app/**/*.tsx'
        ],

        tests: ['test/**/*spec.tsx'],

        compilers: {
            '**/*.ts?(x)': wallaby.compilers.typeScript({
                module: 'commonjs',// jscs:ignore
                jsx: 'React'
            })
        },

        env: {
            type: 'node'
        },

        setup: function () {
            var jsdom = require('jsdom');
            global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
            global.window = document.parentWindow;
        }
    };
};
```
> in visual studio code I don't get the inline errors - is this on purpose or am I missing a setting

Inline errors in VS Code only work from version 1.3 of the editor (where the API to implement the feature was introduced). The current version is 1.2, so if you'd like to use the feature you'll need to [install the insider's build of the editor](https://code.visualstudio.com/insiders)).

Let me know if it addressed the issue and answered your question.

**Comment by maierson** [comment]
Yes - that did it. Thank you very much.

However now it gives another error, also in "before each" hook: Cannot read
property 'addEventListener' of undefined.
This is either using this.container with ReactDom.render or with
TestUtils.renderIntoDocument.

On Thu, Jun 23, 2016 at 10:08 PM, Artem Govorov <notifications@github.com>
wrote:

> Thanks for the project link.
> You are using node.js to run your tests:
>
> env: {
>             type: 'node'
>         }
>
> and there's no DOM there, hence the error. You may use jsdom
> <https://github.com/jesstelford/react-testing-mocha-jsdom#jsdom>, so
>
> npm i jsdom --save-dev
>
> +
>
> add the setup function <https://wallabyjs.com/docs/config/bootstrap.html>
> in your wallaby config:
>
> module.exports = function (wallaby) {
>     return {
>         debug: true,
>
>         files: [
>             'app/**/*.tsx'
>         ],
>
>         tests: ['test/**/*spec.tsx'],
>
>         compilers: {
>             '**/*.ts?(x)': wallaby.compilers.typeScript({
>                 module: 'commonjs',// jscs:ignore
>                 jsx: 'React'
>             })
>         },
>
>         env: {
>             type: 'node'
>         },
>
>         setup: function () {
>             var jsdom = require('jsdom');
>             global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
>             global.window = document.parentWindow;
>         }
>     };
> };
>
> in visual studio code I don't get the inline errors - is this on purpose
> or am I missing a setting
>
> Inline errors in VS Code only work from version 1.3 of the editor (where
> the API to implement the feature was introduced). The current version is
> 1.2, so if you'd like to use the feature you'll need to install the
> insider's build of the editor <https://code.visualstudio.com/insiders>).
>
> Let me know if it addressed the issue and answered your question.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wallabyjs/public/issues/670#issuecomment-228238596>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AP4mMiP7TraEFGx5pyRD0Z0aHUEoq8V1ks5qOzwIgaJpZM4I9Zal>
> .
>



-- 
Dahn Maier
Maier Inc.
dahn@maierinc.com
917.596.3685

------------------------------
This transmission is intended solely for the person or organization to whom
it is addressed and it may contain privileged and confidential information.
If you are not the intended recipient you should not copy, distribute or
take any action in reliance on it. If you believe you received this
transmission in error please notify the sender.

**Comment by ArtemGovorov** [comment]
Sorry, turns out the `jsdom` sample I have referenced is outdated. [This one](http://hellote.com/testing-react-components-with-mocha-and-jsdom/) and [this one](http://jaketrent.com/post/testing-react-with-jsdom/) seem to be more recent and working.

This should work for you:
```javascript
        setup: function () {
            var jsdom = require('jsdom');
            global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
            global.window = document.defaultView;
            global.navigator = global.window.navigator;
        },
```

**Comment by maierson** [comment]
That did it. Thanks again. Looking good so far. I'll know more in a couple
of days.

On Thu, Jun 23, 2016 at 11:38 PM, Artem Govorov <notifications@github.com>
wrote:

> Sorry, turns out the jsdom sample I have referenced is outdated. This one
> <http://hellote.com/testing-react-components-with-mocha-and-jsdom/> and this
> one <http://jaketrent.com/post/testing-react-with-jsdom/> seem to be more
> recent and working.
>
> This should work for you:
>
>         setup: function () {
>             var jsdom = require('jsdom');
>             global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
>             global.window = document.defaultView;
>             global.navigator = global.window.navigator;
>         },
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wallabyjs/public/issues/670#issuecomment-228251030>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AP4mMqhk7157PKAS7zePUuaIwa8cqyVQks5qO1E3gaJpZM4I9Zal>
> .
>



-- 
Dahn Maier
Maier Inc.
dahn@maierinc.com
917.596.3685

------------------------------
This transmission is intended solely for the person or organization to whom
it is addressed and it may contain privileged and confidential information.
If you are not the intended recipient you should not copy, distribute or
take any action in reliance on it. If you believe you received this
transmission in error please notify the sender.
