### ISSUE TITLE
No failing tests, 0 passing in Webstorm IDE

### ISSUE THREAD

**Issue by rollymaduk** [wallabyjs/public#671]
## No failing tests, 0 passing in Webstorm IDE
I cann't seem to get wallaby to work properly with my IDE, It keeps showing "no failing tests, 0 passing!" below are my config and test files, I am currently using webstorm typescript compiler set to use the tsconfig file in my root project.
### Wallaby config

```
module.exports = function (wallaby) {
    return {

        files: [

            {pattern: 'packages/**/*.ts',  load: false},
            {pattern: 'packages/**/test/*.spec.ts', load:false, ignore:true},
            {pattern: 'packages/**/typings/*.ts', load:false, ignore:true}
        ],
        tests: [
            {pattern: 'packages/**/test/*.spec.ts', load: false}
        ],
        debug: true,
        maxConsoleMessagesPerTest: 10000,
        env:{
            type:'node'
        }
    };
};
```
### Test Subject
```
/**
 * Created by rolly_000 on 6/25/2016.
 */
export class DbService{
    constructor(){
    }
    message():string{
        return "hello";
    }
}
```
### Jasmine Test
```
import {DbService} from "../lib/Dbservice";
describe("something is happening", ()=>{
    it("should do something",()=>{
        var res=new DbService();
       expect(res.message()).toEqual(1);
    })
});
```
### tsconfig.json

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "packages/**/*.ts",
    "typings/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```
### IDE 
``` 
webstorm version 11
```

**Comment by ArtemGovorov** [comment]
Try removing `load: false` flag from all of your file patterns. The flag is used in browser environment to control whether or not to load files into the testing sandbox via `script` tags. You're using `node` environment however.

```javascript
module.exports = function (wallaby) {
    return {

        files: [

            {pattern: 'packages/**/*.ts'},
            {pattern: 'packages/**/test/*.spec.ts', ignore:true},
            {pattern: 'packages/**/typings/*.ts', lignore:true}
        ],
        tests: [
            {pattern: 'packages/**/test/*.spec.ts'}
        ],
        debug: true,
        maxConsoleMessagesPerTest: 10000,
        env:{
            type:'node'
        }
    };
};
```

**Comment by rollymaduk** [comment]
It worked thanks, but I have a new error message saying "expect is not defined", I wonder why? can you please help. Could it be that Jasmine expect library does not work in node?

```
import {DbService} from "../lib/Dbservice";
describe("something is happening", ()=>{
    it("should do something",()=>{
        var res=new DbService();
        expect(res.message()).toEqual(1); \\expect is not defined
    })
});

**Comment by ArtemGovorov** [comment]
Wallaby.js for node [uses `mocha` by default](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). For `jasmine` you need to specify the `testFramework` setting.

```javascript
module.exports = function (wallaby) {
    return {
        ...
        testFramework: 'jasmine'
    };
};
```
plus, if you haven't done it yet:
```
npm i jasmine --save-dev
```

**Comment by rollymaduk** [comment]
Many thanks, your support is great and appreciated!

On Sun, Jun 26, 2016 at 9:42 AM, Artem Govorov <notifications@github.com>
wrote:

> Wallaby.js for node uses mocha by default
> <https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks>.
> For jasmine you need to specify the testFramework setting.
>
> module.exports = function (wallaby) {
>     return {
>         ...
>         testFramework: 'jasmine'
>     };
> };
>
> plus, if you haven't done it yet:
>
> npm i jasmine --save-dev
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wallabyjs/public/issues/671#issuecomment-228590751>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACpHGxEtKNsp-g8_ch9PRA1-lbrF5F5yks5qPjuDgaJpZM4I-dqy>
> .
>



-- 

*RegardsRonald Maduka*

**Comment by seaBubble** [comment]
I am also having this issue. My project has been generated with the Angular CLI.
I don't see any errors in the console.

**Config file (wallaby.js)**
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.ts',
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', {loader: 'less-loader', options: {paths: [__dirname]}}]},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
        '@app': path.join(wallaby.projectCacheDir, 'src/app/'),
        '@shared': path.join(wallaby.projectCacheDir, 'src/app/shared'),
        '@env': path.join(wallaby.projectCacheDir, 'src/environments/')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    hints: {
      ignoreCoverage: /ignore coverage/ // or /istanbul ignore next/, or any RegExp
    },

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

**src/WallabyTest.ts**
import './polyfills';

import 'zone.js/dist/zone-testing';

import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting()
);

**Wallaby Console output:**
wallaby.js started
core v1.0.608
Tue, 24 Jul 2018 07:04:18 GMT wallaby:project Wallaby config: /Users/martagalvehernandez/Documents/testWallaby/wallaby.js
Tue, 24 Jul 2018 07:04:21 GMT wallaby:uiService Listening port 51235
Tue, 24 Jul 2018 07:04:21 GMT wallaby:project File cache: /Users/martagalvehernandez/Library/Caches/WebStorm2017.2/wallaby/projects/789d5c61ee4feb7a
Tue, 24 Jul 2018 07:04:21 GMT wallaby:project package.json file change detected, invalidating local cache
Wallaby App (realtime reports) is available at: http://localhost:51245
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #0
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #1
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #2
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #3
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #4
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Starting run worker instance #5
Tue, 24 Jul 2018 07:04:22 GMT wallaby:workers Web server is listening at 49607
Tue, 24 Jul 2018 07:04:22 GMT wallaby:project File cache requires some updates, waiting required files from IDE
Tue, 24 Jul 2018 07:04:22 GMT wallaby:project File src/main.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:22 GMT wallaby:project Preparing to process src/main.ts
Tue, 24 Jul 2018 07:04:22 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:uiService UI client connected
Tue, 24 Jul 2018 07:04:23 GMT wallaby:uiService Outgoing message ui:handshake
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/main.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/main.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/main.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/main.ts changes saved, store ts: 1532412497000, change ts: 1532415862423
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/test.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/index.html changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/styles.css changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tslint.json changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/polyfills.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/wallabyTest.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.app.json changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.spec.json changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.module.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.css changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.html changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.spec.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/environments/environment.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/environments/environment.prod.ts changes are patches only: false
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/app/app.module.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/environments/environment.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/test.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/index.html
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/styles.css
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/tslint.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/polyfills.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/wallabyTest.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/tsconfig.app.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/tsconfig.spec.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/app/app.component.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/app/app.component.css
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/app/app.component.html
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/app/app.component.spec.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Preparing to process src/environments/environment.prod.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Starting processor pool (if not yet started)
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.module.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/app/app.module.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/app/app.module.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.app.json is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/tsconfig.app.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/tsconfig.app.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.spec.json is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/tsconfig.spec.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/tsconfig.spec.json
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/app/app.component.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.css is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/app/app.component.css
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.css
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.html is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/app/app.component.html
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.html
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.spec.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/app/app.component.spec.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.spec.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/environments/environment.prod.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project No preprocessors configured for src/environments/environment.prod.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project Writing to disk and caching processed file src/environments/environment.prod.ts
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.module.ts changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.ts changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.css changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.spec.ts changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.app.json changes saved, store ts: 1532412744000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/tsconfig.spec.json changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/app/app.component.html changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:23 GMT wallaby:project File src/environments/environment.prod.ts changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #0
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #1
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #2
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #3
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #4
Tue, 24 Jul 2018 07:04:24 GMT wallaby:workers Started run worker instance (immediate) #5
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/styles.css is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/styles.css
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/styles.css
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/styles.css changes saved, store ts: 1532412497000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/environments/environment.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/environments/environment.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/environments/environment.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/wallabyTest.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/wallabyTest.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/wallabyTest.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/environments/environment.ts changes saved, store ts: 1532412497000, change ts: 1532415863575
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/wallabyTest.ts changes saved, store ts: 1532412624000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/tslint.json is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/tslint.json
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/tslint.json
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/tslint.json changes saved, store ts: 1532412497000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/test.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/test.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/test.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/test.ts changes saved, store ts: 1532412497000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/polyfills.ts is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/polyfills.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/polyfills.ts
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/polyfills.ts changes saved, store ts: 1532412497000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/index.html is not instrumented by core
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/index.html
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/index.html
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project File src/index.html changes saved, store ts: 1532412497000, change ts: 1532415863574
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Stopping process pool
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Running postprocessor
Tue, 24 Jul 2018 07:04:25 GMT wallaby:postprocessor New TypeScript language service is required
Tue, 24 Jul 2018 07:04:25 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): 1
Tue, 24 Jul 2018 07:04:25 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 1
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/app/app.component.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/app/app.module.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/environments/environment.prod.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/environments/environment.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/main.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/polyfills.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/test.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/wallabyTest.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Preparing to process src/app/app.component.spec.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/app/app.component.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/app/app.component.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/app/app.module.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/app/app.module.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/environments/environment.prod.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/environments/environment.prod.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/environments/environment.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/environments/environment.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/main.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/main.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/polyfills.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/polyfills.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/test.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/test.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/wallabyTest.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/wallabyTest.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Processing compiled src/app/app.component.spec.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Instrumenting src/app/app.component.spec.js, via process pool: false
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/app/app.component.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/app/app.module.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/environments/environment.prod.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/environments/environment.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/main.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/polyfills.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/test.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/wallabyTest.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project No preprocessors configured for src/app/app.component.spec.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/app/app.module.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/environments/environment.prod.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/environments/environment.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/main.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/polyfills.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/test.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/wallabyTest.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:project Writing to disk and caching processed file src/app/app.component.spec.js
Tue, 24 Jul 2018 07:04:25 GMT wallaby:postprocessor New compiler created
Tue, 24 Jul 2018 07:04:25 GMT wallaby:postprocessor Webpack compilation started
Tue, 24 Jul 2018 07:04:28 GMT wallaby:uiService Incoming message ui:tests:resultsRequested
Tue, 24 Jul 2018 07:04:28 GMT wallaby:uiService Outgoing message ui:tests:allResultsUpdated
Tue, 24 Jul 2018 07:04:28 GMT wallaby:uiService Incoming message ui:start
Tue, 24 Jul 2018 07:04:28 GMT wallaby:uiService Outgoing message ui:summary
Tue, 24 Jul 2018 07:04:28 GMT wallaby:uiService Outgoing message ui:files
Tue, 24 Jul 2018 07:04:28 GMT wallaby:postprocessor Webpack compilation finished
Tue, 24 Jul 2018 07:04:28 GMT wallaby:postprocessor Emitting 306 files
Tue, 24 Jul 2018 07:04:28 GMT wallaby:project Postprocessor execution finished
Tue, 24 Jul 2018 07:04:28 GMT wallaby:project Test run started; run priority: 3
Tue, 24 Jul 2018 07:04:28 GMT wallaby:project Running all tests
Tue, 24 Jul 2018 07:04:28 GMT wallaby:workers Starting test run, priority: 3
Tue, 24 Jul 2018 07:04:28 GMT wallaby:chromeRunner Starting sandbox [worker #0, session #9xipu]
Tue, 24 Jul 2018 07:04:28 GMT wallaby:chromeRunner Preparing sandbox [worker #0, session #9xipu]
Tue, 24 Jul 2018 07:04:28 GMT wallaby:browserRunner Total files to load in sandbox: 4
Tue, 24 Jul 2018 07:04:28 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #9xipu]: http://localhost:49607/wallaby_sandbox0.html
Tue, 24 Jul 2018 07:04:28 GMT wallaby:chromeRunner Prepared sandbox [worker #0, session #9xipu]
Tue, 24 Jul 2018 07:04:28 GMT wallaby:workers [worker #0, session #9xipu] Running tests in sandbox
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /Users/martagalvehernandez/Library/Caches/WebStorm2017.2/wallaby/wallaby/tracer.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /Users/martagalvehernandez/Library/Caches/WebStorm2017.2/wallaby/wallaby/tracer.js from disk
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /jasmine@2.8.0/framework.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /jasmine@2.8.0/framework.js from disk
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/configurator.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /jasmine@2.1.3/configurator.js from disk
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/reporter.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /jasmine@2.1.3/reporter.js from disk
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /wallaby-webpack.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /wallaby-webpack.js from cache
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /____wallaby-bundle.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /____wallaby-bundle.js from cache
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /wallaby_webpack_entry.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /wallaby_webpack_entry.js from cache
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /src/app/app.component.spec.js.wbp.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /src/app/app.component.spec.js.wbp.js from cache
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/starter.js
Tue, 24 Jul 2018 07:05:28 GMT wallaby:middleware Serving /jasmine@2.1.3/starter.js from disk
Tue, 24 Jul 2018 07:09:40 GMT wallaby:uiService UI client disconnected
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService UI client connected
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Outgoing message ui:handshake
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Incoming message ui:start
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Outgoing message ui:summary
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Outgoing message ui:files
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Incoming message ui:tests:resultsRequested
Tue, 24 Jul 2018 07:09:42 GMT wallaby:uiService Outgoing message ui:tests:allResultsUpdated
