### ISSUE TITLE
Typescript default value on parameter is causing wallaby test build fails

### ISSUE THREAD

**Issue by jsobell** [wallabyjs/public#672]
### Issue description or question
Any idea why
`public validate(value, isRequired: boolean = true): Promise<boolean>`
returns the error
```
Runtime error: SyntaxError: Unexpected token =
Tue, 28 Jun 2016 04:18:16 GMT wallaby:workers Sandbox (active) [i7txx] error: SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (.\tests\specs\field-error-processor-tests.js:8:50)
    at Module._compile (module.js:435:26)
```

It's the default value that's causing it.
`public validate(value, isRequired: boolean): Promise<boolean>` works fine.
This used to work, so I've obviously changed something, but what? Any ideas?

### Wallaby.js configuration file

```javascript
var webpackConfig = require('./webpack.config');
var wallabyWebpack = require('wallaby-webpack');
var webpackPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'node_modules/chai/chai.js', instrument: false },
            {pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', load:false, instrument: false},
            {pattern: 'node_modules/property-resolver/**/property-resolver.js', load:false},
            {pattern: 'node_modules/bluebird/**/browser/bluebird.js', instrument: false},
            {pattern: 'src/**/*.ts', load: false}
        ],
        tests: [
            {pattern: 'tests/specs/**/*.ts'}
        ],
        env: { type: "node"},
        debug: true,
        testFramework: 'mocha'
    };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
A simple test works for me:
<img width="471" alt="screen shot 2016-06-28 at 2 42 16 pm" src="https://cloud.githubusercontent.com/assets/979966/16404040/84c3c17e-3d3e-11e6-955e-b45bf095bf39.png">

Your config contains a few unused things, like loading `webpack` config and `wallaby-webpack`. You are using `node` environment so those are not used. So your config may be a bit simpler:

```javascript
module.exports = function () {
    return {
        files: [
            'src/**/*.ts'
        ],
        tests: [
            'tests/specs/**/*.ts'
        ],
        env: { type: 'node'},
        debug: true
    };
};
```
But it shouldn't affect the issue. How does your `tsconfig.json` file look like?

**Comment by ArtemGovorov** [comment]
Ok, my guess is that your `tsconfig.json` sets up compilation to `ES6`, so your TypeScript gets compiled to ES6 (with default properties) and wallaby in WebStorm by default is using it's own node version (4.x) that doesn't fully support ES6. You may configure wallaby to [use your system's default node version](https://wallabyjs.com/docs/integration/node.html#node-version):
```javascript
module.exports = function () {
    return {
        ...
        env: { type: 'node', runner: 'node'}
    };
};
```
so if it supports default values, it should work.

**Comment by jsobell** [comment]
I am indeed compiling to ES6, and you suggestion did indeed solve the problem!
Now to fix the code to address the 25 failing tests that this revealed!

Many thanks for the speedy resolution!

Cheers,
 Jason
