### ISSUE TITLE
amdclean/require1k problem/question

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#673]
I don't use browserify or webpack. I try to use [amdclean](https://github.com/gfranko/amdclean) in production. Should I write postprocessor for it?

Also I tried to use [require1k](http://stuk.github.io/require1k/) (the config is below), but the problem is the following: tests aren't reloaded after modifications. 

### Wallaby.js configuration file
```javascript
module.exports = (wallaby) => {
	return {
		files: [
			{ pattern: 'tests/lib/require1k.min.js', instrument: false },
			{ pattern: '../build/node_modules/chai/chai.js', instrument: false },
			{ pattern: '../build/node_modules/mithril/mithril.js', instrument: false },
			{ pattern: 'js/**/*.ts', load: false }
		],
		tests: [
			{ pattern: "tests/**/*.ts", load: false }
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' })
		},
		env: {
			params: { runner: '--web-security=false' }
		},
		testFramework: 'mocha',
		debug: true,
		setup: function () {
			for (var i = 0; i < $_$testFiles.length; i++) {
				var p = $_$testFiles[i].path
				R('./' + p.substring(0, p.length - 3));
			}
		}
	}
}
```

Code editor or IDE name and version: Visual Studio Code Insiders build
OS name and version: Windows

### Questions

What can you advise, which way should I choose? 
Should I use webpack/browserify?
What is the more performant way to combine my scripts and rerun tests?

**Comment by ArtemGovorov** [comment]
I haven't used neither `amdclean` nor `require1k` before, neither we have had any users with this stack, so can't really tell if they work with wallaby or not. 

If you could share a sample project using those techs + the wallaby config that you've shared, I could run it locally to better answer your questions. From what I briefly see from the docs, `amdclean` may require writing a new postprocessor as you have mentioned.

Performance wise, using `amdclean` with a new postprocessor may or may not be an issue depending on whether the tool supports incremental compilation. Webpack and browserify support it, so when some file is changed, wallaby postprocessor for [webpack](https://github.com/jeffling/wallaby-webpack) and [browserify](https://github.com/wallabyjs/wallabify) are able to compile the change pretty fast. 

Without knowing those techs, I may suggest to try using webpack (just for your tests, you may of course keep using `amdclean` for your prod build), to see if it works for you. Or perhaps changing the TypeScript compiler setting to `amd` and using [require.js](https://wallabyjs.com/docs/integration/requirejs.html).
The [webpack config](https://wallabyjs.com/docs/integration/webpack.html) may look like:
```javascript
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({});
module.exports = (wallaby) => {
    return {
        files: [
            { pattern: 'js/**/*.ts', load: false }
        ],
        tests: [
            { pattern: "tests/**/*.ts", load: false }
        ],
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' })
        },
        env: {
            params: { runner: '--web-security=false' }
        },
        testFramework: 'mocha',
        debug: true,
        postprocessor: wallabyPostprocessor,

        setup: function () {
          // required to trigger test loading
          window.__moduleBundler.loadTests();
        }
    }
}
```
(note that wallaby config has to be in the same folder as node modules for this config, also [relative paths like `../` will not work](https://github.com/wallabyjs/public/issues/68) in your share config)

**Comment by andr2** [comment]
Thank you for the detailed answer!

I copied chai.js from relative folder to local libs folder. Now I have the following config:
```javascript
var path = require('path');
module.paths.push(path.resolve(process.cwd() + "/../build/node_modules"));

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({});

module.exports = (wallaby) => {
	return {
		files: [
			{ pattern: 'libs/chai.js', instrument: false, load: true },
			{ pattern: 'libs/mithril.js', instrument: false, load: true },
			{ pattern: 'js/**/*.ts', load: false }
		],
		tests: [
			{ pattern: "tests/**/*.ts", load: false }
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' })
		},
		env: {
			params: { runner: '--web-security=false' }
		},
		testFramework: 'mocha',
		debug: true,
		postprocessor: wallabyPostprocessor,
		setup: function () {
			window.assert = window.chai.assert;
			window.__moduleBundler.loadTests();
		}
	}
}
```

Now it is the following error in console:
```
[Info] Wed, 29 Jun 2016 05:35:37 GMT wallaby:workers Sandbox (active) [z6y1f] error: TypeError: 'undefined' is not an object (evaluating 'window.chai.assert')
[Error] Runtime error: TypeError: 'undefined' is not an object (evaluating 'window.chai.assert')
[Info] Wed, 29 Jun 2016 05:35:37 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: 'undefined' is not an object (evaluating 'window.chai.assert'), stack: http://localhost:59926/wallaby_sandbox0.html:10
```

In wallaby_sandbox0.html which I open in my browser I do not see any chai.js script tag inclusions.

Where is the problem?

**Comment by ArtemGovorov** [comment]
Thanks for checking the sandbox page. Missing file most likely means that wallaby couldn't find the file `libs/chai.js` in your project (relative to the wallaby config). Does it exist? If not and you wouldn't like to duplicate it, then perhaps a symlink may help?

**Comment by andr2** [comment]
Thank you, it finally works! The problem with chai.js was in libs->lib mistyping. (Maybe it would be great to add a warning when a pattern doesn't match any files?)

As you stated earlier relative external paths to node_module don't work. 
But there are these two lines in the log:
```
[Info] Wed, 29 Jun 2016 07:34:43 GMT wallaby:fs Symlink resolution for: d:\Projects\atlantic\build\node_modules\chai\chai.js
[Info] Wed, 29 Jun 2016 07:34:43 GMT wallaby:fs Symlink resolution for: d:\Projects\atlantic\build\node_modules\mithril\mithril.js
```

Does wallaby generate symlinks by itself but they don't work?

**Comment by ArtemGovorov** [comment]
> Does wallaby generate symlinks by itself but they don't work?

No, wallaby doesn't generate any symlinks.

> As you stated earlier relative external paths to node_module don't work. 

Yes, it's a limitation for now (wallaby has to be on the same level or higher than the node modules folder in order to add references to `files` list). But the limitation only affect those files that need to be loaded into the sandbox via `script` tags (those with `load: true`). Other node modules that your tests/app `require` can be resolved by webpack from anywhere with [this webpack setting](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories). Something like:

```javascript
var wallabyPostprocessor = wallabyWebpack({
  resolve: {
    modulesDirectories: [path.resolve(process.cwd() + "/../build/node_modules")]
  }
});
```

> Thank you, it finally works!

Awesome, thanks for the update!
