### ISSUE TITLE
feature request: multiple contexts

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#674]
This is kind of like #265, and in fact may be a duplicate.  It's a different way of solving the same problem.

Problems:

- Mocha needs to run itself.  This has already been addressed in #641 (thanks!)
- Mocha's matrix is somewhat large.  We test against:
  - Node.js @ v0.8, v0.10, v0.12, iojs-v3.x, 4.x, 5.x, and 6.x
  - Browser @ PhantomJS 1.x, IE8, Chrome (latest), Firefox (latest), Edge (latest), Safari (latest)
- The entire suite of tests for any given platform cannot run in the same instance of Mocha.
  - The root cause is architectural limitations; you cannot run test suite *A* with the `bdd` interface and test suite *B* with the `qunit` interface with the same instance.
  - These are split into many different `make` targets.  Running `make test` runs all of the targets.
  - We only get `bootstrap()` to choose the interface.  Is there another function we can call do to this configuration *per-file*? 
- A browser cannot execute a large portion of the integration tests, because they are built around the CLI.

So I'm thinking what I want is basically more *granular* control over how Wallaby runs--I should be able to specify a glob (or individual files) to run in Node.js, another glob to run in the Browser, a third to run in both.  Since we're bundling with Browserify, we need to be able to do that, too,

I realize launching a browser other than PhantomJS or Electron is not supported.  Chromium should have a headless mode sometime this decade, so I imagine that could be on the table eventually.  But, is there a architectural reason why it isn't possible to actually launch Firefox?  Is it a performance concern?  It begs the question where the responsibilities of Wallaby end.  

I am also having trouble envisioning a UI where the coverage for Node.js and the coverage for a browser could be *simultaneously* displayed inline.  For me, inline coverage isn't Wallaby's killer feature--it's the instantaneous execution of changed tests (I realize others may have a different opinion).

**Comment by ArtemGovorov** [comment]
[This feature request](https://github.com/wallabyjs/public/issues/89) to run multiple wallaby configurations a the the same time, and the [request to support different browsers](https://github.com/wallabyjs/public/issues/29) in future should cover everything you've described.

Launching Firefox or 5 different versions of node all at once is may of course have the performance impact. So far our philosophy had been:
- configure wallaby to run your tests with the fastest possible runner to help you through writing the bulk of your code and tests as as as possible.
- configure CI server to run tests on all platforms/OS/devices that you support. 

There's a plan for wallaby to [support CI scenario](https://github.com/wallabyjs/public/issues/72) at some point, but for now the focus is to help you to be more productive when writing your code (by running tests, but the emphasis is on the development time experience).
