### ISSUE TITLE
BUG?: Won't let you select a JS config file generated by TS config file

### ISSUE THREAD

**Issue by andrewconnell** [wallabyjs/public#679]
### Issue description or question
I have a TypeScript file that I use for the Wallaby config in the root of my project (`wallaby.conf.ts`). Part of my build process generates the `wallaby.conf.js` file... verified it's present on the file system. 

- when I run Wallaby, I get nothing... no tests run
- when I try to select the config file, the JS file doesn't show up as an option, only the `wallaby.conf.ts` file shows up... you can't even type in the name of the JS file as it won't find it and won't let you select it
- however if I delete the source `wallaby.conf.ts` file so only , Wallaby will then see the `wallaby.conf.js` file and run tests as designed

### Wallaby.js configuration file

```typescript
import { IWallabyConfig, IWallabyEnvironment } from 'wallaby';

class WallabyConfig implements IWallabyConfig {

  /**
   * @property  {string[]}  files - Collection of files to include when Wallaby 
   *                                copies to it's local cache. 
   */
  public files: string[] = [
      'src/**/*.ts',
      'package.json',
      '!src/**/*.spec.ts'
  ];

  /**
   * @property  {string[]}  tests - Collection of files that include tests.
   */
  public tests: string[] = [
    'src/**/*.spec.ts'
  ];

  /**
   * @property  {IWallabyEnvironment} env - Application runtime type.
   */
  public env: IWallabyEnvironment = <IWallabyEnvironment>{
    type: 'node'
  };

  /**
   * @property  {Object}  compilers - List of compilers and matching file patter.
   */
  public compilers: any = {
    'src/**/*.ts': this.wallaby.compilers.typeScript()
  };

  constructor(private wallaby: any) { }
}

module.exports = (wallaby: any) => {
  return new WallabyConfig(wallaby);
};
```

### Code editor or IDE name and version
Visual Studio Code v1.3.0

### OS name and version
OSX v10.11.5

### Wallaby Version
VS Code extension v1.0.19
Wallaby.js Core v1.0.255

**Comment by ArtemGovorov** [comment]
Wallaby.js displays configuration files using this pattern `'**/*wallaby*.*'`, so the .js` file should show up. When I'm trying to reproduce the issue, it's working as expected for me with the same OS and VS Code version:

![ui](https://cloud.githubusercontent.com/assets/979966/16687256/c6efba70-455a-11e6-9add-18edb466bea8.gif)

Do I have do to something differently to reproduce it? Could you please double check that the `.js` file does exist, and if so, cold you please share the sample project where the issue can be reproduced?

**Comment by andrewconnell** [comment]
If, with your `settings.json` for the user / workspace settings, you include something like this ([see VSCode docs here](https://code.visualstudio.com/docs/languages/typescript#_hiding-derived-javascript-files)):

```javascript
  "files.exclude": {
    "**/*.js":{"when":"$(basename).ts"},
    "**/*.js.map":true
  },
```

See the following. I have `wallaby.conf.ts` in the root, which I open. Then i try to select the config, but it only shows the `*.ts` file... no `*.js` file... I can't even type it in as you see. Then I open a terminal and do a `ls -1` to show the contents of the root folder... you can see the `*.js` file is present, Wallaby just isn't picking it up because I have the setting in the code snippet above to hide the JS file which is common... If you do TypeScript, you don't want to see dupe files everywhere.

![image](https://cloud.githubusercontent.com/assets/2068657/16699035/88c1c332-451f-11e6-94c6-f503d48a4075.png)

**Comment by andrewconnell** [comment]
Hmmm... suddenly it's working... but I didn't change anything. Just walked away from the computer for a few hours and tried it again and now Wallaby is running my tests. I still get the same experience as I see in the YouTube video I posted above, but tests are running now. 

Not sure if you want to leave it as an open issue/bug since you can't select the JS config file or not... feel free to close if you do.

**Comment by ArtemGovorov** [comment]
Thanks for the details. The issue here is that wallaby.js is using VS Code API (`workspace.findFiles`) to get the list of wallaby config file suggestions and the API doesn't return the entries excluded by `files.exclude`, because they don't belong to the workspace anymore.

Considering that once selected wallaby.js file doesn't have to be present in the workspace, the suggested way to select it in such cases would be to comment out the exclusions, select the config, restore the exclusions. This is only required once, the selected config file is then stored and can be used forever (until the file locations is changed).

There's also an automatic convention-based attempt to automatically select wallaby configuration. This is the reason why it works for you: `wallaby.conf.js` is one of the names that wallaby.js automatically checks for an existence (via a direct FS call), so in your case the manual config file selection is not even required.
