### ISSUE TITLE
Advanced glob patterns don't work with Browserify

### ISSUE THREAD

**Issue by Sanjo** [wallabyjs/public#680]
### Issue description

Advanced glob patterns don't work with Browserify. E.g. the `@(foo|bar)` pattern in the files or tests list will break the test execution when Wallabify is used.

### Wallaby.js configuration file

Reproduce: https://github.com/Sanjo/wallaby-browserify-sample/tree/glob-pattern-bug

Commit: https://github.com/Sanjo/wallaby-browserify-sample/commit/e4998884a672885d2c65841b48664e6895cd0167

```javascript
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
    // browserify options, such as
    // insertGlobals: false
  }
  // you may also pass an initializer function to chain other
  // browserify options, such as transformers
  // , b => b.exclude('mkdirp').transform(require('babelify'))
);

module.exports = function () {
  return {
    // set `load: false` to all of the browserified source files and tests,
    // as they should not be loaded in browser,
    // their browserified versions will be loaded instead
    files: [
      {pattern: '@(src)/*.js', load: false}
    ],

    tests: [
      {pattern: 'test/*Spec.js', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    bootstrap: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm 2016.1.3

### OS name and version

Linux (Ubuntu 14.04)

**Comment by ArtemGovorov** [comment]
Thanks for the report. The bug is fixed in Wallaby plugin 1.0.68.
