### ISSUE TITLE
Cannot use triple slash reference with test.ts files

### ISSUE THREAD

**Issue by cocogorilla** [wallabyjs/public#683]
### Issue description or question
When using triple slash references, working tests fail when a portion of fixture setup is moved to another file.  ReferenceError: Can't find variable: <modulename> where modulename is the name of the new file containing the moved fixture setup.

I've implemented reference ordering in my config as an effort to fix issue, no difference in behavior.

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
    return {
        files: [
            'bower_components/text-encoding/lib/encoding-indexes.js',
            'bower_components/text-encoding/lib/encoding.js',
            'bower_components/angular/angular.js',
            'bower_components/angular-animate/angular-animate.js',
            'bower_components/ui-bootstrap.js',
            'bower_components/jszip/dist/jszip.js',
            'bower_components/js-xlsx/dist/xlsx.js',
            'bower_components/papaparse/papaparse.js',
            'src/**/*.ts'
        ],
        tests: [
            'tests/**/*.ts'
        ]
        ,
        compilers: {
            'src/**/*.ts': w.compilers.typeScript({ orderFilesByReferenceComments: true })
        }
    }
}
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Not sure if the issue is related to the reference comments. 
Do you have your fixture setup files in here `tests/**/*.ts`?
Wallaby.js requires the `tests` pattern to [only include files with tests](https://wallabyjs.com/docs/config/files.html#tests), so any other test related files, like helpers, have to be listed under `files`. If your test file follow some naming pattern, liek end with `-test.ts`, you may do this:
```javascript
files: [
            ...
            'src/**/*.ts',
            'tests/**/*.ts'
            '!tests/**/*-test.ts'
        ],
        tests: [
            'tests/**/*-test.ts'
        ]
```
If it doesn't help, could you please create a small sample so I could reproduce the issue?

Another (not related to the issue) thing is that you may [set `instrument: false` flag](https://wallabyjs.com/docs/config/files.html#file-object) to your libraries (`bower_components`), to avoid the overhead of collecting code coverage for them:
```javascript
files: [
            {pattern: 'bower_components/text-encoding/lib/encoding-indexes.js', instrument: false},
            ...
]
```

**Comment by cocogorilla** [comment]
That did the trick.  By placing
    describe('fixtures', () => { });
at the top of my fixture file (which was in tests), the tests pass and reference errors to my fixture file drop out.

Also, thanks for the tips on instrument.

**Comment by cocogorilla** [comment]
Interestingly enough, I'm getting test passes for the first run after adding a test to the file.  But ever after, it complains that the file is missing, and cannot get the reference.  If I shut down the engine and restart it, the fixture file loads perfectly fine and passes my tests initially.  But again, the moment I alter a test, it fails until a restart.

**Comment by cocogorilla** [comment]
Ok, I'll admit at this point, I'm confused.  So here's a git repository... maybe a concrete example will help me get this figured out.

In this example proj, why doesn't Wallby see "TestFiles" module?  Typescript does.

https://github.com/cocogorilla/wallabyproj/

**Comment by ArtemGovorov** [comment]
I have created a [couple of pull requests](https://github.com/cocogorilla/wallabyproj/pulls) in your repo to fix it. As I have mentioned, any other test related files, like helpers, have to be listed under `files`. The issue in your case is that your file from `tests` depends on another file from `tests`. You don't need to add empty tests to your helpers/fixtures, test files are your entry points, anything they depend on should be in the `files` list.

Hope it makes sense, let me know if it works for you.

**Comment by cocogorilla** [comment]
I get it... makes sense.  Thanks.
