### ISSUE TITLE
Src files do not give real time feedback until test file is modified

### ISSUE THREAD

**Issue by blabute** [wallabyjs/public#685]
### Issue description or question
Hello,

I am able to get wallaby running (342 passing) but I do not get real time feedback when editing ES6 source files. A change in the source file instead shows that some lines are now uncovered by my tests even though they are still covered and should just be failing. If I run the project tests manually, I now get feedback that some tests are failing but all lines are covered. If I correct the change in the source file, it shows that the some lines are uncovered again. Rerunning the projects tests manually shows the tests are passing again. 
If I open a test file for an ES6 file and make a change, it now says 417 passing and I now get real time feedback when making changes in both src and test files.
I copied my src and test files into your https://github.com/wallabyjs/wallaby-es6-sample example and still got the same results.

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            {
                pattern: "test/Test.Base/node_modules/chai/chai.js",
                instrument: false
            },
            {
                pattern: "test/Test.Base/node_modules/sinon/pkg/sinon-1.17.3.js",
                instrument: false
            },
            {
                pattern: "src/UserAPI/Content.Global/wwwroot/vendor/jquery/jquery.js",
                instrument: false
            },
            {
                pattern: "src/UserAPI/Content.Global/wwwroot/vendor/jquery.hotkeys/jquery.hotkeys.js",
                instrument: false
            },
            {
                pattern: "src/UserAPI/Content.Global/wwwroot/vendor/jquery-tiny-pubsub/tiny-pubsub.js",
                instrument: false
            },
            {
                pattern: "src/UserAPI/Content.Global/wwwroot/vendor/moment/moment.js",
                instrument: false
            },
            {
                pattern: "test/UserAPI/Auto/Auto.MVCApplication.Tests/js/test/helpers/*.js",
                instrument: true
            },
            {
                pattern: "test/UserAPI/Content.Global.Tests/js/test/helpers/*.js",
                instrument: true
            },
            {
                pattern: "test/UserAPI/LaunchPad/LaunchPad.MVCApplication.Tests/js/test/helpers/*.js",
                instrument: true
            },
            { pattern: "src/UserAPI/Auto/Auto.MVCApplication/wwwroot/js/**/!(*.min.js)*.js" },
            { pattern: "src/UserAPI/Content.Global/wwwroot/js/**/!(*.min.js)*.js" },
            { pattern: "src/UserAPI/LaunchPad/LaunchPad.MVCApplication/wwwroot/js/**/!(*.min.js)*.js" },
        ],

        tests: [
            "test/UserAPI/Auto/Auto.MVCApplication.Tests/js/test/**/*.Tests.js",
            "test/UserAPI/Content.Global.Tests/js/test/**/*.Tests.js",
            "test/UserAPI/LaunchPad/LaunchPad.MVCApplication.Tests/js/test/**/*.Tests.js"
        ],

        testFramework: "mocha",

        preprocessors: {
            "src/UserAPI/Auto/Auto.MVCApplication/wwwroot/js/**/*.js": file => require("./test/Test.Base/node_modules/babel").transform(file.content, { sourceMap: true }),
            "src/UserAPI/Content.Global/wwwroot/js/**/*.js": file => require("./test/Test.Base/node_modules/babel").transform(file.content, { sourceMap: true }),
            "src/UserAPI/LaunchPad/LaunchPad.MVCApplication/wwwroot/js/**/*.js": file => require("./test/Test.Base/node_modules/babel").transform(file.content, { sourceMap: true })
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
> I copied my src and test files into your https://github.com/wallabyjs/wallaby-es6-sample example and still got the same results.

Is the issue reproducible for you on the original example without your source files? For example if you change [this line](https://github.com/wallabyjs/wallaby-es6-sample/blob/master/src/calculator.js#L5), do the tests run?

Could you please share the sample where I could reproduce the issue (a GitHub repo or an attached project archive)? A couple of files (source and test) should be enough, you may remove any business specific/sensitive logic from it if you like.

**Comment by blabute** [comment]
The issue is not reproducible on the original example without my source files. When that line is changed the tests do run as expected.

I have made changes to the calculator.js and calculatorSpec.js files to simulate what our code is like.

### calculator.js

```javascript
'use strict';

class Calculator {
    add(a, b) {
        return a + b;
    }
}

class UsingMyCalculatorClass {
    result() {

        let calculator = new Calculator();

        return calculator.add(1, 2);
    }
}

var UsingMyCalculator = (function () {
    var calculator = new Calculator();

    return {
        result: calculator.add(1, 2)
    };
}());
```

### calculatorSpec.js

```javascript
describe('calculator', () => {

    it('should add numbers', () => {
        let calculator = new Calculator();
        expect(calculator.add(2, 2)).toBe(4);
    });
});

describe('UsingMyCalculatorClass', () => {

    it('should use calculator to add 1 + 2', () => {
        let calculator = new UsingMyCalculatorClass();
        expect(calculator.result()).toBe(3);
    });
});

describe('UsingMyCalculator', () => {

    it('should use calculator to add 1 + 2', () => {
        let result = UsingMyCalculator.result;
        expect(result).toBe(3);
    });
});
```

In UsingMyCalculatorClass, if I change return calculator.add(1, 2); to return calculator.add(2, 2);, wallaby gives real-time feedback that a test is failing.

In UsingMyCalculator, if I change result: calculator.add(1, 2) to result: calculator.add(2, 2), I don't get feedback that the tests are failing. If I run the project tests manually, I am informed that a test is failing.

**Comment by ArtemGovorov** [comment]
Wallaby.js determines what tests to run for some code based on the fact that some test has actually executed this code. In this particular case, wallaby.js can not automatically execute the test when you change UsingMyCalculator, because this code wasn't executed by any test:
```javascript
var UsingMyCalculator = (function () {
    var calculator = new Calculator();

    return {
        result: calculator.add(1, 2)
    };
}());
```
As opposed to other functions that were executed by tests, this code was executed as a part of loading the file and not by any particular test, so there's no way to understand that certain tests should be triggered when changing the code.

Unlike 2 other tests that actually execute some code, the third test only accesses the global `UsingMyCalculator.result` and not causing any code to execute.

If you change the code to actually execute at least something by a test, for example:
```javascript
var UsingMyCalculator = (function () {
  var calculator = new Calculator();

  return {
    result: function () {
      return calculator.add(1, 2);
    }
  };
}());
```
then wallaby will be able to automatically execute the test when you change the `return calculator.add(1, 2);`.

Hope it makes sense.

**Comment by blabute** [comment]
Sorry, my example was poor and did not reflect my team's source and test files.
Wallaby is working on my machine with our solution as expected but some other team members are having issues as I have described above. 
I will remove the business logic from our source files and re-open this issue when I have an opportunity to do so.

Thanks for the quick responses.

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
