### ISSUE TITLE
Wallaby not picking up all tests (possible recursive issue)

### ISSUE THREAD

**Issue by sattaman** [wallabyjs/public#688]
### Issue description or question

npm test uses the following 

```
"scripts": {
    "test": "mocha --require ./src/test/setup.js --recursive ./src/**/test/**/*.spec.js --compilers js:babel-core/register"
  },
```

And this picks up all tests. However I have been unable to recreate this in mockery. 
For instance mockery is not picking up tests in src/js/settings/test/components/navigation. 
How can I recreate the above mocha script with mockery? 

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      {"pattern": "src/js/__OLD__/**/*.js", "ignore": true},
      './src/test/setup.js',
      './src/js/**/*.js',
      './src/js/**/*.json',
    ],

    tests: [
      './src/**/test/**/*.spec.js',
    ],

    env: {
      type: 'node',
      runner: 'node'  // or full path to any node executable
    },

    debug: true,

    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babelrc: 	true
      })
    },

    setup: function() {
        require('./src/test/setup.js');
    }
  };
};

```

### Code editor or IDE name and version

WebStorm v11

### OS name and version
OSX El Capitan

**Comment by ArtemGovorov** [comment]
I have created a sample to reproduce your file structure and config and was able to reproduce the issue. The Wallaby Console however suggest the reason why it's not working:
<img width="1159" alt="screen shot 2016-07-15 at 8 48 53 pm" src="https://cloud.githubusercontent.com/assets/979966/16871983/6f8faf06-4acd-11e6-918c-74ed594eba92.png">
When I did as suggested and added the `{ pattern: 'src/**/test/**/*.spec.js', ignore: true }` to the `files` list, it worked for me. 
Could you please try doing the same to see if it helps?

**Comment by sattaman** [comment]
Ah that's fixed it! I hadn't seen that message , but then my console has crazy amounts of output. 

Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> I hadn't seen that message , but then my console has crazy amounts of output.

If you remove the `debug: true,` setting from the config, it'll only show important stuff in the console.
