### ISSUE TITLE
Support more glob patterns

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#69]
Most of my wallaby config file and test arrays are copies from the ones in karma.conf.js.
I took me some time to get Wallaby working for some larger apps with more complex file patterns. I have the feeling that the `(xxx/yyy)` pattern is not supported.
When I have `'app/scripts/**/*.+(html|js)'` in my files list, the js files are not loaded, but when I have two separate lines for html and js, everything works fine.

**Comment by abelnation** [comment]
grunt-style globbing please!  awesome awesome tool!

**Comment by ArtemGovorov** [comment]
Happy to finally add the support. Now you can use any patterns supported by glob/minimatch. Landed in IntelliJ plugin v1.0.42.
