### ISSUE TITLE
Can't require meteor modules from coffeescript files

### ISSUE THREAD

**Issue by jdrucza** [wallabyjs/public#691]
### Issue description or question

I'm trying to use wallaby on a meteor app and thus have started with xolvio's wallaby server config.
However it fails to find any meteor modules. I've raised an issue on the xolvio repo: https://github.com/xolvio/automated-testing-best-practices/issues/52

And created a sample project demonstrating the problem here: 
https://github.com/jdrucza/coffee-wallaby
### Wallaby.js configuration file

See repo: https://github.com/jdrucza/coffee-wallaby/blob/master/.wallaby_server.js
### Code editor or IDE name and version

Rubymine 2016.1.1
### OS name and version

OSX 10.11.5

**Comment by ArtemGovorov** [comment]
From the wallaby side of things, the config looks good. 

Unfortunately, I don't know `meteor` well enough to be able to tell why its modules are not loaded. The issue doesn't seem to be CoffeeScript specific, if you add `require('meteor/meteor')` to any of the original repo files, you'll get the same error, so I'm not even sure this ever worked.

As far as I know, Xolvio's guys provide some [dedicated support on the subject](http://xolv.io/services/meteor-testing-support/), so you may try to contact them directly if you'd like the issue to be addressed ASAP. /cc @samhatoum @Sanjo

**Comment by jdrucza** [comment]
Thanks for the prompt reply. I will take it up with the xolvio guys as I'm very keen to take advantage of wallaby.

**Comment by smcenlly** [comment]
Closing this issue out as it is very old.
