### ISSUE TITLE
Wallaby.js App: how to switch between projects?

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#692]
Hello @ArtemGovorov,

Could you please tell how to switch between projects?

I have multiple running projects, but http://wallabyjs.com/app shows only first project.

**Comment by carlansley** [comment]
I've found if you open a new browser tab you'll get one or more "Discovered running wallaby.js project, Click here to open XXX" pop-up dialogs in the top right; if you click before they disappear it will switch to that project.  Not ideal but gets the job done.

**Comment by mdreizin** [comment]
@carlansley Thanks for that workaround, but it would be nice to have more elegant way.

**Comment by ArtemGovorov** [comment]
Yes, currently it is the only way. Once you switch to another project, we remember it in that tab and even if you refresh it, wallaby app will try to connect to that project first.
We are thinking how to make it better from the UI perspective.

**Comment by steebchen** [comment]
It would be cool if you could simply click on the title which gets display at the top-right. The app name stands there but does nothing, so when clicking it, you could show a list of detected projects. But the solution as it is currently is okay too for now.

**Comment by mdreizin** [comment]
@ArtemGovorov Do you have any updates on this?

**Comment by ArtemGovorov** [comment]
@mdreizin Not yet.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks. Looking forward to have such feature ;)

**Comment by evgygor** [comment]
This workaround doesn't works for me. Only first opened project displayed in app.
Maybe it's some issue in my config?

**Comment by ArtemGovorov** [comment]
@evgygor What browser are you using? Also the popup with another discovered project may take few seconds to appear.

**Comment by evgygor** [comment]
Thanks

**Comment by colombod** [comment]
I am doing this in chrome and edge (both latest version) and I can only see it open the first project (or first vs code that I started using wallaby with) and never gets any notification to open the other project there

**Comment by ArtemGovorov** [comment]
@colombod It may take a few seconds for the notification to appear. Also try restarting your browser to see if it helps.

**Comment by ArtemGovorov** [comment]
@colombod We have discovered and fixed the issue (it looks like it's only affecting some Windows configurations that allow HTTP server port sharing between processes). 
Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, restart all your running Wallaby instance and the issue should be resolve for you.

**Comment by smcenlly** [comment]
You can now switch between projects in Wallaby App with the `Select project (Alt + 3)` icon. 

![image](https://user-images.githubusercontent.com/2074089/70594152-539a1600-1c2b-11ea-87a9-66d07344d341.png)
