### ISSUE TITLE
Wallaby.js is stopped because your license is being used elsewhere on the network

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#693]
### Issue description

After last update I have started experiencing the following issue:

```
Wallaby.js is stopped because your license is being used elsewhere on the network by xxx (0.0.0.0).  Only one active computer at the same time may use the license.  If you would like to purchase an additional license, please visit our website. 
```

```
Wallaby v1.0.68
Core v1.0.259
```

### Code editor or IDE name and version

WebStorm 2016.2

### OS name and version

OSX 10.11.5

**Comment by ArtemGovorov** [comment]
Most likely there's a not correctly stopped wallaby.js core process still running on the machine (may happen when IDE or wallaby plugin crashes for some reason). Try killing all node processes (or restart the machine) and start wallaby, it should help.

**Comment by ArtemGovorov** [comment]
@rolfb Looks like there may be some orphaned Wallaby processes running on your machine. Try closing your editor, killing all `node` processes on your machine and then start Wallaby - it should help.

**Comment by rolfb** [comment]
@ArtemGovorov - Thanks, it was easy enough to solve, but would be nice to have multiple projects running at the same time regardless :-) Love the project

**Comment by ArtemGovorov** [comment]
@rolfb Th scenario of running multiple projects running at the same time on the same machine is supported.
