### ISSUE TITLE
Wallaby.js app: Tests tree filters and search

### ISSUE THREAD

**Issue by maierson** [wallabyjs/public#694]
### Issue description or question

Truly excellent app already! Thank you for this.

One suggestion: Can the test list on the left be filterable as such ? :
- show only failing tests  when clicking the FAILED count on the top right hand corner
- show tests containing components below a certain (configurable) coverage threshold (ie show me all my tests that have components that are below 50% covered).
- search: if searching for a test file - find and show the file in the test file list on the left instead of showing its preview. The preview can then be launched from the test line but more can be inspected about the test file. For files under test - preview is good as is.

**Comment by ArtemGovorov** [comment]
Thanks for the feedback!
We are planning to add some filters as you've suggested and also a better tests tree search.
Regarding the components below a certain (configurable) coverage threshold, it'll be addressed in the "Files/Coverage" view that what [we are working on at the moment](https://github.com/wallabyjs/public/issues/38#issuecomment-233571999).

**Comment by NikGovorov** [comment]
Hi @maierson,

Thanks for your feedback, we implemented tests tree filtering feature in Wallaby.js App v1.0.52.
