### ISSUE TITLE
Wallaby fail when setting Typescript Compiler to ES6

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#695]
### Issue description or question
When changing **compilerOptions.target** in **tsconfig.json** from **es5** to **es6** wallaby fails to run unit tests.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/typescript.events.ts'
    ],
    tests: [
      'test/typescript.events.test.ts'
    ],
    testFramework: 'mocha',
    env: {
        type: 'node'
    },
    debug: true
  };
};
```
### Code editor or IDE name and version
Visual Studio Code v1.3.1

### OS name and version
Windows 10 Enterprise

**Comment by FlippieCoetser** [comment]
Updating Wallaby.js configuration file to include **--harmony** flag resolve issue.

### New Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/typescript.events.ts'
    ],
    tests: [
      'test/typescript.events.test.ts'
    ],
    testFramework: 'mocha',
    env: {
        type: 'node',
        params: {
          runner: '--harmony'
        }
    },
    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
You may also consider updating your node.js to the latest (or to the one that does support ES6 without the `--harmony` flag).
