### ISSUE TITLE
Coverage summary in wallaby app

### ISSUE THREAD

**Issue by mvestergaard** [wallabyjs/public#696]
First of all, the app is a cool idea, looking forward to see how it evolves.

This may already be planned given the "Tests" tab, but I thought I'd add the suggestion anyway.

Could you add a "Files" tab that shows kind of the inverse of what the "Tests" tab shows.
A list of each file and the coverage % of each. Maybe also the ability to view the tests covering each file.

This would greatly help pinpoint files that need more coverage.

**Comment by ArtemGovorov** [comment]
Thanks for the feedback. "Files" view is exactly what [we are working on at the moment](https://github.com/wallabyjs/public/issues/38#issuecomment-233571999).
