### ISSUE TITLE
setup minimal angular 1.x with typescript

### ISSUE THREAD

**Issue by ofauno** [wallabyjs/public#698]
### Issue description or question
hi 😄  was trying to setup a simple angular 1.x with typescript
and on the test side seems to happen nothing, I googled and githubed multiple
similar projects but no one as simpler as mine, all boils down to use webpack helpers or
postprocessor but this repo I just plain minimal angular app

https://github.com/jamons/tdd-angular-typescript 

it ends up like:

![app_spec_ts_-_ng-tdd-ts](https://cloud.githubusercontent.com/assets/1057021/17007935/5434ce74-4eb2-11e6-8c6f-3d064dc537d7.jpg)

> ​0  failing tests, 0 passing

weird since I use wallaby with simple plain old js with ts and it works great 👍 
regards 💃 

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        testFramework: 'mocha',
        debug: true,
        files: [
            {
                pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false
            },
            { 
                pattern: 'node_modules/angular/angular.js', 
                instrument: false
            },
            { 
                pattern: 'node_modules/angular-mocks/angular-mocks.js', instrument: false 
            },
            { 
                pattern: "node_modules/bardjs/dist/bard.min.js", 
                instrument: false 
            },
            { 
                pattern: 'node_modules/chai/chai.js', 
                instrument: false 
            },
            { 
                pattern: 'node_modules/sinon/pkg/sinon.js', 
                instrument: false 
            },
            { 
                pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', 
                instrument: false 
            },
            { 
                // pattern: 'src/*.js',
                pattern: 'src/*.ts', 
                load: false 
            }
        ],
        tests: [
            {
                // pattern: 'test/*.spec.js', 
                pattern: 'test/*.spec.ts', 
                load: false
            }
        ]
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.3.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I have sent you the PR https://github.com/jamons/tdd-angular-typescript/pull/1, you need to remove `load: false` from your `files`/`tests`, it's normally used for webpack that has to compile/process files before loading and loads them in the `setup` function, but in your case you just want to [load these files](https://wallabyjs.com/docs/config/files.html#file-object) into the sandbox.

**Comment by ArtemGovorov** [comment]
Another issue I saw is that loading minified bard source doesn't seem to work, but changing it like so
```
pattern: "node_modules/bardjs/dist/bard.js",
```
seems to fix it. There're still other errors, like `app.dashboard` is missing, but they seem to be specific to your app code and you probably have a better why it happens (perhaps the module is not defined).

**Comment by ofauno** [comment]
@ArtemGovorov now it works like a charm man, added those tweaks 👍  💃 kudos

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
