### ISSUE TITLE
Cannot find module server.js

### ISSUE THREAD

**Issue by Burgov** [wallabyjs/public#699]
### Issue description or question
I installed wallaby .68 on my windows instance of WebStorm. Our license expired a while ago, so I fetch the latest version still covered, which is .66, and installed that instead. Now when I run it, I get the following error:

```
module.js:339
    throw err;
    ^

Error: Cannot find module 'C:\Users\Bart\.WebStorm2016.1\system\wallaby\wallaby\server.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

I checked, and while the folder `C:\Users\Bart\.WebStorm2016.1\system\wallaby` exists, `C:\Users\Bart\.WebStorm2016.1\system\wallaby\wallaby` doesn't.

### Wallaby.js configuration file

```javascript
n/a
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report. We'll fix the issue with еру fresh install for expired licenses soon. In a meantime, please do this:
- Download https://s3.amazonaws.com/wallaby-downloads/wallaby-v1.0.243.zip,
- Extract the archive to `C:\Users\Bart\.WebStorm2016.1\system\wallaby\wallaby`.
- Start wallaby.js.

**Comment by Burgov** [comment]
Thanks! That worked
