### ISSUE TITLE
Error: One of your tests is trying to unload window object.

### ISSUE THREAD

**Issue by iamdudley** [wallabyjs/public#700]
### at http://localhost:50084/**wallaby**/tracer.js:14

I'm trialing WallabyJs and I consistently get the error above when running my javascript tests via Wallaby. It doesn't crash Wallaby but simply reports the test as a fail. It errors out on the same test every time. However, if I go to the test and click "Run file tests" in the Context Menu the test runs and passes and I get the nice green squares instead of the pink fail squares. This isn't too much of a worry but it isn't great. 

What is annoying is if this happens when Wallaby is starting for the first time. It can hang the process and I have to restart Wallaby. There is no guarantee that the error won't happen again. It seems to be quite random as to when it happens. Sometimes I've given up trying to start Wallaby because the error keeps blocking Wallaby from starting cleanly. 

Currently we have 567 unit tests. This number is continuing to grow. We use Jasmine for testing with tests and source written mostly in Typescript with a few plain javascript files. We use Chutzpah to run our javascript unit tests both locally and on our CI build machines.

Here is the relevant part of the debug console log

> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: for PreviewManager should use the correct navigation strategy
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed:  null
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed:  undefined
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: should return correct value
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Sandbox (active) [mgimr] error: Error: One of your tests is trying to unload window object.
> Runtime error: Error: One of your tests is trying to unload window object.
> at http://localhost:50413/**wallaby**/tracer.js:14
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Failed to map the stack to user code, entry message: >Error: One of your tests is trying to unload window object., stack: Error: One of your tests is trying to >unload window object.
> at http://localhost:50413/**wallaby**/tracer.js:14
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Run 107 test(s), skipped 0 test(s)
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Sandbox (active) [mgimr] error: Error: One of your >tests is trying to unload window object.
> Runtime error: Error: One of your tests is trying to unload window object.
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Failed to map the stack to user code, entry message: Error: One of your tests is trying to unload window object., stack: http://localhost:50413/**wallaby**/tracer.js:14
> 
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:middleware Preparing to serve >/httpAppendicesViewer/PrefillManagerPreview
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:middleware Serving /httpAppendicesViewer/PrefillManagerPreview from disk
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: should create EmptyRowStrategy if only one row
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: should initialize EmptyRowStrategy correctly
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: should delete row from grid
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Test executed: should delete and add empty row to grid
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:middleware ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Local\Temp\1.wallaby\projects\FG57vVlzA+WewEWCpi1WInb+g1k=\cache\instrumented\httpAppendicesViewer\PrefillManagerPreview'
> Thu, 21 Jul 2016 20:38:54 GMT wallaby:workers Run 86 test(s), skipped 0 test(s)
### Wallaby.js configuration file

``` javascript
// paste your config here
```

**Comment by ArtemGovorov** [comment]
Wallaby subscribes to the window `beforeunload` event and throws the above mentioned error. This means that some of your tests is causing the window to unload, and that what the error message is reporting. 

I wouldn't recommend ignoring the error, it's important to fix. Something in your code/tests causes the window of the testing sandbox page to unload. It such test succeeds in doing so, anything running after it may simply not execute. The worst part is that you may not even now about it, so wallaby notifies you about it.

The reason why it sometimes happens and sometimes not is that wallaby runs your tests in parallel and executes only affected tests, so doesn't run your tests always in the same order (as Chutzpah). It may start affecting Chutzpah is the execution order of your tests changes as a result of refactoring for example.

You said you know what test is causing the issue, is it navigating somewhere somehow? Perhaps changing the window location, opening other URL, etc. I have noticed your log mentioning tests of `navigation strategy`, perhaps it's related. If you know what test it is, you may probably mock some code to make it not navigate away from the testing sandbox - there's no need to really navigate away anyway as there's nothing that can be tested/asserted about it.

**Comment by iamdudley** [comment]
Thanks for the quick reply. I'll have a look at that on Monday.

James.
