### ISSUE TITLE
Test-files starting with a dot

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#701]
### Issue description or question
Test-file is invisible for wallaby if the file starts with a dot (`.tests.ts` for example)

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
	var path = require('path');
	process.env.NODE_PATH = path.resolve(process.cwd() + "/../build/node_modules");

	return {
		files: [
			{ pattern: '../build/node_modules/mithril/mithril.js', instrument: false },
			{ pattern: 'lib/mithril.js', instrument: false },
			{ pattern: '../build/node_modules/chance/chance.js', instrument: false },
			'**/*.ts',
			"!**/*.tests.ts", "!**/.tests.ts",
		],
		tests: [
			"**/*.tests.ts", "**/.tests.ts"
		],
		compilers: {
			'**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs', moduleResolution: 'node' })
		},
		env: {
			type: 'node'
		},
		testFramework: 'mocha',
		setup: function () {
			global.assert = require('chai').assert;
			global.m = require('mithril');
		}
	}
}
```
VSCode insiders build
Windows 10

**Comment by ArtemGovorov** [comment]
Wallaby.js is using the default glob matching settings and the `.tests.ts` file name doesn't match the `**/*.ts` pattern:
```
> require('minimatch')('.tests.ts', '**/*.ts')
false
```
You may do this:
```javascript
var tsCompiler = wallaby.compilers.typeScript({ module: 'commonjs', moduleResolution: 'node' });
...
compilers: {
            '**/*.ts': tsCompiler,
            '**/.*.ts': tsCompiler
        },
```
Let me know if it addresses the issue for you.

**Comment by andr2** [comment]
In config-file I have `"**/.tests.ts"`, and minimatch returns true for this:
```
> require('minimatch')('path/.tests.js', '**/.tests.js')
true
```

But wallaby ignores the file

**Comment by andr2** [comment]
Ah, I understand that the problem is in `compilers` section. But this config also doesn't work:
```
module.exports = (wallaby) => {
	var path = require('path');
	process.env.NODE_PATH = path.resolve(process.cwd() + "/../build/node_modules");

	var tsCompiler = wallaby.compilers.typeScript({ module: 'commonjs', moduleResolution: 'node' });
	return {
		files: [
			{ pattern: '../build/node_modules/mithril/mithril.js', instrument: false },
			{ pattern: 'lib/mithril.js', instrument: false },
			{ pattern: '../build/node_modules/chance/chance.js', instrument: false },
			'**/*.ts',
			"!**/*.tests.ts", "!**/.tests.ts",
		],
		tests: [
			"**/*.tests.ts", "**/.tests.ts"
		],
		compilers: {
			'**/*.ts': tsCompiler,
			'**/.tests.ts': tsCompiler
		},
		env: {
			type: 'node'
		},
		testFramework: 'mocha',
		setup: function () {
			global.assert = require('chai').assert;
			global.m = require('mithril');
		}
	}
}
```
Wallaby simply ignores `form/.tests.ts`

**Comment by ArtemGovorov** [comment]
Thanks for providing more details. There was indeed a bug in the watcher, it's now fixed in the core v1.0.265. It should update automatically within a few minutes during wallaby restarts, here is how to [force the upgrade](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to happen immediately.

**Comment by andr2** [comment]
Thanks a lot, now it works correctly!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by faceyspacey** [comment]
@ArtemGovorov this pattern doesn't work either:

```{ pattern: '.storybook/**/*.js', load: false },```

**Comment by ArtemGovorov** [comment]
@faceyspacey Just tried the pattern and it's working for me:
![screen shot 2017-02-26 at 12 55 42 pm](https://cloud.githubusercontent.com/assets/979966/23336704/43ac1b38-fc23-11e6-8bbb-659bb23d66db.png)

Any hints how to reproduce the issue? Perhaps you could share a sample repo?

**Comment by faceyspacey** [comment]
```
git clone git@github.com:faceyspacey/animated-transition-group.git
yarn
npm test // to see that jest testing works properly
```

In, the file `stories/index.js` you will see that it fails to import a mocked file on line 7:

![wallabyshot](https://cloud.githubusercontent.com/assets/154732/23336790/d86094e2-fb8e-11e6-8ed3-43e561def41d.png)

If you `cd` into the `project/id/instrumented` directory you will see that the `.storybook` folder does not get added, even though its supplied in the wallaby `files` config.

**Comment by ArtemGovorov** [comment]
Cloned the repo, but I can see the folder and of the files in it being copied:

<img width="211" alt="screen shot 2017-02-26 at 1 35 36 pm" src="https://cloud.githubusercontent.com/assets/979966/23336876/8c959a18-fc28-11e6-8395-e474270d6b07.png">

**Comment by faceyspacey** [comment]
that's very weird. for me, it's not being copied.

**Comment by ArtemGovorov** [comment]
What's your OS and node.js version?

**Comment by faceyspacey** [comment]
damn my bad. i forgot to run `ls -a` i.e. with the `-a` param. ..it's being copied, but the test isn't working within wallaby. is it working for you?

**Comment by faceyspacey** [comment]
OSX 10.11.6
NODE v7.0.0

**Comment by ArtemGovorov** [comment]
@faceyspacey Nope, the test isn't working, but it's definitely not because of the missing files, because the files are there. Will have a look into it.

**Comment by faceyspacey** [comment]
To see if it had to do with jest's mocking functionality, i've tried not mocking it as well and it still can't get that `facade.js` file. It seems it's struggling to dig into a hidden directory.

**Comment by ArtemGovorov** [comment]
@faceyspacey Looking into the `instrumented/.storybook/__mocks__/facade.js` - the file is instrumented, but it looks like ES6 `import`s are not compiled to CommonJs for some reason.

**Comment by faceyspacey** [comment]
same with the `instrumented/.storybook/facade.js` ....it must have to do with storybook's way of operating, rather than that hidden folder.

**Comment by ArtemGovorov** [comment]
I think I found the reason. It may sound unintuitive, but for example a file `.storybook/facade.js` doesn't match this glob pattern: `**/*.js`. You may check it yourself:

> node
> require('minimatch')('.storybook/facade.js', '**/*.js')
> false

So the compiler doesn't compile those files in the `.storybook` folder. Here's the solution:

```javascript
const compiler = wallaby.compilers.babel({ babelrc: true, presets: ['babel-preset-jest'] });
...
    compilers: {
      '**/*.js': compiler,
      '.**/**/*.js': compiler
    },
...
```

After you do this, you'll see another (and not related issue). You'll need to exclude `.snap` files from your `tests` list and include them into the `files` list, as [specified in the docs](https://wallabyjs.com/docs/config/files.html#tests).

**Comment by faceyspacey** [comment]
excellent, it works! thanks brother. ...it's not requiring me to exclude `.snap` files from my `tests` list, but if it ever does, i know what to do. thanks again.
