### ISSUE TITLE
VS2015 some blocks are grey when they should have executed (and be green)

### ISSUE THREAD

**Issue by bmjjohn** [wallabyjs/public#702]
### Issue description or question
In VS2015 some blocks are grey when they should have executed. 

In my example the promise rejects so should fall through to the catch block, but Wallaby is colouring these blocks grey. 

See image below - _surely the 2 blocks in the catch() and final then() should be green?_ 

```javascript
describe('Promise test', function() {
    it('Reject in first stage', function () {
        var error = null;

        new Promise(function (a, r) {
            return r('reject 1');

        }).then(function () {
            return new Promise(function (a, r) {
                throw Error('this should not run');

                return a('accept 2');
            });

        }).catch(function (msg) {
            chai.assert.equals(msg, 'reject 1');
            error = msg;

        }).then(function() {
            chai.assert.equal(error, 'reject 1');
        });
    });
});
```

### Wallaby.js configuration file

```javascript
module.exports = function() {
    return {
        files: [
            { pattern: 'tests/lib/chai.js', instrument: false },
            { pattern: 'tests/lib/sinon.js', instrument: false },

            { pattern: 'lib/json2.js', instrument: false },
            { pattern: 'lib/jquery.min.js', instrument: false },
            { pattern: 'lib/underscore.js', instrument: false },
            { pattern: 'lib/backbone.js', instrument: false },
            { pattern: 'lib/es6-promise.min.js', instrument: false },

            'templates/templates.js',
            'js/models.js',
            'js/views.js',
            'js/routes.js'
        ],
        tests: [
            'tests/*Spec.js'
        ],

        debug: true,
        testFramework: 'mocha',

        delays: {
            run: 500
        }                
    };
};
```

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
Windows

![image](https://cloud.githubusercontent.com/assets/5877999/17059387/c981a678-501c-11e6-8a6e-c02017a22af0.png)

**Comment by ArtemGovorov** [comment]
It looks like your test is sync, so as soon as the sync part is executed, the test is over. It's similar to this:
```javascript
it('Reject in first stage', function () {
       setTimeout(function () {
            console.log(123);
        }, 300);
});
```
the `console.log` will not be executed because the test is sync and ends before that.
What you probably need is an async mocha test:
```javascript
it('Reject in first stage', function (done) {
       setTimeout(function () {
            console.log(123);
            done();
        }, 300);
});
```
In your case it's a bit easier, because `mocha` supports promises and instead of passing the `done` callback, you may just return the [promise form the test](http://stackoverflow.com/questions/26571328/how-do-i-properly-test-promises-with-mocha-and-chai), so that mocha automatically waits until it's resolved or rejected:
```javascript
describe('Promise test', function() {
    it('Reject in first stage', function () {
        var error = null;
        return new Promise(function (a, r) { // <- return
        ...
```

Let me know if it addresses your question.

**Comment by bmjjohn** [comment]
Yes, that fixed it!

Thanks for the fast response.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Please note that the issue is not wallaby specific, plain mocha works the exact same way.
