### ISSUE TITLE
Can't see difference between red/green squares on left hand side of debug window!

### ISSUE THREAD

**Issue by pfister** [wallabyjs/public#703]
How does person with red/green color blindness see changes between pass or fail if the squares on lefthand side of debug code window use same shade of green (pass) and of red (fail)?????

I have significant red/green colorblindness.  About 8 percent of all males and about 0.5 percent of all females have red/green colorblindness.

I can see some change in shade/intensity for the other colors, but the red and the green that the wallaby defaults to, are virtually the same shade/intensity, so it is like nothing happened when changing a test's condition from pass to fail or vise versa!

For Visual Studio Code, I would appreciate detailed instructions on how to change the debug square colors used to signify 'pass', 'fail', etc.

**Comment by pfister** [comment]
While you are at it, don't depend on only color to signify status. Why not also change the shape between pass, fail, etc. 

Square or Circle for good. 

Diamond for bad.

All user/developer configurable.

**Comment by pfister** [comment]
Figured it out.  And found an acceptable color scheme. 

For VS Code, under Preferences > User Settings - Added following property to settings.json file:

,
  "wallaby.colors": {
        "covered": "#006600",
        "errorPath": "#ffa0a0",
        "errorSource": "#fe536a",
        "notCovered": "#e60000",
        "partiallyCovered": "#ffa64d"
}

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
I'll check to see what it'd take to make the shapes configurable as well.

**Comment by sawasawasawa** [comment]
@ArtemGovorov is there any chance on adding the shapes options for IntelliJ as well? An `x` within the red square would make life much easier :)

**Comment by sawasawasawa** [comment]
![Zrzut ekranu 2019-08-19 o 09 07 12](https://user-images.githubusercontent.com/11598147/63245607-e3711a00-c260-11e9-8d56-8ffb90944f10.png)
Found that in config, but these fields are disabled - I can edit only the background color. 

Webstorm 2019.2, Wallaby.js 1.0.136
