### ISSUE TITLE
click() and trigger('click') doesn't work

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#705]
### Issue description or question
We have a Angular 1 + TypeScript application which also uses ag-grid.
We have a test that clicks the columnheader of the grid to test the filter.
When we use element.find('<some selector>').click(), it works well in Karma, and the filter div is created in DOM and we can test it. But when this runs from Wallaby.js, it seems nothing happens, and the filter div is not added to the DOM.
If we change the call to click() to 
```
                var clickEvent = document.createEvent('MouseEvent');
                clickEvent.initEvent('click', true, true);
                domElement.dispatchEvent(clickEvent);
```
Then it works OK, and the div is added to the DOM.

### Wallaby.js configuration file
var angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');
module.exports = function () {
    return {
        "files": [
             { pattern: 'src/languages/en-US/*.json', instrument: false },
             { pattern: "test/polyfills/*.js", instrument: false },
             { pattern: "typings/proto/all-protos.d.ts", instrument: false }, // wallaby hack: Make sure protos are loaded so enums are defined properly
             { pattern: "src/vendor/jquery.min.js", instrument: false }, // make sure jQuery is loaded before angular
             { pattern: "src/vendor/ByteBufferAB.min.js", instrument: false }, // wallaby hack: Make sure byte array are loaded before protobuf.js
             { pattern: "src/vendor/angular.min.js", instrument: false }, // Make sure angular is loaded before angular-translate
             { pattern: "src/vendor/angular-translate.min.js", instrument: false }, // Make sure angular-translate is loaded before angular-translate-loader-partial
             { pattern: "src/vendor/*.min.js", instrument: false },
             { pattern: "src/vendor/ui-bootstrap-tpls.js", instrument: false },
             { pattern: "src/vendor/angular-ui-tab-scroll.js", instrument: false },
             { pattern: 'src/vendor/angular-busy.js', instrument: false },
             { pattern: "src/vendor/*.min.js", instrument: false },
             { pattern: 'src/vendor/bmc-dpl/src/components/busy-preloader/busy-preloader.js', instrument: false },
             { pattern: 'src/vendor/bmc-dpl/src/components/timepicker/timepicker.js', instrument: false },
             { pattern: 'src/vendor/bmc-dpl/src/components/datepicker-new/datepicker.js', instrument: false },
             { pattern: 'src/vendor/bmc-dpl/src/components/datetimepicker/datetimepicker.js', instrument: false },
             { pattern: 'src/vendor/bmc-dpl/src/components/counter/counter.js', instrument: false },
             { pattern: 'src/vendor/jsbn.js', instrument: false },
             { pattern: 'src/vendor/rsa.js', instrument: false },
             { pattern: 'src/vendor/jquery-ui-1.11.0.js', instrument: false },
             { pattern: 'src/vendor/date.js', instrument: false },
             { pattern: "src/build/all-protos.js", instrument: false },
             { pattern: "src/build/all-sls-templates.js", instrument: false },
             { pattern: "src/vendor/go.js", instrument: false },
             { pattern: 'src/vendor/ag-grid.js', instrument: false },
             { pattern: 'src/vendor/Chart.js', instrument: false },
             { pattern: 'src/vendor/angular-chart.js', instrument: false },
             { pattern: 'src/vendor/diff_match_patch.js', instrument: false },
             { pattern: 'src/vendor/FileSaver.js', instrument: false },
             { pattern: "node_modules/angular-mocks/angular-mocks.js", instrument: false },
             { pattern: 'node_modules/jasmine-jquery/lib/jasmine-jquery.js', instrument: false },
            "src/modules/*/*.ts",
            "!" + "src/modules/*.tests/*.ts",
            "!" + "src/modules/*.tests2/*.ts",
            "src/modules/*/*/*.ts",
            "!" + "src/modules/*.tests/*/*.ts",
            "!" + "src/modules/*.tests2/*/*.ts",
            "src/modules/*/*/*/*.ts",
            "!" + "src/modules/*.tests/*/*/*.ts",
            "!" + "src/modules/*.tests2/*/*/*.ts",
            "src/modules/**/*.ts",
            "!" + "src/modules/*.tests/**/*.ts",
            "!" + "src/modules/*.tests2/**/*.ts",
            "src/modules/**/*.html",
            "src/images/*"
        ],

        "tests": [
            "src/modules/*.tests/**/*.ts",
            "src/modules/*.tests2/**/*.ts"
        ],
        debug: true,
        "preprocessors": {
            "src/modules/**/*.html": function (file) {
                return angularTemplatePreprocessor.transform(file, {
                    stripPrefix: 'src/',
                    moduleName: 'st-templates'
                })
            }
        }
    }
};

### Code editor or IDE name and version

WebStorm v2016.2.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
> it works well in Karma

Can I see you karma config please?

**Comment by splintor** [comment]
module.exports = function (config) {
    'use strict';
    var antBuildOutputLocation = '../../../ECSNT/SelfService/Server/SelfServiceWeb/logs/WebClient';
    config.set({
        basePath: '../',
        reporters: ['progress', 'coverage'],
        preprocessors: {
            'src/modules/!(plugIns*)/**/*.js': ['coverage'],
            //'src/modules/**/*.js': ['coverage'],
            'src/modules/**/*.html': ['ng-html2js']
        },
        files: [
            {pattern: 'src/languages/en-US/*.json',  watched: false, included: false, served: true, nocache: false},
            {pattern: 'src/modules/*.tests/**/*.js', included: false},
            'test/polyfills/*.js',
            'src/vendor/jquery.min.js', // make sure jQuery is loaded before angular
            "src/vendor/angular.min.js", // Make sure angular is loaded before angular-translate
            "src/vendor/angular-translate.min.js", // Make sure angular-translate is loaded before angular-translate-loader-partial
            'src/vendor/*.min.js',
            'src/vendor/ui-bootstrap-tpls.js',
            'src/vendor/angular-ui-tab-scroll.js',
            'src/vendor/angular-busy.js',
            'src/vendor/bmc-dpl/src/components/busy-preloader/busy-preloader.js',
            'src/vendor/bmc-dpl/src/components/timepicker/timepicker.js',
            'src/vendor/bmc-dpl/src/components/datepicker-new/datepicker.js',
            'src/vendor/bmc-dpl/src/components/datetimepicker/datetimepicker.js',
            'src/vendor/bmc-dpl/src/components/counter/counter.js',
            'src/vendor/jsbn.js',
            'src/vendor/rsa.js',
            'src/vendor/jquery-ui-1.11.0.js',
            'src/vendor/date.js',
            {pattern: 'src/**/*.js.map', included: false},
            {pattern: 'src/*.ico', included: false},
            'node_modules/angular-mocks/angular-mocks.js',
            'node_modules/jasmine-jquery/lib/jasmine-jquery.js',
            'src/build/all-protos.js',
            'src/build/all-sls-templates.js',
            'src/vendor/go.js',
            'src/vendor/ag-grid.js',
            'src/vendor/Chart.js',
            'src/vendor/angular-chart.js',
            'src/vendor/diff_match_patch.js',
            'src/vendor/FileSaver.js',
            'src/modules/*/*.js',
            'src/modules/*/*/*.js',
            'src/modules/*/*/*/*.js',
            'src/modules/**/*.js',
            'src/modules/**/*.html',
            {pattern: "src/modules/**/*.ts", watched: false, included: false, served: true}
        ],
        coverageReporter: {
            reporters: [{type: 'html', subdir: 'report-html'},{type: 'json', subdir: 'report-json'}],
            dir: antBuildOutputLocation + '\\coverage\\unit2\\'
        },
        ngHtml2JsPreprocessor: {
            stripPrefix: 'src/',
            moduleName: 'st-templates'
        },
        trxReporter: {
            outputFile: antBuildOutputLocation + '/karma-test-results.trx',
            suite: ''
        },
        junitReporter: {
            outputFile: antBuildOutputLocation + '/karma-test-results.xml',
            suite: ''
        },
        specReporter: {
            prefixes: { // special V and X characters doesn't look good in ant output
                success: 'V ',
                failure: 'X ',
                skipped: '- '
            }
        },
        autoWatch: true,
        proxies: {
            '/favicon.ico': '/base/src/SelfServiceIcon.ico',
            '/images/': '/base/src/images/'
        },
        frameworks: ['jasmine'],
        //browsers: ['PhantomJS'],
        browsers: ['Chrome_without_sandbox'],
        // browsers: ['Chrome'],
        //browsers: ['Chrome', 'Firefox'],
        //browsers: ['PhantomJS2'],//, 'PhantomJS2_custom'],

        // you can define custom flags
        customLaunchers: {
            // 'PhantomJS2_custom': {
            //     base: 'PhantomJS2',
            //     options: {
            //         windowName: 'my-window',
            //         settings: {
            //             webSecurityEnabled: false
            //         },
            //     },
            //     flags: ['--load-images=true'],
            //     debug: true
            // }
            Chrome_without_sandbox: {
                base: 'Chrome',
                flags: ['--no-sandbox'] // with sandbox it fails under Docker
            }
        },

        phantomjsLauncher: {
            // Have phantomjs exit if a ResourceError is encountered (useful if karma exits without killing phantom)
            exitOnResourceError: true
        },
        plugins: [
            'karma-jasmine',
            'karma-chrome-launcher',
            'karma-firefox-launcher',
            'karma-phantomjs-launcher',
            'karma-phantomjs2-launcher',
            'karma-coverage',
            'karma-spec-reporter',
            'karma-trx-reporter',
            'karma-junit-reporter',
            'karma-ng-html2js-preprocessor'
        ],
        // logLevel: config.LOG_DEBUG,
        // These settings are meant to fix intermittent disconnect problems that occur on TFS
        // See https://github.com/karma-runner/karma/issues/598
        captureTimeout: 61000,
        browserDisconnectTimeout: 11000, // default 2000
        browserDisconnectTolerance: 1, // default 0
        browserNoActivityTimeout: 62000 //default 10000
    });
};

**Comment by ArtemGovorov** [comment]
Wallaby.js is using PhantomJs by default, and it looks like you're using Chrome to run your tests in Karma, I suspect that if you run your tests in Karma with PhantomJs, you'll get the same error. 

From [what I can find](http://stackoverflow.com/questions/15739263/phantomjs-click-an-element), PhantomJs doesn't support `click()` (and it's not even a standard yet). You may add a polyfill for PhantomJs like described in the SO answers I referenced, or [use wallaby supported Electron/V8 as a runner](https://wallabyjs.com/docs/integration/electron.html) that should be identical as running your tests in Chrome (except that wallaby will do it without opening any windows). Wallaby also [supports PhantomJs 2](https://wallabyjs.com/docs/integration/phantomjs2.html), where the `click()` support may be added, but I'm not sure, you may try it.

**Comment by splintor** [comment]
Thanks for the clear explanation. We ended up using dispatchEvent instead of click().
