### ISSUE TITLE
Wallaby.js Core v1.0.267 hangs with Angular1 / Karma / Webpack

### ISSUE THREAD

**Issue by andrewconnell** [wallabyjs/public#708]
I think this is a config issue, but I can't seem to crack it. No matter what I change in my config, even with `debug=true` in the Wallaby config, all I see in the console is

```
[Info] started Wallaby.js Core v1.0.267
```

First time I'm trying to get Wallaby working on this project so not sure if the version matters in this case. This Angular project is a library of directives (no views), written in TypeScript and current tests pass without Wallaby using Gulp to load Karma that uses webpack. I'm a little confused how all this is supposed to work in Wallaby since Webpack does the processing of TypeScript => JavaScript and then runs & reports on the tests... not sure how to get the tests showing in VSCode.

I've uploaded the entire project here in a fork:
https://github.com/andrewconnell/ng-officeuifabric/tree/wallabyjs

To run tests WITHOUT Wallaby, after cloning, do:

```
npm i
npm run dev-install
npm test
```

That will run a gulp task **test** ([see this for details](https://github.com/andrewconnell/ng-officeuifabric/blob/wallabyjs/build/gulp/tasks/test.ts#L54-L104)) that uses Karma (which uses webpack) to test the library.

Stuck trying to get this working since the only thing I can get Wallaby to show in the console is that it's started, then it just hangs. Tried playing with the `workers` in the config with no affect...

Ideas?

> BTW, if you hide `*.js` files in VSCode, you need to unhide them in your settings, then compile everything to TypeScript (`npm run build:ts`) and then configure Wallaby to use the config file in `build/config/wallaby.config.js`.

### Wallaby.js configuration file

https://github.com/andrewconnell/ng-officeuifabric/blob/wallabyjs/build/config/wallaby.config.ts

### Code editor or IDE name and version

Visual Studio Code v1.3.1

### OS name and version

OSX v10.11.5

**Comment by ArtemGovorov** [comment]
I have [sent the PR](https://github.com/andrewconnell/ng-officeuifabric/pull/2) and added some notes, including relevant docs links there. 

The reason it was not working at all, is that it couldn't access any source/tests folders, because of where the wallaby config file was located. I'll see if I can do some better error reporting in this case.

Other than this change, I have modified the config to use webpack with wallaby like [described in the docs](https://wallabyjs.com/docs/integration/webpack.html).

**Comment by andrewconnell** [comment]
Dang... works like a champ. Thanks @ArtemGovorov ! Will blog this up this week...

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! Please share the link to the blog post, would love to check it out.
