### ISSUE TITLE
Importing css/scss modules

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#709]
I am having hard time with loading css modules in my app (error: cannot find module './styles.css'.)

I read [this](https://github.com/wallabyjs/public/issues/628) issue and I tried adding css/scss to my `files`, with no luck. 

My build setup is a bit different: (we use node with server side rendering. But this is another issue, I'm focusing on client side only now - react + es6).

#### Build (high level)
- First step: gulp + babel is transpiling/coping everything (es6, scss) to `dist` folder, keeping project's structure. 
- Second step: Webpack is bundling the transpiled files, from `dist` folder

My tests are running from dist folder as well.. (I have a specs bundle).

My js file are loading css in the following format:

`import styles from './styles.css';`

This is because the file is already transpiled from .scss to .css (inside `dist`). 

So, when using Wallabyjs, trying to load `./styles.css` will always fail, because there is no such file (there is `./styles.scss` instead.

I'm loading my webpack's configuration file. Maybe I should create new configurations with an 'scss' loader? 

### Wallaby.js configuration file
```js
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('my-node-build/config/webpack.config');
module.exports = function (wallaby) {

  webpackConfig.module.loaders.push({
    test: /\.json$/,
    loader: 'json'
  });

  webpackConfig.externals = webpackConfig.externals || {};
  webpackConfig.externals.jsdom = 'window';
  webpackConfig.externals.cheerio = 'window';
  webpackConfig.externals['react/lib/ExecutionEnvironment'] = true;
  webpackConfig.externals['react/lib/ReactContext'] = 'window';

  const webpackPostprocessor = wallabyWebpack(webpackConfig);

  return {
    files: [

      { pattern: 'node_modules/fetch-mock/es5/client-browserified.js', instrument: false },

      { pattern: 'src/client/**/*.spec.[t|j]s*', load: false, ignore: true },

      { pattern: 'src/client/**/*.scss', load: false, instrument: false },

      { pattern: 'src/client/**/*.[t|j]s*', load: false }
    ],

    tests: [
      { pattern: 'src/client/**/*.spec.[t|j]s*', load: false }//,
//      { pattern: 'test/**/*.spec.[t|j]s*', load: false }
    ],

    compilers: {
      'src/client/**/*.[t|j]s*': wallaby.compilers.babel({ babel: require('my-node-build/node_modules/babel-core') })
    },

    testFramework: 'mocha',

    postprocessor: webpackPostprocessor,
    /*global window*/
    bootstrap(wallaby) {
      window.__moduleBundler.loadTests();
      wallaby.testFramework.configure({
        // you may remove the `scriptPreprocessor` as it's not used anyway
        moduleNameMapper: {
          'src/client/**/*.css': require('path').join(wallaby.localProjectDir, 'index.js')
        },
      });
    },
    debug: true
  };
};

```
### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The referenced issue and this fragment:
```javascript
wallaby.testFramework.configure({
        // you may remove the `scriptPreprocessor` as it's not used anyway
        moduleNameMapper: {
          ...
        },
      });
```
are for `jest` testing framework, so doesn't apply in your case.

Wallaby.js config is basically a build config for your testing environment. So you need to do something similar to what you're doing in your build process and compile your `.scss` files to `.css`. Wallaby supports [`preprocessors`](https://wallabyjs.com/docs/config/preprocessors.html), so may use this simple preprocessor:

```javascript
...
module.exports = function (wallaby) {
  ...
  return {
    ...
    preprocessors: {
      '**/*.scss': file => require('node-sass').renderSync(
                                      {data: file.changeExt('css').content || ' '}
                                    ).css.toString()
    },
  };
};
```

+

```
npm i node-sass --save-dev
```
(but you may already have it installed for you build process anyway)

It is renaming the file from `scss` to `css` by calling `file.changeExt('css')` (that just returns the file so you can chain the `.content` call) and using `sass` compiler to compile `scss` to `css`.

If you have any special options you need to pass to the sass compiler, you may just pass them into the [`renderSync` function](https://github.com/sass/node-sass#usage) used in the preprocessor.

Let me know if it addresses the issue.

**Comment by yanivefraim** [comment]
I managed to make it work, thanks. I built example (based on [wallaby + webpack + react + es6](https://github.com/wallabyjs/wallaby-webpack-es6-react), using css imports. I think that this is starting to be a common scenario...

Is it ok to add it to github? I think it can be nice if you add it to your examples

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Sure, please share the the link to your repo and I'll add it the wallaby recipes docs page.

**Comment by yanivefraim** [comment]
ok, so this is the repo. I kept it simple (we also have css modules etc. , but I don't think it is related to the example)

https://github.com/yanivefraim/wallaby-webpack-es6-react-css-imports

**Comment by ArtemGovorov** [comment]
Awesome, thanks! Have added the sample to the docs.

**Comment by yanivefraim** [comment]
Cool! I have another example using react + redux + enzyme, which are pretty popular and needs some special settings. I can post it here as well, if you think it is needed...

**Comment by ArtemGovorov** [comment]
Sure, it'd be great to reference it as well from our docs!
