### ISSUE TITLE
Others ways to config instrumented files

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#71]
My `files` array usually should load a lot of files:
* Libraries (bower_components), one pattern per library
* Mock files (json and html)
* Javascript files with some config and mock setup
* Script files to be tested, usually done with a one-liner

Only the script files should be instrumented. Since `instrumented` is true by default, most of my lines have the form `{ pattern: '.....', instrument: false },` which feels like config overhead.

This is no issue when `instrumented` is `false` by default or when it is possible to define instrumented and not instrumented files in another way, for example by defining a list with instrumented files, non-instrumented files and tests.

Karma already has something like this, namely the list with `excluded` files (called `ignore` in WallabyJS).

**Comment by ArtemGovorov** [comment]
Sounds good, I'll add a way to override defaults for file object properties.

For now you could do something like this:
``` javascript
var n = file => {pattern: file, instrument: false}; // any defaults that work for you
var i = file => {pattern: file, ignore: true};

module.exports = function () {
  return {
    files: [
      n('bower_components/jquery/jquery.js'),
      n('helpers/helper.js')
      i('ignoredFile.js')
      'src/*.js'
    ],

    tests: [
      'test/*Spec.js'
    ]
  };
};
```

**Comment by ArtemGovorov** [comment]
Have added another way to [override the defaults](https://github.com/wallabyjs/public#file-object) with `wallaby.defaults.files` and `wallaby.defaults.tests`, see the `load` property description section.
