### ISSUE TITLE
Show last run screenshot not showing in VS 2015

### ISSUE THREAD

**Issue by saralamuralikrishna** [wallabyjs/public#710]
### Issue description or question

Show last run screenshot not showing in VS 2015

### Wallaby.js configuration file

```javascript
// paste your config here
```
{
  "files": [
    {
      "pattern": "Scripts/angular.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jstests/localStorageServiceFake.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-ui-router.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-mocks.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jquery-2.1.4.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jquery-ui-1.11.4.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/lodash.compat.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/ng*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-toaster/*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-loading-bar/loading-bar.js",
      "instrument": false
    },
    {
      "pattern": "AppScripts/Models/Availability.js",
      "instrument": true
    },
    {
      "pattern": "TestScripts/fakeApiService.js",
      "instrument": true
    },
    {
      "pattern": "Scripts/jstests/lib/chai.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/jstests/lib/sinon*.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-datepicker/angular-moment.min.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/angular-datepicker/angular-datepicker.min.js",
      "instrument": false
    },
    {
      "pattern": "Scripts/bliss/*.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/infos/infos-module.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Search/*-module.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*-module.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*-module.js",
      "instrument": true
    },
    {
      "pattern": "my-bertus-angular-app.config.js",
      "instrument": true
    },
    {
      "pattern": "my-bertus-angular-app.run.js",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/my-bertus-angular-app.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/ordered-model.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/order-result-summary-item-model.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/*-model*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Models/*-list*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/Core/*.ts",
      "instrument": true
    },
    {
      "pattern": "TestScripts/fakeResourceService.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/myBertusAngularApp/*.ts",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*service*.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*service.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/myBertusAngularApp/LocalStorage.js",
      "instrument": true
    },
    {
      "pattern": "AppScripts/**/*.ts",
      "instrument": true
    },
    {
      "pattern": "Scripts/App/**/*.js",
      "instrument": true
    }
    
  ],
  "tests": [
    "Scripts/jstests/infoslist.test.js"   
  ],
  "testFramework": "mocha"
}

### Code editor or IDE name and version

Visual Studio 2015
Visual Studio 2013

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
I just checked the latest version in your environment and it worked for me.

Does it show an empty border when you invoke the action?
Note that you need to [run a particular test first](https://wallabyjs.com/docs/intro/get-started-vs.html#smart-actions) with the "Run line tests" action to see the screenshot for it.

Does the action work on a sample [from this repository](https://github.com/wallabyjs/public/tree/master/sample/visualstudio)? For example, try running mocha config, then [open this test](https://github.com/wallabyjs/public/blob/master/sample/visualstudio/test/calculatorMochaSpec.js#L63), then invoke "Run line tests" smart action on that line, the invoke "Show last screenshot" action.

**Comment by saralamuralikrishna** [comment]
I have installed latest version and it shows empty border. 
I tried running the tests first and it shows empty border. 
I tried running the repository but got below error
​​​​​TypeError: 'undefined' is not a function (evaluating 'this[t](e[t])')
TypeError: 'undefined' is not a function (evaluating 'this[t](e[t])')
at http://localhost:62881/__wallaby__/mocha@2.0.1/framework.js:15

**Comment by ArtemGovorov** [comment]
Ok, empty border means that the screenshot is empty. Perhaps your test is not creating any visual stuff, or deleting it before wallaby makes a screenshot. 

Try replacing your test file content with this:
```javascript
  it('screenshot test', function() {
    document.body.style.width = '100%';
    document.body.style.height = '100%';
    document.body.style.backgroundColor = 'red';
  });
```
run the test and then run the "Show last run screenshot" action. Does it display a red screenshot?

**Comment by ArtemGovorov** [comment]
I'll close the issue since there wasn't any activity on it for a while. Please let me know if it's still valid for you and try the suggestion above.
