### ISSUE TITLE
Wallaby.js App: Parses ES6 string interpolation incorrectly

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#718]
Wallaby.js App parses `ES6` string interpolation Incorrectly:

![screen shot 2016-08-01 at 6 09 05 pm](https://cloud.githubusercontent.com/assets/279122/17298563/1b028690-5813-11e6-88e7-5ca0f0a71930.png)

**Comment by ArtemGovorov** [comment]
Could you please share the code to reproduce it? Is this from an OSS project? Simple cases seem to work ok, so must be something in the file.

**Comment by mdreizin** [comment]
@ArtemGovorov Please see https://github.com/mdreizin/webpack-cluster

**Comment by ArtemGovorov** [comment]
@mdreizin Submitted the issue to the editor control repo: https://github.com/Microsoft/monaco-editor/issues/89

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks a lot ;)

**Comment by NikGovorov** [comment]
The issue is fixed in the recent versions of Wallaby.js App.
