### ISSUE TITLE
Can't get any tests to load, `Running Tests` spinner constantly spinning

### ISSUE THREAD

**Issue by mwq27** [wallabyjs/public#723]
### Issue description or question

I always get `No failing tests, 0 passing` message in the Failing Tests tab.  It seems like no tests are loading up.  There are also no color squares in the gutter on any file.  I'm not sure what I'm doing wrong here.
### Wallaby.js configuration file

``` javascript
var wallabyAngularFilesort = require('wallaby-angular-filesort');
var wallabyPostprocessor = wallabyAngularFilesort.create({
    whitelist: ['src/tools/**/*.js']
});

module.exports = function () {
    return {
        files: [
            { pattern: 'bower_components/angular/angular.js', instrument: false },
            { pattern: 'bower_components/angular-mocks/angular-mocks.js', instrument: false },
            { pattern: 'bower_components/lodash/lodash.js', instrument: false },
            { pattern: 'bower_components/highcharts/highcharts.js', instrument: false },
            { pattern: 'node_modules/mocha/mocha.js', instrument: false },
            { pattern: 'node_modules/chai/chai.js', instrument: false },
            { pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false },
            { pattern: 'src/tools/**/*.js', load: true },
            { pattern: 'src/tools/**/*.spec.js', ignore: true }

        ],

        tests: [
            { pattern: 'src/**/*.spec.js', load: true }
        ],

        env: {
            kind: 'electron'
        },
        debug: true,

        testFramework: 'mocha',
        postprocessor: wallabyPostprocessor
    };
};
```
### Code editor or IDE name and version

WebStorm v2016.2
### OS name and version

OSX 10.10.5  Yosemite

**Comment by ArtemGovorov** [comment]
Are you still also having these errors: https://github.com/wallabyjs/public/issues/231#issuecomment-236976168 or they're gone?

Please remove this line from your config
```javascript
{ pattern: 'node_modules/mocha/mocha.js', instrument: false }
```
Wallaby uses its own version of the testing framework, so duplicating it in the `files` list may be breaking things.

Other than that line, your config looks ok and a similar one works for me, so if it still doesn't work for you after removing the line, could you please create a sample project with your config demonstrating the issue?

**Comment by mwq27** [comment]
After removing mocha.js things started working :)  I do have a reference to chai.js in there, and I'm now getting `expect is not defined` errors in my tests.  Is there something that I am missing?

**Comment by ArtemGovorov** [comment]
@mwq27 You're probably missing [setting `window.expect` in your `setup` function](https://wallabyjs.com/docs/config/bootstrap.html):
```javascript
...
setup: function() {
      window.expect = chai.expect;
},
...
```

**Comment by ArtemGovorov** [comment]
Closing the issue for now, please let me know if it's still valid and you can share a sample project so I may have a look.
