### ISSUE TITLE
source-map-support error in wallaby.js console (on startup)

### ISSUE THREAD

**Issue by nathanvale** [wallabyjs/public#726]
My Wallaby.js configuration was working fine until I moved to webpack 2 beta ( i believe)

I am no getting this error on startup 

Please feel free to have a look at my repository.

Cheers.

https://github.com/nathanvale/reactjs-hackathon-kit

[Info] Wallaby.js stopped
[Error] /home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:411
[Error]       var hasStack = (arguments[1] && arguments[1].stack);
[Error]                                                   ^
[Error] SyntaxError: Unexpected token ! in JSON at position 0
[Error]     at Object.parse (native)
[Error]     at new SourceMapConsumer (/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:50:24)
[Error]     at mapSourcePosition (/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:164:14)
[Error]     at wrapCallSite (/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:327:20)
[Error]     at /home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:362:26
[Error]     at Array.map (native)
[Error]     at Function.prepareStackTrace (/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:361:24)
[Error]     at SyntaxError.get stack (native)
[Error]     at process.emit (/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:411:51)
[Error]     at process._fatalException (bootstrap_node.js:254:26)

```javascript
'use strict';
var wallabyWebpack = require('wallaby-webpack');


var config = require('./bin/webpack/webpack.config.test').default;

config.module.loaders = config.module.loaders.filter(
    function (l) {
        return l.loader !== 'awesome-typescript-loader?tsconfig=tsconfig-test.json'
    }
)

// tests + specHelper will be webpack-ed entry points
config.entryPatterns = ['src/**/*.spec.js*', 'src/polyfill.js', 'src/spec-helper.js'];

config.resolve = {

    extensions: ['', '.js', '.json', '.css'],
    alias: {
        sinon: 'sinon/pkg/sinon.js'
    }
}


var webpackPostprocessor = wallabyWebpack(config)




module.exports = function (wallaby) {


    return {
        debug: true,
        files: [
            { pattern: 'src/spec-helper.ts', load: false },
            { pattern: 'src/polyfill.ts', instrument: false },
            { pattern: 'src/**/*.ts*', load: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.jpg', load: false },
            { pattern: 'src/**/*.spec.ts*', ignore: true },
        ],
        tests: [
            { pattern: 'src/**/*.spec.ts*', load: false },
        ],


        compilers: {

            '**/*.ts': w.compilers.typeScript({ target: 'es5' })
        },

        postprocessor: webpackPostprocessor,

        testFramework: "mocha",

        bootstrap: function () {

            window.__moduleBundler.loadTests();

        }
    };
};
```

Visual Studio Code v1.3.0
Linux

**Comment by ArtemGovorov** [comment]
Perhaps I'm missing some code that has not yet been pushed to the repo, but the [wallaby config](https://github.com/nathanvale/reactjs-hackathon-kit/blob/master/wallaby.js) doesn't even let me start wallaby:

```
[Error] ReferenceError: w is not defined
[Error]     at module.exports (/reactjs-hackathon-kit/wallaby.js:50:24)
```

Another thing I noticed is that this code in the config
```javascript
config.module.loaders = config.module.loaders.filter(
    function (l) {
        return l.loader !== 'awesome-typescript-loader?tsconfig=tsconfig-test.json'
    }
)
```
doesn't do anything, because the TypeScript loader is defined as `loader: 'awesome-typescript-loader?target=es5',` in the `./bin/webpack/webpack.config.test`.

If I fix these error and run tests, I get a lot of error about missing `rxjs` modules. The `src/polyfill.ts` file imports them, but there's no `rxjs` module installed or specified in the dependencies in the `package.json` file.

**Comment by nathanvale** [comment]
I have committed and pushed  again and fixed the missing problems.

make sure you are running node 6.3.0

npm run test works
and so does

npm run dev

I am defiantly able to start wallaby and but getting  

[Info] Wallaby.js stopped
[Error] /Users/nathanvale/Documents/Git Repositories/reactjs-hackathon-kit/node_modules/source-map-support/source-map-support.js:411
[Error]       var hasStack = (arguments[1] && arguments[1].stack);

**Comment by ArtemGovorov** [comment]
This is strange, wallaby doesn't seem to even start. 
Could you please try this config and paste the console output?

```javascript
'use strict';

console.log('config loaded');
var wallabyWebpack = require('wallaby-webpack');
console.log('wallabyWebpack loaded');

var config = require('./bin/webpack/webpack.config.test').default;
console.log('webpack.config.test loaded');

config.module.loaders = config.module.loaders.filter(
    function (l) {
        return l.loader !== 'awesome-typescript-loader?tsconfig=tsconfig-test.json'
    }
)

// tests + specHelper will be webpack-ed entry points
config.entryPatterns = ['src/**/*.spec.js*', 'src/polyfill.js', 'src/spec-helper.js'];

config.resolve = {

    extensions: ['', '.js', '.json', '.css'],
    alias: {
        sinon: 'sinon/pkg/sinon.js'
    }
}


var webpackPostprocessor = wallabyWebpack(config)

console.log('webpackPostprocessor loaded');


module.exports = function (wallaby) {

    console.log('loading settings');
    return {
        debug: true,
        files: [
            { pattern: 'src/spec-helper.ts', load: false },
            { pattern: 'src/polyfill.ts', instrument: false },
            { pattern: 'src/**/*.ts*', load: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.jpg', load: false },
            { pattern: 'src/**/*.spec.ts*', ignore: true },
        ],
        tests: [
            { pattern: 'src/**/*.spec.ts*', load: false },
        ],


        compilers: {

            '**/*.ts': w.compilers.typeScript({ target: 'es5' })
        },

        postprocessor: webpackPostprocessor,

        testFramework: "mocha",

        bootstrap: function () {

            window.__moduleBundler.loadTests();

        }
    };
};
```

**Comment by nathanvale** [comment]
Here is my console output

[Info] config loaded
[Info] wallabyWebpack loaded
[Error]
/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:411
[Error]       var hasStack = (arguments[1] && arguments[1].stack);
[Error]                                                   ^
[Error] SyntaxError: Unexpected token ! in JSON at position 0
[Error]     at Object.parse (native)
[Error]     at new SourceMapConsumer
(/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:50:24)
[Error]     at mapSourcePosition
(/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:164:14)
[Error]     at wrapCallSite
(/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:327:20)
[Error]     at
/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:362:26
[Error]     at Array.map (native)
[Error]     at Function.prepareStackTrace
(/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:361:24)
[Error]     at SyntaxError.get stack (native)
[Error]     at process.emit
(/home/nathanvale/Documents/repos/ts-starter-kit/node_modules/source-map-support/source-map-support.js:411:51)
[Error]     at process._fatalException (bootstrap_node.js:254:26)

**Comment by ArtemGovorov** [comment]
It seems like some issue in your `./bin/webpack/webpack.config.test`, the error is raised from it.

Does running this from CLI
```
node ./bin/webpack/webpack.config.test.js
```
in your project folder work?

Considering that `npm run test` works on your machine, and the only thing it seem to be doing differently in terms of loading the `./bin/webpack/webpack.config.test.js` file is setting `NODE_ENV=test`, you may try the same in wallaby config just before loading the file:
```javascript
'use strict';

var wallabyWebpack = require('wallaby-webpack');

process.env.NODE_ENV = 'test'; // <----

var config = require('./bin/webpack/webpack.config.test').default;

...
```

**Comment by nathanvale** [comment]
Running

node ./bin/webpack/webpack.config.test.js

From the cli works.

also adding 

process.env.NODE_ENV = 'test'; // <----

Made no difference.

I have done a huge clean up of my npm packages, removed them an installed them again and pushed to github.

Still wallaby console is reporting the above source-map-support error. I believe it is coming from awesome-typescript loader as that needs it but wallaby doesn't use it. hmm lost a little bit

**Comment by nathanvale** [comment]
Yes I can confirm

if I comment out  line 1 in
node_modules/awesome-typescript-loader/dist/entry.js
wallaby proceeds to compile.

Not sure why it works with npm run test and not inside wallaby at this stage.

`//require('source-map-support').install();
module.exports = require('./index');
//# sourceMappingURL=entry.js.map`

**Comment by ArtemGovorov** [comment]
I'm really puzzled and not yet sure why it happens (and can't reproduce it on OSX or Ubuntu). Now considering that wallaby.js doesn't need the loader, you may do this in the config (to avoid changing anything else just for the sake of getting wallaby working):

```javascript
'use strict';

var wallabyWebpack = require('wallaby-webpack');

var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
  if (filePath === 'source-map-support') {
    return {install: () => {}};
  }
  return originalRequire.call(this, filePath);
};

var config = require('./bin/webpack/webpack.config.test').default;

modulePrototype.require = originalRequire;
...
```
This will basically make node return an object with noop when `source-map-support` is requested as a part of `./bin/webpack/webpack.config.test` loading from wallaby. Let me know if the workaround is working for you (can't check because it's working for me without the workaround).

**Comment by nathanvale** [comment]
Great the workaround at least gets Wallaby up and running. I am happy to go with the work around. I'm using ubuntu here but will look at osx later. It's very odd - i'm not sure why wallaby is hitting awesome-typescript-loader - when i am using your compiiler in the config. happy to close this issue and move on. i have a new issue now to report.

Thanks!
