### ISSUE TITLE
Plugins added to webpack.config.resolve throw a type error from wallaby/server.js

### ISSUE THREAD

**Issue by nathanvale** [wallabyjs/public#729]
I need to add a plugin to my webpack config resolve property so webpack can resolve files to typescripts baseUrl setting in tsconfig.json.

`config.resolve = {

    extensions: ['', '.js', '.json', '.css'],
    alias: {
        sinon: 'sinon/pkg/sinon.js'
    },

    plugins: [
        new TsConfigPathsPlugin()
    ]
}`

Pushed to:
https://github.com/nathanvale/reactjs-hackathon-kit

However Wallaby is throwing a TypeError when this setting exists:

[Error] TypeError: Cannot read property 'length' of undefined
[Error]   at Object.complete (/home/nathanvale/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:17:17207)
[Error]   at Timeout.<anonymous> (/home/nathanvale/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:17:16608)
[Error]   at tryOnTimeout (timers.js:224:11)
[Error]   at Timer.listOnTimeout (timers.js:198:5)

`'use strict';
var wallabyWebpack = require('wallaby-webpack');

var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
  if (filePath === 'source-map-support') {
    return {install: () => {}};
  }
  return originalRequire.call(this, filePath);
};

var config = require('./bin/webpack/webpack.config.test').default;

modulePrototype.require = originalRequire;

var config = require('./bin/webpack/webpack.config.test').default;
var TsConfigPathsPlugin = require('awesome-typescript-loader').TsConfigPathsPlugin;

process.env.NODE_ENV = 'test';

config.module.loaders = config.module.loaders.filter(
    function (l) {
        return l.loader !== 'awesome-typescript-loader?useBabel=true'
    }
)

// tests + specHelper will be webpack-ed entry points
config.entryPatterns = ['src/**/*.spec.js*', 'src/polyfill.js', 'src/spec-helper.js'];

config.resolve = {

    extensions: ['', '.js', '.json', '.css'],
    alias: {
        sinon: 'sinon/pkg/sinon.js'
    },

    plugins: [
        new TsConfigPathsPlugin()
    ]
}

var webpackPostprocessor = wallabyWebpack(config)

module.exports = function (wallaby) {

    return {
        debug: true,
        files: [
            { pattern: 'src/spec-helper.ts', load: false },
            { pattern: 'src/polyfill.ts', instrument: false },
            { pattern: 'src/**/*.ts*', load: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.jpg', load: false },
            { pattern: 'src/**/*.spec.ts*', ignore: true },
        ],
        tests: [
            { pattern: 'src/**/*.spec.ts*', load: false },
        ],

        compilers: {
            'src/**/*.ts?(x)': wallaby.compilers.typeScript({
                target: 'es5'
            })
        },

        postprocessor: webpackPostprocessor,

        testFramework: "mocha",

        bootstrap: function () {

            window.__moduleBundler.loadTests();

        }
    };
};`

Visual Studio Code v1.3

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
> [Error] TypeError: Cannot read property 'length' of undefined
> [Error] at Object.complete (/home/nathanvale/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.20/wallaby/server.js:17:17207)

There must be some errors reported above it, are there any?

**Comment by ArtemGovorov** [comment]
I have been getting some parse errors when trying to run the tests in your repo with wallaby. Opening one of the reported files in a browser revealed that it's a TS file, not compiled JS. Apparently the `TsConfigPathsPlugin` uses an absolute path and pointing back to the local project (as opposed to be using a relative path and hitting wallaby cache). While there's probably a way to make it work, an easier way is just not to use (because wallaby is not using the `awesome-typescript-loader` anyway) and just use the webpack standard way to make it resolve files as modules relatively to your `src` folder: https://github.com/nathanvale/reactjs-hackathon-kit/pull/1
