### ISSUE TITLE
ava test.skip not skipping assertions

### ISSUE THREAD

**Issue by kennethlynne** [wallabyjs/public#730]
### Issue description or question
![wat](http://g.recordit.co/3og0ADt51P.gif)

### Code editor or IDE name and version
WebStorm v11

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report, the bug is fixed in core 1.0.273. As you know, wallaby will be updated automatically, or you may just restart the IDE and start wallaby to force the update.
