### ISSUE TITLE
Results not updating for related tests, and error showing up on wrong assertions

### ISSUE THREAD

**Issue by kennethlynne** [wallabyjs/public#731]
### Issue description or question

Using Ava
![wat](http://g.recordit.co/QQICXjg0D7.gif)

**Comment by ArtemGovorov** [comment]
Could you please create a sample I could run? 
It may be your tests state issue, try setting [`workers: {recycle: true}`](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) in the config: if the issue goes away then it's definitely the state, if it doesn't go away then can still be state, but either way I'll need a sample to run to find out.

**Comment by ArtemGovorov** [comment]
Closing the issue for now, please let me know if it's still valid and you can share a sample project so I may have a look.
