### ISSUE TITLE
How to use wallaby with seajs?

### ISSUE THREAD

**Issue by scq000** [wallabyjs/public#733]
### Issue description or question
I wan't to use wallabyjs to test seajs modules, but it cant' work? How to do with it?

### Wallaby.js configuration file

wallaby.js
```javascript
module.exports = function () {
  return {
    files: [
      {pattern: 'bower_components/seajs/dist/sea.js', instrument: false},
      {pattern: 'lib/*.js', instrument: false, load: false},


      {pattern: 'src/**/*.js', load: false},
    ],

    tests: [
      {pattern: 'test/**/*Spec.js', load: false}
    ]
  };
};
```

test-main.js

```

(function(wallaby, seajs) {
  var tests = [],
      file;
  var alias = {
    "jquery": "../lib/jquery",
  };

  wallaby.delayStart();

  seajs.config({
    alias: alias
  });

  seajs.use(wallaby.tests, function() {

    wallaby.start();

  });
})(window.wallaby, seajs);

```

### Code editor or IDE name and version

WebStorm v11

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
I haven't heard of seajs before, so not sure if wallaby works with it or not (it also looks like the most of the seajs docs are in Chinese and I don't know the language). If it works with karma, it should work with wallaby. 

From what I see in your config, you have not included the `test-main.js` file to the files list, I think it should be there with the `load: true` flag set.

**Comment by scq000** [comment]
Ok, thank you for your help!
