### ISSUE TITLE
Jest Documentation: Requiring 'package.json' instructions are not clear

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#734]
![image](https://cloud.githubusercontent.com/assets/5240018/17464076/0886b4e2-5ca4-11e6-99d9-e1dda78de187.png)

I played around with this for longer than I care to admit, trying to physically `require` the package.json, only to find out that if you leave the `configure()` function call without arguments, it does just that. 

Can this perhaps be better clarified in the docs to prevent others from making the mistake I made?

**Comment by ArtemGovorov** [comment]
Do you mean that when you call `configure()` with no arguments, it just uses the `jest` section from your `package.json`? I actually had no idea it works this way, and what's more puzzling it doesn't work for me this way. When I call `configure()` with no arguments it's just using jest with its default config.

What kind of issues did you have `require`-ing the `package.json`? I have adjusted the docs to make it more clear what to do:
```javascript
     testFramework: 'jest'

     setup: function (wallaby) {
       // require the file and pass its jest prop
       wallaby.testFramework.configure(require('./package.json').jest);
     }
```

**Comment by dsifford** [comment]
Yeah, sorry, I forgot to write back. 

It does not work that way! I think wallaby was able to scoop leftover `haste_cache` or something for that particular instance for it to work.

I ended up just copy-pasting the jest config from my `package.json` because I just couldn't figure out how to get it to work otherwise.

> What kind of issues did you have require-ing the package.json? 

The directory that it looked in was the `.atom` directory, and not the root of the project. This is likely just an issue with atom users.

**Comment by ArtemGovorov** [comment]
I'm trying on [this sample project](https://github.com/wallabyjs/wallaby-jest-sample), adding `package.json` to the `files` list, adding a simple `jest` section to the `package.json`, having this in the `setup` function:

```javascript
setup: function (wallaby) {
       wallaby.testFramework.configure(require('./package.json').jest);
}
```
and it's working for me (the settings are used) in Atom on OSX, Windows and Ubuntu.

> The directory that it looked in was the .atom directory, and not the root of the project

Can't reproduce this on any system in Atom. Wallaby sets its test worker process working directory to be the project directory so I'm not even sure how it could end up looking for something in the `.atom` directory.

Could you please share a sample where I could reproduce these issues? I'm keen to investigate what's going on.

**Comment by dsifford** [comment]
I'm not totally sure. This is more than likely user-error.

When I did it I attempted to include the whole package.json. Let me try your way real fast and see if that works. I'll chime back in a few.

**Comment by dsifford** [comment]
@ArtemGovorov Yep, that did the trick. Sorry for the ignorance!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
It probably was the error in docs that I fixed: before the fix it was saying `require('package.json')` (it wasn't correct, because node will try to find `package.json` node module, so supposed to be `require('./package.json')`), and it wasn't mentioning specifically that `.jest` property of the required object needs to be used. So hopefully much clearer now, sorry about the time you have to spent on this and thanks for reporting it!

**Comment by dsifford** [comment]
No worries. Thanks for the stellar support, as usual. 😃
