### ISSUE TITLE
Import with an absolute path from root directory

### ISSUE THREAD

**Issue by danimbrogno** [wallabyjs/public#735]
### Issue description or question

Hi, I have a meteor project I'm trying to integrate with Wallaby using https://github.com/xolvio/automated-testing-best-practices as a starting point. My issue is that my project references imports from my project root: i.e.

`import Hello from '/imports/test.js';`

Is there a way I can configure wallaby / webpack so it knows where to look for modules loaded from an absolute path (i.e. those with a leading slash)?

I've got a sample project here that shows the issue: https://github.com/danimbrogno/automated-testing-best-practices

See error in /imports/ui/components/inctest.js.

### Wallaby.js configuration file

```javascript
var _ = require('underscore');
var path = require('path');
var fs = require('fs');
var wallabyWebpack = require('wallaby-webpack');
var babel = require('babel-core');

module.exports = function (wallaby) {

  var webpackConfig = {
    resolve: {
      root: path.join(wallaby.projectCacheDir, 'src', 'imports'),
      extensions: ['', '.js', '.jsx', '.json']
    },
    module: {
      loaders: [
        // JavaScript is handled by the Wallaby Babel compiler
        { test: /\.json$/, loader: 'json-loader' }
      ]
    }
  };

  var wallabyPostprocessor = wallabyWebpack(webpackConfig);


  var babelCompiler = wallaby.compilers.babel();

  var packageStubs = fs.readdirSync('./src/imports/testing/client/stubs/packages')
    .map(function (fileName) {
      return 'packages/' + fileName;
    });

  var appManifest = require(path.resolve('./src/.meteor/local/build/programs/web.browser/program.json')).manifest;
  var meteorPackageFiles = appManifest
    .filter(function (file) {
      return file.type === 'js' && file.path.startsWith('packages/') &&
        [

        ].indexOf(file.path) === -1;
    })
    .map(function (file) {
      var basePath = packageStubs.indexOf(file.path) !== -1 ?
        'src/imports/testing/client/stubs' :
        'src/.meteor/local/build/programs/web.browser';
      return {pattern: path.join(basePath, file.path)};
    });

  return {
    // set `load: false` to all source files and tests processed by webpack
    // (except external files),
    // as they should not be loaded in browser,
    // their wrapped versions will be loaded instead
    files: [
      'src/.meteor/local/build/programs/web.browser/merged-stylesheets.css',
      'src/imports/testing/client/__meteor_runtime_config__.js',
    ].concat(
       meteorPackageFiles,
       [
         {pattern: 'src/imports/testing/_support/**', load: false},
         {pattern: 'src/imports/**/*.@(js|jsx)', load: false},
         {pattern: 'src/imports/**/*-spec.@(js|jsx)', ignore: true},
         {pattern: 'src/imports/**/server/**/*.@(js|jsx)', ignore: true},
       ]
    ),
    tests: [
      {pattern: 'src/imports/**/*-spec.@(js|jsx)', load: false},
      {pattern: 'src/imports/**/server/**/*-spec.@(js|jsx)', ignore: true},
    ],

    compilers: {
      // Important: Make sure that src/.meteor/ is excluded from the pattern
      'src/imports/**/*.@(js|jsx)': babelCompiler,
      'tests/**/*.@(js|jsx)': babelCompiler,
    },

    postprocessor: wallabyPostprocessor,

    bootstrap: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();

			process.env.NODE_PATH = path.join(wallaby.projectCacheDir,'src');

		  require('module').Module._initPaths()
    },

    env: {
      type: 'browser',
      runner: require('phantomjs').path,
    },

    testFramework: 'jasmine',

    debug: true,
  };
};

```

### Code editor or IDE name and version
Atom v1.x

### OS name and version
OSX El Capitan

**Comment by ArtemGovorov** [comment]
These lines in the `bootstrap` function will not help because they are for node environment:
```javascript
process.env.NODE_PATH = path.join(wallaby.projectCacheDir,'src');
require('module').Module._initPaths()
```

Setting the [`resolve.root`](https://webpack.github.io/docs/configuration.html#resolve-root) in webpack config like you are doing: 
```javascript
var webpackConfig = {
    resolve: {
      root: path.join(wallaby.projectCacheDir, 'src', 'imports'),
      ...
```
should help in cases when you do
```
import Hello from 'test'
```
This will resolve `test.js` file in `src/imports`. In your example however you are doing two things that I'm not sure are errors or not:
- you are trying to resolve from `imports/test.js'`, but the webpack root is already set to imports so it'll search for `src/imports/imports/test.js`. Perhaps you meant to just `import Hello from 'test'`? If you do need to use multiple different roots for your imports, perhaps you may consider using [webpack module directories setting](https://webpack.github.io/docs/configuration.html#resolve-modulesdirectories)?
- you are resolving with the leading `/`. I have never seen anyone using it like this as an absolute *nix path (which is actually not an existing absolute path) and not sure if webpack can actually be configure to handle cases like this. Is it a Meteor specific thing?

**Comment by danimbrogno** [comment]
To your first point, thanks this was a typo, I've removed 'imports' from the root so it reads `root: path.join(wallaby.projectCacheDir, 'src'),`. Unfortunately this doesn't solve the issue. 

Yes it is a bit odd, and yes it is a meteor specific thing. Meteor's build system creates a kind of "virtual" root inside your application folder which it considers the root during it's build process. I think Meteor has it's own build system that doesn't make use of WebPack. The reason I'm using wallaby / webpack is that it makes for much faster testing then what comes bundled with Meteor.

One solution would be to go through all my source code and switch from absolute to relative paths, but I'd rather not go down that route atm. I am hoping WebPack can be configured to recognize imports from root, and map then to a certain folder.

I'll follow up with the webpack folks on this one.

**Comment by ArtemGovorov** [comment]
Ok, thanks for the update. If it's not possible doing with webpack, you may also try using [wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) and use some RegExp to remove the leading `/` from each file content before the files are webpack-ed. Note that the preprocessor will be getting an already compiled JS as an input, so the replacement should be operating with `require`, not `import`, ie `require('/...')` -> `require('...')`.

**Comment by danimbrogno** [comment]
Thanks Artem! I was able to get it working using the babel plugin `babel-project-relative-import`.
