### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by rpmonteiro** [wallabyjs/public#738]
### Issue description or question
Hi @ArtemGovorov , when trying to run a command (`pg_restore` - which assumes postgres is installed) using node's `child_process.exec()`, wallaby throws an error saying `command not found`. Is wallaby running that command in a different environment than my terminal shell?

Here's the command I'm running:
![image](https://cloud.githubusercontent.com/assets/7824615/17557535/7572ea2c-5f0f-11e6-85cf-88c8f13e7b16.png)

on a `beforeEach hook` so I can reset the database after each test
![image](https://cloud.githubusercontent.com/assets/7824615/17557559/8c3810e8-5f0f-11e6-900a-68205d89089e.png)

Mocha runs just fine.

Here's the error it throws:
![image](https://cloud.githubusercontent.com/assets/7824615/17557630/d86ec34e-5f0f-11e6-9280-bca43a6ab296.png)

How to make wallaby run that without any issues? Thank you!

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  process.env['NODE_ENV'] = 'test';
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'node_modules/**/*.js', ignore: true},
      {pattern: 'server/**/*-test.js', ignore: true},
      {pattern: 'public/**/*.js', ignore: true},
      {pattern: 'server/tests/db/*.*', instrument: false},
      'server/**/*.js',
      'public/*.*'
    ],
    tests: [
      'server/**/*-test.js'
    ],
    testFramework: 'mocha',
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: false
    },
    
    setup: function () {
      require('babel-polyfill');
    }
  };
};

```

### Code editor or IDE name and version
Atom v1.9.7

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Wallaby for Atom is using Atom process environment variables. If you open Atom Dev Tools and try to run the command there (may just run the command to get help displayed or something):

![screen shot 2016-08-11 at 10 07 16 am](https://cloud.githubusercontent.com/assets/979966/17575310/941070e8-5fab-11e6-8fea-68b89a9c0952.png)


does it work?

**Comment by ArtemGovorov** [comment]
Also try to paste `process.env.PATH` and see the result in your Atom Dev Tools console. Check if the path where the tool is installed in the that `PATH`. If it's not, you may try adding something like:
```
process.env.PATH += require('path').delimiter + 'the/tool/path'
```
to your [Atom init file](http://flight-manual.atom.io/hacking-atom/sections/the-init-file/).

**Comment by rpmonteiro** [comment]
Hi Artem, that did fix it, thank you.

Because it was a postgres command, I added the following to the Atom init file as you suggested:
```
process.env.PATH += require('path').delimiter + '/Applications/Postgres.app/Contents/Versions/9.5/bin:$PATH'
```

Now I have another problem... I'm running that pg_restore command to restore a dump file, which is not in the instrumented folder, thus not being found when running the command!
![image](https://cloud.githubusercontent.com/assets/7824615/17583313/3e3997e2-5fa8-11e6-82a2-98627a7e9363.png)

Here's my wallaby folder tree:
![image](https://cloud.githubusercontent.com/assets/7824615/17583277/fe2dba66-5fa7-11e6-981d-7c16e391d10c.png)

The command being ran:
![image](https://cloud.githubusercontent.com/assets/7824615/17583345/6f43515c-5fa8-11e6-8526-7ce3fc7ca735.png)

So it's looking for the file on the instrumented folder, but I have no way of getting that dump file in there. My wallaby config is on the first post where I'm requiring the file. I've tried setting a `load` flag to `true`, but no success.

Any ideas? 
Thanks again Artem

**Comment by ArtemGovorov** [comment]
It's supposed to get copied to the `instrumented` folder, if the file is there when wallaby starts. Just tried adding a simple binary to a simple sample project, like `{pattern: 'src/t.zip', instrument: false},` and I see the file being copied successfully. Is the file there (in your local project) when you start wallaby? Perhaps it happens because there's no file extension (try adding some)?

**Comment by rpmonteiro** [comment]
Ah, that must be it. The dump file has no extension at all.
Any way of getting a file there that has no extension?

**Comment by rpmonteiro** [comment]
Got it!
Replaced 
`{pattern: 'server/tests/db/*.*', instrument: false}`
with 
`{pattern: 'server/tests/db/*', instrument: false}`

Thanks again Artem!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
