### ISSUE TITLE
Postgres command failed in Wallaby

### ISSUE THREAD

**Issue by rpmonteiro** [wallabyjs/public#741]
### Postgres command failed in Wallaby
Atom runs the command just fine while wallaby makes it fail.

I'm trying to reset a database by using postgres's `pg_restore` command to reset the db to the dump state. 

Running that command from the Atom console - runs just fine: 
![image](https://cloud.githubusercontent.com/assets/7824615/17586650/ea048dd6-5fba-11e6-8c16-0fb3d72633b0.png)

The command is being triggered only once, at a beforeEach hook:
![image](https://cloud.githubusercontent.com/assets/7824615/17586797/bcfcaebc-5fbb-11e6-9363-13939057a799.png)

Now when wallaby tries and run the same command: 
![image](https://cloud.githubusercontent.com/assets/7824615/17586676/1cdaeae8-5fbb-11e6-8a09-57ae39a8b862.png)

It's not a directory problem, as it was fixed by https://github.com/wallabyjs/public/issues/738. The dump file is instrumented and it's in wallaby's project dir.

I suspect the problem is that because wallaby runs that on every keypress, it might be overloading the postgres db (by running it hundreds of times per minute), which in turn returns that error.

I know it's a pretty obscure error,  but might be very helpful for other people trying to get wallaby running fine with DB tests.

Do you have any ideas, @ArtemGovorov ?

Thank you again for your patience!

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'node_modules/**/*.js', ignore: true},
      {pattern: 'server/**/*-test.js', ignore: true},
      {pattern: 'public/**/*.js', ignore: true},
      {pattern: 'server/tests/db/*', instrument: false},
      'server/**/*.js',
      'public/*.*'
    ],
    tests: [
      'server/**/*-test.js'
    ],
    testFramework: 'mocha',
    env: {
      type: 'node',
      params: {
        env: 'NODE_ENV=test'
      },
      runner: 'node'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: false
    },
    setup: function () {
      require('babel-polyfill');
    }
  };
};

```

### Code editor or IDE name and version
Atom v1.9

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
I have a suspicion that it's not correctly copied (because of the absence of the file extension). It is copied, by I think it's corrupted. Try adding a file extension `.bin` to it.

**Comment by rpmonteiro** [comment]
So I tried adding .bin to it but it corrupts the file, so that didn't work.
I've added .backup/.sql/.dump and while running it in the terminal works fine with any of those extensions, it still outputs the same error in wallaby's focus panel.

**Comment by rpmonteiro** [comment]
I've also compared the original files and the ones in wallaby's intrumented folder and they look exactly the same.

**Comment by ArtemGovorov** [comment]
I just have added `.dump` extensions to the list of extensions that wallaby recognises as binary, try [forcing the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to v1.0.277 and trying `.dump` again.

> I suspect the problem is that because wallaby runs that on every keypress

Does it sometimes work?
Could you paste the full error message (without any sensitive data) from the the wallaby panel?

**Comment by ArtemGovorov** [comment]
I've never used the tool, is there any way to get some more diagnostics why the command failed? 

In your Atom example you are specifying the directory right in the command text, while in your test you're setting `cwd`, did you try running the command in the same way as in Atom (just in case)? 

Also try hardcoding the absolute path to the dump in your local project folder in the test to see if it works or not.

**Comment by rpmonteiro** [comment]
Thanks for the suggestions, Artem. 
I did try all that with no different results.

Here's what I figured out though:
![image](https://cloud.githubusercontent.com/assets/7824615/17589274/af89e924-5fcb-11e6-9248-f8f90e244610.png)

It really seems it's related to how wallaby copies the file.

The original file runs no problem, but not the copied one...

Does this ring a bell for you?

Again, thanks for your patience

**Comment by rpmonteiro** [comment]
Update:

Got it working with an ugly solution (not really a solution because other people won't be able to run it), but should help you by providing some more insights.

Running from the wallaby dir:
![image](https://cloud.githubusercontent.com/assets/7824615/17590057/08070a9c-5fd0-11e6-8628-45e94eeb00af.png)

Running from the original dir:
![image](https://cloud.githubusercontent.com/assets/7824615/17590111/46088226-5fd0-11e6-8b2f-2c5139a78447.png)

**Comment by ArtemGovorov** [comment]
Can't reproduce it locally, but it looks like the dump file is corrupted when copied to the wallaby cache folder. Now given that the original file works ok, let's do it his way. Remove the `{pattern: 'server/tests/db/*', instrument: false},` pattern from your `files` and add this to your `setup` function:

```javascript
    setup: function (wallaby) {
      require('babel-polyfill');

      var path = require('path');
      var cp = require('child_process');
      var exec = cp.exec;
      cp.exec = function () {
        var commandCwd = arguments[1].cwd;
        arguments[1].cwd = commandCwd.replace(
          path.resolve(wallaby.projectCacheDir),
          path.resolve(wallaby.localProjectDir));
        return exec.apply(this, arguments);
      }
    }
```

This way we'll be just intercepting the `exec` calls and changing the command options `cwd` to your local project folder instead of the wallaby cache. So you don't need to change your code/tests to do it.

Let me know if this works for you.

**Comment by rpmonteiro** [comment]
Simply genius! 

Works perfectly.

I brag to my friends all the time about how ridiculously good wallaby's support (you) is. Many have converted already!

Keep up the great work, Artem.

See you on the next issue! (Hopefully not ;-) )
Cheers
