### ISSUE TITLE
CSS import causing Wallaby to crash

### ISSUE THREAD

**Issue by MechJosh0** [wallabyjs/public#744]
### Issue description or question
In a file I'm testing I have `import './style.css';` which is breaking wallaby.js. Mocha tests are passing fine when I add a [css-null function to the compiler](https://github.com/MechJosh0/storybook-mdl-error/commit/c5b7684709e331d21af8aabd9de6b36cbabdbfa9). However I'm still having problems getting wallaby.js to run correctly. I have tried using the [Webpack](https://wallabyjs.com/docs/integration/webpack.html) NormalModuleReplacementPlugin and Null loader solutions but I get the following error: `TypeError: Cannot read property 'cache' of undefined`. I am using Meteor as my true build tool if this makes a difference.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  var load = require;

  return {
    files: [
      'client/modules/**/components/*.js',
      'client/modules/**/actions/*.js',
      'client/modules/**/containers/*.js',
      'client/modules/**/libs/*.js',
      'public/lib/getmdl/material.min.js',
      // 'public/lib/getmdl/material.min.css' //(adding it here causes ILLEGAL error, not adding it causes module not found)
    ],
    tests: [
      'client/**/tests/*.js'
    ],
    compilers: {
       '**/*.js*': wallaby.compilers.babel({
         babel: load('babel-core'),
         presets: ['es2015', 'stage-2', 'react']
       })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      global.React = require('react');
    }
  };
};
```

### Example repo
https://github.com/MechJosh0/storybook-mdl-error

### Code editor or IDE name and version
WebStorm v2016.2.1

### OS name and version
Linux

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. I have sent you [the PR with working wallaby config](https://github.com/MechJosh0/storybook-mdl-error/pull/1).

Basically you just need to do the same thing as you do in mocha - require those helpers you're using (`css-null-compiler.js` and `.scripts/mocha_boot.js`) before tests. In wallaby you just use [the `setup` function for it](https://wallabyjs.com/docs/integration/node.html#mocha---require-equivalent), which you already had in your config for setting the global `React` variable.

Let me know if this works for you.

**Comment by MechJosh0** [comment]
Brilliant, that's done it! Thanks @ArtemGovorov
