### ISSUE TITLE
Wallaby App suggestions

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#747]
- Jump to the failing test when running a test. Perhaps make this feature toggleable because auto-jump could be a bit annoying when there are a lot of tests failing and when you are multi-tasking
- Expand/Collapse all buttons for the tests tree
- Add Meta title that makes more sense than the root folder name and make it configurable from the wallaby config
- Mark test files in the files list with a separate color or font style
- Since all instrumented files are used to calculate the coverage percentage I want more control which files are instrumented an which files are not. You could a `instrumentedFiles` key to the config. If this key is used, it will override all the `instrumented: true` flags in the `files` list. Separate from the coverage calculation, this setting simplifies debugging because I can instrument a library with a oneliner without having to split op several patterns in my `files` list into 'instrumented' and 'not instrumented'.
It also looks like it is impossible to not instrument test helpers that are required from a test file.

If you want me to make separate issues per bullet point, please let me know.

**Comment by ArtemGovorov** [comment]
Thanks for the feedback. I like all of the suggestions. A couple of things are already working (or partially working):

> Expand/Collapse all buttons for the tests tree

Buttons would definitely be helpful, for now there's a way to expand from the keyboard: using `right arrow key + Cmd/Ctrl` to fully expand a selected node, or `right arrow key + Cmd/Ctrl + Shift` to fully expand the whole tree.

> Add Meta title that makes more sense than the root folder name and make it configurable from the wallaby config

This is supported - you can use `name` in the root config object:
```javascript
module.exports = function (wallaby) {
  return {
    name: 'Project Title'
    ...
  };
};
```
There's not tutorial on the wallaby app yet because it's still in beta, but this will be in the docs.

**Comment by ArtemGovorov** [comment]
Most of the suggestions are implemented now:
- Wallaby App now jumps to the latest executed and/or failing test.
- Expand/Collapse actions are available (described above), buttons will be added a bit later as well.
- Project name can be changed: https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#faq.
- Tests and files now have differently coloured icons.
- File patterns participating in the code coverage calculation can now be changed: https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#faq.
