### ISSUE TITLE
Invalid component element. This may be caused by unintentionally loading two independent copies of React.

### ISSUE THREAD

**Issue by arjunu** [wallabyjs/public#749]
### Issue description or question
**ReactDOM.render(): Invalid component element. This may be caused by unintentionally loading two independent copies of React.**

If I comment React in externals it throws **_registerComponent(...): Target container is not a DOM element.** for 
```
render(
    <Provider store={store}>
        <Router routes={rootRoute} history={history}/>
    </Provider>,
    document.getElementById('root')
);
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

module.exports = function (wallaby) {

    var webpackPostprocessor = wallabyWebpack({
        // webpack options
        externals: {
            // Use external version of React instead of rebuilding it
            'react': 'React',
            'cheerio': 'window',
            'react/addons': true,
            'react/lib/ExecutionEnvironment': true,
            'react/lib/ReactContext': true
        },
        module: {
            loaders: [
                {
                    test: /\.css$/,
                    loader: 'style!css-loader?modules!postcss-loader'
                },
                {
                    test: /\.(ttf|ico|eot|otf|svg|png|gif|woff|jpeg(2)?)(\?[a-z0-9]+)?$/,
                    loader: 'file-loader'
                }]
        },
        resolve: {
            extensions: ['', '.js']
        }
    });

    return {
        files: [
            {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
            {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
            {pattern: 'src/**/*.css', load: false},
            {pattern: 'src/**/*.ico', load: false},
            {pattern: 'src/**/*.eot', load: false},
            {pattern: 'src/**/*.woff', load: false},
            {pattern: 'src/**/*.ttf', load: false},
            {pattern: 'src/**/*.svg', load: false},
            {pattern: 'src/**/*.otf', load: false},
            {pattern: 'src/**/*.png', load: false},
            {pattern: 'src/**/*.js', load: false},
            {pattern: 'src/**/*.test.js', ignore: true},
            {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false}
        ],

        tests: [
            {pattern: 'tests/**/**.tests.js', load: false}
        ],
        testFramework: 'mocha',
        compilers: {
            '**/*js': wallaby.compilers.babel()
        },
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};

```

### Code editor or IDE name and version

WebStorm 2016.2.2
Build #WS-162.1628.41, built on August 16, 2016
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX El Capitan 10.11.16

### Wallaby Version
1.0.72

**Comment by ArtemGovorov** [comment]
Can't reproduce it locally, must be something your project/setup specific. Could you please create and share a github repo demonstrating the issue?

**Comment by ArtemGovorov** [comment]
(was trying to reproduce on this repo: https://github.com/wallabyjs/wallaby-webpack-es6-react)

**Comment by arjunu** [comment]
Okay I create and share a repo.

**Comment by arjunu** [comment]
Here's the repo https://github.com/arjunu/wallaby-react-test

If I import into my test file anything from a file that has import React statement, I get the error

**Comment by arjunu** [comment]
Sorry I closed by mistake!

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

The very first error I got in your repo was because there's not `root` element in your document:

![app](https://cloud.githubusercontent.com/assets/979966/17809841/9851d32e-665c-11e6-9db7-e36ef41510f8.gif)

If I change [the `bootstrap` function](https://wallabyjs.com/docs/config/bootstrap.html) to create one, the error is fixed:

```javascript
        bootstrap: function () {
            var root = document.createElement('div');
            root.id = 'root';
            document.body.appendChild(root);

            window.__moduleBundler.loadTests();
        }
```

I'm not an expert in React, so not sure if it's ok for you to create one in the `bootstrap` or you need to create one in your `beforeEach` hooks, whatever works for you.

The next error I got after fixing the previous  one was this:
![app1](https://cloud.githubusercontent.com/assets/979966/17809886/fabf705c-665c-11e6-8fac-620a72c5c52b.gif)
Again, I'm not an expert in React, but it's fixed if you do what the error says and return a function.

**Comment by arjunu** [comment]
There was a typo in` index.js`

`const Hello = (<p>Hello</p>);` was supposed to be `const Hello = ()=> (<p>Hello</p>);`

Anyways,
I removed React from externals, got rid of "unintentionally loading two independent copies of React.". 

Included the three lines in bootstrap function, got rid of "_registerComponent(...): Target container is not a DOM element."

Thanks!
