### ISSUE TITLE
Uncovered regions are not updated automatically

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#75]
When I reveil the uncovered regions, and I add a test to cover these regions, the coverage markers in the left margin are updated but the uncovered regions are not.
They are updated when I manually do "show uncovered regions" again.

From usability perspective the uncovered regions should be updated automatically too.

![uncovered_regions](https://cloud.githubusercontent.com/assets/963136/7268807/6a39709a-e8cd-11e4-9365-78dbfd6ddfc5.png)

**Comment by ArtemGovorov** [comment]
Agreed, nice find.
