### ISSUE TITLE
Parse Error. Pushing or Returning Short Hand Object Creation

### ISSUE THREAD

**Issue by btull89** [wallabyjs/public#755]
This returns a parse error:
```javascript
define(function() {
    var noMatch= {
        key: "NoMatch",
        message: function () {
            return "No match was found.";
        }
    }

    return {
        //noMatch //this fails due to parse error
        noMatch : noMatch // this passes
    }
});
```
```javascript
self.WarningMessages.push({ key: key, message: message }); //passes
self.WarningMessages.push({ key, message}); //fails due to Parse Error
```
### Wallaby.js configuration file
```javascript
module.exports = function () {
    return {
        files: [
          { pattern: "gi_/lib/*.js", instrument: false },
          { pattern: "gi_/Crm_EntityRibbonScript/*_commands.js" },
          {pattern: "gi_/**/*.js", load: false },
          {pattern: "Test/SpecRunner.js", instrument: false}
        ],

        tests: [
          {pattern: "Test/**/*spec.js", load: false}
        ]
    };
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Shorthand property names is a part of ES6 spec and by default wallaby runs your browser tests in PhantomJs which only supports ES5, so throws the Parse Error.

There're a couple of available options depending on how your app is supposed to work in production. 

If you're only targeting browsers/devices with ES6 support, then you may configure [Electron runner for your tests](https://wallabyjs.com/docs/integration/electron.html) in which case it'll be like running your tests in the latest Chrome.

If you're targeting browsers that don't support ES6 as well, then you probably have `babel` or similar in place in your build process, that transpiles your ES6 code to ES5. In this case you may [just configure `babel`](https://wallabyjs.com/docs/integration/es-next.html) in wallaby and use any ES6 or even ES7 features.

Let me know if this helps.

**Comment by btull89** [comment]
That was very helpful Artem. Thank you for taking the time to help!
