### ISSUE TITLE
Show difference of deep equal object in output window

### ISSUE THREAD

**Issue by josh-egan-ps** [wallabyjs/public#758]
### Issue description or question

I would like to be able to see the diff right in the "Failing Tests" output window. Right now, I see this:

![image](https://cloud.githubusercontent.com/assets/12396134/17940430/538c323c-69ec-11e6-8fb4-d01c34ec1445.png)

Clicking on the "Show difference" link opens a new window that shows a nice display of the difference, but it takes too long and requires pointing and clicking! I would rather see the diff printed right there in the output window. Is there a way I could turn this on via a setting? If not, could that be added?
### Code editor or IDE name and version

WebStorm 2016.2.2
Build #WS-162.1628.41, built on August 16, 2016
### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
There are a couple of constraints here: the short message (before the `Show difference` link) is provided by a testing framework, so there's not much we can do to expand it (but different frameworks provide different quality messages, some are better). The difference display is a separate window is powered by WebStorm built-in diff view, and it's not possible to display it right in the console.

Having said that, there's a very fast way to display the message without pointing and clicking, you may use the `Show assertion data diff` context action:

![s](https://cloud.githubusercontent.com/assets/979966/17951822/aa24122e-6aa8-11e6-9a97-70d1c4ea7dc3.gif)

It can be as fast as just a single keyboard shortcut, if you assign one for the action in your Settings:

<img width="789" alt="screen shot 2016-08-25 at 9 51 34 am" src="https://cloud.githubusercontent.com/assets/979966/17951979/963c5252-6aa9-11e6-8d32-98228cac595e.png">

**Comment by IPWright** [comment]
Is that sort of thing supported in Sublime? I'm trying to compare DOM actual/expected at the moment and it'd be great if there were some nice way of seeing a visual diff via the web app side of things - possibly letting me suggest custom formatters/pretty printers.

**Comment by ArtemGovorov** [comment]
> Is that sort of thing supported in Sublime?

Unfortunately there're a few limitations in what plugins can do in Sublime, so we're unable to do the same there.

>  it'd be great if there were some nice way of seeing a visual diff via the web app side of things

This is supported. There's the `Show diff` icon displayed in the Wallaby App next to the errors where `actual` and `expected` can be visually compared:

![app](https://cloud.githubusercontent.com/assets/979966/20546949/69ddac2c-b164-11e6-9e72-4810722df51b.gif)
