### ISSUE TITLE
Hubot (coffescript) and wallaby

### ISSUE THREAD

**Issue by sondremare** [wallabyjs/public#759]
### Issue description or question
I am using hubot (open source bot code) and struggling with tests in wallaby.
I am using the mocha framework, and running tests manually like this:
"test": "mocha \"src/**/*.spec.js\" --compilers coffee:coffee-script --require ./tests/setup.js"

The reason I need to add the coffee-script compiler is because the package "hubot-test-helpers" requires "hubot". And hubot does not distribute .js-files... 

I read up on some issues here, and found the preprocessor solution. But it does not work for me.
I still get **Cannot find module 'hubot'**.
Any ideas on how to solve this issue?

PS! Using coffeescript compiler v1.6.3

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/hubot/**/*.coffee', instrument: false},
      'src/*.js',
      'scripts/*.js',
      '!src/*.spec.js',
      'tests/setup.js'
    ],
    tests: [
      'src/*.spec.js',
    ],
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    preprocessors: {
       'node_modules/hubot/**/*.coffee': file => require('coffee-script').compile(file.rename(file.path + '.js').content)
     },
    bootstrap: function bootstrap() {
       require('./tests/setup');
     },
  };
};
```

### Code editor or IDE name and version

WebStorm v2016.2

### OS name and version
OSX 10.11.5

**Comment by ArtemGovorov** [comment]
Thanks for providing the details. In your case it's enough to just do the similar thing as in your mocha command and add CS compiler for `.cs` files in the `bootstrap` function:

```javascript
module.exports = function () {
  return {
    files: [
      'src/*.js',
      'scripts/*.js',
      '!src/*.spec.js',
      'tests/setup.js'
    ],
    tests: [
      'src/*.spec.js',
    ],
    env: {
      type: 'node'
    },
    testFramework: 'mocha',

    bootstrap: function bootstrap() {
      require('./tests/setup');
      require('coffee-script/register'); // <--
    },
  };
};
```

Let me know if this works for you.

**Comment by sondremare** [comment]
Now I get: Error: Cannot find module '../../bin/coffee'
tried with both CoffeScript v1.6.3 and 1.10.0 (latest)

**Comment by ArtemGovorov** [comment]
I have pushed the sample https://github.com/wallabyjs/hubot-sample with your config and CoffeeScript v1.6.3, it works for me:

<img width="669" alt="screen shot 2016-08-25 at 7 10 04 pm" src="https://cloud.githubusercontent.com/assets/979966/17963183/a33422d4-6af7-11e6-826d-f47ed2761748.png">


Please try it and if it works for you, try adding things specific to your project to try and break it.

**Comment by sondremare** [comment]
Will try it immediately. Thanks alot :D

**Comment by sondremare** [comment]
I actually get the exact same error in the sample. I do not have any global versions of coffee-script installed. Using npm version 3.9.3 and node version 6.2.1

**Comment by ArtemGovorov** [comment]
Oh, sorry, I was trying wallaby dev version and it worked for me but the production version did throw the error you've mentioned. The issue is that it's trying to load the `coffee-script` module shipped with wallaby instead of loading the local one. I have updated the sample to load coffee-script from your local folder, should work for you know:

```javascript
    bootstrap: function bootstrap(w) {
      require('./tests/setup');
      require(require('path').join(w.localProjectDir, 'node_modules/coffee-script'));
    }
```

**Comment by ArtemGovorov** [comment]
BTW, your original way should also work, if you fix a couple of things:
- Pattern for the `hubot` module needs to include all files, not just `.coffee`: `'node_modules/hubot/**/*.*'` (otherwise `package.json` and other potentially required files will not be copied to the wallaby cache).
- In your preprocessor `file.rename(file.path + '.js')` just adds `.js` instead of changing the extension., so is making `index.coffee` -> `index.coffee.js`. You need to change it and can use the `changeExt` function.
```javascript
module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/hubot/**/*.*', instrument: false},
      'src/*.js',
      'scripts/*.js',
      '!src/*.spec.js',
      'tests/setup.js'
    ],
    tests: [
      'src/*.spec.js',
    ],
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    preprocessors: {
      'node_modules/hubot/**/*.coffee': file => require('coffee-script').compile(file.changeExt('js').content)
    },
    bootstrap: function bootstrap() {
      require('./tests/setup');
    },
  };
};
```

**Comment by sondremare** [comment]
Works like a charm :D (the first option).
Thanks a lot for amazing help

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
