### ISSUE TITLE
test/files pattern assertion failure

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#76]
Say we have this config:

```javascript
files: [
  { pattern: 'test/spec/home/helperFile.js', instrument: false }
],
tests: [
  { pattern: 'test/spec/home/helperFile.js', ignore: true },
  'test/spec/**/*.js'
]
```

The helperfile does not contain specs, but contains some helper functions for the specs. Therefore it is in the spec directive. I excluded the file from the `tests` and included it in the `files` array.

However, the famous message still appears:

> File/pattern `test/spec/home/helperFile.js` is specified in the files list but also found in the tests > list: `test/spec/**/*.js`.
> If it's a test, make sure to exclude it from the files list, for example by adding `{ pattern: 'test/spec/**/*.js', ignore: true }` to the files list.
> If it's not a test, remove it from the tests list.

I do not want to ignore a full pattern, only a file.
Is the assertion checking based on overlapping patterns or on overlapping files? I think the latter is better.

**Comment by ArtemGovorov** [comment]
It looks like a bug in the check, your config should work. The workaround before the fix is very simple - just ignore the message, everything else should still work.

**Comment by ArtemGovorov** [comment]
Fixed. It should automatically be updated after wallaby restart (within the next 20 minutes) or immediately with WebStorm restart.
