### ISSUE TITLE
Wallaby hanging 

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#760]
### Issue description or question

Hi,

I've got a node project and node has started hanging, this is the first excerpt from the walaby console:

```
[Info] Started Wallaby.js Core v1.0.282
[Error] Error: spawn /Users/zpydee/.nvm/versions/node/v6.3.0/bin/node EMFILE
[Error]   at exports._errnoException (util.js:1008:11)
[Error]   at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
[Error]   at onErrorNT (internal/child_process.js:348:16)
[Error]   at _combinedTickCallback (internal/process/next_tick.js:74:11)
[Error]   at process._tickCallback (internal/process/next_tick.js:98:9)
```

The process eventually runs out of memory after several attempts.

I've recently added the following `before_install` to my `.travis.yml` file to prevent travis from not being able to run a post-install on nested `package.json` files and not sure if this could be causing the `EMFILE`:

```
before_install:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
```

Any guidance would be greatly appreciated. My tests are passing in `mocha`.

thanks,
Dave

### Wallaby.js configuration file

stock standard...

```javascript
module.exports = function (w) {

  return {
    files: [
      { pattern: 'src/**/*.js', load: true },
      { pattern: 'src/**/*.spec.js', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*.spec.js', load: true }
    ],

    env: {
      type: 'node'
    },

  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.4.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I'm not sure if it's wallaby specific issue, have you seen/tried this: https://github.com/sindresorhus/gulp-imagemin/issues/10#issuecomment-38260029?

**Comment by ArtemGovorov** [comment]
Actually [this](http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks) is probably be more helpful as from what I read `ulimit` is only the the current terminal session.

**Comment by zpydee** [comment]
hmmmm, increasing ulimit no helping

**Comment by ArtemGovorov** [comment]
Looks like `ulimit` is only the the current terminal session, did you try the suggestion from [this answer](http://unix.stackexchange.com/questions/108174/how-to-persist-ulimit-settings-in-osx-mavericks)? Also, perhaps try killing all node processes/rebooting to see if it helps.

**Comment by zpydee** [comment]
issue actually seems related to my post-install script somehow:

```
"postinstall" : "find ./src/* -maxdepth 5 -name package.json -execdir npm install \\;",
```

its still running, but if I set it lower than 5, it runs happily but the `wallaby` can't find lib dependencies for child projects..

i'll keep on investigating, but i'm gonna close this issue for now...

**Comment by ArtemGovorov** [comment]
Thanks for the update, perhaps this could help for resolving dependencies for child projects: https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder

**Comment by zpydee** [comment]
thanks, that suggestion was on the money - happy to have my coloured dots back :-)

just for sake of clarity, I added:

```
process.env.NODE_PATH += path.delimiter + path.join(w.localProjectDir, 'src/lib/utils/encryption', 'node_modules');
```

to point to my encryption library. am I correct in assuming I'd repeat for each child project that has its own node_modules?

**Comment by ArtemGovorov** [comment]
> am I correct in assuming I'd repeat for each child project that has its own node_modules?

Correct. This, or, given that wallaby config is essentially a node app, you can write a small function to recursively walk your folder structure and add found `node_modules` folders to the `process.env.NODE_PATH` automatically (may make sense if you have a lot of child projects).

**Comment by zpydee** [comment]
thanks as always for your prompt and very helpful assistance!
