### ISSUE TITLE
Correct link to issue tracker on http://wallabyjs.com

### ISSUE THREAD

**Issue by al-the-x** [wallabyjs/public#761]
### Issue description or question

From http://wallabyjs.com/#plans :

> ### Where is your changelog, and what does the roadmap for wallaby.js look like?
>
> [Our changelog](https://github.com/wallabyjs/public/blob/master/CHANGELOG.md) is in our public repository.
>
> Wallaby.js roadmap:
> 
> * Implementing Test Explorer and Coverage Reports.
> * Implementing better test debugging.
> * Support for more testing frameworks.
> * Simplifying wallaby.js configuration process.
>
> Are we missing something? [Share your idea or vote for other submitted ideas.](https://github.com/wallabyjs/public/issues/issues/new?title=Support%20...&labels=enhancement)

The link to "Share your idea..." has an extra `/issues/new` in it and I'm not sure the query string is as intended. Perhaps:

https://github.com/wallabyjs/public/issues?q=support+in:title&labels=enhancement

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

Vim. Coming soon?

### OS name and version

OSX
Linux (Ubuntu, mostly)

**Comment by ArtemGovorov** [comment]
Thanks for the report! Fixed as you've suggested.
Regarding Vim, no close plans yet, but feel free to subscribe to the feature request: https://github.com/wallabyjs/public/issues/14
