### ISSUE TITLE
Can't get Electron + Typescript project to start

### ISSUE THREAD

**Issue by celador** [wallabyjs/public#762]
### Issue description or question
I can't figure out how to get Wallaby configured properly.  I'm doing extension development for VSCode using Typescript.   The tests run fine using the launch.json file shown below.

### Wallaby.js configuration file
```javascript
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/chai/lib/chai.js', instrumented: false },
            'src/**/*.ts',
        ],
        tests: [
            'test/**/*.test.ts'
        ],
        testFramework: 'mocha',
        env: {
            kind: 'electron'
        },
        setup: function () {
            window.expect = chai.expect;
        },
        debug: false,
    }
}
```

### tsconfig.json configuration file
```javascript
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es5",
        "outDir": "out",
        "noLib": true,
        "sourceMap": true,
        "rootDir": "."
    },
    "exclude": [
        "node_modules",
        "typings/browser",
        "typings/±browser.td.s"
    ]
}
```

### Launch.json
```javascript
    {
      "name": "Launch Tests",
      "type": "extensionHost",
      "request": "launch",
      "runtimeExecutable": "${execPath}",
      "args": [
        "--extensionDevelopmentPath=${workspaceRoot}",
        "--extensionTestsPath=${workspaceRoot}/out/test"
      ],
      "stopOnEntry": false,
      "sourceMaps": true,
      "outDir": "${workspaceRoot}/out/test",
      "preLaunchTask": "npm"
    }
```

### Code editor or IDE name and version
Visual Studio Code v1.4.0

### OS name and version
OSX

### Test file
import * as chai from 'chai';
import * as vscode from 'vscode';
const expect = chai.expect;

describe('Extension Tests', () => {
    let myExtension: vscode.Extension<any>;

    before(() => {
        myExtension = vscode.extensions.getExtension('JohnAaronNelson.ForceCode');
        expect(myExtension).to.not.be.undefined;
    });

    it('activates', () => {
        return myExtension.activate()
            .then(() => {
                expect(true).to.eql(true);
            });
    });
});

### Errors
[Info] Started Wallaby.js Core v1.0.282
[Error] Runtime error: Uncaught ReferenceError: module is not defined
[Error] at http://localhost:60121/node_modules/chai/lib/chai.js?1453982067000&wallabyFileId=1:2
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/compile.js?1472216372512&wallabyFileId=5:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/credentials.js?1472216372555&wallabyFileId=6:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/deploy.js?1472216372606&wallabyFileId=7:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/executeAnonymous.js?1472216372630&wallabyFileId=8:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/exportPackage.js?1472216372641&wallabyFileId=9:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/getLog.js?1472216372653&wallabyFileId=10:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/index.js?1472216372660&wallabyFileId=11:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/lens.js?1472216372670&wallabyFileId=12:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/menu.js?1472216372697&wallabyFileId=13:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/open.js?1472216372713&wallabyFileId=14:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/retrieve.js?1472216372724&wallabyFileId=15:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/commands/staticResource.js?1472216372745&wallabyFileId=16:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/extension.js?1472216372757&wallabyFileId=2:3
[Error] Runtime error: Uncaught TypeError: Object.defineProperty called on non-object
[Error] at http://localhost:60121/src/models/commands.js?1472216372767&wallabyFileId=17:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/parsers/getName.js?1472216372774&wallabyFileId=18:3
[Error] Runtime error: Uncaught TypeError: Object.defineProperty called on non-object
[Error] at http://localhost:60121/src/parsers/getToolingType.js?1472216372779&wallabyFileId=19:33
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/parsers/index.js?1472216372783&wallabyFileId=20:3
[Error] Runtime error: Uncaught TypeError: Cannot set property 'getIcon' of undefined
[Error] at http://localhost:60121/src/parsers/open.js?1472216372787&wallabyFileId=21:30
[Error] Runtime error: Uncaught TypeError: Object.defineProperty called on non-object
[Error] at http://localhost:60121/src/services/constants.js?1472216372792&wallabyFileId=23:33
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/services/forceService.js?1472216372807&wallabyFileId=24:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/services/index.js?1472216372812&wallabyFileId=25:3
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/src/services/logger.js?1472216372822&wallabyFileId=26:3
[Error] Runtime error: Uncaught TypeError: Object.defineProperty called on non-object
[Error] at http://localhost:60121/src/util/sleep.js?1472216372826&wallabyFileId=22:13
[Error] Runtime error: Uncaught ReferenceError: require is not defined
[Error] at http://localhost:60121/test/extension.test.js?1472216372829&wallabyFileId=4:3
[Error] Runtime error: Uncaught TypeError: Cannot read property 'expect' of undefined
[Error] at http://localhost:60121/wallaby_sandbox0.html:10

**Comment by ArtemGovorov** [comment]
Wallaby.js doesn't support VS Code extension testing scenario. Electron is supported as a runner for browser tests (or hybrid tests with node access from the renderer process).
