### ISSUE TITLE
Echo wallaby config file to the console if it's not standard

### ISSUE THREAD

**Issue by brianmhunt** [wallabyjs/public#769]
### Issue description or question

I spent a bunch of time trying to diagnose a problem related to a `module not found`.  It turns out that I had accidentally clicked the button "use as wallaby config" on an arbitrary node script. It gave errors pretty close to what you'd expect to see if tests were running but failing, so it was confusing.

What would have helped a lot is if the config file being used was printed to the Wallaby Console (particularly if the config file is not one of the standard `wallaby.js`, etc.)

Just a thought - might save someone else a bit of a headache. :smile:

Cheers

**Comment by ArtemGovorov** [comment]
Thanks for your feedback, I have added the config path printing to the Wallaby Console, will be released with the next core version.

The used config file name is also always displayed in the title of the Wallaby Panel:
<img width="457" alt="screen shot 2016-09-01 at 9 15 21 pm" src="https://cloud.githubusercontent.com/assets/979966/18165586/5df7b9f0-7089-11e6-97b2-a101a6cfd6b0.png">
