### ISSUE TITLE
Debounce file watches

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#77]
When changing the code, Wallaby immediately runs the test. For example when you are typing `it('shou` an exception is immediately displayed, because you are not finished with typing.

A debounce on the file watches will decrease the restless behaviour of the watches so that I will be more focused on writing code instead of being distracted by red annotations that are displayed too early. I prefer to have a config option available to set the milliseconds.

**Comment by ArtemGovorov** [comment]
There are [2 delay settings](https://github.com/wallabyjs/public#delays-setting) that can control exactly what you'd like.

**Comment by ArtemGovorov** [comment]
P.S. I should really start splitting docs into multiple smaller wiki pages as you have suggested.

**Comment by fvanwijk** [comment]
Oops, sorry for not finding it in the docs (used the wrong search query). Splitting up docs would help ;)
