### ISSUE TITLE
Support for ts files without modules

### ISSUE THREAD

**Issue by cleytonb** [wallabyjs/public#770]
### Issue description or question

Hi,

I'm having trouble with a exported ts class without a module. The ts code is as follows:

```javascript
export class FormMaker {
    test() {
        return true;
    }
}
```

I can see the compiled version is like this:

```javascript
"use strict";
var FormMaker = (function () {
    function FormMaker() {
    }
    FormMaker.prototype.test = function () {
        return true;
    };
    return FormMaker;
}());
exports.FormMaker = FormMaker;
```

When I run wallaby, of course, I receive the error "Cant find variable: exports". But this is a valid ts code compiled to es5 using commonjs. I think Wallaby should support this. When I change the ts file to be like this:

```javascript
module XYZ {
    export class FormMaker {
        test() {
            return true;
        }
    }
}
```

Then it compiles to this:

```javascript
var XYZ;
(function (XYZ) {
    var FormMaker = (function () {
        function FormMaker() {
        }
        FormMaker.prototype.test = function () {
            return true;
        };
        return FormMaker;
    }());
    XYZ.FormMaker = FormMaker;
})(XYZ || (XYZ = {}));
```

Wich in turn allows me to run the tests. However, this limits me too much. I can't export the module because the tests don't run if I do (same problem, can't find variable), If I keep the code in the way it works, I can't import the module in typescript because it says that my file isn't a module, I can't export my class as default...

Since I didn't find any open issues about this, I'm pretty sure that I missed something. Can you help me?

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            'src/**/*.ts'
        ],
        tests: [
            'test/**/*.spec.ts'
        ],
        debug: true
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.4.0

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
> When I run wallaby, of course, I receive the error "Cant find variable: exports". But this is a valid ts code compiled to es5 using commonjs.

Is this a node project or a web application that is supposed to run in browser? 

If it's a node app that you're testing, then you're missing [the `env.type` setting](https://wallabyjs.com/docs/integration/node.html) to run your test in node.

If it's browser tests, then it depends how your app is supposed to work in a browser. CommonJs is not supported in browsers, so you must be using something to build your app, and wallaby supports both [webpack](https://wallabyjs.com/docs/integration/webpack.html) and [browserify](https://wallabyjs.com/docs/integration/browserify.html).

**Comment by cleytonb** [comment]
It is a library that is supposed to run in browser. It wasn't clear that I needed to build using some module loader because [this sample](https://github.com/wallabyjs/wallaby-typescript-sample/) don't have any.

Will try to configure using webpack then.

**Comment by ArtemGovorov** [comment]
The sample you've mentioned works because it uses `module XYZ {...}` that doesn't compile to CommonJs.

CommonJs doesn't work in browser as is, so it's not a limitation of wallaby.js or something specific to wallaby.js. To make your library work in a browser, you'll need to set up the build process anyway, no matter how you set up your tests.

You may find [this sample helpful](https://github.com/ArtemGovorov/wallaby-webpack-sample/) to setup a TypeScript + Webpack project.
