### ISSUE TITLE
Documentation - Which webpack usage

### ISSUE THREAD

**Issue by brianmhunt** [wallabyjs/public#772]
### Issue description or question

[Webpack](https://github.com/webpack/karma-webpack) has two means of loading files:

1.  Each test as an entry

```javascript
module.exports = function(config) {
  config.set({
    // ... normal karma configuration
    files: [
      // all files ending in "_test"
      {pattern: 'test/*_test.js', watched: false},
      {pattern: 'test/**/*_test.js', watched: false}
      // each file acts as entry point for the webpack configuration
    ],

    preprocessors: {
      // add webpack as preprocessor
      'test/*_test.js': ['webpack'],
      'test/**/*_test.js': ['webpack']
    },

    webpack: {
      // karma watches the test entry points
      // (you don't need to specify the entry option)
      // webpack watches dependencies

      // webpack configuration
    },

    webpackMiddleware: {
      // webpack-dev-middleware configuration
      // i. e.
      stats: 'errors-only'
    }
  });
};
```

2. Single (or few) entry point(s)

```javascript
files: [
  // only specify one entry point
  // and require all tests in there
  'test/test_index.js'
],

preprocessors: {
  // add webpack as preprocessor
  'test/test_index.js': ['webpack']
},
// test/test_index.js

// require all modules ending in "_test" from the
// current directory and all subdirectories
var testsContext = require.context(".", true, /_test$/);
testsContext.keys().forEach(testsContext);
```

Is one of these preferable over the other with Wallaby?

It seems that the first method would allow more granular re-testing than the latter.  I'm using the second method, and it seems that changing any file, even on leaves, causes the entire test process to re-run.

**Comment by ArtemGovorov** [comment]
Those approaches are for karma-webpack plugin, and wallaby works differently from karma. In wallaby [`tests` list should only list files with tests](https://wallabyjs.com/docs/config/files.html#tests), with `wallaby-webpack` those will be used as entry points for webpack compilation, so no `require.context` is required.

And as you've mentioned, this allows wallaby more granular re-testing, so if you change a test file (or a source file that is covered by few tests), wallaby will be able to re-run just those tests that need to be run, not everything.

**Comment by ArtemGovorov** [comment]
So in terms of the original question, wallaby is using `each test as an entry` approach. Having said that, if you need to have some other entry points (that are not tests), you may do it via the [`entryPatterns` setting](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns). 

Hope it makes sense.

**Comment by brianmhunt** [comment]
Thanks Artem - that makes sense, grateful for the clarification.

Have a great weekend.
