### ISSUE TITLE
ngCliWebpack issues

### ISSUE THREAD

**Issue by nerumo** [wallabyjs/public#775]
Hi, first thanks for the ngCliWebpack example. I'm still having issues to run wallaby. First, I guess the wallaby-webpack npm package is missing in your example (or is it now part of the plugin?).
Second: I have component builder tests with angular 2. In those tests it can't find the reference to .scss files. The error message is:
Runtime error: Error: Cannot find module "./example.component.scss"

And third: the initial start of wallaby only shows grey points on the side of webstorm (eap 2016.3). After I change a particular test file, it starts showing the true test coverage. This step has to be repeated for every test in the project.

All the configuration is copied from your great ngCliWebpack example (with no adaptions). Thank you for your help.

**Comment by nerumo** [comment]
addition: if I save some specific test files, I get the following error:
Runtime error: Error: Cannot find module '1111'
After that the wallaby server died. And now wallaby can't find any tests anymore. Is there a cache to be cleared?

**Comment by ArtemGovorov** [comment]
Hi,

> First, I guess the wallaby-webpack npm package is missing in your example

Thanks, confirmed, it was missing. Added it to the the dev dependencies.

> Runtime error: Error: Cannot find module "./example.component.scss"

The example is using CSS, so you'll need to change the pattern in your `files` list: 
```JavaScript
{pattern: 'src/**/*.css', load: false},
```

> And third: the initial start of wallaby only shows grey points on the side of webstorm (eap 2016.3)

> addition: if I save some specific test files, I get the following error:
Runtime error: Error: Cannot find module '1111'

Can't reproduce those one in the example. Is it only reproducible in your project or in the example repo as well? If only in your project, could you please fix the issue with the `.scss` files (as described above), try again and and if it is still happening, create and share a sample project where I could reproduce it?

Regarding the cache cleaning, you may change wallaby config (even a space anywhere would do), and restart wallaby, this should clear the cache.

**Comment by nerumo** [comment]
tnx, the scss now works. the cache cleaning also did it's job. but the module resolution error persists. can I somehow privately submit the project?

**Comment by ArtemGovorov** [comment]
I have created a private repo and added you as a collaborator, you should receive and invitation email and can push the project there.

**Comment by zpydee** [comment]
thanks for example project!

**Comment by zpydee** [comment]
my project seems not to be working after upgrading angular-cli to beta 14 in order to run on angular 2.0.0. is any configuration  change required?

**Comment by ArtemGovorov** [comment]
@zpydee Updated the https://github.com/wallabyjs/ngCliWebpackSample sample to use angular-cli beta 14. It works now.

The only wallaby specific thing that wasn't working (and it was pretty clear why from the error message), was the [changes in the `zone.js` imports for angular 2 in the test setup](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/test.ts#L3-L8). After doing the same in [the `wallabyTest.js` file](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts#L3-L8).
