### ISSUE TITLE
Jest 15.0.2 - Cannot read property '_jasmineAdapter' of undefined

### ISSUE THREAD

**Issue by yleflour** [wallabyjs/public#776]
### Issue description or question
When running Jest I get the following output
```
[Info]​​​​​ console.log:  FAIL  client-site/src/common/direction/__tests__/saga.js
​​​​​[Info]​​​​​ console.log:   ● Test suite failed to run
​​​​​[Info]​​​​​     TypeError: Cannot read property '_jasmineAdapter' of undefined
​​​​​[Info]​​​​​       
​​​​​[Info]​​​​​       at Object.<anonymous> (../../../wallaby/runners/node/jest@0.4.3/jasmine2Initializer.js:14:2761)
​​​​​[Info]​​​​​       at process._tickCallback (internal/process/next_tick.js:103:7)
```

Going through the old issues, I know that you already faced this with Jest. Right now I am using version 15.0.2.

### Wallaby.js configuration file

```javascript
/* eslint-disable max-len */
const path = require('path');

module.exports = (wallaby) => {
  process.env.NODE_PATH += `${path.delimiter}${path.join(wallaby.localProjectDir, 'client-site', 'node_modules')}${path.delimiter}${path.join(wallaby.localProjectDir, 'server', 'node_modules')}`;
  const babelCompiler = wallaby.compilers.babel({
    plugins: ['transform-runtime', 'transform-flow-strip-types', 'react-hot-loader/babel'],
    presets: ['es2015', 'stage-0', 'react'],
  });

  return {
    files: [
      { pattern: 'client-site/jest/environment.js', instrumented: false },
      { pattern: '**/__mocks__/*.js', instrumented: false },
      'client-site/src/**/*.js',
      '!client-site/src/**/__tests__/*.js',
      { pattern: 'server/jest/environment.js', instrumented: false },
      'server/src/**/*.js',
      '!server/src/**/__tests__/*.js',
    ],

    tests: [
      'client-site/src/**/__tests__/*.js',
      'server/**/__tests__/*.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      'client-site/**/*.js': babelCompiler,
    },

    bootstrap: (Wallaby) => {
      Wallaby.testFramework.configure({
        moduleDirectories: [
          'node_modules',
          'client-site/node_modules',
          'client-site/src',
          'server/node_modules',
        ],
        moduleNameMapper: {
          '^[./a-zA-Z0-9$_-]+\\.(jpg|png|gif|eot|svg|ttf|woff|woff2|mp4|webm)$': '<rootDir>/client-site/jest/FileStub.js',
          '^[./a-zA-Z0-9$_-]+\\.css$': '<rootDir>/client-site/jest/CSSStub.js',
          '^[./a-zA-Z0-9$_-]+\\.scss$': '<rootDir>/client-site/jest/CSSStub.js',
        },
        testEnvironment: 'node',
        verbose: true,
      });
    },
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.4.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Thanks for the report. I have tried this project https://github.com/wallabyjs/wallaby-jest-sample, added you config jest configuration, but can't reproduce the issue. 

Could you please try the sample project (before running the `npm install`, change the `jest-cli` version to 15.0.2), to see if it works for you? If it does, could you please fork it and try to add the bits I'm missing to reproduce the issue (or create a sample based on your current project)?

Also, what is your wallaby core version?

**Comment by yleflour** [comment]
I just tested the sample and it works.

I am running a one repo project with multiple sub-projects which had different versions of jest-cli installed throughout the folders which wallaby probably picked up. So I deleted every node_modules folder, gathered my test config at the root, npm installed everything and relaunched Wallaby and it works.

By the way, for future reference, how do you find the wallaby core version? You should add a command (I am using vscode) to get the infos such as `Wallaby.js:info`

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update.

Sorry I didn't mention how to look up the core version, it's displayed in the VS Code Dev Tools:
![screen shot 2016-09-06 at 6 45 04 pm](https://cloud.githubusercontent.com/assets/979966/18267387/36cbe888-7462-11e6-97b8-f89715b2e7e9.png)

I'll make sure we display the version in Wallaby Console output channel, just like we do for other editors.

**Comment by ArtemGovorov** [comment]
Just doubled checked, the core version is displayed in the Wallaby Console output as well:
![screen shot 2016-09-06 at 7 09 46 pm](https://cloud.githubusercontent.com/assets/979966/18268069/89f8d77a-7465-11e6-9853-271b23e5e0ab.png)

**Comment by IPWright** [comment]
👍 Blatting `node_modules` and re-running an `npm-install` worked for me too.
