### ISSUE TITLE
Jest 15.1.1

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#777]
### Issue description or question

I'm getting this error when attempting to configure tests to use Jest:

```
​​​​​jest-cli node module is not found or the version is not supported, missing `npm install jest-cli --save-dev`?
```

Jest is installed, and is using version 15.1.1. Is this version unsupported?

Thanks,

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
	var typescriptOptions = {
		module: 'commonjs',
		target: 'es5',
		jsx: 'react',
		experimentalDecorators: true,
		transpileOnly: true,
	};

	return {
		files: [
			{ pattern: 'scripts/**/*.ts', load: false },
			{ pattern: 'scripts/**/*.tsx', load: false },
			{ pattern: 'scripts/**/*.spec.ts', ignore: true },
			{ pattern: 'scripts/**/*.spec.tsx', ignore: true },
		],

		tests: [
			{ pattern: 'scripts/**/*.spec.ts', load: false },
			{ pattern: 'scripts/**/*.spec.tsx', load: false },
		],

		compilers: {
			'**/*.ts': wallaby.compilers.typeScript(typescriptOptions),
			'**/*.tsx': wallaby.compilers.typeScript(typescriptOptions),
		},

		testFramework: 'jest',

		env: {
			type: 'node',
			runner: 'node',
		},

		setup: function (wallaby) {
			wallaby.testFramework.configure({
				automock: false,
			});
		}
	};
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
I have tried this sample project https://github.com/wallabyjs/wallaby-jest-sample with jest 15.1.1 but can't reproduce the issue.

Could you please try cloning the sample project, running `npm install` and see if it works for you?

**Comment by ArtemGovorov** [comment]
I have also just added some more diagnostics and published the core version (1.0.287), please restart your IDE and start wallaby to get the core update. The error message after the update should include some error stack.

**Comment by dylanparry** [comment]
Sorry, my mistake—I'd done `npm i -D jest` but not `npm i -D jest-cli`. Even though the former installs the latter as a dependency, it doesn't seem to work unless I install it explicitly.

It's now picking up Jest correctly, however it doesn't seem to be correctly finding my tests. The files with the tests in have grey squares next to all of them, implying that they aren't being ran.  It's showing `No failing tests, 0 passing.` in the output window.

I've created a simple test in one of the test files:

```javascript
describe('test', () => {
	it('is true', () => {
		expect(true).toBeTruthy();
	});
});
```

and that isn't being ran either.

Any ideas?

**Comment by ArtemGovorov** [comment]
>  It's showing `No failing tests, 0 passing`. in the output window.

Try removing the `load: false` from your `tests`/`files` patterns. Sorry I didn't noticed and didn't mentioned didn't earlier. With the setting wallaby just doesn't load any tests, hence `No failing tests, 0 passing`. Any specific reason you have the `load: false` attribute set?

**Comment by dylanparry** [comment]
Ah brilliant, thanks. That was a remnant from when I was using Webpack/Mocha/Electron to run tests—can't remember why it was needed, but removing it now makes everything work properly. Thanks again :)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
Yep, in webpack the setting is required to avoid loading anything before it is webpack-ed (bundled).
