### ISSUE TITLE
Tests run in SublimeText 3, but not via the app

### ISSUE THREAD

**Issue by Hitman666** [wallabyjs/public#778]
### Issue description
I'm able to run Wallaby in ST3 as you can see on the screenshot:

![](http://i.imgur.com/Dl4cFg8.png)

but when I run this via the app (I wanted to see the test coverage report) I'm getting this:

![](http://i.imgur.com/IC8CMNb.png)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    return {
        files: [
            {pattern: 'www/lib/ionic/js/ionic.bundle.js', instrument: false},
            {pattern: 'www/lib/ionic-platform-web-client/dist/ionic.io.bundle.min.js', instrument: false},
            {pattern: 'www/lib/ionic-service-core/ionic-core.js', instrument: false},
            {pattern: 'www/lib/ngCordova/dist/ng-cordova.min.js', instrument: false},
            {pattern: 'www/lib/angular-markdown-directive/markdown.js', instrument: false},
            {pattern: 'www/lib/angular-translate/angular-translate.js', instrument: false},

            {pattern: 'www/lib/angular-phonegap-push-notification/push.js', instrument: false},
            {pattern: 'www/lib/angular-phonegap-ready/ready.js', instrument: false},
            {pattern: 'www/lib/angular-sanitize/angular-sanitize.min.js', instrument: false},
            {pattern: 'www/angular-ios9-uiwebview.patch.js', instrument: false},

            'www/js/app.js',
            'www/js/controllers/signup.js',

            {pattern: 'www/lib/angular-mocks/angular-mocks.js', instrument: false}
        ],
        tests: [
            'tests/controllers/*.spec.js',
            'tests/controllers/**/*.spec.js',
        ],

        debug: true,

        testFramework: 'jasmine',

        reportConsoleErrorAsError: true
    };
};
```

### Code editor or IDE name and version
Sublime Text v3

### OS name and version
OSX El Capitan 10.11.4

**Comment by ArtemGovorov** [comment]
Wallaby App doesn't run tests itself, it's just reporting the results from currently connected editors. Perhaps there was another editor started at the same time where the error was happening? Try stopping wallaby in all editors, starting your tests in Sublime Text and then opening/refreshing the app. Also, just to make sure, try opening [Wallaby Tests view](https://wallabyjs.com/docs/intro/get-started-sublime.html#failing-tests) in the editor just to make use there're no failing tests.

**Comment by Hitman666** [comment]
Ah, you're totally right. I had more ST3 windows opened with the same project 😳
