### ISSUE TITLE
Using with ES6

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#779]
Hi, since Node 6 can run ES6 code .. is it possible to make wallaby run with node 6 so that I do not need to transpile code with babel anymore?

**Comment by ArtemGovorov** [comment]
It is possible. You don't actually have to do anything special - it should just work (as long as the node version that you're using with wallaby supports ES6). For example, [this sample test](https://github.com/wallabyjs/wallaby-node-iojs-sample) is using ES6 arrow functions without any transpilation.
