### ISSUE TITLE
"Can't find variable React" when using webpack + babel

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#78]
In my spec file I use `TestUtils` which are required separately. Note that `React` is not referenced in spec.
In my source file I require React explicitly.

I've pushed a test case to the repository wallabyjs/wallaby-webpack-es7

**Comment by ArtemGovorov** [comment]
@okonet I think that is [how babel works](https://babeljs.io/docs/usage/jsx/). It translates JSX tags to `React.createElement` calls. 
I see two options here:
- add react to wallaby config `files` list, so it will be loaded to the sandbox (pushed the change to wallabyjs/wallaby-webpack-es7 repo).
- import react to every spec just like you did in the comment.

I guess the first option is better for your case.

**Comment by okonet** [comment]
Hmmm, why is it working with karma-setup then? But thanks for explaining it.

**Comment by ArtemGovorov** [comment]
I'm not sure why it works with karma, could you please share your karma config?

**Comment by okonet** [comment]
You're right. Karma has it included as well. Sorry for bothering. I had to double check it.
