### ISSUE TITLE
Official example not working with Jest

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#785]
### Issue description or question

I've just tried wallaby v 1.0.64 with Jest using https://github.com/wallabyjs/wallaby-jest-sample and it threw:

```
TypeError: require(...).buildHasteMap is not a function
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
```

### Wallaby.js configuration file

https://github.com/wallabyjs/wallaby-jest-sample/blob/master/wallaby.js

Wallaby core v1.0.259

### Code editor or IDE name and version

IntelliJ IDEA v2016.2

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The sample has the `"jest-cli": "*"` in the `package.json`, so it installs the latest `jest-cli` (v15.1.1 as of today). Core 1.0.259 only supports Jest v13.x, so you'll need to run:
```
npm i jest-cli@13
```
Jest v14 and v15 had introduced a few changes, so we have been adding its support to the core as those versions were released. The latest core v1.0.287 (as of today) supports Jest v14 and v15.
