### ISSUE TITLE
Wallaby.js App: Ordering of files/folders

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#788]
First off, I really love the Web interface—it gives me excellent code coverage feedback at a glance!

I've noticed that the ordering of files/folders in the "files" view of the interface is done alphabetically, which means that there's a mix of files and folders instead of the folders appearing at the top.

Eg.

![image](https://cloud.githubusercontent.com/assets/3692873/18468676/e3889852-799c-11e6-9eb4-6bc8e0500712.png)

Notice how the `classes` folder appears below `bootstrap.tsx`, and how there's a `tests` folder towards the end of the listing in between a bunch of `.ts` files?

Would it be possible to fix this so that folders appear at the top of the list as they would in most file managers like Explorer etc? That would make it easier to find things when the contents of the folders start to get a bit long :)

Thanks!

**Comment by ArtemGovorov** [comment]
Thanks for the feedback! The sorting order is fixed, just refresh you Wallaby.js App page now (or within the next 5 minutes) and it it should be ok.

**Comment by dylanparry** [comment]
Wonderful :) That's much better, thanks!
