### ISSUE TITLE
Show console.log in tool window when all tests pass

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#79]
Currently the `console.log` messages are only displayed in the tool window when there is a test that fails.
I would like to see them when all tests pass as well, for debugging purposes, when you want to see the contents of a large object, or just to verify that all of my `console.log`s are removed after fixing my tests.

You could rename the "Failing tests" tool window to "Test messages" or something like that, because the window is not only showing you failing tests, but also stack traces and console output.

**Comment by ArtemGovorov** [comment]
I understand that what I'm about to suggest is not exactly what you are asking, but if you invoke `Show line test(s)` action in any required context, such as a test or a source file, it will show you all console.log messages triggered by the test or all console.log messages triggered by all tests covering the line of code.

**Comment by fvanwijk** [comment]
Yes, it shows console output in the popup window. Looks like a workaround? :)

I expect consistent behaviour, eg. seeing toolbox output when `console.log` is used, triggered by the *automatic* test. This should have no connection with the outcome (pass or fail) of the test.
Let me know what you think :)

**Comment by ArtemGovorov** [comment]
Popup window displays latest output for any given context, no matter when did listed tests run. When invoked in context of a test, it's something like a test explorer, where you can select a test and inspect the latest console.log for it.

So from the UX perspective, if you make some change, and it has required 3 tests to run, would you like to see the latest console.log output only for those 3? Or you'd actually like to have an access to (the latest) console.log output from all of your tests?

**Comment by fvanwijk** [comment]
I think it would be most consistent when only the console.log output for those 3 tests is displayed.

In general I think that the UX challenge is that the tool window does not give any context about its contents. When you see output for failed tests and exceptions, the context can be derived implicitely from he contents of the log, but it is not possible to derive context for the tests that are fired automatically, because you do not know exactly which tests are required to run when some code is changed. Therefore, in case of an empty tool window, you do not know if that is because there are no console.logs anymore or because there are no tests (or code) fired with console.logs in it.

When you may implement some 'project overview/summary' popup or tool window in the future, with total coverage percentage, etc., I presume that these UX issues could be solved a lot easier. I haven't really thought that out yet.

**Comment by ArtemGovorov** [comment]
Thanks for you thoughts! I agree about the context, it may be hard to distinguish between nothing happened and no console.log calls.

Implementing project wide report/summary will certainly help will some of these issues [and it is planned](https://github.com/wallabyjs/public/issues/38).

**Comment by smcenlly** [comment]
This information is available in [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html). We do not have plans to show console in Wallaby Tests output when tests are passing but Wallaby App allows you to quickly find (and filter) tests with console output.
