### ISSUE TITLE
​​TypeError: Cannot set property '0' of undefined​​

### ISSUE THREAD

**Issue by jeromu** [wallabyjs/public#790]
### Issue description or question
After a while, I get this error: ​​"TypeError: Cannot set property '0' of undefined​​", and not test run after that, even after Stopping/Starting Wallaby again.

The workaround I found is to delete the content of the projects folder (in c:/users/(user)/.vscode/extensions/WallabyJs.wallaby-vscode1.0.23/), or re-saving the wallaby config.

What causes this instability?

### Wallaby.js configuration file

```javascript
//var babel = require('babel-core');

module.exports = function (wallaby) {
  return {
    files: [
      'server/src/**/*.js',
      { pattern: 'server/src/test/live/*-test.js', ignore: true },
      { pattern: 'server/src/test/units/**/*-test.js', ignore: true },
      { pattern: 'server/src/test/units/*-test.js', ignore: true },
      { pattern: 'server/src/test/units/resources/**/*.*', instrument: false, load: true, ignore: false },  // files used by tests
      { pattern: 'api/swagger/*.yaml', instrument: false, load: true, ignore: false }
      { pattern: 'static/favicon.ico', instrument: false, load: true, ignore: false }
    ],
    debug: true,

    tests: [
      'server/src/test/units/**/*-test.js',
      'server/src/test/units/*-test.js',
      // According to the help, the 'tests' list should only include actual tests, not helper functions or other resources, so ignoring these
      { pattern: 'server/src/test/units/resources/**/*.*', ignore: true }
    ],
    env: {
      type: 'node',
      params: {
        env: 'PORT=0;TESTING=true;NO_MORGAN_LOGS=true;NODE_ENV=development'
      }
    },
    testFramework: 'mocha',
    bootstrap: function (wallaby) {
      const mocha = wallaby.testFramework;
      mocha.timeout('10000');
    },
    workers: {
      // Set both to 1, since tests are dependent
      initial: 1,
      regular: 1,
      recycle: true  // recycles workers (slower, but more consistent when some tests may not clean up after themselves)
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babelrc: true,
        presets: ['es2015-node4']//,
        // babel: babel
        // babel options
        // like `stage: n` for Babel 5.x or `presets: [...]` for Babel 6
        // (no need to duplicate .babelrc, if you have it, it'll be automatically loaded)
      })
    }
  };
};

```

### Code editor or IDE name and version
Visual Studio Code (latest)

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
It sounds like a corrupted caching issue. Currently you can force wallaby project cache to be cleared by stopping wallaby, changing the wallaby configuration file content (even just adding a space somewhere inside) and running wallaby again. Deleting the projects folder does the same.

As to why it's happening - there may be a few reasons. Is the issue reliably reproducible? Would you be able to create/share a sample project where I could reproduce it? I can create you a private repo for it if you like.

**Comment by ArtemGovorov** [comment]
I can try to create a sample project if you share your `package.json`, `.babelrc` and node version, but I have a feeling that the issue is project/code/test specific.

Also could you please paste the full error (and few entries before it) from the Wallaby Console output channel?

**Comment by jeromu** [comment]
Thanks!  But, I couldn't reproduce after fixing a bunch of problems with the tests themselves.  Closing the issue.  Thanks.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by vespertilian** [comment]
@ArtemGovorov your fix worked for me!

**Comment by oliversalzburg** [comment]
I just opened VS Code and started Wallaby and ran into this issue. I changed something in the config file and changed it right back, then the error was gone.

It's disappointing to see that no proper fix was implemented for this behavior in the past year.

It's also disappointing that it is a known issue that this error is produced by including non-test files as tests, but Wallaby is unable to detect and report the issue.

**Comment by ArtemGovorov** [comment]
> It's disappointing to see that no proper fix was implemented for this behavior in the past year.

Unfortunately we can't reproduce the issue, it only seem to be affecting certain projects/setups and no one yet was able to provide a repro. If you can provide a sample repo where we can reproduce it, we'll fix it as soon as we can.

**Comment by oliversalzburg** [comment]
If the problem is caused by a corrupted cache and clearing said cache resolves the problem, I don't understand how an example project is supposed to demonstrate the issue, as the problem was never with the project in the first place.

I have been using the product for just a few days and have encountered this error a couple times already. It's surprising that it's apparently hard to reproduce and doesn't come up during regular development every once in a while.

**Comment by ArtemGovorov** [comment]
> If the problem is caused by a corrupted cache and clearing said cache resolves the problem, I don't understand how an example project is supposed to demonstrate the issue, as the problem was never with the project in the first place.

Sorry I must have not been clear about what is happening. The issue only shows up in *some* projects/environments, the majority of our users are not experiencing the issue. So far, we couldn't reproduce it or find what kinds/attributes/files/actions of the affected projects are causing the issue. We ourselves are using Wallaby internally in a few projects, not to mention many test/user samples we run everyday and had never hit it.

Once we find a reliable way to reproduce the issue, I think it'll be a matter of very short time span to get it fixed and publish the fix. Unfortunately, we can't reproduce it without some help from those who are experiencing it.

**Comment by oliversalzburg** [comment]
Alright. Makes sense. I'll keep an eye out for what might be the reason for this on our end. I seem to be seeing this usually when I start introducing Wallaby into a new project. Once I'm set up and have a workflow going, I don't see this happening anymore. I'll report back when I have something useful.

**Comment by sergeyzwezdin** [comment]
@ArtemGovorov  The issue started to appear yesterday:

![image](https://user-images.githubusercontent.com/800755/86075440-71cd4380-baa1-11ea-92d0-41a3706306ea.png)

Deleting `projects` folder helps only until I change my code and Wallaby re-starts the test. After that issue appears again.

I cannot reproduce it in separate project and I cannot share my project. Any advice on how to fix it?

**Comment by ArtemGovorov** [comment]
@sergeyzwezdin Have you also tried to delete Jest's cache (if you are using Jest):
```
jest --clearCache
```

> I cannot reproduce it in separate project and I cannot share my project. Any advice on how to fix it?

If the suggestion above doesn't help, please create a new issue and share Wallaby Diagnostics report (the steps how to get the report are described in the new issue template).

**Comment by sergeyzwezdin** [comment]
@ArtemGovorov Thanks! `jest -clearCache` doesn't help

I've created another issue - https://github.com/wallabyjs/public/issues/2466
