### ISSUE TITLE
display deep diff

### ISSUE THREAD

**Issue by rgoldman-qb** [wallabyjs/public#791]
### Issue description or question

when a test fails, is there a way to see the deep difference - instead of seeing this message 
```expected [ Array(1) ] to deeply equal [ Array(1) ]​​```

for example - if I'm comparing these two arrays 
```[{ id: 1, values: [1, 2, 3] }]   [{ id: 1, values: [1, 2, 7] }]```  
i want to see that the second index of the values array is different

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
    return {
        "files": [
            "src/**/*.ts",
            "!src/**/*Tests.ts"

        ],
        "tests": [
            "src/**/*Tests.ts"
        ],
        debug: true,
        env: {
            type: 'node'
        }
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.5.2

### OS name and version

OSX v10.10.5

**Comment by ArtemGovorov** [comment]
Could you please share a sample test file (with a test doing the assertion)?

**Comment by ArtemGovorov** [comment]
Colorized diff output support landed in VS Code: https://twitter.com/wallabyjs/status/776331730387017729

**Comment by rgoldman-qb** [comment]
Thanks!!
