### ISSUE TITLE
Test failures do not appear inline in code

### ISSUE THREAD

**Issue by chris-nissen** [wallabyjs/public#794]
### Issue description or question
My test failures are showing pink squares on the failing line rather than red, and they don't appear inline in the code. But they do appear properly in the output window.

![image](https://cloud.githubusercontent.com/assets/8062774/18649571/69151858-7e7d-11e6-8585-a0ab9b351ecb.png)
![image](https://cloud.githubusercontent.com/assets/8062774/18649619/a4633dcc-7e7d-11e6-9064-f8979e8bd2f3.png)

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');

module.exports = function (wallaby) {

	var webpackPostprocessor = wallabyWebpack(webpackConfig);

	return {
		name: 'xxx',

		files: [
			{ pattern: 'App/**/*.ts', load: false },
			{ pattern: 'App/**/*.tsx', load: false },
			{ pattern: 'App/**/*.spec.ts', ignore: true }
		],

		tests: [
			{ pattern: 'App/**/*.spec.ts', load: false }
		],

		testFramework: 'mocha',

		postprocessor: webpackPostprocessor,

		setup: function () {
			window.__moduleBundler.loadTests();
		},

		debug: false
	};
};
```

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows 10

### Webpack configuration file

```javascript
/* eslint-disable no-var, strict, prefer-arrow-callback */
'use strict';

var path = require('path');
var webpack = require('webpack');

module.exports = {
	cache: true,
	entry: {
		main: './App/main.tsx',
		vendor: [
			'babel-polyfill',
			'bootstrap',
			'react',
			'react-dom',
			'react-router',
			'redux',
			'redux-thunk',
			'react-router-redux'
		]
	},
	output: {
		path: path.resolve(__dirname, './dist/scripts'),
		filename: '[name].js',
		chunkFilename: '[chunkhash].js'
	},
	module: {
		loaders: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				loader: 'babel-loader?presets[]=es2015&presets[]=react!ts-loader'
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel',
				query: {
					presets: ['es2015', 'react']
				}
			}
		]
	},
	plugins: [
		// Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
		new webpack
		.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' })
	],
	resolve: {
		// Add `.ts` and `.tsx` as a resolvable extension.
		extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
	},
	devServer: {
		contentBase: '.',
		host: 'localhost',
		port: 9000
	}
};
```

**Comment by ArtemGovorov** [comment]
@chris-nissen Thanks for sharing the webpack config, could you please also share your `tsconfig.json` file?

**Comment by chris-nissen** [comment]
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es6",
    "jsx": "preserve",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true
  },
  "exclude": [
      "node_modules"
  ]
}
```

**Comment by ArtemGovorov** [comment]
Thanks, it looks like webpack loaders are breaking source maps. When using Wallaby with Webpack and TypeScript, you need
- remove [ts-loader](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript) because wallaby built-in compiler will compile TS files,
- [use Babel preprocessor](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) if your TS code gets compiled to ES6.

So your config may look like this:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');

// as described in
// https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript
webpackConfig.module.loaders = [];
resolve.extensions = ['', '.js', '.jsx'];

module.exports = function (wallaby) {

    var webpackPostprocessor = wallabyWebpack(webpackConfig);

    return {
        name: 'xxx',

        files: [
            { pattern: 'App/**/*.ts', load: false },
            { pattern: 'App/**/*.tsx', load: false },
            { pattern: 'App/**/*.spec.ts', ignore: true }
        ],

        tests: [
            { pattern: 'App/**/*.spec.ts', load: false }
        ],

        testFramework: 'mocha',
       
        // as descibed in
        // https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel
        preprocessors: {
          '**/*.js': function(file){ 
            require('babel-core').transform(
              file.content, {sourceMap: true, presets: ['es2015', 'react']});
        },

        postprocessor: webpackPostprocessor,

        setup: function () {
            window.__moduleBundler.loadTests();
        },

        debug: false
    };
};
```

Please let me know if this works for you.

**Comment by ArtemGovorov** [comment]
Quick update, I made a mistake in the preprocessor, it should be:

```javascript
        preprocessors: {
          '**/*.js': function(file) { 
            return require('babel-core').transform(
              file.content, {sourceMap: true, presets: ['es2015', 'react']});
          }
        },
```

**Comment by chris-nissen** [comment]
That updated code looks the same to me.

I also added "webpackConfig." onto the front of the "resolve.extensions" line.

But now I'm getting 
```
ModuleParseError: Module parse failed: C:\Users\chris.nissen\Source\Repos\<...>\Web\App\main.tsx Unexpected token (11:29)
You may need an appropriate loader to handle this file type.
```

**Comment by chris-nissen** [comment]
Do I need a compiler to get from the Typescript to es2016 as configured here: https://github.com/wallabyjs/public/issues/327#issuecomment-244401516

**Comment by ArtemGovorov** [comment]
> That updated code looks the same to me.

I updated it in both places just in case.

>```
ModuleParseError: Module parse failed: C:\Users\chris.nissen\Source\Repos\<...>\Web\App\main.tsx Unexpected token (11:29)
You may need an appropriate loader to handle this file type.
```

How is the `main.tsx` file referenced from tests? 
Try expanding the preprocessor pattern to include jsx files (compiled from tsx files):

```javascript
 preprocessors: {
          '**/*.js*': ...,
```

**Comment by ArtemGovorov** [comment]
> Do I need a compiler to get from the Typescript to es2016 as configured here ...

You may need to add the `plugins: ...` part, but only if you have the specific issue with testing function names.

**Comment by chris-nissen** [comment]
Same error if I change the preprocessor pattern. The reference to main.tsx, I think, is coming from the "entry" object in the webpack config file. Should I be adding a line like this?
```
webpackConfig.entry = {};
```

**Comment by ArtemGovorov** [comment]
@chris-nissen Please try it, but you shouldn't need to, `wallaby-webpack` replaces the `entry`. Is there anything else referencing the file in your app?

**Comment by ArtemGovorov** [comment]
Also, try deleting the `devServer` in wallaby config:

```
delete webpackConfig.devServer;
```

**Comment by chris-nissen** [comment]
OK, adding that "entry" line resolves the error about main.tsx. 

I had moved on from that example test that I first posted, but I tried it again and it now fails with a red square as expected.

So this is now a separate problem--getting my modules to resolve. With a test that references another Typescript class (a Redux store), I'm now getting 
`
ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./Dummy in .\App\store
`
Here is the test file:
```
import * as Dummy from './Dummy';
import { expect } from 'chai';

describe('the dummy reducer', () => {

	it('should load junk', 	() => {
		const initialState: Dummy.DummyState = {
			junk: null
		};
		const action = {
			type: 'LOAD',
			junk: 'junk'
		};
		var newState = Dummy.reducer(initialState, action);
		
		expect(newState.junk).to.equal('junka');
	});
});
```
and here's the referenced file which is in the same directory:
```
import { typeName, isActionType, Action, Reducer } from '../redux-typed/StrongActions';
import { ActionCreator } from './index';
import { browserHistory } from 'react-router';

export interface DummyState {
	junk: string;
}

@typeName('LOAD')
class Load extends Action {
	constructor(
		public junk: string) {
		super();
	}
}

export const actionCreators = {
	load: (): ActionCreator => (dispatch, getState) => {
		dispatch(new Load('testing'));
	}
};

const initialState: DummyState = {
	junk: null
}

export const reducer: Reducer<DummyState> = (state, action) => {
	if (isActionType(action, Load)) {
		return {
			junk: action.junk
		}
	}

	return state || initialState;
};
```

**Comment by ArtemGovorov** [comment]
Awesome, we are getting somewhere :)

> `ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./Dummy in .\App\store`

This is an error from webpack, it for some reason can't find the `App\store\Dummy` file. What is the `Dummy` file extension? Windows paths are case sensitive, so please check if the file name case is correct.

**Comment by chris-nissen** [comment]
It's Dummy.ts. So I tried changing the import line to 
```import * as Dummy from './Dummy.ts';```
and the error goes back to a parse error:
```
ModuleParseError: Module parse failed: .\App\store\Dummy.ts Unexpected token (5:7)
You may need an appropriate loader to handle this file type.
```

**Comment by ArtemGovorov** [comment]
> So I tried changing the import line to 
`import * as Dummy from './Dummy.ts';`
and the error goes back to a parse error:

This is expected, you don't need to change it.

Could you please try adding `"module": "CommonJS"` to your `tsconfig.json`?

**Comment by ArtemGovorov** [comment]
I have set up [the sample repo](https://github.com/wallabyjs/wallaby-794) with your configs and structure and reproduced the issue.

Adding `"module": "CommonJS"` or ``"module": "es6"`` to your `tsconfig.json` `compilerOptions` fixes it, however I understand if it may not be desirable to change the config just for the sake of getting wallaby working, so another way is to just specify the setting in the [wallaby compiler setting for TypeScript](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings). That's what I did in the [sample repo](https://github.com/wallabyjs/wallaby-794/blob/master/wallaby.js#L30).

Wallaby copies specified `files`/`tests` to its own file cache (that [you can inspect](https://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page)), compiles, instruments, processes with webpack, etc., and uses the cache to serve the files from it. Without the `"module": "..."` setting, it was assuming that no module system is used (vanilla scripts) and it was renaming `.ts` files to `.compiled.js` files (`Dummy.ts` -> `Dummy.compiled.js`), so webpack didn't see them because of the `compiled` part in the name.

Hope it makes sense. Please let me know if this works for you. Feel free to change the repo if you have any more config issues.

**Comment by chris-nissen** [comment]
Yep, that worked. Thanks for the help, Artem!
