### ISSUE TITLE
Can Wallaby detect infinite loops?

### ISSUE THREAD

**Issue by andreipfeiffer** [wallabyjs/public#796]
### Issue description or question

I was curious if Wallaby is able or not to detect long running scripts, or infinite loops. If I mistakenly write a piece of code, it's not trivial to tell if it's a code problem, or a Wallaby problem (I also had problems starting it sometimes).

The setup I use is very simple.
I can reproduce this with a simple "while(1) {}" code.

Sublime consoles:
<img width="712" alt="screen shot 2016-09-20 at 16 17 20" src="https://cloud.githubusercontent.com/assets/2570562/18671897/8c1234ae-7f4e-11e6-91de-09a17c9cb2fb.png">

<img width="598" alt="screen shot 2016-09-20 at 16 17 41" src="https://cloud.githubusercontent.com/assets/2570562/18671900/8f179ac2-7f4e-11e6-80a2-999e9cc933c4.png">

Atom console:
<img width="1718" alt="screen shot 2016-09-20 at 16 24 40" src="https://cloud.githubusercontent.com/assets/2570562/18671965/ca14492c-7f4e-11e6-85a0-8a06616dda9d.png">

They just hang like that until I stop them.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: ['*List.js'],
    tests: ['*Test.js'],
    testFramework: 'jasmine',
    env: {
      type: 'node'
    },
    debug: true
  };
};
```

### Code editor or IDE name and version

Atom v1.10.2
Sublime Text v3

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment]
Good question, and thanks for providing the wallaby config.

Unlike any other test runners I know, Wallaby supports infinite loop detection for browser. Today we  have also added the support for infinite loop detection for node environment. The support is landed in core v1.0.290. The core will be updated automatically, to get the change ASAP, you [may force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Now if wallaby detects a possible loop for node, it'll report it in similar way it's doing it for browser environment:

<img width="747" alt="screen shot 2016-09-21 at 2 01 31 pm" src="https://cloud.githubusercontent.com/assets/979966/18697376/fb621e4a-8003-11e6-9d4d-0ec8e4b9b1c6.png">

(note that in case of Atom, you should check [Wallaby Console in the Dev Tools](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) for the message)

Regarding the recent issues with starting wallaby, I noticed you're using `jasmine` and there was an [issue with jasmine v2.5.1](https://github.com/wallabyjs/public/issues/668) and [issue with v2.5.2](https://github.com/wallabyjs/public/issues/793), where wallaby would just hang on the start. The issues are resolved now and are not related to the infinite loop detection.

**Comment by andreipfeiffer** [comment]
Thank you @ArtemGovorov for the quick response.

**Comment by andreipfeiffer** [comment]
Hey @ArtemGovorov I have v1.0.291 in my Atom editor, with a node env, and still hangs without any output if I add a while(1) {} statement.

Is any timeout set to detect these long running scripts?

**Comment by ArtemGovorov** [comment]
@andreipfeiffer Yes, there's a 5 seconds timeout. Here's the repo with your config: https://github.com/wallabyjs/wallaby-796, here's how it works for me in Atom:
![at](https://cloud.githubusercontent.com/assets/979966/18709965/13ab194c-8046-11e6-9a04-41f8120f8940.gif)

**Comment by andreipfeiffer** [comment]
Ohh shit, that console is for node env too? OK, I see that message too in that console.
Is it difficult to display the message in the Wallaby Console too?

Also, I can see now the error in Sublime.

**Comment by ArtemGovorov** [comment]
Yes, [it's where the debug output is displayed](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) regardless of the environment. Wallaby panel only displays test errors, while wallaby console (displayed in Dev Tools) displays less frequent setup errors (that come and go).

**Comment by andreipfeiffer** [comment]
Got it. Thanks a lot @ArtemGovorov , really helpful.
