### ISSUE TITLE
Wallabjs.com/app out of sync with IDE

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#798]
### Issue description or question

The wallabyjs.com/app is out of sync with my IDE. One is showing that the tests have passed, the other is not. Possibly related is the fact that I'm having to manually trigger some tests in my IDE (they're not detecting as I type some of the time).

I've tried re-starting wallaby, and I've tried re-loading my browser page.

Here is a screenshot of my IDE:

![image](https://cloud.githubusercontent.com/assets/1374775/18707377/af98a288-7fed-11e6-8adf-4e3685410b2b.png)

Here is the wallaby app page:

![image](https://cloud.githubusercontent.com/assets/1374775/18707384/ba531a1e-7fed-11e6-86b7-a58381a6ee1d.png)

And a console dump from the browser (doesn't show any errors)

> Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> /app/#/tests:1 Document was loaded from Application Cache with manifest http://wallabyjs.com/app/manifest.appcache
> /app/#/tests:1 Application Cache Checking event
> /app/#/tests:1 Application Cache NoUpdate event
> main.71bda00….js:2 app comp: initialising.
> main.71bda00….js:2 bus: starting.
> main.71bda00….js:2 bus: started.
> main.71bda00….js:2 app comp: initialised.
> main.71bda00….js:2 app comp: updating cache.
> main.71bda00….js:1 Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> main.71bda00….js:2 app comp: updated cache.
> /app/#/tests:1 Application Cache Checking event
> /app/#/tests:1 Application Cache NoUpdate event
> /app/#/tests:1 Application Cache Checking event
> /app/#/tests:1 Application Cache NoUpdate event
> Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
> Navigated to http://wallabyjs.com/app/
> /app/#/tests:1 Creating Application Cache with manifest http://wallabyjs.com/app/manifest.appcache
> /app/#/tests:1 Application Cache Checking event
> /app/#/tests:1 Application Cache Downloading event
> /app/#/tests:1 Application Cache Progress event (0 of 112) http://wallabyjs.com/app/monaco-editor/vs/editor/contrib/suggest/browser/symbol-sprite.svg
> /app/#/tests:1 Application Cache Progress event (1 of 112) http://wallabyjs.com/app/25a32416abee198dd821b0b17a198a8f.eot
> /app/#/tests:1 Application Cache Progress event (2 of 112) http://wallabyjs.com/app/monaco-editor/vs/editor/editor.main.nls.es.js
> /app/#/tests:1 Application Cache Progress event (3 of 112) http://wallabyjs.com/app/ac327c4db6284ef64ebe872b6308f5da.woff
> /app/#/tests:1 Application Cache Progress event (4 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/less.js
> /app/#/tests:1 Application Cache Progress event (5 of 112) http://wallabyjs.com/app/e6cf7c6ec7c2d6f670ae9d762604cb0b.woff2
> /app/#/tests:1 Application Cache Progress event (6 of 112) http://wallabyjs.com/app/c8ddf1e5e5bf3682bc7bebf30f394148.woff
> /app/#/tests:1 Application Cache Progress event (7 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.it.js
> /app/#/tests:1 Application Cache Progress event (8 of 112) http://wallabyjs.com/app/monaco-editor/vs/language/json/jsonWorker.js
> /app/#/tests:1 Application Cache Progress event (9 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/workerServer.js
> /app/#/tests:1 Application Cache Progress event (10 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/worker/workerMain.js
> /app/#/tests:1 Application Cache Progress event (11 of 112) http://wallabyjs.com/app/1dc35d25e61d819a9c357074014867ab.ttf
> /app/#/tests:1 Application Cache Progress event (12 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/lua.js
> main.71bda00….js:2 app comp: initialising.
> main.71bda00….js:2 bus: starting.
> main.71bda00….js:2 bus: started.
> main.71bda00….js:2 app comp: initialised.
> /app/#/tests:1 Application Cache Progress event (13 of 112) http://wallabyjs.com/app/d7c639084f684d66a1bc66855d193ed8.svg
> /app/#/tests:1 Application Cache Progress event (14 of 112) http://wallabyjs.com/app/splash.png
> /app/#/tests:1 Application Cache Progress event (15 of 112) http://wallabyjs.com/app/a35546eef3ea0de0d4735f23b0a0873b.eot
> /app/#/tests:1 Application Cache Progress event (16 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/csharp.js
> /app/#/tests:1 Application Cache Progress event (17 of 112) http://wallabyjs.com/app/f641a7d4e80fd6321135b1a2b4ce8bb1.svg
> /app/#/tests:1 Application Cache Progress event (18 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/objective-c.js
> /app/#/tests:1 Application Cache Progress event (19 of 112) http://wallabyjs.com/app/cd7296352d159532b66c07d98efb1126.ttf
> /app/#/tests:1 Application Cache Progress event (20 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.js
> /app/#/tests:1 Application Cache Progress event (21 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.de.js
> /app/#/tests:1 Application Cache Progress event (22 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/ini.js
> /app/#/tests:1 Application Cache Progress event (23 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/r.js
> /app/#/tests:1 Application Cache Progress event (24 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.es.js
> /app/#/tests:1 Application Cache Progress event (25 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.ja.js
> /app/#/tests:1 Application Cache Progress event (26 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.fr.js
> /app/#/tests:1 Application Cache Progress event (27 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/workerServer.nls.it.js
> /app/#/tests:1 Application Cache Progress event (28 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.js
> /app/#/tests:1 Application Cache Progress event (29 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/vb.js
> /app/#/tests:1 Application Cache Progress event (30 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/ruby.js
> /app/#/tests:1 Application Cache Progress event (31 of 112) http://wallabyjs.com/app/monaco-editor/vs/basic-languages/src/css.js
> /app/#/tests:1 Application Cache Progress event (32 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.ko.js
> /app/#/tests:1 Application Cache Progress event (33 of 112) http://wallabyjs.com/app/monaco-editor/vs/editor/contrib/quickOpen/browser/symbol-sprite.svg
> /app/#/tests:1 Application Cache Progress event (34 of 112) http://wallabyjs.com/app/monaco-editor/vs/base/common/worker/simpleWorker.nls.ru.js
### Wallaby.js configuration file

``` javascript
var webpackConfig = {
  module: {
    loaders: [
        { test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/ },
        { test: /\.less$/, loader: 'style!css!less', exclude: /node_modules/ },
        { test: /\.css$/, loader: 'style-loader!css-loader' }
    ]
  },
  devtool: 'inline-source-map' // just do inline source maps instead of the default
};

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.js', load: false },
            { pattern: 'tests/utils/*.js', load: false }
        ],
        tests: [
            { pattern: './tests/**/*.tests.js', load: false }
        ],
        testFramework: 'jasmine',
        compilers: {
            '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') })
        },
        postprocessor: wallabyPostprocessor,
        bootstrap: function() {
            window.__moduleBundler.loadTests();
        }
        // setup: function () {
        //     // required to trigger test loading
        //     window.__moduleBundler.loadTests();
        // }
    };
};
```
### Code editor or IDE name and version

Sublime Text v3 Build 3123
### OS name and version

Windows 10 Pro x64

**Comment by ArtemGovorov** [comment]
Thanks for sharing the screenshots and the logs!
We'll definitely need some more debug info to get to the bottom of the issue.

To rule out some simple things:
- Do you have only one editor launched with the project? If there're a couple of editors, both running wallaby, the different results may be coming from another editor.
- When you *refresh the page with the App*, does it start to display correct results? If not, does it start to display correct results if you *restart wallaby in editor and then refresh the page with the App*?

> Possibly related is the fact that I'm having to manually trigger some tests in my IDE 

Good spot! Did you notice it's always happening after manual runs? Or can happen without them? Also, how frequently does the issue show up (like once an hour/few hours/a day)?

Could you please set the [`debug: true` flag](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) in your config and the next time you see the issue, please paste the [output from Wallaby Console](https://wallabyjs.com/docs/intro/get-started-sublime.html#troubleshooting)? It doesn't have to be the full log, I'm specifically after lines containing `wallaby:uiService`, like:
```
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService UI client connected
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Outgoing message ui:handshake
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Incoming message ui:start
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Outgoing message ui:summary
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Outgoing message ui:files
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Incoming message ui:tests:resultsRequested
Wed, 21 Sep 2016 23:42:22 GMT wallaby:uiService Outgoing message ui:tests:allResultsUpdated
```

**Comment by IPWright83** [comment]
That's fine Artem I'll let you know when I get a log. To answer some of your questions:

- I normally "snap" tabs out of Sublime so I can work on code/testing on 2 different screens. I'm not sure how Sublime works, but I guess that might be 2 applications? I only start Wallaby in one window with the tests, while the code I'm normally modifying is on its own in the separate window.

- The app didn't seem to displaying correct results after both a restart of wallaby in the editor AND a refresh of the application.

- In this case manual runs also weren't updating the app. 

- I guess I've only noticed this issue maybe once a day at the moment, but I have phases of working with/without Wallaby and I've not been in a "with" phase long enough to spot a pattern yet.

**Comment by ArtemGovorov** [comment]
Thanks! So far it from your answers it seems like there's a phantom wallaby.js process hanging somewhere.

> The app didn't seem to displaying correct results after both a restart of wallaby in the editor AND a refresh of the application

This is interesting. When the issue shows up next time, please try to stop wallaby, refresh the app and see if it's still going to display anything. It shouldn't display anything because it needs a running instance of wallaby, but if it does then it's definitely a phantom instance of wallaby hanging somewhere.

When the issue shows up next time, try stopping wallaby and then killing all node processes on the machine, and restarting wallaby.

**Comment by smcenlly** [comment]
Closing this issue as we haven't had more detail or reports of more occurrences since Sep 22, 2016.
