### ISSUE TITLE
Opacity settings

### ISSUE THREAD

**Issue by olegafx** [wallabyjs/public#8]
Could you add opacity settings? Green color of that rectangles is too bright. It distracts me from a code.

![image](https://cloud.githubusercontent.com/assets/867546/6004489/2dd1ec1e-ab14-11e4-82c1-7077d075a470.png)

P.S. Thank you for the awesome tool :+1:

**Comment by ArtemGovorov** [comment]
https://twitter.com/wallabyjs/status/562522934082678784
