### ISSUE TITLE
TypeScript in IntelliJ reporting errors where there are none

### ISSUE THREAD

**Issue by DataTables** [wallabyjs/public#800]
### Issue description or question

I've installed the Wallaby plug-in for TypeScript and set it up [per the documentation](https://wallabyjs.com/docs/intro/get-started-jetbrains.html). It appears to run, but it is telling me there are errors in the code where there are none (I have both TSlint and TypeScript compiler configured to highlight errors and they aren't reporting any).

### Wallaby.js configuration file

```javascript

module.exports = function ( wallaby ) {
  return {
	"files": [
	  "helpers/**/*.ts"
	],
	"tests": [
	  "test/helpers/**/*.spec.ts"
	],
    compilers: {
      // I've tried it with and without this
      '**/*.ts': wallaby.compilers.typeScript({
        typescript: require('typescript')
      })
    }
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2016.2.4

### OS name and version

OSX - 10.11.5
Node: 6.3.0
TypeScript: 2.0.3

### A couple of examples:

> SyntaxError: Expected an identifier but found '.' instead
>	at helpers/async.ts:3

![screen shot 2016-09-23 at 16 58 12](https://cloud.githubusercontent.com/assets/278219/18792566/f45fed00-81ae-11e6-9bec-4e8f3714413e.png)

> SyntaxError: Use of reserved word 'class'
>	at helpers/i18n.ts:5

![screen shot 2016-09-23 at 16 59 42](https://cloud.githubusercontent.com/assets/278219/18792630/27004aca-81af-11e6-9323-da992dd8e737.png)

> SyntaxError: Use of reserved word 'let' in strict mode
>	at helpers/param.ts:7

![screen shot 2016-09-23 at 17 00 28](https://cloud.githubusercontent.com/assets/278219/18792655/4256f76a-81af-11e6-87d3-53377b019b78.png)

I've got 8 errors in total being reported by Wallaby. Not sure what I've done wrong!

**Comment by DataTables** [comment]
I should add:

> wallaby.js started
> core v1.0.294

**Comment by ArtemGovorov** [comment]
Your current wallaby config runs tests in a browser environment (PhantomJs).
Here's what happens: your `.ts` files compiled to `.js` according to your `tsconfig.json` (which I'm assuming targets ES6) and then wallaby tries to run the ES6 code in browser environment.

If you're writing a node.js application, you need to add the `env` setting to run your tests in node:
```javascript
module.exports = function (wallaby) {
  return {
    ...

    env: {
      type: 'node',
      runner: 'node'
    }
  };
};
```

If it's browser tests, then you'll need to add some more configuration depending on how your app gets built/loaded (like [webpack](https://wallabyjs.com/docs/integration/webpack.html)/[browserify](https://wallabyjs.com/docs/integration/browserify.html)/etc.). You're using ES6 modules, how do you compile/load them (if it is browser tests)?

**Comment by DataTables** [comment]
Awesome - that's the piece of information I was missing. Thanks!

I'll be getting my license shortly :-)
