### ISSUE TITLE
TypeError: describe.only is not a function with Jest

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#801]
### Issue description or question

I'm using Jest (`"jest-cli": "^15.1.1",`) and getting error

```
TypeError: describe.only is not a function
```

in the wallaby console if I try to run

```js
describe.only('should pass', () => {})
```

Which is valid and defined in jest: http://facebook.github.io/jest/docs/api.html#basic-testing and it works with CLI `jest` command. Same with `it`

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test';

module.exports = wallaby => ({
  files: [
    { pattern: 'src/**/*.js' },
    { pattern: 'src/**/*.js.snap' },
    { pattern: 'src/**/*.spec.js', ignore: true }
  ],

  tests: [
    { pattern: 'src/**/*.spec.js' }
  ],

  compilers: {
    'src/**/*.js': wallaby.compilers.babel()
  },

  env: {
    type: 'node',
    runner: 'node'
  },

  testFramework: 'jest'
});
```

### Code editor or IDE name and version

IntelliJ IDEA 2016.3 EAP

### OS name and version

OSX 10.11.5 (15F34)

**Comment by ArtemGovorov** [comment]
I'm not yet sure what's going on here, but `it.only` and `describe.only` don't work for me with CLI command (without wallaby involved at all):

```
 ./node_modules/.bin/jest
```
results in

![screen shot 2016-09-24 at 10 34 16 am](https://cloud.githubusercontent.com/assets/979966/18804735/a0b13c7e-8242-11e6-9a7e-eb7674ced83b.png)

I'm also using `jest-cli` v15.1.1.

**Comment by ArtemGovorov** [comment]
I'm trying on this sample: https://github.com/wallabyjs/wallaby-jest-sample. Is there any setting I'm missing (that turns on `.only` support in jest)?

**Comment by ArtemGovorov** [comment]
Have done some more investigation, here's [the commit](https://github.com/facebook/jest/commit/94852b1c4003cb45702dba6a4d94cde88e3e9815) that seems to add `.only` support for Jest, but it's was dome after 15.1.1 release and is just not released yet. I'm guessing the Jest docs are just published ahead of time, but the most puzzling thing is that you said it the CLI works for you, have no idea how what's going on there.

**Comment by okonet** [comment]
I guess, but might be the master version that I'm using. Need to check then I get back to my computer.

**Comment by ArtemGovorov** [comment]
> but might be the master version that I'm using

Not sure, but sounds unlikely, because if I apply [that commit from master](https://github.com/facebook/jest/commit/94852b1c4003cb45702dba6a4d94cde88e3e9815), specifically the line `environment.global.it.only = environment.global.fit;`, to my locally installed jest (`jest-jasmine2`) module, both the CLI and wallaby.js just start working for me. While with the current version none of them works for me.

**Comment by okonet** [comment]
It might be that my CLI uses globally symlinked master version and wallaby uses the local one. I'll need to clean up my env and let you know.

**Comment by ArtemGovorov** [comment]
> my CLI uses globally symlinked master version and wallaby uses the local one

This definitely sounds like something that can cause the issue. Wallaby is currently always using the local one.
