### ISSUE TITLE
TypeError: Cannot read property 'querySelector' of undefined (react, aphrodite, jest)

### ISSUE THREAD

**Issue by giraud** [wallabyjs/public#808]
### Issue description or question

I got an error with wallaby and test workers.
I'm using react and aphrodite for inline styles.

I'm trying to switch to the jest test runner, and use jsdom instead of phantomjs. I added jest as a dependency and when I run it in the console (with a script that run "jest --watch") everything is working fine.

Now if I launch the wallaby configuration, I qot the following errors:
```
TypeError: Cannot read property 'querySelector' of undefined
	    at injectStyleTag (<rootdir>\node_modules\aphrodite\lib\inject.js:31:28)
	    at flushToStyleTag (<rootdir>\node_modules\aphrodite\lib\inject.js:184:9)
	    at RawTask.call (<rootdir>\node_modules\asap\asap.js:40:19)
	    at flush (<rootdir>\node_modules\asap\raw.js:50:29)
	    at nextTickCallbackWith0Args (node.js:420:9)
	    at Immediate._tickCallback [as _onImmediate] (node.js:349:13)
	    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

If I go to the failing test and touch the file (just change a comment), then the test pass.

### Wallaby.js configuration file

```javascript
module.exports = wallaby => ({
        files: [
            'src/**/*.js',
            '!src/**/*-spec.js'
        ],

        tests: [
            'src/**/*-spec.js'
        ],

        env: {
            type:   'node',
            runner: 'node',
        },
        testFramework: 'jest',

        compilers: {
            'src/**/*.js': wallaby.compilers.babel()
        }
})
```
 I tried adding a setup, but it had no impact 
```javascript
setup: function() {
    var jsdom = require('jsdom');
    global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
    global.window = document.defaultView;
    global.navigator = global.window.navigator;
}
```

I also tried to delay the start of the tests in setup, but had no luck
Same if I use only one worker.
I don't know what's different with the command line. What else could I do ? 

### Code editor or IDE name and version

IntelliJ IDEA 2016.1.2

### OS name and version

Windows
jest 15.1.1

**Comment by ArtemGovorov** [comment]
Could you please share a small sample project where I could reproduce the issue? Or if it is easily reproducible, please share your `package.json` and a test file and I'll try to create the project myself.

**Comment by ArtemGovorov** [comment]
I have put together a small sample and was able to reproduce they issue.
However, it doesn't look like it is wallaby.js specific issue, as the same issue shows up for me when running `jest` CLI command as well:

```
$ ./node_modules/.bin/jest 
 PASS  src/__tests__/a-spec.js
  ✓ test (18ms)

Test Summary
 › Ran all tests.
 › 1 test passed (1 total in 1 test suite, 1 snapshot, run time 1.341s)

<rootdir>/node_modules/aphrodite/lib/inject.js:32
        styleTag = document.querySelector("style[data-aphrodite]");
                           ^
TypeError: Cannot read property 'querySelector' of undefined
    at injectStyleTag (<rootdir>/node_modules/aphrodite/lib/inject.js:32:28)
    at flushToStyleTag (<rootdir>/node_modules/aphrodite/lib/inject.js:185:9)
    at RawTask.Object.<anonymous>.RawTask.call (<rootdir>/node_modules/asap/asap.js:40:19)
    at flush (<rootdir>/node_modules/asap/raw.js:51:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I have done some investigation, and here's what's going on: [`aphrodite` is doing some async work](https://github.com/Khan/aphrodite#style-injection-and-buffering), that is triggered *after*  a sync test ends.

Here's what you can do to just get rid of the error:
- add a [`setupFiles` setting to `jest`](http://facebook.github.io/jest/docs/configuration.html#setupfiles-array) (scripts to be executed in `jest` environment right before tests),
- to avoid creating any new files, you may use wallaby.js file itself as the setup file, so need to add it to the `files` list,
- add some code that gets executed in `jest` environment and ignores the async request from `aphrodite`.

Here's how your config may look like:

```javascript
module.exports = wallaby => ({
    files: [
        'src/**/*.js',
        '!src/**/*-spec.js',
        {pattern: 'wallaby.js', instrument: false}
    ],

    tests: [
        'src/**/*-spec.js'
    ],

    env: {
        type: 'node',
        runner: 'node',
    },
    testFramework: 'jest',

    compilers: {
        'src/**/*.js': wallaby.compilers.babel()
    },

    setup: (wallaby) => {
        wallaby.testFramework.configure({
            setupFiles: ['wallaby.js']
        });
    }
});

if (global.document) {
    var originalProcessNextTick = process.nextTick;
    process.nextTick = function (cb) {
        if (cb.toString().indexOf('function flush()') === 0) return;
        return originalProcessNextTick.apply(this, arguments);
    }
}
```

Let me know if this fixes the issue for you.

**Comment by giraud** [comment]
It totally fixed my issue.
Thank you so much for your work.
