### ISSUE TITLE
Filter tests by tag?

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#809]
Hi, in Mocha it is possible to filter tests by @tag

Is it possible to have this working in Wallaby?

**Comment by ArtemGovorov** [comment]
Hi,

If you mean [this mocha feature](https://github.com/mochajs/mocha/wiki/Tagging), then yes, you can just use [the `setup` function](https://wallabyjs.com/docs/config/bootstrap.html#setup-function) to access mocha object and set this setting (or any other mocha settings).

```javascript
module.exports = function () {
  return {
    ...
    setup: function(wallaby) {
      wallaby.testFramework.grep('@fast');
    }
};
```

This will make mocha (wallaby) only execute tests with the `@fast` tag:
```
it('some test @fast', () => {...});
```

The config like this will execute all BUT `@slow` tests.
```javascript
module.exports = function () {
  return {
    ...
    setup: function(wallaby) {
      wallaby.testFramework.grep('@slow');
      wallaby.testFramework.invert();
    }
};
```
