### ISSUE TITLE
console.log truncated in VSCode

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#813]
### Issue description or question

The output from `console.log(...)` is truncated, eg.

![image](https://cloud.githubusercontent.com/assets/3692873/19081127/1ba17cb2-8a51-11e6-9855-cdee4b642b10.png)

This makes it difficult to see what's going on when I'm trying to debug things.

Is there a setting that I can change to make it show the full output, or is this a bug?

### Code editor or IDE name and version

Visual Studio Code 1.5.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
It is truncated by design for the inline view.
To view the full multiline output you may use the "Show line tests" action:

![vsc](https://cloud.githubusercontent.com/assets/979966/19098361/fb700e46-8aef-11e6-88c1-a72a9458bf2a.gif)

(the output there is still truncated, but only if it exceeds 16kb of text)

**Comment by breathe** [comment]
@ArtemGovorov Is there a way to see output that exceeds 16kb of text?

**Comment by smcenlly** [comment]
Previously this was a hard coded setting, but we have just updated wallaby to make this configurable. From our [updated docs](https://wallabyjs.com/docs/config/overview.html#maximum-log-entry-size):

By default, wallaby.js truncates logged messages that exceed 16,384 characters in length. You may change the maximum number of characters using the maxLogEntrySize setting:

```javascript
  module.exports = function () {
    return {
      ...
      maxLogEntrySize: 32768
    };
  };
```
