### ISSUE TITLE
Code coverage report (static wallaby app build)

### ISSUE THREAD

**Issue by tamascsaba** [wallabyjs/public#815]
In this issue started a conversation https://github.com/wallabyjs/public/issues/675 and I really interested about this comment https://github.com/wallabyjs/public/issues/675#issuecomment-239351139 to open source wallaby app.

If it is not possible, I think good idea to generate static code coverage report  after test runs.

**Comment by smcenlly** [comment]
Closing this issue as we currently have no plans to implement this feature request.
