### ISSUE TITLE
Support jest 16.0.0

### ISSUE THREAD

**Issue by AliensFromMars** [wallabyjs/public#817]
### Issue description or question
I'm experiencing the problem where it says none of my tests are being ran even though the debug log states otherwise. I'm assuming that it's because the latest major update to jest changed the way test results were returned back. It works just fine with 15.1.1.

### Code editor or IDE name and version
WebStorm v2016.2.3

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Jest v16.0.1 support has just landed in wallaby.js core 1.0.300. The core will be updated automatically, alternatively you may restart your IDE and start wallaby to get the update ASAP.
