### ISSUE TITLE
Requiring Sass via TypeScript without Webpack

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#818]
### Issue description or question

I am using TypeScript to write my code, and have added some `require()` statements to bring in some Sass files that will eventually be compiled into a bundle using Webpack. My tests however are written using Node and jsdom so that I don't have to build in any preprocessing other than transpiling my TypeScript to ES5.

The problem I'm having is that I get errors like:

![image](https://cloud.githubusercontent.com/assets/3692873/19159705/58e60b70-8be5-11e6-9060-8273de839911.png)

Is there any way in which I can continue to use my current setup of Node/jsdom to run my tests, but at the same time get rid of errors like this? I really don't want to have to add Webpack to my testing process.

Thanks.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    var typescriptOptions = {
        module: 'commonjs',
        target: 'es5',
        jsx: 'react',
        experimentalDecorators: true,
        transpileOnly: true,
    };

    return {
        files: [
            { pattern: 'scripts/**/src/**/*.ts', load: false },
            { pattern: 'scripts/**/src/**/*.tsx', load: false },
        ],

        tests: [
            { pattern: 'scripts/**/tests/**/*.spec.ts' },
            { pattern: 'scripts/**/tests/**/*.spec.tsx' },
        ],

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript(typescriptOptions),
            '**/*.tsx': wallaby.compilers.typeScript(typescriptOptions),
        },

        testFramework: 'mocha',

        setup: function (wallaby) {
            require('jsdom-global')();
        },

        env: {
            type: 'node',
            runner: 'node',
        },
    };
};
```

### Code editor or IDE name and version

VSCode 1.5.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
The issue is not wallaby.js specific and the solution I have seen people using for both plain mocha and wallaby is to just configure node to load nothing for the extension:

```javascript
setup: function (wallaby) {
            require.extensions['.scss'] = () => {};
            require('jsdom-global')();
        },
```

However, it will not work for you because node will still try to look up the provided path and you're using inline loaders (`!style!css...`) that makes it an invalid path for node. So you need to intercept node `require` function earlier and just return early for `.scss` files:

```javascript
setup: function (wallaby) {

            var path = require('path');
            var modulePrototype = require('module').Module.prototype;
            if (!modulePrototype._originalRequire) {
              modulePrototype._originalRequire = modulePrototype.require;
              modulePrototype.require = function (filePath) {
                if (~filePath.indexOf('.scss')) return {};
                return modulePrototype._originalRequire.call(this, filePath);
              };
            }

            require('jsdom-global')();
        },
```

**Comment by dylanparry** [comment]
Perfect, thanks :)
