### ISSUE TITLE
Run typescript based test via jest

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#819]
### Issue description or question
I was able to setup test specs written in typescript with jest test runner, but experiencing wallaby does not point to original test spec (.ts) - not sure what configuration I may additionally need to this working.

### Wallaby.js configuration file
reproducible repo is at https://github.com/kwonoj/jest_ts_wallaby
`npm install` -> run wallaby, open up output panel and it shows `console.log:  PASS  spec/sum-spec.js`

![screen shot 2016-10-07 at 14 03 56](https://cloud.githubusercontent.com/assets/1210596/19205368/ec11ed7c-8c96-11e6-8474-39c443e78d6f.png)

wallaby 1.0.28 / core 1.0.301

### Code editor or IDE name and version

Visual Studio Code 1.5.3

### OS name and version

OSX 10.11.6

**Comment by kwonoj** [comment]
Problem here is wallaby does not list / navigate test properly, i.e click test status in status bar, it doesn't do anything.

**Comment by ArtemGovorov** [comment]
I have checked out the repo, but can't reproduce any of these issues: 

> experiencing wallaby does not point to original test spec (.ts)

> wallaby does not list / navigate test properly

Here's what I do:

![vsc](https://cloud.githubusercontent.com/assets/979966/19211650/d670159a-8d84-11e6-87e4-b3c639fcc877.gif)

What am I missing?

**Comment by kwonoj** [comment]
huh, weird. Let me try on my end again.

**Comment by kwonoj** [comment]
Weird, it seems working, don't know what happened. :/ Let me close this issue, and appreciate for help.
