### ISSUE TITLE
Wallaby.js App: Source code highlighting

### ISSUE THREAD

**Issue by dylanparry** [wallabyjs/public#826]
### Issue description or question

The source code highlighting in the Wallaby.js App does not work for TSX files. These should be marked as Typescript files in order for the colouring to work correctly. It works for regular TS files, just not TSX.

TS files look like:

![image](https://cloud.githubusercontent.com/assets/3692873/19348356/70893b70-9145-11e6-9487-a5680796c110.png)

but TSX files don't get any love:

![image](https://cloud.githubusercontent.com/assets/3692873/19348366/7c8104e4-9145-11e6-9ef9-111032c5791a.png)

**Comment by ArtemGovorov** [comment]
Done, published in Wallaby App 1.0.13.

**Comment by dylanparry** [comment]
Excellent service, as always :) Thanks.
