### ISSUE TITLE
No failing tests, 0 passing Angular2 & Webpack

### ISSUE THREAD

**Issue by ryandegruyter** [wallabyjs/public#831]
### Issue description or question
I'm trying to setup wallaby with this repo:
https://github.com/qdouble/angular-webpack2-starter

I've followed the config as described in the following repo: 
https://github.com/wallabyjs/angular2-webpack-starter/

All ts code show gray boxes, f.e.:
![image](https://cloud.githubusercontent.com/assets/12190633/19411713/0eda4bf8-9307-11e6-8018-1a154d67d42f.png)

But only spec-bundle.js has green boxes:
![image](https://cloud.githubusercontent.com/assets/12190633/19411724/2924d7f8-9307-11e6-9a51-d8e5df254791.png)

output:
![image](https://cloud.githubusercontent.com/assets/12190633/19411763/c8284312-9307-11e6-98dd-2632950d246d.png)

My folder structure is:

/Project
---/folderA
---/folderB
---/angular2starter
------/src
------/test-config
------wallaby.js

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'test-config/spec-bundle.js',
        'src/**/*spec.js'
    ],

    module: {
        loaders: [
            {test: /\.css$/, loader: 'raw-loader'},
            {test: /\.html$/, loader: 'raw-loader'},
            {test: /karma-require/, loader: 'null'}
        ]
    }
});

module.exports = function () {

    return {
        files: [
            {pattern: 'test-config/spec-bundle.js', load: false},
            {pattern: 'test-config/karma-require.js', load: false},
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'src/**/*.css', load: false},
            {pattern: 'src/**/*.html', load: false},
            {pattern: 'src/**/*spec.ts', ignore: true},
            {pattern: 'src/**/*.d.ts', ignore: true}
        ],

        tests: [
            {pattern: 'src/**/*spec.ts', load: false},
            {pattern: 'test/**/*spec.ts', load: false}
        ],

        testFramework: 'jasmine',

        env: {
            runner: require('phantomjs-prebuilt').path,
            params: { runner: '--web-security=false' }
        },

        postprocessor: webpackPostprocessor,

        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

### Code editor or IDE name and version
IntelliJ IDEA v15

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo.
Wallaby.js has legacy support fro prev versions of TypeScript and because of that it requires the `module` option to be set in the `tsconfig.json` compiler options:
Try adding
```
{
  "compilerOptions": {
    "module": "commonjs",
    ...
```
to your tsconfig.json. It won't change anything in your prod build. Please let me know if this helps and resolves the issue.

**Comment by ArtemGovorov** [comment]
BTW, we will be changing the behaviour soon so that no changes to the `tsconfig.json` will be required by default. For now if you don't like to touch the file, you may specify the module setting right in wallaby config: https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings

**Comment by ryandegruyter** [comment]
Awesome, it's working, thanks for the quick support!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
