### ISSUE TITLE
CLI SCSS issue

### ISSUE THREAD

**Issue by ajrauen** [wallabyjs/public#836]
### Issue description or question
When trying to run a spec, I get the following
​​​​​[Info]​​​​​ Tue, 18 Oct 2016 16:54:13 GMT wallaby:workers Sandbox (active) [gmdo6] error: Error: Cannot find module "./collapse-panel.component.scss"
​​[Error] Runtime error: Error: Cannot find module "./collapse-panel.component.scss"​​
​​[Error] at http://localhost:63606/src/app/modules/nokia/collapse-panel/collapse-panel.component.js.545.wbp.js?1476809649819&wallabyFileId=41:85​​
​​​​​[Info]​​​​​ Tue, 18 Oct 2016 16:54:13 GMT wallaby:workers Sandbox (active) [gmdo6] error: Error: Cannot find module "./collapse-panel.component.scss"
​​[Error] Runtime error: Error: Cannot find module "./collapse-panel.component.scss"​​

### Wallaby.js configuration file

```
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
   ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: {runner: '--web-security=false'}
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },



    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Looks like `.scss` files are not included in the wallaby `files` list, hence the error. Try adding:
```javascript
{pattern: 'src/**/*.scss', load: false},
```
to your `files` list.
