### ISSUE TITLE
Avoid separate config file

### ISSUE THREAD

**Issue by kdalgaard** [wallabyjs/public#837]
I am hesitant to add a `wallaby.js` config file at the root of my project, since Wallaby isn't technically a dependency of the project and the extra file is simply clutter for developers not using it.

Would it be possible to add a `"wallaby"` section to `package.json` instead?

**Comment by ArtemGovorov** [comment]
I suppose we could add the support for `wallaby` section is the `package.json`. However, wallaby.js is a javascript file, and in many cases it contains some code, so expressing it (as a string?) in the `package.json` may not be an option for many users.

**Comment by kdalgaard** [comment]
Good point. I wonder whether it would create too much incoherence to have the choice between a `wallaby.json` (JSON) file and a `"wallaby"` section in `package.json`...

**Comment by kdalgaard** [comment]
Which is more prevalent in your user base, a dynamic or a static config?

**Comment by ArtemGovorov** [comment]
@kdalgaard Most of the config files we see contain code. Only simple scenarios need just a list of `files`/`tests`, but (almost) everyone these days need one or a combo of these: [webpack](https://wallabyjs.com/docs/integration/webpack.html)/[browserify](https://wallabyjs.com/docs/integration/browserify.html), [some setup code](https://wallabyjs.com/docs/config/bootstrap.html), [system.js](https://wallabyjs.com/docs/integration/systemjs.html), [babel](https://wallabyjs.com/docs/integration/es-next.html), [jspm](https://wallabyjs.com/docs/integration/jspm.html), etc, where some (simple, but still) code configuration is required.

**Comment by kdalgaard** [comment]
Fair point.
