### ISSUE TITLE
Webpack jasmine-matchers - how to load so Wallaby sees it?

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#838]
## Question

Using webpack. Loading jasmine with jasmine-matchers. Karma-conf like this:

    module.exports = function (config) {
      config.set({
        basePath: __dirname,
        frameworks: ['jasmine', 'jasmine-matchers', 'sinon'],

I manged to get sinon loading OK when running wallaby - thanks to this ticket:  https://github.com/wallabyjs/public/issues/821 - thanks for that.

Now getting problems when trying to use jasmine matchers.  Not sure how to proceed.  The approach of adding the files to the array:

      files: [
        {pattern: 'node_modules/karma-jasmine-matchers/index.js', load: false},
        {pattern: 'test/unit/setup.js', load: false},
        {pattern: 'src/**/*.js', load: false}
      ],

in the wallaby.js does not work - get error: 

	TypeError: undefined is not a function (evaluating 'expect(true).toBeTrue()')

in a simple test like this: 

  it('matchers exist', () => {
    expect(true).toBeTrue();  // toBeTrue() is from matchers 
  });

The above test works OK when running from 'npm karma start test' task.

**Comment by ArtemGovorov** [comment]
if you'd like the file to be loaded globally (without having to `import` it from your tests or tests setup file, like with your karma config), then you'll [need to set the `load: true` flag](https://wallabyjs.com/docs/config/files.html#file-object) (and ideally `instrument: false` flag to avoid the library instrumentation).

Also you'll need to load the correct file. If you look into the `node_modules/karma-jasmine-matchers/index.js`, you'll discover that it's just a karma plugin that loads the `jasmine-expect` module internally, so to load the library you'll need:
```javascript
{pattern: 'node_modules/jasmine-expect/dist/jasmine-matchers.js', load: true, instrument: false},
```

**Comment by vipirain** [comment]
But how can I achieve it with automatic configuration?

**Comment by ArtemGovorov** [comment]
@vipirain Can you please create a new issue and share your Wallaby Diagnostics report as described in the new issue template?

**Comment by tomitrescak** [comment]
Sorry to revive old thread but this does not work for me. This is my config:

```js
// @ts-nocheck
// eslint-disable-next-line @typescript-eslint/no-var-requires

module.exports = function (wallaby) {
  var path = require('path');

  // support for baseurl
  process.env.NODE_PATH += path.delimiter + path.join(wallaby.projectCacheDir, 'src');

  return {
    files: [
      {
        pattern: 'src/lib/extendExpect.ts',
        instrument: false,
        load: true
      },
      { pattern: 'src/**/*.ts' },
      { pattern: '!src/**/*.test.ts' }
    ],
    tests: ['src/**/*.test.ts'],
    env: {
      type: 'node',
      NODE_ENV: 'test'
    },
    testFramework: 'mocha'
  };
};
```

The extendExpect file is not loaded

**Comment by tomitrescak** [comment]
Going to create a new issue
