### ISSUE TITLE
Angular2 issue with the TestBed dependency injection. Can't resolve all parameters. 

### ISSUE THREAD

**Issue by vespertilian** [wallabyjs/public#839]
### Issue description or question

I get an error when running the tests for a component that requires services that are mocked via TestBed.configure testing module. Specifically it's one of the sub components that does not know were to get it's dependencies from. 

These test pass when using the karma runner. 

I have setup a sample for you based on the Angular2-Webpack-Starter that replicates my issue. 

https://github.com/Benefex/angular2-webpack-starter/tree/wallaby_failure
**branch: wallaby_failure**

The issue is Title needs http, but does not know it needs to get it from the TestBed config block. 

**error**
```
Error: Can't resolve all parameters for Title: (?).
```

**component**
```js
export class Home {
  // Set our default values
  localState = { value: '' };
  // TypeScript public modifiers
  constructor(public appState: AppState, public title: Title) {

  }
...
```

**test setup**
```js
...
  beforeEach(() => TestBed.configureTestingModule({
    providers: [
      BaseRequestOptions,
      MockBackend,
      {
        provide: Http,
        useFactory: function(backend: ConnectionBackend, defaultOptions: BaseRequestOptions) {
          return new Http(backend, defaultOptions);
        },
        deps: [MockBackend, BaseRequestOptions]
      },
      AppState,
      Title,
      Home
    ]
  }));
...
```

**title service**
```js
@Injectable()
export class Title {
  value = 'Angular 2';
  constructor(public http: Http) {

  }
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /karma-require/, loader: 'null'},
      {test: /\.jade$/, loader: 'pug-html-loader'},
      {test: /\.(scss|sass)$/, loaders: ['raw', 'sass']}, // <--like in webpack.test.js
      {test: /\.json$/, loader: 'json-loader'},
    ]
  }
});

module.exports = function () {

  return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'config/karma-require.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.jade', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      // {pattern: 'src/**/*.d.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: { runner: '--web-security=false' }
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
I think I have seen the issue when was setting up wallaby.js for [earlier in one of your other issues](https://github.com/wallabyjs/public/issues/812#issuecomment-251289441). The issue was caused by including `*.d.ts` files and in my pull request I have excluded them, but looks like you've [commented out the exclusion](https://github.com/Benefex/angular2-webpack-starter/commit/fc852c0be42e22fd8c8e76cc552f58bbca0f495a#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecL35). If I uncomment my change, it works for me. Any specific reason you've commented it out?

**Comment by vespertilian** [comment]
Yep that was the issue. I have no idea when / how I copied over the config, I was still struggling with Sass because of the way we had referenced the files (which I worked out). Thanks so much. It's all working now and it's lots faster than Karma.

**Comment by Barryrowe** [comment]
@ArtemGovorov You have saved me so much time over the last year with how you dig into so many specific issues...Thanks for all the great work.

For anyone else that might hit this, I came across this when racking my brain trying to apply a working configuration from an Ionic 2 rc.4 application to an Ionic 2 final app.  Karma was working but could NOT figure out why the dependency injector was failing for a test with defined providers...

Turns out in the latest Ionic 2 template, they provide a declarations.d.ts file at the root that caused this same issue...

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the notes Barry!

**Comment by mattmutt** [comment]
I know this is an older issue, but I am faced with the dilemma that my project's TypeScript code does need to `import` some interface declarations files `*.d.ts`. The build always compiled fine, but with WallabyJS the recommended config has `*.d.ts` file purposely removed. Now Adding it back in is a bad move because I'll get the `Error: Can't resolve all parameters for <ClassName>: (?).` and keeping the `*.d.ts` files filtered out causes them to not be referenced and I get errors. Is it correct in the first place reference these `*.d.ts` files from code. Syntactically it is correct.

**Comment by ArtemGovorov** [comment]
@mattmutt We have made some changes to support your scenario. You may update wallaby.js core to [the latest version 1.0.472](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) (if it hasn't done it automatically yet). 

So In the latest release it's possible to not remove `*.d.ts` files (so that you may comment out their exclusion in your `files` list) and [use the `useStandardDefaults` setting for a full TS compilation](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) (that will take `.*.d.ts` files into account).

```javascript
module.exports = function () {

  return {
    files: [
      ...
      // {pattern: 'src/**/*.d.ts', ignore: true}
    ],
    ...
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({ useStandardDefaults: true })
    },
    ...
  };
};
```

**Comment by saurabh-lath** [comment]
I am facing exactly the same issue. My tests are passing with karma, but fails with Wallaby.

Error: Can’t resolve all parameters for MyComponent: (?)

I am testing a component which includes a sub component (MyComponent) from another module.
I have checked my wallaby config, it already excludes “*.d.ts”

`return {
    files: [
      {pattern: 'src/**/*.ts', load: false, instrument: true},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false, instrument: true},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ]`

Any Ideas?

**Comment by ArtemGovorov** [comment]
@saurabh-lath May I see your full wallaby config? Also, where is your `tsconfig.json` file located, what's its name and what is in it?

**Comment by saurabh-lath** [comment]
@ArtemGovorov thanks for your reply. 

my tsconfig.json is in myproject folder which is in root folder along with wallaby config.

tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "../../assets/dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "../../node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```
Wallaby Config:

```
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('.myproject/tsconfig.json').compilerOptions,
  require('./myproject/src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {
  wallaby.defaults.files.instrument = false;
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [      
      'myproject/src/wallabyTest.js',
      'myproject/src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'myproject/src/app'),
        path.join(wallaby.projectCacheDir, 'myproject/src'),
        'node_modules'
      ]
    }
  });

  return {
    files: [
      {pattern: 'myproject/src/**/*.ts', load: false, instrument: true},
      {pattern: 'myproject/src/**/*.d.ts', ignore: true},
      {pattern: 'myproject/src/**/*.css', load: false},
      {pattern: 'myproject/src/**/*.less', load: false},
      {pattern: 'myproject/src/**/*.scss', load: false},
      {pattern: 'myproject/src/**/*.sass', load: false},
      {pattern: 'myproject/src/**/*.styl', load: false},
      {pattern: 'myproject/src/**/*.html', load: false, instrument: true},
      {pattern: 'myproject/src/**/*.json', load: false},
      {pattern: 'myproject/src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'myproject/src/**/*spec.ts', load: false, instrument: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },
    
    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'myproject/src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'myproject/src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

Please also note that all my other tests on other components are passing no problem.

**Comment by ArtemGovorov** [comment]
@saurabh-lath Try changing your config like this:

```diff
var compilerOptions = Object.assign(
  require('.myproject/tsconfig.json').compilerOptions,
  require('./myproject/src/tsconfig.spec.json').compilerOptions);

+compilerOptions.useStandardDefaults = true;
...

  return {
    files: [
      {pattern: 'myproject/src/**/*.ts', load: false, instrument: true},
-     {pattern: 'myproject/src/**/*.d.ts', ignore: true},
```

If it doesn't help, please create and share a sample repo demonstrating the issue. Hopefully it shouldn't be too hard to isolate given that it is only one test/component and you can easily reproduce the issue.

**Comment by saurabh-lath** [comment]
@ArtemGovorov  unfortunately that solution did not work. I will create a sample repo demonstrating this issue. Thanks for your help.
