### ISSUE TITLE
Dependencies fail to install

### ISSUE THREAD

**Issue by johannesjo** [wallabyjs/public#84]
Somehow the node dependencies failed to install. Unfortunately I don't remember which. Could you provide a dependency list so that I can uninstall them and try again?

**Comment by ArtemGovorov** [comment]
Try uninstalling the plugin (Settings - Plugins - Wallaby.js - Uninstall plugin), removing [dependency cache folder](https://github.com/wallabyjs/public/issues/32#issuecomment-77309111) and installing the plugin again. Let me know if it helps.

**Comment by johannesjo** [comment]
Thanks. That worked!
