### ISSUE TITLE
Visual Studio 2015 error on start up

### ISSUE THREAD

**Issue by mikeyjones** [wallabyjs/public#842]
After installing wallaby for Visual Studio 2015, when I start up Visual Studio I get an error loading the extension.

I am running on Windows 10 Anniversary, with Visual Studio 2015 Update 3

Here is the printout of the error VS gives me:
```
  <entry>
    <record>132</record>
    <time>2016/10/22 22:20:19.235</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [WallabyPackage]</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
  </entry>
  <entry>
    <record>133</record>
    <time>2016/10/22 22:20:19.253</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [WallabyPackage]Source: &apos;Wallaby.VisualStudio.Vsix&apos; Description: Could not load type &apos;Clide.Diagnostics.Tracer&apos; from assembly &apos;Clide, Version=2.5.0.0, Culture=neutral, PublicKeyToken=5b91f4c51d49ec0c&apos;.&#x000D;&#x000A;System.TypeLoadException: Could not load type &apos;Clide.Diagnostics.Tracer&apos; from assembly &apos;Clide, Version=2.5.0.0, Culture=neutral, PublicKeyToken=5b91f4c51d49ec0c&apos;.&#x000D;&#x000A;   at Wallaby.VisualStudio.Vsix.WallabyPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>134</record>
    <time>2016/10/22 22:20:19.275</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WallabyPackage](null)</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>135</record>
    <time>2016/10/22 22:20:19.277</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [WallabyPackage]</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
```

Any ideas on how I can fix this?

### Code editor or IDE name and version

Visual Studio 2015

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
The most likely reason is that wallaby.js extension dependency conflict with some other extension that you have installed. Could you please list other VS extensions you have installed?

**Comment by mikeyjones** [comment]
Sure, I seem to have a lot, most of them have come from installing Xamarin and Web Essentials.

* Add New File (3.5.113)[Web Essential]
* Azure AD Authentication Connected Service (1.1.63009.34349)
* Azure DataLake Tools for Visual Studio (2.1.0.0)
* Browser Reload on Save (1.0.17)[Web Essential]
* Browser Sync (1.2.22)[Web Essential]
* Bundler & Minifier (2.1.279)[Web Essential]
* Clang with Microsoft CodeGen (14.0.25516.0)
* Cloud Explorer for Visual Studio 2015 (1.0.60930.4)
* Command Bus, Event Stream and Async Manager (1.0.28)
* Developer Analytics Tools (7.10.1020.1)
* Editor Enhancements (1.0.24)[Web Essential]
* Enable XAML Language for Xamarin.Forms (1.2)
* File Icons (1.7.61)[Web Essential]
* File Nesting(2.5.63)[Web Essential]
* Get Xamarin (1.0.0.0)
* Glyphfriend (1.5.2.0)[Web Essential I think]
* HTML Snippet Pack (1.0.5)[Web Essential]
* Image Optimiser (3.6.94)[Web Essential]
* Image Sprites (1.4.45)[Web Essential]
* Javascript Snippet Pack (1.2.14)[Web Essential]
* Markdown Editor (1.9.173)[Web Essential]
* Microsoft .NET Core Tools (14.1.20907.0)
* Microsoft ASP.NET and Web Tools (14.1.20907.0)
* Mircosoft ASP.NET Web Frameworks and Tools (5.2.40314.0)
* Microsoft Azure App Service Tools (14.0.20810.0)
* Microsoft Azure Mobile Services Connected Service  (2.0.63009.34349)
* Microsoft Azure Quickstarts
* Microsoft Azure Storage Connected Service
* Microsoft Connected Services
* Microsoft Office 365 API Tools
* Microsoft Visual C++ Cross Platform Mobile Development (iOS)
* MySQL for Visual Studio (1.2.6)
* Nuget Package Manager for Visual Studio 2015 (3.5.0.1484)
* Open Command Line (2.1.176)[Web Essential]
* Package Installer (1.8.87)[Web Essential]
* Prism Template Pack (1.6)[Web Essential]
* Suggested Extensions (1.1.76)[Web Essential]
* Typescript for Microsoft Visual Studio (2.0.3.0)
* Visual Studio Emulator for Android (1.1.622.2)
* Visual Studio Extension for TextMate Grammars (1.1.60520.2)
* Visual Studio Extensions for Windows Library for Javascript (1.0.9651.40228)
* Visual Studio Tools for Apache Cordova (14.0.60527.5)
* Wallby.js for Visual Studio 2015 (1.0.25)
* Web Accessibility Checker (1.3.33)
* Web Compiler (1.11.319)[Web Essential]
* Web Essentials 2015.3 (3.0.235)[Web Essential]
* Web Extension Pack (1.6.52)[Web Essential]
* Xamarin for Visual Studio (4.2.703)
* Xamarin.Forms Templates (0.5.54)
* XAML Styler (2.2)

Thats everything I have installed. I disabled all the extensions I could and the error still happened, so I might need to uninstall them to test this properly.

Thanks for the fast feedback

Mike

**Comment by ArtemGovorov** [comment]
Thanks for the extension list! We have found the issue (conflict with one of Xamarin extensions) and are working on the fix. We'll be publishing it later today, I'll let you know once the update is available.

**Comment by shrikantWipro** [comment]
Even i am facing the same issue. Its all working fine with VS2013 its a problem with only 2015.
Following are the visual extensions on my machine.

- Command Bus ,Event Stream  [1.0.28]
- Get Xamarin   [[1.0.0.0]]   -- Xamarin
- NCrunch for Visual studio  [[2.27.03]]  --  Remco software Ltd.
- TypeScript for Microsoft visual studio  [[1.8.36.0]] --  Microsoft
- Visual studio Extension for Textmate Grammer  [[1.1.60520.2]] --  Microsoft
- Visual Studio Extension for windows Library for JavaScript   [[1.0.9651.40228]] --  Microsoft
- Wallaby.js for visual studio 2015  [[1.0.25]]  --  Wallby.js
- Xamarin for Visual studio    [[4.2.703]]  --   Xamarin
- Xamarin.Forms Templates   [[0.5.54]]   --    Xamarin


# Code editor or IDE name and version
Visual Studio 2015 Update 3


# OS name and version
Windows

## Screen Shot.
![loadissue1](https://cloud.githubusercontent.com/assets/23029088/19642842/d2569e5c-9a04-11e6-99ba-7bfde55dd947.jpg)

### Error log.

`<entry>
    <record>603</record>
    <time>2016/10/24 09:24:57.168</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [WallabyPackage]</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
  </entry>
  <entry>
    <record>604</record>
    <time>2016/10/24 09:24:57.169</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [WallabyPackage]Source: &apos;Wallaby.VisualStudio.Vsix&apos; Description: Could not load type &apos;Clide.Diagnostics.Tracer&apos; from assembly &apos;Clide, Version=2.5.0.0, Culture=neutral, PublicKeyToken=5b91f4c51d49ec0c&apos;.&#x000D;&#x000A;System.TypeLoadException: Could not load type &apos;Clide.Diagnostics.Tracer&apos; from assembly &apos;Clide, Version=2.5.0.0, Culture=neutral, PublicKeyToken=5b91f4c51d49ec0c&apos;.&#x000D;&#x000A;   at Wallaby.VisualStudio.Vsix.WallabyPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>605</record>
    <time>2016/10/24 09:24:57.175</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [WallabyPackage](null)</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>606</record>
    <time>2016/10/24 09:24:57.180</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [WallabyPackage]</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
    <hr>80131522</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>607</record>
    <time>2016/10/24 09:24:57.184</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Package failed to load; error message suppressed by skip flag</description>
    <guid>{69DD754B-CB7C-4FE2-8508-55BF57E3381C}</guid>
  </entry>
  <entry>`

**Comment by ArtemGovorov** [comment]
We have found the issue (conflict with one of Xamarin extensions) and are working on the fix. We'll be publishing it later today, I'll let you know once the update is available.

**Comment by ArtemGovorov** [comment]
The fix is published in the wallaby extension v1.0.26. Please restart your IDE and wallaby.js will prompt to update the extension.

**Comment by mikeyjones** [comment]
Thanks for fixing this, I have restarted VS a couple of times and it has not updated wallaby. So I tried removing the old 1.0.25 version from VS, and installing the new 1.0.0.26, however, whichst VS is saying it is not installed, the VSIX installer says "This extension is not installable on any currently installed products". Seems like it is detecting the old version is still there, so will not install the new version. is there anything I can do to either force VS to update or install the newer version?

**Comment by ArtemGovorov** [comment]
> "This extension is not installable on any currently installed products"
Perhaps you're trying to install VS 2013 extensions version? Just in case, here the download link for VS 2015 extension version - http://download.wallabyjs.com/vs-2015

**Comment by mikeyjones** [comment]
oops, must have been, that link fixed it Thanks again for your support, great product!!!

**Comment by shrikantWipro** [comment]
Thanks! its all working fine now....:)
