### ISSUE TITLE
Getting Postprocessor run failure: .... SyntaxError: Unexpected token (66:52)​​ after reinstalling node_modules

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#844]
### Issue description or question

Hi, I have reinstalled my node_modules and now I'm getting " Postprocessor run failure: ....file.js, SyntaxError: Unexpected token (66:52)​​"

How can I debug why I'm getting the issue? My tests now won't run.

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (w) {
  return {
    files: [
      'app/shared/**/*.ts',
      { pattern: 'app/**/tests/*.ts', ignore: true }
    ],
    tests: [
      'app/shared/**/tests/*.ts'
    ],
    compilers: {
      "**/*.ts*": w.compilers.typeScript({module: "commonjs", target: "es5"})
    },
    env: {
      type: "node"
    },
    testFramework: "mocha",
    workers: {
       initial: 1,
       regular: 1
     },
    delays: {
      run: 100
    },
    setup: function(w) {
      // configure chai
      var sould = require('chai').should();

      // configure sinon
      var sinon = require('sinon');
      var sinonTest = require('sinon-test');

      sinon.test = sinonTest.configureTest(sinon);
      sinon.testCase = sinonTest.configureTestCase(sinon);

      // handle db
      global.workerId = w.workerId;
    },
    teardown: function (wallaby) {
      const connector = require('apollo-connector-mongodb');
      connector.disposeDb(true);
    }
  }; 
};
```

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

OSX

**Comment by tomitrescak** [comment]
It was the missing "typescript" in my node_modules. Wallaby is not picking up the global installation. Which is ok at least I know it would fail in CI.

**Comment by ArtemGovorov** [comment]
Cool, thanks for the update. Wallaby.js ships with an embedded TypeScript compiler 1.8.x that it's using if no local TypeScript version is found. Probably you're using some newer TS 2 syntax TS 1.8 compiler couldn't handle it.
