### ISSUE TITLE
CSS imports in React, with Jest

### ISSUE THREAD

**Issue by andreipfeiffer** [wallabyjs/public#849]
### Issue description or question

I can't figure out how to configure Wallaby to make the tests work with CSS imports.
I get this error message in wallaby console:

ModuleParseError: Module parse failed: ./src/editions/edition.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

I guess it's something to do with webpack loaders, but I can't find anything in wallaby docs regarding this, because I don't use any preprocessors or compilers.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    // webpack options

    externals: {
      // Use external version of React instead of rebuilding it
      "react": "React"
    },
    resolve: {
      extensions: ['', '.js', '.jsx']
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.js*', load: false},
      {pattern: 'src/**/*.spec.js*', ignore: true, load: false},
      {pattern: 'src/**/*.css', load: false, instrument: false},
      {pattern: 'package.json', load: false, instrument: false}
    ],

    tests: [
      {pattern: 'src/**/*.spec.js*', load: false},
      {pattern: 'src/**/*.snapshot*', ignore: true, load: false}
    ],

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

    postprocessor: webpackPostprocessor,

    setup: (wallaby) => {
      const jestConfig = require('./package.json').jest;
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

### webpack configuration file

```
const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

const APP_DIR = path.join(__dirname, 'src');
const BUILD_DIR = path.join(__dirname, 'dist');

module.exports = {
  devtool: 'eval',
  entry: {
    editions: APP_DIR + '/editions/index.js',
  },
  output: {
    path: BUILD_DIR,
    filename: '[name].bundle.js'
  },
  plugins: [
    new ExtractTextPlugin('[name].bundle.css', {
      allChunks: true
    }),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: ['babel'],
        include: APP_DIR
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
      }
    ]
  }
};
```

### Code editor or IDE name and version

Atom v1.11.2

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
What you pass to wallabyWebpack is [the webpack settings](https://wallabyjs.com/docs/integration/webpack.html#usage), so this
```javascript
  var webpackPostprocessor = wallabyWebpack({
    // webpack options
    module: {
      loaders: [
        {test: /\.css$/, loader: 'raw-loader'}
      ]
    },
    ...
  });
```
should work for you.

**Comment by andreipfeiffer** [comment]
Hey @ArtemGovorov,

I used the exact loaders I used in my webpack.config, without the ExtractTextPlugin:

```
{test: /\.css$/, loader: 'style-loader!css-loader'}
```

I don't get those errors anymore, but I have some other ones, which also appeared previously, and I thought they will get fixed if I can properly load the css files:

```
ReferenceError: Can't find variable: require

ReferenceError: Can't find variable: require
at http://localhost:53125/wallaby_sandbox0.html:10

ReferenceError: Can't find variable: require
at http://localhost:53125/wallaby_sandbox1.html:10

ReferenceError: Can't find variable: require
at http://localhost:53125/wallaby_sandbox2.html:10
```

I don't explicitly use require() anywhere in the files, so I have no idea where is this coming from.

**Comment by ArtemGovorov** [comment]
The error must be coming from your `setup` function:
```javascript
 setup: (wallaby) => {
      const jestConfig = require('./package.json').jest;
      wallaby.testFramework.configure(jestConfig);
    },
```
The code is executed in browser context (outside webpack), however you're trying to use `require` there, and also `jest` which only runs in node, not in browser. I'm not sure about your setup, but you can either [run tests in node](https://wallabyjs.com/docs/integration/node.html) and use `jest`, or run them in browser environment and use `webpack` and some browser supported testing framework, like mocha or jasmine. Wallaby doesn't support using webpack and node environment together.

If you're using `jest` for your tests, you don't need webpack at all. [Simple config should suffice](https://wallabyjs.com/docs/integration/jest.html), plus [configuring jest `moduleNameMapper `](https://facebook.github.io/jest/docs/tutorial-webpack.html) for your CSS files.

**Comment by andreipfeiffer** [comment]
Hey Artem,

I think I'm getting closer. I've cleaned up the wallaby config file:

* removed everything related to webpack
* copy pasted the jest config options so you can see them (they are pasted from their docs), 
* replaced the pattern method for files with simple strings

Now I get this error, still related to the CSS file.

```
/Users/andreipfeiffer/.atom/packages/atom-wallaby/projects/2e6f50dec7c545d2/instrumented/src/editions/edition.css:1

at src/editions/Edition.js:5:0
at src/editions/Edition.spec.js:10:0

Error: Your test suite must contain at least one test.
    at onResult (/Users/andreipfeiffer/work/mamp/timjs.ro/node_modules/jest-cli/build/TestRunner.js:189:18)
    at promise.then.then.result (/Users/andreipfeiffer/work/mamp/timjs.ro/node_modules/jest-cli/build/TestRunner.js:311:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Edition.js:5:0 is:
```
import './edition.css';
```

I've tried many combinations of wallaby config regarding css files: un/instrumented, loaded/not loaded, etc. Any configuration has the same result.

### wallaby config

```
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js*',
      '!src/**/*.spec.js*',
      {pattern: 'src/**/*.css', load: false, instrument: false}
    ],

    tests: [
      'src/**/*.spec.js*'
    ],

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    setup: (wallaby) => {
      wallaby.testFramework.configure({
        "moduleNameMapper": {
          "^.+\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__dummies__/fileDummy.js",
          "^.+\\.(css|less)$": "<rootDir>/__dummies__/styleDummy.js"
        },
        "moduleFileExtensions": ["js", "jsx", "json"],
        "moduleDirectories": ["node_modules", "src"]
      });
    },
  };
};
```

**Comment by ArtemGovorov** [comment]
Unfortunately `jest` doesn't provide enough info and just fails, but the reason is that it can't find the `__dummies__/styleDummy.js` file. Just add the fie to your `files` list and it should work (simple sample with your config works for me):
```javascript
files: [
      'src/**/*.js*',
      '__dummies__/**/*.js', // <---
      '!src/**/*.spec.js*',
      {pattern: 'src/**/*.css', load: false, instrument: false}
    ],
```

**Comment by andreipfeiffer** [comment]
You're right, because every file that should be handled by tests, needs to be specified in the files Array, right? Just like in karma. Didn't think of that.

Thank's very much @ArtemGovorov for your patience.
It's working now.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> because every file that should be handled by tests, needs to be specified in the files Array

Yes, it's correct.
