### ISSUE TITLE
 Mocha global suite `before` and `after` hooks are only called once per 'wallaby start'

### ISSUE THREAD

**Issue by geekflyer** [wallabyjs/public#850]
### Issue description or question

In mocha one can do a global setup and teardown that should be run once before and after any test via a `before` and `after` outside of any describe block. In my case I've defined this in a seperate dummy testfile which looks like that:

`test/envSetup.test.js` (it's part of test config path in wallaby)
```js
import {getUniqueSchemaName} from '../src/util';
import {createSchema, dropSchema} from '../src/db';
import {useConnectionP} from 'sap-hdb-addons-promise';

const credentials = require('./credentials.json');
const testSchema = getUniqueSchemaName();

before(() => {
  console.log('global setup');
  // setup schema for tests
  return useConnectionP(credentials, async client => {
    try {
      await createSchema(client, testSchema);
    }
    catch (e) {
      if (e.code === 386 /*schema already exists, so lets drop it first*/) {
        await dropSchema(client, testSchema);
        await createSchema(client, testSchema);
      } else {
        throw e;
      }
    }
  });
});

after(() => {
  console.log('global teardown');
  return useConnectionP(credentials, client => dropSchema(client, testSchema))
});
```

You can see I want to create a database schema before and drop the schema after.

Unfortunately the global before and after hooks seem to be called only once (basically after I start wallaby in my IDE), but they don't seem to be executed after I change a test, even if wallaby restarts a worker. (I tried both to enable and disable worker recycle but it didn't get called either way). They only seem to be executed once I change specifically the envSetup.test.js file.

What I would have expected is that those hooks get called for every test run, exactly like the wallaby specific `setup` and `teardown` hooks in the wallaby.js config.

You might wonder why I'm not using the wallaby.js specific hooks? The reason is I don't want to have too much wallaby specific config / logic, because I also have to run everything in a CI environment via the normal mocha runner, which obviously will not execute the wallaby specific hooks but only the mocha native hooks.

Can this be fixed or is this purposeful or an inherent limitation because the hooks are defined in a separate file?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.js',
      {pattern: 'test/**/*', instrument: false},
      {pattern: 'test/**/*.test.js', ignore: true}

    ],
    tests: [
      'test/**/*.test.js'
    ],
    env: {
      type: 'node',
      params: {
        runner: '--harmony'
      }
    },
    testFramework: 'mocha',
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: function () {

      console.log('global wallaby setup');
      //
      // if (typeof global.count !== 'number') {global.count = 0;}
      // global.count = global.count + 1;

      // setup CHAI and CHAI AS PROMISED using `should` assertion style
      const chai = require('chai');
      const chaiAsPromised = require('chai-as-promised');
      chai.use(chaiAsPromised);
      global.should = chai.should();
    },

    teardown: function(){
      console.log('global wallaby teardown');
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    },
  };
};
```

### Code editor or IDE name and version

WebStorm 2016.2.4
Build #WS-162.2228.20, built on October 18, 2016

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
Wallaby doesn't have any limitations for hooks are defined in a separate file. The file `test/envSetup.test.js` is specified as a test in your wallaby config (satisfies `tests` pattern), so it gets run as every other test - guaranteed on start, but then only if you change it or something  that the test covers.

What you need to do is to load the file with the hooks before tests. The `setup` function is a perfect place to do it. Your hooks logic can stay in a separate file that can be re-used when running tests on CI server. Note that mocha defines global `before` and `after` hooks slightly after the `setup` function (when loading test/spec files), so you'll need to `require` the file with hooks using `mocha.suite.beforeAll` callback:

```javascript
    tests: [
      '!test/envSetup.test.js'
      'test/**/*.test.js'
    ],
    ...
    setup: function (w) {
      let mocha = w.testFramework;
      mocha.suite.beforeAll(() => require(w.localProjectDir + '/test/envSetup.test'));
    },
```

Let me know if this works for you. I tested on a simple sample and it seems to work ok.

**Comment by geekflyer** [comment]
Hi @ArtemGovorov,

I just tried your suggestion, however it seems the wallaby transpiler doesn't transpile my envSetup.js file with this setup. I'm getting `"before all" hook: Unexpected reserved word` . To isolate the problem I just commented out everything in the envSetup.js and put it a `console.log('foo')` and then it worked.

Here's my wallaby config:

```js
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.js',
      {pattern: 'test/**/*', instrument: false},
      '!test/**/*.test.js'
    ],
    tests: [
      '!test/envSetup.test.js',
      'test/**/*.test.js',
    ],
    env: {
      type: 'node',
      params: {
        runner: '--harmony'
      }
    },
    testFramework: 'mocha',
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: function (wallaby) {

      console.log('global wallaby setup');

      var mocha = wallaby.testFramework;

      mocha.suite.beforeAll(() => require(wallaby.localProjectDir + '/test/envSetup.js'));

      // if (typeof global.count !== 'number') {global.count = 0;}
      // global.count = global.count + 1;

      // setup CHAI and CHAI AS PROMISED using `should` assertion style
      const chai = require('chai');
      const chaiAsPromised = require('chai-as-promised');
      chai.use(chaiAsPromised);
      global.should = chai.should();
    },

    teardown: function(){
      console.log('global wallaby teardown');
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    },
  };
};
```

and again the `envSetup.js` (note I removed the `.test` from the filename

```js
import {getUniqueSchemaName} from '../src/util';
import {createSchema, dropSchema} from '../src/db';
import {useConnectionP} from 'sap-hdb-addons-promise';

const credentials = require('./credentials.json');

let testSchema = getUniqueSchemaName();

before(() => {
  console.log('global setup');
  // setup schema for tests
  return useConnectionP(credentials, async client => {
    try {
      await createSchema(client, testSchema);
    }
    catch (e) {
      if (e.code === 386 /*schema already exists, so lets drop it first*/) {
        await dropSchema(client, testSchema, true);
        await createSchema(client, testSchema);
      } else {
        throw e;
      }
    }
  });
});

after(() => {
  console.log('global teardown');
  return useConnectionP(credentials, client => dropSchema(client, testSchema))
});
```

**Comment by ArtemGovorov** [comment]
Hi @geekflyer, 
sorry I have missed that you're using ES6 imports in the hooks file, so I suggested to load the file from the project folder (`wallaby.localProjectDir`) without wallaby compilation.

In this case you may just compile the file and load it from the wallaby cache (`wallaby.projectCacheDir`). Note that wallaby doesn't compile files that are marked with `instrument: false`, so I have also listed the file in the files list before the `{pattern: 'test/**/*', instrument: false}` pattern, so it uses the default `instrument: true` and gets compiled.

If you're using [Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html) and have set `instrument: false` flag to make the files not to contribute to the code coverage metrics, you [may use this setting instead](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html#how-to-exclude-certain-files-or-file-patterns-from-code-coverage-calculation).

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.js',
      'test/envSetup.js', // <--- so it gets instrumented and compiled
      {pattern: 'test/**/*', instrument: false},
      '!test/**/*.test.js'
    ],
    tests: [
      'test/**/*.test.js',
    ],
    env: {
      type: 'node',
      params: {
        runner: '--harmony'
      }
    },
    testFramework: 'mocha',
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: function (wallaby) {

      console.log('global wallaby setup');

      var mocha = wallaby.testFramework;

      // <--- using projectCacheDir to load the compiled file
      mocha.suite.beforeAll(() => require(wallaby.projectCacheDir + '/test/envSetup'));

      // if (typeof global.count !== 'number') {global.count = 0;}
      // global.count = global.count + 1;

      // setup CHAI and CHAI AS PROMISED using `should` assertion style
      const chai = require('chai');
      const chaiAsPromised = require('chai-as-promised');
      chai.use(chaiAsPromised);
      global.should = chai.should();
    },

    teardown: function(){
      console.log('global wallaby teardown');
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    },
  };
};
```

Hope it makes sense. Let me know if this works for you.

**Comment by ArtemGovorov** [comment]
If you don't want to instrument the file with global hooks file for some other reason, and still would like it to be compiled, you may [define a preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) just for that file
```javascript
...
files: [
      'src/**/*.js',
      {pattern: 'test/**/*', instrument: false},
      '!test/**/*.test.js'
    ],
...
preprocessors: {
      'test/envSetup.js': file => require('babel-core')
                            .transform(file.content, {sourceMap: true, filename: file.path, presets: [...]})
    }
```
In this case the file will not be instrumented, but will be compiled.

**Comment by geekflyer** [comment]
Thanks @ArtemGovorov , the second to last setup works now.

Another related question: Is there a way to do a global **async** setup (and teardown respectively), but only do it **one time**, once wallaby is started, irrespective of how many workers etc. are there?

In my current setup I'm creating a db schema (it's an actual db schema) and populate it with some test data in order to test some (read-only) query logic etc.. Currently I'm doing this with the above setup once per test run, however on the long term I expect to have a larger amount of test data so it is probably better to do this setup only one time - per wallaby start. Since in my tests I'm only doing **reads** on the test data there also will be no concurrency issues between multiple workers etc.

**Comment by ArtemGovorov** [comment]
To run something one time per worker, you may use the `setup` function. To make it async and one time only, you may do:
```javascript
setup: function (wallaby) {
  if(!global._executedOneTime) {
    global._executedOneTime = true;
    wallaby.delayStart();
    somethingAsync(() => {
        wallaby.start();
    });
  }
}
```

This, plus setting the `workers` count to 1. It should do the trick, but not ideal the parallelisation is disabled.

If you'd like to execute something before the test run in any of the workers, to be able to use the setup result in multiple workers without having to disable the parallelisation, you may try doing the setup earlier in the pipeline in a [postprocessor](https://wallabyjs.com/docs/config/postprocessor.html):

```javascript
postprocessor: function (wallaby) {
       return new Promise(
         function (resolve, reject) {
            try {
              // may use the same trick with global._executedOneTime
              // to only execute only once when wallaby is started

              // resolve when the work is done
              // or reject on errors
              resolve();

            } catch (err) {
              reject(err);
            }
          });
     }
```

Note that the postprocessor code is executed outside the test worker context (in the main node process), so you won't be able to set some process global state and re-use it in workers (unless you set/re-use `process.env` variables that are passed from the main process to test worker processes).

We haven't used a postprocessor for stuff like that, but theoretically I don't see why not.

Unfortunately, due to the nature how wallaby.js can be stoped, there's no async `teardown` version. I normally recommend to rely on any `teardown` and just check and do it if required in the setup code, because the `teardown` may fail to execute for various reasons, while the setup code will always run (and due to the continuous nature of the execution, it doesn't really matter when the teardown code is executed). You may invoke some async `teardown` code from mocha `after` hook (async version), just to keep things clean if it is a last run, but note that this code is not always guaranteed to execute for the [reasons described in the post](https://github.com/wallabyjs/public/issues/256#issuecomment-139975411).

Hope it makes sense.

**Comment by geekflyer** [comment]
@ArtemGovorov  I'm now setting up some stuff in the postprocessor and tried to pass credentials from postprocessor to the worker via `process.env.MYSTUFF` but in the worker (have set worker count to 1) the environment variable is not defined. Any idea? Is there another way to pass context from postprocessor to the workers?

**Comment by ArtemGovorov** [comment]
@geekflyer By the time the postprocessor runs, test worker processes are already created with the `process.env` available at that time, so it's too late to set anything in the postprocessor.

It will work if you set the `process.env` vars earlier:

```javascript
module.exports = function (wallaby) {
  
  process.env.MYSTUFF = 'MYSTUFF';

  return {
    ...
    postprocessor: function () {
      return new Promise(
        function (resolve, reject) {
          try {
            // ...
            resolve();

          } catch (err) {
            reject(err);
          }
        });
    },
    setup: function (w) {
      console.log(process.env.MYSTUFF);
      ...
    }
```

This should work if the context you're passing is not created in the postprocessor. If you do, you may just pass the context as a file, for example JSON, so it's easier to consume in the worker:

```javascript
   postprocessor: wallaby => {
      // `createFile` returns a promise, so may just return it from the postprocessor
      return wallaby.createFile({
        path: 'context.json',
        content: '{"MYSTUFF": "mystuff"}'
      });
    },
   setup: function () {
      // you may just consume the JSON from tests or set the process.env
      var context = require('./context.json');
      console.log(context);
      process.env.MYSTUFF = context.MYSTUFF;
      ...
    },
```

 Would this work for you?

**Comment by geekflyer** [comment]
the first one doesn't really seem to work since the 
```js
function (wallaby) {

  process.env.MYSTUFF = 'MYSTUFF';

  return {
    ...
    postprocessor: function () {
      return new Promise(
        function (resolve, reject) {
          try {
            // ...
            resolve();

          } catch (err) {
            reject(err);
          }
        });
    },
    setup: function (w) {
      console.log(process.env.MYSTUFF);
      ...
    }
```

seems to be *evaled* once for the wallaby main process and then again for each test.:

```js
'use strict';

module.exports = function (wallaby) {

  console.log('run wallaby config');

  return {
    files: [
      'src/**/*.ts',
      'test/envSetup.ts',
      { pattern: 'test/**/*', instrument: false },
      '!test/**/*.test.ts'
    ],
    filesWithNoCoverageCalculated: ['test/envSetup.ts'],
    tests: [
      'test/**/*.test.ts'
    ],
    env: {
      type: 'node',
      params: {
        runner: '--harmony'
      }
    },
    testFramework: 'mocha',
    preprocessors: {
      // transpile missing ES6 / ES2015 features for current node version (i.e. 4.4.7), since we wanna set TypeScript target to ES6
      '**/*.js': wallaby.compilers.babel()
    },
    setup: function (wallaby) {
      var mocha = wallaby.testFramework;
      mocha.timeout(30000);

      mocha.suite.beforeAll(() => require(wallaby.projectCacheDir + '/test/envSetup.js'));
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: false
    }
  };
};
```

```sh
wallaby.js started
core v1.0.313
run wallaby config
Wallaby App available at: http://wallabyjs.com/app/#/files
run wallaby config
run wallaby config
run wallaby config
run wallaby config
run wallaby config
run wallaby config
run wallaby config
run wallaby config
console.log: global mocha setup
console.log: global mocha teardown
Finished executing 7 affected test(s)
```

Didn't yet try the second example, but I guess this would do it. I meanwhile just wrote a plain.js script with the setup and added it into the `before launch` runner configuration of wallaby in webstorm. The script emits a `credentials.json` which is later on read by the worker, similar to your second example.

I guess that does it for now but on the mid term it would be nice if wallaby would better support all those one-time setup scenarios (see it as as a feature request :-) ). One thing I can't easily do for example do at the moment (neither with before_launch webstorm config, nor postprocessor) is to write the setup script itself in TypeScript and / or reuse other test utilities written in TypeScript. I would have to setup and initialize the TypeScript compiler completely separately from wallaby just for loading and transpiling the one-time test logic.

Maybe it would be good to add a `setupOneTime` hook or something similar.

Thx and Best Regards Christian

**Comment by ArtemGovorov** [comment]
> wallaby config seems to be evaled once for the wallaby main process and then again for each test

It's actually evaled once for the wallaby main process and once for each `instrumenter` process. Wallaby creates a few instrumenter processes to compile/instrument files in parallel. Once executed, the wallaby config root function is not executed when you're editing tests/files after wallaby is started.

> One thing I can't easily do for example do at the moment (neither with before_launch webstorm config, nor postprocessor) is to write the setup script itself in TypeScript and / or reuse other test utilities written in TypeScript.

Just tried something and it seems to work. I did

```
npm i ts-node --save-dev
```
and created a `plain.ts` file in the project root, that exports some context (and can import/use any other TS files):

```javascript
    postprocessor: w => {
      require('ts-node/register');
      return w.createFile({
        path: 'credentials.json',
        content: JSON.stringify(require('./plain'))
      });
    },
    setup: function (w) {
      var context = require('./credentials.json');
      console.log(context);
    },
```

> Maybe it would be good to add a setupOneTime hook that runs after the transpilers and postProcessors, but before the first worker is started or something similar.

Noted, thanks!
