### ISSUE TITLE
Angular2 cli ​showing 0 failing and 0 passing

### ISSUE THREAD

**Issue by Conrad777** [wallabyjs/public#851]
I think I am just missing something that might be very obvious to you, but when I run wallaby it doesn't seem to access my tests. All I get in the wallaby console is `0 failing tests, 0 passing` with no errors.

I am using the Angular cli version 1.0.0-beta.17 and copied [this example](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js) for my config file.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'script-loader', exclude: /node_modules/},
      {test: /\.scss$/, loaders: ['raw-loader', 'postcss-loader', 'sass-loader']},
      { test: /\.json$/, loader: 'json-loader' },
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: {runner: '--web-security=false'}
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.6.1

### OS name and version

macOS Sierra v10.12

**Comment by ArtemGovorov** [comment]
> All I get in the wallaby console is `0 failing tests, 0 passing` with no errors.

This is normally printed in `Wallaby.js Tests` output channel, wallaby console output should have much more details. Try switching to the [`Wallaby.js Console` output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) to see if there're any errors reported there.

One thing I can see different between your config file and the example if the missing [`src/wallabyTest.js` entry pattern](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L5) and probably [the file itself](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts). It's a file to initialize testing environment, just like the [one for karma](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/test.ts).

**Comment by Conrad777** [comment]
That was it... I knew I was missing something silly.

Thanks for the help!!!

**Comment by ArtemGovorov** [comment]
No worries, thanks for the update!
