### ISSUE TITLE
Wallaby updates to old version (1.0.178)

### ISSUE THREAD

**Issue by uitgewis** [wallabyjs/public#852]
### Issue description or question
While attempting to trail out wallaby on a recent project, I installed the plugin for VSCode and everything worked fine. The following day the "wallaby core" updated to `1.0.178`, and is persisting to download it when attempting to do a "force" update by deleting the relevant client folders.

I have also attempted to reinstall the plugin on VSCode by uninstalling and installing it again, but to no avail. 

However, strangely enough I found a file from ./dist/wallaby.json which does not match with what's given at http://update.wallabyjs.com/wallaby.json. I've tried replacing the file locally with the remote one and restarting VSCode, also with no success.

### Code editor or IDE name and version
Visual Studio Code v1.6.1

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment]
Do you have a valid wallaby license key? If not, where did you get the trial license key from?

**Comment by ArtemGovorov** [comment]
Either way, please email the wallaby license key you're using to hello@wallabyjs.com. You may display/copy the key by using `Manage license key` command.
