### ISSUE TITLE
Wont run, stuck after  Sandbox is generated step after license purchase

### ISSUE THREAD

**Issue by vnovakovits** [wallabyjs/public#853]
### Issue description or question
Worked fine in trial, after license stuck in Sandbox is generated step and didn't run.
![capture](https://cloud.githubusercontent.com/assets/11074850/19937784/4764e7a8-a12b-11e6-9d09-4b3ff5b12e17.PNG)
When i tried to run wallaby again it warned me that it's a single instance configuration and asked if i wanted it to stop.
When i stopped it and tried once more i had the same issue.

### Wallaby.js configuration file
```
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallaby-test.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.test.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'package.json', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: {runner: '--web-security=false'}
    },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
WebStorm 2016.2.4
Build #WS-162.2228.20, built on October 18, 2016
JRE: 1.8.0_101-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

### OS name and version
Windows 8,1 Pro

**Comment by ArtemGovorov** [comment]
The license activation shouldn't affect it, so it's probably just a coincidence. 

Since your config looks very similar to [the ngCli sample](https://github.com/wallabyjs/ngCliWebpackSample), could you please try getting the ngCli sample locally and running wallaby on it to see if it works?

**Comment by ArtemGovorov** [comment]
Please let me know if this is still a valid issue.
