### ISSUE TITLE
Typescript 2.0 via NuGet

### ISSUE THREAD

**Issue by iamdudley** [wallabyjs/public#856]
We use a Typescript compiler that is distributed via NuGet rather than having it installed locally on dev machines and our CI build servers. This means when we upgrade Typescript the correct version of the Typescript compiler is used at the appropriate time because the Typescript version is referenced in the csproj file for each project that uses Typescript. With this set up we do not have a tsconfig.json file.

Is it possible to configure Wallaby to use this NuGet version of Typescript rather than the in built Wallaby version? We have moved on to Typescript 2.0 and the built in compiler seems to be 1.8. This part confuses me because it isn't complaining if I use a 2.0 feature like "never". It compiles just fine so maybe Wallaby isn't using the 1.8 tsc.exe?

The NuGet package is located at localRepo\packages\Microsoft.TypeScript.MSBuild.2.0.6 and wallaby.js is at localRepo\MyApp\Solution\wallaby.js. The compilers section of wallaby.js is

```
    compilers: {
            "**/*.ts": wallaby.compilers.typeScript({
                orderFilesByReferenceComments: true,
                target: "es5"
            })
```

Whilst investigating this issue I was watching the processes involved and I never saw tsc.exe running when wallaby.js was compiling the .ts into .js. When building with VS2015 directly I could see it running from the NuGet package directory. This confuses me because I expected to see a version of tsc.exe running from inside C:\Users\me\.wallaby\core or C:\Users\me\AppData\Local\Temp\1\.wallaby\projects

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
Windows Server 2008 R2

Thanks for your help.

James.

**Comment by ArtemGovorov** [comment]
Wallaby.js is not using the `tsc.exe`, the command line tool was designed for one time compilation and is too slow for the incremental compilation on code changes. We are using [TypeScript Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services) to make the incremental compilation as fats as possible.

So wallaby.js is first trying to find the [`typescript` node module](https://www.npmjs.com/package/typescript) installed locally (in the project `node_modules`), if it doesn't find it, then it uses the built-in version (1.8).

It is possible to have the `typescript` node module installed anywhere, and [`require` it by its path in the wallaby config](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-version). However, looking into the Microsoft.TypeScript.MSBuild nuget package, the package doesn't include the `typescript` node module, only the `tsc`, so it will not be possible to use it from wallaby.

I have just updated the built-in TS version to 2.0.7, so you may [update your wallaby.js core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)  and hopefully you can just keep using it for now. Mid/long term solution would be to have the `typescript` node module installed locally/or added to the solution node modules/`devDependencies`.

Hope it makes sense. Please let me know if it addresses your issue/question.

**Comment by iamdudley** [comment]
Thanks for the quick response. Looks like I'll need to do a little more reading!
