### ISSUE TITLE
Typescript2 baseUrl mapping

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#857]
Cannot get working configuration for ts2 with `baseUrl` path mapping in node environment.

Test code:
```
import _ from 'core/utils';
_.x;
```
This code throws the following error in wallaby console: `​​[Error] Runtime error: Error: Cannot find module 'core/utils'​​`

### Wallaby.js configuration file
```javascript
module.exports = (wallaby) => {
    var tsCompiler = wallaby.compilers.typeScript({
        "module": "commonjs",
        "baseUrl": "."
    });
    return {
        files: [
            '**/*.ts',
            "!**/*.tests.ts", "!**/.tests.ts",
        ],
        tests: [
            "**/*.tests.ts", "**/.tests.ts"
        ],
        compilers: {
            '**/*.ts': tsCompiler,
            '**/.tests.ts': tsCompiler
        },
        env: {
            type: 'node'
        },
        testFramework: 'mocha',
        setup: function() {}
    }
}
```

versions: Windows & Visual Studio Code fresh release

**Comment by ArtemGovorov** [comment]
I'm not sure how the `baseUrl` is related, but what you seem to be missing is the hint to node.js [where to load the modules](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) references by non-relative paths like `core/utils`. if the `core/utils` is the folder in your project root (as well as other non-relative imports), try this:

```javascript
module.exports = (wallaby) => {
    ...
    var path = require('path');
    process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;
    ...
    return {
        ...
    };
}
```

**Comment by andr2** [comment]
Thanks! Now it works.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
