### ISSUE TITLE
Alt+W, Alt+1 only works after using Solution Explorer wallaby.js context menu first

### ISSUE THREAD

**Issue by iamdudley** [wallabyjs/public#859]
If I try to start Wallaby using Alt+W, Alt+1 shortcut key combo it does not start. I then start Wallaby by using the context menu on the wallaby.js file in the Solution Explorer. Wallaby starts. From this point on all the Wallaby shortcuts work (Stop, Start, re-Start). 

I have checked the Visual Studio keyboard shortcut bindings and the Wallaby shortcuts are there in the global scope. Any thoughts on what might be going wrong?

**Comment by ArtemGovorov** [comment]
Hi, thanks for the report. We are able to reproduce the issue and are looking into it.

**Comment by ArtemGovorov** [comment]
The issues is fixed and the fix is published in the latest wallaby for VS extension v1.0.27.
