### ISSUE TITLE
Elaborate run window output in webstorm

### ISSUE THREAD

**Issue by g0t4** [wallabyjs/public#86]
I find myself watching the "Failing Tests" window quite a bit. When there are no failing tests, it would be nice to have the number of passing tests. "No failing tests" could mean something is messed up and no tests are loaded. Unfortunately even using the "Wallaby console" for this is tricky with the continuous testing nature, you really only get an overall test count when you first launch wallaby. If the "failing tests" window reported "No failing tests, X passing" that would help me have confidence that I really didn't muck something up. 

Also, when there are failures, the # failing versus the # passing would be nice to see at the top of the output to see how bad I messed up the tests, how many tests did I "break"

In the "Wallaby console" it would also be nice to see the number of tests re-run as part of the standard, non debug output. Right now it's part of the debug output but it blends in with debug information and is hard to find. Also, it would be nice to have this without the debug flag turned on. When I change code, it would be awesome to know how many tests are affected/re-run.

These are just a few ideas of what would help me "trust" what wallaby is reporting back to me and perhaps catch issues, especially when I'm modifying the wallaby configuration file. Perhaps part of my desire for this is that a few times wallaby seems to get "stuck" after a few hours of using it and I have to relaunch the runner. Though, I think these would be nice long term features to have too.

**Comment by ArtemGovorov** [comment]
Thanks for the feedback.
I have added both number of passing tests to the "Failing Tests" tab and number of affected tests that re-run on changes to the "Wallaby Console" tab. 

The idea is still shaping up, but there's [the feature request](https://github.com/wallabyjs/public/issues/38) to add coverage reports, as well as [some ideas](https://github.com/wallabyjs/public/issues/79#issuecomment-95544751) from @fvanwijk. It seems like some form of 'project overview/summary' or 'test explorer' with some stats/test data would significantly increase the visibility of what is going on with the tests.

**Comment by g0t4** [comment]
Awesome, this will be a great help for me. I like the simplicity of very
little output, I think this is just the right balance to understand and
"trust" what's going on as the tests can run so quickly I don't even know
if they ran!
