### ISSUE TITLE
Wallaby config for latest Aurelia webpack skeleton v1.1.1

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#865]
### Question / request for example config 

Could someone please create a sample wallaby.js config file to use with the latest Aurelia webpack skeleton?

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

Thanks.

**Comment by ArtemGovorov** [comment]
Was there any specific issue that you've encountered when trying to create the config for the project? 

The config I have [created for you here](https://github.com/wallabyjs/public/issues/835) works for me with some minimal changes:

```javascript
process.env.BABEL_ENV = 'node';
process.env.NODE_ENV = 'test';

require('babel-core/register');
var webpackConfig = require('./webpack.config.babel');

// Cleaning it
delete webpackConfig.entry;
delete webpackConfig.devServer;
delete webpackConfig.resolve.root;
delete webpackConfig.module.postLoaders;

// removing babel and source map loaders
webpackConfig.module.rules.shift();
webpackConfig.module.rules.pop();

webpackConfig.plugins = webpackConfig.plugins.filter(p => !p.getPath);
webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/**/*.spec.js'];

process.env.BABEL_ENV = 'webpack';
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'test/unit/setup.js', load: false},
      {pattern: 'src/**/*.js', load: false}
    ],

    tests: [
      '!test/e2e/**',
      {pattern: 'test/**/*.spec.js', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

The changes are:
- using `babel-core/register` to load webpack config that is using ES imports, so needs to be transpiled;
- setting `process.env.BABEL_ENV` for the webpack config dynamic transpilation and then for the webpack build;
- removing webpack loaders for JavaScript files. The webpack config now exports them as `webpackConfig.module.rules` (that you may see by using `console.log` in the wallaby config), and have the first and the last rule for babel-loader and `istanbul` coverage instrumentor respectively (so I used `shift` and `pop`).
- removing wallaby compiler settings for babel as there's [the `.babelrc` file in the project that wallaby can use automatically](https://wallabyjs.com/docs/integration/es-next.html#babel-compiler-options) (given that the `process.env.BABEL_ENV` is set in the wallaby config).

If you hit the issue with `babel-core/register` (`SyntaxError: Unexpected token ! in JSON at position 0`), you may use the [solution described here](https://github.com/wallabyjs/public/issues/863#issuecomment-259470716).

**Comment by stevies** [comment]
Thanks.  I almost got it working by hacking around in the previous example - but your solution above is much neater.
