### ISSUE TITLE
Typescrript ES6 is not working with Wallaby (Aurelia config)

### ISSUE THREAD

**Issue by tomasbonco** [wallabyjs/public#869]
Hello,

Wallaby config: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript/wallaby.js
TSconfig: https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript/tsconfig.json

Only TSconfig mutation is target set to `es6`, which breaks wallaby. With `es5` it works in amazing way.

Thank you.

**Comment by ArtemGovorov** [comment]
Wallaby.js using PhantomJs 2 by default, and ES6 is not fully supported by it. You may either add [babel preprocessor](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) to compile ES6 to ES5 or use [Electron runner that natively supports ES6](https://wallabyjs.com/docs/integration/electron.html). For example, doing:

```
npm install electron --save-dev
```
+
```javascript
module.exports = function () {
  return {
    ...

    env: {
      kind: 'electron'
    }
  };
};
```
worked for me on the referenced repo.
