### ISSUE TITLE
Unable to use `jest.mock` with Wallaby

### ISSUE THREAD

**Issue by narthollis** [wallabyjs/public#872]
### Issue description or question

When running tests in wallaby, modules mocked using `jest.mock` are imported rather than the requested mocked version.

A minimal reproduction can be found at https://github.com/narthollis/minimal_jest_mock

Output from npm run -s test (`jest --no-cache --config jest.config.json`)
```
E:\temp\minimal_jest_mock>npm run -s test
 PASS  src\items\example.test.js
  example
    √ should return the current unix time stamp (4ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.812s
Ran all test suites.
```

Output from Wallaby console
```
1 failing tests, 0 passing

src/items/example.test.js example should return the current unix time stamp [3 ms]

	TypeError: _dateProvider2.default.now.mockImplementationOnce is not a function
		at Object.<anonymous> src/items/example.test.js:15
		at Object.e.length.arguments.(anonymous function) test/setup-before-after.js:34
```

### Wallaby.js configuration file
```javascript
process.env.NODE_ENV = 'test';

// eslint-disable-next-line func-names
module.exports = function (wallaby) {
    return {
        files: [
            { pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false },
            'defaultData/**/*.json',
            'src/**/*.js*',
            '!src/**/*.test.js*',
            '!src/**/*.fixture.js',

            { pattern: 'test/*.js', instrument: false },
        ],

        tests: [
            'src/**/*.test.js',
            'src/**/*.test.jsx',
        ],

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
            '**/*.jsx': wallaby.compilers.babel(),
        },

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony',
            },
        },

        testFramework: 'jest',

        setup: (w) => {
            w.testFramework.configure({
                setupTestFrameworkScriptFile: '<rootDir>/test/setup-before-after.js',
                moduleFileExtensions: ['js', 'json', 'jsx', 'node'],
                moduleNameMapper: {
                    '^.+\\.(css|scss|sass)$': '<rootDir>/test/styleMock.js',
                    '^.+\\.(gif|ttf|eot|svg)$': '<rootDir>/test/fileMock.js',
                },
                // testRegex: '/__tests__/.*|\\.(test|spec)\\.(js|jsx)$',
            });
        },
    };
};

```

### Code editor or IDE name and version
WebStorm 2016.3

### OS name and version
Windows 7

A Min

**Comment by ArtemGovorov** [comment]
Interesting, if you change 
```javascript
import * as example from './example';
import DateProvider from '../module/dateProvider';
jest.mock('../module/dateProvider');
```
to

```javascript
jest.mock('../module/dateProvider');
const example = require('./example')
const DateProvider = require('../module/dateProvider').default;
```
then it starts working. Looks like `jest` is doing some magic internally to call `jest.mock` before imports and the magic is not called when `jest` is used by wallaby.  I'm investigating it now.

**Comment by narthollis** [comment]
In the Jest documentation, it mentions:
> Note: When using `babel-jest`, calls to `mock` will automatically be hoisted to the top of the code block. Use `doMock` if you want to explicitly avoid this behavior.

https://facebook.github.io/jest/docs/api.html#jestmockmodulename-factory-options

Could this be related?

**Comment by ArtemGovorov** [comment]
Yes, it looks like the case. Wallaby instrumentation is probably breaking the hoisting behaviour. I'm looking into the ways to fix it.

**Comment by ArtemGovorov** [comment]
Ok, so I have investigated what exactly is going on. `jest` is sneakily using `babel-preset-jest` to hoist calls to `mock`. But because it's implementation is not wallaby instrumentation friendly, it doesn't work. Actually anything other than simple usage breaks it, so for example following examples will not work with plain `jest`/`npm run test`:

```javascript
import * as example from './example';
import DateProvider from '../module/dateProvider';
{
  jest.mock('../module/dateProvider');
}
```

or 

```javascript
import * as example from './example';
import DateProvider from '../module/dateProvider';
1, jest.mock('../module/dateProvider');
```

To make it work, the preset has to be applied during wallaby babel compilation. There're a few options to make it work.

1) It can be specified in your `.babelrc`:
```
{
  "presets": [
    ["es2015", {"loose": false, "modules": false}],
    "react",
    "stage-1"
  ],
  "env": {
    "test": {
      "presets": [
        "babel-preset-jest", // <---
        ["es2015", {"loose": false, "modules": "commonjs"}],
        "react",
        "stage-1"
      ]
    }
  }
}
```
2) Alternatively you can have a separate section:
```
{
  "presets": [
    ["es2015", {"loose": false, "modules": false}],
    "react",
    "stage-1"
  ],
  "env": {
    "test": {
      "presets": [
        ["es2015", {"loose": false, "modules": "commonjs"}],
        "react",
        "stage-1"
      ]
    }
    "wallaby": { // <---
      "presets": [
        "babel-preset-jest", // <---
        ["es2015", {"loose": false, "modules": "commonjs"}],
        "react",
        "stage-1"
      ]
    }
  }
}
```
plus
```javascript
process.env.NODE_ENV = 'wallaby';
```
in your wallaby config.

3) Added to babel configuration in your wallaby config:

```javascript
process.env.NODE_ENV = 'test';

const babelConfig = JSON.parse(require('fs').readFileSync(require('path').join(__dirname, '.babelrc'))).env.test;
babelConfig.presets.push('babel-preset-jest');

// eslint-disable-next-line func-names
module.exports = function (wallaby) {
    return {
        ...
        compilers: {
            '**/*.js*': wallaby.compilers.babel(babelConfig)
        },
        ...
    };
};

```

Whatever way you choose, it should only affect wallaby, `npm run test` should still work the same way as it does now.

**Comment by narthollis** [comment]
Excellent. Thanks very much for looking into this and getting back to me
quickly.

**Comment by ArtemGovorov** [comment]
Forgot to mention one more way, probably the easiest one, with the only one change to wallaby config:

```javascript
        ...
        compilers: {
            '**/*.js*': wallaby.compilers.babel({babelrc: true, presets: ['babel-preset-jest']})
        },
```

**Comment by gregorskii** [comment]
@ArtemGovorov yep jest CLI does work.

It was related to this `babel-preset-jest` I found that using `babel-plugin-jest-hoist` is more compatible with Babel 7. The issue I am having now is the `__mocks__` is still not working.

I can try to put together a simpler repo to demonstrate, this project is a client's project.

Let me try a few more things and then Ill create the repo.

Have you seen any issues with using the  jest `__mocks__` folder before?

Seems like `jest.mock` mocks are working.

**Comment by gregorskii** [comment]
@ArtemGovorov here is a smaller fork of my project:

https://github.com/gregorskii/wallaby-native-test

When running wallaby I see a lot of issues with long execution:

```
Some long running code has been detected: one of your files is taking more than 5000ms to execute.
Execution of the following files has started but has not finished:
- src/App.js
- src/App.test.js
- src/navigation/AppNavigator.js
Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,
and restarting wallaby to make sure that it is this test/file causing the issue and not something else.
Pinging test runner sandbox...
The sandbox is not responsive. Check for possibly recently introduced infinite loops.
```

At the end of it env variables that should be set by `react-native-config` are not set. These values are mocked in the `__mocks__` folder.

Running `yarn test` results in the correct behavior:

```
 PASS  src/components/StyledText.test.js
 PASS  src/App.test.js
  ● Console

    console.log src/App.js:12
      WALLABY@!
    console.log src/App.js:12
      WALLABY@!


Test Suites: 2 passed, 2 total
Tests:       3 passed, 3 total
Snapshots:   3 passed, 3 total
Time:        2.223s
Ran all test suites.
```

The value Config.TEST is set, which is defined in the `.env`.

The details of how `react-native-config` work is not the issue I have (that package was picked for this project by a previous team. My issue is that it appears that the `__mocks__` and the mock in `__tests__/setupJest.js` do not appear to be running.

**Comment by gregorskii** [comment]
Ah yes. That makes perfect sense. Will add the .env and instruct the team the delay in starting is expected (makes sense it would be).

I was initiated thinking the delay was due to the missing env variable, but it does make sense it has to mount a lot to run ready native code.

Thank you!

**Comment by meltedspark** [comment]
How am I supposed to workaround it with `yoshi 3.0.0`? The only line in `wallaby.js` is `module.exports = require('yoshi/config/wallaby-jest');`

**Comment by ArtemGovorov** [comment]
@meltedspark Since different questions had been raised/answered in this issue, could you please provide some more details about the issue that you have? Perhaps even create a separate issue - we are happy to help.

**Comment by meltedspark** [comment]
The issue is exactly the same - when running with `wallaby.js` the `jest.mock`s are not hoisted. I can open a separate issue but not sure it's necessary because it will be the same.

**Comment by meltedspark** [comment]
[Here](https://github.com/wix-private/business-manager-dashboard) is the project, [here](https://github.com/wix-private/business-manager-dashboard/tree/transfer-success-transfer) is the branch, [here](https://github.com/wix-private/business-manager-dashboard/blob/transfer-success-transfer/src/services/RenewalDateService.spec.ts) is the sample code.

**Comment by ArtemGovorov** [comment]
@meltedspark Thanks. I can not access the repo that you've listed (looks like it's private Wix repo), but your `devDependencies` is enough to see the issue. 

Wallaby with [Jest and Typescript needs the following preprocessor](https://wallabyjs.com/docs/integration/jest.html#jest-with-typescript-and-jestmock-calls) to make Jest hoisting work:

```js
module.exports = wallaby => {
  const config = require('yoshi/config/wallaby-jest')(wallaby);
  config.workers = {recycle: false};
  config.preprocessors = {
    '**/*.js?(x)': file =>
      require('babel-core').transform(file.content, {
        sourceMap: true,
        filename: file.path,
        presets: ['babel-preset-jest']
      })
  };
  return config;
};
```

I have also set `workers.recycle` to false, it makes Wallaby much faster - not sure why it's set to `true` in `yoshi`, I will create a pull request to revert it.

**Comment by meltedspark** [comment]
Oops, I just noticed that I posted in the wrong issue ))) I meant to post in in yoshi's repository, there is an issue with the exact same title. *facepalm*.
Thank you so much for helping despite of missing context!
