### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Waihibeachian** [wallabyjs/public#876]
Hi, I'm wondering if you can help me. I'm getting the below error when I initally start or restart wallaby

![image](https://cloud.githubusercontent.com/assets/16510929/20446636/9918cec2-ae3f-11e6-9c85-dadb432e2d47.png)

Also the test count is 27 but there are 90 tests in total.

If I go into the source .ts or the actual test file and press space (ie make a change) all the tests in that file execute correctly and the error goes away. In addition, the total test count increase as I press space in each test file until all tests pass which increases the total passed tests to 90. FYI Im using "core v1.0.324"

Any insights would be great. 

### Wallaby.js configuration file
'use strict';

const wallabyWebpack = require('wallaby-webpack');

module.exports = (wallaby) => {

    const webpackPostprocessor = wallabyWebpack({
        entry: ['babel-polyfill']
    });

    return {
        files: [
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'test/unit/setup.ts', load: false },
            { pattern: 'test/unit/unittestHelpers.ts', load: false }
        ],

        tests: [
            { pattern: 'test/unit/settings/globalstrings/*.spec.ts', load: false }
        ],

        postprocessor: webpackPostprocessor,

        compilers: {
            'src/**/*.ts': wallaby.compilers.typeScript({
                module: 'es2015',
                target: 'es2015',
                "experimentalDecorators": true,
                "emitDecoratorMetadata": true,
                typescript: require('typescript')
            })
        },

        preprocessors: {
            '**/*.js': wallaby.compilers.babel()
        },

        bootstrap: function (wallaby) {
            window.__moduleBundler.loadTests();
        },

        debug: false
    };
};

import './../../setup';
import {GlobalStrings, REFRESH_ORDER} from '../../../../src/settings/GlobalStrings';
import {AppMock} from '../../unittestHelpers';

describe('globalstrings_add', () => {
    let globalStrings;
    let app;

    beforeEach(() => {
        app = new AppMock()
        app.t = ""
        app.m = ""
         
        globalStrings = new GlobalStrings(null, app, null, null, true);
        globalStrings._nRefreshOrder = REFRESH_ORDER.COMPLETED
    });

    //#region _nRefreshOrder != REFRESH_ORDER.COMPLETED 2016-11-15 MW
    it('_nRefreshOrder != REFRESH_ORDER.COMPLETED', () => {
        globalStrings.settingsLabelsSource = []

        globalStrings._nRefreshOrder = REFRESH_ORDER.LOAD_SETTINGLABELS
        expect(globalStrings.add()).toEqual(false);

        expect(app.t).toEqual("");
        expect(app.m).toEqual("");
    });
    //#endregion

    //#region add hasChanges 2016-11-15 MW
    it('hasChanges', () => {
        globalStrings.hasChanges = true
        expect(globalStrings.add()).toEqual(false);

        expect(app.t).toEqual("Global Strings");
        expect(app.m).toEqual("Sorry you can not use the filter while current item is being edited");
        expect(app.type).toEqual(app.AlertTYPE.danger);
    });
    //#endregion

    //#region add good one 2016-11-15 MW
    it('Good One!', () => {
        globalStrings.hasChanges = false
        expect(globalStrings.add()).toEqual(true);

        expect(app.t).toEqual("");
        expect(app.m).toEqual("");
    });
    //#endregion
});

### Code editor or IDE name and version
Visual Studio 2015

### OS name and version
Windows ver 10.0.14393

**Comment by ArtemGovorov** [comment]
I'm not sure what exactly is causing the issue, but there're a few things that are not correct in the config.

- Babel-polyfill is not loaded correctly, see the correct way in [this issue](https://github.com/wallabyjs/public/issues/875#issuecomment-261694161) that I have responded.
- `preprocessors` setting is using compiler instead of a preprocessor. It should be something like:

```javascript
preprocessors: {
            'src/**/*.js': function (file) {
                return require('babel-core').transform(
                    file.content, { sourceMap: true, 
                      presets: ['es2015', 'react'] // <-- or whatever presets you have in your .babelrc
                });
            }
        },
```

However, you may just remove the babel preprocessor and make your TypeScript compiler to compile to ES5:

```javascript
    compilers: {
        'src/**/*.ts': wallaby.compilers.typeScript({
            module: 'commonjs',
            target: 'es5',
            "experimentalDecorators": true,
            "emitDecoratorMetadata": true,
            typescript: require('typescript')
        })
    },
```

Is there any specific reason you need the babel transpilation step and not using the direct compilation of TypeScript to ES5?

**Comment by Waihibeachian** [comment]
Thanks for the prompt reply! Your answer has lead me to a solution.

**Comment by Waihibeachian** [comment]
Thanks for the reply. The config file changes lead me to the following which is now working.

'use strict';

const wallabyWebpack = require('wallaby-webpack');

module.exports = (wallaby) => {

    const webpackPostprocessor = wallabyWebpack({});

    return {
        files: [
            { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'test/unit/setup.ts', load: false },
            { pattern: 'test/unit/unittestHelpers.ts', load: false }
        ],

        tests: [
             { pattern: 'test/unit/settings/**/*.spec.ts', load: false }
        ],

        compilers: {
            'src/**/*.ts': wallaby.compilers.typeScript({
                module: 'commonjs',
                target: 'es2015',
                "experimentalDecorators": true,
                "emitDecoratorMetadata": true,
                typescript: require('typescript')
            })
        },

        preprocessors: {
            '**/*.js': file => require("babel-core")
                .transform(file.content,
                {
                    sourceMap: true,
                    presets: ["es2015"]
                })
        },

        postprocessor: webpackPostprocessor,
        
        bootstrap: function (wallaby) {
            window.__moduleBundler.loadTests();
        },

        debug: false
    };
};
