### ISSUE TITLE
No context elements​​ - webpack + typescript + aurelia

### ISSUE THREAD

**Issue by dweber019** [wallabyjs/public#877]
### Issue description or question
I'm currently setting up wallaby in a webpack + ts + aurelia boilerplate.
You guys have an awesome documentation. Step for step I could proceed but now I'm stuck.

I have the following error:
```javascript
[Info]​​​​​ Sun, 20 Nov 2016 00:04:01 GMT wallaby:postprocessor New compiler created
​​[Error] No context elements​​
​​[Error] TypeError: Cannot convert undefined or null to object​​
​​[Error]   at /Users/<user>/Documents/aurelia-ts-boilerplate/node_modules/aurelia-webpack-plugin/dist/index.js:194:58​​
```

It's seams as the aurelia-webpack-plugin is causing some troubles but removing the plugin leads to other/more errors.

I also tried to use the following solution but didn't work either and I don't like it as webpack for example handles other data like json: https://github.com/wallabyjs/public/issues/544 

Here a branch to reproduce the error: https://github.com/w3tecch/aurelia-ts-boilerplate/tree/feature/wallaby-js

### Wallaby.js configuration file
```javascript
// https://github.com/wallabyjs/public/issues/726
var Module              = require( 'module' ).Module;
var modulePrototype     = Module.prototype;
var originalRequire     = modulePrototype.require;
modulePrototype.require = function ( filePath ) {
    if ( filePath === 'source-map-support' ) {
        return { install: () => {} };
    }
    return originalRequire.call( this, filePath );
};

process.env.NODE_ENV = 'test';
var webpackConfig = require('./webpack.config')();

modulePrototype.require = originalRequire;

webpackConfig.resolve.extensions = ['', '.js'];
webpackConfig.devtool = 'source-map';

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
  return {
    // set `load: false` to all source files and tests processed by webpack
    // (except external files),
    // as they should not be loaded in browser,
    // their wrapped versions will be loaded instead
    files: [
      // {pattern: 'lib/jquery.js', instrument: false},
      {pattern: 'src/app/**/*.ts', load: false}
    ],

    tests: [
      {pattern: 'test/unit/**/*.spec.ts', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.7.1

### OS name and version
OSX 10.12

Thanks for your help

**Comment by ArtemGovorov** [comment]
I have sent you the [pull request](https://github.com/w3tecch/aurelia-ts-boilerplate/pull/2). Here's an overview of the config changes ([mostly taken from here](https://github.com/wallabyjs/public/issues/835#issuecomment-254384615)):
- `aurelia-webpack-plugin` and webpack typescript loader have to be removed.
- the typescript webpack loader you're using is compiling TS to ES2015 according to your `tsconfig.json` and [using babel transpilation to compile ES2015 modules](https://github.com/w3tecch/aurelia-ts-boilerplate/blob/master/tsconfig.json#L13), so I have [added babel preprocesor](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) to do the same in wallaby config. 
- Added `babel-polyfill` to support Promises (see below).

Note that your karma config is using Firefox to run tests, while wallaby is using PhantomJs2 by default, so if you hit any ES2015 related issues, you may add more presets to the babel preprocessor (like `es2015`) or switch to [electron/V8 test runner](https://wallabyjs.com/docs/integration/electron.html) that supports most of the ES2015 (including promises, so if you switch, you may remove the `babel-polyfill` loading).

**Comment by dweber019** [comment]
Outstanding response time! Thanks a lot
