### ISSUE TITLE
Webpack Samples Fail on Linux

### ISSUE THREAD

**Issue by andyrj** [wallabyjs/public#883]
### Issue description or question
Attempting to run any of the webpack sample projects in VS Code 1.7.2 on Linux, fails silently...
https://github.com/wallabyjs/wallaby-webpack-sample,
https://github.com/wallabyjs/wallaby-webpack-*

The basic sample that is not webpack dependent works as expected, https://github.com/wallabyjs/wallaby_example

### Wallaby.js configuration file
Using provided wallaby.js files in each of the sample projects

```javascript
var wallabyWebpack = require('wallaby-webpack');

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    // webpack options

    externals: {
      // Use external version of React instead of rebuilding it
      "react": "React"
    },
    resolve: {
      extensions: ['', '.js', '.jsx']
    }
  });

  return {
    files: [
      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
      {pattern: 'src/**/*.js*', load: false}
    ],

    tests: [
      {pattern: 'test/**/*Spec.js*', load: false}
    ],

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

		debug: true,
    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.7.2

### OS name and version

Linux 4.8.11

### details ###
Running Dev env inside of docker container which is Ubuntu 16.04.1 image, fully updated with latest packages and VS Code version installed.  Node version is v6.9.1 installed via nvm, and I have set the necessary vs code settings for node: 
{
  "wallaby.node": "/home/dev/.nvm/versions/node/v6.9.1/bin/node"
}

If I clone the basic example at https://github.com/wallabyjs/wallaby_example,
npm install, and start wallaby within vs code, the tests run and the editor is populated with markers denoting test coverage.

For all of the sample webpack projects in your repo using the same environment that works for wallaby_example, fails to run the tests or show any test coverage marking in the editor window.

I enabled debug:true inside of the wallaby.js and receive the following output from the webpack example projects in the Wallaby Output window:

[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:project Wallaby config: /home/dev/github/andyrj/wallaby-webpack-es6-react/wallaby.js
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:fs File added: node_modules/react/dist/react-with-addons.js
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.328
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:fs File added: test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:fs File added: src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:project File cache: /home/dev/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.31/projects/17d3ef9d880e51dc
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:uiService Listening port 51235
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:52 GMT wallaby:project Config file change detected, invalidating local cache
​​​​​[Info]​​​​​ Wallaby App available at: http://wallabyjs.com/app/#/files
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:workers Parallelism for initial run: 2, for regular run: 2
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:workers Starting run worker instance #0
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:workers Starting run worker instance #1
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:workers Web server is listening at 44373
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File cache requires some updates, waiting required files from IDE
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File node_modules/react/dist/react-with-addons.js changes are patches only: false
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File test/labelSpec.jsx changes are patches only: false
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File src/Label.jsx changes are patches only: false
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Preparing to process test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Preparing to process src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Preparing to process node_modules/react/dist/react-with-addons.js
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Starting processor pool (if not yet started)
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File node_modules/react/dist/react-with-addons.js is not instrumented by core
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project No preprocessors configured for node_modules/react/dist/react-with-addons.js
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project Writing to disk and caching processed file node_modules/react/dist/react-with-addons.js
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:53 GMT wallaby:project File node_modules/react/dist/react-with-addons.js changes saved, store ts: 1459267271000, change ts: 1480370453150
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:processor Running 1 processor(s) for src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:processor Running 1 processor(s) for test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:processor Finished running one processor for src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Processing compiled src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Instrumenting src/Label.jsx, via process pool: true
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:processor Finished running one processor for test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Processing compiled test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Instrumenting test/labelSpec.jsx, via process pool: true
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project No preprocessors configured for src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Writing to disk and caching processed file src/Label.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project File src/Label.jsx changes saved, store ts: 1480369768572, change ts: 1480370453156
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project No preprocessors configured for test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Writing to disk and caching processed file test/labelSpec.jsx
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project File test/labelSpec.jsx changes saved, store ts: 1480369768572, change ts: 1480370453154
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 3 project files none were found by patterns: **/*.ts?(x)
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:project TypeScript postprocessor is removed as requested by itself
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:54 GMT wallaby:postprocessor New compiler created
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:postprocessor Emitting 161 files
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:project Postprocessor execution finished
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:project Test run started; run priority: 3
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:project Running all tests
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:workers Starting test run, priority: 3
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:phantomRunner Starting sandbox [worker #0, session #zybn9]
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:phantomRunner Preparing sandbox [worker #0, session #zybn9]
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:browserRunner Total files to load in sandbox: 162
​​​​​[Info]​​​​​ Mon, 28 Nov 2016 22:00:55 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #zybn9]: http://localhost:44373/wallaby_sandbox0.html

But the tests never actually appear to run...  I can see the "[---=-------]" progress indicator for wallaby just cycle endlessly on the vs code status bar.

Any help would be greatly appreciated as I would really like to use your product but I am not willing to change my build tools to do so.

**Comment by ArtemGovorov** [comment]
It looks like PhantomJs fails to start on your OS. Please try running [Electron runner instead](https://wallabyjs.com/docs/integration/electron.html):

```
npm install electron --save-dev
```
plus adding the `env` setting to your config:
```javascript
module.exports = function () {
  return {
    ...
    env: {
      kind: 'electron'
    }
    ...
  };
};
```

**Comment by andyrj** [comment]
I tracked down what was causing the issue on my end, I apologize for the noise

**Comment by ArtemGovorov** [comment]
Thanks for then update. Out of interest, what was the issue, if you don't mind sharing?

**Comment by andyrj** [comment]
running with grsecurity patched kernel, hadn't thought about paxctl issues preventing phantomjs/electron from running ><
