### ISSUE TITLE
Visual Studio 2015 crash on startup

### ISSUE THREAD

**Issue by stevegreatrex** [wallabyjs/public#884]
### Issue description or question
When I click Start Wallaby on the solution explorer context menu I get a generic Windows crash message of `Visual Studio 2015 stopped working...`

By debugging this error I found that it was due to the `.wallaby` folder not being present at `%AppData%\Local\Temp\.wallaby` which was causing a `DirectoryNotFound` exception to be thrown when trying to create the log file.

I manually created the `.wallaby` folder and it was able to start up without any problems.

### Wallaby.js configuration file
```javascript
Not applicable
```

### Code editor or IDE name and version
Visual Studio Enterprise 2015 Update 3 `14.0.25431.01`

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for the report. The issue is fixed and the fix is published in wallaby extension for VS v1.0.28.
