### ISSUE TITLE
Missing tracer start subscription

### ISSUE THREAD

**Issue by FlemmingBehrend** [wallabyjs/public#885]
### Issue description or question

I just purchased a licens and started with the angular-cli example. Awesome product btw :smile: 

When i running wallaby, sometimes I get the following error in the wallaby console:

```text
Runtime error: Error: Missing tracer start subscription
at http://localhost:62339/__wallaby__/tracer.js:14
```

Any idea how to avoid this?

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');

var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'src/wallabyTest.js',
        'src/**/*spec.js'
    ],
    module: {
        loaders: [
            {test: /\.css$/, loader: 'raw-loader'},
            {test: /\.html$/, loader: 'raw-loader'},
            {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
            {test: /\.json$/, loader: 'json-loader'},
            {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
            {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
            {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
            {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
        ]
    }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function(wallaby) {
    return {
        files: [
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'src/**/*.css', load: false},
            {pattern: 'src/**/*.scss', load: false},
            {pattern: 'src/**/*.html', load: false},
            {pattern: 'src/**/*spec.ts', ignore: true, load: false}
        ],
        tests: [
            {pattern: 'src/**/*spec.ts', load: false}
        ],
        testFramework: 'jasmine',
        env: {
            runner: require('phantomjs-prebuilt').path,
            params: {runner: '--web-security=false'}
        },
        plugins: [
            new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css|ico)$/, 'node-noop')
        ],
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
        },
        postprocessor: webpackPostprocessor,
        setup: function () {
            window.__moduleBundler.loadTests();
        },
        debug: false
    };
};

```

### Code editor or IDE name and version

IntelliJ IDEA v2016.3

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Just [updated the sample](https://github.com/wallabyjs/ngCliWebpackSample) to use the latest version of `angular-cli`. Could you please try the sample to see if the error shows up for you there?

> sometimes I get the following error in the wallaby console

- Could you please paste the full output (from the start) from the wallaby console when you get this error?
- How often do you get the error? I'm assuming it's not every time you start wallaby? 
- Are you getting the error when editing code/tests or only when you start/restart wallaby? 
- If it shows up during file editing, is there anything special/common with the files you're editing that cause the error to appear?
- If you can reproduce the issue in the sample repo (or could share an access to the repo where it is reproducible), could you please share the steps to reproduce it?

Most likely not related to the issue, but could you please remove this from your wallaby config:
```javascript
env: {
            runner: require('phantomjs-prebuilt').path,
            params: {runner: '--web-security=false'}
        },
        plugins: [
            new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css|ico)$/, 'node-noop')
        ],
```
The `env` setting is not required as this PhantomJs version is now the default used by wallaby and the `plugins` setting is misplaced, it's a webpack setting and should be passed to the `wallabyWebpack({...})`.

One other thing you may try is switching to [Electron test runner](https://wallabyjs.com/docs/integration/electron.html) to see if it the error is still showing up there.

**Comment by FlemmingBehrend** [comment]
Have worked for some hours now and I just got the error. When I started this morning there was an update to the intellij plugin. 

I updated the plugin and started by changing the configuration to match the comments from your previous post. (angular versions are the same as the ngCliWebpackSamle and updated the wallaby.js and removed plugins and env.)

> Could you please paste the full output (from the start) from the wallaby console when you get this error?  

I have put the full log [here](https://gist.github.com/FlemmingBehrend/4248867826aa0b4863b93a3c66514a21)  

> How often do you get the error? I'm assuming it's not every time you start wallaby?

Got it around 30-50 times yesterday, but today I have only got it once. Wallyby seems to work even when the error is there.

> Are you getting the error when editing code/tests or only when you start/restart wallaby?

It is when editing code and test code. I have never seen it when wallaby is starting.

> If it shows up during file editing, is there anything special/common with the files you're editing that cause the error to appear?

Not that I have noticed, seems to be when I have changed random components, services and tests in the project.

> If you can reproduce the issue in the sample repo (or could share an access to the repo where it is reproducible), could you please share the steps to reproduce it?

I have not been able to reproduce it in a stable way.

----
Another thing I have noticed is that wallyby takes along time executing my test.

Here is a snippet of the log, this is what it logs out when I am added a space to a test. 

```text
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project File src/app/consequences/consequences.component.spec.ts changes are patches only: true
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Returning previously cached file [50] from memory
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Preparing to process src/app/consequences/consequences.component.spec.ts
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project No compilers configured for src/app/consequences/consequences.component.spec.ts
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project File src/app/consequences/consequences.component.spec.ts is not instrumented by core
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project No preprocessors configured for src/app/consequences/consequences.component.spec.ts
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Writing to disk and caching processed file src/app/consequences/consequences.component.spec.ts
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project File src/app/consequences/consequences.component.spec.ts changes saved, store ts: 1480509150946, change ts: 1480510565431
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Running postprocessor
Wed, 30 Nov 2016 12:56:05 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Preparing to process src/app/consequences/consequences.component.spec.js
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Processing compiled src/app/consequences/consequences.component.spec.js
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Instrumenting src/app/consequences/consequences.component.spec.js, via process pool: false
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project No preprocessors configured for src/app/consequences/consequences.component.spec.js
Wed, 30 Nov 2016 12:56:05 GMT wallaby:project Writing to disk and caching processed file src/app/consequences/consequences.component.spec.js
Wed, 30 Nov 2016 12:56:05 GMT wallaby:uiService Outgoing message ui:files
Wed, 30 Nov 2016 12:56:06 GMT wallaby:postprocessor Emitting 2 files
Wed, 30 Nov 2016 12:56:06 GMT wallaby:project Postprocessor execution finished
Wed, 30 Nov 2016 12:56:06 GMT wallaby:project Test run started; run priority: 2
Wed, 30 Nov 2016 12:56:06 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Wed, 30 Nov 2016 12:56:06 GMT wallaby:workers Starting test run, priority: 2
Wed, 30 Nov 2016 12:56:06 GMT wallaby:phantomRunner Starting sandbox [worker #0, session #rh8v3]
Wed, 30 Nov 2016 12:56:06 GMT wallaby:phantomRunner Preparing sandbox [worker #0, session #rh8v3]
Wed, 30 Nov 2016 12:56:06 GMT wallaby:browserRunner Total files to load in sandbox: 1075
Wed, 30 Nov 2016 12:56:06 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #rh8v3]: http://localhost:51831/wallaby_sandbox0.html
Wed, 30 Nov 2016 12:56:06 GMT wallaby:phantomRunner Creating page for worker #0
Wed, 30 Nov 2016 12:56:06 GMT wallaby:phantomRunner Phantom page created
Wed, 30 Nov 2016 12:56:06 GMT wallaby:phantomRunner Prepared sandbox [worker #0, session #rh8v3]
Wed, 30 Nov 2016 12:56:06 GMT wallaby:workers Running tests in sandbox [worker #0, session #rh8v3]
Wed, 30 Nov 2016 12:56:06 GMT wallaby:middleware Preparing to serve /__modules/347.js
Wed, 30 Nov 2016 12:56:06 GMT wallaby:middleware Serving /__modules/347.js from cache
Wed, 30 Nov 2016 12:56:06 GMT wallaby:middleware Preparing to serve /src/app/consequences/consequences.component.spec.js.wbp.js
Wed, 30 Nov 2016 12:56:06 GMT wallaby:middleware Serving /src/app/consequences/consequences.component.spec.js.wbp.js from cache
Wed, 30 Nov 2016 12:56:06 GMT wallaby:workers Loaded 4 test(s)
Wed, 30 Nov 2016 12:56:13 GMT wallaby:workers Test executed: should not have any id before OnInit is called
Wed, 30 Nov 2016 12:56:16 GMT wallaby:workers Test executed: should retrieve consequence when OnInit is called
Wed, 30 Nov 2016 12:56:19 GMT wallaby:workers Test executed: should not have any stakeholder elements in the dom if no stakeholders are returned by service
Wed, 30 Nov 2016 12:56:19 GMT wallaby:workers Test executed: should contain 3 stakeholder elements when consequence have 3 stakeholders
Wed, 30 Nov 2016 12:56:20 GMT wallaby:workers Run 4 test(s), skipped 0 test(s)
Wed, 30 Nov 2016 12:56:20 GMT wallaby:workers Sandbox [rh8v3] is responsive, closing it
Finished executing 4 affected test(s)
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Test run finished
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Processed console.log entries
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Processed loading sequences
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Processed executed tests
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Processed code coverage
Wed, 30 Nov 2016 12:56:20 GMT wallaby:project Test run result processed and sent to IDE
Wed, 30 Nov 2016 12:56:20 GMT wallaby:uiService Outgoing message ui:summary
```

I don't think it have anything to do with the error, it is just if you can see from the log if I am doing something wrong.

**Comment by ArtemGovorov** [comment]
> Wallaby seems to work even when the error is there.

Ah, ok, it then just may be an error related to cancelling the test run (as a result of your subsequent changes), so if it doesn't cause any other issues, I wouldn't worry about it.

> Another thing I have noticed is that wallaby takes along time executing my tests. 

Thanks for the log. It does indeed look like the 4 tests took ~14 seconds to execute, however according to the log, it was the time consumed by the tests themselves.

Is there anything time consuming you're doing in those tests, or in `before`/`beforeEach` hooks? Are/were those 4 tests passing (or ending by jasmine timeout)?

If you could create a sample project with those 4 tests (or similar ones) taking that long, I'm more than happy to have look.

**Comment by FlemmingBehrend** [comment]
You are correct, it is the tests that takes the time. I have just startet using the web ui you have created for wallyby. I have to say wallaby is one of the best tools I have used so far, and I have used a lot of tools :+1: 

![image](https://cloud.githubusercontent.com/assets/1967934/20792236/0906a3d2-b7c1-11e6-820c-6a3e8acbe91e.png)

I think it has something to do with angular and creation of the TestBed in each test. The test for my domain model are very fast.

I have put the project [here](https://github.com/FlemmingBehrend/ngCliWebpackSample/tree/slow-tests). If you have the time to take a look I would really appreciate it.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the project, here's the numbers I have got:

![screen shot 2016-12-01 at 10 14 56 pm](https://cloud.githubusercontent.com/assets/979966/20793636/b0b00b26-b813-11e6-9521-df4aac8aace9.png)

So the numbers I'm getting are ok, but there's no `consequences.component.spec.ts` (that takes ~17 for you) in the shared project (and the rest of the tests look ok). Would it be possible to add it there?

**Comment by FlemmingBehrend** [comment]
Think you are running the master branch. I put all the test in the slow-test branch.

**Comment by FlemmingBehrend** [comment]
Have investigated some more, the big time consuming thing is material design. The import `MaterialModule.forRoot()` takes ~3 to import.

With `MaterialModule.forRoot()` imported:
![image](https://cloud.githubusercontent.com/assets/1967934/20794587/4a398a8e-b7cd-11e6-8e1d-01fb253d94ae.png)

Without `MaterialModule.forRoot()` imported:
![image](https://cloud.githubusercontent.com/assets/1967934/20794630/76ce8c20-b7cd-11e6-9746-1afe964be0ec.png)

I know the tests are now failing, but the initialization of the beforeEach block should be comparable.

**Comment by ArtemGovorov** [comment]
I can't yet reproduce the issue. Here's my results:

With `MaterialModule.forRoot()` imported:

![screen shot 2016-12-01 at 11 47 12 pm](https://cloud.githubusercontent.com/assets/979966/20796144/945130f6-b820-11e6-85ac-bbec5c8a5bb5.png)

Without `MaterialModule.forRoot()` imported:

![screen shot 2016-12-01 at 11 47 36 pm](https://cloud.githubusercontent.com/assets/979966/20796173/b635b322-b820-11e6-8b3e-4b94b816575a.png)

Try [disabling the parallelisation](https://wallabyjs.com/docs/config/workers.html) to see how it affects your environment:

```javascript
module.exports = function(wallaby) {
    return {
        ...
      workers: {initial: 1, regular: 1}
    };
};
```

**Comment by FlemmingBehrend** [comment]
I have tried to change to one worker but still have the very slow tests. 

![image](https://cloud.githubusercontent.com/assets/1967934/20796661/6f736e78-b7d7-11e6-96e3-0137520acc3c.png)

I will try the setup on another computer not connected to the company and without company software to see if I can recreate it there.

**Comment by ArtemGovorov** [comment]
It is indeed very slow. I'll also try to reproduce it on few other machines and profile what's going on there. Could you please also try [Electron runner](https://wallabyjs.com/docs/integration/electron.html) to see if the issue is PhantomJs specific or not?

**Comment by FlemmingBehrend** [comment]
I tried to create the setup from the [slow-tests](https://github.com/FlemmingBehrend/ngCliWebpackSample/tree/slow-tests) branch on my macbook with the following setup:

* Macbook (macOS sierra, 10.12.1)
* Webstorm (2016.3.1)
* Wallaby (initialised with two workers)

I got faster test execution times, but still a little slower than the ones you got. Tried to execute the test with phantomjs and electron, but no noticeable  difference.

With phantomjs:
<img width="770" alt="skaermbillede 2016-12-01 kl 16 05 25" src="https://cloud.githubusercontent.com/assets/1967934/20799426/76b5a6fa-b7e2-11e6-8373-b738f1ecf48a.png">

With electron:
<img width="767" alt="skaermbillede 2016-12-01 kl 16 23 39" src="https://cloud.githubusercontent.com/assets/1967934/20799481/9c16a2b4-b7e2-11e6-968f-29c77859791d.png">

Even through the tests are slow compared to test not using the TestBed, I think the problem must be internal in our company. I will try investigating virus scanners and other programs running on our machines.

Thanks for time you spend on helping me out.

**Comment by ArtemGovorov** [comment]
Thanks for checking and for the update! Virus scanners and IO performance are good candidates to check.

2-2.5 seconds for 5 tests still doesn't look great, so I have done some more investigation. 

I tried a few things and it looks like the issue with 2-2.5 seconds for 5 tests is [the angular 2 issue with the `TestBed.configureTestingModule`](https://github.com/angular/angular/issues/12409) that you've referenced already.

**Comment by ArtemGovorov** [comment]
Also it doesn't seem to be wallaby.js specific, karma is also giving me similar results if I run those 5 tests:

<img width="610" alt="screen shot 2016-12-02 at 3 59 25 pm" src="https://cloud.githubusercontent.com/assets/979966/20824453/a3c63986-b8a8-11e6-8a5b-c103cb2f96ae.png">

(and it's considering that karma is configured to run without code coverage collection, which adds some overhead)

So let's wait and see what angular 2 guys say/do about it, not much I can do from the wallaby side of things.
