### ISSUE TITLE
Uncaught ReferenceError: Zone is not defined​​ Angular-CLI w/ Wallabyjs

### ISSUE THREAD

**Issue by cuken** [wallabyjs/public#886]
### Issue description or question

I attempted to get Wallaby to work with an existing project I was working on. Not convinced it wasn't something in my project, I created a brand new project via angular-cli, installed wallaby, wallaby-webpack, and electron and tried to use the below config file. I keep getting a Uncaught ReferenceError: Zone is not defined​​ error. I've attached the Pastebin of the entire export.

http://pastebin.com/sXHAeGxM

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    env: {
      kind: 'electron'
    },

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Both
WebStorm v2016.3.1
Visual Studio Code v1.7.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Most likely reason is the missing `src/wallabyTest.ts` file, try adding one from [the sample](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) to see if it starts working for you. If not, please try getting the mentioned sample and running it to see if it works or not for you.
