### ISSUE TITLE
executed wallaby with typescript / ts-node

### ISSUE THREAD

**Issue by dweber019** [wallabyjs/public#892]
### Issue description or question
As you can see in https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack, there is a webpack.config.ts file and the repository has switched from using node to ts-node.

This breaks wallaby as wallaby doesn't know TS and the webpack config file is a TS file. Is there any way that wallaby can be executed with ts-node?

### Wallaby.js configuration file
One which is using the webpack plugin

### Code editor or IDE name and version
N/A

### OS name and version
N/A

**Comment by ArtemGovorov** [comment]
You [may use `ts-node` and `require` `.ts` files](https://github.com/wallabyjs/public/issues/552) from the wallaby config: 
```javascript
require('ts-node').register({
    compilerOptions: {
        module: 'CommonJS',
    },
})

// now you may `require` .ts webpack config
```

P.S. If you hit an issue like `SyntaxError: Unexpected token !`, you may use [the code from this comment](https://github.com/wallabyjs/public/issues/552#issuecomment-261694949).

**Comment by dweber019** [comment]
Works! Thanks
There "Unexpected token" is already implemented as I had that issue previously ;)
