### ISSUE TITLE
VSCode: Show popup window for inline console.log output

### ISSUE THREAD

**Issue by xsintill** [wallabyjs/public#893]
### Issue description or question
Using console.log to print out an object wallaby should show a popup window with all it's values instead of a line of text being cut off with ellipsis. VSCode does something similar when in debug mode hitting a breakpoint one can hover over code and a popup window will be shown with the objects value

### Code editor or IDE name and version
Visual Studio Code v1.7.2

### OS name and version
Windows 7

**Comment by ArtemGovorov** [comment]
You may use the `Show line tests` wallaby command on the line with the `console.log` to display the output. It's not exactly the debugging popup (which VS Code API only allows using when developing a debugger), but does the trick.

**Comment by ArtemGovorov** [comment]
Forgot to add: here's the command description in wallaby for VS Code tutorial: https://wallabyjs.com/docs/intro/get-started-vscode.html#commands.
