### ISSUE TITLE
TypeError: null is not an object (evaluating 'testProxyZone.run')​​

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#894]
Hi Artem,

I'm getting the above error and not sure where to start. Tests run successfully in Karma. I am using your standard angular-cli config.

Can you offer any guidance?

regards,
Dave

**Comment by ArtemGovorov** [comment]
If you're using the config from here: https://github.com/wallabyjs/ngCliWebpackSample, then the most likely reason is the missing `src/wallabyTest.ts` file, try adding one from [the sample](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) to see if it starts working for you. If not, please try getting the mentioned sample and running it to see if it works or not for you.

**Comment by zpydee** [comment]
I'm using the same configs as your sample, including the wallabyTest.ts configuration. Herewith for your comment:

(I noticed you didn't have the env setup in your sample so i commented that out, but problem persists)

WALLABY.JS
```
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/test.wallaby.js',
    'src/app/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    // env: {
    //   runner: require('phantomjs-prebuilt').path,
    //   params: {runner: '--web-security=false'}
    // },

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

TEST.WALLABY.TS
```
import './polyfills.ts';

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';


let testing = require('@angular/core/testing');
let testingBrowser = require('@angular/platform-browser-dynamic/testing');

testing.getTestBed().initTestEnvironment(
    testingBrowser.BrowserDynamicTestingModule,
    testingBrowser.platformBrowserDynamicTesting()
);

```

**Comment by ArtemGovorov** [comment]
Does [this sample](https://github.com/wallabyjs/ngCliWebpackSample) (as is) work for you?

**Comment by zpydee** [comment]
no, same issue occurs. do you think it could be from angular-cli updates?

**Comment by zpydee** [comment]
also, the error only occurs with one of my spec files, which might be a clue. i think i'll see if i can isolate the spoecific spec causing the error

**Comment by ArtemGovorov** [comment]
I have just updated the sample to use the latest `angular-cli` beta.22 (and pushed the update) and it's working for me. It was working for me before the update though.

I have searched for the `testProxyZone.run` in `node_modules` and the only place where the error could be coming from is `node_modules/zone.js/dist/jasmine-patch.js`, line 102/104, if the `testProxyZone` wasn't initialised at the line 122. Not yet sure how is it possible, because it wouldn't work in karma either if there was something wrong with the `zone.js/jasmine-patch.js`.

**Comment by ArtemGovorov** [comment]
> also, the error only occurs with one of my spec files

So, given [the sample](https://github.com/wallabyjs/ngCliWebpackSample) is not working for you either, which test of the only spec file of the sample does it fail on?

**Comment by zpydee** [comment]
i'm exploring. i must conclude this isn't a wallaby problem but rather a PEBKAU (problem exists between keyboard and user) :-)

I'll shout if I get stuck but as always thanks for your assistance.

**Comment by ArtemGovorov** [comment]
No worries, please also let me know if you find the reason.

**Comment by zpydee** [comment]
I believe I have found the issue. It appears wallaby does not like empty specs with the angular-clie configuration, i.e:

```
it('should be a note for a future spec i want to write');
```

I often use this approach when scaffolding out my requirements...

**Comment by ArtemGovorov** [comment]
Are you sure it is the issue? Because:
- the sample doesn't even have empty specs,
- `karma` doesn't work in such cases either.

**Comment by zpydee** [comment]
if I comment out the empty spec, wallaby is happy, if not, I get the error. Karma is happy in both cases. have you tried adding an empty spec to your sample?

**Comment by ArtemGovorov** [comment]
> have you tried adding an empty spec to your sample?

Yes, here's what I get from `karma` if I add the empty test
```
it('should be a note for a future spec i want to write');
```
to the `src/app/app.component.spec.ts` file:

```
Chrome 54.0.2840 (Mac OS X 10.12.0) AppComponent encountered a declaration exception FAILED
        TypeError: Cannot read property 'length' of undefined
            at wrapTestInZone (webpack://///ngCliWebpackSample/~/zone.js/dist/jasmine-patch.js?:101:25)
            at Env.jasmineEnv.(anonymous function) [as it] (webpack://///ngCliWebpackSample/~/zone.js/dist/jasmine-patch.js?:72:28)
            at Suite.eval (webpack://///ngCliWebpackSample/src/app/app.component.spec.ts?:30:5)
            at ZoneDelegate.invoke (webpack://///ngCliWebpackSample/~/zone.js/dist/zone.js?:232:26)
            at Zone.run (webpack://///ngCliWebpackSample/~/zone.js/dist/zone.js?:114:43)
            at Suite.eval (webpack://///ngCliWebpackSample/~/zone.js/dist/jasmine-patch.js?:89:29)
            at Env.jasmineEnv.(anonymous function) [as describe] (webpack://///ngCliWebpackSample/~/zone.js/dist/jasmine-patch.js?:66:38)
```

Looking into the [`zone.js/dist/jasmine-patch.js`](https://github.com/angular/zone.js/blob/master/dist/jasmine-patch.js#L101), it makes sense because the passed `testBody` is the second argument of the [`it` test function that is replaced](https://github.com/angular/zone.js/blob/master/dist/jasmine-patch.js#L72) by the `jasmine-patch.js`, so it fails in karma as well for me. I'm really puzzled how is works for you in karma.

**Comment by zpydee** [comment]
yes, i stand corrected - just tested the same. i only really use karma in travis - wallaby is my primary tooling for specs. it previously had the empty spec as an xit, which is why i never noticed it, but even with xit, wallaby still gives the error.

**Comment by zpydee** [comment]
weird, i'm getting the same error with xit in karma now as well. i'm sure i wasn't previously. oh, well...

**Comment by ArtemGovorov** [comment]
> weird, i'm getting the same error with xit in karma now as well. i'm sure i wasn't previously.

Yes, I'm getting the same error with `xit` as well - [the `zone.js/dist/jasmine-patch.js` is replacing `it`, `xit`, `fit`](https://github.com/angular/zone.js/blob/master/dist/jasmine-patch.js#L69).

So it is not wallaby breaking on the empty spec function, but the `zone.js/dist/jasmine-patch.js`, so I suggest to create an issue in the angular.js repo. In meantime, perhaps using:
```javascript
it('should be a note for a future spec i want to write', () => {});
```
could work for you?

**Comment by zpydee** [comment]
yes, this is what i've done. sorry to have consumed your time for nothing

**Comment by ArtemGovorov** [comment]
It's ok, glad the issue is sorted out and there's a solution/workaround.
