### ISSUE TITLE
Automatically pick up .wallaby.js .wallaby.json or .wallaby.conf.js as config

### ISSUE THREAD

**Issue by HCanber** [wallabyjs/public#895]
The docs mentions recommended names that seems to be detected automatically by Wallaby the first time it's run:

> Recommended names are `wallaby.js/wallaby.json` or `wallaby.conf.js`.

Since config-files often start with a `.`, for example `.editorconfig`, `.eslintrc`, `.npmignore` it would be great if that could be used for Wallaby's config files as well.

So wallaby.js would automatically pick up `wallaby.js/wallaby.json`, `.wallaby.js/.wallaby.json`, `wallaby.conf.js` or `.wallaby.conf.js`

**Comment by ArtemGovorov** [comment]
> The docs mentions recommended names that seems to be detected automatically by Wallaby the first time it's run

It's true, but only for some supported editors. Some still require to select a config explicitly. Which editor are you using if I may ask?

**Comment by HCanber** [comment]
I'm using VS Code 1.7.2 on OSX

**Comment by ArtemGovorov** [comment]
Implemented and published in the VS Code extension 1.0.32.
