### ISSUE TITLE
Jasmine timeout somehow used in Jest tests?

### ISSUE THREAD

**Issue by yedidyak** [wallabyjs/public#896]
I have two Wallaby configs, one for Jasmine and one for Jest.

`wallabyJest.js`: 
```
const babelOptions = {
  "presets": [
    "es2015",
    "stage-0",
    "react"
  ]
};

module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    files: [
      'src/**/*.js',
      '!src/**/*.test.js'
    ],

    tests: [
      'src/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel(babelOptions)
    },

    setup: function (w) {
      require('babel-polyfill');
    }
  };
};
```

When I run a test using that config, if it fails by a timeout I get the following message in the console:

```
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

I can't see where to change the default timeout, nor why it's taking a jasmine environment var.

If I change that var in the test itself, for example bu putting `jasmine.DEFAULT_TIMEOUT_INTERVAL = 10` in `beforeEach()`, it uses the changed value, but I can't find a way t set it globally.

Am I missing something?

**Comment by ArtemGovorov** [comment]
`Jest` is using jasmine behind the scenes so yes, it does use Jasmine timeout. You may configure `jest` to increase the timeout globally as [described in the `jest` repo](https://github.com/facebook/jest/issues/652), for example by creating a `jestSetup.js` file with the increased timeout:
```javascript
jasmine.DEFAULT_TIMEOUT_INTERVAL = 10000;
```
 and making it `jest` `setupTestFrameworkScriptFile`:
```javascript
module.exports = function(wallaby) {
  return {
    ...
    setup: function (w) {
      ...
      w.testFramework.configure({
         setupTestFrameworkScriptFile: '<rootDir>/jestSetup.js'
      });
    }
  };
};
```

**Comment by sudhanshuraheja** [comment]
5000 works well as a global config, if you want to change the timeout for a specific test, please do this

    test("test an API which takes time", () => {

        doYourThing()

    }, 10000)

**Comment by kachkaev** [comment]
@sudhanshuraheja does this work for both sync and async tests? I could not use timeout for potentially long-running sync jobs – these tests never caused a timeout:

```js
test("sync test", () => {
    const result = slowSyncFunction();
    expect(result).toEqual(42);
}, 10)
```
This works though:

```js
test("async test", async () => {
    const result = await slowAsyncFunction();
    expect(result).toEqual(42);
}, 10)
```

If timeouts for sync stuff are not supported by design, how can be the efficiency of sync code tested in jest then?

**Comment by ArtemGovorov** [comment]
@kachkaev I don't think Jest (or any test runners, except for Wallaby.js) can detect timeouts in long-running sync tests.
