### ISSUE TITLE
Using Wallaby with Babel in Aurelia-CLI

### ISSUE THREAD

**Issue by spapaseit** [wallabyjs/public#897]
### Issue description or question
I have an aurelia-cli application, based on `ESNext` and using `Babel` as a transpiler. The whole thing runs from VS2015 in as ASP.NET Core app.

I have tried setting up Wallaby based on issue #784, but I get several errors when starting wallaby, amongst which:

`​​​​​Uncaught Error: Module name "aurelia-polyfills/aurelia-polyfills" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded`
and
`Uncaught Error: Module name "../setup" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded`

Could you maybe point me in the right direction?

### Wallaby.js configuration file
I have created a stripped down version of my repo; the `wallaby.js` config file can be found at:
https://github.com/spapaseit/aurelia-cli-wallaby-babel/blob/master/wallaby.js

And this is the url of the repo:
https://github.com/spapaseit/aurelia-cli-wallaby-babel

### Code editor or IDE name and version

Visual Studio 2015
### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Your karma config doesn't seem to work either, not sure it's supposed to, but it would be easier to troubleshoot/compare if it was working. 

The main issue is the setup is using AMD/require.js for testing and your babel compiler is not configured to transform modules to AMD. If you add the same babel plugin as used in the [aurelia.json](https://github.com/spapaseit/aurelia-cli-wallaby-babel/blob/270f2006f883e0177df228c6079f09f782498edf/aurelia_project/aurelia.json#L16):
```javascript
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: [...],
        plugins: [
          ...
          "transform-es2015-modules-amd" // <--
        ]
      })
    },
```
then the issue should be resolved.

I have noticed however another issue with loading `jquery` popping up next. To fix it, you'll need a slightly modified `setup` function to close follow [the way aurelia resolves external libs](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/the-aurelia-cli/6).

```javascript
    setup: (function (wallaby) {
      wallaby.delayStart();

      requirejs.config({
        packages: [
          // packages
        ]
      });

      require(["test/unit/setup.js"].concat(wallaby.tests), function () {
        wallaby.start();
      });
    }).toString().replace("// packages", aureliaJson.build.bundles[1].dependencies.reduce(function (prev, curr) {
      var moduleName, modulePath, moduleMain;
      if (curr.path) {
        moduleName = moduleMain = curr.name;
        modulePath = path.relative(
          __dirname,
          path.resolve(__dirname, "aurelia_project", curr.path))
          .split('\\').join('/');
        if (curr.main) {
          moduleMain = curr.main;
        }
      }
      else {
        moduleName = curr;
        var packageJson = require(__dirname + '/node_modules/' + moduleName + '/package.json');
        if (packageJson.jspm) {
          moduleMain = packageJson.jspm.main;
          modulePath = 'node_modules/' + moduleName + '/' + packageJson.jspm.directories.dist;
        }
        else {
         // <-- handling non jspm modules
          moduleMain = path.basename(packageJson.main, '.js');
          packageJson.main = packageJson.main.split('/');
          packageJson.main.pop();
          modulePath = 'node_modules/' + moduleName + '/' + packageJson.main.join('/');
        }
      }
      return prev
        + '{ name: ' + JSON.stringify(moduleName)
        + ', location: ' + JSON.stringify(modulePath)
        + ', main: ' + JSON.stringify(moduleMain)
        + '},';
    }, ''))
```

Please note that it's just a basic implementation of that the aurelia docs say, and may require modifications/additions. Unfortunately it doesn't seem possible to re-use any code/module from aurelia to do this, but I'd be happy to be proved wrong if someone finds it and points an easier way.
