### ISSUE TITLE
Support webpack

### ISSUE THREAD

**Issue by ArtemGovorov** [wallabyjs/public#9]

**Comment by okonet** [comment]
:+1:

**Comment by irium** [comment]
+1

**Comment by okonet** [comment]
I believe this is now supported via preprocessors?

**Comment by ArtemGovorov** [comment]
I haven't tried webpack specifically yet, it may be already possible to use it via preprocessors, I'm just not familiar with its API.

**Comment by okonet** [comment]
I'll try it today and let you know if it worked...

**Comment by ArtemGovorov** [comment]
Awesome, thanks.

**Comment by jeffling** [comment]
It would be pretty simple to set it up with webpack, but it's trickier than just using the webpack command if we want to take advantage of webpack-dev-middleware and so on. 

I also just did https://github.com/jeffling/wallaby-vinyl-adapter so theoretically you could use gulp-webpack maybe? It's still very raw so I expect to see some huge omissions :)

**Comment by okonet** [comment]
@sokra told me what karma-webpack is a one big hack... But at least it works.

**Comment by jeffling** [comment]
So using the gulp-webpack plugin seemed to be the easiest route for me, since any plugin I made was going to use memoryfs anyways probably. 

I got it close, but with one big blocker:

```
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Applications/IntelliJ IDEA 14.app/Contents/bin/src/ui/pdfViewer/pdfViewerService.spec.coffee in /Applications/IntelliJ IDEA 14.app/Contents/bin
```

So I hardcoded the 'context' in webpack config, which I really don't want to do in my actual project, but still no go:

```ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' /Applications/IntelliJ IDEA 14.app/Contents/bin/src/app/ta/ta.spec.coffee in /Users/jeff/Work/benchception/rind/git
```

I tried to remove the the intellij stuff by doing `file.path.replace(process.cwd(), '')` in the vinyl adapter, but still I get the above error multiple times.

I think things could be easier if the command runs in the context of the project dir as opposed to intellij's bin. @ArtemGovorov What do you think about that? 

Any luck on your end, @okonet?

**Comment by jeffling** [comment]
I got webpack emitting! by hardcoding the absolute path of the directory into vinyl-adapter.... Not an idea solution :) 

[11:04:31] Version: webpack 1.5.3
                  Asset     Size  Chunks             Chunk Names
7703d88c6c37d60774e3.js  1202972       0  [emitted]  main

**Comment by ArtemGovorov** [comment]
@jeffling I have changed the working directory to be the project working dir. So now project.cwd() will return the project directory and hopefully file resolution should work. Also, I have added a first parameter to the configuration function, that contains `localProjectDir` property, returning the project dir:
```javascript
module.exports = function (wallaby) {
  console.log(wallaby.localProjectDir);
  return {...};
};
```

Please let me know if I can change or add anything else  to make it easier. 

So, it seems like it's almost working with gulp-webpack + wallaby-vinyl-adapter? Do you have some sample webpack project with vinyl-adapter and wallaby config somewhere that I can try? Perhaps we could recommend it as the official way to run webpack with wallaby.

@okonet @sokra @jeffling  from my brief look into webpack, it seems it can be configured something like:

```javascript
var webpack = require('webpack');

var compiler = webpack({
  entry: {
    pageA: "./pageA",
    pageB: "./pageB",
    shared: "./shared",
    common: "./common"\
    // list of files here that I can if needed expose from wallaby API
  },
  output: {
    path: require('path').join(__dirname, "js"),
    filename: "[name].js"
  },
  plugins: [new webpack.optimize.CommonsChunkPlugin({
    filename: 'init.js',
    minChunks: Infinity
  })]
});
```
so that it emits 1 self-sufficient file per each project file and 1 init.js file that can be included before everything else. Production project configuration should obviously use better bundle set up, but for tests - it's ideal. 

I am assuming that this way it should probably be possible to create the compiler once and then somehow invoke in from preprocessor to re-compile only changed files? Not sure how well webpack internal caching would work in this case.

Your thoughts?

**Comment by jeffling** [comment]
@ArtemGovorov I'll see how far I can get tonight - hard to find time during the weekday. 

Re: your idea, it would be really cool if in the beginning of wallaby run, the entry is set by wallaby, but watching is done by webpack so we can take advantage of all the cool stuff webpack can do. If the 'done' callback can be called at any time, multiple times, we could probably make it work without any other changes to the api.

**Comment by ArtemGovorov** [comment]
@jeffling Delegating watcher to webpack seems like a big change and a bit like a hack: 
- wallaby.js uses code editor infrastructure for file watching (it does some efficient smarts like file moving and renaming). Turning it off and using webpack notifications may works but will require some changes and possibly some webpack changes as wallaby needs more than just content of the file.
- wallaby.js has to get the file content first to modify (instrument) it, before any other changes - otherwise coverage just won't work - source maps is not enough for code coverage.

Regarding common chunk plugin causing all tests to have to be rerun on changes to a lot of common things - not sure, why? Wallaby.js tracks dependencies between files and only loads and runs those test files into sandbox that are affected by changes. So it something that is used in all test files has changed - then of course all the tests run, but it's expected.

**Comment by jeffling** [comment]
@ArtemGovorov My last comment was on the assumption that webpack would be in charge of watching. I may actually be wrong in that too - webpack watching might be better than I give it credit for. 

In that case, we could try to find some other way keep one compiler and trigger it at the right time, but I'm not sure how it's going to work if we pre-populate the entries. Another idea would be to make a new compiler for each test file, cache them, then just trigger them with `compiler.run` when wallaby sends a file again.

**Comment by ArtemGovorov** [comment]
@jeffling Ok, thanks for clarifying. I may try some of the ideas later. Thanks for your time and ideas, please keep posting your findings and results as well, whenever you have some time of course.

**Comment by jeffling** [comment]
@ArtemGovorov I set up a repo at jeffling/wallaby-webpack with my simple config and a dev environment to try the ideas. I ended up extracting stuff out of gulp-webpack, because there were some problems and the logic was pretty simple anyways. Having a separate repo lets us try some caching strategies we couldn't do with gulp-webpack anyways. 

If anybody else would like push access just let me know. I have to go back to my day job now :)

**Comment by ArtemGovorov** [comment]
@jeffling cool, thanks!

**Comment by ArtemGovorov** [comment]
I think I'm close to have something working for webpack, could you please recommend an OSS project or projects using webpack with significant number tests so that I could test my solution?

**Comment by jeffling** [comment]
@ArtemGovorov  https://github.com/jlongster/transducers.js only one test file, but lots of tests in that file

**Comment by jeffling** [comment]
@ArtemGovorov hey, wondering how the webpack thing is going, and if you need any help at all?

**Comment by ArtemGovorov** [comment]
@jeffling I almost got it working, will push the first version into https://github.com/jeffling/wallaby-webpack in a couple of days or so. It'll need some testing on some real-world scenarios and I'd certainly appreciate a code review. 

One thing I have noticed: you're using CoffeeScript in the wallaby-webpack repo example, and CoffeeScript is not supported by wallaby yet. It can be transpiled in wallaby preprocessors and by webpack loaders, but coverage for CS files will only be supported once wallaby [supports its instrumentation](https://github.com/wallabyjs/public/issues/49).

**Comment by jeffling** [comment]
Ah, so that makes sense why I wasn't getting anywhere and why it worked better when I used js. Thanks, I'll be on the lookout for that.

**Comment by ArtemGovorov** [comment]
Everyone is welcome to try the first version of webpack support: https://github.com/jeffling/wallaby-webpack
