### ISSUE TITLE
Inline console logging not showing in Sublime Text v3

### ISSUE THREAD

**Issue by bZichett** [wallabyjs/public#900]
Is inline `console.log` functionality available in Sublime 3?  

The intellij plugin works great for me, but after I suggested my brother pick up a license for sublime, we're finding it's less functional.  The value of the `console.log` seems to not show inline but only at the bottom left corner of the screen, as some type of "info" value (?), when the caret is on the line with the `console.log`.  Is this the intended behavior, or are we doing something wrong with configuration?  

This is a killer feature of wallaby that I get a lot of use out of.  We really would like this to work!

### Wallaby.js configuration file

```javascript
// exact config from calculator-sample
```

### Code editor or IDE name and version

Sublime Text v3 build 3126

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
There's nothing wrong with your configuration, the functionality is only available in the status bar (not inline), as described in [our Sublime Text tutorial](https://wallabyjs.com/docs/intro/get-started-sublime.html#wallabyjs-in-action). We'd love to add the support, but editor integration wise we can only go as far as the editor plugin API allows, and inline messages are not supported in Sublime Text plugins API.

We have the issue filed internally and if something changes and we can add the feature, we'll definitely do it.

**Comment by ArtemGovorov** [comment]
Great news, [we've found a way to make inline messages work in Sublime Text 3](https://twitter.com/wallabyjs/status/808975647737401345): 
![sb](https://cloud.githubusercontent.com/assets/979966/21177871/c0dd452a-c238-11e6-92d8-5c1dc9728c3e.gif)

**Comment by fvanwijk** [comment]
Why not make it `true` by default?

**Comment by ArtemGovorov** [comment]
The feature is in its early stages in Sublime Text, and may need some more ironing (based on the users feedback). We'll make the `inlineMessages` flag `true` by default eventually after some time.

**Comment by bZichett** [comment]
Christmas comes early, eh?  Awesome work Artem.
