### ISSUE TITLE
Calculator Test Project not working

### ISSUE THREAD

**Issue by investor-analytics** [wallabyjs/public#902]
### Issue description or question

I am having lots of trouble even running the calculator test project in Visual Studio Code..
All I get when issuing the wallaby start command is the spinner. 
When I look at the wallaby console output it just shows

​​​​​[Info]​​​​​ Node Commands
​​​​​[Info]​​​​​ 
​​​​​[Info]​​​​​ Syntax:
​​​​​[Info]​​​​​     node {operator} [options] [arguments]
​​​​​[Info]​​​​​ 
​​​​​[Info]​​​​​ Parameters:
​​​​​[Info]​​​​​         /? or /help   - Display this help message.
​​​​​[Info]​​​​​         list          - List nodes or node history or the cluster
​​​​​[Info]​​​​​         listcores     - List cores on the cluster
​​​​​[Info]​​​​​         view          - View properties of a node
​​​​​[Info]​​​​​         online        - Set nodes or node to online state
​​​​​[Info]​​​​​         offline       - Set one or more nodes to the offline state
​​​​​[Info]​​​​​ 
​​​​​[Info]​​​​​ For more information about HPC command-line tools,
​​​​​[Info]​​​​​ see http://go.microsoft.com/fwlink/?LinkId=120724.

I would expect (probably) to see it trying to find the javascript test files.

So firstly

1. what is the command to get the wallaby console running when its not showing?
2. I need to be able to show the output on the console when I start wallaby - I just get some nebulous node output at present
3. How can I load the tests properly so that I get the green/red icons and I can start writing some proper tests!

I am unable to get this package running on any project I try and use which is a shame because it looks as though it will help me to test my angular 2 project easily.

### Wallaby.js configuration file

module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};

```javascript

```

### Code editor or IDE name and version
Visual Studio Code v1.7.2
![wallaby capture](https://cloud.githubusercontent.com/assets/22916653/21093996/a6772ca2-c04c-11e6-80dd-0626c5268de0.PNG)

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Wallaby.js requires [node.js](http://nodejs.org/) to run, and in VS Code by default it runs `node` command expecting it to your system installed node.js version. However, in your case it looks like `node` command is mapped to other program (returning the output you see).

If you don't like to re-map the command to node.js, you may set the path to your system installed node.js in [the extension settings](https://wallabyjs.com/docs/intro/install.html#nodejs-2).
