### ISSUE TITLE
Wallaby + webpack + typescript + custom loaders

### ISSUE THREAD

**Issue by wojciak** [wallabyjs/public#903]
### Issue description or question
When I try to configure wallaby with webpack and typescript I get errors regarding module parsing of extra loaders (like require('my.html') or require('my.css')) - it seems that wallaby runs the typescript compilation before the webpack loader bundle which in turn throws these errors.

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackConfiguration = require('./webpack.config');

webpackConfiguration.entry = {};
webpackConfiguration.entryPatterns = ['app/app.js', 'test/index.js', 'test/**/*.spec.js'];

module.exports = function (wallaby) {
  webpackConfiguration.resolve.root = wallaby.projectCacheDir;
  webpackConfiguration.resolve.extensions = ['', '.js'];

  return {
    files: [
      { pattern: 'app/**/*.*', load: false },
      { pattern: 'test/index.js', load: false },
      { pattern: 'test/mocks/**/*.js', instrument: false }
    ],
    tests: [
      { pattern: 'test/**/*.spec.js', load: false }
    ],
    env: {
      kind: 'electron'
    },
    testFramework: 'jasmine',
    postprocessor: wallabyWebpack(webpackConfiguration),
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v11
### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> it seems that wallaby runs the typescript compilation before the webpack loader bundle

Wallaby does indeed run TS compilation before webpack, but it shouldn't cause any issues. You may need to [remove the ts-loader](https://wallabyjs.com/docs/integration/webpack.html#loaders-vs-preprocessorscompilers) from the list of loaders in your wallaby config (from the `webpackConfiguration.loaders` array).

> I get errors regarding module parsing of extra loaders

What errors are you getting? Any chance you could share a sample where I could have a look?

**Comment by wojciak** [comment]
Hi Artem - thank you for the quick reply! 

I've prepared a little repo to illustrate the issue: https://github.com/wojciak/wallabyjs-webpack-typescript

The errors that I get:

1. ```javascript
ModuleParseError: Module parse failed: ./app/template.html Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
```

2 ```javascript
ModuleParseError: Module parse failed: ./app/style.scss Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
```

3 ```javascript
Uncaught SyntaxError: Unexpected token import
  at app/oldModule.js:1
```

**Comment by ArtemGovorov** [comment]
Thanks for the repo. 

The first 2 errors were related to the absolute path supplied to the loaders `include`. You may either re-map them to [point to the wallaby cache](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) or just remove the `include` path like I did in the config below.

The third error is tricky. You'd like your JavaScript files (like `app/oldModule.js`) to be compiled by the TS compiler, is it correct? If you rename them to `.ts`, it'd be the best/easiest option. You you can not, you may configure TS compiler to include them, and add the `suppressOutputPathCheck` option. Unfortunately this way I had to also set `instrument: false` to make it work, but I'll have a deeper look tomorrow if it can be avoided.

```javascript
const wallabyWebpack = require('wallaby-webpack');

module.exports = function (wallaby) {
  const webpackConfiguration = require('./webpack.config');

  webpackConfiguration.entry = {};
  webpackConfiguration.resolve.extensions = ['', '.js'];
  webpackConfiguration.entryPatterns = ['app/app.js', 'test/index.js', 'test/**/*.spec.js'];
  webpackConfiguration.resolve.root = wallaby.projectCacheDir;
  webpackConfiguration.module.loaders.shift();
  webpackConfiguration.module.loaders.forEach(l => {
    delete l.include;
  });

  return {
    files: [
      { pattern: 'app/**/*.js', load: false, instrument: false },
      { pattern: 'app/**/*.ts', load: false },
      { pattern: 'app/**/*.html', load: false },
      { pattern: 'app/**/*.scss', load: false },
      { pattern: 'test/index.js', load: false }
    ],

    tests: [
      { pattern: 'test/**/*.spec.js', load: false }
    ],
    testFramework: 'jasmine',
    env: {
      kind: 'electron'
    },
    compilers: {
      'app/**/*.js': wallaby.compilers.typeScript({
        "target": "es5",
        "module": "commonjs",
        "allowJs": true,
        "suppressOutputPathCheck": true
      })
    },
    postprocessor: wallabyWebpack(webpackConfiguration),
    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

**Comment by wojciak** [comment]
It's alive - thank you! 

We're slowly migrating to .ts and wallaby is helping a ton - we don't need instrumentation on the .js part of things so only look into it if you really really want to :)

Awesome support as always! 👍

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
