### ISSUE TITLE
CoffeeScript file called API.coffee is not compiled

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#906]
### Issue description or question

Look at the screenshot below and you'll see the API.coffee file in the instrumented folder

![image](https://cloud.githubusercontent.com/assets/656739/21190164/e0476190-c218-11e6-9f32-a632ee0ffafd.png)

The ```_API.coffee``` and ```_API.js``` files are a test that I did just copy creating a copy of the current ```API.coffee``` file

Any ideas?

### Wallaby.js configuration file

```javascript
module.exports = (wallaby)->
  console.log wallaby

  just_Load = (file)->
    return { pattern: file, instrument: false, load: true, ignore: false }
  config =
    files : [
      just_Load 'bower_components/angular/angular.js'
      just_Load 'bower_components/angular-route/angular-route.js'
      just_Load 'bower_components/angular-mocks/angular-mocks.js'

      just_Load 'bower_components/jquery/dist/jquery.min.js'

      # weird bug where chai will load from node_modules but not from bower_components
      #{pattern: 'bower_components/chai/chai.js', instrument: true},
      just_Load  'node_modules/chai/chai.js'
      './src/**/*.coffee'
      './.dist/js/templates.js'
      './data/**/*.coffee'
    ]
    tests : [
      './test/**/*.coffee'
    ]

    bootstrap:  ()->
      window.expect = chai.expect;
  

  return config
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by DinisCruz** [comment]
This is weird, after renaming **API.coffee** to **API2.coffee** and then back to **API.coffee** the expected **API.js** file is there now

![image](https://cloud.githubusercontent.com/assets/656739/21190347/5a20cbb4-c219-11e6-9545-3718b9327175.png)

**Comment by ArtemGovorov** [comment]
Perhaps it's a caching issue. Try changing your wallaby config (even a space in the file will do) and restarting it to see if the issue goes away.
