### ISSUE TITLE
Unable to use local Typescript version

### ISSUE THREAD

**Issue by MrCrimp** [wallabyjs/public#908]
### Issue description or question
I'm using (locally installed) typescript@2.1.1 (in my node_modules) & VsCode 1.8.

VsCode has no problem with the object rest/spread syntax.
Wallaby cannot compile Object rest/spread code.
Tests without Object rest/spread syntax executes fine.
Tests using ts-node/Typescript 2.1 are running fine under mocha. 

I've verified that typescript version in `wallaby.projectCacheDir/node_modules` is 2.1.1

Setup function seems to log 2.0.7, no matter what.
Tried direct path require-ing node_modules/typescript/lib, installing typescript globally etc

console.log('Wallaby ts version:', require('typescript').version); // 2.0.7

Additional notes:
- setting NODE_PATH manually
- using importhelpers
- using baseUrl + paths
- using typeRoots due to inconsistent typescript behaviour with `@types`

### Wallaby.js configuration file

```javascript

'use strict';

module.exports = function (wallaby) {

  // Inform wallaby of where to start the require and import paths
  // we are using relative imports with TypeScript baseUrl, eg import * as x from  'app/module'
  var path = require('path');
  process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;

  return {

    files: [

      'app/**/*.ts*',

      { pattern: 'app/**/*.test.ts*', ignore: true }

    ],

    tests: [      
      
      'app/**/*.test.*'

    ],

    compilers: {

      '**/*.ts*': wallaby.compilers.typeScript()
    
    },

    preprocessors: {

      // ensure that any import/require of SASS returns empty string under test
      "**/*.scss": file => ""

    },

    env: {
      type: "node"
    },
    
    debug: true,
    
    testFramework: "mocha",

    workers: {
      recycle: true
    },
    
    delays: {
      run: 500
    },

    setup: function (w) {

      // patch node/jsdom with ES2015 features
      require('babel-polyfill')

      // whenever a module requires a .sass file, patch require() so it always returns empty object
      require.extensions['.scss'] = () => {};

      // setup jsdom to emulate global browser properties
      require('jsdom-global')();

      console.log('Wallaby ts version:', require('typescript').version); //always 2.0.7
    }

  };

};

```

### tsconfig.json
```json
{
  "compilerOptions": {
    
    "moduleResolution": "node",        
    "target": "es5",
    "jsx": "react",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "importHelpers": true,
    "allowJs": false, 
    "noImplicitAny": true,
    "noImplicitReturns": true,

    "outDir": "__ts-compiled__",

   "typeRoots": [
      "node_modules/@types"
    ],

    "lib": [
      "es2015", "dom"
    ],
    
    "baseUrl": ".",

    "paths": {
      "*": [
        "*"
      ]
    }
  },
  
  "exclude": [
      "bin",
      "obj",
      "node_modules",
      "wwwroot",
      "dist",
      "server",
      
  ],

  "typescript.tsdk": "./node_modules/typescript/lib"
}

```

### Code editor or IDE name and version

Visual Studio Code v1.8

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
When doing
```javascript
console.log('Wallaby ts version:', require('typescript').version);
```
in the `setup` function, the `2.0.7` is expected because in this case wallaby.js embedded version is resolved. 

However, the `setup` function runs in the context of a test runner process and the TypeScript compilation is done earlier in a different context. I suspect that setting `process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;` makes wallaby to resolve the typescript incorrectly.

If you do:
```javascript
'use strict';

module.exports = function (wallaby) {

  console.log('Wallaby ts version:', require('typescript').version);

  // Inform wallaby of where to start the require and import paths
  // we are using relative imports with TypeScript baseUrl, eg import * as x from  'app/module'
  var path = require('path');
  process.env.NODE_PATH += path.delimiter + wallaby.projectCacheDir;

  return {

    ...

  };

};
```
does it print the correct version? If it does, try [passing the correct version to the compiler](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-version) settings:

```javascript
'use strict';

module.exports = function (wallaby) {
  var ts = require('typescript');
  ...
  return {

    ...
    compilers: {
        '**/*.ts*': wallaby.compilers.typeScript({
            typescript: ts
        })
     }

  };

};
```

or, what may be an overkill but should 100% work, try specifying an absolute path to the local TypeScript:

```javascript
'use strict';

module.exports = function (wallaby) {
  var path = require('path');
  var ts = require(path.join(wallaby.localProjectDir, 'node_modules/typescript'));
  ...
  return {

    ...
    compilers: {
        '**/*.ts*': wallaby.compilers.typeScript({
            typescript: ts
        })
     }

  };

};
```

Either way, please let me know what is printed when you move the `console.log` up in the config, and which solution had worked for you, if any.

**Comment by MrCrimp** [comment]
On windows this works and if I pass ts as {typescript: ts} 

```
 ts = require(path.join(wallaby.localProjectDir, 'node_modules/typescript/lib/typescript'));
  console.log('Wallaby ', wallaby.localProjectDir, " | Typescript " , ts.version);
```

On OSX I can't get it to work. I seem to be stuck with bad TS or Node paths.

NODE_PATH is empty unless I set it. 
How does wallaby use default node strategy vs NODE_PATH when it resolves requires?  Is **ts-node** involved when running with "env":"node" ?

**Comment by MrCrimp** [comment]
Update
I got it working on OSX as well now, with the fix you provided after I had cleaned up and updated

>npm uninstall typescript -g

>npm i -g typescript@2.1.4

>npm uninstall typescript ts-node 

>npm i typescript@2.1.4 ts-node

I'm unable to determine the exact cause, but the problem seemed to be a local issue on my machine.

Thank you for the quick response on this!
