### ISSUE TITLE
Newly added files won't be processed when wallaby is already running 

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#91]
1. Start wallaby
1. Add a new spec file to the project (I use `./[module].js/__tests_/[module].spec.js` file paths)

Wallaby won't process this newly added file until I restart it

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue, how do you add the spec file? Here is what I do (using the file path structure that you have mentioned)

![spec](https://cloud.githubusercontent.com/assets/979966/7367890/6c9acdca-ede6-11e4-9f5e-89e10142889e.gif)

**Comment by okonet** [comment]
It seems to be babel- or pre-processor related I think:

I use following template for my JSX specs:

```
/*eslint no-unused-expressions: 0*/

import _ from "lodash";
import React from "react/addons";
import TestUtils from "react/lib/ReactTestUtils";
import LoggedInUserDropdownItems from "../LoggedInUserDropdownItems";

let R$ = require("rquery")(_, React);

describe("LoggedInUserDropdownItems", () => {

    it("should be defined", () => {
        let Component = R$(TestUtils.renderIntoDocument(
            <LoggedInUserDropdownItems />
        ));
        expect(Component[0]).to.not.be.undefined;
    });

});
```

and I get following in wallaby console:

```
Runtime error: TypeError: 'undefined' is not an object (evaluating '_import2['default']')
Runtime error: TypeError: Requested prototype of a value that is not an object.
Runtime error: TypeError: Requested prototype of a value that is not an object.
```

**Comment by okonet** [comment]
After I restart wallaby server, it runs just fine.

It seems the error `Runtime error: TypeError: Requested prototype of a value that is not an object.` comes from this import: `import LoggedInUserDropdownItems from "../LoggedInUserDropdownItems.jsx";`

and the `Runtime error: TypeError: 'undefined' is not an object (evaluating '_import2['default']')` from `let R$ = require("rquery")(_, React);`

**Comment by ArtemGovorov** [comment]
Created the exact same template, installed required dependencies, but still can't catch it:

![new](https://cloud.githubusercontent.com/assets/979966/7389293/e3d8a1c2-eeaf-11e4-89c6-4908cca8a736.gif)

Is there any difference between how I do and how you do it?

**Comment by okonet** [comment]
Must be some other dependency. I've just added another spec and got this:

```
js/utils/__tests__/findWhereDeep.spec.js findWhereDeep should be defined [1 ms]

	'undefined' is not an object (evaluating '_findWhereDeep2['default']')
```

for this:

```js
/*eslint no-unused-expressions: 0*/

import findWhereDeep from "../findWhereDeep";

describe("findWhereDeep", () => {

    it("should be defined", () => {
        findWhereDeep.should.not.be.undefined;
    });

});
```

**Comment by okonet** [comment]
But I think this issue can be closed, since it doesn't seem to be wallaby issue after all. Or what's your opinion?

**Comment by ArtemGovorov** [comment]
I'll try to play a bit more with it, maybe I'll be able to reproduce it.

**Comment by ArtemGovorov** [comment]
Can't reproduce, please let me know if you encounter it again and it's reproducible.
