### ISSUE TITLE
Wallaby app ignoring whitespace on error messages

### ISSUE THREAD

**Issue by steebchen** [wallabyjs/public#913]
When I have an error occurring and inspecting it in the wallaby app using [power-assert](https://github.com/power-assert-js/power-assert), its message is shown without respecting white space. I am missing `white-space: pre;` on `test-explorer .data tests-details .details .errors-logs .error-list .error-item .error-message`. I don't know if this is expected behavior to save space and have limited space for each error message, but with the output power-assert gives me this is kind of useless. Maybe you could expand the div to see the full output or show the message with pre white space if there is only one.

This is how it's showing:
![selection_999 1025](https://cloud.githubusercontent.com/assets/5013932/21406006/96dffe98-c7c9-11e6-9acd-bec87e92fb73.png)

This is how it *could* look like IMO:
![selection_999 1027](https://cloud.githubusercontent.com/assets/5013932/21406020/acc303f4-c7c9-11e6-979c-ad3a4f1c6dd9.png)

This is the correct output in Atom:
![image](https://cloud.githubusercontent.com/assets/5013932/21405893/ecfd1bfe-c7c8-11e6-91ef-9d5f76482c71.png)

Note that it's just a suggestion with low priority – I am quite happy with the correct output in atom.

Atom v1.12.4
Linux Mint 18
atom-wallaby v1.0.14

**Comment by ArtemGovorov** [comment]
Totally makes sense. The change has just been released in Wallaby App v1.0.18.
