### ISSUE TITLE
import Angular2TokenService generates an error

### ISSUE THREAD

**Issue by sgruhier** [wallabyjs/public#916]
### Issue description or question

As soon as I import Angular2TokenService 
```ts
import { Angular2TokenService } from 'angular2-token';
``` 

I have that error
```
​​Error: Cannot find module "./src/angular2-token.service"​​
```

But tests work with ng test

### Wallaby.js configuration file
I just cloned your ngCliWebpackSample and added Angular2TokenService import.
So same config.
You can see it here (forked from your official) https://github.com/sgruhier/ngCliWebpackSample

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

OSX macOS Sierra#latest

As soon as I can have wallaby working I'll by few licences. Thanks a lot!

**Comment by ArtemGovorov** [comment]
It looks like an issue in the `angular2-token` build that exposes .ts files to be loaded by webpack as opposed to the compiled .js files. This makes webpack to compile the package on the fly when running `ng test`, but will not work for example for projects that don't use TypeScript. I have [created the issue in the package repo](https://github.com/neroniaky/angular2-token/issues/103).

However, wallaby works a bit differently as it [compiles TypeScript before webpack](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript). To make it work before the `angular2-token` build is fixed, you may just tell wallaby to compile this specific module:

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  resolve: {
    modules: ['node_modules'] // <-- pointing to wallaby cache
  },

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      // <-- telling wallaby to compile the module
      {pattern: 'node_modules/angular2-token/**/*.*', load: false, instrument: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

With these changes the official sample works for me when doing `import { Angular2TokenService } from 'angular2-token';`. Please try and let me know if it works for you.

**Comment by sgruhier** [comment]
Thanks  A LOT! 
What a fast answer and fix. You rock.
