### ISSUE TITLE
Wallaby JS app should only be able to be served over https

### ISSUE THREAD

**Issue by tikotzky** [wallabyjs/public#917]
### Issue description or question
The wallaby app served at `http://wallabyjs.com/app/` should redirect to **only** allow itself to be served over `https`. The app has access to all code currently being testing by wallaby and serving over https would help prevent a MITM attack from being able to read out file contents over the websocket.

### Wallaby.js configuration file

N/A

### Code editor or IDE name and version

ANY

### OS name and version

ALL

**Comment by ArtemGovorov** [comment]
The `https://wallabyjs.com/app/` version works in Chrome, but unfortunately we still need to provide the `http` version for browsers that don't support a websocket connection to localhost from a https served page by default (like FF, Safari - only with special flags).

There's plan to address this by providing an npm package for installing Wallaby App. This way the installation will be secure (as long as the default https npm registry is used) and the app will be served from the localhost.

**Comment by ArtemGovorov** [comment]
I'll post the update here once the npm package with Wallaby App is published. Once published, it'd be the preferred way to install and use wallaby app.

Please let me know if the new solution (once ready and available) addresses your concern. For now I suggest just using `https://wallabyjs.com/app/` in Chrome.

**Comment by tikotzky** [comment]
Cool. 
Why cant the app itself be hosted locally by wallaby and pull down the needed script and css via css? 

This way you'd be able to go to something like `http://localhost:someport/app`

**Comment by ArtemGovorov** [comment]
Thanks for the note, it is a great idea and we are now considering the solution as well. 

Regards, Artem

**Comment by ArtemGovorov** [comment]
Ok, so starting from the wallaby core v1.0.335 and wallaby app v1.0.19, it's possible open `http://localhost:51245/` and it should work. We're still testing bits and pieces, but you may already try it to see how it goes for you.

**Comment by tikotzky** [comment]
Amazing!! 
Thanks for the super quick response.

One more request once you're here 😃
Can you add a shortcut to open wallaby app (running on localhost) from the editor?
Perhaps something like **⌘+⇧+R A**

**Comment by ArtemGovorov** [comment]
> Can you add a shortcut to open wallaby app (running on localhost) from the editor?

Sure, created an internal task for this one. You are using VS Code, right?

**Comment by tikotzky** [comment]
Yup I'm on vscode. 
Thanks!
