### ISSUE TITLE
can't stop instrumentation of a file

### ISSUE THREAD

**Issue by cellog** [wallabyjs/public#918]
### Issue description or question

I have a file, test/test_helper.js, which is being instrumented.  I would like it not to be.  However, if I add a line { pattern: 'test/test_helper.js', instrument: false}, then suddenly the entire thing blows up and babel doesn't run (I think) because it errors out on every single "import" statement as an unidentified symbol in every test.  If I replace the "test/**/*.js" with a similar line, the same thing happens.  If I just ignore: true it, then all tests fails with "can't find ../../test_helper" and so on.

How the hell do I get wallaby to ignore the file?

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  const load = require;

  return {
    files: [
      { pattern: 'test/t3st.config.es6.js', instrument: false },
      { pattern: 'test/**/*.test.js', ignore: true },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      'test/**/*.js',
      'src/**/*.js*',
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false },
      { pattern: 'config.js'},
      { pattern: 'config/coaches.js'},
    ],
    tests: [
      { pattern: 'test/test_helper.js', ignore: true, instrument: false },
      { pattern: 'node_modules/*', ignore: true, instrument: false },
      { pattern: 'test/index.js', ignore: true, instrument: false },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      'test/**/*.test.js*'
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
        babel: load('babel-core'),
        presets: ['es2015', 'stage-0', 'react']
      })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      // this fools meteor into ignoring the require statement.
      // otherwise, it will try to load jsdom into the web version build and server build.
      const fool = require
      const jsdom = fool('jsdom').jsdom
      const sinon = fool('sinon')
      const chai = fool('chai')
      const expect = chai.expect
      const $ = fool('jquery')
      const chaiJquery = fool('chai-jquery')
      fool('babel-polyfill')


// from mocha-jsdom https://github.com/rstacruz/mocha-jsdom/blob/master/index.js#L80
      const propagateToGlobal = (window) => {
        for (var key in window) {
          if (!window.hasOwnProperty(key)) continue
          if (key in global) continue

          global[key] = window[key]
        }
      }

// setup the simplest document possible
      const doc = jsdom('')
      const win = doc.defaultView
      global.document = doc
      global.window = win
      global.sinon = sinon
      global.expect = expect
      global.chai = chai
      global.$ = $(win)

      propagateToGlobal(win)
      global.window.____isjsdom = true
    }
  };
};
```

test_helper.js:
```
import React, { Component } from 'react';
import chai from 'chai';
import chaiJquery from 'chai-jquery';
import p from 'chai-as-promised';
import { Provider } from 'react-redux';
import { createStore, combineReducers } from 'redux';
import reducers from '../src/reducers';
import teaspoon from 'teaspoon'

import PouchDB from 'pouchdb'
PouchDB.plugin(require('pouchdb-adapter-memory'))

function pouchme(database) {
  return new PouchDB(database, { adapter: 'memory' })
}

chaiJquery(chai, chai.util, $);
chai.use(p);

function renderComponent(ComponentClass, props = {}, state = {}, returnStore = false) {
  class Tester extends Component {
    constructor(props) {
      super(props)
      this.state = props
    }
    componentWillReceiveProps(props) {
      if (props !== this.props)
      this.setState(props)
    }
    render() {
      return (
        <Provider store={store}>
          <ComponentClass {...this.state} />
        </Provider>
      )
    }
  }

  const store = createStore(combineReducers(reducers), state);
  const componentInstance = teaspoon(
    <Tester {...props} />
  ).render()
  const ret = componentInstance
  if (returnStore) {
    return [ret, store];
  }
  return ret;
}

export { renderComponent, pouchme };
```
### Code editor or IDE name and version

WebStorm 2016.3.2

### OS name and version

OSX 10.10.5

**Comment by ArtemGovorov** [comment]
Wallaby doesn't compile files that are not instrumented. 

Could you please mention the reason why do you need to turn off the instrumentation? Depending on the reason I'll recommend what to do.

**Comment by cellog** [comment]
Hi, thanks for the quick reply.  The file is a test helper file, included by tests, but is not a source file.  It is only executing 88% of the lines, and so my total coverage is 99.85% instead of 100%.  I'd like to have test_helper.js removed from the output in the wallaby app (http://wallabyjs.com/app/#/files).  Which - by the way - I LOVE.  But I digress.  Basically, I want it not to be considered a source file.

Thanks

**Comment by ArtemGovorov** [comment]
Thanks for explaining the reason. In this case you may use the special setting to exclude the file from the code coverage calculation. Please see the FAQ section at the end of this tutorial: https://wallabyjs.com/docs/intro/get-started-wallaby-app.html

**Comment by cellog** [comment]
thanks! so I should use this, yes?

    filesWithNoCoverageCalculated: ['test/test-helper.js'],

I tried this, the coverage was still happening, so I removed test/test-helper.js from files, and got 'file not found' errors.  I'm sorry I'm such a dunce with this.  Let me know if there is more documentation I can read, and I will go there.  Appreciate the help.  wallaby has transformed my coding.

**Comment by ArtemGovorov** [comment]
Hmm, yes, the `filesWithNoCoverageCalculated` should do the trick. Tried on a simple sample and it works for me. Let me try to create a sample with your structure and config.

**Comment by ArtemGovorov** [comment]
While trying to reproduce it, I found the issue. Change the hyphen to underscore, and it should work:
```javascript
filesWithNoCoverageCalculated: ['test/test_helper.js'],
```

**Comment by cellog** [comment]
Ack! Thanks. Late night obvious errors. Appreciate the pebkac debugging :)



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.39&pv=6.0.1&source=email_footer_2] On Mon, Dec 26, 2016 at 2:38am, Artem Govorov < notifications@github.com [notifications@github.com] > wrote:
While trying to reproduce it, I found the issue. Change the hyphen to underscore, and it should work:

filesWithNoCoverageCalculated: ['test/test_helper.js'],
