### ISSUE TITLE
buble compiler

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#919]
I was trying to write a compiler for [Buble](https://gitlab.com/Rich-Harris/buble), but [ran into trouble](https://gitlab.com/Rich-Harris/buble/issues/170).

(I was able to write a preprocessor instead)

Just wanted to ping you on it, in case you had any insight (or were just curious).  Thanks as always!

**Comment by ArtemGovorov** [comment]
Hi, wallaby supports ES2015 code instrumentation (before the code gets preprocessed), so in this specific case the preprocessor is as performant as compiler, and should suffice.

**Comment by ArtemGovorov** [comment]
Though, I may be missing something and perhaps your performance testing revealed that the compiler in this case is more performant?
