### ISSUE TITLE
Converting from node.js env to browser env

### ISSUE THREAD

**Issue by cellog** [wallabyjs/public#921]
### Issue description or question

Hi,

I just started using CSS Modules, and thus code like this:

import styles from './App.css'

breaks everything.  So, I moved to a webpack-based wallaby.js with browser environment in order to use the css loader.  I would have used a null loader, but I am using css classes to test whether components are being rendered, so I will need to import them into the tests as well.

Unfortunately, because I wanted the tests to work in both wallaby and karma, I've been loading all the expectation stuff in the setup() function, using require().  This, of course, is now impossible in the browser context (took me a while to figure this out, but I got it).

I have 2 huge issues (thanks in advance):

1) where do I load babel-polyfill?  It is erroring out with $_wp$ not found, because it isn't.  If I set load to false, so that it loads later in the browser, it won't be loaded at all, since webpack doesn't use it directly.

2) I need to somehow include a few packages that modify the $ (jquery) variable.  Specifically, teaspoon (https://github.com/jquense/teaspoon) and chai-jquery.  I had been doing it with the commented out require code in wallaby.js setup(), and this code in test_helper.js (our old friend from the last support request):

```
import React, { Component } from 'react';
import chai from 'chai';
import chaiJquery from 'chai-jquery';
import p from 'chai-as-promised';
import { Provider } from 'react-redux';
import { createStore, combineReducers } from 'redux';
import reducers from '../src/reducers';
import teaspoon from 'teaspoon'

import PouchDB from 'pouchdb'
PouchDB.plugin(require('pouchdb-adapter-memory'))

function pouchme(database) {
  return new PouchDB(database, { adapter: 'memory' })
}

chaiJquery(chai, chai.util, $);
chai.use(p);

function renderComponent(ComponentClass, props = {}, state = {}, returnStore = false) {
  class Tester extends Component {
    constructor(props) {
      super(props)
      this.state = props
    }
    componentWillReceiveProps(props) {
      if (props !== this.props)
      this.setState(props)
    }
    render() {
      return (
        <Provider store={store}>
          <ComponentClass {...this.state} />
        </Provider>
      )
    }
  }

  const store = createStore(combineReducers(reducers), state);
  const componentInstance = teaspoon(
    <Tester {...props} />
  ).render()
  const ret = componentInstance
  if (returnStore) {
    return [ret, store];
  }
  return ret;
}

export { renderComponent, pouchme };

```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack')

module.exports = function(wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    // webpack options
    module: {
      loaders: [
        {
          test: /\.css$/,
          loader: 'css-loader',
          query: {
            modules: true,
            importLoaders: true,
            localIdentName: '[name]__[local]___[hash:base64:5]'
          }
        }, {
          test: /\.css$/,
          loader: 'postcss-loader'
        },
        { test: /\.json$/, loader: "json-loader" },
      ]
    },
    resolve: {
      extensions: ['', '.js', '.jsx']
    }
  })

  return {
    files: [
      { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
      { pattern: 'node_modules/chai/chai.js', instrument: false },
      { pattern: 'node_modules/jquery/dist/jquery.js', instrument: false },

      { pattern: 'test/test_helper.js', load: false },
      { pattern: 'test/**/*.test.js', ignore: true },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      { pattern: 'src/**/*.js*', load: false },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'style/**/*.css', load: false },
      { pattern: 'postcss.config.js', load: false },
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false },
      { pattern: 'config.js', load: false},
      { pattern: 'config/coaches.js', load: false},
    ],
    filesWithNoCoverageCalculated: ['test/test_helper.js','postcss.config.js',],
    tests: [
      { pattern: 'node_modules/*', ignore: true, instrument: false },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      { pattern: 'test/**/*.test.js*', load: false },
    ],
    compilers: {
      '**/*.js*': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['es2015', 'stage-0', 'react']
      })
    },
    postprocessor: webpackPostprocessor,
    testFramework: 'mocha',
    setup: function() {
//      window.sinon = require('sinon')
//      const chai = require('chai')
//      window.expect = chai.expect
//      const $ = require('jquery')
//      const chaiJquery = require('chai-jquery')
//      window.$ = $(window)
      window.expect = chai.expect

      window.__moduleBundler.loadTests()
    },
    //debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm 2016.3.2

### OS name and version

OSX 10.10.5

**Comment by ArtemGovorov** [comment]
> I need to somehow include a few packages

In browser context with webpack, you may have the file that does load the modules as an [entry pattern](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns)

> where do I load babel-polyfill?

The way you're loading it now looks correct:

```javascript
{ pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
```

Not sure why it may not work, especially with `$_wp$ not found`. If using the entry pattern as described above doesn't fix this issue (or perhaps `require('babel-polyfill')` inside that entry file), then please create a repo demonstrating the issue, I'm happy to have a look.

**Comment by cellog** [comment]
I have sent you an invite to the repository in question.  It is a private repository, but there is nothing confidential or private in there, yet.  It's just not ready for public display

**Comment by ArtemGovorov** [comment]
I had a look and looks like apart from a few errors (fully reported in the Failing Tests tab) everything seems to work.

- The first error I noticed was instrumentation error of a `.json` file, which makes sense - you don't want those to be instrumented, but your compiler pattern included `.json` files:
```javascript
'**/*.js*': wallaby.compilers.babel({...
```
so you need to change it to only include `.js`/`.jsx` files:
```javascript
'**/*.js?(x)': wallaby.compilers.babel({...
```

- The second error was missing `jquery` module. It is neither in `dependencies`, not in `devDependencies`, so it makes sense that the module can not be found.

- The third error was about missing `$.fn` when loading `chai-jquery`, it was fixed after assigning the global `$` correctly in the `setup-test.js` file  (for some reason you were assigning the global $ variable to `$(window)`):

```javascript
...
const $ = require('jquery')
window.$ = $; // <---
const chaiJquery = require('chai-jquery')
```

After fixing those errors, some tests are running, some are still failing though because of the never loaded `sinon` and some missing `../../config` file.

**Comment by ArtemGovorov** [comment]
There's also the `Cannot resolve module 'react/lib/ReactMount'` error raised from the `teaspoon` node module. The module does the `react` version check and for some reason loads the `ReactMount` from `react-dom` (where it has been moved), [only from react v 15.4.x](https://github.com/jquense/teaspoon/blob/master/src/utils.js#L14), while yours is v15.3.2, so `teaspoon` tries to load `react/lib/ReactMount`, which already doesn't seem to exist in v15.3.2. Perhaps you need to upgrade your react version or report the issue to the `teaspoon` repo.

Anyway, it's not wallaby specific issue and would come up in karma as well (but I couldn't find a way to run karma in your repo, `npm test` just hangs for me).

**Comment by cellog** [comment]
Thanks for taking a look. I had mistakenly installed jquery without the - - save option. Teaspoon was working just fine as is with wallabyjs in node environment, I will try those fixes and see where we can get from there.

Thanks
Greg



via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.3.39&pv=6.0.1&source=email_footer_2] On Tue, Dec 27, 2016 at 2:27am, Artem Govorov < notifications@github.com [notifications@github.com] > wrote:
There's also the Cannot resolve module 'react/lib/ReactMount' error raised from the teaspoon node module. The module does the react version check and for some reason loads the ReactMount from react-dom (where it has been moved), only from react v 15.4.x [https://github.com/jquense/teaspoon/blob/master/src/utils.js#L14] , while yours is v15.3.2, so teaspoon tries to load react/lib/ReactMount , which already doesn't seem to exist in v15.3.2. Perhaps you need to upgrade your react version or report the issue to the teaspoon repo.

Anyway, it's not wallaby specific issue and would come up in karma as well (but I couldn't find a way to run karma in your repo, npm test just hangs for me).

**Comment by cellog** [comment]
thanks again for taking a look.  One last question: I would like to debug why teaspoon is not working (I can get everything else to work).  I'm using teaspoon as a way to test the React tree, and it would require rewriting about 500 tests, something that would delay the project by at least a month.

So, basically, is there any way I can get more information than the debug: true flag displays?  I can't figure out if the error I'm seeing is inside webpack, a babel error, or a teaspoon error.  Specifically I am seeing:

TypeError: Invalid Version: function (e) {var n=t[o][1][e];return s(n?n:e);}

and the stack trace is less than helpful:

TypeError: Invalid Version: function (e) {var n=t[o][1][e];return s(n?n:e);}
	at test/test_helper.js:8
	at test/campers/components/Campers.test.js:1

line 8 is simply "import teaspoon from 'teaspoon'"

**Comment by cellog** [comment]
I traced the error, it is being thrown in the SemVer package, which is not used by teaspoon.  It's used by PouchDB.  Basically, I fixed the problem by discarding everything I have tried to make wallaby work with webpack for the past 24 hours, and doing something else.  Still no idea what the hell was going on.  Too much magic! :)

**Comment by cellog** [comment]
FYI, I abandoned the switch to using webpack, went back to my old way.  The fix needed was simple in the end:

```
module.exports = function(wallaby) {
  // There is a weird error with the mui and mantra.
  // See: https://goo.gl/cLH8ib
  // Using require here seems to be the error.
  // Renaming it into `load` just fixed the issue.
  const load = require;

  return {
    files: [
      'test/test_helper.js',
      { pattern: 'test/**/*.test.js', ignore: true },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      'src/**/*.js*',
      { pattern: 'src/.stories/**/*.*', ignore: true, instrument: false },
      { pattern: 'src/index.js', ignore: true, instrument: false },
      { pattern: 'config.js'},
      { pattern: 'config/coaches.js'},
    ],
    filesWithNoCoverageCalculated: ['test/test_helper.js'],
    tests: [
      { pattern: 'node_modules/*', ignore: true, instrument: false },
      { pattern: 'test/karma/*', ignore: true, instrument: false },
      'test/**/*.test.js*'
    ],
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: load('babel-core'),
        presets: ['es2015', 'stage-0', 'react']
      })
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha',
    setup: function() {
      // this fools meteor into ignoring the require statement.
      // otherwise, it will try to load jsdom into the web version build and server build.
      const fool = require
      const jsdom = fool('jsdom').jsdom
      const sinon = fool('sinon')
      const chai = fool('chai')
      const expect = chai.expect
      const $ = fool('jquery')
      const chaiJquery = fool('chai-jquery')
      fool('babel-polyfill')


// from mocha-jsdom https://github.com/rstacruz/mocha-jsdom/blob/master/index.js#L80
      const propagateToGlobal = (window) => {
        for (var key in window) {
          if (!window.hasOwnProperty(key)) continue
          if (key in global) continue

          global[key] = window[key]
        }
      }

// setup the simplest document possible
      const doc = jsdom('')
      const win = doc.defaultView
      global.document = doc
      global.window = win
      global.sinon = sinon
      global.expect = expect
      global.chai = chai
      global.$ = $(win)

      propagateToGlobal(win)
      global.window.____isjsdom = true
    }
  };
};
```

I changed the pattern to '**/*js?(x)' as you recommended.  Now it works without any errors

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
