### ISSUE TITLE
unexpected token import

### ISSUE THREAD

**Issue by marcusnielsen** [wallabyjs/public#922]
I just can't get imports to work with my project even though I can run tests directly via jest in my CLI
This is a short dump of my error in VSCode.
```
/Users/mn/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/projects/91c1b660117235ac/instrumented/components/button/behaviors.test.js:2
​​​​​[Info]​​​​​     import { async } from 'most-subject';
​​​​​[Info]​​​​​     ^^^^^^
​​​​​[Info]​​​​​     SyntaxError: Unexpected token import
​​​​​[Info]​​​​​       
​​​​​[Info]​​​​​       at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:320:12)
​​​​​[Info]​​​​​       at process._tickCallback (../../.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/projects/91c1b660117235ac/instrumented/internal/process/next_tick.js:103:7)
```

I've tried a bunch of things with compiler options for babel to make sure I avoid using `modules: false` in my .babelrc, but nothing seems to make a difference. I don't know what makes jest able to parse the code in CLI mode but not when wallaby calls jest-runtime.

### Wallaby.js configuration file

```javascript
module.exports = function onWallaby (wallaby) {
  return {
    files: [
      'components/**/*.js',
      '!components/**/*.test.js'
    ],
    tests: [
      'components/**/*.test.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    debug: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

OSX

**Comment by marcusnielsen** [comment]
Also tried:
```
module.exports = function onWallaby (wallaby) {
  return {
    files: [
      'components/**/*.js',
      '!components/**/*.test.js'
    ],
    tests: [
      'components/**/*.test.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    setup: function (wallaby) {
      wallaby.testFramework.configure({
        'transform': {
          '^.+\\.js$': '<rootDir>/node_modules/babel-jest'
        }
      })
    },
    debug: true
  }
}
```

and my current .babelrc is:
```
{
  "presets": [
    "es2015"
  ]
}
```

My source code can be found here:

https://github.com/marcusnielsen/reactive-tournament/

**Comment by marcusnielsen** [comment]
Solved by installing the babel plugin for imports:

```
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-es2015-modules-commonjs"
  ]
}
```

I got a bit confused since I use webpack 2 to build with tree shaking when building the code, and jest apparently works out of the box without babel configuring. My bad :-P

Thanks for a great tool!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by ArtemGovorov** [comment]
After reviewing your wallaby config more carefully, I have noticed that you don't have [babel compilation configured](https://wallabyjs.com/docs/integration/es-next.html) for wallaby at all. That's probably the reason why it didn't work.

If you change your config to:

```javascript
module.exports = function onWallaby (wallaby) {
  return {
    files: [
      'components/**/*.js',
      '!components/**/*.test.js'
    ],
    tests: [
      'components/**/*.test.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    debug: true
  }
}
```
you may not need the `setup` function in the config, and may use your original `.babelrc`:
```
{
  "presets": [
    "es2015"
  ]
}
```

**Comment by marcusnielsen** [comment]
Thanks for pointing it out!

It must've dropped off in the middle of the testing. I had it at some point, and in the solution as well.

The thing that made it tricky for me to get started was the combination of babeljs without commonjs transformation in production, and not using webpack with wallaby (I wanted a minimal "just works" setting before going full on). It's more due to the messy setup with tree shaking than wallaby being hard to setup.
