### ISSUE TITLE
Issue with angular2-token tests

### ISSUE THREAD

**Issue by sgruhier** [wallabyjs/public#923]
### Issue description or question

I'm testing some API calls using angular2-token. I do a classic mock of HTTP using MockBackend.
`ng test` works fine, but I have a weird error with wallaby.

```
​​TypeError: undefined is not an object (evaluating 'b.prototype')​​
```

You already helped me out to setup wallaby with angular-cli and angular2-token. I just added on spec on my ngCliWebpackSample clone (https://github.com/sgruhier/ngCliWebpackSample) 

Thanks in advance for your help.

### Wallaby.js configuration file

Classic ngCliWebpackSample Wallaby.js file (https://github.com/sgruhier/ngCliWebpackSample/blob/master/wallaby.js) with specific code to work with angular2-token.

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

OSX

**Comment by sgruhier** [comment]
Forget it, it works after having restarted Visual Studio Code !

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
