### ISSUE TITLE
wallaby configuration with code using jest-runtime

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#926]
### Issue description or question
I'm seeing some erroneous behavior when run test via wallaby, while running with default test runner works fine. Error messages are like below, 
```
Failed: $_$wp is not defined​​
      at Object.<anonymous> ​source/runner/_tests/fixtures/__DangerfileEmpty.js:1​
      at _callee2$ ​source/runner/DangerfileRunner.js:75:2​
```

I'm currently suspecting this is somewhat related with codebase transforms some codes via `jest-runtime` internally, but not sure how to configure wallaby accepts those.

### Wallaby.js configuration file

https://github.com/danger/danger-js

```javascript
module.exports = (wallaby) => ({
  files: [
    "source/**/!(*.test).js",
    { pattern: "source/**/fixtures/*", instrument: false, load: true },
    { pattern: "package.json", instrument: false, load: true }
  ],

  tests: [
    "source/**/*.test.js"
  ],

  env: {
    type: "node"
  },

  compilers: {
    "**/*.js?(x)": wallaby.compilers.babel()
  },

  testFramework: "jest",

  workers: {
    initial: 1,
    regular: 1
  }
})
```

### Code editor or IDE name and version

WebStorm v11
IntelliJ IDEA v15
Visual Studio 2015
Visual Studio 2013
Atom v1.x 
Visual Studio Code v1.x [x]
Sublime Text v3

### OS name and version

Windows [x] windows 10
OSX
Linux

**Comment by ArtemGovorov** [comment]
I haven't yet had a chance to try the repo, but given the error is coming from the `source/runner/_tests/fixtures/__DangerfileEmpty.js` file, I can see that it's instrumented, even though there's the file pattern that says not to instrument it. 

The reason why it's instrumented is that wallaby applies the patterns from the top of the list (and flags from the first pattern that is met are applied), so the top pattern (with `instrument: true` by default gets applied first and the second one doesn't get applied). I suspect changing the patterns order may fix it for you:

```javascript
  files: [
    { pattern: "source/**/fixtures/*", instrument: false, load: true },
    "source/**/!(*.test).js",
    { pattern: "package.json", instrument: false, load: true }
  ],
```

Try it this way and let me know how it goes.

**Comment by kwonoj** [comment]
Just gave a quick try with suggestion, but no luck. Seems it might need global injection to runtime somewhere but it's my rough guess.

**Comment by ArtemGovorov** [comment]
Got a chance to try it. The idea of not instrumenting fixtures was correct, but they need to be transpiled, so babel `preprocessor` can be used for them. Here's the [full working config for the repo](https://github.com/danger/danger-js/pull/75).

**Comment by kwonoj** [comment]
So much appreciate for help!
