### ISSUE TITLE
Options other than phantomjs

### ISSUE THREAD

**Issue by cyberhck** [wallabyjs/public#931]
PhantomJS lacks many features which newer browsers should have, so a config to change default would have been awesome.

There are numerous headless browsers: https://github.com/dhamaniasad/HeadlessBrowsers

I'd like to see some chromium browsers being used by default. When developing on a modern technology, PhantomJS is just PITA.

**Comment by ArtemGovorov** [comment]
PhantomJs is a default option historically, but wallaby.js [supports electron](https://wallabyjs.com/docs/integration/electron.html) so you can run your tests in Chromium/V8 environment with a single change in your wallaby config. 

Closing as a duplicate of https://github.com/wallabyjs/public/issues/29
