### ISSUE TITLE
How to use fetch polyfill?

### ISSUE THREAD

**Issue by cyberhck** [wallabyjs/public#932]
I tried couple of different things:
```
{pattern: 'node_modules/node-fetch/index.js', load: true, instrument: false}
```
or
```
{pattern: 'node_modules/whatwg-fetch/fetch.js', load: true, instrument: false}
```
or
```
bootstrap: function(){
    self.fetch = require('node-fetch');
},
```
or
```
bootstrap: function(){
    require('node-fetch');
},
```
With bunch of different options, but no luck, it says fetch not defined.

**Comment by ArtemGovorov** [comment]
Could you please share your full wallaby config file?

**Comment by cyberhck** [comment]
```
module.exports = function (w) {
    return {
        files: [
            'src/**/*.ts',
            '!src/**/*.spec.ts',
            {pattern: 'node_modules/node-fetch/index.js', load: true, instrument: false}
        ],
        tests: [
            'src/**/*.spec.ts'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'jasmine'
    };
};
```

**Comment by ArtemGovorov** [comment]
So you're running tests in node.js environment (not browser environment), so no need to specify the node module in the tests list. As described in [the `node-fetch` module's docs](https://www.npmjs.com/package/node-fetch), you may just `require` it from your tests:

```javascript
var fetch = require('node-fetch');
fetch('https://github.com/')...
```

If you'd like to set it globally, you may use node.js `global` object to do so in [the setup/bootstrap function](https://wallabyjs.com/docs/config/bootstrap.html):
```javascript
module.exports = function (w) {
    return {
        files: [
            'src/**/*.ts',
            '!src/**/*.spec.ts'
        ],
        tests: [
            'src/**/*.spec.ts'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'jasmine',
        setup: function() {
          global.fetch = require('node-fetch');
        }
    };
};
```

**Comment by mchaov** [comment]
I can't figure out how to make it work with jest-fetch-mock. 
```
...
        setup: (w) => {
            global.jest = require("jest");
            w.testFramework.configure(require('./package.json').jest);
            global.fetch = require("jest-fetch-mock");
        }
...
```
TypeError: jest.fn is not a function

**Comment by ArtemGovorov** [comment]
Setting up a global variable in Wallaby config won't hep, because Jest creates separate execution contexts with their own globals. You may follow the instructions from the `jest-fetch-mock` repo at https://github.com/jefflau/jest-fetch-mock#installation-and-setup, and create setupJest file and reference it from your Jest config (nothing special in Wallaby config is required - it is purely Jest related issue).

**Comment by mchaov** [comment]
> Setting up a global variable in Wallaby config won't hep, because Jest creates separate execution contexts with their own globals. You may follow the instructions from the `jest-fetch-mock` repo at https://github.com/jefflau/jest-fetch-mock#installation-and-setup, and create setupJest file and reference it from your Jest config (nothing special in Wallaby config is required - it is purely Jest related issue).

Yeah, that did it, thanks!
