### ISSUE TITLE
Support code coverage in Vue.js single file components 

### ISSUE THREAD

**Issue by davidmoshal** [wallabyjs/public#934]
### Issue description or question

HI, not seeing Vuejs on your supported framework page (even though it has more stars than all except React). 

Question: will Wallaby work with Vue + Tyescript + Webpack

For example, with this type of project:

https://github.com/ktsn/typescript-webpack-simple

which uses Typescript compiler, not Babel

### Wallaby.js configuration file

None yet

### Code editor or IDE name and version

WebStorm 2016.3.2

### OS name and version

OSX 10.12.2

**Comment by ArtemGovorov** [comment]
Hi,

the last time I tried wallaby with vue+webpack there were some issues with displaying the code coverage of .vue files (due to some vue-loader implementation specifics), but the rest did work. Please feel free to try configuring the project [using this tutorial](https://wallabyjs.com/docs/integration/webpack.html). If something doesn't work for you, please let me know, happy to have a look.

**Comment by davidmoshal** [comment]
hmm, so that tutorial leads to this project:

https://github.com/wallabyjs/wallaby-webpack-sample

which doesn't have a webpack.config.js file?

**Comment by ArtemGovorov** [comment]
> which doesn't have a `webpack.config.js` file, but seems to run fine.

Wallaby doesn't need a webpack config for simple cases (you don't need ts-loader or babel loader as described in the referenced docs), but there's a way to supply an [existing webpack config](https://wallabyjs.com/docs/integration/webpack.html#webpack-config) if required.

> so, now the question is what happens when TS, Webpack, and Vue are combined?

It may just work (except code coverage indicators for .vue files). [TypeScript compilation doesn't need any special config with wallaby.js](https://wallabyjs.com/docs/integration/typescript.html) and normally works with defaults, Here's also the example of using wallaby.js with browserify + vue (of course browserify is not webpack, but still quite similar config).

**Comment by davidmoshal** [comment]
I'm not actually using .vue files at the moment (because they actually don't really support TS themselves)! 

I load html templates from the ts files.

So, still looking at various examples:

TS + Webpack:
https://github.com/wojciak/wallabyjs-webpack-typescript
https://github.com/risonipli/wallaby-webpack-typescript-issue
(The latter does have a webpack.conf.js file)

and 
Vue + Webpack:
https://github.com/rvanzon/vue-webpack-wallaby

will then try TS + Webpack + Vue and see what happens .....

**Comment by davidmoshal** [comment]
ps: should I be concerned that Wallaby is running Node V4 (in the Webstorm config), whereas the rest of the project is on Node V6 ?

**Comment by ArtemGovorov** [comment]
> should I be concerned that Wallaby is running Node V4 (in the Webstorm config), whereas the rest of the project is on Node V6 

It should be fine (wallaby is only using this node version to run itself and other tool it loads, like webpack), unless you're using some native modules, such as node-sass, that require compilation for your node version. If you do, you may just [point the Webstorm Run Configuration to your local node v6](https://wallabyjs.com/docs/intro/install.html#nodejs).

**Comment by davidmoshal** [comment]
ok, so this setup doesn't work correctly:
https://github.com/rvanzon/vue-webpack-wallaby

given this in `test/unit/specs/Hello.spec.js`:
```js
expect(vm.$el.querySelector('.hello h1').textContent).to.equal('Hello Vue!')
```

then in the vue file `src/components/Hello.vue`:
```vue
    <h1>{{ msg }}</h1>
```
is changed to:
```vue
    <h2>{{ msg }}</h2>
```
then the test doesn't fail unless you restart wallaby.js

**Comment by davidmoshal** [comment]
this one seems like it's a mess, I'm guessing that wallaby's webpack config is the problem:
https://github.com/wojciak/wallabyjs-webpack-typescript

**Comment by davidmoshal** [comment]
@ArtemGovorov - you didn't include the link for browserify and vue!

**Comment by davidmoshal** [comment]
this one works, sort of, but the error messages don't navigate to the exact line in the tests, but close enough I guess.

https://github.com/wallabyjs/wallaby-webpack-typescript-issue

**Comment by davidmoshal** [comment]
So a summary so far.

**Goal**: Vuejs + Webpack + Typescript.

No template was found on Github with all 3 components.

The following were all the templates found with any of the components:

**Webpack:** (no vue, no typescript)
- https://github.com/wallabyjs/wallaby-webpack-sample  works

**Typescript:** (no vue, no webpack)
- https://github.com/wallabyjs/wallaby-typescript-sample works

**Webpack + Typescript:** (no vue)
- https://github.com/wallabyjs/wallaby-webpack-typescript-issue
  - works, sort of, error messages don't completely map to test files.
  - a broken test in a single file can easily make all the files look broken in the wallaby web app (not that helpful)
- https://github.com/wojciak/wallabyjs-webpack-typescript
   - totally broken:
     ```
     ModuleParseError: Module parse failed: ./app/template.html Unexpected token (1:0)
     You may need an appropriate loader to handle this file type.
     ```

**Vue + Webpack**
- https://github.com/rvanzon/vue-webpack-wallaby
   - not picking up changes in the .vue files, note this is not simply a problem of code coverage
   - wallaby is not reloading the vue files after changes 
   - I suspect that there is a watch option in the webpack config located in the wallaby.js file that needs to be tweaked.
   - So it's a concern that there need to be 2 separate webpack configuration files to keep in sync.

**Next steps:**

Possibly start with ttps://github.com/wallabyjs/wallaby-webpack-typescript-issue, and add vue and see if we can get the dynamic template loading working? 
Ideally without separate webpack.js configuration?

**Comment by ArtemGovorov** [comment]
>  you didn't include the link for browserify and vue!

Oops, sorry, here it is: https://github.com/wallabyjs/public/issues/930.

> + Typescript

We may take it out of the equation. As I have mentioned, TypeScript compilation doesn't need any special config (if you have a tsconfig.json in the project root, then it should just work).

> https://github.com/wojciak/wallabyjs-webpack-typescript

I don't think I have seen this repo before, it may just be that the user was experimenting with wallaby and have pushed the half-working version to GitHub.

> https://github.com/wallabyjs/wallaby-webpack-typescript-issue

This repo was created to reproduce some issue for another user, so perhaps the 2 issues you saw there (`error messages don't completely map to test files` and `broken test in a single file can easily make all the files look broken in the wallaby web app`) are related to the issue.

> https://github.com/rvanzon/vue-webpack-wallaby

This repo had also been created by a user who was exploring the possibility of using wallaby with vue, but there're a few things that are not correct in that config (for example has to be in the project's root and can't have paths going up like `../..`).

We maintain the list of [officially maintained samples in the docs](https://wallabyjs.com/docs/integration/overview.html). Here's the [sample of webpack + TypeScript](https://github.com/ArtemGovorov/wallaby-webpack-sample/) from the list, please try it to see if the issues you've mentioned are showing up in the sample.

> Webpack + Vue
> - not picking up changes in the .vue files
> - this is not simply a problem of code coverage, wallaby is not reloading the vue files after changes and rerunning the tests, ie: not picking up a test dependency.
> - I suspect that the webpack config in the wallaby.js file is missing a watch setting

Yes, unfortunately because wallaby.js doesn't instrument `.vue` files, it also can not track the dependency between a `.vue` file and tests at the moment (but we're planning to change it soon). For now the workaround is to use `Alt+Enter` + "Run project tests"/"Run file tests" action (can use a shortcut) when working with/editing `.vue` files. Anyway, you've mentioned that you're not using `.vue` files, so it should not be an issue for you.

> - It's a concern that there need to be 2 separate webpack configuration files to keep in sync.

It's not really 2 separate webpack configs. The idea is to load the prod/dev webpack config inside wallaby config and then just adjust some details for the testing environment.

I'll try to find some time next week to see what's required to make make wallaby.js work with vue. In a meantime the https://github.com/rvanzon/vue-webpack-wallaby repo looks like the closest to what it should be. I'd start with moving wallaby config to the root of the project.

**Comment by davidmoshal** [comment]
Thanks for the detailed response.
I found another example, from the official docs link you sent, which has TS + Webpack + Angular2 looks like a good example of how Vue 'should' work:
https://github.com/wallabyjs/angular2-webpack-starter
(though note Vue is far less verbose than Angular)

> Yes, unfortunately because wallaby.js doesn't instrument .vue files, it also can not track the dependency between a .vue file and tests at the moment (but we're planning to change it soon). For now the workaround is to use Alt+Enter + "Run project tests"/"Run file tests" action (can use a shortcut) when working with/editing .vue files. Anyway, you've mentioned that you're not using .vue files, so it should not be an issue for you.

Couple of points:
1. Yes, I'm not using `.vue` files currently, because the typscript script blocks don't work properly and cause problems in IntelliJ. Also, am waiting for `.tsx` support which might be better. However, I do use `.hbs` templates, and I would like Wallaby to re-run tests if a `.hbs` template changes.

2. I'm really surprised about not being able to re-run tests after a `.vue` file changes! Isn't that what Webpack is for? I mean Webpack has a vue-loader, and can easily re-trigger a build when those files changes. This brings me back to the early question about webpack configs - I get that you're not using webpack bundles, but if you're not using the output of a .vue file transformation by vue-loader, then it's not clear to me a) what you're using Webpack for then, and b) whether you're actually testing the same code that will show up in production, even if it isn't bundled.

ps: Vue-loader has fantastic [documentation](https://vue-loader.vuejs.org/en/). Given such a loader, there should be a way to make this work easily, no?

Thanks

**Comment by ArtemGovorov** [comment]
> However, I do use `.hbs` templates, and I would like Wallaby to re-run tests if a `.hbs` template changes.

Yes, as I have mentioned, we are planning to add the support for re-running affected tests on related non-JavaScript/TypeScript files changes soon.

>  but if you're not using the output of a .vue file transformation by vue-loader

We are using the output of a .vue file transformation by vue-loader. And we are testing the same code that the webpack config produces, except that it's not concatenated into a single bundle file.

**Comment by ArtemGovorov** [comment]
Ok, so I have taken the [template you've originally shared](https://github.com/ktsn/typescript-webpack-simple), and after a bit of investigation of how `ts-loader` works (it is used to compile TypeScript inside `.vue` files), I have create the working wallaby config for the project. Here's [the sample](https://github.com/wallabyjs/wallaby-934) which may end up being an official one once it's working for you and others.

Please have a look to see how it works for you. Note that you need the [latest wallaby core v1.0.340](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). There's the separate issue with `.vue` file changes not (always) triggering the test run, but as I said we are working on it.

**Comment by davidmoshal** [comment]
Wow, thanks, I will check it out now!

**Comment by davidmoshal** [comment]
Getting late here (2am in SF), so I'm going to take a break.

The Webstorm integration seems to work nicely, and reports errors correctly.

_**Honesly, this seems like a 'game changer' for testing!**_
Reminds me a bit of what the 'LightTable' IDE was trying to do for Clojure a few years ago.
After just a few minutes playing with it I'm wondering how I lived without it!
Definitely I'll be buying a license.

The wallabyjs.com/app though seems broken, in several ways, I need more time to give useful feedback, and also to design tests that don't include typescript scripts inside of .vue templates, as discussed previously.

One question: 
I was under the impression that wallaby.js required separate testing libraries to be imported, yet your example has no testing libraries in `package.json', and none that I can see in `node_modules`. I'm assuming that `describe` and `expect` functions come from some bundled Jasmine libraries, correct?

Great work!

Thanks
David

**Comment by ArtemGovorov** [comment]
Great, thanks for the update!

> The wallabyjs.com/app though seems broken, in several ways, I need more time to give useful feedback

Please report any issues you find with it, much appreciated. Would be especially helpful if you could describe a way to reproduce them in the sample project, which is already working for you.

> I was under the impression that wallaby.js required separate testing libraries to be imported, yet your example has no testing libraries in package.json, and none that I can see in node_modules. I'm assuming that describe and expect functions come from some bundled Jasmine libraries, correct?

It is correct. For browser environment, wallaby comes with bundled libraries of all testing frameworks that it supports. So if you're using mocha as opposed to jasmine, you'll need a separate assertion library like `chai`, and either `require` it from tests, or just [load it globally like in this sample](https://github.com/ArtemGovorov/wallaby-webpack-sample/blob/master/wallaby.js#L8).

**Comment by fvanwijk** [comment]
Here are some additional notes about .vue files and coverage.

I don't have Wallaby coverage markers in the .vue files. When running with karma/istanbul/isparta I also have coverage issues. Here is an example

<img width="238" alt="coverage_fail" src="https://cloud.githubusercontent.com/assets/963136/21748958/f494ff94-d592-11e6-9956-349529f91de0.png">

I remember trying to fix this a couple of months ago. It seemed a source maps issue with vueify - perhaps vue-loader has the same issue? - and we decided to go back to .html+.js instead of .vue files.
Now we have Vue 2 (runtime build) and it looks like .vue files are sort of required or you will have a lot of other issues with compiling templates to render functions. So we switched back to .vue files, resulting in Wallaby config issues (#930).

You could fork the `wallaby` branch from https://github.com/fvanwijk/vue-multiselect-browserify-example (see #930) and clean it up a little bit to have a wallaby-vue-browserify sample repo. I could do it too if you want.

We also could create a wallaby-vue-browserify-typescript sample repo to complement that whole family.

**Comment by ArtemGovorov** [comment]
> I don't have Wallaby coverage markers in the .vue files

Yep, it was never supported. As `.vue` files is not JavaScript but mixed content, wallaby needs a compiler or a preprocessor to instrument it correctly. Last time I was trying to create one, I have hit an issue with `vue-loader` implementation specifics related to source maps generatin, so perhaps it's same issue you saw with `istanbul`.

> We also could create a wallaby-vue-browserify-typescript sample repo to complement that whole family.

That would be great!

**Comment by ArtemGovorov** [comment]
For webpack projects, as of [wallaby.js core v1.0.341](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and `wallaby-webpack` module v0.0.28, editing `.vue` files (or any other non-instrumented files listed in the `files` list) should now trigger dependent tests.

**Comment by davidmoshal** [comment]
tested with https://github.com/rvanzon/vue-webpack-wallaby
changing the Hello.vue component from:
```js
export default {
  data () {
    return {
      msg: 'Hello Vue!'
    }
  }
}
```

to 
```js
export default {
  data () {
    return {
      msg: 'Goodby Vue!'
    }
  }
}

```
Does NOT trigger re-running of the tests, restarting Wallaby.js is required to fail the test.
Using:
```
wallaby.js started
core v1.0.341
```

**Comment by ArtemGovorov** [comment]
That repo has some other issues with its config, please [try this one](https://github.com/wallabyjs/wallaby-934) (with a fresh `npm install` to get the latest `wallaby-webpack`).

**Comment by davidmoshal** [comment]
@ArtemGovorov I published a demo project, using Vue + Typescript + Wallabyjs

https://github.com/davidmoshal/reactive-vue-typescript-testing

Using Vue hot-reloading plus Wallabyjs at the same time is somewhat magical.

I'm using Vue 1.x instead of Vue 2.x for the following reasons:

a) `vue-typescript` is the most mature Vue + Typescript library and it's incompatible with Vue 2.0.

b) Vue 2.0 introduced several breaking changes, and has made several questionable design changes. I suspet that many Vue 1.x users will also hold off on upgrading until these are sorted out. 


David

ps: I bought a license, very happy with Wallabyjs

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the order, the update and the repo. Published it in [the examples docs page](https://wallabyjs.com/docs/integration/overview.html#sample-projects-with-wallabyjs-config-and-other-wallabyjs-recipes).

**Comment by ChangJoo-Park** [comment]
@ArtemGovorov Hello, I am big fan of Wallaby.js

Here is Vue.js with webpack template sample (include vimeo 😄 )

https://github.com/ChangJoo-Park/vue-wallaby-webpack-template

Please add green(and red!) rounded rectangle on my code editor when I edit `.vue` file!

**Comment by jraller** [comment]
I've had partial luck using the following pieces with Webpack, Typescript, Vue2, and Mocha. Inside my test.ts files I bring the .vue components in with `const component = require('!vue-loader!./../app/views/component.vue');` and in my .vue files I have a `<template>` section followed by a script tag in the form `<script lang="ts" src="./component.ts"></script>`. I've found that removing the `src=""` portion of the script tag causes errors. I'm not getting coverage reports for my components in Wallaby with this, but I am getting test failures changing dynamically when I modify my .vue file, the associate .ts file, or my test.ts file. In my test.ts files I'm using Avoriaz, chai, sinon, sinon-chai, and the babel-polyfill. When I have a workable template using these I'll share it.

**Comment by jraller** [comment]
When using vue-loader with single file components that use src imports of typescript files that themselves have includes from the node_modules folder (ex: 'vue' and 'vue-class-component') something in the chain is causing Wallaby to not see those imports as being from the project node_modules, and there are TS2307 errors generated to that effect. Rewriting the .ts files that the component references in the script tag to avoid the imports works, but then the benefits of vue-class-component are missing.

**Comment by ArtemGovorov** [comment]
@jraller Any chance you could share the repro where `something in the chain is causing Wallaby to not see those imports as being from the project node_modules`? I'm happy to investigate.

**Comment by jraller** [comment]
@ArtemGovorov Thank you for Wallabyjs. https://github.com/jraller/Vote/tree/webpack is a project I'm using to learn how to use the parts of this tool chain work together. It is messy as it is a learning zone, but the tests folder is a good place to see what is working and what isn't.

**Comment by ArtemGovorov** [comment]
@jraller I was wondering why you needed to specify `!vue-loader!...` in your tests and while investigating I have realised that you are not actually using your webpack config with wallaby at all.

The `wallabyWebpack` function that you're calling expects webpack config object, but your `./webpack.config` doesn't export the config object, it [exports a function](https://github.com/jraller/Vote/blob/fb9703e8662dc148b176312b9cf38ee75d5b0ea5/webpack.config.js#L238).

So I went ahead, called that function, then cleaned up the webpack config for wallaby (as the [docs say](https://wallabyjs.com/docs/integration/webpack.html) `.ts` extension has to be removed from the extensions and also wallaby doesn't need `.ts` and `.js` loaders):

```javascript
const webpackConfig = require('./webpack.config')();
const wallabyWebpack = require('wallaby-webpack');

webpackConfig.module.rules = webpackConfig.module.rules.filter(r => !'.ts'.match(r.test) && !'.js'.match(r.test));
webpackConfig.resolve.extensions = ['.vue', '.jsx', '.js'];
delete webpackConfig.devServer;
delete webpackConfig.entry;

module.exports = function (wallaby) {
...
```

Also needed to install `npm i imports-loader --save-dev` that is required by the webpack config.

After these changes, you can import `.vue` files without an explicit loader: 
```javascript
const Sanity = require('../app/views/sanity.vue');
```

I haven't found the way to see the `something in the chain is causing Wallaby to not see those imports as being from the project node_modules, and there are TS2307 errors generated to that effect` errors in the project. I'm sure it's easy to reproduce, but I haven't used vue, so don't even know where to start.

Anyway, the correct loading of the webpack config may have actually fixed those errors as well.

**Comment by jraller** [comment]
@ArtemGovorov Thanks. I check those changes out tomorrow and report back. Hopefully I can document that and get it in a form so that others don't stumble into the same mistakes I made.

**Comment by jraller** [comment]
@ArtemGovorov Your improvements have been implemented in my code. Thank you.

**Comment by retrocede** [comment]
@ArtemGovorov any updates on the instrumentation of .vue files? I'm looking at adopting wallaby for several projects, but single file component support is a must.

Are there any roadblocks towards .vue file usage that the community can help out with?

**Comment by ArtemGovorov** [comment]
@retrocede The last time I tried to set up the instrumentation of .vue files for vue+webpack there were some issues that seem to be related to how vue-loader works. I can try again and investigate it further - could you please create and share a sample project for your scenario (with all related configs)?

**Comment by retrocede** [comment]
@ArtemGovorov https://github.com/ChangJoo-Park/vue-wallaby-webpack-template from @ChangJoo-Park  is very similar to the setup we use. If you need another example repo I can spin one up sometime today though.

**Comment by scottbedard** [comment]
I too would like to see support for webpack with .vue files

**Comment by ArtemGovorov** [comment]
I have created [this pull request](https://github.com/ChangJoo-Park/vue-wallaby-webpack-template/pull/2) to the @ChangJoo-Park awesome template.

Once applied applied in your wallaby config, you get wallaby.js full presence inside .vue files scripts:

![vue](https://user-images.githubusercontent.com/979966/28302976-e822e7ee-6bd3-11e7-8942-446d48e6b1bb.gif)

The major change is to disable `vue-loader` for script sections of the `.vue` files, and use https://github.com/wallabyjs/wallaby-vue-compiler as a compiles for `.vue` files.

**Comment by bbugh** [comment]
If you're like me (and I know I am) you found this thread from Googling "wallaby vue" and  spent hours screwing around with webpack to get Jest to work since the template linked above uses Karma. 

Instead of going that route, I recommend the the wallaby config linked here https://github.com/wallabyjs/public/issues/1456 for Jest. It's far less complex and skips Webpack altogether. 🎉
