### ISSUE TITLE
Accessing webpack constant in wallaby

### ISSUE THREAD

**Issue by glendaviesnz** [wallabyjs/public#941]
### Issue description or question

What is the best/recommended way to make webpack constants available to wallaby.js. I am using the angular class webpack seed which defines an ENV constant, which i am using in the main app component to dictate if some dev tools are included or not. 

export class AppComponent {
    public environment = ENV;
}

This works fine with all the webpack and karma builds but wallaby gives a "Can't find variable: ENV​​" error. 

I have tried declaring the ENV variable in wallaby.js, config/spec-bundle.js  and config/karma-require.js, but get the same error. Declaring it as global.ENV in these files fixes it for wallaby, but breaks it for the webpack builds.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.scss$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /karma-require/, loader: 'null-loader'}
    ]
  }
});

module.exports = function () {

  return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'config/karma-require.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true},
      {pattern: 'src/**/*.d.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.8

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Try adding it the same way it's done in the [webpack config for karma](https://github.com/AngularClass/angular2-webpack-starter/blob/master/config/webpack.test.js#L187):

```javascript
const DefinePlugin = require('webpack/lib/DefinePlugin');
const ENV = process.env.ENV = process.env.NODE_ENV = 'test';
...
var webpackPostprocessor = wallabyWebpack({
  ...
  }
});

module.exports = function () {

  return {
    ...
    plugins: [
      new DefinePlugin({
        'ENV': JSON.stringify(ENV)
      })
    ]
  };
};
```

**Comment by glendaviesnz** [comment]
Sorted. Thanks.

**Comment by glendaviesnz** [comment]
Just an additional note - I needed to include the plugins setting in the webpackPostProcessors section rather than module.exports to get it to work.

**Comment by ArtemGovorov** [comment]
@glendaviesnz Oh, my bad. Edited my comment to fix it.
