### ISSUE TITLE
'SyntaxError: Unexpected token import' with Quill

### ISSUE THREAD

**Issue by rpmonteiro** [wallabyjs/public#946]
### Issue description or question
So I'm using this library called Quill which requires a specific method of importing.. I think close to #887.
Here's a link explaining it better than I can: http://quilljs.com/guides/adding-quill-to-your-build-pipeline/

The imports look like this:
![image](https://cloud.githubusercontent.com/assets/7824615/21894521/6ef3dd5e-d8d7-11e6-8063-a544ecaa5301.png)

There's no special .babelrc magic going on.

I get this error:
![image](https://cloud.githubusercontent.com/assets/7824615/21894423/18923b9a-d8d7-11e6-89b8-e01fc21982f4.png)

I've tried pre-processing it with the babel-core, but it just throws more errors even.

I've already spent hours on this and still don't understand what's going on. I would immensely appreciate your help, Artem sensei!

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src-cls/**/*.js*',
      {pattern: 'src-cls/**/__tests__/*-test.js', ignore: true},
      {pattern: 'src-cls/**/__integrationTests__/*-test.js', ignore: true},
      {pattern: 'src-cls/docs/*', ignore: true},
      'src-cls/__tests__/*',
      'src-le/**/*.js*',
      {pattern: 'src-le/**/__tests__/*-test.js', ignore: true},
      {pattern: 'src-le/__tests__/*', ignore: true},
      {pattern: 'src-le/images/*', ignore: true}
    ],

    tests: [
      'src-cls/**/__tests__/*-test.js',
      'src-le/**/__tests__/*-test.js'
    ],

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({module: 'commonjs'}),
      '**/*.js*': wallaby.compilers.babel()
    },
    
    env: {
      type: 'node',
      params: {
        env: 'LOCAL_PATH=' + process.cwd()
      }
    },

    testFramework: 'mocha',
    
    setup: function () {
      require.extensions['.jsx'] = require.extensions['.js'];
      require('./src-cls/__tests__/setup');
      require('./src-cls/__tests__/helpers');
    }
  };
};

```

### Code editor or IDE name and version

Atom v1.13.0

### OS name and version

OSX (latest)

**Comment by ArtemGovorov** [comment]
If you need to compile some of your node modules with babel (for example because they use ES6 modules internally like `quill`), you may enable `babel-register` just for those modules. This should work for you:

```javascript
module.exports = function () {
  return {
    ...

    setup: function (w) {
      require('babel-register')({ only: /quill/ });
    }
  };
};
```

**Comment by rpmonteiro** [comment]
Thanks Artem, that got things a step further (which I actually had gotten there yesterday by putting quill in the files and not instrumenting them).

Now I get reference errors, `Node is not defined`. etc, because of this:
![image](https://cloud.githubusercontent.com/assets/7824615/21926621/74812332-d97a-11e6-9eb3-8f7fe838e241.png)

My runner is `node`, and everything breaks if I change it to `browser` (as expected)...

Any ideas that might help?

Thanks again Artem!

**Comment by ArtemGovorov** [comment]
> I have the headless browser in one of the requires in the setup, but that only comes into play before the tests are run.. way after babel compiles Quill.

This may happen if you are `putting quill in the files and not instrumenting them`, but with the way I suggested (`babel-register` in the `setup` function) Quill should be compiled by babel when it is first imported, so your setup files should run before it.

**Comment by rpmonteiro** [comment]
Yes! You're right! I've plugged the hole by adding an empty object when accessing the variable where it was erroring out - thank you!

But now...
![image](https://cloud.githubusercontent.com/assets/7824615/21928254/a5f193a0-d981-11e6-8462-47569a207676.png)

It triggers on an SVG file?

**Comment by ArtemGovorov** [comment]
Does it work for you with plain mocha?

**Comment by rpmonteiro** [comment]
Yeah, it runs fine. 

I also don't have any tests pulling anything that uses Quill just yet.

**Comment by ArtemGovorov** [comment]
Great, could you then please share the sample repo with mocha and wallaby configured where I could reproduce the error?

**Comment by rpmonteiro** [comment]
Sure, I'll create one now

**Comment by rpmonteiro** [comment]
This is as far as I could get...

https://github.com/rpmonteiro/wallaby-webpack-es6-react

Sorry if it's not much help

**Comment by ArtemGovorov** [comment]
How do I run mocha (that works for you) is the repo?

**Comment by ArtemGovorov** [comment]
Also wallaby.js file in the repo is completely different from the one you've share in this issue. Could you please change the repo/create a new one to reflect your current setup, including existing working mocha, and wallaby.js config that you're truing to make work?

**Comment by rpmonteiro** [comment]
My apologies. I've now added it correctly.

Guess what, it almost works. :rofl: Mocha is no working though.
But I'm still getting the same error on the main repo! `React is not defined`..

**Comment by ArtemGovorov** [comment]
Wallaby works for me on this repo. Try adding more stuff from your main repo to reproduce the issue in the sample repo.

> Mocha is not working though.

Is it configured the same way as in your main repo? If yes, then I don't understand how does it work in your main repo.

**Comment by rpmonteiro** [comment]
Ok, I got both mocha and wallaby running fine on the sample repo. 

I still have that error on the main repo though...
![image](https://cloud.githubusercontent.com/assets/7824615/21933205/5899dd0e-d99c-11e6-9c7d-2af471f0814f.png)

How is that `React.createElement` be inline with an svg file!? Do you have any idea of what's causing that entanglement?

On the main repo, I'm running only 1 test - the same one as the sample repo.. everything is pretty much the same, but I can't reproduce it on the sample repo!

I think we're almost there, Artem! Any ideas?

**Comment by rpmonteiro** [comment]
Finally managed to reproduce the error!
On the main repo I was importing a Quill theme file, which has the following import:

https://github.com/quilljs/quill/blob/develop/ui/icons.js

And that's by importing that file (and subsequently the svg files), that it errors out.

**Comment by rpmonteiro** [comment]
And I fixed it!

http://stackoverflow.com/questions/37259523/require-import-svg-during-mocha-tests
const noop = () => 1;
require.extensions['.svg'] = noop;

Mocha can't deal with .svg files obviously, so that little hack just returns something acceptable whenever an svg is about to be loaded, thus fixing the problem.

Thank you very much Artem! You're the man!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! I should have guessed about the .svg file loading, but I was completely puzzled about the `React.createElement` error message.
