### ISSUE TITLE
Wallaby.js code instrumentation corrupts binary files

### ISSUE THREAD

**Issue by mdebruijne** [wallabyjs/public#947]
### Issue description or question

I have noticed that some tests are failing in wallaby.js while the same tests complete successfully in Jest. After some investigation I have noticed that wallaby.js code instrumentation corrupts binary files. For example; ~/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/projects/71c0b94a51457398/original/static/favicon.ico is a 70 bytes file and ~/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.37/projects/71c0b94a51457398/instrumented/static/favicon.ico is a 1 byte file.

Please make sure that wallaby.js isn't changing binary files, like in this example an ICO file.

If you need more information then please let me know.

### Wallaby.js configuration file

```javascript
{
  "env": {
    "type": "node",
    "runner": "node",
    "params": {
      "runner": "--harmony_async_await"
    }
  },
  "files": [
    "lib/*.js",
    "routes/*.js",
    "static/*"
  ],
  "hints": {
    "ignoreCoverage": "istanbul ignore"
  },
  "testFramework": "jest",
  "tests": [
    "test/*.js"
  ]
}
```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
Hmm, I'm trying with some `.ico` files (wallaby icons) and it's working for me as expected (it copies files over correctly). Could you please attach an icon file that fails to copy?

**Comment by mdebruijne** [comment]
I have attached a ZIP file with the original and the instrumented file (can't attach ICO files directly in GitHub)

Additional information;
- remove the wallaby.js extension and thus remove the original and instrumented files
- install the wallaby.js extension, the files are copied from my working directory to the wallaby.js project folder
- after the first copy/instrumentation the binary files are the same as the the working directory and correct in both original and instrumented directories, all the tests in wallaby.js are successful
- after some development, the files are "re-instrumentated" and then become corrupt and tests start to fail in wallaby.js (note that the files haven't been changed in the working directory)

I have done this procedure multiple times (also on different systems) and the problem always reappears
Although the problem is 100% reproducible (for me), unfortunately I cannot tell you exactly what event triggers the re-instrumentation of the existing files and corrupts them.

Is it possible to enable debugging/analyse logs to get more insight in the root cause?

[favicon.ico.zip](https://github.com/wallabyjs/public/files/704163/favicon.ico.zip)

**Comment by ArtemGovorov** [comment]
> after some development, the files are "re-instrumentated" and then become corrupt

How fast does it happen?

**Comment by mdebruijne** [comment]
This problem reoccurs between a few hours and a couple of days after reinstalling the wallaby.js extension.

What events do trigger the re-instrumentation of the existing files? Maybe I can use this information to better reproduce the problem.

Is it possible to enable debugging/analyse logs to get more insight in the root cause?

**Comment by ArtemGovorov** [comment]
> This problem reoccurs between a few hours and a couple of days after reinstalling the wallaby.js extension.

You don't actually need to re-install the extension. It's wallaby cache issue, so you may simply [touch your wallaby config file](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) (adding a space will do) and wallaby will invalidate the cache after the restart.

> What events do trigger the re-instrumentation of the existing files?

Only file changes are supposed to trigger the re-instrumentation.

> Is it possible to enable debugging/analyse logs to get more insight in the root cause?

Yes, please set [`debug: true`](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) and the next time it happens, [open Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) and paste the output here (or email to hello@wallabyjs.com) - let's see if there's anything suspicious there.

**Comment by ArtemGovorov** [comment]
> You don't actually need to re-install the extension. It's wallaby cache issue, so you may simply touch your wallaby config file (adding a space will do)

Forgot to mention, this only works if the file in the `instrumented` folder is corrupted, for the the corrupted file in the `original` folder, you may just delete the folder (or the whole `projects` folder).

**Comment by mdebruijne** [comment]
Only the files in the instrumented directory become corrupted. The files in the original directory are the same as the working directory

I have enabled debug and will report back when the problem reoccurred.

Thanks for your excellent support!

**Comment by ArtemGovorov** [comment]
Thanks! I have just published a new version where I have changed a couple of things that, though not likely, but still may be contributing to the issue. Try [updating the core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to see if the issue persists (and if it does - we'll see what's in the debug output).

**Comment by mdebruijne** [comment]
I have updated the core, but the problem occurred again. I have sent a debug log to hello@wallabyjs.com referencing this issue.

**Comment by ArtemGovorov** [comment]
Thanks, I have found a couple of things in the log that I'll need to investigate. In a meantime, to make it so the issue doesn't bother you, you may do this:

- remove the `static/*` pattern from your `files` list,
- run:
```
npm install fs-extra copy --save-dev
```
and change the config:

```javascript
var path = require('path');
var copy = require('copy');

module.exports = function (wallaby, done) {
  require('fs-extra').ensureDirSync(wallaby.projectCacheDir + '/static');
  copy(
    path.join(wallaby.localProjectDir, 'static', '*.*'),
    path.join(wallaby.projectCacheDir, 'static'),
    function () {
      done({
        files: [...], // <-- remove `static/*` pattern from here
        ... // the rest of your config
      });
    });
};
```

This way wallaby will copy the files from `static` folder once and will never override them while working.

**Comment by mdebruijne** [comment]
Thanks for the workaround.

I am now able to always reproduce this problem. I have sent a test case with instructions to hello@wallabyjs.com

**Comment by ArtemGovorov** [comment]
@mdebruijne Thanks, but I haven't received anything at hello@wallabyjs.com, could you please double check if you sent it?

**Comment by ArtemGovorov** [comment]
Thanks a lot for the repo with steps to reproduce. I have found out the reason and fixed the issue. Please [update to the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) (or wait for an automatic update) and the issue should go away.

**Comment by mdebruijne** [comment]
Thanks @ArtemGovorov

I can confirm that the bug has been fixed.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
