### ISSUE TITLE
Angular:

### ISSUE THREAD

**Issue by johannesjo** [wallabyjs/public#95]
I get the following error when trying to test an angular application.
```
 [$injector:modulerr] Failed to instantiate module myApp due to:\nTypeError: \'undefined\' is not a constructor (evaluating \'new UAParser()\')
```

I'm using the latest version of wallaby, angular 1.3.15 and the 'wallaby-ng-html2js-preprocessor.

**Comment by ArtemGovorov** [comment]
Would you be able to provide a small sample repository where I could reproduce the issue?

**Comment by johannesjo** [comment]
@ArtemGovorov unfortunately not before the end of the month.

**Comment by ArtemGovorov** [comment]
The error normally means that some module is failing to load. Check your `files` list to make sure everything is there and in the correct order. Maybe some of the files (specifically with UAParser) is not included?

**Comment by johannesjo** [comment]
My bad. I was assuming that UAParser is a wallaby component, but its something one of my colleges added  and there seems to be something wrong with the wiredep setup. 

Thanks for your quick response! Now everything works.

**Comment by ArtemGovorov** [comment]
@johannesjo Awesome, thanks for the update.
