### ISSUE TITLE
Wallaby moves gzipped files in a way that alters the files

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#950]
For example if I have the following gzipped file contents:

```
ã
«1Ä ¿ûWláR‡õûà!úa/D}Ω&”åsK©çß«ì1ø¯ø∏§çZ%VÕì∑£?Sò– ˜’Öƒ&µÈtmµíp{©B?ÈrÖeZ
```

it gets moved to /403206ad672a2e7f/original and its contents become:

```
�
�1� ��Wl�R����!�a/D}�&ӌsK���Ǔ1������Z%V͓��?S�� �Յ�&��tm��p{�B?�r�eZ
```

I've tried various configurations such as `{instrumented: false}` as well as not specifying the file. From what I can tell is it doesn't matter--because the "original" file is moved incorrectly before it arrives in the "instrumented" folder. 

Why are the files gzipped? I'm writing tests for conditional logic regarding express compression. I'm using supertest to test express. As a result, I can't successfully set the content-encoding to gzip because of this. 

For example, here are `req.headers` in the Jest console:

```
{ 'accept-ranges': 'bytes',
      'cache-control': 'public, max-age=31536000',
      'last-modified': 'Sat, 14 Jan 2017 05:43:27 GMT',
      etag: 'W/"670-1599b808018"',
      'content-type': 'text/javascript; charset=utf-8',
      'content-length': '1648',
      'content-encoding': 'gzip',
      date: 'Sat, 14 Jan 2017 09:11:25 GMT',
      connection: 'close' }
```

And here they are in the Wallaby "console":

```
null
```

lol

### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Looks like I need to whitelist an extension so that wallaby correctly treats them as binary files. What's the extension for these file you're using? `*.gzip`?

**Comment by ArtemGovorov** [comment]
We just [published the core update v1.0.346](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) to properly support `.gz`/`.gzip` files. Please try it and let me know how it goes. Note that you'll need to delete the corrupted original files first.

**Comment by faceyspacey** [comment]
My files have the `.js` extension even though they're gzipped. I could make express route `.js` to `.js.gz`. 

I think the best option would be to leave it in the user's hands--at least as a fallback ;). So if there was a file config like: `{binary: true}` then we wouldn't have to be limited to supported file extensions.

**Comment by ArtemGovorov** [comment]
Fair enough, just added the `binary` flag support.
[Update wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and try this (make sure gzipped files/pattern go before the rest):
```javascript
files: [
  {pattern: 'src/gzipped.js', instrument: false, binary: true}
  ...
]
```

**Comment by fvanwijk** [comment]
Doc update?

**Comment by ArtemGovorov** [comment]
@fvanwijk Sure, will do shortly (IntelliJ needs a bit more work to support it).

**Comment by faceyspacey** [comment]
@ArtemGovorov confirmed. thanks again.
