### ISSUE TITLE
"Module not found" with TypeScript emitting ES6 & webpack

### ISSUE THREAD

**Issue by stevegreatrex** [wallabyjs/public#951]
### Issue description or question
When trying to combine Webpack, TypeScript, ES6 & WallabyJs in VSCode, wallaby cannot resolve modules from `.spec.ts` files.

See [twitter thread](https://twitter.com/SteveGreatrex/status/820164581041537024)

### Wallaby.js configuration file
[Reproduction repo](https://github.com/stevegreatrex/wallaby-bug-repro)

```javascript
See repo
```

### Code editor or IDE name and version
Visual Studio Code v1.0.37

### OS name and version
ubuntu 16.04

**Comment by ArtemGovorov** [comment]
Thanks for the repo. Sent you [the PR to wallaby config](https://github.com/stevegreatrex/wallaby-bug-repro/pull/1). As [specified in the wallaby webpack docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder), in cases like this absolute path to wallaby cache is required.

**Comment by stevegreatrex** [comment]
Fixed by https://github.com/stevegreatrex/wallaby-bug-repro/pull/1
