### ISSUE TITLE
node-config compatibility issue?

### ISSUE THREAD

**Issue by tompiarulli** [wallabyjs/public#953]
### Issue description or question

I'm using Wallaby with a project that uses [node-config](https://github.com/lorenwest/node-config), more specifically [feathers-configuration](https://github.com/feathersjs/feathers-configuration) and although my tests run fine via the CLI, in Wallaby when testing a service that loads from the configuration it fails due to a configuration variable being undefined.

### Wallaby.js configuration file

```javascript
module.exports = function setup(wallaby) {
  return {
    files: [
      'src/**/*.js', '!src/**/*.test.js'
    ],
    tests: [
      'src/**/*.test.js'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: ['latest', 'react', 'stage-2'],
        plugins: ['transform-runtime']
      })
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
I'm not sure if I understand the issue correctly, but perhaps you're missing your config file pattern(s) in the `files` list, like `'config/**/*.json'` (or wherever the config files are)? If it's not the case, please provide some more info how to reproduce the issue.

**Comment by tompiarulli** [comment]
Nailed it, totally didn't think of that - Thanks!
