### ISSUE TITLE
Support ... jasmin-given

### ISSUE THREAD

**Issue by royiHalp** [wallabyjs/public#955]
### Issue description or question
what about support for jasmin-given?

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm v11
IntelliJ IDEA v15
Visual Studio 2015
Visual Studio 2013
Atom v1.x
Visual Studio Code v1.x
Sublime Text v3

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Just tried and it seems to work with wallaby.js.

![given](https://cloud.githubusercontent.com/assets/979966/22050372/102cddda-dd86-11e6-9966-055b175dab4a.gif)

All I had to do was
```
npm install jasmine-given
```
in the project and add the framework to the `files` list ([like any other helper/globally loaded framework](https://wallabyjs.com/docs/config/files.html)):
```javascript
module.exports = function () {

  return {
    files: [
      { pattern: 'node_modules/jasmine-given/dist/jasmine-given.js', instrument: false },
      ...
    ],

    ...
  };
};

```

Let me know if you're hitting any specific issues with `jasmine-given`.
