### ISSUE TITLE
Error when I try to run wallaby js 

### ISSUE THREAD

**Issue by daBishMan** [wallabyjs/public#956]
### Issue description or question
The test do not run, I get errors when I start the server.  I am using angular-cli.beta.25.5, angular 2.4.1

I get the following error in the visual studio code.

```
​​​​​0 failing tests, 0 passing​​​​​

​​ReferenceError: Can't find variable: Map​​
​​at http://localhost:63188/__modules/42.js?1484671366823:80​​
​​ReferenceError: Can't find variable: Map​​
  at ​src/app/core/analytics/analytics.service.spec.ts:3​
​​ReferenceError: Can't find variable: Map​​
  at ​src/app/core/services/actions/actions.service.spec.ts:2​
```

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
      { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
      { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};```

### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
Windows 10 x64

**Comment by ArtemGovorov** [comment]
Looks like polyfills are not loaded, it usually happens when you forget to add the [wallaby.js test bootstrap file](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) to your project like described in the [angular-cli wallaby sample readme](https://github.com/wallabyjs/ngCliWebpackSample#wallabyjs).

**Comment by daBishMan** [comment]
I followed the example it worked on a new project, on my existing project I get 

> ​​Error: Cannot find module "./profile-dialog.component.less"​​
  at ​src/app/profile/profile-dialog/profile-dialog.component.ts:11​
  at ​src/app/profile/profile-dialog/profile-dialog.component.ts:11​
  at ​src/app/profile/profile-dialog/profile-dialog.component.ts:13​
  at ​src/app/profile/profile-dialog/profile-dialog.component.spec.ts:2​
​​Error: Cannot find module "./profile-sidebar.component.less"​​
  at ​src/app/profile/profile-sidebar/profile-sidebar.component.ts:8​
  at ​src/app/profile/profile-sidebar/profile-sidebar.component.ts:8​
  at ​src/app/profile/profile-sidebar/profile-sidebar.component.ts:10​
  at ​src/app/profile/profile-sidebar/profile-sidebar.component.spec.ts:2​

but when you look at the code it is part of the styleUrls 

`  templateUrl: './profile-dialog.component.html',
  styleUrls: ['./profile-dialog.component.less']
})`

Any suggestions ?

**Comment by ArtemGovorov** [comment]
You'll [need to add `*.less` files](https://wallabyjs.com/docs/config/files.html) to the `files` list of your wallaby config. I have [updated the sample to include those files](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L32).

**Comment by daBishMan** [comment]
One more issue, please now I am getting

> Error: Module build failed: Can't resolve '../../node_modules/bootstrap/less/variables.less' in '.\src\app'​​
​​ @ C:\Users\Jay\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.39\projects\50045fbbb63477c8\instrumented\src\app\variables.less (line 1, column 0)​​
​​ near lines:​​
​​   ​​
​​   @import "../../node_modules/bootstrap/less/variables.less";​​
​​   ​​
​​at http://localhost:60108/src/app/profile/profile-dialog/profile-dialog.component.less.754.wbp.js?1484798040245&wallabyFileId=150:1​​
​​Error: Module build failed: Can't resolve '../../node_modules/bootstrap/less/variables.less' 

I am importing the file into my own less file

`@import "../../node_modules/bootstrap/less/variables.less";`

any suggestions?

For the record, I purchased your product.

**Comment by ArtemGovorov** [comment]
Try adding the file to your `files` list:

```javascript
...
module.exports = function (wallaby) {

  return {
    files: [
      ...
      { pattern: 'node_modules/bootstrap/less/variables.less', load: false }
      ...
    ],
...
```

**Comment by daBishMan** [comment]
I got it to work, thank you so much.   I am getting an exception in some test, that the angular-cli runs fine.
![image](https://cloud.githubusercontent.com/assets/5060855/22093540/af95d344-ddc3-11e6-9c01-07cad1239c75.png)

What is the cause of this error it does not make sense to me.

**Comment by ArtemGovorov** [comment]
angular-cli is [using Chrome](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/karma.conf.js#L40) to run your tests, wallaby.js is using PhantomJs by default and it looks to me like it's not happy about some syntax in some of your modules. You may switch to [Electron test runner](https://wallabyjs.com/docs/integration/electron.html) in wallaby to essentially run your tests in the same JS engine (Chrome V8), however the failing tests in PhantomJs may mean that your code will not work in Safari and some other older browsers, so if your app targets those browsers, I'd investigate the issue further - if not, I'd just switch to Electron runner.
