### ISSUE TITLE
App coverage reverts to out-of-date values on file save (VSCode)

### ISSUE THREAD

**Issue by grantbowering** [wallabyjs/public#957]
### Issue description or question
As I'm typing a test, the app continually updates to show coverage.  While the file is modified in memory in the IDE, all is well, but when I save the file, the wallaby app "updates" the coverage stats and code highlights displayed to a previous, now inaccurate state (I believe it might be the state when I last restarted wallaby in the IDE, but I haven't tested that extensively).  Lines that had become covered change back to appearing as not covered.  Typing anything else in the file after saving causes it to re-evaluate and display current coverage again, until I hit save again and it reverts to older coverage again.
So far when this happens, I've restored the correct behavior for a little while by stopping and restarting wallaby, but that's obviously not desirable (and sorta time consuming, because a full webpack compile takes more than a few seconds).  A short time after doing so, I notice it happening again.
Note that I've only seen this happening to me in VSCode, I haven't seen it happen yet in VS2015, but I haven't been using VS2015 for client side tests much so I can't confirm whether it's VSCode-only or not.  I will try using 2015 for the rest of the day and see if I encounter the same issue.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var Module = require('module').Module;
var modulePrototype = Module.prototype;
var originalRequire = modulePrototype.require;
modulePrototype.require = function (filePath) {
    if (filePath === 'source-map-support') {
        return { install: () => { } };
    }
    return originalRequire.call(this, filePath);
};

var webpackConfig = require('./webpack.config');

modulePrototype.require = originalRequire;

webpackConfig.module.loaders = [];
webpackConfig.resolve.extensions = ['', '.js', '.jsx'];
webpackConfig.entry = {};
delete webpackConfig.output;
delete webpackConfig.devServer;

// To support Enzyme
webpackConfig.module.loaders.push({
	test: /\.json$/,
	loader: 'json-loader'
});

webpackConfig.externals = webpackConfig.externals || {};
webpackConfig.externals.jsdom = 'window';
webpackConfig.externals.cheerio = 'window';
webpackConfig.externals['react/addons'] = true;
webpackConfig.externals['react/lib/ExecutionEnvironment'] = true;
webpackConfig.externals['react/lib/ReactContext'] = true;

// Per: https://github.com/davezuko/react-redux-starter-kit/issues/327
webpackConfig.node = webpackConfig.node || {};
webpackConfig.node.fs = 'empty';

module.exports = function (wallaby) {
	// Per https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder
	webpackConfig.resolve.root = [path.join(wallaby.projectCacheDir, 'App')];

	var webpackPostprocessor = wallabyWebpack(webpackConfig);

	return {

		files: [
			{ pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
			{ pattern: 'node_modules/json.date-extensions/json.date-extensions.js', instrument: false },
			{ pattern: 'Scripts/testSetup.js', instrument: false },
			{ pattern: 'App/**/*.ts?(x)', load: false },
			{ pattern: 'App/**/*.spec.ts?(x)', ignore: true }
		],

		tests: [
			{ pattern: 'App/**/*.spec.ts?(x)', load: false }
		],

		testFramework: 'mocha',

		compilers: {
			'App/**/*.ts*': wallaby.compilers.typeScript({
				module: 'es6'
			})
		},

		preprocessors: {
			'App/**/*.js': function (file) {
				return require('babel-core').transform(
					file.content, { sourceMap: true, presets: ['es2015', 'react'] });
			}
		},

		postprocessor: webpackPostprocessor,

		setup: function () {
			window.__moduleBundler.loadTests();
		},

		debug: false,
		hints: {
			ignoreCoverage: / coverage ignore next /
		}
	};
};
```

### tsconfig.json
```javascript
{
	"compilerOptions": {
		"moduleResolution": "node",
		"target": "es6",
		"jsx": "preserve",
		"experimentalDecorators": true,
		"sourceMap": true,
		"skipDefaultLibCheck": true,
		"allowSyntheticDefaultImports": true,
		"noImplicitAny": true,
		"baseUrl": ".",
		"paths": {
			"*": [
				"App/*",
				"node_modules/*",
				"App/typeOverrides/*"
			]
		},
		"typeRoots": [ "./node_modules/@types" ]
	},
	"awesomeTypescriptLoaderOptions": {
		"useBabel": true,
		"useCache": true
	},
	"exclude": [
		"node_modules"
	]
}
```

### webpack.config.js 
```javascript
/* eslint-disable no-var, strict, prefer-arrow-callback */
'use strict';

var path = require('path');
var webpack = require('webpack');
var progressPlugin = require('webpack/lib/ProgressPlugin');
var checkerPlugin = require('awesome-typescript-loader').CheckerPlugin;

function progressHandler(percentage, msg) {

	if (percentage < 1) {
		percentage = Math.floor(percentage * 100);
		msg = percentage + '% ' + msg;
		if (percentage < 100) {
			msg = ' ' + msg;
		}
		if (percentage < 10) {
			msg = ' ' + msg;
		}
	}

	process.stdout.write('                                              \r' + msg + '\r');
}

module.exports = {
	cache: true,
	entry: {
		main: './App/main.tsx',
		vendor: [
			'isomorphic-fetch',
			'babel-polyfill',
			'bootstrap',
			'react',
			'react-bootstrap',
			'react-bootstrap-table',
			'react-datepicker',
			'react-dom',
			'react-measure',
			'react-router',
			'react-router-bootstrap',
			'redux',
			'redux-thunk',
			'react-router-redux',
			'moment',
			'moment-business',
			'seamless-immutable',
			'classnames',
            'json.date-extensions'
		]
	},
	output: {
		path: path.resolve(__dirname, './dist/scripts'),
		filename: '[name].js',
		chunkFilename: '[chunkhash].js'
	},
	module: {
		loaders: [
			{
				test: /\.ts(x?)$/,
				exclude: /node_modules/,
				loader: 'babel-loader?presets[]=es2015&presets[]=react!awesome-typescript-loader'
			},
			{
				test: /\.js$/,
				exclude: /node_modules/,
				loader: 'babel',
				query: {
					presets: ['es2015', 'react']
				}
			},
			{ test: /\.css$/, loader: 'style!css' }
		]
	},
	plugins: [
		// Maps these identifiers to the jQuery package (because Bootstrap expects it to be a global variable)
		new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' }),
		new progressPlugin(progressHandler),
        new checkerPlugin()
	],
	resolve: {
		// Add `.ts` and `.tsx` as a resolvable extension.
		extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
		root: [
			path.resolve('./App'),
			path.resolve('./node_modules')
		]
	},
	devServer: {
		contentBase: '.',
		host: 'localhost',
		port: 9000
	}
};
```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

Windows 8.1

**Comment by ArtemGovorov** [comment]
> While the file is modified in memory in the IDE, all is well, but when I save the file, the wallaby app "updates" the coverage stats and code highlights displayed to a previous, now inaccurate state

Just to make it clear, the issue is only showing up in [the wallaby app](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html) while saving files in VS Code, but not in the VS Code editor itself, where coverage indicators are still displayed correctly, right?

**Comment by ArtemGovorov** [comment]
After running a few projects/tests, I can't reproduce the issue in wallaby app. Here's what I do:
- open a project in VS Code,
- start wallaby,
- open http://wallabyjs.com/app/#/files,
- add a test that increases the code coverage (without saving),
- observe coverage summary and indicators changed in the app,
- save the file in VS Code,
- observe coverage summary and indicators stay the same as expected in the app.

![app](https://cloud.githubusercontent.com/assets/979966/22050036/24ef2500-dd83-11e6-95ce-d78161f53de4.gif)

What am I missing? Could you perhaps extract a reproducible sample that I could have a look into?

**Comment by grantbowering** [comment]
It'll take me a little while to get a chance to get a reproduction together, but I haven't forgotten about this ticket, I'm just commenting so that you know I saw your request and I'll get to it this weekend hopefully.  Thanks :)

**Comment by grantbowering** [comment]
I haven't had the chance to whittle down a repro, but here's a bullet point that might help shed some light:
I don't get this behavior in VS 2015, but what does happen is that wallaby will get "stuck" partway through the test execution,  somewhere like "Execution progress: 250 tests" out of 500+ tests, and just not do anything anymore... The only way I can seem to get it going again is by making a whitespace change to my wallaby.js, which to my understanding causes a cache somewhere to be invalidated, and then it works again.  Could a problem with cache be the root cause of the VSCode issue as well?

**Comment by ArtemGovorov** [comment]
> Could a problem with cache be the root cause of the VSCode issue as well?

Unlikely, but hard to tell without the repro. 
Just in case, please check that you're using the latest `wallaby-webpack` package version.

**Comment by grantbowering** [comment]
Wow, it was WAY out of date, 0.0.23... I'll update it to 0.0.32 and see if that makes any difference (I don't see anything in the commit history since then that looks relevant, but one never knows)

**Comment by ankhzet** [comment]
Encountering the same issue. Like @grantbowering, I'm using typescript in junction with jasmine and wallaby. After some glitch, coverage web app stops reacting on updates. Wallaby by itself is working, but web app doesn't sync with it. Opening console shows zero reaction to updates in tests, refreshing app page spits 'Application Cache Progress event', but no actual changes are picked up (number of tests doesn't match, files structure not updated, code coverage not updated etc etc). Web app page is still working even if wallaby plugin is stopped, so I assume project structure is cached, but for some reason app stopped to update it's state.

Opening the coverage app in the Incognito mode in Chrome shows cached content firstly, but shortly after "Discovered running wallaby.js project Click here to open ...." tooltip is shown (dunno why it's not shown on page refresh in regular mode tab, maybe it's related to cause). When clicking on it, page refreshes and then works as expected, but only in that specific tab. Old tabs still show cached contents, new incognito tabs as well, until you click on mentioned tooltip.
Also, refreshing incognito tab before tooltip is shown results in it not showing at all afterwards.

**Comment by ankhzet** [comment]
Also, after updating Chrome, app seems to start trying to connect to wallaby instance on each new tab opened just like in incognito mode (it spits 'WebSocket connection to 'ws://127.0.0.1:53582/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED' errors to console and then shows 'Discovered running wallaby.js project' tooltip, thus allowing to connect to wallaby instance), but app itself works as expected only if you click on suggested 'Discovered running wallaby.js project' tooltip. If you ignore it, it won't be shown on future page refreshes, thus only old project cache will be shown. In new opened tab it will show tooltip again, but won't show afterwards in the same tab no matter how mush you refresh it.

Some subtle manual-discover link somewhere near 'Light theme'/'Need help?' links would be helpful as a temporary workaround. Also, does coverage app not support multiple wallaby instances management? Being able to look the list of active instances and choose which to connect to in each separate browser tab may come in handy.

**Comment by ArtemGovorov** [comment]
@ankhzet Thanks for the detailed description! From what you've described, it doesn't look like it's the issue with wallaby app. Looks like somehow (perhaps IDE crash), there's one instance of orphaned wallaby core process is left running (even though the plugin is stopped), so it messes up the displayed app results (by reporting whatever old results it has). Try stopping wallaby, killing all node processes on the machine (or restarting it), it should help.

**Comment by ankhzet** [comment]
Yup, that was the case. App is now correctly reconnects immediately in the new tabs and on refresh.
Thanks for the quick reply, @ArtemGovorov =).

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity.
