### ISSUE TITLE
symlinked node_modules in lerna project structure

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#959]
### Issue description or question
I have a monorepo that uses LernaJS to bootstrap the packages.

#### Example
There are two packages `A` and `B`, where `B` is the dependency of `A`.

This is what the paths look like:

packages/A
packages/B
packages/A/node_modules/B

#### Problems

1. On initial start, `B` is instrumented twice. Once for the path `packages/B` and once for `packages/A/node_modules/B`. Would it be possible to detect that `packages/B` was already compiled so that `packages/A/node_modules/B` doesn't get processed as well? I think it will shorten the time it takes for the project to start.
2. If `B` is changed, only the tests related to `B` will be affected. Tests belonging to `A` are ignored. This seems to be only occurring in WebStorm and not VSCode.

I have thought of ignoring the `node_modules` under `packages` entirely and update `process.env.NODE_PATH` to reference those `node_modules`, but I wanted to see if there's a better solution.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      {
        pattern: "packages/**",
      },

      {
        pattern: "packages/**/__tests__/**",
        ignore: true
      }
    ],

    tests: [
      {
        pattern: "packages/**/__tests__/**",
      },

      {
        pattern: "packages/**/node_modules/**/__tests__/**",
        ignore: true
      }
    ],

    testFramework: "jasmine",

    env: {
      type: "node",
    },

    loose: true,

    delay: {
      run: 1000
    },

    filesWithNoCoverageCalculated: [
      "**/node_modules/**"
    ],

    debug: true,

    reportConsoleErrorAsError: true,
  };
};
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows

Thank you.

**Comment by ArtemGovorov** [comment]
The solution is described in https://github.com/wallabyjs/public/issues/960#issuecomment-273674519
