### ISSUE TITLE
creation of new blank test triggers reprocessing of all files

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#960]
### Issue description or question

I noticed that upon adding a new blank test, WallabyJS reprocesses everything like it does during the initial startup. Is there a configuration that I can set so that this doesn't happen?

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      {
        pattern: "packages/**",
      },

      {
        pattern: "packages/**/__tests__/**",
        ignore: true
      }
    ],

    tests: [
      {
        pattern: "packages/**/__tests__/**",
      },

      {
        pattern: "packages/**/node_modules/**/__tests__/**",
        ignore: true
      }
    ],

    testFramework: "jasmine",

    env: {
      type: "node",
    },

    loose: true,

    delay: {
      run: 1000
    },

    filesWithNoCoverageCalculated: [
      "**/node_modules/**"
    ],

    debug: true,

    reportConsoleErrorAsError: true,
  };
};
```

### Code editor or IDE name and version
WebStorm v11

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Could you please create a sample repo with your config demonstrating this this issue and the issue https://github.com/wallabyjs/public/issues/959 as well?

**Comment by thomastnguyen91** [comment]
Sample: https://github.com/thomastnguyen91/wallaby-issue-959.

You can use this for both issues. In creating the sample, it seems that issue #960 only occurs when it's a typescript project.

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I can confirm I can reproduce both issues. You're also correct that #960 is only reproduced for typescript project (identical javascript project works fine), thanks for the note. 

Looking into the issues now.

**Comment by ArtemGovorov** [comment]
I have fixed the bug in wallaby.js core and published it, so [you may force the update and try it](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). 

I have also sent you [the pull request](https://github.com/thomastnguyen91/wallaby-issue-959/pull/1) to make it correctly work with your package structure to close https://github.com/wallabyjs/public/issues/959. As you've been suggesting, the best way to make it work is to simply exclude `node_modules` and specify `NODE_PATH` to point to the wallaby cache, that is what I have done in the pull request.

**Comment by thomastnguyen91** [comment]
I updated the core to v1.0.351, but I get the following log when I add `test.ts` to `packages/B/__tests__`. Is this correct?

Thu, 19 Jan 2017 04:12:51 GMT wallaby:project File packages/B/__tests__/test.ts changes are patches only: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/B/__tests__/test.ts
Thu, 19 Jan 2017 04:12:51 GMT wallaby:processor No compilers found for packages/B/__tests__/test.ts
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project File packages/B/__tests__/test.ts is not instrumented by core
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/B/__tests__/test.ts
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/B/__tests__/test.ts
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project File packages/B/__tests__/test.ts changes saved, store ts: 1484799171000, change ts: 1484799171180
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Running postprocessor
Thu, 19 Jan 2017 04:12:51 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Thu, 19 Jan 2017 04:12:51 GMT wallaby:postprocessor TypeScript language service re-created because some tracked files were added or deleted
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/A/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/B/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/A/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/B/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Preparing to process packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processing compiled packages/A/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Instrumenting packages/A/index.js, via process pool: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processing compiled packages/B/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Instrumenting packages/B/index.js, via process pool: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processing compiled packages/A/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Instrumenting packages/A/__tests__/index.js, via process pool: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processing compiled packages/B/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Instrumenting packages/B/__tests__/index.js, via process pool: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processing compiled packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Instrumenting packages/B/__tests__/test.js, via process pool: false
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/A/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/B/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/A/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/B/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project No preprocessors configured for packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/A/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/B/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/A/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/B/__tests__/index.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Writing to disk and caching processed file packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Postprocessor execution finished
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Test run started; run priority: 2
Thu, 19 Jan 2017 04:12:51 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Thu, 19 Jan 2017 04:12:51 GMT wallaby:workers Starting test run, priority: 2
Thu, 19 Jan 2017 04:12:51 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #xf6hg]
Thu, 19 Jan 2017 04:12:51 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #xf6hg]
Thu, 19 Jan 2017 04:12:51 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #xf6hg]
Thu, 19 Jan 2017 04:12:51 GMT wallaby:workers Running tests in sandbox [worker #0, session #xf6hg]
Thu, 19 Jan 2017 04:12:51 GMT wallaby:workers Loaded 0 test(s)
Thu, 19 Jan 2017 04:12:51 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Thu, 19 Jan 2017 04:12:51 GMT wallaby:workers Sandbox [xf6hg] is responsive, closing it
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Test run finished
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processed console.log entries
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processed loading sequences
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processed executed tests
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Processed code coverage
Thu, 19 Jan 2017 04:12:51 GMT wallaby:project Test run result processed and sent to IDE

**Comment by ArtemGovorov** [comment]
Yes, it's expected. Once the file is added and you start editing it, wallaby will perform much less work (than when adding it).

**Comment by thomastnguyen91** [comment]
Is there no way to mitigate the workload for adding the file? For a small project, it finishes relatively fast, but as the number of files increase, it can take awhile for the process to finish.

**Comment by thomastnguyen91** [comment]
I converted the sample repo to use babel and this is the log that I get. Would it be possible for typescript version to do the same?

```
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project File packages/B/__tests__/test.js changes are patches only: false
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Preparing to process packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:processor Running 1 processor(s) for packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:processor Finished running one processor for packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Compiler did not set ranges for file [packages/B/__tests__/test.js]
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Processing compiled packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Instrumenting packages/B/__tests__/test.js, via process pool: false
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project No preprocessors configured for packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Writing to disk and caching processed file packages/B/__tests__/test.js
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project File packages/B/__tests__/test.js changes saved, store ts: 1484800561000, change ts: 1484800561461
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Test run started; run priority: 2
Thu, 19 Jan 2017 04:36:01 GMT wallaby:testTask Test files from affected: 1, from deleted or manually requested: 0, from recently changed: 0, from loaded by: 0, from failing: 0
Thu, 19 Jan 2017 04:36:01 GMT wallaby:workers Starting test run, priority: 2
Thu, 19 Jan 2017 04:36:01 GMT wallaby:nodeRunner Starting sandbox [worker #0, session #xzl47]
Thu, 19 Jan 2017 04:36:01 GMT wallaby:nodeRunner Preparing sandbox [worker #0, session #xzl47]
Thu, 19 Jan 2017 04:36:01 GMT wallaby:nodeRunner Prepared sandbox [worker #0, session #xzl47]
Thu, 19 Jan 2017 04:36:01 GMT wallaby:workers Running tests in sandbox [worker #0, session #xzl47]
Thu, 19 Jan 2017 04:36:01 GMT wallaby:workers Loaded 0 test(s)
Thu, 19 Jan 2017 04:36:01 GMT wallaby:workers Run 0 test(s), skipped 0 test(s)
Thu, 19 Jan 2017 04:36:01 GMT wallaby:workers Sandbox [xzl47] is responsive, closing it
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Test run finished
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Processed console.log entries
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Processed loading sequences
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Processed executed tests
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Processed code coverage
Thu, 19 Jan 2017 04:36:01 GMT wallaby:project Test run result processed and sent to IDE
```

**Comment by ArtemGovorov** [comment]
Babel operates on a file basis, while TypeScript needs to access all files during compilation.

TypeScript incremental compilation is known to sometimes fail/break when adding/deleting files, that's why we restart TS compiler on files adding/deleting. While it may take longer to finish in larger projects, the effect is normally not noticeable: 
- you don't add new files to your project very frequently (comparing to how much time you spend editing them),
- when you're adding an empty file there's nothing to be reported for it anyway, so while you're spending a few seconds to add something meaningful to the file (that wallaby can report) - the chances are the recompilation will be finished by then and you won't even notice it.

**Comment by thomastnguyen91** [comment]
I see your point. I guess there is nothing you can do about it if TypeScript has to be greedy during compilation. Thank you for the help.

**Comment by ArtemGovorov** [comment]
We may add a setting that will suppress TypeScript compiler to restart on adding/deleting files, and it should hopefully work for you in most of the cases, but beware of some strange compiler behaviour when mass adding/deleting files. Would you like us to add the setting for you?

**Comment by thomastnguyen91** [comment]
Would it be possible for you to add that as an experimental feature? I'll try and give feedback to improve it if needed.

**Comment by ArtemGovorov** [comment]
Sure, thanks, sounds good. Will let you know once it's added and how to configure it.
