### ISSUE TITLE
Tests run with wallaby are unable to require dependencies from parent node_module directories.

### ISSUE THREAD

**Issue by thuey** [wallabyjs/public#961]
### Issue description or question
I am using a monorepo that uses asini to hoist common dependencies to the root of the monorepo. This works fine for development and running tests through the command line. However, when I try to use wallaby, I get errors that it is unable to find modules that are installed at the root of the monorepo. I created a very simple repo here to demonstrate the issue: https://github.com/thuey/wallaby-mono.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*.js'
    ],

    env: {
      type: 'node'
    }
  };
};
```

### Code editor or IDE name and version

Atom v1.13.0

### OS name and version

OSX - 10.11.6

**Comment by ArtemGovorov** [comment]
Thanks for the repo!
Ideally I'd recommend placing wallaby.js config file to the root of the repo (and change the paths in the config). If you can't do it, then you may [use this recipe](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) to point node to the location of the modules. I have sent you [the PR for your sample project](https://github.com/thuey/wallaby-mono/pull/1).

**Comment by thuey** [comment]
Thanks for the response! Unfortunately, neither of those workarounds is great for my situation. Asini will hoist common modules to the root of the monorepo, while leaving modules with conflicting versions installed in each package's own node_modules. So I really need it to look in both places. This normally works well because when requiring modules in node, it naturally traverses upwards checking for node_modules in ancestor directories. So is there something about the environment that Wallaby is running in that prevents node from doing this? If so, I'll either have to figure out a different way of structuring our mono repos, or Wallaby might just not be a great fit for our use case.

**Comment by ArtemGovorov** [comment]
> So I really need it to look in both places. 

The config in the pull request I've sent you should work exactly like this. It'll look for the node modules in the package `node_modules` folder and in the hoisted `node_modules` folder.

> So is there something about the environment that Wallaby is running in that prevents node from doing this?

Yes, wallaby run your tests from its [own file cache](https://wallabyjs.com/docs/intro/how-it-works.html#wallabyjs-cache), it also adds the same level `node_modules` to look at by default. So when node  traverses upwards checking for node_modules in ancestor directories, it does it in the wallaby cache, where the node modules do not exist (copying them over is not really a good idea). 

Having said that, the [suggested solution](https://github.com/thuey/wallaby-mono/pull/1/files) should fully work for you scenario, unless I'm missing something, in which case please let me know and we'll figure it out to make it work for you.

**Comment by damonmaria** [comment]
@ArtemGovorov  Thought I would post here rather than re-opening this / opening a new issue. I'm currently using the recipe linked above to work with `node_modules` in a subfolder. The issue is I have multiple subfolders like this and adding their `node_modules` to the global path `NODE_PATH` means that if I've missed adding a package to `package.json` / `node_modules` in one of those subfolders, but it's in another, then my tests will pass but fail in a real setting. 

Ideally Wallaby would look back through the ancestor directories of where the file came from as that would match reality.

**Comment by damonmaria** [comment]
Or what if when Wallaby was putting files into the cache it scanned for and symlinked to any `node_modules` found in ancestor dirs in the project dir when directories are created in the cache? Could that also solve #68?

**Comment by ArtemGovorov** [comment]
@damonmaria Your scenario is a bit different, however, I absolutely agree that

> Ideally Wallaby would look back through the ancestor directories of where the file came from as that would match reality.

We have an idea how to implement it, and will be doing it soon. The new version will allow you not not specify the `NODE_PATH` at all. 

@thuey your scenario will also work without specifying `NODE_PATH`, so stay tuned.

**Comment by ArtemGovorov** [comment]
@thuey @damonmaria Hey guys, as promised, I have published the new version of wallaby.js core that addresses the issue. You may [update your wallaby.js core to the latest version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and will not need to specify the `NODE_PATH` any more. Please try it and let me know how it works for you.

**Comment by damonmaria** [comment]
I just updated:
````
wallaby.js started
core v1.0.353
````

But it can't find my `babel-polyfill` which is in a child folder. Is this maybe because I `require('babel-polyfill')` in the config `bootstrap`? But I think that's the appropriate place to do it.

**Comment by ArtemGovorov** [comment]
> Is this maybe because I `require('babel-polyfill')` in the config bootstrap? 

Correct, `bootstrap` is executed in the context of a folder where wallaby.js config is, so node look back through the ancestor directories (but not in subdirectories). So in this case it's not a wallaby.js specific issue. Say you had a few different `'babel-polyfill'` installed in various subfolders - which one would you want wallaby/node to pick?

**Comment by ArtemGovorov** [comment]
@damonmaria In your case you may do: 

```javascript
    bootstrap: function (w) {
      require(require('path').join(w.localProjectDir, 'subfolder/node_modules/babel-polyfill'));
    }
```

**Comment by damonmaria** [comment]
Great, that works. And I no longer need `NODE_PATH`. Thanks @ArtemGovorov, that's awesome. Nice change.

**Comment by thuey** [comment]
@ArtemGovorov Thanks for the fast response time on this. After updating wallaby-core, it started working for the example I sent you. However, it still would not work for my actual project. In my attempts to keep my example as simple as possible, I might have over-simplified it. I'm also using webpack and electron.

To investigate, I added webpack and electron to my example repo. Under this combination, I once again get errors about not being able to find modules that are installed at the parent level. It should be noted that this is also true when using the default environment (which I believe is PhantomJS). 

I've updated my example repo with both webpack and electron for thoroughness. Is there a setting I need to change in webpack for this to work? I'll also try out your other work arounds when I get a chance and let you know how that goes.

**Comment by thuey** [comment]
As you probably suspected, that didn't work. I'm guessing because the workaround you suggested would only work for a node environment.

**Comment by ArtemGovorov** [comment]
@thuey 
> I'm also using webpack and electron. 

It's a different (wallaby/webpack specific) issue, here [the described solution](https://wallabyjs.com/docs/integration/webpack.html#module-resolution-issues) in our webpack docs. I have sent you [the pull request](https://github.com/thuey/wallaby-mono/pull/2/commits/f50c9d3b47a650039562dc63a3bc3a6089220e93) to make it work.
