### ISSUE TITLE
​​SyntaxError: Unexpected token 'const'​​ for typescript project

### ISSUE THREAD

**Issue by tedwong** [wallabyjs/public#962]
### Issue description or question
​​SyntaxError: Unexpected token 'const'​​ for typescript project.
Git Hub:
https://github.com/tedwong/testWallaby

### Wallaby.js configuration file
```javascript
'use strict';
var babel = require('babel-core');
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
  // browserify options, such as insertGlobals: false
}
// you may also pass an initializer function to chain other browserify options,
// such as transformers , b =>
// b.exclude('mkdirp').transform(require('babelify'))
);

module.exports = (wallaby) => {
  return {
    files: [
      {
        pattern: 'node_modules/chai/chai.js',
        instrument: false
      }, {
        pattern: 'src/*.ts',
        load: false
      }
    ],
    tests: [
      {
        pattern: 'tests/*spec.ts',
        load: false
      }
    ],
    compilers: {
      'src/*.ts': wallaby.compilers.typeScript({
          "outDir": "./ts-build/",
          "sourceRoot": "./src",
          "sourceMap": true,
          "noImplicitAny": true,
          "moduleResolution": "node",
          "module": "commonjs",
          "target": "es6",
          "allowJs": true,
          "experimentalDecorators": true
        })
    },
    testFramework: "mocha",
    postprocessor: wallabyPostprocessor,
    bootstrap: function (wallaby) {
      var mocha = wallaby.testFramework;
      mocha.ui("bdd");
      window.chai = chai;
      window.expect = chai.expect;
      // required to trigger tests loading
      window
        .__moduleBundler
        .loadTests();
    },
    debug: true
  };
};
```
### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
OSX

Screen cap for references:
![screen shot 2017-01-20 at 10 04 03 pm](https://cloud.githubusercontent.com/assets/188722/22152199/a17e3194-df5c-11e6-9552-e5c8c155681b.png)

**Comment by ArtemGovorov** [comment]
Your TypeScript config targets ES6: `"target": "es6",` and wallaby.js by default is using PhantomJs that doesn't fully support ES6.

You may either:
- change the TypeScript options to target ES5: `"target": "es5",`
- or configure wallaby to use [Chrome/V8 engine via Electron](https://wallabyjs.com/docs/integration/electron.html) that fully supports ES6.

**Comment by tedwong** [comment]
I got a new error after I use the electron, I globally install electron. After that, I got this error:

> ​​​​​[Info]​​​​​ Sat, 21 Jan 2017 09:38:12 GMT wallaby:workers Sandbox (active) [29fv7] error: ReferenceError: window is not defined
> ​​[Error] Runtime error: ReferenceError: window is not defined​​
> ​​[Error]     at emitTwo (events.js:87:13)​​
> ​​[Error]     at WebSocket.emit (events.js:172:7)​​

Here is my updated config:

> 
> 'use strict';
> var wallabify = require('wallabify');
> var wallabyPostprocessor = wallabify({
>   // browserify options, such as insertGlobals: false
> }
> // you may also pass an initializer function to chain other browserify options,
> // such as transformers , b =>
> // b.exclude('mkdirp').transform(require('babelify'))
> );
> 
> module.exports = (wallaby) => {
>   return {
>     files: [
>       {
>         pattern: 'src/*.ts',
>         load: false
>       }
>     ],
>     tests: [
>       {
>         pattern: 'tests/*spec.ts',
>         load: false
>       }
>     ],
>     compilers: {
>       'src/*.ts': wallaby
>         .compilers
>         .typeScript({
>           "outDir": "./ts-build/",
>           "sourceRoot": "./src",
>           "sourceMap": true,
>           "noImplicitAny": true,
>           "moduleResolution": "node",
>           "module": "commonjs",
>           "target": "es6",
>           "allowJs": true,
>           "experimentalDecorators": true
>         })
>     },
>     testFramework: "mocha",
>     postprocessor: wallabyPostprocessor,
>     bootstrap: function (wallaby) {
>       var mocha = wallaby.testFramework;
>       mocha.ui("bdd");
>       window.chai = chai;
>       window.expect = chai.expect;
>       // required to trigger tests loading
>       window
>         .__moduleBundler
>         .loadTests();
>     },
>     env: {
>       type: 'node',
>       kind: 'electron',
>       options: {
>         width: 400,
>         height: 400
>       }
>     },
>     debug: true
>   };
> };

**Comment by ArtemGovorov** [comment]
> `ReferenceError: window is not defined`

It's because you've specified `type: 'node',` in your `env` setting for some reason. It has to be removed (or be `type: 'browser'` for electron runner):

```javascript
 env: {
      kind: 'electron',
      options: {
        width: 400,
        height: 400
      }
    },
```

>  I globally install electron

You need to either install it locally to your project's node_modules or, as [the docs say](https://wallabyjs.com/docs/integration/electron.html) specify the path to the installed executable in the `env.runner`.

**Comment by tedwong** [comment]
So wired, I locally installed, but it got the process.binding is not supported error:

```
​​​​​[Info]​​​​​ Sat, 21 Jan 2017 10:09:39 GMT wallaby:workers Sandbox (active) [amkke] error: Uncaught Error: process.binding is not supported
​​​​​[Info]​​​​​ Sat, 21 Jan 2017 10:09:39 GMT wallaby:workers Failed to map the stack to user code, entry message: Uncaught Error: process.binding is not supported, stack: Uncaught Error: process.binding is not supported
```

Is this related to the electron or in the wallaby?

**Comment by ArtemGovorov** [comment]
I'm not sure, have never seen the error. From googling it may happen some of the imported modules is using process.binding and browserify can't handle it.

I finally had a chance to clone [your repo](https://github.com/tedwong/testWallaby) to try and reproduce the issue, but I can't even run it, it's missing `wallabify`, `browserify` and other modules.

I did however notice your `npm test` command and it looks like you use mocha with ts-node to run your tests. If that's the case, then this wallaby config should work for you. But then I'm not sure why you needed `browserify` in the first place. How do you currently run your tests in your real project? In it browser tests or node tests you're running?

```javascript
module.exports = () => {
  return {
    files: [
      'src/*.ts'
    ],
    tests: [
      'tests/*spec.ts'
    ],
    env: {
      type: 'node'
    },
    debug: true
  };
};
```

If you need wallaby to run your tests via browserify build, then please update your test repo so I could reproduce the issue with the `process.binding`.

**Comment by tedwong** [comment]
@ArtemGovorov  Thanks for your help. I finally rebuild .js based on your example as follow to solve the issue:

> module.exports = () => {
>   return {
>     files: [
>       {
>         pattern: 'node_modules/chai/chai.js',
>         instrument: false
>       },
>       'src/*.ts'
>     ],
>     tests: ['tests/*spec.ts'],
>     env: {
>       type: 'node'
>     },
>     debug: true,
>     testFramework: "mocha",
>     setup: function () {
>       // window.expect = chai.expect;
>     }
>   };
> };
> 
>
