### ISSUE TITLE
Support in-editor output of non-console loggers

### ISSUE THREAD

**Issue by carlansley** [wallabyjs/public#964]
### Issue description or question

Is there a way to have something other than `console.log` show output in the editor?  In our case, we use the `debug` module:

```
import * as debug from 'debug';

const log = debug('test');

log('hello');   // print 'hello' here, same as console.log
```

Is this possible to configure, or not currently supported?

### Code editor or IDE name and version

WebStorm 2016.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Currently it's not supported, here's the [feature request](https://github.com/wallabyjs/public/issues/165) you may subscribe to
