### ISSUE TITLE
Resize Electron window inside the tests?

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#965]
### Question

Hello, new user here...

Is it possible to change the _Electron window size_ from inside the tests? I would like to run assertions on the positioning of HTML elements given different window sizes. I'm using Mocha for now, if it counts.

I would need to dynamically change the options values in a `before` hook. Can give a link to my Github repo if needed.

```
env: {
      kind: 'electron',
      options: { width: 400, height: 400 }
    }
```

Thank you!

### Code editor or IDE name and version

Visual Studio Code v1.9

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Unfortunately changing the *Electron window size* from the context of your tests is not possible. 

Wallaby.js (as well as karma, or mocha/jasmine in browser, and other browser test runners) runs tests in a context of a test web page. So your tests run in browser context and can only do as much as your browser application can.

Having said that, you may try using `window.resizeTo(100, 100);` or change the size of your root element container (and trigger window resize event if needed) in your tests,

**Comment by bfulop** [comment]
I just tried in a `before` hook:

```
   window.resizeTo(1400, 1700)
   windowWidth = window.innerWidth
   windowWidth // 800
```

Wallaby still reports `window.innerWidth`  as `800`. 

I was wondering if it could be possible to make the Electron `BrowserWindow` object globally available during `setup`? 

My goal is to be able to test the layout of elements at different screen sizes. (granted, not a common scenario, but would make my life a lot easier)

**Comment by ArtemGovorov** [comment]
> I was wondering if it could be possible to make the Electron `BrowserWindow` object globally available during `setup`?

The `setup` function is executed in a different context (Electron renderer process) so there's no direct access to the `BrowserWindow` (which is in the main Electron process) there.

Even though **I don't think it is a great idea**, but I have added an RPC channel to change the `BrowserWindow` size. It is:
- bit hacky,
- electron specific, 
- and I'd rather recommend changing the root container size to test what you're testing (to make your tests hosting process agnostic). 

But if you are 100% want to do it, you may [update your wallaby.js core to the latest version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and do this:

```javascript
    setup: function (wallaby) {
      // or whatever name you like
      window.resizeToAsync = function (width, height, done) {
        var ipc = require('electron').ipcRenderer;
        ipc.send('resizeWindow',
          {
            pageId: window.location.href[window.location.href.lastIndexOf('.') - 1],
            width: width,
            height: height
          });
        ipc.once('resizeWindow', done);
      };
      ...
    },
```
and then in your tests you may do:

```javascript
describe('tests that require a specific window size', function() {
  beforeEach(function(done) {
    window.resizeToAsync(1000, 1000, done);
  });
  it('size test', function() {
    windowWidth = window.innerWidth
    windowWidth
  });
});
```

**Comment by bfulop** [comment]
Artem, thank you very much for taking the time to reply during the weekend!

I'm going to try your suggestion, but I had another idea this morning. What do you think of this approach, maybe less hacky. The idea is to rely on webdriverio to handle the browser part:

1. Run wallaby in NodeJS and import [Webdriverio standalone](http://webdriver.io/guide/getstarted/modes.html)  for the tests
2. Site running on an external server (external to Wallaby), hosting an html page where I will render my components into
3. In my test (spec) file import the Inferno/React component that I want to test
4. Render the component in the `before` hook and insert it in the html page (step 2.) with WebdriverIO [`selectorExecute`](http://webdriver.io/api/action/selectorExecute.html)
5. Run my assertions, and resize the browser window via WebdriverIO, etc

I think this should work well with Wallaby – as I type my code, it should be able to update the rendered page (step 4.) and rerun the assertions. I might even be able to see my component update _live_ in the browser window, interactive programming FTW!

The reason I want to actually change the browser window size is to trigger different media queries in the CSS.  I admit, I'm not totally sure what the _root container_ is. Does resizing it trigger the CSS breakpoints?

I will only be able try this strategy tomorrow morning, but if you confirm that this could work, I will definitely give it a try!

**Comment by ArtemGovorov** [comment]
I have never worked with webdriverio, so can't comment much about the approach, but I'd try the solution I have provided first - I've tried and it seem to work ok for window resizing.

> The reason I want to actually change the browser window size is to trigger different media queries in the CSS. I admit, I'm not totally sure what the root container is. 

I was thinking about having a root `div` element where you'd render your components to and then resizing it, but I don't think it'll work with media queries.

**Comment by bfulop** [comment]
Thanks! I've tested your suggestion and got `require` error, probably nothing complicated. 

I could not resist playing around WebdriverIO and it [almost works](https://github.com/wallabyjs/public/issues/967). I'm pretty excited about this setup, so I will give it a few more tries...

With WebdriverIO, I can delegate all browser-related tests to this module and later rerun the tests on a hosted cross browser testing service (Browserstack, etc).

**Comment by bfulop** [comment]
Just for reference, here's [the ticket](https://github.com/bfulop/interactive_frontend_dev/issues/8) I created in my repo on testing different screen sizes.
