### ISSUE TITLE
Don't rerun setup between two tests?

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#967]
Hello,

I've managed to successfully integrate [WebdriverIO standalone](http://webdriver.io/guide/getstarted/modes.html) into Wallaby. There's a slight problem though.

WebdriverIO let's you control browsers (Selenium) from your JavaScript environment. Before you can run your commands, you need to initialise a client, i.e. define the target browser, launch it, and point it to the target webpage (and wait for it to load).

I've added all this to the wallaby `setup` method, but it doesn't work the way I hoped. As soon as my tests have run, wallaby runs the `teardown` and now if I start modifying my code, Wallaby reruns the whole `setup` process (opening a new browser window, etc.)

Here's my `setup` method:

```
    setup: function (wallaby) {
      wallaby.delayStart()
      var webdriverio = require('webdriverio')
      var options = { desiredCapabilities: { browserName: 'firefox' } }
      var wdioclient = webdriverio.remote(options)
      wdioclient
        .init()
        .url('https://duckduckgo.com/')
        .then(function () {
          console.log('will start the testsss')
          global.wdioclient = wdioclient
          wallaby.start()
        })
    },

    teardown: function (wallaby) {
      global.wdioclient.end()
    }
```

I'm wondering how to solve this? What would be the best place for `wdioclient.init().url('https://duckduckgo.com/')` so that Wallaby doesn't have to rerun this part each time between two code modifications?

Here's the link to the [wallaby config file](https://github.com/bfulop/interactive_frontend_dev/blob/Feature-BowserTesting/wallaby.js)
And the [spec file](https://github.com/bfulop/interactive_frontend_dev/blob/Feature-BowserTesting/test/webdriverioSimple.js)

(This is a continuation from #965 )

**Comment by ArtemGovorov** [comment]
Nice, thanks for sharing!

The `setup` code runs before each test run by design, it allows you to initialize things before tests. If you'd like to only run some things once per process, you may do set/check some global flag:

```javascript
    setup: function (wallaby) {

      if(global._webdriverioInitialized) return;
      global._webdriverioInitialized = true;

      wallaby.delayStart()
      var webdriverio = require('webdriverio')
      var options = { desiredCapabilities: { browserName: 'firefox' } }
      var wdioclient = webdriverio.remote(options)
      wdioclient
        .init()
        .url('https://duckduckgo.com/')
        .then(function () {
          console.log('will start the testsss')
          global.wdioclient = wdioclient
          wallaby.start()
        })
    },
```

**Comment by ArtemGovorov** [comment]
Even may be checking the `global.wdioclient`, instead of creating a separate flag.

**Comment by bfulop** [comment]
Thanks for the reply, you beat me to it! 😎 I just had the same idea a minuet ago...

If you're interested, I can give you a summary once I get everything working. I haven't seen this setup so far.

**Comment by bfulop** [comment]
[This commit](https://github.com/bfulop/interactive_frontend_dev/commit/b83cf9600ba996a2f40b226f42f2dfad8414d080) now works perfect now!

So I can confirm that it is possible to __live test any browser__ with WebdriverIO and Wallaby! 🎉

**Comment by bfulop** [comment]
Maybe all that's missing is to run `global.wdioclient.end()` when I manually end Wallaby?

**Comment by ArtemGovorov** [comment]
Awesome, great job, will check it out in detail as soon as I can!

> Maybe all that's missing is to run `global.wdioclient.end()` when I manually end Wallaby?

This bit is a bit tricky, as there's no special wallaby API for it. But you may try the [process `beforeExit` or `exit` event subscriptions](https://nodejs.org/api/process.html#process_event_beforeexit):

```javascript

process.on('beforeExit', () => global.wdioclient && global.wdioclient.end());

module.exports = function (wallaby) {
  ...
```

**Comment by bfulop** [comment]
Here's a teaser. I'll continue tomorrow with rendering React/Inferno into the target browser and testing that. For now this is just WebdriverIO updating the browser (no React)

![wallabytest2](https://cloud.githubusercontent.com/assets/1718128/22201379/8de75e5e-e163-11e6-8fd2-aa4c8e54d71c.gif)

**Comment by ArtemGovorov** [comment]
Wow, looks so cool!
