### ISSUE TITLE
vs code can't find wallaby.js commands

### ISSUE THREAD

**Issue by Shayac** [wallabyjs/public#969]
### Issue description or question
Editor can't seem to find the wallaby commands even though they are in the command palette. For eg. selecting `Wallaby.js: Start` from the command palette just gives me `command 'wallaby.start' not found`. 
Uninstalling the wallaby extension and reinstalling it didn't help. Neither did restarting the editor.

### Code editor or IDE name and version
Visual Studio Code v1.9.0-insider

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
> Visual Studio Code v1.9.0-insider

Does it work for you in the stable 1.8.1?

**Comment by Shayac** [comment]
Yes. it does work. It was working for me in the insider edition too for a nice little while. It was only when I tried using it in the stable edition that it broke for me in the insider edition.

**Comment by ArtemGovorov** [comment]
Sounds like there must be some changes in the insider build that broke it. I suggest to use the stable build for now, we'll investigate the insider version soon.

**Comment by ArtemGovorov** [comment]
I can't reproduce it the insiders build. Everything installs and works for me as expected. Could you please try 
- uninstalling the extension from the insiders build instance,
- reinstalling the insiders build,
- opening the `/Users/username/.vscode-insiders/extensions/` folder and making sure there's no `WallabyJs.wallaby-vscode-1.0.39` subfolder there,
- starting the insiders build,
- installing wallaby.js extension.
Right after installing it, you should see this message:
<img width="843" alt="screen shot 2017-01-24 at 8 38 42 am" src="https://cloud.githubusercontent.com/assets/979966/22226098/a747ce80-e210-11e6-90b1-41761ec9e9e0.png">
and after a few seconds a couple more:
<img width="824" alt="screen shot 2017-01-24 at 8 38 54 am" src="https://cloud.githubusercontent.com/assets/979966/22226120/bb263bee-e210-11e6-995f-61c8a1bc3222.png">
Now you may try using the shortcuts. If they still don't work, please 
- make and attach a screenshot of the Dev Tools console (`Cmd + Alt + I`)
- provide a list of other extensions that you have installed (perhaps there's a conflict with one of them).

**Comment by Shayac** [comment]
I should uninstall the whole insider build? or just the wallaby extension?

**Comment by ArtemGovorov** [comment]
First wallaby extension, then the whole insider build.

**Comment by Shayac** [comment]
I just `rm -rf`'ed the `extensions/Wallaby.js` folder and reinstalled. And now it seems to be working!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! Not sure what it was, perhaps a corrupted extension installation, though I haven't seen it happening before.

**Comment by sherm84** [comment]
Same here, I'm with vs code 1.15.1 webpack + angular 
OS: windows
deleting extensions/Wallaby.js doesn't help
On WebStorm working fine

**Comment by ArtemGovorov** [comment]
@sherm84 Just tried installing the extension in vs code 1.15.1, everything worked for me. Try re-installing the extension, you should see these messages:

<img width="824" alt="screen shot 2017-01-24 at 8 38 54 am" src="https://cloud.githubusercontent.com/assets/979966/22226120/bb263bee-e210-11e6-995f-61c8a1bc3222.png">

and after that you may start wallaby.

**Comment by sherm84** [comment]
tried, didn't help :(
![screenshot_5](https://user-images.githubusercontent.com/4091896/29618296-5bcd45d2-8820-11e7-9dc2-e15b3599e42f.png)

**Comment by ArtemGovorov** [comment]
@sherm84 Hmm, interesting.

Could you please try the following and attach the results:
- confirm that you see these messages when (re)installing the extension:
<img width="824" alt="screen shot 2017-01-24 at 8 38 54 am" src="https://cloud.githubusercontent.com/assets/979966/22226120/bb263bee-e210-11e6-995f-61c8a1bc3222.png">

- restart your VS Code, try starting Wallaby, open VS Code Dev tools (`Help - Toggle Developer Tools`), open the Console tab and copy/paste its content here.
- download [VS Code insiders build]()https://code.visualstudio.com/insiders and install only wallaby extension in it. Then run it to see if it works or not.
- open this folder: `c:\\Users\\USERNAME\\.vscode\\extensions\\`. Check how many folder that start with `WallabyJs.wallaby-vscode-...` in there. If it's more than one, delete all, restart VS Code, install wallaby and try again. If it's just one, open the `WallabyJs.wallaby-vscode-...` folder and share the content of the `package.json` file from the folder, and also the screenshot of the folder's content.

**Comment by sherm84** [comment]
It works now, the problem was in user settings. thanks
