### ISSUE TITLE
Not showing results in visual studio code

### ISSUE THREAD

**Issue by glendaviesnz** [wallabyjs/public#970]
### Issue description or question

Wallaby was running fine in Angular 2/Visual studio code project, but after recent update of wallaby it stopped reporting result - ie. it seems to load and run without any obvious errors, but the loading symbol keeps showing bottom right, and no wallaby indications show against line numbers in editor. 

Debug log is attached
[wallabylog.txt](https://github.com/wallabyjs/public/files/724957/wallabylog.txt)
.

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
const DefinePlugin = require('webpack/lib/DefinePlugin');
const ENV = process.env.ENV = process.env.NODE_ENV = 'test';

var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'config/spec-bundle.js',
        'src/**/*spec.js'
    ],

    module: {
        loaders: [
            { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
            { test: /\.css$/, loader: 'raw-loader' },
            { test: /\.scss$/, loaders: ['raw-loader', 'sass-loader'] },
            { test: /\.json$/, loader: 'json-loader' },
            { test: /\.html$/, loader: 'raw-loader' },
            { test: /karma-require/, loader: 'null-loader' }
        ]
    },
    plugins: [
        new DefinePlugin({
          'ENV': JSON.stringify(ENV),
          'HMR': false,
          'VERSION': 'wallaby101'
        })
    ]
});

module.exports = function () {

    return {
        files: [
            { pattern: 'config/spec-bundle.js', load: false },
            { pattern: 'config/karma-require.js', load: false },
            { pattern: 'src/**/*.ts', load: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.scss', load: false },
            { pattern: 'src/**/*.html', load: false },
            { pattern: 'src/**/*.json', load: false },
            { pattern: 'src/**/*spec.ts', ignore: true },
            { pattern: 'src/**/*.d.ts', ignore: true },
            { pattern: 'src/**/*.e2e.ts', ignore: true }
        ],

        tests: [
            { pattern: 'src/**/*spec.ts', load: false },
            { pattern: 'test/**/*spec.ts', load: false }
        ],

        testFramework: 'jasmine',

        postprocessor: webpackPostprocessor,

        setup: function () {
            window.__moduleBundler.loadTests();
        },

        debug: true
    };
};

```
### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
> but after recent update of wallaby it stopped reporting result

Was it wallaby core update or the extension update? Either way, I don't think we added/changed anything recently that could possibly break this kind of setup, but just in case.

To find out if it's the project/environment specific issue or not, could you please clone these 2 projects and run wallaby to see if it's working for you:
- https://github.com/wallabyjs/calculator-sample
- https://github.com/wallabyjs/ngCliWebpackSample/

**Comment by glendaviesnz** [comment]
ok - one of those annoying ones - worked fine in the two sample repos, and then magically worked again in my project when I switch back to it - despite no end of restarts changing it earlier - go figure :-)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
