### ISSUE TITLE
Get the uninstrumented code?

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#971]
Hello,

Background info: I want to pass my code to the browser through WebdriverIOs [`execute` method](http://webdriver.io/api/protocol/execute.html). 

The problem is, that if I trigger this from my Mocha `before` hook, the code is already instrumented and passed as `function addnumbers(a, b) { $_$wf(1); return $_$w(1, 0), a + b; }`

(_Sidenote:_ The code I want to send is the same that I want to test with Wallaby. In fact, I might not even want to unit test this code... These are React components and I want to run assertions on how they're rendered in the browser but not exactly the output of the functions. 
So the ideal workflow would look like this: 

Edit my component → new code sent to the browser → run assertions with webdriverIO. 

Ideally, I would like that this happens as a type, so it's Wallaby who's dispatching the update events. _sidenote end_)
 
I almost got it working ([wallaby.js file](https://github.com/bfulop/interactive_frontend_dev/blob/6e2a77e15fd70a3934fbce022a552e9a0c8b8f36/wallaby.js) and [test file](https://github.com/bfulop/interactive_frontend_dev/blob/6e2a77e15fd70a3934fbce022a552e9a0c8b8f36/test/webdriverioSimple.js)), but I can only pass strings, the functions are instrumented.

Perhaps I can remove the instrumentation in the wallaby.js file (where I'm passing the data to the browser)?

**Comment by ArtemGovorov** [comment]
You may try removing the instrumentation by setting the [`instrument: false` flag](https://wallabyjs.com/docs/config/files.html#file-object):

```javascript
 {pattern: 'src/webdriverComponent.js', load: true, instrument: false}
```

Alternatively, if you can execute some in the browser before running tests, you may just provide stubs for the instrumentation instructions, so they do nothing. There are just few of them, this should suffice:
```javascript
window.$_$wp = function() {};
window.$_$wpe = function() {};
window.$_$w = function() {};
window.$_$wf = function() {};
window.$_$wv = function(v) { return v; };
window.$_$tracer = {};
```

**Comment by bfulop** [comment]
Thanks, they both sound like great solutions, especially for my use case. 

It should be possible to add the instrumentation functions to target page that I'm using to test my components. 

I love how you can configure _everything_ in Wallaby!

**Comment by bfulop** [comment]
Yes! I can confirm it works (`instrument: false` method, haven't tried to other, but don't need to for now)

[wallaby.js](https://github.com/bfulop/interactive_frontend_dev/blob/b55e7db06cd64296e8aa4b5c7ea58f5fad6fc5ae/wallaby.js)

[test definition file](https://github.com/bfulop/interactive_frontend_dev/blob/b55e7db06cd64296e8aa4b5c7ea58f5fad6fc5ae/test/webdriverioSimple.js)

[file under test](https://github.com/bfulop/interactive_frontend_dev/blob/b55e7db06cd64296e8aa4b5c7ea58f5fad6fc5ae/src/webdriverComponent.js)

The code I want to test passes through the browser and I can immediately see the result with Wallaby. Updates as I type, even though the code is executed in a browser that Wallaby doesn't even know it's running!
In fact the browser could even be a **mobile device** or an **old version of IE** running in a cloud service (Browserstack, SauceLabs, Testingbot, etc).

Won't have more time today to test React component rendering but it should work. It already did, [running from wallaby.js](https://github.com/bfulop/interactive_frontend_dev/blob/6e2a77e15fd70a3934fbce022a552e9a0c8b8f36/wallaby.js#L47)
