### ISSUE TITLE
Show skipped tests in the Wallaby App

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#972]
I'd like to suggest an enhancement to the WallabyJS app. We've got some tests that we're essentially skipping using `xit`. I'm skipping them because they fail, and they're supposed to fail, and at this point in time we don't want to invest time into fixing them. However we do at some point later on.

Unfortunately due to our publishing processes, we ensure that all our tests must pass before being able to push changes up to NPM etc. Hence the needing to `xit` the tests. The problem here is that while the IDE tends to put little orange markers beside these tests, the WallabyJS app completely hides the skipped tests, meaning we have 0 visibility on them.

I've had to rename the highest describe in the file, putting on a prefix to flag that there are some hidden tests that don't pass, but if wallaby were able to include these as skipped tests that'd be really helpful, a bit like Jasmine does. Then I wouldn't have to take out useful tests for the future from our TDD approach.

**Comment by dotnetprofessional** [comment]
I'd like to add a +1 for this too. However, my scenario is around the BDD style of writing tests in that you'd right all the tests first (well at least the describe and it definitions) so you know what the spec is for the code. Then start to fill in the tests as you write the code. I find this is valuable for tracking progress as well as knowing when you're done. However as mentioned this isn't possible in Wallaby currently as ignored tests are well ignored :) I have to run the test runner from the command line to get visibility into these tests.

**Comment by NikGovorov** [comment]
Hi All,

The feature was implemented and released in the latest version of the editor extensions, core and wallaby app.

![vsc_jb_app_skipped_todo](https://user-images.githubusercontent.com/129254/83220295-f59bc380-a1b5-11ea-9895-a86545be8d3d.gif)
