### ISSUE TITLE
How can I use WebSocket with Wallaby.js?

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#975]
This is not an issue directly related to _Wallaby.js_, but rather related to how I am supposed
to set up a testing environment which allows me to use HTML5 `WebSocket` inside the node
based test runner.

If my understanding is correct, I cannot use `WebSocket` in the test runner, unless I import `ws` (for instance). However, if I import `ws`, I then cannot produce a working npm package for the browser,
as it has dependencies on `fs`, for instance.

Can I somehow _emulate_ `WebSocket` in my testing environment, by injecting it in the global
environment? I am currently using this _test helper_ (injected in mocha through `--require ./test/test-helper.js`) in order to provide an environment which looks like a browser:

```js
'use strict';

// Provide document and window as globals, so that React can be
// tested outside of a browser environment.

import jsdom from 'jsdom';

const doc = jsdom.jsdom ('<!doctype html><html><body><div id="root"/></body></html>');
const win = doc.defaultView;

// const MSIE11 = 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko';
const Chrome49 =
  'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)' +
  ' Chrome/49.0.2454.85 Safari/537.36';

/* global global */
global.document  = doc;
global.window    = win;
global.navigator = {userAgent: Chrome49};

if (console.debug === undefined) {
  // Setting the userAgent to Chrome triggers a warning in React, which we
  // suppress in our custom implementation of console.debug() as it only adds
  // noise and is not pertinent in a testing environment.
  console.debug = function (...args) {
    if (args[0].includes ('https://fb.me/react-devtools')) {
      return;
    }
    console.log (...args);
  };
}

Object.keys (win).forEach (key => {
  if (!(key in global)) {
    global[key] = win[key];
  }
});
```

**Comment by epsitec** [comment]
By the way, my test helper is injected into Wallaby.js through the `wallaby.conf.js` file:

```js
bootstrap: function (wallaby) {
  ...
  require ('./test/test-helper');
}
```

**Comment by ArtemGovorov** [comment]
From what I could quickly find, [`jsdom` doesn't implement WebSocket](https://github.com/tmpvar/jsdom/issues/1195), though they could have. 

I suppose your best choice is to just import `ws` in your test helper, create `global.WebSocket` object and [implement the API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) by wrapping the `ws`. You don't have to expose/implement everything immediately, just those things that you're using/testing. As an alternative to wrapping `ws`, you may leave empty stubs, or spies to verify the WebSocket API calls, as you probably don't need to actually establish the actual WebSocket connections.

**Comment by epsitec** [comment]
I'll go ahead and do that, simply adding `global.WebSocket` as being a synonym of `WebSocket` from the `ws` module, which provides out of the box an API which seems compatible enough with the HTML5 spec for my use case.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by epsitec** [comment]
This works for me:

```js
'use strict';

// Provide document and window as globals, so that React can be
// tested outside of a browser environment.

import jsdom from 'jsdom';
import WebSocket from 'ws';

const doc = jsdom.jsdom ('<!doctype html><html><body><div id="root"/></body></html>');
const win = doc.defaultView;

// const MSIE11 = 'Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko';
const Chrome49 =
  'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)' +
  ' Chrome/49.0.2454.85 Safari/537.36';

/* global global */
global.document  = doc;
global.window    = win;
global.navigator = {userAgent: Chrome49};
global.WebSocket = WebSocket;

if (console.debug === undefined) {
  // Setting the userAgent to Chrome triggers a warning in React, which we
  // suppress in our custom implementation of console.debug() as it only adds
  // noise and is not pertinent in a testing environment.
  console.debug = function (...args) {
    if (args[0].includes ('https://fb.me/react-devtools')) {
      return;
    }
    console.log (...args);
  };
}

Object.keys (win).forEach (key => {
  if (!(key in global)) {
    global[key] = win[key];
  }
});
```
