### ISSUE TITLE
Configuration for create-react-app-typescript

### ISSUE THREAD

**Issue by pauleveritt** [wallabyjs/public#980]
### Issue description or question

*Note: I realize I am starting to abuse the support that comes with the purchase. I'm up for doing bounties, AirPair, or simply buying another license. You should get paid for your time.*

I'm going to make one more attempt at keeping TypeScript in my toolchain. There's [a fork of create-react-app](https://github.com/wmonk/create-react-app-typescript) which generates TypeScript-centric React starters. Here's [a generated app where I attempt](https://github.com/pauleveritt/my-app) to get Wallaby working.

`npm run test` works ok, but running Wallaby gives:

```
TypeError: Cannot read property 'cache' of undefined
    at Object.<anonymous> (./src/App.test.js.wbp.js:1:112)
    at Runtime._execModule (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/jest-runtime/build/index.js:441:13)
    at Runtime.requireModule (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/jest-runtime/build/index.js:297:14)
    at jasmine2 (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/jest-jasmine2/build/index.js:95:11)
    at runTest (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/jest/node_modules/jest-cli/build/runTest.js:50:10)
    at promise.then (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/jest/node_modules/jest-cli/build/TestRunner.js:304:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Also, `moduleNameMapper` doesn't seem to work on handling `.css` etc.

```
Module not found: Error: Cannot resolve 'file' or 'directory' ./App.css in ./srcModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' ./App.css in /Users/pauleveritt/Library/Caches/WebStorm2017.1/wallaby/projects/4dec90c41644528d/instrumented/src
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/lib/Compilation.js:229:38
  at onDoneResolving (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/lib/NormalModuleFactory.js:85:20
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:726:13
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:52:16
  at done (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:241:17)
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:44:16
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:723:17
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/async/lib/async.js:167:37
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
  at onResolved (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:127:10
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:191:15
  at applyPluginsParallelBailResult.createInnerCallback.log (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
  at loggingCallbackWrapper (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
  at /Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/tapable/lib/Tapable.js:134:6
  at Tapable.<anonymous> (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryDescriptionFilePlugin.js:24:12)
  at Storage.finished (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
  at ReadFileContext.callback (/Users/pauleveritt/projects/scratchpad/my-app/node_modules/graceful-fs/graceful-fs.js:78:16)
  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require('wallaby-webpack');
const webpackPostprocessor = wallabyWebpack({});
const path = require('path');

module.exports = function (wallaby) {
    process.env.NODE_PATH +=
        path.delimiter +
        path.join(__dirname, 'node_modules') +
        path.delimiter +
        path.join(__dirname, 'node_modules/react-scripts-ts/node_modules');
    require('module').Module._initPaths();

    // Babel needs this
    // create-react-app-typescript does not use this
    // process.env.NODE_ENV = 'development';

    return {
        files: [
            'src/**/*.ts*',
            '!src/**/*.test.ts*'
        ],

        tests: ['src/**/*.test.ts*'],

        env: {
            type: 'node',
            runner: 'node'
        },

        postprocessor: webpackPostprocessor,

        setup: (wallaby) => {
            wallaby.testFramework.configure({
                moduleNameMapper: {
                    '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve('react-scripts-ts/config/jest/fileTransform.js'),
                    '^.+\\.css$': require.resolve('react-scripts-ts/config/jest/cssTransform.js')
                }
            });
        },

        testFramework: 'jest'
    };
};
```

### Code editor or IDE name and version

WebStorm 2017.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Hi Paul,

> Note: I realize I am starting to abuse the support that comes with the purchase. I'm up for doing bounties, AirPair, or simply buying another license. You should get paid for your time.

I appreciate your willingness to help, but please don't bother with buying another license. When the questions are answered here, the answers are helpful to other users as well. If you feel like helping the project to grow and get better, please keep asking good questions, submit bugs, share your feedback with us, help us spreading the word about the tool.

`jest` runs in node, so no webpack is required to make the tests work Moreover, wallaby doesn't support webpack for node environment (that is totally capable of doing CommonJs without the module bundler).

I have sent you [the PR to make the config work](https://github.com/pauleveritt/my-app/pull/1).

**Comment by pauleveritt** [comment]
That PR did the trick perfectly. I had a feeling webpack wasn’t needed. The .css and .svg imports are taken out by the wallaby moduleNameMapper.

One last question…setting testFramework to ‘jest’ does that mean Jest’s use of jsdom is retained, or do you switch back to Wallaby’s use of phantomJS?

I have to say, when I did the pull and got Wallaby back, it was a surprising feeling of joy. There’s something hard to describe about sitting in front of Wallaby. And I still have a lot to learn about its feature set.

—Paul

**Comment by ArtemGovorov** [comment]
> setting testFramework to ‘jest’ does that mean Jest’s use of jsdom is retained, or do you switch back to Wallaby’s use of phantomJS?

[Setting the `env`](https://wallabyjs.com/docs/config/runner.html) (that can be used to switch between PhantomJs, V8/Chrome via Electron and node.js), makes wallaby to run tests in node. Setting `testFramework` to `jest` is required because wallaby.js supports [other testing frameworks that run in node.js environment](https://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). Some of the frameworks, like jasmine and mocha, can run both in browser/PhantomJs and in node.js, while Jest only runs in node.js environment.
