### ISSUE TITLE
wallaby-babel-es7 issue

### ISSUE THREAD

**Issue by ochemerys** [wallabyjs/public#982]
### Issue description
I just started REST API application build on Koa2. I run tests in Mocha. I want Wallaby for my unit tests. When I started with Wallaby, I encountered interesting issue.

When I just run Wallaby, tests are passing and I'm in green 
![image](https://cloud.githubusercontent.com/assets/20651535/22406986/e0217aea-e61a-11e6-86ad-86eef6a591f0.png)

If I modify code file or test file I have a strange message  "OverwriteModelError: Cannot overwrite `Action` model once compiled." and all my tests fail.
![image](https://cloud.githubusercontent.com/assets/20651535/22407002/4f40d178-e61b-11e6-89f8-1e995c2556d3.png)

I borrowed wallaby config settings from https://github.com/wallabyjs/wallaby-babel-es7-sample

Am I missing something?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},

            {pattern: 'node_modules/chai/chai.js', instrument: false},
            {pattern: 'node_modules/sinon/lib/sinon.js', instrument: false},

            {pattern: 'node_modules/koa/lib/application.js', instrument: false},
            {pattern: 'node_modules/koa-router/lib/router.js', instrument: false},
            {pattern: 'node_modules/koa-bodyparser/index.js', instrument: false},
            {pattern: 'node_modules/koa-logger/index.js', instrument: false},

            {pattern: 'node_modules/mongoose/index.js', instrument: false},

            'src/**/*.js',
            '!src/**/*.spec.js'
        ],

        tests: [
            'src/**/*.spec.js'
        ],

        testFramework: 'mocha',

        compilers: {
            'src/**/*.js': wallaby.compilers.babel()
        },

        env: {
            type: 'node'
        }

    };
};
```
### Code runner version
Node v6.9.2

### package.json file
```javascript
"devDependencies": {
    "babel-cli": "^6.22.2",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-latest": "^6.22.0",
    "babel-register": "^6.22.0",
    "chai": "^3.5.0",
    "mocha": "^3.2.0",
    "sinon": "^1.17.7",
    "supertest": "^2.0.1"
  },
  "dependencies": {
    "babel-polyfill": "^6.22.0",
    "koa": "^2.0.0",
    "koa-bodyparser": "^3.2.0",
    "koa-logger": "^1.3.1",
    "koa-router": "^7.1.0",
    "mongoose": "^4.7.7"
  }
```
### Code editor or IDE name and version
WebStorm 2016.3.2

### OS name and version
Windows 7

Thank you.

**Comment by ArtemGovorov** [comment]
It's a known issue with mongoose caching its models (it also has issues with parallelisation AFAIK). Wallaby, unlike mocha, tries to reuse node processes, and because some modules, like mongoose cache things per process, it sometimes may cause the issues like the one you're observing. 

Try the suggested settings from:
https://github.com/wallabyjs/public/issues/239
https://github.com/wallabyjs/public/issues/323

Ultimately, this should work:
```javascript
module.exports = function () {
   return {
     files: [
       ...
     ],

     tests: [
       ...
     ],

     workers: {
       recycle: true,
       initial: 1,
       regular: 1
     }
   };
 };
```
but you may also try without setting the initial/regular count. You may also try avoiding setting `recycle: true` [by clearing the `mongoose` module state, as described in the docs](https://wallabyjs.com/docs/integration/node.html#node-process-reuse):

```javascript
module.exports = wallaby => {
  return {
    ...
    setup: function (w) {
      delete require.cache[require.resolve('mongoose')];
    }
  };
};
```
