### ISSUE TITLE
Typescript + Babel issue when Typescript targets ESNext

### ISSUE THREAD

**Issue by narthollis** [wallabyjs/public#984]
### Issue description or question

When Typescript is targeting ESNext, it may emit code that the causes a syntax error to be thrown before the file is handled by the preprocessor. The case I have run into is using Object Spread `{ ...foo }`.

A minimal reproduction can be found at: https://github.com/narthollis/minimal_typescript_esnext_babel

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test';

const fs = require('fs');
const babelrc = JSON.parse(fs.readFileSync('./.babelrc', "utf8"));

// eslint-disable-next-line func-names
module.exports = function (wallaby) {

    return {
        files: [
            'src/**/*.ts*',
            '!src/**/*.test.ts*',
        ],

        tests: [
            'src/**/*.test.ts*',
        ],

        preprocessors: {
            'src/**/*.js*': file => require('babel-core').transform(
                    file.content,
                    { sourceMap: true, presets: babelrc.env.test.presets }
                )
        },

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony',
            },
        },

        testFramework: 'jest',

        setup: (w) => {
            w.testFramework.configure({
                moduleFileExtensions: ['js', 'json', 'jsx', 'node', 'ts', 'tsx'],
            });
        },

    };
};
```

### Code editor or IDE name and version

WebStorm 2017.1 EAP

### OS name and version

Windows 7

**Comment by ArtemGovorov** [comment]
Thanks for the repo. 
We have added Object Rest/Spread Properties support in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

> When Typescript is targeting ESNext

Juts so we better understand your scenario, what's the reason for not targeting `ES5` in the `tsconfig.json` and avoiding the babel compilation step altogether?

**Comment by narthollis** [comment]
Our build process currently outputs typescript + Babel and I would like to
have my test processed the same way.

The main reason for this is we have recently moved to typescript and have
more experience with Babel.

I currently have my Wallaby setup to instruct typescript to output es2015
and I will be manually invoking jest on commit to ensure that there were no
bugs introduced by the Babel transform.

**Comment by ArtemGovorov** [comment]
Fair enough, thanks for sharing your scenario details.
