### ISSUE TITLE
Not recognizing "modulePaths" in package.json jestconfig

### ISSUE THREAD

**Issue by epitaphmike** [wallabyjs/public#986]
I am running into multiple issues with the wallaby config working with Jest.

1. When I require('./package.json').jest in the wallaby.testFramework.configure it doesn't seem that wallaby is honoring the variables inside the jestsetup.js in jest: { setupFiles: [ jestsetup.js ] } that are used for enzyme.

```
ReferenceError: shallow is not defined
```

2. It seems like wallaby is not reading the jest config's modulePaths. Leaving me with errors like

```
Error: Cannot find module 'moment' from 'formatter.test.js'
``` 

In this case "moment" lives in the node_modules under "../../../../site-ui", not the "base-ui" where the wallaby-config.js lives.

All these test run and code coverage is complete when ran in node. 

wallaby-config.js
---
```javascript
module.exports = function (wallaby) {
    var jestconfig = require('./package.json').jest;

    return {
        files: [...],
        tests: [... ],
        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js*': wallaby.compilers.babel()
        },
        setup: function (wallaby) {
            wallaby.testFramework.configure(this.jestconfig);
        }
    }
};
``` 

jestsetup.js
---
```javascript
// Make Enzyme functions available in all test files without importing
import { shallow, render, mount } from 'enzyme';

global.shallow = shallow;
global.render = render;
global.mount = mount;

// Skip createElement warnings but fail tests on any other warning
console.error = message => {
    if (!/(React.createElement: type should not be null)/.test(message)) {
        throw new Error(message);
    }
};
```
```
ReferenceError: shallow is not defined
```
If I copy the jest: {...} out of the package.json into the wallaby.testFramework.configure({...}) it works. I'd prefer not to duplicate the config and have it live in one location, the package.json

wallaby-config.js
---
```javascript
module.exports = function (wallaby) {
    var jestconfig = require('./package.json').jest;

    return {
        ...
        setup: function (wallaby) {
            wallaby.testFramework.configure({
                "collectCoverage": true,
                "collectCoverageFrom": [...],
                "coveragePathIgnorePatterns": [
                    "/node_modules/",
                    "/node/"
                ],
                "coverageReporters": [
                    "json",
                    "text"
                ],
                "coverageDirectory": "<rootDir>/tests/coverage",
                //
                // Not reading node_modules from these directories
                //
                "modulePaths": [
                    "../../../../site-ui/src/main/client/node_modules",
                    "../../../../account-ui/src/main/client/node_modules"
                ],
                "moduleNameMapper": {
                    "^SiteUI(.*)$": "../../../../site-ui/src/main/client$1",
                    "^AccountUI(.*)$": "../../../../account-ui/src/main/client$1",
                    "^Common(.*)$": "<rootDir>/$1"
                },
                "notify": true,
                "setupFiles": [
                    "<rootDir>/jestsetup.js"
                ],
                "snapshotSerializers": [
                    "<rootDir>/node_modules/enzyme-to-json/serializer"
                ],
                "testPathDirs": [
                    "<rootDir>",
                    "../../../../site-ui/src/main/client",
                    "../../../../account-ui/src/main/client"
                ],
                "verbose": true
            });
        }
    }
};
``` 

### Code editor or IDE name and version

IntelliJ IDEA 2016.3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The [`setup` function is executed in the context of the test runner](https://wallabyjs.com/docs/config/bootstrap.html), not in the context of the configuration file.

It means that you cannot use objects/variables defined within the configuration file code:

```javascript
module.exports = function (wallaby) {
    var jestconfig = require('./package.json').jest;

    return {
        files: [...],
        tests: [... ],
        ...
        setup: function (wallaby) {
            wallaby.testFramework.configure(this.jestconfig); // <-- there's no jestconfig, it's undefined
        }
    }
};
```

You need to `require` the package.json right in the setup function, as [described in the docs](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) (don't forget to add the `package.json` file to the `files` list as you'll be accessing it from the test worker):
```javascript
module.exports = function (wallaby) {

    return {
        files: [
          ...,
          'package.json'
        ],
        tests: [... ],
        ...
        setup: function (wallaby) {
            var jestconfig = require('./package.json').jest;
            wallaby.testFramework.configure(jestconfig);
        }
    }
};
```

Let me know if it works for you.

**Comment by epitaphmike** [comment]
So it seem I have ran into a different issue.

My directory structure is as follows

```
/client
    /node_modules
    /components
    /more directories
    .babelrc
    jestsetup.js
    package.json
    wallaby-config.js
```

wallaby-config.js
---
```javascript
module.exports = function (wallaby) {

    return {
        files: [
            'client/**/*.js*',
            '!node/',
            '!node_modules/',
            'package.json'
        ],

        tests: [
            'tests/**/*test.js'
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest',

        compilers: {
            '**/*.js*': wallaby.compilers.babel()
        },

        setup: function (wallaby) {
            wallaby.testFramework.configure(require('./package.json').jest);
        },

        debug: true
    }
};
```
With the compilers setup like

```javascript
compilers: {
    '**/*.js*': wallaby.compilers.babel()
}
```
I get an output of a failure to run the compilers

```
Failed to run compilers on package.json ...
```

With the compilers setup with the client dir before the **

```javascript
compilers: {
    'client/**/*.js*': wallaby.compilers.babel()
}
```
I get an output with an ES6 issue.
```
import moment from 'moment';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by ArtemGovorov** [comment]
The [file/test paths in the wallaby config](https://wallabyjs.com/docs/config/files.html) has to be relative to the config file. The compiler pattern is applied to whatever is whitelisted in the `files`/`tests`, so `**/*.js*` is ok to have for the compiler pattern. But, because your `package.json` is in the files list, the compiler is trying to compile it as well (`*.json` is satisfied by `**/*.js*`). You may either provide a better pattern (like `**/*.js?(x)`), or set [the `instrument: false` flag](https://wallabyjs.com/docs/config/files.html#file-object) for the `package.json`.

```javascript
module.exports = function (wallaby) {

    return {
        ...
        compilers: {
            '**/*.js?(x)': wallaby.compilers.babel()
        }
       ...
    }
};
```

**Comment by epitaphmike** [comment]
Is there a way to get wallaby to recognize the **modulePaths** directories in the package.json jest config?

All my testing is done in a base-ui, it has sibling directories at the same level called site-ui and account-ui. Both these directories have their own node_modules. The base-ui houses common components that are used in both site-ui and account-ui.

Jest's **modulePaths** allows me to add paths to the respective node_modules directories under each module, site-ui and account-ui. This way I can do things like `import moment from 'moment'` and it resolves properly. 

Right now wallaby throws errors like `Error: Cannot find module 'moment' from 'formatter.test.js'`

What would be the best approach to include these dependencies?

package.json
---
```javascript
"jest": {
    "collectCoverage": true,
    "collectCoverageFrom": [
      "**/*.{js,jsx}",
      "../../../../site-ui/src/main/client/**/*.{js,jsx}",
      "../../../../account-ui/src/main/client/**/*.{js,jsx}",
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/node/"
    ],
    "coverageReporters": [
      "json",
      "text"
    ],
    "coverageDirectory": "<rootDir>/tests/coverage",
    "modulePaths": [
      "../../../../site-ui/src/main/client/node_modules",
      "../../../../account-ui/src/main/client/node_modules"
    ],
    "moduleNameMapper": {
      "^SiteUI(.*)$": "../../../../site-ui/src/main/client$1",
      "^AccountUI(.*)$": "../../../../account-ui/src/main/client$1",
      "^Common(.*)$": "<rootDir>/$1"
    },
    "notify": true,
    "setupFiles": [
      "<rootDir>/jestsetup.js"
    ],
    "snapshotSerializers": [
      "<rootDir>/node_modules/enzyme-to-json/serializer"
    ],
    "testPathDirs": [
      "<rootDir>",
      "../../../../site-ui/src/main/client",
      "../../../../account-ui/src/main/client"
    ],
    "verbose": true
  }
```

```
/base-ui/src/main/client
    /node_modules
    /components
    /more directories
    .babelrc
    jestsetup.js
    package.json
    wallaby-config.js

/site-ui/src/main/client
    /node_modules
    /components
    .babelrc
    package.json

/account-ui/src/main/client
    /node_modules
    /components
    .babelrc
    package.json
```

**Comment by ArtemGovorov** [comment]
> Is there a way to get wallaby to recognize the modulePaths directories in the package.json jest config

Wallaby.js is using its own file cache to run the tests from, so any relative path in your jest config is resolved against wallaby cache folder. You are using the `<rootDir>` is some places, but not everywhere, if you just do:
```
"modulePaths": [
      "<rootDir>/../../../../site-ui/src/main/client/node_modules",
      "<rootDir>/../../../../account-ui/src/main/client/node_modules"
    ],
```
then it should work for you.

**Comment by ArtemGovorov** [comment]
One more thing, for the same reason as described above, you may [need to adjust the `moduleMapper` setting](https://github.com/wallabyjs/public/issues/936#issuecomment-271146762):

```javascript
    setup: function (wallaby) {
      const config = require('./package.json').jest
      const pattern = '^Common(.*)$'
      conf.moduleNameMapper[pattern] = config.moduleNameMapper[pattern].replace('<rootDir>', wallaby.projectCacheDir)
      wallaby.testFramework.configure(config)
    }
```

You'll only need to do it if you'd like to see the code coverage in the `^Common(.*)$` modules.

**Comment by epitaphmike** [comment]
That worked. Thank you. The one this I am still struggling with the having the wallaby.config.js in my base-ui and I cannot test outside of the base-ui directory into sibling directories. It seems to be an issue with wallaby if I am not mistaken. https://github.com/wallabyjs/public/issues/68

One thing I tried to do was create a wallaby.config.js in the site-ui directory and point to the package.json  in the base-ui directory for the jest.config. That also did not work.

Thank you.

**Comment by ArtemGovorov** [comment]
> The one this I am still struggling with the having the wallaby.config.js in my base-ui and I cannot test outside of the base-ui directory into sibling directories. It seems to be an issue with wallaby if I am not mistaken. #68

Correct, wallaby currently can not run tests outside of the folder where it's located. It is the right issue you've referenced https://github.com/wallabyjs/public/issues/68
