### ISSUE TITLE
How to load jasmine-ajax for tests with wallaby-webpack

### ISSUE THREAD

**Issue by janneh** [wallabyjs/public#987]
### Issue description or question

I'm running my tests with karma using jasmine and would like to use wallaby. I'm bundling with webpack and using `wallaby-webpack`. Been looking at https://github.com/fvanwijk/testRunnerConfig and I've set it up and all tests are running but a bunch that rely on `jasmine-ajax` fail. 

I have this in my karma.conf.js file:

```javascript
...
    frameworks: [
      "jasmine",
      "jasmine-ajax",
      "jasmine-expect-jsx"
    ],
...
```

What would that translate to in the wallaby config?

This is browser env so I can't `require("jasmine-ajax")` in `setup/bootstrap` as suggested in some other issue.

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by janneh** [comment]
ok, got it...
fyi for anyone else looking for this, include:

```js
module.exports = function (wallaby) {

  return {
    files: [
      { pattern: "node_modules/jasmine-ajax/lib/mock-ajax.js", instrument: false }
    ]
  }

}
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
