### ISSUE TITLE
angular2 quickstart with wallaby

### ISSUE THREAD

**Issue by lelehehe** [wallabyjs/public#988]
### Issue description or question
How to setup wallabyjs file for the latest angular 2 quickstart project?
### Wallaby.js configuration file
https://github.com/lelehehe/quickstart.git
This is a forked repository for the angular team quickstart repository

I have a wallaby js file setup, but it doesn't work. 

### Code editor or IDE name and version

Visual Studio Code v1.9

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I have sent you the [pull request with the working config](https://github.com/lelehehe/quickstart/pull/1). The difference is mostly 
- updating obsolete Angular 2 APIs used in your existing config, 
- using `tsconfig.json` from the nested folder, 
- and [configuring system.js similar to karma](https://github.com/lelehehe/quickstart/blob/master/karma-test-shim.js#L44).

**Comment by lelehehe** [comment]
Artem,

Thanks a lot for your help. I will do a demo to our team about this tool.

Mike

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
