### ISSUE TITLE
Support google chrome extension development

### ISSUE THREAD

**Issue by Alino** [wallabyjs/public#989]
### Issue description or question
ReferenceError: chrome is not defined
![image](https://cloud.githubusercontent.com/assets/763194/22598150/c5b1885a-ea32-11e6-8431-0c5aa23d17e2.png)

### Wallaby.js configuration file

```javascript
module.exports = function (w) {

  return {
    files: [
      'node_modules/@types/chrome/*.ts',
      'app/src/**/*.ts'
    ],

    tests: [
      'app/specs/**/*.spec.ts'
    ],

    compilers: {
      '**/*.ts': w.compilers.typeScript({ module: 'commonjs' })
    },

    testFramework: "jasmine",

    env: {
      type: 'node'
    }
  };
};
```

### tsconfig.ts
```javascript
{
  "compilerOptions": {
    "removeComments": false,
    "sourceMap": false,
    "noImplicitAny": false,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "lib": ["dom", "es6"],
    "declaration": false,
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "types": [
      "jasmine",
      "underscore",
      "chrome"
    ]
  },
  "include": [
    "src/**/*",
    "specs/**/*"
  ],
  "exclude": [
    "dev/**/*",
    "dist/**/*"
  ]
}
```

### Code editor or IDE name and version
Visual Studio Code v1.9.0

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Unfortunately wallaby.js doesn't support google chrome extension development. You're running your tests in node environment:
```
    env: {
      type: 'node'
    }
```
and as expected it has no idea about `chrome` global object.
At the moment, wallaby only supports node.js, PhantomJs and Chrome/V8 via Electron (but as a browser, not as extension dev environment).

To support the feature of chrome extension development, we'll need to create a new environment/test runner type.

**Comment by Alino** [comment]
I hoped that if I give it the typescript types for chrome, it will know the chrome variable :(

would it be difficult to create new test runner type for this? Are there any plans to do so? Could I do it myself and could you give me a hint please?

This is the second time I am trying to use wallaby, first time with webstorm + meteor and it didn't work and there was no support for it.
Now after half a year I switched to visual code + chrome development and so I upgraded my wallaby license to freedom, and I hope that we can solve this somehow this time.

**Comment by ArtemGovorov** [comment]
> typescript types for chrome

TypeScript types are not adding the values in runtime, if the there's no `chrome` global object in the environment, importing its types will not help.

> would it be difficult to create new test runner type for this? Are there any plans to do so? Could I do it myself and could you give me a hint please?

Yes, it is a difficult task and while you could theoretically do it yourself, it may take you a while.

> so I upgraded my wallaby license to freedom, and I hope that we can solve this somehow this time.

Unfortunately chrome extensions dev environment is not something that wallaby ever supported or advertised as supported. And as I said it's not a trivial task to add the new runner, so I can't provide you any ETA/promises on the feature implementation. Having said that, I totally understand your frustration, and if you've upgraded your license just to use wallaby in the chrome extensions dev environment, please send us an email to hello@wallabyjs.com, and we'll do a refund for you.

**Comment by smcenlly** [comment]
To test chrome extensions with Wallaby, we recommend creating a mock for the chrome runtime objects. Something like [jest-chrome](https://github.com/extend-chrome/jest-chrome), which you may use with Wallaby + Jest.
