### ISSUE TITLE
Wallaby can't find my spec files

### ISSUE THREAD

**Issue by nibblesnbits** [wallabyjs/public#990]
### Issue description or question

I'm trying to set up Wallaby against a (somewhat) simple React/Webpack project, but it seems wallaby is having a hard time finding my files.

(see error in [README](https://github.com/nibblesnbits/webpack-wallaby))

### Wallaby.js configuration file

(see [here](https://github.com/nibblesnbits/webpack-wallaby/blob/master/wallaby.js))

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Have sent you [the pull request](https://github.com/nibblesnbits/webpack-wallaby/pull/1). Webpack 1.x requires the empty extension to be specified, just like it's done in [your webpack configs](https://github.com/nibblesnbits/webpack-wallaby/blob/master/webpack.config.dev.js#L8).
