### ISSUE TITLE
wallaby + angular 2 quickstart demo: moduleId: module.id issue

### ISSUE THREAD

**Issue by lelehehe** [wallabyjs/public#991]
### Issue description or question
Artem, 
how to setup a Wallaby config file to handle angular "moduleId: module.id"? 
Right now in wallaby, we have 
`compilerOptions.module = 'system';`
but module in "moduleId: module.id" is defined in commonjs instead of system. 
Here is the error in wallaby console: 
`​​[Error] Runtime error: Error: (SystemJS) Can't find variable: module​​`

One possible fix is to setup a variable in wallaby.js file: 
`var module = { id: 'foo' };  `
But I am not sure how to make that work. 

### Wallaby.js configuration file
https://github.com/lelehehe/quickstart.git

### Code editor or IDE name and version

Visual Studio Code v1.x

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Did you try:

```javascript
...
setup: function (wallaby) {
      window.module = { id: 'foo' };
      ...
}
```
?

**Comment by ArtemGovorov** [comment]
If the above doesn't help, you may remove 
```javascript
compilerOptions.module = 'system';
```
and remove `format: 'register'`:
```javascript
        meta: {
          'src/app/*': {
            scriptLoad: true,
            // format: 'register' <--
          }
        },
```
and try it this way.

**Comment by lelehehe** [comment]
the first way: 
```
setup: function (wallaby) {
      window.module = { id: 'foo' };
      ...
}
```
works great. The last one doesn't work. 
I will stay with the first approach for now. 
Thanks again for your quick response.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
