### ISSUE TITLE
​​ReferenceError: Can't find variable: Map​​

### ISSUE THREAD

**Issue by daBishMan** [wallabyjs/public#992]
### Issue description or question
Getting an error when running Wallaby.  

> ​​​​​0 failing tests, 0 passing​​​​​
​​​​​​​​​​
​​ReferenceError: Can't find variable: Map​​
​​ReferenceError: Can't find variable: Map​​
​​at http://localhost:54239/__modules/25.js?1486327666297:81​​

New Project using @angular/cli beta 30

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      { test: /\.css$/, loader: 'raw-loader' },
      { test: /\.html$/, loader: 'raw-loader' },
      { test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/ },
      { test: /\.json$/, loader: 'json-loader' },
      { test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader'] },
      { test: /\.less$/, loaders: ['raw-loader', 'less-loader'] },
      { test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader'] },
      { test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000' }
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.d.ts', ignore: true },
      { pattern: 'src/**/*.css', load: false },
      { pattern: 'src/**/*.less', load: false },
      { pattern: 'src/**/*.scss', load: false },
      { pattern: 'src/**/*.html', load: false },
      { pattern: 'src/**/*spec.ts', ignore: true }
    ],

    tests: [
      { pattern: 'src/**/*spec.ts', load: false }
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.9

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment]
Looks like [the polyfills file](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/polyfills.ts) wasn't loaded. It means that you probably have [the wallabyTest.ts file](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) missing. 

Please follow the [instructions in the repo readme](https://github.com/wallabyjs/ngCliWebpackSample#wallabyjs) to create the missing file (and install a couple of other required packages). If it still doesn't work after adding the file. please let me know.

**Comment by daBishMan** [comment]
I do have the wallabytests.ts file, in Angular-Cli beta 30 they change the way the polyfills are loaded.

Below are the contents of wallabytests.ts

```
import './polyfills.ts';

import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';


const testing = require('@angular/core/testing');
const testingBrowser = require('@angular/platform-browser-dynamic/testing');

testing.getTestBed().initTestEnvironment(
  testingBrowser.BrowserDynamicTestingModule,
  testingBrowser.platformBrowserDynamicTesting());
```

**Comment by ArtemGovorov** [comment]
> in Angular-Cli beta 30 they change the way the polyfills are loaded

They did, but it shouldn't affect the way wallaby loads them the polyfills from the `src/wallabyTest.ts`. 

Yesterday I have updated the [sample repo](https://github.com/wallabyjs/ngCliWebpackSample) to Angular-Cli beta 30, and it's working for me. Could you please see if the repo is working for you, and we'll take it from there?

**Comment by daBishMan** [comment]
Thank you so much for your help.  On a new CLI 30 project it works great per your updated instruction or even your previous version.  Obviously, this is a problem with my project somehow I need to determine. 

Thanks again, you can close this if you wish.

**Comment by ArtemGovorov** [comment]
@daBishMan Thanks for the update. If you could create/share a repo where I could reproduce it, I'm happy to have a look. 

One other thing I may suggest without being able to reproduce the error, is to switch to [Chrome/V8 via Electron](https://wallabyjs.com/docs/integration/electron.html) in your wallaby config, it should eliminate the need in Map polyfill altogether.

**Comment by ArtemGovorov** [comment]
Regarding determining the issue in your project, try starting wallaby and opening the `src/wallabyTest.ts`file, check if the indicators there are green (if not, the file is not being loaded, then double check its path in the config):

<img width="630" alt="screen shot 2017-02-07 at 1 26 08 pm" src="https://cloud.githubusercontent.com/assets/979966/22676746/04ae0066-ed39-11e6-8227-dc930603c3de.png">

**Comment by daBishMan** [comment]
Thank you so much for your willingness to help.  You can find the repo with the error at https://github.com/daBishMan/ngx-fun the master branch is fine.   thank you so much for your assistance.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. Looks like the `wallbyTest` file name is misspelled (it's missing an `a` letter).

**Comment by daBishMan** [comment]
now I am completely embarrassed.    Too bad there is no delete thread and hide it from the internet forever button on git hub.  

Thanks again.

**Comment by ArtemGovorov** [comment]
@daBishMan No worries, it's not your fault, but our tool's missing feature of warning about cases like this. We do have in our backlog.
