### ISSUE TITLE
In large project running "Run Line Tests" to update snapshots runs really slow! 

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#998]
### Issue description or question

I'm running wallaby on a project with a significantly large Typescript codebase. While tests seem to run fast and efficiently, the moment I decide to run "line Test" to update wallaby snapshot, it takes the same amount of time as running wallaby from start.

### Wallaby.js configuration file

```javascript
const transform = require("jsx-controls-loader");
module.exports = function(wallaby) {
  // var load = require;

  return {
    files: [
      "src/client/**/*.ts*",
      "src/shared/**/*.ts*",
      'src/**/*.snap',
      'package.json',
      "i18n/*.json",
      '!src/tests/*.ts*',
    ],
    tests: [
      'src/tests/*.ts*'
    ],
    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({module: "commonjs", target: "es6", jsx: "react"})
    },
    preprocessors: {
      "**/*.js": file => transform(file.content)
    },
    env: {
      type: "node"
    },
    testFramework: "jest",
    setup: function(wallaby) {
      wallaby.testFramework.configure(require('./package.json').jest);
    },
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.9

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I'll need a reproducible sample to be able to profile it. Any chance you could share the project?

Also could you please 
- add the [`debug: true` setting](https://wallabyjs.com/docs/config/overview.html#debug-setting) to your config,
- start wallaby, wait for the initial run to finish,
- open the Wallaby Console output channel and clear it,
- open a test file, run the `Run line tests` action in some test,
- paste the full output of the Wallaby Console here.

**Comment by tomitrescak** [comment]
@ArtemGovorov unfortunatelly I cannot share the project with you. Yet here is the console info you asked about. Indeed it seems that it is reinitialising the whole project:

https://gist.github.com/tomitrescak/d06d84089ed90fe6cd15fd5e80be7eeb

**Comment by ArtemGovorov** [comment]
@tomitrescak Thanks for the log. It looks like you're running line tests for `src/tests/first.ts`, but there's no snapshot in your project for the file yet. Try running `jest -u` first, then start wallaby and repeat the steps above, and create another gist with the Wallaby Console Output.

**Comment by ArtemGovorov** [comment]
@tomitrescak There's another thing missing in your config. For snapshots from TS files, you'll need to add a preprocessor to rename them for wallaby, as [described here](https://wallabyjs.com/docs/integration/jest.html#snapshot-testing).

**Comment by tomitrescak** [comment]
@ArtemGovorov I have configured the app as per instructions but running line tests re-creates the whole application. Also, I can see the snapshot file in the directory and interactibg with it changes test. Here is the gist (I also included updated wallaby.js and package.json file):

https://gist.github.com/tomitrescak/6d55409ecff0919c14e56e52d6267179

**Comment by ArtemGovorov** [comment]
Thanks for the config files. I'm really puzzled about your setup. Will need to ask a couple of questions and to figure out a couple of things before addressing the issue properly:

- How do you run jest without wallaby? You `package.json` doesn't have a `test` command and what interests me is how does jest (without wallaby) run at all as you don't seem to have any `transform` setting in your jest config to handle TypeScript.
- You have mentioned that you "can see the snapshot file in the directory and interactibg with it changes test". What's the full name of the snapshot file and other snapshot files? Is it `*.js.snap` or `*.ts.snap`/`*.tsx.snap`? Do you commit your snapshot files to your repo?

**Comment by ArtemGovorov** [comment]
One more question: as I have asked earlier,

> It looks like you're running line tests for src/tests/first.ts, but there's no snapshot in your project for the file yet. Try running jest -u first, then start wallaby

however from the latest log it still looks like the `src/tests/__snapshots__/first.js.snap` was not there before doing the test. Is that the case or am I missing something?

Also a quick update, I have made some modifications to try to address the issue. Could you please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and repeat the steps again (make sure the `src/tests/__snapshots__/first.js.snap` file is present before starting) and see if it's any better now?

**Comment by tomitrescak** [comment]
@ArtemGovorov the change is now fast! Good job. Yet, file is now created as 'first.tsx.snap' not sure if that's what was intended but that preprocessor thing seems to be ignored now.

I have not configured yet jest to run from command line, will do that later.
If the file was supposed to be called with "tsx" then we can close this issue (file is created by wallaby)

Thanks for the amazing support!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking!

> file is now created as 'first.tsx.snap'

Yes, it is expected, because the snapshot file name should reflect the test file name. When you'll configure jest CLI later, it'll be doing the same.

**Comment by tomitrescak** [comment]
@ArtemGovorov just a summary and I'll close this issue:

1. The *.snap preprocessor config is no longer necessary (or does not work)
2. The file is now named with .ts and .tsx, exactly the same way as jest would do

FYI, here is updated section in package.json

```json
{
"jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/preprocessor.js"
    },
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
   }
```

**Comment by ArtemGovorov** [comment]
@tomitrescak Thanks, one thing, please rearrange the `moduleFileExtensions` to have the `js` as the first extension, as it may affect wallaby:
```
"moduleFileExtensions": [
      "js",
      "ts",
      "tsx"
    ],
```

**Comment by tomitrescak** [comment]
Yeah, I already ran into that, where source mapping was blowing up. Putting it in order worked like charm. Thanks!
