### ISSUE TITLE
Update wallaby to use TS 2.1

### ISSUE THREAD

**Issue by jmwnoble** [wallabyjs/public#999]
### Wallaby.js configuration file
Having to use 
```javascript
typescript: require('typescript'),
```

and therefore install typescript as a node package, to avoid parse errors using Async/Await compiling to ES5.  

So two questions: 1) is there a plan to move wallaby to TS 2.1 2) is there away to get wallaby to use the version of typescript used by the visual studio project?

### Code editor or IDE name and version
Visual Studio 2017

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
> 1) is there a plan to move wallaby to TS 2.1

Just updated the embedded version to 2.1.5. Please restart VS to get the latest wallaby.js core.

> 2) is there away to get wallaby to use the version of typescript used by the visual studio project?

Not sure about it. If there's a node package somewhere that VS is using internally, you may be able to do 
```javascript
typescript: require('/absolute/path/to/the/vs/ts/version/typescript'),
```

**Comment by jmwnoble** [comment]
Thanks @ArtemGovorov!
